### ISSUE TITLE
infinite Waiting for the cluster to join error when make redis cluster in openshift

### ISSUE THREAD

**Issue by cherry4477** [openshift/origin#10001]
i use  templates described here [https://github.com/kelseyhightower/kubernetes-redis-cluster] to create 6 pods and 6 services. then i create a ruby pod to excecute the redis.rb, the logs are as below:

##### Version
oc version is oc v1.1.6-ldp0.3.3

##### Steps To Reproduce
1. use the template describe in [https://github.com/kelseyhightower/kubernetes-redis-cluster] to create 6 pods and 6 services, i changed the clusterIP to 192.168.X.X
2. to create a ruby pod to execute the redis.rb, in the ruby pod and do not forget executing this command: gem install redis, otherwise,the redis.rb can not be executed

##### Current Result
infinite Waiting for the cluster to join........................................................................................................................................

##### Expected Result
redis.rb should be executed successfully, and the cluster should be arranged as 3 masters and 3 slaves.
##### Additional Information
here is the log of redis.rb :
```
>>> Creating cluster
>>> Performing hash slots allocation on 6 nodes...
Using 3 masters:
172.30.122.99:6379
172.30.122.98:6379
172.30.122.97:6379
Adding replica 172.30.122.96:6379 to 172.30.122.99:6379
Adding replica 172.30.122.95:6379 to 172.30.122.98:6379
Adding replica 172.30.122.94:6379 to 172.30.122.97:6379
M: 7e42913aabc8f55dd412a959da9b0bd58a4133c9 172.30.122.99:6379
   slots:0-5460 (5461 slots) master
M: c2e738fa25345b98ca14d3d8a240980c7ffbda1b 172.30.122.98:6379
   slots:5461-10922 (5462 slots) master
M: 81078cb5c548c036277e70781901e027186c01d6 172.30.122.97:6379
   slots:10923-16383 (5461 slots) master
S: faed0f1ce212fc1e25434ca278b082c52d3668be 172.30.122.96:6379
   replicates 7e42913aabc8f55dd412a959da9b0bd58a4133c9
S: 47147b7aef64511d7fbd33be11593eee0f852c29 172.30.122.95:6379
   replicates c2e738fa25345b98ca14d3d8a240980c7ffbda1b
S: 2c95e9e47cfc0697acaf3f0c233788f11a4f17bd 172.30.122.94:6379
   replicates 81078cb5c548c036277e70781901e027186c01d6
Can I set the above configuration? (type 'yes' to accept): yes
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join..................................................................
```

and here is the log of the first pod:
```
Server started, Redis version 3.2.0
1:M 19 Jul 06:56:32.611 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 19 Jul 06:56:32.611 * The server is now ready to accept connections on port 6379
1:M 19 Jul 06:56:55.376 # configEpoch set to 1 via CLUSTER SET-CONFIG-EPOCH
1:M 19 Jul 06:56:55.400 # IP address for this node updated to 10.1.19.36
```
here is the log of the second pod :

```
1:M 19 Jul 06:56:29.264 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 19 Jul 06:56:29.264 # Server started, Redis version 3.2.0
1:M 19 Jul 06:56:29.265 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 19 Jul 06:56:29.265 * The server is now ready to accept connections on port 6379
1:M 19 Jul 06:56:57.672 # configEpoch set to 2 via CLUSTER SET-CONFIG-EPOCH
```
the 3,4,5,6 are the same.i guess that the first pod's ip has been changed,hence other pods could not communicate with it.  

any suggestions?thank you~~~

**Comment by bparees** [comment]
@cherry4477 according to @mfojtik origin isn't supporting replicasets quite yet...  were you running an openshift cluster or just using the openshift client with a kubernetes cluster?

**Comment by cherry4477** [comment]
hi, thank u for your reply. i'm running an openshift cluster

**Comment by bparees** [comment]
ok, so replicasets are not supported on openshift clusters just yet.  coming soon.

**Comment by cherry4477** [comment]
okay,thank you and looking forward to it~~~

**Comment by bparees** [comment]
@mfojtik informed me that it should be supported in master now.

**Comment by cherry4477** [comment]
so if i run all the 6 pods in the 3 masters, it would be ok?

**Comment by bparees** [comment]
as long as your masters have enough resources to run the pods, it shouldn't matter where you run them.
