### ISSUE TITLE
`oc create -f test/testdata/app-scenarios` fails to POST

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#10008]
Link to last failure: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4612/consoleFull#-200384109356c25df4e4b05b79524e5d52

##### Version
```
oc v1.3.0-alpha.0+ea204df-dirty
kubernetes v1.3.0+57fb9ac
features: Basic-Auth
```

##### Steps To Reproduce
1. [test]

##### Current Result
```
FAILURE after 2.917s: test/cmd/admin.sh:350: executing 'oc create -f test/testdata/app-scenarios' expecting success: the command returned the wrong error code

Standard error from the command:
The Service "frontend" is invalid.
spec.clusterIP: Invalid value: "172.30.17.154": provided IP is already allocated
```
##### Expected Result
Should succeed

EDIT: [updated link to last failure](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4612/consoleFull#-200384109356c25df4e4b05b79524e5d52)

**Comment by stevekuznetsov** [comment]
@juanvallejo why the assign to me?

**Comment by juanvallejo** [comment]
@stevekuznetsov Ah was not sure who to assign to this

**Comment by stevekuznetsov** [comment]
@juanvallejo if unsure, leave assignment and priority label unset, someone like @danmcp will come by to set them soon

**Comment by mfojtik** [comment]
@sgallagher can you please spend some time figuring out what is the issue here?

**Comment by sgallagher** [comment]
@juanvallejo Can you point me at a recent example? The original link has expired.

**Comment by juanvallejo** [comment]
@sgallagher Hm, the build seems to have been deleted, after checking on [ci.openshift.redhat.com/jenkins/](https://ci.openshift.redhat.com/jenkins/). Unfortunately this was the only build I can find this error happening

**Comment by miminar** [comment]
Here's another occurence: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4618/console#159471615556c25df4e4b05b79524e5d52

**Comment by juanvallejo** [comment]
Ah here's one that just happened as well: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4612/consoleFull#-200384109356c25df4e4b05b79524e5d52

**Comment by stevekuznetsov** [comment]
@miminar did we set up a Jenkins FCM for this?

**Comment by stevekuznetsov** [comment]
The failures seem to be this always:

```
Error from server: The POST operation against Pod could not be completed at this time, please try again.
```

**Comment by liggitt** [comment]
Looks like that message is coming from https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/api/rest/create.go#L106

```
// CheckGeneratedNameError checks whether an error that occurred creating a resource is due
// to generation being unable to pick a valid name.
func CheckGeneratedNameError(strategy RESTCreateStrategy, err error, obj runtime.Object) error {
	if !errors.IsAlreadyExists(err) {
		return err
	}

	objectMeta, kind, kerr := objectMetaAndKind(strategy, obj)
	if kerr != nil {
		return kerr
	}

	if len(objectMeta.GenerateName) == 0 {
		return err
	}

	return errors.NewServerTimeoutForKind(kind.GroupKind(), "POST", 0)
}
```

that's a terrible error... it looks like it's converting an AlreadyExists error into a server timeout error if it has a generate name

**Comment by liggitt** [comment]
@smarterclayton looks like the sample data for petset is the culprit... it's creating a petset and all the pods that go with it, so the pod creates will race with the petset controller, and are likely to fail with an `AlreadyExists` error

**Comment by liggitt** [comment]
bumping priority, I think we'll hit this flake a lot

**Comment by liggitt** [comment]
reopening until https://github.com/openshift/origin/pull/10240 goes in as well
