### ISSUE TITLE
create persistent volume template and create persistent volume from template on web console failed 

### ISSUE THREAD

**Issue by vanloswang** [openshift/origin#10016]
[provide a description of the issue]
##### Version

oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
##### Steps To Reproduce
1. create a nfs pv template as follow:

``` bash
# cat nfs-persistent-volume.json
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "nfs-persistent-volume",
    "creationTimestamp": null,
    "annotations": {
      "description": "NFS Persistent Volume",
      "iconClass": "icon-default",
      "tags": "instant-app"
    }
  },
  "objects": [
    {
      "kind": "PersistentVolume",
      "apiVersion": "v1",
      "metadata": {
        "name": "${NFS_PV_NAME}"
      },
      "spec": {
           "capacity": {
                "storage": "${NFS_PV_CAPACITY}"
           },
        "accessModes": [
          "ReadWriteOnce"
        ],
        "nfs": {
          "path": "${NFS_PATH}",
          "server": "${NFS_SRV}"
        },
           "persistentVolumeReclaimPolicy": "Recycle"
      }
    }
  ],
  "parameters": [
    {
      "name": "NFS_PV_NAME",
      "displayName": "NFS Persistent Volume Name",
      "description": "The name of the NFS Persistent Volume.",
      "value": "512Mi"
    },
    {
      "name": "NFS_PV_CAPACITY",
      "displayName": "Volume Capacity",
      "description": "Volume space available for data, e.g. 512Mi, 2Gi.",
      "value": "1Gi",
      "required": true
    },
    {
      "name": "NFS_PATH",
      "displayName": "NFS Export Path",
      "description": "The path of the NFS export.",
      "value": "/home/data"
    },
    {
      "name": "NFS_SRV",
      "displayName": "NFS Srv Addr",
      "description": "The IP Address or domian name of the NFS server.",
      "value": "172.0.0.1"
    }
  ],
  "labels": {
    "template": "nfs-persistent-volume-template"
  }
}
```
1. import the template

``` bash
# oc create -f nfs-pvt.yaml -n openshift
```

3.create nfs pv in web console, then it reports as follow:
can not create persistent volume "nfs-pv-xxx"。 User "admin" cannot create persistentvolumes in project "pvdbg".
##### Current Result

create failed.
##### Expected Result

create ok.

**Comment by liggitt** [comment]
Two observations:

1. I would not expect most users to have the ability to create persistent volumes, so it is likely this will still result in a forbidden error
2. The web console may be attempting to create all resources within the current project. I'm not sure if it should detect resources that should be created outside namespaces and create those as root scope objects... the web console isn't surfacing any other root scope objects

**Comment by vanloswang** [comment]
@liggitt I know this is a privileged operation, but it is more convenient to create persistent volume than do it on backgroud command line. Also we can reuse the template and just input arguments.

**Comment by vanloswang** [comment]
@jwforres Maybe we can create a persistent volume specifically belongs to a project. Drag,Click and Input  on Web Console will be more easy to do.

**Comment by jwforres** [comment]
I don't think we have any plans to do this from the web console.  You can easily create PVCs now as an end user and pick from storage classes. End users can't create PVs.
