### ISSUE TITLE
Choose to prevent jenkins servier from being created for pipeline buildconfig

### ISSUE THREAD

**Issue by bparees** [openshift/origin#10039]
If i'm using a central jenkins server to manage all my pipeline builds then i do not want a jenkins server created in my project when i create a pipeline buildconfig.

I would like a way to mark the namespace or buildconfig in such a way that the default jenkins spin up does not occur.

@siamaksade

**Comment by siamaksade** [comment]
It's good to have it both on namespace and buildconfig. The default behaviour probably should be not to spin up Jenkins and user should be able to enable auto spin-up.

**Comment by bparees** [comment]
> The default behaviour probably should be not to spin up Jenkins and user should be able to enable auto spin-up.

no i'm pretty sure we want this to work by default out of the box for a seamless pipeline experience.

the centralized CI/CD configuration is a more admin-centric choice.

**Comment by siamaksade** [comment]
Not necessarily centralized but most users won't have their Jenkins instnce in the same project that hosts am specific app containers. The same way that peoplecreate a DEV, TEST, ... projects for different phases of their apps, they'll put the shared resources across projects (Jenkins, SonarQube, Nexus, etc) in a separate infra/cicd/etc project. 

This usecase is different form a centralized enterprise Jenkins managed by Ops team across the entire organization.

**Comment by bparees** [comment]
trello: https://trello.com/c/pRTTyP42
