### ISSUE TITLE
Git authentication fail with secret

### ISSUE THREAD

**Issue by Neonell** [openshift/origin#10033]
I tried to connect my Openshift cluster with a Git repository using secret and find out that it wasn't easy to make it work.

I tried to create a secret with basic authentication and one with ssh private key. Both authentication method are working with GIT but failed when used in Openshift build-config.

The only way I could actually authenticate myself with the git repository into openshift is to give the username and password directly into the repository URL into the build-config yaml file.

##### Version
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce with basic auth
1. oc secrets new-basicauth basicsecret --username=USERNAME --password=PASSWORD
2. oc secrets add serviceaccount/builder secrets/basicsecret
3.  oc new-build  https://bitbucket.org/xx/yy.git --build-secret basicsecret 

##### Steps To Reproduce with ssh auth
1. oc secrets new-sshauth sshsecret --ssh-privatekey=.ssh/id_rsa
2. oc secrets add serviceaccount/builder secrets/sshsecret 
3.  oc new-build git@bitbucket.org:xx/yy.git --build-secret sshsecret  

##### Current Result
Both method doesn't work and return authentication errors.

If I edit the URL from the basicauth build and set it to: https://username:password@bitbucket.org/xx/yy.git it work fine.

I could download without problem my repository on the master with git command and ssh private key.

##### Expected Result
I can authenticate myself with a secret basic or ssh authentication.

##### Additional Information
Log output from the pod with the ssh authentication secret:
I0726 09:36:48.819109       1 builder.go:57] Master version "v1.2.0", Builder version "v1.2.0"
I0726 09:36:48.823723       1 builder.go:145] Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:92233720368547, CPUShares:2, CPUPeriod:100000, CPUQuota:-1, MemorySwap:92233720368547}
I0726 09:36:48.825903       1 source.go:197] Downloading "ssh://git@bitbucket.org/xx/yy.git" ...
F0726 09:36:49.463157       1 builder.go:204] Error: build error: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bparees** [comment]
to provide git credentials for accessing a repository during a build, please see:
https://docs.openshift.org/latest/dev_guide/builds.html#using-private-repositories-for-builds

the purpose of the --build-secret flag is to allow you to make the value of a secret available to your actual build steps (the assemble script in the case of source-type build, or the dockerfile in the case of a docker-type build), it is not used to access your source repository.

**Comment by bparees** [comment]
(you will need to add the secret reference to your buildconfig after creating it, there is no way to specify the secret as part of invoking new-build)

**Comment by Neonell** [comment]
Hi,

Thanks a lot for the answer I tried first by editing the yaml file and adding the secret and then only with the --build-secret flag. What is funny is that the yaml is the same when I create it with the --build-secret file as the one they ask to add in the documentation:

For example:
oc new-build https://bitbucket.org/xx/yy.git --build-secret basicsecret -o json > test.json

Will output.
"source": {
                    "type": "Git",
                    "git": {
                        "uri": "https://bitbucket.org/xx/yy.git"
                    },
                    "secrets": [
                        {
                            "secret": {
                                "name": "basicsecret"
                            },
                            "destinationDir": "."
                        }
                    ]
                }


And you say you have to set it manually in the yaml, so the yaml file looks like this:
source:
    type: Git
    git:
      uri: 'git@bitbucket.org:xx/yy.git'
    sourceSecret:
      name: sshsecret
    secrets: null

And like this it's working actually. 

I get confused because first I tried to edit the yaml and add the secretsource but for some reason it didn't worked so then I tried with the flag too. I can't explain what I did wrong but I saved my json configuration file and it looks like this:
 "source": {
                    "type": "Git",
                    "git": {
                        "uri": "git@bitbucket.org:xx/yy.git"
                    },
                    "sourceSecret":{
                        "name": "sshsecret"
                    }
                }

But whatever sorry for the time loss and thanks a lot for the answer.

Best Regards,
Neo

**Comment by bparees** [comment]
hm, i am not sure what the issue is between the file you edited originally with sourceSecret, and the one that ultimately worked for you.  but glad to hear you got it working!

(and the file created with --build-secret is definitely different from the other two you pasted, the --build-secret one is setting the "secrets" array field, not the "sourceSecret" field.)
