### ISSUE TITLE
`os::util::repository_relative_path` breaks when used from a different directory

### ISSUE THREAD

**Issue by enj** [openshift/origin#10041]
`os::util::repository_relative_path` fails when you have `cd` or `pushd` into a different directory than from what the test shell script was called from.  This is because it is looking for the location of the shell script using `realpath` relative to the starting location instead of the current location.

cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@Miciah is there any sane way to determine how the working directory has changed from the original working directory that was used to call a script? The issue above is happening when I call `realpath $0`, basically, as `$0` is relative.

Alternatively, we can just detect this case and fall back to not providing any utility. That's simpler.

**Comment by Miciah** [comment]
I don't have any clever ideas on determining the original working directory, but could we save it in a global when `os::util::repository_relative_path` is defined? That is, `readonly ORIG_PWD="$PWD"` immediately before or after the function definition, and do a `pushd`/`popd "$ORIG_PWD"` in the function.

**Comment by stevekuznetsov** [comment]
@Miciah I like that.

**Comment by enj** [comment]
@stevekuznetsov why didn't you think of that :stuck_out_tongue: 
The `pushd` / `popd` version of my code was so much nicer.

**Comment by stevekuznetsov** [comment]
@enj your PR isn't in yet ... you can always wait :)
