### ISSUE TITLE
devenv_ami and other jenkins jobs should use Docker 1.10 "push as v1" instead of downgrading

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#10059]
As seen [here](https://ci.openshift.redhat.com/jenkins/job/devenv_ami/4685/console):
```
+ vagrant push-openshift-release --registry docker.io/

exit $exitcode
[ec2-user@ip-172-18-12-220 ~]$ export TERM=vt100
[ec2-user@ip-172-18-12-220 ~]$ stty raw -echo
[ec2-user@ip-172-18-12-220 ~]$ Error while running ssh/sudo command: 
echo "Pushing release images"
set -e
pushd /data/src/github.com/openshift/origin
  OS_PUSH_BASE_IMAGES="" OS_PUSH_BASE_REGISTRY="docker.io/" hack/push-release.sh
popd
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

@smarterclayton do you understand this?

/cc @jwforres @danmcp

**Comment by smarterclayton** [comment]
Were there any other logs?

**Comment by stevekuznetsov** [comment]
Not that I can tell. Very weird.

**Comment by smarterclayton** [comment]
If it's brand new it could be due to my merged changes.  Not sure how.

**Comment by smarterclayton** [comment]
Not positive, but it looks like rebuilding the images on docker 1.9.1 is failing, or not happening

```
  vagrant build-origin-base-images
  vagrant build-origin --images
```

Base images works, but `build-origin --images` does nothing (displays no output).  That's deeply suspicious (after downgrade, no images should be present, so builds should work).

Actually... looking at build-origin --images, it's completely wrong.

**Comment by smarterclayton** [comment]
`build-origin --images` does not do the right thing, so the short term fix is going to be invoke the correct image build flow on Docker 1.9.  The next step would be to stop downgrading to Docker 1.9, and instead use the new flag added to Docker 1.10 to push using v1 schema.

**Comment by smarterclayton** [comment]
Ok, fixed for now.  We now need to switch to stop downgrading 1.9, use 1.10, and use the "push v1".

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/devenv_ami/4726/console passed

**Comment by smarterclayton** [comment]
@bparees FYI, repurposing this.

**Comment by bparees** [comment]
@smarterclayton are you going to update the push operations done within our various vagrant plugins (eg the s2i image tests/pushes) to do this?

**Comment by bparees** [comment]
(right now the s2i/db image jenkins jobs explicitly downgrade to 1.9)

**Comment by smarterclayton** [comment]
I don't know that I am necessarily, but someone needs to, and we should do it for all our jobs.  I think we need to update our AMIs first to have the "push as v1" setting.  OR we change that setting at the end of the AMI and restart docker.

**Comment by bparees** [comment]
push as v1 is a dockerconfig setting, or an arg on the docker push command?

**Comment by smarterclayton** [comment]
/etc/sysconfig/docker flag on startup of the daemon

**Comment by stevekuznetsov** [comment]
That belongs in vagrant-openshift

**Comment by bparees** [comment]
@stevekuznetsov why don't we want to do it in the ami?

**Comment by stevekuznetsov** [comment]
I don't understand your question -- we configure `/etc/sysconfig/docker` in `vagrant install-origin-base`. We should add this new config option to that preexisting logic.
