### ISSUE TITLE
Logging data in small chunks becomes inefficient.

### ISSUE THREAD

**Issue by rflorenc** [openshift/origin#10052]
We have an aggregate logging test which uses 'logger' to send strings of different sizes at different rates to syslog. These log files are then curated into .json files by the fluentd pods and bulk uploaded to the elasticsearch pod.
When logging in small chunks of for example 15kbs or 30kbs, I/O is weirdly inefficient. 

This is possibly related to the way bulk uploads operate as explained here:
https://www.elastic.co/guide/en/elasticsearch/guide/current/bulk.html#_how_big_is_too_big

##### Version
openshift v3.2.1.3-1-gcbaf600
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

##### Steps To Reproduce
Example for 10 node cluster

1. Create logging project from the openshift ansible template: 
Example: https://github.com/rflorenc/svt/blob/master/logging_metrics_performance/enterprise_logging/enterprise-logging-setup.sh

2. The test is basically running the following for each of the cluster nodes:
`i=0;
while [ $i -lt ${xtimes} ]
do
        echo "Container ${i} :"
        docker run -d gcr.io/google_containers/busybox:1.24 "/bin/sh" "-c" "while true ; do logger ${string} ; sleep ${delay}; done"
        ((i++))
done`

Where ${string} is the length of the string to log and ${delay} sets the interval.
Running a simple while loop on each node also works.
`while true ; do logger ${string} ; sleep ${delay}; done`

##### Current Results

http://perf-infra.ec2.breakage.org/incoming/clustermasterfluentd/logger_10n_5ppn_15kbs_10m_1/tools-default/espod/pidstat/file_io.html

http://perf-infra.ec2.breakage.org/incoming/clustermasterfluentd/logger_10n_5ppn_30kbs_10m/tools-default/espod/pidstat/file_io.html

http://perf-infra.ec2.breakage.org/incoming/clustermasterfluentd/logger_10n_5ppn_60kbs_10m/tools-default/espod/pidstat/file_io.html

**Comment by rflorenc** [comment]
@timothysc @jeremyeder @ekuric

**Comment by jcantrill** [comment]
@richm @ewolinetz @lukas-vlcek  I presume this is is tuning setting we would provide to fluentd?  @sosiouxme is this a place for the suggested 'logging controller' to maybe dynamically tune fluentd

**Comment by lukas-vlcek** [comment]
@rflorenc I think it would be useful if you can provide more details about specific setup for Elasticsearch. I assume that each chart (the links you provided) contains data for only a single Elasticsearch process (not sure how many ES nodes you were running but we see only one node performance stats, correct?).

First thing that caught my attention was related memory usage:

- http://perf-infra.ec2.breakage.org/incoming/clustermasterfluentd/logger_10n_5ppn_15kbs_10m_1/tools-default/espod/pidstat/memory_usage.html
- http://perf-infra.ec2.breakage.org/incoming/clustermasterfluentd/logger_10n_5ppn_30kbs_10m/tools-default/espod/pidstat/memory_usage.html
- http://perf-infra.ec2.breakage.org/incoming/clustermasterfluentd/logger_10n_5ppn_60kbs_10m/tools-default/espod/pidstat/memory_usage.html

If I read it correctly, then no matter what scenario you were testing charts show that Elasticsearch process is always at capacity which was specified by `Xmx1g` though it should have started at `Xmx256m` (`[...]/bin/java_-Xms256m_-Xmx1g_-Djava.awt.hea[...]`). If this is true then you are not operating ES nodes in good environment. Lack of memory will definitely lead to high GC pressure in JVM impacting all internal ES threads (and possibly leading to stop world CG cycles too).

- Do you think you can start capturing pbench data before ES node is started? This should allow us to see how memory usage jumps quickly from 256m to 1g and stays flat all the time.
- Can you try to give ES more memory room and repeat the test?

**Comment by richm** [comment]
Should this issue be in the https://github.com/openshift/origin-aggregated-logging/issues ?

**Comment by ewolinetz** [comment]
Fluentd has the ability to tune its buffered output for sending the batch [1], we don't currently give a way to tune it other than updating the fluentd config (with a configmap *void where prohibited).  We had made mention of possibly giving an easier way to do this in the perf plan for Aggregated logging, but I don't remember it going much further than that.

[1] https://github.com/uken/fluent-plugin-elasticsearch#buffered-output-options

**Comment by rflorenc** [comment]
@lukas-vlcek 

> I think it would be useful if you can provide more details about specific setup for Elasticsearch. I assume that each chart (the links you provided) contains data for only a single Elasticsearch process (not sure how many ES nodes you were running but we see only one node performance stats, correct?).

Yes, only one espod is running in the cluster but I didn't turn any knob or tune anything specific.

> If this is true then you are not operating ES nodes in good environment. Lack of memory will definitely lead to high GC pressure in JVM impacting all internal ES threads (and possibly leading to stop world GC cycles too)

The tests are running on EC2 M4.4xLarge (master, registry/router) and M4.Large (nodes). The thing is this cluster also has metrics deployed, hence the other java processes (pid 4948: cassandra) you see in the pbench data. I'll look into deleting metrics (/cc @ekuric ) and compare.  

> 
Do you think you can start capturing pbench data before ES node is started? This should allow us to see how memory usage jumps quickly from 256m to 1g and stays flat all the time.

Yes, I can start pbench when the project is being created. 

>
Can you try to give ES more memory room and repeat the test?

Sure. What would be the best way of doing that on project creation time?

**Comment by lukas-vlcek** [comment]
Well my understanding is that Xmx is automatically set to (Avail RAM)/2, see https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/run.sh#L25

@ewolinetz @richm Do you know if we can override `Xmx` settings in `ES_JAVA_OPTS` somehow before ES process is started?

**Comment by jeremyeder** [comment]
cc/ @portante

**Comment by richm** [comment]
@lukas-vlcek yes - the env. var. INSTANCE_RAM can be set e.g. `INSTANCE_RAM=4G`

**Comment by lukas-vlcek** [comment]
@richm So this means that by default `INSTANCE_RAM` is set here https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/Dockerfile#L13 but @rflorenc should override the `INSTANCE_RAM` value before `run.sh` script is run, correct?

**Comment by lukas-vlcek** [comment]
So probably by providing custom `ES_INSTANCE_RAM` template value which is used here: https://github.com/openshift/origin-aggregated-logging/blob/master/deployer/templates/es.yaml#L116 ?

**Comment by richm** [comment]
@lukas-vlcek yes

**Comment by rflorenc** [comment]
@richm @lukas-vlcek thanks, will try that as well.

**Comment by lukas-vlcek** [comment]
@rflorenc be munificent, give it a lot, just for the sake of this test. As Rich said, give it 4G, this should result to `Xmx=2G` (may be you can try even more than physical Mem avail on EC2 M4.4xLarge because the Xmx will always result to half of that).

**Comment by rflorenc** [comment]
@lukas-vlcek @richm 
This is how I've been running it from the start. 
Looks like it's not picking up the correct value?

```
Adding required roles
oauthclient "kibana-proxy" deleted
--> Deploying template logging-deployer-template for "logging-deployer-template"
     With parameters:
      MODE=install
      IMAGE_PREFIX=docker.io/openshift/origin-
      IMAGE_VERSION=latest
      IMAGE_PULL_SECRET=
      INSECURE_REGISTRY=false
      ENABLE_OPS_CLUSTER=false
      KIBANA_HOSTNAME=kibana.example.com
      KIBANA_OPS_HOSTNAME=kibana-ops.example.com
      PUBLIC_MASTER_URL=https://ec2-54-187-192-234.us-west-2.compute.amazonaws.com:8443
      MASTER_URL=https://ip-172-31-10-247.us-west-2.compute.internal:8443
      ES_CLUSTER_SIZE=1
      ES_INSTANCE_RAM=8G
      ES_PVC_SIZE=
      ES_PVC_PREFIX=logging-es-
      ES_PVC_DYNAMIC=
      ES_NODE_QUORUM=
      ES_RECOVER_AFTER_NODES=
      ES_RECOVER_EXPECTED_NODES=
      ES_RECOVER_AFTER_TIME=5m
      ES_OPS_CLUSTER_SIZE=
      ES_OPS_INSTANCE_RAM=8G
      ES_OPS_PVC_SIZE=
      ES_OPS_PVC_PREFIX=logging-es-ops-
      ES_OPS_PVC_DYNAMIC=
      ES_OPS_NODE_QUORUM=
      ES_OPS_RECOVER_AFTER_NODES=
      ES_OPS_RECOVER_EXPECTED_NODES=
      ES_OPS_RECOVER_AFTER_TIME=5m
      FLUENTD_NODESELECTOR=logging-infra-fluentd=true
      ES_NODESELECTOR=
      ES_OPS_NODESELECTOR=
      KIBANA_NODESELECTOR=
      KIBANA_OPS_NODESELECTOR=
      CURATOR_NODESELECTOR=
      CURATOR_OPS_NODESELECTOR=

```

**Comment by lukas-vlcek** [comment]
@rflorenc I see

    ES_INSTANCE_RAM=8G
    [...]
    ES_OPS_INSTANCE_RAM=8G

this is not what you wanted? Has this value been correctly applied? Like can you see what was the `-Xmx??` value used for Elasticsearch process (you can see it via `top` and also in `pbench` results output).

**Comment by ewolinetz** [comment]
@rflorenc what version of the ES image are you using? is it also 3.2.1?

**Comment by sosiouxme** [comment]
For a time, our ES image failed to actually apply the specified RAM
settings and you just got the ES defaults. I don't remember exactly when we
noticed and fixed this but the current images should definitely have the
fix. So do check what Java is getting in the container... there should be
two -Xmx values, the first one being the ES defaults (hardcoded), and later
in the command line, half the value that we specify (by these parameters,
4G - other half is left for the kernel page cache to fill) to override the
default.

**Comment by rflorenc** [comment]
@lukas-vlcek 
The value wasn't correctly applied.

https://github.com/rflorenc/svt/blob/efk_pbench/logging_metrics_performance/enterprise_logging/enterprise-logging-setup.sh#L102

`
/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true
`

@richm you mentioned earlier today this can be worked around by overriding value in the the dc? How can I go about doing that?

I was told to stick to the openshift-ansible infrastructure templates and this seems to be the issue here.
@timothysc

**Comment by richm** [comment]
```/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true ..... -Xmx4g```

```-Xmx``` appears twice in the output - the latter value is the one that takes effect - this is due to the way the elasticsearch startup scripts work.

**Comment by rflorenc** [comment]
I think this can be closed, it's not a logging issue. Thanks all.

**Comment by rflorenc** [comment]
Thank you all, It's clear now.
