### ISSUE TITLE
[DOC] How to add another docker registry for oc import-image

### ISSUE THREAD

**Issue by kwoodson** [openshift/origin#10069]
I'm attempting to test a new ose-docker-registry on a cluster where I have it configured only for registry.access.  I need to access a different registry where the recently built docker-registry lives.  I have very little idea on where to modify docker registry authentication for adding another registry.

##### Version
oc v3.2.1.9-1-g2265530
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. Import an image from an external registry that requires auth. oc import-image registery.qe.openshift.com/openshift3/ose-docker-registry:v3.2.1.12

##### Current Result
Does not work as there are configuration requirements.
##### Expected Result
A document or ability to oc import-image from an external registry.
##### Additional Information
As you can see I can run the command but the import will fail.  I do have credentials but I'm unsure as to where it needs to live so that I can make this work.  An option to pass in my docker creds(config.json) file would be awesome.

 oc import-image --from='registry.qe.openshift.com' openshift3/ose-docker-registry:v3.2.1.12 --confirm
The import completed successfully.

Name:			ose-docker-registry
Created:		Less than a second ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2016-07-27T16:26:42Z
Docker Pull Spec:	172.30.56.234:5000/default/ose-docker-registry

Tag		Spec				Created			PullSpec	Image
v3.2.1.12	registry.qe.openshift.com	Less than a second ago			import failed: you may not have access to the Docker image "registr...

**Comment by kwoodson** [comment]
I tried this but was unsuccessful.

https://docs.openshift.org/latest/dev_guide/managing_images.html#private-registries

**Comment by gyj0825** [comment]
I also encountered the same problem.When the registry is insecure can be imported.
Does not support importing image from the secure registry?

**Comment by miminar** [comment]
@kwoodson, @gyj0825 could you please provide some details? What was the output of import-image command. What does `oc describe is/target-image-stream` show?

AFAIK importing from authenticated registries works.

**Comment by soltysh** [comment]
> Does not support importing image from the secure registry?

Yes the document pointed in https://github.com/openshift/origin/issues/10069#issuecomment-235728844 is the one that is working.

> The reason is because the registry using a self-signed certificate?

If you have that you need both, iow. `--insecure` (which will not check certificate authenticity) and the secret to actually access the registry.

**Comment by miminar** [comment]
Closing now, feel free to re-open if it doesn't work for you.
