### ISSUE TITLE
user management features user stories and feature roadmap

### ISSUE THREAD

**Issue by lexlapax** [openshift/origin#1006]
Although I've seen some direction around what the user / account / system management apis and corresponding back-end features look like.. 
In the [openshift_model doc](https://github.com/openshift/origin/blob/master/docs/openshift_model.md) and the [other](https://github.com/openshift/origin/blob/master/docs/proposals/capabilities.md) [docs](https://github.com/openshift/origin/blob/master/docs/proposals/policy.md) , including the trello boards for openshift, I see bits and pieces.
I was wandering if there was a set of user stories that you're working against from
a developer (openshift user)
a project admin 
an account admin
a system operator (overall openshift admin)
an external orchestrator on behalf of one of the above users that calls different openshift apis.

If there is one, I wanted to see if we can add our user stories to it (if not already there) based on how we've operated openshift 2.0 for 2+ years, more specifically interested in the 4th and 5th use cases...

**Comment by lexlapax** [comment]
BTW, great job on getting to the beta 1 milestone, which has most of the container and deployment workflow bits almost figured out. I was testing it for the user and account features and APIs... I did look through the trello boards but saw a few issues scattered through different portions..  the request

**Comment by smarterclayton** [comment]
@lexlapax The answer is yes, but the use cases are scattered.  I think your feedback on 4 and 5 are critical - if you'd like to describe them here, we can draft a document which is a superset of the policy and authz / authn docs to capture them.

**Comment by lexlapax** [comment]
Thanks @smarterclayton , 
I've started with a set of user stories that have been a particularly thorny issue for our IT and other deployments.. We can probably add to the basic user stories (and implementation notes) as we go along.

As a system operator, I would like to
- make an api call for CRUD operations (create/read/update/delete) on an account object in openshift
- make an api call for CRUD operations on a project admin object in openshift
- make an api call for CRUD operations on a developer object user
- make an api call for CRUD operations on a project object
- make an api call for CRUD operations on system operator accounts 
- have all system operator actions to be logged and time stamped
- allow/authorize a machine account to take the above actions
- make a call to non-destructively rebalance (for load/memory/cpu) an application or a service across nodes

As an external orchestrator, I would like to 
- use a machine account to make api calls to call CRUD operations on an account object
- use a machine account to make api calls to call CRUD operations on an developer object
- use a machine account to make api calls to call CRUD operations on an project object

Some notes (implementation, elaboration), 
Most enterprises have existing dashboards, orchestration systems, IDM systems, order/cloud management systems etc.
With openshift 2.x we've had to hack into and create our own apis for orchestration systems to create account/user objects in openshift.. and with upgrades, it becomes rather painful to integrate them again and again.

For the sysop use cases, the ability to call crud API operations on an account object may be a good enough starting point, which would potentially allow the system operator to get an authorization token with privilege escalation (or account masquerading) that allows it to do other operations.

For the CRUD operations, the api (likely RESTful calls) are a must, rather than relying on commandline scripts. The sysop api endpoints can be a separte URI for additional protection against unauthorized use.

For authorizations (for machine account, privilege escalation or account masquerading), OAUTH is an acceptable and probably a better vehicle to go after. 

-sandeep

**Comment by liggitt** [comment]
Most of these are addressed in 1.0:

> - make an api call for CRUD operations (create/read/update/delete) on an account object in openshift
> - make an api call for CRUD operations on a project admin object in openshift
> - make an api call for CRUD operations on a developer object user

The `User`, `Identity`, and `UserIdentityMapping` API objects allow management of login identities and mapped users.

> - make an api call for CRUD operations on a project object

The `Project` and `Namespace` API objects allow this

> - make an api call for CRUD operations on system operator accounts 

The `ServiceAccount` API objects allow this

> - allow/authorize a machine account to take the above actions
> - use a machine account to make api calls to call CRUD operations on an account object
> - use a machine account to make api calls to call CRUD operations on an developer object
> - use a machine account to make api calls to call CRUD operations on an project object

Service account users can be granted any role a human user can.

I think the only thing mentioned that still needs work is logging/auditing. I'd recommend a separate issue to track that.

**Comment by liggitt** [comment]
Closing as resolved
