### ISSUE TITLE
FailedSync errors when using a Daemonset

### ISSUE THREAD

**Issue by zaina** [openshift/origin#10066]
I'm running into an issue using daemonsets in my Origin environment: The pods are deployed then die with FailedSync and CrashLoopBackOff errors. I tried running the same pod outside a daemonset and it works fine. Any ideas on what might be wrong?

`Warning   FailedSync Error syncing pod, skipping: failed to "StartContainer" for "new-app" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=new-app pod=new-app-3io4w_project-name(4464eafd-4abf-11e6-8969-fa163e7cf49c)"`

I tried disabling the Liveness Probe, but the pods still died with FailedSync errors: 
`Liveness probe failed: dial tcp 10.1.37.3:28588: i/o timeout
Killing container with docker id 104e7914197a: Need to kill pod.`

##### Version
oc v1.2.0
openshift v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

##### Steps To Reproduce
1. Deploy a new-app using a daemonset
2. Containers start up then die abruptly

##### Current Result
```shell
# oc get pods
NAME            READY     STATUS                    RESTARTS   AGE
new-app-2pogp   0/1       CrashLoopBackOff          12         47m
new-app-2zy62   0/1       CrashLoopBackOff          12         47m
new-app-3io4w   0/1       CrashLoopBackOff          12         47m
new-app-6nzet   0/1       CrashLoopBackOff          12         47m
```
##### Expected Result
Pods remain in running state.

**Comment by liggitt** [comment]
can you look at the YAML of a crashing pod and a pod you created by hand and see if there are any differences? My guess is that the one created from a daemonset is running as a different UID

**Comment by zaina** [comment]
By UID you mean the runAsUser field? Neither pods have that field set and both are running with `privileged: false`.

**Comment by liggitt** [comment]
can you provide the yaml of the working pod and crashing pod side-by-side?

**Comment by ncdc** [comment]
@liggitt FYI we're working this in https://bugzilla.redhat.com/show_bug.cgi?id=1361349. If you want to help, the more the merrier 😄, but my team is handling things in the bz. We'll update this once the bz is resolved, but we won't provide status updates/questions/etc here.

cc @tracyrankin @sttts @ingvagabund @pmorie @eparis

**Comment by ncdc** [comment]
Closing this as the referenced bz has turned into a docs bug for how users can do this.
