### ISSUE TITLE
Make parents calculation more strict

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#10079]
When marking parents in `oadm top images` we're comparing only the top most layer, which might lead to erroneous information if two images will have exactly the same layer (might happen when exactly the same operation is invoked). We should rather verify the sequence for that. See [this comment](https://github.com/openshift/origin/pull/9587#discussion_r72574740).

**Comment by soltysh** [comment]
@miminar fyi

**Comment by bparees** [comment]
trello'd https://trello.com/c/z5JvS6Dx
