### ISSUE TITLE
template.service.sepc.ports.targetport：Specify the variable error

### ISSUE THREAD

**Issue by lifei825** [openshift/origin#10072]
errlog:

Cannot create service "ogg-target-test-tcp". Service "ogg-target-test-tcp" is invalid: [spec.ports[2].targetPort: Invalid value: "30014": must be an IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])*, it must contain at least one letter [a-z], and hyphens cannot be adjacent to other hyphens): e.g. "http", spec.ports[3].targetPort: Invalid value: "30015": must be an IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])*, it must contain at least one letter [a-z], and hyphens cannot be   to other hyphens): e.g. "http"].

```

```
 template config:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: app
    name: ${APPLICATION_NAME}-tcp
  spec:
    ports:
    - name: 7809-tcp
      port: 7809
      protocol: TCP
      targetPort: 7809
    - name: 22-tcp
      port: 22
      protocol: TCP
      targetPort: 22
    - name: dy1-tcp
      port: ${DY_PORT_A}
      protocol: TCP
      targetPort: ${DY_PORT_A}
    - name: dy2-tcp
      port: ${DY_PORT_B}
      protocol: TCP
      targetPort: ${DY_PORT_B}”“”
```

```

**Comment by liggitt** [comment]
To specify a port number, the value must be unquoted.

**Comment by liggitt** [comment]
Unfortunately, there's not a way to have an unquoted parameter value in a template currently

**Comment by lifei825** [comment]
thanks

**Comment by mansab** [comment]
Has this been fixed in newer versions of Openshift CLI?
