### ISSUE TITLE
flake: oc import-image php, image stream was updated

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#10080]
Seen in https://github.com/openshift/origin/pull/9240, full log: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4110/console

```
Running test/cmd/migrate.sh:38: executing 'oc import-image --from=php:latest test:2 --confirm' expecting success...
FAILURE after 1.827s: test/cmd/migrate.sh:38: executing 'oc import-image --from=php:latest test:2 --confirm' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: Operation cannot be fulfilled on imagestream "test": the image stream was updated from "4858" to "4860"
```

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4152/consoleFull

**Comment by pravisankar** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/5018/console

**Comment by jcantrill** [comment]
https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/1015/console
