### ISSUE TITLE
auto-generated certificates should be valid as client certificates too

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#10085]
From https://trello.com/c/naQqeIWM we now have signed server certificates generated automatically for services. With a small tweak, these could also be used as client certificates to identify pods from one service to another.
##### Version

```
$ oc version
oc v1.3.0-alpha.2+e430003-dirty
kubernetes v1.3.0+57fb9ac
```
##### Steps To Reproduce
1. Create service with annotation `service.alpha.openshift.io/serving-cert-secret-name: something`
2. `oc extract secret/something`
3. `openssl x509 -in tls.crt -noout -text`
##### Current Result

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1959928277197880331 (0x1b3310624b9f7c0b)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=openshift-service-serving-signer@1469631583
        Validity
            Not Before: Jul 28 14:13:54 2016 GMT
            Not After : Jul 28 14:13:55 2018 GMT
[...]
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
```
##### Expected Result

```
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
```

Alternatively, it could be a separate annotation and/or cert for the client cert.
##### Additional Information

Not familiar with the golang API for generating these. http://www.zytrax.com/tech/survival/ssl.html#x509 seems to indicate the underlying field is `ExtendedKeyUsage` and the relevant value is `clientAuth`.

**Comment by liggitt** [comment]
I don't think those should be used as client certs. Misusing the serving cert requires access to the cert/key AND the ability to trick DNS. Misusing the cert as a client cert would just require access to the cert/key, and you could use that from anywhere.

**Comment by sosiouxme** [comment]
Discussed with deads yesterday, agreed it's not as hard to misuse, but you would have to *get* it in the first place. That kind of access would imply bad things already. But I'll leave it to him as to whether to reopen.

**Comment by deads2k** [comment]
> don't think those should be used as client certs. Misusing the serving cert requires access to the cert/key AND the ability to trick DNS. Misusing the cert as a client cert would just require access to the cert/key, and you could use that from anywhere.

It requires getting the cert and key AND a server that is configured to trust that particular key/cert pair.  Anything that has managed to steal a cert/key from a given namespace already had sufficient access to steal/impersonate/disrupt the thing you were already trusting.  These are secrets, if someone has access to the secrets in your namespace, they've got you.

I think the argument for irrevokability and lifespan is stronger.  How about an option to generate a client cert with short lifespan?

**Comment by sosiouxme** [comment]
I'd feel happier about short-lived client certs if the cert generator renewed expiring certs and restarted the pods for the service. I guess the same goes for server certs, really.

**Comment by deads2k** [comment]
> I'd feel happier about short-lived client certs if the cert generator renewed expiring certs and restarted the pods for the service. I guess the same goes for server certs, really.

Yeah, let's see if we can agree on what we'd like to do though.  I think the only realistic concern about doing this is the long-lived nature of the cert.  If they were revocable, then the "someone else can present this" wouldn't matter since the act of getting the power implied the power to take what they wanted already.  It's the fact that you can never trust that subject again that's problematic.

One interesting option would be to allow a request to sign a namespaced username for a short period of time.

@sosiouxme we're unlikely to get those changes in for 3.3.

**Comment by mwringe** [comment]
Is there any update on this?

**Comment by mwringe** [comment]
@deads2k any thoughts or opinions on if we will ever be able to use do this?

**Comment by deads2k** [comment]
> @deads2k any thoughts or opinions on if we will ever be able to use do this?

No short term plans.  Doubtful for 2017.

**Comment by smarterclayton** [comment]
I want to circle the wagons on this one and get closure on a final decision as to whether we can solve this effectively.  @soltysh has been chasing the "restart on secret change" pet.

**Comment by soltysh** [comment]
There's a card on PM board: https://trello.com/c/0S0iyU74/864-2-add-controller-to-regenerate-service-serving-certificates-follow-up to address this, so I think we want to have it. The biggest problem is what Clayton mentioned "restart on secret change" which is a prereq for making the certs be very short lived. I've talked with David and he mentioned something like hours, with default being 24h.
