### ISSUE TITLE
oc cluster up docker version issue

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#10087]
I tried `oc cluster up` for the first time this morning and got this error:

```
-- Checking Docker client ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:latest image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Checking Docker version ... FAIL
   Error: Invalid character(s) found in patch number "1.fc21"
```
I metioned it to @csrwng.  

My docker version:
```
Docker version 1.8.1.fc21, build 32b8b25/1.8.1
```

Seems that my vagrant box is old, thus my docker is old (pre 1.9), thus things dont work. I'm updating now to see if it will resolve the problem, but creating this issue to document.

**Comment by danmcp** [comment]
@benjaminapetersen 1.8 is certainly not supported.

**Comment by benjaminapetersen** [comment]
Yup, all is well after I updated vagrant.  Hopefully a quick and easy doc fix!  I have a file outlining steps to get up and running, I can PR the contributing.adoc here & origin-web-console as well if that would be helpful.

**Comment by csrwng** [comment]
cluster up has been updated to check for docker 1.9 or above.
