### ISSUE TITLE
GitHub webhook documentation linked when editing configuration

### ISSUE THREAD

**Issue by matthicksj** [openshift/origin#10098]
When I was looking for the webhook information I initially went to the build and editing the configuration.  In this view, there is information about enabling the triggers, but the webhook links aren't listed for copying and the help isn't linked either.

##### Version
OpenShift Online 3

##### Steps To Reproduce
1. Create a new application
2. Click to the build
3. Click Action -> Edit

##### Current Result
In the Triggers section, the webhooks can be enabled but you can't see the actual webhook URL's

##### Expected Result
Option 1: In the Triggers section, the webhooks should be listed (as they are on the Configuration tag) and the documentation (https://docs.openshift.com/online/dev_guide/builds.html#webhook-triggers) should be linked as well to Learn More.

Option 2: At a minimum we should note that the webhooks themselves are visible on the configuration tab.

##### Additional Information

**Comment by jwforres** [comment]
@jhadvig in case you didnt get notified when this got assigned yesterday, this would be next on the list for you to look at
