### ISSUE TITLE
Add unit test for crypto.SecureTLSConfig to double check on go version bumps

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#10104]
SecureTLSConfig specifies preferred ciphers for serving. When we switch go versions, a unit test should inform us when more secure suites are available, so we remember to add them if desired

**Comment by enj** [comment]
So it is not possible to do this in a unit test.  Jordan wants us to start a checklist for things to verify when upgrading go versions, and to put this on it.  @mfojtik I will let you handle the specifics of that.
