### ISSUE TITLE
hack/test-cmd.sh broken on newer Mac (maybe?)

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1011]
Mac seems to have problem with PEM format in curl or something?

```
curl https://localhost:8443/healtz --key openshift.local.certificates/admin/key.key --cert openshift.local.certificates/admin/cert.crt 

curl: (58) SSL: Can't load the certificate "openshift.local.certificates/admin/cert.crt" and its private key: OSStatus -25299
```

**Comment by liggitt** [comment]
from curl manpage:

> --cert <certificate[:password]>
> ...
> The certificate must be in PKCS#12 format if using Secure Transport, or PEM format if using any other engine.
> ...
> (iOS and Mac OS X only) If curl is built against Secure Transport, then the certificate string can either be the name of a certificate/private key in the system or user keychain, or the path to a  PKCS#12-encoded  certificate and private key.

we can create a p12 cert file like this:
```
openssl pkcs12 -export -inkey key.key -in cert.crt -out cert.p12 -password pass:
```

What's less clear is when we should do this, or how to detect we need to use the p12 cert form

**Comment by smarterclayton** [comment]
Maybe I'll just add a CURL_PK12_ENCODE for the test stuff

**Comment by liggitt** [comment]
If you need to include the entire cert chain in the p12 cert, do this:
```
openssl pkcs12 -export -inkey key.key -in cert.crt -CAfile root.crt -chain -out cert.p12 -password pass:
```

**Comment by smarterclayton** [comment]
Fixed by referenced, thanks
