### ISSUE TITLE
flake: cmd/basicresources:  User "test-user" cannot create deploymentconfigs in project "default"

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#10133]
```
FAILURE after 0.295s: test/cmd/basicresources.sh:306: executing 'oc run --image=openshift/hello-openshift test' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: User "test-user" cannot create deploymentconfigs in project "default"
```

Seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4248/consoleFull#-74446494156c25df4e4b05b79524e5d52)

**Comment by mfojtik** [comment]
I think this smells as well:

```
SUCCESS after 0.339s: test/cmd/basicresources.sh:304: executing 'oc project ''' expecting success; re-trying every 0.2s until completion or 60.000s
```

it seems like the `oc project '$(oc project -q)'` returns ''

**Comment by liggitt** [comment]
@stevekuznetsov are you sure you didn't introduce an issue with switching projects in that PR?

**Comment by stevekuznetsov** [comment]
I'll look into it, but I don't think so -- this is very intermittent, and I see no failures locally.

**Comment by stevekuznetsov** [comment]
Can reproduce locally ... still weird that this isn't 100% on Jenkins. I think it's due to a temporal dependency between tests, will fix.
