### ISSUE TITLE
error: shallow cloning repository "ruby-hello-world.git" to "/tmp/gen428681221"

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#10147]
test failure is

```
FAILURE after 128.114s: test/cmd/builds.sh:26: executing 'oc new-build centos/ruby-22-centos7 https://github.com/openshift/ruby-hello-world.git' expecting success: the command returned the wrong error code

error: shallow cloning repository "https://github.com/openshift/ruby-hello-world.git" to "/tmp/gen428681221" failed: error: RPC failed; result=7, HTTP code = 0
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4368/consoleFull#165029888656c25df4e4b05b79524e5d52

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
[test]

**Comment by bparees** [comment]
pretty sure that's just a github timeout flake.  libcurl uses rc 7 as "could not connect to host"
https://curl.haxx.se/libcurl/c/libcurl-errors.html

if you want to add an FCM for it with a message that explains that to people, that'd be good.
