### ISSUE TITLE
Extended test failure: All nodes should be ready after test

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#10173]
Multiple tests failed in the networking extended test in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/3659

```
    Test Result (7 failures / +7)

    Extended.[k8s.io] Services should serve a basic endpoint from pods [Conformance]
    Extended.[k8s.io] Services should serve multiport endpoints from pods [Conformance]
    Extended.[k8s.io] Services should be able to create a functioning NodePort service
    Extended.[k8s.io] Services should prevent NodePort collisions
    Extended.[k8s.io] Services should check NodePort out-of-range
    Extended.[k8s.io] Services should release NodePorts on delete
    Extended.[k8s.io] Services should create endpoints for unready pods
```

Docker appears to have crashed.

Sample test failure output:

```
All nodes should be ready after test, Not ready nodes
...
KubeletNotReady container runtime is down
```

`
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:133
Aug  2 02:17:37.170: All nodes should be ready after test, Not ready nodes: [{{ } {nettest-master-sdn   /api/v1/nodes/nettest-master-sdn f68b6663-5877-11e6-9bd5-02425c709a19 1659 0 {2016-08-02 02:11:34 -0400 EDT} <nil> <nil> map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/hostname:nettest-master-sdn] map[] [] []} { nettest-master-sdn aws:////i-e4b59174 true} {map[cpu:{{2 0} {<nil>} 2 DecimalSI} memory:{{7933714432 0} {<nil>}  BinarySI} pods:{{110 0} {<nil>} 110 DecimalSI} alpha.kubernetes.io/nvidia-gpu:{{0 0} {<nil>} 0 DecimalSI}] map[memory:{{7933714432 0} {<nil>}  BinarySI} pods:{{110 0} {<nil>} 110 DecimalSI} alpha.kubernetes.io/nvidia-gpu:{{0 0} {<nil>} 0 DecimalSI} cpu:{{2 0} {<nil>} 2 DecimalSI}]  [{OutOfDisk False {2016-08-02 02:17:34 -0400 EDT} {2016-08-02 02:11:34 -0400 EDT} KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False {2016-08-02 02:17:34 -0400 EDT} {2016-08-02 02:11:34 -0400 EDT} KubeletHasSufficientMemory kubelet has sufficient memory available} {Ready False {2016-08-02 02:17:34 -0400 EDT} {2016-08-02 02:16:34 -0400 EDT} KubeletNotReady container runtime is down}] [{LegacyHostIP 172.17.0.2} {InternalIP 172.17.0.2}] {{10250}} {f8bea2ceb61e42a9a94fd319f4048a12 EC29021F-62B3-0087-4C77-094E82BC5522 eda65194-f0ee-470a-915b-1d6472958d75 3.10.0-327.22.2.el7.x86_64 Fedora 24 (Twenty Four) docker://Unknown v1.3.0+57fb9ac v1.3.0+57fb9ac linux amd64} [] [] []}}]
`

**Comment by knobunc** [comment]
@marun there's an selinux error related to overlayfs in the systemd.log artifact.  Perhaps we need to back off?  If you need @weliang1 can try to reproduce it to look at.

**Comment by marun** [comment]
I missed this one, and now the logs are gone.  selinux is set to permissive for the networking job, so I'm not sure how that would be causing the problem.

**Comment by marun** [comment]
Does this issue persist indefinitely or is there precedent to close issues documenting flakes after a certain period of time?
