### ISSUE TITLE
Flake in test/cmd/migrate.sh - migrated more image streams than expected

### ISSUE THREAD

**Issue by miminar** [openshift/origin#10181]
```
Running test/cmd/migrate.sh:64: executing 'oadm migrate image-references --include=imagestreams docker.io/*=my.docker.io/* --all-namespaces=false --loglevel=1 --confirm' expecting success and text 'migrated=1'...
FAILURE after 0.807s: test/cmd/migrate.sh:64: executing 'oadm migrate image-references --include=imagestreams docker.io/*=my.docker.io/* --all-namespaces=false --loglevel=1 --confirm' expecting success and text 'migrated=1': the output content test failed
Standard output from the command:
migrated:  imagestreams/busybox -n default
migrated:  imagestreams/test -n default
summary: total=2 errors=0 ignored=0 unchanged=0 migrated=2

There was no error output from the command.
```

Happened in [job 4516](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4516/console).

**Comment by liggitt** [comment]
@smarterclayton that's a tiny bit concerning... should we use an isolated namespace for the migration tests?

**Comment by smarterclayton** [comment]
That's what `--all-namespaces=false` is supposed to do.  It's supposed to be migrating things in the current namespace.  I fixed one bug about this recently, maybe it crept back in.

**Comment by smarterclayton** [comment]
Actually, https://github.com/openshift/origin/pull/8497/files/6e2823385e9eb13d67b3be6443b644dacb9f08b0#r73333694

implies this is a problem with the test framework or with project switching.  @deads2k  @stevekuznetsov have you seen other instances?

**Comment by deads2k** [comment]
> implies this is a problem with the test framework or with project switching. @deads2k @stevekuznetsov have you seen other instances?

Yes. See https://github.com/openshift/origin/pull/8497#discussion_r73333694 .  I hadn't started looking for it.

**Comment by stevekuznetsov** [comment]
@smarterclayton your link is dead -- what do you want to link to?

Regarding the project cache issue brought up in @deads2k PR... we could add a project cache sync period before launching each bucket. I would be surprised if it hadn't synced by line 64 of the test bucket, though.

**Comment by smarterclayton** [comment]
This problem was that the config was pointing to the default project but
the user *should* have been in cmd-whatever project.  Which implies the
kubeconfig on disk is wrong or there's a race and someone else is modifying
it.

**Comment by liggitt** [comment]
pretty sure it's the login call on line 22 that switched back to the default project
```
os::cmd::expect_success 'oc login -u system:admin'
```

**Comment by liggitt** [comment]
@stevekuznetsov waiting until `oc projects` lists the newly created project in test-cmd.sh before kicking off the sub-test script would be the simplest way to resolve this

**Comment by stevekuznetsov** [comment]
@liggitt I'll submit a patch
