### ISSUE TITLE
origin redirects clients to default-route interface

### ISSUE THREAD

**Issue by jmtd** [openshift/origin#10180]
OpenShift Origin appears to redirect clients (via HTTP) to connect to it over whatever interface is providing the default route on the host. This may not always be an address with which the client can connect to the server, nor the address that the connection originated from, resulting in broken connections.
##### Version

v1.3.0-alpha.2-250-g61eba05
##### Steps To Reproduce
1. Start origin in docker on a host with >1 network interface
2. connect to the HTTP console over the interface which does not supply the default route
3. observe the redirection
##### Current Result

```
$ curl -kI -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.112 Safari/534.30" https://cevm.local:8443/
HTTP/1.1 302 Found
Location: https://172.17.130.226:8443/console/
Date: Tue, 02 Aug 2016 17:39:34 GMT
Content-Length: 203
Content-Type: text/plain; charset=utf-8
```

The relevant part here is the host part of the Location: header: it is not the request host (cevm.local) but an IP which happens to be the assigned address on the host's interface which has the default route configured.
##### Expected Result

```
$ curl -kI -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.112 Safari/534.30" https://cevm.local:8443/
HTTP/1.1 302 Found
Location: https://cevm.local:8443/console/
Date: Tue, 02 Aug 2016 17:39:34 GMT
Content-Length: 203
Content-Type: text/plain; charset=utf-8
```

Perhaps this could/should be configurable. I tried `--hostname` to see if that helped to pin it to my desired interface but it does not.
##### Additional Information

Here's the background as to how I hit this and why it's a problem.

With VirtualBox on a Mac, you can configure a VM to have one of three types of network connections:
- bridged
- NAT
- host only

The bridged connection does not work reliably if you are using Wifi on your Mac. I am able to bridge to a USB NIC more reliably, but less conveniently (as I move from office to meeting rooms etc). I require a VPN to connect to my corporate network and work. When using bridging, I must configure a VPN client within the VM as well as on my host Mac, which is awkward. If the bridge network connection is down (e.g. I have moved to a meeting room and now using wifi on my Mac) I cannot communicate with the VM from the host.

However, despite all that, this results in one network interface in the VM, with the default route over that connection, and thus openshift origin's redirection behaviour does not break using it.

With NAT, my VM can share my host's VPN connection which is convenient, and it doesn't care whether I am using wired or wireless on the host. However, VirtualBox does not set up routing between the host and guest when using NAT, so I cannot by default communicate from the Mac to the VM.

To get around this, I can set up a second interface on the guest which is host-only. This works very well: the default route is over the NAT connection which is wired/wireless agnostic and I don't need a VPN client in the VM. Regardless of the state of any of that, I can always communicate with the VM from the host over the host-only network.

Here's where the openshift behaviour is a problem. If I am connecting to the origin instance on the VM from my host, I am doing so over the host-only network. However, openshift then HTTP redirects me to a URL based on the IP for its default route, the NAT network. My host cannot connect to that address due to the aformentioned VirtualBox limitation, and so things are broken.

**Comment by liggitt** [comment]
You should be able to start OpenShift with a `--public-master=https://cevm.local:8443` arg to tell it where to direct external clients

**Comment by jmtd** [comment]
@liggitt thanks, I'll give that a look!
