### ISSUE TITLE
Persistent Volume Claims not displayed by `oc get all`

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#10185]
Persistent volume claims not being displayed by `oc get all`

##### Version
```
oc v1.3.0-alpha.0+0b518a8-dirty
kubernetes v1.3.0+57fb9ac
features: Basic-Auth

Server https://10.13.137.149:8443
OpenShift v1.3.0-alpha.0+7a0f858-dirty
Kubernetes v1.3.0+57fb9ac
```

##### Steps To Reproduce
1. `oc process -f https://raw.githubusercontent.com/openshift/mysql/master/5.5/examples/replica/mysql_replica.json | oc create -f -`
> persistentvolumeclaim "mysql-master" created
> service "mysql-master" created
> service "mysql-slave" created
> deploymentconfig "mysql-master" created
> deploymentconfig "mysql-slave" created

2. `oc get all`
```
NAME                       REVISION     DESIRED       CURRENT   TRIGGERED BY
dc/mysql-master            1            1             1         config
dc/mysql-slave             1            1             1         config
NAME                       DESIRED      CURRENT       AGE
rc/mysql-master-1          1            1             4s
rc/mysql-slave-1           1            1             4s
NAME                       CLUSTER-IP   EXTERNAL-IP   PORT(S)                 AGE
svc/kubernetes             172.30.0.1   <none>        443/TCP,53/UDP,53/TCP   41s
svc/mysql-master           None         <none>        3306/TCP                4s
svc/mysql-slave            None         <none>        3306/TCP                4s
NAME                       READY        STATUS        RESTARTS                AGE
po/mysql-master-1-axqa9    0/1          Pending       0                       0s
po/mysql-master-1-deploy   1/1          Running       0                       4s
po/mysql-slave-1-deploy    1/1          Running       0                       4s
po/mysql-slave-1-sf9e5     0/1          Pending       0                       0s
```

##### Current Result
Persistent volume claims are not displayed

##### Expected Result
Persistent volume claims should be displayed

##### Additional information
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1298846

**Comment by deads2k** [comment]
PVCs usually can't be re-used.  They should not be included in all.  

@fabianofranz  see discussion in https://github.com/kubernetes/kubernetes/pull/28955

**Comment by juanvallejo** [comment]
@deads2k Okay, thanks. PVCs (and templates) are also [not deleted by `oc get all`](https://bugzilla.redhat.com/show_bug.cgi?id=1298846), is this working as intended, or should I open a new issue for this?

**Comment by deads2k** [comment]
> @deads2k Okay, thanks. PVCs (and templates) are also not deleted by oc get all, is this working as intended, or should I open a new issue for this?

We can't have one without the other.  Deleting all doesn't remove other resource like serviceaccounts or secrets either.

**Comment by juanvallejo** [comment]
> We can't have one without the other. Deleting all doesn't remove other resource like serviceaccounts or secrets either.

Thanks for clarifying! I'll mention this on the BZ
