### ISSUE TITLE
proto errors in jsonpath output for imagestreams

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#10194]
```
openshift start master
oc create -f examples/image-streams/image-streams-centos7.json -n openshift
oc get -n openshift is ruby -o 'jsonpath={.status.tags[*]}'

proto: tag has too few fields: "-"
proto: no coders for struct *reflect.rtype
proto: no encoder for sec int64 [GetProperties]
proto: no encoder for nsec int32 [GetProperties]
proto: no encoder for loc *time.Location [GetProperties]
proto: no encoder for Time time.Time [GetProperties]
tag:"latest" items:<created:<2016-08-03T10:16:15-04:00> dockerImageReference:"centos/ruby-23-centos7@sha256:2375b645b83bff8ccf7e61346859cd9a23ac57af6d443b32b6392c1998d14c74" image:"sha256:2375b645b83bff8ccf7e61346859cd9a23ac57af6d443b32b6392c1998d14c74" generation:2 >  tag:"2.3" items:<created:<2016-08-03T10:16:15-04:00> dockerImageReference:"centos/ruby-23-centos7@sha256:2375b645b83bff8ccf7e61346859cd9a23ac57af6d443b32b6392c1998d14c74" image:"sha256:2375b645b83bff8ccf7e61346859cd9a23ac57af6d443b32b6392c1998d14c74" generation:2 >  tag:"2.2" items:<created:<2016-08-03T10:16:15-04:00> dockerImageReference:"centos/ruby-22-centos7@sha256:8c6c4ff3ae64a90ab1535a7ff33e685c63b3d51f7915722292c12e5ccb8f0a7f" image:"sha256:8c6c4ff3ae64a90ab1535a7ff33e685c63b3d51f7915722292c12e5ccb8f0a7f" generation:2 >  tag:"2.0" items:<created:<2016-08-03T10:16:15-04:00> dockerImageReference:"openshift/ruby-20-centos7@sha256:83c2fd8cc3258f1ec22f26b6f6c573460f43be28f7ab3073b912f7bc8b56d930" image:"sha256:83c2fd8cc3258f1ec22f26b6f6c573460f43be28f7ab3073b912f7bc8b56d930" generation:2 > 
```

**Comment by mfojtik** [comment]
@pweil- will this be fixed by https://github.com/openshift/origin/pull/10191 ?

**Comment by pweil-** [comment]
not sure, I can test it today

**Comment by pweil-** [comment]
tested.  No, it does not fix this issue

**Comment by smarterclayton** [comment]
It was fixed upstream a while ago.  Also, internal types were the only
ones erroring IIRC, so check whether you are incorrectly formatting an
internal object.

**Comment by mfojtik** [comment]
@smarterclayton I hunted down this problem to kube resource_printer.go where the `PrintObj` func for JSONPathPrinter is taking a versioned object and marshaling it into `interface{}{}`.

Then it is passed to JSONPath and when it finds the results and it is printing them back, it calls .String() on versioned fields... The exact field that it fails on is:

```
---> 'v1.NamedTagEventList{Tag:"latest", Items:[]v1.TagEvent{v1.TagEvent{Created:unversioned.Time{Time:time.Time{sec:63607018664, nsec:0, loc:(*time.Location)(0x2e3a4c0)}}, DockerImageReference:"centos/ruby-23-centos7@sha256:0f097bcd89851ed9c5ac367327f0fb4c9d22574e8884d90a301c813b263832e7", Image:"sha256:0f097bcd89851ed9c5ac367327f0fb4c9d22574e8884d90a301c813b263832e7", Generation:2}}, Conditions:[]v1.TagEventCondition(nil)}'
```

So you saying this is fixed in upstream already and we will get the fix in next rebase?

**Comment by mfojtik** [comment]
@smarterclayton also I don't see any fix here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L2387

**Comment by smarterclayton** [comment]
It was fixed by altering the string generator method not report that error.

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/pull/28815 should fix this.

**Comment by mfojtik** [comment]
@liggitt to fix this we will have to pickup the commit @smarterclayton linked, regenerate protobuf for kube and bump the godep and then regenerate the origin.

I think I will punt on this until we do regular rebase (which should fix this) with the workaround being that the end-user can just filter out the stderr to get rid of these errors.

**Comment by smarterclayton** [comment]
This was resolved a while ago.
