### ISSUE TITLE
Registry token auth redirect assumes service IP is visible to end-users

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#10193]
Registry token auth redirects clients to a token endpoint on the same server. Currently, it is using the injected service host and port envvars to determine the redirected hostname. That breaks in cases where the registry is reached via a route or other network method, and the client does not have visibility to the registry service IP.

cc @aweiteka

**Comment by aweiteka** [comment]
I would expect the token endpoint defined in `DOCKER_REGISTRY_SERVICE_HOST` could just be localhost. Should this work?

**Comment by liggitt** [comment]
redirecting end clients to localhost would not work unless the registry was running on their machine

**Comment by liggitt** [comment]
this is the classic "redirect the user to whatever hostname they used to talk to me in the first place" problem

**Comment by aweiteka** [comment]
FYI, here's what I'm seeing:

### Login error

```
$ sudo docker login -p <token_from_ocwhoami> -u bob -e email@example.com registry-***.openshiftapps.com:80
Error response from daemon: no successful auth challenge for http://registry-***.openshiftapps.com:80/v2/ - errors: [Get http://172.30.53.101:5000/openshift/token?account=bob: dial tcp 172.30.53.101:5000: i/o timeout]
```

### Config

Registry service IP is 172.30.53.101. Tried using that as env var to the pod:
```
DOCKER_REGISTRY_SERVICE_HOST=172.30.53.101
```

### Logs

```
time="2016-08-03T20:31:14.041411256Z" level=debug msg="authorizing request" go.version=go1.6.3 http.request.host="registry-***.openshiftapps.com:80" http.request.id=7495b8bb-bc09-4ea7-968d-15c1bacf4896 http.request.method=GET http.request.remoteaddr=172.16.7.156 http.request.uri="/v2/" http.request.useragent="docker/1.10.3 go/go1.5.4 kernel/4.6.4-201.fc23.x86_64 os/linux arch/amd64" instance.id=8935a0dd-2004-4182-a5ce-5fd0b7cff3bb 
time="2016-08-03T20:31:14.041672596Z" level=error msg="error authorizing context: authorization header required" go.version=go1.6.3 http.request.host="registry-***.openshiftapps.com:80" http.request.id=7495b8bb-bc09-4ea7-968d-15c1bacf4896 http.request.method=GET http.request.remoteaddr=172.16.7.156 http.request.uri="/v2/" http.request.useragent="docker/1.10.3 go/go1.5.4 kernel/4.6.4-201.fc23.x86_64 os/linux arch/amd64" instance.id=8935a0dd-2004-4182-a5ce-5fd0b7cff3bb 
```

**Comment by aweiteka** [comment]
@liggitt so this appears to be blocking me running a separate openshift master + registry on top of OpenShift. Not entirely understanding the issue... would having a FQDN for `DOCKER_REGISTRY_SERVICE_HOST` be a workaround?

**Comment by liggitt** [comment]
reworked to auto-detect scheme/host for the token redirect from the incoming request. there's a `tokenrealm` config option in the registry config.yml as an escape hatch, but that shouldn't be needed in a normal pod,service,route setup.

**Comment by liggitt** [comment]
will be fixed in https://github.com/openshift/origin/issues/10418
