### ISSUE TITLE
Coverage generation should run only after all tests complete

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1020]
Test pull requests and ami build is ~12 minutes longer due to html generation, but we only need to return html if the build succeeds.  Suggest generating in a separate step at the end

**Comment by ironcladlou** [comment]
Here's the important section of the current job:

```shell
# ... snip ...

pushd origin
vagrant origin-init --stage inst --os fedora origin_${JOB_NAME}_${BUILD_NUMBER}
vagrant up --provider aws
vagrant sync-openshift3 -s
vagrant test-openshift3 --all -d -c --skip-image-cleanup
test_pull_requests --mark_test_success $ORIGIN_PULL_ID --repo origin --config ~/.test_pull_requests_origin.json
popd
```

What if we...

Changed the main build step to omit the coverage flag, and unset `--skip-image-cleanup`:

```shell
# ... snip ...

pushd origin
vagrant origin-init --stage inst --os fedora origin_${JOB_NAME}_${BUILD_NUMBER}
vagrant up --provider aws
vagrant sync-openshift3 -s
vagrant test-openshift3 --all -d
popd
```

And made the first post-build step set to execute only if the build succeeds:

```shell
vagrant test-openshift3 --all -d -c --skip-image-cleanup
test_pull_requests --mark_test_success $ORIGIN_PULL_ID --repo origin --config ~/.test_pull_requests_origin.json
```

This does mean we'd run the tests twice, but having failures return faster seems worth it.

**Comment by smarterclayton** [comment]
Before changing this we should copy what upstream does in hack/test-go (or bits of it) to aggregate the results.  You can cat the samples together apparently as long as you trim a few lines.

----- Original Message -----

**Comment by danmcp** [comment]
Few things:
- The current state is we don't run coverage on test or merge
- It's the coverage that's the issue and not the html generation
- The result aggregation seems like the remaining feasible piece
