### ISSUE TITLE
Unable to access services outside POD using Router. DNS Issue

### ISSUE THREAD

**Issue by snyamars** [openshift/origin#10209]
I have installed OpenShift Origin 1.3.0_alpha 2 binary on RHEL. I am able to deploy sample applications but unable to access them outside the PODs. This seems to be DNS issue. As per the documentation, 1.3 and above will have SkyDNS running on 8053 and Dnsmasq should be running on port 53.
However, I see that Dnsmasq is not running at all. Pls suggest if I have to make any further changes to enable the service access outside PODs.
##### Version

oc v1.3.0-alpha.2
kubernetes v1.3.0-alpha.1-331-g0522e63
##### Steps To Reproduce
1. Install OpenShift Origin
2. Deploy sample application
3. Expose the service using HAProxy Router
4. Access the application from outside the OpenShift platform
##### Current Result

Unresolved service. Connection refused
##### Expected Result

Service should be accessible
##### Additional Information

I am able to access the service by enabling nodePort.

**Comment by mfojtik** [comment]
@knobunc seems like a networking issue?

**Comment by knobunc** [comment]
From one of the nodes, can you access the pod IP address using curl?  How about the service IP address?  What does 'oc get route ... -o yaml' say?  And how are you accessing the router?  Can you paste an exact error message?

**Comment by snyamars** [comment]
Sorry for the late response. 
I am able to access the pod IP address using curl from the node. I am trying to access the router using the default FQDN generated by Origin. In my case it is 
"hello-service-default.router.default.svc.cluster.local"
Below is the oc get routes output:
NAME            HOST/PORT                                                PATH      SERVICE         TERMINATION   LABELS
hello-service   hello-service-default.router.default.svc.cluster.local             hello-service                 name=hello-openshift


Below is the oc get route .. -o yaml output:

apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: 2016-08-21T10:41:56Z
  labels:
    name: hello-openshift
  name: hello-service
  namespace: default
  resourceVersion: "16420"
  selfLink: /oapi/v1/namespaces/default/routes/hello-service
  uid: e1e4fa09-678b-11e6-ac77-0a5363bd7dfb
spec:
  host: hello-service-default.router.default.svc.cluster.local
  to:
    kind: Service
    name: hello-service
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2016-08-21T10:41:56Z
      status: "True"
      type: Admitted
    host: hello-service-default.router.default.svc.cluster.local
    routerName: router

Below is the output for : oc describe service hello-service
Name:                   hello-service
Namespace:              default
Labels:                 name=hello-openshift
Selector:               name=hello-openshift
Type:                   NodePort
IP:                     172.30.168.91
Port:                   <unset> 8080/TCP
NodePort:               <unset> 31589/TCP
Endpoints:              172.17.0.2:8080,172.17.0.3:8080,172.17.0.4:8080
Session Affinity:       None

Note that the entire setup is running in AWS on RHEL 7 instance.

**Comment by snyamars** [comment]
Exact error message:
curl hello-service-default.router.default.svc.cluster.local
curl: (6) Could not resolve host: hello-service-default.router.default.svc.cluster.local; Name or service not known

**Comment by knobunc** [comment]
Ok... this isn't really a networking problem, it feels like a misconfiguration of the node.  You need to get dnsmasq running on the node.  Did you use the ansible installer?

**Comment by snyamars** [comment]
I have not used ansible installer. I installed it from the binary (https://github.com/openshift/origin/releases/tag/v1.3.0-alpha.2) and followed the documentation. dnsmasq is not running and I believe this is the issue which I highlighted in the beginning of this thread. 
As per version 1.3 documentation, dnsmasq should be running on port 53 but it is not running. Is there any config change I need to make? Pls suggest.

**Comment by knobunc** [comment]
What documentation did you follow?  https://docs.openshift.com/enterprise/3.2/install_config/install/advanced_install.html or https://docs.openshift.com/enterprise/3.2/install_config/install/quick_install.html?

Anyway, unless you use one of our installers, nothing sets up dnsmasq on the node for you, as far as I know.  I think you have to do that yourself (there's a sample networkmanager config script in https://docs.openshift.com/enterprise/3.2/install_config/install/quick_install.html).  @brenton do you know?

**Comment by snyamars** [comment]
I followed the openshift origin (community edition quick install) - https://docs.openshift.org/latest/getting_started/administrators.html#downloading-the-binary

**Comment by chengkuangan** [comment]
Hi, 
 
I have the same issue, using OpenShift Origin 1.3.2 (tried with 1.3.1, same situation). As the document says we can install manually, thus trying it out. In my case, the dnsmasq does running at the following IPs started by openshift start command. Pasted the version info at the bottom of this post

curl http://172.17.0.3:8080/ on the sample pod works fine.

By following the document, I thought we can install and configure OpenShift manually other than using ansible? 

I have been working on this for a week, please help.

root@cluster ~]# netstat -tnap | grep LISTEN
tcp        0      0 10.0.2.15:53            0.0.0.0:*               LISTEN      4334/openshift      
tcp        0      0 0.0.0.0:8053            0.0.0.0:*               LISTEN      4334/openshift  

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[root@cluster ~]# dig parksmap-parksmap.router.default.svc.cluster.local @10.0.2.15

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3 <<>> parksmap-parksmap.router.default.svc.cluster.local @10.0.2.15
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 13130
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;parksmap-parksmap.router.default.svc.cluster.local. IN A

;; AUTHORITY SECTION:
cluster.local.		60	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1482465600 28800 7200 604800 60

;; Query time: 0 msec
;; SERVER: 10.0.2.15#53(10.0.2.15)
;; WHEN: Fri Dec 23 12:11:43 MYT 2016
;; MSG SIZE  rcvd: 161


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[root@cluster ~]# docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

root@cluster ~]# openshift version
openshift v1.3.2
kubernetes v1.3.0+52492b4
etcd 2.3.0+git

**Comment by knobunc** [comment]
Does this work?:
`  dig parksmap-parksmap.router.default.svc.cluster.local @172.30.0.1`

**Comment by chengkuangan** [comment]
Hi Ben,

I had solved the problem by creating a route manually.

Thanks


Thank you.

Kind Regards,

Gan Cheng Kuan
Senior Solution Architect for ASEAN (ISV & Partners)
Red Hat Malaysia Sdn Bhd
Mobile: (60) 012-6581713
Email: chgan@redhat.com

On 10 Jan 2017, at 2:46 AM, Ben Bennett <notifications@github.com> wrote:

Does this work?:
dig parksmap-parksmap.router.default.svc.cluster.local @172.30.0.1

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10209#issuecomment-271368970>,
or mute the thread

**Comment by sundeepk1** [comment]
can you please provide info on how you created the route manually
