### ISSUE TITLE
runtime image pull authentication not set for extended builds

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#10214]
from: https://github.com/openshift/origin/pull/10205#issuecomment-237540255

@php-coder 
> In case of using runtimeImage env variable PULL_DOCKERCFG_PATH is absent. Looks like build.Spec.Strategy.SourceStrategy.PullSecret is set to nil in this case. I'm searching why and who should set it.

cc: @bparees 

we can continue the discussion here.

**Comment by PI-Victor** [comment]
@bparees @php-coder is P2 high enough?

**Comment by bparees** [comment]
@PI-Victor feels p1 to me, at least unless we can determine that it will only occur under specific rare circumstances.

**Comment by php-coder** [comment]
I know how to fix it and I'm preparing the PR for this right now.

Specific circumstances are: we're using builder image that doesn't need a pull secret, while runtime image needs this secret.
