### ISSUE TITLE
deployment config controller doesn't sync, conformance flakes

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#10229]
seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/4712/testReport/junit/(root)/Extended/deploymentconfigs_with_revision_history_limits_should_never_persist_more_old_deployments_than_acceptable_after_being_observed_by_the_controller__Conformance_/)
```
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:577
the current deployment needs to have finished before attempting to trigger a new deployment through configuration change
Expected error:
    <*errors.errorString | 0xc8200ce130>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

**Comment by mfojtik** [comment]
interesting, the seventh DC we triggered (and the one that failed) has this error:

```
I0804 16:09:00.952711   27136 controller.go:407] Error syncing deployment config extended-test-cli-deployment-qnffq-gqpmq/history-limit: Operation cannot be fulfilled on replicationcontrollers "history-limit-7": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by kargakis** [comment]
@mfojtik do we need the retries on conflict you have in https://github.com/openshift/origin/pull/10341

**Comment by mfojtik** [comment]
@kargakis will check.

**Comment by kargakis** [comment]
https://github.com/openshift/origin/pull/10507 added retries on update conflicts in the deploymentconfig controller. Closing until we see it again.
