### ISSUE TITLE
[Conformance] flake: Extended.Deployments - It should immediately start a new deployment

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#10228]
```
Summarizing 1 Failure:

[Fail] deploymentconfigs when run iteratively [It] should immediately start a new deployment [Conformance] 
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:162

Ran 148 of 485 Specs in 1495.782 seconds
FAIL! -- 147 Passed | 1 Failed | 0 Pending | 337 Skipped 

Ginkgo ran 1 suite in 25m0.155416573s
Test Suite Failed
[INFO] Running serial tests
Running Suite: Extended
=======================
Random Seed: 1470337008
Will run 16 of 485 specs

I0804 14:56:48.757541   28379 e2e.go:58] The --provider flag is not set.  Treating as a conformance test.  Some tests may not be run.
Aug  4 14:56:48.757: INFO: >>> kubeConfig: /tmp/openshift/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig

Aug  4 14:56:48.759: INFO: Waiting up to 0 for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Aug  4 14:56:48.804: INFO: Waiting for pods to enter Success, but no pods in "kube-system" match label map[name:e2e-image-puller]
Aug  4 14:56:48.806: INFO: 0 / 0 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Aug  4 14:56:48.806: INFO: expected 0 pod replicas in namespace 'kube-system', 0 are Running and Ready.
Aug  4 14:56:48.808: INFO: Waiting for pods to enter Success, but no pods in "kube-system" match label map[name:e2e-image-puller]
I0804 14:56:48.808226   28379 e2e.go:58] The --provider flag is not set.  Treating as a conformance test.  Some tests may not be run.
```
##### Additional Information

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/4706/consoleFull

@mfojtik not sure if i should assign it to you, or someone else

**Comment by kargakis** [comment]
Please post the link to a log when it occurs again so we can get what we need

**Comment by PI-Victor** [comment]
@kargakis sorry, had no idea the logs expire so fast, but if it comes up again, i will update.

**Comment by kargakis** [comment]
> @kargakis sorry, had no idea the logs expire so fast, but if it comes up again, i will update.

Unfortunately the output you posted is not enough, that's why I am asking for anyone who may stumble upon it in the future. We have a failure trap which dumps the DC, and its RCs and deployer pods.

**Comment by kargakis** [comment]
Keeping it open doesn't help because people are linking from their PRs, retest, and the logs are gone. Next guy that hit this: please reopen with a log from the failed test.

**Comment by soltysh** [comment]
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6719/consoleFull

**Comment by kargakis** [comment]
> Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6719/consoleFull

A combination of https://github.com/openshift/origin/issues/11016 and terminationGracePeriod not being respected. The place where this test fails uses a 30s timeout, the pending deployer pod has been assigned a deletion timestamp at `deletionTimestamp: 2016-09-29T23:17:27Z` and a terminationGracePeriod of 10s but after 21s (`Sep 29 19:17:48.320`) when the test fails the pod is yet to be deleted.

**Comment by legionus** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/7979/consoleFull

```
------------------------------
deploymentconfigs when run iteratively [Conformance] 
  should immediately start a new deployment
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:194

[BeforeEach] [Top Level]
  /data/src/github.com/openshift/origin/test/extended/util/test.go:45
[BeforeEach] deploymentconfigs
  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:133
STEP: Creating a kubernetes client
Oct 28 07:02:20.749: INFO: >>> kubeConfig: /tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig

STEP: Building a namespace api object
Oct 28 07:02:20.772: INFO: configPath is now "/tmp/extended-test-cli-deployment-hzzdz-de5l2-user.kubeconfig"
Oct 28 07:02:20.772: INFO: The user is now "extended-test-cli-deployment-hzzdz-de5l2-user"
Oct 28 07:02:20.772: INFO: Creating project "extended-test-cli-deployment-hzzdz-de5l2"
STEP: Waiting for a default service account to be provisioned in namespace
[It] should immediately start a new deployment
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:194
Oct 28 07:02:20.981: INFO: Running 'oc create --config=/tmp/extended-test-cli-deployment-hzzdz-de5l2-user.kubeconfig --namespace=extended-test-cli-deployment-hzzdz-de5l2 -f /data/src/github.com/openshift/origin/test/extended/testdata/deployments/deployment-simple.yaml -o name'
Oct 28 07:02:21.231: INFO: Running 'oc set env --config=/tmp/extended-test-cli-deployment-hzzdz-de5l2-user.kubeconfig --namespace=extended-test-cli-deployment-hzzdz-de5l2 deploymentconfig/deployment-simple TRY=ONCE'
STEP: by checking that the deployment config has the correct version
STEP: by checking that the second deployment exists
STEP: by checking that the first deployer was deleted and the second deployer exists
[AfterEach] when run iteratively [Conformance]
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:50
[AfterEach] deploymentconfigs
  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:134
Oct 28 07:02:24.602: INFO: Waiting up to 1m0s for all nodes to be ready
STEP: Destroying namespace "extended-test-cli-deployment-hzzdz-de5l2" for this suite.
Oct 28 07:07:24.670: INFO: namespace: extended-test-cli-deployment-hzzdz-de5l2, resource: bindings, ignored listing per whitelist
Oct 28 07:07:24.697: INFO: Couldn't delete ns: "extended-test-cli-deployment-hzzdz-de5l2": namespace extended-test-cli-deployment-hzzdz-de5l2 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed (&errors.errorString{s:"namespace extended-test-cli-deployment-hzzdz-de5l2 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed"})


• Failure in Spec Teardown (AfterEach) [303.948 seconds]
deploymentconfigs
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:827
  when run iteratively [Conformance] [AfterEach]
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:195
    should immediately start a new deployment
    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:194

    Oct 28 07:07:24.697: Couldn't delete ns: "extended-test-cli-deployment-hzzdz-de5l2": namespace extended-test-cli-deployment-hzzdz-de5l2 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed (&errors.errorString{s:"namespace extended-test-cli-deployment-hzzdz-de5l2 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed"})
```

**Comment by liggitt** [comment]
possibly fixed by https://github.com/openshift/origin/pull/11627

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8026/consoleFull#86299571056cbb9a5e4b02b88ae8c2f77
http://pastebin.com/rjQi3a34

The deployer pod is never scheduled, superseded and marked for deletion, but never deleted. @smarterclayton which component is responsible for deleting pending pods at this point? Node controller or pod GC?

**Comment by kargakis** [comment]
At least we don't start a new deployer pod until the old is gone.

**Comment by smarterclayton** [comment]
An unscheduled pod shouldn't be able to be marked for graceful deletion -
it should go away instantly.  That means bad logic in the apiserver - can
you summarize the failure state here so I can check upstream for when this
was fixed (if it has).

On Oct 31, 2016, at 8:46 AM, Michail Kargakis <notifications@github.com>
wrote:

At least we don't start a new deployer pod until the old is gone.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10228#issuecomment-257284586>,
or mute the thread

**Comment by kargakis** [comment]
Hm, it seems that the pod is scheduled but it never transitions to Running. Most probably https://github.com/openshift/origin/issues/11016

**Comment by kargakis** [comment]
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2016-10-31T11:52:07Z
    status: "True"
    type: PodScheduled
  phase: Pending
```

**Comment by soltysh** [comment]
@kargakis can we increase all timeouts in deployments to 1min? We've experienced yesterday with @ncdc this flake in that cherry-pick PR where right after we've went overtime the pod went into ready state. This was one of the 30s timeouts towards the end of that file (can't remember the exact line), so I was thinking about increasing all of those 30s to 1min, wdyt?

**Comment by kargakis** [comment]
Yes, I believe it's fine.

**Comment by soltysh** [comment]
I'll create a PR later today.

**Comment by liggitt** [comment]
Needing to double timeouts is concerning.  Are we tracking finding and fixing the underlying issue for 1.4, and when we do, will we reduce the timeouts so we get notified again if they regress?

**Comment by kargakis** [comment]
thanks

**Comment by soltysh** [comment]
@liggitt it all looks related to #11016 which is devicemapper inefficiency in docker 1.10. Nothing really regressed on our side (see the attached doc in that linked issue). One solution is to either switch to overlay (which rocks!) or upgrade 1.12 and hope it's better.

**Comment by liggitt** [comment]
I thought we were on docker 1.12 in the devenvs. @danmcp?

**Comment by soltysh** [comment]
Actually, we are. Looking [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8031/consoleFull) gives me 1.12.2-rc2, I'd have to verify locally the tests from that doc.

**Comment by danmcp** [comment]
@liggitt Yep, still 1.12 afaict.

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/9535/
