### ISSUE TITLE
Imagestream tags fails with unsecure registries 

### ISSUE THREAD

**Issue by Mangirdaz** [openshift/origin#10235]
If you try create IS with nested structure it fails to referee to external registry (insecure one).

##### Version
`````
oc v3.2.1.4-1-g1864c8f
kubernetes v1.2.0-36-g4a3f9c5
````
##### Steps To Reproduce
"Old" style IS and works just fine
````
{
      "kind": "ImageStream",
      "apiVersion": "v1",
      "metadata": {
        "name": "jenkins",
        "creationTimestamp": null,
             "annotations":{
        	"openshift.io/image.insecureRepository":"true"
        }
      },
      "spec": {
        "dockerImageRepository": "{{docker_registry_url}}/openshift3/jenkins-1-rhel7",
        "tags": [
          {
            "name": "latest",
            "annotations": {
              "description": "Provides a Jenkins server",
              "iconClass": "icon-jenkins",
              "tags": "jenkins"
            }
          }
        ]
      }
    },
````
And now I want to use "New" IS tags to mange my images:
`````
 {
      "kind": "ImageStream",
      "apiVersion": "v1",
      "metadata": {
        "name": "jdk1.8-s2i",
          "annotations":{
        	"openshift.io/image.insecureRepository":"true"
        }
      },
      "spec": {
        "tags": [
          {
            "name": "latest",
            "annotations": {
              "description": "Provides a Java s2i",
              "iconClass": "icon-java",
              "tags": "builder,java,jdk1.8-s2i"
            },
            "from": {
              "kind": "ImageStreamTag",
              "name": "0.1-2"
            }
          },
          {
            "name": "0.1-2",
            "annotations": {
              "description": "Provides a Jenkins server",
              "iconClass": "icon-java",
              "tags": "builder,java,jdk1.8-s2i",
              "version": "1.8"
            },
            "from": {
              "kind": "DockerImage",
              "name": "{{docker_registry_url}}/paas/jdk1.8-s2i:0.1-2"
            }
          }
        ]
      }
    }    
``````

##### Current Result
And what I see is:
`````
-bash-4.2$ oc get is
NAME         DOCKER REPO                                          TAGS                              UPDATED
jdk1.8-s2i   172.30.44.251:5000/openshift/jdk1.8-s2i              0.1-2
jenkins      myinternalregistry:5000/openshift3/jenkins-1-rhel7   1.625,latest                      16 minutes ago
python       myinternalregistry:5000/rhscl/python-27-rhel7        2.7-11.1,latest,2.7 + 2 more...   16 minutes ago
-bash-4.2$ oc describe is jdk1.8-s2i
Name:                   jdk1.8-s2i
Created:                16 minutes ago
Labels:                 <none>
Annotations:            openshift.io/image.dockerRepositoryCheck=2016-08-05T08:37:54Z
                        openshift.io/image.insecureRepository=true
Docker Pull Spec:       172.30.44.251:5000/openshift/jdk1.8-s2i

Tag     Spec                                            Created         PullSpec        Image
latest  0.1-2                                                           <not available> <not available>
0.1-2   myinternalregistry:5000/paas/jdk1.8-s2i:0.1-2   16 minutes ago                  import failed: Internal error occurred: Get https://myinternalregistry....


`````

##### Expected Result
annotation openshift.io/image.insecureRepository=true should be valid for both use cases

**Comment by smarterclayton** [comment]
The new rules require you to set `{importPolicy: {insecure: true}}` per tag.

**Comment by smarterclayton** [comment]
As per https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-tagreference - the insecure annotation is only supported for the `spec.dockerImageRepository` import.

**Comment by Mangirdaz** [comment]
As always - real MVP!

{

		"kind": "ImageStream",
		"apiVersion": "v1",
		"metadata": {
			"name": "java-s2i",
			"creationTimestamp": null
		},
		"spec": {
			"tags": [{
				"name": "latest",
				"annotations": {
					"description": "Build and run java applications",
					"iconClass": "icon-java",
					"tags": "builder,java",
					"supports": "java,jre",
					"sampleRepo": "ssh://git7999/paas/example-spring-boot.git"
				},
				"from": {
					"kind": "ImageStreamTag",
					"name": "0.1-3"
				},
				"importPolicy": {
					"insecure": true
				}
			}, {
				"name": "0.1-3",
				"annotations": {
					"description": "Build and run Java 1.8 applications",
					"iconClass": "icon-java",
					"tags": "builder,java",
					"supports": "java:1.8,java",
					"version": "0.1-3",
					"sampleRepo": "ssh://git/paas/example-spring-boot.git"
				},
				"from": {
					"kind": "DockerImage",
					"name": "{{docker_registry_url}}/paas/jdk1.8-s2i"
				},
				"importPolicy": {
					"insecure": true
				}
			}


```

**Comment by mfojtik** [comment]
@Mangirdaz can you close this issue if this works for you?

**Comment by Mangirdaz** [comment]
Yes please
