### ISSUE TITLE
Fix hack/cherry-pick.sh

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#10248]
The script is [currently broken.](https://gist.github.com/ncdc/71b41275b2068b18323846a2be81d7ed)

/cc @smarterclayton @ncdc

**Comment by ncdc** [comment]
😄 it works sometimes, but those times are few & far between

**Comment by smarterclayton** [comment]
It's broken... because the PR you are trying to merge can't be rebased onto
our branch.  What did you expect, magic?

cd KUBERNETES_DIR
git checkout MY_PR
git rebase openshift/stable-20160804
# get thousands of merge conflicts

Is that not the case?  What would you expect?

**Comment by ncdc** [comment]
I can easily `git apply` the patch from the PR, but the process the script is using doesn't work most of the time for me.

**Comment by smarterclayton** [comment]
You can potentially switch the process to try a rebase (as opposed to a
patch apply), no idea whether that will give you the outcome you want.
Happy to review any PRs
