### ISSUE TITLE
etcd_server_certificates : Retrieve etcd cert tarball Permission denied

### ISSUE THREAD

**Issue by dvohra** [openshift/origin#10259]
[provide a description of the issue]

##### Version
1.21

##### Steps To Reproduce
1. Configure and run a Multiple Masters Using Native HA 
2. ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml

##### Current Result
```
TASK [etcd_server_certificates : Retrieve etcd cert tarball] *******************
fatal: [ec2-54-196-204-223.compute-1.amazonaws.com]: FAILED! => {"failed": true, "msg": "Failed to fetch the file: [Errno 13] Permission denied: '/tmp/etcd_certificates-aR1GTfJ/etcd-ip-10-150-61-233.ec2.internal.tgz'"}
```

##### Expected Result
Openshift Origin cluster with Multiple Masters Using Native HA  to get started

##### Additional Information
Docker 1.10 not pre-installed as 1.12 is not supported by kubernetes.
2 Master nodes
1 worker node
3 total ndes
1 etcd
1 load balancer

**Comment by abutcher** [comment]
@dvohra Looks like we were missing some become statements for these tasks. I've opened https://github.com/openshift/openshift-ansible/pull/2269 to address.

**Comment by dvohra** [comment]
Thanks. The issue is fixed.
