### ISSUE TITLE
Should warn user when using image with volume but without PVC?

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#10265]
I tried Docker official `mongodb` image which will fail terribly when you just run it in OpenShift because it is not able to write into `/data/db` folder (which is strange because that folder exists, but I think the user that run the image is random and does not have rights to write to that directory.

I suggest that when you use `new-app` (or something similar) and creating the mongo pod, we warn you when the Docker image has volumes defined, but you don't have any PV/PVC bound to them. Alternatively we can help users by providing some event in console to help them debug the issue.

**Comment by bparees** [comment]
@mfojtik when you use new-app, you already get an (emptydir) volume for any volumes defined in the image, see the "this image declares volumes and will default to use non-persistent....." message below:

```
--> Found Docker image e0fdd58 (7 days old) from Docker Hub for "centos/mongodb-26-centos7"

    MongoDB 2.6 
    ----------- 
    MongoDB is a scalable, high-performance, open source NoSQL database.

    Tags: database, mongodb, rh-mongodb26

    * An image stream will be created as "mongodb-26-centos7:latest" that will track this image
    * This image will be deployed in deployment config "mongodb-26-centos7"
    * Port 27017/tcp will be load balanced by service "mongodb-26-centos7"
      * Other containers can access this service through the hostname "mongodb-26-centos7"
    * This image declares volumes and will default to use non-persistent, host-local storage.
      You can add persistent volumes later by running 'volume dc/mongodb-26-centos7 --add ...'

--> Creating resources with label app=mongodb-26-centos7 ...
    imagestream "mongodb-26-centos7" created
    deploymentconfig "mongodb-26-centos7" created
    service "mongodb-26-centos7" created
--> Success (DRY RUN)
```

If you want the deployment itself to report some sort of warning in this case, then i think that would fall on platform management.

**Comment by mfojtik** [comment]
i'm fine with the new-app telling you
