### ISSUE TITLE
/bin/test_pull_requests:615:in `local_merge_pull_request': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bparees** [openshift/origin#10267]
```
*****Locally Merging Pull Request: https://github.com/openshift/origin/pull/10261
+ test_pull_requests --local_merge_pull_request 10261 --repo origin --config /var/lib/jenkins/.test_pull_requests_origin.json
Local merging pull request #10261 for repo 'origin'
/bin/test_pull_requests:615:in `local_merge_pull_request': undefined method `[]' for nil:NilClass (NoMethodError)
	from /bin/test_pull_requests:1904:in `<main>'
Build step 'Execute shell' marked build as failure
[PostBuildScript] - Execution post build scripts.
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/4826/console

**Comment by stevekuznetsov** [comment]
Seems like the API response we got for the pull request is missing `pull_request['head']['repo']` -- is this happening more than once? Could just be flaky GitHub API.

**Comment by bparees** [comment]
Yes, has failed 2 or 3 times now.

Ben Parees | OpenShift

**Comment by stevekuznetsov** [comment]
I do see successful conformance runs -- are these failures always for the same PR? Can you link logs?

**Comment by bparees** [comment]
I linked the PR.

Ben Parees | OpenShift

**Comment by bparees** [comment]
PR had no valid repository associated, somehow.
