### ISSUE TITLE
Need a docker version in builder log

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#10264]
With the current situation with Docker 1.10+ manifests pushed to DockerHub, we should display the version of Docker the node where the build run have installed.

I was playing with the official `java` image from DockerHub which fails terribly on 1.9 because of manifest mismatch (build created using new-build).

A clean indication to user of what version of Docker he run might help.

**Comment by bparees** [comment]
it's not like it's just builds that have this problem, deployments won't work either.

**Comment by bparees** [comment]
and i don't think displaying the version is going to help users, they have no idea what the manifest error means.  and we know exactly what it means w/o needing the docker version.

I would prefer to close this.  Whenever i've tried to add version info to the output before, @smarterclayton has squashed it anyway unless it's debug only at which point asking the user for the version is as easy as having them rerun the build w/ verbose logging.
