### ISSUE TITLE
`oc get all` types use shorthand, should use longhand

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#10272]
```
$ oc get all
NAME                 TYPE                                                    FROM          LATEST
bc/ruby-ex           Source                                                  Git@master    4
NAME                 TYPE                                                    FROM          STATUS      STARTED          DURATION
builds/ruby-ex-1     Source                                                  Git@b571f7e   Complete    5 days ago       1m59s
builds/ruby-ex-2     Source                                                  Git@b571f7e   Complete    5 days ago       19s
builds/ruby-ex-3     Source                                                  Git@b571f7e   Cancelled   36 minutes ago   17s
builds/ruby-ex-4     Source                                                  Git@ed91b57   Complete    32 minutes ago   31s
NAME                 DOCKER REPO                                             TAGS          UPDATED
is/ruby-ex           172.30.38.247:5000/projectdan/ruby-ex                   latest        31 minutes ago
NAME                 REVISION                                                DESIRED       CURRENT   TRIGGERED BY
dc/ruby-ex           3                                                       1             0         config,image(ruby-ex:latest)
NAME                 DESIRED                                                 CURRENT       AGE
rc/ruby-ex-1         0                                                       0             5d
rc/ruby-ex-2         0                                                       0             5d
rc/ruby-ex-3         1                                                       1             31m
NAME                 HOST/PORT                                               PATH          SERVICE            TERMINATION   LABELS
routes/ruby-ex       ruby-ex-projectdan.89ed.ded-int-gcp.openshiftapps.com                 ruby-ex:8080-tcp                 app=ruby-ex
NAME                 CLUSTER-IP                                              EXTERNAL-IP   PORT(S)            AGE
svc/ruby-ex          172.30.211.202                                          <none>        8080/TCP           5d
NAME                 READY                                                   STATUS        RESTARTS           AGE
po/ruby-ex-1-build   0/1                                                     Completed     0                  5d
po/ruby-ex-2-build   0/1                                                     Completed     0                  5d
po/ruby-ex-3-jfq1k   1/1                                                     Running       0                  25m
po/ruby-ex-4-build   0/1                                                     Completed     0                  32m
```

We should be listing the names with the long-hand `replicationcontrollers` etc, or have a `type` (GVK?) column.

**Comment by liggitt** [comment]
cc @juanvallejo

**Comment by juanvallejo** [comment]
hm, if we have a `type` column, it would show redundant information in cases where resources don't already display with a shorthand name. I'm on board with just displaying the full resource name as part of the `NAME` column, any thoughts?

**Comment by stevekuznetsov** [comment]
I'm not sure I agree re: redundant information. Instead of printing `type/name` in the `NAME` column, just print `name` and then print the type in the `TYPE` column.

**Comment by stevekuznetsov** [comment]
I would not expect:
```
TYPE NAME
pod  pod/mypod
```

I would expect:
```
TYPE NAME
pod  mypod
```

**Comment by juanvallejo** [comment]
Okay, I'll put a PR together

cc @rhcarvalho

**Comment by rhcarvalho** [comment]
From what I recall, and might be what @juanvallejo hinted at, the problem with the TYPE column is that if we have a single resource type in the output, it becomes redundant to include that column:

```
$ oc get pods
TYPE  NAME
pod   foobar
```

And we don't want the number of columns in the output to change depending on the output, nor breaking backwards compatibility, I believe, or we might be breaking scripts that parsed that output.

The introduction of type/name form was to fix a long standing issue that `oc get all` would return messy, unintelligible output.

Personally, I'm fine with the current output.

In any case, if this is to change it needs to be discussed upstream.

**Comment by stevekuznetsov** [comment]
>  if we have a single resource type in the output, it becomes redundant to include that column

This will by far be the uncommon case on an `oc get all` and I don't mind if we do not optimize for it.

I am also fine without having a `TYPE` column, just long-form names. I might not know what an `rc` or `po` is when I `oc get all` and using the long-form name would make it clear what you're looking at.

**Comment by juanvallejo** [comment]
> I am also fine without having a TYPE column, just long-form names. I might not know what an rc or po is when I oc get all and using the long-form name would make it clear what you're looking at.

Hm, this is a valid point, as a new user I do not think I would be familiar with `dc`, or `rc` at first glance, but I also think displaying `replicationcontroller` would take up significant space. Maybe there could be some kind of lookup table, or `describe` type command that the user could use to receive more information on shorthands and terms they are not familiar with?

**Comment by oatmealraisin** [comment]
If you use `oc get`, it says what shorthands mean.  Shameless plug: #9326

**Comment by juanvallejo** [comment]
This issue no longer occurs on new clients.

Please re-open if still relevant.
