### ISSUE TITLE
flake in cmd/images: cannot delete istag

### ISSUE THREAD

**Issue by miminar** [openshift/origin#10274]
This one looks scary:

```
Running test/cmd/images_tests.sh:237: executing 'oc delete istag/perl:5.16 --context='default/127-0-0-1:28443/system:admin'' expecting success...
FAILURE after 0.213s: test/cmd/images_tests.sh:237: executing 'oc delete istag/perl:5.16 --context='default/127-0-0-1:28443/system:admin'' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: imagestreams "perl" not found
```

Job https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/4708/console

Here's some test context:

```
# test deleting a tag using oc delete
os::cmd::expect_success_and_text "oc get is perl --template '{{(index .spec.tags 0).name}}'" '5.16'
os::cmd::expect_success_and_text "oc get is perl --template '{{(index .status.tags 0).tag}}'" 'latest'
os::cmd::expect_success "oc delete istag/perl:5.16 --context='${cluster_admin_context}'"
```

So it's clear that both image stream and the tag exist. Can the changed context be somehow related?

**Comment by miminar** [comment]
To make the bot happy, here's a parent job link: https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/7632/

**Comment by mfojtik** [comment]
@miminar I think the test is wrong? the image streams are created in the "openshift" namespace, not in "default".

**Comment by mfojtik** [comment]
@deads2k fyi (I think you was changing this recently and yes, I reviewed it :-(

**Comment by miminar** [comment]
@mfojtik you're right! The containing namespace is `test-cmd-images-2`. So it looks like the `cluster_admin_context` is outdated.

**Comment by deads2k** [comment]
> @mfojtik you're right! The containing namespace is test-cmd-images-2. So it looks like the cluster_admin_context is outdated.

Weird that its a flake, not a failure.

**Comment by smarterclayton** [comment]
Maybe the perl image is flaky

**Comment by soltysh** [comment]
I've added explicit project name in the delete command, let's see how that helps.
