### ISSUE TITLE
As a project admin, oc get roles returns nothing

### ISSUE THREAD

**Issue by danmcp** [openshift/origin#10285]
Which I assume is correct although I am not sure why off the top of my head.  But my primary complaint is it's disconcerting to get nothing back as the client.  Did it error and not tell me?  Did I get all the roles and there are none?  Did I get all the roles that I can see and I can see none?  I have no idea from the output.

**Comment by liggitt** [comment]
all empty lists returned to `oc get *` behave that way... if we want to fix it, we have to change it for everything

**Comment by deads2k** [comment]
> Did I get all the roles and there are none?

Yes, standard `oc get` behavior.

**Comment by deadliggitt** [comment]
Yeah, the empty list is correct (since there are no local roles defined in your current namespace)

**Comment by danmcp** [comment]
Behavior understood in this particular case.  Still don't like the general usability.

@fabianofranz Thoughts on how to improve this generically?

**Comment by liggitt** [comment]
If we plumb stderr, we could write a warning there in the case of an empty list where the output format would mean there's no output to stdout

**Comment by fabianofranz** [comment]
+1 for better UX in `get`. Needs to happen upstream though. I'll add this as part of https://trello.com/c/04lpfTQR where other `get` and general printer improvements are being planned.

**Comment by juanvallejo** [comment]
I can put a PR together for this. Would resources through `HumanReadablePrinter` be the only case affected, or would we  want to output a warning when `--output` is also `name`, `json`, or `yaml`?
