### ISSUE TITLE
It isn't clear what roles are available as a project admin

### ISSUE THREAD

**Issue by danmcp** [openshift/origin#10282]
I can add a user with:

oc policy add-role-to-user <role> <username> -n <projectname>

And this is fairly obvious in the UI.  But it isn't obvious where to see a list of available roles.  This is the closest thing:

oc get clusterroles 

But isn't really doc'ed and isn't obvious how to find.  And what I really want is a simple place to see something like this:

https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#roles

But in a more obvious place than the architecture docs.

**Comment by mfojtik** [comment]
@danmcp so you want that command to suggest the valid role names?

@fabianofranz

**Comment by danmcp** [comment]
@mfojtik That would be nice.  Or another more obvious command would be good too.
