### ISSUE TITLE
It isn't clear how to get a container name from oc exec

### ISSUE THREAD

**Issue by danmcp** [openshift/origin#10283]
It says: 

Options:
  -c, --container='': Container name. If omitted, the first container in the pod will be chosen

A pointer to oc describe would be useful.

Same for oc rsync and probably other commands.

**Comment by juanvallejo** [comment]
Reopening for this PR: https://github.com/openshift/origin/pull/10469

**Comment by juanvallejo** [comment]
@danmcp Wondering if you had any feedback / thoughts on this discussion: https://github.com/openshift/origin/pull/10469
