### ISSUE TITLE
As an atomic-registry installer, I want to configure the port the registry uses.

### ISSUE THREAD

**Issue by thomasmckay** [openshift/origin#10287]
When installing and configuring atomic registry, the default port (5000) conflicts with katello's pulp-based registry service. To run both on the same server the atomic registry port needs to be configurable.

The following provides steps to configure post installation:
https://gist.github.com/aweiteka/2fd4f2a90e1842b26ac94345471dc00b/

cc: @aweiteka

**Comment by aweiteka** [comment]
@danmcp if possible please assign to me.

**Comment by danmcp** [comment]
@aweiteka I sent you an invite a while back to join the org.  You have to accept that before you can have stuff assigned to you.

**Comment by thomasmckay** [comment]
Note: This issue will cover docker pull port (5000), cockpit UI, openshift api, and kubernetes api.
