### ISSUE TITLE
CLI and console treat severity of missing probes differently

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#10294]
The CLI shows probes as "warnings" whereas the console shows them as "info" severity.  Need to decide which severity is appropriate.  In the console we felt like missing health checks was important to be notified of but that it wasn't worthy of the "warning" status.

**Comment by jwforres** [comment]
cc @deads2k since this is related to oc status

**Comment by jwforres** [comment]
@fabianofranz @juanvallejo did the CLI notifications end up going in as Warnings or as Info ?

**Comment by juanvallejo** [comment]
@jwforres The liveness probe warnings ended up going in [as Warnings](https://github.com/openshift/origin/pull/10363/files#diff-5e2cc6c782846b03614c62e3d4d53d66R103) to match the severity of readiness probes

**Comment by jwforres** [comment]
@juanvallejo do you know if the CLI today even has a severity level below warning for oc status?

**Comment by spadgett** [comment]
@juanvallejo Sounds like the CLI also has separate warnings for liveness and readiness probes? The web console has a single health checks warning.

**Comment by juanvallejo** [comment]
@jwforres 
> do you know if the CLI today even has a severity level below warning for oc status?

Yes, there is also an [Info severity](https://github.com/openshift/origin/blob/master/pkg/api/graph/interfaces.go#L29-L37), however any markers with that severity do not show up even in the verbose output of `oc status`.

@spadgett 
> Sounds like the CLI also has separate warnings for liveness and readiness probes?

Yes, we currently do readiness checks for deployment configs, and separate liveness checks for dc's and rc's not owned by a dc

**Comment by juanvallejo** [comment]
cc @deads2k

**Comment by jwforres** [comment]
Just making sure... does anyone disagree with the idea of these being INFO level messages instead of warnings?

**Comment by deads2k** [comment]
> Just making sure... does anyone disagree with the idea of these being INFO level messages instead of warnings?

I don't care one way or the other.
