### ISSUE TITLE
Default build log level doesn't include info about the commit that was cloned

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#10296]
If I dig through the default build logs I can eventually find the commit ID that it cloned, but it would be good at the point where we are cloning to say what the commit ID, message, and author were so that when I'm reading the build logs its clear which one I'm looking at.

**Comment by oatmealraisin** [comment]
So we could go with classic Git --pretty formats, which are

oneline:
```<sha1> <title line>```

and medium:

```
commit: <sha1>
Author: <author>
Date: <date>

<Title line>

<Commit message>
```

Of course we could change this to whatever we want.  I took these from the PRETTY FORMATS section of `man git log`

What loglevels should these be at?  Is there a standard we use for each level?

**Comment by bparees** [comment]
Take a look at what we already print in the build describer, we should
mimic that.

As for the log level, I think this should be at level 0 so it always shows
up.

Ben Parees | OpenShift
