### ISSUE TITLE
Add a `make install` target to the Makefile

### ISSUE THREAD

**Issue by oatmealraisin** [openshift/origin#10303]
As a developer, it would make the process of installing openshift and its tools easier if the Makefile had an install target that would
1. Run `make build`
2. Move binaries into /usr/bin or something of that nature
3. Set up man pages and autocompletions for me

This is a pretty standard feature for open source projects, and I think it's important for a project as large as this to have it.  

It was mentioned that having another install method besides the RPM would introduce unneeded complexity, but this is a separate use case, embodied [here](https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#openshift-development) where the user is already building from source.

It was also mentioned that, normally, `make install` requires super user access to install binaries, and that it is a security risk and sketchy to do that.  However, since the source code for Origin is strictly checked and maintained by Red Hat, I think it is safe for a user to trust this code with a `sudo make install`

@stevekuznetsov @smarterclayton If I missed any points in our conversation, lmk

**Comment by smarterclayton** [comment]
The general counter to this was that different distributions have correct
places for binaries, and that's generally the spec author's responsibility,
not ours.  I would *not* be in favor of lots of complex OS detection logic
in our code to set those.  Adding things to your path is not the end of the
world, and man pages are also not the end of the world (I don't see a
benefit for "oc help foo" vs "man oc-foo" today).
