### ISSUE TITLE
Feature Request: Scope for Request Project Creation

### ISSUE THREAD

**Issue by ALRubinger** [openshift/origin#10309]
Developer Programs has an OAuth client application which needs to be able to request project creation for a user.  Currently users may accomplish this via the web console or `oc` client, which have special unrestricted access.  Our OAuth application needs to be able to act on behalf of a user to:
- Create a new project/namespace
- Obtain access for admin rights to this project

For issue review/triage: @liggitt @bparees 

Thanks!

**Comment by bparees** [comment]
@deads2k @smarterclayton /cc

**Comment by deads2k** [comment]
You'll need a cluster-admin to create an oauth client resource for you.  See https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#oauth.  After you have that, you just use your client id/secret to go through the normal oauth flow.

Provisioning projects for a user is beyond the power that a serviceaccount has when acting as an oauth client.

**Comment by deads2k** [comment]
Oh, and `role:self-provisioner:*` and `role:admin:*:!` will get you a user token with the power to hit the projectrequests endpoint and then have the power to act in that new project.

We've considered adding a specific role for: "create a new project and let me have full powers in any project I create", but current labels don't provide enough detail to plumb it all through.  It would end up being a card I think.

**Comment by ALRubinger** [comment]
Yep, understood on the cluster-admin and creating an OAuth client resource; thanks!  And I don't think a serviceaccount makes sense in our case because we'd be one application servicing N users, not an application-per-user or application-per-namespace (as in the Jenkins instance case).

Am I reading you correctly that `role:self-provisioner:*` and `role:admin:*:!` accomplish this use case for us already, only in two scopes as opposed to the new card you reference?

Ultimately we'll need this to be able to target OpenShift Online to act on behalf of a user. :)

**Comment by deads2k** [comment]
> Am I reading you correctly that role:self-provisioner:* and role:admin:*:! accomplish this use case for us already, only in two scopes as opposed to the new card you reference?

These powers are little more broad.  For instance, a cluster-admin should never grant you those scopes since you'd have visibility into openshift-infra.



> Ultimately we'll need this to be able to target OpenShift Online to act on behalf of a user. :)

I can't speak for whether ops would grant you those powers.  You'll probably need to start an internal thread.

**Comment by ALRubinger** [comment]
Got it; so those scopes are, at present, too broad to be granted by ops for OpenShift Online.  

Hence this feature request. :)  I'd like to be able to create a project on behalf of a user and have admin rights to it.

Analogy: GitHub has a scope allowing me to create or fork a repository and have complete access to that repo.

**Comment by deads2k** [comment]
> Got it; so those scopes are, at present, too broad to be granted by ops for OpenShift Online.

What I mean is, "a cluster-admin can never click approve on you prompt".  They could let you request those scopes, and regular users can safely push the "approve" button.

**Comment by smarterclayton** [comment]
We definitely need to summarize the minimal design here and get it into
card form (based on whatever path we want to take with project-request and
templates and patterns).  We definitely want jenkins service account to be
able to create a certain type of project, limited by quota.

**Comment by ALRubinger** [comment]
Really appreciate your help, @deads2k.  

I'll follow up with an email to the dev list summarizing clearly the use case.  For instance @smarterclayton this will differ from a Jenkins service account approach.

**Comment by deads2k** [comment]
Opened https://trello.com/c/3JpqSgIH/782-add-oauth-scope-for-can-create-projects-and-have-full-access-in-the-projects-it-created with initial thoughts.
