### ISSUE TITLE
gitserver image should consume `oc` by being built on `openshift/origin`

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#10306]
Right now the gitserver Dockerfile is not based on `openshift/origin` and has to copy in the `oc` binary in kind of a hack-ey way ... we should just base it on `openshift/origin` instead of `openshift/origin-base` and get the `oc` binary for free by being a descendant.

**Comment by csrwng** [comment]
The reason that it wasn't based on origin was because we had a volume in origin that would cause the gitserver image to fail to deploy. Now we've removed the volume in origin and we can go back to using it as the base.
