### ISSUE TITLE
As an atomic-registry installer, I want to configure the root path to the registry UI and containers.

### ISSUE THREAD

**Issue by thomasmckay** [openshift/origin#10304]
Is it possible to run master with a path prefix? This would let me run on a system where another app owns the root url (eg. katello or Satellite-6).

**Comment by liggitt** [comment]
the API can't be moved from the root. The web console can, I'm not sure about the registry UI

**Comment by mfojtik** [comment]
@aweiteka fyi (the registry UI question)

**Comment by aweiteka** [comment]
@thomasmckay based on our IRC discussion and #10287 I understood we would segment the services based on port, not path. Should this issue be closed?

**Comment by mfojtik** [comment]
@aweiteka agree, closing.

**Comment by thomasmckay** [comment]
ack
