### ISSUE TITLE
nodejs/mongodb extended test flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#10330]
The nodejs/mongo extended test that launches the nodejs example and expects it to be able to connect to the mongodb service to store/retrieve a hit counter fails to connect to mongo randomly:

https://ci.openshift.redhat.com/jenkins/job/origin_extended_image_tests/381/

```
/data/src/github.com/openshift/origin/test/extended/images/sample_repos.go:91
Expected
    [output truncated]
    <span class="code" id="count-value">No database configured</span>
    [output truncated]
to contain substring
    <string>: <span class="code" id="count-value">1</span>
```

I've already updated this test in a couple ways:
1) we ensure the db service is up before trying to access the app
2) the app itself will try to connect to the DB on each request, so if the DB is up when the request comes in, it should be able to connect to the DB

so not sure why it fails to connect to the DB here.  More debug output may need to be added to the sample app to get to the bottom of this.

**Comment by PI-Victor** [comment]
the problem, i think overall - is that the example doesn't do any error handling whenever something happens. 
i will try to give this example an overhaul and test it against origin

**Comment by bparees** [comment]
@PI-Victor keep in mind the example is intended to still work when there is no DB present, so any error handling needs to be restricted to internal logging, not user visible failures.

**Comment by PI-Victor** [comment]
@bparees do you think we really need [all of this concatenation](https://github.com/openshift/nodejs-ex/blob/master/server.js#L13-L33)? or can we keep it simple to only the MONGODB_URL,_USER,_PASS,_PORT
also are you familiar with where OPENSHIFT_NODEJS_PORT,  OPENSHIFT_NODEJS_HOST are defined, i couldn't find any of them in the s2i-nodejs-container or in the origin repo, do we really need them?

**Comment by bparees** [comment]
> @bparees do you think we really need all of this concatenation? or can we keep it simple to only the MONGODB_URL,_USER,_PASS,_PORT

we can't assume MONGODB_URL is defined, so yes we still need to build up the url manually.  In fact if you look at the template for this sample app, you'll see the nothing is defining MONGODB_URL currently.

> also are you familiar with where OPENSHIFT_NODEJS_PORT, OPENSHIFT_NODEJS_HOST are defined, i couldn't find any of them in the s2i-nodejs-container or in the origin repo, do we really need them?

I think you mean OPENSHIFT_NODEJS_IP..anyway they are optional env variables if you want to override the behavior of the app.  OPENSHIFT_NODEJS_PORT still makes sense (control what port the app listens on), OPENSHIFT_NODEJS_IP doesn't make sense anymore, it made sense in v2.  you can remove it if you want.  (and also the "IP" variable reference.  so just always bind to 0.0.0.0)

**Comment by bparees** [comment]
haven't seen this in forever.
