### ISSUE TITLE
TestTriggers_configChange object modified flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#10336]
```
--- FAIL: TestTriggers_configChange (9.62s)
    deploy_trigger_test.go:597: Operation cannot be fulfilled on deploymentconfigs "config": the object has been modified; please apply your changes to the latest version and try again
FAIL
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/4802/console

i know we have similar race condition flakes open, but not sure if they are identical to this one. feel free to dupe as needed.

**Comment by mfojtik** [comment]
@bparees I think they are I will verify that tomorrow.

**Comment by mfojtik** [comment]
interesting, this error comes from a `RetryOnConflict` so we should never see this error unless it is retrying forever.

**Comment by bparees** [comment]
hit this again: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/7880/consoleFull#-91861563756bf4006e4b05b79524e5923
