### ISSUE TITLE
RFE: be able to oc get image with short SHA

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#10332]
Currently if I want to get image information I need to pass the entire SHA to be able to get it, or do `oc get image <sha> |  grep <short sha>`. The short version is presented in `oc describe imagestream` and soon to be added in `oadm top images`.

**Comment by liggitt** [comment]
that's tough, given how images are stored... we'd have to maintain a prefix index and make the API respond to it

**Comment by soltysh** [comment]
Yeah, I was shortly thinking about it but it still would be nice to have, but not so much important so I marked it with p3.

**Comment by mfojtik** [comment]
@soltysh drop a trello card in devexp if you still want this.. closing this as 1y old ;-)
