### ISSUE TITLE
test/extended/core.sh: leave temporary files after running

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#10351]
`test/extended/core.sh` creates temporary `*.kubeconfig` files in the current directory and doesn't remove them after its execution.
##### Steps To Reproduce

`./test/extended/core.sh --ginkgo.focus="extended build"`
##### Current Result

After running the tests I have a couple of files `*.kubeconfig` (like `extended-test-extended-build-6id0f-bltmf-user.kubeconfig`) in the current directory that weren't here before.
##### Expected Result

Tests should remove its temporary files.

**Comment by stevekuznetsov** [comment]
We set up a fake `$HOME` so this should no longer be an issue.
