### ISSUE TITLE
deploymentconfig image field is confusing in presence of an ICT

### ISSUE THREAD

**Issue by bparees** [openshift/origin#10356]
When a user provides an ImageChangeTrigger (ICT) and also defines a value in the "image" field of the pod template for the DC, you end up with race conditions in which the deployment might be based on the value of the image field, or it might be based on the value resolved by the ICT.

It should be a validation error to provide an image field value when the DC also defines an ICT.  Of course there are backwards compatibility concerns here.

And I'm still pretty confused about all the ICT functional scenarios, since the PR for changing their behavior has not yet merged.  So someone who knows more about what's going on there than I should evaluate this.

@kargakis @mfojtik

**Comment by mfojtik** [comment]
@bparees if you add validation error and you create DC without ICT and then you are trying to add it later on, should we refuse it? ;-)

**Comment by bparees** [comment]
@mfojtik i'm just raising problems, you have to provide the solutions.. isn't that how this works? :)

**Comment by smarterclayton** [comment]
I don't see why this should be blocked via validation.  That breaks other scenarios, like taking pod templates from generic tools and putting them into deployment configs, so I'm unlikely to allow that change to happen for API compat reasons.

If the author specifies conflicting ICT and Image, as long as the ICT eventually triggers, that's giving the user what they asked for and is within the bounds of other API use.  My question here would involve: "why are users doing that"?  And it's probably because "we didn't let them work around it until 1.3?"

**Comment by mfojtik** [comment]
@smarterclayton I think we plan to allow users to use IS for k8s deployments, right? Should we work out some generic solution (like using annotations to map images to image streams) so users can use IS in both DC and D without even having ICT defined in DC.

**Comment by bparees** [comment]
> My question here would involve: "why are users doing that"? 

two scenarios i've run into:
1) they just don't understand what the image field is for, so they think they're putting an imagestream tag ref in there, not realizing it's actually a pull spec (and in some cases it's a valid pull spec, so they get unexpected behavior.. eg they put "jenkins" in there and they get jenkins from dockerhub/lib/jenkins instead of the jenkins imagestream, and nothing works and they don't know why the image is broken)
2) they didn't have imagestreams defined in their cluster so when the ICT didn't work, they added the value to the image field (special case of (1) i guess).

So there's no doubt it's fundamentally an education problem and i agree w/ the api compat issue, but it seems like we need to do *something* to help users out here, because they are definitely confused.

**Comment by bparees** [comment]
> If the author specifies conflicting ICT and Image, as long as the ICT eventually triggers, that's giving the user what they asked for and is within the bounds of other API use.

and while i agree it's giving them what they asked for and matches the api contract, it is definitely not giving them what they wanted, or what they thought they asked for.  I don't think anyone has ever defined a deploymentconfig thinking "i'm going to list a pullspec here, and an imagestream over here, and you can give me whichever one you find first, i don't care"

**Comment by smarterclayton** [comment]
Actually, I have.  Because I'm setting up deployment configs that should pull the template based on the base state, and the trigger is an override.

**Comment by bparees** [comment]
> Actually, I have. Because I'm setting up deployment configs that should pull the template based on the base state, and the trigger is an override.

well you shouldn't need to because the trigger is supposed to be resolved as part of creating the first deployment.  (unless you have a case where that imagestream doesn't exist yet, which is where things get weird and i think it's hard to make a case that "i want to use this other docker image until the imagestream becomes available" as opposed to "i should create this imagestream if i want to use it")

**Comment by smarterclayton** [comment]
I agree there is confusion.  But there's no chance to fix this with
validation because:

a) we're not going to break the "copy spec from a to b and then set
triggers"
b) this is something we've always supported, so we aren't going to break
old deployment configs (which set both of these)
c) when we move to upstream deployments, we'll have this same problem
because triggers are annotations

Is there a fix that doesn't involve API breaks?

**Comment by bparees** [comment]
well part of my point in raising it was to get ahead of ending up in the same situation with upstream deployments when we adopt them and add imagestream support to them.

I understand the API limitations, the other reason i opened the issue was to brainstorm what we could possibly do in this space.  Perhaps it should be an oc status warning message.

**Comment by smarterclayton** [comment]
I suspect we will be in the same spot - the core spec is oblivious to
image streams, and we'll have to layer well.

**Comment by bparees** [comment]
but at the time we introduce that layer, can't we declare that using that layer is incompatible with using the existing image field?

**Comment by smarterclayton** [comment]
No, because we'll need to work with old Deployments.  And other tools
will as well.

**Comment by mfojtik** [comment]
@kargakis FYI

**Comment by kargakis** [comment]
> When a user provides an ImageChangeTrigger (ICT) and also defines a value in the "image" field of the pod template for the DC, you end up with race conditions in which the deployment might be based on the value of the image field, or it might be based on the value resolved by the ICT.

Haven't we fixed these races? I don't think we can push validation harder than what we already have done (w/ respect to the support for empty image fields).

**Comment by kargakis** [comment]
Btw, we definitely need better docs around explaining triggers.
