### ISSUE TITLE
applyClientConnectionOverrides should not fall back to 5qps for empty configs

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#10368]
https://github.com/openshift/origin/commit/1f31ddc8a6a04a2d760d460f604f0ff5f9cec074#diff-470100313a22a3d400a33c61d6fa0865R350 takes defaults from config if present

if not present (or if a particular field is not present), it uses the client defaults (e.g. 5QPS), causing things like https://bugzilla.redhat.com/show_bug.cgi?id=1364431 (fixed in https://github.com/openshift/openshift-ansible/pull/2287/files). If we want the defaults to be something other than 5 (and we do), we should have local defaults in code that are closer to the original controller defaults

cc @deads2k

**Comment by deads2k** [comment]
Having made this comment: https://github.com/openshift/origin/pull/9814#discussion_r72104312 only make it worse :(
