### ISSUE TITLE
Proposal: Generic way of "suggesting" commands from a usage template

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#10362]
Some commands might improve their usability by suggesting other openshift commands to retrieve extra information that is needed, or simply to indicate which commands could be executed next by the user (e.g. creating a flow between `oc new-project` and `oc new-app` by suggesting `new-app` somewhere on the usage template of the `new-project` command).

It would be nice to have a standard way of setting these command suggestions. An idea could be to export a function from https://github.com/openshift/origin/blob/master/pkg/cmd/templates/templater.go that receives a pointer to the command making the suggestion, the string suggesting which command to use, and perhaps a function that returns a boolean indicating in which conditions to output this suggestion (or some other case). This function could be saved somewhere in `templater.go` and be returned by another generic function that gets called from the actual template.

Just an idea, but open to further thoughts.

cc @fabianofranz @liggitt @deads2k @smarterclayton

**Comment by smarterclayton** [comment]
Are these usage suggestions like we have for new-app and status
(displayed when you run the command, complete sentences)?  Or just
something like what man shows at the bottom?

**Comment by juanvallejo** [comment]
@smarterclayton 
They are like the ones we have for `new-app` and `status`

**Comment by smarterclayton** [comment]
Those are very code driven, so it doesn't seem likely that we would define
them in the command definition itself.  For instance, the new-app ones only
show up when specific conditions happen.

**Comment by bparees** [comment]
doesn't seem likely we're going to proceed on this, at least not generically.
