### ISSUE TITLE
A small error in v1.3.0-alpha.3 of the document.

### ISSUE THREAD

**Issue by warmchang** [openshift/origin#10371]
[A small error in v1.3.0-alpha.3 of the document.]

##### Version
v1.3.0-alpha.3

##### Steps To Reproduce
1. [The release note, https://github.com/openshift/origin/releases/tag/v1.3.0-alpha.3]
2. [One word "can" is redundant]

##### Additional Information

> Egress Firewalls for namespaces
> 
> A new resource EgressNetworkPolicy has been added which controls how
> traffic exits a namespace. Administrators **can can** use these as
> outbound firewalls when using the multi-tenant SDN network. Each rule
> can be an allow or deny rule, and targets a CIDR. Since policy can
> only be changed by administrators, you can update your out of the box
> project template to include a firewall policy that applies to
> individual namespaces, and then later change to be more permissive.

**Comment by danmcp** [comment]
Fixed, thx!
