### ISSUE TITLE
Project grouping feature

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#10395]
If you are the administrator of 100 or more projects, it is really difficult to find projects,in order to organize projects, we propose a new feature called  "project grouping", in order to share the idea we have developed a prototype.

https://youtu.be/WEbBQ8wLD68

Bye.

**Comment by deads2k** [comment]
@roldancer That's a neat demo.  How were you able to associate the projects with each other?  Did it require any additional permissions for a project-admin?  If there are two project admins, can we group the projects differently?

**Comment by roldancer** [comment]
@deads2k every project admin can create the projetc grouping that they want, project grouping from my point of view should be a user's configuration, it woulb be great if one project admin can shared the project grouping configuration json/yaml file with other admins.

**Comment by deads2k** [comment]
> @deads2k every project admin can create the projetc grouping that they want, project grouping from my point of view should be a user's configuration, it woulb be great if one project admin can shared the project grouping configuration json/yaml file with other admins.

Can you share how you made it work?  That would be a really nice feature if we could find a way to do it that didn't rely on client-side information.
