### ISSUE TITLE
MYSQL_SERVICE_HOST and MYSQL_SERVICE_PORT env variables are not present

### ISSUE THREAD

**Issue by Tocacar** [openshift/origin#10401]
The documentation states that these env variables should be present to my application, however, they are not.

##### Version
oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
When I try to build my app referencing the above environment variables for my database connection, the build fails.

##### Current Result

```
[PDOException]
SQLSTATE[HY000] [2002] No such file or directory
```

##### Expected Result

I expect the variables to be read by my app, and the database connection to be successfully instantiated.

##### Additional Information

In the web console view, and after running "oc env pods --all --list", I can only see the MYSQL env variables for database, user and password.

**Comment by bparees** [comment]
how did you create your application?  Those environment variables only exist if you have defined a service named "MYSQL" in your project.  Which is done by the example templates:
https://github.com/openshift/origin/blob/master/examples/db-templates/mysql-ephemeral-template.json#L14-L17
https://github.com/openshift/origin/blob/master/examples/db-templates/mysql-ephemeral-template.json#L173-L177

https://github.com/openshift/origin/blob/master/examples/quickstarts/cakephp-mysql.json#L247-L253
https://github.com/openshift/origin/blob/master/examples/quickstarts/cakephp-mysql.json#L433-L436

Also if you can point me to the documentation you are referring to, perhaps we can make it clearer.

**Comment by bparees** [comment]
closing due to lack of information.

**Comment by alvarotorrico** [comment]
I´m having the same problem.
Following the steps from openshift documentation, MYSQL_SERVICE_HOST and MYSQL_SERVICE_PORT are not created.
Documentation is here https://docs.openshift.com/enterprise/3.1/using_images/db_images/mysql.html

Command to create the mysql app is $ oc new-app -e MYSQL_USER=<username>,MYSQL_PASSWORD=<password>,MYSQL_DATABASE=<database_name> registry.access.redhat.com/openshift3/mysql-55-rhel7

This format is deprecated and I have to use
$ oc new-app -e  MYSQL_USER=<username> -e MYSQL_PASSWORD=<password> -e MYSQL_DATABASE=<database_name> registry.access.redhat.com/openshift3/mysql-55-rhel7
