### ISSUE TITLE
Improper output on failed registry create

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#10404]
```
$ oadm registry
--> Creating registry registry ...
    error: serviceaccounts "registry" already exists
    error: rolebinding "registry-registry-role" already exists
    deploymentconfig "docker-registry" created
    service "docker-registry" created
--> Failed
error: exit directly
```

The wrong `ErrExit` is being returned - the one from kube needs to be used, and ours should be removed now.

**Comment by juanvallejo** [comment]
@smarterclayton I looked in [kubectl/cmd/util](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/helpers.go#L54), but was only able to find `DefaultErrorExitCode` defined, not a message. Was there a specific message from kube you wanted used instead of `ErrExit`?

**Comment by smarterclayton** [comment]
It's part of  Implement kubectl set probe
<https://github.com/kubernetes/kubernetes/pull/25451> but hasn't merged
yet.  Can you grab that commit (Allow callers to bypass
cmdutil.CheckError() logging
<https://github.com/kubernetes/kubernetes/pull/25451/commits/eedb67a30d3591bb609d649043a99f8fc46cd64a>)
and get it merged?

**Comment by juanvallejo** [comment]
@smarterclayton Sure, will do
