### ISSUE TITLE
oc status support for upstream deployments and replica sets

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#10411]
@mfojtik @deads2k @smarterclayton

**Comment by deads2k** [comment]
@mfojtik nice to have to 3.3 if someone isn't already busy.

**Comment by mfojtik** [comment]
@deads2k I can take a look

**Comment by mfojtik** [comment]
Initially seemed easy, but not it seems like a lot of duplication. We would rather avoid doing this in rush for 3.3 and do it "right" post-3.3.

**Comment by kargakis** [comment]
Raising priority on this one as it has fallen through the cracks for some time

/priority P2

**Comment by smarterclayton** [comment]
This is becoming a serious blocker for debt, because we are now using
deployments extensively.

On Sun, Sep 17, 2017 at 6:22 PM, Michalis Kargakis <notifications@github.com

**Comment by kargakis** [comment]
@mfojtik mind fixing the milestone?

**Comment by mfojtik** [comment]
@kargakis i guess this is more like 3.10.0 at this point

**Comment by mfojtik** [comment]
@kargakis this should be already done

**Comment by mfojtik** [comment]
we also support statefulsets
