### ISSUE TITLE
Metrics in the console is broken.

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#10419]
Metrics in the console based on the latest from master are broken.

The graphs start off normal, but then when they go to update they only bring in one datapoint, and then on the next data point its start back again to normal.

##### Version
latest from master:
openshift v1.3.0-alpha.3+1c80911-dirty
kubernetes v1.3.0+507d3a7
etcd 2.3.0+git

##### Steps To Reproduce
1. install origin from master and configure origin-metrics
2. go to the console and open a pod's metric page
3. notice that the metric page looks right
4. wait for the console to update, notice how its now just one datapoint
5. wait for the next update, notice that the graphs is right again.

Initial working graphs:
![screenshot from 2016-08-15 13-42-21](https://cloud.githubusercontent.com/assets/691166/17673324/8e2d0254-62ee-11e6-9a1b-11dfbcfaf917.png)

After waiting for an update:
![screenshot from 2016-08-15 13-42-37](https://cloud.githubusercontent.com/assets/691166/17673329/90d2b954-62ee-11e6-996f-2c9105497999.png)

**Comment by mwringe** [comment]
@spadgett can you take a look?

**Comment by spadgett** [comment]
@jwforres FYI

**Comment by spadgett** [comment]
Only appears to be an issue for pod metrics, not deployment metrics.
