### ISSUE TITLE
All subcommands under 'oc create' must support dry run

### ISSUE THREAD

**Issue by fabianofranz** [openshift/origin#10426]
We need to be able to visualize how the given resource would look like in JSON and YAML before actually creating it. Some of the subcommands like `oc create quota` already support it, but we need to make sure it's supported for all of them.

**Comment by juanvallejo** [comment]
List of all of the `oc create` sub-commands without a `--dry-run` option:

```
- clusterresourcequota
- deploymentconfig
- identity
- imagestream
- policybinding
- route
- secret
- service
- user
- useridentitymapping
```
