### ISSUE TITLE
add node,"type: NodePort" doesn't work, Pod on the new node

### ISSUE THREAD

**Issue by lifei825** [openshift/origin#10436]
add a node:ansible-playbook playbooks/byo/openshift-node/scaleup.yml
On the new node have a pod, but the service port Can only be a new node IP access, other IP can't access this port(Pod on the old node is good)
The iptables could not find the Cluster IP：`grep 172.30.204.146 /etc/sysconfig/iptables` is none
please, Port of new node, how to let all nodes can access：`telnet everynode NodePort` is ok
thks
##### Version

origin 1.2.0/1.2.1
docker 1.9/1.10.3
openshift-ansible-openshift-ansible-3.0.83-1

**Comment by knobunc** [comment]
@lifei825 Can you give me more details about what you are trying to do?

/etc/sysconfig/iptables will not contain the service address (unless you save the iptables state, but that is not recommeneded).  If you want to see the entries, run the 'iptables-save' command and you can grep that.

If you continue to have trouble, take a look at https://docs.openshift.com/enterprise/3.2/admin_guide/sdn_troubleshooting.html and see if that helps.  But if you can't work it out, please use the debug.sh script referenced at https://docs.openshift.com/enterprise/3.2/admin_guide/sdn_troubleshooting.html#further-help and get me the tar file it generates.

**Comment by lifei825** [comment]
ok，tks
