### ISSUE TITLE
TASK [openshift_common : Install the base package for versioning]

### ISSUE THREAD

**Issue by prasenforu** [openshift/origin#10482]
Installaing 3.2 in centOS in TASK [openshift_common : Install the base package for versioning] section facing following error.

TASK [openshift_common : Install the base package for versioning] **************
fatal: [master.teg.com]: FAILED! => {"changed": false, "failed": true, "msg": "No Package matching 'atomic-openshift-0.0' found available, installed or updated", "rc": 0, "results": []}
##### Version

[provide output of the `openshift version` or `oc version` command]
##### Steps To Reproduce
1. [step 1]
2. [step 2]
##### Additional Information

[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by detiber** [comment]
@prasenforu can you provide more information on how you are installing?

If you are using the advanced installation (running the playbooks directly)
- What does your inventory file look like?
- Are you installing the playbooks from RPM? Which version?
- Are you using a checkout of openshift-ansible? Which branch? 

The thing that stands out the most to me is that it is attempting to install `atomic-openshift-0.0` rather than `origin` with a proper version number, which would lead me to believe that the inventory file you are using has `deployment_type=openshift-enterprise` rather than `deployment_type=origin`.

**Comment by prasenforu** [comment]
Looks like issues got resolved.

You can close.

Thanks & regards,
Prasenjit

+91 9830736299

On 17 Aug 2016, at 7:39 pm, Jason DeTiberus <notifications@github.com<mailto:notifications@github.com>> wrote:

@prasenforu<https://github.com/prasenforu> can you provide more information on how you are installing?

If you are using the advanced installation (running the playbooks directly)

  *   What does your inventory file look like?
  *   Are you installing the playbooks from RPM? Which version?
  *   Are you using a checkout of openshift-ansible? Which branch?

The thing that stands out the most to me is that it is attempting to install atomic-openshift-0.0 rather than origin with a proper version number, which would lead me to believe that the inventory file you are using has deployment_type=openshift-enterprise rather than deployment_type=origin.

**Comment by detiber** [comment]
@tbielawa @smunilla there is a comment incoming for this issue from kbsingh (CentOS) to provide some more info for a reproducer when deploying Origin. Please take a look after any release blockers are taken care of.

**Comment by kbsingh** [comment]
Hi,
This problem persists in the CentOS-PaaS Sig content ( installer from http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/ ); The installer when starting up also only indicates a single install type, which seems to point at the enterprise product.

**Comment by detiber** [comment]
tagging in @abutcher as well
