### ISSUE TITLE
In the different network speed is very slow needs calico network plugin 

### ISSUE THREAD

**Issue by zhwenh** [openshift/origin#10488]
could you tell me how to  configure openshift master and node with **calico** network plugin details , following your steps,thank a lot !
##### Version

openshift 1.2.1

openstack vm use ovs network ,openshift Also with ovs network, 
In the different network speed is very slow （openshift installed The virtual machine IP in different segments）,
iperf -s -p31601 -m -i 1
[  4] local 172.88.5.4 port 31601 connected with 172.88.10.2 port 46352
[  4]  0.0- 1.0 sec  1.92 MBytes  16.1 Mbits/sec
[  4]  1.0- 2.0 sec  0.00 Bytes  0.00 bits/sec
[  4]  2.0- 3.0 sec  0.00 Bytes  0.00 bits/sec
[  4]  3.0- 4.0 sec  1.93 MBytes  16.2 Mbits/sec
[  4]  4.0- 5.0 sec  0.00 Bytes  0.00 bits/sec
[  4]  5.0- 6.0 sec  0.00 Bytes  0.00 bits/sec
[  4]  6.0- 7.0 sec   619 KBytes  5.07 Mbits/sec
[  4]  7.0- 8.0 sec  2.13 MBytes  17.8 Mbits/sec
[  4]  8.0- 9.0 sec  0.00 Bytes  0.00 bits/sec
[  4]  9.0-10.0 sec  0.00 Bytes  0.00 bits/sec
[  4]  0.0-10.8 sec  7.46 MBytes  5.80 Mbits/sec
[  4] MSS size 1348 bytes (MTU 1438 bytes, unknown interface)

In the same network speed normal. So Suggestions in the openstack environment with the calico, Hope to provide the calico plugin，sample：
networkConfig:
  clusterNetworkCIDR: 10.128.0.0/14 
  hostSubnetLength: 9 
  networkPluginName: "calico" 

 thanks a lot！

**Comment by knobunc** [comment]
@rajatchopra Can you point to any links to help with this please?

**Comment by rajatchopra** [comment]
Its just the way calico works with kubernetes. Use the CNI plugin mechanism. See [this](https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/KubernetesIntegration.md) but instead of modifying kubelet, you will have to modify the openshift node config. 
See issue #8321 as an example of the config changes required in openshift master and nodes. The failure in that issue was related to a broken cni ipam plugin, but should be no factor now.

**Comment by kprabhak** [comment]
Looks like this issue is quite dated, but providing links to Calico installation with OpenShift here for reference.
https://docs.projectcalico.org/latest/getting-started/openshift/installation
https://www.youtube.com/watch?v=FsXuZCEWEhQ

Reckon this issue ought to be closed?

**Comment by rajatchopra** [comment]
Thanks for the updated links @kprabhak 

> Reckon this issue ought to be closed?

I believe so. The information should be sufficient.
@zhwenh please re-open if you still have anything unresolved.
