### ISSUE TITLE
flake[builds][Conformance]build without output image building from templates 

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#10489]
these tests were introduced by me. and usually they flake while waiting for the output of a build with no output: to: image name defined. it's supposed to finish the build successfully but not push the image to the registry.
~~the tests use --wait and --follow so one of these is creating problems.~~
there must be some other reason for the logs to timeout.

```
[Fail] [builds][Conformance] build without output image building from templates [It] should create an image from "/data/src/github.com/openshift/origin/test/extended/testdata/test-s2i-no-outputname.json" S2i template without an output image reference defined 
/data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:44

Ran 148 of 487 Specs in 1458.525 seconds
FAIL! -- 147 Passed | 1 Failed | 0 Pending | 339 Skipped 

Ginkgo ran 1 suite in 24m22.89712002s
Test Suite Failed
[INFO] Running serial tests
```

full log: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/5234/consoleFull
spotted in: https://github.com/openshift/origin/pull/10481

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/7019/consoleFull
