### ISSUE TITLE
Add a migration tool for old registry configs

### ISSUE THREAD

**Issue by miminar** [openshift/origin#10499]
As Docker distribution application evolves, so does evolve its configuration file. Some config options get obsolete, renamed made mandatory. We ourselves introduced some backwards incompatible changes to our middleware configuration section.

This previously led to many bugs and issues filled because of using old configuration files with newer registry version.

To make the transitions to newer registry versions as painles as possible, let's add a migration tool to config files. If the docker registry fails to parse configuration file or our middleware fails to load due to wrong options, let's terminate gracefully with some helpful message like:

```
fatal: obsolete configuration detected, please run `oadm migrate registry-config <oldconfigfile>` to update your config file
```

**Comment by mfojtik** [comment]
Trelloed: https://trello.com/c/q8tlfiQK/780-add-a-migration-tool-for-old-registry-configs

**Comment by liggitt** [comment]
Bumping priority back to p1 if the new registry will not start from an old config

**Comment by mfojtik** [comment]
@liggitt we are going to fix the https://github.com/openshift/origin/blob/f5c4c23ff98bd2a569dee75ff964e0e885a68e6a/pkg/cmd/dockerregistry/dockerregistry.go#L44-L44 parser to set the defaults we need if they are missing, together with a fat warning to users asking them to update the configuration.

@legionus is working on a PR, @miminar FYI.

**Comment by legionus** [comment]
@miminar @mfojtik @pweil-  Since we made the migration in automatic mode I think we can close it.

**Comment by mfojtik** [comment]
@legionus @smarterclayton @liggitt do you think there is a room for `oc admin registry --validate-config` or `oc admin registry --configure key=val` command that we can use to modify existing Docker Registry configuration files in the future? I think it provides better end-user experience than "uploading a YAML into a Secret/ConfigMap and linking it into a dc/docker-registry" or "getting the config.yaml from a Secret/ConfigMap key, editing it and then patching the Secret with updated configuration". WDYT?

**Comment by legionus** [comment]
@mfojtik I think it's better to use [ConfigMap](https://github.com/openshift/origin/issues/8851) if you want to change registry config.

**Comment by liggitt** [comment]
the destination of the config (file, configmap, secret) should be independent from the migration method

I could see an option in `oadm registry` to take a config file, put it in a secret, mount the secret and set the envvar for the registry to load the config:
```
oadm registry --registry-config=/path/to/config.yml
```

to update:
```
oadm registry migrate-config /path/to/config.yml
oc secret new docker-registry /path/to/config.yml -o yaml | oc apply
oc deploy docker-registry --latest
```

**Comment by smarterclayton** [comment]
I'm wondering whether this would be a generic "registry migration" or a more specific "registry config migration".  We aren't going to be able to easily migrate all variants of registry setup *or* config, so there's an argument this should be Ansible specific rather than in the product.
