### ISSUE TITLE
HTTPS for WordPress

### ISSUE THREAD

**Issue by yanusocial** [openshift/origin#10509]
Hi!

I can't deploy wordpress example listening on 443 port.

I modified files `examples/wordpress/pod-wordpress.yaml` and `examples/wordpress/pod-wordpress.yaml` modifying ports inside to 443 with no results.

Please, can you help me? I need to deploy a blog on port 443 in production.
Thank you!

**Comment by bparees** [comment]
You need to actually modify the wordpress code/configuration to listen on 443.  Changing the ports in the pod definition just changes what port openshift expects the container to listen on, it doesn't force the application inside the container to actually listen on that port.

That example is deploying this image:
https://hub.docker.com/_/wordpress/

which does not appear to have an environment variable based way to change the configuration, so i think you'd need to go create your own image (based on that image) which supplies the proper wordpress configuration.

You can also consider looking at this example:
https://github.com/openshift/origin/tree/master/examples/wordpress/template

which builds a brand new custom wordpress image from the wordpress source (or a fork of the wordpress source), meaning you could fork the wordpress repo and modify it to supply your configuration, and then build your own wordpress image from your forked source.

The source repo is a parameter to the template with a default, as seen here:
https://github.com/openshift/origin/blob/master/examples/wordpress/template/wordpress-mysql.json#L289-L293

**Comment by bparees** [comment]
Alternatively, you can just define a TLS route in openshift with edge termination, meaning users will get a TLS connection to the cluster, but the internal network connection from the router to the wordpress instance will be insecure.

**Comment by yanusocial** [comment]
Thank you!
I'll work on it.
