### ISSUE TITLE
Check rpm builds during ci tests

### ISSUE THREAD

**Issue by tdawson** [openshift/origin#10512]
Currently there are no tests that ensure that origin.spec changes don't break rpm builds.
This was discussed in the pull request "have origin.spec use hack scripts to build"
#10398

There is  hack/test-rpm.sh but it is not called anywhere in the tests.
There is also the problem that currently, rpmlint, which is called in hack/test-rpm.sh to check the rpms, gives alot of false errors and warnings.

**Comment by stevekuznetsov** [comment]
We've got the RPM build using `build-cross.sh` and we're running a (non-redistributable) build on every merge.
