### ISSUE TITLE
Append oc copy command to copy a single file to container (like oc rsync)

### ISSUE THREAD

**Issue by harobed** [openshift/origin#10529]
With `oc rsync` I can't upload a single file to the container.

I need to do something like:

```
$ oc exec -i myapp-14-grcic -c thecontainername -- bash -c 'cat > /tmp/archive.tgz' < archive.tgz
```

It's not very handy.

I prefer:

```
$ oc cp /tmp/database.sql mysql:/tmp/
```

Best regards,
Stéphane

**Comment by kargakis** [comment]
Upstream issue: https://github.com/kubernetes/kubernetes/issues/13776

**Comment by juanvallejo** [comment]
Upstream PR: https://github.com/kubernetes/kubernetes/pull/34914
