### ISSUE TITLE
Explain how to use the admission plugin master-config.yaml options

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#10539]
Need to explain about the single chain and enablement.

**Comment by bparees** [comment]
@dak1n1 fyi when 3.3 drops you're going to need to explicitly enable the build override plugin for it to work.

**Comment by bparees** [comment]
@dak1n1 (the override plugin is how we enforce forcePull for builds)

**Comment by deads2k** [comment]
> @dak1n1 (the override plugin is how we enforce forcePull for builds)

Which one?  Was it default on before and default on did something?  I swear I asked about these....

**Comment by bparees** [comment]
@dak1n1 nm, just providing the config for the override plugin(as you should already be doing) will be sufficient to enable it, i misunderstood @deads2k's change.

**Comment by deads2k** [comment]
https://github.com/openshift/openshift-docs/pull/2695
