### ISSUE TITLE
Openshift install by "Method 2: Downloading the Binary" - How to config Proxy to web console works?

### ISSUE THREAD

**Issue by Shyckymn** [openshift/origin#10548]
I've installed Openshift following the instructions of the link below:
https://docs.openshift.org/latest/getting_started/administrators.html

Using the "Method 2: Downloading the Binary" topic.

When I access the web console, everything is OK.
But in the Browse Catalog, I see the message "No images or templates".
So, I suspect that the reason is my company proxy.
So I did a research and find some info related to add the NO_PROXY, HTTP_PROXY, and HTTPS_PROXY environment variables to each host’s /etc/sysconfig/openshift-master or /etc/sysconfig/openshift-node file depending on the type of host.
But in that case I don't have those files.
What can be done to solve this problem?

##### Version
./openshift version
openshift v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7
etcd 2.3.0+git

##### Steps To Reproduce
1. Install openshift using the procedures from the link https://docs.openshift.org/latest/getting_started/administrators.html - "Method 2".

##### Current Result
Openshift Web Console - Browse Catalog = "No images or templates."

##### Expected Result
Images and templates available.

##### Additional Information
./oadm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/openshift.local.config/master/admin.kubeconfig'

WARN:  [DCli1003 from diagnostic ConfigLoading@openshift/origin/pkg/diagnostics/client/config_loading.go:105]
       No client config file was available; however, one exists at
           /openshift.local.config/master/admin.kubeconfig
       which may have been generated automatically by the master.
       If you want to use this config, you should copy it to the
       standard location (/root/.kube/config),
       or you can set the environment variable KUBECONFIG:
           export KUBECONFIG=/openshift.local.config/master/admin.kubeconfig
       If not, obtain a config file and place it in the standard
       location for use by the client and diagnostics.

[Note] No client configuration specified; skipping client and cluster diagnostics.
[Note] Summary of diagnostics execution (version v1.3.0-alpha.3):
[Note] Warnings seen: 1

**Comment by liggitt** [comment]
Starting up does not automatically load example templates. You can do that by following the instructions at https://docs.openshift.org/latest/install_config/imagestreams_templates.html

**Comment by liggitt** [comment]
The templates referenced are located under https://github.com/openshift/origin/tree/master/examples as well, and can be created directly from github urls, like this:

`oc create -n openshift -f https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-centos7.json`
