### ISSUE TITLE
Test flake: timed out trying to delete namespace; no pods remaining

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#10546]
Seen here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/5444

Looks related to namespace deletion with pods remaining, but in this case, it appears to call delete on a namespace multiple times.

````
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:133
Aug 19 14:05:15.574: Couldn't delete ns "extended-test-cli-deployment-m35u7-4doth": Operation cannot be fulfilled on namespaces "extended-test-cli-deployment-m35u7-4doth": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
````

**Comment by kargakis** [comment]
The test passes but the namespace fails to be removed - this is not deployment-related

**Comment by mfojtik** [comment]
@deads2k thoughts?

**Comment by deads2k** [comment]
> The test passes but the namespace fails to be removed - this is not deployment-related

Agree.  @derekwaynecarr probably knows more about it than the rest of us.

**Comment by ncdc** [comment]
More details in #10670. Closing this one.
