### ISSUE TITLE
Unable to access web console using public IPAddress in AWS

### ISSUE THREAD

**Issue by snyamars** [openshift/origin#10554]
Hi,
I Have deployed all-in-one binary version of Origin on AWS RHEL 7 instance. Trying to access web console using the public IP Address on port 8443. The console url redirects to private IP Address which is not accessible from browser. Is there any specific change to be made to the installation configuration? Pls suggest.

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v1.3.0-alpha.2
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Steps To Reproduce
1. Install Origin binary on AWS RHEL instance
2. Launch the server: sudo ./openshift start
3. Enable inbound access in AWS Security group to port 8443 for the specific AWS instance
4. Access the console at https://<<public IP Address>>:8443/console

##### Current Result
url redirected to private IP Address and hence console not accessible
##### Expected Result
web console should provide login console screen

**Comment by liggitt** [comment]
Pass `--public-master=https://<publichost>:8443` to tell openshift what to use as the public hostname

**Comment by snyamars** [comment]
I tried starting the origin script as shown below:
sudo ./openshift start --public-master=https://<public host>:8443

I get the following error:
[server.go:127] skydns: listen udp <<public host>>:53: bind: cannot assign requested address

**Comment by snyamars** [comment]
Error message:
[server.go:127] skydns: listen udp <<public host>>:53: bind: cannot assign requested address

**Comment by snyamars** [comment]
server.go:127] skydns: listen udp <public host>:53: bind: cannot assign requested address

**Comment by mfojtik** [comment]
@snyamars can you try to use the named public hostname as @liggitt suggests?

**Comment by snyamars** [comment]
I have tried running with the public hostname as suggested by @liggitt . Looks like the public hostname is already bound to port 53 (by Skydns) and so OpenShift is throwing port bind error as mentioned in the above error message.

**Comment by liggitt** [comment]
The public hostname has no effect on DNS port binding.

**Comment by snyamars** [comment]
I tried the same again without giving port number and using the AWS public DNS name and the console is accessible. Thanks for the support. I am closing the issue.
