### ISSUE TITLE
Add .editorconfig file to origin repository

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#10553]
GitHub supports `.editorconfig` files [0, 1] which controls behaviour of how tabs are displayed.  Currently, the tab width for display is such that one tab is equivalent to 8 spaces, but arbitrary widths are configurable.

I propose adding an `.editorconfig` file ([the one from origin-web-console](https://github.com/openshift/origin-web-console/blob/master/.editorconfig) seems like a good starting point) to the `origin` repository.

The file is respected by some editors as well (though usually overridable based on developer preferences).  I'd suggest a tab width of either two or four spaces and would be happy to open a PR if others think this would be beneficial.

[0] http://stackoverflow.com/questions/33892410/editorconfig-file-in-github/
[1] https://twitter.com/editorconfig/status/610836234676535296

**Comment by danmcp** [comment]
@openshift/team-project-committers Thoughts?

I guess the advantage the current setting is that it's easier to spot when someone is using spaces vs tabs.

**Comment by mfojtik** [comment]
@danmcp i think `gofmt` and `goimports` are doing good job by formatting the code to avoid tabs/spaces problem. IF somebody create PR that mix those, the `make verify` will shoot it down.

I agree that this can be useful for formatting markdown/asciidoc

**Comment by liggitt** [comment]
The effect on github diff display could be nice, but I'm not sure about the auto-formatting aspect. We definitely wouldn't want it fighting with gofmt. If we do this, I would start with a really light-handed one that most closely matches our current codebase (prefer tabs, don't mess with trailing whitespace or newline)

**Comment by smarterclayton** [comment]
Yeah, gofmt wins always.

**Comment by brenton** [comment]
@tiwillia  I'm assuming this is stale now, would you might sanity checking?

**Comment by tiwillia** [comment]
@brenton I'd say this is stale and safe to close.
