### ISSUE TITLE
Pods don't ever get rescheduled on minion crash/reboot

### ISSUE THREAD

**Issue by akram** [openshift/origin#1056]
Hi all,

I am still doing some tests by crashing minions, I got the following issue:

When a minion crashes the pods that were running on this minion never get rescheduled and remains at "Unknow" state until the minion reboot (and remains on their initial minion even after its reboot is completed)

- Start a clustered installation (works on AWS or VirtualBox)
- Wait for the cluster to be up and running
- Connect to the master
- Deploy some pods
- List the pods (openshift cli get pods) and ensure that they are all in "Running" state
- Shutdown a minion

- List the pods:  (openshift cli get pods) we will see that all the pods that were running on the shut down are in "Unknow" state

Once the minion has rebooted, the pods return to state "Running" but they remain on the same minion (this is acceptable of course, but what is the pods not being rescheduled in the meanwhile)

Can you help in investigating ?

**Comment by smarterclayton** [comment]
This is by design.  Pods aren't rescheduled, instead a node would be marked unhealthy or dead and the pods would be considered dead.  This is an upstream item, although I don't have an issue number tracking it.

**Comment by EricMountain-1A** [comment]
@smarterclayton are you refering to GoogleCloudPlatform/kubernetes#1366?

**Comment by smarterclayton** [comment]
Yes, that is the issue that should cover eviction.  Thanks for finding it.

----- Original Message -----
