### ISSUE TITLE
ClusterResourceQuota object kind not registered

### ISSUE THREAD

**Issue by bostoys** [openshift/origin#10579]
I apologize if this is not the correct place to post this issue. I am trying to set up global resource quotas for my OpenShift cluster so that all projects are created with global cpu, pod, and memory limitations without the need for manual intervention by cluster administrators. I am following the instructions in the Origin docs here:
https://docs.openshift.org/latest/admin_guide/multiproject_quota.html

When I run the 'oc create clusterquota' command as listed there I'm told that the "--project-annotation-selector" flag isn't recognized, and when I try to manually create the resource from the listed code block I'm told that "no kind "ClusterResourceQuota" is registered for version "v1"". Am I going about this the wrong way or using outdated software?

Thanks and sorry if I'm posting in the wrong place.

##### Version
[root@os1]# oc version
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
[root@os1]# openshift version
openshift v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

##### Steps To Reproduce
Run the following command:
oc create clusterquota for-user \
     --project-annotation-selector openshift.io/requester=VALID USERNAME HERE \
     --hard pods=10 \
     --hard secrets=20
Or manually create a resource using 'oc create -f compute_resources.yaml' with the yaml code listed at https://docs.openshift.org/latest/admin_guide/multiproject_quota.html

##### Current Result
Errors stating ClusterResourceQuota is not a valid object kind and project-annotation-select is not a valid flag
##### Expected Result
Global resource quota is created system wide.

**Comment by deads2k** [comment]
clusterquota is new in 1.3, so you'll need up to upgrade both your server and client.

**Comment by bostoys** [comment]
Okay, thank you for the information. Is this the only way to set global resource quotas for my OpenShift cluster?

**Comment by deads2k** [comment]
> Okay, thank you for the information. Is this the only way to set global resource quotas for my OpenShift cluster?

You can create project request template that includes default resourcequota objects to prevent abuse if you like: https://docs.openshift.org/latest/admin_guide/managing_projects.html#modifying-the-template-for-new-projects .

The only multi-project quota with soft limits and overcommit across projects is the new clusterquota objects in 1.3.

**Comment by bostoys** [comment]
Thanks for the information.
