### ISSUE TITLE
DeploymentConfig should report validation error when strategy doesn't match params

### ISSUE THREAD

**Issue by bparees** [openshift/origin#10570]
this:
https://github.com/openshift/cakephp-ex/blob/master/openshift/templates/cakephp-mysql.json#L128-L140

Should be a validation error because the strategy is "rolling" while the params are "recreate".

**Comment by kargakis** [comment]
@smarterclayton didn't you enable this as part of the custom deployer changes you made?

**Comment by mfojtik** [comment]
@kargakis I don't see this in validation

**Comment by kargakis** [comment]
Ok, @smarterclayton had started validating recreate and rolling params only for the custom strategy in https://github.com/openshift/origin/commit/4adfd6a6cf2c7bc63d02469fdf4f9fa34fb5d65f which is different from this. @mfojtik you can go ahead and update validation for this.

**Comment by mfojtik** [comment]
on my list

**Comment by bparees** [comment]
I should note there's some backwards compatibility risk in "fixing" this since today it looks like the parameters are respected either way (eg i can have a recreate strategy and rolling params, but my rolling params' prehook will get executed).

**Comment by mfojtik** [comment]
@bparees was just going to mention that :-) I can be saving my rollingParams for later or just trying to switch to recreate to pass a rolling update error and I don't think we have a good system for giving users "warnings".

**Comment by mfojtik** [comment]
OK, we are not going to add validation because that will break the backward compatibility and cause problems with DCs that are stored this way already BUT we should ignore the params if the strategy does not match.

**Comment by bparees** [comment]
>  BUT we should ignore the params if the strategy does not match.

by params are you including the hooks?  and if so, that also would break people, like the cakephp template (that was just fixed) would have suddenly broken if you'd changed this behavior (assuming i'm correct that today you are running the hooks even if they don't match the strategy).

**Comment by mfojtik** [comment]
@bparees yeah so I don't think we can do something here other than making sure the behavior is right when you have both params defined.

**Comment by smarterclayton** [comment]
Open an issue so that in v2 API we defend against this.
