### ISSUE TITLE
Missing documentation on how to change dns zone 

### ISSUE THREAD

**Issue by Firstyear** [openshift/origin#10586]
By default all deployed containers go to svc.cluster.local. There is no documentation on how to update this value post install (and very hard to find how to set it during the cluster install)

Version irrelevant, documentation issue.

**Comment by liggitt** [comment]
changing the dns suffix is not possible yet. https://github.com/openshift/origin/pull/7446 was opened to allow changing it, but isn't quite done yet

**Comment by Firstyear** [comment]
well, even clarifying where in the installation process this needs to be set would be great, especially if it can't be changed post install.

**Comment by liggitt** [comment]
it's not settable yet.

**Comment by Firstyear** [comment]
Okay, worth leaving this open to guarantee it's documented?

**Comment by liggitt** [comment]
I don't think so, we typically open doc pulls as part of the review process for PRs introducing new features

**Comment by Firstyear** [comment]
Right, thanks for your time,
