### ISSUE TITLE
Deployment config log validation is backwards incompatible and too strict

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#10598]
Clients retrieving logs for a deployment config shouldn't break if they pass the container name of the deployer and the deployer pod no longer exists.  It should still fallback to pulling the first pod and first container that exists.

**Comment by jwforres** [comment]
cc @smarterclayton

**Comment by jwforres** [comment]
This was a breaking change to the deployment log API behavior

**Comment by jwforres** [comment]
possibly related to https://github.com/openshift/origin/pull/10377/files

**Comment by deads2k** [comment]
@jwforres do you have an example body?  We haven't made an intentional validation change since January.

**Comment by deads2k** [comment]
> possibly related to https://github.com/openshift/origin/pull/10377/files

Oh joy, you fix one bug.....

**Comment by jwforres** [comment]
Example request wss://<ip_address>:8443/oapi/v1/namespaces/myproject/deploymentconfigs/php/log?follow=true&tailLines=5000&limitBytes=10485760&container=php-1-deploy&version=1&access_token=<token>

Returns 400

**Comment by mfojtik** [comment]
@jwforres why do you pass the container name? I think the previous behavior was wrong, because the "container" was ignored.

**Comment by mfojtik** [comment]
@jwforres @deads2k I can add check if the pod exists and if not fallback to the first container. Will that restore the behavior?

**Comment by mfojtik** [comment]
@jwforres if you unset the `container` field (which should not be set unless you know from what container you want to get logs from) I believe you will get the old behavior.

**Comment by deads2k** [comment]
@mfojtik adding an enumerated string that indicates which kind of pod your containerName is for (deployer or resultant pod), would allow for disambiguation.

**Comment by mfojtik** [comment]
@deads2k I like that fix, but will it be backward compatible then? What happen if you don't supply the `target` field (or whatever we will call the enumerated string). Will that be an error or we fallback to some default behavior? So

1) I have containerName, but no target -> should I go guess where does that container belong?
2) I have containerName, but no target -> if that container name belonged to deployer which is gone now, should I go search for some other container I will stream logs from? What if DC has multiple containers defined, will I default to first one in that case?

I think, there is a lot of "magic" in here and assumption. I know that we do 2) currently and I think it is wrong because we expose the "container" as API query parameter but we are dropping it in the controller.

I would be in favor of reverting the https://github.com/openshift/origin/pull/10377 for now and rethink this more for 1.3.1.

@jwforres @deads2k WDYT?

**Comment by kargakis** [comment]
> Example request wss://:8443/oapi/v1/namespaces/myproject/deploymentconfigs/php/log?follow=true&tailLines=5000&limitBytes=10485760&container=php-1-deploy&version=1&access_token=
> 
> Returns 400

The container param never worked before #10377, did it? Essentially, this is a breaking change for misuses of the deployment log api.

**Comment by deads2k** [comment]
> The container param never worked before #10377, did it? Essentially, this is a breaking change for misuses of the deployment log api.

Which would be fine if there was a reliable way to use it.  Unfortunately, we don't know which kind of pod their container is for, so even after this change the API can't be used reliably.  If it was broken, then fixed: ok.  But it was broken, and its now also broken, but breaking clients too.

**Comment by mfojtik** [comment]
@jwforres https://github.com/openshift/origin/pull/10609 is reverting the fix, but we need to talk about this for 1.3.1. I like the solution of having something like a `logSource` where you specify the source the logs you want (deployer or application). So I will keep this issue open for discussion, but lower the priority.

**Comment by smarterclayton** [comment]
It may be better to allow multiple container names in order.

**Comment by liggitt** [comment]
you need the container name and pod (either the exact name or something we could unambiguously resolve to a pod), and yes, I could see multiple in order (would need parallel arrays)

`?pod=deployer-pod&container=deployer-container&pod=application-pod&container=application-container`

**Comment by smarterclayton** [comment]
You'd also have to potentially specify which deployment you want -
latest, previous, or by exact number.

In practice, this endpoint is more useful when you can stream unified
logs from all containers and also stitch together the deployer and the
actual running pods.  I'd prefer not to over design the API before we
implement what users *actually want* (show me what is happening inside
this deployment config).

**Comment by deads2k** [comment]
> In practice, this endpoint is more useful when you can stream unified
> logs from all containers and also stitch together the deployer and the
> actual running pods.  I'd prefer not to over design the API before we
> implement what users *actually want* (show me what is happening inside
> this deployment config).

It's like there was a secret listener!

**Comment by liggitt** [comment]
incompatibility was fixed, open a new issue to track adding paramters to request logs from a particular container or deployer pod
