### ISSUE TITLE
A slips about the MongoDB description in releases v1.3.0-alpha.3

### ISSUE THREAD

**Issue by warmchang** [openshift/origin#10607]
A slips about the MongoDB description in releases v1.3.0-alpha.3

##### Version
v1.3.0-alpha.3

##### Steps To Reproduce
1. [The release note, https://github.com/openshift/origin/releases/tag/v1.3.0-alpha.3]
2. [The MongoDD should be MongoDB]

##### Additional Information

> New supported versions for popular languages
> 
> PostgreSQL 9.5, Ruby 2.3, Python 3.5, NodeJS 4, MariaDB 10.1, MongoDD 3.2
> 
> add new SCL version imagestreams #9610
> add nodejs 4 imagestream and bump templates to use latest imagestreams #9823

![2016-08-24_112306](https://cloud.githubusercontent.com/assets/13084624/17917279/5bbf311a-69ed-11e6-8b68-456d62631b2b.png)

**Comment by danmcp** [comment]
Fixed.  Thx!

**Comment by warmchang** [comment]
welcome!
