### ISSUE TITLE
Websocket doesn't upgrade for logs that have no content

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#10601]
The web socket stays in pending and is not upgraded until the pod log has some content. In the web console under Chrome, it will show a "Loading logs..." message and finally timeout after 4 minutes.

![screen shot 2016-08-23 at 3 00 44 pm](https://cloud.githubusercontent.com/assets/1167259/17905803/6efb69e8-6942-11e6-82e0-977d4db9a07b.png)

@liggitt @jwforres

**Comment by liggitt** [comment]
recreated with a busybox pod:

1. run a busybox pod that runs "sleep 30 && echo foo && sleep 3600"
2. immediately after starting, view logs via the web console as soon as it starts
3. the websocket won't upgrade until the initial sleep is over

**Comment by liggitt** [comment]
With a debug proxy, I see the upgrade headers and initial frame get sent immediately from the server, but the web console waits until the first text frame is sent to switch from the "Loading log..." to showing the log

**Comment by liggitt** [comment]
```
Binary	Wed Aug 24 13:06:02 EDT 2016	Wed Aug 24 13:06:02 EDT 2016	
Text	Wed Aug 24 13:06:07 EDT 2016	Wed Aug 24 13:06:07 EDT 2016	Zm9vCg==
Text	Wed Aug 24 13:06:07 EDT 2016	Wed Aug 24 13:06:07 EDT 2016	YmFyCg==
Text	Wed Aug 24 13:06:07 EDT 2016	Wed Aug 24 13:06:07 EDT 2016	YmF6Cg==
Close	Wed Aug 24 13:06:12 EDT 2016	Wed Aug 24 13:06:12 EDT 2016	(1000)
```

The initial "ping" frame sent is a binary frame containing an empty byte array. If I switch it to a text frame, the web console displays the log immediately, but treats the ping frame as a blank line 1

**Comment by liggitt** [comment]
There was also an issue with the node not flushing headers when streaming a log back to the master
