### ISSUE TITLE
Limit pod scaling to a maximum number

### ISSUE THREAD

**Issue by luigizuccarelli** [openshift/origin#10629]
[provide a description of the issue]
When deploying a database (pod) with no replication using persistent volumes and persistent volume claims, I want to  restrict the scaling of the pod to no more than one replica i.e have a feature in the DeploymentConfig that has something like replicasMax : 1

The reason is that I don't want data distributed over various persistent stores causing fragmentation.

##### Version
oc v3.2.1.9-1-g2265530
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
NA

##### Current Result
NA

##### Expected Result
NA

##### Additional Information
I realize this is more of a feature than an issue. 
Is there an existing way to achieve this ?,  if not how would we go about trying to implement this or get it accepted as a proposal

**Comment by danmcp** [comment]
Related to: https://trello.com/c/jH7MiGOg

**Comment by ncdc** [comment]
@luigizuccarelli please add your comments to the Trello card and watch its status. Thanks!
