### ISSUE TITLE
High speed loop generating events about volume mounting.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#10626]
I have been playing with ``oc cluster up`` and what is possible as far as volume mounting. I may have well issued an incorrect command, or the cluster may not allow what I was doing, but the command I ran produce a very high speed loop causing huge amounts of events.

```
rc/hello-2
Error creating: pods "hello-2-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
a few seconds ago
15405 times in the last 2 minutes
```

It probably reached that 15000+ count in 30 seconds or so.

Command was:

```
oc set volume dc/hello --add --name=v1 -t hostPath --path /tmp/pv1
```

I forgot the mount path, but is more complaining about ``hostPath`` as type so never got to missing option..

Is a bit of a worry that so many events were being generated so quickly for what was possible a bogus or incorrect command. Do that multiple times and doubt it would be good.

Image versions:

```
openshift/origin-sti-builder          v1.3.0-alpha.3      c2fa186d844a        2 weeks ago         483.5 MB
openshift/origin-deployer             v1.3.0-alpha.3      d4a68c00e564        2 weeks ago         483.5 MB
openshift/origin-docker-registry      v1.3.0-alpha.3      98e3a96eb8f8        2 weeks ago         348.9 MB
openshift/origin                      v1.3.0-alpha.3      93fd7655df0d        2 weeks ago         483.5 MB
openshift/origin-pod                  v1.3.0-alpha.3      1b4bb3233091        2 weeks ago         1.591 MB

```

**Comment by deads2k** [comment]
I think this was fixed in https://github.com/openshift/origin/pull/10414, which merged after we tagged alpha.3.  Can you update an confirm?

**Comment by deads2k** [comment]
Re-open if it wasn't fixed by the pull I referenced.
