### ISSUE TITLE
Forced to restart browser to connect to OpenShift after oc cluster down/up.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#10624]
Using v1.3.0-alpha.3 and ``oc cluster`` on MacOS X, I am finding that if I do an ``oc cluster down`` and then an ``oc cluster up``, that the Chrome and FireFox web browsers on MacOS X hang on trying to connect to the same instance on the same URL if done straight away. I am having to kill the browsers and restart them, at which point they connect straight away. It looks like the browser is caching something and that is causing problems. I did note that if I only tried some time after the subsequent ``oc cluster up``, that it would work. I don't know how long the minimum time period to wait had to be.

Not that I think it matters as believe I also saw it without, but I usually use the ``--host-config-dir``, ``--host-data-dir`` and ``--use-existing-config`` options.

**Comment by liggitt** [comment]
Might be an issue with the API calls from the web console hitting cert errors, even though the web console thinks it has a valid API token. If you log out of the console and go back through the login flow, are you prompted to reaccept the certs and does that resolve the hang?

**Comment by GrahamDumpleton** [comment]
I cannot get anything to come up, not even the top level page by stripping URL back to root. So it is not possible to log out and back in again. When I kill the browser and start again I immediately get back into the project list without needing to login again.

**Comment by liggitt** [comment]
Do you know if taking the cluster down and bringing it back up assigns a different IP or host to the cluster? What browser are you using? What does `curl -k -v https://<cluster>` show?

**Comment by GrahamDumpleton** [comment]
I am not using a Docker machine instance because on MacOS X they don't work for volume mounting (not an OpenShift problem). I am therefore running in the primary Docker service instance and thus it has the same IP address (of my machine) and port number every time.

Immediately after ``oc cluster down`` and ``oc cluster up`` the curl command shows:

```
$ curl -k -v https://192.168.178.53:8443
* Rebuilt URL to: https://192.168.178.53:8443/
*   Trying 192.168.178.53...
* Connected to 192.168.178.53 (192.168.178.53) port 8443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: 127.0.0.1
* Server certificate: openshift-signer@1472093104
> GET / HTTP/1.1
> Host: 192.168.178.53:8443
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Thu, 25 Aug 2016 04:48:40 GMT
< Content-Length: 203
<
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/controllers",
    "/healthz",
    "/healthz/ping",
    "/healthz/ready",
    "/metrics",
    "/oapi",
    "/oapi/v1",
    "/swaggerapi/"
  ]
* Connection #0 to host 192.168.178.53 left intact
```

**Comment by jim-minter** [comment]
@GrahamDumpleton, I haven't been able to recreate this (F24 host, Chrome and Firefox, libvirt F23 VM, origin tip, so no OSX!), please can you provide more reproducer information so I can have a bit more of a go at it?
- can you confirm this issue still exists for you on tip?
- which page are you on when the browser lockups occur?
- can you ensure your firefox & chrome versions are updated & confirm versions?
- can you confirm the precise oc cluster up options you're using?  Here I tried `oc cluster up --host-config-dir=/tmp/config --host-data-dir=/tmp/data --host-volumes-dir=/tmp/volumes --use-existing-config`
- what do you mean by "running in the primary Docker service instance"?
- is a truss or tcpdump at all illuminating?

Before, I've seen this kind of thing come down to (a) SSL certs changing under the browser's feet, and (b) browser trouble with long-running websocket connections going cold suddenly

Here I've verified with the above oc cluster up invocation that the SSL cert doesn't change, can you confirm the same?  i.e. run `openssl s_client -connect 192.168.178.53:8443 </dev/null | openssl x509 -noout -text` before and after and compare the results

@jwforres do you have any other advice / does this ring any bells with you?

**Comment by jwforres** [comment]
The only issues I've ever seen were cert related.  @GrahamDumpleton were you using the console that is running as part of the master, or running a local dev version of the origin-web-console repo (via grunt serve).   If the console is running as part of the master then refreshing the page should have triggered the cert prompt, if that was the issue.

If the server went down with the console open its going to attempt to re-connect the websockets, but its on a sleep + retry loop limited to 5 retries, so that shouldn't take down the browser.

**Comment by jwforres** [comment]
FWIW I cluster down/up with the console open all the time, I've never seen this hang the browser.

**Comment by GrahamDumpleton** [comment]
I haven't noticed this with versions after alpha.3 at this point. So likely can be closed.

**Comment by jim-minter** [comment]
OK, please reopen if it recurs.
