### ISSUE TITLE
Can't override oc cluster up instance to use password due to hardwired password used at one point.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#10632]
Because ``oc cluster up`` is open to the world, I wanted to explain to people how to properly secure it with accounts and passwords.

That is, using ``--host-config-dir`` option, then go in and edit ``master/master-config.yaml`` to change ``AllowAllPasswordIdentityProvider`` to ``HTPasswdPasswordIdentityProvider`` and add a ``file`` option of ``/var/lib/origin/openshift.local.config/users.htpasswd``.

I then generated user accounts/passwords into the ``users.htpasswd`` file:

```
$ htpasswd -cb users.htpasswd admin admin
Adding password for user admin
$ htpasswd -b users.htpasswd developer awesome
Adding password for user developer
```

When ``oc cluster up`` is then used it fails though as it has a hardwired account/password combination in it of ``developer:developer`` at one point.

```
I0825 19:35:01.520271    1662 round_trippers.go:299] curl -k -v -XGET  -H "X-Csrf-Token: 1" https://192.168.178.53:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client
I0825 19:35:01.521692    1662 round_trippers.go:318] GET https://192.168.178.53:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client 401 Unauthorized in 1 milliseconds
I0825 19:35:01.521705    1662 round_trippers.go:324] Response Headers:
I0825 19:35:01.521710    1662 round_trippers.go:327]     Date: Thu, 25 Aug 2016 09:35:01 GMT
I0825 19:35:01.521714    1662 round_trippers.go:327]     Content-Length: 0
I0825 19:35:01.521718    1662 round_trippers.go:327]     Content-Type: text/plain; charset=utf-8
I0825 19:35:01.521722    1662 round_trippers.go:327]     Www-Authenticate: Basic realm="openshift"
I0825 19:35:01.521784    1662 round_trippers.go:299] curl -k -v -XGET  -H "Authorization: Basic ZGV2ZWxvcGVyOmRldmVsb3Blcg==" -H "X-Csrf-Token: 1" https://192.168.178.53:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client
I0825 19:35:01.524513    1662 round_trippers.go:318] GET https://192.168.178.53:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client 401 Unauthorized in 2 milliseconds
I0825 19:35:01.524528    1662 round_trippers.go:324] Response Headers:
I0825 19:35:01.524533    1662 round_trippers.go:327]     Www-Authenticate: Basic realm="openshift"
I0825 19:35:01.524538    1662 round_trippers.go:327]     Date: Thu, 25 Aug 2016 09:35:01 GMT
I0825 19:35:01.524542    1662 round_trippers.go:327]     Content-Length: 0
I0825 19:35:01.524546    1662 round_trippers.go:327]     Content-Type: text/plain; charset=utf-8
I0825 19:35:01.524567    1662 basicauth.go:51] already handled basic challenge
FAIL
   Error: challenger chose not to retry the request
```

The decoding of ``ZGV2ZWxvcGVyOmRldmVsb3Blcg==`` yields ``developer:developer``.

What is ``oc cluster up`` doing when logging in? Is this due to the check to see if the default project has been created and if it isn't create it?

Is this the only reason it needs to log in as the user? Could it perhaps not fail outright if it can't log in to do that so that a passwd database could be introduced afterwards?

Any better suggestions of how to introduce better security through way of some special option?

Could one use an option at least the first time that allows you to say ``--enable-accounts`` and have it create the ``htpasswd`` file and ``configure master-config.yaml`` so uses it. The initial ``htpasswd`` can still contain the default password so that login first time to create default project would still work, but then on subsequent times, don't complain if can't log in to do that. Can then explain to users how can change the password and add extra accounts.

**Comment by GrahamDumpleton** [comment]
And just to confirm that the changes I am making do work. If set password in ``htpasswd`` file to ``developer`` as is being used, then it will start up, but then you must use that password in web interface and can't just give it any password as was case before. It will also only allow accounts which are in password file. So issue is purely that that password is likely hardwired when trying to log in to create project.

**Comment by marekjelen** [comment]
I like the idea of having the ability to set more complex password. Full account management is nice to have, but most people will use single user anyway.

**Comment by csrwng** [comment]
Proposed solution is to detect whether the PasswordIdentityProvider is set to something other than the default. If it is, then simply we won't log in.

**Comment by csrwng** [comment]
PR forthcoming

**Comment by GrahamDumpleton** [comment]
How about have an option for ``oc cluster up`` which when passed would prompt you for the ``developer`` password and then also setup the htpasswd provider and create the initial file with the passwd for developer just entered. As you have the password the first time can still create the project.

**Comment by marekjelen** [comment]
In case someone do not persist envs between invocations, it would help to be able to pass the password on the cmd line, without prompting.

**Comment by GrahamDumpleton** [comment]
A command line option is one we have separately discussed. As is defaulting to htpasswd with current default passwd, but providing a separate command to set password via command line, or prompting. So this wrapper around htpasswd command that hides the mechanism. So various ways one could do it.

**Comment by csrwng** [comment]
Addressed by https://github.com/openshift/origin/pull/11146

**Comment by csrwng** [comment]
cluster up should no longer try to login when the provider has changed or the user created
