### ISSUE TITLE
Events tab has no pagination support.

### ISSUE THREAD

**Issue by wtrocki** [openshift/origin#10643]
Events section should have paggination. 
Fetching events for big projects can take long time and it often timeouts.  

Currently used endpoint:
`api/v1/namespaces/{project}/events`
##### Version

oc v3.2.0.41
kubernetes v1.2.0-36-g4a3f9c5
##### Steps To Reproduce
1. Trigger multiple events for the project.
2. Open openshift gui
3. Go to events tab - there is no pagination for events. 
   Fetching events takes more than 10 seconds depending on size of the list.
##### Current Result

Opening events tab for pod is always fetching all project events which can be very long depending on project size.
##### Expected Result

Fetching last 10-20 events is enough.

**Comment by liggitt** [comment]
The underlying API doesn't support pagination

**Comment by liggitt** [comment]
there are no current plans for API pagination
