### ISSUE TITLE
If http proxy is specified, during docker push it attempts to route through it.

### ISSUE THREAD

**Issue by Firstyear** [openshift/origin#10657]
When you build with http_proxy for web access specified, after a build openshift attempts to push through the proxy to the registry. Of course, because the registry is internal, this fails as the external proxy has no access to the internal registry. 
##### Version

oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
##### Steps To Reproduce
1. Build openshift with a http proxy
2. build any container
##### Current Result

All builds fail
##### Expected Result

Builds succeed.

**Comment by mfojtik** [comment]
@bparees I think you dealt with proxies when pushing before, right? we should set no_proxy for the internal registry IP address in the build container?

**Comment by bparees** [comment]
@mfojtik for pushing images i don't think the build container matters, it's all docker daemon configuration right?

**Comment by mfojtik** [comment]
@bparees I will try to see if the docker client is sending the proxy vars to daemon which make the daemon reroute the push via proxy server. In any case, we should set the "no_proxy" for the internal services in the build container).

**Comment by bparees** [comment]
@mfojtik not sure what you mean by the "internal services in the build container".  We are just doing a docker push and we don't know if the registry we're pushing to is internal or external w/o a lot more work.  The model has always been that you need to configure your docker daemon to know when it needs to use a proxy and when it doesn't, for pushing.  It's not part of the build logic.

Now, should we consider allowing users to explicitly state they want a proxy used/not used for their particular buildconfig?  perhaps, but that's definitely an RFE (and i'm not even sure we can do it?  do we actually have control from the client side, over what proxies the daemon uses to push an image to a registry?)

**Comment by mfojtik** [comment]
@bparees agree, @Firstyear can you check that your docker daemon is configured with a proxy disabled when pushing images? is the proxy set for the entire system?

@bparees I think users can already do that by setting no proxy env var in build config if they don't want to use the proxy, right?

**Comment by bparees** [comment]
> @bparees I think users can already do that by setting no proxy env var in build config if they don't want to use the proxy, right?

Short answer:  no, because we whitelist the env variables you're allowed to pass into the builder(not assemble) container.

Long answer: if they don't want to use the proxy for what?  Even if we didn't do the whitelisting, we're making a docker api call, so the NO_PROXY env variable wouldn't be respected by our api call unless we explicitly added logic to look for it, no?

**Comment by ioggstream** [comment]
@bparees if there's an internal  docker-registry, just add the IP to no proxy.

 The same goes for 172.30.0.1 (the kubernetes api endpoint used by various xPaaS container)

**Comment by gregswift** [comment]
So, my question is, why isn't the internal docker registry referenced via a DNS entry via dnsmasq? The first time you kick an environment, the docker registry doesn't have a known IP, and so you have to re-configure NO_PROXY everywhere after the docker registry service gets created, but before everything is actually up.  Then if you haven't added it to your NO_PROXY list in your inventory, when you run the openshift upgrade, you have to then re-configure the NO_PROXY again.  Seems like just referencing `docker-registry.default.cluster.local` or similar would make more sense.

**Comment by gregswift** [comment]
Apparently there is some discussion to DNS being put into this in #8849.

**Comment by sanapir** [comment]
knobunc approved this pull request.

Seems reasonable. LGTM

—
