### ISSUE TITLE
oadm diagnostics shows ipv6 issues on oshift 

### ISSUE THREAD

**Issue by Firstyear** [openshift/origin#10656]
WARN:  [DCli2013 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:157]
       See the warnings below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected

```
   Info:  Service account token successfully authenticated to master
   Info:  Service account token was authenticated by the integrated registry.

   [Note] Running diagnostic: PodCheckDns
          Description: Check that DNS within a pod works as expected

   WARN:  [DP2004 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:79]
          Error querying nameserver 2001:44b8::15:
            dial udp: too many colons in address 2001:44b8::15:53
          This may indicate a problem with non-cluster DNS.

   WARN:  [DP2015 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:124]
          Error querying nameserver 2001:44b8::15:
            dial udp: too many colons in address 2001:44b8::15:53
          This may indicate a problem with DNS.

   [Note] Summary of diagnostics execution (version v1.2.1):
   [Note] Warnings seen: 2
```

WARN:  [DClu3004 from diagnostic MasterNode@openshift/origin/pkg/diagnostics/cluster/master_node.go:175]
       Unable to find a node matching the cluster server IP.
       This may indicate the master is not also running a node, and is unable
       to proxy to pods over the Open vSwitch SDN.
##### Version

oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
##### Steps To Reproduce
1. Have ipv6 on your hosts and DNS
##### Current Result

Random failures throughout openshift
##### Expected Result

Openshift supports ipv6

**Comment by knobunc** [comment]
OpenShift does not support IPv6 yet... is the issue that you want it to tolerate IPv6 configuration on the nodes when diagnostics are run?

**Comment by Firstyear** [comment]
Correct. The presence of IPV6, even if not supported, should not cause random errors on my cluster or the utilities.
