### ISSUE TITLE
Origin does not provide support for CloudProviders

### ISSUE THREAD

**Issue by jwhonce** [openshift/origin#1065]
When creating a new NodeController `nil` is provided for the CloudProvider

https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/master.go#L151

**Comment by smarterclayton** [comment]
We should take an env var and include selected cloud providers -can you prep a list of what we would include?  Some of them have lots of dependencies

**Comment by danmcp** [comment]
@jwhonce ^^

**Comment by smarterclayton** [comment]
Fixed - you can setup cloud providers with apiserverArguments
