### ISSUE TITLE
Cleanup older failed deployer pods

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#10669]
We should keep around just the latest failed deployer for a config.

Was suggested somewhere by @smarterclayton 

cc: @mfojtik

**Comment by mfojtik** [comment]
@kargakis terminated pods are not counting against quota so I don't think this is high priority. Also failed deloyers might be useful for debugging (you can get logs from them, but better would be to use centralized logging for logs...)

**Comment by kargakis** [comment]
This issue doesn't have to do with quota, it's for cleaning up, hence the P3 label. Most if not all of the time you care about the latest failure.

**Comment by kargakis** [comment]
Ok, convinced myself that failed deployer pods should be removed once the related replication controllers that failed to deploy, are actually removed. We need to enhance our cleanup policy (https://github.com/openshift/origin/issues/10683) instead of adding more custom logic.

**Comment by liggitt** [comment]
How do you get logs for the failed deployment if the pod is automatically removed?

**Comment by kargakis** [comment]
> How do you get logs for the failed deployment if the pod is automatically removed?

This issue was about removing the deployer pods for all but the latest failed deployment. Each time a new deployment fails, the deployer pod of the previously failed deployment gets deleted.

**Comment by kargakis** [comment]
For more context see https://trello.com/c/uoIAABEj/446-2-r-d-clean-up-older-failed-deployment-pods and https://github.com/openshift/origin/issues/3543. I think implementing #10683 coupled with the fact that we are going to default revisionHistoryLimit at some point, I am inclined to archive that Trello card.
