### ISSUE TITLE
Documentation: SCC page omits how you add SCC to allow nfs to work

### ISSUE THREAD

**Issue by Firstyear** [openshift/origin#10660]
https://docs.openshift.org/latest/install_config/persistent_storage/pod_security_context.html

This is missing a section about how to actually add the new SCC to the project default, so that it can apply when you rebuild / redeploy contains. 

As a result, without this step, the SCC can't be applied, and NFS volumes don't work.

**Comment by Firstyear** [comment]
https://docs.openshift.org/latest/admin_guide/manage_scc.html

Same issue applies here, no discussion of how to add an SCC to a project default.

**Comment by pweil-** [comment]
@Firstyear can you clarify what you are looking for when you say "adding an SCC to a project default"?  Adding an SCC means granting it to a user or group which is covered in https://docs.openshift.org/latest/admin_guide/manage_scc.html#add-an-scc-to-a-user-or-group

**Comment by Firstyear** [comment]
okay. So in the docs for nfs, it describes:

* get the project default allowed to runAs group and user ranges
* Get the pod values for comparison

Then it describes the creation of an SCC to alter runas, supplementary groups etc. 

At this point the docs *stop*. Which is the issue. But the most important part is actually *adding* the SCC to the project.

You can't add the SCC to a pod, because when you re-deploy, well, it's a new pod, so no more SCC. Back to the restricted policy.

There is no doc on how to add the SCC to the project default, to set the runas or supplementary groups. Without this, I can not complete the NFS configuration allowing persistent volume claims to operate. I need the pod to run in a certain ID range and cannot add a new SCC to define this.

**Comment by pweil-** [comment]
https://github.com/openshift/openshift-docs/pull/4636
