### ISSUE TITLE
expose a standalone script to run extended tests against running OS server

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#10672]
We have a bunch of information on how tests are run, and which tests we can/should run built into our jenkins scripts that needs to be put into our test-rpm.  

##### Version
ALL

##### Steps To Reproduce
1.  Run extended tests

##### Current Result
Several failures, b/c some tests are known not to work. 

##### Expected Result
All tests pass on clean clusters.

/cc @sdodson @ncdc @detiber @jayunit100

**Comment by timothysc** [comment]
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1369588

**Comment by timothysc** [comment]
@mfojtik priority is much higher imo.. I'm going to force priority on the BZ.

**Comment by stevekuznetsov** [comment]
Ideally we want to:
 - factor out the current logic for generating the ignore list
 - surface a new script (in /contrib?) that is:
   - standalone (no `source hack/lib/init.sh`)
   - runs all extended tests (only conformance?) against an openshift server that's already running, using the ignore list

**Comment by stevekuznetsov** [comment]
An issue we may run into here is that we don't publish images and RPMs in lockstep, so there's a possibility for some weirdness with tests being run for an RPM release that don't build their own images from that source and instead use the latest published images.

**Comment by stevekuznetsov** [comment]
@timothysc I will also say:

> Expected Result
> All tests pass on clean clusters.

This is nice, but we don't see that in our tests pretty much ever, so I wouldn't hold out for it.

**Comment by timothysc** [comment]
> This is nice, but we don't see that in our tests pretty much ever, so I wouldn't hold out for it. 

@stevekuznetsov 

![image](https://cloud.githubusercontent.com/assets/169553/18143444/a7cd775c-6f87-11e6-83f3-ed3e88cfcf53.png)

**Comment by stevekuznetsov** [comment]
> be the change you want to see in the world

says a man opening an issue, not a PR :)

**Comment by detiber** [comment]
> An issue we may run into here is that we don't publish images and RPMs in lockstep, so there's a possibility for some weirdness with tests being run for an RPM release that don't build their own images from that source and instead use the latest published images.

While this is true, maybe we need to have a way to specify specific tags for images to use for tests, that way we can make sure we are testing the right combinations, especially as we start talking about older enterprise releases.

**Comment by jayunit100** [comment]
how does this intersect with what is currently done for the extended wrappers ? 
```

# Not run by any suite
readonly EXCLUDED_TESTS=(
  "\[Skipped\]"
  "\[Disruptive\]"
  "\[Slow\]"
  "\[Flaky\]"

"\[Feature:Performance\]"
...
```

Those have custom skips etc. in them.  Maybe we just want to externalize that string (or now, maybe we can viper it somehow if viper works properly in openshift) and be able to reference it https://github.com/openshift/origin/blob/master/test/extended/setup.sh#L127

**Comment by stevekuznetsov** [comment]
The point of this issue is to figure out a way to automate the publishing and release of exactly those wrappers so that they can be statically included as one file to the RPM.

**Comment by timothysc** [comment]
On inspection I think we'll likely release a simplified wrapper that re-enables some of the tests that are commented out and there are also 2 distinct use cases we need to account for. 

1. red/green you cluster installation 
2. test-set on live installation (smaller working set).

**Comment by timothysc** [comment]
@brenton if you have your upgrade only list I would like to close this out this week.

**Comment by timothysc** [comment]
I'm bypassing this with semantics on executing the tests vs. cribbing a skip list.  The existing skip list that is being maintained as part of the jenkins instance has made  a number of suppositions and doesn't appear to be using the installer.  

We have a list of known failed conformance tests that are setup against a production cluster and are fixing here: https://github.com/kubernetes/kubernetes/pull/34140 so I'm closing this issue.  

We will need to update the documentation to reflect the new skip ":Variant"
