### ISSUE TITLE
Openshift start should fail if --kubeconfig file does not exist

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#1067]
If user gives a --kubeconfig parameter on openshift start, if the file referenced does not exist, we do not appear to error out.

Tested with latest image on docker hub, will verify again in morning when running from HEAD

/cc @liggitt

**Comment by liggitt** [comment]
Will be fixed upstream in https://github.com/GoogleCloudPlatform/kubernetes/pull/4581
Will be fixed in origin in https://github.com/openshift/origin/pull/1068
