### ISSUE TITLE
Cleanup policy should retain complete deployments

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#10683]
There is a scenario where the latest deployment is successful and all the old deployments that have been retained as part of the cleanup policy are failed. In that case, the user cannot rollback. The controller should be smarter, it should cleanup all but the last failed deployment and make sure that the rest of the deployments that are retained are complete.

cc: @mfojtik @smarterclayton

**Comment by kargakis** [comment]
Seems like Jenkins is doing the same thing with builds.

**Comment by tnozicka** [comment]
I am going to close this as DC features are frozen. We might consider something like this for upstream - feel free to open the issue there.
