### ISSUE TITLE
Confusing error message when using oc cluster up --use-existing-config with a different IP

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#10685]
I tried to use `oc cluster up --use-existing-config` with a configuration generated against a different IP than my current one today, and the result was not obvious:

```
-- Starting OpenShift container ... FAIL
   Error: Docker run error rc=2
   Details:
     Image: openshift/origin:v1.3.0-alpha.3
     Entrypoint: [/bin/bash]
     Command: [-c for name in 192.168.1.103 localhost.localdomain; do ls /var/lib/origin/openshift.local.config/node-$name &> /dev/null && echo $name && break; done]
```

@csrwng suggested using a predictably named directory, which I endorse.

**Comment by stevekuznetsov** [comment]
`oc cluster up` is not really an internal tool

**Comment by csrwng** [comment]
addressed by https://github.com/openshift/origin/pull/13112
