### ISSUE TITLE
DNS for High Availability Routers

### ISSUE THREAD

**Issue by jtconnor** [openshift/origin#10686]
The [routing documentation](https://github.com/openshift/origin/blob/master/docs/routing.md) says to run multiple router pods with a balancing tier (e.g. DNS round-robin) to achieve high availability routing.  I'm trying to figure out how to gracefully handle host failures with this approach.  Suppose that I've deployed multiple router pods with DNS round-robin load balancing and health checks across the router pod hosts.  Then if a host with a router pod fails, the DNS health check to that router will fail and all traffic will be routed to the healthy host and openshift apps will continue to be externally accessible -- yay!  But when a router host fails, if I understand correctly, kubernetes will try to reschedule the router pod onto a new host and an operator will then have to manually update the DNS configuration to add this new router host.  Is there a suggested approach for automating these DNS updates when a router pod is rescheduled onto a new host?

I'm considering automating router DNS updates by creating a router-dns-updater Docker image that repeatedly queries kubernetes for router pod locations and updates DNS (e.g. in AWS route53) when a router pod is scheduled onto a new host.  What do you think?  Would you want to add this router-dns-updater to the openshift repo?

##### Version
```
[centos@ip-172-31-10-18 ~]$ openshift version
openshift v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5
```

**Comment by eparis** [comment]
See https://docs.openshift.com/enterprise/3.0/admin_guide/high_availability.html for how to set up floating IPs so node failure is handled.

**Comment by jtconnor** [comment]
Thanks for your quick response!  I poked around on Google for how people configure floating IPs in AWS and found a more recent version of the docs that says:

"""
At this time of writing, ipfailover is not compatible with cloud infrastructures. In the case of AWS, an Elastic Load Balancer (ELB) can be used to make OpenShift Enterprise highly available, using the AWS console.
"""
https://docs.openshift.com/enterprise/3.2/admin_guide/high_availability.html

Based on that recommendation, my plan is to run an ELB pointing at all the openshift nodes in my cluster (or, as the cluster grows, I may set a node constraint on the router service and only point the ELB at the nodes that can run the router).  Then if router pods are scheduled to a different host, the ELB health checks will automatically notice the new router pods and start sending traffic to them.  Let me know if you have any suggestions for improving this approach; otherwise, feel free to close the issue.  Thanks so much for your help!

**Comment by eparis** [comment]
Sounds like you've got a solid plan! Thanks!
