### ISSUE TITLE
Changing IP when using oc cluster and --host-config-dir.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#10690]
One of the issues with not using ``127.0.0.1`` for the default IP when using ``oc cluster up`` is that if you are on a laptop and move around between networks, you can't use ``--host-config-dir`` and ``--host-data-dir`` to preserve your configuration and application deployment data. This is because trying to start up the cluster again when on a different network and your IP is different, will fail.

This is a real nuisance for any developer is somewhat mobile.

Not sure whether one can easily accomodate changes or whether simply have to always ensure use ``127.0.0.1`` explicitly. Would prefer to see ``127.0.0.1`` as default as more secure, but have had separate issues with ``127.0.0.1`` failing when using ``--host-data-dir`` (https://github.com/openshift/origin/issues/10630), plus also appears not to be local to box anyway (https://github.com/openshift/origin/issues/10628).

Error one sees is below.

```
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.0-alpha.3 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Checking Docker version ... OK
-- Creating host directories ... OK
-- Finding server IP ...
   Using 192.168.203.114 as the server IP
-- Starting OpenShift container ...
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.203.114:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0828 01:08:38.940442   15529 create_dockercfg_secrets.go:119] Dockercfg secret controller initialized, starting.
     W0828 01:08:38.947420   15529 manager.go:146] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
     I0828 01:08:38.956564   15529 fs.go:139] Filesystem partitions: map[/dev/vda2:{mountpoint:/var/lib/docker/aufs major:254 minor:2 fsType:ext4 blockSize:0}]
     I0828 01:08:38.961599   15529 node.go:376] Using iptables Proxier.
     I0828 01:08:38.961709   15529 proxier.go:209] missing br-netfilter module or unset br-nf-call-iptables; proxy may not work as intended
     I0828 01:08:38.961733   15529 node.go:392] Tearing down userspace rules.
     I0828 01:08:38.994460   15529 nodecontroller.go:167] Sending events to api server.
     I0828 01:08:38.999839   15529 replication_controller.go:240] Starting RC Manager
     I0828 01:08:39.000135   15529 horizontal.go:127] Starting HPA Controller
     I0828 01:08:39.000604   15529 controller.go:237] Starting Daemon Sets controller manager

$ curl -k -v https://192.168.203.114:8443/healthz/ready
*   Trying 192.168.203.114...
* Connected to 192.168.203.114 (192.168.203.114) port 8443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: 127.0.0.1
* Server certificate: openshift-signer@1472178985
> GET /healthz/ready HTTP/1.1
> Host: 192.168.203.114:8443
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: no-store
< Date: Sun, 28 Aug 2016 01:08:52 GMT
< Content-Length: 2
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 192.168.203.114 left intact
```

**Comment by csrwng** [comment]
This and #10685 are almost the same issue. However, that other issue was related to the node ip. I'll look into a solution.

**Comment by bparees** [comment]
i think we agreed with @smarterclayton this was not something we'd enable via oc cluster up(it needs underlying product support), right @csrwng ?

**Comment by csrwng** [comment]
Yes, unless we change the underlying use of IPs in the way openshift starts and associates node config with the IP, generates certificates, etc. we can't make 'cluster up' fix this use case.

**Comment by liggitt** [comment]
I think the crux of the issue is that you can't simultaneously preserve config (which treats config as immutable) and update config (to work with the new IP)
