### ISSUE TITLE
Implement 'oc create pvc' to allow volume claim separate to mounting.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#10700]
In the web interface you can request storage (make a claim), separate to then associating that storage (mounting it) to a particular deployment config (application).

In the REST interface, or using resource objects with ``oc create -f``, you need to create a ``PersistentVolumeClaim`` definition independent of where it may be later used.

With the ``oc`` command line, your only option with ``oc set volume`` is either claim and mount storage in one operation, or mount storage from an existing claim.

To provide parity with web interface and REST interface where a claim can be executed as a separate operation, there should be a ``oc create pvc`` command. The only thing this would do is allow you to make a claim for storage of set size and optionally name it. This would allow the claim to be more easily created in advance of it then being used.

It would also make the story around explaining the usage of volumes easier as one could then explain a single scenario for all interfaces, web interface, REST API, resources and command line. That is, that can create claim as one step, and then mount as second step. This is easier to understand than the more complicated behaviour of ``oc set volume`` where claim and mount done in one step, with it differing from two step process of web interface and REST API or resources.

**Comment by ncdc** [comment]
This code will go into Kube, so I'm going to turn this into a Trello card and we'll track progress there.

https://trello.com/c/sH6GuGwr
