### ISSUE TITLE
the tar.gz does not contain the openshift binary,only the apiserver and kubectl

### ISSUE THREAD

**Issue by Jaware** [openshift/origin#10726]
as the title says, the release tar does not contain the openshift command binary,where can i download it ?hope anyone can help me ,thanks

**Comment by Jaware** [comment]
![image](https://cloud.githubusercontent.com/assets/3970304/18126859/b8192c5a-6faf-11e6-95f6-c2bd66f1a73a.png)

**Comment by PI-Victor** [comment]
not sure which .tar.gz you downloaded [the latest one](https://github.com/openshift/origin/releases/download/v1.2.1/openshift-origin-server-v1.2.1-5e723f6-linux-64bit.tar.gz) has all files in it.
@Jaware can you retry the download? 

![screen shot 2016-08-31 at 14 04 45](https://cloud.githubusercontent.com/assets/6294120/18127997/eab2871e-6f83-11e6-9bf6-3fb3f19bda23.png)
![screen shot 2016-08-31 at 14 05 26](https://cloud.githubusercontent.com/assets/6294120/18128017/00d2c734-6f84-11e6-9c68-c1f7bbfd87b3.png)

**Comment by Jaware** [comment]
thanks ,i will try,this is the first time i met up this strange thing ,i have downoaded 1.3,1.2,1.1 versions,the structure is the same,as the picture shows,only containing apiserver and kubectl.ps i  am chinese,out network may be hacked by other people
