### ISSUE TITLE
oc get with --all-namespaces and a golang template produces a parse error

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin#10721]
Trying to evaluate a routes across all namespaces produces an error.  Excluding the flag works, but including it does not:
```
$ oc get routes --template='{{range .items}}{{if eq .spec.host "kibana.10.1.2.2.xip.io"}}{{.metadata.name}}{{end}}{{end}}'
logging-kibana
$ oc get routes --all-namespaces --template='{{range .items}}{{if eq .spec.host "kibana.10.1.2.2.xip.io"}}{{.metadata.name}}{{end}}{{end}}'
error: error parsing template { --all-namespaces{range .items}}{{if eq .spec.host "kibana.10.1.2.2.xip.io"}}{{.metadata.name}}{{end}}{{end}}, template: output:1: unexpected {{end}}
```
the `--all-namespaces` flag is ending up in the template

##### Version
$ oc version
oc v1.3.0-alpha.3+29d152c-dirty
kubernetes v1.3.0+507d3a7
features: Basic-Auth

**Comment by liggitt** [comment]
I can't recreate this... what environment are you running this command in?

**Comment by jcantrill** [comment]
closing....unable to reproduce...long day...
