### ISSUE TITLE
Ship a readme for "oc" client tools

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#10723]
The Origin binaries downloaded from the Releases page include the `README.md` file from the project root, which gives a great summary of OpenShift itself.

However, there are a few problems with it:
- Since it's not focused on the CLI tools, it contains a lot of information which would be useful for system administrators but not developers (for example, disabled features, how to build Origin, etc)
- It is in Markdown format, which is less portable than HTML or plain text (txt)

I propose that we create a "tips and tricks" sort of document to ship with the client tarball, with advice like:
- A basic incantation of `oc cluster up`
- How to install bash completions (`oc completion`)
- How to get other commands, like `oadm` or `kubectl` by creating symlinks
  *\* I suppose there are problems with shipping symlinks in the release tarballs, given the statement here: https://github.com/openshift/origin/issues/5842

I'm suggesting that this new document replace the existing `README.md`, perhaps as both a `README.txt` and `README.html` built from Markdown source.  That said, the existing document is still useful, so perhaps we can ship it alongside the new files under a different name.

**Comment by stevekuznetsov** [comment]
What use cases were you hoping to target with the inclusion of such a document? I'm not sure there are a lot of people downloading the binaries without any clue what to do with them. I'd expect they're following tutorials in our online documentation, maybe we should focus on making that link as obvious as possible?

**Comment by jawnsy** [comment]
@stevekuznetsov It's not that people don't know what to do with the binaries, but just a few tricks to make the experience more closely resemble what you'd get if you installed the client tool via the RPM. I agree it could just be a matter of linking to the appropriate parts of existing docs.

This comes from one of the discussions on our internal mailing list where someone was asking about bash completions, so it's just that people may not realize:

1. You can use `oc completion` to generate bash completions
2. You can symlink the command to get all the other commands you'd expect (although, I don't know if people get used to using the alternative `oc adm` incantation instead - I think we still document it as `oadm` everywhere, right?)

**Comment by stevekuznetsov** [comment]
@adellape is this something Docs is interested in?
