### ISSUE TITLE
Use docker parsing when manipulating dockerfiles

### ISSUE THREAD

**Issue by bparees** [openshift/origin#1073]
currently build/builder/docker.go does manual parsing of the dockerfile for some manipulation.  we should use docker libs instead for better safety.

@smarterclayton fyi.

**Comment by mfojtik** [comment]
@kargakis https://github.com/docker/docker/blob/640e0fc578e5acdaa71216a300396dfa9af8054f/builder/parser/parser.go

**Comment by smarterclayton** [comment]
In general, we also need more test cases and coverage on this area (if we're rewriting Dockerfiles)

----- Original Message -----

**Comment by kargakis** [comment]
Track process here: https://github.com/openshift/origin/pull/1079
