### ISSUE TITLE
error: Unable to construct api.Node object for kubelet: when run openshift start on a openstack vm

### ISSUE THREAD

**Issue by guangxuli** [openshift/origin#10739]
when run **openshift start** command on a vm(cloud provider with openstack), some errors generate:

E0831 23:30:52.490741    3367 factory.go:291] devicemapper filesystem stats will not be reported: unable to find thin_ls binary
I0831 23:30:52.490769    3367 factory.go:295] Registering Docker factory
E0831 23:30:52.490798    3367 manager.go:240] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
I0831 23:30:52.490811    3367 factory.go:54] Registering systemd factory
I0831 23:30:52.491819    3367 factory.go:86] Registering Raw factory
I0831 23:30:52.492832    3367 manager.go:1072] Started watching for new ooms in manager
I0831 23:30:52.520542    3367 oomparser.go:185] oomparser using systemd
I0831 23:30:52.521749    3367 manager.go:281] Starting recovery of all containers
I0831 23:30:52.522528    3367 manager.go:286] Recovery completed
**E0831 23:30:52.951369    3367 kubelet.go:1168] Unable to construct api.Node object for kubelet: can't get ip address of node openshift-node.novalocal: lookup openshift-node.novalocal on 10.30.1.10:53: no such host
E0831 23:30:53.850683    3367 kubelet.go:1168] Unable to construct api.Node object for kubelet: can't get ip address of node openshift-node.novalocal: lookup openshift-node.novalocal on 10.30.1.10:53: no such host
E0831 23:30:55.549677    3367 kubelet.go:1168] Unable to construct api.Node object for kubelet: can't get ip address of node openshift-node.novalocal: lookup openshift-node.novalocal on 10.30.1.10:53: no such host
E0831 23:30:58.848984    3367 kubelet.go:1168] Unable to construct api.Node object for kubelet: can't get ip address of node openshift-node.novalocal: lookup openshift-node.novalocal on 10.30.1.10:53: no such host
E0831 23:31:05.349490    3367 kubelet.go:1168] Unable to construct api.Node object for kubelet: can't get ip address of node openshift-node.novalocal: lookup openshift-node.novalocal on 10.30.1.10:53: no such host**   

I don't know how to handle this error.  Is my local host config not correct?

**Comment by danmcp** [comment]
@scollier @derekwaynecarr FYI

**Comment by derekwaynecarr** [comment]
@pmorie - can you track this Kubelet message down and report back.  It
sounds like this is misconfigured.

**Comment by detiber** [comment]
@guangxuli how was this host installed/configured?

**Comment by guangxuli** [comment]
thanks @detiber this host is allocated by data center member, I just use it, I know the cloud provider is openstack.
I am not sure how was this host installed, but I can provide some configure info. if you need, BTW, what configuration should I provide, network configuration or others? if you need I will provide try my best. thanks.
