### ISSUE TITLE
Use gopass for password input

### ISSUE THREAD

**Issue by fabianofranz** [openshift/origin#10737]
We must be consistent with upstream in https://github.com/kubernetes/kubernetes/pull/31586 and use `github.com/howeyc/gopass` for masked password input.

**Comment by fabianofranz** [comment]
Affected command: `oc login`.

**Comment by liggitt** [comment]
we don't currently echo the password to the terminal... do we need to pull in the dependency?

**Comment by fabianofranz** [comment]
@liggitt `gopass` adds masked input with `*`, I think that's better UX.

**Comment by liggitt** [comment]
It leaks number of characters in the password. `sudo su` doesnt echo `*`

**Comment by liggitt** [comment]
I'm slightly -1 on this
