### ISSUE TITLE
oc delete all doesn't delete configmaps

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#10734]
Running `oc delete all --all` does not clean up the configmaps.

##### Version
oc v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7
openshift v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7

**Comment by fabianofranz** [comment]
Not deleting configmaps was a deliberate choice, [here are](https://github.com/kubernetes/kubernetes/pull/28955#issuecomment-232737113) the rules we try to follow about what must be part of `all`. 

I'll close this for now, we can reopen it if anything changes.

@smarterclayton @deads2k it keeps coming.

**Comment by fabianofranz** [comment]
One possible idea to address the issue that `all` doesn't actually mean "all" would be to warn users about the objects that would potentially fit the filter but wasn't deleted. For example

```
$ oc delete all --all
buildconfig "hello-world" deleted
imagestream "hello-world" deleted
service "hello-world" deleted
route "hello-world" deleted

WARNING: the following resources has not been deleted and must be deleted individually
secret "hello-world"
configmap "hello-world"
```

**Comment by liggitt** [comment]
we wouldn't go fetch all resources just for a warning. I could see maybe see printing what the `all` alias expanded to

**Comment by fabianofranz** [comment]
@liggitt exactly, that would be the issue, we would have to go get the resources to know what was not part of "all".

**Comment by fabianofranz** [comment]
@liggitt still, from a UX experience that would be nice.
