### ISSUE TITLE
Is there a restful api to implement the "oc delete all -l <label>" function?

### ISSUE THREAD

**Issue by warmchang** [openshift/origin#10758]
Hi,

It look like should delete the resources (pod, rc, route, dc ...) one by one. Is it possible to call a restful api to implement the "oc delete all -l <label>" function?

Thanks.

##### Version
openshift v3.2.0.20
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

**Comment by liggitt** [comment]
Expanding `all` to a set of named resources is done client-side.

You can pass a labelSelector to a deletecollection API call like this, rather than listing and deleting one-by-one:
```
DELETE /api/v1/namespaces/<foo>/pods?labelSelector=key%3Dvalue
```

**Comment by warmchang** [comment]
@liggitt Ok, I got it, thanks!

**Comment by stevekuznetsov** [comment]
@warmchang you can find a full specification for our REST API using Swagger (aka OpenAPI Spec) here: https://github.com/openshift/origin/tree/master/api/swagger-spec

**Comment by warmchang** [comment]
@stevekuznetsov thank you! And can be found by "https://10.2.2.2:8443/swaggerapi/oapi/v1". :smile:
