### ISSUE TITLE
Dropping API support in 1.4.0

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#10754]
The time has come to bid farewell to some early mistakes

openshift/kubernetes@c1ddd443b37844c008648e053862912c7c7c0053 - service.spec.portalIP, pod.spec.host
openshift/kubernetes@ddc3d24 - GET on exec
openshift/kubernetes@0319dc3 - GET on portforward
openshift/kubernetes@97782f7 - GET on attach 

More as I go along

**Comment by ncdc** [comment]
I assume we should bump this to 1.5?

**Comment by smarterclayton** [comment]
These are already dropped.  May need release notes (I don't remember)
