### ISSUE TITLE
TestImageStreamImportQuayIO flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#10764]
```
I0901 09:50:55.887537    2822 client.go:335] Retrying request to a v2 Docker registry after encountering error (0 attempts remaining): Get https://quay.io/v2/coreos/etcd/manifests/latest: Get https://quay.io/v2/auth?scope=repository%3Acoreos%2Fetcd%3Apull&service=quay.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I0901 09:50:55.887672    2822 credentials.go:30] asked to provide RefreshToken for https://quay.io/v2/auth
I0901 09:50:55.887696    2822 credentials.go:25] asked to provide Basic credentials for https://quay.io/v2/auth
I0901 09:53:00.987718    2822 credentials.go:30] asked to provide RefreshToken for https://quay.io/v2/auth
I0901 09:53:00.987743    2822 credentials.go:25] asked to provide Basic credentials for https://quay.io/v2/auth
panic: test timed out after 4m0s
```

as seen in:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/5695/consoleFull

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/4906/testReport/junit/github/com_openshift_origin_test_integration%20%20%20/TestImageStreamImportQuayIO/

**Comment by bparees** [comment]
Seems like this test just needs to be enhanced to retry more in the face of possible network issues.  or use a longer timeout.

**Comment by legionus** [comment]
> panic: test timed out after 4m0s

@bparees 4 minutes. Looks like network could be really broken.
Are you sure you want to wait 10 - 15 minutes ?

**Comment by bparees** [comment]
@legionus the timeout i was proposing increasing was the one we hit here:

```
net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

not the 4 minute test timeout.

**Comment by legionus** [comment]
@bparees We can not change client timeout because it is hidden inside the [registry client](https://github.com/openshift/origin/blob/master/vendor/github.com/docker/distribution/registry/client/repository.go#L65-L82). Also a timeout of 1 minute does not seem too small to me especially if we consider that we have 3 repeated attempts.

Do not break the network when testing network interaction is not considered as plan B?
