### ISSUE TITLE
[Proposal] Include beta types in `oc types` (ReplicaSets, PetSets, etc)

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#10771]
`oc types` does not include new resource types, such as ReplicaSets and PetSets
##### Version

oc v1.3.0-alpha.0+d0df369-dirty
kubernetes v1.3.0+507d3a7
features: Basic-Auth
##### Steps To Reproduce
1. `oc types | grep replicasets`
2. `oc types | grep petsets`
3. `oc types | grep deployments`
##### Current Result
1. No description for ReplicaSets
2. No description for PetSets
3. No description for Deployments
##### Expected Result

Descriptions for new resource types

cc @jwforres @fabianofranz

**Comment by kargakis** [comment]
Do we want to spend time enhancing `oc types` or do we want to make `oc explain` work better? Can we decide once and for all about this? I would love to get rid of the former in favor of the later. Or why do we need both?

**Comment by fabianofranz** [comment]
I agree there's an overlap between `explain` and `types`, my problem with it is having two commands for something we could solve in one. 

On the other hand, in `explain` you must already know what you are looking for, while in `types` you get an explanation about *what* you could look for. What about deprecating `types` and make `explain` without arguments to display a general overview of the available resources, similar to `types` today (just dynamic from the api, not hardcoded)? Would need to happen upstream.

**Comment by kargakis** [comment]
> What about deprecating types and make explain without arguments to display a general overview of the available resources, similar to types today (just dynamic from the api, not hardcoded)? Would need to happen upstream.

+1
