### ISSUE TITLE
Error while processing a template due to adding "app"

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#10782]
I have this template: https://raw.githubusercontent.com/gshipley/openshift3mlbparks/master/mlbparks-template-wildfly.json

As can be seen, the deployment has proper selector:
````
            "selector": {
               "deploymentConfig": "${APPLICATION_NAME}-mongodb"
            },
            "template": {
               "metadata": {
                  "name": "${APPLICATION_NAME}-mongodb",
                  "labels": {
                     "deploymentConfig": "${APPLICATION_NAME}-mongodb"
                  }
               },
````

When instantiated via new-app (oc new app -f mlbparks-template.json), I get:

````
               "selector": {
                    "deploymentConfig": "mlbparks"
                },
                "template": {
                    "metadata": {
                        "creationTimestamp": null,
                        "labels": {
                            "app": "mlbparks",
                            "deploymentConfig": "mlbparks"
                        },
```` 

"app": "mlbparks" added to the template labels, but not to the selector, so the deployment fails.

This problem has happened to me with many, many templates, that do not include "app" already, as we have added some logic to add it, as discussed in this other issue (https://github.com/openshift/origin/issues/9314#issuecomment-226233312) with @csrwng 

I'm using 1.3.0-alpha.3

**Comment by csrwng** [comment]
@jorgemoralespou I am not able to reproduce this issue. Having an additional label in the pod should not prevent the selector from working

**Comment by kargakis** [comment]
> "app": "mlbparks" added to the template labels, but not to the selector, so the deployment fails.

Why does it fail? Can you post the output of the failure (deployer logs, oc status, oc get rc -o yaml)? I just run the template via new-app and both configs were successfully deployed.
```
In project My Project (myproject) on server https://10.0.2.15:8443

http://mlbparks-myproject.10.0.2.15.xip.io (svc/mlbparks)
  dc/mlbparks deploys istag/mlbparks:latest <-
    bc/mlbparks source builds https://github.com/jorgemoralespou/openshift3mlbparks.git#master on openshift/wildfly:latest 
    deployment #1 deployed 21 seconds ago - 1 pod

svc/mongodb - 172.30.171.51:27017
  dc/mlbparks-mongodb deploys openshift/mongodb:2.6 
    deployment #1 deployed 6 minutes ago - 1 pod

1 warning identified, use 'oc status -v' to see details.
```

**Comment by jorgemoralespou** [comment]
@csrwng @kargakis You're right. I might have seen this wrongly or in another template and confused until I opened the issue. I've had strange issues during the week with some templates.
I'm closing this, but if I do see it agin, will report better.

**Comment by jorgemoralespou** [comment]
Found the template, was a different mlbparks. My bad.
I have added it into a gist:

````
oc new-app https://gist.githubusercontent.com/jorgemoralespou/5246ccb19bbfeb4ec77b6387f2495e49/raw/a4c0b348304b7c0a48a932cf3e0382ab09d6681a/failing-template
````

Then mlbparks deployment fails, cause it already had a label, and while processing the template label in the template changed but not in the selector.

**Comment by liggitt** [comment]
right, because new-app (currently) imposes/overwrites labels on objects, which means the selector might not end up matching the created objects, if they had their own idea of their app label

**Comment by kargakis** [comment]
Bumping back to p1 since it seems new-app is broken

**Comment by csrwng** [comment]
@bparees has an initial pull for a fix here: https://github.com/openshift/origin/pull/10789

This has been an issue since 3.2 (whenever we rebased and changed the default behavior of labels to overwrite). Do we consider this a blocker for 3.3? @smarterclayton

**Comment by smarterclayton** [comment]
It was an issue in 3.2 or just in 3.3?

**Comment by csrwng** [comment]
@smarterclayton I thought it was in 3.2. It's not. So yes, it looks like a regression in 3.3.

**Comment by smarterclayton** [comment]
If it only affects some templates I'm less worried about it.  Sucks.
But not a blocker I don't think.

**Comment by csrwng** [comment]
The workaround is to specify an alternate set of labels `-l foo=bar` which stops newapp from trying to set its own app label

**Comment by bparees** [comment]
marking p2 based on https://github.com/openshift/origin/issues/10782#issuecomment-244507896
and workaround described in https://github.com/openshift/origin/issues/10782#issuecomment-244510918

**Comment by csrwng** [comment]
@bparees you addressed this ... sending it your way

**Comment by bparees** [comment]
new-app will no longer set the "app" label if the "app" label already exists on any object in the template.
