### ISSUE TITLE
oc cluster up should automatically detect its public hostname when running on EC2

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#10786]
When running on EC2, care must be taken to use appropriate values for `--public-hostname` and `--routing-suffix` since the interface IP address is private.  It would be convenient if `oc cluster up` could do this automatically. Discussed with @csrwng - seems this is worth exploring.
##### Steps To Reproduce
1. Run "oc cluster up" without parameters on an EC2 host
##### Current Result

The resulting server listens on an internal IP address (172.xx) rather than an ec2 Elastic IP (*.amazonaws.com). Certificates are for the internal hostname as well, since that is what is returned by the `hostname` command.
##### Expected Result

The server should listen for connections on its external address, and generate a certificate for that name.
##### Additional Information

There is a "magic address" that can be used to determine the external hostname from a running EC2 instance. However, care must be taken to ensure that this does not slow down `oc cluster up` for machines running outside of EC2 (we don't want to hang or wait for a long timeout).  This is a "best effort" mechanism, and the worst case should be a fallback to the current behaviour (which simply generates a certificate for the wrong host).

References:
- http://serverfault.com/questions/462903/how-to-know-if-a-machine-is-an-ec2-instance
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

**Comment by willm** [comment]
Is there a workaround for this at the moment? trying to get a test install running on ec2

**Comment by jawnsy** [comment]
Hey @willm,

I'm happy that you're trying out `oc cluster up` :)

Here's what I usually do... `oc cluster up --public-hostname=ec2-hostname --routing-suffix=ec2-ip.xip.io` for example: `oc cluster up --public-hostname=ec2-1-2-3-4.compute-1.amazonaws.com --routing-suffix=1.2.3.4.xip.io` (applications will then be accessible at `appname.1.2.3.4.xip.io`)

I'm unsure about the specific handshake error you're seeing, it doesn't seem to be related to this issue - if my suggestion doesn't work, could you please create a new issue with those logs?

cc @csrwng

**Comment by csrwng** [comment]
@willm if you specify a numeric ip as your --public-hostname, we'll also try to use that as the ip to communicate with the master. Because the ec2 instance doesn't have access to its own public ip, you get the error you're seeing. 

Following @jawnsy's suggestion will get you going. Thx @jawnsy

**Comment by willm** [comment]
Thanks @jawnsy and @csrwng I can get openshift running and access the web ui now, however, the routing still doesn't work. my app runs on port 8080 so i ran `curl -vv appname.1.2.3.4.xip.io:8080` after exposing that port to everyone, however the request just times out. When I curl it from the openshift server using the local ip, I can hit the app fine.

**Comment by csrwng** [comment]
@willm you need to use port 80 on the router ... just try curl -vv http://appname.1.2.3.4.xip.io

**Comment by willm** [comment]
Thank you both so much, I've finally got a basic setup working :) that xip.io service is great (although I will need to figure out wildcard dns another day). I might write a blog post explaining how to set a test openshift origin servcer up on AWS and credit you both obviously.
