### ISSUE TITLE
Map openshift resources to ThirdPartyResorces so that standard kubernetes tools can work with them?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#10797]
Right now kubernetes tools can't query/insert/update/delete OpenShift specific resources like BuildConfig or Route

Eg there's no way to add a BC or Route into a Helm chart.

In kubernetes 1.4 it's looking like [ThirdPartyResources](https://github.com/kubernetes/kubernetes/blob/master/docs/design/extending-api.md) are going to be a thing.

To avoid us having to maintain a fork of helm to support openshift resources - then all app developers having to maintain both kubernetes charts and openshift specific charts - it'd be nice to just have a way to define hem charts once with any openshift specific resources as ThirdPartyResources - so that the same chart could be installed into kubernetes or openshift. It's likely that the TPR's will be ignored on non-openshift clusters - but at least the rest of the chart would still be useful.

Then the TPR for a BC would get mirrored to the real BC resource under the covers

**Comment by liggitt** [comment]
the plan is to register actual API groups for openshift resources. ThirdPartyResources cause more problems than they solve, since they lack validation, conversion, etc

**Comment by jstrachan** [comment]
You mean openshift resources would get up streamed into the kubernetes project itself so they'd appear inside kubectl & helm? If so that's cool ;)

**Comment by liggitt** [comment]
The end goal for API groups is for them to be able to be served from different servers and federated

**Comment by jstrachan** [comment]
Ah thanks, you mean this right? https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/api-group.md I'd missed that - thanks for the heads up!

**Comment by liggitt** [comment]
Yes. The efforts to converge origin resources to API groups are tracked in the trello board https://trello.com/b/Xdy5ADyF/kube-origin

Specifically, these cards (though there are lots of related ones that are needed as well)
https://trello.com/c/yboCgT6c
https://trello.com/c/AVPf3yHf
https://trello.com/c/6Z9avEol

**Comment by derkoe** [comment]
Is there any progress on this? Still can't create OpenShift objects (e.g. Route) via Helm.

**Comment by liggitt** [comment]
As of 3.7, all openshift resources can be created via resources under kube api groups. 

> Still can't create OpenShift objects (e.g. Route) via Helm.

Use
```
kind: Route
apiVersion: route.openshift.io/v1
…
```
