### ISSUE TITLE
extended networking tests use `${version}` component images instead of pinning to commit

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#10795]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/ is hitting 3 hour timeouts on every run after Sep 2, 2016 2:07 PM. Nothing obviously related merged to master since the previous successful run at Sep 2, 2016 1:47 PM.

This is causing all test and merge jobs to abort

**Comment by liggitt** [comment]
looks like this may correspond to when the 1.3.0-rc1 tag was created:

```
$ git rev-parse v1.3.0-rc1 | xargs git cat-file -p
object 69cee339b49af7ec7c39dd6099de3263bb5e4bdc
type commit
tag v1.3.0-rc1
tagger Clayton Coleman <ccoleman@redhat.com> 1472839315 -0400

v1.3.0-rc1
...
```

1472839315 == Sep 2, 2016 2:01 PM.

@smarterclayton, I don't see dockerhub images for the v1.3.0-rc1 tag. Won't the tag existing without the images mess up things that build from the repo and expect to use the default `${version}` image format?

**Comment by liggitt** [comment]
confirmed, no pods can start in the network test:
```
extended-test-get-flows-izpo2-j993y   3s         2m          5         flow-checkxkwbn      Pod                   Warning   FailedSync                {kubelet nettest-node-1}          Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "Tag v1.3.0-rc1 not found in repository docker.io/openshift/origin-pod"

extended-test-get-flows-izpo2-j993y   15s       2m        9         flow-checkxkwbn   Pod                 Warning   FailedSync   {kubelet nettest-node-1}   Error syncing pod, skipping: failed to "StartContainer" for "POD" with ImagePullBackOff: "Back-off pulling image \"openshift/origin-pod:v1.3.0-rc1\""
```

**Comment by liggitt** [comment]
the `v1.3.0-rc1` tag was deleted from the origin repo, but I'm still seeing it in the local git repo on newly spawned test instances. not sure if the tag is in the local git repo on devenv ami's or jenkins machines, and how to clear that out. @danmcp, any ideas?

**Comment by liggitt** [comment]
looks like `repo_checkout_bash_command` doesn't clean up obsolete local tags

**Comment by liggitt** [comment]
@smarterclayton removed the `v1.3.0-rc1` tag from the origin repo, I added local tag cleanup to vagrant-openshift (https://github.com/openshift/vagrant-openshift/issues/488) and to the network jenkins build config temporarily (https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/configure)

the networking tests are running again, so lowering severity.

we should re-examine why the dind setup was affected by this when none of the other test jobs were. my guess is that we should be pinning the images format in the master and node configs, instead of using `${version}`

**Comment by marun** [comment]
@liggitt I suspect the problem is that the other ci jobs building images so they are available from the host docker for subsequent tests, but nodes in a dind clusters will start without any images.  What do you think of having the networking job build the images and load them into the dind nodes to avoid downloading them?

**Comment by liggitt** [comment]
there are two problems, one of which is building/loading the images into the dind nodes, the other is fixing the format in the master/node config to use either the specific built commit or `latest` (if `latest` is already pre-populated from the built version)

**Comment by marun** [comment]
@liggitt Pointers on how to set the format when generating the config?

Also, I'm fuzzy on the details, but would it make sense to try to use the openshift registry to try to serve the images to the dind nodes rather than having to manually export/import images directly to the nested docker daemons?
