### ISSUE TITLE
new-project only allows lowercase dns names as project names

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#1080]
```
$ openshift ex new-project MyNewProjectName
F0220 12:01:27.888377   24304 new_project.go:45] project "MyNewProjectName" is invalid: Name: invalid value 'MyNewProjectName': does not conform to lower-cased dns952
```

If we're going to require lowercased dns names for projects, should new-project lowercase and set the original name as a display name if it differs from the lowercased version?

@deads2k

**Comment by liggitt** [comment]
Hmm... if we normalize project names to lowercase in `new-project` to satisfy name validation, we need to be really careful. Namespace is not validated/normalized currently, so the following does weird things:

Fails with invalid project name:
`openshift ex new-project NewProjectName --admin=foo`

Creates project, namespace, and rolebinding in namespace with lowercase name:
`openshift ex new-project newprojectname --admin=foo`

Creates rolebinding in namespace with mixed case name:
`openshift ex policy add-user admin bar -n NewProjectName`

```
$ osc describe policybindings master -n newprojectname
Name:			master
Created:		2015-02-20 12:10:03 -0500 EST
Labels:			<none>
Last Modified:		2015-02-20 12:10:03 -0500 EST
Policy:			master
RoleBinding[admins]:	 
			Role:	admin
			Users:	[foo]
			Groups:	[]

$ osc describe policybindings master -n NewProjectName
Name:			master
Created:		2015-02-20 12:10:12 -0500 EST
Labels:			<none>
Last Modified:		2015-02-20 12:10:12 -0500 EST
Policy:			master
RoleBinding[admin]:	 
			Role:	admin
			Users:	[bar]
			Groups:	[]
```

**Comment by smarterclayton** [comment]
Ugh

**Comment by liggitt** [comment]
@derekwaynecarr do you have an opinion on namespace validation when the API processes normal commands (either requiring the namespace validate as a DNS name, and/or requiring the namespace entity to exist)

**Comment by deads2k** [comment]
To be clear, this isn't new-project. This is validation for creating any project: https://github.com/openshift/origin/blob/master/pkg/project/api/validation/validation.go#L16.  I presume it's done to match the restriction requirements on namespace.

```
F0223 08:14:59.232918   25310 create.go:81] Namespace "BIG" is invalid: metadata.name: invalid value 'BIG': must have at most 253 characters and match regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
```

So we probably want to decide what to do about illegal namespaces on the command line.  Errors?

**Comment by liggitt** [comment]
Let the validation and errors happen server-side. Looks like namespace validation needs to change globally upstream, which will be exciting, I'm sure

**Comment by liggitt** [comment]
The only namespace validation I could see doing client-side is preventing `.` and `..`, since that can mess up the actual URI of the request sent to the server.

**Comment by deads2k** [comment]
Ah, kapi.ValidNamespace, doesn't do what you'd think it should do:  https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/context.go#L77.

**Comment by liggitt** [comment]
@derekwaynecarr was it intentional that project name validation is more strict than namespace name validation? Looks like projects use `IsDNS952Label` and namespaces use `IsDNSSubdomain`, which is less strict (allows leading digit, or internal periods, I think).

**Comment by liggitt** [comment]
A lot of the weird issues around https://github.com/openshift/origin/issues/1080#issuecomment-75277554 and mixed-case namespaces would go away if all our objects used ValidateObjectMeta... that ensures consistency with lower-case namespaces.

**Comment by smarterclayton** [comment]
Yeah, we need to do that soon.  Was hoping we could cut over to generic etcd in one swell foop.

**Comment by derekwaynecarr** [comment]
It should not be more restrictive.  Will review this.

**Comment by liggitt** [comment]
fixed in https://github.com/openshift/origin/pull/1174
