### ISSUE TITLE
oc cluster up broken by logging in as user inside of 'origin' container

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#10809]
It is currently possible to break ``oc cluster up`` when using a config/data cache if you get into the ``origin`` container and log in as the ``developer`` user. There appears to be no obvious way to recover from this and you have to trash the config/data cache directories and start over.

```
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.0-alpha.3 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Checking Docker version ... OK
-- Creating host directories ... OK
-- Finding server IP ...
   Using public hostname IP 127.0.0.1 as the host IP
   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ...
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Installing registry ... FAIL
   Error: error retrieving docker registry service
   Details:
     Last 10 lines of "origin" container log:
     E0906 01:53:36.391926   23922 manager.go:240] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
     I0906 01:53:36.392075   23922 factory.go:54] Registering systemd factory
     I0906 01:53:36.395395   23922 factory.go:86] Registering Raw factory
     I0906 01:53:36.398498   23922 manager.go:1072] Started watching for new ooms in manager
     I0906 01:53:36.424328   23922 oomparser.go:185] oomparser using systemd
     I0906 01:53:36.425244   23922 manager.go:281] Starting recovery of all containers
     I0906 01:53:36.452475   23922 node.go:347] Starting DNS on 192.168.65.2:53
     I0906 01:53:36.452775   23922 log.go:11] skydns: ready for queries on cluster.local. for tcp://192.168.65.2:53 [rcache 0]
     I0906 01:53:36.452858   23922 log.go:11] skydns: ready for queries on cluster.local. for udp://192.168.65.2:53 [rcache 0]
     I0906 01:53:36.457410   23922 manager.go:286] Recovery completed

   Caused By:
     Error: User "developer" cannot get services in project "default"

```

To reproduce this, start ``oc cluster up`` using something like:

```
oc cluster up --public-hostname 127.0.0.1 \
              --host-config-dir $OPENSHIFT_HOST_CONFIG_DIR \
              --host-data-dir $OPENSHIFT_HOST_DATA_DIR \
              --use-existing-config
```

Then get into the ``origin`` container and log in as the ``developer`` user.

```
$ docker exec -it origin bash
[root@moby origin]# oc login -u developer
Authentication required for https://192.168.65.2:8443 (openshift)
Username: developer
Password:
Login successful.

You have one project on this server: "myproject"

Using project "myproject".
```

The reason you may wanted to have done that is if you had granted rights to ``developer`` user to run the ``oc adm prune images`` command.

```
$ oc login -u system:admin
$ oc adm policy add-cluster-role-to-user system:image-pruner developer
$ oc login -u developer
$ oc adm prune images
```

Problem is if you forget to log back out, that you were logged in as the ``developer`` user is cached.

Now stop OpenShift using ``oc cluster down`` and start it up again using the original ``oc cluster up`` command and you get the failure on startup as originally shown.

I am guessing that the solution would be to do an explicit ``oc logout`` as part of the startup sequence, or whatever else might be required to ensure you are running as the correct user. This is necessary because of the state about who was the logged in user being retained in the config/data cache when OpenShift is shutdown and still be active when it is started up again.

If you can tell me what I would need to change in ``master/admin.kubeconfig`` to recover from this would be interesting to know. :-)

**Comment by liggitt** [comment]
@GrahamDumpleton `oc login -u system:admin` would get that file back to its original user

@csrwng if the config already exists, that should probably be run

**Comment by GrahamDumpleton** [comment]
Yes, doing ``oc login -u system:admin`` to revert it back after having logged in as ``developer`` will ensure it doesn't break on startup. Is the startup script able to do ``oc login -u system:admin`` as a first step though to ensure it is correct user before doing anything else?

**Comment by csrwng** [comment]
this should be addressed by https://github.com/openshift/origin/pull/11146

**Comment by csrwng** [comment]
#11146 has merged
