### ISSUE TITLE
Move manifest schema 1/2 end-to-end tests to extended tests 

### ISSUE THREAD

**Issue by miminar** [openshift/origin#10813]
As a follow-up for #10759, it was requested to turn end-to-end tests into extended.

The extended tests shall be run daily and notify appropriate people.

The extended test should be written in go.

See original comment https://github.com/openshift/origin/pull/10759#issuecomment-244773474.

**Comment by liggitt** [comment]
some of the other advanced registry tests should also be moved (thinking of cross-mount and blob auth tests)
