### ISSUE TITLE
Backport deltaFIFO race to 1.3?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#10826]
https://github.com/kubernetes/kubernetes/pull/32125

Could result in incorrect decisions made based on a "sync", which is bad.  We need to triage which controllers we have that depend on List() from a shared informer or DeltaFIFO being consistent and correct in order to decide whether to have it for 1.3.

**Comment by smarterclayton** [comment]
@ncdc @liggitt @deads2k @bparees @knobunc which controllers use DeltaFIFO or use a shared informer and are dependent on a consistent list (i.e. a snapshot list in order to recalculate a state table, an allocator, or decide what to remove)

**Comment by bparees** [comment]
the build pod delete controller and build delete controller use it to keep track of builds or pods that have been deleted so the corresponding pod or build can be deleted/marked appropriately.

**Comment by bparees** [comment]
the build pod delete controller and build delete controller use it to keep track of builds or pods that have been deleted so the corresponding pod or build can be deleted/marked appropriately.

**Comment by deads2k** [comment]
> the build pod delete controller and build delete controller use it to keep track of builds or pods that have been deleted so the corresponding pod or build can be deleted/marked appropriately.

Does order matter for that?

I can't think of an order dependent controller.  Many already process in multiple threads.

**Comment by bparees** [comment]
order of seeing "delete for pod1" vs "delete for pod2"?  no, should not matter.

**Comment by ncdc** [comment]
I'm going to have to defer to the others on this one - I haven't looked at or touched the Origin controllers in ages.

**Comment by knobunc** [comment]
@dcbw and I are investigating the impact on networking.

**Comment by deads2k** [comment]
The changes look reasonable.  We'll need https://github.com/kubernetes/kubernetes/pull/30948 and https://github.com/kubernetes/kubernetes/pull/32125

**Comment by smarterclayton** [comment]
Hrm.  Maybe we can live with it...

**Comment by dcbw** [comment]
Networking is not affected by this change since we don't use DeltaFIFO yet (waiting on that until 3.4).

Services that only care about deletion (like the build controller) shouldn't be affected either, since they only care about deletion, and the DeltaFIFO already discards Sync events when a previous Deleted event is in the queue.

The service controller double-checks the apiserver for the services state, so it doesn't care either, though it would log errors if the Update->Sync race happened.

But other users (like pkg/controller/framework/ and their Informer/SharedInformer) will be affected by the race, and that means a lot of existing code that uses informers.

**Comment by smarterclayton** [comment]
Thanks.   Based on all feedback this is punted from 1.3 and should be
a 1.3.1 candidate.

**Comment by ichekrygin** [comment]
I am hitting this issue in `v1.3.6`:

**Comment by smarterclayton** [comment]
Looks like contrib/ingress vendors the kube libraries and would need to be updated.  Is there an issue for that in contrib already?

**Comment by ichekrygin** [comment]
@smarterclayton I didn't create one, could you pls help me in creating one?

**Comment by smarterclayton** [comment]
Opened https://github.com/kubernetes/contrib/issues/1790

**Comment by ncdc** [comment]
@smarterclayton do you still want this in 1.3.x or can we close and it'll be in 1.4?

**Comment by smarterclayton** [comment]
It's in 1.4, we can live without 1.3.
