### ISSUE TITLE
Use the client namespacers instead of function wrappers for clients

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#10834]
Details: https://github.com/openshift/origin/pull/10816#discussion_r77662630

We should switch from using the methods like:

```go
listReplicationControllerEvents func(rc *kapi.ReplicationController) (*kapi.EventList, error)
getReplicationController func(namespace, name string) (*kapi.ReplicationController, error)
```

to just use the namespacer.

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/7190 tracked the changes for our controllers but it's now fixed.
