### ISSUE TITLE
cluster up: error: cannot connect to the server: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

### ISSUE THREAD

**Issue by nsams** [openshift/origin#10838]
When starting a local cluster builds fail with the above error.

##### Version
$ oc version
oc v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.0.233:8443
openshift v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7

$ docker --version
Docker version 1.12.1, build 23cf638

##### Steps To Reproduce
1. start a new cluster with `cluster up`
2. try to build something
3. build fails, log shows:

    error: cannot connect to the server: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

##### Additional Information
    0907 16:26:09.139904    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:06.244945463 +0000 UTC):
    [14.252µs] [14.252µs] About to convert to expected version
    [40.103µs] [25.851µs] Conversion done
    [186.936µs] [146.833µs] About to store object in database
    [2.893789737s] [2.893602801s] Object stored in database
    [2.893800631s] [10.894µs] Self-link added
    [2.894910765s] [1.110134ms] END
    I0907 16:26:10.154741    8765 reconciler.go:180] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/secret/c704fdfc-7517-11e6-b49f-001999bbb8c5-deployer-token-rsetc" (spec.Name: "deployer-token-rsetc") pod "c704fdfc-7517-11e6-b49f-001999bbb8c5" (UID: "c704fdfc-7517-11e6-b49f-001999bbb8c5")
    I0907 16:26:10.154799    8765 reconciler.go:180] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/secret/c705799d-7517-11e6-b49f-001999bbb8c5-deployer-token-rsetc" (spec.Name: "deployer-token-rsetc") pod "c705799d-7517-11e6-b49f-001999bbb8c5" (UID: "c705799d-7517-11e6-b49f-001999bbb8c5")
    I0907 16:26:10.255132    8765 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/c704fdfc-7517-11e6-b49f-001999bbb8c5-deployer-token-rsetc" (spec.Name: "deployer-token-rsetc") to pod "c704fdfc-7517-11e6-b49f-001999bbb8c5" (UID: "c704fdfc-7517-11e6-b49f-001999bbb8c5"). 
    I0907 16:26:10.255225    8765 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/c705799d-7517-11e6-b49f-001999bbb8c5-deployer-token-rsetc" (spec.Name: "deployer-token-rsetc") to pod "c705799d-7517-11e6-b49f-001999bbb8c5" (UID: "c705799d-7517-11e6-b49f-001999bbb8c5"). 
    I0907 16:26:10.294655    8765 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/c705799d-7517-11e6-b49f-001999bbb8c5-deployer-token-rsetc" (spec.Name: "deployer-token-rsetc") pod "c705799d-7517-11e6-b49f-001999bbb8c5" (UID: "c705799d-7517-11e6-b49f-001999bbb8c5").
    I0907 16:26:10.296326    8765 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/c704fdfc-7517-11e6-b49f-001999bbb8c5-deployer-token-rsetc" (spec.Name: "deployer-token-rsetc") pod "c704fdfc-7517-11e6-b49f-001999bbb8c5" (UID: "c704fdfc-7517-11e6-b49f-001999bbb8c5").
    E0907 16:26:11.007392    8765 handler.go:278] unable to get fs usage from thin pool for device 1717: no cached value for usage of device 1717
    I0907 16:26:11.108463    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:09.14257409 +0000 UTC):
    [22.059µs] [22.059µs] About to convert to expected version
    [41.302µs] [19.243µs] Conversion done
    [212.837µs] [171.535µs] About to store object in database
    [1.965286536s] [1.965073699s] Object stored in database
    [1.965294546s] [8.01µs] Self-link added
    [1.965848954s] [554.408µs] END
    E0907 16:26:11.229455    8765 handler.go:278] unable to get fs usage from thin pool for device 1719: no cached value for usage of device 1719
    E0907 16:26:11.524853    8765 handler.go:278] unable to get fs usage from thin pool for device 1721: no cached value for usage of device 1721
    E0907 16:26:11.867701    8765 handler.go:278] unable to get fs usage from thin pool for device 1723: no cached value for usage of device 1723
    I0907 16:26:14.486766    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:11.110508423 +0000 UTC):
    [25.178µs] [25.178µs] About to convert to expected version
    [50.045µs] [24.867µs] Conversion done
    [209.943µs] [159.898µs] About to store object in database
    [3.374698279s] [3.374488336s] Object stored in database
    [3.374718402s] [20.123µs] Self-link added
    [3.37621735s] [1.498948ms] END
    I0907 16:26:16.927358    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:14.489441612 +0000 UTC):
    [18.768µs] [18.768µs] About to convert to expected version
    [41.372µs] [22.604µs] Conversion done
    [200.76µs] [159.388µs] About to store object in database
    [2.43671311s] [2.43651235s] Object stored in database
    [2.436721631s] [8.521µs] Self-link added
    [2.437873195s] [1.151564ms] END
    I0907 16:26:20.197439    8765 thin_pool_watcher.go:126] reserving metadata snapshot for thin-pool docker-8:17-2553987-pool
    E0907 16:26:20.236812    8765 thin_pool_watcher.go:72] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exit status 127
    output:

    I0907 16:26:21.499664    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:16.929684218 +0000 UTC):
    [19.948µs] [19.948µs] About to convert to expected version
    [44.402µs] [24.454µs] Conversion done
    [216.394µs] [171.992µs] About to store object in database
    [4.568139649s] [4.567923255s] Object stored in database
    [4.568149565s] [9.916µs] Self-link added
    [4.569940135s] [1.79057ms] END
    E0907 16:26:21.723168    8765 handler.go:278] unable to get fs usage from thin pool for device 1715: no cached value for usage of device 1715
    I0907 16:26:25.070102    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:21.502979006 +0000 UTC):
    [19.13µs] [19.13µs] About to convert to expected version
    [41.842µs] [22.712µs] Conversion done
    [209.031µs] [167.189µs] About to store object in database
    [3.565420281s] [3.56521125s] Object stored in database
    [3.565428509s] [8.228µs] Self-link added
    [3.56708158s] [1.653071ms] END
    I0907 16:26:28.369297    8765 server.go:2161] http: TLS handshake error from 192.168.0.233:49734: EOF
    I0907 16:26:28.369449    8765 server.go:2161] http: TLS handshake error from 192.168.0.233:49736: EOF
    I0907 16:26:28.392767    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:25.072799088 +0000 UTC):
    [18.37µs] [18.37µs] About to convert to expected version
    [39.948µs] [21.578µs] Conversion done
    [186.57µs] [146.622µs] About to store object in database
    [3.318599211s] [3.318412641s] Object stored in database
    [3.318606778s] [7.567µs] Self-link added
    [3.31992986s] [1.323082ms] END
    I0907 16:26:29.653291    8765 server.go:2161] http: TLS handshake error from 192.168.0.233:49744: EOF
    I0907 16:26:29.731445    8765 server.go:2161] http: TLS handshake error from 192.168.0.233:49748: EOF
    I0907 16:26:30.721537    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:28.396152036 +0000 UTC):
    [25.791µs] [25.791µs] About to convert to expected version
    [60.29µs] [34.499µs] Conversion done
    [237.549µs] [177.259µs] About to store object in database
    [2.324133707s] [2.323896158s] Object stored in database
    [2.324141423s] [7.716µs] Self-link added
    [2.325353475s] [1.212052ms] END
    I0907 16:26:31.969778    8765 server.go:2161] http: TLS handshake error from 192.168.0.233:49754: EOF
    I0907 16:26:32.990400    8765 server.go:2161] http: TLS handshake error from 192.168.0.233:49760: EOF
    I0907 16:26:32.990670    8765 server.go:2161] http: TLS handshake error from 192.168.0.233:49764: EOF
    I0907 16:26:32.991630    8765 server.go:2161] http: TLS handshake error from 192.168.0.233:49766: EOF
    I0907 16:26:32.995279    8765 server.go:2161] http: TLS handshake error from 192.168.0.233:49768: EOF
    I0907 16:26:32.996543    8765 server.go:2161] http: TLS handshake error from 192.168.0.233:49762: EOF
    I0907 16:26:33.517578    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:30.723155599 +0000 UTC):
    [19.655µs] [19.655µs] About to convert to expected version
    [35.763µs] [16.108µs] Conversion done
    [157.124µs] [121.361µs] About to store object in database
    [2.793576552s] [2.793419428s] Object stored in database
    [2.793584465s] [7.913µs] Self-link added
    [2.794389416s] [804.951µs] END
    I0907 16:26:34.470842    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:33.523929095 +0000 UTC):
    [20.342µs] [20.342µs] About to convert to expected version
    [46.33µs] [25.988µs] Conversion done
    [195.503µs] [149.173µs] About to store object in database
    [946.340303ms] [946.1448ms] Object stored in database
    [946.349127ms] [8.824µs] Self-link added
    [946.867624ms] [518.497µs] END
    I0907 16:26:34.617918    8765 server.go:2161] http: multiple response.WriteHeader calls
    I0907 16:26:35.257212    8765 thin_pool_watcher.go:126] reserving metadata snapshot for thin-pool docker-8:17-2553987-pool
    E0907 16:26:35.290503    8765 thin_pool_watcher.go:72] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exit status 127
    output:

    I0907 16:26:37.385883    8765 trace.go:61] Trace "Create /oapi/v1/namespaces/openshift/imagestreamimports" (started 2016-09-07 16:26:34.472586746 +0000 UTC):
    [25.177µs] [25.177µs] About to convert to expected version
    [57.484µs] [32.307µs] Conversion done
    [238.358µs] [180.874µs] About to store object in database
    [2.911690516s] [2.911452158s] Object stored in database
    [2.91169944s] [8.924µs] Self-link added
    [2.913250393s] [1.550953ms] END
    E0907 16:26:40.801174    8765 handler.go:278] unable to get fs usage from thin pool for device 1715: no cached value for usage of device 1715
    I0907 16:26:50.303618    8765 thin_pool_watcher.go:126] reserving metadata snapshot for thin-pool docker-8:17-2553987-pool
    E0907 16:26:50.342083    8765 thin_pool_watcher.go:72] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exit status 127
    output:

    I0907 16:26:52.317802    8765 factory.go:206] Replication controller "myproject/" has been deleted
    I0907 16:26:52.332217    8765 factory.go:206] Replication controller "myproject/" has been deleted
    I0907 16:26:52.338310    8765 reconciler.go:180] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path/e24f8435-7517-11e6-b49f-001999bbb8c5-docker-socket" (spec.Name: "docker-socket") pod "e24f8435-7517-11e6-b49f-001999bbb8c5" (UID: "e24f8435-7517-11e6-b49f-001999bbb8c5")
    I0907 16:26:52.338348    8765 reconciler.go:180] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/secret/e24f8435-7517-11e6-b49f-001999bbb8c5-builder-dockercfg-q1rkt-push" (spec.Name: "builder-dockercfg-q1rkt-push") pod "e24f8435-7517-11e6-b49f-001999bbb8c5" (UID: "e24f8435-7517-11e6-b49f-001999bbb8c5")
    I0907 16:26:52.338372    8765 reconciler.go:180] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/secret/e24f8435-7517-11e6-b49f-001999bbb8c5-builder-token-mo6ms" (spec.Name: "builder-token-mo6ms") pod "e24f8435-7517-11e6-b49f-001999bbb8c5" (UID: "e24f8435-7517-11e6-b49f-001999bbb8c5")
    I0907 16:26:52.438584    8765 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/host-path/e24f8435-7517-11e6-b49f-001999bbb8c5-docker-socket" (spec.Name: "docker-socket") to pod "e24f8435-7517-11e6-b49f-001999bbb8c5" (UID: "e24f8435-7517-11e6-b49f-001999bbb8c5"). 
    I0907 16:26:52.438728    8765 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/e24f8435-7517-11e6-b49f-001999bbb8c5-builder-dockercfg-q1rkt-push" (spec.Name: "builder-dockercfg-q1rkt-push") to pod "e24f8435-7517-11e6-b49f-001999bbb8c5" (UID: "e24f8435-7517-11e6-b49f-001999bbb8c5"). 
    I0907 16:26:52.438766    8765 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path/e24f8435-7517-11e6-b49f-001999bbb8c5-docker-socket" (spec.Name: "docker-socket") pod "e24f8435-7517-11e6-b49f-001999bbb8c5" (UID: "e24f8435-7517-11e6-b49f-001999bbb8c5").
    I0907 16:26:52.438873    8765 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/e24f8435-7517-11e6-b49f-001999bbb8c5-builder-token-mo6ms" (spec.Name: "builder-token-mo6ms") to pod "e24f8435-7517-11e6-b49f-001999bbb8c5" (UID: "e24f8435-7517-11e6-b49f-001999bbb8c5"). 
    I0907 16:26:52.491844    8765 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/e24f8435-7517-11e6-b49f-001999bbb8c5-builder-token-mo6ms" (spec.Name: "builder-token-mo6ms") pod "e24f8435-7517-11e6-b49f-001999bbb8c5" (UID: "e24f8435-7517-11e6-b49f-001999bbb8c5").
    I0907 16:26:52.501130    8765 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/e24f8435-7517-11e6-b49f-001999bbb8c5-builder-dockercfg-q1rkt-push" (spec.Name: "builder-dockercfg-q1rkt-push") pod "e24f8435-7517-11e6-b49f-001999bbb8c5" (UID: "e24f8435-7517-11e6-b49f-001999bbb8c5").
    E0907 16:26:53.094773    8765 handler.go:278] unable to get fs usage from thin pool for device 1725: no cached value for usage of device 1725
    E0907 16:26:53.543482    8765 handler.go:278] unable to get fs usage from thin pool for device 1727: no cached value for usage of device 1727
    I0907 16:26:54.465709    8765 factory.go:206] Replication controller "myproject/" has been deleted
    E0907 16:26:54.493857    8765 handler.go:278] unable to get fs usage from thin pool for device 1715: no cached value for usage of device 1715
    I0907 16:26:55.471060    8765 factory.go:206] Replication controller "myproject/" has been deleted
    I0907 16:27:05.364937    8765 thin_pool_watcher.go:126] reserving metadata snapshot for thin-pool docker-8:17-2553987-pool
    E0907 16:27:05.404674    8765 thin_pool_watcher.go:72] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exit status 127
    output:

    E0907 16:27:14.173821    8765 handler.go:278] unable to get fs usage from thin pool for device 1715: no cached value for usage of device 1715
    I0907 16:27:20.423833    8765 thin_pool_watcher.go:126] reserving metadata snapshot for thin-pool docker-8:17-2553987-pool
    E0907 16:27:20.457492    8765 thin_pool_watcher.go:72] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exit status 127
    output:

**Comment by csrwng** [comment]
This has likely been fixed by https://github.com/openshift/origin/pull/10571
Can you try with an 'oc' binary built from master? your version of 'oc' wouldn't have the fix.

**Comment by nsams** [comment]
Yes, works with master version, thanks!
