### ISSUE TITLE
Replace 'openshift.io/encoded-deployment-config' with 'kubernetes.io/created-by' annotation in deployments

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#10848]
[DeploymentEncodedConfigAnnotation](https://github.com/openshift/origin/blob/31f2273690a6b67f3d3dd477f25ab0d365505bf7/pkg/deploy/api/types.go#L222) should be deprecated in favor of [CreatedBy](https://github.com/kubernetes/kubernetes/blob/4ddfc4849a999559725a1c5a8ba477128eeb6cbc/pkg/api/helpers.go#L436)

cc: @mfojtik @smarterclayton

**Comment by liggitt** [comment]
Is it important to know anything about the deployment config at the point when the deployment was created? If so, we still need the encoded data, since the deployment config could change or be deleted and the information would be lost

**Comment by kargakis** [comment]
> Is it important to know anything about the deployment config at the point when the deployment was created? If so, we still need the encoded data, since the deployment config could change or be deleted and the information would be lost

Wait, isn't created-by supposed to store encoded data?

**Comment by kargakis** [comment]
Or do we need to follow a specific process in order to add created-by annotations? All I was thinking was that the deploymentconfig controller would serialize dcs into `created-by` annotations instead of the one we use now.

**Comment by kargakis** [comment]
We now have owner refs. Also, I think we can stop using the encoded annotation but that may be a breaking change, depending on how naughty our customers are.

**Comment by liggitt** [comment]
Isn't the encoding what lets us react properly to repeated changes to the deployment config object?

**Comment by kargakis** [comment]
It's not strictly needed: https://github.com/openshift/origin/issues/11522
