### ISSUE TITLE
Inconsistent behaviour when creating template: components (rc or template or pod) are not always created

### ISSUE THREAD

**Issue by akram** [openshift/origin#1084]
Hi,

I am working with the master version and since a few days, we got inconsistent behaviour when trying to rebuild our test environment with template creation:

We've made test with the following versions:
openshift v0.3.1-123-g4d53fef
kubernetes v0.10.0-503-gc977a45

as well as:
openshift v0.3.1-123-g4d53fef-dirty

So, when using the following template: https://gist.github.com/anonymous/faa63e3be957295a7502
if we do:
```
$ osc create -f my-template.json
registry-template
$ osc get template
NAME                DESCRIPTION                        PARAMETERS          OBJECTS
registry-template   Template definition for registry   0 (all set)         1
$ osc get pods
POD                                     IP                  CONTAINER(S)               IMAGE(S)             HOST                          LABELS                                                                                                         STATUS
registry-replication-controller-cu9i8                       etcd                       coreos/etcd:v0.4.6   172.16.50.134/172.16.50.134   name=registryPod,template=registry-template                                                                    Pending
$ osc get rc
CONTROLLER          CONTAINER(S)        IMAGE(S)            SELECTOR            REPLICAS
$
```
So, in this case, when using osc create the template and the pods gets created, and the replication controller does not
if I do:
```
$ osc process -f my-template.json  | osc create -f -
registry-replication-controller
$ osc get pods
POD                                     IP                  CONTAINER(S)               IMAGE(S)                           HOST                          registry-replication-controller-mcyff                       etcd                       coreos/etcd:v0.4.6                 172.16.50.134/172.16.50.134   name=registryPod,template=registry-template                                                                    Pending
$ osc get templates
NAME                DESCRIPTION         PARAMETERS          OBJECTS
$ osc get rc
CONTROLLER CONTAINER(S) IMAGE(S) SELECTOR REPLICAS
registry-replication-controller etcd coreos/etcd:v0.4.6 name=registryPod,template=registry-template 1
$
```
And in this case, when processing the template and creating it, the pod and the replication controller gets created but not the template.

And in a third case, in another cluster, we've got the rc and the template create, but no pod.

**Comment by smarterclayton** [comment]
That label selector doesn't look valid - labels don't allow mixed case right now.

**Comment by akram** [comment]
Thanks
Should the parser raise an error I'm that case ?

**Comment by akram** [comment]
I've changed my test case, removing the mixed cases labels, and I still get the same behaviour

**Comment by akram** [comment]
@smarterclayton thanks for tagging it. I confirm you that template creation does not work anymore, even by returning to lower case only for labels

**Comment by akram** [comment]
@smarterclayton according to our discussion, it looks like that at some point we used a buggy behaviour of the template creation that were doing creation of the pods even on template creation.

We do agree that ```osc create file.json``` on a template file only creates the template
Where, ```osc process file.json | osc create -f -```process the template and hence create the pods
