### ISSUE TITLE
Keep getting default page even though application was successfully deployed

### ISSUE THREAD

**Issue by srdjanristic** [openshift/origin#10844]
I keep getting the default view where it says: "Welcome to your JBossEWS (Apache/Tomcat) application on OpenShift" even though I committed and pushed my code (Java Spring application) successfully. Everything went fine, when I pushed the code build was successful, and servers restarted successfully, but when I tryed to access my application on nameoftheapp.rhcloud.com I got the default page. My application creates war file with name ROOT so I guess my Java application should be available at the nameoftheapp.rhcloud.com destination. If anyone could help me out and tell me what I did wrong, or what I missed, I would really appreciate?

**Comment by danmcp** [comment]
What version of OpenShift are you using?

**Comment by bparees** [comment]
closing due to lack of information, please reopen if you can supply the information requested.
