### ISSUE TITLE
Editing routes doesn't cleanup properly the config

### ISSUE THREAD

**Issue by spinolacastro** [openshift/origin#10853]
This happens when we create a route exposing the service A and edit it to point to service B. A.K.A AB tests
@knobunc 

##### Version
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. Create app A and B: 
`oc new-app https://github.com/spinolacastro/teste#a --name app-a`
`oc new-app https://github.com/spinolacastro/teste#b --name app-b`
2. Expose the route to service A:
`oc expose svc/app-a --name abtest`
At this point,  the traffic is correctly forwarded to service A.
3. Edit the route to expose service B:
`oc patch routes/abtest -p '{"spec":{"to":{"name": "app-b"}}}'`

##### Current Result
The router should foward traffic to the new enpoint
##### Expected Result
The traffic is being balanced between services

Bug 1374772

**Comment by tracyrankin** [comment]
FYI - @danmcp @brenton @tdawson.  Spoke with @knobunc about this.  Its not a regression, as it is an issue in 3.2.  We agreed that this is going to be fixed in 3.3.1, not 3.3.

**Comment by brenton** [comment]
Thanks for the heads up!

**Comment by rajatchopra** [comment]
Closing this issue with fix gone with #10855. Please re-open if anything else remains.
