### ISSUE TITLE
project wide node-selector is immutable

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#10858]
In an earlier version, I do remember being able to edit the project wide node-selector, however now that doesn't seem to be allowed. Docs suggest editing this field should be possible.

`metadata.annotations[openshift.io/node-selector]: Invalid value: "type=secondary": field is immutable, try updating the namespace`

##### Version
openshift v1.3.0-rc1
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. oc new-project test
2. oc edit project test

##### Current Result

`metadata.annotations[openshift.io/node-selector]: Invalid value: "type=secondary": field is immutable, try updating the namespace`

##### Additional Information
oc adm new-project test --node-selector='type=secondary' seems to be the only way to add this selector now

**Comment by liggitt** [comment]
That annotation was never editable via the `project` resource, only the `namespace` resource.
