### ISSUE TITLE
oc cluster up: flag for "interactive" or "prompt" mode

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#10875]
`oc cluster up` tries to detect or guess reasonable default values when flags are not passed in, and providing a stable command-line interface makes options scriptable.  However, for new users, it may make sense to provide an interactive mode (similar to `atomic-openshift-installer`) that shows users the default or detected values and allows them to be modified before executing.

**Current Result**

When running `oc cluster up` without parameters, default values are automatically detected where possible.  However, if any values are wrong (for example, on EC2, the default hostname will usually be the `.internal` address) then the user will need to `oc cluster down`, add the flag, and `oc cluster up` again.

**Expected Result**

It would be nice to have an `oc cluster up --interactive` mode, where users are prompted about each value before attempting to start the cluster.  Reasonable defaults should still be supplied (and shown to users).

Further related enhancements could include:
- A confirmation of all the options just prior to running, with the option to "go back" and correct previous answers (loop through all the questions again, this time with previously-supplied values)
- A message showing the equivalent command line, so the user can save it somewhere

**Additional Information**
- A readline library may be needed, for example: https://github.com/chzyer/readline - this could add some weight to the `oc` command

**Comment by jawnsy** [comment]
@csrwng What do you think of this proposal?

**Comment by csrwng** [comment]
I think it's not a bad idea. We'd need to have a way to save your responses somewhere so you can repeat cluster up with the options you selected.

So far we haven't had much traction with other interactive type of commands (like an interactive version of new-app). @smarterclayton what do you think?

**Comment by smarterclayton** [comment]
How about just create a script that has those parameters?  The design goal for oc cluster up is to make users successful by default, and be as simple and easy to use as possible.  A user repeatedly running a cluster up every day is not that use case, and if it can be done simply outside of the tool, why do we need to do it in the tool?  

If we can cleanly articulate why doing it in the tool makes it succeed at that design goal that'd help to weigh this.

For each of the things that we get "wrong" on startup (like the .internal thing), can we not get them right?  There has to be some bound on the amount of detection we add - oc cluster up is *not* the ansible install, and shouldn't try to be.

**Comment by jawnsy** [comment]
> How about just create a script that has those parameters?

Right, for repeatedly starting/stopping a cluster, scripting works. An interactive mode is most useful for people running the command the first time, as the other options are to: (a) review all the command-line options; or (b) run the command, figure out something is wrong, then add the parameter (`oc cluster up`, `oc cluster down`, then `oc cluster up` again). Not a huge problem, but it's a [paper cut bug](https://en.wikipedia.org/wiki/Paper_cut_bug).

> For each of the things that we get "wrong" on startup (like the .internal thing), can we not get them right?

Yeah, there are related bugs (https://github.com/openshift/origin/issues/10786 https://github.com/openshift/origin/issues/10874) to fix this behaviour, but autodetection is never going to be perfect for all possible environments.

> oc cluster up is not the ansible install, and shouldn't try to be.

Agreed, but that isn't to say that what's good for the Ansible installer wouldn't be good for `oc cluster up` too. The `oc cluster up` command doesn't (and isn't intended to) cover all the use cases that a full productionized Ansible install would.

I'm curious if @detiber can share thoughts around why the `atomic-openshift-installer` has a guided/wizard-like experience, then we can think about whether the same experience may be useful for `oc cluster up`.

**Comment by smarterclayton** [comment]
This is a scoping problem.  There is infinite complexity in environments - our goal is not to solve that, it's to do 20% of the work and get 80% of the outcome.  If it's not easy to detect, valuable to a significant fraction of use cases, and cheap, we shouldn't be doing it.

**Comment by smarterclayton** [comment]
Also, we are not going to have two installer experiences - we have one, and that's ansible.  So anything that *can* be done with ansible should be done there, and if the problem is that it's too hard to run ansible, we should fix that *in* oc cluster up so that you can go into the easy path.  Duplicating Ansible is not what we are going to do - eventually oc cluster up *might* be replaced by ansible if we can get a consistent dev experience, but it's unlikely in the near term.

**Comment by jawnsy** [comment]
@smarterclayton We seem to be talking past each other, maybe we should set up a call to discuss. I agree that `oc cluster up` should be as "automagic" as possible, and that we don't want to duplicate Ansible. I certainly did not mean to imply otherwise.

The intent of this proposal is just to make `oc cluster up` even better at its intended use case, which is (as I understand it) getting new users up and running with OpenShift as quickly as possible, so they can play around and see the value of it. The _new user experience_ needs to be as frictionless as possible, and if an "interactive mode" helps with that (and remains to be seen whether it would - which is why I'd like @detiber 's thoughts, as someone that built a similar experience for the installer), then I think it's worth exploring.

**Comment by detiber** [comment]
@jawnsy The challenge is that providing the flexibility you are talking about tends to be death by a 1000 paper cuts and requires quite a bit of work to build and maintain. We don't do nearly as good of a job as we can do with the official installer for that experience and having two dedicated efforts for that (both oc cluster up and ansible-based install) would be painful. 

That said, there is work going on to incorporate the ansible-based installation down into the developer tooling, which could easily be the basis for extending `oc cluster` in a way that could run a containerized guided installer at some point down the line.

**Comment by smarterclayton** [comment]
In fact, I would welcome the following:

1. A containerized Ansible + openshift-Ansible source that is ready
for environment / inventory injection (and maybe preprimed for a
default setup)
2. A simple shim to oc cluster up --on=aws that launches that
containerized image with minimal security params against an AWS
account

That's a much better investment in complexity.

**Comment by detiber** [comment]
@smarterclayton added it as a stretch goal for the following card: https://trello.com/c/ReXkAKzQ
