### ISSUE TITLE
oc cluster up: Does the command support docker running in Swarm Mode?

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#10876]
With docker 1.12 (now available in Fedora Rawhide), there is built-in capability to run the engine in Swarm Mode, which is designed to provide rudimentary orchestration services transparently to clients (by supporting the same API calls as Docker Engine).

We should test that `oc cluster up` works correctly when the docker engine is part of a swarm, or otherwise warn/notify the user that the command is not supported in this case.

I'm not very knowledgeable about Swarm yet, but trying it locally seems to work fine. I created 2x Fedora rawhide machines, installed docker on both, used `docker swarm init` and `docker swarm join`. `oc cluster up` runs OpenShift on the local machine (I'm using the default, so `DOCKER_HOST` points to the docker socket).

**Comment by jawnsy** [comment]
After playing with this for a little while, it seems that `docker run` will always schedule instances on the local machine, and that Swarm Mode requires explicitly creating a service. I remember in the early days of Swarm, it was said that Swarm would create a server that supported the full Docker API, meaning that you could "docker run" on that Swarm port instead - I'm unclear from reading the docs if this is still the recommended mode of operation.

I tried to use `docker -H tcp://<manager_host>:<swarm port>` but was seeing TLS errors, so I guess it's not meant to be used this way (or I'm doing something wrong)

**Comment by csrwng** [comment]
cluster up does not work with Docker in Swarm mode and we're not planning support for it.

**Comment by aCandidMind** [comment]
That's a pity! We'd love to use Docker Swarm mode or Mesos (that's our company standard) on OpenShift. One of our biggest customers is now using OpenShift and we'd like to avoid switching to Kubernetes.
