### ISSUE TITLE
Error: build error: timeout while waiting for remote repository ...

### ISSUE THREAD

**Issue by mahsa-frj** [openshift/origin#10870]
Hi everybody, I used the ansible for installing openshift, but when I want to build any app, I get the below error:
for example:
 
    I0910 11:10:25.728583       1 source.go:197] Downloading "https://github.com/bparees/openshift- jee-sample.git" ...
    I0910 11:10:41.728778       1 cleanup.go:23] Removing temporary directory /tmp/s2i-build554974579
    I0910 11:10:41.728800       1 fs.go:156] Removing directory '/tmp/s2i-build554974579'
    F0910 11:10:41.729053 1 builder.go:204] Error: build error: timeout while waiting for remote repository  "https://github.com/bparees/openshift-jee-sample.git"

##### Version
oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5

thanks for your help.

**Comment by bparees** [comment]
Sounds likely to be a networking issue.  Can you deployed the jenkins template(https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-ephemeral-template.json) and use oc rsh to shell into the jenkins pod, and see if you are able to git clone manually from there?

**Comment by bparees** [comment]
closing due to lack of information, please reopen if you can supply the debug information requested.
