### ISSUE TITLE
the same name user from different identity provides can not login problem

### ISSUE THREAD

**Issue by vanloswang** [openshift/origin#10884]
[provide a description of the issue]
I firstly set auth by HTPasswdPasswordIdentityProvider in origin 1.2 and add a user named admin. After a few days, I change the identity provides to LDAPPasswordIdentityProvider and create a user with the same name admin. But I cannot login into the web console by user admin from ldap server

The log info from /var/log/messages is as following:
```bash
login.go:162] Error authenticating "admin" with provider "my_ldap_provider": user "admin" cannot be claimed by identity "my_ldap_provider:uid=admin,ou=People,dc=vanlos,dc=com" because it is already mapped to [my_htpasswd_provider:admin]
```

##### Version
origin 1.2 latest

##### Steps To Reproduce
1. set auth by HTPasswdPasswordIdentityProvider and add a user named admin
2. login web console by user admin(success)
3. change the identity provides to LDAPPasswordIdentityProvider and create a user with the same name admin
4. login web console by user admin(failed with notice 'could not create user admin')

##### Current Result
The user named admin from ldap server after change identity provides from HTPasswdPasswordIdentityProvider to LDAPPasswordIdentityProvider .

##### Expected Result
login success

**Comment by liggitt** [comment]
If you want to allow that, set the mappingMethod on the identity providers to "add", rather than "claim", and the identities will be added to existing users

**Comment by vanloswang** [comment]
@liggitt Thanks, it work ok for me now and I can change between the two identity providers.
