### ISSUE TITLE
zookeeper example fails to start

### ISSUE THREAD

**Issue by ghyde** [openshift/origin#10886]
When I try to deploy the zookeeper example in an OpenShift 3.2 cluster (3 masters, 2 infra nodes, 4 nodes) or inside the CDK (v2.1), the zookeeper pods fail to start (see [Error Log](#error-log)).

The problem results from when OpenShift mounts the volumeMounts listed in `template.json`. Since OpenShift is mounting an empty volume at `/opt/zookeeper/conf`, the existing config files are no longer accessible. Thus, config-and-run.sh returns "No such file or directory".

##### Version
oc v3.2.0.44
kubernetes v1.2.0-36-g4a3f9c5
Docker version 1.9.1, build ab77bde/1.9.1

##### Steps To Reproduce
1. Log into an OpenShift 3.2 environment
2. `cd origin/examples/zookeeper`
3. `oc process -f template.json | oc create -f -`
4. Wait for pods to fail to run.

##### Error Log<a name=error-log></a>

zookeeper pods fail to start, returning the following error:

```
$ oc logs zookeeper-1
/opt/zookeeper/bin/config-and-run.sh: line 7: /opt/zookeeper/conf/zoo-template.cfg: No such file or directory
JMX enabled by default
Using config: /opt/zookeeper/bin/../conf/zoo.cfg
grep: /opt/zookeeper/bin/../conf/zoo.cfg: No such file or directory
mkdir: cannot create directory '': No such file or directory
log4j:WARN No appenders could be found for logger (org.apache.zookeeper.server.quorum.QuorumPeerConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Invalid config, exiting abnormally
```

**Comment by ghyde** [comment]
When will the [Docker Hub image](https://hub.docker.com/r/openshift/zookeeper-346-fedora20/) be updated?

**Comment by bparees** [comment]
@ghyde rebuilt and pushed just now, thanks for the reminder.
