### ISSUE TITLE
cluster up: add localhost:9000 as a default redirect URL for assets in the web console

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#10885]
After this change:
https://github.com/openshift/origin/pull/10819
the web console can no longer be run on a local de environment (localhost:9000) with a cluster up server without first making a change to the config. 

We should add a default redirectURL of localhost:9000 to the config when starting the cluster so it remains useful for development.

**Comment by jwforres** [comment]
@fabianofranz @juanvallejo can one of you take a look at this

**Comment by jwforres** [comment]
see https://github.com/openshift/origin/pull/10819#discussion_r78373970 specifically
