### ISSUE TITLE
Get Logs returns SSL forbidden 

### ISSUE THREAD

**Issue by stobias123** [openshift/origin#10882]
After deploying a new node to my openshift cluster, logs are unable to be returned in the GUI or via `oc logs` command.

##### Version
oc v1.2.1

##### Steps To Reproduce
1. Deploy openshift via [advanced install](https://docs.openshift.org/latest/install_config/install/advanced_install.html ) method<br>
**Note -** Deployment uses HTTP and HTTPS Proxies, docker registry internal IP manually added to `NOPROXY` line in `/etc/sysconfig/docker`.
2. Add a node using `playbooks/byo/openshift-node/scaleup.yml`
3. Re-add registry IP to `NOPROXY` line in `/etc/sysconfig/docker`.
4. Restart docker service.

##### Current Result
```
[user@ose-master ~]$ oc logs gs-perl-test-01-2-build
Error from server: Get https://ose-node2.company.com:10250/containerLogs/gstest-01/gs-perl-test-01-2-build/sti-build: Tunnel or SSL Forbidden
```
##### Expected Result
```
[user@ose-master ~]$ oc logs build/ruby-king-2
I0912 22:27:10.701001       1 builder.go:57] Master version "v1.2.1", Builder version "v1.2.1"
I0912 22:27:10.702310       1 builder.go:145] Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:92233720368547, CPUShares:2, CPUPeriod:100000, CPUQuota:-1, MemorySwap:92233720368547}
I0912 22:27:10.702891       1 sti.go:169] Using HTTP proxy http://PROXY:80 and HTTPS proxy http://PROXY:80 for script download
ETC...
```
##### Additional information
Curl returns a similar failure.
```
[user@ose-master ~]$ curl https://ose-node2.company.com:10250/containerLogs/gstest-01/gs-perl-test-01-2-build/sti-build --insecure
Forbidden (user=system:anonymous, verb=proxy, namespace=, resource=nodes)
```

**Comment by liggitt** [comment]
what is in the HTTP_PROXY, HTTPS_PROXY, and NO_PROXY envvars on the master? It looks like the master might be trying to go through the proxy to reach the new node.

**Comment by stobias123** [comment]
@liggitt There is a proxy set in both the HTTP and HTTPS proxy variables. Both nodes are in the NO_PROXY variable per the ansible playbook. 

It's worth noting that if I run the above command on ose-node2 against localhost it returns the same error. 
```
[user@ose-node2 ~]$ curl https://localhost:10250/containerLogs/gstest-01/gs-perl-test-01-2-build/sti-build --insecure
Forbidden (user=system:anonymous, verb=proxy, namespace=, resource=nodes)

**Comment by liggitt** [comment]
`Forbidden (user=system:anonymous, verb=proxy, namespace=, resource=nodes)` is an error the node produces, and is expected (the kubelet does not allow anonymous access)

`Tunnel or SSL Forbidden` is not an error message that exists within our product, so I'm guessing it is coming from an external proxy.

**Comment by stobias123** [comment]
After further investigation, I found that I could not log into the master from the node by running `oc login`. I was getting a cert error.

I re-ran the full installation (rather than just use `scaleup.yml`) with the `openshift_certificates_redeploy_ca=true` flag set, and the issue was resolved.

**Comment by tremble** [comment]
I think we may also be hitting this.  The above comments have given me the appropriate clues though.

It looks like the scaleup playbook isn't updating /etc/origin/master/master-config.yaml to include the new nodes in the kubernetesMasterConfig section.

**Comment by tremble** [comment]
Correction, there's (at least) 4 places that need upating:

- /etc/origin/master/master-config.yaml
- /etc/sysconfig/atomic-openshift-master
- /etc/sysconfig/atomic-openshift-master-api
- /etc/sysconfig/atomic-openshift-master-controllers

**Comment by tremble** [comment]
And another (on all nodes?):
- /etc/sysconfig/docker
