### ISSUE TITLE
post-rebase: rsync port forward should accept a ready channel?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#10908]
1.4 rebase introduced port forward accepting a ready channel - we may want to use it in rsync.

@ncdc @csrwng

**Comment by ncdc** [comment]
cc @derekwaynecarr and @hodovska (who did the upstream port forward changes)

**Comment by jim-minter** [comment]
PR submitted.  I don't *think* I missed the point of the issue, but I think we were in fact already synchronising appropriately on the ready channel.  The upstream change appears simply to expose the pre-existing channel as an argument to portforward.New() to neaten the API.
