### ISSUE TITLE
Don't pollute Jenkins logs with "Publish artifacts to S3" messages

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#10907]
When I open the console log (for example: https://ci.openshift.redhat.com/jenkins/job/origin_extended_image_tests/549/consoleFull) of the build in Jenkins I see a lot of messages like this:

```
Publish artifacts to S3 Bucket bucket=aos-ci/jenkinsorigin, file=audit.log region=us-east-1, will be uploaded from slave=false managed=true , server encryption false
```

As developer I don't see any interesting information and each time I have to scroll them up. In the report before, for example, these messages are ~65% of all the log (6860 lines from 9725).

I'm suggesting to not print them to the log.

**Comment by dobbymoodge** [comment]
https://github.com/jenkinsci/s3-plugin/pull/94
