### ISSUE TITLE
Make it easier to develop against `oc cluster up`

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#10900]
Right now I'm using a special script the @csrwng gave me to develop against `oc cluster up`, ie, get my changes to show up without rebuilding an image.  We should make these scripts official or add another official way to develop against `oc cluster up`, for it is the king of all local clusters.

**Comment by stevekuznetsov** [comment]
This is a dupe of an issue I'll dig up tomorrow... Notably I remember @rcarvalho having some implementation that was used by people to do this.

**Comment by csrwng** [comment]
I really like the approach of having a way to bind mount the binary and not having to inject the binary in images or rebuilding images. Either of those methods is too slow imho.

**Comment by mfojtik** [comment]
i'm with @pmorie here, it would be nice to have `oc cluster up` automatically pickup the binaries I built during the development process.

**Comment by mfojtik** [comment]
additionally, if we go that path, we will need a docs (HACKING.md?) that describes how you can develop origin itself.

**Comment by csrwng** [comment]
Created a trello card for this.
https://trello.com/c/2U18YOhD/1141-allow-running-cluster-up-with-locally-built-openshift-binaries

Closing the issue.

**Comment by jorgemoralespou** [comment]
@csrwng I would think this is too specific to openshift engineering and conflicts with other answers we've had before.

**Comment by csrwng** [comment]
Yeah, at least with the Trello card we can have the discussion. There's no reason to have an issue open for it though.
