### ISSUE TITLE
post-rebase: RESTOptionsGetter and StorageFactory need to be aligned

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#10910]
We probably don't have to pass RESTOptionsGetter into each etcd (David and I agree) - we just want to pass RESTOptions, and then have the checker in ApplyOptions() be factored to do the checks without creating the storage.  

We also need to factor out the duplication of BuildDefaultStorageFactory for `pkg/cmd/server/kubernetes/master_config.go` with upstream.

TODO:
- [ ] ~~switch to upstream `BuildDefaultStorageFactory`~~
- [ ] ~~use upstream `RESTStorageProvider`~~
- [ ] ~~build storage using upstream `StorageFactory`~~
- [x] add tests for storage location (https://github.com/openshift/origin/pull/12656)
- [x] clean storage configuration - prereq for 1.6 rebase (https://github.com/openshift/origin/pull/12541)
- [x] fix sdn object storage location (https://github.com/openshift/origin/pull/13124)
- [x] align with the new storage configuration from upstream (should happen during 1.6 rebase)
- [x] add upstream `ObjectFuncName` defaulting which was done in #12541 (this will be cherry-picked into 1.6), tracked in https://github.com/openshift/origin/issues/13182
- [x] add upstream tests for storage location like #12656, also tracked in https://github.com/openshift/origin/issues/13182

**Comment by timothysc** [comment]
@soltysh labeled as P2, is this a deliverable for 3.4?

**Comment by soltysh** [comment]
@timothysc I'm currently working on this, I'd like to have it for 3.4, definitely, but it's hard to tell. I do my best.

**Comment by timothysc** [comment]
@pweil- my favorite short/mid term approach for handling https://bugzilla.redhat.com/show_bug.cgi?id=1378180 is to enable resource sharding , similar to what we did upstream.

**Comment by soltysh** [comment]
Arh... I wasn't able to finish this one, it'll have to wait for the next release :/

**Comment by danmcp** [comment]
@soltysh @mfojtik How big/risky of an item is this?  It sounds bad enough that we should attempt to get it in still if at all possible.

**Comment by soltysh** [comment]
This is a major change to align the storage layer with upstream. I don't feel strongly confident to finish it now. I'd prefer to wait for 1.5, personally.

**Comment by smarterclayton** [comment]
Agreed.  You can split Kube / Origin probably, but not origin.

**Comment by timothysc** [comment]
Even with https://github.com/openshift/origin/pull/11925, I still think it is a priority to have this for 1.5.  I just want to make certain we don't punt this out again.

**Comment by mfojtik** [comment]
@enj was looking into `ApplyOptions` recently in kube

**Comment by soltysh** [comment]
@enj copied our solution into upstream. What @timothysc is saying we should fix this in origin. Yes I'd like to have this in, right after the rebase. It's pretty high on my todo list.

**Comment by enj** [comment]
https://github.com/kubernetes/kubernetes/pull/37770 is merged.

**Comment by soltysh** [comment]
@timothysc I'm aligning this partially to what k8s has, but since @enj changes will land with k8s 1.6 https://github.com/openshift/origin/pull/12541 is just preparing for that. Unless there's something specific you want to be addressed for 1.5, lemme know.

**Comment by soltysh** [comment]
Since https://github.com/openshift/origin/pull/12541 is waiting for https://github.com/openshift/origin/pull/12656 to land first, I doubt we can make it for 1.5 this late. I'm moving milestone to 1.6 for this.

**Comment by soltysh** [comment]
@enj I've updated the TODO list in the first comment, mind taking a look if everything is covered there?

**Comment by enj** [comment]
@soltysh I added a task to port the etcd storage path test.  Otherwise list looks good.

**Comment by liggitt** [comment]
is this done?

**Comment by enj** [comment]
@soltysh I am not really sure what `align with the new storage configuration from upstream (should happen during 1.6 rebase)` means.

**Comment by soltysh** [comment]
@enj that was the part that I've already put inside the code and the rebase had to un-comment it, which it did. So I'm guessing with this one in we can close this.

**Comment by soltysh** [comment]
@enj if you think there's still something that should be handled feel free to re-open this.
