### ISSUE TITLE
IPv6 only websocket connection is not stable.

### ISSUE THREAD

**Issue by MariasStory** [openshift/origin#10934]
[provide a description of the issue]

I have IPv6 only connection and have sporadic problems with websocket connection to the server.

Some of the packages are not transferred and the connection is broken after being open for some minutes. Sporadic behavior.
##### Version

Openshift portal
##### Steps To Reproduce
1. Create a simple websocket server in node.js.
2. Send few kb of information to the server from IPv6 only network.
##### Current Result

The information is not delivered.
##### Expected Result

Expect a stable websocket connection as it is from IPv4 subnet.
##### Additional Information

Random failures throughout openshift for ipv6 is also reported in #10656

**Comment by knobunc** [comment]
Can you provide more details please?  OpenShift does not support IPv6 yet...

**Comment by MariasStory** [comment]
Hi @knobunc,
Sorry for the delay in answer. It seems that the problem is in socket.io.
The problem exists on another hosts as well.

The issue is reported in https://github.com/socketio/socket.io/issues/2686

I'll follow the problem and report results.

**Comment by knobunc** [comment]
Ok, thanks!  I'm going to close the issue here, but please add comments if appropriate.

**Comment by MariasStory** [comment]
Hi @knobunc,

Unfortunately, after testing I come to conclusion that there is a problem with Openshift. While using IPv6 only connection I cannot use critical tools needed to operate the cite. I cannot transfer files bigger ~4k through git, ssh, websocket, post requests.
I didn't have such problems using IPv4 from the same system with the same configuration.

I consider this incident high priority because I cannot continue developing using Openshift service.

Please reopen this case again.

I appreciate your help in solving this problem.

**Comment by knobunc** [comment]
Please clarify where IPv6 is being used?  OpenShift does not support IPv6, so if the service is on OpenShift... I'm surprised anything works.

**Comment by MariasStory** [comment]
Hi @knobunc,
It seems that the problem is related to Ubuntu 16.04 (Maybe linux in general). It does not work with some data transfer. In particular it effects communication with Openshift and I cannot use any practical way of sending information more than ~4k.
The same transfer on Windows 10 works.
It also appears that another services are effected. On another hand there are cases where the data transfer work just find. Especially, with a direct connection.
At the moment I have a filling that it is some kind of combination of IPv6 only connection on Ubuntu 16.04 and the way Openshift handles connections.
I will follow with details when I find additional information.

**Comment by Alok123456** [comment]
Hey, i am getting issues with the firefox version 50.0 as i am unable to establish a connection with the websocket when i try to run my Graphene-ui app in firefox. It gives me these errors:
![screenshot from 2016-11-28 15-29-08](https://cloud.githubusercontent.com/assets/20416373/20664469/5ef164fe-b581-11e6-9d93-53b5fbe9f99e.png)
as mentioned in this screen-shot.

**Comment by MariasStory** [comment]
I have the answer:
Decrease MTU to 1200 and all will work.

The long answer is:
IPv6 can use a bigger package size then IPv4. Somewhere on the way to the server there is an appliance that does the translation of the IPv6 packages to IPv4. During this translation, bigger packages are split. Normally it could work, but in reality, some/older appliances drop connection.

This problem is not limited to Openshift.

PS: Would be very nice to have the IPv6 protocol supported.

**Comment by knobunc** [comment]
Thanks for the update.

You can track IPv6 features in OpenShift with https://trello.com/c/eFarF7cq/85-ipv6-is-the-future,  but it's going to be a while before we get it fully supported.  There is work going on in Kubernetes too that is not tracked on that board unless we are involved with it directly.

**Comment by Alok123456** [comment]
Hey, thanks for the solution @MariasStory  but i don't have IPv6 supported in my network. So, just decreasing the MTU to 1200 will work ?
