### ISSUE TITLE
Seeing thin_ls errors from v1.3.0

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#10940]
@ncdc @derekwaynecarr what does this mean?

```
E0916 02:07:46.850102    4248 thin_pool_watcher.go:72] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exit status 127
output:

I0
```

**Comment by smarterclayton** [comment]
What I'm also seeing is

```
E0916 02:18:10.798310   14670 kubelet.go:2684] Failed cleaning pods: [remove /var/lib/origin/openshift.local.volumes/pods/83da9053-7bb1-11e6-887e-080027242396/volumes/kubernetes.io~secret/default-token-eg709: device or resource busy, remove /var/lib/origin/openshift.local.volumes/pods/863fa999-7bb1-11e6-887e-080027242396/volumes/kubernetes.io~secret/default-token-eg709: device or resource busy, remove /var/lib/origin/openshift.local.volumes/pods/e543e536-7adf-11e6-a55c-080027242396/volumes/kubernetes.io~secret/deployer-token-zskfz: device or resource busy, remove /var/lib/origin/openshift.local.volumes/pods/e544ee69-7adf-11e6-a55c-080027242396/volumes/kubernetes.io~secret/deployer-token-zskfz: device or resource busy]
```

over and over.

**Comment by ncdc** [comment]
@smarterclayton not sure if you were running at log level 5, but if you were, did you see `reserving metadata snapshot for thin-pool` along with either `error reserving metadata for thin-pool` or `reserved metadata snapshot for thin-pool`?

Can you paste the output of `docker info`?

The `device or resource busy` errors are not likely to be related to whatever is going on here, I wouldn't think.

**Comment by danni** [comment]
I'm not sure if this is related, but I'm seeing issues where I'm not getting OutOfDisk errors on a node when the thin-pool fills up.

**Comment by ncdc** [comment]
@danni do you have the thin_ls binary on your system?

**Comment by danni** [comment]
Yes. It's Atomic Host 7.

**Comment by ncdc** [comment]
@danni sorry, I was misremembering how we calculate OutOfDisk. We use thin_ls to check the storage used in the copy-on-write filesystems for each container. We use dmsetup to check for the thin pool capacity. Please open a separate issue about the thin pool filling up and not getting OutOfDisk. Thanks!

**Comment by lukegb** [comment]
thin_ls doesn't seem to be present inside `origin-node`:

```
[root@kube3 ~]# docker exec -it origin-node /bin/bash
[root@kube3 origin]# which thin_ls
/usr/bin/which: no thin_ls in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
[root@kube3 origin]# yum whatprovides '*bin/thin_ls'
<...>
device-mapper-persistent-data-0.6.2-1.el7_2.x86_64 : Device-mapper Persistent Data Tools
Repo        : updates
Matched from:
Filename    : /usr/sbin/thin_ls
<...>
[root@kube3 origin]# rpm -q device-mapper-persistent-data
package device-mapper-persistent-data is not installed
```

**Comment by lukegb** [comment]
cAdvisor finds `thin_ls` under `/rootfs`, but the container is lacking the .so to make it work, it seems:
```
[root@node3 origin]# /rootfs/usr/sbin/thin_ls 
/rootfs/usr/sbin/thin_ls: error while loading shared libraries: libaio.so.1: cannot open shared object file: No such file or directory
```

**Comment by marekjelen** [comment]
Hi, I have just deployed clean 1.4.0 cluster and I am seeing this error in the syslog

```
Jan 20 10:31:11 cluster01-node-2.c.openshift-clusters.internal origin-node[15114]: E0120 10:31:11.591954   15162 thin_pool_watcher.go:72] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/mapper/DOCKER-docker--pool_tmeta: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/mapper/DOCKER-docker--pool_tmeta`: exit status 127
```

It appears periodically every 15s.

**Comment by ncdc** [comment]
Can you run that manually as root?

**Comment by marekjelen** [comment]
```
[root@cluster01-node-2 /]# thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/mapper/DOCKER-docker--pool_tmeta
no current metadata snap
```

**Comment by ncdc** [comment]
Oh sorry, you have to take the snap first. OpenShift does that
automatically. I'm not at my desk but I can send you the command for that
in a couple of hours.

**Comment by ncdc** [comment]
@marekjelen are you running OpenShift containerized?

**Comment by marekjelen** [comment]
Yes, running as containerized. I took the cluster down during the weekend and deployed new one today, the same error is there again.

**Comment by andrewklau** [comment]
I've been seeing this on nodes since 1.2 (atomic containerized)

**Comment by ncdc** [comment]
@sjenning can you find someone to investigate (atomic host, containerized origin, thin_ls is failing)?

**Comment by marekjelen** [comment]
In my case it's plain CentOS

**Comment by sjenning** [comment]
On my somewhat old version of Centos Atomic 7

```
$ atomic host status
State: idle
Deployments:
● centos-atomic-host:centos-atomic-host/7/x86_64/standard
       Version: 7.20161006 (2016-10-05 23:28:52)
        Commit: 2ad34dba5286d69de71b61678d5190b246e7836beada3cdfa18f7bfa4ae3c3f0
        OSName: centos-atomic-host
  GPGSignature: 1 signature
                Signature made Wed 05 Oct 2016 11:39:15 PM UTC using RSA key ID F17E745691BA8335
                Good signature from "CentOS Atomic SIG <security@centos.org>"
[centos@atomic ~]$ ldd /usr/sbin/thin_ls
	linux-vdso.so.1 =>  (0x00007ffda1989000)
	libaio.so.1 => /lib64/libaio.so.1 (0x00007f4b9b36a000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f4b9b140000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f4b9ae37000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4b9ab35000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4b9a91f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4b9a55c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4b9b574000)
```

Could be an issue with a more recent version, but the `atomic host upgrade` command isn't working for me ATM :disappointed:

**Comment by PiotrKlimczak** [comment]
Seeing exactly same issue.
Running containerized version of OpenShift origin 1.4.1.
Origin-node complains all the time about thin_ls exit code 127 due to missing library:

ldd /rootfs/usr/sbin/thin_ls
	linux-vdso.so.1 =>  (0x00007ffd55be2000)
	libaio.so.1 => not found
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fdbf6aba000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fdbf67b1000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fdbf64af000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fdbf6298000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fdbf5ed7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdbf6cea000)

Can run it as without problem from host.

**Comment by sjenning** [comment]
@smarterclayton @ncdc it looks like `thin_ls` is not directly packaged in the origin-node container, hence the missing library.  Do we put `/rootfs/...` paths on the PATH inside the origin container?  If so, we should not do that.

I think this is the fix
```diff
diff --git a/images/base/Dockerfile b/images/base/Dockerfile
index 08bc247..e1b9388 100644
--- a/images/base/Dockerfile
+++ b/images/base/Dockerfile
@@ -7,7 +7,7 @@
 FROM centos:centos7
 
 RUN INSTALL_PKGS="which git tar wget hostname sysvinit-tools util-linux bsdtar epel-release \
-      socat ethtool device-mapper iptables tree findutils nmap-ncat e2fsprogs xfsprogs lsof" && \
+      socat ethtool device-mapper iptables tree findutils nmap-ncat e2fsprogs xfsprogs lsof device-mapper-persistent-data" && \
     yum install -y $INSTALL_PKGS && \
     rpm -V $INSTALL_PKGS && \
     yum clean all && \
diff --git a/images/base/Dockerfile.centos7 b/images/base/Dockerfile.centos7
index f8505d4..e810c24 100644
--- a/images/base/Dockerfile.centos7
+++ b/images/base/Dockerfile.centos7
@@ -7,7 +7,7 @@
 FROM centos:centos7
 
 RUN INSTALL_PKGS="which git tar wget hostname sysvinit-tools util-linux bsdtar centos-release-openshift-origin \
-      socat ethtool device-mapper iptables tree findutils nmap-ncat e2fsprogs xfsprogs lsof" && \
+      socat ethtool device-mapper iptables tree findutils nmap-ncat e2fsprogs xfsprogs lsof device-mapper-persistent-data" && \
     yum install -y $INSTALL_PKGS && \
     rpm -V $INSTALL_PKGS && \
     yum clean all && \
diff --git a/images/base/Dockerfile.rhel7 b/images/base/Dockerfile.rhel7
index 1be9e2f..9231c46 100644
--- a/images/base/Dockerfile.rhel7
+++ b/images/base/Dockerfile.rhel7
@@ -7,7 +7,7 @@
 FROM rhel7
 
 RUN INSTALL_PKGS="which git tar wget hostname sysvinit-tools util-linux bsdtar \
-      socat ethtool device-mapper iptables tree findutils nmap-ncat e2fsprogs xfsprogs lsof" && \
+      socat ethtool device-mapper iptables tree findutils nmap-ncat e2fsprogs xfsprogs lsof device-mapper-persistent-data" && \
     yum install -y $INSTALL_PKGS && \
     rpm -V $INSTALL_PKGS && \
     yum clean all && \
```

**Comment by derekwaynecarr** [comment]
@sjenning -- makes sense to me.

**Comment by lukegb** [comment]
cadvisor automatically searches `/rootfs` for `thin_ls`: https://github.com/openshift/origin/blob/85eb37b34f0657631592356d020cef5a58470f8e/vendor/github.com/google/cadvisor/devicemapper/util.go#L29-L32

**Comment by derekwaynecarr** [comment]
what cadvisor is doing feels wrong imho to search the host rather than package it in the container if its a strict dependency.

**Comment by sjenning** [comment]
@lukegb oooh.  yeah, that's not desirable.  @derekwaynecarr agreed.  PR in the works.

**Comment by smarterclayton** [comment]
Is this installed by Ansible already?

On Feb 1, 2017, at 7:59 PM, OpenShift Bot <notifications@github.com> wrote:

Closed #10940 <https://github.com/openshift/origin/issues/10940> via #12753
<https://github.com/openshift/origin/pull/12753>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10940#event-945738214>, or mute
the thread

**Comment by sjenning** [comment]
@smarterclayton it is not installed by openshift-ansible, at least not directly (might get pulled in as a dep for some other package).  RHEL Atomic cloud image has it preinstalled.  Normal RHEL cloud image does not have it installed by default.

**Comment by ncdc** [comment]
Is it not in origin.spec?

**Comment by sjenning** [comment]
@ncdc must have been in the wrong directory when I did my grep :disappointed: 

Yes, it is currently required by the origin-node package.

Not sure if this is needed anymore.

**Comment by sjenning** [comment]
After thinking about it, yes it is needed.  If someone does a non-containerized node install.

Which make me realize that since we don't install origin-node via yum/RPM in the origin container, we  don't get the dependency management that the package manager provides.  We need to keep the list of dependencies we manually specify in the Dockerfiles for the different images in sync with the `Requires:` in their RPM specs.

**Comment by smarterclayton** [comment]
We will be installing origin-node in the container.

**Comment by ksurent** [comment]
Any chance this will be backported to 1.4.x ?

**Comment by sjenning** [comment]
@ksurent after some additional investigation, it was determined that thin_ls is not safe to run for the purposes of periodic statistics gathering due to its potentially high I/O load that can max out the disk for long periods of time.

It was disabled completely in https://github.com/openshift/origin/pull/12822, until we can either improve thin_ls or find a alternative way to get the information.

That hasn't been backported yet but probably should be. @derekwaynecarr ?
