### ISSUE TITLE
oc set image should return a reasonable error when used with build configs

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#10947]
Right now it doesn't output anything if you pass an arbitrary container name and image name.

cc: @mfojtik

**Comment by bparees** [comment]
presumably this issue is blocked by https://github.com/openshift/origin/issues/10945

**Comment by mfojtik** [comment]
@bparees it will be a follow up :-)

**Comment by bparees** [comment]
@kargakis after discussing with @mfojtik this sounds like an upstream issue that set image needs to report an error for any resource that doesn't contain a pod spec, it's not a build specific thing.  agree?

**Comment by kargakis** [comment]
sure, Michal mentioned buildconfigs I guess because that's the only
non-podspec-y thing I would try to set an image to, hence I assigned it to
you but feel free to pass it back to PM

**Comment by bparees** [comment]
@PI-Victor i heard a rumor you were interested in an upstream issue. do you want to take this?  (needs to be opened against k8s and then addressed)

**Comment by PI-Victor** [comment]
@bparees yes, if it's not extremely urgent, i'd like to give it a shot.

**Comment by bparees** [comment]
@PI-Victor i don't think it's urgent.  please open an upstream issue and close this one.

**Comment by PI-Victor** [comment]
so begins my first issue with k8s: https://github.com/kubernetes/kubernetes/issues/32865
as @bparees suggested, closing this.
