### ISSUE TITLE
Store jobs under batch not under extensions

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#10950]
Currently Jobs are [stored](https://github.com/openshift/origin/blob/7fbb28e56d1975de73b209a46fcd5cf3eea68c62/pkg/cmd/server/kubernetes/master_config.go#L158) under `extensions` groups which is meant to be removed in the next version (1.5) of k8s (https://github.com/kubernetes/kubernetes/issues/32763). We need to:
- [ ] - ~~migrate Jobs from `extensions` to `batch`~~
- [ ] - change the cohabitation definition in `master_config.go`
- [ ] - configure the storage layer so that jobs are still stored under current location

/cc @smarterclayton

**Comment by soltysh** [comment]
Actually I was thinking about moving the storage location to batch, exactly like in k8s, is that a bad idea?

**Comment by liggitt** [comment]
It means all existing jobs disappear...

**Comment by soltysh** [comment]
Right, but that's why I'm talking about migrating those from the old to the new prefix, maybe that sounds ignorant, but that should be possible, right?

**Comment by liggitt** [comment]
That either means offline migration or complicated custom "stitch from two places" storage.

**Comment by smarterclayton** [comment]
Generally we would only enable new deployments in the new location.  We
don't have a reason to move these except during the etcd 2 -> 3 migration
and even then it hardly seems worth it.

**Comment by soltysh** [comment]
Gotcha, thanks for clearing this out. I've updated the description to reflect that.

**Comment by soltysh** [comment]
Per [this comment](https://github.com/kubernetes/kubernetes/pull/33861#issuecomment-252031787) extensions.Jobs won't be removed until after 1.5. I'm changing the prio to p2 and moving to milestone 1.5 in that case.

**Comment by liggitt** [comment]
is this the plan?

1.5:
* switch the storage version to batch/v1 Jobs for 1.5
* run that way for a release (which should let the Job controller update status on those jobs, effectively converting them to batch/v1 Jobs in storage, right? or do we need a post-upgrade task that touches completed/failed jobs to make sure they update in storage?)
* announce deprecation of extensions/v1beta1 Jobs

1.6:

* remove extensions/v1beta1 Jobs

**Comment by soltysh** [comment]
That's basically what I was thinking of. Though I need to sync with you and @deads2k how to configure storage so that it remains under extensions key still. Although, I'd prefer to move them to batch, still.

**Comment by deads2k** [comment]
> That's basically what I was thinking of. Though I need to sync with you and @deads2k how to configure storage so that it remains under extensions key still. Although, I'd prefer to move them to batch, still.

Unless you perform an offline migration, moving them to a different destination will lose all your existing ones.  If you tried to merge two different locations, you have the potential for name conflicts.

**Comment by soltysh** [comment]
I'm aware of that and that's probably why I'll go with the proposed solution, but I can dream from time to time, esp. now when it's Xmas time 😉
