### ISSUE TITLE
Horizontal Pod Autoscaler - Consider the client connections instead CPU comsumption.

### ISSUE THREAD

**Issue by Shyckymn** [openshift/origin#10958]
Hello everyone!

Is there any way to implement HPA using number of client connections instead of CPU consumption?
Is there a plugin that allows this type of implementation?
I'm thinking about use this in my nginx service with autoscaler.

**Comment by DirectXMan12** [comment]
We hope to have support for this in the future, but we're still working on getting the necessary plumbing in place (getting support for more metrics into Heapster, getting support for scaling on different metrics in the Horizontal Pod Autoscaler).  You can follow work on https://github.com/kubernetes/kubernetes/pull/28628 for more information.
