### ISSUE TITLE
sosreport integration

### ISSUE THREAD

**Issue by orgcandman** [openshift/origin#10960]
[provide a description of the issue]

openshift origin does not have any kind of integration with sosreport.  When using the sosreport tool, it would be useful to have openshift state (such as the node configuration yaml) captured
##### Version

all
##### Steps To Reproduce
1. run 'sosreport'
2. look for openshift / origin related files.
##### Current Result

observe that only the /etc/dnsmasq configurations, storage locations, and selinux information is captured.  
##### Expected Result

openshift origin configuration

**Comment by jcantrill** [comment]
@sosiouxme Thoughts on how we might tackle this enhancement?  We would provide an openshift plugin that runs the oadm diagnostic and outputs results to sosreport desired format?

**Comment by sosiouxme** [comment]
For v2, someone who was more sosreport-focused worked on a module, and I can't remember just who that was. Seems at least plausible that they might be willing to do it again for v3.

Basically, we can have sosreport run any commands we want and have the output included in the sosreport that goes back to whoever wants to troubleshoot. oadm diagnostics would be one. We might also want to get logs of particular pods, e.g. router/registry/logging/metrics.

**Comment by jcantrill** [comment]
@sosiouxme might this be addressed by the 'oenshift_health_checker'

**Comment by sosiouxme** [comment]
Ansible openshift_health_checker role would not be something we'd be likely to run as part of sosreport. Very heavy and relies on config / inventory file etc

It looks like if you run sosreport on a master it already does `oadm diagnostics` -- there was a [related bug](https://bugzilla.redhat.com/show_bug.cgi?id=1463509). So *somebody* has created a v3 sosreport plugin. Having it find the node config yaml, master config yaml, related unit and pod logs, etc seems like a sos issue.
