### ISSUE TITLE
Kubectl run and oc run doesn't behave the same under the console

### ISSUE THREAD

**Issue by rafabene** [openshift/origin#10961]
When I run  
```
oc run guestbook-service --image=rafabene/microservices-guestbook:1.0 -r 2
deploymentconfig "guestbook-service" created
```

Both replicas appears under the same "guestbook-service" deployment in the console,

But when I run 
```
kubectl run guestbook-service --image=rafabene/microservices-guestbook:1.0 -r 2
deployment "guestbook-service" created
```
They are not presented together in the console

##### Version
```
oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://192.168.64.10:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
Already Described

##### Current Result
Kubectl run and oc run creates a "deployment" but both appears in different way in the console

##### Expected Result
Show the same console for both commands

**Comment by liggitt** [comment]
A kubernetes deployment is not the same as an openshift deploymentconfig. Full support for kubernetes deployments in the web console is being worked on for 1.4 and tracked at https://trello.com/c/HGvCTI96
