### ISSUE TITLE
Openshift Client cant be used from outside

### ISSUE THREAD

**Issue by mangirdaz** [openshift/origin#10967]
Openshift GoLang Client cant be used from outside. Even If I want to use openshift vendor folder still fails due compile errors. 
##### Version

1.3+
##### Steps To Reproduce

```
package main

import (
    "github.com/openshift/origin/pkg/client"
    "k8s.io/kubernetes/pkg/client/restclient"
)

func main() {

    config := &restclient.Config{
        Host:     "localhost:8443",
        Username: "admin",
        Password: "admin",
        Insecure: true,
    }

    client.New(&config)

}

```
##### Current Result

```
cannot use &config (type **"k8s.io/kubernetes/pkg/client/restclient".Config) as type *"github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient".Config in argument to client.New
```
##### Expected Result

Success

http://stackoverflow.com/questions/39519965/use-vendor-from-other-project
https://lists.openshift.redhat.com/openshift-archives/dev/2016-June/msg00079.html

Ping:
@smarterclayton @jim-minter,
Clayton, any news on "unversioned" client?

**Comment by smarterclayton** [comment]
The near term plan is going to be expose `openshift/client-go` like Kubernetes exposes `k8s.io/client-go`.  We are still waiting for that to be complete upstream before we switch though.

**Comment by Mangirdaz** [comment]
How far is "near term"? and do you have any work started in any sub-repo already?

**Comment by fabianofranz** [comment]
We already have a RFE and a [backlog story](https://trello.com/c/PTDrY0GF) to track this, @smarterclayton can we close this one?

**Comment by smarterclayton** [comment]
The goal would be to do it within the month.

**Comment by Mangirdaz** [comment]
Ok, thanks. Marking in my calendar to check this one in one month :)

**Comment by Mangirdaz** [comment]
@smarterclayton gentle reminder? Will we have something untill end of the month? We are working on AVI network integration for DNS + Virtual services. And now either we go for Java or Go :) and I want Go :)

**Comment by jimmidyson** [comment]
We don't have any problem with using the existing go client outside of OpenShift - we use this in a number of utilities. For example, see https://github.com/fabric8io/exposecontroller/blob/master/exposecontroller.go#L49-L57 for the Kubernetes client & REST config creation & https://github.com/fabric8io/exposecontroller/blob/master/exposestrategy/strategy.go#L51-L55 for the creation of the OpenShift client from the specified REST config.

**Comment by Mangirdaz** [comment]
Thanks! You just planned by weekend!

**Comment by pweil-** [comment]
This has been moved to Trello for release tracking purposes: https://trello.com/c/PTDrY0GF/794-13-client-provide-go-client-similar-to-kubernetes
