### ISSUE TITLE
1.3 Console doesn't show the image id as 1.2

### ISSUE THREAD

**Issue by rafabene** [openshift/origin#10962]
In OpenShift 1.2 I could see the image hash id in the overview page for the pods. Now I can't see it anywhere

##### Version
```
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://192.168.64.10:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
1. Create an openshift 1.3 instance
2. oc login
3. oc run guestbook-service --image=rafabene/microservices-guestbook:1.0 -r 2
4. open the overview page

##### Current Result
Overview shows: Image: rafabene/microservices-guestbook:1.0

##### Expected Result
Overview shows: Image: rafabene/microservices-guestbook:1.0(sad9a0)

**Comment by jwforres** [comment]
@spadgett we need to check whats different about our new logic to see why the SHA no longer shows up in this case

**Comment by spadgett** [comment]
Looks like we didn't carry over the `imagestreams` watch and `ImageStreamResolver` logic to the new overview.

https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/topology.js#L466-L473

**Comment by jwforres** [comment]
Yeah that was originally intentional when we were only falling back to showing the image details if metrics didn't work.  When we added the image details always we missed adding that back in.

**Comment by spadgett** [comment]
For the posted example, I don't see the SHA in 1.2 either.

```
oc run guestbook-service --image=rafabene/microservices-guestbook:1.0 -r 2
```

![screen shot 2016-09-19 at 10 21 50 am](https://cloud.githubusercontent.com/assets/1167259/18635396/f200f5f4-7e52-11e6-9f94-3d56629d3df5.png)

I don't believe we've ever shown the SHA for this case.

**Comment by jwforres** [comment]
in 1.2 and prior we never showed the SHA for RCs / Pods that were set up directly against a docker pull spec and didn't use an deployment config with an ICT (and image stream).  in 1.3 we actually always show the SHA if it is present in the docker pull spec whether there is an ICT and image stream or not, so we actually show it more often than we did using the old logic.

We can actually make this even better though now that the image id is on the containerStatuses

```
  containerStatuses:
    - name: sti-build
      <snip> ... </snip>
      imageID: >-
        docker://sha256:591a8e633348c3e3f4ea06790eaa6ecc4c66ac5f73e999fa3eab8e583fd4c747
      containerID: >-
        docker://5954bb61024b1b3eaadc972bf8df98421908e181e3047109914c7b6ba5261f3d
```

**Comment by jwforres** [comment]
You can end up with pods with different images though, so we'd need to handle that

**Comment by jwforres** [comment]
Need to update the monitoring page at the same time
