### ISSUE TITLE
oc: set image needs to accept image stream tags and image stream images.

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#10974]
Follow-up to https://github.com/openshift/origin/pull/10945

cc: @smarterclayton @mfojtik @openshift/cli-review

**Comment by mfojtik** [comment]
@smarterclayton @kargakis so just to break this down, what we want is:

```
$ oc set image dc/nginx nginx=nginx:1.2 # set the ICT to point to nginx:1.2 docker image
$ oc set image dc/nginx nginx=istag/nginx:1.2 # set the ICT to point to "nginx:1.2" IST
$ oc set image rs/nginx nginx=nginx:1.2 # set the image field for nginx container in RS nginx to nginx:1.2
$ oc set image rs/nginx nginx=istag/nginx:1.2 # set the image field for nginx container in RS nginx to resolved IST nginx:1.2
$ oc set image rs/nginx nginx=nginx:1.2 # set the image field for nginx container in RS nginx to docker image nginx:1.2
```

The image name we will support will be:

* `nginx:1.2` - will set the Docker image name to this value (no resolving)
* `istag/nginx:1.2` - will set image name to resolved IST except DC where it will set the ICT?
* `isimage/nginx:latest@sha256:xyz` - same as above but with image stream image.

**Comment by mfojtik** [comment]
Also for the DC, the question is if we are going to create the ICT for you or not. Also what parameters that ICT will be created with.

**Comment by mfojtik** [comment]
Another option is to not do any magic, and just always resolve the image and set it directly in the pod spec.

**Comment by kargakis** [comment]
> Also for the DC, the question is if we are going to create the ICT for you or not. Also what parameters that ICT will be created with.

We have oc set triggers for that. oc set image is just about the image.

**Comment by kargakis** [comment]
The syntax for the command SGTM

**Comment by mfojtik** [comment]
OK, so no magic with ICT, just set the image field, where will will resolve the ISTAG and ISIMAGE when the command is executed.

**Comment by kargakis** [comment]
Not much magic, more precisely :)

**Comment by fabianofranz** [comment]
Proposition looks good to me.

**Comment by mfojtik** [comment]
@fabianofranz one change from this proposal in the actual PR is that we are injecting `--source` flag to `oc set image` (which is upstream) and we will default to `istag` (because in openshift image stream tags are first class citizens)...

**Comment by fabianofranz** [comment]
@mfojtik sounds good.
