### ISSUE TITLE
Unable to integrate private docker registry managed by nexus with Openshift/origin

### ISSUE THREAD

**Issue by hachiko21** [openshift/origin#10973]
[provide a description of the issue]
##### Version

[provide output of the `openshift version` or `oc version` command]
oc version : 1.2.1
docker version: 1.10.3
vm : centos 7

**Comment by Mangirdaz** [comment]
Nexus used to use non standard naming format. Standart is registry/namespace/image:tag.  Sonatype had one more with repository, which was not playing well with all the standards. But You kinda lack info in this ticket so only assumptions here :)

**Comment by smarterclayton** [comment]
Yes, please provide details of your scenario and we can take a look.

**Comment by hachiko21** [comment]
error: can't connect to "registry-address:port": error checking for V2 registry at https://myregistry-address/v2/: Get https://myregistry-address/v2/: Tunnel or SSL Forbidden

**Comment by hachiko21** [comment]
i have created secret as well as service account inside the project bt still it's trying to login to nexus machine.  M using "oc new-app myregistry/image:tag" for pulling image

**Comment by hachiko21** [comment]
Error syncing pod, skipping: failed to "StartContainer" for "mysql" with ImagePullBackOff: "Back-off pulling image

**Comment by Mangirdaz** [comment]
First I think you are trying to use your registry with https aka. secure.

To eliminate certificate problem try using plain text (http) registry on nexus side and openshift (you will need disable ssl on nexus and add registry as insecure on OSE). 
And check same workflows. And I met 2 beers that it will work if all done right.
