### ISSUE TITLE
Inconsistent naming of path params in REST API schemas.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#10984]
In the path for the REST API endpoints, you have a whole lot for namespaces. Looking at just those for Kubernetes api we have.

```
    "path": "/api/v1/namespaces/{namespace}/bindings",
    "path": "/api/v1/namespaces/{namespace}/configmaps",
    "path": "/api/v1/namespaces/{namespace}/configmaps/{name}",
    "path": "/api/v1/namespaces/{namespace}/endpoints",
    "path": "/api/v1/namespaces/{namespace}/endpoints/{name}",
    "path": "/api/v1/namespaces/{namespace}/events",
    "path": "/api/v1/namespaces/{namespace}/events/{name}",
    "path": "/api/v1/namespaces/{namespace}/limitranges",
    "path": "/api/v1/namespaces/{namespace}/limitranges/{name}",
    "path": "/api/v1/namespaces/{namespace}/persistentvolumeclaims",
    "path": "/api/v1/namespaces/{namespace}/persistentvolumeclaims/{name}",
    "path": "/api/v1/namespaces/{namespace}/persistentvolumeclaims/{name}/status",
    "path": "/api/v1/namespaces/{namespace}/pods",
    "path": "/api/v1/namespaces/{namespace}/pods/{name}",
    "path": "/api/v1/namespaces/{namespace}/pods/{name}/attach",
    "path": "/api/v1/namespaces/{namespace}/pods/{name}/binding",
    "path": "/api/v1/namespaces/{namespace}/pods/{name}/eviction",
    "path": "/api/v1/namespaces/{namespace}/pods/{name}/exec",
    "path": "/api/v1/namespaces/{namespace}/pods/{name}/log",
    "path": "/api/v1/namespaces/{namespace}/pods/{name}/portforward",
    "path": "/api/v1/namespaces/{namespace}/pods/{name}/proxy",
    "path": "/api/v1/namespaces/{namespace}/pods/{name}/proxy/{path}",
    "path": "/api/v1/namespaces/{namespace}/pods/{name}/status",
    "path": "/api/v1/namespaces/{namespace}/podtemplates",
    "path": "/api/v1/namespaces/{namespace}/podtemplates/{name}",
    "path": "/api/v1/namespaces/{namespace}/replicationcontrollers",
    "path": "/api/v1/namespaces/{namespace}/replicationcontrollers/{name}",
    "path": "/api/v1/namespaces/{namespace}/replicationcontrollers/{name}/scale",
    "path": "/api/v1/namespaces/{namespace}/replicationcontrollers/{name}/status",
    "path": "/api/v1/namespaces/{namespace}/resourcequotas",
    "path": "/api/v1/namespaces/{namespace}/resourcequotas/{name}",
    "path": "/api/v1/namespaces/{namespace}/resourcequotas/{name}/status",
    "path": "/api/v1/namespaces/{namespace}/secrets",
    "path": "/api/v1/namespaces/{namespace}/secrets/{name}",
    "path": "/api/v1/namespaces/{namespace}/serviceaccounts",
    "path": "/api/v1/namespaces/{namespace}/serviceaccounts/{name}",
    "path": "/api/v1/namespaces/{namespace}/services",
    "path": "/api/v1/namespaces/{namespace}/services/{name}",
    "path": "/api/v1/namespaces/{namespace}/services/{name}/proxy",
    "path": "/api/v1/namespaces/{namespace}/services/{name}/proxy/{path}",
    "path": "/api/v1/namespaces/{namespace}/services/{name}/status",
    "path": "/api/v1/namespaces/{name}",
    "path": "/api/v1/namespaces/{name}/finalize",
    "path": "/api/v1/namespaces/{name}/status",
```

As you can see there is a lack of consistency with the path param name used to identify the namespace. In most cases it is ``{namespace}``, but there a few cases where is is ``{name}}``.

This can be a bit annoying when doing code generation for the API where because of the way the generated API is being constructed and mapped into a specific language (think automatic mapping of URL to object traversal), the path param name needs to be consistent at a common point in the URL path where always represents the same thing.

Same issue arises in ``watch`` API endpoints as well where mostly uses ``{namespace}`` but then has:

```
    "path": "/api/v1/watch/namespaces/{name}",
```

Would have been nice that the naming was consistent to avoid problems. Am currently changing the schema on the fly to allow type of generated language API want to use.

Likely this will not be fixed, but thought I would log the inconsistency anyway so can make sure can avoid such a thing in the future.

**Comment by liggitt** [comment]
the name parameter is always used for the object's name. When the object is located *within* a namespace, the namespace param is used to indicate which one. 

When working with an actual namespace object, "…/namespaces/{name}" is used. This is consistent with any other unnamespaced object, like "…/nodes/{name}"

**Comment by GrahamDumpleton** [comment]
The choice of what should be consistent though makes life difficult for API generation though, as well as understandability. To be friendly to automatic API generation tools, it should have been internally consistent for each object type and not use a different param name at different times to refer to the same object type.
