### ISSUE TITLE
Etcd removed by running make clean

### ISSUE THREAD

**Issue by yin** [openshift/origin#1098]
Running make clean should not remove etcd installed by hack/install-etcd.sh

To reproduce: 
1. Run:
    ```hack/install-etcd.sh```
2. Run:
    ```make clean```
3. Run:
    ```hack/test-end-to-end.sh```

Desired effect: Test should run, not complaining about missing etcd binary.

**Comment by danmcp** [comment]
1) test-end-to-end.sh doesn't require install-etcd.sh to have been called
2) If you pull down the latest source and run make clean.  How do you know whether you need to also clean out the etcd install?

I might see a use case for an option on make clean to not remove etcd.  And maybe etcd should be in a different folder to make that easier.  But in general this doesn't seem like a clear win.
