### ISSUE TITLE
Centos7 testing package origin-1.3.0-2.el7.x86_64 package cannot deploy router/registry

### ISSUE THREAD

**Issue by jperville** [openshift/origin#10985]
On Centos7, using the testing packages from http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/ , openshift origin 1.3.0 installs but deploying router and registry pod fails with the following error message in `oc describe`:

```
Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "Tag 1.3.0 not found in repository docker.io/openshift/origin-pod"
```

I believe this is due to incorrect handling of the version in the package, the docker image version should be "v1.3.0" instead of "1.3.0". A similar issue I have found is https://github.com/openshift/openshift-ansible/issues/2045 which was solved by @tdawson .

##### Version

```
oc 1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.33.220.xip.io:8443
openshift 1.3.0
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
1. deploy testing openshift origin from packages at http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/ (version is currently : `*-1.3.0-2.el7.x86_64`)
2. deploy router or registry component using "oadm router" or "oadm registry"

##### Current Result

Pods are stuck in "ContainerCreating" phase.

```sh
[root@master ~]# oc get pods
NAME                       READY     STATUS              RESTARTS   AGE
docker-registry-1-deploy   0/1       ContainerCreating   0          5m
router-master-1-deploy     0/1       ContainerCreating   0          5m
```

The relevant message in the output of `oc describe pod docker-registry-1-deploy` is the following:

```
  8s		8s		1	{kubelet master}			Warning		FailedSync		Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "Tag 1.3.0 not found in repository docker.io/openshift/origin-pod"
```

##### Expected Result

The router and registry should deploy.

**Comment by tdawson** [comment]
Ugg ... the blasted 'v' again.
We are currently still unable to build source rpm's from origin via scripts. #7268 
We are close, but not quite there.

Because of that I made a typo, forgot the v in the variable.  It has been fixed and there is a new version that should work.. (version : *-1.3.0-3.el7.x86_64)

**Comment by jperville** [comment]
Thank you very much @tdawson for the quick fix.
