### ISSUE TITLE
Allow specify other docker-machine driver for "oc cluster up"

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#10982]
Currently oc cluster up fire docker-machine with virtualbox and there is no way to specify another driver (i.e: xhyve, kvm, etc..)
##### Version

oc v1.4.0-alpha.0+85eb37b
kubernetes v1.4.0-beta.3+d19513f
##### Steps To Reproduce

oc cluster up --docker-driver=xhyve
##### Current Result

error as not implemented
##### Expected Result

creating oc cluster with the xhyve driver

**Comment by smarterclayton** [comment]
@csrwng can we work this into the existing docker machine flag somehow?  Or have a --machine-args?  I'm concerned about the sheer number of flags, but the 2-3 most common should be allowed as long as we can clearly explain them.  The rest the user can be expected to provide by creating a machine up front themselves.

**Comment by chmouel** [comment]
FYI for others that are wondering and looking at this issue, I made a blog post about it (which document how to create a machine up front as well for future) https://blog.chmouel.com/2016/09/19/getting-openshift-origin-cluster-up-working-with-xhyve/

**Comment by christian-posta** [comment]
+1 @smarterclayton either add `--machine-args` or `--native-virt` or something that allows us to create the machine using whatever the native virt technology is with docker-machine

**Comment by csrwng** [comment]
@smarterclayton given our recent conversation about cluster up not being in the business of creating virtual machines, maybe the right thing to do is to deprecate the --create-machine flag and make it more explicit that you need to have a working Docker for cluster up to work. wdyt?

**Comment by csrwng** [comment]
Minishift (https://github.com/minishift/minishift) which now uses cluster up under the covers allows you more flexibility to create a VM for it. Closing this in favor of using that to create your vm.
