### ISSUE TITLE
Give builds and build pods meaningful names

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1099]
Builds are currently generating a UID for their name.  The build launch code should be using the GenerateName field on the Build object to provide a prefix (that gets randomly generated by a suffix) to have a name.

**Comment by bparees** [comment]
Providing a value for the GenerateName field I understand, but "that gets randomly generated by a suffix" i do not...  what are you proposing we use as the value for the GenerateName field (which is the prefix as i understand it)

**Comment by smarterclayton** [comment]
Right now a bunch of things are being named with uids.  I just want everything to have a meaningful name.

**Comment by bparees** [comment]
https://github.com/openshift/origin/pull/1114

**Comment by bparees** [comment]
close?

**Comment by brenton** [comment]
Resolved by https://github.com/openshift/origin/pull/1114
