### ISSUE TITLE
oc cluster up "--use-existing-config" doesn't show that config is being used

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#10998]
When I have created a cluster with "oc cluster up --use-existing-config" and then bring down and back up the cluster I see the exact same logging as the initial cluster creation, although most of the things have already been done.

```
-- Checking for existing OpenShift container ... OK
-- Creating host directories ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
```

I would expect at least this messages to be different and indicate me that the process just checked for existence in some cases, or skipped in others.

**Comment by csrwng** [comment]
Should be fixed by https://github.com/openshift/origin/pull/11146
