### ISSUE TITLE
oc cluster up recreates myproject in a "--use-existing-config" after I have removed

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#10999]
As a user of oc cluster up I have created a cluster and used --use-existing-config to preserve state.
I have then deleted myproject as it doesn't make sense for me.
I have brought down the cluster and back up, and the project gets recreated.

I would expect the project to remain deleted, as that is an action I did consciously as a user.

**Comment by csrwng** [comment]
Should be fixed by https://github.com/openshift/origin/pull/11146
