### ISSUE TITLE
'oc rollout status' is missing

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#10994]
When rebasing to kubernetes 1.4, `kubectl rollout status` did not make it to `oc` tool.
This seems to be the same issue as with [oc set image](https://github.com/openshift/origin/pull/10945)

cc: @kargakis @mfojtik 

##### Version
```bash
oc version
oc v1.4.0-alpha.0+93292f7-dirty
kubernetes v1.4.0-beta.3+d19513f
features: Basic-Auth
```

**Comment by kargakis** [comment]
Added in https://github.com/openshift/origin/pull/9874
