### ISSUE TITLE
WebHook on GitLab does not work

### ISSUE THREAD

**Issue by vanloswang** [openshift/origin#11002]
Environment is similar to https://github.com/openshift/origin/issues/10986, just replace Gogs to GitLab, The GitLab server is deployed in a CentOS 7 VM.
Click 'Test Hook'  and it returns an error, the error info is as following:
```bash
Hook execution failed: {"kind"=>"Status", "apiVersion"=>"v1", "metadata"=>{}, "status"=>"Failure", "message"=>"Internal error occurred: hook failed: missing X-GitHub-Event or X-Gogs-Event", "reason"=>"InternalError", "details"=>{"causes"=>[{"message"=>"hook failed: missing X-GitHub-Event or X-Gogs-Event"}]}, "code"=>500}
```
It seems like the webhook communication is ok now, but the request header does not contain the key and value for X-GitHub-Event or X-Gogs-Event. So how to let origin works together with GitLab?
The GitLab version is gitlab-ce-8.5.1-ce.0.el7.x86_64 and the settings on GitLab is as following:
![image](https://cloud.githubusercontent.com/assets/1133578/18655122/d89fe11c-7f18-11e6-939f-4986ee53d4c9.png)

##### Version
Origin 1.2

##### Steps To Reproduce
1. create a build tempate with github webhook and create a build task
2. copy the webhook URL, and create a webhook on GitLab
3. click 'Test Hook' on GitLab

##### Current Result
failed and show me:
```bash
Hook execution failed: {"kind"=>"Status", "apiVersion"=>"v1", "metadata"=>{}, "status"=>"Failure", "message"=>"Internal error occurred: hook failed: missing X-GitHub-Event or X-Gogs-Event", "reason"=>"InternalError", "details"=>{"causes"=>[{"message"=>"hook failed: missing X-GitHub-Event or X-Gogs-Event"}]}, "code"=>500}
```

##### Expected Result
success

**Comment by vanloswang** [comment]
As I know there is a event within GitLab request json data named 'X-Gitlab-Event', may be we need to add support for it.

**Comment by jorgemoralespou** [comment]
@vanloswang You should use generic webhook on OpenShift for GitLab

**Comment by bparees** [comment]
@jorgemoralespou assuming gitlab is matching the github payload, using the github webhook makes sense given all the data we pull off of it.

if gitlab is not matching the github payload then i agree, this is not going to work and shouldn't be merged...  i was just assuming it was.  perhaps a mistake.

**Comment by jorgemoralespou** [comment]
@bparees Didn't see the PR, just saw the issue and my comment was to confirm that GitHub triggers did not work with GitLab and generic webhook was needed. As if the linked PR does fixes that, then I'm happy to have it merged it.
We've been using GitLab for quite some time and have been always needing to use generic webhook. If using the GitHub one provides greater benefit, LGTM.

**Comment by vanloswang** [comment]
@bparees @jorgemoralespou With this commit, the webhook on gitlab is work well for me.

**Comment by shubhamsinha111** [comment]
> @vanloswang You should use generic webhook on OpenShift for GitLab

i used generic webhook still got 400 error "Hook executed successfully but returned HTTP 400 {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"missing X-GitHub-Event or X-Gogs-Event","reason":"BadRequest","code":400}"
