### ISSUE TITLE
Ugly and redundant output in new-build

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#11000]
* Displaying the same info twice
* The format is impossible for a human being to understand at a glance.  It's better to simplify and not show every option than it is to be difficult to read.

```
$ oc new-build --binary --name sized --to sized:middle
* A Docker build using binary input will be created
      * The resulting image will be pushed to image stream "sized:middle"
      * Use 'start-build --from-dir=DIR|--from-repo=DIR|--from-file=FILE' to trigger a new build
      * WARNING: a binary build was created, you must specify one of --from-dir|--from-file|--from-repo when starting b
```

**Comment by smarterclayton** [comment]
The message should be more geared towards a first time user - so overwhelming me with 30 characters of `-`, `|`, and `=` is not useful.  Could just tell the user what flags are relevant or tell them to look at the help.

**Comment by bparees** [comment]
I think we should just always print the WARNING version, unless you explicitly requested a binary build in which case the non-warning variant(and only that variant) makes sense.   But we should probably never print both.

@jim-minter you're as user facing as anyone, want to take a crack at cleaning this up?  I suggest you comment w/ a draft proposal of the new text before you both to start making code changes...you're going to find this to be a surprisingly contentious topic :)

**Comment by jim-minter** [comment]
OK, so if a binary build was specifically requested (--binary), how about:
`      * A binary build was created, use 'start-build --from-dir|--from-file|--from-repo' to start it`

Otherwise (does this only happen when the user references a local path / local git repo with no remotes?):
`      * WARNING: a build was created from a local path/repository, use 'start-build --from-dir|--from-file|--from-repo' to start it`

Let the discussions commence!

**Comment by bparees** [comment]
> Could just tell the user what flags are relevant or tell them to look at the help.

@smarterclayton those *are* the flags that are relevant...  telling them to look at the help is likely to be even longer than the existing 30 chars.

> Otherwise (does this only happen when the user references a local path / local git repo with no remotes?):

@jim-minter yeah i believe that's the only case(s).

> * WARNING: a build was created from a local path/repository, use 'start-build --from-dir|--from-file|--from-repo' to start it

i prefer it explicitly saying a binary build was created, that gives them a reference point to go find more docs.

but the biggest issue (beyond the duplicate message) is whether we use the existing wording (which indicates all the flags) or find some other wording that makes @smarterclayton happier.

**Comment by smarterclayton** [comment]
If you meet someone new, do you give them the entire details of your life
story?  Or do you give them an anecdote intended to start a conversation,
and see how it goes from there?

Sending all the flags, of which we don't even really explain the
difference, doesn't help (because you've just exceeded their threshold of
new things to learn).  My recommendation is to give them only the
information they need to be successful in a sentence not much longer than
80 chars.

Do they *need* to know the exact syntax of all the flags?  Or just one?  If
only novice users are going to bother to read this, which flag are they
likely to want?

**Comment by bparees** [comment]
> f you meet someone new, do you give them the entire details of your life story? Or do you give them an anecdote intended to start a conversation, and see how it goes from there?

Well, I am an oversharer.......

ok so if it's a git repo show them the --from-repo flag and if it's not, show them the --from-dir flag.  --from-file is unusual/unlikely to be what they need if they just ran new-app against a directory.

unfortunately that probably takes this change from trivial to slightly complicated to carry the state of "what is this thing they passed us" out to where the message is generated, but a tour through the new-app/new-build code will do @jim-minter some good.

**Comment by smarterclayton** [comment]
I'd ok with even a single flag.   Dir is most likely to work, but repo
would likely be more accurate in any new-app new-build flow.

On Sep 21, 2016, at 3:13 AM, Ben Parees <notifications@github.com> wrote:

f you meet someone new, do you give them the entire details of your life
story? Or do you give them an anecdote intended to start a conversation,
and see how it goes from there?

Well, I am an oversharer.......

ok so if it's a git repo show them the --from-repo flag and if it's not,
show them the --from-dir flag. --from-file is unusual/unlikely to be what
they need if they just ran new-app against a directory.

unfortunately that probably takes this change from trivial to slightly
complicated to carry the state of "what is this thing they passed us" out
to where the message is generated, but a tour through the new-app/new-build
code will do @jim-minter <https://github.com/jim-minter> some good.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/11000#issuecomment-248530291>,
or mute the thread

**Comment by bparees** [comment]
we went with --from-dir because you're you're only going to get a binary build if either 

1) the dir isn't a git repo
2) the dir doesn't have a valid remote

of those scenarions, --from-dir works for both, --from-repo might be want you want for one of them.
