### ISSUE TITLE
post-rebase: investigate master startup failures

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#11011]
After the rebase, we're seeing a lot of master `/healthz` flakes on the LDAP test. Unclear what this means as the symptom is fairly vague as far as "something failed in the master startup" but we should investigate it since it comes after months of nice green tests. 

https://ci.openshift.redhat.com/jenkins/job/ldap_groups_extended/buildTimeTrend

@smarterclayton

**Comment by stevekuznetsov** [comment]
We're up to 12 consecutive failures ... bumping priority. This seems bad.

**Comment by liggitt** [comment]
is this still an issue?

**Comment by stevekuznetsov** [comment]
LDAP test seems pretty stable now, so I guess it went away ... that is a little disconcerting but I'll close this guy.
