### ISSUE TITLE
running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#11015]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6193/
Conformance test flakes with:

```
hack/build-cross.sh
++ temporarily enabling swap space to assist in building in limited memory - use OS_BUILD_SWAP_DISABLE=1 to bypass
++ Building go targets for linux/amd64: cmd/openshift cmd/oc

/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory
```
##### Version

oc v1.3.0-alpha.3+fab0d0a-dirty
kubernetes v1.3.0+507d3a7
features: Basic-Auth

Server https://10.13.137.149:8443
openshift v1.3.0-rc1
kubernetes v1.3.0+52492b4
##### Steps To Reproduce

[merge] / [test]
##### Current Result

```
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory
```
##### Expected Result

success

**Comment by smarterclayton** [comment]
Solution is to move to Go 1.7 or run our tests on bigger machines.  Dan, which one do you want to do?
