### ISSUE TITLE
master API allows to upload invalid image object

### ISSUE THREAD

**Issue by miminar** [openshift/origin#11012]
Image object containing manifest V2 schema 2 with missing `DockerImageConfig` attribute can be created but cannot be received.
##### Version

master
##### Steps To Reproduce
1. manually create image stream mapping with manifest V2 schema 2 lacking `DockerImageConfig`:

``` go
    ism := ImageStreamMapping{
        ObjectMeta: ObjectMeta{
            Namespace: "namespace",
            Name:      "is",
        },
        Image: Image{
            ObjectMeta: ObjectMeta{
                Name: manifestDigest,
            },
            DockerImageReference: dockerImageReference,
            DockerImageManifest:  string(m), // m is of manifest schema 2
        },
        Tag: "tag",
    }
```
1. `oc get istag is/tag`
##### Current Result

Error from server: unexpected end of JSON input
##### Expected Result

I can see the image.
##### Additional info

ImageWithMetadata helper expects `DockerImageConfig` to be set: https://github.com/openshift/origin/blob/7f59726538199f5fc1bd30a975ab2530eb30535e/pkg/image/api/helper.go#L528. We should fail image validation if unset for schema 2 manifest.

**Comment by liggitt** [comment]
can we tighten validation of that, or will that cause problems with existing data?

**Comment by miminar** [comment]
>  can we tighten validation of that, or will that cause problems with existing data?

That's what I plan to do. If someone was using his own client (all the clients we have upload correct objects) to upload such a data, he is already unable to access it using our API. Tightening validation won't make the situation any worse.

**Comment by miminar** [comment]
The `DockerImageConfig` is now being intentionally removed. It's now stored on registry's storage instead. Serving the image without the `DockerImageConfig` filled has been fixed.
