### ISSUE TITLE
Rename 'Clean' to 'Incremental' in v1beta2

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#1102]
As a reference see https://github.com/openshift/origin/pull/1101

**Comment by smarterclayton** [comment]
Not sure Incremental is the best word, but agree with the context change.

**Comment by soltysh** [comment]
@smarterclayton I'm open for suggestions, we need to come up with some kind of negation of Clean, so it's `false` by default. Incremental seemed the most natural IMHO.

**Comment by soltysh** [comment]
Already done as part of this commit https://github.com/openshift/origin/commit/2e188016aa957efe6b55744930941495a5673b5b. @danmcp pls close.
