### ISSUE TITLE
redis on Origin

### ISSUE THREAD

**Issue by vanloswang** [openshift/origin#11029]
I create a template with persistent volume for redis. The redis docker image is docker.io/redis:3.2.3-alpine which the offical GitLab template uses.

The pod for redis start failed, and show me as following:
```bash
su-exec: setgroups: Operation not permitted 
```

##### Version
Origin 1.2

##### Steps To Reproduce
1. create a template for redis, using docker image docker.io/redis:3.2.3-alpine
2. create an app for redis

##### Current Result
The pod for redis start failed, and show me as following:
```bash
su-exec: setgroups: Operation not permitted 
```

##### Expected Result
run ok

**Comment by bparees** [comment]
it sounds like this image expects to run as a specific user (in particular it appears to default to running as root).  By default containers in openshift run as a random uid for security reasons.  If you control your openshift cluster, you can follow these instructions to enable yourself to run the image as the user it defines:
https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile

alternatively you can update their image to follow our recommendations for making an image able to run as any uid:
https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines

see the section on "support arbitrary user ids"
