### ISSUE TITLE
oc doesn't time out watches on target server disappearing

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#11038]
oc watches don't handle target server disappearing ungracefully (e.g. power off).
##### Version

```
$openshift version                         

openshift v1.3.0-alpha.2+10133fa
kubernetes v1.3.0+57fb9ac
etcd 2.3.0+git

Server https://192.168.42.116:8443
OpenShift v1.3.0
Kubernetes v1.3.0+52492b4
```
##### Steps To Reproduce
1. Start OpenShift server & log in
2. `oc get pods -w`
3. Power off OpenShift host
##### Current Result

oc client does not close

Notice that `netstat -anp|grep 8443` shows connection still established.
##### Expected Result

oc client should close connections & report error (or potentially reconnect transparently).
##### Additional Information

I assume this is because WS read timeouts are set to infinity. Would be better to implement WS ping (I've confirmed API server handles this properly) & set a reasonable read timeout.

**Comment by liggitt** [comment]
oc doesn't use websockets, it uses chunked streaming connections. Not sure what the client side timeout on the connection is

**Comment by jimmidyson** [comment]
Ah I didn't know that. Exhibits same behaviour though from what I can see so assume read timeout is being disabled - that would be valid of course, receiving no data for a long time would be fine if connection was still actually valid.

**Comment by juanvallejo** [comment]
Adding a client request timeout here: https://github.com/openshift/origin/pull/11104

**Comment by juanvallejo** [comment]
@jimmidyson a client-side request timeout has been added.
I am closing this issue, but please re-open if it is still not fixed.
