### ISSUE TITLE
when using --public-hostname , subdomain should NOT point to internal ip 

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#11048]
oc cluster up --public-hostname=openshift.xyz.com

##### Version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.31.41.134:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
oc new-project dev
oc new-app debianmaster/nodejs-welcome  
oc expose svc nodejs-welcome

##### Current Result
oc get routes 
nodejs-welcome-dev.172.31.41.134.xip.io

##### Expected Result
nodejs-welcome-dev.openshift.xyz.com

**Comment by csrwng** [comment]
@debianmaster this is working as designed. We cannot assume that the public host you specify supports wildcard DNS. If you want to change the default routing suffix you can specify it with `--routing-suffix`.

Closing this issue but reopen if you think we can handle this differently.
