### ISSUE TITLE
'oc rollout status' will return exit code 0 even though the command status does not exist

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#11043]
`oc rollout status` returns bad exit code 0 even though there is no command `status` there. This is a big issue for scripts...
##### Version

``` bash
$ oc version
oc v1.4.0-alpha.0+8974c3c-dirty
kubernetes v1.4.0-beta.3+d19513f
features: Basic-Auth

Server https://192.168.42.42:8443
openshift v1.4.0-alpha.0+c452daf
kubernetes v1.4.0-beta.3+d19513f
```
##### Steps To Reproduce
1. oc rollout status
2. oc rollout xxxxxxxxxxxwhateverxxxxxxxxxxx
##### Current Result

exit code 0
##### Expected Result

non zero exit code

**Comment by kargakis** [comment]
This is a problem with all nested commands @openshift/cli-review

**Comment by juanvallejo** [comment]
`rollout status` sub-command was added here: https://github.com/openshift/origin/pull/9874, but @kargakis is right, will fix this for non-existent commands
