### ISSUE TITLE
Source pod ip is not preserved when contacting a cluster ip service

### ISSUE THREAD

**Issue by marun** [openshift/origin#11042]
A kube e2e test was added to validate preservation of the pod source ip when contacting a service:

https://github.com/kubernetes/kubernetes/pull/30739

This test currently fails when run against origin.  According to @danwinship, this is due to docker adding a rule ensuring that anything with a source IP in lbr0's network and destination IP outside of lbr0's network is masqueraded.  The result is that a pod IP (e.g. x.x.x.5) would appear to the service ip as the lbr0 gateway (e.g. x.x.x.1).

The e2e in question will be skipped until this issue is resolved.

cc: @openshift/networking

**Comment by danwinship** [comment]
Not clear if we're going to fix this before migrating everyone to OVN, but we don't want the issue auto-closed

/remove-lifecycle rotten
/lifecycle frozen

**Comment by danwinship** [comment]
This works for ovs-networkpolicy, and is not going to be fixed for ovs-multitenant.
/close
