### ISSUE TITLE
TestNamespaceLifecycleAdmission flake

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#11058]
the new TestNamespaceLifecycleAdmission test from #10911 just tripped up a merge:

    --- FAIL: TestNamespaceLifecycleAdmission (8.61s)
    	namespace_lifecycle_admission_test.go:97: Expected forbidden error because of a terminating namespace, got <nil>
    FAIL

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/6227/consoleFull#213299324856bf4006e4b05b79524e5923

@liggitt

**Comment by liggitt** [comment]
that's... concerning... not seeing how that would happen with a single etcd

**Comment by mfojtik** [comment]
@liggitt do you want to take a look on this issue?

**Comment by liggitt** [comment]
yeah, I figured it out. the expiry check on the "forceLiveLookup" cache in the upstream lifecycle admission plugin was backwards, so the logic to work off live data immediately after a namespace delete wasn't effective.
