### ISSUE TITLE
customize master logs

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin#11063]
Hi, I would like to add some extra fields in OpenShift master logs, so that using "journalctl openshift-master", it displays those fields, can we achieve this? 

FYI- I have installed origin using ansible.

**Comment by sosiouxme** [comment]
@priyanka5 can you give an example of what you would like to do?

I don't believe the master is logging directly to the journal; rather it has output that is directed to the journal by systemd. So other than modifying the log messages I doubt there is much that can be done.

**Comment by portante** [comment]
How does OpenShift master emit its logs?  Does it use the `sd_journal_*()` APIs directly?  Or `syslog()`?  Or just emit to `stdout`/`stderr`?  If it is via `sd_journal*()`, then from the API descriptions those fields (key/value pairs) can be added by the code for OpenShift master that invokes those APIs, and then will be displayed via journalctl [[1](https://www.freedesktop.org/software/systemd/man/sd_journal_print.html#)].

If it is via `syslog()` or `stdout`/`stderr`, then it would seem that all that the OpenShift master code can do to add just data is just include it in the base log message and then it will show up in the journalctl message field.

**Comment by priyanka5** [comment]
@sosiouxme @portante : thanks for the response, basically I am looking for auditing logs , where I would like to see some custom fields such as role assigned to the user. I was referring to this link -**https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-node-config-audit-config** , this gives some details but not everything a PaaS admin would like to have in logs. Is there a way? and one more thing I would like to know is using ansible installation where source code link is defined?? so that I can modify the public origin code and create my own github branch and ansible will use that for installation, Thanks again

**Comment by jcantrill** [comment]
@priyanka5 I am sorry but you are not being clear about what you require.  If you wish to include additional information to audit logging, please feel free to hack on this repo and submit a PR or provide more explicit details about the enhancement.  Also, the source code for the ansible code used for installation can be found at https://github.com/openshift/openshift-ansible

**Comment by sosiouxme** [comment]
I think this request is finally being fulfilled in the form of audit logging and advanced audit configuration. See https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-node-config-advanced-audit
