### ISSUE TITLE
Share the pod cache with deployer pods

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#11081]
Our deployer pods use an [internal cache](https://github.com/openshift/origin/blob/88e231f624c0962eb5737b1cf151853c436446cd/pkg/deploy/strategy/support/lifecycle.go#L482) for watching changes to hook pods. We may want to make them use the shared cache.

@deads2k @mfojtik thoughts?

**Comment by deads2k** [comment]
> Our deployer pods use an internal cache for watching changes to hook pods. We may want to make them use the shared cache.
> 
> @deads2k @mfojtik thoughts?

Does the deployer watch more than once in its process?  If not, you won't gain anything.

**Comment by kargakis** [comment]
Yes, it can have up to three pods to watch for (pre, mid, post) and any of those may be at any state (Pending, Running, Succeed/Failed) and have Retry policy set. So it may need to watch for [0, 3*2] times for non-retrying and as many retries as we can do for the rest of the deployment timeout (which can be a pretty big number) for retrying hooks.

**Comment by kargakis** [comment]
Wait, it can just use up to three watches that's all.

**Comment by liggitt** [comment]
And it watches namespaced.
