### ISSUE TITLE
error: Pod "hello-openshift" is invalid: spec: Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds`

### ISSUE THREAD

**Issue by adelton** [openshift/origin#11093]
[provide a description of the issue]

I try to follow https://github.com/openshift/origin/tree/master/examples/hello-openshift on OpenShift Origin installation, started on Fedora 24 via `oc cluster up` with `oc` from origin-clients-1.3.0-1.x86_64, in turn built from rawhide .spec at https://copr.fedorainfracloud.org/coprs/adelton/openshift-origin-1.3/

I am able to do

```
# oc get pod hello-openshift -o yaml |grep podIP
  podIP: 172.17.0.2
# curl 172.17.0.2:8080
Hello OpenShift!
```

but the `oc set env` step fails:

```
# oc set env pod/hello-openshift RESPONSE="Hello World!"
error: Pod "hello-openshift" is invalid: spec: Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds`
```

##### Version
[provide output of the `openshift version` or `oc version` command]

```
# oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://10.16.69.150:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
1. Have some recent `origin-clients` rpm package installed.
2. Run `oc login` and log in as `developer`
3. `git clone https://github.com/openshift/origin.git`
4. `oc create -f origin/examples/hello-openshift/hello-pod.json`
5. `oc get pod hello-openshift -o yaml |grep podIP`
6. `curl 172.17.0.2:8080`
7. `oc set env pod/hello-openshift RESPONSE="Hello World!"`

##### Current Result
```
error: Pod "hello-openshift" is invalid: spec: Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds`
```
##### Expected Result

No error and subsequent `curl 172.17.0.2:8080` showing `Hello World!` as https://github.com/openshift/origin/tree/master/examples/hello-openshift suggests.

##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

I get
```
# oadm diagnostics
-bash: oadm: command not found
```

**Comment by liggitt** [comment]
the doc is wrong, you can't change the spec of an existing pod

**Comment by bparees** [comment]
assigning to @knobunc since he introduced this behavior and documentation.
