### ISSUE TITLE
Autoscaling is taking too long to start new containers.

### ISSUE THREAD

**Issue by Shyckymn** [openshift/origin#11095]
Hello everyone!

My HPA is taking too long to start new containers.
I created a service containing one http/apache container and created HPA.
So, I defined the CPU limits to 50 (request) and 100 (limit). 
I did the same for Memory Request/Limit.
Then, I created autoscaling with Min Pods = 1 and Max Pods = 10.
After that, I made some test with Apache HTTP server benchmarking tool (ab).

`$ab -k -c 500 -t 900 -n 500000 http://myurl`

My openshift deployment takes about 10 minutes to scale up all the 10 containeres.

How can I adjust the settings to improve this time?

##### Version
```
oc v1.3.0-rc1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.8.7.213:8443
openshift v1.3.0-rc1
kubernetes v1.3.0+52492b4
```

**Comment by DirectXMan12** [comment]
Can you clarify which part is taking "too long"?  Is it that it takes a while to send the scale request?  Is it that it takes a while for all the containers to be up and running?  Do you see multiple scales over the 10 minute interval (e.g. scale up to 3, scale up to 6, scale up to 10)?  Without any further information, it's difficult to figure out the best course of action here (for instance, we have some known scale time issues that exhibit themselves under certain conditions, but it's difficult to know if you're hitting those without further information).

Events from the HPA and targeted DC (or RC) would be useful, as well as a more detailed description of the issue.

**Comment by Shyckymn** [comment]
@DirectXMan12  It was that it takes a while to send the scale request. 
If the upper limit of consumption of cpu / memory of the DC was reached, it takes about 5 minutes to the upscale starts.
I increased the allocation of server memory and the start time of the HPA has improved considerably.
Thanks for your attention!
Closing this issue.
