### ISSUE TITLE
The README for hello-openshift is not clear about how to get modified container running

### ISSUE THREAD

**Issue by adelton** [openshift/origin#11108]
[provide a description of the issue]
I try to follow https://github.com/openshift/origin/tree/master/examples/hello-openshift on OpenShift Origin installation, started on Fedora 24 via `oc cluster up` with `oc` from origin-clients-1.3.0-1.x86_64, in turn built from rawhide .spec at https://copr.fedorainfracloud.org/coprs/adelton/openshift-origin-1.3/

When I modify the string of the response in `hello_openshift.go` (due to https://github.com/openshift/origin/issues/11093 I cannot change it for existing container) and do the `go build` + `mv` + `docker build` commands, the response does not change.

The `README.md` should say how to restart the pod, or whatever steps are needed.

##### Version
[provide output of the `openshift version` or `oc version` command]

```
# oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://10.16.69.150:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
1. Follow https://github.com/openshift/origin/tree/master/examples/hello-openshift
2. Build new `docker.io/openshift/hello-openshift`, with different string assigned instead of

```
response = "Hello everyone!"
```

in the .go file.

##### Current Result

`curl` still returns `Hello OpenShift!`

When I remove the pod and create it again with

```
# oc delete pod hello-openshift
pod "hello-openshift" deleted
# oc create -f hello-pod.json
pod "hello-openshift" created
```

I start to get

```
# curl 172.17.0.2:8080
curl: (7) Failed to connect to 172.17.0.2 port 8080: Connection refused
```

The `oc status` reports

```
pod/hello-openshift runs openshift/hello-openshift

Errors:
  * pod/hello-openshift is crash-looping

```
##### Expected Result

Clear steps that allow the person following the README.md to get the new, updated pod, up and running.

##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]
```
# oadm diagnostics
-bash: oadm: command not found
```

**Comment by knobunc** [comment]
Submitted https://github.com/openshift/origin/pull/11117 to clarify how to change the message.

I don't know why your custom image did not work.  Can you pull the logs from docker for one of the failed pods?

**Comment by adelton** [comment]
> Submitted #11117 to clarify how to change the message.

Thank you, I confirm that adding `env` works.

If deployment was used on top (?) of pod, would it then be possible to change the value "on-the-fly", with some `oc patch`?

> I don't know why your custom image did not work. Can you pull the logs from docker for one of the failed pods?

Currently, after rebuilding the container with `go build -tags netgo`, the pod is shown failing with `no such file or directory `. And I get the same error when I try to run the container locally with `docker run`:

```
# docker run --rm -ti docker.io/openshift/hello-openshift
no such file or directory
docker: Error response from daemon: Container command not found or does not exist..
```

Re-pulling the image from the Docker hub makes it work:

```
# docker run --rm -ti docker.io/openshift/hello-openshift
serving on 8888
serving on 8080
```

**Comment by knobunc** [comment]
If you have a dc or rc on top, you can just set it by running this command:
  oc set env ...

I do not understand the docker pull probkem.  @bparees do you have any insight?

**Comment by bparees** [comment]
I suspect this has to do w/ the need to statically build the hello-openshift binary.  I don't remember the details, but it causes issues like this.  When we build it for the image we publish to dockerhub we take some special actions to ensure the binary is properly statically built.

specifically we build it w/ these environment values set: CGO_ENABLED=0 OS_GOFLAGS="-a -installsuffix cgo"

see: https://github.com/openshift/origin/issues/2579
and https://github.com/openshift/origin/pull/2904

**Comment by knobunc** [comment]
The current README tells you:

> 
> After that, if you are running the pod from above, delete it:
> 
>` $ oc delete pod hello-openshift`
> 
> Then you can re-create the pod as with the first example, get the new IP address, and then curl will show your new message
