### ISSUE TITLE
TestNamespaceLifecycleAdmission integration flake

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#11109]
```
--- FAIL: TestNamespaceLifecycleAdmission (8.48s)
	namespace_lifecycle_admission_test.go:97: Expected forbidden error because of a terminating namespace, got <nil>
FAIL
```

Seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/6378/consoleFull#-212491224457692177e4b031e1b25cfb77

**Comment by mfojtik** [comment]
@deads2k fyi.

**Comment by liggitt** [comment]
Fixed in https://github.com/openshift/origin/pull/11088 which merged an hour after that test job started
