### ISSUE TITLE
Add oc create route plain and --labels

### ISSUE THREAD

**Issue by ghost** [openshift/origin#11110]
I open this Issue as a outcome of the discussion on the users mailing list about **Router Sharding**

http://lists.openshift.redhat.com/openshift-archives/users/2016-September/thread.html#00180
##### Version

git master
##### Steps To Reproduce
1. `oc create route unsecure ...`  
   - this command should create just a route like  
     `oc expose service nginx`
2. `oc create route ... --labels route=default`  
   this command creates a route and labels the route to be able to us it in ROUTE or NAMESPACE_LABEL for router sharding
##### Current Result

Not available
##### Expected Result

@ `oc create route plain ...`  
- a http route to the service  

@ `oc create route ... --labels route=default`  
- a labeled route
##### Additional Information

visit [Using Router Shards](https://docs.openshift.org/latest/install_config/router/default_haproxy_router.html#using-router-shards) for the topic of router sharding

**Comment by kargakis** [comment]
cc: @openshift/cli-review

**Comment by fabianofranz** [comment]
I'm good with the adding `--labels` part, but what's the motivation for wanting `oc create route plain` and not just using `oc expose`? Discoverability? I ask because today `oc create route` is clearly positioned as a command to create *secured* routes, for unsecured ones it already points to `oc expose` in help.

**Comment by cw-aleks** [comment]
It is easier for the most customer to use **one** command for routes.
But I'm fine with `oc expose` for the unsecured route.

I have change _plain_ to _unsecure_ is much better. Thanks for the hint ;-)

**Comment by kargakis** [comment]
@fabianofranz I was thinking the same thing but eventually I think we probably want to move users away from `expose` (so a subcommand in `create route` for creating unsecured routes is probably fine).
