### ISSUE TITLE
Extended.deploymentconfigs with revision history limits [Conformance] should never persist more old deployments than acceptable after being observed by the controller

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#11114]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6409/consoleFull had a conformance test flake:

```
• Failure [288.339 seconds]
deploymentconfigs
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:767
  with revision history limits
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:716
    should never persist more old deployments than acceptable after being observed by the controller [Conformance] [It]
    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:715

    Expected an error to have occurred.  Got:
        <nil>: nil

    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:696
```
##### Additional Information

This is from https://github.com/openshift/origin/pull/11045 where I revise how the asset bundle for the console is built. I don't see how it could be related to deployments.

**Comment by kargakis** [comment]
@sosiouxme is this failure from 4 days ago? If so, it should be fixed on master by https://github.com/openshift/origin/pull/11066

**Comment by mfojtik** [comment]
@sosiouxme right, this should be fixed by now, if you see this again in more recent test run feel free to re-open this.

**Comment by sosiouxme** [comment]
sorry for the false alarm.

**Comment by soltysh** [comment]
This looks like a more recent run: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6719/consoleFull although I'm wondering if that didn't fail in what I'm tracking in https://github.com/openshift/origin/issues/11016#issuecomment-250493844

**Comment by kargakis** [comment]
@enj can you post the job that failed?

**Comment by mfojtik** [comment]
@kargakis https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6910/

**Comment by enj** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/6910/consoleFull

```
• Failure [486.240 seconds]
deploymentconfigs
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:767
  with revision history limits
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:716
    should never persist more old deployments than acceptable after being observed by the controller [Conformance] [It]
    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:715

    Expected error:
        <*errors.errorString | 0xc8200f9600>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    not to have occurred

    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:696
```

**Comment by soltysh** [comment]
I've been hitting similar, but wrt to PodDisruptionbudget in #11187: 
```
• Failure [80.527 seconds]
[k8s.io] DisruptionController [Feature:PodDisruptionbudget]
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:793
  should update PodDisruptionBudget status [It]
  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/disruption.go:102

  Expected error:
      <*errors.errorString | 0xc8200dd780>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/disruption.go:100
```

It all goes to #11016, I need to go back to that topic next week.

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/693/testReport/junit/(root)/Extended/deploymentconfigs_with_revision_history_limits__Conformance__should_never_persist_more_old_deployments_than_acceptable_after_being_observed_by_the_controller/

**Comment by eparis** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/51/

**Comment by kargakis** [comment]
```
• Failure [191.179 seconds]
deploymentconfigs
/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:894
  with revision history limits [Conformance]
  /go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:803
    should never persist more old deployments than acceptable after being observed by the controller [It]
    /go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:802

    the current deployment needs to have finished before attempting to trigger a new deployment through configuration change
    Expected error:
        <*errors.StatusError | 0xc4211f4c00>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {SelfLink: "", ResourceVersion: ""},
                Status: "Failure",
                Message: "the server has asked for the client to provide credentials (get pods)",
                Reason: "Unauthorized",
                Details: {
                    Name: "",
                    Group: "",
                    Kind: "pods",
                    Causes: [
                        {
                            Type: "UnexpectedServerResponse",
                            Message: "Unauthorized",
                            Field: "",
                        },
                    ],
                    RetryAfterSeconds: 0,
                },
                Code: 401,
            },
        }
        the server has asked for the client to provide credentials (get pods)
    not to have occurred

    /go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:774
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/476/consoleFull#-16030365756cbb9a5e4b02b88ae8c2f77

**Comment by kargakis** [comment]
Deployer logs:
```
Mar 27 17:51:41.400: INFO: --- pod history-limit-8-deploy logs
2017-03-27T21:51:07.279145000Z --> pre: Running hook pod ...
2017-03-27T21:51:12.770480000Z test pre hook executed
2017-03-27T21:51:12.771249000Z --> pre: Success
2017-03-27T21:51:13.888870000Z --> Scaling up history-limit-8 from 0 to 1, scaling down history-limit-7 from 1 to 0 (keep 1 pods available, don't exceed 2 pods)
2017-03-27T21:51:13.889947000Z     Scaling history-limit-8 up to 1
2017-03-27T21:51:39.164748000Z error: You must be logged in to the server (the server has asked for the client to provide credentials (get pods))---
```

**Comment by mfojtik** [comment]
@kargakis I think I saw this yesterday, will have a look today

**Comment by kargakis** [comment]
@mfojtik yes, it was the same failure. Not sure why it happens

**Comment by mfojtik** [comment]
@kargakis would help to see master logs to find the spot it is trying to get the pods (I suspec the deployment pruner)

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/309/

**Comment by mfojtik** [comment]
wth... it seems like the client/user we used that test suddently lost the permissions? (there are test cases from the same test that pass...) @enj is that possible?

I will check if we do something special in that test cases (because if something in the client/auth would be broken, we will be seeing this randomly)

**Comment by smarterclayton** [comment]
This is etcd losing leader because fsync to disk was 15s or higher.  I.e.
same old etcd problem @stevekuznetsov

**Comment by mfojtik** [comment]
Thanks Clayton, this bug was driving me crazy :)

**Comment by stevekuznetsov** [comment]
Still trying to figure out why etcd falls over when we pass it a data dir...

**Comment by bparees** [comment]
for anyone else running into this flake from other tests, the fingerprint is a command failing with:
```
"error: You must be logged in to the server (the server has asked for the client to provide credentials"
```

**Comment by bparees** [comment]
(assuming we're using this flake to chase the credential issues that @smarterclayton says are caused by etcd hiccups)

**Comment by stevekuznetsov** [comment]
There's a couple of issues tracking it, #13067 also

**Comment by mfojtik** [comment]
@stevekuznetsov just saw this on GCE

**Comment by bparees** [comment]
and non-GCE
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/489/

**Comment by stevekuznetsov** [comment]
Don't think that is the same flake -- https://github.com/openshift/aos-cd-jobs/pull/199 should have fixed the ETCD issue. There is no mention of credentials in the flake you linked.

**Comment by stevekuznetsov** [comment]
@smarterclayton are we running etcd data in a tmpfs in the GCE job? If not, we will continue to see etcd issues with fsync ther

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/4883/

**Comment by mrogers950** [comment]
```
Failure [78.051 seconds]
deploymentconfigs
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:1121
  with revision history limits [Conformance]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:892
    should never persist more old deployments than acceptable after being observed by the controller [It]
    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:891

    the current deployment needs to have finished before attempting to trigger a new deployment through configuration change
    Expected error:
        <*errors.errorString | 0xc421861bf0>: {
            s: "found multiple running deployments: [history-limit-2 history-limit-3]",
        }
        found multiple running deployments: [history-limit-2 history-limit-3]
    not to have occurred

    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:851
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/3885/

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/503/testReport/junit/(root)/Extended/_Feature_DeploymentConfig__deploymentconfigs_with_revision_history_limits__Conformance__should_never_persist_more_old_deployments_than_acceptable_after_being_observed_by_the_controller__Suite_openshift_conformance_parallel_/

**Comment by tnozicka** [comment]
Feels like this issue is tracking many different failures.
- I guess the etcd issue is fixed now?
- `found multiple running deployments` was already fixed
- [this](https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/503/testReport/junit/(root)/Extended/_Feature_DeploymentConfig__deploymentconfigs_with_revision_history_limits__Conformance__should_never_persist_more_old_deployments_than_acceptable_after_being_observed_by_the_controller__Suite_openshift_conformance_parallel_/) last failure remains to be investigated

**Comment by kargakis** [comment]
Different failure mode:
```
expected len of old deployments: 2 to equal dc revisionHistoryLimit: 3
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17104/test_pull_request_origin_extended_conformance_gce/11266/

**Comment by jim-minter** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17666/test_pull_request_origin_extended_conformance_install/3727/
