### ISSUE TITLE
oc client now will not ignore SSL certificate hostname mismatch even with insecure

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#11122]
With a master certificate that does not contain the "correct" hostname, the latest version of oc will not ignore this problem even when --insecure is set.

##### Version
origin-clients from centos 1.3.0-3.el7
[root@8a369a8b5694 /]# oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. create a bad master certificate for the api
2. try to login

##### Current Result

(hostnames truncated)

[root@8a369a8b5694 /]# oc login https://master1-b754:8443 --insecure-skip-tls-verify=true -u andrew -p something --loglevel=8
I0927 18:56:02.730036      90 round_trippers.go:296] HEAD https://master1-b754:8443/
I0927 18:56:02.730083      90 round_trippers.go:303] Request Headers:
I0927 18:56:03.090114      90 round_trippers.go:321] Response Status:  in 360 milliseconds
I0927 18:56:03.090145      90 round_trippers.go:324] Response Headers:
F0927 18:56:03.090202      90 helpers.go:110] error: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, master1-15bf, master1.example.com, openshift, openshift.default, openshift.default.svc, openshift.default.svc.cluster.local, 172.30.0.1, 192.168.0.101, not master1-b754

##### Expected Result
An error/warning perhaps, but a functional login.

**Comment by liggitt** [comment]
need to allow insecure setting to bypass x509.HostnameError and x509.CertificateInvalidError

also need to tweak the insecure prompt text depending on which error they are bypassing, and adjust the "get pretty error" helper

should backport to 1.3.1

**Comment by thoraxe** [comment]
Is there an older version of the origin-clients package I can get from somewhere that doesn't have this issue?

**Comment by thoraxe** [comment]
I just tried every single version of the origin-clients package with no success. Oh well.

**Comment by kbsingh** [comment]
@thoraxe: you can yum install origin-clients-1.2.1 from the same CentOS repos and it should work. We'll try and get this fix ported into the origin-clients-1.3 rpms soon ( cc @tdawson )

**Comment by fabianofranz** [comment]
This fix was ported to the 1.3 / 3.3 git branches, meaning it will be in the next point release (Origin 1.3.1 and OCP 3.3.1).
