### ISSUE TITLE
Web console : using "http" (instead "https") in the address produces raw TCP packet as reply

### ISSUE THREAD

**Issue by ppatierno** [openshift/origin#11134]
Hi,
is it normal that using the browser with the following address : 

http://localhost:8443/console

(note http instead of https)

Openshift doesn't not redirect to https but replies with a strange TCP packet with following values : 

0x15 0x03 0x01 0x00 0x02 0x02 0x0A

so not with a valid HTTP response and then close the communication socket ?

Thanks,
Paolo.

##### Version
oc v1.4.0-alpha.0+fcba8ba
kubernetes v1.4.0-beta.3+d19513f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.1.104:8443
openshift v1.4.0-alpha.0+fcba8ba
kubernetes v1.4.0-beta.3+d19513f

##### Steps To Reproduce
1. Start OpenShift origin
2. Open a browser and specify http://localhost:8443/console as address

##### Current Result

Strange raw TCP response.

##### Expected Result

At least a redirect to the https page ?

**Comment by liggitt** [comment]
Yes, that is normal. A single port cannot serve both http and https, including a http->https redirect
