### ISSUE TITLE
Container can't access the network with to the as xx.com

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#11132]
Hi,
I have a error when i use openshift that container can't access the network(use openshift-ansible to build it).
```
cat /etc/resolv.conf 
# Generated by NetworkManager
search skys.net
nameserver 172.17.0.108
# nameserver updated by /etc/NetworkManager/dispatcher.d/99-origin-dns.sh
```
when i ping www.baidu.com,the domain name is `www.baidu.com.skys.net`,so it is error when i want to build my project.
![q-0](https://cloud.githubusercontent.com/assets/12937669/18907751/7a69da0c-859f-11e6-8c79-9ae393825b85.png)
![q-1](https://cloud.githubusercontent.com/assets/12937669/18907752/7a6bf72e-859f-11e6-884e-db793c08d9d3.png)
---
delete `search skys.net`,the pod is ok to access the network,but this can't solve this problem.
![q-2](https://cloud.githubusercontent.com/assets/12937669/18908547/99f2fc20-85a2-11e6-820a-807549fd4532.png)
when i restart network ,NetworkManager or machine，the `search skys.net` have be configured in /etc/resolv.conf.
thanks.

**Comment by knobunc** [comment]
@wenskys what version of OpenShift are you running?

**Comment by wenskys** [comment]
@knobunc openshift origin 1.3

**Comment by wenskys** [comment]
@knobunc It is easy to solve  it.
delete the `search skys.net` when network/NetworkManager restart
```
#/etc/NetworkManager/dispatcher.d/99-origin-dns.sh
sed -i '0,/^nameserver/ s/^nameserver.*$/nameserver '"${def_route_ip}"'/g' /etc/resolv.conf
#insert it
eval sed -i '/$(hostname -d)/d' /etc/resolv.conf
```
