### ISSUE TITLE
disable feature does not work?

### ISSUE THREAD

**Issue by vanloswang** [openshift/origin#11133]
add disabledFeatures in /etc/origin/master/master-config.yaml as following:
```bash
assetConfig:
  disabledFeatures: "web console"
  logoutURL: ""
```
Both "web console" and "WebConsole" are tested, the two strings is found out in ./pkg/cmd/server/api/types.go. But none of them works for me. As https://github.com/openshift/origin/pull/4046 says it will deny access '/console'. The docs of disabledFeatures from https://docs.openshift.org/latest/install_config/master_node_configuration.html is only this descriptions:
```bash
DisabledFeatures

A list of features that should not be started. You will likely want to set this as null. It is very unlikely that anyone will want to manually disable features and that is not encouraged.
```
Maybe my config is wrong, I guess.

##### Version
Origin 1.2

##### Steps To Reproduce
1. add disabledFeatures in /etc/origin/master/master-config.yaml
2. restart master
3. access the '/console' from web browser 

##### Current Result
access not denied

##### Expected Result
access denied

**Comment by jwforres** [comment]
@miminar since you made the change in the referenced PR

**Comment by liggitt** [comment]
`disabledFeatures` doesn't nest under `assetConfig`, and should be an array:

```
disabledFeatures:
- WebConsole
```

**Comment by vanloswang** [comment]
@jwforres @liggitt It works for me now. Thanks.
