### ISSUE TITLE
oc cluster up: should check for existing/accessibility of /var/run/docker.sock on remote system

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#11143]
You can bind the docker daemon to a TCP socket, so that it can be used over the network, using the `-H` flag, this means the daemon will no longer listen on the default UNIX socket `/var/run/docker.sock`.

For example:

`docker daemon -H tcp://0.0.0.0:2375` listens on a TCP port **only**
`docker daemon` listens on a Unix domain socket **only**
`docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock` listens on both a TCP port and domain socket
##### Version

origin 1.3.0 final release tarball (openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-linux-64bit):

```
oc v1.3.0
kubernetes v1.3.0+52492b4
openshift v1.3.0
kubernetes v1.3.0+52492b4
```
##### Steps To Reproduce
1. Set options in `/etc/sysconfig/docker` and restart the daemon: `-H tcp://0.0.0.0:2375` and `--insecure-registry 172.30.0.0/16`
2. From another machine, download the `oc` tarball
3. Set your `DOCKER_HOST` environment variable to point to the first machine (`export DOCKER_HOST=tcp://1.2.3.4:2375`)
4. Check connectivity using `docker info`
5. Run `oc cluster up`, which correctly runs against the remote machine, but errors out unless the remote machine is listening on the docker socket
##### Current Result

```
FAIL
   Error: cannot access master readiness URL https://xxx:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0928 18:32:54.607640    4952 log.go:11] skydns: ready for queries on cluster.local. for udp4://0.0.0.0:8053 [rcache 0]
     I0928 18:32:54.706102    4952 run_components.go:223] DNS listening at 0.0.0.0:8053
     I0928 18:32:54.709474    4952 start_master.go:544] Controllers starting (*)
     E0928 18:32:54.711045    4952 util.go:45] Metric for serviceaccount_controller already registered
     I0928 18:32:54.712827    4952 docker.go:329] Start docker client with request timeout=2m0s
     I0928 18:32:54.777164    4952 start_node.go:298] Starting node xxx (v1.3.0)
     I0928 18:32:54.778955    4952 start_node.go:307] Connecting to API server https://xxx:8443
     I0928 18:32:54.790540    4952 docker.go:309] Connecting to docker on unix:///var/run/docker.sock
     I0928 18:32:54.790569    4952 docker.go:329] Start docker client with request timeout=0
     F0928 18:32:54.790618    4952 node.go:169] error: No Docker socket found at /var/run/docker.sock. Have you started the Docker daemon?
```

A solution is to ensure that the daemon still listens on /var/run/docker.sock by specifying: `-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock`.
##### Expected Result

It would be nice if `oc cluster up` detected that there is nothing listening on `/var/run/docker.sock` on the docker host and provided an appropriate error message, rather than failing at node startup time.

**Comment by jawnsy** [comment]
@csrwng What do you think? I can understand if this isn't a supported scenario, though if it's not too much trouble, an error message would be nice.

I did confirm that everything works nicely if the docker daemon is listening on both TCP and its default Unix domain socket, which is pretty nifty!

**Comment by csrwng** [comment]
Yup, we should display an informative error if possible.
