### ISSUE TITLE
Add easy means of getting the URL for the REST API using 'oc'.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#11148]
Currently to get the URL for the REST API endpoint using ``oc`` you need to run:

```
oc config view --minify -o jsonpath='{.clusters[*].cluster.server}'
```

It would be better to have a easier and more obvious way of getting this.

@smarterclayton suggested an option to either ``oc whoami`` or ``oc project``.

This would make it easier to get the URL when someone wants to write scripts which operate against the REST API and it should use whatever is the current cluster the user is logged into.

Currently need to say:

```
#!/bin/sh

OPENSHIFT_API_URL=`oc config view --minify -o jsonpath='{.clusters[*].cluster.server}'`
OPENSHIFT_API_TOKEN=`oc whoami --token`

URL="$OPENSHIFT_API_URL/oapi/v1/users/~"

curl -H "Authorization: Bearer $OPENSHIFT_API_TOKEN" $URL
```

Would sure look nicer if that command to get the URL could be simplified.

**Comment by stevekuznetsov** [comment]
For many tasks you should also be able to do `oc get raw /some/endpoint`
