### ISSUE TITLE
Router misbehaves due to mismatched certificate/key

### ISSUE THREAD

**Issue by exowaucka** [openshift/origin#11140]
If you create a route using a key and certificate that don't match, all new routes will fail to work (return 503s).  Even worse, doing a deployment will cause existing routes to for that service to fail in the same manner.  Worst of all, it is possible (observed in the wild on a 1.2 cluster) for traffic intended for one service to be sent to another service in another project!

A relatively easy solution would be to check that the key matches the certificate before attempting to use a route when generating the HAProxy config.
##### Version

```
oc v1.3.0
kubernetes v1.3.0+52492b4
```
##### Steps To Reproduce
1. Create a few services in a few projects, all with associated routes.
2. Create a new route in one project with a key that does not match the certificate.
3. Do a deployment on a different service in a different project.
4. Create a new route in a different project using a valid certificate and key.
5. Attempt to access the redeployed service using its original route.  This should fail with a 503 or return data from a different service.
6. Attempt to access the route created in step 4.  This should fail with a 503.
##### Current Result

503s.  503s everywhere.
##### Expected Result

Only the bad route should return a 503.

**Comment by knobunc** [comment]
This is the same as https://bugzilla.redhat.com/show_bug.cgi?id=1379701

If you do:
  oc env dc/router EXTENDED_VALIDATION=true

Then it will make the haproxy validate the certs.

**Comment by exowaucka** [comment]
Is there any particular reason `EXTENDED_VALIDATION=true` isn't the default?

**Comment by ramr** [comment]
@exowaucka  so the only reason its not on by default was to give it time to soak (didn't have enough data points to make a call either way). We will make it default and probably part of the default api validation checks (not require a variable etc) - though I think we still need to consider implications to existing routes. Thx

**Comment by ramr** [comment]
Associated PR: https://github.com/openshift/origin/pull/11218
