### ISSUE TITLE
oc policy can-i --list output is not parser friendly.

### ISSUE THREAD

**Issue by pruan-rht** [openshift/origin#11147]
oc policy can-i --list output is not parser friendly due to the lack of --output=format support
##### Version

oc v1.3.0-rc1+ea6ca28
##### Steps To Reproduce

oc policy can-i --list
##### Current Result

not parser friendly
##### Expected Result

parser friendly.

**Comment by fabianofranz** [comment]
Hey @liggitt @deads2k, @abstractj is taking this one. Which output formats would you expect to have here? If the entries directly reflects single API objects then I'd say all output formats we have in `get` probably apply; otherwise maybe just json and yaml?

**Comment by deads2k** [comment]
It doesn't have a name with the object comes back. Or at least not a meaningful one.  Otherwise, it is a normal API object.

**Comment by abstractj** [comment]
@fabianofranz  We've been discussing some changes here https://github.com/abstractj/origin/commit/88bf1621ec7b4ea8e31f1bedd4c4336c6969f3a1#commitcomment-22954041. Sharing just in case.

**Comment by abstractj** [comment]
@fabianofranz fyi I reassigned this to Juan, because his solution (https://github.com/juanvallejo/origin/commit/875b22c122ca9578c096401492680d759cb6666b) is way ahead than mine
