### ISSUE TITLE
Error syncing pod, skipping: failed to "StartContainer" for "tomcat" with RunContainerError: "runContainer: Error response from daemon: {\"message\":\"cannot join network of a non running container: 15dd9ef8489f8047c7a0511d94f96843c6650e4d51f6d86a939bf9060c7e5364\"}

### ISSUE THREAD

**Issue by hachiko21** [openshift/origin#11154]
[provide a description of the issue]
##### Version

oc - v1.3.0
[provide output of the `openshift version` or `oc version` command]
##### Steps To Reproduce
1. [step 1]
2. [step 2]
##### Additional Information

[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by hachiko21** [comment]
openshift container log

Failed cleaning up orphaned pod directories: remove /var/lib/origin/openshift.local.volumes/pods/d7e16dd8-863a-11e6-8eda-fa163e2dff61/volumes/kubernetes.io~secret/default-token-bn0gt: device or resource busy

**Comment by derekwaynecarr** [comment]
Can you give a series of reproduction steps?  Are you running an image from a public location that we can try to reproduce the failure?

**Comment by hachiko21** [comment]
I am using openshift origin version 1.3.0 running as a docker container. i have created my secret for pulling image from own private registry.
yaml file for creating pod:

apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - image: myregistry/mysql
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 3306
  imagePullSecrets:
    - name: myregistrysecret

**Comment by derekwaynecarr** [comment]
Do all containers on your cluster fail to start, or just this one?  Can you launch other pods without issue?

**Comment by hachiko21** [comment]
No all container have same problem.

**Comment by LalatenduMohanty** [comment]
@hachiko21 Were you able to fix the issue you reported? Looks like we are seeing similar issue.

**Comment by haimari** [comment]
@hachiko21 
Hello
Got the same issue...
https://stackoverflow.com/questions/44702715/kubernetes-pod-fails-with-crashloopbackoff
