### ISSUE TITLE
letsencrypt certificate in oc client

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#11151]
The letsencrypt certificates doesn't seem to be integrated with oc

##### Version

oc v1.4.0-alpha.0+40668dd
kubernetes v1.4.0-beta.3+d19513f
features: Basic-Auth

##### Steps To Reproduce
1. Use a letsencrypt certificates for the console, API which gets nicely show as secure in firefox : 

<img width="922" alt="2016-09-29__10-11-32-12477" src="https://cloud.githubusercontent.com/assets/98980/18946148/eca58394-862d-11e6-8161-ebd46f3ac67b.png">

2. Use oc client to connect to it :  

<img width="904" alt="2016-09-29__10-18-09-4050" src="https://cloud.githubusercontent.com/assets/98980/18946180/0d0a4566-862e-11e6-8305-feaa24b5960e.png">

##### Current Result

"The server uses a certificate signed by an unknown authority."

##### Expected Result

it should recognize this authority

##### Additional Information

This is MacosX Sierra

I compiled the oc client from git with this golang version : 

go version go1.7.1 darwin/amd64

**Comment by fabianofranz** [comment]
cc @liggitt

**Comment by liggitt** [comment]
what is $KUBECONFIG pointing to? is `curl` happy with the cert and hostname?

**Comment by chmouel** [comment]
Yes curl is happy 

<img width="953" alt="2016-09-30__08-12-50-6151" src="https://cloud.githubusercontent.com/assets/98980/18982366/d393ebd0-86e5-11e6-9a2d-6d74baada455.png">

The .kube/config contains this : 

http://sprunge.us/IeER

**Comment by liggitt** [comment]
Do you have $KUBECONFIG set?

**Comment by chmouel** [comment]
noip, i don't

**Comment by liggitt** [comment]
interesting... a standalone go program doesn't like the cert either:

main.go:
```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	req, _ := http.NewRequest("GET", "https://lb.198.154.189.125.xip.io:8443", nil)
	fmt.Println(http.DefaultClient.Do(req))
}
```

```
go run main.go
<nil> Get https://lb.198.154.189.125.xip.io:8443: x509: certificate signed by unknown authority
```

curl is happy for me as well:
```
curl https://lb.198.154.189.125.xip.io:8443 -vvv
* Rebuilt URL to: https://lb.198.154.189.125.xip.io:8443/
*   Trying 198.154.189.125...
* Connected to lb.198.154.189.125.xip.io (198.154.189.125) port 8443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: lb.198.154.189.125.xip.io
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET / HTTP/1.1
> Host: lb.198.154.189.125.xip.io:8443
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Fri, 30 Sep 2016 15:59:37 GMT
< Content-Length: 203
< 
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/controllers",
    "/healthz",
    "/healthz/ping",
    "/healthz/ready",
    "/metrics",
    "/oapi",
    "/oapi/v1",
    "/swaggerapi/"
  ]
* Connection #0 to host lb.198.154.189.125.xip.io left intact
```

**Comment by liggitt** [comment]
did you include the intermediate in the serving cert chain?

**Comment by chmouel** [comment]
I believe that's issue @liggitt after putting the full certificates chain it's working properly with the oc client, the behavior from curl not failing got me into error. thanks

**Comment by debianmaster** [comment]
i'm seeing same issue with  letsencrypt cert  my oc client version is oc v1.4.1+3f9807a   can you tell me how to import `full certificates chain`

**Comment by liggitt** [comment]
In the serving certificate given to the API, there should be multiple PEM blocks. The first should be the server's certificate, followed by the intermediate certificate PEM blocks
