### ISSUE TITLE
RFE: be able to validate objects before submission (--dry-run)

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#11152]
This comes from this SO question: http://stackoverflow.com/questions/38824409/validate-openshift-objects-defined-in-yaml-before-actually-applying-or-executing

Generally, I want to verify if the objects returned by the template are valid, but the only option to do so is to invoke:

```
$ oc process -f examples/zookeeper/template.json | oc apply -f -
```

which will actually create those objects, if valid. Otherwise, I'll get an actual error. 

I'd like to be able to invoke:

```
$ oc process -f examples/zookeeper/template.json | oc apply --dry-run -f -
```

which will give me either the validation error or empty output meaning ok.

I guess, this should go upstream since both apply and create (which should get `--dry-run` as well) are from k8s.

**Comment by soltysh** [comment]
@fabianofranz || @bparees not sure which one of you could own that

**Comment by kargakis** [comment]
upstream issue: https://github.com/kubernetes/kubernetes/issues/11488

**Comment by juanvallejo** [comment]
This has been addressed in upstream PR: https://github.com/kubernetes/kubernetes/pull/34028

**Comment by kargakis** [comment]
I guess we can close this issue in favor of kubernetes/kubernetes#11488 - dry-run still needs to move server-side though

**Comment by soltysh** [comment]
@juanvallejo this should land with the next rebase (#13653) in that case. Mind closing it then?
