### ISSUE TITLE
Connections between pods/conteiner 

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [openshift/origin#11168]
Connections between pods/conteiner on Openshift node?

##### Version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
I have 2 pods nginx and mysql

##### Current Result
have to dynamic IP on  both pods
and need always change configure in nginx for connections to mysql after scale/up/restart pods
there is no connection on the domain name or the name pods

##### Expected Result
what are the ways of interconnection containers/pods? 

- built-dns for new containers?
- auto adding to /etc/hosts (as local dns) ?
- lables(from kubernetes ) / links(from docker cli)/extrahosts(from composer file)?

how connections between other nodes with openshift on other VPS/DC?

##### Additional Information

[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by bparees** [comment]
pods are interconnected using services: https://docs.openshift.org/latest/architecture/core_concepts/pods_and_services.html#services

**Comment by Evgeniy-Bondarenko** [comment]
how connections between other nodes with openshift?

We have webserver on node1 and database on node2. 
How we connect webserver to node2:/database?

You can show a small example of a configuration for connecting two different pods(web and db) on the same node or/and on different nodes openshift?

**Comment by bparees** [comment]
again, you use services.  you define a service for the DB and you access the service by its hostname from the webserver pod.

This template defines all aspects of an application frontend and database and the services that allow them to interact:
https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json

**Comment by bparees** [comment]
the point of services is you don't need to care what node the pod is running on, it's stable hostname/ip that fronts the pod.

**Comment by bevinhex** [comment]
To make it clear, let me give my example
I created a new mongodb-persistent app
after that ```oc get svc``` results
```mongodb   172.30.164.147   <none>        27017/TCP   31m```
Now I created wekan with ```oc new-app quay.io/wekan/wekan:v0.89```
now '''oc get svc``` gets
```
mongodb   172.30.164.147   <none>        27017/TCP   31m
wekan     172.30.73.68     <none>        80/TCP      25m
```
So mongodb service name is "mongodb", so for wekan I provide MONGO_URL variable as
MONGO_URL=mongodb://user:password@mongodb/wekan

The point is , it seems you can access other service container just by its service name (don't use IP, it changes)
