### ISSUE TITLE
how change password for web interface?

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [openshift/origin#11162]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]
oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
when we go to web interface https://mydoain:8443 we have default web-interface (admin:admin) for openshift

##### Current Result
default pass
##### Expected Result
1. change pass
2. add new user for joint project 
3. how add ssl key? (replace ./openshift.local.config/master/ca.key - no result)
##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by liggitt** [comment]
changing the password depends on the identity provider you are using for authentication.

information on customizing the certificate used to serve the web console is available at https://docs.openshift.org/latest/install_config/certificate_customization.html#configuring-custom-certificates
