### ISSUE TITLE
RFE: Ability to set default revisionHistoryLimit

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#11169]
It would be good if we can set a default `revisionHistoryLimit` similar to the the project default limits

Users who have quotas on RC will end up hitting their quota without even realising.

**Comment by mfojtik** [comment]
@andrewklau sounds good to me.

@smarterclayton @deads2k objections?

**Comment by deads2k** [comment]
> @smarterclayton @deads2k objections?

I don't object to a default as long as its high.  The issue is backwards compatibility.  If the limit is not high enough, you can end up suddenly removing old deployments that people were intentionally keeping before.

**Comment by andrewklau** [comment]
If it's included as part of the configurable project limits, you could avoid having backwards compatibility issues as it'd have to be explicitly defined.

**Comment by deads2k** [comment]
> If it's included as part of the configurable project limits, you could avoid having backwards compatibility issues as it'd have to be explicitly defined.

@mfojtik if you decide to go this route, you'll want to make sure that it doesn't have any negative interactions with the admission plugins that embed limit rangers.

**Comment by smarterclayton** [comment]
Where would we set this?

**Comment by deads2k** [comment]
> Where would we set this?

I think we're talking about a `LimitRange` wired to a deploymentconfigspec.RevisionHistoryLimit.  API defaulting has backwards compatibility concerns.  A LimitRange wouldn't, but it would make migration and code interaction a little more difficult.
