### ISSUE TITLE
oc annotate does not allow setting an annotation to empty

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin#11175]
oc annotate does not allow setting an annotation to empty.  Trying to advise users to set a project node selector to empty for use in oadm diagnostics logging.
##### Version

oc v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.28.128.4:8443
openshift v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7
##### Steps To Reproduce
1. Create a project with an annotation
2. Try to update the annotation to empty
##### Current Result

$ oc annotate namespace logging openshift.io/node-selector="" --overwrite
error: invalid annotation format: openshift.io/node-selector=
##### Expected Result

Yeah for you
##### Additional Information

```
$ oc annotate namespace logging openshift.io/node-selector="" --overwrite --loglevel=8
I0930 18:31:43.327516    6431 loader.go:330] Config loaded from file /var/lib/openshift/openshift.local.config/master/admin.kubeconfig
F0930 18:31:43.327814    6431 helpers.go:108] error: invalid annotation format: openshift.io/node-selector=
```

**Comment by kargakis** [comment]
cc: @openshift/cli-review probably needs an upstream issue

**Comment by juanvallejo** [comment]
both origin and upstream PRs have been merged, closing this issue, please re-open if necessary

**Comment by smarterclayton** [comment]
Did this make it to 3.7.1?

**Comment by juanvallejo** [comment]
@smarterclayton yes: https://github.com/openshift/origin/commits/v3.7.1?before=ee2e38215f562d6dad9b30da8dcec2fbf5a6cf60+35
