### ISSUE TITLE
Jenkins pipeline stages not updated in web-console

### ISSUE THREAD

**Issue by LarsMilland** [openshift/origin#11170]
Jenkins pipeline stages not updated in web-console.
##### Version

oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxx.yyy.domain:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
##### Steps To Reproduce

oc new-project pipeline

Create jenkins service from the "jenkins-ephemeral" template

Create the ruby sample jenkins pipeline as explained here:

https://github.com/openshift/origin/tree/master/examples/jenkins/pipeline

with the template:

https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/pipeline/samplepipeline.json

and then start the pipeline builder

oc start-build sample-pipeline
##### Current Result

The build starts and runs fine in Jenkins, but in the web console the pipeline stages status to the pipeline build are not updated. The contained ruby builder starts fine and also the following deployer, so the pipeline executes fine.
##### Expected Result

The build would run as expected, and the web console would show the stages from the pipeline as they progress.

**Comment by jwforres** [comment]
This sounds like one of a number of issues with the sync plugin

If it eventually syncs its probably this one https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/85

or could be either of these coming up again
https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/98
https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/70

**Comment by jwforres** [comment]
cc @jimmidyson

**Comment by jimmidyson** [comment]
What version of the sync plugin are you using? Can you try with the latest, 0.0.13 please?

**Comment by LarsMilland** [comment]
Hi

I have created an updated version of the jenkins-1-centos image that is used as the default one which is currently "shipped" with OpenShift Origin to include the sync plugin version 0.0.13, as the one that is referenced as of now is the 0.0.12 version. 

Then I have run same procedure as before but without any change to the result. The pipelines still runs fine, but there is nothing in the web-console of OpenShift.

When looking at the log output of the pod running the Jenkins server inside the namespace of OpenShift where all this is running there are a few errors where the sync plugin complains that it can't update the "pipeline" status back to the OpenShift environment. 

Please see the attached log file showing these errors.  

Best regards
Lars Milland
[OpenShiftJenkinsPipelinesSyncLogs.txt](https://github.com/openshift/origin/files/504184/OpenShiftJenkinsPipelinesSyncLogs.txt)

**Comment by jimmidyson** [comment]
From the logs you can see that the service account that Jenkins is running as doesn't have correct permissions to update build configs or builds. I'm not sure what the recommended roles are for Jenkins - @bparees?

**Comment by bparees** [comment]
It should be given the edit role. Our sample jenkins template creates the
service account and binds the role if you use it to stand up jenkins.

Ben Parees | OpenShift

**Comment by LarsMilland** [comment]
Hi

Yes I understand that the "jenkins" serviceaccount should have edit rights on the namespace where the jenkins pod is supposed to sync its pipeline stage changes back to OpenShift.

So I have also earlier investigated this via:
oc get rolebindings - that reports the jenkins serviceaccount to have that exact rolebinding

NAME                    ROLE                    USERS     GROUPS                             SERVICE ACCOUNTS   SUBJECTS
jenkins_edit            /edit                                                                jenkins

and from and export:

oc export rolebindings jenkins_edit
apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-ephemeral
    template: jenkins-ephemeral-template
  name: jenkins_edit
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: pipelines
userNames:
- system:serviceaccount:pipelines:jenkins


and here the the output of describing the jenkins pod:

oc describe pods jenkins-4-pkz6e
Name:                   jenkins-4-pkz6e
Namespace:              pipelines
Security Policy:        restricted
Node:                   mynode.company.domain/123.11.11.11
Start Time:             Sat, 01 Oct 2016 10:20:06 +0200
Labels:                 deployment=jenkins-4
                        deploymentconfig=jenkins
                        name=jenkins
Status:                 Running
IP:                     11.11.1111
Controllers:            ReplicationController/jenkins-4
Containers:
  jenkins:
    Container ID:       docker://2a97a41d5b87a063dc54f77f0e5cae5c926a1ed41ff9a2447f882d6bad390939
    Image:              111.111.111.111:5000/default/s2ijenkins@sha256:15c90be84983539f1e12bf81dfe16304691af4d9ac22fd1ed0917db19586ec16
    Image ID:           docker://sha256:0ea0451cdf39f0c7c5953a0c7e5b310733a160aff6baff6c67ee4c0cca64a8ce
    Port:
    Limits:
      memory:   512Mi
    Requests:
      memory:           512Mi
    State:              Running
      Started:          Sat, 01 Oct 2016 10:20:08 +0200
    Ready:              True
    Restart Count:      0
    Liveness:           http-get http://:8080/login delay=120s timeout=3s period=10s #success=1 #failure=3
    Readiness:          http-get http://:8080/login delay=3s timeout=3s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/lib/jenkins from jenkins-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from jenkins-token-ma07j (ro)
    Environment Variables:
      JENKINS_PASSWORD:                 password
      KUBERNETES_MASTER:                https://kubernetes.default:443
      KUBERNETES_TRUST_CERTIFICATES:    true
      JNLP_SERVICE_NAME:                jenkins-jnlp
Conditions:
  Type          Status
  Initialized   True
  Ready         True
  PodScheduled  True
Volumes:
  jenkins-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  jenkins-token-ma07j:
    Type:       Secret (a volume populated by a Secret)
    SecretName: jenkins-token-ma07j
QoS Tier:       Burstable
No events.

Regardless of the above role bindings the serviceaccount does still not have the proper rights:
 
oc adm policy who-can edit buildconfigs
Namespace: pipelines
Verb:      edit
Resource:  buildconfigs

I have tried to "grant" the edit rights directly:
oc adm policy add-role-to-user edit system:serviceaccount:pipelines:jenkins

But without any success.

If I grant the jenkins serviceaccount cluster admin rights:

oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:pipelines:jenkins

Then it of course gets the edit rights. Then also the web-console gets updated with the stages from executing the pipelines.

So I am a little puzzled to why the rights are not granted as they should be.

Best regards
Lars Milland

**Comment by bparees** [comment]
Thanks, that's helpful output. @deads2k @liggitt any ideas on why these
permissions don't seem to be working?

Ben Parees | OpenShift

**Comment by liggitt** [comment]
"oc adm policy who-can edit buildconfigs" is the wrong check. "edit"
isn't a normal API verb. Try with "create" or "update". Based on the
role bindings, I expect the service account will show it does have
edit permissions. Are you seeing authorization failures from the
Jenkins pod?

The reason the "who-can" query showed that a cluster admin could
perform the "edit" action is because cluster admins can perform *any*
action on *any* resource. It would also answer affirmatively for
"who-can educate dolphins"

**Comment by liggitt** [comment]
@jimmidyson, is it possible to capture the server response for the forbidden errors? The message returned contains useful info that would help debug

**Comment by jimmidyson** [comment]
Create a new logger in Jenkins via the Jenkins configuration pages for okhttp & io.fabric8, set to level ALL & you should see a full trace of requests.

**Comment by liggitt** [comment]
@LarsMilland a couple other things to check:

1. see who is allowed to modify jenkinspipeline builds:
    ```
oc policy who-can update builds
oc policy who-can update buildconfigs
oc policy who-can create builds/jenkinspipeline
```

2. try to edit the buildconfig or build as the service account and see what errors are produced:
```
oc annotate bc/sample-pipeline foo=bar --as=system:serviceaccount:$(oc project -q):jenkins
oc annotate build/sample-pipeline-<existing-build-number> foo=bar --as=system:serviceaccount:$(oc project -q):jenkins
```

**Comment by LarsMilland** [comment]
Hi

It spells out like this:

The resources in the namespace with the Jenkins pod have been granted update rights to "builds" and "buildconfigs", through the role binding created through use of the template I would guess.

So the command:
oc policy who-can update builds
oc policy who-can update buildconfigs

responds like this:
Namespace: pipelines
Verb:      update
Resource:  builds/buildconfigs

Users:  ...
        system:serviceaccount:pipelines:jenkins



but for the "create" rights on the "builds/jenkinspipeline"

oc policy who-can create builds/jenkinspipeline

only the cluster-admin users and groups are reported, as they would have access to everything as I now understand.

then when trying the annotate command on bc/sample-pipeline as the serviceaccount I am told that the build strategy of JenkinsPipeline is not allowed:

oc annotate bc/sample-pipeline foo=bar --as=system:serviceaccount:$(oc project -q):jenkins
Error from server: buildconfigs "sample-pipeline" is forbidden: build strategy JenkinsPipeline is not allowed
 
same goes with trying to annotate the the specific build instance of one of the pipeline executions.

These annotation are both allowed with the cluster-admin role granted to the jenkins serviceaccount.

Best regards
Lars Milland

**Comment by bparees** [comment]
Is this a cluster that was upgraded from an earlier version?  Did you run
the reconcile roles command?

Ben Parees | OpenShift

**Comment by LarsMilland** [comment]
Hi

Thank you for all the help explaining where things could be wrong in this case.

It was exactly the case the cluster was an upgraded one from version OpenShift Origin 1.2.0 to version 1.3.0.

I had not run the reconciling cluster-roles and cluster-role-bindings. I have now, and the Jenkins pipeline builds now runs with their stages state changes updating to the web-console.

Best regards
Lars Milland

**Comment by jimmidyson** [comment]
Ah that's great - was trying to recreate this earlier but couldn't. Thanks @bparees!

**Comment by sudhirpandey** [comment]
We are having the same issue and we too upgraded the cluster from 1.2.0 to 1.3.0 
we did how ever ran
```
adm policy reconcile-cluster-roles \
    --additive-only=true \
    --confirm
```

and this 
```
oadm policy reconcile-cluster-role-bindings \
    --exclude-groups=system:authenticated \
    --exclude-groups=system:authenticated:oauth \
    --exclude-groups=system:unauthenticated \
    --exclude-users=system:anonymous \
    --additive-only=true \
    --confirm
```

According to the upgrade manuals but stills we dont see build status on the web console
In the jenkins pod we do how ever see these logs

```
WARNING: Caught: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://kubernetes.default/oapi/v1/namespaces/ci/builds/app-pipeline-2. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://kubernetes.default/oapi/v1/namespaces/ci/builds/app-pipeline-2. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked
```

Are we missing any thing while reconciling the cluster-roles and cluster-role bindings.

**Comment by bparees** [comment]
are you sure your jenkins pod is running under the jenkins service account?

**Comment by sudhirpandey** [comment]
yes the jenkins pod running seems to be under jenkins service account of same project

```
  restartPolicy: Always
  securityContext:
    fsGroup: 1000060000
    seLinuxOptions:
      level: s0:c8,c2
  serviceAccount: jenkins
  serviceAccountName: jenkins
```

**Comment by sudhirpandey** [comment]
Besides i am trying a cross project build via jenkins /pipeline being in third project..
project ci=> has jenkins
project dev => to build the app 
project test => to deploy the app

in project dev => ci/jenkins has edit role
in project test => ci/jenkins has edit role

The builds and pipleine go through and does what needs to be done.. only the web-console is not updated with status.

**Comment by sudhirpandey** [comment]
as said in this thread,.. we explicitly need to do this for this to be working..
`oadm policy reconcile-cluster-role-bindings --confirm` 
So i the docs might need update 
https://docs.openshift.org/latest/install_config/upgrading/manual_upgrades.html

**Comment by bparees** [comment]
@deads2k we're having a number of users running into pipeline/buildconfig permission issues when upgrading clusters, sounds like the reconcile roles instructions may need a review. (see https://github.com/openshift/origin/issues/11170#issuecomment-257268191)

**Comment by deads2k** [comment]
> @deads2k we're having a number of users running into pipeline/buildconfig permission issues when upgrading clusters, sounds like the reconcile roles instructions may need a review. (see #11170 (comment))

@liggitt looks like a role was bound to `system:authenticated` and the default instructions say to exclude anything bound to that user from reconciliation.  Role was bound here https://github.com/openshift/origin/blame/master/pkg/cmd/server/bootstrappolicy/policy.go#L974 in this pull https://github.com/openshift/origin/pull/8693 .

Shall we reconsider the default excludes and do it based on annotation like we've done with roles?

**Comment by deads2k** [comment]
@bparees It would be possible add an annotation to a role that indicates that reconciliation should not add additional bindings.  Doing this would allow this feature to work out of the box.  @liggitt feels strongly that this is the wrong approach and that instead we should require users (or ansible) to understand any new role we want bound to all subjects and require them to run an additional step for those new roles (that they know by name).

Assigning to @liggitt.

**Comment by pweil-** [comment]
bump @liggitt still a blocker for 1.4 and low enough risk to get in by Friday?

**Comment by pweil-** [comment]
@deads2k opinions on blocker status/risk here?

**Comment by deads2k** [comment]
> @deads2k opinions on blocker status/risk here?

One of those rare times we're not aligned.  As I understand @liggitt's position, we'll ship with new configs working out of the box and old configs broken out of the box unless they're using the ansible installer.  Makes this non-blocking, but @liggitt should probably make an issue against ansible and followup with @sdodson .

**Comment by sdodson** [comment]
@deads2k Can you give us a one liner to fix that particular permission? We can add that to the 1.4 upgrade steps as a workaround. CC: @dgoodwin

**Comment by liggitt** [comment]
Reconcile the bindings for the Jenkins pipeline role without excluding anonymous users:

oadm policy reconcile-cluster-rolebindings system:build-strategy-jenkinspipeline --confirm

**Comment by dgoodwin** [comment]
Am I correct that this requires first checking that the jenkins template has been used, otherwise the above will fail?

Does the --confirm imply interaction with the user?

**Comment by liggitt** [comment]
No, it can be done immediately after the normal role reconciliation, prior to anything template related

Reconcile operations default to dry runs. --confirm makes it take effect

**Comment by dgoodwin** [comment]
Thanks that will save me some time.

**Comment by pweil-** [comment]
moving to p2 based on the work around in the installer.  Please reset if I've jumped the gun

**Comment by jwforres** [comment]
Removing component/web from this since there is nothing to be done on the console side.

**Comment by liggitt** [comment]
fixed in https://github.com/openshift/openshift-ansible/issues/2777

**Comment by talzi** [comment]
hi,

i am getting similar issue.
I created new jenkins image (Added more plugins), create images stream under openshift project and deployed it using jenkins ephemeral template.
I am now trying to run simple pipeline but it is stuck, not even starting, job is not created in Jenkins
what am i missing?
getting following errors in the  pod's log

```
Caused by: java.io.IOException: Unexpected response code for CONNECT: 504
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:329)
	at okhttp3.internal.connection.RealConnection.buildTunneledConnection(RealConnection.java:155)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:111)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:64)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:541)
```

thanks
