### ISSUE TITLE
tito builds don't leave _output hanging around

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#11184]
a tito build does ~40 minutes of useful work, much of which leaves artifacts in _output ... we don't want to get rid of that

**Comment by sdodson** [comment]
RPM builds always clean up after themselves. I think we should add whatever you want to keep from _output into an RPM and then whatever you want can be installed from the resultant RPM.

**Comment by stevekuznetsov** [comment]
Understood. @sdodson what is preferable -- using Origin's `make release` target to generate the binaries, etc, and having the `tito` build simply consume them, instead of building again, or doing as you suggest and feeding the output back into the system through an RPM?

**Comment by stevekuznetsov** [comment]
Issue with `tito`.
