### ISSUE TITLE
Web console seems to transfer to private service IP (AWS)

### ISSUE THREAD

**Issue by lilnate22** [openshift/origin#11185]
Openshift webconsole seems to be fixed on private IP rather than public (or all for that matter) on AWS using RHEL-7.2 AMI

##### Version
[provide output of the `openshift version` or `oc version` command]
kubernetes v1.4.0-beta.3+d19513f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://{**MY PRIVATE SERVER IP**}:8443
openshift v1.4.0-alpha.0+ffdeb1b
kubernetes v1.4.0-beta.3+d19513f

##### Steps To Reproduce
1. [step 1]
start a ec2 instance in AWS, install docker, follow openshift install guide on: 
https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container

2. [step 2] follow the final instruction:
OpenShift Origin includes a web console which helps you visualize your applications and perform common creation and management actions. You can use the test user we created above to log in to the console via https://<server>:8443/console.

##### Current Result
webconsole should be opened and functional
![image](https://cloud.githubusercontent.com/assets/882236/19017447/949ce094-8807-11e6-9283-1258e81b0ea1.png)

##### Expected Result
Origin website should be working as expected 
##### Additional Information
Looking at the web console (the js console in browsers) i can see its attempting to hit the private IP, rather than the public one. 

is there away to specify openshift to use public?

**Comment by liggitt** [comment]
Add the `--public-master=https://<public-ip>:8443` arg when starting the master

**Comment by lilnate22** [comment]
sorry @liggitt getting a bit of error in logs when i run this: 

```
sudo docker run  -d --name "origin" \
        --privileged --pid=host --net=host \
        -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw \
        -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes \
        openshift/origin start --public-master=https://{MY_PUBLIC_AWS_IP}:8443
```


when i run it, the docker container starts up, and then crashes:

```
002 04:00:14.759127    2895 manager.go:290] Recovery completed
I1002 04:00:14.976875    2895 node.go:498] Started Kubernetes Proxy on 0.0.0.0
I1002 04:00:15.077167    2895 node.go:358] Starting DNS on {MY_PUBLIC_IP}:53
I1002 04:00:15.077455    2895 logs.go:41] skydns: ready for queries on cluster.local. for tcp://54.70.198.222:53 [rcache 0]
I1002 04:00:15.077483    2895 logs.go:41] skydns: ready for queries on cluster.local. for udp://54.70.198.222:53 [rcache 0]
I1002 04:00:15.077585    2895 logs.go:41] skydns: listen udp {MY_PUBLIC_IP}:53: bind: cannot assign requested address
```

Its a brand spanking new ec2 instance, nothing running on port 53.

**Comment by liggitt** [comment]
@lilnate22 that looks like a bug in the [node DNS startup code](https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/node_config.go#L298-L300), which is trying to bind a DNS listener to the public IP:
```
if len(options.DNSIP) > 0 {
    dnsConfig.DnsAddr = options.DNSIP + ":53"
}
```

@smarterclayton, the node probably shouldn't use DNSIP as the bind address

**Comment by liggitt** [comment]
@lilnate22 you can change --public-master to be your public AWS DNS hostname instead (http://ec2-xx-xx-xx-xx.compute-1.amazonaws.com) as a workaround

**Comment by liggitt** [comment]
@lilnate22 can you confirm --public-master with the external DNS name works for you? I opened #11194 to address the IP/DNS binding bug

**Comment by lilnate22** [comment]
yes this worked @liggitt. Thanks for the help!

**Comment by rajc** [comment]
i have ran this docker command and use the DNS. i am able to access the console via browser. 
however, when i try to deploy an example ruby app. i get a build failure due to OC unable to push the image.  
`ruby-ex-1   Source    Git       Failed (ExceededRetryTimeout)`
'WARNING: No Docker registry has been configured with the server. Automatic builds and deployments may not function.'

i did add `INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'`  to my docker config and then restarted docker. 

do i need to map ports?
