### ISSUE TITLE
`oadm manage-node --evacuate` doesn't know about replicasets or daemonsets

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#11193]
`oadm manage-node --evacuate` avoids deleting "unmanaged" pods that will not be automatically recreated, but does not pay attention to pods managed by replicasets or daemonsets.

If such pods exist, they get lumped in with one-off pods and require --force to delete.

**Comment by mfojtik** [comment]
@kargakis i think for making this work, we need to have ownership reference, right?

**Comment by kargakis** [comment]
For `manage-node` to work we just need to list all replica sets and daemon sets, and use their selectors to filter out pods. Eventually, we should switch to owner references but it's not required for this to be fixed.

**Comment by mfojtik** [comment]
@kargakis ok
