### ISSUE TITLE
Service switch - connection refused

### ISSUE THREAD

**Issue by mvlach** [openshift/origin#11190]
I have two services - service-a and service-b. I have the service called service which have selectors app: service-a deploymentconfig: service-a.

When edit the service and change selectors to service-b I get the connection problems on the client side.
##### Version

oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
##### Steps To Reproduce
1. create the same service (A,B)
2. create service which routes to the service A resp. B (based on selectors)
3. run monitoring tool (we loggin the client javascript error to kibana)
4. edit the service and change selectors
##### Current Result

Connection broken - clients reports Network problem
##### Expected Result

No one know about the service swtiching

**Comment by knobunc** [comment]
Can you please post the output from 'oc get endpoints <servicename>'  after the edit.

**Comment by mvlach** [comment]
current settings is 

```
service                 10.1.0.5:8080,10.1.0.5:8181     21d
service-a               10.1.0.13:8080,10.1.0.13:8181   14d
service-b               10.1.0.5:8080,10.1.0.5:8181     15d
```
