### ISSUE TITLE
Accessing remote cluster via SOCKS proxy?

### ISSUE THREAD

**Issue by jo-sm** [openshift/origin#11208]
I'm running a cluster on a private VM that can't be accessed without a SOCKS proxy locally, but there doesn't appear to be an option to connect through a proxy, and I can't see anything in the documentation about this. Is is possible to connect to a remote server over a SOCKS proxy or are there workarounds to deal with this case?

The only way I know how to handle it is to do a LocalForward in my ssh config to the remote `8443` port, but I'd prefer to be able to access it via the same IP that I access the console in the browser.

**Comment by enj** [comment]
So we don't support SOCKS proxies with `oc`, only HTTP proxies via the `HTTPS_PROXY` environment variable.  You may be able to do something like [this](http://unix.stackexchange.com/questions/71481/use-socks-proxy-for-commands-in-terminal) but I did not have luck with it locally.  Adding SOCKS proxy support would have to be an upstream PR to k8s.

**Comment by eidottermihi** [comment]
You could use an HTTP-to-SOCKS proxy like https://github.com/oyyd/http-proxy-to-socks to proxy http traffic to your SOCKS proxy, for example:

```bash
# startup http/s to socks proxy on port 9999
hpts -s yoursocksproxyhost:yoursocksproxyport -p 9999
# set http/s_proxy environment variables
export http_proxy=http://localhost:9999
export https_proxy=http://localhost:9999
# start using oc
oc login your-cluster
```

**Comment by albertogalan** [comment]
You can use vpn over ssh with sshuttle 

> sshuttle -r yourhostip 0.0.0.0/0
> nmap your-cluster-ip -p 8443  # check that you can access to your clusterr-ip port  
>oc login your-cluster

https://github.com/sshuttle/sshuttle
