### ISSUE TITLE
oc cluster fails to install metrics with ocp 3.3

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#11207]
When using `--metrics` with the OCP version, metrics deployment fails since the `ose-metrics-deployer` image doesn't exist:

```
Failed to pull image "registry.access.redhat.com/openshift3/ose-metrics-deployer:v3.3.0.32": image pull failed for registry.access.redhat.com/openshift3/ose-metrics-deployer:v3.3.0.32, this may be because there are no credentials on this request.  details: (unknown: Not Found)
```
##### Version

oc v3.3.0.32
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
##### Steps To Reproduce

```
oc cluster up --image=registry.access.redhat.com/openshift3/ose --metrics
```

**Comment by csrwng** [comment]
@sdodson @mwringe is there any chance the metrics deployer can be tagged in the ose registry? otherwise we would have to use the origin version (maybe with the :latest tag).

**Comment by mwringe** [comment]
@csrwng it is tagged in the OSE registry, and it should automatically be the right version which is specified in the template which is used to deploy metrics.

Eg: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.3/infrastructure-templates/enterprise/metrics-deployer.yaml#L104

**Comment by sdodson** [comment]
@mwringe but they're not the same tags as the ose version ie: 'ose:v3.3.0.35' versus 'metrics-deployer:3.3.0'. While the installer does handle this for the most part I think I'm in favor of using the same tags for both, this would allow me to implement the version matching you'd requested for origin metrics in the installer without having to special case it for OSE where the tags are different.

If we were to do this it'd mean we'd need to tag metrics and logging components on each OSE patch even if things weren't actually changed and we'd also be expected to upgrade metrics and logging components each time an upgrade of OSE is performed, again even if the actual images hadn't changed.

**Comment by mwringe** [comment]
The logic behind this was due to the the metrics components having a separate project and have a separate lifecycle than OpenShift. So when OpenShift v3.3.0.35 is built, the metrics components are not also built at that time and so we don't have a metrics component with that specific build number.

> If we were to do this it'd mean we'd need to tag metrics and logging components on each OSE patch even if things weren't actually changed and we'd also be expected to upgrade metrics and logging components each time an upgrade of OSE is performed, again even if the actual images hadn't changed.

That might work, but it does bring up an interesting questions where if we need to push out new metrics images to fix an issue. In that case we may need to also do a release for OpenShift since they are meant to be kept in sync.

I am all in favour of improving how we currently handle things.

I think the original idea was to have an alias tag for the metrics tags so that the vX.Y.Z would always correspond to the latest metrics image meant for OpenShift vX.Y.Z.a.b.c, but I don't think we really have it setup properly this way.

**Comment by csrwng** [comment]
@sdodson @mwringe did we decide how to proceed? If it will be a while before we switch the tagging for the metrics deployer image, I think we need to fix 'cluster up' to use the proper template.

**Comment by mwringe** [comment]
@csrwng 'cluster up' definitely needs to fix this while we figure out if we can handle tagging in a better manner

**Comment by csrwng** [comment]
@mwringe thx, will do

**Comment by jcantrill** [comment]
It was my understanding that logging and metrics would/could flow on a different cadence then OSE and it's conceivable that you might need to deploy logging separately.  To simplify things, it seems reasonable that we  retag logging and metrics images when you re-release OSE.  To my knowledge, however, the only way we provide these images now is to release OSE; there is no process to release them separately so it seems tagging them to match is appropriate.

**Comment by sosiouxme** [comment]
Pretty sure we don't want to rebuild all the images every time there's a new OpenShift build. Seems to me this could go one of two ways:

1. retag shipped images to match each time there's a new version of OpenShift
2. have `oc cluster up` only use the x.y.z of the version, as that is what gets shipped

**Comment by bparees** [comment]
@csrwng @coreydaley is there a PR associated w/ this issue?

**Comment by coreydaley** [comment]
@bparees not at this time.  We have not heard back after the meeting that we had to determine a strategy to fix this issue, which was suggested to be tagging the images correctly.

**Comment by bparees** [comment]
@coreydaley who are we waiting to hear back from?  should this be assigned to the metrics team to fix the image tagging?

**Comment by sdodson** [comment]
Productization has made the tagging changes in our most recent builds but that broke some of the existing process. The build we're doing today should have both the new tags 'v3.4.0.x' and old '3.4.0' easing the transition. So lets test with today's build.

**Comment by csrwng** [comment]
@tdawson assigning to you ... please close when the latest changes are in. Thanks!

**Comment by tdawson** [comment]
logging-deployer and metrics-deployer images are now tagged with both 3.4.0 and v3.4.0.25 (or whatever is the latest ocp version) in both pulp and registry.ops.
This solves the problem for both "oc cluster up" and older scripts and/or ways of pulling the images.
