### ISSUE TITLE
"etcd cluster is unavailable or misconfigured" flake

### ISSUE THREAD

**Issue by jupierce** [openshift/origin#11234]
Possible flake while running CI tests for OpenShift jenkins-plugin:
https://ci.openshift.redhat.com/jenkins/job/test-openshift-pipeline-plugin/49/console

```
Wed Oct  5 14:22:15 EDT 2016
[INFO] Installing the registry
clusterrolebinding "registry-registry-role" created
deploymentconfig "docker-registry" created
Error from server: error when creating "STDIN": client: etcd member https://172.18.10.242:4001 has no leader
Error from server: error when creating "STDIN": Internal error occurred: failed to allocate a serviceIP: client: etcd cluster is unavailable or misconfigured; error #0: client: etcd member https://172.18.10.242:4001 has no leader

[ERROR] PID 12858: hack/util.sh:457: `oc create -f -` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/util.sh:457: `oc create -f -`
[INFO] 		  2: test/extended/setup.sh:123: install_registry
[INFO] 		  3: test/extended/core.sh:11: os::test::extended::setup
[INFO]   Exiting with code 1.
```

fyi @gabemontero

**Comment by liggitt** [comment]
that's impressive for a non-clustered etcd

**Comment by gabemontero** [comment]
Just in case, to clarify, we are running origin extended tests, and things
fail during extended test setup before we can execute the jenkins extended
test.

**Comment by liggitt** [comment]
oh, in the jenkins setup for this job, are we setting up the cluster to put etcd data on a ramdisk?

**Comment by gabemontero** [comment]
Hm, first I heard of that.

The job currently launches the extended test in this fashion:

vagrant test-origin --extended "core(openshift pipeline plugin)" -d
--skip-check --skip-image-cleanup --image-registry
ci.dev.openshift.redhat.com:5000

just looked at our extended test job for builds, and I see this prior to
its extended test launch:

# use a ramdisk for etcd storage
vagrant ssh -c "sudo mkdir /tmp || true"
vagrant ssh -c "sudo mount -t tmpfs -o size=2048m tmpfs /tmp"

Sounds like what you are referring to.  I've added those lines to the job
for testing the jenkins plugin.  We'll kick off another run in @jupierce's
PR.

I also see the extended build test job does not leverage the
--image-registry parameter, but I'm going to leave that in for now.  One
moving part at a time.

thanks!

**Comment by jupierce** [comment]
I have not seen this again since Gabe made the change. Thanks @liggitt !
