### ISSUE TITLE
`oc cluster up` image layer math is weird

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#11243]
It has been a while since I learned division but these percentages seem off:

```
-- Checking for openshift/origin:v1.4.0-alpha.0 image ... 
   Pulling image openshift/origin:v1.4.0-alpha.0
   Pulled 1/3 layers, 36% complete
   Pulled 2/3 layers, 77% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
``

**Comment by liggitt** [comment]
Not all images are the same size. Also, some of the next layer could have completed (layers pull in parallel)

**Comment by stevekuznetsov** [comment]
Both of those facts mean that perhaps the current display isn't the best way to show the end user how data is being downloaded, definitely a little confusing for anyone paying attention to what `oc cluster up` is printing. Meh.

**Comment by liggitt** [comment]
the message prints every 10 seconds, and whenever a layer completes.  If you're fortunate to have your pull complete before you get to the 10 second mark and see multiple percentages progressing, your confusion is brief

**Comment by stevekuznetsov** [comment]
Fair enough
