### ISSUE TITLE
oadm prune does not remove empty ImageStreams

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#11250]
I have an empty image stream (ie. wrong spec, error on the other side, whatever), when I'm calling `oadm prune images` I'm expecting this IS be removed (it falls into passed arguments). But since it's not pointing to any image it is not. 
Now the question is how to remove those? Should we have additional `oadm prune imagestreams` command or `oadm prune image` should be more smart? 
I think I'd prefer the former, @smarterclayton @miminar wdyt?

**Comment by soltysh** [comment]
I found it during testing #11249

**Comment by miminar** [comment]
I wouldn't remove the empty IS by default. Only when explicitly requested with some flag.

Consider a user running `oc create imagestream myis` (which is initially empty) and 1 minute later a scheduled job to prune images is run. What a surprise - the `myis` doesn't exist anymore.

Also during an image push. Image stream needs to be created before image can be tagged into it. Those are two separate API calls. Again, there may be race conditions when prune command runs periodically.

**Comment by mfojtik** [comment]
@soltysh I agree with @miminar that if the image stream is empty and it is not occupying an extra storage, we don't need to prune it. I can also create image stream and have pipeline that takes week to complete a populate that image with any data.

**Comment by soltysh** [comment]
I feel convinced, closing.
