### ISSUE TITLE
Unable to log into exposed registry

### ISSUE THREAD

**Issue by stobias123** [openshift/origin#11267]
I’m unable to push images to it due to authentication problems it seems. I’ve done some looking around and it seems very similar to this issue on bugzilla - https://bugzilla.redhat.com/show_bug.cgi?id=1341861 

Some context, our registry is the default, insecure registry deployed with the advanced install. It’s been exposed following the docs here. 

##### Version
```
[admin@openshift-master ~]$ oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift-master.example.com:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
1. Expose *insecure* registry following [this doc](https://docs.openshift.org/latest/install_config/registry/securing_and_exposing_registry.html#access-insecure-registry-by-exposing-route)
2. Get login token with `oc whoami -t`  
3. Attempt to log in to registry as described at above link 

##### Current Result
```
admin@workstation ~/websphere_docker> docker login -p MnhDIF9xpQhG2lIatSzmFGbJAwKGqX8a7OkbnZNXNH4 -e unused -u unused registry.cloud.example.com                                                   1
	Error response from daemon: Unexpected status code [503] : <html>
		... some style code removed here ... 
	  <body>
		<div>
		  <h1>Application is not available</h1>
		  <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>
		</div>
	  </body>
	</html>
admin@workstation ~/websphere_docker> docker push registry.cloud.example.com/toby/websphere:allocator                                                                                               
The push refers to a repository [registry.cloud.example.com/toby/websphere]
... some image layers here...
c8a75145fcc4: Waiting 
unauthorized: authentication required
```

##### Expected Result
Successul log in. Sucessful image push.

##### Additional Information
Docker opts list the registry as an insecure registry. (I've tried with IP as well as hostname)
```
	admin@workstation ~> grep OPTIONS /etc/sysconfig/docker
	OPTIONS='--insecure-registry registry.cloud.example.com:5000 --insecure-registry registry.cloud.example.com --selinux-enabled --log-driver=journald'
```
Here's my registry service
```
	[admin@openshift-master ~]$ oc get svc
	NAME               CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
	docker-registry    172.30.94.152    <none>        5000/TCP                  15d
	kubernetes         172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     15d
	registry-console   172.30.65.165    <none>        9000/TCP                  14d
	router             172.30.196.214   <none>        80/TCP,443/TCP,1936/TCP   15d
```

Here's the route for my registry..
```
	[admin@openshift-master ~]$ oc get route docker-registry -o yaml
	apiVersion: v1
	kind: Route
	metadata:
	  creationTimestamp: 2016-09-28T20:34:43Z
	  labels:
		docker-registry: default
	  name: docker-registry
	  namespace: default
	  resourceVersion: "417723"
	  selfLink: /oapi/v1/namespaces/default/routes/docker-registry
	  uid: fd0b280e-85ba-11e6-9d37-0050568b4a96
	spec:
	  host: registry.cloud.example.com
	  port:
		targetPort: 5000-tcp
	  to:
		kind: Service
		name: docker-registry
		weight: 100
	status:
	  ingress:
	  - conditions:
		- lastTransitionTime: 2016-09-28T20:34:43Z
		  status: "True"
		  type: Admitted
		host: registry.cloud.example.com
		routerName: router
```
I read through [issue 11262](https://github.com/openshift/origin/issues/11262) and though I should add this... when I curl the service IP directly from a cluster member, I get an error as well.
```
[admin@openshift-master ~]$ curl https://172.30.94.152:5000/v0
curl: (35) SSL received a record that exceeded the maximum permissible length.
```

**Comment by BenHall** [comment]
When deploying, did you have KUBE_CONFIG set? I noticed I needed to set the config so it had the correct keys to deploy.

For example:
`oc adm registry -n default --config=/openshift.local.config/master/admin.kubeconfig`

**Comment by miminar** [comment]
@stobias123 If I'm not mistaken, your router listens on port 80. That means, you shouldn't suffix your registry name with `:5000`.

**Comment by stobias123** [comment]
@miminar The options line also listed it without the port. However, I've removed the line including port 5000 and receive the same result.

**Comment by stobias123** [comment]
@BenHall I deployed registry following  [origin docs ].  (https://docs.openshift.org/latest/install_config/registry/deploy_registry_existing_clusters.html)
```oadm registry --config=admin.kubeconfig \
    --service-account=registry  ```
Is there a way to list the current registry config before making any changes? I can't find it in the `oc adm --help`

Registry works within the cluster, and nodes can push new images up after being built. I run into an issue when I try to expose the registry, and push to it from an external machine.

**Comment by miminar** [comment]
> Is there a way to list the current registry config before making any changes?

@stobias123 Try `oadm registry -o json`.

> Registry works within the cluster, and nodes can push new images up after being built.

Can you login/push/pull using both internal IP (`172.30.94.152`) and domain name (`registry.cloud.example.com`) from within the cluster? So the only problem is connection from outside?

I'll try this out tomorrow and see if I can reproduce.

**Comment by stobias123** [comment]
@miminar See below for login results within the cluster. 

```[admin@openshift-master ~]$ sudo docker login -p pqNy2onGvCieUs_PexlxnINnbp8kzd9ammnjgdevr0c -e unused -u unused 172.30.94.152
Error response from daemon: invalid registry endpoint "http://172.30.94.152/v0/". HTTPS attempt: unable to ping registry endpoint https://172.30.94.152/v0/
v2 ping attempt failed with error: Get https://172.30.94.152/v2/: dial tcp 172.30.94.152:443: getsockopt: no route to host
 v1 ping attempt failed with error: Get https://172.30.94.152/v1/_ping: dial tcp 172.30.94.152:443: getsockopt: no route to host. HTTP attempt: unable to ping registry endpoint http://172.30.94.152/v0/
v2 ping attempt failed with error: Get http://172.30.94.152/v2/: dial tcp 172.30.94.152:80: getsockopt: no route to host
 v1 ping attempt failed with error: Get http://172.30.94.152/v1/_ping: dial tcp 172.30.94.152:80: getsockopt: no route to host
```
Using DNS name...
```[admin@openshift-master ~]$ sudo docker login -p pqNy2onGvCieUs_PexlxnINnbp8kzd9ammnjgdevr0c -e unused -u unused registry.cloud.example.com
....shortened output...
      <h1>Application is not available</h1>
      <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>
    </div>
  </body>
</html>
```
I realized that since we're using proxy in docker options, there might be a problem there. After adding `registry.cloud.example.com` to the `NO_PROXY` line in `/etc/sysconfig/docker`.  I got output more similar to using internal IP.
```
 [admin@openshift-master ~]$ sudo docker login -p pqNy2onGvCieUs_PexlxnINnbp8kzd9ammnjgdevr0c -e unused -u unused registry.cloud.example.com
Error response from daemon: invalid registry endpoint "http://registry.cloud.example.com/v0/". HTTPS attempt: unable to ping registry endpoint https://registry.cloud.example.com/v0/
v2 ping attempt failed with error: Get https://registry.cloud.example.com/v2/: dial tcp 10.100.23.173:443: getsockopt: connection refused
```

Adding `registry.cloud.example.com` to the `NO_PROXY` line on a workstation not part of the cluster produced the same results as before; html page with "app not serving requests"

**Comment by miminar** [comment]
@stobias123 The correct endpoint for your registry from inside of cluster is `172.30.94.152:5000`. Be sure to mark it as insecure if it is not secured:

```
--insecure-registry=172.30.94.152:5000 --insecure-registry=registry.cloud.example.com
```
Have you exposed the registry according to https://docs.openshift.org/latest/install_config/registry/securing_and_exposing_registry.html#exposing-the-registry?

**Comment by stobias123** [comment]
@miminar I was able to use the registry from inside the cluster using the above listed port. 

The registry was exposed following the doc listed above, but I was still having trouble with an _insecure registry_.

I ended up securing the registry today, and everything works fine as long as I copy the ca.crt to clients.

**Comment by miminar** [comment]
Glad it works for you, exposing insecure registry doesn't work ATM. But we're working on it https://github.com/openshift/origin/pull/11391. Closing.
