### ISSUE TITLE
networking test flake "certificate is valid for nettest-node-1, 172.17.0.3, not nettest-node-2"

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#11274]
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/6833:

`Oct  7 17:38:40.311: INFO: Error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc [oc logs --namespace=extended-test-get-flows-57ect-zuw9v --config=/tmp/extended-test-get-flows-57ect-zuw9v-user.kubeconfig flow-checklhsi6] []   Error from server: Get https://nettest-node-2:10250/containerLogs/extended-test-get-flows-57ect-zuw9v/flow-checklhsi6/flow-check: x509: certificate is valid for nettest-node-1, 172.17.0.3, not nettest-node-2`

This is the same symptom as #11025 but presumably not the same cause. This was in a post-#11061 tree, so it may actually be caused by a dind deployment bug this time...

@marun

**Comment by liggitt** [comment]
That's… concerning
