### ISSUE TITLE
RFE: Route quota/limits

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#11276]
The routes section seems to be rather unrestricted. 

It'd be nice if we could set a limit on how many routes a user can have per project, and possibly a restriction on route names (similar to the project name restriction) so users couldn't select possible trademarked/offensive words etc.

**Comment by knobunc** [comment]
For the restriction part, we are tracking that feature request with:
  https://trello.com/c/bqKQiLsx/5-restrict-routes-with-blacklist-ingress (and https://bugzilla.redhat.com/show_bug.cgi?id=1151582)

For the limits, you can limit the number of routes with quotas:
  https://docs.openshift.com/enterprise/3.2/dev_guide/compute_resources.html

**Comment by andrewklau** [comment]
@knobunc not seeing any route quotas/limits in the docs
