### ISSUE TITLE
oc adm metrics? Use adm to install heapster

### ISSUE THREAD

**Issue by BenHall** [openshift/origin#11282]
I really like the router/registry CLI extensions to `oc adm`. I'm surprised that metrics wasn't included as an option and instead looks like there are a number of steps involved for users. 

Is there a reason I have missed?

**Comment by stevekuznetsov** [comment]
I think the current target is to contain the logic for deploying metrics and logging in Ansible playbooks. I believe this is to take advantage of the idempotency guarantees, etc, that we gain from Ansible as well as the synergy with other tasks cluster administrators will be making, many of which we see through Ansible as well. @smarterclayton will be able to give better insight.

**Comment by jcantrill** [comment]
In follow-up to @stevekuznetsov  comments, the current plan for administration of metrics is captured here: https://trello.com/c/piaWOfvB though to be honest, the original implementation of the task has morphed and it needs to be update.  Metrics administration will be done using Ansible (as that is our preferred administration tool). Moving forward, which will be realized in the not so distant future, this will replace the current metrics deployer.

**Comment by mwringe** [comment]
@smarterclayton is Ansible now going to be required to install and manage Origin? If not, why would we want to put all the metrics management into a tool which is not required by Origin itself?

**Comment by jcantrill** [comment]
closing as unlikely to move into 'oc adm' given the use of ansible
