### ISSUE TITLE
There was an error talking to AWS.

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#11292]
```
There was an error talking to AWS. The error message is shown below:

InsufficientInstanceCapacity => We currently do not have sufficient m4.xlarge capacity in the Availability Zone you requested (us-east-1d). Our system will be working on provisioning additional capacity. You can currently get m4.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1c, us-east-1e, us-east-1b.
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/6890/console

**Comment by stevekuznetsov** [comment]
The intent was for us to not have to have developers create issues for this type of issue... Hence that third bullet point in the bot response. I guess we need to rethink that?

**Comment by danmcp** [comment]
@stevekuznetsov No, the issue is still pretty pointless.

**Comment by kargakis** [comment]
```
If something else like CI system downtime or maintenance caused the job to fail, contact a member of the Team Project Committers group to trigger the job again.
```
Why is this necessary and can't be automated?

**Comment by stevekuznetsov** [comment]
> Why is this necessary

Because it hasn't been automated

> can't

It's probably possible using the AWS APIs.

> Why haven't we automated it?

Simple matter of bandwidth.
