### ISSUE TITLE
You should be able to specify environment variables for builds with jenkinsPipelineStrategy

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#11293]
Regular builds with `sourceStrategy` support adding *env* to parametrize the build and to allow you to reuse the same assembly script. https://docs.openshift.org/latest/dev_guide/builds.html#buildconfig-environment

We should be able to do the same for builds with `jenkinsPipelineStrategy`. This will allow you to have same parametrizable Jenkinsfile the same way you can share and parametrize assembly script.

*Env* should be available in [jenkinspipelinebuildstrategy](https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-jenkinspipelinebuildstrategy) the same way it is in [sourcebuildstrategy](https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-sourcebuildstrategy) and injected to the environment where Jenkinsfile is run.

**Comment by bparees** [comment]
converted to trello. https://trello.com/c/h6NSFQgk/1052-allow-env-variables-on-pipeline-buildconfigs
