### ISSUE TITLE
e2e tests fail with more recent versions of docker (1.12 etc) 

### ISSUE THREAD

**Issue by gnufied** [openshift/origin#11302]
##### Version
HEAD

##### Steps To Reproduce

e2e tests are failing to run with latest version of docker because they use following command:

```
docker tag -f blahxxxx
```

https://github.com/openshift/origin/blob/master/test/end-to-end/core.sh#L135

This flag is no longer available in newer versions of docker (as far as I can tell from version 1.12+). The flag was already deprecated in 1.10.

**Comment by stevekuznetsov** [comment]
We run this test many times a day with Docker 1.10.3 in our CI sever. Could you please provide:

```sh
$ oc version
$ docker version
```

And any other relevant details about your environment?

**Comment by gnufied** [comment]
```
~> docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

```
~> oc version
oc v1.4.0-alpha.0+88a2e30
kubernetes v1.4.0+776c994
features: Basic-Auth
Unable to connect to the server: x509: certificate signed by unknown authority
```

Ignore unable to connect error because I shutdown the server.   

So I narrowed it down further. `-f` flag has been deprecated in docker-1.10 as evident from:

```
─openshift/origin> docker tag -f
Warning: '-f' is deprecated, it will be removed soon. See usage.
docker: "tag" requires 2 arguments.
See 'docker tag --help'.

Usage:  docker tag [OPTIONS] IMAGE[:TAG] [REGISTRYHOST/][USERNAME/]NAME[:TAG]

Tag an image into a repository
```

And completely removed from docker 1.12.

**Comment by gnufied** [comment]
I am going to edit the issue to be more accurate. Sorry about it.
