### ISSUE TITLE
Document what 'all' maps to in oc get and oc delete.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#11301]
Using the magic `all` value in place of listing specific resource object types is poorly covered in the help strings for `oc get` and `oc delete`. There is one example in `oc delete` but nothing in `oc get`.

It should be better documented in help strings and possibly online documentation, including saying what `all` actually maps to, which at this point is supposedly buildconfigs, builds, imagestreams, deploymentconfigs, replicationcontrollers, routes, services, and pods. Where a user is able to easily find that I don't know. Likely buried deep in the code somewhere.

**Comment by juanvallejo** [comment]
Maybe we could dynamically retrieve the list of resources [from clientcmd/shortcut_restmapper.go]((https://github.com/openshift/origin/blob/master/pkg/cmd/util/clientcmd/shortcut_restmapper.go#L93) and display them somewhere in the usage output of these two commands (or maybe as a sub-section under `oc get`?)

**Comment by liggitt** [comment]
No API calls to display help.
