### ISSUE TITLE
Is kubernetes in our OpenShift support 'deploy' on Mesos?

### ISSUE THREAD

**Issue by guangxuli** [openshift/origin#11311]
Hi guys.
I know kubernetes  support 'delpoy' on Mesos,  Is kubernetes in our OpenShift version support this? the feedback from my team seems that it does not  supported this . I'm not sure, if no, can someone give some suggestion for support this function? thanks.

**Comment by danmcp** [comment]
Mesos is not currently an option for deployment of OpenShift.  You can track this RFE to see any updates on the subject:

https://bugzilla.redhat.com/show_bug.cgi?id=1383547

**Comment by getstek** [comment]
The RFE is set to 'Closed WONTFIX' without any detail. Is there a specific reason it won't be looked at?
