### ISSUE TITLE
Simplify evacuate code

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#11310]
Currently our `oadm manage-node --evacuate` code is filled with all sorts of controller checks to make sure we properly identify pods during node evacuation. We should ensure all controllers have `controllerRef` set (as proposed in https://github.com/kubernetes/kubernetes/issues/24946) to be able to have a generic code in the evacuation.

@mfojtik fyi

**Comment by mfojtik** [comment]
@soltysh the old servers will not have that annotation set, so we will always need to carry the "legacy" code in case not all pods respects that annotation.

**Comment by soltysh** [comment]
First we need to make sure ALL controllers set this annotation accordingly, once that is done we'll have to do version dependent logic. Since, old clusters won't have all the resources you were adding in your PR, either.

**Comment by smarterclayton** [comment]
We need to move people to using `drain` and deprecate and remove --evacuate.

**Comment by mfojtik** [comment]
@smarterclayton PR opened.
