### ISSUE TITLE
ImageStream references not resolved when user creates Build object through REST API

### ISSUE THREAD

**Issue by mmilata** [openshift/origin#11324]
Tried to directly (i.e. not by instantiating `BuildConfig`) create `Build` object for custom type build, with the builder image specified as ImageStreamTag (e.g. `my-ist:latest`). The created build pod is stuck in Pending state. Following event indicates that it's trying to use the ImageStreamTag name as a docker pullspec:
```
6m 13s 6 {kubelet localhost.localdomain} spec.containers{custom-build} Warning Failed  Failed to pull image "my-ist:latest": Error: image library/my-ist not found
```

##### Version
Built from today's git - 8f6030a36e51fabb7f894badfe2f14a2823e819f.

##### Steps To Reproduce
1. `oc create imagestream my-ist`
2. push tag to the imagestream
3. create build:

```
$ oc create -f -
apiVersion: v1
kind: Build
metadata:
  name: my-build
spec:
  strategy:
    customStrategy:
      from:
        kind: ImageStreamTag
        name: my-ist:latest
    type: Custom
```

##### Current Result

```
oc describe build my-build
Name:           my-build
Namespace:      default
Created:        37 seconds ago
Labels:         <none>
Annotations:    openshift.io/build.pod-name=my-build-build

Status:         Pending
Duration:       waiting for 37s
Build Pod:      my-build-build

Strategy:               Custom
Image Reference:        ImageStreamTag my-ist:latest
Empty Source:           no input source provided

Build trigger cause:    <unknown>

Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath                   Type            Reason          Message
  ---------     --------        -----   ----                            -------------                   --------        ------          -------
  37s           37s             1       {default-scheduler }                                            Normal          Scheduled       Successfully assigned my-build-build to localhost.localdomain
  35s           19s             2       {kubelet localhost.localdomain} spec.containers{custom-build}   Normal          Pulling         pulling image "my-ist:latest"
  33s           17s             2       {kubelet localhost.localdomain} spec.containers{custom-build}   Warning         Failed          Failed to pull image "my-ist:latest": Error: image library/my-ist not found
  33s           17s             2       {kubelet localhost.localdomain}                                 Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "custom-build" with ErrImagePull: "Error: image library/my-ist not found"

  32s   5s      2       {kubelet localhost.localdomain} spec.containers{custom-build}   Normal  BackOff         Back-off pulling image "my-ist:latest"
  32s   5s      2       {kubelet localhost.localdomain}                                 Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "custom-build" with ImagePullBackOff: "Back-off pulling image \"my-ist:latest\""
```

##### Expected Result

* Either the reference in `spec.strategy.customStrategy.from` is resolved to actual pullspec. I'm suspecting there's a reason the reference is resolved when BuildConfig is instantiated, though.
* Or the `Build` should be rejected as invalid.

##### Additional Information

* The image reference is resolved here: https://github.com/openshift/origin/blob/v1.4.0-alpha.0/pkg/build/generator/generator.go#L382
* The image name is used here, however nothing checks the `from` field type: https://github.com/openshift/origin/blob/v1.4.0-alpha.0/pkg/build/controller/strategy/custom.go#L24

**Comment by bparees** [comment]
@mmilata is this specific to custom strategy or is it a problem for any build object that uses an imagestream reference?

**Comment by mmilata** [comment]
Right, looking at the source it doesn't seem to be specific to custom strategy:
* `spec.strategy.dockerStrategy.from`: if kind is not `DockerImage` then the FROM image is not used
* `spec.strategy.sourceStrategy.from`, `spec.strategy.sourceStrategy.runtimeImage`: kind not checked, assumed to be `DockerImage`
* `spec.source.image[i].from`: kind not checked, assumed to be `DockerImage`

**Comment by php-coder** [comment]
> spec.strategy.sourceStrategy.from, spec.strategy.sourceStrategy.runtimeImage: kind not checked, assumed to be DockerImage 

For these cases we have a test: `test/extended/testdata/build-extended/bc-scripts-in-the-image.yaml` It uses `ImageStreamTag` for both elements and it works.

**Comment by mmilata** [comment]
@php-coder it works because it's a `BuildConfig`. Whenever you create a `Build` from `BuildConfig` the `ImageStreamTag` references are translated to `DockerImage` references.

When user creates the `Build` directly by POSTing to [/oapi/v1/namespaces/{namespace}/builds](https://docs.openshift.org/latest/rest_api/openshift_v1.html#create-a-build-2) this translation is bypassed. The code that creates build pods assumes the references are `DockerImage` and tries to `docker pull` the name of the ImageStream, which is not the right thing to do.

Creating `Build` without using `BuildConfig` is probably not what most users want to do but the [OSBS](https://github.com/projectatomic/osbs-client) team tried that for one-off builds and ran into this confusing behavior.

**Comment by php-coder** [comment]
@mmilata Ah, now I see what's the point. Thank you for an explanation!

**Comment by mmilata** [comment]
What would be the right thing to do here?

1. Reject builds which doesn't refer to images by `DockerImage` as invalid.
2. Resolve `ImageStreamTag`s in build controller when build is created. Keep the code that resolves `ImageStreamTag`s during `BuildConfig` instantiation.
3. Resolve `ImageStreamTag`s in build controller when build is created. Remove the code that resolves `ImageStreamTag`s during `BuildConfig` instantiation.
4. Something else?

**Comment by bparees** [comment]
(2) is the least risky/invasive.  i'd start there and we can consider (3) in the future.

**Comment by mmilata** [comment]
Closing this because #11398 was merged.

**Comment by ududitjha** [comment]
Hi All,

I am getting the Error when i was trying to execute pipeline for build config  execution.

Below are the error which i was getting.

Starting the "Trigger OpenShift Build" step with build config "nicnspeap" from the project "new".
com.openshift.restclient.OpenShiftException: Exception trying to POST https://172.30.0.1/oapi/v1/namespaces/new/buildconfigs/nicnspeap/instantiate response code: 422 Build "nicnspeap-7" is invalid: spec.source: Invalid value: "": must provide a value for at least one source input(git, binary, dockerfile, images).
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:114)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:258)

**Comment by bparees** [comment]
Your error has nothing to do with this issue and the error message you pasted shows you exactly what the problem is. If you want further assistance, please open a new issue.
