### ISSUE TITLE
at scale, dockercfg controller can miss token population window

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#11333]
the dockercfg controller creates an empty token secret, then waits in a loop for 2 seconds for it to be fulfilled by the token controller.

in a large cluster, the empty token secret might not make it to the front of the token controller's queue within the 2 second window. the dockercfg controller will remove and retry, but if the queue is long enough at steady state, that won't help.

we may need to make the wait longer, or make it tuneable, or both

**Comment by mfojtik** [comment]
@liggitt this refers to dev-preview bug, right?

**Comment by liggitt** [comment]
to my knowledge, this hasn't been seen in dev-preview, but has been seen in other large clusters

**Comment by liggitt** [comment]
I'm not sure if I'd tune the wait time, the number of tries, or switch it to a slow backoff.

I wouldn't want to just increase the wait time... on well-performing clusters, the token is available after a single wait, so we don't want to slow that down 10x.
