### ISSUE TITLE
Unable to build container on Origin v1.3

### ISSUE THREAD

**Issue by ganrad** [openshift/origin#11342]
I am trying to build a new container using the 'oc new-app' command on a RHEL7.2 VM. Here is the command I am using

```
oc new-app https://github.com... --name=my-app
```

**Exception I am getting:**

```
Cloning "https://github.com/ganrad/Apache-Spark-2.0.1-OpenShift-3.3.git" ...
error: build error: fatal: unable to access 'https://github.com/ganrad/Apache-Spark-2.0.1-OpenShift-3.3.git/': Could not resolve host: github.com; Unknown error
```

I went thru the comments in a related post ->https://github.com/openshift/origin/issues/7840
On the host, I tried the following:-
- ping github.com (resolves the ip. ok)
- nslookup github.com (ok. outputs the IP of github.com)
- sudo docker run --rm -it openshift/base-centos7 /bin/bash (Container started ok.  In the container, I was able to ping github.com, no problem)
- ran 'oadm diagnostics' 
  Looks like a DNS issue (dnsmasq or SkyDNS).  Output is pasted below. Also, I don't see any config. file for dnsmasq in /etc/dnsmasq.d directory!).

```
[
[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint

ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:155]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected

       ERROR: [DP1003 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:88]
              Could not authenticate to the master with the service account credentials: Get https://kubernetes.default.svc.cluster.local:443/oapi/v1/users/~: dial tcp: lookup kubernetes.default.svc.cluster.local: no such host

       ERROR: [DP1016 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:113]
              DNS resolution for registry address docker-registry.default.svc.cluster.local returned an error; container DNS is likely incorrect. The error was: read udp 172.17.0.3:36963->192.168.58.101:53: read: no route to host

       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected

       ERROR: [DP2003 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:72]
              The first /etc/resolv.conf nameserver 192.168.58.101
              could not resolve kubernetes.default.svc.cluster.local.
              Error: read udp 172.17.0.3:55354->192.168.58.101:53: read: no route to host
              This nameserver points to the master's SkyDNS which is critical for
              resolving cluster names, e.g. for Services.

       WARN:  [DP2014 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:119]
              A request to the nameserver 192.168.58.101 timed out.
              This could be temporary but could also indicate network or DNS problems.

       WARN:  [DP2015 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:124]
              Error querying nameserver 192.168.58.101:
                read udp 172.17.0.3:37515->192.168.58.101:53: read: no route to host
              This may indicate a problem with DNS.

       [Note] Summary of diagnostics execution (version v1.3.0):
       [Note] Warnings seen: 2
       [Note] Errors seen: 3
]
```
##### Version

```
[gradhakr@os13 ~]$ oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.58.101:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

Any help would be much appreciated! Thanks.

**Comment by knobunc** [comment]
Can you resolve kubernetes.default.svc.cluster.local from the node?
  dig kubernetes.default.svc.cluster.local @172.30.0.1

How about from inside the centos container?

Thanks

**Comment by ganrad** [comment]
Hi,
I did some more troubleshooting yesterday.  Apparently, the Networkmanager on the node was down for some reason.  And I couldn't get it to start.  So I think that was the issue.
Anyways, I have built a new RHEL72 VM today.  And I am going to run OpenShift v1.3 binary on it.  Will reach out in case I run into any issues.  Thanks for your quick attention to this problem.  Appreciate it.  I will post a comment to close this issue in the next day or two if everything goes fine.

**Comment by ganrad** [comment]
Hi,
So I created a new RHEL72 VM today and ran into a similar problem.  Notes attached below -
Here is my config -
- RHEL 7.2 VM running on VirtualBox on MacOS
- I have configured both NAT & Host only adapters on the VM.
- VM has two interfaces enp0s3 (10.0.2.15) & enp0s8 (192.168.58.101).  enp0s3 is internal and allows VM to host connections. enp0s8 is external and allows host to VM connection (ssh ....)
- Network manager in VM/Node is active (working ok). 
```
[gradhakr@os13 ~]$ sudo systemctl status network
[sudo] password for gradhakr: 
● network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network)
   Active: active (exited) since Thu 2016-10-13 14:39:21 PDT; 22min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2620 ExecStop=/etc/rc.d/init.d/network stop (code=exited, status=0/SUCCESS)
  Process: 2860 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=0/SUCCESS)

Oct 13 14:39:20 os13.demo network[2860]: Bringing up loopback interface:  Co...'
Oct 13 14:39:20 os13.demo network[2860]: Could not load file '/etc/sysconfig...'
Oct 13 14:39:20 os13.demo network[2860]: Could not load file '/etc/sysconfig...'
Oct 13 14:39:20 os13.demo network[2860]: Could not load file '/etc/sysconfig...'
Oct 13 14:39:20 os13.demo network[2860]: [  OK  ]
Oct 13 14:39:21 os13.demo network[2860]: Bringing up interface enp0s3:  Conn...)
Oct 13 14:39:21 os13.demo network[2860]: [  OK  ]
Oct 13 14:39:21 os13.demo network[2860]: Bringing up interface enp0s8:  Conn...)
Oct 13 14:39:21 os13.demo network[2860]: [  OK  ]
Oct 13 14:39:21 os13.demo systemd[1]: Started LSB: Bring up/down networking.
Hint: Some lines were ellipsized, use -l to show in full.
```
- /etc/resolv.conf on node
```
[gradhakr@os13 ~]$ cat /etc/resolv.conf
# Generated by NetworkManager
search hsd1.wa.comcast.net. demo
nameserver 75.75.75.75
nameserver 75.75.76.76
```  
- node-config.yaml.  'dnsIP' value seems to point to the node IP, which seems right.
```
[gradhakr@os13 ~]$ cat openshift.local.config/node-os13.demo/node-config.yaml
allowDisabledDocker: false
apiVersion: v1
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: 5m
  authorizationCacheSize: 1000
  authorizationCacheTTL: 5m
dnsDomain: cluster.local
dnsIP: 10.0.2.15
dockerConfig:
  execHandlerName: native
enableUnidling: true
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
iptablesSyncPeriod: 30s
kind: NodeConfig
masterClientConnectionOverrides:
  acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
  burst: 40
  contentType: application/vnd.kubernetes.protobuf
  qps: 20
masterKubeConfig: node.kubeconfig
networkConfig:
  mtu: 1450
  networkPluginName: ""
nodeIP: ""
nodeName: os13.demo
podManifestConfig: null
servingInfo:
  bindAddress: 0.0.0.0:10250
  bindNetwork: tcp4
  certFile: server.crt
  clientCA: node-client-ca.crt
  keyFile: server.key
  namedCertificates: null
volumeConfig:
  localQuota:
    perFSGroup: null
volumeDirectory: /home/gradhakr/openshift.local.volumes
```
- on node : dig kubernetes.default.svc.cluster.local @172.30.0.1 returns output below. 
```
[gradhakr@os13 ~]$ dig kubernetes.default.svc.cluster.local @172.30.0.1

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> kubernetes.default.svc.cluster.local @172.30.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28817
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN A

;; ANSWER SECTION:
kubernetes.default.svc.cluster.local. 30 IN A	172.30.0.1

;; Query time: 0 msec
;; SERVER: 172.30.0.1#53(172.30.0.1)
;; WHEN: Thu Oct 13 14:15:28 PDT 2016
;; MSG SIZE  rcvd: 70
```
- on node 'nslookup' returns output below.  So I think, the dnsmasq dns server running on the node (10.0.2.15) seems to be resolving the address for 'kubernetes.default.svc.cluster.local' OK.    But from within the container/pod, 'kubernetes.default.svc.cluster.local' is not getting resolved!
```
[gradhakr@os13 ~]$ nslookup kubernetes.default.svc.cluster.local
Server:		10.0.2.15
Address:	10.0.2.15#53

Name:	kubernetes.default.svc.cluster.local
Address: 172.30.0.1
```
- Within the centos container, nslookup & dig commands don't work (as the executables are not there). Ping returns unknown host
- When I try to create the docker registry, the pod fails
```
[gradhakr@os13 ~]$ oadm registry --credentials=./openshift.local.config/master/openshift-registry.kubeconfig
[gradhakr@os13 ~]$ oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-deploy   0/1       Error     0          35s
[gradhakr@os13 ~]$ oc logs -f dc/docker-registry
error: couldn't get deployment docker-registry-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp 172.30.0.1:443: getsockopt: no route to host
```
- I also see another bunch of etcd related errors in the 'openshift start' command window.  Looks like the etcd db is corrupted.  Is there a way to reset the etcd cluster ?
```
E1013 14:52:02.616557    3257 controller.go:121] unable to sync kubernetes service: client: etcd cluster is unavailable or misconfigured
E1013 14:52:03.879213    3257 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
I1013 14:52:03.879341    3257 trace.go:61] Trace "Update /api/v1/nodes/os13.demo/status" (started 2016-10-13 14:51:56.876109049 -0700 PDT):
[19.168µs] [19.168µs] About to convert to expected version
[83.137µs] [63.969µs] Conversion done
[87.759µs] [4.622µs] About to store object in database
[7.003186768s] [7.003099009s] END
E1013 14:52:03.879632    3257 kubelet.go:2971] Error updating node status, will retry: client: etcd cluster is unavailable or misconfigured
2016-10-13 14:52:04.130190 E | v2http: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 1.51s]
2016-10-13 14:52:10.957130 E | v2http: got unexpected response error (etcdserver: request timed out)
E1013 14:52:10.957520    3257 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
```
I have a few other questions:
- Is there any documentation on configuring networking for OpenShift origin on Virtual Box ?  Even after I get all the issues resolved, I still won't be able to access the web console from my host as the MasterURL points to the VM/Node's internal interface - 10.0.2.15.  Any pointers on how I can set this up would be very helpful....

**Comment by knobunc** [comment]
What networking plugin are you using?  You can use the troubleshooting guide at https://docs.openshift.com/container-platform/3.3/admin_guide/sdn_troubleshooting.html (and see the debug.sh script to gather a debug tar that you can get to us)

@bparees do you know what that etcd error might mean?  Or how to troubeshoot it further?

**Comment by bparees** [comment]
@knobunc not really, i mean it sounds like the kubelet isn't even able to connect to etcd but why or how to get more info would be a question for the cluster infra team.

**Comment by ganrad** [comment]
Ok.  So I was able to get past a few issues yesterday.  But etcd is still displaying error messages on the openshift console window.  
When I try to create the registry, I am now getting an exception which seems to be tied to etcd server -
```
[gradhakr@os13 ~]$ oadm registry --mount-host=/home/gradhakr/registry
--> Creating registry registry ...
    serviceaccount "registry" created
    error: rolebinding "registry-registry-role" already exists
    error: client: etcd cluster is unavailable or misconfigured
    service "docker-registry" created
--> Failed
error: exit directly
```
This is what I am seeing in the openshift console window.  And these messages are getting logged every few minutes.  Not sure what they mean.
```
E1014 12:42:27.314880   24939 kubelet.go:2971] Error updating node status, will retry: Operation cannot be fulfilled on nodes "os13.demo2": the object has been modified; please apply your changes to the latest version and try again
E1014 12:45:28.165790   24939 controller.go:121] unable to sync kubernetes service: client: etcd cluster is unavailable or misconfigured
E1014 12:45:28.240723   24939 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
```

**Comment by knobunc** [comment]
@bparees thanks

**Comment by ganrad** [comment]
Attaching my master-config.yaml file ....

[master-config.txt](https://github.com/openshift/origin/files/530410/master-config.txt)

**Comment by ganrad** [comment]
Hi All,
I want to demo Origin next week and would appreciate some help/pointers to resolve the etcd issue.  I am now only seeing etcd errors in the OpenShift console.  The kubelet for some reason is unable to connect to etcd.  When I run this command on the node, I don't get any output-
curl -L http://10.0.2.15:4001/version
Any quick help would be much appreciated.  Thanks.

**Comment by derekwaynecarr** [comment]
the kubelet does not speak to etcd, the kubelet speaks to the apiserver, which communicates with etcd.  are you having other issues with your apiserver creating resources (pods, events, nodes, etc.)?

**Comment by ganrad** [comment]
Hi, no I don't think so.  I can see the node status (oc get nodes) is 'ready'.  Only when I try to issue the 'oadm registry...' command, I see a whole bunch of errors in the Origin console output (pasted above).  I haven't started Origin on my VM for a couple of days. Will fire it up again tomorrow and troubleshoot this some more.  Any help would be much appreciated.  Thanks.

**Comment by coreydaley** [comment]
Closing due to age and inactivity.  Please re-open with new information, or open a new issue if you are still having an issue.
