### ISSUE TITLE
Unable to execute commands as system:admin

### ISSUE THREAD

**Issue by seybi87** [openshift/origin#11349]
Hi Openshift guys,

I am using the 1.3 binary release, installed from scratch.

The installation is running and I can use the CLI and web console as user 'test'

I'am trying modify the default user, therefore I'm logging in as system:admin using the admin.kubeconfig

As soon as I execute any command I get the follwoing error response:

`User "system:anonymous" cannot get clusterpolicies at the cluster scope`

What am I doing wrong here?

##### Version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1.  create a project 'testproject' as user 'test' via the web console
2. ` oc login -u system:admin -n testproject --config=/opt/openshift-server/openshift.local.config/master/admin.kubeconfig`

`Logged into "https://192.168.0.202:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * testproject
    default
    kube-system
    openshift
    openshift-infra

Using project "testproject".`

2. `oc describe clusterPolicy testproject`
`Error from server: User "system:anonymous" cannot get clusterpolicies at the cluster scope`

See below my admin.kubeconfig:

`
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3$
    server: https://IP:8443
  name: IP:8443
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3$
    server: https://HOSTNAME.de:8443
  name: hostname:8443
contexts:
- context:
    cluster: IP:8443
    namespace: testproject
    user: system:admin/IP:8443
  name: cloudsocket/IP:8443/system:admin
- context:
    cluster: IP:8443
    namespace: default
    user: system:admin/IP:8443
  name: default/IP:8443/system:admin
- context:
    cluster: hostname:8443
    namespace: default
    user: system:admin/IP:8443
  name: default/hostname:8443/system:admin
current-context: testproject/IP:8443/system:admin
kind: Config
preferences: {}
users:
- name: system:admin/IP:8443
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREVENDQWZXZ0F3SUJ$
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcDJ$

`Thank you in advance for your help!

**Comment by mfojtik** [comment]
@seybi87 you don't have to login as system admin, you can just execute this command:

```
$ oc describe clusterPolicy testproject --config=/var/lib/openshift/openshift.local.config/master/admin.kubeconfig
```

**Comment by seybi87** [comment]
@mfojtik  thanks for reply.
I also tried this before but it results in the same error message:
`oc describe clusterPolicy test --config=/opt/openshift-server/openshift.local.config/master/admin.kubeconfig
Error from server: User "system:anonymous" cannot get clusterpolicies at the cluster scope`

**Comment by mfojtik** [comment]
@seybi87 weird, can you try to `oc logout`? @enj @liggitt any ideas?

**Comment by seybi87** [comment]
Yes, it does still not work, neither logged in nor logged out before executing the command.

**Comment by enj** [comment]
Some things to try:

Make sure you can read the config (without having to be `root`)

`sudo chmod 655 /opt/openshift-server/openshift.local.config/master/admin.kubeconfig`

Login to `system:admin` in the `default` namespace, not your test one.:

`oc login -u system:admin -n default --config=/opt/openshift-server/openshift.local.config/master/admin.kubeconfig`

You can also run commands this way:

`KUBECONFIG=/opt/openshift-server/openshift.local.config/master/admin.kubeconfig oc ...`

Export `KUBECONFIG` if you always want to be `system:admin`:

`export KUBECONFIG=/opt/openshift-server/openshift.local.config/master/admin.kubeconfig`

**Comment by seybi87** [comment]
@enj  Thanks for your input, changing the permissions of the admin.config file indeed solved the problem.

As I run the installation as root, only root had access to the config.

Thanks again for the quick and helpful comments!
