### ISSUE TITLE
oc cluster up --env splits string args on comma

### ISSUE THREAD

**Issue by tjuerge** [openshift/origin#11359]
String values used in `oc cluster --env` are split on commas, e.g. `NO_PROXY` in
```
[vagrant@localhost app]$ oc cluster up --env=HTTP_PROXY=http://10.0.2.2:3128,HTTPS_PROXY=http://10.0.2.2:3128,NO_PROXY=".localdomain,10.0.2.15,10.1.0.0/16,172.30.0.0/16"
-- Checking OpenShift client ... OK
              :
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
^C
[vagrant@localhost app]$ docker exec -it origin env|grep PROXY
HTTP_PROXY=http://10.0.2.2:3128
HTTPS_PROXY=http://10.0.2.2:3128
NO_PROXY=.localdomain
```

##### Version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. `oc cluster up --env=HTTP_PROXY=http://10.0.2.2:3128,HTTPS_PROXY=http://10.0.2.2:3128,NO_PROXY=".localdomain,10.0.2.15,10.1.0.0/16,172.30.0.0/16"`
2. `docker exec -it origin env|grep NO_PROXY`

##### Current Result
Env values containing commas are truncated.

##### Expected Result
Env values containing commas are complete.

##### Additional Information
Maybe this issue is related to #9565

**Comment by liggitt** [comment]
yeah, same issue as https://github.com/openshift/origin/issues/9565
