### ISSUE TITLE
How can i find the implements when i get an URL

### ISSUE THREAD

**Issue by Decent-Dexter** [openshift/origin#11364]
For instance,  
`requestURL := o.ClientConfig.Host + "/oauth/authorize?response_type=token&client_id=openshift-challenging-client"`
where can i find the implements of this requestURL?

**Comment by enj** [comment]
@Decent-Dexter I am not really sure what you are looking for...

If you are looking for the implementation of the OAuth flow, that is provided by [osin](https://github.com/RangelReale/osin):

1. [osinserver.go#L47](https://github.com/openshift/origin/blob/master/pkg/oauth/server/osinserver/osinserver.go#L47)
2. [authorize.go#L106](https://github.com/openshift/origin/blob/master/vendor/github.com/RangelReale/osin/authorize.go#L106)

**Comment by Decent-Dexter** [comment]
@enj That basicly solves my problem for now.Thanks a lot.
