### ISSUE TITLE
godep-restore fails on k8s.io/client-go/1.4/discovery

### ISSUE THREAD

**Issue by lpabon** [openshift/origin#11372]
Trying to do a ./hack/godep-restore.sh and it fails on k8s.io/client-go/1.4/discovery.
##### Version

Commit hash: 098e0ee9e4c868292f6c6e0d8d9340e79b068147
##### Steps To Reproduce
1. Checkout out openshift/origin into a clean GOPATH
2. run ./hack/godep-restore.sh
##### Current Result

```
# cd /home/lpabon/git/golang/openshift/src/k8s.io/client-go; git checkout 82291698d0e5b9f3bfea77ae707aa4e0007d6e76
fatal: reference is not a tree: 82291698d0e5b9f3bfea77ae707aa4e0007d6e76
godep: error downloading dep (k8s.io/client-go/1.4/discovery): exit status 128
godep: Error downloading some deps. Aborting restore and check.
[ERROR] PID 23491: hack/godep-restore.sh:90: `"${GODEP}" restore` exited with status 1.
[INFO]          Stack Trace:
[INFO]            1: hack/godep-restore.sh:90: `"${GODEP}" restore`
[INFO]   Exiting with code 1.
```
##### Expected Result

It is supposed to setup all the dependencies in $GOPATH

**Comment by kargakis** [comment]
godep is not used anymore
