### ISSUE TITLE
Build ImageSource is including source directory when suffixed with /

### ISSUE THREAD

**Issue by rcernich** [openshift/origin#11373]
ImageSource sourcePath is specified with a trailing / but the directory is still being included in the mounted directory, e.g.
sourcePath=/foo/
destinationDir=bar
Build includes .../bar/foo/<foo-content> as opposed to the documented .../bar/<foo-content>

##### Version
3.3.0.16

##### Steps To Reproduce
Create a build config with a mounted source image.  Examine the build log after building with --build-loglevel=5 and notice where the files are being mounted.

**Comment by bparees** [comment]
the syntax for not copying the dir itself is to end in "/." not just "/" so @rcernich is going to double check on this.

**Comment by rcernich** [comment]
my bad, the source path must end with "/." not "/"
