### ISSUE TITLE
First build triggered through UI fails

### ISSUE THREAD

**Issue by david-strejc** [openshift/origin#11387]
When I got git repository protected by login or ssh key (GitLab for example) and I want to trigger my build through UI fist build fails. 

There is no option for adding git credentials for initial git builds in OpenShift UI.

Is there any way how I can let my users trigger their builds through UI and have private git repository?

**Comment by spadgett** [comment]
@david-strejc For the web console, we're in the progress of adding support for private Git repositories now. See this Trello card:

https://trello.com/c/OVlx3edX

Part of the implementation has merged to origin-web-console under this pull request:

https://github.com/openshift/origin-web-console/pull/511

We plan to add support to the "Add to Project" page as well. This is planned to 1.4.

**Comment by spadgett** [comment]
Closing the issue here as it is tracked in Trello. Please subscribe to https://trello.com/c/OVlx3edX for updates.
