### ISSUE TITLE
Environment variables used in s2i/environment aren't visible through UI

### ISSUE THREAD

**Issue by david-strejc** [openshift/origin#11388]
When I create s2i/environment variables I expect to see them through UI (build and deployment management) - but there is no option for managing those variables.

I don't know if those variables can be overridden or not (I expect they can be) but it is little bit confusing for end user.

**Comment by bparees** [comment]
unassigning myself, @jwforres if there's something you need from the backend side let me know, but this sounds like purely a console RFE.

**Comment by jwforres** [comment]
@spadgett if I understand the request this sounds like the environment vars that are on the s2i base image, we could read off the environment from the image metadata like we do on the create from image page and show it as a separate read only section with additional details

**Comment by david-strejc** [comment]
I've expected, that variables from (I am using overriding .s2i/ from within git repository - so Docker builder image has its own .s2i ) environment file (.s2i/environment) will be visible through UI and programmer can edit and change them from UI. I don't want those variables to be read only as for example we are setting java max and min memory this way.

Am I clear?

**Comment by jwforres** [comment]
You can already overwrite them on the Environment tab for the build config,
or in the build config editor, or when you are creating from a builder
image in add to project. User defined environment takes precedence.

As far as viewing what is in your .s2i/environment file, are you expecting
to see this on the build configuration, a specific instance of a build, on
the resulting build config?

@bparees does that env end up on the built image's metadata?

**Comment by bparees** [comment]
> @bparees does that env end up on the built image's metadata?

yes it should.  they become env variables defined in the output image.
