### ISSUE TITLE
oc rsync --watch trying to sync excluded files too

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#11382]
`oc rsync --watch` trying to sync excluded files too and failing with too many files open error
##### Version

```
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://10.0.0.249:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```
##### Steps To Reproduce

```
$ oc rsync api api-1-wz3u0:/opt/app-root/src --exclude='api/node_modules/***' --watch
```
##### Current Result

```
building file list ... done

sent 94 bytes  received 20 bytes  76.00 bytes/sec
total size is 3099  speedup is 27.18
error: error watching source path api: error adding watcher for path api/node_modules/async/node_modules/lodash: too many open files
```
##### Expected Result

`--watch`  should exclude node_modules

**Comment by bparees** [comment]
here are the rules the watch logic would need to honor to exclude the same set of paths as rsync:
https://www.samba.org/ftp/rsync/rsync.html
(INCLUDE/EXCLUDE PATTERN RULES section)

Need to find a go library that will allow easy comparison between those patterns and the files we find during recursive watching.

**Comment by bparees** [comment]
per a suggestion from @csrwng might be able to use --list-only to determine the list of files to watch. will look into it.
