### ISSUE TITLE
oc get istag/mysql:5.5 fails

### ISSUE THREAD

**Issue by bparees** [openshift/origin#11381]
Not sure if this is a flake or something more fundamental, it is failing consistently since friday night.

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/7166/consoleFull#87565479056c25df4e4b05b79524e5d52

```
FAILURE after 59.513s: test/cmd/images_tests.sh:177: executing 'oc get istag/mysql:5.5' expecting success; re-trying every 0.2s until completion or 60.000s: the command timed out
```

i've confirmed that mysql:5.5 can be imported/imagestream created on my machine.

**Comment by mfojtik** [comment]
@bparees https://github.com/openshift/origin/pull/11245 merged this Friday. @legionus can you take a look?

**Comment by kargakis** [comment]
Not sure if it's related to #11245, the slowness in the istag api seems like different. This is probalby the same issue as https://github.com/openshift/origin/issues/10663)

**Comment by liggitt** [comment]
bumping priority, queue is failing 100% on this

**Comment by liggitt** [comment]
the failure is in `images-old-policy.sh`, which tests behavior of the tag command when direct istag creation cannot be performed.

**Comment by liggitt** [comment]
looks like the test is running against the dockerhub mysql image, and is only importing a few of the many possible tags. the dockerhub image just pushed a bunch of tag changes 2 days ago, and 5.5 is not even in the spec.tags list of the imagestream

**Comment by knobunc** [comment]
This is happening over on release-1.3 branch.

**Comment by liggitt** [comment]
fix was in https://github.com/openshift/origin/issues/11393 if you want to cherry pick it
