### ISSUE TITLE
Running individual core extended tests may fail with timeout when waiting for image registry

### ISSUE THREAD

**Issue by gnufied** [openshift/origin#11406]
Running individual core extended test blocks forever
##### Version

```
oc v1.4.0-alpha.0+49de813
kubernetes v1.4.0+776c994
features: Basic-Auth
```
##### Steps To Reproduce

Try and run a individual core test via:

```
~> test/extended/core.sh --ginkgo.focus=<regex>
```
##### Current Result

It hangs while waiting for docker registry to be up. It stops at following step:

```
enshift.local.config/master/admin.kubeconfig'' expecting success; re-trying every 0.25s until completion or 80.000s
[INFO] OpenShift server health checks done at: 
Mon Oct 17 17:22:28 EDT 2016
[INFO] Installing the registry
serviceaccount "registry" created
clusterrolebinding "registry-registry-role" created
deploymentconfig "docker-registry" created
service "docker-registry" created
[INFO] Waiting for command to finish: 'oc get dc/docker-registry -o 'jsonpath={.status.observedGeneration},{.status.replicas},{.status.updatedReplicas},{.status.availableReplicas}' --config='/tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig' | grep '^1,1,1,1$''...
```

In my testing I found the docker registry to be up, but it the version/generation of `dc/docker-registry` does not matches with what is expected of the test. The same thing works if I run whole extended suite.
##### Expected Result

It should be possible to run individual tests.

**Comment by php-coder** [comment]
Sometimes extended tests also failed for me near this line, but they're failing after timeout (5 mins) with error message like this:
```
[INFO] Waiting for command to finish: 'oc get dc/docker-registry -o 'jsonpath={.status.observedGeneration},{.status.replicas},{.status.updatedReplicas},{.status.availableReplicas}' --config='/tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig' | grep '^1,1,1,1$''...
[ ERR] Gave up waiting for: 'oc get dc/docker-registry -o 'jsonpath={.status.observedGeneration},{.status.replicas},{.status.updatedReplicas},{.status.availableReplicas}' --config='/tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig' | grep '^1,1,1,1$''
[ERROR] PID 15342: hack/util.sh:105: `return 1` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/util.sh:105: `return 1`
[INFO] 		  2: test/extended/setup.sh:125: wait_for_registry
[INFO] 		  3: test/extended/core.sh:11: os::test::extended::setup
[INFO]   Exiting with code 1.
...
```

@gnufied In which environment you're running tests? In my case it's all-in-one VM in the Vagrant. Do you have logs in the `/tmp/openshift/test-extended/core/logs` directory? When tests are blocking what is the `docker ps` output? If you see that some container are running, did you try to take their logs by `docker logs` command?

**Comment by php-coder** [comment]
@mfojtik I have a fix for this, so I hope that you wouldn't mind if I take it? :)

**Comment by gnufied** [comment]
@php-coder I am running this on my local Ubuntu (*cough*) box natively. There are no vms involved. My docker version is - "1.12.1".

While the tests are blocking the output of `docker ps` is - https://gist.github.com/gnufied/5a93ba236563703df8635fbec981a49c 


I will try and get other logs. Sorry I didn't see your response until now.

**Comment by mmilata** [comment]
Seen in Jenkins: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8060/console
