### ISSUE TITLE
Proposal: support pyflame and similar live application profilers

### ISSUE THREAD

**Issue by ncoghlan** [openshift/origin#11431]
pyflame is a ptrace-based profiler for Python applications that aims to make it possible to identify performance bottlenecks in running services without degrading their operations: https://eng.uber.com/pyflame/

At the moment, such profilers can't be used in OpenShift (especially in multi-tenant configurations), as they need external ptrace access to the running container.

This isn't necessarily a request to allow pyflame to work as-is in multi-tenant configurations (I assume there would be significant security problems with that), but rather a request to:
- if they're not supported, explain somewhere (perhaps in a blog post?) what alternative performance profiling options _are_ supported
- if they _are_ supported (at least in single tenant environments where you control the host nodes), explain how to set that up

And if it isn't yet possible to enable these kinds of tools even when you're managing your own cluster, _then_ it would be a technical RFE to at least make that feasible.

**Comment by bparees** [comment]
@jeremyeder is this something your team would be positioned to do (provide some doc recommendations for doing perf analysis on apps running on openshift)?

**Comment by bparees** [comment]
@jeremyeder bump
