### ISSUE TITLE
Building example Py 3.5. Django project fails following "oc cluster up"

### ISSUE THREAD

**Issue by ncoghlan** [openshift/origin#11433]
To experiment with querying for external route information from inside a running pod, I was setting up a new example Py3.5 Django project under "oc cluster up". However, the container build failed with the following two errors seeming significant.

At start of build:

    Cloning "https://github.com/openshift/django-ex.git" ...
        Commit:	9f38043a5ef683404aae82bfd86f4f7c15f618ea (Merge pull request #61 from stedotmartin/master)
        Author:	Ben Parees <bparees@users.noreply.github.com>
        Date:	Sun Oct 2 06:00:08 2016 -0800
    error: An error occurred saving build revision: Put https://172.30.0.1:443/oapi/v1/namespaces/myproject/builds/route-tinkering-1/details: dial tcp 172.30.0.1:443: getsockopt: no route to host

At end of build:

    Pushing image 172.30.93.232:5000/myproject/noroute-tinkering:latest ...
    Registry server Address: 
    Registry server User Name: serviceaccount
    Registry server Email: serviceaccount@example.org
    Registry server Password: <<non-empty>>
    error: build error: Failed to push image: Put http://172.30.93.232:5000/v1/repositories/myproject/route-tinkering/: dial tcp 172.30.93.232:5000: getsockopt: connection refused

After using the advanced options with the external route configured failed, I tried again with the external route, and got the same build failures.

##### Version
$ oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://192.168.1.21:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4

From https://copr.fedorainfracloud.org/coprs/adelton/openshift-origin-1.3/ on Fedora 24

##### Steps To Reproduce
1. Run `oc cluster up` (adding the extra `--insecure-registry` setting to `/etc/sysconfig/docker` after it complained the first time)
2. Go to the web console, login as developer/developer and select "Add to Project"
3. Add a Python 3.5 app, name it, and select "Try it" for the example Django project
4. Click "Create"

##### Current Result

The initial build & deployment fails, with the above errors

##### Expected Result

The example image is deployed in the local dev cluster

##### Additional Information

This system does have some customisations of Docker's DNS settings to handle VPN connectivity on the host: http://stackoverflow.com/questions/35693117/how-can-i-give-docker-containers-access-to-a-dnsmasq-local-dns-resolver-on-the-h

However, that shouldn't be impacting this, since these connections are using IP addresses, not domain names.

More promising is the `oadm diagnostics` output (thanks for that tip in the issue template!), which suggests that the cluster registry didn't start for some reason:

    $ oadm diagnostics
    [Note] Determining if client configuration exists for client/cluster diagnostics
    Info:  Successfully read a client config file at '/home/ncoghlan/.kube/config'
    Info:  Using context for cluster-admin access: 'default/192-168-1-21:8443/system:admin'

    [Note] Running diagnostic: ConfigContexts[/192-168-1-21:8443/developer]
        Description: Validate client config context is complete and has connectivity

    Info:  For client config context '/192-168-1-21:8443/developer':
        The server URL is 'https://192.168.1.21:8443'
        The user authentication is 'developer/192-168-1-21:8443'
        The current project is 'default'
        Successfully requested project list; has access to project(s):
            [myproject]

    [Note] Running diagnostic: ConfigContexts[default/192-168-1-21:8443/system:admin]
        Description: Validate client config context is complete and has connectivity

    Info:  For client config context 'default/192-168-1-21:8443/system:admin':
        The server URL is 'https://192.168.1.21:8443'
        The user authentication is 'system:admin/192-168-1-21:8443'
        The current project is 'default'
        Successfully requested project list; has access to project(s):
            [default kube-system myproject openshift openshift-infra]

    [Note] Running diagnostic: DiagnosticPod
        Description: Create a pod to run diagnostics from the application standpoint

    Info:  Output from the diagnostic pod (image openshift/origin-deployer:v1.3.0):
        [Note] Running diagnostic: PodCheckAuth
                Description: Check that service account credentials authenticate as expected

    [Note] Running diagnostic: ClusterRegistry
        Description: Check that there is a working Docker registry

    ERROR: [DClu1006 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:208]
        The "docker-registry" service exists but has no associated pods, so it
        is not available. Builds and deployments that use the registry will fail.

    ERROR: [DClu1001 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:178]
        The "docker-registry" service exists but no pods currently running, so it
        is not available. Builds and deployments that use the registry will fail.

    [Note] Running diagnostic: ClusterRoleBindings
        Description: Check that the default ClusterRoleBindings are present and contain the expected subjects

    [Note] Running diagnostic: ClusterRoles
        Description: Check that the default ClusterRoles are present and contain the expected permissions

    [Note] Running diagnostic: ClusterRouterName
        Description: Check there is a working router

    ERROR: [DClu2007 from diagnostic ClusterRouter@openshift/origin/pkg/diagnostics/cluster/router.go:156]
        The "router" DeploymentConfig exists but has no running pods, so it
        is not available. Apps will not be externally accessible via the router.

    [Note] Running diagnostic: MasterNode
        Description: Check if master is also running node (for Open vSwitch)

    Info:  Found a node with same IP as master: 192.168.1.21

    [Note] Skipping diagnostic: MetricsApiProxy
        Description: Check the integrated heapster metrics can be reached via the API proxy
        Because: The heapster service does not exist in the openshift-infra project at this time,
        so it is not available for the Horizontal Pod Autoscaler to use as a source of metrics.

    [Note] Running diagnostic: NodeDefinitions
        Description: Check node records on master

    [Note] Skipping diagnostic: ServiceExternalIPs
        Description: Check for existing services with ExternalIPs that are disallowed by master config
        Because: No master config file was detected

    [Note] Summary of diagnostics execution (version v1.3.0):
    [Note] Errors seen: 3

**Comment by coreydaley** [comment]
@ncoghlan 
After looking at this page (https://copr.fedorainfracloud.org/coprs/adelton/openshift-origin-1.3/), I see this line "Instructions not filled in by author. Author knows what to do. Everybody else should avoid this repo".  If you would like to try out OpenShift Origin it would probably be best to download it from an official source such as https://github.com/openshift/origin/releases.  There is no quick/easy way to know exactly what code is or was included in that repo that you installed.

I was not able to duplicate the issue that you encountered when using the oc command downloaded from the github releases page linked above.

**Comment by ncoghlan** [comment]
With the v1.3.1 download from https://github.com/openshift/origin/releases and unpacking both the client and the server binaries into ~/.local/bin, I don't get the option of running a plain Django example anymore, so I used the django-psql example instead.

For that, the PostgreSQL container deployment failed with the following and no other output:

    error: couldn't get deployment postgresql-1: Get https://172.30.0.1:443/api/v1/namespaces/myproject/replicationcontrollers/postgresql-1: dial tcp 172.30.0.1:443: getsockopt: no route to host

The Python/Django example container build failed with the same errors as above.

Running `oadm diagnostics` also gives the same errors as shown above:

    <snip>
    ERROR: [DClu1006 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:208]
        The "docker-registry" service exists but has no associated pods, so it
        is not available. Builds and deployments that use the registry will fail.

    ERROR: [DClu1001 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:178]
        The "docker-registry" service exists but no pods currently running, so it
        is not available. Builds and deployments that use the registry will fail.

    <snip>

    ERROR: [DClu2007 from diagnostic ClusterRouter@openshift/origin/pkg/diagnostics/cluster/router.go:156]
        The "router" DeploymentConfig exists but has no running pods, so it
        is not available. Apps will not be externally accessible via the router.

   <snip>

To double check the COPR versions were indeed gone and I was running the binaries from the downloaded tarball, I checked with `oc version`:

    $ oc version
    oc v1.3.1
    kubernetes v1.3.0+52492b4
    features: Basic-Auth GSSAPI Kerberos SPNEGO

    Server https://192.168.1.21:8443
    openshift v1.3.1
    kubernetes v1.3.0+52492b4

I'm not sure if it's relevant, but when I open the web console, I need to authorize a certificate security exception in Firefox before it will permit connections over SSL.

**Comment by ncoghlan** [comment]
To completely rule out SELinux problems, I tried again under `setenforce 0` with no change in behaviour. However, running `oc cluster up --server-log-level=2` and looking at the container logs via Cockpit gives these additional error messages:

    I1020 07:35:34.874058   31694 controller.go:375] Cannot update the status for "default/docker-registry": Operation cannot be fulfilled on deploymentconfigs "docker-registry": the object has been modified; please apply your changes to the latest version and try again
    I1020 07:35:34.874119   31694 controller.go:427] Error syncing deployment config default/docker-registry: Operation cannot be fulfilled on deploymentconfigs "docker-registry": the object has been modified; please apply your changes to the latest version and try again
    I1020 07:35:34.875858   31694 controller.go:229] Error instantiating deployment config default/router: Operation cannot be fulfilled on deploymentconfigs "router": the object has been modified; please apply your changes to the latest version and try again
    I1020 07:35:34.956132   31694 controller.go:229] Error instantiating deployment config default/docker-registry: couldn't retrieve deployment for deployment config "default/docker-registry": replicationcontrollers "docker-registry-1" not found
    I1020 07:35:34.958298   31694 controller.go:229] Error instantiating deployment config default/router: couldn't retrieve deployment for deployment config "default/router": replicationcontrollers "router-1" not found

**Comment by ncoghlan** [comment]
And one other recurring error in the container logs that seems like it might be potentially relevant since I'm not sure exactly how I have the docker runtime storage configured on this system:

    E1020 07:47:23.982632   31694 thin_pool_watcher.go:72] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exit status 127

**Comment by ncoghlan** [comment]
Chatting to @soltysh about this, and he indicated the problem may be the fact that the system has a local DNS resolver running, so SkyDNS is having to fall back to running on port 8053:

    -- Checking for available ports ... 
    WARNING: Binding DNS on port 8053 instead of 53, which may be not be resolvable from all clients.

However, if that's the case, then this is a general incompatibility between `oc cluster up` and recent versions of Fedora, since they all run a local caching resolver by default: https://fedoraproject.org/wiki/Changes/Default_Local_DNS_Resolver

**Comment by bparees** [comment]
SkyDNS falling back to port 8053 shouldn't prevent internal hostname resolution from working, right @csrwng ?  the pods should still all have the correct /etc/resolv.conf that points to skydns on 8053.

**Comment by csrwng** [comment]
@bparees yes, that is my understanding
@ncoghlan please flush iptables before running cluster up with `$ iptables -F`. This is likely the same problem we've seen elsewhere.

**Comment by csrwng** [comment]
The cluster up doc badly needs an update with the iptables suggestion front and center, I will submit a PR today

**Comment by ncoghlan** [comment]
Thank you @csrwng, the `iptables -F` suggestion did indeed get the example project deployment working!

There's still one oddity though, which is that the `oadm diagnostics` diagnostic pod failed, so the command hung indefinitely. Getting the logs from the diagnostic pod:

    [Note] Running diagnostic: PodCheckAuth
        Description: Check that service account credentials authenticate as expected

    Info:  Service account token successfully authenticated to master
    ERROR: [DP1014 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:173]
        Request to integrated registry timed out; this typically indicates network or SDN problems.

    [Note] Running diagnostic: PodCheckDns
        Description: Check that DNS within a pod works as expected

    [Note] Summary of diagnostics execution (version v1.3.1):
    [Note] Errors seen: 1

**Comment by ncoghlan** [comment]
Is there are an existing issue report for the firewall compatibility problems with `oc cluster up`? My original problem with failing to run the Django example has been resolved, so this particular issue should probably be closed with a reference to that one (assuming it already exists).

The remaining problem with `oadm diagnostics` looks like it may be a different issue (perhaps related to SkyDNS coming up on port 8053 instead of 53), so please let me know if I should file a separate report for that.

**Comment by csrwng** [comment]
@ncoghlan we have this issue regarding the initial problem https://github.com/openshift/origin/issues/10139

Please open another one for the `oadm diagnostics` issue and I'll investigate. Thx!

**Comment by soltysh** [comment]
> @ncoghlan please flush iptables before running cluster up with $ iptables -F. This is likely the same problem we've seen elsewhere.

Eh... I wasn't even aware of that :(

**Comment by coreydaley** [comment]
Looks like turning off your firewall (firewalld) is recommended in the troubleshooting section of the docs: https://docs.openshift.org/latest/admin_guide/sdn_troubleshooting.html#is-code-firewalld-code-disabled

**Comment by ncoghlan** [comment]
Aye, referencing the troubleshooting guide from the `oc cluster up` would definitely be helpful, as a lot of us using it won't be familiar with the general structure of the OpenShift documentation yet.

Problems with `firewalld` certainly sound plausible in my case, as local bridge networks are treated as untrusted external zones by default. To give Docker containers access to the local resolver in http://stackoverflow.com/questions/35693117/how-can-i-give-docker-containers-access-to-a-dnsmasq-local-dns-resolver-on-the-h for example, I needed to mark the default Docker bridge network as trusted:

    sudo firewall-cmd --permanent --zone=trusted --change-interface=docker0
    sudo firewall-cmd --reload

Perhaps the default OpenShift cluster bridge could be given a similarly predictable name, so a similar pair of commands would work to trust the default cluster?

    sudo firewall-cmd --permanent --zone=trusted --change-interface=openshift0
    sudo firewall-cmd --reload

(That assumes `oc cluster` will re-use an already defined bridge, rather than creating a new one each time, though)

**Comment by coreydaley** [comment]
Closed via #11585
Please open a new issue for any other problems that you encountered that were not directly related to the firewall rules.

**Comment by coreydaley** [comment]
Linking to PR #11624

**Comment by coreydaley** [comment]
Closed via #11624
Please open a new issue for any problems you encounter that do not directly relate to this firewall issue.
