### ISSUE TITLE
oc new-app from private image directly

### ISSUE THREAD

**Issue by mdshuai** [openshift/origin#11435]
##### Description of the issue

Sometime I want create a app from private image, But there is no parameter to specify secret for `oc new-app`.  after create app then edit dc then re-deploy, it's too complex.
##### Steps To Reproduce
1. oc new-app --docker-image=myprivateimage
2. The deploy always failed.
3. I need edit dc to add 'imagePullSecrets' to dc then re-deploy; The step is too complex
##### Expected Result
1. Add parameter to specify pullSecret in `oc new-app` 
2. We can add pullSecret to dc in command; like `oc set pull-secret dc/mydc ....`
##### Additional Information
1. Once there is related card describe the case https://trello.com/c/iatchS02
2. There is [feature about set secret to bc](https://github.com/openshift/ose/commit/a3360680b0bedc584967920167f9e9fe16ee4390) but not for dc.

**Comment by mdshuai** [comment]
@bparees @csrwng

**Comment by bparees** [comment]
we're not adding this to new-app, so the feature would be to update oc set secret to support adding a pull secret to DCs, assigning to platform team.

**Comment by mfojtik** [comment]
@bparees @mdshuai I don't think there is a concept of "pull-secret" in deployment config at all. To be able to use image from private repository, you just need to provide a dockercfg for pulling and attach it to service account.

**Comment by mfojtik** [comment]
What you want is: `oc secrets link serviceaccount-name pull-secret --for=pull`

Let me know if that is what you're looking for.
