### ISSUE TITLE
Error from server: User "admin" cannot get clusterpolicybindings at the cluster scope

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [openshift/origin#11437]
How add permissions for  edit cluster role ?

when I am try: 
$ oc login -u admin
$ oadm policy add-cluster-role-to-user cluster-admin admin
Error from server: User "admin" cannot get clusterpolicybindings at the cluster scope

##### Version
oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
 $ oc login -u system:admin

##### Current Result
Authentication required for https://localhost:8443 (openshift)
Username: system:admin
Password:
error: username system:admin is invalid for basic auth

##### Expected Result

oadm policy add-cluster-role-to-user cluster-admin admin
Error from server: User "admin" cannot get clusterpolicybindings at the cluster scope

##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by liggitt** [comment]
```
oc login -u system:admin
oadm policy add-cluster-role-to-user cluster-admin admin
```

**Comment by deads2k** [comment]
@liggitt looks like yet another person bit by the "run this magic command" that is encouraged because people mutate a file that should be read-only.  You rejected the idea of fixing the problem because of pain around the fix.

**Comment by liggitt** [comment]
I don't mind making the file read-only, but I don't want to bake in "you may not mutate a file containing a cert for a user named X" logic.

**Comment by Evgeniy-Bondarenko** [comment]
Problem resolved after add variable  KUBECONFIG (can check `echo $KUBECONFIG , if empty - need add path)
`export OPENSHIFT=/var/openshift
export KUBECONFIG=$OPENSHIFT/openshift.local.config/master/admin.kubeconfig
export CURL_CA_BUNDLE=$OPENSHIFT/openshift.local.config/master/ca.crt`

or use key in command `oc login -u system:admin --config=/opt/openshift/openshift.local.config/master/admin.kubeconfig` 

Before to close, it could be interesting to improve existing doc about necessary openshift variable
