### ISSUE TITLE
test/cmd/annotations.sh flake / zookeeper-1 / label2

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#11442]
The new test/cmd/annotations.sh test failed for me:

    FAILURE after 0.572s: test/cmd/annotations.sh:25: executing 'oc get pod zookeeper-1 --template="{{.metadata.labels}}"' expecting success and text 'label2\: ': the output content test failed
    Standard output from the command:
    map[name:zookeeper server-id:1 template:zookeeper label2:]
    There was no error output from the command.

ie, the test expects a "\" in the output but it wasn't there

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/7281/consoleFull#174997548756c25df4e4b05b79524e5d52

@juanvallejo, fallout from #11210

**Comment by liggitt** [comment]
the backslash isn't the issue, the space after the colon is
