### ISSUE TITLE
Metrics HPA - Cannot unmarshal object into Go value of type []v1alpha1.PodMetrics

### ISSUE THREAD

**Issue by Shyckymn** [openshift/origin#11463]
When I try to implement the HPA mechanism, my events are showing the following error:

`failed to get CPU utilization: failed to get CPU consumption and request: failed to unmarshall heapster response: json: cannot unmarshal object into Go value of type []v1alpha1.PodMetrics
`
`failed to get CPU consumption and request: failed to unmarshall heapster response: json: cannot unmarshal object into Go value of type []v1alpha1.PodMetrics`

```
docker.io/openshift/origin-metrics-cassandra          latest              4b6f586fd546        37 hours ago        681.3 MB
docker.io/openshift/origin-metrics-hawkular-metrics   latest              3a03e5a58387        37 hours ago        961.7 MB
docker.io/openshift/origin-metrics-heapster           latest              12fd30955a73        37 hours ago        1.037 GB
docker.io/openshift/origin-metrics-deployer           latest              1497218d32e0        37 hours ago        653.5 MB
```
##### Version

```
# oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://pxl0dockr009.dispositivos.bb.com.br:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

**Comment by DirectXMan12** [comment]
That looks like a version mismatch between OpenShift and Heapster (namely, it looks like the difference between an OpenShift which is expecting a response as an array, and a Heapster which is sending a `MetricsList` object instead).  Can you try with `openshift/origin-metrics-heapster:v1.3.0` instead?

**Comment by Shyckymn** [comment]
@DirectXMan12, 
I'm trying to install using the following command:

oc new-app -f metrics-deployer.yaml \
    -p HAWKULAR_METRICS_HOSTNAME=my_server_hostname \
    -p USE_PERSISTENT_STORAGE=false

How can I set the specific version for heapster?

**Comment by Shyckymn** [comment]
@DirectXMan12 I pulled the new version for image:

```
docker.io/openshift/origin-metrics-heapster           latest              12fd30955a73        39 hours ago        1.037 GB
docker.io/openshift/origin-metrics-heapster           v1.3.0              3f80c00bdd32        4 weeks ago         994.8 MB
```

I changed the YAML config for my DC and deleted the POD. The new POD was created with version 1.3.0. 

Now I have the following message in logfiles:

`Oct 20 13:43:20 pxl0dockr009 docker: W1020 15:43:20.303022       1 horizontal.go:99] Failed to reconcile nginx: failed to compute desired number of replicas based on CPU utilization for DeploymentConfig/fap/nginx: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 0/1 of pods`

My hakular-metrics POD has the following WARNs in the log:

```
15:42:00,943 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-5) RESTEASY002142: Multiple resource methods match request "GET /counters/data". Selecting one. Matching methods: [public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.getMetric(javax.ws.rs.container.AsyncResponse,java.lang.String), public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.deprecatedFindCounterDataStats(javax.ws.rs.container.AsyncResponse,java.lang.String,java.lang.String,java.lang.Integer,org.hawkular.metrics.model.param.Duration,org.hawkular.metrics.model.param.Percentiles,org.hawkular.metrics.model.param.Tags,java.util.List,java.lang.Boolean)]
15:42:00,952 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-30) RESTEASY002142: Multiple resource methods match request "GET /counters/data". Selecting one. Matching methods: [public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.getMetric(javax.ws.rs.container.AsyncResponse,java.lang.String), public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.deprecatedFindCounterDataStats(javax.ws.rs.container.AsyncResponse,java.lang.String,java.lang.String,java.lang.Integer,org.hawkular.metrics.model.param.Duration,org.hawkular.metrics.model.param.Percentiles,org.hawkular.metrics.model.param.Tags,java.util.List,java.lang.Boolean)]
15:42:00,985 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) RESTEASY002142: Multiple resource methods match request "GET /counters/data". Selecting one. Matching methods: [public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.getMetric(javax.ws.rs.container.AsyncResponse,java.lang.String), public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.deprecatedFindCounterDataStats(javax.ws.rs.container.AsyncResponse,java.lang.String,java.lang.String,java.lang.Integer,org.hawkular.metrics.model.param.Duration,org.hawkular.metrics.model.param.Percentiles,org.hawkular.metrics.model.param.Tags,java.util.List,java.lang.Boolean)]
15:43:01,047 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-12) RESTEASY002142: Multiple resource methods match request "GET /counters/data". Selecting one. Matching methods: [public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.getMetric(javax.ws.rs.container.AsyncResponse,java.lang.String), public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.deprecatedFindCounterDataStats(javax.ws.rs.container.AsyncResponse,java.lang.String,java.lang.String,java.lang.Integer,org.hawkular.metrics.model.param.Duration,org.hawkular.metrics.model.param.Percentiles,org.hawkular.metrics.model.param.Tags,java.util.List,java.lang.Boolean)]
15:43:01,052 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-26) RESTEASY002142: Multiple resource methods match request "GET /gauges/data". Selecting one. Matching methods: [public void org.hawkular.metrics.api.jaxrs.handler.GaugeHandler.getMetric(javax.ws.rs.container.AsyncResponse,java.lang.String), public void org.hawkular.metrics.api.jaxrs.handler.GaugeHandler.deprecatedFindData(javax.ws.rs.container.AsyncResponse,java.lang.String,java.lang.String,java.lang.Integer,org.hawkular.metrics.model.param.Duration,org.hawkular.metrics.model.param.Percentiles,org.hawkular.metrics.model.param.Tags,java.util.List,java.lang.Boolean)]
15:43:01,075 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-23) RESTEASY002142: Multiple resource methods match request "GET /counters/data". Selecting one. Matching methods: [public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.getMetric(javax.ws.rs.container.AsyncResponse,java.lang.String), public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.deprecatedFindCounterDataStats(javax.ws.rs.container.AsyncResponse,java.lang.String,java.lang.String,java.lang.Integer,org.hawkular.metrics.model.param.Duration,org.hawkular.metrics.model.param.Percentiles,org.hawkular.metrics.model.param.Tags,java.util.List,java.lang.Boolean)]
15:43:01,085 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-10) RESTEASY002142: Multiple resource methods match request "GET /counters/data". Selecting one. Matching methods: [public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.getMetric(javax.ws.rs.container.AsyncResponse,java.lang.String), public void org.hawkular.metrics.api.jaxrs.handler.CounterHandler.deprecatedFindCounterDataStats(javax.ws.rs.container.AsyncResponse,java.lang.String,java.lang.String,java.lang.Integer,org.hawkular.metrics.model.param.Duration,org.hawkular.metrics.model.param.Percentiles,org.hawkular.metrics.model.param.Tags,java.util.List,java.lang.Boolean)]
```

**Comment by DirectXMan12** [comment]
> My hakular-metrics POD has the following WARNs in the log

Hawkular should not affect the HPA, unless it is not running (in which case Heapster will fail to start).

> Now I have the following message in logfiles:

This happens repeatedly?  Does it continue to happen, or go away?  Are there any messages in your Heapster logs?

**Comment by Shyckymn** [comment]
@DirectXMan12 Yes, the metrics warn messages are repeated. 
I attached the metrics logfile:
[metrics.txt](https://github.com/openshift/origin/files/542435/metrics.txt)

For openshift-infra services, all the metrics (CPU, Memory, Network) are being collected.
I created one DC for a NGINX container. In there, the CPU metrics are not being collected. The graphs stay in zero Milicores.

```
# oc get pods -n fap
NAME            READY     STATUS    RESTARTS   AGE
nginx-2-iynoc   1/1       Running   0          1h
```

```
# oc get hpa -n fap
NAME      REFERENCE                TARGET    CURRENT   MINPODS   MAXPODS   AGE
nginx     DeploymentConfig/nginx   30%       0%        1         10        2h

```

Here are my heapster logfile, with debug level = 4:
[heapster.txt](https://github.com/openshift/origin/files/542429/heapster.txt)

**Comment by DirectXMan12** [comment]
this seems to be the relevant line:

> Skipping rates for namespace:fap/pod:nginx-2-iynoc - different create time new:2016-10-20 13:52:26.08581871 -0200 -0200  old:0001-01-01 00:00:00 +0000 UTC

If Heapster skips rate calculation, you won't get CPU info, since CPU is a rate (CPU is natively returned as cumulative CPU time, but when we usually think of CPU, we think of "instantaneous" CPU usage, thus the rate calculation).  I'm not entirely sure *why* it's skipping rate calculation.  It could have something to do with the stub entry, if I had to guess.  If it helps to restart Heapster while the pods in question are still running, then that might confirm some of my suspicions.

**Comment by Shyckymn** [comment]
Heapster isn't being restarted... 
I made one try changing the "metric-resolution" from 15s to 20s and then recreate the pod.

```
# oc get pods --show-all
NAME            READY     STATUS    RESTARTS   AGE
nginx-1-y23ka   1/1       Running   0          9m
```

Still got the message:

`I1021 12:54:45.202253       1 rate_calculator.go:51] Skipping rates for namespace:fap/pod:nginx-1-y23ka/container:nginx - different create time new:2016-10-21 10:42:51.789824705 -0200 -0200  old:0001-01-01 00:00:00 +0000 UTC
`

**Comment by Shyckymn** [comment]
I1021 14:12:25.203762       1 rate_calculator.go:51] Skipping rates for namespace:fap/pod:nginx-2-deploy - different create time new:0001-01-01 00:00:00 +0000 UTC  old:2016-10-21 12:11:56.019518196 -0200 -0200
I1021 14:12:25.204027       1 rate_calculator.go:51] Skipping rates for namespace:fap/pod:nginx-2-deploy/container:deployment - different create time new:0001-01-01 00:00:00 +0000 UTC  ```
old:2016-10-21 12:11:57.203492548 -0200 -0200
I1021 14:12:25.204173       1 pod_based_enricher.go:46] Failed to get pod namespace:fap/pod:nginx-2-deploy from cache: cannot find pod definition
I1021 14:12:25.204216       1 pod_based_enricher.go:46] Failed to get pod namespace:fap/pod:nginx-1-y23ka from cache: cannot find pod definition
I1021 14:12:25.204269       1 pod_based_enricher.go:55] Failed to get pod namespace:fap/pod:nginx-1-y23ka from cache: cannot find pod definition
I1021 14:12:25.204319       1 pod_based_enricher.go:55] Failed to get pod namespace:fap/pod:nginx-2-deploy from cache: cannot find pod definition
```

**Comment by DirectXMan12** [comment]
> Heapster isn't being restarted... 

I was suggesting that if you restarted Heapster, and that fixed the problem, it would confirm my suspicion, but since restarting Heapster to change the metric resolution didn't help anything, it might be a slightly different problem from my initial guess.

**Comment by Shyckymn** [comment]
The strange thing is that any namespace that I create and after that set resource limits, give me the error message "failed to get pod namespace":

```
I1021 15:50:05.315586       1 pod_based_enricher.go:46] Failed to get pod namespace:gecin/pod:nginx-1-deploy from cache: cannot find pod definition
I1021 15:50:05.315718       1 pod_based_enricher.go:55] Failed to get pod namespace:gecin/pod:nginx-1-deploy from cache: cannot find pod definition
```

**Comment by DirectXMan12** [comment]
it's actually "failed to get pod $HEAPSTER_IDENTIFIER", where `$HEAPSTER_IDENTIFIER` is `namespace:$NS/pod:$POD` (the wording of the message could be clearer). Perhaps Heapster is having difficulty communicating with your API server?

**Comment by Shyckymn** [comment]
The strange thing is that the CPU metric collection works for OpenShift infra-namespace.
Any other project that I create and perform some deploy, the CPU metric collection does not work.
It could be any user permission that is missing?
![openshift_metrics](https://cloud.githubusercontent.com/assets/21058463/19640267/a7277390-99ba-11e6-9601-3cd49d415bba.JPG)

**Comment by Shyckymn** [comment]
I also tried to create the deploy within the OpenShift-Infra namespace where other applications are in the collection of metrics working perfectly. But the error persists:
I1024 11: 29: 25.187971 pod_based_enricher.go 1: 46] Failed to get pod namespace: OpenShift-infra / pod: nginx-1-deploy from cache: can not find pod definition
I1024 11: 29: 25.188151 pod_based_enricher.go 1: 55] Failed to get pod namespace: OpenShift-infra / pod: nginx-1-deploy from cache: can not find pod definition

**Comment by DirectXMan12** [comment]
> It could be any user permission that is missing?

That could do it.  It's possible Heapster's ServiceAccount is missing permissions to list pods in any namespace (but by default, it gets permission to list in it's own).  Can you check that?

**Comment by Shyckymn** [comment]
@DirectXMan12 How can I do that? Can you help me with the steps?

**Comment by Shyckymn** [comment]
Guys, you'll not believe...

I decided to delete all objects and create an additional node.
Now, I have one master server and one node server.

So, I created a new project and pushed some images (nginx and httpd) to it.
After deploy, create route, set resource limits and add autoscaler, everything works fine!

I don't know the reason why the "metrics collect" works with nodes but doesn't works with master...

Any ideas?

**Comment by xigang** [comment]
I have the same problem.

~~~
I0717 15:26:05.231253   20646 pod_based_enricher.go:46] Failed to get pod namespace:0/pod:01-20-17-57-54-o0tw6 from cache: cannot find pod definition
I0717 15:26:05.232498   20646 pod_based_enricher.go:55] Failed to get pod namespace:start/pod:05-05-14-21-12-3q3ph from cache: cannot find pod definition
I0717 15:26:05.233080   20646 pod_aggregator.go:57] Pod not found adding namespace:start/pod:05-05-14-21-12-3q3ph
~~~
