### ISSUE TITLE
Clear out used images in extended tests

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#11464]
Suspected ran out of space when doing testextended extended:core(builds) and extended:core(image_ecosystem) at the same time - look at whether docker space can be reclaimed at end of runs.

Example failure: https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/624/

**Comment by bparees** [comment]
specifically we probably want to focus on the images produced by the builds.

it's possible we can leverage oadm prune for this, otherwise shelling to docker rmi commands is acceptable as far as i'm concerned.

**Comment by jim-minter** [comment]
@bparees there's clearly more to this than I had first thought.

The above link has expired and I can't now recall where we were running into space trouble - whether in the docker daemon storage, the storage backing the Openshift registry, or elsewhere.  I think maybe the former but presumably it would be good to take care of both pieces ideally.

If it's the docker daemon storage, then targeted rmi's might help to some extent (e.g. removing additional layers built _above_ S2I images), but with tests running in parallel I'm a little concerned about whether issuing rmi's (especially if I were to use -f) could potentially interfere with other running tests.  I think base images would not be removable in general until the end of the test run.

Things are also problematic WRT the Openshift registry: right now I can't see a straightforward method to reduce storage use, using oadm prune or otherwise, which would help us and which wouldn't risk interfering with parallel tests.

My gut feel as things stand is to close this issue on the grounds that the ends don't justify the means.  What are your thoughts?

**Comment by jim-minter** [comment]
@bparees, does #7101 have any implications for this work?  Effectively, fixing this issue involves adding in calls to the local docker socket for cleanup after pretty much all build extended tests, which looks like the reverse of the direction #7101 is wanting to go.

**Comment by bparees** [comment]
@jim-minter yes, good catch, that would be problematic.  perhaps we can leverage oc adm prune images?

**Comment by bparees** [comment]
i guess that will only prune images from the registry, not the node's local docker daemon library so probably nevermind.

**Comment by bparees** [comment]
(so basically i don't think i have any good ideas here, we may have to just close this unless you do...I don't really want to go down the path of launching privileged pods on the nodes to clean things up)

**Comment by jim-minter** [comment]
yes, I'll close this.  I've opened separate pull requests for other bits and pieces I encountered while working on this.
