### ISSUE TITLE
regular user can create a project but not a namespace?

### ISSUE THREAD

**Issue by jwendell** [openshift/origin#11471]
It seems a regular user is allowed to create a project but not a namespace. Isn't a project simply an [extension of a namespace](https://docs.openshift.com/container-platform/3.3/architecture/core_concepts/projects_and_users.html#projects)?

```
[jwendell@jsantana-temp ~]$ oc version
oc v1.4.0-alpha.0+9ef2b7f
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://192.168.0.105:8443
openshift v1.4.0-alpha.0
kubernetes v1.4.0-beta.3+d19513f

[jwendell@jsantana-temp ~]$ oc whoami 
developer

[jwendell@jsantana-temp ~]$ oc create namespace xuxa
Error from server: User "developer" cannot create namespaces at the cluster scope

[jwendell@jsantana-temp ~]$ oc new-project xuxa
Now using project "xuxa" on server "https://192.168.0.105:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.
```

**Comment by liggitt** [comment]
`oc new-project` creates a projectrequest, which gives a cluster admin control over allowing, denying, or shaping the resulting namespace that gets created (they can define a template that adds quota, etc, to the new namespace)

**Comment by jwendell** [comment]
So, the user is not "allowed" to skip the openshift api and use k8s api directly for ns creation, right?

Doesn't make sense then make the endpoint `/api/v1/namespaces` an alias to `/oapi/v1/projectrequests`?

**Comment by liggitt** [comment]
Some users can use the namespaces API (the cluster admin can, the part of the API server that fulfills the projectrequest API call does, etc), but most regular users cannot.

> Doesn't make sense then make the endpoint /api/v1/namespaces an alias to /oapi/v1/projectrequests?

no, the project request API is different, and it's bad to mask the actual kubernetes API which can still be used by highly privileged users.

**Comment by erikbsap** [comment]
FYI: In OCP 3.7 it's possible to create namespaces apparently, but it may not do the same thing. Question is: should it do the same thing?

I'm strongly in favor of it doing the same thing, because many new users nowadays don't really know what's the difference between kubernetes and openshift.

**Comment by liggitt** [comment]
> FYI: In OCP 3.7 it's possible to create namespaces apparently

Only if you are a superuser

> should it do the same thing?
> I'm strongly in favor of it doing the same thing

No. The project request API instantiates an admin-defined template that can include quota restrictions. The namespace API is a kubernetes API whose behavior we can not and would not change.

**Comment by erikbsap** [comment]
@liggitt You are right. @miminar and I found that someone assigned the cluster-admin clusterrole to the normal user. What a surprise that was.

**Comment by omeryounus** [comment]
how to grant permissions to create namespace?
