### ISSUE TITLE
Lacking extended build tests

### ISSUE THREAD

**Issue by bparees** [openshift/origin#1147]
A lot of build scenarios are currently untested, we need to add some extended tests that validate various build permutations (docker, custom type builds, builds with no output defined, etc).

these are hard to run as mocked integration tests since we really need to run the sti/docker build code to ensure everything is processed correctly, so the right solution is probably to create something like the e2e test, but that does more scenarios and is not a required part of the merge process.

**Comment by mfojtik** [comment]
+1

**Comment by soltysh** [comment]
+1

**Comment by bparees** [comment]
Closing this as we'll handle it in trello:
https://trello.com/c/j4UFRiUN/511-5-more-extended-build-tests
