### ISSUE TITLE
canonical way to find the OAuth authorize URL in a pod?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#11486]
Any web console which wants to reuse the OAuth mechanism in OpenShift needs to know the OAuth URL. e.g. its something like this in OpenShift:

```
https://${APISERVER}:${OAUTH_AUTHORIZE_PORT}/oauth/authorize
```

Up to now we've been using a template parameter and forcing the user to have to configure this value but its error prone & makes apps harder to use on OpenShift.

I wonder is there some way we can find this value, via the Downward API, some canonical environment variable, Secret or REST API? I'd like to make apps easier to just run on OpenShift rather than need careful configuration to be able to do basic things like OAuth authentication.

Even just a way to find the external URL for the API master would do the trick really. (I know inside kubernetes we can use `https://kubernetes/` - its just that doesn't help when doing OAuth in a web browser)

**Comment by liggitt** [comment]
https://github.com/openshift/origin/pull/10845/ adds https://openshift.default.svc/.well-known/oauth-authorization-server (https://tools.ietf.org/html/draft-ietf-oauth-discovery-04) in 1.4

**Comment by jstrachan** [comment]
@liggitt awesome thanks!!
