### ISSUE TITLE
 Suggest, append a comment in dockerregistry/Dockerfile to say what and where is bin/dockerregistry file

### ISSUE THREAD

**Issue by harobed** [openshift/origin#11507]
What is ? and where is ? bin/dockerregistry executable used here: https://github.com/openshift/origin/blob/master/images/dockerregistry/Dockerfile#L10

Suggest, append a comment in Dockerfile to say what and where is this file.

Best regards,
Stéphane

**Comment by harobed** [comment]
I think it's a executable create with this source code:

* main file: https://github.com/openshift/origin/blob/master/cmd/dockerregistry/main.go
* and: https://github.com/openshift/origin/tree/master/pkg/dockerregistry

It's right ?

**Comment by smarterclayton** [comment]
Yes, that is correct.
