### ISSUE TITLE
sample app still uses ruby-20-centos and not centos7

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1151]
There was just a discussion in the training repo about this. Looks like the sample app sti build JSON still uses the old image.

eg: https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json#L114

**Comment by jhadvig** [comment]
@thoraxe there is a PR prepared which is fixing this:
https://github.com/openshift/origin/pull/1121

**Comment by jhadvig** [comment]
@thoraxe fyi https://github.com/openshift/origin/pull/1121 got merged
