### ISSUE TITLE
Go 1.7 compilation issues

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#11511]
A small number of tests are failing on go 1.7 - I'm currently working on the CI infra switch, but we can't merge that until those are fixed.

@sdodson @ncdc @mfojtik @bparees

**Comment by bparees** [comment]
Is there a reason we can't hold the switch until we finish landing 3.4 items?

**Comment by smarterclayton** [comment]
Does not block 3.4 items.

**Comment by sdodson** [comment]
Hmm, for some reason I thought origin was already building with 1.7 in CI. Today's OCP build will be the first to build with 1.7, do we need to switch back to 1.6 for a while?
@tdawson FYI

**Comment by smarterclayton** [comment]
I'm not sure it impacts you, just copied for reference.

On Oct 23, 2016, at 7:15 PM, Ben Parees <notifications@github.com> wrote:

Is there a reason we can't hold the switch until we finish landing 3.4
items?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/11511#issuecomment-255621732>,
or mute the thread

**Comment by smarterclayton** [comment]
The code should work, your unit tests will fail.

**Comment by stevekuznetsov** [comment]
We're compiling with 1.7 fine now.
