### ISSUE TITLE
Config change comparisons do not need to decode DCs

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#11522]
The way we determine config changes for a deployment config foo currently is the following:
1) get latest state of dc/foo
2) get latest rc/foo-n for dc/foo
3) decode dc from rc/foo-n annotation
4) compare decoded dc template with live dc template

Instead of decoding every time the DC from the annotation, we could simply remove the additional annotations/labels we set on RCs and compare the RC directly with the DC. [Note that that's the way we do the comparisons in upstream Deployments](https://github.com/kubernetes/kubernetes/blob/c615e094b80b82435de19a69d67f84418a97a203/pkg/controller/deployment/util/deployment_util.go#L505).

Pros:
- we stop decoding every time we need to compare

Cons:
- users tampering with their RCs won't get the expected behavior. That this can still happen currently by changing the serialized annotation though.

Thoughts @smarterclayton @mfojtik

**Comment by smarterclayton** [comment]
If upstream deployments would be broken if the user mucked with the RS,
then we're ok mucking with it.

**Comment by kargakis** [comment]
It would be nice if replica sets for deployments would be immutable except
rs.spec.replicas

**Comment by kargakis** [comment]
I think upstream is moving on the opposite direction with Deployments.

**Comment by kargakis** [comment]
https://docs.google.com/document/d/10LFy30JTfTD3qgCsBZ2S8ZpuWao9mqT_xqkcbvPzVf4/edit?ts=5b036da4#heading=h.l3tv7bl8l1r1
