### ISSUE TITLE
Provide a way to manually invoke non-automatic ImageChange triggers

### ISSUE THREAD

**Issue by elyscape** [openshift/origin#11538]
If a DeploymentConfig has an ImageChange trigger configured, a new deployment will be triggered any time the image changes. [If `imageChangeParams.automatic` is set to `false`](https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-deploymenttriggerimagechangeparams), this does not happen, for obvious reasons. However, in this scenario, there is no way to manually invoke the trigger.

There was a workaround in versions of OpenShift Origin prior to 1.3.0; changing a targeted container's image value would cause the ImageChange trigger to fire and update it to the current image pointed at by the specified ImageStreamTag, allowing you to invoke the ImageChange trigger by just setting the value of `image` to some dummy value or even removing it. Since 1.3.0, however, this does not occur, and the dummy value remains.

There is a way to permanently enable all ImageChange triggers on a DeploymentConfig: running `oc deploy $DC --enable-triggers` will set `imageChangeParams.automatic` to `true` on all ImageChange triggers. Unfortunately, there is no easy way to disable them again. It can be done on the command line, if one has [`jq`](https://stedolan.github.io/jq/) installed, with this set of commands:

``` shellsession
scapeless:~ elyscape$ oc get dc somedc -o json |
> jq '.spec.triggers[] |= if .imageChangeParams then .imageChangeParams.automatic = false else . end' |
> oc replace -f -
deploymentconfig "somedc" replaced
```

This is, of course, cumbersome and non-ideal. It also requires one to have `jq` installed and doesn't really provide a way to specify which ImageChange triggers should be enabled or disabled (in theory this should be possible given fancy commands to `jq`, but, again, cumbersome and non-ideal).

Ideally, there would be an API and CLI command to manually invoke a ImageChange triggers on a given DeploymentConfig, with the ability to optionally specify which trigger(s) should be invoked.
##### Version

```
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server [REDACTED]
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

**Comment by kargakis** [comment]
'oc rollout latest' and 'oc set triggers' is what you are after. The former is in 1.4, the latter is in 1.3. Most of the deploy flags will be deprecated in 1.4, I would like to deprecate the whole command.

**Comment by elyscape** [comment]
Aha! `oc rollout latest` is what I'm looking for. Thanks for pointing it out to me!

That being said, it would be nice if there were a way to specify to `oc rollout latest` that it shouldn't perform a deployment if the the images haven't changed. I don't see anything like that at present.

**Comment by kargakis** [comment]
> That being said, it would be nice if there were a way to specify to oc rollout latest that it shouldn't perform a deployment if the the images haven't changed. I don't see anything like that at present.

@smarterclayton @mfojtik any ideas on this? We have `Force` in the deployment request that always runs deployments. That's the appropriate field for using to not force deployments (for example the trigger controller always uses force=false to not start deployments when there is nothing new to deploy) but we also need a separate field that will help us separate between the trigger controller calling instantiate and all other clients (manual updates) because so far we have been separating based on the use of Force. I think that field should be the same as the upstream change-cause annotation or our dc.status.details field.
