### ISSUE TITLE
imagerepos broken for multiple tags w/ same imageid

### ISSUE THREAD

**Issue by bparees** [openshift/origin#1154]
This commit: https://github.com/openshift/origin/commit/361cdea6819f960d39b19f69a1c08ae04257ed2e#diff-5471a801fd55d5af2f431056b6d24254

appears to have made it such that you can't push two different tags for the same image...(ie tag an image as "test" and then later push a prod tag for that same image).

You can see here that my repo does not contain the prod tag, and the json for what is being pushed does contain the prod tag, yet it gets rejected as being identical:
https://gist.github.com/bparees/5235b5bbccad7a78a44d

@smarterclayton @ncdc

**Comment by smarterclayton** [comment]
We should definitely let you tag it multiple times, just not create it (filter out duplicates).  Creating one that already exists and is identical should be "success"

**Comment by ncdc** [comment]
I have a fix for this

**Comment by ncdc** [comment]
It's part of a larger refactoring effort, however. I'll try to submit a PR today.

**Comment by smarterclayton** [comment]
Do we need larger refactors right before beta2?  The answer can be yes if the arguments are good enough :)

**Comment by ncdc** [comment]
It's for https://trello.com/c/ZPKh3cBp/296-3-management-of-historical-image-repository-tags-imageregistry-beta2. Do you want a small PR to fix just this issue?

**Comment by ncdc** [comment]
I've got a small PR to fix this coming right up in a few minutes :-)
