### ISSUE TITLE
If new build of application fails, deploy pod still waits 10 minutes

### ISSUE THREAD

**Issue by robstryker** [openshift/origin#11541]
##### Version
Whatever is included in CDK weekly builds

##### Steps To Reproduce
0. Make sure attempts to resolve github.com fail
1. Start CDK weekly build
2. In JBossTools, right-click an application, and select "Deploy Latest". This will start both a build and a deploy pod. The deploy pod will wait for the build pod to complete.
3. Go to 10.1.2.2:8443/console/project/name/pods and look at running pods.  

##### Current Result
Build pod fails, deploy pod takes 10 minutes to fail

##### Expected Result
Expect to see two pods both failed:  build pod and deploy pod

There is no reason for deploy pod to wait 10 minutes. It is waiting for build pod to complete, but it should also notice when build pod has failed and then abort the deploy pod. 

See https://issues.jboss.org/browse/JBIDE-23402  for more information.

**Comment by kargakis** [comment]
> In JBossTools, right-click an application, and select "Deploy Latest". This will start both a build and a deploy pod. The deploy pod will wait for the build pod to complete.

I am not familiar with the way JBossTools works and this is probably an issue for that component ie. not something we can do anything about in Origin. The common build-deploy flow we use in our pipeline and template examples spins a build and waits for it to finish before starting the deployer pod. For example, if you run examples/sample-app/application-template-stibuild.json and the build never succeeds, then a new deployment will never start.

**Comment by kargakis** [comment]
There is also https://github.com/kubernetes/kubernetes/issues/18568 upstream that once fixed will allow us to abort deployments that we know will never succeed such as trying to deploy an image that doesn't exist earlier than the timeout.

**Comment by robstryker** [comment]
>      I am not familiar with the way JBossTools works and this is probably an issue for that component ie. not something we can do anything about in Origin. 

Sorry, this is not just a JBT bug. It is a bug in origin.   The only question is what the "deploy latest" action does. The fact is, the deploy pod sits around for 10 minutes waiting for the build pod, even if the build pod has failed. 

@adietish Any comments?

**Comment by kargakis** [comment]
@robstryker the deployer pod should start once the build succeeds, otherwise what image are you trying to deploy if it's not built yet?

**Comment by robstryker** [comment]
I understand that the deployer pod should start once the build succeeds. This is working as expected. 

The deployer pod should also FAIL QUICKLY if the build pod FAILS. 

Currently, the deployer pod is sitting around waiting for build pod to succeed. Build pod fails, and deployer pod is still waiting. It is waiting for an event that will never happen. Build pod cannot succeed, since it already failed. Deploy pod is waiting for nothing. Deploy pod should abort once build pod fails.
