### ISSUE TITLE
Support HTTP->HTTPS redirection on non-edge terminated routes

### ISSUE THREAD

**Issue by elyscape** [openshift/origin#11547]
Edge-terminated routes allow you to set [`insecureEdgeTerminationPolicy`](https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-tlsconfig) to `redirect`, which makes causes the router to respond to HTTP requests with 302 Found and a redirect to the same location over HTTPS. If, however, you're using a reencrypt or passthrough route, this is not an option. While it would be relatively simple to set up another, HTTP-only route pointing at a service that used nginx to respond to all requests with a redirect to HTTPS, this seems like the sort of thing that could be trivially handled by the router. Maybe a `redirectInsecureRequests` field could be added?
##### Version

```
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server [REMOVED]
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

**Comment by knobunc** [comment]
This is https://trello.com/c/0BaxAOK9 and there's bug https://bugzilla.redhat.com/show_bug.cgi?id=1306216 open too.  We are working on it.
