### ISSUE TITLE
Different IPs created on `oc cluster up` in different networks

### ISSUE THREAD

**Issue by bdshadow** [openshift/origin#11553]
`oc cluster up` done once at home launches OS server that is not accessible in office
##### Version

oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.40.4.227:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
##### Steps To Reproduce

1) i do `oc cluster up` at home and get server accessible on https://192.168.0.24:8443. Everything works fine (i have internet via WiFi router)
2) then i close my laptop lid, it falls asleep and go to office
3) put the ethernet cable into the laptop 
4) try to continue working with OS created at home - everything hangs and not accessible
5) do `oc cluster down` and `oc cluster up` and server is up with https://10.40.4.227:8443 IP address
6) disconnected the cable, connected to wifi office network, needed to repeat steps 4 and 5. Now have  https://10.202.13.186:8443

**Comment by csrwng** [comment]
This is working as designed. However, it does cause issues with saved config and such. A couple of other issues have been opened about it. 

A workaround that you can try at least for now is to use `--public-hostname=127.0.0.1` with `oc cluster up`.

**Comment by csrwng** [comment]
Fixed with #13112
