### ISSUE TITLE
"permission denied" error when writing to provisioned gluster volumes.

### ISSUE THREAD

**Issue by humblec** [openshift/origin#11556]
A PVC is BOUND to a Gluster PV and attached to an app pod ( for ex: fedora container). When writing to this  mount path inside this container, it throws out "permission denied" error.

sh-4.3$ df -h .
Filesystem                                         Size  Used Avail Use% Mounted on
10.70.41.220:vol_cf226e24f9424425dd89e1df63f0f5de   50G   67M   50G   1% /mnt/glusterfs
sh-4.3$ pwd
/mnt/glusterfs
sh-4.3$ touch 1
touch: cannot touch '1': Permission denied
sh-4.3$ 

[root@dhcp43-179 ~]# oc get pvc
NAME              STATUS    VOLUME               CAPACITY   ACCESSMODES   AGE
glusterfs-claim   Bound     glusterfs-cf226e24   50Gi       RWX           33m
[root@dhcp43-179 ~]# oc get pv
NAME                 CAPACITY   ACCESSMODES   STATUS    CLAIM                  REASON    AGE
glusterfs-cf226e24   50Gi       RWX           Bound     default/glusterfs-claim             34m
##### Current Result

The application write fails on the persitent volume.
##### Expected Result

The application pod should be able to write to this share.

**Comment by humblec** [comment]
#### Additional Info or RCA 
The issue is that volumes come with UID/GID of 0 (root).  For a container to be able to write to them, we need to have the container also have a root ID, but this, of course, is not a good solution.

**Comment by humblec** [comment]
Tracked with PR # https://github.com/kubernetes/kubernetes/pull/35460

**Comment by jhou1** [comment]
@humblec I see https://github.com/kubernetes/kubernetes/pull/21304 is merged upstream, do you know when this will be merged in OCP? Thanks!

**Comment by humblec** [comment]
@jhou1 iic you meant https://github.com/kubernetes/kubernetes/pull/35460 instead of https://github.com/kubernetes/kubernetes/pull/35460 .  If that is the case, the origin PR is here #https://github.com/openshift/origin/pull/11893 . @childsb can you please help to get it merged in OCP 3.4 tree ?

**Comment by jhou1** [comment]
Thank you!
