### ISSUE TITLE
Update kube dep to latest release-1.4 sha

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#11565]
There are a number of fixes that have been patched to the version that we are currently carrying in our godeps.  
##### Version

current origin master
##### Steps To Reproduce
1. checkout upstream release-1.4 branch 
2. do a diff from our Godep sha to latest 
   `git log --pretty=oneline 776c99451414ec6ba...origin/release-1.4 | wc -l` 
##### Current Result

224 patches
##### Expected Result

much smaller set.
##### Additional Information

contains etcd3 clientv3 performance fixes that we're uncovered during validation. 

/cc @pweil- @smarterclayton @mffiedler

**Comment by pweil-** [comment]
@mfojtik - need to decide if there are critical patches that are required to pick, if we can safely (and quickly) do a refresh of the existing dependency), or if we cannot do this for 3.4.

cc @liggitt

**Comment by pweil-** [comment]
For the record I think there is too much risk and not enough time for a full refresh and that we should be looking for critical patches to pull in.

**Comment by smarterclayton** [comment]
I'll push a rebase branch that contains the upstream cherry-picks to at
least test.  While someone evaluates the list.

**Comment by timothysc** [comment]
@jayunit100 try to see if you can cherry-pick back the check-service affinity patch again after this lands.

**Comment by soltysh** [comment]
https://github.com/openshift/origin/pull/11709 merged. I'm trying to cherry pick 35205 in https://github.com/openshift/origin/pull/11749, but that currently has quite a few tests issues. If those don't get addressed by tomorrow, we'll just go with what was introduced in the former.

**Comment by timothysc** [comment]
Closing, thanks for the update!

**Comment by jayunit100** [comment]
Looks like checkServiceAffinity is still  > 1 commits behind, so , we wont be able to cleanly rebase it on to this one., wait till next rebase i guess.
