### ISSUE TITLE
Error on 'docs/cluster_up_down.md' to perform an 'oc cluster up' on a latest release

### ISSUE THREAD

**Issue by padajuan** [openshift/origin#11580]
[provide a description of the issue]
The issue comes when you try to perform a `oc cluster up` on a 'latest' release published at Github, this is because if you create a new release on GitHub of a previous version of 1.3.X, you have not the proper release to perform this action

##### Version
N/A

##### Steps To Reproduce
1. Install Docker with your platform's package manager.
2. Configure the Docker daemon with an insecure registry parameter of `172.30.0.0/16`
   In RHEL and Fedora, edit the `/etc/sysconfig/docker` file and add or uncomment the following line:

   ```
   INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'
   ```
   After editing the config, restart the Docker daemon.

3. Download the Linux `oc` binary from
   [openshift-origin-client-tools-VERSION-linux-64bit.tar.gz](https://github.com/openshift/origin/releases/latest)
   and place it in your path.

4. Open a terminal with a user that has permission to run Docker commands and run:

##### Current Result
You will download a latest pushed release, could be 1.2 for example

##### Expected Result
Always perform an `oc cluster up` to run OCP

##### Additional Information
DOC Error

**Comment by padajuan** [comment]
The new Pull request [Here](https://github.com/openshift/origin/pull/11585)

**Comment by coreydaley** [comment]
Closed via #11585
