### ISSUE TITLE
Cherry picking: Some notes / thoughts on improving it...

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#11582]
Problem: 

hack/cherry-pick.sh is error prone and can be tricky to use.  

Solution:

Not sure what the exact solution is, but here are some notes so far...
- We should state `remote upstream kubernetes` branches , rather than "remote upstream", which might help clarify things/prevent errors when setting up fetch remotes.
- We also should just directly show the snippet for kube: 

```
[remote "origin"]
        url = https://github.com/kubernetes/kubernetes
        fetch = +refs/heads/*:refs/remotes/origin/*
        fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
```
- It appears to me that even in the case of merge conflicts,...

```
++ Generating patch for 71249bb82b55f4a09a7b1a53016562f0804883be..182e89b84edf407ebbe56f0cffa117f6a47c8f36 onto 776c994 ...
...
Applied patch to 'plugin/pkg/scheduler/algorithm/types.go' with conflicts.
error: patch failed: plugin/pkg/scheduler/generic_scheduler.go:113
Falling back to three-way merge...
Applied patch to 'plugin/pkg/scheduler/generic_scheduler.go' with conflicts.
++ Merge conflicts when generating patch, please resolve conflicts and then press ENTER to continue
```

... somehow my attempt at cherry-pick showed a clean working tree and status:

```
➜  kubernetes git:(last_upstream_branch) git status
On branch last_upstream_branch
nothing to commit, working tree clean
```

Maybe this is a bug in the script?  I'm assuming when it sais "resolve the conflicts" 

cc @ncdc @pweil-

**Comment by pweil-** [comment]
the output there definitely looks like you would have had a dirty tree with items to resolve. @mfojtik @soltysh

**Comment by soltysh** [comment]
I recently fallback to manual wget <pr_link>.diff, replace dirs to `vendor/k8s.io/kubernetes` and `git apply --reject` since I was having some problems with that script, especially that I have to go paths for origin and k8s.

**Comment by ncdc** [comment]
@soltysh that's what `git apply --directory` is for :-)
