### ISSUE TITLE
Tests failing with Docker 1.12

### ISSUE THREAD

**Issue by danmcp** [openshift/origin#11591]
From: https://ci.openshift.redhat.com/jenkins/job/base_ami/2460/console

I1026 13:28:47.178541   11616 router_http_server.go:208] Stopping listener at 172.18.1.127:8443
--- FAIL: TestRouter (0.30s)
	router_test.go:71: Error starting container openshift/origin-haproxy-router : API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
FAIL
Running TestRouterDuplications...
failed  TestRouterDuplications
I1026 13:28:47.368426   11651 router_http_server.go:303] Started, serving at 172.18.1.127:8080
I1026 13:28:47.368496   11651 router_http_server.go:303] Started, serving at 172.18.1.127:8888
I1026 13:28:47.368537   11651 router_http_server.go:303] Started, serving at 172.18.1.127:8889
I1026 13:28:47.369113   11651 router_http_server.go:335] Started, serving TLS at 172.18.1.127:8443
I1026 13:28:47.624233   11651 router_http_server.go:208] Stopping listener at 172.18.1.127:8080
I1026 13:28:47.624256   11651 router_http_server.go:208] Stopping listener at 172.18.1.127:8888
I1026 13:28:47.624266   11651 router_http_server.go:208] Stopping listener at 172.18.1.127:8889
I1026 13:28:47.624275   11651 router_http_server.go:208] Stopping listener at 172.18.1.127:8443
--- FAIL: TestRouterDuplications (0.26s)
	router_test.go:750: Error starting container openshift/origin-haproxy-router : API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
FAIL
Running TestRouterHealthzEndpoint...
failed  TestRouterHealthzEndpoint
I1026 13:28:47.811038   11684 router_http_server.go:303] Started, serving at 172.18.1.127:8080
I1026 13:28:47.811109   11684 router_http_server.go:303] Started, serving at 172.18.1.127:8888
I1026 13:28:47.811153   11684 router_http_server.go:303] Started, serving at 172.18.1.127:8889
I1026 13:28:47.814772   11684 router_http_server.go:335] Started, serving TLS at 172.18.1.127:8443
I1026 13:28:48.073397   11684 router_http_server.go:208] Stopping listener at 172.18.1.127:8080
I1026 13:28:48.073419   11684 router_http_server.go:208] Stopping listener at 172.18.1.127:8888
I1026 13:28:48.073426   11684 router_http_server.go:208] Stopping listener at 172.18.1.127:8889
I1026 13:28:48.073433   11684 router_http_server.go:208] Stopping listener at 172.18.1.127:8443
--- FAIL: TestRouterHealthzEndpoint (0.26s)
	router_test.go:936: Test with "stats port enabled" error starting container openshift/origin-haproxy-router : API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
FAIL
Running TestRouterPathSpecificity...
failed  TestRouterPathSpecificity
I1026 13:28:48.261452   11717 router_http_server.go:303] Started, serving at 172.18.1.127:8080
I1026 13:28:48.261528   11717 router_http_server.go:303] Started, serving at 172.18.1.127:8888
I1026 13:28:48.261578   11717 router_http_server.go:303] Started, serving at 172.18.1.127:8889
I1026 13:28:48.262062   11717 router_http_server.go:335] Started, serving TLS at 172.18.1.127:8443
I1026 13:28:48.512422   11717 router_http_server.go:208] Stopping listener at 172.18.1.127:8080
I1026 13:28:48.512457   11717 router_http_server.go:208] Stopping listener at 172.18.1.127:8888
I1026 13:28:48.512473   11717 router_http_server.go:208] Stopping listener at 172.18.1.127:8889
I1026 13:28:48.512482   11717 router_http_server.go:208] Stopping listener at 172.18.1.127:8443
--- FAIL: TestRouterPathSpecificity (0.25s)
	router_test.go:391: Error starting container openshift/origin-haproxy-router : API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
FAIL
Running TestRouterReloadCoalesce...
failed  TestRouterReloadCoalesce
I1026 13:28:48.702667   11750 router_http_server.go:303] Started, serving at 172.18.1.127:8080
I1026 13:28:48.702729   11750 router_http_server.go:303] Started, serving at 172.18.1.127:8888
I1026 13:28:48.702780   11750 router_http_server.go:303] Started, serving at 172.18.1.127:8889
I1026 13:28:48.703225   11750 router_http_server.go:335] Started, serving TLS at 172.18.1.127:8443
I1026 13:28:48.974609   11750 router_http_server.go:208] Stopping listener at 172.18.1.127:8080
I1026 13:28:48.974636   11750 router_http_server.go:208] Stopping listener at 172.18.1.127:8888
I1026 13:28:48.974652   11750 router_http_server.go:208] Stopping listener at 172.18.1.127:8889
I1026 13:28:48.974661   11750 router_http_server.go:208] Stopping listener at 172.18.1.127:8443
--- FAIL: TestRouterReloadCoalesce (0.27s)
	router_test.go:1505: Error starting container openshift/origin-haproxy-router : API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
FAIL
Running TestRouterReloadSuppressionOnSync...
ok      TestRouterReloadSuppressionOnSync
Running TestRouterServiceUnavailable...
failed  TestRouterServiceUnavailable
I1026 13:28:55.280858   11798 router_http_server.go:303] Started, serving at 172.18.1.127:8080
I1026 13:28:55.280926   11798 router_http_server.go:303] Started, serving at 172.18.1.127:8888
I1026 13:28:55.280971   11798 router_http_server.go:303] Started, serving at 172.18.1.127:8889
I1026 13:28:55.281417   11798 router_http_server.go:335] Started, serving TLS at 172.18.1.127:8443
I1026 13:28:55.536864   11798 router_http_server.go:208] Stopping listener at 172.18.1.127:8080
I1026 13:28:55.536904   11798 router_http_server.go:208] Stopping listener at 172.18.1.127:8888
I1026 13:28:55.536921   11798 router_http_server.go:208] Stopping listener at 172.18.1.127:8889
I1026 13:28:55.536936   11798 router_http_server.go:208] Stopping listener at 172.18.1.127:8443
--- FAIL: TestRouterServiceUnavailable (0.26s)
	router_test.go:973: Error starting container openshift/origin-haproxy-router : API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
FAIL
Running TestRouterStatsPort...
failed  TestRouterStatsPort
I1026 13:28:55.721275   11833 router_http_server.go:303] Started, serving at 172.18.1.127:8080
I1026 13:28:55.721337   11833 router_http_server.go:303] Started, serving at 172.18.1.127:8888
I1026 13:28:55.721376   11833 router_http_server.go:303] Started, serving at 172.18.1.127:8889
I1026 13:28:55.721872   11833 router_http_server.go:335] Started, serving TLS at 172.18.1.127:8443
I1026 13:28:55.984881   11833 router_http_server.go:208] Stopping listener at 172.18.1.127:8080
I1026 13:28:55.984908   11833 router_http_server.go:208] Stopping listener at 172.18.1.127:8888
I1026 13:28:55.984916   11833 router_http_server.go:208] Stopping listener at 172.18.1.127:8889
I1026 13:28:55.984923   11833 router_http_server.go:208] Stopping listener at 172.18.1.127:8443
--- FAIL: TestRouterStatsPort (0.26s)
	router_test.go:882: Error starting container openshift/origin-haproxy-router : API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

**Comment by smarterclayton** [comment]
This is the networking team.

**Comment by smarterclayton** [comment]
They need to stop passing host config to start container.
