### ISSUE TITLE
Build tito in hack container

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#11603]
- Sort out tito output directories (concerned about size of BASETMPDIR for most hack/env runs - should we just be using _output)
- Add tito to release images
- Need to create a fake golang package in the release images, because we're testing with upstream golang, and so we'll need to test against those and the centos packages.
- Need to get actual version injected
- Do we need the `-0` on the package version if we're always building incremental?  Is that standard (can't remember)

@stevekuznetsov we're close.

**Comment by smarterclayton** [comment]
Also turn off test building.

**Comment by smarterclayton** [comment]
We don't need to actually build release zips in build-cross.  That might save some time.

**Comment by smarterclayton** [comment]
```
$ sudo du -sh /var/lib/docker/volumes/local/_data/_output
2.1G	/var/lib/docker/volumes/local/_data/_output
```

That's a bit painful.

**Comment by stevekuznetsov** [comment]
`_output` was always for things that we wanted to stick around after the fact, `$BASETMPDIR` for stuff Jenkins would download but we could throw away usually.

**Comment by stevekuznetsov** [comment]
https://github.com/dgoodwin/tito/pull/236 will allow us to tag versions correctly with `tito` and a `.spec` file that has `0.0.1`

**Comment by stevekuznetsov** [comment]
https://github.com/openshift/origin/pull/11618 lets us skip tests

**Comment by stevekuznetsov** [comment]
We're fixed now.
