### ISSUE TITLE
oc run --dry-run gives error that cannot list all pods in the cluster.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#11605]
If want to see what resources `oc run` would create when using `--dry-run` option, it fails with the error:

```
$ oc run test -i --tty --rm --image=busybox --dry-run -o json
Error from server: User "developer" cannot list all pods in the cluster
```

If try and do it as system admin via `sudoers` role, then times out.

```
$ oc run test -i --tty --rm --image=busybox --dry-run -o json --as system:admin
error: timed out waiting for the condition
```
##### Version

oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4
##### Steps To Reproduce

Run the command:

```
oc run test -i --tty --rm --image=busybox --dry-run -o json
```
##### Current Result

Outputs error:

```
Error from server: User "developer" cannot list all pods in the cluster
```
##### Expected Result

Output the resources that would be created.

**Comment by fabianofranz** [comment]
Some flags like the ones that make `run` interactive (`--attach`, `--stdin` and `--tty`) must not be used with `--dry-run`, it doesn't make sense. The command should validate it and throw a proper usage error.
