### ISSUE TITLE
`openshift start master` should not automatically create a node entry

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1161]
While it is helpful for `openshift start` to automatically add `$(hostname -f)` as a node for the 30-second all-in-one startup scenario, this is not desirable when starting just the master; nodes should be added explicitly, and we can't assume the master will be one. The self entry in that case is likely to confuse and, being defined automatically, may not specify resource availability consistently with the way other nodes are defined even if it is desired.

We discussed other flags for preventing auto-adding self as node at startup, but the simplest/clearest approach seems to be to distinguish `openshift start` (where you would need and expect self to be added) from `openshift start master` (where you would not).

**Comment by brenton** [comment]
+1

**Comment by brenton** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1191357
