### ISSUE TITLE
RFE: show me groups I'm assigned to

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#11611]
`oc whoami` can give you information about your current user, it would be nice to also present which groups I'm a member of, including the virtual groups. 
Maybe something like `oc whoami --groups`?

@deads2k @liggitt thoughts?

**Comment by mfojtik** [comment]
@deads2k I think we have "can-i" endpoint but we are lacking CLI tooling right?

**Comment by mfojtik** [comment]
I like the `oc whoami --groups --roles`

**Comment by liggitt** [comment]
there's no user-accessible API which lists groups by user, or roles by user

roles would be at multiple levels, cluster-wide, and per-namespace

**Comment by abstractj** [comment]
@liggitt @soltysh would you mind if I give it a try?

**Comment by soltysh** [comment]
@abstractj sure, we're open to PRs :)

**Comment by bparees** [comment]
@simo5 i think this falls under your area?  if not you can assign it over to @mfojtik
