### ISSUE TITLE
No way to access OpenShift Origin 1.2 documentation after the 1.3 release

### ISSUE THREAD

**Issue by exowaucka** [openshift/origin#11623]
I'm still running OpenShift Origin 1.2.  I want to read the documentation without having to guess which parts only apply to 1.3.  If the 1.2 documentation exists anywhere, it's pretty well-hidden.  All Google queries lead to https://docs.openshift.org/latest (the 1.3 documentation).

**Comment by kargakis** [comment]
@openshift/team-documentation

**Comment by stevekuznetsov** [comment]
Should probably open an issue with github.com/openshift/openshift-docs as that would be a more appropriate place to track

**Comment by exowaucka** [comment]
[Issue](https://github.com/openshift/openshift-docs/issues/3128) opened on openshift-docs.
