### ISSUE TITLE
devenv_ami failing on missing zip

### ISSUE THREAD

**Issue by danmcp** [openshift/origin#11625]
https://ci.openshift.redhat.com/jenkins/job/devenv_ami/5258/consoleFull

which: no bsdtar in (/data/src/github.com/openshift/origin/_output/etcd/bin:/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64:/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin)
++ Creating openshift-origin-client-tools-v1.4.0-alpha.0+9f85202-857-mac.zip
5b6e6d6f3617e5501e1aa9ee9c6ce3b5f6ecfaed0ee02be14ebdc7e1cea0a7d9  oc
/data/src/github.com/openshift/origin/hack/common.sh: line 504: zip: command not found
[ERROR] PID 10587: hack/common.sh:504: `zip "${OS_LOCAL_RELEASEPATH}/${archive_name}" -qj "${release_binpath}/${file}"` exited with status 127.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/common.sh:504: `zip "${OS_LOCAL_RELEASEPATH}/${archive_name}" -qj "${release_binpath}/${file}"`
[INFO] 		  2: hack/common.sh:462: os::build::archive_zip
[INFO] 		  3: hack/build-cross.sh:37: os::build::place_bins
[INFO]   Exiting with code 127.
[ERROR] PID 2365: hack/common.sh:390: `os::build::place_bins "${OS_CROSS_COMPILE_BINARIES[@]}"` exited with status 127.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/common.sh:390: `os::build::place_bins "${OS_CROSS_COMPILE_BINARIES[@]}"`
[INFO] 		  2: hack/build-cross.sh:37: os::build::place_bins
[INFO]   Exiting with code 127.
make: *** [build-cross] Error 127

**Comment by smarterclayton** [comment]
You also need bsdtar.
