### ISSUE TITLE
[networking][router] weighted openshift router flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#11649]
```
• Failure [156.277 seconds]
[networking][router] weighted openshift router
/data/src/github.com/openshift/origin/test/extended/router/weighted.go:112
  The HAProxy router
  /data/src/github.com/openshift/origin/test/extended/router/weighted.go:111
    should appropriately serve a route that points to two services [It]
    /data/src/github.com/openshift/origin/test/extended/router/weighted.go:110

    Expected error:
        <*errors.errorString | 0xc82017a980>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    not to have occurred

    /data/src/github.com/openshift/origin/test/extended/router/weighted.go:56
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/7997/consoleFull#39374030356cbb9a5e4b02b88ae8c2f77

**Comment by bparees** [comment]
(defaulting to p1 per new flake priorities)

**Comment by knobunc** [comment]
From docker.journal in artifacts:
````
Oct 28 14:12:54 ip-172-18-15-109.ec2.internal dockerd-current[2180]: E1028 18:12:54.208082       1 reflector.go:203] github.com/openshift/origin/pkg/router/template/service_lookup.go:30: Failed to list *api.Service: User "system:serviceaccount:extended-test-scoped-router-j2yjk-6fq93:default" cannot list all services in the cluster
````

Which means this is bug 1380669 [link](https://bugzilla.redhat.com/show_bug.cgi?id=1380669)

**Comment by knobunc** [comment]
Resolved by #11713

**Comment by bparees** [comment]
happened again here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8472/

**Comment by knobunc** [comment]
I think the new symptom is a dupe of https://github.com/openshift/origin/issues/11016

**Comment by bparees** [comment]
reopening as the discussion in #11016 implies these tests need to be fixed individually to tolerate the longer start times: https://github.com/openshift/origin/issues/11016#issuecomment-268802384

**Comment by bparees** [comment]
(and i've seen this one several times lately, but it was reported against #11016)

**Comment by smarterclayton** [comment]
New process is going to be closing as dupe of #11016.  I also added increased timeouts to every failing dupe.
