### ISSUE TITLE
Deployment controller hot-looping

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#11656]
Not sure what caused it but I see 100% of CPU usage and this messages in logs repeating really fast:

```
I1031 11:43:17.687064   17026 controller.go:296] Updated the status for "test/deployment-simple" (observed generation: 3)
I1031 11:43:17.687391   17026 factory.go:124] Updating deployment config "deployment-simple"
I1031 11:43:17.689825   17026 controller.go:296] Updated the status for "test/deployment-simple" (observed generation: 3)
I1031 11:43:17.690434   17026 factory.go:124] Updating deployment config "deployment-simple"
I1031 11:43:17.692912   17026 controller.go:296] Updated the status for "test/deployment-simple" (observed generation: 3)
```

I was playing with `test/extended/testdata/deployments/deployment-with-ref-env.yaml` (oc deploy --latest / oc rollout / pause/ resume) but I don't know what exactly caused the hot-loop.

**Comment by mfojtik** [comment]
@kargakis feel free to decrease the priority.

**Comment by kargakis** [comment]
Found it, we are hotlooping between changing the condition from paused to complete. Working on a fix.

**Comment by kargakis** [comment]
Simple to reproduce: start a new rollout, pause it, observed the dc controller getting into the hotloop once the rolllout completes.
