### ISSUE TITLE
should support a client that connects, sends no data, and disconnects

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#11662]
```
• Failure [116.452 seconds]
[k8s.io] Port forwarding
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:793
  [k8s.io] With a server that expects a client request
  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:793
    should support a client that connects, sends no data, and disconnects [Conformance] [It]
    /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/portforward.go:220

    Oct 31 07:45:07.478: Pod did not stop running: timed out waiting for the condition

    /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/portforward.go:210
------------------------------
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8026/consoleFull#-80183125256cbb9a5e4b02b88ae8c2f77

**Comment by derekwaynecarr** [comment]
@sjenning -- am i remembering incorrectly that you signed up for port-forwarding after @ncdc moved on?

**Comment by ncdc** [comment]
This is happening upstream too occasionally. https://github.com/kubernetes/kubernetes/issues/26955

**Comment by ncdc** [comment]
@sjenning if you do take this over, I will happily give you a brain dump on how port forwarding works

**Comment by derekwaynecarr** [comment]
per our discussion in blocker call, we are marking this p2 while we track the same flake upstream.

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/9535/

**Comment by marun** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/9752
