### ISSUE TITLE
atomic registry missing DOCKER_REGISTRY_SERVICE_HOST env var

### ISSUE THREAD

**Issue by thomasmckay** [openshift/origin#11670]
https://github.com/openshift/origin/blob/master/examples/atomic-registry/systemd/install.sh#L71

Without this env var, docker push to registry gives errors like this (note the invalid value message):
```
Oct 31 12:47:46 registry.example.com atomic-registry[14455]: time="2016-10-31T16:47:46.452183896Z" level=error 
msg="error creating ImageStreamMapping: ImageStreamMapping \"test-for-echo\" is invalid: image.dockerImageReference: Invalid value: \":5001/thomasmckay/test-for-echo@sha256:bb6345201244ea4f80457b9df0d83d9fcb4c8fda1cf03ada48966c427f40bfc0\": invalid reference format" 
go.version=go1.6.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v1+prettyjws" http.request.host="registry.example.com:5001" 
http.request.id=ab781300-c194-4fed-aaa9-5db01ae1db6f http.request.method=PUT http.request.remoteaddr="127.0.0.1:57222" 
http.request.uri="/v2/thomasmckay/test-for-echo/manifests/v1" 
http.request.useragent="docker/1.10.3 go/go1.6.3 git-commit/cb079f6-unsupported kernel/3.10.0-229.4.2.el7.x86_64 os/linux arch/amd64" i
nstance.id=9eccbea1-88e0-4d57-abcf-91d5fea669c4 vars.name="thomasmckay/test-for-echo" vars.reference=v1
```

**Comment by mfojtik** [comment]
@aweiteka are you working on the fix?

**Comment by Conan-Kudo** [comment]
Adding this variable manually in `/etc/sysconfig/atomic-registry` fixed the problem for me.

**Comment by yangjunsss** [comment]
Fix mine by adding ```DOCKER_REGISTRY_SERVICE_HOST=${installhost}"`` into ```/host/etc/sysconfig/atomic-registry``` and then ```sudo systemctl restart atomic-registry```

**Comment by aweiteka** [comment]
Atomic registry deployment is being deprecated in favor of better tested and maintained installation methods.

- [oc cluster up](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md) for non-production "try it out" or test deployments
- [openshift-ansible](http://www.projectatomic.io/blog/2017/05/oo-standalone-registry/) for more production use cases.

This reported issue will not be addressed.
