### ISSUE TITLE
FAILURE after 0.334s: test/end-to-end/core.sh:423: executing 'oc logs dc/frontend' expecting success and text 'Connecting to production database': the output content test failed

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#11682]
```
FAILURE after 0.334s: test/end-to-end/core.sh:423: executing 'oc logs dc/frontend' expecting success and text 'Connecting to production database': the output content test failed
Standard output from the command:
--> pre: Running hook pod ...
--> pre: Success
--> Scaling frontend-1 to 2
--> Waiting up to 2m0s for pods in deployment frontend-1 to become ready
--> post: Running hook pod ...
--> post: Success
--> Success
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/7975/consoleFull#-14238278135762928fe4b031e1b25ced2a

**Comment by soltysh** [comment]
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/8061/consoleFull

**Comment by kargakis** [comment]
@bparees flakes should be marked as P1 until triaged by their owners

https://github.com/openshift/origin/issues/11661#issuecomment-257309445

**Comment by bparees** [comment]
@kargakis and with 4 people hitting it in the last 18 hours, what's the justification for triaging it as a p2?

**Comment by bparees** [comment]
(I raised it because at the time it had been hit a bunch of times, and that was *before* the 4 new ones)

**Comment by kargakis** [comment]
> @kargakis and with 4 people hitting it in the last 18 hours, what's the justification for triaging it as a p2?

You can blame @mfojtik @liggitt for not merging https://github.com/openshift/origin/pull/11725 :)

**Comment by mfojtik** [comment]
@kargakis one fix at the time... :-)
