### ISSUE TITLE
Deployment config conditions follow-up work

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#11686]
Currently the dc controller sets conditions based on the state of the rc that is set by the deployment controller. The following scenario can lead into missing progress report:
-- Deployer pod is created by the deployment controller, rc is set to Pending
-- Deployer pod runs and scales up the rc to 1
-- Deployment config controller sees the update to the rc but it is still tagged as Pending so it will continue showing the "Wating on deployer pod ..." message.
-- Deployment controller updates rc to Running
-- Deployment config controller sees the update but it doesn't see that it is progressing (it is already scaled to one, blocked on the pod becoming ready), the message in the status continues to be "Wating on deployer pod ..."

Happened in https://github.com/openshift/origin/issues/11685

The first implementation of conditions is conservative in that we set conditions based on the state of the RC that is set by the deployment controller. Progress should trump the state of the RC.

@mfojtik @smarterclayton

**Comment by kargakis** [comment]
@mfojtik since you are touching conditions

**Comment by mfojtik** [comment]
@kargakis so you want it to transition to Running when the deployer pod scales the RC to >0 ? or when the deployer pod is created?

**Comment by kargakis** [comment]
I just had another look at the code and I think we should set the condition to Progressing regardless of `deployutil.IsProgressing(config, *newStatus)` returns the first time.
