### ISSUE TITLE
Global "--context" argument causes "oc whoami" to fail

### ISSUE THREAD

**Issue by hansmi** [openshift/origin#11688]
The `whoami` command has a `--context` option which conflicts with the global `--context` option:

```
$ oc options 2>&1 | grep -w -- --context
      --context='': The name of the kubeconfig context to use

$ oc whoami --help 2>&1 | grep -w -- --context
  -c, --context=false: Print the current user context name
```

##### Version
```
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. Set up at least one context, preferrably more
2. Get context name

    ```
    $ oc config view -o json | jq -r '.contexts | .[] | .name'
    appuio
    customer-foo
    ```

2. Use context with a command like `get` (works):

    ```
    $ oc --context=appuio get pod
    NAME                       READY     STATUS    RESTARTS   AGE
    …
    ```

3. Use context with `whoami` (fails):

    ```
    $ oc --context=appuio whoami
    Error: invalid argument "appuio" for --context=appuio: strconv.ParseBool: parsing "appuio": invalid syntax
    ```

##### Current Result
Command fails:
```
$ oc --context=appuio whoami
Error: invalid argument "appuio" for --context=appuio: strconv.ParseBool: parsing "appuio": invalid syntax
```

##### Expected Result
Command does not fail and uses the selected context. `whoami`'s own `--context` parameter should still be usable, too.

**Comment by hansmi** [comment]
A colleague has pointed out to me that `whoami --context` is meant to print the context of the currently active cluster/user combination. As such my reading of the description of the option was wrong. I assume everything works as expected in this regard.

**Comment by liggitt** [comment]
In any case, deprecated in favor of --show-context in 1.4, will remove the special meaning of --context for whoami in 1.5 so it is consistent with all other commands
