### ISSUE TITLE
Unable to push docker image to Openshift Origin Docker registry - no basic auth credentials

### ISSUE THREAD

**Issue by abrahamjaison01** [openshift/origin#11683]
I was trying to deploy a docker image I have created via Openshift. I followed the instructions in: [](http://www.opensourcerers.org/importing-an-external-docker-image-into-red-hat-openshift-v3/)

However, as I tried to push my docker image to the Openshift registry, it did not succeed, as shown.

##### Version

> [root@mymachine ~]# oc version
> 
> oc v1.2.0
> 
> kubernetes v1.2.0-36-g4a3f9c5
> 
> [root@mymachine ~]# docker --version
> 
> Docker version 1.11.0, build 4dc5990

##### Steps To Reproduce

1. Build a custom docker image in the local docker repository using `docker build`
2. Tag that docker image to push it to the openshift docker registry as <docker registry ip>:<port>/<project_name>/<image_name> E.g. 172.30.155.111:5000/default/myimage
3. Push the docker image to the repository. `docker push 172.30.155.111:5000/default/myimage`. 

##### Current Result

> [root@mymachine ~]# docker push 172.30.155.111:5000/default/mycostumedaemon
> 
> The push refers to a repository [172.30.155.111:5000/default/mycostumedaemon]
> 
> 0a4a35d557a6: Preparing
> 
> 025eba1692ec: Preparing
> 
> 5332a889b228: Preparing
> 
> e7b287e8074b: Waiting
> 
> 149636c85012: Waiting
> 
> f96222d75c55: Waiting
> 
> no basic auth credentials

##### Expected Result
The expected result is that the image should have been pushed to the repository successfully. 

##### Additional Information
When running the command below, some errors are obtained. The errors are listed below.
> [root@mymachine ~]# openshift ex diagnostics
> 
> ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:155]
>        See the errors below in the output from the diagnostic pod:
>        [Note] Running diagnostic: PodCheckAuth
>               Description: Check that service account credentials authenticate as expected
> 
>        WARN:  [DP1005 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:85]
>               A request to the master timed out.
>               This could be temporary but could also indicate network or DNS problems.
> 
>        ERROR: [DP1016 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:113]
>               DNS resolution for registry address docker-registry.default.svc.cluster.local returned an error; container DNS is likely incorrect. The error was: read udp 172.17.0.5:57168->192.168.XX.XXX:53: read: no route to host
> 
>        [Note] Running diagnostic: PodCheckDns
>               Description: Check that DNS within a pod works as expected
> 
>        ERROR: [DP2003 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:72]
>               The first /etc/resolv.conf nameserver 192.168.XX.XXX
>               could not resolve kubernetes.default.svc.cluster.local.
>               Error: read udp 172.17.0.5:35781->192.168.XX.XXX:53: read: no route to host
>               This nameserver points to the master's SkyDNS which is critical for
>               resolving cluster names, e.g. for Services.
> 
>        WARN:  [DP2015 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:124]
>               Error querying nameserver 192.168.XX.XXX:
>                 read udp 172.17.0.5:45998->192.168.XX.XXX:53: read: no route to host
>               This may indicate a problem with DNS.
> 
>        WARN:  [DP2014 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:119]
>               A request to the nameserver 192.168.XX.XXX timed out.
>               This could be temporary but could also indicate network or DNS problems.
> 
>        [Note] Summary of diagnostics execution (version v1.2.0):
>        [Note] Warnings seen: 3
>        [Note] Errors seen: 2
> 

PS: I am not sure whether there is already an issue raised on this, but I couldn't find any useful topics/discussions on this.!

**Comment by miminar** [comment]
Have you logged in to the registry before pushing as [described here](https://docs.openshift.org/latest/install_config/registry/accessing_registry.html#access-logging-in-to-the-registry)?

**Comment by abrahamjaison01** [comment]
Well.. that seems to be a random error.. I restarted the services, created a new project and a docker registry etc., and started everything over again and it now works fine.. Not sure if it is a bug though..!
Also I couldn't find any commands such as ./openshift restart or ./openshift stop.. Only ./openshift start is available..! Thanks..
