### ISSUE TITLE
remove unneeded vendored test files.

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#11695]
do we run any of tests that are in the vendor folder?
i know we run some/all kube tests ourselves, but i don't know anything about this.
i was wondering if we can remove them or if we should keep them?
```
ipalade@dhcp129-131:~/origin$ find vendor/ -name "*_test.go"  | grep -v k8s
vendor//github.com/containernetworking/cni/pkg/invoke/find_test.go
vendor//github.com/containernetworking/cni/pkg/invoke/invoke_suite_test.go
vendor//github.com/containernetworking/cni/pkg/ns/ns_suite_test.go
vendor//github.com/containernetworking/cni/pkg/ns/ns_test.go
vendor//github.com/containernetworking/cni/pkg/skel/skel_suite_test.go
vendor//github.com/containernetworking/cni/pkg/skel/skel_test.go
vendor//github.com/containernetworking/cni/pkg/types/args_test.go
vendor//github.com/containernetworking/cni/pkg/types/types_suite_test.go
vendor//github.com/containernetworking/cni/pkg/utils/utils_suite_test.go
vendor//github.com/containernetworking/cni/pkg/utils/utils_test.go
vendor//github.com/containernetworking/cni/plugins/ipam/host-local/allocator_test.go
vendor//github.com/containernetworking/cni/plugins/ipam/host-local/host_local_suite_test.go
vendor//github.com/containernetworking/cni/plugins/main/loopback/loopback_suite_test.go
vendor//github.com/containernetworking/cni/plugins/main/loopback/loopback_test.go
vendor//github.com/coreos/go-iptables/iptables/iptables_test.go
vendor//github.com/docker/distribution/registry/storage/linkedblobstore_test.go
vendor//github.com/mitchellh/go-wordwrap/wordwrap_test.go
vendor//github.com/openshift/imagebuilder/builder_test.go
```
@bparees @smarterclayton

**Comment by smarterclayton** [comment]
We definitely run all the Kube tests, but not other vendors.  All the
examples you described above look like incorrect vending.

**Comment by bparees** [comment]
platform team seems like the team that is closest to owning the godep folder, assigning to @mfojtik

**Comment by mfojtik** [comment]
I would prefer to do some house-keeping after 1.4 to get rid of these. I'm not too much concerned about them now as they are not compiled when building origin, but I'm concerned about the amount of work this will need to make the commits right ;-)

**Comment by PI-Victor** [comment]
@mfojtik  there's a PR https://github.com/openshift/origin/pull/11696 not yet merged, since i didn't realize i had to name it right, we can merge it after 1.4 drops.

**Comment by mfojtik** [comment]
bump(*) ? nice try :-)

**Comment by mfojtik** [comment]
Assigning this back to @PI-Victor as he have PR out already.
