### ISSUE TITLE
Oauth redirects to internal address

### ISSUE THREAD

**Issue by oatmealraisin** [openshift/origin#11692]
When signing into the Jenkins Ephemeral template using oauth, I'm being redirected to
`https://openshift.default.svc/oauth/authorize?client_id=system:serviceaccount:myproject:jenkins&redirect_uri=https://jenkins-myproject.10.192.219.70.xip.io/securityRealm/finishLogin&response_type=code&scope=user:info%20user:check-access&state=OGNlOGU3OGUtNTQ5OS00`
which fails to resolve.

##### Version
```bash
 $ oc version
oc v1.4.0-alpha.0+8b2d509-925
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://10.192.219.70:8443
openshift v1.4.0-alpha.0
kubernetes v1.4.0-beta.3+d19513f
```

##### Steps To Reproduce
```bash
oc cluster up
oc new-app https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/jenkins-ephemeral-template.json
oc new-app https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/application-template.json
```

##### Current Result
```
https://openshift.default.svc/oauth/authorize?client_id=system:serviceaccount:myproject:jenkins&redirect_uri=https://jenkinsmyproject.10.192.219.70.xip.io/securityRealm/finishLogin&response_type=code&scope=user:info%20user:check-access&state=OGNlOGU3OGUtNTQ5OS00
Server not found

Firefox can’t find the server at openshift.default.svc.
```

##### Expected Result

Navigation to oauth login page or jenkins page

##### Additional Information
[oc get all](https://paste.fedoraproject.org/467305/78009253)

**Comment by oatmealraisin** [comment]
@gabemontero Any ideas?

**Comment by gabemontero** [comment]
get the output for  `oc get sa jenkins -o yaml` and run `docker logs <jenkins container id>`

**Comment by gabemontero** [comment]
and how recent is the openshift version you posted?

**Comment by liggitt** [comment]
@gabemontero do you default to openshift.default.svc if you can't find the discovery info? That's unlikely to be a good default

**Comment by gabemontero** [comment]
@liggit we should only be using openshift.default.svc when the jenkins pod accesses the master; it is not intended to show up in a browser URL

**Comment by liggitt** [comment]
@oatmealraisin what do you see if you request `https://<master>:8443/.well-known/oauth-authorization-server`?

**Comment by oatmealraisin** [comment]
@gabemontero
[oc get sa jenkins -o yaml](https://paste.fedoraproject.org/467324/80104131)
[docker logs](http://paste.fedoraproject.org/467329/47801055/)
[docker logs &> logs](http://paste.fedoraproject.org/467332/78010604/)

@liggitt 
```bash
 $ curl https://10.192.219.70:8443/.well-known/oauth-authorization-server -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot \"get\" on \"/.well-known/oauth-authorization-server\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```
The openshift version is from last night at around 5pm

**Comment by oatmealraisin** [comment]
this is @gabemontero with Ryan ..... when looking at the jenkins log with trace on, we see that the jenkins oauth plugin is getting a similar exception trying to access .well-known/oauth-authorization-server:

```
com.google.api.client.http.HttpResponseException: 403 Forbidden
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:serviceaccount:myproject:jenkins\" cannot \"get\" on \"/.well-known/oauth-authorization-server\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

So a couple of notes:
- I need to fix the plugin to not default the login provider to oauth if we get this error 
- but short term, we need to see if this is a general issue or something specific to Ryan's env

**Comment by liggitt** [comment]
is this an old cluster restarting against old etcd data? if so, run `oadm policy reconcile-cluster-roles --confirm`

**Comment by oatmealraisin** [comment]
Ryan says he uninstalled the reinstalled everything..... should be a fresh cluster.  Trying out reconcile anyway.

**Comment by oatmealraisin** [comment]
@liggitt @gabemontero Ryan in control again, after remaking the openshift image and using @csrwng 's localup, everything is in order. Is there any possibility that a user could encounter this

**Comment by gabemontero** [comment]
IMO it is highly unlikely unless the user is developing origin and gets his install in an indeterminate state like yours appeared to be.

**Comment by gabemontero** [comment]
I am still updating the jenkins oauth plugin to no default to oauth when we get permissions error like you got.  But that is not a code change in the origin repo.

**Comment by oatmealraisin** [comment]
Closing :) thanks @gabemontero !

**Comment by eramlawi** [comment]
having this issue after trying to do this 
https://computingforgeeks.com/setup-openshift-origin-local-cluster-on-centos/

on fresh  CentOS Linux release 7.6.1810 (Core) 
up to date

**Comment by eramlawi** [comment]
okay never run oc cluster up , if you do so it will create alot of entries with 127.0.0.1 you need to always use your public IP
