### ISSUE TITLE
UI: don't respawn many websockets on failure indefinitely

### ISSUE THREAD

**Issue by larstobi** [openshift/origin#1171]
When running an OpenShift v0.3.2 master with Safari v8.0.3 (10600.3.18), an untrusted certificate may cause Safari to run an infinite loop trying to connect to a WebSocket with TLS on the master with 100 tries per second.

It will log on the master: https://gist.github.com/larstobi/7fe6af82f0a2521658b0
which is from this line of code:  https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/master.go#L366

In the Safari Error Console, I see lots of these messages: https://gist.github.com/larstobi/3e156a29b52c51c86dea

To make the behaviour disappear with Safari, I first quit Safari, then start Safari, go to https://oo1.local:8444 (my OpenShift master) and when I get the untrusted certificate warning, I select "Always Trust" on the certificate, type in my OS X password, and now it works perfectly again.

Suggestion to back off on the connection retries.

Should there also be a notofication to the user in the UI that there is a problem with the TLS WebSockets connection?

Thanks to @liggitt and @jwforres for helping me on IRC #openshift-dev with this issue.

**Comment by jwforres** [comment]
Fixed in #1325
