### ISSUE TITLE
Running a docker image in openshift origin without building it via web console

### ISSUE THREAD

**Issue by abrahamjaison01** [openshift/origin#11721]
I have a docker image developed and pushed onto the docker registry in openshift. Now I need to run the docker image as it is by passing some ENV variables. As shown below my docker image "mycustomdaemon:latest" was listed when I clicked "Add to project" link. However when I try to run it, it asks for the Git Repository URL and requires to build again. I just want to run the docker image as such and doesn't need to rebuild or perform any such operations on it. How should I go about it

##### Version

> [root@mymachine ~]# openshift version
> openshift v1.2.0
> kubernetes v1.2.0-36-g4a3f9c5
> etcd 2.2.5

> [root@mymachine ~]# docker --version
> Docker version 1.11.0, build 4dc5990

##### Steps To Reproduce
1. Create a docker image and test it locally
2. Push it to the openshift docker registry after tagging the docker image as <docker-registry-IP>:<port>/<project-name>/<image-stream-name>. Then issue the command: docker push <dockerimagename> after logging in to the docker and openshift registry.
3. Go to the web console and select the project. Click on "Add to Project" link and browse for the image you pushed and click on it. 

##### Current Result
Docker image is pushed and is available in the repository as shown below..

![capture1](https://cloud.githubusercontent.com/assets/14936005/19916704/d2699b58-a0e2-11e6-85c8-ad81d65ef375.JPG)

However when I click on it, it asks for Git repository URL and performs building operations. 

![capture2](https://cloud.githubusercontent.com/assets/14936005/19916706/d66404fa-a0e2-11e6-99eb-53f47f272b80.JPG)

##### Expected Result

I just need to run the docker image as such and do not want to perform operations such as building it again or anything of that sort.

**Comment by abrahamjaison01** [comment]
I tried to run the image directly from the CLI by issuing the `oc new-app` command but got the following error output. 

> error: can't look up Docker image "172.30.155.111:5000/default/mycustomdaemon:latest": Internal error occurred: Get https://172.30.155.111:5000/v2/: http: server gave HTTP response to HTTPS client
> error: no match for "172.30.155.111:5000/default/mycustomdaemon:latest"

![capture3](https://cloud.githubusercontent.com/assets/14936005/19917243/6b47b7a2-a0e7-11e6-94d8-6ab76b79db79.JPG)

**Comment by mfojtik** [comment]
@abrahamjaison01 you seems to have two extra spaces in that command.

**Comment by mfojtik** [comment]
adding @jwforres to guide what label needs to be added to be able to run the image directly (I guess you have to use the different tab in the console to do so.)

**Comment by jwforres** [comment]
You need to use a newer version of openshift.  We added a "Deploy Image" feature in 1.3, see https://blog.openshift.com/whats-new-openshift-3-3-web-console/

**Comment by bparees** [comment]
@jwforres candidate for closing?
