### ISSUE TITLE
PR test flake: Base repository commit ID ### doesn't match evaluated commit ID ####

### ISSUE THREAD

**Issue by jupierce** [openshift/origin#11735]
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/717/console

```
*****Locally Merging Pull Request: https://github.com/openshift/origin/pull/11711
+ test_pull_requests --local_merge_pull_request 11711 --repo origin --config /var/lib/jenkins/.test_pull_requests_origin.json
  Checking if current base repo commit ID matches what we expect
  Deleting comment #257685908
Base repository commit ID 68604665ba89da34d6e990b174b45b832988f0eb doesn't match evaluated commit ID 16306a6a0698dfbd2922635e1afc0e8a0fcee535
Build step 'Execute shell' marked build as failure
```

**Comment by dobbymoodge** [comment]
Yeah, that shouldn't be happening...

**Comment by dobbymoodge** [comment]
Actually nevermind, I think that's the right behavior - did it kick off a new test automatically or did you have to update the [test] comment?

**Comment by jupierce** [comment]
Responded out of band in IRC. For posterity: no -- the test did not automatically restart. They had an opportunity to do so overnight, but I manually ran [test] the next day.

**Comment by dobbymoodge** [comment]
FWIW I haven't been able to reproduce this; my attempts lead to the test being re-kicked the next time the merge queue is processed.

If anyone spots this flake, please let me know right away so I can review the process_pull_requests logs before they're rotated out.

**Comment by dobbymoodge** [comment]
No longer applicable, test_pull_requests doesn't build origin any longer.
