### ISSUE TITLE
HostSubnet handling is subject to multi-master race conditions

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#11740]
@liggitt points out that the timeline in https://github.com/openshift/origin/pull/11628#discussion_r86171874 is not actually guaranteed safe, because it's possible that the HostSubnets().Get() call at t=4 will hit an etcd that hasn't yet observed the deletion that occurred at t=3, which will then cause us to do the wrong thing. The fix for this is to keep a cache and act based on whether the HostSubnet is still in the cache, rather than whether it's known to the API server.

We may also be making this same mistake in other places.

In fact, EventQueue keeps a cache internally already, we just need to tweak RunEventQueue() to expose it, and then make use of it. (See also node.go:watchServices(), where we are manually keeping a cache that is redundant with the EventQueue's.)

**Comment by dcbw** [comment]
@danwinship instead of the internal cache, use NewEventQueueForStore()

**Comment by danwinship** [comment]
to clarify, this only causes problems if you delete a node and then immediately recreate it again faster than the etcds can sync up (which is not something you'd really have any reason to do), and afaik the bug has been around since 1.0

**Comment by knobunc** [comment]
Tracking this with https://trello.com/c/B56OdzdS

Since it is has been that way since 1.0 and is too risky to fix at the moment, dropping the priority.

**Comment by danwinship** [comment]
oh, hello random old bug that probably explains the weird HostSubnet behavior we were seeing on Online (#18617).

cc @pravisankar because I think you were digging into this?

/lifecycle frozen

**Comment by danwinship** [comment]
No idea if this is still an issue, but migrated to https://github.com/openshift/sdn/issues/25
