### ISSUE TITLE
port-forward throwing error (socat[25241] E connect(3, AF=2 127.0.0.1:5858, 16): Connection refused)

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#11745]
[provide a description of the issue]

##### Version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://10.0.0.249:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
```sh
oc new-app https://github.com/debianmaster/nodejs-welcome --name=welcome
sudo oc port-forward welcome-3-tcyai 5858
```
Remote debug from IDE  on  5858

##### Current Result
```sh
$ sudo oc port-forward welcome-3-tcyai 5858
Password:
Forwarding from 127.0.0.1:5858 -> 5858
Forwarding from [::1]:5858 -> 5858
Handling connection for 5858
E1102 21:36:45.364610   97738 portforward.go:327] an error occurred forwarding 5858 -> 5858: error forwarding port 5858 to pod welcome-3-tcyai_myproject, uid : exit status 1: 2016/11/03 02:42:20 socat[25241] E connect(3, AF=2 127.0.0.1:5858, 16): Connection refused
```

##### Expected Result
I should be able to debug from visual studio

**Comment by debianmaster** [comment]
I'm trying to debug a nodejs application by forwarding the traffic from pod to localhost in this scenario

**Comment by danwinship** [comment]
worksforme... can you run the node with --loglevel=5 and attach the logs (from when you first call "oc port-forward" until you make the failed connection attempt)

**Comment by debianmaster** [comment]
sorry silly mistake     my package json had 
`node server.js --debug=5858`
instead of 
`node --debug=5858  server.js `

i will try to compensate your time  for sure :)

closing this.
