### ISSUE TITLE
flake: Services should serve a basic endpoint from pods

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#11747]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8227/consoleFull

    • Failure [137.094 seconds]
    [k8s.io] Services
    /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:793
      should serve a basic endpoint from pods [Conformance] [It]
      /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/service.go:145
    
      Nov  2 18:52:46.072: Timed out waiting for service endpoint-test2 in namespace e2e-tests-services-1tjbg to expose endpoints map[pod1:[80]] (1m0s elapsed)

also seen in #11639, #11676

**Comment by pweil-** [comment]
bumped to p1 since all test flakes are now being started as a p1 for triage.

**Comment by danwinship** [comment]
I'm not able to reproduce this locally...

FTR note that this is not an SDN error: it happens in the conformance test, using built-in kube networking.
