### ISSUE TITLE
1.5 k8s rebase prereqs

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#11748]
To simplify the next rebase here's a list of items that should be fixed first:

- [ ] - align storage layer  (https://github.com/openshift/origin/issues/10910)
- [ ] - removing all references to `kube/pkg/client/unversioned` client code

**Comment by soltysh** [comment]
@deads2k @liggitt @smarterclayton anything else?

**Comment by soltysh** [comment]
@mfojtik fyi

**Comment by soltysh** [comment]
Removing client/unversioned is in https://github.com/openshift/origin/pull/11916

**Comment by kargakis** [comment]
@soltysh can we close this issue now?

**Comment by soltysh** [comment]
Yeah, I think we can. The storage alignment is tracked in its own issue pinned to 1.6. And k8s `pkg/client` was fixed in the other PR. No need to have multiples issues tracking the same thing.
