### ISSUE TITLE
extended test flake: jenkins-plugin test imagestream SCM DSL failed

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#11755]
Extended test failure:
```
• Failure [734.770 seconds]
[image_ecosystem][jenkins][Slow] openshift pipeline plugin
/data/src/github.com/openshift/origin/test/extended/image_ecosystem/plugin.go:851
  jenkins-plugin test context  
  /data/src/github.com/openshift/origin/test/extended/image_ecosystem/plugin.go:850
    jenkins-plugin test imagestream SCM DSL [It]
    /data/src/github.com/openshift/origin/test/extended/image_ecosystem/plugin.go:819

    Expected error:
        <*errors.errorString | 0xc8210be060>: {
            s: "timed out while waiting of an image stream tag extended-test-jenkins-plugin-q24aa-aveqi/localjenkins:develop",
        }
        timed out while waiting of an image stream tag extended-test-jenkins-plugin-q24aa-aveqi/localjenkins:develop
    not to have occurred
```

**Comment by csrwng** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/730

**Comment by csrwng** [comment]
@jupierce @bparees Looks like the jenkins pod was killed with an OOM event
 
From the origin.log:
```
I1102 16:10:42.318989   21350 handler.go:325] Added event &{/system.slice/docker-57e1c8f06f54195a12992ccf2ba1ec27a3191279636781627292f75edae95749.scope 2016-11-02 16:10:42 -0400 EDT oom {<nil>}}
I1102 16:10:42.319092   21350 manager.go:1102] Created an OOM event in container "/system.slice/docker-57e1c8f06f54195a12992ccf2ba1ec27a3191279636781627292f75edae95749.scope" at 2016-11-02 16:10:42 -0400 EDT
I1102 16:10:42.319105   21350 handler.go:325] Added event &{/system.slice/docker-57e1c8f06f54195a12992ccf2ba1ec27a3191279636781627292f75edae95749.scope 2016-11-02 16:10:42 -0400 EDT oomKill {0xc8332684e0}}
```

In the log of the pod itself, there's nothing indicating that it's out of memory:
https://gist.github.com/csrwng/98fea66d293e4ef7bcc75c778d8bae96

Is this an issue with how much memory we're assigning the pod?

**Comment by bparees** [comment]
@csrwng is this jenkins coming from our standard template?  if so it's right on the edge of manageable, as @jupierce found during his investigation, but with the heap now set to 60% of the container memory, i would expect to see java OOMs, not actual native OOM kills.

**Comment by csrwng** [comment]
It's jenkins from the modified template in the extended testdata files. But I don't think it's that diffent from the standard one. @derekwaynecarr do you know what kind of oom would generate the above messages?

**Comment by gabemontero** [comment]
with @jupierce 's latest change the tests should no longer need the modified template; it instantiates the examples/jenkins/jenkins-ephemeral-template.json file now

**Comment by csrwng** [comment]
Ahh ok, then that's what we're using :-)

**Comment by jupierce** [comment]
I'm going to venture that we are still playing with fire with 512G Jenkins profiles -- even with the heap change. Unless cgroups have been extensively tested with embedded systems (embedded Java systems, at that), the amount of free memory we are dealing with is a rounding error in most environments.
Options that come to mind:
1. We can get approval to run 1GB Jenkins profiles everywhere.
2. We can run extended tests at 1GB to avoid this and hope for the best in OSO.
3. We can try to tune the 512G profile for the memory pressure (e.g. vm.vfs_cache_pressure=200 or setting cgroup memory.memsw.usage_in_bytes; fwiw, both of these would require root privilege in the container or support from the platform).
4. We can work on understanding root cause at the OOM Killer level. I suspect I can create a test that will kill Jenkins pods consistently so that the problem can be reproduced, but we will go down a deep rabbit (kernel) hole before we find it.

**Comment by bparees** [comment]
with a 60% heap setting that means we've got 200megs for native memory (which should be the only thing we'd be using that could cause an OOM kill).  i'm a little surprised we'd be chewing up that much native memory but it seems like it would be worth trying to gather some metrics from the pod...  maybe we can run jenkins w/ a background process the records native memory usage to stdout so we can see the conditions when it gets oom killed?

**Comment by gabemontero** [comment]
On Thursday, November 3, 2016, Ben Parees <notifications@github.com> wrote:

> with a 60% heap setting that means we've got 200megs for native memory
> (which should be the only thing we'd be using that could cause an OOM
> kill). i'm a little surprised we'd be chewing up that much native memory
> but it seems like it would be worth trying to gather some metrics from the
> pod... maybe we can run jenkins w/ a background process the records native
> memory usage to stdout so we can see the conditions when it gets oom killed?
>
+1 I advocated this last go around as well

**Comment by jupierce** [comment]
I'm definitely +1 for more evaluation because I don't like to speculate. Just cautioning that I don't believe this will yield to simple monitoring (i.e. there is something else happening here with Linux buffers/caches that we have limited tools in this environment to effectively isolate).

**Comment by gabemontero** [comment]
On Fri, Nov 4, 2016 at 9:01 AM, Justin Pierce <notifications@github.com>
wrote:

> I'm definitely +1 for more evaluation because I don't like to speculate.
> Just cautioning that I don't believe this will yield to simple monitoring
> (i.e. there is something else happening here with Linux buffers/caches that
> we have limited tools in this environment to effectively isolate).
>
Good point.  Minimally having the simpler form of monitoring baked into our
extended test here though would at least (help) confirm that a more
esoteric situation like you describe is occurring.  Once we have that
proof, we could work with the appropriate folks to put together the
additional diagnostics needed.

**Comment by csrwng** [comment]
We likely have that data from cadvisor already ... we should be able to just dump it when an error occurs

**Comment by jupierce** [comment]
@csrwng Sounds promising, but #4143 makes it sound like it might take some work to extract.

**Comment by csrwng** [comment]
@jupierce my understanding is we could get the data by hitting an endpoint on the etcd server ... will play with it today

**Comment by csrwng** [comment]
actually, not the etcd server ... the kubelet. This gets me a dump of metrics data on my server:
```
curl --cacert ./ca.crt --cert ./master.kubelet-client.crt --key ./master.kubelet-client.key https://127.0.0.1:10250/metrics
```

**Comment by jupierce** [comment]
That is an impressive amount of information, but it seems like we are still missing some key values (e.g. RSS of Java process). Perhaps we could doing something like PR #11795 ?

**Comment by gabemontero** [comment]
Is this still occurring since the changes in Java tuning for Jenkins were introduced by @jupierce ?

**Comment by bparees** [comment]
no, haven't seen it in any of the nightly runs.
