### ISSUE TITLE
oc new-project --as adds information to .kube/config which makes oc extremely slow

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#11758]
when using "oc new-project --as" you end up creating entries in .kube/config for each --as user.

When creating 3 projects, it's not noticed. But when creating 100 user projects this way, by the 70th or 80th user things get really, really slow.

If you run "oc" with --loglevel=8 during this process you notice that all of the entries in .kube/config are being evaluated, which starts to slow down the processing of whatever command was requested.

##### Version
oc v3.3.1.3
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.boston2.openshift3roadshow.com
openshift v3.3.1.3
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. have a system with a large number of users (eg: 100)
2. for num in $(seq -f %02d 0 100); do oc new-project foo-$num --as=user$num; done

##### Current Result
By around 70 or so users things start to slow down.

##### Expected Result
No slowdown.

##### Additional Information
I'm not sure why we would add entries to the kubeconfig file just because we're creating a project as a different user.

**Comment by liggitt** [comment]
creating a project switches your current context to that project

`--as` is not specific to the new-project command, it's a global option that makes the API requests use impersonation.

if you are batch creating projects, you should probably use `--skip-config-write`

**Comment by thoraxe** [comment]
OOOH thanks!
