### ISSUE TITLE
`openshift ex registry` and similar should enable easy updating

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1175]
Should someone make a mistake, like say not adding the right --images when creating the infrastructure component, it should be easy and obvious how to back that out.

Right now, for the registry, it means deleting the DC, the service, and the pod, and then _restarting the master_ to clear the service cache if you tried to use it at any point before realizing your mistake. This is far from obvious to the uninitiated. It should at least be possible to display what was created so the user can figure it out for themself. Better if there is a --delete or --recreate option (which also handles the service cache).

Of course, if it were possible to recreate without deleting the service, it wouldn't be necessary to clear that cache.

**Comment by derekwaynecarr** [comment]
+1 - I ran into this many times over the past week.

**Comment by sosiouxme** [comment]
Forgot to mention, ImageRepositories get the docker-registry service inserted as the default as well. So definitely best to re-create while keeping the same service.

**Comment by smarterclayton** [comment]
It should be trivially easy to edit a dc from the cli.  That's the real problem here.  We should show more info about what you are creating (types as part of the output) and allow the normal "it exists" to tell you how to change them.  Once config reconciliation is possible, we should allow that to be applied.

**Comment by sosiouxme** [comment]
Good point; regardless of what mechanism gets us to the desired state,  updating is what we really want.

**Comment by smarterclayton** [comment]
As a side node I think we should invert --create and make it the default, with --dry-run or --check being the optional behavior.

**Comment by ncdc** [comment]
At worst, this can be a docs-only fix, where we describe what `osadm registry` creates and how to edit it. Better would maybe be an `--edit` flag to `osadm registry` or something along those lines. @smarterclayton @danmcp any preference?

**Comment by smarterclayton** [comment]
Post 3.0

**Comment by kargakis** [comment]
@smarterclayton this feels like it should be handled by the set commands

**Comment by smarterclayton** [comment]
Yes, set commands would handle individual fields, patch and apply need
to be improved (actually, can you look at why apply is broken on the
output of oadm registry -o yaml?)Z

**Comment by kargakis** [comment]
> actually, can you look at why apply is broken on the output of oadm registry -o yaml?

We need to cherry-pick https://github.com/kubernetes/kubernetes/pull/20948. I just tested it in Kube (working), cherry-picked and tested in Origin (working), and will submit a PR shortly.

**Comment by kargakis** [comment]
`patch` and `apply` work, and we have oc set {triggers,env,volume,probe} for updating a dc

So to summarize what's left here:
* oc set image 
* oc set hooks (https://trello.com/c/YfElgSo0/585-make-it-easier-to-create-deployment-hooks-evg)
* oc set limits (https://github.com/openshift/origin/issues/8329)
* anything else?

**Comment by smarterclayton** [comment]
oc rollout image is probably the alternate for oc set image.

I'm not aware of others.

**Comment by kargakis** [comment]
> oc set image

https://github.com/kubernetes/kubernetes/pull/25509

> oc set hooks (https://trello.com/c/YfElgSo0/585-make-it-easier-to-create-deployment-hooks-evg)

https://github.com/openshift/origin/pull/9187

> oc set limits (#8329)

https://github.com/kubernetes/kubernetes/pull/27206

**Comment by kargakis** [comment]
And we also have paused now, so we will be able to run updates more efficiently.
For example, for securing the docker registry, we currently run 4 deployments. We should run one instead:
```
oc rollout pause dc/registry
oc set volume dc/registry --add --type=secret --secret-name=registry-secret -m /etc/secrets
oc set env dc/registry \
    REGISTRY_HTTP_TLS_CERTIFICATE=/etc/secrets/registry.crt \
    REGISTRY_HTTP_TLS_KEY=/etc/secrets/registry.key
oc patch (probes)
oc rollout resume dc/registry
```
https://docs.openshift.org/latest/install_config/install/docker_registry.html#securing-the-registry

**Comment by kargakis** [comment]
@JacobTanenbaum all the required commands except `oc set resources` are in master. Handing this issue to you until the command you are working on (https://github.com/kubernetes/kubernetes/pull/27206) is picked up in Origin.

**Comment by pweil-** [comment]
`oc set resources` is in now, closing
