### ISSUE TITLE
Deploy metrics - "401 Unauthorized", response: "Unauthorized"

### ISSUE THREAD

**Issue by mvlach** [openshift/origin#11762]
Heapster cannot load statistics.

E1103 20:40:25.011250       1 kubelet.go:230] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "https://192.168.1.178:10250/stats/container/": request failed - "401 Unauthorized", response: "Unauthorized"

I tried to add the cluster-admin role, but without success.

##### Version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.1.177:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
I follow the documentation https://docs.openshift.org/latest/install_config/cluster_metrics.html#metrics-deployer-service-account
```
[root@master ~]# oadm  policy who-can cluster-reader stats
Namespace: openshift-infra
Verb:      cluster-reader
Resource:  stats

Users:  system:serviceaccount:openshift-infra:heapster

Groups: system:cluster-admins
        system:masters
```

```
RoleBinding[cluster-readers]:				 
							Role:			cluster-reader
							Users:			<none>
							Groups:			system:cluster-readers
							ServiceAccounts:	management-infra/management-admin, openshift-infra/heapster
							Subjects:		<none>
```

##### Current Result
Endpoint Check in effect. Checking https://hawkular-metrics:443/hawkular/metrics/status
The endpoint check has successfully completed.
Starting Heapster with the following arguments: --source=kubernetes:https://kubernetes.default.svc:443?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250 --sink=hawkular:https://hawkular-metrics:443?tenant=_system&labelToTenant=pod_namespace&labelNodeId=nodename&caCert=/hawkular-cert/hawkular-metrics-ca.certificate&user=hawkular&pass=AQroyJdqqekpAtf&filter=label(container_name:^system.slice.*|^user.slice) --tls_cert=/secrets/heapster.cert --tls_key=/secrets/heapster.key --tls_client_ca=/secrets/heapster.client-ca --allowed_users=system:master-proxy --metric_resolution=10s
I1103 20:18:41.251832       1 heapster.go:65] heapster --source=kubernetes:https://kubernetes.default.svc:443?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250 --sink=hawkular:https://hawkular-metrics:443?tenant=_system&labelToTenant=pod_namespace&labelNodeId=nodename&caCert=/hawkular-cert/hawkular-metrics-ca.certificate&user=hawkular&pass=AQroyJdqqekpAtf&filter=label(container_name:^system.slice.*|^user.slice) --tls_cert=/secrets/heapster.cert --tls_key=/secrets/heapster.key --tls_client_ca=/secrets/heapster.client-ca --allowed_users=system:master-proxy --metric_resolution=10s
I1103 20:18:41.251922       1 heapster.go:66] Heapster version 1.1.0
I1103 20:18:41.252311       1 configs.go:60] Using Kubernetes client with master "https://kubernetes.default.svc:443" and version "v1"
I1103 20:18:41.252327       1 configs.go:61] Using kubelet port 10250
I1103 20:18:41.317935       1 driver.go:322] Initialised Hawkular Sink with parameters {_system https://hawkular-metrics:443?tenant=_system&labelToTenant=pod_namespace&labelNodeId=nodename&caCert=/hawkular-cert/hawkular-metrics-ca.certificate&user=hawkular&pass=AQroyJdqqekpAtf&filter=label(container_name:^system.slice.*|^user.slice) 0xc820300000  5}
I1103 20:18:41.378355       1 heapster.go:92] Starting with Hawkular-Metrics Sink
I1103 20:18:41.378415       1 heapster.go:92] Starting with Metric Sink
I1103 20:18:41.462046       1 heapster.go:171] Starting heapster on port 8082
E1103 20:18:55.020502       1 kubelet.go:230] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "https://192.168.1.177:10250/stats/container/": request failed - "401 Unauthorized", response: "Unauthorized"
E1103 20:18:55.029225       1 kubelet.go:230] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "https://192.168.1.178:10250/stats/container/": request failed - "401 Unauthorized", response: "Unauthorized"

**Comment by liggitt** [comment]
the right `who-can` query is `oadm policy who-can get nodes/stats --all-namespaces`

can you double check which service account the heapster pod is running as?

**Comment by mvlach** [comment]
```[root@master ~]# oadm policy who-can get nodes/stats --all-namespaces
Namespace: <all>
Verb:      get
Resource:  nodes/stats

Users:  system:master
        system:serviceaccount:management-infra:management-admin
        system:serviceaccount:openshift-infra:heapster
        system:serviceaccount:openshift-infra:namespace-controller

Groups: system:cluster-admins
        system:cluster-readers
        system:masters
        system:node-admins```

**Comment by mvlach** [comment]
@liggitt  "can you double check which service account the heapster pod is running as?" - how to do it please :)

**Comment by liggitt** [comment]
`oc get pods -n openshift-infra`, find the heapster pod, then `oc get pod -n openshift-infra <heapster-pod-name> -o yaml` and see the service account name

**Comment by mvlach** [comment]
```
[root@master ~]# oc get pod/heapster-t94bd -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"openshift-infra","name":"heapster","uid":"05d30e96-a1fd-11e6-bb0c-66b2f2d6b340","apiVersion":"v1","resourceVersion":"1435902"}}
    openshift.io/scc: anyuid
  creationTimestamp: 2016-11-03T20:42:40Z
  generateName: heapster-
  labels:
    metrics-infra: heapster
    name: heapster
  name: heapster-t94bd
  namespace: openshift-infra
  resourceVersion: "1435918"
  selfLink: /api/v1/namespaces/openshift-infra/pods/heapster-t94bd
  uid: 105596f1-a206-11e6-a4bf-66b2f2d6b340
spec:
  containers:
  - command:
    - heapster-wrapper.sh
    - --wrapper.username_file=/hawkular-account/hawkular-metrics.username
    - --wrapper.password_file=/hawkular-account/hawkular-metrics.password
    - --wrapper.allowed_users_file=/secrets/heapster.allowed-users
    - --wrapper.endpoint_check=https://hawkular-metrics:443/hawkular/metrics/status
    - --source=kubernetes:https://kubernetes.default.svc:443?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250
    - --sink=hawkular:https://hawkular-metrics:443?tenant=_system&labelToTenant=pod_namespace&labelNodeId=nodename&caCert=/hawkular-cert/hawkular-metrics-ca.certificate&user=%username%&pass=%password%&filter=label(container_name:^system.slice.*|^user.slice)
    - --tls_cert=/secrets/heapster.cert
    - --tls_key=/secrets/heapster.key
    - --tls_client_ca=/secrets/heapster.client-ca
    - --allowed_users=%allowed_users%
    - --metric_resolution=10s
    image: openshift/origin-metrics-heapster:latest
    imagePullPolicy: IfNotPresent
    name: heapster
    ports:
    - containerPort: 8082
      name: http-endpoint
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /opt/heapster-readiness.sh
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SYS_CHROOT
      privileged: false
      seLinuxOptions:
        level: s0:c3,c2
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /secrets
      name: heapster-secrets
    - mountPath: /hawkular-cert
      name: hawkular-metrics-certificate
    - mountPath: /hawkular-account
      name: hawkular-metrics-account
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: heapster-token-4c7nt
      readOnly: true
  dnsPolicy: ClusterFirst
  host: 192.168.1.177
  imagePullSecrets:
  - name: heapster-dockercfg-ccscz
  nodeName: 192.168.1.177
  restartPolicy: Always
  securityContext:
    seLinuxOptions:
      level: s0:c3,c2
  serviceAccount: heapster
  serviceAccountName: heapster
  terminationGracePeriodSeconds: 30
  volumes:
  - name: heapster-secrets
    secret:
      secretName: heapster-secrets
  - name: hawkular-metrics-certificate
    secret:
      secretName: hawkular-metrics-certificate
  - name: hawkular-metrics-account
    secret:
      secretName: hawkular-metrics-account
  - name: heapster-token-4c7nt
    secret:
      secretName: heapster-token-4c7nt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2016-11-03T20:42:40Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2016-11-03T20:42:51Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2016-11-03T20:42:40Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b6154a440bd5e00bcdd7746a3a7dab1d613bca356ae7ca3683966aeda8264a74
    image: openshift/origin-metrics-heapster:latest
    imageID: docker://sha256:d560082d954e03060a3f55c22d21520e7442f46d142daec5dde21404f99dd790
    lastState: {}
    name: heapster
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2016-11-03T20:42:43Z
  hostIP: 192.168.1.177
  phase: Running
  podIP: 10.1.1.3
  startTime: 2016-11-03T20:42:40Z

```

**Comment by mvlach** [comment]
```
  serviceAccount: heapster
  serviceAccountName: heapster
```
It is correct ?

**Comment by mvlach** [comment]
Should it correlate ?

```
Nov  3 21:58:55 master origin-node: E1103 21:58:55.007351    3015 server.go:215] Unable to authenticate the request due to an error: User "system:node:192.168.1.177" cannot create authentication.k8s.io.tokenreviews at the cluster scope
```

**Comment by liggitt** [comment]
Yes. Did you just upgrade from an older version manually? If so, you need to reconcile cluster roles (`oadm policy reconcile-cluster-roles --confirm -o name`)

**Comment by mvlach** [comment]
Yes - I did.

This is only applicable on the master nodes, isn't ?

**Comment by mvlach** [comment]
It looks like it is working. Thanks very much
