### ISSUE TITLE
jenkins template message is wrong

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#11766]
Jenkins pipeline example description says:

```
     The Jenkins server is not currently automatically instantiated for you.  Please instantiate one of the Jenkins templates to create a Jenkins server for managing your pipeline build configurations.
```

but that is not the case in 1.4.0-alpha.1

**Comment by bparees** [comment]
@smarterclayton what are you running?  that's been updated already:
https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-persistent-template.json#L14
https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-ephemeral-template.json#L14

**Comment by smarterclayton** [comment]
Ah, it was the embedded template from oc 1.3.0
