### ISSUE TITLE
FAIL: TestTriggers_configChange

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#11772]
```
--- FAIL: TestTriggers_configChange (4.99s)
	deploy_trigger_test.go:666: Operation cannot be fulfilled on deploymentconfigs "config": the object has been modified; please apply your changes to the latest version and try again
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/8159/consoleFull#-94697474756bf4006e4b05b79524e5923

From the logs it seems that the test config was reconciled 20 times in one second which made the retry we already have for conflicts (max 5 retries) to blow up.

cc: @mfojtik @smarterclayton

**Comment by mfojtik** [comment]
@kargakis do we want to bump the number of retries?

**Comment by kargakis** [comment]
20 resyncs in a second seem like a pathological case. The queue will rarely be empty and resyncs are unlikely to be popped that fast. It seems that this flake is a rare one so we don't really need to fix it now. I still need to get to reproduce this and understand why we had so many resyncs in such a short period of time.

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10457/consoleFull#13294255005762928fe4b031e1b25ced2a

**Comment by smarterclayton** [comment]
```
--- FAIL: TestTriggers_configChange (5.46s)
	deploy_trigger_test.go:666: Operation cannot be fulfilled on deploymentconfigs "config": the object has been modified; please apply your changes to the latest version and try again
	etcd.go:99: dumping etcd to "/tmp/openshift/test-integration//etcd-dump-runtime.call32.json"
```

**Comment by smarterclayton** [comment]
Happing fairly often.  Bumping priority.

**Comment by smarterclayton** [comment]
In case we actually broke config change triggers for some reason.

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/11074/

**Comment by mfojtik** [comment]
@smarterclayton the fix should be merging now... we bumping the number of retries until we have Patch() in integration and we use it instead of Update().
