### ISSUE TITLE
docker push throwing error 500

### ISSUE THREAD

**Issue by joekohut** [openshift/origin#11782]
With latest atomic registry build -
Getting error 500 while trying to push an image:

##### Version
oc v1.4.0-alpha.1+9c565ab-8
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v1.4.0-alpha.1+9c565ab-8
kubernetes v1.4.0+776c994

##### Steps To Reproduce
docker login using token issued from https://myregistry:9090 site
docker tag -f docker.io/hello-world myregistry.mydomain.com:5000/hello/hello
docker push myregistry.mydomain.com:5000/hello/hello

##### Current Result

docker push myregistry.mydomain.com:5000/hello/hello
The push refers to a repository [myregistry.mydomain.com:5000/hello/hello] (len: 1)
95f1eedc264a: Pushed
6432e0ccba2d: Pushed
latest: digest: sha256:500b65b612ec59c692d94b7a42e7f689652b41aecfc1602f258dd3efe5c4bb75 size: 2097
Received unexpected HTTP status: 500 Internal Server Error

Created the hello repository ahead of time.

##### Expected Result

image gets pushed

**Comment by ncdc** [comment]
Please pastebin/gist the logs from your docker-registry pod. Thanks!

**Comment by joekohut** [comment]
those tools are blocked for me.

how's this:
[atomic-registry.docker.txt](https://github.com/openshift/origin/files/572340/atomic-registry.docker.txt)

**Comment by ncdc** [comment]
`error creating ImageStreamMapping: User \"system:anonymous\" cannot create imagestreammappings in project \"hello\"`.

Looks like your `docker login` didn't work?

**Comment by joekohut** [comment]
It certainly did - I used the token - 
docker login -p D8XMbgJqSlur-CkCLvEAEay3wpkM6-7nx5iWpZPui1k -e unused -u unused myregistry.mydomain.com:5000
WARNING: login credentials saved in /root/.docker/config.json
Login Succeeded

**Comment by ncdc** [comment]
What does `oc project` print out?

**Comment by liggitt** [comment]
imagestreammappings are created using the registry's client... how is the registry starting up?

**Comment by ncdc** [comment]
Oh, right... So it sounds like the registry is misconfigured.

**Comment by ncdc** [comment]
Note this is atomic registry

**Comment by joekohut** [comment]
I don't know why it states ImageStream - I created a "new project" only.
Yes, it is atomic-registry.
Version
oc v1.4.0-alpha.1+9c565ab-8

**Comment by ncdc** [comment]
We manage image streams under the covers for you. When you push, you're pushing to an image stream. The act of pushing is actually creating an ImageStreamMapping resource, and that's what's failing. It appears that your registry is not properly authenticating to the master. Did you get any errors when you installed the registry? Did you change the configuration post installation in any way? Reinstall at any time?

**Comment by joekohut** [comment]
This is all bare bones, which is why I am posting here ...
atomic install projectatomic/atomic-registry-install myregistry.mydomain.com
sudo systemctl enable --now atomic-registry-master.service
sudo /var/run/setup-atomic-registry.sh
goto port 9090
create project hello 
scrape docker login line
docker tag
docker push
ERROR 500

**Comment by ncdc** [comment]
I installed Atomic Registry and was able to follow your steps and push. Can you paste the output of `docker inspect atomic-registry`?

**Comment by joekohut** [comment]
[atomic-registry.inspect.txt](https://github.com/openshift/origin/files/575762/atomic-registry.inspect.txt)

**Comment by ncdc** [comment]
Ok it looks like you're running into a similar issue that I encountered. Can you edit /etc/sysconfig/atomic-registry and add the line

```
DOCKER_REGISTRY_SERVICE_HOST=<url of your registry>
```

Once you've done that, restart atomic-registry and see if that works any better. If it does not, could you please verify that /etc/atomic-registry/serviceaccount has files in it?

**Comment by joekohut** [comment]
Please share an example.

DOCKER_REGISTRY_SERVICE_HOST=<url of your registry>

 I tried  DOCKER_REGISTRY_SERVICE_HOST=myhost as well as DOCKER_REGISTRY_SERVICE_HOST=https://myhost:5000
and observe no change after restarting each time.

FROM THE HOST:
ls /etc/atomic-registry/serviceaccount
ca.crt  namespace  README  service-ca.crt  token

**Comment by joekohut** [comment]
Please share an example.


DOCKER_REGISTRY_SERVICE_HOST=<url of your registry>


I tried  DOCKER_REGISTRY_SERVICE_HOST=myhost as well as DOCKER_REGISTRY_SERVICE_HOST=https://myhost:5000
and observe no change after restarting each time.

FROM THE HOST:
ls /etc/atomic-registry/serviceaccount
ca.crt  namespace  README  service-ca.crt  token

**Comment by ncdc** [comment]
myregistry.mydomain.com

**Comment by joekohut** [comment]
Unfortunately, the FQDN entry did not help.

As an aside, here is a snippet from atomic-registry-master log:

I1107 15:51:47.969149       1 master.go:392] Started Origin API at 0.0.0.0:8443/oapi/v1
I1107 15:51:47.969155       1 master.go:392] Started OAuth2 API at 0.0.0.0:8443/oauth
I1107 15:51:47.969161       1 master.go:392] Started Web Console 0.0.0.0:8443/console/
I1107 15:51:47.969167       1 master.go:392] Started Swagger Schema API at 0.0.0.0:8443/swaggerapi/
I1107 15:51:47.969180       1 master.go:392] Started OpenAPI Schema at 0.0.0.0:8443/swagger.json
I1107 15:51:48.514959       1 trace.go:61] Trace "Create /api/v1/namespaces/openshift-infra/serviceaccounts" (started 2016-11-07 15:51:48.178447525 +0000 UTC):
[15.905Âµs] [15.905Âµs] About to convert to expected version
[73.382Âµs] [57.477Âµs] Conversion done
[300.92588ms] [300.852498ms] About to store object in database
[336.477166ms] [35.551286ms] END

**Comment by ncdc** [comment]
Ok, I'll have to turn this over to @legionus for further assistance.

**Comment by joekohut** [comment]
Thank you for looking at this issue.

**Comment by aweiteka** [comment]
@joekohut I reproduced your issue and believe it's due to an empty `/etc/atomic-registry/serviceaccount/token` file. Please confirm.

**Temporary workaround**

1. Run these two commands to print the token:

        TOKEN_NAME=$(sudo docker exec atomic-registry-master oc get sa registry --template '{{ $secret := index .secrets 1 }} {{ $secret.name }}')
        sudo docker exec atomic-registry-master oc get secret ${TOKEN_NAME} --template '{{ .data.token }}' | base64 -d
1. Copy the token (be careful: there's no new line at the end of the token string) and paste into this file:

        /etc/atomic-registry/serviceaccount/token
1. Restart registry service

        sudo systemctl restart atomic-registry.service

**Cause**

The `/var/run/setup-atomic-registry.sh` script uses a hard-coded index int to grab the registry secret name. In some cases (?) the incorrect secret is referenced and it cannot decode a valid token for the registry service.

**Comment by aweiteka** [comment]
Proposed workaround pushed to installer image docker.io/projectatomic/atomic-registry-install

**Comment by joekohut** [comment]
Thanks for looking into this. I pulled a new version of the installer and it still left the token file empty. I went back to the workaround - I stuffed the token into the token file, and that made progress in that I was able to install and authen/authorize to the registry - this resolved the system:anonymous error 500. Yet, I now receive a different error 500 regarding "invalid reference format". I am still unable to push an image. Pls advise.

Client side:
docker login -p R7ExtIXXNdNgOLGcFJH9Yp0xuYtphYUXsNU_jPXWmFY -e unused -u unused docker-x0.mydomain.com:5000
Flag --email has been deprecated, will be removed in 1.13.
Login Succeeded
docker tag hello-world docker-x0.mydomain.com:5000/joe/hello-world
docker push docker-x0.mydomain.com:5000/joe/hello-world
The push refers to a repository [docker-x0.mydomain.com:5000/joe/hello-world]
a02596fdd012: Layer already exists
received unexpected HTTP status: 500 Internal Server Error

Registry Logs:
IP - - [28/Nov/2016:15:17:10 +0000] "PUT /v2/joe/hello-world/manifests/latest HTTP/1.1" 500 697 "" "docker/1.12.1 go/go1.6.2 git-commit/083ee20 kernel/3.10.0-327.36.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"
time="2016-11-28T15:17:10.701632169Z" level=error msg="error creating ImageStreamMapping: ImageStreamMapping \"hello-world\" is invalid: image.dockerImageReference: Invalid value: \":5000/joe/hello-world@sha256:d7b61d216202150821d37ebf08b07f843cf6ada74638369e05b6b9b15bdd6c95\": invalid reference format" go.version=go1.6.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v1+prettyjws" http.request.host="docker-x0.mydomain.com:5000" http.request.id=47400a69-c50b-4d3f-bddc-8d82c490cd1f http.request.method=PUT http.request.remoteaddr="10.93.104.20:55592" http.request.uri="/v2/joe/hello-world/manifests/latest" http.request.useragent="docker/1.12.1 go/go1.6.2 git-commit/083ee20 kernel/3.10.0-327.36.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))" instance.id=bd55378b-b887-497c-a1f3-750b088a82e7 vars.name="joe/hello-world" vars.reference=latest
time="2016-11-28T15:17:10.701870983Z" level=error msg="response completed with error" err.code=unknown err.detail="ImageStreamMapping \"hello-world\" is invalid: image.dockerImageReference: Invalid value: \":5000/joe/hello-world@sha256:d7b61d216202150821d37ebf08b07f843cf6ada74638369e05b6b9b15bdd6c95\": invalid reference format" err.message="unknown error" go.version=go1.6.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v1+prettyjws" http.request.host="docker-x0.mydmomain.com:5000" http.request.id=47400a69-c50b-4d3f-bddc-8d82c490cd1f http.request.method=PUT http.request.remoteaddr="IP:55592" http.request.uri="/v2/joe/hello-world/manifests/latest" http.request.useragent="docker/1.12.1 go/go1.6.2 git-commit/083ee20 kernel/3.10.0-327.36.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=20.587361ms http.response.status=500 http.response.written=697 instance.id=bd55378b-b887-497c-a1f3-750b088a82e7 vars.name="joe/hello-world" vars.reference=latest

**Comment by ncdc** [comment]
This is because /etc/sysconfig/atomic-registry is missing a value for `DOCKER_REGISTRY_SERVICE_HOST`.

**Comment by joekohut** [comment]
Thanks. Sure is - that did the trick. Everything is working, albeit with two manual config tweaks. Are these two config issues something that you can **resolve in the installer**? fyi - I also happened to notice that atomic-registry services do not start under docker 1.12. I reverted to docker 1.10.

**Comment by aweiteka** [comment]
> Are these two config issues something that you can resolve in the installer?

I have pushed a fix to image docker.io/projectatomic/atomic-registry-install

> fyi - I also happened to notice that atomic-registry services do not start under docker 1.12. I reverted to docker 1.10.

This makes me sad.

**Comment by joekohut** [comment]
Aaron, the latest image works flawlessly and has resolved the two config issues in this request #11782.
Thanks for fixing!
Hopefully, someone can take a look at the docker 1.12 issue in a different ticket.
Closing as RESOLVED.
