### ISSUE TITLE
Node 0.10 is EOL.

### ISSUE THREAD

**Issue by jdalton** [openshift/origin#11797]
I noticed that openshift [supports Node.js applications](https://developers.openshift.com/languages/nodejs/).
Unfortunately it stats that it supports  nodejs-0.10 which is EOL.

For upgrading the [latest LTS](https://github.com/nodejs/LTS) is Node 6.

**Comment by PI-Victor** [comment]
@jdalton i think you want the other version of openshift. this repo's for the v3.
not sure 100% but i think you can open an issue at: https://github.com/openshift/origin-server

**Comment by jdalton** [comment]
Thanks, moved to https://github.com/openshift/origin-server/issues/6429.
