### ISSUE TITLE
State of examples/data-population

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#11809]
It's not clear what the purpose of examples/data-population is, or that what is there currently works with the latest tree.  Example: if I run populate.sh, my events fill up with "Error creating: pods "app-X-1-build" is forbidden: failed quota: quota: must specify memory"

It would be good to document the purpose of the example, add some testing to ensure it is behaving as specified, or remove it.

**Comment by ianmiell** [comment]
Also: if you have other scripts you prefer to use, please point me at them :)

**Comment by pweil-** [comment]
@mfojtik are these useful anymore?

**Comment by mfojtik** [comment]
@derekwaynecarr @smarterclayton do we need examples/data-population?
