### ISSUE TITLE
oc rsh encryption

### ISSUE THREAD

**Issue by rudijs** [openshift/origin#11801]
Hi,

We've had an external security review and one of the items highlighted was 'oc rsh':

` Traffic sent between an rsh client and rsh server is unencrypted, meaning it is susceptible to eavesdropping`

I'm pretty sure 'oc rsh'  is tunneled through TLS, but I'm not able yet to find that clearly documented (so I can link to it in my follow up report on this advisory)

Is the security or encryption that rsh uses in the docs?

##### Version
1.1.4

##### Steps To Reproduce
oc rsh -h

**Comment by ncdc** [comment]
If your master and nodes are secured with certificates, then `oc rsh` is secured. If your masters/nodes allow insecure connections, then it's possible that `oc rsh` is unencrypted. But our default setup is to use certificates and encrypt communications.

**Comment by rudijs** [comment]
OK great.

I've also done a wireshark packet capture and can see dest port 8443 is all encrypted.

Thanks!
