### ISSUE TITLE
Dump etcdv3 contents in tests

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#11837]
We're only getting stuff from etcdv2 right now.

/cc @deads2k

**Comment by mfojtik** [comment]
I rewrote the dumper recently when we got rid of go-etcd client. I can take a look on dumping etcd3 content as well, but AFAIK for 1.4 we staying on etcd2.

**Comment by stevekuznetsov** [comment]
@mfojtik I don't know what "the dumper" is but I mean this recursive dump: https://github.com/openshift/origin/blob/master/hack/lib/cleanup.sh#L16

**Comment by stevekuznetsov** [comment]
We've re-enabled etcd v3 in our tests so this is relevant again.

**Comment by deads2k** [comment]
To whoever picks this up (everyone owns CI, so there's no telling who it will be), remember that etcd3 storage is all protobuf (that's what we want to test), so the dump will be undecodable, unsearchable, and unparseable with any normal tools.

**Comment by mfojtik** [comment]
WIP: https://github.com/openshift/origin/pull/14145

**Comment by simo5** [comment]
@enj @stevekuznetsov is this really a P1 ?
If so we clearlyned to hand this to someone else as it is not getting done.

**Comment by stevekuznetsov** [comment]
If nobody is missing this, then it seems ok to bump down from p1
