### ISSUE TITLE
Suggestion: append in `oc` a warning message if you use oc version < OpenShift server version

### ISSUE THREAD

**Issue by harobed** [openshift/origin#11836]
I've lost many time with this mistake: http://lists.openshift.redhat.com/openshift-archives/users/2016-November/msg00071.html

« Your version of oc is too old. Your file works for me, when I use 1.3.0+, but I get the same error as you when using 1.2.0. »

Suggestion: append in `oc` a warning message if you use `oc` version < OpenShift server version.

**Comment by kargakis** [comment]
@openshift/cli-review

**Comment by juanvallejo** [comment]
Would this be something a user sees when specific commands / actions fail, or could this be a warning placed under a command such as `oc version` / `oc login`?

**Comment by harobed** [comment]
> Would this be something a user sees when specific commands / actions fail

:+1:
