### ISSUE TITLE
Short write during oc exec (long output)  and   oc rsh (long input & ouput)

### ISSUE THREAD

**Issue by jupierce** [openshift/origin#11841]
Attempting to cat the file https://gist.github.com/jupierce/c15f2ec12b6431f47eb6ae23a7519966
results in a consistent "short write" error from go.

v2.go:147] short write

##### Version
oc v1.4.0-alpha.0+567c5e1-854-dirty
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://192.168.1.103:8443
openshift v1.4.0-alpha.0
kubernetes v1.4.0-beta.3+d19513f

##### Steps To Reproduce
**To create for oc-exec:**
1. Copy the file https://gist.github.com/jupierce/c15f2ec12b6431f47eb6ae23a7519966 into a running pod (e.g. the path /tmp/file)
2. oc exec <pod name> -- cat /tmp/file

**To create for oc-rsh:**
1. Copy the file https://gist.github.com/jupierce/c15f2ec12b6431f47eb6ae23a7519966 to a local file system location (e.g. /tmp/file)
2. cat /tmp/file | oc rsh <pod name> tee /tmp/file

##### Current Result
A significant portion of the file prints, but the process eventually stops and prints:
v2.go:147] short write

##### Expected Result
The file should print successfully.

##### Additional Information
- RSH does not suffer the same problem as exec when simply printing the file: oc rsh <pod name> cat /tmp/file   
- The underlying problem can cause oc exec to never return. I initially discovered the issue using jmap on a JVM instance running in a pod. In this scenario, oc exec reports the short write, but never terminates. 

@derekwaynecarr - @bparees Thought you might have the most insight on this one.

**Comment by pweil-** [comment]
related PR: https://github.com/openshift/origin/pull/11680

**Comment by aveshagarwal** [comment]
I am looking into it.

**Comment by jupierce** [comment]
@pweil- @aveshagarwal . I just pulled #11680 into my environment. I'm no longer able to reproduce this. Thank you.
