### ISSUE TITLE
Support csproj files for identifying .NET Core projects

### ISSUE THREAD

**Issue by omajid** [openshift/origin#11842]
(This is a heads up for something that will become an issue in the future)

OpenShift supports .NET Core images and relies on `project.json` files to [identify a project as .NET](https://github.com/openshift/origin/blob/85eb37b34f0657631592356d020cef5a58470f8e/pkg/generate/source/detector.go#L71). An upcoming version of .NET Core will switch from using `project.json` files to `${PROJECT_NAME}.csproj` files: [.NET Core Tooling](https://blogs.msdn.microsoft.com/dotnet/2016/10/19/net-core-tooling-in-visual-studio-15/). This change is being added to Visual Studio right now and will be added to .NET Core in a later release (possibly in a couple of months).

OpenShift will need to update the detection routines to pick up these `csproj` files to identify a .NET Core project in addition to `project.json` files.

**Comment by jerboaa** [comment]
@bparees A heads-up for you so you can plan accordingly.

**Comment by bparees** [comment]
@jim-minter maybe while you're doing the updates for jenkinsfile support, you can go ahead and add this to the .net detection logic.
