### ISSUE TITLE
os::log::warn function prints newline character as-is

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#11853]
##### Version
Commit: 058a0d827b7184ade97c49b93fc1f1118ae640ae

##### Steps To Reproduce
```console
$ ./hack/test-integration.sh TestOadmPodNetwork
```

##### Current Result
```console
$ ./hack/test-integration.sh TestOadmPodNetwork
...
[WARNING] System logger could not be started, 'sar' binary not found in this environment.\n
ok      TestOadmPodNetwork
```

##### Expected Result
New line character shouldn't be shown.

##### Additional Information
This message is printed in `os::log::system::start` function:
```bash
function os::log::system::start() {
	if ! which sar >/dev/null 2>&1; then
		os::log::warn "System logger could not be started, 'sar' binary not found in this environment."
```
Let's look at the `os::log::warn` implementation:
```bash
function os::log::warn() {
		os::text::print_yellow "[WARNING] $*\n" 1>&2
}
```
And to the `os::text::print_yellow` declaration:
```bash
function os::text::print_yellow() {
		os::text::yellow
		echo "${*}"
		os::text::reset
}
```
As we can see `os::log::warn` passes string that contains `\n` to `os::text::print_yellow` function that is using `echo` and doesn't expand new line symbol.

Because `echo` always add a newline after the message we shouldn't append it manually in `os::log::warn`.

**Comment by php-coder** [comment]
CC @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Rebase to current `master`, this is fixed.

**Comment by php-coder** [comment]
For the history: related PR is https://github.com/openshift/origin/pull/11783
