### ISSUE TITLE
oc cluster up fails to install metrics

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#11859]
There has been a change in origin metrics where we now need to have the view permission for the Hawkular Metrics pod (required for clustering the application server).

Currently the Hawkular Metrics pod will fail with instruction on how to fix it, but we should update the oc cluster up command to add this.

**Comment by mwringe** [comment]
PR: https://github.com/openshift/origin/pull/11860

**Comment by mwringe** [comment]
@csrwng can you take a look at the PR?

**Comment by spadgett** [comment]
Looks like this was fixed by #11860

/close
