### ISSUE TITLE
Extended.[k8s.io] Generated release_1_2 clientset should create pods, delete pods, watch pods

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#11867]
```
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/generated_clientset.go:193
Nov 10 04:16:47.312: Failed to observe pod deletion
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/generated_clientset.go:117
```

Observed here: https://github.com/openshift/origin/pull/11774

**Comment by ncdc** [comment]
I looked at the logs. I think this is just another general "slow" issue. Could be something about the VM, or something else, but stuff just didn't happen fast enough.

**Comment by mfojtik** [comment]
@ncdc +1 i haven't seen this flake recently, however in last two days I saw at least 2 ultra-rare flakes all related to "slowness" (an empty namespace failed to remove and this.)

**Comment by stevekuznetsov** [comment]
It is probably linked to something messing up in the docker daemon, we saw #11870 as well recently.
