### ISSUE TITLE
Conformance suite times out after five hours -- structural failure

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#11870]
Looks like we have a structural failure (Docker daemon, maybe?) that leads to all of our timeouts getting hit in a conformance run, which then gets force-killed at 5hours. 

See: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8537/console

**Comment by stevekuznetsov** [comment]
Similar thing happened in the past: https://github.com/openshift/origin/issues/9965

**Comment by stevekuznetsov** [comment]
https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/origin_extended_image_tests/751/

**Comment by oatmealraisin** [comment]
https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/origin_extended_image_tests/755/consoleFull#195601705956cbb9a5e4b02b88ae8c2f77

**Comment by pweil-** [comment]
> https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/origin_extended_image_tests/751/

cc @kargakis another "timed out waiting for condition"

**Comment by stevekuznetsov** [comment]
My bet is this has to do with instability we inherited from the Docker 1.12 bump. @ncdc has other thoughts.

**Comment by ncdc** [comment]
Re the link from @pweil-, that is a bug. See #11922 for a possible fix.

**Comment by ncdc** [comment]
I haven't started looking into `error creating federation client config: invalid configuration: no configuration has been provided` yet
