### ISSUE TITLE
oc logs does not work  for pipeline builds

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#11871]
For a regular build you can get logs by `oc logs build/nodejs-ex-1`. But this doesn't work for build with pipeline strategy.

Problem is that even the API `/oapi/v1/namespaces/{namespace}/builds/{name}/log` is broken (probably not implemented) for this. 

##### Version
```
$ oc version
oc v1.4.0-alpha.1+ee5a124-135-dirty
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://192.168.42.42:8443
openshift v1.4.0-alpha.1+43fbf69-133
kubernetes v1.4.0+776c994
```
##### Steps To Reproduce
- have a pipeline build
```
$ oc get build nodejs-ex-pipeline-6
NAME                   TYPE              FROM           STATUS     STARTED          DURATION
nodejs-ex-pipeline-6   JenkinsPipeline   Git@sync-WIP   Complete   16 minutes ago   1m10s
```
```
$ oc logs build/nodejs-ex-pipeline-6
Error from server: pod "nodejs-ex-pipeline-6-build" not found
```

##### Current Result
Not found

##### Expected Result
Show logs

**Comment by mfojtik** [comment]
@tnozicka AFAIK the logs for pipeline builds are not implemented yet as it will require proxying logs from the Jenkins (IMHO).

**Comment by bparees** [comment]
trello'd https://trello.com/c/TcYufF8n
