### ISSUE TITLE
GitHub authentication based on teams

### ISSUE THREAD

**Issue by e-bits** [openshift/origin#11882]
Would it be possible to enhance the GitHub OAuth to authenticate against teams within an organisation? At the moment the authentication works against organisations and i think i would be nice to have a kind of a smaller unit to grant access, especally for larger organisations.

Is someone else intrestet in this? What do you think? @liggitt

**Comment by liggitt** [comment]
see #11931

**Comment by e-bits** [comment]
Thanks a lot, you guys are awesome 👍

**Comment by liggitt** [comment]
closing this issue, feature is tracked in https://trello.com/c/akzREfyn/836-allow-github-identity-provider-to-require-team-membership, implemented in #11931, documented in https://github.com/openshift/openshift-docs/pull/3237
