### ISSUE TITLE
traffic splitting of A/B deployment is by replicas but not by service

### ISSUE THREAD

**Issue by tj13** [openshift/origin#11881]
##### Version
$ oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://cjjoc01.sit.caijj.net:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. config an  a/b deployment for application logresolver. 
2. create two service logresolver-a with one replica and logresover-b with two replicas, 
2. check the weight in haproxy config

##### Current Result
1. on web console, 10% traffic is routed to service logresolver-a, 90% traffic is routed to service logresolver-b.
![image](https://cloud.githubusercontent.com/assets/14867953/20210817/5b26f256-a836-11e6-9f88-dd32dabb07c4.png)
2. checked haproxy configuration
![image](https://cloud.githubusercontent.com/assets/14867953/20210846/7bded2de-a836-11e6-817f-178fe52a65b8.png)

**Comment by rajatchopra** [comment]
Fixed by #15903

**Comment by pravisankar** [comment]
Fixed by https://github.com/openshift/origin/pull/15309
