### ISSUE TITLE
osc needs a version too

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1189]
For those who may just have the osc client (don't have / aren't aware of "openshift" binary)... it needs a command to indicate its own version like `openshift version` does.

**Comment by kargakis** [comment]
How can someone have/use `osc` without the `openshift` binary?

**Comment by sosiouxme** [comment]
If you download any of the releases at https://github.com/openshift/origin/releases then "osc" and "openshift" binaries are included (they are the same, but different name and not a symlink). The user could then feel free to delete "openshift" if they don't want to run their own service and just use osc. Or they might just move it into /usr/bin or whatever - in any case, there is no link to the "openshift" binary from downloaded osc, so no simple way to determine its version.

**Comment by kargakis** [comment]
I've added a [fix](https://github.com/openshift/origin/pull/1199) for this.

**Comment by sosiouxme** [comment]
Thanks.
