### ISSUE TITLE
Jenkins fails to highlight failed tests

### ISSUE THREAD

**Issue by oatmealraisin** [openshift/origin#11890]
Only one of the failures with [this test](https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/origin_extended_image_tests/751/) shows up. Is this intentional? I wasn't able to find this skip in other test failures.

**Comment by stevekuznetsov** [comment]
As far as the regex in the failure cause management entry only catching one failure message, nothing we can do about that I don't think. I've definitely seen it catch more than one instance, so I don't really know when it chooses not to.
