### ISSUE TITLE
Multiple test fails 

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#11903]
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/793/

	Test Result (11 failures / +10)

    Extended.[k8s.io] Garbage collector [Feature:GarbageCollector] should delete pods created by rc when not orphaning
    Extended.[networking] OVS generic should add and remove flows when pods are added and removed
    Extended.[imageapis] openshift limit range admission should deny a push of built image exceeding openshift.io/Image limit
    Extended.[k8s.io] Deployment RollingUpdateDeployment should scale up and down in the right order
    Extended.[networking] OVS generic should add and remove flows when nodes are added and removed
    Extended.[k8s.io] Federation secrets [Feature:Federation12] Secret objects should be created and deleted successfully
    Extended.[image_ecosystem][jenkins] schedule jobs on pod slaves use of jenkins with kubernetes plugin by creating slave from existing builder and adding it to Jenkins master
    Extended.[k8s.io] Deployment deployment should label adopted RSs and pods
    Extended.[k8s.io] Deployment RollingUpdateDeployment should delete old pods and create new ones
    Extended.[k8s.io] Deployment RecreateDeployment should delete old pods and create new ones

**Comment by coreydaley** [comment]
Happened again, got 12 failures this time
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/797/

**Comment by pweil-** [comment]
@kargakis this looks like a grab bag of "timed out waiting for the condition" issues but maybe not related to ns deletions like some of the other flakes we've seen where the "pods remaining" message is also given.  Since quite a few are in deployments maybe you can take a look.

**Comment by pweil-** [comment]
maybe fixed here: https://github.com/openshift/origin/issues/11870#issuecomment-260774252

**Comment by ncdc** [comment]
I'm working on fixing this in #11922 but I'd be happy to have someone take it over. Some notes:

- we don't have the garbage collector enabled, so we need to skip those tests for now
- the OVS tests shouldn't run in core.sh (they're run by networking.sh)
- Deployment tests are broken because the SA the deployment controller uses doesn't have permission to update pods. We should probably open an kube issue to minimize the permissions that controller needs - updating all pods is pretty broad.
- not yet sure why the limit range admission plugin is trying to pull scratch
- I haven't looked into the others yet

**Comment by kargakis** [comment]
The upstream deployment controller updates pods for replica sets that don't have the podtemplate hash that separates them from other deployment pods (helps in adoption of replica sets). I will have a look tomorrow.

**Comment by ncdc** [comment]
I think I prematurely said 11922 fixed this. Now that 11922 and #11945 are in, everything should pass except for the jenkins failure.

**Comment by kargakis** [comment]
> I think I prematurely said 11922 fixed this. Now that 11922 and #11945 are in, everything should pass except for the jenkins failure.

Not sure what that is.

**Comment by ncdc** [comment]
Gabe looked into it. It's a Jenkins build e2e test

**Comment by gabemontero** [comment]
The test:

```
Extended.[image_ecosystem][jenkins] schedule jobs on pod slaves use of jenkins with kubernetes plugin by creating slave from existing builder and adding it to Jenkins master
```

has been replaced via https://github.com/openshift/origin/pull/11844

The replacement test has been clean in various runs since the merge.

Closing this out.
