### ISSUE TITLE
"openshift.io/container.%s.image.entrypoint" annotation

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#11906]
oc debug introduced the "openshift.io/container.%s.image.entrypoint" annotation.

AFAICS:
- this is used as a heuristic to helpfully indicate to the end user what the pod entrypoint might be when running oc debug
- the only place that actually seems to set this is oc new-app (set on the DC then the DC annotates created pods)

Some drawbacks of this approach are:
- not all pods are created via oc new-app; if a pod isn't, this heuristic doesn't exist to help oc debug users for that pod
- the annotation could straightforwardly get out of sync with the container - e.g. if the container is updated with a new entrypoint and the DC isn't edited, or if someone copy/pastes to a template
- the fact that oc new-app substitutes the container name into the annotation limits the length of valid container names from 63 to 36 (63 - len("container..image.entrypoint")) (https://bugzilla.redhat.com/show_bug.cgi?id=1392764; #11895)

Is there willingness / a sensible technical route to revisit this design decision?
E.G. could the annotation be placed on a pod when it is admitted, or could oc debug correctly discover the actual entrypoint in use from the kubelet, or something else?

@bparees 
@smarterclayton

**Comment by jim-minter** [comment]
@wanghaoran1988

**Comment by bparees** [comment]
@smarterclayton this is a question for you since it appears you introduced the annotation and mechanism for consuming it.

**Comment by liggitt** [comment]
That should probably be made index-based or the user-specified aspects be moved into the annotation value. Limiting the name length for that reason is bad.

**Comment by smarterclayton** [comment]
We don't need the annotation in the long run.  It was a stop gap before we
had resolved images.  I'd prefer to replace it with a conditional lookup on
imagestreamimport and indicate if that image can't be found or an error
occurs (image lookup cannot block debug, and is just advisory).

On Nov 14, 2016, at 12:57 PM, Jordan Liggitt <notifications@github.com>
wrote:

That should probably be made index-based or the user-specified aspects be
moved into the annotation value. Limiting the name length for that reason
is bad.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/11906#issuecomment-260409972>,
or mute the thread

**Comment by jim-minter** [comment]
Sorry, I don't understand what is meant by "conditional lookup on imagestreamimport".  I can see that with an image on an imagestream, the entrypoint seems to be findable via the API via oc get isimage or oc get image (although I'm not sure what the difference between these two is).

I'm not clear what should be done for the case of an arbitrary docker image (which I think is important use case, although it's not covered by today's stopgap).  If I do oc import-image, I can then sort-of then see the detail via oc get isimage or oc get image, BUT the imageID reported on the pod or via docker inspect does not correspond to any sha visible in oc get isimage or oc get image (also not clear why that should be?)

**Comment by bparees** [comment]
@smarterclayton who owns the debug feature so we can get this cleaned up?

**Comment by smarterclayton** [comment]
Whoever wants to fix it.

This is informational, so trying an image import and not getting the exact
value is ok.  imageID was broken but is fixed in more recent versions of
Red Hat Docker (talk to Andy or Derek about that).

**Comment by bparees** [comment]
@rhcarvalho you're the only person i know is on the diagnostics team, feel free to get this reassigned, but i think it probably should be owned by that team.

**Comment by bparees** [comment]
>  I'd prefer to replace it with a conditional lookup on imagestreamimport 

@smarterclayton did you mean imagestreamimage here?  

Assuming so, @jim-minter, it seems like the proposal is to do away w/ the annotation and instead, on invocation of oc debug, look up the imagestreamimage for the container and determine the entrypoint that way.  Not sure what the implication is for images that don't have imagestreamimages associated (ie containers that are running an image directly from dockerhub, not via an imagestream reference).  But that would still maintain parity with the existing behavior (which only works for new-app created stuff which means imagestream referencing stuff).

**Comment by bparees** [comment]
diagnostics team says they don't own oc debug and @smarterclayton has implied devex does own it, so we'll let @jim-minter continue w/ this.

still need an answer from @smarterclayton on what was meant by "lookup on imagestreamimport"
