### ISSUE TITLE
RFE: allow listing all imagestreamimages

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#11915]
It would be nice if the server would allow listing all imagestreamimages in a namespace / all namespaces.

##### Version
oc v1.4.0-alpha.1+9c4f9ee-179
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://192.168.121.16:8443
openshift v1.4.0-alpha.1+9c4f9ee-179
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. oc get isimage

##### Current Result
No resources found.
Error from server: Unable to list "imagestreamimages": the server could not find the requested resource

##### Expected Result
It would be nice if the server would allow listing all imagestreamimages in a namespace / all namespaces.

(oc get isimage does work today if you provide it the specific <name>@<id> that you already know exists).

**Comment by kargakis** [comment]
cc: @mfojtik @soltysh

**Comment by soltysh** [comment]
Not sure if there's a proper justification for such an action, given the fact that neither ISI or IST does not exist. They are virtual objects, that's why listing them would mean listing IS and extracting information about particular ISI/IST and then returning to a user. I'm lowering the prio since I don't see this being super important to pursue.

**Comment by kargakis** [comment]
@soltysh we already support getting single images, listing is desirable too

**Comment by soltysh** [comment]
True, but that's again, getting a single instance needed for build, deployment, etc. Not sure about the importance of getting all ISIs or ISTs. Seems quite burdensome when I think of the results.

**Comment by kargakis** [comment]
We don't use the ISI api/client for getting images for deployments. For me it makes sense to provide at least read actions on these resources. We don't have a good way for letting users know how many images they have in their namespace.

**Comment by soltysh** [comment]
Do you care how many ISIs you have, besides some of them will be pointing to old images, which will actually blur the picture. I'm not strongly convinced into this.

**Comment by jim-minter** [comment]
Some notes: oc get imagestreamtags already works, and `oc get` specifically lists 'imagestreamimages' (plural) as a valid thing to get (but it doesn't yet work).

The fact that you can do 'oc get collection' on different types of object broadly regardless of their type is a very important API feature and foundation for end users who are learning to use the platform.  It is important for transparency of the platform and for understanding.  In general imagestreams, tags and images are a very valuable feature but somewhat opaque and surprisingly hard for end users to understand and reason about.  So IMO someting that adds clarity surely helps here.

**Comment by kargakis** [comment]
Agreed with @jim-minter, our APIs should be consistent.

**Comment by soltysh** [comment]
> Agreed with @jim-minter, our APIs should be consistent.

They are not and I doubt ever will be.

**Comment by bparees** [comment]
trello'd https://trello.com/c/0qC3syQK
