### ISSUE TITLE
Bad "UPDATED" value on ImageStreamImage

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#11914]
When run (for example) on a new-app created app, os get isimage return an UPDATED value of "292 years ago".

##### Version
oc v1.4.0-alpha.1+9c4f9ee-179
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://192.168.121.16:8443
openshift v1.4.0-alpha.1+9c4f9ee-179
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. oc new-app https://github.com/openshift/nodejs-ex
2. wait for build to complete
3. oc get isimage nodejs-ex@$(oc get is nodejs-ex --template '{{(index (index .status.tags 0).items 0).image}}')

##### Current Result
```
NAME                                                                                DOCKER REF                                                                                                  UPDATED         IMAGENAME
nodejs-ex@sha256:8aac4dd5692f7ed4aa1558f88ca6eebbbc0e1e36b368d5abf298897e66b3cd6f   172.30.32.164:5000/demo/nodejs-ex@sha256:8aac4dd5692f7ed4aa1558f88ca6eebbbc0e1e36b368d5abf298897e66b3cd6f   292 years ago   sha256:8aac4dd5692f7ed4aa1558f88ca6eebbbc0e1e36b368d5abf298897e66b3cd6f
```
##### Expected Result
UPDATED should not read "292 years ago".

**Comment by kargakis** [comment]
cc: @mfojtik @soltysh @miminar @legionus

**Comment by mfojtik** [comment]
Fixed here: https://github.com/openshift/origin/pull/12052
