### ISSUE TITLE
'cluster up': pods cannot access a service that points back to the pod

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#11929]
When running a cluster created with 'cluster up', a pod cannot access a service (by name or ip) that points to itself. The request simply times out.

This is not the case when running a cluster with plain 'openshift start'

##### Version
oc v1.4.0-alpha.1+9c4f9ee-179
kubernetes v1.4.0+776c994
features: Basic-Auth

Server 
openshift v1.4.0-alpha.1+9c4f9ee-179
kubernetes v1.4.0+776c994

**Comment by csrwng** [comment]
@thoraxe fyi

**Comment by jim-minter** [comment]
@csrwng I think #12111 is identical - maybe worth closing this in favour of the other as it has more info?

**Comment by csrwng** [comment]
@jim-minter sounds good. 
Dupe of #12111
