### ISSUE TITLE
Latest release for client tools on GitHub is not always the correct one

### ISSUE THREAD

**Issue by rassie** [openshift/origin#11932]
Currently, the link to the latest release (also available from console help) is https://github.com/openshift/origin/releases/latest, which points to the latest released binary (1.2.2) as opposed to the stable release with the highest version (1.3.1). This has probably happened because 1.2.2 has been released after 1.3.1, but it's still the wrong version to recommend to 1.3 users via console link.

**Comment by mfojtik** [comment]
@jwforres FYI

**Comment by smarterclayton** [comment]
Unfortunately GitHub doesn't give us a way to fix this.  Only an alternate URL on a link shortener site could do it.

**Comment by smarterclayton** [comment]
@fabianofranz basically we can't use the GitHub latest link.

**Comment by fabianofranz** [comment]
Right, basically GitHub points `/latest` to the latest release by date that is not marked as a pre-release. I'm afraid not even the [releases API](https://developer.github.com/v3/repos/releases/) provides a clean way to change that.
