### ISSUE TITLE
oc cluster up dns will not work OOTB on firewalld-enabled fedora

### ISSUE THREAD

**Issue by maci0** [openshift/origin#11949]
The internal service name resolution fails when using a cluster set up by
`oc cluster up` on a F25 system which is firewqalld-enabled

Happens with both origin 1.3.1 and OCP 3.1.3

If I stop firewalld and restart docker and recreate the oc cluster it will work fine.

**Comment by csrwng** [comment]
Instructions have now been added to the doc for the rules you need for cluster up.
(step 3 here: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux)

In addition, now cluster up performs a check on startup to see if this access is not allowed.
