### ISSUE TITLE
oc cluster up with metrics fails with ERR_SSL_SERVER_CERT_BAD_FORMAT

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#11943]
When trying to access the metrics status page, it will fail with ERR_SSL_SERVER_CERT_BAD_FORMAT.

There is no option to by pass this bad certificate in Chrome, but it is possible to by pass it in Firefox. 

##### Version
v1.4.0-alpha.1

##### Steps To Reproduce
1. `oc cluster up --metrics`
2. the output of the above will tell you where the metrics endpoint is available at (The metrics service is available at:....). Visiting this page in Chrome will not allow you to continue.

##### Current Result
Unable to access metrics when using chrome:

"This site can’t provide a secure connection
metrics-openshift-infra.10.15.17.108.xip.io doesn't adhere to security standards.
ERR_SSL_SERVER_CERT_BAD_FORMAT"

##### Expected Result
Being able to access metrics.

##### Additional Information
Installing OpenShift manually with metrics does not have this problem.
It appears that Firefox allows an option to by pass the bad certificate.

**Comment by csrwng** [comment]
This is likely due to cluster up not clearing the config/certs directory when starting up again. Same as in https://github.com/openshift/origin/issues/11651

**Comment by csrwng** [comment]
Should no longer be an issue with the latest cluster up
