### ISSUE TITLE
Enable the Kubernetes Garbage Collection controller

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#11951]
* need to make the API prefix configurable upstream (/oapi)
* it won't work right since all of our resources are duplicated
* need to carry a patch with lists of "don't delete this"
* in kube 1.5 GC will be enabled by default

**Comment by deads2k** [comment]
This is used by some controllers upstream.  Not enabling this will result in inconsistent behavior upstream and downstream.

**Comment by kargakis** [comment]
cc: @mfojtik

**Comment by kargakis** [comment]
> This is used by some controllers upstream. Not enabling this will result in inconsistent behavior upstream and downstream.

I think the intention is to have controllers set owner references independent of enabled GC. Not sure that's the case currently with RC / RS.

**Comment by mfojtik** [comment]
@deads2k I guess we will have to add special service account for generic GC controller (and not recycle the existing 'gc' SA).

**Comment by deads2k** [comment]
> @deads2k I guess we will have to add special service account for generic GC controller (and not recycle the existing 'gc' SA).

correct.

**Comment by mfojtik** [comment]
@ncdc updated description from what I learned from @deads2k, please add any other concerns there to make this more fun ;-)

**Comment by soltysh** [comment]
After talking to @deads2k I'm moving this to 1.6 milestone, since there's nothing we can do about atm. We're waiting for upstream changes.

**Comment by liggitt** [comment]
@deads2k this is enabled now, right?

**Comment by ncdc** [comment]
Yes
