### ISSUE TITLE
remove OriginalSourceURLAnnotationKey logic

### ISSUE THREAD

**Issue by bparees** [openshift/origin#11969]
Once we are building our builder images based on rhel7.3 and an equivalent centos version, we will no longer need the logic associated with the "OriginalSourceURLAnnotationKey" annotation, which exists to deal with long git tokens that the underlying http libraries didn't support prior to 7.3.

So when we get to that point, we should remove the associated logic.

**Comment by bparees** [comment]
relevant code:
https://github.com/openshift/origin/blob/master/pkg/build/builder/cmd/scmauth/password.go#L103
https://github.com/openshift/origin/blob/master/pkg/build/builder/cmd/builder.go#L127
https://github.com/openshift/origin/blob/master/pkg/build/builder/common.go#L23

**Comment by csrwng** [comment]
Fixed with https://github.com/openshift/origin/pull/13560
