### ISSUE TITLE
Proposal: Increase "created time" precision (show hours + mins) in CLI and Web Console

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#11967]
Related Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1232251

Right now, the web-console and CLI show the created time for a resource with an hour difference:
```
Name:		nodejs-ex
Created:	2 hours ago
Labels:		app=nodejs,deploymentconfig=nodejs-ex,generatedby=OpenShiftWebConsole,name=nodejs-ex
Latest Version:	2
...
```
*Web-console*

![web-console](https://bugzilla.redhat.com/attachment.cgi?id=1039392)

It would be ideal to (rather than just fix this hour discrepancy) display hours + minutes in the "created time" of resources

cc @jwforres @spadgett @fabianofranz @deads2k

**Comment by spadgett** [comment]
What would we show after days have elapsed?

**Comment by juanvallejo** [comment]
@spadgett hm, would it be feasible to display `<days> + <hours> + <minutes>` as each becomes `> 0`? We could probably stop at days even after years pass.

**Comment by spadgett** [comment]
I guess I'm not convinced the different between "4 hours ago" and "4 hours 23 minutes ago" is that meaningful most of the time. I think I prefer the former (current behavior).

Do we let users hover and see the exact time using a `title` attribute?

**Comment by jwforres** [comment]
On Fri, Nov 18, 2016 at 4:19 PM, Sam Padgett <notifications@github.com>
wrote:

> I guess I'm not convinced the different between "4 hours ago" and "4 hours
> 23 minutes ago" is that meaningful most of the time. I think I prefer the
> former (current behavior).
>

And I agree. Its humanized relative time, its intentionally not precise and
its consistent with the precision the CLI is using.  I don't see us
changing the behavior.


> Do we let users hover and see the exact time using a title attribute?
>

Yes we do, its part of the relative-timestamp directive

**Comment by jwforres** [comment]
I'm leaning in the direction of declaring that bugzilla as WONTFIX, I don't
see us changing the library we use for dates on the console or on the CLI.
  @fabianofranz opinion?

**Comment by jwforres** [comment]
Although looking back at the bug history we had said the CLI was doing the
wrong thing.  Any CLI folks know how bad it would be for us to fix the
CLI's behavior?

**Comment by juanvallejo** [comment]
@jwforres 
> Although looking back at the bug history we had said the CLI was doing the
wrong thing.  Any CLI folks know how bad it would be for us to fix the
CLI's behavior?

It gets cast to an `int` [here](https://github.com/docker/go-units/blob/master/duration.go#L13). I think the fix might just be adding `1` to [these return values](https://github.com/docker/go-units/blob/master/duration.go#L21-L33) and make an upstream PR to docker. cc @fabianofranz

**Comment by fabianofranz** [comment]
When converting a `float` to `int` in Go, the fraction part just gets blindly discarded. 

@juanvallejo I'm + 1 to submit a fix to Docker's [go-units](https://github.com/docker/go-units) but I'd suggest to fix it by doing proper rounding (which I believe is how moment.js does it, might be worth to check). Since Go's `math` doesn't provide rounding, one popular trick is to add `0.5` and then cast to `int`, examples in https://play.golang.org/p/TK-hjJFEX0.

**Comment by jwforres** [comment]
moment.js shows relative time in minutes until after 45 mins, then it
switches to rounding for hours

**Comment by juanvallejo** [comment]
@fabianofranz +1 to adding `0.5` before casting to `int`, would we also want to round for hours after 45 mins to be fully consistent with `moment.js`? Could be something like:
```
else if minutes < 46 {
	return fmt.Sprintf("%d minutes", minutes)
} else if hours := int(d.Hours()); hours <= 1 {
	return "About an hour"
}
```

**Comment by fabianofranz** [comment]
@juanvallejo definitely works for me, we just have to check how well that will be accepted there. Do you want me to take care of this (I have a Docker dev env already)?

**Comment by juanvallejo** [comment]
@fabianofranz 
> definitely works for me, we just have to check how well that will be accepted there. Do you want me to take care of this (I have a Docker dev env already)?

Sounds good, thanks!

**Comment by fabianofranz** [comment]
Docker PR in https://github.com/docker/go-units/pull/22
