### ISSUE TITLE
Don't Use `jq` in test-cmd Tests

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#11977]
In order to reduce indirection and complexity in the tests and to get rid of the runtime dependency, we shouldn't use `os::cmd` to test the output of `jq` testing the output of `oc get`. Instead of writing a complex test using `jq`, we should just enumerate the conditions we want to test for using `os::cmd`.

See https://github.com/openshift/origin/commit/beb7d4c57e1995bb00920f1191a0edf898861262#commitcomment-19902464

**Comment by mfojtik** [comment]
@stevekuznetsov or use `--jsonpath` ?

**Comment by stevekuznetsov** [comment]
@mfojtik yes, if possible, use `jsonpath` over Go templates.

**Comment by stevekuznetsov** [comment]
Mostly fixed these days 
/close
