### ISSUE TITLE
Add "Copy to Clipboard" to the "Command Line Tools" page

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#11975]
On the "Command Line Tools" there is a CLI command to show the user how he can login to OpenShift using the current session token:

```
oc login https://my.openshift.com --token=P0YVx5Sr0TRn8FEl9F11FhMYSsbcEw14E0qDnZET9Bc
```
Every single user has to click on that, select it and copy to clipboard. There should be a "Copy to Clipboard" button near that command to make it easier to do just that.

**Comment by spadgett** [comment]
Already working on it :)

https://github.com/openshift/origin-web-console/pull/871#issuecomment-261651599
