### ISSUE TITLE
sti-builder binary needs a version

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#1198]
The 'sti-builder' binary we use to trigger the STI builds should have `--version` option (or it should be printed into build log. This helps with investigating issues caused by outdated images, etc. Also it will improve the bug reporting as we will know from what STI version the builder is based from.

**Comment by mfojtik** [comment]
@soltysh @bparees FYI

**Comment by soltysh** [comment]
:+1:

**Comment by kargakis** [comment]
Should I incorporate this into my [pr](https://github.com/openshift/origin/pull/1199) about osc version?

**Comment by bparees** [comment]
@kargakis sure.

**Comment by kargakis** [comment]
I guess this can close now.
