### ISSUE TITLE
oc cluster up should accept cloud provider and cloud config environmental variables

### ISSUE THREAD

**Issue by rootfs** [openshift/origin#11998]
[provide a description of the issue]

Based on the description [this AWS config](https://docs.openshift.com/container-platform/3.3/install_config/configuring_aws.html)
there is no document on how to provide cloud provider and config during oc cluster up. Even after modifying master and node configs and restart the cluster, there are still other config mismatched to resolve.

##### Version
[provide output of the `openshift version` or `oc version` command]
3.4
##### Steps To Reproduce
1. oc cluster up
2. modify master and node config
3. run oc cluster up --use-existing-config=true

##### Current Result
after step 3, there are other config mismatches, mostly related to networkconfig.
##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by liggitt** [comment]
expanding `oc cluster up` to include cloud provider configuration is a big step... not sure that's in scope for that command

**Comment by rootfs** [comment]
If we cannot get there easily, we'd better have a doc helping how to do it manually.

**Comment by pweil-** [comment]
oc cluster up is meant to run a local cluster.  For other installation methods I would refer to the existing documentation.
