### ISSUE TITLE
Cannot get skydns record in etcd

### ISSUE THREAD

**Issue by JaysonQY** [openshift/origin#12002]
[Cannot get skydns record when i query etcd]

##### Version
[v1.3]

##### Steps To Reproduce
1. [`etcdctl --endpoints=https://10.10.10.10:4001 --cert-file=/etc/origin/master/master.etcd-client.crt --key-file=/etc/origin/master/master.etcd-client.key --ca-file=/etc/origin/master/ca.crt ls /skydns` . The above command get nothing.]

##### Current Result
No skydns record in etcd ,where are they
##### Expected Result
I want to manually add some extra record to skydns.

**Comment by liggitt** [comment]
openshift doesn't persist skydns records in etcd, it builds them dynamically from services/endpoints

**Comment by liggitt** [comment]
see implementation in https://github.com/openshift/origin/blob/master/pkg/dns/
