### ISSUE TITLE
New app from template shows images multiple times

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#12006]
When creating a new app from a template through the web ui the list of images used in the template shows the same images multiple times if the same image is used in multiple build configs. For example using this template:
https://github.com/jbossdemocentral/coolstore-microservice/blob/demo-1/openshift-templates/coolstore-template.yaml

<img width="702" alt="template" src="https://cloud.githubusercontent.com/assets/1174934/20563947/0c1ead94-b18b-11e6-9e23-aa957ddeec4d.png">

##### Version
OpenShift Master:
v3.3.1.3
Kubernetes Master:
v1.3.0+52492b4

**Comment by jwforres** [comment]
@siamaksade please open web console issues in the origin-web-console repo in the future https://github.com/openshift/origin-web-console/issues
