### ISSUE TITLE
Double quotes in help for `openshift start --images`

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1200]
```
# openshift start -h
[...]
      --images="openshift/origin-${component}:${version}": When fetching images used by the cluster for important components, use this format on both master and nodes. The latest release will be used by default.
```

Double quotes here under bash or similar shell would result in shell expansion of ${component} and ${version} (probably to the empty string) rather than passing them as part of the images template string as desired. Under most shells we would expect single quotes to be appropriate.

The double quotes are cobra defaults. Recording the ensuing conversation:

-----
> https://github.com/spf13/pflag/blob/master/flag.go#L280
> 
> Options are 1) to patch FlagUsages() in Cobra, 2) do a simple replace s/"/' in our template where we call FlagUsages() or 3) simply not use FlagUsages() and implement our own function to print flags in the templates.
> 
> Preferences?
> 
> Fabiano Franz
-----

-----
> Implement our own, I think.  We shouldn't be patching things in cobra that wouldn't get fixed, and I'm not sure cobra would accept that patch.  However, it doesn't hurt to propose the change.
> (Clayon Coleman)
-----

**Comment by fabianofranz** [comment]
Fixed in https://github.com/openshift/origin/pull/1503
