### ISSUE TITLE
oc start-build race condition

### ISSUE THREAD

**Issue by bparees** [openshift/origin#12010]
It looks like we have a race condition in which the buildconfig gets modified by something(?) between when we grab it and when we attempt to update it(probably to set the sequence id?) as part of a start-build execution.  I didn't look at @oatmealraisin's recent changes for handling build sequence collisions, any chance those changes introduced this failure mode?  /cc @csrwng 

from https://ci.openshift.redhat.com/jenkins/job/origin_extended_build_tests/853/consoleFull#5996965456cbb9a5e4b02b88ae8c2f77

```
Nov 23 04:06:08.317: INFO: Running 'oc start-build --config=/tmp/extended-test-jenkins-pipeline-z0kik-rht79-user.kubeconfig --namespace=extended-test-jenkins-pipeline-z0kik-rht79 sample-pipeline -o=name'
Nov 23 04:06:09.225: INFO: Error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc [oc start-build --config=/tmp/extended-test-jenkins-pipeline-z0kik-rht79-user.kubeconfig --namespace=extended-test-jenkins-pipeline-z0kik-rht79 sample-pipeline -o=name] []    Error from server: Operation cannot be fulfilled on buildconfigs "sample-pipeline": the object has been modified; please apply your changes to the latest version and try again
 [] <nil> 0xc8212d34a0 exit status 1 <nil> true [0xc820c88700 0xc820c88730 0xc820c88740] [0xc820c88700 0xc820c88730 0xc820c88740] [0xc820c88708 0xc820c88728 0xc820c88738] [0xb18c80 0xb18de0 0xb18de0] 0xc8211b3320}:
StdOut>

StdErr>
Error from server: Operation cannot be fulfilled on buildconfigs "sample-pipeline": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by bparees** [comment]
(note that i thought maybe this was a race between a configchange triggered build, and the start-build triggered one, but the buildconfig in question has no triggers associated.  so i'm not even sure what else is updated the buildconfig.  perhaps the sync plugin updating it for some other reason?)

**Comment by oatmealraisin** [comment]
@bparees I don't think it could be my change, I just added a log :P 

The log is 404 now, would there be any way to replicate this? Should this bug just be closed?

**Comment by bparees** [comment]
yeah we can close it pending someone else hitting it.
