### ISSUE TITLE
oc cluster up fails when /var/lib/origin is symlink to other directory

### ISSUE THREAD

**Issue by praveenkumar** [openshift/origin#12029]
If we have /var/lib/origin symlink to some other directory then oc cluster up fails.
```
# ls -l /var/lib/ | grep origin
lrwxrwxrwx  1 root root      25 Nov 25 04:20 origin -> /tmp/origin/
```

##### Version
```
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. On your host create `/var/lib/origin` as symlink to other directory before `oc cluster up`

```
ln -s /tmp/origin/ /var/lib/origin
```

2. After that run `oc cluster up`

##### Current Result

```
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.3.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... FAIL
   Error: cannot create host volumes directory
   Caused By:
     Error: Docker run error rc=1
     Details:
       Image: openshift/origin:v1.3.1
       Entrypoint: [/bin/bash]
       Command: [-c for dir in /rootfs/var/lib/origin/openshift.local.config /rootfs/var/lib/origin/openshift.local.volumes; do if [ ! -d "${dir}" ]; then mkdir -p "${dir}"; fi; done]
       Error Output:
         mkdir: cannot create directory '/rootfs/var/lib/origin': File exists
         mkdir: cannot create directory '/rootfs/var/lib/origin': File exists
```

##### Expected Result

It should detect symlink and create required file to symlinked directory.

**Comment by csrwng** [comment]
A workaround would be to specify alternate directories with `--host-data-dir`, `--host-config-dir`, and `--host-volumes-dir`

**Comment by praveenkumar** [comment]
@csrwng agree on workaround but I think we should honor symlinks also because most of time folks use it.

**Comment by csrwng** [comment]
@praveenkumar @gbraad how critical is a fix for this issue? A fix is not trivial, given that the directories that actually get mounted to the container would need to be pre-resolved before starting containers. 

If it's not critical, I'm inclined to close it.

**Comment by praveenkumar** [comment]
@csrwng please go ahead and close it because we also now using bind mounts not symlinks.
