### ISSUE TITLE
Incorrect CHECKSUM content on releases

### ISSUE THREAD

**Issue by hferentschik** [openshift/origin#12025]
The CHECKSUM files hosted as part of the release don't contain the right filenames. For example [v.1.3.1](https://github.com/openshift/origin/releases/tag/v1.3.1):

The CHECKSUM file contains this line for OS X oc:

    3c941f0634566142784503e0b06c9c733bc1fda75b7b8cffb71f688b4f400d03  openshift-origin-client-tools-v1.3.1-dad658de7465ba8a234a4fb40b5b446a45a4cee1-mac.zip

The actual file name of the zip is, however, _openshift-origin-client-tools-v1.3.1-2748423-mac.zip_.
Note, that the displayed checksums on the download page seem correct.

When it comes to [v1.4.0-rc1](https://github.com/openshift/origin/releases/tag/v1.4.0-rc1) all checksums are wrong. The ones displayed and the ones in the CHECKSUM file. The filenames are of the form _openshift-origin-client-tools-v1.4.0-rc1.b4e0954-linux-32bit.tar.gz_, whereas the filenames as part of the checksum information is _a8dae6c6bac14fa93270ef  openshift-origin-client-tools-v1.4.0-rc1+b4e0954-linux-32bit.tar.gz_. Note, the '+' instead of '.' in the checksum filename. 

I am trying to download and verify release artifacts, but verification fails, since the filenames don't match.

**Comment by stevekuznetsov** [comment]
@smarterclayton can update the releases (?) to be correct. I'll take a look at automating this step better.

**Comment by hferentschik** [comment]
Thanks. It would be great if the releases could be updated.

**Comment by smarterclayton** [comment]
Updated, I think I got them.

**Comment by smarterclayton** [comment]
Reopen if not.

**Comment by hferentschik** [comment]
> Updated, I think I got them.

Jupp, seems to work. Thanks.

**Comment by hferentschik** [comment]
@smarterclayton actually, can we re-open this. It seems the checksum for the OS X oc binary is still wrong - https://github.com/openshift/origin/releases/tag/v1.3.1

The displayed CHECKSUM on the site looks ok, but if you download the file the OS X binary is listed as 

    3c941f0634566142784503e0b06c9c733bc1fda75b7b8cffb71f688b4f400d03  openshift-origin-client-tools-v1.3.1-dad658de7465ba8a234a4fb40b5b446a45a4cee1-mac.zip

Is this some sort of caching issue?

**Comment by smarterclayton** [comment]
Maybe, will look.

**Comment by jimmidyson** [comment]
I've reopened - the CHECKSUM file downloaded has the wrong file name. I've seen this intermittently with previous releases so wonder if there is something wrong with the release scripts?

**Comment by smarterclayton** [comment]
Yes - should be easy to fix though if someone can take a look - make release will generate it based out of code in hack/common.sh (just a mismatch between the new archive name and the internal git field)

**Comment by smarterclayton** [comment]
Fixed now
