### ISSUE TITLE
 Сhanging router's timeout does not work

### ISSUE THREAD

**Issue by alenavorozhbieva** [openshift/origin#12022]
##### Version
OpenShift Master: v1.2.1
Kubernetes Master: v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. Change env in router deploymentconfig
ROUTER_DEFAULT_CLIENT_TIMEOUT 10s
ROUTER_DEFAULT_CONNECT_TIMEOUT 10s
ROUTER_DEFAULT_SERVER_TIMEOUT 10s
2. Execute any http request to any route which lasts more than 10 seconds 

##### Current Result
The request is successeful
##### Expected Result
Response code: 504
Response message: Gateway Time-out

##### Additional Information
I tried use haproxy.router.openshift.io/timeout annotation on concrete route. It's not working too

**Comment by knobunc** [comment]
@JacobTanenbaum PTAL

**Comment by alenavorozhbieva** [comment]
Any updates ?

**Comment by knobunc** [comment]
@JacobTanenbaum tells me the timeout changes were added to Origin 1.3, but you are running an earlier version.
