### ISSUE TITLE
Pods stucked in Terminating state indefinitely

### ISSUE THREAD

**Issue by ingvagabund** [openshift/origin#12039]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]
https://github.com/openshift/ose/releases/tag/v3.4.0.28

##### Steps To Reproduce
Create 100s of projects ( with 100 pods per project ) and delete delete them ( oc delete project $project ). See https://bugzilla.redhat.com/show_bug.cgi?id=1397356 

##### Current Result
Some pods are hang in `Terminating` state indefinitely

##### Expected Result
All pods are removed and there is no pod in `Terminating` state

##### Additional Information
Debugging clusterprojecta9/hellopods86 pod. `Apiserver` thinks the pod does not exist cause the ``BeforeDelete`` of pod storage delete strategy returns the pod is already deleted (`gracefulPending` set to true). Thus the pod is not deleted and the `Kubelet` does not receive delete event. Since the delete event is not received, the `Kubelet` still tries to delete the pod from the `Apiserver`.

So far could not figure out what path leads to setting pod's `deletionTimestamp` and `deletionGracePeriodSeconds` fields the way the `Apiserver` consider the pod to be deleted.

**Comment by ingvagabund** [comment]
When reproducing use log level 6. It will provide logs about pod storage registry updates.

**Comment by derekwaynecarr** [comment]
After further analysis, there was a bug in API server that prevented resources in this state from ever being deleted.  Bumped to p0 to reflect the priority due to no ability to purge the resource from storage.
