### ISSUE TITLE
ipfailover fails and vip can't work

### ISSUE THREAD

**Issue by yanghaichao12** [openshift/origin#12034]
when run "oadm ipfailover...",the vip can not be added on NIC
node1：10.47.171.45
node2：10.47.171.49
VIP：10.47.171.59
pod:  10.1.1.2(hostport:32768,containerport:22）
vrrp_script:
![image](https://cloud.githubusercontent.com/assets/20693362/20637158/9a4b580e-b3b8-11e6-8195-19022069e8cf.png)
iptables nat:
![image](https://cloud.githubusercontent.com/assets/20693362/20637165/d0239018-b3b8-11e6-997c-52bf5201f52d.png)
when i ping 10.1.1.2,that can not reach
![image](https://cloud.githubusercontent.com/assets/20693362/20637171/18610c0c-b3b9-11e6-93d3-556cdfc1e9dd.png)
so i capture pkg on vNIC tun0:
![image](https://cloud.githubusercontent.com/assets/20693362/20637176/3f2cc240-b3b9-11e6-9d83-81abda07878b.png)
![image](https://cloud.githubusercontent.com/assets/20693362/20637180/5c7b9164-b3b9-11e6-9d2f-385367adb8b6.png)
and below is flow table:
![image](https://cloud.githubusercontent.com/assets/20693362/20637190/aef140b0-b3b9-11e6-95e5-4889e18ff072.png)
there is no entry for 10.47.171.45,so i reckon that's why ipfailover doesn't work.
i down the "lo" and ping 10.1.1.2, now it can be reached.then i make "lo" up,"ipfailover" work well and i can access the vip "10.47.171.59".
so,is there some bug about this fuction ?

**Comment by knobunc** [comment]
What does the 'oc logs' show for the ipfailover pod?  Is your service reachable on 10.47.171.45 port 32768?  Can you get me the service definition please?  The flows don't matter since it is on the node address.

**Comment by knobunc** [comment]
@pecameron including you since you have more operational expertise with ipfailover.

**Comment by pecameron** [comment]
@yanghaichao12 For </dev/tcp/10.47.171.59/32768 to work the port must be open on the node. The watchport is a port that ipfailover/keepalived tracks to verify that the desired application is running. For keepalived to (possibly) service a VIP on the node the watch port, in this case 32768, must be open on the node. If it is not keepalived will report the node in  the FAULT state. Check "oc logs <ipf-pods>" on all of the ipfailover nodes to verify the state of each node. When this is running normally one node will be in MASTER state and the rest in BACKUP state. 
One way to set this up is to set the VIP as the Service externalIP and set the watchport to be the service port. The DC or RC associated with the service should be running a replica on each of the nodes that is running ipfailover.

**Comment by yanghaichao12** [comment]
@knobunc i diden't use node address
![image](https://cloud.githubusercontent.com/assets/20693362/20691984/f13dd71e-b60f-11e6-9410-276971e0dc7f.png)
and i believe port 32768 is reachable but pod ip not.
![image](https://cloud.githubusercontent.com/assets/20693362/20692026/3e2a35fe-b610-11e6-8ddc-0de8a961fcf2.png)
below are the results of 'oc logs':

![image](https://cloud.githubusercontent.com/assets/20693362/20692114/ce8f5e08-b610-11e6-8ff7-c56d07ec6c6c.png)

**Comment by yanghaichao12** [comment]
@pecameron ，the port is open
![image](https://cloud.githubusercontent.com/assets/20693362/20692233/878b1fe6-b611-11e6-9260-5ad3c60ced36.png)
i access the pod according to VIP+nodeport '32768' and i think the Service doesn't take part in the proccessing .
when i 
1.delete the chain below and 
2.ping PodIP and 
3.add the chain deleted just now.
then all is ok.
![image](https://cloud.githubusercontent.com/assets/20693362/20692593/f8233da4-b613-11e6-9fe7-274e571d6565.png)
that's the result:
![image](https://cloud.githubusercontent.com/assets/20693362/20692664/7daf92ec-b614-11e6-96ae-da2932e76dca.png)
