### ISSUE TITLE
Proposal of removing unnessacary reloads in HAProxy router

### ISSUE THREAD

**Issue by louyihua** [openshift/origin#12036]
Currently, the openshift HAProxy router deals with changes through a commit&reload way, which means everytime when a route or endpoint changes, the router is reloaded for the new configuration to take effect. This implementation is simple, but inefficient, as a pod's health state change will affect all the other inrelevant services by causing them unavailable for user during the reload period.

My proposal here is to use the CLI provided by HAProxy to remove any unnessacary router reloads. By reviewing the CLI provided by HAProxy, one can easily find that there are commands for maintaining servers and maps, which can be used by the router to avoid router reloads in many circumstances. For example, when a pod's states changes from `Ready` to `NotReady`, router can use the CLI to disable the corresponding server rather than refresh the config & reload HAProxy; and when the pod's state is back to `Ready` again, the CLI can be used to bring the corresponding server enabled. This can even be used for a route --- when a route is deleted, router just needs to delete the corresponding entry from the map frontend uses!

**Comment by knobunc** [comment]
Thank you for the suggestion.  We saw that feature in 1.6, but unfortunately we are stuck with 1.5 for the moment.  We are working to get 1.6 or 1.7 packaged so that we can use the improved features.

**Comment by DanyC97** [comment]
@knobunc what can we do to help speed up this ? Where is the packaging work and what requirements are around it?
