### ISSUE TITLE
image tags not being imported from custom image

### ISSUE THREAD

**Issue by adbaldi** [openshift/origin#12046]
Image tags set in a custom Dockerfile (e.g. LABEL io.openshift.tags="builder,php,php56,rh-php56") do not appear to be getting imported with the image when pushing a custom image to the integrated repository.
  
##### Version
# oc version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxx.xxx.xxx:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. create custom Dockerfile 
2. add LABEL io.openshift.tags="label1,label2," to Dockerfile
3. build image
4. push image to integrated openshift docker repository
5. view new image in "add to project" section of the web console 

##### Current Result
image tags are not listed on image 

##### Expected Result
image tags listed on image

**Comment by mfojtik** [comment]
@adbaldi when you `oc describe image sha256:...` that you imported, do you see the Docker Labels set?

**Comment by mfojtik** [comment]
@adbaldi additionally, can you check the tags are set in image stream tag annotations for that image? `oc get ist image:latest -o yaml`

**Comment by miminar** [comment]
@adbaldi As of now, OpenShift doesn't process these labels. You can set the labels or annotations post push. E.g.:

```
$ oc label image/sha256:cadf15583833e810b7eecd66528bb85b39e146433a3b5e71fed3d022d906df2c "io.openshift.tags=builder.php.php56.rh-php56"
```

Note that I've used dots to separate individual tags because label values must match `(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?` regexp.

You could use `oc annotate` instead (to make an annotation) which isn't so strict about the values.

**Comment by miminar** [comment]
Nevertheless, I see the processing of manifest labels and their assignment into image objects as a desirable behavior. Especially since we plan to remove the manifests from image objects completely.

I'll propose a change to image metadata filling.

@adbaldi would it satisfy your needs if we store the image labels as annotations in image objects?

**Comment by adbaldi** [comment]
@mfojtik I do see the Docker labels set when I describe the image and also in the image stream tag.  Also, I have tried adding the tags to the image stream as you pointed out but they did not change anything. I was able to apply a name to the image by modifying the image stream, but not labels.

@miminar I labeled the image as you suggested and I do see it applied to the image when i describe it.  However, it still does not seem to make a difference.  I also tried using annotate and had the same result.

Here is a little more background info on what I'm trying to do.  I made a new builder image for our users to use when building applications.  I would like this image to appear as an option in the web console (under add to project) without having to expand and dig through the section under "additional images".  

Digging through the origin documentation, it seems as though I should be able to do this by using the docker label io.openshift.tags-builder,.....  Unfortunately this does not appear to have any effect on the image (as seen by openshift).  I have also tried using the example builder image supplied by the s2i github project (https://github.com/openshift/source-to-image/tree/master/examples/nginx-app) to make sure it wasnt just my image.  The sample nginx image also does not appear to be getting labeled when I push it to the repository.  

I have also tried looking over the default images that are automatically added to openshift using the advanced installer method and it appears as though the labels come from the spec definition in the image stream as mfojtik pointed out.  I manually added the labels to the image stream spec and still did not have any luck.

At this point, I'm not sure if I'm just not understanding how the labels are supposed to be applied, or if I'm hitting some sort of bug.  Hopefully you guys can clear up my confusion.

**Comment by adbaldi** [comment]
I just managed to get this to work.  The docker label for io.openshift.tags still does not label the image stream as suggested in the documentation but I was finally able to manually label the builder image.

I believe the problem was caused by a manifest schema mismatch.  The integrated repository only stores manifest schema v1 by default.  However, the version of docker (or possible go) that I was using to push the images (Docker version: 1.10.3, go version: 1.6.3) appears to only post the v2 schema.  Which was resulting in there not being a manifest stored within the repository.  It seems as though the missing manifest might have been causing some sort of hiccup with openshift grabbing the image labels from the image stream.  

I was able to get the image labeled properly by rebuilding and pushing the image using the docker client running on an openshift node (Docker version: 1.10.3, go version: 1.6.2) and then manually editing the imagestream tags.

**Comment by bparees** [comment]
assuming the documentation being referred to is: https://docs.openshift.org/latest/creating_images/metadata.html

no implementation was ever done to use a particular image label as a source of tag metadata to be applied to the imagestream tag.  at this point it's unlikely it will be.
