### ISSUE TITLE
oAuth redirect then doesn't allow multiple query string parameters

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin#12044]
https://github.com/openshift/origin-web-console/pull/884 adds functionality that utilizes multiple query string parameters.  Unfortunately, more than one query string parameter get culled by oAuth redirection, breaking the functionality added in https://github.com/openshift/origin-web-console/pull/884 if a user is not already logged in.

**Comment by liggitt** [comment]
bug in OAuth redirect library encoding of the URL fragment during the redirect
fixed upstream in https://github.com/RangelReale/osin/pull/136

**Comment by liggitt** [comment]
fixed by https://github.com/openshift/origin-web-console/issues/943
