### ISSUE TITLE
dotnet language detection

### ISSUE THREAD

**Issue by tmds** [openshift/origin#12074]
The new app guide describes automatic language detection: https://docs.openshift.com/online/dev_guide/new_app.html. For .NET Core this is currently done based on the existence of a project.json file.

A .NET Core application targeting version 1.0 does not run 1.1 and vice versa. So if OpenShift picks an image that doesn't match the version used by the application, the app won't build and run.

There are a few options:
- No longer support automatic language detection for .NET Core
- Make OpenShift smarter and let it peek in the project.json file to figure out what version of the image it should use (Microsoft.NETCore.App dependency)

.NET Core supports installing multiple versions side-by-side. So it is possible to create an image that can run both 1.0 and 1.1, but that image would only get fatter over time.

CC @bparees

**Comment by bparees** [comment]
This isn't really a unique problem to .NET, there are many images for which we support multiple language versions and they may not all be forward/backward compatible.  

New-app's logic is going to pick the "latest" imagestreamtag for a given language match, barring any other information from the user.  If that match isn't appropriate, the user will have to explicitly indicate the image they want to match, but trying to get new-app to understand all the versions of language frameworks and align that to what imagestreamtags are available(via some naming convention that allows new-app to understand 1) the version of the application and 2) the version the image supports) sounds difficult to maintain.

At the end of the day, new-app's automatic detection is a best guess and not a guarantee.

**Comment by tmds** [comment]
For .NET Core, x.y releases are nor forward, nor backward compatible. The latest release has a higher chance of being a 'Current' (i.e. short term support) than an LTS release. So chances of the language detection working are less than 1/N (N = number of supported .NET Core x.y releases).
If the second option seems to difficult to maintain, consider the first option.
