### ISSUE TITLE
docs/cli.md: drop support for passing comma-separated parameters

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#12076]
https://github.com/openshift/origin/blob/master/docs/cli.md should be updated because now it says that `-e` and `-p` accepts comma-separated parameters. Probably, the same applies for `-l` option but I'm not sure.

Related to https://github.com/openshift/origin/pull/11539

CC @bparees @mmilata

**Comment by kargakis** [comment]
We should probably move this in openshift-docs.

**Comment by mmilata** [comment]
@php-coder good catch!

**Comment by php-coder** [comment]
>Probably, the same applies for -l option but I'm not sure.

@mmilata Is it true or not?

**Comment by mmilata** [comment]
Looks to me that `-l` still accepts comma-separated assignments.
