### ISSUE TITLE
failed to "StartContainer" for "init" with CrashLoopBackOff

### ISSUE THREAD

**Issue by J0hnson** [openshift/origin#12084]
[root@master1 tmp]# oc version
**oc v1.3.1**
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://lb.paastest.cn:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4

[root@master1 tmp]# docker version
Client:
 Version:         **1.10.3**
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64

##### Steps To Reproduce
1. Download fabric8 0.4.112
2. Install fabric8 in openshift
gofabric8-linux-amd64 deploy -y --namespace=fabric8 --domain=paastest.cn --app=cd-pipeline
3.All services/pods can work fine except jenkins .
##### Current Result
The logs:

, **failed to "StartContainer" for "init" with CrashLoopBackOff**: "Back-off 40s restarting failed container=init pod=jenkins-1-kh8n7_fabric8(4818378b-b792-11e6-be46-00248cfcb938)"
]
  10m   10m     1       {kubelet master3.paastest.cn}   spec.initContainers{init}       Normal  Created         Created container with docker id 63c11535bdb7
  10m   10m     1       {kubelet master3.paastest.cn}   spec.initContainers{init}       Normal  Started         Started container with docker id 63c11535bdb7
  10m   8m      8       {kubelet master3.paastest.cn}                                   Warning FailedSync      Error syncing pod, skipping: [failed to "InitContainer" for "init" with RunInitContainerError: "init container \"init\" exited with 1"
, failed to "StartContainer" for "init" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=init pod=jenkins-1-kh8n7_fabric8(4818378b-b792-11e6-be46-00248cfcb938)"
]
##### Expected Result

Can anyone give some advice to troubleshoot?
Appreciate.

**Comment by pweil-** [comment]
@J0hnson please take a look at `oc get events` in the fabric8 namespace and `oc logs` for the pod in question.  They may provide you with information on why the pod is failing.

**Comment by J0hnson** [comment]
@pweil-  Thanks for your advice.
Actually, i have done something just like you recommended. Using oc describe pod jenkins-XXX.
No matter using oc get events or oc logs,the error message is the following,nothing else.

Error syncing pod, skipping: [failed to "InitContainer" for "init" with RunInitContainerError: "init container "init" exited with 1"

**Comment by pweil-** [comment]
thanks @J0hnson.  What is the init container doing?  I would suggest trying to see if you have failed containers on the node it was scheduled (`docker ps -a`) and see if you can inspect the logs of the failed init container.  Based on the information above it looks like the init container is started but whatever it is running is exiting abnormally which is causing the crash loop.  

@mfojtik this may be an issue for the fabric8 folks

**Comment by J0hnson** [comment]
@pweil-  Thanks, I found an error in the host in which the jenkins pod located.
Dec  5 10:03:32 master2 origin-node: E1205 10:03:32.210381   17942 docker_manager.go:2021] Error running pod "jenkins-2-ueuef_fabric(6d9b3ac8-ba8e-11e6-be46-00248cfcb938)" init container "init", restarting: &{ID:{Type:docker ID:ed1cda9ce43e3a3cb36995b55b47c2293481e6859d0b6919320a7b337036de30} Name:init State:exited CreatedAt:2016-12-05 02:02:33.090856607 +0000 UTC StartedAt:2016-12-05 02:02:34.684387429 +0000 UTC FinishedAt:2016-12-05 02:02:34.738444585 +0000 UTC ExitCode:1 Image:busybox ImageID:docker://sha256:e02e811dd08fd49e7f6032625495118e63f597eb150403d02e3238af1df240ba Hash:1699025945 RestartCount:5 Reason:Error Message:}
Dec  5 10:03:32 master2 origin-node: I1205 10:03:32.210411   17942 docker_manager.go:2288] checking backoff for container "init" in pod "jenkins-2-ueuef"
Dec  5 10:03:32 master2 origin-node: I1205 10:03:32.210502   17942 docker_manager.go:2302] Back-off 2m40s restarting failed container=init pod=jenkins-2-ueuef_fabric(6d9b3ac8-ba8e-11e6-be46-00248cfcb938)
Dec  5 10:03:32 master2 origin-node: E1205 10:03:32.210540   17942 pod_workers.go:183] Error syncing pod 6d9b3ac8-ba8e-11e6-be46-00248cfcb938, skipping: [failed to "InitContainer" for "init" with RunInitContainerError: "init container \"init\" exited with 1"
Dec  5 10:03:32 master2 origin-node: , failed to "StartContainer" for "init" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=init pod=jenkins-2-ueuef_fabric(6d9b3ac8-ba8e-11e6-be46-00248cfcb938)"

I have also posted the issue in fabric8,but no reply yet.

**Comment by mfojtik** [comment]
@J0hnson can you locate the host where the init container ran and do `docker ps -a` and locate that container which exited with 1? It seems like there is a problem in that container.

**Comment by J0hnson** [comment]
@mfojtik
Sorry late to reply.
i just get reply from fabirc8 and  it's now fixed in fabric8 platform 2.4.15

https://github.com/fabric8io/gofabric8/issues/315
