### ISSUE TITLE
Volume error in Vagrant

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#1209]
When I stop the Openshift server, nuke openshift.local.* and try to restart it again in Vagrant I get the following error:
```
F0303 12:00:03.629983   26605 node.go:108] Couldn't create kubelet volume root directory '/data/src/github.com/openshift/origin/openshift.local.volumes': mkdir /data/src/github.com/openshift/origin/openshift.local.volumes: file exists
````

**Comment by danmcp** [comment]
This doesn't seem to be an issue anymore with:

sudo systemctl stop openshift
sudo rm -rf /openshift.local.*
sudo systemctl start openshift
