### ISSUE TITLE
Carry over base container security context fields to lifecycle hook pod

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#12103]
Follow up issue for https://github.com/openshift/origin/pull/12080/files#r90483173

When creating the lifecycle hook pod we should evaluate if the security context requests need to be carried over from the base container so that the lifecycle hook pod is running under the same context as the base container pod (or as close to it as possible).

**Comment by kargakis** [comment]
@mfojtik @php-coder on your plate

**Comment by mfojtik** [comment]
@pweil- i'm not 100% sure about this is an issue. Maybe i'm wrong, but we don't allow to change the SecurityContext for the deployer Pod? IOW. there is no way I know about (again maybe I'm wrong) that you can pass this into lifecycle hooks nowadays... @kargakis do I miss something?

**Comment by pweil-** [comment]
@mfojtik this is ensuring that a lifecycle hook pod would run with the same security context that the targeted container itself runs with.  Not the deployer pod.  Does that make sense?

**Comment by mfojtik** [comment]
@pweil- so it is not copying it from the deployer pod, but rather from the deployment config replication controller template pod spec. That makes more sense, yeah.

**Comment by mfojtik** [comment]
(also mean my PR is wrong ;-)
