### ISSUE TITLE
how to figure out which ports are exposed by an image stream

### ISSUE THREAD

**Issue by tmds** [openshift/origin#12113]
When using the `oc new-app` command I'd like to set an envvar to configure the app to match the exposed ports of the image stream.

I can't figure out what `oc` command tells me what ports are exposed by an image stream.

**Comment by mfojtik** [comment]
@tmds 

```
# oc describe istag/ruby:latest -n openshift | grep Exposes
Exposes Ports:	8080/tcp
```

**Comment by tmds** [comment]
@mfojtik perfect!
