### ISSUE TITLE
Openshift origin upgrade failing

### ISSUE THREAD

**Issue by roshan-mr** [openshift/origin#12136]
[I am trying to upgrade openshift origin cluster from verson 1.2 to 1.3, but it failing due to some unexpected errors.]

##### Version after running the upgrade playbook (play failed)
[openshift v1.3.1
kubernetes v1.3.0+52492b4
etcd 2.3.0+git]

##### Steps To Reproduce
1. [cd ~/openshift-ansible]
2. [git pull https://github.com/openshift/openshift-ansible master]
3. [ansible-playbook -vvvvvvv openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_3/upgrade.yml]

##### Current Result
fatal: [10.11.10.10]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": true, 
            "dest": "/etc/origin/master/master-config.yaml", 
            "yaml_key": "admissionConfig.pluginConfig", 
            "yaml_value": "{}"
        }, 
        "module_name": "modify_yaml"
    }, 
    **"msg": "argument of type 'NoneType' is not iterable"**
}
fatal: [10.11.11.10]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": true, 
            "dest": "/etc/origin/master/master-config.yaml", 
            "yaml_key": "admissionConfig.pluginConfig", 
            "yaml_value": "{}"
        }, 
        "module_name": "modify_yaml"
    }, 
    **"msg": "argument of type 'NoneType' is not iterable"
}**
fatal: [10.11.12.10]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": true, 
            "dest": "/etc/origin/master/master-config.yaml", 
            "yaml_key": "admissionConfig.pluginConfig", 
            "yaml_value": "{}"
        }, 
        "module_name": "modify_yaml"
    }, 
    **"msg": "argument of type 'NoneType' is not iterable"**
}
        to retry, use: --limit @/home/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_3/upgrade.retry

PLAY RECAP *********************************************************************
10.11.10.10                : ok=122  changed=2    unreachable=0    failed=1   
10.11.11.10                : ok=116  changed=1    unreachable=0    failed=1   
10.11.12.10                : ok=116  changed=1    unreachable=0    failed=1   

Any help would be much appreciated.

**Comment by FilipVozar** [comment]
I had the exact same problem, my solution was to use branch 'release-1.3' from openshift-ansible repository, instead of using master (and use ansible 2.2)

**Comment by sdodson** [comment]
@abutcher Probably happening because it's a config that lacks `admissionConfig.pluginConfig` to begin with?

**Comment by abutcher** [comment]
I wasn't able to reproduce this problem with a config lacking `admissionConfig.pluginConfig` but I can see that we're setting `openshift.master.admission_plugin_config` to `{}` as the default behavior. I think I'm going to remove the defaulting of `openshift.master.admission_plugin_config` so that we can conditionally skip this upgrade step.
