### ISSUE TITLE
panic on the cli when creating from a json file

### ISSUE THREAD

**Issue by Titerote** [openshift/origin#12132]
When creating a rolebinding, or any json from the oc command line I get an exception if there is an extra , at the end of the object. It does the job, and do the binding of the service account to the existing role.

##### Version
oc v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://osmaster.mgt.tite.lan:8443
openshift v1.4.0-alpha.1+f189ede
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Create a file with this content:
        {
            "apiVersion": "v1",
            "groupNames": null,
            "kind": "RoleBinding",
            "metadata": {
                "labels": {
                    "group": "cicd",
                    "template": "cicd"
                },
                "name": "bkpadm_edit"
            },
            "roleRef": {
                "name": "edit"
            },
            "subjects": [
                {
                    "kind": "ServiceAccount",
                    "name": "bkpadm"
                }
            ]
        },
2. oc create -f filename.json

##### Current Result
tite@montaraz:~/proyectos/SnapGizmos/CICD$ oc create -f deploys/poclab/62-bkpadm-sarole.json 
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x246ad60, 0xc4200101c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/yaml.(*YAMLOrJSONDecoder).Decode(0xc420d33838, 0x2615620, 0xc4207df980, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/yaml/decoder.go:218 +0x3cc
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*StreamVisitor).Visit(0xc4209e4a00, 0xc420745140, 0xc42018e330, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:515 +0xfc
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*FileVisitor).Visit(0xc420744fc0, 0xc420745140, 0x0, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:485 +0xd9
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc4207653e0, 0x1, 0x1, 0xc42074f230, 0x1, 0xc42074f230)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:199 +0xf4
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0xc420744fe0, 0xc42074f230, 0x0, 0x2a8c14e)
        <autogenerated>:124 +0x6e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x3d69f40, 0xc420744fe0, 0xc4209e49c0, 0xc4209e4a40, 0xc420745101, 0xc4209e4a40)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:405 +0x94
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc420745040, 0xc4209e4a40, 0x18, 0x18)
        <autogenerated>:140 +0x6e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x3d69f80, 0xc420745040, 0xc4207450c0, 0x3, 0x4, 0xc420745100, 0xc420d33a01, 0xc420745100)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:313 +0xd6
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc42074f200, 0xc420745100, 0x4, 0xc41ffb2a53)
        <autogenerated>:160 +0x78
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x3d69ec0, 0xc42074f200, 0xc4209ab590, 0x7f6c6a8fc960, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:340 +0xf1
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc420765420, 0xc4209ab590, 0x4135b8, 0x50)
        <autogenerated>:155 +0x65
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc4208ea930, 0xc4209ab590, 0x7, 0x0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/resource/result.go:81 +0x4e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.RunCreate(0xc42062be60, 0xc42070e240, 0x3d66e80, 0xc420038010, 0xc4208ed860, 0x0, 0x23510c0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/create.go:160 +0x4c6
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdCreate.func1(0xc42070e240, 0xc4209fe040, 0x0, 0x2)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/create.go:69 +0x145
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc42070e240, 0xc4209d1ee0, 0x2, 0x2, 0xc42070e240, 0xc4209d1ee0)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x439
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4202fe240, 0xc420038008, 0xc420038018, 0xc4202fe240)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4202fe240, 0x2, 0xc4202fe240)
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:33 +0x165

##### Expected Result
Error from server: error when creating "deploys/poclab/62-bkpadm-sarole.json": rolebinding "bkpadm_edit" already exists

##### Additional Information
I can provide the oadm diagnostics if need it be

**Comment by mfojtik** [comment]
AFAIK JSON specification does not allow trailing comma

**Comment by mfojtik** [comment]
(but the panic is unfortunate, we should report this more nicely)

**Comment by juanvallejo** [comment]
@mfojtik opened PR here https://github.com/openshift/origin/pull/12144

**Comment by juanvallejo** [comment]
Upstream PR: https://github.com/kubernetes/kubernetes/pull/38525

**Comment by fabianofranz** [comment]
Fixed upstream in https://github.com/kubernetes/kubernetes/pull/38525, waiting for the next Kube rebase.
