### ISSUE TITLE
retryTimeout in Recreate strategy should be proportionate to TimeoutSeconds

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#12154]
https://github.com/openshift/origin/blob/6eefa2a58356dfa91f1228f59c2980c40ead7659/pkg/deploy/strategy/recreate/recreate.go#L90

Currently set to 2min

Should be `config.Spec.Strategy.RecreateParams.TimeoutSeconds - (time.Now - deployerPodStartTime)`
We can either get the pod start time by getting the pod via the api or by using the downward api once we can get the pod start time (https://github.com/kubernetes/kubernetes/issues/36813).

**Comment by mfojtik** [comment]
@kargakis i guess this is similar to lifecycle hook pods, correct?

**Comment by kargakis** [comment]
> @kargakis i guess this is similar to lifecycle hook pods, correct?

I am not following.
