### ISSUE TITLE
No update :latest version docker image (Image Streams)

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [openshift/origin#12156]
No auto deploy :latest version docker image when have update on dockerhub
No manual update  :latest version docker image when have update on dockerhub

##### Version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
oc new-app --docker-image=mongo --name mongo
--> Creating resources with label app=mongo ...
    imagestreams "mongo " created
    deploymentconfigs "mongo " created
    services "mongo " created

Have new version image on dockerhub, but I not have the opportunity update my pod/instance

##### Expected Result

automatic / manual deploy with the appearance of the image

**Comment by Evgeniy-Bondarenko** [comment]
Are there any any webhook(link or etc) for this action ?

**Comment by kargakis** [comment]
This seems like a duplicate of https://github.com/openshift/origin/issues/10981. 

There is an option with `oc tag` to schedule the import. Not sure about the interval (should be a setting in master configuration - ccing @soltysh to keep me honest.)
https://docs.openshift.org/latest/dev_guide/managing_images.html#importing-tag-and-image-metadata
Webhooks are something we want to add support for:
https://trello.com/c/NwCisNFP/727-deployments-add-webhooks-to-deployments-accept-push-events-from-dockerhub

I expect that an ImageChangeTrigger set to your DC that points to that repository alongside with a scheduled import should work for 1.3:
https://docs.openshift.org/latest/dev_guide/deployments/basic_deployment_operations.html#image-change-trigger

**Comment by soltysh** [comment]
> There is an option with oc tag to schedule the import. Not sure about the interval (should be a setting in master configuration - ccing @soltysh to keep me honest.)
> https://docs.openshift.org/latest/dev_guide/managing_images.html#importing-tag-and-image-metadata

Correct, the image will be re-fetch every x-seconds, where that is configured at a cluster level in `master-config.yaml`, see [here](https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-config-image-config) and look for option named `ScheduledImageImportMinimumIntervalSeconds`.

**Comment by Evgeniy-Bondarenko** [comment]
Fine! 
`oc import-image mongo --from=mongo:latest --confirm=true`
`oc tag --source=docker mongo:latest  default/mongo:latest  --scheduled=true`
and edit `master-config.yaml`
`ScheduledImageImportMinimumIntervalSeconds=60` 

```
#> oc describe is mongo
Name:                   mongo
Namespace:              default
Created:                42 seconds ago
Labels:                 <none>
Annotations:            openshift.io/image.dockerRepositoryCheck=2016-12-07T16:52:35Z
Docker Pull Spec:       <none>
Unique Images:          1
Tags:                   1

latest
  tagged from mongo:latest

  * mongo@sha256:d929ffc5d0871712198be82c475397e5e9c71f3d2a9fa4b304f623ad09ad204b
      36 seconds ago
```

How I can see what image is periodically updated? Or time last check?

**Comment by soltysh** [comment]
There is no user-reachable information about it, sorry. You'd have to bump master loglevels and see info there.

**Comment by smarterclayton** [comment]
The conditions on the image stream indicate the last error but we opted not to edit the image stream to include the last check time because it would cause lots of extra writes to etcd

**Comment by Evgeniy-Bondarenko** [comment]
Thanks for the explanation
