### ISSUE TITLE
Support ECDSA keys in auto service cert issuer

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#12152]
Currently keys provided ootb are RSA 2048 bit. Would it be possible to make this configurable, possibly via annotations on the service? Key type & length would be great. What do you think @deads2k?

**Comment by deads2k** [comment]
> Currently keys provided ootb are RSA 2048 bit. Would it be possible to make this configurable, possibly via annotations on the service? Key type & length would be great. What do you think @deads2k?

I'd rather be prescriptive in what we provide.  Is it unworkable for some reason?

**Comment by jimmidyson** [comment]
It's not unworkable, I've just had discussions with people on various projects in the past & different people had different requirements placed on them in their environment. But it's not something I personally need so feel free to close if it's not something you feel necessary to add.

**Comment by smarterclayton** [comment]
I do think this will come up in the future.  Is there an easy way we can simultaneously not support every variant but potentially offload some service signing cert checks?

For now I'd agree we want a really good reason to support flexibility here.
