### ISSUE TITLE
OpenShift doesn't override default kubelet behavior of leaving one container around

### ISSUE THREAD

**Issue by dcbw** [openshift/origin#12150]
https://github.com/kubernetes/kubernetes/pull/19837/commits/e070cb617ab99a204c8c4907b8db03286121ee8e seems to have changed the kube config MaxContainerCount default from 100 to -1, which leaves at least one container. The MaxContainers flag (which ends up copied to MaxContainerCount) also states -1 means "disabled".

OpenShift doesn't seem to override this default, leading to at least one container (often the infra) left.  This causes failed infra containers to never be GC-ed, and that leads to leaked IPAM leases that we had to fix with https://github.com/openshift/origin/pull/11964.

@derekwaynecarr @openshift/networking

**Comment by dcbw** [comment]
PR that changed defaults is https://github.com/kubernetes/kubernetes/pull/19837

**Comment by dcbw** [comment]
Verified that kubelet, using local-up-cluster.sh, also uses -1:

container.ContainerGCPolicy{MinAge:0, MaxPerPodContainer:1, MaxContainers:-1}

**Comment by dcbw** [comment]
So MaxPerPodContainer:1 will make Docker GC remove all but one container for each pod.  But MaxContainers:-1 means that there will always be at least one container left around for each pod, and often that's the Infra container if that container failed.  Which means IPAM won't get torn down for it.

**Comment by dcbw** [comment]
One option is to not count the Infra container towards the MaxPerPodContainers.  Is there a great reason for keeping hte infra container around?

**Comment by pweil-** [comment]
@derekwaynecarr @dcbw - this looks like a blocker to me.  Please re-prioritize if you disagree.

**Comment by eparis** [comment]
I THINK that they have a workaround on the network side. So we might be able to survive until 3.5. I'll let @dcbw and @knobunc confirm. Do we have any concerns about other CNI based network plugins here?

I'd also like to know the risks here.

**Comment by derekwaynecarr** [comment]
I will bring this up in today's SIG-NODE meeting.  I did not think the infra container was intended to count towards the MaxPerPodContainers setting.

**Comment by dcbw** [comment]
@eparis we have a workaround for openshift, and upstream has a workaround for the 'kubenet' plugin.  But all other plugins either need their own workaround, or they will potentially leak IPAM and maybe other resources since the kubelet docker runtime doesn't clean these up.

So openshift has no risk for 3.4.

**Comment by dcbw** [comment]
> I will bring this up in today's SIG-NODE meeting. I did not think the infra container was intended to count towards the MaxPerPodContainers setting.

@derekwaynecarr I can't see anything in the docker runtime that would always GC the infra container.  Perhaps you are thinking of when the docker runtime re-uses an old infra container?  If so, that's currently broken in at least two cases:

1) if the infra container is dead (eg, docker restart underneath kubelet/openshift) because SyncPod() calls killPodWithSyncResult() with ConvertPodStatusToRunningPod() which ignores dead infra containers (which haven't been GC-ed or had network teardown).

2) if a previous infra container failed setup; I see this often with `failed to "StartContainer" for "POD" with RunContainerError: "runContainer: Error response from daemon: Container command not found or does not exist."`. Then another infra gets created, and when GC/deletion-event-handling actually happens, kubelet instead matches on container name (POD) deleting the failed infra container, while leaving the actually-set-up infra container dead and not torn down.

**Comment by pweil-** [comment]
> So openshift has no risk for 3.4.

removing this from the blocker list then.  Thanks @dcbw

**Comment by dcbw** [comment]
See https://github.com/kubernetes/kubernetes/pull/37036 for an upstream fix.

**Comment by dcbw** [comment]
https://github.com/kubernetes/kubernetes/pull/37036 got merged for 1.6 so we should see it in OpenShift soon.
