### ISSUE TITLE
Exchange paths for routes with same host fails

### ISSUE THREAD

**Issue by louyihua** [openshift/origin#12166]
When two routes hold the same host and different paths, exchange their paths may fail with certain steps.

##### Version
v1.4.0-rc1+b4e0954

##### Steps To Reproduce
1. Create route A to serve www.example.com/pathA
2. Create route B to serve www.example.com/pathB
3. Modify route A to serve www.example.com/pathB
4. Modify route B to serve www.example.com/pathA

##### Current Result
Route B fails to commit and shows that the older route A forbids it.

##### Expected Result
Both route A and route B are commited.

##### Additional Information
This bug is caused by the incorrect logic in the `HandleRoute` function `unique_host.go`. Current logic may leave more than one items for the same route object in the `hostToRoute[host]` array if an older route displaces an existing path, which will then forbid other routes to serve its old serving path.
A fix to this bug is submitted in PR #12167 .

**Comment by ramr** [comment]
This is related to the order in which the routes are processed if 4 is done before 3.  And that message is correct based on the facts at that point in time - routeA holds the pathA and so routeB is not admitted.

The easiest way to check that is working is to insert a delay between steps 3 and 4. Wait for route A to update before altering route B.  I just tested this and it works for me.
