### ISSUE TITLE
LDAP Sync does not support groups of groups

### ISSUE THREAD

**Issue by mgjadoul** [openshift/origin#12168]
Using `oadm groups sync` , I get those errors:

```
Error determining usernames for LDAP group "CN=1U17-powner,OU=Groups,OU=1U17,OU=Apps,O=Airbus": the user entry (&{CN=1U17-1S05-p-ADMIN,OU=Groups,OU=1U17,OU=Apps,O=Airbus []}) does not map to a OpenShift User name with the given mapping.
Error determining usernames for LDAP group "CN=1U17-pmember,OU=Groups,OU=1U17,OU=Apps,O=Airbus": the user entry (&{CN=1U17-1v73-d-EDIT,OU=1v73,OU=1U17,OU=Apps,O=Airbus []}) does not map to a OpenShift User name with the given mapping.
Error determining usernames for LDAP group "CN=1U17-cluster-admin,OU=Groups,OU=1U17,OU=Apps,O=Airbus": the user entry (&{CN=1U17-ABC-cluster-admin,OU=ABC-admin,OU=1U17,OU=Apps,O=Airbus []}) does not map to a OpenShift User name with the given mapping.
```

Effectivelly the users mentionned are not users but other groups. We effectivelly use groups of groups.

This basically make this command useless, as to be really usefull, I shall reimplement it, or have only users in groups.

It would definitely be more usefull to correct the implementation in Openshift dirrectly. I would even provide a patch if possible...

##### Version
```
oc v3.2.1.17
kubernetes v1.2.0-36-g4a3f9c5
```

##### Steps To Reproduce
1. In Your LDAP create a group, and include nested groups 
2. `oc adm groups sync ....`

##### Current Result
```
Error determining usernames for LDAP group "CN=powner,OU=Groups,OU=1U17,OU=Apps,O=...": the user entry (&{CN=powner-1,OU=Groups,OU=1U17,OU=Apps,O=... []}) does not map to a OpenShift User name with the given mapping.
```

Normal as this is a group.

##### Expected Result

Get a group in openshift with all users including those in the nested group.

**Comment by stevekuznetsov** [comment]
If I remember correctly, today we do not support nested groups unless the group query given does the resolution in the LDAP server.

/cc @liggitt

**Comment by enj** [comment]
So something like this should work?  http://stackoverflow.com/a/6202683/3777613

**Comment by stevekuznetsov** [comment]
If using Active Directory as the LDAP server, yes, that sort of query should resolve to the correct list of users.

**Comment by mgjadoul** [comment]
Our LDAP is an AD LDS (AD for authentication and AD LDS for authorization). 
I tested with the following config: it works but it is very slow....

kind: LDAPSyncConfig
apiVersion: v1
url: ldaps://...:636
bindDN: CN=binduser,OU=Users,OU=Apps,O=acme
bindPassword: ...
insecure: false
ca: my-ldap-ca-bundle.crt
activeDirectory:
    groupsQuery:
        baseDN: OU=myapp,OU=Apps,O=acme
        scope: sub
        derefAliases: always
        timeout: 0
        filter: (objectClass=group)
        pageSize: 0
    groupUIDAttribute: dn
    groupNameAttributes: [ cn ]
    usersQuery:
        baseDN: "OU=ourcity,OU=FR,OU=Persons,O=acme"
        scope: sub
        derefAliases: never
        filter: (objectclass=inetOrgPerson)
        pageSize: 0
    userNameAttributes: [ uid ]
    groupMembershipAttributes: [ "memberof:1.2.840.113556.1.4.1941:" ]
    tolerateMemberNotFoundErrors: true
    tolerateMemberOutOfScopeErrors: false

And to confirm: the same search with memberof instead of "memberof:1.2.840.113556.1.4.1941:"  does not work but is fast.

To make it working I tested on a subtree. And with one group only. The subtree has few users (100) compared to the full ldap (>100000).
The result is that this attribute is certainly not indexed in our case. Basically it took 30 seconds to return one user out of around 100.
Therefor I think this filter is only useable to test if one particular user is in the group our not.

I am unsure I can convince my company to add this index only for me.... This LDAP is a corporate solution and has many users / applications / groups. 

Is there any other config I could test?

**Comment by stevekuznetsov** [comment]
How slow is the full sync? When we considered supporting nested groups in the past, we quickly realised doing so for server solutions other than AD would be extremely difficult. Future planning may change this, but today I'd say it's unlikely we will support nested groups as first-class concepts in the sync.

We have previously also taken the stance that LDAP group sync is an operation happening at most once or twice a day, so speed is not an issue. Are you able to come to the same conclusion for your use-case?

**Comment by liggitt** [comment]
> Basically it took 30 seconds to return one user out of around 100.

The query should be done once per group ("look up all members for group X"), not per-member. Asking the server to find flattened members should be no less efficient than traversing nested groups and querying membership via LDAP queries.

When you run with that config, syncing a single group (which contains nested groups that flatten to ~100 members), can you increase verbosity and see how many group queries are being run?

**Comment by stevekuznetsov** [comment]
> can you increase verbosity 

`oadm sync groups .... --loglevel=5` should be high enough to see everything we need.

**Comment by mgjadoul** [comment]
I will do...
But I also simple ldapsearch like this:

ldapsearch  -D "CN=Binduser,OU=Users,OU=Apps,O=Acme" -b
"OU=Mycity,OU=Persons,O=Acme" -s sub -H "ldaps://ldapname:636" -W
"(&(objectclass=inetorgperson)(*memberof*
=CN=cluster-admin-group,OU=Groups,OU=Apps,O=Acme))"

ldapsearch  -D "CN=Binduser,OU=Users,OU=Apps,O=Acme" -b
"OU=Mycity,OU=Persons,O=Acme" -s sub -H "ldaps://ldapname:636" -W
"(&(objectclass=inetorgperson)(*memberof:1.2.840.113556.1.4.1941:*
=CN=cluster-admin-group,OU=Groups,OU=Apps,O=Acme))"

The result is the same as with oadm sync groups ....

Again, my guess is that if this attribute "
*memberof:1.2.840.113556.1.4.1941:" *is not indexed, the ldap server will
have to do a full table scan and check each user. It is cleat that the
simple memberof index will not have the required information for nested
groups.

Regards,

Marc

**Comment by stevekuznetsov** [comment]
From what I understand those are computed attributes, I'm not sure they can be indexed.

Assuming in good faith that Active Directory has taken the due diligence to make the query performant, it's not obvious to me that we could implement a more performant variant of the algorithm inside of OpenShift, externally to the LDAP server. 

I'm also not sure I understand the use-case that requires "performance" from this command. What adverse effects are there if the sync takes a minute or two to run?

**Comment by mgjadoul** [comment]
More information on our use case: it is a very large company: many users,
many applications, many groups
The policy is to use AD for authentication and AD LDS for authorization.
Using AD groups is problematic as it increase the size of the TGT and other
objects.  AD groups are reserved for case where there are no other solution.

The use case  that requires "performance" is very simple:
* If you implement LDAP Sync, you necessarily do not want to run it once a
day when user can actually get its new project environment in seconds.
* If it is slow, it also certainly means (full table scan) it use a lot of
resources on the LDAP server
* I did the search on a small branch --> on the complete ldap , multiply
the time at least by 100 (I will test also to be sure)

In our case We implement this story/process:
* On request, Openshift infra team (me) will create the project for the
business/dev/project teams
* We will create a group in Ldap server and delegate management of this
group in a corporate tool.
* Project will be able to add users in their ldap group.
* The group is included in another group to let them accessing through
Apache to the Web Console (using mod_ldap).
* The group is synchronized (once an hour and on project creation) in
Openshift and I add a role to the group to let them access their project.
* The user access to Openshift Web Consle, is authenticated and created
automatically. He can immediately access its projects!

In our "augmented" schema this quite simple algorithm would be performant.
Of course the performance will depend on the depth.  But for a depth of 2
or 3 (more is a risk) I see no problem.
* We start from whitelist or in our case from an search base (ou
representing the application) with few groups.
* Read groups --> Take members from attribute "member".
* If member is a group --> do it again on each group: take members from
attribute member.
* Ignore members which are groups this time

--> You have all users (actually their dn). You can now access them to get
attributes.
NB: you could check mod_ldap_authz implementation as it does support it
very well.

There are some cases where this algorithm would be slow but I can't think
of any significant case.

Using LDAP_Sync in Openshift seems to start the search from the user, even
in an augmented active directory configuration? I can't figure out from the
documentation....

Best regards,

Marc

**Comment by stevekuznetsov** [comment]
> In our "augmented" schema this quite simple algorithm would be performant.

The concern remains -- if LDAP servers _themselves_ provide this functionality and we provide a means by which you may use it in your group sync, why should OpenShift Origin re-implement this logic? No matter the algorithm, unless we have reason to believe the LDAP server has implemented the lookup in an inefficient way, the same implementation of it by OpenShift will necessarily be as good or slower due to network latencies.

> I did the search on a small branch --> on the complete ldap , multiply the time at least by 100 (I will test also to be sure)

Is it the case that you expect every single person who has an entry in your LDAP server to need access to OpenShift? If not, I would assume adding tighter scopes to your queries would allow them to return more quickly from the LDAP server. If you do need the entirety of an enormous LDAP server to be synced with OpenShift, you must accept that large queries to that LDAP server will take time. As mentioned previously, recording the time to find one user in a group is not necessarily informative of the timing of finding all members of the group: taking the time for one member and multiplying by the N members in the group is not effective at determining the total time a sync would take, since queries are not done per-user. 

---

When you provide us with verbose client-side logs from `oadm groups sync` we may investigate performance issues on our end. If we are failing to use the caches we have set up for the sync in the `oadm` client, or we are mistakenly making too many queries to the LDAP server, we can definitely address these issues and make the sync as efficient as reasonably possible in our client. I'm not sure, though, that there is a compelling argument for re-implementing algorithms inside OpenShift generically enough to encompass the vast amount of diversity in LDAP setups, especially when the LDAP servers themselves provide this functionality.

**Comment by enj** [comment]
Docs for using nested group membership are available [here](https://docs.openshift.org/latest/install_config/syncing_groups_with_ldap.html#nested-sync).

Feel free to reopen this if you encounter any issues @mgjadoul
