### ISSUE TITLE
Logging for CLI websocket interactions is insufficient

### ISSUE THREAD

**Issue by jupierce** [openshift/origin#12173]
`oc ... loglevel=8` gives exceptional debugging information for traditional RESTful interactions with the APIServer: HTTP headers, req/resp content, status codes, cURL equivalents, etc. However, websocket based interactions are difficult to debug from logs alone because they lack this level of detail.

Excerpt from oc logs -f bc/logtest --loglevel=8:
```
I1207 09:45:14.820626   14768 round_trippers.go:296] GET https://10.13.137.186:8443/oapi/v1/namespaces/myproject/builds/logtest-1/log?follow=true
I1207 09:45:14.820635   14768 round_trippers.go:303] Request Headers:
I1207 09:45:14.820640   14768 round_trippers.go:306]     Accept: application/json, */*
I1207 09:45:14.820644   14768 round_trippers.go:306]     User-Agent: oc/v1.5.0 (linux/amd64) openshift/a76df20
I1207 09:45:14.820649   14768 round_trippers.go:306]     Authorization: Bearer EUWSopd965KvzaH2L-IFnase2OKoZYk5TX0RfY5tRXA
I1207 09:45:14.835713   14768 round_trippers.go:321] Response Status: 200 OK in 15 milliseconds
I1207 09:45:14.835738   14768 round_trippers.go:324] Response Headers:
I1207 09:45:14.835748   14768 round_trippers.go:327]     Cache-Control: no-store
I1207 09:45:14.835755   14768 round_trippers.go:327]     Content-Type: text/plain
I1207 09:45:14.835761   14768 round_trippers.go:327]     Date: Wed, 07 Dec 2016 14:45:14 GMT
```

At log level 9:
```
I1207 09:57:31.173519   16996 round_trippers.go:299] curl -k -v -XGET  -H "User-Agent: oc/v1.5.0 (linux/amd64) openshift/a76df20" -H "Authorization: Bearer EUWSopd965KvzaH2L-IFnase2OKoZYk5TX0RfY5tRXA" -H "Accept: application/json, */*" https://10.13.137.186:8443/oapi/v1/namespaces/myproject/builds/stress-1/log?follow=true
```

Issues with these listings:
- Headers missing: Connection: Upgrade, Upgrade: websocket, and others that are verb specific.
- The data returned by the server and lifecycle of the websocket are not logged. 
- The proposed curl invocation is insufficient to replicate the server interaction (lack of headers/websocket support).

Without logging information (and with the default security configuration preventing network analysis), I can only resort to the more costly process of inspecting source and building a test harness. 

##### Version
oc v1.5.0-alpha.0+a76df20-255-dirty
kubernetes v1.4.0+776c994
features: Basic-Auth

##### Steps To Reproduce
1. oc new-build https://github.com/openshift/ruby-hello-world --name=logtest
2. oc logs -f bc/logtest --loglevel=8
3. oc logs -f bc/logtest --loglevel=9

##### Current Result
Very little / misleading information about the websocket connection.

##### Expected Result
Logging commensurate with traditional RESTful interactions.

**Comment by smarterclayton** [comment]
Upstream and yes, please
