### ISSUE TITLE
Env var with comma in it doesn't work on `new-app`

### ISSUE THREAD

**Issue by kalote** [openshift/origin#12181]
When creating an app with 'oc new-app' command, i have an error:

> environment variables must be of the form key=value

my env var is a mongoDB cluster URI (mongo01:27017,mongo02:27017,mongo03:27017) and it should be working.

##### Version
oc v1.3.0-rc1
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://stuff.private:443
openshift v3.3.1.5
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Create a new nodeJS app with a connectivity to mongoDB
2. This app have 2 env: PREPROD + PROD (each with its own mongoDB)
3. MongoDB is a clustered mongoDB (so multiple instance to give as the mongo_uri)
4. Expose the env var MONGO_URI so that your pod can use it in its deployment config
5. oc new-app myapp -e MONGO_URI=mongodb://usr:pwd@mongodb-01:27017,mongodb-02:27017,mongodb-03:27017/my-db?replicaSet=rs0

##### Current Result

Doesn't work, error related to comma value ("environment variables must be of the form key=value")

##### Expected Result

Should work and add the envVar as a new one in deploymentConfig

##### Additional Information

If i input this value directly in the dc on the web console ("edit YAML"), it works. But I want to do it in command line.

**Comment by php-coder** [comment]
Related to https://github.com/openshift/origin/pull/11539
CC @bparees

**Comment by bparees** [comment]
this was fixed by the commit @php-coder referenced.

**Comment by php-coder** [comment]
@bparees This is different: now impossible to use comma in the value:
```
oc new-app myapp -e MONGO_URI=mongodb://usr:pwd@mongodb-01:27017,mongodb-02:27017,mongodb-03:27017/my-db?replicaSet=rs0
```

**Comment by bparees** [comment]
@php-coder the user was on 1.3, it wouldn't have had these changes.  the way @mmilata implemented the PR, you can use commas in the value.  @mmilata can confirm.

**Comment by bparees** [comment]
@php-coder fyi here's what you get now:
```
$ oc new-app myapp -e MONGO_URI=mongodb://usr:pwd@mongodb-01:27017,mongodb-02:27017,mongodb-03:27017/my-db?replicaSet=rs0
warning: --env no longer accepts comma-separated lists of values. "MONGO_URI=mongodb://usr:pwd@mongodb-01:27017,mongodb-02:27017,mongodb-03:27017/my-db?replicaSet=rs0" will be treated as a single key-value pair.
```

**Comment by php-coder** [comment]
@bparees Thank you for the explanation!

**Comment by kalote** [comment]
Hello,

Why did you close it ? I'm using:

OpenShift Master:
v3.3.1.5
Kubernetes Master:
v1.3.0+52492b4

And i can't upgrade my platform like that, so i don't quite see how you "fix" it ? what can i do to make this work ?

**Comment by bparees** [comment]
I closed it because the issue has been fixed and this is not something we're likely to backport to 3.3.

You can workaround the limitation by setting the env variable via "oc env" after creating the deploymentconfig, or using oc edit to manipulate the resource directly.

**Comment by kalote** [comment]
Ok thanks o/
