### ISSUE TITLE
viewing project description ignores linebreaks

### ISSUE THREAD

**Issue by djdevin** [openshift/origin#12194]
The project description field supports linebreaks, however they are not displayed on the project page. The `oc new-app` command also supports linebreaks passed in the description and they appear correctly only when editing the project.

I noticed that they are not stripped they are just not converted to HTML breaks.

![linebreaks](https://cloud.githubusercontent.com/assets/418136/21024755/a3f40820-bd53-11e6-90e7-fd37bbc87dcc.png)

##### Version
1.3.1

##### Steps To Reproduce
1. Create a new project with linebreaks in the description
2. View the projects page

##### Current Result
Everything is on the same line.

##### Expected Result
Everything should not be on the same line.

**Comment by jwforres** [comment]
@rhamilto we probably need to be careful allowing too many line-breaks, truncate-long-text allows limiting the number of line breaks
