### ISSUE TITLE
add-cluster-role-to-group don't complaint when adding a non existent group

### ISSUE THREAD

**Issue by snebel29** [openshift/origin#12206]
I notice that when running add-cluster-role-to-group you can add a non existent group to the policy bindings

##### Version
```$ oc version
oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
```

##### Steps To Reproduce
1. `oc adm policy add-cluster-role-to-group cluster-reader nonexistentgroup`
2. `oc get clusterPolicyBindings -o yaml`

##### Current Result
The non existent group gets added

##### Expected Result
An error should be raised so you can notice the issue/typo

**Comment by smarterclayton** [comment]
Allowing this to happen is intentional (so you don't have to bind in explicit order, and because some groups are virtual and only exist when accessing the system via a cert), but users should definitely get an informational message if the binding entity is not found.

**Comment by stevekuznetsov** [comment]
FYI @enj This is the current behavior for all of the `add[-cluster]-role-to-(group|user)` commands.

**Comment by enj** [comment]
/unassign

@stlaz @sttts @mfojtik
