### ISSUE TITLE
Some components are using deprecated docker/engine-api

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#12212]
A few files import packages from `github.com/docker/engine-api`, which has been [deprecated](https://github.com/docker/engine-api) and superceded by `github.com/docker/client`. Given the low number of files impacted (mainly in bootstrapping and docker build code), we should consider switching.

##### Version

origin master

* [Godeps](https://github.com/openshift/origin/blob/master/Godeps/Godeps.json#L1132)
* [Code search](https://github.com/openshift/origin/search?utf8=%E2%9C%93&q=github.com%2Fdocker%2Fengine-api)

##### Current Result

From a cursory search, excluding origin, the following files contain references to the deprecated `engine-api` package:

* pkg/bootstrap/docker/dockerhelper/helper.go
* pkg/bootstrap/docker/dockermachine/helper.go
* pkg/bootstrap/docker/up.go
* pkg/cmd/cli/cmd/dockerbuild/dockerbuild.go
* pkg/cmd/server/kubernetes/node.go

##### Expected Result

These should instead refer to the replacement packages: `github.com/docker/client` - see https://github.com/docker/docker/tree/master/client

Since the old package is deprecated, it may soon be stop receiving updates, so it's a good idea to evaluate switching over before that time comes.

**Comment by jawnsy** [comment]
This would affect #10637 and may impact the size of our resulting binaries. I don't know the priority of this problem, hopefully someone can help triage/prioritize this.

cc @csrwng

**Comment by mfojtik** [comment]
@bparees i'm getting tired switching docker clients every couple months :-) but I guess this would also affect s2i

**Comment by bparees** [comment]
maybe we just skip this move and wait for client to be deprecated before we do anything.....

**Comment by bparees** [comment]
I should note the only reason this isn't a bigger impact is we never moved off fsouza in origin.

**Comment by mfojtik** [comment]
@bparees I can see that kube still use engine-api, I think my position would be wait till they switch. I hate having 3 docker clients in origin.

**Comment by jim-minter** [comment]
https://github.com/kubernetes/kubernetes/issues/34308 is the kube issue for move from engine-api (not that anything seems to be happening on that front right now)

**Comment by mfojtik** [comment]
@jim-minter @bparees kubernetes is switching to [CRI](http://blog.kubernetes.io/2016/12/container-runtime-interface-cri-in-kubernetes.html)

**Comment by csrwng** [comment]
@mfojtik nice. @deads2k ^^ any chance of policy-based access to CRI functions? We could use that to harden builds (instead of having unlimited access to a Docker socket).

**Comment by csrwng** [comment]
Closing this issue as won't fix. The engine client is still used upstream for the Docker CRI implementation. I don't see us moving off of it any time soon.
