### ISSUE TITLE
Proposal: Multi-stage "oc cluster up" process

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#12213]
##### Background

"oc cluster up" works by pulling an origin image and running openshift via a container engine, which could be on the same system (`DOCKER_HOST=/var/run/docker.sock`) or a remote host (`DOCKER_HOST=https://1.2.3.4:5678`). Since `oc cluster up` is intended as a development and test tool, a local docker daemon is the most likely scenario, but there is support for remote daemons as well. This remote capability could be useful when running `oc` on a low-power laptop, since it allows a comparatively more powerful remote server to do most of the work (although in that case, a workaround could be to `ssh` into the target system and run `oc cluster up` from there).

##### Current Behaviour

Today, the `oc` binary contains much of the logic to bootstrap the openshift-in-container configuration. It has some [careful handling](https://github.com/openshift/origin/blob/master/pkg/bootstrap/docker/up.go#L899-L907) to ensure that things work correctly in the remote-DOCKER_HOST case: 

```go
// First, try to get the host from the DOCKER_HOST if communicating via tcp
var err error
ip := c.DockerHelper().HostIP()
if ip != "" {
	glog.V(2).Infof("Testing Docker host IP (%s)", ip)
	if err = c.OpenShiftHelper().TestIP(ip); err == nil {
		return ip, nil
	}
}
```

##### Proposed Behaviour

This proposal suggests running `oc cluster up` code in multiple stages:

Stage 1: Find the docker daemon and connect to it
Stage 2: Pull an image containing "oc cluster up" code and run on the daemon (whether local or remote)

##### Pros

* We execute a single process on the remote docker host
  * This would be Go code, so has access to libraries or execution of other processes as needed
  * May improve performance, since only one container needs to be executed (instead of one per command, e.g. running `uname` or `hostname` or small bash scripts)
* By running `oc cluster up` inside a container, the distinction between "running locally" and "running remotely" is removed, simplifying branches in the code.  The local "oc" binary would be responsible for streaming output from the "oc cluster up" command.
* The origin image is expected to be available, and getting another container image shouldn't be a big deal.

##### Cons

* This may impact development velocity for `oc cluster up` itself, since testing would require building an updated image.
* I don't know how this may impact with things like `docker machine`.

**Comment by jawnsy** [comment]
@csrwng What do you think? This thought occurred to me while working on #10786, since I wanted to be able to run some REST API calls from the target system, and doing it via remote `docker run curl` type commands seemed tedious.

**Comment by csrwng** [comment]
@jawnsy one of the things that's cool about cluster up is that you can specify a prior version of ose/origin in an image and it will bring it up for you. We would stop being able to do that if we switched to using cluster up on the container completely. There's also the part of it that needs to do some client setup, particularly if you're running on a Mac or Windows. It's nice that you can use your native oc binary to work with the OpenShift cluster.

Having said that, there's things in cluster up that I would like to not be so shell-scripty like:
https://github.com/openshift/origin/blob/master/pkg/bootstrap/docker/host/host.go#L17-L23

A counter proposal would be to leave cluster up's main path as is, in order to support starting previous versions. And, have it detect whether the origin/ocp image we're bringing up supports a new command ... let's call it 'cluster up bootstrap', that will do the type of stuff that we do through multiple container runs in the current cluster up (create dirs, test whether to use nsenter, create config, etc). What do you think?

**Comment by bparees** [comment]
> We would stop being able to do that if we switched to using cluster up on the container completely.

well, you could still do it, but the "oc cluster up" behavior you'd get would be tied to the version of openshift you were bringing up, since the "oc cluster up" container would also be versioned, right?

**Comment by bparees** [comment]
(obviously that would only work going forward since there would be no "oc cluster up" image for older versions)

**Comment by csrwng** [comment]
That's what I meant :)

**Comment by csrwng** [comment]
As we discussed, it would probably make sense to create a separate bootstrap container that can be built with the rest of origin. It would do most of the bootstrap while the oc binary on the client could do client stuff like setup the login, start socat (in the case of Docker for Mac), etc.

**Comment by smarterclayton** [comment]
How many containers do we need to start this container?

**Comment by jorgemoralespou** [comment]
Is this use case so common that we want to support it? I agree that it will be nice, but also it will complicate backwards compatibility, and that is a nicer feature to have and support.

**Comment by bparees** [comment]
if you're concerned w/ compatibility, this puts us on a better path since it will align the master server w/ the infrastructure images we're running.

**Comment by jorgemoralespou** [comment]
how? I would expect that if you specify --version aligns the master server and the infrastructure images. Only in the case of latest this could be a problem, but I would rather have --version applied to the one of the oc client if not explicitly specified.

@bparees Can you elaborate on why?

**Comment by jorgemoralespou** [comment]
I think it will complicate use cases were we will want oc cluster client to be able to configure and bootstrap the cluster, as the logic will now reside in a remote container.

**Comment by bparees** [comment]
> how? I would expect that if you specify --version aligns the master server and the infrastructure images. 

today the bootstrapping logic is not aligned w/ that master or infrastructure images, meaning the templates/etc that it tries to install (And other config it tries to do) would not be aligned.

> I think it will complicate use cases were we will want oc cluster client to be able to configure and bootstrap the cluster, as the logic will now reside in a remote container.

that doesn't sound like a use case we should be encouraging..oc cluster up is for standing up and initializing a cluster, not managing other clusters.

Anyway i don't think this is the most important feature in the world, but if we run everything else in container, why wouldn't we run the bootstrapping logic in a container that's version-aligned w/ the cluster it's bootstrapping?

**Comment by jorgemoralespou** [comment]
@bparees I also don't think that installing the templates should be part of oc cluster, to be honest. I think that oc cluster by default should be just a cluster start tool and provide mechanisms to configure that cluster with whatever you want. I would think that installing templates/etc is more what should be in minishift.

When I meant configuring the cluster I didn't meant a remote cluster, I meant the cluster that is started with the "oc cluster" command. There's already an issue requesting this feature, and I expect the minishift asking for similar soon if they haven't done already. As can be seen in the case (https://github.com/openshift/origin/issues/12266) there's a reason to provide different bootstraping for a cluster, and the only thing that should belong to oc cluster is the ability to make it easy.

Are we trying to make oc cluster more than just a tool to start a local cluster? What is in the cluster might be very different depending on what version, what capabilities, if origin or ocp, ... and so on, so I don't think it should belong here. IMHO.

But as usual, I might be wrong.

**Comment by bparees** [comment]
yeah i disagree.  oc cluster up is the single file download standalone binary that gives you a cluster that's ready for development, which means it's got imagestreams and templates installed.  And it's not a tool for managing clusters generically.

The whole point is that:

```
oc cluster up
oc new-app https://github.com/openshift/nodejs-ex
```

works.

**Comment by smarterclayton** [comment]
If we're moving into config management of the master we should pump the
brakes.  That's what ansible is for, and we are starting to stray.  There's
a lot of discussion going on about making playbooks runnable from inside
containers (and parameterized) so we can afford to be less aggressive here
and fix the problem.  Eventually we want oc cluster up --provider=gce

On Dec 15, 2016, at 10:37 PM, Ben Parees <notifications@github.com> wrote:

yeah i disagree. oc cluster up is the single file download standalone
binary that gives you a cluster that's ready for development, which means
it's got imagestreams and templates installed. And it's not a tool for
managing clusters generically.

The whole point is that:

oc cluster up
oc new-app https://github.com/openshift/nodejs-ex

works.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12213#issuecomment-267509679>,
or mute the thread

**Comment by jorgemoralespou** [comment]
Containerized and parameterizable ansible sounds good. Didn't thought on
that option.

**Comment by jorgemoralespou** [comment]
My only concern would be how big the container would be to pull it down
just to configure an allinone cluster up?

**Comment by bparees** [comment]
@jorgemoralespou are you referring to the bootstrap container?  if so, it would share the base layer with the other cluster intrastructure images, so there's very little additional that would be pulled.

**Comment by jorgemoralespou** [comment]
I was referring to configuring a cluster through an ansible container. I
would think this is too heavyweight. Bootstrap container is clear is not
and it might be a good option.

**Comment by csrwng** [comment]
Created Trello card, closing the issue
https://trello.com/c/cULNEIER/1248-multi-stage-cluster-up

**Comment by bparees** [comment]
@csrwng may have missed the close button :)
