### ISSUE TITLE
Allow a source repository to specify the S2I builder image that should be used.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#12219]
When you use ``oc new-app`` against a code repository, the automatic detection algorithm will be applied to determine what should be done.

This can result in an S2I builder being chosen for you based on the language specific files found. For example, if the source repository contains ``requirements.txt``, or ``setup,py``, then the Python S2I builder will be used. Similar for Ruby, Java etc. If no specific language was found but a ``Dockerfile`` exists, then the docker build strategy will instead be triggered.

When the source strategy is triggered for a specific language, then the ``latest`` image for that language S2I builder will always be used. There is no way to specify a specific version of the S2I builder for the language being used. Thus if a code repository contains Python code that only works with Python 2, it will fail, because the latest image is for Python 3.5.

To deal with this specific issue, but also the more general problem of how to make language detection extensible, it may be simpler to allow a code repository to contain a file such as ``.s2i/source-image``, which can be used to explicitly name the S2I builder image. This way a code repository with Python 2 code in it, could add this file and in it have ``python:2.7``.

This same mechanism could be used to resolve conflicts where language detection finds multiple things that match. For example, it is quite common with Python applications to use ``npm`` to install Javascript modules needs for front end code delivered up by the web application. The ``package.json`` file in the same code repository therefore could cause a conflict other whether should be Node.JS or Python repository, depending on order that detection algorithm checks. The use of a ``.s2i/source-image`` file could be used to override it.

Finally, since this file does implement an override of the language detection algorithm, then it would be possible to a code repository to specify a complete new S2I builder that OpenShift ``oc new-app`` command doesn't even know about. The code repository could for example list a file reference to an S2I builder such as ``ceylon/s2i-ceylon:1.3.1`` which is not part of OpenShift.

Overall, this would make it much easier for third parties to supply sample applications that could easily be deployed as a prospective user only needs to point ``oc new-app`` at the code repository and doesn't have to work out what the S2I builder is to use in ``oc new-app builder~repo`` form of the command.

**Comment by bparees** [comment]
converted to trello: https://trello.com/c/zFRttzdc
