### ISSUE TITLE
oc cluster up should import JBoss streams, at least in OCP

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#12225]
it would be good for JBoss images to work OOTB after oc cluster up, at least in OCP.

@csrwng fyi

**Comment by csrwng** [comment]
As @bparees mentioned we should likely check the openshift/library repo at build time.

**Comment by bparees** [comment]
We need to resolve licensing questions before we go installing the jboss imagestreams everywhere.

**Comment by bparees** [comment]
@csrwng or @jim-minter let's cardify and close this.

**Comment by csrwng** [comment]
https://trello.com/c/4bDQV42F/1251-cluster-up-import-jboss-streams-in-ocp
