### ISSUE TITLE
oc cluster status extensions

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#12224]
oc cluster up status should check the status of the router, registry, metrics (if applicable), logging (if applicable)

This is because all of these may continue loading after oc cluster up itself has finished.

Possibly some sort of option equivalent to --porcelain for checking via shell scripts may be appropriate.

@csrwng fyi

**Comment by csrwng** [comment]
sgtm 
What would be the output look like if you specify --porcelain ? Shouldn't we just reuse the output formatting elsewhere in the CLI ? so we can specify things like -o jsonpath='{ .router.status }'

**Comment by jorgemoralespou** [comment]
I think this feature is really nice and helpful.

**Comment by jim-minter** [comment]
@csrwng, to be clear, I'm definitely /not/ suggesting a `--porcelain` option - just (possibly) something which provides stable output for scripts - if implemented this should absolutely be in an existing OpenShift/k8s idiom...

**Comment by csrwng** [comment]
@jim-minter thx :) sorry for misunderstanding. We should do it
