### ISSUE TITLE
Increase delays when switching after deploy

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [openshift/origin#12220]
I have an application with a long running (5-10 seconds), and when attempting to update (install the next version) I have down-time of 5-10 seconds (due to the fact that the old instance is switched off too early)

How do I set startup so there was no downtime? Openshift config? Dockerfile?

##### Version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
Deploy new version applications

##### Current Result
Switching on is not until the end of the running version of the new application

##### Expected Result
add necessary timeout shutdown applications(old version) for running applications with new version

**Comment by kargakis** [comment]
Can you post the DC you are using?

**Comment by Evgeniy-Bondarenko** [comment]
@kargakis not used, only start application without mount dc
problem is not in the slow application startup
problem is in the absence of a delay when switching to the new version application.

how to increase the switching delay?
or how explain openshift engine, then the application is not yet fully run and need time(in this time need to continue to work previous version of the application)?

The main objective: to reduce down-time during deploy.

**Comment by kargakis** [comment]
You probably want to use [dc.spec](https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-deploymentconfigspec).MinReadySeconds to increase the time the deployment will wait on top of the readiness checks for new pods.

**Comment by Evgeniy-Bondarenko** [comment]
Fine!
How do I change this value (minReadySeconds) for just this pod/namespace/all-servers?
(need little instruction for clarity)

**Comment by kargakis** [comment]
You can edit or patch the DC
```
oc patch dc/NAMEHERE -p '{"spec":{"minReadySeconds":NUMHERE}}'
```
Unfortunately there is no global option to default new DCs or update old DCs so you will need to run this manually for all DCs. @smarterclayton isn't it reasonable to provide a way for admins to set global defaults for stuff?

**Comment by smarterclayton** [comment]
Probably not, if it can easily be accomplished via the API.  Applications are responsible for specifying their own parameters with regards to delays.  Expectation is that the readiness check *is* the min ready seconds (and you could just add a wait to your readiness check if you really wanted to).

**Comment by kargakis** [comment]
@Evgeniy-Bondarenko feel free to reopen if you have any more issues with this.
