### ISSUE TITLE
[RFE] Build strategy jenkinsPipelineStrategy should support "env" variables.

### ISSUE THREAD

**Issue by etsauer** [openshift/origin#12239]
I want to be able to use environment variables set at `spec.strategy.jenkinsPipelineStrategy.env` to pass parameters to my jenkinsfile.groovy code passed into the buildConfig. Currently, the `env` struct does not exists for the jenkinsPipelineStrategy as it does with all other build strategies.

If the env struct is added to the jenkinsPipeline object, support could be added to the OpenShift sync plugin for jenkins to be able to inject those env vars into a build job via the EnvInject plugin

https://github.com/jenkinsci/openshift-sync-plugin
https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin

**Comment by bparees** [comment]
exists in our trello backlog: https://trello.com/c/h6NSFQgk
