### ISSUE TITLE
egress router & local network

### ISSUE THREAD

**Issue by fgiloux** [openshift/origin#12248]
The egress router does not work when the gateway and the destination IPs are the same and more generally when the destination IP is directly accessible from the node.
The following command in the egress-router.sh script fails:
 `# ip route add ${EGRESS_DESTINATION}/32 via ${EGRESS_GATEWAY} dev macvlan0`
RTNETLINK answers: File exists
which would be ok as it is not needed but the script starts with "set -ex" which prevents the following commands to be executed and the nat table does not get populated.
I am preparing a pull request for it, just adding a test before the command should make it but I first need to setup a dev env for executing the test suite.

##### Version
I tested with:
openshift v3.3.0.34
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Create the pod with the same values for EGRESS_DESTINATION an EGRESS_GATEWAY
2. From another pod try to access a backend service at EGRESS_DESTINATION using the IP address of the router pod => fail
3. Log into the container of the egress router: # oc rsh egress-1 and check that the nat table has not been populated: # iptables -L -n -t nat => empty
 
Regards,

Frédéric

**Comment by danwinship** [comment]
fixed long ago by #12460
