### ISSUE TITLE
scale failing for replication controllers

### ISSUE THREAD

**Issue by jwendell** [openshift/origin#12247]
it seems scaling replication controllers is failing - scaling of deployment config is fine.

##### Version
oc v1.5.0-alpha.0+0e898c8-207
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://xxxxxxxxx
openshift v3.4.0.34+87d9d8d
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Have an environment with a DC (which creates a RC)
2. Run `oc scale --replicas=2 replicationcontrollers <rc-name>`
3. Notice it doesn't scale
  3.1 See the events tab of console ui. It seems it's created but deleted immediately.
4. Notice that `oc scale --replicas=2 dc <dc-name>` works fine

##### Current Result
In the events tab of console ui, I see:
`Scaled replication controller "xxx-1" from 2 to 1 `
This is weird. Also I see messages telling the container was created and it was deleted, both having the same timestamp.

##### Expected Result
It works fine just like oc scale dc

**Comment by mfojtik** [comment]
@jwendell it works this way by design I think. The RC is managed by DC. In order to scale the RC you have to scale the DC.

**Comment by jwendell** [comment]
This is not what oc scale --help says...

RC is a k8s concept. If we do it this way we would be changing behaviors, right?

Also, it used to work on OCP 3.3.

**Comment by kargakis** [comment]
@jwendell the `oc scale --help` is scoped to how oc scale works. I don't think it makes sense to include information about other components of the system -in this case the deployment controller, but you can have an arbitrary number of others (see custom controllers)- with which it may compete. You have to know beforehand that you shouldn't manage replication controllers owned by deployments in the first place.

It is noted in the docs: https://docs.openshift.org/latest/dev_guide/deployments/how_deployments_work.html#what-is-a-deployment

**Comment by jwendell** [comment]
@kargakis thanks for the explanation and the link to the doc. Now it's clear to me that we shouldn't touch RC that are managed by a DC.

However, it works for OCP versions < 3.4, that's why I thought it was a bug/regression. I believe it's a "new" behavior then?

**Comment by kargakis** [comment]
> However, it works for OCP versions < 3.4, that's why I thought it was a bug/regression. I believe it's a "new" behavior then?

What do you mean by this? You shouldn't be able to scale a RC for a DC since `oc scale` was introduced back in 1.1 (meaning the controller would "fix" your change). There have been some bugs along the releases, but generally it should work as expected (DC controller syncs the underlying RCs on every change they have).

**Comment by kargakis** [comment]
Maybe the so called regression is due to the fact that early releases (1.1 and maybe 1.2) our deployment controllers werent using informers which means that RCs would be reconciled on DC updates and when the controller would relist and not on RC updates. This was wrong behavior and should be fixed in >= 3.3.

**Comment by jwendell** [comment]
Yeah, maybe that's the reason.

I'm using the k8s rest api directly (instead of using oc scale) to increase the number of replicas of a RC. I'll use the oapi to change the DC instead.

Thanks.
