### ISSUE TITLE
How to access the last git message on container

### ISSUE THREAD

**Issue by luiscoms** [openshift/origin#12261]
I want to know the last git message inside container like `OPENSHIFT_BUILD_REFERENCE` that holds the branch name that I build.

**Comment by bparees** [comment]
you want to access that as part of your build steps, or you want openshift to include that information in the image produced by the build?

**Comment by bparees** [comment]
we already include this information in the image we build, as labels:

```
                "io.openshift.build.commit.author": "Ben Parees \u003cbparees@users.noreply.github.com\u003e",
                "io.openshift.build.commit.date": "Mon Dec 12 08:26:46 2016 -0500",
                "io.openshift.build.commit.id": "343689f74d71911bd8d1d0d0bdb5307ea65ce426",
                "io.openshift.build.commit.message": "Merge pull request #83 from guangxuli/fix_branch",
                "io.openshift.build.commit.ref": "master",
```

**Comment by luiscoms** [comment]
I am using this information on endpoint of my api to know if we already deploy the last changes

**Comment by bparees** [comment]
So given that the information is part of the image metadata (labels) already, you can look at the imagestreamimage to see the values:

```
$ oc get imagestreamtags
NAME               DOCKER REF                                                                                                 UPDATED         IMAGENAME
nodejs-ex:latest   172.30.236.128:5000/p1/nodejs-ex@sha256:fab06eccfe03936e6736dedca3ac06e7be405fdd0cd5fb9360acade0cb64bed7   3 minutes ago   sha256:fab06eccfe03936e6736dedca3ac06e7be405fdd0cd5fb9360acade0cb64bed7

$ oc get isimage nodejs-ex@sha256:fab06eccfe03936e6736dedca3ac06e7be405fdd0cd5fb9360acade0cb64bed7 -o yaml | grep commit
        io.openshift.build.commit.author: Ben Parees <bparees@users.noreply.github.com>
        io.openshift.build.commit.date: Mon Dec 12 08:26:46 2016 -0500
        io.openshift.build.commit.id: 343689f74d71911bd8d1d0d0bdb5307ea65ce426
        io.openshift.build.commit.message: 'Merge pull request #83 from guangxuli/fix_branch'
        io.openshift.build.commit.ref: master
        io.openshift.build.commit.author: Ben Parees <bparees@users.noreply.github.com>
        io.openshift.build.commit.date: Mon Dec 12 08:26:46 2016 -0500
        io.openshift.build.commit.id: 343689f74d71911bd8d1d0d0bdb5307ea65ce426
        io.openshift.build.commit.message: 'Merge pull request #83 from guangxuli/fix_branch'
        io.openshift.build.commit.ref: master
```

**Comment by luiscoms** [comment]
This information is that I want, but how can I see that inside container since it is running?

**Comment by bparees** [comment]
Inside which container?

**Comment by luiscoms** [comment]
Inside the application running container

**Comment by bparees** [comment]
We don't have a way to make that available to you currently.  I would suggest you consider using a custom assemble script that uses git to get the message (by invoking git on the local source which was cloned as part of the input to the build process) and write it to a file within the image, as part of your assembly process.

**Comment by luiscoms** [comment]
Currently this does not exists.

```
$ env | grep -i opensh                                                    
OPENSHIFT_BUILD_NAME=worker-5                                              
OPENSHIFT_BUILD_SOURCE=git@mygit.com:luiscoms/worker.git                                                                   
OPENSHIFT_BUILD_NAMESPACE=worker          
OPENSHIFT_BUILD_REFERENCE=master 
```

What the variable will contain?

**Comment by bparees** [comment]
the new env variable looks like this:
OPENSHIFT_BUILD_COMMIT=e79d8870be808a7abb4ab304e94c8bee69d909c6

**Comment by bparees** [comment]
I misspoke when i said 1.4.  It will only be in 1.5+
https://github.com/openshift/origin/pull/12390

Is that variable sufficient for your needs?

**Comment by luiscoms** [comment]
I am using this git command to get what I want

    git log -n1 --pretty=format:'%h%d %s - %an'

As a result:

    c3f3d07 (HEAD, tag: 1.3.0) Merge branch 'release/1.3.0' - luiscoms

**Comment by luiscoms** [comment]
I guess that the commit message could be saved into `OPENSHIFT_BUILD_COMMIT_MESSAGE`

**Comment by bparees** [comment]
it could be, but we don't currently have any plans to do so.  it's likely at least some users would object to leaking such information.

**Comment by luiscoms** [comment]
For now I am running the git command on my application.

**Comment by luiscoms** [comment]
With other image I use this approach by extending `assemble` script:

Add a `.s2i/bin/assemble` file

```bash
#!/bin/bash
echo "Before assembling"

/usr/libexec/s2i/assemble
rc=$?

if [ $rc -eq 0 ]; then
    echo "After successful assembling"
    git log -n1 --pretty=format:'%h%d %s - %an' > git_branch.txt
else
    echo "After failed assembling"
fi

exit $rc
```

Described here:

https://github.com/openshift/source-to-image/blob/master/docs/user_guide.md

**Comment by bparees** [comment]
thanks @luiscoms.  since we already provide the git commit env var which can be used for version information, and i'm worried about leaked information if we provide the commit message (and there are valid ways to get the information you want into the image), i'm closing this.
