### ISSUE TITLE
Extended.[k8s.io] DNS should provide DNS for services [Conformance]

### ISSUE THREAD

**Issue by bparees** [openshift/origin#12264]
```
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/dns.go:400
Expected error:
    <*errors.errorString | 0xc8200f3600>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/dns.go:236
```

Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/9572/

**Comment by smarterclayton** [comment]
I'd be surprised if this is not #11016

**Comment by bparees** [comment]
that may be but it's really annoying trying to track down appropriate flake issues when we don't actually have ones open that mention the specific test failure.

also to the extent to which #11016 can be mitigated by making test case changes, it should be, so the issue can be used for that also.
