### ISSUE TITLE
oc process unnecessarily checks namespace on templates from inputstream

### ISSUE THREAD

**Issue by jupierce** [openshift/origin#12277]
According to the documentation, processing templates automatically strips namespace information from objects being processed: https://docs.openshift.com/enterprise/3.0/dev_guide/templates.html  (/"If an object definition’s metadata includes..." ) . However, this sensible step currently does not apply to the template's namespace.

```
$ oc get -o=json template mongodb-ephemeral -n openshift | oc process -f -
```

Results in the error:
```
error: the namespace from the provided object "openshift" does not match the namespace "temp". You must pass '--namespace=openshift' to perform this operation.
````

##### Version
oc v1.5.0-alpha.0+cd418ff-255-dirty
kubernetes v1.4.0+776c994
features: Basic-Auth

##### Steps To Reproduce
1. oc cluster up
2. oc get -o=json template mongodb-ephemeral -n openshift | oc process -f -

##### Current Result
error: the namespace from the provided object "openshift" does not match the namespace "temp". You must pass '--namespace=openshift' to perform this operation.

##### Expected Result
The template should be processed.

##### Additional Information
Using oc export instead of oc get solves this problem, but for reasons related to establishing a fluent Jenkins pipeline DSL, this issue may deserve some attention. The namespace check seems unnecessary and complicates some nice command chaining.

**Comment by bparees** [comment]
Agree, there's no reason I can think of for `oc process` to care what namespace the template resource claims to be from.  However, the error message provides the correct corrective action:

```
You must pass '--namespace=openshift' to perform this operation.

$ oc get -o=json template mongodb-ephemeral -n openshift | oc process -f - --namespace=openshift
```

succeeds.

So reducing this to p3.
