### ISSUE TITLE
RFE: ability to mark/flag images so they're excluded from image pruning

### ISSUE THREAD

**Issue by fgiloux** [openshift/origin#12289]
"oadm prune images" is a very useful command to clear old images. It takes in consideration images that are in use or have been recently used and allow deleting a pile of images created as part of the development process. It is however for auditing and potential rollback required to keep some old images that may not have  been in use for a longer time. Typically images that have been rolled out into production at some point (and decommissioned later on) and have been annotated accordingly.
This enhancement request is to add an option to exclude images with a particular annotation from the pruning operation.

**Comment by ncdc** [comment]
While an annotation may be appropriate and may be the way this gets implemented, I'd recommend just asking for the basic requirement - a way to mark or flag an image such that it is not considered a candidate for pruning.

**Comment by fgiloux** [comment]
Agreed

**Comment by soltysh** [comment]
@mfojtik fyi

**Comment by smarterclayton** [comment]
How would you fit such a tag into your process?  Would this be a manual administration step?  What criteria would you use to identify the images you would tag?

**Comment by fgiloux** [comment]
It would evolve with the release process, first manual and then automated. The tag would be applied at the time the image is either rolled out into production or marked for roll out.

**Comment by mfojtik** [comment]
Tracked in Trello: https://trello.com/c/Gr89MgQB/899-ability-to-mark-flag-images-so-theyre-excluded-from-image-pruning
