### ISSUE TITLE
Loadbalancer between multiple pods 

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [openshift/origin#12283]
I have one deployment config then I am scaling this 1 pod to 4 pod. 
when I am connected via the service to this 4 scaling pods(in one dc) (service  is automatically generated)
all load(tcp request) goto first pod, but same time on others pods(2,3,4) have not activity (only the expectation of requests)

##### Version
```
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.3.0
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
1. Run first pod (from dockerimage)
2. scaling this pod 
3. connecting to this pod via service 

##### Current Result
Work only first pod

##### Expected Result
uniform load/balancing new tcp request

**Comment by knobunc** [comment]
Evgeniy, can you give some details about how you are connecting to the service?

Also, can you give the output from:

oc export svc _servicename_
oc get ep _servicename_

Thanks

**Comment by Evgeniy-Bondarenko** [comment]
I am connecting via route(openshift) from local network. 

`nginx` - `proxy_pass http://localdomain.local:80` => `local_network` => `openshift_route` - `openshift_service` - `openshift_pods(multiple)`

```
$ oc export svc frontend
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: frontend
    deploymentconfig: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
``` 
```
 $ oc get ep frontend
NAME       ENDPOINTS                                                     AGE
frontend   172.16.0.5:9000,172.16.0.7:9000,172.16.0.3:9000 + 1 more...   22d

```

**Comment by knobunc** [comment]
Ok, cool.  How are you testing the route?  From a web browser?  Or with curl?  The service is not directly used when the router is being used.  It uses the service to get the endpoints, and then provides cookie-based persistence to the endpoint that was first selected.

**Comment by Evgeniy-Bondarenko** [comment]
I am generated load over `openshift_route` and all request (from 1000 users) goto first pod.
I am check 2 case:
users - nginx - route - service - pod
users --------- route - service - pod

and I have one result - all traffic go to first pod.

**Comment by knobunc** [comment]
How are you generating the load?  Is it perhaps using the same cookie across requests?

**Comment by Evgeniy-Bondarenko** [comment]
No, I am using wget/curl/httpie bot via parallel request (this apps have not cookie memory)
all bot is starting from different servers in local_network goto first pod.

how i can check/debug traffic routing in openshift energy ? may be i can see traffic in iptables?

**Comment by knobunc** [comment]
Look at the router stats https://docs.openshift.org/latest/admin_guide/router.html#viewing-statistics

The iptables service load balancer is not used when you are using the router.

How are you determining that only one pod is servicing all requests?

Can you `oc export route openshift_route` and give that to me?  And how did you make your router?

**Comment by Evgeniy-Bondarenko** [comment]
I see all request in log pod (debug mode)
Router will be installed in other name space (in current namespace router in not installed),think therefore there was no balancing. 

I have 2 namespace:
- sirst - router is instaled
- second - router is not instaled

After we found a interrelation, I decided to install it (router to second namespace)

```
oadm policy add-scc-to-user hostnetwork -z router
oadm router router --replicas=1 --service-account=router
```

but after install and succesfuly start pod/router - we have error:
```
E1216 23:49:37.652719 1 reflector.go:203] github.com/openshift/origin/pkg/router/template/service_lookup.go:30: Failed to list *api.Service: User "system:serviceaccount:prod:router" cannot list all services in the cluster```

This log is repeated every second

**Comment by knobunc** [comment]
Ah.. you need to grant a permission if you are using sharding:
  https://docs.openshift.com/enterprise/3.2/install_config/install/deploy_router.html#creating-the-router-service-account

**Comment by Evgeniy-Bondarenko** [comment]
Fine! Work after cmmand 
`oadm policy add-cluster-role-to-user     cluster-reader     system:serviceaccount:test:router`

But on other namespace have error in pod when deploy (on installed on the same servers)

```
pod (router-1-i9wl2) failed to fit in any node fit failure on node (pre-node2): PodFitsHostPorts fit failure on node (node1): PodFitsHostPorts 
pod (router-1-i9wl2) failed to fit in any node fit failure on node (pre-node1): PodFitsHostPorts fit failure on node (node2): PodFitsHostPorts
 ```
how many routers should be on the server?
(one router - one namespace or one router - one servver/claster ?)

**Comment by Evgeniy-Bondarenko** [comment]
Current status `router` pods on new namespace - `Status:      Pending` and after 10 error message in prev my message `Status:      Fail`
