### ISSUE TITLE
oc and client keys and certificates returns a tls handshake failure

### ISSUE THREAD

**Issue by usawa** [openshift/origin#12295]
Hi, 

For infrastructure and security reasons, I put an haproxy load balancer in front of my openshift masters. Security asked us to limit access by IP range (this one is working fine), but now I want to add a new functionality : Client certificates and Certificates revocation list. the idea is to allow people to work from everywhere if they've the good key pair. A a result, it works when I use curl (API) or chrome (console). But I'm unable to make it working with the oc CLI. It's like, at some point oc "forgets" to send the key pair in the request.

Could you check if I'm doing something wrong ?

##### Version
Origin 1.3.2 or Origine 1.4.0-rc1 + oc related version
Tests are done using oc cluster up

##### Steps To Reproduce

1. haproxy test configuration, if a client certificate is specified, it uses the "openshift" backend, else it returns a 503 : 

```
frontend frontend-multihost-intranet-uat-https
  mode http
  bind *:8444 ssl crt /certs/crt.pem ca-file /ca_certs/ca.crt crl-file /ca_certs/root.crl.pem verify optional
  use_backend openshift if { ssl_c_used }

backend openshift
  mode http
  balance roundrobin

  default-server inter 3s fall 3 rise 2
  option httpchk get /
  http-check expect status 200

  server localhost 192.168.0.45:8443 check ssl
```

2. curl result (working), as you see at some point there's a redirect to the "real" master url (localhost:8443):
```
$ curl -kvL -4 -XGET  -H "X-Csrf-Token: 1" 'https://localhost:8444/oauth/authorize?response_type=token&client_id=openshift-challenging-client'  --key ./client2.key -E ./client2.p12:toto -u admin:system
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8444 (#0)
* Client certificate: sebastien.rohaut.bis
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: MyOpenshift
* Server auth using Basic with user 'admin'
> GET /oauth/authorize?response_type=token&client_id=openshift-challenging-client HTTP/1.1
> Host: localhost:8444
> Authorization: Basic YWRtaW46c3lzdGVt
> User-Agent: curl/7.51.0
> Accept: */*
> X-Csrf-Token: 1
>
< HTTP/1.1 302 Found
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Expires: Fri, 01 Jan 1990 00:00:00 GMT
< Location: https://127.0.0.1:8443/oauth/token/implicit#access_token=NSHPEuxN0pdUj--cUoaMSSRDHe3cjFmMJUXE_RRWg6U&expires_in=86400&scope=user:full&token_type=Bearer
...
```

2. oc (not working), the HEAD is working, the GET also  (response headers), then, at some point, a 503 is returned :
```
$ oc login --client-certificate ./client2.crt --client-key ./client2.key --insecure-skip-tls-verify=true https://localhost:8444 --loglevel 10
I1217 20:58:19.902599   18912 loader.go:354] Config loaded from file /Volumes/Users/sebastien/.kube/config
I1217 20:58:19.902812   18912 round_trippers.go:299] curl -k -v -XHEAD  https://localhost:8444/
I1217 20:58:19.959085   18912 round_trippers.go:318] HEAD https://localhost:8444/  in 56 milliseconds
I1217 20:58:19.959105   18912 round_trippers.go:324] Response Headers:
I1217 20:58:19.959146   18912 round_trippers.go:299] curl -k -v -XGET  -H "X-Csrf-Token: 1" https://localhost:8444/oauth/authorize?response_type=token&client_id=openshift-challenging-client
I1217 20:58:19.984164   18912 round_trippers.go:318] GET https://localhost:8444/oauth/authorize?response_type=token&client_id=openshift-challenging-client 503 Service Unavailable in 25 milliseconds
I1217 20:58:19.984179   18912 round_trippers.go:324] Response Headers:
I1217 20:58:19.984182   18912 round_trippers.go:327]     Cache-Control: no-cache
I1217 20:58:19.984186   18912 round_trippers.go:327]     Connection: close
I1217 20:58:19.984188   18912 round_trippers.go:327]     Content-Type: text/html
I1217 20:58:19.984333   18912 helpers.go:199] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Internal error occurred: unexpected response: 503",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "unexpected response: 503"
      }
    ]
  },
  "code": 500
}]
F1217 20:58:19.984352   18912 helpers.go:115] Error from server: Internal error occurred: unexpected response: 503
```

3. oc with a slightly different haproxy option (verify required and a default backend), returns:
```
I1217 20:50:41.441646   18565 round_trippers.go:318] GET https://localhost:8444/oauth/authorize?response_type=token&client_id=openshift-challenging-client  in 25 milliseconds
I1217 20:50:41.441662   18565 round_trippers.go:324] Response Headers:
F1217 20:50:41.441692   18565 helpers.go:115] error: remote error: tls: handshake failure
````
##### Expected Result
It should ask for user/password

**Comment by usawa** [comment]
I now got a better understanding of how it works. I understand the TLS client auth is managed on openshift masters/kubernetes side. If I do a ```oc get projects``` with my certs, they're sent to my haproxy frontend (SSL termination), so request is proxified (without certs) to openshift/kubernetes.

But certificate is not sent with the ```login```command, because it's implicit the client certificate replaces the login credentials.

Unlucky, you/we forgot that a first TLS termination could be done on Load balancer / proxy side... We could be able to allow both : it costs nothing to send the certs, even if they're not used to authenticate on openshift/kubernetes side.

**Comment by fabianofranz** [comment]
cc @liggitt

**Comment by liggitt** [comment]
providing a client certificate + key pair to `oc login` to store and send in addition to the obtained API bearer token would be a new feature.

this is a similar feature request to https://trello.com/c/q09n338W

**Comment by usawa** [comment]
I agree, it's exactly what I need. As a temporary workaround, I ask users go to /oauth/token/request to get a token. Then they generate or update their kube config using oc config, with the new token and the certificates. It works. But I would prefer them to use oc login.

**Comment by fabianofranz** [comment]
Closing in favour of the backlog story.
