### ISSUE TITLE
OpenShift uses non-private IP addresses as default ingress range

### ISSUE THREAD

**Issue by hansmi** [openshift/origin#12313]
Pull request #10500 added a default ingress IP range, `172.46.0.0/16`. As of December 20, 2016 that IP range is owned by T-Mobile USA:

```
$ whois 172.46.0.0
…
OrgName:        T-Mobile USA, Inc.
­…
```

Neither #10500 nor the issues #10387 and #10595 talk about why this particular range was chosen. One of the [RFC 1918](https://tools.ietf.org/html/rfc1918) ranges or the test networks in [RFC 5735](https://tools.ietf.org/html/rfc5735) (i.e. `203.0.113.0/24`) would probably be a better choice. The latter wouldn't conflict with existing cluster ranges.

##### Version
The test cluster has Origin 1.3, but the code in question is the same in `master`.
```
$ oc version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
Please note that this is on a cluster with an empty `IngressIPNetworkCIDR`. I understand that the chosen configuration type couldn't possibly work as-is. This issue is merely regarding the chosen range.

```
$ oc create -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: iptest
spec:
  ports:
  - name: test
    nodePort: 31280
    port: 31280
    protocol: TCP
    targetPort: 31280
  sessionAffinity: None
  type: LoadBalancer
EOF

$ oc get svc iptest
NAME      CLUSTER-IP       EXTERNAL-IP                   PORT(S)     AGE
iptest    172.30.205.237   172.46.170.33,172.46.170.33   31280/TCP   5s
```

**Comment by marun** [comment]
Fixed by https://github.com/openshift/origin/pull/12379
