### ISSUE TITLE
Error seen in test-cmd openshift.log

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12325]
```
I1220 21:10:56.062505   22005 factory.go:640] Backing off 4s for pod &{backoff:8000000000 lastUpdate:{sec:63617865056 nsec:62481909 loc:0x84f7ca0} reqInFligh
I1220 21:10:56.929544   22005 object.go:62] Unknown field type 'int64': 86400
```

Wut?

**Comment by mfojtik** [comment]
There is just one place with that value: `pkg/cmd/server/kubernetes/node_config_test.go`.

**Comment by mfojtik** [comment]
It is not an error, just visiting a map field that is int64.

**Comment by smarterclayton** [comment]
Why is it in the logs / why are we reporting it?  Why would int64 be bad?

**Comment by bparees** [comment]
not sure why your line number is 62, but i assume this is coming from:
```
default:
		glog.V(5).Infof("Unknown field type '%s': %v", v.Kind(), v)
		return nil
	}
```

which really just means "this field can't possibly contain a parameter reference, so we're going to ignore it".  @smarterclayton assuming you can confirm your line 62 aligns w/ what i pasted above (which is line 76 in master), we can lower the severity and i can clean up the logging message.

**Comment by smarterclayton** [comment]
Hrm, no idea, this was on a master run I think.
