### ISSUE TITLE
Add name length validations to project creation

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin#1232]
Ran into an issue where I was able to create project 'foo', but unable to push to the local docker registry because the name was too short.  Add name length validations to project creation, server-side, and possibly to the client create project command.  

Per @ncdc ref as the current restrictions are in flux:
https://github.com/docker/distribution/blob/master/registry/api/v2/names.go#L16
https://github.com/docker/distribution/blob/master/registry/api/v2/names.go#L20
https://github.com/docker/docker/issues/10392#issuecomment-76869719
https://github.com/docker/distribution/issues/241

@derekwaynecarr This would need to go upstream?

**Comment by derekwaynecarr** [comment]
Origin will proxy the namespace create request in Kube, so in theory, we can provide our own more restrictive validation once the docker registry constraints are better known.  In practice, I am not a fan of needing to align project name validation with docker registry validation rules.

Is it not possible to adapt a project name to a valid docker registry name?  

For example, if the project name is too short, can we not pad it when its used on the registry side?

**Comment by ncdc** [comment]
@derekwaynecarr we could do that. However, if someone wanted to pull from/push to their image repository in our registry, they'd have to know the padding rules, as `docker pull registry.openshift.com/a/myapp` will fail.

**Comment by derekwaynecarr** [comment]
If the padding rule is to meet a min-length of 2, it's not a lot of padding, so I am less concerned there.

I am more concerned on the max length constraint of 30 characters.  

Kube restricts at a much higher level: 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/util/validation.go#L52

**Comment by ncdc** [comment]
I'm not overly concerned about 30; we're working with Docker to get that increased.

**Comment by derekwaynecarr** [comment]
So if we need to provide our own more restrictive validation that a project has a length between 2 and 30 characters, we can do that, but it limits our ability to expose any existing namespaces in Kuberentes as projects if/when Origin runs as pod on an existing Kubernetes cluster.

**Comment by liggitt** [comment]
@ncdc what did the length requirements end up being for the v2 registry?

**Comment by ncdc** [comment]
@liggitt a Docker image repository is made up of 1 or more components separated by slashes. Each component must be at least 2 characters, and the first character of each component must be alphanumeric. The total length of an image repository's name, including slashes, must be <= 255 characters.

**Comment by ncdc** [comment]
See https://github.com/docker/distribution/blob/master/registry/api/v2/names.go for the impl.

**Comment by liggitt** [comment]
Also see https://bugzilla.redhat.com/show_bug.cgi?id=1190052

**Comment by derekwaynecarr** [comment]
We proxy project creation so in theory we could further restrict validation.

**Comment by liggitt** [comment]
We can, but maybe just on create? Don't want to prevent updating an existing namespace with a short name using the project proxy

**Comment by ncdc** [comment]
I'd like to propose that we add validation somewhere that a namespace must be at least 2 characters, and then for ImageStreams, add validation that len(namespace + / + name) <= 255. Thoughts?

**Comment by liggitt** [comment]
We can add validation on Project create (but not update) and for ImageStream.

**Comment by derekwaynecarr** [comment]
A name is immutable post create, so it should not be a concern.

**Comment by liggitt** [comment]
if we say a project with a single character name is invalid, that could block a project update to add an annotation to a namespace that was created with a single-character name

**Comment by liggitt** [comment]
we can also do namespace validation on image streams... not let them be created in single-character namespaces
