### ISSUE TITLE
Error: Failed switching to "redis": operation not permitted

### ISSUE THREAD

**Issue by maiconbaumx** [openshift/origin#12339]
Hello team!

I i'm just newbie in OpenShift and I'm having problem trying to run a Redis Server.

This is my output log:

```
[root@oc-master ~]# oc logs redis-2-9kbmf
error: failed switching to "redis": operation not permitted
```

Anyone know how to fix this?

**Comment by stevekuznetsov** [comment]
Running application in OpenShift will run them as a random UUID to enhance security. It looks like your application failed to `su redis`, which is expected. Which Redis deployment are you using? It doesn't seem like we have an official OpenShift v3 Redis app to deploy yet, so you may need to edit your security context constraints to:
 - [Enable Images to Run with USER in the Dockerfile](https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile)
 - [Enable Container Images that Require Root](https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root)

Or generally use a less strict security context constraint as described in the [administrator guide](https://docs.openshift.org/latest/admin_guide/manage_scc.html). Note that you will need cluster-level administrative privileges to make these changes.

Note that a more work-intensive approach but an approach that maximizes security would be to build a Redis container image that did not require a specific `USER` or UUID, or `root`.

@bparees may be able to comment on deploying Redis specifically.

**Comment by maiconbaumx** [comment]
Oh, really thank you for your help.
I'm trying to use the latest version of Redis, but I didn't know how in fact OpenShift works with UUID. 
I will try to use less strict security, just for tests purpose, then I will build a new image for my purposes.

Really thank you!

**Comment by stevekuznetsov** [comment]
No problem! If those suggestions end up working out for you, please leave a comment here to that effect so we can make sure you have your question answered before we close out the issue ticket.

**Comment by maiconbaumx** [comment]
Right. Just one more question:
In what section in [this link](https://docs.openshift.org/latest/admin_guide/manage_scc.html) I need to look to use less strict security?

I don't know if you can help me with this question, because this is not a issue, just a newbie question, but, if you can, I'll be thankful. If don't, please, this issue can be closed!

Thank you!

**Comment by maiconbaumx** [comment]
Well, I got it!
Thank you anyway for all the help.

This issue can be closed :D

**Comment by bparees** [comment]
@maiconbaumx fyi there is now an openshift supported redis image and a template for deploying it.. you can find the templates (one uses persistent storage, one uses ephemeral) here: https://github.com/openshift/origin/tree/master/examples/db-templates

you will need to install the new redis imagestream for the template to work, the imagestream is here: https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L733-L771

**Comment by maiconbaumx** [comment]
Ty @bparees!
I'll learn about this..
As I said, I'm newbie in OpenShift, but I'm learning a lot about it.
Can you suggest me some tutorials? I'm reading the documentation =]

**Comment by bparees** [comment]
@maiconbaumx you can go through this tutorial: https://github.com/openshift/origin/tree/master/examples/sample-app

you also might find this interesting:
https://github.com/openshift/origin/tree/master/examples/jenkins

**Comment by maiconbaumx** [comment]
Thank you @bparees!
I'm trying to deploy an image from my private repository of DockerHub and I'm not havinh successfull. I receive the message: You may not have access to the Docker image "foo/bar". What can I do to deploy a image from my private repository of DockerHub?

**Comment by bparees** [comment]
@maiconbaumx you probably need to follow these docs: https://docs.openshift.org/latest/dev_guide/managing_images.html#using-image-pull-secrets

if after following those instructions you're still having an issue, please open a separate issue and detail the steps you are taking, and provide the relevant api object defintions (eg the deploymentconfig, replicationcontroller, pod definition, etc).

**Comment by maiconbaumx** [comment]
Ok, really ty @bparees! I'll try this steps. :D

**Comment by maiconbaumx** [comment]
@bparees I just want to say thank you for your help. I achieved this!

**Comment by bparees** [comment]
@maiconbaumx glad to hear it!

**Comment by samanamp** [comment]
> Running application in OpenShift will run them as a random UUID to enhance security. It looks like your application failed to `su redis`, which is expected. Which Redis deployment are you using? It doesn't seem like we have an official OpenShift v3 Redis app to deploy yet, so you may need to edit your security context constraints to:
> 
> * [Enable Images to Run with USER in the Dockerfile](https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile)
> * [Enable Container Images that Require Root](https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root)
> 
> Or generally use a less strict security context constraint as described in the [administrator guide](https://docs.openshift.org/latest/admin_guide/manage_scc.html). Note that you will need cluster-level administrative privileges to make these changes.
> 
> Note that a more work-intensive approach but an approach that maximizes security would be to build a Redis container image that did not require a specific `USER` or UUID, or `root`.
> 
> @bparees may be able to comment on deploying Redis specifically.

updating the link(this works for kubernetes 4.x as well): https://docs.openshift.com/container-platform/3.6/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root

**Comment by HassanShamshir-perception** [comment]
not worked for me
