### ISSUE TITLE
One project for 2 user

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [openshift/origin#12338]
##### Version
```
$ oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.3.0
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
I have two user (basic-user for develover)
I create one project

##### Current Result
Now the project is not visible to other users.

##### Expected Result
 How to make a common project for all user?
 How to make a common project for group user?

**Comment by stevekuznetsov** [comment]
Policy is created in OpenShift using `oadm policy` commands and the architecture is documented [online](https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html). You will need administrative privileges (`admin` role) to add more policy for a project and cluster administrative privileges (`cluster-admin` role) to add policies for the cluster. The [OpenShift documentation](https://docs.openshift.org/latest/admin_guide/manage_authorization_policy.html) lists available roles and what they mean.

Specifically, to allow a user to see a project and most non-secret items in the project, first enter the project:
```
$ oc project "${PROJECT_NAME}"
```

Then, you can bind the `view` role to them in the project:
```
$ oadm policy add-role-to-user view "${USER_NAME}"
```

To allow a user to add new objects and edit current objects, bind the `edit` role to them in the project:
```
$ oadm policy add-role-to-user edit "${USER_NAME}"
```

To allow a user to administer a project, bind the `admin` role to them in the project
```
$ oadm policy add-role-to-user admin "${USER_NAME}"
```

Similarly, you can bind these roles to a group:
```
$ oadm policy add-role-to-group view "${GROUP_NAME}"
```

**Comment by Evgeniy-Bondarenko** [comment]
Thank you!
