### ISSUE TITLE
We tried to send a request to the provided URL but an error occurred: HTTP status code , SSL_connect returned=1 errno=0 state=error: certificate verify failed

### ISSUE THREAD

**Issue by brunofoca** [openshift/origin#12347]
We tried to send a request to the provided URL but an error occurred: HTTP status code , SSL_connect returned=1 errno=0 state=error: certificate verify failed

##### Version
```
openshift v1.3.2
kubernetes v1.3.0+52492b4
etcd 2.3.0+git
```

##### Steps To Reproduce
I installed Openshift last week. I can open the interface and create projects and now I'm trying to integrate with Gitlab to use auto deploy function of the new Gitlab version, now I need to configure SSL in Openshift server, but I can’t do it by myself, and I need help, if possible.
I used Let's Encrypt, all SSL certs had been generated but Openshift can't read the SSL certs. I'm not sure if I need to convert SSL certs or configure one specific file in Openshift.
I have 4 files (cert.pem, chain.pem, fullchain.pem and privkey.pem for my domain), all generated by Let's Encrypt.
I was trying to config ‘namedCertificates: null’ in node-config.yaml file.
Any help will be appreciated.
Thanks!

##### Additional Information
```
$ oadm diagnostics
WARN:  [DCli1003 from diagnostic ConfigLoading@openshift/origin/pkg/diagnostics/client/config_loading.go:105]
       No client config file was available; however, one exists at
           ./openshift.local.config/master/admin.kubeconfig
       which may have been generated automatically by the master.
       If you want to use this config, you should copy it to the
       standard location (/root/.kube/config),
       or you can set the environment variable KUBECONFIG:
           export KUBECONFIG=./openshift.local.config/master/admin.kubeconfig
       If not, obtain a config file and place it in the standard
       location for use by the client and diagnostics.

[Note] No client configuration specified; skipping client and cluster diagnostics.
[Note] Summary of diagnostics execution (version v1.3.2):
[Note] Warnings seen: 1
```

**Comment by smarterclayton** [comment]
Which URL did you encounter the error?  Was this during the install?

**Comment by brunofoca** [comment]
Hi @smarterclayton,
No, I already installed, the address is: https://openshift.catskillet.com:8443, you can use default credentials, it's test environment.
(when you open will appear https error, this is my problem)...
---------
I installed SSL (Let's Encrypt) in this server but I don't know how to configure in Openshift it, I tried to configure in 'namedCertificates' in 'node-config.yaml' file but didn't work.
So GitLab can't connect because SSL not working yet.
Thanks for your reply and if you need more information I'm ready to send.
Bruno
---------
Attachments
![openshift](https://cloud.githubusercontent.com/assets/21228173/21552790/26cb96f8-cdeb-11e6-87a5-cf52953e76b6.png)
![gitlab](https://cloud.githubusercontent.com/assets/21228173/21552795/2bfc1440-cdeb-11e6-9372-5a805c58efe5.png)

**Comment by smarterclayton** [comment]
If Let's Encrypt is downloading certificates to disk, you'll need to set
that up post installation to point to your downloaded certificates in the
master-config.yaml and node-config.yaml files on each machine.  If you get
the certificates up front, then you'll need to follow the steps here with
Ansible to ensure they are put into place:
https://docs.openshift.org/latest/install_config/certificate_customization.html
.

**Comment by brunofoca** [comment]
Sorry for delay I was trying and testing.
My installation is in this path: /opt/openshift/openshift.local.config
In openshift.local.config appears two directories, master (don't have .yaml file) and node-li1302-130.members.linode.com (node-config.yaml)
So I configured in 'node-config.yaml' the parameters below but it's not working yet:
namedCertificates:
  - certFile: /etc/letsencrypt/live/openshift.catskillet.com/fullchain.pem
  keyFile: /etc/letsencrypt/live/openshift.catskillet.com/privkey.pem
  names:
  - "openshift.catskillet.com"
