### ISSUE TITLE
Openshift adding new nodes to cluster failed

### ISSUE THREAD

**Issue by roshan-mr** [openshift/origin#12359]
Adding new nodes to openshift cluster failed with following errors

```
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (12 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (11 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (10 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (9 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (8 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (7 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (6 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (5 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (4 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (3 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (2 retries left).
FAILED - RETRYING: TASK: openshift_manage_node : Wait for Node Registration (1 retries left).
failed: [10.12.10.10] (item=n11.apps.au.example.net) => {"changed": false, "cmd": ["oc", "get", "node", "n11.apps.au.example.net"], "delta": "0:00:00.119928", "end": "2016-12-29 15:11:16.010129", "failed": true, "item": "n11.apps.au.example.net", "rc": 1, "start": "2016-12-29 15:11:15.890201", "stderr": "Error from server: nodes \"n11.apps..au.example.net\" not found", "stdout": "", "stdout_lines": [], "warnings": []}
```

 I executed the scaleup.yml playbook:

```
$ ansible-playbook ~/openshift-ansible/playbooks/byo/openshift-node/scaleup.yml
```

##### Version
```
openshift v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5
```

##### Steps To Reproduce
https://docs.openshift.com/enterprise/3.2/install_config/adding_hosts_to_existing_cluster.html#adding-nodes-advanced

##### Current Result
```
failed: [10.12.10.10] (item=n11.apps.au.example.net) => {"changed": false, "cmd": ["oc", "get", "node", "n11.apps.au.example.net"], "delta": "0:00:00.119928", "end": "2016-12-29 15:11:16.010129", "failed": true, "item": "n11.apps.au.example.net", "rc": 1, "start": "2016-12-29 15:11:15.890201", "stderr": "Error from server: nodes \"n11.apps..au.example.net\" not found", "stdout": "", "stdout_lines": [], "warnings": []}
```

Any help would be much appreciated.

Regards,
Muhammed Roshan

**Comment by sdodson** [comment]
@roshan-mr Are there other errors logged earlier? Has the origin-node service started successfully on n11.apps.au.example.net? If not is there anything interesting it its logs? `systemctl status origin-node` and `journalctl -lu origin-node`

**Comment by xiaoping378** [comment]
Maybe we need a command: ```oc cluster join <token>```, just like ```kubeadm join <IP> <token>```

**Comment by jawnsy** [comment]
@xiaoping378 "oc cluster join" was merged recently under #9547 but I'm not sure how to use it or if it'd work for your usecase

**Comment by poltorres7** [comment]
@sdodson 
I've this logs with your command

>  -- Logs begin at Tue 2017-03-28 14:25:01 EDT, end at Thu 2017-05-04 18:37:12 EDT. --
> May 04 16:59:08 ose-master-vol.localdomain systemd[1]: Starting Atomic OpenShift Node...
> May 04 16:59:08 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:08.223818    8375 plugins.go:71] No cloud provider specified.
> May 04 16:59:08 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:08.224021    8375 common.go:54] Starting with configured hostname '10.20.10.203' (IP '')
> May 04 16:59:08 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:08.224032    8375 common.go:79] Initializing single-tenant plugin for 10.20.10.203 (10.20.10.203)
> May 04 16:59:08 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:08.224050    8375 start_node.go:288] Starting node 10.20.10.203 (v3.2.1.30)
> May 04 16:59:08 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:08.225104    8375 start_node.go:297] Connecting to API server https://10.20.10.203:8443
> May 04 16:59:08 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:08.231979    8375 node.go:131] Connecting to Docker at unix:///var/run/docker.sock
> May 04 16:59:08 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:08.262790    8375 manager.go:132] cAdvisor running in container: "/"
> May 04 16:59:08 ose-master-vol.localdomain atomic-openshift-node[8375]: W0504 16:59:08.311242    8375 subnets.go:112] Could not find an allocated subnet for node: 10.20.10.203, Waiting...
> May 04 16:59:08 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:08.394895    8375 fs.go:109] Filesystem partitions: map[/dev/vda1:{mountpoint:/ major:253 minor:1 fsType: bl
> May 04 16:59:08 ose-master-vol.localdomain atomic-openshift-node[8375]: W0504 16:59:08.813116    8375 subnets.go:112] Could not find an allocated subnet for node: 10.20.10.203, Waiting...
> May 04 16:59:09 ose-master-vol.localdomain atomic-openshift-node[8375]: W0504 16:59:09.314566    8375 subnets.go:112] Could not find an allocated subnet for node: 10.20.10.203, Waiting...
> May 04 16:59:09 ose-master-vol.localdomain atomic-openshift-node[8375]: W0504 16:59:09.816017    8375 subnets.go:112] Could not find an allocated subnet for node: 10.20.10.203, Waiting...
> May 04 16:59:10 ose-master-vol.localdomain atomic-openshift-node[8375]: W0504 16:59:10.317412    8375 subnets.go:112] Could not find an allocated subnet for node: 10.20.10.203, Waiting...
> May 04 16:59:10 ose-master-vol.localdomain atomic-openshift-node[8375]: W0504 16:59:10.819281    8375 subnets.go:112] Could not find an allocated subnet for node: 10.20.10.203, Waiting...
> May 04 16:59:11 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:11.147665    8375 manager.go:169] Machine: {NumCores:4 CpuFrequency:2394454 MemoryCapacity:8203104256 Machin
> May 04 16:59:11 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:11.178672    8375 manager.go:175] Version: {KernelVersion:3.10.0-327.10.1.el7.x86_64 ContainerOsVersion:Red 
> May 04 16:59:11 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:11.179377    8375 server.go:344] Using root directory: /var/lib/origin/openshift.local.volumes
> May 04 16:59:11 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:11.179583    8375 server.go:683] Watching apiserver
> May 04 16:59:11 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:11.185187    8375 plugins.go:127] Loaded network plugin "redhat/openshift-ovs-subnet"
> May 04 16:59:11 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:11.185225    8375 kubelet.go:380] Hairpin mode set to "none"
> May 04 16:59:11 ose-master-vol.localdomain atomic-openshift-node[8375]: W0504 16:59:11.321556    8375 subnets.go:112] Could not find an allocated subnet for node: 10.20.10.203, Waiting...
> May 04 16:59:11 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:11.323559    8375 manager.go:212] Setting dockerRoot to /var/lib/docker
> May 04 16:59:11 ose-master-vol.localdomain atomic-openshift-node[8375]: I0504 16:59:11.323587    8375 plugins.go:56] Registering credential provider: .dockercfg
> May 04 16:59:11 ose-master-vol.localdomain atomic-openshift-node[8375]: W0504 16:59:11.823434    8375 subnets.go:112] Could not find an allocated subnet for node: 10.20.10.203, Waiting...

what you think it could be?

**Comment by sdodson** [comment]
@poltorres7 the controllers aren't provisioning a subnet for the node as expected. First, verify that `networkPluginName: redhat/openshift-ovs-subnet` is set in /etc/origin/master/master-config.yaml, check your master logs for indications as to why it's not creating the subnet? 

Since you've got an OCP install, `journalctl -lu atomic-openshift-master` or `journalctl -lu atomic-openshift-master-controllers` depending on if it's HA or not.

If it were an origin install it'd be `origin-master` and `origin-master-controllers` if HA.

**Comment by roshan-mr** [comment]
Issue is fixed. Newly added node was running a latest version of Openshift packages. We manually downgraded packages to previous version(same as that of our cluster) and ran the playbook again. This time the node was able to join the cluster.
