### ISSUE TITLE
deploy image bug

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#12355]
I think the results of using openshift console to deploy images should be to let the user can easily deployment project/application/package, such as a nginx, centos/systemd.

By openshift, users can easily through the console running their image, like `oc run`.

When I use the deployment of image feature, I chose the images such as `openshift/centos:latest`, actually it haven't pull 172.30.0.17:5000/openshift/centos(pull the centos image), rather than private image of the warehouse, this is obviously unreasonable.
```lang=bash
Normal	BackOff		Back-off pulling image "centos"
Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "skys-centos" with ImagePullBackOff: "Back-off pulling image \"centos\""
```
Maybe it can be optimized?
By the way,yum package update is not very timely, can be updated？`http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/`

Openshift team is a very good team, we can do better！

![bug-1](https://cloud.githubusercontent.com/assets/12937669/21519711/5050a5c0-cd2a-11e6-8ccc-ac8f7ed90554.png)
![bug-2](https://cloud.githubusercontent.com/assets/12937669/21519712/545051c0-cd2a-11e6-9b02-5fd66ee4974b.png)
![bug-3](https://cloud.githubusercontent.com/assets/12937669/21519715/571a3b46-cd2a-11e6-9fb0-37e55f2d4247.png)
![bug-4](https://cloud.githubusercontent.com/assets/12937669/21519719/5b340f54-cd2a-11e6-819c-b770a1aefc81.png)
![bug-5](https://cloud.githubusercontent.com/assets/12937669/21519852/26748f0e-cd2b-11e6-906d-efaa27417655.png)

**Comment by wenskys** [comment]
such as `oc run newtest --image=172.30.0.17:5000/openshift/centos --replicas=2`

**Comment by mfojtik** [comment]
The image for deployment should be resolved automatically if the deployment has ImageChangeTrigger. ( @kargakis ). I wonder why the image is "centos" when you pick the openshift/centos image stream.

**Comment by wenskys** [comment]
> Deploy an existing image from an image stream tag or Docker pull spec. "deploy image" looks like `oc run`.
Using `deploy image` to deploy an existing image(172.30.0.17:5000/openshift/centos),but openshift pull a new image like **centos**, so I think it might be a bug.
Aren't you?

**Comment by bparees** [comment]
i see nothing here that's an image bug.  Either deployments aren't resolving something they should be, or the console isn't setting up the deployment correct.

**Comment by bparees** [comment]
(or more likely there's a user error, it's fairly difficult to follow exactly what @wenskys did here.  how is the openshift/centos imagestream defined, for example?)
