### ISSUE TITLE
OpenShift-SkyDNS issue. DNSMASQ running in port 53 instead of Openshift provisioned DNS

### ISSUE THREAD

**Issue by roshan-mr** [openshift/origin#12351]
I am seeing that in all my pods running in OpenShift cluster, the DNS settings in the resolv.conf file is pointing to the the IP Address of the node in which the respective pods are running, instead of the service IP of openshift internal DNS (172.30.0.1).  Also, I can see that the port 53 on the master is listening to DNSMASQ, instead of OpenShift. I would like to have the openshift DNS in place instead of the dnsmasq. What is the fix? Any help will be much appreciated.

##### Version
```
openshift v1.3.1
kubernetes v1.3.0+52492b4
etcd 2.3.0+git
```

##### Current Result
DNSMASQ listening to port 53 in master. 
##### Expected Result
OpenShift provisioned DNS service should run in port 53

**Comment by smarterclayton** [comment]
The settings are intentional - using dnsmasq allows more efficent caching.  In addition, it allows us to support a wider range of resolver scenarios.

**Comment by knobunc** [comment]
Closing this issue... if you have further questions or if you think something is wrong please feel free to re-open.
