### ISSUE TITLE
Nodes showing ready despite SSL errors

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#1236]
A node shows as ready as long as /healthz returns a 200, however if I've done something like rebuild my certificate store and I haven't propagated the new CA to the node it cannot reach the API and shouldn't be marked as ready.

I imagine /healthz shouldn't return a 200 if a node is unable to reach the master.

**Comment by smarterclayton** [comment]
Can you open this upstream?

**Comment by sdodson** [comment]
It looks like this may be covered in https://github.com/GoogleCloudPlatform/kubernetes/issues/2959 but I've created https://github.com/GoogleCloudPlatform/kubernetes/issues/5250

**Comment by liggitt** [comment]
I think node status is done by callback now, rather than /healthz pings

**Comment by smarterclayton** [comment]
It is
