### ISSUE TITLE
extended test "idling and unidling unidling [It] should work with TCP (when fully idled) [Conformance]" doesn't work when not on local host

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12362]
Needs to use the harnesses in place in services tests to verify unidling.

```
idling and unidling unidling [It] should work with TCP (when fully idled) [Conformance]
test/extended/idling/idling.go:297
```

**Comment by smarterclayton** [comment]
This is not a flake.

**Comment by DirectXMan12** [comment]
/remove-lifecycle stale

I seem to recall working on this, but need to verify that it got fixed.

**Comment by DirectXMan12** [comment]
/remove-lifecycle rotten

We still need to get around to this.

> Needs to use the harnesses 

@smarterclayton what specifically do you mean by this?
