### ISSUE TITLE
oc cluster up on Mac ignores FQDN for --public-hostname

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#12369]
This may be related to https://github.com/openshift/origin/issues/12337.

On a Mac, if you supply a FQDN using an xip.io address that maps to 127.0.0.1, it ignores the FQDN and uses 127.0.0.1 anyway.

```
$ oc cluster up --public-hostname=profile.127.0.0.1.xip.io
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.0-rc1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://127.0.0.1:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
```

What I expect to see is that it says the web console is accessible as:

```
https://profile.127.0.0.1.xip.io:8443
```

and for that to be the REST API endpoint as well. That isn't the case though:

```
$ oc whoami --show-server
https://127.0.0.1:8443
```

If you access ``https://profile.127.0.0.1.xip.io:8443`` it just redirects you back to ``https://127.0.0.1:8443`` as well, confirming that it doesn't use it internally.

Not sure if this is simply because ``--public-hostname`` is ignored on Mac, or whether because the FQDN maps to 127.0.0.1 that ignores it and uses the IP instead.

The intent of doing this is so that one can embedded a distinguishing name in the FQDN, so that one can have multiple different save instances of cluster that one would start up at different times where they have different context names. That way starting a second instance doesn't have conflicting context name which causes problems with caching and reusing credentials.

Only current solution is to stuff around with contexts yourself and change manually.

**Comment by csrwng** [comment]
This looks like a bug. Will work on a fix.
