### ISSUE TITLE
Error When building nodejs project

### ISSUE THREAD

**Issue by TheRealImaginary** [openshift/origin#12374]
I was following the [Getting Started](https://docs.openshift.com/online/getting_started/beyond_the_basics.html#btb-creating-a-new-application-from-source-code) Tutorial for starting/building a nodejs app. After I login, I use:
oc new-project elise
oc new-app .  --name elise
oc start-build elise

In the console it says "build "elise-1" started", and then in the webconsole, it says running, shortly after wards it fails with an error. Here's the log:
```
Pulling image "registry.ops.openshift.com/rhscl/nodejs-4-rhel7@sha256:d1ff569f7f6c9abe794d7d28d64d5365d04f7093b1c90f52b896ade20ae4f1ad" ...
Pulling image "registry.ops.openshift.com/rhscl/nodejs-4-rhel7@sha256:d1ff569f7f6c9abe794d7d28d64d5365d04f7093b1c90f52b896ade20ae4f1ad" ... 
---> Installing application source ...
mv: cannot stat '/tmp/src/*': No such file or directory
error: build error: non-zero (13) exit code from registry.ops.openshift.com/rhscl/nodejs-4-rhel7@sha256:d1ff569f7f6c9abe794d7d28d64d5365d04f7093b1c90f52b896ade20ae4f1ad
```

oc v3.3.1.4
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.preview.openshift.com:443
openshift v3.3.1.3
kubernetes v1.3.0+52492b4

**EDIT**
I used the web console instead for creating the app. It doesn't throw the same error, however a different one, here is a snippet of the log:
```
npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/opt/rh/rh-nodejs4/root/usr/bin/node" "/opt/rh/rh-nodejs4/root/usr/bin/npm" "install"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package erlpack@0.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer discord.js@11.0.0 wants erlpack@hammerandchisel/erlpack#master

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app-root/src/npm-debug.log

error: build error: non-zero (13) exit code from registry.ops.openshift.com/rhscl/nodejs-4-rhel7@sha256:d1ff569f7f6c9abe794d7d28d64d5365d04f7093b1c90f52b896ade20ae4f1ad
```
I think it has to do with being unable to download a dependency, not sure why, can anyone guide me on how to fix it please ?

**Comment by PI-Victor** [comment]
i think i saw your stackoverflow question and forgot to reply to it yesterday, sorry.
i can build the example just fine, well almost, i can build it locally, but i'm using the latest version. online devpreview doesn't create containers for me.
that first error looks a lot like you have some scripts missing for s2i.
can you `npm update` locally, commit your changes, push and use your forked example to redeploy?

**Comment by PI-Victor** [comment]
doesn't seem to be dependencies, since packages.json deps have loose dependency requirements.
also i was able to deploy online with `oc new-app https://github.com/pi-victor/nodejs-ex --name nodejs-mongodb-example`

**Comment by TheRealImaginary** [comment]
Thanks for you response, (that was not me on stackoverflow :P), It works now. =D.Thanks again.
