### ISSUE TITLE
base_ami for rhel7next is failing due to missing a volume group for Docker storage

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12370]
https://ci.openshift.redhat.com/jenkins/job/base_ami/2609/

```

Running ssh/sudo command 'SSH_USER='ec2-user' /home/ec2-user//resources/configure_docker.sh' with timeout 1800. Attempt #0
/home/ec2-user//resources/configure_docker.sh: line 25: VG: unbound variable
Error while running ssh/sudo command: SSH_USER='ec2-user' /home/ec2-user//resources/configure_docker.sh
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

SSH_USER='ec2-user' /home/ec2-user//resources/configure_docker.sh

Stdout from the command:



Stderr from the command:

/home/ec2-user//resources/configure_docker.sh: line 25: VG: unbound variable
```

**Comment by mfojtik** [comment]
weird, I just ran the commands locally and the configure_docker.sh worked fine...

**Comment by stevekuznetsov** [comment]
Not quite a scripting error. There is no Docker storage volume group, which, while it shouldn't crash the build, actually does indicate a failure in the AMI creation. It has happened before but I still don't quite understand why.

**Comment by stevekuznetsov** [comment]
@danmcp FYI

I'm going to lower this priority, looks like a bug in the base OS AMI for rhel7next but I'm not sure if that really impacts us for now. We will be explicitly creating the VG using `oct` anyway.

**Comment by stevekuznetsov** [comment]
This AMI is not supported.

/close
