### ISSUE TITLE
The OpenShift API seems to end keepalive connections with a TCP reset.

### ISSUE THREAD

**Issue by nixx** [openshift/origin#12371]
When using the API with http keep-alive, the connection is closed with a TCP reset after 24 hours

##### Version
openshift v3.3.1.5 (Enterprise)
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Make a connection to the API with HTTP/1.1 (either in a pod to KUBERNETES_SERVICE_HOST or to the master from outside)
2a. Let the connection stay open without sending any traffic.
2b. Reuse the connection over a longer period of time. 
##### Current Result

The client seems to receive a TCP reset when the server closes the connection.

When the connection stays idle, we get a TCP reset from the outside it happens after a few minutes.

When we send traffic, we get at TCP reset after approx 24 hours.

##### Expected Result

A graceful shutdown with TCP close and not at TCP reset when the connection has been idle for some time.

A "Connection: close" in the response from the server if we have a connection that is long lived and the server wishes to close it.

##### Additional Information

We are using Vertx which uses Netty. The default settings is to have persistent connections without timeouts.

We can add timeouts on the clients, but a sensible keepalive timeout (Apache has 5 seconds as a default) would be nice, since people tend not to adjust the defaults in their frameworks.

**Comment by mfojtik** [comment]
@smarterclayton any thoughts?

**Comment by smarterclayton** [comment]
Can you describe your environment, I.e. what load balancers are in play?

**Comment by nixx** [comment]
We use OpenShift Enterprise v3.3.1.5. We are running three masters.

I see that I should probably have made two issues, one for the access from outside of the cluster via HAProxy and one from access to the API from a pod running inside the cluster.  We are using the KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT when running inside the cluster.

See the screenshot from Wireshark:
![screenshot](https://cloud.githubusercontent.com/assets/138005/21764122/c22dbb66-d661-11e6-8c32-d246742ab914.png)

We query the API every two minutes, and after a while, we receive a TCP reset. The attached screenshot is from a TCP dump from a pod. The initial assumption was that it happend every 24 hours. This was not correct, because after restarts of some pods, we got it at the same time of day, but before 24 hours after establishing the connection.

I do understand that these kind of problems is very difficult to pinpoint (at least I feel they are). But the TCP reset aside, a shorter timeout on HTTP Keep-Alive would make sense either way.

**Comment by smarterclayton** [comment]
@openshift/networking for the service access this would be the node iptables proxy / SDN plugin or the API - can you guys help us identify whether we have an aggressive connection timeout setup that might cause this before the APIs?

The masters will definitely timeout connections after a certain period - if you're seeing it at a certain time of day, that could be a number of things:

1. HAProxy being restarted
2. Node iptables terminating connections
3. Individual masters terminating connections from Go runtime

**Comment by eparis** [comment]
haproxy shouldn't be involved on these internal communications, right?

Is it possible to get a simultaneous captures like the above from the master, node, and the client pod? So we can better see where the rst is being generated? I can see this capture itself is rather huge, so I image the node and master will be even worse...

**Comment by smarterclayton** [comment]
Right, it was reported for both ends and I wanted to be sure there aren't two overlapping errors (a reset from haproxy and a different reset from iptables, vs potentially just a reset on the master itself via go).

**Comment by danwinship** [comment]
Are they adding any firewall rules of their own?

Also, getting logs from the master (maybe with --loglevel=5) from the time when the connection gets dropped would be useful (to see if it logs an error, or if the drop corresponds to when it's reloading iptables rules, etc)

**Comment by nixx** [comment]
We will give you a TCP dump as requested, but we need a few days..

**Comment by nixx** [comment]
Sorry for the late feedback.

We still get resets periodically, but capturing a tcpdump has not been as easy as first assumed. We need to capture a lot of data to see something interesting, and some of the data is sensitive, and I won't risk any exposure.

We continue to see the resets every now and then, but less frequently after adding timeouts to every keep-alive connection. My initial comment of having a shorter keep-alive timeout stands, but as long as we know that we need to add timeouts to clients, it is less of a problem for us. Unfortunately I don't have time to keep investigating this any further now, but I will keep our probes running, and will report back if I'm able to pinpoint better the source of the connection reset.

Thanks for the help and the great product:)

**Comment by kargakis** [comment]
@openshift/sig-networking
