### ISSUE TITLE
[test][extended] openshift pipeline plugin returns 404

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#12383]
Not sure what's causing this, so i'm opening ~a temporary~ an issue.
The openshift pipeline plugin extended tests are returning 404.
See https://ci.openshift.redhat.com/jenkins/job/origin_extended_image_tests/807/

logs:
https://ci.openshift.redhat.com/jenkins/job/origin_extended_image_tests/807/consoleFull#40473246556cbb9a5e4b02b88ae8c2f77

**Comment by mfojtik** [comment]
cc @gabemontero

**Comment by gabemontero** [comment]
@csrwng - it may be coincidence, but did your https://github.com/openshift/origin/commit/5fca12e2a10a15878ee1ef138d80632cf3c73c7b merge recently?

**Comment by gabemontero** [comment]
In general, the creation of jobs is no longer working for any of the plugin tests.  In examining the failures, I noticed the version of jenkins_plugin.go I had pulled from origin yesterday was no longer up to date.  Doing the update this morning is when I believe I noticed that @csrwng 's change had merged.

**Comment by csrwng** [comment]
@gabemontero taking a look

**Comment by csrwng** [comment]
yup, it was my bad ... for some reason I thought I ran extended tests for both sets of affected tests, but I guess I only ran them for the pipeline examples. PR submitted.
