### ISSUE TITLE
osc log fails

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#1239]
When running as a project admin, `osc log pod` results in
```
Forbidden: "/api/v1beta1/proxy/minions/deads-dev-01/containerLogs/test/database-1-rsn1t/ruby-helloworld-database?follow=false" denied by default 
```

Proxying for `osc log pod` builds a URL that tries to hit a minion, `/api/v1beta1/proxy/minions/deads-dev-01/containerLogs/test/database-1-rsn1t/ruby-helloworld-database?follow=false`. Since that is non-namespaced and we don't want project admins mucking around with minions, we have to come up with some way of authorizing this request that doesn't involve global rights to minions.

For my own notes, the authorization attributes come in as:
```
authorizer.DefaultAuthorizationAttributes{Verb:"proxy", Resource:"minions", ResourceName:"deads-dev-01", RequestAttributes:interface {}(nil), NonResourceURL:false, URL:"/api/v1beta1/proxy/minions/deads-dev-01/containerLogs/test/database-1-rsn1t/ruby-helloworld-database"}
```

**Comment by ncdc** [comment]
I'm guessing this would also fall under https://trello.com/c/YC6ri7qQ/380-13-implement-a-secure-proxy-for-logs-remote-execution-and-other-node-level-services-security-codefreeze, right?

**Comment by deads2k** [comment]
@csrwng I'm pretty sure you're doing this.

@liggitt reassign if Cesar agrees?

**Comment by csrwng** [comment]
@deads2k yup -- https://github.com/openshift/origin/pull/1978

**Comment by csrwng** [comment]
@deads2k - this issue should be fixed. can you close it?
