### ISSUE TITLE
Review git non-URL parsing in origin and s2i

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#12403]
Golang 1.8 will tighten its URL parsing code (https://github.com/golang/go/commit/c5ccbdd22bdbdc43d541b7e7d4ed66ceb559030e).  This will affect how we handle git non-URL strings (e.g. user@host:/path)  - review and clean origin and s2i in preparation.

**Comment by bparees** [comment]
@jim-minter well you warned us but i'm going to close this as a dupe to retain the other issues opened for this:
https://github.com/openshift/origin/issues/14831
https://github.com/openshift/origin/issues/15005
