### ISSUE TITLE
[RFE] OpenShift checker like oc_lint

### ISSUE THREAD

**Issue by phracek** [openshift/origin#12404]
During the writing of templates and pods, sometimes, I made a mistake.

Unfortunaly I don't know it and during processing template I see errors like spec.containers.image is empty and something like that.

It would be nice to have a tool which could do some preprocessing and help me at the beginning with stupid errors.

But maybe it is out of scope.

**Comment by pweil-** [comment]
Closing in favor of the existing RFE card in Trello https://trello.com/c/32jW0GmA/778-8-template-linter-evg-templates
