### ISSUE TITLE
how to use sshd in openshift

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#12414]
hi，i want to use sshd in openshift，but that is someting wrong.

```
oc run myssh --image=172.30.0.17:5000/openshift/centos-sshd:6
oc exec -it ansible-sshd-2-9fyne /bin/bash
[root@ansible-sshd-2-9fyne /]# ssh 10.30.0.15     
Read from socket failed: Connection reset by peer
```
when i use `docker run -d --name=myssh 172.30.0.17:5000/openshift/centos-sshd:6`,it's work well.
```
[root@05128dd66aa4 /]# ssh 10.30.1.15 -lroot
root@10.30.1.15's password: 
[root@05128dd66aa4 ~]# 
```
i also use `oadm policy add-scc-to-user anyuid -z default` for my project.
who call i do for use sshd in openshift?thanks

**Comment by mfojtik** [comment]
@wenskys the question is how you can run "ssh <host>" from a container running inside the OpenShift to another container? Is the IP address (10.30.1.15) accessible from cluster?

**Comment by mfojtik** [comment]
@knobunc I think this might be networking problem in the end :-)

**Comment by wenskys** [comment]
@mfojtik 
the container ip(10.30.1.15,run as `docker run `) can't accessible from cluster.
other application(such as `oc run xxx`) is ok,such as nginx,redis,zookeeper.
only the ssh container hava this problem.
```lang=bash
OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to 10.30.0.17 [10.30.0.17] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: identity file /root/.ssh/identity type -1
debug1: identity file /root/.ssh/identity-cert type -1
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.3
debug1: match: OpenSSH_5.3 pat OpenSSH*
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_5.3
debug2: fd 3 setting O_NONBLOCK
debug1: SSH2_MSG_KEXINIT sent
debug3: Wrote 960 bytes for a total of 981
Read from socket failed: Connection reset by peer
```

**Comment by knobunc** [comment]
What does 'oc logs' say for the container?  Without having the pod and image definitions I can't be sure, but my hunch is that sshd is trying to bind to port 22 and in docker it works because it is running as root, but openshift uses a non-privileged user by default.  So you need to either make the container privileged or make sure that the container keeps CAP_SERVICE_BIND (using an scc).  An easier answer is to use a non-privileged port (say 2222) and then have a service that takes port 22 and maps it to 2222.

But, why do you want to run sshd anyway?  You can oc rsh into a container if you want to debug.

**Comment by kargakis** [comment]
Closing in favor of more discussion in the mailing list

http://lists.openshift.redhat.com/openshift-archives/users/2017-July/msg00017.html

**Comment by akostadinov** [comment]
I'll plug here my blog about creating a suitable ssh image for running within OpenShift unprivileged:
https://rboci.blogspot.bg/2016/06/creating-docker-images-suitable-for.html

I believe it is still valid.

**Comment by Melki-Sap** [comment]
Hi akostadinov, I tried your https://rboci.blogspot.bg/2016/06/creating-docker-images-suitable-for.html but did not worked. Could you explain more about Openssh running on Openshift ? Thank you.

**Comment by akostadinov** [comment]
@Melki-Sap , if you explain more about what did you do and what exactly didn't work, then I can check it. I have not built a new image for a long time. It is also possible that something changed in the meanwhile. But better do in a blog comment.
