### ISSUE TITLE
1.5 post-rebase tasks

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#12425]
- [ ] ~~ungrossify `GetOperationIDAndTags` in `pkg/cmd/server/kubernetes/master_config.go`~~
- [ ] ~~clean up copy-kube-artifacts.sh / find a way to ensure running godep-save.sh doesn't delete all the files pulled in via copy-kube-artifacts~~
- [ ] ~~in `pkg/cmd/server/kubernetes/master_config.go`, where we have `genericConfig.SecureServingInfo.ExtraClientCACerts, err = ...`, "I'd rather see GetClientCertCAs []*x509.Certificate than expose GetOAuthClientCertCAs and spread knowledge of all the config fields that contain client ca files."~~
- [x] Fix pkg/build/admission/jenkinsbootstrapper/admission.go and the ClientMapper method, see https://github.com/ncdc/origin/pull/26 where it was added (@deads2k mentioned we might want to fix the a.privilegedRESTClientConfig which should have those values already set)
- [x] remove `pkg/client/testclient`
- [x] remove commented out `resourceEncodingConfig.SetVersionEncoding…` in `pkg/cmd/server/kubernetes/master_config.go`
- [x] ungrossify how we configure the client for the cron job controller in `pkg/cmd/server/start/start_master.go`
- [x] see if we can fix lister-gen so it correctly creates `expansion_generated.go` for the OpenShift api group given that it has types split across multiple packages for the same GroupVersion; add verify-generated-listers.sh to `make verify`
- [x] sweep all OpenShift repos for references to PetSet and rename to StatefulSet - https://github.com/openshift/origin/pull/12642
- [x] sweep all OpenShift repos for references to ScheduledJob and rename to CronJob - https://github.com/openshift/origin/pull/12518
- [x] remove kube boilerplate headers from any files in origin - https://github.com/openshift/origin/pull/12613
- [x] set watch cache sizes appropriately in `pkg/cmd/server/kubernetes/master_config.go` (`cachesize.InitializeWatchCacheSizes(s.GenericServerRunOptions.TargetRAMMB)`)
- [x] replace origin node auth with upstream auth (@liggitt)
- [x] In `pkg/cmd/server/origin/master_config.go`, remove our use of SelfSubjectAccessReview attributeInfo so we can replace with the upstream version (see TODO `replace AuthorizationAttributeBuilder with kapiserverfilters.NewRequestAttributeGetter`)
- [x] Reconsider every filter in the handler chain and try to use upstream filters
- [x] Replace origin admission Validator interface with kube’s since they’re identical - https://github.com/openshift/origin/pull/12750
- [x] Update build tools to use go1.7, due to a few deps in k8s repo (namely new fields in http lib)- https://github.com/openshift/origin/commit/8c8bf03fe7abea6df6d2887cce47613e59cbf716
- [ ] ~~Figure out why DNS is taking longer to serve requests (the services/endpoints reflectors are taking longer to be primed, maybe?)~~
- [x] ...

**Comment by ncdc** [comment]
I'll be adding more here but I'm going to take a quick lunch break. FYI @smarterclayton @mfojtik @soltysh @deads2k @liggitt @sttts

**Comment by kargakis** [comment]
@mfojtik can you pick up plumbing --dry-run in `oc rollout` for DCs?

**Comment by mfojtik** [comment]
@kargakis adding to my list, thanks

**Comment by kargakis** [comment]
Seems like we already have an issue for that (https://github.com/openshift/origin/issues/11215) so I am removing it from the TODO list of this issue.

**Comment by mfojtik** [comment]
@liggitt if you get time, can you please go through this list and check what we are missing?

**Comment by liggitt** [comment]
essential items completed
