### ISSUE TITLE
Can't seem to log into internal docker registry

### ISSUE THREAD

**Issue by tellmejeff** [openshift/origin#12426]
I'm trying to log into the internal registry to push some images since I'm working behind a proxy and can't access the redhat registry normally. I followed the instructions for creating the registry and securing it, and creating a route for it so that I can send requests to it via https://$(hostname):8443. But the login is failing telling me that 'User "system:anonymous" cannot "post" on "/v1/users/"'. 

##### Version
```
oc v3.3.1.5
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ld7-zko8s6q-ws:8443
openshift v3.3.1.5
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
```
docker login -u $(oc whoami) -e 'jeffrey.s.poore@bankofamerica.com' -p $(oc whoami -t) $(hostname):8443
```

##### Current Result
```
Error response from daemon: Unexpected status code [403] : {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot \"post\" on \"/v1/users/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

##### Additional Information
I do see this from the oadm diagnostics command:
```
 ERROR: [DP1012 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:168]
              Unexpected status code from integrated registry authentication:
              400 Bad Request
```

Attached the ouptut of 'oc get all -o json -n default' which should include all the docker registry resources.

[all.json.txt](https://github.com/openshift/origin/files/694152/all.json.txt)

I'm sure I'm just missing some crucial step.

**Comment by ncdc** [comment]
Are you sure you have the hostname & port of the registry correct? If you get the error message you pasted, it typically means you're trying to `docker login` to the OpenShift master server.

**Comment by tellmejeff** [comment]
someone pointed out to me that is the web console. duh. I have been
battling issues trying to log in on the internal IP on port 5000 and it
just seems to hang.

**Comment by tellmejeff** [comment]
Actually I determined that the hang was caused by the proxy I'm behind. But now I get this when I try to log in:

docker login -u $(oc whoami) -e 'jeffrey.s.poore@bankofamerica.com' -p $(oc whoami -t) 172.30.10.52:5000
Error response from daemon: no successful auth challenge for https://172.30.10.52:5000/v2/ - errors: [basic auth attempt to https://172.30.10.52:5000/v2/ realm "openshift" failed with status: 400 Bad Request]

**Comment by tellmejeff** [comment]
I determined from the log in the registry that it was missing OPENSHIFT_CA_DATA and OPENSHIFT_MASTER env vars. Now I have that, but I have a certificate verification issue. I don't suppose there is a way to turn off tls verify for the auth part:

time="2017-01-09T22:05:32.534367922Z" level=error msg="error authorizing context: Get https://ld7-zko8s6q-ws:8443/oapi/v1/users/~: x509: certificate signed by unknown authority" go.version=go1.4.2 http.request.host="172.30.10.52:5000" http.request.id=a2185549-e63b-4e79-bdc5-10811261925e http.request.method=GET http.request.remoteaddr="10.1.0.1:45818" http.request.uri="/v2/" http.request.useragent="docker/1.10.3 go/go1.6.2 git-commit/429be27-unsupported kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64" instance.id=56341edd-c907-4c05-a7cd-f810f9e17d0b

**Comment by mfojtik** [comment]
@pweil- i have no idea how the api-approved label was added... must be safari/github glitch.

**Comment by tellmejeff** [comment]
I reinstalled my registry and was able to log in. I believe this was an issue of registering the host certificates correctly.
