### ISSUE TITLE
Logs showing error in custom oadm router

### ISSUE THREAD

**Issue by PhilipGough** [openshift/origin#12421]
When deploying a custom router inside an OpenShift project, limited to a specific namespace, the logs are throwing the following error repeatedly:

```
E0106 06:22:27.931327       1 reflector.go:203] github.com/openshift/origin/pkg/router/template/service_lookup.go:30: Failed to list *api.Service: User "system:serviceaccount:myProjectName:myServiceAccount" cannot list all services in the cluster
```

##### Version
```
openshift v3.3.0.34
kubernetes v1.3.0+52492b4
etcd 2.3.0+git
```

##### Steps To Reproduce
This router is deployed from a template but essentially it is using the `oadm router` command with host networking set to false and restricted to a specific namespace.
 
##### Current Result
The router itself is working perfectly, the entries are being populated inside the map file and traffic is being directed as expected. The only issue is the pollution of the logs make it unusable for the required purpose.

When I create a cluster role binding for the service account, the router works the same, but the above error is not thrown so there is no issue. This is fine as a workaround, but I would like to not to have to create the role binding as it must be done as an admin.

@knobunc @DirectXMan12

**Comment by knobunc** [comment]
This is fixed in 3.4 as bug https://bugzilla.redhat.com/show_bug.cgi?id=1380669 with PR https://github.com/openshift/origin/pull/11713
