### ISSUE TITLE
JSON Validation on API calls

### ISSUE THREAD

**Issue by ejemba** [openshift/origin#1243]
Some users warn that error messages we get from malformed json on API calls are unclear. So they spent time to debug their json input.

I propose to add something like json-schema ( http://json-schema.org ) with the go associated library ( https://github.com/xeipuuv/gojsonschema )

JSON Schema allow to validate an input JSON against a schema definition. And we get fine grained error messages.

For instance a schema can be this

    {
        "title":  "Example Schema",
        "type":  "object",
        "properties":  {
            "firstName":  {
                "type":  "string"
            },
            "lastName":  {
                "type":  "string"
            },
            "age":  {
                "description":  "Age in years",
                "type":  "integer",
                "minimum":  0
            }
        },
        "required":  ["firstName",  "lastName"]
    }

I do not think this can impact performance or if yes we can just activate it for test & quality purpose.

What do you think about this ?

Epo

**Comment by smarterclayton** [comment]
We have swagger, which is supposed to most of this.  Upstream has been tracking towards a fix for some of the issues.  However, we're still gated by the golang JSON parser which (while generally awesome) has some limitations when you want to deeply control the structure.  That's covered by https://github.com/GoogleCloudPlatform/kubernetes/issues/3338 which I'll say covers this issue.
