### ISSUE TITLE
Question - how to wrap these oc commands in ReST API

### ISSUE THREAD

**Issue by mjangid** [openshift/origin#12436]
Hi There,

I am trying to create a project in OpenShift internal infrastructure via the API.
Which API should I use for below and do we have any sample for these?

```
oc new-project signon
oc policy add-role-to-user system:image-puller system:serviceaccount:signon:builder -n mjangid
oc new-app mjangid/t24\~https://gitlab.myserver.com/root/signon-t24-s2i.git --name=t24
oc new-app mjangid/h2\~https://gitlab.myserver.com/root/signon-h2.git --strategy=docker --name=h2
```

Thanks
Manoj Jangid

**Comment by mfojtik** [comment]
@mjangid the first two seems one-shot API calls, the new-app however has built in logic for the input which will result in multiple API calls..

**Comment by stevekuznetsov** [comment]
@mjangid while I don't necessarily suggest this as the backing logic for `new-app` might change... you could run all of these commands with `--loglevel=10` and you'd see all of the REST calls come out in the log.

**Comment by mfojtik** [comment]
@stevekuznetsov new-app has a lot of machinery to determine things from GIT repo or from the image metadata.

**Comment by kargakis** [comment]
Please use the mailing list for this kind of questions
