### ISSUE TITLE
support parent/child namespaces for service discovery

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#1244]
we've been trying to figure out ways to provision things like ElasticSearch, InfluxDB, Keycloak and so forth for OpenShift V3 customers. There are 2 extreme scenarios: providing services for the administrators of OpenShift themselves versus application developers inside a namespace (different groups/teams in prod/dev/test etc). 

In many ways we want to share services across as many namespaces as possible (having everything in the same namespace tends to pollute UIs, its very inefficient etc). Plus there's huge overhead running all the tools for every namespace (e.g. an Elasticsearch cluster for each namespace, a Keycloak for each namespace, Influxdb cluster for each namespace).

The other option is to have a single global installation of everything. But then that has other risks (e.g. often folks can't accept the risk of production data being potentially exposed in a shared Elasticsearch cluster with non-production people).

e.g. for logs / metrics / security, you often want groups of things. A typical on premise may want to isolate logs/metrics/authentication for production systems from non-production. So you may just want, say, 2 group; one for prod stuff one for non-prod and for each of those to have Elasticsearch, InfluxDB and so forth.

If there was a way of having a parent/child relationship with namespaces; any namespace in a child of the 'development' namespace could inherit all the shared services in that namespace (e.g. shared Elasticsearch / InfluxDb and so forth).

By sharing here I mean that the Services in this namespace would get pre-populated with all the services from the parent namespace; so it would look and feel like all these services are in that namespace; that the implementations could be shared between namespaces.

The general idea is to make things look and feel like things are in their own separate namespaces; but have a grouping/organisation structure so that things can be shared.

i.e. I'm suggesting a way to map namespaces as being children of a parent namespace; so that services can be provisioned in the parent namespace which would then be visible in the child namespace. 

This simple idea would make it easy to share horizontal services across teams/projects/namespaces without having to either run everything in every namespace - and we'd be able to reuse the existing Kubernetes service discovery mechanism too.

**Comment by jstrachan** [comment]
I guess this general idea is like having organisations in authentication; a way of grouping namespaces and sharing services between them

**Comment by jstrachan** [comment]
a similar but unrelated issue on this topic. We've a really nice [Arquillian based integration testing framework for kubernetes](http://fabric8.io/v2/testing.html) that can easily perform java / junit based integration tests of kubernetes replication controllers / services / pods. 

It works by creating a new namespace for each integration test; which is great. However it'd be nice if we could associate each new dynamically created namespace with a group/organisation; so it could automatically inherit centralised logging and so forth

**Comment by smarterclayton** [comment]
I'm really hesitant to introduce hierarchy but I agree the use case is valid and we need to have a way to solve this for efficiency reasons.  I do *not* want to do nested ACL traversals, but there may be a way to simplify this.  We should try to sketch out a couple of designs on how to do this.

**Comment by jstrachan** [comment]
Agreed. I'm hoping this can be lightweight really and not involve massive changes. 

Mostly its about having an easy way to discover services in a parent/inherited namespace; we could maybe leave the ACL stuff as it is (each namespace defines its own ACL) and just have a way to import services (e.g. populate the service environment variables for inherited services etc)
