### ISSUE TITLE
CLI parser reports wrong incorrect option

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#1245]
Tried this command:
```
openshift start --listen=http://127.0.0.1:8080 --require-authentication=true
```
and it said
```
unknown flag: --listen
```
which is obviously wrong, because there's no `--require-authentication=true`, not `--listen`.

git master, 0.4.0 too

**Comment by smarterclayton** [comment]
@fabianofranz something we should fix upstream

**Comment by fabianofranz** [comment]
Fixed in https://github.com/openshift/origin/pull/1640
