### ISSUE TITLE
Support docker aws regions

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#12454]
The region list in the s3 driver is out of date.  We are missing us-east-2.  The upstream also does not support ca-central-1 - it needs to be added and rebased into our dependency.

https://github.com/docker/distribution/blob/master/registry/storage/driver/s3-aws/s3.go#L104
https://github.com/openshift/origin/blob/master/vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go#L73

**Comment by pweil-** [comment]
from @derekwaynecarr 

```
I had to add the following to Kube related items for each release:

3.3 to add missing support for the following: ap-south-1, ca-central-1, us-east-2

3.4 to add missing support for the following: ca-central-1, us-east-2

We should make sure that has parity.
```

**Comment by pweil-** [comment]
https://github.com/docker/distribution/pull/2140

**Comment by DanyC97** [comment]
i guess this issue ca be closed?

**Comment by pweil-** [comment]
https://github.com/openshift/origin/pull/12451

**Comment by tj13** [comment]
@pweil- +1  for cn-northwest.
