### ISSUE TITLE
Post-rebase: conformance test hung getting logs off the node

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12458]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/10037/console

This is unusual - I wonder if we ran out of disk space.  Opening to have something to track.

**Comment by smarterclayton** [comment]
@ncdc

**Comment by ncdc** [comment]
This is probably the hanging VM problem I saw in a few CI runs. The console
listed multiple docker soft lockups. Not sure what's going on.

**Comment by ncdc** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1412810

**Comment by smarterclayton** [comment]
I'm going to disable memcfg notifications until this is fixed.

**Comment by smarterclayton** [comment]
Except we don't have the flag yet until we pick up 1.5.2

**Comment by smarterclayton** [comment]
There is a disable patch, @soltysh on your PR you'll want to ignore that but you may need to default the flag to off in master.

**Comment by ncdc** [comment]
Why'd you reopen?

**Comment by soltysh** [comment]
@smarterclayton I've added test for `ExperimentalKernelMemcgNotification` being `false` in latest push, see [here](https://github.com/openshift/origin/pull/12481/commits/827c6567d28abf1ecd90bcfc277b7309e8a317fa#diff-e775429015fc39e89a7985115d301c46R129), is that sufficient?

**Comment by smarterclayton** [comment]
Just reopened so we have a place to track turning it to a flag.  I think we still want this in 3.5 if we can get the soft lock fixed - I'm hoping to get enough testing that we can turn it back on before thatz

**Comment by ncdc** [comment]
AFAIK the lockup is still an issue. The kube 1.6 rebase adds the `--experimental-kernel-memcg-notification` flag.

**Comment by ncdc** [comment]
Lowering priority for now to get this off the blocker list

**Comment by ncdc** [comment]
@derekwaynecarr @sjenning this is the origin issue for the memcg kernel issue. Feel free to close if you just want to manage this in the bz linked above.

**Comment by sjenning** [comment]
Yeah, this might be drawn out.  We can just open a PR to enable it when the kernel BZ is fixed.  

Or when we decide to disable THPs on origin :crossed_fingers:
