### ISSUE TITLE
"oc set image" broken

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#12468]
`oc set image` worked with an image reference before. Now it seems to take only imagestreamref. This is definitely issue of the client because if I downgrade it works. 

It works with v1.4.0-alpha.0+8134786 and before.

This is a breaking change for me and broke my pipelines.

This is useful feature because I can do:

```bash
$ export SHA=$(oc get is helloworld -o go-template --template='{{range .status.tags}}{{if eq .tag "latest"}}{{(index .items 0).dockerImageReference}}{{end}}{{end}}')
$ oc set image dc/helloworld-dev helloworld=${SHA}
```

##### Version
v1.5.0-alpha.1+71d3fa

##### Steps To Reproduce
1. oc set image dc/nodejs-ex nodejs-ex=172.30.216.109:5000/node/nodejs-ex@sha256:f42d7c977a60f67edd5a2f00706a071d720b73f37469f801ed45b7afbc7e9410

##### Current Result
error: unable to resolve image "172.30.216.109:5000/node/nodejs-ex@sha256:f42d7c977a60f67edd5a2f00706a071d720b73f37469f801ed45b7afbc7e9410" for container "nodejs-ex": invalid image stream tag "", must be of the form [NAMESPACE/]NAME:TAG

##### Expected Result
works as it did before

**Comment by mfojtik** [comment]
@tnozicka this is not a bug, the `oc set image` defaults the `--source` parameter to `istag`. What you are trying to do is to use `--source=docker`.

You can just add that parameter and everything should work :-) I think we always defaulted to `istag` there so I dunno why this broke recently?

**Comment by tnozicka** [comment]
@mfojtik thanks, I will migrate and add the flag.

**Comment by kargakis** [comment]
> I think we always defaulted to istag there so I dunno why this broke recently?

The virtue of running from master :)
