### ISSUE TITLE
openshift/origin-f5-router deployment fails due to improper API call to BIG-IP

### ISSUE THREAD

**Issue by yasensim** [openshift/origin#12462]
I am trying to install F5 router plugin to my F5 BIG-IP version 12.1.2
I get cannot create/modify published policy error message.
I dont have any policies defined in the F5 box.

##### Version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://osmaster.yasen.local:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4

---------------------------------------------------
Sys::Software Status
Volume  Product  Version    Build  Active    Status
---------------------------------------------------
HD1.1    BIG-IP   12.1.2  0.0.249     yes  complete

##### Steps To Reproduce
1. [step 1]
oadm router router --type=f5-router --external-host=10.29.15.88 --external-host-username=admin --external-host-password=mySecretPass1! --external-host-http-vserver=apps.yasen.local --external-host-https-vserver=https.apps.yasen.local --external-host-private-key=/root/.ssh/id_rsa --service-account=router --external-host-insecure=true
2. [step 2]

##### Current Result
router-deploy POD runs successfully, but router POD fails.
##### Expected Result
the F5 POD to run.
##### Additional Information
[root@osmaster ~]# oc logs po/router-1-q1a96
W0112 08:50:25.083445       1 f5.go:243] Strict certificate verification is *DISABLED*
error: Encountered an error on POST request to URL https://10.29.15.88/mgmt/tm/ltm/policy: HTTP code: 400; error from F5: 01071abb:3: Cannot create/modify published policy '/Common/openshift_insecure_routes' directly, try specifying a draft folder like '/Common/Drafts/openshift_insecure_routes'.

**Comment by yasensim** [comment]
I assume there is a difference in the APIs between the F5 version the plugin was developed and the new version I have. I can share my setup over webex/skype for faster resolution. Please let me know if that helps.

**Comment by ramr** [comment]
@yasensim  sorry for the delay replying - have been out sick. 
So, this looks like something changed in the new F5 versions 12.x - we probably need to add support for that. For now, a workaround would be to use the F5 Big-IP 11.6.x version. 
Am not sure a remote session would help, we probably need to debug/look at docs and fix this.

@rajatchopra  do you recall the version of F5 Big-IP version you tested the ramp node removal with?

**Comment by kargakis** [comment]
@openshift/sig-networking
