### ISSUE TITLE
[tests][extended] openshift pipeline build

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#12479]
flake from https://github.com/openshift/origin/pull/12467
jenkins URL https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/977/consoleFull#-152215633856cbb9a5e4b02b88ae8c2f77
```
• Failure [3623.146 seconds]
[builds][Slow] openshift pipeline build
/data/src/github.com/openshift/origin/test/extended/builds/pipeline.go:165
  Pipeline with maven slave
  /data/src/github.com/openshift/origin/test/extended/builds/pipeline.go:53
    Should build and complete successfully [It]
    /data/src/github.com/openshift/origin/test/extended/builds/pipeline.go:52

    Expected
        <bool>: false
    to be true

    /data/src/github.com/openshift/origin/test/extended/builds/pipeline.go:46
```

cc @gabemontero @bparees @csrwng

**Comment by PI-Victor** [comment]
p.s.: i have a hunch this is just network latency, rather than an actual issue, so feel free to bump down from p2 if it's too much.

**Comment by gabemontero** [comment]
This test is actually one that @csrwng added vs. me.  @PI-Victor may be correct that is is a network flake, given the build failure is a timeout and the pod event dump shows not build pods at all, but the test as currently constructed does not provide additional debug like our jenkins_plugin.go tests like dumping the contents of the jenkins pod, to conceivably see where things broke in launching the slave.

At best, I think we'll need to add the additional debug and reopen this issue if/when it shows up again.

@bparees FYI

**Comment by PI-Victor** [comment]
just FYI, this happened again.
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/985/consoleFull#123465095256cbb9a5e4b02b88ae8c2f77

**Comment by mmilata** [comment]
Seen here: https://ci.openshift.redhat.com/jenkins/job/origin_extended_build_tests/915/consoleFull#137011386456cbb9a5e4b02b88ae8c2f77

**Comment by gabemontero** [comment]
To complete the loop, when https://github.com/openshift/origin/pull/12440 finishes merging, the orchestration pipeline test will be commented out from pipeline.go.

Per discussion between @csrwng , @bparees , and myself, @csrwng has some optimization and rework in mind for this test, and we'll use this issue to track that to-do.

**Comment by bparees** [comment]
@gabemontero do we think this is fixed w/ your recent pipeline updates?

**Comment by gabemontero** [comment]
yes I do @bparees ... aside from the recent updates, that test and the associated diagnostic gathering have evolved quite a bit since this was first opened.  That also factors in to my thinking that the flavor of failure from this run is no longer pertinent.
