### ISSUE TITLE
Failures from gce cluster test runs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12475]
Against master https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/43/testReport/

https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/43/testReport/(root)/Extended/_k8s_io__Networking__k8s_io__Granular_Checks__Pods_should_function_for_intra_pod_communication__http__Conformance_/ is failing because of pod per node limits - perhaps we should increase them @ncdc?

https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/43/testReport/(root)/Extended/_registry__migration__manifest_migration_from_etcd_to_registry_storage_registry_can_get_access_to_manifest/ is panicking @legionus @miminar 

https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/43/testReport/(root)/Extended/_k8s_io__KubeletManagedEtcHosts_should_test_kubelet_managed__etc_hosts_file__Conformance_/ is failing after the rebase on the cluster or is net new @ncdc @soltysh 

https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/43/testReport/(root)/Extended/_k8s_io__Services_should_serve_a_basic_endpoint_from_pods__Conformance_/ is timing out because of #11016

**Comment by legionus** [comment]
> https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/43/testReport/(root)/Extended/_registry__migration__manifest_migration_from_etcd_to_registry_storage_registry_can_get_access_to_manifest/ is panicking 

Test failed because of https://github.com/openshift/origin/blob/master/test/extended/images/helper.go#L138 function. I can't say more without stack trace.

**Comment by ncdc** [comment]
> https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/43/testReport/(root)/Extended/_k8s_io__KubeletManagedEtcHosts_should_test_kubelet_managed__etc_hosts_file__Conformance_/

This passes for me in F25 but I have seen it fail in RHEL 7.3. I'll look into it (maybe SELinux?).

**Comment by ncdc** [comment]
@smarterclayton the /etc/hosts tests is failing because the VM is running docker 1.10.3. I see the same failure in RHEL with that docker version. It passes if you upgrade to docker 1.12.

**Comment by ncdc** [comment]
@smarterclayton according to @pmorie, that /etc/hosts test is going to fail on docker 1.10 due to a bug in docker. Apparently a side effect of specifying the seccomp profile is that multiple containers for the same pod (same ipc namespace) result in different mcs settings, when they should be identical. This has been fixed in docker 1.12. So it's going to keep failing for now, until your VMs are up to docker 1.12. Or we could put in a "skip if docker > 1.12" perhaps.

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/43/testReport/(root)/Extended/_k8s_io__Networking__k8s_io__Granular_Checks__Pods_should_function_for_intra_pod_communication__http__Conformance_/ is conflicting with kubelet cleanup which schedules max pods on all nodes - moving that to serial and also allowing global scheduling on that one.

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/pull/12488

**Comment by smarterclayton** [comment]
All of these are resolved
