### ISSUE TITLE
extended tests failing to clean up namespaces

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12487]
Extended.deploymentconfigs with multiple image change triggers [Conformance] should run a successful deployment with multiple triggers

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/10128/testReport/junit/(root)/Extended/deploymentconfigs_with_multiple_image_change_triggers__Conformance__should_run_a_successful_deployment_with_multiple_triggers/

```
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:142
Jan 13 13:50:55.401: Couldn't delete ns: "extended-test-cli-deployment-dgf3x-j2rk0": namespace extended-test-cli-deployment-dgf3x-j2rk0 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed (&errors.errorString{s:"namespace extended-test-cli-deployment-dgf3x-j2rk0 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed"})
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:353
```

@derekwaynecarr

**Comment by smarterclayton** [comment]
Isn't there an upstream report of this in 1.5?

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/151/testReport/junit/(root)/Extended/_k8s_io__Kubectl_client__k8s_io__Kubectl_run_pod_should_create_a_pod_from_an_image_when_restart_is_Never__Conformance_/

**Comment by derekwaynecarr** [comment]
My memory from 1.5 is that this has been relatively reliable, last major issue was related to pods not getting deleted....

**Comment by derekwaynecarr** [comment]
There are a couple incidences of this against 1.5 upstream:
https://github.com/kubernetes/kubernetes/issues/40391

The incidence is not super frequent, I think the priority should be reduced to match upstream.

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/1063/testReport/junit/(root)/Extended/deploymentconfigs_when_run_iteratively__Conformance__should_immediately_start_a_new_deployment/

**Comment by soltysh** [comment]
Another one in https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1070/testReport/junit/(root)/Extended/deploymentconfigs_with_enhanced_status__Conformance__should_include_various_info_in_status/

**Comment by smarterclayton** [comment]
I'm going to increase to 10 workers like upstream after discussion with
@liggitt
