### ISSUE TITLE
New failure mode in extended deployment test

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12490]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/10142/testReport/junit/(root)/Extended/deploymentconfigs_with_test_deployments__Conformance__should_run_a_deployment_to_completion_and_then_scale_to_zero/

**Comment by smarterclayton** [comment]
@mfojtik @kargakis

**Comment by kargakis** [comment]
```
Error from server (BadRequest): the server rejected our request for an unknown reason (get deploymentConfigs deployment-test)
```
Seems like the `kubectl logs` (https://github.com/kubernetes/kubernetes/issues/38774) breakage that got pulled in with the rebase.

**Comment by mfojtik** [comment]
It seems we have to pickup  https://github.com/kubernetes/kubernetes/pull/39831 once merged
