### ISSUE TITLE
build in vagrant vm failed due to "cannot allocate memory"

### ISSUE THREAD

**Issue by suibinz** [openshift/origin#12491]
env: vagrant vm set to 6G memory (on a 8G Macbook Pro)

##### Version
commit b7ed17562dee53ddcaa821d8be48cdda51e4e85b
Author: OpenShift Bot <dmcphers+openshiftbot@redhat.com>
Date:   Fri Jan 13 15:52:55 2017 -0500

##### Steps To Reproduce
```
[vagrant@localhost origin]$ make clean build
rm -rf _output
hack/build-go.sh
++ Building go targets for linux/amd64: cmd/openshift cmd/oc pkg/sdn/plugin/sdn-cni-plugin vendor/github.com/containernetworking/cni/plugins/ipam/host-local vendor/github.com/containernetworking/cni/plugins/main/loopback
\# github.com/openshift/origin/cmd/openshift
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /bin/gcc: cannot allocate memory

[ERROR] PID 2609: hack/common.sh:257: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )` exited with status 1.
[INFO] 		Stack Trace:
[INFO] 		  1: hack/common.sh:257: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )`
[INFO] 		  2: hack/build-go.sh:33: os::build::build_binaries
[INFO]   Exiting with code 1.
Makefile:41: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by stevekuznetsov** [comment]
What you're seeing is simply that you do not have enough RAM to do a full build. There is some change coming to how we do builds that I think will reduce the memory required, but that is coming in six to eight months. I'm not sure there is much more you can do today. @smarterclayton @csrwng @liggitt how much RAM do you guys give your Vagrant boxes to build with9?

**Comment by smarterclayton** [comment]
If you switch to Go 1.7 requirements drop back down to something more reasonable like 3-4gb.  It's just Go 1.6 that is the pig.

**Comment by suibinz** [comment]
Manually upgrade the vagrant vm to Go1.7 does make the build work. 
I am new to this project, but can look into packaging Go1.7 into the vagrant VM.

**Comment by smarterclayton** [comment]
Don't worry about that for right now - we're reducing the number of places
that are impacted so changes to vagrant won't be the best place.

On Jan 14, 2017, at 12:17 PM, ZUnshakable <notifications@github.com> wrote:

Manually upgrade the vagrant vm to Go1.7 does make the build work.
I am new to this project, but can look into packaging Go1.7 into the
vagrant VM.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12491#issuecomment-272637985>,
or mute the thread

**Comment by suibinz** [comment]
ok. So if one needs to use Virtualbox Vagrant VM for development, either wait for that chance, or manually upgrade Go to 1.7.

**Comment by smarterclayton** [comment]
Or allocate more memory, yes.  I believe 6.5GB is enough now.
