### ISSUE TITLE
Dynamic PV's not being attached to nodes on GCE

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#12500]
I'm seeing following StatefulSet extended failures (usually due to timeouts) both in master and my rebase PR (https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/984/consoleFull).

```
[Fail] [k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [It] should allow template updates 
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/petset.go:923

[Fail] [k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [It] should provide basic identity 
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/petset.go:923

[Fail] [k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [It] should handle healthy pet restarts during scale 
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/petset.go:923
```

@smarterclayton fyi

**Comment by smarterclayton** [comment]
Stateful set looks like it's failing because of:

```
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  10m		45s		36	{default-scheduler }			Warning		FailedScheduling	SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-pet-0", which is unexpected.

```

?

**Comment by soltysh** [comment]
This should be fixed in #12642.

**Comment by smarterclayton** [comment]
Failing on GCE now https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/188/testReport/junit/(root)/Extended/_k8s_io__StatefulSet__k8s_io__Basic_StatefulSet_functionality_should_provide_basic_identity/

**Comment by soltysh** [comment]
Looking...

**Comment by soltysh** [comment]
So the PR of mine changed `setup.sh` specifically to allow hostPath mounts, but gce tests is starting openshift differently. I need to update appropriate component for that. I'll send a PR shortly, I first need to figure out how it starts.

**Comment by smarterclayton** [comment]
You need to fix the tests.  They are not allowed to access hostpaths.

**Comment by smarterclayton** [comment]
probably by setting privileged like @pmorie and @ncdc did for the other tests.

**Comment by smarterclayton** [comment]
This looks like PVs are not being mounted correctly to nodes on 1.5 on GCE.  I see node status attached, the PVC is bound, but the actual disk in GCE is not being attached to the instance.  I'll need some help debugging from sos-storage.

**Comment by smarterclayton** [comment]
Disabling the tests while this is investigated https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/216/#showFailuresLink was the last failing test.

**Comment by smarterclayton** [comment]
This is from post 1.5.2 update.

**Comment by childsb** [comment]
@rootfs

**Comment by rootfs** [comment]
upstream pr created https://github.com/kubernetes/kubernetes/pull/41034

**Comment by rootfs** [comment]
@soltysh @smarterclayton fix in https://github.com/openshift/origin/pull/12835
