### ISSUE TITLE
should check kube-proxy urls extended test failure

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#12501]
I'm seeing this extended test failure both in master and current rebase PR (https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/984/consoleFull):
```
• Failure [63.262 seconds]
[k8s.io] Networking
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:826
  should check kube-proxy urls [It]
  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/networking.go:84

  At least two nodes necessary with an external or LegacyHostIP
  Expected
      <int>: 1
  to be >=
      <int>: 2

  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:476
```

@ncdc did you solve this problem last time?

**Comment by ncdc** [comment]
This is the test that requires 2 nodes. It runs as part of the networking
extended tests. You tried to pick the upstream pull that skips instead of
fails, except it skips in our environments because of how the skip code is
written.

**Comment by ncdc** [comment]
To be more specific, we should only fail this test if we are running test/extended/networking.sh and there are not at least 2 nodes (that would indicated a problem with the dind cluster setup). In other scenarios, if we only have 1 node, we should skip this test.

**Comment by soltysh** [comment]
I remember cherry-picking a fix disabling those, but you reverted those, since it disabled more than we wanted. Which basically means this is a known problem and I'll let @openshift/networking team handle that :)

**Comment by soltysh** [comment]
I don't recall seeing it recently.
/close
