### ISSUE TITLE
newapp.go:887] Unable to check for circular build input: Unable to check for circular build input/outputs: imagestreams "php" not found

### ISSUE THREAD

**Issue by shiywang** [openshift/origin#12513]
[provide a description of the issue]
newapp.go:887] Unable to check for circular build input: Unable to check for circular build input/outputs: imagestreams "php" not found

##### Version
 oc version
oc v1.5.0-alpha.1+d4533b6-282
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Current Result
[root@ip-172-18-4-193 ~]# oc get template
NAME                    DESCRIPTION                                                                        PARAMETERS     OBJECTS
cakephp-mysql-example   An example CakePHP application with a MySQL database. For more information ab...   19 (4 blank)   8
[root@ip-172-18-4-193 ~]# oc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-rhel7.json 
imagestream "ruby" created
imagestream "nodejs" created
imagestream "perl" created
imagestream "php" created
imagestream "python" created
imagestream "mysql" created
imagestream "mariadb" created
imagestream "postgresql" created
imagestream "mongodb" created
imagestream "redis" created
imagestream "jenkins" created
[root@ip-172-18-4-193 ~]# oc new-app --template=cakephp-mysql-example
--> Deploying template "lgproj1/cakephp-mysql-example" to project lgproj1

     CakePHP + MySQL (Ephemeral)
     ---------
     An example CakePHP application with a MySQL database. For more information about using this template, including OpenShift considerations, see https://github.com/openshift/cakephp-ex/blob/master/README.md.

WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing.

     The following service(s) have been created in your project: cakephp-mysql-example, mysql.

For more information about using this template, including OpenShift considerations, see https://github.com/openshift/cake-ex/blob/master/README.md.

     * With parameters:
        * Name=cakephp-mysql-example
        * Namespace=openshift
        * Memory Limit=512Mi
        * Memory Limit (MySQL)=512Mi
        * Git Repository URL=https://github.com/openshift/cakephp-ex.git
        * Git Reference=
        * Context Directory=
        * Application Hostname=
        * GitHub Webhook Secret=f5MW3J3hrUKtokySrihHhaqXyT5gBWB4jKS0UqbJ # generated
        * Database Service Name=mysql
        * Database Engine=mysql
        * Database Name=default
        * Database User=cakephp
        * Database Password=6F2VJWwS3sSX50TB # generated
        * CakePHP secret token=Zr3oi1yqcCJBPJL5bvQDmoO0wJtUJT2qf2AGKH4gFfNwAN8fC3 # generated
        * CakePHP Security Salt=HtQESyFtdCuAg3aG7ynsdPdnIIidhas7uiec2ljn # generated
        * CakePHP Security Cipher Seed=366460425660174572450622482886 # generated
        * OPcache Revalidation Frequency=2
        * Custom Composer Mirror URL=

W0116 21:31:45.684672   20632 newapp.go:887] Unable to check for circular build input: Unable to check for circular build input/outputs: imagestreams "php" not found
--> Creating resources ...
    error: secrets "cakephp-mysql-example" already exists
    service "cakephp-mysql-example" created
    route "cakephp-mysql-example" created
    imagestream "cakephp-mysql-example" created
    buildconfig "cakephp-mysql-example" created
    deploymentconfig "cakephp-mysql-example" created
    service "mysql" created
    deploymentconfig "mysql" created
--> Failed

##### Expected Result
all success

**Comment by bparees** [comment]
1) you need to create the imagestreams in the openshift namespace since that is where the template references them.  it looks like you created them in your own project.  (alternatively you can set the namespace parameter on the template to tell it what namespace to look in)

2) Based on `error: secrets "cakephp-mysql-example" already exists` you had already created a secret in your project with this name, which is going to cause problems, you need to delete it.
