### ISSUE TITLE
protobuff generation script fails check for 3.1 protoc binary

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#12512]
is it safe to generate with the latest protoc bin?
https://github.com/google/protobuf/releases/tag/v3.1.0

currently the check fails for 3.1
https://github.com/openshift/origin/blob/master/hack/update-generated-protobuf.sh#L4-L5

or do we follow upstream in this case and leave it as it is?

@smarterclayton @bparees

**Comment by smarterclayton** [comment]
We have not tested with 3.1.  If it generates no changes when you run, you
can expand the check.

**Comment by bparees** [comment]
the output is slightly different.
