### ISSUE TITLE
oc cluster up output has gotten too unwieldy

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12531]
It's telling me things I don't care about.  Should be about half the total output, and only slow steps or important information steps should be shown.

**Comment by mfojtik** [comment]
Or have `--verbose` flag for those who care?

**Comment by smarterclayton** [comment]
We already have loglevel, any output not useful to the user to convey
failures, general progress during slow operations, or meaning should be
removed.  The different checks we do aren't something the user cares about
mots of the time.

**Comment by LalatenduMohanty** [comment]
@csrwng I think this issue should be closed now Or do you guys close these automatically as part of release process.

**Comment by csrwng** [comment]
@LalatenduMohanty thanks for the reminder. Closing
