### ISSUE TITLE
How to run openshift as pod in an existing k8s cluster

### ISSUE THREAD

**Issue by xiaoping378** [openshift/origin#12534]
Hi ,
if i have an existing k8s cluster, how to use the features added by openshift ?
can i use command oc to make it available?

**Comment by sdodson** [comment]
Origin today is not capable of running on top of kubernetes. Once origin is capable we'll be working on the installation.

**Comment by xiaoping378** [comment]
Thanks for the answer

**Comment by xiaoping378** [comment]
any plan to make origin is capable to run as pod in  k8s cluster ?
