### ISSUE TITLE
Copying annotations from DeploymentConfig to ReplicationController

### ISSUE THREAD

**Issue by lulf** [openshift/origin#12539]
I have some custom annotations added to a DeploymentConfig and would like for them to be propagated/copied to the ReplicationController that is created. Currently, only the labels of the DeploymentConfig are propagated.

##### Version
oc v1.3.2
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Create DeploymentConfig with custom annotations

##### Current Result
ReplicationController does not contains annotations

##### Expected Result
ReplicationController contains annotations

##### Additional Information

Example reproducing the issue:

{
  "apiVersion": "v1",
  "kind": "DeploymentConfig",
  "metadata": {
    "name": "test",
    "labels": {
      "example": "label1"
    },
    "annotations": {
      "example": "annotation1"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "example": "labelselect"
    },
    "template": {
      "metadata": {
        "labels": {
          "example": "labelselect"
        }
      },
      "spec": {
        "containers": [
          {
            "image": "fedora:24",
            "name": "test"
          }
        ]
      }
    }
  }
}

**Comment by mfojtik** [comment]
Isn't:

```
$ oc annotate rc --selector=openshift.io/deployment-config.name=<DCNAME> foo=bar
```

enough?

**Comment by kargakis** [comment]
@mfojtik what if you need to propagate 10 different annotations with various custom values?

**Comment by kargakis** [comment]
Btw note that this already happens in upstream Deployments (although they don't propagate labels).

**Comment by mfojtik** [comment]
@kargakis you can specify as many annotations as you want?

**Comment by lulf** [comment]
I'd like to avoid doing special handling on the client side to achieve this, and I think it would be consistent the way labels are propagated.

**Comment by kargakis** [comment]
@mfojtik yes but what about the custom values in those annotations? For example, serialized json.

**Comment by mfojtik** [comment]
@lulf do you expect the annotations to be propagated to all RC or just the active one?

**Comment by mfojtik** [comment]
@kargakis go templates to the rescue? ;-) (agree it is ugly)

**Comment by kargakis** [comment]
@mfojtik annotations will be propagated only during creation of the rc.

**Comment by mfojtik** [comment]
@kargakis how do you pick up which annotations should be propagated?

**Comment by kargakis** [comment]
same way as labels, you don't

**Comment by lulf** [comment]
@mfojtik I'd expect it to be done the same way as for labels basically

**Comment by mfojtik** [comment]
if I create stuff with `new-app`, we get:

```
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
```

will this annotation be copied to RC?

**Comment by kargakis** [comment]
There is no special casing involved but we could possibly add if we want to
