### ISSUE TITLE
build durations are wrong

### ISSUE THREAD

**Issue by bparees** [openshift/origin#12549]
The build.status.duration field is reporting incorrect values, the values are much too small.

It appears the Decorator being used to set the value is called immediately after the build is created, whereas it should only be called when the build completes.  I'm not even sure why we're using a Decorator to set this value instead of setting when we update the build status to complete.

https://github.com/openshift/origin/blob/master/pkg/build/registry/build/strategy.go#L27

Near as i can tell, that code will result in the Duration being set to currentTime-creationTime, the first time the decorator is invoked(which is when exactly? but certainly it's not when the build is complete).

I'm also not really sure why we even have a Duration field, we should just be calculating it based on the status.StartTime and status.CompletionTime, anytime we need to display it.

@smarterclayton @csrwng any chance you know some of the history behind why we're doing this this way?

**Comment by smarterclayton** [comment]
I don't think we should have a duration field, although both start time and
completion time are questionable because there is no guarantee the clock
for measuring those is the same (whereas duration could come from the
actual build).  Either way I hate the duration field as a "duration" (i
would have vetoed that if i caught it in time).  We should only have two
fields - start + complete, or start + duration.

**Comment by bparees** [comment]
Right, well we're stuck with it now, right? But I still don't understand
why it's being set in the way it is(via the decorator). That's what I was
hoping for some clarification on.

(we can also update the describe function to calculate duration instead of
using the field. Apparently that's what the console does because it shows a
proper value.)


Ben Parees | OpenShift

**Comment by csrwng** [comment]
Looks like the decorator was introduced when we refactored the etcd storage for builds to use generic etcd: https://github.com/openshift/origin/pull/2204
I don't see a reason not to fix it.

**Comment by bparees** [comment]
> I don't think we should have a duration field, although both start time and completion time are questionable because there is no guarantee the clock for measuring those is the same (whereas duration could come from the actual build).

it could, maybe, but today it doesn't, it comes from the start and completion time, so it's definitely not adding any accuracy.
