### ISSUE TITLE
`oc cluster up` fails to bring up registry and router on RHEL7.3

### ISSUE THREAD

**Issue by surajssd** [openshift/origin#12546]
$subject.

registry and router fail
```bash
[root@ose-vm4 ~]# oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-deploy   0/1       Error     0          17m
router-1-deploy            0/1       Error     0          17m
```
registry deploy logs
```bash
[root@ose-vm4 ~]# oc logs docker-registry-1-deploy
error: couldn't get deployment docker-registry-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp 172.30.0.1:443: getsockopt: no route to host
```
router deploy logs
```bash
[root@ose-vm4 ~]# oc logs router-1-deploy
error: couldn't get deployment router-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/router-1: dial tcp 172.30.0.1:443: getsockopt: no route to host
[root@ose-vm4 ~]# 
```

##### Version

```bash
[root@ose-vm4 ~]# oc version
oc v1.3.2
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.70.48.31:8443
openshift v1.3.2
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce

Download oc release of above version and run `oc cluster up`

##### Current Result

Registry and Router not running

##### Expected Result

Registry and Router running

##### Additional Information

docker version
```bash
# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.x86_64
 Go version:      go1.6.2
 Git commit:      429be27-unsupported
 Built:           Fri Nov 18 17:03:44 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.x86_64
 Go version:      go1.6.2
 Git commit:      429be27-unsupported
 Built:           Fri Nov 18 17:03:44 2016
 OS/Arch:         linux/amd64
```

SELinux is in `Enforcing` mode right now.

**Comment by surajssd** [comment]
After reporting this issue updated machine and now:

```bash
# docker version
Client:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Wed Jan 11 17:53:20 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Wed Jan 11 17:53:20 2017
 OS/Arch:         linux/amd64
```

and still the problem persists!

**Comment by ncdc** [comment]
Please try flushing your iptables rules and report back if this fixes it:

```bash
oc cluster down
sudo systemctl stop docker
sudo iptables -F
sudo iptables -t nat -F
sudo systemctl start docker
oc cluster up
```

**Comment by 201sandeep** [comment]
I am facing the same issue, it is not working... even though i am facing a strange issue

When i am trying to run 

#oc cluster down 

This command finishes then and there but nothing happens i can still see the ports are still used and openshift processes are still running

[root@openshift-vm1 ~]# ps aux | grep -i openshift
root      84418  6.4 12.1 11040768 227892 ?     Ssl  03:08   0:14 /usr/bin/openshift start master --config=/etc/origin/master/master-config.yaml --loglevel=2
root      84481  1.2  3.4 588756 64640 ?        Ssl  03:08   0:02 /usr/bin/openshift start node --config=/etc/origin/node/node-config.yaml --loglevel=2
root      85073  0.0  0.0 112648   968 pts/0    S+   03:12   0:00 grep --color=auto -i openshift
[root@openshift-vm1 ~]# netstat -lnpt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd
tcp        0      0 0.0.0.0:8053            0.0.0.0:*               LISTEN      84418/openshift
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1740/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2448/master
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      84418/openshift
tcp6       0      0 :::10250                :::*                    LISTEN      84481/openshift
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd
tcp6       0      0 :::22                   :::*                    LISTEN      1740/sshd
tcp6       0      0 :::7001                 :::*                    LISTEN      84418/openshift
tcp6       0      0 ::1:25                  :::*                    LISTEN      2448/master
tcp6       0      0 :::4001                 :::*                    LISTEN      84418/openshift
[root@openshift-vm1 ~]#

[root@openshift-vm1 ~]#
[root@openshift-vm1 ~]# oc get nodes
NAME                        STATUS                     AGE
openshift-vm1.example.com   Ready,SchedulingDisabled   13d
openshift-vm2.example.com   Ready                      13d
[root@openshift-vm1 ~]# oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-5-deploy   0/1       Pending   0          13d
registry-console-1-2v8xe   1/1       Running   2          9d
router-1-deploy            0/1       Pending   0          13d
[root@openshift-vm1 ~]#

both registry and router are still in pending state, Please help someone.. Please

**Comment by 201sandeep** [comment]
@surajssd can you please paste output of #oc get nodes ?

**Comment by surajssd** [comment]
@ncdc this helped thanks a lot :+1:

**Comment by surajssd** [comment]
@201sandeep oops sorry didn't see your comment, re-opening for you!

**Comment by 201sandeep** [comment]
@surajssd no prob you can close it, i will raise a new case. Thanks
