### ISSUE TITLE
Flake: executing oc logs kubectl-with-token

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#12540]
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10167/consoleFull:

```
FAILURE after 0.223s: test/end-to-end/core.sh:375: executing 'oc logs kubectl-with-token' expecting success and text 'Using in-cluster configuration': the output content test failed
Standard output from the command:
NAME                 READY     STATUS    RESTARTS   AGE
kubectl-with-token   1/1       Running   0          5s
```

@stevekuznetsov it looks like our testing framework got crazy, the output looks like from `oc get` rather than `oc logs`, is it possible?

**Comment by jim-minter** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10169/consoleFull#11056859515762928fe4b031e1b25ced2a may be similar?

```
FAILURE after 0.221s: test/end-to-end/core.sh:363: executing 'oc logs cli-with-token' expecting success and text 'Using in-cluster configuration': the output content test failed
Standard output from the command:
In project test on server https://172.30.0.1:443
pod/cli-with-token runs openshift/origin:5e49b66
1 warning identified, use 'openshift cli status -v' to see details.

There was no error output from the command.
```

**Comment by stevekuznetsov** [comment]
Very weird. I'll take a look.

**Comment by stevekuznetsov** [comment]
@smarterclayton @ncdc are we running any of these tests in parallel? The output caches are not thread-safe in `os::cmd`.

**Comment by stevekuznetsov** [comment]
And is that a change that may have come from the rebase? This is really wonky.

**Comment by ncdc** [comment]
Haven't we been running the ginkgo tests in parallel for a while now? Not sure about the others.

**Comment by stevekuznetsov** [comment]
@ncdc I meant `os::cmd` tests in parallel

**Comment by ncdc** [comment]
I don't know

**Comment by stevekuznetsov** [comment]
Wait ... these are logs from pods with the CLI inside of them. We are seeing the CLI output from within the pod be incorrect -- not use the in-cluster configuration, etc. This isn't what we thought.

**Comment by stevekuznetsov** [comment]
Closing for https://github.com/openshift/origin/issues/12558
