### ISSUE TITLE
SelfLink is not correct for root-scoped resources

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#12553]
[provide a description of the issue]
SelfLink are not correct of User resource type
##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [step 1] launch the openshift and login using user haowang@redhat.com
2. [step 2] get the user using cluster admin
oc get User haowang@redhat.com -o json
{
    "apiVersion": "v1",
    "groups": null,
    "identities": [
        "anypassword:haowang@redhat.com"
    ],
    "kind": "User",
    "metadata": {
        "creationTimestamp": "2017-01-19T02:37:24Z",
        "name": "haowang@redhat.com",
        "resourceVersion": "629",
        **"selfLink": "/oapi/v1/usershaowang%40redhat.com",**
        "uid": "3596af1e-ddf0-11e6-a9e2-0ef2a44bfb8e"
    }
}

##### Current Result
the selflink of user is not correct, lack a slash after the "users"
##### Expected Result
should be /oapi/v1/user/haowang@redhat.com

**Comment by ncdc** [comment]
Need to pull in https://github.com/kubernetes/kubernetes/pull/37686

**Comment by enj** [comment]
@ncdc will we ge the fix in the 1.6.1 rebase?

**Comment by ncdc** [comment]
It hasn't been fixed upstream yet

**Comment by ncdc** [comment]
There are 3 competing PRs to fix it. I've asked @deads2k to drive one of them home.

**Comment by ncdc** [comment]
Fix: https://github.com/openshift/origin/pull/14001
