### ISSUE TITLE
Improve ImageStreamImport behaviour with unsecured registries

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#12562]
oc debug needs to be able to obtain the command/entrypoint from an image given its reference.  It is proposed that oc debug use ImageStreamImport to fetch the image docker metadata.  Currently, oc debug cannot tell whether the image ref it has is hosted on an insecure registry or not, so it doesn't know whether to set insecure: true or not when it does this.

Setting insecure always to false would mean that oc debug couldn't print the command/entrypoint of an image built using Origin and hosted on an insecure local registry.  Setting it always to true creates a security risk.

So far there are two suggestions for how to fix this:
1) if a requested image ref received by ImageStreamImport is already known to origin as an Image, just return it directly without querying the remote registry.  Difficulties: how to tell the receiver is authorized to view the image metadata; invalidation if the remote registry no longer has the image (although this actually helps the oc debug case)

2) Docker specifically has a --insecure-registry= configuration.  If ImageStreamImport receives a request against a matching registry, it should upgrade insecure to true.  Notes: a) if the master already requires a local docker, the local docker configuration can be retrieved by the /info API call.  Otherwise it would be necessary to make --insecure-registry= a master configurable. b) it should be considered whether as a result of this, the insecure flag could be removed altogether?

This issue blocks bz1392764 / #12559.

@smarterclayton 
@bparees 
@miminar

**Comment by smarterclayton** [comment]
> how to tell the receiver is authorized to view the image metadata

You can get access to the authorizer in the context and check permissions for that user against the image stream tag or image stream image.

**Comment by jim-minter** [comment]
@smarterclayton I don't believe this works because the imagestream is not known.

**Comment by smarterclayton** [comment]
The image stream would be <registryname>/X/X (available from the strategy)

**Comment by jim-minter** [comment]
An option 3. is for oc debug to be given a --insecure option, which it could to populate the insecure: field (not that this option gets my vote)

**Comment by jim-minter** [comment]
Discussed this with @smarterclayton the other day - I think the outcome was that the imagestreamimportservice should be enhanced such that if it receives a request for metadata for an image hosted in OpenShift's registry, it is able to return the metadata to the user direct from etcd, subject to access control, without having to query out to the registry.

**Comment by bparees** [comment]
trello'd https://trello.com/c/SmuU6O2Y
