### ISSUE TITLE
'oc exec -it' fails on MINGW32

### ISSUE THREAD

**Issue by f-w** [openshift/origin#12568]
Hi,
I use MINGW32 (installed by gitbash) on Windows 7 for all of my devops and coding. oc works except for `oc exec -it` when I want to connect to pod. In such case I have to switch to DOS. The issue probably exists in kubernetes so I add a reference https://github.com/kubernetes/kubernetes/issues/37471.

Thanks for looking into it!

##### Version

```
oc v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.99.101:8443
openshift v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
On MINGW32
```
x@laptop MINGW32 /
$ oc exec -it elasticsearch-3-c0oql bash
Unable to use a TTY - input is not a terminal or the right kind of file
```
Same command run from DOS on the same pc works.

**Comment by ncdc** [comment]
Does `docker exec -it` work in mingw?

cc @csrwng

**Comment by f-w** [comment]
@ncdc. Good point. No, it doesn't. Submitted https://github.com/docker/toolbox/issues/624
