### ISSUE TITLE
origin upgrade (1.3.1 --> 1.3.3) fail.

### ISSUE THREAD

**Issue by warmchang** [openshift/origin#12574]
##### Version
[root@master openshift-ansible]# origin version
origin v1.3.1
kubernetes v1.3.0+52492b4
etcd 2.3.0+git

##### Steps To Reproduce
1. run "ansible-playbook playbooks/byo/openshift-cluster/upgrades/v3_3/upgrade.yml".
2. the  [Generate etcd backup] task fail:
> TASK [Generate etcd backup] ****************************************************
> fatal: [master.fin.com]: FAILED! => {"changed": true, "cmd": ["etcdctl", "backup", "--data-dir=/var/lib/origin/openshift.local.etcd", "--backup-dir=/var/lib/origin/etcd-backup-20170120115918"], "delta": "0:00:00.244160", "end": "2017-01-20 11:59:19.224973", "failed": true, "rc": 1, "start": "2017-01-20 11:59:18.980813", "stderr": "2017-01-20 11:59:19.056214 W | snap: skipped unexpected non snapshot file db\n2017-01-20 11:59:19.122903 W | wal: ignored file 5.tmp in wal\n2017-01-20 11:59:19.221939 I | walpb: crc mismatch", "stdout": "", "stdout_lines": [], "warnings": []}
>         to retry, use: --limit @/root/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_3/upgrade.retry

Anybody had the same problem?

**Comment by sdodson** [comment]
You have embedded etcd, the playbooks should upgrade you to the latest version of etcd available and use that to perform the backup. For Fedora 25 or RHEL7 that should be etcd 3.0.15 and this problem shouldn't occur. What OS are you running?

**Comment by warmchang** [comment]
hi, @sdodson 
The OS is CentOS, the original version is CentOS 7.2(1511). After installation (run yum update before install openshift), it updated to 7.3(1611).

> [root@node1 ~]# uname -a
> Linux node1.fin.com 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> [root@node1 ~]# cat /etc/redhat-release
> CentOS Linux release 7.3.1611 (Core)

Whether it is caused because the version 1.3.3 is not ready in the CentOS repo?
> [root@node1 ~]# yum info origin
> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
>  * base: mirrors.aliyun.com
>  * extras: mirrors.aliyun.com
>  * updates: mirrors.aliyun.com
> Installed Packages
> Name        : origin
> Arch        : x86_64
> Version     : 1.3.1
> Release     : 1.el7
> Size        : 204 M
> Repo        : installed
> From repo   : centos-openshift-origin
> Summary     : Open Source Container Management by Red Hat
> URL         : https://github.com/openshift/origin
> License     : ASL 2.0
> Description : Origin is a distribution of Kubernetes optimized for enterprise application
>             : development and deployment, used by OpenShift 3 and Atomic Enterprise. Origin
>             : adds developer and operational centric tools on top of Kubernetes to enable
>             : rapid application development, easy deployment and scaling, and long-term
>             : lifecycle maintenance for small and large teams and applications.

**Comment by warmchang** [comment]
Update successfully to use release-1.4 branch by @sdodson 's advice. https://github.com/openshift/openshift-ansible/issues/3302
Close this issue.
