### ISSUE TITLE
Rapid actions on a DC end up messing its scale

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#12589]
https://github.com/openshift/origin/issues/11004#issuecomment-274122501

This came out of a test that creates and deletes the same config a bunch of times. I haven't looked closely but I would expect selector generation using the DC uid would solve this.

@smarterclayton @mfojtik

**Comment by mfojtik** [comment]
@kargakis selector generation for what? can you elaborate?

**Comment by kargakis** [comment]
@mfojtik once a DC is created, add its UID in its selector. Not sure if this is feasible because the uid is generated once the DC is created so maybe there could be a way to wait for the selector to contain the uid before proceeding to create RCs.

**Comment by kargakis** [comment]
Or potentially the uid is added just in the RCs selectors. The DC controller can also switch to use the scale endpoint for scaling RCs. Does that support preconditions?

**Comment by kargakis** [comment]
https://github.com/kubernetes/community/pull/256

**Comment by kargakis** [comment]
Now I think this will be fixed once we add owner references in RCs.
