### ISSUE TITLE
Identities missing after 1.3 -> 1.4 upgrade

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#12598]
Post upgrade all user identities and mappings seem to be lost (users exist but identities missing)
Using mappingMethod=lookup

Will update

**Comment by liggitt** [comment]
thanks for the report. it looks like the computed keypath for identities in etcd was accidentally changed during the 1.4 development cycle. will be corrected to refer to the 1.3 location and a hotfix will be released.

**Comment by andrewklau** [comment]
I already ran migration scripts to recreate all the identities, will there be a merge or will they be deleted?

**Comment by liggitt** [comment]
the old identities are still intact in etcd under the old key

with the fix in https://github.com/openshift/origin/issues/12606, the old identities would be visible again, and any new ones you created under the new key would be inert.

**Comment by andrewklau** [comment]
Thanks for the clarification. I can just recreate the identities because we already manage them externally. 

This should clear out the soon to be redundant identities? after #12606 is included in a released
`etcdctl rm --recursive /openshift.io/identities`

**Comment by liggitt** [comment]
https://github.com/openshift/origin/releases/tag/v1.4.1 has been released which resolves this issue.

Identity objects created while running 1.4.0 are located in etcd under the `/openshift.io/identities/$name` key. They can be copied to the `/openshift.io/useridentities/$name` key using etcdctl to make them available in 1.4.1

EgressNetworkPolicy objects created while running 1.4.0 are located in etcd under the `/openshift.io/egressnetworkpolicies/$namespace/$name` key. They can be copied to the `/openshift.io/registry/egressnetworkpolicy/$namespace/$name` key using etcdctl to make them available in 1.4.1.
