### ISSUE TITLE
RepresenterError: cannot represent an object: htpasswd_auth

### ISSUE THREAD

**Issue by john-deng** [openshift/origin#12594]
I faced the issue that RepresenterError: cannot represent an object: htpasswd_auth when install openshift origin 1.4, how to solve this issue?

[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]
openshift origin 1.4

##### Steps To Reproduce
1. [step 1]
`
# here is the inventory
# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd
nfs

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
openshift_release=v1.4
openshift_image_tag=v1.4.0
openshift_install_examples=true
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

#docker_version="1.12.6"

osm_use_cockpit=true
osm_cockpit_plugins=['cockpit-kubernetes']

containerized=true

openshift_public_hostname=console.openshift.origin
openshift_master_default_subdomain=app.console.openshift.origin

openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_nfs_directory=/exports
openshift_hosted_registry_storage_nfs_options='*(rw,root_squash)'
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=40Gi

openshift_hosted_metrics_deploy=false

[masters]
console.openshift.origin openshift_schedulable=true

# host group for etcd
[etcd]
console.openshift.origin

[nfs]
console.openshift.origin #openshift_schedulable=true
# host group for nodes, includes region info
[nodes]
console.openshift.origin openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=true

# end of the inventory
`
2. [step 2]

# run ansible playbook
ansible-playbook openshift-ansible/playbooks/byo/config.yml -v

##### Current Result
`
TASK [openshift_master : Restore Master Proxy Config Options] ******************
task path: /root/install-centos-server2/openshift-ansible/roles/openshift_master/tasks/systemd_units.yml:148

TASK [openshift_master : Restore Master AWS Options] ***************************
task path: /root/install-centos-server2/openshift-ansible/roles/openshift_master/tasks/systemd_units.yml:155

TASK [openshift_master : Create session secrets file] **************************
task path: /root/install-centos-server2/openshift-ansible/roles/openshift_master/tasks/main.yml:139
<console.openshift.origin> ESTABLISH SSH CONNECTION FOR USER: root
<console.openshift.origin> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r console.openshift.origin '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414 `" && echo ansible-tmp-1484988798.48-163584992130414="` echo ~/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414 `" ) && sleep 0'"'"''
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/files/stat.py
<console.openshift.origin> PUT /tmp/tmpG4OQqI TO /root/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414/stat.py
<console.openshift.origin> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[console.openshift.origin]'
<console.openshift.origin> ESTABLISH SSH CONNECTION FOR USER: root
<console.openshift.origin> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r console.openshift.origin '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414/ /root/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414/stat.py && sleep 0'"'"''
<console.openshift.origin> ESTABLISH SSH CONNECTION FOR USER: root
<console.openshift.origin> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt console.openshift.origin '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414/stat.py && sleep 0'"'"''
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/files/file.py
<console.openshift.origin> PUT /tmp/tmpzR_8YO TO /root/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414/file.py
<console.openshift.origin> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[console.openshift.origin]'
<console.openshift.origin> ESTABLISH SSH CONNECTION FOR USER: root
<console.openshift.origin> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r console.openshift.origin '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414/ /root/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414/file.py && sleep 0'"'"''
<console.openshift.origin> ESTABLISH SSH CONNECTION FOR USER: root
<console.openshift.origin> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt console.openshift.origin '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414/file.py && sleep 0'"'"''
<console.openshift.origin> ESTABLISH SSH CONNECTION FOR USER: root
<console.openshift.origin> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r console.openshift.origin '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1484988798.48-163584992130414/ > /dev/null 2>&1 && sleep 0'"'"''
ok: [console.openshift.origin] => {
    "changed": false,
    "diff": {
        "after": {
            "path": "/etc/origin/master/session-secrets.yaml"
        },
        "before": {
            "path": "/etc/origin/master/session-secrets.yaml"
        }
    },
    "gid": 0,
    "group": "root",
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "delimiter": null,
            "dest": "/etc/origin/master/session-secrets.yaml",
            "diff_peek": null,
            "directory_mode": null,
            "follow": true,
            "force": false,
            "group": "root",
            "mode": 384,
            "original_basename": "sessionSecretsFile.yaml.v1.j2",
            "owner": "root",
            "path": "/etc/origin/master/session-secrets.yaml",
            "recurse": false,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": null,
            "unsafe_writes": null,
            "validate": null
        }
    },
    "mode": "0600",
    "owner": "root",
    "path": "/etc/origin/master/session-secrets.yaml",
    "secontext": "system_u:object_r:etc_t:s0",
    "size": 147,
    "state": "file",
    "uid": 0
}

TASK [openshift_master : set_fact] *********************************************
task path: /root/install-centos-server2/openshift-ansible/roles/openshift_master/tasks/main.yml:151
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 443, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 248, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 373, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 427, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 383, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 583, in do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/root/install-centos-server2/openshift-ansible/filter_plugins/openshift_master.py", line 500, in translate_idps
    return yaml.safe_dump([idp.to_dict() for idp in idp_list], default_flow_style=False)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 218, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 215, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 101, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: htpasswd_auth

fatal: [console.openshift.origin]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/root/install-centos-server2/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
console.openshift.origin           : ok=250  changed=9    unreachable=0    failed=1
localhost                  : ok=11   changed=9    unreachable=0    failed=0
`
##### Expected Result
failed=0

##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by derdanu** [comment]
+1

**Comment by john-deng** [comment]
It is the issue that caused by ansible 2.2.1, so close it.

see the solution here: https://github.com/openshift/openshift-ansible/issues/3146
