### ISSUE TITLE
Pushing image fails when using OpenShift eclipse plugin

### ISSUE THREAD

**Issue by magick93** [openshift/origin#12603]
I'm trying to push docker image to remote OpenShift using Eclipse OpenShift plugin.

##### Version
oc version
oc v1.3.2
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.hughestech.co:8443
openshift v1.3.2
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Fill in details in 
![image](https://cloud.githubusercontent.com/assets/2173213/22187024/65772c9c-e0ff-11e6-80fb-a4fd30c6508a.png)

##### Current Result

![image](https://cloud.githubusercontent.com/assets/2173213/22187017/465f7c38-e0ff-11e6-845b-ac0eb8e21c9d.png)
##### Expected Result

I expect to be able to push to remote docker register in OpenShift cluster

**Comment by bdshadow** [comment]
Created JIRA in Jboss Tools: https://issues.jboss.org/browse/JBIDE-23771

**Comment by bdshadow** [comment]
@magick93 could you please provide information about the version of the Openshift Plugin?
Click `Help -> Installation Details`, in Installed Software tab find openshift plugin and check it in the version column, please

**Comment by magick93** [comment]
![image](https://cloud.githubusercontent.com/assets/2173213/22211205/a0319b82-e18c-11e6-9a94-f6c33c5378b1.png)

**Comment by bdshadow** [comment]
@magick93 according to the comment in the JIRA by @jeffmaury:

> This is a known issue. Pushing an image to OpenShift registry does not work if you are not working with the OpenShift docker daemon. This happens when the OpenShift env (ie the registry) is using a non standard certificate (self signed,....) that cannot be validated by the Docker daemon

**Comment by jcantrill** [comment]
Closing in favor of jira issue
