### ISSUE TITLE
Portal's are not namespaced

### ISSUE THREAD

**Issue by brenton** [openshift/origin#1261]
If I run `openshift ex registry --create` today it will create a service in the default namespace called docker-registry.  If I then create a project and create a service in that probject with the same name as the (but different IP) it will shadow the original one thereby breaking my registry.

**Comment by brenton** [comment]
@derekwaynecarr, @smarterclayton, do you happen to know if there is upcoming work in kubernetes to prevent this from happening?

**Comment by smarterclayton** [comment]
You said "create a project and a service in that project" it will shadow it - docker-registry shouldn't be showing up in other projects anyway?

**Comment by brenton** [comment]
That was really just an example.  I hit this in another case where two templates I used happen to create services with the same name.  What I'm trying to say is that if anyone in another namespace creates a service that happens to match the name of someone else's it will break their service's iptables nat rule.

**Comment by ncdc** [comment]
@brenton is this the same issue (upstream)? https://github.com/GoogleCloudPlatform/kubernetes/issues/4288

**Comment by brenton** [comment]
That is exactly issue.  My github issue search-fu failed me.

**Comment by brenton** [comment]
@jianlinliu, this would a good situation to have a test case for.  We'll likely get the fix during the next kubernetes rebase.
