### ISSUE TITLE
oc cluster up should provide consistent node name

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#12622]
When I do "oc cluster up --public-hostname" I would like the node to be named after that name/ip so that it's consistent across locations when roaming IPs. Now I get a name for the node in /var/lib/origin/openshift.local.config/node-XXX.XXX.XXX.XXX that is different depending on the ip where my cluster is started no matter what options I do pass.

Also related, #12621, in case there's a different way to specify the ip to bind than --public-hostname.

##### Version
1.5.0-alpha.2

**Comment by jorgemoralespou** [comment]
@pweil- I would like to ask for a raise in priority for this issue, since this blocks one very important use case for oc cluster up, which is roaming when a cluster is already created.
The field is using "oc cluster" to do a lot of demos and local development on openshift and they are constantly moving and they need to recreate the cluster and recreate their demos, while if this was solved, they could prepare the demos beforehand making sure they could properly show it at a customer site.

cc/ @smarterclayton

**Comment by pweil-** [comment]
@jorgemoralespou would `--use-existing-config` help your use case rather than recreating new configs during the cluster up?

**Comment by jorgemoralespou** [comment]
@pweil- that is the source of the problem
When using --use-existing-config I get a node created with an IP (the one that was provided when the cluster got created). Then, if you move to a different network, and do "oc cluster up", that IP might not be available and the cluster will not start.

@csrwng Can probably better describe the problem, if he sit close to you, and probably in a much more agile way.

With both 2 issues here described, one can be sure that the cluster he creates and provisions (with a demo) will most likely run anywhere (except if a proxy is required, as that would require change in configuration). This is key to do demos that you want to prepare in advance..

**Comment by edseymour** [comment]
I can confirm this does limit the usability of persistent configuration. As the node name and configuration is locked to the local IP of the host, the node becomes unavailable when the host IP changes - as @jorgemoralespou described with a roaming IP. 

An example scenario: creating a demo at the office, then attempting to replay demo at a meet-up.

**Comment by edseymour** [comment]
Workaround is to pass 127.0.0.1 as the public hostname. 

What appears to happen is that during oc cluster up, the public hostname is used to derive an IP address which is then used to create a node name. The if the IP changes, due to roaming, or dhcp lease expiration, subsequent calls fail: 

```
-- Starting OpenShift container ... FAIL
   Error: Docker run error rc=2
   Details:
     Image: registry.access.redhat.com/openshift3/ose:latest
     Entrypoint: [/bin/bash]
     Command: [-c for name in 192.168.1.152 mypublic.hostname; do ls /var/lib/origin/openshift.local.config/node-$name &> /dev/null && echo $name && break; done]
```

Where in above example 192.168.1.152 was an old assigned IP to mypublic.hostname

If a static IP is passed to the public hostname option, this is used instead. Therefore subsequent runs are guaranteed to work with 127.0.0.1

**Comment by jorgemoralespou** [comment]
@eseymour that doesn't work on mac where you might get a different IP for the docker for mac boot 2 docker.  Also minishift can run in the same problem. So far they try to always assign the same ip to their boot2docker but it's giving some issues with xhyve and the dhcp leases. 

It would be awesome to have this fixed.

**Comment by csrwng** [comment]
@jorgemoralespou working on it... should hopefully have a pull ready today

**Comment by edseymour** [comment]
@jorgemoralespou yes, totally agree. I'm running on Linux (fedora) - which I should've made clear.

**Comment by edseymour** [comment]
@csrwng awesome :+1:

**Comment by edseymour** [comment]
OK, my assertion that 127.0.0.1 works was incorrect. It works in the sense that the oc cluster up consistently completes successfully, however, it breaks the internal OpenShift SDN. Likely due to being a non-unique IP that is shared within each container running.

**Comment by csrwng** [comment]
@edseymour what do you mean by it breaking the internal openshift SDN? Do you mean that services don't work anymore?

**Comment by edseymour** [comment]
@csrwng so an example build fails as unable to resolve/connect to github. Metrics deployment fails as it claims it cannot connect to the kubernetes service. Stop cluster, restart using host IP, and it features working as expected.

**Comment by bparees** [comment]
@csrwng unclear if this is resolved w/ the loopback changes you made?

**Comment by csrwng** [comment]
Yes, this is fixed
