### ISSUE TITLE
Pod is unable to successfully curl <servicename>:<port>

### ISSUE THREAD

**Issue by crobby** [openshift/origin#12624]
[provide a description of the issue]

##### Version
oc v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
0. iptables -F
1. oc cluster up
2. start a service
3. start another pod and get a terminal in that pod
4. curl <servicename>:<port>

##### Current Result
curl from one pod in my project to a service:port in the same project does not work

##### Expected Result
curl from within pod to service:port should work

##### Additional Information
DNS seems to be resolving correctly
sh-4.2$ ping testcluster-ui                                                                                                                           
PING testcluster-ui.myproject.svc.cluster.local (172.30.3.121) 56(84) bytes of data.     

curl to testcluster-ui:8080   or 172.30.3.121:8080  does NOT work

curling the endpoint from within the pod DOES work
sh-4.2$ curl 172.17.0.6:8080                                                                                                                          
<!DOCTYPE html><html>     

from my host running the oc cluster up, curl to the service IP:port DOES work

oadm diagnostics output:

[croberts@crlaptop ~]$ oadm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/home/croberts/.kube/config'
Info:  Using context for cluster-admin access: 'default/192-168-1-92:8443/system:admin'

[Note] Running diagnostic: ConfigContexts[myproject/192-168-1-92:8443/developer]
       Description: Validate client config context is complete and has connectivity
       
Info:  For client config context 'myproject/192-168-1-92:8443/developer':
       The server URL is 'https://192.168.1.92:8443'
       The user authentication is 'developer/192-168-1-92:8443'
       The current project is 'myproject'
       Successfully requested project list; has access to project(s):
         [myproject]
       
[Note] Running diagnostic: ConfigContexts[myproject/192-168-1-92:8443/system:admin]
       Description: Validate client config context is complete and has connectivity
       
Info:  For client config context 'myproject/192-168-1-92:8443/system:admin':
       The server URL is 'https://192.168.1.92:8443'
       The user authentication is 'system:admin/192-168-1-92:8443'
       The current project is 'myproject'
       Successfully requested project list; has access to project(s):
         [default kube-system myproject openshift openshift-infra]
       
[Note] Running diagnostic: ConfigContexts[myproject/localhost:8443/developer]
       Description: Validate client config context is complete and has connectivity
       
ERROR: [DCli0014 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'myproject/localhost:8443/developer':
       The server URL is 'https://localhost:8443'
       The user authentication is 'developer/localhost:8443'
       The current project is 'myproject'
       (*errors.StatusError) the server has asked for the client to provide credentials
       
       This means that when we tried to make a request to the master API
       server, the request required credentials that were not presented. This
       can happen with an expired or invalid authentication token. Try logging
       in with this user again.
       
[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint
       
ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:155]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected
              
       Info:  Service account token successfully authenticated to master
       ERROR: [DP1014 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:173]
              Request to integrated registry timed out; this typically indicates network or SDN problems.
              
       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected
              
       [Note] Summary of diagnostics execution (version v1.5.0-alpha.2+e4b43ee):
       [Note] Errors seen: 1
       
[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint
       
WARN:  [DNet2002 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:82]
       Skipping network diagnostics check. Reason: Not using openshift network plugin.
       
[Note] Skipping diagnostic: AggregatedLogging
       Description: Check aggregated logging integration for proper configuration
       Because: No master config file was provided
       
[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry
       
[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects
       
Info:  clusterrolebinding/cluster-admins has more subjects than expected.
       
       Use the `oadm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.
       
Info:  clusterrolebinding/cluster-admins has extra subject {ServiceAccount default pvinstaller    }.

[Note] Running diagnostic: ClusterRoles
       Description: Check that the default ClusterRoles are present and contain the expected permissions
       
[Note] Running diagnostic: ClusterRouterName
       Description: Check there is a working router
       
[Note] Running diagnostic: MasterNode
       Description: Check if master is also running node (for Open vSwitch)
       
Info:  Found a node with same IP as master: 192.168.1.92

[Note] Skipping diagnostic: MetricsApiProxy
       Description: Check the integrated heapster metrics can be reached via the API proxy
       Because: The heapster service does not exist in the openshift-infra project at this time,
       so it is not available for the Horizontal Pod Autoscaler to use as a source of metrics.
       
[Note] Running diagnostic: NodeDefinitions
       Description: Check node records on master
       
[Note] Skipping diagnostic: ServiceExternalIPs
       Description: Check for existing services with ExternalIPs that are disallowed by master config
       Because: No master config file was detected
       
[Note] Summary of diagnostics execution (version v1.5.0-alpha.2+e4b43ee):
[Note] Warnings seen: 1
[Note] Errors seen: 2

**Comment by crobby** [comment]
For what it's worth, my machine is running fedora 25.  Let me know if I can offer anything else.

**Comment by csrwng** [comment]
@crobby are you able to curl external urls from your client pod? (ie. github.com)

**Comment by crobby** [comment]
Yes, curling external urls from within the pod is indeed working.

**Comment by csrwng** [comment]
@crobby can you run `docker inspect origin` and include the output?

**Comment by crobby** [comment]
[croberts@crlaptop ~]$ docker inspect origin
[
    {
        "Id": "82b768472921277d4d3e672f2fb78d206a1086b1697e6e28abf700217bb4870d",
        "Created": "2017-01-23T19:47:45.882887971Z",
        "Path": "/usr/bin/openshift",
        "Args": [
            "start",
            "--master-config=/var/lib/origin/openshift.local.config/master/master-config.yaml",
            "--node-config=/var/lib/origin/openshift.local.config/node-192.168.1.92/node-config.yaml",
            "--loglevel=4"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 10750,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-01-23T19:47:46.671472538Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:97b5c50da638a168e6fe28ae0d4fbb7137e0dd6b7174537c24f5fc3f321c9a2f",
        "ResolvConfPath": "/var/lib/docker/containers/82b768472921277d4d3e672f2fb78d206a1086b1697e6e28abf700217bb4870d/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/82b768472921277d4d3e672f2fb78d206a1086b1697e6e28abf700217bb4870d/hostname",
        "HostsPath": "/var/lib/docker/containers/82b768472921277d4d3e672f2fb78d206a1086b1697e6e28abf700217bb4870d/hosts",
        "LogPath": "",
        "Name": "/origin",
        "RestartCount": 0,
        "Driver": "devicemapper",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/log:/var/log:rw",
                "/var/run:/var/run:rw",
                "/sys:/sys:ro",
                "/var/lib/docker:/var/lib/docker",
                "/:/rootfs:ro",
                "/var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave",
                "/home/croberts/originconfig:/var/lib/origin/openshift.local.config:z",
                "/sys/devices/virtual/net:/sys/devices/virtual/net:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "journald",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "host",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "oci",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "2061",
                "DeviceName": "docker-253:0-4587668-4f0f9c5d3cdd02a9abea107759adc494553b8658d880178a1b330761a2afe0ae",
                "DeviceSize": "10737418240"
            }
        },
        "Mounts": [
            {
                "Source": "/sys",
                "Destination": "/sys",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/lib/docker",
                "Destination": "/var/lib/docker",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/",
                "Destination": "/rootfs",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/lib/origin/openshift.local.volumes",
                "Destination": "/var/lib/origin/openshift.local.volumes",
                "Mode": "rslave",
                "RW": true,
                "Propagation": "rslave"
            },
            {
                "Source": "/home/croberts/originconfig",
                "Destination": "/var/lib/origin/openshift.local.config",
                "Mode": "z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/sys/devices/virtual/net",
                "Destination": "/sys/devices/virtual/net",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/log",
                "Destination": "/var/log",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/run",
                "Destination": "/var/run",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "crlaptop.crobby.org",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "53/tcp": {},
                "8443/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "HOME=/root",
                "OPENSHIFT_CONTAINERIZED=true",
                "KUBECONFIG=/var/lib/origin/openshift.local.config/master/admin.kubeconfig",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "start",
                "--master-config=/var/lib/origin/openshift.local.config/master/master-config.yaml",
                "--node-config=/var/lib/origin/openshift.local.config/node-192.168.1.92/node-config.yaml",
                "--loglevel=4"
            ],
            "Image": "openshift/origin:v1.5.0-alpha.2",
            "Volumes": null,
            "WorkingDir": "/var/lib/origin",
            "Entrypoint": [
                "/usr/bin/openshift"
            ],
            "OnBuild": null,
            "Labels": {
                "build-date": "20161214",
                "io.k8s.description": "OpenShift Origin is a platform for developing, building, and deploying containerized applications. See https://docs.openshift.org/latest for more on running OpenShift Origin.",
                "io.k8s.display-name": "OpenShift Origin Application Platform",
                "license": "GPLv2",
                "name": "CentOS Base Image",
                "vendor": "CentOS"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "2e79a4b62e77689172705be65110b99ec7cdb290e92b4a8b6ae714d1d0b0f445",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "79ae5fa67635828c30b839c12b2968cfb1d8d85e018a8125ee7ca9c4429431db",
                    "EndpointID": "60f66c24dd59b6776e3a7135217bb63b63d69868aba0dfb18dc4ff8593f8fed6",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]

**Comment by ncdc** [comment]
@crobby what is your kernel version? `uname -r`

**Comment by crobby** [comment]
4.9.4-201.fc25.x86_64

**Comment by ncdc** [comment]
@crobby I believe you're running into this: https://bugzilla.redhat.com/show_bug.cgi?id=1414068. You can download a testing kernel to see if it fixes things.

**Comment by crobby** [comment]
I will give that a try, thanks @ncdc.

**Comment by crobby** [comment]
Wow, thank you both so much.  Updating to 4.9.5-200.fc25.x86_64 does indeed seem to fix the problem that I'm having.

**Comment by csrwng** [comment]
thx @ncdc !!

**Comment by lpshikhar** [comment]
@crobby Hi, even the service discovery mechanism is not working for me on my mac. If I pass the pod IP individually as environment variables to my application, everything works fine. As soon as I use the service name or service IP, the pod keeps looking for the service to resolve. But on the contrary, if I ping a service name or service IP from the pod terminal, it is resolving the name into IP.
I can provide details if needed.

**Comment by csrwng** [comment]
@lpshikhar if you are using Docker for Mac 1.13, please upgrade to Docker for Mac 1.13.1. There was a networking issue that broke services.

**Comment by lpshikhar** [comment]
@csrwng Hi, Thank you so much, upgrading docker to version 1.13.1 worked.
