### ISSUE TITLE
Zookeeper example questions

### ISSUE THREAD

**Issue by Syffs** [openshift/origin#12620]
I'm a beginner, so sorry in advance if this appears to be a stupid question... I'm taking [this example](https://github.com/openshift/origin/tree/master/examples/zookeeper) as a reference for porting it into my solution, so I assume that the way it's done here is the way to go. 

Now I don't understand the way it's designed... 

My understanding is that having zk-1,zk-2,...,zk-N pods predefined break the philosophy of openshift to have scalable services. Instead, I guess I would have defined this as below to allow slaves scalability:

- 1 zk service 

- 2 DeploymentConfig: zk-master, zk-slave-[a-z0-9]{4}

**So I'm pretty sure I misunderstood something, but what?** 

Looking at this [other example](https://github.com/openshift/origin/blob/master/examples/pets/zookeeper/zookeeper.yaml), Zookeeper is set up differently with StatefulSet and 3 replicas. 

**What's the difference of philosophy which brought to these 2 different implementations?**

**Comment by mfojtik** [comment]
@Syffs this example was built when the statefulset did not existed :-) we should probably update it to use the stateful set now.

**Comment by Syffs** [comment]
@mfojtik thanks for the clarification! Do know when it could be updated? I guess this take the same basis as [this one](https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/tutorials/stateful-application/zookeeper.yaml) ?

Do you have plans of providing an example for hadoop/spark/hbase applications? I've struggled for a while on how to set these up, and I don't even think my architecture is state-of-the-art.

**Comment by kargakis** [comment]
Removed in https://github.com/openshift/origin/pull/18192
