### ISSUE TITLE
oc cluster up does not bind to a specific IP on mac

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#12621]
When you do "oc cluster up --public-hostname '11.2.2.2'" where you want openshift listening on 11.2.2.2, you see the following startup message:

````
-- Finding server IP ...
   Using public hostname IP 11.2.2.2 as the host IP
   Using 127.0.0.1 as the server IP
````

I can not access my cluster at https://11.2.2.2:8443 even though I'm setting that as the public hostname. I need to do the following command to be able to access it at that ip:

````
socat TCP-L:8443,reuseaddr,fork,backlog=20,bind=11.2.2.2 SYSTEM:"docker exec -i origin socat - TCP\:localhost\:8443"
````

I want to have a way to specify where my cluster is bound and I'll make sure if that ip is publicly accessible or not. That's my responsibility and decision. Maybe an extra "--bind-ip" is the solution, but I want to be able to use the provided by me ip for the complete cluster setup/bootstrap.

I can have a private loopback interface dedicated to oc cluster with a name in /etc/hosts to make my life easier or I can maybe bind to my public ip to allow people to access my cluster for testing purposes. Either way, I think this should be a developer decision, and the tool should support this OOTB.

I want to be able to access the console at the provided URL in the bootstrap output, and if the ip is public, I want anyone to be able to access it there:

````
   The server is accessible via web console at:
       https://11.2.2.2:8443
`````

By the way, this only happens on mac.

##### Version
1.5.0-alpha.2 and prior.

**Comment by jasonmadigan** [comment]
@jorgemoralespou from what I can tell, this used to work pretty much as you've described back in the `1.3.x` releases of `oc`. Would be great to get a fix or another option.

I've rolled back to these for now, since some of my wrapper scripts setup a local interface alias via loopback to give the cluster a static IP (similar to you) that won't move around when I move between wired/wireless networks.

**Comment by csrwng** [comment]
Fix is included in https://github.com/openshift/origin/pull/13112

**Comment by csrwng** [comment]
@jasonmadigan or @jorgemoralespou can you please try the latest binary from that pull and check that it fixes this use case?

**Comment by jasonmadigan** [comment]
thanks @csrwng - will give that a go now. didn't see a linked binary, but I'll build locally and check.

**Comment by csrwng** [comment]
@jasonmadigan,  @jorgemoralespou has added a helpful plug-in to his oc-cluster [wrapper](https://github.com/openshift-evangelists/oc-cluster-wrapper) that will build a binary (mac,windows,linux) for you on your local cluster as long as you point it to a repo and branch name.

**Comment by jasonmadigan** [comment]
@csrwng @jorgemoralespou awesome, that's very useful, will use that next time - thanks!

**Comment by jasonmadigan** [comment]
@csrwng Just gave https://github.com/openshift/origin/pull/13112 a spin locally and things are working exactly as I wanted them - thanks!

Some details:

* Running Docker for Mac 1.13.1 (on Sierra)
* I've alias'd `192.168.44.10` to the `lo0` interface (e.g. `sudo ifconfig lo0 alias 192.168.44.10`) so I can move around networks and keep my cluster working locally
* Built locally and can now run `oc cluster up --public-hostname '192.168.44.10'` and the server IP is set correctly - can login via https://192.168.44.10:8443/console/ & the default router for apps gives me the route I expect e.g. http://test-myproject.192.168.44.10.xip.io/

Let me know if you want any other details or a re-test with my scenario.

**Comment by bparees** [comment]
sounds like this is fixed, closing.
