### ISSUE TITLE
oc cluster up won't start after adding the check for port 53 availability

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#12646]
oc cluster up won't start because the new check which is wrong!

The check for 53 is wrong because it does not consider ports that are bound to specific IP and fails. Also there should always be an option to disable such check but I can't find one!?

Typically port 53 is widely used by libvirt (dnsmasq), but is bind to specific IP so this should not be an issue.

It worked before...

@csrwng ?

##### Version
```bash
$ oc version
oc v1.5.0-alpha.2+c5868ac-143-dirty
kubernetes v1.5.2+43a9be4
features: Basic-Auth
```

##### Steps To Reproduce
1. oc cluster up --version latest --public-hostname 10.34.129.181

##### Current Result
```
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:latest image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... FAIL
   Error: a port needed by OpenShift is not available
   Caused By:
     Error: ports in use: [53]
```

##### Expected Result
Work (as it did before)

##### Additional Information
```bash
$ sudo netstat -tulpn | grep ':53 '
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      1797/dnsmasq        
udp        0      0 192.168.122.1:53        0.0.0.0:*                           1797/dnsmasq        
```

```bash
$ ip a
2: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 50:7b:9d:ab:1f:38 brd ff:ff:ff:ff:ff:ff
    inet 10.34.129.181/23 brd 10.34.129.255 scope global dynamic enp0s25
       valid_lft 82335sec preferred_lft 82335sec
    inet6 2620:52:0:2280:527b:9dff:feab:1f38/64 scope global mngtmpaddr dynamic 
       valid_lft 2591973sec preferred_lft 604773sec
    inet6 fe80::527b:9dff:feab:1f38/64 scope link 
       valid_lft forever preferred_lft forever
5: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:2e:ea:b3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
```

**Comment by csrwng** [comment]
@tnozicka yes that seems wrong. It should not fail because 53 is in use. Taking a look

**Comment by tnozicka** [comment]
@csrwng thanks
btw. works with

```bash
$ oc v1.5.0-alpha.2+e4b43ee-dirty
kubernetes v1.5.2+43a9be4
features: Basic-Auth
```

**Comment by coreydaley** [comment]
@tnozicka OpenShift tries to use port 53, and if that is unavailable it tries to use port 8053.  Do you also have something running on port 8053?

Code for reference: https://github.com/openshift/origin/blob/master/pkg/bootstrap/docker/openshift/helper.go#L37-L38

**Comment by coreydaley** [comment]
@csrwng Looks like @smarterclayton broke it with this pull request:  https://github.com/openshift/origin/commit/3f42e195349e98f377a3c28a32f8e317729bff2f#diff-289dd62730ab075b34eb10a03a9687e6

This code: https://github.com/openshift/origin/commit/3f42e195349e98f377a3c28a32f8e317729bff2f#diff-289dd62730ab075b34eb10a03a9687e6

Is now calling this function: https://github.com/openshift/origin/blob/master/pkg/bootstrap/docker/up.go#L664 which returns an error that causes an exit, instead of calling this function: https://github.com/openshift/origin/blob/master/pkg/bootstrap/docker/up.go#L673 which would use the alternate dns port instead of just failing and exiting.  @smarterclayton might have a better idea of how to fix it as his pull request did quite a bit of refactoring.

**Comment by mfojtik** [comment]
@jhadvig you was asking me today about this :-)

**Comment by csrwng** [comment]
I'm working on a fix ... and hopefully extended tests that will help us figure out when we break it in the future.

**Comment by csrwng** [comment]
Fixed in https://github.com/openshift/origin/pull/12745#event-944210946
