### ISSUE TITLE
Panic during integration run

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12659]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10529/consoleFull

```
I0124 18:34:26.146727    9835 ensure.go:84] Added replication-controller service accounts to the system:replication-controller cluster role: <nil>
unexpected fault address 0xffffffff81580a1a
fatal error: fault
[signal 0xb code=0x1 addr=0xffffffff81580a1a pc=0x77ef7b]

goroutine 491 [running]:
runtime.throw(0x587dc88, 0x5)
	/usr/lib/golang/src/runtime/panic.go:547 +0x90 fp=0xc821a11b50 sp=0xc821a11b38
runtime.sigpanic()
	/usr/lib/golang/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc821a11ba0 sp=0xc821a11b50
net/http.(*response).finishRequest(0xc82e089860)
	/usr/lib/golang/src/net/http/server.go:1257 +0xab fp=0xc821a11bd0 sp=0xc821a11ba0
net/http.(*conn).serve(0xc821ee1400)
```

**Comment by soltysh** [comment]
I've went through the console logs in search for anything suspicious, haven't found a sweet spot, yet. It is on my radar, although I'm suspecting this is a bug in integration tests itself, not in origin. With that I'm lowering the priority to p2.

**Comment by simo5** [comment]
@soltysh is this somthing real still ?
The link to CI is gone and I do not see enough infoto act on this. Should we close and assume it's gone ?

**Comment by soltysh** [comment]
That's fair. I'll go ahead and close this. Please re-open if this re-appears.
