### ISSUE TITLE
integration flake: TestIngressConfiguredRouter: unavailable ingress route

### ISSUE THREAD

**Issue by miminar** [openshift/origin#12661]
Looks like TLS config secret failed to propagate:

```
I0124 14:29:41.550505       1 ingress.go:309] Error retrieving secret router-namespace/my-secret: converting (v1.NamespaceList) to (api.Secret): ObjectMeta not present in src
I0124 14:29:41.550537       1 ingress.go:324] Unable to source TLS configuration for ingress router-namespace/foo from secret router-namespace/my-secret
I0124 09:30:12.212705   10834 router_http_server.go:258] Stopping listener at 172.18.11.103:8080
I0124 09:30:12.212741   10834 router_http_server.go:258] Stopping listener at 172.18.11.103:8888
I0124 09:30:12.212750   10834 router_http_server.go:258] Stopping listener at 172.18.11.103:8889
I0124 09:30:12.212758   10834 router_http_server.go:258] Stopping listener at 172.18.11.103:8443
--- FAIL: TestIngressConfiguredRouter (31.53s)
	router_test.go:1879: Error accessing ingress configured route: unavailable the entire time: endpoint not available
FAIL
E0124 09:30:12.212801   10834 router_http_server.go:364] HTTP server failed: accept tcp 172.18.11.103:8080: use of closed network connection
```

Happened in job https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10490/consoleFull#120288724156bf4006e4b05b79524e5923

**Comment by marun** [comment]
The TLS secret is intentionally missing to allow validation of an unsecured route generated from an ingress.  Only once an unsecured route can be reached is a secret added that allows testing of the same route via https.  The error here is due to the unsecured route not being reached within the expected interval (30s).

**Comment by knobunc** [comment]
Seems to be a transient docker failure that we can't do much about.

**Comment by stevekuznetsov** [comment]
What is the significance of this 30s timeout? Why is bumping it not appropriate here?

**Comment by stevekuznetsov** [comment]
I seem to be hitting this a lot ... 
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration_future/12/
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration_future/11/

**Comment by stevekuznetsov** [comment]
Seeing this in `base_ami` too: https://ci.openshift.redhat.com/jenkins/job/base_ami/2680/consoleFull#120292087656bf4006e4b05b79524e5923

**Comment by knobunc** [comment]
We can't trigger this any more... something else has become more responsive.  Dropping the Priority.

**Comment by stevekuznetsov** [comment]
@deads2k has identified this as a failure point for all of the recent test runs. @knobunc what is the significance of the 30s timeout? Can we bump it?

**Comment by deads2k** [comment]
Looks like every job since 10am today.

**Comment by knobunc** [comment]
Ugh!  Ok, let's bump the timeout.  @JacobTanenbaum can you look at this please?

**Comment by stevekuznetsov** [comment]
We haven't had a merge since [this job](https://ci.openshift.redhat.com/jenkins/view/Origin%20PR%20Tests/job/merge_pull_request_origin/15/) merged https://github.com/openshift/origin/commit/a4efef06914b2a2ab169574e372576613e2a309d about 20 hours ago. No new AMIs since [#9](https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/9/) two days ago. If this can flare up due to other slowness, bump the timeout to an hour.

**Comment by stevekuznetsov** [comment]
In general we should never use such short timeouts unless they are semantically meaningful to the test. Let the 4min global test timeout kick in unless you have a specific need to make a shorter timeout.

**Comment by smarterclayton** [comment]
Looks like this test is broken when run in hack/env - we fixed the other router tests, we should fix it here too.  Should be:

```
hack/env integration.test -test.run=TestIngressConfiguredRouter
```

Looks like not timeout related at all.

**Comment by knobunc** [comment]
Oh good.  I was having trouble imagining why we would take more than 30s to respond to a simple http request...

**Comment by liggitt** [comment]
Is this still an issue?

**Comment by knobunc** [comment]
@smarterclayton where are we running that test?  Is it in a repo I don't know about?  Or did @stevekuznetsov fix this in one of his recent (excellent) cleanups of the shell stuff?

**Comment by stevekuznetsov** [comment]
We have not seen this in a while... closing.
