### ISSUE TITLE
Statefulset example: cannot find volume plugin for alpha provisioning 

### ISSUE THREAD

**Issue by Syffs** [openshift/origin#12676]
I'm trying to run this [Zookeeper example](https://github.com/openshift/origin/tree/master/examples/statefulsets/zookeeper), but I end with errors such as:
```
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  1h            12s             281     {default-scheduler }                    Warning         FailedScheduling        [SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-zoo-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-zoo-0", which is unexpected.]
```
or
```
error finding provisioning plugin for claim test/datadir-zoo-2: cannot find volume plugin for alpha provisioning
```

I'm note sure but I suspect that it might be due to line `volume.alpha.kubernetes.io/storage-class: anything`, because I don't think that there is any default StorageClass defined...
If so how can I set up the most simple StorageClass to get this to work, because as I'm self-hosting my openshift origin cluster, I cannot fit into any of the cloud storage option (GCE, AWS, Azure, etc...)?

##### Version
```
[user@server ~]$ oc version
oc v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.1.106:8443
openshift v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. Retrieve file [zookeeper.yaml](https://gist.github.com/Syffs/0ddf5f007ca8360f3ac50262697e6452)
2. Run as below:
```
oc process -f zookeeper.yaml > zookeeper.active
oc create -f zookeeper.active
```
3. oc describe pods zoo-0

##### Current Result

- Volumes are not allocated

- Pods are not scheduled

**Comment by smarterclayton** [comment]
I wonder if the example was updated upstream to remove the annotation.

**Comment by stevekuznetsov** [comment]
When I hit this, I was installing Origin with the Ansible installer and needed to add the following stanza to my OSEv3 vars:

```yml
osm_controller_args:
  enable-hostpath-provisioner:
    - true
```

**Comment by jorgemoralespou** [comment]
I have hit this with minishift, which embeds "oc cluster up"., trying to deploy [this example](https://github.com/kubernetes/charts/blob/master/stable/gitlab-ce/values.yaml) which uses the alpha annotation.

I'm using 3.6.0-rc.0.

**Comment by stevekuznetsov** [comment]
Other issues tracking this,

/close
