### ISSUE TITLE
test/end-to-end/core.sh:363: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token.log'' expecting success and text 'Using in-cluster configuration': the output content test failed

### ISSUE THREAD

**Issue by pecameron** [openshift/origin#12678]
[provide a description of the issue]

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10577/console

Running test/end-to-end/core.sh:363: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token.log'' expecting success and text 'Using in-cluster configuration'...
FAILURE after 0.015s: test/end-to-end/core.sh:363: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token.log'' expecting success and text 'Using in-cluster configuration': the output content test failed
Standard output from the command:
Waiting for pod test/cli-with-token to be running, status is Pending, pod ready: false
Waiting for pod test/cli-with-token to be running, status is Pending, pod ready: false
In project test on server https://172.30.0.1:443
pod/cli-with-token runs openshift/origin:b91b87b
1 warning identified, use 'openshift cli status -v' to see details.

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by ncdc** [comment]
This isn't actually why #12472 failed. We know about that issue and it runs with errexit turned off. Your actual failure was this:

```
Running test/end-to-end/core.sh:422: executing 'oc get builds --namespace test -o jsonpath='{.items[0].status.phase}'' expecting any result and text 'Running'; re-trying every 0.2s until completion or 600.000s...
FAILURE after 599.388s: test/end-to-end/core.sh:422: executing 'oc get builds --namespace test -o jsonpath='{.items[0].status.phase}'' expecting any result and text 'Running'; re-trying every 0.2s until completion or 600.000s: the command timed out
Standard output from the command:
Pending
... repeated 33 times
Failed
... repeated 1434 times
Standard error from the command:
[ERROR] PID 32716: hack/lib/cmd.sh:618: `return "${return_code}"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/cmd.sh:618: `return "${return_code}"`
[INFO] 		  2: test/end-to-end/core.sh:422: os::cmd::try_until_text
[INFO]   Exiting with code 1.
[ERROR] PID 31461: hack/test-end-to-end-docker.sh:91: `${OS_ROOT}/test/end-to-end/core.sh` exited with status 1.
```

**Comment by ncdc** [comment]
I'm going to close this out since it's a red herring. We can create a new issue for the build failure if needed.
