### ISSUE TITLE
Deployments without triggers don't automatically resolve images

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#12687]
Apps deployed without a trigger don't automatically resolve/associate the image on deploy

![image](https://cloud.githubusercontent.com/assets/2239920/22361022/b39abe4a-e4a9-11e6-96c2-0ff1b469234b.png)

eg.
```
oc get dc
NAME      REVISION   DESIRED   CURRENT   TRIGGERED BY
asd       1          1         1         
```

This will lead to:
```
Back-off pulling image "asd:latest"
Error syncing pod, skipping: failed to "StartContainer" for "asd" with ImagePullBackOff: "Back-off pulling image \"asd:latest\""
Failed to pull image "asd:latest": unauthorized: authentication required
Error syncing pod, skipping: failed to "StartContainer" for "asd" with ErrImagePull: "unauthorized: authentication required"
```

This resolves the issue. Not sure if this is intentional/by design?

```
oc set image dc/asd asd=test/asd:latest
```

##### Version
1.4.1

**Comment by spadgett** [comment]
This should be fixed by https://github.com/openshift/origin-web-console/pull/810 

We add the trigger now, but set `automatic` to false. See also https://github.com/openshift/origin-web-console/issues/808

cc @kargakis

**Comment by kargakis** [comment]
You need an ImageChangeTrigger if you want to associate a DC with an
ImageStream, there is no other way around it.

Beyond that, you have two options: either set automatic to true in which
case as soon as an image is available, a new deployment starts for you or
in case of automatic=false, the image will be resolved when you try to
deploy (oc rollout latest - oc deploy --latest - and I think the console
now uses the /instantiate endpoint for the Deploy button).

**Comment by kargakis** [comment]
Not an issue.
