### ISSUE TITLE
no errors when logging to console using non-existent usernames/passwords

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#1268]
I just tried logging in to console by typing whatever and when I submitted the form, the page didn't output anything. I find this to be a UX bug.

**Comment by liggitt** [comment]
I can't reproduce this. Do you mean web console or CLI? What version (`openshift version`) and configuration (`openshift start <YOUR ARGS> --write-config --master-config=master.yaml --node-config=node.yaml`) are you using?

**Comment by TomasTomecek** [comment]
web console

**Comment by liggitt** [comment]
Issue was `--master` host was unreachable by browsers. Adding `--public-master` solved the issue.
