### ISSUE TITLE
RFE: Add support for docker build-args

### ISSUE THREAD

**Issue by lionelve** [openshift/origin#12686]
I have a Dockerfile with an ARG statement and I would like to run something equivalent to 

$docker build --build-arg ARG1=value ./build-dir

There is no such option in oc start-build for BuildConfigs that use the Docker Strategy. 

For people stuck with Dockerfiles this means creating copies of the file for different values of ARG1.

**Comment by bparees** [comment]
in progress in trello:
https://trello.com/c/Yh9BPAGi
