### ISSUE TITLE
Deleting jobs is awfully slow

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#12689]
Given I want to delete all jobs created by a cronjobs:

```
# oc get jobs | wc -l
56
# time oc delete jobs --all
job "test-1485371100" deleted
job "test-1485371400" deleted
job "test-1485371700" deleted
job "test-1485372000" deleted
job "test-1485372300" deleted
job "test-1485372600" deleted
job "test-1485372900" deleted
job "test-1485373200" deleted
job "test-1485373500" deleted
job "test-1485373800" deleted
job "test-1485374100" deleted
job "test-1485374400" deleted
job "test-1485374700" deleted
job "test-1485375000" deleted
....
^C
real	1m6.850s
```

(note it deleted ~20 jobs and then I stopped it)

**Comment by kargakis** [comment]
revisionHistoryLimit on cronjons is the real fix

**Comment by soltysh** [comment]
From what I've discussed this with @mfojtik in person still the delete operation of a single job so extremely slow, it might be connected with the number of existing jobs. I'll dig into it.

**Comment by soltysh** [comment]
Now that deletion happens server-side, I think we can close this.

/close
