### ISSUE TITLE
Make oc new-app find a template inside a repo and use that when instantiating application

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#12692]
I've spoke earlier today with @GrahamDumpleton and we come up with this idea about `oc new-app` (when it already has the repo contents for language detection) could search for OpenShift template and use that instead of the default machinery currently available in `new-app` when instantiating my application. This would allow me easily distribute my application along with recommended setting, like for example readiness probes, etc.

@bparees @csrwng wydt? since you're responsible for the new-app command. I'm also inclined to start a new new-app like project that would allow some more customization of that process, can be tracked as a separate issue, though :)

**Comment by csrwng** [comment]
there's a card for that :)
https://trello.com/c/iotn8FCo/873-8-make-new-app-generate-based-on-skeleton-definition-evg-app-creation

And yes, the idea is that you'd supply your templates for the generated objects.

**Comment by soltysh** [comment]
In that case, I'm fine closing this issue with that link. Thank you!
