### ISSUE TITLE
Integration Test Suite Timing Out

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#12705]
Seeing `test_pull_requests_origin_integration` jobs get aborted at the 3h mark like [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10697).

**Comment by stevekuznetsov** [comment]
Timings:

```
hack/build-base-images.sh took 133 seconds
hack/build-cross.sh took 464 seconds
hack/build-release.sh took 492 seconds
hack/build-images.sh took 205 seconds
/data/src/github.com/openshift/origin/hack/build-go.sh test/integration/integration.test took 629 seconds
hack/test-integration.sh took 1919 seconds
hack/build-go.sh took 4 seconds
```

Then, `hack/test-end-to-end.sh` ran. The above timing (considering that build-cross is a part of build-release AFAICT) took ~56minutes. None of the e2e `os::cmd` test timings look long, so I'm at a loss to see what took two hours.

**Comment by stevekuznetsov** [comment]
The actual tests in the e2e suite look to not have taken too much time ...

```sh
$ curl -s https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10697/consoleText | grep -Po "(?<=SUCCESS after )[0-9]+\.[0-9]+(?=s)" | paste -sd+ - | bc
202.270
```

/cc @smarterclayton I can't quite figure out what part of the test suite is broken but usually when we start timing out it means something is pretty bad on a structural level.

**Comment by stevekuznetsov** [comment]
[Another instance](https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/13404/)

**Comment by stevekuznetsov** [comment]
@pweil- there is nothing to really suggest this is due to tooling -- should be triaged as a normal bug

**Comment by mfojtik** [comment]
@soltysh is going to look at this, but I don't thing this is a blocker for 1.5.

**Comment by soltysh** [comment]
I wonder how this relates to #12659. I'm going to link the two, just as a reference.

**Comment by soltysh** [comment]
This might be the culprint:
```
Running test/end-to-end/core.sh:416: executing 'oadm diagnostics DiagnosticPod --images='openshift/origin-${component}:d87efa8'' expecting success and not text 'ERROR'...
Build timed out (after 180 minutes). Marking the build as aborted.
```
maybe it's worth shortening the timeout there. I'll open a PR in a few.

**Comment by soltysh** [comment]
I've started with getting the test back to its original shape here: https://github.com/openshift/origin/pull/12890.

**Comment by soltysh** [comment]
With the revert being merged we agreed with @stevekuznetsov to close this flake. If the situation will happen again this issue will be re-opened.
