### ISSUE TITLE
Way to expose the OpenShift Port when Using Docker Toolbox on Windows and oc cluster up?

### ISSUE THREAD

**Issue by tellmejeff** [openshift/origin#12706]
I'm working on some documentation about how to get a simple OpenShift instance running on a laptop. I installed Docker Toolbox (I'm only running Home edition of Windows 10), and then got the oc command line tool and created the cluster. That all works. My question is how can I then point a web browser in Windows to see the OpenShift console? I see that there is a way to start containers in Docker and port forward local ports to the containers, but I'm not sure how to do this with the cluster started by the oc command. Is there a way to do it? Also curious about how you would access any of the other Docker containers that are created by deploying on the cluster?

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994

**Comment by tellmejeff** [comment]
Apparently I was just doing something wrong last night because I'm able to hit it just fine today. Closing.

**Comment by JayGlass** [comment]
Hi TellMeJeff!  Was this with regards to getting openshift/origin running under windows10?  Did you get it running?  I fired it up but had a lot of errors so figured it was likely not functioning properly so abandoned it for now.  Did you finish your documentation if it was with regards to origin on windows10?  I'd like to get it working as well!

**Comment by tellmejeff** [comment]
It was, but I forked over the $200 and upgraded to the pro edition which has Hyper-V and it works fine with the latest version of Docker.

**Comment by JayGlass** [comment]
Thanks for replying!

  So the pro edition of win 10?  I have win 10 as it's a work laptop...
 mind sharing your documentation for getting it going, and again, we are
talking about origin correct?  I tried to fire it up on my laptop after
getting hyper-v enabled and docker up, running and tested but it (origin)
spit out a bunch of errors, not sure I tried hard enough.  I sent you an
invite on LinkedIn if you dont mind!

Jay

   

  Quoting Jeffrey Poore <notifications@github.com>:

> It was, but I forked over the $200 and upgraded to the pro edition which
> has Hyper-V and it works fine with the latest version of Docker.
>
>   —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub[1], or mute the
thread[2].
>       



Links:
------
[1] https://github.com/openshift/origin/issues/12706#issuecomment-290251995
[2]

**Comment by tellmejeff** [comment]
I basically just used the oc cluster up method for running OpenShift which you can follow on the openshift.org website. If you are seeing errors it is probably Docker having issues getting the images with OpenShift in them, but those usually can be worked out. What errors are you seeing?
