### ISSUE TITLE
Template metadata for Service Catalog proposal

### ISSUE THREAD

**Issue by bparees** [openshift/origin#12719]
The service catalog defines metadata that services can define for the catalog entry:
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#catalog-metadata

Our templates also define some metadata today:
https://github.com/openshift/origin/blob/master/examples/quickstarts/nodejs-mongodb.json#L7-L10
https://github.com/openshift/origin/blob/master/examples/quickstarts/nodejs-mongodb.json#L13

I'd like to propose a mapping of existing fields/annotations into the service catalog metadata, along with new annotations:

Mappings of existing metadata:

* template.Name -> name
* template.Annotations['description'] -> description
* template.Annotations['openshift.io/display-name'] -> displayName

New annotations+mapping:

* template.Annotations['template.openshift.io/image-url'] -> imageUrl  (note that this is a little redundant to the icon field we already have, but unless the SC changes, I don't think we can reuse our icon field.  We might be able to drop the icon field in the future, though)
* template.Annotations['template.openshift.io/long-description'] -> longDescription
* template.Annotations['template.openshift.io/provider-display-name'] -> providerDisplayName
* template.Annotations['template.openshift.io/documentation-url'] -> documentationUrl
* template.Annotations['template.openshift.io/support-url'] -> supportUrl

I don't think we can map our existing "message" field to any of the SC metadata because it's intended to be information provided to the user after they instantiate the template, not beforehand.

Things to be approved by @openshift/api-review and @pmorie 

1) Using annotations to introduce the additional metadata (rather than first class fields)
2) The mapping of existing fields/annotations
3) The names and set of annotations being introduced

@pmorie also need your confirmation that this is the finalized (or at least very nearly finalized) set of service metadata.

this will be in fulfillment of https://trello.com/c/8Q9GhXrV

**Comment by bparees** [comment]
@pmorie @openshift/api-review bump.

**Comment by deads2k** [comment]
lgtm.  Leaving untagged for @pmorie to have a chance.

**Comment by bparees** [comment]
@pmorie bump

**Comment by bparees** [comment]
@pmorie among other questions I have about this:  I don't see how we are supposed to provide parameter metadata as part of a catalog entry.

I see the broker api has parameters on the provision call, but how does the catalog know what parameters to accept/collect from the user?

**Comment by pmorie** [comment]
>  I don't see how we are supposed to provide parameter metadata as part of a catalog entry.

It's currently an opaque blob.  Work is underway to add a parameter schema, but isn't complete yet.

**Comment by bparees** [comment]
@pmorie is that the "metadata" field listed here:
https://github.com/pmorie/servicebroker/blob/4c8cd1a497a3e2ea6932b56a2c215a79afe0ae7f/spec.md#response

?

**Comment by pmorie** [comment]
@bparees that's actually metadata about the service in general.  As far as I can tell, current broker authors use the long description to document which parameters are accepted and what their types are.  The proposal I'm referring to is https://github.com/openservicebrokerapi/servicebroker/pull/74

Overall this LGTM.

**Comment by bparees** [comment]
> As far as I can tell, current broker authors use the long description to document which parameters are accepted and what their types are. 

@pmorie ok..so we will assume that new parameters field exists and we will *not* use the long-description field for that purpose (we'll use it for a real long description).

**Comment by bparees** [comment]
@jim-minter sorry I should have tagged you into this previously.

**Comment by jim-minter** [comment]
np; lgtm!
