### ISSUE TITLE
admission plugin LimitPodHardAntiAffinityTopology causes anti affinity e2e failures

### ISSUE THREAD

**Issue by aveshagarwal** [openshift/origin#12712]
The admission plugin LimitPodHardAntiAffinityTopology only allows the topology key: kubernetes.io/hostname 

so anti pod affinity e2e tests that are based on topology keys consisting of zones (e2e.inter-pod-affinity.kubernetes.io/zone) fail as the plugin does not allow any key other than: kubernetes.io/hostname. 

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1413748

The failed tests are: 

[It] validates that InterPodAntiAffinity is respected if matching 2
[It] validates that InterPod Affinity and AntiAffinity is respected if matching

So why is the plugin enabled by default?

**Comment by aveshagarwal** [comment]
@derekwaynecarr

**Comment by aveshagarwal** [comment]
The plugin is enabled here by default: https://github.com/openshift/origin/blob/master/pkg/cmd/server/start/admission.go#L68

**Comment by ncdc** [comment]
@aveshagarwal see https://github.com/kubernetes/kubernetes/issues/19914 for possible justification. I think if we want these particular e2es to pass, we need to consider starting up the master with a different admission configuration specifically for this test. cc @deads2k @liggitt @smarterclayton

**Comment by smarterclayton** [comment]
The plugin was enabled because you shouldn't be able to break the cluster as an end user.  In 1.5, is this safe to enable?

**Comment by ncdc** [comment]
@smarterclayton do you mean disable?

**Comment by derekwaynecarr** [comment]
affinity is alpha in k8s 1.5.  as a result, I don't think we should have a plug-in default to on for an annotation based feature like this.  it's promoted to beta in k8s 1.6, we should look to default to on at that point.  any objections to disabling plugin?

**Comment by aveshagarwal** [comment]
https://github.com/openshift/origin/pull/12782 to fix this issue.

**Comment by smarterclayton** [comment]
No objects to disable.
