### ISSUE TITLE
oc cluster up --no-bootstrap

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#12714]
There's a use case where someone creating a cluster will may want it empty as they will bootstrap it after the fact. Example, minishift.
It would be nice to be able to pass a command line argument --no-bootstrap (e.g.) that will not:
- create the default project
- create the default user
- load the templates and imagestreams

cc/ @hferentschik @LalatenduMohanty

**Comment by LalatenduMohanty** [comment]
+1 , It can extended by minishift in a way that it would give advance users more freedom to do stuff . Refer https://github.com/minishift/minishift/issues/273

**Comment by bparees** [comment]
unless this is a requirement for minishift, i am not in favor of this.

**Comment by csrwng** [comment]
https://trello.com/c/ZKtp90ko/1252-cluster-up-provide-a-no-bootstrap-option

**Comment by hferentschik** [comment]
> unless this is a requirement for minishift, i am not in favor of this.

it is not a requirement, but imo gives a bit more flexibility, not only for Minishift. I am in particular thinking of the default templates being created.

**Comment by bparees** [comment]
> it is not a requirement, but imo gives a bit more flexibility, not only for Minishift. I am in particular thinking of the default templates being created.

i understand the desire, but the stated purpose of oc cluster up is not to give users a way to create customized/flexible clusters, it is to give them a quick and easy way to run a cluster that we know will work.  The more options we start giving people, the more differences crop up in their clusters, the more stuff we can't assume will "just work" for a user and the more questions we have to ask to support them.

if you want a customized cluster, you should be using the primarily openshift install paths.

**Comment by hferentschik** [comment]
I hear where you are coming from. @csrwng and I had been discussing ways to make things more configurable, w/o the need to change the user experience. The idea would be to change certain behavior based on say environment variables. Something which is not directly exposed to the user via the CLI. This would allow for example Minishift to gain a bit more control over some of the details.
