### ISSUE TITLE
Document folders/sub-folders of code using README files

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#12739]
Documentation for logical groupings of code (folders/sub-folders) should be included in README files within those folders/sub-folders.  For example:  There should be a README in the pkg/build/builder folder detailing that you must build  new images ( run hack/build-images.sh ) and then start openshift with the --latest-images=true flag to test that code.  I was not able to find anywhere that this was documented and easily findable.

**Comment by mfojtik** [comment]
@coreydaley we should have `doc.go` for each package with the documentation. That can be browsed via godoc.

I agree that for "important" packages we might have special README.
