### ISSUE TITLE
Running ipfailover with two interfaces

### ISSUE THREAD

**Issue by misabel** [openshift/origin#12746]
Is there a way to configure one ipfailover deploymentconfig can serve two different interfaces?
Or do two separate dc's need to be created?

I'm currently running Openshift v1.3.1

What's happening now is I run:
`oadm ipfailover ipfailover --replicas=2 --selector="ha-router=infra" --virtual-ips="171.21.7.123, 191.21.7.123" --service-account=ipfailover --create`

This succesfully deploys to the desired nodes, but when I check one of the nodes keepalived config

[keepalived.txt](https://github.com/openshift/origin/files/743518/keepalived.txt)
 it does add a second vrrp_instance, but it chooses enp1s0f0 instead of the second interface enp1s0f1 which is the one 192.21.7.123 is running on. 

Is there a way to differentiate these out when first creating the ipfailover pods?

**Comment by knobunc** [comment]
@misabel it looks like you would like us to change the ipfailover so that the interface can be specified manually, and if given, override the default interface detection.  Without that, you can't do what you want.
