### ISSUE TITLE
oc cluster up - ability to specify the port other than 8443

### ISSUE THREAD

**Issue by jwendell** [openshift/origin#12755]
I wonder if it's possible to specify the port to be used by the cluster other than the default 8443.

I tried to pass --public-hostname=0.0.0.0:10000 but it didn't work.

An use case would be the need to start more than one instance in the same machine.

##### Version
oc v1.5.0-alpha.2+92ce2c9-317
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.0.108:8443
openshift v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4

**Comment by jwendell** [comment]
It seems it's not possible... looking at the source, port 8443 is hard coded everywhere...
Also, origin starts up a number of services that expose the port to the host, like etcd, and dns.

So, for my use case (be able to spawn more than one origin per machine), I think the solution would be to be able to specify an argument, say 'bind=1.2.3.4' that would tell origin to use this address to all services it spawns. Should I open a new issue for this?

**Comment by ledroide** [comment]
It is still impossible to define another port than 8443. 
_oc v3.7.2+282e43f_
Please add a parameter to specify the port
