### ISSUE TITLE
Output of oc version contains file name

### ISSUE THREAD

**Issue by rhopp** [openshift/origin#12768]
Normal output of "oc version" looks like:
```
$ ./oc version
oc v3.4.1.2
kubernetes v1.4.0+776c994

```
 But when I rename oc to something else, the output of "version" contains file name:
```
$ mv oc "what the heck?" 
```
```
$ ./what\ the\ heck\? version
what the heck? v3.4.1.2
kubernetes v1.4.0+776c994
```

##### Steps To Reproduce
1. rename "oc" to "something else"
2. run `something\ else version`

Is this intended? This breaks our tooling (Devstuidio) as we are parsing this output for vesion and when one extracts oc to directory when oc is already present the system may rename it to something like "oc 2".

**Comment by adietish** [comment]
Related to this is that the enterprise version of the binary will produce the very same version info beside the version being 3.x (vs. 1.x for the github version).

**Comment by juanvallejo** [comment]
Thanks for catching this, opened PR here: https://github.com/openshift/origin/pull/12781

> Related to this is that the enterprise version of the binary will produce the very same version info: There's nothing but the version (1.x for github, 3.x for enterprise) to distinguish them. Not ideal imho

Unfortunately, I am not sure that there is something we can do about this, cc @deads2k

**Comment by deads2k** [comment]
> Unfortunately, I am not sure that there is something we can do about this, cc @deads2k

I'll punt to @smarterclayton.
