### ISSUE TITLE
Automatic Addition of a Source Secret doesn't work

### ISSUE THREAD

**Issue by jihyun00** [openshift/origin#12766]
I wanted to add a source secret automatically, so I found a document about it (https://docs.openshift.org/latest/dev_guide/builds.html#automatic-addition-of-a-source-secret-to-a-build-configuration)

I tested but it didn't work on my machine.

After I read origin source code, I found it only works on Openshift origin v1.5.0-alpha.2 .

I wonder if it's possible to add that function on Openshift origin v1.4.1 .

##### Version
```
[provide output of the `openshift version` or `oc version` command]
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://fusiondv01gm:443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994
```

**Comment by bparees** [comment]
No, we generally do not backport features to older versions of origin, sorry.
