### ISSUE TITLE
Deployments don't work with oc logs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12789]
```
$ oc logs deployment/prometheus
error: cannot get the logs from extensions/__internal, Kind=Deployment
```

Should work.

**Comment by pweil-** [comment]
removing from blocker list as this is an upstream dependency that is not a regression.

**Comment by soltysh** [comment]
I'm setting this for 1.6 milestone since this should be fixed with the next rebase. I'm also setting this to P1 to track it during bug burdown.

**Comment by soltysh** [comment]
This is now solved.
