### ISSUE TITLE
oc status doesn't show details of deployments

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12790]
I swear we fixed this, but maybe we just tolerated it.

```
svc/prometheus (all nodes):30900 -> 9090
  pod/prometheus-3729295909-qd1wb runs prom/prometheus
```

deployment should show up here.

**Comment by juanvallejo** [comment]
cc @deads2k

**Comment by smarterclayton** [comment]
I may never have added it.

**Comment by kargakis** [comment]
@mfojtik

**Comment by deads2k** [comment]
> I may never have added it.

We never did.  @mfojtik or @soltysh had a pull for it as I recall.

**Comment by mfojtik** [comment]
@deads2k I had (have?) but the problem with this was that there was too much duplication to handle both DeploymentConfig and Deployment (basically you have to copy&paste a large chunks of code). So we postponed it till we refactor how oc status works... 

Do we consider this a blocker for 1.5? I would love to work on this for 1.6 (not sure we have enough time for 1.5)

**Comment by soltysh** [comment]
Ref: https://github.com/openshift/origin/pull/10490

**Comment by kargakis** [comment]
Dupe of https://github.com/openshift/origin/issues/10411
