### ISSUE TITLE
[RFE] support "additive" scripts for STI process

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1279]
Currently, when customizing the STI scripts, one must take the original script and then add to it.

It would be nice if we supported some kind of additive mechnaism. Either by indicating it in the script, or by having a script of the same name with a number (eg: ##-assemble [happens before assemble] and assemble-## [happens after assemble])

**Comment by bparees** [comment]
this should be opened against https://github.com/openshift/source-to-image instead as that is the component that provides the override functionality.

**Comment by thoraxe** [comment]
Opened: https://github.com/openshift/source-to-image/issues/154
