### ISSUE TITLE
Flake: idle.sh:36: executing 'oc get pod -l app=idling-echo -o go-template='{{ len .items }}'' expecting any result and text '2'

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#12797]
Seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/10857/testReport/junit/github/com_openshift_origin_test_cmd_idle_by-label/test_cmd_idle_sh_36__executing__oc_get_pod__l_app_idling_echo__o_go_template_____len__items______expecting_any_result_and_text__2___re_trying_every_0_2s_until_completion_or_60_000s/):

```
=== BEGIN TEST CASE ===
test/cmd/idle.sh:36: executing 'oc get pod -l app=idling-echo -o go-template='{{ len .items }}'' expecting any result and text '2'; re-trying every 0.2s until completion or 60.000s
FAILURE after 60.007s: test/cmd/idle.sh:36: executing 'oc get pod -l app=idling-echo -o go-template='{{ len .items }}'' expecting any result and text '2'; re-trying every 0.2s until completion or 60.000s: the command timed out
Standard output from the command:
0
... repeated 91 times
Standard error from the command:
No resources found.
... repeated 91 times
=== END TEST CASE ===
```

**Comment by knobunc** [comment]
We bumped the timeout for this to 120s recently.

**Comment by DirectXMan12** [comment]
@knobunc this is in in the command tests, it appears, which don't actually do an unidling (just idling).

**Comment by derekwaynecarr** [comment]
no occurrences noted since bump, so i am lowering priority as this should not be a release blocker.
