### ISSUE TITLE
flake: error: replication controller "docker-registry-1" has failed progressing

### ISSUE THREAD

**Issue by sjenning** [openshift/origin#12806]
I've tried to merge https://github.com/openshift/origin/pull/12762 twice and both times got

```
error: replication controller "docker-registry-1" has failed progressing
```

Any insight?

**Comment by ncdc** [comment]
I also see this:

```
I0202 18:56:09.535338    9406 factory.go:488] About to try and schedule pod docker-registry-1-deploy
I0202 18:56:09.535351    9406 scheduler.go:93] Attempting to schedule pod: default/docker-registry-1-deploy
I0202 18:56:09.535364    9406 factory.go:511] Ignoring node 172.18.5.114 with Ready condition status False
I0202 18:56:09.535372    9406 scheduler.go:97] Failed to schedule pod: default/docker-registry-1-deploy
I0202 18:56:09.535376    9406 factory.go:581] Unable to schedule default docker-registry-1-deploy: no nodes are registered to the cluster; waiting
```

**Comment by ncdc** [comment]
Yeah, it looks like the node never transitioned to ready.

**Comment by ncdc** [comment]
It looks like the openshift process was only alive for 12 or 13 seconds. I'm surprised the DC would transition to Failed that quickly, but I'm not up to speed with the DC inner workings. Here's the build console in question if anyone feels like looking in more detail: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/10984/consoleFull

**Comment by mfojtik** [comment]
@ncdc seems like the node problem (although the quick transition of DC is worrysome)... mind bumpint this to P2? (seems pretty rare flake).

**Comment by ncdc** [comment]
P2 works for me

**Comment by smarterclayton** [comment]
What "node problem"

**Comment by ncdc** [comment]
@mfojtik actually I think this is probably deployment related. It looks like, given a few more seconds, the node probably would have returned a ready condition of true.

**Comment by mfojtik** [comment]
@ncdc @smarterclayton the timing from the log:

```
I0202 18:56:06.486608    9406 panics.go:76] POST /oapi/v1/namespaces/default/deploymentconfigs/docker-registry/instantiate: (53.809838ms) 500
[logging stack trace snip]
logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12P\n\x04\n\x00\x12\x00\x12\aFailure\x1a:deployment config \"docker-registry\" cannot be instantiated\"\x000\xcc\x01\x1a\x00\"\x00"
 18:56:09.535376    9406 factory.go:581] Unable to schedule default docker-registry-1-deploy: no nodes are registered to the cluster; waiting
```

(I would expect the DC controller will reconcile when the node is available for the deployer pod to run). @kargakis do you remember what the instantiate endpoint does in that case?

**Comment by kargakis** [comment]
The controllers have no notion of nodes being up or down. If this depends on instantiate we can retry longer with a backoff.

**Comment by mfojtik** [comment]
@kargakis this haven't reccured recently, but I guess we want to still increase the interval till we fail the deployment because there are no nodes available?

**Comment by mfojtik** [comment]
Closing due to age.

**Comment by simo5** [comment]
I am now seeing this error here:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19328/test_pull_request_origin_extended_ldap_groups/27/

Any insights on what it may be ?

**Comment by simo5** [comment]
sounds like the job was using outdated images, closing again
