### ISSUE TITLE
OC not compatible with the version of windows

### ISSUE THREAD

**Issue by aerogelio** [openshift/origin#12809]
Whe I try run command OC throw message error: 

```
This version of C:\Users\rogelio\Documents\path\oc.exe is not compatible with th
e version of Windows you're running. Check your computer's system information to
 see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and
 then contact the software publisher.
```

##### Version
1.4.1

##### Steps To Reproduce
1. Download version 1.4.1 for windows, here: https://github.com/openshift/origin/releases
2. Add path, run.

##### Current Result
Show this message:
This version of C:\Users\rogelio\Documents\path\oc.exe is not compatible with th
e version of Windows you're running. Check your computer's system information to
 see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and
 then contact the software publisher.

##### Expected Result
Run command.

##### Additional Information
My OS is Window 7 32 bits, professional.
My operating system is not original.

**Comment by stevekuznetsov** [comment]
@smarterclayton do we intend to ship 32bit windows and mac builds of the client?

**Comment by smarterclayton** [comment]
No

**Comment by juanvallejo** [comment]
Closing, as this is not something we can address.
@aerogelio please try running `oc` in a 64-bit version of Windows if possible. Alternatively, we also build for 32-bit versions of Linux: https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-client-tools-v1.4.1-3f9807a-linux-32bit.tar.gz

**Comment by aerogelio** [comment]
Later I'll see if you can upload a video with the process I follow maybe I'm doing something wrong.

**Comment by aerogelio** [comment]
Thank you I am already running from debian 8, later I'll see if you can upload a video with the process I follow maybe I'm doing something wrong.

**Comment by satourne** [comment]
Hi,
Which oc.exe version is designed for a Windows Vista 32bits OS, please ?
Thank you.
