### ISSUE TITLE
"oc create secret" can't handle mixed case file names on Windows

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#12801]
[provide a description of the issue]
When trying to make secrets from a file using oc on windows, the command fails if the filename is mixed case. 
##### Version
[provide output of the `openshift version` or `oc version` command]
PS C:\Users\steve\Downloads> .\oc.exe version
oc v3.3.1.3
kubernetes v1.3.0+52492b4
features: Basic-Auth

PS C:\Users\steve\Downloads> oc version
oc v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
features: Basic-Auth

##### Steps To Reproduce

PS C:\Users\steve\Downloads> .\oc.exe create secret generic google-creds --from-file=./googleRoadshow-036eb8bfdc71.json
error: googleRoadshow-036eb8bfdc71.json is not a valid key name for a secret
PS C:\Users\steve\Downloads> mv .\googleRoadshow-036eb8bfdc71.json .\google-036eb8bfdc71.json
PS C:\Users\steve\Downloads> .\oc.exe create secret generic google-creds --from-file=./google-036eb8bfdc71.json
secret "google-creds" created

**Comment by juanvallejo** [comment]
I am no longer able to reproduce this issue with v3.4 on windows, maybe the fix is something that could be backported? cc @smarterclayton

**Comment by juanvallejo** [comment]
Closing this, as it is not present in clients 3.4 and above.

cc @fabianofranz
