### ISSUE TITLE
After "oc cluster up/down", default router no long works

### ISSUE THREAD

**Issue by suibinz** [openshift/origin#12810]
##### Version
openshift v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. start all-in-on cluster using "oc cluster up"  (following https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md
All services are working correctly (i.e. python app, jenkins, gogs, etc.)
2. after "oc cluster down" and "oc cluster up (with existing data/config), all services routing stop working and http is getting:

"Application is not available

The application is currently not serving requests at this endpoint. It may not have been started or is still starting."

##### Current Result
3) tried a few things but still the same result:
a) redeploy apps;
b) delete and create new routes
c) create new app with new route

4) This is NOT an external dns problem, because I curl'ed from within the host or the origin container and getting the same result. And Console is working properly.

5) Signed in as system:admin and the default router, and it seems working "properly"
oc describe svc/router
Name:			router
Namespace:		default
Labels:			router=router
Selector:		router=router
Type:			ClusterIP
IP:			172.30.46.31
Port:			80-tcp	80/TCP
Endpoints:		172.31.0.194:80
Port:			443-tcp	443/TCP
Endpoints:		172.31.0.194:443
Port:			1936-tcp	1936/TCP
Endpoints:		172.31.0.194:1936
Session Affinity:	None

##### Additional Information

`[root@ip-172-31-0-194 origin]# oadm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/var/lib/origin/openshift.local.config/master/admin.kubeconfig'
Info:  Using context for cluster-admin access: 'default/172-31-0-194:8443/system:admin'

[Note] Running diagnostic: ConfigContexts[cicd/172-31-0-194:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

Info:  For client config context 'cicd/172-31-0-194:8443/system:admin':
       The server URL is 'https://172.31.0.194:8443'
       The user authentication is 'system:admin/172-31-0-194:8443'
       The current project is 'cicd'
       Successfully requested project list; has access to project(s):
         [dev kube-system myproject openshift openshift-infra stage cicd default]

[Note] Running diagnostic: ConfigContexts[default/paas-cumulaas-com:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

Info:  For client config context 'default/paas-cumulaas-com:8443/system:admin':
       The server URL is 'https://paas.cumulaas.com:8443'
       The user authentication is 'system:admin/172-31-0-194:8443'
       The current project is 'default'
       Successfully requested project list; has access to project(s):
         [stage cicd default dev kube-system myproject openshift openshift-infra]

[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint

Info:  Output from the diagnostic pod (image openshift/origin-deployer:v1.5.0-alpha.2):
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected

       Info:  Service account token successfully authenticated to master
       Info:  Service account token was authenticated by the integrated registry.
       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected

       [Note] Summary of diagnostics execution (version v1.5.0-alpha.2+e4b43ee):
       [Note] Completed with no errors or warnings seen.

[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint

WARN:  [DNet2002 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:82]
       Skipping network diagnostics check. Reason: Not using openshift network plugin.

[Note] Skipping diagnostic: AggregatedLogging
       Description: Check aggregated logging integration for proper configuration
       Because: No master config file was provided

[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry

WARN:  [DClu1012 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:300]
       The pod logs for the "docker-registry-1-j6fsc" pod belonging to
       the "docker-registry" service indicated unknown errors.
       This could result in problems with builds or deployments.
       Please examine the log entries to determine if there might be
       any related problems:

       time="2017-02-04T21:14:23.73342784Z" level=error msg="error authorizing context: authorization header required" go.version=go1.7.4 http.request.host="172.30.1.1:5000" http.request.id=edf840c9-5451-4a93-9620-7504298fdb27 http.request.method=GET http.request.remoteaddr="172.31.0.194:35446" http.request.uri="/v2/" http.request.useragent="docker/1.12.5 go/go1.7.4 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=335376d3-b63b-40c2-8e5b-4a63b2536e16
       time="2017-02-04T21:25:08.906441017Z" level=error msg="error authorizing context: authorization header required" go.version=go1.7.4 http.request.host="172.30.1.1:5000" http.request.id=1b22159d-aaac-4143-a5e4-b8c2b5198556 http.request.method=GET http.request.remoteaddr="172.31.0.194:37580" http.request.uri="/v2/" http.request.useragent="docker/1.12.5 go/go1.7.4 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=335376d3-b63b-40c2-8e5b-4a63b2536e16
       time="2017-02-04T21:36:01.535736615Z" level=error msg="error authorizing context: authorization header required" go.version=go1.7.4 http.request.host="172.30.1.1:5000" http.request.id=ea18db32-6640-4da9-a01a-ce86816cdc1b http.request.method=GET http.request.remoteaddr="172.31.0.194:39824" http.request.uri="/v2/" http.request.useragent="docker/1.12.5 go/go1.7.4 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(go-dockerclient)" instance.id=335376d3-b63b-40c2-8e5b-4a63b2536e16
       time="2017-02-04T21:36:04.714839447Z" level=error msg="response completed with error" err.code="blob unknown" err.detail=sha256:af27e9f8b974d18bbc59b704f6c884e07dbf36bc6134793d60cfce94c77562c3 err.message="blob unknown to registry" go.version=go1.7.4 http.request.host="172.30.1.1:5000" http.request.id=fe5812bb-e253-4c40-b16f-ce20787e1664 http.request.method=HEAD http.request.remoteaddr="172.31.0.194:39843" http.request.uri="/v2/dev/testpython1/blobs/sha256:af27e9f8b974d18bbc59b704f6c884e07dbf36bc6134793d60cfce94c77562c3" http.request.useragent="docker/1.12.5 go/go1.7.4 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(go-dockerclient)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=40.859489ms http.response.status=404 http.response.written=157 instance.id=335376d3-b63b-40c2-8e5b-4a63b2536e16 vars.digest="sha256:af27e9f8b974d18bbc59b704f6c884e07dbf36bc6134793d60cfce94c77562c3" vars.name="dev/testpython1"
       time="2017-02-04T21:36:04.847409875Z" level=error msg="response completed with error" err.code="manifest invalid" err.detail="manifest V2 schema 2 not allowed" err.message="manifest invalid" go.version=go1.7.4 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.host="172.30.1.1:5000" http.request.id=a3888b73-b689-4eb2-b936-f2720905aa7b http.request.method=PUT http.request.remoteaddr="172.31.0.194:39848" http.request.uri="/v2/dev/testpython1/manifests/latest" http.request.useragent="docker/1.12.5 go/go1.7.4 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(go-dockerclient)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=23.308945ms http.response.status=400 http.response.written=82 instance.id=335376d3-b63b-40c2-8e5b-4a63b2536e16 vars.name="dev/testpython1" vars.reference=latest
       time="2017-02-04T21:36:08.803214423Z" level=error msg="error authorizing context: authorization header required" go.version=go1.7.4 http.request.host="172.30.1.1:5000" http.request.id=3540f052-8979-4459-9ac0-145bd25ce46b http.request.method=GET http.request.remoteaddr="172.31.0.194:39860" http.request.uri="/v2/" http.request.useragent="docker/1.12.5 go/go1.7.4 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=335376d3-b63b-40c2-8e5b-4a63b2536e16

[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects

Info:  clusterrolebinding/cluster-admins has more subjects than expected.

       Use the `oadm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.

Info:  clusterrolebinding/cluster-admins has extra subject {ServiceAccount default pvinstaller    }.

[Note] Running diagnostic: ClusterRoles
       Description: Check that the default ClusterRoles are present and contain the expected permissions

[Note] Running diagnostic: ClusterRouterName
       Description: Check there is a working router

[Note] Running diagnostic: MasterNode
       Description: Check if master is also running node (for Open vSwitch)

Info:  Found a node with same IP as master: 172.31.0.194

[Note] Skipping diagnostic: MetricsApiProxy
       Description: Check the integrated heapster metrics can be reached via the API proxy
       Because: The heapster service does not exist in the openshift-infra project at this time,
       so it is not available for the Horizontal Pod Autoscaler to use as a source of metrics.`

[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by knobunc** [comment]
What does 'oc logs' say for the router pod?  I assume this is a single node cluster.  And what does 'oc get endpoints' say?

**Comment by suibinz** [comment]
Might have something to do with change of cluster IP between cluster go up/down (using different EC2 instance private IP). [https://github.com/openshift/origin/issues/10690](url)

I have yet to try to see if I can manually change the save config/data file can accommodate the IP changes between up/down.  But it is probably not a real use case that needs to be supported.
