### ISSUE TITLE
Router stop working with 3000+ routes.

### ISSUE THREAD

**Issue by mignev** [openshift/origin#12813]
Hello guys,
I've just tested creating of 3000+ routes and `openshift-router` become unhealthy and unresponsive.

##### Version

oc v1.4.1
openshift v1.4.1
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0

##### Steps To Reproduce 
```
oc project myproject

for i in {1..10000}; do oc create route edge myroute$i --service=mysvc --hostname=ssl-route-mysvc$i.example.com; done
```

##### Current Result
What I watched:
1. openshift-router makes 3MB-50MB/s Disk Writes
2. haproxy eats up to 70GB of RAM (just don't have server with more ram for this test.)
3. Cannot load the routes after 2500th-2700th route from the config.

**Comment by knobunc** [comment]
You are probably blowing up your APR cache.  Try the suggestions in https://trello.com/c/qI628QaP

**Comment by mignev** [comment]
Hi @knobunc thank you for the idea ... yes this fixed the issues up there, but with 10k routes the routers doesn't work anyways .... even they don't load the routes after restart for example.

The output is the standard, but there are 10k routes should be loaded.
```
I0206 17:18:36.497691       1 router.go:437] Router reloaded:
 - Checking HAProxy /healthz on port 1936 ...
 - HAProxy port 1936 health check ok : 0 retry attempt(s).
```

In your opinion does this could be connected with the above or I should open another issue?

**Comment by knobunc** [comment]
You can reopen this.  But the quote above looks ok to me... are the routes not loaded?

**Comment by mignev** [comment]
Yes, they are not loaded. I was waiting for few minutes but nothing happened.

**Comment by mignev** [comment]
These are the results with 8000 routes before the router restart.

```
for i in {1..10000}; do time curl -k https://ssl-route-mysvc2.example.com/; done

real  1m18.812s
user  0m0.019s
sys 0m0.031s
Hello World :)

real  1m15.660s
user  0m0.098s
sys 0m0.032s
Hello World :)

real  1m16.695s
user  0m0.076s
sys 0m0.033s
Hello World :)

real  1m17.008s
user  0m0.108s
sys 0m0.039s


Hello World :)

real  1m16.320s
user  0m0.091s
sys 0m0.038s
```

After the restart as I mentioned the router it doesn't start at all.

While I'm looking at `top` I can't see any of `openshift-router` or `haproxy` processes.

**Comment by knobunc** [comment]
What does 'oc logs <routerpodname>' show?

**Comment by mignev** [comment]
This is the return of oc logs

```
[root@master01 ~]# oc logs router-12-5b65f
I0208 14:21:05.515787       1 router.go:229] Router is including routes in all namespaces
I0208 14:21:05.841821       1 router.go:437] Router reloaded:
 - Checking HAProxy /healthz on port 1936 ...
 - HAProxy port 1936 health check ok : 0 retry attempt(s).
[root@master01 ~]#
```

From time to time after the deletion of pod doesn't return anythink ... just waiting and nothing, but I can't find when did it.
