### ISSUE TITLE
Deleted service serving certificate secret is not recreated

### ISSUE THREAD

**Issue by abutcher** [openshift/origin#12834]
Deleting a service serving certificate secret does not cause the secret to be recreated. A service serving certificate secret currently must be deleted and service annotations (`service.alpha.openshift.io/serving-cert-secret-name`, `service.alpha.openshift.io/serving-cert-signed-by`) must be removed/re-added to trigger recreation.

##### Version
```
openshift v3.5.0.17+c55cf2b
kubernetes v1.5.2+43a9be4
etcd 3.1.0
```
##### Steps To Reproduce
1. Annotate service with `service.alpha.openshift.io/serving-cert-secret-name=NAME`
2. Ensure service serving certificate secret is created.
3. Delete service serving certificate secret.

##### Current Result
Deleted service serving certificate secret **is not** recreated.

##### Expected Result
Deleted service serving certificate secret **is** recreated.

/cc @deads2k @smarterclayton

**Comment by deads2k** [comment]
@mfojtik @soltysh
