### ISSUE TITLE
sourceSecret ignored when strategy=docker

### ISSUE THREAD

**Issue by sglebs** [openshift/origin#12847]
If you have a private git repository and try to follow the tips at https://blog.openshift.com/deploying-from-private-git-repositories/ it will work only if you use --strategy=source. As soon as you add a Dockerfile at the root of your project, it will fail to build because OpenShift claims it cannot clone the repo. It is as if sourceSecret is being ignored when --strategy=docker kicks in.

##### Version

oc v1.3.3
kubernetes v1.3.0+52492b4
features: Basic-Auth

Vagrantfile:

```
  config.vm.box = "thesteve0/openshift-origin"
  # uncomment this line if you downloaded the box and want to use it instead
  # config.vm.box = "openshift3"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "10.2.2.2"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.hostname = "origin"

  config.vm.provider "virtualbox" do |vb|
     #   vb.gui = true
     vb.memory = "5096"
     vb.cpus = 2
     vb.name = "origin-1.3.0"
  end

end
```

##### Steps To Reproduce

  * oc new-app --strategy=docker --name=ping-mqm-dev https://github.com/sglebs/ping.git#locust -e PORT=8080 -e PROCFILE_TARGET=web 
  * It will build fine

  * Now copy this ping project to a remote, private repo yourrepo.com 
  * Follow the steps at https://blog.openshift.com/deploying-from-private-git-repositories/ :
    * oc project mqm
    * oc secrets new scmsecret ssh-privatekey=$HOME/.ssh/id_rsa
    * oc secrets add serviceaccount/builder secrets/scmsecret
    * oc new-app --strategy=docker --name=ping-mqm-dev https://yourrepo.com/ping.git#locust -e PORT=8080 -e PROCFILE_TARGET=web 
    * oc patch bc ping-mqm-dev -p '{"spec":{"source":{"sourceSecret":{"name":"scmsecret"}}}}' 
    * It will fail to build. It says it cannot git clone due to credentials/permissions. You can retry as many times as you want, it will always fail.

   * Now try again with source-based (non-docker), it will work fine. First public repo:
    * oc new-app --strategy=source --name=ping-mqm-dev https://github.com/sglebs/ping.git#master -e PORT=8080 -e PROCFILE_TARGET=web
    * works fine

  * Now try again with source-based (non-docker) in a private repo, it will work fine:
   * copy this ping project to a remote, private repo yourrepo.com 
  * Follow the steps at https://blog.openshift.com/deploying-from-private-git-repositories/ :
    * oc project mqm
    * oc secrets new scmsecret ssh-privatekey=$HOME/.ssh/id_rsa
    * oc secrets add serviceaccount/builder secrets/scmsecret
    * oc new-app --strategy=source --name=ping-mqm-dev https://yourrepo.com/ping.git#master -e PORT=8080 -e PROCFILE_TARGET=web
    * oc patch bc ping-mqm-dev -p '{"spec":{"source":{"sourceSecret":{"name":"scmsecret"}}}}' 
    * works fine

Conclusion: sourceSecret is not being honoured when --strategy=docker (when you use a Dockerfile at the root dir of your project)

##### Current Result

Fails to clone the sources, as if the secret had not been installed.

##### Expected Result

git clone should work fine, just like when --strategy=docker

**Comment by bparees** [comment]
please provide level 5 build logs and also the buildconfig resource definitions for both your source and docker builds.

**Comment by bparees** [comment]
also you're on a fairly old version of openshift, can you confirm this problem exists with 1.4?

**Comment by bparees** [comment]
i'm not able to recreate this, lowering severity while we work out @sglebs' issue.

**Comment by sglebs** [comment]
I got the Vagrantfile from https://www.openshift.org/vm/Vagrantfile

I will hunt for a newer one and use it.

**Comment by sglebs** [comment]
https://www.openshift.org/vm/ mentions Minishift, which is a BETA and V3, so I suppose it is no good because you want me to try 1.4, right? I will continue the hunt, I know I stumbled upon a page which taught how to have a Vagrantfile pointing at the latest OpenShift (which did not work for me back then, so that is why I decided to stick to the one I use / older). Feel free to post a URL to a Vagrantfile which you prefer that I use for reproducing this. Thanks.

**Comment by bparees** [comment]
@sglebs this should be working in 1.3 also, so if you want to provide the debug info i requested above from your 1.3 environment i can at least take a look at that.

**Comment by sglebs** [comment]
I managed to get Minishift going. I also pushed my ping project to a private repo at BitBucket, to make it easier to reproduce. I will try it all again and will get back here.

**Comment by sglebs** [comment]
Well, it turns out that even building from source is failing with Minishift. Did things change in the json in 1.4? Here:

```
Configuration

Build Strategy:
Source
Source Repo:
ssh://git@bitbucket.org/debugteam/ping.git
Source Ref:
master
Builder Image:
openshift/python:3.5
Output To:
mqm/ping-mqm-dev:latest
Run Policy:
Serial 
```

The authentication error:

```
Cloning "ssh://git@bitbucket.org/debugteam/ping.git" ...
error: build error: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Resources/Secrets does show my secret (RSA private key):

```
scmsecret created 42 minutes ago
Type:
Opaque
SSH Private Key:
*****
```

And this is the bc:

```json
{
    "kind": "BuildConfig",
    "apiVersion": "v1",
    "metadata": {
        "name": "ping-mqm-dev",
        "namespace": "mqm",
        "selfLink": "/oapi/v1/namespaces/mqm/buildconfigs/ping-mqm-dev",
        "uid": "0d308eca-eec5-11e6-87b5-360667dc33fd",
        "resourceVersion": "1862",
        "creationTimestamp": "2017-02-09T12:41:17Z",
        "labels": {
            "app": "ping-mqm-dev"
        },
        "annotations": {
            "openshift.io/generated-by": "OpenShiftNewApp"
        }
    },
    "spec": {
        "triggers": [
            {
                "type": "GitHub",
                "github": {
                    "secret": "fTODkE7WDIyyAOSlnHjA"
                }
            },
            {
                "type": "Generic",
                "generic": {
                    "secret": "0JhF2diZPNjoQlqid5hV"
                }
            },
            {
                "type": "ConfigChange"
            },
            {
                "type": "ImageChange",
                "imageChange": {
                    "lastTriggeredImageID": "centos/python-35-centos7@sha256:1f1edfbd9384a0d2eec00dbd363afac9fc72980865dc4572aae574de2b5c3899"
                }
            }
        ],
        "runPolicy": "Serial",
        "source": {
            "type": "Git",
            "git": {
                "uri": "ssh://git@bitbucket.org/debugteam/ping.git",
                "ref": "master"
            },
            "sourceSecret": {
                "name": "scmsecret"
            }
        },
        "strategy": {
            "type": "Source",
            "sourceStrategy": {
                "from": {
                    "kind": "ImageStreamTag",
                    "namespace": "openshift",
                    "name": "python:3.5"
                }
            }
        },
        "output": {
            "to": {
                "kind": "ImageStreamTag",
                "name": "ping-mqm-dev:latest"
            }
        },
        "resources": {},
        "postCommit": {}
    },
    "status": {
        "lastVersion": 2
    }
}
```

This is how I enabled the secret (followed the tip in the article I mentioned at the top):
```
oc patch bc ping-mqm-dev -p '{"spec":{"source":{"sourceSecret":{"name":"scmsecret"}}}}' 
```

I did check at BitBucket and my public RSA key is there, corresponding to the private RSA key which I installed under OpenShift.

Did the json location change? Do I need to tweak my "oc patch" line above?

**Comment by sglebs** [comment]
Meanwhile, I am trying alternatives:

```
oc set build-secret --source bc/ping-mqm-dev scmsecret
```

Unfortunately this fails, see ticket #12888

**Comment by sglebs** [comment]
This one made it work again for source-based builds:

```
oc secrets link builder scmsecret
```

I will try for docker-based builds now.

**Comment by sglebs** [comment]
The line above also worked for docker-based deploys:

```
oc secrets link builder scmsecret
```

In other words, this line from the article https://blog.openshift.com/deploying-from-private-git-repositories/ does not work (or at least is not enough):

```
oc secrets add serviceaccount/builder secrets/sshsecret
```

**Comment by sglebs** [comment]
Feel free to close this ticket.

**Comment by bparees** [comment]
@marekjelen fyi.  seems like your blog needs some updating.  I think maybe "serviceaccount/builder" is not the correct name for the builder service account.

**Comment by sglebs** [comment]
I added a comment to the blog, with the warning.

**Comment by bparees** [comment]
thanks @sglebs
