### ISSUE TITLE
oc adm diagnostics returns errors about missing iptables package/service, though firewalld is installed and working

### ISSUE THREAD

**Issue by etsauer** [openshift/origin#12845]
It appears `pkg/diagnostics` needs updating to check for either `iptables` or `firewalld`. 

##### Version
[root@master-0 ~]# oc version
oc v3.4.1.2
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master-0.d1.casl.rht-labs.com:8443
openshift v3.4.1.2
kubernetes v1.4.0+776c994

##### Steps To Reproduce
Install OpenShift with firewalld enabled.

Run `oc adm diagnostics`

##### Current Result

ERROR: [DS3002 from diagnostic UnitStatus@openshift/origin/pkg/diagnostics/systemd/unit_status.go:55]
       systemd unit atomic-openshift-node depends on unit iptables, which is not loaded.
       
       iptables is used by nodes for container networking.
       Connections to a container will fail without it.
       An administrator probably needs to install the iptables unit with:
       
         # yum install iptables
       
       If it is already installed, you may to reload the definition with:
       
         # systemctl reload iptables

##### Expected Result

No error above

**Comment by mattthias** [comment]
Hi @etsauer !

I run into the same problem today. Why did you closed the issue?


     $ oc version
      oc v1.5.0
      kubernetes v1.5.2+43a9be4
      features: Basic-Auth GSSAPI Kerberos SPNEGO

      Server https://master:8443
      openshift v1.5.0
      kubernetes v1.5.2+43a9be4


Best wishes,
Matthias
