### ISSUE TITLE
Router Integration Tests All Fail When Run From Container

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#12854]
It's a hard pre-requisite for OpenShift hosting Origin CI to be able to run the entire test suite from inside a container. Today, something is not networking correctly when the router integration tests are started from within a container.

Reproducing this can be done with:
```
$ hack/env make test-integration
```

Failures look like [this](https://ci.openshift.redhat.com/jenkins/job/base_ami/2681/console).

/cc @knobunc @marun @smarterclayton

**Comment by smarterclayton** [comment]
integration uses the docker socket to create a router that talks back to a process it runs on localhost - probably needs to listen on the host network by default rather than localhost.

**Comment by stevekuznetsov** [comment]
@knobunc
