### ISSUE TITLE
"openshift ex" commands trigger the SkyDNS port configuration logic

### ISSUE THREAD

**Issue by brenton** [openshift/origin#1285]
If you are running SkyDNS on port 53 and then on the same system (or any system listening on port 53) attempt to run "openshift ex router" you see this error message:

~~~
W0311 13:35:53.994836   11546 config.go:111] Unable to bind DNS as 0.0.0.0:53 (you may need to run as root), using 0.0.0.0:8053 which will not resolve from all locations
~~~

This is really minor, but it would likely cause confusion during beta3 since we rely a lot on the experimental commands.

**Comment by smarterclayton** [comment]
Fixed in #1263
