### ISSUE TITLE
[POST-REBASE] oc get kind/name -o=name/json/yaml exits with error if resource is not present

### ISSUE THREAD

**Issue by jupierce** [openshift/origin#12867]
There appears to be no way to programmatically test for the existence of an OpenShift resource without trying to scan human readable stderr message.

##### Version
oc v1.5.0-alpha.2+5565661-354-dirty
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://10.13.137.184:8443
openshift v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. oc cluster up
2. oc get pod/does-not-exist -o=name
3. echo $?

##### Current Result
Return status from oc is a '1' and reports 'Error from server (NotFound): pods "does-not-exist" not found'. A script cannot determine the difference between the simple absence of a resource and, for example, an inability to communicate with the server.

##### Expected Result
Using -o=name, the output should simply be an empty string with no human readable message. This will help complex programmatic actors, like Jenkins pipelines, to pick up where they left off.
For -o=json/yaml, it might also make sense to return an empty list.

**Comment by jupierce** [comment]
FYI @gabemontero @juanvallejo

**Comment by juanvallejo** [comment]
Although you can always redirect 2>/dev/null, for example, I definitely agree that it would make more sense to just return an empty list in the case of json/yaml. 

As for the exit code, it might be good to keep exit code 1 in the case of no resources so as to not break any existing scripts that rely on this, but the addition of an empty list as stated above, coupled with this exit code would allow a parser to distinguish between an actual error and a lack of resources.

cc @smarterclayton

**Comment by jupierce** [comment]
@juanvallejo If the exit code is non-zero on an empty -o=name result, a script cannot reliably tell the difference between a resource which happens not to exist and, for example, an API Server it cannot contact. That is an important difference. One is a normal part of inspecting a system's state and the other is likely a fatal error.

**Comment by jupierce** [comment]
@juanvallejo If this is a backwards compatibility concern, --ignore-not-found (similar to what oc delete supports) would work for me.

**Comment by juanvallejo** [comment]
I think `--ignore-not-found` would definitely be a reasonable approach

**Comment by gabemontero** [comment]
+1 on `--ignore-not-found`

**Comment by smarterclayton** [comment]
--ignore-not-found is at least consistent with what we do today.

Long term I'd probably say we should have distinct exit codes for certain common and scriptable errors.  I shouldn't have to come up with complex parsing rules.

**Comment by fabianofranz** [comment]
Post-rebase, fixed in https://github.com/kubernetes/kubernetes/pull/41433.

**Comment by fabianofranz** [comment]
Fixed by the Kubernetes 1.6 rebase.

**Comment by jupierce** [comment]
@gabemontero @bparees 
This should allow us to implement Selector.exists() in the Jenkins client plugin.
