### ISSUE TITLE
Proposal: Splitting controllers up and out of the masters to be pods

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12898]
There are three steps required before the controllers can be split from the masters:

1. Stop using etcd for leader election, and instead rely on https://github.com/kubernetes/kubernetes/blob/master/pkg/client/leaderelection/leaderelection.go which allows the controllers to be run on non-master nodes
2. Allow the controllers to be split up while retaining their function - either as scheduler / controller-manager / origin, or (more likely) scheduler / workload controllers / security controllers (which better aligns cache reuse).  I think we want to be able to go from monolithic controller (today) to at least 2-3 subgroups without increasing total memory use > 25%
3. Ensure the controllers can safely run as daemonsets on the masters - what resource / restart / reschedule logic do we need to safely ensure their operation?  How do we ensure the critical path of scheduler -> daemonset controller -> other controllers loop is resilient and not subject to operator error?  Do we need a "critical pod" scheduler that ensures certain pods always come back up?

We may want to work upstream to make controller-manager less monolithic as well.

In general, the goal should be to smooth the controllers out across multiple masters to better use CPU and memory, without wasting memory or causing operational headaches.

**Comment by smarterclayton** [comment]
@ncdc @deads2k @liggitt  @openshift/scale-performance-review came out of a discussion with @timothysc and myself as well as ongoing discussions about to enable kube-origin split.

**Comment by timothysc** [comment]
You absolutely need this fix https://github.com/kubernetes/kubernetes/pull/40868 prior to enabling.

**Comment by smarterclayton** [comment]
Implemented

**Comment by deads2k** [comment]
@smarterclayton is there a spot showing the ansible parameters to change to try this?  I remember you saying something about CI using it.
