### ISSUE TITLE
Registry fails to come up (`oc rollout status dc/docker-registry` exited with status 1)

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#12897]
Looks like [this](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance_future/38/consoleFull#19241280135898c58db7602c31c0eab717):
```
[INFO] Installing the registry
serviceaccount "registry" created
clusterrolebinding "registry-registry-role" created
deploymentconfig "docker-registry" created
service "docker-registry" created
Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
error: replication controller "docker-registry-1" has failed progressing
[ERROR] PID 11195: test/extended/setup.sh:151: `oc rollout status dc/docker-registry` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: test/extended/setup.sh:151: `oc rollout status dc/docker-registry`
[INFO] 		  2: test/extended/conformance.sh:7: os::test::extended::setup
[INFO]   Exiting with code 1.
```

This is due to https://github.com/kubernetes/kubernetes/issues/40973

**Comment by stevekuznetsov** [comment]
This is mostly a tracking issue for flake tagging. Not sure we need someone assigned to it but we will want it up so people can satisfy the re-test bot.

**Comment by pweil-** [comment]
> Not sure we need someone assigned to it

I'll add @legionus to make sure it gets closed out.

**Comment by stevekuznetsov** [comment]
@pweil- I also tried to address this in my PR #12901 -- let's keep an eye on the jobs and see if we are hitting it much

**Comment by stevekuznetsov** [comment]
Seems to be fixed in https://github.com/openshift/origin/pull/12901
