### ISSUE TITLE
oc cluster up has network connectivity issues for services on Docker 1.13 (Mac)

### ISSUE THREAD

**Issue by wkulhanek** [openshift/origin#12922]
When running oc cluster up (ocp 3.4.1.5) on Docker 1.13 on a Mac, services can't talk to each other. Easily reproduced by trying to set up a Gogs talking to PostgreSQL - it can't see the postgresql service.

This is on Mac (Sierra) with Docker 1.13. Given that 1.13 is the only version that is (easily) downloadable from docker.com I feel like more folks will run into this.

I understand oc cluster is only officially supported on 1.12.x - but would be nice to get a fix regardless.

**Comment by csrwng** [comment]
@wkulhanek this should be fixed in Docker for Mac 1.13.1.

**Comment by wkulhanek** [comment]
@csrwng You appear to be correct. Just tried it on 1.13.1 and it works as it should. Thanks for the confirmation!
