### ISSUE TITLE
Feature request - Versioning and rollback of scc

### ISSUE THREAD

**Issue by magick93** [openshift/origin#12937]
It is possible to rollback changes to a DC - https://docs.openshift.com/enterprise/3.0/dev_guide/deployments.html#rolling-back-a-deployment

It would be good if similar functionality was available for SCC.

Please let me know if you need more info.

**Comment by mfojtik** [comment]
@magick93 i would love to have more info please. Can you please describe the use cases for SCC rollback?

**Comment by php-coder** [comment]
@magick93 I'm closing this issue because of no feedback was provided. Please, reopen this issue when you will be able to provide uses cases.
