### ISSUE TITLE
Proposal: Long term evolution of multi-tenant cluster federation 

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#12931]
Today, OpenShift supports several core concepts around self-provisioning and tenancy that must be adapted to work in a federated environment.  In addition, many users build self-service portals on top of OpenShift for provisioning that leverage underlying APIs to impose their own provisioning and allocation strategies

1. Enable users to self-service create projects (via `projectrequest`) that use templates configured by the admin to provide an out-of-the-box restricted environment (limited quota, acl, security)
2. Limit the number of self-service projects created per user (implicit quota for projects)
3. The ability for administrators to bulk assign namespace policies and permissions into default ACL `roles` such that classes of users can be identified across the cluster
4. Allowing administrators to bulk assign namespace user, group, selinux, and fsgroup identifiers
5. Allowing administrators to bulk join multi-tenant namespaces, or impose consistent ingress and egress policy per namespace
6. Add cluster resource quota which applies to namespaces in bulk (so that many namespaces can share the same fixed upper limit of quota)
7. Allow administrators to limit the permissions users have within the namespace to alter any of the named policies above

Future work includes:

1. Further refining the "personal" project concept to limit the resources a user can access to - probably by a combination of "user name" -> "project name" mapping, plus quota, plus cluster resource quota.
2. Enabling organizational project allocation (ensuring namespaces are placed into an organization, and ensuring the creation counts are rate limited)
3. Investigate how organizations could be "mapped" from a central registry (in keycloak?) into each cluster

**Comment by vanloswang** [comment]
@smarterclayton That's will be great, since k8s 1.6, it can be deployed with coredns, and openshift 3.6.0 is rebase on k8s 1.6, could you keep updating this process of this great work here?
