### ISSUE TITLE
Unable to import docker-compose yaml to oc

### ISSUE THREAD

**Issue by anshul35** [openshift/origin#12932]
Unable to import docker-compose yaml to oc

##### Version
```
oc v3.3.1.7
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://<server>:443
openshift v3.3.1.3
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
```
$ git clone https://github.com/Netflix/conductor.git
$ cd docker
$ oc import docker-compose -f docker-compose.yaml
```
##### Current Result
```
ERRO[0001] Failed to parse service conductor-server: yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into string
E0212 19:16:58.343048   64676 project.go:155] Could not parse config for project docker : yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into string
error: yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into string
```
##### Expected Result
Succesfully started deployment and service

##### Additional Information
The yaml file works correct with docker-compose command. The services get started and working. Seems oc does not support all docker-compose versions yet.

Here is the link to docker-compose.yaml for quick ref.
https://github.com/Netflix/conductor/blob/dev/docker/docker-compose.yaml

**Comment by pweil-** [comment]
@anshul35 please see if https://github.com/kubernetes-incubator/kompose is sufficient for your use case.   If not feel free to reopen this issue.  As of now we are [considering deprecating oc import docker-compose in favor of the upstream project](http://lists.openshift.redhat.com/openshift-archives/dev/2017-February/msg00018.html).
