### ISSUE TITLE
Running hack/env with OS_BUILD_ENV_LOCAL_DOCKER but not as root fails to create /openshifttmp on host

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#12934]
When running `OS_BUILD_ENV_LOCAL_DOCKER=y hack/env make release-rpms` in a jenkins job, the building process fails due to several errors:
http://pastebin.com/tJh7QqME

Not sure if its because of not running the container under root.

@smarterclayton thoughts ? cc'ing @stevekuznetsov

**Comment by jhadvig** [comment]
So after removing the `OS_BUILD_ENV_LOCAL_DOCKER` env var the build process failed when building the images
http://pastebin.com/cuDLjscq

**Comment by stevekuznetsov** [comment]
@smarterclayton we should have `/var/run/docker.sock` in the container, right?
```
++ Active images
hack/build-images.sh: line 157: docker: command not found
[ERROR] PID 28949: hack/build-images.sh:157: `sort` exited with status 1.
[INFO]      Stack Trace:
[INFO]        1: hack/build-images.sh:157: `sort`
[INFO]   Exiting with code 1.
make: *** [release-rpms] Error 1
```

**Comment by stevekuznetsov** [comment]
Should we add imagebuilder to the `origin-release` Dockerfiles?

**Comment by smarterclayton** [comment]
Yeah

**Comment by jhadvig** [comment]
So after adding the imagebuilder but now when I `make release-rpm` i get 
```
openshift/hello-openshift: hack/build-images.sh: line 83: docker: command not found
openshift/hello-openshift: Removing examples/hello-openshift/bin/hello-openshift
openshift/hello-openshift: Finished in 1 seconds

```
for every image that we build... so I guess the question is, shouldn't we only build the rpms in hack/env and the images outside of it ? Or install docker inside `origin-release` ?

**Comment by jhadvig** [comment]
@smarterclayton thoughts ?

**Comment by smarterclayton** [comment]
The script really doesn't need to tag as latest in that case - I'm not even
sure we ever use :latest, so it would be better if line 83 didn't exist and
line 68 used ${OS_RELEASE_COMMIT}

**Comment by stevekuznetsov** [comment]
@smarterclayton do we want `$OS_BUILD_ENV_LOCAL_DOCKER` to imply `/tmp` for temp dir in the container?

**Comment by smarterclayton** [comment]
Hrm, I'm not sure.  /tmp is just a convention, not a hard rule

On Feb 20, 2017, at 9:16 PM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> do we want
$OS_BUILD_ENV_LOCAL_DOCKER to imply /tmp for temp dir in the container?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12934#issuecomment-281226289>,
or mute the thread

**Comment by stevekuznetsov** [comment]
Fixed in our latest `/tmp` shuffling

/close
