### ISSUE TITLE
"system:serviceaccount:sti-app:deployer" cannot list events in project "sti-app" openshift 1.4.1

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#12947]
Hi,when i use openshift-ansible to update openshfit1.4.1,i can't deploy anything(s2i or deploy a new pod) .openshift 1.3.x is ok.
such as
```
--> Scaling up java-5 from 0 to 1, scaling down java-3 from 1 to 0 (keep 1 pods available, don't exceed 2 pods)
    Scaling java-5 up to 1
--> Error listing events for replication controller java-5: User "system:serviceaccount:sti-app:deployer" cannot list events in project "sti-app"
--> Error listing events for replication controller java-3: User "system:serviceaccount:sti-app:deployer" cannot list events in project "sti-app"
Error from server: User "system:serviceaccount:sti-app:deployer" cannot watch replicationcontrollers in project "sti-app"
```
![sti-app-1](https://cloud.githubusercontent.com/assets/12937669/22918941/055d44a6-f2c8-11e6-9b36-bfd11a50c48e.png)
![sti-app-2](https://cloud.githubusercontent.com/assets/12937669/22918948/09deae52-f2c8-11e6-8755-17328268f66a.png)

**Comment by mfojtik** [comment]
@wenskys have you tried to run `oadm policy reconcile-cluster-roles` ?

**Comment by wenskys** [comment]
@mfojtik thanks.i have runing  `oadm policy reconcile-cluster-roles --confirm` to repair this error.
It looks like a bug when people update origin1.4.1.

**Comment by kargakis** [comment]
It's not a bug, you always need to upgrade your roles after upgrades. It's documented.
