### ISSUE TITLE
Jenkins marks job as failed when all sub-jobs succeed

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#12950]
Bot said:

```
continuous-integration/openshift-jenkins/test FAILURE (https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/184/) (Base Commit: bd3e362)
```

but https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/184/ was successful.

**Comment by soltysh** [comment]
Same here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_future/185/
in https://github.com/openshift/origin/pull/12948

**Comment by stevekuznetsov** [comment]
To be specific here, Jenkins marks the job as failed -- the bot is correct in that the job is failed and it reports as such. The bug is that the job should not be failed.

**Comment by soltysh** [comment]
Yeah, that's true. What wonders me why it was marked as failed, when none of the sub-build did not failed.

**Comment by stevekuznetsov** [comment]
There was an error in the job config, has been fixed with https://github.com/openshift/aos-cd-jobs/pull/27
