### ISSUE TITLE
how set jboss.as.management.blocking.timeout on jboss in openshift 3

### ISSUE THREAD

**Issue by templarfelix** [openshift/origin#12963]
how i set jboss.as.management.blocking.timeout on jboss profile ?

**Comment by pweil-** [comment]
@rcernich

**Comment by rcernich** [comment]
Which specific image are you trying to use?

What are you trying to do that requires an update to this parameter?

Shot in the dark...you might try adding something like JAVA_OPTS_APPEND=-Djboss.as.management.blocking.timeout=1000 to the deployment config

**Comment by pweil-** [comment]
Info about managing environment variables for pods can be found here: https://docs.openshift.org/latest/dev_guide/environment_variables.html

**Comment by templarfelix** [comment]
@rcernich and @pweil- its solve my issue thanks.
