### ISSUE TITLE
No package matching 'python-ruamel-yaml' found available,installed or updated and NetworkManger bug in origin1.4.1

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#12964]
Hi,when i use openshift-ansible to update origin to 1.4.1,i have encountered a few bugs,such as `No package matching 'python-ruamel-yaml' found available,installed or updated ` and `NetworkManger  must be installed or updated`.
i have runing `pip install ruamel.yaml` or `yum localinstall -y python2-ruamel-yaml-0.12.14-7.el7.centos.x86_64.rpm` to resolve it,but always failure.
At laster i use openshift-ansible-3.5.7-1 to resolve the problems.
![error-1](https://cloud.githubusercontent.com/assets/12937669/22957676/db166874-f364-11e6-9fd6-04f19732f944.png)

The bug for `NetworkManger must be installed or updated` have't be repair in new version.so i need use `systemctl restart NetworkManger` to  resolve the problems.
can we check NetworkManger is runing,and restart it in openshift-ansible？
![bug-1](https://cloud.githubusercontent.com/assets/12937669/22957675/d8427688-f364-11e6-8bb9-64a9a1ebb113.png)
thanks.

**Comment by opuk** [comment]
This error also seems to occur when trying to deploy on Atomic.

**Comment by mazzystr** [comment]
I see the same behavior when deploying OSE 3.4

[ccallega-rmbp] [04:13:40 PM] GIT: On branch origin/release-1.5 *
(ansible)[ccallega@~/repos/openshift-ansible]$ ansible --version
ansible 2.2.0.0
  config file = /Users/ccallega/repos/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides

$ cat abc2/hosts | grep openshift_release
openshift_release=3.4

My target hosts are RHEL 7 latest

**Comment by sdodson** [comment]
> This error also seems to occur when trying to deploy on Atomic.

We have no solution for this today.

> i have runing pip install ruamel.yaml or yum localinstall -y python2-ruamel-yaml-0.12.14-7.el7.centos.x86_64.rpm to resolve it,but always failure.

python2-ruamel-yaml-0.12.14-9.el7.x86_64.rpm in the centos paas sig common repo should fulfill those requirements for origin installs, need to verify that we're enabling that repo early on, but it's at http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/common/

**Comment by sdodson** [comment]
Closing this as it's an openshift-ansible problem not origin. Please track https://github.com/openshift/openshift-ansible/issues/3302
