### ISSUE TITLE
oc rsh does not support RESOURCE NAME syntax

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#12968]
```
oc rsh dc jenkins
Error from server (NotFound): pods "dc" not found
```
@openshift/cli-review

**Comment by juanvallejo** [comment]
I'm not sure if this is something that we would want to support, at least with the current assumptions that we make about user arguments in this command. Right now, we assume the following:

- If a single argument was given, and the argument was not of the form `resource/name`, [we assume](https://github.com/openshift/origin/blob/master/pkg/cmd/util/clientcmd/factory.go#L241) that [the user wants a pod](https://github.com/openshift/origin/blob/master/pkg/cmd/util/cmd.go#L53) with the name `args[0]`.
- If more than one argument was given, and the first argument did not match the form `resource/name`, we assume the same of it as the first point, and the rest of the arguments [are treated as commands to run in that pod's first container](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/rsh.go#L124) (if no specific container was requested).

While it would be ideal to support the `resource/name` syntax here, we would be breaking the current behavior of this command which treats `args[:1]` as commands to execute in a pod's container.

cc @fabianofranz @smarterclayton

**Comment by smarterclayton** [comment]
This limitation was intentional because we want oc rsh to be compatible with ssh syntax.  Allowing two arguments is ambiguous.

**Comment by smarterclayton** [comment]
We need to add a comment to the code that this is intentional so we
don't forget in the future.

Basically rsh must be an exact replacement for ssh.

**Comment by juanvallejo** [comment]
Right, you would have to specify the namespace flag before the pod name
