### ISSUE TITLE
--etcd flag does not accept a list of machines

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#1296]
--etcd flag should accept a list of etcd 'machines' for HA purposes. It currently only allows you to provide one machine and will automatically determine the leader from there, but if that machine is down openshift will fail even if there's still a majority available.

**Comment by brenton** [comment]
@smarterclayton, should this issue also track the fact that we don't have a way to have the embedded etcd find it's peers?

**Comment by smarterclayton** [comment]
This is fixed with Jordan's changes
