### ISSUE TITLE
base_ami syncing Origin repo incorrectly, leading to new-app failures

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#12975]
@stevekuznetsov 
@bparees 

base-ami builds are now failing regularly as follows (after the AMI is built, while testing is attempting to prove that the AMI is good to use):

```
FAILURE after 0.173s: test/cmd/newapp.sh:326: executing 'oc import docker-compose -f test/testdata/app-scenarios/docker-compose/complex/docker-compose.yml --dry-run' expecting success and text 'warning: not all docker-compose fields were honored': the command returned the wrong error code; the output content test failed
There was no output from the command.
Standard error from the command:
ERROR: ssh git clone spec error: unable to parse ssh git clone specification:  /data/src/github.com/openshift/origin-bare#master
ERROR: ssh git clone spec error: unable to parse ssh git clone specification:  /data/src/github.com/openshift/origin-bare#master
can't build "nginx": cannot obtain remote URL for repository at /go/src/github.com/openshift/origin/test/testdata/app-scenarios/docker-compose/complex/nginx
can't build "web": cannot obtain remote URL for repository at /go/src/github.com/openshift/origin/test/testdata/app-scenarios/docker-compose/complex/app
[ERROR] PID 28647: hack/lib/cmd.sh:242: `return "${return_code}"` exited with status 1.
```

It took me a while to work it out, but the failure is happening because the test is being run in a docker container (under `hack/env`).  Reproducer:

`OS_BUILD_ENV_PRESERVE=_output/local hack/env hack/test-cmd.sh newapp`

The flow is something like this:
- oc import docker-compose looks to see if it's in a git repo.
- It is, and it consults the remote, which is /data/src/github.com/openshift/origin-bare
- /data/src/github.com/openshift/origin-bare does not exist in the docker container
- it tries to parse /data/src/github.com/openshift/origin-bare#master as ssh git clone spec
- it falls over

**Comment by jim-minter** [comment]
At the moment I'm not yet clear why pkg/generate/dockercompose/generate.go:169 even cares if it's in a git repo, or what the remote of that repo is.  Assuming it is legitimate logic, we probably need to harden up the handling when the remote doesn't make sense to us.  That fix may turn out to be in s2i code which is vendored into origin, and may also as a consequence harden up equivalent code paths in new-app.

**Comment by stevekuznetsov** [comment]
Yeah, we talked about this when we first started seeing it in the `base_ami` -- even if `openshift-bare` were in the container, it's a bare checkout and doesn't have any refs so the code would likely fail anyway. The verdict from @smarterclayton and @bparees was that we should try to just disable these tests in `base_ami` or figure out why they look different in `test_pull_requsts_origin_check`.

**Comment by stevekuznetsov** [comment]
Also sorry that you had to spend the time looking at this and debugging -- if I had known you were digging into `base_ami` failures I would have happily briefed you on some of the failures we know about in the job and how we were thinking of tackling them.

**Comment by jim-minter** [comment]
I had supposed that if `openshift-bare` were in the container, things would work, but I think this is actually an underlying bug which we should fix.  It'd be minor if it weren't blocking base_ami.

I'm keen to get a new base_ami so we can tell if the issues we're seeing in our nightly jenkins jobs go away with the latest docker.  If disabling the test in the short term to get a new base_ami works, I'm all for it.

**Comment by stevekuznetsov** [comment]
> I had supposed that if `openshift-bare` were in the container, things would work, but I think this is actually an underlying bug which we should fix. It'd be minor if it weren't blocking `base_ami`.

Right -- this is where I think we understand the problem a little differently. Even if we had the `bare` repo available to us, a bare clone does not have a `.git` and does not have a `#master` ref. We'd be failing anyway.

> I'm keen to get a new `base_ami` so we can tell if the issues we're seeing in our nightly jenkins jobs go away with the latest docker. If disabling the test in the short term to get a new `base_ami` works, I'm all for it.

We have about three other unrelated issues installing the newest Docker versions on the `base_ami` as of this week. [This](https://trello.com/c/lfY86n9T/81-ci-jenkins-maintenance-fix-vagrant-based-base-ami-job) card is tracking the effort for `base_ami` and [this](https://trello.com/c/XesZUuzu/80-ci-jenkins-reconfigure-jenkins-jobs-to-be-generated-from-declarative-config) card is tracking the migration of the extended test jobs to `oct` AMis which have a newer Docker and do not have this bare repo issue.

**Comment by bparees** [comment]
> At the moment I'm not yet clear why pkg/generate/dockercompose/generate.go:169 even cares if it's in a git repo, or what the remote of that repo is.

It cares because it's ultimately going to construct a buildconfig and buildconfigs need to have remote git repos for the source url.

>  Assuming it is legitimate logic, we probably need to harden up the handling when the remote doesn't make sense to us.

i think the code is doing the right thing.  you pointed us to a repo and we told you we couldn't determine a valid git remote for the repo you pointed us to.

> I had supposed that if openshift-bare were in the container, things would work, but I think this is actually an underlying bug which we should fix.

i don't think so, but try me again.

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/base_ami/2718/console
```
Running test/cmd/newapp.sh:348: executing 'oc import docker-compose -f test/testdata/app-scenarios/docker-compose/complex/docker-compose.yml -o name --dry-run' expecting success and text 'service/redis'...
SUCCESS after 0.208s: test/cmd/newapp.sh:348: executing 'oc import docker-compose -f test/testdata/app-scenarios/docker-compose/complex/docker-compose.yml -o name --dry-run' expecting success and text 'service/redis'
```
\m/

**Comment by stevekuznetsov** [comment]
🙌 🎉

**Comment by kargakis** [comment]
The fix was to rsync the local repo back to the remote so the `.git` dir can be picked up by the remote.
Thanks @stevekuznetsov 

Latest base_ami build is green
https://ci.openshift.redhat.com/jenkins/job/base_ami/2719/
