### ISSUE TITLE
Reencrypting routes with service serving cert secrets

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#12971]
Trying to use the service serving cert secrets to secure services and then using a reencrypt route so that traffic is only unencrypted on the router and endpoint pod, not in transit.

Reencrypted routes require the CA certificate of the target service to be included via `destinationCaCertificate` on the route spec. In the case of a service using service serving cert secrets, this is an internal cluster CA and hard to get at without shell access.

It would be great if a route could recognise somehow that the service serving cert secret is being used by the target service and set the `destinationCaCertificate` accordingly. This would enable for a reencrypted route to be specified easily in one step, with templates being easily portable between clusters.

**Comment by knobunc** [comment]
This is https://trello.com/c/VJ5kHWFF

**Comment by kargakis** [comment]
Fixed in https://github.com/openshift/origin/pull/13752
