### ISSUE TITLE
Glusterfs with network encryption fails mounting when single node is down

### ISSUE THREAD

**Issue by aliscott** [openshift/origin#12985]
Glusterfs volume fails to mount when client/server network encryption is enabled and a single gluster node is unavailable

##### Version
```
openshift v1.4.1
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0
```

##### Steps To Reproduce
1. Create a persistent-volume-claim that uses glusterfs dynamic provisioning.
2. Stop the volume, enable client.ssl and server.ssl and restart the volume.
3. Mount the volume to a pod.
4. Test reading and writing files to the volume. Everything works fine at this stage.
5. Shut down a single glusterfs node
4. Test reading and writing files to the volume.

##### Expected Result

I should be able to mount the volume and it should still be readable and writeable, since 2/3 of the gluster nodes are still running.

##### Current Result
Neither reading or writing to the volume works. When recreating the pod the volume fails to mount:
```
8s  8s  1 {kubelet node-fbcb9413635c}   Warning  FailedMount Unable to mount volumes for pod "nginx_test1(867619c0-dcc3-11e6-9ab1-06ff73935133)": timeout expired waiting for volumes to attach/mount for pod "nginx"/"test1". list of unattached/unmounted volumes=[mypd]
8s  8s  1 {kubelet node-fbcb9413635c}   Warning  FailedSync Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "nginx"/"test1". list of unattached/unmounted volumes=[mypd]
```

The volume works again when I bring up unavailable node or if I disable client and server SSL.

##### Additional Information

[glusterd.log.txt](https://github.com/openshift/origin/files/779579/glusterd.log.txt)

**Comment by wenskys** [comment]
I also have this question.

**Comment by aliscott** [comment]
I'm also having this problem when only management encryption is enabled.

**Comment by wuchester** [comment]
I am also encountering this issue as well.

**Comment by wuchester** [comment]
I am having this same issue as well. Kindly share if there is a fix for these, thanks.

**Comment by obnoxxx** [comment]
looking...

@raghavendra-talur , @ramkrsna, @humblec, @MohamedAshiqrh

**Comment by raghavendra-talur** [comment]
@aliscott I am not sure if enabling on management encryption is supported. I refer to https://kshlm.in/post/network-encryption-in-glusterfs/ for Gluster and ssl setup.

**Comment by raghavendra-talur** [comment]
@aliscott On the main issue
1. how did you generate certs? 
2. self signed or common CA
3. Does this happen when any of the 3 nodes are down or is it only one special node?

**Comment by obnoxxx** [comment]
@aliscott any update on this?

(github should introduce a "needinfo" flag ...)

**Comment by aliscott** [comment]
Sorry, I missed this.

> 1. how did you generate certs?

I followed the guide here:
https://access.redhat.com/documentation/en-US/Red_Hat_Storage/3.1/html/Administration_Guide/chap-Network_Encryption.html

> 2. self signed or common CA

Self-signed

> 3. Does this happen when any of the 3 nodes are down or is it only one special node?

Any of the nodes

**Comment by alikhajeh1** [comment]
/remove-lifecycle stale
any update on this?

**Comment by JasonGiedymin** [comment]
I'm going to link my update to a related ticket:  https://github.com/openshift/origin/issues/13013
