### ISSUE TITLE
Tag is not trimmed before pulling image

### ISSUE THREAD

**Issue by goern** [openshift/origin#12997]
[provide a description of the issue]
Having a trailing space with the tag of an image leads to image pull errors. 

##### Version
```
oc v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://acme-ocp3-haproxy-0.acme.example.com:8443
openshift v3.3.1.7
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
1. deploy something using an image with a trailing space, for example `"goern-docker-registry.bintray.io/goern/artifactory-pro:5.0.1-3 "`

##### Current Result
Event logs shows `Back-off pulling image "goern-docker-registry.bintray.io/goern/artifactory-pro:5.0.1-3 "`

##### Expected Result
Successfully pulled image "goern-docker-registry.bintray.io/goern/artifactory-pro:5.0.1-3"

**Comment by smarterclayton** [comment]
I'm hesitant to trim tags anywhere.  We don't do it for a large majority of items.

**Comment by mfojtik** [comment]
Agree with @smarterclayton
