### ISSUE TITLE
skydns errors

### ISSUE THREAD

**Issue by jmccormick2001** [openshift/origin#1300]
running the master branch today, skydns is working, but I'm seeing many lines in the log
that appear to be errors:

2015/03/12 15:58:16 skydns: can not forward, name too short (less than 2 labels): `othyupzude.'
2015/03/12 15:58:16 skydns: can not forward, name too short (less than 2 labels): `tfyvmhdrkgirb.'
2015/03/12 15:58:16 skydns: can not forward, name too short (less than 2 labels): `aqmiinaarw.'
2015/03/12 15:58:17 skydns: can not forward, name too short (less than 2 labels): `yeibywxzfxqy.'
2015/03/12 15:58:17 skydns: can not forward, name too short (less than 2 labels): `dzuthhzyvu.'
2015/03/12 15:58:17 skydns: can not forward, name too short (less than 2 labels): `nlmprpowwz.'

**Comment by smarterclayton** [comment]
That's very strange - it looks like you have something hitting your DNS endpoint that is not Openshift.  Or something is misconfigured in the containers.

**Comment by jmccormick2001** [comment]
interestingly, I started fresh with origin master today, and started getting these same errors immediately after running "osc process  -f cpm-template.json  | osc create -f -" and "osc process -f cpm-admin-template.json  | osc create -f -", I don't get these errors in the log afterwards it appears, crazy, I'll do some more debugging and try to narrow this down.

**Comment by danmcp** [comment]
Any update?

**Comment by jmccormick2001** [comment]
I've not noticed this lately...probably safe to close

**Comment by smarterclayton** [comment]
Ok - we'll keep an eye open.  There was some flakiness in DNS for a bit inside docker as well.
