### ISSUE TITLE
Readiness automatically fail its test even though when it start container creating, Origin show it is running for more than 5 minutes

### ISSUE THREAD

**Issue by angelmotta** [openshift/origin#13006]
When I execute a deployment for a new container, the container creating start but the webconsole automatically since the beginning show "container has been running for more than 5 minutes and has not passed its readiness check"

##### Version (oc version)
openshift v1.3.2
kubernetes v1.3.0+52492b4

I have a mule application in this container and it has connectivity issue that is solved when I remove the readiness check in the yml file (sorry I can not provide more details about this) 
So I have discovered that is something with readiness check, showing since the beginning this warning.

Initially I had this readiness configuration, then I changed the initial DelaySeconds to 180 and TimeoutSeconds to 15, but every time I deploy the container, the origin web console show "container was running more than 5 minutes and fail its check" but it is starting the creation process Why happen that? how to solve that.
        readinessProbe:
         tcpSocket:
           port: 8085
         initialDelaySeconds: 60
         timeoutSeconds: 1

**Comment by jwforres** [comment]
If this message is showing up as soon as the pod is created then you must have a clock skew between your server and your browser client. Different time zones is fine but both the server and client need to be set to the correct time within their time zone.

**Comment by angelmotta** [comment]
Hi @jwforres thanks for your assistanc: 1) the clock skew is between my browser client and Master Server?
2) what do you mean with: different time zones is fine but both have to set the correct time "within their" time zone
I have figured out that running the deployment from my laptop office in the local network I don't see that message, however I saw that message from my personal laptop connected remotely from VPN. (but I don't understand what is wrong with the timezone of my personal computer, I will try again this deploy to see this behaviour)

Again thanks in advance

**Comment by jwforres** [comment]
Yes the clock skew is between your browser client and the master, possibly the node depending on which timestamp is causing the problem.

My point about time zones is that having the computers set to different time zones doesn't matter.  But as an example if you are in the EDT timezone and it is currently supposed to be 5:30 in the EDT timezone and your clock says its 5:35 then your clock is not set correctly.  Every timezone has a "correct" time.  Based on what you are saying it sounds like your clock on your personal laptop is not set correctly within your timezone.

**Comment by angelmotta** [comment]
Hi Jessica, it's totally true what you said, I have seen this same behavior this time with anothe computer of my colleague which had his computer with time UTC -5 in his windows os but its time is 4 minutes before.
Checking the "container creation process" his browser reported automatically "container running 4 minutes ago"

At this point I wonder why the web UI show that information based on the time of the browser client, I think would be better if time was based only from the time got it from Openshift infraestructure, not from the client.

**Comment by jwforres** [comment]
This is only an issue for durations that have to be calculated, we only get certain timestamps back from the API.  We did get the API to start returning a Date header so we have an idea of what the server thinks is the "current" time.  We have an open bug tracking the remaining work

https://bugzilla.redhat.com/show_bug.cgi?id=1371764
