### ISSUE TITLE
Passing proxy configuration to Maven?

### ISSUE THREAD

**Issue by steveg-mo** [openshift/origin#13010]
##### Description:
Docker / Openshift / OS the http_proxy / https_proxy settings not being passed to Maven.
Wildfly demo build fails.

##### Version:
[root@localhost ~]# oc version
oc v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.0.2.15:8443
openshift v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. [step 1]
 oc cluster up --http-proxy=http://user:pass@ip:8080 --https-proxy=http://user:pass@ip:8080
2. [step 2]
Initialise demo build of Wildfly

##### Current Result
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://repo1.maven.org/maven2): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.60.209] failed: Connection timed out (Connection timed out)

##### Expected Result
Expected  the proxy settings would have been passed to Maven but they do not seem to be.
The build requires one to clone the git demo (https://github.com/bparees/openshift-jee-sample.git)
Then add configuration/settings.xml supplying proxy information.
Push this back to a git repository then supply this to Openshift new-app.

Is this the correct way?
Is there a location that one can set Maven proxy info locally?
Have attempted to supply MVN_ARGS but to no avail.

**Comment by bparees** [comment]
the wildfly image expects the maven proxy setting to come from an HTTP_PROXY_HOST variable:
https://github.com/openshift-s2i/s2i-wildfly/blob/master/10.1/s2i/bin/assemble#L153-L175

Which is not set as a default env variable by cluster up.  (cluster up just sets HTTP_PROXY/HTTPS_PROXY as default bulid env variables)

**Comment by steveg-mo** [comment]
@bparees  Thanks for this info.
BTW should one be able to set these commands with -e or --env switch to oc cluster up?
I have attempted to but they do not seem to be honoured.
What syntax does the --env -e flags employ?
Checked online but the example I have found do not work.

Thanks

**Comment by bparees** [comment]
the -e flag to oc cluster up does not set environment variables on the buildconfigs, i don't believe it's possible short of providing a custom master-config file to oc cluster up, one which configures the build defaulter:

https://docs.openshift.org/latest/install_config/build_defaults_overrides.html#manually-setting-global-build-defaults

Other than doing that, you'd need to edit your buildconfig directly (or pass -e args to new-app/new-build, depending how you are creating your buildconfig).
