### ISSUE TITLE
default/kubernetes service slow to appear

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#13019]
I'm newly finding that when starting origin, it's taking up to as much as 10 sec for the default/kubernetes service to appear.  The home-made openshift bootstrap script I was using is below, but the registry and router sometimes fail to start because their deployment is attempted before the default/kubernetes service is available.

> systemctl start openshift.service
> 
> while ! curl -o /dev/null -m 2 -kfs https://localhost:8443/healthz; do
>   sleep 1
> done
> 
> oadm registry
> oadm policy add-scc-to-user hostnetwork -z router
> oadm router &>/dev/null

So I've had to add the following:

> while ! oc get svc kubernetes &>/dev/null; do
>   sleep 1
> done

Does it make sense not to start reporting healthz until the existence of the default/kubernetes service?  Or can/has something else be/been done so that people don't have to do this kind of home-made thing?

**Comment by stevekuznetsov** [comment]
The contract for `/healthz` is that it returns 200 when the API server has started. See info also in the related PR: https://github.com/openshift/origin/pull/12901 and issue: https://github.com/openshift/origin/issues/12897. No word yet from upstream on how they want to handle this.

**Comment by stevekuznetsov** [comment]
Should be an upstream issue.

/close
