### ISSUE TITLE
failed to external access to console url

### ISSUE THREAD

**Issue by mahsa-frj** [openshift/origin#13011]
HI everybody, I configured openshift-origin in 5 node, one node is configured as a local dns, and have one master and 3 node. every 5 node, have a local IP address but the master node have a floating ip for external access. I created a record in cloudflare for external access between floating IP address and hostname of master node.
 when i execute below command from master:

     curl -v https://openshift-dep-3-lb.x.com:8443

I get good output. But when I trying this command from remote server, I get below output:

    * About to connect() to openshift-dep-3-lb.x.com port 8443 (#0)
    *   Trying a.a.a.a...
    * Connected to openshift-dep-3-lb.x.com (a.a.a.a) port 8443 (#0)
    * Initializing NSS with certpath: sql:/etc/pki/nssdb
    *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
    CApath: none
    * NSS error -12188 (SSL_ERROR_INTERNAL_ERROR_ALERT)
    * Peer reports it experienced an internal error.
    * Closing connection 0
    curl: (35) Peer reports it experienced an internal error.

##### Version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift-dep-3-lb.x.com:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

please help me to understand how to configure openshift for external access.
thanks in advanced.

**Comment by pweil-** [comment]
`NSS error -12188 (SSL_ERROR_INTERNAL_ERROR_ALERT)` 

Seems to indicate some issue with the certs or server setup.  @sdodson @liggitt seen this before?

**Comment by sdodson** [comment]
If the environment was installed using openshift-ansible did you add `openshift_master_cluster_public_hostname=openshift-dep-3-lb.x.com` ensuring that the master certificates are signed with the hostname of your load balancer? Also, is your load balancer configured for TCP passthrough or does it terminate TLS? If it terminates TLS it needs to trust the CA of your masters.
