### ISSUE TITLE
3.5 Upstream pick list

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#13025]
Suggested picks from the last 4 weeks in the kube 1.5 branch.  @smarterclayton @ncdc @liggitt @mfojtik @deads2k PTAL and confirm/deny any that you can.  Thanks.

- [x] ~kubernetes/kubernetes#38818 https://github.com/openshift/origin/pull/13131~
- [x] ~kubernetes/kubernetes#41455 https://github.com/openshift/origin/pull/13131~
- [x] ~~https://github.com/kubernetes/kubernetes/commit/1bf90c8 - Change default reconciler sync period to 1 minute (7 days ago)~~ (https://github.com/openshift/origin/pull/13132)
- [x] ~~https://github.com/kubernetes/kubernetes/commit/3151e6e - flag gate critical pods annotation support in kubelet
              Do we need the above? We never allowed those, did we?~~
- [x] ~~https://github.com/kubernetes/kubernetes/commit/81ac623 - cherry-pick #38855 - Fix variable shadowing in exponential backoff (13 days ago)~~ https://github.com/openshift/origin/pull/13083 https://github.com/openshift/origin/pull/13084
- [x] ~~https://github.com/kubernetes/kubernetes/commit/a80e219 - cherr-pick #38339 - Exponential back off when volume delete fails (13 days ago)~~ done in https://github.com/openshift/origin/commit/4615974b76d39a38acaa20e4e6551e7b9c1cf5a9
- [x] ~~https://github.com/kubernetes/kubernetes/commit/3ccda07 - Plumb subresource through subjectaccessreview (2 weeks ago)~~ https://github.com/openshift/origin/pull/13085 https://github.com/openshift/origin/pull/13086
- [x] ~~https://github.com/kubernetes/kubernetes/commit/9903bd8 - Remove duplicate calls to describeInstance from aws (3 weeks ago)~~ done in https://github.com/openshift/origin/pull/12740
- [x] ~~https://github.com/kubernetes/kubernetes/commit/b1882b6 - controller: old pods should block deployment completeness (3 weeks ago)~~ (https://github.com/openshift/origin/pull/13133)
- [x] ~~https://github.com/kubernetes/kubernetes/commit/e4f22b5 - Adjust global log limit to 1ms (4 weeks ago)~~ https://github.com/openshift/origin/pull/13087 https://github.com/openshift/origin/pull/13088
- [x] ~~https://github.com/kubernetes/kubernetes/commit/9fc7413 - Make HandleError prevent hot-loops (4 weeks ago)~~ https://github.com/openshift/origin/pull/13087 https://github.com/openshift/origin/pull/13088
- [x] ~~https://github.com/kubernetes/kubernetes/commit/37cd179 - present request header cert CA (4 weeks ago)~~ https://github.com/openshift/origin/pull/13145
- [x] ~~https://github.com/kubernetes/kubernetes/commit/7c187ca - Fixed bug which prevents PDBs which have minAvailable specified as a percentage working with StatefulSet pods (4 weeks ago)~~ (https://github.com/openshift/origin/pull/13143)
- [x] ~~https://github.com/kubernetes/kubernetes/commit/2eef243 - various kubectl fixes (4 weeks ago)~~ done in https://github.com/openshift/origin/pull/12143
- [x] https://github.com/kubernetes/kubernetes/commit/63a4e72 - Fix: With TolerateUnready set, endpoints are still listed for (4 weeks ago) https://github.com/openshift/origin/pull/13134
- [x] ~~https://github.com/kubernetes/kubernetes/commit/c529006 - Add path exist check in getPodVolumePathListFromDisk (4 weeks ago)~~ https://github.com/openshift/origin/pull/13057, https://github.com/openshift/origin/pull/13058
- [x] ~~https://github.com/kubernetes/kubernetes/commit/6941fe3 - Check if error is Status in result.Stream() (4 weeks ago)~~ done in https://github.com/openshift/origin/pull/12610
- [x] ~~https://github.com/kubernetes/kubernetes/commit/ea100df - AWS: recognize eu-west-2 region https://github.com/openshift/origin/pull/13056,~~ https://github.com/openshift/origin/pull/13055
- [x] ~~https://github.com/kubernetes/kubernetes/commit/9eab226947d73a77cbf8474188f216cd64cd5fef - Enqueue controllers after minreadyseconds when all pods are ready https://github.com/openshift/origin/pull/13140~~

Not from 1.5 branch:

- [x] ~~[docker opt separator](https://github.com/kubernetes/kubernetes/pull/40903) (consider a backported version of this with docker version check rather than the [existing fix](https://github.com/openshift/origin/pull/12831))~~ https://github.com/openshift/origin/pull/13141

**Comment by stevekuznetsov** [comment]
@pweil- I thought we didn't want the Docker security opt separator choosing logic as we didn't support the older Docker API version anyway

**Comment by mdshuai** [comment]
@stevekuznetsov Not support doesn't means no one use it, just in case someone use it. If we have this, it will be better. I support contain this.
Recently there are two cases use old docker though we don't know why they still use old version.
https://github.com/openshift/origin/pull/12831#issuecomment-280329639
https://bugzilla.redhat.com/show_bug.cgi?id=1424629#c2

**Comment by pweil-** [comment]
@stevekuznetsov yeah, what @mdshuai mentioned is why I'm proposing we pick it.  A) it went in to upstream with version specific support so we'll get it anyway in 1.6 and B) we're already receiving bugs on it being "broken".

**Comment by stevekuznetsov** [comment]
I thought @pmorie had done that for the explicit reason that we do not support that version of Docker and do not want to enable people to use it in the unsupported state. I'll let you guys duke it out :)

**Comment by pweil-** [comment]
then we need a min version check on startup RFE, not random code that fails :smile:

**Comment by mfojtik** [comment]
@pweil- definitely want the AWS: recognize eu-west-2 region :-)

**Comment by stevekuznetsov** [comment]
@pweil- I am 100% certain that the installer will fail you if you try to install OCP on a system with an old Docker.

**Comment by vikaslaad** [comment]
I was able to install OCP 3.5 (with Docker 1.10.3) and installer did not fail, should I create a bug for that ?
https://bugzilla.redhat.com/show_bug.cgi?id=1424629

**Comment by stevekuznetsov** [comment]
@sdodson seems like a bug ^^

**Comment by ncdc** [comment]
>  kubernetes/kubernetes@3151e6e - flag gate critical pods annotation support in kubelet
Do we need the above? We never allowed those, did we?

I believe @sjenning / @derekwaynecarr reverted upstream changes that enabled "critical pods"

**Comment by pweil-** [comment]
> believe @sjenning / @derekwaynecarr reverted upstream changes that enabled "critical pods" in a <carry> commit

[Removed from the list](https://github.com/openshift/origin/commit/05308bd77e90026c03eebd3585c5a819e6af9db0)

**Comment by sdodson** [comment]
> @sdodson seems like a bug ^^

Yeah, I think that particular instance was on atomic host where our only recourse is to abort the install/upgrade and have them upgrade to a newer version of atomic host. If for some reason they need downgrade, like 3.3 requiring docker-1.10 then they'll have to downgrade atomic host.

**Comment by gnufied** [comment]
We need:

1. https://github.com/kubernetes/kubernetes/pull/38818
2. https://github.com/kubernetes/kubernetes/pull/41455
 
As well. Both these PRs have been already backported to 3.4 .

**Comment by pweil-** [comment]
thanks @gnufied, added to the list.  I see the 3.4 PRs but not master ones.  Since you've already gone through the trouble of backporting to 3.4 can you open the master/3.5 PRs?  If you want to respond on this thread or ping me the numbers in IRC I'll update the main comment.

**Comment by gnufied** [comment]
@pweil-  Yes I will bring them to 3.5/master. I was going to in fact, just caught up with 1.6 freeze in upstream.

**Comment by mfojtik** [comment]
@deads2k  kubernetes/kubernetes@37cd179 - present request header cert CA (4 weeks ago) -> this does not apply cleanely, can you please check?

**Comment by sttts** [comment]
@mfojtik looks like that's the backport we need to get rid of my patch.

**Comment by kargakis** [comment]
Also needed: https://github.com/kubernetes/kubernetes/pull/42236

**Comment by soltysh** [comment]
> docker opt separator (consider a backported version of this with docker version check rather than the existing fix)

@pmorie since you're the original author of the PR do we still want to have it for 1.5?

**Comment by mfojtik** [comment]
@pweil- last 2 remaining \o/

**Comment by soltysh** [comment]
I think we're done with all cherry-picks, I'm closing this then.
