### ISSUE TITLE
flake: Disks aren't attached to GCE instances when they start, ansible install fails because /sdc missing

### ISSUE THREAD

**Issue by bparees** [openshift/origin#13026]
```
17:33:10 TASK [openshift-volume-quota : Create filesystem for /var/lib/origin/openshift.local.volumes] ***
17:33:10 Monday 20 February 2017  22:33:10 +0000 (0:00:00.077)       0:04:09.715 ******* 
17:33:11 
fatal: [ci-prtest761-ig-n-lxzc]: FAILED! => {"changed": false, "failed": true, "msg": "Device /dev/sdc not found."}
```
from
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/761/consoleFull#-3659644775849c75fe4b0052e114d805c

**Comment by stevekuznetsov** [comment]
I think I made an issue for this one already

**Comment by smarterclayton** [comment]
This is openshift/origin-gce#14

**Comment by stevekuznetsov** [comment]
We might want to keep this one open thought for flake comments to satisfy @openshift-bot

**Comment by smarterclayton** [comment]
Fixed, gce attach is async and we had to wait for disk operations to complete
