### ISSUE TITLE
Route should support HTTP and HTTPS for the same domain name

### ISSUE THREAD

**Issue by mrcage** [openshift/origin#13031]
I have a container with a web application accepting requests on port 80 (HTTP) and port 443 (HTTPS). The port numbers are only examples, it could just as well be 8080 and 8443 or any other port.

I need to publish both the plain-text and the secure version of the web-application using the same domain-name (e.g http://my-app.com and https://my-app.com). 

As of now, I can only configure one targer port per route (e.g. either 80 or 443, or any other exposed port) in the OpenShift GUI. For my use-case, I need to have both ports be available over the same name. Is it possible to implement this, or is it already existing, but not available in the GUI (the documentation seems not to mention this use-case)...

**Comment by knobunc** [comment]
Sorry, missed this earlier.

We do not allow what you want directly.  You can set the route insecureEdgeTerminationPolicy:
  https://docs.openshift.com/container-platform/3.7/architecture/networking/routes.html#secured-routes

Your best bet is to set it to `Redirect` to redirect http to https, or you can do `Allow` to allow both http and https to get to the backend.  If you use `Allow` then the backing app can look at the http headers to determine if it came over http or https, and then you can serve different pages if appropriate.
