### ISSUE TITLE
nodejs project build failiing to connect to npm registry behind proxy

### ISSUE THREAD

**Issue by mtbvang** [openshift/origin#13037]
Running the helloworld-msa example the nodejs frontend project fails. I'm behind a corporate proxy and have oc clustered up with:

oc cluster up --http-proxy $http_proxy --https-proxy $https_proxy --no-proxy $no_proxy

All the applications in the example are building successfully except the two node ones because of the  error below which I assume is because the proxy settings for npm aren't being set correctly despite the proxy arguments being set on oc cluster up. 

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v1.5.0-alpha.3+cf7e336
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v1.5.0-alpha.3+cf7e336
kubernetes v1.5.2+43a9be4

##### Current Result
Receiving source from STDIN as archive ...
Step 1/9 : FROM ryanj/centos7-nodejs:6.4.0
# Executing 3 build triggers...
Step 1/1 : COPY package.json /opt/app-root/src
 ---> Using cache
Step 1/1 : RUN npm install
 ---> Running in 31b255dac493
npm info it worked if it ends with ok
npm info using npm@3.10.6
npm info using node@v6.4.0
npm info attempt registry request try #1 at 10:21:38 PM
npm http request GET https://registry.npmjs.org/bootstrap
npm info attempt registry request try #1 at 10:21:38 PM
npm http request GET https://registry.npmjs.org/express
npm info attempt registry request try #1 at 10:21:38 PM
npm http request GET https://registry.npmjs.org/jquery
npm info attempt registry request try #1 at 10:21:38 PM
npm http request GET https://registry.npmjs.org/keycloak-js
npm info attempt registry request try #1 at 10:21:38 PM
npm http request GET https://registry.npmjs.org/mustache
npm info attempt registry request try #1 at 10:21:38 PM
npm http request GET https://registry.npmjs.org/mustache-express
npm info attempt registry request try #1 at 10:21:39 PM
npm http request GET https://registry.npmjs.org/patternfly
npm info attempt registry request try #1 at 10:21:39 PM
npm http request GET https://registry.npmjs.org/phantomjs
npm info retry will retry, error on last attempt: Error: connect ECONNREFUSED <ipaddress>:443

##### Steps To Reproduce
1. check out helloworld-msa sample project and frontend projects.
2. cd helloworld-msa/ansible
2. oc start-build --build-loglevel=5 frontend --from-dir="../../frontend" --follow

##### Expected Result
Node application to be able to npm install successfully and build image.

##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by bparees** [comment]
starting oc cluster up w/ a proxy value does not setup that proxy for builds.  You need to set the appropriate http_proxy env variables in your buildconfig:

https://github.com/sclorg/s2i-nodejs-container/blob/master/4/s2i/bin/assemble#L25-L48

@csrwng it's starting to seem like oc cluster up should setup build defaulters for the proxy env variables.  (I assume it's already setting up a build defaulter for the git proxy)

**Comment by csrwng** [comment]
@bparees we are already setting defaults for the env vars:
https://github.com/openshift/origin/blob/master/pkg/bootstrap/docker/openshift/helper.go#L612-L641

**Comment by csrwng** [comment]
@mtbvang this seems to be an issue with the helloworld-msa example. In our nodejs builder we set the npm config based on the presence of the HTTP[S]_PROXY variables as @bparees pointed out above. However, in this case, this is a Docker build that is likely not configuring npm before calling npm install.

**Comment by bparees** [comment]
i'm going to guess this is an ONBUILD driven thing from:
https://github.com/openshift-s2i/s2i-nodejs-community/blob/master/nodejs.org/Dockerfile.onbuild#L67

so yeah, that image would need to be updated to add ONBUILD commands that setup the proxy where appropriate.

**Comment by bparees** [comment]
(thanks @csrwng)
