### ISSUE TITLE
Need newer kernel in Jenkins jobs for NetworkPolicy testing support

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#13049]
It is currently not possible to add NetworkPolicy tests to the extended networking tests (#12991), because the VMs we are running the Jenkins jobs on in AWS do not appear to have OVS conntrack support in their kernel. From the logs, the kernel in question is "3.10.0-327.22.2.el7.x86_64", which looks like it corresponds to RHEL 7.2. So the fix is that we need RHEL 7.3 instead I guess.

For OCP 3.5, NetworkPolicy is considered "tech preview" (and has some known problems anyway) so the inability to test it is bad but not necessarily a blocker. For 3.6 it is supposed to be fully supported and we will need this to work.

**Comment by stevekuznetsov** [comment]
@tdawson let's chat sometime about this process

**Comment by stevekuznetsov** [comment]
@danmcp also fyi

**Comment by tdawson** [comment]
I'd already been asked about getting the latest RHEL 7.4 kernel in repo, available for some openshift testing.  It's not completely setup yet, but would that work for your testing?

**Comment by danwinship** [comment]
Not sure exactly what you're asking, but (a) if you mean "would 7.4 rather than 7.3 be OK", then yes, (b) if you mean "would it be OK to have just the 7.4 *kernel* but not full 7.4 userland", then yes, that's OK too (the tests run in a container that has new enough OVS userland), (c) if by "available for *some* openshift testing" you mean to imply "not used for *all* openshift testing", then, no, that doesn't help because I can't commit the tests until openshift-bot is using the new kernel by default.

**Comment by stevekuznetsov** [comment]
@tdawson I guess I was expecting to generate a new "bare os" RHEL AMI for 7.4, and to more automate that process - in the chain of AMIs it's still 100% manual right now.

**Comment by tdawson** [comment]
I totally misunderstood what was being asked.

**Comment by smarterclayton** [comment]
Gce should have the packages for this now

**Comment by danwinship** [comment]
Any update on this?

**Comment by stevekuznetsov** [comment]
We recently upgraded the kernels, so we have now:

```
$ uname -a
Linux ip-172-18-5-77.ec2.internal 3.10.0-514.21.1.el7.x86_64 #1 SMP Sat Apr 22 02:41:35 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

@danwinship is this acceptable?

**Comment by danwinship** [comment]
Ah, yes, that works. I should have checked some recent test logs before pinging. Thanks.
