### ISSUE TITLE
User system:anonymous cannot get on console

### ISSUE THREAD

**Issue by eurodomenii** [openshift/origin#13066]
Users cannot login via web console.

##### Version
My installation is an openshift origin version 1.4.1 stand alone registry, Centos 7 
https://docs.openshift.org/latest/install_config/install/stand_alone_registry.html#install-config-installing-stand-alone-registry
Tried with also with origin 1.3.3 
##### Steps To Reproduce
1. https://localshift.mydomain.com:8443/console
Current result
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot \"get\" on \"/console\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
2. https://localshift.mydomain.com:8443
Current result
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/controllers",
    "/healthz",
    "/healthz/ping",
    "/healthz/ready",
    "/metrics",
    "/oapi",
    "/oapi/v1",
    "/swaggerapi/"
  ]
}
##### Expected Result
The normal behaviour ( tested on a cluster up installation, on the same browser) for anonymous is redirect from /console to /login?then=... token…. . 

##### Additional Information
A similar issues is https://access.redhat.com/solutions/2790131, but cannot see the progress.  In that situation, even is normal to deny /console/project/test1/overview, the expected result should be redirecting to login page, instead of forbidden. Anyway, /console should be accessible by anonymous users.

The cli oc login works. 

After testing with "oc login" with non-system admin is normal to get  https://bugzilla.redhat.com/show_bug.cgi?id=1420621. No other errors at _oadm diagnostics_

cat /etc/ansible/hosts
```
 [test]
 localshift.mydomain.com

 #Create an OSEv3 group that contains the masters and nodes groups
 [OSEv3:children]
 masters
 nodes

 # Set variables common for all OSEv3 hosts
 [OSEv3:vars]
 # SSH user, this user should allow ssh based auth without requiring a password
 ansible_ssh_user=root
 use_cluster_metrics=true
 # Force different version 
 # openshift_pkg_version=-1.3.3

 # If ansible_ssh_user is not root, ansible_become must be set to true
 #ansible_become=true

 deployment_type=origin
 deployment_subtype=registry
 openshift_docker_options="--selinux-enabled --log-driver=journald --insecure-registry 172.30.0.0/16"

 # Allow all auth. For testing
 openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]

 # host group for masters
 [masters]
 localshift.mydomain.com

 # host group for nodes, includes region info
 [nodes]
 localshift.mydomain.com openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

```
Thank you!

**Comment by eurodomenii** [comment]
I have tried unsuccessfully,  with Origin v1.5.0-alpha.2, 1.4.1, 1.3.3 in my KVM environment, also on DigitalOcean.

Then I realized that maybe stand alone registry deployment could be the cause https://docs.openshift.org/latest/install_config/install/stand_alone_registry.html#overview 

Indeed, reverting KVM from snapshot, with the same host preparation for advanced installation, it worked with the following workaround inventory: ( omitting _deployment_subtype=registry_) 

```
[root@sm ~]# cat /etc/ansible/hosts
 [test]
 localshift.mydomain.com

 #Create an OSEv3 group that contains the masters and nodes groups
 [OSEv3:children]
 masters
 nodes

 # Set variables common for all OSEv3 hosts
 [OSEv3:vars]
 # SSH user, this user should allow ssh based auth without requiring a password
 ansible_ssh_user=root
 use_cluster_metrics=true

 # If ansible_ssh_user is not root, ansible_become must be set to true
 #ansible_become=true

 deployment_type=origin
 containerized=true
 openshift_release=v1.4.1
 openshift_image_tag=v1.4.1

 openshift_docker_options="--selinux-enabled --log-driver=journald --insecure-registry 172.30.0.0/16"

 # Allow all auth. For testing
 openshift_master_identity_providers=[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]
 
 # host group for masters
 [masters]
 localshift.mydomain.com

 # host group for etcd
 [etcd]
 localshift.mydomain.com

 # host group for nodes, includes region info
 [nodes]
 localshift.mydomain.com openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

```
Btw, **how is different** the _single master acting also as node deployment_ from 
_stand alone registry deployment_ https://docs.openshift.org/latest/install_config/install/stand_alone_registry.html#overview ?
I get the same  “single host that includes the master, node, etcd, and registry components.”

**Comment by pweil-** [comment]
@aweiteka this looks more related to the stand alone registry config, mind taking a look?

**Comment by Sandvich** [comment]
I'm having the same issue - the weird thing is that it worked just fine until recently. There's some package I've updated that broke it (maybe ca-certificates).
(Running on Fedora 25 server)

**Comment by aweiteka** [comment]
Atomic registry deployment is being deprecated in favor of better tested and maintained installation methods.

- [oc cluster up](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md) for non-production "try it out" or test deployments
- [openshift-ansible](http://www.projectatomic.io/blog/2017/05/oo-standalone-registry/) for more production use cases.

This reported issue will not be addressed.
