### ISSUE TITLE
Unable to start openshift-origin node

### ISSUE THREAD

**Issue by Office-Manager** [openshift/origin#13081]
**v1.5.0-alpha.3** 
Version
```

openshift v1.5.0-alpha.3
containerized=true
openshift_release=v1.5.0-alpha.3
openshift_image_tag=v1.5.0-alpha.3
```

` /usr/bin/docker run --name origin-node --rm --privileged --net=host --pid=host --env-file=/etc/sysconfig/origin-node -v /:/rootfs:ro -e CONFIG_FILE=${CONFIG_FILE} -e OPTIONS=${OPTIONS} -e HOST=/rootfs -e HOST_ETC=/host-etc -v /var/lib/origin:/var/lib/origin:rslave -v /etc/origin/node:/etc/origin/node -v /etc/localtime:/etc/localtime:ro -v /etc/machine-id:/etc/machine-id:ro -v /run:/run -v /sys:/sys:rw -v /sys/fs/cgroup:/sys/fs/cgroup:rw -v /usr/bin/docker:/usr/bin/docker:ro -v /var/lib/docker:/var/lib/docker -v /lib/modules:/lib/modules -v /etc/origin/openvswitch:/etc/openvswitch -v /etc/origin/sdn:/etc/openshift-sdn -v /etc/systemd/system:/host-etc/systemd/system -v /var/log:/var/log -v /dev:/dev $DOCKER_ADDTL_BIND_MOUNTS openshift/node:${IMAGE_VERSION}
container_linux.go:247: starting container process caused "exec: \"/usr/local/bin/origin-node-run.sh\": stat /usr/local/bin/origin-node-run.sh: not a directory"
/usr/bin/docker-current: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/local/bin/origin-node-run.sh\\\": stat /usr/local/bin/origin-node-run.sh: not a directory\"\n".
[root@ip121 ansible]# echo $?
125
`

Seems the image was missing the origin-node-run.sh
Using the "latest" seems to resolve this issue.

**Comment by tdawson** [comment]
Why was this assigned to me?  I don't do anything with the OpenShift Origin images.

**Comment by sjenning** [comment]
Closing due to age and problem on old alpha build.  Please repoen if still an issue in 1.7 or master.
