### ISSUE TITLE
Docker build from GUI?

### ISSUE THREAD

**Issue by cameron-scrace** [openshift/origin#13095]
I can easily create a docker build from the command line using oc new-app and a git repo that has a Dockerfile, but I can't find anyway to do this cleanly from the GUI. Is there a way to do this?

##### Version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.companyname.com
openshift v1.4.1
kubernetes v1.4.0+776c994

**Comment by jwforres** [comment]
There isn't a nice GUI for it today, the user story is tracked in this trello story already https://trello.com/c/6CuBSnFF

You can use the Import YAML/JSON option to create one.  We do let you edit the build configuration if you have a docker strategy build that exists (e.g. directly edit embedded Dockerfiles, or change source repo information)
