### ISSUE TITLE
flake: Extended.deploymentconfigs generation [Conformance] should deploy based on a status version bump

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13105]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/978/testReport/junit/(root)/Extended/deploymentconfigs_generation__Conformance__should_deploy_based_on_a_status_version_bump/

```
/tmp/openshift/tito/rpmbuild-originIrXnnn/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:577
Expected error:
    <*util.ExitError | 0xc421181c20>: {
        Cmd: "oc rollout --config=/tmp/extended-test-cli-deployment-21c5c-hnqgm-user.kubeconfig --namespace=extended-test-cli-deployment-21c5c-hnqgm latest generation-test",
        StdErr: "Error from server (Conflict): Operation cannot be fulfilled on deploymentconfigs \"generation-test\": the object has been modified; please apply your changes to the latest version and try again",
        ExitError: {
            ProcessState: {
                pid: 22701,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 200859},
                    Stime: {Sec: 0, Usec: 24943},
                    Maxrss: 34768,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 9142,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 2751,
                    Nivcsw: 53,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
not to have occurred
/tmp/openshift/tito/rpmbuild-originIrXnnn/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:550
```

We should guard against this.

**Comment by smarterclayton** [comment]
For triage p1

**Comment by mfojtik** [comment]
Guess this should be using Patch(), but our legacy client for DC does not have Patch()... Should be fixed in 1.6 when we switch (hopefully to clientset).

**Comment by bparees** [comment]
does not appear to be fixed in 1.6:
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/733/testReport/junit/(root)/Extended/deploymentconfigs_generation__Conformance__should_deploy_based_on_a_status_version_bump/

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1612/testReport/junit/(root)/Extended/deploymentconfigs_generation__Conformance__should_deploy_based_on_a_status_version_bump/

**Comment by kargakis** [comment]
@mfojtik you can always update the test to retry on conflicts and have a separate issue that tracks making instantiate use GuaranteedUpdate.

**Comment by tnozicka** [comment]
seems like now we do Update only for servers older than 1.4 otherwise we call instantiate
https://github.com/tnozicka/origin/blob/a71e6f14824d4b5bb3eb852104163b01cf32f1fb/pkg/cmd/cli/cmd/rollout/latest.go#L165-L165

**Comment by mfojtik** [comment]
@kargakis do we want to nuke the support for pre 1.4 clients now?

**Comment by kargakis** [comment]
@mfojtik for 1.7 servers, yes we can. cc: @smarterclayton 

[Essentially, nuke this part of code out of origin](https://github.com/openshift/origin/blob/bbb9647b7655d3c709580b9ccf018649cfe1b45d/pkg/deploy/registry/deployconfig/strategy.go#L73-L77).

**Comment by kargakis** [comment]
@mfojtik can you open a separate issue for the rollback issue we found out yesterday? The code above is responsible that the update is not going through instantiate.

**Comment by mfojtik** [comment]
@kargakis https://github.com/openshift/origin/issues/14903 is for deprecating the old rollout latest

**Comment by mfojtik** [comment]
This is fixed by https://github.com/openshift/origin/pull/14902
