### ISSUE TITLE
How to access docker repo using SSO API Key ?

### ISSUE THREAD

**Issue by techsivam** [openshift/origin#13127]
Hi,

I Have SSO API Key , using docker login i am able to pull images form the repo, but when i try to create micro service POD using openshift , not able to authendicate the repo. how do i enable authendicate or add secret in opneshift using SSO API Key?

##### Version

OpenShift Master:
    v1.3.1
Kubernetes Master:
    v1.3.0+52492b4 

##### Steps To Reproduce
1. docker login -u -p myservcer.com working fine
docker pull image is working

2. same path if i give in Deployemnt config and try to create pod it says not able to authendicate that path.

##### Current Result
not able to authenticate
##### Expected Result
it should get the image because its alteady docker login is done.
##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by legionus** [comment]
@simo5 Right now the only way is to create a special user and use that token.

**Comment by legionus** [comment]
If you use the pullthrough from your server, then you need to add a secret to make it work:
```
oc secrets new-dockercfg SECRET --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL
```
