### ISSUE TITLE
Duplicate libraries in bundled dependencies

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#1312]
We currently bundle 

[code.google.com/p/goauth2/oauth](https://github.com/openshift/origin/blob/ab1d409b09155dcd691c4148699aaf3a09c5846f/Godeps/Godeps.json#L19)
[golang.org/x/oauth2](https://github.com/openshift/origin/blob/ab1d409b09155dcd691c4148699aaf3a09c5846f/Godeps/Godeps.json#L725) (which redirects to [github.com/golang/oauth2](https://github.com/golang/oauth2))

and 

[code.google.com/p/goprotobuf/proto](https://github.com/openshift/origin/blob/ab1d409b09155dcd691c4148699aaf3a09c5846f/Godeps/Godeps.json#L39)
[github.com/golang/protobuf/proto](https://github.com/openshift/origin/blob/ab1d409b09155dcd691c4148699aaf3a09c5846f/Godeps/Godeps.json#L554)

which are duplicates

Eventually we will need to replace all the Google Code repositories with their GitHub counterparts
http://google-opensource.blogspot.cz/2015/03/farewell-to-google-code.html

**Comment by smarterclayton** [comment]
Some of these are coming from upstream dependencies - can you find those and open issues / pulls to them?

**Comment by kargakis** [comment]
For protobuf, we need to rebase the Prometheus client (they started bundling their dependencies so I think we won't need to import protobuf)

**Comment by kargakis** [comment]
For protobuf, we need to rebase the Prometheus client (they already made the switch), etcd (they still haven't replaced the google code links though), the golang-protobuf-extensions ([they also have made the switch](https://github.com/matttproud/golang_protobuf_extensions/commit/a54dae06c0faf29d6809624404a44565a1097efe)).

**Comment by kargakis** [comment]
False alarm for etcd, they seem to use gogoprotobuf which is an extension of goprotobuf. grep tricked me because of the vendored gogoprotobuf package which contains links in comments from the original goprotobuf google repository. So rebasing the Prometheus client and the golang-protobuf-extension will probably suffice in order to remove the goprotobuf google repo dependency.

**Comment by smarterclayton** [comment]
Going to handle this after the rebase.

**Comment by kargakis** [comment]
No more duplicates in our deps.
