### ISSUE TITLE
oc cluster up checks for exact --insecure-registry entry

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#13136]
I have in my /etc/sysconfig/docker an entry with:

````
INSECURE_REGISTRY='--insecure-registry 0.0.0.0/0'
````

which basically makes every registry insecure. "oc cluster up" fails to start as it's checking to an exact configuration entry of "--insecure-registry 172.30.0.0/16"

##### Version
````
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.17.0.1:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994
````

**Comment by csrwng** [comment]
Yes, ideally we would check your current entries and see if they cover the cidr for services. However, in the grand scheme of things, I would consider this to be lower priority. You can always add another --insecure-registry entry with the exact value that oc cluster up is looking for.

**Comment by jorgemoralespou** [comment]
@csrwng Agree this is low priority, but I wanted to have it tracked, just in case related works happen and can be addressed.
