### ISSUE TITLE
Jenkins not un-idled on Pipeline build start

### ISSUE THREAD

**Issue by vpavlin** [openshift/origin#13135]
When I idle Jenkins and then start a pipeline build, Jenkins is not un-idled and build just sits there. Jenkins gets successfully started when I hit it's route URL.

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Deploy Jenkins
2. Apply pipeline build
3. call `oc idle jenkins`
4. `oc start-build my-pipeline-build`

##### Current Result
Pipeline build is started (Console shows new build), but as Jenkins has been scaled down, pipeline is never processed.

##### Expected Result
Jenkins gets scaled up and the build proceeds

##### Additional Information
I am using steps here https://github.com/vpavlin/fabric8-pipeline-demo (+ the manual idling and another start-build)

**Comment by bparees** [comment]
The way the pipeline build feature works today, Jenkins observes build objects in openshift and runs them.  If jenkins is idled, it can't do that.

Having openshift poke jenkins when a new build is created would require that openshift knew where your jenkins server was and how to reach it, which will not always be the case. I'm in favor of closing this issue.

**Comment by vpavlin** [comment]
Hmm..I thought there is also something in OpenShift representing the jenkinspipeline strategy which can executed the code, but if that is not the case, then this is probably nonsense.

**Comment by bparees** [comment]
@vpavlin there is a build object in openshift representing the pipeline build, it's what jenkins looks for to know it needs to start the jenkins job.  openshift itself doesn't do anything with that object though.

**Comment by vpavlin** [comment]
Ok, so the "custom" solution could be a small service which would be also watching for these and hit the jenkins API if it's idled.

**Comment by mfojtik** [comment]
@bparees we should make sure the jenkins is not idled automatically which will break the pipeline builds.

@vpavlin i believe you can use `oc observe` in a pod that does monitor this... wonder what happen if that is idled :-)

**Comment by bparees** [comment]
> @bparees we should make sure the jenkins is not idled automatically which will break the pipeline builds.

how do we do that?  something we can add to the pod definition?

**Comment by mfojtik** [comment]
@smarterclayton ^ 

i'm not that familiar with idling, just seems reasonable to whitelist my infra services from being idled :-)

**Comment by mfojtik** [comment]
@pweil- bumping this up... auto-idling is not supported, so if you idle your infra jenkins, you're hurting yourself... 

this case would make sense in env where the auto-idle is turned on (to prevent idler idling your infra)

**Comment by vpavlin** [comment]
Ok, thanks guys, seems like there will have to be some service sitting around to watch this and act based on some rules.

Feel free to close it if you don't see it as a reasonable feature request

**Comment by smarterclayton** [comment]
I do think we probably need to "wake Jenkins on build".  We may need to think about what components might be idled that should be unidled when system events happen.  It's kind of like an image change trigger, but for a service.

**Comment by vpavlin** [comment]
@smarterclayton Hi any update on this?

**Comment by coreydaley** [comment]
I just tested this using the supplied steps to reproduce and Jenkins does not get un-idled when a pipeline build is started.

**Comment by DirectXMan12** [comment]
> I just tested this using the supplied steps to reproduce and Jenkins does not get un-idled when a pipeline build is started.

Correct, nothing has changed since this was opened.  Someone would need to go write a custom controller that woke up the Jenkins instances when new Jenkins builds come in.

**Comment by bparees** [comment]
@smarterclayton what do you see as the direction on this?  It seems to me the right solution is something generic, e.g.  maybe a way to annotate your replicationcontroller/replicaset with a resource type/json-path to watch for?  (which, when seen, unidles the RC)

**Comment by DirectXMan12** [comment]
is idling the controller watching a particular resource a common pattern?  It seems like it's mostly a problem if you have some sort of controller that runs on a per-namespace basis.
