### ISSUE TITLE
Reserve kube[-*] and openshift[-*] namespaces

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#13147]
Upstream is reserving kube-* namespaces (kube-system and kube-public are notably already used).

We should do the same with openshift[-*] namespaces and prevent those from being used in project requests (e.g. limit access to cluster admins)

Need to decide what to do on upgrade to make sure we don't bump to a level that gives power to a namespace a user previously requested as their own.

**Comment by liggitt** [comment]
cc @deads2k @mfojtik

**Comment by deads2k** [comment]
@enj this is the thing we need a pre-flight check for.

I think we can reasonably scope the check to those namespace prefixes AND the `openshift.io/requester` being set.  @liggitt there could be gaps with custom templates that did something different, but they should be rare....

**Comment by stevekuznetsov** [comment]
We should probably have this done if we are going to enforce it on upgrade...

**Comment by enj** [comment]
The intent may have been for this check to be enabled for 3.6+?

Maybe I will need to add that toggle to split the checks after all.

**Comment by liggitt** [comment]
fixed in https://github.com/openshift/origin/pull/13673

**Comment by enj** [comment]
Technically the ansible bits are not complete...

**Comment by liggitt** [comment]
https://github.com/openshift/openshift-ansible/pull/4030
https://github.com/openshift/openshift-ansible/pull/4031
