### ISSUE TITLE
can't push image in docker registry

### ISSUE THREAD

**Issue by fdelahaye-mmtt** [openshift/origin#13164]
[provide a description of the issue]

##### Version
[root@openshift-master master]# oc version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift-master.unicite.fr.netcentrex.net:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. [step 1]
advanced installation of openshift using single master example  

2. [step 2]
create a helloworld project and app in web console using user/user account

##### Current Result

**build logs :** 
Cloning "https://github.com/fdelahaye-mmtt/helloworld-php.git" ...
	Commit:	17f69b4d3e7a16ec905e9b6955a4a7c26bdfc939 (Update index.php)
	Author:	François Delahaye <francois.delahaye@mmtt.fr>
	Date:	Wed Jan 11 11:18:47 2017 +0100
---> Installing application source...
Pushing image 172.30.142.31:5000/helloworld-php/helloworld-php:latest ...
Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
**error: build error: Failed to push image: Put http://172.30.142.31:5000/v1/repositories/helloworld-php/helloworld-php/: dial tcp 172.30.142.31:5000: getsockopt: connection refused**

##### Expected Result

the image is pushed , the build is OK, etc ... 

##### Additional Information

**1.  I have added in /etc/sysconfig/docker the following key :** 
INSECURE_REGISTRY='--insecure-registry  172.30.0.0/16'

**2. I can't find any  "docker-registry" running pod :** 
[root@openshift-master master]# oc --config=admin.kubeconfig get pods
NAME                       READY     STATUS    RESTARTS   AGE
registry-console-1-2f4iu   1/1       Running   0          12m
router-1-deploy            0/1       Pending   0          46m

**3. oc status output :** 
[root@openshift-master master]# oc --config=admin.kubeconfig status
In project default on server https://openshift-master.unicite.fr.netcentrex.net:8443

https://docker-registry-default.router.default.svc.cluster.local (passthrough) (svc/docker-registry)

svc/kubernetes - 172.30.0.1 ports 443, 53->8053, 53->8053

https://registry-console-default.router.default.svc.cluster.local (passthrough) (svc/registry-console)
  dc/registry-console deploys docker.io/cockpit/kubernetes:latest
    deployment #1 deployed 49 minutes ago - 1 pod

svc/router - 172.30.31.140 ports 80, 443, 1936
  dc/router deploys docker.io/openshift/origin-haproxy-router:v1.4.1
    deployment #1 pending 50 minutes ago

Errors:
  * route/docker-registry is routing traffic to svc/docker-registry, but either the administrator has not installed a router or the router is not selecting this route.
  * route/registry-console is routing traffic to svc/registry-console, but either the administrator has not installed a router or the router is not selecting this route.

2 errors and 1 warning identified, use 'oc status -v' to see details.

**4. oadm diagnostics output** : 
[root@openshift-master master]# oadm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/root/.kube/config'
Info:  Using context for cluster-admin access: 'default/openshift-master-unicite-fr-netcentrex-net:8443/system:admin'
[Note] Performing systemd discovery

[Note] Running diagnostic: ConfigContexts[/openshift-master-unicite-fr-netcentrex-net:8443/admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0013 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context '/openshift-master-unicite-fr-netcentrex-net:8443/admin':
       The server URL is 'https://openshift-master.unicite.fr.netcentrex.net:8443'
       The user authentication is 'admin/openshift-master-unicite-fr-netcentrex-net:8443'
       The current project is 'default'
       (*errors.StatusError) User "system:anonymous" cannot list all projects in the cluster

       This means that when we tried to make a request to the master API
       server, your kubeconfig did not present valid credentials to
       authenticate your client. Credentials generally consist of a client
       key/certificate or an access token. Your kubeconfig may not have
       presented any, or they may be invalid.

[Note] Running diagnostic: ConfigContexts[/openshift-master-unicite-fr-netcentrex-net:8443/default]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0013 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       The current client config context is '/openshift-master-unicite-fr-netcentrex-net:8443/default':
       The server URL is 'https://openshift-master.unicite.fr.netcentrex.net:8443'
       The user authentication is 'default/openshift-master-unicite-fr-netcentrex-net:8443'
       The current project is 'default'
       (*errors.StatusError) User "system:anonymous" cannot list all projects in the cluster

       This means that when we tried to make a request to the master API
       server, your kubeconfig did not present valid credentials to
       authenticate your client. Credentials generally consist of a client
       key/certificate or an access token. Your kubeconfig may not have
       presented any, or they may be invalid.

[Note] Running diagnostic: ConfigContexts[default/openshift-master-unicite-fr-netcentrex-net:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

Info:  For client config context 'default/openshift-master-unicite-fr-netcentrex-net:8443/system:admin':
       The server URL is 'https://openshift-master.unicite.fr.netcentrex.net:8443'
       The user authentication is 'system:admin/openshift-master-unicite-fr-netcentrex-net:8443'
       The current project is 'default'
       Successfully requested project list; has access to project(s):
         [default helloworld-php kube-system logging management-infra openshift openshift-infra]

[Note] Running diagnostic: ConfigContexts[helloworld-php/openshift-master-unicite-fr-netcentrex-net:8443/user]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0013 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'helloworld-php/openshift-master-unicite-fr-netcentrex-net:8443/user':
       The server URL is 'https://openshift-master.unicite.fr.netcentrex.net:8443'
       The user authentication is 'user/openshift-master-unicite-fr-netcentrex-net:8443'
       The current project is 'helloworld-php'
       (*errors.StatusError) User "system:anonymous" cannot list all projects in the cluster

       This means that when we tried to make a request to the master API
       server, your kubeconfig did not present valid credentials to
       authenticate your client. Credentials generally consist of a client
       key/certificate or an access token. Your kubeconfig may not have
       presented any, or they may be invalid.

[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint

ERROR: [DCli2001 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:77]
       Creating diagnostic pod with image openshift/origin-deployer:v1.4.1 failed. Error: (*errors.errorString) an empty
namespace may not be set during creation

[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint

ERROR: [DNet2001 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:78]
       Checking network plugin failed. Error: User "system:anonymous" cannot get clusternetworks at the cluster scope

[Note] Running diagnostic: AggregatedLogging
       Description: Check aggregated logging integration for proper configuration

[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry

ERROR: [DClu1006 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:208]
       The "docker-registry" service exists but has no associated pods, so it
       is not available. Builds and deployments that use the registry will fail.

ERROR: [DClu1001 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:178]
       The "docker-registry" service exists but no pods currently running, so it
       is not available. Builds and deployments that use the registry will fail.

[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects

Info:  clusterrolebinding/cluster-readers has more subjects than expected.

       Use the `oadm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra
subjects.

Info:  clusterrolebinding/cluster-readers has extra subject {ServiceAccount management-infra management-admin    }.

Info:  clusterrolebinding/self-provisioners has more subjects than expected.

       Use the `oadm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra
subjects.

Info:  clusterrolebinding/self-provisioners has extra subject {ServiceAccount management-infra management-admin    }.

[Note] Running diagnostic: ClusterRoles
       Description: Check that the default ClusterRoles are present and contain the expected permissions

[Note] Running diagnostic: ClusterRouterName
       Description: Check there is a working router

ERROR: [DClu2007 from diagnostic ClusterRouter@openshift/origin/pkg/diagnostics/cluster/router.go:156]
       The "router" DeploymentConfig exists but has no running pods, so it
       is not available. Apps will not be externally accessible via the router.

[Note] Running diagnostic: MasterNode
       Description: Check if master is also running node (for Open vSwitch)

Info:  Found a node with same IP as master: openshift-master.unicite.fr.netcentrex.net

[Note] Skipping diagnostic: MetricsApiProxy
       Description: Check the integrated heapster metrics can be reached via the API proxy
       Because: The heapster service does not exist in the openshift-infra project at this time,
       so it is not available for the Horizontal Pod Autoscaler to use as a source of metrics.

[Note] Running diagnostic: NodeDefinitions
       Description: Check node records on master

WARN:  [DClu0003 from diagnostic NodeDefinition@openshift/origin/pkg/diagnostics/cluster/node_definitions.go:112]
       Node openshift-master.unicite.fr.netcentrex.net is ready but is marked Unschedulable.
       This is usually set manually for administrative reasons.
       An administrator can mark the node schedulable with:
           oadm manage-node openshift-master.unicite.fr.netcentrex.net --schedulable=true

       While in this state, pods should not be scheduled to deploy on the node.
       Existing pods will continue to run until completed or evacuated (see
       other options for 'oadm manage-node').

[Note] Running diagnostic: ServiceExternalIPs
       Description: Check for existing services with ExternalIPs that are disallowed by master config

[Note] Running diagnostic: AnalyzeLogs
       Description: Check for recent problems in systemd service logs

Info:  Checking journalctl logs for 'origin-master' service
Info:  Checking journalctl logs for 'origin-node' service
Info:  Checking journalctl logs for 'docker' service

[Note] Running diagnostic: MasterConfigCheck
       Description: Check the master config file

WARN:  [DH0005 from diagnostic MasterConfigCheck@openshift/origin/pkg/diagnostics/host/check_master_config.go:52]
       Validation of master config file '/etc/origin/master/master-config.yaml' warned:
       assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
       assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console
       auditConfig.auditFilePath: Required value: audit can now be logged to a separate file

[Note] Running diagnostic: NodeConfigCheck
       Description: Check the node config file

Info:  Found a node config file: /etc/origin/node/node-config.yaml

[Note] Running diagnostic: UnitStatus
       Description: Check status for related systemd units

ERROR: [DS3002 from diagnostic UnitStatus@openshift/origin/pkg/diagnostics/systemd/unit_status.go:55]
       systemd unit origin-node depends on unit iptables, which is not loaded.

       iptables is used by nodes for container networking.
       Connections to a container will fail without it.
       An administrator probably needs to install the iptables unit with:

         # yum install iptables

       If it is already installed, you may to reload the definition with:

         # systemctl reload iptables

[Note] Summary of diagnostics execution (version v1.4.1):
[Note] Warnings seen: 2
[Note] Errors seen: 9
[root@openshift-master master]#

**Comment by miminar** [comment]
@fdelahaye-mmtt Have you finished deploying the integrated registry? I can see only a docker-registry service created. Have you run `oadm registry` to deploy the registry or is this a result of running an ansible playbook?

To deploy the registry, just `oc delete -n default svc/docker-registry` and follow our  [guide](https://docs.openshift.org/latest/install_config/registry/deploy_registry_existing_clusters.html#deploy-registry).

**Comment by canit00** [comment]
Looks like your router and registry didn't get deployed. This could have been for various reasons and you haven't provided enough information to determine why. In any case, I'd recommend that you carefully now walk through these steps in order to deploy a Docker registry and router.

Proxy Deployment:
https://docs.openshift.org/latest/install_config/registry/deploy_registry_existing_clusters.html

Router Deployment:
https://docs.openshift.org/latest/install_config/router/index.html

Questions.
1. How did you install Origin?
2. What events do you see re: router OR registry?

`oc get events -w`

**Comment by fdelahaye-mmtt** [comment]
I have installed with ansible, using the single master  example found [here](https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master)

I did what minimar suggests : 

```
oc --config=admin.kubeconfig delete -n default svc/docker-registry 
service "docker-registry" deleted
```
then
```
oadm registry --config=admin.kubeconfig  --service-account=registry 
--> Creating registry registry ...
    error: serviceaccounts "registry" already exists
    clusterrolebinding "registry-registry-role" created
    deploymentconfig "docker-registry" created
    service "docker-registry" created
--> Failed

```

despite the errors I can see now docker-registry pod : 

```
oc --config=admin.kubeconfig get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-eepg2    1/1       Running   0          37s
registry-console-1-2f4iu   1/1       Running   0          4h
router-1-deploy            0/1       Pending   0          4h
```
but the image still cannot be pushed : 

```
Cloning "https://github.com/fdelahaye-mmtt/helloworld-php.git" ...
	Commit:	17f69b4d3e7a16ec905e9b6955a4a7c26bdfc939 (Update index.php)
	Author:	François Delahaye <francois.delahaye@mmtt.fr>
	Date:	Wed Jan 11 11:18:47 2017 +0100
---> Installing application source...
Pushing image 172.30.142.31:5000/helloworld-php/helloworld-php:latest ...
error: build error: Failed to push image: Put http://172.30.142.31:5000/v1/repositories/helloworld-php/helloworld-php/: dial tcp 172.30.142.31:5000: getsockopt: no route to host
```

**Comment by fdelahaye-mmtt** [comment]
oups I didn't want to close, I still get some problems

**Comment by fdelahaye-mmtt** [comment]
hi again,
problem fixed after docker-registry re-creation and master reboot ,
thanks everybody

**Comment by miminar** [comment]
@fdelahaye-mmtt I'm glad to hear that. Yes, the master restart is necessary after the registry is re-deployed with a new service.

**Comment by kalingaha** [comment]
Hi,
This error occured when i was using origin version 1.5.  Then i uninstalled and install the version 3.6. Then the issue fixed.
