### ISSUE TITLE
oc new-app blindly creates imagestream, failing if it already exists

### ISSUE THREAD

**Issue by lance** [openshift/origin#13169]
I have noticed some odd behavior that is causing some problems for automation scripts I am writing. When I use a docker builder image for my node apps (whether it's from bucharestgold or ryanj), a build and deployment works the first time, but the second time an app is created, I get the error message `error: imagestreams "centos7-s2i-nodejs" already exists`. I am not a go developer, but from examining the code, it appears the problem is [here](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/newapp.go#L310-L312). 

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994

##### Steps To Reproduce
To reproduce this problem.

```sh
$ git clone https://github.com/bucharest-gold/s2i-nodejs.git
$ cd s2i-nodejs.git
$ oc cluster up
$ oc login -u developer -p developer
$ oc new-project test
$ oc new-app bucharestgold/centos7-s2i-nodejs:latest~. --name=app1 
$ oc new-app bucharestgold/centos7-s2i-nodejs:latest~. --name=app2
```

The first `oc new-app` command works as expected. The second command generates the following output.

```sh
$ oc new-app bucharestgold/centos7-s2i-nodejs:latest~. --name=app2
--> Found Docker image 18714e4 (45 hours old) from Docker Hub for "bucharestgold/centos7-s2i-nodejs:latest"

    Node.js v7.6.0
    --------------
    Platform for building and running Node.js applications

    Tags: builder, nodejs, nodejs-v7.6.0

    * An image stream will be created as "centos7-s2i-nodejs:latest" that will track the source image
    * A source build using source code from https://github.com/bucharest-gold/s2i-nodejs.git#master will be created
      * The resulting image will be pushed to image stream "app2:latest"
      * Every time "centos7-s2i-nodejs:latest" changes a new build will be triggered
    * This image will be deployed in deployment config "app2"
    * Port 8080/tcp will be load balanced by service "app2"
      * Other containers can access this service through the hostname "app2"

--> Creating resources ...
    error: imagestreams "centos7-s2i-nodejs" already exists
    imagestream "app2" created
    buildconfig "app2" created
    deploymentconfig "app2" created
    service "app2" created
--> Failed
```

As you can see, the buildconfig and other assets are created, and the app is successfully deployed. However the `oc` command returns at this point with an error code, and indicates failure in the console when it shouldn't. This is making scripting of `oc` commands very difficult, and it's not totally clear whether the `new-app` command is fully successful (it appears to be, but who knows!).

##### Current Result
```sh
--> Creating resources ...
    error: imagestreams "centos7-s2i-nodejs" already exists
    imagestream "app2" created
    buildconfig "app2" created
    deploymentconfig "app2" created
    service "app2" created
--> Failed
```

##### Expected Result
```sh
--> Creating resources ...
    imagestream "centos7-s2i-nodejs" created
    imagestream "app1" created
    buildconfig "app1" created
    deploymentconfig "app1" created
    service "app1" created
--> Success
    Build scheduled, use 'oc logs -f bc/app1' to track its progress.
    Run 'oc status' to view your app.
```

##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by bparees** [comment]
it's a valid bug that new-app should not attempt to create the imagestream again if one already exists w/ the proper reference.  That said, if you want to avoid this you can create the imagestream yourself and then pass the imagestreamtag to new-app instead of passing a docker image reference.

that is: oc new-app centos7-s2i-nodejs:latest~. --name=app2

(in this context, "centos7-s2i-nodejs:latest" refers to the imagestreamtag that was created by the first new-app invocation)

@oatmealraisin i'm assigning this to you because i think there's some overlap with 
https://bugzilla.redhat.com/show_bug.cgi?id=1419801

**Comment by lance** [comment]
@bparees thanks for the recommendation. I found another workaround by using the docker strategy and including a Dockerfile in my repositories. E.g. https://github.com/lance/node-msa-demo/blob/master/start.sh
