### ISSUE TITLE
Memory Leak issue in Openshift

### ISSUE THREAD

**Issue by sravanpsk** [openshift/origin#13186]
[HelloWorldTestApllication.docx](https://github.com/openshift/origin/files/823185/HelloWorldTestApllication.docx)
[HelloWorldTestApllication.docx](https://github.com/openshift/origin/files/823186/HelloWorldTestApllication.docx)

##### Description
While trying to deploy spring boot application built as a docker image it is consuming too much memory in openshift whereas the same image started in docker local consumes less than half of the memory

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1.  Create a hello-world microservice based on Spring Boot.
2.  Build it as docker image
3.  Run the docker image in docker local. Check memory consumption with `docker stats`
4. Push Docker image to docker repository.
5. Pull image in openshift from docker repository.
6. Import and deploy/create new app by running - oc new-app <dockerregistryname/imagename>
7. Deploy - oc deploy <dc>
8. Check the memory consumption by Hawkular Metrics. This is twice as much as the memory consumption in step 3.

##### Current Result
Memory consumption gets more than thrice, once image is deployed on Openshift.
##### Expected Result
Memory Consumption should be somewhat similar to local.

##### Additional Information
##Docker Version
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Mon Jan 23 15:35:13 2017
 OS/Arch:         linux/amd64

##Docker Info
Containers: 67
 Running: 35
 Paused: 0
 Stopped: 32
Images: 169
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 24.03 GB
 Data Space Total: 46.14 GB
 Data Space Available: 22.11 GB
 Metadata Space Used: 8.241 MB
 Metadata Space Total: 100.7 MB
 Metadata Space Available: 92.42 MB
 Thin Pool Minimum Free Space: 4.614 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 31.01 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false

**Comment by smarterclayton** [comment]
@openshift/scale-performance-review

**Comment by jeremyeder** [comment]
Hi @sravanpsk -- seems to be ok here, docker stats says 2.359 and hawkular says 2.4 (rounded up in the UI).

```
# docker stats 329 --no-stream
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O             PIDS
329                 1.00%               2.359 GiB / 15.26 GiB   15.46%              0 B / 0 B           151.5 MB / 2.253 MB   112
```
![cfme_mem](https://cloud.githubusercontent.com/assets/1919640/23556806/d6e60d56-fffb-11e6-9d8f-2ad84e716be5.png)

**Comment by sravanpsk** [comment]
Hi @jeremyeder , I have uploaded supported document in this I am running a springboot hellowworld application in my local docker, the memory consumed is 116.7 MiB after this running the application in docker installed on openshift is taking 385 MiB and when it is deployed in openshift it is taking 480 MiB. The steps followed here doesn't link to each other and it is just for the testing only.
