### ISSUE TITLE
Update `store.CompleteWithOptions` upstream to default `store.ObjectNameFunc`

### ISSUE THREAD

**Issue by enj** [openshift/origin#13182]
This needs to be done before we migrate to using `store.CompleteWithOptions`.

> `store.CompleteWithOptions` will need to be updated with this upstream.  All of the object name funcs will also need to be deleted.  To do so safely means we need the etcd storage test upstream as well.

> So there is no PR upstream yet.  Basically I am saying that we plan to replace `ApplyOptions` with `store.CompleteWithOptions`.  Thus `store.CompleteWithOptions` must at least do everything `ApplyOptions` does.  Therefore it needs to be updated to default a missing `ObjectNameFunc`.  At that point it would make sense to delete the `ObjectNameFunc`s in upstream as they would no longer be useful.  Since all of this is will be a relatively large change to the storage layer, it would make sense for us to upstream the etcd storage path test to give us higher confidence that we did not accidentally break something.

xref: #12541

**Comment by soltysh** [comment]
I've linked it with #10910, where I have a list of things that needs to happen to have this all straighten out.

**Comment by enj** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/44779
