### ISSUE TITLE
store master and ideally node logs after test_pull_requests_origin_gce failures

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#13191]
Following on from #13067, it would be good to store master, and ideally node logs, as artifacts after failures in the test_pull_requests_origin_gce CI job.  This would help debugging test failures

**Comment by kargakis** [comment]
We do store master and node logs today but it seems they are pushed only in S3, right @stevekuznetsov @smarterclayton ?

**Comment by stevekuznetsov** [comment]
Correct
