### ISSUE TITLE
Init container doesn't run but main container starts

### ISSUE THREAD

**Issue by iocanel** [openshift/origin#13197]
The init container doesn't run but the main container of the pod starts normally.

What makes the issue even more strange is that if I create my environment using:

     oc new-app <template-name> 

Things work fine, But if I try:

    oc process <template-name> | oc create -f -

I get the reported issue:

##### Version

Server https://api.rh-idev.openshift.com:443
openshift v3.3.1.3
kubernetes v1.3.0+52492b4

##### Steps To Reproduce

Step 1: Install prerequisites 

     oc create -f https://raw.githubusercontent.com/redhat-ipaas/openshift-templates/master/serviceaccount-as-oauthclient-single-tenant.yml

Step 2: Create the template 
    oc create -f https://raw.githubusercontent.com/redhat-ipaas/openshift-templates/master/redhat-ipaas-single-tenant.yml

Step 3: Process and Create

    c process  redhat-ipaas-single-tenant  OPENSHIFT_MASTER=https://172.30.0.1:443 ROUTE_HOSTNAME=ipaas-testing.b6ff.rh-idev.openshiftapps.com KEYCLOAK_ROUTE_HOSTNAME=ipaas-testing-keycloak.b6ff.rh-idev.openshiftapps.com OPENSHIFT_OAUTH_CLIENT_ID=system:serviceaccount:ipaas-testing:ipaas-oauth-client OPENSHIFT_OAUTH_CLIENT_SECRET=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpcGFhcy1jaSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJpcGFhcy1vYXV0aC1jbGllbnQtdG9rZW4tanQ1NjYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiaXBhYXMtb2F1dGgtY2xpZW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNDhmM2M3NDctZmRkMC0xMWU2LWEyOTctMGUxM2EwMmQ4ZWJkIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmlwYWFzLWNpOmlwYWFzLW9hdXRoLWNsaWVudCJ9.C86lM3h83tY2OL4UlbAw6qQ4cn8rwpoN_frBYbpoV5GhROMkyMNwmxsvVkmybL0QSAyP3NcL-n9APIUakiLSF02KkUjgD_i5VopwAKijLiXOBvLRQCDJPB-gUq42tgqUFrWGrI137vc0NfLagOx9sRqtn4Ox8pG1SlKzilap_YrDNfgVxWrbLNpdpUiCE2wXos9AHwyUX-yp8P4QeOjQ70kaYCpVrV7heg1QnWVN0tG14gHEgXLsnmNX0lWqHq7z7UnQ_lasy2d4KYLyJmAoJcFl-rVwvgsZgHfT8YMNE-PMaSKLtgplqG_7sTV9P2mfZhV45_M1nFygzojgQug_EQ OPENSHIFT_OAUTH_DEFAULT_SCOPES="user:info user:check-access role:edit:ipaas-testing:"! | oc create -f -

##### Current Result

The pod that is created after the `ipaas-keycloak` DeploymentConfig has errors because the init container never run and the main container failed (due to not proper initialization).

##### Expected Result

The init container to run.

##### Additional Information
Replacing the `Step 3` with the following command, makes everything work fine:

    oc new-app redhat-ipaas-single-tenant -p OPENSHIFT_MASTER=https://172.30.0.1:443 -p ROUTE_HOSTNAME=ipaas-testing.b6ff.rh-idev.openshiftapps.com -p KEYCLOAK_ROUTE_HOSTNAME=ipaas-testing-keycloak.b6ff.rh-idev.openshiftapps.com -p OPENSHIFT_OAUTH_CLIENT_ID=system:serviceaccount:ipaas-testing:ipaas-oauth-client -p OPENSHIFT_OAUTH_CLIENT_SECRET=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpcGFhcy1jaSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJpcGFhcy1vYXV0aC1jbGllbnQtdG9rZW4tanQ1NjYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiaXBhYXMtb2F1dGgtY2xpZW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNDhmM2M3NDctZmRkMC0xMWU2LWEyOTctMGUxM2EwMmQ4ZWJkIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmlwYWFzLWNpOmlwYWFzLW9hdXRoLWNsaWVudCJ9.C86lM3h83tY2OL4UlbAw6qQ4cn8rwpoN_frBYbpoV5GhROMkyMNwmxsvVkmybL0QSAyP3NcL-n9APIUakiLSF02KkUjgD_i5VopwAKijLiXOBvLRQCDJPB-gUq42tgqUFrWGrI137vc0NfLagOx9sRqtn4Ox8pG1SlKzilap_YrDNfgVxWrbLNpdpUiCE2wXos9AHwyUX-yp8P4QeOjQ70kaYCpVrV7heg1QnWVN0tG14gHEgXLsnmNX0lWqHq7z7UnQ_lasy2d4KYLyJmAoJcFl-rVwvgsZgHfT8YMNE-PMaSKLtgplqG_7sTV9P2mfZhV45_M1nFygzojgQug_EQ -p OPENSHIFT_OAUTH_DEFAULT_SCOPES="user:info user:check-access role:edit:ipaas-testing:"!

**Comment by iocanel** [comment]
Ping @bparees @derekwaynecarr @jimmidyson

**Comment by bparees** [comment]
we also compared the pod definitions from the two scenarios and there's no obvious difference:
https://github.com/iocanel/ipaas-system-tests/blob/troubleshooting/pod-working.yml
https://github.com/iocanel/ipaas-system-tests/blob/troubleshooting/pod-failing.yml

**Comment by iocanel** [comment]
Thanks @bparees, I almost forgot. And here's is the actuall diff: https://www.diffchecker.com/BEvY1Cti too.

**Comment by jimmidyson** [comment]
This is still affecting us in several environments (though not all). @derekwaynecarr Any ideas on what this could be?

**Comment by rhuss** [comment]
@bparees @derekwaynecarr Any news on this ?

**Comment by sjenning** [comment]
Init containers were alpha in 3.3 IIRC and not fully baked.  Can this be reproduced against 3.7?

**Comment by iocanel** [comment]
That's a good question. I will try and let you know.

**Comment by iocanel** [comment]
Since March, when I initially opened the issue a lot of things have changed, including our templates which no longer make use of init containers. So we are no longer exposed to that issue and thus I think its best to close the issue.
