### ISSUE TITLE
Network mode is now supported, we must set it in builds

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13208]
@bparees needs to be added to fsouza/go-dockerclient I think, I see it in the API.

We need to know the container name of the pause container - not sure how to do it precisely, but fairly important.

**Comment by bparees** [comment]
we're doing it for s2i builds, i would assume we can use the same mechanism to get it.

**Comment by smarterclayton** [comment]
Docker builds.  Needs to be added.

On Mar 3, 2017, at 12:29 AM, Ben Parees <notifications@github.com> wrote:

we're doing it for s2i builds, i would assume we can use the same mechanism
to get it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/13208#issuecomment-283869356>,
or mute the thread

**Comment by bparees** [comment]
> Docker builds. Needs to be added.

i know, i'm just saying we're already grabbing the network mode for s2i so i assume we can easily grab it for docker builds the same way.  i'm working on a PR for this.
