### ISSUE TITLE
How to deploy catalog

### ISSUE THREAD

**Issue by vnugent** [openshift/origin#13209]
I have a working cluster but couldn't find any documentation on how to create a catalog of pre-defined s2i apps such as node.js, python. In particular I want to deploy a new app from a node.js  github repo.  I build my Docker image elsewhere and create a DeploymentConfig but it's not intention. 

The doc below explains the concept of Node.js S2I but it doesn't really show you how to build your node.js project on github with OpenShift node.js image.

https://docs.openshift.com/container-platform/3.3/using_images/s2i_images/nodejs.html

##### Version
1.4

**Comment by bparees** [comment]
it's not clear to me what you are trying to do, but this document covers how to define a new application starting from source code on github and build it using an s2i builder image:
https://docs.openshift.org/latest/dev_guide/application_lifecycle/new_app.html

does that help?

**Comment by vnugent** [comment]
I deployed Origin 1.4 from the release binary.  There are no s2i builder images.  I want to create a catalog of builders similar to what you have in openshift dev preview.

![ose-catalog](https://cloud.githubusercontent.com/assets/3805254/23626098/7ba19980-0260-11e7-94e8-35a4010e5ca8.png)

**Comment by vnugent** [comment]
Sorry I was not very coherent in the initial bug report.  I meant to say " I _can_ build my Docker image elsewhere and create a DeploymentConfig but it's not _my_ intention."

**Comment by bparees** [comment]
@vnugent ah, this doc tells you how to do that: https://docs.openshift.org/latest/install_config/imagestreams_templates.html
