### ISSUE TITLE
Incorrect error message when using osc create

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#1321]
I am trying to set up a list of buildConfigs (`test.json`) in Vagrant:
```
[vagrant@openshiftdev examples]$ openshift cli create -f test.json
F0316 16:34:54.371332    2117 create.go:83] unable to get type info from "test.json": couldn't get version/kind: error converting YAML to JSON: yaml: found character that cannot start any token
```

Obviously, my json file has an error (or many) but it definitely doesn't have to do with converting a YAML file to JSON.

**Comment by smarterclayton** [comment]
This is covered by other changes upstream - Kubernetes #5533
