### ISSUE TITLE
detach doesn't work when atomic-openshift-node runs inside container

### ISSUE THREAD

**Issue by gnufied** [openshift/origin#13228]
##### Version
3.5.x

##### Steps To Reproduce
When kubelet/node process is running inside container and `atomic-openshift-node` process is restarted then users can't detach volumes mounted by the kubelet process. 

There is already a bug -  https://bugzilla.redhat.com/show_bug.cgi?id=1427807

But the gist of it is:

We are running `atomic-openshift-node` via following docker command:

```
docker run -it --name atomic-openshift-node --rm --privileged --net=host --pid=host -v /:/rootfs:ro -v /var/lib/origin:/var/lib/origin:rslave -v /run:/run -v /sys:/sys:rw -v /sys/fs/cgroup:/sys/fs/cgroup:rw -v /usr/bin/docker:/usr/bin/docker:ro -v /var/lib/docker:/var/lib/docker -v /lib/modules:/lib/modules -v /var/log:/var/log -v /dev:/dev fedora /bin/bash -l
```

And that means when the process is started, it scans all mount points inside "/" and creates bind mounts inside container under "/rootfs" directory.  This becomes a problem if - kubelet mounts a newly discovered AWS-EBS disks from within the container using `nsenter` and then kubelet process gets restarted.  On restart - naturally all of "/" on host is scanned again and the EBS disk that was host mounted from container on `/var/lib/origin/openshift.local.volumes/pod/xxx/volumes/aws-ebs/xxx` 
gets mounted inside "/rootfs/xxxx" inside container. 

This means same device `/dev/xvdbb` gets mounted multiple places inside container:

```/var/lib/origin/openshift.local.volumes/pod/xxxx/volumes/xxx`
/rootfs/var/lib/origin/openshift.local/xxx```

There is also mounts inside "/var/lib/docker/" for same device but we can ignore that for right now. 

The code in Kubernetes only attempts to unmount "/var/lib/origin/openshift.local.volumes", it is unaware of other mount points that are created as a result of recursive bind mounts and hence device always appears busy and can't be detached.

Is there any reason all of `"/"` from Host is mounted inside `"/rootfs"` of container? Why can't we just mount `"/proc"` for example:

```
docker run -v /proc:/rootfs/proc:ro <other arguments>
```

**Comment by derekwaynecarr** [comment]
Fixed by https://github.com/openshift/origin/pull/13327

If you run this manually, you will need to update your docker run invocation to align with what is presented in the referenced PR (/var/lib/origin:/var/lib/origin:rslave)
