### ISSUE TITLE
Extended.[builds][Slow] openshift pipeline build Blue-green pipeline Blue-green pipeline should build and complete successfully

### ISSUE THREAD

**Issue by bparees** [openshift/origin#13220]
```
Error from server (Conflict): Operation cannot be fulfilled on buildconfigs "bluegreen-pipeline": the object has been modified; please apply your changes to the latest version and try again
```
https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/1152/testReport/junit/(root)/Extended/_builds__Slow__openshift_pipeline_build_Blue_green_pipeline_Blue_green_pipeline_should_build_and_complete_successfully/

**Comment by jim-minter** [comment]
Is this the same as #13694? If so suggest closing this issue.
