### ISSUE TITLE
Public Layers as a performance optimization

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13243]
Many of the images we use are known to be "public" (they require no additional credentials to access).  A layer that is "public" should be globally available, in that pushes to a repository that doesn't have the image yet should not have to upload the layer again.

If we track a pool of "public" layers, can we bypass push for a large set of the layers in the "openshift" namespace, or most / all of those from the hub?  How much time would that save on initial builds?  How would we model it?

@mfojtik @miminar @legionus

**Comment by legionus** [comment]
I guess we can extend the `pullthroughBlobStore` and check dockerhub as last check. If we find blob there, we can mirror it. But even now no one prevents to use pullthrough for "public" images.

**Comment by dmage** [comment]
@bparees if we make a new endpoint to resolve [bug 1531676](https://bugzilla.redhat.com/show_bug.cgi?id=1531676), this optimization can be made on the side of the new endpoint.

**Comment by bparees** [comment]
> @bparees if we make a new endpoint to resolve bug 1531676, this optimization can be made on the side of the new endpoint.

the new endpoint would return all public layers known to the registry?

**Comment by dmage** [comment]
If it will answer whether a blob belongs to an image stream, it could pretend that all public layers belongs to all image streams.

**Comment by bparees** [comment]
> If it will answer whether a blob belongs to an image stream, it could pretend that all public layers belongs to all image streams.

ok that's a different new api than the one I was thinking of (one that lists all blobs associated w/ an imagestream, or lists all images associated w/ an imagestream).  Though it would also address the problem of too many api calls (not quite as efficiently though since it would still make a call per layer instead of a single call).

**Comment by bparees** [comment]
> If we track a pool of "public" layers, can we bypass push for a large set of the layers in the "openshift" namespace,

I thought cross-mount was supposed to handle this already(assuming of course that we pullthrough'd the layers at some point in the openshift namespace)?  What *are* the conditions under which a layer can be successfully cross-mounted on push?

> or most / all of those from the hub?

I'm not understanding what the hub has to do with this.  Is the idea that any layer we pullthrough'd from a public repository, should be marked as public when we mirror it?
