### ISSUE TITLE
deployer-token incorrect ca.crt

### ISSUE THREAD

**Issue by Iambchop** [openshift/origin#13252]
All deployer-token secrets are generated with old, incorrect ca.crt after the OpenShift Container Platform CA was reployed by the redeploy-certificates playbook (openshift-ansible-3.4.56-1) causing all deployments to fail.

Initially, after manually restarting origin-master-api and origin-master-controllers the deployer tokens were being generated with the correct, new ca.crt value.  But, after a few days it has reverted back to the old value and restarting the services did not help.

My question is:  how is the deployer-token generated?  (Where does it get the ca.crt value from?)

Thanks :-)

##### Version
```
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. Cluster was deployed and working properly with self-signed cert for masterPublicURL
2. Requested and received a signed certificate from our internal enterprise CA
3. Used the redeploy-certificates playbook to deploy the new cert for masterPublicURL; openshift_certificates_redeploy_ca was set to false
    a. Even though openshift_certificates_redeploy_ca was set to false, the playbook recreated and redployed the OpenShift Container Platform CA as well.  (It appears that this bug was fixed in openshift-ansible-3.5.)
    b. The playbook failed at the end while restarting the services.
4. All deployments failed with "certificate signed by unknown authority."
    a. We noticed that the ca.crt in the deployer-token was still the old CA.
    b. Updating ca.crt in the deployer token with "oc edit" did not work.  After changing the value and saving, the ca.crt was still the old value.
5. After manually restarting origin-master-api, origin-master-controllers, and origin-node, the deployer-tokens automatically updated to the new value and deployments once again worked.
6. A few days later deployments suddenly started failing again; upon inspection, the deployer-tokens again reverted to the old ca.crt value.
7. After manually restarting origin-master-api and origin-master-controllers, the deployer-tokens automatically updated to the new value and deployments once again worked.
8. A few days later deployments suddenly started failing again; upon inspection, the deployer-tokens again reverted to the old ca.crt value.
9. This time restarting the services has no effect: the deployer-tokens still have the old ca.crt value and all deployments are failing.

##### Current Result
All deployments fail (certificate signed by unknown authority).

##### Expected Result
Deployments run.

##### Additional Information
In our test cluster (which only has a single master server), we had no issues with the incorrect ca.crt value being placed into the deployer tokens.  The production cluster has 3 master/infrastructure nodes, 3 etcd nodes, 8 primary nodes, and 2 additional nodes (SchedulingDisabled, only added to get access to the SDN).

Also, /etc/origin/master/ca.crt and /etc/origin/node/ca.crt on all hosts have the same size and md5sum.

**Comment by mfojtik** [comment]
@liggitt @sdodson i thought the restart of the API server is required when updating certs.

**Comment by sdodson** [comment]
@abutcher any ideas here?

**Comment by abutcher** [comment]
@Iambchop Does `/etc/origin/master/ca-bundle.crt` match on each master?

**Comment by Iambchop** [comment]
@abutcher  No it does not match.  Thanks!
```
0a2a5eb856e94ae9629cbdf8b16959bf  /etc/origin/master/ca-bundle.crt
792af0489d3683e79fa26a389962ab42  /etc/origin/master/ca-bundle.crt
6c56ff9d782d353a178cae7b4febd55c  /etc/origin/master/ca-bundle.crt
```
I will look at their contents today.

**Comment by Iambchop** [comment]
Copied ca.crt to ca-bundle.crt on the two masters that were out of date:

```
6c56ff9d782d353a178cae7b4febd55c  /etc/origin/master/ca.crt
6c56ff9d782d353a178cae7b4febd55c  /etc/origin/master/ca.crt
6c56ff9d782d353a178cae7b4febd55c  /etc/origin/master/ca.crt
6c56ff9d782d353a178cae7b4febd55c  /etc/origin/master/ca-bundle.crt
6c56ff9d782d353a178cae7b4febd55c  /etc/origin/master/ca-bundle.crt
6c56ff9d782d353a178cae7b4febd55c  /etc/origin/master/ca-bundle.crt
```

And after restarting the master services deploymentss are running again.  Thank you very much.  :-)
