### ISSUE TITLE
Flake: failed to "StartContainer" for "router" with ErrImagePull: "net/http: request canceled"

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#13294]
Seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_networking_minimal/16/consoleFull#-169259343956c60d7be4b02b88ae8c268b):

```
00:54:22.900 Mar  7 20:40:02.388: INFO: At 2017-03-07 20:39:51.286085019 -0500 EST - event for scoped-router: {kubelet nettest-node-2} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "router" with ErrImagePull: "net/http: request canceled"
```

Is this a registry thing?

**Comment by mfojtik** [comment]
not a registry issue, seems more like a docker issue.

**Comment by smarterclayton** [comment]
This looks like the docker registry timing out or getting slow.

**Comment by stevekuznetsov** [comment]
We should check that this wasn't due to the AWS S3 outage

**Comment by stevekuznetsov** [comment]
Wait, we shouldn't be pulling that image from the hub, nevermind

**Comment by dmage** [comment]
> 2017-03-07 20:37:01.420030851 -0500 EST - event for endpoint-1: {kubelet nettest-node-2} Pulling: pulling image "openshift/hello-openshift"
> 2017-03-07 20:39:51.285971044 -0500 EST - event for scoped-router: {kubelet nettest-node-2} Failed: Failed to pull image "openshift/origin-haproxy-router": net/http: request canceled

It was timeout from docker.io. Please reopen if it happens again.
