### ISSUE TITLE
Systemctl restart Docker affect bash connection to pod "oc exec -ti container_bash bash"

### ISSUE THREAD

**Issue by angelmotta** [openshift/origin#13290]
I could keep the containers "running" after execute "systemctl restart docker" in one openshift node using "live-restore": true option in the /etc/docker/daemon.json file and "KillMode=process" in docker.service file, however I have noticed that I can not connect to the bash shell of the container anymore:
"oc exec -ti pod_name bash" show the following output:
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:75: starting setns process caused \\\"fork/exec /proc/self/exe: no such file or directory\\\"\"\n"
error: error executing remote command: error executing command in container: Error executing in Docker Container: 126

##### Version
openshift version
openshift v1.3.2
kubernetes v1.3.0+52492b4
etcd 2.3.0+git

##### Steps To Reproduce
1. Enable "KillMode=process" in docker.service file in the openshift node
2. systemctl daemon-reload
3. systemctl restart docker (The goal is restart docker without affect the pods operation, I need to add a new registry in the configuration file and restart docker service)
4.- oc get nodes (pods continue up and running)
5.- oc exec -ti pod_name bash (from the master node and show the error reported)
6.- From the WEB UI Console show the same error output in the "terminal" tab

##### Current Result
The connection to the bash shell of the container is blocked.

##### Expected Result
Work normally inside the container. 

I have the concern if the container actually is running normally since I can not connect again to its bash shell.

**Comment by pweil-** [comment]
Unfortunately live-restore is currently unsupported due to [issues with the mount namespace](https://bugzilla.redhat.com/show_bug.cgi?id=1419877).  Right now the best option is to evacuate the node before performing a restart.
