### ISSUE TITLE
Flake: bizarro project already exists

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13293]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/1424/testReport/junit/(root)/Extended/deploymentconfigs_when_tagging_images__Conformance__should_successfully_tag_the_deployed_image/

**Comment by mfojtik** [comment]
This test is definitely a winner in number of weird flakes.

**Comment by mfojtik** [comment]
Closing due to age. Seems like some rare race or GC issue where the project already existed between test runs?
