### ISSUE TITLE
HAProxy mapping file doesn't set the right backend

### ISSUE THREAD

**Issue by DanyC97** [openshift/origin#13301]
Hi,

I'm running the default haproxy image `openshift/origin-haproxy-router:v1.3.1` with the default routers created in `default` namespace in a VMware env where OS Origin was deployed.
I then created a route, svc, pod in a different namespace as below

```
[root@localhost ~]# oc get route
NAME               HOST/PORT         PATH      SERVICES           PORT      TERMINATION
srv1   srv1.router.domain1             srv1               <all>


[root@localhost ~]# oc get route -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: 2017-03-06T21:53:16Z
    name: srv1
    namespace: proj1
    resourceVersion: "8377"
    selfLink: /oapi/v1/namespaces/proj1/routes/srv1
    uid: 4d9ff9a0-02b7-11e7-be59-005056803f91
  spec:
    host: srv1.router.domain1
    to:
      kind: Service
      name: srv1
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2017-03-06T21:53:16Z
        status: "True"
        type: Admitted
      host: srv1.router.domain1
      routerName: router
      wildcardPolicy: None
kind: List
metadata: {}

```
And the svc output looks like below (ignore the type LB as that it should be `NodePort` )

```
[root@localhost ~]# oc get svc srv1 -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-03-06T20:28:35Z
  labels:
    app: srv1
    env: qa-perf
    location: labs
  name: srv1
  namespace: proj1
  resourceVersion: "2440"
  selfLink: /api/v1/namespaces/proj1/services/srv1
  uid: 79880f58-02ab-11e7-be59-005056803f91
spec:
  clusterIP: 172.30.58.128
  deprecatedPublicIPs:
  - 172.46.216.144
  externalIPs:
  - 172.46.216.144
  ports:
  - nodePort: 9104
    port: 9004
    protocol: TCP
    targetPort: 9004
  selector:
    app: srv1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.46.216.144

```
Now if i look in one of the routers i see the mapping file being

```
oc exec -it router-2-fiuyy -- cat os_http_be.map
srv1.router.domain1 proj1_srv1

```
and the haproxy.config is 

```
# Plain http backend
backend be_http_proj1_svc1

  mode http
  option redispatch
  option forwardfor
  balance leastconn

  timeout check 5000ms
  http-request set-header X-Forwarded-Host %[req.hdr(host)]
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
  http-request set-header X-Forwarded-Proto https if { ssl_fc }

  cookie 30c70fe9792c2e88504911824cce9bbb insert indirect nocache httponly

  http-request set-header Forwarded for=%[src];host=%[req.hdr(host)];proto=%[req.hdr(X-Forwarded-Proto)]

```
My understanding is that the value in the haproxy.config `be_http_proj1_svc1` should match the one in the map file however in the map file i don't have the `be_http` as a prefix. Am i missing s'thing here ?

@ramr @knobunc i suspect you guys are familiar with this code hence you might be able to help/ shed some light ? (much thanks in advance)

##### Version
 ```
oc version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.1.1.106:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4
```

**Comment by DanyC97** [comment]
and if i'm not wrong the code which generates/ write the map file is [here](https://github.com/openshift/origin/blob/release-1.3/pkg/router/template/router.go#L501) however i don't see the prefix as being mentioned [here](https://github.com/openshift/origin/blob/release-1.3/images/router/haproxy/conf/haproxy-config.template#L466) hence a bit confused how could the map file match the harpoxy backend ...hmm

please help .... :)

**Comment by DanyC97** [comment]
@JacobTanenbaum @Miciah you might be familiar with this code and maybe could help ? 

_sorry for nominating you directly, thank you in advance for any help_

**Comment by pweil-** [comment]
@DanyC97 the prefix mappings are in the template.  They use the map file to find the suffix based on the incoming host name.  So for example, if your traffic is hitting the http public front end with host name of `srv1.router.domain1` it is translated to `be_http_proj1_svc1` [here](https://github.com/openshift/origin/blob/release-1.3/images/router/haproxy/conf/haproxy-config.template#L107-L111).

The same type of logic can be found in the special processing for [other types of routes](https://github.com/openshift/origin/blob/release-1.3/images/router/haproxy/conf/haproxy-config.template#L160-L167)

**Comment by DanyC97** [comment]
@pweil- thank you for response. Seems i went down the rabbit hole thinking the mapping should be the problem for my main issue.

IF you don't mind asking you one more question:  

any tips (maybe how i can troubleshoot further w/o going again on a wrong path ;-( ) you could share which could help me understand why when i do a `curl http://srv1.router.domain1` i do see the request hitting my router (looking in the haproxy debug logs fwd to my remote syslog server) but i don't see the request hitting my pod. 

_I'm not sure if this could be because i'm not setting any headers, are they required/ must?_

**Comment by pweil-** [comment]
For http the host should be available so I wouldn't expect any special headers to be required.

Couple things of note:

1.  I notice your service is of type `LoadBalancer` and has external IPs.  I'm not sure the use case here but generally, if you're using the router for this service, you wouldn't need that.  The router becomes the ingress point (ie your public dns name points to the router ip)

2.  In your original comment I don't see any [servers](https://github.com/openshift/origin/blob/release-1.3/images/router/haproxy/conf/haproxy-config.template#L306-L314) listed in `backend be_http_proj1_svc1`.  These server entries come from the endpoints of the service.  Use `oc get endpoints <service name>` to see if any show up.

I'd first check the endpoints to see if any are showing up.  If not it is usually an indicator of pods being in a bad state.  So I'd usually go with 

1.  can I curl the pod directly
2.  do endpoints show up on the service
3.  can I curl the service
4.  is the service/endpoints picked up by the router (looks like it is in your case)
5.  can I curl the router ip with that host like I have a dns record (ie. `curl -H Host:www.example.com <your router ip>`)

**Comment by DanyC97** [comment]
@pweil-  first thanks for reply.

on 1) is known issue, you are right and will be changed
on 2) yes they show up, all is good

As for the other points 1-4 all looks good, i'll try now point 5) but i see you using with `-H Host:www.example.com1 is this mandatory?

because my e2e test is like this:

* on `server1` i have a mapping in `/etc/hosts` file like `1.1.1.1  srv1.router.domain1` because it can't contact the DNS server
* from `server1` i run `curl http://srv1.router.domain1` as you see w/o `-H` 

i have a feeling the `-H` is required for haproxy to be able to redirect/ fwd the request

**Comment by pweil-** [comment]
@DanyC97 it's mandatory if you aren't resolving `srv1.router.domain1` via dns or some other way.  Using an `/etc/hosts` entry should be ok because the host of `srv1.router.domain1` is resolved.  You can give the curl command a shot though to see if you get different results

Ok, so if you have `server` directives in the router then it sounds like they are being picked up correctly.  

If you can also curl those endpoints directly and get the expected response then my last guess would be that the backends are considered down by the router for some reason.

If you have the [stats console available](https://docs.openshift.org/latest/admin_guide/router.html#viewing-statistics) you can see what haproxy thinks the status of the servers is.

If you've disabled the console for any reason you should also be able to get the stats from the socket by running this within the router container `echo "show stat" | socat unix-connect:/var/lib/haproxy/run/haproxy.sock stdio`.

If the backends are considered down by haproxy (but you're able to curl the IPs in `server` directly) it may indicate that the router pod is having a network issue.

**Comment by DanyC97** [comment]
@pweil- thx a lot again
