### ISSUE TITLE
cannot import docker images from docker private repository 

### ISSUE THREAD

**Issue by samiaben88** [openshift/origin#13303]
I install openshift origin on two kvm (1 master and 1 slave) using ansible.

all the images that I need are stored into an external private docker registry.

##### Current Result

to deploy my micro services I did:

docker pull private-repo:5000/repo-name/image-name:tag
docker tag image-id  internal-repo:5000/project-name/image-name:tag
oc new-app internal-repo:5000/project-name/image-name:tag

it deploy my micro-services and add an image-stream in the internal registry.

Till now everything works fine. 

##### Expected Result

in order to import images directly from the external repository I did follow the doc: 
https://docs.openshift.com/container-platform/3.4/dev_guide/managing_images.html

and create secret from .docker/config.json  and 
oc secrets new pull-secrets--registry .dockerconfigjson=/root/.docker/config.json
oc secrets add serviceaccount/default secrets/pull-secrets-registry --for=pull
oc secrets add serviceaccount/builder secrets/pull-secrets-registry

The expected results would be to import directly the docker images but instead of that I get:

[root@master .docker]# oc new-app --docker-image='docker-registry.xxxx.com:5000/xxx-releases/xxx-ui-admin:2.6' --loglevel=4
I0308 16:59:27.307711   47343 dockerimagelookup.go:73] checking remote registry for "docker-registry.xxxx.com:5000/xxxx-releases/xxxx-ui-admin:2.6"
I0308 16:59:28.578453   47343 dockerimagelookup.go:208] image import failed: api.ImageImportStatus{Tag:"2.6", Status:unversioned.Status{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ListMeta:unversioned.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"you may not have access to the Docker image \"docker-registry.xxxx.com:5000/xxxx-releases/xxxx-ui-admin:2.6\"", Reason:"Unauthorized", Details:(*unversioned.StatusDetails)(nil), Code:401}, Image:(*api.Image)(nil)}
I0308 16:59:28.578541   47343 dockerimagelookup.go:92] checking local Docker daemon for "docker-registry.xxxx.com:5000/xxxx-releases/xxxx-ui-admin:2.6"
I0308 16:59:28.604448   47343 dockerimagelookup.go:380] partial match on "docker-registry.xxxx.com:5000/xxxx-snapshots/xxxx-ui-admin:3.0" with 0.500000
I0308 16:59:28.604488   47343 dockerimagelookup.go:380] partial match on "xxxx-ui-admin:3.0" with 0.500000
F0308 16:59:28.611404   47343 helpers.go:110] error: multiple images or templates matched "docker-registry.xxxx.com:5000/xxxx-releases/xxxx-ui-admin:2.6": 2

The argument "docker-registry.xxxx.com:5000/xxxx-releases/xxxx-ui-admin:2.6" could apply to the following Docker images, OpenShift image streams, or templates:

* Docker image "docker-registry.xxxx.com:5000/xxxx-snapshots/xxxx-ui-admin:3.0", 8b72667, from docker-registry.xxxx.com:5000, 203.594mb
  Use --docker-image="docker-registry.xxxx.com:5000/xxxx-snapshots/xxxx-ui-admin:3.0" to specify this image or template

* Docker image "xxxx-ui-admin:3.0", 8b72667, from docker-registry.xxxx.com:5000, 203.594mb
  Use --docker-image="xxxx-ui-admin:3.0" to specify this image or template

##### Version
oc version
oc v1.3.3
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.xxxx.com:8443
openshift v1.3.3
kubernetes v1.3.0+52492b4

Any help please?

**Comment by samiaben88** [comment]
Any help please?

**Comment by miminar** [comment]
@samiaben88 I've just succeeded with the `new-app` using my private docker hub repository. I had to run only:
```
oc secrets new pull-secrets .dockerconfigjson=~/.docker/config.json
```

There may be something special about your registry name which causes secrets not to be matched. Can you reveal the registry host name?

**Comment by samiaben88** [comment]
I create a new secret and now it is working :o , I'm really glad but I don't know what was the cause of the error :s 
any way thanks a lot ^^

**Comment by miminar** [comment]
@samiaben88 glad it works for you. Feel free to re-open if you hit this again.
