### ISSUE TITLE
Improve import errors reporting to users

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13319]
Discovered here: https://github.com/openshift/origin/pull/13313#discussion_r105185524

Basically when an user initiate import from repository or use image stream that has multiple tags, the importer will not properly update the image stream status with the errors if they occur.

Instead the errors are logged (V(4)) into the server log and burried there. That in turn results to an image stream that is stuck in "importing tag foo" forever.

We should have better mechanism to report import errors, that does not rely exclusively on "tags".

**Comment by soltysh** [comment]
I'm adding 1.6 milestone to this one, I'd like to see this done asap.

**Comment by mfojtik** [comment]
@bparees I think this deserves a Trello card (we want to start using conditions for IS to report import errors/progress/etc.)

**Comment by bparees** [comment]
trello'd https://trello.com/c/kevT8FIa
