### ISSUE TITLE
 couldn't get deployment docker-registry-1

### ISSUE THREAD

**Issue by barleyer** [openshift/origin#13338]
[provide a description of the issue]
When I finish deploying openshift by  BYO ， docker-registry，router，registry-console 3 pods can not deploy. master，node and etcd all in one host。
##### Version
[provide output of the `openshift version` or `oc version` command]
[root@hna-225 ~]# oc version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.71.84.225:8443
openshift v1.3.1
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. [step 1]
ansible-playbook -i backup/hosts openshift-ansible/playbooks/byo/config.yml 

##### Current Result
pod log ：
error: couldn't get deployment docker-registry-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp 172.30.0.1:443: getsockopt: no route to host

##### Expected Result
docker-registry，router，registry-console 3 pods can  deploy.

###more information ####

[root@hna-225 ~]# systemctl status iptables.service 
● iptables.service - IPv4 firewall with iptables
   Loaded: loaded (/usr/lib/systemd/system/iptables.service; enabled; vendor preset: disabled)
   Active: active (exited) since 五 2017-03-10 14:23:16 CST; 1min 23s ago
  Process: 12043 ExecStop=/usr/libexec/iptables/iptables.init stop (code=exited, status=0/SUCCESS)
  Process: 12392 ExecStart=/usr/libexec/iptables/iptables.init start (code=exited, status=0/SUCCESS)
 Main PID: 12392 (code=exited, status=0/SUCCESS)

[root@hna-225 ~]# oc get ep
NAME               ENDPOINTS                                               AGE
docker-registry    <none>                                                  18m
kubernetes         10.71.84.225:8443,10.71.84.225:8053,10.71.84.225:8053   22h
registry-console   <none>                                                  22h
router             <none>                                                  22h

[root@hna-225 ~]# iptables-save |grep 172.30.0.1
-A KUBE-SERVICES -d 172.30.0.1/32 -p udp -m comment --comment "default/kubernetes:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-3VQ6B3MLH7E2SZT4
-A KUBE-SERVICES -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-BA6I5HTZKAAAJT56
-A KUBE-SERVICES -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
[root@hna-225 ~]# iptables-save |grep KUBE-SVC-NPX46M4PTMTKRN6Y
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
-A KUBE-SERVICES -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 180 --reap --name KUBE-SEP-XVW6ARXHYT2T7E3A --mask 255.255.255.255 --rsource -j KUBE-SEP-XVW6ARXHYT2T7E3A
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-XVW6ARXHYT2T7E3A
[root@hna-225 ~]# iptables-save |grep KUBE-SEP-XVW6ARXHYT2T7E3A
:KUBE-SEP-XVW6ARXHYT2T7E3A - [0:0]
-A KUBE-SEP-XVW6ARXHYT2T7E3A -s 10.71.84.225/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-XVW6ARXHYT2T7E3A -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-XVW6ARXHYT2T7E3A --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 10.71.84.225:8443
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 180 --reap --name KUBE-SEP-XVW6ARXHYT2T7E3A --mask 255.255.255.255 --rsource -j KUBE-SEP-XVW6ARXHYT2T7E3A
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-XVW6ARXHYT2T7E3A
[root@hna-225 ~]# ip route 
default via 10.71.84.1 dev enp0s25  proto static  metric 100 
10.1.0.0/16 dev tun0  proto kernel  scope link 
10.71.84.0/24 dev enp0s25  proto kernel  scope link  src 10.71.84.225  metric 100 
172.30.0.0/16 dev tun0  scope link

**Comment by scheng1** [comment]
@ganhuang

**Comment by scheng1** [comment]
This is hosts file：

[OSEv3:children]
masters
etcd
nodes
#new_nodes
#lb

[OSEv3:vars]
deployment_type=origin
containerized=false
openshift_install_examples=true
openshift_master_default_subdomain=mytest.com
ansible_ssh_user=root
#openshift_release=v1.3
openshift_pkg_version=-1.3.1

#openshift_master_cluster_method=native
#openshift_master_cluster_hostname=hna-227
#openshift_master_cluster_public_hostname=hna-227

openshift_router_selector='region=master'
openshift_registry_selector='region=master'
#openshift_hosted_router_replicas=3


#openshift_set_hostname=True
#openshift_node_dnsmasq_additional_config_file=/root/origin-dnsmasq.conf

oreg_url=e4557337.m.daocloud.io/openshift/origin-${component}:${version}
openshift_dns_ip=8.8.8.8
#openshift_hosted_logging_deploy=true


# Skip upgrading Docker during an OpenShift upgrade, leaves the current Docker version alone.
docker_upgrade=False

# default project node selector
#osm_default_node_selector='region=primary'
[OSEv3:children]
masters
etcd
nodes
#new_nodes
#lb

[OSEv3:vars]
deployment_type=origin
containerized=false
openshift_install_examples=true
openshift_master_default_subdomain=mytest.com
ansible_ssh_user=root
openshift_release=v1.3
openshift_pkg_version=-1.3.1

#openshift_master_cluster_method=native
#openshift_master_cluster_hostname=hna-227
#openshift_master_cluster_public_hostname=hna-227

openshift_router_selector='region=master'
openshift_registry_selector='region=master'
#openshift_hosted_router_replicas=3


#openshift_set_hostname=True
#openshift_node_dnsmasq_additional_config_file=/root/origin-dnsmasq.conf

oreg_url=e4557337.m.daocloud.io/openshift/origin-${component}:${version}
openshift_docker_insecure_registries=hub.hcpaas.com,bjdhub.haihangyun.com,hkdmirror.haihangyun.com,e4557337.m.daocloud.io
#openshift_docker_options="--registry-mirror=http://bjdhub.haihangyun.com"
openshift_docker_options="--registry-mirror=http://e4557337.m.daocloud.io"
openshift_dns_ip=8.8.8.8
#openshift_hosted_logging_deploy=true


# Skip upgrading Docker during an OpenShift upgrade, leaves the current Docker version alone.
docker_upgrade=False

# default project node selector
#osm_default_node_selector='region=primary'

# Override the default pod eviction timeout
openshift_master_pod_eviction_timeout=2m

# Override master servingInfo.maxRequestsInFlight
openshift_master_max_requests_inflight=1000


[masters]
hna-225
[etcd]
hna-225
[nodes]
hna-225 openshift_node_labels="{'region': 'master', 'zone': 'master-2'}" openshift_scheduleable=true

**Comment by scheng1** [comment]
hosts file:
[OSEv3:children]
masters
etcd
nodes
#new_nodes
#lb

[OSEv3:vars]
deployment_type=origin
containerized=false
openshift_install_examples=true
openshift_master_default_subdomain=mytest.com
ansible_ssh_user=root
openshift_release=v1.3
openshift_pkg_version=-1.3.1

#openshift_master_cluster_method=native
#openshift_master_cluster_hostname=hna-227
#openshift_master_cluster_public_hostname=hna-227

openshift_router_selector='region=master'
openshift_registry_selector='region=master'
#openshift_hosted_router_replicas=3


#openshift_set_hostname=True
#openshift_node_dnsmasq_additional_config_file=/root/origin-dnsmasq.conf

oreg_url=e4557337.m.daocloud.io/openshift/origin-${component}:${version}
openshift_docker_insecure_registries=hub.hcpaas.com,bjdhub.haihangyun.com,hkdmirror.haihangyun.com,e4557337.m.daocloud.io
#openshift_docker_options="--registry-mirror=http://bjdhub.haihangyun.com"
openshift_docker_options="--registry-mirror=http://e4557337.m.daocloud.io"
openshift_dns_ip=8.8.8.8

##logging
#openshift_hosted_logging_deploy=true
#penshift_master_logging_public_url=https://kibana.logging.com
#openshift_hosted_logging_elasticsearch_cluster_size=1


debug_level=5

#Skip upgrading Docker during an OpenShift upgrade, leaves the current Docker version alone.
docker_upgrade=False

#default project node selector
#osm_default_node_selector='region=primary'

#Override the default pod eviction timeout
openshift_master_pod_eviction_timeout=2m

#Override master servingInfo.maxRequestsInFlight
openshift_master_max_requests_inflight=1000


[masters]
hna-225
[etcd]
hna-225
[nodes]
hna-225 openshift_node_labels="{'region': 'master', 'zone': 'master-2'}" openshift_scheduleable=true

**Comment by pweil-** [comment]
@scheng1 to help us debug what is going on here, which pod is producing 

```
pod log ：
error: couldn't get deployment docker-registry-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp 172.30.0.1:443: getsockopt: no route to host
``` 

You also mention that 2 other pods (router and a registry console) cannot deploy.  Are they producing different errors?  

With an error like `https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp 172.30.0.1:443: getsockopt: no route to host` I'm not sure this is a registry deployment issue but we can start debugging there.

**Comment by scheng1** [comment]
yes, they  are   producing different errors. @pweil-

**Comment by debianmaster** [comment]
from masters/nodes are you able to 
`host docker-registry.default.svc.cluster.local`  ?

**Comment by scheng1** [comment]
no， @debianmaster 
[root@hna-225 ~]# telnet docker-registry.default.svc.cluster.local 5000
Trying 172.30.39.236...
telnet: connect to address 172.30.39.236: Connection refused

[root@hna-225 ~]# iptables-save |grep 172.30.39.236
-A KUBE-SERVICES -d 172.30.39.236/32 -p tcp -m comment --comment "default/docker-registry:5000-tcp cluster IP" -m tcp --dport 5000 -j KUBE-SVC-ECTPRXTXBM34L34Q
-A KUBE-SERVICES -d 172.30.39.236/32 -p tcp -m comment --comment "default/docker-registry:5000-tcp has no endpoints" -m tcp --dport 5000 -j REJECT --reject-with icmp-port-unreachable

**Comment by naveenkumartangallapally** [comment]
Got the same error at docker registry as mentioned by @scheng1 .... I have tried "quick installation method" mentioned in "https://docs.openshift.com/enterprise/3.0/install_config/install/quick_install.html" 

[root@master ~]# host docker-registry.default.svc.cluster.local
docker-registry.default.svc.cluster.local has address 172.30.185.99
[root@master ~]#

@pweil- Please help

**Comment by pweil-** [comment]
Since these are all producing the same networking type symptoms I'm moving this to the network component as it no longer looks related to deployments or the registry

**Comment by debianmaster** [comment]
@pweil-  @naveenkumartangallapally   
please use latest doc  
this one is old
https://docs.openshift.com/enterprise/3.0/install_config/install/quick_install.html

Latest
https://docs.openshift.com/enterprise/3.4

**Comment by scheng1** [comment]
@ganhuang  strong boy

**Comment by naveenkumartangallapally** [comment]
deployed openshift according to 
https://docs.openshift.com/container-platform/3.4/install_config/install/host_preparation.html
unable to create container for docker registry. 

[root@master1 ~]# oc get pods
NAME                        READY     STATUS    RESTARTS   AGE
docker-registry-2-deploy    0/1       Error     0          13m
registry-console-1-deploy   0/1       Error     0          14m
router-1-deploy             0/1       Error     0          15m
[root@master1 ~]# oc logs registry-console-1-deploy
error: couldn't get deployment registry-console-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/registry-console-1: dial tcp 172.30.0.1:443: getsockopt: connection refused

[root@master1 ~]# ping 172.30.0.1
PING 172.30.0.1 (172.30.0.1) 56(84) bytes of data.
From 10.130.0.1 icmp_seq=1 Destination Host Unreachable
From 10.130.0.1 icmp_seq=2 Destination Host Unreachable
From 10.130.0.1 icmp_seq=3 Destination Host Unreachable


[root@master1 ~]# cat /etc/sysconfig/docker |grep -i insecure
OPTIONS=' --selinux-enabled --log-driver=json-file --log-opt max-size=50m'
# adding the registry to the INSECURE_REGISTRY line and uncommenting it.
INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'
[root@master1 ~]#

**Comment by debianmaster** [comment]
`oc get events -n default` ?   
what command did you execute to deploy registry?

**Comment by naveenkumartangallapally** [comment]
these containers are created by quick installation method,       
no command was used to deploy registry.

**Comment by naveenkumartangallapally** [comment]
getting below error when running above command:
oc get events -n default 

[root@master1 ~]# 
[root@master1 ~]# oc get events -n default
LASTSEEN   FIRSTSEEN   COUNT     NAME                       KIND      SUBOBJECT   TYPE      REASON       SOURCE                        MESSAGE
59m        59m         1         docker-registry-1-deploy   Pod                   Normal    Scheduled    {default-scheduler }          Successfully assigned docker-registry-1-deploy to node1.example.com
58m        58m         1         docker-registry-1-deploy   Pod                   Warning   FailedSync   {kubelet node1.example.com}   Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "net/http: request canceled"

58m       58m       1         docker-registry-2-deploy   Pod                                     Normal    Scheduled    {default-scheduler }          Successfully assigned docker-registry-2-deploy to node1.example.com
52m       55m       2         docker-registry-2-deploy   Pod       spec.containers{deployment}   Normal    Pulling      {kubelet node1.example.com}   pulling image "openshift3/ose-deployer:v3.4.1.10"
53m       53m       1         docker-registry-2-deploy   Pod       spec.containers{deployment}   Warning   Failed       {kubelet node1.example.com}   Failed to pull image "openshift3/ose-deployer:v3.4.1.10": net/http: request canceled
53m       53m       1         docker-registry-2-deploy   Pod                                     Warning   FailedSync   {kubelet node1.example.com}   Error syncing pod, skipping: failed to "StartContainer" for "deployment" with ErrImagePull: "net/http: request canceled"

49m       49m       1         docker-registry-2-deploy   Pod       spec.containers{deployment}   Normal    Pulled       {kubelet node1.example.com}   Successfully pulled image "openshift3/ose-deployer:v3.4.1.10"
49m       49m       1         docker-registry-2-deploy   Pod       spec.containers{deployment}   Normal    Created      {kubelet node1.example.com}   Created container with docker id f98045bbe0cc; Security:[seccomp=unconfined]
49m       49m       1         docker-registry-2-deploy   Pod       spec.containers{deployment}   Normal    Started      {kubelet node1.example.com}   Started container with docker id f98045bbe0cc
49m       49m       1         docker-registry-2-deploy   Pod                                     Warning   FailedSync   {kubelet node1.example.com}   Error syncing pod, skipping: error killing pod: failed to "TeardownNetwork" for "docker-registry-2-deploy_default" with TeardownNetworkError: "Failed to teardown network for pod \"69fc869f-1310-11e7-87de-080027ec090d\" using network plugins \"cni\": CNI request failed with status 400: 'failed to get host veth: invalid argument\n'"

59m       59m       1         docker-registry             DeploymentConfig             Normal    DeploymentCreated                {deploymentconfig-controller }     Created new replication controller "docker-registry-1" for version 1
59m       59m       1         docker-registry             DeploymentConfig             Normal    DeploymentCancelled              {deploymentconfig-controller }     Cancelled deployment "docker-registry-1" superceded by version 2
59m       59m       30        docker-registry             DeploymentConfig             Normal    DeploymentAwaitingCancellation   {deploymentconfig-controller }     Deployment of version 2 awaiting cancellation of older running deployments
58m       58m       1         docker-registry             DeploymentConfig             Normal    DeploymentCancelled              {deployments-controller }          docker-registry-1: Deployment "default/docker-registry-1" cancelled
58m       58m       1         docker-registry             DeploymentConfig             Normal    DeploymentCreated                {deploymentconfig-controller }     Created new replication controller "docker-registry-2" for version 2
1h        1h        1         master1.example.com         Node                         Normal    Starting                         {kubelet master1.example.com}      Starting kubelet.
1h        1h        2         master1.example.com         Node                         Normal    NodeHasSufficientDisk            {kubelet master1.example.com}      Node master1.example.com status is now: NodeHasSufficientDisk
1h        1h        2         master1.example.com         Node                         Normal    NodeHasSufficientMemory          {kubelet master1.example.com}      Node master1.example.com status is now: NodeHasSufficientMemory
1h        1h        2         master1.example.com         Node                         Normal    NodeHasNoDiskPressure            {kubelet master1.example.com}      Node master1.example.com status is now: NodeHasNoDiskPressure
1h        1h        1         master1.example.com         Node                         Normal    RegisteredNode                   {controllermanager }               Node master1.example.com event: Registered Node master1.example.com in NodeController
1h        1h        1         master1.example.com         Node                         Normal    Starting                         {kube-proxy master1.example.com}   Starting kube-proxy.
1h        1h        1         master1.example.com         Node                         Normal    Starting                         {kubelet master1.example.com}      Starting kubelet.
1h        1h        1         master1.example.com         Node                         Normal    NodeHasSufficientDisk            {kubelet master1.example.com}      Node master1.example.com status is now: NodeHasSufficientDisk
1h        1h        1         master1.example.com         Node                         Normal    NodeHasSufficientMemory          {kubelet master1.example.com}      Node master1.example.com status is now: NodeHasSufficientMemory
1h        1h        1         master1.example.com         Node                         Normal    NodeHasNoDiskPressure            {kubelet master1.example.com}      Node master1.example.com status is now: NodeHasNoDiskPressure
1h        1h        1         master1.example.com         Node                         Normal    Starting                         {kube-proxy master1.example.com}   Starting kube-proxy.
5m        1h        2         master1.example.com         Node                         Normal    NodeNotSchedulable               {kubelet master1.example.com}      Node master1.example.com status is now: NodeNotSchedulable
1h        1h        1         master1.example.com         Node                         Normal    NodeReady                        {kubelet master1.example.com}      Node master1.example.com status is now: NodeReady
17m       17m       1         master1.example.com         Node                         Normal    NodeSchedulable                  {kubelet master1.example.com}      Node master1.example.com status is now: NodeSchedulable
1h        1h        1         node1.example.com           Node                         Normal    Starting                         {kubelet node1.example.com}        Starting kubelet.
1h        1h        2         node1.example.com           Node                         Normal    NodeHasSufficientDisk            {kubelet node1.example.com}        Node node1.example.com status is now: NodeHasSufficientDisk
1h        1h        2         node1.example.com           Node                         Normal    NodeHasSufficientMemory          {kubelet node1.example.com}        Node node1.example.com status is now: NodeHasSufficientMemory
1h        1h        2         node1.example.com           Node                         Normal    NodeHasNoDiskPressure            {kubelet node1.example.com}        Node node1.example.com status is now: NodeHasNoDiskPressure
1h        1h        1         node1.example.com           Node                         Normal    RegisteredNode                   {controllermanager }               Node node1.example.com event: Registered Node node1.example.com in NodeController
1h        1h        1         node1.example.com           Node                         Normal    Starting                         {kube-proxy node1.example.com}     Starting kube-proxy.
1h        1h        1         node1.example.com           Node                         Normal    Starting                         {kubelet node1.example.com}        Starting kubelet.
1h        1h        1         node1.example.com           Node                         Normal    NodeHasSufficientDisk            {kubelet node1.example.com}        Node node1.example.com status is now: NodeHasSufficientDisk
1h        1h        1         node1.example.com           Node                         Normal    NodeHasSufficientMemory          {kubelet node1.example.com}        Node node1.example.com status is now: NodeHasSufficientMemory
1h        1h        1         node1.example.com           Node                         Normal    NodeHasNoDiskPressure            {kubelet node1.example.com}        Node node1.example.com status is now: NodeHasNoDiskPressure
1h        1h        1         node1.example.com           Node                         Normal    Starting                         {kube-proxy node1.example.com}     Starting kube-proxy.
1h        1h        1         node1.example.com           Node                         Normal    NodeReady                        {kubelet node1.example.com}        Node node1.example.com status is now: NodeReady
1h        1h        1         node2.example.com           Node                         Normal    Starting                         {kubelet node2.example.com}        Starting kubelet.
1h        1h        2         node2.example.com           Node                         Normal    NodeHasSufficientDisk            {kubelet node2.example.com}        Node node2.example.com status is now: NodeHasSufficientDisk
1h        1h        2         node2.example.com           Node                         Normal    NodeHasSufficientMemory          {kubelet node2.example.com}        Node node2.example.com status is now: NodeHasSufficientMemory
1h        1h        2         node2.example.com           Node                         Normal    NodeHasNoDiskPressure            {kubelet node2.example.com}        Node node2.example.com status is now: NodeHasNoDiskPressure
1h        1h        1         node2.example.com           Node                         Normal    RegisteredNode                   {controllermanager }               Node node2.example.com event: Registered Node node2.example.com in NodeController
1h        1h        1         node2.example.com           Node                         Normal    Starting                         {kube-proxy node2.example.com}     Starting kube-proxy.
1h        1h        1         node2.example.com           Node                         Normal    Starting                         {kubelet node2.example.com}        Starting kubelet.
1h        1h        2         node2.example.com           Node                         Normal    NodeHasSufficientDisk            {kubelet node2.example.com}        Node node2.example.com status is now: NodeHasSufficientDisk
1h        1h        2         node2.example.com           Node                         Normal    NodeHasSufficientMemory          {kubelet node2.example.com}        Node node2.example.com status is now: NodeHasSufficientMemory
1h        1h        2         node2.example.com           Node                         Normal    NodeHasNoDiskPressure            {kubelet node2.example.com}        Node node2.example.com status is now: NodeHasNoDiskPressure
1h        1h        1         node2.example.com           Node                         Normal    Starting                         {kube-proxy node2.example.com}     Starting kube-proxy.
1h        1h        1         node2.example.com           Node                         Normal    NodeReady                        {kubelet node2.example.com}        Node node2.example.com status is now: NodeReady
59m       59m       1         registry-console-1-deploy   Pod                          Normal    Scheduled                        {default-scheduler }               Successfully assigned registry-console-1-deploy to node2.example.com
57m       57m       1         registry-console-1-deploy   Pod                          Warning   FailedSync                       {kubelet node2.example.com}        Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "net/http: request canceled"

55m       55m       1         registry-console-1-deploy   Pod                spec.containers{deployment}   Normal    Pulling             {kubelet node2.example.com}      pulling image "openshift3/ose-deployer:v3.4.1.10"
51m       51m       1         registry-console-1-deploy   Pod                spec.containers{deployment}   Normal    Pulled              {kubelet node2.example.com}      Successfully pulled image "openshift3/ose-deployer:v3.4.1.10"
51m       51m       1         registry-console-1-deploy   Pod                spec.containers{deployment}   Normal    Created             {kubelet node2.example.com}      Created container with docker id 1231cdbc10e8; Security:[seccomp=unconfined]
51m       51m       1         registry-console-1-deploy   Pod                spec.containers{deployment}   Normal    Started             {kubelet node2.example.com}      Started container with docker id 1231cdbc10e8
59m       59m       1         registry-console            DeploymentConfig                                 Normal    DeploymentCreated   {deploymentconfig-controller }   Created new replication controller "registry-console-1" for version 1
1h        1h        1         router-1-deploy             Pod                                              Normal    Scheduled           {default-scheduler }             Successfully assigned router-1-deploy to node2.example.com
58m       58m       1         router-1-deploy             Pod                                              Warning   FailedSync          {kubelet node2.example.com}      Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "net/http: request canceled"

55m       55m       1         router-1-deploy   Pod                spec.containers{deployment}   Normal    Pulling             {kubelet node2.example.com}      pulling image "openshift3/ose-deployer:v3.4.1.10"
51m       51m       1         router-1-deploy   Pod                spec.containers{deployment}   Normal    Pulled              {kubelet node2.example.com}      Successfully pulled image "openshift3/ose-deployer:v3.4.1.10"
51m       51m       1         router-1-deploy   Pod                spec.containers{deployment}   Normal    Created             {kubelet node2.example.com}      Created container with docker id b9adbc4a4c7b; Security:[seccomp=unconfined]
51m       51m       1         router-1-deploy   Pod                spec.containers{deployment}   Normal    Started             {kubelet node2.example.com}      Started container with docker id b9adbc4a4c7b
1h        1h        1         router            DeploymentConfig                                 Normal    DeploymentCreated   {deploymentconfig-controller }   Created new replication controller "router-1" for version 1
[root@master1 ~]#

**Comment by debianmaster** [comment]
do you see any other erros on  `Monitoring` section in  UI?

**Comment by naveenkumartangallapally** [comment]
we are not yet at the dashbord login step,actually pods are in error state.

[root@master1 ~]# oc get pods
NAME                        READY     STATUS    RESTARTS   AGE
docker-registry-2-deploy    0/1       Error     0          1h
registry-console-1-deploy   0/1       Error     0          1h
router-1-deploy             0/1       Error     0          1h

**Comment by debianmaster** [comment]
you should be able to login irrespective of pods crashing.     
goto    https://master:8443

**Comment by naveenkumartangallapally** [comment]
i am able to login dashboard,but not able to pull images

**Comment by naveenkumartangallapally** [comment]
hi i am getting below error:

kindly help me to solve the issue:

[root@master1 ~]# oc get pods
NAME                        READY     STATUS    RESTARTS   AGE
docker-registry-2-deploy    0/1       Error     0          56m
registry-console-1-deploy   0/1       Error     0          56m
router-1-deploy             0/1       Error     0          57m
[root@master1 ~]# oc logs docker-registry-2-deploy
--> Waiting up to 10m0s for pods in deployment docker-registry-2 to become ready
error: update acceptor rejected docker-registry-2: pods for deployment "docker-registry-2" took longer than 600 seconds to become ready
[root@master1 ~]# oc logs docker-registry-2-deploy
--> Waiting up to 10m0s for pods in deployment docker-registry-2 to become ready
error: update acceptor rejected docker-registry-2: pods for deployment "docker-registry-2" took longer than 600 seconds to become ready
[root@master1 ~]#

**Comment by debianmaster** [comment]
@naveenkumartangallapally  add me on gtalk    9chakri [at] gmail.com  so we can debug

**Comment by naveenkumartangallapally** [comment]
ok sure

**Comment by arialdomartini** [comment]
Hi @debianmaster 
I'm experiencing the same issue. Any chance to get some help as well? I would appreciate a lot!

**Comment by naveen408** [comment]
Hello Debian master, 
i am  also  experiencing the same  issue  , i am using  tomcat 8 S2I catalog to  deploy   helloworld   java app. However i see the  below error ? 

Any  advise or help  ?


> Scaling javahello-1 to 1
--
  | --> Waiting up to 10m0s for pods in deployment javahello-1 to become ready
  | error: update acceptor rejected javahello-1: pods for deployment "javahello-1" took longer than 600 seconds to become read

**Comment by debianmaster** [comment]
@naveen408  @arialdomartini    can you please send your error messages

**Comment by naveen408** [comment]
i dont see any  thing in events and this  is what i see in logs . 


--> Scaling javahello-1 to 1
--
  | --> Waiting up to 10m0s for pods in deployment javahello-1 to become ready
  | error: update acceptor rejected javahello-1: pods for deployment "javahello-1" took longer than 600 seconds to become ready

**Comment by naveen408** [comment]
some  more information 

Container deployment

State:
Terminated at Jul 12, 2017 11:13:34 AM with exit code 1 (Error)
Ready:
false
Restart Count:
0

**Comment by naveen408** [comment]
Attached  logs and  events  information.
[Oc-eventsinformation.txt](https://github.com/openshift/origin/files/1143265/Oc-eventsinformation.txt)
[oclogs.txt](https://github.com/openshift/origin/files/1143266/oclogs.txt)
