### ISSUE TITLE
Internal DNS not working from PoD

### ISSUE THREAD

**Issue by prasenforu** [openshift/origin#13341]
Env : AWS, custom dns setup

OSE 3.3 

Problem:
Opesnhift Internal DNS not working from PoD but from PoD external resolution working .
From Host kubernetes internal dns resolving. 

Below output From PoD:

```
 # nslookup google.com
Server:    10.90.2.210
Address 1: 10.90.2.210

Name:      google.com
Address 1: 2404:6800:4006:803::200e syd09s12-in-x0e.1e100.net
Address 2: 216.58.199.46 syd09s12-in-f46.1e100.net

 # nslookup kubernetes.svc.cluster.local
Server:    10.90.2.210
Address 1: 10.90.2.210

nslookup: can't resolve 'kubernetes.svc.cluster.local'

# nslookup 172.30.0.1
Server:    10.90.2.210
Address 1: 10.90.2.210

Name:      172.30.0.1
Address 1: 172.30.0.1
```

Pod resolve.conf:
```
# more /etc/resolv.conf
# Generated by NetworkManager
search cloud-cafe.in
nameserver 10.90.2.210
# nameserver updated by /etc/NetworkManager/dispatcher.d/99-origin-dns.sh

```
Below output From Host:

```
[root@ose-master ~]# nslookup google.com
Server:         10.90.1.208
Address:        10.90.1.208#53

Non-authoritative answer:
Name:   google.com
Address: 216.58.199.46

[root@ose-master ~]# nslookup kubernetes.default.svc.cluster.local
Server:         10.90.1.208
Address:        10.90.1.208#53

Name:   kubernetes.default.svc.cluster.local
Address: 172.30.0.1

[root@ose-master ~]# nslookup 172.30.0.1
Server:         10.90.1.208
Address:        10.90.1.208#53

** server can't find 1.0.30.172.in-addr.arpa.: NXDOMAIN

```
Host resolve.conf:
```
[root@ose-master ~]# more /etc/resolv.conf
# Generated by NetworkManager
search cloud-cafe.in
nameserver 10.90.1.208
# nameserver updated by /etc/NetworkManager/dispatcher.d/99-origin-dns.sh
```

**Comment by debianmaster** [comment]
is dnsmasq running on host?

**Comment by prasenforu** [comment]
Yes its running all hosts (master, hub(infra), node1 & node2

```
[root@ns1 ~]# ssh ose-master " ps -lef | grep dnsmasq"
4 S nobody     5922      1  0  80   0 -  3886 poll_s 00:09 ?        00:00:00 /usr/sbin/dnsmasq -k
4 S root       6085   6082  0  80   0 - 28280 wait   00:11 ?        00:00:00 bash -c  ps -lef | grep dnsmasq
0 S root       6089   6085  0  80   0 - 28162 pipe_w 00:11 ?        00:00:00 grep dnsmasq
[root@ns1 ~]# ssh ose-hub " ps -lef | grep dnsmasq"
4 S nobody     6372      1  0  80   0 -  3886 poll_s 00:09 ?        00:00:00 /usr/sbin/dnsmasq -k
4 S root       6592   6589  0  80   0 - 28280 wait   00:11 ?        00:00:00 bash -c  ps -lef | grep dnsmasq
0 S root       6596   6592  0  80   0 - 28162 pipe_w 00:11 ?        00:00:00 grep dnsmasq
[root@ns1 ~]# ssh ose-node1 " ps -lef | grep dnsmasq"
4 S nobody     6088      1  0  80   0 -  3886 poll_s 00:10 ?        00:00:00 /usr/sbin/dnsmasq -k
4 S root       6293   6290  0  80   0 - 28280 wait   00:12 ?        00:00:00 bash -c  ps -lef | grep dnsmasq
0 S root       6297   6293  0  80   0 - 28162 pipe_w 00:12 ?        00:00:00 grep dnsmasq
[root@ns1 ~]# ssh ose-node2 " ps -lef | grep dnsmasq"
4 S nobody      974      1  0  80   0 -  3886 poll_s Mar10 ?        00:00:00 /usr/sbin/dnsmasq -k
4 S root       6034   6031  0  80   0 - 28280 wait   00:12 ?        00:00:00 bash -c  ps -lef | grep dnsmasq
0 S root       6038   6034  0  80   0 - 28163 pipe_w 00:12 ?        00:00:00 grep dnsmasq
```

**Comment by prasenforu** [comment]
Another observation, its resolving ip with ip.
Like if I do 

# nslookup 172.30.0.1
Server:    10.90.2.210
Address 1: 10.90.2.210

Name:      172.30.0.1
Address 1: 172.30.0.1

**Comment by prasenforu** [comment]
Any news ?

**Comment by jarekg83** [comment]
+1 
Just faced the same issue, spent 2 days trying to get this sorted to finally realise every single DNS query from within the pod resolves to the local IP of the node the pod is running. 

I'm on version 3.4.

[root@node1 ~]# oc version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

[root@node1 ~]# docker exec -ti e982680cfc78 /bin/sh
sh-4.2$ ping google.com
PING google.com.192.168.56.211.xip.io (192.168.56.211) 56(84) bytes of data.
64 bytes from node1.192.168.56.211.xip.io (192.168.56.211): icmp_seq=1 ttl=64 time=0.145 ms
64 bytes from node1.192.168.56.211.xip.io (192.168.56.211): icmp_seq=2 ttl=64 time=0.115 ms
64 bytes from node1.192.168.56.211.xip.io (192.168.56.211): icmp_seq=3 ttl=64 time=0.061 ms
^C
--- google.com.192.168.56.211.xip.io ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.061/0.107/0.145/0.034 ms
sh-4.2$ ping google.com
PING google.com.192.168.56.211.xip.io (192.168.56.211) 56(84) bytes of data.
64 bytes from node1.192.168.56.211.xip.io (192.168.56.211): icmp_seq=1 ttl=64 time=0.135 ms
^C
--- google.com.192.168.56.211.xip.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.135/0.135/0.135/0.000 ms

On version 3.3 I'm not experiencing this issue.

**Comment by ksemaev** [comment]
OK, I've wasted a lot of time trying to make this DNS for services work.  just to make things clear: in all cluster only openhift master can resolv queries for services. On master you can check it with dig @localhost -p 8053 kubernetes.default.svc.cluster.local

In my case all nodes and masters have file /etc/dnsmasq.d/node-dnsmasq.conf which is basically copied at every start of system from default config file.
They, by default have this entry: server=/in-addr.arpa/127.0.0.1, while the only one who can resolv names in this cluster is master on port 8053.
After setting the valuse of source file to server=/in-addr.arpa/127.0.0.1#8053 - still no luck:
 systemctl status dnsmasq
setting upstream servers from DBus
using nameserver 127.0.0.1#53 for domain cluster.local
using nameserver 127.0.0.1#53 for domain in-addr.arpa

After disabling support for DBus - no luck. Found out this file with some stupied instructions: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_node_dnsmasq/files/networkmanager/99-origin-dns.sh

At this point the file /etc/dnsmasq.d/node-dnsmasq.conf with all my settings is just ignored on master and all nodes, so they are using nameserver 127.0.0.1#53 for domain cluster.local which is nonsense.

The only solution I habe now is set manually needed server in additional config file for dnsmasq

**Comment by jarekg83** [comment]
There should be a dnsmasq upstream configuration as well which is being taken when you configure OpenShift for the first time. It takes your 'legit' DNS servers and puts them into upstream config so if it won't resolve domain from your internal cluster DNS it will pass queries to the upstream servers.

**Comment by Thram** [comment]
I'm having this problem right now
