### ISSUE TITLE
Annoying log message when a job is completed

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13349]
```
E0310 19:50:26.972448    2803 utils.go:91] Unable to get uid from job persistent-volume-setup in namespace default
```

Happens on oc cluster up after that job finishes, logs every few seconds.  Ugly.

@derekwaynecarr @sjenning @soltysh

**Comment by soltysh** [comment]
This is actually cumming from [cronjob controller](https://github.com/openshift/origin/blob/9e4e2e788bd6d42f2258efe218c71af1c62a64b2/vendor/k8s.io/kubernetes/pkg/controller/cronjob/utils.go#L91) and should be silenced definitely.

**Comment by sjenning** [comment]
@smarterclayton it would be easy to change the log level on that message to `V(4)` like the messages in `getParentUIDFromJob()`.  However, I'd like to know why the parent UID can't be found.  At loglevel 4 there should be a message from `getParentUIDFromJob()` on what failed.  Is that something that is expected to work? Should we remove the job after it completes?

**Comment by soltysh** [comment]
@sjenning CronJob controller is still not that mature, there are a few other problems, I'll address this issue when touching the controller next time.

**Comment by soltysh** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/44962, I'll cherry-pick this after the rebase.
