### ISSUE TITLE
Networking tests disable SELinux

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#13347]
Just saw this in the log:

```
02:58:18.636 [INFO] Temporarily disabling selinux enforcement
02:58:21.875 [INFO] Targeting multitenant plugin: redhat/openshift-ovs-multitenant
```

Why does it need to be off? What is the gap for turning it on?

/cc @marun @knobunc @smarterclayton

**Comment by marun** [comment]
Docker-in-docker breaks if selinux is enabled.  Might be fixable, but it will likely require an selinux guru and considerable effort, and I'm not sure that effort would be worth it.

**Comment by stevekuznetsov** [comment]
@pmorie can be our SELinux guru as necessary. We want 100% of our tests to be running with `setenforce 1`. Do we need a card for this issue or can we just work off of this?

**Comment by marun** [comment]
I don't see the point, but sure.

**Comment by stevekuznetsov** [comment]
There are a lot of cases where people make decisions in their tests that are not valid on a system with SELinux enforcing. Do you not think this could happen in the networking tests?

**Comment by marun** [comment]
I think the risk of baking in assumptions in the networking tests that would break on an selinux-enforcing deployment are minimal, and that it doesn't outweigh the cost of maintaining selinux compatibility for a development-only environment.  We've been using dind for testing for ~15 months , and I can't recall a single instance of selinux incompatibility being introduced as a result.

**Comment by rhatdan** [comment]
But what is the reason for turning it off in the first place?  Is there something we could have fixed that caused you to turn it off?

**Comment by stevekuznetsov** [comment]
@marun what was the SELinux denial for DIND? Is it still valid?
