### ISSUE TITLE
HTTP/1.1 violation, oc login fails 503 on haproxy loadbalancing to master api

### ISSUE THREAD

**Issue by sspreitzer** [openshift/origin#13355]
When using oc login on a master, that is behind an haproxy loadbalancer forwarding the request to the master, the request can not be routed as the "Host" header is missing. This is against [HTTP/1.1 RFC 2616](https://tools.ietf.org/html/rfc2616#section-14.23) which expects "Host" header as a MUST.

This is a protocol violation and thereof a software bug.

##### Version
```
[sspreitz@sspreitz byo]$ oc version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.zh.spreitzer.ch:443
openshift v1.4.1
kubernetes v1.4.0+776c994
```

##### Steps To Reproduce
1. Setup an haproxy loadbalancer forwarding request based on "Host" header to master api
2. Try oc login against the loadbalancer url

##### Current Result
Error 503 as haproxy can not route the request

##### Expected Result
RFC compliant HTTP/1.1 request including "Host" header

##### Additional Information
This error can be workaround-ed by adding SSL/TLS SNI based routing to the haproxy logic.
`use_backend openshift if { hdr(Host) -i openshift.zh.spreitzer.ch } or { ssl_fc_sni -i openshift.zh.spreitzer.ch }`

**Comment by pweil-** [comment]
@sspreitzer I'm not sure we have enough to go on here.  It appears that you are using the OpenShift router to front the api server for requests.

In your last statement you mention that using a header check for host or an sni check for the host is fixing your problem which is what the router already does when you set up routes.  Can you include the route definition that you're using for folk to do more debugging?

**Comment by sspreitzer** [comment]
@pweil- I am using an ordinary haproxy installation in front of the api, not an openshift router.

While this one fails
`use_backend openshift if { hdr(Host) -i openshift.zh.spreitzer.ch }`

This one succeeds
`use_backend openshift if { hdr(Host) -i openshift.zh.spreitzer.ch } or { ssl_fc_sni -i openshift.zh.spreitzer.ch }`

That is a very strong indicator of the oc client not sending the "Host" header as of HTTP/1.1. I verified the haproxy logs that oc client uses HTTP/1.1.

**Comment by pweil-** [comment]
@sspreitzer ah, ok, thanks for the clarification.

The client should be making [TLS connections which is why the SNI indicator is working for you but not the Host header check](https://tools.ietf.org/html/rfc3546#section-3.1).  Unless you've terminated the encryption and are still not seeing the right header information.  

Changing this to networking component.

**Comment by sspreitzer** [comment]
@pweil- I am terminating the TLS and do not see the "Host" header.

**Comment by pweil-** [comment]
@sspreitzer ok, got it. :+1: 

@fabianofranz in your hands then

**Comment by fabianofranz** [comment]
cc @liggitt @deads2k

**Comment by liggitt** [comment]
I'm not able to recreate this. 
```
$ oc version
oc v1.4.1+977f53a-32
kubernetes v1.4.0+776c994
features: Basic-Auth
```

running against a debugging server, I see Host headers sent on `oc login` and on normal `oc get ...` API calls

**Comment by liggitt** [comment]
I think your host matching is failing because it doesn't include the port

**Comment by liggitt** [comment]
Does the following work?

`use_backend openshift if { hdr(Host) -i openshift.zh.spreitzer.ch } or { hdr(Host) -i openshift.zh.spreitzer.ch:443 }`

**Comment by sspreitzer** [comment]
@liggitt confirmed

Adding port to the Host Header field works. Thanks!
