### ISSUE TITLE
oc create route edge does not have insecureEdgeTerminationPolicy Allow

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13357]
Even though we claim that the default (in the API) of insecureEdgeTerminationPolicy is allow, that's not actually the outcome if omitted.

We need to:

1. decide the correct behavior (applying a default now would break existing users)
2. figure out whether we regressed in 1.5 when we added more termination policies, and if so add more tests / fix
3. document better
4. potentially fix `oc create edge` to use insecureEdgeTerminationPolicy = Allow by default, if we don't change 1

Edge with allow is the "best case" outcome (since users get TLS termination for free and all routers are in practice set up with a wildcard), so doesn't seem there would be a reason not to behave that way.

**Comment by smarterclayton** [comment]
@knobunc @ramr

**Comment by ramr** [comment]
@smarterclayton  the original default was `none` - meaning we didn't allow it [aka denied http traffic], so am not sure what changed where but @JacobTanenbaum might probably know. 
Jacob?
Also, just me 2 cents (fwiw now! ;^)),  don't think edge with `allow` is a good default (edge with `deny` is better as it forces using secure connections and making the user explicitly enable insecure connections) - that said, edge w/ redirect could be a candidate for the default though ... 

/cc @knobunc

**Comment by smarterclayton** [comment]
We should document None then as the default.  If we want to change create edge we can, but now that you describe the old value I do recall that being the base.  Definitely can't break back compat
