### ISSUE TITLE
Can not run a single package unit test sucessful

### ISSUE THREAD

**Issue by guangxuli** [openshift/origin#13367]
Single package unit tests can not pass.

##### Version
oc v1.5.0-alpha.3+9e4e2e7-354-dirty
kubernetes v1.5.2+43a9be4
features: Basic-Auth

##### Steps To Reproduce
1. [step 1]
**go test -v ./pkg/build/builder/**
2. [step 2]
--- FAIL: TestDockerfilePath (0.00s)
	docker_test.go:198: failed to create tmpdir: mkdir /tmp/openshift-integration/dockerfile-path090939547: no such file or directory
	docker_test.go:198: failed to create tmpdir: mkdir /tmp/openshift-integration/dockerfile-path544528702: no such file or directory
	docker_test.go:198: failed to create tmpdir: mkdir /tmp/openshift-integration/dockerfile-path357757317: no such file or directory
	docker_test.go:198: failed to create tmpdir: mkdir /tmp/openshift-integration/dockerfile-path091360544: no such file or directory
=== RUN   TestEmptySource
--- PASS: TestEmptySource (0.00s)
=== RUN   TestGetDockerfileFrom
--- FAIL: TestGetDockerfileFrom (0.00s)
	docker_test.go:344: failed to create tmpdir: mkdir /tmp/openshift-integration/dockerfile-path059391487: no such file or directory
	docker_test.go:344: failed to create tmpdir: mkdir /tmp/openshift-integration/dockerfile-path114618706: no such file or directory
	docker_test.go:344: failed to create tmpdir: mkdir /tmp/openshift-integration/dockerfile-path807753865: no such file or directory

The directory **/tmp/openshift-integration/** may be created before our full test, but why not make sure the directory has already exist and create the directory if not exist. After then we can make a single package unit tests.

**Comment by stevekuznetsov** [comment]
`/tmp/openshift-integration` does not look like a directory that our Bash would create, maybe it's some other test suite? @bparees would probably know better

**Comment by guangxuli** [comment]
@stevekuznetsov thanks.
@bparees  if this issue is deserved to be fixed, i can try to do that.

**Comment by bparees** [comment]
@guangxuli The normal way to run these tests is `hack/test-go.sh pkg/build/builder` instead as it ensures some necessary environment.

That said, I can't reproduce this running `go test -v ./pkg/build/builder` and I do not have a /tmp/openshift-integration directory.

**Comment by bparees** [comment]
sorry, I see it now.  however running it via hack/test-go.sh does prevent this issue.  Not exactly sure why.

**Comment by bparees** [comment]
Looks like hack/test-go.sh sets up a BASETMPDIR which the downstream tests depend on existing.
