### ISSUE TITLE
How to hide IP and Hostname on origin UI?

### ISSUE THREAD

**Issue by DockerAsura** [openshift/origin#13364]
Hi Team,
Is there any way to hide Hostname and  IP on origin UI page for all user and service account's.

Origin installed in ansible method

Thanks
Asura

**Comment by jwforres** [comment]
I think the answer to your question is no. What IPs are you wanting to hide, Pod IPs? Service IPs?

You could probably write custom CSS and load it as an extension to hide them but you'd have to use some pretty specific text-based selectors and there would be no guarantee of the same CSS working across releases.

https://docs.openshift.org/latest/install_config/web_console_customization.html#loading-custom-scripts-and-stylesheets

**Comment by DockerAsura** [comment]
the node IP or Hostname.

**Comment by jwforres** [comment]
Just following up on this, no there is no way to do this today, and the way its split across a dt element and a dd element you cant really even do this effectively with a text-based CSS selector.  If this is something you need then feel free to open a PR to openshift/origin-web-console that adds a class name to both the dd and dt for the Node, and then you would be able to hide them in your environment using a CSS extension.
