### ISSUE TITLE
maven version updates

### ISSUE THREAD

**Issue by mangirdaz** [openshift/origin#13372]
OCP Java Base images Uses maven to build java code. 
Maven version is old in those images so it does not support multi-module projects. 
Maven version is almost 2-3 years old.

##### Version

docker run -u root -it registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat7-openshift 'mvn' '--version'
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/jboss -Duser.name=jboss
**Apache Maven 3.0.5 (Red Hat 3.0.5-17)**
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.8.6-300.fc25.x86_64", arch: "amd64", family: "unix"

$ docker run -u root -it registry.access.redhat.com/jboss-eap-7/eap70-openshift 'mvn' '--version'
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/jboss -Duser.name=jboss
**Apache Maven 3.0.5 (Red Hat 3.0.5-17)**
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.8.6-300.fc25.x86_64", arch: "amd64", family: "unix"

When image public version has all good:
docker run -u root -it openshift/wildfly-101-centos7 'mvn' '--version'
**Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)**
Maven home: /usr/local/apache-maven-3.3.9
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.8.6-300.fc25.x86_64", arch: "amd64", family: "unix"

**Comment by pweil-** [comment]
This will need to be filed with https://issues.jboss.org for jboss/eap support.  Thanks!
