### ISSUE TITLE
[oc cluster up] - started listening on wrong IP

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#13383]
`oc cluster up` starts up on "random" IP. This has always been the case and I have been mentioning it in issues before, that it needs to take a flag to specify listening address but I was told that you can specify `--public-hostname` and that's enough. Although that worked for one of my use cases It can't ever work when you are behind NAT and you want to specify different public-hostname and listen IP.

Now even specifying public-ip stopped working.

@csrwng 

##### Version
```
$ oc version
oc v1.5.0-alpha.3+f617108-367
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://10.34.250.70:8443
openshift v1.5.0-alpha.3+87ca44f-314
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. 
```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether ...
    inet 10.34.250.70/22 brd 10.34.251.255 scope global dynamic wlp3s0
       valid_lft 85805sec preferred_lft 85805sec
3: enp0s25: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether ... brd ff:ff:ff:ff:ff:ff
4: oc0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether ... brd ff:ff:ff:ff:ff:ff
    inet 192.168.42.42/32 brd 192.168.42.42 scope global oc0
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether ... brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

2. oc cluster up --version=latest --metrics --public-hostname 192.168.42.42

##### Current Result
```bash
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... 
   WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:latest image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 10.34.250.70 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Installing metrics ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... 
   Now using project "myproject" on server "https://10.34.250.70:8443".
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.42:8443

   The metrics service is available at:
       https://metrics-openshift-infra.10.34.250.70.nip.io

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
```

##### Expected Result
Ideally implement `--listen` flag, but at least that: All runs on `192.168.42.42` not `10.34.250.70`.

Btw. it also fails if I run it offline:
```
FAIL
   Error: cannot access master readiness URL https://192.168.42.42:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0314 10:01:11.031535    3402 horizontal.go:132] Starting HPA Controller
     I0314 10:01:11.032118    3402 daemoncontroller.go:196] Starting Daemon Sets controller manager
     I0314 10:01:11.032182    3402 disruption.go:274] Starting disruption controller
     I0314 10:01:11.032186    3402 disruption.go:276] Sending events to api server.
     I0314 10:01:11.057489    3402 docker_manager.go:262] Setting dockerRoot to /var/lib/docker
     I0314 10:01:11.058120    3402 docker_manager.go:265] Setting cgroupDriver to cgroupfs
     I0314 10:01:11.072978    3402 server.go:770] Started kubelet v1.5.2+43a9be4
     I0314 10:01:11.073107    3402 server.go:123] Starting to listen on 0.0.0.0:10250
     F0314 10:01:11.084720    3402 node.go:463] error: Could not initialize Kubernetes Proxy: failed to select a host interface: Unable to select an IP.
      When running in a container, you must run the container in the host network namespace with --net=host and with --privileged
```

**Comment by csrwng** [comment]
@tnozicka - can you please try the oc binary from this pr? https://github.com/openshift/origin/pull/13112

Are you running on Linux?

**Comment by tnozicka** [comment]
@csrwng I am running Arch Linux. (I'll try that PR.)

**Comment by tnozicka** [comment]
I've tried with current master (626c61c) and it's working now. Well, it's working as it used to.

I still think that listenIP and public-hostname should be 2 separate flags. If you are running behind NAT those 2 will always differ and how do you specify which interface it should bound to in case there are more than one which is very common (e.g. in OpenStack). Also in case of NAT (like in OpenStack) your public IP is not on any interface - this effectively means that you can't choose an interface at all. For me this ended up with `oc cluster up` binding to management interface instead of the public facing one - meaning it couldn't get any traffic.

But if you don't want to implement those feel free to close this ticket.

**Comment by jorgemoralespou** [comment]
+1
@csrwng I think we've discussed this many times before, and although you did convince me last time we talked, I see now you were still wrong. I second @tnozicka

**Comment by csrwng** [comment]
@tnozicka @jorgemoralespou I don't disagree with you, it would give you more control to specify them independently. It also means another flag ...  @smarterclayton ?

**Comment by smarterclayton** [comment]
If we make the flag behave like openshift start, and be exactly equivalent, I'm provisionally ok with it

**Comment by jorgemoralespou** [comment]
@smarterclayton I think that I'm provisionally dancing the "dance of the
rain", until you revoke your provisionally agreement.
@csrwng please don't give time Clayton to think. 🤔

El 5 jun. 2017 21:40, "Clayton Coleman" <notifications@github.com> escribió:

If we make the flag behave like openshift start, and be exactly equivalent,
I'm provisionally ok with it

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/13383#issuecomment-306282153>,
or mute the thread

**Comment by csrwng** [comment]
Converting this into a trello card, since it's an enhancement request
https://trello.com/c/eZIzgqXx/1254-cluster-up-allow-specifying-public-host-and-master-ip-separately
