### ISSUE TITLE
No package matching 'origin-docker-excluder' found available

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#13386]
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/249/consoleFull#-14246886155849c75fe4b0052e114d805c:

```
12:39:12 TASK [openshift_excluder : Install docker excluder] ****************************
12:39:13 
fatal: [localhost]: FAILED! => {
12:39:13     "changed": false, 
12:39:13     "failed": true, 
12:39:13     "rc": 126, 
12:39:13     "results": [
12:39:13         "No package matching 'origin-docker-excluder' found available, installed or updated"
12:39:13     ]
12:39:13 }
12:39:13 
12:39:13 MSG:
12:39:13 
12:39:13 No package matching 'origin-docker-excluder' found available, installed or updated
12:39:13 
12:39:13 PLAY RECAP *********************************************************************
12:39:13  [WARNING]: Could not create retry file '/usr/share/ansible/openshift-
12:39:13 ansible/playbooks/byo/config.retry'.         [Errno 13] Permission denied:
12:39:13 u'/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry'
12:39:13 localhost                  : ok=122  changed=8    unreachable=0    failed=1   
12:39:13 
12:39:13 ++ export status=FAILURE
12:39:13 ++ status=FAILURE
12:39:13 + set +o xtrace
```

**Comment by stevekuznetsov** [comment]
Fixed in https://github.com/openshift/openshift-ansible/pull/3658

**Comment by dmage** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/379/consoleFull#-14246886155849c75fe4b0052e114d805c

**Comment by stevekuznetsov** [comment]
@sdodson @ingvagabund https://github.com/openshift/openshift-ansible/pull/3694 introduced this regression _again_

**Comment by mfojtik** [comment]
Seen in https://github.com/openshift/origin/issues/13386

**Comment by sdodson** [comment]
@mfojtik I'm pretty sure that job was started before the fix was merged. Lets see what the new tests say.

**Comment by stevekuznetsov** [comment]
@mfojtik that job synced Origin to 75c6750bf108066564938beab4090e3d5271cd56 which was before Scott's merge
