### ISSUE TITLE
config - validation

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#1338]
need validation for master and node config files.  This includes:

 - [x] fields filled in
 - [x] certs provided for tls connections
 - [ ] certs signed by correct CA
 - [x] agreement on addresses
 - [ ] client connections pointing to started servers
 - [x] fields have correct format

**Comment by liggitt** [comment]
required fields, certs provided, address agreement, and field format is done

signed certs and server connection checks probably go beyond what we want to validate (should you have to be online to validate the config? seems like you shouldn't)

**Comment by liggitt** [comment]
closing as the initial validation pass is complete
