### ISSUE TITLE
Docker 1.12 requires go version 1.7.5 while origin documentation points to 1.6

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [openshift/origin#13384]
[provide a description of the issue]
The documentation in contributing.md says we can use 1.6 for development where as for docker 1.1.2, the requirements clearly ask to upgrade 1.7.5. Also, there are some default libraries like context in go 1.7 which are not by default in 1.6.

> Installing Go. Currently, OpenShift supports building using Go 1.6.x. Do NOT use $HOME/go for Go installation, save that for the Go workspace below.

So, the documentation in origin contributing.md has to be updated to use golang 1.7.

**Comment by mfojtik** [comment]
That is correct, I believe we require go 1.7 for the master now.
