### ISSUE TITLE
Make oc login works against github/google identity  provider

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#13395]
Currently, oc login only works with htpassword/ldap ... identity provider which user can input user/pass to login successful, for the OAuth based identity provider, use should open the openshift webconsole to login and get the token the login with token using oc, it will be better, if user run "oc login"(when use github/google) then the client will open the webconsole automatically to let use login using their github/google account, after that, oc should receive the user info, add finish the login on the oc client side

**Comment by guangxuli** [comment]
That's looks like reasonable and convenient when use openshift for a public container cluster.

**Comment by wanghaoran1988** [comment]
Seems we have [card](https://trello.com/c/aZwg6o8g/769-security-launch-web-browser-from-cli-when-oauth-flow-cannot-be-completed-with-challenges) for this

**Comment by pweil-** [comment]
closing in favor of trello, thanks for adding the reference!

**Comment by lkhomenk** [comment]
"Card not found." any updates on this?

**Comment by schabrolles** [comment]
any update ?
