### ISSUE TITLE
Invalid flag handling message needs work

### ISSUE THREAD

**Issue by bparees** [openshift/origin#134]
When specifying an invalid flag on the openshift cli, there are two problems:
1) it reports all flags as invalid, not just the invalid flag
2) for each invalid flag, it refers the user to the help. it should only do this once, at the end.
3) it reports an unknown flag, then gives usage, then reports a bunch of invalid flags.

here's an example (only "ectdBADDir" is an invalid flag):
[bparees@bparees ~/git/gocode/src/github.com/openshift/origin/examples/simple-ruby-app (deploy)]$ DOCKER_REGISTRY=localhost:5000 openshift start --listenAddr="0.0.0.0:8080" --volumeDir=`mktemp -d` --etcdBADDir=`mktemp -d`
unknown flag: --listenAddr

Usage: 
  openshift [flags]
  openshift [command]

Available Commands: 
  start                     Launch in all-in-one mode
  kube                      The Kubernetes command line client
  version                   Display version
  help [command]            Help about any command

 Available Flags:
      --help=false: help for openshift

Use "openshift help [command]" for more information about that command.
Error: unknown flag: --listenAddr
Usage of openshift:
      --help=false: help for openshift
unknown flag: --volumeDir
Usage of openshift:
      --help=false: help for openshift
unknown flag: --etcdBADDir
Usage of openshift:
      --help=false: help for openshift

**Comment by smarterclayton** [comment]
Where are we on this?

**Comment by fabianofranz** [comment]
@smarterclayton Fixed, the issue can be closed.

**Comment by bparees** [comment]
Still broken, though not as bad:
 openshift start --listen=http://0.0.0.0:8080 --volumeDir=mktemp -d --etcdBADDir=mktemp -d
unknown flag: --listen
<usage printed>


"--listen" is not a bad flag, but it's being reported as such.  etcBADDir is a bad flag and is not reported as such.

**Comment by fabianofranz** [comment]
Ok, I didn't notice that scenario before. Working on a fix.

----- Original Message -----

**Comment by bparees** [comment]
@deads2k this is the issue i was thinking of, guess it was in fact still in progress, sounds like you're fixing it so thanks! :)

**Comment by deads2k** [comment]
@bparees see https://github.com/openshift/origin/pull/1257

**Comment by soltysh** [comment]
@bparees can we close this?

**Comment by bparees** [comment]
yeah looks like it's working right now...thanks @fabianofranz and @deads2k
