### ISSUE TITLE
"The HAProxy router should override the route host with a custom value" fails with "timed out waiting for the condition"

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#13403]
```
20:54:19   The HAProxy router
20:54:19   /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:142
20:54:19     should override the route host with a custom value [It]
20:54:19     /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:141
20:54:19 
20:54:19     Expected error:
20:54:19         <*errors.errorString | 0xc820430cd0>: {
20:54:19             s: "timed out waiting for the condition",
20:54:19         }
20:54:19         timed out waiting for the condition
20:54:19     not to have occurred
20:54:19 
20:54:19     /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:115
```
<details>
<summary>Excerpt from log</summary>
<pre>
20:50:51 [Conformance][networking][router] openshift routers The HAProxy router 
20:50:51   should override the route host with a custom value
20:50:51   /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:141
20:50:51 [BeforeEach] [Top Level]
20:50:51   /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/test.go:47
20:50:51 [BeforeEach] [Conformance][networking][router] openshift routers
20:50:51   /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:141
20:50:51 STEP: Creating a kubernetes client
20:50:51 Mar 14 15:50:51.298: INFO: >>> kubeConfig: /tmp/openshift/test-extended/networking/multitenant/openshift.local.config/master/admin.kubeconfig
20:50:51 
20:50:51 STEP: Building a namespace api object
20:50:51 Mar 14 15:50:51.329: INFO: configPath is now "/tmp/extended-test-scoped-router-zv6wb-xmbw2-user.kubeconfig"
20:50:51 Mar 14 15:50:51.329: INFO: The user is now "extended-test-scoped-router-zv6wb-xmbw2-user"
20:50:51 Mar 14 15:50:51.329: INFO: Creating project "extended-test-scoped-router-zv6wb-xmbw2"
20:50:51 STEP: Waiting for a default service account to be provisioned in namespace
20:50:51 [BeforeEach] [Conformance][networking][router] openshift routers
20:50:51   /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:35
20:50:51 Mar 14 15:50:51.517: INFO: Running 'oc adm --config=/tmp/openshift/test-extended/networking/multitenant/openshift.local.config/master/admin.kubeconfig --namespace=extended-test-scoped-router-zv6wb-xmbw2 policy add-cluster-role-to-user system:router extended-test-scoped-router-zv6wb-xmbw2-user'
20:50:51 cluster role "system:router" added: "extended-test-scoped-router-zv6wb-xmbw2-user"
20:50:51 Mar 14 15:50:51.802: INFO: Running 'oc create --config=/tmp/extended-test-scoped-router-zv6wb-xmbw2-user.kubeconfig --namespace=extended-test-scoped-router-zv6wb-xmbw2 -f /data/src/github.com/openshift/origin/test/extended/testdata/scoped-router.yaml'
20:50:52 pod "scoped-router" created
20:50:52 pod "router-override" created
20:50:52 rolebinding "system-router" created
20:50:52 route "route-1" created
20:50:52 route "route-2" created
20:50:52 service "endpoints" created
20:50:52 pod "endpoint-1" created
20:50:52 [It] should override the route host with a custom value
20:50:52   /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:141
20:50:52 Mar 14 15:50:52.123: INFO: Creating new exec pod
20:50:54 STEP: creating a scoped router from a config file "/data/src/github.com/openshift/origin/test/extended/testdata/scoped-router.yaml"
20:53:54 Mar 14 15:53:54.180: INFO: Scoped Router test [Conformance][networking][router] openshift routers The HAProxy router should override the route host with a custom value logs:
20:53:54  
20:53:54 [AfterEach] [Conformance][networking][router] openshift routers
20:53:54   /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:142
20:53:54 STEP: Collecting events from namespace "extended-test-scoped-router-zv6wb-xmbw2".
20:53:54 STEP: Found 12 events.
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:50:52.028815203 -0400 EDT - event for scoped-router: {default-scheduler } Scheduled: Successfully assigned scoped-router to nettest-node-2
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:50:52.045410275 -0400 EDT - event for router-override: {default-scheduler } Scheduled: Successfully assigned router-override to nettest-node-1
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:50:52.116704664 -0400 EDT - event for endpoint-1: {default-scheduler } Scheduled: Successfully assigned endpoint-1 to nettest-node-2
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:50:52.159927394 -0400 EDT - event for execpod: {default-scheduler } Scheduled: Successfully assigned execpod to nettest-node-1
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:50:52.806040075 -0400 EDT - event for execpod: {kubelet nettest-node-1} Pulled: Container image "gcr.io/google_containers/hostexec:1.2" already present on machine
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:50:52.8999792 -0400 EDT - event for execpod: {kubelet nettest-node-1} Created: Created container with docker id 2370922356c8; Security:[seccomp=unconfined]
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:50:53.080227971 -0400 EDT - event for execpod: {kubelet nettest-node-1} Started: Started container with docker id 2370922356c8
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:50:53.18829905 -0400 EDT - event for scoped-router: {kubelet nettest-node-2} Pulling: pulling image "openshift/origin-haproxy-router"
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:50:53.203874414 -0400 EDT - event for router-override: {kubelet nettest-node-1} Pulling: pulling image "openshift/origin-haproxy-router"
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:50:53.301225692 -0400 EDT - event for endpoint-1: {kubelet nettest-node-2} Pulling: pulling image "openshift/hello-openshift"
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:53:53.192175261 -0400 EDT - event for scoped-router: {kubelet nettest-node-2} Failed: Failed to pull image "openshift/origin-haproxy-router": net/http: request canceled
20:53:54 Mar 14 15:53:54.183: INFO: At 2017-03-14 15:53:53.192312073 -0400 EDT - event for scoped-router: {kubelet nettest-node-2} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "router" with ErrImagePull: "net/http: request canceled"
20:53:54 
20:53:54 Mar 14 15:53:54.189: INFO: POD              NODE            PHASE    GRACE  CONDITIONS
20:53:54 Mar 14 15:53:54.189: INFO: endpoint-1       nettest-node-2  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT ContainersNotReady containers with unready status: [test]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT  }]
20:53:54 Mar 14 15:53:54.189: INFO: execpod          nettest-node-1  Running  1s     [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:53 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT  }]
20:53:54 Mar 14 15:53:54.189: INFO: router-override  nettest-node-1  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT ContainersNotReady containers with unready status: [router]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT  }]
20:53:54 Mar 14 15:53:54.189: INFO: scoped-router    nettest-node-2  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT ContainersNotReady containers with unready status: [router]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-03-14 15:50:52 -0400 EDT  }]
20:53:54 Mar 14 15:53:54.189: INFO: 
20:53:54 Mar 14 15:53:54.191: INFO: 
20:53:54 Logging node info for node nettest-master-node
20:53:54 Mar 14 15:53:54.193: INFO: Node Info: &TypeMeta{Kind:,APIVersion:,}
20:53:54 Mar 14 15:53:54.193: INFO: 
20:53:54 Logging kubelet events for node nettest-master-node
20:53:54 Mar 14 15:53:54.195: INFO: 
20:53:54 Logging pods the kubelet thinks is on node nettest-master-node
20:53:54 W0314 15:53:54.221260   21726 metrics_grabber.go:73] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
20:53:54 Mar 14 15:53:54.374: INFO: 
20:53:54 Latency metrics for node nettest-master-node
20:53:54 Mar 14 15:53:54.374: INFO: 
20:53:54 Logging node info for node nettest-node-1
20:53:54 Mar 14 15:53:54.376: INFO: Node Info: &TypeMeta{Kind:,APIVersion:,}
20:53:54 Mar 14 15:53:54.376: INFO: 
20:53:54 Logging kubelet events for node nettest-node-1
20:53:54 Mar 14 15:53:54.378: INFO: 
20:53:54 Logging pods the kubelet thinks is on node nettest-node-1
20:53:54 Mar 14 15:53:54.398: INFO: router-override started at 2017-03-14 15:50:52 -0400 EDT (0+1 container statuses recorded)
20:53:54 Mar 14 15:53:54.398: INFO: 	Container router ready: false, restart count 0
20:53:54 Mar 14 15:53:54.398: INFO: execpod started at 2017-03-14 15:50:52 -0400 EDT (0+1 container statuses recorded)
20:53:54 Mar 14 15:53:54.398: INFO: 	Container hostexec ready: true, restart count 0
20:53:54 W0314 15:53:54.400451   21726 metrics_grabber.go:73] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
20:53:54 Mar 14 15:53:54.562: INFO: 
20:53:54 Latency metrics for node nettest-node-1
20:53:54 Mar 14 15:53:54.562: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:2m5.441006s}
20:53:54 Mar 14 15:53:54.562: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:47.371058s}
20:53:54 Mar 14 15:53:54.562: INFO: {Operation:stop_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:30.073948s}
20:53:54 Mar 14 15:53:54.562: INFO: 
20:53:54 Logging node info for node nettest-node-2
20:53:54 Mar 14 15:53:54.565: INFO: Node Info: &TypeMeta{Kind:,APIVersion:,}
20:53:54 Mar 14 15:53:54.565: INFO: 
20:53:54 Logging kubelet events for node nettest-node-2
20:53:54 Mar 14 15:53:54.567: INFO: 
20:53:54 Logging pods the kubelet thinks is on node nettest-node-2
20:53:54 Mar 14 15:53:54.575: INFO: scoped-router started at 2017-03-14 15:50:52 -0400 EDT (0+1 container statuses recorded)
20:53:54 Mar 14 15:53:54.575: INFO: 	Container router ready: false, restart count 0
20:53:54 Mar 14 15:53:54.575: INFO: endpoint-1 started at 2017-03-14 15:50:52 -0400 EDT (0+1 container statuses recorded)
20:53:54 Mar 14 15:53:54.575: INFO: 	Container test ready: false, restart count 0
20:53:54 W0314 15:53:54.577783   21726 metrics_grabber.go:73] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
20:53:54 Mar 14 15:53:54.769: INFO: 
20:53:54 Latency metrics for node nettest-node-2
20:53:54 Mar 14 15:53:54.769: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:47.309522s}
20:53:54 Mar 14 15:53:54.769: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:17.288121s}
20:53:54 STEP: Dumping a list of prepulled images on each node
20:53:54 Mar 14 15:53:54.771: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
20:53:54 STEP: Destroying namespace "extended-test-scoped-router-zv6wb-xmbw2" for this suite.
20:54:19 Mar 14 15:54:19.890: INFO: namespace: extended-test-scoped-router-zv6wb-xmbw2, resource: bindings, ignored listing per whitelist
20:54:19 
20:54:19 
* Failure [208.610 seconds]
20:54:19 [Conformance][networking][router] openshift routers
20:54:19 /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:143
20:54:19   The HAProxy router
20:54:19   /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:142
20:54:19     should override the route host with a custom value [It]
20:54:19     /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:141
20:54:19 
20:54:19     Expected error:
20:54:19         <*errors.errorString | 0xc820430cd0>: {
20:54:19             s: "timed out waiting for the condition",
20:54:19         }
20:54:19         timed out waiting for the condition
20:54:19     not to have occurred
20:54:19 
20:54:19     /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:115
</pre>
</details>

A full log: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_networking_minimal/294/consoleFull

**Comment by smarterclayton** [comment]
This is the same problem as #13050
