### ISSUE TITLE
Ability to enable/disable features like origin API groups

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13414]
With https://github.com/openshift/origin/pull/12986 merging and given that there are outstanding bugs gaps that might break the stability of Origin, we were discussing what would be the best way to disable/enable features like this in the master.

So by default, the groups will be disabled, but we should able able to enable that feature by specifying a flag when installing OpenShift via Ansible (?) and also have a way to configure the CI to enable the feature when needed.

The question is, what mechanism we can use to do this? A master config option? An `openshift start` flag? Environment variable? Is there anything in Kube we can use?

@smarterclayton @deads2k @liggitt @soltysh @ncdc FYI

**Comment by ncdc** [comment]
Bumping priority given we have to figure this out before the next online push.

It definitely should not be a flag.

Master config option could work.

Environment variables are hacky and "hidden".

Kube has something called feature gates.

**Comment by ncdc** [comment]
But Kube's feature gates, the last time I checked, are hard coded. I'm not sure if we could append to the list.

**Comment by liggitt** [comment]
we have `disabledAPIGroupVersions` in the config

**Comment by smarterclayton** [comment]
Gates would be the preferred path, we either need our own (and reuse code)
or for gates to not be hardcoded.

**Comment by deads2k** [comment]
> Gates would be the preferred path, we either need our own (and reuse code)
> or for gates to not be hardcoded.

How long would we honor the gating flag?  This is really just an intermediate state that we don't expect any normal customer to be running in, right?  Seems like you could hack in an ugly drop patch for the temporary OSE timeframe and we could be running with it on in origin to try to catch the bugs.  No changes to the installer, no changes to CI, no migration for flags or config we have no intention of shipping.

My previous experience in trying to get CI coverage for multiple running modes was basically "don't do that".

**Comment by smarterclayton** [comment]
We're going to have feature flags because we're pushing to origin every 3
weeks - and we will have "not ready" features that have partial exposure in
master.  We'd introduce tests that test both modes.

**Comment by deads2k** [comment]
> We're going to have feature flags because we're pushing to origin every 3
> weeks - and we will have "not ready" features that have partial exposure in
> master.  We'd introduce tests that test both modes.

Are we going to try to preserve the knobs or are we just going to later ignore the flags we create to temporarily disable behavior?

**Comment by smarterclayton** [comment]
On Mar 17, 2017, at 8:12 AM, David Eads <notifications@github.com> wrote:

We're going to have feature flags because we're pushing to origin every 3
weeks - and we will have "not ready" features that have partial exposure in
master. We'd introduce tests that test both modes.

Are we going to try to preserve the knobs or are we just going to later
ignore the flags we create to temporarily disable behavior?


Probably ignore them.  They're tools that have a designated expiration for
specific rollout cases.  They're a descending whistle that shouldn't be an
incoming mortar.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/13414#issuecomment-287338549>,
or mute the thread

**Comment by mfojtik** [comment]
@smarterclayton @ncdc bumping this to P2 (I guess we will need this to enable/disable other features in future, so we should continue discussing what will the best way to do that be...). However, for 3.6 I think the conclusion we made on the arch call was that we will go with API groups enabled, but we do a deep sweep in our admission controllers to find potential problems.

One way suggested by @smarterclayton was to change the legacy client to return API grouped resources to ensure they are properly captured by our admission controllers (make a PR with this change, run tests...).
