### ISSUE TITLE
Switch from legacy client to clientsets and start using new API endpoints

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13422]
Ref: https://github.com/openshift/origin/issues/13412

With API groups merged, we should start switching from the legacy API client (pkg/client) to a generated clientsets and start hitting the new API endpoints.
This will require updating the client sets and we should probably start with this work early after 1.6 lands.

**Comment by kargakis** [comment]
@mfojtik is this fixed now?

**Comment by soltysh** [comment]
Yeah, all the bits are in. 
/close
