### ISSUE TITLE
Flake: The connection to the server <...>:8443 was refused

### ISSUE THREAD

**Issue by tbielawa** [openshift/origin#13425]
From PR https://github.com/openshift/openshift-ansible/pull/3131

> continuous-integration/openshift-jenkins/test FAILURE (https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install/33/) (Base Commit: 612599f)

Seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install/33/testReport/junit/(root)/Additional%20master%20configuration/_localhost__openshift_examples___Import_Centos_Image_streams/)

```
Regression

Additional master configuration.[localhost] openshift_examples : Import Centos Image streams

Failing for the past 1 build (Since Failed#33 )
Took 0.32 sec.
Error Message

Output to stderr: The connection to the server ip-172-18-8-221.ec2.internal:8443 was refused - did you specify the right host or port?
```

**Comment by stevekuznetsov** [comment]
Didn't we hit this a couple times in that PR and never anywhere else? I think it's a failure from the changes....

**Comment by tbielawa** [comment]
@stevekuznetsov after I thought about it for a while and put the failure in context I came to the same conclusion. The PR it failed on was modifying proxy settings, that could easily have lead to a refused connection.

**Comment by soltysh** [comment]
I spoke with @stevekuznetsov about this error, and it doesn't look like its a flake. Especially that this appeared several times, but only in this single PR, so this might be an actual error in the implementation. Having said that, I'm closing this until next occurrence.
