### ISSUE TITLE
Oauth server not handling state when requesting a token directly

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#1342]
This results in the web console not returning to the page you were previously on before being redirected to login.

**Comment by liggitt** [comment]
The osin library is not including state in the hash for the implicit flow

**Comment by liggitt** [comment]
Fixed in https://github.com/RangelReale/osin/pull/32
Will look into updating osin or cherry-picking if the delta is too big

**Comment by liggitt** [comment]
Diff between where we are and `master` isn't that big: https://github.com/RangelReale/osin/compare/1f4e9754a8931fbd9834ab11592f358418efc9ff...master

Most of the changes are changes to examples or a refactor of token expiration checking
