### ISSUE TITLE
Normalize policy using `oadm migrate`

### ISSUE THREAD

**Issue by enj** [openshift/origin#13429]
xref: #13334

**Comment by deads2k** [comment]
This isn't just debt/cleanliness.  We have to perform this migration to support switching to RBAC in version 1.6+(one shot upgrade distance).

**Comment by enj** [comment]
Spoke with @deads2k - we do not need this anymore since we will go to RBAC in 3.7+.

**Comment by deads2k** [comment]
> Spoke with @deads2k - we do not need this anymore since we will go to RBAC in 3.7+

I forgot that we don't do this on the conversion step since it wouldn't round-trip. We do still need this.  Probably could just write a one release controller or poststart hook.  I don't see a reason to let users manage the rollout.
