### ISSUE TITLE
[Router] Namespace sync not guaranteed to run before route sync

### ISSUE THREAD

**Issue by marun** [openshift/origin#13437]
Namespace sync is intended to occur before route sync since a route's namespace will be checked at admission against a list of acceptable namespaces.  If a new namespace is added but namespace sync not not yet occurred, any route in that namespace would not be admitted to the router.  The router currently defines the namespace sync interval as the router sync interval less 10s, but that isn't enough to guarantee execution order due to the use of 'sliding' timers.    

The interval of a sliding timer does not include the execution time of the sync function.  It is therefore possible for the sync time to skew across the different resource watchers and the namespace loop as their respective execution time accumulates variation due to resource contention and network latency.

Note that this isn't a hard-failure condition.  The likely symptom is exposure of a route might be take 2 sync intervals instead of 1.  I'm reporting the problem in here in case the described behavior is seen in a production environment.

**Comment by pravisankar** [comment]
We have changed the router to do watch on namespaces instead of periodic sync (pr: https://github.com/openshift/origin/pull/16039), so this issue does not exist anymore.
