### ISSUE TITLE
`rulevalidation.Covers` should not use `authorizationapi.NormalizeResources`

### ISSUE THREAD

**Issue by enj** [openshift/origin#13430]
xref: #13334

**Comment by deads2k** [comment]
This will break old, non-migrated rules which rely on coverage from different roles.  I think I'm ok doing this in 1.6 since the common case of coverage based on the same rule or based on "*" will still work.

@liggitt arguments against?

**Comment by enj** [comment]
@deads2k do we still need this?

**Comment by deads2k** [comment]
> @deads2k do we still need this?

If we switch in 3.7, no.

**Comment by tiran** [comment]
@deads2k @enj Is this ticket still relevant? We switched to RBAC in 3.7.

``rulevalidation.Covers`` is used in ``pgk/diagnostics/cluster`` and ``pkg/oc/admin/policy``. It calls ``authorizationapi.NormalizeResources`` in ``breakdownRuleForGroup``.

**Comment by deads2k** [comment]
unnecessary post-switch.

**Comment by enj** [comment]
> unnecessary post-switch. 

@deads2k I do not think it is that simple, see #15911
