### ISSUE TITLE
oc adm registry broken for older servers

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#13447]
Running an older (non-master) server (as with 'cluster up'), creating the registry fails because the `oc adm registry` command tries to use the new api groups. 

Running with `--loglevel=8`, you can see it's trying to post to the new api groups:

`POST https://127.0.0.1:8443/apis/authorization.openshift.io/v1/clusterrolebindings`
`POST https://127.0.0.1:8443/apis/apps.openshift.io/v1/namespaces/default/deploymentconfigs`

**Comment by smarterclayton** [comment]
All generators should default to the old types - this may be related to my problem this morning as well

**Comment by mfojtik** [comment]
@csrwng @smarterclayton @sttts I think this is because of cached discovery. Can you try to remove ~/.kube cache and try again? (my theory is that you cached the discovery from "new" server and then try to run with that cache against "old" server).

**Comment by soltysh** [comment]
This is definitely caused by the cache being out of date. I've hit the same problem when stress testing the new deployments endpoint. The cache was built with apps/v1beta1.Deployments on (the k8s one) and then I disabled just them and retry kubectl operation and it obviously failed due to not having that resource. Wouldn't it make sense to refresh cache (entire or partial) in those cases? @liggitt @deads2k ?

**Comment by mfojtik** [comment]
@csrwng would it make sense for `oc cluster up` to always invalidate the discovery cache? if users can start the cluster using arbitrary image version, it might cause a lot of troubles in future...
Also worth mention that the discovery cache should have 10 min TTL and then it is refreshed, which makes me wonder if it is worth fixing anyway ;-)

**Comment by sttts** [comment]
Copy&pasting our irc chat here:

<maszulik>	sttts: wouldn't it be reasonable if we're getting 404 after reaching an endpoint from cache to do a double check?
<maszulik>	sttts: I mean the cache says apps/v1beta1/deployments is there, but I've turned them off explicitly, when kubectl gets 404 it could refresh the cache or at least part of it
<sttts>	maszulik: yes, probably. we do the opposite already: if you do "kubectl get bla", it invalidates the cache
<sttts>	maszulik: but it's all in the rest mapper. what we have now is an error long after the rest mapper. wiring cache invalidation will be tricky

**Comment by deads2k** [comment]
Just to make sure I'm following along here.  
 1. run 1.6 openshift at host1:port1
 1. run oc against it
 1. stop 1.6 openshift and start a 1.5 openshift *on the exact same host1:port1*
 1. run oc against it -- fail.

Is that a use-case we're particularly concerned with?  It seems like the chances of an end user seeing this happen are vanishingly small.  If we think its only a problem with cluster-up, it seems like cluster-up could simply clear the cache for you when it starts the server, since it knows the host:port.

**Comment by csrwng** [comment]
@mfojtik @deads2k @sttts It doesn't look like it's the cache. I made sure I deleted my .kube directory. Same error.

**Comment by mfojtik** [comment]
@csrwng hrm. there is no way the oc will figure out that endpoint or have it hardcoded afaik.

**Comment by csrwng** [comment]
@mfojtik here's logging from clearing the .kube directory, logging in, and then trying `oc adm registry`:
https://gist.github.com/csrwng/92f751756bc5f81a0a87b6e93cf77e98

**Comment by mfojtik** [comment]
Seems like it is sending the new API type:

I0320 09:24:34.891261   24048 request.go:559] Request Body:
"{\"kind\":\"DeploymentConfig\",\"apiVersion\":\"apps.openshift.io/v1\",\"metadata\":{\"name\":\"docker-registry\",\"creationTimestamp\":null,\"labels\":{\"docker-registry\":\"default\"}},\"spec\":{\"strategy\":{\"resources\":{}},\"triggers\":[{\"type\":\"ConfigChange\"}],\"replicas\":1,\"test\":false,\"selector\":{\"docker-registry\":\"default\"},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"docker-registry\":\"default\"}},\"spec\":{\"volumes\":[{\"name\":\"registry-storage\",\"emptyDir\":{}}],\"containers\":[{\"name\":\"registry\",\"image\":\"openshift/origin-docker-registry:v1.5.0-alpha.3\",\"ports\":[{\"containerPort\":5000}],\"env\":[{\"name\":\"REGISTRY_HTTP_ADDR\",\"value\":\":5000\"},{\"name\":\"REGISTRY_HTTP_NET\",\"value\":\"tcp\"},{\"name\":\"REGISTRY_HTTP_SECRET\",\"value\":\"jaRzQL/zIPUbYdRv7Dy3RNHO69X0DIvrjeRSVAH4wNs=\"},{\"name\":\"REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ENFORCEQUOTA\",\"value\":\"false\"}],\"resources\":{\"requests\":{\"cpu\":\"100m\",\"memory\":\"256Mi\"}},\"volumeMounts\":[{\"name\":\"registry-storage\",\"mountPath\":\"/registry\"}],\"livenessProbe\":{\"httpGet\":{\"path\":\"/healthz\",\"port\":5000},\"initialDelaySeconds\":10,\"timeoutSeconds\":5},\"readinessProbe\":{\"httpGet\":{\"path\":\"/healthz\",\"port\":5000},\"timeoutSeconds\":5},\"securityContext\":{\"privileged\":false}}],\"serviceAccountName\":\"registry\",\"serviceAccount\":\"registry\"}}},\"status\":{\"latestVersion\":0,\"observedGeneration\":0,\"replicas\":0,\"updatedReplicas\":0,\"availableReplicas\":0,\"unavailableReplicas\":0}}\n"

It should use the legacy one. Indeed a bug somewhere in the generator code.


-----Original Message-----

**Comment by smarterclayton** [comment]
This is a blocker for me to cut 3.6.0-alpha.0 - how hard to fix?

On Mar 20, 2017, at 9:36 AM, Michal Fojtik <notifications@github.com> wrote:

Seems like it is sending the new API type:

I0320 09:24:34.891261   24048 request.go:559] Request Body:
"{\"kind\":\"DeploymentConfig\",\"apiVersion\":\"apps.openshift.io/v1\
",\"metadata\":{\"name\":\"docker-registry\",\"creationTimestamp\":null,\"labels\":{\"docker-registry\":\"default\"}},\"spec\":{\"strategy\":{\"resources\":{}},\"triggers\":[{\"type\":\"ConfigChange\"}],\"replicas\":1,\"test\":false,\"selector\":{\"docker-registry\":\"default\"},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"docker-registry\":\"default\"}},\"spec\":{\"volumes\":[{\"name\":\"registry-storage\",\"emptyDir\":{}}],\"containers\":[{\"name\":\"registry\",\"image\":\"openshift/origin-docker-registry:v1.5.0-alpha.3\",\"ports\":[{\"containerPort\":5000}],\"env\":[{\"name\":\"REGISTRY_HTTP_ADDR\",\"value\":\":5000\"},{\"name\":\"REGISTRY_HTTP_NET\",\"value\":\"tcp\"},{\"name\":\"REGISTRY_HTTP_SECRET\",\"value\":\"jaRzQL/zIPUbYdRv7Dy3RNHO69X0DIvrjeRSVAH4wNs=\"},{\"name\":\"REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ENFORCEQUOTA\",\"value\":\"false\"}],\"resources\":{\"requests\":{\"cpu\":\"100m\",\"memory\":\"256Mi\"}},\"volumeMounts\":[{\"name\":\"registry-storage\",\"mountPath\":\"/registry\"}],\"livenessProbe\":{\"httpGet\":{\"path\":\"/healthz\",\"port\":5000},\"initialDelaySeconds\":10,\"timeoutSeconds\":5},\"readinessProbe\":{\"httpGet\":{\"path\":\"/healthz\",\"port\":5000},\"timeoutSeconds\":5},\"securityContext\":{\"privileged\":false}}],\"serviceAccountName\":\"registry\",\"serviceAccount\":\"registry\"}}},\"status\":{\"latestVersion\":0,\"observedGeneration\":0,\"replicas\":0,\"updatedReplicas\":0,\"availableReplicas\":0,\"unavailableReplicas\":0}}\n"

It should use the legacy one. Indeed a bug somewhere in the generator code.


-----Original Message-----
