### ISSUE TITLE
Report certificate expirations times via Prometheus metrics for nodes, masters, and routers

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13449]
We can also report the client certificates.  We can do it in Kube but I'd like it to be in Origin for 1.6

@liggitt

**Comment by php-coder** [comment]
This playbook generates similar report for all certs: https://github.com/openshift/openshift-ansible/blob/master/playbooks/certificate_expiry/easy-mode.yaml It could be helpful to find out certs locations.
