### ISSUE TITLE
Nginx setgid(107) error

### ISSUE THREAD

**Issue by Dec-** [openshift/origin#13443]
Hi,

i downloaded Openshift 1.5 and did  cluster up command. Everything works fine but when trying to run Docker image Nginx im getting error: 
2017/03/19 09:01:56 [emerg] 7#7: setgid(107) failed (1: Operation not permitted)
2017/03/19 09:01:56 [alert] 1#1: worker process 7 exited with fatal code 2 and cannot be respawned

Can some1 help me with problem? Thx :)

**Comment by smarterclayton** [comment]
The default openshift security policy blocks containers from performing setuid and setgid operations.  You'll need to grant that to your project - see: https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root

**Comment by samanamp** [comment]
> The default openshift security policy blocks containers from performing setuid and setgid operations. You'll need to grant that to your project - see: https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root

updating the link in case someone sees this thread and has the same issue: https://docs.openshift.com/container-platform/3.6/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root
