### ISSUE TITLE
inconsistent output between oc and web interface

### ISSUE THREAD

**Issue by jduncan-rva** [openshift/origin#13440]
I'm using origin 1.4 from a minishift setup with the CentOS image. All functioning and up and running. It is in a kvm VM on Fedora 25.

The list of projects between the web interface and oc are pretty drastically different. 

logged into the web UI and oc as system:admin

1) in the web interface you cannot see the default, openshift, openshift-infra, etc. projects. However they are visible to oc.
2) If you create a project in the web interface you can see it in oc
3) If you create a project in oc, you cannot see it in the web interface

I would assume that the project listings would be consistent in the web interface and with oc.

##### Version
OpenShift Master:
v1.4.1+3f9807a
Kubernetes Master:
v1.4.0+776c994

I've confirmed the same functionality with oc v1.4.1+3f9807a and oc v1.3.1

##### Steps To Reproduce
1. set up minishift with a CentOS image
2. log in as system:admin in the gui and with oc
3. create a project in the gui
4. create a project with oc
5. compare the lists

##### Current Result

1) in the web interface you cannot see the default, openshift, openshift-infra, etc. projects. However they are visible to oc.
2) If you create a project in the web interface you can see it in oc
3) If you create a project in oc, you cannot see it in the web interface

##### Expected Result

The project listings should be consistent using both methods.

**Comment by stevekuznetsov** [comment]
Sounds like you're logged in as a user with administrative rights with `oc` and some other user in the web console. From the Origin side of things, everything is working as intended. You should open an issue against the Minishift repository.

**Comment by jduncan-rva** [comment]
I am using the same credentials with the web ui and oc.

**Comment by stevekuznetsov** [comment]
If you log in using the token in the web console (top right corner on the overview page, click the question mark) what do you see when you do:

```
oc get projects
oc whoami
```

**Comment by jduncan-rva** [comment]
it's configured with an AllowAll identity provider.

**Comment by stevekuznetsov** [comment]
Right, I'm fairly sure `system:admin` can only log in with certificate authentication, so I am assuming you logged in as a different user -- that's what logging in with the token from the console and using `oc whoami` would help look into. You could also `oc get users` as the cluster admin and see if there are other users provisioned -- one would have been made when you logged in before. 

You can always create a new user to log into the web console with, and grant them admin rights.

/cc @enj for login confirmation and @jwforres for the normal way to log into a cluster admin user on the web console

**Comment by jduncan-rva** [comment]
I really am logged in as system:admin.

jduncan@dhcp-192-168-1-140 ~$ oc whoami
system:admin
jduncan@dhcp-192-168-1-140 ~$ oc get users
NAME        UID                                    FULL NAME   IDENTITIES
developer   4824a2d6-0c16-11e7-9722-525400fa954e               anypassword:developer
system      683ee3e1-0c18-11e7-9722-525400fa954e               anypassword:system

I'm guessing the anypassword authconfig, and the fact that the system user doesn't have a cluster-admin or admin role is what is causing the weirdness.

**Comment by stevekuznetsov** [comment]
So, to be clear... you see a different list of projects when you:

 1. log into the web console, grab the token login from the overview page, log into `oc` using that token
 2. log into the web console and view the list of projects

**Comment by jduncan-rva** [comment]
No. that works. 

To make sure I understand what is happening here, logging into oc with the same user/pass combination is allowing the unexpected behavior because the authconfig is set to an AllowAll policy?

**Comment by stevekuznetsov** [comment]
No. I do not believe it is correct to attempt a login to the web console as `system:admin`. The `oc login -u system:admin` should not use a password, but credentials from the `admin.kubeconfig`. I'm not certain how you would go about logging in as `system:admin` in the web console, hopefully Jessica can clear that up. In the meanwhile, if you need an administrative view into the web console, just add a user to log in as and bind the administrative roles to them.

**Comment by enj** [comment]
`system:admin` is a certificate based identity - it is not stored in `etcd` and will not show up in a call to `oc get users`.  Both the `developer` and `system` users from your logs are standard `anypassword` users with no special permissions.  It is not possible to authenticate as `system:admin` via the `anypassword` IDP.  You may be able to send the certificate via the browser.  It would be easier to simply add whatever roles you needed to one of the `anypassword` users using `oc`.

**Comment by jduncan-rva** [comment]
Thanks for the education. I'll close this out as it is acting correctly, if not intuitively.
