### ISSUE TITLE
find: paths must precede expression: 2

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13453]
I started to get this on my centos7 dev box:

```console
[@dev] .../openshift/origin # ./hack/test-integration.sh TestPullThroughInsecure
find: warning: the -d option is deprecated; please use -depth instead, because the latter is a POSIX-compliant feature.
find: paths must precede expression: 2
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
++ Building go targets for linux/amd64: test/integration/integration.test
```

Dunno what changed in the scripts, but it seems like the offending bit is:

```
++ find /tmp/openshift/test-integration -d 2
```

**Comment by stevekuznetsov** [comment]
Looks like `tmpdir` cleanup code added by @smarterclayton recently

**Comment by smarterclayton** [comment]
@mfojtik can you try out -depth

**Comment by stevekuznetsov** [comment]
@smarterclayton on GNU `find` it looks like `-depth` means to do a DFS.

**Comment by danwinship** [comment]
`find "${BASETMPDIR}" -mindepth 2 -maxdepth 2 -type d` works on linux and according to https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/find.1.html should work on OS X too.

Though this would also be a good time to reconsider whether running "rm -rf" as root on the unvalidated output of a command is a good idea.

**Comment by stevekuznetsov** [comment]
> Though this would also be a good time to reconsider whether running "rm -rf" as root on the unvalidated output of a command is a good idea.

Do we have any other choice when we are cleaning up test artifacts that were created as root?

**Comment by danwinship** [comment]
I'm not sure what the set of things we're cleaning up is. Is it possible to specify the directories more explicitly? Or else to just delete and recreate all of ${BASETMPDIR} rather than trying to pick out only parts of it?

(eg, see https://bugzilla.redhat.com/show_bug.cgi?id=1202858 for a concrete example of a root "rm -rf" accidentally turning into "rm -rf /".)

**Comment by stevekuznetsov** [comment]
The specific error they encountered was 

```sh
rm -rf "${SOME_VAR}"/*
```

When this is run _without_ `set -o nounset` this will remove root. Not only do we enforce `set -o nounset` in all cases but this case does not look that way and if it did we would also make edits to it as I did in https://github.com/openshift/origin/commit/0c804382069f5592727a853015729d34a9f5bf8c

You make a good point but I think in this case we are guarding against it effectively and on purpose :)

**Comment by Miciah** [comment]
`rm -rf "${SOME_VAR}"/*` does not error if `SOME_VAR` is set but empty.

**Comment by stevekuznetsov** [comment]
Ah right well in any case as before in the `test-go` example when we have such situations the `"${var:?}"` syntax is used as described in the BZ.

The logic under question here does:

```sh
for directory in $( find "${BASETMPDIR}" -d 2 ); do
    ${USE_SUDO:+sudo} rm -rf "${directory}"
done
```

So if we are using `sudo` and "${directory}" is unset (which I am not certain can happen in the `for` construct anyway...) we would execute 

```sh
sudo rm -rf ''
```

Which does not carry the risk in any case.

**Comment by danwinship** [comment]
Yeah, I agree that there's no obvious way this particular usage could go wrong (assuming that someone doesn't do something like `mkdir -p "${BASETMPDIR}/dirname-ending-in-space /etc"` just to mess it up), but I'm still leery of it on general principle.

**Comment by php-coder** [comment]
I've just seen it here: https://ci.openshift.redhat.com/jenkins/job/fork_ami/385/consoleFull

**Comment by php-coder** [comment]
> @mfojtik can you try out -depth

```console
$ docker run -it centos /bin/bash
[root@c61926b076bc /]# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 
[root@c61926b076bc /]# find /tmp -d 2
find: warning: the -d option is deprecated; please use -depth instead, because the latter is a POSIX-compliant feature.
find: paths must precede expression: 2
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
[root@c61926b076bc /]# find /tmp -depth 2
find: paths must precede expression: 2
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
[root@c61926b076bc /]# find /tmp -mindepth 1 -maxdepth 1
/tmp/.ICE-unix
...
[root@c61926b076bc /]# find --version
find (GNU findutils) 4.5.11
...
```

**Comment by stevekuznetsov** [comment]
We need

```sh
for directory in $( find "${BASETMPDIR}" -mindepth 2 -maxdepth 2 ); do
```
