### ISSUE TITLE
oc describe scc doesn't list allowed seccomp profiles

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#13459]
In the output of `oc describe scc <name>` I don't see any information about allowed seccomp profiles. I feel that it should be here.

##### Steps To Reproduce
1. `oc cluster up`
2. `oc login -u system:admin`
3. `oc describe scc privileged`

##### Current Result
No information about allowed profiles.

##### Expected Result
Information about allowed profiles should be shown.

**Comment by php-coder** [comment]
@pweil- I can fix it if it should be fixed :)

**Comment by pweil-** [comment]
yeah, should be added to the describer
