### ISSUE TITLE
Changes to make podnode admission controller plugin to make it more concise

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [openshift/origin#13460]
Small changes to make the admission controller plugin & code more concise like

- We are anyways denying for all operations other than CREATE, so no need to have UPDATE in handler.
https://github.com/openshift/origin/blob/114908c09cb048d8fbe0cf488d44f937563311d8/pkg/scheduler/admission/podnodeconstraints/admission.go#L50
- We can find the blacklist labels from the config, no need to have field for it in plugin again.
https://github.com/openshift/origin/blob/114908c09cb048d8fbe0cf488d44f937563311d8/pkg/scheduler/admission/podnodeconstraints/admission.go#L61

**Comment by liggitt** [comment]
we only want to allocate the blacklisted labels once, and we need to handle update for resources other than pods
