### ISSUE TITLE
Try It Out v2 Example fails

### ISSUE THREAD

**Issue by chenrygithub** [openshift/origin#13468]
I've just started with OpenShift and have started a cluster using the containerised method. I can log into the web gui remotely and all that seems working OK. 

I do the Try It Out example, oc login, oc new-project, oc oc new-app openshift/deployment-example and curl which all works fine. I go to the 'oc tag deployment-example:v2 deployment-example:latest' bit and get the following error:

`oc tag deployment-example:v2 deployment-example:latest
error: "deployment-example:v2" is not currently pointing to an image, cannot use it as the source of a tag`

##### Version
oc v1.5.0-alpha.3+87ca44f-314
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.0.158:8443
openshift v1.5.0-alpha.3+87ca44f-314
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. Run through 'Method 1: Running in a container'
2. Go through 'Try It Out Steps 1 to 5
3. Run 'oc tag deployment-example:v2 deployment-example:latest' as instructed.

##### Current Result
Command returns:

`oc tag deployment-example:v2 deployment-example:latest
error: "deployment-example:v2" is not currently pointing to an image, cannot use it as the source of a tag`

##### Expected Result
The curl command should return a document with v2 in it instead of v1 from the previous example.

##### Additional Information
`# oadm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/var/lib/origin/openshift.local.config/master/admin.kubeconfig'
Info:  Using context for cluster-admin access: 'default/192-168-0-158:8443/system:admin'

[Note] Running diagnostic: ConfigContexts[default/192-168-0-158:8443/system:admin]
       Description: Validate client config context is complete and has connectivity
       
Info:  The current client config context is 'default/192-168-0-158:8443/system:admin':
       The server URL is 'https://192.168.0.158:8443'
       The user authentication is 'system:admin/192-168-0-158:8443'
       The current project is 'default'
       Successfully requested project list; has access to project(s):
         [default kube-system openshift openshift-infra test]
       
[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint
       
ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:155]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected
              
       ERROR: [DP1003 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:88]
              Could not authenticate to the master with the service account credentials: Get https://kubernetes.default.svc.cluster.local:443/oapi/v1/users/~: dial tcp: lookup kubernetes.default.svc.cluster.local: no such host
              
       ERROR: [DP1016 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:113]
              DNS resolution for registry address docker-registry.default.svc.cluster.local returned an error; container DNS is likely incorrect. The error was: read udp 172.17.0.2:57007->192.168.0.158:53: read: no route to host
              
       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected
              
       ERROR: [DP2003 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:72]
              The first /etc/resolv.conf nameserver 192.168.0.158
              could not resolve kubernetes.default.svc.cluster.local.
              Error: read udp 172.17.0.2:51461->192.168.0.158:53: read: no route to host
              This nameserver points to the master's SkyDNS which is critical for
              resolving cluster names, e.g. for Services.
              
       WARN:  [DP2014 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:119]
              A request to the nameserver 192.168.0.158 timed out.
              This could be temporary but could also indicate network or DNS problems.
              
       WARN:  [DP2015 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:124]
              Error querying nameserver 192.168.0.158:
                read udp 172.17.0.2:44169->192.168.0.158:53: read: no route to host
              This may indicate a problem with DNS.
              
       [Note] Summary of diagnostics execution (version v1.5.0-alpha.3+cf7e336):
       [Note] Warnings seen: 2
       [Note] Errors seen: 3
       
```
[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint
       
WARN:  [DNet2002 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:81]
       Skipping network diagnostics check. Reason: Not using openshift network plugin.
       
[Note] Skipping diagnostic: AggregatedLogging
       Description: Check aggregated logging integration for proper configuration
       Because: No master config file was provided
       
[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry
       
WARN:  [DClu1002 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:192]
       There is no "docker-registry" service in project "default". This is not strictly required to
       be present; however, it is required for builds, and its absence probably
       indicates an incomplete installation.
       
       Please consult the documentation and use the 'oadm registry' command
       to create a Docker registry.
       
[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects
       
[Note] Running diagnostic: ClusterRoles
       Description: Check that the default ClusterRoles are present and contain the expected permissions
       
[Note] Running diagnostic: ClusterRouterName
       Description: Check there is a working router
       
WARN:  [DClu2001 from diagnostic ClusterRouter@openshift/origin/pkg/diagnostics/cluster/router.go:129]
       There is no "router" DeploymentConfig. The router may have been named
       something different, in which case this warning may be ignored.
       
       A router is not strictly required; however it is needed for accessing
       pods from external networks and its absence likely indicates an incomplete
       installation of the cluster.
       
       Use the 'oadm router' command to create a router.
       
[Note] Running diagnostic: MasterNode
       Description: Check if master is also running node (for Open vSwitch)
       
Info:  Found a node with same IP as master: origin.colinhenry.co.uk

[Note] Skipping diagnostic: MetricsApiProxy
       Description: Check the integrated heapster metrics can be reached via the API proxy
       Because: The heapster service does not exist in the openshift-infra project at this time,
       so it is not available for the Horizontal Pod Autoscaler to use as a source of metrics.
       
[Note] Running diagnostic: NodeDefinitions
       Description: Check node records on master
       
[Note] Skipping diagnostic: ServiceExternalIPs
       Description: Check for existing services with ExternalIPs that are disallowed by master config
       Because: No master config file was detected
       
[Note] Summary of diagnostics execution (version v1.5.0-alpha.3+87ca44f-314):
[Note] Warnings seen: 3
[Note] Errors seen: 1
```

**Comment by debianmaster** [comment]
Assuming that you are in `myproject` name space
This will work,   you need to specify the full docker image name (with namespae)

```sh
oc tag docker.io/openshift/deployment-example:v2 myproject/deployment-example:latest
```

**Comment by soltysh** [comment]
That's correct, or more explicitly use: `oc tag --source=docker openshift/deployment-example:v2 deployment-example:latest`. I've opened https://github.com/openshift/origin/pull/13552 to update the docs.
