### ISSUE TITLE
Aggregated logging (version 1.2) not working

### ISSUE THREAD

**Issue by roshan-mr** [openshift/origin#13480]
Aggregated logging configuration in origin 1.2 is failing

##### Version
openshift v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

##### Steps To Reproduce
1. Followed https://docs.openshift.org/1.2/install_config/aggregate_logging.html

##### Current Result
In the deployer pod logs, i found the following,

===================
Attaching secrets to service accounts
+ oc secrets add serviceaccount/aggregated-logging-elasticsearch logging-elasticsearch
+ oc secrets add serviceaccount/aggregated-logging-fluentd logging-fluentd
+ oc secrets add serviceaccount/aggregated-logging-curator logging-curator
+ '[' -n '' ']'
+ generate_configmaps
+ echo 'Deleting configmaps'
+ oc delete configmap -l logging-infra=support
Deleting configmaps
error: resource name may not be empty
==================

##### Expected Result
All the logging components should be deployed without any issues.

**Comment by jcantrill** [comment]
@roshan-mr I would suggest using origin-1.4 or better.  The 1.4 has undergone many fixes recently to stabilize the release.  Additionally, there are a multitude of fixes targeted for 1.5 and 3.6 which are awaiting to be merged.
Closing  as we are unlikely to fix anything in 1.2.
