### ISSUE TITLE
'osc login' displays no help options

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1348]
```
$ osc help login
Logs in to the OpenShift server and save the session
information to a config file that will be used by every subsequent command.

First-time users of the OpenShift client must run this command to configure the server,
establish a session against it and save it to a configuration file, usually in the
user's home directory.

The information required to login, like username and password or a session token, and 
the server details, can be provided through flags. If not provided, the command will
prompt for user input if needed.

Use "osc --help" for a list of all commands available in osc.
Use "osc options" for a list of global command-line options (applies to all commands).
```

can't see help options, not very useful.

**Comment by fabianofranz** [comment]
I have a TODO for this one, the major reason is that all flags in `login` are also persistent flags, and we are hiding the persistent ones by default. We need a way in our templates or Cobra to be able to display some pre-selected flags even if they are persistent. So 2 things:

 - Expose `server`, `context`, `username`, `password`, `insecure-skip-tls-verify` and other persistent flags that have a meaning locally in `login`. 
 - I believe `username` and `password` should be *de-registered* from persistent flags, and be local to `login`. In OpenShift we only want them being used in the `login` command, nothing else.

**Comment by smarterclayton** [comment]
In the short term, just adding a custom help template that reused the default but added those specific options would help.

----- Original Message -----

**Comment by fabianofranz** [comment]
Fixed in https://github.com/openshift/origin/pull/1372

**Comment by fabianofranz** [comment]
@smarterclayton Seems I can't close an issue myself, can you close it?
