### ISSUE TITLE
Error creating rbd image: executable file not found in $PATH

### ISSUE THREAD

**Issue by eurodomenii** [openshift/origin#13517]
Error during Ceph Dynamic Provisioning https://docs.openshift.org/latest/install_config/persistent_storage/dynamically_provisioning_pvs.html#ceph-persistentdisk-cephRBD

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Running Openshift containerized ( with rpm works)
2. Schedule master as node 
3. Using Ceph Dynamic Provisioning ( with static provisioning works)

##### Current Result

```
Mar 22 23:51:49 oc docker: W0322 21:51:49.834757       1 rbd_util.go:336] failed to create rbd image, output
Mar 22 23:51:49 oc docker: E0322 21:51:49.834776       1 rbd_util.go:341] rbd: Error creating rbd image: executable file not found in $PATH
Mar 22 23:51:49 oc docker: E0322 21:51:49.834785       1 rbd.go:310] rbd: create volume failed, err: executable file not found in $PATH
Mar 22 23:51:49 oc docker: I0322 21:51:49.834797       1 pv_controller.go:1281] failed to provision volume for claim "myproject/myclaim" with StorageClass "ssdkube": rbd: create volume failed, err: executable file not found in $PATH

```
##### Expected Result
Succesful mapping. 
##### Additional Information
Explanation:
The container openshift origin master pod is missing the rbd binary. Static provisioning works because ceph-deploy was installed previously on the node. 

Related issue
https://github.com/kubernetes/kubernetes/issues/38923  Error creating rbd image: executable file not found in $PATH #38923

**Comment by 4admin2root** [comment]
Is there any plan to add ceph rbd to google_containers docker image (e.g, gcr.io/google_containers/kube-controller-manager-amd64) ?
