### ISSUE TITLE
s2i builds fail with `error: Execution of post execute step failed`

### ISSUE THREAD

**Issue by mhutter** [openshift/origin#13515]
Since the upgrade to Origin 1.4.1 (from 1.3.3), existing builds started failing. We observe the following errors after s2i builds, in the log output of the build pod:

    error: Execution of post execute step failed
    warning: Failed to remove container "e0797414abffe57004bae66ce1a6cb2eb08c448adc2ac50115f4335d7c2cfa28": Error response from daemon: {"message":"Driver devicemapper failed to remove root filesystem e0797414abffe57004bae66ce1a6cb2eb08c448adc2ac50115f4335d7c2cfa28: failed to remove device 1179c571f6c9241f9f28483afb17c0352acccee7a772c57498d5a5c1dd7a3f2d:Device is Busy"}
    error: build error: building myproject/myapp-2:6a8c0f59 failed when committing the image due to error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?

When I then connect to the OS node the build ran on, container `e0797` is already gone and deleted. Only things leftover are the pod and the builder:

    # docker ps
    064700c87936 openshift/origin-sti-builder:v1.4.1 "/usr/bin/openshift-s" About an hour ago Exited (1) About an hour ago k8s_sti-build.475d5884_myapp-2-build_myproject_faa2b943-0f0e-11e7-b75c-06ce7400036c_1269ebf8
    c23f09fc9458 openshift/origin-pod:v1.4.1         "/pod"                 About an hour ago Exited (0) About an hour ago k8s_POD.4eb8dca1_myapp-2-build_myproject_faa2b943-0f0e-11e7-b75c-06ce7400036c_c3f516c5

I also have gisted two `docker inspect <container>` outputs:

* [docker-inspect-pod.json][] - the `openshift/origin-sti-builder` container from above
* [docker-inspect-s2i.json][]

[docker-inspect-s2i.json]: https://gist.github.com/mhutter/ee47537a17648794a01dcd226b181e47#file-docker-inspect-s2i-json
[docker-inspect-pod.json]: https://gist.github.com/mhutter/ee47537a17648794a01dcd226b181e47#file-docker-inspect-pod-json

Used s2i image: [modified version of the sclorg s2i php container](https://github.com/abacusresearch/s2i-php-container/tree/master/7.0).

**Stuff I tried** (but did not work)

* restarting the docker daemon
* resetting docker storage - this did help, for a handful of builds, then the problems started again.
* Disabling selinux (has caused problems in the past)
* rebuilding the s2i image

##### Version
`oc version`:

    oc v1.4.1+3f9807a
    kubernetes v1.4.0+776c994
    features: Basic-Auth

    Server https://console.customer.net:443
    openshift v1.4.1+3f9807a
    kubernetes v1.4.0+776c994

`docker version`:

    Client:
     Version:         1.12.6
     API version:     1.24
     Package version: docker-common-1.12.6-11.el7.centos.x86_64
     Go version:      go1.7.4
     Git commit:      96d83a5/1.12.6
     Built:           Tue Mar  7 09:23:34 2017
     OS/Arch:         linux/amd64

    Server:
     Version:         1.12.6
     API version:     1.24
     Package version: docker-common-1.12.6-11.el7.centos.x86_64
     Go version:      go1.7.4
     Git commit:      96d83a5/1.12.6
     Built:           Tue Mar  7 09:23:34 2017
     OS/Arch:         linux/amd64

`docker info`:

    Containers: 64
     Running: 44
     Paused: 0
     Stopped: 20
    Images: 109
    Server Version: 1.12.6
    Storage Driver: devicemapper
     Pool Name: vg_docker-docker--pool
     Pool Blocksize: 524.3 kB
     Base Device Size: 10.74 GB
     Backing Filesystem: xfs
     Data file:
     Metadata file:
     Data Space Used: 57.97 GB
     Data Space Total: 102.8 GB
     Data Space Available: 44.79 GB
     Metadata Space Used: 9.568 MB
     Metadata Space Total: 155.2 MB
     Metadata Space Available: 145.6 MB
     Thin Pool Minimum Free Space: 10.28 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: true
     Deferred Deletion Enabled: false
     Deferred Deleted Device Count: 0
     Library Version: 1.02.135-RHEL7 (2016-11-16)
    Logging Driver: json-file
    Cgroup Driver: systemd
    Plugins:
     Volume: local
     Network: null host bridge overlay
    Swarm: inactive
    Runtimes: docker-runc runc
    Default Runtime: docker-runc
    Security Options: seccomp selinux
    Kernel Version: 3.10.0-514.10.2.el7.x86_64
    Operating System: CentOS Linux 7 (Core)
    OSType: linux
    Architecture: x86_64
    Number of Docker Hooks: 2
    CPUs: 8
    Total Memory: 31.42 GiB
    Name: node1.os.abasky.net
    ID: YOZ5:3EFC:BDBD:4EBX:CJXW:GH2U:PJJX:LMNK:IXDR:QZVC:LU7D:6HQH
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): false
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    WARNING: bridge-nf-call-iptables is disabled
    WARNING: bridge-nf-call-ip6tables is disabled
    Insecure Registries:
     127.0.0.0/8
    Registries: docker.io (secure)

##### Additional Information

`oc adm diagnostics` did not reveal any information.

The relevant lines of a build with `BUILD_LOGLEVEL=5` is in (this gist)[https://gist.github.com/mhutter/98f464a0759de25452a1634ce7cbb399]

**Comment by bparees** [comment]
this may be the issue where commits take over 2 minutes and get timed out.  It was fixed in 1.5 here:
https://github.com/openshift/origin/pull/13172

and 1.4 here:
https://github.com/openshift/origin/pull/13174/files

but it did not make it into 1.4.1.

Part of the question would be why your image commits are taking so long, however (and why that would have changed with 1.4.1, since the same timeout applied to 1.3)

**Comment by mhutter** [comment]
@bparees the resulting image _is_ quite big, I'll check if i can shrink it to get the commits under 2 minutes

**Comment by bparees** [comment]
ok, let us know.  There is also a 1.5 release candidate available which includes the fix if you want to test it on another cluster.

**Comment by mhutter** [comment]
Workarounds:

1) Shrink your Docker Image :)
2) Use a more recent S2I-Builder:

In order to temporarily use another version of the docker image, the  easiest way seems to be to simply pull the new image and tag it as the one used by openshift:

    docker pull docker.io/openshift/origin-sti-builder:v1.5.0-r
    docker tag docker.io/openshift/origin-sti-builder:v1.5.0-rc.0 docker.io/openshift/origin-sti-builder:v1.4.1

**Comment by bparees** [comment]
@mhutter great, sounds like you got it working, thanks for the update (and workarounds)!
