### ISSUE TITLE
Dynamically provisioning ssh remote access for openshift containers (use case FileZilla sftp file transfers)

### ISSUE THREAD

**Issue by eurodomenii** [openshift/origin#13521]
RATIONALE

Openshift market target, as PaaS, should include also average, non-geek users. 
Copying files to or from a container with oc rsync command line + setup cwRsync and oc cli, would be overkill for such users. 
Openshift web console is a comfortable Swiss Army knife for them already. The missing piece is an easy way to transfer files ( where FileZilla or other sftp clients comes into play).

OPENSHIFT.COM

Openshift version 2 provided ssh keys at aplication level (https://youtu.be/dZwngyEtWmU?t=189) 
https://developers.openshift.com/managing-your-applications/remote-connection.html 
https://blog.openshift.com/using-filezilla-and-sftp-on-windows-with-openshift/ 

ORIGIN 1.4+

As far as I understood, the new docker /kubernetes has different approach.
Each container is running non-privileged, non root user with a single service, without ssh daemon. 
It seems that OpenShift Online DEVELOPER PREVIEW  has the same approach. 

DESIGN IMPLEMENTATION PROPOSAL

1) Add /bin/bash to existing users
https://github.com/sclorg/s2i-base-container/blob/master/Dockerfile

`useradd -u 1001 -r -g 0 -d ${HOME} -s /sbin/nologin \`

2) Use supervisord to run ssh and web service in container
   So far can I use a hook to keep, the existing openshift origin base images git sources? I guess a build hook.

3) Dynamically expose ports
   There should be something like _ip_external_cluster:hostPort:containerPort ( ip:222:22)_ for NAT access from outside. 

   Solution confirmed by https://github.com/openshift/origin/issues/12414#issuecomment-271986646  

> An easier answer is to use a non-privileged port (say 2222) and then have a service that takes port 22 and maps it to 2222.

Now comes the most difficult part.
What host port should I use for each customer container, in order to avoid conflict ? 

A hacky way could be generating with a formula from pod name, but this would mean using a very late deployment hook. 

Or checking the next available host port in range 2222+ and assign it ? This port information should be stored somewhere, in order to expose somehow this information to the user, like token in console/command-line web console.  How to trigger and where to store the exposed host port?

Thanks!

**Comment by pweil-** [comment]
In addition to rsync an upstream copy command was added in Kubernetes https://github.com/kubernetes/kubernetes/pull/34914.  This is tracked in https://github.com/openshift/origin/issues/10529.  Closing as a duplicate.  

Help text:

```
$ oc cp --help
Copy files and directories to and from containers.

Usage:
  oc cp <file-spec-src> <file-spec-dest> [options]

Examples:
  # !!!Important Note!!!
  # Requires that the 'tar' binary is present in your container
  # image.  If 'tar' is not present, 'kubectl cp' will fail.
  
  # Copy /tmp/foo_dir local directory to /tmp/bar_dir in a remote pod in the default namespace
  oc cp /tmp/foo_dir <some-pod>:/tmp/bar_dir
  
  # Copy /tmp/foo local file to /tmp/bar in a remote pod in a specific container
  oc cp /tmp/foo <some-pod>:/tmp/bar -c <specific-container>
  
  # Copy /tmp/foo local file to /tmp/bar in a remote pod in namespace <some-namespace>
  oc cp /tmp/foo <some-namespace>/<some-pod>:/tmp/bar
  
  # Copy /tmp/foo from a remote pod to /tmp/bar locally
  oc cp <some-namespace>/<some-pod>:/tmp/foo /tmp/bar

Options:
  -c, --container='': Container name. If omitted, the first container in the pod will be chosen

Use "oc options" for a list of global command-line options (applies to all commands).
```
