### ISSUE TITLE
Add timestamps into deployer log

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13526]
Deployer pod should log the timestamps along with the messages,  so it is easier to debug problems where the scaling takes too much time and other timeout issues.

It might be also helpful when debugging long-running post-mid-pre hooks. The timestamp should be visible for normal verbosity level as well.

**Comment by mfojtik** [comment]
@tnozicka interested? ;-)

**Comment by kargakis** [comment]
`oc logs --timestamps`?

**Comment by mfojtik** [comment]
@kargakis yes, sorry forgot about that :-)
