### ISSUE TITLE
TestExtensionAPIServerConfigMap timed out waiting for the condition

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13522]
Seen: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/596/consoleFull#77873853956bf4006e4b05b79524e5923

snip:
```
--- FAIL: TestExtensionAPIServerConfigMap (14.49s)
	extension_apiserver_test.go:40: timed out waiting for the condition
FAIL
```

**Comment by mfojtik** [comment]
@deads2k FYI

**Comment by deads2k** [comment]
Failed on 

```
I0322 18:58:02.792565   21164 panics.go:76] POST /api/v1/namespaces/kube-system/configmaps: (557.560739ms) 404 [[integration.test/v1.5.2+43a9be4 (linux/amd64) kubernetes/43a9be4] 127.0.0.1:49062]
E0322 18:58:02.792803   21164 client_ca_hook.go:93] namespace "kube-system" not found
```

You'd expect that to be the namespace lifecycle admission plugin, but it seems to be happy `admission.go:157] found kube-system via storage lookup`.  Chase admission plugins maybe?  We should probably make those return error messages that indicate which admission plugin rejected them.
