### ISSUE TITLE
 hawkular-cassandra "--truststore_node_authorities value is not specified. Aborting"

### ISSUE THREAD

**Issue by askstack** [openshift/origin#13532]
Pod "hawkular-cassandra" failed to start, given this error "The --truststore_node_authorities value is not specified. Aborting"

##### Version
openshift v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. provision a new cluster with openshift-ansible
openshift_release=v1.5.0-rc.0
openshift_image_tag=v1.5.0-rc.0

##### Current Result
Pod "hawkular-cassandra" failed to start, given this error "The --truststore_node_authorities value is not specified. Aborting"

**Comment by mwringe** [comment]
It sounds like you are using the 'latest' metrics images, you need to be using the metrics images for your particular version of OpenShift.

**Comment by askstack** [comment]
How can I specify which metrics image to use?  I thought I already specified the version in my ansible inventory file. Thanks.

>openshift_release=v1.5.0-rc.0
>openshift_image_tag=v1.5.0-rc.0

**Comment by mwringe** [comment]
if you run 'oc get pods -o yaml' for the openshift-infra namespace, what version is it saying for your pods?

The error message you are seeing is not suppose to be in the 1.5.0 version of metrics.

@jcantrill for the ansible changes, where is it getting the metrics image tag from?

**Comment by askstack** [comment]
You are right, It is the latest.  
image: docker.io/openshift/origin-metrics-cassandra:latest

I will leave this bug report open for few more days, in case jcantrill replies. 

Thanks!

**Comment by jcantrill** [comment]
Recently changed, but you can specify the desired repo and image version by setting the hosted vars which will be picked up here: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/vars/default_images.yml#L2-L3

**Comment by jpkrohling** [comment]
From what I understood, this is not an issue. As such, I'm closing this one.

**Comment by gshipley** [comment]
I ran in to this issue today as well on 1.5.0.  This should be re-opened and the default behavior should pick up the correct version.  Here is the inventory that I am using.

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=origin
enable_excluders=false
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
containerized=true
openshift_release=v1.5
openshift_image_tag=v1.5.0
openshift_public_hostname=console.techdope.io
openshift_master_default_subdomain=apps.console.techdope.io
openshift_hosted_metrics_deploy=true

**Comment by mwringe** [comment]
What version of openshift-ansible are you using? You need to use the version of openshift-ansible which corresponds to the version of OpenShift and the version of metrics you want to deploy.

**Comment by loa** [comment]
Same issue here.

Using `openshift-ansible:release-1.5` with following hosts vars `openshift_release=v1.5.0`.

I get the same error and with cassandra pods on latest.

**Comment by ganto** [comment]
Having the same issue using `openshift-ansible:release-1.5`. The source of the `latest` image tag comes from [here](https://github.com/openshift/openshift-ansible/blob/b8724612088dda54a0c84a185381bd77504e6d01/roles/openshift_metrics/vars/default_images.yml#L3) (3.5.72-1). I cannot find `openshift_hosted_metrics_deployer_version` to be defined anywere, so it will default to `latest`.

**Comment by pat2man** [comment]
@ganto that looks correct. The example config has you set the logging version but not the metrics version: https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example#L571

**Comment by pat2man** [comment]
I verified that if you set `openshift_hosted_metrics_deployer_version` yourself (I set it to `v1.5.0`) and run openshift-ansible metrics come up properly.

**Comment by metal3d** [comment]
as @pat2man said, I set it up to v1.5.1 and it works !
Thanks for that resolution
