### ISSUE TITLE
Docker prefix error

### ISSUE THREAD

**Issue by Dec-** [openshift/origin#13542]
Hi,

im getting this error: Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: docker: failed to parse docker version \"17.03.0-ce\": illegal zero-prefixed version component \"03\" in \"17.03.0-ce\""

Arch Linux
Openshift origin 1.6
Docker 17.03.0-ce

**Comment by ncdc** [comment]
This will be fixed once https://github.com/openshift/origin/pull/13512 merges

**Comment by Dec-** [comment]
Thx, closing for now. 👍
