### ISSUE TITLE
Best Practices to install OpenShift in a production environment

### ISSUE THREAD

**Issue by soufiane8096** [openshift/origin#13544]
Hi guys,
I've already installed an All in one Openshift, but I wanna know what is the best practices to install it for production. What's the best architecture ? Use the advanced install (with ansible or not) ? How to monitor it ? I accept all kind of aids (documentation, comment, videos) everything.

Thank you !

**Comment by pweil-** [comment]
@soufiane8096 this is a pretty broad question.  My advice here would be to start with this documentation:  https://docs.openshift.org/latest/install_config/install/planning.html
