### ISSUE TITLE
Test failure for all scheduling predicates tests

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#13553]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/658/#showFailuresLink

**Comment by stevekuznetsov** [comment]
This is usually namespace termination problems on the serial stuff... I thought we had an issue around here somewhere for it

```
Mar 27 18:24:17.955: INFO: Waiting for terminating namespaces to be deleted...
Mar 27 18:24:17.957: INFO: Unexpected error occurred: Namespace e2e-tests-init-container-hx6md is active
```

**Comment by stevekuznetsov** [comment]
dupe of https://github.com/openshift/origin/issues/13536
