### ISSUE TITLE
Validate upstream namespace finalizer

### ISSUE THREAD

**Issue by enj** [openshift/origin#13564]
- [ ] Create third party resource and make sure it gets deleted when the namespace is deleted
- [ ] Delete the `originnamespacefinalizer` and make sure that something like a `buildconfig` (origin only resource) gets cleaned up automatically

cc @liggitt @deads2k do we need to add anything else?

**Comment by deads2k** [comment]
> cc @liggitt @deads2k do we need to add anything else?

Delete the originnamespacefinalizer and make sure that something like a buildconfig gets cleaned up automatically.

**Comment by enj** [comment]
@deads2k do we need anything else or did #13587 take care of this?

**Comment by deads2k** [comment]
done
