### ISSUE TITLE
Origin's openstack.go does not support ca-file cloud provider attribute

### ISSUE THREAD

**Issue by Delmonte3161** [openshift/origin#13571]
The Kubernetes openstack.go supports ca-file cloud provider attribute but origin's openstack.go does not: [see kubernetes code here](https://github.com/kubernetes/kubernetes/blob/eaf8351d45d712987929f6584deda89035fc0e8d/pkg/cloudprovider/providers/openstack/openstack.go)

My openstack provider does not allow api-key auth so need ability to pass a ca-file to the cloud provider for v3 ssl authentication.

**Comment by mfojtik** [comment]
@Delmonte3161 we should get that attribute after 1.6 rebase lands as this flag was added a month ago (https://github.com/kubernetes/kubernetes/commit/e3c8a0ceb66816433b095c4d734663e1b1e0e4ea).
