### ISSUE TITLE
Egress Firewall - Invalid value: "": invalid CIDR address:

### ISSUE THREAD

**Issue by canit00** [openshift/origin#13573]
Currently unable to deploy egress firewall rule using dnsName as outlined in the [latest documentation](https://docs.openshift.org/latest/admin_guide/managing_networking.html#admin-guide-limit-pod-access-egress).

***Would like the ability to utilize egress firewall using dnsName***

[version]
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994

##### Steps To Reproduce
oc create -f example-egress-fw.json

```
{
    "kind": "EgressNetworkPolicy",
    "apiVersion": "v1",
    "metadata": {
        "name": "default"
    },
    "spec": {
        "egress": [
            {
                "type": "Allow",
                "to": {
                    "cidrSelector": "1.2.3.0/24"
                }
            },
            {
                "type": "Allow",
                "to": {
                    "dnsName": "www.foo.com"
                }
            },
            {
                "type": "Deny",
                "to": {
                    "cidrSelector": "0.0.0.0/0"
                }
            }
        ]
    }
}
```

##### Current Result
***Error:***

```
The EgressNetworkPolicy "default" is invalid: spec.egress[1].to: Invalid value: "": invalid CIDR address: 
```

##### Expected Result
The ability to deploy egress firewall using dnsName - per documentation.

##### Additional Information
The catch here is when reading the [OCP egress FW documentation](https://docs.openshift.com/container-platform/3.4/admin_guide/managing_pods.html#admin-guide-limit-pod-access-egress) it does not mention the ***to dnsName***.

When deploying the example noted in the OCP documentation deployment works.

```
{
    "kind": "EgressNetworkPolicy",
    "apiVersion": "v1",
    "metadata": {
        "name": "default"
    },
    "spec": {
        "egress": [
            {
                "type": "Allow",
                "to": {
                    "cidrSelector": "1.2.3.0/24"
                }
            },
            {
                "type": "Deny",
                "to": {
                    "cidrSelector": "0.0.0.0/0"
                }
            }
        ]
    }
}
```

***Would like the ability to utilize egress firewall using dnsName***

**Comment by canit00** [comment]
Learned that this in the upstream Origin version. Thanks!

**Comment by zuaresc** [comment]
@mfojtik I have tried to use this new feature in Origin 1.5.1 and am receiving the same error that @canit00 received. According to the [1.5 documentation](https://docs.openshift.org/1.5/admin_guide/managing_networking.html#admin-guide-limit-pod-access-egress), this functionality should be available. However, the API endpoint doesn't accept `dnsName` as a valid property. It's missing from the [1.5 API documentation](https://docs.openshift.org/1.5/rest_api/openshift_v1.html#v1-egressnetworkpolicypeer) as well.

Is this expected?
