### ISSUE TITLE
Multi port on the one domain

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [openshift/origin#13574]
[Multi port on the one domain to several containers]

##### Version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Create first route to pod for domain example.com (for http :80)
2. Create second route to pod for domain example.com (for http :8080)
3. Create third route to pod for domain example.com (for https :443)

##### Current Result
Requested host example.com was rejected by the router. Reason: route first-route already exposes example.com and is older.
##### Expected Result
It is necessary to have access to several ports in one or several containers using only one domain

**Comment by kincl** [comment]
Is there a plan to support this in the future? I don't see any reason why the domain should have to be unique across all routes when you could have one route serve unsecured traffic and another route serve secured traffic on the same domain.

**Comment by knobunc** [comment]
You can set up a route that redirects http to https, or that allows both http and https traffic, but it will only send the traffic to one back-end.  There is no way to serve completely different traffic for http and for https for the same path.

We don't view having completely different content that differs only by the http protocol used as a valuable feature.  Also, we do not allow specification of the port used for http or https in the route.  The router is configured with the http and https port to use (defaulting to 80 and 443).  If you want to serve content on other ports you could use router sharding to accommodate it by labeling the routes or namespaces and then using label selectors in the router configuration to choose what routes to serve on the different routers.
