### ISSUE TITLE
Sort events by timestamp

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#13581]
It'd be great if oc get events could by default sort by lastTimestamp, it just makes more sense instead of having to type more

`oc get events --sort-by='.lastTimestamp'`

**Comment by rascasoft** [comment]
Would it be possible to reopen this one? I think it raises a very straight point: as it is by now "oc get events" is pretty useless unless you exactly know what you're looking for.

**Comment by bsquizz** [comment]
@rascasoft this syntax currently works for me:

```
oc get events --sort-by='{.lastTimestamp}'
```

**Comment by flickerfly** [comment]
Doesn't seem to work with `--all-namespaces` which would be nice.

**Comment by yrro** [comment]
I am using this as a workaround:

https://github.com/kubernetes/kubernetes/issues/29838#issuecomment-646764617

**Comment by EmmanuelKasper** [comment]
@flickerfly 
FWIW with OCP 4.7 sorting  by timestamp in all namespaces is working.

~~~
oc get events --sort-by='{.lastTimestamp}' --all-namespaces | head -2

NAMESPACE                 LAST SEEN   TYPE      REASON                  OBJECT                          MESSAGE
openshift-marketplace     142m        Normal    Scheduled               pod/redhat-operators-6mnwr      Successfully assigned openshift-marketplace/redhat-ope

oc get events --sort-by='{.lastTimestamp}' --all-namespaces | tail -1 
openshift-marketplace     90s         Normal    Killing                 pod/redhat-operators-q69n8      Stopping container registry-server
~~~

**Comment by ypismerov-tmx** [comment]
I vote for reopening this issue as it does not make sense to keep adding the option routinely.
What would it break?
