### ISSUE TITLE
calico network failed to "SetupNetwork"

### ISSUE THREAD

**Issue by zhwenh** [openshift/origin#13580]
origin v1.5.0-rc.0 Version + Calico + cni

this is my inventory

openshift_use_openshift_sdn=false
openshift_node_proxy_mode=iptables
openshift_use_calico=true
os_sdn_network_plugin_name=cni

kubectl get pods --namespace=kube-system
NAME READY STATUS RESTARTS AGE
calico-policy-controller-442588368-2k3hh 1/1 Running 0 1d

f8c226ee26b5 calico/node:v1.1.0 "start_runit" 2 days ago Up 2 days calico-node

./calicoctl get profile k8s_ns.default -o yaml

apiVersion: v1
kind: profile
metadata:
name: k8s_ns.default
tags:
k8s_ns.default
spec:
egress:
action: allow
destination: {}
source: {}
ingress:
action: allow
destination: {}
source: {}
"router-1-deploy_default “ pod is in ns default
Additional Information

Error syncing pod, skipping: failed to "SetupNetwork" for "router-3-deploy_default" with SetupNetworkError: "Failed to setup network for pod "router-3-deploy_default(799d976f-1502-11e7-b3c1-fa163e10ef43)" using network plugins "cni": failed to send CNI request: Post http://dummy/: dial unix /var/run/openshift-sdn/cni-server.sock: connect: no such file or directory; Skipping pod"	39 times in the last 0 seconds

**Comment by djosborne** [comment]
This was resolved in the duplicate issue: https://github.com/openshift/openshift-ansible/issues/3805
