### ISSUE TITLE
openvswitch support for NetworkPolicy plugin

### ISSUE THREAD

**Issue by barnzdan** [openshift/origin#13596]
Having an issue getting redhat/openshift-ovs-networkpolicy tested on v3.6.0-alpha.0 and compatibility with openvswitch image for v3.6.0-alpha.0.

##### Version
% oc version
oc v3.6.0-alpha.0+0343989
kubernetes v1.5.2+43a9be4
features: Basic-Auth

openshift v3.6.0-alpha.0+0343989
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. build containerized cluster using openshift_image_tag=v3.6.0-alpha.0
2. set os_sdn_network_plugin_name='redhat/openshift-ovs-networkpolicy'

##### Current Result
openshift-master.service starts
openshift-node.service will not start with the following error: SDN initialization failed: found OVS 2.4.0, need 2.5.0 or later
openvswitch docker image: openshift/openvswitch:v3.6.0-alpha.0 

 **_ovs-vsctl show_**
e0bc5956-286d-4ab5-8bf1-df52ab47249e
    Bridge "br0"
        fail_mode: secure
        Port "tun0"
            Interface "tun0"
                type: internal
        Port "vxlan0"
            Interface "vxlan0"
                type: vxlan
                options: {key=flow, remote_ip=flow}
        Port "br0"
            Interface "br0"
                type: internal
       ovs_version: 2.4.0

##### Expected Result
Have a version of ovs that is compatible with NetworkPolicy plugin.

**Comment by barnzdan** [comment]
Any updates on this one?

**Comment by kargakis** [comment]
Please ask at the openshift users mailing list.
