### ISSUE TITLE
source IP to container log for external traffic

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [openshift/origin#13592]
source IP to container for external traffic

##### Version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Run nginx container 
2. Create route

##### Current Result
Now in log have docker IP (as source IP) 172.17.0.1 instead 42.76.65.54

##### Expected Result 
In log have source IP (e.g. 42.76.65.54) instead local docker IP (172.17.0.1)

**Comment by pweil-** [comment]
@Evgeniy-Bondarenko it's unclear what the issue is here?  A couple questions to help someone debug:

1. why do you expect the 42.* ip address?  All pods in OpenShift are assigned an ip from the pod cidr
1. creating a route does not change an pod's ip address so the steps to reproduce are not clear
1. what log are you referring to
1. please include pod definitions and the logs, redact information if necessary

**Comment by Evgeniy-Bondarenko** [comment]
@pweil- I am check again several options

1. 42.76.65.54 - it is example public address for nginx request

2.a. If use **UNsecured** route, then source ip address is not change.
`PC (42.76.65.54) -> :80 [openshift] -> unsecured route ->:80 [nginx pod] -> in nginx log "42.76.65.54"`
 
2.b.  If use secured route **EDGE**, then source ip address is not change
`PC (42.76.65.54) -> :443 [openshift] -> secured EDGE-route ->:80 [nginx pod] -> in nginx log "42.76.65.54" `

2.c.  If use secured route **passthought**, then source ip address is **CHANGE**
`PC (42.76.65.54) -> :443 [openshift] -> secured passthought-route ->:443 [nginx pod] -> in nginx log "172.17.0.1"`(docker ip host) or empty. Also empty in headers '"$http_user_agent" "$http_x_forwarded_for", in $remote_addr - "172.17.0.1"(docker ip host).


Is it possible to obtain $remote_addr (souce public ip PC) if I can use case 2.c. (secured passthought-route)?
Also in 2b I have _400 Error_ when I am want use ssl in to nginx container:
`PC (42.76.65.54) -> :443 [openshift] -> secured EDGE-route ->_**:443**_ [nginx pod] -> in nginx log "42.76.65.54" `

**Comment by pweil-** [comment]
Ah, thanks for the clarification @Evgeniy-Bondarenko.  That makes much more sense and should be enough info for the network folks to comment.  However, I think the sticking point here is that a passthrough route is a tcp connection in the haproxy template (so it can support non-http traffic) so there is not a chance to set forwarded for headers.

**Comment by Evgeniy-Bondarenko** [comment]
1. Can I change (add proxy for header)? There are some examples of how to make a modification to the haproxy template and use your custom container in the router `router`

2. also use `http2.0` and via `passthrough route` - all work
but via `EDGE route`  - I have  only `http1.1`
**`HTTP2.0`** is very important for me now, due to the non receipt of the header, there are many questions about the expansion of the router functionality and the addition of custom functions.

3. `proxy_protocol` Is it possible to use it through a router?
https://www.nginx.com/resources/admin-guide/proxy-protocol/

**Comment by pweil-** [comment]
You are able to [configure the PROXY protocol](https://docs.openshift.org/latest/install_config/router/proxy_protocol.html) to be used.  As you mentioned you can definitely customize the template if necessary.  I'll let the network folks comment on if that's suitable or not based on your use case.  :smile:

**Comment by knobunc** [comment]
The proxy protocol we directly support is to get the information to the router.  We currently do not configure haproxy to pass it to the backends.

BUT you can configure that yourself using a custom template and route annotations.

If you set 'send-proxy (https://cbonte.github.io/haproxy-dconv/1.5/configuration.html#5.2-send-proxy) on the server line it will enable proxy protocol.  You can then make a new annotation on routes to enable it, and make use of that in the template to conventionalize it:
  https://github.com/openshift/openshift-docs/pull/3779/files#diff-31124cd02eb905bca7f54c8cc4ffe68dR288

Then you can follow https://docs.openshift.com/enterprise/3.2/install_config/install/deploy_router.html#using-configmap-replace-template to replace the router template.
