### ISSUE TITLE
Provide feedback on progression for "Receiving source from STDIN as archive..."

### ISSUE THREAD

**Issue by apupier** [openshift/origin#13612]
When starting a build which is quite big or over a slow network, the message "Receiving source from STDIN as archive..." can stay for several minutes without any feedback.

it would be nice to provide progression to the user.

##### Version
Version

OpenShift Master:
v3.4.1.10
Kubernetes Master:
v1.4.0+776c994

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Current Result
a long wait without feedback

##### Expected Result
an indicator of the progression

##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

related code is here: https://github.com/openshift/origin/blob/15e32698da7bd4c8d24a3d965571b356ac022250/pkg/build/builder/source.go#L201

**Comment by bparees** [comment]
converted to trello card: https://trello.com/c/EeYJiEdg
