### ISSUE TITLE
complete investigation/change around use of common webhook cause for github/generic

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#13620]
Consider this portion of the recently dropped changes for gitlab and bitbucket webhooks:  https://github.com/openshift/origin/blob/master/pkg/build/api/types.go#L176-L216

During the discussion in https://github.com/openshift/origin/pull/13389, the question was asked if we could refactor the existing `GitHubWebHookCause` and `GenericWebHookCause` to use `CommonWebHookCause`

The discussion started in earnest at https://github.com/openshift/origin/pull/13389#discussion_r108419441
and was active for about a day, culminating with the ask from @bparees [here](https://github.com/openshift/origin/pull/13389#discussion_r108685079) to @smarterclayton to weigh in.

This issue is being opened to track getting that feedback from @smarterclayton and if code changes to `GitHubWebHookCause` and `GenericWebHookCause` to use `CommonWebHookCause` are allowable, make those happen.

**Comment by smarterclayton** [comment]
You can change the internal structure as long as serialization doesn't
change.  If you do an inlined struct (both in Go and JSON) usually you can
get away with it.  Have to be really, really careful that both stay the
same.

**Comment by bparees** [comment]
@smarterclayton the concern was around protobuf serialization, which is going to change if we do this.  My understanding was that might be ok since we aren't storing protobufs yet, nor are external clients using it.

**Comment by smarterclayton** [comment]
You can definitely use the common struct on new external types, and use the
common struct internally.  Not going to give you much though (to use it
internally).

**Comment by bparees** [comment]
the external serialization (json format) isn't going to change.

i think maybe the simplest way to move forward is for @gabemontero to create the PR refactoring things and we can discuss the changes with an example in front of us.

**Comment by gabemontero** [comment]
See PR ... we cannot make this change.
