### ISSUE TITLE
No warning about route host and ROUTER_OVERRIDE_HOSTNAME/ROUTER_SUBDOMAIN mismatch

### ISSUE THREAD

**Issue by carlpett** [openshift/origin#13622]
We tried to set a specific host header on a route, and it just wouldn't "take". The yaml `spec.host` would be correct, but `status.ingress.host` would be set to the auto-generated host. After quite a lot of troubleshooting, we found this in the documentation:

>`ROUTER_OVERRIDE_HOSTNAME` If set true, override the spec.host value for a route with the template in `ROUTER_SUBDOMAIN`.

And sure enough, `ROUTER_OVERRIDE_HOSTNAME` was `true`. But I think that maybe this should generate some type of notice to the user? Since we didn't know about those settings, it "just not works", without any feedback about what was going wrong. The route is admitted, but altered, so it's a bit of mixed signals.

##### Version
```bash
$ oc version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master-api.domain.tld
openshift v1.4.1
kubernetes v1.4.0+776c994
```

##### Steps To Reproduce
1. Create route with specific host, despite having `ROUTER_OVERRIDE_HOSTNAME` and `ROUTER_SUBDOMAIN` set.
2. `oc get route the-route -o yaml`, or check UI

##### Current Result
All OK without errors, but spec and status do not match.

##### Expected Result
Some type of warning

**Comment by pweil-** [comment]
I would've expected the route status to indicate the exposed route name which was different than the spec.host.  @carlpett was that the case here?  If so maybe a condition to make it more clear to the user would be helpful

**Comment by carlpett** [comment]
@pweil- Yes, the hostname reported in the UI, or `status.ingress.host` in the yaml, was different from the one I asked for.  So just a little hint as to why this was happening, maybe linking to the docs, would have been sufficient.
