### ISSUE TITLE
local git repository in openshift 3

### ISSUE THREAD

**Issue by yeganx** [openshift/origin#13634]
[provide a description of the issue]
we have problem in build source code that is local git rep
git clone user@192.168.0.11:/home/user/gitRepSrc
the above command work properly and master can see 192.168.0.11
my problem is , I dont know what should put in Git Repository URL in templete ?
##### Version
[provide output of the `openshift version` or `oc version` command]
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

**Comment by pweil-** [comment]
@yeganx please provide more info for folks to help out.  What template are you trying to instantiate?  How did you deploy OpenShift and can the nodes see the git repo?   What error are you seeing and where is the error being surfaced?  Logs, events, and resource definitions?

**Comment by yeganx** [comment]
all my openshift node can clone it , but its not password less
i go through this https://blog.openshift.com/deploying-from-private-git-repositories/
my type of  project is php project 
$  git clone user@192.168.0.11:/home/user/gitRepSrc
in 192.168.0.11 i did 
oc project test
$ssh-keygen -t rsa -C "my_secret_key_for_OpenShift"
Enter file in which to save the key (/root/.ssh/id_rsa): /root/.ssh/id_xxx
Enter passphrase (empty for no passphrase): (enter)
Enter same passphrase again: (enter)
$oc secrets new-sshauth sshsecret --ssh-privatekey=$HOME/.ssh/id_XXX
$oc secrets add serviceaccount/builder secrets/sshsecret
$oc patch buildConfig myapp -p '{"spec":{"source":{"sourceSecret":{"name":"sshsecret"}}}}'

**Comment by bparees** [comment]
not sure why this has been opened twice but i'm closing this one in deference to
https://github.com/openshift/origin/issues/13689
