### ISSUE TITLE
cluster up: create a route for the system registry

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#13643]
cluster up should create a TLS route for the local registry so images can be pushed/pulled directly from the registry. 

This requires that the right certificate be placed under `/etc/docker/certs.d/[route-host]/' in the Docker VM.

**Comment by csrwng** [comment]
@LalatenduMohanty @hferentschik

**Comment by hferentschik** [comment]
@csrwng is there an ETA when this will come? Can this be part of 1.6 (or I guess 3.6 now)?

**Comment by csrwng** [comment]
@hferentschik no eta at this point, but we have it on our trello board. I'll give it higher priority than other cluster up items.

**Comment by bparees** [comment]
@csrwng please link the trello card + close this issue.

**Comment by csrwng** [comment]
https://trello.com/c/8DR2emei/1140-2-expose-the-openshift-registry-through-a-route-when-started-with-cluster-up-localdev
