### ISSUE TITLE
Extended.deploymentconfigs with enhanced status [Conformance] [It] should include various info in status 

### ISSUE THREAD

**Issue by legionus** [openshift/origin#13644]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/582/testReport/junit/(root)/Extended/deploymentconfigs_with_enhanced_status__Conformance__should_include_various_info_in_status/

**Comment by kargakis** [comment]
```
Apr  5 12:22:14.034: INFO: Running 'oc logs --config=/tmp/extended-test-cli-deployment-5mxrq-gvb5w-user.kubeconfig --namespace=extended-test-cli-deployment-5mxrq-gvb5w pod/deployment-simple-1-deploy --timestamps=true'
Apr  5 12:22:14.808: INFO: --- pod deployment-simple-1-deploy logs
2017-04-05T16:22:08.272799000Z error: couldn't get deployment deployment-simple-1: the server has asked for the client to provide credentials (get replicationcontrollers deployment-simple-1)---
```
@mfojtik

**Comment by bparees** [comment]
looks like the same failure mode on a similar test here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/142/testReport/junit/(root)/Extended/deploymentconfigs_rolled_back__Conformance__should_rollback_to_an_older_deployment/

**Comment by mfojtik** [comment]
seems like this is infrastructure related... we need to know why the client has to provide credentials (all clients in extended tests use the kubeconfig files so it should not ask for the credentials unless the test is talking to a different server or the server is not fully bootstrapped?)

**Comment by enj** [comment]
Closing since does not seem to occur anymore.
