### ISSUE TITLE
Pod dns lookups fail as oc cluster up is using hosts dns instead of ClusterDNS

### ISSUE THREAD

**Issue by kcd83** [openshift/origin#13648]
The `oc cluster` tool uses hosts dns configuration instead of clusterdns. Without cluster dns, pod inter-communication fails e,g, https://wesmorgan.svbtle.com/rabbitmq-cluster-on-kubernetes-with-statefulsets

This may be by design but is there any documentation to help explain this or better yet alternative configurations?

##### Version
oc v3.6.0-alpha.0+0343989
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://10.22.104.212:8443
kubernetes v1.5.3

##### Steps To Reproduce
1. oc rsh somepod
2. cat /etc/resolve.conf

```
oc cluster up --host-data-dir=/mydata --version=v1.5.0-alpha.3
oc create secret generic rabbitmq-config --from-literal=erlang-cookie=c-is-for-cookie-thats-good-enough-for-me
oc create -f .\k8s-rabbitmq-statefulset.yaml
```
If using https://wesmorgan.svbtle.com/rabbitmq-cluster-on-kubernetes-with-statefulsets comment out `volume.alpha.kubernetes.io/storage-class: anything` first or you will need to delete the PVCs and start again.

##### Current Result
nslookup someotherpod will fail.
```
cat /etc/resolv.conf
search mycompany.local
nameserver 10.22.15.1
nameserver 10.22.15.2
nameserver 192.168.101.8
```
##### Expected Result
Example when using minikube
```
cat /etc/resolv.conf
search rabbitmq.default.svc.cluster.local default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.0.0.10
options ndots:5
```

Am I doing something wrong or is there a workaround to get dns working for pods?

**Comment by csrwng** [comment]
This was a bug. It's been fixed with https://github.com/openshift/origin/pull/13539

@kcd83 try building a newer oc from origin master

**Comment by kcd83** [comment]
I cannot spot which script builds `oc` in https://github.com/openshift/origin/blob/master/HACKING.md

Are the CI builds available?

**Comment by bparees** [comment]
at this point you can use the new origin 3.6.0-alpha2 release to pick up the fix.  closing, please comment back if it's still an issue for you.
