### ISSUE TITLE
build pruning configuration api

### ISSUE THREAD

**Issue by bparees** [openshift/origin#13640]
We're working on https://trello.com/c/048p7YRO this sprint, and as part of that we need to add pruning configuration fields to the buildconfig.  Specifically the user needs to tell us how many builds to keep.

We have a few apis in mind and would like @openshift/api-review to weigh in on the preferred implementation:

1) user just indicates to keep N builds, we keep the last N builds.
2) user indicates to keep N builds, we keep N builds and at least the last successful build if it's not part of N
3) user indicates to keep N builds, we keep N builds and at least the last failed build if it's not part of N
4) user indicates to keep N builds, we keep N builds and at least the last failed+successful builds if they are not part of N
5) user indicates to keep N failed builds and M successful builds, we do that.

(5) aligns with the arguments oadm prune currently takes and is the most flexible option, so that's our preferred approach (ie introduce 2 new fields on BuildConfig, KeepFailedBuilds and KeepSuccessfulBuilds or some such names)

Default values will be infinity in all cases (again unless we are advised otherwise by @openshift/api-review)

/cc @coreydaley

**Comment by kargakis** [comment]
Another option is to follow the implementation of cleanup policy for CronJobs where options for both successful and failed jobs are provided: https://github.com/kubernetes/kubernetes/pull/40932

**Comment by bparees** [comment]
@kargakis isn't that pretty much option 5 above?

**Comment by smarterclayton** [comment]
I'm ok with 5, keep names consistent with cronjobs (sub build / jobs etc)

Builds are a job.

On Apr 5, 2017, at 7:22 PM, Ben Parees <notifications@github.com> wrote:

@kargakis <https://github.com/kargakis> isn't that pretty much option 5
above?

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/13640#issuecomment-291933784>,
or mute the thread

**Comment by kargakis** [comment]
@bparees yeah, for some unknown reason I skipped that

**Comment by pweil-** [comment]
5 seems easiest to reason about.  1 still makes you understand that N might not be high enough to have a successful build still around.

**Comment by bparees** [comment]
sounds like consensus on option 5 and copy the names from what other components use.
