### ISSUE TITLE
ExtendedTest.ImageEco: 

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#13659]
See https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/21/

The mongo replica statefulset extended test failed.

When attempting to read a record from a replicaset pod we got an authentication failure:

```

DEBUG: reading record from the pod mongodb-replicaset-0
Apr  6 01:36:59.296: INFO: Running 'oc exec --config=/tmp/extended-test-mongodb-petset-replica-5zmxf-wz761-user.kubeconfig --namespace=extended-test-mongodb-petset-replica-5zmxf-wz761 mongodb-replicaset-0 -- bash -c mongo --quiet "$MONGODB_DATABASE" --username "$MONGODB_USER" --password "$MONGODB_PASSWORD" --eval 'rs.slaveOk(); printjson(db.test.find({}, {_id: 0}).toArray())''
Apr  6 01:36:59.623: INFO: Error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc [oc exec --config=/tmp/extended-test-mongodb-petset-replica-5zmxf-wz761-user.kubeconfig --namespace=extended-test-mongodb-petset-replica-5zmxf-wz761 mongodb-replicaset-0 -- bash -c mongo --quiet "$MONGODB_DATABASE" --username "$MONGODB_USER" --password "$MONGODB_PASSWORD" --eval 'rs.slaveOk(); printjson(db.test.find({}, {_id: 0}).toArray())'] []   2017-04-06T05:36:59.615+0000 E QUERY    [thread1] Error: Authentication failed. :
DB.prototype._authOrThrow@src/mongo/shell/db.js:1441:20
@(auth):6:1
@(auth):1:2

exception: login failed
 2017-04-06T05:36:59.615+0000 E QUERY    [thread1] Error: Authentication failed. :

2017-04-06T05:36:59.615+0000 E QUERY    [thread1] Error: Authentication failed. 


```

The mongodb-replicaset-0 pod exists, as do -1 and -2, and their logs are dumped.

For each of them, their last log entries are indicative of an error ... I don't know enough about mongo to say with certainty whether the are benign or not, or would have anything to do the Authentication failure previously noted. 
Pending any clarification on this email thread, I'll just open and issue and we can triage from there.

Here is an example of the logs I'm referring to:

```

2017-04-06T05:36:52.380061000Z => [Thu Apr 06 05:36:52] Successfully joined replica set
2017-04-06T05:36:53.278599000Z 2017-04-06T05:36:53.277+0000 I REPL     [ReplicationExecutor] could not find member to sync from
2017-04-06T05:37:55.003372000Z 2017-04-06T05:37:55.001+0000 E STORAGE  [ftdc] WiredTiger (2) [1491457075:1495][17:0x7f5b4a582700], WT_SESSION.open_cursor: /var/lib/mongodb/data/collection-6-5046268617127439500.wt: file-size: stat: No such file or directory
2017-04-06T05:37:55.003656000Z 2017-04-06T05:37:55.001+0000 W FTDC     [ftdc] Uncaught exception in 'CursorNotFound: unable to open cursor at URI statistics:table:collection-6-5046268617127439500. reason: No such file or directory' in full-time diagnostic data capture subsystem. Shutting down the full-time diagnostic data capture subsystem.:
%!s(<nil>)

```

**Comment by gabemontero** [comment]
Assigned P3 for now ... unclear if this is consistent or flake

**Comment by bparees** [comment]
@omron93 would appreciate any insight you can offer.

**Comment by omron93** [comment]
@gabemontero I hope it is fixed now - please retest it. (description in https://github.com/sclorg/mongodb-container/issues/237)

Second log is very interesting and it seems like a bug in MongoDB. How to reproduce this issue?

Also it would be good to extend GitHub CI tests (https://github.com/sclorg/mongodb-container/blob/master/3.2/test/run-openshift) to test more scenarios... to catch failures earlier. @bparees Suggestions are welcomed.

**Comment by bparees** [comment]
rerunning here:
https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/test_branch_origin_extended_image_ecosystem/23/

**Comment by gabemontero** [comment]
We had another instance of the error last night:  https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/22/display/redirect

It looks like it ran before https://github.com/sclorg/mongodb-container/pull/237 was done, so it may just be a question of timing.

**Comment by bparees** [comment]
@omron93 the test in question is here:
https://github.com/openshift/origin/blob/master/test/extended/image_ecosystem/mongodb_replica_statefulset.go

reproducing it can be done by either manually walking through the steps of that test against your own cluster, or setting up+running the openshift extended test core bucket w/ a focus of "statefulset"

as for extending the basic image tests to catch something like this... well, certainly testing replication in the basic tests would be nice, but probably fairly painful w/o the openshift infrastructure in place.  I see there's a run-openshift test script, it that being executed as part of the image PR CI tests?

**Comment by gabemontero** [comment]
https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/test_branch_origin_extended_image_ecosystem/23/ is still running, but in looking at the full console log the statefulset tests have run and passed.

I'll wait for the job to complete to be sure, but assuming I didn't miss anything, I'll mark this closed (given it was happening consistently) when successful completion is official.

**Comment by gabemontero** [comment]
Test officially passed ... closing.

**Comment by bparees** [comment]
thanks @gabemontero, @omron93

**Comment by omron93** [comment]
> as for extending the basic image tests to catch something like this... well, certainly testing replication in the basic tests would be nice, but probably fairly painful w/o the openshift infrastructure in place. I see there's a run-openshift test script, it that being executed as part of the image PR CI tests?

@bparees  Yes, I thought `run-openshift` script for mongodb-container. It is not executed automatically for every PR, but can be triggered by `[test-openshift]` (and I try to do it for every PR changing replication related code).
For the mongodb-container PR that caused this issue, `run-openshift` script passed (because it is using only admin user)... So therefore I thought it would be good to extend it. So I would like to know what in your point of view would be good to test with pull requests ?

**Comment by bparees** [comment]
sounds like it would be good to run as both admin and non-admin :)

it'd be nice to always run the openshift tests too, unless that's just too time consuming.

**Comment by omron93** [comment]
> sounds like it would be good to run as both admin and non-admin :)

Yes, that is current problem. I thought anything to test possible future mistakes :-)

> it'd be nice to always run the openshift tests too, unless that's just too time consuming.

I agree. But IMPOV problem is that extended tests requires compilation of OpenShift origin. @bparees Or something changed?

**Comment by bparees** [comment]
i don't remember the details but can you not just grab the latest origin release binaries and use oc cluster up or something?
