### ISSUE TITLE
TestConcurrentBuildPodControllers running state test: Did not reach desired build state: Running

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13650]
```
--- FAIL: TestConcurrentBuildPodControllers (55.18s)
	controllers.go:300: running state test: Did not reach desired build state: Running
	etcd.go:99: dumping etcd to "/tmp/openshift/test-integration/etcd-dump-TestConcurrentBuildPodControllers.json"
FAIL
```

Seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/579/consoleFull#122487110756bf4006e4b05b79524e5923

**Comment by bparees** [comment]
@csrwng seems likely to be related to the buildpod controller refactor.  at a minimum the test needs a lot more debugging to print out the build it's actually looking at and the state of it, so we can do a better job of correlating what's in etcd.

**Comment by csrwng** [comment]
@bparees most of the time you can see from the log what states the pod has transitioned to. Taking a look.

**Comment by bparees** [comment]
the etcd dump for this run shows 3 builds, one in pending, one in failed because the pod was deleted, and one in a generic failed state.  I'm guessing the build in question is the one that's still in pending.

**Comment by csrwng** [comment]
The log doesn't seem to indicate a problem with the code,  but rather with the test. The test did not catch an update event for the pod when it transitioned from pending to running. Lowering to P2 and will submit a PR to add more logging to determine where the issue is.

**Comment by bparees** [comment]
flakes default to P1 based on them impacting other developers trying to test/merge, not necessarily because they represent a product issue.  If after a month or so this isn't recurring frequently we can consider lowering it (but hopefully we'll have it fixed before then).

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/1062/

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/1103/

**Comment by mfojtik** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/1184/consoleFull#122489609356bf4006e4b05b79524e5923

**Comment by eparis** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/485/
