### ISSUE TITLE
oc policy scc-review: error message doesn't provide useful info

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#13651]
`oc policy scc-review` and `oc policy scc-subject-review` should show a useful error message.

##### Version
oc v3.6.0-alpha.0+83e3250-176-dirty
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. `oc policy scc-subject-review`
2. `oc policy scc-review`

##### Current Result
```console
$ oc policy scc-subject-review
error: scc-subject-review
See 'oc policy scc-subject-review -h' for help and examples.
$ oc policy scc-review
error: scc-review
See 'oc policy scc-review -h' for help and examples.
```

##### Expected Result
Should show something more useful. For example:
```
$ oc policy can-i
error: you must specify two or three arguments: verb, resource, and optional resourceName
See 'oc policy can-i -h' for help and examples.
```

CC @sdminonne

**Comment by sdminonne** [comment]
sorry folks, seeing this only now.
