### ISSUE TITLE
Setting env is not workable in installing atomic-registry

### ISSUE THREAD

**Issue by yangjunsss** [openshift/origin#13655]
The env variable is not workable when install atomic-registry via ``atomic install``

```shell
[root@i-srns2x1d ~]# echo $CONSOLEPORT
8080
[root@i-srns2x1d ~]# sudo atomic install projectatomic/atomic-registry-install $REGISTRY_HOST | grep CONSOLEPORT
+ mkdir -p /etc/atomic-registry/master/site
+ mkdir -p /etc/atomic-registry/registry
+ mkdir -p /etc/atomic-registry/serviceaccount
+ mkdir -p /host/var/lib/atomic-registry/registry
+ cp /exports/unit_files/atomic-registry-console.service /exports/unit_files/atomic-registry-master.service /exports/unit_files/atomic-registry.service /host/etc/systemd/system/
+ cp /exports/config/atomic-registry /exports/config/atomic-registry-console /exports/config/atomic-registry-master /host/etc/sysconfig/
+ cp /exports/oauthclient.yaml /etc/atomic-registry/master/
+ cp /exports/setup-atomic-registry.sh /host/var/run/
+ cp /exports/registry-login-template.html /host/etc/atomic-registry/master/site/
+ chown -R 1001:root /host/var/lib/atomic-registry/registry
+ chown -R 1001:root /etc/atomic-registry/registry
+ set +x
CONSOLEPORT=9090
docker run -i --rm --privileged --net=host -v /etc/atomic-registry/:/etc/atomic-registry/ -v /var/lib/atomic-registry/:/var/lib/atomic-registry/ -v /:/host -e REGISTRYPORT -e MASTERPORT -e CONSOLEPORT -e REGISTRYIMAGE -e MASTERIMAGE -e CONSOLEIMAGE -e REGISTRYTAG -e MASTERTAG -e CONSOLETAG --entrypoint /usr/bin/install.sh projectatomic/atomic-registry-install 139.198.5.141
```

You can see the ``CONSOLEPORT`` have already set to 8080,but the ``CONSOLEPORT`` variable is still 9090 not the expected value 8080 in config file and outputs.

My env:
```shell
[root@i-srns2x1d ~]# atomic -v
1.14.1
[root@i-pygpuj80 ~]# cat /etc/fedora-release
Fedora release 24 (Twenty Four)
[root@i-srns2x1d ~]# uname -a
Linux i-srns2x1d 4.5.5-300.fc24.x86_64 #1 SMP Thu May 19 13:05:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pweil-** [comment]
@aweiteka should this be filed through support?

**Comment by yangjunsss** [comment]
I can to fix it like this:

```shell
sudo docker run -i --rm \
                --privileged \
                --net=host \
                -v /etc/atomic-registry/:/etc/atomic-registry/ \
                -v /var/lib/atomic-registry/:/var/lib/atomic-registry/ \
                -v /:/host \
                -e REGISTRYPORT=$REGISTRYPORT \
                -e MASTERPORT=$MASTERPORT \
                -e CONSOLEPORT=$CONSOLEPORT \
                -e REGISTRYIMAGE=$REGISTRYIMAGE \
                -e MASTERIMAGE=$MASTERIMAGE \
                -e CONSOLEIMAGE=$CONSOLEIMAGE \
                -e REGISTRYTAG=$REGISTRYTAG \
                -e MASTERTAG=$MASTERTAG \
                -e CONSOLETAG=$CONSOLETAG \
                --entrypoint /usr/bin/install.sh \
		 projectatomic/atomic-registry-install $REGISTRY_HOST
```

But I check the [Docker docs](https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose) that if no = is provided, then that variable’s current value, set via export, is passed through to the container. So why it doesn't work? Do I misunderstand?

**Comment by aweiteka** [comment]
> should this be filed through support?

This is only supported here in this upstream repo. I'll take a look.

**Comment by aweiteka** [comment]
I have reproduced your issue. You are thinking through this properly. It appears to be an issue with the atomic CLI but I'm not sure.

The method I have successfully used and would recommend as a workaround was to define the ENV vars inline with the CLI. In your case:

    sudo CONSOLEPORT=8080 atomic install projectatomic/atomic-registry-install $REGISTRY_HOST
Could you try this syntax? Does this work for you? Note: $REGISTRY_HOST is an argument to the atomic command so it is evaluated by the shell right away.

**Comment by aweiteka** [comment]
Atomic registry deployment is being deprecated in favor of better tested and maintained installation methods.

- [oc cluster up](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md) for non-production "try it out" or test deployments
- [openshift-ansible](http://www.projectatomic.io/blog/2017/05/oo-standalone-registry/) for more production use cases.

This reported issue will not be addressed.
