### ISSUE TITLE
Add tests for image signatures

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13698]
Currently the image signature code in origin is not covered by any tests except manual QE testing.
We should figure out how to:

1) Push a signature using "skopeo copy" tool and verify the signature was created successfully
2) Push a signature using "curl" command directly using the registry signature endpoint.
3) Get the signature using "curl" command from signature endpoint.
4) Remove signature from the image
5) Verify the image signature

(the 4) and 5) has to be done after https://github.com/openshift/origin/pull/13585 merges).

**Comment by dmage** [comment]
@stevekuznetsov how can I use skopeo in our end-to-end tests?

**Comment by stevekuznetsov** [comment]
Depends on how you want to use it. I would love to not add more Bash-based test suites unless we _need_ to. @mfojtik what is the requirement here? Can we get the Skopeo source on there and use their source in compiling Go-based tests? Do we need to install them as an RPM and use them on the command line?

**Comment by dmage** [comment]
Now we have unit tests TestSignatureGet and TestSignaturePut.
