### ISSUE TITLE
Question:    How i can run just api-server without UI

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#13690]
In latest version of openshift origin how can i run just openshift api server w/o  UI.

running origin-master-api   is also running UI  how can i just run api server?

**Comment by stevekuznetsov** [comment]
> running origin-master-api is also running UI

Can you be more clear on how you are starting the API? `openshift start master`?

**Comment by debianmaster** [comment]
Running these two separately 
```sh
openshift start master api 
openshift start master controllers
```
I'm trying to host Openshift webconsole UI separately  and point the webconsole to my api servers (this works)

But how do i  just start  openshift master api server w/o   UI  or  UI comes by default with api server?

**Comment by stevekuznetsov** [comment]
@jwforres or @liggitt would know better -- if I remember correctly there was a reference implementation putting the UI into a Pod but this would not allow for IE clients to reach it correctly.

**Comment by liggitt** [comment]
Omit the assetConfig stanza from the master-config.yaml file

**Comment by debianmaster** [comment]
@liggitt  @stevekuznetsov   thanks i will try omitting assetConfig

**Comment by pweil-** [comment]
@debianmaster looks like this is resolved.  Please feel free to reopen if that doesn't work for you.
