### ISSUE TITLE
Need a new role for signing images

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13697]
Currently only "cluster-admin" role can attach signature via curl to integrated Docker registry.
We need to have more finer-grained role that allows privileged users to perform signing without having extra privileges.

This will be something like "image-signer" role that can PUT signature and pull/push to any repository.

**Comment by mfojtik** [comment]
@miminar @enj PTAL the role name/intent.

**Comment by miminar** [comment]
What's wrong with the [existing system:image-signer](https://github.com/openshift/origin/blob/7811e4bdb79ea30900c430d7d875d8388ec56231/pkg/cmd/server/bootstrappolicy/constants.go#L77) role?

**Comment by mfojtik** [comment]
@miminar overlooked that, thanks! closing.
