### ISSUE TITLE
Treat external and managed images the same when pruning

### ISSUE THREAD

**Issue by miminar** [openshift/origin#13700]
Currently, `oadm prune images` work only on managed images. It made sense in the past because managed images were the only ones that stored blobs on registry's storage.

Nowadays, the registry mirrors blobs of external images locally (on demand), which grows its storage.

Moreover, consider an image stream with tag:

```
{
    "kind": "ImageStream",
    "apiVersion": "v1",
    "metadata": {
        "name": "ruby-ex",
        "namespace": "haowang1",
    },
    "spec": {
        "tags": [...]
    },
    "status": {
        "dockerImageRepository": "172.30.144.247:5000/haowang1/ruby-ex",
        "tags": [
            {
                "tag": "latest",
                "items": [
                    {
                        "dockerImageReference": "registry.example.org/nm/ruby-ex@sha256:3281b0a06aee05cd59a39e1195b588f61a891f4c8d5bfc686eb83b3f5bde1b9d",
                    },
                    {
                        "dockerImageReference": "registry.example.org/nm/ruby-ex@sha256:8b5970d5d1b974abd070e2ba684f47e7c4cd118a745b039cfced4f6d1df70e3f",
                    },
                    {
                        "dockerImageReference": "registry.example.org/nm/ruby-ex@sha256:9fdab34fe4de1c8da70a139a8ea8b67a876215e7766e29701de87ab06b3970a5",
                    }
                ]
            },
        ]
    }
}
```

All of the tagged images are external, imported periodically.

With command `oadm prune images --keep-tag-revisions=1 --confirm` no image, not even tag will be removed. If they were managed, only the first image would have stayed. With the current approach of ignoring external images during pruning, the `ruby-ex:latest` image stream tag will keep growing - possibly with new mirrored blobs filling up the registry's storage. Worse, it will fill etcd as well.

I don't see a reason for differentiating external and managed images during the pruning anymore.

@smarterclayton are you ok with pruning external images?
@legionus, @dmage  FYI

**Comment by smarterclayton** [comment]
I'm ok with pruning external images now.
