### ISSUE TITLE
OpenShift becomes unresponsive after suspending laptop

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#1370]
Fedora 20
OpenShift V 0.4.1

Started openshift with:
 sudo ./openshift start &> /tmp/openshift.log &

Suspended my Lenovo T440s (closed the lid)
After coming back to life I get this:

spousty@localhost openshift$ ./osc describe service docker-registry
F0318 14:19:27.292608    2245 describe.go:47] Get https://192.168.1.119:8443/api/v1beta1/services/docker-registry?namespace=default: dial tcp 192.168.1.119:8443: i/o timeout
spousty@localhost openshift$ ./osc describe service docker-registry
F0318 14:20:03.717867    2525 describe.go:47] Get https://192.168.1.119:8443/api/v1beta1/services/docker-registry?namespace=default: dial tcp 192.168.1.119:8443: i/o timeout

I killed it by killing all processes. Started it back up and get this:

spousty@localhost openshift$ ./osc describe service docker-registry
Name:			docker-registry
Labels:			docker-registry=default
Selector:		docker-registry=default
IP:			172.30.17.49
Port:			5000
Endpoints:		<none>
Session Affinity:	None

**Comment by smarterclayton** [comment]
At a minimum the cluster is too fragile to IP changes on the master.  We should be using cluster DNS to get the master IPs where possible.

**Comment by brenton** [comment]
@smarterclayton, should we remove the 0.5.0 milestone from this?

**Comment by smarterclayton** [comment]
I think pointing to an ip is fragile, and it's not a small fix.

**Comment by brenton** [comment]
Given 0.5.0 is scheduled for tomorrow I'm going to label this 0.6.0 then.

**Comment by smarterclayton** [comment]
This error is now manifesting with 

```
E0427 10:29:58.686286   19421 reflector.go:119] Failed to list *api.Namespace: "/api/v1beta3/namespaces" is forbidden because system:kube-client cannot list on namespaces in 
E0427 10:29:58.886226   19421 reflector.go:119] Failed to list *api.ResourceQuota: "/api/v1beta3/resourcequotas" is forbidden because system:kube-client cannot list on resourcequotas in 
```

@deads2k @liggitt are our cert/auth path now suddenly more sensitive to IPs?  

Scenario 

1. have running openshift system
2. change host IP (wireless)
3. stop openshift
4. start openshift

At this point openshift does not start.

**Comment by smarterclayton** [comment]
Deleting the certs and restarting does not fix the problem.

**Comment by derekwaynecarr** [comment]
So this looks like an admission handler, or some other controller (resource_controller.go?) that is just trying to build a local cache.  Did we recently change how we construct internal clients for admission handlers and internal controllers?  Maybe you need to reset your local policy.json?

**Comment by liggitt** [comment]
Nothing's changed with IP/cert stuff.... on restart, new server certs will be generated if needed to pick up new IP addresses, but the CA and old client certs will continue working.

**Comment by smarterclayton** [comment]
Ok, so then this is a policy issue or policy cache issue.  What's my debug steps?

**Comment by derekwaynecarr** [comment]
@deads2k ?

**Comment by deads2k** [comment]
> Ok, so then this is a policy issue or policy cache issue. What's my debug steps?

```
osc describe policy default --namespace=master --config=openshift.local.certificates/admin/.kubeconfig 
osc describe policybindings master --namespace=master --config=openshift.local.certificates/admin/.kubeconfig
```

You should see something like this:
```
RoleBinding[system:components]:			 
						Role:	system:component
						Users:	[system:kube-client system:openshift-client]
						Groups:	[system:nodes]
```

That indicates that the `system:kube-client` user (the one from your messages) has rights to do * on *.  If you have that, then it's unlikely that this caused your server to not start, but a gist of the log showing which controller is failing might be useful.

**Comment by smarterclayton** [comment]
They're all failing, although the next time it happens i'll check again.

----- Original Message -----

**Comment by smarterclayton** [comment]
It was the policy.json file.  Renaming it allowed start to proceed.  Why is policy.json on disk blocking my all in one from starting?

**Comment by deads2k** [comment]
> It was the policy.json file. Renaming it allowed start to proceed. Why is policy.json on disk blocking my all in one from starting?

We try to write to the file.  It seems unlikely that the file was locked (`ioutil.WriteFile` looks good), but I guess it's possible.  Do you still have the stack from when it was stuck?

**Comment by smarterclayton** [comment]
I don't have a stack, no.  It's preventing policy from being correct for some reason.

----- Original Message -----

**Comment by danmcp** [comment]
@thesteve0 Are you able to recreate still?

**Comment by smarterclayton** [comment]
This is still a problem and is high severity.  IP address changes result in an unusable deployment or default config.  However, it only occurs when an IP changes which is not a production scenario (today).

----- Original Message -----

**Comment by thesteve0** [comment]
Assuming that clayton's response covers it. Please let me know if you need
me to try and reproduce as well
Thanks
Steve

**Comment by stevekuznetsov** [comment]
@smarterclayton @danmcp Is this reproducible? I just restructured the policy & auth caches ( #2539 ) so I can look at this.

**Comment by danmcp** [comment]
@stevekuznetsov I believe so.

**Comment by stevekuznetsov** [comment]
@danmcp this has nothing to do with the policy cache, I won't be effective at looking at it

**Comment by smarterclayton** [comment]
I believe he considers this a learning experience.

**Comment by ncdc** [comment]
Here's my openshift.log after suspending, waiting about half an hour, resuming, and killing with SIGABRT: https://gist.githubusercontent.com/ncdc/d112dd2084612f65a250/raw/6986e8fcf4249edc6fddaacc9c219afecdc91d39/openshift.log

**Comment by smarterclayton** [comment]
Might be cAdvisor parsing oomkill logs and getting some very slow behavior from the journal:

```
goroutine 1121 [syscall]:
syscall.Syscall(0x0, 0xc4, 0xc20a06f000, 0x1000, 0x73, 0x1000, 0x0)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:21 +0x5 fp=0xc20bda0380 sp=0xc20bda0378
syscall.read(0xc4, 0xc20a06f000, 0x1000, 0x1000, 0x73, 0x0, 0x0)
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:867 +0x6e fp=0xc20bda03c8 sp=0xc20bda0380
syscall.Read(0xc4, 0xc20a06f000, 0x1000, 0x1000, 0x73, 0x0, 0x0)
	/usr/lib/golang/src/syscall/syscall_unix.go:136 +0x58 fp=0xc20bda0408 sp=0xc20bda03c8
os.(*File).read(0xc208fb3700, 0xc20a06f000, 0x1000, 0x1000, 0x80, 0x0, 0x0)
	/usr/lib/golang/src/os/file_unix.go:191 +0x5e fp=0xc20bda0448 sp=0xc20bda0408
os.(*File).Read(0xc208fb3700, 0xc20a06f000, 0x1000, 0x1000, 0x7f2c7418f340, 0x0, 0x0)
	/usr/lib/golang/src/os/file.go:95 +0x91 fp=0xc20bda04a0 sp=0xc20bda0448
bufio.(*Reader).fill(0xc20a65ae40)
	/usr/lib/golang/src/bufio/bufio.go:97 +0x1ce fp=0xc20bda0548 sp=0xc20bda04a0
bufio.(*Reader).ReadSlice(0xc20a65ae40, 0xc20a06f00a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:295 +0x257 fp=0xc20bda0590 sp=0xc20bda0548
bufio.(*Reader).ReadBytes(0xc20a65ae40, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:374 +0xd2 fp=0xc20bda06b0 sp=0xc20bda0590
bufio.(*Reader).ReadString(0xc20a65ae40, 0xc208d88f0a, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:414 +0x58 fp=0xc20bda0708 sp=0xc20bda06b0
github.com/google/cadvisor/utils/oomparser.readLinesFromFile(0xc208d88f60, 0xc20a65ae40)
	/home/vagrant/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/google/cadvisor/utils/oomparser/oomparser.go:113 +0x6e fp=0xc20bda07c8 sp=0xc20bda0708
github.com/google/cadvisor/utils/oomparser.func·001()
	/home/vagrant/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/google/cadvisor/utils/oomparser/oomparser.go:138 +0x39 fp=0xc20bda07e0 sp=0xc20bda07c8
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20bda07e8 sp=0xc20bda07e0
created by github.com/google/cadvisor/utils/oomparser.(*OomParser).StreamOoms
	/home/vagrant/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/google/cadvisor/utils/oomparser/oomparser.go:139 +0x10e
```

**Comment by ncdc** [comment]
Super easy way to reproduce:

1. Start OpenShift
2. Send SIGSTOP to OpenShift pid
3. Advance date of your system by 1 day
4. Send SIGCONT to OpenShift pid
5. Watch CPU spike now

**Comment by smarterclayton** [comment]
great.

On Thu, Sep 10, 2015 at 9:15 AM, Andy Goldstein <notifications@github.com>
wrote:

> Super easy way to reproduce:
>
>    1. Start OpenShift
>    2. Send SIGSTOP to OpenShift pid
>    3. Advance date of your system by 1 day
>    4. Send SIGCONT to OpenShift pid
>    5. Watch CPU spike now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/1370#issuecomment-139231043>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment]
(note to self) isolate by stopping/continuing:
* master api (against external etcd)
* master controllers (against external etcd)
* just node (no pods)
* just node (with pods)

**Comment by ncdc** [comment]
I'm pretty sure this is an upstream issue, as I've seen it with pure
Kubernetes before.

**Comment by smarterclayton** [comment]
I hope this is a clock issue.  I really do.

On Sep 10, 2015, at 11:10 AM, Andy Goldstein <notifications@github.com>
wrote:

I'm pretty sure this is an upstream issue, as I've seen it with pure
Kubernetes before.

On Thu, Sep 10, 2015 at 11:09 AM, Jordan Liggitt <notifications@github.com>
wrote:

> (note to self) isolate by stopping/continuing:
>
> - master api (against external etcd)
> - master controllers (against external etcd)
> - just node (no pods)
> - just node (with pods)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/1370#issuecomment-139274900>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/1370#issuecomment-139275282>.

**Comment by liggitt** [comment]
It's definitely in the node. You don't even have to suspend the process, just advance the system clock by a day while running. With loglevel=5, it immediately started spewing:
```
I0911 22:46:11.938037   24253 container.go:383] [/system.slice/dbus.service] Housekeeping took 107.894516ms
I0911 22:46:11.938177   24253 container.go:383] [/system.slice/upower.service] Housekeeping took 150.162803ms
I0911 22:46:11.938508   24253 container.go:383] [/system.slice/avahi-daemon.service] Housekeeping took 160.158069ms
I0911 22:46:11.959288   24253 container.go:383] [/docker-daemon] Housekeeping took 161.017795ms
I0911 22:46:11.959625   24253 container.go:383] [/user.slice] Housekeeping took 101.244414ms
I0911 22:46:11.989376   24253 container.go:383] [/system.slice/NetworkManager.service] Housekeeping took 140.064894ms
I0911 22:46:12.000361   24253 container.go:383] [/system.slice/abrt-oops.service] Housekeeping took 191.674165ms
I0911 22:46:12.003182   24253 container.go:383] [/system.slice/auditd.service] Housekeeping took 195.563892ms
I0911 22:46:11.922044   24253 container.go:383] [/system.slice/rngd.service] Housekeeping took 163.990542ms
I0911 22:46:11.922075   24253 container.go:383] [/system.slice/systemd-timedated.service] Housekeeping took 153.932112ms
I0911 22:46:12.052215   24253 container.go:383] [/system.slice/packagekit.service] Housekeeping took 235.048979ms
I0911 22:46:12.061843   24253 container.go:383] [/] Housekeeping took 204.425684ms
I0911 22:46:12.069962   24253 container.go:383] [/kubelet] Housekeeping took 132.437336ms
I0911 22:46:12.110206   24253 container.go:383] [/system.slice/gdm.service] Housekeeping took 111.453078ms
I0911 22:46:12.150436   24253 container.go:383] [/user.slice] Housekeeping took 171.586431ms
I0911 22:46:12.180271   24253 container.go:383] [/system.slice/upower.service] Housekeeping took 150.664434ms
I0911 22:46:12.194863   24253 container.go:383] [/system.slice/avahi-daemon.service] Housekeeping took 164.648624ms
I0911 22:46:12.213445   24253 container.go:383] [/system.slice/NetworkManager.service] Housekeeping took 183.515976ms
I0911 22:46:12.230136   24253 container.go:383] [/system.slice/rngd.service] Housekeeping took 106.936878ms
I0911 22:46:12.236386   24253 container.go:383] [/system.slice/rsyslog.service] Housekeeping took 214.080241ms
I0911 22:46:12.246367   24253 container.go:383] [/system.slice/packagekit.service] Housekeeping took 127.433194ms
I0911 22:46:12.246796   24253 container.go:383] [/kubelet] Housekeeping took 107.299327ms
I0911 22:46:12.246874   24253 container.go:383] [/system.slice/systemd-timedated.service] Housekeeping took 215.967504ms
I0911 22:46:12.269024   24253 container.go:383] [/system.slice/geoclue.service] Housekeeping took 337.642907ms
I0911 22:46:12.271216   24253 container.go:383] [/system.slice/libvirtd.service] Housekeeping took 121.741809ms
I0911 22:46:12.271466   24253 container.go:383] [/system.slice/systemd-logind.service] Housekeeping took 240.667755ms
I0911 22:46:12.271811   24253 container.go:383] [/system.slice/irqbalance.service] Housekeeping took 122.182466ms
I0911 22:46:12.291648   24253 container.go:383] [/system.slice/auditd.service] Housekeeping took 259.578619ms
I0911 22:46:12.302568   24253 container.go:383] [/system.slice/abrt-oops.service] Housekeeping took 142.697159ms
I0911 22:46:12.311871   24253 container.go:383] [/] Housekeeping took 134.144502ms
I0911 22:46:12.321353   24253 container.go:383] [/system.slice/accounts-daemon.service] Housekeeping took 107.389335ms
I0911 22:46:12.321771   24253 container.go:383] [/system.slice/dbus.service] Housekeeping took 292.156299ms
I0911 22:46:12.331817   24253 container.go:383] [/docker-daemon] Housekeeping took 301.08741ms
I0911 22:46:12.351599   24253 container.go:383] [/system.slice/NetworkManager.service] Housekeeping took 129.670562ms
I0911 22:46:12.361763   24253 container.go:383] [/system.slice/polkit.service] Housekeeping took 116.156323ms
```

**Comment by smarterclayton** [comment]
I blame cadvisor

On Sep 10, 2015, at 10:49 PM, Jordan Liggitt <notifications@github.com>
wrote:

It's definitely in the node. You don't even have to suspend the process,
just advance the system clock by a day while running. With loglevel=5, it
immediately started spewing:

I0911 22:46:11.938037   24253 container.go:383]
[/system.slice/dbus.service] Housekeeping took 107.894516ms
I0911 22:46:11.938177   24253 container.go:383]
[/system.slice/upower.service] Housekeeping took 150.162803ms
I0911 22:46:11.938508   24253 container.go:383]
[/system.slice/avahi-daemon.service] Housekeeping took 160.158069ms
I0911 22:46:11.959288   24253 container.go:383] [/docker-daemon]
Housekeeping took 161.017795ms
I0911 22:46:11.959625   24253 container.go:383] [/user.slice]
Housekeeping took 101.244414ms
I0911 22:46:11.989376   24253 container.go:383]
[/system.slice/NetworkManager.service] Housekeeping took 140.064894ms
I0911 22:46:12.000361   24253 container.go:383]
[/system.slice/abrt-oops.service] Housekeeping took 191.674165ms
I0911 22:46:12.003182   24253 container.go:383]
[/system.slice/auditd.service] Housekeeping took 195.563892ms
I0911 22:46:11.922044   24253 container.go:383]
[/system.slice/rngd.service] Housekeeping took 163.990542ms
I0911 22:46:11.922075   24253 container.go:383]
[/system.slice/systemd-timedated.service] Housekeeping took
153.932112ms
I0911 22:46:12.052215   24253 container.go:383]
[/system.slice/packagekit.service] Housekeeping took 235.048979ms
I0911 22:46:12.061843   24253 container.go:383] [/] Housekeeping took
204.425684ms
I0911 22:46:12.069962   24253 container.go:383] [/kubelet]
Housekeeping took 132.437336ms
I0911 22:46:12.110206   24253 container.go:383]
[/system.slice/gdm.service] Housekeeping took 111.453078ms
I0911 22:46:12.150436   24253 container.go:383] [/user.slice]
Housekeeping took 171.586431ms
I0911 22:46:12.180271   24253 container.go:383]
[/system.slice/upower.service] Housekeeping took 150.664434ms
I0911 22:46:12.194863   24253 container.go:383]
[/system.slice/avahi-daemon.service] Housekeeping took 164.648624ms
I0911 22:46:12.213445   24253 container.go:383]
[/system.slice/NetworkManager.service] Housekeeping took 183.515976ms
I0911 22:46:12.230136   24253 container.go:383]
[/system.slice/rngd.service] Housekeeping took 106.936878ms
I0911 22:46:12.236386   24253 container.go:383]
[/system.slice/rsyslog.service] Housekeeping took 214.080241ms
I0911 22:46:12.246367   24253 container.go:383]
[/system.slice/packagekit.service] Housekeeping took 127.433194ms
I0911 22:46:12.246796   24253 container.go:383] [/kubelet]
Housekeeping took 107.299327ms
I0911 22:46:12.246874   24253 container.go:383]
[/system.slice/systemd-timedated.service] Housekeeping took
215.967504ms
I0911 22:46:12.269024   24253 container.go:383]
[/system.slice/geoclue.service] Housekeeping took 337.642907ms
I0911 22:46:12.271216   24253 container.go:383]
[/system.slice/libvirtd.service] Housekeeping took 121.741809ms
I0911 22:46:12.271466   24253 container.go:383]
[/system.slice/systemd-logind.service] Housekeeping took 240.667755ms
I0911 22:46:12.271811   24253 container.go:383]
[/system.slice/irqbalance.service] Housekeeping took 122.182466ms
I0911 22:46:12.291648   24253 container.go:383]
[/system.slice/auditd.service] Housekeeping took 259.578619ms
I0911 22:46:12.302568   24253 container.go:383]
[/system.slice/abrt-oops.service] Housekeeping took 142.697159ms
I0911 22:46:12.311871   24253 container.go:383] [/] Housekeeping took
134.144502ms
I0911 22:46:12.321353   24253 container.go:383]
[/system.slice/accounts-daemon.service] Housekeeping took 107.389335ms
I0911 22:46:12.321771   24253 container.go:383]
[/system.slice/dbus.service] Housekeeping took 292.156299ms
I0911 22:46:12.331817   24253 container.go:383] [/docker-daemon]
Housekeeping took 301.08741ms
I0911 22:46:12.351599   24253 container.go:383]
[/system.slice/NetworkManager.service] Housekeeping took 129.670562ms
I0911 22:46:12.361763   24253 container.go:383]
[/system.slice/polkit.service] Housekeeping took 116.156323ms

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/1370#issuecomment-139435139>.

**Comment by liggitt** [comment]
I blame housekeeping tick calculation

**Comment by liggitt** [comment]
also, commenting on github while advancing your system clock is disconcerting
![20150911_224950_time](https://cloud.githubusercontent.com/assets/980082/9806123/b8d1bfc2-580e-11e5-812c-0637b18fe6c6.png)

**Comment by liggitt** [comment]
kudos to @ncdc for the easy recreation steps
