### ISSUE TITLE
serviceaccount OAuth client docs led me to believe I could specify a protocol-less redirect URI

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13706]
Docs https://docs.openshift.com/container-platform/3.4/architecture/additional_concepts/authentication.html#redirect-uris-for-service-accounts imply that I can do:

```
serviceaccounts.openshift.io/oauth-redirecturi.first=//127.0.0.1:4180/oauth2/callback
```

I can't.  But it would be useful.

@enj

**Comment by enj** [comment]
I believe you are trying to default the scheme with a static URI?

We default it to `https` only for dynamic URIs.  For static URIs we only do validation - no defaulting.  I forget @liggitt 's reasoning behind it.  Probably something along the lines of no magic with static URIs.

**Comment by liggitt** [comment]
How is that useful? You should know whether that is serving http or https and you have to explicitly indicate it if you want it to work with the browser

**Comment by smarterclayton** [comment]
Because otherwise I have to do:

```
serviceaccounts.openshift.io/oauth-redirecturi.first=https://127.0.0.1:4180/oauth2/callback
serviceaccounts.openshift.io/oauth-redirecturi.first=http://127.0.0.1:4180/oauth2/callback
```

Which we several lines down say "oh this works great for when you're doing a reference".  Not clear to me why we'd make a big deal about it for references but not for static URLs.
