### ISSUE TITLE
cadvisor spams logs

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#13719]
cadvisor spams when it finds more than one filesystem a message that scares people.

```
Apr 11 20:29:36 ip-172-31-56-130.ec2.internal atomic-openshift-node[40301]: I0411 20:29:36.352561   40301 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
```

it should stop spamming.

**Comment by derekwaynecarr** [comment]
per @eparis request.

**Comment by eparis** [comment]
online clusters see more that x1000 times per hour in the logs. Which starves out useful messages.
