### ISSUE TITLE
[POST-REBASE] oc version gives error when there is no connection to last server connected

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#13716]
I have connected to a server that I provisioned in the cloud with "oc login". After the server has been destroyed, I have tried to verify the version of my client, and got unexpected output.

````
$ oc version
oc v3.6.0-alpha.0+0343989
kubernetes v1.5.2+43a9be4
features: Basic-Auth
Unable to connect to the server: dial tcp: lookup console.jorge.pixy.io on 8.8.8.8:53: no such host
````
Similar issue can happen if the cluster is down or not accessible.

There should be a way to specify to check only the version of the client, and not of the server being connected, something like "oc version --local" 

I consider this a bug, and I think that being able to get the version of just the client should be mandatory.

**Comment by fabianofranz** [comment]
The `--client` flag now exists upstream, waiting for the next Kube rebase.

**Comment by jorgemoralespou** [comment]
It's sad that it's not the default behavior, and that the flag is not
really --server.

Thanks for the update.
