### ISSUE TITLE
TestConcurrentBuildPodControllers flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#13712]
```
--- FAIL: TestConcurrentBuildPodControllers (55.15s)
	controllers.go:312: running state test: Did not reach desired build state: Running
	etcd.go:99: dumping etcd to "/tmp/openshift/test-integration/etcd-dump-TestConcurrentBuildPodControllers.json"
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/994

thought we already had a flake issue for this, but i can't find it..feel free to close if there is one.

**Comment by csrwng** [comment]
dup of https://github.com/openshift/origin/issues/13650

**Comment by bparees** [comment]
man, my search must have been terrible, dunno why it didn't find that :(
