### ISSUE TITLE
docker-registry is in pending state

### ISSUE THREAD

**Issue by naveenkumartangallapally** [openshift/origin#13711]
I setup my openshift origin environment using below

root@cgdell72-Lenovo-B50-80:~# oc version
oc v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.1.33:8443
openshift v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4

after dashboard luanched succsessfully but my docker registry and router are in pending state.

i am getting below error from logs:
root@cgdell72-Lenovo-B50-80:~# oc volume dc/docker-registry --list
Flag --list has been deprecated, Volumes and volume mounts can be listed by providing a resource with no additional options.
Error from server (NotFound): deploymentconfigs "docker-registry" not found

**Comment by pweil-** [comment]
> Error from server (NotFound): deploymentconfigs "docker-registry" not found

Hi Naveen.  This states that the dc you are looking for is not there.  Use `oc get dc` to show all deployment configs.  Please make sure you are in the namespace you created it in originally or use `--namespace` on your command to specify the specific namespace.

Please also check the events in the namespace for errors.

**Comment by naveenkumartangallapally** [comment]
root@cgdell72-Lenovo-B50-80:~# oc get dc
No resources found.
root@cgdell72-Lenovo-B50-80:~# 

but "./openshift start"  has started the deployment of docker registry, which i can see in the UI
![docker registry](https://cloud.githubusercontent.com/assets/25741747/24914266/5e9382ce-1ef1-11e7-9ee5-aa8e17b59863.png)

**Comment by naveenkumartangallapally** [comment]
root@cgdell72-Lenovo-B50-80:~/openshift-origin-client-tools-v1.5.0-rc.0-49a4a7a-linux-32bit# service docker restart 
docker stop/waiting
docker start/running, process 5125
root@cgdell72-Lenovo-B50-80:~/openshift-origin-client-tools-v1.5.0-rc.0-49a4a7a-linux-32bit# oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... 
   WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.0-rc.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... 
   WARNING: Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients.
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.1.33 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.1.33:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

**Comment by pweil-** [comment]
Make sure when you run the `oc get dc` command you are in the default project.  `oc project` will tell you what project you are currently using.  If you need to log in as an admin to get access to the default project you can use the command listed in the `oc cluster up` output as shown above.

Also check the logs of the deployment and the events in the namespace.

**Comment by naveenkumartangallapally** [comment]
Now i went to "default" project as an admin and got the deployments.. Thanks for that info :) 
root@cgdell72-Lenovo-B50-80:~# oc get dc
NAME              REVISION   DESIRED   CURRENT   TRIGGERED BY
docker-registry   1          1         0         config
router            1          1         0         config
root@cgdell72-Lenovo-B50-80:~# 

Also, I found the below logs for the openshift container... 
root@cgdell72-Lenovo-B50-80:~# docker ps 
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS               NAMES
ae01a36ae996        openshift/origin:v1.5.0-rc.0   "/usr/bin/openshif..."   3 hours ago         Up 3 hours                              origin
root@cgdell72-Lenovo-B50-80:~#
root@cgdell72-Lenovo-B50-80:~# docker logs ae01a36ae996
...
E0411 14:35:09.690700    5694 pod_workers.go:184] Error syncing pod 90e143dd-1ea7-11e7-aa6c-1c3947271533, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: docker: failed to parse docker version \"17.03.1-ce\": illegal zero-prefixed version component \"03\" in \"17.03.1-ce\""
root@cgdell72-Lenovo-B50-80:~# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@cgdell72-Lenovo-B50-80:~# 
root@cgdell72-Lenovo-B50-80:~# docker ps 
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS               NAMES
ae01a36ae996        openshift/origin:v1.5.0-rc.0   "/usr/bin/openshif..."   3 hours ago         Up 3 hours                              origin
root@cgdell72-Lenovo-B50-80:~# 


is it required to have specific version of docker??

**Comment by pweil-** [comment]
Thanks @naveenkumartangallapally.  Looks like you are running in to https://github.com/openshift/origin/issues/13281 which needs to be resolved upstream.  You will need to downgrade your docker for now per [the current workaround](https://github.com/openshift/origin/issues/13281#issuecomment-290693519)

**Comment by naveenkumartangallapally** [comment]
which docker version i need to downgrade?
we have 2 fields for version in "docker version"
Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
i believe the problem is with 17.03  according to the logs. should this be downgraded to 1.12?

**Comment by pweil-** [comment]
Yes, the 17.03.1-ce is causing a parsing error.  Downgrading to 1.12 should fix it.

**Comment by mbn18** [comment]
Same problem. To work with latest docker I reverted to older image `openshift/origin:v1.4.1`

version:

	oc v1.4.1+3f9807a
	kubernetes v1.4.0+776c994
	features: Basic-Auth GSSAPI Kerberos SPNEGO

	Server https://192.168.1.100:8443
	openshift v1.4.1+3f9807a
	kubernetes v1.4.0+776c994
