### ISSUE TITLE
REST spam

### ISSUE THREAD

**Issue by eparis** [openshift/origin#13724]
Online runs masters with `--v=2`.

We should ask upstream to reconsider moving the API call tracing to V(3) at least. If they are unwilling we need to change it in OpenShift. 65% of OpenShift online logs look like:
```
panics.go:76] GET /api/v1/namespaces/[snip]/replicationcontrollers: (1.778871ms) 200 [[openshift/v1.5.2+43a9be4 (linux/amd64) kubernetes/43a9be4] 172.31.56.130:33182]
```
These need to go away to make online logs useful again.

**Comment by ncdc** [comment]
This is https://github.com/kubernetes/kubernetes/pull/40933, which has not been accepted upstream yet. I just commented on that hoping that we can convince them that it's acceptable.
