### ISSUE TITLE
S2I builds fail on `oc cluster up` with new Docker

### ISSUE THREAD

**Issue by marekjelen** [openshift/origin#13733]
Using `oc cluster up` on macOS with Docker 

```
Version 17.03.1-ce-mac5 (16048)
Channel: stable
b18e2a50cc
```

fails on creating new pod for s2i build.

##### Version
```
oc v3.6.0-alpha.0+0343989
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.0+0343989
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. oc cluster up
2. oc new-app ruby~https://github.com/gshipley/openshift-workshops-1.git
3. oc describe build openshift-workshops-1-1

##### Current Result

Build events report 

```
Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: docker: failed to parse docker version \"17.03.1-ce\": illegal zero-prefixed version component \"03\" in \"17.03.1-ce\""
```

##### Expected Result

OpenShift should start s2i build.

**Comment by bparees** [comment]
@marekjelen i think this is fixed in master, alternatively you will need to downgrade your docker to a 1.xx version.  Docker changed their versioning scheme and broke us.

**Comment by balsmn** [comment]
If it is fixed in the latest master, do we have a corresponding openshift/origin docker image containing the fix? I tried the openshift/origin:lastest (on 21.04.2017) and still got the same error.

**Comment by csrwng** [comment]
Only the cluster up issue is fixed in master. This is an issue with the kubelet. It will be fixed in the final 1.5 release of origin and when we rebase on the latest kubernetes for 1.6. In the meantime, the easiest thing to do is to downgrade to a Docker version that works:

https://download.docker.com/mac/stable/1.13.1.15353/Docker.dmg

**Comment by balsmn** [comment]
Thanks for the message. Any approx time line when one can expect the final 1.5?

**Comment by bparees** [comment]
@smarterclayton would best be able to answer that (ETA for 1.5final)

**Comment by balsmn** [comment]
Thanks @smarterclayton. I saw your release of 1.5 final on Friday and I got the pod up and running locally.

**Comment by bparees** [comment]
@marekjelen sounds like this should be working in the 1.5 final release.  please let us know if you still have issues.
