### ISSUE TITLE
Master composition

### ISSUE THREAD

**Issue by soufiane8096** [openshift/origin#13736]
Hi,

I looked for some information about master, but I didn't find answers in documentation/forum ... : 
-/ What is a master ? it's a particular node .. Ok !
 A Node run pods which encapsultate containers and mostly docker image. But there is no indication if the services covered by a master are run in pods too ? If i have only one master and a service goes down, it will try to restart ? There is something to restart it ? How is it managed ? 

Please give me some clarification if you can !

Thank you for your answers !

**Comment by stevekuznetsov** [comment]
There is a [specific section](https://docs.openshift.org/latest/architecture/infrastructure_components/kubernetes_infrastructure.html#master) in our documentation about the masters, but I think you should start by reading the [overview](https://docs.openshift.org/latest/architecture/index.html) for the OpenShift v3 architecture.

**Comment by soufiane8096** [comment]
Thank you for your answers ! You're ritght, I red a PDF documentation not this one. Thanks ;)
