### ISSUE TITLE
oc import-image tls: handshake failure

### ISSUE THREAD

**Issue by hobti01** [openshift/origin#13735]
I'm unable to create an image stream from a tag in a private, remote registry.
```
# oc import-image my.registry/my-image:0.1 --confirm
The import completed with errors.
Name:                   my-image
Namespace:              default
Created:                10 minutes ago
Labels:                 <none>
Annotations:            openshift.io/image.dockerRepositoryCheck=2017-04-12T12:35:54Z
Docker Pull Spec:       172.30.244.222:5000/default/my-image
Unique Images:          0
Tags:                   1
0.1
  tagged from my.registry/my-image:0.1
  ! error: Import failed (InternalError): Internal error occurred: Get https://my.registry/v2/: remot
e error: tls: handshake failure
      10 minutes ago
```
The docker daemon has been configured correctly and can successfully pull images.

##### Version
```
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://10.132.0.2:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994
```

##### Steps To Reproduce
1. Have an external, private registry requiring client certificates for TLS and username/password for authentication
2. Configure docker to access the registry
```
# ls /etc/docker/certs.d/my.registry/
ca.crt client.cert client.key
```
3. Confirm that docker can pull the image
```
# docker pull my.registry/my-image:0.1
Trying to pull repository my.registry/my-image ... 
0.1: Pulling from my.regsitry/my-image
ee4aeaf2fc2d: Pull complete 
...
Digest: sha256:2490277653dcf0cc5d79d89f3a4e13d2e8dad8a252f8ce6bcedae0200db5f646
```
4. Import image
```
# oc import-image my.registry/my-image:0.1 --confirm
The import completed with errors.
...
  ! error: Import failed (InternalError): Internal error occurred: Get https://my.registry/v2/: remot
e error: tls: handshake failure
```

##### Current Result
TLS handshake error

##### Expected Result
Image stream created and image imported

##### Additional Information
The registry only supports the TLSv1 protocol.  TLSv1.2 and SSLv3 are not available.

**Comment by kawaffels** [comment]
@hobti01 We just hit the same issue.  Did you manage fix it / find a workaround?

**Comment by hobti01** [comment]
@kawaffels unfortunately this never received any resolution.  We were not able to use OpenShift ImageStreams. :(

**Comment by kawaffels** [comment]
Lets hope, that it's going to be fixed in future releases ...
