### ISSUE TITLE
Collapse config change triggers into the main DC controller

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#13763]
Once https://github.com/openshift/origin/pull/13242 is merged, we can move the CCT mechanism from the deployment trigger controller into the main DC controller and switch the former controller off.

**Comment by kargakis** [comment]
The blue peak is 400s from instantiate as per @smarterclayton. Those are coming from the deployment trigger controller most likely (what else). This issue should fix that peak so I am adding this to the 3.7 milestone.
![unnamed](https://user-images.githubusercontent.com/3900799/27013598-2ae1b830-4ee7-11e7-85a3-a91ab42fa65d.png)

**Comment by kargakis** [comment]
Those are API server errors during the 3.5->3.6 upgrade btw

**Comment by kargakis** [comment]
@mfojtik this is the issue I mentioned today. 400s by instantiate is the #1 error coming from our API server. Collapsing the deployment trigger controlller in the main controller, ought to fix it since we will stop using instantiate in the controller.

**Comment by mfojtik** [comment]
+1 we have to fix this, on my 3.7 list

**Comment by kargakis** [comment]
Fixed by https://github.com/openshift/origin/pull/14910 🎉
