### ISSUE TITLE
Atomic-Registry-Console port 9090 is conflict with Fedora admin console port tcp/9090 

### ISSUE THREAD

**Issue by yangjunsss** [openshift/origin#13769]
Fedora24 is using cockpit.socket service in tcp/9090, I try to change exposed port to 8080 via the  ```CONSOLEPORT``` var but it doesn't work. The containers starting logs as belows:
```shell
Apr 14 14:45:50 i-c5fr3igr docker[1694]: cockpit-ws: Error starting web server: Failed to bind to port 9090: Error binding to address: Address already in use
Apr 14 14:45:56 i-c5fr3igr docker[1694]: INFO: cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Apr 14 14:45:56 i-c5fr3igr docker[1694]: cockpit-ws: Error starting web server: Failed to bind to port 9090: Error binding to address: Address already in use
Apr 14 14:46:02 i-c5fr3igr docker[1694]: INFO: cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Apr 14 14:46:02 i-c5fr3igr docker[1694]: cockpit-ws: Error starting web server: Failed to bind to port 9090: Error binding to address: Address already in use
```

The start cmd is : ``` ExecStart=/usr/bin/docker run --rm --env-file=/etc/sysconfig/atomic-registry-console --name atomic-registry-console -p ${CONSOLEPORT}:${CONSOLEPORT} -u 1001 ${CONSOLEIMAGE}:${CONSOLETAG} ```

$CONSOLEPORT is 8080

env:
```shell
[root@i-c5fr3igr bin]# atomic -v
1.14.1
[root@i-c5fr3igr bin]# docker -v
Docker version 1.10.3, build 667d6d1/1.10.3
```

Any comments?  My workaround way is to stop it via ```sudo systemctl disable cockpit.socket```

**Comment by mfojtik** [comment]
@aweiteka feel free to move this issue to the registry console repo (always forget whos the main contact for that ;-).

**Comment by aweiteka** [comment]
> My workaround way is to stop it via sudo systemctl disable cockpit.socket

The container exposes port 9090 either way. The CONSOLEPORT env var only affects the mapping of the container port.

@petervo is there a flag to launch docker.io/cockpit/kubernetes to expose another port? Ideally using an environment variable. Basically this docker run command fails -p 8080:9090 when cockpit is already running on the host so we need to enable something like -p 8080:8080 for the registry console use case.

**Comment by aweiteka** [comment]
Atomic registry deployment is being deprecated in favor of better tested and maintained installation methods.

- [oc cluster up](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md) for non-production "try it out" or test deployments
- [openshift-ansible](http://www.projectatomic.io/blog/2017/05/oo-standalone-registry/) for more production use cases.

This reported issue will not be addressed.
