### ISSUE TITLE
start openshift failed with cAdvisor is unsupported in this build

### ISSUE THREAD

**Issue by jiangytcn** [openshift/origin#13778]
As per the [contribution guidance](https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-locally-on-your-host), i failed at `sudo ./openshift start` which is `F0415 20:02:00.875857   36786 node.go:323] failed to run Kubelet: failed to create kubelet: cAdvisor is unsupported in this build`

##### Version

> → ./openshift version
> openshift v1.5.0-rc.0+49a4a7a
> kubernetes v1.5.2+43a9be4
> etcd 3.1.0

> → docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

> Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

##### Platform
MacOS Sierra 10.12.3

Is there any prerequisites i am missing ?

**Comment by ncdc** [comment]
Are you running `sudo openshift start` directly on MacOS?

**Comment by jiangytcn** [comment]
@ncdc yes. I thought the root cause is that the k8s doesn't support Mac yet.

**Comment by ncdc** [comment]
@jiangytcn you won't be able to run the node (kubelet) portion of openshift (or kubernetes) directly on a Mac. That requires Linux.

If you want to run on a Mac and you don't want to set up a Linux virtual machine, I would recommend you look at `oc cluster up`.

**Comment by pweil-** [comment]
looks like this has been answered, closing
