### ISSUE TITLE
CLI not properly handling -o jsontemplate

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#13784]
I have loaded a template with:

````
oc create -f https://gitlab.com/gitlab-org/omnibus-gitlab/raw/master/docker/openshift-template.json
````
 
Then I want to query for specific information on the template:

When I query for the template I get the appropriate info:
````
oc get template/gitlab-ce -o json
{
    "apiVersion": "v1",
    "kind": "Template",
    "labels": {
        "createdBy": "gitlab-ce-template"
    },
    "metadata": {
        "annotations": {
...
````

But if I use jsontemplate I get:
````
$ oc get template/gitlab-ce -o jsontemplate { .objects[] }
error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'oc get resource/<resource_name>' instead of 'oc get resource resource/<resource_name>'
````

##### Version
````
oc version
oc v3.6.0-alpha.1+46942ad
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.1+46942ad
kubernetes v1.5.2+43a9be4
````

**Comment by ncdc** [comment]
@jorgemoralespou are you literally doing `-o jsontemplate { .objects[] }` or do you have any of that in quotes (`'{ .objects[] }'`). Also I think it's `-o jsonpath`, not `jsontemplate`?

**Comment by jorgemoralespou** [comment]
@ncdc You're right that jsonpath is not a valid option. I always get it wrong at first (the problem of being a non technical spanish) and I fix it based on what error I get. This time the error was very misleading. I think it's still an error on the message I get, independent of my inhability to do the things right. 

WDYT?

**Comment by ncdc** [comment]
@jorgemoralespou I agree with you that the error message you got is not exactly super helpful at determining what's wrong, but I'm not sure how much we can do here. You omitted quotes, so I'm guessing it's interpreting it as `jsonpath={` and then looking at what's left (`.objects[]` and `}`) and interpreting one of those as a resource type, and then saying you shouldn't mix and match a standalone resource type with ones that include it. A cleaner example that results in this error would be: `oc get pods foo pod/bar`.

btw just for clarity, it's `jsontemplate` that's the invalid option - `jsonpath` is correct.

**Comment by jorgemoralespou** [comment]
@ncdc if jsontemplate does not exist as valid route for -o I would expect an error message saying: " jsontemplate is not a valid option" rather than assuming it's a jsonpath.

Also, if assuming it's a jsonpath I don't agree that it should give that message. I wanted to get specific output of a single template, hence selecting the template and looking for the objects field in the template, which is one of the fields in a template, and I should be able to print that output.

**Comment by ncdc** [comment]
@jorgemoralespou it's not assuming it's jsonpath. Let me reiterate what is going on. You did the equivalent of `oc get pods pod1 pod/pod2`. Anytime the client sees a combination of `pods <name> <name> <name> ...` and `pod/<name>` it will give you the error you're seeing. This is because it's seeing a combination of `<resource type> <name> <name> ....` and `<resource type>/<name> <resource type>/<name> ...`.

It's not immediately clear, but if you look closely, this is what is happening with your request:

```
oc get template/gitlab-ce -o jsontemplate {         .objects[]   }
               ^                     ^    ^             ^        ^
     <resource type>/<name>          |    |             |        |
                         <output format>  |             |        |
                              <output format argument>  |        |
                                                      <name>     |
                                                              <name>
```

**Comment by ncdc** [comment]
Which means that it's first validating the request format ("type/name name name name" is invalid) before getting to the invalid option passed to -o. If you do `oc get template/gitlab-ce -o jsontemplate='{ .objects[] }'`, you will get `error: output format "jsontemplate={ .objects[] }" not recognized`.

**Comment by jorgemoralespou** [comment]
@ncdc understood. Thanks for the explanation. Now, is this the behavior we want? If it is I'll close the issue, but for me as a user was misleading.

**Comment by ncdc** [comment]
@jorgemoralespou I don't know off the top of my head how we would be able to discern user intent. Perhaps @openshift/ui-review have some ideas. If we were to do anything, the changes would belong upstream in Kubernetes, as that's where this is coming from.

**Comment by ncdc** [comment]
cc @smarterclayton

**Comment by stevekuznetsov** [comment]
I think that if the user is quoting their arguments and passes the JSONPath string as one argument, the error you showed above clearly lets them know that `jsontemplate` is unknown. It's pretty hard to discern user intent in this case and in general I think it's reasonable to assume that the user is passing the right number of arguments / is using word-splitting when they intend to.

**Comment by smarterclayton** [comment]
The message is definitely weird - i think it's too aggressive for complex arguments and needs to be a bit more nuanced.
