### ISSUE TITLE
DC condition has reason `ProgressDeadlineExceeded` when deployment cancelled

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#13800]
The deployment config condition is misleading. It has reason `DeadlineExceeded` when I cancelled the deployment. I'd expect the reason to indicate the deployment was cancelled.

#### Deployment Config Status

```yaml
status:
  latestVersion: 3
  observedGeneration: 6
  replicas: 0
  updatedReplicas: 0
  availableReplicas: 0
  unavailableReplicas: 0
  details:
    message: config change
    causes:
      - type: ConfigChange
  conditions:
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2017-04-18T12:10:03Z'
      lastTransitionTime: '2017-04-18T12:10:03Z'
      reason: ProgressDeadlineExceeded
      message: replication controller "hello-openshift-3" has failed progressing
    - type: Available
      status: 'False'
      lastUpdateTime: '2017-04-18T13:06:15Z'
      lastTransitionTime: '2017-04-18T13:06:15Z'
      message: Deployment config does not have minimum availability.
```

#### Replication Controller Metadata

Notice the status is cancelled. It's also strange to me that the deployment phase is failed when the deployment was cancelled.

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-openshift-3
  namespace: failed-deployment
  selfLink: >-
    /api/v1/namespaces/failed-deployment/replicationcontrollers/hello-openshift-3
  uid: f0fa42be-242f-11e7-ad20-c653b3ffadbe
  resourceVersion: '132052'
  generation: 3
  creationTimestamp: '2017-04-18T12:09:58Z'
  labels:
    app: hello-openshift
    openshift.io/deployment-config.name: hello-openshift
  annotations:
    kubectl.kubernetes.io/desired-replicas: '1'
    kubectl.kubernetes.io/update-source-id: 'hello-openshift-1:87cb15d1-23a5-11e7-8d0c-c653b3ffadbe'
    openshift.io/deployer-pod.name: hello-openshift-3-deploy
    openshift.io/deployment-config.latest-version: '3'
    openshift.io/deployment-config.name: hello-openshift
    openshift.io/deployment.cancelled: 'true'
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: '0'
    openshift.io/deployment.status-reason: The deployment was cancelled by the user

[...]
```

##### Version

OpenShift Master:
v1.0.4+b7a5b0f-12416
Kubernetes Master:
v1.5.2+43a9be4

##### Steps To Reproduce
1. Start a deployment
2. Cancel it before it completes

cc @jwforres @kargakis @mfojtik

**Comment by kargakis** [comment]
Sure, we should switch the condition to reflect cancel rather than a timeout of the deployer.
The code now simply propagates the terminal status of the RC into its DC status:
https://github.com/openshift/origin/blob/be5034b339b85eba62b875df7fa35f1665eb0ab7/pkg/deploy/controller/deploymentconfig/controller.go#L375-L377

> It's also strange to me that the deployment phase is failed when the deployment was cancelled.

Cancel means fail since it's not a success. I am not sure we want to add a third terminal phase at this point. This should be related to job terminal status cc: @soltysh

**Comment by mfojtik** [comment]
@kargakis +1 to not add third terminal phase... if the rollout is cancelled it means it failed to succeed by a human intervention. agree we should propagate that in conditions.

**Comment by soltysh** [comment]
We should slowly get rid of phases, entirely.

**Comment by spadgett** [comment]
> We should slowly get rid of phases, entirely.

Please let the UI team know as you do this :) We still have some code that looks at phase

**Comment by soltysh** [comment]
Sigh...
