### ISSUE TITLE
Record excluder state and disable.[localhost] openshift_excluder : Install docker excluder

### ISSUE THREAD

**Issue by bparees** [openshift/origin#13802]
```
No package matching 'origin-docker-excluder-1.5.0-0.7.rc1*' found available, installed or updated
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/783/

**Comment by ncdc** [comment]
I believe a fix for this is on its way

**Comment by bparees** [comment]
@ncdc is there a PR or do you know who's working on it?

**Comment by ncdc** [comment]
@sdodson is

**Comment by sdodson** [comment]
Fixed by openshift-ansible-3.5.53-1.git.0.8ade9f2.el7 which landed in centos paas sig repos ~ 30 minutes ago. Current in flight jobs look like they've progressed past the point of failure.

**Comment by sdodson** [comment]
Closing as the last few tests runs haven't shown signs of this issue.

**Comment by sdodson** [comment]
should no longer be an issue
