### ISSUE TITLE
No package matching 'origin-1.5.0-0.7.rc1' found available, installed or updated

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#13814]
```
TASK [openshift_common : Install the base package for versioning] **************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_common/tasks/main.yml:44
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "generated_timestamp": "2017-04-19 07:45:06.511114", 
    "msg": "No package matching 'origin-1.5.0-0.7.rc1' found available, installed or updated", 
    "rc": 126, 
    "results": [
        "No package matching 'origin-1.5.0-0.7.rc1' found available, installed or updated"
    ]
}
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/217/consoleFull#77014445158b6e51eb7608a5981914356

**Comment by sdodson** [comment]
@jhadvig I'd like to switch to a repo that doesn't have openshift-ansible-3.5.46 as that has critical excluder bugs that do not exist in the GA version.

One way to do that would be to switch from repos at 
https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin15/

to
http://cbs.centos.org/repos/paas7-openshift-origin15-testing/x86_64/os/Packages/

We'd want to follow up to get rid of the -testing as soon as this repo is populated but I don't think that will happen until after Origin 1.5 GA happens

http://cbs.centos.org/repos/paas7-openshift-origin15/x86_64/os/Packages/

What do you think?

**Comment by sdodson** [comment]
Alternatively, I think we should consider disabling the excluders until we have only 1.5 GA builds in the repos that these CI jobs utilize.

**Comment by bparees** [comment]
saw again here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/247/consoleFull#-14246886155849c75fe4b0052e114d805c

**Comment by kargakis** [comment]
And again: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/251/consoleFull#77014445158b6e51eb7608a5981914356

**Comment by jhadvig** [comment]
@sdodson so until we can to http://cbs.centos.org/repos/paas7-openshift-origin15-testing/x86_64/os/Packages/ repo I would just add the `enable-excluders: false` variable to the [inventory](https://github.com/openshift/aos-cd-jobs/blob/master/sjb/inventory/group_vars/OSEv3/general.yml) that we use to run the playbooks and by that disable all the excluders. Although I'm not sure if that wont hide any other potential issues.

**Comment by jhadvig** [comment]
Also why cant we backport the excluder fix to openshift-ansible-3.5.46 ?

**Comment by stevekuznetsov** [comment]
Can we see if this is p0? @sdodson are there jobs within the last day or so that have succeeded while trying to install `origin-1.5.0-0.7.rc1` ?

**Comment by smarterclayton** [comment]
@jhadvig was this the one you were fixing?

**Comment by jhadvig** [comment]
@smarterclayton yes it was

**Comment by stevekuznetsov** [comment]
Not blocking anymore, not p0

**Comment by tbielawa** [comment]
Getting a similar issue in https://github.com/openshift/openshift-ansible/pull/4041

https://aos-ci.s3.amazonaws.com/openshift/openshift-ansible/jenkins-openshift-ansible-test-matrix-CONTAINERIZED=_containerized,OSE_VER=3.6,PYTHON=System-CPython-2.7,TOPOLOGY=openshift-cluster-containerized,TargetBranch=master,nodes=openshift-ansible-slave-630/e1a91973650a26859d1d02449ac35b1946746392.txt

```
  1. Host:     10.8.170.8
     Play:     Disable excluders
     Task:     openshift_excluder : Install docker excluder
     Message:  No package matching 'atomic-openshift-docker-excluder-3.6.109*' found available, installed or updated
...
```

Guessing it's probably a new puddle dropping mid-install. Just flake-tagging so I can get this PR moving again.

**Comment by stevekuznetsov** [comment]
This was caused by hitting some bugs in the impl of the excluders at that version -- we should _not_ be hitting it for the same reasons now. /cc @sdodson @ingvagabund

**Comment by sdodson** [comment]
This occurrence is, as tim says, problems associated with the images being newer on the test registry than the rpm repos. In fact it looks like the 3.6 image push failed and the repo never got updated so I manually updated it.
