### ISSUE TITLE
Extended.deploymentconfigs with multiple image change triggers

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#13821]
[First test flake](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/253/) - second is known.

Extended.deploymentconfigs with multiple image change triggers [Conformance] should run a successful deployment with a trigger used by different containers
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/253/consoleFull#-62810337056cbb9a5e4b02b88ae8c2f77

**Comment by kargakis** [comment]
First seems known too
```
• Failure [72.576 seconds]
deploymentconfigs
/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:900
  with multiple image change triggers [Conformance]
  /go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:390
    should run a successful deployment with a trigger used by different containers [It]
    /go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:389

    Expected error:
        <*errors.StatusError | 0xc421637200>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {SelfLink: "", ResourceVersion: ""},
                Status: "Failure",
                Message: "the server has asked for the client to provide credentials (get deploymentConfigs example)",
                Reason: "Unauthorized",
                Details: {
                    Name: "example",
                    Group: "",
                    Kind: "deploymentConfigs",
                    Causes: [
                        {
                            Type: "UnexpectedServerResponse",
                            Message: "Unauthorized",
                            Field: "",
                        },
                    ],
                    RetryAfterSeconds: 0,
                },
                Code: 401,
            },
        }
        the server has asked for the client to provide credentials (get deploymentConfigs example)
    not to have occurred
```

**Comment by mfojtik** [comment]
@enj @liggitt i'm not sure if this is a deployment issue or something broken in the auth layer...

My guesses will be:

1) the client dropped the config/token for some reason
2) the bootstraping of roles haven't finished

do you guys have any other clues where to start looking?

**Comment by mfojtik** [comment]
Also it is interesting that this has been polling for 72s and then suddenly failed....

**Comment by stevekuznetsov** [comment]
This is etcd falling over with a bad IO operation. See also #13067 and https://github.com/openshift/aos-cd-jobs/pull/169

**Comment by mfojtik** [comment]
@stevekuznetsov the etcd issue was fixed and I don't see any new occurences of this, closing this.
