### ISSUE TITLE
extended tests run in 3 mins and report success

### ISSUE THREAD

**Issue by bparees** [openshift/origin#13826]
as seen here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended/195/console

near as i can tell this did not actually run any tests and yet it reported success.

the tag was:
[testextended][extended:core(builds)]

from here:
https://github.com/openshift/origin/pull/13825

**Comment by bparees** [comment]
@smarterclayton @stevekuznetsov @dobbymoodge @jupierce 

did we change anything here recently?  or did i just do something dumb?  False negatives are worrisome.

**Comment by smarterclayton** [comment]
Dupe of #13823
