### ISSUE TITLE
All CI jobs are either broken, or succeeding immediately without doing anything

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#13823]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/1139/consoleFull#-118218696958b6e51eb7608a5981914356

**Comment by kargakis** [comment]
Seems like this is blocking the merge queue @jhadvig @sdodson

**Comment by kargakis** [comment]
Or at least I have seen in twice in a row
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/1141/consoleFull#-118218696958b6e51eb7608a5981914356

**Comment by smarterclayton** [comment]
@jupierce

**Comment by smarterclayton** [comment]
Rpm builds are failing

**Comment by smarterclayton** [comment]
Or not being called

**Comment by smarterclayton** [comment]
Almost certainly https://github.com/openshift/aos-cd-jobs/commit/b1d17d59c5b68006fc31c93743d5e532c28ad920, possible escaping is broken

**Comment by bparees** [comment]
yeah i'm hitting it too, so probably not a flake.
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/1145

**Comment by smarterclayton** [comment]
I changed the bash quote escaping in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/1147/console to test.  But it doesn't look like it changed here

**Comment by smarterclayton** [comment]
Heh all the jobs are broken - just succeeding

**Comment by smarterclayton** [comment]
I believe fixed in https://github.com/openshift/aos-cd-jobs/pull/197

**Comment by smarterclayton** [comment]
Waiting to see 1147 get past the failure

**Comment by smarterclayton** [comment]
1147 got past it, it was indeed double escaping.  Pushing a new change.

**Comment by smarterclayton** [comment]
Ok some of the jobs started succeeding again with my latest update.  Monitoring.

**Comment by stevekuznetsov** [comment]
Thanks for the fix @smarterclayton, yes sorry the escaping was the issue. I've made sure all PRs affected by this got a new kick for re-test/merge.

**Comment by stevekuznetsov** [comment]
Jobs like https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/816/ failing shows a return to normalcy. Thanks again @smarterclayton for fixing.
