### ISSUE TITLE
flake: python: can't open file 'hack/determine_install_upgrade_version.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#13833]
First seen in https://github.com/openshift/openshift-ansible/pull/3919, https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_update/118/console

```
...
########## STARTING STAGE: INSTALL ANSIBLE ATOMIC-OPENSHIFT-UTILS ##########
+ [[ -s /var/lib/jenkins/jobs/test_pull_request_openshift_ansible_extended_conformance_install_update/workspace/activate ]]
+ source /var/lib/jenkins/jobs/test_pull_request_openshift_ansible_extended_conformance_install_update/workspace/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/6a41b1c0e6822ccfb40398a030e16a09894da043
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/6a41b1c0e6822ccfb40398a030e16a09894da043
++ export PATH=/var/lib/jenkins/origin-ci-tool/6a41b1c0e6822ccfb40398a030e16a09894da043/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/6a41b1c0e6822ccfb40398a030e16a09894da043/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_openshift_ansible_extended_conformance_install_update/workspace/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_openshift_ansible_extended_conformance_install_update/workspace/.config
++ mktemp
+ script=/tmp/tmp.PuA3PtA4ON
+ cat
+ chmod +x /tmp/tmp.PuA3PtA4ON
+ scp -F ./.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.PuA3PtA4ON openshiftdevel:/tmp/tmp.PuA3PtA4ON
+ ssh -F ./.config/origin-ci-tool/inventory/.ssh_config openshiftdevel /tmp/tmp.PuA3PtA4ON
+ cd /data/src/github.com/openshift/aos-cd-jobs
+ pkg_name=origin
+ git checkout sjb
+ echo origin
+ echo 'openshift-ansible openshift-ansible-callback-plugins openshift-ansible-docs openshift-ansible-filter-plugins openshift-ansible-lookup-plugins openshift-ansible-playbooks openshift-ansible-roles'
++ cat OPENSHIFT_ANSIBLE_BUILT_VERSION
+ sudo python hack/determine_install_upgrade_version.py atomic-openshift-utils-3.6.30-1.git.0.63e1bed.el7.noarch
python: can't open file 'hack/determine_install_upgrade_version.py': [Errno 2] No such file or directory
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: INSTALL ANSIBLE ATOMIC-OPENSHIFT-UTILS ##########
```

**Comment by rhcarvalho** [comment]
This seems to be more of an issue with CI than a "flake". @stevekuznetsov @jhadvig is it fair to tag it as `kind/test-flake` and have it here in origin, or should we/I create issues in aos-ci-jobs or other repo next time?

**Comment by mfojtik** [comment]
Since the missing `determine_install_upgrade_version.py` file is not part of origin repo, I wouild say this belongs to aos-ci-jobs.

**Comment by rhcarvalho** [comment]
@mfojtik the doubt arises when we consider that AFAIK Rosie only considers flake issues in this repo, and that influences the merge queue process (e.g. for re-triggering merges), at least it is how it affects the merge queue in openshift-ansible, not sure if it is the same for the origin queue.

Then again, if we take a strict interpretation of the label this is issue is not a _test flake_, but if we expand the interpretation of the label to involve anything that makes a Jenkins job fail for reasons unrelated to the code changes in the PR, then this would make sense, thus my question ;)

**Comment by jhadvig** [comment]
The issue has been fixed. It was not a flake. It was cause by fact that we [moved](https://github.com/openshift/aos-cd-jobs/commit/a61253a1c6834242de208308788ab505f259f5ce) jobs and scripts from aos-cd-jobs repo branches in to master, which deleted all the branches and we didnt have time to adjust those scripts (eg. determine_install_upgrade_version.py) with proper prefix.
Closing this issue

**Comment by jhadvig** [comment]
@rhcarvalho next time please ping somebody from the CD team and ask if its worth to open an issue, cause while we are under the infrastructure development these types of mistakes may happen.
And if you want to open an issue open it in a proper repo. Since this is jenskins job related issue, `aos-cd-jobs` should be your first guess.

**Comment by stevekuznetsov** [comment]
> Since this is jenskins job related issue, aos-cd-jobs repository should be your first guess.

They'll probably still want to open it here since the robot wants Origin `kind/test-flake` issues for re-triggering the job.
