### ISSUE TITLE
[question]: how to CURD an user in project scope by the project admin ?

### ISSUE THREAD

**Issue by xiaoping378** [openshift/origin#13832]
Hi , 

Now `user` is the cluster scope, 
I made a clusterrole which can CURD users and assigned to the project admin, so the admin can create an user and assign an role in the own project, OK, everything is good...

but the project admin can also CURD the others' user in the cluster... this is terrible.
Maybe we need two types: `clusteruser` and `user`, one for cluster and the other for project scope.

**Comment by enj** [comment]
> Now `user` is the cluster scope, I made a clusterrole which can CURD users and assigned to the project admin, so the admin can create an user and assign an role in the own project, OK, everything is good... but the project admin can also CURD the others' user in the cluster... this is terrible.

This is working as expected.  Do not let normal users create other users.  If you need to make it easy for users to be provisioned, set up an IDP such GitHub, LDAP, etc.

> Maybe we need two types: `clusteruser` and `user`, one for cluster and the other for project scope.

The does not make sense - a user logs into the cluster, not a project.  Service accounts are project scoped, but they are not meant to be used directly by users.

Feel free to reopen if you have further questions.

**Comment by xiaoping378** [comment]
@enj 

i want to that the project admin have ability to create users on own project, `NOT` sync from the existing user from LDAP, Github,etc, syncing need cluster-admin privileges....

Do you have any suggestion to implement this?

**Comment by xiaoping378** [comment]
I think my requirement is the Domains in keystone:

> Domains are high-level containers for projects, users and groups. As such, they can be used to centrally manage all keystone-based identity components. With the introduction of account domains, server, storage and other resources can now be logically grouped into multiple projects (previously called tenants) which can themselves be grouped under a master account-like container. In addition, multiple users can be managed within an account domain and assigned roles that vary for each project.

we have any plan to support it ？ i can help...

**Comment by enj** [comment]
> i want to that the project admin have ability to create users on own project, `NOT` sync the existing users from LDAP, Github,etc, syncing need cluster-admin privileges....

This is not possible.

> we have any plan to support it

Closest proposed thing is https://github.com/openshift/origin/pull/6226 (this is a long way off)
