### ISSUE TITLE
oc pods are in error state

### ISSUE THREAD

**Issue by naveenkumartangallapally** [openshift/origin#13843]
i newly setup openshift origin with advanced installation with ansible.

after the completion of setup registry and pods are going into error state.

[root@master ~]# oc get pods

NAME                        READY     STATUS              RESTARTS   AGE
docker-registry-1-deploy    0/1       Error               0          4m
registry-console-1-deploy   1/1       Running             0          4m
registry-console-1-r0jiw    0/1       ContainerCreating   0          1m
router-1-deploy             0/1       Error               0          5m
 and logs are saying 

[root@master ~]# 
[root@master ~]# oc logs docker-registry-1-deploy
error: couldn't get deployment docker-registry-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp 172.30.0.1:443: getsockopt: connection refused
[root@master ~]# oc logs router-1-deploy
error: couldn't get deployment router-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/router-1: dial tcp 172.30.0.1:443: getsockopt: connection refused

after that i tried some dubugs as 
oc cluster down
sudo systemctl stop docker
sudo iptables -F
sudo iptables -t nat -F
sudo systemctl start docker
oc cluster up

but when i am trying to oc cluster up i am getting below error:
[root@master ~]# systemctl is-active docker
active
[root@master ~]# oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.4.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... FAIL
   Error: a port needed by OpenShift is not available
   Caused By:
     Error: ports in use: [4001 7001 8443 10250 53]
[root@master ~]# 

and my oc version:
[root@master ~]# oc version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://master.example.com:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

please suggest anyone

**Comment by pweil-** [comment]
@naveenkumartangallapally it looks like you still have an instance of the cluster running if all those ports are in use.  Can you please check with `ps` and kill any running openshift processes?

**Comment by csrwng** [comment]
If you've setup a cluster with ansible, you should not be using cluster up. All services should be managed via systemctl.

**Comment by naveenkumartangallapally** [comment]
Hi @pweil,

i am trying to deploy openshift with advanced installation method by using ansible play-book,

after completion of installation i am getting below error:

[root@master ~]# oc get pods
NAME                        READY     STATUS    RESTARTS   AGE
docker-registry-1-deploy    0/1       Error     0          12m
registry-console-1-deploy   0/1       Error     0          12m
router-1-deploy             0/1       Error     0          13m


[root@master ~]# oc logs docker-registry-1-deploy
error: couldn't get deployment docker-registry-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp 172.30.0.1:443: getsockopt: connection refused


[root@master ~]# oc version 
oc v3.5.5.15
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://master.example.com:8443
openshift v3.5.5.15
kubernetes v1.5.2+43a9be4
[root@master ~]# 


pls help me on the issue to resolve?

**Comment by pweil-** [comment]
@naveenkumartangallapally there is not much info here past what you've already stated in the original description.  Please check `oc get events` to see if that has information on why all of your deployments are failing.  Also please check the master logs.

**Comment by naveenkumartangallapally** [comment]
Hi pweil,

oc get events output is like below:

[root@master ~]# oc get events
LASTSEEN   FIRSTSEEN   COUNT     NAME                        KIND               SUBOBJECT                     TYPE      REASON                    SOURCE                            MESSAGE
4m         4m          1         docker-registry-1-deploy    Pod                                              Normal    Scheduled                 {default-scheduler }              Successfully assigned docker-registry-1-deploy to node1.example.com
3m         3m          1         docker-registry-1-deploy    Pod                spec.containers{deployment}   Normal    Pulling                   {kubelet node1.example.com}       pulling image "openshift3/ose-deployer:v3.5.5.15"
1m         1m          1         docker-registry-1-deploy    Pod                spec.containers{deployment}   Normal    Pulled                    {kubelet node1.example.com}       Successfully pulled image "openshift3/ose-deployer:v3.5.5.15"
1m         1m          1         docker-registry-1-deploy    Pod                spec.containers{deployment}   Normal    Created                   {kubelet node1.example.com}       Created container with docker id 94435156b9a3; Security:[seccomp=unconfined]
1m         1m          1         docker-registry-1-deploy    Pod                spec.containers{deployment}   Normal    Started                   {kubelet node1.example.com}       Started container with docker id 94435156b9a3
4m         4m          1         docker-registry             DeploymentConfig                                 Normal    DeploymentCreated         {deploymentconfig-controller }    Created new replication controller "docker-registry-1" for version 1
7m         7m          1         master.example.com          Node                                             Normal    Starting                  {kubelet master.example.com}      Starting kubelet.
7m         7m          1         master.example.com          Node                                             Warning   ImageGCFailed             {kubelet master.example.com}      unable to find data for container /
7m         7m          2         master.example.com          Node                                             Normal    NodeHasSufficientDisk     {kubelet master.example.com}      Node master.example.com status is now: NodeHasSufficientDisk
7m         7m          2         master.example.com          Node                                             Normal    NodeHasSufficientMemory   {kubelet master.example.com}      Node master.example.com status is now: NodeHasSufficientMemory
7m         7m          2         master.example.com          Node                                             Normal    NodeHasNoDiskPressure     {kubelet master.example.com}      Node master.example.com status is now: NodeHasNoDiskPressure
7m         7m          1         master.example.com          Node                                             Normal    RegisteredNode            {controllermanager }              Node master.example.com event: Registered Node master.example.com in NodeController
7m         7m          1         master.example.com          Node                                             Normal    Starting                  {kube-proxy master.example.com}   Starting kube-proxy.
7m         7m          1         master.example.com          Node                                             Normal    NodeReady                 {kubelet master.example.com}      Node master.example.com status is now: NodeReady
7m         7m          1         master.example.com          Node                                             Normal    NodeNotSchedulable        {kubelet master.example.com}      Node master.example.com status is now: NodeNotSchedulable
7m         7m          1         node1.example.com           Node                                             Normal    Starting                  {kubelet node1.example.com}       Starting kubelet.
7m         7m          1         node1.example.com           Node                                             Warning   ImageGCFailed             {kubelet node1.example.com}       unable to find data for container /
7m         7m          2         node1.example.com           Node                                             Normal    NodeHasSufficientDisk     {kubelet node1.example.com}       Node node1.example.com status is now: NodeHasSufficientDisk
7m         7m          2         node1.example.com           Node                                             Normal    NodeHasSufficientMemory   {kubelet node1.example.com}       Node node1.example.com status is now: NodeHasSufficientMemory
7m         7m          2         node1.example.com           Node                                             Normal    NodeHasNoDiskPressure     {kubelet node1.example.com}       Node node1.example.com status is now: NodeHasNoDiskPressure
7m         7m          1         node1.example.com           Node                                             Normal    RegisteredNode            {controllermanager }              Node node1.example.com event: Registered Node node1.example.com in NodeController
7m         7m          1         node1.example.com           Node                                             Normal    Starting                  {kube-proxy node1.example.com}    Starting kube-proxy.
7m         7m          1         node1.example.com           Node                                             Normal    NodeReady                 {kubelet node1.example.com}       Node node1.example.com status is now: NodeReady
7m         7m          1         node2.example.com           Node                                             Normal    Starting                  {kubelet node2.example.com}       Starting kubelet.
7m         7m          1         node2.example.com           Node                                             Warning   ImageGCFailed             {kubelet node2.example.com}       unable to find data for container /
7m         7m          2         node2.example.com           Node                                             Normal    NodeHasSufficientDisk     {kubelet node2.example.com}       Node node2.example.com status is now: NodeHasSufficientDisk
7m         7m          2         node2.example.com           Node                                             Normal    NodeHasSufficientMemory   {kubelet node2.example.com}       Node node2.example.com status is now: NodeHasSufficientMemory
7m         7m          2         node2.example.com           Node                                             Normal    NodeHasNoDiskPressure     {kubelet node2.example.com}       Node node2.example.com status is now: NodeHasNoDiskPressure
7m         7m          1         node2.example.com           Node                                             Normal    RegisteredNode            {controllermanager }              Node node2.example.com event: Registered Node node2.example.com in NodeController
7m         7m          1         node2.example.com           Node                                             Normal    Starting                  {kube-proxy node2.example.com}    Starting kube-proxy.
7m         7m          1         node2.example.com           Node                                             Normal    NodeReady                 {kubelet node2.example.com}       Node node2.example.com status is now: NodeReady
3m         3m          1         registry-console-1-deploy   Pod                                              Normal    Scheduled                 {default-scheduler }              Successfully assigned registry-console-1-deploy to node2.example.com
1m         1m          1         registry-console-1-deploy   Pod                spec.containers{deployment}   Normal    Pulling                   {kubelet node2.example.com}       pulling image "openshift3/ose-deployer:v3.5.5.15"
20s        20s         1         registry-console-1-deploy   Pod                spec.containers{deployment}   Normal    Pulled                    {kubelet node2.example.com}       Successfully pulled image "openshift3/ose-deployer:v3.5.5.15"
16s        16s         1         registry-console-1-deploy   Pod                spec.containers{deployment}   Normal    Created                   {kubelet node2.example.com}       Created container with docker id 189ee59ac589; Security:[seccomp=unconfined]
15s        15s         1         registry-console-1-deploy   Pod                spec.containers{deployment}   Normal    Started                   {kubelet node2.example.com}       Started container with docker id 189ee59ac589
3m         3m          1         registry-console            DeploymentConfig                                 Normal    DeploymentCreated         {deploymentconfig-controller }    Created new replication controller "registry-console-1" for version 1
5m         5m          1         router-1-deploy             Pod                                              Normal    Scheduled                 {default-scheduler }              Successfully assigned router-1-deploy to node1.example.com
3m         3m          1         router-1-deploy             Pod                spec.containers{deployment}   Normal    Pulling                   {kubelet node1.example.com}       pulling image "openshift3/ose-deployer:v3.5.5.15"
1m         1m          1         router-1-deploy             Pod                spec.containers{deployment}   Normal    Pulled                    {kubelet node1.example.com}       Successfully pulled image "openshift3/ose-deployer:v3.5.5.15"
1m         1m          1         router-1-deploy             Pod                spec.containers{deployment}   Normal    Created                   {kubelet node1.example.com}       Created container with docker id 54b5da83a7eb; Security:[seccomp=unconfined]
1m         1m          1         router-1-deploy             Pod                spec.containers{deployment}   Normal    Started                   {kubelet node1.example.com}       Started container with docker id 54b5da83a7eb
5m         5m          1         router                      DeploymentConfig                                 Normal    DeploymentCreated         {deploymentconfig-controller }    Created new replication controller "router-1" for version 1
[root@master ~]# 


and my master logs showing as:
[root@master ~]# systemctl status atomic-openshift-master
● atomic-openshift-master.service - Atomic OpenShift Master
   Loaded: loaded (/usr/lib/systemd/system/atomic-openshift-master.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-06-06 10:43:04 EDT; 18min ago
     Docs: https://github.com/openshift/origin
 Main PID: 24977 (openshift)
   Memory: 346.8M
   CGroup: /system.slice/atomic-openshift-master.service
           └─24977 /usr/bin/openshift start master --config=/etc/origin/master/master-config.yaml --loglevel=2

Jun 06 11:01:02 master atomic-openshift-master[24977]: I0606 11:01:02.191069   24977 panics.go:76] GET /api/v1/nodes?fieldSelector=met…1:44820]
Jun 06 11:01:02 master atomic-openshift-master[24977]: I0606 11:01:02.301052   24977 panics.go:76] PUT /api/v1/nodes/node1.example.com...44820]
Jun 06 11:01:04 master atomic-openshift-master[24977]: I0606 11:01:04.564750   24977 panics.go:76] GET /api/v1/namespaces/default/serv...57764]
Jun 06 11:01:04 master atomic-openshift-master[24977]: I0606 11:01:04.790028   24977 panics.go:76] GET /apis/extensions/v1beta1/thirdp...57764]
Jun 06 11:01:05 master atomic-openshift-master[24977]: I0606 11:01:05.097646   24977 panics.go:76] GET /api/v1/watch/secrets?fieldSele...57764]
Jun 06 11:01:06 master atomic-openshift-master[24977]: I0606 11:01:06.502516   24977 panics.go:76] GET /apis/batch/v2alpha1/cronjobs: ...57798]
Jun 06 11:01:06 master atomic-openshift-master[24977]: I0606 11:01:06.507850   24977 panics.go:76] GET /apis/batch/v2alpha1/jobs: (4.7...57798]
Jun 06 11:01:06 master atomic-openshift-master[24977]: I0606 11:01:06.743797   24977 panics.go:76] GET /api/v1/nodes?resourceVersion=0...57764]
Jun 06 11:01:06 master atomic-openshift-master[24977]: I0606 11:01:06.880057   24977 panics.go:76] GET /api/v1/nodes?fieldSelector=met...58410]
Jun 06 11:01:06 master atomic-openshift-master[24977]: I0606 11:01:06.990584   24977 panics.go:76] PUT /api/v1/nodes/master.example.co...58410]
Hint: Some lines were ellipsized, use -l to show in full.
[root@master ~]# 




[root@master ~]# oc describe pod docker-registry-1-deploy
Name:			docker-registry-1-deploy
Namespace:		default
Security Policy:	restricted
Node:			node1.example.com/192.168.59.40
Start Time:		Tue, 06 Jun 2017 10:54:15 -0400
Labels:			openshift.io/deployer-pod-for.name=docker-registry-1
Status:			Failed
IP:			10.129.0.3
Controllers:		<none>
Containers:
  deployment:
    Container ID:	docker://94435156b9a3b46d699f93cadeb807a7937473460ab957b3178eb92d1e8f502b
    Image:		openshift3/ose-deployer:v3.5.5.15
    Image ID:		docker-pullable://registry.access.redhat.com/openshift3/ose-deployer@sha256:7ce4cb09a57772b7d4b45b82da42ad87f84596a4096508246ddf08daac06c624
    Port:		
    State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Tue, 06 Jun 2017 10:56:55 -0400
      Finished:		Tue, 06 Jun 2017 10:57:02 -0400
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from deployer-token-mf7tx (ro)
    Environment Variables:
      KUBERNETES_MASTER:	https://master.example.com:8443
      OPENSHIFT_MASTER:		https://master.example.com:8443
      BEARER_TOKEN_FILE:	/var/run/secrets/kubernetes.io/serviceaccount/token
      OPENSHIFT_CA_DATA:	-----BEGIN CERTIFICATE-----
MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE0OTY3NjAwODEwHhcNMTcwNjA2MTQ0MTIwWhcNMjIwNjA1
MTQ0MTIxWjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE0OTY3NjAwODEw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCzxnbDe4QQDUYFY9Mxa6Vm
j1Zssrk7XYipa7eq5r4Cyt7TB39d0rgU/CN+gstZMzKSMqeO0LAXKhWMlJK/Opqn
I89NC1cQPDDcwgKTUpDI27Glt4uQGgJB01HABlDU/RzaXj8+Qd5CAdRxiSbhBsOU
+fPlnZ9ADqcooU12ufcsswRrEfNSaOqcUCy6Ovo20aUVCS/bdKJUftircz21PvwC
6WbMkP7X56ESImidTNp+UmztMtjRBY2ytI/9iIntFpO9xbnczOnKt/J0kHvi+WLU
1o5K6K7oPbsBlMtuISvbaEfv3PCJCb/mq4eoWkeU9tJRNbsoNdcC14yRL9KfY9+l
AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
SIb3DQEBCwUAA4IBAQCvKwunT7bT0c3PwCqihFACsC1iWdS8Ki8p0uFL1k7pfvoD
nohNw9OzWlJ1rcVNko1tc/8JCGolirwvvvCDRDiRhnsP7UHN2BA9/XhT0pvWuwmG
w+slJEIVIxtoeni1YD/9n75cN+yLozw+BezOm4HsWbItUSQPpna7lJR6rE+2jbmn
ZsZx5NPWdEIBAQkr2SJpV4bZqJlS9KlhhVqsiUnxqbTu+A0ii6pUAAqu2r/ki1dP
FvM95jWv3soD3gjV/Ko5+zDUt6ZnsN80x72D5ejF8k1j8wqvGd5WEKbsdBLclbgy
LcSXKIufQC+Ijx3i3WecZ51ATb8Zoc4gozZN6A9W
-----END CERTIFICATE-----

      OPENSHIFT_DEPLOYMENT_NAME:	docker-registry-1
      OPENSHIFT_DEPLOYMENT_NAMESPACE:	default
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  deployer-token-mf7tx:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	deployer-token-mf7tx
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----				-------------			--------	------		-------
  8m		8m		1	{default-scheduler }						Normal		Scheduled	Successfully assigned docker-registry-1-deploy to node1.example.com
  7m		7m		1	{kubelet node1.example.com}	spec.containers{deployment}	Normal		Pulling		pulling image "openshift3/ose-deployer:v3.5.5.15"
  5m		5m		1	{kubelet node1.example.com}	spec.containers{deployment}	Normal		Pulled		Successfully pulled image "openshift3/ose-deployer:v3.5.5.15"
  5m		5m		1	{kubelet node1.example.com}	spec.containers{deployment}	Normal		Created		Created container with docker id 94435156b9a3; Security:[seccomp=unconfined]
  5m		5m		1	{kubelet node1.example.com}	spec.containers{deployment}	Normal		Started		Started container with docker id 94435156b9a3
[root@master ~]#

**Comment by pweil-** [comment]
```
4m 4m 1 docker-registry-1-deploy Pod Normal Scheduled {default-scheduler } Successfully assigned docker-registry-1-deploy to node1.example.com
3m 3m 1 docker-registry-1-deploy Pod spec.containers{deployment} Normal Pulling {kubelet node1.example.com} pulling image "openshift3/ose-deployer:v3.5.5.15"
1m 1m 1 docker-registry-1-deploy Pod spec.containers{deployment} Normal Pulled {kubelet node1.example.com} Successfully pulled image "openshift3/ose-deployer:v3.5.5.15"
1m 1m 1 docker-registry-1-deploy Pod spec.containers{deployment} Normal Created {kubelet node1.example.com} Created container with docker id 94435156b9a3; Security:[seccomp=unconfined]
1m 1m 1 docker-registry-1-deploy Pod spec.containers{deployment} Normal Started {kubelet node1.example.com} Started container with docker id 94435156b9a3
```

Ok, let's start here.  I can see that docker-registry-1-deploy  was scheduled on node1.example.com and is in a failed state.  The pod spec shows

```
State:	Terminated
Reason:	Error
Exit Code:	1
```

and you were unable to get logs with `oc logs docker-registry-1-deploy`.  Can you go to the node (node1.example.com) and see if you can do a `docker logs 94435156b9a3` to get any info on the failure?  If that does not work let's try redeploying and follow the deployment logs.

**Comment by bparees** [comment]
the oc cluster up usage that lead to this being assigned to @csrwng was spurious, i believe.  @pweil- back to you to find a more appropriate owner.

**Comment by pweil-** [comment]
closing due to lack of response.
