### ISSUE TITLE
Remove hardcoded kapi.PodAttachOptions.Stdout/err in buildconfiginstantiate

### ISSUE THREAD

**Issue by sttts** [openshift/origin#13859]
... when https://github.com/kubernetes/kubernetes/issues/44448 is merged. Compare discussion: https://github.com/openshift/origin/pull/13653#pullrequestreview-33893947

**Comment by mfojtik** [comment]
CC @bparees

**Comment by bparees** [comment]
they've been removed
/assign
/close
