### ISSUE TITLE
Secure Docker Registry Certificate Error

### ISSUE THREAD

**Issue by lazerion** [openshift/origin#13850]
We can not deploy secure registry on OCP 3.5. Below you can find error

[root@ip-10-20-4-38 master]# oc version
oc v3.5.5.5
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.hazelcast-ocp.com:8443
openshift v3.5.5.5
kubernetes v1.5.2+43a9be4

```
oadm ca create-server-cert \
> >     --signer-cert=/etc/origin/master/ca.crt \
> >     --signer-key=/etc/origin/master/ca.key \
> >     --signer-serial=/etc/origin/master/ca.serial.txt \
> >     --hostnames='registry.hazelcast-ocp.com,docker-registry.default.svc.cluster.local,172.30.221.40' \
> >     --cert=/etc/secrets/registry.crt \
> >     --key=/etc/secrets/registry.key
```
bash: --signer-cert=/etc/origin/master/ca.crt: **No such file or directory**

[root@ip-10-20-4-38 master]# ls /etc/origin/master/
admin.crt         etcd.server.crt         master.kubelet-client.crt  openshift-master.crt         serviceaccounts.private.key
admin.key         etcd.server.key         master.kubelet-client.key  openshift-master.key         serviceaccounts.public.key
admin.kubeconfig  master-config.yaml      master.proxy-client.crt    openshift-master.kubeconfig  service-signer.crt
ca-bundle.crt     master.etcd-ca.crt      master.proxy-client.key    policy.json                  service-signer.key
**ca.crt**            master.etcd-client.crt  master.server.crt          registry.crt                 session-secrets.yaml
ca.key            master.etcd-client.csr  master.server.key          registry.key
ca.serial.txt     master.etcd-client.key  named_certificates         scheduler.json

Could you please advise?

Thanks in advance

**Comment by dmage** [comment]
> bash: --signer-cert=/etc/origin/master/ca.crt: No such file or directory

Please ensure that you have \ as a last symbol on the previous line. Bash tried to interpret this line as a separate command.
