### ISSUE TITLE
oc status should report about failed Deployments

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#13853]
When Deployment has failed, `oc status` show me no errors at all and puzzling me as a user.

##### Version
oc v3.6.0-alpha.1+846289d-75-dirty
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://10.0.2.15:8443
openshift v3.6.0-alpha.1+846289d-75-dirty
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. oc cluster up
2. wget https://raw.githubusercontent.com/pires/kubernetes-elasticsearch-cluster/d37fa1e2fd0b9291cd174226d23bfc249adb6c0a/es-master.yaml
3. oc create -f es-master.yaml

##### Current Result
Deployment has failed because of SCC but `oc status` doesn't tell me about this:
```console
$ oc status
In project My Project (myproject) on server https://10.0.2.15:8443

You have no services, deployment configs, or build configs.
Run 'oc new-app' to create an application.
$ oc describe rs
...
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  10m		2s		57	{replicaset-controller }			Warning		FailedCreate	Error creating: pods "es-master-2387585559-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: "IPC_LOCK": capability may not be added capabilities.add: Invalid value: "SYS_RESOURCE": capability may not be added]
```

##### Expected Result
`oc status` should be aware about failed Deployments.

**Comment by kargakis** [comment]
Previous attempt: https://github.com/openshift/origin/pull/10490

**Comment by kargakis** [comment]
@mfojtik fixed?
