### ISSUE TITLE
oc cluster up: provide a hint to the user where he can find server logs

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#13855]
I feel that it's not easy to find server logs when using `oc cluster up`. I remember that Cesar told me about `docker logs origin` but it's not always work. When this command doesn't show all the logs, I have to use `journalctl -u docker` command.

Could we provide a hint to user about where he can find server logs? It could be printed after server is started up.

@bparees @csrwng

**Comment by stevekuznetsov** [comment]
Are you using the `journald` log driver for Docker? Not clear why there would be a difference between `docker logs` and `journalctl`.

**Comment by php-coder** [comment]
> Are you using the journald log driver for Docker?

Yes, I am. It's default configuration for Docker in Fedora AFAIK.

> Not clear why there would be a difference between docker logs and journalctl.

It's not clear to me too and I'd be grateful if someone shed a light on it.

**Comment by csrwng** [comment]
@php-coder is there specific log entries that you can only see by doing `journalctl -u docker` vs the `docker logs origin`? As far as I know `docker logs origin` should have given you all the log entries created by the single master/node process.

**Comment by bparees** [comment]
@php-coder bump as for why docker logs origin was insufficient for you.

@csrwng does seem like printing out that the logs can be found in docker logs origin would be helpful as a resolution to this (pending more info from @php-coder)

**Comment by php-coder** [comment]
@bparees Unfortunately, I don't remember details but probably I was editing one of the admission plugins.

**Comment by php-coder** [comment]
> @csrwng does seem like printing out that the logs can be found in docker logs origin would be helpful as a resolution to this

I agree.
