### ISSUE TITLE
Check deployment storage migration away from extensions

### ISSUE THREAD

**Issue by sttts** [openshift/origin#13857]
Check whether upstream migrates deployments away from extensions and migrate in origin as well. Compare the discussion in https://github.com/openshift/origin/pull/13653#discussion_r112562651.

**Comment by soltysh** [comment]
Not sure about 3.7 milestone, this needs to align with when k8s does that move, as well.

**Comment by sttts** [comment]
It's only the reminder to double check what kube does. Not that we forget to follow them like with HPAs.

**Comment by soltysh** [comment]
HPA wasn't done properly, it was silently moved to autoscaling group, without extensions being kept for at least a revision.
