### ISSUE TITLE
S2I Build accessing a SSH private Git Repository

### ISSUE THREAD

**Issue by glennodickson** [openshift/origin#13863]
I would like to connect to my private GIT repo and build the code from it using a SI2 build however upon running the build it fails the host key as mentioned below.

##### Version
> C:\data\dev>oc version
> oc v1.3.1
> kubernetes v1.3.0+52492b4
> features: Basic-Auth
> 
> Server https://SOMEIP:8443
> openshift v1.3.1
> kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Installed secret
oc secrets new buildsecret ssh-privatkey=.......\.ssh\id_rsa
2. Added secret to builder role
oc secrets add serviceaccount/builder secret/buildsecret
3. Confirmed the Build Config contains the secret entry as required
 "source": {
                    "type": "Git",
                    "git": {
                        "uri": "ssh://dickson@192.168.1.109/volume1/repo/ex-camel-rest-ms"
                    },
                    "secrets": [
                        {
                            "secret": {
                                "name": "buildsecret"
                            },
                            "destinationDir": "."
                        }
                    ]
4. Installed new build
oc new-build fabric8/tomcat-8~ssh://synologyuser@SOMEIP/volume1/repo/ex-camel-rest-ms --build-secret buildsecret --strategy=docker

##### Current Result
> Cloning "ssh://synologyuser@SOMEIP/volume1/repo/ex-camel-rest-ms" ...
> error: build error: Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

##### Expected Result
I can authenticate myself with ssh authentication.

##### Additional Information
Build Config in Json
[buildconfig.txt](https://github.com/openshift/origin/files/948719/buildconfig.txt)

Secret Matches with ID_RSA file
As noted in this post [https://github.com/openshift/origin/issues/5818](url) I've checked that build secret matches that of the id_rsa file using the following file:
oc get secrets/github-secret -o json -  I did decode the secret using Base64 and it matched

**Comment by bparees** [comment]
I think you're hitting a TLS cert verification issue, not a credentials verification issue:
https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#source-secrets-trusted-certificate-authorities

**Comment by glennodickson** [comment]
Thanks for your suggestion. 
I listed the build configs:

```
oc set env bc --all --list
# buildconfigs ex-camel-rest-ms
```

Applying the following command:
`oc set env bc/ex-camel-rest-ms --env=GIT_SSL_NO_VERIFY=true`

Re ran the build but had the same issue.
```
Cloning "ssh://dickson@192.168.1.109/volume1/repo/ex-camel-rest-ms" ...
error: build error: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

Is this what you were suggesting?

**Comment by bparees** [comment]
Well that is one way (it's not secure, but it will work around your issue).  Can you provide level 5 build logs? (oc start-build yourbuildname --build-loglevel=5)

The right fix for this issue is to provide the correct CA cert as a secret, as discussed in the doc i linked.

**Comment by glennodickson** [comment]
Yes I'd like to eventually use a secured connection however I thought it would be easier to turn off the verification. I see that the doco offer 2 options:

1. Create a secret with a CA certificate file (recommended).
I'm unclear how this works but seems to suggest creating a certificate:
`oc secrets new mycert ca.crt=</path/to/file>`

path/to/file : does this refer to the ssh\id_rsa file I mentioned in my original post?

2. Disable Git TLS verification. 
Thought I'd get this to work first since it seems simpler. I've attached the level docs and the extract from Build Config below:

1) Level 5 Logs
[level5logs.txt](https://github.com/openshift/origin/files/968026/level5logs.txt)

2) Build Config extract:
```
strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: myproject
        name: 'tomcat-8:latest'
      env:
        -
          name: GIT_SSL_NO_VERIFY
          value: 'true'
````

Thanks for your assistance.

**Comment by bparees** [comment]
> path/to/file : does this refer to the ssh\id_rsa file I mentioned in my original post?

no this would be the CA cert that can validate the cert your git server is using.

I think the GIT_SSL_NO_VERIFY=true flag may only work when using https as the git clone protocol and you appear to be using ssh.  Is https an option for your git server?

**Comment by glennodickson** [comment]
Hi Ben

I didn't setup any CA certs for my git server that I am aware of only the
private keys. Funnily I can git clone from my windows command line however,
Openshift dies as mentioned in my initial email.

https for my git service will take a fair effort since I'm using on a
synology nas.

Is there no simple solution to merely get source from a git repo using
Openshift :( ? Or is the first option (Create a secret with a CA
certificate file) from your linked doco the only option at this stage. if
so, where do I get the certificate from?

**Comment by bparees** [comment]
based on this:
http://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository

i think you actually need to install provide a known_hosts file to the build instead, and i don't think we have a mechanism for providing that as part of the build.

@csrwng you probably have the most git-hacking experience here....  basically @glennodickson is doing a git clone over ssh and since the host isn't known, it fails.  I'm a bit surprised this hasn't come up for anyone else (surely this isn't the first time someone is doing a git clone over ssh)

**Comment by bparees** [comment]
ah, apparently we turn off strict host key checking when a private ssh key is provided.

i wonder if the sourceSecret is not constructed correctly.  @glennodickson can oc get (yoursecret) -o yaml and provide the output here? feel free to mask the values, i'm just interested in the key names and other metadata.

the key in the secret needs to be named "ssh-privatekey"

**Comment by bparees** [comment]
(docs on defining the an ssh secret for source cloning are here: https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#source-secrets-ssh-key-authentication )

**Comment by glennodickson** [comment]
Thanks for your reply. Yes I've test for the access to git server
from OpenShift VM and found that I could ping if I used the IP address
however using the name of the git server didn't resolve because there is no
entry in the known_hosts, as one would expect.

To ensure I didn't have too many unknowns, I thought I'd use the IP for the
time being until I get it work then move to resolving names.

**Comment by glennodickson** [comment]
As requested I've attached the secret file in yml format I've been working with:
[buildsecret.txt](https://github.com/openshift/origin/files/973666/buildsecret.txt)

With this I noticed that I mispelt ssh-privatkey missing the e. So I corrected this and here is the new file with correction;
[newbuildsecret.txt](https://github.com/openshift/origin/files/973859/newbuildsecret.txt)

So I reissued the new command:
`oc secrets new buildsecret ssh-privatekey=c:\Users\....\.ssh\id_rsa`

I'm really surprised but got the same error:
> Cloning "ssh://dickson@192.168.1.103/volume1/repo/ex-camel-rest-ms" ...
> error: build error: Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

One thing I noticed with the documentation you recently suggested was that it is uses:
`oc secrets new-sshauth sshsecret --ssh-privatekey=$HOME/.ssh/id_rsa`

In my initial post I used the the following command to create the secret:
`oc secrets new buildsecret ssh-privatekey=c:\Users\dickson\.ssh\id_rsa`

Thinking this might make a difference I regenerated the secret and attempted to run the build with no difference of outcome. Here is the secret using the command from the doco:
[secretFromDoco.txt](https://github.com/openshift/origin/files/973941/secretFromDoco.txt)

**Comment by bparees** [comment]
and you're able to git clone from the repo using that id_rsa on your host and username dickson?

**Comment by glennodickson** [comment]
I am able to clone from my Windows command line if that is what you mean. I haven tried to ssh to Openshift VM and clone from there.

**Comment by bparees** [comment]
@glennodickson yeah i'm just trying to confirm that the username and id_rsa file are valid/sufficient to access your git repository since everything else about your configuration looks right to me at this point.

now that i think you have it correct, it would be worth gathering another round of level 5 logs because there should be a GIT_SSH variable being set as part of the git command invocations, if we have properly picked up your ssh-privatekey secret.

there's also some debug that should show up:
		glog.V(4).Infof("Finding auth for %q", file.Name())

and 
		glog.V(4).Infof("Found SCMAuth %q to handle %q", scmAuth.Name(), file.Name())

**Comment by glennodickson** [comment]
I've obtained the log but I'm not seeing this. I"ve attached the level5 and the current secret (not that has changed). 
[level5logs.txt](https://github.com/openshift/origin/files/979087/level5logs.txt)
[currentsecret.txt](https://github.com/openshift/origin/files/979088/currentsecret.txt)

Whilst I know this is from my Windows console I thought I'd run the following commands 
- git ls-remote --heads ssh://dickson@192.168.1.109/volume1/repo/ex-camel-rest-ms  (from level5 logs)
-  git clone ssh://dickson@diskstation.local/volume1/repo/ex-camel-rest-ms-ws

Both were successful and since the key is on my host it indicates that the git server is honoring ssh. However, this still does not verify Openshift VM's ability.

So this GIT_SSH variable I'm not seeing this and I'm not sure what this is or where it is being set. Is there some doco that explains this in sufficient detail?

**Comment by bparees** [comment]
can you try updating to a newer openshift version before we debug this further?  i don't want to chase a resolved issue.

**Comment by glennodickson** [comment]
Sure totally understand and have been wanting to do this for sometime. Is there an easy way of doing this or some doco to support this?  Will downloading a new OC and starting the cluster the only way to achieve this ? if so will my current configuration be preserved ?

**Comment by bparees** [comment]
@glennodickson the easiest thing just to confirm we can get this working for a newer version would be to grab the origin 1.5 release, and use "oc cluster up" to bring up a simple development cluster at the 1.5 level. (I don't know how/where you're running your existing cluster, i'm hoping you can do this on a separate machine and just not touch your existing cluster at all for the moment).

**Comment by glennodickson** [comment]
@bparees I've installed OSE 1.5 and executed the following steps:
```
oc secrets new buildsecret ssh-privatekey=c:\Users\dickson\.ssh\id_rsa
oc secrets add serviceaccount/builder secret/buildsecret
oc new-build fabric8/tomcat-8~ssh://dickson@192.168.1.102/volume1/repo/ex-camel-rest-ms --build-secret buildsecret --strategy=docker
```
I've executed the build and attached the level 5 logs : 
[ose1-5-level5-logs.txt](https://github.com/openshift/origin/files/990165/ose1-5-level5-logs.txt)

I've check keys according to the doco and as I've mentioned previously I can clone via the windows CLI which indicates that I'm using the right ones.

**Comment by bparees** [comment]
i don't think you've attached the secret to your build correctly.  you've specified a "secret" which is an input to the build, what you need to specify is a sourceSecret which is a secret used to perform the git clone.  Here's my source section from my BC:

```
    source:
      git:
        uri: ssh://git@github.com/bparees/nodejs-ex
      sourceSecret:
        name: buildsecret
      type: Git
```

you passed "--build-secret" to new-build, but the help for --build-secret explains what it's really for:
```
--build-secret=[]: Secret and destination to use as an input for the
build.
```

**Comment by glennodickson** [comment]
Yes seems to have progressed further producing the following output:

> Cloning "ssh://dickson@192.168.1.107/volume1/repo/ex-camel-rest-ms" ...
> 	Commit:	94c72aafa5d77e825dbd239bfffc670b1eb55bb2 (.)
> 	Author:	dickson <glennodickson@gmail.com>
> 	Date:	Thu Feb 2 23:47:57 2017 +0800
> error: build error: open /tmp/docker-build011785234/Dockerfile: no such file or directory

Not sure why its complaining about the docker (...) as my OC NEW-BUILD command supplies the tomcat image reference. Anyway, I'll look this up.

Also V1.5 provide screens to add sourceSecrets now which really helped.

As you might beware I'm rather new to Openshift and I really appreciate you're assistance. Thanks

**Comment by bparees** [comment]
You've defined a docker strategy build and you have not supplied a Dockerfile in your git repo (or supplied an inline dockerfile), so there's no way for the build to build your repo (since you are doing a docker strategy build, it's going to invoke docker build on your git repo content).

i'm going to close this issue since the SSH problem is resolved, but feel free to hit me up on irc.freenode.net in #openshift-dev if you need more help with your buildconfiguration.

**Comment by glennodickson** [comment]
Awesome, that's great and thanks so much.
