### ISSUE TITLE
high cpu usage of openshift when running in a docker container for a few days

### ISSUE THREAD

**Issue by rawlingsj** [openshift/origin#1386]
After having openshift running for a few days and actively using it the machine's performance degrades.  Doing a simple top shows it's the openshift process chewing up the cpu.

I know this is not much information but I wanted to track the issue incase others are seeing this.

https://gist.github.com/rawlingsj/2decbccf024d19e3ab48

Are there any suggestions on where to start to investigate?  I've had a brief look and couldn't see any obvious tools that can be used to help, debug or analyse high cpu go processes (I'm not familiar with go).

For info - after a docker kill and docker start openshift the process goes straight back up to high cpu usage.

**Comment by smarterclayton** [comment]
We have an integrated debug - restart openshift and set the environment variable OPENSHIFT_PROFILE=web.  That'll expose the profiling endpoint on http://127.0.0.1:6060/debug/pprof

You should be able to capture a CPU graph via http://127.0.0.1:6060/debug/pprof/profile?debug=1 (that'll run for 30 seconds by default and you may have to remove the debug flag to get it to generate a file output).  Can you send me that and the version you're running?

**Comment by danmcp** [comment]
Closing due to age without prejudice.
