### ISSUE TITLE
Router path parameters broken in 1.5

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#13862]
Routes that are created with a path / are now only responding to traffic in / and not any subsequent paths

ie.
Route: example.com
Path: /

example.com --> OK
example.com/test --> NOT OK

The web console has / as a suggested value
This was not the same behaviour in 1.4.1

##### Version
v1.5.0

**Comment by mignev** [comment]
👍

**Comment by markyjackson-taulia** [comment]
Dumb question maybe but did we not skip v1.5.0 in favor of v1.5.1 due to a security vulnerability?

**Comment by andrewklau** [comment]
I don't know about that, but this above will definitely be breaking apps for some users that upgrade.

**Comment by kargakis** [comment]
@knobunc

**Comment by smarterclayton** [comment]
@liggitt has investigated

**Comment by liggitt** [comment]
> Dumb question maybe but did we not skip v1.5.0 in favor of v1.5.1 due to a security vulnerability?

you may be thinking of kube 1.5.0. OpenShift 1.5.0 is based on kube 1.5.2

**Comment by liggitt** [comment]
fixed in #13867, will cherry-pick to release-1.5 branch

**Comment by pilhuhn** [comment]
That would explain a thing or two ...

**Comment by liggitt** [comment]
1.5 pick in https://github.com/openshift/origin/pull/13923

**Comment by andrewklau** [comment]
Will there be a release for this fix?

**Comment by budhrg** [comment]
@andrewklau , released with [1.5.1](https://github.com/openshift/origin/releases/tag/v1.5.1).
