### ISSUE TITLE
Some resources don't support list and/or watch, which breaks the kube garbage collector

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#13876]
These break the kube garbage collector controller unless we explicitly add their GroupVersionResources to the list to exclude from GC.

Missing watch:
- "authorization.openshift.io", Version: "v1", Resource: "clusterrolebindings"
- "authorization.openshift.io", Version: "v1", Resource: "clusterroles"
- "authorization.openshift.io", Version: "v1", Resource: "rolebindings"
- "authorization.openshift.io", Version: "v1", Resource: "roles"
- "image.openshift.io", Version: "v1", Resource: "imagestreamtags"

Missing list:
- "image.openshift.io", Version: "v1", Resource: "imagesignatures"
- "user.openshift.io", Version: "v1", Resource: "useridentitymappings"

**Comment by mfojtik** [comment]
all these are virtual resources, does it make sense to add list/watch to them? can those list/watches be just dummy? 

i mean when the imagestream is deleted, the imagestream tag is just a virtual resource, so it will go away as well automatically... does not need garbage collector.

**Comment by kargakis** [comment]
> all these are virtual resources

(cluster)roles and (cluster)rolebindings aren't virtual

**Comment by jwforres** [comment]
Please do not add dummy list/watch for virtual resources that have no reason for list/watch.  We are planning to use the new supported methods info that will be returned on API discovery (post-rebase) to know whether resources should show up in Other Resources, I'm trying to STOP maintaining a list of special things.

**Comment by ncdc** [comment]
Agreed. This is a tracking issue to figure out what to do. I think the
proper fix is a change to the Kube garbage collector controller.

**Comment by mfojtik** [comment]
@ncdc making the upstream GC controller more flexibe sounds much better than adding dummy/fake watches for things that should not have them.

**Comment by ncdc** [comment]
Yes, fake watches was not the idea I had in mind for a solution.

**Comment by mfojtik** [comment]
@ncdc is somebody looking into fixing this in kube GC controller? on arch call we talked about clientset generator skip generating watch/list for the resources that does not support it. Will that make sense?

@soltysh FYI

**Comment by ncdc** [comment]
@mfojtik I can fix GC upstream

**Comment by ncdc** [comment]
@mfojtik https://github.com/kubernetes/kubernetes/pull/45897
