### ISSUE TITLE
1.5.0. router is broken on 'oc cluster up'

### ISSUE THREAD

**Issue by oprudkyi** [openshift/origin#13873]
os:opensuse 42.1
origin: 1.5.0 (there wasn't such issue with 1.4.1 and earlier )

it's seems like router can't connect to API via internal IP

```
E0424 12:42:16.071027       1 reflector.go:188] github.com/openshift/origin/pkg/router/template/service_lookup.go:30: Failed to list *api.Service: Get https://172.30.0.1:443/api/v1/services?resourceVersion=0: dial tcp 172.30.0.1:443: i/o timeout
E0424 12:42:16.157643       1 reflector.go:188] github.com/openshift/origin/pkg/router/controller/factory/factory.go:68: Failed to list *api.Route: Get https://172.30.0.1:443/oapi/v1/routes: dial tcp 172.30.0.1:443: i/o timeout
E0424 12:42:16.157643       1 reflector.go:188] github.com/openshift/origin/pkg/router/controller/factory/factory.go:75: Failed to list *api.Endpoints: Get https://172.30.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 172.30.0.1:443: i/o timeout
```

to fix I forwarded router to master ip, i.e. added to environments 
```
            - name: KUBERNETES_SERVICE_HOST
              value: 172.16.0.2
            - name: KUBERNETES_SERVICE_PORT
              value: '8443'
```
and now everything works. 

##### Version
oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.16.0.2:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
'oc cluster up'

##### Current Result
routes don't work

**Comment by YannMoisan** [comment]
I have the same issue.

I've tried to fix with
```
oc cluster up -e KUBERNETES_SERVICE_HOST=192.168.0.26 -e KUBERNETES_SERVICE_PORT=8443
```
but it didn't work …

**Comment by oprudkyi** [comment]
@YannMoisan 
you have to add them into deployment config (via editing of yaml) or directly in the "Environment" tab or router deployment https://IP:8443/console/project/default/browse/dc/router?tab=environment

**Comment by oprudkyi** [comment]
the same issue with v3.6.0

**Comment by zonArt** [comment]
Same issue here

**Comment by zonArt** [comment]
A little update for me on this issue, I just notice that I'm actually still using version v1.5.1 for the router, is it something wrong with openshift-ansible update playbook ? It may change if I update the router version what do you think ?

**Comment by dlakatos847** [comment]
Still present with Origin v3.11 on OpenSuSE Tumbleweed.
