### ISSUE TITLE
RFE: provide an option to process only selected resources from template

### ISSUE THREAD

**Issue by yacekmm** [openshift/origin#13871]
Having a template yml file with several resources I want to process only a subset of them, preferably only those that are tagged with a certain tag. 

Thanks to such filter / selector I could tag some of my resources with 'backend', some with 'frontend' and could call `oc process | oc apply` to process only backend or only frontend resources.

It is important when the environment is complex and template file is the base of the config - kept in text file, versioned on a repo as Infrastructure as a Code. Those resources oftentimes has same parameters (like passwords, etc), so it is convenient to keep them in one file.

##### Additional Information
I'm using command combination: `oc process -f .\templateFile.yml | oc apply -f -`

**Comment by pweil-** [comment]
closing in favor of existing RFE in BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1439219
