### ISSUE TITLE
flake [builds][Conformance] build without output image 

### ISSUE THREAD

**Issue by abutcher** [openshift/origin#13888]
```
• Failure [57.048 seconds]
[builds][Conformance] build without output image
/go/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:54
  building from templates
  /go/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:53
    should create an image from a S2i template without an output image reference defined [It]
    /go/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:52

    Expected
        <bool>: false
    to be true

    /go/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:44
```

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/278/consoleFull#-181858664156cbb9a5e4b02b88ae8c2f77

**Comment by bparees** [comment]
this is pretty bizarre.  Somehow WaitForBuildResult returned while the build was still running, but w/o having timed out on waiting for the build.

**Comment by bparees** [comment]
```
Done waiting for test-sti-1: util.BuildResult{BuildPath:"build/test-sti-1", BuildName:"test-sti-1", StartBuildStdErr:"", StartBuildStdOut:"build/test-sti-1", StartBuildErr:error(nil), BuildConfigName:"", Build:(*api.Build)(0xc420d7d340), BuildAttempt:true, BuildSuccess:false, BuildFailure:false, BuildCancelled:false, BuildTimeout:true, LogDumper:(util.LogDumperFunc)(nil), oc:(*util.CLI)(0xc4205102d0)}
```

**Comment by bparees** [comment]
it looks like maybe we failed to list the builds here:
https://github.com/openshift/origin/blob/master/test/extended/util/framework.go#L556-L559

which would cause us to bomb out while the build is running, but then update it to mark it as timed out here:
https://github.com/openshift/origin/blob/master/test/extended/util/framework.go#L523

going to add some debug/logging.

**Comment by bparees** [comment]
debug PR here: https://github.com/openshift/origin/pull/13904

**Comment by bparees** [comment]
https://github.com/openshift/origin/pull/13904 doesn't actually fix this but it should ensure that if it recurs we'll have enough debugging to do something about it, so i'm going to let it close this issue.

(my only theory is that we're failing to list the builds, if that's true and it recurs as a flake we can consider making the test more robust to tolerate a failure to list the builds and retry).
