### ISSUE TITLE
API storage version changes from 3.6 to 3.7

### ISSUE THREAD

**Issue by enj** [openshift/origin#13885]
#### Required

- [x] Drop `HorizontalPodAutoscaler` from `extensions/v1beta1` and `oadm migrate` to ensure all are `autoscaling/v1` (the preferred storage version in `3.6` is `autoscaling/v1`)

#### Optional

- [x] Move `StorageClass.storage.k8s.io` from `v1beta1` to `v1`

**Comment by ncdc** [comment]
We need people to run `oadm migrate` using 3.6 before they upgrade to 3.7, right?

**Comment by enj** [comment]
> We need people to run `oadm migrate` using 3.6 before they upgrade to 3.7, right?

@ncdc Correct.  `oadm migrate` is required when you drop a `GVK`, so we would need to run it when we drop `HorizontalPodAutoscaler` from `extensions/v1beta1`, which will happen in `3.7`.

**Comment by liggitt** [comment]
So there are two tasks:
1. change the storage version
2. add to `oadm migrate`

**Comment by ncdc** [comment]
I can work on this unless someone else has already started?

**Comment by ncdc** [comment]
Ok, the default storage version for HPA is currently autoscaling/v1, so we don't need to make any changes there.

We currently test that existing `extensions/v1beta1.HPA` data in etcd is written as `autoscaling/v1.HPA` in `test/integration/storage_versions.test.go`. I'm assuming that `oadm migrate storage` will automagically just work for us to convert legacy extensions HPAs to autoscaling in etcd. Is that assumption correct? If so, it sounds like we don't need to do anything more for HPAs, other than document that admins must run `oadm migrate storage` before they install 3.7. Please let me know if any of this is incorrect.

Finally, do we want to deal with storageclass v1beta1 -> v1 now, or later in 3.7?

**Comment by liggitt** [comment]
> it sounds like we don't need to do anything more for HPAs, other than document that admins must run oadm migrate storage before they install 3.7

do we just document, or do we add checks that prevent them from upgrading while they still have etcd data with extensions/v1beta1 HPA?

> do we want to deal with storageclass v1beta1 -> v1 now, or later in 3.7?

we should do it the same release as kube did so we don't get caught carrying legacy types/groups

**Comment by ncdc** [comment]
> do we just document, or do we add checks that prevent them from upgrading while they still have etcd data with extensions/v1beta1 HPA?

Is there any way to definitively prevent an rpm (or containerized) upgrade from 3.6 to 3.7 if etcd still has extensions/v1beta1 HPA?

> we should do it the same release as kube did so we don't get caught carrying legacy types/groups

+1, I'll figure that out

**Comment by ncdc** [comment]
storageclass v1 was added in kube 1.6

**Comment by ncdc** [comment]
xref https://github.com/kubernetes/kubernetes/issues/45134

**Comment by sttts** [comment]
@deads2k added you. do you take care of this? There is a carry commit re-adding the old HPA types in 3.6.

**Comment by sttts** [comment]
@deads2k can you update this from the 3.7 rebase?

**Comment by deads2k** [comment]
> Drop HorizontalPodAutoscaler from extensions/v1beta1 and oadm migrate to ensure all are autoscaling/v1 (the preferred storage version in 3.6 is autoscaling/v1)

done


> Move StorageClass.storage.k8s.io from v1beta1 to v1

done

**Comment by sttts** [comment]
Closing after both tasks are done.

**Comment by mic4ael** [comment]
What about the docs (https://docs.openshift.com/container-platform/3.7/dev_guide/pod_autoscaling.html)? Since you don't support it, why do you still mention the `extensions..` API in the docs?

**Comment by DirectXMan12** [comment]
https://github.com/openshift/openshift-docs/pull/8135
