### ISSUE TITLE
Serverless support

### ISSUE THREAD

**Issue by mytototo** [openshift/origin#13883]
Hi there,

Is there any plans to have a serverless tool running on OpenShift? This way, we'd be able to build _functions as a service_ on top of Kubernetes.

Thanks.

**Comment by pweil-** [comment]
@mytototo FaaS is something we'd want to see fully supported upstream and hence supported on OpenShift.  There are a number of efforts going on in this space like (in no particular order or endorsement): [fission](http://fission.io/), [funktion](https://github.com/fabric8io/funktion), and [kubeless](https://github.com/bitnami/kubeless).
