### ISSUE TITLE
oc cluster up doesn't work with latest stable Docker4mac

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#13899]
##### Version
~/opt ❯❯❯ oc version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth

~/opt ❯❯❯ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

##### Steps To Reproduce
1. oc cluster up

##### Current Result
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... FAIL
   Error: Minor number must not contain leading zeroes "03"

**Comment by php-coder** [comment]
CC @csrwng

**Comment by csrwng** [comment]
Please use the released v1.5.0 version of the oc binary

**Comment by csrwng** [comment]
Alternatively, you can downgrade docker to 1.13.1:
https://download.docker.com/mac/stable/1.13.1.15353/Docker.dmg

**Comment by pweil-** [comment]
closing with above solutions
