### ISSUE TITLE
Extended test failure: "should contain the failure reason related to failing to fetch runtime image artifacts"

### ISSUE THREAD

**Issue by oatmealraisin** [openshift/origin#13894]
[This test](https://github.com/openshift/origin/blob/b01ec19131b1fffb03a3f306f45d8d6c8225eff7/test/extended/builds/failure_status.go#L156) seems to be running into a timing issue.

```
Did not find a "BuildFailed" event on build extended-test-update-buildstatus-g1cr4-mdz07/statusfail-runtimeartifacts-1
    Expected
        <bool>: false
    to be true
```
[Jenkins logs](https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/42/consoleFull#-169259343956c60d7be4b02b88ae8c268b)

@bparees fyi

**Comment by stevekuznetsov** [comment]
Why p2?

**Comment by bparees** [comment]
doesn't block the merge queue. it's an extended test and not in the conformance bucket.

**Comment by bparees** [comment]
(and i'm reasonably confident it's a flake and not an actual bug in the feature code)
