### ISSUE TITLE
Poor error message about invalid uid/gid range

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#13908]
When user tries to use too big group in the `fsGroup`, validation fails with the following error:

>spec.template.spec.securityContext.fsGroup: Invalid value: 3000030000: must be between 0 and 2147483647, inclusive

The 2147483647 is also couldn't be found in the sources with `git grep` that makes debug more difficult.

I suggest to [modify this message](https://github.com/openshift/origin/blob/33052f6494d53dc563f8ee80babc419b24cfe79d/vendor/k8s.io/kubernetes/pkg/util/validation/validation.go#L184-L199) to explicitly says about invalid GID. If we'll decide to do that we should also take into account [validation of `runAsUser` and `supplementalGroups` fields](https://github.com/openshift/origin/blob/33052f6494d53dc563f8ee80babc419b24cfe79d/vendor/k8s.io/kubernetes/pkg/api/validation/validation.go#L2249-L2272).

This has been reported by @mfojtik initially.

**Comment by php-coder** [comment]
@pweil- WDYT?

**Comment by pweil-** [comment]
I'm not clear about what you're proposing to change the error message to since it already says it's the `fsGroup` field, lists the invalid number, and gives the valid values.  I guess you could put the word GID in the SCC validation - not changing the upstream message since that is using a generic InclusiveError

**Comment by php-coder** [comment]
>  I guess you could put the word GID in the SCC validation - not changing the upstream message since that is using a generic InclusiveError

Yes, to make it like this:

>spec.template.spec.securityContext.fsGroup: Invalid value: 3000030000: **invalid user group:** must be between 0 and 2147483647, inclusive
