### ISSUE TITLE
superfluous warnings displayed by oc status

### ISSUE THREAD

**Issue by jeremyeder** [openshift/origin#13913]
[provide a description of the issue]
```
$ oc status -v
<snip>
Warnings:
  * Unable to list petsets resources.  Not all status relationships can be established.
```
##### Version
[provide output of the `openshift version` or `oc version` command]
```
 $ oc version
oc v1.3.3
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://example.com:443
openshift v3.5.5.10
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. [step 1]
Create a cakephp+mysql persistent example/template.

2. [step 2]
run ```oc status```

##### Current Result
A superfluous warning is displayed.

##### Expected Result
```oc status``` should not show warnings if they're not relevant.

##### Additional Information
- Parts of this were addressed in #11403 and originally reported in issue 10269.
- petsets were renamed...

**Comment by mfojtik** [comment]
@jeremyeder do we have any templates in examples that use petset and not statefullset ?

**Comment by jeremyeder** [comment]
Just grep'd the origin/examples dir, and no, it doesn't look like we are referencing petsets anywhere.

I'm using https://github.com/openshift/origin/blob/master/examples/quickstarts/cakephp-mysql-persistent.json

**Comment by kargakis** [comment]
@mfojtik this should be fixed now, right?
