### ISSUE TITLE
Using oreg_url in hosts doesn't work if private registry requires authentication

### ISSUE THREAD

**Issue by johnr-spindance** [openshift/origin#13918]
(for privacy, renamed our domain to example.com and removed url of openshift master)

##### Version
```
$ oc version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://**************:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce

- Setup a Nexus OSS server and synced openshift/origin-pod and openshift/origin-deployer images to it.
- Nexus doesn't have an option for anonymous pull
- OpenShift installed with:
```
oreg_url=nexus.example.com:5000/openshift/origin-${component}:${version}
```
- When running a deployment config, it fails because it doesn't have credentials:
```
Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "image pull failed for nexus.example.com:5000/openshift/origin-pod:v1.3.0, this may be because there are no credentials on this request. details: (Get https://nexus.example.com:5000/v2/openshift/origin-pod/manifests/v1.3.0: no basic auth credentials)"
```
- I added the docker secrets to router and deploy service accounts:
```
oc create secret docker-registry nexus-release --docker-server=nexus.example.com:5000 --docker-username=<my username> --docker-password="<my password>" --docker-email=ops@example.com

oc secrets link serviceaccounts/default secrets/nexus-release --for=pull
oc secrets link serviceaccounts/router secrets/nexus-release --for=pull
oc secrets link serviceaccounts/deployer secrets/nexus-release --for=pull

oc adm policy add-scc-to-user privileged system:serviceaccount:default:router:deployer
```

Right now, my workaround is to ssh to the individual hosts, sudo su as root, and do a docker login / docker pull to get these images from the private registry. Once I have done this, the deployment configs are able to successfully do their deploy using the origin-pod and origin-deployer containers and also successfully pull / deploy our app containers from the SAME registry I was trying to use.

I can only determine that OpenShift is trying to get its "origin-*" pods without authentication as it normally gets them from docker hub. This creates a somewhat difficult situation for us because we are deploying OpenShift Origin in a "disconnected environment" (ie. no internet). Now I know the OpenShift Enterprise documentation suggests importing these images with docker save / docker load, but why should that be necessary? Why can't we just have OpenShift get them from the same private registry as the apps I'm trying to deploy from? Why can't we be able to provide credentials when its needed?

So I'm opening an issue because there should be an option to provide credentials to authenticate to a private registry that we specify with the "ore_url" var in openshift-ansible and we shouldn't have to use the "recommended" method of docker save to a tar, scp the tar, then docker load.

Please provide a way to pass credentials for these cases.

##### Current Result
Currently, OpenShift seems to only pull its "origin-*" containers by using a registry that allows for anonymous pull (no authentication).

##### Expected Result
I would expect that there be an option available to provide credentials in a situation where those containers must be pulled from a disconnected environment without internet where credentials for a registry are required.

**Comment by stevekuznetsov** [comment]
Assigning @sdodson for triage/

**Comment by sdodson** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1316341 has some prior discussion on this topic, there's regrettably a number of private comments where folks have tried one thing or another but I think the redux is that we should perform a `docker login` then copy `~/.docker/config.json` from that user to `/var/lib/origin/config.json` everything should work.

@ncdc Am I reading that bug correctly?  We don't even need to add secrets to the service accounts or do we need to do that too?

**Comment by ncdc** [comment]
@sdodson yes that is what is documented in the bz. However I believe that when the kubelet pulls an image, it unions the credentials in that `config.json` with whatever secrets are available to the user/serviceaccount creating a container, which means that users could get access to images via the credentials in `config.json` that they otherwise shouldn't be able to. Is that still correct @deads2k @liggitt @derekwaynecarr?

**Comment by johnr-spindance** [comment]
These are great thoughts. We're using .dockercfg in the secrets for pull. Can we use config.json instead?

**Comment by deads2k** [comment]
> I believe that when the kubelet pulls an image, it unions the credentials in that config.json with whatever secrets are available to the user/serviceaccount creating a container, which means that users could get access to images via the credentials in config.json that they otherwise shouldn't be able to. Is that still correct @deads2k @liggitt @derekwaynecarr?

Yes, that is correct.

**Comment by sdodson** [comment]
This would be an external registry rather than the internal registry so I think we'd just want to note that anyone on the cluster would have access to images these credentials grant access to.

**Comment by johnr-spindance** [comment]
Is there any further consideration for this issue. Are there any known work-arounds to the credentials issue?

**Comment by sdodson** [comment]
@johnr-spindance you should be able to run `docker login` and then copy $HOME/.docker/config.json to /var/lib/origin and the kubelet will pick it up.

**Comment by sdodson** [comment]
This is now possible.

https://github.com/openshift/openshift-ansible/blob/master/inventory/hosts.example#L221-L227

/close

**Comment by canit00** [comment]
@sdodson this is still a current issue in 3.7.44 OCP which we're still unable to work around. I am failing to understand the section that you highlighted will help in this case?

**Comment by sdodson** [comment]
Sorry, that code has changed since I linked to the master branch so the lines are offset. These are the two variables I was speaking of, they will be used to log into the registry specified by oreg_url if they're set. Leading to ~ansible_user/.docker/config.json and /var/lib/origin/.docker/config.json having credentials for the registry which should make everything work.

#oreg_auth_user=some_user
#oreg_auth_password='my-pass'

**Comment by canit00** [comment]
Thank you @sdodson Finally were able to deploy! Do you know if there is any direction where this process will be documented better or change to save user's time?

My example:
```
---
- hosts: all
  gather_facts: no
  tasks:
  - name: create docker dir
    file:
      path: /var/lib/openshift/.docker
      state: directory

  - name: populate config.json
    copy:
      dest: /var/lib/openshift/.docker/config.json
      content: |
        {
                "auths": {
                        "registry00.com:5000": {
                                "auth": "TYbunybnfeunkbjnb="
                        },
                        "registry01.com:5000": {
                                "auth": "vgbhjnfcgvbhjnfcg="
                        }
                }
        }
```
