### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by robstryker** [openshift/origin#13929]
[provide a description of the issue]
When accessing jolokia without authorization, the reseponse string violates expectations of Jolokia's client jars and the published response spec. 

Spec: https://jolokia.org/reference/html/protocol.html#responses

Specifically, the field "status" is guarenteed to return an integer, but openshift is returning a string. 

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v3.3.1.5
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.99.100:8443
openshift v3.5.5.5
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Current Result
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot get pods/unsafeproxy in project \"test1\"",
  "reason": "Forbidden",
  "details": {
    "name": "camel-ose-springboot-xml-1-xgu2e:8778",
    "kind": "pods/unsafeproxy"
  },
  "code": 403
}

##### Expected Result
{
   "value": .... ,
   "status" : 403,
   "timestamp" : 1244839118,
   "request": {
               "type": ...,
               ....
              },
   "history":[
               {"value": ... ,
                "timestamp" : 1244839045
               }, ....
             ]
 }

##### Additional Information
https://github.com/rhuss/jolokia/pull/292#issuecomment-293350685
https://issues.jboss.org/browse/JBIDE-23869

**Comment by liggitt** [comment]
If you access the Jolokia API via the OpenShift pod proxy endpoint, the responses to unauthorized requests will be OpenShift API responses, and will have nothing to do with the application running in the pod. The fact that OpenShift returns a body similar to the the jolokia API is pure coincidence.
