### ISSUE TITLE
oadm migrate image-references fails in CI

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#13924]
https://github.com/openshift/origin/blob/master/test/cmd/migrate.sh#L55-L61 is flaking in CI.

This needs to fixed, but we've disabled it for now post-rebase.

**Comment by smarterclayton** [comment]
How long has it been flaking?

**Comment by smarterclayton** [comment]
Only rebase?

**Comment by sttts** [comment]
During rebase I saw it only once: in the final test run. Have we had it more often? /cc @soltysh

**Comment by pweil-** [comment]
@mfojtik FYI

**Comment by ncdc** [comment]
I uncommented it locally and it passed for me the one time I've run it so far. I'll do it in a loop and see how it goes.

**Comment by ncdc** [comment]
Ran it 3 or 4 more times, no flakes.

**Comment by deads2k** [comment]
> I uncommented it locally and it passed for me the one time I've run it so far. I'll do it in a loop and see how it goes.

You should try it in CI. It was failing every single run.

**Comment by soltysh** [comment]
Looking into it right now...

**Comment by soltysh** [comment]
I've tried it multiple (>10) times locally, checking once again on aws, if I don't see anything suspicious during those runs I'll open a PR later today.
