### ISSUE TITLE
Pods Set QOS Class should be submitted and removed

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#13936]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1005/consoleFull#-169259343956c60d7be4b02b88ae8c268b

@sttts @derekwaynecarr

**Comment by sttts** [comment]
```
Apr 27 16:59:42.562: INFO: Couldn't delete ns: "e2e-tests-pods-lt2f1": namespace e2e-tests-pods-lt2f1 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed (&errors.errorString{s:"namespace e2e-tests-pods-lt2f1 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed"})
```

@ncdc you have looked into similar issues during the rebase, haven't you?

**Comment by ncdc** [comment]
@sttts I noticed that deleting namespaces was taking longer than I expected, but I didn't dig into it.
