### ISSUE TITLE
TestUpdateNodeWithMultiplePods

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#13941]
--- FAIL: TestUpdateNodeWithMultiplePods (1.76s)
	taint_controller_test.go:523: Failed to deleted pod pod1 after 0
	taint_controller_test.go:523: Failed to deleted pod pod2 after 1
	taint_controller_test.go:523: Failed to deleted pod pod3 after 2

@sttts you said you were looking at this one.

**Comment by sttts** [comment]
Fixed in https://github.com/openshift/origin/pull/13940.
