### ISSUE TITLE
hack/test-end-to-end-docker.sh:79: `oc cluster up --server-loglevel=4 --version="${TAG}" --host-data-dir="${VOLUME_DIR}/etcd" --host-volumes-dir="${VOLUME_DIR}"` exited with status 1.

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#13945]
oc cluster-up fails

hack/test-end-to-end-docker.sh:79: `oc cluster up --server-loglevel=4 --version="${TAG}" --host-data-dir="${VOLUME_DIR}/etcd" --host-volumes-dir="${VOLUME_DIR}"` exited with status 1.

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1006/

```
++ Docker is installed, running hack/test-end-to-end-docker.sh instead.
[INFO] Starting containerized end-to-end test
[INFO] openshift version: openshift v3.6.0-alpha.1+6cf37aa-293
[INFO] kubernetes v1.6.1+5115d708d7
[INFO] etcd 3.1.0
[INFO] oc version:        oc v3.6.0-alpha.1+6cf37aa-293
[INFO] kubernetes v1.6.1+5115d708d7
[INFO] features: Basic-Auth GSSAPI Kerberos SPNEGO
[INFO] Using images:							openshift/origin-${component}:6cf37aa
[INFO] Starting OpenShift containerized server
Starting OpenShift using openshift/origin:6cf37aa ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:6cf37aa image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
FAIL
   Error: Get https://127.0.0.1:8443/api: EOF
[ERROR] PID 765: hack/test-end-to-end-docker.sh:79: `oc cluster up --server-loglevel=4 --version="${TAG}" --host-data-dir="${VOLUME_DIR}/etcd" --host-volumes-dir="${VOLUME_DIR}"` exited with status 1.
```

@stevekuznetsov @dobbymoodge I can't find the openshift.log in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/1518/s3/ .  Where are we saving the container logs?

**Comment by stevekuznetsov** [comment]
Looks like we _are_ dumping container logs, and you would find them in S3 under `scripts/script-name/logs/containers`, but we're looking for the `k8s` prefix to select which containers we log and kill. No logic also exists for the `origin` container (or any other containerized components).

**Comment by ncdc** [comment]
@stevekuznetsov can we fix that? What file do we need to edit?

**Comment by stevekuznetsov** [comment]
https://github.com/openshift/origin/issues/13949

**Comment by stevekuznetsov** [comment]
I'll look into it this morning

**Comment by stevekuznetsov** [comment]
I'll grab logs but past that I am not sure this one is on me ;)

**Comment by sttts** [comment]
@stevekuznetsov any news about the logs?

**Comment by stevekuznetsov** [comment]
@sttts was able to address that in https://github.com/openshift/origin/issues/13952 a couple weeks ago -- logs should be present

**Comment by sttts** [comment]
Found the following in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/1889/console of https://github.com/openshift/origin/pull/14121:
```
F0509 22:44:35.253443   18718 kubelet.go:1235] Failed to start cAdvisor readdirent: no such file or directory
```

**Comment by sttts** [comment]
@derekwaynecarr have you seen that before ^^ ? We could patch the cAdvisor Start func to get some more info. Googling leads to many reports with that error message.

**Comment by stevekuznetsov** [comment]
Not pertinent anymore
/close

**Comment by juanvallejo** [comment]
Seeing this in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_end_to_end/14908/ 
Seeing it happen repeatedly for end-to-end tests for https://github.com/openshift/origin/pull/20282
