### ISSUE TITLE
TestUpdateNode: taint_controller_test.go:440: Only one added taint tolerated: Unexepected test result. Expected delete true, got false

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13946]
Seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_check/1531/testReport/junit/github.com_openshift_origin_vendor_k8s/io_kubernetes_pkg_controller_node/TestUpdateNode/

```
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.TestUpdateNode (from github.com_openshift_origin_vendor_k8s.io_kubernetes_pkg_controller_node)


=== RUN   TestUpdateNode
--- FAIL: TestUpdateNode (4.71s)
	taint_controller_test.go:440: Only one added taint tolerated: Unexepected test result. Expected delete true, got false
```

**Comment by mfojtik** [comment]
@sttts maybe related to https://github.com/openshift/origin/issues/13941 ?

**Comment by mfojtik** [comment]
(also there is a typo in the error message ;-)

**Comment by sttts** [comment]
#13941  was only bad timing in the tests, `time.Sleeps`. Will take a look here.

**Comment by sttts** [comment]
This involves timing as well. It starts the controller, waits 200ms and hopes that the controller process everything.
