### ISSUE TITLE
github.com/openshift/origin/test/cmd/debug.test/cmd/debug.sh:37: executing 'oc get imagestreamtags wildfly:latest' expecting success

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#13944]
github.com/openshift/origin/test/cmd/debug.test/cmd/debug.sh:37: executing 'oc get imagestreamtags wildfly:latest' expecting success; re-trying every 0.2s until completion or 60.000s

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1001/

I haven't confirmed it wasn't just a case of dockerhub down or something.

**Comment by ncdc** [comment]
It looks like the hub or something in front of the hub was down. The import for `cmd-debug/wildfly` got some status.tags, but a bunch had ImportSuccess=False and got 503 Service Temporarily Unavailable.

Should we close this?

**Comment by deads2k** [comment]
> It looks like the hub or something in front of the hub was down. The import for cmd-debug/wildfly got some status.tags, but a bunch had ImportSuccess=False and got 503 Service Temporarily Unavailable.

sure

**Comment by smarterclayton** [comment]
We're talking about moving our dependent images someplace reliable.
