### ISSUE TITLE
Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] 

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#13942]
Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Scaling down before scale up is finished should wait until current pod will be running and ready before it will be removed

**Comment by deads2k** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1023/

**Comment by sttts** [comment]
Fixed in https://github.com/openshift/origin/pull/13939

**Comment by sttts** [comment]
The panic is actually fixed by #13939. Now we see a broken watch.

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/1588
