### ISSUE TITLE
Extended.[builds][Conformance] s2i build with a quota Building from a template should create an s2i build with a quota and run it

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#13947]
Extended.[builds][Conformance] s2i build with a quota Building from a template should create an s2i build with a quota and run it

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1014/

**Comment by sttts** [comment]
```Cannot connect to the Docker daemon. Is the docker daemon running on this host?```

Looks like a flake. I would wait here until it happens again.

**Comment by sttts** [comment]
Assuming it was a flake. Reopen if it happens again.
