### ISSUE TITLE
ServiceAccount token unusable via Websocket

### ISSUE THREAD

**Issue by brilliantmichael** [openshift/origin#13968]
We would like to create a visual-ops style dashboard of events in an Openshift cluster. To do this we are thinking of using a cluster-reader ServiceAccount and then using the long-lived kubernetes token to subscribe to events.

This works fine when using a plain user's openshift token, for example:

```js
  const socket = new WebSocket(
    "wss://www.example.com:8443/oapi/v1/users" +
    "?resourceVersion=0&watch=true&access_token=" + userToken,
    ["websocket"]
  )

  socket.onmessage = function (event) {
    console.log(JSON.parse(event.data));
  }
```
However using a ServiceAccount token yields a 403 unauthorized error. Funnily enough it works authenticating HTTP requests via the Bearer token. Is there a different method to use ServiceAccount tokens to authenticate a websocket connection?

```
oc project <project>
oc describe ServiceAccount monitor
oc describe secret monitor-token-a1b2c
```

##### Version
```
oc version
oc v3.2.0.46-1-g3fab54d
kubernetes v1.2.0-36-g4a3f9c5
```

##### Steps To Reproduce
1. Obtain the long-lived token for a ServiceAccount (as above)
2. Attempt to use this token to subscribe to the API via Websockets (as above)

##### Current Result (Unable to authenticate)
```
WebSocket connection to 'wss://www.example.com:8443/oapi/v1/users
?resourceVersion=0&watch=true&access_token=<serviceaccount_token>'
failed: HTTP Authentication failed; no valid credentials available
```
##### Expected Result (Success)
```
Request URL: wss://www.example.com:8443/oapi/v1/users
?resourceVersion=0&watch=true&access_token=<user_token>
Request Method:GET
Status Code:101 Switching Protocols
```

**Comment by deads2k** [comment]
Opened https://github.com/openshift/origin/pull/13978, but I'm actually unsure how to test it.

@brilliantmichael any chance you're in a position to build the branch and check this?

**Comment by pweil-** [comment]
@enj FYI
