### ISSUE TITLE
Extended.deploymentconfigs when run iteratively [Conformance] should only deploy the last deployment

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#13973]
Extended.deploymentconfigs when run iteratively [Conformance] should only deploy the last deployment

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/514/

**Comment by stevekuznetsov** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/514/testReport/junit/(root)/Extended/deploymentconfigs_when_run_iteratively__Conformance__should_only_deploy_the_last_deployment/

**Comment by mfojtik** [comment]
@stevekuznetsov any new occurences of this or any logs I can start looking at?

**Comment by mfojtik** [comment]
bumping to P2 due to age

**Comment by mfojtik** [comment]
Closing as this haven't reccured and we don't have any logs.
