### ISSUE TITLE
[k8s.io] Daemon set [Serial] [It] Should update pod when spec was updated and update strategy is RollingUpdate

### ISSUE THREAD

**Issue by eparis** [openshift/origin#13977]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/506/consoleFull#-169259343956c60d7be4b02b88ae8c268b

from https://github.com/openshift/origin/pull/13847

**Comment by stevekuznetsov** [comment]
[This error](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/506/testReport/junit/(root)/Extended/_k8s_io__Daemon_set__Serial__Should_update_pod_when_spec_was_updated_and_update_strategy_is_RollingUpdate/) doesn't make a lot of sense...

```
/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/daemon_set.go:322
Expected
    <int>: 0
to be >
    <int>: 0
/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/daemon_set.go:445
```

**Comment by bparees** [comment]
fresh logs:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/1075/testReport/junit/(root)/Extended/_k8s_io__Daemon_set__Serial__Should_update_pod_when_spec_was_updated_and_update_strategy_is_RollingUpdate/

**Comment by derekwaynecarr** [comment]
@jboyd01 - can you look at this test and see if you can make sense of what is going on.

in particular, why https://github.com/openshift/origin/issues/13977#issuecomment-298366756 is not helpful output.

**Comment by kargakis** [comment]
Recurred at least twice today

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3322/

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/view/All/job/merge_pull_request_origin/1340/

**Comment by kargakis** [comment]
We should move serial tests to run as post-submits. Then we can use post-submit results from GCS buckets to block merges with the submit queue.

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/4538/

**Comment by stevekuznetsov** [comment]
Ignoring problems until they go away is ultimately the best approach...
