### ISSUE TITLE
Building pull-requests on OpenShift?

### ISSUE THREAD

**Issue by alikhajeh1** [openshift/origin#13970]
We're using the postCommit buildConfig hook to run tests before pushing the image. We've also configured GitHub to trigger a build on new commits on the master branch.

Currently there doesn't seem to be way to do this for pull-requests, so we still need things like TravisCI/Jenkins to run tests on pull-requests before we merge them. It seems OpenShift is very close to being able to do this though, e.g. if I could configure the buildConfig to dynamically set the source > git > ref value from the git SHA in the payload of the webhook. Such a buildConfig could then tag the built image with the branch name, which could then be deployed on not depending on what users want to do.

Maybe there's another way that I'm not aware of?

##### Version
```
oc v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
features: Basic-Auth

Server xxx
openshift v1.4.1
kubernetes v1.4.0+776c994
```

**Comment by bparees** [comment]
Though strangely our docs don't seem to mention it, when you use a github webhook openshift does set the ref to the payload of the webhook, however the github webhook only respects push events today:

https://github.com/openshift/origin/blob/master/pkg/build/webhook/github/github.go#L66-L82

The code also confirms that the commit in question is relevant to the branch the buildconfig is setup to build, so if you have a buildconfig that builds the "dev" branch of your repo, and you push a commit to the "test" branch, the buildconfig will not be triggered.

In any case, we recently found a limitation w/ respect to testing PR branches which take a slightly different ref form than a standard branch or commit and delivered a fix a few days ago:
https://github.com/openshift/origin/pull/13893

Using the generic webhook you ought to at least be able to trigger a build against any ref you want (including PR branches, with the above fix):
https://docs.openshift.org/latest/dev_guide/builds/triggering_builds.html#generic-webhooks

For my part I think i need to know what github webhook event you are intending to have sent to openshift and what the payload will be, to understand if there's a code change we need to make here for that part of your request.

For the second part, dynamically tagging the output image based on the commit that was built, that is part of this card which is on our backlog of things we'd like to do: https://trello.com/c/nOX8FTRq

**Comment by gabemontero** [comment]
generic webhooks *possibly could* also allow you to process other events besides push (though a http proxy would be needed I believe to translate the URL to the generic webhook endpoint)

**Comment by gabemontero** [comment]
documentation pull https://github.com/openshift/openshift-docs/pull/4293 has been initiated to improve the documentation in this space

**Comment by stevekuznetsov** [comment]
To what extent are we going to be positioning ourselves behind the triggers/"pure `dc`" mechanism for this? There are a couple comprehensive GitHub pull request triggering plugins for Jenkins that come to mind, would that not be the more appropriate choice?

**Comment by bparees** [comment]
> To what extent are we going to be positioning ourselves behind the triggers/"pure dc" mechanism for this? 

"to some extent".  Yes, for sophisticated triggering scenarios we definitely recommend users use a jenkins job (or other CI tool) as the mechanism for triggering their build flow, since openshift will probably never expand to support every possibly webhook event and schema.  But that said, github is a common enough use case that we want to make it possible to trigger openshift builds w/o introducing a jenkins (or other CI) layer, for most people.

**Comment by stevekuznetsov** [comment]
So the line in the sand here would be -- if you want the build triggered for every PR, regardless of who made the PR, etc, we may in the future support this. Past that, use Jenkins?

**Comment by bparees** [comment]
> So the line in the sand here would be -- if you want the build triggered for every PR, regardless of who made the PR, etc, we may in the future support this. Past that, use Jenkins?

The line in the sand is probably at least that far, anyway.  I'm not prepared to declare what we will never support.

**Comment by alikhajeh1** [comment]
> Using the generic webhook you ought to at least be able to trigger a build against any ref you want (including PR branches, with the above fix):
https://docs.openshift.org/latest/dev_guide/builds/triggering_builds.html#generic-webhooks
For my part I think i need to know what github webhook event you are intending to have sent to openshift and what the payload will be, to understand if there's a code change we need to make here for that part of your request.

Thanks @bparees, here are the events I was thinking of (let me know if you'd me to dig-up/create example payloads for each):
GitHub: `Pull request` and `Push` events so we can build PRs and any pushes to those PRs.
GitLab: `Push events` (they don't seem to have an event for new PRs)
BitBucket: `Repository > Push` and `Pull Request > Created`events

> For the second part, dynamically tagging the output image based on the commit that was built, that is part of this card which is on our backlog of things we'd like to do: https://trello.com/c/nOX8FTRq

Sounds good. I'm thinking users can do this until that card is progressed:
1. Have a BuildConfig that just runs tests.
2. Create the above webhooks to build all commits that are pushed.
3. Run the tests and update the status of the commit in GitHub/GitLab/BitBucket.
4. Always exit 1 so no images are pushed.

Users could have a separate BuildConfig for their master branch that then just runs tests and pushes the image if the tests pass.

**Comment by bparees** [comment]
> GitHub: Pull request and Push events so we can build PRs and any pushes to those PRs.

github push events are supported today, supporting PR events would be a new feature, but it's not obvious to me we can get an event when a new commit is pushed to an existing PR, which is what you'd really need for this to be useful.  For now i'm inclined to say jenkins plugins provide better support for PR-based triggering than we're likely to provide.

> GitLab: Push events (they don't seem to have an event for new PRs)

gitlab push events are implemented now, they'll be part of OCP3.6:
https://docs.openshift.org/latest/dev_guide/builds/triggering_builds.html#gitlab-webhooks


> BitBucket: Repository > Push and Pull Request > Createdevents

BitBucket push is implemented now, willl be part of OCP3.6: https://docs.openshift.org/latest/dev_guide/builds/triggering_builds.html#bitbucket-webhooks

for Push support again i'm inclined to say Jenkins probably does more in this space than we're likely to try to keep pace with in openshift itself.

> Always exit 1 so no images are pushed.

you can just define a buildconfig with no output image.

**Comment by bparees** [comment]
based on what we provide currently(which includes the ability to build the specific commit that was pushed to a branch) and what we're (un)likely to provide, I don't think there's a clear next action on this.

**Comment by alikhajeh1** [comment]
@bparees am I right in thinking that the simplest way to build pull-requests (run unit tests) is to:
1. Have a BuildConfig, let's say pr-builder, it doesn't matter what source Repo/Ref it uses as long it has the correct sourceSecret so it can clone private repos. Delete the ImageStream for it so it just runs tests.
2. Write a small app that receives webhooks from GitLab/GitHub/BitBucket. If the commit in the webhook is something we want to build, this app uses the `oc` CLI/API to update the source Repo/Ref of pr-builder, then calls `oc start-build` on it.

I [looked into](https://github.com/openshift/origin/pull/13893/files#diff-b2838f8df02d5913c246a3b2783d277eR11) using `Source Ref: refs/pull/X/head` where X is the PR number but that doesn't seem to help in this case as X can't be automatically set from the webhook itself.

**Comment by bparees** [comment]
you can pass --commit to oc start-build rather than updating the source of the pr-builder (contrary to the name, it can be any valid git ref for the repo).  but otherwise your summary is accurate.  (I'd also consider Jenkins instead of "a small app").
