### ISSUE TITLE
How can I enable template service broker in origin 3.6.0-alpha.1

### ISSUE THREAD

**Issue by yepengxj** [openshift/origin#13971]
I ran a 3.6.0-alpha.1 origin cluster in  docker and  enabled template service broker by  `openshift ex config patch "${SERVER_CONFIG_DIR}/master/master-config.orig2.yaml" --patch="{\"enableTemplateServiceBroker\": true}"  > "${SERVER_CONFIG_DIR}/master/master-config.yaml"`  , but I can't find how to use template service broker to provision a service and web-console do not display binding menu. what can I do to enable template service broker, thanks very much

**Comment by maleck13** [comment]
@yepengxj  I did something similar and was able to use this by trying the scripts in  https://github.com/openshift/origin/tree/master/pkg/template/servicebroker/test-scripts

**Comment by jim-minter** [comment]
In addition to enabling the TSB, you can allow unauthenticated users to access the API by applying https://github.com/openshift/origin/tree/master/pkg/template/servicebroker/test-scripts/clusterrole.yaml .  See the README.md file in the same directory.  Following on from that, as mentioned you can try out the test scripts.  Make sure you have at least one template in the openshift namespace already.

As regards the service catalog and web console pieces, I don't know the answer; perhaps @pmorie or @jwforres could provide further detail.
