### ISSUE TITLE
Docker service crashed

### ISSUE THREAD

**Issue by jagadeeshops** [openshift/origin#13987]
We are running 3 master, 3 etcd and 8 nodes cluster.
We are using RHEL 7.2 . In the last week, docker service crashed in 3 servers with the following error 
"fatal error: unexpected signal during runtime execution 
sigpanic()". 
Docker version is 1.9.1
Containers running on those servers are rescheduled.
But liveliness check and readiness check were failing for some time. But the actual container itself is killed.

##### Version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v1.4.1
kubernetes v1.4.0+776c994
Docker version 1.9.1

##### Steps To Reproduce
Its occuring in a random fashion

##### Current Result
Docker is crashing
##### Expected Result
Docker should not crash

**Comment by pweil-** [comment]
@jagadeeshops the 1.4/3.4 release requires Docker 1.12 (https://docs.openshift.com/container-platform/3.4/install_config/install/prerequisites.html).  Please try upgrading and see if you can still reproduce.

**Comment by jwhonce** [comment]
@jagadeeshops Please provide the docker logs showing the panic and stack trace.  Thank you.

**Comment by jagadeeshops** [comment]
@jwhonce I am attaching the logs
[dockerlogs.txt](https://github.com/openshift/origin/files/972760/dockerlogs.txt)

**Comment by jagadeeshops** [comment]
@pweil- I will try that option and post the results

**Comment by jagadeeshops** [comment]
@pweil- Our initial cluster version is 1.2.1.
Our current version is 1.4.1. We installed and upgraded through openshift-ansible scripts.
Its using the below repo
"centos-openshift-origin".
Current docker package name is "docker-1.9.1-25.1.origin.el7.x86_64".
Its tied up with origin. If i uninstall docker, origin-node package is also getting uninstalled.

**Comment by jagadeeshops** [comment]
@pweil- @jwhonce 

Found the problem and workaround.
Changed the logging driver for Docker from "journald" to "json-file".
This change fixed the issue and now docker is not crashing.
