### ISSUE TITLE
Flake deploymentconfigs with test deployments [Conformance] [It] should run a deployment to completion and then scale to zero 

### ISSUE THREAD

**Issue by abutcher** [openshift/origin#13980]
```
• Failure [26.555 seconds]
deploymentconfigs
/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:908
  with test deployments [Conformance]
  /go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:309
    should run a deployment to completion and then scale to zero [It]
    /go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:308

    Expected
        <string>: --> pre: Running hook pod ...
        test pre hook executed
        --> pre: Success
        --> Scaling deployment-test-1 to 2
        --> Waiting up to 10m0s for pods in rc deployment-test-1 to become ready
    to contain substring
        <string>: --> Success

    /go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:256
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible/87/consoleFull#-210271339656cbb9a5e4b02b88ae8c2f77

**Comment by enj** [comment]
Seen in https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/657/

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/706/

**Comment by smarterclayton** [comment]
This is now the #1 break in the queue and testing on master

**Comment by mfojtik** [comment]
@smarterclayton do we have some fresh logs? seems like the log snippet from the description does not match the reality anymore.

**Comment by mfojtik** [comment]
@smarterclayton ok, this code does `oc logs -f pods/deployer` to collect the logs. It stores the output of that command into `out` variable when the `-f` drops (which happen when the deployer pod is gone/complete). It seems like:

1) We miss buff.sync() somewhere to flush all logs into `out`
2) Something changed in `oc logs -f` and we won't get the complete logs from the pod or we miss the last line of the log output (did something changed in upstream re: logging?)

**Comment by mfojtik** [comment]
I ran this test for some time in a loop and no luck reproducing this :/

**Comment by mfojtik** [comment]
@kargakis @smarterclayton ok, the only reasonable way to fix it and unblock the queue is to use the deployment config condition to check the success (i can check the `NewRcAvailableReason`).

I will add FIXME there for now and will continue investigating.

**Comment by mfojtik** [comment]
This is journald rate-limiter issue, as a band-aid we are going to disable the `--> Success` check in logs (we already check the conditions/reason to make sure the rollout completed successfully).

Moving this to P2 just to track this once the rate-limiter is fixed.

**Comment by smarterclayton** [comment]
Still happening

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/5157/

**Comment by bparees** [comment]
> Moving this to P2 just to track this once the rate-limiter is fixed.

@mfojtik was the rate-limiter ever fixed?

**Comment by mfojtik** [comment]
@bparees it was tweaked for some tests but not for deployment tests... so no, it was not fixed (the original issues is still opened).

**Comment by jim-minter** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17248/test_pull_request_origin_extended_conformance_install_update/9178/

**Comment by tnozicka** [comment]
@mfojtik close in favor of https://github.com/openshift/origin/issues/17747 ?
