### ISSUE TITLE
3.6 Upgrade Failure:  50 k8s e2e tests fail

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#13997]
When installing Origin 1.5 and upgrading to Origin 3.6, we see 50 k8s tests fail on the e2e suite:

  - Extended.[k8s.io] ConfigMap optional updates should be reflected in volume [Conformance] [Volume]	7 min 0 sec	17
  - Extended.[k8s.io] ConfigMap should be consumable via the environment [Conformance]	9.5 sec	17
  - Extended.[k8s.io] Daemon set [Serial] Should adopt or recreate existing pods when creating a RollingUpdate DaemonSet with matching or mismatching templateGeneration	20 sec	17
  - Extended.[k8s.io] Daemon set [Serial] Should not update pod when spec was updated and update strategy is OnDelete	20 sec	17
  - Extended.[k8s.io] Daemon set [Serial] Should update pod when spec was updated and update strategy is RollingUpdate	20 sec	17
  - Extended.[k8s.io] Daemon set [Serial] should run and stop complex daemon with node affinity	5 min 18 sec	17
  - Extended.[k8s.io] InitContainer should invoke init containers on a RestartAlways pod	35 sec	17
  - Extended.[k8s.io] InitContainer should invoke init containers on a RestartNever pod	8.2 sec	17
  - Extended.[k8s.io] InitContainer should not start app containers and fail the pod if init containers fail on a RestartNever pod	10 sec	17
  - Extended.[k8s.io] InitContainer should not start app containers if init containers fail on a RestartAlways pod	25 sec	17
  - Extended.[k8s.io] Kubectl client [k8s.io] Kubectl taint [Serial] should remove all the taints with the same key off a node	10 sec	17
  - Extended.[k8s.io] Kubectl client [k8s.io] Kubectl taint [Serial] should update the taint on a node	10 sec	17
  - Extended.[k8s.io] Projected optional updates should be reflected in volume [Conformance] [Volume]	4 min 16 sec	17
  - Extended.[k8s.io] Projected should be consumable from pods in volume [Conformance] [Volume]	9.5 sec	17
  - Extended.[k8s.io] Projected should be consumable from pods in volume as non-root [Conformance] [Volume]	9.4 sec	17
  - Extended.[k8s.io] Projected should be consumable from pods in volume as non-root with defaultMode and fsGroup set [Conformance] [Volume]	9.5 sec	17
  - Extended.[k8s.io] Projected should be consumable from pods in volume with defaultMode set [Conformance] [Volume]	16 sec	17
  - Extended.[k8s.io] Projected should be consumable from pods in volume with mappings [Conformance] [Volume]	9.4 sec	17
  - Extended.[k8s.io] Projected should be consumable from pods in volume with mappings and Item Mode set [Conformance] [Volume]	9.5 sec	17
  - Extended.[k8s.io] Projected should be consumable from pods in volume with mappings and Item mode set[Conformance] [Volume]	9.8 sec	17
  - Extended.[k8s.io] Projected should be consumable from pods in volume with mappings as non-root [Conformance] [Volume]	9.6 sec	17
  - Extended.[k8s.io] Projected should be consumable in multiple volumes in a pod [Conformance] [Volume]	9.6 sec	17
  - Extended.[k8s.io] Projected should be consumable in multiple volumes in the same pod [Conformance] [Volume]	9.7 sec	17
  - Extended.[k8s.io] Projected should project all components that make up the projection API [Conformance] [Volume] [Projection]	9.5 sec	17
  - Extended.[k8s.io] Projected should set DefaultMode on files [Conformance] [Volume]	9.4 sec	17
  - Extended.[k8s.io] Projected should set mode on item file [Conformance] [Volume]	16 sec	17
  - Extended.[k8s.io] Projected should update annotations on modification [Conformance] [Volume]	2 min 14 sec	17
  - Extended.[k8s.io] Projected should update labels on modification [Conformance] [Volume]	2 min 14 sec	17
  - Extended.[k8s.io] Projected updates should be reflected in volume [Conformance] [Volume]	5 min 14 sec	17
  - Extended.[k8s.io] ResourceQuota should create a ResourceQuota and capture the life of a configMap.	7.5 sec	17
  - Extended.[k8s.io] ResourceQuota should create a ResourceQuota and capture the life of a persistent volume claim with a storage class. [Volume]	40 sec	17
  - Extended.[k8s.io] ResourceQuota should create a ResourceQuota and capture the life of a persistent volume claim. [Volume]	7.5 sec	17
  - Extended.[k8s.io] ResourceQuota should create a ResourceQuota and capture the life of a pod.	7.5 sec	17
  - Extended.[k8s.io] ResourceQuota should create a ResourceQuota and capture the life of a replication controller.	7.3 sec	17
  - Extended.[k8s.io] ResourceQuota should create a ResourceQuota and capture the life of a secret.	18 sec	17
  - Extended.[k8s.io] ResourceQuota should create a ResourceQuota and capture the life of a service.	7.7 sec	17
  - Extended.[k8s.io] SchedulerPredicates [Serial] validates that Inter-pod-Affinity is respected if not matching	2 min 25 sec	17
  - Extended.[k8s.io] SchedulerPredicates [Serial] validates that NodeAffinity is respected if not matching	2 min 25 sec	17
  - Extended.[k8s.io] SchedulerPredicates [Serial] validates that a pod with an invalid NodeAffinity is rejected	25 sec	17
  - Extended.[k8s.io] SchedulerPredicates [Serial] validates that a pod with an invalid podAffinity is rejected because of the LabelSelectorRequirement is invalid	25 sec	17
  - Extended.[k8s.io] SchedulerPredicates [Serial] validates that taints-tolerations is respected if matching	9.4 sec	17
  - Extended.[k8s.io] SchedulerPredicates [Serial] validates that taints-tolerations is respected if not matching	9.5 sec	17
  - Extended.[k8s.io] Secrets optional updates should be reflected in volume [Conformance] [Volume]	7 min 5 sec	17
  - Extended.[k8s.io] Secrets should be consumable via the environment [Conformance]	18 sec	17
  - Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Scaling down before scale up is finished should wait until current pod will be running and ready before it will be removed	10 min	17
  - Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy	11 min	17
  - Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Should recreate evicted statefulset	32 sec	17
  - Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should adopt matching orphans and release non-matching pods	31 sec	17
  - Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should allow template updates	40 sec	17
  - Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should not deadlock when a pod's predecessor fails

Seen in `test_branch_origin_extended_conformance_install_update` jobs [279](https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install_update/279/)-[299](https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install_update/299/).

**Comment by stevekuznetsov** [comment]
I've added a `[testupgrade]` trigger to PRs for Origin that will trigger this test against a PR.

**Comment by stevekuznetsov** [comment]
Moving this to `p0` as it means that our install+upgrade leads us to a pretty broken state as far as k8s is concerned.

**Comment by ncdc** [comment]
I guess this is my new task of the day :-/

**Comment by ncdc** [comment]
This sounds like it's because 1.5 is using the etcd2 mode and 3.6 defaults to etcd3. Maybe?

**Comment by ncdc** [comment]
Hmm, maybe not. I'm looking at one test where I thought that was the case, but now I'm not so sure.

**Comment by ncdc** [comment]
AHA! This is actually upgrading from 1.5.0-1 to v3.6.0-alpha.0 (which is PRE 1.6 rebase), and then running the post-rebase extended tests:

```
I0430 02:10:48.209934  117898 test.go:92] Extended test version v3.6.0-alpha.1+1c79486-337
```

Should kube 1.6 e2es pass against a kube 1.5 base?

**Comment by ncdc** [comment]
I would think we'd want the kube 1.5 e2es to be able to pass against 1.5 and 3.6, but there's no guarantee that 3.6 e2es would be able to pass against 1.5 (they may expect and require 3.6 features to validate a 3.6 test).

I'm going to close this. Reopen if you disagree.
