### ISSUE TITLE
3.6 Upgrade Failure: etcdctl.sh.j2 not in path, upgrade fails

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#14000]
We are seeing the [`Drop etcdctl profiles.[localhost] Configure etcd profile.d alises`](https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install_update/lastCompletedBuild/consoleFull#-14246886155849c75fe4b0052e114d805c) fail in the upgrade:

```
TASK [Configure etcd profile.d alises] *****************************************
task path: /usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/upgrades/etcd/roles/etcd/tasks/etcdctl.yml:6
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "generated_timestamp": "2017-05-02 10:51:23.534971", 
    "msg": "Unable to find 'etcdctl.sh.j2' in expected paths."
}
```

This error happens on every run of the `test_branch_origin_extended_conformance_install_update` job since [300](https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install_update/300)

**Comment by stevekuznetsov** [comment]
I've added a `[testupgrade]` trigger to PRs for Origin that will trigger this test against a PR.

**Comment by andrewlove** [comment]
I'm getting this too on upgrade attempt from Origin 1.4.1 to 1.5.0.

**Comment by ingvagabund** [comment]
@stevekuznetsov upgrade from openshift-ansible rpm? Or from the openshift/openshift-ansible master HEAD?

**Comment by stevekuznetsov** [comment]
@ingvagabund RPMs built from OpenShift Ansible 0a195fb83ecd592ca0b2c897dc240298cd64a75e

**Comment by stevekuznetsov** [comment]
But most likely also any recent HEAD from the last two weeks, 00d007565aff754cb282631f89de93c1c9cc0a46 could very well be the culprit/

**Comment by stevekuznetsov** [comment]
@ingvagabund this is happening 100% of the time on upgrade -- are you having trouble reproducing? This bug should be high priority. /cc @sdodson

**Comment by stevekuznetsov** [comment]
Nevermind, saw the updates in https://github.com/openshift/openshift-ansible/issues/4077

**Comment by andrewlove** [comment]
Confirmed successful upgrade from Origin 1.4.1 to 1.5.0.
Many thanks
