### ISSUE TITLE
Service Broker bind implementation

### ISSUE THREAD

**Issue by maleck13** [openshift/origin#14003]
I realise the service broker is currently just a tech preview, but I have some questions about the bind implementation.
Currently, the bind implementation seems very simple. Correct me if I am wrong, but from reading the code I believe it simply looks for a basic auth secret plus the cluster ips of the services and returns those.
Are there plans to allow for creating many bindings to one service or to allow creating a binding to something like a mongodb or mysql db in which a new set of credentials plus the database is created? Or would you expect other service brokers to provide this functionality?
To support this kind of binding, I imagine, is complex as you have multiple protocols and requirements.
I have been looking at building a broker that works with OpenShift (hence my interest) . One way I considered solving the problem of multiple bindings and protocols was to use a job with an image that would contain the required logic to create the binding. My service broker would then launch this job passing in the "admin" credentials that were created / specified when the service was first provisioned (this could be a secret also) and then check the status of the job to see had it succeeded. The job could be responsible for not only creating the binding but also creating a secret in the specified namespace. Likely there is a much better way to achieve this but wanted share my thoughts. Interested to hear any thoughts or plans in this area.

**Comment by pweil-** [comment]
@maleck13 this is better submitted to the service-catalog incubator repository https://github.com/kubernetes-incubator/service-catalog

**Comment by maleck13** [comment]
@pweil- Thanks for getting back to me. A little confused though, the code I am referring to is in the OpenShift repo not the service catalog. But I will open an issue there as you suggest.
