### ISSUE TITLE
Openshift origin build issues

### ISSUE THREAD

**Issue by zafinxueqian** [openshift/origin#14004]
[provide a description of the issue]
Cloning "https://xxx@bitbucket.org/zafinworks/xxxx.git" ...
WARNING: timed out waiting for git server, will wait 1m4s
WARNING: timed out waiting for git server, will wait 4m16s
WARNING: timed out waiting for git server, will wait 17m4s
##### Version
openshift v1.5.0+031cbe4

##### Steps To Reproduce
[On a cluster using the network policy SDN plugin]
1. oc new-app wildfly:test~https://xxx@bitbucket.org/zafinworks/xxxx.git --name='zplatform'

##### Current Result
Cloning "https://xxx@bitbucket.org/zafinworks/xxxx.git" ...
WARNING: timed out waiting for git server, will wait 1m4s
WARNING: timed out waiting for git server, will wait 4m16s
WARNING: timed out waiting for git server, will wait 17m4s
##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by stobias123** [comment]
@bparees I'm seeing this issue as well - fresh install of OSE - v3.5.5.8.

When I rsh into the router pod and export my http proxy, I'm able to curl https://github.com without issue.

I set the `openshift_http(s)_proxy` , `openshift_builddefaults_http(s)_proxy` , and 'openshift_builddefaults_git_http(s)_proxy` variables in ansible at install time.

Build logs (level 5) show that the proxy should be set... 

It could well be a networking issue, but where do I start to troubleshoot? I was able to curl out from a pod in the network, curl from the nodes work as well.. not sure where to check next. I even ran https://raw.githubusercontent.com/openshift/openshift-sdn/master/hack/debug.sh but I don't know where to start with those logs.

**Comment by bparees** [comment]
@stobias123 can you provide those level 5 build logs (via pastebin please)?

**Comment by stobias123** [comment]
Sure. Here you go - https://pastebin.com/2jGYySV1

**Comment by bparees** [comment]
@stobias123 thanks.  I agree it looks like all the proxy values are set, i'm not sure why your router might be able to reach github (via your proxy) but your build cannot, however the router does run in a different project which might be part of why.

Can you deploy the jenkins image (template for deployment is here: https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/jenkins-ephemeral-template.json ) in your normal user project (where you are doing the builds) and then oc rsh into that and attempt the git from there?  you should be able to run this line on you are rsh'd into the jenkins pod:

```
SOURCE_REPOSITORY=https://github.com/openshift/ruby-ex.git SOURCE_URI=https://github.com/openshift/ruby-ex.git SOURCE_REF=master ORIGIN_VERSION=v3.5.5.8 BUILD_LOGLEVEL=4 ALLOWED_UIDS=1- DROP_CAPS=KILL,MKNOD,SETGID,SETUID,SYS_CHROOT PUSH_DOCKERCFG_PATH=/var/run/secrets/openshift.io/push KUBERNETES_PORT_53_UDP=udp://172.30.0.1:53 KUBERNETES_PORT_53_UDP_PROTO=udp KUBERNETES_PORT_53_UDP_PORT=53 KUBERNETES_PORT_53_TCP=tcp://172.30.0.1:53 KUBERNETES_PORT_53_TCP_PORT=53 RUBY_STILL_KING_PORT=tcp://172.30.23.51:8080 KUBERNETES_SERVICE_PORT=443 KUBERNETES_PORT_443_TCP_PORT=443 KUBERNETES_SERVICE_HOST=172.30.0.1 KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443 KUBERNETES_PORT_443_TCP_PROTO=tcp RUBY_STILL_KING_SERVICE_PORT=8080 RUBY_STILL_KING_SERVICE_PORT_8080_TCP=8080 RUBY_STILL_KING_PORT_8080_TCP_PROTO=tcp RUBY_STILL_KING_PORT_8080_TCP_PORT=8080 KUBERNETES_SERVICE_PORT_DNS_TCP=53 KUBERNETES_PORT=tcp://172.30.0.1:443 KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1 KUBERNETES_PORT_53_UDP_ADDR=172.30.0.1 KUBERNETES_PORT_53_TCP_PROTO=tcp KUBERNETES_PORT_53_TCP_ADDR=172.30.0.1 RUBY_STILL_KING_SERVICE_HOST=172.30.23.51 RUBY_STILL_KING_PORT_8080_TCP=tcp://172.30.23.51:8080 KUBERNETES_SERVICE_PORT_HTTPS=443 KUBERNETES_SERVICE_PORT_DNS=53 RUBY_STILL_KING_PORT_8080_TCP_ADDR=172.30.23.51 container=oci HOME=/root OPENSHIFT_CONTAINERIZED=true KUBECONFIG=/var/lib/origin/openshift.local.config/master/admin.kubeconfig git ls-remote --heads https://github.com/openshift/ruby-ex.git
```

**Comment by stobias123** [comment]
no dice. it hangs.

**Comment by bparees** [comment]
well that's good, sort of.  it definitely points to a network issue (not surprisingly).  I'm going to have to hand you off to our networking lead, @knobunc to troubleshoot further.

**Comment by sbadakhc** [comment]
Hi,

I'm also having the same problem but the jenkins template and associated command execution worked for me:
```
da9292ad13bbb2c1eb2a264d7b531bf6ead0bf38        refs/heads/lukas-vlcek-fix-readme
855ab2de53ff897a19e1055f7554c64d19e02c50        refs/heads/master
```
Is there anything else can try?

**Comment by sbadakhc** [comment]
Actually this seems to be working now!
Apologies.

**Comment by knobunc** [comment]
@danwinship is there something special you need to do to make build containers work correctly when using the network policy plugin?

**Comment by coreydaley** [comment]
@zafinxueqian are you still experiencing this issue?

**Comment by xqianwang** [comment]
@coreydaley  Not any more.  Thank you!

**Comment by Tsoa27** [comment]
hey guys, i'm newby in openshift and i've got the same issue.  It try to deploy an application by using git but it always fails. My DNS work proprelly  and i am using a proxy behind a firewall.

**Comment by bparees** [comment]
@Tsoa27 please open a new issue, provide your buildconfig yaml definition and level 5 build logs (oc start-build yourbuild --build-loglevel=5)
