### ISSUE TITLE
oc secret and password containing special character

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#14012]
How to use `oc secret new-basicauth … --password=''` when the password contains special character like bang `!` and simple quote `'`. I'd like to use the CLI to have the command in my history. 

As a workaround, I use `oc secret new-basicauth … --prompt=true`

##### Version
~/P/afds-jenkins-s2i git:master ❯❯❯ oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

**Comment by juanvallejo** [comment]
@YannMoisan Using a 3.7 client, I'm able to specify a secret containing characters such as `'` and `!`.
Please re-open if you are still seeing this issue with a newer client.
