### ISSUE TITLE
Remove extensions/v1beta1.HorizontalPodAutoscaler for 3.7

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#14028]
Kube removed `extensions/v1beta1.HorizontalPodAutoscaler` in 1.6. Because we did not inform users that was happening, we are carrying this forward into 3.6. We cannot continue to support `extensions/v1beta1.HorizontalPodAutoscaler` past 3.6, and users must migrate to `autoscaling/v1` prior to upgrading to 3.7.

Tasks:

- [ ] Remove our carry of `extensions/v1beta1.HorizontalPodAutoscaler` from origin ASAP after master is for 3.7
- [x] Switch web console to use `autoscaling/v1` ASAP
- [ ] Document very clearly that HPA is being removed from extensions/v1beta1 in 3.7
- [ ] Document that users must run `oadm migrate storage ...` once their cluster is fully upgraded to 3.6 so any existing HPAs in etcd are re-encoded as `autoscaling/v1`
- [ ] Make sure openshift-ansible upgrade playbook runs `oadm migrate storage ...` before installing any 3.7 RPMs

cc @smarterclayton @sdodson @brenton @DirectXMan12 @ingvagabund @derekwaynecarr @deads2k @sttts @liggitt @mfojtik @jwforres

**Comment by jwforres** [comment]
thanks to @liggitt the console is switched over to autoscaling/v1 for 3.6, I'm not aware of any remaining work there and QE will be regression testing that very soon https://trello.com/c/kj6KUWRF

**Comment by sdodson** [comment]
Upgrade playbooks run `oc adm migrate storage --include=jobs --confirm` will that include what you need?

**Comment by deads2k** [comment]
> Document that users must run oadm migrate storage ... once their cluster is fully upgraded to 3.6 so any existing HPAs in etcd are re-encoded as autoscaling/v1

I think this actually going to be a general problem: at some point during ReleaseX you need to run `oadm migrate Y` before upgrading to ReleaseX+1.  Is there a way for us in origin to indicate that a given `oadm migrate` command must be run before an upgrade to the next level?

**Comment by enj** [comment]
@deads2k see #13565
