### ISSUE TITLE
getting error: No package matching 'PyYAML' is available

### ISSUE THREAD

**Issue by naveenkumartangallapally** [openshift/origin#14023]
I am trying to setup openshift on google cloud engine.

when i am trying to run play book, i am getting below error:

```
failed: [node2.example.me] (item=[u'iproute', u'python-dbus', u'PyYAML', u'yum-utils']) => {
    "failed": true, 
    "item": [
        "iproute", 
        "python-dbus", 
        "PyYAML", 
        "yum-utils"
    ]
}

MSG:

No package matching 'PyYAML' is available
```
can any one please help on these?

**Comment by php-coder** [comment]
This is installer issue and it's better to report it to https://github.com/openshift/openshift-ansible

Also you didn't mention which target OSes you're using. If you're installing on Fedora then it looks like https://github.com/openshift/openshift-ansible/issues/2491

**Comment by php-coder** [comment]
CC @sdodson

**Comment by sdodson** [comment]
@naveenkumartangallapally yes, what OS are the target hosts running?

**Comment by naveenkumartangallapally** [comment]
i am targeting to ubuntu hosts which are delpoyed in google cloud engine
