### ISSUE TITLE
Decide when to switch to etcd3, protobuf

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#14029]
We need to:

- decide when to move to etcd3 and protobuf by default for all new clusters
- ensure that existing clusters currently using etcd2/json remain on etcd2/json
  - this will probably require new fields in master-config.yaml to make this configurable
  - then, an openshift-ansible upgrade playbook change to add the new field(s)
- decide when we will force existing clusters to move to etcd3/protobuf

cc @smarterclayton @eparis @sdodson @brenton @deads2k @sttts @liggitt @mfojtik @soltysh

**Comment by eparis** [comment]
@ingvagabund he was working on the code to make this possible, last I heard.

**Comment by sdodson** [comment]
If we maintain the current state where only all-in-one clusters switch by default I think that's best. Then the installer can manage migration and defaulting to etcd3/protobuf on upgrade or greenfield.

**Comment by ncdc** [comment]
@sdodson agreed, so if we do nothing else, 3.5->3.6 upgrades and new 3.6 installations will be etcd2/json.

I created this issue so we can push this to completion.

**Comment by enj** [comment]
So why don't we want new clusters to be etcd3/protobuf?

**Comment by ncdc** [comment]
Actually, my agreement was too broad 😄. I would love to see new 3.6 clusters be etcd3/protobuf.

**Comment by smarterclayton** [comment]
New clusters created by Ansible can be without adding new config
flags.  Anyone not installing with Ansible can rtm?

**Comment by mfojtik** [comment]
@smarterclayton @ncdc is there something that needs to be done for etcd3? is this a blocker for 3.6?

**Comment by smarterclayton** [comment]
@sdodson owned the ansible stuff, we can probably start recommending new
clusters go to proto in 3.6 and look at 3.6.1+ for people doing upgrades.
In our in person discussion we agreed that 3.6 upgrade and proto upgrade
should be separate steps for users anyway.

**Comment by liggitt** [comment]
need to resolve https://github.com/openshift/origin/issues/13419
