### ISSUE TITLE
Hairpin does not work with the all-in-one

### ISSUE THREAD

**Issue by enj** [openshift/origin#14031]
1. Start an all-in-one server
2. Create a pod that runs a server, and a service selecting the pod
3. From within the pod, attempt to contact the service

Hairpin is not set up by the all-in-one, so the pod is unable to reach itself. Needs to be fixed and a test added to ensure we don't regress.

Currently a service cannot loopback to itself using its service DNS name with the all-in-one configuration.

cc @openshift/networking @liggitt

**Comment by enj** [comment]
xref: https://github.com/openshift/origin/issues/13927#issuecomment-298112303

**Comment by liggitt** [comment]
or even a merge-blocking test... this seems fundamental enough that we'd want high visibility if it didn't work

**Comment by liggitt** [comment]
@danwinship @dcbw what's the status on getting hairpin working again with the all-in-one?

**Comment by enj** [comment]
So what is the plan for this in 3.6?

**Comment by david-martin** [comment]
@enj I have seen a similar issue with `oc cluster up` on 3.6.0 alpha2 (on Fedora 25)
The pod can curl itself OK if it uses the PodIP or localhost. 
```
sh-4.2$ curl -I 172.17.0.4:8080                                                                         
HTTP/1.1 200 OK       

sh-4.2$ curl -I localhost:8080                                                                          
HTTP/1.1 200 OK                                                                                                                                                                           
```

But curling the service name doesn't work. (Service name is `testa`)
The request seems to timeout.
```
sh-4.2$ curl -I testa:8080                                                                              
curl: (7) Failed connect to testa:8080; Connection timed out                                            
```

Other pods can be accessed OK by their service name. Its just when a pod is talking to itself that there's a problem.
```
sh-4.2$ curl -I testb:8080                                                                              
HTTP/1.1 200 OK                                                                                         
```

**Comment by sttts** [comment]
How critical is this? We marked it as blocker in https://github.com/openshift/origin/issues/13732#issuecomment-314686570. /cc @mfojtik

**Comment by garagatyi** [comment]
Hi. We have faced the same behavior in Che on a single server OpenShift. Is there anyone working on this issue? If no is there anyone who knows where to dig to fix this issue?

**Comment by riuvshin** [comment]
same issue with `3.7.0`.
any news about current status of this?

**Comment by smarterclayton** [comment]
@openshift/sig-networking please triage thid

**Comment by smarterclayton** [comment]
This

**Comment by knobunc** [comment]
@smarterclayton I think the right answer is that the all-in-one needs to use a networking plugin by default.  Perhaps the kubenet one (to be as light as possible).  Otherwise there's no good way for us to set the hairpin.

@dcbw do you have any thoughts?

**Comment by eivantsov** [comment]
Is there any way to pass `--network-plugin=kubenet` to oc or maybe manually do that? 

I tried tried adding plugin in node-config.yaml in networkConfig section but it did not help.

```
networkConfig:
  mtu: 1450
  networkPluginName: "kubenet"

```
Restarting produces the following error:
```
E0219 12:04:17.092274    1688 kubelet.go:2072] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
```

**Comment by eivantsov** [comment]
Is this going to be solved somehow or are there any workarounds?

**Comment by riuvshin** [comment]
/remove-lifecycle stale

issue is still actual.

**Comment by garagatyi** [comment]
@eivantsov found a workaround - reconfigure docker daemon not to use userland proxy. Here is the [link](https://github.com/eclipse/che/issues/8134#issuecomment-408663305) to the explanation.
So, we might consider closing this issue since it seems it is not prioritized enough to find a better solution.

**Comment by l0rd** [comment]
On kubernetes 1.11 I cannot reproduce this issue anymore
