### ISSUE TITLE
Extended.[builds][Slow] openshift pipeline build Pipeline with env vars should build and complete successfully

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#14035]
Unable to reproduce locally
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended/293/testReport/junit/(root)/Extended/_builds__Slow__openshift_pipeline_build_Pipeline_with_env_vars_should_build_and_complete_successfully/

**Comment by gabemontero** [comment]
Took a quick peek.  Looks eerily similar to the update conflict on the build config that @jim-minter was working last week:

```
May  3 13:24:08.431: INFO: Running 'oc start-build --config=/tmp/extended-test-jenkins-pipeline-rr2ff-zx5jm-user.kubeconfig --namespace=extended-test-jenkins-pipeline-rr2ff-zx5jm -e FOO2=BAR2 sample-pipeline-withenvs -o=name'
May  3 13:24:08.773: INFO: Error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc [oc start-build --config=/tmp/extended-test-jenkins-pipeline-rr2ff-zx5jm-user.kubeconfig --namespace=extended-test-jenkins-pipeline-rr2ff-zx5jm -e FOO2=BAR2 sample-pipeline-withenvs -o=name] []    Error from server (Conflict): Operation cannot be fulfilled on buildconfigs.build.openshift.io "sample-pipeline-withenvs": the object has been modified; please apply your changes to the latest version and try again
 [] <nil> 0xc421e367e0 exit status 1 <nil> <nil> true [0xc4207ac060 0xc4207ac088 0xc4207ac098] [0xc4207ac060 0xc4207ac088 0xc4207ac098] [0xc4207ac068 0xc4207ac080 0xc4207ac090] [0xdc53f0 0xdc54f0 0xdc54f0] 0xc421f149c0 <nil>}:
StdOut>

StdErr>
Error from server (Conflict): Operation cannot be fulfilled on buildconfigs.build.openshift.io "sample-pipeline-withenvs": the object has been modified; please apply your changes to the latest version and try again



start-build output with args [-e FOO2=BAR2 sample-pipeline-withenvs -o=name]:
Error>exit status 1
StdOut>

StdErr>
Error from server (Conflict): Operation cannot be fulfilled on buildconfigs.build.openshift.io "sample-pipeline-withenvs": the object has been modified; please apply your changes to the latest version and try again

```

Don't know if @jim-minter 's fix merged ... if no, we close this as a dup of what he is working; if yes, we need to clear up why the retry he introduced was not sufficient, and perhaps add retry in our jobs.

And there is the niggling concern of @bparees as to *why* we are getting the conflict.

**Comment by gabemontero** [comment]
Going to give to @jim-minter , at least initially, given his recent history here.  Based on his availability wrt Summit and how frequently we see this moving forward, we'll adjust if need be.

**Comment by bparees** [comment]
> Don't know if @jim-minter 's fix merged ... 

it has not, it's here: https://github.com/openshift/origin/pull/13910

**Comment by gabemontero** [comment]
ah .. thx @bparees 

refreshing my memory wrt the changes, I believe they should address what @coreydaley saw.

and that PR notes a couple of existing flakes which look similar to this one

going to go ahead and close this one then ... of course if folks think there is a reason to reopen, certainly do so and elaborate
