### ISSUE TITLE
provision an AWS EC2 instance.[localhost] aws-up : wait for SSH to be available

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#14041]
See: https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/540/testReport/junit/(root)/provision%20an%20AWS%20EC2%20instance/_localhost__aws_up___wait_for_SSH_to_be_available/

```
TASK [aws-up : wait for SSH to be available] ***********************************
task path: /var/lib/jenkins/origin-ci-tool/e33d742ece97905d80ae8022c42b9eda26908af5/lib/python2.7/site-packages/oct/ansible/oct/playbooks/provision/roles/aws-up/tasks/main.yml:110
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "elapsed": 601, 
    "failed": true, 
    "generated_timestamp": "2017-05-03 06:40:34.126255", 
    "msg": "Timeout when waiting for 172.18.13.150:22"
}
```

Marking this as P2 initially as this seems like an AWS infra flake.

**Comment by kargakis** [comment]
@stevekuznetsov @jhadvig @smarterclayton should the GCE job fail because of AWS? It seems that `test_branch_origin_extended_conformance_gce.yml` is based on `common/test_cases/origin.yml` which used AWS as a provider.

**Comment by jhadvig** [comment]
> should the GCE job fail because of AWS? It seems that test_branch_origin_extended_conformance_gce.yml is based on common/test_cases/origin.yml which used AWS as a provider.

So from what I see, the GCE job is launching and AWS machine from which it starts a origin cluster where the tests are running. So that shouldnt be the cause ?

**Comment by stevekuznetsov** [comment]
Yep -- we use a containerized GCE provisioner and installer, which cannot run directly on the Jenkins master as the master should not have heavy load and does not run a Docker daemon. EC2 VM is used as an intermediate.

**Comment by ncdc** [comment]
We know AWS VMs sometimes fail to start. Not much we can do about it.
