### ISSUE TITLE
--api-version flag being used in test-cmd tests

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#14053]
Flag is deprecated and will be removed, we should be proactive if possible: 

 - [ ] [test/cmd/builds.sh:100](https://github.com/openshift/origin/tree/master/test/cmd/builds.sh#L100)
 - [ ] [test/cmd/builds.sh:101](https://github.com/openshift/origin/tree/master/test/cmd/builds.sh#L101)
 - [ ] [test/cmd/builds.sh:103](https://github.com/openshift/origin/tree/master/test/cmd/builds.sh#L103)
 - [ ] [test/cmd/login.sh:62](https://github.com/openshift/origin/tree/master/test/cmd/login.sh#L62)
 - [ ] [test/cmd/login.sh:91](https://github.com/openshift/origin/tree/master/test/cmd/login.sh#L91)

Are we fine to just remove these? /cc @liggitt @deads2k

**Comment by stevekuznetsov** [comment]
OK, so this issue is really to ensure `oc start-build` and `oc login` are negotiating properly -- @mfojtik  @bparees can you please delegate these two tasks to someone?

**Comment by bparees** [comment]
@coreydaley can you take a look at the start-build piece? 

Does this affect new-app/new-build also?

**Comment by coreydaley** [comment]
@bparees I was able to remove the --api-version from test/cmd/builds.sh script lines and the test ran without issue.

**Comment by coreydaley** [comment]
@bparees looks like login is still relying on the --api-version here: https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/login/login.go#L141

I was not able to find a similar piece of code in the start-build command, it also did not seem to be present in the new-app or new-build commands either.

**Comment by wtrocki** [comment]
Seems that all occurrences were removed. Login go is now in: https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/login/login.go

Documentation still mentions that parameter here:
https://github.com/openshift/origin/blob/c0ea12300305269c3d4cfdc95ffd1ef48102c70e/docs/cli.md

**Comment by bparees** [comment]
@stevekuznetsov looks like we think this is resolved, can you confirm?

**Comment by stevekuznetsov** [comment]
```
$ grep -nr '\-\-api-version' test/cmd/ | wc -l
0
```

/close
