### ISSUE TITLE
Faild to mount volumes for pod

### ISSUE THREAD

**Issue by lvshangze** [openshift/origin#14067]
##### Version
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
etcd 3.1.0

##### Steps To Reproduce
1.
 openshift start --master-config='./openshift.local.config/master/master-config.yaml' --node-config='./openshift.local.config/node-ecs-opsft.novalocal/node-config.yaml' 2>&1 | tee openshift-start.log

2. 
 oc login -u system:admin
 oc project default
 oc create serviceaccount registry -n default
 oadm policy add-scc-to-user privileged system:serviceaccount:default:registry
 oadm registry --config=./openshift.local.config/master/admin.kubeconfig --service-account=registry
 oc describe service docker-registry --config=openshift.local.config/master/admin.kubeconfig
3.
 oc login
 oc project default
 oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git
4.
 oc create -f cinder-pv.yaml
 oc create -f pv-claim.yaml
5.
Visit Openshift Web Console in browser in another windows vm and try to add storage to the template of deployment config ruby-ex.

##### Current Result
Failded mount : Unable to mount volumes for pod "ruby-ex-18-lfh2x_default(0090f9af-3169-11e7-b774-fa163ef1258d)": timeout expired waiting for volumes to attach/mount for pod "default"/"ruby-ex-18-lfh2x". list of unattached/unmounted volumes=[volume-i7n1g]

Failed sync : Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"ruby-ex-18-lfh2x". list of unattached/unmounted volumes=[volume-i7n1g]

##### Expected Result
Successfully mounted volumes for pod,the template of deployment config ruby-ex can be active.

##### Additional Information
I'm doing this on OpenStack Xen virtualization platform,there's no symbolic link like "virtio-vulumeID" under /dev/disk/by-id.Actually,I found the volume was already attached to my vm on my OpenStack console,and tried to add virtio symbolic links manually,but the issue is still going.

This is an issue since I tested v1.2.2 on OpenStack  Xen virtualization platform,if OpenShift itself won't be compatible with Xen,then how can I do this resolving this issue?

**Comment by zhoutiekui** [comment]
I had encountered the same issue. anybody who knows the reason ? thanks.

**Comment by lvshangze** [comment]
@childsb
