### ISSUE TITLE
[cluster up] Implement a hostPath based persistent volume provisioner

### ISSUE THREAD

**Issue by hferentschik** [openshift/origin#14062]
Instead of having to pre-create hostPath persistent volumes, it would be nice to have them dynamically created. This would also solve timing issues and the need to create persistent volumes in the background (see #14060).

As reference have a look at this article https://dzone.com/articles/dynamically-provisioning-hostpath-based-volumes-on

See also https://github.com/minishift/minishift/issues/856

**Comment by bparees** [comment]
@csrwng please turn this into a trello card and close it.

**Comment by csrwng** [comment]
https://trello.com/c/WElKnCid/1249-cluster-up-dynamic-pv-provisioner

**Comment by hferentschik** [comment]
@csrwng, just so that I understand, this is now a Trello card and will be tracked and resolved there? How will I get notified when this feature lands?

**Comment by csrwng** [comment]
@hferentschik you can subscribe to the trello card

**Comment by hferentschik** [comment]
Which requires me to sign up for Trello right? That seems odd to me and not really user/contributor friendly. Would it not make more sense to not close until the pull request for this is merged? After all, there will be a pull request for this in this repo at some stage, right?

**Comment by bparees** [comment]
> Which requires me to sign up for Trello right? That seems odd to me and not really user/contributor friendly.

vs haivng to sign up for github?  The boards are public, you can view stuff w/o creating an account, but yes if you want to track/notification you'll have to sign up for trello.

We don't want the overhead of tracking/managing/monitoring/discussing feature requests in multiple places.  Trello is our process for managing our RFE backlog.

**Comment by hferentschik** [comment]
> vs haivng to sign up for github?

Except i already had to sign up for GitHub in order to create this issue. Also contributors will in most cases have GitHub accounts. The same cannot be said for Trello.

I understand that you use Trello for your backlog, but this is not really user friendly for external issue reporters.
