### ISSUE TITLE
[cluster up] Have option to skip creation of persistent volumes 

### ISSUE THREAD

**Issue by hferentschik** [openshift/origin#14061]
In some cases the user might want to create its own persistent volumes, using a different config or maybe even a custom provisioner. In these cases it should be able to skip the creation of the persistent volumes.

An example of where it would have been useful to be able to skip persistent volume creation can be seen in Minishift - https://github.com/minishift/minishift/issues/856

Maybe instead of a pure skip, it could be a flag for specifying the number of persistent volumes to created, which can for example be set to 0.

See also #14060.

**Comment by bparees** [comment]
@csrwng trello and close.  i like the "number of volumes, possibly zero" suggestion.

**Comment by csrwng** [comment]
https://trello.com/c/HbpYqEkm/1250-cluster-up-option-to-set-number-of-pvs-to-create
