### ISSUE TITLE
[cluster up] Persistent volume creation should not occur in the background

### ISSUE THREAD

**Issue by hferentschik** [openshift/origin#14060]
It is really unexpected imo that persistent volume creation occurs in the background. It makes it hard to know when OpenShift is fully provisioned. 

If the reasons for the background creation is the time it takes to provision the persistent volumes, then I suggest to just provision 10 and skip background creation.

This was an issue for the usage of _cluster up_ as part of Minishift. See also https://github.com/minishift/minishift/issues/856

**Comment by bparees** [comment]
@hferentschik are they really being created so slowly that this is an issue?  the issue you linked to discussed problems w/ permissions, if there is a specific comment in that extremely long thread that talks about issues w/ background creation, please link directly to it.

**Comment by csrwng** [comment]
Persistent volume creation is not the only thing that behaves this way ... the registry, router, metrics, logging, all behave the same way. The alternative is to have the developer wait a very long time until everything has been provisioned.

Closing as won't fix.

**Comment by hferentschik** [comment]
There is a differences though. For registry, router etc, I can easily wait for their completion using _oc_. This is not so easy for the job creating persistent volumes. @csrwng, remember how we tried to do that and ended up with a waiting loop in Minishift. 

Another point is that in the case of registry, router, metrics, we (Minishift) can just continue. For persistent volumes we needed to wait, since we need to make adjustments to the file permissions. 

I am ok with closing this, provided there will be the option to configure the amount of persistent volumes created or completely turn it off.

**Comment by csrwng** [comment]
@hferentschik I'm more in favor of controlling the number of pv's with the option of setting them to 0 (for which we already created a trello card). I don't think that there's a case where we would want to wait for pv's to finish getting created.

**Comment by hferentschik** [comment]
>  I'm more in favor of controlling the number of pv's with the option of setting them to 0 (for which we already created a trello card).

Ok, works for me.

> I don't think that there's a case where we would want to wait for pv's to finish getting created.

Fair enough.

**Comment by jorgemoralespou** [comment]
@csrwng Hey, one question that has come to my mind. If the registry changed to be persistent when you introduced these changes, is the registry using these PVs?

I've been looking at the code (remember I'm no go developer, so don't understand much), but it seems that the registry PV is created by the pvsetup.go, that means by the job. So, that means that:

- this PV will always need to be created
- it would be good to create this PV along or before the registry

I think.

**Comment by csrwng** [comment]
@jorgemoralespou the registry doesn't use a pv... it uses a host directory, which we happen to create in the same directory where we put the other pv's. We would still create it regardless.
