### ISSUE TITLE
EgressNetworkPolicy does not correctly populate flow rules

### ISSUE THREAD

**Issue by gizmonicus** [openshift/origin#14074]
EgressNetworkPolicy object does not get created properly and does not have any effect on containers within the project namespace where it was created.

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://origin.[REDACTED]:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Create a project
2. Add an EgressNetworkPolicy object to block traffic to 10.1.2.3/32

##### Current Result
EgressNetworkPolicy has no effect

##### Expected Result
EgressNetworkPolicy should block traffic to 10.1.2.3/32

##### Additional Information
I've run oc adm diagnostics and the only error I get appears to be related to permissions:
```
ERROR: [DNet2006 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:130]
       Creating network diagnostic pod "network-diag-pod-11zr6" on node "a1aorigin01.[REDACTED]" with command "chroot /host openshift infra network-diagnostic-pod -l 1" failed: pods "network-diag-pod-11zr6" is forbidden: unable to validate against any security context constraint: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.containers[0].securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.containers[0].securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used]
```
My EgressNetworkPolicy object looks like this:
```
---
kind: EgressNetworkPolicy
apiVersion: v1
metadata:
  name: test-policy
spec:
  egress:
  - type: Allow
    to:
      cidrSelector: 10.1.2.3/32
```
I can see the flow rule added in the table, so that part appears to be working as expected. On all of the Openshift nodes, including the master and proxy servers, the following command always returns the same result.
```
ovs-ofctl -O OpenFlow13 dump-flows br0 | grep 10.1.2.3
 cookie=0x0, duration=30.614s, table=9, n_packets=0, n_bytes=0, priority=1,ip,reg0=0x12,nw_dst=10.1.2.3 actions=drop
```
However, the rule that directs traffic to this table does not actually get added on any of the nodes other than the master server. Below is the output of the command run on the master server. On _all other nodes in the cluster_, the `goto_table:9` action is missing.
```
ovs-ofctl -O OpenFlow13 dump-flows br0 | grep goto_table:9
 cookie=0x0, duration=159119.420s, table=5, n_packets=0, n_bytes=0, priority=0,ip actions=goto_table:9
```

This past week, I upgraded to version 1.4.1 from 1.2.0 using the origin-ansible playbook (release-1.4), so I can not say if this has worked in the past because I have only just recently had the ability to create these objects. Here is the current ansible hosts file in case it helps with troubleshooting, with sensitive information redacted:
```
# Create an OSEv3 group that contains the masters and nodes groups
[OSv3:children]
masters
#new_nodes
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSv3:vars]
openshift_master_metrics_public_url=https://metrics.apps.[REDACTED]/hawkular/metrics
openshift_node_kubelet_args={'max-pods': ['50']}
openshift_pkg_version=-1.4.1-1.el7
openshift_release=v1.4
ansible_ssh_user=root
deployment_type=origin
openshift_master_identity_providers=[REDACTED]

# Paths to certificate files for the master web host.
openshift_master_named_certificates=[{"certfile": "/etc/pki/tls/certs/origin.crt", "keyfile": "/etc/pki/tls/certs/origin.key", "names": ["origin.[REDACTED]"]}]
openshift_master_cluster_public_hostname=origin.[REDACTED]
openshift_master_overwrite_named_certificates=true

# Subdomain is the wildcard domain that gets assigned to apps by default.
osm_default_subdomain=apps.[REDACTED]

# See the following article for SDN configuration details
# https://docs.openshift.org/latest/architecture/additional_concepts/sdn.html
osm_cluster_network_cidr=192.168.0.0/16
osm_host_subnet_length=8
os_sdn_network_plugin_name=redhat/openshift-ovs-multitenant
osm_default_node_selector="region=primary"

# Set CORS origin to allow swagger api browsing
osm_custom_cors_origins=['swagger-is-linux.apps.[REDACTED]']

# host group for masters
[masters]
bandera.[REDACTED]

# host group for nodes
[nodes]
isorigin01.[REDACTED] openshift_node_labels="{'region':'primary','zone':'is','vlan':'admin64','san':'true'}"
a1aorigin01.[REDACTED] openshift_node_labels="{'region':'primary','zone':'a1a','vlan':'admin64','san':'true'}"

# The following nodes will not be schedulable; they are listed as nodes only so that they belong to the OVS network
bandera.[REDACTED] openshift_node_labels="{'region':'master','zone':'default','vlan':'admin64'}" openshift_schedulable=false
haproxy01.[REDACTED] openshift_node_labels="{'region':'infra','zone':'is','vlan':'dmz','ipf':'apps'}"
haproxy02.[REDACTED] openshift_node_labels="{'region':'infra','zone':'a1a','vlan':'dmz','ipf':'apps'}"

# host group for etcd
[etcd]
bandera.[REDACTED]
isorigin01.[REDACTED]
a1aorigin01.[REDACTED]
```

Finally, I don't see anything in the journal when the object is created that would indicate a problem. If there are any other logs or configuration files you would like me to collect, I'll be more than happy to provide them.

**Comment by danwinship** [comment]
> This past week, I upgraded to version 1.4.1 from 1.2.0 using the origin-ansible playbook

Probably some corner case having to do with skipping 1.3 in the upgrade process... If you reboot your nodes it will probably start working. (The fact that you don't have the "goto_table:9" rules suggests that you probably have a slightly-broken mix of old and new flows or something like that.)

**Comment by gizmonicus** [comment]
I did not skip 1.3 during the upgrade process, though I did not mention that in the issue above. I will try restarting nodes and report back when I have done this.

**Comment by gizmonicus** [comment]
I've added a new node and it appears that the egressnetworkpolicy does get created correctly on the newly added node. I have not had a chance to try rebooting the other nodes yet, but this lends some credibility to that theory.

**Comment by danwinship** [comment]
Any updates to this?

> My EgressNetworkPolicy object looks like this:
> ...
>       - type: Allow

I'm assuming that's a typo/cut+pasto and your *real* rule has "Deny"?

**Comment by gizmonicus** [comment]
Yes, it's a deny in my real rule. I logged in today since I haven't touched Openshift in a few months and it appears that these rules have been added between my latest update on the 19th and today. I haven't done anything, no reboots, no updates, so I can't say what changed or why it is working when it didn't for a couple of days after I first added it.

I added a new rule today, just to see if it would show up, but it so far has not in the 10 minutes since it was created, even on the "new" node (new being relative here). I would expect an entry to show up in the flow tables within a few seconds, is that correct?

Here's the actual policy document:

```
apiVersion: v1
kind: EgressNetworkPolicy
metadata:
  creationTimestamp: 2017-08-16T17:22:50Z
  name: test-policy2
  namespace: is-linux-test
  resourceVersion: "26776297"
  selfLink: /oapi/v1/namespaces/is-linux-test/egressnetworkpolicies/test-policy2
  uid: 8771f355-82a7-11e7-a784-0050560000c2
spec:
  egress:
  - to:
      cidrSelector: 10.2.1.84/32
    type: Deny
```

**Comment by gizmonicus** [comment]
One other oddity here, I ran my dump-flows command again after adding the new rule and now neither the rule I just added, nor the working one are in the flow tables. It appears to have clobbered all egress policies for this namespace.

**Comment by danwinship** [comment]
Oh, yes, you are only allowed to have a single EgressNetworkPolicy object per Namespace. (Otherwise it wouldn't be clear which order to apply to rules in between the two policies if they conflicted.) So if you create a second one, it logs an error and the blocks all traffic from the namespace until you fix it.

**Comment by gizmonicus** [comment]
Ah, OK, I would think that it just wouldn't let you create another policy. Anyway, deleting the other policy resolved the problem. I think we can close this one since I have no way to reproduce, and it's entirely possible this was caused by having a second egress policy initially. I don't remember exactly what the state was at the time.

**Comment by danwinship** [comment]
Kubernetes doesn't inherently have any concept of "singleton" types, so there's no way to block the creation unfortunately. It's not a great situation.
