### ISSUE TITLE
Allow binding to a locally defined role in my own namespace

### ISSUE THREAD

**Issue by jfchevrette** [openshift/origin#14078]
As a normal user, I could like to be able to define a role in my own namespace and bind it to a serviceaccount also defined in my own namespace.

Right now, this is not possible because my normal user does not have the privileges required to create a rolebinding / policybinding

##### Steps To Reproduce
```
oc login -u normaluser
oc new-project testrolebinding
oc project testrolebinding

cat <<EOF | oc create -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-restricted-sa
  namespace: testrolebinding
EOF

cat <<EOF | oc create -f -
apiVersion: v1
kind: Role
metadata:
  name: pods-view-only
  namespace: testrolebinding
rules:
- apiGroups: null
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
EOF

cat <<EOF | oc create -f -
apiVersion: v1
kind: RoleBinding
metadata:
  name: my-restricted-sa
  namespace: testrolebinding
roleRef:
  name: pods-view-only
  namespace: testrolebinding
subjects:
- kind: ServiceAccount
  name: my-restricted-sa
  namespace: testrolebinding
EOF

Error from server: error when creating "STDIN": policybindings "testrolebinding:default" not found

$ oc create policybinding testrolebinding:default
Error from server: User "myuser" cannot create policybindings in project "testrolebinding"
```
##### Current Result
- Normal user is unable to create a local policybinding under his own namespace.
- Normal user is unable to bind role to a serviceaccount

##### Expected Result
Normal user should be able to bind local role to a local serviceaccount defined under his namespace.

This is useful to set granular permissions to specific service accounts. For instance when running a pod under a specific serviceaccount to allow it to list some specific project resources.

cc @liggitt

**Comment by jfchevrette** [comment]
cc @deads2k

**Comment by deads2k** [comment]
This is likely to come up again as make the transition to RBAC and need a controller that syncs in the opposite direction for a rolling upgrade.

**Comment by pweil-** [comment]
FYI @enj @mfojtik

**Comment by enj** [comment]
@deads2k so if I remember correctly, the reason we do not allow users to bind to custom local roles is that doing so allows escalation.  For example, they could circumvent quote restrictions.

**Comment by deads2k** [comment]
> @deads2k so if I remember correctly, the reason we do not allow users to bind to custom local roles is that doing so allows escalation. For example, they could circumvent quote restrictions.

No, that check is separate.

**Comment by enj** [comment]
@deads2k so which scenario does this prevent?

**Comment by deads2k** [comment]
> @deads2k so which scenario does this prevent?

cluster-admin wants to tighten permissions (for whatever reason) and can do so centrally without inspecting namespaced roles which may now grant more privileges.

It's one that I think we're willing to give up.
