### ISSUE TITLE
Template descriptions replaced by name

### ISSUE THREAD

**Issue by djdevin** [openshift/origin#14079]
I noticed in 1.5, the template descriptions are gone:

![desc](https://cloud.githubusercontent.com/assets/418136/25758661/6b902806-319d-11e7-9ae2-5d7f6b40017e.png)

In 1.4 they used to pull from the description property in the template metadata.

##### Version
OpenShift Master:
v1.5.0+031cbe4
Kubernetes Master:
v1.5.2+43a9be4

##### Steps To Reproduce
1. Go to /console/project/XXX/create/category/php
2. Notice how template descriptions are replaced by name (?)

##### Current Result
Descriptions do not appear

##### Expected Result
Descriptions should appear

**Comment by jwforres** [comment]
This is already fixed in master and patched for OCP 3.5
