### ISSUE TITLE
[cluster up] Allow to change the permissions of created persistent volumes

### ISSUE THREAD

**Issue by hferentschik** [openshift/origin#14076]
Following up on #13496 as well as https://github.com/minishift/minishift/issues/856, I'd suggest to add some form of flag or other mechanism to configure the permissions hostPath based persistent volumes get configured with _cluster up_.

cc @csrwng

**Comment by csrwng** [comment]
trello card
https://trello.com/c/Y5B2fKsp/1255-cluster-up-allow-creation-of-world-writeable-persistent-volumes

**Comment by gbraad** [comment]
@hferentschik please, also have a look at https://github.com/openshift/origin/pull/16631 This is the proposed solution from OpenShift's side. With a marker file we can prevent the creation of the PVs to happen.
