### ISSUE TITLE
oc start-build --list-webhooks doesn't support gitlab and bitbucket

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#14071]
`oc start-build --list-webhooks` doesn't list gitlab and bitbucket as accepted values:
```console
$ oc start-build -h | grep list-webhook
      --list-webhooks='': List the webhooks for the specified build config or build; accepts 'all', 'generic', or 'github'
```
After [looking to the source code](https://github.com/openshift/origin/blob/076d2314b0296b6c0d486010ef6167cae6cec1b5/pkg/cmd/cli/cmd/startbuild.go#L420-L430) it turns out it doesn't support them at all.

@bparees @gabemontero @oatmealraisin

**Comment by gabemontero** [comment]
thanks for the heads up @php-coder

**Comment by php-coder** [comment]
After implementing this, could you also update example in documentation at https://docs.openshift.com/online/cli_reference/basic_cli_operations.html#start-build ?

>List the webhooks for the specified build configuration or build; accepts all, generic, or github:
>
>$ oc start-build --list-webhooks

Also it's better to edit command to `oc start-build --list-webhooks=<type>`

**Comment by bparees** [comment]
We're not going to implement it. Start build via webhook exists only to support our internal git server use case, thus it only needs to support the github hook. This was a conscious decision.

**Comment by gabemontero** [comment]
dahh!!  totally forgot that ...thanks @bparees

**Comment by php-coder** [comment]
Thanks, Ben!

I could only add that from a user perspective if `oc start-build --list-webhooks=all` doesn't list gitlab/bitbucket, then it will be unexpected behavior and look like a bug.
