### ISSUE TITLE
[Fail] [builds][Slow] openshift pipeline build Pipeline using jenkins-client-plugin [It] should build and complete successfully

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#14084]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended/319/consoleFull#82220402358b6e51eb7608a5981914356

[Fail] [builds][Slow] openshift pipeline build Pipeline using jenkins-client-plugin [It] should build and complete successfully 
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:176

• Failure [562.954 seconds]
[builds][Slow] openshift pipeline build
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:395
  Pipeline using jenkins-client-plugin
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:182
    should build and complete successfully [It]
    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:181

    Expected
        <bool>: false
    to be true

    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:176

**Comment by gabemontero** [comment]
Took a peek.  Saw the same SSL conn errors and watch timeouts from jenkins in the jenkins pod log, similar to https://github.com/openshift/origin/issues/13984, and what we've reproduce in debug runs with https://github.com/openshift/origin/pull/14013

These just manifest in a couple of different spots / different tests intemittently.

Close as a dup of the above.
