### ISSUE TITLE
How to make CNI work with redhat/openshift-ovs-multitenant?

### ISSUE THREAD

**Issue by gustavohenrique** [openshift/origin#14081]
I'm trying to configure a cluster manually (not using Ansible) as I described in https://github.com/openshift/origin/issues/13959. But I didn't found how to configure the network for communication between master and nodes.
Can anyone help me about how to configure a network plugin in Origin?

##### Version
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
etcd 3.1.0
CentOS 7
Docker 17.03.1-ce

**Comment by knobunc** [comment]
What is the error you are hitting?  You need to get the CNI pieces in the right place, and then you need to allow VxLAN traffic between your nodes (on port 4789), but the SDN should take care of that rule in iptables.

Take a look at https://github.com/openshift/origin/blob/master/images/dind/node/Dockerfile for how it is setting up the files for CNI.

**Comment by bmeng** [comment]
I think you can refer to this file to put the CNI related files into right place. 
https://github.com/openshift/origin/blob/master/contrib/node/install-sdn.sh

**Comment by kargakis** [comment]
Not something that needs to be tracked in our issue tracker.
