### ISSUE TITLE
TestRoundTrip flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14097]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_check/1770/testReport/junit/github.com_openshift_origin_vendor_k8s/io_kubernetes_pkg_api/TestRoundTrip/

@mfojtik

**Comment by derekwaynecarr** [comment]
i cant access the logs anymore.

have not seen this flake in > 3 months.

closing for now.  re-open if we see again.
