### ISSUE TITLE
cannot create Data Store PostgreSQL: error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

### ISSUE THREAD

**Issue by fossil** [openshift/origin#14091]
[provide a description of the issue]
cannot create Data Store PostgreSQL

##### Version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.178.20:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
trying jee example
http://www.mastertheboss.com/soa-cloud/openshift/java-ee-example-application-on-openshift
logged in as developer developer
created new project demoejb
demojee>>Add to project>>Catalog>>Data stores>>PostgreSQL
Create with all default parameters
then go to Overview and see the error
Log:
error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

##### Current Result
Data Store PostgreSQL cannot be created

##### Expected Result
Data Store PostgreSQL created successfully.

##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
sudo oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/home/fossil/.kube/config'
Info:  Using context for cluster-admin access: 'myproject/192-168-178-20:8443/system:admin'

[Note] Running diagnostic: ConfigContexts[demojee/192-168-178-20:8443/developer]
       Description: Validate client config context is complete and has connectivity
       
Info:  For client config context 'demojee/192-168-178-20:8443/developer':
       The server URL is 'https://192.168.178.20:8443'
       The user authentication is 'developer/192-168-178-20:8443'
       The current project is 'demojee'
       Successfully requested project list; has access to project(s):
         [demojee myproject]
       
[Note] Running diagnostic: ConfigContexts[myproject/192-168-178-20:8443/system:admin]
       Description: Validate client config context is complete and has connectivity
       
Info:  For client config context 'myproject/192-168-178-20:8443/system:admin':
       The server URL is 'https://192.168.178.20:8443'
       The user authentication is 'system:admin/192-168-178-20:8443'
       The current project is 'myproject'
       Successfully requested project list; has access to project(s):
         [default demojee kube-system myproject openshift openshift-infra]
       
[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint
       
ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:155]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected
              
       ERROR: [DP1001 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:53]
              could not read the service account token: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
              
       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected
              
       [Note] Summary of diagnostics execution (version v1.5.0+031cbe4):
       [Note] Errors seen: 1
       
[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint
       
ERROR: [DNet2001 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:77]
       Checking network plugin failed. Error: User "developer" cannot get clusternetworks at the cluster scope
       
[Note] Skipping diagnostic: AggregatedLogging
       Description: Check aggregated logging integration for proper configuration
       Because: No master config file was provided
       
[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry
       
ERROR: [DClu1006 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:209]
       The "docker-registry" service exists but has no associated pods, so it
       is not available. Builds and deployments that use the registry will fail.
       
[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects
       
Info:  clusterrolebinding/cluster-admins has more subjects than expected.
       
       Use the `oadm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.
       
Info:  clusterrolebinding/cluster-admins has extra subject {ServiceAccount default pvinstaller    }.

[Note] Running diagnostic: ClusterRoles
       Description: Check that the default ClusterRoles are present and contain the expected permissions
       
[Note] Running diagnostic: ClusterRouterName
       Description: Check there is a working router
       
ERROR: [DClu2007 from diagnostic ClusterRouter@openshift/origin/pkg/diagnostics/cluster/router.go:156]
       The "router" DeploymentConfig exists but has no running pods, so it
       is not available. Apps will not be externally accessible via the router.
       
[Note] Running diagnostic: MasterNode
       Description: Check if master is also running node (for Open vSwitch)
       
Info:  Found a node with same IP as master: 192.168.178.20

[Note] Skipping diagnostic: MetricsApiProxy
       Description: Check the integrated heapster metrics can be reached via the API proxy
       Because: The heapster service does not exist in the openshift-infra project at this time,
       so it is not available for the Horizontal Pod Autoscaler to use as a source of metrics.
       
[Note] Running diagnostic: NodeDefinitions
       Description: Check node records on master
       
[Note] Skipping diagnostic: ServiceExternalIPs
       Description: Check for existing services with ExternalIPs that are disallowed by master config
       Because: No master config file was detected
       
[Note] Summary of diagnostics execution (version v1.5.0+031cbe4):
[Note] Errors seen: 4

[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
sudo oc get all -o json -n demojee
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "DeploymentConfig",
            "metadata": {
                "creationTimestamp": "2017-05-06T16:44:41Z",
                "generation": 2,
                "labels": {
                    "app": "postgresql-persistent",
                    "template": "postgresql-persistent-template"
                },
                "name": "postgresql",
                "namespace": "demojee",
                "resourceVersion": "1102",
                "selfLink": "/oapi/v1/namespaces/demojee/deploymentconfigs/postgresql",
                "uid": "4d23689f-327b-11e7-be4f-3c970e16854b"
            },
            "spec": {
                "replicas": 1,
                "selector": {
                    "name": "postgresql"
                },
                "strategy": {
                    "activeDeadlineSeconds": 21600,
                    "recreateParams": {
                        "timeoutSeconds": 600
                    },
                    "resources": {},
                    "type": "Recreate"
                },
                "template": {
                    "metadata": {
                        "creationTimestamp": null,
                        "labels": {
                            "name": "postgresql"
                        }
                    },
                    "spec": {
                        "containers": [
                            {
                                "env": [
                                    {
                                        "name": "POSTGRESQL_USER",
                                        "valueFrom": {
                                            "secretKeyRef": {
                                                "key": "database-user",
                                                "name": "postgresql"
                                            }
                                        }
                                    },
                                    {
                                        "name": "POSTGRESQL_PASSWORD",
                                        "valueFrom": {
                                            "secretKeyRef": {
                                                "key": "database-password",
                                                "name": "postgresql"
                                            }
                                        }
                                    },
                                    {
                                        "name": "POSTGRESQL_DATABASE",
                                        "value": "sampledb"
                                    }
                                ],
                                "image": "centos/postgresql-95-centos7@sha256:3a20fe72d4906533eb7d26f394d03137e32c4857e8632561662549590e25d8ad",
                                "imagePullPolicy": "IfNotPresent",
                                "livenessProbe": {
                                    "failureThreshold": 3,
                                    "initialDelaySeconds": 30,
                                    "periodSeconds": 10,
                                    "successThreshold": 1,
                                    "tcpSocket": {
                                        "port": 5432
                                    },
                                    "timeoutSeconds": 1
                                },
                                "name": "postgresql",
                                "ports": [
                                    {
                                        "containerPort": 5432,
                                        "protocol": "TCP"
                                    }
                                ],
                                "readinessProbe": {
                                    "exec": {
                                        "command": [
                                            "/bin/sh",
                                            "-i",
                                            "-c",
                                            "psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'"
                                        ]
                                    },
                                    "failureThreshold": 3,
                                    "initialDelaySeconds": 5,
                                    "periodSeconds": 10,
                                    "successThreshold": 1,
                                    "timeoutSeconds": 1
                                },
                                "resources": {
                                    "limits": {
                                        "memory": "512Mi"
                                    }
                                },
                                "securityContext": {
                                    "capabilities": {},
                                    "privileged": false
                                },
                                "terminationMessagePath": "/dev/termination-log",
                                "volumeMounts": [
                                    {
                                        "mountPath": "/var/lib/pgsql/data",
                                        "name": "postgresql-data"
                                    }
                                ]
                            }
                        ],
                        "dnsPolicy": "ClusterFirst",
                        "restartPolicy": "Always",
                        "securityContext": {},
                        "terminationGracePeriodSeconds": 30,
                        "volumes": [
                            {
                                "name": "postgresql-data",
                                "persistentVolumeClaim": {
                                    "claimName": "postgresql"
                                }
                            }
                        ]
                    }
                },
                "test": false,
                "triggers": [
                    {
                        "imageChangeParams": {
                            "automatic": true,
                            "containerNames": [
                                "postgresql"
                            ],
                            "from": {
                                "kind": "ImageStreamTag",
                                "name": "postgresql:9.5",
                                "namespace": "openshift"
                            },
                            "lastTriggeredImage": "centos/postgresql-95-centos7@sha256:3a20fe72d4906533eb7d26f394d03137e32c4857e8632561662549590e25d8ad"
                        },
                        "type": "ImageChange"
                    },
                    {
                        "type": "ConfigChange"
                    }
                ]
            },
            "status": {
                "availableReplicas": 0,
                "conditions": [
                    {
                        "lastTransitionTime": "2017-05-06T16:44:41Z",
                        "lastUpdateTime": "2017-05-06T16:44:41Z",
                        "message": "Deployment config does not have minimum availability.",
                        "status": "False",
                        "type": "Available"
                    },
                    {
                        "lastTransitionTime": "2017-05-06T16:44:43Z",
                        "lastUpdateTime": "2017-05-06T16:44:43Z",
                        "message": "replication controller \"postgresql-1\" has failed progressing",
                        "reason": "ProgressDeadlineExceeded",
                        "status": "False",
                        "type": "Progressing"
                    }
                ],
                "details": {
                    "causes": [
                        {
                            "imageTrigger": {
                                "from": {
                                    "kind": "ImageStreamTag",
                                    "name": "postgresql:9.5",
                                    "namespace": "openshift"
                                }
                            },
                            "type": "ImageChange"
                        }
                    ],
                    "message": "image change"
                },
                "latestVersion": 1,
                "observedGeneration": 2,
                "replicas": 0,
                "unavailableReplicas": 0,
                "updatedReplicas": 0
            }
        },
        {
            "apiVersion": "v1",
            "kind": "ReplicationController",
            "metadata": {
                "annotations": {
                    "kubectl.kubernetes.io/desired-replicas": "1",
                    "openshift.io/deployer-pod.name": "postgresql-1-deploy",
                    "openshift.io/deployment-config.latest-version": "1",
                    "openshift.io/deployment-config.name": "postgresql",
                    "openshift.io/deployment.phase": "Failed",
                    "openshift.io/deployment.replicas": "0",
                    "openshift.io/deployment.status-reason": "image change",
                    "openshift.io/encoded-deployment-config": "{\"kind\":\"DeploymentConfig\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"postgresql\",\"namespace\":\"demojee\",\"selfLink\":\"/oapi/v1/namespaces/demojee/deploymentconfigs/postgresql\",\"uid\":\"4d23689f-327b-11e7-be4f-3c970e16854b\",\"resourceVersion\":\"1081\",\"generation\":2,\"creationTimestamp\":\"2017-05-06T16:44:41Z\",\"labels\":{\"app\":\"postgresql-persistent\",\"template\":\"postgresql-persistent-template\"}},\"spec\":{\"strategy\":{\"type\":\"Recreate\",\"recreateParams\":{\"timeoutSeconds\":600},\"resources\":{},\"activeDeadlineSeconds\":21600},\"triggers\":[{\"type\":\"ImageChange\",\"imageChangeParams\":{\"automatic\":true,\"containerNames\":[\"postgresql\"],\"from\":{\"kind\":\"ImageStreamTag\",\"namespace\":\"openshift\",\"name\":\"postgresql:9.5\"},\"lastTriggeredImage\":\"centos/postgresql-95-centos7@sha256:3a20fe72d4906533eb7d26f394d03137e32c4857e8632561662549590e25d8ad\"}},{\"type\":\"ConfigChange\"}],\"replicas\":1,\"test\":false,\"selector\":{\"name\":\"postgresql\"},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"name\":\"postgresql\"}},\"spec\":{\"volumes\":[{\"name\":\"postgresql-data\",\"persistentVolumeClaim\":{\"claimName\":\"postgresql\"}}],\"containers\":[{\"name\":\"postgresql\",\"image\":\"centos/postgresql-95-centos7@sha256:3a20fe72d4906533eb7d26f394d03137e32c4857e8632561662549590e25d8ad\",\"ports\":[{\"containerPort\":5432,\"protocol\":\"TCP\"}],\"env\":[{\"name\":\"POSTGRESQL_USER\",\"valueFrom\":{\"secretKeyRef\":{\"name\":\"postgresql\",\"key\":\"database-user\"}}},{\"name\":\"POSTGRESQL_PASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"name\":\"postgresql\",\"key\":\"database-password\"}}},{\"name\":\"POSTGRESQL_DATABASE\",\"value\":\"sampledb\"}],\"resources\":{\"limits\":{\"memory\":\"512Mi\"}},\"volumeMounts\":[{\"name\":\"postgresql-data\",\"mountPath\":\"/var/lib/pgsql/data\"}],\"livenessProbe\":{\"tcpSocket\":{\"port\":5432},\"initialDelaySeconds\":30,\"timeoutSeconds\":1,\"periodSeconds\":10,\"successThreshold\":1,\"failureThreshold\":3},\"readinessProbe\":{\"exec\":{\"command\":[\"/bin/sh\",\"-i\",\"-c\",\"psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'\"]},\"initialDelaySeconds\":5,\"timeoutSeconds\":1,\"periodSeconds\":10,\"successThreshold\":1,\"failureThreshold\":3},\"terminationMessagePath\":\"/dev/termination-log\",\"imagePullPolicy\":\"IfNotPresent\",\"securityContext\":{\"capabilities\":{},\"privileged\":false}}],\"restartPolicy\":\"Always\",\"terminationGracePeriodSeconds\":30,\"dnsPolicy\":\"ClusterFirst\",\"securityContext\":{}}}},\"status\":{\"latestVersion\":1,\"observedGeneration\":1,\"replicas\":0,\"updatedReplicas\":0,\"availableReplicas\":0,\"unavailableReplicas\":0,\"details\":{\"message\":\"image change\",\"causes\":[{\"type\":\"ImageChange\",\"imageTrigger\":{\"from\":{\"kind\":\"ImageStreamTag\",\"namespace\":\"openshift\",\"name\":\"postgresql:9.5\"}}}]},\"conditions\":[{\"type\":\"Available\",\"status\":\"False\",\"lastUpdateTime\":\"2017-05-06T16:44:41Z\",\"lastTransitionTime\":\"2017-05-06T16:44:41Z\",\"message\":\"Deployment config does not have minimum availability.\"}]}}\n"
                },
                "creationTimestamp": "2017-05-06T16:44:41Z",
                "generation": 1,
                "labels": {
                    "app": "postgresql-persistent",
                    "openshift.io/deployment-config.name": "postgresql",
                    "template": "postgresql-persistent-template"
                },
                "name": "postgresql-1",
                "namespace": "demojee",
                "resourceVersion": "1101",
                "selfLink": "/api/v1/namespaces/demojee/replicationcontrollers/postgresql-1",
                "uid": "4d2dc75d-327b-11e7-be4f-3c970e16854b"
            },
            "spec": {
                "replicas": 0,
                "selector": {
                    "deployment": "postgresql-1",
                    "deploymentconfig": "postgresql",
                    "name": "postgresql"
                },
                "template": {
                    "metadata": {
                        "annotations": {
                            "openshift.io/deployment-config.latest-version": "1",
                            "openshift.io/deployment-config.name": "postgresql",
                            "openshift.io/deployment.name": "postgresql-1"
                        },
                        "creationTimestamp": null,
                        "labels": {
                            "deployment": "postgresql-1",
                            "deploymentconfig": "postgresql",
                            "name": "postgresql"
                        }
                    },
                    "spec": {
                        "containers": [
                            {
                                "env": [
                                    {
                                        "name": "POSTGRESQL_USER",
                                        "valueFrom": {
                                            "secretKeyRef": {
                                                "key": "database-user",
                                                "name": "postgresql"
                                            }
                                        }
                                    },
                                    {
                                        "name": "POSTGRESQL_PASSWORD",
                                        "valueFrom": {
                                            "secretKeyRef": {
                                                "key": "database-password",
                                                "name": "postgresql"
                                            }
                                        }
                                    },
                                    {
                                        "name": "POSTGRESQL_DATABASE",
                                        "value": "sampledb"
                                    }
                                ],
                                "image": "centos/postgresql-95-centos7@sha256:3a20fe72d4906533eb7d26f394d03137e32c4857e8632561662549590e25d8ad",
                                "imagePullPolicy": "IfNotPresent",
                                "livenessProbe": {
                                    "failureThreshold": 3,
                                    "initialDelaySeconds": 30,
                                    "periodSeconds": 10,
                                    "successThreshold": 1,
                                    "tcpSocket": {
                                        "port": 5432
                                    },
                                    "timeoutSeconds": 1
                                },
                                "name": "postgresql",
                                "ports": [
                                    {
                                        "containerPort": 5432,
                                        "protocol": "TCP"
                                    }
                                ],
                                "readinessProbe": {
                                    "exec": {
                                        "command": [
                                            "/bin/sh",
                                            "-i",
                                            "-c",
                                            "psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'"
                                        ]
                                    },
                                    "failureThreshold": 3,
                                    "initialDelaySeconds": 5,
                                    "periodSeconds": 10,
                                    "successThreshold": 1,
                                    "timeoutSeconds": 1
                                },
                                "resources": {
                                    "limits": {
                                        "memory": "512Mi"
                                    }
                                },
                                "securityContext": {
                                    "capabilities": {},
                                    "privileged": false
                                },
                                "terminationMessagePath": "/dev/termination-log",
                                "volumeMounts": [
                                    {
                                        "mountPath": "/var/lib/pgsql/data",
                                        "name": "postgresql-data"
                                    }
                                ]
                            }
                        ],
                        "dnsPolicy": "ClusterFirst",
                        "restartPolicy": "Always",
                        "securityContext": {},
                        "terminationGracePeriodSeconds": 30,
                        "volumes": [
                            {
                                "name": "postgresql-data",
                                "persistentVolumeClaim": {
                                    "claimName": "postgresql"
                                }
                            }
                        ]
                    }
                }
            },
            "status": {
                "observedGeneration": 1,
                "replicas": 0
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "creationTimestamp": "2017-05-06T16:44:41Z",
                "labels": {
                    "app": "postgresql-persistent",
                    "template": "postgresql-persistent-template"
                },
                "name": "postgresql",
                "namespace": "demojee",
                "resourceVersion": "1075",
                "selfLink": "/api/v1/namespaces/demojee/services/postgresql",
                "uid": "4d1992f5-327b-11e7-be4f-3c970e16854b"
            },
            "spec": {
                "clusterIP": "172.30.252.9",
                "ports": [
                    {
                        "name": "postgresql",
                        "port": 5432,
                        "protocol": "TCP",
                        "targetPort": 5432
                    }
                ],
                "selector": {
                    "name": "postgresql"
                },
                "sessionAffinity": "None",
                "type": "ClusterIP"
            },
            "status": {
                "loadBalancer": {}
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Pod",
            "metadata": {
                "annotations": {
                    "openshift.io/deployment.name": "postgresql-1",
                    "openshift.io/scc": "restricted"
                },
                "creationTimestamp": "2017-05-06T16:44:41Z",
                "labels": {
                    "openshift.io/deployer-pod-for.name": "postgresql-1"
                },
                "name": "postgresql-1-deploy",
                "namespace": "demojee",
                "resourceVersion": "1113",
                "selfLink": "/api/v1/namespaces/demojee/pods/postgresql-1-deploy",
                "uid": "4d3caa18-327b-11e7-be4f-3c970e16854b"
            },
            "spec": {
                "activeDeadlineSeconds": 21600,
                "containers": [
                    {
                        "env": [
                            {
                                "name": "KUBERNETES_MASTER",
                                "value": "https://192.168.178.20:8443"
                            },
                            {
                                "name": "OPENSHIFT_MASTER",
                                "value": "https://192.168.178.20:8443"
                            },
                            {
                                "name": "BEARER_TOKEN_FILE",
                                "value": "/var/run/secrets/kubernetes.io/serviceaccount/token"
                            },
                            {
                                "name": "OPENSHIFT_CA_DATA",
                                "value": "-----BEGIN CERTIFICATE-----\nMIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu\nc2hpZnQtc2lnbmVyQDE0OTQwNjI1NDIwHhcNMTcwNTA2MDkyMjIxWhcNMjIwNTA1\nMDkyMjIyWjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE0OTQwNjI1NDIw\nggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDggTVHUekogjSzWmB70pVC\nUc/HdgmVxGFoxbaFULA0Vodx/tJUnmd+V06pMsO+aGrLd7FgOCBfmOkmzjBmBypU\nSKyS0qvbaWKzOVgmMfVrdH0voA91Ju1sja55fHSx/0HhmGy82y1DD3wj+Af0ltbQ\nxsM45QZQYpYm/vUnoAwwk2p87OCa1+qJ9/IIxJuxS026IJ81aPgFDSGviXNUY1VC\nwiX8FuQKU6mBaHCTaJnvgi3ibMjTxuLfC0Jexv6t6AqgX6zAUanzehqm32GuSbYd\nyBq+iRXUWT0DBvdyR8heu4R2D7I7ziPaimbv8AaBo+lXin4ERcmTC8WfHstu3kAx\nAgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG\nSIb3DQEBCwUAA4IBAQC4zp0T5cIZtHDcMBn9H133O6rTLve2/o0IjgVIJXCijr/G\ncY7oJMnrskqRXbMFGznoTnJyoK71xcQQ09sbm9Sq95Hjn6JyqJcmj72LPdhpVnJG\nN81KfxeJTPJdF+oLUeiVdHlKMbBcsPBNDXHTIWQhKM6kzqyzUxqcmeQw7FKtMSpZ\nTlls/lRBaHhdY0oBZofJmNSLC8Ayx+gUIuY+uOXS/L1h6HO4h0zZWrwWtDnKbbyW\nRqSqSqkEeDTl4wvs/kHeSlb00Jx5Wqbw3G2NeZL6Wow/0ej1V5MHK4+Tu02K5LCA\nAKJ/WnSId5b/PUDf8sOCCSiZJr1ojluvrS8hU4Gl\n-----END CERTIFICATE-----\n"
                            },
                            {
                                "name": "OPENSHIFT_DEPLOYMENT_NAME",
                                "value": "postgresql-1"
                            },
                            {
                                "name": "OPENSHIFT_DEPLOYMENT_NAMESPACE",
                                "value": "demojee"
                            }
                        ],
                        "image": "openshift/origin-deployer:v1.5.0",
                        "imagePullPolicy": "IfNotPresent",
                        "name": "deployment",
                        "resources": {},
                        "securityContext": {
                            "capabilities": {
                                "drop": [
                                    "KILL",
                                    "MKNOD",
                                    "SETGID",
                                    "SETUID",
                                    "SYS_CHROOT"
                                ]
                            },
                            "privileged": false,
                            "runAsUser": 1000050000,
                            "seLinuxOptions": {
                                "level": "s0:c7,c4"
                            }
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "volumeMounts": [
                            {
                                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "name": "deployer-token-z09fk",
                                "readOnly": true
                            }
                        ]
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "imagePullSecrets": [
                    {
                        "name": "deployer-dockercfg-w838k"
                    }
                ],
                "nodeName": "192.168.178.20",
                "restartPolicy": "Never",
                "securityContext": {
                    "fsGroup": 1000050000,
                    "seLinuxOptions": {
                        "level": "s0:c7,c4"
                    }
                },
                "serviceAccount": "deployer",
                "serviceAccountName": "deployer",
                "terminationGracePeriodSeconds": 10,
                "volumes": [
                    {
                        "name": "deployer-token-z09fk",
                        "secret": {
                            "defaultMode": 420,
                            "secretName": "deployer-token-z09fk"
                        }
                    }
                ]
            },
            "status": {
                "conditions": [
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2017-05-06T16:44:41Z",
                        "status": "True",
                        "type": "Initialized"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2017-05-06T16:44:41Z",
                        "message": "containers with unready status: [deployment]",
                        "reason": "ContainersNotReady",
                        "status": "False",
                        "type": "Ready"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2017-05-06T16:44:41Z",
                        "status": "True",
                        "type": "PodScheduled"
                    }
                ],
                "containerStatuses": [
                    {
                        "containerID": "docker://e22ef67b67d87207801054281f37f865fdeecccc52ff92426a593a5f73867653",
                        "image": "openshift/origin-deployer:v1.5.0",
                        "imageID": "docker-pullable://openshift/origin-deployer@sha256:39ddbba5da02dbf130b92d0fcca99d61fcf9680cbc60f435d1f38c15e432d04c",
                        "lastState": {},
                        "name": "deployment",
                        "ready": false,
                        "restartCount": 0,
                        "state": {
                            "terminated": {
                                "containerID": "docker://e22ef67b67d87207801054281f37f865fdeecccc52ff92426a593a5f73867653",
                                "exitCode": 1,
                                "finishedAt": "2017-05-06T16:44:43Z",
                                "reason": "Error",
                                "startedAt": "2017-05-06T16:44:43Z"
                            }
                        }
                    }
                ],
                "hostIP": "192.168.178.20",
                "phase": "Failed",
                "startTime": "2017-05-06T16:44:41Z"
            }
        }
    ],
    "kind": "List",
    "metadata": {},
    "resourceVersion": "",
    "selfLink": ""
}

[visit https://docs.openshift.org/latest/welcome/index.html]
Visited

**Comment by enj** [comment]
@soltysh closing as duplicate of https://github.com/openshift/origin/issues/13865.
