### ISSUE TITLE
TestRecreateSecretControllerFlow flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14096]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_check/1770/testReport/junit/github/com_openshift_origin_pkg_service_controller_servingcert/TestRecreateSecretControllerFlow/

@deads2k @mfojtik

**Comment by mfojtik** [comment]
@kargakis 404, do we have any logs from this?

**Comment by mfojtik** [comment]
@kargakis moving this to P2, will bump back when this occurs again.

**Comment by mfojtik** [comment]
Closing due to age
