### ISSUE TITLE
Route default hostname does not respect public-hostname setting in oc cluster up

### ISSUE THREAD

**Issue by DuncanDoyle** [openshift/origin#14099]
[provide a description of the issue]

In the previous versions, the "oc expose" command would respect the hostname set with "--public-hostname" when creating default hostnames in the route. For example, when --public-hostname is set to "127.0.0.1", the default route created for a service would be "{service-name}.127.0.0.1.xip.io"

In OpenShift Origin 1.5 this no longer works. When setting my public-hostname to 127.0.0.1, the route created still gets the public IP address of my network adapter, e.g.: "{service-name}.192.168.1.64.xip.io".

##### Version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. oc cluster up --public-hostname=127.0.0.1
2. Create a service
3. Create a default route for the service

##### Current Result
The hostname of the route uses the public IP address of my network adapter (e.g. 192.168.1.64)

##### Expected Result
The hostname of the route should use the hostname set by "--public-hostname".

##### Additional Information
na

**Comment by jawnsy** [comment]
Can you work around the problem while we investigate by using the --routing-suffix flag?

For example: `oc cluster up --public-hostname=127.0.0.1 --routing-suffix=127.0.0.1.xip.io`

**Comment by DuncanDoyle** [comment]
The "--routing-suffix" workaround does not seem to work for me either. It still uses the {public-ip}.xip.io as suffix. I can workaround the problem for now by explicitly setting the hostname when creating the route.

**Comment by DuncanDoyle** [comment]
FYI, after starting my cluster with an empty config and data directory, the "--routing-suffix" flag does work.
