### ISSUE TITLE
client.JSONPrinter{} should not sort the JSON items

### ISSUE THREAD

**Issue by VojtechVitek** [openshift/origin#141]
`client.JSONPrinter{}`, as used in `openshift kube process -c template.json` command, should preserve order of the template's JSON items for better readability.

Seems like the used [json.MarshalIndent()](http://golang.org/pkg/encoding/json/#MarshalIndent) method https://github.com/openshift/origin/blob/master/pkg/cmd/client/json_printer.go#L20 sorts the items automatically. We need to either reimplement this method or figure out how to turn off the sorting.

Also, I'd expect the '\n' character at the end of the result JSON output.

/cc @mfojtik @bparees

**Comment by smarterclayton** [comment]
Closing without prejudice - reopen upstream or suggest a fix.
