### ISSUE TITLE
`oc cluster up --version=latest` fails on the Mac

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#14101]
The command

```
$ oc cluster up --version=latest
```

fails on a Mac with this error:

> failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"

After updating node-config.yaml with these args as suggested by @ncdc 

```yaml
kubeletArguments:
  cgroup-driver:
    - 'cgroupfs'
```

the cluster starts, but no nodes become available.

> Failed to start ContainerManager failed to initialise top level QOS containers: root container /kubepods doesn't exist

Here are the events from `oc describe node localhost`:

```
FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1m		1m		1	kubelet, localhost			Normal		Starting		Starting kubelet.
  1m		1m		1	kubelet, localhost			Warning		ImageGCFailed		unable to find data for container /
  1m		1m		2	kubelet, localhost			Normal		NodeHasSufficientDisk	Node localhost status is now: NodeHasSufficientDisk
  1m		1m		2	kubelet, localhost			Normal		NodeHasSufficientMemory	Node localhost status is now: NodeHasSufficientMemory
  1m		1m		2	kubelet, localhost			Normal		NodeHasNoDiskPressure	Node localhost status is now: NodeHasNoDiskPressure
  1m		1m		1	kubelet, localhost			Warning		KubeletSetupFailed	Failed to start ContainerManager failed to initialise top level QOS containers: root container /kubepods doesn't exist
```

cc @csrwng @jwforres @derekwaynecarr

**Comment by kargakis** [comment]
Seeing this in Fedora 25 too

**Comment by csrwng** [comment]
@kargakis can you try with PR https://github.com/openshift/origin/pull/13964 and see if that resolves your issue? (you'd have to build an origin image with that code as well). I'm really surprised that it's happening in fedora, given that we do have systemd there and the cgroups are known. It could be a different issue.

**Comment by kargakis** [comment]
> @kargakis can you try with PR #13964 and see if that resolves your issue? (you'd have to build an origin image with that code as well). I'm really surprised that it's happening in fedora, given that we do have systemd there and the cgroups are known. It could be a different issue.

@csrwng works like a charm!

**Comment by alberttwong** [comment]
https://github.com/openshift/origin/issues/17570
