### ISSUE TITLE
net/http: TLS handshake timeout deployment flake

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#14109]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1250/consoleFull#-169259343956c60d7be4b02b88ae8c268b

[Fail] deploymentconfigs with revision history limits [Conformance] [It] should never persist more old deployments than acceptable after being observed by the controller

In this case, the deployer pod failed to speak to the master API:

```
May  9 07:44:55.904: INFO: --- pod history-limit-8-deploy logs
2017-05-09T11:40:04.577121000Z error: couldn't get deployment history-limit-8: Get https://172.30.0.1:443/api/v1/namespaces/extended-test-cli-deployment-3zn4t-5kkzz/replicationcontrollers/history-limit-8: net/http: TLS handshake timeout---
```

Although this looks a bit like #11114 I'm opening a new issue because I didn't see any obvious specific evidence of etcd/credentials issues here.

**Comment by tnozicka** [comment]
So this was either infra failing or API server going down in exactly that moment, but I am inclined to blame infra. In both cases the hasn't been an occurrence of this for a **long** time and I see no action to be taken for fixing this.
