### ISSUE TITLE
Can't build against golang 1.8; need goproxy update

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#14104]
kubernetes git now requires golang 1.8 to build, but openshift won't run if built against golang 1.8 because of https://github.com/elazarl/goproxy/issues/208. We need to update goproxy, presumably to the same version as kubernetes (c4fc265).

I started doing this but then noticed that there are special hacks for goproxy in hacks/godep-restore.sh so I figure someone who knows what that's about should deal with it.

**Comment by smarterclayton** [comment]
@ncdc

**Comment by smarterclayton** [comment]
Moving to 3.6 because we may need to compile on 1.8 earlier in case an Os breaks.

**Comment by danwinship** [comment]
FWIW it turns out we don't even need a full goproxy update; just grabbing the updated version of certs.go with a golang-1.8-generated certificate fixes things

**Comment by liggitt** [comment]
there were quite a few certs in kubernetes that had to be updated as well

**Comment by danwinship** [comment]
this was fixed by #14754
