### ISSUE TITLE
RC and pods left after garbage collection

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#14115]
The template service broker e2e extended test instantiates then removes the cakephp-mysql-persistent template.  Now that GC is switched on, the removal cascades to all the objects named in the template, but some additional objects are not deleted:

```
$ oc get all
NAME         DESIRED   CURRENT   READY     AGE
rc/mysql-1   1         1         0         6m

NAME                READY     STATUS              RESTARTS   AGE
po/mysql-1-1gs6r    0/1       ContainerCreating   0          6m
po/mysql-1-deploy   1/1       Running             0          6m
```

(in this case, po/mysql-1-1gs6r is stuck forever as a PVC it requires has already gone).

Exactly which objects get left may be timing dependent.

Should the deployment controller / replication controller set OwnerReferences on DC and RC objects to enable cascading delete?

**Comment by kargakis** [comment]
The RC controller already sets owner refs in Pods. Only missing piece is the DC controller setting owner refs in RCs. Tacked in https://trello.com/c/B10xLQ6L/927-set-owner-refs-in-rcs-owned-by-dcs

**Comment by tnozicka** [comment]
@jim-minter this should be already fixed by https://github.com/openshift/origin/pull/14322

**Comment by kargakis** [comment]
@tnozicka do we have an integration test for owner refs?

**Comment by tnozicka** [comment]
@kargakis not yet. I have an issue for it here: https://github.com/openshift/origin/issues/14416

**Comment by kargakis** [comment]
Cool, closing this issue in favor of that one.
