### ISSUE TITLE
Command line client uses git show --quiet instead of -s

### ISSUE THREAD

**Issue by lbilger** [openshift/origin#14111]
I had a problem with builds using `oc start-build` sporadically failing. Finally I found that it was due to the complete diff of the current git commit being included in the commit message that was sent to OpenShift (`spec.revision.git.message` in the build's yaml). For large commits, this seems to cause a problem with no helpful error message - the only thing I could find in the build log was this:

`container_linux.go:247: starting container process caused "process_linux.go:334: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: \""`

Looking into the source code of the `oc` command line client, I found that it is using `git show --quiet` to get the revision information from git. This does not work on our - admittedly old - version `1.7.10.4` of `git`. Also, I can't find anything about it in the documentation even of a newer version of `git` (tried `git help show`). It seems not to be a supported option for `git show`. However, `git show -s` seems to create the expected output on all versions I tried.

I also found this mailing list conversation where it is said that `-s` should be used instead of `--quiet`: http://git.661346.n2.nabble.com/git-show-and-the-quiet-option-td6414698.html

If you decide not to change this because it only affects old versions of git, maybe this issue will at least point others with the same problem in the right direction.

##### Version
```
oc v1.3.2
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server ***
openshift v3.4.1.10
kubernetes v1.4.0+776c994
```

##### Steps To Reproduce
1. Install git version 1.7.10.4
2. start a binary build from within a git repository

##### Current Result
Diff is appended to commit message.

##### Expected Result
Diff is not appended.

**Comment by juanvallejo** [comment]
@lbilger I was able to reproduce the `--quiet` flag not suppressing diff with git `1.7.10.4` (it did suppress diff with `-s`). However, I am not able to get `oc start-build` to fail with this version of `git` in my path.

Are you still able to reproduce this issue with a newer version of `oc`?
Also, can you provide a sample output of what you see when `oc start-build` fails?

**Comment by stevekuznetsov** [comment]
If we're grabbing the commit message,  we should be using formatting specifiers with `But log`: `--pretty=%s`  or `%b`, `%B`, etc. Not grabbing output from human- readable commands like `got show`.

**Comment by lbilger** [comment]
@juanvallejo Unfortunately, the server running git 1.7.10.4 is our company's Jenkins server and I can't install a newer oc version on this server. The build fails when the diff gets very long, for example if I rename/move several long files.

The only error message we get is something like this:
```
Uploading directory "target/oc_deploy" as binary input for the build ...
Error from server: cannot upload file to build [build-name]-66 with status Failed
```

Also, if the build passes, we see the diff in the spec/revision/git/message of the Build.

By now, we have worked around this by putting a shell script called ```git``` on the path of the jenkins server that calls the real git but swaps ```-s``` for ```--quiet```.

**Comment by juanvallejo** [comment]
@lbilger thanks, PR opened to address this issue [here](https://github.com/openshift/origin/pull/15334)
