### ISSUE TITLE
Extended.[k8s.io] Daemon set [Serial] Should adopt or recreate existing pods when creating a RollingUpdate DaemonSet with matching or mismatching templateGeneration

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14129]
```
/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/daemon_set.go:401
Expected
    <int>: 0
to be >
    <int>: 0
/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/daemon_set.go:445
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1312/testReport/junit/(root)/Extended/_k8s_io__Daemon_set__Serial__Should_adopt_or_recreate_existing_pods_when_creating_a_RollingUpdate_DaemonSet_with_matching_or_mismatching_templateGeneration/

**Comment by bparees** [comment]
(and i have no idea why it failed when it expected "0" to be "0")

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/701/

**Comment by derekwaynecarr** [comment]
upstream flake:
https://github.com/kubernetes/kubernetes/issues/42908

claimed fix:
https://github.com/kubernetes/kubernetes/pull/42925

the referenced fix is in origin, so it must be upset for another reason.

**Comment by derekwaynecarr** [comment]
@marun -- can you help track this down further?

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1257/consoleFull#-127006950458b6e51eb7608a5981914356

**Comment by smarterclayton** [comment]
I think this is also in part https://github.com/kubernetes/kubernetes/issues/50586
