### ISSUE TITLE
oadm policy commands should print a message after success

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#14137]
@mfojtik spotted that SCC-related command like `oadm policy add-scc-to-user` works silently and show nothing to the user after successful execution. For the consistency we may show something like this:
```console
$ oadm policy add-scc-to-user anyuid test-user
securitycontextconstraints "anyuid" modified
```

@deads2k @fabianofranz WDYT?

**Comment by mfojtik** [comment]
I think this will improve user experience greatly.

**Comment by deads2k** [comment]
Do we do anything like that for the `add-role-to-user` commands?

**Comment by php-coder** [comment]
Yes, we [do](https://github.com/openshift/origin/blob/2628c775ad4f7469490fe55a7763ab02d732be5f/pkg/cmd/admin/policy/modify_roles.go#L434-L452). But here it's a bit different because we aren't create a new resource but instead modifying existing one.

**Comment by deads2k** [comment]
> Yes, we do. But here it's a bit different because we aren't create a new resource but instead modifying existing one.

Those commands don't make new resources if they don't have to.

**Comment by fabianofranz** [comment]
sgtm

**Comment by php-coder** [comment]
Looks like it was fixed:

```console
$ oc adm policy add-scc-to-user anyuid test-user
scc "anyuid" added to: ["test-user"]
$ oc adm policy remove-scc-from-user anyuid test-user
scc "anyuid" removed from: ["test-user"]
```
The same for add-scc-to-group, remove-scc-from-group, add-role-to-user, remove-role-from-user, add-role-to-group, remove-role-from-group, 
add-cluster-role-to-user, remove-cluster-role-from-group, add-cluster-role-to-group, remove-cluster-role-from-user.
