### ISSUE TITLE
need oadm migrate tool to check for parity between origin authorization and rbac

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#14139]
In order to switch between openshift authorization and RBAC rules, we need to ensure parity.  The controllers are in place https://github.com/openshift/origin/pull/14064, but we need to check to make sure everything has actually succeeded before switching.

@liggitt Also, we need to have a plan for communicating the change to customers, since their mutations are going to be stomped by the reverse controller we build for the migration: RBAC to origin stomp.

**Comment by deads2k** [comment]
> @deads2k wouldn't we technically need this for 3.6 since customers need to run it before upgrading to 3.7?

We have the controller to keep things in sync before an upgrade.  This is the final check.

**Comment by enj** [comment]
@sdodson I will try to get this sorted for 3.6.

**Comment by enj** [comment]
@sdodson we need to sync today as #14429 is merged now.
