### ISSUE TITLE
create ownerrefs for resources that used to be reaped.

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#14133]
We can turn GC on by default for our resources, but we need a way to establish links for...

 - [x] rc to dc
 - [x] pod to rc
 - [ ] rolebinding to role
 - [ ] oathclientauthorizations to users
 - [ ] pod to build
 - [x] build to bc

Since a connection can reasonably be disconnected, I don't think we want to use a controller to establish the links.  We could use `oadm migrate` to set the initial links and controller driven links are easy to get right as we move forward, but links like rolebindings to roles are harder to establish.

Some relationships cannot be GC'ed since they are updated not deleted: removing users from rolebindings as a for instance.  This means that some form of reapers need to stick around.

**Comment by pweil-** [comment]
@mfojtik added cross link to your [Trello card](https://trello.com/c/QZNtFysL)

**Comment by kargakis** [comment]
pod to rc should already be handled by the upstream rc controller.

**Comment by kargakis** [comment]
bc to build is supposedly already done

**Comment by mfojtik** [comment]
@enj @deads2k i guess we want to handle the rolebinding to role and oathclientauthorizations to users by oadm migrate? @enj something you want to look at? (assuming you are familiar with the oadm migrate code ;-)

**Comment by tnozicka** [comment]
rc to dc just merged https://github.com/openshift/origin/pull/14322

**Comment by mfojtik** [comment]
@bparees do we have build -> pod ownerRef? I assume we do?

**Comment by bparees** [comment]
> @bparees do we have build -> pod ownerRef? I assume we do?

not yet.  currently the build controller deletes the pod when the build is deleted.  But this PR is adding them:
https://github.com/openshift/origin/pull/14289/files#diff-037e7619679bf13f352b3eefec32d9ecR222

**Comment by soltysh** [comment]
This should be solved by now.
/close
