### ISSUE TITLE
oc logs -f, oc start-builds --follow, hang 

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#14148]
Breaking out from https://github.com/openshift/origin/issues/13984

See comments for discussion between @ncdc and I, as well as a thread dump of a hang seen locally on my laptop (happens consistently there, but intermittently in the devexp overnight build exteneded tests), origin commit levels, etc.:

1. https://github.com/openshift/origin/issues/13984#issuecomment-299345281
2. https://github.com/openshift/origin/issues/13984#issuecomment-299345497
3. https://github.com/openshift/origin/issues/13984#issuecomment-299505360
4. https://github.com/openshift/origin/issues/13984#issuecomment-299514049
5. https://github.com/openshift/origin/issues/13984#issuecomment-299524626
6. https://github.com/openshift/origin/issues/13984#issuecomment-299526537
7. https://github.com/openshift/origin/issues/13984#issuecomment-299555875

@openshift/devex FYI - RE: recent flake discussion during team scrum

**Comment by liggitt** [comment]
has this been seen upstream?

**Comment by ncdc** [comment]
I haven't seen any reports of it, other than one bug that only happens with
the json-file docker log driver.

**Comment by gabemontero** [comment]
I did have one update I had been meaning to post ... I ran the latest `oc` client against 3.6 alpha 1 (i.e. pre-3.6 rebase) and did *NOT* see the issue ... the `oc logs ... --follow` terminated.

**Comment by liggitt** [comment]
yeah, seems extremely likely to be CRI-related

**Comment by bparees** [comment]
@liggitt can you name a better owner? clearly not @csrwng :)

**Comment by ncdc** [comment]
I can take this, but I'll need the simplest, most reliable reproducer.

**Comment by gabemontero** [comment]
@ncdc and I have talked on IRC ... the example was posted at https://github.com/openshift/origin/issues/13984#issuecomment-299505360

**Comment by gabemontero** [comment]
@ncdc here are the `oc get --raw /debug/pprof/goroutine?debug=2` and `docker info` results after producing the hang 
[data.zip](https://github.com/openshift/origin/files/1032559/data.zip)

**Comment by gabemontero** [comment]
At least for me running locally, turns out I was running with json-file, and was unaware.  Switching to journald, I no longer see this on my laptop.

In which case, backporting https://github.com/kubernetes/kubernetes/pull/44406 should address.

Per discussion with @ncdc, any intermittent versions of this being seen on the CI systems during extended test are probably something different.  

That said, I'll add the two diagnostics noted above to our debug of that issue.

thanks @ncdc

**Comment by gabemontero** [comment]
verified at origin commit level 5a191207dc380c9b7271958b356cc5e3fc951be6

**Comment by ncdc** [comment]
@gabemontero did this get resolved?

**Comment by gabemontero** [comment]
On Tue, May 30, 2017 at 9:55 AM, Andy Goldstein <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> did this get resolved?
>
@ncdc yes already closed out the issue, noting the commit level I verified
your fix with

**Comment by ncdc** [comment]
@gabemontero I thought following logs was hanging in the CI jobs too?

**Comment by gabemontero** [comment]
On Tue, May 30, 2017 at 10:12 AM Andy Goldstein <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> I thought following logs
> was hanging in the CI jobs too?
>
only very intermittently and most likely without the json log driver;
whereas I saw this consistently from the command line (which lead to my
opening this issue) and the json log driver was in play

My take is closing this issue out for the consistent command line json log
driver flavor;  I am going to update my debug PR for the CI jobs with
docker info and master stack dump invocations added to the failure debug;
if another instance arises we will take the debug data and open a new issue
as needed
