### ISSUE TITLE
Binary build fails with /tmp/docker-build186920625/Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#14141]
My binary build fails with this error in the log`/tmp/docker-build186920625/Dockerfile: no such file or directory`

##### Version
```
$ oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce

1. `oc new-build --binary=true --name=test-front-react --image-stream=nginx-openshift:latest`

2. `oc start-build test-front-react --from-dir=build --wait=true`

##### Current Result

Uploading directory "build" as binary input for the build ...
build "test-front-react-1" started
error: The build test-dev/test-front-react-1 status is "Failed"```

##### Additional Information
```
$ oc logs -f bc/test-front-react
Receiving source from STDIN as archive ...
error: build error: open /tmp/docker-build186920625/Dockerfile: no such file or directory
```

**Comment by php-coder** [comment]
@bparees

**Comment by bparees** [comment]
@YannMoisan Is your buildconfig strategy docker?  Is there a Dockerfile in your "build" dir?

**Comment by YannMoisan** [comment]
The issue was due to the automatic strategy discovery : _docker_ instead of _source_.
So i've just added `--strategy=source` to fix.

I was mislead by this example : https://github.com/OpenShiftDemos/openshift-cd-demo/blob/ocp-3.4/cicd-template.yaml#L107

**Comment by bparees** [comment]
cool.
