### ISSUE TITLE
Is there a k8s 1.6 based release of origin?

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#14146]
General question: 
Is there a k8s 1.6 based release of origin?
I have tried both recent alpha version of origin and they does not seem to have k8s 1.6.
i'm specifically looking for  RBAC compatibility  of k8s on openshift

**Comment by enj** [comment]
What do you mean by RBAC compatibility?  Master is based on 1.6.1.

**Comment by jocelynthode** [comment]
master is indeed based on 1.6.1, but there are no release and no rpms available that make use of k8s 1.6. Is there a plan for this in the near future ?

**Comment by stevekuznetsov** [comment]
We aim to get the CentOS PaaS SIG RPM publishing to more closely track master. If you're looking for pre-release Origin RPMs, that's where they'll be. I can't give a more specific date other than "soon," unfortunately.

**Comment by pweil-** [comment]
As @stevekuznetsov says, 1.6 is still in development and has not yet been released (or alpha released).  Master is the closest thing available right now if you would like to develop or test out 1.6 binaries via a local build.
