### ISSUE TITLE
oc rsh <podname> results in "http: server gave HTTP response to HTTPS client"

### ISSUE THREAD

**Issue by kilimandjango** [openshift/origin#14160]
I have a fresh installation of openshift origin v1.5.0 running on 2 virtual machines based on REHL:

$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)

The installation was done with ansible. 

##### Version
$ oc version
oc v1.5.0
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
$ oc get pods -o wide

NAME                       READY     STATUS    RESTARTS   AGE       IP              NODE
docker-registry-1-408lp    1/1       Running   4          5h        10.129.0.110    xxx
registry-console-1-zc4c5   1/1       Running   1          2h        10.128.0.78     xxx
router-1-ql61m             1/1       Running   12         2d        10.64.112.135   xxx

$ oc rsh docker-registry-1-408lp

`error: error sending request: Post https://xxx:8443/api/v1/namespaces/default/pods/docker-registry-1-408lp/exec?command=%2Fbin%2Fsh&command=-c&command=TERM%3D%22xterm%22+%2Fbin%2Fsh&container=registry&container=registry&stdin=true&stdout=true&tty=true: http: server gave HTTP response to HTTPS client
root@xxx(xxx) [/home/ansible]`
 

--> ping on the node ip is working
--> curl is not working!

##### Current Result
oc rsh is currently not working (also curl is not working).
This results in health checks not working which prevents pods from being started.

##### Expected Result
oc rsh and curl should be working

##### Additional Information
$ oadm diagnostics is showing this error:

`ERROR: [DNet2011 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:166]
       Deleting remote logdir "/tmp/openshift/nodes/flexlnx023.eil.risnet.de" on node "xxx" failed: error sending request: Post https://xxx:8443/api/v1/namespaces/network-diag-ns-3lgz4/pods/network-diag-pod-1nrjk/exec?command=chroot&command=%2Fhost&command=sh&command=-c&command=shopt+-s+dotglob+%26%26+rm+-rf+%2Ftmp%2Fopenshift%2Fnodes%2Fflexlnx023.eil.risnet.de&container=network-diag-pod-1nrjk&container=network-diag-pod-1nrjk&stderr=true&stdout=true: http: server gave HTTP response to HTTPS client,`

**Comment by pweil-** [comment]
@jwhonce looks like both errors are through the exec command.  Possibly a missing `--insecure-registry`?

@mfojtik @fabianofranz @legionus FYI

**Comment by jwhonce** [comment]
@kilimandjango What are the values of ADD_REGISTRY and INSECURE_REGISTRY in /etc/sysconfig/docker?  Thanks

**Comment by kilimandjango** [comment]
Thanks for your help!

Both values are standard:
ADD_REGISTRY='registry.access.redhat.com'
INSECURE_REGISTRY='--insecure-registry '--insecure-registry 172.30.0.0/16

It is really strange. The playbook is standard and I never met this error before (neither OCP or Origin).

The problem with curl seemed to be a Proxy setting. So the following command is working:
$ curl -kv <ipaddress>:<portnumber> --noproxy '*'

**Comment by debianmaster** [comment]
`INSECURE_REGISTRY='--insecure-registry '--insecure-registry 172.30.0.0/16`  this seems incorrect to me.

**Comment by kilimandjango** [comment]
> INSECURE_REGISTRY='--insecure-registry '--insecure-registry 172.30.0.0/16 this seems incorrect to me.

Srry that was a copy paste error...

`INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'`

This was the correct entry.

In the meantime I downgraded to Openshift Origin v1.4.1 and this is working without any problems. 
When there is time left I will try to upgrade to Origin v1.5 the following days.

Thank you for all the support!
