### ISSUE TITLE
Add template service broker tests to conformance tests

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#14163]
Requires update to test installation playbooks to configure TSB

**Comment by jim-minter** [comment]
Subsequently, TSB e2e test should ensure deprovision removes all objects

**Comment by bparees** [comment]
And delete the old template tests extended job.

**Comment by jim-minter** [comment]
covered by #15966 and https://trello.com/c/eGPZllFr/1314-template-service-broker-dont-return-from-deprovision-until-all-objects-gone
