### ISSUE TITLE
[RFE] internal skydns should be able to serve ootb routing, infra

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1416]
Currently for beta testing we are using a dnsmasq configuration that looks like the following:

/etc/hosts has FQDNs for ose3-master.example.com and ose3-node1/2.example.com
wildcard *.cloudapps.example.com pointing at ip for master, where the router is guaranteed to be

What would be extremely useful is if the integrated SkyDNS on the master could do the same thing:

1) serve DNS resolution for masters and nodes out of /etc/hosts
2) automatically serve the correct ip for a router on a specific domain (eg: cloudapps.example.com)

**Comment by smarterclayton** [comment]
We need to figure out whether we'll get in an infinite loop if we have the master in its own /etc/resolv.conf (because skydns looks up /etc/resolv.conf to find other name servers), and also whether we can easily set up a wildcard domain with a simple change to etcd (should be able to set up wildcard forwarding from external to the service IP or the host of the router).

**Comment by smarterclayton** [comment]
I tried this on a Mac with the following config:

```
nameserver <localopenshiftaddress>
nameserver <upstream>
```

I then verified dig was able to resolve both - but I don't know whether that was causing broken recursive queries.  It *seemed* like it was ok.  I'd recommend going ahead and trying this from the master in a normal configuration, and opening an issue if you hit something.  At worst, we can omit the current host IP from the resolver list as a fix.

**Comment by smarterclayton** [comment]
Note that if you're not running a kube proxy locally service IPs won't resolve.

**Comment by thoraxe** [comment]
So there was lots of talk about open resolvers and other things... I'm not sure that we should leave this issue open because I think solving it potentially represents a security issue...

**Comment by smarterclayton** [comment]
Resolving is disabled, although we have anecdotal reports that disabling it made certain things worse.  But in the event it was open externally it would only be answering a delegated domain so I don't consider that a security issue.

----- Original Message -----

**Comment by pweil-** [comment]
@sdodson I believe that you had a demo of using dns on the node as part of https://github.com/openshift/openshift-ansible/pull/4292.  I don't think this does anything for the routes though so this is partially addressed

**Comment by sdodson** [comment]
@thoraxe Do you want this just for hosts that are part of the cluster or do you want it for external hosts.

If you only care about internal hosts the openshift_node_dnsmasq_additional_config_file can be set to a path of a local dnsmasq .conf file which gets copied to all nodes and that could specify the wildcard you're asking for but you'd need to know the ip address of the router.

If we want skydns to do this it'd have to create records for routes that point at the router.

**Comment by thoraxe** [comment]
@sdodson I didn't realize we could add additional config to the installer, too.

Definitely can just close this.
