### ISSUE TITLE
SCC admission uses a client to do a live namespace lookup instead of a cache

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#14175]
It looks like this code down here https://github.com/openshift/origin/blob/master/pkg/security/admission/admission.go#L100 uses a live namespace lookup for admitting pods.  This surprised me.

**Comment by pweil-** [comment]
@deads2k that's the namespace from the admission attributes, why is that incorrect?  

Or are you saying that the code it is calling should be caching the namsepaces to get the preallocated values?

**Comment by deads2k** [comment]
> Or are you saying that the code it is calling should be caching the namsepaces to get the preallocated values?

The default across the project is to use a cache unless extraordinary circumstances prevent it.  I don't think the deletion and recreation race is enough to warrant this since we don't prevent such a race in the authorizer.

**Comment by pweil-** [comment]
discussed, it is the shared code that this is calling (where the pre-allocated values are looked up) that is the issue here not the use of the ns from the admission object.  @php-coder that's where a cache lookup is desired.
