### ISSUE TITLE
Extended.[k8s.io] Projected should be consumable from pods in volume with mappings [Conformance] [Volume]

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14176]
```
/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/projected.go:56
Expected error:
    <*errors.errorString | 0xc42183c840>: {
        s: "expected pod \"pod-projected-secrets-6c209410-3730-11e7-ac42-0e29f564e1d8\" success: <nil>",
    }
    expected pod "pod-projected-secrets-6c209410-3730-11e7-ac42-0e29f564e1d8" success: <nil>
not to have occurred
/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:2183
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/1997/

**Comment by bparees** [comment]
@derekwaynecarr wasn't sure if this should be you or @childsb for storage, please reassign as needed.

**Comment by derekwaynecarr** [comment]
@jpeeler -- can you try to triage further?  has upstream kube encountered similar flakes?  are their associated fixes we should have picked?

**Comment by jpeeler** [comment]
@derekwaynecarr I don't know of any upstream flakes involving a projected volume currently. The only time I recall projected volume flakes occurring was several months ago (https://github.com/kubernetes/kubernetes/issues/42154) and the fix is already in master.

**Comment by jpeeler** [comment]
I think projection issues were solved here: https://github.com/kubernetes/kubernetes/pull/59873. So I'm closing this.
