### ISSUE TITLE
Cannot create storage

### ISSUE THREAD

**Issue by romantomchak** [openshift/origin#14184]
Hello,

after fresh installation, when I'm trying to create new storage from web console I'm always gets the error message: `no persistent volumes available for this claim and no storage class is set`, reason: `Failed binding`

##### Version
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
etcd 3.1.0

##### Steps To Reproduce
1. Go to the web console `Storage section`
2. Push on `Create Storage` button
3. Create storage.

The generated YAML config is 
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storagename
  namespace: gitlab-infrastructure
  selfLink: /api/v1/namespaces/example/persistentvolumeclaims/storagename
  uid: 2827819d-389a-11e7-95f3-4e4829be6605
  resourceVersion: '6296'
  creationTimestamp: '2017-05-14T11:40:40Z'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status:
  phase: Pending
```

##### Current Result
This storage always has `Pending` status and in Monitoring->Events I receive error message  `no persistent volumes available for this claim and no storage class is set`. 

Please help me what am I doing wrong? I am a newcomer in Openshift.

**Comment by ephillipe** [comment]
I am having same issue.

Anyone can help us?

**Comment by Moep90** [comment]
Same here...

**Comment by tapas4java** [comment]
Any update here? Facing same issue in a v3.6 cluster

**Comment by tapas4java** [comment]
@romantomchak Did you get a chance to resolve this issue??

**Comment by debianmaster** [comment]
Looks like cluster does not have any persistent volumes.  You should create PVs first.

**Comment by tapas4java** [comment]
Thanks @debianmaster 

After adding `openshift_cloudprovider_kind=gce` in inventory/hosts file did the trick. Now Openshift is able to create PV dynamically on GCE without any extra config.

**Comment by debianmaster** [comment]
Awesome. Good luck.

**Comment by lauer3912** [comment]
Cannot create persistent volume claim "mysql". persistentvolumeclaims "mysql" is forbidden: exceeded quota: 6170702e726f6d616e79736f667440676d61696c2e636f6d-noncompute, requested: requests.storage=1Gi, used: requests.storage=0, limited: requests.storage=0.

**Comment by tapas4java** [comment]
@lauer3912 You have to increase your Quota limit by adding payment method to Google account

**Comment by lauer3912** [comment]
@tapas4java Where to increase the quota?  I can not find ah

**Comment by tapas4java** [comment]
[Here](https://cloud.google.com/compute/quotas)

**Comment by cars10** [comment]
@tapas4java where exactly can i set that config? I experience the same issue as @romantomchak , cannot create pvc's.

**Comment by tapas4java** [comment]
Hope you are following [Jennings's Video](https://www.google.com.sg/url?sa=t&rct=j&q=&esrc=s&source=video&cd=1&cad=rja&uact=8&ved=0ahUKEwj6sMfYhunWAhUDLpQKHYIZDcIQtwIIJjAA&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D1Lo10hLC2XE&usg=AOvVaw32zhCjdYuLlqXuyRZR1i-0) ??

I have added `openshift_cloudprovider_kind=gce` to `inventory/hosts` file

**Comment by cars10** [comment]
I am *not* on GCE. I wanted to create a PVC locally on my mashine.

**Comment by xiaods** [comment]
any process on it.

**Comment by xiaods** [comment]
for developer purpose, we can use hostPath provisioner to resolve it.

https://github.com/kubernetes-incubator/external-storage/blob/master/docs/demo/hostpath-provisioner/README.md

**Comment by yves-vogl** [comment]
Hi Folks,

afaik you cannot use persistent volumes when you haven't configured an appropriate provider before.

**Comment by japplewhite** [comment]
same here

**Comment by rohilshah95** [comment]
anyone found a fix for this?

**Comment by debianmaster** [comment]
@rohilshah95  @japplewhite   do you have persistent storage configure to openshift?  else you will see this issue.   Also make sure you have a default storageclass 

`oc get pv`     or .  `oc get storageclass` .  should show you

**Comment by rushins** [comment]
i hit the same issue. we have openshift 3.9 with kubernetes 1.9 ? we dont have any GCE as this cluster is on-premise ...do i have to create NFS PV first to consume PVC ? i thought PV should work local disk as well.

can someone help what is the solution.

**Comment by debianmaster** [comment]
@rushins
 you should have a PV first or a storage class to create a PVC.

use    oc get pv .       and    oc get storageclass       to see if you
have any

**Comment by rushins** [comment]
so as stated before "do i have to create NFS PV first to consume PVC " i created PV and rest is fine, however i was under impression that Openshift Contianer Platform will allow to use localhost path based disk as PV ? if this is possible in redhat openshift container platform? as other kubernetes without redhat openshift is doable with this way using localhost path LVM devices. ?
