### ISSUE TITLE
oc rsh timeout does not appear to work

### ISSUE THREAD

**Issue by cammil** [openshift/origin#14188]
oc rsh timeout does not appear to work

##### Version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://****
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. `oc rsh --shell=/bin/bash --timeout=10000 $OC_POD`

##### Current Result
Connection drops / times out after a few seconds

##### Expected Result
Connection to drop / time out only after specified time

##### Additional Information
NA

**Comment by juanvallejo** [comment]
cc @fabianofranz

**Comment by juanvallejo** [comment]
Hi @cammil is this issue still happening?
The `--timeout` option for commands that rely on streaming connections, such as `rsh`, is meant to apply only when fetching the desired pod from the server. It could be likely that the node is the one dropping the connection in this case, after you have fetched the desired pod, and have established a streaming connection to it. You might need to adjust the `streaming-connection-idle-timeout` in your node-config to be a higher value. Related upstream issue: https://github.com/kubernetes/kubernetes/issues/19231

Please reopen this issue, if it is still happening, or is not able to be resolved by editing your `node-config.yaml` as mentioned in the above steps.
