### ISSUE TITLE
explicit environment variables for buildConfig and deploymentConfig: Error mismatch! Expected <nil>, got no match for "centos/ruby-22-centos7"

### ISSUE THREAD

**Issue by dmage** [openshift/origin#14187]
github.com/openshift/origin/test/integration.TestNewAppBuildConfigEnvVarsAndSecrets (from github.com_openshift_origin_test_integration)
```
--- FAIL: TestNewAppBuildConfigEnvVarsAndSecrets (6.31s)
	newapp_test.go:1761: explicit environment variables for buildConfig and deploymentConfig: Error mismatch! Expected <nil>, got no match for "centos/ruby-22-centos7"
```
Seen there: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1394/

**Comment by mfojtik** [comment]
o dockerhub flake?

**Comment by bparees** [comment]
sure looks that way (especially since two newapp tests failed to find that same image in this run) but we should at least see if we can add some better debug output to prove this in future failures.

**Comment by bparees** [comment]
(I'm dropping to p2 on the assumption it's a dockerhub flake which means we can't really fix it, but we can raise it back up if evidence points in another direction).

**Comment by bparees** [comment]
closing as dockerhub flake and not recurring.
