### ISSUE TITLE
Failure to build unit tests on mac

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#14181]
```
hack/test-go.sh
[INFO] [CLEANUP] Cleaning up temporary directories
# github.com/openshift/origin/vendor/github.com/mtrmac/gpgme
/Users/clayton/projects/origin/src/github.com/openshift/origin/vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: 'gpgme.h' file not found
 #include <gpgme.h>
          ^
1 error generated.
```

**Comment by smarterclayton** [comment]
Container's image uses this for gpgme.

```
// +build !containers_image_openpgp
```

That should probably be reversed - callers should opt in to gpgme, rather than opt out.  It also needs to be guarded for cgo, windows, or mac.

**Comment by smarterclayton** [comment]
For now, it should be changed

```
openpgp
// +build containers_image_openpgp !cgo !linux

gpgme
// +build !containers_image_openpgp,cgo,linux
```

**Comment by mfojtik** [comment]
@mtrmac FYI.

**Comment by mtrmac** [comment]
@mfojtik Shouldn’t  https://github.com/openshift/origin/pull/13585/files#diff-e9de5dd9671aca3eaf70ce14cf4cc369 / https://github.com/openshift/origin/pull/13585/files#diff-9283775b0feecc10455ec28bd08983b0 already be setting the configuration? Or perhaps `hack/test-go.sh` needs a similar treatment?

`!linux` would AFAICT be incorrect; reportedly `brew install gpgme` does allow building that package against that on macOS. (To be clear, I’m not at all saying that `brew install gpgme` should be a prerequisite for OpenShift.)

**Comment by mfojtik** [comment]
@mtrmac people don't have to use `test-go.sh` to run tests, but just `go test`... in that case running without that tag will cause the test compilation to fail. It should not by default.

**Comment by smarterclayton** [comment]
Requiring C libraries to be present when doing native Go compile on
platforms is unusual, and annoying in general.  I'd suggest all
"unusual" paths be opt-in - if we aren't 100% sure libgpgme isn't
easily available and correct on a platform, make it opt in.  Ie have a
specific tag to allow opt in.

We can carry an upstream patch, but generally most users are going to
want opengpg, and sometimes libgpg

**Comment by mfojtik** [comment]
@smarterclayton @mtrmac i guess we want to fix this upstream, right? we don't want to carry a patch in origin.

**Comment by mtrmac** [comment]
Which “upstream” are we talking about here? (“carry an upstream patch” vs. “carry a patch in origin”, is there a difference? And "fix this upstream”?)

In my opinion, the golang `openpgp` implementation is more risky than `gpgme` calling into the original/“proven” `gnupg` code with its almost 20-year history. Feel free to call that conservatism, appeal to authority, cargo culting, whatever; I may be knowledgeable just enough to detect obviously amateurish and unsafe crypto, I am definitely not qualified enough to make a substantial opinion on the specifics of these two implementations. (To be fair, I also have no reason to think the `openpgp` implementation is in any specific way unsafe—just my best guess is that the risk is higher.)

In principle, we need to prioritize user security over programmer convenience—after all, programmers are able to write tools which make their lives simpler, but users must rely on programmers to make the software secure.

Then there’s the matter of the `openpgp` backend not supporting signing.

So, overall, AFAICT it makes much more sense for containers/image to default to `gpgme`. Sure, we should make that as easy as possible to use, or to opt out for projects which know better.

---

Now, sure, a Golang-only implementation can be a valuable trait, and it may well make sense for OpenShift to value that over some slight difference in risk of vulnerabilities. But that does not make that judgment call directly applicable to the containers/image defaults.

**Comment by mfojtik** [comment]
Origin probably never picks the gpgme dep as we need to cross build for
different platforms and having CGO dependency seems unreasonable for the
feature we use the containers/image library for in near future as it makes
the usage of the oc much harder since the users will have to install the
gpgme libs.

I guess it should be the best interest of containers/image to allow
different implementations with implications for the user to pick the
security he is willing to trust.

@smarterclayton fyi.

**Comment by smarterclayton** [comment]
Another point - I'd rather never include cgo code unless absolutely proven
that we need it, because I'd rather not even have to consider memory faults
as a possible attack vector, especially in code that accepts input from
untrusted users.

**Comment by runcom** [comment]
> I guess it should be the best interest of containers/image to allow
> different implementations with implications for the user to pick the
> security he is willing to trust.

@mtrmac I agree with the others here (not about security, but about the library) - containers/image is merely a library and as such it must be configurable - your point on security is certainly super valid but if a linux specific dependency is preventing other (huge) projects like Origin to use our library, we are mostly failing to provide a good library. We must deal with this as Golang is cross-platform and people bid on this. My take is: default to golang opengpg in the library (skopeo can always build with gpgme). Go opengpg can be secured in the future with signing features also, but right now, gpgme is actually blocking people on other platform to _easily_ use our library and I'd rather not do this.

**Comment by mfojtik** [comment]
Closing as this is working now.
