### ISSUE TITLE
Decide how to vendor external repositories

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#14199]
We have a number of incubator repositories that we are going to need to vendor into origin in the near future:

- service catalog
- cluster capacity
- metrics

At least two of these repositories are built using the kubernetes API machinery, which is basically guaranteed to have skew between the versions used in origin and the versions used in the incubator repos.

We recently talked between myself, @smarterclayton, @deads2k and @derekwaynecarr about a vendoring scheme like so:

    └── cmd                     
        └── service-catalog/go/src/github.com/kubernetes-incubator/service-catalog
            ├── apiserver
            ├── controller-manager
            └── vendor

...where the external repo has its own binaries built under the top-level `cmd` directory, with a distinct per-external-repo vendor directory.

Does that make sense to everyone?

cc @jpeeler @eparis

**Comment by eparis** [comment]
If we are doing per binary vendoring, what's the point of vendoring here? Just because our testing sucks if we don't vendor?

**Comment by deads2k** [comment]
> Just because our testing sucks if we don't vendor?

That's what I got out of the conversation.  Testing and tooling doesn't handle multiple repos.

**Comment by deads2k** [comment]
> Does that make sense to everyone?

I think you may end up needing to put an entirely separate gopath down there, but the idea is what we talked about.  Things that should actually be in their own repo end up in the main repo with a separate GOPATH such that we don't interact and *nothing* else is allowed to depend on them.

Actually, that should included in the work.  A `go list` based verify script to ensure we never depend on these since they're unvendorable.

**Comment by eparis** [comment]
I'm ok with such vendoring IFF there is NO pointing back and forth.

What do we do about something like federation that is (eventually) going to want to care about openshift resources and be it's own vendored magic...

**Comment by deads2k** [comment]
> What do we do about something like federation that is (eventually) going to want to care about openshift resources and be it's own vendored magic...

I think you really have to hope that federation becomes generic.  It needs to operate upon unknown resources in order to properly support version skew anyway.

**Comment by pmorie** [comment]
@deads2k 

> separate GOPATH 

Is the distinction that you would want `cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/...` rather than what I wrote above?

**Comment by deads2k** [comment]
> Is the distinction that you would want cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/... rather than what I wrote above?

I think that keeps you from having to rewrite any paths, but if there's a better way to avoid path rewriting to make your patches easier to maintain while keeping our vendor paths completely distinct, I'm fine with that too.

**Comment by pmorie** [comment]
@deads2k ack.

**Comment by pmorie** [comment]
Updated description - I wonder at this point if we should just plunk the entire repo down at `cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog`.  Thoughts?

**Comment by deads2k** [comment]
> Updated description - I wonder at this point if we should just plunk the entire repo down at cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog. Thoughts?

Is there some git magic to make picks easier for you?  I remember @csrwng used some sub-repo thing somewhere for something.  I don't remember exactly what it does.

**Comment by pmorie** [comment]
Subrepo and subtree both have pretty major drawbacks IMO

**Comment by csrwng** [comment]
@deads2k I don't remember using a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules), but I would vote for not adding one to origin :) They're a pain to deal with.

**Comment by pmorie** [comment]
...and subtree is much, much worse.

**Comment by smarterclayton** [comment]
And to be clear, any project that we can eventually split out once we have common Go tooling and unified build stuff (which @stevekuznetsov and I have been planning, but keep getting distracted by other requirements from teams like special merge tags and build flakes and things no one cares about) should be as much as possible a lift and shift "git filter-branch ...; cp -R . other".  So optimizing for something under `cmd/NAME/` that can look like another repo is good.

**Comment by derekwaynecarr** [comment]
this approach looks fine to me given current constraints.

i don't think this impacts federation just yet as federation is still in the kube tree.

@aveshagarwal -- can you update your pr for cluster capacity as outlined above?

**Comment by stevekuznetsov** [comment]
Are we not considering investing developer time into making the tooling more generic? The big need for these new repos is build scripts, right? How complicated and different are those builds from Origin? Can we vendor the tooling instead of the code and have these components in separate repos? How will these components be tested? If they are in separate repos at any point do we expect strong coupling with Origin?

**Comment by stevekuznetsov** [comment]
For what it's worth I've found submodules to be pretty effective. I think they gained a lot of detractors at first but they've matured since.

**Comment by jpeeler** [comment]
Given that service-catalog and cluster-capacity have been vendored for several months now, I think it's safe to close this.
