### ISSUE TITLE
Build containers cannot resolve service hostnames

### ISSUE THREAD

**Issue by alikhajeh1** [openshift/origin#14196]
The `/etc/resolv.conf` of build containers isn't showing the `dnsIP` configured in the node config (normal pod containers do show this). This means that scripts in the postCommit of buildConfigs cannot use the service.project.svc hostname to connect to a service and must use the service Cluster IP instead.

##### Version
```
Server https://XXX
openshift v1.5.0
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. Deploy the built-in MongoDB template and note the connection string.
2. Deploy a test app that has a postCommit script that tries to connect to MongoDB using the service hostname and notice the `getaddrinfo: Name does not resolve` errors.
3. Switch the test app's postCommit script to use the cluster IP and notice it connects fine.

##### Current Result
The build logs show that the build cannot connect using the service hostname:
```
D, [2017-05-15T15:15:21.646020 #6] DEBUG -- : MONGODB | Server mongodb:27017 initializing.
D, [2017-05-15T15:15:21.647393 #6] DEBUG -- : MONGODB | getaddrinfo: Name does not resolve
```

##### Expected Result
The build should be able to connect to services using their hostname.

**Comment by bparees** [comment]
This is a known limitation of the fact that the build spawns a secondary container directly on the host, not managed by openshift.  This means the /etc/resolv.conf available to that secondary container will not include cluster DNS information.  The solution/workaround is to add the cluster DNS ip to your node's /etc/resolv.conf, as that is the DNS information that will be provided to the secondary container.

I think we might be able to fix this by reading the /etc/resolv.conf from the build pod and using that information to populate the HostConfig for the secondary container when it is launched.

**Comment by bparees** [comment]
Moving this to our trello backlog here: https://trello.com/c/3Mb8EIh0/1256-use-pod-dns-for-build-containers

**Comment by bparees** [comment]
also tracking as a bug here: 
https://bugzilla.redhat.com/show_bug.cgi?id=1471691
