### ISSUE TITLE
Remove conversions from extended deployment test

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14218]
https://github.com/openshift/origin/blob/b96ef9a8617746640d9429f698f1d44f2dcd86fb/test/extended/deployments/deployments.go#L851-L856

**Comment by mfojtik** [comment]
Bumping to P3. This will require rewriting the deployment controllers to use versioned client (we have to do it at some point, but not high prio for 3.6)

**Comment by kargakis** [comment]
Not sure this is important enough to track.
