### ISSUE TITLE
Unable to mount RWX volume to multiple pods

### ISSUE THREAD

**Issue by golyalpha** [openshift/origin#14224]
##### Steps To Reproduce
Create an RWX volume
Create a PHP webapp (I'm using my fork of SysCrack as the source)
Add storage mount to the deployment controller (mount path: /opt/app-root/src/data)
Deploy
Deploy again (after the initial deployment finishes)

##### Current Result
Second deployment fails on the rolling strategy

##### Expected Result
Second deployment on the rolling strategy will deploy without problems.

##### Additional Information
I have health checks (liveness and readiness) turned on, and have switched from Rolling to Recreate deployment strategy because of this error, it still appears sometimes in the events though.

**Comment by mfojtik** [comment]
@golyalpha can you please provide the error you seeing in events?
