### ISSUE TITLE
LimitRange should create a LimitRange with defaults and ensure pod has those defaults applied.

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#14229]
[Fail] [k8s.io] LimitRange [AfterEach] should create a LimitRange with defaults and ensure pod has those defaults applied. 

May 17 05:35:47.014: INFO: Couldn't delete ns: "e2e-tests-limitrange-ncfbv": namespace e2e-tests-limitrange-ncfbv was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed (&errors.errorString{s:"namespace e2e-tests-limitrange-ncfbv was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed"})

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/674/consoleFull

This is identical to #11094, but that flake appears to have stopped happening immediately after the proposed fix for it was committed, so it must be happening for a different reason now

**Comment by derekwaynecarr** [comment]
i am unable to access the log for when this occurred.  it has not occurred in last month based on links.  reducing to sev 2.  most instances of this flake are due to latency of the watch event being propagated to admission controller.

**Comment by derekwaynecarr** [comment]
although in the snippet, it looks like a namespace deletion took too long.
