### ISSUE TITLE
server/client compatibility issue with deployments resource

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14235]
newer oc client with slightly older server doesn't support extended/v1beta1 deployment objects via bulk mapper (maps them to the wrong resource endpoint)

##### Version
$ oc version
oc v3.6.0-alpha.1+c66c96b-619-dirty
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.1+46942ad
kubernetes v1.5.2+43a9be4

(note that the server is 3.6 alpha1, the client is a bit newer)

##### Steps To Reproduce
1. run oc cluster up to start a server that uses the openshift/origin:v3.6.0-alpha.1 image, and a current oc binary.
2. oc new-app -f https://gist.githubusercontent.com/bparees/cb9f9683bb0cd38dfa5944712a62b4cf/raw/e0d07ea8f7e091d0f8baaaaa3820ff636be1cb75/gistfile1.txt --loglevel=8

The mapper tries to map the extensions/v1beta1 deployment object from the template, into the "apps/v1beta1" groupversion:

I0517 22:51:04.728052   23565 round_trippers.go:383] POST https://127.0.0.1:8443/apis/apps/v1beta1/namespaces/p1/deployments

Which does not exist in this server version:
```
$ curl -k https://localhost:8443/apis/apps/v1beta1{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "apps/v1beta1",
  "resources": [
    {
      "name": "statefulsets",
      "namespaced": true,
      "kind": "StatefulSet"
    },
    {
      "name": "statefulsets/status",
      "namespaced": true,
      "kind": "StatefulSet"
    }
  ]
}
```

##### Current Result
resource cannot be created

##### Expected Result
resource can be created (via the extensions/v1beta1 api endpoint)

##### Additional info
This works fine with a newer server(matching the client level), as expected since the newer server has an apps/v1beta1 deployment resource.

@kargakis @deads2k I was pointed to you guys on this issue.  It's possible it belongs as an upstream issue, let me know if i should open it there.

**Comment by kargakis** [comment]
@soltysh why apps/v1beta1 does not exist in 3.6?

**Comment by kargakis** [comment]
Oh wait a minute
```
kubernetes v1.5.2+43a9be4
```
This is prior to the rebase - @bparees can you try again post-rebase?

**Comment by kargakis** [comment]
Ok, run the provided example, works fine in 
```
oc v3.6.0-alpha.1+a2b1868-621
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.1+a2b1868-621
kubernetes v1.6.1+5115d708d7
$ oc new-app -f https://gist.githubusercontent.com/bparees/cb9f9683bb0cd38dfa5944712a62b4cf/raw/e0d07ea8f7e091d0f8baaaaa3820ff636be1cb75/gistfile1.txt 
--> Deploying template "default/service-catalog" for "https://gist.githubusercontent.com/bparees/cb9f9683bb0cd38dfa5944712a62b4cf/raw/e0d07ea8f7e091d0f8baaaaa3820ff636be1cb75/gistfile1.txt" to project default

     * With parameters:
        * CORS Allowed Origin=localhost
        * Service catalog image tag=canary

--> Creating resources ...
    deployment "apiserver" created
    service "apiserver" created
    deployment "controller-manager" created
    service "controller-manager" created
    clusterrolebinding "template-broker-caller-binding" created
--> Success
    Run 'oc status' to view your app.
$ curl -k https://localhost:8443/apis/apps/v1beta1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "apps/v1beta1",
  "resources": [
    {
      "name": "deployments",
      "namespaced": true,
      "kind": "Deployment",
      "verbs": [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch"
      ],
      "shortNames": [
        "deploy"
      ]
    },
    {
      "name": "deployments/rollback",
      "namespaced": true,
      "kind": "DeploymentRollback",
      "verbs": [
        "create"
      ]
    },
    {
      "name": "deployments/scale",
      "namespaced": true,
      "kind": "Scale",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    },
    {
      "name": "deployments/status",
      "namespaced": true,
      "kind": "Deployment",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    },
    {
      "name": "statefulsets",
      "namespaced": true,
      "kind": "StatefulSet",
      "verbs": [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch"
      ]
    },
    {
      "name": "statefulsets/status",
      "namespaced": true,
      "kind": "StatefulSet",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    }
  ]
}
```

**Comment by deads2k** [comment]
@bparees Bulk shouldn't be doing mapping anymore.  Can you create a gist of the objects that new-app is trying to create?  --dry-run maybe?

**Comment by bparees** [comment]
> This is prior to the rebase - @bparees can you try again post-rebase?

yes it works fine w/ a post-rebase server, i think i stated that in the original report..the problem is when the client/server are mismatched.

> @bparees Bulk shouldn't be doing mapping anymore. Can you create a gist of the objects that new-app is trying to create? --dry-run maybe?

i'm probably just using incorrect terminology.  the object new-app is trying to create is a "extensions.Deployment{}" object.  The Bulk creator is ultimately using the RESTMapper near as i can tell.  At the end of the day, the GroupVersion is being looked up from the object which has no type metadata.  

here's the gist of the debug i did in the restmapper to show the object being mapped and the objectkind/groupverisionkind data it results in:
https://gist.github.com/bparees/4ec28e95e88cf4ecd5937d4a7525919f

**Comment by bparees** [comment]
that debug is in pkg/kubectl/resource/mapper.go:InfoForObject()

**Comment by deads2k** [comment]
Is there no --dry-run?  The internal object serialization just says new-app is creating an internal object.  It doesn't indicate how its serializing that object out for a client to create it.  If `new-app` is serializing out the wrong object, then new app needs to be fixed.  If `new-app` is serializing out the correct object, then we'll need to find the client problem.

**Comment by kargakis** [comment]
I was able to create Deployments in a 3.5 cluster using kubectl 1.7 but not oc 1.6

**Comment by bparees** [comment]
@deads2k well i'm seeing slightly different behavior now, but here's the object new-app has created and is POSTing (which I assume is the external object you were requesting):

```
I0518 16:18:10.995877   28995 request.go:991] Request Body: {"kind":"Deployment"
,"apiVersion":"apps/v1beta1","metadata":{"name":"controller-manager","creationTi
mestamp":null,"labels":{"app":"controller-manager"},"annotations":{"openshift.io
/generated-by":"OpenShiftNewApp"}},"spec":{"replicas":1,"selector":{"matchLabels
":{"app":"controller-manager"}},"template":{"metadata":{"creationTimestamp":null
,"labels":{"app":"controller-manager"}},"spec":{"volumes":[{"name":"service-cata
log-ssl","secret":{"secretName":"apiserver-ssl","items":[{"key":"tls.crt","path"
:"apiserver.crt"}],"defaultMode":420}}],"containers":[{"name":"controller-manage
r","image":"quay.io/kubernetes-service-catalog/controller-manager:canary","args"
:["-v","5","--service-catalog-api-server-url","http://$(APISERVER_SERVICE_HOST):
$(APISERVER_SERVICE_PORT)"],"ports":[{"containerPort":8080,"protocol":"TCP"}],"r
esources":{},"volumeMounts":[{"name":"service-catalog-ssl","readOnly":true,"moun
tPath":"/etc/service-catalog-ssl"}],"terminationMessagePath":"/dev/termination-l
og","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolic
y":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","secur
ityContext":{},"schedulerName":"default-scheduler"}},"strategy":{"type":"Rolling
Update","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}}},"status":{}}
```

here's where it posts it (which is the wrong endpoint, it should be apis/extensions/v1beta1/... for this level of server, i believe)

```
I0518 16:18:10.995951   28995 round_trippers.go:383] POST https://127.0.0.1:8443/apis/apps/v1beta1/namespaces/p1/deployments
```

and it gets rejected based on permissions (rather than resource not found)
```
I0518 16:18:11.020760   28995 request.go:991] Response Body: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"developer\" cannot create deployments.apps in project \"p1\"",
  "reason": "Forbidden",
  "details": {
    "group": "apps",
    "kind": "deployments"
  },
  "code": 403
}
```

which is odd since the server still doesn't actually have an apps/v1beta1 endpoint:
```
$ curl -k https://localhost:8443/apis/apps/v1beta1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "apps/v1beta1",
  "resources": [
    {
      "name": "statefulsets",
      "namespaced": true,
      "kind": "StatefulSet"
    },
    {
      "name": "statefulsets/status",
      "namespaced": true,
      "kind": "StatefulSet"
    }
  ]
}
```

Here's how new-app is converting the internal object to external:
```
	if errs := runtime.DecodeList(result.Objects, kapi.Codecs.LegacyCodec(latest.Version)); len(errs) > 0 {
		err = errors.NewAggregate(errs)
		return nil, fmt.Errorf("error processing template %q: %v", name, err)
	}
```

Now I assume what's going wrong here is that the external object is showing an apiversion of "apps/v1beta1" instead of "extensions/v1beta1".  If that is because we're doing the conversion wrong, i could use some help fixing the conversion...  but i'm not sure how the client would know?

**Comment by liggitt** [comment]
new-app creates Deployment objects now?

**Comment by liggitt** [comment]
oh, from a template

**Comment by deads2k** [comment]
Sounds like a serialization problem in the command.

**Comment by bparees** [comment]
> Sounds like a serialization problem in the command.

@deads2k we read the file in via:

```
		obj, err := resource.NewBuilder(r.Mapper, r.Typer, r.ClientMapper, kapi.Codecs.UniversalDecoder()).
			NamespaceParam(r.Namespace).RequireNamespace().
			FilenameParam(false, &resource.FilenameOptions{Recursive: false, Filenames: terms}).
			Do().
			IntoSingleItemImplied(&isSingleItemImplied).
			Object()
```

at that point my understanding is everything is internal.  In particular since this is a Template object with embedded Objects, the Deployment is embedded as a runtime.Unknown within the Template.Objects array:

```
deployment: &runtime.Unknown{TypeMeta:runtime.TypeMeta{APIVersion:"", Kind:""}, Raw:[]uint8{0x7b,...........
```

Then we ultimately decode it using:
```
	if errs := runtime.DecodeList(result.Objects, kapi.Codecs.LegacyCodec(latest.Version)); len(errs) > 0 {
		err = errors.NewAggregate(errs)
		return nil, fmt.Errorf("error processing template %q: %v", name, err)
	}
```

which gives us a:

```
after decode &extensions.Deployment{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"apiserver", GenerateName:"", Namespace:"", SelfLink:"", .....
```

Notice again we have no Kind/APIVersion information as a result of that decode.

And that is ultimately the object we send into the BulkMapper which tries to make it a apps/deployment and then that gets rejected by the server.

So the problem seems to be that the BulkMapper is only locally aware and as a result it is mapping deployment objects to a type that old servers do not understand.  It doesn't seem like a serialization problem to me.  The object should have been mapped as an extensions/deployments, not an apps/deployments.

**Comment by bparees** [comment]
assigning to @deads2k since it sounds like he's working on a PR for this.
