### ISSUE TITLE
Getting panic when disabling the *just* the node proxy

### ISSUE THREAD

**Issue by celebdor** [openshift/origin#14244]
In the openshift-ansible patches I was readying for Kuryr integration we disable the proxy. We do it as suggested in:

https://github.com/openshift/origin/blob/master/docs/openshift_networking_requirements.md#advanced-requirements

Adding the following to the node /etc/sysconfig/origin-node :

    OPTIONS="--disable proxy"

This used to work in origin 1.4. However, this week I deployed with 1.5 and the node panicked on startup consistently

##### Version
oc v1.5.0
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master-1.kuryrdemo:8443
openshift v1.5.0
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. openshift start node --disable proxy
(or modify the sysconfig options to have systemctl start origin-node pick up the proxy disabling, which is how I did it

##### Current Result
"panic: runtime error: invalid memory address or nil pointer dereference"
##### Expected Result
Starts up properly

##### Additional Information
As a not very agreeable workaround, If I disable the dns and the plugins it boots up well:
--disable dns,proxy,plugins

**Comment by stevekuznetsov** [comment]
Does the panic give you a stack dump as well?

**Comment by celebdor** [comment]
Yes:
`May 19 09:33:04 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/asm_amd64.s:479
May 19 09:33:04 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/panic.go:458
May 19 09:33:04 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/panic.go:62
May 19 09:33:04 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/sigpanic_unix.go:24
May 19 09:33:04 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:332
May 19 09:33:04 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:256
May 19 09:33:04 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:187
May 19 09:33:04 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96
May 19 09:33:04 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97
May 19 09:33:04 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52
May 19 09:33:04 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/asm_amd64.s:2086
May 19 09:33:05 worker-1 origin-node[85250]: E0519 09:33:05.135124   85250 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
May 19 09:33:05 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:72
May 19 09:33:05 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:65
May 19 09:33:05 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:51
May 19 09:33:05 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/asm_amd64.s:479
May 19 09:33:05 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/panic.go:458
May 19 09:33:05 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/panic.go:62
May 19 09:33:05 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/sigpanic_unix.go:24
May 19 09:33:05 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:332
May 19 09:33:05 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:256
May 19 09:33:05 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:187
May 19 09:33:05 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96
May 19 09:33:05 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97
May 19 09:33:05 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52
May 19 09:33:05 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/asm_amd64.s:2086
May 19 09:33:06 worker-1 origin-node[85250]: E0519 09:33:06.137901   85250 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
May 19 09:33:06 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:72
May 19 09:33:06 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:65
May 19 09:33:06 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:51
May 19 09:33:06 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/asm_amd64.s:479
May 19 09:33:06 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/panic.go:458
May 19 09:33:06 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/panic.go:62
May 19 09:33:06 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/sigpanic_unix.go:24
May 19 09:33:06 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:332
May 19 09:33:06 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:256
May 19 09:33:06 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:187
May 19 09:33:06 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96
May 19 09:33:06 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97
May 19 09:33:06 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52
May 19 09:33:06 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/asm_amd64.s:2086
May 19 09:33:07 worker-1 origin-node[85250]: E0519 09:33:07.140765   85250 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
May 19 09:33:07 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:72
May 19 09:33:07 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:65
May 19 09:33:07 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:51
May 19 09:33:07 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/asm_amd64.s:479
May 19 09:33:07 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/panic.go:458
May 19 09:33:07 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/panic.go:62
May 19 09:33:07 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/sigpanic_unix.go:24
May 19 09:33:07 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:332
May 19 09:33:07 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:256
May 19 09:33:07 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:187
May 19 09:33:07 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96
May 19 09:33:07 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97
May 19 09:33:07 worker-1 origin-node[85250]: /builddir/build/BUILD/origin-1.5.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52
May 19 09:33:07 worker-1 origin-node[85250]: /usr/lib/golang/src/runtime/asm_amd64.s:2086
`

**Comment by celebdor** [comment]
I just checked and if I only disable dns,proxy it works. The plugins have no effect. There must be some wrong dependency of kube-dns on the proxy (dependency which I've not found in upstream k8s).

**Comment by pravisankar** [comment]
Tested on latest code and this issue doesn't exist anymore. 
Fix for older release is already merged: https://github.com/openshift/ose/pull/866

**Comment by celebdor** [comment]
Thanks!
