### ISSUE TITLE
ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:\n - Internal Error

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#14245]
test_pull_request_origin_extended_conformance_gce failed because "Stage PROVISION TEST CLUSTER failed.". I think the error quoted in the summary line is the relevant bit but I don't really know

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/2191/consoleFull#188388948758b6e51eb7608a5981914356

**Comment by stevekuznetsov** [comment]
Yeah, I think we intermittently will hit this. /cc @smarterclayton

**Comment by smarterclayton** [comment]
Yeah, this API in GCE sucks.  We need to file a bug about it sucking.

**Comment by stevekuznetsov** [comment]
Haven't seen this since.
