### ISSUE TITLE
oc new-app generating invalid EXPOSE instruction

### ISSUE THREAD

**Issue by dashford** [openshift/origin#14253]
Hi,

I'm trying to add [Localstack](https://github.com/atlassian/localstack) into OpenShift via `oc new-app git@github.com:atlassian/localstack.git --name="localstack"`. This is generating the following error message:

```
error: the Dockerfile has an invalid EXPOSE instruction: could not parse "4567-4582": must be numeric
```

Looking at a previous pull request (https://github.com/openshift/origin/pull/10677) it seems that openshift's validation only allows entirely numeric values rather than other valid options like ranges.

##### Version
```
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.99.100:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. Run `oc new-app git@github.com:atlassian/localstack.git --name="localstack"`

##### Current Result
```
error: the Dockerfile has an invalid EXPOSE instruction: could not parse "4567-4582": must be numeric
```

##### Expected Result
The app should be created an a build started.

Any additional information, please let me know.
Thanks!

**Comment by php-coder** [comment]
CC @bparees

**Comment by bparees** [comment]
i'm going to lump this in with https://bugzilla.redhat.com/show_bug.cgi?id=1452162

**Comment by dashford** [comment]
Thanks @bparees

**Comment by ianmiell** [comment]
I have a fork with a more naive Dockerfile: https://github.com/ianmiell/localstack/blob/master/Dockerfile
