### ISSUE TITLE
oc delete po --grace-period=0 is not respected

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14257]
Instead we set grace period to 1

https://pastebin.com/i06W60FQ

Is this expected?

@ncdc @deads2k @smarterclayton @liggitt @sttts

**Comment by ncdc** [comment]
I believe you now how to specify `--force` as well

**Comment by liggitt** [comment]
Yes, intentional 

https://github.com/kubernetes/kubernetes/pull/37263

**Comment by kargakis** [comment]
--grace-period=0 --force works fine
