### ISSUE TITLE
Generated OpenAPI spec lacks 'securityDefinitions' key

### ISSUE THREAD

**Issue by caseyfw** [openshift/origin#14268]
The generated OpenAPI spec is missing the [securityDefinitions](http://swagger.io/specification/#securityDefinitionsObject) section that defines which security mechanisms the API supports (e.g. OAuth, HTTP Basic, etc).

This means clients generated from it using tools like [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) lack security context and only work with endpoints that do not require auth.

##### Version
Current master branch.

##### Steps To Reproduce
```
curl -s https://raw.githubusercontent.com/openshift/origin/master/api/swagger-spec/openshift-openapi-spec.json | grep securityDefinitions
```

##### Current Result
No output.

##### Expected Result
```
  "securityDefinitions": {
```

##### Additional Information
As a concrete example, here is an [OpenShift PHP client](https://github.com/universityofadelaide/openshift-restclient-php) generated using the 2.3.0 branch of [Swagger Codegen](https://github.com/swagger-api/swagger-codegen/tree/2.3.0) from the [current OpenShift API spec](https://raw.githubusercontent.com/openshift/origin/master/api/swagger-spec/openshift-openapi-spec.json) in master branch. The PHP codegen templates (correctly) only output auth code if the [authMethods](https://github.com/swagger-api/swagger-codegen/blob/2.3.0/modules/swagger-codegen/src/main/resources/php/api.mustache#L256) item is set, which is derived from the [securityDefinitions](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L646) key in the spec.

The [example API spec](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/petstore.json#L811) provided by Swagger shows a correctly configured securityDefinitions item.

**Comment by enj** [comment]
@liggitt I think the cleanest change would be to update [DefaultOpenAPIConfig](https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/master/master_config.go#L434) to extract info from `masterConfig` to build the `SecurityDefinitions`.  I believe we would want (assuming OpenAPI supports all of these):

1. OAuth
2. Bearer Token (web sockets?)
3. x509

WDYT?

**Comment by simo5** [comment]
Looking at existing securityDefitions examples in the code, it looks like Oauth is considered a Bearertoken and rthere is no differentiation between that ans ServiceAccount tokens ...
Also I could not find any example of x509 auth defintions ...

**Comment by enj** [comment]
@simo5 does swagger differentiate between random noise tokens and JWTs?  I believe they use the same header.  I would assume you need to look at the swagger specification to determine how to represent tokens, certs, etc.

**Comment by simo5** [comment]
Swagger (and code in origin) does not differentiate between JWT and other Bearer tokens.
I couldn't find any example of swagger representing a x509 authentication, so I am kinda blocked on that one.
I will open a WIP PR in a moment to start reasoning on this with some code at hand.
