### ISSUE TITLE
oc get sa --loglevel=5 on master returns no glog output

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#14265]
Mac, recent master

```
oc get sa --loglevel=5
```

returns no glog output.  Bumping to a higher level returns glog.  We may have broken the default flush behavior (we must always flush when we exit main(), otherwise we can loose output).

**Comment by fabianofranz** [comment]
Do we even log anything below level 5 on a successful `get` call? The config loader and cache discovery are all level 6 and up. Log flushing seems correct in both `oc` and `kubectl`.

**Comment by smarterclayton** [comment]
I'm shocked we log nothing below v6.  But looks like that's the case.
