### ISSUE TITLE
Too many kubelet_docker_operations_errors are being reported

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#14266]
Over a six hour period on a moderately large (105 node, 800 pod) cluster, the following average metrics per node were generated by the kubelet (errors per 6 hours per node):

```

Element	Value
{operation_type="inspect_container"}	93686.74285714283
{operation_type="remove_container"}	28869.180952380957
{operation_type="list_containers"}	223.45714285714286
{operation_type="version"}	64.18095238095238
{operation_type="list_images"}	29.257142857142856
{operation_type="inspect_image"}	28.26666666666666
{operation_type="pull_image"}	5.647619047619047
{operation_type="stop_container"}	3.1619047619047604
{operation_type="remove_image"}	0.9333333333333332
{operation_type="start_exec"}	0.8666666666666668
{operation_type="start_container"}	0.39047619047619053
{operation_type="create_container"}	0.30476190476190484
{operation_type="inspect_exec"}	0.18095238095238095
{operation_type="resize_exec"}	0.08571428571428573
{operation_type="logs"}	0.06666666666666668
{operation_type="create_exec"}	0.05714285714285715
```

inspect_container and remove_container are *probably* returning 404, but we are logging them as real errors.  In most places where those methods are called by kubernetes, they are safe - i.e. as a pod is terminated in a sync loop, if we expect the container to go away, a 404 isn't an error, it's normal.

We should sweep all the places where we return these and verify that we are correctly handling "not found" to separate normal behavior from error.

**Comment by smarterclayton** [comment]
Hrm - rate is pretty low for the other errors over time.  Not sure exactly - maybe these stats are persistent across kubelet restarts (coming from the daemon?), or something else is weird.

**Comment by andrewklau** [comment]
I see this a lot too. When I was watching logs, most of the errors do come from 404/not found. 
remove_container for me has always been related to devicemapper/thin_ls and it's delayed removal. 

Would be cool to see if there was a way to find only the critical events.

**Comment by derekwaynecarr** [comment]
for future reference, this is 3.5.1.10 version of openshift.

**Comment by smarterclayton** [comment]
3.5.5.10

**Comment by derekwaynecarr** [comment]
thx for fixing my typo ;-)

**Comment by sjenning** [comment]
@joelsmith PTAL
