### ISSUE TITLE
test/cmd/quota/clusterquota.test/cmd/quota.sh:35: executing 'oc describe appliedclusterresourcequota/for-deads-by-annotation -n bar --as deads'

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14261]
```
=== BEGIN TEST CASE ===
test/cmd/quota.sh:35: executing 'oc describe appliedclusterresourcequota/for-deads-by-annotation -n bar --as deads' expecting any result and text 'secrets.*(1[0-9]|20|21|22)'; re-trying every 0.2s until completion or 60.000s
FAILURE after 59.793s: test/cmd/quota.sh:35: executing 'oc describe appliedclusterresourcequota/for-deads-by-annotation -n bar --as deads' expecting any result and text 'secrets.*(1[0-9]|20|21|22)'; re-trying every 0.2s until completion or 60.000s: the command timed out
```

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/711

We don't seem to have a quota component label.  Let me know if it would be appropriate to create one, or is there some other component that's being used for that?

**Comment by deads2k** [comment]
infrequent counting problem in quota which is structural.

**Comment by bparees** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17661/test_pull_request_origin_cmd/7138/

@deads2k can the test be loosened to tolerate the counting problem?

**Comment by mfojtik** [comment]
See here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18328/test_pull_request_origin_cmd/9314/
