### ISSUE TITLE
etcdhelper: add a README file with usage

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#14278]
As an OpenShift developer I'd like to have ability to read about `etcdhelper` utility in human readable format. At this time it looks like a private tool.

Right now, to build it, I did:
```console
$ cd tools/etcdhelper
$ go build
```

When I'm executing it with `-h` option it shows me only flags and not the options (where is `ls`, `get` and `dump`?):
```console
$ ./etcdhelper -h
Usage of ./etcdhelper:
  -alsologtostderr
    	log to standard error as well as files
  -cacert string
    	Server TLS CA certificate.
```

Also I couldn't run it because of error:
```console
$ ./etcdhelper dump
ERROR: unable to connect to etcd: grpc: timed out when dialing
```

CC @soltysh @enj

**Comment by php-coder** [comment]
> When I'm executing it with -h option it shows me only flags and not the options (where is ls, get and dump?):

They're here:
```console
./etcdhelper 
ERROR: you need to specify action: dump or ls [<key>] or get <key>
```

**Comment by php-coder** [comment]
> Also I couldn't run it because of error:

I got it working with the following command:
```console
sudo ./etcdhelper \
-cacert /path/to/openshift.local.config/master/ca.crt  \
-cert /path/to/openshift.local.config/master/master.etcd-client.crt \
-key /path/to/openshift.local.config/master/master.etcd-client.key \
dump
```

**Comment by enj** [comment]
@php-coder in reality it is a private developer tool that is tied to the types that existed when it was compiled.  Very few people would have the keys to mess with etcd directly and you cannot mutate data using it.  I am not against adding docs for it, but I do not intend customers to use it.

**Comment by php-coder** [comment]
> you cannot mutate data using it.

If it will be able to do this, it would be possible to push it to the upstream: https://github.com/kubernetes/kubernetes/issues/45974

> I do not intend customers to use it.

Yes, I understand. That's why I put "As an OpenShift developer" to the description.

**Comment by enj** [comment]
> If it will be able to do this, it would be possible to push it to the upstream

@php-coder the upstream tool probably would not be able to decode the origin types but @deads2k would know more about that.

**Comment by deads2k** [comment]
> @php-coder the upstream tool probably would not be able to decode the origin types but @deads2k would know more about that.

Upstream tooling cannot decode openshift protobuf objects without being recompiled with new types.
