### ISSUE TITLE
Importing properly labeled image should add it to Catalog

### ISSUE THREAD

**Issue by marekjelen** [openshift/origin#14291]
When docker image has all necessary labels and is imported using `oc import-image` into OpenShift, the resulting IS does not extract labels from the image and so does not add the builder into the Catalog.

##### Version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. oc import-image sample --from=mjelen/s2i --confirm
2. go to Catalog in Web UI

##### Current Result
The sample builder is not in the "Uncategorized" category.

##### Expected Result
The sample builder should be in the "Uncategorized" category.

##### Additional Information
When importing IS using the `oc import-image` the spec -> tags -> annotations should be populated from the labels attached to the docker image, e.g.

```
{
   "kind": "ImageStream",
   "apiVersion": "v1",
   "metadata": {
   },
   "spec": {
      "tags": [
         {
            "annotations": {
               "description": "<populated from io.k8s.description label>",
               "tags": "<populated from io.openshift.tags>"
            }
         }
      ]
   }
}
```

**Comment by pweil-** [comment]
Trello card:  https://trello.com/c/RPTugJoZ/515-5-registry-import-docker-labels-as-annotations
