### ISSUE TITLE
`openshift ex config` does not use the same clientcmd.Config as `osc`

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1431]
Needs to be updated to take the factory (or at least take the same client.config)

Also, expose both `openshift admin config *` and `osc config *` at that time.

**Comment by smarterclayton** [comment]
@deads2k as we discussed

**Comment by deads2k** [comment]
There's been a lot of action on this and there's more to come as we collapse the loading chain even further.  For now, this particular problem has been fixed here: https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/config.go#L16.

@jwforres close please?
