### ISSUE TITLE
template service broker: use groups/extra information from catalog

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#14315]
Once the catalog is able to pass in groups/extra information, use this throughout the relevant flows, and enable SARing for the template in provision.go

**Comment by pweil-** [comment]
@jim-minter @bparees should this be a trello card?

**Comment by bparees** [comment]
my guess is the effort will be pretty small once the api is in place, we can probably get away w/ leaving it as an issue as long as we don't forget about it.

@jim-minter correct me if you think this is more than a one hour code change once the SC is providing the info.

**Comment by jim-minter** [comment]
Thinking about it, I fear it's going to be >1 hour, e.g. because I think there'll be an API change.  Gonna open a trello card.

**Comment by jim-minter** [comment]
https://trello.com/c/EXHlyops/
