### ISSUE TITLE
fedora_inst libvirt image won't build without updating golang

### ISSUE THREAD

**Issue by juanluisvaladas** [openshift/origin#14313]
##### Version

OpenShift origin branch master commit 50b7254bf0a6e2354a2486781b6d6f2ab6451ef2
fedora_inst libvirt image available at https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_virtualbox_inst.box uploaded on 10-Nov-2016 

##### Steps To Reproduce
1. export VAGRANT_DEFAULT_PROVIDER=libvirt
2. Run ```vagrant box delete fedora_inst --provider libvirt``` to ensure you download the latest image 
3. Run ```vagrant up ``` and ```vagrant ssh```
3. ```cd /data/src/github.com/openshift/origin/```
4-```make clean build```

##### Current Result
```[vagrant@localhost origin]$ make clean build
rm -rf _output
hack/build-go.sh  
[FATAL] Detected Go version: go version go1.6.2 linux/amd64.
[FATAL] Origin builds require Go version 1.7 or greater.
[ERROR] PID 3216: hack/common.sh:152: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/common.sh:152: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )`
[INFO] 		  2: hack/build-go.sh:37: os::build::build_binaries
[INFO]   Exiting with code 1.
Makefile:41: recipe for target 'build' failed
make: *** [build] Error 1
```
##### Expected Result
Build should perform successfully

##### Additional Information
Fixing this is quite trivial since golang is compiled statically, although it should work by default, specially because it's not documented on CONTIRBUTING.md

I haven't tested it with other providers but most likely there are more affected

**Comment by pweil-** [comment]
@stevekuznetsov @sdodson this isn't really an install issue but I'm not sure who to assign this one to.  Do you know who is maintaining this vm?

**Comment by sdodson** [comment]
@dobbymoodge do you know who maintains this image?

**Comment by dobbymoodge** [comment]
@sdodson Ugh, I think it's supposed to be me. I guess I know what I'm doing this morning. :)

**Comment by stevekuznetsov** [comment]
Right now the unfortunate answer is that we have a couple Trello cards [1](https://trello.com/c/TvTgWOJN/202-ci-maintenance-re-enable-the-vm-image-build-pipeline-for-the-origin-ci-tool) [2](https://trello.com/c/efl0h7sm/35-ci-oct-localdevtooling-improve-support-for-local-development-work-using-the-origin-ci-tool) for maintenance tasks for these VMs but nobody is looking into it right now. I'll talk with @dobbymoodge to see what we can do.

**Comment by dobbymoodge** [comment]
Just a bump to say this is still on my stack, but I haven't been able to make time for it yet :(

**Comment by dobbymoodge** [comment]
I'm 99% sure nobody cares about this anymore. @juanluisvaladas is this still a concern for you?

**Comment by juanluisvaladas** [comment]
@dobbymoodge I'm building it on my workstation, so if you want to remove the feature it's ok for me.

**Comment by dobbymoodge** [comment]
Stale, and the fix is no longer relevant/possible
