### ISSUE TITLE
Collapse router image directories

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14325]
Is there a reason for keeping egress separate from haproxy, f5?

https://github.com/openshift/origin/tree/master/images/egress/router
https://github.com/openshift/origin/tree/master/images/router

@knobunc @ramr @smarterclayton

**Comment by knobunc** [comment]
images/router/* are about getting traffic in to the cluster.

images/egress/* are about getting traffic out of the cluster.

**Comment by smarterclayton** [comment]
Different images?
