### ISSUE TITLE
flake: ERROR! Problem parsing file '/data/src/github.com/openshift/aos-cd-jobs/sjb/inventory/group_vars/OSEv3/checks.yml'

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#14334]
test_pull_request_origin_extended_conformance_install_update failed with:

    + echo '=== Installing origin-1.5.1-1.el7 ==='
    ++ cat ./DEPLOYMENT_TYPE
    + ansible-playbook -vv --become --become-user root --connection local --inventory sjb/inventory/ /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-node/network_manager.yml -e deployment_type=origin
    Using /etc/ansible/ansible.cfg as config file
    ERROR! Problem parsing file '/data/src/github.com/openshift/aos-cd-jobs/sjb/inventory/group_vars/OSEv3/checks.yml': line 2, column 1
    ++ export status=FAILURE
    ++ status=FAILURE
    + set +o xtrace
    ########## FINISHED STAGE: FAILURE: INSTALL ORIGIN ##########
    Build step 'Execute shell' marked build as failure

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/513/consoleFull#181270559558b6e51eb7608a5981914356

**Comment by sdodson** [comment]
@sosiouxme https://github.com/openshift/aos-cd-jobs/pull/288 fixed this, right?

**Comment by sosiouxme** [comment]
Yep, last week. And, my bad :(
