### ISSUE TITLE
Question about quickstart templates

### ISSUE THREAD

**Issue by wzheng1** [openshift/origin#14343]
Hi Ben, can I know why these templates are not included in examples/quickstarts and not installed in OCP/Online?
https://github.com/openshift/nodejs-ex/blob/master/openshift/templates/nodejs.json
https://github.com/openshift/dancer-ex/blob/master/openshift/templates/dancer.json
https://github.com/openshift/django-ex/blob/master/openshift/templates/django.json
https://github.com/openshift/cakephp-ex/blob/master/openshift/templates/cakephp.json

Looking forward to your answer, thanks in advance!

**Comment by bparees** [comment]
@wzheng1 we wanted to simplify the number of quickstarts users are confronted with in online.  We didn't think there was much value in giving them both a "with a database" and "without a database" version of the sample applications, so we just went with the "with a database" versions.

**Comment by akostadinov** [comment]
Does that mean we should not actually have to test the other versions with online?
If we don't have anything "official" then I see no point in testing it given it is not part of the product.

**Comment by bparees** [comment]
@akostadinov well it's still a template we offer that users can find and use so we'd like to not break them, but testing them in one environment (whether that's online or OCP) should be sufficient.

**Comment by akostadinov** [comment]
The thing about testing a git branch is that the branch can change at any time without warning. I think we rely on the upstream tests in this case anyway.
Not useless to test for sure. But will be not a hard guarantee it will work when users try it. I'll leave the responsible team to decide how to handle this. Just wanted to confirm that these images would not have same level of support.

**Comment by bparees** [comment]
>  Just wanted to confirm that these images would not have same level of support.

confirmed.

**Comment by wzheng1** [comment]
@bparees Thanks for your feedback!
