### ISSUE TITLE
Flake: e2e: the command timed out

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#14367]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1755/testReport/junit/github/com_openshift_origin_test_end-to-end_core/test_end_to_end_core_sh_409__executing__oc_get_pods__l_openshift_io_deployer_pod_type_hook_pre___o_jsonpath___items____status_phase___expecting_any_result_and_text___Succeeded$___re_trying_every_0_2s_until_completion_or_60_000s/
```
=== BEGIN TEST CASE ===
test/end-to-end/core.sh:409: executing 'oc get pods -l openshift.io/deployer-pod.type=hook-pre  -o jsonpath={.items[*].status.phase}' expecting any result and text '^Succeeded$'; re-trying every 0.2s until completion or 60.000s
FAILURE after 60.120s: test/end-to-end/core.sh:409: executing 'oc get pods -l openshift.io/deployer-pod.type=hook-pre  -o jsonpath={.items[*].status.phase}' expecting any result and text '^Succeeded$'; re-trying every 0.2s until completion or 60.000s: the command timed out
Standard output from the command:
Standard error from the command:
=== END TEST CASE ===
```

**Comment by pweil-** [comment]
I've seen a few other time out flakes lately.  They may all be related but it seems like there is something that needs to be investigated in infra.

**Comment by tnozicka** [comment]
I think this happened because it is the first test there that uses docker.io/busybox and pulling that image took too long.
