### ISSUE TITLE
openshift-openapi-spec.json missing x-kubernetes-group-version-kind

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#14373]
The OpenShift OpenAPI JSON is missing the `x-kubernetes-group-version-kind` property to know what API group, version, and kind the schema is describing. The property is there in the upstream swagger.json.

OpenShift:

https://github.com/openshift/origin/blob/master/api/swagger-spec/openshift-openapi-spec.json

Upstream:

https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json

@smarterclayton @jwforres

**Comment by smarterclayton** [comment]
Blocker because this prevents some automation from working.

**Comment by smarterclayton** [comment]
@sttts we may have lost a part of openapi in the rebase.

**Comment by sttts** [comment]
They were only recently added in https://github.com/kubernetes/kubernetes/commit/fca7003dc5bd122e2123ef260e8612663f74a65b#diff-8445f058e4643cc06261a14af95e8470 upstream. Did we have them before in origin?

**Comment by smarterclayton** [comment]
I must be thinking of a different upstream change.

I'm considering backporting this so Sam can rely on them.
