### ISSUE TITLE
integration tests not dumping logs

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14376]
As seen here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/2601/consoleFull

When the webhook test fails, the server log is not dumped:

```
Running TestWebhook...
failed  TestWebhook
=== RUN   TestWebhook
masterAddr: "127.0.0.1:12000"
--- FAIL: TestWebhook (7.82s)
	webhook_test.go:123: Created build not found in cluster: builds.build.openshift.io "pushbuild-12" not found
	etcd.go:126: dumping etcd to "/tmp/openshift/test-integration/etcd-dump-runtime.call32.json"
Running TestWebhookGitHubPing...
```

It's also worth nothing that "etcd-dump-runtime.call32.json" does not appear in the s3 artifacts, not sure if that needs a separate issue or if @enj is fixing that with his other changes.

@stevekuznetsov assigning to you because @smarterclayton says you changed the log behavior for integration tests recently.

**Comment by stevekuznetsov** [comment]
In fact it was @jhadvig that made the recent changes -- the server log should be in the same process as the test, right? Unclear why it's not getting put anywhere.

**Comment by smarterclayton** [comment]
Yeah, it's like stderr got sent someplace else but not included in the
junit.

**Comment by enj** [comment]
I still have not gotten #14145 working so no etcd dump...

**Comment by stevekuznetsov** [comment]
> It's also worth nothing that "etcd-dump-runtime.call32.json" does not appear in the s3 artifacts, 

We also have this code in [`test/util/client.go`](https://github.com/openshift/origin/blob/master/test/util/client.go#L30-L33):

```go
// GetBaseDir returns the base directory used for test.
func GetBaseDir() string {
	return cmdutil.Env("BASETMPDIR", path.Join(os.TempDir(), "openshift-"+Namespace()))
}
```

We should probably separate the `$BASETMPDIR` -- actual temporary things and `$BASEOUTDIR` -- things that get saved as output from a test run. Right now @bparees that etcd thing is put into the tmp directory, which does not get persisted.
