### ISSUE TITLE
Image GC Removes Infrastructure Images

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#14371]
In CI we are seeing the image GC remove infrastructure images like `openshift/origin-pod`. See this [recent test run](https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/79/) where we see tests fail with:

```
May 26 01:39:02.693: INFO: At 2017-05-26 01:33:56 -0400 EDT - event for test-pod-e965194c-41d4-11e7-902f-0ec295d3db32: {kubelet 172.18.10.174} FailedSync: Error syncing pod, skipping: failed to "CreatePodSandbox" for "test-pod-e965194c-41d4-11e7-902f-0ec295d3db32_extended-test-s2i-usage-psfr5-fqmwx(e965bd47-41d4-11e7-9bac-0ec295d3db32)" with CreatePodSandboxError: "CreatePodSandbox for pod \"test-pod-e965194c-41d4-11e7-902f-0ec295d3db32_extended-test-s2i-usage-psfr5-fqmwx(e965bd47-41d4-11e7-9bac-0ec295d3db32)\" failed: rpc error: code = 2 desc = unable to pull sandbox image \"openshift/origin-pod:4bc3b30\": Tag 4bc3b30 not found in repository docker.io/openshift/origin-pod"
```

And we see this in the log:

```
 E0526 01:33:53.029257    5536 kubelet.go:1170] Image garbage collection failed: wanted to free 1651087769, but freed 1796661201 space with errors in image deletion: [rpc error: code = 2 desc = Error response from daemon: {"message":"conflict: unable to remove repository reference \"openshift/origin-pod:latest\" (must force) - container 615e30c56733 is using its referenced image baf2c076564e"}, rpc error: code = 2 desc = Error response from daemon: {"message":"conflict: unable to delete 04224f601398 (cannot be forced) - image has dependent child images"}, rpc error: code = 2 desc = Error response from daemon: {"message":"conflict: unable to delete 97b5c50da638 (cannot be forced) - image has dependent child images"}, rpc error: code = 2 desc = Error response from daemon: {"message":"conflict: unable to remove repository reference \"openshift/origin-docker-registry:latest\" (must force) - container b71140d4690e is using its referenced image cf154706d3da"}]
```

/cc @smarterclayton @bparees @derekwaynecarr

**Comment by stevekuznetsov** [comment]
To be clear, the cluster was trying to use `openshift/origin-pod:4bc3b30` as the pod image, which was deleted, image GC also apparently wanted to remove `openshift/origin-pod:latest`, which failed.

**Comment by derekwaynecarr** [comment]
this is a feature request for kubelet to ignore certain images for gc.  reducing priority.

**Comment by bparees** [comment]
this is actually breaking our tests semi regularly (or was) so while I don't disagree w/ treating the main issue as an RFE, we need to figure out what we're going to do in our test environment to avoid this problem in the meantime (unless @stevekuznetsov can tell me it's already been addressed).

I think it mostly comes down to allocating more docker storage for images.

**Comment by stevekuznetsov** [comment]
The issue has been addressed in the environments by bumping storage allocations.

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale
/lifecycle frozen

This remains a royal PITA
