### ISSUE TITLE
Can "oc get imagestream" return the registry route host ?

### ISSUE THREAD

**Issue by dmsimard** [openshift/origin#14384]
An installation provided by openshift-ansible today yields an internal/private IP address inside the ``DOCKER REPO`` url when doing the command ``oc get is``.

For example:
```
$ oc get imagestreams -n test
NAME      DOCKER REPO                       TAGS      UPDATED
busybox   172.30.11.215:5000/test/busybox   latest    2 seconds ago
```

This is also mentioned as an explicit note in [official documentation](https://access.redhat.com/documentation/en-us/openshift_container_platform/3.5/html/installation_and_configuration/setting-up-the-registry#exposing-the-registry):
> NOTE
> Your image streams will have the IP address and port of the registry service, not the route name and port. See oc get imagestreams for details.

I understand the need for internal service components to use non-routed and direct access to the registry, and that changing the host for the ``DOCKER REPO`` would lead to unnecessary load on the router.

However, this is poor in terms of end user experience -- it yields an unknown and unreachable ``DOCKER REPO`` url.

https://github.com/openshift/openshift-ansible/pull/4292 aims to change the IP address for a (internal) hostname which, in the end, doesn't change the fact that the end user will not be able to use it.

Is there a way to expose the docker-registry service route DNS for end users using the ``oc get is`` command without impacting service reaching the registry directly ?

##### Version
oc v1.5.0
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.1.15:8443
openshift v1.5.0
kubernetes v1.5.2+43a9be4

##### Current Result
An internal IP or host is provided to end users in the DOCKER REPO field of the ``oc get is`` command.

##### Expected Result
The DOCKER REPO field of the ``oc get is`` command instead returns the docker-registry service route host.

**Comment by dmsimard** [comment]
@sdodson: as per discussed
@mfojtik: I'm told this is something you might be able to help with ?

**Comment by sdodson** [comment]
I believe setting OPENSHIFT_DEFAULT_REGISTRY to point at the route would probably make things display as you'd like. The thing I'm wondering is if push/pull secrets would be generated properly. Also, what impact this would have? It'd surely result in an increase in traffic through the routing layer.

**Comment by mfojtik** [comment]
@sdodson no, currently we only set the secrets for the IP address of the service and for the foo.bar.svc DNS.

**Comment by dmsimard** [comment]
Tracked in Trello - adding the concept of a public URL for image streams: https://trello.com/c/2cHkrqIu/954-provide-public-pull-url-for-images

**Comment by mfojtik** [comment]
@dmsimard @sdodson discussion seems to happen here: https://github.com/openshift/origin/pull/14398

**Comment by codrinbucur** [comment]
this would be quite important
