### ISSUE TITLE
Builds are pushing layers to the registry that shouldn't be needed

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#14382]
Running an S2I build for a base image that already exists in the registry we still see it pushing 9+ layers.  @smarterclayton and @bparees said this should not be the case.  Even on subsequent builds of the same build config it continues to push a number of layers.

**Comment by bparees** [comment]
if this has regressed, I don't think it's the first time.  Do we have sufficient test coverage for trusted layer checking?

**Comment by smarterclayton** [comment]
The base image might require us to use registry pull through (which is ok,
no perf hit if the upstream registry is fast) for the base images.  The
subsequent build thing seems wrong unless metadata on the node is not
correct for the originating location.

**Comment by dmage** [comment]
Let's go step-by-step through the process.

* Builder fetches a base image from docker.io.
* It builds code.
* It uploads the result to the internal registry.

Layers might be reused
1. if there is the same layer in the same ImageStream,
2. or if Docker client uses the cross repository blob mount.

For the first case, someone should upload the base image or make image-import of it (aka pull through).
For the second case, builder should get the base image from the internal registry.

I guess neither is satisfied, so the layers were uploaded.

**Comment by smarterclayton** [comment]
The subsequent build is the most concerning part of this.  That should not
happen on subsequent pushes.

The first case is probably solved if we set the shared images to use local
pull through, however that won't always be the right thing to do if the
location of those images doesn't support offload.

We should verify that registry.access.redhat.com properly supports content
offload when we set an openshift/image to resolve the reference.  If it
does, we can consider instructing the server to pull through.

**Comment by dmage** [comment]
I've tried with cakephp-ex, the log output says 4 layers are reuploaded.
The difference is in timestamp bytes (5-8) in gzip headers.
```
php-56-centos7/blobs/sha256:ca0dd86f0ac1dced164a4bc7032126a8d3f10014c51ac438eb2a1eaee52abcc7
1f 8b 08 00 [00 09 6e 88] 00 ff

cakephp-example/blobs/sha256:98f6c65b9f49b791fc06dc56c1406c6ca1c5743e7e90556514f728c09d9f9d63
1f 8b 08 00 [00 00 00 00] 00 ff
```
Does S2I try to recompress the base image?

The next build uploaded only 1 layer, as expected.

**Comment by bparees** [comment]
No, it shouldn't be touching the base layers...

**Comment by smarterclayton** [comment]
I think this is the Go version mismatch between docker and registry -
docker is recalculating layer digests and getting a different answer
because go changed.

On May 29, 2017, at 1:28 PM, Ben Parees <notifications@github.com> wrote:

No, it shouldn't be touching the base layers...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/14382#issuecomment-304704706>,
or mute the thread

**Comment by dmage** [comment]
So I've tried it once again.

```
Builder image: centos/php-70-centos7@sha256:b963a0c6daf776a452cf765ab66c0a80ba431d861f91ad352e72e4448f1eae50
Output image: myproject/cakephp-example:latest
```

S2I pulled the builder image from docker.io, so its layers couldn't be cross-mounted into the output repository.

For some reason the layers was touched:

```
$ diff -dur <(hexdump -C <builder-image-layer-4.tar.gz) <(hexdump -C <result-image-layer-4.tar.gz)
--- /dev/fd/63  2017-06-27 18:19:08.793021671 +0200
+++ /dev/fd/62  2017-06-27 18:19:08.793021671 +0200
@@ -1,4 +1,4 @@
-00000000  1f 8b 08 00 00 09 6e 88  00 ff ec 59 6d 6f db 38  |......n....Ymo.8|
+00000000  1f 8b 08 00 00 00 00 00  00 ff ec 59 6d 6f db 38  |...........Ymo.8|
 00000010  12 ce 67 fe 8a a9 1a ac  6d d4 2f 8a 13 27 7b d9  |..g.....m./..'{.|
 00000020  f5 e2 ba 5d 17 1b 6c 5b  1f dc 76 7b 8b 5e 21 d0  |...]..l[..v{.^!.|
 00000030  d2 c8 22 2a 91 02 49 d9  31 8a fe f7 c3 90 b2 a5  |.."*..I.1.......|
$
```

But they could not be reused for the first time without cross-mounting. So for now that's doesn't matter.

When I built the second time, in the logs was:

```
Pushing image 172.30.1.1:5000/myproject/cakephp-example:latest ...
Pushed 6/9 layers, 67% complete
Pushed 7/9 layers, 78% complete
Pushed 8/9 layers, 89% complete
Pushed 9/9 layers, 100% complete
Push successful
```

But the things was changed in the manifest were the last layer and the config. And there were only two POSTs for these blobs in the registry logs. So the log is a bit misleading.

Therefore, it seems it works and I want steps to reproduce this bug.

**Comment by smarterclayton** [comment]
Since it was on docker for mac, i suppose this could be the go version
mismatch thing

**Comment by dmage** [comment]
So, as for me, everything works as expected.

If you want fewer pushes on the first build, then we need to pull base images from the internal registry and probably to make some fixes to S2I. Please open another issue for a such enhancement.

A subsequent build, as I can see in registry logs, uploads only one layer. Although it prints more than one "Pushed" message, it's not true. It can upload more layers if the builder image is changed, though.

Please provide me with steps to reproduce if you think there is a bug.
