### ISSUE TITLE
Couldn't get version/kind; json parse error: unexpected end of JSON input

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#14396]
github.com/openshift/origin/test/cmd/request-timeout.test/cmd/timeout.sh:19: executing 'oc login -u testuser -p test --request-timeout=1ns' expecting failure and text 'Timeout exceeded while awaiting headers' (from github.com_openshift_origin_test_cmd_request-timeout)

```
=== BEGIN TEST CASE ===
test/cmd/timeout.sh:19: executing 'oc login -u testuser -p test --request-timeout=1ns' expecting failure and text 'Timeout exceeded while awaiting headers'
FAILURE after 0.465s: test/cmd/timeout.sh:19: executing 'oc login -u testuser -p test --request-timeout=1ns' expecting failure and text 'Timeout exceeded while awaiting headers': the output content test failed
There was no output from the command.
Standard error from the command:
error: couldn't get version/kind; json parse error: unexpected end of JSON input
=== END TEST CASE ===
```

See: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1823/testReport/junit/github/com_openshift_origin_test_cmd_request-timeout/test_cmd_timeout_sh_19__executing__oc_login__u_testuser__p_test___request_timeout_1ns__expecting_failure_and_text__Timeout_exceeded_while_awaiting_headers_/

**Comment by mfojtik** [comment]
@stevekuznetsov @smarterclayton infra flake?

**Comment by stevekuznetsov** [comment]
Infra seems fine here -- the error is from `oc` and seems legitimate.

**Comment by mfojtik** [comment]
@smarterclayton @sttts this seems like we got faster and we get something back in 1ns? that something was JSON junk we interrupted in the middle?

**Comment by sttts** [comment]
> that something was JSON junk we interrupted in the middle

Could be. Any chance to reproduce locally?

**Comment by mfojtik** [comment]
Likely infra issue and haven't seen this for ~2 months, closing.
