### ISSUE TITLE
Helm integration

### ISSUE THREAD

**Issue by odzhu** [openshift/origin#14394]
[Helm not able to install charts on OpenShift Origin]

##### Version
v1.4.1+3f9807a

##### Steps To Reproduce
1. helm install --tiller-namespace myproject stable/mysql --name test --kube-context myproject/192-168-64-6:8443/system:admin

##### Current Result
"system:serviceaccount:myproject:default" cannot get namespaces in project "myproject"
##### Expected Result
packaged installed
##### Additional Information
Same [issue](https://github.com/kubernetes/helm/issues/2517) on helm side.

Please advise on future plans with regards to helm.

Thank you.

**Comment by mfojtik** [comment]
@deads2k cannot get namespaces in project seems pretty crazy.

**Comment by odzhu** [comment]
@mfojtik, @deads2k , 

this is [resolved](https://github.com/kubernetes/helm/issues/2517) 

Thank you.
