### ISSUE TITLE
WARNING: Binding DNS on port 8053 instead of 53

### ISSUE THREAD

**Issue by sputnik-1** [openshift/origin#14392]
When I start the docker all-in-one OpenShift container the DNS server binds to port 8053 and I have problems using the web interface to login to the console. Using the Arora web browser the login page displays OK, but after I login to the console, the page does not load properly. Please see the attached screenshots for more information.

I can use the OC command from a terminal as normal developer or as the admin user. I just need to get the web console interface working now.

spock@laptop ~ $ oc cluster up --image=registry.access.redhat.com/openshift3/ose --version=latest
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:latest image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... 
   WARNING: Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients.
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.1.100 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.1.100:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

I can access the cluster from the command line OK, but not from the web console.

It looks like the issue is with the DNS server binding to port 8053 instead of 53.

spock@laptop ~ $ oc version
oc v3.5.5.10
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.1.100:8443
openshift v3.5.5.15
kubernetes v1.5.2+43a9be4

Running nslookup I get the following output:

spock@laptop ~ $ nslookup x.192.168.1.100.xip.io
Server:         127.0.1.1
Address:        127.0.1.1#53

Non-authoritative answer:
Name:   x.192.168.1.100.xip.io
Address: 192.168.1.100

which would indicate DNS is expected to be bound to port 53.

This is running on a 64 bit laptop with Linux Mint Sarah (based on Ubuntu 16.04) installed.

I'm using the following docker version:

spock@laptop ~ $ docker version
Client:
Version: 1.13.1
API version: 1.26
Go version: go1.7.5
Git commit: 092cba372
Built: Wed Feb 8 06:44:30 2017
OS/Arch: linux/amd64

Server:
Version: 1.13.1
API version: 1.26 (minimum version 1.12)
Go version: go1.7.5
Git commit: 092cba372
Built: Wed Feb 8 06:44:30 2017
OS/Arch: linux/amd64
Experimental: false

I have checked what ports are in use on the laptop host, and these are:

Initiating SYN Stealth Scan at 07:35
Scanning localhost (127.0.0.1) [1000 ports]
Discovered open port 8443/tcp on 127.0.0.1
Discovered open port 4001/tcp on 127.0.0.1
Discovered open port 7001/tcp on 127.0.0.1

Host is up (0.000042s latency).
Not shown: 997 closed ports
PORT STATE SERVICE
4001/tcp open newoak
7001/tcp open afs3-callback
8443/tcp open https-alt

So port 53 is not in use on the local docker host machine.

This indicates that there is something inside the docker all-in-one OpenShift 3.5 container platform that is binding to port 53 before DNS attempts to bind to that default port.

Any idea how to find out why this is happening please?

![openshift-arora-login-1](https://cloud.githubusercontent.com/assets/2807784/26540152/da2b8460-4447-11e7-96ec-9f222dcc03cb.png)

![openshift-arora-login-2](https://cloud.githubusercontent.com/assets/2807784/26540160/e38b770e-4447-11e7-9dea-defcb01c3fd9.png)

![openshift-arora-login-3](https://cloud.githubusercontent.com/assets/2807784/26540164/ee0dc704-4447-11e7-8342-37c95e887a24.png)

[oc-diags-openshift.txt](https://github.com/openshift/origin/files/1034356/oc-diags-openshift.txt)

[oc-jason.txt](https://github.com/openshift/origin/files/1034357/oc-jason.txt)

**Comment by sputnik-1** [comment]
This is running on a 64 bit laptop with Linux Mint Sarah (based on Ubuntu 16.04) installed.

I'm using the following docker version:

spock@laptop ~ $ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba372
 Built:        Wed Feb  8 06:44:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba372
 Built:        Wed Feb  8 06:44:30 2017
 OS/Arch:      linux/amd64
 Experimental: false

I have checked what ports are in use on the laptop host, and these are:

Initiating SYN Stealth Scan at 07:35
Scanning localhost (127.0.0.1) [1000 ports]
Discovered open port 8443/tcp on 127.0.0.1
Discovered open port 4001/tcp on 127.0.0.1
Discovered open port 7001/tcp on 127.0.0.1

Host is up (0.000042s latency).
Not shown: 997 closed ports
PORT     STATE SERVICE
4001/tcp open  newoak
7001/tcp open  afs3-callback
8443/tcp open  https-alt

So port 53 is not in use on the local docker host machine.

This indicates that there is something inside the docker all-in-one OpenShift 3.5 container platform that is binding to port 53 before DNS attempts to bind to that default port.

Any idea how to find out why this is happening please?

**Comment by php-coder** [comment]
One tip that could be helpful in debugging is to run `oc cluser up` with `--loglevel=5`, post its output to pastebin and paste a link here. This particular check for available ports inspect `/proc/net/tcp` and `/proc/net/tcp6` files, so maybe they have data in unexpected format.

CC @csrwng

**Comment by sputnik-1** [comment]
Thanks for that tip php-coder.

Here is the requested log file attached.

[oc-log-level5-start.txt](https://github.com/openshift/origin/files/1035541/oc-log-level5-start.txt)

**Comment by sputnik-1** [comment]
Looking at that log file, I see the following error on line 628: 

I0529 11:13:24.447068   20678 run.go:266] Stderr:                                                               
curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error                           
I0529 11:13:24.447082   20678 run.go:270] Container run successful

**Comment by sputnik-1** [comment]
I was wondering about connecting to the container that runs the internal cluster DNS server, and trying to see why it cannot bind to port 53.

Can somebody tell me the name of the container I need to attach to please?

**Comment by csrwng** [comment]
@sputnik-1 the container is 'origin'

**Comment by csrwng** [comment]
@sputnik-1 I don't believe the issue is with the dns server, given that you only need the numeric ip to use the web console. Does the Arora browser have a way of displaying the javascript console (as in Firefox or Chrome dev tools?) If it does, can you include the log here? Also, have you tried it with a different browser?

**Comment by sputnik-1** [comment]
Hi csrwng,

thanks for the pointer to the container.

I tried with Firefox first, and the login page did not even load then.

**Comment by csrwng** [comment]
@sputnik-1 any chance you can try it with chrome?

**Comment by sputnik-1** [comment]
will do that ASAP

**Comment by sputnik-1** [comment]
OK - rebooted my laptop and restarted the cluster.

Searching the latest logs, I found the following:

   Using 192.168.1.100 as the server IP
-- Starting OpenShift container ... 

   Creating initial OpenShift configuration
I0530 16:01:16.011063    4543 run.go:155] Creating container named ""
config:
  image: registry.access.redhat.com/openshift3/ose:latest
  command:
    start
    --images=registry.access.redhat.com/openshift3/ose-${component}:latest
    --volume-dir=/var/lib/origin/openshift.local.volumes
    --dns=0.0.0.0:8053
    --write-config=/var/lib/origin/openshift.local.config
    --master=192.168.1.100
    --hostname=192.168.1.100

I'm wondering if I can pass the  --dns=0.0.0.0:53 as a parameter to the oc command?

Still need to take a look at this in Chrome.

**Comment by csrwng** [comment]
That command line argument is used to generate the config. We don't expose that argument directly, but you can always change the value by editing the `master-config.yaml` file generated under `$CONFIG_DIR/master`, where `$CONFIG_DIR` is by default `/var/lib/origin/openshift.local.config` on the docker host. (You can also place it in a different location by specifying `--host-config-dir=/your/directory` when starting cluster up). After you edit it, bring the cluster down with `oc cluster down` and then bring it back up with `oc cluster up --use-existing-config` so no new config is generated.

Having said all that, I don't think your issue is with DNS. There is something going on with your browser, since you should not need the internal DNS server to access the web console.

**Comment by sputnik-1** [comment]
Hi csrwng.

You were right - it was a browser issue.

Having restarted the cluster and used chrome everything works as expected.

Please see the attached screenshots to confirm this.

![openshift-chrome-login-ok-1](https://cloud.githubusercontent.com/assets/2807784/26591503/c8252a14-4555-11e7-8df1-3ee2e3a4b82f.png)

![openshift-chrome-login-ok-2](https://cloud.githubusercontent.com/assets/2807784/26591526/d9560164-4555-11e7-8161-50d416b269fc.png)

Thank you for all your help with this guys.

I'll close this now as it's not an issue.

Keith
