### ISSUE TITLE
Infra flake: timeout: aws-up : wait for SSH to be available

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#14397]
provision an AWS EC2 instance.[localhost] aws-up : wait for SSH to be available

Took 10 min.
Error Message: Timeout when waiting for 172.18.12.41:22

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1827/testReport/junit/(root)/provision%20an%20AWS%20EC2%20instance/_localhost__aws_up___wait_for_SSH_to_be_available/

**Comment by stevekuznetsov** [comment]
Some things we really can't help. This is one of them. We could keep this open for re-tests but there's no work to do here.
