### ISSUE TITLE
oc tag command should allow updating just the reference

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#14404]
Currently if I invoke `oc tag` on an existing tag it will scratch entire contents previously available. I'd like to be able to update just the reference definition, but leave the other elements as is. 

This comes from this thread: http://lists.openshift.redhat.com/openshift-archives/users/2017-May/msg00102.html

**Comment by mfojtik** [comment]
@soltysh do we want `--confirm` for this case?

**Comment by soltysh** [comment]
@mfojtik I was rather thinking about `--update` (or alike), since we'll add new functionality, and not to break backwards compatibility. `--confirm` would be when we'd do force update.

**Comment by mfojtik** [comment]
@soltysh `--update` or `--replace` sounds good to me.

**Comment by bparees** [comment]
trello'd https://trello.com/c/7m9SbxfY
