### ISSUE TITLE
DNS service lookup failed for first 5 mins in container

### ISSUE THREAD

**Issue by jagadeeshops** [openshift/origin#14401]
When a container started it failed to resolve the service name for about 3 times in first 5 minutes.
It succeeded in the fourth attempt.
##### Version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v1.4.1
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Occurred only once. Unable to reproduce

##### Additional Information
zookeeper is the service name:

May 25th 2017, 11:29:14.552	maas-consumer-mssql	Caused by: java.net.UnknownHostException: zookeeper: Name does not resolve
May 25th 2017, 11:26:51.673	maas-consumer-mssql	Caused by: java.net.UnknownHostException: zookeeper: Name does not resolve
May 25th 2017, 11:25:56.361	maas-consumer-mssql	Caused by: java.net.UnknownHostException: zookeeper: Name does not resolve

Fourth time it resolved and connected successfully.

/etc/resolv.conf contents:
node ip only

At the same time zookeeper was running. Since its unable to resolve the hostname, Service is up or down doesnt matter.

**Comment by knobunc** [comment]
The networking team owns the networking to get to the DNS service... but not the resolver.  Passing over to the Kube team.

**Comment by jagadeeshops** [comment]
This issue occurs only in one Alpine based java container.  Today again that issue surfaced. But after two to three restarts, Pods settled down

**Comment by jagadeeshops** [comment]
@derekwaynecarr  @knobunc  Can you provide the trouble shooting steps or pointers regarding this issue

**Comment by knobunc** [comment]
I think that the initial request is taking that long to timeout, and then getting marked as offline by dnsmasq and then that server is no longer queried.  Can we get the /etc/resolv.conf from inside the pod, and then we can go from there?  A tcpdump of the dns traffic from inside the pod would give some credence to the theory too.

**Comment by derekwaynecarr** [comment]
@jagadeeshops - is this a single node cluster?  can you handle this with a liveness or readiness check as well?
