### ISSUE TITLE
Branch `ref` in BuildConfig from template stores commit ID and never updates

### ISSUE THREAD

**Issue by InfoSec812** [openshift/origin#14414]
When using a BuildConfig in a template as shown:

```json
    {
      "apiVersion": "v1",
      "kind": "BuildConfig",
      "metadata": {
        "annotations": {
          "openshift.io/generated-by": "OpenShiftNewApp"
        },
        "creationTimestamp": null,
        "labels": {
          "app": "openshift-sonarqube",
          "appName": "sonarqube"
        },
        "name": "openshift-sonarqube"
      },
      "spec": {
        "nodeSelector": null,
        "output": {
          "to": {
            "kind": "ImageStreamTag",
            "name": "openshift-sonarqube:latest"
          }
        },
        "postCommit": {},
        "resources": {},
        "runPolicy": "Serial",
        "source": {
          "git": {
            "uri": "https://github.com/InfoSec812/openshift-sonarqube.git",
            "ref": "${SONAR_CONTAINER_BRANCH}"
          },
          "type": "Git"
        },
        "strategy": {
          "dockerStrategy": {
            "from": {
              "kind": "ImageStreamTag",
              "name": "sonarqube:latest"
            },
            "env": [
              {
                "name": "SONAR_PLUGINS_LIST",
                "value": "${SONAR_PLUGINS_LIST}"
              }
            ],
            "noCache": true
          },
          "type": "Docker"
        },
        "triggers": [
          {
            "github": {
              "secret": "REDACTED"
            },
            "type": "GitHub"
          },
          {
            "generic": {
              "secret": "REDACTED"
            },
            "type": "Generic"
          },
          {
            "type": "ConfigChange"
          },
          {
            "imageChange": {},
            "type": "ImageChange"
          }
        ]
      },
      "status": {
        "lastVersion": 0
      }
    },
```
Upon initially processing the template, OpenShift apparently stores the commit ID and uses that for subsequent builds. This means that if you make changes to that branch, you have to delete the BuildConfig and recreate it so that it will store the updated commit ID. For large templates this can get VERY tedious.

##### Version
```
oc v3.6.0-alpha.1+46942ad
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.example.com:8443
openshift v3.5.5.5
kubernetes v1.5.2+43a9be4
```
##### Steps To Reproduce
1. Create a template which has a BuildConfig which uses a branch/tag reference (e.g. https://github.com/rht-labs/openshift-sonarqube/blob/include-postgresql/sonarqube-template.json)
2. Process and create from that template
3. Make a change to the referenced branch
4. Rebuild from the BuildConfig

##### Current Result
The same source code is used for the second build as is used with the initial build

##### Expected Result
The updated source code from the changed branch should be used.

##### Additional Information
I spent several hours today fighting with this as to WHY it wasn't getting my updated source code from that branch. Very frustrating and not intuitive at all.

**Comment by bparees** [comment]
> Upon initially processing the template, OpenShift apparently stores the commit ID and uses that for subsequent builds. This means that if you make changes to that branch, you have to delete the BuildConfig and recreate it so that it will store the updated commit ID. For large templates this can get VERY tedious.

On every build, Openshift will clone your repo and check out the ref defined in the buildconfig.  If it points to a specific commit, you will always get that commit.  If it points to a branch, you'll get the current content of that branch (if you push new changes to the branch and rerun the build, it will build the new changes).

If you think that's not the behavior you're observing, we can debug further.  For starters i'd like to see the buildconfig that was created from your template (ie what ref value got filled in?).  We don't store your source code, so there's no way we are using the previous code in a subsequent build.

Openshift does store the actual commit that got build, in the revision field of the build object, but that's for the specific build and is not relevant to what happens when you run a new build from the buildconfig.

Also are you sure you're rebuilding from the buildconfig?  If you selected to rebuild from an existing build, then yes that is the behavior you'll see because you've asked the system to rerun exactly that build, meaning exactly the same commit level/etc.  What you want is to start a new build from the buildconfig, not rerun a build from an existing build.

**Comment by InfoSec812** [comment]
The behavior I am seeing is as described above. In order for the new code to get picked up I have to completely delete the project and re-provision from template. As requested, the resultant BuildConfig is below:

```
{
    "apiVersion": "v1",
    "kind": "BuildConfig",
    "metadata": {
        "annotations": {
            "openshift.io/generated-by": "OpenShiftNewApp"
        },
        "creationTimestamp": "2017-05-31T23:32:32Z",
        "labels": {
            "app": "openshift-sonarqube",
            "appName": "sonarqube"
        },
        "name": "openshift-sonarqube",
        "namespace": "sonarqube",
        "resourceVersion": "3654996",
        "selfLink": "/oapi/v1/namespaces/sonarqube/buildconfigs/openshift-sonarqube",
        "uid": "6b84b59a-4659-11e7-8877-fa163e90c4fc"
    },
    "spec": {
        "nodeSelector": null,
        "output": {
            "to": {
                "kind": "ImageStreamTag",
                "name": "openshift-sonarqube:latest"
            }
        },
        "postCommit": {},
        "resources": {},
        "runPolicy": "Serial",
        "source": {
            "git": {
                "ref": "include-postgresql",
                "uri": "https://github.com/InfoSec812/openshift-sonarqube.git"
            },
            "type": "Git"
        },
        "strategy": {
            "dockerStrategy": {
                "env": [
                    {
                        "name": "SONAR_PLUGINS_LIST",
                        "value": "findbugs pmd ldap buildbreaker github gitlab"
                    }
                ],
                "from": {
                    "kind": "ImageStreamTag",
                    "name": "sonarqube:latest"
                }
            },
            "type": "Docker"
        },
        "triggers": [
            {
                "github": {
                    "secret": "tu5UyJNNhAyxXYrcnDTZ"
                },
                "type": "GitHub"
            },
            {
                "generic": {
                    "secret": "xhUU0WVDG3eA2Yu89zGe"
                },
                "type": "Generic"
            },
            {
                "type": "ConfigChange"
            },
            {
                "imageChange": {
                    "lastTriggeredImageID": "sonarqube@sha256:d5f7bb8aecaa46da054bf28d111e5a27f1378188b427db64cc9fb392e1a8d80a"
                },
                "type": "ImageChange"
            }
        ]
    },
    "status": {
        "lastVersion": 1
    }
}
```

**Comment by bparees** [comment]
> The behavior I am seeing is as described above. 

i described two behaviors.

how are you launching the subsequent build?

**Comment by bparees** [comment]
can't recreate and insufficient information to continue diagnosing, please comment back if you want to continue investigating this.
