### ISSUE TITLE
Set Trigger Doesn't Allow Alternate Namespace

### ISSUE THREAD

**Issue by duffenterprises** [openshift/origin#14421]
Using oc set trigger doesn't provide a mechanism to set the namespace to an alternate namespace than the one you are working in.  This functionality is desired for when the ImageStream exists in one namespace, but not the targeted namespace (e.g. DEV/TEST)

Executing the following command within the namespace auth-svc-dev
`oc set triggers dc/auth-svc-dev  --from-image=auth-svc-dev/auth-svc:priceless_morse --containers=auth-svc-dev`

Results in the following changes to the deployment config and a re-deployment:
```code
type: ImageChange  
      imageChangeParams:  
        automatic: true
        containerNames:
          - auth-svc-dev
        from:
          kind: ImageStreamTag
          namespace: auth-svc-dev
          name: 'auth-svc:priceless_morse'
        lastTriggeredImage: >-
          10.x.x.x:5000/auth-svc-dev/auth-svc@sha256:1d194efdf8a09f96afc7099b65023eec3e45d6b93c655de17cb7aa56e50d9107
```
Executing the command within the namespace auth-svc-test
`oc set triggers dc/auth-svc-test--from-image=auth-svc-dev/auth-svc:priceless_morse --containers=auth-svc-test`

Results in the following changes to the deployment config but no re-deployment:

```code
type: ImageChange  
      imageChangeParams:  
        automatic: true
        containerNames:
          - auth-svc-test
        from:
          kind: ImageStreamTag
          namespace: auth-svc-test
          name: 'auth-svc:priceless_morse'
```

The suspicion is that the re-deployment doesn't initiate because auth-svc:priceless_morse doesn't exist in the namespace auth-svc-test. Is there a mechanism of using `oc set trigger` if the image stream exists in another namespace.

##### Version

```code
kduffy@utah:~/openshift_client_tools$ oc version
oc v3.5.5.15
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.5.5.8
kubernetes v1.5.2+43a9be4

```

**Comment by tnozicka** [comment]
@mfojtik you fixed this reacently, right?
