### ISSUE TITLE
Template broker sends `service-instances` instead of `service_instances` in parameter schemas object

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#14439]
The template broker is sending the following parameters using the following JSON:

```
      "schemas": {
       "service-instances": {
        "create": {
         "parameters": {
            ...
```

But the service catalog is expecting `service_instances` instead:

https://github.com/kubernetes-incubator/service-catalog/blob/97d278a41eee2bf81896f2d1359c8ba6b66fa0c2/pkg/brokerapi/schemas.go#L22

This prevents the catalog from adding the parameter schema to the service class.

##### Version

oc v3.6.0-alpha.1+0bea328-833
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.1+1bf8a17-976
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Enable template broker in master-config.yaml
2. Run pkg/template/servicebroker/test-scripts/catalog.sh and view the output

cc @jim-minter @pmorie @jwforres @bparees

**Comment by jim-minter** [comment]
ick, good catch, thanks
