### ISSUE TITLE
How can I build by using a persistent_storage

### ISSUE THREAD

**Issue by calmking** [openshift/origin#14449]
Is anybody knows how I can add a persistent volume to the buildConfig. I have some thing locally, cannot build from the remote url, etc.  I've looked for all docs ,but not found at all.
##### Version
`oc v1.5.0
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.5.0
kubernetes v1.5.2+43a9be4
`
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. create a buildconfig
2. startbuild

Thanks .

**Comment by pweil-** [comment]
adding volumes to build pods is a feature being tracked here: https://trello.com/c/NnMBJybJ

**Comment by calmking** [comment]
@pweil- Thank you  very much!
