### ISSUE TITLE
Build stuck in the status New

### ISSUE THREAD

**Issue by fesenko** [openshift/origin#14452]
I created a new project which consists of one Node.js app. When open the page Build I see there a build stuck in the status New with the following details:

```
Status: New
Started: not started
Duration: waiting for 5 hours
Triggered by: Build configuration change
```

There is no logs, just a blank page.

```
oc get builds
NAME        TYPE      FROM         STATUS    STARTED   DURATION
nodeapp-1   Source    Git@master   New
```

```
oc describe build
Name:		nodeapp-1
Namespace:	test-openshift
Created:	7 minutes ago
Labels:		app=nodeapp
		buildconfig=nodeapp
		openshift.io/build-config.name=nodeapp
		openshift.io/build.start-policy=Serial
Annotations:	openshift.io/build-config.name=nodeapp
		openshift.io/build.number=1

Status:		New
Duration:	waiting for 7m13s
Build Config:	nodeapp
Build Pod:	nodeapp-1-build

Strategy:	Source
URL:		https://github.com/openshift/nodejs-ex.git
Ref:		master
From Image:	DockerImage openshift/nodejs-010-centos7@sha256:bd971b467b08b8dbbbfee26bad80dcaa0110b184e0a8dd6c1b0460a6d6f5d332
Output to:	ImageStreamTag nodeapp:latest
Push Secret:	builder-dockercfg-3w48f

Build trigger cause:	Build configuration change

No events.
```

```
oc describe pod nodeapp-1-build
Error from server: pods "nodeapp-1-build" not found
```

```
oc logs build/nodeapp-1
Error from server: unable to wait for build nodeapp-1 to run: received unknown object while watching for builds
```

The issue is with Build only. I have a few applications running and I can increase the number of pods in their deployments without any issue.

##### Version
openshift v1.3.1
kubernetes v1.3.0+52492b4
etcd 2.3.0+git

**Comment by fesenko** [comment]
Turned out that it might take really long for build to start, i. e. transit from New to Running state. I'm still not sure what's causing it.

**Comment by bparees** [comment]
There was a bug that I think affected the 1.3.x release in which if you had a lot of old builds, it could take a while to start a new build.  Do you have a large number of old(terminated/completed) builds (regardless of what buildconfig they are associated with) in your cluster?

If so, try pruning them.

**Comment by bparees** [comment]
(the bug was fixed in 1.4)

**Comment by fesenko** [comment]
@bparees, thanks a lot.

**Comment by luckyycool** [comment]
It is never fixed, my build is waiting to start from 8 hours...I have tried deleting and creating again from last 1 week, nothing worked.

**Comment by bparees** [comment]
@luckyycool there are many possible causes of that.  If you would like some assistance resolving your issue, which is almost certainly different than what was resolved here, please open a new issue and provide:

1) your cluster version
2) your buildconfig yaml
3) your build object yaml
4) any other useful steps to recreate your issue.

typical causes include your build referencing an imagestreamtag that does not exist.

I won't reply on this closed issue again.

**Comment by luckyycool** [comment]
@bparees I understand what you are saying...I have created account last week only.  And I am just trying to  run first app by creating a nodejs app from it's own github link..no custom code /setup modification.

**Comment by HloniT** [comment]
I  have created and account now only. And I am just trying to run first app by creating a nodejs app from it's own github link..no custom code /setup modification. the build is not starting, what am I doing wrong?

**Comment by adambkaplan** [comment]
@HloniT is this on an OpenShift Online cluster?

**Comment by gsimon75** [comment]
The [OKD doc](https://docs.okd.io/latest/architecture/core_concepts/builds_and_image_streams.html#pipeline-build) says that

> The first time a project defines a build configuration using a Pipeline strategy, OKD instantiates a Jenkins server to execute the pipeline. Subsequent Pipeline build configurations in the project share this Jenkins server.

On the other hand, the [Openshift Online doc](https://docs.openshift.com/online/using_images/other_images/jenkins.html#jenkins-creating-jenkins-service-from-template) suggest to explicitely start Jenkins by either `oc new-app jenkins-persistent` or `oc new-app jenkins-ephemeral`.

My buildconfig was also stuck, but manually starting a persistent Jenkins solved it, and the build took about 3 minutes to start.

**Comment by bparees** [comment]
@gsimon75 what version of Openshift are you on?  Openshift v4 no longer auto-instantiates jenkins for you.

The v4 docs are here:  https://docs.openshift.com/container-platform/4.1/welcome/index.html

There is technically no "OKD4" yet, so the okd docs are reflecting 3.x behavior.

**Comment by gsimon75** [comment]
> what version of Openshift are you on?

I'm on Openshift Online, so it's v3 and it indeed doesn't instantiate Jenkins implicitely.

So when I forgot to do that manually, the symptoms were exactly the same as @fesenko experienced: no progress, builds stuck at 'new' (and an intense feeling of a great disturbance in the Force :) ).

That's why I thought it's worth a note, so if someone finds this issue by searching for the symptoms (like @HloniT ), a quick check on Jenkins can easily catch this trivial mistake, before going into those more sophisticated possibilities.

**Comment by bparees** [comment]
> I'm on Openshift Online, so it's v3 

fyi We do have v4 Online cluster available now.

v3 is being phased out as users roll off.

**Comment by kuhlaid** [comment]
I was having the same issue and it depends on where you look for logs. While the CLI may be unhelpful, the web console may be throwing errors in the developer or admin console. The best place to look seems to be the events for the entire project in the web console and NOT in the pod or build itself, if something if hanging the build. My problems were coming from an app I was trying reinstall from scratch, but had not deleted all of the related resource objects from the previous install.
