### ISSUE TITLE
oc apply with --selector results in error "object does not implement the Object interfaces"

### ISSUE THREAD

**Issue by oweise** [openshift/origin#14450]
We are trying to process a template into a list YML and then use "oc apply" to either create or update the entities described there. We would like to use the "--selector" parameter to choose which entities are actually created.

However on every occasion calling "oc apply --selector" produces the following error:

error: object does not implement the Object interfaces

This even happens with an empty list YML without any items, like this one:

apiVersion: v1
items:
kind: List
metadata: {}

##### Version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.99.100:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. Create list.yml with the contents described above
2. Use: oc apply --selector="somelabel=somevalue" -f list.yml

##### Current Result
Cancels with error:
error: object does not implement the Object interfaces

##### Expected Result
Tries to apply the contained items in the list YML that match the label selector. In that case: None.

##### Additional Information
This is currently tried using Minishift 1.0 installation and the provided oc client.
Diagnostics and current workspace do not seem related. Please inform me if you need any more information.

**Comment by chenleji** [comment]
Is this a k8s issue? I found this issue on k8s v1.7.3.

**Comment by tinexw** [comment]
/reopen

This issue still exists. The selector cannot be applied to a list, just to objects. 

I want to create objects from a template by processing the template, piping the output to oc apply and pruning everything matching a certain label: 

`` oc process -f <filename> | oc apply --prune -l foo=bar -f -``

This works if I don't use the template but store all object configurations in a directory.
