### ISSUE TITLE
Openshift nodes can't talk to each other

### ISSUE THREAD

**Issue by do3cc** [openshift/origin#14455]
We have set up a basic openshift cluster on 4 virtual machines with the ansible scripts.
From the router pod I can only reach pods when they are on the same node.

I followed the debugging guide from the documentation but did not find anything obvious.

##### Version
oc v1.5.0
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://os-master.itiso.net:8443
openshift v1.5.0
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. connect to pod on node A
2. curl a ip from a pod on node B

##### Current Result
```
sh-4.2# curl -vk 10.128.0.9
* About to connect() to 10.128.0.9 port 80 (#0)
*   Trying 10.128.0.9...
* No route to host
* Failed connect to 10.128.0.9:80; No route to host
* Closing connection 0
curl: (7) Failed connect to 10.128.0.9:80; No route to host
```
##### Expected Result
I get some helpful information (given something would listen on port 80)

##### Additional Information

[openshift-sdn-debug-2017-06-02.tgz.zip](https://github.com/openshift/origin/files/1047990/openshift-sdn-debug-2017-06-02.tgz.zip)

**Comment by knobunc** [comment]
Does 'oadm diag NetworkCheck' say anything usedul?

**Comment by do3cc** [comment]
```
[root@os-master ~]# oadm diagnostics NetworkCheck
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/root/.kube/config'

[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint

ERROR: [DNet2007 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:141]
       timed out waiting for the condition

[Note] Summary of diagnostics execution (version v1.5.0):
[Note] Errors seen: 1
```
I have used the weekend to learn about openflow and openvswitch to debug understand this a bit petter.

**Comment by do3cc** [comment]
I managed to stop most pods so that I only see the traffic I am generating.
I am pinging from the pod on one node to the other.
On the source node, the last openflow rule that gets applied is this:
```
table=50, n_packets=2351433, n_bytes=98760186, priority=100,arp,arp_tpa=10.128.0.0/23 actions=move:NXM_NX_REG0[]->NXM_NX_TUN_ID[0..31],set_field:146.108.41.59->tun_dst,output:1
```

On the receiving end, the page gets dropped in this table:
```
Every 2.0s: ovs-ofctl -O OpenFlow13 dump-flows br0 | sed -e "s/^....................................//" | grep table=10                                                                                                                                                                                                                            Fri Jun 16 10:02:17 2017

table=10, n_packets=0, n_bytes=0, priority=100,tun_src=146.108.41.55 actions=goto_table:30
table=10, n_packets=0, n_bytes=0, priority=100,tun_src=146.108.41.53 actions=goto_table:30
table=10, n_packets=0, n_bytes=0, priority=100,tun_src=146.108.41.54 actions=goto_table:30
table=10, n_packets=3287058, n_bytes=138060188, priority=0 actions=drop
table=100, n_packets=815699, n_bytes=86959163, priority=0 actions=output:2
```

I did not see a rule where the tun_src became the IP of the node, I guess it still has the IP of the POD, but I have to catch a package yet.

**Comment by do3cc** [comment]
After catching the packet with tcpdump I noticed that the ip packet does not have the IP of the POD but another IP. Same subnet as the node, but different host part.
After this I realized that my nodes got a static IP configured but networkmanager assigned a dynamic IP too. outgoing packets had the dynamically assigned IP and because of that the openvswitch dropped the packet.
After reconfiguring the nodes so that nm does not assign dynamic IPs any more, the pods can talk cross node.

So problem on my side.

Thanks @knobunc for having a look at this ticket!

**Comment by knobunc** [comment]
@do3cc glad you got to the bottom of it.

**Comment by priyanka5** [comment]
@do3cc - I am facing  same issue recently with my openshift installation , where I am not able to reach docker-registry from other nodes and it gives "no route to host" error . I tried SDN debugging but that doesnt help. Could you please help me how you solved the issue as disabling network manager also doesn't work for me. Thanks

**Comment by azimovMichael** [comment]
@do3cc Can you please explain in more detail how you debugged the traffic between the pods?
Having the same issue..

**Comment by do3cc** [comment]
@azimovMichael 
See the ovs-ofctl command from https://github.com/openshift/origin/issues/14455#issuecomment-308962217
For seeing the traffic. The command to get the output in the first code comment, I forgot. I learned openflow commands for this debugging but didn't use it again since then and forgot most of it.
