### ISSUE TITLE
how can I add incremental in imagestream build template？

### ISSUE THREAD

**Issue by myonlyzzy** [openshift/origin#14464]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]

I want know  if I  create a is in openshift namespace。 Openshift will provide a  default template for use。but the default template I don,t know where .and i want use default template build docker images use incremental . where can I should motify .

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by pweil-** [comment]
@myonlyzzy I don't understand this question.  An image stream and a template are different things.  An image stream provides an image that can be referenced in a spec (could be in a template).  A template provides a set of a objects that will be created when the template is instantiated.  One of those objects may contain a spec that points to an image stream.

Please clarify what you're trying to accomplish.  Thanks!

**Comment by mfojtik** [comment]
Yeah, I don't understand the question either. Can you please provide more info about what you are trying to do? Are you trying to to make a build config with incremental=true ?

**Comment by mfojtik** [comment]
Closing since we lack the answer. Please feel free to re-open if this is still an issue.
