### ISSUE TITLE
liveness probe from route causes TLS errors in Elasticsearch

### ISSUE THREAD

**Issue by richm** [openshift/origin#14463]
I have created a reencrypt route for an Elasticsearch service like this:
```
apiVersion: v1
kind: Route
metadata:
 name: logging-es
 namespace: logging
spec:
 host: es.openshiftdevel
 tls:
   caCertificate: |
     -----BEGIN CERTIFICATE-----
MIIC2jCCAcKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAeMRwwGgYDVQQDExNsb2dn
...

     -----END CERTIFICATE-----
   destinationCACertificate: |
     -----BEGIN CERTIFICATE-----
MIIC2jCCAcKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAeMRwwGgYDVQQDExNsb2dn
...

   termination: reencrypt
 to:
   kind: Service
   name: logging-es
   weight: 100
 wildcardPolicy: None
```

It looks like the router has some sort of readiness or liveness probe for this route that runs every 10 seconds or so, that hits https://host:port.  I'm getting the following errors in my Elasticsearch log because of this.  I'm sure it is the router, based on incoming IP, and the fact that this error goes away if I delete the route:
```
[2017-06-02 20:57:53,070][ERROR][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [Ego the Living Planet] SSL Problem illegal change cipher spec msg, conn state = 6, handshake state = 1
javax.net.ssl.SSLException: illegal change cipher spec msg, conn state = 6, handshake state = 1
       at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
```
##### Version
latest devenv:
openshift v3.6.0-alpha.1+dcf2e0c-997
kubernetes v1.6.1+5115d708d7
etcd 3.1.0

##### Steps To Reproduce
1. install origin-aggregated-logging
2. create a reencrypt route to Elasticsearch

##### Current Result
See these errors every 10 seconds in the Elasticsearch pod logs:
```
[2017-06-02 20:57:53,070][ERROR][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [Ego the Living Planet] SSL Problem illegal change cipher spec msg, conn state = 6, handshake state = 1
javax.net.ssl.SSLException: illegal change cipher spec msg, conn state = 6, handshake state = 1
       at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
...
```

##### Expected Result
No errors

##### Additional Information
I can help set up logging if that helps.

**Comment by knobunc** [comment]
Yes, the router does health checking at a 5 second interval by default.

You can set the route annotation router.openshift.io/haproxy.health.check.interval or the router environment variable ROUTER_BACKEND_CHECK_INTERVAL to change it per route, or globally (respectively).

The format is a number and a unit (us, ms, s, m, h, d).

There's currently no way to disable the checking, but you can set it to something really long (1000d) to reduce the log spam.

We just enable the tcp check:
  https://www.haproxy.com/doc/aloha/7.0/haproxy/healthchecks.html#checking-a-tcp-port

And that does a tcp handshake then drops the connection.  That must be confusing the ssl implementation you are using.

**Comment by richm** [comment]
Elasticsearch is a Java application - it's using the regular Java TLS stack - I would be surprised if we don't see this with other Java applications - should I file a bug directly against haproxy?

**Comment by knobunc** [comment]
No, you can configure other types of health checks...  so we could set it up so that we do ssl checks instead:
  https://www.haproxy.com/doc/aloha/7.0/haproxy/healthchecks.html#checking-a-ssl-port

So it's really a feature request against Origin I guess.

**Comment by lukas-vlcek** [comment]
//cc @josefkarasek

**Comment by richm** [comment]
@knobunc Then should I reopen this issue, or open a new one?

**Comment by richm** [comment]
I went ahead and opened a new issue https://github.com/openshift/origin/issues/14515
