### ISSUE TITLE
Question:  how can i find object owner in openshift?

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#14465]
I would like to find out the owner of the object (who created/triggered  an object)  how can i do it in openshift?   k8s seems to have something called as `metadata/ownerReferences`

**Comment by kargakis** [comment]
Same way for Openshift - owner refs should be added in all parent objects by 3.6.

cc: @mfojtik

**Comment by debianmaster** [comment]
thank you!  that's all i needed.
