### ISSUE TITLE
github.com/openshift/origin/test/cmd/describe.test/cmd/describer.sh:16: executing 'eventnum=$(oc get events | wc -l) && [[ $eventnum -gt 1 ]]' expecting success

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14479]
```
=== BEGIN TEST CASE ===
test/cmd/describer.sh:16: executing 'eventnum=$(oc get events | wc -l) && [[ $eventnum -gt 1 ]]' expecting success; re-trying every 0.2s until completion or 60.000s
FAILURE after 59.558s: test/cmd/describer.sh:16: executing 'eventnum=$(oc get events | wc -l) && [[ $eventnum -gt 1 ]]' expecting success; re-trying every 0.2s until completion or 60.000s: the command timed out
Standard output from the command:
Standard error from the command:
No resources found.
... repeated 45 times
=== END TEST CASE ===
```

in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_check/2812/

**Comment by juanvallejo** [comment]
cc @fabianofranz

**Comment by juanvallejo** [comment]
@bparees I have not yet been able to reproduce this flake locally. Could it be that the command in [describer.go#L15](https://github.com/openshift/origin/blob/master/test/cmd/describer.sh#L15) took too long / hanged?

**Comment by bparees** [comment]
i don't think so, it looks like it retried 45 times and never got the output it was looking for, before giving up.  (it never found any events).

so the underlying issue, presumably, is that the events this test expected to see were not actually created for some reason.
