### ISSUE TITLE
Cobra is eating the first argument when it matches the first original argument

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1447]
https://github.com/openshift/origin/pull/1446 added an "admin" sub command, which coincidentally is a common first argument for policy addition.  It exposes a bug in cobra:

    openshift admin policy add-user admin anypassword:adduser -n ui-test-project

returns arguments ["anypassword:adduser"] instead of ["admin", "anypassword:adduser"], so it looks like Cobra is getting confused and eating the first arg.  Needs to be fixed.

**Comment by fabianofranz** [comment]
Fixed in https://github.com/openshift/origin/pull/1901

**Comment by fabianofranz** [comment]
@smarterclayton this is fixed, please close.
