### ISSUE TITLE
oc cluster up with latest Docker CE

### ISSUE THREAD

**Issue by bobbydeveaux** [openshift/origin#14481]
When running `oc cluster up` with the latest version there is an error: "{"message":"starting container with non-empty request body was deprecated since v1.10 and removed in v1.12"}
"

##### Version
oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

docker version

Client:
 Version:      17.06.0-ce-rc1
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 02:56:01 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce-rc1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 03:00:14 2017
 OS/Arch:      linux/amd64
 Experimental: true

##### Steps To Reproduce
1. $ oc cluster up

##### Current Result
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... 
   WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ... 
   Pulling image openshift/origin:v1.5.1
   Pulled 0/3 layers, 5% complete
   Pulled 1/3 layers, 80% complete
   Pulled 2/3 layers, 83% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... FAIL
   Error: Cannot get TCP port information from Kubernetes host
   Caused By:
     Error: cannot start container 2d527ef5d905fb4733ac552d45295942f330343256e1524fa5d739dd8c88380e
     Caused By:
       Error: API error (400): {"message":"starting container with non-empty request body was deprecated since v1.10 and removed in v1.12"}

##### Expected Result
expect open shift to be up and running 

##### Additional Information
this worked before updating to the latest docker version. But it looks like something OpenShift should support/be aware of

**Comment by php-coder** [comment]
CC @csrwng

**Comment by bparees** [comment]
@csrwng this is fixed, right?

**Comment by csrwng** [comment]
Yes, v3.6.0-alpha.2 of cluster up works with the latest Docker CE version
