### ISSUE TITLE
Allow limitCPUToMemoryPercent to be decimal

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#14484]
Currently limitCPUToMemoryPercent is only allowed to be an integer. It'd be nice to be able to use a decimal like 37.5% as it'll result in cleaner output

ie. I want to get 3/8 
1024 * 37.5% = 384

However the closest I can get is 37 or 38
1024 * 37 = 378.88
1024 * 38 = 389.12

**Comment by derekwaynecarr** [comment]
i am just curious why you chose 1024 as the example since 1 core = 1000m?

**Comment by andrewklau** [comment]
I'm looking at the memory -> CPU ratio, so my 1024 came from 1024MiB

**Comment by derekwaynecarr** [comment]
makes sense, sorry for being slow.
