### ISSUE TITLE
oc set image is missing examples utilizing --source

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14487]
Since we are changing the default behavior of the upstream command, we should at least provide examples with the involved flag (--source)

@mfojtik

**Comment by mfojtik** [comment]
@kargakis @smarterclayton how about instead of updating the example create the image stream when using oc set image with something that does not exists?

**Comment by mfojtik** [comment]
so:

```
$ oc set image deployments,rc nginx=nginx:1.9.1
```

Will automatically create the "nginx" image stream and import the tags and then set the image to point to that tag? Guess we want to promote the IS more. Or we can tell users how to create/import the image stream as part of the error.

**Comment by smarterclayton** [comment]
I don't know that set image should create image streams - fairly
concerned about complexity here.

**Comment by mfojtik** [comment]
@smarterclayton maybe suggesting to create the image stream will do, basically all the examples set image provides are upstream and does not work ootb in origin (because we default to istag)

**Comment by bparees** [comment]
@kargakis @mfojtik why is "oc set image dc/foo" defaulting to assume the value is an imagestreamtag?  shouldn't it assume it's a docker image, just like it would be in upstream?

**Comment by smarterclayton** [comment]
Yeah, I think we should assume --source=docker by default, not
--source=imagestreamtag.  It's confusing for upstream users.

**Comment by kargakis** [comment]
sgtm

**Comment by bparees** [comment]
Next question:  is this something we can change today w/o breaking compatibility?
