### ISSUE TITLE
create an `oc watch-build` command (or something like that) to watch local source code for changes and trigger builds

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#14492]
so its kinda like the watching in Draft; so folks can create a new app, get local source, edit the source and have `oc` keep rebuilding & deploying as the code changes.

the first cut of this command could be super simple, just waiting for files to change and running
```
oc start-build mybuild --from-dir .
```
but then more advanced implementations could:
* detect what files to watch automatically - maybe using extra metadata on the BuildConfig / S2I image to figure out what files need to be watched (versus ignored) and avoid rebuilding unless real changes are required
* over time integrate the more RAD / rapid approaches to get faster feedback without doing a full S2I rebuild like this: https://blog.openshift.com/fast-iterative-java-development-on-openshift-kubernetes-using-rsync/

Via eclipse tooling we've something kinda like this; but it'd be nice to have a CLI option thats IDE / editor agnostic that over time can be tuned to work faster for different languages/builders

**Comment by sspeiche** [comment]
Yes, something like 

```
oc start-build mybuild --from-dir . --watch
```

Would be handy.  I made it [a card too](https://trello.com/c/B7HJbvIy/1237-oc-watch-local).
For additional reference, the JBoss Developer Studio feature is [blogged about here](https://developers.redhat.com/blog/2017/04/10/develop-and-deploy-on-openshift-next-gen-using-red-hat-jboss-developer-studio/) as well.

**Comment by jstrachan** [comment]
@sspeiche sounds good yeah. I wonder if we may want an `oc watch-build` some day so we can add extra CLI arguments about what patterns of files to watch and what watch mode we need (e.g. rebuilding on change versus in the more incremental updates to running containers etc)

**Comment by sspeiche** [comment]
@jstrachan agree it would be good to have a streamlined experience and performs well

**Comment by gabemontero** [comment]
with card present on devexp board per our process closing this out
