### ISSUE TITLE
Untar error on re-exec cmd: fork/exec /proc/self/exe: cannot allocate memory

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#14496]
```
++ Building go targets for linux/amd64: test/extended/extended.test
hack/build-go.sh took 406 seconds
[INFO] Starting 'networking' extended tests
[INFO] [CLEANUP] Cleaning up temporary directories
[INFO] Building docker-in-docker images
Building container images
Sending build context to Docker daemon  38.4 kB

Error response from daemon: Untar error on re-exec cmd: fork/exec /proc/self/exe: cannot allocate memory
[ERROR] PID 1933: hack/dind-cluster.sh:276: `${DOCKER_CMD} build -t "${image_name}" .` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/dind-cluster.sh:276: `${DOCKER_CMD} build -t "${image_name}" .`
[INFO] 		  2: hack/dind-cluster.sh:266: build-image
[INFO] 		  3: hack/dind-cluster.sh:372: build-images
[INFO]   Exiting with code 1.
[ERROR] PID 18804: test/extended/networking.sh:350: `${CLUSTER_CMD} build-images` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: test/extended/networking.sh:350: `${CLUSTER_CMD} build-images`
[INFO]   Exiting with code 1.
/data/src/github.com/openshift/origin/hack/lib/log/system.sh: line 31:  1927 Terminated              sar -A -o "${binary_logfile}" 1 86400 > /dev/null 2> "${stderr_logfile}"
[ERROR] PID 18748: test/extended/networking-minimal.sh:6: `NETWORKING_E2E_MINIMAL=1 "${OS_ROOT}/test/extended/networking.sh"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: test/extended/networking-minimal.sh:6: `NETWORKING_E2E_MINIMAL=1 "${OS_ROOT}/test/extended/networking.sh"`
[INFO]   Exiting with code 1.
```
Seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_networking_minimal/2840/consoleFull

**Comment by php-coder** [comment]
CC @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@smarterclayton did our build requirements for memory go up again?

**Comment by smarterclayton** [comment]
I think that's a different error?

**Comment by stevekuznetsov** [comment]
Ah, right -- image build. Would `imagebuilder` have higher requirements than `docker build`?

**Comment by smarterclayton** [comment]
Doubt it unless there's some actual pressure on the node.  Could be docker
blows up and is taking all the memory

On Jun 6, 2017, at 4:47 PM, Steve Kuznetsov <notifications@github.com>
wrote:

Ah, right -- image build. Would imagebuilder have higher requirements
than docker
build?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/14496#issuecomment-306612129>,
or mute the thread

**Comment by miminar** [comment]
Hit this as well in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/1995/consoleFull#61010783358b6e51eb7608a5981914356

**Comment by enj** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_networking_minimal/3002/consoleFull#-14129110435898c58db7602c31c0eab717

**Comment by stevekuznetsov** [comment]
Once https://github.com/openshift/origin/pull/14522 lands I am interested to see if the problem remains with `imagebuilder` -- currently, the networking builds are the only "real" `docker build` invocations we have remaining in the CI

**Comment by stevekuznetsov** [comment]
OK, we haven't seen this since introducing https://github.com/openshift/origin/pull/14522
