### ISSUE TITLE
Deleted LDAP user won't reclaim identity

### ISSUE THREAD

**Issue by i0x4b** [openshift/origin#14506]
Strange issue, this may just be my screw up: I set up LDAP authentication against Active Directory which works fine. No issues on that end, tested with multiple users. However, I deleted one of the users using "oc delete user <username>", which, as expected - removed the user. It's still present in Active Directory obviously, and it works elsewhere.

However, I can no longer authenticate in OpenShift using the user. I assume this is intended behaviour, but is there a way to reverse the deletion without restoring a snapshot of the VM it runs on? Currently the log returns the following, sanitized:

 Error authenticating "<username>" with provider "<domain service>": users "<username>" not found

It works for other users where we haven't deleted it, and to make sure it wasn't just my user, I did the same to another one to test - same issue present.

##### Version
oc version
oc v3.5.5.15

##### Steps To Reproduce
1. Set up LDAP authentication
2. Log in with user so it's claimed
3. Delete user using "oc delete user <username>"
4. Attempt to log in, it will fail with: Error authenticating "<username>" with provider "<domain service>": users "<username>" not found

##### Current Result
Cannot log in.

##### Expected Result
Expected LDAP provider to reclaim the username if it was active / allowed by the logon filter.

**Comment by i0x4b** [comment]
After diving into the documentation a bit more, I finally found the "oc delete identity" command - using this resolved it. I somehow overlooked it when taking a gander.

**Comment by vitruxv** [comment]
I have the same issue but when I run the command it just says the user is not found.
