### ISSUE TITLE
HTTPoxy in haproxy

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#14516]
Perhaps it would be ideal to add the patch for https://httpoxy.org/ in the default haproxy template?

**Comment by pweil-** [comment]
@knobunc raising this so it can be triaged down if necessary but blocks by default.

@rajatchopra FYI

**Comment by rajatchopra** [comment]
Should do it on per route basis using annotations.

**Comment by simo5** [comment]
@rajatchopra why is it not sufficient to just add it to the config template ?

**Comment by knobunc** [comment]
I vote for just blocking it.  What's the use-case that we would break?

**Comment by knobunc** [comment]
I entered https://bugzilla.redhat.com/show_bug.cgi?id=1469633

**Comment by knobunc** [comment]
This is not a release blocker, people can replace the router template today to work around it.

**Comment by simo5** [comment]
@knobunc ok if I prepare a patch that changes the template to unconditionally block the proxy header in requests ?

**Comment by eparis** [comment]
@simo5 go for it.

**Comment by simo5** [comment]
Please check if this PR looks like enough. Or do we have some other way to configure Haproxy ?

**Comment by rajatchopra** [comment]
That PR should do it. But I am not sure of the unconditional stripping. That's a blanket hammer on all routes. Making it per route (per backend in haproxy config) would mean that some routes can opt out of it if they want (though I cannot think of that use case).

**Comment by eparis** [comment]
how hard would it be to make it default to strip per route, but allow someone to explicitly NOT strip?

**Comment by rajatchopra** [comment]
fairly straightforward I guess.. use an annotation: 
if ( route.annotation("I_WANT_THAT_HEADER") == "" ) {  http-request del-header.. }

My unverified assumption is that haproxy honours the http-request argument within the backend (the docs say its supported iirc)

**Comment by knobunc** [comment]
I still think the right answer is to define a new env for this, say "ROUTER_STRIP_HEADERS" and then have it be a list of space separated headers to drop.  Then we just loop over that and add in the drop lines.  We would default it to "Proxy" and if the user didn't want that, they can set the string to empty.
