### ISSUE TITLE
`oc cluster up' fails with Error: Cannot get TCP port information from Kubernetes host

### ISSUE THREAD

**Issue by VojtechVitek** [openshift/origin#14512]
I wanted to start OpenShift cluster directly using my Docker for Mac. (I'd like to avoid having minishift / additional VM).

##### Version
```
$ oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

$ docker version
Client:
 Version:      17.06.0-ce-rc1
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 02:56:01 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce-rc1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 03:00:14 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

##### Steps To Reproduce
- Install Docker for Mac.
- Run `oc cluster up`

##### Current Result
```
$ oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ...
   WARNING: Cannot verify Docker version
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.1 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... FAIL
   Error: Cannot get TCP port information from Kubernetes host
   Caused By:
     Error: cannot start container eb890a1e31e02b53cefe1a14d23dba1f90f979685980dc1b64a0db50efd4822c
     Caused By:
       Error: API error (400): {"message":"starting container with non-empty request body was deprecated since v1.10 and removed in v1.12"}
```

### starting container with non-empty request body was deprecated since v1.10 and removed in v1.12
Seems like a Docker API mismatch to me.

Is this something that might get fixed? Or should I just give up trying it out on Docker for Mac?

**Comment by VojtechVitek** [comment]
Same with 
```
$ oc version
oc v3.6.0-alpha.1+46942ad
kubernetes v1.5.2+43a9be4
features: Basic-Auth
```

**Comment by mfojtik** [comment]
@bparees @csrwng this looks like we should bump the docker client deps? ;-)

**Comment by bparees** [comment]
@VojtechVitek !

**Comment by csrwng** [comment]
@mfojtik that should be fixed with https://github.com/openshift/origin/pull/14169

**Comment by csrwng** [comment]
Hi @VojtechVitek :)

**Comment by VojtechVitek** [comment]
Hey guys, good to see you again!

Marek Jelen's visiting me here in Toronto. And we're just about to spin up our first OpenShift cluster on GCE for Pressly Inc. :)

**Comment by csrwng** [comment]
@VojtechVitek another option is to downgrade your Docker for Mac version.  1.13.1 works great and you can download it here: https://download.docker.com/mac/stable/1.13.1.15353/Docker.dmg

**Comment by php-coder** [comment]
> @mfojtik that should be fixed with #14169

I'm not sure because it updates not to the latest version but to the version that has UserNs field.

**Comment by bparees** [comment]
@csrwng this is resolved now right?  (w/ your changes to move to docker-engine)

**Comment by csrwng** [comment]
@bparees yes, that's correct. Closing
