### ISSUE TITLE
quota and rangelimits

### ISSUE THREAD

**Issue by barleyer** [openshift/origin#14518]
Hi All,
I would like to know that the  default quota and rangelimits for every new projects ， pod etc  if i do not create any resource about quota and rangelimits 。

Many thanks.

**Comment by mfojtik** [comment]
@scheng1 you're asking what the default quota/limits are in the online or in the origin locally?
I believe locally you can run `oc get quota` and `oc get limits`.

**Comment by scheng1** [comment]
@mfojtik  Thank you for u help . if i do not create any resource about  quota/limits ，there is no  quota/limits object as follow.
[root@node1 ~]# oc get quota
No resources found.
[root@node1 ~]# oc get limits
No resources found.

**Comment by scheng1** [comment]
then how to know the quota/limits information ？  Many thanks.

**Comment by mfojtik** [comment]
@scheng1 what you see when you describe the current project? `oc describe <project>`

**Comment by scheng1** [comment]
@mfojtik 
[root@node1 storage]# oc describe project cheng
Name:			cheng
Namespace:		<none>
Created:		9 seconds ago
Labels:			<none>
Annotations:		openshift.io/description=
			openshift.io/display-name=
			openshift.io/sa.scc.mcs=s0:c13,c2
			openshift.io/sa.scc.supplemental-groups=1000160000/10000
			openshift.io/sa.scc.uid-range=1000160000/10000
Display Name:		<none>
Description:		<none>
Status:			Active
Node Selector:		<none>
Quota:			<none>
Resource limits:	<none>

**Comment by scheng1** [comment]
@ganhuang

**Comment by scheng1** [comment]
In my opinion, if no  quota/limits object exists , the project/pod .. unrestricted use the node resources

**Comment by scheng1** [comment]
modify master-config.yaml to create quota/limits object when create a new project  (not include oadm new-project ..)by docs:https://docs.openshift.org/latest/admin_guide/managing_projects.html#template-for-new-projects
