### ISSUE TITLE
Use quorum read for origin api resources

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#14520]
Currently only oauth resources use quorum read (https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/rest/storage_options.go#L78)

@deads2k is saying that all kubernetes resources now use qread.

In some cases not doing qread can lead into false 404 if the get request hits the wrong etcd member (which might be fatal with GC enabled) but might also lead into other fun: https://github.com/coreos/etcd/issues/3879 or https://github.com/coreos/etcd/issues/4978

**Comment by deads2k** [comment]
> @deads2k is saying that all kubernetes resources now use qread.

This is what I thought happened.  I remember it coming up in discussions about "live" reads before.  Also, if its not the case, then upstream kube is crazy lucky with timing to never flake out on this.

@liggitt am I misremembering?

**Comment by mfojtik** [comment]
this (might) be the cause for https://github.com/openshift/origin/issues/13995 although that issue predates addition of ownerRefs from RC to DC.

**Comment by mfojtik** [comment]
as alternative to quorum read @sttts proposed to add 'quorum:true' to `metav1.GetOptions{}`. Then controllers like GC should set that up to make sure we delete only things that are really gone.

**Comment by deads2k** [comment]
> as alternative to quorum read @sttts proposed to add 'quorum:true' to metav1.GetOptions{}.

That's a good idea, but not something we can reasonably do in 3.6

**Comment by sttts** [comment]
My assumption is still that upstream has **no** quorum reads. But this somehow contradicts the fact that GC does not have known problems upstream.

**Comment by liggitt** [comment]
Everything I've seen said upstream is that HA etcd should always run in quorum read mode.

**Comment by mfojtik** [comment]
//cc @smarterclayton

**Comment by smarterclayton** [comment]
So we thought that in 3.4 and 3.5 all resources were on quorum reads, but they are not.

In 3.4 and 3.5, only oauthaccesstokens and oauthclientsecets has it on.  Jordan had a bit of code that we had to disable in 3.4 because of the refactor upstream that would allow us to turn it off.

Turning on qread for everything is probably not possible unless we perf tested first, and i suspect it would crush us.  So what are out other options?  Causal read via etags?  Almost impossible to get in this late in the cycle.

**Comment by sttts** [comment]
For reference, the kube discussion: https://github.com/kubernetes/kubernetes/issues/19902

**Comment by enj** [comment]
I decided to comment there to try and consolidate the discussion.

**Comment by smarterclayton** [comment]
Opened https://github.com/openshift/origin/pull/14572 to turn it on by default.  The alternative is https://github.com/openshift/origin/pull/14571, which is an API change.

**Comment by mfojtik** [comment]
@smarterclayton #14572 merged, so I guess we can close this one.
