### ISSUE TITLE
oc get with multiple -l args just uses the last one

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14525]
```
$ oc get pods -l app=ruby-helloworld-sample -l foo=bar
No resources found.
```

```
$ oc get pods -l foo=bar -l app=ruby-helloworld-sample
NAME               READY     STATUS    RESTARTS   AGE
database-1-dx3n0   1/1       Running   0          11m
```

I would have expected either an error that you can't pass the flag multiple times, or for the labels to be ANDed together.

There's also an argument that they should be ORed (rather than ANDed), but regardless ignoring all but the last value seems non-obvious.

I assume this will need to go upstream but i'm going to start it here.

(I'm aware of the `-l label1,label2` syntax, but I thought we were trying to move away from comma separated multivalue because it breaks as soon as your values contain commas)

@juanvallejo @fabianofranz

**Comment by fabianofranz** [comment]
@tanskann @bparees `oc get` never supported multiple `--selector`, the flag is an unique string (as opposed to a slice or array). As an enhancement, we could make it a slice and start supporting it multiple times. WDYT?

Note that, although not a rule, it is not a common behavior in POSIX commands to throw an error when it expected a flag just once and you provide it multiple times, most usual is to just take the last one and use it.

```
$ ls -l --sort=time --sort=size
$ mktemp XXX --suffix=.foo --suffix=.bar
```

**Comment by bparees** [comment]
> As an enhancement, we could make it a slice and start supporting it multiple times. WDYT?

that would be my preference since it seems like desirable/intuitive behavior.
