### ISSUE TITLE
SCC that is more strict to the capabilities than "restricted" is not getting used

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#14530]
When I'm creating a new SCC that has the same set of rules as "restricted" but differs in `dropCapabilities`, this new SCC isn't taking an effect.

```console
$ oc get scc restricted -o yaml | grep -A5 requiredDropCapabilities
requiredDropCapabilities:
- KILL
- MKNOD
- SYS_CHROOT
- SETUID
- SETGID
$ oc get scc super-restricted -o yaml | grep -A2 requiredDropCapabilities
requiredDropCapabilities:
- ALL
runAsUser:
$ oc get scc total-restricted -o yaml | grep -A6 requiredDropCapabilities
requiredDropCapabilities:
- KILL
- MKNOD
- SYS_CHROOT
- SETUID
- SETGID
- ALL
```
Despite that `super-restricted` and `total-restricted` are more strict than `restricted`, when I'm creating a pod under user, the pod is always admitted by `restricted` SCC.

Based on [the prioritization rules](https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#scc-prioritization), I'd expect that one of these most restrictive SCCs should be used.

@pweil- Is it a bug or I'm missing something here?

**Comment by pweil-** [comment]
@php-coder https://github.com/openshift/origin/blob/dffe340b459f13f6daa360972385267784ce1642/pkg/security/scc/byrestrictions.go#L20-L20

Restriction needs to be enhanced here to account for that difference.  It's currently only looking at the main strategies.

**Comment by adelton** [comment]
> When I'm creating a new SCC that has the same set of rules as "restricted" but differs in dropCapabilities, this new SCC isn't taking an effect.

Could you please provide a test plan -- SCC definitions and commands that you run and actual / expected results?

**Comment by php-coder** [comment]
@adelton Yes, here are they:
```console
$ oc login -u system:admin # login as admin to be able to create a new SCC
$ oc get scc restricted -o yaml >scc.yaml # dumping restricted SCC to use it as a template for a new one
$ vim scc.yaml
@@ -18,7 +18,7 @@
	   pods to be run with a UID, and SELinux context that are allocated to the namespace.  This
	   is the most restrictive SCC and it is used by default for authenticated users.
   creationTimestamp: 2017-06-15T10:25:17Z
-  name: restricted
+  name: super-restricted
   resourceVersion: "252"
   selfLink: /api/v1/securitycontextconstraints/restricted
   uid: ed756520-51b4-11e7-899e-507b9d2b16b9
@@ -30,6 +30,7 @@
 - SYS_CHROOT
 - SETUID
 - SETGID
+- ALL
 runAsUser:
   type: MustRunAsRange
 seLinuxContext:
$ oc create -f scc.yaml # create a new SCC
$ oc login -u developer -p developer # login as unprivileged user
$ vim examine-caps.yaml
apiVersion: v1
kind: Pod
metadata:
  generateName: examine-caps-
spec:
  restartPolicy: Never
  containers:
  - name: examine-caps
    image: centos:latest
    command:
    - "/bin/bash"
    - "-c"
    - "capsh --print"
$ oc create -f examine-caps.yaml
pod "examine-caps-9vlzl" created
$ oc describe pod examine-caps-9vlzl | grep Policy
Security Policy:	restricted
```
Pod has been created and admitted by "restricted" SCC while it should be admitted by "super-restricted" SCC as it's more strict and also available to any authenticated users.

**Comment by adelton** [comment]
Thanks.

Is pkg/security/admission/admission_test.go the test which should go with this change?

**Comment by adelton** [comment]
Is this issue only about dropping capabilities or about the whole accounting of default caps as well?

Is it OK to just take the number of caps as the score (with dropping ALL setting things to zero) or should we somehow measure for example SETUID against SETGID as well?

**Comment by php-coder** [comment]
> Is pkg/security/admission/admission_test.go the test which should go with this change?

At least we should have tests in `pkg/security/scc/byrestrictions_test.go` but we can also enhance `TestAdmitWithPrioritizedSCC` from `admission_test.go` to take into account `requiredDrops` field.

**Comment by php-coder** [comment]
> Is this issue only about dropping capabilities or about the whole accounting of default caps as well?

Even if we decide to account allowed/default caps, I'm suggesting to do this as a separate task and here  focus only on requredDrops.

@pweil- WDYT?

> Is it OK to just take the number of caps as the score (with dropping ALL setting things to zero) or should we somehow measure for example SETUID against SETGID as well?

It's OK for the first iteration.

It's still will be not accurate because if one SCC is dropping something that is dropped by default, while another don't do this, really they would have the same set of caps, but our logic will treat the first as more strict.

**Comment by pweil-** [comment]
@php-coder we need to make sure that we get the other PR in 3.6 then if we're trying to get this piece in.  I don't want it half baked at release time.

**Comment by pweil-** [comment]
@php-coder I think we also need to make sure (via a test) that our bootstrapped SCCs come out in the order expected so we maintain backwards compat going forward

**Comment by adelton** [comment]
By the way, what is the effect of thepod being admitted by the less strict SCC? Is there some information / security leak?

**Comment by pweil-** [comment]
No, I don't consider this a leak.  In order to use either of these SCCs the user must be given access to them so they are allowed to use both.  It is just an unexpected sorting behavior to determine what is most restrictive.

**Comment by php-coder** [comment]
> It is just an unexpected sorting behavior to determine what is most restrictive.

And this order always can be altered by setting `priority` field on the SCC. Here we're just improving default behavior.

**Comment by adelton** [comment]
I'm not sure that attempting to cram the logic to `pointValue` is the right place to solve the problem.

Wouldn't better place be the `Less` in pkg/security/scc/bypriority.go and pkg/security/scc/byrestrictions.go where upon the `pointValue`s being equal, we'd do some detailed comparison of the caps, rather than trying to come up with numerical value?

**Comment by adelton** [comment]
Pull request attempting to address this issue -> https://github.com/openshift/origin/pull/14825.
