### ISSUE TITLE
Switch the generic trigger controller to use apps/deployments

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#14543]
Spawned from this comment:

https://github.com/openshift/origin/pull/14317#discussion_r120438934

Basically we have to switch `Resource:  schema.GroupResource{Group: "extensions", Resource: "deployments"},` to `Group: apps`.

@kargakis @tnozicka

**Comment by tnozicka** [comment]
the generic trigger controller code has been removed in https://github.com/openshift/origin/pull/14910
