### ISSUE TITLE
s2i image build metrics not showing up in cadvisor prometheus entries

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#14554]
I've run tests over and over and I can't seem to get cadvisor prometheus metrics to show the docker container started by s2i, so we have no visibility into those.  We see other docker containers, so I'm not sure whether this is just bad testing, or whether there is something subtly weird with how that container is created which is getting omitted by cadvisor.

Very frustrating because we can't actually see the metrics from them.

**Comment by bparees** [comment]
@smarterclayton @derekwaynecarr i'd love to just move the s2i assemble container and docker build container into the pod cgroup if we think that would fix this.  @derekwaynecarr can you give me some pointers on making that happen?  we're using the docker-engine apis to launch our containers/run docker builds and I don't see anything that lets us directly control the cgroup, only the ability to pass in memory/cpu limits (which is what we do today).

**Comment by bparees** [comment]
related card: https://trello.com/c/fQAwpTcH

**Comment by smarterclayton** [comment]
This would still be something we have to investigate even if we move the
build under a cgroup, just because all containers on the system should be
accounted for and it *seems* like they are not.

**Comment by bparees** [comment]
build containers should all be under the pod cgroup now (once the cluster is updated).

**Comment by bparees** [comment]
@smarterclayton is this still an issue?  if so, is there anything further we need to do on the build side (short of us getting to the point where we do not run our containers for anything)?

**Comment by bparees** [comment]
this is fixed/being fixed by @derekwaynecarr's patches, right?

**Comment by bparees** [comment]
@derekwaynecarr @smarterclayton bump. fixed, right?

**Comment by bparees** [comment]
@derekwaynecarr @smarterclayton this is fixed right?

**Comment by smarterclayton** [comment]
Dunno

**Comment by smarterclayton** [comment]
Looks like good and bad

Good: i see the cpu on the slice
Bad: there are zero labels on it (pod, container name, namespace) so it's
not much use.

Looks like cadvisor needs to set the pod and namespace labels on the slices.
