### ISSUE TITLE
panic on healthz: poststarthook/ca-registration failed: reason withheld

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#14577]
Saw this ugly panic in master log: https://gist.github.com/mfojtik/9cc54967165ff0ed8444611762203544

Seems like the reason for it is: `poststarthook/ca-registration failed: reason withheld\nhealthz check failed`

This repeats twice in the log. Maybe this should not be 500 but some like "not ready" ?

**Comment by mfojtik** [comment]
@deads2k @liggitt @smarterclayton any clues?

**Comment by deads2k** [comment]
Is it a panic or just a stack?

**Comment by mfojtik** [comment]
@deads2k seems stack from the 500 code.
