### ISSUE TITLE
Metrics I want my cluster to tell me

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#14576]
Using this to record things we noticed while working on production issues.  These are all metrics I'd expect to be tracked during updates, or in general whenever changes in the system happen.

1. number of failed builds and deployments at any instant of time
2. number of deployments in `progressing: false`
3. number of pods that are started but not ready
4. number of pods that are crashlooping
5. number of failures to initialize network traffic
6. number of routes that are in rejected state
7. number of services with zero endpoints
8. number of pods that have restarted in the last minute

Some of these are in kube-state-metrics which I'd like to integrate.

Add more as comments.

**Comment by jcantrill** [comment]
@mwringe I presume there is a role for the hawular agent to play here?

**Comment by mfojtik** [comment]
@smarterclayton number of currently in-flight deployments, average time of rollout complete?

**Comment by mfojtik** [comment]
@smarterclayton is there a good example how we can get those metrics exposed from deployment controller?

**Comment by mfojtik** [comment]
@smarterclayton i also this we should expose the number of failed image imports

**Comment by smarterclayton** [comment]
Yes.  Kube-state-metrics is the pattern we want to follow, but we won't be
scraping the controllers until 3.7

On Jun 22, 2017, at 7:19 AM, Michal Fojtik <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> i also this we should
expose the number of failed image imports

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/14576#issuecomment-310363408>,
or mute the thread

**Comment by jcantrill** [comment]
Is this issue generally something we will get from each component owner providing relevant prometheus metrics?

**Comment by kargakis** [comment]
@jcantrill seems like yeah. @mfojtik @bparees what metrics from @smarterclayton's list do we miss today?

**Comment by bparees** [comment]
@kargakis i can only speak to build metrics, for which we have what @smarterclayton asked for.
