### ISSUE TITLE
Transition to k8s RBAC

### ISSUE THREAD

**Issue by odzhu** [openshift/origin#14588]
Hi Team,

I understand, OpenShift started implementation of it's RBAC mechanism even before Kubernetes, it explains why you implement it on your own.

Could you please share intentions/communication about transition to k8s native RBAC if any ?

##### Version
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
kubectl get roles
kubectl get clusterroles
kubect get rolebindings

##### Current Result
none
##### Expected Result
same resources as on OpenShift level
##### Additional Information

Thank you

**Comment by enj** [comment]
We wrote both the Origin and Kube RBAC implementations.  Origin came first, we learned from our mistakes, and then wrote a subtly different / better version for Kube.  We will start taking migration steps in 3.6 and should finish around the 3.8 timeframe.  You can look at the PRs that I have been involved in for the last ~2 months if you are interested in the specifics.  Feel free to reopen if you have further questions.

**Comment by odzhu** [comment]
thank you @enj
