### ISSUE TITLE
Lots of failed mounts with oc cluster up lately

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14589]
Not sure if this because of something in my env or a general problem but I have noticed that failed mounts are common in v3.6.0-alpha.2 with oc cluster up.
```
2m         2m          1         jenkins-1-deploy   Pod                                                   Warning   FailedMount         kubelet, localhost            Unable to mount volumes for pod "jenkins-1-deploy_myproject(595f15d4-4f65-11e7-aa2f-68f72840e7df)": timeout expired waiting for volumes to attach/mount for pod "myproject"/"jenkins-1-deploy". list of unattached/unmounted volumes=[deployer-token-f2vwz]
2m         2m          1         jenkins-1-deploy   Pod                                                   Warning   FailedSync          kubelet, localhost            Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "myproject"/"jenkins-1-deploy". list of unattached/unmounted volumes=[deployer-token-f2vwz]
```
```
$ oc version
oc v3.6.0-alpha.2+08cc91a-15-dirty
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
$ cat /etc/redhat-release 
Fedora release 25 (Twenty Five)
```
@csrwng @derekwaynecarr

**Comment by csrwng** [comment]
@kargakis do the mounts eventually succeed ?

**Comment by kargakis** [comment]
@csrwng in short, yes, they succeed eventually but that can take up to 5-10m, maybe more. This is problematic for a deployment though since waiting for the mount up to 10m exhausts the default deployment timeout, thus the deployment is scaled down.

**Comment by gnufied** [comment]
So, these are just secret volumes right? Not AWS volumes by the looks of it. We will look into it. cc @openshift/storage

**Comment by kargakis** [comment]
Yeah, just the sa token.

**Comment by kargakis** [comment]
Most likely something with my env since I get the same behavior in v1.5.1 and I don't recall such behavior during the 1.5 times. I have migrated to use oc cluster up on AWS ever since so I am going to close this one.
