### ISSUE TITLE
reduce the CPU / memory usage of deploy pods on OpenShift Online?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#14587]
I tried to `oc apply` [this yaml which contains 3 DCs](https://gist.github.com/jstrachan/97f7e30fce67f4524101236cf0403093) and I get 1 of the 3 DCs hung. e.g. try:
```
oc apply -f https://gist.githubusercontent.com/jstrachan/97f7e30fce67f4524101236cf0403093/raw/1598d8dbee6e7a43f6d855481ebb35aa956f6775/funktion.yml
```
Then 2 startup fine and the deploy pods terminate once the pods are running as expected.  

The 3rd DC hangs so that I can't trigger a redeploy via the console's `Deploy` button:
![banners_and_alerts_and_openshift_web_console](https://user-images.githubusercontent.com/30140/27031060-a6a645a6-4f66-11e7-9f61-db3636107be4.png)

Do deploy pods need to take up so much CPU wonder? It might be nice to allow > 2 DCs to be used on OpenShift Online.

Also when this issue hits; should the Deployment retry itself later when the deploy pod quota is freed up? e.g. I just get this in the console:
![openshift_web_console](https://user-images.githubusercontent.com/30140/27031153-fe4ab8b4-4f66-11e7-8b8c-5dbc072b4a5f.png)

or
```
$ oc get pod
NAME                          READY     STATUS    RESTARTS   AGE
configmapcontroller-1-lmlgp   1/1       Running   0          8m
exposecontroller-2-k7sbr      1/1       Running   0          8m
```
so no deploy pod are running any more & I don't see a way from the OpenShift console to restart it manually either - there's no way through the UI to cancel and retry Deployments right?

**Comment by abhgupta** [comment]
@jstrachan @pweil- This is not an Online specific issue. The question here is whether the deployment should be automatically retried when the "terminating" quota is freed up (after the other deployments are complete)? 

The user should be able to cancel the "stuck" deployment and trigger a new one manually via the console. Is that not working for you?

**Comment by jstrachan** [comment]
It does feel like pending DeploymentConfigs should retry automatically after some period if they were prevented due to terminating quota (after all if using Deployments instead of DeploymentConfigs then there's no quota limit and things just work). Or have much smaller limits (say cpu of 100m or something) so that with a 2 CPU limit on OSO you can run > 2 DeploymentConfigs concurrently.

In terms of working around this manually via the console - I don't see how. See the above screenshot; the `Deploy` button is disabled; then pausing/resuming the deployment did nothing. AFAIK there's no way to cancel/retry the deployment via the UI either

**Comment by pweil-** [comment]
@tnozicka

**Comment by andrewklau** [comment]
@jstrachan You can cancel the deployment by going into the replication controller (its hidden in there).

**Comment by jstrachan** [comment]
@andrewklau aha great catch thanks! Might be nice to add this as a menu on the Deployment page too

**Comment by tnozicka** [comment]
@jstrachan you can specify deployment pod `resources` here https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-deploymentstrategy

According to the docs that limit is for deployment + lifecycle hooks. My guess would be that deployer-pod needs a fraction of these resources since it's a Go app.

But I would suspect that Online injects some defaults and a lower bound there.

I would have to look into the retry but we don't generally retry deployments when something bad happens to deployer pod. This might change in future if we decide to go with upstream deployments and controller based approach.

**Comment by jstrachan** [comment]
@tnozicka ah thanks, didn't realise you could customize them.

Yeah it does sound extreme limits for deployments! I wonder if its so large to cater for custom lifecycle hooks or something?

**Comment by andrewklau** [comment]
Having it retry would be good. 

If for example you want to max out your terminating resource to build your app, the deployer pod will end up being forbidden as it tries to come up before the quota has been updated.

eg. terminating quota 1GiB
I build with 1GiB, it finishes and deployer pod starts, however my terminating quota was not sync'd yet and the deployer pod is forbidden. App is then stuck and doesn't deploy.
