### ISSUE TITLE
Remove test variable from docker-registry Dockerfile

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14608]
https://github.com/openshift/origin/blob/a0147110ec25e6c77c89474602e8402132586166/images/dockerregistry/Dockerfile#L26

This one is used for testing so we should probably get rid of it from the Dockerfile.

I was trying to move it as an ENV in https://github.com/openshift/origin/pull/13642#discussion_r110499657 but w/o any success (see my comment). [Removing it breaks some tests](https://github.com/openshift/origin/pull/14070) so more work needs to be done here.

**Comment by miminar** [comment]
Do you mean `DOCKER_REGISTRY_URL`? That's not a testing variable. It's a mandatory env var for the registry ATM.
To get rid of it, we would have to parse `${DOCKER_REGISTRY_SERVICE_HOST}:` and `${DOCKER_REGISTRY_SERVICE_PORT}` in the registry binary.

**Comment by dmage** [comment]
Fixed by #14882
