### ISSUE TITLE
Should allow insecure connection as a backup

### ISSUE THREAD

**Issue by danmcp** [openshift/origin#1460]
osc login
Please provide the server URL or just <enter> to use 'https://localhost:8443': https://130.211.183.187:8443
F0325 16:14:34.223890   31660 login.go:38] Get https://130.211.183.187:8443/oauth/authorize?client_id=openshift-challenging-client&response_type=token: x509: certificate is valid for 10.240.130.195, 127.0.0.1, not 130.211.183.187

I tried to connect to a remote server and got the above.  It isn't the best of messages.  But besides that I should be able to accept an insecure connection.

**Comment by liggitt** [comment]
Should be prompted to accept an insecure connection now. Can you verify and close?

**Comment by liggitt** [comment]
closing, `osc login` prompts to accept insecure now
