### ISSUE TITLE
Enable the use of the informer cache for build pruning

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#14638]
Follow up to #14596 and #14635

We did not initially enable cache because the build informer cache was not reliably populating the namespace index. 

The cache should be enabled after both of those PRs merge. We should also consider adding an index for builds by BuildConfig.

**Comment by bparees** [comment]
we can definitely merge this as a bug fix

**Comment by csrwng** [comment]
Addressed by https://github.com/openshift/origin/pull/14679
