### ISSUE TITLE
oc import-image fails when ImageStream has no tags

### ISSUE THREAD

**Issue by larkly** [openshift/origin#14631]
If an unpopulated ImageStream for some reason exists in a project, oc import-image (with --confirm --all to import all docker tags from a remote repository) fails with
`error: image stream does not have valid docker images to be imported`

This is due to the test in /pkg/cmd/cli/cmd/importimage.go, where
`len(stream.Spec.Tags) == 0`
will cause this error to be thrown.

If an image is tagged in the ImageStream with oc tag (even without a valid reference), the command completes as expected.

##### Version
openshift v3.5.5.8
kubernetes v1.5.2+43a9be4

##### Current Result
Full imports from external registries fail if ImageStream is defined and empty. It works fine if ImageStream is undefined or populated.

##### Expected Result
The expected outcome is that the tags from the remote repository are imported without failure. Alternatively a flag should be available to force the import.

**Comment by matthewpdias** [comment]
+1 I just ran into this today, and I was expecting the external tags to be imported.

**Comment by inspired** [comment]
Running v3.7.0 and also ran into this.

> oc delete is RESOURCE_NAME

resolved it

**Comment by bparees** [comment]
@legionus since you're looking for stuff to do, can you look into this one?

**Comment by bparees** [comment]
> The expected outcome is that the tags from the remote repository are imported without failure. 

@larkly @inspired @matthewpdias i'm confused by what is being asked here.  The code in question fails the import if you don't have a spec.DockerImageRepository AND you don't have any spec.tags.  If that is the state of your imagestream, what are you expecting to see imported?  What remote repository do you expect to import from, when there isn't one specified in the imagestream?

**Comment by bparees** [comment]
@legionus explained this to me, i'm set, thanks.

**Comment by bparees** [comment]
(the scenario appears to be invoking ` oc import-image --confirm --all --from docker.io/busybox foobar` with an empty foobar imagestream)
