### ISSUE TITLE
Rebase tool wishlist

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#14641]
In no particular order, but while I'm dealing with some pain.

1. Auto-fork pick to openshift/kubernetes and rebump in openshift/origin.  This would keep the list up to date.
2. Auto-list of pulls already merged into a particular level of kube.
3. Building on 2, auto-creation of the pick list for the next rebase.
4. Also building on 2, nag issues in openshift for pulls that are closed without merging.

**Comment by kargakis** [comment]
Is this issue addressed by the publishing bot?
