### ISSUE TITLE
Support optional args in diagnostics

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#14640]
It should be possible for some diagnostics to have optional arguments that parameterize checks that may run too long or too short.  Exposed by #14604 and suggested by @eparis.  I temporarily used an env var for a variable that only 10-20% of people may need to customize.

**Comment by sosiouxme** [comment]
The command has a few flags directed at specific diagnostics, like `--network-pod-image`. More could be added, of course, but I don't really like proliferating flags for what are really sort of subcommands (did not really like those flags being added to begin with).

So would this imply there should be a generic parameter specifically for passing parameters for specific diagnostics? Something like:
`--param EtcdWriteVolume.write-volume-duration=10s`

This would have the disadvantage of not being discoverable via the usual -h flag (we could introduce a flag specifically for listing them, though) and not being name-checked or type-checked/converted by cobra. Obviously this is just as true for env vars and probably any solution we could come up with that's not formal flags.

**Comment by sosiouxme** [comment]
Resolved with https://github.com/openshift/origin/pull/17773
