### ISSUE TITLE
Update CI to allow building and testing with golang 1.8

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#14648]
The 1.7 rebase requires golang 1.8 to compile.  We need our CI to support building and testing on that level.  A WIP PR could be ready to start tracking failures as early as next week.

@smarterclayton @eparis @liggitt @jupierce

**Comment by stevekuznetsov** [comment]
Nothing needs to change from CI perspective, just set `OS_BUILD_ENV_GOLANG=1.8` when you run stuff. The PR to update it for CI should change the default in [`hack/lib/build/constants.sh`](https://github.com/openshift/origin/blob/master/hack/lib/build/constants.sh#L5)

**Comment by stevekuznetsov** [comment]
No longer applicable

/close
