### ISSUE TITLE
oc version command output contains error message

### ISSUE THREAD

**Issue by sub-mod** [openshift/origin#14651]
when i run ```oc version``` command I get an error message "You must be logged in to the server (the server has asked for the client to provide credentials)"

##### Version
```
oc version
oc v3.6.0-alpha.2+ee9f436-198-dirty
kubernetes v1.6.1+5115d708d7
features: Basic-Auth
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

##### Steps To Reproduce
1. ```oc version```

##### Expected Result
The error message should not be shown

**Comment by pweil-** [comment]
@fabianofranz I feel like I've seen this before (maybe in a BZ) but didn't find it on a quick search

**Comment by juanvallejo** [comment]
@sub-mod are you still running into this issue?
Also, any chance you could post the output of `oc version --loglevel 8`?

**Comment by juanvallejo** [comment]
@liggitt I'm not sure why hitting the `/version/openshift` endpoint would require authentication.
Maybe you've seen a similar issue before?

**Comment by juanvallejo** [comment]
@sub-mod try running `oc adm reconcile-cluster-roles`
