### ISSUE TITLE
unable to decode "prometheus.yaml": no kind "Template" is registered for version "template.openshift.io/v1"

### ISSUE THREAD

**Issue by alekonkoisp** [openshift/origin#14666]
Hi i'm unable to deploy prometheus into my minishift instance.

Atttach the "oc new-app -f prometheus.yaml " command line report:

unable to decode "prometheus.yaml": no kind "Template" is registered for version "template.openshift.io/v1"

##### Version
$ oc version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4

$ minishift.exe version
minishift v1.1.0

minishift run in Windows 10 with virtualbox driver

##### Steps To Reproduce
1. minishift start    (origin 1.5.1)
2. oc new-app -f prometheus.yaml

##### Current Result
unable to decode "prometheus.yaml": no kind "Template" is registered for version "template.openshift.io/v1"
##### Expected Result
creation of prometheus app

**Comment by mfojtik** [comment]
@alekonkoisp can you upgrade the oc client to 1.5?

**Comment by alekonkoisp** [comment]
Updated oc client to 1.5.1
````
$ oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth
Server https://192.168.99.100:8443
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
````

but the problem remains

````
$ oc new-app -f prometheus.yaml
error: unable to load template file "prometheus.yaml": unable to decode "prometheus.yaml": no kind "Template" is registered for version "template.openshift.io/v1"
error: no match for "prometheus.yaml"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
````

**Comment by mfojtik** [comment]
@alekonkoisp i see what is the problem now...

The example is made for API group (which was introduced in 3.5+). To make this work, you can edit the template and replace `template.openshift.io/v1` with `v1`. Let me know if that worked for you.

**Comment by mfojtik** [comment]
@smarterclayton is 3.6 needed for the prometheus example (examples/prometheus)? I can fix the API version but then I get:

```
[@dev] .../openshift/origin # oc new-app examples/prometheus/prometheus.yaml
--> Deploying template "test/prometheus" for "examples/prometheus/prometheus.yaml" to project test

     Prometheus
     ---------
     A monitoring solution for an OpenShift cluster - collect and gather metrics from nodes, services, and the infrastructure.



     * With parameters:
        * NAMESPACE=kube-system
        * IMAGE_PROXY=registry.svc.ci.openshift.org/ci/oauth-proxy:latest
        * IMAGE_PROMETHEUS=registry.svc.ci.openshift.org/ci/prometheus:latest
        * SESSION_SECRET=MbWYGLhX7tnfdnBEWcfT6w024EcpiPHnOK2fMFXreDX # generated

error: object does not implement the Object interfaces
```

**Comment by mfojtik** [comment]
@alekonkoisp forget that, there are 2 more objects with API groups, you can pick up this template: https://github.com/openshift/origin/pull/14768

**Comment by smarterclayton** [comment]
Specifically default destinationCACertificates.
