### ISSUE TITLE
oadm migrate tool to prevent upgrade if volumeSource.metadata is present

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#14677]
https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/api/v1/types.go#L338-L341 has been deprecated for multiple releases.  We should block upgrade if someone has these while we still have the types in 3.6, so that we'll be clean in 3.7.

@liggitt

**Comment by enj** [comment]
I am already working on this so not sure why assignment was changed.
