### ISSUE TITLE
Flake: github3.models.GitHubError: 403 API rate limit exceeded for openshift-bot

### ISSUE THREAD

**Issue by tbielawa** [openshift/origin#14682]
PR fails tests due to

```
+ python check-pull-request-status.py 4041 master /var/lib/jenkins/.config/hub test_status_config.yml
Traceback (most recent call last):
  File "check-pull-request-status.py", line 25, in <module>
    pull_request = client.pull_request(owner='openshift', repository='openshift-ansible', number=pull_request_id)
  File "/usr/lib/python2.7/site-packages/github3/github.py", line 1026, in pull_request
    r = self.repository(owner, repository)
  File "/usr/lib/python2.7/site-packages/github3/github.py", line 1063, in repository
    json = self._json(self._get(url), 200)
  File "/usr/lib/python2.7/site-packages/github3/models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "/usr/lib/python2.7/site-packages/github3/models.py", line 121, in _boolean
    raise GitHubError(response)
github3.models.GitHubError: 403 API rate limit exceeded for openshift-bot.
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: CHECK OTHER JOB STATUSES [00h 00m 01s] ##########
Build step 'Execute shell' marked build as failure
```

##### Version
CI 3.6 OCP

##### Steps To Reproduce
Submit a PR during a busy time of the merge cycle

##### Current Result
Rosie runs exceeds rate limit.

##### Expected Result
Rosie can talk to GitHub and not break a merge

Reference: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/600/console#118321978658b6e51eb7608a5981914356

**Comment by kargakis** [comment]
@dobbymoodge @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@dobbymoodge here's another client using the Rosie credentials. The script is https://github.com/openshift/aos-cd-jobs/blob/master/sjb/check-pull-request-status.py

**Comment by dobbymoodge** [comment]
It needs to check the rate limit header and/or use conditional requests.
Will look into it in a bit.

**Comment by dobbymoodge** [comment]
We've enabled conditional queries/query caching for testing on all major rosie configs, so we should see some improvement here. In a couple of days if things look good, we'll merge in the rosie changes and enable them across all rosie configs.

**Comment by dobbymoodge** [comment]
http://cachecontrol.readthedocs.io/en/latest/storage.html <-- we should look at implementing this for our python github clients. We will probably need similar cache invalidation logic to https://github.com/openshift/test-pull-requests/pull/54

**Comment by stevekuznetsov** [comment]
Or hopefully the volume of requests will be so much smaller with Rosie having caches we'll be able to let the Python clients run loose.

**Comment by dobbymoodge** [comment]
I'm assuming the measures we've taken have satisfactorily addressed this problem. Reopen if it happens again.
