### ISSUE TITLE
[builds][Conformance][valueFrom] process valueFrom in build strategy environment variables failing on GCE provider

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#14689]
Need to figure out why [builds][Conformance][valueFrom] process valueFrom in build strategy environment variables (test/extended/builds/valuefrom.go) is failing on GCE with error: Rpmdb checksum is invalid: dCDPT(pkg checksums): centos-release-scl-rh.noarch 0:2-2.el7.centos - u and remove the framework.SkipIfProviderIs("gce")

Introduced in pull request #14143

**Comment by mfojtik** [comment]
bumping to P1, seems like the rate this happen increased.

**Comment by bparees** [comment]
@mfojtik was referring to failures in the test, but not this specific checksum issue.  @coreydaley if we're not still recreating the checksum issue, let's just close this.

**Comment by coreydaley** [comment]
@mfojtik Could you please open a new issue for your flake?

**Comment by mfojtik** [comment]
@coreydaley already done :) sorry for the noise
