### ISSUE TITLE
Can't build Go and binaries in Centos using Vagrantfile and contrib/vagrant scripts

### ISSUE THREAD

**Issue by ayen-tibco** [openshift/origin#14706]
Following the Contrib doc, I can't seem to build the binaries to get the openshift origin up and running.  I can't seem to skip the build either even though .vagrant-openshift.json has skip-build=true.

##### Version
Centos version is 7.3
Can't even build the openshift origin

##### Steps To Reproduce
1. git clone openshift/origin
2. vagrant plugin install vagrant-openshift
2. create .vagrant-openshift.json 'vagrant origin-init --stage inst --os centos7 master'
3. set skip-build: true in .vagrant-openshift.json
4. vagrant up or vagrant provision master --provision-with shell

##### Current Result
See attached 'make build' output file
[output.txt](https://github.com/openshift/origin/files/1081407/output.txt)

```
+++ echo hack/build-go.sh
++ bash_source=hack/build-go.sh
++ [[ -z true ]]
++ os::log::info '                2: hack/build-go.sh:37: os::build::build_binaries'
++ local message
+++ os::log::internal::prefix_lines '[INFO]' '            2: hack/build-go.sh:37: os::build::build_binaries'
+++ local 'prefix=[INFO]'
+++ local 'content=               2: hack/build-go.sh:37: os::build::build_binaries'
+++ local 'old_ifs=
'
+++ IFS='
'
+++ for line in ${content}
+++ echo '[INFO]                  2: hack/build-go.sh:37: os::build::build_binaries'
+++ IFS='
'
++ message='[INFO]                2: hack/build-go.sh:37: os::build::build_binaries'
++ os::log::internal::to_logfile '[INFO]                  2: hack/build-go.sh:37: os::build::build_binaries'
++ [[ -n /data/src/_output/scripts/build-go/logs ]]
++ [[ -d /data/src/_output/scripts/build-go/logs ]]
++ echo '[INFO]                   2: hack/build-go.sh:37: os::build::build_binaries'
++ echo '[INFO]                   2: hack/build-go.sh:37: os::build::build_binaries'
[INFO]            2: hack/build-go.sh:37: os::build::build_binaries
++ stack_index=3
++ (( i++  ))
++ (( i < 4 ))
++ os::log::info '  Exiting with code 1.'
++ local message
+++ os::log::internal::prefix_lines '[INFO]' '  Exiting with code 1.'
+++ local 'prefix=[INFO]'
+++ local 'content=  Exiting with code 1.'
+++ local 'old_ifs=
'
+++ IFS='
'
+++ for line in ${content}
+++ echo '[INFO]   Exiting with code 1.'
+++ IFS='d
'
++ message='[INFO]   Exiting with code 1.'
++ os::log::internal::to_logfile '[INFO]   Exiting with code 1.'
++ [[ -n /data/src/_output/scripts/build-go/logs ]]
++ [[ -d /data/src/_output/scripts/build-go/logs ]]
++ echo '[INFO]   Exiting with code 1.'
++ echo '[INFO]   Exiting with code 1.'
[INFO]   Exiting with 1
```

##### Expected Result
openshift binaries and config files generated

##### Additional Information
my centos7.3 bash 4.2.x had to be update to 4.3> since 'local -n' is used and only recognized in later bash version.

**Comment by pweil-** [comment]
@csrwng @jim-minter @marun looks like you have been in the Vagrantfile lately.  Something you've seen or can help with?

**Comment by ayen-tibco** [comment]
Tried with release-1.5 and release-1.3branches and still no success.

**Comment by stevekuznetsov** [comment]
Yes, I'd strongly suggest using `oct` -- but even then the local VM story is pretty lacking. We don't have resources to maintain these local development scenarios.

@ayen-tibco are you on a machine with a Docker daemon? You can do builds inside of a container, not a VM, and still not need to do any installation of local dependencies.

**Comment by ayen-tibco** [comment]
Not familiar with oct. I am just trying to get multi node configuration setup and running. I will go back to oc  cluster up (the --join does not work correctly which is why I was trying the Vagrantfile).  openshift-ansible cluster configuration had issues too.  As a newbie, this origin stuff is to difficult to configure and deploy. I'll will go back to RH Container Platform or the hosted version to see if I can get anything done there.

**Comment by csrwng** [comment]
Neither the vagrant plugin nor cluster up are meant to give you a multi-node cluster. If you need to set one up, you should use openshift-ansible. It is possible to setup with multiple vm's on your machine and the byo playbook.

**Comment by stevekuznetsov** [comment]
Are you trying to solve provisioning or installation? If you have multiple nodes, especially if you have HA control plane, by far your best bet is OpenShift-Ansible.

**Comment by jim-minter** [comment]
Hi @ayen-tibco I wonder if this is the issue:
```
+ ln -s /data/src /data/src/_output/local/go/src/github.com/openshift/origin
ln: failed to create symbolic link ‘/data/src/_output/local/go/src/github.com/openshift/origin’: Protocol error
```

Guess: are you using VirtualBox on Windows?  If so, it may be that you can't compile origin on a shared folder in the VM.

**Comment by ayen-tibco** [comment]
Hi @jim-minter.

You are correct, I am on windows and sharing the folder to the VirtualBox VM. Never again...what a waste of time...ugh.
