### ISSUE TITLE
error: SDN node startup failed: Allocated ofport (-1) did not match request (1)

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14708]
conformance install/update setup failed here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/1317/

```
Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.
```

in s3 artifacts `journals/origin-node.service` shows:
```
Jun 16 11:27:48 ip-172-18-8-42.ec2.internal origin-node[33133]: F0616 11:27:48.319074   33133 node.go:351] error: SDN node startup failed: Allocated ofport (-1) did not match request (1)
```

as the last message.

@sdodson @knobunc not sure which of you should own this.

**Comment by sdodson** [comment]
I'd leave it up to networking to do the first cut at triage here. Let us know if you need any help debugging install process or implementing changes.

**Comment by knobunc** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1467387

**Comment by rjhowe** [comment]
Is ipv6 disabled?  If so you are hitting this bug.

https://bugzilla.redhat.com/show_bug.cgi?id=1445054

```
 ovs-vsctl[50616]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --may-exist add-port br0 vxlan0 -- set Interface vxlan0 ofport_request=1 type=vxlan "options:remote_ip=\"flow\"" "options:key=\"flow\""
 kernel: vxlan: Cannot bind port 4789, err=-97
 atomic-openshift-node[50567]: F0705 07:56:05.456865   50567 node.go:351] error: SDN node startup failed: Allocated ofport (-1) did not match request (1)
 systemd[1]: atomic-openshift-node.service: main process exited, code=exited, status=255/n/a
 systemd[1]: Failed to start Atomic OpenShift Node.
```

```
$ cat /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz-3.10.0-514.21.2.el7.x86_64 root=UUID=d85d7be1-03aa-433a-a847-030104cc3ce2 ro console=tty0 console=ttyS0,115200n8 no_timer_check net.ifnames=0 ipv6.disable=1  crashkernel=auto LANG=en_US.UTF-8
```

**Comment by brenton** [comment]
@knobunc, should this be closed now that the underlying RHEL bug has been fixed? https://bugzilla.redhat.com/show_bug.cgi?id=1454636 ( I see the RHEL 7.3. EUS bug technically hasn't been fixed yet, but that's not what we run in CI)

**Comment by ronsengupta** [comment]
I still get this on RHEL 7.4 and OCP 3.5

**Comment by danwinship** [comment]
@ronsengupta what is the output of `uname -sr`? And you're seeing the node fail to start with the "Allocated ofport (-1)" error? (As opposed to the node starting, but showing errors about "ofport -1" in the logs later.)?

**Comment by danwinship** [comment]
Presumed fixed by the kernel vxlan ipv6 fix

**Comment by debianmaster** [comment]
seeing this issue in  3.10

**Comment by danwinship** [comment]
@debianmaster The specific bug being discussed here was caused by a kernel problem and is independent of OpenShift version. I don't know the specific kernel versions with the fix, beyond that it's fixed in current releases of RHEL. If you are running a kernel that's more than a year old or so, then you are probably hitting that bug (and the fix is to either upgrade your kernel or don't disable IPv6). If you are running a more recent kernel then please provide the kernel version number and the exact log message you're getting.
