### ISSUE TITLE
service catalog role mappings should only allow catalog controller to create/update service class

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#14703]
normal users should not be able to create or update a service class.

only the catalog should be privileged to create them as a consequence of talking to broker.

##### Version
n/a

**Comment by derekwaynecarr** [comment]
@pmorie @jpeeler -- please ensure your default roles account for above.

xref https://bugzilla.redhat.com/show_bug.cgi?id=1462086

fyi @jwforres

**Comment by pmorie** [comment]
cc @ewolinetz

**Comment by pmorie** [comment]
The roles in https://github.com/openshift/openshift-ansible/pull/4195/files and https://github.com/openshift/origin/pull/14528 should correctly implement this; it's not clear to me how the catalog was set up by the reporter of the linked bug.

**Comment by jwforres** [comment]
@pmorie they were not running behind the aggregator and using the template from the console so things were very insecure.  sounds like you guys already covered things in the installer

**Comment by enj** [comment]
@openshift/security

**Comment by adelton** [comment]
Could you please provide steps to reproduce (commands to run) for this issue?

**Comment by derekwaynecarr** [comment]
moving milestone to 3.7 as catalog is tech preview in 3.6 with documented limitations.

**Comment by adelton** [comment]
> sounds like you guys already covered things in the installer

Is this still an issue?

**Comment by simo5** [comment]
@pmorie can you comment on the status of this or close it ?

**Comment by pmorie** [comment]
This is fixed now; sorry - missed the issue; closing.
