### ISSUE TITLE
How to restore openshift master node?

### ISSUE THREAD

**Issue by Coyote5** [openshift/origin#14719]
[provide a description of the issue]
I have a openshift cluster that has a single master node and three etcd node.I backup the etcd regularly. A few days ago, the master host crashed. I reinstall the master node, and restore the etcd whith the backup file. After recovering the etcd, the master  doesn't work properly. The master service always crash and restart.Before restore the etcd, the master work properly.

##### Version
[provide output of the `openshift version` or `oc version` command]
openshift v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

**Comment by pweil-** [comment]
@Coyote5 to help us provide assistance, can you confirm that you're following these procedures for backup/restore: https://docs.openshift.org/latest/admin_guide/backup_restore.html

**Comment by Coyote5** [comment]
@pweil- Sorry,I do not backup the /etc/origin/master directory. Is it possible for me to restore the system?

**Comment by pweil-** [comment]
Can you post the actual errors you're seeing on startup?

**Comment by Coyote5** [comment]
No error during startup. But

**Comment by Coyote5** [comment]
There is no error during startup, but after a while the origin-master service restarts.

```Jun 17 14:35:41 host-10-1-236-104 systemd: origin-master.service: main process exited, code=exited, status=255/n/a
Jun 17 14:35:41 host-10-1-236-104 systemd: Unit origin-master.service entered failed state.
Jun 17 14:35:41 host-10-1-236-104 systemd: origin-master.service failed.
Jun 17 14:35:46 host-10-1-236-104 systemd: origin-master.service holdoff time over, scheduling restart.
Jun 17 14:35:46 host-10-1-236-104 origin-master: W0617 14:35:46.612531   75785 start_master.go:270] assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
Jun 17 14:35:46 host-10-1-236-104 origin-master: W0617 14:35:46.612636   75785 start_master.go:270] assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console

**Comment by sdodson** [comment]
@Coyote5 Can you set loglevel=4 in /etc/sysconfig/origin-master and see if more information is logged when you attempt to start the master? I suspect that you probably need to rebuild new certificates.

**Comment by Coyote5** [comment]
How can I rebuild new certificate?
