### ISSUE TITLE
Endpoints controller is dumb

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#14710]
On 3.5 It looks like it's refreshing every 30s, and it's doing a live GET before update, and somehow we're generating 100 GET calls / second on a set of 10k endpoints.

**Comment by smarterclayton** [comment]
@derekwaynecarr if i don't get a chance to look at this someone should

**Comment by smarterclayton** [comment]
Basically - endpoints controller is horribly broken, upstream we completely rewrote it (as a result of this issue), and we may backport if we still see issues at extreme scale in 3.6.

**Comment by derekwaynecarr** [comment]
we can have someone look at backport if needed.

pertinent upstreams:
https://github.com/kubernetes/kubernetes/pull/47731
https://github.com/kubernetes/kubernetes/issues/47788

**Comment by derekwaynecarr** [comment]
@aveshagarwal -- can you help put picks together in origin for the referenced PRs in case we see this in 3.6?

**Comment by aveshagarwal** [comment]
https://github.com/openshift/origin/pull/15067
