### ISSUE TITLE
cluster down: error: json: cannot unmarshal bool into Go struct field APIMount.RW of type string

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#14737]
I see the following error running cluster down.

```
$ oc cluster down
error: json: cannot unmarshal bool into Go struct field APIMount.RW of type string
```

##### Version

Current master:

```
$ oc version
oc v3.6.0-alpha.1+fa750b9-1441
kubernetes v1.6.1+5115d708d7
features: Basic-Auth
```

cc @csrwng

**Comment by php-coder** [comment]
It's possible that https://github.com/openshift/origin/pull/14729 will fix this bug.

**Comment by spadgett** [comment]
I can confirm that there is no error on cluster down when I build with #14729

**Comment by csrwng** [comment]
dup of #14546
