### ISSUE TITLE
Cloudera manager - could not open session 

### ISSUE THREAD

**Issue by elmehdi92** [openshift/origin#14767]
Hello Guys, 

I m having trouble trying to create a cloudera-manager docker image. I want to deploy on Openshift 

So, here is the Dockerfile : 

```
FROM centos:6.6


COPY cloudera-manager.repo /etc/yum.repos.d/

# Install useful things that are missing from the centos:6.6 image.
RUN yum install -y openssh-clients \
    openssh-server \
    rsyslog \
    sudo \
    tar \
    wget \
    which

RUN yum clean all

RUN yum install --nogpgcheck -y java-1.7.0-openjdk-devel oracle-j2sdk1.7 python-setuptools supervisor cloudera-manager-server cloudera-manager-daemons cloudera-manager-server-db-2 postgresql.x86_64 rsync sudo

RUN easy_install supervisor
RUN yum clean all

CMD ["/sbin/init"] 
```

So, When I run the container in a privileged mode (On my local machine), I can start the services (cloudera-scm-server-db cloudera-scm-server)

But not with a normal way. 

I m tried to manage SCC but without success. 

The error I keep having is : `cloud not open session`. when I do :` service cloudera-scm-server-db` start or `/etc/init.d/cloudera-scm-server-db start `

I m getting the same error on the pods logs.. 

Any idea how to manage this or how to start a privileged container correctly on Openshift ? 

Thank you in advance

**Comment by elmehdi92** [comment]
@php-coder @tnozicka  any idea guys ?

**Comment by php-coder** [comment]
> So, When I run the container in a privileged mode (On my local machine)

How do you run it? Show us Pod (or DeploymentConfig) definition, please.

> I m tried to manage SCC but without success.

What have you tried exactly?

Most likely, granting `anyuid` SCC should be enough: https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile

**Comment by php-coder** [comment]
> CMD ["/sbin/init"] 

This one is very suspicious. Do you really need to run `init` process inside of a container?

**Comment by pweil-** [comment]
> This one is very suspicious. Do you really need to run init process inside of a container?

and if so are you using the oci systemd hook? https://github.com/projectatomic/oci-systemd-hook

**Comment by elmehdi92** [comment]
@php-coder thank you for your reply, 

I meant use the docker command on my local machine not in Openshift  : 

```
[root@localhost mezghari-clouderabase]# docker run   mezghari/cloudera-base
could not open session
```

```
[root@localhost mezghari-clouderabase]# docker run  --privileged mezghari/cloudera-base
The files belonging to this database system will be owned by user "cloudera-scm".
This user must also own the server process.

The database cluster will be initialized with locale en_US.UTF8.
The default text search configuration will be set to "english".

fixing permissions on existing directory /var/lib/cloudera-scm-server-db/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 32MB
creating configuration files ... ok
creating template1 database in /var/lib/cloudera-scm-server-db/data/base/1 ... ok
initializing pg_authid ... ok
setting password ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok

Success. You can now start the database server using:

    postgres -D /var/lib/cloudera-scm-server-db/data
or
    pg_ctl -D /var/lib/cloudera-scm-server-db/data -l logfile start

Adding configs
Creating SCM configuration file: /etc/cloudera-scm-server/db.properties
waiting for server to start.... done
server started
CREATE ROLE
CREATE DATABASE
Created db properties file /etc/cloudera-scm-server/db.properties
Creating DB amon for role ACTIVITYMONITOR
CREATE ROLE
CREATE DATABASE
Created DB for role ACTIVITYMONITOR
Creating DB rman for role REPORTSMANAGER
CREATE ROLE
CREATE DATABASE
Created DB for role REPORTSMANAGER
Creating DB nav for role NAVIGATOR
CREATE ROLE
CREATE DATABASE
Created DB for role NAVIGATOR
Creating DB navms for role NAVIGATORMETASERVER
CREATE ROLE
CREATE DATABASE
Created DB for role NAVIGATORMETASERVER
Enabled remote connections
waiting for server to shut down.... done
server stopped
DB initialization done.
waiting for server to start.... done
server started

```

The first one without` --privileged `

I also update the `CMD ["/sbin/init"]` and changed it with : `CMD ["/etc/init.d/cloudera-scm-server-db" , "start"]` 

I ve followed this in order to get this container running on Openshift : https://blog.openshift.com/getting-any-docker-image-running-in-your-own-openshift-cluster/ 

the cloud not open session error I got when not running in privileged mode, is the one I got on the pods that s why I thought it might be coming from the this aspect 

Thanks in advance.

**Comment by elmehdi92** [comment]
@php-coder @pweil-  No, I dont need it, What I need to most is getting the cloudera-scm-server-db and cloudera-scm-server services running correctly on the container.

**Comment by php-coder** [comment]
> Any idea how to manage this or how to start a privileged container correctly on Openshift ?

In order to start a privileged container in OpenShift, you need to do the following:
1) ensure that service account (or user) has permissions to the SCC that allows creating privileged pods (see my link above)
2) write a pod definition (it can be a plain Pod or ReplicationController/DeploymentConfig/Deployment)
3) run a pod

Try to follow these steps and ask a concrete questions if you will face obstacles.

**Comment by php-coder** [comment]
P.S. And, please, don't create a new issues for your questions. This is a bug tracker and not a forum. Ideally, questions should be posted to a mailing list: http://lists.openshift.redhat.com/openshiftmm/listinfo/users

**Comment by elmehdi92** [comment]
@php-coder I m sorry, i didnt know. 
thanks a lot for your help, but  I didnt get your second point ? 
I deploy a new image using oc new-app ... 
thanks

**Comment by php-coder** [comment]
> I deploy a new image using oc new-app ...

`oc new-app` creates DeploymentConfig but this config runs unprivileged pod. However, you can edit this DeploymentConfig and set `securityContext.privileged` field to `true`. Use `oc get dc` to get list of deployment configs and `oc edit dc/<name>` to edit particular deployment config.
