### ISSUE TITLE
build an origin release failed after 6 hours

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14765]
```
[INFO] hack/build-images.sh exited with code 0 after 00h 07m 49s
hack/extract-release.sh
++ Extracting openshift-origin-server-v3.6.0-alpha.2-8e027cd-380-linux-64bit.tar.gz
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
++ Extracting openshift-origin-client-tools-v3.6.0-alpha.2-8e027cd-380-linux-64bit.tar.gz
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
++ Extracting openshift-origin-image-v3.6.0-alpha.2-8e027cd-380-linux-64bit.tar.gz
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.security.selinux'
Connection to 172.18.14.156 closed by remote host.
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: BUILD AN ORIGIN RELEASE [06h 08m 49s] ##########
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/3430/

two issues w/ this:

1) obviously ideally it shouldn't fail
2) if it is going to fail, it'd be good if it could fail sooner than 6 hours.  It's especially problematic if it happens to a PR on the merge queue.

**Comment by stevekuznetsov** [comment]
> 1. obviously ideally it shouldn't fail

¯\_(ツ)_/¯

> 2. if it is going to fail, it'd be good if it could fail sooner than 6 hours. It's especially problematic if it happens to a PR on the merge queue.

Today, we have two knobs:

 - overall job timeout
 - `charlie` on the VM

We don't have a way to apply that to a stage or action, and as we have jobs that actually take a long time (looking at you, extended and AMI jobs) we have historically kept the limit at 6h. I'm open to other approaches.

**Comment by bparees** [comment]
> We don't have a way to apply that to a stage or action, and as we have jobs that actually take a long time 

how do we not have the ability to set a timeout on a particular step within a stage?  Not a jenkins job way, but a way in the logic we're running (e.g. the ansible playbook).

Our tests all include logical timeouts if the condition they are waiting for goes unmet, can we not wrap the "run the ansible installer" in a "and if it isn't done after an hour, fail" logic?  (assuming it was the ansible installer steps that were at issue here)

**Comment by stevekuznetsov** [comment]
I see, ok. We run these stages by using `scp` to bring a shell script to the remote host and then `ssh` to execute it -- we can prefix that with a `timeout` command. I think we'd change [this line](https://github.com/openshift/aos-cd-jobs/blob/master/sjb/actions/script.py#L22) to look more like:

```sh
ssh -F ./.config/origin-ci-tool/inventory/.ssh_config -t openshiftdevel "bash -l -c \\"timeout {{ timeout }} ${script}\\""
                                                                                       ^-------------------^
```

We'd want some reasonable default and to allow shell actions to pass through a different value if necessary. Do you think you have bandwidth to add this?

**Comment by bparees** [comment]
i can take a crack at it.  obviously the tricky bit is picking suitable timeouts.
