### ISSUE TITLE
AWS provision failure: Failed to connect to the host via ssh: ssh_exchange_identification: read: Connection reset by peer

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14771]
Seen this flake a few times now:

```
########## STARTING STAGE: USE A RAMDISK FOR ETCD ##########
+ [[ -s /var/lib/jenkins/jobs/test_branch_origin_extended_builds/workspace/activate ]]
+ source /var/lib/jenkins/jobs/test_branch_origin_extended_builds/workspace/activate
++ export VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890
++ VIRTUAL_ENV=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890
++ export PATH=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/origin-ci-tool/9aea3b4f81e266b026e21975a3a6a5a1cfddd890/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ unset PYTHON_HOME
++ export OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_branch_origin_extended_builds/workspace/.config
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_branch_origin_extended_builds/workspace/.config
++ mktemp
+ script=/tmp/tmp.sDGN8NlHJd
+ cat
+ chmod +x /tmp/tmp.sDGN8NlHJd
+ scp -F ./.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.sDGN8NlHJd openshiftdevel:/tmp/tmp.sDGN8NlHJd
ssh_exchange_identification: read: Connection reset by peer
lost connection
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: USE A RAMDISK FOR ETCD [00h 00m 00s] ##########
```

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/104/console

Is there anything we can do to make this stage more robust?

(p2 because I haven't seen it in the merge queue, may be specific to our extended job?)

**Comment by bparees** [comment]
@jim-minter fyi

**Comment by stevekuznetsov** [comment]
The failure was on server-side when we were using `scp`:

```
ssh_exchange_identification: read: Connection reset by peer
lost connection
```

Not clear what killed `sshd` on the target host, or if the host just died, but it looks like total failure on that end. Not sure there's much more we can do.

**Comment by bparees** [comment]
is it worth adding a retry loop?

**Comment by stevekuznetsov** [comment]
Looks like every time we tried to hit the machine for the rest of the job also failed. I'm not sure we need to be well-formed in case the VM falls over entirely like that. If we see this more than once and we have a reason to think re-try would help, we could try to add it. I think `scp` and `ssh` both emit a different exit code when _they_ fail versus when their remote stuff fails.

**Comment by bparees** [comment]
ok, i'll close for now but i do think i've seen it at least twice in the last few days.

**Comment by coreydaley** [comment]
Looks like this flake is showing up again:
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/113

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1228/consoleFull#-211399806158b6e51eb7608a5981914356

**Comment by dmage** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_image_registry_integration/54/console

**Comment by dmage** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_image_registry_integration/60/

**Comment by stevekuznetsov** [comment]
@dmage there is really nothing we can do about this -- not sure reporting every AWS API flake is worth your time

**Comment by bparees** [comment]
@stevekuznetsov if we're seeing this this much, perhaps the jobs themselves need to detect this and be rerun?

**Comment by stevekuznetsov** [comment]
If we were seeing it much more commonly, maybe.
