### ISSUE TITLE
Metrics failed to install with cluster up

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#14789]
After running the command,

```
$ oc cluster up --service-catalog=true --version=latest --metrics
```

metrics fail to install. The error from `openshift-ansible-metrics-job` from `openshift-infra` is

```
STDOUT:

not installed

TASK [openshift_metrics : Check that python-passlib is available on the control host] ***
fatal: [127.0.0.1]: FAILED! => {
    "assertion": "'not installed' not in passlib_result.stdout", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}

MSG:

python-passlib rpm must be installed on control host
```

##### Version

Current master.

```
oc version
oc v3.6.0-alpha.2+5dce9b9-371
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
kubernetes v1.6.1+5115d708d7
```

cc @csrwng @jcantrill @mwringe

**Comment by csrwng** [comment]
Requires an updated openshift-ansible image

**Comment by spadgett** [comment]
Thanks @csrwng. I pulled `openshift/origin-ansible:latest`, but I'm still seeing the error. It looks like it's a couple weeks old. I guess I need to build the latest myself?

**Comment by jcantrill** [comment]
@spadgett I would build it yourself, but maybe @sdodson or @sosiouxme has insight on why its not being pushed with every ansible build...

**Comment by sdodson** [comment]
We should get this integrated into CI, at least a daily build if not per PR. @codificat What needs to be done here? Just `docker build` in the openshift-ansible repo?

**Comment by codificat** [comment]
There is a job in ci.openshift called `build-and-release-latest-openshift-ansible-images` which will build and push the image. Right now it's manually run though... short term @sdodson or @sosiouxme can manually start it?

Then review automatic runs - originally the expectation was that the image would not need too frequent updates, and the manual "do it" on the job would be enough.

One thing that the job doesn't cover right now is multiple tags for the image, which might be necessary (e.g. `latest` + `v3.6`).

**Comment by sdodson** [comment]
https://ci.openshift.redhat.com/jenkins/job/build-and-release-latest-openshift-ansible-images/16/console

**Comment by spadgett** [comment]
Thanks for the help. Working now with the latest image!
