### ISSUE TITLE
RC can end up with a Foreground finalizer but no deletionTimestamp

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#14805]
This is related to https://github.com/kubernetes/kubernetes/issues/47843
Except when it is a DC and not a Deployment, then on the RC that gets left behind we are seeing a finalizer get set but there is no deletionTimestamp on the RC.  It should not have a foreground deletion finalizer with no deletionTimestamp.  This may not be a separate issue but tracking it in case there is something weird going on in our deployment controller.

**Comment by jwforres** [comment]
cc @liggitt

**Comment by tnozicka** [comment]
@mfojtik doesn't it require also setting the finalizer on DC? Seems like the same issue as why we added that finalizer to RC in DC->RC->Pod chain. I feel like I have proposed adding admission control to set finalizers on DC somewhere to fix this issue. But I think you can easily break it with adding one more item to the chain. Maybe GC could use some improvements? cc: @deads2k

**Comment by soltysh** [comment]
https://github.com/kubernetes/kubernetes/pull/44058 seems to be reasonable approach and fixes the root cause.
