### ISSUE TITLE
Properly parse http accept header

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#1480]
Currently we're doing this:
```
accept := req.Header.Get("Accept")
if req.URL.Path == "/" && strings.Contains(accept, "text/html") {
```
which is error prone, looking at [this http spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), which allows you to specify the accept header in quite sophisticated way. 
Unfortunately I couldn't find any go lib to cover this, but [here](https://github.com/mitsuhiko/werkzeug/blob/80d674429f3ea76a706e6dc2419a3cecf7b2a33b/werkzeug/datastructures.py#L1648-L1666) is implementation of this in python.

**Comment by smarterclayton** [comment]
goautoneg is a package we already vendor from upstream

**Comment by soltysh** [comment]
#1945 was merged, thus closing.
