### ISSUE TITLE
Limit the maximum number of concurrent connections a pod can receive through a route annotation

### ISSUE THREAD

**Issue by jtudelag** [openshift/origin#14822]
Through a route annotation, I want to be able to set the maximum number of concurrent connections a pod exposed under a route can receive.

Some use cases:

As a developer, I want that the platform controls the amount of traffic my app can receive. This can save my app from going down under extreme loads.

As a project admin, I want to protect the apps that are exposed externally through routes from DDoS like attacks.

**Comment by pravisankar** [comment]
Fixed by https://github.com/openshift/origin/pull/15559
