### ISSUE TITLE
If the port is not specified in the for --public-master it will default to 8443, even if the scheme is explicitly declared

### ISSUE THREAD

**Issue by brenton** [openshift/origin#1482]
If I set `--public-master` to https://myproxy.example.com the automatically generated oauth clients will have redirect URIs like `https://myproxy.example.com:8443/oauth/token/display`.

I had to explicitly set `:443` on the end.  I think this will be surprising to admins trying to configuration authentication proxies.  If the code gets messy to implement the least surprising cases I would prefer:

* `--public-master=myproxy.example.com` behaves the same as today
* `--public-master=https://myproxy.example.com` returns an error saying the port is explicitly required.
* `--public-master=myproxy.example.com:443` returns an error saying the scheme is explicitly required.
* `--public-master=https://myproxy.example.com:443` works

Admins new to openshift will not understand how to clear out the autogenerated oauth clients.  Perhaps if we improved the stale detection this configuration wouldn't be a problematic.  I think today the master only checks if they exist, not if they are pointing to the correct redirect URIs.

If we're concerned about backwards compatibility then we could technically return warnings.  In any case, @sosiouxme, stale oauth clients in etcd will be a case the diagnostic tooling will eventually need to check for.

@liggitt, thoughts?

**Comment by liggitt** [comment]
Admins doing configuration *should* be working from config files, which have none of the nasty surprises the command line defaults do. Config files are fully specified, and we don't default ports or anything else from them.

**Comment by liggitt** [comment]
The built-in clients get updated from config every time the server starts

**Comment by brenton** [comment]
Ahh, I haven't had time to look at the latest config work in detail.  If those configs don't suffer from these issues we can just close this.

**Comment by brenton** [comment]
I still think we'll need the diagnostics check for the oauth clients though.  If two masters had different values that could get confusing depending on how things are restarted.

**Comment by liggitt** [comment]
Our approach:

Command-line args are minimal, and are targeted at development/kick-the-tires scenarios (mint all my certs, autodetect my local IP, derive one value from another, etc, etc).

Config files are fully specified and don't do magic for you. If something isn't right, you should be able to look at the config file and see it. We can add validation errors or warnings to detect common problems.

**Comment by liggitt** [comment]
Yes, that is one of many things we'll need to make better once we have multi-master

**Comment by sosiouxme** [comment]
The cmdline-vs-config dichotomy makes good sense to me and should be prominently stated in our docs :)  (@adellape where?) I don't think the beta3 ansible installer has been updated to use the new server config but should soon be (this should make server diagnostics way easier too).

**Comment by liggitt** [comment]
initial docs here: https://github.com/openshift/openshift-docs/pull/244
