### ISSUE TITLE
git url parsing unit test failure with golang-1.8

### ISSUE THREAD

**Issue by detiber** [openshift/origin#14831]
When using golang 1.8, there are failures related to parsing git urls due to changes in url.Parse in golang 1.8

##### Version
master

##### Steps To Reproduce
1. OS_BUILD_ENV_GOLANG=1.8 hack/env make release
2. OS_BUILD_ENV_GOLANG=1.8 hack/env make test-unit

##### Current Result
```
--- FAIL: TestParseRepository (0.08s)
	git_test.go:101: ParseRepository returned err: parse git@[2001:db8::1]:repository.git: first path segment in URL cannot contain colon
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x229c48]

goroutine 7 [running]:
testing.tRunner.func1(0xc42007d110)
	/usr/lib/golang/src/testing/testing.go:622 +0x25c
panic(0x274e40, 0x429700)
	/usr/lib/golang/src/runtime/panic.go:489 +0x284
github.com/openshift/origin/pkg/generate/git.TestParseRepository(0xc42007d110)
	/root/origin/_output/local/go/src/github.com/openshift/origin/pkg/generate/git/git_test.go:108 +0xf58
testing.tRunner(0xc42007d110, 0x2d7278)
	/usr/lib/golang/src/testing/testing.go:657 +0x9c
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:697 +0x270
FAIL	github.com/openshift/origin/pkg/generate/git	0.137s
```

##### Expected Result
Unit test cases in pkg/generate/git/git_test.go should pass.

**Comment by detiber** [comment]
@bparees @gabemontero There didn't seem to be an obvious easy fix to me here. It looks like we may need to pre-process git urls prior to passing to url.Parse instead of just post-processing.

**Comment by bparees** [comment]
@jim-minter are these the same parse changes you warned us about, or were those changes in go1.7?

**Comment by bparees** [comment]
(note that we don't support building origin on go1.8 currently)

**Comment by detiber** [comment]
@bparees understood, multi-arch builds are currently tied to golang-1.8 because of issues with golang-1.7 on ppc64le. I'm happy to assist with the issue given some guidance, but I'd expect that any fix would target 3.7 at this point.

**Comment by jim-minter** [comment]
Yes. Work needs to be done in origin and s2i. https://github.com/openshift/origin/issues/12403 and https://github.com/openshift/source-to-image/issues/632 (for want of anything better).
I had hoped to make a substantial improvement but got bogged down / distracted.
Git's code to parse clone specs is surprisingly involved.  The specs come in three forms: URL (https://github.com/openshift/origin.git), SSH (git@github.com:openshift/origin.git) and file (worst cases C:\path\to\repo and path/to/repo) and broadly speaking it is illegal to convert between them, so you mustn't really store the non-URL ones in a URL.  Ideally we'd treat them more or less opaquely but there are also cases where we muck around with them.
I should resurrect my branch in 3.7.

**Comment by jim-minter** [comment]
Perhaps an interim step of continuing to convert SSH specs to URLs as we do today, but with less help from url.Parse, might make sense.

**Comment by smarterclayton** [comment]
We are almost certainly going to switch to Go 1.8 during the 3.6.x lifecycle.  So we should assume that anything we do is going to have to be back ported to 3.6.1 or 3.6.2.

**Comment by deads2k** [comment]
This is now blocking the rebase's test-cmd.sh https://github.com/openshift/origin/pull/15100

```
I0711 14:56:53.494395    2436 newapp.go:248] treating /home/deads/workspaces/openshift3/src/github.com/openshift/origin/test/testdata/build-arg-dockerfile as possible source repo
I0711 14:56:53.494493    2436 git.go:213] makePathAbsolute /home/deads/workspaces/openshift3/src/github.com/openshift/origin/test/testdata/build-arg-dockerfile
I0711 14:56:53.494772    2436 repository.go:385] Executing git config --get-regexp ^remote\..*\.url$
I0711 14:56:53.499057    2436 repository.go:385] Executing git symbolic-ref -q --short HEAD
I0711 14:56:53.506937    2436 helpers.go:225] Connection error: parse git@github.com:deads2k/origin: first path segment in URL cannot contain colon
F0711 14:56:53.506998    2436 helpers.go:120] error: Unable to connect to the server: first path segment in URL cannot contain colon
```
 on 
```
oc new-build /home/deads/workspaces/openshift3/src/github.com/openshift/origin/test/testdata/build-arg-dockerfile --build-arg 'foo=bar' --to 'test' -o jsonpath='{.items[?(@.kind=="BuildConfig")].spec.strategy.dockerStrategy.buildArgs[?(@.name=="foo")].value}' --loglevel=8

```

**Comment by deads2k** [comment]
I will try commenting out bits of the test-cmd test to see how much is broken.
