### ISSUE TITLE
No mention of password during `oc cluster up` operation

### ISSUE THREAD

**Issue by budhrg** [openshift/origin#14832]
##### Version
```
$ oc version
oc v3.6.0-alpha.1+46942ad
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

```

##### Steps To Reproduce
1. Run `oc cluster up`

##### Current Result
```
Starting OpenShift using openshift/origin:v3.6.0-alpha.1 ...
...

The server is accessible via web console at:
    https://127.0.0.1:8443

You are logged in as:
    User:     developer

To login as administrator:
    oc login -u system:admin
```
##### Expected Result
```
Starting OpenShift using openshift/origin:v3.6.0-alpha.1 ...
...

The server is accessible via web console at:
    https://127.0.0.1:8443

You are logged in as:
    User:     developer
    Password: developer

To login as administrator:
    oc login -u system:admin
```

Curious to know why we are dropping `Password` here. How will the user know how to login to web console?

Is it due to the fact that password here is just a fake one as we can use anything in the password field?

**Comment by csrwng** [comment]
> Is it due to the fact that password here is just a fake one as we can use anything in the password field?

Yes, you can use anything. Displaying one is misleading.

**Comment by budhrg** [comment]
> Displaying one is misleading.

Showing nothing as well also might be confusing to new users (may be my opinion only). 
Probably something like:
```
User:          developer
Password:  <anything> (unauthenticated)
```

will convey fast and better to user that he/she has to use anything for password which is unauthenticated.

**Comment by csrwng** [comment]
@budhrg agree. I'll submit a pr with a fix.

**Comment by budhrg** [comment]
@csrwng  or should I try :smile:

**Comment by csrwng** [comment]
definitely 👍

**Comment by budhrg** [comment]
Added fix @csrwng
