### ISSUE TITLE
Exiting "Trigger OpenShift Build" unsuccessfully; build "xxxxxx-build-2" did not complete successfully within the configured timeout of "900000" ms; last reported status:  [NotStarted].

### ISSUE THREAD

**Issue by zafinxueqian** [openshift/origin#14840]
[provide a description of the issue]
I am wondering where is the default timeout configured and how can I change it in Jenkins pipeline build.  Thanks
##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oadm diagnostics` or `oc adm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by bparees** [comment]
https://github.com/openshift/jenkins-plugin#trigger-openshift-build

it should be configurable in the build step itself (via configuring the jenkins job).

closing, but feel free to reopen if that doesn't help you.
