### ISSUE TITLE
test_pull_request_origin_extended_networking_minimal fails on bringup

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#14857]
See https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1096/

```
[ERROR] Timeout waiting for 3 nodes to report readiness
[ERROR] PID 23850: hack/dind-cluster.sh:41: `return 1` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/dind-cluster.sh:41: `return 1`
[INFO] 		  2: hack/dind-cluster.sh:121: wait-for-cluster
[INFO] 		  3: hack/dind-cluster.sh:636: start
[INFO]   Exiting with code 1.
[INFO] Saving cluster configuration
[ERROR] Failed to deploy cluster for plugin: {multitenant}
```

Couldn't find something in this arena already opened.  Apologies if I missed it.

**Comment by bparees** [comment]
@knobunc i know we've had flakes for the networking dind test before, not sure if this matches one that is currently open though.

**Comment by danwinship** [comment]
happened a few times within a few days in June and then hasn't happened since... so either there was some infrastructure issue, or else someone fixed the problem independently of this bug report.
