### ISSUE TITLE
Acessing other ports than 80 and 443 from outside of the cluster

### ISSUE THREAD

**Issue by JackOneil** [openshift/origin#14852]
#I would like to open port (eg. 3306) for public to the outside of openshift cluster

##### Version
openshift v1.5.1
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. deploy application, mysql container to openshift
2. start pod, check service to have port and TargetPort to 3306

##### Current Result
can't access port 3306 from outside of the cluster

##### Expected Result
to be able to access the port 3306 from outside of cluster

##### Additional Information
I am able to access the port 3306 within the cluster but not from outside. As far as goes the documentation, i can create route for example to nginx server to be open on port 80 or 443, but how can i do this for other ports ?

**Comment by knobunc** [comment]
Hopefully these docs help:
  https://docs.openshift.com/container-platform/3.5/dev_guide/getting_traffic_into_cluster.html

But the brief version is that services are not exposed outside the cluster unless you do something else, and there are a variety of options depending on your needs.
