### ISSUE TITLE
understand syntax of docker-compose.yml

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#1485]
It would be great, that when creating deployment, openshift would recognize `docker-compose.yml` and would deploy the app using the docker compose's yaml file (so user wouldn't have to specify links, volumes etc.).

Does that make sense?

**Comment by mfojtik** [comment]
i was thinking the same also with `fig`

**Comment by soltysh** [comment]
@mfojtik docker-compose is a replacement for `fig` see their [website](http://www.fig.sh/) at the top.

**Comment by red-hood** [comment]
Very good idea :+1:

**Comment by mfojtik** [comment]
there was trello card for this

**Comment by soltysh** [comment]
The card: https://trello.com/c/Z9UBcuyz/414-generate-k8s-json-from-openshift-json-future

**Comment by smarterclayton** [comment]
Prototyped, but compose kind of sucks.  Not sure yet how to best leverage this

**Comment by TomasTomecek** [comment]
They also changed syntax recently. Would be nice if there was a command to create a basic template with deployment (which should be finalized by user afterwards).

**Comment by kargakis** [comment]
@smarterclayton is this fixed?

**Comment by smarterclayton** [comment]
Yes, this was fixed.
