### ISSUE TITLE
hawkular metrics url incorrectly configured during `oc cluster up`

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#14874]
[provide a description of the issue]

##### Version
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
oc cluster up --logging --metrics

##### Current Result
metrics are not shown for pods (even after metrics pods are up and accepting self signed cert)
looks like metrics url is not configured properly in master-config.yaml
Actual metrics url is `https://hawkular-metrics-openshift-infra.127.0.0.1.nip.io/hawkular/metrics`
where as configured one is 
`https://metrics-openshift-infra.127.0.0.1.nip.io/hawkular/metrics`

##### Expected Result
pods should show metrics

**Comment by jcantrill** [comment]
Using latest which moves to Ansible based deployment of metrics with 'oc cluster up' I am unable to reproduce the difference:

```
# ./oc cluster up --host-config-dir=/tmp/foo --host-data-dir=/tmp/foo --metrics --version=latest
Starting OpenShift using openshift/origin:latest ...
Pulling image openshift/origin:latest
Pulled 2/4 layers, 51% complete
Pulled 2/4 layers, 67% complete
Pulled 2/4 layers, 82% complete
Pulled 3/4 layers, 97% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://127.0.0.1:8443

The metrics service is available at:
    https://metrics-openshift-infra.127.0.0.1.nip.io

You are logged in as:
    User:     developer

To login as administrator:
    oc login -u system:admin

```
results in the master-config.yaml:

```
assetConfig:
  metricsPublicURL: https://metrics-openshift-infra.127.0.0.1.nip.io/hawkular/metrics
```
Please try latest.

**Comment by debianmaster** [comment]
can you provide `oc version` with which you tried ?

**Comment by jcantrill** [comment]
Mine was built from source that uses ansible to install metrics, which would be HEAD

**Comment by debianmaster** [comment]
i tried `v3.6.0-alpha.2+3c221d5`  so it might differ
