### ISSUE TITLE
Make TemplateInstance objects hold a ref to their Template

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#14883]
At the moment, TemplateInstance objects (used by the template service broker) contain the entire Template that will be instantiated.  Making this an ObjectReference to a Template would make it easier to create a TemplateInstance object.  @openshift/api-review is this something that in principle should be allowable as an API change for 3.7?

Notes:
1. It will be necessary to handle loops (a Template whose instantiation eventually causes a TemplateInstance to be created which refers to the same Template, etc.)
2. The TemplateInstance should probably keep an exact copy of the template it instantiated for future reference - perhaps in Status?

@bparees

**Comment by bparees** [comment]
Note that we would keep the existing inline template field, this would be an additional field (TemplateRef or something), and validation require one or the other, but not both.  (I think this means we would need to change the existing Template field from a Template to a *Template)

**Comment by jim-minter** [comment]
Trello'd https://trello.com/c/h9s07jWe/1325-make-templateinstance-objects-hold-a-ref-to-their-template
