### ISSUE TITLE
osc describe build mybuild-1 should show buildConfig it was generated from

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#1489]
The discussion starts [here](https://botbot.me/freenode/openshift-dev/2015-03-26/?msg=35143719&page=7).

@bparees I can handle this one with #1488 if you don't mind :smile:

**Comment by bparees** [comment]
I already did this one on friday:
https://github.com/openshift/origin/pull/1474/

**Comment by soltysh** [comment]
Right :wink:
