### ISSUE TITLE
oc new-app --build-env doesn't work on templates

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#14906]
`oc new-app --build-env` works in conjunction with an argument such as `https://github.com/openshift/nodejs-ex`, but it doesn't work in conjunction with `-f path/to/template`.  `oc new-app --env` works as expected.

```
$ oc new-app -f https://raw.githubusercontent.com/openshift/rails-ex/master/openshift/templates/rails-postgresql.json --build-env FOO=bar -o yaml | grep -C 2 FOO
$ oc new-app -f https://raw.githubusercontent.com/openshift/rails-ex/master/openshift/templates/rails-postgresql.json --env FOO=bar -o yaml | grep -C 2 FOO
        containers:
        - env:
          - name: FOO
            value: bar
          - name: DATABASE_SERVICE_NAME
--
        containers:
        - env:
          - name: FOO
            value: bar
          - name: POSTGRESQL_USER
```

**Comment by jim-minter** [comment]
@bparees I think this should be dealt with for 3.6 but wanted to run it by you

**Comment by bparees** [comment]
yeah, given that --env doesn't apply the env to the buildconfigs, this seems necessary/useful for fixing in 3.6.

**Comment by pdmack** [comment]
Not to conflate this issue but it should be noted that this also applies to `--context-dir` if a template is in play. That doesn't get passed to the builder either.

`openshift v3.6.121
kubernetes v1.6.1+5115d708d7`

**Comment by coreydaley** [comment]
@pdmack would you mind opening a new issue for that please for tracking purposes.
