### ISSUE TITLE
Remove updating latest version in rollout latest in favor of instantiate

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#14903]
In 3.7 we want to nuke this: https://github.com/mfojtik/origin/blob/50c1aadf1fc9088a617899c4ad8fac1dee8fc484/pkg/cmd/cli/cmd/rollout/latest.go#L165

**Comment by kargakis** [comment]
Also https://github.com/openshift/origin/blob/bbb9647b7655d3c709580b9ccf018649cfe1b45d/pkg/deploy/registry/deployconfig/strategy.go#L73-L77
