### ISSUE TITLE
oc debug should not use AttachablePodForObject

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#14915]
Debug doesn't work against attachable pod for object because a scaled to zero Deployment (required for us to be able to debug and mount an RWO) hangs forever.

We should be using a different method `MostAccuratePodTemplateForObject` which should try to go as far down as it can and then return back a pod template, and if there are zero pods return the RS template

**Comment by smarterclayton** [comment]
Also, `oc get deploy/prometheus -o yaml | oc debug --one-container -c prometheus -f -` fails.

Basically, I need to be able to debug from an approximate pod template.

**Comment by smarterclayton** [comment]
It is not appropriate to change AttachablePodForObject (a template is not attachable).

**Comment by smarterclayton** [comment]
And this is actually a pretty common use case - you want to debug something with RWO.  You scale it to zero (because otherwise you have to fight for the RWO).  You then want to run debug on it.

**Comment by wanghaoran1988** [comment]
@smarterclayton @fabianofranz  How do you think about just remove the `AttachablePodForObject` logic [here](https://github.com/openshift/origin/blob/master/pkg/cmd/util/clientcmd/factory.go#L208-L214) and use the t.spec.Template directly? I am not very clear why we need carbon copy an existed pod instead of using the t.spec.Template, would you please tell me the logic behind this ?

**Comment by smarterclayton** [comment]
Debug wants to get the closest possible pod template to what is actually
running.  It does not require a running pod, it just prefers one if
possible.

**Comment by wanghaoran1988** [comment]
Add MostAccuratePodTemplateForObject to upstream ObjectMappingFactory, so we can always get the pod template of the upstream resources.

> Also, oc get deploy/prometheus -o yaml | oc debug --one-container -c prometheus -f - fails.
> 
> Basically, I need to be able to debug from an approximate pod template.
For this kind debug, template from stdin, I am try to fix, but I found if we read the template from stdin, the pod can be created successfully but the tty tunnel cannot be established, as the code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/exec.go#L235) don't think stdin is a terminal.

**Comment by smarterclayton** [comment]
Debug with piped input should only succeed if the user passed a command
*AND* set --no-tty
