### ISSUE TITLE
Occasionally need to restart origin-node (write unix /var/run/docker.sock->@: write: broken pipe)

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#14927]
I am starting to see this error where I need to occasionally restart origin-node

It seems to cause a few issues, but I believe might be primarily due to this line:

```
write unix /var/run/docker.sock->@: write: broken pipe
```

Symptoms include: My prometheus alerts firing off docker timeout errors, docker cli hangs, ebs volumes fail to mount, network issue (as below) although the node status reports it self as ready.

```
Error syncing pod, skipping: failed to "SetupNetwork" for "web-server-3-7dxjm_test2" with SetupNetworkError: "Failed to setup network for pod \"web-server-3-7dxjm_test2(d62428f0-5b88-11e7-bd76-06579dce22e7)\" using network plugins \"cni\": CNI request failed with status 400: 'failed to read pod test2/web-server-3-7dxjm: pods \"web-server-3-7dxjm\" not found\n'; Skipping pod
```

Restarting origin-node fixes all of the above problems. 

This is occurring on nodes with 1.4.1 (downgraded due to https://github.com/openshift/origin/issues/14092

Might be an issue which was fixed in 1.5?

##### Version
1.4.1

**Comment by andrewklau** [comment]
Also seems to happen on 1.5.1 nodes but only seems to be long running nodes (30 days+).

**Comment by jwhonce** [comment]
@andrewklau Which version of the docker rpm are you using? And do the docker logs show any errors prior to the broken pipe message?

**Comment by andrewklau** [comment]
@jwhonce nodes are atomic os:

```
# docker -v
Docker version 1.12.6, build 3a094bd/1.12.6
```

Prior to the broken pipe message alerts are usually firing off errors like error with "list_containers", "create_containers etc.
