### ISSUE TITLE
cAdvisor metrics on OpenShift nodes sum CPU into `/` and `/system.slice` cgroups, but not memory

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#14920]
container_cpu_usage_seconds_total is cumulative for cgroups in 3.5 and 3.6.  container_memory_rss is not.  Confusing, not necessarily broken.

**Comment by smarterclayton** [comment]
Not a 3.6 blocker, but both confusing and potentially not right

**Comment by derekwaynecarr** [comment]
my fix for runc merged, we will have to bump runc in cadvisor, and use it to expose total_ values so we do not look at charges local to the cgroup but also its children.

**Comment by sjenning** [comment]
for the record, that is a bump to at least https://github.com/opencontainers/runc/commit/7139b61f7fdb904d0acb8db825709aa8d2d2ef36

**Comment by sjenning** [comment]
@aveshagarwal PTAL

**Comment by smarterclayton** [comment]
I thought this was fixed in 3.7

**Comment by sjenning** [comment]
Very true, fixed by https://github.com/openshift/origin/pull/16419 and pulled in on the rebase for 3.8.  Nothing to see here!
