### ISSUE TITLE
support a clear way to determine if a user is 'root'.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#14957]
This is a hard issue to describe.  Most users in a cluster are aware that there is some form of "root" or "Administrative" user.  However, when running apps that need to do certain root type functionality, its hard to determine which user ACLs they actually need. 

Concretely, as a user, I'd like to get comprehensive feedback when an OC action fails, about why it failed and where I can read more / how I can reconfigure my cluster, so that those actions can succeed.'

I'll try to flesh out more details below...  

##### Version
all 

##### Steps To Reproduce
1. minishift start
2. 

```
➜  ~ oc whoami -c
/192-168-64-3:8443/jay
```

This gives very little useful information if I need certain security information to confirm if I can run my app. 

As an admin, there is more (group) information but not much more....

```
➜  ~ oc whoami -c
default/192-168-64-3:8443/system:admin
```

##### Current Result

You get minimal options for understanding 'who you are'.

##### Expected Result
```
➜  ~ oc whoami -c
default/192-168-64-3:8443/system:admin
```

Comprehensive information, about who you are, what your role is in the cluster, and how to understand how that role relates to things you might need to do for your particular app.

#### Workaround

You can indirectly probe your privileges by trying things, and failing, like so:

- `oc describe clusterPolicyBindings` are an indirect way of determining if you're a cluster admin.

```
Error from server (Forbidden): User "jayunit100" cannot list all securitycontextconstraints in the cluster
```

##### Desired behaviour 

Rather then probing, I'd like it if the oc client told me more about who I was, what role I was playing, and where to read more about those roles, and maybe even what other roles existed on the cluster (if thats considered insecure, maybe obfuscate some info about those roles, but at least list them in some form)... I think it  would be nice if it actually said "You are only authorized to view these scopes - to configure scopes, go to openshift.io/docs/configuring-scopes and ask your administrator for corresponding access".  

I guess the net effect here, is that I'm asking for more self-documenting behaviour in the client when it comes to access control and permissions, since people who need to do semi-privilieged tasks in their apps have no breadcrumbs to follow at the moment, and the docs around openshift administration are focused on the creation of roles but not how those roles are used differently by different application developers.

**Comment by enj** [comment]
`oc policy can-i --list -n foo` tells you everything you can do in a namespace.  It can easily be used to determine everything you can do in all namespaces you have access to.  There is not a simple way AFAIK to see all cluster scoped actions you can do.  `oc policy can-i verb resource --all-namespaces` works for individual `verb resource` pairs (`oc policy can-i '*' '*' --all-namespaces` tells you if you are cluster admin).  `oc get clusterroles` can be used by all authenticated users to see what the roles mean, but not who those roles are bound to.  I am not saying anything of this is obvious, but most of the functionality is there.

@openshift/security

**Comment by pweil-** [comment]
> if thats considered insecure, maybe obfuscate some info about those roles, but at least list them in some form

I think this would be an information leak no matter how obscure it was.  It also implies that the operation you're invoking runs with escalation privileges since it would be able to list other roles.  In any case, I think this is a dupe of https://github.com/openshift/origin/issues/11611 so we can continue the discussion there.
