### ISSUE TITLE
path based routing with mixed tls

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#14950]
We are having issues with mixing path based routing. The issue spawns from https://github.com/tnozicka/openshift-acme

Is the correct behaviour to only accept one type of termination?

ie. 

https://www.example.com/ <-- termination=reencrypt --> web1
https://www.example.com/path <-- termination=edge --> web2

The path based route is "accepted" but only routes to web1 unless the path is also set to termination=reencrypt

This also happens with non tls

https://www.example.com/ <-- termination=edge --> web1
http://www.example.com/path <-- no tls --> web2

Again the /path is accepted but only routes to web1

**Comment by tnozicka** [comment]
To me this sound like a bug. 

We clearly document that only passthrough won't work with path based routing for obvious reasons. 

This should work as per https://docs.openshift.org/latest/architecture/core_concepts/routes.html#path-based-routes

I also think there is a related bug with a path based routing between one route with HTTP only and the second one with HTTPS and with insecureEdgeTerminationPolicy (allow, redirect). https://github.com/tnozicka/openshift-acme/issues/11#issuecomment-310811312

**Comment by tnozicka** [comment]
@knobunc WDYT?

**Comment by knobunc** [comment]
@tnozicka yes, it certainly looks like a bug.

**Comment by tnozicka** [comment]
@JacobTanenbaum bump :)

**Comment by tnozicka** [comment]
@JacobTanenbaum any chance you could review the fix https://github.com/openshift/origin/pull/15847 ?
