### ISSUE TITLE
SetupHostPathVolumes failing

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14972]
Every extended test that uses SetupHostPathVolumes is suddenly failing:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended/798/

@eparis you made some other chcon changes lately, this failure appears to occur somewhere in here:

https://github.com/openshift/origin/blob/master/test/extended/util/framework.go#L1190-L1217

any chance this is related?

```
• Failure [32.662 seconds]
[image_ecosystem][mysql][Slow] openshift mysql replication
/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originj18B5x/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/mysql_replica.go:202
  MySQL replication template for 5.5: https://raw.githubusercontent.com/sclorg/mysql-container/master/5.5/examples/replica/mysql_replica.json [It]
  /openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originj18B5x/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/mysql_replica.go:200

  Expected error:
      <*exec.ExitError | 0xc420b69dc0>: {
          ProcessState: {
              pid: 25400,
              status: 256,
              rusage: {
                  Utime: {Sec: 0, Usec: 0},
                  Stime: {Sec: 0, Usec: 1956},
                  Maxrss: 42876,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 266,
                  Majflt: 0,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 0,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 1,
                  Nivcsw: 1,
              },
          },
          Stderr: nil,
      }
      exit status 1
  not to have occurred

  /openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originj18B5x/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/mysql_replica.go:89
```

@stevekuznetsov any other CI infrastructure changes that could be tripping up this logic?

**Comment by eparis** [comment]
It's certainly possible...  If auditd is running we should see something in `ausearch -m AVC -m SELINUX_ERR` (or just in /var/log/audit/audit.log)

If not these should show up in /var/log/messages.

**Comment by eparis** [comment]
And I'd want to know `rpm -q selinux-policy-targeted`

**Comment by stevekuznetsov** [comment]
We have the output of `ausearch -m AVC` in [this artifact](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended/798/s3/download/generated/avc_denials.log) for that failed job. @eparis should I add in `-m SELINUX_ERR` as well ?

There is an artifact [`installed_packages`](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended/798/s3/download/generated/installed_packages.log) that shows all installed packages...

```
libselinux.x86_64            2.5-6.el7            @oso-rhui-rhel-server-releases
libselinux-devel.x86_64      2.5-6.el7            @oso-rhui-rhel-server-releases
libselinux-python.x86_64     2.5-6.el7            @oso-rhui-rhel-server-releases
libselinux-utils.x86_64      2.5-6.el7            @oso-rhui-rhel-server-releases
selinux-policy.noarch        3.13.1-102.el7_3.16  @oso-rhui-rhel-server-releases
selinux-policy-targeted.noarch
                             3.13.1-102.el7_3.16  @oso-rhui-rhel-server-releases
container-selinux.noarch     2:2.12-2.gite7096ce.el7
                                                  @httpsmirroropenshiftcomenterpriserheldockertestedx8664os
```

**Comment by stevekuznetsov** [comment]
@bparees i don't have enough context as to what, exactly, is failing to say

**Comment by eparis** [comment]
@stevekuznetsov yes, lets add `-m SELINUX_ERR -m USER_AVC` to that. I tried tooling around to find those artifacts before I asked. I'll have to bother you later to see where I should have been looking...

**Comment by stevekuznetsov** [comment]
I'll add those messages. Will try to doc the artifacts we have and blast out an email.

**Comment by bparees** [comment]
@openshift/devex fyi this is causing the replica test failures in extended:core(image_ecosystem)

**Comment by coreydaley** [comment]
@stevekuznetsov @eparis Do you have any updates on what is causing this failure and how to fix it?

**Comment by stevekuznetsov** [comment]
@coreydaley do you have a recent failure? In that job, look at the artifacts (`generated/avc_denials.log` and `generated/installed_packages.log`) to answer the questions @eparis had above

**Comment by bparees** [comment]
recent failure: https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/test_branch_origin_extended_image_ecosystem/124/

**Comment by gabemontero** [comment]
With the https://ci.openshift.redhat.com/jenkins/view/All/job/test_branch_origin_extended_image_ecosystem/131/ failure, the `generated/avc_denials.log` simply has:

```
<no matches>
```

The `generated/installed_packages.log` has shows selinux related versions at:

```
grep --color -nH -e selinux installed_packages.log
container-selinux.noarch      2:2.19-2.1.el7   @httpsmirroropenshiftcomenterpriserheldockertestedx8664os
libselinux.x86_64             2.5-6.el7           @oso-rhui-rhel-server-releases
libselinux-devel.x86_64       2.5-6.el7           @oso-rhui-rhel-server-releases
libselinux-python.x86_64      2.5-6.el7           @oso-rhui-rhel-server-releases
libselinux-utils.x86_64       2.5-6.el7           @oso-rhui-rhel-server-releases
selinux-policy.noarch         3.13.1-102.el7_3.16 @oso-rhui-rhel-server-releases
selinux-policy-targeted.noarch 3.13.1-102.el7_3.16 @oso-rhui-rhel-server-releases

```

@eparis - does that provide any additional insight?

thanks

**Comment by gabemontero** [comment]
Yeah subsequent failures continue to have `<no matches>` in the avc_denials.log.

Any ideas if we need different ausearch args?  Or are we just barking up the wrong tree here?

**Comment by bparees** [comment]
doing some debug on this here: https://github.com/openshift/origin/pull/15553

**Comment by bparees** [comment]
this break was introduced here:
https://github.com/openshift/origin/pull/12942/files#diff-f4a17e7c84ee9f2a9cb2d480ebc033e9R1185
