### ISSUE TITLE
Conformance test cleanup error: You cannot remove a running container

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#14973]
Looks like all tests passed, but cleanup failed:

```
Ran 26 of 865 Specs in 826.754 seconds
SUCCESS! -- 26 Passed | 0 Failed | 2 Pending | 837 Skipped Jun 29 22:45:10.009: INFO: Error running cluster/log-dump.sh: fork/exec /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/cluster/log-dump.sh: no such file or directory
PASS

Ginkgo ran 1 suite in 13m47.229093346s
Test Suite Passed
[INFO] [CLEANUP] Beginning cleanup routines...
[INFO] [CLEANUP] Dumping cluster events to _output/scripts/conformance/artifacts/events.txt
Logged into "https://ip-172-18-6-65.ec2.internal:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default
    kube-public
    kube-system
    logging
    management-infra
    openshift
    openshift-infra

Using project "default".
[INFO] [CLEANUP] Dumping container logs to _output/scripts/conformance/logs/containers
[INFO] [CLEANUP] Truncating log files over 200M
[INFO] [CLEANUP] Stopping docker containers
[INFO] [CLEANUP] Removing docker containers
Error response from daemon: You cannot remove a running container 62eb30190f241d360108fcc65e881a5b9141a07019132461a62e86ee881f4271. Stop the container before attempting removal or use -f
Error response from daemon: You cannot remove a running container e78008e029baea3c1470ab37e06b6e1e57132a6c8ee12e04de7a05b46f454b5a. Stop the container before attempting removal or use -f
Error response from daemon: You cannot remove a running container b02399575da8ff6fc7e9a68b2e2ef2237eeeaa665691826e4ff1919191db0d7f. Stop the container before attempting removal or use -f
Error response from daemon: You cannot remove a running container b884f036987a2775c047e632ee781c6f929967aea1e550fa34bca421f3033339. Stop the container before attempting removal or use -f
[INFO] [CLEANUP] Killing child processes
[INFO] [CLEANUP] Pruning etcd data directory
rm: cannot remove ‘/tmp/etcd/member’: Permission denied
[ERROR] test/extended/conformance.sh exited with code 1 after 00h 45m 31s
make: *** [test-extended] Error 1
```

 Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/747/console

**Comment by stevekuznetsov** [comment]
This does not cause the job to fail and should not be linked as a flake.

**Comment by rhcarvalho** [comment]
@stevekuznetsov, if not what was reported here, could you please help identify what failed in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/747/console? Thanks.

**Comment by stevekuznetsov** [comment]
@rhcarvalho the best place to look for failures will be the [jUnit test report](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/747/testReport/) on that linked job, we can see that two tests ( [`Extended.[builds][Conformance] oc new-app should succeed with a --name of 58 characters`](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/747/testReport/junit/(root)/Extended/_builds__Conformance__oc_new_app_should_succeed_with_a___name_of_58_characters/) and [`Extended.[k8s.io] EmptyDir volumes should support (non-root,0666,default) [Conformance] [Volume]`](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_with_status_check/747/testReport/junit/(root)/Extended/_k8s_io__EmptyDir_volumes_should_support__non_root_0666_default___Conformance___Volume_/) ) failed.
