### ISSUE TITLE
'oc get po --show-all=false -w' is not working as expected

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14975]
It returns back all pods instead of just running pods.

@openshift/cli-review 

```
$ oc version
oc v3.6.0-alpha.2+49d3685-464
kubernetes v1.6.1+5115d708d7
```

**Comment by juanvallejo** [comment]
Upstream PR: https://github.com/kubernetes/kubernetes/pull/52051

**Comment by juanvallejo** [comment]
[Upstream PR](https://github.com/kubernetes/kubernetes/pull/52051) has merged.
Tagging as `post-rebase`

**Comment by kargakis** [comment]
@juanvallejo thanks!
