### ISSUE TITLE
oauthaccesstoken deleted with a propagation policy gets stuck

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#14976]
If I delete an oauthaccesstoken with a propagation policy set then it will get stuck and never be deleted.  Tested with both Foreground and Orphan.  The finalizers and deletionTimestamp get set and the object is never removed.

**Comment by deads2k** [comment]
So it appears that we explicitly ignore some resources for GC, but the storage doesn't get the memo, so they end up stuck. Even better, given that list, if I fix it this release and we change our minds, during a rolling upgrade we'll have a state where they end up stuck.
