### ISSUE TITLE
oc cluster up should start separate master and node containers

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#14981]
oc cluster up is a great development test environment.

when testing features (node controller, etc). its often useful to have a node come up, and then kill it without killing the master.  ideally, i could kill the node container and have the master still running.  if oc cluster up created a separate container for master from node, this would be possible to simulate.

/cc @csrwng

**Comment by csrwng** [comment]
This is addressed in the latest cluster up which starts everything separate.
/close
