### ISSUE TITLE
Panic on master when trying to use vSphere cloud provider

### ISSUE THREAD

**Issue by jtcressy** [openshift/origin#14995]
I'm trying to bootstrap a cluster via [openshift/openshift-ansible](https://github.com/openshift/openshift-ansible) and I have added tasks in the openshift_cloud_provider role to create cloud configs on all nodes and the master. But, the master is crashing with a full stack dump after first saying ``panic: runtime error: invalid memory address or nil pointer dereference``

##### Version
1.5.1
##### Steps To Reproduce
1. Create 1 master & 4 nodes based on Centos 7 on vsphere cluster, including dns etc. This cluster should work without trying to setup any cloud providers. (use the byo playbooks)
2. edit /etc/origin/master/master-config.yaml to point to cloud-config files for vsphere
3. restart master via ``systemctl restart origin-master``
4. stack trace viewable in ``journalctl -xe``

##### Current Result
``panic: runtime error: invalid memory address or nil pointer dereference``

##### Expected Result
openshift bootstraps kubelets with cloud configs for vsphere such that it can be used. I would like to use this for scheduling storage via the ``kubernetes.io/vsphere-volume`` storage driver.

##### Additional Information

Output of stack trace from systemd journal when trying to start the origin-master service: [origin-master-trimmed.log.txt](https://github.com/openshift/origin/files/1116917/origin-master-trimmed.log.txt)

Master config: [master-conf.yaml.txt](https://github.com/openshift/origin/files/1116920/master-conf.yaml.txt)

Example vsphere.conf cloud config: [vsphere.conf.txt](https://github.com/openshift/origin/files/1116919/vsphere.conf.txt)

**Comment by mfojtik** [comment]
Seems like there is related issue in kubernetes: https://github.com/kubernetes/kubernetes/issues/43471

Check if your topology is supported?

**Comment by jtcressy** [comment]
I'm not sure what "supported" would mean other than having your cluster be virtual machines running on the vsphere cluster. I made sure to enable uuid labeling on these VM's. I suppose there might be some disconnect since I didnt use kubernetes-anywhere to startup this cluster, but it outlines [here](https://kubernetes.io/docs/getting-started-guides/vsphere/#configuring-vsphere-cloud-provider) that you should be able to set it up even if you didnt bootstrap the cluster with kubernetes-anywhere.

**Comment by jtcressy** [comment]
It looks like this issue is fixed in kubernetes with https://github.com/kubernetes/kubernetes/pull/39752 and is staged for origin 3.7 release, however it looks like 3.7's release is months away just by glancing at the current roadmap. 

Is there any way we can backport a workaround for this issue? I haven't looked too deeply at the code just yet. 

I apologize for the impatience but i'm having severe storage problems on my production cluster which is relying on NFS-based persistent volumes. I need to use vsphere volumes to get rid of these permission issues that NFS is so fond of.
