### ISSUE TITLE
flake: Permission denied

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#14990]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/2889/testReport/junit/github/com_openshift_origin_test_cmd_cmd-images-namespace-setup/hack_test_cmd_sh_112__executing__oc_new_project__cmd_images___expecting_success/

```
github.com/openshift/origin/test/cmd/cmd-images-namespace-setup.hack/test-cmd.sh:112: executing 'oc new-project 'cmd-images'' expecting success (from github.com_openshift_origin_test_cmd_cmd-images-namespace-setup)

Failing for the past 1 build (Since Failed#2889 )
Took 0.81 sec.
add description
Error Message

the command returned the wrong error code
Stacktrace

=== BEGIN TEST CASE ===
hack/test-cmd.sh:112: executing 'oc new-project 'cmd-images'' expecting success
FAILURE after 0.815s: hack/test-cmd.sh:112: executing 'oc new-project 'cmd-images'' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server (InternalError): Internal error occurred: Operation cannot be fulfilled on policybindings.authorization.openshift.io ":default": the object has been modified; please apply your changes to the latest version and try again
=== END TEST CASE ===
```

**Comment by smarterclayton** [comment]
@deads2k wat

**Comment by deads2k** [comment]
> @deads2k wat

Blame the guy who wanted virtual resources. :)

Weird that it managed to conflict with itself. If it's common, we can try digging.  As I recall, we made it attempt to determine if there was diff in the conflict already.

**Comment by smarterclayton** [comment]
I've seen it on an uptick recently.  This is code I would not expect to fail though, so unless it's some incredibly random chance thing, we should identify where it is and stomp it.

**Comment by deads2k** [comment]
opened https://github.com/openshift/origin/pull/15027 to help debug the actor conflicting.

**Comment by deads2k** [comment]
Also, templates only create and creates retry on conflict here: https://github.com/openshift/origin/blob/master/pkg/authorization/registry/rolebinding/policybased/virtual_storage.go#L154

**Comment by pweil-** [comment]
cc @mfojtik

**Comment by simo5** [comment]
We moved to rbac so this should be gone, reopen if it resurfaces ?
