### ISSUE TITLE
Dependency on goversioninfo breaking OCP build

### ISSUE THREAD

**Issue by jupierce** [openshift/origin#14996]
The dependency introduced #14967 (goversioninfo) is breaking automated OCP builds:
FYI @smarterclayton @smunilla

##### Version
Current master

##### Steps To Reproduce
1. Run hack/build-cross.sh in clean mock environment

##### Current Result
http://download-node-02.eng.bos.redhat.com/brewroot/work/tasks/5032/13585032/build.log

```
+ hack/build-cross.sh
++ Building go targets for linux/amd64: images/pod cmd/dockerregistry cmd/gitserver vendor/k8s.io/kubernetes/cmd/hyperkube pkg/sdn/plugin/sdn-cni-plugin vendor/github.com/containernetworking/cni/plugins/ipam/host-local vendor/github.com/containernetworking/cni/plugins/main/loopback examples/hello-openshift
++ Building go targets for linux/amd64: cmd/openshift cmd/oc cmd/kubefed
++ Building go targets for darwin/amd64: cmd/openshift cmd/oc cmd/kubefed
++ Building go targets for windows/amd64: cmd/openshift cmd/oc cmd/kubefed
[FATAL] Required `goversioninfo` binary was not found in $GOPATH.
[ERROR] PID 84818: hack/lib/build/binaries.sh:152: `local -a binaries=("$@")` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/build/binaries.sh:152: `local -a binaries=("$@")`
[INFO] 		  2: hack/build-cross.sh:79: os::build::build_binaries
[INFO]   Exiting with code 1.
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.yrNw3b (%build)
    Bad exit status from /var/tmp/rpm-tmp.yrNw3b (%build)
Child return code was: 1
```

**Comment by shiywang** [comment]
I thought this pr https://github.com/openshift/origin-ci-tool/pull/115 already introduced `goversioninfo` binary, @stevekuznetsov do you have any ideas on why this binaries can't find ?

**Comment by smarterclayton** [comment]
I'm going to revert that change until we know what the fix is

On Jul 1, 2017, at 11:01 AM, Shiyang Wang <notifications@github.com> wrote:

I thought this pr openshift/origin-ci-tool#115
<https://github.com/openshift/origin-ci-tool/pull/115> already introduced
goversioninfo binary, @stevekuznetsov <https://github.com/stevekuznetsov>
do you have any ideas on why this binaries can't find ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/14996#issuecomment-312436826>,
or mute the thread

**Comment by smarterclayton** [comment]
Reverted in #14997

**Comment by stevekuznetsov** [comment]
@jupierce @smunilla is this a build on baby build VM? You just need to install the dependency.

**Comment by jupierce** [comment]
@stevekuznetsov This part of the build is performed by brew - on a separate sever / environment. Dependencies can be installed into the environment prior to a build (e.g. go), but I suspect they need to be RPMized if they are not vendored in the origin codebase. Are there analogous tools we use like this?

**Comment by stevekuznetsov** [comment]
We install [a number of tools](https://github.com/openshift/origin-ci-tool/blob/master/oct/ansible/oct/playbooks/prepare/golang.yml#L65-L70) using `go get` but I do not think any of them are build-time dependencies.

**Comment by jupierce** [comment]
Would we lose much if I run the command as part of the build pipeline prior to sending the job to brew? We do some preprocessing for origin-web-console with simple dependencies we can load on to buildvm. For example, https://github.com/openshift/aos-cd-jobs/blob/master/jobs/build/ose/scripts/merge-and-build.sh#L100 . We would need the step taken out of the default build-cross target (or make it build-cross smart enough to detect the command has already been run and not run it again).

**Comment by stevekuznetsov** [comment]
I agree with you -- I think the approach should be the same as for `go-bindata`. They're analogous dependencies. `build-cross` does not try to download the dependency, it just checks that it exists.

**Comment by fabianofranz** [comment]
@jupierce @stevekuznetsov anything you guys need from me here? I'd love to have this fixed before the new release, so that we can have signed binaries. Tks!

**Comment by stevekuznetsov** [comment]
Add logic to the `merge-and-build.sh` as linked above to install the new build time dependency

**Comment by jupierce** [comment]
Sorry.. pto and other fires causing distraction. 
@stevekuznetsov @fabianofranz I think there are three options:

1. Fast: build-cross can do a go install for goversioninfo before using it.
2. Medium: we can discuss whether it is possible to install goversioninfo in merge-and-build.sh and perform preprocessing on the source code *before* submitting a build to brew. build-cross would need to be changed to not execute goversioninfo this during every build. 
3. Slow: We can RPMize goversioninfo and make it available for brew builds.
