### ISSUE TITLE
With the upcoming release of version 3.6, we need to update the README.

### ISSUE THREAD

**Issue by warmchang** [openshift/origin#14994]
It is 5 month age, too long.

**Comment by mfojtik** [comment]
@smarterclayton @warmchang @adellape any ideas what we should update? ;-)

**Comment by warmchang** [comment]
Can update the features list which add/modifed in version 3.6 :smile: 
![image](https://user-images.githubusercontent.com/13084624/28162936-987c3b40-67fb-11e7-9d45-cd73a71a8a28.png)

**Comment by warmchang** [comment]
Close it by https://github.com/openshift/origin/commit/e6ec2150f79444aa40f272c740ca3ea1b6af914c
