### ISSUE TITLE
Extended.[builds][Slow] openshift pipeline build Pipeline with env vars should build and complete successfully

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14998]
This looks like a new failure mode for this test, the env var value is not getting set:

```
/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:380
Expected error:
    <*errors.errorString | 0xc420825070>: {
        s: "Error waiting for status 200 and verification regex \"FOO2 is BAR2\" from resource path http://172.30.95.27:80/job/extended-test-jenkins-pipeline-v0hrt-kln7m-sample-pipeline-withenvs/lastBuild/consoleText: timed out waiting for the condition",
    }
    Error waiting for status 200 and verification regex "FOO2 is BAR2" from resource path http://172.30.95.27:80/job/extended-test-jenkins-pipeline-v0hrt-kln7m-sample-pipeline-withenvs/lastBuild/consoleText: timed out waiting for the condition
not to have occurred
/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:344
```

```
Retrieving Jenkins resource: "http://172.30.95.27:80/job/extended-test-jenkins-pipeline-v0hrt-kln7m-sample-pipeline-withenvs/lastBuild/consoleText"
Content did not match verification regex "FOO2 is BAR2":
 OpenShift Build extended-test-jenkins-pipeline-v0hrt-kln7m/sample-pipeline-withenvs-1
[Pipeline] node
Running on master in /var/lib/jenkins/jobs/extended-test-jenkins-pipeline-v0hrt-kln7m-sample-pipeline-withenvs/workspace
[Pipeline] {
[Pipeline] echo
FOO1 is BAR1
[Pipeline] echo
FOO2 is null
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by bparees** [comment]
(jenkins job is here: https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/test_branch_origin_extended_builds/116)

**Comment by gabemontero** [comment]
Need a dump of the jenkins logs but test is currently not collecting that on failures here.

Will see if I can repro locally, otherwise will submit pull to grab the jenkins logs on this particular failure.

**Comment by gabemontero** [comment]
OK, it worked for me when running by hand, but I was able to reproduced when running the extended test locally.

There are no exceptions when the error occurs.

I think it is a timing situation wrt watch events and the application of openshift env vars as jenkins job params, where if the events come in the wrong order, the env var specified on the `oc start-build` cmd line does not get applied.

I'll need to study / compare the successful and failing runs some more.

**Comment by gabemontero** [comment]
Definitely intermittent / timing ... I've had the extended test pass for me locally as well.

**Comment by gabemontero** [comment]
Yeah at first blush the event flow are the same between failed and passing runs.

Also, the build object during the failed run, when running `oc get build...` outside of jenkins, shows the env var from the command line was in the object.

I think this will require adding debug to the plugin to dump what it receives on its watches when it fails.

**Comment by gabemontero** [comment]
Digging a bit, aside from the event flow, processing of the events in the sync plugin as asynchronous aspects, both for the BC events and Build events.  It is still an intermittent timing issue of some sort, it just is not obvious to me from code examination.  As noted previously, running the test with some additional logging in the plugin, seeing if I can capture the precise order of things that results in the BC's default env var list taking hold.

**Comment by gabemontero** [comment]
Haven't repro'ed to confirm, but believe I've figured it out.  At least what would line up with the BC and Build being created very close to each other as would happen in an automated test vs. running by hand.

I can start on a fix @bparees but there are some logistics to consider:
1) do you want the sync-plugin fix in 3.6 ?
2) if so, then I'll need to create in https://github.com/jenkinsci/openshift-sync-plugin first, then cherry pick back into https://github.com/openshift/jenkins-sync-plugin
3) otherwise I can do the normal flow, even addressing in our current ext tests, but we just don't build an RPM for the new sync-plugin version

**Comment by bparees** [comment]
it feels like something we should fix for 3.6 (the ramifications seem bad).  that said, i think you're out all next week, right?  can you point me in the general direction of the issue?  (if we're going to fix it we need it in by friday at the latest..probably sooner given the overhead in spinning new jenkins images)

**Comment by gabemontero** [comment]
On Sun, Jul 2, 2017 at 11:18 PM Ben Parees <notifications@github.com> wrote:

> it feels like something we should fix for 3.6 (the ramifications seem
> bad). that said, i think you're out all next week, right? can you point me
> in the general direction of the issue? (if we're going to fix it we need it
> in by friday at the latest..probably sooner given the overhead in spinning
> new jenkins images
>
)
>

I have the fix ready.  I'll create the PR after breakfast.  The PR will be
in https://github.com/jenkinsci/openshift-sync-plugin.
We can cut the new version image from that and then cherry pick back into
https://github.com/openshift/jenkins/jenkins-sync-plugin later.  There is
some commit cleanup that will have to happen post 3.6 GA to get the two
repos fully in sync.

**Comment by bparees** [comment]
thanks!

**Comment by gabemontero** [comment]
hey @bparees - v0.1.23 of the sync plugin, which contains the fix previously discussed, is not available at https://updates.jenkins-ci.org/download/plugins/openshift-sync/0.1.23/openshift-sync.hpi

You and @smunilla should be able to pull it into the appropriate versions of the jenkins centos/rhel images.

Of course, once the image has been updated, the next round of extended test runs should pick it up, and we should be able to close this issue.

**Comment by bparees** [comment]
awesome, thank you @gabemontero!

**Comment by bparees** [comment]
centos bump is here:
https://github.com/openshift/jenkins/pull/329
