### ISSUE TITLE
Some rolebindingrestrictions cannot be storage migrated because of a missing namespace

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15006]
From a prod dataset being tested in #14999.  Migration being run on some role binding restrictions is failing.

```
error:     -n AAA rolebindingrestrictions/match-project-admin-user: namespaces "AAA" not found
error:     -n BBB rolebindingrestrictions/match-project-admin-user: namespaces "BBB" not found
```

First, this means that something in the update path is checking for namespace existence on these RBRs.  However, if the namespace isn't being changed during an RBR, it shouldn't be checked.  That's probably the minimal bug that needs to be fixed here.  

However, if the namespace doesn't exist, why is the RBR blocking?  RBR shouldn't require a namespace to exist in order to mutate it, unless permission checks are required, and if permission checks ARE required, then it needs to be cleaned up prior to deletion, which it apparently was not.

Would like an answer before we deploy 3.6 to a prod env on Wednesday

@jupierce @Miciah

**Comment by deads2k** [comment]
> First, this means that something in the update path is checking for namespace existence on these RBRs

Namespace lifecycle admission plugin?

**Comment by Miciah** [comment]
> Namespace lifecycle admission plugin?

I don't see a reason that would affect rolebindingrestrictions specifically though.

**Comment by deads2k** [comment]
> I don't see a reason that would affect rolebindingrestrictions specifically though.

You didn't get cleaned up when a namespace was deleted.  I remember a bug about it.

**Comment by Miciah** [comment]
That would be https://github.com/openshift/origin/pull/13563.

We cleaned up the rolebindingrestrictions that had been created before we fixed the problem, but maybe this cluster got left out of the cleanup.  I'll dig up the script we gave to ops.

@smarterclayton, do we need to fix anything in migration if these are just rolebindingrestrictions that were created before we fixed the namespace controller to reap rolebindingrestrictions?

**Comment by jupierce** [comment]
@Miciah sent these scripts to the CD team. We will be running them on our free & starter clusters to ensure there are no hiccups during their eventual migration. @smarterclayton ok to remove as delivery-blocker?

**Comment by smarterclayton** [comment]
It's ok to remove as deliver blocker.

As far as having invalid data, no update should block on not existing
external references, so I'd like this fixed.  Update is required to work on
Get, no exceptions

On Jul 5, 2017, at 9:24 AM, Justin Pierce <notifications@github.com> wrote:

@Miciah <https://github.com/miciah> sent these scripts to the CD team. We
will be running them on our free & starter clusters to ensure there are no
hiccups during their eventual migration. @smarterclayton
<https://github.com/smarterclayton> ok to remove as delivery-blocker?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15006#issuecomment-313101771>,
or mute the thread

**Comment by smarterclayton** [comment]
Note that this failure breaks upgrades for users (now that upgrade is in the path).  So will have to be fixed in 3.6.x.

**Comment by liggitt** [comment]
https://github.com/openshift/origin/pull/15123 fixes admission to allow cleanup of orphaned objects even when the namespace doesn't exist

backports in https://github.com/openshift/ose/pull/800 and https://github.com/openshift/ose/pull/801

**Comment by enj** [comment]
@smarterclayton the namespace lifecycle bits are fixed now and I helped @jupierce clean up the upgrade issues.  Based on my discussions with @liggitt our customers are unlikely to hit this since online is the primary user of RBR.  Thus I do not think we need to add complexity to our ansible flow to handle auto deleting these orphaned objects.  WDYT?

**Comment by smarterclayton** [comment]
Agree, and users have a manual workaround.

Have we changed ansible to do the full migration yet?

**Comment by enj** [comment]
I do not know what you mean by "full migration" - storage migration runs with `--include=*` as of openshift/openshift-ansible/pull/4533

**Comment by smarterclayton** [comment]
Yes, that is full migration.

**Comment by smarterclayton** [comment]
So I still expect a fix in master (maybe not for 3.6.0) which prevents updates on role binding restrictions that are invalid from failing if the user hasn't changed something.  Updates that don't change shouldn't fail, period.

**Comment by liggitt** [comment]
> So I still expect a fix in master (maybe not for 3.6.0) which prevents updates on role binding restrictions that are invalid from failing if the user hasn't changed something. Updates that don't change shouldn't fail, period.

I thought the point of the migration tool was that there might be changes server-side (in storage content-type or version) that wouldn't be observable from the client side.

**Comment by adelton** [comment]
@smarterclayton, so what is the best way to determine that user hasn't changed anything?

Also, how about @liggitt's point that user might not have changed anything but there might be changes forced by something on server's side?

In general, isn't this mostly about the architecture of the upgrades and user experience? How exactly is this related to component/auth or area/security?

**Comment by smarterclayton** [comment]
Much of the validation code for Updates does that check.

Server side changes are usually done by someone with permissions.

It's component/auth because that's who owns the code that is not conformant
(the rolebinding restriction code)

On Sep 8, 2017, at 4:48 AM, Jan Pazdziora <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton>, so what is the best
way to determine that user hasn't changed anything?

Also, how about @liggitt <https://github.com/liggitt>'s point that user
might not have changed anything but there might be changes forced by
something on server's side?

In general, isn't this mostly about the architecture of the upgrades and
user experience? How exactly is this related to component/auth or
area/security?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15006#issuecomment-328043430>,
or mute the thread

**Comment by enj** [comment]
> what is the best way to determine that user hasn't changed anything?

So migrate can always tell if something was changed when the resource version returned is different.

But there is not a good way to guarantee that an update that changes nothing never fails.
