### ISSUE TITLE
Migration of prod cluster blocked on builds and build configs that fail Git URI validation

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15005]
In a prod data set being tested on 3.6

```
error:     -n XXXX buildconfigs/XXXXX: BuildConfig "XXXXX" is invalid: spec.source.git.uri: Invalid value: "git@github.com:REPO/NAME.git": uri is not a valid url
```

Our URI must support `git@SERVER:PATH`.

This blocks underlying migration of data in 3.6, and may have broken end users.

@jupierce @bparees we cannot promote 3.6 to prod without resolving this or determining it is not an issue.

**Comment by smarterclayton** [comment]
Found in #14999

**Comment by bparees** [comment]
@smarterclayton was this built on go1.8?  it looks/sounds similar to the discussions here:

https://github.com/openshift/origin/issues/14831
https://github.com/openshift/origin/issues/12403

which are specifically triggered by golang changing url.Parse in 1.8.

**Comment by smarterclayton** [comment]
Yes, will retest without.  Note we are possibly going to switch to go 1.8 during the 3.6 lifecycle so we should fix before we forget it

**Comment by smarterclayton** [comment]
Dropping to p1

**Comment by smarterclayton** [comment]
Confirmed works on 1.7.5

**Comment by bparees** [comment]
@coreydaley same as https://github.com/openshift/origin/issues/14831

**Comment by jim-minter** [comment]
FYI as things stand I don't believe this is a blocker for 3.6.0 - intending to merge a fix early in 3.7 in such a way as can be backported to 3.6.x if a decision is taken to move to go 1.8 for 3.6.x.

**Comment by bparees** [comment]
@jim-minter correct, it's not a blocker for 3.6.0 ( @smarterclayton didn't realize it was golang1.8 specific) but it's been requested that we preemptively backport to the 3.6.x branch, presumably as soon as 3.6.0 goes out.  So you can count on that :)

I'm going to move it to a p2 since it's not a blocker for 3.6.0.

**Comment by bparees** [comment]
p1 since this is now blocking the rebase.  still not a blocker for 3.6.0 though, so we'll need to sort through how @deads2k wants to cherry-pick the fix (once it's ready) into his rebase.
