### ISSUE TITLE
test/cmd/newapp.sh test flake - late completion of repository import

### ISSUE THREAD

**Issue by miminar** [openshift/origin#15015]
```
=== BEGIN TEST CASE ===
test/cmd/newapp.sh:29: executing 'oc get imagestreamtags mysql:5.6' expecting success; re-trying every 0.2s until completion or 60.000s
FAILURE after 59.644s: test/cmd/newapp.sh:29: executing 'oc get imagestreamtags mysql:5.6' expecting success; re-trying every 0.2s until completion or 60.000s: the command timed out
Standard output from the command:
Standard error from the command:
Error from server (NotFound): imagestreamtags.image.openshift.io "mysql:5.6" not found
... repeated 106 times
=== END TEST CASE ===
```

In [this job ](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_check/4086/testReport/junit/github/com_openshift_origin_test_cmd_newapp/test_cmd_newapp_sh_29__executing__oc_get_imagestreamtags_mysql_5_6__expecting_success__re_trying_every_0_2s_until_completion_or_60_000s/).

In the master log I can see that the import has been finished a while after the lastest check for the `mysql:5.6` istag:

```
I0703 11:27:33.987853   10348 wrap.go:42] GET /oapi/v1/namespaces/cmd-newapp/imagestreamtags/mysql:5.6: (2.131133ms) 404 [[oc/v1.6.1+5115d708d7 (linux/amd64) kubernetes/314edd5] 172.17.0.2:47492]
I0703 11:32:05.890608   10348 factory.go:185] Image stream "mysql" updated.
``` 

Late by 5 seconds. Shall we extend the timeout to 2 minutes?

**Comment by bparees** [comment]
> Late by 5 seconds. Shall we extend the timeout to 2 minutes?

i think so.
