### ISSUE TITLE
add 127.0.0.1.nip.io to DefaultAllowedRegistriesForImport

### ISSUE THREAD

**Issue by goern** [openshift/origin#15033]
add 127.0.0.1.nip.io to https://github.com/openshift/origin/blob/7d28dcbf839c6eaaecd70a9f3b808abcf6c0ac47/pkg/cmd/server/api/types.go#L139  so that registries hosted on the local cluster could be used to pull from. This will significantly reduce friction if testing with Artifactory ;)

##### Version
oc v3.6.0-alpha.2+3c221d5

##### Steps To Reproduce
This is a RFE

##### Current Result
```
$ oc import-image busybox:latest --from artifactory-artifactory-test.127.0.0.1.nip.io/artifactory/docker-io-remote/busybox:latest --confirm 
The ImageStreamImport "busybox" is invalid: spec.images[0].from.name: Invalid value: "docker-io-remote/busybox": importing images from registry "artifactory-artifactory-test.127.0.0.1.nip.io:443" is forbidden, only images from "172.30.1.1:5000,docker.io,*.docker.io,registry.access.redhat.com,gcr.io,quay.io,*.amazonaws.com" are allowed
```

##### Expected Result
```
$ oc 2>&1 >/dev/null import-image busybox:latest --from artifactory-artifactory-test.127.0.0.1.nip.io/artifactory/docker-io-remote/busybox:latest --confirm
$ echo $?
0
```

##### Additional Information
N/A

**Comment by mfojtik** [comment]
@goern see https://github.com/openshift/origin/pull/15919

**Comment by soltysh** [comment]
Based on https://github.com/openshift/origin/pull/15919#issuecomment-325671198 we won't add non-production defaults. 
/close
