### ISSUE TITLE
If run fails because the container has an error, no output printed

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15031]
```
$ oc run --restart=Never --image centos:7 -it --attach debug -- /bin/bas
$ echo $?
127
```

Should have displayed an error. Very annoying.

**Comment by fabianofranz** [comment]
@sttts Do you recall what's the reason for not printing the exit error message in cases like this? Looks like it was intentional, the description of `--attach` flag mentions it.

**Comment by sttts** [comment]
@fabianofranz do we know the error message? The 127 can come from `/bin/bas` not existing or from `oc run --restart=Never --image centos:7 -it --attach debug -- /bin/bash -c "exit 127"`. A look into the kubelet and the docker API might tell us.

**Comment by smarterclayton** [comment]
In this case we get a distinct error status from the container runtime, so
it should be on the pod.

**Comment by fabianofranz** [comment]
Unrelated to the message, what I was wondering was the reason why we deliberatelly decided to not print any output message in those cases, `run` returns a `CodeExitError` [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/run.go#L364-L367) whose message gets ignored by `CheckError` [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/helpers.go#L170-L171) (code comment says "do not print anything, only terminate with given error").

**Comment by fabianofranz** [comment]
Anyways the pod is left in the `ContainerCannotRun` state with the message 

```
invalid header field value "oci runtime error: container_linux.go:247:
            starting container process caused \"exec: \\\"/bin/bas\\\": stat /bin/bas:
            no such file or directory\"\n"
```

**Comment by sttts** [comment]
Cannot really remember. I believe we didn't have a proper error message at that time. The one above is also ugly. Where does the "invalid header field value" come from?

**Comment by smarterclayton** [comment]
Probably all the way from the node - Derek had fixed something in here
recently to clean up the errors for 1.7 but I don't know if he backported
@derekwaynecarr or if the attach code in the kubelet is affected.
 log/attach/portforward need to get a lot better in how they handle errors
for clients, up to and including retrying

**Comment by smarterclayton** [comment]
If this isn't easy it's something we can defer.  It's pretty annoying...

**Comment by fabianofranz** [comment]
I'd say we rely on the current `state.terminated.message`, it's ugly today but at least gives you the real reason and can be improved server-side in future. @sttts @smarterclayton works for you?

**Comment by fabianofranz** [comment]
Fixed in https://github.com/openshift/origin/pull/15090, @smarterclayton @sttts PTAL.
