### ISSUE TITLE
Analyse logs

### ISSUE THREAD

**Issue by mrsiano** [openshift/origin#15042]
Im new to openshift \ kubernets 
I faced some issues to start the master node, when I start debug it, I found the '/var/log/messages  a bit inefficient to analyse.
it will be nicer to have an advance format or dedicate log.

meanwhile we can start with some tagging for errors e.g: '[ERROR]' as first string
bear in mind that some other logs don't have an any error indication (in the actual log message).

see
https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/ensure.go#L74
this one is has no error message but compare to 
glog.Errorf("Unable to create default security context constraint %s.  Got error: %v", scc.Name, err)
which has the "Got error" string
or some other had 'error first' 

either way, they can be filtered by simple grep, but some other can not.

we should formalised this file and may be others to report '[ERROR]' nicely.

##### Version
v3.6.133

@jeremyeder @sjug

**Comment by mrsiano** [comment]
@smarterclayton 
hi, could you review it ?

**Comment by pweil-** [comment]
in glog the errors are prefixed with the level  (E, W, I), it is the first character of the line.  You can grep for statements that are logged with `glog.Errorf` using that.

Example of some warnings and info:
```
W0711 14:37:49.832193   25746 genericapiserver.go:295] Skipping API autoscaling/v2alpha1 because it has no resources.
I0711 14:37:49.849201   25746 reflector.go:236] Listing and watching *apps.StatefulSet from github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215
W0711 14:37:49.871547   25746 genericapiserver.go:295] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
```

**Comment by mrsiano** [comment]
Awesome !
thanks for the explanation ..
