### ISSUE TITLE
Enable audit logging for e2e tests

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15041]
During e2e to tests it is very useful to know who is doing what against the API.  The audit log for this purpose.  https://github.com/openshift/origin/pull/15027 turned it on for test-cmd, but it would be good to have on in all of our e2e tests.

**Comment by stevekuznetsov** [comment]
@sdodson is this available to us as a var for the installer?

**Comment by sdodson** [comment]
openshift_master_audit_config='{"enabled": true}'

should be enough but you can pass in the full yaml value as json if you want more configurability
https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example#L809-L816

**Comment by stevekuznetsov** [comment]
@deads2k can you add:

```yaml
openshift_master_audit_config:
  enabled: true
```

To the [CI inventory](https://github.com/openshift/aos-cd-jobs/blob/master/sjb/inventory/group_vars/OSEv3/general.yml) to enable this for other tests?
