### ISSUE TITLE
Add more context in deployment logs

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15054]
Like when an app pod is crashlooping or the image cannot be pulled. 

@mfojtik @tnozicka @smarterclayton

**Comment by smarterclayton** [comment]
In general the deployer pod has *all* of the pod and RC info, so it can output info like the current progress, things that might blocking, etc almost as soon as they happen.  That would be a significant step up in how users interact.

I.e.:

```
--> deploying blah blha blah
    warning: pod 1 restarted immediately with exit code: 127 (message: .....)
```

**Comment by kargakis** [comment]
@tnozicka @mfojtik can you update the milestone if this is not meant to land in 3.7?

**Comment by tnozicka** [comment]
I like the idea; targeting this 3.8
