### ISSUE TITLE
Extended.DNS should answer endpoint and wildcard queries for the cluster

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15059]
```
/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originC4Pt6i/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/test/extended/dns/dns.go:378
Jul  5 14:05:45.327: Unexpected results: unexpected count 9/10 for "test_udp@_http._tcp.externalname.e2e-tests-dns-mkx0t.svc": map[]
/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originC4Pt6i/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/test/extended/dns/dns.go:233
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/4100/

**Comment by bparees** [comment]
@sttts you win the "last one to touch the test file" competition.  Feel free to reassign if you're not the best person for this.

**Comment by sttts** [comment]
Was this a one-time flake until now? I would reduce priority until this happens again.

**Comment by bparees** [comment]
i'm assuming so, i didn't find an existing issue when i opened it and i guess no one has seen it since though it's only been 6 days.  Anyway lowering the severity for now seems ok since it's not frequently recurring.

**Comment by sosiouxme** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18186/test_pull_request_origin_extended_conformance_gce/14947/

**Comment by sjenning** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19040/test_pull_request_origin_extended_conformance_install/9640/

**Comment by gabemontero** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20492/test_pull_request_origin_extended_conformance_install/14140/
