### ISSUE TITLE
flake: Can't join running container network

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15052]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/2966/testReport/junit/(root)/Extended/_networking__services_when_using_a_plugin_that_isolates_namespaces_by_default_should_allow_connections_to_services_in_the_default_namespace_from_a_pod_in_another_namespace_on_the_same_node/

```
Extended.[networking] services when using a plugin that isolates namespaces by default should allow connections to services in the default namespace from a pod in another namespace on the same node (from (networking_multitenant_true_01.xml))

Failing for the past 1 build (Since Failed#2966 )
Took 50 sec.
add description
Stacktrace

/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/networking/services.go:51
Expected success, but got an error:
    <*errors.errorString | 0xc421849c60>: {
        s: "pod 'service-wget' terminated with failure: &ContainerStateTerminated{ExitCode:128,Signal:0,Reason:ContainerCannotRun,Message:cannot join network of a non running container: 2d5a6e62f897d94f487b20401770326856fb6444436b7f51745b336a599edb30,StartedAt:2017-07-05 10:30:39 -0400 EDT,FinishedAt:2017-07-05 10:30:39 -0400 EDT,ContainerID:docker://942a44616e35bb7fbcab58d8f65ddc11210c4e4663a0805ced93bbdc5cf3f018,}",
    }
    pod 'service-wget' terminated with failure: &ContainerStateTerminated{ExitCode:128,Signal:0,Reason:ContainerCannotRun,Message:cannot join network of a non running container: 2d5a6e62f897d94f487b20401770326856fb6444436b7f51745b336a599edb30,StartedAt:2017-07-05 10:30:39 -0400 EDT,FinishedAt:2017-07-05 10:30:39 -0400 EDT,ContainerID:docker://942a44616e35bb7fbcab58d8f65ddc11210c4e4663a0805ced93bbdc5cf3f018,}
/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/networking/services.go:50
Standard Output

[BeforeEach] [Top Level]
  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/test.go:52
[BeforeEach] when using a plugin that isolates namespaces by default
  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/networking/util.go:270
[BeforeEach] when using a plugin that isolates namespaces by default
  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:120
�[1mSTEP�[0m: Creating a kubernetes client
Jul  5 10:30:27.475: INFO: >>> kubeConfig: /tmp/openshift/networking-minimal/multitenant/openshift.local.config/master/admin.kubeconfig

�[1mSTEP�[0m: Building a namespace api object
�[1mSTEP�[0m: Waiting for a default service account to be provisioned in namespace
[BeforeEach] when using a plugin that isolates namespaces by default
  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:120
�[1mSTEP�[0m: Creating a kubernetes client
Jul  5 10:30:27.552: INFO: >>> kubeConfig: /tmp/openshift/networking-minimal/multitenant/openshift.local.config/master/admin.kubeconfig

�[1mSTEP�[0m: Building a namespace api object
�[1mSTEP�[0m: Waiting for a default service account to be provisioned in namespace
[It] should allow connections to services in the default namespace from a pod in another namespace on the same node
  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/networking/services.go:51
Jul  5 10:30:31.650: INFO: Target pod IP:port is 10.128.0.4:8080
Jul  5 10:30:31.668: INFO: Endpoint e2e-tests-net-services1-h6494/service-55whr is not ready yet
Jul  5 10:30:36.672: INFO: Target service IP:port is 172.30.226.230:8080
Jul  5 10:30:36.680: INFO: Waiting up to 5m0s for pod service-wget                                            status to be success or failure
Jul  5 10:30:36.682: INFO: No Status.Info for container 'service-wget-container' in pod 'service-wget' yet
Jul  5 10:30:36.682: INFO: Waiting for pod service-wget                                            in namespace 'e2e-tests-net-services2-wf6cf' status to be 'success or failure'(found phase: "Pending", readiness: false) (1.915377ms elapsed)
Jul  5 10:30:41.685: INFO: Nil State.Terminated for container 'service-wget-container' in pod 'service-wget' in namespace 'e2e-tests-net-services2-wf6cf' so far
Jul  5 10:30:41.685: INFO: Waiting for pod service-wget                                            in namespace 'e2e-tests-net-services2-wf6cf' status to be 'success or failure'(found phase: "Pending", readiness: false) (5.004462147s elapsed)
Jul  5 10:30:46.687: INFO: Nil State.Terminated for container 'service-wget-container' in pod 'service-wget' in namespace 'e2e-tests-net-services2-wf6cf' so far
Jul  5 10:30:46.687: INFO: Waiting for pod service-wget                                            in namespace 'e2e-tests-net-services2-wf6cf' status to be 'success or failure'(found phase: "Pending", readiness: false) (10.006887626s elapsed)
Jul  5 10:30:51.690: INFO: Nil State.Terminated for container 'service-wget-container' in pod 'service-wget' in namespace 'e2e-tests-net-services2-wf6cf' so far
Jul  5 10:30:51.690: INFO: Waiting for pod service-wget                                            in namespace 'e2e-tests-net-services2-wf6cf' status to be 'success or failure'(found phase: "Pending", readiness: false) (15.009405407s elapsed)
[AfterEach] when using a plugin that isolates namespaces by default
  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:121
�[1mSTEP�[0m: Collecting events from namespace "e2e-tests-net-services1-h6494".
�[1mSTEP�[0m: Found 5 events.
Jul  5 10:30:56.730: INFO: At 2017-07-05 10:30:27 -0400 EDT - event for service-55whr: {kubelet nettest-node-1} MissingClusterDNS: kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
Jul  5 10:30:56.730: INFO: At 2017-07-05 10:30:28 -0400 EDT - event for service-55whr: {kubelet nettest-node-1} Pulling: pulling image "gcr.io/google_containers/porter:cd5cb5791ebaa8641955f0e8c2a9bed669b1eaab"
Jul  5 10:30:56.730: INFO: At 2017-07-05 10:30:29 -0400 EDT - event for service-55whr: {kubelet nettest-node-1} Pulled: Successfully pulled image "gcr.io/google_containers/porter:cd5cb5791ebaa8641955f0e8c2a9bed669b1eaab"
Jul  5 10:30:56.730: INFO: At 2017-07-05 10:30:29 -0400 EDT - event for service-55whr: {kubelet nettest-node-1} Created: Created container
Jul  5 10:30:56.730: INFO: At 2017-07-05 10:30:29 -0400 EDT - event for service-55whr: {kubelet nettest-node-1} Started: Started container
Jul  5 10:30:56.739: INFO: POD            NODE            PHASE    GRACE  CONDITIONS
Jul  5 10:30:56.739: INFO: service-55whr  nettest-node-1  Running  30s    [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-07-05 10:30:27 -0400 EDT  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-07-05 10:30:29 -0400 EDT  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-07-05 10:30:29 -0400 EDT  }]
Jul  5 10:30:56.739: INFO: 
```

**Comment by smarterclayton** [comment]
@openshift/networking needs triage

**Comment by danwinship** [comment]
Jul 05 14:30:37 nettest-node-1 openshift[256]: I0705 14:30:37.226085     256 ovs.go:139] Executing: ovs-vsctl --may-exist add-port br0 veth99a9802f
    Jul 05 14:30:37 nettest-node-1 ovs-vsctl[2082]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --may-exist add-port br0 veth99a9802f
    Jul 05 14:30:37 nettest-node-1 openshift[256]: I0705 14:30:37.242379     256 ovs.go:139] Executing: ovs-vsctl get Interface veth99a9802f ofport
    Jul 05 14:30:37 nettest-node-1 openshift[256]: I0705 14:30:37.251949     256 ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=-1, arp, nw_src=10.128.0.5, arp_sha=0a:58:0a:80:00:05, actions=load:16444317->NXM_NX_REG0[], note:2d.5a.6e.62.f8.97.d9.4f.48.7b.20.40.17.70.32.68.56.fb.64.44.43.6b.7f.51.74.5b.33.6a.59.9e.db.30, goto_table:21
    Jul 05 14:30:37 nettest-node-1 ovs-ofctl[2094]: ovs|00001|ofp_util|WARN|Negative value -1 is not a valid port number.
    Jul 05 14:30:37 nettest-node-1 openshift[256]: I0705 14:30:37.257972     256 ovs.go:143] Error executing ovs-ofctl: 2017-07-05T14:30:37Z|00001|ofp_util|WARN|Negative value -1 is not a valid port number.

So we successfully added the veth, but are then told that its OVS port is -1.
(This is not the same as #14708, which happens adding the vxlan tunnel at startup; this happens after other containers have successfully been created.)

This seems to happen sporadically throughout the test run, it just took a while to cause a test to actually fail:

    ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=3, arp, nw_src=10.128.0.2, arp_sha=...
    ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=4, arp, nw_src=10.128.0.3, arp_sha=...
    ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=5, arp, nw_src=10.128.0.4, arp_sha=...
    ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=-1, arp, nw_src=10.128.0.5, arp_sha=...
    ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=6, arp, nw_src=10.128.0.6, arp_sha=...
    ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=7, arp, nw_src=10.128.0.7, arp_sha=...
    ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=-1, arp, nw_src=10.128.0.8, arp_sha=...
    ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=8, arp, nw_src=10.128.0.9, arp_sha=...
    ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=9, arp, nw_src=10.128.0.10, arp_sha=...
    ovs.go:139] Executing: ovs-ofctl -O OpenFlow13 add-flow br0 table=20, priority=100, in_port=10, arp, nw_src=10.128.0.11, arp_sha=...

But the "-1"s don't show up in successful test runs (or even on node-2 of the same test run).

**Comment by danwinship** [comment]
and it's (presumably) not that there's a race condition and we need to wait before calling "get port", because otherwise we'd (presumably) see a gap in the port numbering above (eg skipping `in_port=6`)

logs don't show any errors from ovs

**Comment by dcbw** [comment]
true.  looks like the port gets added to the database, then the vswitchd notices and adds the port, then writes the update to the database.  we read in between.

**Comment by danwinship** [comment]
You missed the "not" in my comment. If the problem was that we were racing, then the first "-1" would be getting allocated port 6 some time shortly after we failed to read its port number, and so the next veth should get port 7 and so we'd see `in_port=-1` followed by `in_port=7`. Unless we `del-port`ed the port before vswitchd allocated a port to it, but in fact, we never del-port the port at all in this case. The logs show no further references to the relevant veth interface.

**Comment by dcbw** [comment]
I'm not convinced the vswitchd acts as we expect here yet.  Its code does iterate over the current database state and add ports, in an order determined by a hash map which may not the be same order we added ports to the database in.  Which could account for why the next port gets 6, if it showed up earlier while iterating the map.  But it may also do the right thing.

Though as aconole suggested, we should also read the database and see if the error field is set too.

**Comment by dcbw** [comment]
@danwinship after doing some testing with ovs-vsctl, it appears it does wait until the vswitchd has fully configured the port including the ofport_request.  So yeah, no race, it must be an internal failure of some kind that we can't see because we aren't logging it.

**Comment by danwinship** [comment]
same underlying problem as #12544
