### ISSUE TITLE
grace-period isn't passed through `oc delete --cascade=false`

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15060]
`oc delete pod --all --grace-period=0 --force --cascade=false` does not set the grace period to zero in its request.   The plumbing is missing here:  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/delete.go#L244 .

Without this power, when GC is enabled (all the time), you no longer a way to express: "delete it now".

@juanvallejo @fabianofranz

**Comment by deads2k** [comment]
We need some way to actually delete an item "now".  Starting off as a blocker until we find that way.

**Comment by fabianofranz** [comment]
Fixed in https://github.com/openshift/origin/pull/15091, @deads2k PTAL.
@juanvallejo sorry, picked this one to try to get it in before code freeze.  ;)

**Comment by smarterclayton** [comment]
Probably need `--override-finalizers` but it has to be optional.

**Comment by deads2k** [comment]
@smarterclayton `oc delete --force --now --grace-period=0 --override-finalizers --for-the-love-of-god-just-delete-it-already!!!!` ?

**Comment by smarterclayton** [comment]
that too

**Comment by smarterclayton** [comment]
--who-do-I-have-to-bribe-to-delete-this-already
