### ISSUE TITLE
How to stop crushing apiserver on events

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15079]
For the unidler, we don't actually care about any events older than about 30 seconds because the request has already failed at the router at that point.  This means that a full relist in a large cluster is useless to us because it takes more than 30 seconds to get the result of that list.  What we really want is a very fast way to get the most current RV and then use that RV to establish a watch as quickly as possible.  We could do this by doing a list inside of the default namespace (should have few events), discard all the events, only return the RV, and start watching.  We could then track the biggest RV we see from events and use *that* RV to restablish a watch (the reflector may already do this, not sure).

The biggest edge is a failover scenario in a small cluster.  Those events may still be useful from a list and this code woudl simply discard them.  Perhaps a separate list call run in a different gofunc or something?

@ironcladlou something to consider.  Feel free to modify the description for readability and/or declare the idea untenable.

**Comment by ironcladlou** [comment]
Here's my take on how the unidler works.

1. The controller [watches all events in the system](https://github.com/openshift/origin/blob/HEAD/pkg/unidling/controller/unidling_controller.go#L95), but ultimately discards/ignores almost all events looking for ones which [have a certain reason](https://github.com/openshift/origin/blob/HEAD/pkg/unidling/controller/unidling_controller.go#L178) assigned to drive unidling.
2. The unidler proxy [generates the one kind of event](https://github.com/openshift/origin/blob/HEAD/pkg/proxy/unidler/unidlerproxy.go#L41) the controller cares about.

This seems fundamentally problematic:

1. Events are one of the biggest firehose resources in the system; in a high volume environment (e.g. Online), the controller is continuously consuming and discarding irrelevant events.
2. The apiserver which is providing the events watch to the controller is continuously issuing GETs for the next event resource from etcd to service the watch. The stream of events is essentially endless and ever-growing with cluster capacity.
3. The EventRecorder abstraction doesn't provide a way to assign labels to events to allow the controller to filter events to those it cares about.
4. Even with label filters, the filtering is done in the apiserver and for such a huge key space would probably be very expensive.

I wonder whether events are the appropriate signaling mechanism here. I need to learn more about the overall design. Is there some other stable resource (the namespace itself?) which could be annotated or labelled to drive unidling?

**Comment by ironcladlou** [comment]
The unidler proxy seems to signal the controller by creating an event referencing a Service to be unidled; could the Service itself be annotated, and the entire algo framed around updates to Services rather than Events?

**Comment by deads2k** [comment]
> The unidler proxy seems to signal the controller by creating an event referencing a Service to be unidled; could the Service itself be annotated, and the entire algo framed around updates to Services rather than Events?

@DirectXMan12 This one is for you I think.  Did you avoid it because you were worried that a user would write a bot that just continually applied the annotation and events were out of a user's control?

**Comment by DirectXMan12** [comment]
@deads2k I believe someone tried to throw holy water at me at the though of the proxier user having permission to modify objects.  I'm fine with using that annotation, I think.  I'd put in on the endpoints object, since we already restrict users from editing endpoints, anyway.

**Comment by DirectXMan12** [comment]
I'd have actually preferred not to use events FWIW.

**Comment by sjenning** [comment]
@frobware PTAL
