### ISSUE TITLE
oc rsync should accept pod/<pod-name> as well as <pod-name>

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#15076]
The ``oc rsync`` command accepts a pod name, but in doing that it can only be a pod name and cannot have a ``pod/`` prefix. This means you cannot easily capture output from ``oc get pods -o name ...`` and use it as argument to ``oc rsync`` as it outputs ``pod/`` prefix. This means you have to end up using a ``jsonpath`` or ``custom-columns`` output format and specifically get out the ``metadata.name`` value.

```
POD=`oc get pods -o jsonpath='{.items[*].metadata.name}' --selector app=blog`
```

This is inconvenient.

Other commands such as ``oc rsh`` and ``oc exec`` will accept a value with ``pod/`` prefix even though they can only accept a pod name.

##### Version

oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://localhost:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce

Presuming you have an app deployed with name ``blog``, run:

```
$ oc rsync . `oc get pods --selector app=blog -o name`:/tmp
error: invalid pod name pods/blog-19-l2ldj: a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

in comparison, ``oc rsh`` works:

```
$ oc rsh `oc get pods --selector app=blog -o name`
(app-root)sh-4.2$
```

##### Current Result

Fails as above.

##### Expected Result

Shouldn't complain and allow ``pod/`` prefix. 

##### Additional Information

Note that a review should be done to see if there are any other ``oc`` commands which similar only accept a pod name but currently reject a name with ``pod/`` prefix. These should also be fixed.

**Comment by sparty02** [comment]
I just hit this same thing with oc port-forward.  My workaround was:
```bash
oc get pods -o name | grep connect-db | sed -e 's/^pod\///' | xargs -I % oc port-forward % 5432:5432
```

**Comment by GrahamDumpleton** [comment]
Hmmm, I should have remembered ``oc port-foward`` as also had to use similar workaround there a month or so ago when doing:

* https://learn.openshift.com/introduction/port-forwarding/

**Comment by enj** [comment]
@openshift/cli-review
