### ISSUE TITLE
oc create imagestream does not accept names with multiple slashes

### ISSUE THREAD

**Issue by thomasmckay** [openshift/origin#15086]
docker distribution allows creation of images with multiple slashes in them. openshift should allow same.

For reference: 
https://github.com/docker/distribution/blob/master/docs/spec/api.md#overview
https://github.com/docker/distribution/blob/master/reference/regexp_test.go#L131

```
$ oc create imagestream abc/def
The ImageStream "abc/def" is invalid: metadata.name: Invalid value: "abc/def": may not contain '/'
```

##### Version
[provide output of the `openshift version` or `oc version` command]
```
$ oc version
oc v1.5.0
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.194:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
```
oc create imagestream abc/def
```

##### Current Result
Error

##### Expected Result
Success

**Comment by thomasmckay** [comment]
Found this PR that was closed. Can it be revisited?
https://github.com/openshift/origin/pull/11076

**Comment by pweil-** [comment]
There is a name restriction that will not be lifted so this isn't going to be possible.  Do you have a use case where this scenario is required?  It looked like, based on the discussion, that maybe an import wasn't working correctly.  @mfojtik?

**Comment by mfojtik** [comment]
The imagestream name cannot contain slashes as that will violate the API.

**Comment by pweil-** [comment]
> The imagestream name cannot contain slashes as that will violate the API.

Right.  My question is whether or not there was a case where we couldn't import items that were multi-slashed due to naming the stream after the image?  That may be something we need to address since it's valid in other registries.  The alternative is a pull, retag, push which isn't great.

**Comment by bparees** [comment]
@mfojtik ^^^^

**Comment by bparees** [comment]
@pweil- oc tag lets you specify the IST name independent of the image repository, so i'm closing this as won't/can't fix.
