### ISSUE TITLE
Image signature verification corrupt after removed

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#15081]
When a signature is verified and then removed verification is somehow corrupted and cannot be re-verified with the CLI.

##### Version
```
$ oc version
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. Push and sign an image

        $ sudo GNUPGHOME=/home/aweiteka/.gnupg atomic --debug push \
        --sign-by aweiteka@redhat.com --type atomic --insecure \
        172.30.1.1:5000/prod/rhel-atomic:latest
2. Verify image signature and save

        $ oc adm verify-image-signature \
        sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7 \
        --expected-identity 172.30.1.1:5000/prod/rhel-atomic:latest \
        --public-key /home/aweiteka/.gnupg/aweiteka-redhat.pub --save
        image "sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7" identity is now confirmed (signed by GPG key "0EEB7F8664E11092")
3. Remove verification

        $ oc adm verify-image-signature \
        sha256:73f843089733d841562a8564cab653aa7947626ad6171f1a0a2b51de4f8d4dc7 \
        --public-key /home/aweiteka/.gnupg/aweiteka-redhat.pub --remove-all

##### Current Result

Verification fails after signature has been removed

```
$ oc adm verify-image-signature \
sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7 \
--expected-identity 172.30.1.1:5000/prod/rhel-atomic:latest \
--public-key /home/aweiteka/.gnupg/aweiteka-redhat.pub --save
error: sha256:73f843089733d841562a8564cab653aa7947626ad6171f1a0a2b51de4f8d4dc7 does not have any signature
```

##### Expected Result
Verify cmd output:

    image "sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7" identity is now confirmed (signed by GPG key "0EEB7F8664E11092")

Image describe output:

```
$ oc describe image sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7
Docker Image:		172.30.1.1:5000/prod/rhel-atomic@sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7
Name:			sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7
Created:		40 minutes ago
Annotations:		openshift.io/image.managed=true
Image Size:		30.34 MB (first layer 30.34 MB, last binary layer 1.047 kB)
Image Signatures:
  Name:		sha256:378a287287a7de988af8ec713be4853ff134df443f362025d70de6911eaed0a7@100cc543a4d1226f3775eed1e0d664d1
  Type:		atomic
  Status:		Verified
  Issued By:	0EEB7F8664E11092
  :		Signature is Trusted (verified by user "developer" on 2017-07-05 16:41:59 -0400 EDT)
  :		Signature is ForImage ( on 2017-07-05 16:41:59 -0400 EDT)
```

##### Workaround
Re-push and sign image then verify

##### Additional Information

OUTPUT: https://paste.fedoraproject.org/paste/-7aa7XlfDQfmQmztXRIGiQ

**Comment by mfojtik** [comment]
@aweiteka `--remove-all` will actually nuke the signature off the image... i agree it should just clear the verification status.
