### ISSUE TITLE
Is any way to Openshift respect Docker ENV variables

### ISSUE THREAD

**Issue by judavi** [openshift/origin#15092]
I have been working with Docker Notary to help verify the trust of the images that we use, but now I want to use this feature inside Openshift. In theory, Openshift uses the Docker Client so if you setup the environment variable DOCKER_CONTENT_TRUST=1 it supposes that just use images from trusted sources.
I setup the variable trough /etc/environment or even with export but no luck at all.
Does anyone know if this is possible? Doesn't Openshift respect the custom settings from the Docker Client?
Thanks in advance for the help

**Comment by judavi** [comment]
Any thoughts? @smarterclayton

**Comment by smarterclayton** [comment]
@derekwaynecarr @sjenning

**Comment by sjenning** [comment]
@judavi my understanding is that this env var must be set on the environment in which the docker daemon runs, correct?  If so, you should be able to set an env var in the `docker.service` unit file with `systemctl edit docker.service` and adding `Environment=DOCKER_CONTENT_TRUST=1` before the `ExecStart` line.

**Comment by sjenning** [comment]
@judavi If you `ps -fe | grep docker` and get the PID of the docker daemon, does `DOCKER_CONTENT_TRUST=1` show up in `cat /proc/$PID/environ`?

**Comment by judavi** [comment]
@sjenning  yes
[judavi@sd]$ sudo cat /proc/85903/environ
LANG=en_US.UTF-8PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin NOTIFY_SOCKET=/run/systemd/notify GOTRACEBACK=crash **DOCKER_CONTENT_TRUST=1** OPTIONS= --selinux-enabled --insecure-registry 172.30.0.0/16 DOCKER_CERT_PATH=/etc/docker ADD_REGISTRY=--add-registry registry.access.redhat.com DOCKER_CONTENT_TRUST_SERVER=https://notary-server:4443 DOCKER_STORAGE_OPTIONS=--storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/docker--vg-docker--pool --storage-opt dm.use_deferred_removal=true --storage-opt dm.use_deferred_deletion=true DOCKER_NETWORK_OPTIONS=-b=lbr0 --mtu=1450

**Comment by judavi** [comment]
[judavi@sd]$ oc version
oc v3.3.1.11
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v3.3.1.11
kubernetes v1.3.0+52492b4

**Comment by judavi** [comment]
I have been keep playing with the config file and I notice that other configurations like --signature-verification works but for some reason content-trust doesn't

**Comment by sjenning** [comment]
@ravisantoshgudimetla PTAL

**Comment by ravisantoshgudimetla** [comment]
@judavi Can you elaborate on -

> But doesn't matter where I use setup the variable (and I'm also restarting the services) Openshift is still running new images, so is like Openshift will be skipping or overriding the settings.

Are you seeing some error when pod is creating? If yes, can you share the steps to reproduce it? I have created a signed image and was able to pull it successfully in OpenShift after setting the .DOCKER_CONTENT_TRUST=1

**Comment by judavi** [comment]
@ravisantoshgudimetla there is no error and that's the issue, if you try to run an unsigned image with DOCKER_CONTENT_TRUST=1  Openshift should not create containers with that image... that is the idea of content trust.

**Comment by judavi** [comment]
@ravisantoshgudimetla friendly reminder
