### ISSUE TITLE
Login blocked by getting user:info user:check-access from API

### ISSUE THREAD

**Issue by phru** [openshift/origin#15094]
Hi,

I have downloaded and set up the prometheus example POD. When trying to log in to Prometheus I am facing the following error message:

"message": "scopes [user:info user:check-access] prevent this action; User \"<username>\" cannot get user.openshift.io.users at the cluster scope",

Checking the oadm policy my user is allowed to get <OSC-Host>/apis/*

Please advise what needs to be granted to be able to log in with oAuth.

Thanks in advance.

##### Version
oc v3.5.5.26
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Open Prometheus route endpoint and try to log in

##### Current Result
500 Internal Error

Internal Error

Log: "message": "scopes [user:info user:check-access] prevent this action; User \"<username>\" cannot get user.openshift.io.users at the cluster scope",
##### Expected Result
Successful login to Prometheus 

##### Additional Information

1
--
192.168.111.111 - - [07/Jul/2017:14:25:20 +0000] prometheus.cloudapps.example.com GET - "/oauth/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" 302 359 0.000
  | 2017/07/07 14:25:24 provider.go:526: 403 GET https://os-master.example.com:8443/apis/user.openshift.io/v1/users/~ {
  | "kind": "Status",
  | "apiVersion": "v1",
  | "metadata": {},
  | "status": "Failure",
  | "message": "scopes [user:info user:check-access] prevent this action; User \"<username>\" cannot get user.openshift.io.users at the cluster scope",
  | "reason": "Forbidden",
  | "details": {
  | "name": "~",
  | 192.168.111.111 - - [07/Jul/2017:14:25:24 +0000] prometheus.cloudapps.example.com GET - "/oauth/callback?code=i9NM2MV-fY8_74CMdQAKvW50EpMvxoJs4t8Xrb7Eraw&state=0f563e2450b894cc9c72f8d1e584f5c6%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" 500 330 0.048
  | "group": "user.openshift.io",
  | "kind": "users"
  | },
  | "code": 403
  | }
  | 2017/07/07 14:25:24 oauthproxy.go:551: 192.168.111.111:49660 error redeeming code got 403 {
  | "kind": "Status",
  | "apiVersion": "v1",
  | "metadata": {},
  | "status": "Failure",
  | "message": "scopes [user:info user:check-access] prevent this action; User \"<username>\" cannot get user.openshift.io.users at the cluster scope",
  | "reason": "Forbidden",
  | "details": {
  | "name": "~",
  | "group": "user.openshift.io",
  | "kind": "users"
  | },
  | "code": 403
  | }
  | 2017/07/07 14:25:24 oauthproxy.go:368: ErrorPage 500 Internal Error Internal Error
  | 2017/07/07 14:25:24 oauthproxy.go:626: 192.168.111.111:49660 Cookie "_oauth_proxy" not present
  | 192.168.111.111 - - [07/Jul/2017:14:25:24 +0000] prometheus.cloudapps.example.com GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" 403 2491 0.000
  | 192.168.212.6 - - [07/Jul/2017:14:25:56 +0000] 192.168.212.6:8443 GET localhost:9090 "/metrics" HTTP/1.1 "Prometheus/2.0.0-alpha.3" 200 5160 0.004

**Comment by pweil-** [comment]
can you confirm that you gave the `cluster-reader` role to the service account?  It is in the example template:

```
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: prometheus-cluster-reader
  roleRef:
    name: cluster-reader
  subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: "${NAMESPACE}"
```

**Comment by smarterclayton** [comment]
The prometheus example does not work against 3.5 at the current time.  It's likely you are hitting an issue addressed in 3.6

**Comment by iloayuil** [comment]
@smarterclayton  I got the same error information as above, the version of oc and k8s is ：
$ oc version 
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Is the same problem? @smarterclayton

**Comment by HackToHell** [comment]
Getting the same issue against OCP 1.5.
