### ISSUE TITLE
Re-enable idler

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15101]
https://github.com/openshift/origin/pull/15100 is failing on idler compilation problems.  I made some changes in `separate: DANW: endpointsconfighandler changes` which may or may not have helped, so feel free to revert those.

This is blocking progress on the rebase since we cannot complete a compile and get a master without having this work.

```
# github.com/openshift/origin/pkg/proxy/hybrid
pkg/proxy/hybrid/proxy.go:97: not enough arguments in call to p.unidlingProxy.OnServiceUpdate
	have ([]*"github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/api".Service)
	want (*"github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/api".Service, *"github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/api".Service)
# github.com/openshift/origin/pkg/proxy/unidler
pkg/proxy/unidler/unidlersocket.go:265: svcInfo.ServiceRef undefined (type *userspace.ServiceInfo has no field or method ServiceRef)
pkg/proxy/unidler/unidlersocket.go:345: svcInfo.ServiceRef undefined (type *userspace.ServiceInfo has no field or method ServiceRef)
```

**Comment by danwinship** [comment]
from #15100:

It looks like the upstream types were renamed to EndpointsHandler and ServiceHandler. This is going to need a bunch of work though because the interfaces have grown and HybridProxier needs to implement the new functions.

**Comment by DirectXMan12** [comment]
@deads2k I'll try to get you a PR to fix this as soon as possible (hopefully Monday or Tuesday).  I'm fine with merging the rebase with a disabled unidler, though, if that makes your life easier.

**Comment by deads2k** [comment]
The rebase branch is reviewed and green.  You can build a new pull using it as the base, but I think that pull is done.  See the https://github.com/openshift/origin/pull/15234 for base.
