### ISSUE TITLE
How could I pass command line arguments in openshift

### ISSUE THREAD

**Issue by akd31** [openshift/origin#15110]
I am working on consul. In my local machine I use the command below to create a 3 nodes consul cluster. I want to deploy consul on Openshift container platform. I am using web console and I couldn't find how I could pass the command line arguments like -server -bind=<external ip> -retry-join=<root agent ip> -bootstrap-expect=<number of server agents>. Can you help me ?

$ docker run -d --net=host -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' consul agent -server -bind=<external ip> -retry-join=<root agent ip> -bootstrap-expect=<number of server agents>

**Comment by php-coder** [comment]
> I am using web console and I couldn't find how I could pass the command line arguments

Pod spec has `command` and `args` parameters for that: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/

So it's possible but I can't tell you for sure how to accomplish it with a web console. I suspect that you should try to edit `DeploymentConfig` there.

**Comment by pweil-** [comment]
`command` and `args` are the correct way to pass flags if necessary.  You are able to edit the dc yaml and update the pod spec accordingly
