### ISSUE TITLE
Drop dockerclient in favor of Docker's engine API

### ISSUE THREAD

**Issue by miminar** [openshift/origin#15113]
Kube upstream did this a while ago: https://github.com/kubernetes/kubernetes/pull/23800

Pros:
1. reduce dependencies
2. reduce dependencies
3. reduce dependencies
4. [upstream library](https://github.com/moby/moby/tree/master/client) is preferred over [3rd party library](https://github.com/fsouza/go-dockerclient)

Note that https://github.com/docker/engine-api has been deprecated already.

@mfojtik @dmage @legionus FYI

**Comment by bparees** [comment]
dupe of https://github.com/openshift/origin/issues/12212
