### ISSUE TITLE
PLEASE publish openshift/origin (and other stuf) on "registry.access.redhat.com"

### ISSUE THREAD

**Issue by andrefernandes** [openshift/origin#1512]
Latest docker version available on Satellite (1.4.1) suggests (as per "/etc/sysconfig/docker") that there is a public Red Hat docker registry at "registry.access.redhat.com".

Querying this registry (search REST API) lists a number of rhel official images, but openshift/origin is not one of them.

PLEASE, publish on "registry.access.redhat.com" the same releases from docker hub so that we, unhappy corporate proxied customers, can also pull them from a "whitelistable" source.

(this means not just "openshiuft/origin" images, but also its dependencies)

**Comment by brenton** [comment]
The most official OpenShift v3 images we have right now are under registry.access.redhat.com/openshift3-beta/.  Unfortunately, those won't be useful to you unless you have a beta subscription (there are some required RPM components).  I'll have someone from our customer engagement team follow up with you to see if you want to participate.

Just to be clear, my understanding is that registry.access.redhat.com is for products.  The origin images are part of the upstream project and are based on centos7.

**Comment by brenton** [comment]
I'm closing this for now.  I talked with someone today that said they would reach out to you.  If that doesn't happen don't hesitate to open this back up.

**Comment by andrefernandes** [comment]
Sure. Thanks!

De: Brenton Leanhardt [mailto:notifications@github.com]
Enviada em: terça-feira, 31 de março de 2015 16:48
Para: openshift/origin
Cc: Andre de Oliveira Fernandes
Assunto: Re: [origin] PLEASE publish openshift/origin (and other stuf) on "registry.access.redhat.com" (#1512)


I'm closing this for now. I talked with someone today that said they would reach out to you. If that doesn't happen don't hesitate to open this back up.
