### ISSUE TITLE
Fail to init node on openstack environment: json: cannot unmarshal array into Go value of type string

### ISSUE THREAD

**Issue by woshidagouxiong** [openshift/origin#15131]
When i try to deploy openshift on openstack environment, it fails to init node and output log as below
kubelet_node_status.go:73] Unable to construct v1.Node object for kubelet: failed to get external ID from cloud provider: json: cannot unmarshal array into Go value of type string
the build of openshift origin is openshift-origin-server-v3.6.0-alpha.2-3c221d5-linux-64bit

It works well on openshift 1.4-rc1 + openstack

##### Version
$ oc version
oc v3.6.0-alpha.2+d4f473a-846-dirty
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://10.20.57.199:8443
openshift v3.6.0-alpha.2+d4f473a-846-dirty
kubernetes v1.6.1+5115d708d7

##### Cloud config
[Global]
auth-url = http://10.160.58.30:5000/v2.0
username = admin
password = admin
#domain-id =
tenant-id = f5d103378bc3409fa8af0483fa079410
region = RegionOne

[LoadBalancer]
subnet-id = a7af28d9-0bab-485d-bb09-2cb9aed25610

**Comment by woshidagouxiong** [comment]
##### Version
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7

v3.6.0-alpha.2+d4f473a-846-dirty is my build from source

**Comment by sdodson** [comment]
How are you starting it? Can you add --loglevel=6 and see if there's useful debugging info there?
