### ISSUE TITLE
Atomic Registry Quickstart Installation broken on CentOS7

### ISSUE THREAD

**Issue by severinraez** [openshift/origin#15137]
Seems as if the latest docker images from _openshift/origin-docker-registry_ and _openshift/origin_ don't play nice with the installer.

##### Version

Follow http://docs.projectatomic.io/registry/latest/registry_quickstart/administrators/index.html#registry-quickstart-administrators-index on a fresh centos7 install.

##### Steps To Reproduce
1. `vagrant up centos/7` (give your box a static ip and use e.g. _192.168.33.10.xip.io_ as the hostname for the atomic registry setup)
2. `yum install docker atomic`
3. `systemctl start docker; systemctl enable docker`
4. Follow the instructions in the tutorial, up to and including `systemctl enable --now atomic-registry-master.service`
5. Wait for the docker containers to come up

##### Current Result

* Registry container is constantly crashing, complaining because the config file _/etc/atomic-registry/registry/config.yml_ (this is the path on the host) that's mapped into the container is empty.
* Master containers' stdout/stderr is full of complaints about the user _system:admin_ not being authorized to query resources.

##### Expected Result

Everything works

##### Fix

Pin the images to v1.5.1 
Do

```
export REGISTRYTAG=v1.5.1
export MASTERTAG=v1.5.1
export CONSOLETAG=latest
atomic install projectatomic/atomic-registry-install $host 
```

instead of just 

    atomic install projectatomic/atomic-registry-install $host 

What's still a little troubling is that there are no tags on dockerhub to pin the console image, _cockpit/kubernetes_, to.

**Comment by pweil-** [comment]
@severinraez what issues are you seeing when using the latest images?  That may help folks diagnose the issue.  Thanks

**Comment by severinraez** [comment]
I edited my comment to closer describe what happened. Sadly I didn't have the presence of mind to keep the exact error messages. Hope that helps.

**Comment by aweiteka** [comment]
Atomic registry deployment is being deprecated in favor of better tested and maintained installation methods.

- [oc cluster up](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md) for non-production "try it out" or test deployments
- [openshift-ansible](http://www.projectatomic.io/blog/2017/05/oo-standalone-registry/) for more production use cases.

This reported issue will not be addressed.
