### ISSUE TITLE
FAILURE: INSTALL ANSIBLE ATOMIC-OPENSHIFT-UTILS

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15144]
On the release-1.5 branch

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/2268/consoleFull#69811047958b6e51eb7608a5981914356

@jhadvig @stevekuznetsov @sdodson

**Comment by stevekuznetsov** [comment]
@jhadvig looks like the script failed:

```
+ sudo python sjb/hack/determine_install_upgrade_version.py atomic-openshift-utils-3.6.142-1.git.0.b284f55.el7.noarch --dependency_branch release-1.5
++ export status=FAILURE
```

Did we add those logging steps for the script?

**Comment by kargakis** [comment]
Yeah, this one is broken:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/2272/console

Raising priority since this now blocks merges on release-1.5.

**Comment by kargakis** [comment]
Fixed by https://github.com/openshift/aos-cd-jobs/pull/420. I can verify this is not a problem anymore.
