### ISSUE TITLE
The Build Status is not updating properly

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#1514]
I saw this bug yesterday and I can see some of these today. The problem is that I can see my 'build' finished (by looking at `docker ps -a`):

```
a4ff5cb12c1f        openshift/origin-docker-builder:latest  
"/usr/bin/openshift-   3 minutes ago       Exited (0) 2 minutes ago
k8s_docker-build.68d01dc8_testsecretbuilder_secret780444235_5a39c705-d7a0-11e4-8ad5-525400885eaf_b89d23d3     
```

However, the `osc get builds` command display the Status as 'Running' for another ~60-100 seconds. Since I'm using Watch(), this is causing that the test i'm writing is taking unnecessary long time.

**Comment by bparees** [comment]
@mfojtik what's the pod state at the time?

**Comment by soltysh** [comment]
+1 on that, I've observed that happening just recently

**Comment by bparees** [comment]
closing as i think this is better now that we cleaned up some logic here.  @mfojtik or @soltysh please reopen if you think it's still an issue.
