### ISSUE TITLE
envFrom in buildConfig

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#15159]
1.6 added the envFrom support so we can load configmaps and secrets straight into environment variables. eg.

```
          envFrom:
            - configMapRef:
                name: test
```

Can this support be included in buildConfigs?

**Comment by bparees** [comment]
for now we did just add valueFrom support for buildconfig env vars, perhaps you can use that?  (it is part of the pending 3.6 release)

https://docs.openshift.org/latest/dev_guide/builds/build_environment.html

(I realize it means having to explicitly identify each key in the configmap/secret that you want to consume)

**Comment by bparees** [comment]
converted to our trello backlog here: https://trello.com/c/kemg2ILC

**Comment by andrewklau** [comment]
EnvFrom would just help with being able to keep things consistent with the
deployment environment. When there's over 30+ env variables it's not fun.

**Comment by bparees** [comment]
thanks, closing the issue, we'll continue to track the RFE in trello.

**Comment by sapkra** [comment]
The trello board says that the feature was migrated but I couldn't find any documentation about it.
Does anyone has some information about it?

**Comment by bparees** [comment]
@sapkra it was migrated to our jira board here: 
https://jira.coreos.com/browse/DEVEXP-57

unfortunately the board is not currently public (we're working on making it public).

However it is not currently a high priority item in our backlog.

**Comment by sapkra** [comment]
Ahh ok now I understand: not the feature was migrated...the ticket was just migrated to JIRA.
And yeah it would be great to have more transparency in issues etc.

**Comment by adambkaplan** [comment]
@sapkra there is a project under way to make our JIRA issues/stories public. I want to say the goal is to complete this by the end of 2019/early 2020.
