### ISSUE TITLE
Ability to clone a persistent volume

### ISSUE THREAD

**Issue by fctucker** [openshift/origin#15153]
I have a volume as part of my deployment.  I want to take that volume and clone it (copy its contents) into a new volume and mount that into another deployment. 

The idea is that the original deployment modified the contents of a volume, and i want to have another deployment use that volume's contents without actually affecting the 1st deployment.

is this ... possible?  ... a bad idea?  ... Documented somewhere?

Thanks

**Comment by jsafrane** [comment]
Volume cloning is not implemented in OpenShift. We're working on volume snapshots upstream, so you could take a snapshot of your volume and restore it into another volume(s), but that's in early development right now. Please follow https://github.com/kubernetes-incubator/external-storage/pull/197
