### ISSUE TITLE
oc status / oc describe dc / oc describe rc doesn't communicate time ranges well

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15175]
Deployments and pod creations take a certain amount of time.  I was looking to see whether a new deployment overlapped with a failure (registry was being redeployed, builds failed to push).  But the CLI didn't help me find out how long the deployment took.  I had to drill into pods.

Some things that could help:

1. oc status could tell me how long the last successful deployment took
2. oc describe dc could give me info about both start and completion time, as well as potentially info on the pods themselves (newest pod went ready X minutes ago)
3. oc get pods could potentially show ready time (creation time is not as useful)

Needs some design thought

**Comment by DanyC97** [comment]
great idea @smarterclayton , any idea if the proposal was made to K8 upstream too ? 
This sort of info will be v much appreciated for ops (and not only) guys

**Comment by smarterclayton** [comment]
Not yet but @tnozicka is this something you can run down?

**Comment by tnozicka** [comment]
converted to trello card: https://trello.com/c/4VoWUODN
