### ISSUE TITLE
Registry appears to be network bound when many pushes are in progress

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15177]
Network IO peaks at 80mb/s on m4.4xlarge infra nodes during large scale push event.

![network](https://www.dropbox.com/s/oh2rj1gy98pr8ch/Screenshot%202017-07-12%2018.36.50.png?raw=1)

We don't appear to be CPU bound:

![cpu](https://www.dropbox.com/s/7yvs31baycieoja/Screenshot%202017-07-12%2018.29.34.png?raw=1)

Are we hitting an artificial limit in the kernel / etc that prevents this from succeeding?

@jeremyeder

**Comment by smarterclayton** [comment]
Same curve for network outbound (above was inbound):

![transmit](https://www.dropbox.com/s/1gzqpuc9ggd39bh/Screenshot%202017-07-12%2018.39.16.png?dl=0)

**Comment by jeremyeder** [comment]
I show the same.

![image](https://user-images.githubusercontent.com/1919640/28144816-d1ba50b0-673b-11e7-8cfd-01a1f91a99b5.png)

But those instance types should be capable of 2Gbps.  Can you post the output of
```
ethtool -i eth0
```
If it is ```ixgbevf``` then we are already setup for EC2 Enhanced Networking.
If if is ```vif``` then we are not, and we need to fix that.

Tunings should be fine as long as ```tuned``` is running and you have the ```atomic-openshift-node-guest``` profile.  Run this:

```
tuned-adm active
```

Here is test network test data from m4.4xlarge, I just ran this tonight:

![image](https://user-images.githubusercontent.com/1919640/28146088-3442a1ca-6745-11e7-86ef-a077c4a35a00.png)

So my answer (absent any other information) is that you're not facing a network bottleneck, at least on eth0.  We have to continue looking.

I note that according to this page: http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html we might want to check with AWS support to see if we're being rate limited by S3.

Also note that when we scaled down the infra nodes from m4.10xlarge to m4.4xlarge, we went from 10Gbit down to 2Gbit network performance limits.

**Comment by smarterclayton** [comment]
@eparis can you help close the loop here with Jeremy?

On Jul 12, 2017, at 9:18 PM, Jeremy Eder <notifications@github.com> wrote:

I show the same.

[image: image]
<https://user-images.githubusercontent.com/1919640/28144816-d1ba50b0-673b-11e7-8cfd-01a1f91a99b5.png>

But those instance types should be capable of 2Gbps. Can you post the
output of

ethtool -i eth0

If it is ixgbevf then we are already setup for EC2 Enhanced Networking.
If if is vif then we are not, and we need to fix that.

Tunings should be fine as long as tuned is running and you have the
atomic-openshift-node-guest profile. Run this:

tuned-adm active

Here is test network test data from m4.4xlarge, I just ran this tonight:

[image: image]
<https://user-images.githubusercontent.com/1919640/28146088-3442a1ca-6745-11e7-86ef-a077c4a35a00.png>

So my answer (absent any other information) is that you're not facing a
network bottleneck, at least on eth0. We have to continue looking.

I note that according to this page:
http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html
we might want to check with AWS support to see if we're being rate limited
by S3.

Also note that when we scaled down the infra nodes from m4.10xlarge to
m4.4xlarge, we went from 10Gbit down to 2Gbit network performance limits.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15177#issuecomment-314941998>,
or mute the thread

**Comment by legionus** [comment]
Now we have a request limits.

https://docs.openshift.org/latest/install_config/registry/extended_registry_configuration.html#docker-registry-configuration-reference-openshift

@smarterclayton @bparees Does this solve the problem?

**Comment by bparees** [comment]
> @smarterclayton @bparees Does this solve the problem?

I wouldn't think so.  My interpretation of this issue is that the concern is scaling up to handle more pushes (either by fixing the bottleneck if it's something we can control, or scaling horizontally to give us more bandwidth)
