### ISSUE TITLE
No such container when fetching build logs

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15171]
Seeing some instances of:
`no such container: "cc3cbb214251252acd0e40e35ccf8f625c644a36957378763451e7bc57bb3e73"`

when retrieving build logs.

Builds themselves will always have some boiler plate logs (assuming the pod container ever started), e.g.:

```
$ oc logs build/ruby-sample-build-1
Cloning "https://github.com/openshift/ruby-hello-world.git" ...
	Commit:	022d87e4160c00274b63cdad7c238b5c6a299265 (Merge pull request #58 from junaruga/feature/fix-for-ruby24)
	Author:	Ben Parees <bparees@users.noreply.github.com>
	Date:	Fri Mar 3 15:29:12 2017 -0500
```

so this looks to me like the build pod container was removed (or couldn't be accessed/found), rather than an issue w/ the build itself having failed during some container operation.

It would also be nice if the oc logs output made it clearer when it has "failed to retrieve logs" vs making it look like the error message *is* the content of the logs you requested.

**Comment by smarterclayton** [comment]
@derekwaynecarr could be a race condition in kubelet logging - haven't had
time to look at it (we check the container, then call logs, but if the
container exits in between)

**Comment by derekwaynecarr** [comment]
@bparees -- was the container garbage collected?

**Comment by bparees** [comment]
@derekwaynecarr unknown.  thought the container shouldn't be GCed as long as the pod exists, though?  Or is that just a prioritization?

**Comment by bparees** [comment]
@sjenning I think you might have worked this elsewhere?  (or be working it elsewhere?)
