### ISSUE TITLE
error: update acceptor rejected

### ISSUE THREAD

**Issue by ghost** [openshift/origin#15176]
I am using tomcat 8 S2I catalog to deploy helloworld java app ( war file ) from  our internal GIT . it is able to create a  container and  push it to  registry and deployment fails   with  the below error. 

This is a  simple hello world app  , works when  i  deploy manually , but i when i  use catalog  deployment fails . 

Also  , no information  found in events

Any advise  or help is appreciated.

-> Scaling javahello-1 to 1
--
  | --> Waiting up to 10m0s for pods in deployment javahello-1 to become ready
  | error: update acceptor rejected javahello-1: pods for deployment "javahello-1" took longer than 600 seconds to become ready

openshift v3.4.1.7
kubernetes v1.4.0+776c994

# oc get events
No resources found.

**Comment by naveen408** [comment]
i just  re-deployment to capture  events  info  -   Attached  Logs and events 

[oclogs.txt](https://github.com/openshift/origin/files/1143252/oclogs.txt)
 

[Oc-eventsinformation.txt](https://github.com/openshift/origin/files/1143241/Oc-eventsinformation.txt)

**Comment by mfojtik** [comment]
It says the readiness probe failed, can you share the DC yaml or check if the readiness probe actually can succeed?

**Comment by naveen408** [comment]
i am  still struggling to find information  why it is failing  at readiness..

Here is the   DC  config  information ..  

apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2017-07-12T15:57:04Z
  generation: 3
  labels:
    app: jws30-tomcat8-basic-s2i
    application: javahello
    template: jws30-tomcat8-basic-s2i
    xpaas: 1.2.0
  name: javahello
  namespace: javahello
  resourceVersion: "10277725"
  selfLink: /oapi/v1/namespaces/javahello/deploymentconfigs/javahello
  uid: bfb45e88-671a-11e7-9717-005056953170
spec:
  replicas: 1
  selector:
    deploymentConfig: javahello
  strategy:
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: javahello
        deploymentConfig: javahello
      name: javahello
    spec:
      containers:
      - env:
        - name: JWS_ADMIN_USERNAME
          value: "768234"
        - name: JWS_ADMIN_PASSWORD
          value: welcome1
        image: 172.30.155.146:5000/javahello/javahello@sha256:94a3d291f753d8a4d4b182880ba8fa0f88aa01387810347f418e0b8ecf27014e
        imagePullPolicy: Always
        name: javahello
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -s -u 7xxxxx:welcme1 'http://localhost:8080/manager/jmxproxy/?get=Catalina%3Atype%3DServer&att=stateName'
|grep -iq 'stateName *= *STARTED'
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 60
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - javahello
      from:
        kind: ImageStreamTag
        name: javahello:latest
        namespace: javahello
      lastTriggeredImage: 172.30.155.146:5000/javahello/javahello@sha256:94a3d291f753d8a4d4b182880ba8fa0f88aa01387810347f418e0b8ecf27014e
    type: ImageChange
  - type: ConfigChange
status:
  conditions:
  - lastTransitionTime: 2017-07-12T15:57:04Z
    message: Deployment config does not have minimum availability.
    status: "False"
    type: Available
  - lastTransitionTime: 2017-07-12T20:34:42Z
    message: Replication controller "javahello-2" has failed progressing
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  details:
    causes:
    - imageTrigger:
        from:
          kind: ImageStreamTag
          name: javahello:latest
          namespace: javahello
      type: ImageChange
    message: image change
  latestVersion: 2
  observedGeneration: 3

**Comment by fishbb** [comment]
Hi I am running into the same issue. 

`
--> Scaling django-2 to 1
--
  | --> Waiting up to 10m0s for pods in rc django-2 to become ready
  | W1021 22:52:42.975801       1 reflector.go:323] github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:509: watch of *api.Pod ended with: too old resource version: 1555123963 (1555128189)
  | error: update acceptor rejected django-2: pods for rc "django-2" took longer than 600 seconds to become ready
`

**Comment by kargakis** [comment]
@ghost make sure the readiness probe is valid and maybe tweak `failureThreshold` to a higher value?
