### ISSUE TITLE
builds should retry push under more conditions

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15178]
we should be more aggressive in retrying failed pushes since the cost of doing so is low and the cost of not doing so (forcing a user to rebuild) is high.

here are some of the errors we've seen that should be considered for retry:

```
  2 error: build error: Failed to push image: Put https://172.30.208.107:5000/v2/XX/XX/manifests/latest: EOF
   7 error: build error: Failed to push image: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
   9 error: build error: Failed to push image: dial tcp 172.30.208.107:5000: getsockopt: no route to host
  13 error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: i/o timeout
  18 error: build error: Failed to push image: error parsing HTTP 400 response body: unexpected end of JSON input: ""
  23 error: build error: Failed to push image: Get https://172.30.208.107:5000/v1/_ping: dial tcp 172.30.208.107:5000: getsockopt: no route to host
```

/cc @smarterclayton

**Comment by bparees** [comment]
now you can have this one too :)

**Comment by smarterclayton** [comment]
The last four are probably reasonable, the first two let's hold off on (not enough data)

**Comment by bparees** [comment]
@coreydaley, @smarterclayton has expressed a desire to get this in 3.6.0 (meaning it will need to be fixed quickly and backported into the release-3.6 stream).  the PR should be pretty simple, can you jump on it?

Thanks

**Comment by coreydaley** [comment]
@bparees ok, I'll work on it now

**Comment by bparees** [comment]
thanks @coreydaley

**Comment by coreydaley** [comment]
@bparees pr here: https://github.com/openshift/origin/pull/15380
