### ISSUE TITLE
wrong metricsPublicURL in master-config.yaml (minishift)

### ISSUE THREAD

**Issue by ArminMW** [openshift/origin#15182]
wrong metricsPublicURL in master-config.yaml (minishift)

##### Version

minishift v1.2.0
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
etcd 3.2.0-rc.1

##### Steps To Reproduce

1. using Minishift v1.2.0 deploy Origin v3.6.0-alpha.2 with Metrics, e.g.:
  minishift start --openshift-version=v3.6.0-alpha.2 --memory=8000 --metrics --logging
2. wait until deployments of pods finalize: hawcular-cassandra, hawkular-metrics, heapster
3. log into OpenShift Web Console as admin
4. open the metrics URL from the OpenShift Web Console: 
  Hawkular status page shows ("Metrics Service :STARTED")
5. reload the OpenShift Web Console
6. now the pod metrics should be displayed, but they are not, due to the wrong metricsPublicURL in master-config.yaml
7. correct metricsPublicURL in master-config.yaml
8. restart openshift
9. reload the OpenShift Web Console
10. now the pod metrics are displayed

##### Current Result

The metricsPublicURL is missing the "hawkular-" prefix:

minishift ssh
grep /mnt/sda1/var/lib/minishift/openshift.local.config/master/master-config.yaml
  metricsPublicURL: https:**//metrics**-openshift-infra.192.168.42.152.nip.io/hawkular/metrics

Thus the Origin OpenShift Web Console does not pod show metrics.

##### Expected Result

minishift ssh
grep /mnt/sda1/var/lib/minishift/openshift.local.config/master/master-config.yaml
  metricsPublicURL: https:**//hawkular-metrics**-openshift-infra.192.168.42.152.nip.io/hawkular/metrics

##### Additional Information

After manual correction of the metricsPublicURL in the master-config.yaml and restart of openshift everything works as expected: the pod metrics are shown in the OpenShift Web Console.

I am not sure if this issue is in Origin or in Minishift. Please excuse me if this is the wrong place to report a minishift related  issue.

**Comment by php-coder** [comment]
The same issue in Minishift repo: https://github.com/minishift/minishift/issues/1125

**Comment by mfojtik** [comment]
@ArminMW mind closing this in favor of the minishift issue @php-coder pointed out?

**Comment by ArminMW** [comment]
Close this because follow-up in https://github.com/minishift/minishift/issues/1125

**Comment by praveenkumar** [comment]
@ArminMW This is not something we change as part of minishift. I think this issue we need to file against `oc cluster up` and involve @csrwng . Below provision part of `oc cluster up`

```
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.161:8443

The metrics service is available at:
    https://metrics-openshift-infra.192.168.42.161.nip.io

The kibana logging UI is available at:
    https://kibana-logging.192.168.42.161.nip.io

You are logged in as:
    User:     developer

To login as administrator:
    oc login -u system:admin
````

**Comment by csrwng** [comment]
Created an issue on the origin side https://github.com/openshift/origin/issues/15205
