### ISSUE TITLE
Enabling certain admission controllers that mutate pods on updates can block other updates

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15188]
Much of the pod is immutable on update after it has been scheduled to a node, but some of the admission controllers we have will mutate a pod on update after scheduling and thus prevent *any* updates to the pod unless mutation is removed.

In place updates to pods must succeed unless there is a very good reason.  This blocked deleting a pod that had a dangling finalizer - we were unable to delete the pod because of the finalizer, but unable to update the finalizer because of this bug, which led to us having to delete it with etcd.

Reviewed all admission controllers which mutate pods AND mutate fields other than the known safe ones (image policy and image policy web hook are safe because they only mutate image references on pods).

Affected:

* k8s.io/kubernetes/plugin/pkg/admission/alwayspullimages/admission.go
* k8s.io/kubernetes/plugin/pkg/admission/defaulttolerationseconds/admission.go

In this case, it was always pull images.

PodSecurityPolicy may be affected, but will file a separate issue upstream TODO

**Comment by enj** [comment]
@openshift/security @jupierce

**Comment by smarterclayton** [comment]
Not all are closed, more complex

**Comment by smarterclayton** [comment]
fixed the important bits for 3.6
