### ISSUE TITLE
BuildConfig rollbacks

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15204]
We have all the info in place: BC, old builds. It should be fairly easy to provide a command that rollbacks a BC to a previous spec.

@bparees

**Comment by bparees** [comment]
We already let you rerun an older builds.  If you want to revert to a previous buildconfig spec itself, you should be keeping the buildconfig definition in source control.  Not sure why we'd re-implement that capability?

**Comment by kargakis** [comment]
The one doesn't exclude the other. In source control you may need to revert more than one commit and sometimes it will not be a clean revert, whereas `oc rollback bc/deck --dry-run -o yaml [--to-revision=N] > deck.yaml` is still a declarative workflow.

**Comment by bparees** [comment]
if you created the BC from source control, why would you ever not be able to revert to that level in your source control?  Even if other changes were made at that level, you can check out the old deck.yaml from the level you care about.

**Comment by bparees** [comment]
Turning our resource api into a revision control system seems like a mistake.

**Comment by mfojtik** [comment]
agree with @bparees you should already have previous image avaiable so rolling back a build config produces nothing just the same image you already built before (which I think is bad process, because that rollback build is not guaranteed to succeed (external deps might change, etc.). So instead of rolling back build I would rather roll back the previous image, which we already support in DC ;-)

**Comment by kargakis** [comment]
DC rollback is fairly simple, there is no "revision controling" happening in the API, oc PUTs the manifest it gets back from the endpoint. I wanted to use rollback for builds when I was prototyping - so no use of a declarative workflow, while it's still possible to have it. 

> agree with @bparees you should already have previous image available so rolling back a build config produces nothing just the same image you already built before (which I think is bad process, because that rollback build is not guaranteed to succeed (external deps might change, etc.). So instead of rolling back build I would rather roll back the previous image, which we already support in DC ;-)

This is not about the previous image, I wanted to use previous spec options. DC rollbacks update not just your image but all of your DC spec and that's what we support.

**Comment by bparees** [comment]
> This is not about the previous image, I wanted to use previous spec options.

then rerun the old build.

**Comment by bparees** [comment]
closing as won't fix for the reasons in my earlier comments.
