### ISSUE TITLE
Pod service DNS resolution problem after installation in Azure Cloud VMs

### ISSUE THREAD

**Issue by bzon** [openshift/origin#15207]
**Version**:Openshift Origin v1.5
**Cloud Provider**: Azure
**VM image**: Centos 7.3 by OpenLogic

**Problem:**  

When inside a pod and I run `curl https://kubernetes.default.svc:443`, I can't resolve it properly. 

I never had this issue when using the playbook in AWS Centos VMs.  

**Installation inventory file:**

```
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=john
deployment_type=origin

osm_use_cockpit=true
osm_cockpit_plugins=['cockpit-kubernetes']

# Master node time sync
openshift_clock_enabled=true

# If ansible_ssh_user is not root, ansible_sudo must be set to true
ansible_become=true

# enable htpasswd authentication
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/openshift-passwd'}]

openshift_master_default_subdomain=origin.104.41.148.233.xip.io

# default project node selector
osm_default_node_selector='region=apps'

# default selectors for router and registry services
openshift_router_selector='region=infra'
openshift_registry_selector='region=infra'

# disable strict production setup check
openshift_disable_check=docker_storage,memory_availability,disk_availability

# so builds can push successfully to the insecure registry using its default cidr block
openshift_docker_insecure_registries=172.30.0.0/16

# host group for masters
#openshift_hostname=openshift-master.quz5xqnm1qveha3q0nhditkpae.bx.internal.cloudapp.net
#openshift_hostname=openshift-worker.quz5xqnm1qveha3q0nhditkpae.bx.internal.cloudapp.net

[masters]
104.41.148.233 openshift_schedulable=true openshift_public_hostname=ose-master01.eastus.cloudapp.azure.com openshift_hostname=openshift-master01

[etcd]
104.41.148.233

# host group for nodes, includes region info
[nodes]
104.41.148.233 openshift_node_labels="{'region': 'infra'}" openshift_hostname=openshift-master01
40.114.47.192 openshift_node_labels="{'region': 'apps', 'zone': 'default'}" openshift_hostname=openshift-worker01
```

**Error from diagnostics:**  
```
[root@openshift-master01 master]# oadm diagnostics DiagnosticPod
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/root/.kube/config'

[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint

ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:155]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected

       WARN:  [DP1005 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:85]
              A request to the master timed out.
              This could be temporary but could also indicate network or DNS problems.

       ERROR: [DP1006 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:110]
              DNS resolution for registry address docker-registry.default.svc.cluster.local timed out; this could indicate problems with DNS resolution or networking

       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected

       WARN:  [DP2009 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:64]
              A request to the master (SkyDNS) nameserver 10.0.0.7 timed out.
              This could be temporary but could also indicate network or DNS problems.
              This nameserver is critical for resolving cluster DNS names.

       WARN:  [DP2014 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:119]
              A request to the nameserver 10.0.0.7 timed out.
              This could be temporary but could also indicate network or DNS problems.

       [Note] Summary of diagnostics execution (version v1.5.1+7b451fc):
       [Note] Warnings seen: 3
       [Note] Errors seen: 1
```

**Master /etc/resolv.conf**
```
; generated by /usr/sbin/dhclient-script
search quz5xqnm1qveha3q0nhditkpae.bx.internal.cloudapp.net
nameserver 168.63.129.16
```

**Node /etc/resolv.conf**
```
; generated by /usr/sbin/dhclient-script
search quz5xqnm1qveha3q0nhditkpae.bx.internal.cloudapp.net
nameserver 168.63.129.16
```

**Comment by bzon** [comment]
I think I may have solved the issue by adding this `openshift_override_hostname_check=true`. 

Based from: https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example
```
# openshift-ansible will wait indefinitely for your input when it detects that the
# value of openshift_hostname resolves to an IP address not bound to any local
# interfaces. This mis-configuration is problematic for any pod leveraging host
# networking and liveness or readiness probes.
# Setting this variable to true will override that check.
#openshift_override_hostname_check=true
```

**Comment by aaryabhatt** [comment]
Hi, I tried to reinstall origin with this parameter in centos, but still facing the same issue.  
`ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:155]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected
              
       WARN:  [DP1005 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:85]
              A request to the master timed out.
              This could be temporary but could also indicate network or DNS problems.
              
       ERROR: [DP1006 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:110]
              DNS resolution for registry address docker-registry.default.svc.cluster.local timed out; this could indicate problems with DNS resolution or networking
              
       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected
              
       WARN:  [DP2009 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:64]
              A request to the master (SkyDNS) nameserver 136.243.59.150 timed out.
              This could be temporary but could also indicate network or DNS problems.
              This nameserver is critical for resolving cluster DNS names.
              
       WARN:  [DP2010 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:66]
              A request to the nameserver 136.243.59.150 timed out.
              This could be temporary but could also indicate network or DNS problems.
              
       WARN:  [DP2014 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:119]
              A request to the nameserver 136.243.59.150 timed out.
              This could be temporary but could also indicate network or DNS problems.
              
       [Note] Summary of diagnostics execution (version v1.5.1+7b451fc):
       [Note] Warnings seen: 4
       [Note] Errors seen: 1
`

**Comment by bzon** [comment]
@aaryabhatt Are you also running it in Azure? 

You may also want to add these:  
```
openshift_dns_ip=172.30.0.1
```

Try looking at my inventory file at my personal guide gist..
https://gist.github.com/bzon/b3201d54c5b7b70fe7e117c28a0c18bc#for-azure-vm

**Comment by aaryabhatt** [comment]
It's not on azure. It's bare metal server on public network, and all node server are bare metal and  on public network too. I have configured dns subdomains for nodes on godaddy, do I still need this?

**Comment by bzon** [comment]
@aaryabhatt have you met the pre-requisite in the pre installation guide of Openshift Origins?

**Comment by aaryabhatt** [comment]
Yes, installation goes smoothly without any issue. Issue is that any DNS service are not running in any pod. I can't nslookup google.com from any pod terminal, I can't call any services name using curl or telnet while IP address of services is working. Even it is blocking the apt-get update in pod terminal, while ping 8.8.8.8 works fine. DNSMASQ is running.

**Comment by bzon** [comment]
@aaryabhatt sorry I can't help you. I will now close this issue since this topic is just about and issue when installing in Azure CentOS VMs.

**Comment by aaryabhatt** [comment]
ok, @bzon, just quick question,  I found out due to multiple repetitive un-installation and installation, I found out that --insecure-registry 172.30.0.0/16 was missing from /etc/sysconfig/docker file, than I add it to this and restart the docker, do I reinstall it again

**Comment by bzon** [comment]
@aaryabhatt That the docker settings should not be a problem and has no relation with your DNS problem. Docker settings in /etc/sysconfig/dockerfile can be modified anytime after installation.

**Comment by aaryabhatt** [comment]
@bzon  openshift_dns_ip=172.30.0.1, did the magic. Thanks
