### ISSUE TITLE
Wrong metrics URL configured for `cluster up`

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#15205]
Issue from:
https://github.com/openshift/origin/issues/15182

cluster up is generating a URL like: `https://metrics-openshift-infra.[blah]` whereas the deployer is now using `https://hawkular-metrics-openshift-infra.[blah]`

**Comment by csrwng** [comment]
@jcantrill - this used to work before but for some reason it seems that the latest deployer has changed the format of the hostname.

**Comment by jcantrill** [comment]
Trying with:

origin commit:  05b9ea884e842546bde220700684388a27beb7bc
openshift-ansible commit: da7551b82fc37a77181a8c9aa9b82060b7101c5f

The job produced the following route:

```
# oc get routes
NAME               HOST/PORT                                           PATH      SERVICES           PORT      TERMINATION   WILDCARD
hawkular-metrics   hawkular-metrics-openshift-infra.127.0.0.1.nip.io             hawkular-metrics   <all>     reencrypt     None
```
Is it still an issue?

**Comment by csrwng** [comment]
@jcantrill an image with openshift-ansible master resolves this for me as well.

**Comment by jcantrill** [comment]
@csrwng Can we close this issue as resolved?

**Comment by csrwng** [comment]
Yes
