### ISSUE TITLE
Why are both admission plugins OriginPodNodeEnvironment and PodNodeSelector enabled by default?

### ISSUE THREAD

**Issue by aveshagarwal** [openshift/origin#15222]
Shouldn't PodNodeSelector deprecate OriginPodNodeEnvironment, as PodNodeSelector also provides support for per namspace whitelist on top of what everything is done by OriginPodNodeEnvironment?

The another difference is that PodNodeSelector looks for annotation `scheduler.alpha.kubernetes.io/node-selector` whereas OriginPodNodeEnvironment looks for `openshift.io/node-selector` on a namespace.

I did some testing and I did not notice any issue from functionality point of view even when both are being used though, so does not seem any concern with both enabled simultaneously. 
 
@derekwaynecarr

**Comment by liggitt** [comment]
we have to continue supporting the existing annotations

**Comment by aveshagarwal** [comment]
PodNodeSelector could also have a configurable variable with default to scheduler.alpha.kubernetes.io/node-selector.
