### ISSUE TITLE
Additional roles missing system-only annotation

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#15241]
RE: [web console issue 1858](https://github.com/openshift/origin-web-console/issues/1858)
Original issue #14411, PR #14510 

![screen shot 2017-07-17 at 2 16 43 pm](https://user-images.githubusercontent.com/280512/28284761-2599980e-6b00-11e7-969b-0ed82092f855.png)

Per @enj fix should be done in `GetDeadClusterRoles`.

**Comment by benjaminapetersen** [comment]
fyi @jwforres migrated it here, still as p3.

**Comment by jwforres** [comment]
I would consider this worse than a p3, its a pretty bad experience OOTB and is a regression

**Comment by jwforres** [comment]
@enj who should this be assigned to?

**Comment by enj** [comment]
@benjaminapetersen has totally got this 😄
