### ISSUE TITLE
fix e2e tests: SchedulerPriorities

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15254]
Specifically:

```
Extended.[k8s.io] SchedulerPriorities [Serial] Pod should be schedule to node that don't match the PodAntiAffinity terms
Extended.[k8s.io] SchedulerPriorities [Serial] Pod should perfer to scheduled to nodes pod can tolerate
```

Disabled in `disable a few failing e2e tests` from https://github.com/openshift/origin/pull/15234.  It is green and reviewed, so it's a good base to start from.

**Comment by wanghaoran1988** [comment]
Unfortunately, I wrote the scheduler priorities e2e tests, but the sig scheduler team are not decide write some more integration testing replace the e2e tests. tracked issues here:https://github.com/kubernetes/kubernetes/issues/48176

**Comment by deads2k** [comment]
@aveshagarwal Be sure to revert https://github.com/openshift/origin/pull/15707/commits/e060970c189723c830ea3a2b785d87328b2ae22b on your way through.

**Comment by aveshagarwal** [comment]
@deads2k sure.
