### ISSUE TITLE
Re-enable stateful set tests

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15252]
Specifically:
```
Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should matching orphans and release non-matching pods
Extended.[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should not deadlock when a pod's predecessor fails
```

The problem was with PVs, not getting removed.  It sounds similar to this: https://github.com/kubernetes/kubernetes/issues/48716

It is disabled in `disable a few failing e2e tests` in the rebase pull: https://github.com/openshift/origin/pull/15234 .  The rebase pull is reviewed and green, so it's a good base to start testing on.

**Comment by kargakis** [comment]
Hm, they seem enabled and flakying in the queue?

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1334/

**Comment by bparees** [comment]
+1 @kargakis 

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3400

**Comment by soltysh** [comment]
This is not relevant any more.
/close
