### ISSUE TITLE
Bash/Zsh completion should be documented

### ISSUE THREAD

**Issue by hadess** [openshift/origin#15251]
Probably as part of the installation process. It's super useful to avoid typos.

**Comment by stevekuznetsov** [comment]
Which set of documents on installation were you looking at, where you think it should be added?

**Comment by hadess** [comment]
I'd expect it at the same location as the link to the binaries for the client at:
https://github.com/openshift/origin#installation

**Comment by hadess** [comment]
Still relevant from what I can tell.

**Comment by stevekuznetsov** [comment]
Would you be willing to write a PR adding the phrasing you'd expect there?

**Comment by hadess** [comment]
No, sorry. I had to do a mandatory training with work, found the documentation lacking, and was asked by the trainer to open an issue. That's as far as my involvement goes.
