### ISSUE TITLE
re-enable portworx

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15269]
The rebase had to disable portworx because of a double proto registration.  See `UPSTREAM: <drop>: hack out portworx to avoid double proto registration` in the rebase branch here https://github.com/openshift/origin/pull/15234.

That pull is reviewed and green, so its a good base for starting over.  If you revert the UPSTREAM patch, you'll see error messages about duplicate registrations.

**Comment by harsh-px** [comment]
@deads2k Can we please get this back?

As a result of this, people using Openshift 3.6 are not able to use Portworx.

**Comment by deads2k** [comment]
> As a result of this, people using Openshift 3.6 are not able to use Portworx.

This is known in 3.7 (happened during the rebase).  If it's broken in 3.6, then that's a separate and unknown problem.

@derekwaynecarr @rootfs

**Comment by rootfs** [comment]
@deads2k portworx volume should work, but provisioner is not enabled (missing [here](https://github.com/openshift/origin/blob/release-3.6/pkg/cmd/server/kubernetes/master/controller/volumes.go#L103)

@harsh-px refer to https://github.com/openshift/origin/pull/15661

**Comment by harsh-px** [comment]
@rootfs Thanks for the info. If we submit a PR now to enable the provisioner, can this make it to any 3.6 patch release?

**Comment by adityadani** [comment]
PR https://github.com/openshift/origin/pull/15862 got merged. 
What is the procedure to cherry-pick changes into release-3.6 branch? We would like to enable portworx for the upcoming 3.6.x release.

**Comment by adityadani** [comment]
@deads2k What is the procedure to cherry-pick changes from master to a release branch?

**Comment by liggitt** [comment]
it was disabled only in the 3.7 branch as part of the rebase onto 1.7

**Comment by adityadani** [comment]
@liggitt. This PR #15862 solves two issues
1. solves the protobuf conflict because of which portworx was disabled (code commented out) in rebase 1.7 branch
2. Enables the portworx plugin in openshift. (adds portworx to the list of plugins in openshift)
AFAIK we will need to enable portworx just like other plugins #15661. 
But we wanted to do it the one of the 3.6.x releases as well. Is it possible to do so?
