### ISSUE TITLE
Remove use of legacy client

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15272]
The legacy openshift client doesn't support proto, is hard to maintain (I spent forever dealing with it in the rebase), and isn't the direction we're headed.  We need to delete it.

**Comment by mfojtik** [comment]
@deads2k i'm pretty sure I filled similar issue some time ago but can't find it now :-/

this will be a hell task as somebody will have to sweep the integration tests and extended tests and replace all clients there...

**Comment by deads2k** [comment]
> this will be a hell task as somebody will have to sweep the integration tests and extended tests and replace all clients there...

Yes it will be.  Still needs doing though.  I spent a large portion of the rebase hacking around to keep all the non-generated fakes still working with the backing library and broken schemes.  Shuffling the work to the rebaser (who pays it every three months) isn't a reasonable solution to "it'll be hard to move forward and keep up with the project".

**Comment by mfojtik** [comment]
Slowly getting there: https://github.com/openshift/origin/pull/15624
