### ISSUE TITLE
remove sdn's `GetNodeCondition`

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15283]
The rebase (https://github.com/openshift/origin/pull/15234) had to make a copy of `GetNodeCondition` in `pkg/sdn/plugin/subnets.go`.  The upstream function works against the external version.  We should switch to using the external version to match.

**Comment by danwinship** [comment]
@pravisankar I think I remember seeing this function get killed off or rewritten in one of your active PRs? (pkg/network/master/subnets.go:GetNodeCondition())

**Comment by pravisankar** [comment]
Yes, this was fixed by https://github.com/openshift/origin/pull/18758/
