### ISSUE TITLE
re-apply log message suppression

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15308]
`cb1f3d352b UPSTREAM: 48635: proxy/userspace: suppress "LoadBalancerRR: Removing endpoints" message`

The pick into the 1.7 rebase didn't make sense and it was just logging, so kicked to post-rebase.

**Comment by deads2k** [comment]
The rebase branch is review and green as a starting point https://github.com/openshift/origin/pull/15234

**Comment by dcbw** [comment]
@deads2k I think you can just grab https://github.com/kubernetes/kubernetes/pull/48635/commits/0233f2b924398e2e975e9dd33b891e602f9ec558 from upstream instead?  or do you want me to do that?

That commit applies fine.

**Comment by deads2k** [comment]
> @deads2k I think you can just grab kubernetes/kubernetes@0233f2b from upstream instead? or do you want me to do that?
> 
> That commit applies fine.

I'll give it a go. Thanks.
