### ISSUE TITLE
e2e cli-with-token failed to get "Using in-cluster configuration"

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#15329]
```github.com/openshift/origin/test/end-to-end/core.test/end-to-end/core.sh:385: executing 'cat '/data/src/github.com/openshift/origin/_output/scripts/test-end-to-end/logs/cli-with-token.log'' expecting success and text 'Using in-cluster configuration'```

Seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3264/testReport/junit/github/com_openshift_origin_test_end-to-end_core/test_end_to_end_core_sh_385__executing__cat___data_src_github_com_openshift_origin__output_scripts_test_end_to_end_logs_cli_with_token_log___expecting_success_and_text__Using_in_cluster_configuration_/

Job: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3264/

**Comment by bparees** [comment]
presumably a dupe of https://github.com/openshift/origin/issues/14897

@mfojtik can you put the full error in your issue descriptions?  e.g.:
```
=== BEGIN TEST CASE ===
test/end-to-end/core.sh:385: executing 'cat '/data/src/github.com/openshift/origin/_output/scripts/test-end-to-end/logs/cli-with-token.log'' expecting success and text 'Using in-cluster configuration'
FAILURE after 0.016s: test/end-to-end/core.sh:385: executing 'cat '/data/src/github.com/openshift/origin/_output/scripts/test-end-to-end/logs/cli-with-token.log'' expecting success and text 'Using in-cluster configuration': the output content test failed
Standard output from the command:
If you don't see a command prompt, try pressing enter.

There was no error output from the command.
=== END TEST CASE ===
```

makes it easier to hunt dupes (and easier on the person assigned to it)

**Comment by mfojtik** [comment]
@bparees I don't think this is a dupe, seems like as a different error (but the output seems similar)

**Comment by mfojtik** [comment]
@bparees ok, it is the same :-) journald rate limitter i assume.
