### ISSUE TITLE
test/cmd/sdn.sh:27: executing 'oc get netnamespace default -o jsonpath="{.netid}"' expecting success and text '^0$': the command returned the wrong error code; the output content test failed

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#15337]
seen multiple times post-rebase:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3261/consoleFull#23533870556c25df4e4b05b79524e5d52
```
FAILURE after 0.623s: test/cmd/sdn.sh:27: executing 'oc get netnamespace default -o jsonpath="{.netid}"' expecting success and text '^0$': the command returned the wrong error code; the output content test failed
There was no output from the command.
Standard error from the command:
Error from server (NotFound): netnamespaces.network.openshift.io "default" not found
```

cc @deads2k @danwinship @dcbw

**Comment by liggitt** [comment]
odd that it was looking for netnamespaces.network.openshift.io... should be defaulting to v1

**Comment by liggitt** [comment]
depending on what order the sdn netnamespace controller is initialized in, it is not auto-creating netnamespace objects

if I force the `openshift.io/sdn` controller initializer to run last, no netnamespace objects get auto-created

**Comment by deads2k** [comment]
> if I force the openshift.io/sdn controller initializer to run last, no netnamespace objects get auto-created

smacks of a controller init function not running in a gofunc.

**Comment by liggitt** [comment]
yup, just found it

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/view/All/job/merge_pull_request_origin/1300/

**Comment by liggitt** [comment]
fixed by https://github.com/openshift/origin/issues/15353
