### ISSUE TITLE
jenkins-plugin / openshift-restclient-java pod exe equivalent no longer works post-rebase

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#15330]
@openshift/devex @jcantrill FYI

See https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/136/testReport/junit/(root)/Extended/_image_ecosystem__jenkins__Slow__openshift_pipeline_plugin_jenkins_plugin_test_context___jenkins_plugin_test_exec_freestyle/

and 

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/136/testReport/junit/(root)/Extended/_image_ecosystem__jenkins__Slow__openshift_pipeline_plugin_jenkins_plugin_test_context___jenkins_plugin_test_exec_DSL/

Attempts to exec into a pod were working fine pre-3.7 rebase.

Now, the `onFailure` callback from the restclient IPodExec capability is getting called, with the msg from okhttp:

`java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'`

@deads2k - did the inventory of 3.7 rebase changes include adjustment to how `oc exec` worked from the client side?  If yes, then 

1) we'll need to adjust the openshift-restclient-java component accordingly.
2) this origin issue will get resolved with openshift-restclient-java and jenkins-plugin pulls

If no, then I'll try some comparison tests with the actual `oc exec` and see where the similarities / differences take us.

**Comment by deads2k** [comment]
> @deads2k - did the inventory of 3.7 rebase changes include adjustment to how oc exec worked from the client side? If yes, then

Not to my knowledge.  That would have broken compatibility with existing clients.

**Comment by gabemontero** [comment]
On Wed, Jul 19, 2017 at 10:31 AM, David Eads <notifications@github.com>
wrote:

> @deads2k <https://github.com/deads2k> - did the inventory of 3.7 rebase
> changes include adjustment to how oc exec worked from the client side? If
> yes, then
>
> Not to my knowledge. That would have broken compatibility with existing
> clients.
>
OK thanks.  I'll include test runs with the actual `oc exec` as well as the
jenkins plugin and diagnose from there.

**Comment by jcantrill** [comment]
@gabemontero  Have you tried running the restclient integration tests [1] , specifically: https://github.com/openshift/openshift-restclient-java/blob/master/src/test/java/com/openshift/internal/restclient/api/capabilities/PodExecIntegrationTest.java

It has been a while since I last ran them but last I tried, they were all running successfully assuming you had a server setup

[1] https://github.com/openshift/openshift-restclient-java#testing

**Comment by gabemontero** [comment]
OK, thanks for the tip @jcantrill, but I decided to stay as close as possible to the error scenario, at least initially.

So, oc from the cmd line works.  The REST url generated is:

```
https://127.0.0.1:8443/api/v1/namespaces/myproject/pods/centos-1-vzw4j/exec?command=echo&command=hello&command=world&command=1&container=centos&container=centos&stderr=true&stdout=true
```

The URL generated by the plugin/java-restclient that gets the 400 is:
```
https://172.30.0.1/api/v1/namespaces/myproject/pods/centos-1-vzw4j/exec?command=echo&command=hello&command=world&command=1
```

Ignoring the hosts used since this is cmd line vs. within a pod, the specifications of the container, stdout, stderr, are the differences.

With the plugin as is, I can specify the container explicitly, but still get the 400 error with the following URL generated by the restclient:

```
https://172.30.0.1/api/v1/namespaces/myproject/pods/centos-1-vzw4j/exec?container=centos&command=echo&command=hello&command=world&command=1
```

Note the container is specified twice as query params in the `oc` POST url via `--loglevel=8`.

@deads2k  - per the same plugin/restclient version working pre 3.7 rebase and breaking post 3.7 rebase, do these URL differences help pinpoint what the server side difference might be off the top of your head?  If not, I can start grepping through the k8s code, but any pointers would of course be appreciated.

**Comment by deads2k** [comment]
Yeah, that difference helps.  My guess would be defaulting in the apiserver: https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L218 .  It's hard to read and hard to test and that bit in particular is icky to deal with.

**Comment by deads2k** [comment]
@gabemontero the old 1.6 code was broken and stomped all values to true.  The fix could be a long time coming (if at all). I'd suggest explicitly setting the values to true (all other known callers do).

**Comment by gabemontero** [comment]
Thanks for the investigation / heads up @deads2k 

@jcantrill - I'll see about crafting a pull for the restclient that explicitly sets those additional params
