### ISSUE TITLE
executing 'oc import-image mysql-new-single:latest --from=docker.io/mysql:latest --confirm' expecting success and text 'sha256:'

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15333]
=== BEGIN TEST CASE ===
test/cmd/images_tests.sh:142: executing 'oc import-image mysql-new-single:latest --from=docker.io/mysql:latest --confirm' expecting success and text 'sha256:'
FAILURE after 30.430s: test/cmd/images_tests.sh:142: executing 'oc import-image mysql-new-single:latest --from=docker.io/mysql:latest --confirm' expecting success and text 'sha256:': the command returned the wrong error code; the output content test failed
There was no output from the command.
Standard error from the command:
Error from server (Timeout): Timeout: request did not complete within allowed duration
=== END TEST CASE ===

**Comment by kargakis** [comment]
cc: @soltysh

**Comment by soltysh** [comment]
It looks like docker hub hiccup at the time. I haven't seen this being reported more than once. I'll lower the prio for now, but feel free to bump it up again if it re-appears.

**Comment by bparees** [comment]
doesn't seem to be recurring, closing.
