### ISSUE TITLE
TestImageStreamImportAuthenticated - namespace "integration" not found

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#15359]
Details: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3293/testReport/junit/github/com_openshift_origin_test_integration%20%20%20/TestImageStreamImportAuthenticated/

Seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3293/

**Comment by bparees** [comment]
@mfojtik @miminar is this still an active flake?  no one has ref'd it in almost 2 months.  (in fact you were the only one to hit it, it seems)

**Comment by miminar** [comment]
Looks like fixed or of rare occurrence. Let's re-open if someone hits this.
