### ISSUE TITLE
API server requires `Origin` header for OPTION request

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#15398]
When sending OPTION requests the API server seems to require the `Origin` header to match a hostname in the master-config.yaml `corsAllowedOrigins` otherwise it returns a 403 response.

I'm not sure if this is intended as GET, POST, PATCH, DELETE, PUT don't require this but only OPTION

##### Version
v1.5.1

**Comment by liggitt** [comment]
That is correct. Web browsers "preflight" cross-domain requests by sending an OPTIONS request first and making sure the server allows the request.
