### ISSUE TITLE
origin_gce job takes 2hr, up from 1h30, reports 3x unit tests

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15392]
Sometime in the last week the origin_gce job jumped in duration from 1h35m to 2h.  Happened between https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_gce/878/ and https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_gce/880/ and is almost certainly the rebase.

Also, junit results for this job are reported three times, almost certainly unrelated.  @stevekuznetsov @jupierce @kargakis re: the multiple junit reports showing up.

**Comment by smarterclayton** [comment]
These three tests look like the bulk of the cost:

```
Test name | Duration  ↑ | Status
-- | -- | --
[k8s.io] SchedulerPriorities [Serial] Pod should avoid to schedule to node that have avoidPod annotation | 12 min | Passed
[k8s.io] SchedulerPriorities [Serial] Pod should be schedule to node that satisify the PodAffinity | 11 min | Passed
[k8s.io] SchedulerPriorities [Serial] Pod should be prefer scheduled to node that satisify the NodeAffinity | 11 min | Passed
```

**Comment by smarterclayton** [comment]
The next worst are:

```
deploymentconfigs reaper [Conformance] should delete all failed deployer pods and hook pods | 5 min 13 sec | Passed
[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications | 5 min 0 sec | Passed
[k8s.io] Probing container should *not* be restarted with a exec "cat /tmp/health" liveness probe [Conformance] | 4 min 12 sec | Passed
[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform canary updates and phased rolling updates of template modifications | 2 min 57 sec | Passed
[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy | 2 min 46 sec | Passed
```

**Comment by smarterclayton** [comment]
I guess I'm just going to disable the slow ones for now.

**Comment by kargakis** [comment]
Serial tests should run post-submit.

**Comment by smarterclayton** [comment]
We run these pre merge because we have occasionally regressed them.

On Jul 21, 2017, at 3:33 AM, Michail Kargakis <notifications@github.com>
wrote:

Serial tests should run post-submit.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15392#issuecomment-316927548>,
or mute the thread

**Comment by kargakis** [comment]
The submit queue can look into failures from post-submit jobs (in GCS) and
block merges.
We will not enable this initially, but as we setup post-submits, we are
going to use it.
