### ISSUE TITLE
oc cluster up --version=latest --metrics fails to install metrics

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#15410]
From the openshift-ansible-metrics-job log:

```
TASK [openshift_metrics : list existing secrets] *******************************
--
  | fatal: [127.0.0.1]: FAILED! => {
  | "changed": false,
  | "cmd": "oc -n openshift-infra --config=/tmp/openshift-metrics-ansible-PFjLDo/admin.kubeconfig get secrets -o name",
  | "failed": true,
  | "rc": 2
  | }
  |  
  | MSG:
  |  
  | [Errno 2] No such file or directory
```

##### Version

oc v3.6.0-alpha.2+d5b13f7-1092
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-rc.0+cf7626e-182
kubernetes v1.7.0+695f48a16f

##### Steps To Reproduce
Run `oc cluster up --version=latest --metrics` 

##### Current Result

openshift-ansible-metrics-job pod in the openshift-infra namespace will fail

cc @csrwng @rhamilto @jcantrill

**Comment by jcantrill** [comment]
@spadgett Looking at the version, this is 'oc' from HEAD of origin?  I need to rebuild it myself?

**Comment by spadgett** [comment]
@jcantrill Yeah, this seems to be an issue post rebase, although I'm not sure if you need the latest oc to reproduce. I build from master.

**Comment by jcantrill** [comment]
@sdodson  @sosiouxme rebuilding and using latest I can confirm the failure.  Debug into the pod  which is openshift-ansible, I does not appear to have the 'oc' or 'oadm' binary as part of the image or anywhere to be found in the path

**Comment by sosiouxme** [comment]
We can add `oc` back to the openshift-ansible image; however, I want to understand why. Why run `oc` on localhost (the host where Ansible is being run) when basically everything else in Ansible runs it on the master? Does this need to be a local action at all?

**Comment by jcantrill** [comment]
@sosiouxme I'm working on a PR right now to add it back in but this code is running in a job pod on the master.  If you can think of an alternative to making 'oc cluster up' work with logging and metrics I defer to your knowledge

**Comment by jcantrill** [comment]
The ref PR will fix the issue specifically associated with the error but metrics wont deploy until openshift-ansible/pull/4978 is merged as well.

**Comment by sosiouxme** [comment]
origin-ansible:latest,v3.7 should have the fix when [this build](https://ci.openshift.redhat.com/jenkins/job/build-and-release-latest-openshift-ansible-images/67/) completes.
