### ISSUE TITLE
doc: the osc login command breaks the steps in doc

### ISSUE THREAD

**Issue by xjvs** [openshift/origin#1541]
The recently merged change in doc (https://github.com/openshift/origin/blob/master/examples/sample-app/README.md) added a new line of command to be executed, but it breaks the followed commands.

The new command in step 3:

    $ osc login -u test-admin --client-certificate=`pwd`/openshift.local.certificates/admin/cert.crt --client-key=`pwd`/openshift.local.certificates/admin/key.key --certificate-authority=`pwd`/openshift.local.certificates/ca/cert.crt

If this command is executed, the followed command of 'openshift ex policy add-role-to-user ...' will fail as below:
 
    [root@test sample-app]# osc login -u test-admin --client-certificate=`pwd`/openshift.local.certificates/admin/cert.crt --client-key=`pwd`/openshift.local.certificates/admin/key.key --certificate-authority=`pwd`/openshift.local.certificates/ca/cert.crt
    Authentication required for https://localhost:8443 (openshift)
    Password: 
    Login successful.

    You don't have any projects. If you have access to create a new project, run

        $ openshift ex new-project <projectname> --admin="test-admin"

    To be added as an admin to an existing project, run

        $ openshift ex policy add-role-to-user admin "test-admin" -n <projectname>

    [root@test sample-app]# export KUBECONFIG=`pwd`/openshift.local.certificates/admin/.kubeconfig
    [root@test sample-app]# export CURL_CA_BUNDLE=`pwd`/openshift.local.certificates/ca/cert.crt
    [root@test sample-app]# openshift ex policy add-role-to-user view test-admin
    F0401 17:34:51.774296    4649 add_user.go:44] "/osapi/v1beta1/policyBindings/master?namespace=default" is forbidden because test-admin cannot get on policyBindings with name "master" in default

**Comment by vtts** [comment]
sorry, I forgot to point out which the doc is:
https://github.com/openshift/origin/blob/master/examples/sample-app/README.md

**Comment by xjvs** [comment]
it has been updated (bda8e88) in the latest version. close.
