### ISSUE TITLE
DNS is not working for service names

### ISSUE THREAD

**Issue by ksemaev** [openshift/origin#15449]
DNS service integrated on master is not set up on nodes. 
Master is listening for queries on port 8053 (kubernetes service), while dnsmasq on master uses file /etc/dnsmasq.d/node-dnsmasq.conf with default records "server=/cluster.local/127.0.0.1" which does not make any sense.
After manually setting value as "server=/cluster.local/127.0.0.1#8053", restring master VM, dnsmasq daemon is still using "using nameserver 127.0.0.1#53 for domain cluster.local"

This behavior is absolutely undocumented, all this wild stuff with NetworkManager + dnsmasq + iptables + kubernetes service is not understandable. Why can't the installer make this typical default configuration of master and nodes for working with kubernetes integrated dns?

##### Version
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. fresh install of master and several nodes
2. dig kubernetes.default.svc.cluster.local on master or any node or any pod

##### Current Result
; <<>> DiG 9.9.4-RedHat-9.9.4-50.el7_3.1 <<>> @localhost kubernetes.default.svc.cluster.local
; (2 servers found)
;; global options: +cmd
;; connection timed out; no servers could be reached

##### Expected Result
dig @localhost -p 8053 kubernetes.default.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-50.el7_3.1 <<>> @localhost -p 8053 kubernetes.default.svc.cluster.local
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65521
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN A

;; ANSWER SECTION:
kubernetes.default.svc.cluster.local. 30 IN A   172.30.0.1

;; Query time: 0 msec
;; SERVER: 127.0.0.1#8053(127.0.0.1)
;; WHEN: Tue Jul 25 15:34:22 MSK 2017
;; MSG SIZE  rcvd: 70

##### Additional Information
cat /etc/dnsmasq.d/node-dnsmasq.conf
server=/in-addr.arpa/127.0.0.1#8053
server=/cluster.local/127.0.0.1#8053

cat /etc/dnsmasq.d/origin-upstream-dns.conf
server=192.168.119.10
server=192.168.119.11

systemctl status dnsmasq.service
● dnsmasq.service - DNS caching server.
   Loaded: loaded (/usr/lib/systemd/system/dnsmasq.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-07-25 14:56:38 MSK; 42min ago
Jul 25 14:56:38 opsmaster.prod.elpass dnsmasq[3311]: using nameserver 127.0.0.1#53 for domain cluster.local
Jul 25 14:56:38 opsmaster.prod.elpass dnsmasq[3311]: using nameserver 127.0.0.1#53 for domain in-addr.arpa
Jul 25 14:56:38 opsmaster.prod.elpass dnsmasq[3311]: using nameserver 192.168.119.10#53
Jul 25 14:56:38 opsmaster.prod.elpass dnsmasq[3311]: using nameserver 192.168.119.11#53

**Comment by djdevin** [comment]
I just had this issue but it was because I was using the openshift-ansible installer "master" branch instead of the "release-1.5" branch. Maybe this is the same issue.

**Comment by ksemaev** [comment]
I managed to do like this:
created /etc/dnsmasq.d/custom-dnsmasq.conf with  "server=/cluster.local/127.0.0.1#8053" on master;
created /etc/dnsmasq.d/custom-dnsmasq.conf with  "server=/cluster.local/_master_ip_#8053" on nodes;
removed /etc/NetworkManager/dispatcher.d/99-origin-dns.sh on master;
commented /etc/dnsmasq.d/origin-dns.conf #enable-dbus on master and nodes;
restarted master and nodes;

**Comment by ksemaev** [comment]
@djdevin did switching to "release-1.5" helped? Is it supposed - that I need to switch?

**Comment by djdevin** [comment]
It did. The project page for openshift-ansible says they only guarantee the master branch to work with the latest version which would be 1.6. So if you want to run v1.5.1 it's best to use the release-1.5 branch for installing/scaling the cluster.

**Comment by djdevin** [comment]
Maybe this has something to do with https://github.com/openshift/openshift-ansible/pull/4530 where node DNS changed. I checked out to a revision of openshift-ansible before those commits and it doesn't exist. I think the master branch now requires 1.6+.

Likely same as #15419 and #15228

**Comment by sdodson** [comment]
Yeah, the release-1.5 branch of openshift-ansible should be used to install a 1.5 environment. The change moves to use the dns server on the node and all masters should be nodes but that change won't work on a 1.5 install.

**Comment by devopsnote** [comment]
when i use the openshift-ansible release-1.5
```
[root@master ~]# oc version 
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.example.com:8443
openshift v1.5.1
kubernetes v1.5.2+43a9be4
```
---------------------------------------------------
when i build a project 
```
Cloning "https://github.com/nichochen/mybank-demo-maven" 
error: build error: fatal: unable to access 'https://github.com/nichochen/mybank-demo-maven/': Failed connect to github.com:443; Connection timed out
```
---------------------------------------------------
on the host
```
[root@master ~]# ping -c 4 github.com 
PING github.com (192.30.255.112) 56(84) bytes of data.
64 bytes from 192.30.255.112 (192.30.255.112): icmp_seq=1 ttl=128 time=204 ms
64 bytes from 192.30.255.112 (192.30.255.112): icmp_seq=2 ttl=128 time=203 ms
64 bytes from 192.30.255.112 (192.30.255.112): icmp_seq=3 ttl=128 time=203 ms
64 bytes from 192.30.255.112 (192.30.255.112): icmp_seq=4 ttl=128 time=203 ms

--- github.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 203.086/203.752/204.877/0.782 ms

[root@master ~]# cat /etc/resolv.conf 
# Generated by NetworkManager
search example.com
nameserver 10.0.7.1
# nameserver updated by /etc/NetworkManager/dispatcher.d/99-origin-dns.sh
```
-----------------------------------------------------------------
on the pod 
```
[root@centos /]# ping  -c 4 github.com    
PING github.com.example.com (219.153.42.238) 56(84) bytes of data.

--- github.com.example.com ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3000ms

[root@centos /]# cat /etc/resolv.conf 
search default.svc.cluster.local svc.cluster.local cluster.local example.com
nameserver 10.0.7.1
nameserver 10.0.7.1
options ndots:5


[root@centos /]# ping -c 4 github.com.
PING github.com (192.30.255.112) 56(84) bytes of data.
64 bytes from 192.30.255.112 (192.30.255.112): icmp_seq=1 ttl=127 time=206 ms
64 bytes from 192.30.255.112 (192.30.255.112): icmp_seq=2 ttl=127 time=201 ms
64 bytes from 192.30.255.112 (192.30.255.112): icmp_seq=3 ttl=127 time=205 ms
64 bytes from 192.30.255.112 (192.30.255.112): icmp_seq=4 ttl=127 time=202 ms

--- github.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 201.671/204.047/206.493/2.026 ms
```
--------------------------------------------------------------------------

**Comment by ksemaev** [comment]
This issue is actual for release 1.5, but all releases newer then that are fine
