### ISSUE TITLE
Vagrant image does not work on Windows Host - Symlinks

### ISSUE THREAD

**Issue by tomgross** [openshift/origin#1544]
Running the Vagrant image as described in Step 6 of CONTRIBUTING.adoc#develop-on-virtual-machine-using-vagrant fails with because of CRLF line endings

``` bash
[vagrant@openshiftdev origin]$ hack/build-go.sh
ln: failed to create symbolic link ‘/data/src/github.com/openshift/origin/_outpu
t/local/go/src/github.com/openshift/origin’: Protocol error
```

This is an issue of the vboxvfs (https://www.virtualbox.org/ticket/818). Is there a way to handle the symlinks outside the shared folder?

**Comment by patjlm** [comment]
I saw [here](http://mluksa.blogspot.fr/2015/01/dealing-with-errors-when-running.html) that a workaround is to run vagrant up as administrator

**Comment by jfmatth** [comment]
The main issue I see with this is that it now makes a separate instance of the VM in Virtualbox, one for the user and one for the Administrator.

Is there another workaround here?
