### ISSUE TITLE
cmd test flake: 0-length response instead of expected timeout

### ISSUE THREAD

**Issue by miminar** [openshift/origin#15453]
```
=== BEGIN TEST CASE ===
test/cmd/timeout.sh:19: executing 'oc login -u testuser -p test --request-timeout=1ns' expecting failure and text 'Timeout exceeded while awaiting headers'
FAILURE after 0.356s: test/cmd/timeout.sh:19: executing 'oc login -u testuser -p test --request-timeout=1ns' expecting failure and text 'Timeout exceeded while awaiting headers': the output content test failed
There was no output from the command.
Standard error from the command:
error: 0-length response
=== END TEST CASE ===
```

Happened in job https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3449/testReport/junit/github/com_openshift_origin_test_cmd_request-timeout/test_cmd_timeout_sh_19__executing__oc_login__u_testuser__p_test___request_timeout_1ns__expecting_failure_and_text__Timeout_exceeded_while_awaiting_headers_/

**Comment by simo5** [comment]
@abstractj can you look into this one ?

**Comment by abstractj** [comment]
@simo5 sure!

**Comment by abstractj** [comment]
@miminar is this URL correct? I'm getting 404 when trying to access the report.

**Comment by miminar** [comment]
@abstractj unfortunately the test results don't survive long. The latest accessible run is 3481 as of now (not mentioning anomaly 1​25​0).

**Comment by abstractj** [comment]
@miminar thank you, I finally managed to reproduce the issue

Code to reproduce the issue:

```
#!/bin/sh

# Cleanup cluster resources created by this test
(
set +e
oc delete all,templates --all
exit 0
) &>/dev/null


oc new-app node

while true; do
   oc login -u testuser -p test --request-timeout=1ns 2>> log.txt &
done
```

**Comment by abstractj** [comment]
@juanvallejo I will definitely need your help on this. It seems something really tricky to debug.

**Comment by juanvallejo** [comment]
Fixed in https://github.com/openshift/origin/pull/15885
