### ISSUE TITLE
Writing the node config is not working

### ISSUE THREAD

**Issue by brenton** [openshift/origin#1545]
When I run `openshift start node --write-config --config=node.yaml` it doesn't appear to do anything.  It doesn't write node and it simply returns 0.  With `--loglevel=4` I see the following and then it exits:

~~~
I0401 11:26:08.289381   22934 create_signercert.go:80] Creating a signer cert with: admin.CreateSignerCertOptions{CertFile:"openshift.local.certificates/ca/cert.crt", KeyFile:"openshift.local.certificates/ca/key.key", SerialFile:"openshift.local.certificates/ca/serial.txt", Name:"openshift-signer@1427901968", Overwrite:false}
~~~

I'm running from the latest merged code (currently https://github.com/openshift/origin/commits/862caa729b3b4c939e2409434878560ed5968946).

**Comment by brenton** [comment]
@deads2k, I'm guessing this is a WIP? https://github.com/openshift/origin/blob/master/pkg/cmd/server/start/start_node.go#L117

**Comment by brenton** [comment]
Actually, looking again after lunch I see it's actually the RunNode function that handles this....

**Comment by brenton** [comment]
Upon further investigating, it's bailing at https://github.com/openshift/origin/blob/master/pkg/cmd/server/admin/create_nodeconfig.go#L143

It doesn't look like we're returning these error messages.  I'm not sure where it's suppose to get that value.  Setting --master doesn't work:

~~~
[root@dev origin]# openshift start node --write-config --config=node.yaml --loglevel=4 --master=https://192.168.133.100
Error: unknown flag: --master
openshift: invalid command [`start` `node` `--write-config` `--config=node.yaml` `--loglevel=4` `--master=https://192.168.133.100`]
Run 'openshift help' for usage
~~~

**Comment by deads2k** [comment]
I see it.

**Comment by brenton** [comment]
If I tell it not to creates the certs it will at least write out the node.yaml.  However, it doesn't format it correctly.  It's all on one line.

**Comment by deads2k** [comment]
That last will be fixed by https://github.com/openshift/origin/pull/1539

**Comment by brenton** [comment]
Cool, so I guess we just need to the error messages to print and then the defaults to set correctly in the config.

**Comment by deads2k** [comment]
If all you want is the node config, try `osadm create-node-config`

**Comment by brenton** [comment]
Yeah, I eventually came across that command.  Thanks!

Do we want to leave this issue open to track the printing of error messages and the possible certificate generation bug with `openshift start node --write-config` ?

**Comment by deads2k** [comment]
Yes.  I think #1554 will address it.  At the very least, it gives you a shot by providing a good error message.
