### ISSUE TITLE
Can we access the generated route hostname?

### ISSUE THREAD

**Issue by jwendell** [openshift/origin#15464]
In a template I have a route with an empty hostname, so that Openshift generates one for me. Later on this template, I define a pod and I would like to set an environment variable whose value is the generated hostname.

Is that possible?

**Comment by pweil-** [comment]
This is not currently possible in a template.  There is no guarantee that the route will actually have a name assigned when the pod is created either.  However, another option here would be to use a service name, especially since this would be internal cluster communication.
