### ISSUE TITLE
Using ImagePolicy with the integrated registry

### ISSUE THREAD

**Issue by rezie** [openshift/origin#15475]
When I enable the ImagePolicy plugin with a single execution rule - matching the integrated registry, my deployment don't seem to be passing the check.

To test this, I have pushed a postgres image to the internal registry (using the service's cluster IP as the registry name), and attempted to create a deployment using the image stream tag that is automatically created (postgres:latest). It seems that Origin might not be acknowledging that the image is from within the internal registry, and may perhaps be failing at this [point](https://github.com/openshift/origin/blob/v3.6.0-rc.0/pkg/image/admission/imagepolicy/rules/rules.go#L99).

Can I get some insight into how this is supposed to work? The [current documentation](https://docs.openshift.org/latest/admin_guide/image_policy.html) suggests that my process is mostly identical (except that I'm pushing the image directly).

##### Version
1.5.1 (also tested on 3.6.0-rc.0)

##### Steps To Reproduce
1. Setup the ImagePolicy

The rule I used (rest of the ImagePolicy configuration is left at the default):
```
- name: allow-internal-registry
  matchIntegratedRegistry: true
  onResources:
  - group: ""
  resource: pods
  - group: ""
  resource: builds
  skipOnResolutionFailure: true
```
Note: I also had to modify `imageConfig` in my master-config to include the internal registry in the prefix (e.g. `172.30.1.1:5000/openshift/origin-${component}:v3.6.0-rc.0`), and push that image into the internal registry (e.g. `docker push 172.30.1.1:5000/openshift/origin-deployer:v3.6.0-rc.0`) . Otherwise, the origin-deployer image cannot be deployed either.

2. Push an image to the internal registry
`docker push 172.30.1.1:5000/openshift/postgres:latest`

3. Attempt a deployment
`oc new-app -i postgres:latest`

##### Current Result
Error from deployment's events:
```
Error creating: Pod "" is invalid: spec.containers[0].image: Forbidden: this image is prohibited by policy
```
Logs after increasing the loglevel:
```
I0726 15:46:32.539922   15373 accept.go:106] Validate image 172.30.1.1:5000/openshift/postgres@sha256:9fd48e1602e56ee6af7b097684b66f25ab2f3addcebe1905f54e3df4cfbfbdf7 against rule "allow-internal-registry": false
I0726 15:46:32.540026   15373 accept.go:96] Made decision for &{DockerImage  172.30.1.1:5000/openshift/postgres@sha256:9fd48e1602e56ee6af7b097684b66f25ab2f3addcebe1905f54e3df4cfbfbdf7    } (as: 172.30.1.1:5000/openshift/postgres@sha256:9fd48e1602e56ee6af7b097684b66f25ab2f3addcebe1905f54e3df4cfbfbdf7, err: <nil>): false
I0726 15:46:32.540136   15373 accept.go:121] failed to create: [spec.containers[0].image: Forbidden: this image is prohibited by policy]
```

**Comment by rezie** [comment]
Forgot to mention - this doesn't seem to be an issue if I were to deploy the image via a pod directly, instead of via a deploymentconfig. This would be another difference from the examples provided by the documentation.

**Comment by mfojtik** [comment]
@rezie this happen because we resolve the image for DC from the imagestream which results into the image name (which is represented by digest or 'ID'). I'm looking into this now.

**Comment by mfojtik** [comment]
@rezie also the deployment needs to run the deployer image as a pod, how you configured that?

**Comment by rezie** [comment]
@mfojtik Re: the deployer - yes that's correct. Normally the Openshift component images would be in a separate external registry (and supply the `matchRegistries` portion of the ImagePolicy) and that would solve the problem as well, but I had pushed it to the internal registry for convenience during testing.

**Comment by mfojtik** [comment]
@rezie i tested this fix: https://github.com/openshift/origin/pull/15582

seems like with this I am able to deploy stuff from integrated registry.

**Comment by rezie** [comment]
Thanks for the help and glad to hear that. Any idea which release this would be part of?

**Comment by mfojtik** [comment]
@rezie since we just cut 3.6 and this missed, i think 3.6.1
