### ISSUE TITLE
routing documentation still refers to round-robin DNS as viable HA strategy

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1547]
We had had some internal discussions regarding whether or round-robin DNS is a viable HA strategy for routing, and came to the determination that it is not.

tl;dr:
If a DNS entry points to a dead router, a client will still end up trying to send traffic to the dead router until the TTL of the cached DNS entry expires. Upon expiry of the cached DNS entry, the client will perform another DNS lookup, which could potentially send you right back to the same dead router.

We should probably remove this from the docs, as keepalived seems to be the strategy we are shooting for for HA routing.

**Comment by pweil-** [comment]
I believe this can be closed, @ramr has added the keepalived section to the documentation.
