### ISSUE TITLE
oc adm verify-signature panics when verifying gpg v3 signature

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#15489]
Reproducer is a little bit tricky, but I tried to capture it in this [gist](https://gist.github.com/mfojtik/003ab21bf1b7c3d719e60081e95deea4).

Basically without this fix we can't verify signatures that RH provides for its own official images.
This is a blocker for 3.6.

@mtrmac i tested [this](https://github.com/openshift/origin/issues/15490) and it works perfectly fine. I know that you call it "do not use" but we might need to pick this up since the close for 3.6 is today and we don't have enough time to do full investigation. I'm open to backport whatever fix we decide for post-3.6. Agree?

**Comment by mfojtik** [comment]
@mpbarrett FYI

**Comment by mtrmac** [comment]
> I know that you call it "do not use" but we might need to pick this up since the close for 3.6 is today and we don't have enough time to do full investigation. I'm open to backport whatever fix we decide for post-3.6. Agree?

Sorry, no. It is literally better for that code to crash than to let an untrusted signature through.

Has anyone tested this with an untrusted signature? With a corrupt signature?

I’m working on the testing and treating this as a priority, but given pre-existing commitments the earliest I will probably be able to sign off on the patch is today sometime before EOB US time; very likely not before 6 PM Europe / noon US.

**Comment by mtrmac** [comment]
OK, ACKing based on tests in https://github.com/mtrmac/image/commits/openpgp-v3 .  The tests need cleaning up, but they do cover the relevant cases to my knowledge already.
