### ISSUE TITLE
export/import imagestreamtag: missing tag does not allow importing or patching objects

### ISSUE THREAD

**Issue by chlunde** [openshift/origin#15492]
imagestreamtags created by using OCR can't be imported after export, because they do not have a tag field.

##### Version
oc v3.6.0-rc.0+98b3d56
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server
openshift v3.6.0-rc.0+98b3d56
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
Push an image using openshift as a registry:

    oc new-project exp-imp
    docker tag docker.io/openshift/origin-docker-registry:v3.6.0-rc.0 registry-hostname/exp-imp/name:tag
    docker push registry-hostname/exp-imp/name:tag

Try to export and import the imagestreamtag.  It misses the tag field.

    oc get istag -o yaml > x
    oc apply -f x                                                                                                                                             
    Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
    The ImageStream "name" is invalid: spec.tags[tag].referencePolicy.type: Invalid value: "": valid values are "Source", "Local"

##### Current Result

Exported objects are not importable again.

```
apiVersion: v1
items:
- apiVersion: v1
  generation: 1
  image:
    dockerImageLayers: null
    dockerImageMetadata:
      ContainerConfig: {}
      Created: null
      Id: ""
      apiVersion: "1.0"
      kind: DockerImage
    dockerImageMetadataVersion: "1.0"
    dockerImageReference: docker-registry.default.svc:5000/exp-imp/name@sha256:dd6a15a2dd6506c3767e95efd854e439d9b3b636f99d3a37ba44cfa8614892af
    metadata:
      creationTimestamp: null
      name: sha256:dd6a15a2dd6506c3767e95efd854e439d9b3b636f99d3a37ba44cfa8614892af
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    creationTimestamp: 2017-07-27T09:28:58Z
    name: name:tag
    namespace: exp-imp
    resourceVersion: "33475"
    selfLink: /oapi/v1/namespaces/exp-imp/imagestreamtags/name%3Atag
    uid: 1fbcf5da-72ad-11e7-af02-005056a55c50
  tag: null
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
```

##### Expected Result

It should be possible to take a backup of the backing store of the registry and all images/imagestreams/imagestreamtags objects, and import them to a clean install to restore, or move data.

ping @soltysh

**Comment by soltysh** [comment]
@chlunde the reason you're having this problem is that the Image Stream created when pushing directly to internal registry does not have `.spec` field filled in, only `.status` (check `oc get is -o yaml`). This is intentional, since when you're moving from one environment to another you want to have a working resource after import (here you'd have to either re-push the image or provide secrets to be able to access that other registry). 

If you invoke following series of steps:
```
oc import-image hello --from=docker.io/openshift/hello-openshift --confirm
oc get istag/hello:latest -o yaml > istag.yaml
oc delete is/hello
oc create -f istag.yaml 
```
the istag creation will succeed, because the initial image has a specification that can be exported and re-used somewhere else, because it's pointing to externally reachable registry.

**Comment by soltysh** [comment]
I'm closing this, since it's working as expected. If you don't agree feel free to re-open and provide arguments why and what would be the expected result.

**Comment by chlunde** [comment]
@soltysh OK, thanks, I think I get it.

This means that backup/restore of a standalone registry needs to be either full etcd backup/restore, or pushing the images back if you have the metadata available.  If you want to keep the same registry backing store (like s3/minio) and have a new cluster, it also seems to be possible to restore only projects, and prefixes /openshift.io/images/ /openshift.io/imagestreams/ from etcd.

**Comment by soltysh** [comment]
@chlunde correct.
