### ISSUE TITLE
origin-master kept coredump after the machine rebooted 

### ISSUE THREAD

**Issue by ghost** [openshift/origin#15493]
After I rebooted the machine, the origin master kept coredump. 

##### Version
[root@tj1-container-cloud01 ~]# oc version
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. reboot the machine where the origin master was

##### Current Result
origin master cannot startup and keep coredump,  error messages is below:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xa84fdd]
```
##### Expected Result
origin master can start up normally

##### Additional Information
Full Error Information:

> "Create /api/v1/namespaces/openshift-infra/serviceaccounts" [603.65083ms] [3.023007ms] END
> I0727 18:33:06.143201   10254 logs.go:41] http: TLS handshake error from 127.0.0.1:48746: read tcp4 127.0.0.1:8443->127.0.0.1:48746: read: connection reset by peer
> W0727 18:33:06.470568   10254 run_components.go:207] Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients
> I0727 18:33:06.471061   10254 logs.go:41] skydns: ready for queries on cluster.local. for tcp4://0.0.0.0:8053 [rcache 0]
> I0727 18:33:06.471083   10254 logs.go:41] skydns: ready for queries on cluster.local. for udp4://0.0.0.0:8053 [rcache 0]
> I0727 18:33:06.571174   10254 run_components.go:224] DNS listening at 0.0.0.0:8053
> I0727 18:33:06.571240   10254 start_master.go:582] Controllers starting (*)
> I0727 18:33:06.571579   10254 serviceaccounts_controller.go:120] Starting ServiceAccount controller
> E0727 18:33:06.572545   10254 util.go:45] Metric for serviceaccount_controller already registered
> I0727 18:33:06.573549   10254 logs.go:41] warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xa84fdd]
> 
> goroutine 8092 [running]:
> panic(0x3b55580, 0xc4200100d0)
> 	/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
> github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper(0xc4204328c0, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/builddir/build/BUILD/origin-1.5.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:349 +0x24d
> github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper-fm(0x0, 0x0, 0x0, 0xc427551040, 0xc4257741f0)
> 	/builddir/build/BUILD/origin-1.5.1/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:106 +0x48
> github.com/openshift/origin/pkg/cmd/server/start.startControllers(0xc42175c000, 0xc4217dcfc0, 0x0, 0x0)
> 	/builddir/build/BUILD/origin-1.5.1/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:670 +0xaa0
> github.com/openshift/origin/pkg/cmd/server/start.(*Master).Start.func1(0xc42175c000, 0xc4217dcfc0)
> 	/builddir/build/BUILD/origin-1.5.1/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:436 +0x41
> created by github.com/openshift/origin/pkg/cmd/server/start.(*Master).Start
> 	/builddir/build/BUILD/origin-1.5.1/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:443 +0x761

**Comment by deads2k** [comment]
Hmmm... This looks very similar to condition that minikube had when someone tried to create a TPR.  Did you attempt to create any TPRs in the cluster?

**Comment by iloayuil** [comment]
I tried to deploy kubernetes-operator on openshift cluster, I wonder maybe the kubernetes-operator tried to create a TPR.  But I think the code should catch this problem exception instead of coredump.

**Comment by deads2k** [comment]
> I tried to deploy kubernetes-operator on openshift cluster, I wonder maybe the kubernetes-operator tried to create a TPR. But I think the code should catch this problem exception instead of coredump.

TPRs are known buggy in kubernetes and not supported in openshift.  The only way we were able to fix them upstream was to completely remove them and rewrite the feature using CustomResourceDefinitions.  

I'm afraid that there's really not a whole lot we can do to save an installation that turned them on.  As I noted, minikube has exactly the same problem.
