### ISSUE TITLE
SCC.*Capabilities: should be case insensitive

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#15503]
At this time it's possible to create a capabilities that differs only by case:
```console
$ oc get scc restricted -o yaml | grep -A7 requiredDropCapabilities
requiredDropCapabilities:
- KILL
- MKNOD
- SYS_CHROOT
- SETUID
- SETGID
- setgid
- Kill
```
I'd expect that it shouldn't be possible and if I'm adding "Kill" and there is already "KILL" then my cap should be ignored.

### Version
```console
$ oc version
oc v3.6.0-rc.0+58b7ec5-295-dirty
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

Server https://10.34.129.200:8443
openshift v3.6.0-rc.0+58b7ec5-295-dirty
kubernetes v1.7.0+695f48a16f
```

@pweil- @adelton WDYT?

**Comment by pweil-** [comment]
@php-coder capabilities here are container runtime specific values.  We don't want to make the assumption that all runtimes will always use case insensitive values or values cased one way or another.  Being exact is desired here.

**Comment by adelton** [comment]
OTOH, we make some assumption about the semantics of those strings, for things like `*` and `ALL` and `all`.

Is there currently a kernel or container runtime where capability names would be case sensitive and the difference in case would make a difference?

**Comment by pweil-** [comment]
not that I know of, it was a decision during the api review process though when I suggested relaxing it.
