### ISSUE TITLE
etcd storage test failed to catch CRD during 1.7 rebase

### ISSUE THREAD

**Issue by enj** [openshift/origin#15511]
@deads2k likes to make me have a bad day...

@liggitt

**Comment by liggitt** [comment]
registered into a different scheme, so didn't show up in the AllKnownTypes loop?

**Comment by deads2k** [comment]
> @deads2k likes to make me have a bad day...

It's a gift.

**Comment by enj** [comment]
Fixed by #20411 and #20746
