### ISSUE TITLE
Advanced installer failed with default configuration

### ISSUE THREAD

**Issue by ksemaev** [openshift/origin#15525]
Advanced installer failed with default configuration

##### Version
release-1.5

##### Steps To Reproduce
1. create  Single Master and Multiple Nodes Inventory File (https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master )
2. ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml

##### Current Result
All nodes and masters:
TASK [set_fact] 
fatal: [opsmaster.domain]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'deployment_type' is undefined\n\nThe error appears to have been in '/root/openshift-ansible/playbooks/common/openshift-cluster/initialize_facts.yml': line 18, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      openshift_docker_hosted_registry_network: \"{{ hostvars[groups.oo_first_master.0].openshift.common.portal_net }}\"\n  - set_fact:\n    ^ here\n"}

##### Expected Result
Suscessful installation

##### Additional Information
inventory has a line: openshift_deployment_type=origin

**Comment by php-coder** [comment]
Installer has its own repository and it's better to create an issue in their repository: https://github.com/openshift/openshift-ansible/issues

CC @sdodson

**Comment by sdodson** [comment]
@ksemaev You're using the latest from release-1.5 branch? Can I get `git describe` from within your checkout?

**Comment by ksemaev** [comment]
@sdodson surely, but I already made new setup from master branch. Fresh checkout for now gives me:
git describe
openshift-ansible-3.5.103-1

**Comment by ksemaev** [comment]
Moved fresh issue to installers repo: https://github.com/openshift/openshift-ansible/issues/5169
