### ISSUE TITLE
Some required package(s) are available at a version\nthat is higher than requested\n  openvswitch-2.6.1\nThis will prevent installing the version you requested.\nPlease check your enabled repositories or adjust openshift_release.

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15545]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/3102/consoleFull#78083386458b6e51eb7608a5981914356

Happens in the release-1.5 branch.

@sdodson @openshift/networking

**Comment by sdodson** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1476783

**Comment by sdodson** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1476783 cloned to backport this to 3.5

**Comment by rhcarvalho** [comment]
@sosiouxme looks like we're being too strict about versions and not allowing higher patch versions?

**Comment by sosiouxme** [comment]
This check wasn't in the install/upgrade path and in any case didn't run against ovs prior to 3.6.

It's actually expecting ovs to be 2.4:

```
                    "package_list": [
                        {
                            "check_multi": false, 
                            "name": "openvswitch", 
                            "version": "2.4"
                        }, 
```

And the reason it's doing that is because `openshift_version` is coming up with 1.4 as the OpenShift version that's being installed. 2.4 is the correct version of ovs that we suport for that version of OpenShift.

```
TASK [openshift_version : debug] ***********************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_version/tasks/main.yml:198
ok: [localhost] => {
    "generated_timestamp": "2017-07-29 07:51:34.503111", 
    "openshift_release": "VARIABLE IS NOT DEFINED!"
}

TASK [openshift_version : debug] ***********************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_version/tasks/main.yml:200
ok: [localhost] => {
    "generated_timestamp": "2017-07-29 07:51:34.535786", 
    "openshift_image_tag": "v1.4.1"
}

TASK [openshift_version : debug] ***********************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_version/tasks/main.yml:202
ok: [localhost] => {
    "generated_timestamp": "2017-07-29 07:51:34.570025", 
    "openshift_pkg_version": "-1.4.1-1.el7"
}
```

@kargakis I'm not sure how this job is intended to work but it seems to be using the 3.6 installer to install Origin 1.4 (at least that's what RPMs/images are available) but with a more recent version of ovs available. Can you check what's supposed to be happening here?

I don't know that anyone is regularly testing 1.4 installs with 3.6 installer, though I don't know any specific reasons it wouldn't work given the right content to install.

**Comment by kargakis** [comment]
@jhadvig ^

**Comment by jhadvig** [comment]
So the issue (probably the cause of this one) is that we are installing and upgreadint different versions of origin.
```
+ source ORIGIN_VARS
++ ORIGIN_INSTALL_VERSION=1.5.1-1.el7
++ ORIGIN_INSTALL_MINOR_VERSION=5
++ ORIGIN_UPGRADE_RELEASE_VERSION=3.6.0-0.rc.0.385.e7e33d9
++ ORIGIN_UPGRADE_RELEASE_MINOR_VERSION=6
+ source OPENSHIFT_ANSIBLE_VARS
++ ATOMIC_OPENSHIFT_UTILS_INSTALL_VERSION=3.6.173.0.1-1.git.0.71e81fa.el7
++ ATOMIC_OPENSHIFT_UTILS_INSTALL_MINOR_VERSION=6
++ ATOMIC_OPENSHIFT_UTILS_UPGRADE_RELEASE_VERSION=3.7.2-1.git.0.0fe87cb.el7
++ ATOMIC_OPENSHIFT_UTILS_UPGRADE_RELEASE_MINOR_VERSION=7
```

**Comment by sosiouxme** [comment]
`openshift_version` determines the version to install based on the inventory and the RPMs/images available, so I suspect these env vars aren't getting translated into what you actually want.

**Comment by jhadvig** [comment]
@sosiouxme yeah but we are passing the `openshift_pkg_version` directly as a param to ansible when running the install && upgrade playbook. Check https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_branch_origin_extended_conformance_install_update.yml#L120

**Comment by jhadvig** [comment]
So in this case we have 3.6 for openshift-ansible but not for origin. Thats why we are installing and upgrading to different versions. 
I would suggest to check the minor versions of the both built rpms(origin && o-a) and if they dont match then either fail prematurely or install corresponding version of the dependency package, in this case o-a.
@stevekuznetsov thoughts ?

**Comment by stevekuznetsov** [comment]
@jhadvig how did we end up with different minor versions of origin and o-a?

**Comment by jhadvig** [comment]
@stevekuznetsov cause there already is a 3.7 for a-o but not for origin

**Comment by stevekuznetsov** [comment]
@smarterclayton this is why we need `alpha.0`

**Comment by jhadvig** [comment]
+1

**Comment by sosiouxme** [comment]
@kargakis @jhadvig @stevekuznetsov is this issue still relevant? I'm pretty sure CI/CD hasn't been sitting still for the last few releases ...

**Comment by sosiouxme** [comment]
Feel free to reopen if still relevant.
