### ISSUE TITLE
Status 405 trying to pull repository google_containers/pause

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15543]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/5104/

**Comment by smarterclayton** [comment]
Why are we pulling that one when we have a pod image?  We used to use origin/pod

**Comment by pweil-** [comment]
Hrm, looks like this was changed in the 1.5 rebase for the pruning tests:

https://github.com/openshift/origin/pull/12143/commits/11337ac609c1e2d3111cbb6685e2f9120c82aea0#diff-4ea7c8f0aaeae849c3760842d6b42c60R542

**Comment by mfojtik** [comment]
Fix: https://github.com/openshift/origin/pull/15601

**Comment by bparees** [comment]
closing based on supposed fix and no recurrences.
