### ISSUE TITLE
git clone do not create a whole project

### ISSUE THREAD

**Issue by shefbel** [openshift/origin#15555]
I found out that some directories are missed after cloning project
**Step to reproduce:**

git clone https://github.com/openshift/origin.git

**Conditions:**
Reproduced under Linux and Windows
_[CentOS 7]_
git version 1.8.3.1

_[Windows]_
git version 2.10.1.windows.1

**Cloning result:**
_[start files after cloning]_
.git
.github
.tito
api
assets
cmd
Godeps
.gitattributes
.gitignore
.travis.yml
CONTRIBUTING.adoc
HACKING.md
LICENSE
Makefile
OWNERS
README.md
UPGRADE.md
Vagrantfile
_[end files after cloning]_

**Expected Result:**
_[expected dir/files structure]_
.github
.tito
api
assets
cmd
contrib
docs
examples
Godeps
hack
images
pkg
test
tools
vendor
.gitattributes
.gitignore
.travis.yml
CONTRIBUTING.adoc
doc.go
HACKING.md
LICENSE
Makefile
origin.spec
OWNERS
README.md
UPGRADE.md
Vagrantfile

Please advise how fix it.

**Comment by php-coder** [comment]
That's weird.

Could you post the output of the the commands `git status`, `git branch`, and `git rev-parse HEAD`?

**Comment by shefbel** [comment]
**git status**
http://www.shefbel.org/openshift_origin_status_after_clone.txt.7z

status shows that all that directories were delete, that is the reason why openshift_origin_status_after_clone.txt is too big.


**git branch**
* master

**git rev-parse HEAD**
f8071e8787e54576ab605010c536c32443d4c02d

**Comment by jim-minter** [comment]
Set `git config --system core.longpaths true`.  See https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows.
