### ISSUE TITLE
v3.6.0 release version issues?

### ISSUE THREAD

**Issue by tobru** [openshift/origin#15571]
When downloading the latest `v3.6.0` release from https://github.com/openshift/origin/releases/tag/v3.6.0 the versioning looks weird.

##### Version

```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0-rc.0+de23676-359
kubernetes v1.7.0+695f48a16f
```

##### Steps To Reproduce
1. wget https://github.com/openshift/origin/releases/download/v3.6.0/openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit.tar.gz
2. tar xvzf openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit.tar.gz
3. cd openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit
4. ./oc cluster up
5. oc version

##### Current Result

```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0-rc.0+de23676-359
kubernetes v1.7.0+695f48a16f
```

##### Expected Result

I expect the server version to report `v3.6.0` without `-rc.0` and kubernetes to be version `v1.6.1-1-g5115d708d7` (as stated in https://github.com/openshift/origin/releases/v3.6.0-rc.0).

**Comment by tnozicka** [comment]
@tobru does it work for you now? see: https://lists.openshift.redhat.com/openshift-archives/dev/2017-July/msg00063.html

**Comment by tobru** [comment]
@tnozicka Yes, the image seems to be correct now! Thanks for checking.
