### ISSUE TITLE
hack/env make build-rpms writes to container FS

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15573]
It should be writing to a volume for performance and other reasons.  It's writing about 5.5GB.  

@stevekuznetsov @kargakis

**Comment by smarterclayton** [comment]
Also, a good fraction (20%?) of `make build-rpms` is a single threaded `rpmbuild` step.  Not sure we can fix that, unless rpmbuild explicitly has a parallelism flag we're skipping.

**Comment by smarterclayton** [comment]
Splitting out cluster-capacity and service catalog are likely the two
biggest wins we can get.

**Comment by smarterclayton** [comment]
(in terms of overall reducing the release time).  But these look like low
hanging fruit.  5.5gb is pretty ridiculous though.

**Comment by kargakis** [comment]
cc @adammhaile @smunilla @bbguimaraes

**Comment by sdodson** [comment]
> /cc @sdodson @dgoodwin re: parallelizing rpmbuild

Aside from the multi-arch client bits if we call `hack/build-go.sh` with all of the binaries we want does it not parallelize things?

**Comment by sdodson** [comment]
Also, is our process still building items outside of rpmbuild and then again inside rpmbuild? Could the process not be amended to remove that duplicate effort?

**Comment by smarterclayton** [comment]
Hack/build-go is fully parallel (except for the link step, which doesn't
always rise above a certain number of cores.

In the problem we are discussing here - there is no duplicate effort
anymore.  The release tars are all for github and aren't in the critical
path.  That step in the future might diminish in importance, but it's not
being invoked in duplicate.

On Aug 1, 2017, at 9:09 AM, Scott Dodson <notifications@github.com> wrote:

Also, is our process still building items outside of rpmbuild and then
again inside rpmbuild? Could the process not be amended to remove that
duplicate effort?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15573#issuecomment-319364971>,
or mute the thread

**Comment by bparees** [comment]
@smarterclayton @kargakis @stevekuznetsov who should own this?

(i'm trying to get all our open origin issues to have owners)

**Comment by stevekuznetsov** [comment]
Go build chain writes to `/tmp` which is a volume and this is the root cause of the `etcd` issues in CI. Consider this fixed.

/close
