### ISSUE TITLE
oc version missing openshift server version

### ISSUE THREAD

**Issue by tobru** [openshift/origin#15578]
After trying to upgrade OpenShift to `v3.6.0` with the wrong built images (See #15571) the command `oc version` doesn't show the OpenShift server version anymore. The built images now seem to contain the correct OpenShift version, so I tried the upgrade again, but the version number doesn't display anymore. The OpenShift Webinterface shows:

```
OpenShift Master: v3.6.0+c4dd4cf
Kubernetes Master: v1.6.1+5115d708d7
```

##### Version

```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
n/a

##### Current Result

```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.6.1+5115d708d7
```

##### Expected Result

```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

**Comment by pweil-** [comment]
@openshift/cli-review

**Comment by pweil-** [comment]
@spadgett regression?

**Comment by spadgett** [comment]
@pweil- I believe it is a regression. @fabianofranz ?

This is what I see on a mac at least.

```
openshift-origin-client-tools-v3.6.0-c4dd4cf-mac ./oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

**Comment by tobru** [comment]
If you need more information from my side, I'm happy to help!

**Comment by juanvallejo** [comment]
@fabianofranz I suspect this is happening due to either a [NotFound, Unauthorized, or Forbidden error](https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/version.go#L173)

@tobru could you please post the output of `https://localhost:8443/version/openshift`?

**Comment by juanvallejo** [comment]
@tobru also, if possible, could you post the output of `oc version --loglevel 8`?

**Comment by juanvallejo** [comment]
cc @smarterclayton

**Comment by pweil-** [comment]
@mfojtik

**Comment by mdshuai** [comment]
Should same bug with https://bugzilla.redhat.com/show_bug.cgi?id=1471717 Have you enable aggregator?  In `master-config.yaml`
```
aggregatorConfig:
  proxyClientInfo:
    certFile: aggregator-front-proxy.crt
    keyFile: aggregator-front-proxy.key
```

**Comment by tobru** [comment]
YES! That was it... This was somehow a left-over from some testings with the service catalog.

**Comment by juanvallejo** [comment]
Linking related upstream issue: https://github.com/kubernetes-incubator/service-catalog/issues/722
