### ISSUE TITLE
Failure when building on the 3.6.0 branch in RPM version

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15579]
Building on 3.6.0 post release cut: https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install_update/935/consoleFull#113722548058b6e51eb7608a5981914356

```
++ OS_GIT_VERSION=v3.6.0+68c4c59-3
++ [[ clean == \d\i\r\t\y ]]
++ os::build::version::kubernetes_vars
+++ go run /data/src/github.com/openshift/origin/tools/godepversion/godepversion.go /data/src/github.com/openshift/origin/Godeps/Godeps.json k8s.io/kubernetes/pkg/api comment
++ KUBE_GIT_VERSION=v1.6.1-1-g5115d708d7
+++ go run /data/src/github.com/openshift/origin/tools/godepversion/godepversion.go /data/src/github.com/openshift/origin/Godeps/Godeps.json k8s.io/kubernetes/pkg/api
++ KUBE_GIT_COMMIT=fff65cf
+++ echo v1.6.1-1-g5115d708d7
+++ sed 's/-\([0-9]\{1,\}\)-g\([0-9a-f]\{7,40\}\)$/\+\2/'
++ KUBE_GIT_VERSION=v1.6.1+5115d708d7
++ [[ v1.6.1+5115d708d7 =~ ^v([0-9]+)\.([0-9]+)(\.[0-9]+)*([-].*)?$ ]]
++ os::build::version::etcd_vars
+++ go run /data/src/github.com/openshift/origin/tools/godepversion/godepversion.go /data/src/github.com/openshift/origin/Godeps/Godeps.json github.com/coreos/etcd/etcdserver comment
++ ETCD_GIT_VERSION=v3.2.1
+++ go run /data/src/github.com/openshift/origin/tools/godepversion/godepversion.go /data/src/github.com/openshift/origin/Godeps/Godeps.json github.com/coreos/etcd/etcdserver
++ ETCD_GIT_COMMIT=61fc123
++ [[ v3.6.0+68c4c59-3 =~ ^v([0-9](\.[0-9]+)*)(.*) ]]
++ OS_RPM_VERSION=3.6.0
++ metadata=+68c4c59-3
++ [[ + == \+ ]]
++ [[ +68c4c59-3 =~ ^\+([a-z0-9]{7,40})(-([0-9]+))?(-dirty)?$ ]]
++ build_sha=68c4c59
++ build_num=3
++ OS_RPM_RELEASE=1.3.68c4c59
++ export OS_RPM_NAME OS_RPM_VERSION OS_RPM_RELEASE OS_RPM_ARCHITECTURE
++ echo origin-3.6.0-1.3.68c4c59.x86_64
+ origin_package=origin-3.6.0-1.3.68c4c59.x86_64
+ rpm -V origin-3.6.0-1.3.68c4c59.x86_64
package origin-3.6.0-1.3.68c4c59.x86_64 is not installed
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: ENSURE BUILT VERSION OF ORIGIN IS INSTALLED [00h 00m 01s] ##########
```

**Comment by smarterclayton** [comment]
@stevekuznetsov is this a known?

**Comment by stevekuznetsov** [comment]
Not clear .. @jhadvig will know better

**Comment by jhadvig** [comment]
So the issue is because of condition we added in https://github.com/openshift/aos-cd-jobs/pull/313.
THe idea was to skip the build if the o-a point to a non master branch, but now I see that can cause problem.
I've copied the job and removed the condition in it.  Here is the job testing the change: 
https://ci.openshift.redhat.com/jenkins/view/All/job/jhadvig_install_upgrade/1/

**Comment by kargakis** [comment]
Still an issue?

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/3378/consoleFull#-88500902058b6e51eb7608a5981914356

**Comment by kargakis** [comment]
Raising priority as this job seems to fail consistently now: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/

**Comment by stevekuznetsov** [comment]
A version of the Origin package that sorts newer than what we're building off of master was pushed to the CentOS PaaS SIG repos we have enabled in the job.

**Comment by stevekuznetsov** [comment]
I've updated the `oct` playbooks to ensure that the latest CentOS repo we add has `origin*` excluded. We'll need a new base AMI for this to trickle through, though. I'll see if we can do that in the job itself as well for now to unblock the queue.

**Comment by stevekuznetsov** [comment]
Fixed this as per above.
