### ISSUE TITLE
S2I Build error due to read: connection reset by peer

### ISSUE THREAD

**Issue by reddyrocks** [openshift/origin#15592]
I am running s2i build on Jenkins slave that has s2i mixin and it used to work fine for most of the builds but all of a sudden, I am seeing a new error.
I0801 17:18:20.244127    9638 docker.go:948] Removing container "12f9115bbf9dff39984dee60326c9f05bf6a146d64bb6a46f24f79624e5ddd19" ...
I0801 17:18:20.487410    9638 docker.go:952] Removed container "12f9115bbf9dff39984dee60326c9f05bf6a146d64bb6a46f24f79624e5ddd19"
I0801 17:18:20.487840    9638 cleanup.go:33] Removing temporary directory /tmp/s2i478542863
I0801 17:18:20.487901    9638 fs.go:159] Removing directory '/tmp/s2i478542863'
I0801 17:18:20.488082    9638 sti.go:624] 
E0801 17:18:20.495194    9638 main.go:368] An error occurred: waiting for container "12f9115bbf9dff39984dee60326c9f05bf6a146d64bb6a46f24f79624e5ddd19" to stop: An error occurred trying to connect: Post http://jenkins.host.com/containers/12f9115bbf9dff39984dee60326c9f05bf6a146d64bb6a46f24f79624e5ddd19/wait: read tcp : 
ip1 to ip2 read: connection reset by peer

Let me know, if there is any way to solve this ???

Note:
I have replaced our actual hostname of jenkins with "host" and ip address with "ip1 and ip2".

**Comment by php-coder** [comment]
@openshift/devex

**Comment by mfojtik** [comment]
what is "http://jenkins.host.com/containers/12f9115bbf9dff39984dee60326c9f05bf6a146d64bb6a46f24f79624e5ddd19/wait" ?

**Comment by bparees** [comment]
please don't open the same issue in multiple places, it results in duplicated efforts by different groups of people.
https://github.com/openshift/source-to-image/issues/782
