### ISSUE TITLE
lstat /var/lib/docker/devicemapper/mnt/.../rootfs/go/src/github.com/openshift/origin/_output/local/releases: no such file or directory

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#15602]
Seen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/5312/consoleFull#9938473135898c58db7602c31c0eab717

**Comment by mfojtik** [comment]
@smarterclayton @stevekuznetsov not sure if infra problem or docker problem.

**Comment by stevekuznetsov** [comment]
```
Running TestRootAPIPaths...
failed  TestRootAPIPaths
```

This is a harmless failure in a cleanup script. Your job had a failed test.
