### ISSUE TITLE
Origin 1.5 : slow pods reschedule

### ISSUE THREAD

**Issue by cello86** [openshift/origin#15623]
We installed a fresh Origin 1.5 installation and we tried to verify the infrastructure node switch in case of node failure for the docker registry and console but we noticed that Origin spends some minutes to create the new pods on the other infra node.

##### Version
# oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://dev-openshift.test.local:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. stop the docker daemon on infra node where the registry and console pod are running
2. monitor the pods status and all are running
3. after some minutes Origin creates new pods and marks the other as unkwnow.

```
# oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-w9ngm    1/1       Unknown   0          16m
docker-registry-1-xr0st    0/1       Running   0          1m
registry-console-1-0z7g2   0/1       Running   0          1m
registry-console-1-htzt2   1/1       Unknown   0          16m
router-1-1dc1h             0/1       Pending   0          16m
router-1-7j90j             1/1       Unknown   0          44m
router-1-pncsk             0/1       Running   0          1m 

```
4. the new containers are created on the other node
5. the old containers are marked as Unknown still the node become available

##### Current Result
the results reported into the point 4, 5 and 6.

##### Expected Result
We would understand if we can configure a more reactive reschedule action into the pods behavior.

##### Additional Information
# oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/root/.kube/config'
Info:  Using context for cluster-admin access: 'default/dev-openshift-test-it:8443/system:admin'
[Note] Performing systemd discovery

[Note] Running diagnostic: ConfigContexts[default/dev-openshift-test-it:8443/system:admin]
       Description: Validate client config context is complete and has connectivity
       
Info:  The current client config context is 'default/dev-openshift-test-it:8443/system:admin':
       The server URL is 'https://dev-openshift.test.local:8443'
       The user authentication is 'system:admin/dev-openshift-test-it:8443'
       The current project is 'default'
       Successfully requested project list; has access to project(s):
         [default kube-system logging management-infra openshift openshift-infra]
       
[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint
       
ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:155]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected
              
       Info:  Service account token successfully authenticated to master
       ERROR: [DP1014 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:173]
              Request to integrated registry timed out; this typically indicates network or SDN problems.
              
       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected
              
       [Note] Summary of diagnostics execution (version v1.5.0+031cbe4):
       [Note] Errors seen: 1
       
[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint
       
ERROR: [DNet2007 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:141]
       timed out waiting for the condition
       
[Note] Skipping diagnostic: AggregatedLogging
       Description: Check aggregated logging integration for proper configuration
       Because: No LoggingPublicURL is defined in the master configuration
       
[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry
       
ERROR: [DClu1007 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:237]
       The "docker-registry" service has multiple associated pods each using
       ephemeral storage. These are likely to have inconsistent stores of
       images. Builds and deployments that use images from the registry may
       fail sporadically. Use a single registry or add a shared storage volume
       to the registries.
       
WARN:  [DClu1010 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:263]
       Failed to read the logs for the "docker-registry-1-w9ngm" pod belonging to
       the "docker-registry" service. This is not a problem by itself but
       prevents diagnostics from looking for errors in those logs. The
       error encountered was:
       (*errors.StatusError) Get https://dev-openshift05.test.local:10250/containerLogs/default/docker-registry-1-w9ngm/registry: dial tcp 192.168.98.145:10250: getsockopt: connection refused
       
WARN:  [DClu1009 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:244]
       The "docker-registry-1-xr0st" pod for the "docker-registry" service is not running.
       This may be transient, a scheduling error, or something else.
       
WARN:  [DClu1014 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:316]
       The "docker-registry" service exists with 1 associated pod(s), but there
       are 0 endpoints in the "docker-registry" service.
       This mismatch likely indicates a system bug, and builds and
       deployments that require the registry may fail sporadically.
       
[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects
       
Info:  clusterrolebinding/cluster-readers has more subjects than expected.
       
       Use the `oadm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.
       
Info:  clusterrolebinding/cluster-readers has extra subject {ServiceAccount management-infra management-admin    }.
Info:  clusterrolebinding/cluster-readers has extra subject {ServiceAccount default router    }.

Info:  clusterrolebinding/self-provisioners has more subjects than expected.
       
       Use the `oadm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.
       
Info:  clusterrolebinding/self-provisioners has extra subject {ServiceAccount management-infra management-admin    }.

[Note] Running diagnostic: ClusterRoles
       Description: Check that the default ClusterRoles are present and contain the expected permissions
       
[Note] Running diagnostic: ClusterRouterName
       Description: Check there is a working router
       
WARN:  [DClu2008 from diagnostic ClusterRouter@openshift/origin/pkg/diagnostics/cluster/router.go:193]
       Failed to read the logs for the "router-1-7j90j" pod belonging to
       the router deployment. This is not a problem by itself but prevents
       diagnostics from looking for errors in those logs. The error encountered
       was:
       (*errors.StatusError) Get https://dev-openshift05.test.local:10250/containerLogs/default/router-1-7j90j/router: dial tcp 192.168.98.145:10250: getsockopt: connection refused
       
[Note] Running diagnostic: MasterNode
       Description: Check if master is also running node (for Open vSwitch)
       
Info:  Found a node with same IP as master: dev-openshift04.test.local

[Note] Skipping diagnostic: MetricsApiProxy
       Description: Check the integrated heapster metrics can be reached via the API proxy
       Because: The heapster service does not exist in the openshift-infra project at this time,
       so it is not available for the Horizontal Pod Autoscaler to use as a source of metrics.
       
[Note] Running diagnostic: NodeDefinitions
       Description: Check node records on master
       
WARN:  [DClu0003 from diagnostic NodeDefinition@openshift/origin/pkg/diagnostics/cluster/node_definitions.go:112]
       Node dev-openshift01.test.local is ready but is marked Unschedulable.
       This is usually set manually for administrative reasons.
       An administrator can mark the node schedulable with:
           oadm manage-node dev-openshift01.test.local --schedulable=true
       
       While in this state, pods should not be scheduled to deploy on the node.
       Existing pods will continue to run until completed or evacuated (see
       other options for 'oadm manage-node').
       
WARN:  [DClu0003 from diagnostic NodeDefinition@openshift/origin/pkg/diagnostics/cluster/node_definitions.go:112]
       Node dev-openshift02.test.local is ready but is marked Unschedulable.
       This is usually set manually for administrative reasons.
       An administrator can mark the node schedulable with:
           oadm manage-node dev-openshift02.test.local --schedulable=true
       
       While in this state, pods should not be scheduled to deploy on the node.
       Existing pods will continue to run until completed or evacuated (see
       other options for 'oadm manage-node').
       
WARN:  [DClu0003 from diagnostic NodeDefinition@openshift/origin/pkg/diagnostics/cluster/node_definitions.go:112]
       Node dev-openshift03.test.local is ready but is marked Unschedulable.
       This is usually set manually for administrative reasons.
       An administrator can mark the node schedulable with:
           oadm manage-node dev-openshift03.test.local --schedulable=true
       
       While in this state, pods should not be scheduled to deploy on the node.
       Existing pods will continue to run until completed or evacuated (see
       other options for 'oadm manage-node').
       
WARN:  [DClu0003 from diagnostic NodeDefinition@openshift/origin/pkg/diagnostics/cluster/node_definitions.go:112]
       Node dev-openshift04.test.local is ready but is marked Unschedulable.
       This is usually set manually for administrative reasons.
       An administrator can mark the node schedulable with:
           oadm manage-node dev-openshift04.test.local --schedulable=true
       
       While in this state, pods should not be scheduled to deploy on the node.
       Existing pods will continue to run until completed or evacuated (see
       other options for 'oadm manage-node').
       
WARN:  [DClu0002 from diagnostic NodeDefinition@openshift/origin/pkg/diagnostics/cluster/node_definitions.go:110]
       Node dev-openshift05.test.local is defined but is not marked as ready.
       Ready status is Unknown because "NodeStatusUnknown"
       If the node is not intentionally disabled, check that the master can
       reach the node hostname for a health check and the node is checking in
       to the master with the same hostname.
       
       While in this state, pods should not be scheduled to deploy on the node,
       and any existing scheduled pods will be considered failed and removed.
       
[Note] Running diagnostic: ServiceExternalIPs
       Description: Check for existing services with ExternalIPs that are disallowed by master config
       
[Note] Running diagnostic: AnalyzeLogs
       Description: Check for recent problems in systemd service logs
       
Info:  Checking journalctl logs for 'origin-node' service
Info:  Checking journalctl logs for 'docker' service

[Note] Running diagnostic: MasterConfigCheck
       Description: Check the master config file
       
WARN:  [DH0005 from diagnostic MasterConfigCheck@openshift/origin/pkg/diagnostics/host/check_master_config.go:52]
       Validation of master config file '/etc/origin/master/master-config.yaml' warned:
       assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
       assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console
       auditConfig.auditFilePath: Required value: audit can now be logged to a separate file
       
[Note] Running diagnostic: NodeConfigCheck
       Description: Check the node config file
       
Info:  Found a node config file: /etc/origin/node/node-config.yaml

[Note] Running diagnostic: UnitStatus
       Description: Check status for related systemd units
       
[Note] Summary of diagnostics execution (version v1.5.0+031cbe4):
[Note] Warnings seen: 10
[Note] Errors seen: 3

**Comment by cello86** [comment]
We have identified the problem on version 3.6. The master nodes use the default configuration of "podEvictionTimeout" configured to 5 minutes and after the change to 30 seconds the behavior of the pods rescheduling related to a node failure is more responsive.

**Comment by DanyC97** [comment]
@cello86 any chance you can close this issue please ? thx
