### ISSUE TITLE
PSP/SCC should sort linux levels for logical comparison

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#15627]
In another issue it was noticed that PSP/SCC should recognize that SELinux levels can be logically equivalent.  Currently levels will be failed today if the exact ordering is not met:

For example:  s0:c0,c6 is equal to s0:c6,c0

Enhance PSP/SCC to take into account logical equivalence of the SELinux level.

@childsb @pmorie @php-coder @openshift/sig-security

**Comment by php-coder** [comment]
Could you provide an use-case when "levels will be failed"? Where we're comparing SCCs by SELinux properties?

**Comment by pweil-** [comment]
I'll try to clarify

Currently the `SELinux.Level` field will fail if it has:

On the Pod: `s0:c6,c0`
On the SCC: `s0:c0,c6`

So the SCC strategy is doing a straight == comparison of the fields which doesn't take into account that the ordering of `c0` and `c6` shouldn't matter, the allowed categories are the same.

We should also take into account ranges which can be expressed with shorthand of `c0.c6`.

[The docs](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/SELinux_Users_and_Administrators_Guide/chap-Security-Enhanced_Linux-SELinux_Contexts.html)

```
level

The level is an attribute of MLS and MCS. An MLS range is a pair of levels, written as lowlevel-highlevel 
if the levels differ, or lowlevel if the levels are identical (s0-s0 is the same as s0). Each level is a 
sensitivity-category pair, with categories being optional. If there are categories, the level is written as 
sensitivity:category-set. If there are no categories, it is written as sensitivity.

If the category set is a contiguous series, it can be abbreviated. For example, c0.c3 is the same as 
c0,c1,c2,c3. The /etc/selinux/targeted/setrans.conf file maps levels (s0:c0) to human-readable form (that 
is CompanyConfidential). In Red Hat Enterprise Linux, targeted policy enforces MCS, and in MCS, there 
is just one sensitivity, s0. MCS in Red Hat Enterprise Linux supports 1024 different categories: c0 
through to c1023. s0-s0:c0.c1023 is sensitivity s0 and authorized for all categories.

MLS enforces the Bell-La Padula Mandatory Access Model, and is used in Labeled Security Protection 
Profile (LSPP) environments. To use MLS restrictions, install the selinux-policy-mls package, and 
configure MLS to be the default SELinux policy. The MLS policy shipped with Red Hat Enterprise Linux 
omits many program domains that were not part of the evaluated configuration, and therefore, MLS on a 
desktop workstation is unusable (no support for the X Window System); however, an MLS policy from 
the upstream SELinux Reference Policy can be built that includes all program domains. For more
 information on MLS configuration, see Section 4.12, “Multi-Level Security (MLS)”.
⁠```

**Comment by adelton** [comment]
@pweil-, could you please provide steps to reproduce, and point to the place in code where we should be testing for this?

Is normalizing the values a reasonable approach, or is something different needed?

**Comment by pweil-** [comment]
to reproduce define an SCC with a mustRunAs SELinux strategy and pod with selinux levels.  The values can look like:

> On the Pod: s0:c6,c0
On the SCC: s0:c0,c6

When you submit the pod for admission it will deny the request because the values are not strictly equal.

The issue in the code is in the mustRunAs SELinux strategy.  That is probably where I'd suggest doing a logical comparison rather than a hard equals

**Comment by simo5** [comment]
@rhatdan do you have sensible advice ^ ?

**Comment by rhatdan** [comment]
I would validate the labels, although you could use the kernel for this if you want.  But the main rule I would worry about is

s0:c3,c2 == s0:c2,c3
security_check_context() Would check the validity but you would have to hard code it.

security_check_context("system_u:system_r:container_t:MCS")

**Comment by pweil-** [comment]
> s0:c3,c2 == s0:c2,c3

this is the one that bit us.  

Having a range check would be nice to have but I think it's less likely to cause an error in the real world.
