### ISSUE TITLE
oc get with --all-namespaces shows incorrect columns

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#15637]
When `oc get` is used for getting info about cluster-wide resources (`--all-namespaces`), `NAMESPACE` column is shown but because it always empty, the output is formatted incorrectly.

Reported by: @legionus 

##### Version
```
oc v3.6.0-rc.0+dc4d146-490-dirty
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

Server https://10.34.129.200:8443
openshift v3.6.0-rc.0+dc4d146-490-dirty
kubernetes v1.7.0+695f48a16f
```

##### Steps To Reproduce
1. `oc cluster up`
2. `oc login -u system:admin`
3. `oc get users --all-namespaces`

##### Current Result
```
NAMESPACE   NAME                                   UID       FULL NAME   IDENTITIES
developer   e5593048-792c-11e7-823b-507b9d2b16b9             anypassword:developer
```

##### Expected Result
```
NAMESPACE   NAME         UID                                     FULL NAME   IDENTITIES
            developer    e5593048-792c-11e7-823b-507b9d2b16b9                anypassword:developer
```

##### Additional Information
This isn't specific to `users` resource but also for scc (`oc get scc --all-namespaces`), images (`oc get images --all-namespaces`) and perhaps others.

**Comment by wanghaoran1988** [comment]
/assign
Seems the clustered scope resource have this kind problem, I will take a look

**Comment by wanghaoran1988** [comment]
This issue has fixed by tablePrinter upstream, I guess a rebase can fix this.

**Comment by php-coder** [comment]
Could you post a link to the upstream PR at least?

**Comment by wanghaoran1988** [comment]
1. We are fill out the empty column with empty spaces here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/humanreadable.go#L475-L478
2. And this is the some prs switch to use table printers
https://github.com/kubernetes/kubernetes/pull/49700
https://github.com/kubernetes/kubernetes/pull/49359

**Comment by php-coder** [comment]
Here is a bug in K8s about completely removing this field for cluster scoped resources: https://github.com/kubernetes/kubernetes/issues/53767
