### ISSUE TITLE
softlinks stopped to work with hostPath (hostmount) in 3.6.0

### ISSUE THREAD

**Issue by oprudkyi** [openshift/origin#15647]
after switching to 3.6.0 from 1.5.1.  softlinks (created via ln -s)  stopped to work 

i.e. for deployment config like 
```
      volumes:
        - hostPath:
            path: /some/path/to/softlink 
```
it results in deployment error 
Error : lstat /some/path/to/softlink:  no such file or directory

though longer path , i.e. /some/path/to/softlink/subdir - works 

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.16.0.2:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. have in deployment config 
```
      volumes:
        - hostPath:
            path: /some/path/to/softlink 
```

##### Current Result
Error : lstat /some/path/to/softlink:  no such file or directory

##### Expected Result
successful deployment

**Comment by pweil-** [comment]
@smarterclayton FYI, looks like this could be a regression

@childsb if this is a regression let's make sure that QA has a test case for this scenario

**Comment by php-coder** [comment]
@openshift/sig-storage

**Comment by jsafrane** [comment]
/reopen
/remove-lifecycle rotten
/lifecycle frozen

It takes a long time, however we're fixing this.
