### ISSUE TITLE
redeploing of default router fails with PodFitsHostPorts

### ISSUE THREAD

**Issue by oprudkyi** [openshift/origin#15646]
when openshift is run via 'oc cluster up'  and router is deployed (manually or on config change) it fails to run till restart of openshift with error

No nodes are available that match all of the following predicates:: PodFitsHostPorts (1).

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.16.0.2:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. start via 'oc cluster up --use-existing-config'
2. go to router deployment (in 'default' project ) /console/project/default/browse/dc/router?tab=history  and press 'Deploy' 

##### Current Result
router is not started, there is error 
No nodes are available that match all of the following predicates:: PodFitsHostPorts (1).

##### Expected Result
router deployed 

p.s. this only related to 3.6.0, 1.5.1 works fine

**Comment by csrwng** [comment]
It seems that the router is getting deployed with the wrong strategy. If using a rolling type of deployment the old and new deployment would not be able to coexist, given that they both use the same host ports. When deployed in a single node cluster, it should be a recreate type of deployment.

**Comment by mfojtik** [comment]
@oprudkyi can you double check the deployment strategy for the router?

**Comment by mfojtik** [comment]
@csrwng seems like the router is using rolling strategy by default, is this something we want to change for oc cluster up?

**Comment by csrwng** [comment]
@mfojtik yes and I would think you'd want to change it for any regular deployment as well where there is only one infra node.

**Comment by mfojtik** [comment]
@csrwng detecting just 1 infra node will be hard, guess something we can do in ansible.

**Comment by csrwng** [comment]
@mfojtik what's the use case for a rolling deployment? Do you assume that an external load balancer will redirect router traffic to the new node where it's deployed? (Assuming you are using host ports which is the default)

**Comment by lcarva** [comment]
I saw this after upgrading from 3.5 to 3.6 in a rhel 7.4 vagrant box. Changing the deployment strategy from `Rolling` to `Recreate` in deployment config for router fixed the issue.

```
oc -n default edit dc router
oc -n default rollout latest router
```

**Comment by kargakis** [comment]
Rolling deployment should also work if you use percentages (the defaults are 25%-25%).
