### ISSUE TITLE
disable the creation of the Jenkins DeploymentConfig if a pipeline BuildConfig exists via some other means?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#15653]
Right now on OpenShift.io we create a Jenkins Service in the users namespace `${ID}` to prevent OpenShift creating a Jenkins DC in the `${ID}` namespace if the user creates a pipeline BuildConfig there. Instead we provision a Jenkins in the `${ID}-jenkins` namespace with different quotas etc.

The problem is users can delete the Jenkins service which then forces OSO to create another Jenkins DC in the `${ID}` namespace.

So we'd like another way to disable this behaviour such that users can't accidentally disable it. Users who opt out of openshift.io should get this default behaviour; so it needs to be some user specific marker that users can't remove but that OSIO can.

We were wondering if we could/should use an annotation on the Project to denote whether or not OSO should auto-provision a Jenkins DC?

OOTB users cannot annotate a Project due to security; however we should hopefully be able to do this using the OpenShift.io account?

**Comment by bparees** [comment]
@jstrachan we can take this as an RFE but my understanding is today you have your own cluster so why not just disable autoprovisioning in the cluster entirely?

https://docs.openshift.org/latest/install_config/configuring_pipeline_execution.html#overview

**Comment by jstrachan** [comment]
@bparees good point ;) lemme check if we can do that

**Comment by bparees** [comment]
converted this to a trello card: https://trello.com/c/6NPQRyHl
