### ISSUE TITLE
Build step broken in some postsubmits

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#15650]
Specifically:
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_templates

For example:
```
One or more required Docker images are not available:
                   openshift/origin-deployer:586257a,
                   openshift/origin-docker-registry:586257a,
                   openshift/origin-haproxy-router:586257a,
                   openshift/origin-pod:586257a
               Configured registries: docker.io
```

@bparees seems that these jobs depend on push_origin_release to finish first? push_origin_release pushes only to latest tag though.

cc: @smarterclayton @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@kargakis is this with the new Origin sync in there? Yeah, they were meant to run from a built AMI and not from master commit post-submit as that was going to save us time. Those jobs need to start from the base AMI and build all of Origin

**Comment by kargakis** [comment]
Yeah, I had already pushed the new sync stuff.

**Comment by kargakis** [comment]
> @kargakis is this with the new Origin sync in there? Yeah, they were meant to run from a built AMI and not from master commit post-submit as that was going to save us time. Those jobs need to start from the base AMI and build all of Origin

Ok, will remove them from postsubmits. SGTY?

**Comment by bparees** [comment]
the templates job is going to go away since that's now running on all merges anyway.

as for the other 2, running them post-submit would be nice, what do i need to do to make that happen?  but i'm ok w/ removing them for now to get things clean again.

**Comment by stevekuznetsov** [comment]
@kargakis let's move everything that currently is based off of the build AMI stage out of postsubmit and keep running them only daily
