### ISSUE TITLE
Containerized install with system containers fails to start containers with local (empty-dir) volumes

### ISSUE THREAD

**Issue by cldmnky** [openshift/origin#15668]
We have installed Origin on CentOS Atomic hosts using system containers. Deploying the registry using local volumes (empty-dir)  fails due to missing devices in /dev inside the system container.

During the pod setup on the node, origin-node tries to set quota using xfs_quota:
```Aug 08 07:56:30 ip-10-20-5-186.eu-central-1.compute.internal origin-node[38442]: I0808 07:56:30.791785   38453 quota.go:94] Ran: xfs_quota [-x -c limit -g bsoft=536870912 bhard=536870912 1000040000 /dev/xvdc]```

This fails due to missing block devices in the system container:
``` Aug 08 07:56:46 ip-10-20-5-186.eu-central-1.compute.internal origin-node[38442]: E0808 07:56:46.740857   38453 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/empty-dir/16b66913-7c0f-11e7-b49f-0ad123927c77-registry-storage\" (\"16b66913-7c0f-11e7-b49f-0ad123927c77\")" failed. No retries permitted until 2017-08-08 07:57:02.740832915 +0000 UTC (durationBeforeRetry 16s). Error: MountVolume.SetUp failed for volume "kubernetes.io/empty-dir/16b66913-7c0f-11e7-b49f-0ad123927c77-registry-storage" (spec.Name: "registry-storage") pod "16b66913-7c0f-11e7-b49f-0ad123927c77" (UID: "16b66913-7c0f-11e7-b49f-0ad123927c77") with: error applying quota: xfs_quota: cannot setup path for mount /dev/xvdc: No such file or directory ``` 

The `/dev/xvdc` is mounted on ` /var/lib/origin/openshift.local.volumes type xfs (rw,relatime,seclabel,attr2,inode64,grpquota)`  as volume directory in node-config: `volumeDirectory: /var/lib/origin/openshift.local.volumes` 

Adding a bind mount for the local volume device in the runc's config.json solves it:
```...
        {
            "type": "bind",
            "source": "/dev/xvdc",
            "destination": "/dev/xvdc",
            "options": [
                "rbind",
                "rw",
                "mode=755"
            ]
        },
```

##### Version
```
[ec2-user@ip-10-20-4-73 ~]$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://internal-openshift-master.test.xxxxx.xxx:443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
``` 

##### Steps To Reproduce
1. Install a Origin cluster on AWS using `openshift-ansible-contrib:reference-architecture/aws-ansible/ose-on-aws.py`, containerized using system containers on a Atomic host.
2. Try to deploy the router using local volumes.

##### Current Result
Pods fail to start due to volume setup of the quota

##### Expected Result
Pods should start with quota set on the local volume

**Comment by cldmnky** [comment]
I took the liberty to submit a PR to solve this: https://github.com/openshift/origin/pull/15693

**Comment by giuseppe** [comment]
https://github.com/openshift/origin/pull/15693 is merged, can we close this issue?

**Comment by cldmnky** [comment]
The merged PR solves the issue, so yes.
