### ISSUE TITLE
Versions in Swagger API "x-kubernetes-group-version-kind" all reporting as "latest"

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#15666]
Since the 1.7 rebase, the version information is missing under "x-kubernetes-group-version-kind" under api/swagger-spec/openshift-openapi-spec.json - instead of reporting things like "version": "v1" (or whatever), everything is coming through as "version": "latest"

**Comment by jim-minter** [comment]
@deads2k or @sttts would you be able to take a look at this?

**Comment by deads2k** [comment]
> @deads2k or @sttts would you be able to take a look at this?

Is it blocking something?  I took a guess at a p2 assuming that its not.

**Comment by jim-minter** [comment]
It'd be handy if it were fixed as it causes the api documentation autogeneration that I'm working on to come out wrong.
