### ISSUE TITLE
Adding hostPath Volume Halts Deployment Completely

### ISSUE THREAD

**Issue by chenchik** [openshift/origin#15678]
I'm trying to get a JDBC Kafka Connect connector working with Openshift. I am using the "all in one" vagrant VM to run Openshift.

I have shhed into the all in one VM and have successfully ran the container I wanted to run using strictly docker. This was the command I used:

```
docker run -d \
  --name=j1 \
  --net=host \
  -e CONNECT_BOOTSTRAP_SERVERS=*******:9092 \
  -e CONNECT_REST_PORT=28083 \
  -e CONNECT_GROUP_ID="jdbc-group" \
  -e CONNECT_CONFIG_STORAGE_TOPIC="connect-configs" \
  -e CONNECT_OFFSET_STORAGE_TOPIC="connect-offsets" \
  -e CONNECT_STATUS_STORAGE_TOPIC="connect-status" \
  -e CONNECT_KEY_CONVERTER="io.confluent.connect.avro.AvroConverter" \
  -e CONNECT_VALUE_CONVERTER="io.confluent.connect.avro.AvroConverter" \
-e CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL="http://****:8081" \
  -e CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL="http://****:8081" \
  -e CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
  -e CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
  -e CONNECT_LOG4J_ROOT_LOGLEVEL=DEBUG \
  -e CONNECT_REST_ADVERTISED_HOST_NAME="localhost" \
  -v /tmp/quickstart/file:/tmp/quickstart \
  -v /tmp/quickstart/jars:/etc/kafka-connect/jars \
  chenchik/custom-connect-hdfs:with-servers
```

I can replicate creating the pod with all the environment variables set, but once I try to bind mount the required volumes, I can't update my pod as it halts in a state of creating the next pod and then times out. This is what my `oc get pods` looks like:

```
c55-4-tvi7l               1/1       Running   0          12m
c55-5-deploy              1/1       Running   0          9m
```

I need to be able to deploy the container with the needed volumes in order to boot up the Kafka Connect connector. The jar file can be obtained by running the following command (it will end up in /tmp/quickstart/jars):

`curl -k -SL "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.39.tar.gz" | tar -xzf - -C /tmp/quickstart/jars --strip-components=1 mysql-connector-java-5.1.39/mysql-connector-java-5.1.39-bin.jar`

I'm doing the openshift equivalent of docker's "-v" `docker run` option in this way:

`oc volume dc/<my deployment config> --add --overwrite --name="<name of volume that is reponsible for the path /etc/kafka-connect/jars>" --type="hostPath" --path="/tmp/quickstart/jars" --mount-path="/etc/kafka-connect/jars"
`

Should this work?

##### Version
oc v1.1.1
kubernetes v1.1.0-origin-1107-g4c8e6f4

##### Steps To Reproduce
`oc new-app chenchik/custom-connect-hdfs:with-servers -e CONNECT_BOOTSTRAP_SERVERS=****:9092 -e CONNECT_REST_PORT=8083 -e CONNECT_GROUP_ID="jdbc-group" -e CONNECT_CONFIG_STORAGE_TOPIC="connect-configs" -e CONNECT_OFFSET_STORAGE_TOPIC="connect-offsets" -e CONNECT_STATUS_STORAGE_TOPIC="connect-status"  -e CONNECT_KEY_CONVERTER="io.confluent.connect.avro.AvroConverter" -e CONNECT_VALUE_CONVERTER="io.confluent.connect.avro.AvroConverter" -e CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL="http://****:8081" -e CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL="http://****:8081" -e CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" -e CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter" -e CONNECT_LOG4J_ROOT_LOGLEVEL=INFO -e CONNECT_REST_ADVERTISED_HOST_NAME="localhost3" --name=duck3`

`oc volume dc/duck3 --all`

If there’s one with a path of /tmp/quickstart/jars, update that volume

`oc volume dc/duck3 --add --overwrite --name="duck3-volume-1" --type="hostPath" --path="/tmp/quickstart/jars" --mount-path="/etc/kafka-connect/jars"`

##### Current Result
Stalls on the deployment of the pod.

##### Expected Result
Deploys pod.

##### Additional Information
The link below is where I got my information about the docker version of deploying the Kafka Connect JDBC connector:

http://docs.confluent.io/current/cp-docker-images/docs/tutorials/connect-avro-jdbc.html

**Comment by php-coder** [comment]
Do you see any errors in `oc get events`, `oc `status` output? I'm not sure but probably you may have problems because the usage of hostPath volumes have to be allowed by SCC. If it's the case then you should grant access to `hostaccess` SCC to the appropriate service account.

**Comment by tnozicka** [comment]
closing this as the requested info wasn't provided in 2 months
