### ISSUE TITLE
`oc annotate` with `--overwrite` flag doesn't update resource version

### ISSUE THREAD

**Issue by vvk** [openshift/origin#15698]
When using command `oc annotate namespace` with `--overwrite` flag, `resourceVersion` is not updated.

##### Version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server XXX
openshift v1.3.3
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Run `oc get namespace <namespace-name> -o json`
2. Remember `resourceVersion` value.
3. Run `oc annotate namespace <namespace-name> my_annotation=some_value --overwrite=true`
4. Run `oc get namespace <namespace-name> -o json`
5. Look at `resourceVersion` value.

##### Current Result
`resourceVersion` is not updated.
##### Expected Result
`resourceVersion` is updated.

**Comment by juanvallejo** [comment]
@vvk I am unable to replicate this (client / server versions at 3.7)

Any chance you could try with a newer version of oc? (though I suspect this might be happening due to using `oc` against an older cluster)

**Comment by juanvallejo** [comment]
Closing. Please re-open if this is still able to be replicated with a newer client against a cluster with a +-1 version skew
