### ISSUE TITLE
Why does it take so long to tell a client that a resource does not exist?

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#15699]
```
$ time oc get pods >/dev/null

real	0m0.514s
user	0m0.223s
sys	0m0.028s
```

```
$ time oc get pdods >/dev/null
the server doesn't have a resource type "pdods"

real	0m1.890s
user	0m0.218s
sys	0m0.036s
```

@smarterclayton @deads2k @sttts

**Comment by sttts** [comment]
It's redownloading discovery information on cache miss in the rest mapper. That download is apigroup by apigroup, in serial (yes, that's not very clever).

**Comment by smarterclayton** [comment]
I have an issue open upstream on this, and it probably shouldn't re download if the cache is relatively fresh.  It's a big usability thing.

**Comment by sttts** [comment]
What about etags? We got that for openapi. Would maybe make a difference here as well, especially if we combine all the downloads into one.

**Comment by smarterclayton** [comment]
we got it and reverted it because it was horribly broken.  so we don't have it yet :)

**Comment by sttts** [comment]
if only broken by implementation, there is hope.

**Comment by stevekuznetsov** [comment]
@sttts did this get fixed upstream?

**Comment by sttts** [comment]
> @sttts did this get fixed upstream?

Nope, we haven't done anything about this as far as I know. >2s is quite a lot for an interactive command. Added a trello card to the master team: https://trello.com/c/l4MgfY3S/1162-implement-etags-for-discovery-to-avoid-2s-for-oc-get-ppods

**Comment by stevekuznetsov** [comment]
/close
Trello card is a better tracker
