### ISSUE TITLE
Flaky container create/pod start behavior

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15695]
I'm seeing a lot of test failures due to pods/containers that fail to start, e.g.:

```
ug  9 01:34:53.866: INFO: Error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc [oc logs --config=/tmp/extended-test-jenkins-plugin-hgf4t-4f805-user.kubeconfig --namespace=extended-test-jenkins-plugin-hgf4t-4f805-jenkins pod/jenkins-1-deploy] []   Error from server (BadRequest): container "deployment" in pod "jenkins-1-deploy" is waiting to start: ContainerCreating
 Error from server (BadRequest): container "deployment" in pod "jenkins-1-deploy" is waiting to start: ContainerCreating
 [] <nil> 0xc420b1f6e0 exit status 1 <nil> <nil> true [0xc420844040 0xc420844068 0xc420844068] [0xc420844040 0xc420844068] [0xc420844048 0xc420844060] [0x14741c0 0x14742c0] 0xc421916840 <nil>}:
Error from server (BadRequest): container "deployment" in pod "jenkins-1-deploy" is waiting to start: ContainerCreating
Error retrieving logs for pod "jenkins-1-deploy": exit status 1
```

as seen in:

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/168/

Here we see the current time and the fact that the pod was created much earlier but is still pending:
```
Aug  9 01:34:53.485: INFO: Running 'oc describe --config=/tmp/extended-test-jenkins-plugin-hgf4t-4f805-user.kubeconfig --namespace=extended-test-jenkins-plugin-hgf4t-4f805-jenkins pod/jenkins-1-deploy'
Describing pod "jenkins-1-deploy"
Name:		jenkins-1-deploy
Namespace:	extended-test-jenkins-plugin-hgf4t-4f805-jenkins
Node:		ip-172-18-2-2.ec2.internal/172.18.2.2
Start Time:	Wed, 09 Aug 2017 01:19:53 -0400
Labels:		openshift.io/deployer-pod-for.name=jenkins-1
Annotations:	openshift.io/deployment.name=jenkins-1
		openshift.io/scc=restricted
Status:		Pending
```

due to it being in container create:

```
Containers:
  deployment:
    Container ID:	
    Image:		openshift/origin-deployer:01e5a1b
    Image ID:		
    Port:		<none>
    State:		Waiting
      Reason:		ContainerCreating
```

**Comment by bparees** [comment]
@derekwaynecarr I don't know if the k8s team should also be involved in this or not, so just ccing you for now.

**Comment by bparees** [comment]
more of the same:
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/173/testReport/junit/(root)/Extended/_Conformance__image_ecosystem__mongodb__Slow__openshift_mongodb_replication__with_statefulset__creating_from_a_template_should_instantiate_the_template/

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/170/testReport/junit/(root)/Extended/_builds__Slow__openshift_pipeline_build_Pipeline_with_env_vars_should_build_and_complete_successfully/

**Comment by jwhonce** [comment]
@bparees I assume this VM is using the m4.xlarge default of a GP2 volume.  Is it possible to run sar on the VM during the tests and record the results in the S3 artifacts?

Additionally, the CloudWatch/BurstBalance data would be great to have.  I do not know how to capture that data for these throw away VM's.

**Comment by bparees** [comment]
> @bparees I assume this VM is using the m4.xlarge default of a GP2 volume. 

it's whatever our CI infrastructure deploys by default, so probably?

>  Is it possible to run sar on the VM during the tests and record the results in the S3 artifacts?

not sure what sar is.  Does it need to be run before things start or after they fail or what?  We can certainly update the CI jobs to run additional tools/collect additional information.

Not sure about the cloudwatch data either, @stevekuznetsov might know if that's something we have a way to gather.

**Comment by stevekuznetsov** [comment]
There's a framework for running `sar` and posing PDFs output from that ... let me dig into why it's not running for this

**Comment by stevekuznetsov** [comment]
@bparees @jwhonce  could you add a call to [`os::log::system::start`](https://github.com/openshift/origin/blob/master/hack/lib/log/system.sh#L207) in the appropriate test scripts?

**Comment by bparees** [comment]
@stevekuznetsov looks like we already do:
https://github.com/openshift/origin/blob/master/test/extended/core.sh#L8
https://github.com/openshift/origin/blob/master/test/extended/setup.sh#L81

**Comment by stevekuznetsov** [comment]
Bail out early on `$TEST_ONLY=1` https://github.com/openshift/origin/blob/master/test/extended/setup.sh#L54

**Comment by bparees** [comment]
so is it safe to move the call above that bail out?

**Comment by stevekuznetsov** [comment]
I don't see why not

**Comment by stevekuznetsov** [comment]
Wait

**Comment by stevekuznetsov** [comment]
You may need to mess with the placement of `os::util::environment::setup_all_server_vars` or at least determine which vars the logger needs and ensure they are available

**Comment by bparees** [comment]
This continue to be a frequent flake for us, most recently seen here:

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/239/testReport/junit/(root)/Extended/_image_ecosystem__Slow__openshift_images_should_be_SCL_enabled_test_context_using_the_SCL_in_s2i_images__openshift_python_33_centos7__should_be_SCL_enabled__Suite_openshift_/

This container sat in containercreate for 10 minutes:
```
Oct  5 04:43:27.314: INFO: Describing pod "test-pod-a1d676d7-a985-11e7-b998-0ea13e4a2248"
Name:		test-pod-a1d676d7-a985-11e7-b998-0ea13e4a2248
Namespace:	extended-test-s2i-usage-h4cr4-4ldm0
Node:		ip-172-18-5-81.ec2.internal/172.18.5.81
Start Time:	Thu, 05 Oct 2017 04:33:35 +0000
Labels:		name=test-pod-a1d676d7-a985-11e7-b998-0ea13e4a2248
Annotations:	openshift.io/scc=restricted
Status:		Pending
IP:		
Containers:
  test:
    Container ID:	
    Image:		openshift/python-33-centos7
    Image ID:		
    Port:		<none>
    Command:
      /bin/bash
      -c
      python --version
    State:		Waiting
      Reason:		ContainerCreating
```

as did this one:
```
Oct  5 04:43:28.736: INFO: Describing pod "test-pod-a2addba0-a985-11e7-b7f2-0ea13e4a2248"
Name:		test-pod-a2addba0-a985-11e7-b7f2-0ea13e4a2248
Namespace:	extended-test-s2i-usage-3l0q9-8nnr5
Node:		ip-172-18-5-81.ec2.internal/172.18.5.81
Start Time:	Thu, 05 Oct 2017 04:33:37 +0000
Labels:		name=test-pod-a2addba0-a985-11e7-b7f2-0ea13e4a2248
Annotations:	openshift.io/scc=restricted
Status:		Pending
IP:		
Containers:
  test:
    Container ID:	
    Image:		openshift/ruby-22-centos7
    Image ID:		
    Port:		<none>
    Command:
      /bin/bash
      -c
      ruby --version
    State:		Waiting
      Reason:		ContainerCreating
```

(note that although it's from a different test, the timestamp is similar, so perhaps an exhausted IOPS issue?)

also this one:
```
Oct  5 04:43:52.543: INFO: Describing pod "django-example-1-deploy"
Name:		django-example-1-deploy
Namespace:	extended-test-django-repo-test-h588p-8lc2z
Node:		ip-172-18-5-81.ec2.internal/172.18.5.81
Start Time:	Thu, 05 Oct 2017 04:33:08 +0000
Labels:		openshift.io/deployer-pod-for.name=django-example-1
Annotations:	openshift.io/deployment.name=django-example-1
		openshift.io/scc=restricted
Status:		Pending
IP:		
Containers:
  deployment:
    Container ID:	
    Image:		openshift/origin-deployer:5d7f1b8
    Image ID:		
    Port:		<none>
    State:		Waiting
      Reason:		ContainerCreating
```

and this one:

```
Oct  5 04:43:07.237: INFO: Describing pod "jenkins-1-deploy"
Name:		jenkins-1-deploy
Namespace:	extended-test-jenkins-plugin-q4m1j-8wc6h-jenkins
Node:		ip-172-18-5-81.ec2.internal/172.18.5.81
Start Time:	Thu, 05 Oct 2017 04:33:15 +0000
Labels:		openshift.io/deployer-pod-for.name=jenkins-1
Annotations:	openshift.io/deployment.name=jenkins-1
		openshift.io/scc=restricted
Status:		Pending
IP:		
Containers:
  deployment:
    Container ID:	
    Image:		openshift/origin-deployer:5d7f1b8
    Image ID:		
    Port:		<none>
    State:		Waiting
      Reason:		ContainerCreating
```

**Comment by stevekuznetsov** [comment]
@bparees still an issue?

**Comment by bparees** [comment]
Haven't seen it recently.
/close
