### ISSUE TITLE
oc volume --add issues

### ISSUE THREAD

**Issue by fortinj66** [openshift/origin#15711]
I'm getting an error when I try to create a new volume via the CLI.  Here is the simplest xase pretty much right out of the examples:

```
 oc volume dc/category-menu-micro --add --mount-path=/home/appuser/logs_2
info: Generated volume name: volume-42v2d
error: deploymentconfigs/category-menu-micro map: map[] does not contain declared merge key: name

```

##### Version
[johnf@os-master-d01 scripts]$ oc version
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://os-master-d01:8443
openshift v1.5.1
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
```
 oc volume dc/category-menu-micro --add --mount-path=/home/appuser/logs_2
```
##### Current Result
```
info: Generated volume name: volume-42v2d
error: deploymentconfigs/category-menu-micro map: map[] does not contain declared merge key: name
```
##### Expected Result
successful creation of volume in the dc

##### Additional Information

I know parts are working correctly because if I give and existing volume I get this error:
```
oc volume dc/category-menu-micro --add --mount-path=/home/appuser/logs
info: Generated volume name: volume-gfvsp
error: deploymentconfigs/category-menu-micro volume mount '/home/appuser/logs' already exists for container 'category-menu-micro'
[johnf@os-master-d01 scripts]$
```

**Comment by fortinj66** [comment]
I figured out the issue and work-around.  
The dc was deploying from an image stream tag.  Adding a volume with this setting fails from the cli.  When I changed the dc to deploy from an image the volume was created properly from the cli...

Not sure if that is supposed to work that way or not...

**Comment by juanvallejo** [comment]
@fortinj66 
> The dc was deploying from an image stream tag. Adding a volume with this setting fails from the cli. When I changed the dc to deploy from an image the volume was created properly from the cli...

Are you still able to replicate this issue? Any chance you could try with a newer version of `oc` (3.6, 3.7)?
