### ISSUE TITLE
error: unable to recognize '...': no matches for monitoring.coreos.com/, Kind=Prometheus

### ISSUE THREAD

**Issue by objectiser** [openshift/origin#15724]
I have an [example](https://github.com/objectiser/opentracing-prometheus-example) that uses minishift (v1.2.0) with openshift v3.6.0-alpha.2 to deploy prometheus-operator. However when I update to openshift v3.6.0 I get:

> error: unable to recognize "https://raw.githubusercontent.com/objectiser/opentracing-prometheus-example/master/prometheus-kubernetes.yml": no matches for monitoring.coreos.com/, Kind=Prometheus

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.176:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. minishift start --openshift-version=v3.6.0
2. oc login -u system:admin
3. oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:myproject:default
4. oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:myproject:prometheus-operator
5. oc create -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/bundle.yaml
6. Wait for prometheus-operator to start
7. oc create -f https://raw.githubusercontent.com/objectiser/opentracing-prometheus-example/master/prometheus-kubernetes.yml

This final command works fine on v3.6.0-alpha.2 but not on v3.6.0

##### Current Result

service "prometheus" created
error: unable to recognize "https://raw.githubusercontent.com/objectiser/opentracing-prometheus-example/master/prometheus-kubernetes.yml": no matches for monitoring.coreos.com/, Kind=Prometheus

##### Expected Result

prometheus "prometheus" created
service "prometheus" created

##### Additional Information

[origin-get-all.zip](https://github.com/openshift/origin/files/1214473/origin-get-all.zip)

**Comment by pweil-** [comment]
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  version: v1.6.3
  resources:
    requests:
      memory: 400Mi
```

`monitoring.coreos.com/v1alpha1` is not an api group that OpenShift provides, it looks to be a coreos custom API.  An example of deploying prometheus as a pod in OpenShift can be found here: https://github.com/openshift/origin/tree/master/examples/prometheus

**Comment by objectiser** [comment]
@pweil- Hi Paul - was curious why this worked with v3.6.0-alpha.2?

The problem with the project you have referenced is that it does not automatically manage collection of the prometheus metrics from deployed services as they are deployed or scaled up.

**Comment by pweil-** [comment]
@objectiser without an api aggregator (ie something installed that was providing that API and registering it somehow) I'm not sure how it would've worked for you before.  I did a little bit of research and it appears this this is an API that coreos provides on top of Kube.  Their [Prometheus Operator](https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html) is what seems to provide this resource as a TPR so maybe that was installed before?

**Comment by objectiser** [comment]
@pweil- Before doing the steps to reproduce I always run `minishift delete` - so assume this would be a completely clean environment, followed by the steps I've listed above - and agree that neither yaml file contain any TPR definitions, so confused where these are being defined.

**Comment by pweil-** [comment]
@objectiser did a bit more digging and local testing on this one, sorry for the delay.  In 3.6 we found that using TPRs caused issues with existing endpoint when the TPR was removed.  There were also issues with process crashing.  Since OpenShift never officially supported TPRs the code that was causing issues was removed.

Additionally, they've been deprecated upstream in 1.7 and will be removed in 1.8 (beta features have a 1 release deprecation policy).  Apologies for the inconvenience.

**Comment by objectiser** [comment]
No problem - thanks for investigating, I'll look into alternatives.

**Comment by hurtauda** [comment]
Hello,

I am facing the same issue with openshift v3.6.1+008f2d5 .
@objectiser Have you found a solution to have the prometheus-operator (0.11.3) to run on this version / an alternative?

Rgds,
hurtauda

**Comment by objectiser** [comment]
@hurtauda No didn't find a solution, but someone I work with who is a prometheus committer, did some changes to remove coreos and achieve the same requirements directly with prometheus: https://github.com/objectiser/opentracing-prometheus-example/commits?author=krasi-georgiev
