### ISSUE TITLE
Correlation between ansible, branches and oc version

### ISSUE THREAD

**Issue by ksemaev** [openshift/origin#15729]
Can't find anywhere which version of what should I use. Where is a table which says that these versions of ansible works with these versions of openshift, which is installed from this branch?

Had lots of problems trying to install with ansible 2.3.1.0 from master branch which gave me oc v1.5.1 with broken metric and many other conflicts.

Please provide this information)

**Comment by sdodson** [comment]
Origin 3.6 RPMs have not been published which is causing some problems. But with regard to the branches does this PR help? https://github.com/openshift/origin/issues/15729

**Comment by ksemaev** [comment]
What PR are you talking about?) I just don't quite understand the dependencies between ansible and oc versions at this point. Many issue resolvers tell in this repo that you should use ansible version. For example (I know it is different repo, and installer has another different repo, but may be this concern any playbooks/branches/versions): https://github.com/openshift/origin-metrics/issues/331
"What version of ansible are you using?"

Or to install oc 1.5.x I can use 1.5 branch with any ansible version? There should be some info about it in documentation - but I just can't find it.

**Comment by sdodson** [comment]
Sorry I meant to link to https://github.com/openshift/openshift-ansible/pull/5057

**Comment by ksemaev** [comment]
Yep, thank you for the linking!
