### ISSUE TITLE
Double resources created with oc new-app when image stream is specified

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#15726]
This was performed on latest master (as of today):
```
$ oc version
oc v3.6.0-rc.0+8d96d48-566
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

Server https://localhost:8443
openshift v3.6.0-rc.0+8d96d48-566
kubernetes v1.7.0+695f48a16f
```

##### Steps To Reproduce
1. `oc import-image hello --from=docker.io/openshift/hello-openshift --confirm` - creates an image stream
2. `oc new-app hello --image-stream=hello` - this will create *two* identical DC and SVC

##### Current Result
```
$ oc new-app hello --image-stream=hello
--> Found image 8757ed3 (15 hours old) in image stream "test/hello" under tag "latest" for "hello"

    * This image will be deployed in deployment config "hello"
    * Ports 8080/tcp, 8888/tcp will be load balanced by service "hello"
      * Other containers can access this service through the hostname "hello"
    * WARNING: Image "test/hello:latest" runs as the 'root' user which may not be permitted by your cluster administrator

--> Found image 8757ed3 (15 hours old) in image stream "test/hello" under tag "latest" for "hello"

    * This image will be deployed in deployment config "hello-1"
    * Ports 8080/tcp, 8888/tcp will be load balanced by service "hello-1"
      * Other containers can access this service through the hostname "hello-1"
    * WARNING: Image "test/hello:latest" runs as the 'root' user which may not be permitted by your cluster administrator

--> Creating resources ...
    deploymentconfig "hello" created    <--------------------
    deploymentconfig "hello-1" created  <--------------------
    service "hello" created
    service "hello-1" created
--> Success
    Run 'oc status' to view your app.
```
##### Expected Result
Only one DC is created.

**Comment by bparees** [comment]
you asked for two things, you got two things, what's the bug?

you told new-app:

1) figure out what this "hello" thing is and create resources for it.  it figured out it's an imagestream and created resources for it.
2) please create resources for this other thing named hello, i'm telling you explicitly it's an image-stream.  It created resources for it.

if you only want one, either run:

```
$ oc new-app --image-stream=hello
```
or

```
$ oc new-app hello
```

**Comment by soltysh** [comment]
Oh, sorry for the misunderstanding. You're right I've assumed `hello` after `oc new-app` is the name whereas I should've used `--name` flag to force a specific name for generated artifacts. I must have messed it with `oc run` which works that way. Thanks!
