### ISSUE TITLE
"invalid memory address or nil pointer dereference" when ListClusterPolicyBindings returns an error

### ISSUE THREAD

**Issue by simo5** [openshift/origin#15747]
A panic happens in some tests when ListClusterPolicyBindings() returns an error when called by ListPolicyBindings()

Triggered by PR #15605 

##### Version
Current master tree

The issue is caused by incorrect error handling

**Comment by smarterclayton** [comment]
Testing this out, I may just cherrypick it into my branch and let it sit for a while since repo may be annoying.
