### ISSUE TITLE
SELinux relabeling when using subPath

### ISSUE THREAD

**Issue by dmytroleonenko** [openshift/origin#15750]
#### Description
After upgrading from 1.5.1 -> 3.6.0 (using openshift-ansible-3.6.173.0.5-5/playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml playbook)  all the ConfigMap files mounted using subPath are non-readable: Permission denied. It looks related to [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1475137). Not sure though because it said to be related to 1.5 (3.5) rather than to 3.6.

Now my configMaps' files look like this:
```
[root@ip-10-216-10-80 ~]# ls -laZ /proc/87199/root/opt/zeppelin/conf/
drwxr-xr-x. centos centos system_u:object_r:svirt_sandbox_file_t:s0:c50,c995 .
drwxr-sr-x. centos centos system_u:object_r:svirt_sandbox_file_t:s0:c50,c995 ..
-rw-r--r--. centos centos system_u:object_r:svirt_sandbox_file_t:s0:c50,c995 configuration.xsl
-rw-r--r--. centos centos system_u:object_r:svirt_sandbox_file_t:s0:c50,c995 interpreter.json
-rw-r--r--. centos centos system_u:object_r:svirt_sandbox_file_t:s0:c50,c995 interpreter-list
-rw-r--r--. centos centos system_u:object_r:svirt_sandbox_file_t:s0:c50,c995 log4j.properties
-rw-r--r--. root   centos system_u:object_r:var_lib_t:s0   shiro.ini
```

listing from actual worker instance running the pod.
pid 87199 is one of pids inside the pod. If configMap is mounted into a directory as a whole it gets relabeled properly. Just not the case with the individually mounted files.

```
$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://internal-OpenshiftWebInternal-1094922621.us-east-1.elb.amazonaws.com:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

**Comment by dmytroleonenko** [comment]
```# setenforce 0``` as a temporary solution. Otherwise, everything is broken badly

**Comment by wongma7** [comment]
see also https://bugzilla.redhat.com/show_bug.cgi?id=1481617

**Comment by adelton** [comment]
> # setenforce 0 as a temporary solution. Otherwise, everything is broken badly

Another workaround, mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1481617#c1, is to use `..data/` in the `subPath`.

**Comment by adelton** [comment]
@childsb, @pweil-, given this looks like an issue in docker which does not follow symlinks, what does this mean for tracking of this Origin issue?

**Comment by adelton** [comment]
The upstream docker (moby) PR https://github.com/moby/moby/pull/34792 has been merged.

**Comment by adelton** [comment]
A RHEL Extras `docker` build `docker-1.12.6-57.git85d7426.el7` fixes the problem. This is some newer build will be available in 7.4 updates.

**Comment by smarterclayton** [comment]
Given that we're waiting on a CentOS downstream I'm going to move this to P2.

**Comment by smarterclayton** [comment]
@dmytroleonenko Please close when you confirm this is fixed.
