### ISSUE TITLE
It should be possible to specify discontiguous UID ranges for PSP and SCC

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15775]
The `openshift.io/sa.scc.uid-range` should allow supporting multiple uid-ranges (similar to supplemental groups) so that a set of separate blocks can be used.  For example, `1,0,10000-11000`.  The first value should be the default.  Allows applications to get flexibility about UIDs they can use without having to create tons of SCCs.

@openshift/sig-security

**Comment by smarterclayton** [comment]
I think there's an old issue on this but I can't find it.

**Comment by simo5** [comment]
@php-coder can you look into this one ?

**Comment by pweil-** [comment]
duplicate: https://github.com/openshift/origin/issues/7014
