### ISSUE TITLE
oc rollout latest misses --follow

### ISSUE THREAD

**Issue by tobru** [openshift/origin#15777]
When running `oc deploy mydc --latest --follow` I get the hint `Flag --latest has been deprecated, use 'oc rollout latest' instead`. Looking at `oc rollout latest -h` reveals that there is no option `--follow`. Either this option should be added to `oc rollout latest` or the hint removed from `oc deploy`.

##### Version
```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://console.appuio.ch:443
openshift v3.5.5.31
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. Run `oc deploy mydc --latest --follow`
2. Read `Flag --latest has been deprecated, use 'oc rollout latest' instead`
3. Check `oc rollout latest -h`
4. Notice that there is no `--follow` flag

##### Current Result

No `--follow` flag available for `oc rollout latest`

##### Expected Result

`--follow` flag available for `oc rollout latest`

**Comment by mfojtik** [comment]
@kargakis FYI

I think we decided to not implement follow logic into rollout latest, but instead to use `oc rollout status`. The `--follow` was always great source of bugs and all sort of problems with dropped watches/etc.
