### ISSUE TITLE
Integration tests failin release-3.6 branch

### ISSUE THREAD

**Issue by simo5** [openshift/origin#15771]
When integration tests are run they fail in TestRouter* tests with the following error:
```--- FAIL: TestRouter (0.02s)
	router_test.go:75: Error starting container openshift/origin-haproxy-router : no such image
```

This is blocking merging to the release-3.6 branch.
See failed test run here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/5915/

**Comment by deads2k** [comment]
appears fixed.
