### ISSUE TITLE
oc new-app -f ... -o yaml is broken

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15783]
```
$ oc new-app -f examples/prometheus/prometheus.yaml -o yaml
error: extensions.Deployment is not suitable for converting to ""
```

**Comment by smarterclayton** [comment]
@fabianofranz @mfojtik just noticed this is broken in master - this is a high priority because we may have regressed automation around new-app (and potentially in 3.6 as well)

**Comment by csrwng** [comment]
@smarterclayton it doesn't look like this is a regression. It's broken in 3.6.0 and 3.5.1 ... the issue is the Deployment type in the prometheus template.

**Comment by csrwng** [comment]
@fabianofranz the code that's broken is the common printer code, which I think you own:
https://github.com/openshift/origin/blob/master/pkg/cmd/util/cmd.go#L124

That fails when called with a Deployment object and actualOutputVersion is blank("")

**Comment by smarterclayton** [comment]
Dropping priority slightly
