### ISSUE TITLE
flake: Deployment hook test fails with retry 2 instead of retry 1

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15790]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/4202/testReport/junit/(root)/Extended/deploymentconfigs_with_failing_hook__Conformance__should_get_all_logs_from_retried_hooks/

```
Extended.deploymentconfigs with failing hook [Conformance] should get all logs from retried hooks

/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:734
Expected
    <string>: --> pre: Running hook pod ...
    pre hook logs
    --> pre: Retrying hook pod (retry #2)
    pre hook logs
to contain substring
    <string>: --> pre: Retrying hook pod (retry #1)
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:733
```

**Comment by tnozicka** [comment]
@mfojtik do we have some common tracking issue for journald failures?

Lowering to P2 since it doesn't seem to repeat and this is long standing issue with journald in our tests.

**Comment by smarterclayton** [comment]
We do, it's p0 and someone needs to move it forward :)

On Aug 21, 2017, at 3:29 AM, Tomáš Nožička <notifications@github.com> wrote:

@mfojtik <https://github.com/mfojtik> do we have some common tracking issue
for journald failures?

Lowering to P2 since it doesn't seem to repeat and this is long standing
issue with journald in our tests.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15790#issuecomment-323667638>,
or mute the thread

**Comment by mfojtik** [comment]
cc @soltysh

**Comment by tnozicka** [comment]
found it: https://github.com/openshift/origin/issues/14785

**Comment by tnozicka** [comment]
closing this one as we track the journald issue in https://github.com/openshift/origin/issues/14785 and it seem to be ok with the increased limits in https://github.com/openshift/openshift-ansible/pull/3753
