### ISSUE TITLE
persistent-volume-binder needs to use upstream init

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15812]
`kube-controller-manager` has the idea of init functions.  We've been able to collapse onto almost all of them, but we still have a custom function for enabling the `persistentvolume-binder`.  This causes us to slip against the upstream during rebases.

Ideally we're able to use the normal controller initializer.  See https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/master/controller/config.go#L21, https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/master/controller/config.go#L30-L33, and https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/master/controller/volumes.go for examples

**Comment by deads2k** [comment]
@eparis this is what's leading to our slips and links to the pattern we use for the "normal" upstream integration.

**Comment by eparis** [comment]
https://trello.com/c/EvdONcue

**Comment by jsafrane** [comment]
If I understand it correctly, the only reason for custom init in Origin is a different default recycler template at https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/master/controller/volumes.go#L76

So we need a way how to pass a *v1.Pod with a recycler template from place where OpenShift and Kubernetes is different into [startPersistentVolumeBinderController](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/core.go#L146) that is the same for both (and to ProbeControllerVolumePlugins that's called by it).

I see several ways out of this, not sure how acceptable they would be upstream.

1. Add a new field into `ControllerContext`:
   ```go
   type ControllerContext struct {
       ClientBuilder controller.ControllerClientBuilder
       InformerFactory informers.SharedInformerFactory
       Options options.CMServer
       AvailableResources map[schema.GroupVersionResource]bool
       Cloud cloudprovider.Interface
       Stop <-chan struct{}
       RecyclerVolumeTemplate *v1.Pod // <----
    }
   ```
   OpenShift would fill its own template, call Kubernetes' `NewControllerInitializers()` and `startPersistentVolumeBinderController` would find the template in its context. This seems to be the cleanest way to me.

2. Add a new field into `CMServer`:
   ```go
   type CMServer struct {
      componentconfig.KubeControllerManagerConfiguration
      RecyclerVolumeTemplate *v1.Pod
      ...
   ```
    This is equivalent to 1., just with a different place for the template that's available from `ControllerContext.Options`.

3. Change Kubernetes' `ProbeControllerVolumePlugins` to accept the template from caller:
   ```go
   func ProbeControllerVolumePlugins(cloud cloudprovider.Interface, config componentconfig.VolumeConfiguration, defaultRecyclerTemplate *v1.Pod) []volume.VolumePlugin {
   ```
   And once it's there, we copy Kubernetes' initalizer into OpenShift (just 19 lines of [startPersistentVolumeBinderController](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/core.go#L146)  ), only with the different default template. This protects us from changes in volume plugins, however it still can make troubles when these 19 lines of Kubernetes' startPersistentVolumeBinderController are changed.

@deads2k, what do you say? Is there any better way? Is there any other controller that solves the same problem?

**Comment by jsafrane** [comment]
Oh, an there is of course 3. Add recycler pod template to `KubeControllerManagerConfiguration`. This requires changing `k8s.io/kubernetes/pkg/apis/componentconfig/types.go`:

```go
type PersistentVolumeRecyclerConfiguration struct {
        ...
        DefaultPodTemplate *v1.Pod
}
```

It would add dependency of `apis/componentconfig/types.go` on `v1/types.go` which does not look right to me.
