### ISSUE TITLE
RBAC Migration Followup #4: Use upstream subject locator directly

### ISSUE THREAD

**Issue by enj** [openshift/origin#15816]
Remove `openshiftSubjectLocator`

**Comment by enj** [comment]
@abstractj per our earlier conversation:

1. Delete the openshift version of the subject interface
2. Delete our wrapper around the kube subject interface
3. Update all users of our interface with the kube interface
4. Fix any issues that item 3 creates

**Comment by abstractj** [comment]
@enj n00b friendly speaking, for item **1** are you talking about this piece of code https://github.com/abstractj/origin/blob/a94e0db72459c5963eb474acf0dc31ae1eb72486/pkg/authorization/authorizer/authorizer.go#L19-L21 ? 

And for **2** is this the part of the code you mention https://github.com/abstractj/origin/blob/a94e0db72459c5963eb474acf0dc31ae1eb72486/pkg/authorization/authorizer/authorizer.go#L27-L29?
