### ISSUE TITLE
intermitent errors with OC client and minishift.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#15811]
[provide a description of the issue]

Sometimes, the OC client (3.2) explodes when accessing my minishift cluster

Oddly, I don't see this behaviour in the 3.1 client.

##### Version

- My minishift version is  1.4
- The breaking oc client is 3.2
- The more robust OC client from what i can tell is 3.1.1.

##### Steps To Reproduce
1. minishift start
2. Run the following ad naseum:

oc login system:admin 

about 30% of the time, you get:

##### Current Result

```
Using project "myproject".
failed MSpanList_Insert 0x2a61780 0xb1dd767faa3e6 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x268c1d0, 0x2a61780)
        /usr/lib/golang/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x268ade0, 0x1, 0x10000000025, 0xd539)
        /usr/lib/golang/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x26940b8, 0xc208598d10)
        /usr/lib/golang/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x2a3f000, 0x25, 0x1786780)
        /usr/lib/golang/src/runtime/mcache.c:90 +0xa0

goroutine 30 [running]:
runtime.switchtoM()
        /usr/lib/golang/src/runtime/asm_amd64.s:198 fp=0xc208599240 sp=0xc208599238
runtime.mallocgc(0x800, 0x0, 0x3, 0x1)
        /usr/lib/golang/src/runtime/malloc.go:178 +0x849 fp=0xc2085992f0 sp=0xc208599240
runtime.rawmem(0x800, 0x800)
        /usr/lib/golang/src/runtime/malloc.go:371 +0x39 fp=0xc208599318 sp=0xc2085992f0
runtime.growslice(0x11a75c0, 0x0, 0x0, 0x0, 0x70a, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/runtime/slice.go:83 +0x237 fp=0xc208599378 sp=0xc208599318
crypto/tls.(*Conn).readHandshake(0xc208392840, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:835 +0x522 fp=0xc208599538 sp=0xc208599378
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc208519e60, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/handshake_client.go:227 +0x68 fp=0xc208599ad0 sp=0xc208599538
crypto/tls.(*Conn).clientHandshake(0xc208392840, 0x0, 0x0)
```

##### Expected Result

The OC client should probably never spew a stack trace this large , and should summarize why the handshake is a problem, maybe it should even retry the handshake ?

**Comment by smarterclayton** [comment]
Are you on a Mac from the client?  The 3.2 binaries won't run against El Capitan or later unless they were rebuilt against Go 1.7

**Comment by jayunit100** [comment]
@smarterclayton  its a symptom of  https://github.com/alco/goon/issues/10 . Is there a way openshift can handle this gracefully ? if so it would be nice.  otherwise we can close it.
