### ISSUE TITLE
RBAC Migration Followup #11: Remove getAPIGroupLegacy from scope converter

### ISSUE THREAD

**Issue by enj** [openshift/origin#15824]
Upstream rules have always required a group.  Remove `getAPIGroupLegacy` from `pkg/authorization/authorizer/scope/converter.go`

**Comment by mrogers950** [comment]
@enj can you expand on "Remove" here? Just getting rid of getAPIGroupLegacy() and its call in removeEscalatingResources() outright causes the converter test to fail:
```
	converter_test.go:281: skip non-matching group secrets: expected [PolicyRule{NonResourceURLs:["/" "/.well-known" "/.well-known/*" "/api" "/api/*" "/apis" "/apis/*" "/oapi" "/oapi/*" "/osapi" "/osapi/" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version" "/version/*"], Verbs:["get"]} PolicyRule{Resources:["pods" "secrets"], APIGroups:["foo"]}], got [PolicyRule{NonResourceURLs:["/" "/.well-known" "/.well-known/*" "/api" "/api/*" "/apis" "/apis/*" "/oapi" "/oapi/*" "/osapi" "/osapi/" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version" "/version/*"], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:["foo"]}]
```

**Comment by enj** [comment]
@mrogers950 the only test the fails for me locally is `match old group secrets`.  I believe that test can be changed to `no longer match old group secrets"` which should confirm that `secrets` is not dropped anymore.

**Comment by enj** [comment]
Just to be clear, you should be able to delete the `getAPIGroupLegacy` code completely and only minor changes should be required to the associated tests to keep everything passing.
