### ISSUE TITLE
[PROPOSAL] Add --interactive flag to `oc delete`

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#15829]
**Case**
The `oc delete` command does not currently ask for confirmation before deleting resource(s). 

**Solution**
Although asking for confirmation interactively out of the box would go against cli principles of having all commands be scriptable, a solution to this would be to have the user explicitly ask for `oc delete` to be interactive by passing a flag (such as `oc delete ... --confirm`). This would introduce a non-breaking change to the command for existing scripts, and would allow users to have the same experience as the web console when using the command.

**Notes**
Related bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1405198

cc @openshift/cli-review @spadgett @smarterclayton

**Comment by smarterclayton** [comment]
So in order to be safe, someone has to remember to type --interactive?  Doesn't seem likely that's going to prevent the user from accidentally deleting things

**Comment by fabianofranz** [comment]
I'd still not recommend making it interactive, but something like this could be possible (probably not applicable for all kinds, but the most destructive ones like `project`):

```
$ oc delete project mystuff
WARNING: deleting the project will also delete all resources in it. If you are sure bla bla run it again with the "--confirm" flag.

$ oc delete project mystuff --confirm
project "mystuff" deleted
```

This is somehow not backwards compatible though, in the sense that a given command ran exactly the same way no longer does exactly the same thing.

**Comment by smarterclayton** [comment]
Yeah, we can't change delete without a much larger set of agreement.  And
it would still be backwards incompatible, so we should probably focus on
doing delete protection instead (there's another issue tracking it in kube)
so that users have to think before deleting certain resources.
