### ISSUE TITLE
RBAC Migration Followup #15: Revisit forbidden message maker

### ISSUE THREAD

**Issue by enj** [openshift/origin#15828]
Revisit forbidden message maker (see if its needed / what we need from it)

For example, it prevents leaking information about if projects exist

**Comment by abstractj** [comment]
@enj where the forbidden message maker is located?

**Comment by enj** [comment]
See `NewForbiddenMessageResolver` in `pkg/authorization/authorizer/messages.go`.  You will want to trace the history from starting from #2319 to determine if:

1. Any of the code can be deleted
2. Any of the code can be replaced with upstream equivalents
