### ISSUE TITLE
RBAC Migration Followup #12: use RBAC encoding in create-bootstrap-policy-file 

### ISSUE THREAD

**Issue by enj** [openshift/origin#15825]
Switch encoding to RBAC in `pkg/cmd/server/admin/create_bootstrappolicy_file.go`

**Comment by enj** [comment]
This is similar to #15833 / #15857 in that it deals with how we encode exported auth data.  Currently the `create-bootstrap-policy-file` command writes out the legacy origin auth types instead of the RBAC objects.

@deads2k @liggitt can we do this in 3.7?  Won't it make the command incompatible with older clusters?

**Comment by deads2k** [comment]
@enj didn't you guys kill the file since it wasn't being used anymore?

**Comment by simo5** [comment]
@deads2k the admin command to create a bootstrap policy file still exists

**Comment by deads2k** [comment]
> @deads2k @liggitt can we do this in 3.7? Won't it make the command incompatible with older clusters?

@fabianofranz what kind of stability guarantees do we have on the command?  If its based on intent, I guess I'd keep the encoding for 3.7 and switch for 3.8.  I think the failure mode would be a 3.7 oc against a 3.6 master that was trying to export the rules and do something with them.
