### ISSUE TITLE
RBAC Migration Followup #10: Fix router ignore error

### ISSUE THREAD

**Issue by enj** [openshift/origin#15822]
Fix `ignoreError` in `pkg/oc/admin/router/router.go`

**Comment by mrogers950** [comment]
@enj it looks like you're referring to correcting the 'Temp fix for test/cmd/router.sh' part of 806d7be. What are we looking for in a permanent fix here?

**Comment by mrogers950** [comment]
Removing the added check for details.Kind == "clusterrolebindings" does not cause test/cmd/router.sh to fail in any obvious way, so perhaps this fix is not needed anymore.

**Comment by enj** [comment]
@mrogers950 yeah I was hoping that reverting back the original code 

```go
return (details.Kind == "serviceaccounts" && details.Name == saName) ||
(details.Kind == "clusterrolebinding" && details.Name == roleBindingName)
```

would work since I had done a lot of work to make the proxy give the "correct" error.

I am fine with that as a fix, but see if you can figure out what ignoring that error actually means and add some docs around it in the code.
