### ISSUE TITLE
RBAC Migration Followup #8: Remove policy from bootstrap policy

### ISSUE THREAD

**Issue by enj** [openshift/origin#15820]
Remove policy objects from bootstrap roles

**Comment by simo5** [comment]
@enj, we need more context here for people to be able to pick this up and do something.

**Comment by enj** [comment]
Our bootstrap auth policy most likely still grants users access to `{cluster}policy{binding}` objects.  We need to scrub the code for these policy rules and remove them since the endpoints no longer exisit.  An example that uses an RBAC builder (origin has something similar which we may be able to delete, and rules can also be created manually so some regex foo may be require to make sure everything has been cleaned up):

`rbac.NewRule(...).Groups(...).Resources("policybindings").RuleOrDie()`
