### ISSUE TITLE
x509 error trying to run an oc new-app sample behind a corporate proxy that intercepts and substitutes certs

### ISSUE THREAD

**Issue by bobmhong** [openshift/origin#15883]
I'm testing an origin cluster created with oc cluster up on RHEL7.  Our corporate proxy intercepts and replaces certs for certain URLs needed to download docker images (dseasb33srnrn.cloudfront.net).

I needed to add the company cert to /etc/pki/ca-trust/source/anchors and run update-ca-trust extract, then service docker restart to get the cluster to start properly.

I'm now getting an x509 error when trying to use oc new-app to try one of the sample apps.

I'm not sure where to put the company cert so this will work.

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
 
Server https://127.0.0.1:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

##### Current Result
https://gist.github.com/bobmhong/992a8a95a5601bc71da2dec11837c0e8

##### Expected Result
oc new-app is able to download necessary images because company's custom proxy cert is trusted 

Thanks,

Bob

**Comment by akostadinov** [comment]
You need to add your company certificate into a `builder` user account secret.
https://docs.openshift.com/container-platform/3.3/dev_guide/builds.html#trusted-certificate-authorities and add as a `sourceSecret` to your build config.

**Comment by bobmhong** [comment]
@akostadinov Thanks.  I've tried the following, but so far no luck: 

oc login -u=server -p=password -n=bob1
oc secrets new custom-tls-ca-bundle ca.crt=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
oc secrets link builder custom-tls-ca-bundle
oc annotate secret custom-tls-ca-bundle 'build.openshift.io/source-secret-match-uri-1=*://*'
oc set build-secret --pull --all custom-tls-ca-bundle

The docs mention this will allow Git to trust my cert, but does not mention how to configure the ca for pulling images.

Thoughts?

**Comment by akostadinov** [comment]
For pulling images, that should be configured the way you described in your original description. I thought your remaining issue is git clone.

**Comment by bobmhong** [comment]
Unfortunately I'm still struggling with this.  I am able to pull docker images from my linux host directly, but the operation fails when the pull is done in response to an oc new app command.  

I tried placing the cert in /etc/pki/ca-trust/source/anchors and running update-ca-trust extract within the origin container as I did in my linux host and still got the error.  

Attempted to do the same in my origin-docker-registry container, but did not have rights to the /etc/pki/ca-trust/source/anchors directory.

Any other ideas?

**Comment by akostadinov** [comment]
For me it's been working - just add CA as you describe on **all** nodes in the cluster + restart docker daemon. I never needed to add CAs to the containers themselves. Did you do this?

Alternatively you can try setting `--insecure-registry=` option to docker but only as a test, not recommended for production use.
