### ISSUE TITLE
error: server does not support API version "federation/v1beta1

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#15895]
I have two openshift clusters  with contexts  `fed`  and `cluster1`  

##### Version
on both clusters this is the current openshift version
```sh
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
```
kubefed init fellowship --host-cluster-context=fed --dns-provider="google-clouddns" --dns-zone-name="fed.xfc.io." --image='openshift/origin-federation:v3.6.0-alpha.2'
```
```console
[root@master1 origin]# kubectl get pods --namespace=federation-system
NAME                                             READY     STATUS    RESTARTS   AGE
fellowship-apiserver-3159749933-300fh            2/2       Running   0          8m
fellowship-controller-manager-1770790688-4qvqj   1/1       Running   1          8m
```
> Trying this 
```sh
kubefed join cluster1 --host-cluster-context=fed
```

##### Current Result
```
[root@master1 origin]# kubefed join cluster1 --host-cluster-context=fed
error: server does not support API version "federation/v1beta1"
```
##### Expected Result
```
cluster1 should join the federation
```

##### Additional Information
I'm using kubefed supplied by openshift releases and clusters are stood up using oc cluster up

**Comment by mfojtik** [comment]
@deads2k @sttts i can see the federation is in 'unexposed' groups and commented out in as "enable as part of a separate binary"

**Comment by debianmaster** [comment]
@deads2k  @sttts  any comments ?

**Comment by deads2k** [comment]
> @deads2k @sttts any comments ?

I'd ask @marun about federation problems.

**Comment by marun** [comment]
Given that there is no intent to support federation v1, I'm moving the priority to backlog.
