### ISSUE TITLE
Cannot access service through external IP

### ISSUE THREAD

**Issue by adalga** [openshift/origin#15892]
I want to access my service through externalIp. To do this I have done the instructions on openshift documentation. I changed the master config and restart the master services. I set the IngressIPNetworkCIDR: 172.46.0.0/16. However, when I make the service's spec->port->type : LoadBalancer it assigns 172.29.*.* still. And I can't access the service via given IP.Connection times out. What am I doing wrong?

##### Version
openshift v3.5.5.26
kubernetes v1.5.2
etcd 3.1.0

**Comment by teotia39** [comment]
Even me getting the same issue while using HA cluster with multimasters , I can easily access service via
<master_ip>:<node_port> , but not via <external_ip>:<node-port> , even when the external IP is added in DNS server of my org's network.

Who is actually generating this external ip , is this HA-Proxy incase of my HA cluster or openshift generating something randomly , How Do i get a single entry point of my service (backed by two masters) outside kubernetes cluster . I think ingress type services cannot be created in openshift.
