### ISSUE TITLE
regression  61a8212 : server crash while processing template to resources

### ISSUE THREAD

**Issue by xjvs** [openshift/origin#1590]
61a8212 introduced a regression which cause server crash while processing template to resources.
How to reproduce:

1. Open a terminal A, and start openshift
```
# pwd
/root/go/src/github.com/openshift/origin/examples/sample-app

# openshift start
...<snip>...
```
2. Open another terminal B, and run commands:

```
# pwd
/root/go/src/github.com/openshift/origin/examples/sample-app

# export OPENSHIFTCONFIG=`pwd`/openshift.local.certificates/admin/.kubeconfig
# export CURL_CA_BUNDLE=`pwd`/openshift.local.certificates/ca/cert.crt

# osc process -f application-template-stibuild.json
F0403 15:04:59.893169   12397 process.go:131] Post https://192.168.10.5:8443/osapi/v1beta1/templateConfigs?namespace=default: EOF
```

in terminal A, you'll see openshift crashed immediately. There are 9000+ lines of error messages (from 900+ go routines) printed on console, so I'm not going to paste it here. You can reproduce with the simple steps above.

It doesn't happen with 69e1d88.

**Comment by ncdc** [comment]
I'll take a look at this

**Comment by ncdc** [comment]
I'm not able to reproduce. Can you please redirect the output from `openshift start` to a log file, and when you reproduce, paste the first lines you see related to a panic?

**Comment by ncdc** [comment]
Or just paste the entire log to fpaste or something like that, if you want.

**Comment by xjvs** [comment]
hi, I just reproduced it with another host and paste part of the log here: http://ur1.ca/k3ria

**Comment by ncdc** [comment]
What git commit are you currently at?

**Comment by xjvs** [comment]
My fault, Andy just talked with me on irc, I'm running the old binary without make clean build. The latest code doesn't crash indeed. I'll update here after go through the sample-app guide.

**Comment by xjvs** [comment]
I confirmed it works well with the latest code. sorry, closing this.
