### ISSUE TITLE
Controller metrics don't follow prometheus conventions

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15917]
Caught this in master:

![metrics](https://www.dropbox.com/s/lc9a7r5nnpw7c8h/Screenshot%202017-08-22%2022.39.57.png?raw=1)

No prometheus metric should have upper case.  Should always be snake case.  Needs to be fixed.

**Comment by smarterclayton** [comment]
@deads2k / @derekwaynecarr not sure who touched this code path last.

**Comment by smarterclayton** [comment]
Also

![bad](https://www.dropbox.com/s/pyci3yes8fx7juw/Screenshot%202017-08-22%2022.41.29.png?raw=1)

Also bad

**Comment by smarterclayton** [comment]
This looks like there is one metric being created *per resource version* which is so bad I can't even describe how bad the badness is.  :)  Must fix for release to online because this will murder prometheus.

**Comment by deads2k** [comment]
> This looks like there is one metric being created per resource version which is so bad I can't even describe how bad the badness is. :) Must fix for release to online because this will murder prometheus.

Pretty sure that number is just our uniquifier.  One metric per reflector.

**Comment by smarterclayton** [comment]
Either way, needs to be brought under control.  Your uniquifier should
probably just be a label if it has no meaning, and if you don't know what
the metric measures I'm not sure what value the metric is providing.

On Aug 23, 2017, at 7:07 AM, David Eads <notifications@github.com> wrote:

This looks like there is one metric being created per resource version
which is so bad I can't even describe how bad the badness is. :) Must fix
for release to online because this will murder prometheus.

Pretty sure that number is just our uniquifier. One metric per reflector.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15917#issuecomment-324296661>,
or mute the thread

**Comment by smarterclayton** [comment]
The part we need to verify is that I believe there is code creating stores and reflectors for one off objects (as part of normal control flow code) and if so this pattern can't work (grows unbounded).  Anonymous reflectors should just be anonymous, or fall into a single generic pool.  Even a count of how many anonymous reflectors there are would be ok, or if the average distribution of size of the store.  But auto generated unbounded cardinality will kill us and isn't worth it.

**Comment by deads2k** [comment]
> Either way, needs to be brought under control.  Your uniquifier should
> probably just be a label if it has no meaning, and if you don't know what
> the metric measures I'm not sure what value the metric is providing.

Prometheus metric registration requires a unique name and we don't have one at the point where this metric is getting created.  We're counting on the rest of the name to "unique enough" to provide value.  Notice that it specifies origin and type.  We just don't want it to kill a server process if it collides.

**Comment by deads2k** [comment]
> But auto generated unbounded cardinality will kill us and isn't worth it.

Not unbounded.  Per reflector.  If your reflectors grow unbounded, you'll crash from traffic/memory/decoding long before metric gathering is a problem.
