### ISSUE TITLE
Deprecate any remaining legacy auth policy users in 3.7 release notes

### ISSUE THREAD

**Issue by enj** [openshift/origin#15932]
Deprecate the following in 3.7 so we can remove them in 3.8:

1. Gated commands
2. The use of `oadm policy` commands against an older cluster (i.e. stop using the proxied endpoints internally in the server and via the client)
3. ??

cc @openshift/api-review @openshift/cli-review

**Comment by simo5** [comment]
Handling here: https://github.com/openshift/openshift-docs/issues/4906
