### ISSUE TITLE
Accesslog can't be disabled in docker-registry

### ISSUE THREAD

**Issue by born2fail** [openshift/origin#15949]
Trying to modify docker registry configuration as shown in: 
https://docs.openshift.org/latest/install_config/registry/extended_registry_configuration.html#registry-configuration-reference
https://docs.docker.com/registry/configuration/#accesslog
```
log:
  accesslog:
    disabled: true
```
Log output still include accesslog entries. Another modifications done to docker registry configuration file (like formatter: logstash) are working good.

##### Version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.beabloo.com:8443
openshift v1.5.1
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. Create new configuration file
2. oc secrets new registry-config config.yml=config-docker.yml
3. oc volume dc/docker-registry --add  --type=secret     --secret-name=registry-config -m /etc/docker/registry/
4. oc set env dc/docker-registry     REGISTRY_CONFIGURATION_PATH=/etc/docker/registry/config.yml

##### Current Result
docker registry output (logs) show accesslog entries

##### Expected Result
accesslog entries are not shown

**Comment by pweil-** [comment]
access log configuration was [added in the 2.6 release](https://github.com/docker/distribution/commit/4034ff65f0d4812aa61663d6d3ea5dc26819df6f).  The rebase to 2.6 is currently being worked and can be [tracked with this card](https://trello.com/c/Vac6mHz5/1277-8-registry-rebase-docker-distribution-to-26x)
