### ISSUE TITLE
Builds started from a build config should have a structural reference to the creating build config

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1595]
A build that is unambiguously created from a build config should be associated to the creating build config via an ObjectReference.  The label can remain, but the build should point to its creator.  Is related to the triggering information, but is a primary structural field.  Should be set by the generator.

**Comment by soltysh** [comment]
@smarterclayton can we close this?

**Comment by smarterclayton** [comment]
Yes, implemented.
