### ISSUE TITLE
Pods fail to start during containerized install

### ISSUE THREAD

**Issue by jmencak** [openshift/origin#15953]
Pods fails to start during containerized install in RHEL Atomic Host 7.4 and oc 3.7

##### Version
$ oc version
oc v3.7.0-0.104.0
kubernetes v1.7.0+695f48a16f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ip-172-31-8-189.us-west-2.compute.internal:8443
openshift v3.7.0-0.104.0
kubernetes v1.7.0+695f48a16f

##### Current Result
    $ oc get pods
    NAME                        READY     STATUS              RESTARTS   AGE
    pod-diagnostic-test-zsq3d   0/1       ContainerCreating   0          4m
    router-2-deploy             0/1       ContainerCreating   0          1h

    # journalctl -xe|grep router|tail -n1
    Aug 24 10:52:08 ip-172-31-8-189.us-west-2.compute.internal dockerd-current[1195]: E0824 10:52:08.632329    9522 pod_workers.go:182] Error syncing pod 1ed023e6-88aa-11e7-9491-02ec7115a004 ("router-2-deploy_default(1ed023e6-88aa-11e7-9491-02ec7115a004)"), skipping: failed to "KillPodSandbox" for "1ed023e6-88aa-11e7-9491-02ec7115a004" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"router-2-deploy_default\" network: failed to find plugin \"openshift-sdn\" in path [/opt/openshift-sdn/bin /opt/cni/bin]"

##### Expected Result
Pods starting.

##### Additional Information
Pods started fine on RHEL Atomic Host 7.4 and oc 3.6

**Comment by jmencak** [comment]
Same issue on v3.7.0-0.109.0

**Comment by sdodson** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1485312 bug on this too, i'll try to get someone on installer side to look at it today but it's probably best triaged by networking team.

**Comment by sdodson** [comment]
https://github.com/openshift/origin/issues/15210 same error

**Comment by ashcrow** [comment]
Responding in BZ

**Comment by pweil-** [comment]
marking this p0 as the bug is marked urgent

**Comment by ashcrow** [comment]
In https://bugzilla.redhat.com/show_bug.cgi?id=1485312#c6 @jupierce noted that the package was accidentally removed in the build and should be back in the next build.

**Comment by jmencak** [comment]
Works with v3.7.0-0.117.0 puddle now.  I think this can be closed.
