### ISSUE TITLE
Could not fetch resource: Quota 'ROUTES' exceeded

### ISSUE THREAD

**Issue by sjenning** [openshift/origin#15969]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15940/test_pull_request_origin_extended_conformance_gce/6541/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15956/test_pull_request_origin_extended_conformance_gce/6540/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15558/test_pull_request_origin_extended_conformance_gce/6539/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15955/test_pull_request_origin_extended_conformance_gce/6537/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15940/test_pull_request_origin_extended_conformance_gce/6536/

```
TASK [gce-provision : Provision GCE resources] *********************************
Thursday 24 August 2017  14:31:39 +0000 (0:00:00.080)       0:00:02.972 ******* 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/tmp/provision.sh"], "delta": "0:00:51.011002", "end": "2017-08-24 14:32:30.285033", "failed": true, "rc": 1, "start": "2017-08-24 14:31:39.274031", "stderr": "ERROR: (gcloud.compute.networks.create) Could not fetch resource:\n - Quota 'ROUTES' exceeded.  Limit: 300.0", "stderr_lines": ["ERROR: (gcloud.compute.networks.create) Could not fetch resource:", " - Quota 'ROUTES' exceeded.  Limit: 300.0"], "stdout": "", "stdout_lines": []}
```

**Comment by smarterclayton** [comment]
Was fixed a while back.
