### ISSUE TITLE
new CLI: oc link-service someNamespace serviceNames | --all | -l foo=bar

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#15980]
it would be useful to be able to link services from `someNamespace` into the current (or some other) namespace.

When developing inside Che inside fabric8 / openshift.io the workspace pod is in the `jstrachan-che` namespace and it'd be nice to be able to link all services running in the staging environment (in namespace `jstrachan-stage`) so that any apps running in the workspace pod can reuse local services in the `Che` namespace which point to the services in `Staging`

e.g. inside the Che workspace shell it'd be nice to do something like:

```bash
$ oc project jstrachan-stage
$ oc get service
NAME        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
cheese160   172.30.8.89   <none>        8080/TCP   1d

$ oc project jstrachan-che
$ oc get service
No resources found.

# now lets link cheese160 from staging into the che namespace

$ oc link-service jstrachan-stage --all
service cheese160 linked in namespace jstrachan-che

$ oc project jstrachan-che
$ oc get service 

NAME        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
cheese160   <none>     cheese160.jstrachan-stage        8080/TCP   1m
```

## How it works
So the `oc link-service` command would take the source namespace then some service selection criteria (`--all`, one or more names or a `--label` selector). It could take an optional target namespace (which if not specified would use the current namespace context).

Then for each service `foo` found in the source namespace `sourceNamespace` that match the name/selector the code would:

* oc export service foo --namespace sourceNamespace > foo.yml
* remove the selector 
* add `externalName: foo.targetNamespace`
* oc apply -f foo.yml -n targetNamespace

i.e. it'd create a similar service in the target namespace that links to the source service.

We may need a flag to overwrite existing services that already exist in the target namespace or whether to log a warning

**Comment by jorgemoralespou** [comment]
@jstrachan What about network connectivity? How would you make sure that the service in namespace jstrachan-che can access the service in namespace jstrachan-stage? Is this assuming a specific network plugin? With openshift-sdn-multitenant both projects need to be joined. With opensihft-sdn-networkpolicy there needs to be network policies allowing the pods in namespace jstrachan-che to access pods in namespace jstrachan-stage, AFAIK.

**Comment by jstrachan** [comment]
I guess the command could check if the network works between the namespaces; if not it could see if there's an external name (e.g. a Route) for the service? If it can't know/test that the service is linked it could fail and report that the network can't connect?

I guess defaulting to an external Route is maybe safer - if there is one for the service
