### ISSUE TITLE
PUT with `Expect: 100-continue` results in 500

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#1598]
I am trying to `PUT` a custom json with modified labels to master's REST api. Master is hidden behind httpd auth proxy.

Unfortunately the master is unable to handle header `Expect: 100-continue\r\n` properly.

Request forwarded from httpd proxy to master:
```
PUT /osapi/v1beta1/builds/hello-world-20150406-145951?namespace=default HTTP/1.1\r\n
Host: 127.0.0.1:8443\r\n
User-Agent: PycURL/7.29.0\r\n
Accept: */*\r\n
Content-Type: application/json\r\n
Authorization: Bearer MGYwMzU2OGEtMWNjYi00MWQ3LWFiNjUtNWJiMDFiN2RhZjI5\r\n
Expect: 100-continue\r\n
Connection: Keep-Alive\r\n
Content-Length: 0\r\n
```

Response from master to httpd proxy:
```
HTTP/1.1 500 Internal Server Error\r\n
Content-Type: application/json\r\n
Date: Mon, 06 Apr 2015 13:00:26 GMT\r\n
Content-Length: 144\r\n

{\n  "kind": "Status",\n  "creationTimestamp": null,\n  "apiVersion": "v1beta1",\n  "status": "Failure",\n  "message": "empty input",\n  "code": 500\n}
```

Master should react to `Expect: 100-continue` by sending `HTTP/1.1 100 Continue\r\n\r\n` and not fail with 500.

**Comment by smarterclayton** [comment]
Is this with mod_auth or something more sophisticated?

**Comment by TomasTomecek** [comment]
httpd with basic auth (can provide whole config)
client is curl (I think that `curl -X PUT -d @build.json ...` should reproduce it)

**Comment by smarterclayton** [comment]
Looking at the Go docs there's comments that they already handle this, but maybe we're doing something specific that blocks it.

----- Original Message -----

**Comment by liggitt** [comment]
this actually isn't the auth component... it's the API server not being ok with getting a request containing no body it can deserialize... @smarterclayton, where did you see comments that addressed the 100 status code?

**Comment by smarterclayton** [comment]
It was more the server support side.

----- Original Message -----

**Comment by liggitt** [comment]
@TomasTomecek should probably close here and move to an upstream issue

**Comment by TomasTomecek** [comment]
@liggitt okay, I haven't tried this in a while. We've workarounded it by doing `POST` instead of `PUT`.

**Comment by TomasTomecek** [comment]
FYI, this is no longer an issue in k8s:
```
% curl -v -H "Expect: 100-continue" -d @node.json -XPUT http://127.0.0.1:8080/api/v1/nodes/127.0.0.1
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> PUT /api/v1/nodes/127.0.0.1 HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.44.0
> Accept: */*
> Expect: 100-continue
> Content-Length: 1019
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 409 Conflict
< Content-Type: application/json
< Date: Fri, 11 Sep 2015 08:36:29 GMT
< Content-Length: 334
<
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "node \"127.0.0.1\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again",
  "reason": "Conflict",
  "details": {
    "name": "127.0.0.1",
    "kind": "node"
  },
  "code": 409
* Connection #0 to host 127.0.0.1 left intact
}
```

**Comment by liggitt** [comment]
ha, just tried against origin and it worked there as well
