### ISSUE TITLE
Instructions for oc cluster up in Fedora 26

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#15983]
In Fedora 26, there is a new (different) way to configure the insecure-registry option required by oc cluster up. Documentation needs to reflect it.

**Comment by bparees** [comment]
@csrwng we shouldn't provide any documention on on how to do this.  just tell people they need to add the insecure registry.  Anything else is asking for a doc maintenance nightmare.

**Comment by csrwng** [comment]
@bparees so just remove the existing instructions?

**Comment by bparees** [comment]
@csrwng replace them with "configure docker with the insecure registry FOO." and maybe link to the docker docs for configuring insecure registries.  But don't get distribution/platform specific.

**Comment by csrwng** [comment]
makes sense. @jorgemoralespou do you want to make that change in this pr?

**Comment by jorgemoralespou** [comment]
@csrwng, no. I'll close this PR, as it will be difficult for me to get the
right wording, links, etc...
