### ISSUE TITLE
Disable sdn in openshift after installation

### ISSUE THREAD

**Issue by prasenforu** [openshift/origin#15999]
OC 3.2
Installation done using Ansible.

Want to use different CNI.

For that I want to disable sdn in openshift after installation.

But do not want to reinstall entire openshift.

Please help

**Comment by knobunc** [comment]
Can't you make your change and re-run the ansible playbook?  It should just change the appropriate setting.

If you are unwilling to do it using Ansible, you can edit the config on each node and in the master.
