### ISSUE TITLE
process valueFrom in build strategy environment variables should successfully resolve valueFrom in docker build environment variables

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16008]
```
[builds][Conformance][valueFrom] process valueFrom in build strategy environment variables should successfully resolve valueFrom in s2i build environment variables 51s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\s\[builds\]\[Conformance\]\[valueFrom\]\sprocess\svalueFrom\sin\sbuild\sstrategy\senvironment\svariables\sshould\ssuccessfully\sresolve\svalueFrom\sin\ss2i\sbuild\senvironment\svariables$'
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/valuefrom.go:71
Expected
    <bool>: false
to be true
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/valuefrom.go:60
```

Seen this here:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15624/test_pull_request_origin_extended_conformance_install_update/4947/

Seems related to docker.io laziness:

```
2017-08-28T11:49:36.106806000Z F0828 11:49:36.105568       1 helpers.go:120] error: build error: failed to pull image: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/26/2645884c86a61245b3c79c40e866b5fb06867114726fcf5ea427197bf74a7941/data?Expires=1503922166&Signature=RPOo5Zs-Qr~3vCT0CDd~kZqkQ3o7GJ2La2LcXnQb5FwJbAKTkDYrrqs2o79jU~0IhqZoYVHuTLebiREybsLaYKeKude4rH-Cq2RKsM9snypfA6jCIfIwwYmIRvTmWUp0xzZYKP4vyIiRlTbjCDYRJ-HK3GJcHyitXtgE2sxVDvU_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout
```

**Comment by bparees** [comment]
We should look into whether we can do more aggressive retries on pull failures in cases like this.

**Comment by bparees** [comment]
(As with failure to push, the cost of retrying a failing pull that will never succeed is worth paying, against the cost of failing a build that otherwise could have succeeded if we'd retried)

**Comment by bparees** [comment]
build log is available here: 
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/15624/test_pull_request_origin_extended_conformance_install_update/4947/artifacts/junit_03.xml

(search for error: build error: failed to pull image: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/26/2645884c86a61245b3c79c40e866b5fb06867114726fcf5ea427197bf74a7941/data?Expires=1503922166&Signature=RPOo5Zs-Qr~3vCT0CDd~kZqkQ3o7GJ2La2LcXnQb5FwJbAKTkDYrrqs2o79jU~0IhqZoYVHuTLebiREybsLaYKeKude4rH-Cq2RKsM9snypfA6jCIfIwwYmIRvTmWUp0xzZYKP4vyIiRlTbjCDYRJ-HK3GJcHyitXtgE2sxVDvU_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout )

**Comment by enj** [comment]
Seen in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17617/test_pull_request_origin_extended_conformance_install/3574/

**Comment by bparees** [comment]
@enj different issue.  you hit https://github.com/openshift/origin/issues/17330
