### ISSUE TITLE
We log too much output about requests at v5

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16001]
Every API call generates the following.  This makes our v5 debugging logs 5x bigger than they need to be.  I think at this point we can safely say the "satisfied by" is not necessary for our debugging - we should kick it to v(6) or higher.  That would make our integration and e2e test logs much more information dense with no loss.

```
I0823 20:47:22.539012    1505 handler.go:160] kube-aggregator: GET "/apis/user.openshift.io/v1/users/admin" satisfied by nonGoRestful
I0823 20:47:22.539028    1505 pathrecorder.go:247] kube-aggregator: "/apis/user.openshift.io/v1/users/admin" satisfied by prefix /apis/user.openshift.io/v1/
I0823 20:47:22.539034    1505 handler.go:160] kube-apiserver: GET "/apis/user.openshift.io/v1/users/admin" satisfied by nonGoRestful
I0823 20:47:22.539039    1505 pathrecorder.go:253] kube-apiserver: "/apis/user.openshift.io/v1/users/admin" satisfied by NotFoundHandler
I0823 20:47:22.539044    1505 handler.go:160] openshift-apiserver: GET "/apis/user.openshift.io/v1/users/admin" satisfied by nonGoRestful
I0823 20:47:22.539048    1505 pathrecorder.go:253] openshift-apiserver: "/apis/user.openshift.io/v1/users/admin" satisfied by NotFoundHandler
I0823 20:47:22.539077    1505 handler.go:150] user.openshift.io-apiserver: GET "/apis/user.openshift.io/v1/users/admin" satisfied by gorestful with webservice /apis/user.openshift.io/v1
```

**Comment by deads2k** [comment]
This logging is an absolute life saver when trying to sort out why your delegated server (which openshift uses *a lot*), isn't working.  Putting at loglevel 6 starts showing our client API calls too.

What else are you looking at at loglevel 5 which has more utility in the API server?  Maybe that should move to a 4.  Controllers are a separate process, so you're only dealing with apiserver log messages.

**Comment by smarterclayton** [comment]
Every other component does debug at log level 5.  However, these 5 lines
are 95% of log level logic.  Which says to me that this component is being
selfish and making everyone else's debugging worse, to catch a very rare
problem.  Every one else's debugging gets worse so that you can debug this
one component, which isn't very useful.  We have targeted debug for a
reason, but the rule is "v(5) is what is useful for debugging".  If one
component drowns everyone else out, then ultimately no one can debug at
v(5).

**Comment by deads2k** [comment]
This just helped me solve a problem with https://github.com/openshift/origin/pull/16009 5 minutes ago.

We're logging the API server.  I'm open to trying to find a way to gate it easily like we could jsr 47 components, but it's incredibly useful to have and got added to fix an actual problem, not a "gee, this may be interesting some day".

**Comment by smarterclayton** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/14558/test_pull_request_origin_integration/6628/
is 5x longer than every other person on the team needs.  I know it helps
you, but it hurts everyone else.  I appreciate your desire to have it
available, but it can't come at the expense of everyone else's efficiency.

**Comment by smarterclayton** [comment]
As per in person discussion, we're going to drop to loglevel=4 and make
people log important stuff at 4.
