### ISSUE TITLE
Error waiting for fluentd pod (openshift ansible logging)

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#16005]
Apparently slow infrastructure causing a flake:

```
[ERROR] PID 36012: hack/testing/entrypoint.sh:40: `fpod=$( get_running_pod fluentd )` exited with status 1.

...

[ERROR] found 0 for project .operations message 2e82170f-3b85-4c84-9f52-69e45e2a0860 - expected 1
{
    "_shards": {
        "failed": 0,
        "successful": 1,
        "total": 1
    },
    "count": 0
}
{
    "_shards": {
        "failed": 0,
        "successful": 1,
        "total": 1
    },
    "hits": {
        "hits": [],
        "max_score": null,
        "total": 0
    },
    "timed_out": false,
    "took": 1
}
[ERROR] wait_for_fluentd_to_catch_up: not found 1 record project .operations for 2e82170f-3b85-4c84-9f52-69e45e2a0860 after 300 seconds
[ERROR] Checking journal for 2e82170f-3b85-4c84-9f52-69e45e2a0860...
[ERROR] Found 2e82170f-3b85-4c84-9f52-69e45e2a0860 in journal
[ERROR] PID 106936: test/viaq-data-model.sh:624: `return $rc` exited with status 1.
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_logging/757/console

Seen in https://github.com/openshift/openshift-ansible/pull/4570 / https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/928/

**Comment by rhcarvalho** [comment]
@jcantrill FYI if this interests your team, otherwise sorry for bothering ;)

**Comment by jcantrill** [comment]
This is caused as discovered by @richm when fluentd does not have enough cpu resources.

**Comment by richm** [comment]
@jcantrill That should have been fixed @rhcarvalho what version of the test are you using?

**Comment by rhcarvalho** [comment]
@richm it was in the openshift-ansible merge queue, I don't know what version.

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/928/

**Comment by richm** [comment]
ok - I think it is a test flake - try it again

**Comment by jcantrill** [comment]
Closing related to the amount of CPU given to fluent.  Please reopen if we see otherwise
