### ISSUE TITLE
Mounts have different semantics depending on if the directory already exists.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#16011]
[provide a description of the issue]

##### Version

oc v3.2.0.46-1-g3fab54d
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
On an openshift cluster:

1. Mount a file X into /run/secrets
2. Mount the exact same X file into /run/secrets2

Note that the file is in ` /run/secrets/X/X` in (1) and  `/run/secrets/X` in (2).

##### Current Result
```
/usr/local/tomcat $ ls -altrh /run/secrets2/HUB_POSTGRES_ADMIN_PASSWORD_FILE
lrwxrwxrwx    1 root     root          39 Aug 28 16:34 /run/secrets2/HUB_POSTGRES_ADMIN_PASSWORD_FILE -> ..data/HUB_POSTGRES_ADMIN_PASSWORD_FILE
/usr/local/tomcat $ ls -altrh /run/secrets/HUB_POSTGRES_ADMIN_PASSWORD_FILE
total 0
lrwxrwxrwx    1 root     root          39 Aug 28 16:34 HUB_POSTGRES_ADMIN_PASSWORD_FILE -> ..data/HUB_POSTGRES_ADMIN_PASSWORD_FILE
lrwxrwxrwx    1 root     root          31 Aug 28 16:34 ..data -> ..8988_28_08_12_34_44.628856968
drwxr-sr-x    2 root     10004400      46 Aug 28 16:34 ..8988_28_08_12_34_44.628856968
drwxrwsrwx    3 root     10004400      99 Aug 28 16:34 .
drwxr-xr-x    6 root     root         142 Aug 28 16:34 ..
```
##### Expected Result

ls -altrh /run/secrets2/HUB_POSTGRES_ADMIN_PASSWORD_FILE and
ls -altrh /run/secrets/HUB_POSTGRES_ADMIN_PASSWORD_FILE

Should both list a single file, not a dir.

##### Additional Information

I suspect this is a kubernetes 1.4 issue  ? I dont recall seeing it being the case in openshift 3.6 when running Minishift.  I do see it on OSE though.  I think it has to do w/ the fact that openshift likes to use /run/secrets.  So this only happens when the dir. ALREADY exists.

**Comment by jayunit100** [comment]
Actually, closing for now, I think this is fixed and is a kube issue.

**Comment by jayunit100** [comment]
Just confirmed, on an openshift cluster, the exact same mount directive:

```
 - mountPath: /run/secrets/HUB_POSTGRES_USER_PASSWORD_FILE
          name: hpup-user
          subPath: HUB_POSTGRES_USER_PASSWORD_FILE
```

```
/usr/local/tomcat $ ls /run/secrets                                                                                                                   
HUB_POSTGRES_ADMIN_PASSWORD_FILE  HUB_POSTGRES_USER_PASSWORD_FILE  
```

**Comment by jayunit100** [comment]
@rootfs filesystem and @rhatdan security folks ...    any thoughts on how we should mount files into /run/secrets  ?

**Comment by rhatdan** [comment]
/run/secrets is a special directory which is created by docker to container the RHEL secrets code.  It is probably some interaction here which is causing the issue.

**Comment by jayunit100** [comment]
I see it in OSE but not in origin as I recall.
