### ISSUE TITLE
RBAC Migration Followup #23: Investigate distinctions between different user/group kinds

### ISSUE THREAD

**Issue by tiran** [openshift/origin#16032]
RBAC does not distinguish between ``UserKind`` and ``SystemUserKind``. Both kinds are mapped to ``APIGroup = rbac.GroupName`` and ``Kind = rbac.UserKind``. The same is true for ``GroupKind`` and ``SystemGroupKind``. We need to confirm that the distinction between the different kinds still works as we expected. Further more, does it make sense to upstream the distinction?

@openshift/sig-security

**Comment by liggitt** [comment]
> We need to confirm that the distinction between the different kinds still works as we expected. Further more, does it make sense to upstream the distinction?

No, the distinction is not meaningful upstream.

**Comment by enj** [comment]
@liggitt @deads2k from what I gather we use this distinction in:

1. Impersonation
2. Role binding restriction admission

Are you aware of any other use cases?  I do not think the above two require any changes.

**Comment by simo5** [comment]
@liggitt @deads2k @enj given work ongoing with the impersonation and RBR, do we need to do anything about this distinction ? Or should we just close this issue as resolved ?

**Comment by deads2k** [comment]
> @liggitt @deads2k @enj given work ongoing with the impersonation and RBR, do we need to do anything about this distinction ? Or should we just close this issue as resolved ?

I haven't yet looked at rolebindingrestrictions.

**Comment by enj** [comment]
There is logic in `pkg/authorization/admission/restrictusers/subjectchecker.go` that may need to be addressed.

**Comment by enj** [comment]
#16155 covers the impersonation bits, but we have not addressed RBR.

**Comment by simo5** [comment]
So I did a more fine grained review of subjectcheker, and it looks to me the only reason why SystemUsers/Groups are handled specially is to skip checks for things those user "cannot have".
so it looks completely safe to me to just remove those special checks.
I will do so in a PR that also converts the file to use rbac.Subject types instead of the olf kapi.ObjectReference stuff
