### ISSUE TITLE
Build failed push image to registry with 500 internal server err

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#16051]
[provide a description of the issue]
Build failed push image to registry with 500 internal server err
##### Version
[provide output of the `openshift version` or `oc version` command]
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
etcd 3.2.1
This is an origin rpm pkg installed cluster with:
```
origin-clients-3.6.0-1.0.c4dd4cf.x86_64
origin-master-3.6.0-1.0.c4dd4cf.x86_64
centos-release-openshift-origin36-1-1.el7.centos.noarch
origin-node-3.6.0-1.0.c4dd4cf.x86_64
origin-docker-excluder-3.6.0-1.0.c4dd4cf.noarch
tuned-profiles-origin-node-3.6.0-1.0.c4dd4cf.x86_64
origin-sdn-ovs-3.6.0-1.0.c4dd4cf.x86_64
origin-excluder-3.6.0-1.0.c4dd4cf.noarch
origin-3.6.0-1.0.c4dd4cf.x86_64
```

##### Steps To Reproduce
1. [step 1]
oc new-app https://github.com/openshift/ruby-ex

##### Current Result
Failed push
##### Expected Result
Succeed
##### Additional Information
logs for build:

```
Pushing image docker-registry.default.svc:5000/haowang/ruby-ex:latest ...
Pushed 0/9 layers, 1% complete
Pushed 1/9 layers, 44% complete
Pushed 2/9 layers, 25% complete
Pushed 3/9 layers, 35% complete
Pushed 4/9 layers, 46% complete
Pushed 8/9 layers, 99% complete
Pushed 9/9 layers, 100% complete
Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: received unexpected HTTP status: 500 Internal Server Error
```
logs for registry:
```
time="2017-08-30T08:48:49.811499595Z" level=debug msg="filesystem.Stat(\"/docker/registry/v2/blobs/sha256/e0/e0a2cddebe2358a47455a3c492bb92583ee1f3ca31d3aa90781d65a06472cad6/data\")" go.version=go1.7.6 http.request.host="docker-registry.default.svc:5000" http.request.id=18ff1ae8-4aee-4d54-9da0-a5d2996b5514 http.request.method=HEAD http.request.remoteaddr="10.2.6.1:56244" http.request.uri="/v2/haowang1/ruby-ex/blobs/sha256:e0a2cddebe2358a47455a3c492bb92583ee1f3ca31d3aa90781d65a06472cad6" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(go-dockerclient)" instance.id=a7fc1648-ab73-4749-8d8a-8ddf2a81c2d7 openshift.auth.user="system:serviceaccount:haowang1:builder" openshift.logger=registry trace.duration=18.129µs trace.file="/openshifttmp/openshift/build-rpm-release/tito/rpmbuild-originlTBPIz/BUILD/origin-3.6.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/openshift/origin/vendor/github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=6cefdbb9-3fac-4f23-95d4-f06151720343 trace.line=137 vars.digest="sha256:e0a2cddebe2358a47455a3c492bb92583ee1f3ca31d3aa90781d65a06472cad6" vars.name="haowang1/ruby-ex" 
time="2017-08-30T08:48:49.811542362Z" level=debug msg="(*remoteBlobGetterService).Stat: starting with dgst=sha256:e0a2cddebe2358a47455a3c492bb92583ee1f3ca31d3aa90781d65a06472cad6" go.version=go1.7.6 http.request.host="docker-registry.default.svc:5000" http.request.id=18ff1ae8-4aee-4d54-9da0-a5d2996b5514 http.request.method=HEAD http.request.remoteaddr="10.2.6.1:56244" http.request.uri="/v2/haowang1/ruby-ex/blobs/sha256:e0a2cddebe2358a47455a3c492bb92583ee1f3ca31d3aa90781d65a06472cad6" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(go-dockerclient)" instance.id=a7fc1648-ab73-4749-8d8a-8ddf2a81c2d7 openshift.auth.user="system:serviceaccount:haowang1:builder" openshift.logger=registry vars.digest="sha256:e0a2cddebe2358a47455a3c492bb92583ee1f3ca31d3aa90781d65a06472cad6" vars.name="haowang1/ruby-ex" 
10.2.6.1 - - [30/Aug/2017:08:48:49 +0000] "HEAD /v2/haowang1/ruby-ex/blobs/sha256:e0a2cddebe2358a47455a3c492bb92583ee1f3ca31d3aa90781d65a06472cad6 HTTP/1.1" 500 456 "" "docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(go-dockerclient)"
time="2017-08-30T08:48:49.814083918Z" level=error msg="failed to get image stream: the server has asked for the client to provide credentials (get imageStreams ruby-ex)" go.version=go1.7.6 instance.id=a7fc1648-ab73-4749-8d8a-8ddf2a81c2d7 openshift.logger=registry 
time="2017-08-30T08:48:49.814185687Z" level=error msg="response completed with error" err.code=unknown err.detail="denied: requested access to the resource is denied" err.message="unknown error" go.version=go1.7.6 http.request.host="docker-registry.default.svc:5000" http.request.id=18ff1ae8-4aee-4d54-9da0-a5d2996b5514 http.request.method=HEAD http.request.remoteaddr="10.2.6.1:56244" http.request.uri="/v2/haowang1/ruby-ex/blobs/sha256:e0a2cddebe2358a47455a3c492bb92583ee1f3ca31d3aa90781d65a06472cad6" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(go-dockerclient)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=10.292634ms http.response.status=500 http.response.written=456 instance.id=a7fc1648-ab73-4749-8d8a-8ddf2a81c2d7 openshift.auth.user="system:serviceaccount:haowang1:builder" openshift.logger=registry vars.digest="sha256:e0a2cddebe2358a47455a3c492bb92583ee1f3ca31d3aa90781d65a06472cad6" vars.name="haowang1/ruby-ex" 
```
dc

```
{
    "apiVersion": "v1",
    "kind": "DeploymentConfig",
    "metadata": {
        "creationTimestamp": "2017-08-29T09:44:35Z",
        "generation": 3,
        "labels": {
            "docker-registry": "default"
        },
        "name": "docker-registry",
        "namespace": "default",
        "resourceVersion": "28136",
        "selfLink": "/oapi/v1/namespaces/default/deploymentconfigs/docker-registry",
        "uid": "ab038682-8c9e-11e7-aef4-fa163e544fa9"
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "docker-registry": "default"
        },
        "strategy": {
            "activeDeadlineSeconds": 21600,
            "resources": {},
            "rollingParams": {
                "intervalSeconds": 1,
                "maxSurge": "25%",
                "maxUnavailable": "25%",
                "timeoutSeconds": 600,
                "updatePeriodSeconds": 1
            },
            "type": "Rolling"
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "docker-registry": "default"
                }
            },
            "spec": {
                "containers": [
                    {
                        "env": [
                            {
                                "name": "REGISTRY_HTTP_ADDR",
                                "value": ":5000"
                            },
                            {
                                "name": "REGISTRY_HTTP_NET",
                                "value": "tcp"
                            },
                            {
                                "name": "REGISTRY_HTTP_SECRET",
                                "value": "wI9VDPTdCNqetNG9+hBL0OvGqdos7SWADsk387fFPF0="
                            },
                            {
                                "name": "REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ENFORCEQUOTA",
                                "value": "false"
                            },
                            {
                                "name": "OPENSHIFT_DEFAULT_REGISTRY",
                                "value": "docker-registry.default.svc:5000"
                            },
                            {
                                "name": "REGISTRY_HTTP_TLS_KEY",
                                "value": "/etc/secrets/registry.key"
                            },
                            {
                                "name": "REGISTRY_HTTP_TLS_CERTIFICATE",
                                "value": "/etc/secrets/registry.crt"
                            }
                        ],
                        "image": "openshift/origin-docker-registry:v3.6.0",
                        "imagePullPolicy": "IfNotPresent",
                        "livenessProbe": {
                            "failureThreshold": 3,
                            "httpGet": {
                                "path": "/healthz",
                                "port": 5000,
                                "scheme": "HTTPS"
                            },
                            "initialDelaySeconds": 10,
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "timeoutSeconds": 5
                        },
                        "name": "registry",
                        "ports": [
                            {
                                "containerPort": 5000,
                                "protocol": "TCP"
                            }
                        ],
                        "readinessProbe": {
                            "failureThreshold": 3,
                            "httpGet": {
                                "path": "/healthz",
                                "port": 5000,
                                "scheme": "HTTPS"
                            },
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "timeoutSeconds": 5
                        },
                        "resources": {
                            "requests": {
                                "cpu": "100m",
                                "memory": "256Mi"
                            }
                        },
                        "securityContext": {
                            "privileged": false
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "volumeMounts": [
                            {
                                "mountPath": "/registry",
                                "name": "registry-storage"
                            },
                            {
                                "mountPath": "/etc/secrets",
                                "name": "registry-certificates"
                            }
                        ]
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "nodeSelector": {
                    "registry": "enabled",
                    "role": "node"
                },
                "restartPolicy": "Always",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "serviceAccount": "registry",
                "serviceAccountName": "registry",
                "terminationGracePeriodSeconds": 30,
                "volumes": [
                    {
                        "emptyDir": {},
                        "name": "registry-storage"
                    },
                    {
                        "name": "registry-certificates",
                        "secret": {
                            "defaultMode": 420,
                            "secretName": "registry-certificates"
                        }
                    }
                ]
            }
        },
        "test": false,
        "triggers": [
            {
                "type": "ConfigChange"
            }
        ]
    },
    "status": {
        "availableReplicas": 1,
        "conditions": [
            {
                "lastTransitionTime": "2017-08-30T08:41:21Z",
                "lastUpdateTime": "2017-08-30T08:41:21Z",
                "message": "replication controller \"docker-registry-2\" has failed progressing",
                "reason": "ProgressDeadlineExceeded",
                "status": "False",
                "type": "Progressing"
            },
            {
                "lastTransitionTime": "2017-08-30T08:42:27Z",
                "lastUpdateTime": "2017-08-30T08:42:27Z",
                "message": "Deployment config has minimum availability.",
                "status": "True",
                "type": "Available"
            }
        ],
        "details": {
            "causes": [
                {
                    "type": "Manual"
                }
            ],
            "message": "manual change"
        },
        "latestVersion": 2,
        "observedGeneration": 3,
        "readyReplicas": 1,
        "replicas": 1,
        "unavailableReplicas": 0,
        "updatedReplicas": 0
    }
}

```

**Comment by wanghaoran1988** [comment]
https://paste.fedoraproject.org/paste/XQjXflklDUz0943OiQmX3Q

**Comment by mfojtik** [comment]
is this a multi-master environment? if so can you attach the corresponding master logs (the 403 errors in particular)

**Comment by wanghaoran1988** [comment]
No, one cluster, one node

**Comment by legionus** [comment]
@wanghaoran1988 For some reason, some queries to master API fail due to the lack of permissions.
Can you grep the master log for errors ?

**Comment by wanghaoran1988** [comment]
this is the master log, I am not sure what's the error for the pushed failed problem, but I seem some certificates verification problem.
https://paste.fedoraproject.org/paste/mo0~5zpjRmnQ7zuPNBbaGw

**Comment by coffeetalkh** [comment]
Same issue here and this is my scc configuration:

```
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
apiVersion: v1
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:nodes
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'privileged allows access to all privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is the most relaxed SCC and should be used
      only for cluster administration. Grant with caution.'
  creationTimestamp: 2017-08-29T11:39:48Z
  name: privileged
  resourceVersion: "1351"
  selfLink: /api/v1/securitycontextconstraints/privileged
  uid: c35c4b35-8cae-11e7-b6dc-005056b601be
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:build-controller
- system:serviceaccount:default:pvinstaller
- system:serviceaccount:default:registry
- system:serviceaccount:default:router
- admin
- system:admin
volumes:
- '*'
```

**Comment by malagant** [comment]
Well, It's all about permissions as I found out with having the same trouble today.
I found this: https://access.redhat.com/solutions/2173071
It's all about permissions on the docker directory for the registration.
The solution is for 3.1 but worked for me using 3.6

So glad I found it.

**Comment by do3cc** [comment]
I have the same problem with multi master setup, the solution from @malagant does not help, the permissions are correct.
I do not see any errors in the master logs.

**Comment by sudhirpandey** [comment]
facing exactly same issue here in multi master setup, it used to just work fine since we deployed, now we are getting this 
The logs on master seems to produce something like this
```
GET /oapi/v1/namespaces/core-dev2/imagestreams/qm-ps: (268.325µs) 401 [[dockerregistry/v1.5.1+7b451fc (linux/amd64) openshift/0ef5dda]
```

The build was initiated and is done by service account builder. Default policy in the project is looks okey too
```
RoleBinding[system:image-pullers]:
Role:			system:image-puller
Users:			<none>
Groups:			system:serviceaccounts:core-dev2
Subjects:		<none>
```

```
oc get sa
NAME       SECRETS   AGE
builder    3         1y
default    2         1y
deployer   2         1y
```
Not sure what we are missing , especially given that it used to just work fine.

**Comment by sudhirpandey** [comment]
So this is how we got over this issue, its a weird solution though
1) Copy and create deployment config generated from `oadm registry -o yaml` 
2) Then we launched (parallel) registry pod  using the above deployment config
```
 oc get dc
NAME               REVISION   DESIRED   CURRENT   TRIGGERED BY
docker-registry    25         1         1         config
docker-registry2   2          1         1         config
```
3)edited the docker registry service to use new pod adjusting selector in service, ( tried the new build, it worked just fine)

4) We originally had nfs backed persistance storage in for dockerregistry. So we edited the newly deployed docker registry config to use same  persistance volume claim. ( this time as well the build proceeded without any trouble)

so we left the new deployment configs (docker-registry2) , and phased out the old  deployment configs( docker-registry)

**Comment by legionus** [comment]
@bparees I guess we need to reassign this issue to master or security team.

**Comment by bparees** [comment]
@mfojtik Seems like either the registry's SA credentials aren't being respected, or the api server is having problems validating credentials in general.

**Comment by nvnvashisth** [comment]
Even I am facing the similar. I am using OC version 3.7

[root@cbc upgrades]# oc version
oc v3.7.23
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://cbc
openshift v3.7.23
kubernetes v1.7.6+a08f5eeb62

Cloning "https://github.com/nvnvashisth/phpMyAdmin.git " ...
--
  | Commit:	eedcdfa4027208ad3bec6301821b043316368cc2 (Updated the config file)
  | Author:	nvnvashisth <nvnvashisth@gmail.com>
  | Date:	Wed Mar 28 12:02:48 2018 +0200
  | ---> Installing application source...
  | Found 'composer.json', installing dependencies using composer.phar...
  | Downloading https://getcomposer.org/installer , attempt 1/6
  | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  | Dload  Upload   Total   Spent    Left  Speed
  | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 100  298k  100  298k    0     0   382k      0 --:--:-- --:--:-- --:--:--  382k
  | All settings correct for using Composer
  | Downloading...
  | Composer (version 1.6.3) successfully installed to: /opt/app-root/src/composer.phar
  | Use it: php composer.phar
  | Loading composer repositories with package information
  | Installing dependencies (including require-dev) from lock file
  | Nothing to install or update
  | Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
  | Generating optimized autoload files
  | => sourcing 20-copy-config.sh ...
  | ---> 11:09:29     Processing additional arbitrary httpd configuration provided by s2i ...
  | => sourcing 00-documentroot.conf ...
  | => sourcing 50-mpm-tuning.conf ...
  | => sourcing 40-ssl-certs.sh ...
  | Pushing image docker-registry.default.svc:5000/openshift/myadmin:latest ...
  | Registry server Address:
  | Registry server User Name: serviceaccount
  | Registry server Email: serviceaccount@example.org
  | Registry server Password: <<non-empty>>
  | error: build error: Failed to push image: Get https://docker-registry.default.svc:5000/v1/_ping:  http: server gave HTTP response to HTTPS client


Any idea about this?

**Comment by bparees** [comment]
@nvnvashisth your problem is that your docker daemon is not setup to treat the internal registry (docker-registry.default.svc:5000) as insecure.  Either secure the internal registry, or configure your docker daemon on all nodes to treat it as insecure.

**Comment by nvnvashisth** [comment]
I have done both entries with IP and hostname in the daemon.json, but it throws up same error.
Entry done in both master and node. Below is the entry

[root@cbc-rh-os-m01 docker]# more daemon.json
{
"insecure-registries" : ["172.30.47.17:5000"]
}
{
"insecure-registries" : ["docker-registry.default.svc:5000"]
}


and error changed a bit after redeployment.


Downloading https://getcomposer.org/installer , attempt 1/6
--
  | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  | Dload  Upload   Total   Spent    Left  Speed
  | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 100  298k  100  298k    0     0   317k      0 --:--:-- --:--:-- --:--:--  317k
  | All settings correct for using Composer
  | Downloading...
  | Composer (version 1.6.3) successfully installed to: /opt/app-root/src/composer.phar
  | Use it: php composer.phar
  | Loading composer repositories with package information
  | Installing dependencies (including require-dev) from lock file
  | Nothing to install or update
  | Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
  | Generating optimized autoload files
  | => sourcing 20-copy-config.sh ...
  | ---> 14:21:58     Processing additional arbitrary httpd configuration provided by s2i ...
  | => sourcing 00-documentroot.conf ...
  | => sourcing 50-mpm-tuning.conf ...
  | => sourcing 40-ssl-certs.sh ...
  | Pushing image docker-registry.default.svc:5000/openshift/myadmin:latest ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Warning: Push failed, retrying in 5s ...
  | Registry server Address:
  | Registry server User Name: serviceaccount
  | Registry server Email: serviceaccount@example.org
  | Registry server Password: <<non-empty>>
  | error: build error: Failed to push image: After retrying 6 times, Push image still failed due to error: Get https://docker-registry.default.svc:5000/v1/_ping:  dial tcp 172.30.47.17:5000: getsockopt: connection refused

**Comment by bparees** [comment]
first off, i'm pretty sure this is not the right way to configure things:

```
[root@cbc-rh-os-m01 docker]# more daemon.json
{
"insecure-registries" : ["172.30.47.17:5000"]
}
{
"insecure-registries" : ["docker-registry.default.svc:5000"]
}
```

you should have a single insecure-registries entry with an array of values.


As for your new failure, that implies the registry is not actually running.  Confirm that your registry pods are still running, particularly since you restarted your docker daemon to pick up the config change.

**Comment by nvnvashisth** [comment]
Hello Ben,

Apologies for sending update this late.
So now I have fixed the registry.

Coming back to original error which I faced in start which is below.

 Pushing image docker-registry.default.svc:5000/openshift/myadmin:latest ...
  | Registry server Address:
  | Registry server User Name: serviceaccount
  | Registry server Email: serviceaccount@example.org
  | Registry server Password: <>
  | error: build error: Failed to push image: Get https://docker-registry.default.svc:5000/v1/_ping: http: server gave HTTP response to HTTPS client

and you said " configure your docker daemon on all nodes to treat it as insecure."

So at the moment, I have just configured IP in my daemon.json, am I supposed 
to make the entry of hostname too in the json file.


Selectors:docker-registry=default
Type:ClusterIP
IP:172.30.47.17
Hostname:docker-registry.default.svc 

Also you said "you should have a single insecure-registries entry with an array of values."

Could you please confirm if below is the format of updating the json with both IP and hostname. 

[root@cbc-rh-os-m01 docker]# more daemon.json
{
"insecure-registries" : ["172.30.47.17:5000", "docker-registry.default.svc:5000"]
}

**Comment by bparees** [comment]
> , am I supposed to make the entry of hostname too in the json file.

yes (you should probably only need the hostname, actually, but having both won't hurt)

> Could you please confirm if below is the format of updating the json with both IP and hostname

yes that looks right.

**Comment by kingkeivn** [comment]
@MacThrawn 
What changs have been made to this configuration?can you go into more detail?And in which file ?Thank you .
