### ISSUE TITLE
register TSB via TSB template

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16075]
Currently oc cluster up makes a direct call to the SC to register the TSB.  This should instead be handled by the TSB template that installs the other pieces of the template.  It should also properly setup the TLS certs (today it registers as skipTLS=true).

There is at least one challenge here which is that if the TSB registers w/ the broker before the TSB is actually available, the SC will hit the TSB, fail, and then wait 5 mins before trying again.  That is going to lead to a bad experience when doing cluster up since the TSB content won't show up in the web console for 5 minutes.

So this may need to be yet another template, which is only provisioned once the TSB is up.

@deads2k @jim-minter

**Comment by deads2k** [comment]
I think this issue involves @sdodson and @ewolinetz too.

@bparees is there any reason to avoid an installation order that goes
 1. openshift core
 2. TSB - wait for ready
 3. SC - wait for ready
 4. SC wiring?

If you happen to have a `.yaml` file that shows what we're creating, my memory says there's not actually any information that must flow from TSB to SC-wiring, so a TSB update (or removal) doesn't really matter.  It would just be  dangling broker ref.

**Comment by bparees** [comment]
@deads2k we can't create the broker resource(which is the thing that kicks off the SC trying to access the TSB) until the SC is registered w/ the aggregator, right?

So there is a dependent ordering of:
1) sc broker resource is registered (implies SC is up)
2) tsb is up
3) create tsb broker resource (results in SC calling TSB)

**Comment by deads2k** [comment]
> @deads2k we can't create the broker resource(which is the thing that kicks off the SC trying to access the TSB) until the SC is registered w/ the aggregator, right?

I think that's the install path I described, but on a TSB update (bumping the image, changing the config, or some such), the broker resource doesn't need to be updated, right?

**Comment by bparees** [comment]
> I think that's the install path I described

well it's also the install path i originally described, so perhaps we're talking past each other?

>  on a TSB update (bumping the image, changing the config, or some such), the broker resource doesn't need to be updated, right?

correct.

**Comment by deads2k** [comment]
Based on in person discussion, we're leaning towards a separate folder under `/install` that will contain broker resources.  The templates in there may be special snowflakes in terms of "when do I create these", but we don't want them in the `/install/tsb` folder since everything in that folder should be contained and not have a dependency on the SC.  The SC and every broker should be installable in parallel.
