### ISSUE TITLE
Associate user with scc using a manifest?

### ISSUE THREAD

**Issue by fabiand** [openshift/origin#16087]
We are aiming to deploy KubeVirt on minishift with manifests-only thus no cli interaction.
So far we can deploy everything, there are just issues when we get to associating the user/serviceaccount with an scc, currently this needs to be done on the cli using
```
oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt
```
The question is if this command can also be performed with manifests only

For all details look at the end of http://adam.younglogic.com/2017/08/deploying-kubevirt-on-origin-master/

##### Version
master

##### Steps To Reproduce
1. oc create serviceaccount -n kube-system kubevirt
2. oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt

##### Current Result
clis needed

##### Expected Result
can all be done from manifests

**Comment by pweil-** [comment]
There is not currently a way to do this via something like templates.  At this point it would need to be scripted via an ansible playbook or some other mechanism.

**Comment by enj** [comment]
I suppose you could create a copy of the privileged SCC with the SA you need to grant it to.  Sounds like a terrible idea though, and I am not sure if it will work.  This should go away when we switch to PSP.

**Comment by fabiand** [comment]
I'm now actually looking that I add my user to a role which already has the permission to perform privileged operations.

**Comment by liggitt** [comment]
A user cannot be added to an existing SCC with just a manifest today.

Currently, the only way to grant access to an SCC using a manifest is to define a new SCC containing only the desired user and create it via a manifest.
