### ISSUE TITLE
Investigate accessing /etc/docker/certs.d from image importer, registry

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16084]
It should be possible for importer and registry to gracefully reuse the host's local registry client certs if specified to abstract connecting to client-cert protected registries.  These tend to be "host local" and the container engine accesses them abstractly (because they represent part of the infrastructure).

Per import / periodically when image import controller runs it should look at /etc/docker/certs.d and glob the certs into the transports it uses for importing.  This is better than looking at config because these certificates are part of infrastructure, not cluster configuration, and having multiple paths requires multiple rotation paths (we want to have the host rotation be successful for the cluster).  If in the future the controllers run in a container we would consider host mounting that directory.

For the registry, a hostPath mount of that directory into the same directory in the registry is also possible, or an admin could work around that by simply putting the cert in a secret and mounting that into a container.  It's not a requirement that we implement this for pullthrough for step one, as long as it is possible in the future.  Either way, reusing the same code as above would be ideal, and having it well abstracted.  No need for additional config here either.

Goal is to demonstrate any other obstacles that would prevent this from working or highlight gaps the various code flows.

**Comment by bparees** [comment]
Thanks @smarterclayton, seems straightforward to me.  But once we resolve any questions/concerns @dmage and @legionus have, we will turn this into a trello card and queue it up asap.

**Comment by dmage** [comment]
We can reuse [ReadCertsDirectory](https://godoc.org/github.com/moby/moby/registry#ReadCertsDirectory) from moby/moby.

**Comment by bparees** [comment]
@smarterclayton i heard a rumor you and bbreard found some holes/blockers in this plan yesterday (from the registry side)....?

**Comment by smarterclayton** [comment]
No?

**Comment by bparees** [comment]
converted to trello: https://trello.com/c/fFU482Al
