### ISSUE TITLE
'Write failed: Broken pipe' while 'Trying to pull repository docker.io/openshift/origin-release'

### ISSUE THREAD

**Issue by mtnbikenc** [openshift/origin#16114]
Seen this several times and have not found a related issue.

```
+ hack/env OS_ONLY_BUILD_PLATFORMS=linux/amd64 hack/build-rpm-release.sh
[INFO] Pulling the openshift/origin-release:golang-1.8 image to update it...
Trying to pull repository registry.access.redhat.com/openshift/origin-release ... 
Trying to pull repository docker.io/openshift/origin-release ... 
golang-1.8: Pulling from docker.io/openshift/origin-release
Digest: sha256:0f1705f538fc3096a32b8b3111d5c7cb2eabc51b3d4a027c20ca97f46ff39d6d
Write failed: Broken pipe
```
https://github.com/openshift/openshift-ansible/pull/5287#issuecomment-326703819

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/971/consoleFull#147027785258b6e51eb7608a5981914356

**Comment by mfojtik** [comment]
guess we need docker daemon logs to know what is going on there.

**Comment by jwhonce** [comment]
@mtnbikenc We need the docker daemon logs (preferably with the daemon running -D).  Also which rpm for docker are you using?

**Comment by mtnbikenc** [comment]
@jwhonce This was happening in CI, not my local test systems.  I will check the logs in the job linked above and see if I can find which version of docker was installed.  Do you know if docker daemon logs are captured as part of the CI job?

**Comment by mtnbikenc** [comment]
Docker version: `docker-2:1.12.6-48.git0fdc778.el7.x86_64`

**Comment by jwhonce** [comment]
@mtnbikenc Are you still seeing the issue with newer docker builds?  Additionally, were you ever able to capture a docker log during an incident?

**Comment by mtnbikenc** [comment]
@jwhonce I'm not seeing this particular issue in CI any longer.  I was not able to get logs because they were removed before I could track down where they were.
