### ISSUE TITLE
Descriptions in image streams for MySQL need to be updated with better URL.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#16121]
The description in MySQL image stream uses a URL which is outdated.

##### Version

oc v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f

##### Steps To Reproduce

Run:

```
oc describe is/mysql -n openshift
```

This will output descriptions for images like:

```
Provides a MySQL 5.7 database on CentOS 7. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/mysql-container/tree/master/5.7/README.md.
```

##### Current Result

Following the URL leads you to a page which contains:

```
root/usr/share/container-scripts/mysql/README.md
```

That path is not clickable and so is hard to then find the actual documentation.

##### Expected Result

The description should instead use:

https://github.com/sclorg/mysql-container/blob/master/5.7/root/usr/share/container-scripts/mysql/README.md

Similar change for other versions of mysql image.

##### Additional Information

Should perhaps double check whether PostgreSQL images have been changed as well.

**Comment by mfojtik** [comment]
CC @hhorak

**Comment by bparees** [comment]
@hhorak the imagestreams that need to be updated are here:
https://github.com/openshift/origin/tree/master/examples/image-streams

both the rhel and centos ones, for all the db images.

**Comment by bparees** [comment]
@GrahamDumpleton fixing here: https://github.com/sclorg/mysql-container/pull/236
ptal.

**Comment by bparees** [comment]
@GrahamDumpleton and https://github.com/sclorg/postgresql-container/pull/290
