### ISSUE TITLE
oc explain crd/volumesnapshot/volumesnapshotdata yields error

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#16127]
```
$ oc explain crd
error: group apiextensions.k8s.io has not been registered
```

On a cluster where we already run CRDs
```
$ oc version
oc v3.6.0-rc.0+f8071e8-362
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

openshift v3.7.0-alpha.1+70fcade-21
kubernetes v1.7.0+695f48a16f
```

@openshift/cli-review @sttts @deads2k 

/kind bug

**Comment by deads2k** [comment]
@fabianofranz Based on the error, it looks like the `kubectl explain` only works on groups registered into a group registry.  That doesn't work well in general.

**Comment by liangxia** [comment]
$ oc explain volumesnapshot
error: group volume-snapshot-data.external-storage.k8s.io has not been registered

$ oc explain volumesnapshotdata
error: group volume-snapshot-data.external-storage.k8s.io has not been registered

oc v3.7.0-0.181.0
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

**Comment by nikhita** [comment]
Commented upstream: https://github.com/kubernetes/kubernetes/issues/49465#issuecomment-358080250.

**Comment by sttts** [comment]
@nikhita the linked issue is "only about" the CRD and APIService types that are implemented via delegation in kube-apiserver. It's not even about the CRD instances. But solving the former probably also solves the later.

**Comment by nikhita** [comment]
> But solving the former probably also solves the later.

Yes, it does. :)
