### ISSUE TITLE
MySQL Pod in Wordpress Example Fails

### ISSUE THREAD

**Issue by imesh** [openshift/origin#16134]
It seems like the MySQL pod in Wordpress example is failing to start due to a permission issue with the following error:

https://github.com/openshift/origin/tree/v3.6.0/examples/wordpress

```
---> 03:46:56     Processing MySQL configuration files ...
--
  | ---> 03:46:56     Initializing database ...
  | ---> 03:46:56     Running mysql_install_db ...
  | mkdir: cannot create directory '/var/lib/mysql/data': Permission denied
  | chmod: cannot access '/var/lib/mysql/data/mysql': Permission denied
  | mkdir: cannot create directory '/var/lib/mysql/data': Permission denied
  | chmod: cannot access '/var/lib/mysql/data/test': Permission denied
  | 170905  3:46:56 [Note] /opt/rh/mysql55/root/usr/libexec/mysqld (mysqld 5.5.45) starting as process 43 ...
  | 170905  3:46:56 [Warning] Can't create test file /var/lib/mysql/data/mysql.lower-test
  | 170905  3:46:56 [Warning] Can't create test file /var/lib/mysql/data/mysql.lower-test
  | /opt/rh/mysql55/root/usr/libexec/mysqld: Can't change dir to '/var/lib/mysql/data/' (Errcode: 13)
  | 170905  3:46:56 [ERROR] Aborting
```

#### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://192.168.99.103:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

#### Steps To Reproduce
oc create -f examples/wordpress/pvc-wp.yaml 
oc create -f examples/wordpress/pvc-mysql.yaml
oc create -f examples/wordpress/pod-mysql.yaml

#### Current Result
MySQL pod fails to start with the above error.

#### Expected Result
MySQL pod to be started with the attached volume mount.

#### Additional Information
ERROR: [DCli0015 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'default/127-0-0-1:8443/system:admin':
       The server URL is 'https://127.0.0.1:8443'
       The user authentication is 'system:admin/127-0-0-1:8443'
       The current project is 'default'
       (*url.Error) Get https://127.0.0.1:8443/api: dial tcp 127.0.0.1:8443: getsockopt: connection refused
       Diagnostics does not have an explanation for what this means. Please report this error so one can be added.

**Comment by imesh** [comment]
The issue was with the storage, created two 5 GB host path volumes and the issue was solved.

**Comment by pennpeng** [comment]
same issue when i use cinder storage？  what's wrong with me？？
