### ISSUE TITLE
kube-scheduler defaults should be to configmaps, not endpoints

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16135]
#16132 showed that kube-scheduler lock management in v3.7.0-alpha.1 was being done under endpoints.  It should not be, and under configmaps instead.

```
hybrid proxy: update ep kube-scheduler in main proxy
```

**Comment by deads2k** [comment]
> #16132 showed that kube-scheduler lock management in v3.7.0-alpha.1 was being done under endpoints. It should not be, and under configmaps instead.

Ok, I'll update this using the options.

@sdodson when this eventually gets wired separately, you'll have to set the override too.
