### ISSUE TITLE
How  to use EFK  to display  HAProxy logs from Syslog

### ISSUE THREAD

**Issue by scheng1** [openshift/origin#16133]

**Comment by jcantrill** [comment]
Use Kibana with cluster-admin credentials to query for logs in one of th .operations-<DATE> indices.  The logging stack uses the Common Data Model (CDA) as a 'schema' to log information which will provide you with information for selectively querying those log entries.

**Comment by sghosh151** [comment]
Is there a way to get tenant specific HAProxy logs based on the tentant's routes?

**Comment by jcantrill** [comment]
@sghosh151 Are you deploying HAProxy to multiple domains?  Can you identify a usecase you are specifically trying to resolve?

 Consider visiting: https://github.com/openshift/origin-aggregated-logging for information regarding the EFK stack and its design

**Comment by scheng1** [comment]
@jcantrill please give me more help about that .Now I have collect haproxy log (from router pod) by rsysylog but the haproxy does not support json log format . The  haproxy log is  writing to `/var/log/message` and `/var/log/haproxy` .Although EFK display the log in file message, I can not  find any haproxy log in kibana.I think the reason is the fluentd.conf-->source-->format .can you give some advices. Thanks a lot.

**Comment by scheng1** [comment]
@jcantrill can you give me your email address,so i can send more details to you.thanks a lot.

**Comment by jcantrill** [comment]
@scheng1 Are you deploying haproxy as a container on openshift?  

The logs gathered by the EFK stack will index logs from containers where the index is based upon the the Openshift project for the container.  Each log message is enhanced to include the pod metadata for the log entry.  The collector additional intakes 'operational' logs from the node's `/var/log/messages` when the node is configured to use `json-file` driver and writes them to operation index.  Based on https://github.com/openshift/origin/issues/16133#issuecomment-327731392 I suspect your logs are ending up in the operations index. The fluentd collector will read nothing from `/var/log/haproxy.log` as its not configured to do that.

**Comment by scheng1** [comment]
@jcantrill  my email address is  `newbility.cheng@gmail.com`. could u send a email to me ,so i can send more details to you.

**Comment by scheng1** [comment]
Now, i can see haproxy logs  in `indices/.operations.*.*`. But i can not find them in kibana.

**Comment by scheng1** [comment]
@jcantrill  how indexs created in  EFK stack ?

**Comment by scheng1** [comment]
@jcantrill  hi, what the index `.all`  means? does it contains all indices.  and how the indices created  dynamically?now  I can manually create haproxy index and see haproxy log in kibana. but if default index is `.all`, kibana displays `no results found`. please give me some help , thanks a lot.

**Comment by jcantrill** [comment]
@scheng1 '.all' is an alias to every index added for administrators to allow you to create queries and visualizations across every index.  It is added by the plugin that is included as part of the logging stack.

I do not know how manually creating indices will be handled using the plugins we provide.  The expectation is that logs are pushed from fluentd in a known format to ES.  The ACLs and logic are all designed around a known format.  It could be you have no results for a number of reasons but I suspect you possibly do not have the correct time range selected in Kibana

**Comment by scheng1** [comment]
@jcantrill  i manually create indices in kibana web(`button setting`).

**Comment by jcantrill** [comment]
The openshift-elasticseach-plugin is added to Elasticsearch to address the multi-tenancy requirements of the EFK stack.

**Comment by scheng1** [comment]
>The openshift-elasticseach-plugin is added to Elasticsearch to address the multi-tenancy requirements of the EFK stack.

is there any tutorial to introduce it. thanks

**Comment by scheng1** [comment]
@jcantrill  .How EFK control  authorization that make user just can see his own index(named by project name). Thanks a lot.

**Comment by scheng1** [comment]
i can not find the following in file `/usr/share/elasticsearch/config/elasticsearch.yml` 
>openshift:
>  acl:
>    users:
>      names: ["system.logging.fluentd", "system.logging.kibana", "system.logging.curator"]
>      system.logging.fluentd:
>        execute: ["actionrequestfilter.fluentd"]
>        actionrequestfilter.fluentd.comment: "Fluentd can only write"
>      system.logging.kibana:
>        bypass: ["*"]
>        execute: ["actionrequestfilter.kibana"]
>        actionrequestfilter.kibana.comment: "Kibana can only read from every other index"
>      system.logging.kibana.*.comment: "Kibana can do anything in the kibana index"
>      system.logging.kibana.*.indices: [".kibana.*"]
>      system.logging.curator:
>        execute: ["actionrequestfilter.curator"]
>        actionrequestfilter.curator.comment: "Curator can list all indices and delete them"
>      system.admin:
>        bypass: ["*"]
>      system.admin.*.comment: "Admin user can do anything"

**Comment by scheng1** [comment]
openshift:
  acl:
    users:
      names: ["system.logging.fluentd", "system.logging.kibana", "system.logging.curator"]
      system.logging.fluentd:
        execute: ["actionrequestfilter.fluentd"]
        actionrequestfilter.fluentd.comment: "Fluentd can only write"
      system.logging.kibana:
        bypass: ["*"]
        execute: ["actionrequestfilter.kibana"]
        actionrequestfilter.kibana.comment: "Kibana can only read from every other index"
      system.logging.kibana.*.comment: "Kibana can do anything in the kibana index"
      system.logging.kibana.*.indices: [".kibana.*"]
      system.logging.curator:
        execute: ["actionrequestfilter.curator"]
        actionrequestfilter.curator.comment: "Curator can list all indices and delete them"
      system.admin:
        bypass: ["*"]
      system.admin.*.comment: "Admin user can do anything"
