### ISSUE TITLE
Unable to checkout under Windows (Filename too long)

### ISSUE THREAD

**Issue by carlpett** [openshift/origin#16145]
I cannot checkout the repo under Windows, due to nested vendor directories going too deep:

>fatal: cannot create directory at 'cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/vendor/k8s.io/kubernetes/cmd/libs/go2idl/client-gen/testoutput/clientset_generated/test_internalclientset/typed/testgroup/internalversion': Filename too long

I have a fairly minimal GOPATH already (`C:\Dev`), so there's not much room for improvement there, unfortunately.

**Comment by enj** [comment]
You will probably need to enable long paths in your OS with something like https://superuser.com/q/1119883

**Comment by carlpett** [comment]
@enj That doesn't work. I believe this is because the policy change suggested there only affects Windows Store apps and Win32 apps with the correct manifest. Git is neither, though. 

Is the multiple levels of nested vendoring necessary?

**Comment by enj** [comment]
> Is the multiple levels of nested vendoring necessary?

Until those incubator projects stabilize and start using the same version of dependencies as kube / origin, we are stuck with those folders.  They may eventually get forked into their own repos as well.

I suppose you could run it in a VM :/

**Comment by carlpett** [comment]
I see, that's unfortunate.
Anyway, I found that recent versions of git for windows has a config flag which can be used as a workaround: `git config core.longpaths true`.
It is not really a proper solution, since `cmd` and a quite a few other programs can't read files there, but it works well enough for now.
