### ISSUE TITLE
rpm packaging should create /etc/openshift

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1614]
Since we now have real "config files" for openshift, we should probably have a config file folder, which might logically reside in something like `/etc/openshift`. This can store both master and node configs, as well as any other relevant configuration files.

**Comment by sdodson** [comment]
I can provide /etc/openshift in the 'openshift' rpm but I'm trying to figure out what our next step would be. Should we make any attempt to provide a skeleton/default config files in /etc/openshift/master.yaml and/etc/openshift/node.yaml in the RPM? How about merging defaults and local config modifications?

@sosiouxme @detiber @deads2k @liggitt seem like interested parties here.

**Comment by detiber** [comment]
I'd vote to not include default configs at this point. We can reassess once things have settled down. Otherwise, we are going to have to keep updating it as the config format changes.

**Comment by deads2k** [comment]
I would really like to avoid merging unless there's an incredibly strong case for it.  Merging has been the bane of .kubeconfig.

**Comment by sosiouxme** [comment]
Agreed, no default configs or merging. Just need the directory to exist to put stuff in.

**Comment by brenton** [comment]
Looks like we can close this now.
