### ISSUE TITLE
TestRouterReloadCoalesce flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#16167]
```
--- FAIL: TestRouterReloadCoalesce (0.00s)
	router_test.go:1397: Error validating master addr 172.18.10.119:8080 : Get http://172.18.10.119:8080: read tcp 172.18.10.119:58668->172.18.10.119:8080: read: connection reset by peer
	router_test.go:1403: Error validating master addr 172.18.10.119:8080 : Get http://172.18.10.119:8888: dial tcp 172.18.10.119:8888: getsockopt: connection refused
	router_test.go:1411: Error validating master addr 172.18.10.119:8080 : Get https://172.18.10.119:8443: dial tcp 172.18.10.119:8443: getsockopt: connection refused
	router_test.go:1518: Unable to start http server: listen tcp 172.18.10.119:8080: bind: address already in use
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_end_to_end/1896/consoleFull#38566852656bf4006e4b05b79524e5923

/assign @knobunc
/sig networking
/kind test-flake

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_end_to_end/2143/consoleFull#38566852656bf4006e4b05b79524e5923

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/15199/test_pull_request_origin_end_to_end/2218/

**Comment by bparees** [comment]
looks like a dupe of https://github.com/openshift/origin/issues/16414

(this was older but that one has more traction)
