### ISSUE TITLE
oc get/describe bc should report last build status

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16184]
buildconfig.status should include information about the state of the last completed build (failed/successful and maybe the name of it).

(if there are newer builds that are in new/running/pending should those also be represented?)

@smarterclayton

**Comment by smarterclayton** [comment]
Probably some conditions.  Maybe a count or the most recent running build
number.  DaemonSet and StatefulSet status give you some idea of what is
going on, but don't give you all the details.  I think we could get away
with some of those fields here.  Definitely should look at it from the
perspective of the minimum status necessary for a naive ui to convey "what
is this build config doing right now"

**Comment by bparees** [comment]
trello'd https://trello.com/c/YjUxMm1P
