### ISSUE TITLE
It should be possible to set the service-catalog apiserver/controller log level with oc cluster up

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#16201]
Currently, the loglevel for the service-catalog API server and controller-manager is hardcoded in the template used by `oc cluster up` to install the service-catalog.  We should make this configurable so that people can easily run at a higher log level without messing with the templates.

##### Version
master

**Comment by jim-minter** [comment]
Also currently in examples/service-catalog/service-catalog.yaml the log level is set at `-v 10`, which is arguably on the high side for a default.  I suggest lowering it.
