### ISSUE TITLE
oc get should mention SCC resource

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#16210]
##### Version
oc v3.7.0-alpha.1+50094ed-201-dirty
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

Server https://10.34.129.200:8443
openshift v3.7.0-alpha.1+50094ed-201-dirty
kubernetes v1.7.0+695f48a16f

##### Steps To Reproduce
1. `oc get 2>&1 | grep scc`

##### Current Result
Empty output.

##### Expected Result
Should be suggested as it's a valid resource:
```console
$ oc get scc
NAME               PRIV      CAPS      SELINUX     RUNASUSER          FSGROUP     SUPGROUP    PRIORITY   READONLYROOTFS   VOLUMES
anyuid             false     []        MustRunAs   RunAsAny           RunAsAny    RunAsAny    10         false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]

```

**Comment by DanyC97** [comment]
@pweil- what is funny is that on my case i can't even use scc anymore

```
oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://370-lb1:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
```

```
oc get scc
the server doesn't have a resource type "scc"
```
and is not [this](https://bugzilla.redhat.com/show_bug.cgi?id=1525014) bug as i haven't deployed the service catalog

**Comment by pweil-** [comment]
@DanyC97 that is certainly a different problem then cli suggestions.  I see you've filed https://github.com/openshift/origin/issues/18302 already.  Thanks!

**Comment by DanyC97** [comment]
fair point @pweil-  ..sorry to hijack this issue
