### ISSUE TITLE
Cannot use a template variable for a label

### ISSUE THREAD

**Issue by woopla** [openshift/origin#16223]
Hello,

I'm writing a template to facilitate auto-deploy of Git branches to Openshift for testing (it's to integrate with the Gitlab 'environments' features). When the review of the app is done, all the objects related to the branch should be deleted inside Openshift. So I'm trying to add a label to all the objects, so that the environment clean-up is a simple `oc delete all -l "app=$APP"`

Openshift does not like that, and returns this on template upload:
```
The Template "tech-setup-ephemeral" is invalid: labels: Invalid value: "${NAME}": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

##### Version
[provide output of the `openshift version` or `oc version` command]
```shell
> oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://<server>:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. Create a template YAML file with this:
```yaml
labels:
  app: ${NAME}
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
```
2. Try to upload the template to Openshift

##### Current Result
```shell
> oc create -f tech-setup-ephemeral-template.yaml
The Template "tech-setup-ephemeral" is invalid: labels: Invalid value: "${NAME}": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

##### Expected Result
Template is created, and the `app` label is applied with a value that depends on the value of the `NAME` variable passed to `oc process`.

Thanks,

Clément

**Comment by woopla** [comment]
So I figured out that I can use `oc process -l app=$NAME`, which fixes the problem.

Could you please update the documentation @ https://docs.openshift.org/latest/dev_guide/templates.html#writing-parameters to mention that it's not supported for labels?

Thanks,

Clément

**Comment by bparees** [comment]
I think we should just lift this restriction.  The only risk is that if someone uses a parameter reference as a label value, and they don't supply a parameter, then the ${REF} value will be left in the label field and result in invalid objects which will get rejected.
