### ISSUE TITLE
Extended.[image_ecosystem][perl][Slow] hot deploy for openshift perl image Dancer example should work with hot deploy 

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16229]
```
/go/src/github.com/openshift/origin/test/extended/image_ecosystem/s2i_perl.go:110
Expected
    <bool>: false
to be true
/go/src/github.com/openshift/origin/test/extended/image_ecosystem/s2i_perl.go:63
```

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/204

Based on the output/expected output, it looks like maybe the perl image is suddenly hot deploying code changes even before we set "PERL_APACHE2_RELOAD=true":

expected to see a count of 3:
```
CheckPageContains was looking for <span class="code" id="count-value">3</span>
```

but saw a count of 1337 (which is the modification we made, but hot deploy wasn't enabled yet):

```
 <span class="code" id="count-value">1337</span>
```

@coreydaley if you can investigate what the behavior is of this image now...  i'm ok if it's changed, we can update the test to just expect hot deploy to always work, but i'd like to be sure that's really what happened first.

**Comment by coreydaley** [comment]
@bparees as far as I can see it looks like a flake.  It's not happening consistently, and the most recent time it failed it was looking for 3 but got 
`<span class="code" id="count-value">4</span>`

**Comment by bparees** [comment]
@coreydaley already did that last night (the 3 vs 4 thing is because the liveness probe was hitting the page and increasing the page count).  So that flake should be fixed.  But the 1337 value showing when hot deploy wasn't enabled is still weird and concerning.

fixes to the liveness probes here:
https://github.com/openshift/dancer-ex/pull/66
https://github.com/openshift/cakephp-ex/pull/81

**Comment by coreydaley** [comment]
@bparees yep, I saw those go in.  I do agree that we should keep an eye on it.  If it happens again I will investigate further.

**Comment by coreydaley** [comment]
This has not happened again, closing for now.

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/me/my-views/view/DevEx/job/test_branch_origin_extended_image_ecosystem/210/testReport/junit/(root)/Extended/_image_ecosystem__perl__Slow__hot_deploy_for_openshift_perl_image_Dancer_example_should_work_with_hot_deploy/

**Comment by bparees** [comment]
@coreydaley 
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/249/testReport/junit/(root)/Extended/_image_ecosystem__perl__Slow__hot_deploy_for_openshift_perl_image__Dancer_example_should_work_with_hot_deploy__Suite_openshift_/

**Comment by coreydaley** [comment]
@gabemontero Have you seen this flake come up recently?  I didn't see it during last sprint, we might be able to close this one.
cc: @bparees

**Comment by bparees** [comment]
@coreydaley image ecosystem hasn't been in good shape so i don't think we have any sense of whether this test is legitmately passing, or failing for other reasons before we get there.  I think we need to leave it open.  We certainly didn't make any changes to think we sorted it out.  I think @jim-minter was on the hunt last.
