### ISSUE TITLE
oc rsync compression mode

### ISSUE THREAD

**Issue by fche** [openshift/origin#16227]
It would be nice if `oc rsync` grew an option to transfer files with the `-z` flag.  I'm having to transfer several GB of highly compressible data across `oc rsync` (3.6), and it's eschewing a lot of time savings because neither `--strategy=rsync` nor `--strategy=rsync-daemon` include `-z`.  Could we have a way of passing extra flags to the inferior `rsync`?  Or pass `-z` all the time?

**Comment by fbac** [comment]
I opened PR #18599 to address this request, but I've not received any review. Am I missing something or should I ping manually someone?

Thanks.
