### ISSUE TITLE
Openshif-origin, how to get the registry / router exposed?

### ISSUE THREAD

**Issue by ultimatemanu** [openshift/origin#16237]
[Despite having read the documentation, I am stuck with getting the openshift docker registry exposed]

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Question

We are setting up a test cloud Openshift Origin which we created using the openshift ansible playbook. We are following the documentation at: https://docs.openshift.com/container-platform/latest/install_config/install/advanced_install.html
We have not done anything special concerning the openshift registry or router. We are pretty new to this topic and we tried since few tags to bring the openshift registry accessible....

We have 3 hosts:

master (unschedulable)
node-1 which is set to the region 'infra' and has the registry and router services
node-2 (other region).
Here the services running on the default project:
<pre>
NAME                 CLUSTER-IP        EXTERNAL-IP         PORT(S)                              AGE
docker-registry    172.30.78.66        &ltnone>           5000/TCP                              3h
kubernetes           172.30.0.1            &ltnone>           443/TCP,53/UDP,53/TCP      3h
registry-console   172.30.190.63      &ltnone>           9000/TCP                              3h
router                   172.30.197.135    &ltnone>           80/TCP,443/TCP,1936/TCP   3h
</pre>

When we SSH directly on the node-1 where the registry and router are running, we can access the registry without problem and we can push some images. Exactly what is here described: https://docs.openshift.org/latest/install_config/registry/accessing_registry.html

Now we cannot access the registry for other hosts (master or node-2) and we really do not understand how we can make the registry accessible.... We have of course read: https://docs.openshift.org/latest/install_config/registry/securing_and_exposing_registry.html#access-insecure-registry-by-exposing-route

We have used this command: `oc expose service docker-registry --hostname=<hostname> -n default`
The documentation says: You must be able to resolve this name externally via DNS to the router’s IP address.

As the router does not have any EXTERNAL-IP address attached to it, we do not understand how to reach it.

What is meant here?
Is there any `oc` or `oadm` command for exposing the router through an external-ip address?

Thanks in advance
Emmanuel

**Comment by pweil-** [comment]
Routers run with the assumption that your cluster/network administrator will deploy them on nodes that are publicly (or whatever access you determine) accessible.  Routers use [host networking](https://docs.openshift.org/latest/install_config/router/default_haproxy_router.html#overview) by default so they will bind to all interfaces (port 80/443) of the host they are deployed on.  From there you can set a wildcard DNS to point to the router node IP address to resolve routes.
