### ISSUE TITLE
Compilation errors are not copied to the build log

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16238]
From here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16199/test_pull_request_origin_integration/7254/

it is not clear what the error is but it should. The error can be found in the docker.service journal (it is valid compilation error related to the changes), however it would be nice if we can flush those container logs out.

**Comment by stevekuznetsov** [comment]
@smarterclayton why are we missing `stdout` here?

**Comment by smarterclayton** [comment]
Dunno, someone changed something and started to eat it?

**Comment by stevekuznetsov** [comment]
I'm not seeing changes in `hack/lib/build/environment.sh` of that type. @mfojtik can you reproduce with `$OS_DEBUG=true`?

**Comment by stevekuznetsov** [comment]
No repro
/close
