### ISSUE TITLE
[API Spec] 'required' constraints in the schema definition 

### ISSUE THREAD

**Issue by hrishin** [openshift/origin#16230]
E.g. In the [schema](https://github.com/garethr/openshift-json-schema/blob/master/master/deploymentconfig.json#L5) (derived [from](https://github.com/openshift/origin/blob/master/api/swagger-spec/openshift-openapi-spec.json))  `DeploymentConfig` has the `status` property  which is marked as required. There are many other resource properties for instance which are marked as required in schema definition like this.

**Question:** Why some properties are marked as required (mandatory) in schema definition? even though It looks like the data is required for these resource properties is returned by the server (non client-side), while it is probably forbidden (or at least optional) in the client request. isn't it?

**Use case:**
We using this schema definition to validate the resources spec https://github.com/fabric8io/fabric8-maven-plugin/issues/1039. Due to unnecessary constraints, schema validation is getting failed.

**Comment by smarterclayton** [comment]
Should be optional.  We definitely need to do a pass and mark all status fields optional.

**Comment by hrishin** [comment]
@smarterclayton thanks!
There are couple of more fields similar to status field
