### ISSUE TITLE
Make .kubeconfig *not* a dotfile

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#1625]
We currently use the path `~/.config/openshift/.kubeconfig` for configuration by default. It's confusing for the new users not seeing the kubeconfig since the dotfiles are hidden by default with ls and not sure it's needed to be hidden when in this directory.

What about making `~/.config/openshift/kubeconfig.yml` or something like this instead (or at least not a starting by a dot)

**Comment by chmouel** [comment]
related kubernetes issue https://github.com/GoogleCloudPlatform/kubernetes/issues/4615

**Comment by deads2k** [comment]
@smarterclayton Three questions:
 1. What filename should I use in $HOME?  `~/.config/openshift/openshiftconfig`?
 1. What filename should I use in `cwd`? `./.openshift/openshiftconfig`?
 1. Must I migrate existing files or simply abandon in place?

**Comment by deads2k** [comment]
@jwforres unlucky string compare.  Can you reopen this?

**Comment by deads2k** [comment]
done.
