### ISSUE TITLE
CORS headers missing from API responses

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#16279]
Note: This is breaking the web console merge queue. See https://github.com/openshift/origin-web-console/issues/2037

API responses no longer contain CORS response headers. This prevents the web console from working when the console domain doesn't match the API server's.

With `oc cluster up --version=latest`:

```
$ curl 'https://127.0.0.1:8443/oapi/v1/projects' -i -H 'Origin: https://localhost:9000' -H 'authorization: Bearer <token>' -H 'accept: application/json'
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Type: application/json
Date: Mon, 11 Sep 2017 11:43:27 GMT
Content-Length: 121

{
  "kind": "ProjectList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/oapi/v1/projects"
  },
  "items": []
}
```

With `oc cluster up --version=v3.7.0-alpha.1`:

```
$ curl 'https://127.0.0.1:8443/oapi/v1/projects' -i -H 'Origin: https://localhost:9000' -H 'authorization: Bearer <token>' -H 'accept: application/json'
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, X-Requested-With, If-Modified-Since
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE, PATCH
Access-Control-Allow-Origin: https://localhost:9000
Access-Control-Expose-Headers: Date
Cache-Control: no-store
Content-Type: application/json
Date: Mon, 11 Sep 2017 11:47:26 GMT
Content-Length: 121

{
  "kind": "ProjectList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/oapi/v1/projects"
  },
  "items": []
}
```

 `localhost` is listed as a CORS allowed origin in master-config.yaml.

```yaml
corsAllowedOrigins:
- 127.0.0.1
- 127.0.0.1:8443
- localhost
```

##### Version

oc v3.6.0-rc.0+9c8ad0a-1251
kubernetes v1.7.0+80709908fd
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+db2d00f-290
kubernetes v1.7.0+80709908fd

cc @liggitt @deads2k

**Comment by deads2k** [comment]
Oh, that's a fun thing.  Config wasn't ever getting built right and we've been accidentally hard-coding it in a custom filter that fell out of sync with upstream.

**Comment by deads2k** [comment]
Opened https://github.com/openshift/origin/pull/16280.  We may want to start building the config we mean to build until we're actually running separately.  The kube-apiserver is still a little crazy to wire up.
