### ISSUE TITLE
Template cannot get processed via web console

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#16292]
The following template gets processed correctly with `oc process` however the web console complains about duplicate keys if imported via *Import YAML/JSON*:

https://raw.githubusercontent.com/OpenShiftDemos/openshift-cd-demo/ocp-3.6/cicd-template.yaml

The error reported by the web console is:
```
duplicated mapping key at line 14, column 1:
    message: The CI/CD infrastructur ... 
    ^
```

##### Version
oc v3.6.173.0.5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://api.pro-us-east-1.openshift.com:443
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7

**Comment by spadgett** [comment]
YAML with duplicate keys is invalid, even though `oc process` allows it. We've changed it to a warning as well in the web console in 3.7.

Fixed by https://github.com/openshift/origin-web-console/pull/1798
