### ISSUE TITLE
hack/build-images.sh doesn't build `openshift/origin-source`

### ISSUE THREAD

**Issue by wbrefvem** [openshift/origin#16304]
A number of images depend on `openshift/origin-source`, which `hack/build-images.sh` doesn't build, and it doesn't exist on Docker, Fedora, or Red Hat registries.

##### Version
oc v3.7.0-alpha.1+7f5230c-320
kubernetes v1.7.0+80709908fd
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. `hack/env make release`

##### Current Result
Fails during creation of images that depend on `openshift/origin-source` image.

##### Expected Result
EDIT:
~~`hack/build-images.sh` should build `openshift/origin-source` if it doesn't already exist locally.~~
`make release` should include building `openshift/origin-source`.

##### Additional Information
```
hack/build-images.sh
[openshift/origin-pod] --> Image openshift/origin-source was not found, pulling ...
[openshift/origin-pod] no such image
[WARNING] Retrying image build for openshift/origin-pod:latest, attempt 1...
[openshift/origin-service-catalog] --> Image openshift/origin-source was not found, pulling ...
[openshift/origin-service-catalog] no such image
[WARNING] Retrying image build for openshift/origin-service-catalog:latest, attempt 1...
[openshift/origin-cluster-capacity] --> Image openshift/origin-source was not found, pulling ...
[openshift/origin-cluster-capacity] no such image
[WARNING] Retrying image build for openshift/origin-cluster-capacity:latest, attempt 1...
[openshift/origin-pod] --> Image openshift/origin-source was not found, pulling ...
[openshift/origin-pod] no such image
[ERROR] PID 15514: hack/build-images.sh:50: `return "${result}"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/build-images.sh:50: `return "${result}"`
[INFO]   Exiting with code 1.
[ERROR] PID 15420: hack/build-images.sh:50: `wait $i` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/build-images.sh:50: `wait $i`
[INFO]   Exiting with code 1.
[ERROR] hack/build-images.sh exited with code 1 after 00h 00m 05s
make: *** [build-images] Error 1
[ERROR] PID 3764: hack/lib/build/environment.sh:210: `return "${exitcode}"` exited with status 2.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/build/environment.sh:210: `return "${exitcode}"`
[INFO] 		  2: hack/lib/build/environment.sh:270: os::build::environment::withsource
[INFO] 		  3: hack/env:42: os::build::environment::run
[INFO]   Exiting with code 2.
```

**Comment by stevekuznetsov** [comment]
You need to use `hack/build-base-images.sh` We can probably make that error message better.

**Comment by wbrefvem** [comment]
@stevekuznetsov 
I should clarify. My expected result was incorrect. I would expect that `make release` should build base images before building the images they're based on. (I've updated the expected result up top.) Something like a build target called `build-base-images` that calls `hack/build-base-images.sh` and is a dependency of `build-images`.
