### ISSUE TITLE
Credentials failures with dockerhub flaking in integration

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#16318]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16316/test_pull_request_origin_integration/7532/

A test that ensures image streams work with external registries makes sense but IMO we should investigate removing the dockerhub dependency from most of those tests.

@bparees @soltysh 
/kind test-flake

**Comment by kargakis** [comment]
Or it seems like a real problem @mfojtik

**Comment by bparees** [comment]
I think we've got at least one other issue covering this.  (and yeah, it's a code/dockerhub problem, definitely *not* a test we want to remove)

**Comment by kargakis** [comment]
Please link to the other issue.

**Comment by bparees** [comment]
https://github.com/openshift/origin/issues/16312
https://github.com/openshift/origin/issues/16323

and the aos-devel thread.
