### ISSUE TITLE
Cluster up should no longer set `pod_presets` to true

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#16313]
Clustering up with the `--service-catalog` flag should no longer set the web console pod presets feature flag to true. Pod presets have been removed from service catalog in 3.7. Turning off this flag prevents the console from prompting the user to bind to a specific application, which will not work.

https://github.com/openshift/origin/blob/4a90471ed4a04cd8aeebdd71edb9e991074ef346/pkg/oc/bootstrap/docker/openshift/helper.go#L851

cc @jeff-phillips-18 @csrwng

**Comment by spadgett** [comment]
Note that the flag works in 3.6, so ideally we'd disabled it in 3.7 only.

**Comment by spadgett** [comment]
@ewolinetz @sdodson This change should be made to the installer as well. Is there a place you'd like me to open an issue?

**Comment by spadgett** [comment]
Thanks @ewolinetz, I opened https://github.com/openshift/openshift-ansible/issues/5403. Let me know if you have questions.

**Comment by maleck13** [comment]
@spadgett we had hoped to make use of these. Do you know if they are due to come back. Are you aware of any issues I could follow to keep track of what is happening with PodPresets?

**Comment by spadgett** [comment]
@maleck13 I'll defer to @pmorie on pod presets.
