### ISSUE TITLE
Support ManifestList in dockerregistry and importer

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#16323]
Dockerhub serves `ManifestList` instead of regular `Manifest` if you provide it with information about having that type supported. Whenever we import `github.com/docker/distribution/manifest/manifestlist` which we do indirectly in integration tests we tell docherhub we do support this.

There was one attempt to bypass the problem temporarily: https://github.com/openshift/origin/pull/16319 but that failed. 

@dmage is currently working on a permanent fix

Make sure to revert:
- [ ] https://github.com/openshift/origin/pull/16324
- [ ] carry commit from https://github.com/openshift/origin/pull/16319

**Comment by bparees** [comment]
fixed by https://github.com/openshift/origin/pull/16322

all relevant PRs were reverted(ie tests re-enabled) with that work as well.
