### ISSUE TITLE
Openshift 1.6 install docs

### ISSUE THREAD

**Issue by ibuler** [openshift/origin#16341]
Hi, 
I only see openshift 1.5 docs in website for production  installation. Is there some docs for 1.6 ?

**Comment by php-coder** [comment]
This is a question to @openshift/team-documentation

**Comment by adellape** [comment]
Fixed via https://github.com/openshift/openshift-docs/pull/5261. Note that for Origin, the release number jumped from 1.5 to 3.6, to align with the OpenShift Container Platform numbering.

**Comment by adellape** [comment]
OK, link from the drop-down to Origin 3.6 docs now works:

https://docs.openshift.org
