### ISSUE TITLE
Ugrade from 1.5 to 3.6 not possible because docker can't pull openshift/origin:v3.6

### ISSUE THREAD

**Issue by arthfl** [openshift/origin#16346]
Tried to upgrade an Origin cluster from 1.5 to 3.6.
Ansible stopped at
```
TASK [openshift_version : Set precise containerized version to configure if openshift_release specified] **************
fatal: [--redacted--]: FAILED! => {"changed": true, "cmd": ["docker", "run", "--rm", "openshift/origin:v3.6", "version"], "delta": "0:00:06.192561", "end": "2017-09-14 11:10:36.040463", "failed": true, "rc": 125, "start": "2017-09-14 11:10:29.847902", "stderr": "Unable to find image 'openshift/origin:v3.6' locally\nTrying to pull repository registry.access.redhat.com/openshift/origin ... \nTrying to pull repository registry.access.redhat.com/openshift/origin ... \nTrying to pull repository docker.io/openshift/origin ... \n/usr/bin/docker-current: manifest unknown: manifest unknown.\nSee '/usr/bin/docker-current run --help'.", "stderr_lines": ["Unable to find image 'openshift/origin:v3.6' locally", "Trying to pull repository registry.access.redhat.com/openshift/origin ... ", "Trying to pull repository registry.access.redhat.com/openshift/origin ... ", "Trying to pull repository docker.io/openshift/origin ... ", "/usr/bin/docker-current: manifest unknown: manifest unknown.", "See '/usr/bin/docker-current run --help'."], "stdout": "", "stdout_lines": []}
```
I ssh-ed into the host and tried to pull the image manually:
```
 docker pull openshift/origin:v3.6
Trying to pull repository registry.access.redhat.com/openshift/origin ... 
Trying to pull repository registry.access.redhat.com/openshift/origin ... 
Trying to pull repository docker.io/openshift/origin ... 
manifest unknown: manifest unknown
```
So, more or less the same result
##### Version
[provide output of the `openshift version` or `oc version` command]
```
$ oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://--redacted--:8443
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4

```

Operating system is AtomicOS:
```
# atomic -v
1.18.1
```

##### Steps To Reproduce
1. Try running "ansible-playbook -i youinventory.ini playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml" on a v1.5 cluster (running AtomicOS, although i don't know if this is relevant)

##### Current Result
Upgrading fails

##### Expected Result
Upgrading should work

##### Additional Information
Wasn't even able to pull the _openshift/origin:v3.6_ image on my workstation, which has a quite recent docker version:
```
$ docker version
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   87847530f7
 Built:        Wed Aug 30 21:31:46 2017
 OS/Arch:      linux/amd64
```

**Comment by mfojtik** [comment]
@arthfl it is ':v3.6.0'

**Comment by mfojtik** [comment]
@smarterclayton this is third time somebody asked me about v3.6 :-) can we push that tag to dockerhub as well or it will break our versioning?

**Comment by arthfl** [comment]
Well, i can pull the image manually with "docker pull openshift/origin:v3.6.0", but when i put
```
openshift_release=3.6.0
```
in my inventory file, ansible complains:
```
Failure summary:


  1. Hosts:    --redacted--
     Play:     Verify upgrade can proceed on first master
     Task:     fail
     Message:  openshift_release is 3.6.0 which is not a valid release for a 3.6 upgrade
```

**Comment by smarterclayton** [comment]
@openshift/ansible-review

**Comment by krzysiekneo** [comment]
Please try tag it:
`docker tag docker.io/openshift/origin:v3.6.0 openshift/origin:v3.6`
In my case it helped.
I'm also trying to upgrade from 1.5 to 3.6 and I've found also an issue in the file:
playbooks/common/openshift-cluster/upgrades/pre/verify_inventory_vars.yml
is:    		
`when: openshift_release is defined and openshift_release[0] == 'v'`
should be:	
`when: openshift_release is defined and openshift_release[0] == 'v3.6.0'`

**Comment by arthfl** [comment]
Can confirm that the workaround from @krzysiekneo works.
First pulling the image and then tagging it with the name that the ansible playbooks expects, gets me past that stage.

But of course i've ran into the same problem with _playbooks/common/openshift-cluster/upgrades/pre/verify_inventory_vars.yml_ now.

Anyway, the initial issue should get fixed somehow. Will open another one for the inventory vars thing.

**Comment by feld-ims** [comment]
Does this only impact upgrades? I didn't seem to have an issue with a fresh install using
```
openshift_release=v3.6
openshift_version=3.6.0
```
