### ISSUE TITLE
SA role bindings are not deleted when the SA is deleted.

### ISSUE THREAD

**Issue by jtudelag** [openshift/origin#16356]
SA binding (role or clusterrole binding) is not deleted when the SA is deleted.

##### Version
oc version
oc v3.5.5.31
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://XXXXXXXXX:8443
openshift v3.5.5.31
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. oc new-project test
2. oc -n test create sa test
3. oc -n test get sa test
NAME      SECRETS   AGE
test      2         7s
4. oc -n test adm policy add-role-to-user cluster-reader -z test
5. oc -n test get rolebinding cluster-reader
NAME             ROLE              USERS     GROUPS    SERVICE ACCOUNTS   SUBJECTS
cluster-reader   /cluster-reader                       test               
6. oc -n test delete sa test
7. oc -n test get sa test 
Error from server (NotFound): serviceaccounts "test" not found
8.  oc -n test get rolebinding cluster-reader
NAME             ROLE              USERS     GROUPS    SERVICE ACCOUNTS   SUBJECTS
cluster-reader   /cluster-reader                       test     

##### Current Result
cluster-reader role binding still exists and contains test SA. 

##### Expected Result
test SA should not be included in the cluster-reader binding of project test.

**Comment by liggitt** [comment]
the service account object is decoupled from the permission grant. permissions can be granted to a service account that does not yet exist, and are independent of the lifecycle of the service account object

**Comment by jtudelag** [comment]
Thanks for the answer @liggitt, but what about users? I mean, permissions can be granted to a user that does not yet exist too. And when a user is deleted, no matter if it exists or not, bindings are deleted too. I was expecting the same behaviour for SAs, just for consistency...
