### ISSUE TITLE
Registry should return forbidden instead of 500 when get/create signature failed because of permissions

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16352]
When registry make a request to OpenShift API and the token used in that request does not have enough perms to get or create signature, registry will fail with 500 error hiding the cause, which is permission denied. We should return 403 instead of 500.

**Comment by csrwng** [comment]
@mfojtik just a correction... it's not permissions to create a signature, it's permissions to read a signature (see #16349)

**Comment by mfojtik** [comment]
@csrwng i'm pretty sure both will return 500 :-) But I would be surprised if create return 400 ;)

**Comment by bparees** [comment]
@mfojtik what API request were you making?  I assume you weren't directly creating the imagesignature.

**Comment by bparees** [comment]
@mfojtik @legionus this looks right to me:
https://github.com/openshift/origin/pull/16353/files#diff-93ff04a669b260955e668eb4ee914e01L160

can i get another hint? :)

(steps to recreate this would be useful)

**Comment by bparees** [comment]
we appear to be doing the right thing now:
```
$ curl -k 172.30.201.67:5000/extensions/v2/test-docker/origin-ruby-sample/signatures/sha256:c1fb4160ed2b43b9b8c6d93a5908ca22ccac8442a0876e1103da9493daa1e73d
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"signature","Class":"","Name":"test-docker/origin-ruby-sample","Action":"get"},{"Type":"repository","Class":"","Name":"test-docker/origin-ruby-sample","Action":"pull"}]}]}
```
