### ISSUE TITLE
error: Import failed (Unauthorized): you may not have access to the Docker image from private insecure repository

### ISSUE THREAD

**Issue by pycaster** [openshift/origin#16367]
I push an image to a private insecure quay.io as a result of successful build config but can't seem to import the same image into the imagestream. Is this supported?

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Create build config from a git repo and push the image to a private quay.io repository
2. Create imagestream and import image from the private quay.io (source) by following,

oc import-image is-hola:0.1 quay.example.com/blue/hola:0.1 --insecure=true --confirm

##### Current Result

This is how my build config looks like and it's successful in pushing the image,

apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2017-09-15T01:48:13Z
  labels:
    app: hola
    createdBy: template-hola
    template: hola
  name: hola
  namespace: hello-openshift
  resourceVersion: "402251"
  selfLink: /oapi/v1/namespaces/hello-openshift/buildconfigs/hola
  uid: efa7a278-99b7-11e7-aa57-fa163ef8f0c8
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    pushSecret:
      name: external-registry
    to:
      kind: DockerImage
      name: quay.example.com/blue/hola:0.1
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/redhat-helloworld-msa/hola
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: wildfly:latest
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
      lastTriggeredImageID: openshift/wildfly-101-centos7@sha256:501bc1a8919899024d1a92a147b4d58ad87d0944c720b939cdfe5eff7773e977
    type: ImageChange
status:
  lastVersion: 2

This is how my imagestream looks like and complains that I don't have access to this image,

apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2017-09-15T01:51:03Z
      openshift.io/image.insecureRepository: "true"
    creationTimestamp: 2017-09-15T01:48:13Z
    generation: 4
    labels:
      app: hola
      createdBy: template-hola
      template: hola
    name: is-hola
    namespace: hello-openshift
    resourceVersion: "402033"
    selfLink: /oapi/v1/namespaces/hello-openshift/imagestreams/is-hola
    uid: efa9636d-99b7-11e7-aa57-fa163ef8f0c8
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: quay.example.com/blue/hola:0.1
      generation: 3
      importPolicy:
        insecure: true
      name: "0.1"
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: docker-registry.default.svc:5000/hello-openshift/is-hola
    tags:
    - conditions:
      - generation: 3
        lastTransitionTime: 2017-09-15T01:51:03Z
        message: you may not have access to the Docker image "quay.example.com/blue/hola:0.1"
        reason: Unauthorized
        status: "False"
        type: ImportSuccess
      items: null
      tag: "0.1"
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""

##### Expected Result

I am expecting to import this image into imagestream and use it in deploymentConfig.

I am seeing my docker pull spec as below in the imagestream and not "quay.example.com/test/is-hola",

Docker Pull Spec:       docker-registry.default.svc:5000/hello-openshift/is-hola

##### Additional Information

I don't see any integrated registry service here,

$oc get svc
NAME           CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
router         172.30.181.229   <none>        80/TCP,443/TCP,1936/TCP   1d
service-hola   172.30.177.209   <none>        8888/TCP                  35m

$oc describe sa/builder
Name:           builder
Namespace:      hello-openshift
Labels:         <none>
Annotations:    <none>

Image pull secrets:     builder-dockercfg-2rvv9
                        external-registry

Mountable secrets:      builder-token-qk760
                        builder-dockercfg-2rvv9
                        external-registry

Tokens:                 builder-token-qk760
                        builder-token-vjrv2

$oc describe sa/default
Name:           default
Namespace:      hello-openshift
Labels:         <none>
Annotations:    <none>

Tokens:                 default-token-4hlkl
                        default-token-k3pqf

Image pull secrets:     default-dockercfg-pjwfl
                        external-registry

Mountable secrets:      default-token-k3pqf
                        default-dockercfg-pjwfl
                        external-registry

**Comment by pycaster** [comment]
I was able to resolve it. Was just a configuration issue.

**Comment by samirshamsi100** [comment]
What was the configuration issue? We are facing the exact same issue.

**Comment by uvwild** [comment]
yeah, bad style to not mention the resolution.

**Comment by domq** [comment]
If you come here from the future through Google: in my case I had a `from:` construct in my `ImageStream`'s `spec:` → `tags:`, where none should have be. At this point, it seems to me that the only case where you want a `spec:` in your ImageStream at all, is when you are pulling that stream from an external Docker registry.

**Comment by maktup** [comment]
Someone get the solution of this problem ?

**Comment by maktup** [comment]
This problem is in the Image that was not good compiled, and the problem is show with a: DESCRIBE in the ImageStream
