### ISSUE TITLE
template customizability

### ISSUE THREAD

**Issue by bparees** [openshift/origin#1636]
Currently only ENV values can be parameterized in openshift templates.  There are several additional places where it would be useful to be able to provide customized values when instantiating the template:

**naming**:  currently services/deploymentconfigs/buildconfigs/etc all have a fixed name defined in the template.  This means you can't instantiate a template more than once in a given project.  It would be good to be able to make these values the product of a parameter with a default value so the user can override them when deploying the template.

**source repo**: currently the source repo is a fixed value.  This is fine for "instant app" templates where you want to run, for example, Wordpress from the wordpress repo.  It's less fine for "Quick start/example" use cases where the user is going to want to point to a repo that they control (they are using the template to get the right images selected and services defined, not to pick up the source).  Again we should be able to parameterize the source repo using a parameter with a default value.

The question then is, do we just strategically add the ability to replace those specific things, or do we go implement a generic approach where any string in the template can be replaced by a parameter value?  Or at least any value field of type string/primitive?

**Comment by bparees** [comment]
@smarterclayton @jstrachan @goldmann @mfojtik feedback please.

**Comment by mfojtik** [comment]
@bparees the generic approach is already done, I had PR for that. I can adapt the PR to selectively enable on what items we want to support substitutions.

**Comment by smarterclayton** [comment]
I would rather allow all values to be substituted (numbers and strings).

**Comment by bparees** [comment]
@mfojtik remind me...did you PR only do values, or did it do keys and values?

**Comment by rcernich** [comment]
Here's a list of the fields I was trying to use parameters for in one of my templates:
 * id fields (service, route, etc.)
 * metadata/name fields (route, image stream, build config, deployment config, etc.)
 * build
  * image change trigger (tag)
  * git source (uri, ref, context dir)
  * sti (tag)
  * output to (name, tag)
 * deployment
  * image change trigger (container name, from/name, tag)
  * container (name, image, port/name)
 * selector values (i.e. not keys)
 * label values (i.e. not keys)

**Comment by jstrachan** [comment]
allowing all values to be parameterised sounds like a nice thing to me

**Comment by rcernich** [comment]
I'm also using generated parameters for build trigger git/generic secrets.

**Comment by smarterclayton** [comment]
Secrets should be created automatically, is that because you're using the url in another resource as an ENV var?

**Comment by rcernich** [comment]
@smarterclayton no, this is for the source triggers in the build config (i.e. BuildConfig/triggers/type=github/github/secret and BuildConfig/triggers/type=generic/generic/secret).  If secrets can be used for those settings, then that would probably be preferable.

**Comment by smarterclayton** [comment]
Gotcha.  I was thinking about webhooks, and secret data still has to be filled out.  It does mean eventually the UI should be able to provide a file as a parameter value.

**Comment by maxandersen** [comment]
+1 for not limiting replacement to specific locations but open up for any attribute value.
Then provide additional smarter ways to generate values based on kubernetes/OS3 state (to avoid overlapping names etc.) and the template mechanism would become really useful really fast.

**Comment by mfojtik** [comment]
@bparees only values, keys would be more tricky :)

**Comment by mfojtik** [comment]
@bparees for reference, this is the PR: https://github.com/openshift/origin/pull/827

**Comment by mfojtik** [comment]
@bparees taking my previous comment back, the PR do support replacing keys in map (if I reading my code correctly ;-)

**Comment by bparees** [comment]
and here's the trello card: https://trello.com/c/50JUEZtO/336-2-as-a-user-i-would-like-to-generically-substitute-template-parameters-composition-future

**Comment by smarterclayton** [comment]
I don't want to replace keys unless someone can make a really strong argument.  And even then, I'll probably say no :)

----- Original Message -----

**Comment by mfojtik** [comment]
@smarterclayton yeah, I also think that replacing in map keys is not ideal and I can't make a good use case for that in my brain.

**Comment by bparees** [comment]
@mfojtik does your PR implementation support partial replacement (eg "$MYPARAM-foo") or only exact matches?

**Comment by smarterclayton** [comment]
Also please sync with Paul on the requirements for substitution I gave him.  Always require ${name}, support proper escaping

**Comment by bparees** [comment]
@mfojtik we're getting pushed to move on this, can you reopen/rebase your PR so we can have the discussion/review?

@danmcp @johnkeck fyi.

**Comment by mfojtik** [comment]
@bparees will do it as first thing tomorrow morning.

**Comment by bparees** [comment]
resolve by https://github.com/openshift/origin/issues/827
