### ISSUE TITLE
Add test to check new error codes are not duplicates 

### ISSUE THREAD

**Issue by simo5** [openshift/origin#16364]
Error codes are only useful if the uniquely identify an error point in the code.
Currently there is no test that verifies new PRs are not introducing duplicate codes, and we rely on reviewers to catch duplicates.
This should be done by a test not by a human, it's a wte of time and it is super-error prone.

**Comment by sosiouxme** [comment]
To be clear, are you talking about errors in general in the product, or specifically in diagnostics?

I mean, I think it would be nice to have unique error codes in the rest of the product too...
