### ISSUE TITLE
flake: openshift router metrics The HAProxy router should expose prometheus metrics for a route

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#16369]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible/671/consoleFull#214282049956cbb9a5e4b02b88ae8c2f77

```
• Failure [21.267 seconds]
[Conformance][networking][router] openshift router metrics
/go/src/github.com/openshift/origin/test/extended/router/metrics.go:192
  The HAProxy router
  /go/src/github.com/openshift/origin/test/extended/router/metrics.go:191
    should expose prometheus metrics for a route [It]
    /go/src/github.com/openshift/origin/test/extended/router/metrics.go:173

    Expected error:
        <*errors.errorString | 0xc421150ca0>: {
            s: "last response from server was not 403: 401",
        }
        last response from server was not 403: 401
    not to have occurred

    /go/src/github.com/openshift/origin/test/extended/router/metrics.go:99
```

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/6141/consoleFull#141320619656cbb9a5e4b02b88ae8c2f77

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/6135/consoleFull#79597540756cbb9a5e4b02b88ae8c2f77

**Comment by mfojtik** [comment]
I see this under almost every PR that failed to test, raising severity.

**Comment by mrogers950** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16376/test_pull_request_origin_extended_conformance_install_update/6178/

**Comment by smarterclayton** [comment]
Fixed

**Comment by knobunc** [comment]
Fixed by https://github.com/openshift/origin/pull/16365
