### ISSUE TITLE
TestMonitorNodeStatusEvictPodsWithDisruption flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#16370]
```
--- FAIL: TestMonitorNodeStatusEvictPodsWithDisruption (3.49s)
	nodecontroller_test.go:1297: Zone is partially disrupted - eviction should take place.: expected pod eviction: true, got false
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_unit/2732/consoleFull#-115297467956bf4006e4b05b79524e5923

/assign @derekwaynecarr 
/kind test-flake
/priority P1

**Comment by kargakis** [comment]
Seems fixed upstream (https://github.com/kubernetes/kubernetes/issues/39975) but there are a couple of months ever since it was closed?

**Comment by tnozicka** [comment]
seen in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/14910/test_pull_request_origin_unit/3869/
