### ISSUE TITLE
templateservicebroker end-to-end test should pass an end-to-end test

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16374]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/14910/test_pull_request_origin_extended_conformance_gce/7937/

```
/tmp/openshift/build-rpm-release/tito/rpmbuild-originJKHWWh/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:362
Expected error:
    <*errors.errorString | 0xc421262e90>: {
        s: "operation returned state failed",
    }
    operation returned state failed
not to have occurred
/tmp/openshift/build-rpm-release/tito/rpmbuild-originJKHWWh/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:145			
```

(similar the security test). I guess this can be etcd timeout, but I haven't looked into this deeply.

**Comment by jim-minter** [comment]
wow, something went horribly wrong here.  @stevekuznetsov I can't find any master logs - are these available?

**Comment by stevekuznetsov** [comment]
Yes, today they are not in GCS -- see the [s3 bucket](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/7937/s3/) though.

**Comment by mfojtik** [comment]
The cause of etcd timeout was tmpfs not wired into the container that run the test. This was fixed, closing this.
