### ISSUE TITLE
imageConfig empty on cluster upgrade

### ISSUE THREAD

**Issue by feld-ims** [openshift/origin#16388]
When upgrading origin cluster from 1.5.1 to 3.6.0 using the ansible installer, some of the nodes have missing values in the node-config.yaml for imageConfig.format, so the origin-node service fails to start. Ensuring these values ARE present before running the upgrade, it continues to happen on random nodes without any real pattern. Installing a fresh 3.6.0 cluster on the same hosts worked without issue.

##### Version
1.5.1 -> 3.6.0

##### Steps To Reproduce
1. run the ansible upgrade script

##### Current Result
cluster upgrade fails

##### Expected Result
cluster upgrade succeeds

**Comment by tremble** [comment]
We've just hit this too,

I suspect it's been introduced by 
```
commit 57abb2f092264e8adbecf006d3ea0205bfa39489
Author: Michael Gugino <mgugino@redhat.com>
Date:   Thu Aug 17 22:45:05 2017 -0400
```

@michaelgugino  The upgrade playbooks check for undefined *NOT* empty string
```
$ grep -r oreg_url_master *
...
playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml:    when: oreg_url is defined or oreg_url_master is defined
...
```

**Comment by pweil-** [comment]
@feld-ims would you mind opening this against https://github.com/openshift/openshift-ansible which is where the playbooks are maintained?  Thanks!
