### ISSUE TITLE
Default serviceaccounts no longer able to pull images from openshift project after upgrade to 3.6.0

### ISSUE THREAD

**Issue by rezie** [openshift/origin#16380]
We are currently in the process of upgrading from a v1.5.1 cluster to v3.6.0; we are also following the blue/green deployment guide. So far, the masters have been upgraded and the updated router and registry images have been deployed onto the v3.6 nodes; all of the v1.5.1 nodes have been shut down. In addition, cluster roles and bindings and the SCCs have been updated as well (via oadm reconcile).

We noticed that existing deployments that referenced imagestreams from the default openshift project were now having authorization errors when they attempted to spin up and pull images. This is all using the internal registry.

##### Version
```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.adx3.org:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

# docker 
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-28.git1398f24.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      1398f24/1.12.6
 Built:           Fri May 26 17:28:18 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-28.git1398f24.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      1398f24/1.12.6
 Built:           Fri May 26 17:28:18 2017
 OS/Arch:         linux/amd64
```

##### Steps To Reproduce
After upgrading to 3.6, verify that deployments which reference imagestreams pushed into the Openshift project are still accessible. This can be also be tested by attempting to login to the internal registry using a test project's default dockercfg token:

```
oc new-project test
oc get secrets
oc describe secret default-dockercfg-blabla

(copy the token)

docker login -u serviceaccount -p <token> registryIP:5000
docker pull registryIP:5000/openshift/any_image:some_tag
```

Note: Logging in via the `oc whoami -t` credentials allows pulling from the openshift project without a problem.

##### Current Result

```
Trying to pull repository 172.30.134.33:5000/openshift/postgres ...
unauthorized: authentication required
```

##### Expected Result
The image should pull successfully

##### Additional Information
```
oc describe policyBinding :default
Name:					:default
Namespace:				docker-test
Created:				3 hours ago
Labels:					<none>
Annotations:				<none>
Last Modified:				2017-09-15 12:49:27 +0000 UTC
Policy:					<none>
RoleBinding[admin]:
					Role:			admin
					Users:			me
					Groups:			<none>
					ServiceAccounts:	<none>
					Subjects:		<none>
RoleBinding[system:deployers]:
					Role:			system:deployer
					Users:			<none>
					Groups:			<none>
					ServiceAccounts:	deployer
					Subjects:		<none>
RoleBinding[system:image-builders]:
					Role:			system:image-builder
					Users:			<none>
					Groups:			<none>
					ServiceAccounts:	builder
					Subjects:		<none>
RoleBinding[system:image-pullers]:
					Role:			system:image-puller
					Users:			<none>
					Groups:			system:serviceaccounts:docker-test
					ServiceAccounts:	<none>
					Subjects:		<none>
```

Logs from the internal registry:

```
time="2017-09-15T15:28:55.133185912Z" level=debug msg="Origin auth: checking for access to repository:openshift/postgres:pull" go.version=go1.7.6 http.request.host="172.30.134.33:5000" http.request.id=cf4304a9-1cfa-4bc6-8d93-45e46e47ba71 http.request.method=GET http.request.remoteaddr="x.x.x.x:39142" http.request.uri="/v2/openshift/postgres/manifests/1.0.0" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.16.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=ac1eac7d-4ba4-4ea4-bafc-c69129354c21 openshift.auth.user="system:serviceaccount:docker-test:default" openshift.logger=registry vars.name="openshift/postgres" vars.reference=1.0.0
time="2017-09-15T15:28:55.143694194Z" level=error msg="OpenShift access denied: User \"system:serviceaccount:docker-test:default\" cannot get imagestreams/layers.image.openshift.io in project \"openshift\"" go.version=go1.7.6 http.request.host="172.30.134.33:5000" http.request.id=cf4304a9-1cfa-4bc6-8d93-45e46e47ba71 http.request.method=GET http.request.remoteaddr="x.x.x.x:39142" http.request.uri="/v2/openshift/postgres/manifests/1.0.0" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.16.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=ac1eac7d-4ba4-4ea4-bafc-c69129354c21 openshift.auth.user="system:serviceaccount:docker-test:default" openshift.logger=registry vars.name="openshift/postgres" vars.reference=1.0.0
time="2017-09-15T15:28:55.143774413Z" level=error msg="error authorizing context: access denied" go.version=go1.7.6 http.request.host="172.30.134.33:5000" http.request.id=cf4304a9-1cfa-4bc6-8d93-45e46e47ba71 http.request.method=GET http.request.remoteaddr="x.x.x.x:39142" http.request.uri="/v2/openshift/postgres/manifests/1.0.0" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.16.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=ac1eac7d-4ba4-4ea4-bafc-c69129354c21 openshift.logger=registry vars.name="openshift/postgres" vars.reference=1.0.0
```

Workaround:
`oc policy add-role-to-user system:image-puller system:serviceaccount:<your_project>:default --namespace=openshift`

(alternative, untested)  // edited by enj
`oc policy add-role-to-group system:image-puller system:serviceaccounts:openshift -n openshift`

**Comment by ttindell2** [comment]
+1 seeing the same thing.

**Comment by rezie** [comment]
Huh that's odd... I thought I replied yesterday. In any case:

Name:					:default
Namespace:				openshift
Created:				2 months ago
Labels:					<none>
Annotations:				<none>
Last Modified:				2017-09-19 18:32:47 +0000 UTC
Policy:					<none>
RoleBinding[admin]:
					Role:			admin
					Users:			-redacted-
					Groups:			<none>
					ServiceAccounts:	<none>
					Subjects:		<none>
RoleBinding[system:deployer]:
					Role:			system:deployer
					Users:			<none>
					Groups:			<none>
					ServiceAccounts:	deployer
					Subjects:		<none>
RoleBinding[system:image-builder]:
					Role:			system:image-builder
					Users:			<none>
					Groups:			<none>
					ServiceAccounts:	builder
					Subjects:		<none>
RoleBinding[system:image-puller]:
					Role:			system:image-puller
					Users:			<none>
					Groups:			system:serviceaccounts:openshift
					ServiceAccounts:	docker-test/default, ...
					Subjects:		<none>


Name:					openshift:default
Namespace:				openshift
Created:				2 months ago
Labels:					<none>
Annotations:				<none>
Last Modified:				2017-07-18 16:26:31 +0000 UTC
Policy:					openshift
RoleBinding[shared-resource-viewers]:
					Role:			shared-resource-viewer
					Users:			<none>
					Groups:			system:authenticated
					ServiceAccounts:	<none>
					Subjects:		<none>

**Comment by rezie** [comment]
Closing this because it sounds like #16465 will deal with the underlying problem.
