### ISSUE TITLE
Rename command osc log to osc logs

### ISSUE THREAD

**Issue by jpechane** [openshift/origin#1639]
I think it would be good to rename comand 'osc log' to 'osc logs' or support both variants. The reasoning behind is

1) Docker uses 'docker logs'
2) There is 'osc build-logs'

This means that 'osc log' is anomaly and is frequently mis-type as 'osc logs'

**Comment by smarterclayton** [comment]
Agreed, something we need to open as an upstream issue.

**Comment by mfojtik** [comment]
+1

**Comment by smarterclayton** [comment]
Did this get opened upstream?

**Comment by kargakis** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/8634
