### ISSUE TITLE
openshift-sdn is opening more watches than expected

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16397]
From a medium sized cluster, the rate of WATCH requests being made to the API server for netnamespaces, egressnetworkpolicies, and hostsubnets is higher than endpoints and nodes.  In general, these rates should all be about the same because each node should have roughly the same watch durations for each of the caches it maintains.

It's possible that either the watches for openshift-sdn have a lower timeout value (it should be 10-20m by default) or the watch is being broken before it should be by the nodes.  Because very large clusters will have many nodes, we need to be really careful to ensure that we are not creating watches too often in openshift-sdn.

```
{client="openshift/v3.6.173.0.5 (linux/amd64) openshift/f30b99e",resource="netnamespaces"} | 2.466664166697916
{client="openshift/v3.6.173.0.5 (linux/amd64) openshift/f30b99e",resource="egressnetworkpolicies"} | 1.7416652604342446
{client="openshift/v3.6.173.0.5 (linux/amd64) openshift/f30b99e",resource="hostsubnets"} | 0.9249992187597655
{client="openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/fff65cf",resource="services"} | 0.8333326562584634
{client="openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/fff65cf/system:serviceaccount:kube-system:horizontal-pod-autoscaler",resource="pods"} | 0.6416666666666667
{client="openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/fff65cf",resource="pods"} | 0.4791659375091145
{client="openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/fff65cf",resource="nodes"} | 0.43333281250651035
{client="openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/fff65cf",resource="endpoints"} | 0.4249996354212239
```

@openshift/sig-networking please look into this (verify you are watching at 15-20m intervals minimum)

**Comment by danwinship** [comment]
The watchers are created by code that eventually calls `kcache.NewReflector` with a `resyncPeriod` of `30*time.Minute`.

What exactly do the numbers in those logs there mean?

(The node/endpoint/service/pod watchers are via shared informers, which is why they behave differently.)

**Comment by smarterclayton** [comment]
Numbers are "watches created per second across the cluster".  The client section is identifying nodes, with the exception of the one for service account.  So you should read this as:

Across the cluster, we are creating more watches per second per node for netnamespaces than pods, nodes, services, and endpoints combined.

That generally implies the expected timeout period is not actually being used.  You can verify this by starting up openshift-sdn to point to a master running at --loglevel=3 and see the WATCH requests created.

**Comment by danwinship** [comment]
the switch to shared informers (#16766) should have fixed this
