### ISSUE TITLE
serving cert controller should set owner ref for cert secret

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16401]
I would expect that deleting the service with cascade=true would delete the secret created by the controller.  Also makes cleanup correct.

@deads2k make sense to you too?

**Comment by mfojtik** [comment]
How about existing secrets? Does they need a migration or update with ownerRefs?

**Comment by mfojtik** [comment]
@deads2k will have PR today

**Comment by deads2k** [comment]
> @deads2k will have PR today

I volunteered huh? :)

**Comment by mfojtik** [comment]
also I'm thinking that we can get rid of the `ServiceUIDAnnotation` if we use owner ref.

**Comment by deads2k** [comment]
> also I'm thinking that we can get rid of the ServiceUIDAnnotation if we use owner ref.

I don't think so.  Nothing says that I can't simply create multiple ownerRefs to multiple services.  You would try to cross-correlate multiple fields?

**Comment by deads2k** [comment]
Opened https://github.com/openshift/origin/pull/16406
