### ISSUE TITLE
executing 'oc delete project 'cmd-admin'' expecting success 1.63s

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#16402]
```
=== BEGIN TEST CASE ===
hack/test-cmd.sh:126: executing 'oc delete project 'cmd-admin'' expecting success
FAILURE after 1.631s: hack/test-cmd.sh:126: executing 'oc delete project 'cmd-admin'' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
The connection to the server 172.17.0.2:28443 was refused - did you specify the right host or port?
=== END TEST CASE ===
				
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/14910/test_pull_request_origin_cmd/2940/

/assign @mfojtik 
/sig master
/kind test-flake

**Comment by kargakis** [comment]
@mfojtik this is flakying a lot today
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16224/test_pull_request_origin_cmd/2941/
/priority P1

**Comment by soltysh** [comment]
@kargakis from looking into docker.service logs it looks like it's similar to https://github.com/openshift/origin/issues/16248. Closing, since the other one is already P0.

**Comment by bparees** [comment]
the P0 has been closed and this is still happening:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16684/test_pull_request_origin_cmd/4215/

**Comment by bparees** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16874/test_pull_request_origin_cmd/4691/
