### ISSUE TITLE
Cluster up should no longer set `service_catalog_landing_page` to true

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#16415]
In origin-web-console, we've made the service catalog landing page the default (https://github.com/openshift/origin-web-console/pull/2078). Cluster up should no longer set `service_catalog_landing_page` to true, and that value will be ignored if set.

https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/openshift/helper.go#L849

**Comment by bparees** [comment]
If that's the default now, what happens when we bring up cluster up w/o the service catalog?

**Comment by spadgett** [comment]
It still uses the new experience, just with no service catalog resources.

**Comment by bparees** [comment]
if we don't set this, people won't be able to use older versions of the web console w/ the SC.  Is there any harm in leaving it set?

**Comment by bparees** [comment]
(this logic is tied to the oc client binary, not the version of the cluster/webconsole they are deploying)

**Comment by spadgett** [comment]
No, it will just be ignored.

But I thought it wasn't supported already per https://github.com/openshift/origin/pull/16314#issuecomment-329165577 ?

**Comment by spadgett** [comment]
I'm OK leaving it as-is.

**Comment by bparees** [comment]
We dropped 3.6 support.  someone on a slightly older 3.7 cluster could still have issues.  it's not a big deal, just want to make sure you're aware.

**Comment by bparees** [comment]
When did the web console start treating this as the default?

**Comment by spadgett** [comment]
> When did the web console start treating this as the default?

About 15 minutes ago :)

**Comment by spadgett** [comment]
> We dropped 3.6 support. someone on a slightly older 3.7 cluster could still have issues. it's not a big deal, just want to make sure you're aware.

OK, then probably no change needed. Closing.
