### ISSUE TITLE
osc update --patch doesn't work as advertised

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1642]
```
$ _output/local/go/bin/osc  update -h
Update a resource by filename or stdin.
[...]
	# Update a pod by downloading it, applying the patch, then updating. Requires apiVersion be specified.
	$ osc update pods my-pod --patch='{ "apiVersion": "v1beta1", "desiredState": { "manifest": [{ "cpu": 100 }]}}'

Options:
  -f, --filename=[]: Filename, directory, or URL to file to use to update the resource.
      --patch='': A JSON document to override the existing resource. The resource is downloaded, patched with the JSON, then updated.
```

OK, let's try that out:

```
$ _output/local/go/bin/osc   get nodes
NAME                LABELS                  STATUS
172.16.4.110        region=infra,zone=NA    Schedulable,Ready
172.16.4.113        region=normal,zone=z1   Schedulable,Ready
172.16.4.146        region=normal,zone=z1   Schedulable,Ready
172.16.4.152        region=normal,zone=z2   Schedulable,Ready
172.16.4.158        region=normal,zone=z2   Schedulable,Ready
172.16.4.159        region=infra,zone=NA    Schedulable,Ready
$ cat > /tmp/foonode.json
{                
        "apiVersion": "v1beta1",
        "labels": {
                "region": "infra",
                "zone": "NA",
                "foo": "bar"
            }
}
$ _output/local/go/bin/osc  update node 172.16.4.110 --patch=`cat /tmp/foonode.json`
F0408 12:23:02.342063    3568 update.go:52] Error: Must provide resource and name command line params
see 'osc update -h' for help.
```

Now, it could easily be the case I did something wrong. But if so, it should tell me what that is, because I clearly followed the example and provided the parameters. If I need to add kind or name to the json, it should tell me that, not this. Or if the help is wrong, fix that and this message.

While fixing this might be a good time to also have --patch support using -f to supply a filename? Putting JSON on the cmdline is awkward.

**Comment by smarterclayton** [comment]
Doesn't seem anything obviously wrong on the command or the json.

**Comment by kargakis** [comment]
We just wrap `update` so this is an upstream problem.

**Comment by sosiouxme** [comment]
@kargakis i haven't worked directly with kube yet, could do this but it would likely be faster if you did :)

**Comment by sosiouxme** [comment]
Just noting. If I do "osc edit node/nodename" I get an error which might possibly be related.

```
# osc edit node/172.16.4.113
Error: minion "172.16.4.113" cannot be updated: the resource was updated to 2081
You must update your resource version and run `osc update -f /tmp/osc-edit-127098957` to overwrite the remote changes.
```

(I know the node resource version gets updated every few seconds but this still happens if I'm very quick with the edit or remove resourceVersion altogether)

**Comment by smarterclayton** [comment]
Basically... dont try to edit nodes yet :)

Nodes get updated too often.

**Comment by bparees** [comment]
--patch will be going away.

**Comment by smarterclayton** [comment]
Supposedly it's being resurrected.  No idea when though.

----- Original Message -----

**Comment by kargakis** [comment]
> Supposedly it's being resurrected. No idea when though.

Is there a PR upstream about it? In master it's [disabled](https://github.com/GoogleCloudPlatform/kubernetes/blob/a161edb3960c01ff6e14813858c2eeb85910009b/pkg/kubectl/cmd/update.go#L57)
