### ISSUE TITLE
confusing error message for broken kubeconfig

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1643]
```
$ _output/local/go/bin/osc  get nodes --config=/tmp/.kubeconfig
F0408 12:36:14.378556    4902 get.go:70] Error: no server found for 
```

I ran into this by accident with a "broken" .kubeconfig. Unfortunately I blew it away so I'm not sure the exact scenario, but I could reproduce it using the generated admin .kubeconfig and simply editing the file to set current-context: none. I would surmise there are likely other ways to break it.

The error message is... inscrutable. If what you're trying to say is that there's no such context, or you automatically created a context but it has no server ... then some message to that effect would be helpful.

**Comment by smarterclayton** [comment]
This is fixed upstream and will be in the next rebase.

**Comment by danmcp** [comment]
Any remaining issues here?

**Comment by sosiouxme** [comment]
It's... better anyway.

```
# osc get nodes --config=!$
osc get nodes --config=/tmp/admin.kubeconfig
Error in configuration: default cluster has no server defined
```

**Comment by smarterclayton** [comment]
I'm going to reopen, I want a better message before we cut 3.0

**Comment by cmoulliard** [comment]
What means the message "Error in configuration: default cluster has no server defined" and what is the workaround ? It seems that this message appears when no project exist when we run the command `
osc get pods or osc new-project demo` in a linux machine where openshift is running

````
alias osc="docker run --rm -i --entrypoint=osc --net=host openshift/origin:latest --insecure-skip-tls-verify"

osc login --server='https://localhost:8443'

osc new-project demo
Error in configuration: default cluster has no server defined
````

**Comment by sosiouxme** [comment]
@cmoulliard in the end it means your client configuration is not fully specified. You'll get this with an empty config file. What you are doing above creates a new docker container for each invocation of "osc" so it will never store the login configuration and starts with an empty file each time.

Not having any config is probably the most common case where you get that specific message. You could also get it if you've edited the file and fat-fingered something. In general, since the primary parts of your login (cluster, context, auth/identity) are unlikely to mean much to the casual user, errors related to "your client config is missing stuff" need to be a lot more informative.

**Comment by ashcrow** [comment]
As of 418b348498ea4d899f92f3bda3c7f46f90831435 trying to start up a Vagrant dev environment also ends up throwing this error on first try....

1. ```vagrant up```
2. ```vagrant ssh```
3. ```make build```
4. ```sudo systemctl start openshift```
5. ... wait ...
6. ```oc get nodes```
7. See error

**Comment by deads2k** [comment]
Before I change this, would "no cluster specified in kubeconfig" suit you?

**Comment by smarterclayton** [comment]
I don't think that's the message we want - cluster isn't a common user
facing thing.  Probably - "no configuration has been defined, create a
config file via oc login"

On Jun 30, 2015, at 10:44 AM, David Eads <notifications@github.com> wrote:

Before I change this, would "no cluster specified in kubeconfig" suit you?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/1643#issuecomment-117212587>.

**Comment by deads2k** [comment]
> I don't think that's the message we want - cluster isn't a common user
> facing thing.  Probably - "no configuration has been defined, create a
> config file via oc login"

Ok.  This requires refactoring all the kube `NewCmd*` methods to accept a `CheckErr` method or placing it in the `Factory`.  The `Factory` should probably be split into constituent interfaces to make it easier to track who is using what.  In all cases, this has to wait until after kube starts taking changes again.

**Comment by smarterclayton** [comment]
Just carry an upstream patch.

On Tue, Jun 30, 2015 at 1:44 PM, David Eads <notifications@github.com>
wrote:

> I don't think that's the message we want - cluster isn't a common user
> facing thing. Probably - "no configuration has been defined, create a
> config file via oc login"
>
> Ok. This requires refactoring all the kube NewCmd* methods to accept a
> CheckErr method or placing it in the Factory. The Factory should probably
> be split into constituent interfaces to make it easier to track who is
> using what. In all cases, this has to wait until after kube starts taking
> changes again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/1643#issuecomment-117277255>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
For the message and a simple check

On Tue, Jun 30, 2015 at 1:50 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> Just carry an upstream patch.
>
> On Tue, Jun 30, 2015 at 1:44 PM, David Eads <notifications@github.com>
> wrote:
>
>> I don't think that's the message we want - cluster isn't a common user
>> facing thing. Probably - "no configuration has been defined, create a
>> config file via oc login"
>>
>> Ok. This requires refactoring all the kube NewCmd* methods to accept a
>> CheckErr method or placing it in the Factory. The Factory should
>> probably be split into constituent interfaces to make it easier to track
>> who is using what. In all cases, this has to wait until after kube starts
>> taking changes again.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/issues/1643#issuecomment-117277255>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by stevekuznetsov** [comment]
+1 For "remember to login using `oc login` ... I've mentally mapped this error message to "log in" or "check kubeconfig". That mapping should be directly written.

**Comment by deanpeterson** [comment]
This is all very confusing.  When I first get openshift up and running.  Before creating any users I can run ./oc get nodes and it returns all running nodes.  After I create a user I get: "User "test-admin" cannot list all nodes in the cluster".  So I log that user out and try to get back to the state I was before (being able to call ./oc get nodes).  Then I get: "User "system:anonymous" cannot list all nodes in the cluster".  How do I get access back to run "./oc get nodes"?

**Comment by deanpeterson** [comment]
Ah, great thanks!  I looked at the admin.kubeconfig and tried logging that user in, but I was missing the -u

**Comment by smarterclayton** [comment]
Run 'oc config view' and look for something like 'name:
default/10-1-2-2:8443/system:admin' (the numbers will be different).  Then
run 'oc config use-context default/10-1-2-2:8443/system:admin'

On Wed, Jul 22, 2015 at 11:01 AM, deanpeterson <notifications@github.com>
wrote:

> This is all very confusing. When I first get openshift up and running.
> Before creating any users I can run ./oc get nodes and it returns all
> running nodes. After I create a user I get: "User "test-admin" cannot list
> all nodes in the cluster". So I log that user out and try to get back to
> the state I was before (being able to call ./oc get nodes). Then I get:
> "User "system:anonymous" cannot list all nodes in the cluster". How do I
> get access back to run "./oc get nodes"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/1643#issuecomment-123750936>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deanpeterson** [comment]
Actually when I try ./oc login -u system:admin I get the error that prevented me from using system:admin before. Is there a special password for that?  I get this error: 
"Error from server: an error on the server has prevented the request from succeeding"

When I use: ./oc config user-context default/172-19-17-143:8443/system:admin
it just thinks that is an invalid command and lists out available commands.

**Comment by liggitt** [comment]
Logging in as the system:admin will only work if your kubeconfig already has the credentials for that user. That user is certificate-based, not password based.

**Comment by deanpeterson** [comment]
i was able to get smarterclaytons command to work.  however, then when trying: ./oc get nodes I get: 
"Error in configuration: default cluster has no server defined"

So I try the commands i see in the documentation for entering certificates:
$ export KUBECONFIG=`pwd`/openshift.local.config/master/admin.kubeconfig
$ export CURL_CA_BUNDLE=`pwd`/openshift.local.config/master/ca.crt
$ sudo chmod +r `pwd`/openshift.local.config/master/admin.kubeconfig

Now I get the message again: "Error from server: User "system:anonymous" cannot list all nodes in the cluster"

I'm not very good at getting these certificates right, or getting them to stick around for some reason.

**Comment by deanpeterson** [comment]
this is my admin.kubeconfig:

apiVersion: v1
clusters:
- cluster:
    certificate-authority: ca.crt
    server: https://172.19.17.143:8443
  name: 172-19-17-143:8443
contexts:
- context:
    cluster: 172-19-17-143:8443
    user: test-admin/172-19-17-143:8443
  name: /172-19-17-143:8443/test-admin
- context:
    cluster: 172-19-17-143:8443
    namespace: default
    user: system:admin/172-19-17-143:8443
  name: default/172-19-17-143:8443/system:admin
- context:
    cluster: 172-19-17-143:8443
    namespace: test
    user: test-admin/172-19-17-143:8443
  name: test/172-19-17-143:8443/test-admin
current-context: test/172-19-17-143:8443/test-admin
kind: Config
preferences: {}
users:
- name: system:admin/172-19-17-143:8443
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDVENDQWZPZ0F3SUJBZ0lCQXpBTEJna3Foa2lHOXcwQkFRc3dKakVrTUNJR0ExVUVBd3diYjNCbGJuTm8KYVdaMExYTnBaMjVsY2tBeE5ETTJORFkxTnpZd01CNFhEVEUxTURjd09URTRNVFl3TlZvWERURTJNRGN3T0RFNApNVFl3Tmxvd056RWVNQndHQTFVRUNoTVZjM2x6ZEdWdE9tTnNkWE4wWlhJdFlXUnRhVzV6TVJVd0V3WURWUVFECkV3eHplWE4wWlcwNllXUnRhVzR3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFoKV2lzSU9rdUJ0bWdibk1mVUxRZThPYVAxeWlsa1JidkZXdUd1UDZPcmdpNkN2c3AyUW1LNkRTNDhwSUY2OXRnZwpSR3NxcDJhVEZXdGp4RjR3SStTOTJPejAwZjVXTlE3RytYdDJiRStIMzVPS0UzQ2hxWEJmVW52bzdyamducU05CktDNTEydm84TmNCZDdTSEtwZXZydGJSZDFkRkozUURtUzJzUTJUd1lZZkRwTFNZVGwrOWNRQm1iZkZKNVYrK0EKTnA0UWVGNlRrZCtENWFrL1FJN0xHVCsvcjkzR1UxSE1mWDdFRHJ6eE12WHJTQnA4TDRzSThKbU1qVFpndVBISwowRGtGZzQzQzRocERaakdkSkt1RHBrdUtMQ3dBd09kbE5EcElrbDhQM2pNSmxkQzIzOVc0Uko2aWl6K3JEUXhRCnk2KzRpMnFGTjdzNDJGWW5yQ2ZyQWdNQkFBR2pOVEF6TUE0R0ExVWREd0VCL3dRRUF3SUFvREFUQmdOVkhTVUUKRERBS0JnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUFzR0NTcUdTSWIzRFFFQkN3T0NBUUVBU1I2SApEMDFzN0VDTC9QMFpBdEN6eFI1aCtQSTVmOFB6OGhBVEJEN0hpeDJOQXhBL1JZOWJYR0dUQjFUY1FtTlZzZkQ2CnVrOFU5ajdHQ2ZwUlVOeTFCaldacS9NekVoTW9qU1I1VHA0S2V3VDJZUG1qVVNVdy9ZbEdwK2xTNDZUS29ZQ2IKZ2dxcUx2NUhhUnBkNURodVFPVkxxelpxN1NUemZibmhqUjlKbjZPZG1sZlc4c1JwMC84Nnp1VWxranNCbHFzUApER090UkRLQ1JCdUQydk5OWVNiWUhhNGk2cE82Yms3R1RWVEpKcnNrRGlRaHZOL2ZFZ3N4OG9YRGk1QkViK3FICmE2S0tmT1oyaGFTN2VFcUFRcEM4NHR1ZHYydjZTQk5adTU4QkRDTUdteXo2SkZPbUxOZndScXpGdlhrejdVZUkKZXJKOW5NRDlVTFQ5WXF6WWhRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMlZvckNEcExnYlpvRzV6SDFDMEh2RG1qOWNvcFpFVzd4VnJocmoranE0SXVncjdLCmRrSml1ZzB1UEtTQmV2YllJRVJyS3FkbWt4VnJZOFJlTUNQa3ZkanM5TkgrVmpVT3h2bDdkbXhQaDkrVGloTncKb2Fsd1gxSjc2TzY0NEo2alBTZ3VkZHI2UERYQVhlMGh5cVhyNjdXMFhkWFJTZDBBNWt0ckVOazhHR0h3NlMwbQpFNWZ2WEVBWm0zeFNlVmZ2Z0RhZUVIaGVrNUhmZytXcFAwQ095eGsvdjYvZHhsTlJ6SDEreEE2ODhUTDE2MGdhCmZDK0xDUENaakkwMllManh5dEE1QllPTnd1SWFRMll4blNTcmc2WkxpaXdzQU1EblpUUTZTSkpmRDk0ekNaWFEKdHQvVnVFU2Vvb3MvcXcwTVVNdXZ1SXRxaFRlN09OaFdKNnduNndJREFRQUJBb0lCQUNCbE9CUzUyNWN4d01LYwowNHZrU2tyYnJIeHQ3VTFzdDFmcSs4Z2s1QmdrQnhxbHBUZUxIWHZ0aXY2dTVqMlZuUkR5SWFieDNHLy91VW5kCmNzeHFEU1hldHpLbU9lcFBiaXhwOHVUcnI4N29tK3p3aU5FUG1CZ2RDeXJrcWRtUXkzUEtFV0t2aUt5QXRuTkoKYk1mdmd3Sld5dE5Sa3lnWE1KTWltb3FnVmp5cjFoTWtOTHJVaTU1TTg2SjJSZDIzN0x6MUFmY0x5SzdtY0hpZgpkTlFZOHpTQXJKaG16WGIzbVlLdURBekcvZ1E2eEhxMzVpZEVLTERjcnA4RjI2UVVnU0VhMVRlWWlqOFN6S0R4ClFxTEQ3QmUzb0dGaXk3Qm0wMlJGa0tjRVJsT0dWNHpoYmZ6OHM1Vmt0YVJUM1Mxait2ZUR5YVZwRnZURHQ0ME0KYWIyRXFnRUNnWUVBN1Jab1FNTnNjcmpoSHZBS3ZaYy9OTTNacjBpM1ZvbGtESG16NFBMM2pLUUZoSVZzLzBGQwp4NXZweTY5c1MzZEU0TW9pbngzYWwwK0VycnNlSzRGS2JELzc2aWNkZEI3N2kwVUw1QmJnT1ZNQUF0SVlpWUdRCmpnNjU0R2ZuM2N1OFd2TjhkbnB2Q1ZuT3hQN1c0bDBabWRUVndjNWV6ME9YV25HSGVTaWZxNkVDZ1lFQTZyQysKWmtnclVWOXN4Q3dncElEZXpDNDZrM2hackk1S1d1MURRRmVxVDVYalJTaVBjOXZ4U1kydDhOdUdzY0krWFllTwp0ZUw5R3BjYkFCdFQ3UXkzSTN0cmhSdXQ5M21nT1ZvOXNka2ZYWXdzNHN1enIybUhEUEJZclA2RTFjUWRYRXpMCnM1Z3oreEczTDVNYUF4MnlwczhGTkZTY3FaSGJtWlBZSU9CNnlBc0NnWUVBeWVmL09NZzBueTZiYVVGN3BDSWUKRGRZUXdKbm9xS1d3c244aWxUdlZYY3lCZG00NmVOY1hDKzdYbUVMNHN2d0xpSFFjTCsyNHJvdGxyM2hqSlNHaQpRN1hwejJzb1JpL3NnSnA0bWZKeFdlQTViaTJGLy9SN0tyK1h4R2c0cWtaTFRobDFzV0JyRjBlSU0zUGpoRHROCkJoaWZRY0dDTkhpWGVNcWVXS3dqN29FQ2dZRUE0ZWppVG5pWDRndDJHbHZUekNZVTBQeUsvQnQwVG9ybGZpTTMKZ2o4Z3ZOMHVXUXNURTFhYks4OUtxVGZYcjFLb1Q4WEdGTVY4RjlWdWN5cmJIYXNJdXduNTFMWnhQbkFBVUZUUwpZRmo5UFVKS2pzSEFwRkJ6Wkh3VEQrc3NHTTFmNmRJdW55RWFvRXBNU0dwVU5yMm1rN1ZoY0I4bWNuL3BvQ3JWCmQ4Zzl5RU1DZ1lFQXV4RmFsRmJ0b1o2aVlQL3c5eDNrSUQyVTZIR2xhUkpnckJUVHpSeEE2aXBuNUdMRHh4bmEKZHNVVW1vNFBkcHNjd2YwZWFxZ3U4OGkzOTBmb2l4V3hlVDNaYi92VUQ0V1E0OC9xeERlQldJY1pWK2F5dmREUAp1NHZFN2NqZTZ3NTNMaTRHS3lFVGFZVWU5Qk1TWjFnTGVzSGZpZXQ2L3k0Ulp1TkRESktONDFBPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
- name: test-admin/172-19-17-143:8443
  user: {}

**Comment by deanpeterson** [comment]
Alright.  I ran ./oc config use-context default/172-19-17-143:8443/system:admin

then ./oc whoami

then ./oc get nodes again and now it works.  Thanks for your help guys.

**Comment by lorenzvth7** [comment]
I've also ```oc get nodes``` output: ```Error in configuration: default cluster has no server defined```. I get this after a while. Just after running the Ansible Installer the command works fine.

**Comment by deads2k** [comment]
@sosiouxme I'm pretty sure that clayton fixed this in 3.1. Can you confirm?

**Comment by sosiouxme** [comment]
@deads2k I would say the message is vastly improved for the most common case:

```
# oc get nodes
error: No configuration file found, please login or point to an existing file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
```

However it's worth mentioning that this is misleading in a couple cases. One is if the file is simply empty (as with our AMIs before starting the server), another is if you've specified a bogus context:

```# oc config set-context foo
context "foo" set.
# oc get nodes
error: No configuration file found, please login or point to an existing file:
[...]
```

If we wanted to be really clear, we'd distinguish between "no config file" and "no context found in your config file". Up to your judgment whether we want to keep this issue open for that.

**Comment by deads2k** [comment]
> If we wanted to be really clear, we'd distinguish between "no config file" and "no context found in your config file". Up to your judgment whether we want to keep this issue open for that.

I think that case is a little pathological.  If you use something other than `oc login` and `oc project`, you're a pretty advanced user.

In both cases, the advice to login is good.
