### ISSUE TITLE
cannot connect to socket within a container

### ISSUE THREAD

**Issue by MarWestermann** [openshift/origin#16433]
Hi I have an openshift 1.5 cluster installed by the advanced installation method (ansible)
Everything worked but now I have problems running containers which want to connect to a unix socket.
For example running the default openshift mariadb or mysql templates don't work cause in the entrypoint script it tries to connect to mysqld via socket and that fails (permission denied).

Now I have a container running unicorn and nginx where nginx tries to connect to unicorn via socket. But again that doesn't work. nginx error logs say:
127#0: *1 connect() to unix:/tmp/application.sock failed (13: Permission denied) while connecting to upstream,

As the same container works running on my local docker instance I guess this is an selinux problem - but I have no idea how I should solve that.

Any help is appreciated.

##### Version
openshift v1.5.0
kubernetes v1.5.2+43a9be4

**Comment by melvz** [comment]
@MarWestermann 

Tried  command "getenforce" ?

~

**Comment by MarWestermann** [comment]
@melvz Not sure what you mean.. where should I try it?

If I run it on the master or on one of nodes I get: "Enforcing" as response.
Within the container where the socket connection fails this command is not available.
