### ISSUE TITLE
Rebase openshift/kubernetes from 1.7.0 to 1.7.6

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#16456]
# Rebase openshift/kubernetes from 1.7.0 to 1.7.6

This issue is automatically generated and contains the list of **174 commits** from the [OpenShift Kubernetes fork](https://github.com/openshift/kubernetes) which should be evaluated for merge into **release-1.7.6** from **release-1.7.0**.

The command used to generate these commits was:

    git --no-pager log --oneline --no-color --reverse openshift/release-1.7.0 --not release-1.7.6

For each commit, resolve the task by doing **one** of the following:

* ✅ Opening and referencing a pull request to the **release-1.7.6** branch for the commit
* ❌ Striking out the commit for cause (e.g. a drop)

When all commits are accounted for, this issue can be closed.

| 🚦 | Commit  | Comments |
| -- | :------- | :----------- |
| | openshift/kubernetes@834c0e2 `UPSTREAM: <carry>: reallow the ability to post across namespaces in api`| | |
| | openshift/kubernetes@c49dd59 `UPSTREAM: <carry>: add kubelet timeouts`| | |
| | openshift/kubernetes@0ffd537 `UPSTREAM: <carry>: Tolerate node ExternalID changes with no cloud provider`| | |
| | openshift/kubernetes@52483ac `UPSTREAM: <carry>: Add our types to kubectl get error`| | |
| | openshift/kubernetes@21bd476 `UPSTREAM: <carry>: Allow overriding default generators for run`| | |
| | openshift/kubernetes@7474fab `UPSTREAM: <carry>: force import ordering for stable codegen`| | |
| | openshift/kubernetes@7f6c271 `UPSTREAM: <drop>: merge multiple registrations for the same group`| | |
| | openshift/kubernetes@3e46076 `UPSTREAM: <carry>: add service serving cert signer to token controller`| | |
| | openshift/kubernetes@8fdc5ee `UPSTREAM: <carry>: fix fifo resync, remove after FIFO is dead`| | |
| | openshift/kubernetes@b27b44b `UPSTREAM: <carry>: ignored namespace lifecycle resources`| | |
| | openshift/kubernetes@91c5ee8 `UPSTREAM: <carry>: Disable file locking in clientcmd`| | |
| | openshift/kubernetes@669a661 `UPSTREAM: <carry>: Disable e2e pre-check on scheduler predicates`| | |
| | openshift/kubernetes@e36334f `UPSTREAM: <drop>: add origin resource shortcuts to kube shortcut restmapper`| | |
| | openshift/kubernetes@8449edf `UPSTREAM: <carry>: Double container probe timeout`| | |
| | openshift/kubernetes@a25b866 `UPSTREAM: <carry>: Increase service endpoint test timeout`| | |
| | openshift/kubernetes@af0acf6 `UPSTREAM: <carry>: Pod deletion can be contended, causing test failure`| | |
| | openshift/kubernetes@3c4c622 `UPSTREAM: docker/engine-api: 26718: Add Logs to ContainerAttachOptions`| | |
| | openshift/kubernetes@4d55cc3 `UPSTREAM: <carry>: update clientset generator for openshift groups`| | |
| | openshift/kubernetes@a5017af `UPSTREAM: carry: google.golang.org/grpc 231b4cfea0e79843053a33f5fe90bd4d84b23cd3 for kubelet api`| | |
| | openshift/kubernetes@c502d10 `UPSTREAM: <carry>: match kube rbac setup in e2es with openshift kinds`| | |
| | openshift/kubernetes@70dc7f8 `UPSTREAM: <carry>: openapi test, patch in updated package name`| | |
| | openshift/kubernetes@c50acbe `UPSTREAM: 00000: make AsVersionedObjects default cleanly`| | |
| | openshift/kubernetes@b28bb71 `UPSTREAM: <carry>: Fix to avoid REST API calls at log level 2.`| | |
| | openshift/kubernetes@f3981f2 `UPSTREAM: 00000: disambiguate operation names for legacy discovery`| | |
| | openshift/kubernetes@da10320 `UPSTREAM: <drop>: drop post 3.7 rebase. allows disabled aggregator`| | |
| | openshift/kubernetes@493a9b8 `UPSTREAM: <carry>: remove JSON codec`| | |
| | openshift/kubernetes@ba30d10 `UPSTREAM: 47975: make proto time precision match json`| | |
| | openshift/kubernetes@dbd49b0 `UPSTREAM: 48017: Plumb preferred version to nested object encoder`| | |
| | openshift/kubernetes@62d17ba `UPSTREAM: 47740: Add websocket protocol authentication method`| | |
| | openshift/kubernetes@c2b29a7 `UPSTREAM: 47740: Use websocket protocol authenticator in apiserver`| | |
| | openshift/kubernetes@1fd8f84 `UPSTREAM: <carry>: add patch to allow shimming SCC`| | |
| | openshift/kubernetes@83328f4 `UPSTREAM: <carry>: update client namer rules for amguity`| | |
| | openshift/kubernetes@2abd137 `UPSTREAM: <carry>: update group references`| | |
| | openshift/kubernetes@b2a6ee2 `UPSTREAM: 47823: don't pass CRI error through to waiting state reason`| | |
| | openshift/kubernetes@8893753 `UPSTREAM: 47094: prioritize messages for long steps`| | |
| | openshift/kubernetes@dfa1538 `UPSTREAM: 47919: Use %q formatter for error messages from the AWS SDK. #47789`| | |
| | openshift/kubernetes@afc76b1 `UPSTREAM: 47367: Add client side event rate limiting`| | |
| | openshift/kubernetes@84e38dc `UPSTREAM: 48261: Fix removing finalizer for garbage collector`| | |
| | openshift/kubernetes@4acb1db `UPSTREAM: 48343: don't accept delete tokens that are waiting to be reaped`| | |
| | openshift/kubernetes@0f828da `UPSTREAM: 44784: Handle vendored names in OpenAPI gen`| | |
| | openshift/kubernetes@74331ec `UPSTREAM: 48354: allow a deletestrategy to opt-out of GC`| | |
| | openshift/kubernetes@c2d4fd1 `UPSTREAM: 48394: GuaranteedUpdate must write if stored data is not canonical`| | |
| | openshift/kubernetes@695b561 `UPSTREAM: 47347: actually check for a live discovery endpoint before aggregating`| | |
| | openshift/kubernetes@1db9f69 `UPSTREAM: <carry>: commit generated openapi`| | |
| | openshift/kubernetes@d103c73 `manual SHA after rebase merges`| | |
| | openshift/kubernetes@8f6518d `UPSTREAM: <drop>: generated updates`| | |
| | openshift/kubernetes@db729e1 `UPSTREAM: 45894: Export BaseControllerRefManager`| | |
| | openshift/kubernetes@c9881ff `UPSTREAM: <carry>: allow to use * as a capability in Security Context Constraints.`| | |
| | openshift/kubernetes@4099b0d `UPSTREAM: <drop>: regenerated openapi because it's not commited`| | |
| | openshift/kubernetes@b2cae02 `UPSTREAM: <drop>: keep old pod available`| | |
| | openshift/kubernetes@e08bc10 `UPSTREAM: 49130: expose RegisterAllAdmissionPlugins`| | |
| | openshift/kubernetes@c0b6824 `UPSTREAM: 49131: expose direct from config new scheduler method`| | |
| | openshift/kubernetes@fd8245a `UPSTREAM: 49132: make a union categoryexpander`| | |
| | openshift/kubernetes@9e89d59 `UPSTREAM: <carry>: make wiring in kubeproxy easy until we sort out config`| | |
| | openshift/kubernetes@eb464d0 `UPSTREAM: <carry>: compensate for poor printer behavior`| | |
| | openshift/kubernetes@b5fd2fe `UPSTREAM: <carry>: increase wait in kubecontrollers`| | |
| | openshift/kubernetes@5d62f5a `UPSTREAM: 49133: update permissions to allow block owner deletion`| | |
| | openshift/kubernetes@9449c21 `UPSTREAM: 49134: tolerate missing template`| | |
| | openshift/kubernetes@ee3707b `UPSTREAM: 49136: don't mutate printers after creation`| | |
| | openshift/kubernetes@95310f1 `UPSTREAM: <drop>: hack out portworx to avoid double proto registration`| | |
| | openshift/kubernetes@cc92323 `UPSTREAM: 45294: Fix protobuf generator for aliases to repeated types`| | |
| | openshift/kubernetes@d8d0924 `UPSTREAM: <carry>: generator updates`| | |
| | openshift/kubernetes@500ca5b `UPSTREAM: <carry>: squash to SCC`| | |
| | openshift/kubernetes@bd70969 `UPSTREAM: 49137: proxier is it really nil`| | |
| | openshift/kubernetes@852cacb `UPSTREAM: <carry>: allow separate mapping fo kind`| | |
| | openshift/kubernetes@504c0cd `UPSTREAM: <drop>: disable suspicously failing tests`| | |
| | openshift/kubernetes@179aa7d `UPSTREAM: <drop>: restore normal alias test`| | |
| | openshift/kubernetes@fdf530d `UPSTREAM: 49139: expose proxy default`| | |
| | openshift/kubernetes@e68a0a2 `UPSTREAM: 48481: protect against nil panic in apply`| | |
| | openshift/kubernetes@39c4336 `UPSTREAM: 48582: Fixes oc delete ignoring --grace-period.`| | |
| | openshift/kubernetes@562dfc7 `UPSTREAM: 48578: run must output message on container error`| | |
| | openshift/kubernetes@d922ac5 `UPSTREAM: 48733: Never prevent deletion of resources as part of namespace lifecycle`| | |
| | openshift/kubernetes@cd6e04a `UPSTREAM: 48613: proxy/userspace: honor listen IP address as host IP if given`| | |
| | openshift/kubernetes@cd3c25c `UPSTREAM: 48884: Do not mutate pods on update`| | |
| | openshift/kubernetes@b9ade08 `UPSTREAM: <drop>: Adapt etcd testing util to v3.2.1`| | |
| | openshift/kubernetes@ee5396b `UPSTREAM: 49120: Modify podpreset lister to use correct namespace`| | |
| | openshift/kubernetes@c429869 `UPSTREAM: 48635: proxy/userspace: suppress "LoadBalancerRR: Removing endpoints" message`| | |
| | openshift/kubernetes@bae6acf `UPSTREAM: 48960: No warning event for DNSSearchForming`| | |
| | openshift/kubernetes@441e130 `UPSTREAM: 47731: Use endpoints informer for the endpoint controller.`| | |
| | openshift/kubernetes@0409b13 `UPSTREAM: 47788: Get rid of 30s ResyncPeriod in endpoint controller.`| | |
| | openshift/kubernetes@fae1160 `UPSTREAM: 49230: use informers for quota calculation`| | |
| | openshift/kubernetes@ff1c861 `UPSTREAM: 49285: do not mutate statefulset on update`| | |
| | openshift/kubernetes@4b5f969 `UPSTREAM: Revert "UPSTREAM: <drop>: keep old pod available"`| | |
| | openshift/kubernetes@71b418e `UPSTREAM: 49111: Fix findmnt parsing in containerized kubelet`| | |
| | openshift/kubernetes@9cb9aa3 `UPSTREAM: 49227: tighten quota controller interface`| | |
| | openshift/kubernetes@61db1a6 `UPSTREAM: 49079: Restore cadvisor prometheus metrics`| | |
| | openshift/kubernetes@0dbbf9e `UPSTREAM: 48709: glusterfs: retry without auto_unmount only when it's not supported`| | |
| | openshift/kubernetes@aeed236 `UPSTREAM: 49127: Make definite mount timeout for glusterfs volume mount`| | |
| | openshift/kubernetes@105bace `UPSTREAM: 49312: allow the /version endpoint to pass through`| | |
| | openshift/kubernetes@824b8b4 `UPSTREAM: 49379: Pass clientset's Interface to CreateScheduler.`| | |
| | openshift/kubernetes@cbab26d `UPSTREAM: 49326: add cronjobs to all`| | |
| | openshift/kubernetes@3748f10 `UPSTREAM: 49353: Use specified ServerName in aggregator TLS validation`| | |
| | openshift/kubernetes@e26f605 `UPSTREAM: 49395: rate limiting should not affect system masters`| | |
| | openshift/kubernetes@dc54815 `UPSTREAM: 49444: Do not spin forever if kubectl drain races with other removal`| | |
| | openshift/kubernetes@922cecc `UPSTREAM: 48940: support fc volume attach and detach`| | |
| | openshift/kubernetes@b465bc1 `UPSTREAM: 48518: Kubelet client cert initialization (and 48519)`| | |
| | openshift/kubernetes@8669077 `UPSTREAM: 49514: Make client bootstrap public`| | |
| | openshift/kubernetes@5afb9a3 `UPSTREAM: 48778: check for negative values`| | |
| | openshift/kubernetes@c7a70b8 `UPSTREAM: 49118: Allow unmounting bind-mounted directories.`| | |
| | openshift/kubernetes@90d0a3f `UPSTREAM: 49475: Fixed glusterfs mount options`| | |
| | openshift/kubernetes@70f1b13 `UPSTREAM: revert: 1b2aacbd4010757b6978ddc40bfc8d89495c89dd: <carry>: allow to use * as a capability in Security Context Constraints.`| | |
| | openshift/kubernetes@fd7d49b `UPSTREAM: 48224: add reflector metrics`| | |
| | openshift/kubernetes@f2c3b93 `UPSTREAM: 49656: make admission tolerate object without objectmeta for errors`| | |
| | openshift/kubernetes@6abc2d5 `UPSTREAM: 49114: Move generators to staging/src/k8s.io/kube-gen`| | |
| | openshift/kubernetes@4484b47 `UPSTREAM: 49495: make it possible to allow discovery errors for controllers`| | |
| | openshift/kubernetes@6dad163 `UPSTREAM: <carry>: Do not error out on pods in kube-system`| | |
| | openshift/kubernetes@73e7163 `UPSTREAM: <drop>: disable openapi aggregation`| | |
| | openshift/kubernetes@9fa4138 `UPSTREAM: 49724: skip WaitForAttachAndMount for terminated pods in syncPod`| | |
| | openshift/kubernetes@0403bda `UPSTREAM: 49448: Use an interface in lock election`| | |
| | openshift/kubernetes@0ea2901 `UPSTREAM: <drop>: make openapi handler serialize in the background`| | |
| | openshift/kubernetes@4639d4b `UPSTREAM: <drop>: pickup clientgen changes`| | |
| | openshift/kubernetes@6f1507d `UPSTREAM: <drop>: update kubernetes types for new codegen syntax`| | |
| | openshift/kubernetes@128cd95 `UPSTREAM: revert: 7fc9d38a7a: <drop>: drop post 3.7 rebase. allows disabled aggregator`| | |
| | openshift/kubernetes@d4ab07d `UPSTREAM: revert: fbf1f04: <drop>: disable openapi aggregation"`| | |
| | openshift/kubernetes@c55470e `UPSTREAM: 00000: allow nil openapispec`| | |
| | openshift/kubernetes@618e569 `UPSTREAM: <drop>: allow duplicate openapi paths. this is moved in 1.8`| | |
| | openshift/kubernetes@ce2eddd `UPSTREAM: <drop>: don't hold API server start on superslow openapi aggregation. Should be baster in 1.8`| | |
| | openshift/kubernetes@1d8e59d `UPSTREAM: <drop>: aggregate openapi through servers. 1.8 should fix this for CRD`| | |
| | openshift/kubernetes@54edac9 `UPSTREAM: <drop>: regenerate clientsets using updated codegen`| | |
| | openshift/kubernetes@eb89032 `UPSTREAM: 49919: Fix duplicate metrics collector registration attempt error`| | |
| | openshift/kubernetes@f6d8699 `UPSTREAM: 50019: create default selection functions for storage`| | |
| | openshift/kubernetes@2e8d5ea `UPSTREAM: 49992: Correctly handle empty watch event cache`| | |
| | openshift/kubernetes@3348bbc `UPSTREAM: 50259: provide the failing health as part of the controller error`| | |
| | openshift/kubernetes@99cfe6e `UPSTREAM: revert: ffead55: <carry>: Fix to avoid REST API calls at log level 2.`| | |
| | openshift/kubernetes@80a4ecf `UPSTREAM: 49972: remove dead log handler and increase verbosity`| | |
| | openshift/kubernetes@42b070a `UPSTREAM: 47267: flag support in kubectl plugins`| | |
| | openshift/kubernetes@f3d80ec `UPSTREAM: <drop>: regenerated openapi`| | |
| | openshift/kubernetes@9f9e9dc `UPSTREAM: 49868: Status objects for 404 API errors will have the correct APIVersion`| | |
| | openshift/kubernetes@5dac881 `UPSTREAM: 50139: skip generation of informers and listers on resources with missing verbs`| | |
| | openshift/kubernetes@050b6e1 `UPSTREAM: <drop>: skip TSB namespace when checking for scheduled pods`| | |
| | openshift/kubernetes@118d6eb `UPSTREAM: 48480: Ensure namespace exists as part of RBAC reconciliation`| | |
| | openshift/kubernetes@02068a7 `UPSTREAM: 50639: Extend SetHeader Requests method ito accept multiple values`| | |
| | openshift/kubernetes@cd06e57 `UPSTREAM: 50702: Allow injection of policy in RBAC post start hook`| | |
| | openshift/kubernetes@4c0b639 `UPSTREAM: 50710: Refactor RBAC authorizer entry points`| | |
| | openshift/kubernetes@2177231 `UPSTREAM: 49902: Allow update to GC fields for RBAC resources`| | |
| | openshift/kubernetes@00447f9 `UPSTREAM: revert: c502d10: <carry>: match kube rbac setup in e2es with openshift kinds`| | |
| | openshift/kubernetes@4c6e2a4 `UPSTREAM: 50620: allow default option values - oc adm top node\|pod`| | |
| | openshift/kubernetes@4741422 `UPSTREAM: 50911: add diff details to pod validation error`| | |
| | openshift/kubernetes@df156b8 `UPSTREAM: 50934: Skip non-update endpoint updates`| | |
| | openshift/kubernetes@2b31ea0 `UPSTREAM: 51144: Fix unready endpoints bug introduced in #50934`| | |
| | openshift/kubernetes@48bf073 `UPSTREAM: 51197: provide a default field selector for name and namespace`| | |
| | openshift/kubernetes@878fec3 `UPSTREAM: 51208: Add an OrDie version for AddPostStartHook`| | |
| | openshift/kubernetes@3dc98da `UPSTREAM: <carry>: allow PV controller recycler template override`| | |
| | openshift/kubernetes@5cbdf4a `UPSTREAM: 51534: update scheduler to return structured errors instead of process exit`| | |
| | openshift/kubernetes@b8c8534 `UPSTREAM: 51535: allow disabling the scheduler port`| | |
| | openshift/kubernetes@ad4c2a9 `UPSTREAM: revert: dcb5eef2d8a6d14816d8d1f767f0d0016b84dcdf: "UPSTREAM: <drop>: hack out portworx to avoid double proto registration"`| | |
| | openshift/kubernetes@4e04b2d `UPSTREAM: 51473: Fix cAdvisor prometheus metrics`| | |
| | openshift/kubernetes@54db91b `UPSTREAM: 50258: Add token group adder component`| | |
| | openshift/kubernetes@c6ba5dd `UPSTREAM: 50258: Add token cache component`| | |
| | openshift/kubernetes@aa527ff `UPSTREAM: 50258: Add union token authenticator`| | |
| | openshift/kubernetes@d43859d `UPSTREAM: 50258: Simplify bearer token auth chain, cache successful authentications`| | |
| | openshift/kubernetes@3ea3483 `UPSTREAM: 51638: allow to generate extended methods in client-go`| | |
| | openshift/kubernetes@cbf016d `UPSTREAM: 51705: Address panic in TestCancelAndReadd`| | |
| | openshift/kubernetes@ff142db `UPSTREAM: 51727: ensure all unstructured resources`| | |
| | openshift/kubernetes@fc67dd3 `UPSTREAM: 51636: add reconcile command to kubectl auth`| | |
| | openshift/kubernetes@1034788 `UPSTREAM: 51148: Enable finalizers independent of GC enablement`| | |
| | openshift/kubernetes@b7f0905 `UPSTREAM: 49142: Slow-start batch pod creation of rs, rc, ds, jobs`| | |
| | openshift/kubernetes@07d7de9 `UPSTREAM: <drop>: Fix result type in fake clientset generator`| | |
| | openshift/kubernetes@284628f `UPSTREAM: 51803: make url parsing in apiserver configurable`| | |
| | openshift/kubernetes@6bfc410 `UPSTREAM: 51932: fix format of forbidden messages`| | |
| | openshift/kubernetes@558e438 `UPSTREAM: 50843: FlexVolume: Add ability to control 'SupportsSELinux' during driver's init phase`| | |
| | openshift/kubernetes@6b54a66 `UPSTREAM: 49219: Use case-insensitive header keys for --requestheader-group-headers.`| | |
| | openshift/kubernetes@ab439de `UPSTREAM: 49133: add controller permissions to set blockOwnerDeletion`| | |
| | openshift/kubernetes@65fc0d9 `UPSTREAM: 45345: Support "fstype" parameter in dynamically provisioned PVs`| | |
| | openshift/kubernetes@1697e18 `UPSTREAM: 48502: Add a refreshing discovery client`| | |
| | openshift/kubernetes@77b4864 `UPSTREAM: 49416: FC volume plugin: remove block device at DetachDisk`| | |
| | openshift/kubernetes@0744085 `UPSTREAM: 52092: Fix resource quota controller panic (Drop in 1.8)`| | |
| | openshift/kubernetes@c8af5fb `UPSTREAM: 50094: apimachinery: remove pre-apigroups import path logic`| | |
| | openshift/kubernetes@370f441 `UPSTREAM: 52127: Fix deployment timeout reporting`| | |
| | openshift/kubernetes@399c7a6 `bump(k8s.io/code-generator): UPSTREAM: <drop>: rename generators to match upstream`| | |
| | openshift/kubernetes@f803a7f `bump(k8s.io/code-generator): UPSTREAM: <drop>: handle kube-gen rename`| | |
| | openshift/kubernetes@e5a3e2e `UPSTREAM: 52344: Do not log spam image pull backoff`| | |
| | openshift/kubernetes@e42de55 `Avoid printing node list for LoadBalancer in log file`| | |
| | openshift/kubernetes@2d49edd `sync(git@github.com:/openshift/origin.git): 87ceff292ab199dc902b52f942951f1b7b88e4fa`| | |

**Comment by ironcladlou** [comment]
@soltysh @deads2k @liggitt experimenting with a little tool to generate the issue body for this work. Let me know if it looks correct/useful.

**Comment by deads2k** [comment]
It looks good.  I'd say that the boolean choice for each item may be a little difficult.  Any way to get a table with checkboxes in it so you have a column for disposition and comments?

**Comment by ironcladlou** [comment]
@deads2k 
>It looks good. I'd say that the boolean choice for each item may be a little difficult. Any way to get a table with checkboxes in it so you have a column for disposition and comments?

I'm using a template to render the Markdown, so we can do anything within those constraints... unfortunately task lists aren't supported within tables, so we'd have to fake it.

How about something like...

| 🚦| Commit |Comments |
| -- | :------ | :----------- |
| ✅ | openshift/kubernetes@834c0e2 UPSTREAM: <carry>: reallow the ability to post across namespaces in api | [PR](http://example.com) |
|  | openshift/kubernetes@0ffd537 UPSTREAM: <carry>: Tolerate node ExternalID changes with no cloud provider | |
| ❌ | openshift/kubernetes@c49dd59 UPSTREAM: <carry>: add kubelet timeouts | Dropped for $reason |

Better? Worse? Other suggestions?

**Comment by smarterclayton** [comment]
Are you going to do one the other way?  All patches added to the upstream release stream that we don't have?

**Comment by soltysh** [comment]
:+1: for the table

**Comment by ironcladlou** [comment]
Talking with @soltysh, we are going to modify the approach and instead use a tool to generate a description for the actual fork rebase PR which will look similar to this issue in that it will:

1. Show we came up with the list of commits in the PR
2. Detail *only those commits* which did not apply cleanly by calling them out and linking the to their correlating rewritten commit
