### ISSUE TITLE
FAILURE after 0.321s: test/cmd/images.sh:108: executing 'oc get istag/tag:1 -o jsonpath={.image.dockerImageReference}' expecting success and text 'wildfly.*@sha256:': the output content test failed

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#16468]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/test_pull_request_origin_cmd/3249/

/kind test-flake
/area image
@bparees @mfojtik

**Comment by bparees** [comment]
This looks like a race condition, we modified the wildfly tag to be from mysql:

os::cmd::expect_success "oc patch istag/wildfly:latest -p='{\"tag\":{\"from\":{\"kind\":\"DockerImage\",\"name\":\"mysql:latest\"}}}'"

then a bit later we turn on scheduled importing:

os::cmd::expect_success "oc patch istag/wildfly:latest -p='{\"tag\":{\"importPolicy\":{\"scheduled\":true}}}'"


then we create tag:1 from wildfly:latest:
os::cmd::expect_success 'oc create imagestreamtag tag:1 --from=wildfly:latest'

and then expect tag:1 to still point to wildfly:
os::cmd::expect_success_and_text 'oc get istag/tag:1 -o jsonpath={.image.dockerImageReference}' 'wildfly.*@sha256:'


but if the scheduled import happened, it's going to point to mysql instead.

It's not terribly obvious to me what this is testing:

os::cmd::expect_success "oc patch istag/wildfly:latest -p='{\"tag\":{\"importPolicy\":{\"scheduled\":true}}}'"
os::cmd::expect_success_and_text 'oc get istag/wildfly:latest -o jsonpath={.tag.importPolicy.scheduled}' 'true'

So i'm somewhat inclined to just delete it.  I guess we could also just set it back to false immediately after setting it to true.

@soltysh @dmage @dmage @miminar thoughts/background on this test?

**Comment by soltysh** [comment]
My personal recommendation would be to split those tests into two separate one, rather then deleting. As usual I'll be hesitant to remove test, but 👍 for fixing it.

**Comment by bparees** [comment]
> My personal recommendation would be to split those tests into two separate one, rather then deleting. As usual I'll be hesitant to remove test, but 👍 for fixing it.

I would normally agree, but I don't see what this is "testing".  It's just doing a patch to a resource and confirming the patch was set.  Surely we have patch testing elsewhere, and we have scheduled import testing elsewhere?

**Comment by soltysh** [comment]
Good point, do it then.
