### ISSUE TITLE
oc policy should support specifying a service account in a different namespace

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#16460]
Currently, `oc policy` has a -z argument which specifies the "service account in the current namespace to use as a user".  This isn't compatible with granting a service account in a *different namespace* some cluster role in the current namespace.  The RFE is to avoid having to write something like `oc project "${NAMESPACE_B}"; oc policy add-role-to-user edit "system:serviceaccount:${NAMESPACE_A}:sa"`

**Comment by jim-minter** [comment]
copy/paste of google doc comments:

Clayton Coleman: Use -z here

Jim Minter: By this point I'm in namespace myapp, so I don't think I can.

Clayton Coleman: -z -n

Jim Minter: Sorry for labouring a point, but I don't think -z -n works for me - it grants edit permissions in a specified namespace to a service account in the same specified namespace.  I want to grant permissions in the current namespace to a service account in a different, specified, namespace.

Clayton Coleman: I meant though that you don't want to do this model for creating the service account.  Reorganize the steps until you don't need to do that.

Jim Minter: How? The docs say -z is "service account in the current namespace to use as a user" - how can this be used to grant access across namespaces?

Clayton Coleman: If we can't express grant other namespace service account in this namespace that's a fairly big hole that I would expect we would fix.  It means we have a crappy experience and users should never have to remember an arbitrary name sequence.

**Comment by liggitt** [comment]
upstream commands use `kubectl create rolebinding my-binding --clusterrole=edit --serviceaccount=sa-namespace:sa-name --namespace=mynamespace`... I'd expect to move in that direction in 3.7 timeframe
