### ISSUE TITLE
Deleting a build pod does not seem to be detected by the build controller

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1646]
No new pod was created within a few minutes, nor was the build marked failed.

Scenario:

1. Start openshift with --images="openshift/origin-${component}:non-existent-tag"
2. Start a build
3. The build and build pod stays in pending forever (no such image origin-sit-build:non-existent-tag)
4. Delete the build pod

Observe:

1. Build pod is not recreated
2. Build is not marked failed (stays in pending).

**Comment by bparees** [comment]
We can't get events for deleted things, right?  so we have to handle this via reconciliation?

**Comment by bparees** [comment]
btw I assume #3 is expected behavior?  so the expected behavior is that either we should recreate the build pod, or fail the build.

**Comment by smarterclayton** [comment]
Can't guarantee you get the event in all cases, correct.  

----- Original Message -----

**Comment by smarterclayton** [comment]
Probably fail the build.

**Comment by bparees** [comment]
fixed with https://github.com/openshift/origin/pull/2465, close at your leisure.
