### ISSUE TITLE
annotate templateinstances when they are created by the broker

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16479]
The web console would like to be able to understand what resources were created as a result of a service provision operation.

If the TSB annotated the templateinstance object, then the web console could look at a given resource and see that:

1) the resource has an ownerref pointing to the template instance
2) the template instance is annotated as having been created by the TSB

And determine that the resource in question is part of a service provision.  Which I believe is one of the things they want to be able to do.

@spadgett sound right?  I don't know if there's any useful value we can put in the annotation that would help you further to know *which* serviceinstance it's associated with.

/cc @jim-minter

**Comment by bparees** [comment]
@spadgett I figured you could also hide resources that are associated w/ a known SC-spawned template instance.  Or move them to another section of the console.

**Comment by ncameronbritt** [comment]
My feeling is that eventually we might want to collapse the provisioned service and whatever resources it creates into one thing. So if your service instantiates a database template, the service instance and that database deployment appear to be one and the same. I'm not sure that the user needs to care about all of the misdirection that has to happen under the covers.

On the one hand I think we'd want the experience of provisioning a database in a project and provisioning a hosted database (for example) to be as similar as possible. On the other hand, users are also likely to be interested in the resources consumed, quota, security implications, etc of having that database running in their namespace. 

cc @openshift/team-ux-review
