### ISSUE TITLE
oc cluster up --use-existing-config=true does not work

### ISSUE THREAD

**Issue by rbaumgar** [openshift/origin#16476]
I create a new cluster on my VirtualBox/Linux. Do some changes. Stop/start cluster and all my changes are lost even I have used "--use-existing-config=true"...

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.99.100:8443
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. oc cluster up --docker-machine=origin --host-config-dir=/var/lib/origin/ocp-config --use-existing-config=true --service-catalog --server-loglevel=1
2. oc adm policy add-cluster-role-to-user cluster-admin admin
3. oc adm policy add-cluster-role-to-group system:openshift:templateservicebroker-client system:unauthenticated system:authenticated
4. oc new-project myproj
5. oc cluster down
6. oc cluster up --docker-machine=origin --host-config-dir=/var/lib/origin/ocp-config --use-existing-config=true --service-catalog --server-loglevel=1

##### Current Result
all projects are new created. Project myproj does not exists. Admin is no longer cluster-admin...

##### Expected Result
I expect, that that the environment looks like before the cluster stop.

**Comment by spadgett** [comment]
That flag is specifically for config like `master-config.yaml`. There are other parameters like `--host-data-dir` that are for etcd data.

**Comment by csrwng** [comment]
@rbaumgar yes, please use --host-data-dir and --host-config-dir to store your config/data in a directory of your choosing. That way when you start the cluster again you can see your policy changes, etc. 

Please see https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#etcd-data

**Comment by rbaumgar** [comment]
Sorry, my fault I made a mistake! I tried to reproduce a problem from OCP with Origin, but it is not reproduce able with Origin...
