### ISSUE TITLE
Example custom builder does not adhere to recommendations in documentation

### ISSUE THREAD

**Issue by hemmop** [openshift/origin#16472]
In the [custom builder documentation](https://docs.openshift.com/container-platform/3.6/creating_images/custom.html) it is stated that

> It is recommended that you write your Custom builder image to only read the information provided by the BUILD environment variable, which conforms to an OpenShift Container Platform API version. You can then parse the required information from the build definition JSON instead of relying on the other individual environment variables provided to the builder image. 

But the [example custom builder](https://github.com/openshift/origin/blob/master/images/builder/docker/custom-docker-builder/build.sh) only uses the _not recommended_ environment variables.

Background: Getting variables from a serialized JSON structure are not trivial, so it would be tremendously valuable if the example builder gave examples on how to to that.

**Comment by bparees** [comment]
@jim-minter it's probably worth cleaning up the custom builder image example to have it actually process the build json in the BUILD env, though it should also still demonstrate using the helper env variables like SOURCE_URI that we inject.

**Comment by jim-minter** [comment]
Ech.

None of ORIGIN_VERSION, PUSH_DOCKERCFG_PATH or DOCKER_SOCKET are retrievable from BUILD.  The latter two are theoretically constants.

OUTPUT_REGISTRY and OUTPUT_IMAGE are retrievable in principle but my opinion is that the effort to do this correctly inside the builder doesn't justify the effort, especially if using bash.

FWIW, SOURCE_REPOSITORY/SOURCE_URI, SOURCE_CONTEXT_DIR and SOURCE_REF are retrievable from BUILD.  You could use jq as follows:

`SOURCE_REPOSITORY=$(jq -nr '(env.BUILD|fromjson).spec.source.git.uri')`

However, I personally wouldn't recommend doing this in a bash script where the value is already available to you, and I wouldn't want to further encourage people to write custom builders in bash, so my suggestion here is actually to remove the advice from the documentation.

Now, I think that arguably the advice should be (have been), given a service account token + the namespace, name and UID of your build, go and get it yourself from the API server -- but I don't think now is the time to address that.

**Comment by bparees** [comment]
> my suggestion here is actually to remove the advice from the documentation.

I sort of agree that encouraging people to parse json in bash scripts is not great, but i don't know how to split the difference of:

1) we need to show people how to access all the build fields they might care about, not just the ones we provide as env variables
2) we should do that using a simple example that people can easily understand/copy, as @hemmop is (reasonably, imho) asking for.

I don't think removing the doc addresses the fundamental request @hemmop has raised, which is, "show me how to parse the build json and extract fields from it"

We can just wash our hands of it by just removing the advice, but I don't know that that's the best thing we can do for our users.  I think you'd be surprised how ecstatic some users would be to have your jq example available to them, even if it's not the most ideal way to handle json parsing.

> Now, I think that arguably the advice should be (have been), given a service account token + the namespace, name and UID of your build, go and get it yourself from the API server -- but I don't think now is the time to address that.

agreed on both counts, as we've also realized that's what we should be doing in our other builder images too.
