### ISSUE TITLE
Enhance "set image-lookup" to allow references to another namespace

### ISSUE THREAD

**Issue by jwendell** [openshift/origin#16473]
Currently we can use `oc set image-lookup <image stream>` to allow this image stream to be referenced by a pod spec in its `image` field.

However this lookup only works within the current namespace. Ideally we should be able to reference image streams from other namespaces as well.

##### Version
```
oc v3.7.0-alpha.0+e5b4a1c-454
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

**Comment by smarterclayton** [comment]
The limitation is somewhat deliberate for now while we gather feedback.  I think it's a reasonable request with some discussion needed on design. 

Can you articulate use cases you want this for?

**Comment by larsks** [comment]
@smarterclayton did this issue ever come up anywhere else? I would, for example, like to be able to reference the `cli` imagestream in the `openshift` namespace from other namespaces -- the `cli` image is useful for one-off `oc` commands, and using the `cli` stream would mean not needing to worry about what image is appropriate for the current openshift environment.
