### ISSUE TITLE
Make new-app use the generated clients

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16470]
Since https://github.com/openshift/origin/pull/16451 merged yesterday, we now have direct access to all OpenShift clients in CLI, so there is no excuse left for not replacing the old `pkg/client' with the clientsets:

```
pkg/generate/app/cmd/newapp.go: "github.com/openshift/origin/pkg/client"
pkg/generate/app/cmd/template.go:       "github.com/openshift/origin/pkg/client"
pkg/generate/app/dockerimagelookup.go:  "github.com/openshift/origin/pkg/client"
pkg/generate/app/imagestreamlookup.go:  "github.com/openshift/origin/pkg/client"
pkg/generate/app/imagestreamlookup_test.go:     "github.com/openshift/origin/pkg/client"
pkg/generate/app/templatelookup.go:     "github.com/openshift/origin/pkg/client"
pkg/generate/app/templatelookup_test.go:        "github.com/openshift/origin/pkg/client"
```

All this should use the internal clientset.

**Comment by mfojtik** [comment]
CC @csrwng

**Comment by csrwng** [comment]
@openshift/devex

**Comment by coreydaley** [comment]
I've got this one

**Comment by bparees** [comment]
@mfojtik what makes this a p1?

**Comment by mfojtik** [comment]
@bparees we **really** don't want to carry legacy clients to 3.8 (maybe except tests)

**Comment by mfojtik** [comment]
@bparees also making this P2 means you will ignore it forever ;-)

**Comment by bparees** [comment]
@mfojtik no, it means we don't consider it a blocker for the sprint and I can queue up a card for dealing with it next sprint instead of yanking someone off other work to deal w/ this immediately.

**Comment by coreydaley** [comment]
@bparees I will defer to your judgement on this, let me know.

**Comment by bparees** [comment]
@coreydaley feel free to work on it once your cards for the sprint are done.

**Comment by coreydaley** [comment]
@bparees sounds good

**Comment by coreydaley** [comment]
@bparees Do we need to knock this down to a P2?

**Comment by coreydaley** [comment]
@bparees from what I can tell, this has already been done in https://github.com/openshift/origin/pull/16595 (possibly others also, but I tracked this one down).


Running `grep -r "origin\/pkg\/client" *` in  ~/go/src/github.com/openshift/origin/pkg returns zero results.

Can you please confirm and I'll close this one and move on to the next.

**Comment by bparees** [comment]
@mfojtik opened the issue, he can confirm/deny whether something still needs to be done.

**Comment by mfojtik** [comment]
@bparees this was plumbed already and I don't think there is something left to be done here.
