### ISSUE TITLE
No way to (programmatically or not) get list of resource types for "osc get"

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#1648]
I only see 2 ways, both don't make it too easy on an end user:
 1. **cli**
```
    $ openshift cli get --help
    Display one or many resources.
    
    Possible resources include builds, buildConfigs, services, pods, **etc.**
```
 1. **rtfm**
   [See docs](https://ci.openshift.redhat.com/openshift-docs-master-testing/latest/using_openshift/cli.html#cli-object-types)

I prefer either I get error message with valid types when I select invalid or something like `osc get-types`.

**Comment by smarterclayton** [comment]
Covered upstream by https://github.com/GoogleCloudPlatform/kubernetes/issues/3060

**Comment by kargakis** [comment]
There is also a [Trello card](https://trello.com/c/1jmGVmMK/522-2-list-all-resources-on-the-client-uicomp-future) for this but I guess upstream work will be sufficient.
