### ISSUE TITLE
Pre-Hook pod doesn't inherit all imagePullSecrets

### ISSUE THREAD

**Issue by deanhighmarkit** [openshift/origin#16504]
If I create a deployment pre-hook it fails to pull the image from the central repository even though it is the same container that is being deployed without the hook. 

##### Version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. Configure private repo for image-import as done here, https://docs.openshift.com/container-platform/3.5/dev_guide/managing_images.html#private-registries.
2. Configure imagestreams to import from private repository. 
3. oc set deployment-hook dc/thecomponent --pre -- echo "TEST"
4. oc rollout latest thecomponent

##### Current Result
The pre container does not contain the same imagePullSecrets as the parent.

It has a "default" secret
```
  imagePullSecrets:
  - name: default-dockercfg-k48vs
```
The primary container has 2 secrets both with necessary permissions to pull from local and remote repos.
```
  imagePullSecrets:
  - name: systemuser-dockercfg-bmgr9
  - name: central-registry
```
##### Expected Result

I expect the secrets to be inherited by the pre container as I would like to drive a schema sync at this phase of the deployment. 

##### Additional Information
N/A

**Comment by mfojtik** [comment]
I can see that we are copying the secrets from the RC template into the hook pod here: https://github.com/openshift/origin/blob/master/pkg/apps/strategy/support/lifecycle.go#L378

I also checked the 1.5 and we do the same. What version of deployer pod you run? Can you double check you run 1.5 deployer pod?

**Comment by mfojtik** [comment]
Also I just checked that if I have DC that has imagePullSecrets set to a secret I created and added to DC manually it is automatically copied into the hook pod.

**Comment by deanhighmarkit** [comment]
I have checked the deployer version, openshift/origin-deployer:v1.5.1

Is there any log I can provide to show what the pre container is doing?
