### ISSUE TITLE
Can't run unit tests on Mac

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16507]
```
~/.../openshift/origin → ./hack/test-go.sh
[INFO] [CLEANUP] Cleaning up temporary directories
# github.com/openshift/origin/vendor/github.com/vishvananda/netlink
vendor/github.com/vishvananda/netlink/filter.go:189:21: undefined: nl.TC_U32_TERMINAL
vendor/github.com/vishvananda/netlink/filter.go:190:21: undefined: nl.TC_U32_OFFSET
vendor/github.com/vishvananda/netlink/filter.go:191:21: undefined: nl.TC_U32_VAROFF
```

@csrwng or @smarterclayton can you repro this?

**Comment by csrwng** [comment]
Yes I can

**Comment by csrwng** [comment]
Of course you can always do hack/env hack/test-go.sh :-)

**Comment by mfojtik** [comment]
@csrwng which makes it 100x slower for the first run and dupe my existing .a into docker volume ;-)

**Comment by csrwng** [comment]
```
export OS_BUILD_ENV_REUSE_VOLUME=code
```
is your friend. If you add that to your .bashrc or whatever init script you use. After the first run it's incremental.

**Comment by mfojtik** [comment]
@danwinship still not working :(

~/.../openshift/origin → ./hack/test-go.sh
[INFO] [CLEANUP] Cleaning up temporary directories
can't load package: package github.com/openshift/origin/pkg/network/master/netid: build constraints exclude all Go files in /Users/mfojtik/go/src/github.com/openshift/origin/pkg/network/master/netid
can't load package: package github.com/openshift/origin/pkg/network/node/cniserver: build constraints exclude all Go files in /Users/mfojtik/go/src/github.com/openshift/origin/pkg/network/node/cniserver
can't load package: package github.com/openshift/origin/pkg/network/sdn-cni-plugin: build constraints exclude all Go files in /Users/mfojtik/go/src/github.com/openshift/origin/pkg/network/sdn-cni-plugin

**Comment by danwinship** [comment]
OK. I have no access to a Mac to test this on, but making sure there's a "doc.go" file in each directory that *doesn't* have `// +build linux` might fix that?
/unassign

**Comment by smarterclayton** [comment]
Yeah

**Comment by bparees** [comment]
@mfojtik since you have the env to test/repro this can you try the fix @danwinship suggested and create the PR?
