### ISSUE TITLE
oc new-build fails with git-ssh url

### ISSUE THREAD

**Issue by akram** [openshift/origin#16519]
[provide a description of the issue]
When running 
```
oc new-build  --strategy=docker --name=jenkins-slave-nodejs6 --code=git@github.com:akram/jenkins-slave-nodejs6.git
```
oc fails with : error: Unable to connect to the server: first path segment in URL cannot contain colon

##### Version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://api.ocp.rhlab.ovh:443
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. oc new-build  --strategy=docker --name=jenkins-slave-nodejs6 --code=git@github.com:akram/jenkins-slave-nodejs6.git
2. voilà

##### Current Result
oc fails with : error: Unable to connect to the server: first path segment in URL cannot contain colon

##### Expected Result
oc creates a new build pointing to the correct git URL

##### Additional Information
The issue #14831 was already anticpating this.

**Comment by bparees** [comment]
and per the closed issue you referenced, it should resolved in 3.7, can you try with the 3.7 alpha release?

**Comment by jim-minter** [comment]
This works for me as expected on master.

**Comment by jim-minter** [comment]
It also works for me as expected with v1.5 client + v3.6 server, and v3.6 client + v3.6 server.
I'm wondering whether the error message is actually referring to the oc<->server connection.  Please could you run oc with --loglevel=4 and send me a (redacted if you prefer) copy of your kubeconfig via e-mail?

**Comment by jim-minter** [comment]
@akram bump :)

**Comment by akram** [comment]
@jim-minter hi guys,
I didn't have time yet to test it with 3.6+

**Comment by akram** [comment]
Oh good news, my platform has been upgraded,
oc v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7

and it works
