### ISSUE TITLE
Image Pushes Don't Always Trigger New Deployments

### ISSUE THREAD

**Issue by liam-middlebrook** [openshift/origin#16523]
When a source2image build is set to automatically push an image to the image store that process happens as expected. The associated deployment configuration is set to automatically deploy when the imagestream object is updated. However this automatic new deployment is inconsistently working or not after a completed source2image build.

##### Version
```
openshift v1.5.1
kubernetes v1.5.2+43a9be4
```
##### Current Result
After completion builds will push their images to the repository. The deployment config sporadically updates to use the new image and then trigger a redeployment.

##### Expected Result
After completion builds will push their images to the repository. The deployment config will consistently update to use the newly pushed image and then trigger a redeployment.

**Comment by kargakis** [comment]
Maybe related to https://github.com/openshift/origin/issues/16728

@mfojtik @tnozicka these issues need triaging

**Comment by tnozicka** [comment]
Hard to say without more detailed info provided (oc get dc,is,build -o yaml).

Origin 1.5.1 is also not supported release anymore and it got significant rewrite since that time. Could you try it with 3.7.1 to see if the issue got fixed?
