### ISSUE TITLE
error: build error: Failed to push image: Put http:///v1/repositories/backend/nats/: malformed HTTP response 

### ISSUE THREAD

**Issue by sandeepbalouria** [openshift/origin#16524]
[provide a description of the issue]

builds can't push to integrated registry. Fails with TLS handshake errors if I dont use insecure resistry option for docker malformed https response if I use insecure resistry option.

ansible installs ofcourse (single master and one node)
I have two clusters one 3.6 and 1.5.1 both giving me the same error.
this deployment is in china
I have 1.5.0 clusters running in AWS. They work fine. 
This is urgent. Thanks 
 

##### Steps To Reproduce
1. fresh ansible install
2. run a build

##### Current Result
error: build error: Failed to push image: Put http://172.30.139.222:5000/v1/repositories/backend/nats/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
##### Expected Result
image pushed scuccessfuly 
##### Additional Information
I can give access to the servers as well 
Thanks

**Comment by bparees** [comment]
where and how did you configure the insecure registry option?

**Comment by sandeepbalouria** [comment]
file /etc/sysconfig/docker and then docker restart
I worked around this issue  for myself. 
Removed the secured registry installed by the ansible install and then deployed registry like
oc adm registry
and then created a push secret and linked to builder (service account)
and finally the build was able to push to integrated registry.

@bparees thanks for the response though.

**Comment by bparees** [comment]
cool, glad you found a solution.
