### ISSUE TITLE
Update image group policy for Docker 1.6 & v2 registry

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#1652]
Once Docker 1.6 and our v2 registry are out, we'll need to have the image resources in the policy like this:

- only the registry is allowed to access images and imagestreammappings
- any client may access imagestreams, imagestreamimages, imagestreamtags
- remove any references to imagerepositorymappings

@smarterclayton @deads2k @jwforres PTAL

**Comment by ncdc** [comment]
We need to decide if consumers other than our integrated registry are allowed to create ImageStreamMappings. @smarterclayton ?

**Comment by smarterclayton** [comment]
Why do we have to decide that?  Someone can create a policy if they want to enable it.  For now we don't need it.

**Comment by ncdc** [comment]
Ok
