### ISSUE TITLE
deprecate projectrequest list

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16530]
It is seems like we only use the projectrequests list to get better error to user when user requests a new project. It is unfortunate that we use List and override the output to be 'metav1.Status{}' as the generated clients expect the result object to be []runtime.Object.

I believe I can't switch it to Get without breaking the backward compatibility (because in Client we will have to carry the List()...).

I think we should start deprecated for List projectrequests or switch it to SelfSAR or make it Get().

**Comment by smarterclayton** [comment]
It's there to give a message.  Status is a valid response.

What kind of method are you trying to generate.

**Comment by mfojtik** [comment]
@smarterclayton giving that message via `List()` is what I don't really like :-) Also what is that endpoint really providing besides SelfSAR that we can do in the client instead?

**Comment by smarterclayton** [comment]
The message, which the UI uses to communicate to end users about where they
go.  The message is actually a feature that admins use to send the user
somewhere else to get access to the cluster.  It's expected to have a URL
in it.
