### ISSUE TITLE
How to connect grafana to prometheus 

### ISSUE THREAD

**Issue by holgerkoch** [openshift/origin#16552]
Hello,

First, thank you very much for the really good Prometheus template. It is working very fine.

We try to connect from a grafana frontend to the Prometheus server. But we got no successful connection. Maybe the oauth proxy is a problem.

My question is, did somebody successfully connect from grafana to the prometheus server? 

Best regards

Holger

##### Version
openshift 3.6

**Comment by pweil-** [comment]
cc @jcantrill @zgalor

**Comment by zgalor** [comment]
@holgerkoch haven't tried that myself.
If grafana is outside of the prometheus pod it will have to connect via the proxy, using openshift admin token in the Authorization header:
`"Authorization: Bearer $TOKEN"`

If grafana headers can't be modified, as a workaround, you can deploy grafana in the same pod, and connect via clear http without the proxy.

**Comment by mrsiano** [comment]
@holgerkoch you can use this PR https://github.com/openshift/origin/pull/17037/

see also
https://github.com/mrsiano/grafana-ocp

**Comment by holgerkoch** [comment]
@mrsiano Thank you very much for your help. Your solution is very simple to install and works like a dream.
