### ISSUE TITLE
Extended.[Feature:Builds][Slow] openshift pipeline build Blue-green pipeline Blue-green pipeline should build and complete successfully

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16553]
```
/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:576
Expected
    <bool>: false
to be true
/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:563
```

in 
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/219/testReport/junit/(root)/Extended/_Feature_Builds__Slow__openshift_pipeline_build_Blue_green_pipeline_Blue_green_pipeline_should_build_and_complete_successfully__Suite_openshift_/

As a side note, we need to revisit what we're dumping on jenkins failures, I think it's too much data that's no longer relevant to the failures we're seeing these days (gc status, registry usage, etc).

**Comment by gabemontero** [comment]
Taking a second pass at this post devcut (i.e. not as distracted) I see the build in fact was started.  I believe / it looks like jenkins was restarted, and with all that churn, the job timed out.

Details (warning - lengthy):
1) So according to the build obj dump, it is in running state:  

```
Status:		�[1mRunning�[0m
Started:	Mon, 25 Sep 2017 08:27:53 EDT
Duration:	running for 1h40m47s

Build Config:	bluegreen-pipeline
Build Pod:	bluegreen-pipeline-1-build
```

2) And I found the job log in the mass of debug data (which @bparees has already made some corrections on, though as previously referenced some additional changes related to his issue makes sense and I'll do that soon).  Among other things, I wonder if we can use `--previous` with `oc logs` to capture prior jenkins instance logs in the case of a restart.

The job log shows It had started `nodejs-mongodb-example-1` and was still monitoring when the job log contents just end.  The last few lines of output from the job log:

```
OpenShiftBuilder bld state:  Running

OpenShiftBuilder found pod jenkins-1-pw511

OpenShiftBuilder found pod mongodb-1-deploy

OpenShiftBuilder found pod mongodb-1-phwh6

OpenShiftBuilder found pod nodejs-mongodb-example-1-build

OpenShiftBuilder going with build pod {"metadata" : {"name" : "nodejs-mongodb-example-1-build", "namespace" : "extended-test-jenkins-pipeline-r2npt-kwld2", "selfLink" : "/api/v1/namespaces/extended-test-jenkins-pipeline-r2npt-kwld2/pods/nodejs-mongodb-example-1-build", "uid" : "f7625aad-a1ec-11e7-bf94-0ecf81703c7e", "resourceVersion" : "5344", "creationTimestamp" : "2017-09-25T12:27:59Z", "labels" : {"openshift.io/build.name" 
```


3) Then look at these series of events.  The `nodejs-mongodb-example-1` build is started, but then the jenkins restart occurs, and then `nodejs-mongodb-example-1` completes:

```
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:10 -0400 EDT - event for nodejs-mongodb-example-1: {build-controller } BuildStarted: Build extended-test-jenkins-pipeline-r2npt-kwld2/nodejs-mongodb-example-1 is now running
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:14 -0400 EDT - event for nodejs-mongodb-example-1-build: {kubelet ip-172-18-11-73.ec2.internal} Pulled: Container image "openshift/origin-sti-builder:11e88a4" already present on machine
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:15 -0400 EDT - event for nodejs-mongodb-example-1-build: {kubelet ip-172-18-11-73.ec2.internal} Created: Created container
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:16 -0400 EDT - event for nodejs-mongodb-example-1-build: {kubelet ip-172-18-11-73.ec2.internal} Started: Started container
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:18 -0400 EDT - event for nodejs-mongodb-example-1-build: {kubelet ip-172-18-11-73.ec2.internal} Pulled: Container image "openshift/origin-sti-builder:11e88a4" already present on machine
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:21 -0400 EDT - event for nodejs-mongodb-example-1-build: {kubelet ip-172-18-11-73.ec2.internal} Created: Created container
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:24 -0400 EDT - event for nodejs-mongodb-example-1-build: {kubelet ip-172-18-11-73.ec2.internal} Started: Started container
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:28 -0400 EDT - event for jenkins: {deployer-controller } Failed: Deployer pod "jenkins-1-deploy" has gone missing
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:28 -0400 EDT - event for jenkins-1: {replication-controller } SuccessfulDelete: Deleted pod: jenkins-1-pw511
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:28 -0400 EDT - event for jenkins-1: {replication-controller } SuccessfulCreate: Created pod: jenkins-1-b69zd
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:28 -0400 EDT - event for jenkins-1-b69zd: {default-scheduler } Scheduled: Successfully assigned jenkins-1-b69zd to ip-172-18-11-73.ec2.internal
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:29 -0400 EDT - event for jenkins-1-b69zd: {kubelet ip-172-18-11-73.ec2.internal} SuccessfulMountVolume: MountVolume.SetUp succeeded for volume "jenkins-token-r1c15" 
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:29 -0400 EDT - event for jenkins-1-b69zd: {kubelet ip-172-18-11-73.ec2.internal} SuccessfulMountVolume: MountVolume.SetUp succeeded for volume "jenkins-data" 
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:30 -0400 EDT - event for jenkins-1-pw511: {kubelet ip-172-18-11-73.ec2.internal} Killing: Killing container with id docker://jenkins:Need to kill Pod
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:30 -0400 EDT - event for mongodb-1-phwh6: {kubelet ip-172-18-11-73.ec2.internal} Pulled: Successfully pulled image "centos/mongodb-32-centos7@sha256:b882f1484bc0bd3b3abb8c3240c8880ec0c558d4f2aefd3214cf85b977247954"
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:33 -0400 EDT - event for mongodb-1-phwh6: {kubelet ip-172-18-11-73.ec2.internal} Created: Created container
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:35 -0400 EDT - event for mongodb-1-phwh6: {kubelet ip-172-18-11-73.ec2.internal} Started: Started container
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:36 -0400 EDT - event for jenkins-1-b69zd: {kubelet ip-172-18-11-73.ec2.internal} Pulled: Container image "openshift/jenkins-2-centos7@sha256:b8cbb037dc5c1d1f0d47327b7b0f7f4949c7e264402bb8fa7b1bdc8fe71feecc" already present on machine
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:38 -0400 EDT - event for jenkins-1-b69zd: {kubelet ip-172-18-11-73.ec2.internal} Created: Created container
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:41 -0400 EDT - event for jenkins-1-b69zd: {kubelet ip-172-18-11-73.ec2.internal} Started: Started container
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:29:02 -0400 EDT - event for jenkins-1-b69zd: {kubelet ip-172-18-11-73.ec2.internal} Unhealthy: Readiness probe failed: Get http://10.128.0.41:8080/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:29:09 -0400 EDT - event for jenkins-1-b69zd: {kubelet ip-172-18-11-73.ec2.internal} Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 503
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:31:37 -0400 EDT - event for nodejs-mongodb-example-1: {build-controller } BuildCompleted: Build extended-test-jenkins-pipeline-r2npt-kwld2/nodejs-mongodb-example-1 completed successfully
```

4) looking at the node logs, I see the probes getting a few 503's before deciding to restart jenkins

5) so the pod logs we have will be the latest - *AFTER* the restart.  That is why I don't see the explicit starting of the job there (but we can still pull the job logs).

What I can't infer yet is:

1) did `Failed: Deployer pod "jenkins-1-deploy" has gone missing` result in the jenkins pod restart, or did the 503s/probe issues result in the restart, and that gone missing message is a result of that or a red herring

2) if some memory constraint caused the restart, we don't seem to have any of our memory debug that is time stamped well before the restart ... the first ones are around the restart time ...they look OK

3) I was also expecting some indication that the job was restarted; but in looking at the sync plugin in this space, logs are lacking, and it is not obvious if it would happen.

So, what I'm going to do next:

a) look into augmenting test debug with `oc log --previous`
b) do some experiments with the bluegreen tests and various restarts (`oc scale`, kill containers, etc.) manually and see what transpires

**Comment by gabemontero** [comment]
@bparees - given the current findings I have, if this is not happening with great frequency, lowering the priority might be appropriate.

**Comment by bparees** [comment]
haven't seen it again, lowering sev is fine.

**Comment by bparees** [comment]
It looks like the entire pod was deleted (hence the restart), which is interesting.  That would imply it's not something within the container (ie OOM) causing the restart.

```

Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:28 -0400 EDT - event for jenkins-1: {replication-controller } SuccessfulDelete: Deleted pod: jenkins-1-pw511
Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:28 -0400 EDT - event for jenkins-1: {replication-controller } SuccessfulCreate: Created pod: jenkins-1-b69zd
```

We really need better auditing on *why* the pod was deleted.

It's possible it was related to this:
 Failed: Deployer pod "jenkins-1-deploy" has gone missing

perhaps a second deployment got triggered as a result of first one vanishing, but of course that still leaves the question of why it vanished.

Anyway logs --previous won't help in this case since it's a different pod, not a restart of a pod.

**Comment by bparees** [comment]
Was there anything in the logs indicating that there was a jenkins-2-deploy?  or anything in the jenkins-1-deploy logs?

**Comment by gabemontero** [comment]
On Thu, Sep 28, 2017 at 1:47 PM Ben Parees <notifications@github.com> wrote:

> Was there anything in the logs indicating that there was a
> jenkins-2-deploy? or anything in the jenkins-1-deploy logs?
>
no sign of jenkins-2-*

**Comment by gabemontero** [comment]
On Thu, Sep 28, 2017 at 1:46 PM Ben Parees <notifications@github.com> wrote:

> It looks like the entire pod was deleted (hence the restart), which is
> interesting. That would imply it's not something within the container (ie
> OOM) causing the restart.
>
>
> Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:28 -0400 EDT - event for jenkins-1: {replication-controller } SuccessfulDelete: Deleted pod: jenkins-1-pw511
> Sep 25 10:08:49.920: INFO: At 2017-09-25 08:28:28 -0400 EDT - event for jenkins-1: {replication-controller } SuccessfulCreate: Created pod: jenkins-1-b69zd
>
> We really need better auditing on *why* the pod was deleted.
>
agreed hence my question;  is the audting something we can do or is it
lower level?

**Comment by bparees** [comment]
> agreed hence my question; is the audting something we can do or is it lower level?

nothing i'm aware of, it was a generic platform complaint :)

**Comment by bparees** [comment]
> did the 503s/probe issues result in the restart

readiness probe failures will not cause a restart (only liveness probe failures).  and if it did result in a restart via that mechanism(liveness failure), it would not have created a new pod identifier for the jenkins pod.

**Comment by gabemontero** [comment]
On Thu, Sep 28, 2017 at 2:43 PM Ben Parees <notifications@github.com> wrote:

> did the 503s/probe issues result in the restart
>
> readiness probe failures will not cause a restart (only liveness probe
> failures). and if it did result in a restart via that mechanism(liveness
> failure), it would not have created a new pod identifier for the jenkins
> pod.
>
ah thanks for that - will try to remember in the future:-)

So yeah it is that mystery delete message then

Still plan on doing so me restart experiments with the bluegreen app and
compare with this test failure, see what if nat insight that provides

**Comment by gabemontero** [comment]
OK, some comparison points running bluegreen manually:

1) if I `docker kill <jenkins container id>` in the middle of a build, jenkins resuscitates the job on restart, and it at least explicitly fails it with the `Resume after a restart not supported for non-blocking synchronous steps` message;  there are analogous logs around this in the jenkins system log as well

nothing like that happened in the test failure

2) doing a `oc scale dc jenkins --replicas=0` and then an `oc scale dc jenkins --replicas=1` looks similar to the failure in that the pod / rc / dc version does not change ... we went from pod `jenkins-1-cd6w8` to `jenkins-1-jhlkv`.  Same results in the job log and jenkins system log as 1)

NET: nothing insightful, other than perhaps reconfirming that the symptoms, etc. exhibited in this failed test run are very odd.

**Comment by bparees** [comment]
this looks like another instance of the jenkins pod going away/being replaced:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16625/test_pull_request_origin_extended_builds/397/

we seem to think the jenkins pod is jenkins-1-pnj9r so we see lots of errors trying to access it:
```
Error from server (NotFound): pods "jenkins-1-pnj9r" not found
```

but when we dump state at the end we find this jenkins pod:
```
Sep 30 03:48:34.011: INFO: Describing pod "jenkins-1-dv7gb"
Name:		jenkins-1-dv7gb
Namespace:	extended-test-jenkins-pipeline-zg5zw-vv9hn
```

**Comment by bparees** [comment]
@gabemontero i think you added some better debug for this and i haven't seen it in a while,so closing.
