### ISSUE TITLE
Provide reasonable way to mock processing a template

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16555]
Spawned from https://github.com/openshift/origin/pull/16550 (commit: https://github.com/openshift/origin/pull/16550/commits/0a56304b66168730388c804ddf18bc6e6a1bea5e)

Currently the new-app calls the Process() template directly which hits the real API client. This will fail in unit tests and we need some reasonable way to mock this call. (by passing the custom `TemplateProcessorInterface`?).

**Comment by bparees** [comment]
Mocking template transformation would seem pointless since the only thing this test is doing is transforming the template.  Just delete the tests if there's no way to run the real code anymore.

**Comment by bparees** [comment]
we also already testing this functionality via the command line testing. let's not go nuts building a bunch of mocks.
