### ISSUE TITLE
Kubelet loops endlessly looking at run once pods

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1656]
Created a number of run once pods that ran to completion, then restarted the all-in-one.  The Kubelet appears to be looping (seeing the pods, that are complete) without ignoring them forever like it should.

```
E0408 19:53:25.715639   27154 event.go:129] Unable to write event '&api.Event{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"deploy-database-18pgcs.13d321db1e02a875", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"19723", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"deploy-database-18pgcs", UID:"13407227-de0f-11e4-9cef-080027c5bfa9", APIVersion:"v1beta1", ResourceVersion:"371", FieldPath:"spec.containers{deployment}"}, Reason:"failed", Message:"Failed to pull image \"openshift/origin-deployer:v0.4.3\": Tag v0.4.3 not found in repository openshift/origin-deployer", Source:api.EventSource{Component:"kubelet", Host:"openshiftdev.local"}, FirstTimestamp:util.Time{Time:time.Time{sec:63564119531, nsec:0x0, loc:(*time.Location)(0x32de2a0)}}, LastTimestamp:util.Time{Time:time.Time{sec:63564119605, nsec:0x2824e3e9, loc:(*time.Location)(0x32de2a0)}}, Count:25}': 'events "deploy-database-18pgcs.13d321db1e02a875" cannot be updated: 101: Compare failed ([19723 != 19726]) [19726]' (will not retry!)
I0408 19:53:27.941076   27154 kubelet.go:994] Already ran container "sti-build" of pod "ruby-sample-build-5_default", do nothing
I0408 19:53:27.963573   27154 kubelet.go:994] Already ran container "deployment" of pod "deploy-docker-registry-2gk2mm_default", do nothing
I0408 19:53:27.972043   27154 kubelet.go:994] Already ran container "deployment" of pod "deploy-docker-registry-2fcm33_default", do nothing
I0408 19:53:27.976866   27154 kubelet.go:994] Already ran container "sti-build" of pod "ruby-sample-build-6_default", do nothing
```

Possible there's a bug in Kubelet log where it doesn't properly ignore run-once pods.

**Comment by smarterclayton** [comment]
That output is looped over and over

**Comment by brenton** [comment]
@smarterclayton, do we think this will make 0.5.0?  While annoying, I don't think it's going to block beta3.

**Comment by smarterclayton** [comment]
It does not

**Comment by derekwaynecarr** [comment]
Attempting to reproduce this now... the kubelet has changed so much, I cannot find that string in kubelet.go ;-)

**Comment by derekwaynecarr** [comment]
So just looking at this code, this predates changing to the SyncPods loop that ran every 10s in Kubelet.  

The code does filter the list of pods it iterates against here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1322

Filters the terminated pods here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1591

So I guess I will just run a bunch of containers to their death and grep logs for anything weird, but this code has definitely improved in the interim from the initial report.

**Comment by derekwaynecarr** [comment]
@smarterclayton - you can close this issue.

See the analysis I provided on the upstream issue (that I also now closed) here:
https://github.com/GoogleCloudPlatform/kubernetes/issues/6641

Net:
Kubelet filters out terminated pods in its synch loop
As a result, Kubelet does not constantly update the pod status once its terminated
As a result, the resource version of a pod is stable once its terminated
As a result, the watch is not spammed with updates for dead pods
