### ISSUE TITLE
No package matching 'atomic-openshift' found available, installed or updated

### ISSUE THREAD

**Issue by delubi** [openshift/origin#16562]
I'm building Openshift origin on VMs running on Azure. 3 masters with ectd. 1 load balancer. 2 nodes.

VM is CentOS7.3. Installer is RPM based. Origin is the latest clone from github. 

When I run the below:

ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml

It reported error:

PLAY RECAP *********************************************************************
OpenShiftLB                : ok=19   changed=2    unreachable=0    failed=0
OpenShiftMaster1           : ok=26   changed=3    unreachable=0    failed=1
OpenShiftMaster2           : ok=21   changed=2    unreachable=0    failed=0
OpenShiftMaster3           : ok=21   changed=2    unreachable=0    failed=0
OpenShiftNode1             : ok=20   changed=2    unreachable=0    failed=0
OpenShiftNode2             : ok=20   changed=2    unreachable=0    failed=0
infra-OpenShiftNode1       : ok=0    changed=0    unreachable=1    failed=0
infra-OpenShiftNode2       : ok=0    changed=0    unreachable=1    failed=0
localhost                  : ok=12   changed=0    unreachable=0    failed=0

Failure summary:

  1. Hosts:    OpenShiftMaster1
     Play:     Determine openshift_version to configure on first master
     Task:     Install the base package for versioning
     Message:  No package matching 'atomic-openshift' found available, installed or updated

Any idea what the message "No package matching 'atomic-openshift' found available, installed or updated" mean and how to resolve it?

Thanks,
Forrest

**Comment by delubi** [comment]
Just found out that I had the deployment type set to openshift-enterprise. Once changed to origin, the error is gone.

**Comment by karunakarreddych** [comment]
Hi Delubi,

I am facing same issue, can you please let me know in which you changed openshift-enterprise to origin.

Thanks,
Karunakar

**Comment by delubi** [comment]
My azure instances are now gone so I don't have a way to check.

I recall the change was made in the ansible playbook config file. Most likely it's in 

openshift-ansible/playbooks/byo/config.yml

Do a search for "openshift-enterprise". It's the value of installation type. Changing it to "origin" was what I did.

Forrest

**Comment by karunakarreddych** [comment]
Thank you very much
