### ISSUE TITLE
Crash loop when PostgreSQL database name contailns a hyphen

### ISSUE THREAD

**Issue by GSI** [openshift/origin#16577]
(possibly related to #7824)

##### Version
'''
oc v3.6.0+c4dd4cf                                                                                                                      
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.starter-ca-central-1.openshift.com:443
openshift v3.6.173.0.7
kubernetes v1.6.1+5115d708d7
'''

##### Steps To Reproduce
1. On a pristine OpenShift Online account: From *Project > Catalog > Data Stores* add **PostgreSQL (Persistent)**
2. Leaving all other settings to default, set **PostgreSQL Database Name** to **sample-db** (default would be **sampledb**)

##### Current Result
Crash loop (Deployment fails)

##### Expected Result
Deployment should succeed

**Comment by hhorak** [comment]
I see the same result when trying it myself. However, the container log itself shows pretty correct message, that the values given are not expected, for example `sample-db` does not match regexp `^[a-zA-Z_][a-zA-Z0-9_]*$` (dash is not allowed in database name). The question now is whether the format of the input can be forced in the OpenShift UI already, so users get early feedback that the value doesn't match expected pattern.

**Comment by bparees** [comment]
it's not possible to do that in the UI today, there's no way to provide validation rules from the image or template.

So this is can't fix.

**Comment by simonvalter** [comment]
this also happens when the project name contains a -
