### ISSUE TITLE
Need tests for PKCE with oc

### ISSUE THREAD

**Issue by enj** [openshift/origin#16579]
#16446 needs the following tests:

1. Unit tests that exercise the code path, WIP: https://github.com/openshift/origin/compare/master...enj:enj/t/pkce_auth_proxy/16579
2. Update `test/integration/scopes_test.go` to perform both a code and token flow with its `Attempt a login using a redirecting auth proxy`
3. Fix code/function docs related to OAuth error handling in `pkg/cmd/util/tokencmd/request_token.go`

**Comment by mrogers950** [comment]
@enj will do.

**Comment by ericavonb** [comment]
Created internal task in JIRA to track.
