### ISSUE TITLE
Define delete behavior for DeploymentConfigs

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#1657]
Deleting a DeploymentConfig which has associated deployments can result in undefined and problematic behavior, especially if the DeploymentConfig is subsequently recreated. See #1649 for an example.

Deleting a DeploymentConfig should have defined behavior, and deleting/recreating a DeploymentConfig should be a safe operation. This issue will track the design for DeploymentConfig delete handling.

**Comment by smarterclayton** [comment]
Also, deployment process pods should hang around for a few minutes if they succeed, or a few more minutes if they fail (and builds should be consistent) @bparees as per discussion

**Comment by jwforres** [comment]
Should consider why as a user I would think about deleting a deployment config

1) I dont want to trigger any more deployments ever, but I want to keep my existing stuff running for a bit
2) I'm completely done with the things the deployment config runs, I dont want it anymore, I want to clean it up completely

You could argue that maybe (1) just needs a really easy "remove triggers" or "update triggers" command (right now you can do that relatively easily using the new osc edit command).  

In which case (2) could be the default behavior for deleting a deployment config -> delete all the deployments.  We can make this very clear from the web console that it is what will happen.  The CLI is more of a concern since osc delete today makes it very easy to cause destructive changes. `osc delete dc prod` -> oh crap I accidentally wiped out prod

**Comment by ironcladlou** [comment]
@jwforres 

>1) I dont want to trigger any more deployments ever, but I want to keep my existing stuff running for a bit
>You could argue that maybe (1) just needs a really easy "remove triggers" or "update triggers" command (right now you can do that relatively easily using the new osc edit command).

I think if you want triggering to stop you should edit/remove triggers.

>2) I'm completely done with the things the deployment config runs, I dont want it anymore, I want to clean it up completely
>In which case (2) could be the default behavior for deleting a deployment config -> delete all the deployments. We can make this very clear from the web console that it is what will happen. The CLI is more of a concern since osc delete today makes it very easy to cause destructive changes. osc delete dc prod -> oh crap I accidentally wiped out prod

I also think that a DC delete should wipe out all associated deployments, and agree that the delete would need to come with some sort of warnings.

Can CLI delete handlers be outfitted with interactive prompts on a per-resource basis so we could get confirmation from users?

Would also be worth noting that an HTTP DELETE on the DC would also nuke everything without any chance for confirmation...

**Comment by smarterclayton** [comment]
----- Original Message -----
> @jwforres
> 
> >1) I dont want to trigger any more deployments ever, but I want to keep my
> >existing stuff running for a bit
> >You could argue that maybe (1) just needs a really easy "remove triggers" or
> >"update triggers" command (right now you can do that relatively easily
> >using the new osc edit command).
> 
> I think if you want triggering to stop you should edit/remove triggers.
> 
> >2) I'm completely done with the things the deployment config runs, I dont
> >want it anymore, I want to clean it up completely
> >In which case (2) could be the default behavior for deleting a deployment
> >config -> delete all the deployments. We can make this very clear from the
> >web console that it is what will happen. The CLI is more of a concern since
> >osc delete today makes it very easy to cause destructive changes. osc
> >delete dc prod -> oh crap I accidentally wiped out prod
> 
> I also think that a DC delete should wipe out all associated deployments, and
> agree that the delete would need to come with some sort of warnings.
> 
> Can CLI delete handlers be outfitted with interactive prompts on a
> per-resource basis so we could get confirmation from users?

The "stop" command is really intended to solve this.  Delete does not blow away your cluster accidentally (well, except for namespace).

**Comment by smarterclayton** [comment]
----- Original Message -----
> Should consider why as a user I would think about deleting a deployment
> config
> 
> 1) I dont want to trigger any more deployments ever, but I want to keep my
> existing stuff running for a bit
> 2) I'm completely done with the things the deployment config runs, I dont
> want it anymore, I want to clean it up completely
> 
> You could argue that maybe (1) just needs a really easy "remove triggers" or
> "update triggers" command (right now you can do that relatively easily using
> the new osc edit command).

We've talked about "pause triggers" or "disable triggers" in other issues.

**Comment by liggitt** [comment]
I think upstream made `--cascade=true` the default, which seems dangerous to me

**Comment by smarterclayton** [comment]
Well.... You say you don't want the deployment anymore....

**Comment by liggitt** [comment]
It's not clear how strong the ownership connection is between a deployment config and the resulting replication controllers. The UI tolerates a deployment annotated with a deployment config that no longer exists… seems like the cascade is handy, but as a default it makes me nervous

**Comment by smarterclayton** [comment]
We probably will just want to make undelere not bad
