### ISSUE TITLE
[Flannel] Some pods do not obtain IP addresses

### ISSUE THREAD

**Issue by bogdando** [openshift/origin#16578]
Some pods do not obtain IP addresses.
Docker containers can be started manually with `docker run` w/o issues.

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master-0.openshift.cluster.lc:8443
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Deploy openshift origin from `openshift-ansible-3.7.0-0.127.0-69-gc16d16d` on top of openstack Centos 7.3 VMs (RDO cloud), by [this provider](https://github.com/openshift/openshift-ansible-contrib/pull/708), using [these inventory vars](https://github.com/bogdando/ocp-inventory/releases/tag/v0.1), following [this guide](https://github.com/openshift/openshift-ansible-contrib/pull/708/files?short_path=9141c3c#diff-9141c3c37ff1e871d38171e178e46e72)
2. Create a cake php app:
```
oc new-project foo
oc new-app --template=cakephp-mysql-example
```

##### Current Result
mysql and console registry pods do obtain IP addresses, while cake php pod doesn't

##### Expected Result
all pods get IP addresses from flannel subnets

##### Additional Information
[oc adm diagnostics](https://pastebin.com/S17LRsYM)
[sudo oc adm diagnostics](https://pastebin.com/znF8fm2h)
[oc get all -o json -n foo](https://pastebin.com/8S6y51pd)

Looks also related https://github.com/kubernetes/kubernetes/issues/52527#issuecomment-332505944

**Comment by bogdando** [comment]
@e-minguez @tomassedovic ^^

**Comment by e-minguez** [comment]
Do you mind to get flannel logs as well as the events in that particular project? (oc get events -w)
Have you tried deploying another set of pods (like jenkins persistent)?

**Comment by bogdando** [comment]
@e-minguez will do, thanks!

Note, for this time, I can see the describe command now shows an IP assigned for the pod, but at the docker side nothing has changes - there is no IP in the inspect outputs.

**Comment by bogdando** [comment]
@e-minguez we're used to make e2e for that openstack provider with a cake php. I'm not sure I know much of other things, like jenkins persistent ! :)

**Comment by bogdando** [comment]
@e-minguez [oc-get-events](https://pastebin.com/LrJqTgpM) , [flannel logs](https://pastebin.com/VbA0xd3Q) (there is nothing can be found in journalctl for flannel), [/run configs](https://pastebin.com/RUHB0n5w)

**Comment by bogdando** [comment]
updated the ticket with [sudo oc adm diagnostics](https://pastebin.com/znF8fm2h) so it can access the cluster master/node configs. note: those 3 errors look irrelevant to me

**Comment by bogdando** [comment]
closing this as the issue was in the missing iptables rules to access DNS from containers

**Comment by bogdando** [comment]
kudos @e-minguez for help!
