### ISSUE TITLE
questionable image tag follow behavior + images.sh race condition

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16590]
@soltysh @smarterclayton @miminar @dmage @legionus Is the below acceptable behavior for reference imagestream tags?  I did the following sequence of events:

oc create imagestreamtag tag:1 --from=wildfly:latest
oc patch istag/wildfly:latest -p='{\"tag\":{\"from\":{\"kind\":\"DockerImage\",\"name\":\"mysql:latest\"}}}'
oc create imagestreamtag tag:2 --from=wildfly:latest

```
apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: 2017-09-28T03:23:25Z
  generation: 2
  name: tag
  namespace: openshift
  resourceVersion: "1552"
  selfLink: /oapi/v1/namespaces/openshift/imagestreams/tag
  uid: 63551616-a3fc-11e7-9d5e-507b9d27b5d9
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamTag
      name: wildfly:latest
    generation: 1
    importPolicy: {}
    name: "1"
    referencePolicy:
      type: Source
  - annotations: null
    from:
      kind: ImageStreamTag
      name: wildfly:latest
    generation: 2
    importPolicy: {}
    name: "2"
    referencePolicy:
      type: Source
status:
  dockerImageRepository: 172.30.8.127:5000/openshift/tag
  tags:
  - items:
    - created: 2017-09-28T03:22:30Z
      dockerImageReference: openshift/wildfly-101-centos7@sha256:501bc1a8919899024d1a92a147b4d58ad87d0944c720b939cdfe5eff7773e977
      generation: 1
      image: sha256:501bc1a8919899024d1a92a147b4d58ad87d0944c720b939cdfe5eff7773e977
    tag: "1"
  - items:
    - created: 2017-09-28T03:23:26Z
      dockerImageReference: mysql@sha256:f6900d8ee65a802f6461a04c5e9f44e2fabbf6f09b2827260c643988bcdba16e
      generation: 2
      image: sha256:f6900d8ee65a802f6461a04c5e9f44e2fabbf6f09b2827260c643988bcdba16e
    tag: "2"
```

The result is that although tag:1 and tag:2 both follow "wildfly:latest", they have different values (as seen above)

That might be expected because they simply took on the value at the time they were created/imported, but one also might expect that when the tag they were following changed, they should have changed.

Bug or not a bug?  either way, this is causing our race condition in images.sh where we do the following:

```
os::cmd::expect_success "oc patch istag/wildfly:latest -p='{\"tag\":{\"from\":{\"kind\":\"DockerImage\",\"name\":\"mysql:latest\"}}}'"
os::cmd::expect_success 'oc create imagestreamtag tag:1 --from=wildfly:latest'
os::cmd::expect_success_and_text 'oc get istag/tag:1 -o jsonpath={.image.dockerImageReference}' 'wildfly.*@sha256:'
```

sometimes tag:1 has a value pointing to a wildfly image and other times it points to a mysql image, depending on how quickly tag:1 was created after the patch operation was performed, so sometimes the test fails because tag:1 points to mysql.

@gabemontero fyi since you've been hitting this.

**Comment by smarterclayton** [comment]
I would expect tag:2 to always point to wildfly:latest for reference image
streams.  create imagestreamtag with a --from to a reference image stream
tag (reference: true) should always inherit the spec tag of the --from,
rather than the status tag.  If it's not a reference tag, I would always
expect it to get wildfly:latest, although we may be unable to provide that
behavior without some client side smarts (we don't currently fail
"resolution" if an import is in progress).

**Comment by smarterclayton** [comment]
Resolution right now is geared much more strongly to the trigger scenario
(no matter what, a deployment config will eventually end up pointing to the
latest status tag).  If an import is in progress blocking until the import
is resolved makes some sense, except that could be an infinite wait in some
cases.

**Comment by bparees** [comment]
> I would expect tag:2 to always point to wildfly:latest for reference image
streams.  create imagestreamtag with a --from to a reference image stream
tag (reference: true) should always inherit the spec tag of the --from,
rather than the status tag.  If it's not a reference tag, I would always
expect it to get wildfly:latest

well that's what it's doing, roughly.  tag:2 is ending pointing to whatever wildfly:latest points to at that time (in this case, wildfly:latest points to a mysql image, it's not a reference tag after the patch).  my concern is more with tag:1..   tag:1 is referencing wildfly:latest.  wildfly:latest now points to mysql, but tag:1 is still pointing to wildfly, not mysql.  Presumably if i re-imported tag:1, it would update to point to mysql(I did not test this).  The question I have is, should I have to explicitly do that import?  

(I'm thinking about it like symlinks.  if a->b and b->c, when i change b->d, then a->d immediately.  a doesn't point to ->c until you "refresh" a and then it ->d.  It seems wrong to see two identical spec tags with different status values).

**Comment by soltysh** [comment]
> The question I have is, should I have to explicitly do that import?

There are two flags for that, one is `reference` and another is `alias`. What you're looking for is `alias`, but that can and will work only within a single Image Stream (we've struggled with the idea of having cross-IS access etc.) For reference, it's always at the moment when the import happens. So I don't see anything wrong here.

**Comment by bparees** [comment]
ok I think i convinced myself this morning that this is no different than:

1) create an IST from dockerimage:foo while :foo tag points to X
2) create a second IST in the same IS, also from dockerimage:foo, when docker repository :foo points to Y

until you explicitly re-import the first IST, the two ISTs will be out of sync despite having the same source.  I guess that's just "working by design".

**Comment by smarterclayton** [comment]
And if you have scheduled import set it will eventually converge

On Sep 28, 2017, at 8:53 AM, Ben Parees <notifications@github.com> wrote:

ok I think i convinced myself this morning that this is no different than:

   1. create an IST from dockerimage:foo while :foo tag points to X
   2. create a second IST in the same IS, also from dockerimage:foo, when
   docker repository :foo points to Y

until you explicitly re-import the first IST, the two ISTs will be out of
sync despite having the same source. I guess that's just "working by
design".

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/16590#issuecomment-332826847>,
or mute the thread
