### ISSUE TITLE
Make it easy to run builds of PRs/forks on Openshift

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#16593]
Today I need to change stuff inside the BC in order to run one-off builds of a PR or a branch in my fork. I end up bypassing building on Openshift by doing it by myself locally all the time. This gets much more painful when there are chained builds in play. For starters, maybe a flag in start-build to point to the new branch or PR will suffice. I am not sure that it's enough in a chained build scenario.

@bparees @smarterclayton 
/sig developer-experience

**Comment by bparees** [comment]
oc start-build --commit ?
(commit can actually be any valid git ref i believe)

**Comment by smarterclayton** [comment]
The UI also needs a way to do this on start build

**Comment by bparees** [comment]
@kargakis can you confirm --commit does what you need for the CLI?  We can pursue allowing the web console "start-build" button to accept args/options separately if so.

**Comment by kargakis** [comment]
--commit is not doing what I want. 

For example, our test-infra fork is at https://github.com/kubernetes/test-infra/commit/bdf1683f63e8612cbfa432d0ec10cb399b4aec72 but if I want to test https://github.com/kubernetes/test-infra/commit/f8b49628c959d664e80aa60dd61881588f730309, it won't work.
```
[mkargaki@dhcp129-211 test-infra]$ oc get bc prow -o yaml
apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: 2017-09-05T15:51:23Z
  name: prow
  namespace: ci
  resourceVersion: "4233301"
  selfLink: /oapi/v1/namespaces/ci/buildconfigs/prow
  uid: 11a3c209-9252-11e7-bd36-42010a800002
spec:
  failedBuildsHistoryLimit: 2
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: prow:binaries
      namespace: ci
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM openshift/origin-release:golang-1.8

      COPY . /go/src/k8s.io/test-infra
      RUN cd /go/src/k8s.io/test-infra && \
          godep restore && \
          cd prow && \
          mkdir -p /static && \
          cp -r cmd/deck/static-rh/* /static && \
          CGO_ENABLED=0 go install -a -installsuffix cgo -ldflags '-w' ./cmd/... && \
          rm -rf /go/src /go/pkg
    git:
      uri: https://github.com/openshift/test-infra.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: openshift/origin-release:golang-1.8
      imageOptimizationPolicy: SkipLayers
    type: Docker
  successfulBuildsHistoryLimit: 1
  triggers:
  - type: ConfigChange
status:
  lastVersion: 8
[mkargaki@dhcp129-211 test-infra]$ oc start-build bc/prow --commit=f8b49628c95
build "prow-9" started
[mkargaki@dhcp129-211 test-infra]$ oc logs -f bc/prow
Cloning "https://github.com/openshift/test-infra.git" ...
error: fatal: Couldn't find remote ref f8b49628c95
Unexpected end of command stream
```

**Comment by bparees** [comment]
why would that not work?

**Comment by bparees** [comment]
if it's part of a PR you need to use the github PR reference syntax.

**Comment by bparees** [comment]
e.g. https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by jwforres** [comment]
For the console I've added this to our card tracking "Start Build" with options https://trello.com/c/nTtovDHM

**Comment by bparees** [comment]
@kargakis did you try using the github PR ref syntax?

**Comment by kargakis** [comment]
Yeah, the github PR syntax works. Parameterizing the git uri and ref works for me.
