### ISSUE TITLE
Image Push fails with 172.30.x.x:5000 port

### ISSUE THREAD

**Issue by hmadabhu** [openshift/origin#16601]
Trying to deploy any of the openshift example deployment, fails on docker push as
Pushing image 172.30.115.188:5000/myphpprj/rails-postgresql-example:latest ...
Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: Error: Status 504 trying to push repository myphpprj/rails

##### Version
 oc version
oc v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ocpmaster1.dbpoc.uk:8443
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
[root@ocpmaster1 ~]# openshift version
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
etcd 3.2.1

##### Steps To Reproduce
1. Login to UI console, create a project, Add to Project, rails-postgresql-example 
2. Watch the build fail with the above message

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by pweil-** [comment]
@hmadabhu 504 is a gateway timeout.  I'm assigning this to the network team but before they can debug can you please confirm that your registry is up and running and you can push to it from within the cluster?

**Comment by hmadabhu** [comment]
Yes the registry us up, I was able to do a 
docker login -u <uname> -p <token> docker-registry.subdomain
and push images.
but not by IP:PORT

**Comment by bparees** [comment]
/close

Ben Parees | OpenShift
