### ISSUE TITLE
Unable to access openshift origin API

### ISSUE THREAD

**Issue by Vishalkale0409** [openshift/origin#1660]
Hi all,
I am facing issue while accessing openshift origin API's. I am facing error as "\"/osapi/v1beta1/authorizeTokens\" is forbidden because system:anonymous cannot list on authorizeTokens in ",

I don't understand how to provide authentication to it. I tried with creating token using cli and providing that using authentications.But still it is not working.Please Help. Thank you in advance.

**Comment by brenton** [comment]
If you want to poke around areas of the api it's probably best to use the admin account.  It's easiest to do this by finding the `openshift.local.certificates/admin/.kubeconfig` that openshift creates on startup and the copy it to `~/.kube/.kubeconfig`.  At that point all the osc commands you run will be done as the admin user.

If you want to use curl or another client simply use the client certificate under `openshift.local.certificates/admin/`.  If you want to verify the server's certificate you can use `openshift.local.certificates/ca/cert.crt`.  Don't hesitate to reopen this if you have additional questions.
