### ISSUE TITLE
pod proxying not working

### ISSUE THREAD

**Issue by jwendell** [openshift/origin#16619]
This used to work before:
```
curl --http1.1 -kv -H"Authorization: Bearer XXX" https://cluster:8443/api/v1/namespaces/ns/pods/podX1:8080/proxy/appEndPoint
```
But not anymore on Openshift 3.7. I get the error:
```
User "jwendell" cannot get pods/unsafeproxy in the namespace "ns"
```
Did anything in this regard changed in 3.7? Does the user need some special permission now?

##### Version
oc v3.7.0-alpha.0+e5b4a1c-454
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

Server xxx
openshift v3.7.0-0.126.4
kubernetes v1.7.0+80709908fd

**Comment by mfojtik** [comment]
cc @openshift/sig-security
