### ISSUE TITLE
CI: use Ansible to deploy TSB for all the e2e tests

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#16622]
At the moment the TSB e2e tests deploy the TSB themselves - should we be relying on Ansible to do this for us (and thereby at least smoke testing the Ansible functionality)?
@bparees

**Comment by bparees** [comment]
Is the rest of the cluster being stood up w/ ansible?  if so i'd be inclined to say yes...  do we have any other patterns like that?  (e.g.do we install logging and metrics that way?)

/cc @ewolinetz @stevekuznetsov

**Comment by bparees** [comment]
one challenge to this is it might end up requiring PR linking to get certain changes in (because a change to the TSB requires a change to the ansible installer which is a different repo).

We had PR linking back in the rosie days, not sure if prow offers that or not.

**Comment by stevekuznetsov** [comment]
> Is the rest of the cluster being stood up w/ ansible?

Yes, the rest of the cluster is brought up with the latest Ansible RPMs

> do we have any other patterns like that? (e.g.do we install logging and metrics that way?)

Yes.

**Comment by stevekuznetsov** [comment]
> one challenge to this is it might end up requiring PR linking to get certain changes in (because a change to the TSB requires a change to the ansible installer which is a different repo).

We will not support PR linking. Your changes have to be backward compatible. 

/cc @smarterclayton

**Comment by smarterclayton** [comment]
Yes.

**Comment by bparees** [comment]
> one challenge to this is it might end up requiring PR linking to get certain changes in (because a change to the TSB requires a change to the ansible installer which is a different repo).

@jim-minter in hindsight this comment feels portentous...

**Comment by jim-minter** [comment]
https://github.com/openshift/origin/pull/17219: so this works in ci/openshift-jenkins/extended_conformance_install, but not in ci/openshift-jenkins/extended_conformance_install_update, because install_update doesn't enable the TSB as part of the update process.  Not sure whether that means that this issue can't be dealt with for now?

**Comment by bparees** [comment]
install/update ought to work now since install/update should be installing 3.7 (which should install the TSB, right?) and then updating to 3.9.

install/update is also disabled currently for reasons i'm not entirely clear on.

**Comment by stevekuznetsov** [comment]
Install/update today is installing 3.8 and upgrading to 3.9. There is no 3.8 release. The job is broken until we have a 3.8 release.

**Comment by bparees** [comment]
thanks @stevekuznetsov.  so @jim-minter when install/update is re-enabled this should work fine since 3.8 would install the TSB.
