### ISSUE TITLE
StatefulSet doesn't support log viewing

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16650]
```
$ oc rsh sts/prometheus -c prom-proxy
error: remote shell for {apps statefulsets} is not supported
```

We need to fix this - stateful sets are now being used in more places.

@openshift/sig-user-interface

**Comment by benjaminapetersen** [comment]
We have a [trello card](https://trello.com/c/M4fAYrUT) for this in the Backlog.

@spadgett

**Comment by benjaminapetersen** [comment]
Oop, my mistake, that trello card is for UI once the APIs exist.  Think you may have created this issue to ensure the APIs exist 😄
