### ISSUE TITLE
Install origin-m4

### ISSUE THREAD

**Issue by luispimenta** [openshift/origin#16666]
I'm trying to install the openshift origin-m4 with the command:

##### Steps To Reproduce
1. sh <(curl -s https://install.openshift.com/origin-m4)

##### Current Result

/dev/fd/63: 2: /dev/fd/63: Syntax error: newline unexpected

I can not continue the origin-m4 installation

**Comment by mfojtik** [comment]
That link is 404, where did you find that instructions?

**Comment by luispimenta** [comment]
Runing : 

`sh <(curl -s https://install.openshift.com)`

Return :

```
For Origin M4 please run:
sh <(curl -s https://install.openshift.com/origin-m4)

For OpenShift Enterprise 3 run:
sh <(curl -s https://install.openshift.com/ose)
```

**Comment by pweil-** [comment]
The link provided takes me to a page with the following options:

`oc cluster up` (latest dev release)
`vagrant up` (CDK)
`atomic-openshift-installer install` (OCP)

These are our supported installation methods.  If you're looking to give it a quick spin I'd recommend `oc cluster up` as a quick and easy way to get started.

**Comment by luispimenta** [comment]
@pweil- But I need the installation of the origin M4.

How can I accomplish it? And not the latest version of openshift.

**Comment by pweil-** [comment]
@adellape I see that all M4 docs have been removed [1] [2].  Where should we be directing folks for older documentation?

[1] https://github.com/openshift/openshift-docs/pull/2819 
[2] https://github.com/openshift/openshift-docs/issues/2550

**Comment by adellape** [comment]
The m4 documentation is available at https://github.com/openshift/origin-server/tree/master/documentation.
