### ISSUE TITLE
[Conformance][templates] templateservicebroker security test should pass security tests [Suite:openshift/conformance/parallel]

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16673]
Seen here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/14910/test_pull_request_origin_extended_conformance_gce/9076/

Also note that this test took 1h to complete, we should probably lower the timeouts?

**Comment by mfojtik** [comment]
@jim-minter actually i'm not sure if this is flake or we broke this by removing the trigger controller, but since only this tests are failing...

**Comment by mfojtik** [comment]
Also we see this a lot today, maybe be well related to infrastructure or docker hub.

**Comment by tnozicka** [comment]
The errors I could spot in there: (maybe some of them have been there even before...)

138x - MySQL
```
Oct  4 11:50:26.164: INFO: At 2017-10-04 10:52:18 +0000 UTC - event for mysql-7-90h0m: {kubelet ip-172-18-8-155.ec2.internal} Unhealthy: Readiness probe failed: sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
```

4x - volume/token
```
Oct  4 11:50:26.164: INFO: At 2017-10-04 10:53:29 +0000 UTC - event for cakephp-mysql-example-1-deploy: {kubelet ip-172-18-8-155.ec2.internal} FailedMount: Unable to mount volumes for pod "cakephp-mysql-example-1-deploy_extended-test-templates-7zzb5-dc357(f8974bfc-a8f1-11e7-bf68-0e0700488850)": timeout expired waiting for volumes to attach/mount for pod "extended-test-templates-7zzb5-dc357"/"cakephp-mysql-example-1-deploy". list of unattached/unmounted volumes=[deployer-token-86mmn]
```

```
Oct  4 11:50:26.172: INFO: At 2017-10-04 11:21:54 +0000 UTC - event for mysql-106-fbn03: {kubelet ip-172-18-8-155.ec2.internal} Unhealthy: Readiness probe failed: rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:83: executing setns process caused \\\"exit status 16\\\"\"\n"
```

```
Oct  4 11:50:26.167: INFO: At 2017-10-04 11:05:08 +0000 UTC - event for mysql-42-skxh4: {kubelet ip-172-18-8-155.ec2.internal} Unhealthy: Readiness probe failed: rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container \"075f37884c5c791710283f874f950d45ddacddd7b70f7c3ef9dda2517c12390f\" does not exist\n"
```

**Comment by jim-minter** [comment]
> Also we see this a lot today, maybe be well related to infrastructure or docker hub.

@mfojtik got an example link?

**Comment by mfojtik** [comment]
@jim-minter see desc: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/14910/test_pull_request_origin_extended_conformance_gce/9076/

**Comment by jim-minter** [comment]
@mfojtik I'm already looking at that one.  You said you're seeing this a lot today, do you have a link to other instances (not associated with that PR, for example?)

**Comment by mfojtik** [comment]
@jim-minter mostly seen in that PR, several times after retesting...

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/9076/consoleFull#24991624156cbb9a5e4b02b88ae8c2f77
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/9074/consoleFull#-45662440256cbb9a5e4b02b88ae8c2f77
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/9072/consoleFull#-77707611256cbb9a5e4b02b88ae8c2f77

**Comment by jim-minter** [comment]
@mfojtik I'll continue to investigate, but looking very quickly, I think that 9076 != (9074, 9072), and 9074 == 9072.  The error messages on 9076 are different and the behaviour is different.  On 9076 it looped recreating the deployment pods again and again.  Are you confident that you've seen an instance like 9076 not on this PR?

**Comment by mfojtik** [comment]
@jim-minter usually one of them or both happens so I suspect they suffer from the same mysql thing that @tnozicka described.

**Comment by jim-minter** [comment]
@mfojtik data point: locally on my machine, master has passed these tests twice, and your branch failed looping recreating deploy pods on the first attempt.

**Comment by mfojtik** [comment]
@jim-minter what you mean failed recreating deploy pods?

**Comment by jim-minter** [comment]
see the events in the log:
```
Oct  4 10:27:32.427: INFO: At 2017-10-04 10:07:55 +0000 UTC - event for mysql-2-deploy: {kubelet ci-prtest-5a37c28-9076-ig-n-m7tk} Pulled: Container image "openshift/origin-deployer:v3.7.0-alpha.1" already present on machine
Oct  4 10:27:32.427: INFO: At 2017-10-04 10:07:56 +0000 UTC - event for mysql-2-deploy: {kubelet ci-prtest-5a37c28-9076-ig-n-m7tk} Created: Created container
Oct  4 10:27:32.427: INFO: At 2017-10-04 10:07:58 +0000 UTC - event for mysql: {deploymentconfig-controller } DeploymentAwaitingCancellation: Deployment of version 3 awaiting cancellation of older running deployments
Oct  4 10:27:32.427: INFO: At 2017-10-04 10:07:58 +0000 UTC - event for mysql: {deploymentconfig-controller } DeploymentCancelled: Cancelled deployment "mysql-2" superceded by version 3
```

lots of DeploymentAwaitingCancellation, DeploymentCancelled events; 106 mysql-N and mysql-N-deploy pods were created.

**Comment by mfojtik** [comment]
@jim-minter thanks, that sounds like something broken in the controller (deployment)

**Comment by mfojtik** [comment]
@jim-minter on the other side, it is weird that only templateinstance tests are broken ;)

**Comment by jim-minter** [comment]
@mfojtik agreed.  If the root cause is with deployments, it sounds like more test coverage is required there.  If it isn't, I'm standing by to improve the TemplateInstance tests...

**Comment by bparees** [comment]
@mfojtik assigning to you based on the last 2 comments, but let's discuss if i got it wrong.

as for increasing the timeout, i assume this only comes close to needing an hour when the tests are failing (because they take so long to fail).  How long are successful runs taking?

**Comment by bparees** [comment]
Sorry, you suggested lowering the timeout, not increasing it.  nm.

**Comment by bparees** [comment]
and @mfojtik i think we've previously established that it's all devex extended tests that turn up deployment issues :)

**Comment by jim-minter** [comment]
- #16675 covers lowering 1h timeout.
- runs 9072 and 9074 flaked due to the cakephp build failing.

FWIW I think this issue can be closed.

**Comment by jim-minter** [comment]
issue for 9072 and 9074: https://github.com/openshift/origin/issues/16676
