### ISSUE TITLE
Private registry authentication - share a secret automatically across all projects

### ISSUE THREAD

**Issue by SpeedBlack** [openshift/origin#16674]
Hello,

We have a functional OCP plaform v3.5.
We need to change the "Redhat" registry (registry.access.redhat.com) with a personal external registry.

My external registry use basic authentication (htpasswd).
On each node i run docker login and then copy $HOME/.docker/config.json to /var/lib/origin (https://github.com/openshift/origin/issues/13918). It's OK but, I have a last problem during the build. An authentication problem.

##### Version
```
# oc version
oc v3.5.5.31
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server
openshift v3.5.5.31
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
If i tried to deploy a new nodejs application (with git repository), I have the following error :
`error: build error: unable to get myregistry.example.com:5000/rhscl/nodejs-4-rhel7 sha256:29b1732f719f4d577827662a8faeea211908657de345ddef4534e3a1eabe1621`

Registry logs: 
```
time="2017-10-02T07:36:26Z" level=error msg="error authenticating user \"\": authentication failure" go.version=go1.7.6 http.request.host="myregistry.example.com:5000" http.request.id=2bcfd069-ef71-469b-9b6b-399b350643b2 http.request.method=GET http.request.remoteaddr="XX.XX.XXX.XX:xxxxx" http.request.uri="/v2/rhscl/nodejs-4-rhel7/manifests/sha256:29b1732f719f4d577827662a8faeea211908657de345ddef4534e3a1eabe1621" http.request.useragent="docker/1.12.6 go/go1.8.3 kernel/3.10.0-693.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=581890a7-dcdc-4ef5-8540-c7d084b12ce6 vars.name="rhscl/nodejs-4-rhel7" vars.reference="sha256:29b1732f719f4d577827662a8faeea211908657de345ddef4534e3a1eabe1621" version=v2.6.2
time="2017-10-02T07:36:26Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": authentication failure" go.version=go1.7.6 http.request.host="myregistry.example.com:5000" http.request.id=2bcfd069-ef71-469b-9b6b-399b350643b2 http.request.method=GET http.request.remoteaddr="XX.XX.XXX.XX:xxxxx" http.request.uri="/v2/rhscl/nodejs-4-rhel7/manifests/sha256:29b1732f719f4d577827662a8faeea211908657de345ddef4534e3a1eabe1621" http.request.useragent="docker/1.12.6 go/go1.8.3 kernel/3.10.0-693.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=581890a7-dcdc-4ef5-8540-c7d084b12ce6 vars.name="rhscl/nodejs-4-rhel7" vars.reference="sha256:29b1732f719f4d577827662a8faeea211908657de345ddef4534e3a1eabe1621" version=v2.6.2
```

The only solution that I found is a create a secret in the project and add this secret for "Pull Secret" option of the project :
```
# oc secrets new-dockercfg secret-registry \
>     --docker-server=myregistry.example.com:5000 --docker-username=AAAAA \
>     --docker-password=BBBB --docker-email=CCCC@ee.com

# oc secrets link default secret-registry --for=pull
```

I would like this "secret-registry" secret be automatically reattached to the "default" service account without having to execute these commands.
Have you any idea to share this "external-registry" secret for all project ? And use this default secret to pull image for all build ? Or another solution ?

Thanks,
Best regards

**Comment by bparees** [comment]
pretty sure the answer is "we'd never want to allow this" but @mfojtik sharing secrets between projects/SAs seems like it would fall under your area.

**Comment by wanghaoran1988** [comment]
Instead of saying share a secret cross namespace, I'd like we can have a way to let the user custom the provision of a sa: like what SA will be created after a namespace created, and what secret will be created and embed in the SA.
@mfojtik

**Comment by mfojtik** [comment]
@bparees i'm not sure what sharing secret between namespaces mean, but secrets cannot be shared (except copying them automatically)

**Comment by mfojtik** [comment]
the project templates should be able to automatically create SA and secret.

**Comment by wanghaoran1988** [comment]
Thanks, yes, update the project templates add the SA and secret you needed will address this.
https://docs.openshift.org/latest/admin_guide/managing_projects.html#modifying-the-template-for-new-projects

**Comment by bparees** [comment]
> @bparees i'm not sure what sharing secret between namespaces mean, but secrets cannot be shared (except copying them automatically)

i meant accessing/using/referencing a secret in one namespace, from another namespace.
