### ISSUE TITLE
Downgrading from clusterroles to roles

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#16670]
I deleted a clusterrole in prow and created the respective role since all components run and crud stuff inside a namespace. 
```
[mkargaki@dhcp129-211 release]$ oc get clusterrole/plank clusterrolebinding/plank
Error from server (NotFound): clusterroles "plank" not found
Error from server (NotFound): clusterrolebindings "plank" not found
[mkargaki@dhcp129-211 release]$ oc get role/plank rolebinding/plank 
NAME
roles/plank

NAME                 ROLE      USERS     GROUPS    SERVICE ACCOUNTS   SUBJECTS
rolebindings/plank   /plank                        plank              
```
but it seems that the service account is still trying to use the missing clusterrole
```
{"error":"error listing prow jobs: response has status \"403 Forbidden\" and body \"{\n  \"kind\": \"Status\",\n  \"apiVersion\": \"v1\",\n  \"metadata\": {},\n  \"status\": \"Failure\",\n  \"message\": \"User \\\"system:serviceaccount:ci:plank\\\" cannot list prowjobs.prow.k8s.io in project \\\"ci\\\": clusterrole.rbac.authorization.k8s.io \\\"plank\\\" not found\",\n  \"reason\": \"Forbidden\",\n  \"details\": {\n    \"group\": \"prow.k8s.io\",\n    \"kind\": \"prowjobs\"\n  },\n  \"code\": 403\n}\n\"","level":"error","msg":"Error syncing.","time":"2017-10-04T10:26:24Z"}
```
I recreated the sa and the deployment but the error seems to persist.

@enj

**Comment by kargakis** [comment]
In the meantime, I have rolled back to clusterroles.

**Comment by kargakis** [comment]
[Here](https://github.com/openshift/release/blob/4dfd683bf70f56b7ac69a3a6919da3bf956f2492/cluster/ci/config/prow/openshift/plank_rbac.yaml) is the policy for plank - roles are exactly the same minus the kinds.

**Comment by enj** [comment]
The `clusterrole.rbac.authorization.k8s.io "plank" not found` is a good indicator of what is wrong.  Specifically, the role reference kind has no meaning in origin authz.  You need to directly specific a namespace at https://github.com/openshift/release/blob/4dfd683bf70f56b7ac69a3a6919da3bf956f2492/cluster/ci/config/prow/openshift/plank_rbac.yaml#L41-L44 for it to understand that you mean to reference a role, and not a cluster role.  This implicit behavior goes away when you use RBAC.

**Comment by enj** [comment]
@kargakis please close this once you get the roles and bindings sorted.

**Comment by pweil-** [comment]
If this isn't a bug we can just close it now.  Please reopen if something is found.
