### ISSUE TITLE
[Conformance][templates] templateinstance readiness test should report ready soon after all annotated objects are ready [Suite:openshift/conformance/parallel]

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16672]
Seen here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/14910/test_pull_request_origin_extended_conformance_gce/9076/

**Comment by bparees** [comment]
@mfojtik is this another issue caused by your broken PR?
