### ISSUE TITLE
/etc/resolv.conf set incorrectly

### ISSUE THREAD

**Issue by hundt** [openshift/origin#16688]
After upgrading to 3.6 (from 1.5), I noticed that /etc/resolv.conf inside containers is now pointing to an *endpoint* for the kubernetes service instead of the service IP.

##### Version
```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://internal-platform-test-master-2103382434.us-east-1.elb.amazonaws.com:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. Start a pod
2. Run `cat /etc/resolv.conf` inside a container

##### Current Result

First line is `nameserver 10.247.107.11`

##### Expected Result

First line is `nameserver 172.30.0.1`

##### Additional Information

I noticed that in:

https://github.com/openshift/origin/blob/release-1.5/pkg/cmd/server/kubernetes/node.go#L288

there is the line:

```
if c.KubeletServer.ClusterDNS == ""
```

and if it is true then `c.KubeletServer.ClusterDNS` is set to be the service IP for the kubernetes service. 

In

https://github.com/openshift/origin/blob/release-3.6/pkg/cmd/server/kubernetes/node/node.go#L245
we are gated instead by 

```
if len(c.KubeletServer.ClusterDNS) == 0 {
```

because `c.KubeletServer.ClusterDNS` is now an array, not a string. But I think it is set as follows:

https://github.com/openshift/origin/blob/release-3.6/pkg/cmd/server/kubernetes/node/node_config.go#L161

Which means the `if` can never pass, because an empty string just results in a non-empty array with a single empty-string element. So it goes into the next `if`, which sets /etc/resolv.conf to point to an endpoint instead of a service IP.

One thing that is confusing me to me is that that second if (https://github.com/openshift/origin/blob/release-3.6/pkg/cmd/server/kubernetes/node/node.go#L253) seems to trigger whenever the first one doesn't, including when `c.KubeletServer.ClusterDNS` is already set, and then it overwrites `c.KubeletServer.ClusterDNS`. This behavior has been around since 1.4 (https://github.com/openshift/origin/commit/3de3eec624b410bcf7b6705133919ef98331f3f4) so I don't really understand how specifying dnsIP has ever worked since then.

**Comment by hundt** [comment]
Any update on this? It is blocking our upgrade and we are having some other issues with 1.5

**Comment by polaru** [comment]
@hundt : what is 172.30.0.1? The IP of the node where the pod is running?

**Comment by hundt** [comment]
@polaru It is the service IP for the kubernetes master service:
```
NAME                CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
kubernetes          172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     21d
```
