### ISSUE TITLE
Flake: cgroup.procs not found during volume test

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16691]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16545/test_pull_request_origin_extended_conformance_gce/9136/

**Comment by smarterclayton** [comment]
Novel new flake in cgroups @openshift/sig-master

**Comment by sjenning** [comment]
dup of https://github.com/openshift/origin/issues/16246
