### ISSUE TITLE
How to acceess the UI on 443 instead of 8443?

### ISSUE THREAD

**Issue by sureshpalemoni** [openshift/origin#16694]
I am not able to access the master GUI outside my tenant n/w with 8443 as port is blocked. I have tried to create routes and change the master-config file but still no luck.

I followed this link: https://blog.openshift.com/run-openshift-console-port-443/

Could anybody explain how to setup gui with port 443?

**Comment by spadgett** [comment]
@sureshpalemoni Have you tried configuring the port as described here?

https://docs.openshift.com/container-platform/3.6/install_config/install/advanced_install.html#configuring-host-port

**Comment by sureshpalemoni** [comment]
I have changed the inventory file: to have this parameter - openshift_master_console_port=443. Still I am not able to open the console. 

I have attached a public IP to the VM, but console is opening with internal IP with port 8443 only - losing the connection after login.

When I open the /etc/origin/master/master-config.yml file:

  masterPublicURL: https://PublicIP:8443
  publicURL: https://PublicIP/console/
  servingInfo:
    bindAddress: 0.0.0.0:443

**Comment by jwforres** [comment]
@sureshpalemoni the console doesn't proxy the API, it hits it directly from the browser. This means you need the API publicly accessible as well.  That means you also need to set openshift_master_api_port to 443

Based on your master config's masterPublicURL it doesn't look like you were doing that.

**Comment by Sispheor** [comment]
Same for me on Openshift 3.11.
Still struggling with this config.

I first deployed with the default 8443.
I followed each step of the blog page.

It worked for me, I could reach the console but this last redirect me each time on port 8443 for the oauth url.

So I've updated my config like this
```
openshift_master_api_port: 443
openshift_master_console_port: 443
```

Ran the master config playbook
```

```

The playbook stuck on task "[openshift_control_plane : Wait for control plane pods to appear] "
With a message at the end
```
failed: [dev-eu-nico-test-master-1] (item=etcd) => {"attempts": 60, "changed": false, "item": "etcd", "msg": {"cmd": "/bin/oc get pod master-etcd-dev-eu-nico-test-master-1 -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "The connection to the server master.service.dc1.consul:8443 was refused - did you specify the right host or port?\n", "stdout": ""}}
failed: [dev-eu-nico-test-master-3] (item=etcd) => {"attempts": 60, "changed": false, "item": "etcd", "msg": {"cmd": "/bin/oc get pod master-etcd-dev-eu-nico-test-master-3 -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "The connection to the server master.service.dc1.consul:8443 was refused - did you specify the right host or port?\n", "stdout": ""}}
failed: [dev-eu-nico-test-master-2] (item=etcd) => {"attempts": 60, "changed": false, "item": "etcd", "msg": {"cmd": "/bin/oc get pod master-etcd-dev-eu-nico-test-master-2 -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "The connection to the server master.service.dc1.consul:8443 was refused - did you specify the right host or port?\n", "stdout": ""}}
```

The playbook tries to reach the service on port **8443**, the previous config so..

**Comment by bessalahAmar** [comment]
@Sispheor did you find any solution for that ?

**Comment by Sispheor** [comment]
sory @bessalahAmar I don't use this version of Openshift anymore.
