### ISSUE TITLE
Unable to use latest ansible with origin-gce, networking setup failure for docker

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16709]
https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/ has been failing since Oct 1 for a small number of flakes which appear related to docker builds accessing the network.  This prevents us from bringing the latest openshift-ansible into the Origin test suites.

It appears this is related to a failure to configure docker and iptables in the correct order, possibly due to Ansible changes made on Oct 1 -> 2.

**Comment by smarterclayton** [comment]
@danwinship @bparees @michaelgugino @sdodson the issue being discussed in IRC.  A test cluster is up that can report the problem.

**Comment by smarterclayton** [comment]
Last green run was https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/468/ Oct 1 11:51PM, the next unambiguous failure was https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/470/ Oct 3 at 1:47PM

**Comment by smarterclayton** [comment]
That's from roughly openshift/openshift-ansible@a9271345b868ca4e9f858d87dd89a31e324ec858 to openshift/openshift-ansible@478cf5dc597433c75de0f513a26eb77a41c38e38

**Comment by smarterclayton** [comment]
Re-opening, https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/489/ failed which should have had the fix.  I kicked a second run, if it also fails I'll create a cluster for debugging.

**Comment by smarterclayton** [comment]
Second run also failed the same way, please ping me on monday and I'll spin up a cluster for additional debugging.

**Comment by smarterclayton** [comment]
We're now 2 weeks behind, bumping to p0

**Comment by smarterclayton** [comment]
Still failing, same symptom https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/495/testReport/(root)/Extended/_Feature_Builds__Conformance__build_without_output_image__building_from_templates_should_create_an_image_from_a_docker_template_without_an_output_image_reference_defined__Suite_openshift_conformance_parallel_/

**Comment by smarterclayton** [comment]
Currently reproduced even with latest master changes on ci-scotttest3-ig-n-c4vt, ansible logs are on ci-scotttest3-ig-m-hk47 in /home/clayton/ansible.log

**Comment by ingvagabund** [comment]
How is it possible that this issue got closed by me and other folks without our knowledge? Weird. Thanks @smarterclayton for re-opening.

**Comment by smarterclayton** [comment]
Because the commit had "fixed" in, so when you push it to your master
GitHub gets confused.  Generally we should avoid using fixes XXX inside
commit messages but it's not a huge deal.

On Oct 11, 2017, at 7:13 AM, Jan Chaloupka <notifications@github.com> wrote:

How is it possible that this issue got closed by me and other folks without
our knowledge? Weird. Thanks @smarterclayton
<https://github.com/smarterclayton> for re-opening.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/16709#issuecomment-335776632>,
or mute the thread
