### ISSUE TITLE
Proxy action always resolves as unsafeproxy, even with authenticated users

### ISSUE THREAD

**Issue by DirectXMan12** [openshift/origin#16710]
Requests to the proxy subresource are transformed to be the `unsafeproxy` action, even when the users are authenticated and not coming from a direct browser request.  

The comment at https://github.com/openshift/origin/blob/050c9eaa0d758e66f576b97da9aef1d9559a563c/pkg/authorization/authorizer/browser_safe_request_info_resolver.go#L56 seems to imply that RBAC subresource should be `proxy` for authenticated users / users not coming directly from a browser, and `unsafeproxy` for non-authenticated users or direct browser requests.

However, according to https://github.com/openshift/origin/blob/050c9eaa0d758e66f576b97da9aef1d9559a563c/pkg/cmd/server/kubernetes/master/master_config.go#L403 and above, the filter is installed in RequestInfoResolver, which runs *before* the generic WithAuthentication filter: https://github.com/openshift/origin/blob/050c9eaa0d758e66f576b97da9aef1d9559a563c/vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go#L491.  This ordering indicates that the browser-safe proxy filter will *never* get user information from the context (the context will always be missing the appropriate key for the user, so `UserFrom` returns that the information is missing).

This breaks the HPA, whose policy expects to be able to `/proxy` the Heapster service.  We could change the policy, but it seems like this filter just isn't working as intended.

##### Version
master as of 050c9eaa0d758e66f576b97da9aef1d9559a563c

##### Steps To Reproduce
1. Fire up OpenShift
2. Attempt a curl (with certs or a bearer token) to `/api/v1/namespaces/openshift-infra/services/https:heapster:/proxy/apis` or any other use of the proxy subresource, and notice that we receive an error that our user cannot `unsafeproxy`, not that the user can't `proxy`.

Debugged this with @frobware 
cc @deads2k since you seem to have been the last one to shuffle this code around ;-)

**Comment by DirectXMan12** [comment]
@deads2k have I missed something tricky here, or did we just not notice this because the HPA e2es aren't enabled and nothing else uses proxy?

**Comment by DirectXMan12** [comment]
FWIW, if I had to guess (haven't done a bisect), this commit probably broke it: 689cdeefd85752b2af78433fb99c8b11fc11f428 -- it's sufficently recent (around the time of https://bugzilla.redhat.com/show_bug.cgi?id=1493057) and seems to reshuffle the related code.

**Comment by deads2k** [comment]
/assign enj

I think @enj found this and has an idea to fix it.
