### ISSUE TITLE
TestScopedProjectAccess integration failed

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#16716]
Not clear to me what failed here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16715/test_pull_request_origin_integration/8960/

**Comment by soltysh** [comment]
From my digging it looks like it's the startup of the server that is failing. Still haven't got to root cause, yet.

**Comment by soltysh** [comment]
Additional test that I can consistently fail on my machine is `TestInvalidRoleRefs` from that same file.

**Comment by enj** [comment]
https://github.com/enj/origin/blob/1eed81f10256f22d4f3426722b44ae47eaf3fba7/test/integration/project_test.go#L488 is where it fails locally for me (the all project list returns 1,2,3 instead of 1,2,3,4.  @deads2k any hints on what changed to break this?

**Comment by enj** [comment]
If I put that part of the test into a loop, it fails twice and then is successful with getting a list of all 4 projects.  So it seems like a cache backing the project ACL is lagging behind more than before.

**Comment by bparees** [comment]
same(?) TestInvalidRoleRefs failure as @soltysh seen here:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16737/test_pull_request_origin_integration/9086/

**Comment by adelton** [comment]
I'm reading the issue and the logs but I somehow fail to see why this is component/auth - what seems to be the auth-related cause behind this?

**Comment by bparees** [comment]
@adelton the assumption is that "TestScopedProjectAccess" would be an auth thing.  If it's not, please determine who would own such a test.

**Comment by bparees** [comment]
(and if it is indeed an Auth test but if failed due to something not auth related, then please determine what component did fail and assign it to the appropriate component)

**Comment by adelton** [comment]
@bparees, thanks.

In https://github.com/openshift/origin/issues/16716#issuecomment-334908621, @enj suggests "cache backing the project ACL is lagging behind more than before". What component is handling the cache backing?

**Comment by enj** [comment]
This is auth because the project list is the only special ACL we have (because RBAC cannot express "list the subset of the projects I can see" - it can only express "list all projects").  The cache logic is in `pkg/project/auth/cache.go`, but I doubt its the actual cache that got slower.  The simplest approach may be a git bisect from a week before this started.

**Comment by smarterclayton** [comment]
Bumping to p0, this is failing 1/5 runs in integration https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/directory/test_pull_request_origin_integration

**Comment by mrogers950** [comment]
Bisecting and running TestScopedProjectAccess points to 84f6103

**Comment by adelton** [comment]
@deads2k, any idea what in 84f6103999da98b0908d1fa70e7b63797d37770b could be causing the problem?

**Comment by deads2k** [comment]
> @deads2k, any idea what in 84f6103 could be causing the problem?

Nothing comes to mind.

**Comment by bparees** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16811/test_pull_request_origin_integration/9229/

**Comment by bparees** [comment]
unless a fix is imminent can we disable this test? (while leaving this issue open to resolve the flake and re-enable it)

**Comment by enj** [comment]
I believe I have determined the root cause and will open a PR tomorrow.

@simo5 @mrogers950

**Comment by deads2k** [comment]
> I believe I have determined the root cause and will open a PR tomorrow.

margin too small?

**Comment by bparees** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16811/test_pull_request_origin_integration/9248/
