### ISSUE TITLE
As a user, I want an api to get the master-config.yaml 

### ISSUE THREAD

**Issue by thomasmckay** [openshift/origin#16712]
It would be helpful to be able to get the _master-config.yaml_ information via api (which would naturally lead to making it available via _oc adm_ command).

For my specific use case, I'd like to display the value of _imagePolicyConfig.maxImagesBulkImportedPerRepository_ in the registry UI since it is confusing to new users that only a subset of tags are pulled for imagestreams (default is 5).

**Comment by smarterclayton** [comment]
The plan here is that master config is going to be moved into a config map on the server and you'd be able to fetch it as an admin

**Comment by thomasmckay** [comment]
Will there be a way to expose individual config maps to non-admin users? If I have permissions to create imagestreams I would want permission to see the limitations. Otherwise only admins would see that only five tags would ever be pulled and not the average user.

**Comment by thomasmckay** [comment]
Does _oc create configmap_ not parse yaml? Worth an RFE? (I tried _oc create configmap master-yaml --from-file=master-config.yaml_)

**Comment by smarterclayton** [comment]
Yes, you can expose individual configs via RBAC.

create config map is adding files as keys in a config map.  If you have
yaml that *IS* a config map, oc create -f configmap.

The master config map would look like the result of (I tried *oc create
configmap master-yaml --from-file=master-config.yaml*) probably
