### ISSUE TITLE
Generic Build error

### ISSUE THREAD

**Issue by AndyOGo** [openshift/origin#16729]
I just tried to move my project from openshift V2 to openshift v3 online.

But if I try to build it, I just get **Generic Build Error** _- check logs for details._
So I check the logs, and there isn't a single error, just npm WARN entries.

Though my local build works.

> oc v3.6.173.0.7
> kubernetes v1.6.1+5115d708d7
> features: Basic-Auth
> 
> Server https://api.starter-ca-central-1.openshift.com:443
> openshift v3.6.173.0.7
> kubernetes v1.6.1+5115d708d7

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
Just hit build now

##### Current Result
Generic Build Error without error logs.

##### Expected Result
Successful Build through S2I

##### Additional Information
I use `npm`, `bower` and `gulp`.
I have successfully setup webhook triggers and pulling from private gitlap repos works too, though my build fails with following non-sense log:

> Cloning "git@gitlab.com:AndyGo88/webapp.git" ...
> 	Commit:	d92b8f0bb8246b5ca5f8bab00f282571ce53e83b (log all env vars)
> 	Author:	Andreas Deuschlinger
> 	Date:	Fri Oct 6 19:55:17 2017 +0200
> ---> Installing application source ...
> ---> Building your Node application from source
> npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
> npm WARN deprecated email-templates@2.7.1: v3.0.1 has been released! try it out and view the new docs at https://github.com/niftylettuce/email-templates - it supports Promises, browser previews, has a cleaner API, and much more!
> npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
> npm WARN deprecated gulp-css-globbing@0.1.9: This package is no longer actively maintained
> npm WARN deprecated gulp-uncss@1.0.6: Use UnCSS through gulp-postcss instead.
> npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
> npm WARN deprecated jade@0.29.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated transformers@1.8.3: Deprecated, use jstransformer
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated swig@1.4.0: This package is no longer maintained

**Comment by aaryabhatt** [comment]
it looks like dependencies issue with you application, try to install your app on same version OS, which you are trying to use here, you will get a better idea.

**Comment by AndyOGo** [comment]
@aaryabhatt 
Thanks for your feedback.

Well, locally I develop on OS X. And works as expected there.
I use Node 6. I only found that there has been known bugs at openshift regarding `bower` as dependency management tool. https://stackoverflow.com/questions/23937675/unable-to-install-bower-on-openshift
Though I can't find information regarding Openshift V3...

**Comment by aaryabhatt** [comment]
@AndyOGo  As this link suggest, it is not openshift bug, it is npm and bower version compatiblity issue. easy way to resolve this is you can build a container image on your mac and test the app. If that work then you can push the image there or use same steps in dockerfile.

**Comment by AndyOGo** [comment]
@aaryabhatt 
Thanks. I will try creating my own dockerfile and see what happens localy.
Though my initial plan was to use s2i 😞

**Comment by aaryabhatt** [comment]
s2i is good option but you will face issue there too, first create the proper working docker file.

**Comment by bparees** [comment]
closing as not an openshift issue.  thanks for the assist @aaryabhatt 

@AndyOGo you can also debug by building your application locally, all the s2i build process is doing is basically invoking "npm install" on your repository:
https://github.com/sclorg/s2i-nodejs-container/blob/master/6/s2i/bin/assemble#L25-L51
