### ISSUE TITLE
oc cluster fails to abort when it first fails to pull the ose image

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#16735]
https://gist.github.com/thoraxe/cc212c2aed681641bd3658dd1454f4c7

oc version = oc v3.7.0-0.127.0
kubernetes v1.7.0+80709908fd
features: Basic-Auth GSSAPI Kerberos SPNEGO

**Comment by bparees** [comment]
@coreydaley i would hope this is an easy fix (that we're just not properly checking a return code on pulling the image).

**Comment by coreydaley** [comment]
It looks like we are running into this issue: https://github.com/docker/engine-api/issues/138
Except it's line 35 now, not 30: https://github.com/docker/engine-api/blob/master/client/image_pull.go#L35

Basically ImagePull doesn't throw an error unless resp.StatusCode == http.StatusUnauthorized, it also looks like engine-api has been deprecated and now resides in github.com/docker/docker/client, which would require a decent amount of reworking of oc cluster up to replace it, as it is not just a drop in.

@bparees let me know how you would like me to proceed.

**Comment by bparees** [comment]
We can inspect to see if the image exists after we do the pull and abort if it doesn't.
