### ISSUE TITLE
import docker-compose was deleted

### ISSUE THREAD

**Issue by Emmanuel35** [openshift/origin#16748]
Import docker-compose was deleted in 3.6.
Could you replace this functionality ?

cf. https://lists.openshift.redhat.com/openshift-archives/dev/2016-May/msg00021.html
cf. https://access.redhat.com/solutions/2899101
 
##### Version
c v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. oc import docker-compose -f .\docker-compose-local.yml

##### Current Result
Error: unknown shorthand flag: 'f' in -f

Usage:
  oc import COMMAND [options]

Available Commands:
  app.json    Import an app.json definition into OpenShift (experimental)

Use "oc <command> --help" for more information about a given command.
Use "oc options" for a list of global command-line options (applies to all commands).

##### Expected Result
Import node, etc.

##### Additional Information
N/A

**Comment by php-coder** [comment]
AFAIK it was replaced in favor of https://github.com/kubernetes/kompose

CC @smarterclayton

**Comment by Emmanuel35** [comment]
Ok, thanks for your feedback.

**Comment by smarterclayton** [comment]
Yes, compose is more feature complete and covers the use case better.

**Comment by vishaldodiya** [comment]
Hello,

How can we use kompose yaml files in `oc import`?

**Comment by Fantaztig** [comment]
I'd also be interested in knowing how to move from docker compose to kompose, couldn't find any documentation on this.
