### ISSUE TITLE
cannot unmarshal array into Go value of type types.ContainerJSON

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16746]
Not clear to me if this is an error that occurs while getting pod logs, or that the pod logs actually contain this value (which they definitely should not) but either way it's a problem:

```
Oct  9 04:01:59.142: INFO: Running 'oc logs --config=/tmp/extended-test-s2i-perl-mt934-fbxrg-user.kubeconfig --namespace=extended-test-s2i-perl-mt934-fbxrg pod/dancer-mysql-example-1-jnvfq'
Oct  9 04:01:59.404: INFO: Log for pod "dancer-mysql-example-1-jnvfq"
---->
json: cannot unmarshal array into Go value of type types.ContainerJSON
<----end of log for "dancer-mysql-example-1-jnvfq"
```

if it is an error retrieving the pod logs, then the oc logs command output needs to be improved to make it clearer as to whether it's reporting its own error, or the actual pod logs.

we're hitting this from time to time in https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/243/testReport/junit/(root)/Extended/_image_ecosystem__perl__Slow__hot_deploy_for_openshift_perl_image__Dancer_example_should_work_with_hot_deploy__Suite_openshift_/

**Comment by mfojtik** [comment]
@bparees ContainerJSON is Docker API type. When this started to happen? After rebase? 

@soltysh did we bumped docker distribution?

**Comment by bparees** [comment]
@mfojtik not sure, i've noticed it within the last week or so.

**Comment by soltysh** [comment]
> @soltysh did we bumped docker distribution?

Nope.

**Comment by sjenning** [comment]
@ingvagabund PTAL

**Comment by ingvagabund** [comment]
Found the same error message in https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/305/console:
```
[INFO] [CLEANUP] Dumping container logs to _output/scripts/core/logs/containers
[INFO] [CLEANUP] Truncating log files over 200M
[INFO] [CLEANUP] Stopping docker containers
[INFO] [CLEANUP] Removing docker containers
Error: No such image, container or task: c506b5635854
json: cannot unmarshal array into Go value of type types.ContainerJSON
Error response from daemon: You cannot remove a running container d291014e73fd6177fe4723fa141f330c7c8f30f0d84570576bfcfbdd53553e4e. Stop the container before attempting removal or use -f
Error response from daemon: You cannot remove a running container a6ab51761f17b87dc5d81d082b5d844d20f0ddc0eeba9f5e87fdaf90b3604225. Stop the container before attempting removal or use -f
```

**Comment by ingvagabund** [comment]
>Oct  9 04:01:59.142: INFO: Running 'oc logs --config=/tmp/extended-test-s2i-perl-mt934-fbxrg-user.kubeconfig --namespace=extended-test-s2i-perl-mt934-fbxrg pod/dancer-mysql-example-1-jnvfq'
Oct  9 04:01:59.404: INFO: Log for pod "dancer-mysql-example-1-jnvfq"
 ---->
json: cannot unmarshal array into Go value of type types.ContainerJSON
<----end of log for "dancer-mysql-example-1-jnvfq"

The error message ``json: cannot unmarshal array into Go value of type types.ContainerJSON`` is part of the container logs as is signified by the starting ``---->`` and ending ``<----end of log for "dancer-mysql-example-1-jnvfq"`` markers. And as can be seen in the ``[INFO] [CLEANUP] Removing docker containers`` logs.

It could be related to the underlying image the affected pod runs from.

**Comment by ingvagabund** [comment]
This pretty looks to me as a docker bug. @lsm5 @runcom after some googling I found discussions saying the problem could be caused by a wrong version of the runc: https://github.com/docker/for-linux/issues/61#issuecomment-316067468

**Comment by ingvagabund** [comment]
```sh
# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-68.gitec8512b.el7.x86_64
 Go version:      go1.8.3
 Git commit:      ec8512b/1.12.6
 Built:           Thu Nov 16 15:19:17 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-68.gitec8512b.el7.x86_64
 Go version:      go1.8.3
 Git commit:      ec8512b/1.12.6
 Built:           Thu Nov 16 15:19:17 2017
 OS/Arch:         linux/amd64
```

**Comment by mirekphd** [comment]
I get this error without Openshift, running pure `docker inspect` (using Jenkins command `app.inside()`). This happens only if the `app` resulted from a non-standard call to `docker.build()`, where the dot has been moved before two `--build-arg` parameters (to work around another bug - this time in Jenkins...)

Error message from Jenkins build log:
```
[Pipeline] sh
+ docker inspect -f . ****/ml-cpu-py37-vsc-cust .
.
json: cannot unmarshal array into Go value of type types.ContainerJSON
[Pipeline] isUnix
[Pipeline] sh
+ docker pull ****/ml-cpu-py37-vsc-cust .
"docker pull" requires exactly 1 argument.
See 'docker pull --help'.

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Pull an image or a repository from a registry
```

it does not appear after standard dot at the end:
```
app = docker.build(SCM_REPO, "--build-arg REINSTALL_PYTHON_PKGS=${buildTimestamp} .")
```

but it does appear after the dot is moved before args:
```
// note we have to specify pwd explicitly rather than using a dot
// which gets deleted in case of multiple --build-arg's
app = docker.build("${SCM_REPO} .", "--build-arg REINSTALL_CODE_SERVER=${buildTimestamp} --build-arg CODER_VERSION=${latestInterfaceAppVersion}")
```

**Comment by AdiWehrli** [comment]
I had the same issue with `docker inspect <image-name> .`. I removed the dot at the end and the error vanished.
