### ISSUE TITLE
Nginx reverse proxy

### ISSUE THREAD

**Issue by ric79** [openshift/origin#16743]
Hello,
I need help for porting my application on Openshift 3

My application has
- Back-end: 3 nodeJs apps (app1, app2, app3)
- Front-end: AngularJS + Nginx 
In my current application, the nginx does reverse proxy for app1/app2/app3, hiding them. 

In Openshift I have already installed the 3 apps but I have concerns about the frontend. I have installed nginx but I have doubts about how implementing the reverse proxy. 

Should I expose just the 3 apps with public routes and use these routes in AngularJS calls?

Thanks
Riccardo

**Comment by aaryabhatt** [comment]
create a separate pod for nginx and use the current nginx proxy conf (remove ssl section) as it is replace the reverse proxy host  with backend apps service name(servicce name will be created if you deplyed it by images of apps). and then create a route for nginx and add certificate in nginx route, by doing this you need to expose only nginx app only with route.
