### ISSUE TITLE
Make template.openshift.io/provider-display-name annotation generic

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#16755]
Request to rename the annotation

`template.openshift.io/provider-display-name` 

to

 `openservicebroker.openshift.io/provider-display-name`

This will allow us to use the annotation on other resources like image streams. When you filter on publisher in the web console catalog, you can then see image streams from a provider. We're already using the `openservicebroker.openshift.io/` prefix here:

https://github.com/openshift/origin/commit/d4cf122f5c86b79bfbca58dc0226cf80021d4aeb#diff-447630aceb0d00f068fd6038e7d99d51R208

@bparees Opinion?

cc @jim-minter @sspeiche

**Comment by bparees** [comment]
i'm not sure why "openservicebroker.openshift.io/provider-display-name" would be an appropriate annotation on an imagestream?

In any case I don't love the suggestion.  We have a bunch of labels/annotations:

```
	// LongDescriptionAnnotation is a template's long description
	LongDescriptionAnnotation = "template.openshift.io/long-description"

	// ProviderDisplayNameAnnotation is the name of a template provider, e.g.
	// "Red Hat, Inc."
	ProviderDisplayNameAnnotation = "template.openshift.io/provider-display-name"

	// DocumentationURLAnnotation is the url where documentation associated with
	// a template can be found
	DocumentationURLAnnotation = "template.openshift.io/documentation-url"

	// SupportURLAnnotation is the url where support for a template can be found
	SupportURLAnnotation = "template.openshift.io/support-url"

	// TemplateInstanceLabel is used to label every object created by the
	// TemplateInstance API.
	TemplateInstanceLabel = "template.openshift.io/template-instance"
```

And putting some in the openservicebroker namespace and some in the template namespace bothers me.

Ultimately the labels are consumed and standardized by the template service broker when it creates the catalog entry.  Forcing the template itself to confirm to some service catalog/broker specific naming conventions doesn't seem right to me.

The web console catalog should be filtering on the "providerDisplayName" value in the catalog entry, not metadata in the template object, right?  Why is it even looking at the template?

**Comment by spadgett** [comment]
@bparees OK I agree that `openservicebroker.openshift.io` is probably wrong. I do think it's useful to have a more generic annotation, however.

Right now if you filter on publisher in the catalog, all of the builder images disappear. If we had a generic publisher annotation, we could also support filtering the builders.

![openshift web console 2017-10-09 14-51-07](https://user-images.githubusercontent.com/1167259/31353673-6b2a7eea-ad01-11e7-929e-31dfe099489d.png)

How about simply `openshift.io/provider-display-name`?

Arguably `template.openshift.io/documentation-url` and `template.openshift.io/support-url` could be generalized as well.

**Comment by bparees** [comment]
> How about simply openshift.io/provider-display-name?

it's ok with me, will need @openshift/api-review sign off.

**Comment by smarterclayton** [comment]
It's fine but needs to be documented in public docs

**Comment by sspeiche** [comment]
What about these annotations, can/should they be used in image-streams? If not these then what should be used?

-  "template.openshift.io/long-description"
-  "template.openshift.io/documentation-url"
-  "template.openshift.io/support-url"

**Comment by bparees** [comment]
> What about these annotations, can/should they be used in image-streams? If not these then what should be used?

we're debating if they should all be renamed to a more generic namespace as part of this.

**Comment by deads2k** [comment]
> we're debating if they should all be renamed to a more generic namespace as part of this.



> Ultimately the labels are consumed and standardized by the template service broker when it creates the catalog entry. Forcing the template itself to confirm to some service catalog/broker specific naming conventions doesn't seem right to me.

It is reasonable to apply annotations in one group to objects of another, when the meta-API you're conforming to is logically owned by the consumer.  A `template.openshift.io/*` annotation on an `image.openshift.io` resource is reasonable, even helpful, when the consumer of that annotation lives in the `template.openshift.io` API group.  The API can be owned by templates and applied to images.

The concept is similar to when we add `service.openshift.io` labels to kubernetes resources.  The meta-API is owned by openshift, the resource is owned by kube.

**Comment by bparees** [comment]
> when the consumer of that annotation lives in the template.openshift.io API group. 

Unfortunately the consumer doesn't(necessarily) live in the template api group.

The proposal here is to label a variety of resources for a variety of purposes:

templates would have the annotation(s) both for the web console to filter on, and for the TSB to use to convert to service catalog fields.

imagestreams would have the annotation(s) for the web console to filter on

**Comment by bparees** [comment]
Essentially we're just defining a standard set of annotations that the console can use when looking at objects (both templates + imagestreams. maybe other stuff in the future).

And then we'd switch the TSB to also use those annotations when it is creating service catalog entries (instead of using the "template.openshift.io" annotations it currently uses)

**Comment by deads2k** [comment]
My experience with "standard" annotations is that they fail.  I mean, we've had three years and haven't even managed to get consistent support for descriptions.  None of the three flavors we have are uniformly supported.

I don't doubt the good intent, I don't doubt the use-case, I don't doubt the willingness, but nothing generic ever seems to stick.  I'm not going to die on the hill for it, but everyone thinks "all resources could have this!" and rarely, if ever, do more than one or two actually support/use it.

**Comment by smarterclayton** [comment]
David's pretty much correct.  Just use the existing annotations if you want
them.  Don't introduce new annotations that require more things to track.

**Comment by bparees** [comment]
> David's pretty much correct.  Just use the existing annotations if you want
them.  Don't introduce new annotations that require more things to track.

Putting a "template.openshift.io/provider-display-name" annotation on an imagestream resource object makes no sense to me.

I can get behind not trying to come up with something generic, because i think we'll fail, but I really don't like the idea of adding "template.openshift.io/provider-display-name" annotations to our imagestreams, when imagestreams have nothing to do with templates or the TSB.

What i was going to suggest (before seeing @smarterclayton's latest response) is that we leave the existing template.* annotations alone, and add in imagestream.openshift.io annotations.  Yes that means the webconsole has to check for two things (and maybe more in the future), but it also means that we can tailor the annotations to the resource, rather than trying to have a single set of annotations that are generically applicable to multiple resource types.

So i guess i'm still going to suggest that.

**Comment by bparees** [comment]
@smarterclayton bump.  @sspeiche has opened a pr defining an openshift.io/provider-display-name annotation (using it on imagestreams).

You seem against that and i'm against template.openshift.io/provider-display-name, so what is your take on imagestream.openshift.io/provider-display-name?

(note that openshift.io/display-name is already in use)

**Comment by sspeiche** [comment]
Any thoughts on what this should be? I have 2 PRs that are waiting for resolution. https://github.com/openshift/origin/pull/16899 and one in JBoss repo.

The Catalog filter on provider is a bit inconsistent as we don't have the content updated.

**Comment by smarterclayton** [comment]
I'm ok with the generic name if this is novel and new and you don't want to use the template. prefix.  Prefix vs not is arbitrary.

**Comment by bparees** [comment]
talked to @smarterclayton and while he'd be willing to have us introduce an image.openshift.io namespace, i feel too guilty about it proceed so  we'll introduce openshift.io/provider-display-name as the generic annotation and update the TSB ones to be openshift.io as well.

@jim-minter i'll need to chat w/ you about any ordering implications of making the change to ensure we don't break tests, but i'll start on the PRs.
