### ISSUE TITLE
multiple paths in an openshift route?

### ISSUE THREAD

**Issue by spicysomtam** [openshift/origin#16769]
When defining a route can you define /patha goes to one service and /pathb goes to another service?

##### Version
3.6.0

##### Steps To Reproduce
Documented here with a single path: https://docs.openshift.com/container-platform/3.6/architecture/networking/routes.html#path-based-routes
Seems a bit useless with a single path, other than blocking other paths.

##### Current Result
Doesn't allow it.

##### Additional Information
So rather than having, say a nginx proxy to do the path splitting/proxying for you, the route could just do it? Saves an additional service/pods. Maybe a feature request?

**Comment by spicysomtam** [comment]
It would be cool to get this. Otherwise we have to continue using a nginx service to do the path splitting.

**Comment by pugetc** [comment]
Same need here. Maybe it will be available in OpenShift with K8s Ingress: https://kubernetes.io/docs/concepts/services-networking/ingress/#simple-fanout?

**Comment by spicysomtam** [comment]
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/openshift. The thing is there are some limitations with that; potentially the router and nginx ingress could clash if on the same node. Then it needs to be enabled by the cluster admin and some setup required. The ideal solution is to enhance openshift routes, to avoid this?

**Comment by devops-42** [comment]
/reopen
Any news in this issue? I'm interested in using the built-in router instead of deploying third-party ingress routers...

Cheers

**Comment by gkarthiks** [comment]
It would be nice to have this capability in-build with the openshift router.
