### ISSUE TITLE
after make command what is the next step

### ISSUE THREAD

**Issue by vikasgubbi** [openshift/origin#16762]
I downloaded from origin/openshift from github and ran  make command what is the next step.please let me know. i am new to openshift.is there any reference manual to how to setup.after make command what is the next stepafter make command what is the next step

**Comment by php-coder** [comment]
OpenShift users don't need to run `make` and building a binary. We're suggesting to download a prepared binary: https://docs.openshift.org/latest/getting_started/administrators.html#downloading-the-binary.

The next step is to run OpenShift (see the link bellow) and try it out: https://docs.openshift.org/latest/getting_started/administrators.html#try-it-out

To make the first experience smooth, please, consider using `oc cluster up` ([watch the screencast](https://github.com/openshift/origin/blob/master/README.md)) or [minishift](https://docs.openshift.org/latest/minishift/index.html).
