### ISSUE TITLE
openshift admin new-project doesn't indicate how to specify project name

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1677]
```
[root@ose3-master training]# openshift admin new-project --help
create a new project

Options:
      --admin='': project admin username
      --admin-role='admin': project admin role name in the master policy namespace
      --description='': project description
      --display-name='': project display name
      --master-policy-namespace='master': master policy namespace

Use "openshift admin --help" for a list of all commands available in openshift admin.
Use "openshift admin options" for a list of global command-line options (applies to all commands).
```

We probably want some indication that you need to do:

```
openshift admin new-project [OPTIONS] name
```

Or something to that effect.

```
openshift v0.4.3.0
kubernetes v0.13.1-dev-641-gf057a25
```

**Comment by smarterclayton** [comment]
There is a general cleanup that needs to be done for all commands

1. Set usage for all commands
2. Add examples for all commands
3. Ensure eric's Manual / Markdown documentation generates it (i.e., follow the upstream style).

We should do all of that at once (@fabianofranz).

**Comment by liggitt** [comment]
help templates stopped outputting the `Use` field for all commands... either need to reinstate that or embed usage in long descriptions

**Comment by smarterclayton** [comment]
We need to sync up with upstream

**Comment by fabianofranz** [comment]
Items 1) and 2) were fixed in https://github.com/openshift/origin/issues/1991. Help now displays usage info and examples from the `Example` attribute in Cobra commands.

**Comment by thoraxe** [comment]
@fabianofranz if you think #1991 fixes it, please close.

**Comment by fabianofranz** [comment]
@smarterclayton please close.
