### ISSUE TITLE
Failed to register broker with OpenShift Client 3.6.0 on OSX

### ISSUE THREAD

**Issue by galderz** [openshift/origin#16771]
Hi,

I'm using OpenShift Client v3.6.0 with Kubernate 1.6 and Docker 1.13.1 on OSX 10.11, and when sometimes `oc cluster up --service-catalog` fails to start with the following error:

    -- Installing service catalog ... FAIL
    Error: failed to register broker with service catalog: timed out waiting for the condition
    make: *** [start-openshift-with-catalog] Error 1

Here are the specific versions I use:

```
kubectl Client Version: v1.6.4
kubetail v1.2.1

OpenShift:
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
kubernetes v1.6.1+5115d708d7,
```

To get around the issue, I'm having to restart the Docker daemon, but this happens every couple of times I restart the OpenShift cluster.

Any clues on what might be the issue? How can I get more logs or debug logs?

Cheers,
Galder

**Comment by galderz** [comment]
I've replicated the issue again and executed `oc get events`. The output is [here](https://gist.github.com/galderz/ecb477b2bfafa826246530fb99a3d98e).

The most noticeable thing are the messages `no nodes available to schedule pods` `FailedScheduling` messages.

**Comment by xiaods** [comment]
out of date.

**Comment by galderz** [comment]
Hmmm, if it's out of date, what solves it? An oc upgrade? A docker upgrade? Both? Something else?

**Comment by galderz** [comment]
@xiaods Mind spilling the beans? ;)

**Comment by xiaods** [comment]
@galderz sorry for the late response. keep your docker version is stable version.
then have a try again with upstream oc. i  use docker for mac version. not for your docker version 1.13
