### ISSUE TITLE
[Conformance][templates] templateinstance security tests should pass security tests

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#16775]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16765/test_pull_request_origin_extended_conformance_gce/9386/

may (or may not) be similar to #16654

**Comment by jim-minter** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16879/test_pull_request_origin_extended_conformance_gce/9914/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16896/test_pull_request_origin_extended_conformance_gce/9904/

**Comment by bparees** [comment]
does not seem to be fixed:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16960/test_pull_request_origin_extended_conformance_gce/10090/

**Comment by smarterclayton** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16986/test_pull_request_origin_extended_conformance_gce/10230/

Might be related to jims last
