### ISSUE TITLE
hack/env make release exited with status code 2

### ISSUE THREAD

**Issue by vikasgubbi** [openshift/origin#16794]
[provide a description of the issue]
ERROR] PID 18910: hack/lib/build/environment.sh:166: `return "${exitcode}"` exited with status 2.

After running hack/env make release got the above error message.

Currently following the CONTRIBUTING.adoc

**Comment by pweil-** [comment]
@vikasgubbi can you post the full output you're seeing?  I'm not sure we have enough to go on here.

**Comment by vikasgubbi** [comment]
please close the ticket.able to configure minishift
