### ISSUE TITLE
Suspicious errors in the integration test logs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16835]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16571/test_pull_request_origin_integration/9281/

```
   		I1012 15:07:30.477385   32591 wrap.go:42] GET /api/v1/namespaces/default/services?fieldSelector=metadata.name%!D(MISSING)docker-registry&resourceVersion=0: (510.465µs) 200 [[integration.test/v1.7.6+a08f5eeb62 (linux/amd64) kubernetes/c84beff/system:serviceaccount:openshift-infra:serviceaccount-pull-secrets-controller] 127.0.0.1:55310]
    		I1012 15:07:30.477663   32591 wrap.go:42] GET /api/v1/namespaces/openshift-infra/secrets?fieldSelector=type%!D(MISSING)kubernetes.io%!F(MISSING)service-account-token&resourceVersion=403&watch=true: (25.981571ms) 200 [[integration.test/v1.7.6+a08f5eeb62 (linux/amd64) kubernetes/c84beff] 127.0.0.1:55066]
 ```

**Comment by smarterclayton** [comment]
@openshift/sig-master

**Comment by mfojtik** [comment]
seems like the `RegistryServiceName` in `~/go/src/github.com/openshift/origin/pkg/serviceaccounts/controllers/docker_registry_service.go` is not set or empty, probably lost in controller refactoring somehow?

**Comment by deads2k** [comment]
Pretty sure it is hardcoded: https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/controller/serviceaccount.go#L101

**Comment by deads2k** [comment]
@smarterclayton `=` becomes `%3d` when encoded for a URL, right?

**Comment by deads2k** [comment]
> @smarterclayton = becomes %3d when encoded for a URL, right?

Yeah, `InfoDepth` does a second `Fprintf` on the message from here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go#L151
