### ISSUE TITLE
Remove sti-image-builder from our build-images flow

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1683]
It's not dependent on openshift, and should be built somewhere else.

**Comment by bparees** [comment]
I don't know that it needs to be built anywhere for now, frankly, it's not being used at the moment.  might be more interesting when we move to using openshift as our build infrastructure.

**Comment by mfojtik** [comment]
+1 @bparees this will be essential part of our own build system in future

**Comment by soltysh** [comment]
@bparees can you please close this one since @mfojtik's PR got merged?
