### ISSUE TITLE
NetworkCheck blocks keyboard interrupt

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#16847]
There is some code in the NetworkCheck diagnostic to handle an interrupt; however it has the effect of blocking them until the diagnostic completes, which is not user friendly.

##### Version

```
$ oc version
oc v3.7.0-alpha.1+86fefdf-1060-dirty
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth
```

But this is probably true since the diagnostic was introduced. 

##### Steps To Reproduce
1. oc adm diagnostics NetworkCheck
2. Ctrl-C

##### Current Result
Continues until the diagnostic completes

##### Expected Result
Aborts

**Comment by pravisankar** [comment]
I could not reproduce the issue on my local machine (using dind cluster). What's the issue with the current code?
```
[ravi@dhcp-16-230 origin]$ oc version
oc v3.7.0-alpha.1+c80317c-1034-dirty
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

[ravi@dhcp-16-230 origin]$ oc adm diagnostics NetworkCheck
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/admin.kubeconfig'

[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint

^CERROR: [DNet2006 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:137]
       Creating network diagnostic pod "network-diag-pod-bg916" on node "openshift-node-1" with command "openshift infra network-diagnostic-pod -l 1" failed: namespaces "network-diag-ns-2ml4c" not found

[Note] Summary of diagnostics execution (version v3.7.0-alpha.1+c80317c-1034-dirty):
[Note] Errors seen: 1
[ravi@dhcp-16-230 origin]$
```

**Comment by sosiouxme** [comment]
The current code does nothing to end the diagnostic when an interrupt is received. The goroutine performs cleanup and exits, but nothing else happens until the diagnostic completes whatever it was doing (in your case, it completed with an error because the namespace has been deleted out from under it). Worse, the signal handler is still directing interrupts to the channel, but nothing is listening to that channel, so any further interrupts go to limbo. So you can't interrupt later diagnostics either.

```
$ oc adm diagnostics  NetworkCheck  ClusterRoleBindings
[...]
[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint
       
^CERROR: [DNet2006 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:137]
       Creating network diagnostic pod "network-diag-pod-x1vhb" on node "ip-172-18-0-248.ec2.internal" with command "openshift infra network-diagnostic-pod -l 1" failed: pods "network-diag-pod-x1vhb" is forbidden: unable to create new content in namespace network-diag-ns-ss4qd because it is being terminated.
       
[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects
       
^C^C^C^C^C^C^C^CInfo:  clusterrolebinding/cluster-readers has more subjects than expected.
       
       Use the `oc adm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.
[...]
```

**Comment by pravisankar** [comment]
@sosiouxme Thanks, now I understood the actual issue and the fix.
Main changes:
  - Running actual check in a go routine along with a channel helps to terminate the diagnostic faster.
  - Stopping the signal notification once we catch it in a diagnostic allows other diagnostic checks to react to the signal if needed.
