### ISSUE TITLE
Some system roles missing authorization.openshift.io/system-only annotation

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#16862]
Some roles are showing up in the web console membership page that probably shouldn't because they're missing the `authorization.openshift.io/system-only` annotation. See

![openshift web console 2017-10-13 12-08-42](https://user-images.githubusercontent.com/1167259/31555571-840586c4-b00f-11e7-9a28-1f45a06604b3.png)

`service-catalog-controller` shouldn't be there and maybe some others. The console will hide roles with that annotation unless a "Show system roles" checkbox is checked.

cc @benjaminapetersen @enj @pmorie 

##### Version

oc v3.7.0-alpha.1+572fb85-1047
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+572fb85-1047
kubernetes v1.7.6+a08f5eeb62

**Comment by enj** [comment]
Sounds like the roles in `examples/service-catalog/service-catalog.yaml` need to be updated to have the annotation.

**Comment by benjaminapetersen** [comment]
I think this made sense back when we first introduced it, but it seems like there are too many parties adding roles now to keep up.  It might make sense to go back to a whitelist of roles in the config file of the console (or we just hard-code it in the membership module), and allow role authors to add an annotation to `userFacing: true` to add to this whitelist.

**Comment by liggitt** [comment]
+1 for whitelist. you will never get all role creators to annotate.

**Comment by benjaminapetersen** [comment]
Back to where we started :)

**Comment by jwforres** [comment]
should we be whitelisting on the roles using an annotation, or whitelisting in the console using an extension with sane defaults

**Comment by benjaminapetersen** [comment]
Perhaps just a list in `config.js`?

**Comment by jwforres** [comment]
@benjaminapetersen wouldn't be in config.js, it would be in constants.js if we do it in the console code. I'm fine with going back to that.  Just means @enj needs to let us know when there is a new default role that makes sense to expose to users.  I expect this will not be often...

**Comment by benjaminapetersen** [comment]
Sorry, meant `constants.js`, yup!

**Comment by spadgett** [comment]
Looks like `sar-creator` and `namespace-viewer` are also coming from the service-catalog template, too.

**Comment by benjaminapetersen** [comment]
History:
- issue #14411 
- PR #14510, 
- PR #15241

**Comment by enj** [comment]
@benjaminapetersen please open an origin PR for 3.8 to gut all the system-only stuff.
