### ISSUE TITLE
2 deployer pods are present for a brief moment 

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#16870]
This is probably because we don't wait for them to be deleted and allow deploying newer RC just because the old one is marked cancelled but this doesn't mean the deployer pod has been deleted yet as that is handled asynchronously by deployer controller.

@smarterclayton this is the issue you pinged me about
cc: @mfojtik 

Seen in https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/502/testReport/junit/(root)/Extended/_Feature_DeploymentConfig__deploymentconfigs_when_run_iteratively__Conformance__should_only_deploy_the_last_deployment__Suite_openshift_conformance_parallel_/

[logs.txt](https://github.com/openshift/origin/files/1383699/logs.txt)

**Comment by sjenning** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16896/test_pull_request_origin_extended_conformance_gce/9904/

**Comment by smarterclayton** [comment]
This was probably pushed over the edge into continuous failures by https://github.com/openshift/origin/pull/16913 - we clean up pods faster, so the controller is more likely to race.

**Comment by smarterclayton** [comment]
Bumping priority since this is breaking most jobs - @tnozicka said he had recreated and is working on a fix.

**Comment by tnozicka** [comment]
@smarterclayton yes, that seem probable because it now waits for about 3s in terminating state and in the meantime we create a new RC and new deployer pod

**Comment by tnozicka** [comment]
temporarily disabling the check https://github.com/openshift/origin/pull/16956

**Comment by tnozicka** [comment]
I thing this is just the check actually seeing 2 deployer pods in non terminating state although they aren't actually running. There seems to be a bug in kubelet updating pod phase from `Succeeded` to `Pending` https://github.com/openshift/origin/issues/17011

**Comment by tnozicka** [comment]
It has been confirmed to be caused by https://github.com/openshift/origin/issues/17011 which is now fixed
