### ISSUE TITLE
Post-`osc login` message doesn't check if user has permission to create projects

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#1688]
@liggitt maybe I'm doing something wrong here, but I can't create a new project after login:

```
[vagrant@openshiftdev origin]$ osc login
Authentication required for https://192.168.121.130:8443 (openshift)
Username: mfojtik
Password: 
Login successful.

You don't have any projects. If you have access to create a new project, run

    $ openshift ex new-project <projectname> --admin="mfojtik"

To be added as an admin to an existing project, run

    $ openshift ex policy add-role-to-user admin "mfojtik" -n <projectname>

[vagrant@openshiftdev origin]$ openshift ex new-project mfojtik --admin="mfojtik"
F0410 10:38:26.535044   21547 new_project.go:47] "/osapi/v1beta1/projects/mfojtik" is forbidden because mfojtik cannot get on projects with name "mfojtik" in mfojtik
```

**Comment by liggitt** [comment]
You need to create the project as a cluster admin. The user you are logged in as does not have project creation permission

**Comment by ncdc** [comment]
Why can't users create their own projects?

**Comment by mfojtik** [comment]
@liggitt maybe we should then remove the suggestion about creating new projects, or check if the user has right to do so and replace the content if the help message with something like 'contact the cluster admin to create a project for you'

**Comment by liggitt** [comment]
To be fair, the suggestion does say "If you have access to create a new project...", but checking and tailoring the suggestion could be reasonable.
