### ISSUE TITLE
five "du" process taking high percentage cpu

### ISSUE THREAD

**Issue by thomasmckay** [openshift/origin#16883]
After letting openshift run over the weekend (started w/ minishift on centos7 VM), the VM has 100% cpu consumed by 5 "du" process. openshift process itself has a modest 20%. The openshift console shows no events or other indication things are not working correctly.

##### Version
$ minishift openshift version
openshift v3.7.0-alpha.1+259bd33-1104
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8

##### Steps To Reproduce
1. start openshift (w/ minishift?)
2. wait a weekend

##### Expected Result
CPU not pegged by _du_

**Comment by pweil-** [comment]
@thomasmckay it's hard to tell that this is an OpenShift related issue based on the description.  Please open this against the minishift repo.

**Comment by Jmainguy** [comment]
I found 27 du -s running today eating lots of cpu, killed them and they came right back. This is a openshift issue and not a specific minishift issue. We are running a 9 node cluster and it was only doing this on one of the app nodes.
