### ISSUE TITLE
Metrics are not available. [using oc cluster up]

### ISSUE THREAD

**Issue by JooyoungJeong** [openshift/origin#16902]
Hi. 
[provide a description of the issue]
i created oc using  oc cluster up   in ec2(AWS)
$ oc cluster up --public-hostname="${public_hostname}" --routing-suffix="${public_ip}.nip.io" --metrics --logging --service-catalog
but, openshift-web-console's monitoring tab doesn't show matric ::

Metrics are not available.
An error occurred getting metrics for container python-test from https://hawkular-metrics-openshift-infra.35.163.xxx.xx.nip.io/hawkular/metrics.

##### Version
[provide output of the `openshift version` or `oc version` command]
 oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.6.1+5115d708d7
##### Steps To Reproduce
1. [step 1]
metadata_endpoint="http://169.254.169.254/latest/meta-data"
public_hostname="$( curl "${metadata_endpoint}/public-hostname" )"
public_ip="$( curl "${metadata_endpoint}/public-ipv4" )"
oc cluster up --public-hostname="${public_hostname}" --routing-suffix="${public_ip}.nip.io" --metrics --logging --service-catalog

2. [step 2]
connect webconsole  ->log in system -> create new project -> create sample python-app [deployment] -> monitoring ->  "Metrics are not available."

##### Current Result
Metrics are not available.
An error occurred getting metrics for container python-test from https://hawkular-metrics-openshift-infra.35.163.xxx.xx.nip.io/hawkular/metrics.

##### Expected Result
metric  data

thank you~

**Comment by rhamilto** [comment]
Pods attempt to create and then error:


Using /usr/share/ansible/openshift-ansible/ansible.cfg as config file
--
  |  
  | PLAY [Create initial host groups for localhost] ********************************
  |  
  | TASK [include_vars] ************************************************************
  | Monday 23 October 2017  12:59:37 +0000 (0:00:00.090)       0:00:00.091 ********
  | ok: [127.0.0.1] => {"ansible_facts": {"g_all_hosts": "{{ g_master_hosts \| union(g_node_hosts) \| union(g_etcd_hosts) \| union(g_new_etcd_hosts) \| union(g_lb_hosts) \| union(g_nfs_hosts) \| union(g_new_node_hosts)\| union(g_new_master_hosts) \| union(g_glusterfs_hosts) \| union(g_glusterfs_registry_hosts) \| default([]) }}", "g_etcd_hosts": "{{ groups.etcd \| default([]) }}", "g_glusterfs_hosts": "{{ groups.glusterfs \| default([]) }}", "g_glusterfs_registry_hosts": "{{ groups.glusterfs_registry \| default(g_glusterfs_hosts) }}", "g_lb_hosts": "{{ groups.lb \| default([]) }}", "g_master_hosts": "{{ groups.masters \| default([]) }}", "g_new_etcd_hosts": "{{ groups.new_etcd \| default([]) }}", "g_new_master_hosts": "{{ groups.new_masters \| default([]) }}", "g_new_node_hosts": "{{ groups.new_nodes \| default([]) }}", "g_nfs_hosts": "{{ groups.nfs \| default([]) }}", "g_node_hosts": "{{ groups.nodes \| default([]) }}"}, "changed": false}
  |  
  | PLAY [Initialization Checkpoint Start] *****************************************
  | skipping: no hosts matched
  |  
  | PLAY [Populate config host groups] *********************************************
  |  
  | TASK [Evaluate groups - g_etcd_hosts or g_new_etcd_hosts required] *************
  | Monday 23 October 2017  12:59:37 +0000 (0:00:00.066)       0:00:00.157 ********
  | skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
  |  
  | TASK [Evaluate groups - g_master_hosts or g_new_master_hosts required] *********
  | Monday 23 October 2017  12:59:37 +0000 (0:00:00.047)       0:00:00.205 ********
  | skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
  |  
  | TASK [Evaluate groups - g_node_hosts or g_new_node_hosts required] *************
  | Monday 23 October 2017  12:59:37 +0000 (0:00:00.037)       0:00:00.243 ********
  | skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
  |  
  | TASK [Evaluate groups - g_lb_hosts required] ***********************************
  | Monday 23 October 2017  12:59:37 +0000 (0:00:00.035)       0:00:00.278 ********
  | skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
  |  
  | TASK [Evaluate groups - g_nfs_hosts required] **********************************
  | Monday 23 October 2017  12:59:37 +0000 (0:00:00.058)       0:00:00.337 ********
  | skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
  |  
  | TASK [Evaluate groups - g_nfs_hosts is single host] ****************************
  | Monday 23 October 2017  12:59:37 +0000 (0:00:00.060)       0:00:00.397 ********
  | skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
  |  
  | TASK [Evaluate groups - g_glusterfs_hosts required] ****************************
  | Monday 23 October 2017  12:59:38 +0000 (0:00:00.065)       0:00:00.463 ********
  | skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
  |  
  | TASK [Evaluate groups - Fail if no etcd hosts group is defined] ****************
  | Monday 23 October 2017  12:59:38 +0000 (0:00:00.028)       0:00:00.492 ********
  | fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one or three hosts. These hosts may be the same hosts as your masters. If this is an upgrade you may set openshift_master_unsupported_embedded_etcd=true until a migration playbook becomes available.\n"}
  |  
  | PLAY RECAP *********************************************************************
  | 127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1
  |  
  |  
  | Monday 23 October 2017  12:59:38 +0000 (0:00:00.048)       0:00:00.540 ********
  | ===============================================================================
  | include_vars ------------------------------------------------------------ 0.07s
  | Evaluate groups - g_nfs_hosts is single host ---------------------------- 0.07s
  | Evaluate groups - g_nfs_hosts required ---------------------------------- 0.06s
  | Evaluate groups - g_lb_hosts required ----------------------------------- 0.06s
  | Evaluate groups - Fail if no etcd hosts group is defined ---------------- 0.05s
  | Evaluate groups - g_etcd_hosts or g_new_etcd_hosts required ------------- 0.05s
  | Evaluate groups - g_master_hosts or g_new_master_hosts required --------- 0.04s
  | Evaluate groups - g_node_hosts or g_new_node_hosts required ------------- 0.04s
  | Evaluate groups - g_glusterfs_hosts required ---------------------------- 0.03s
