### ISSUE TITLE
Router Stuck

### ISSUE THREAD

**Issue by LostStudent** [openshift/origin#16923]
on the Dashboard > Routes

Message with spinner says: "The route is not accepting traffic yet because it has not been admitted by a router"

oc status:
...
Errors:
  * route/carshowsserver is routing traffic to svc/carshowsserver, but either the administrator has not installed a router or the router is not selecting this route.
 

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
Dont know - It was working ...  then it wasn't...

##### Current Result
Standard holding/error page when accessing app url

##### Expected Result
Node app to show - 

##### Additional Information
Curl on pod terminal shows node app as it should.

Only external traffic not hitting app.

 oc adm diagnostics contains:

[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint
       
ERROR: [DNet2001 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:83]
       Checking network plugin failed. Error: User "c**@**.com" cannot get clusternetworks at the cluster scope: User "c**@**.com" cannot get clusternetworks at the cluster scope (get clusterNetworks default)

Sorry in advance im noob....

**Comment by LostStudent** [comment]
I think the original route was created automatically when I added the NodeJS image. I since deleted and recreated multiple times to try to fix: once through the Web Console UI (Routes - Create Route) and another time with commandline: oc expose svc/carshowsserver

I cant see how to get any logs pertaining to routes...

yaml:
apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2017-10-18T08:13:47Z'
  labels:
    app: carshowsserver
  name: carshowsserver
  namespace: carshowsnodemg
  resourceVersion: '109288383'
  selfLink: /oapi/v1/namespaces/carshowsnodemg/routes/carshowsserver
  uid: 440ccace-b3dc-11e7-b95b-02d8407159d1
spec:
  host: carshowsserver-carshowsnodemg.193b.starter-ca-central-1.openshiftapps.com
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: carshowsserver
    weight: 100
  wildcardPolicy: None
status:
  ingress: []

**Comment by pweil-** [comment]
@LostStudent the router itself is probably running in a namespace other than `carshowserver`.  It should be either in the infra namespace or the default namespace depending on how you've installed it.  Try `oc get pods --all-namespaces` to try and figure out where it is.  If you don't see it then it needs to be installed in order for the route to be accepted.  If you do see it please post logs from the pod, the pod definition, and any events from that namespace.

Thanks

**Comment by LostStudent** [comment]
Thanks, This is now working without changing anything.. good when bugs fix themselves.. or syknet is taking over....
