### ISSUE TITLE
Application is not available after successful deployment

### ISSUE THREAD

**Issue by tomaszkurgan** [openshift/origin#16921]
Application worked fine, but all of the sudden it stopped working.
After successful deployment of the application, there is no access to it in a browser.
"Application is not available" appears all the time. Logs look just fine.

##### Version
oc v3.6.173.0.7
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://api.starter-ca-central-1.openshift.com:443
openshift v3.7.0-0.143.3
kubernetes v1.7.0+80709908fd

##### Steps To Reproduce
1. Deploy your app successfully.
2. Go to app side in a web browser.

##### Current Result
"Application is not available" page.

##### Expected Result
App home page.

##### Additional Information
Python2.7 Django app.

Tip 1:
Maybe, this is irrelevant, but I have a Warning bar: "An error occurred getting metrics. Open Metrics URL | Don't Show Me Again" in Overview panel. Clicking "Open Metrics URL" leads me to "Application is not available" page.

Tip 2:
Just to try figure it out by myself, I created route for by database. After some time, it was still with tooltip icon: "The route is not accepting traffic yet..."

Edit:
Tip 3:
Using remote shell to login into the app pod (oc rsh)
command: curl localhost:8080 works just fine.

Edit2:
Fix some typo in the text.

**Comment by lignis** [comment]
I am experiencing the same behavior.

**Comment by mfojtik** [comment]
You can't create a route to database as the routes are http(s) only. The application is not available might suggest a problem with the router/route.

cc @openshift/sig-networking @smarterclayton

**Comment by shatsky** [comment]
Mine too. I've tried to create a new route but it got stuck with the message "The route is not accepting traffic yet because it has not been admitted by a router." When I was migrating to v3 a month ago I got the same problem on starter-us-west-1 and "solved" it with changing server to starter-ca-central-1. Such things make OpenShift Online Starter effectively unusable. I wonder if Pro clients are experiencing same problems.

**Comment by tomaszkurgan** [comment]
Just for my curiosity - is P0 more important than P1?

**Comment by mfojtik** [comment]
@tomaszkurgan yes it is :)

**Comment by harishanand95** [comment]
I'm facing a similar issue. curl localhost:8080 works fine.
Details:
Application: Django/Python3
YAML file : http://dpaste.com/2TRTCMN
Logs: http://dpaste.com/0FG43VS
oc adm diagnostics : http://dpaste.com/0GZ5Y4V

**Comment by tomaszkurgan** [comment]
Yea, everything seams to work now.
Thank You all for your help.

**Comment by harishanand95** [comment]
@tomaszkurgan thank you.. 😄 
Well, I think there should be some mechanism within the web console to report these errors with logs and other details attached.

**Comment by eparis** [comment]
Thank you so much for the report. We have identified the problem and implemented a workaround. We are tracking a permanent fix in:
https://bugzilla.redhat.com/show_bug.cgi?id=1471899
I am going to close this issue.
