### ISSUE TITLE
convert buildConfigHooks to REST resource

### ISSUE THREAD

**Issue by bparees** [openshift/origin#1692]
buildConfigHooks should be implemented as a standard REST resource.

@soltysh fyi.

**Comment by smarterclayton** [comment]
The necessary upstream work has been done so that you can implement `rest.GetterWithOptions` and get the subpath of the resource (so you can get access to `/buildconfighooks/<buildconfig>/(secret:*)/(type:*)`

**Comment by liggitt** [comment]
Fixed in https://github.com/openshift/origin/pull/2082?

**Comment by smarterclayton** [comment]
Yes, close it
