### ISSUE TITLE
Failed to resolve ImageStreamTag in deployment

### ISSUE THREAD

**Issue by darren-roberts** [openshift/origin#16930]
Build fails to pull latest tagged version of image. The image in question is openshift/redhat-openjdk18-openshift:1.1

##### Version

Server https://api.pro-us-east-1.openshift.com:443
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Push new image to GIT Hub
2, Manually execute a build

##### Current Result

Failed to resolve ImageStreamTag in deployment
##### Expected Result

Build to execute

##### Additional Information
Resolved this by deleting the build and recreating it, after the 5th or 6th push of the image to GIT.

Doesn't seem right to have to do this?

**Comment by bparees** [comment]
Do you have build logs?  Preferably level 5.

Seeing the build config json could be useful too (feel free to redact private info)

**Comment by bparees** [comment]
this was likely resolved by us fixing up the imagestream tags in the various online environments.
