### ISSUE TITLE
GCE cannot be installed due to service broker API not found

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16938]
```
TASK [template_service_broker : Register TSB with broker] **********************
Wednesday 18 October 2017  15:43:25 +0000 (0:00:00.302)       0:18:30.857 ***** 
fatal: [ci-prtest-5a37c28-9930-ig-m-h7vx]: FAILED! => {"changed": true, "cmd": "oc process -f \"/tmp/tsb-ansible-yIjjqa/template-service-broker-registration.yaml\" --param CA_BUNDLE=\"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0dmNHVnUKYzJocFpuUXRjMmxuYm1WeVFERTFNRGd6TkRBNE1ESXdIaGNOTVRjeE1ERTRNVFV6TXpJeFdoY05Nakl4TURFMwpNVFV6TXpJeVdqQW1NU1F3SWdZRFZRUUREQnR2Y0dWdWMyaHBablF0YzJsbmJtVnlRREUxTURnek5EQTRNREl3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN5VzdLR2E5T1lCUHdPSUxvenRNSDgKVUEyV2cva1piYk1jelVrbUppejRremN0bXl3MUo3VFZYdWx0SW8zS00xREhRQzRhbmJ6WmRFZWpVRWJzWXc0ZwpGSjNmUFIyTXJBL1BhR3FoK2NwUFFJRUVWaDBDdE14TGRUdHB1S0JYWXRZQlZ1N1gyWDkrWEI5VmxmS2U0ZjNsCmc3dGpiQTlQcGFjelNZelZXTTV1dS9kUGJ1WUw1TGpsNmVCTHhOQXkxN2hqZzhNVFViZkQrOExmZXdiMXh5REYKc3FZNWd0NUZJQTZZNCszZ0ZpRjk5MWhIV0NJVUFFWVhHREdDc3QzczVxbGpBOEo5N3h4aDM2ckowVlh2OFJJZQpmenpvcWx5dndGTXhiQ0NJRklJc3pzU0grdFU5a2JFRXk0ODFjdURCdzJDNE45OGcwbFJaY2N0VVJNN0FBYWZiCkFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQjh6YUpSeW5hM092WVR5S3gzU3R0ZXlsVUcrNkVlajlOdnIzbllLT3RCWFRteQpMWTVUcG1zK3dHV2l4Rm9xc21wSHVoWTVXbGVxeDhhMnpGRlMwT2l6U0JCQmlCaU1ZT1VJWHJGMy9IMWJ3cVFDCklJNitST01jdFRyUDV1cStPYnFaa3pTWEYrNFhaNlhmcFVTcXk4dUpRQjJGa1k4N2VUb0djYlpjNmp1ZGJXOUkKaFkrMEY2NjkyaHJiajVrU05oSTFDNTNuUVJ0UVJrOGJyQ3IrSXc1NXViMCtjYklPdisvUjFhSytuVlZqRFA3VQovREN5dzFwVXdXWTBCK3ZINThra3BVNmFzUDFrN3J1a2dyMEZoOUhneXlyZGliSHplZlEzYmt5a0Z1ZDU0aUhyClI4dVJuM2VhQWlQUElhanBYajljMDJNcW9JTkREVGRKbFRET1FlL3IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=\" | oc apply -f -", "delta": "0:00:00.331967", "end": "2017-10-18 15:43:26.433617", "failed": true, "rc": 1, "start": "2017-10-18 15:43:26.101650", "stderr": "error: unable to recognize servicecatalog.k8s.io/v1alpha1, Kind=ServiceBroker: no matches for servicecatalog.k8s.io/, Kind=ServiceBroker", "stderr_lines": ["error: unable to recognize servicecatalog.k8s.io/v1alpha1, Kind=ServiceBroker: no matches for servicecatalog.k8s.io/, Kind=ServiceBroker"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
ci-prtest-5a37c28-9930-ig-m-h7vx : ok=606  changed=241  unreachable=0    failed=1   
ci-prtest-5a37c28-9930-ig-n-2llf : ok=214  changed=69   unreachable=0    failed=0   
ci-prtest-5a37c28-9930-ig-n-sdgl : ok=214  changed=68   unreachable=0    failed=0   
ci-prtest-5a37c28-9930-ig-n-xbfs : ok=214  changed=68   unreachable=0    failed=0   
localhost                  : ok=34   changed=7    unreachable=0    failed=0   
```

**Comment by smarterclayton** [comment]
The last 6 hours have failed due to this (when not failing for other reasons)

**Comment by smarterclayton** [comment]
@jim-minter

**Comment by smarterclayton** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16843/test_pull_request_origin_extended_conformance_gce/9964/

**Comment by jim-minter** [comment]
I fear it's https://github.com/openshift/release/pull/275

**Comment by smarterclayton** [comment]
Let's go ahead and revert then if you can't immediately fix.  The queue is completely blocked.

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/pull/5746 needs to merge

**Comment by jim-minter** [comment]
https://github.com/openshift/release/pull/297 has merged to disable for now

**Comment by jim-minter** [comment]
@deads2k fyi ^

**Comment by smarterclayton** [comment]
The README.md in openshift/release/cluster/test-deploy contains
instructions on how to replicate the origin-gce runs so you can test things
like this.  Set OPENSHIFT_ANSIBLER_REPO as an env var to override the
ansible version included in the image.

**Comment by bparees** [comment]
> @jboyd01 @ewolinetz @bparees @smarterclayton I suspect that the move from servicecatalog.k8s.io/v1alpha1 to servicecatalog.k8s.io/v1beta1 in #16783 wasn't matched by a PR against openshift-ansible, therefore TSB and ASB installation has been broken; and because it's not tested... 😢

@pmorie @jboyd01 fyi.  I think this move also broke oc cluster up --service-catalog (https://bugzilla.redhat.com/show_bug.cgi?id=1503967)

**Comment by bparees** [comment]
(ok it looks like cluster up is working, i think the user just had misaligned client binaries + image versions)

**Comment by jboyd01** [comment]
Yeah, I did a lot of testing with oc cluster up but I agree, completely missed testing with ansible installer.  I'll do my best to ensure we don't miss this in the future, also @stabler has just done some work in this area so our team in general will have more knowledge about the installer and we'll ensure all are educated about the touch points.

**Comment by jboyd01** [comment]
Not @stabler but @staebler

**Comment by staebler** [comment]
openshift/openshift-ansible#5746 has merged, which should unblock the TSB installation. The ASB installation still needs openshift/openshift-ansible#5805 to merge before it will be unblocked.

**Comment by jim-minter** [comment]
closing as the CI is unblocked; tracking enablement of SC and TSB in CI via #16622
