### ISSUE TITLE
Controllers using 2.5x max memory in 3.7 compared to 3.6

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16955]
Controllers on 3.7 are using 2.5x the memory than a larger cluster on 3.6 (3.6 5gb @ 13k namespaces, 3.7 13gb @ 10k namespaces)

**Comment by enj** [comment]
I would be curious to know if #16986 helps with this since all listers were affected.

**Comment by mfojtik** [comment]
@smarterclayton this was because the job controller got wild, right? this was fixed and @derekwaynecarr have PR open upstream for generic quota.

**Comment by smarterclayton** [comment]
No, this was mostly because of garbage created by authorization.
