### ISSUE TITLE
Extended.[Feature:Prometheus][Feature:Builds] Prometheus when installed to the cluster should start and expose a secured proxy and verify build metrics

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16957]
looks like we're attempting to install prometheus twice:

```
go/src/github.com/openshift/origin/test/extended/prometheus/prometheus_builds.go:32
Expected error:
    <*util.ExitError | 0xc421876300>: {
        Cmd: "oc create --config=/etc/origin/master/admin.kubeconfig -f -",
        StdErr: "Error from server (AlreadyExists): serviceaccounts \"prometheus\" already exists\nError from server (AlreadyExists): clusterrolebindings.authorization.openshift.io \"prometheus-cluster-reader\" already exists\nError from server (AlreadyExists): routes.route.openshift.io \"prometheus\" already exists\nError from server (AlreadyExists): services \"prometheus\" already exists\nError from server (AlreadyExists): secrets \"prometheus-proxy\" already exists\nError from server (AlreadyExists): statefulsets.apps \"prometheus\" already exists\nError from server (AlreadyExists): configmaps \"prometheus\" already exists\nError from server (AlreadyExists): routes.route.openshift.io \"alerts\" already exists\nError from server (AlreadyExists): services \"alerts\" already exists\nError from server (AlreadyExists): secrets \"alerts-proxy\" already exists\nError from server (AlreadyExists): configmaps \"prometheus-alerts\" already exists",
```

@gabemontero I assume this is specific to our test, but if you think it's a generic prometheus issue feel free to reassign.

**Comment by bparees** [comment]
from https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/244/testReport/junit/(root)/Extended/_Feature_Prometheus__Feature_Builds__Prometheus_when_installed_to_the_cluster_should_start_and_expose_a_secured_proxy_and_verify_build_metrics__Suite_openshift_/

**Comment by gabemontero** [comment]
So commit https://github.com/openshift/origin/commit/16373cc68bc5305131d1768a9f7612a3275f3ce9#diff-d834a5fd4c91cb4a584e1113a1db37a5 from @smarterclayton with the switch from Deployments to StatefulSets in the template broke the existence check at https://github.com/openshift/origin/blob/master/test/extended/prometheus/prometheus.go#L293-L298

Do based on which extended test runs first either the tests in prometheus.go or the tests in prometheus_build.go will fail when they are the second test to run.

I'll have a PR ready in a few.

**Comment by bparees** [comment]
ah, now it makes sense. thanks.  well sort of anyway.  i wouldn't really expect us to run both of those tests in any one run.  (one is conformance bucket and one is builds bucket)

**Comment by bparees** [comment]
but maybe this was when we were still running some conformance tests in our builds bucket by accident.
