### ISSUE TITLE
Labels on secrets are not visible on the UI

### ISSUE THREAD

**Issue by matzew** [openshift/origin#16969]
For things like ConfigMaps the labels are visible in the UI. For secrets they are not directly visible. I only see them when I look into the YAML file of the secret (or on the shell, like ` oc get secret -n mynamespace my-secret -o jsonpath="{.metadata.labels.somethign}"
`

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.37.1:8443
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
adding a label to a secret, and notice the UI does not directly show it

##### Current Result
no label visible on the UI - only in the (edit) YAML file option

##### Expected Result
Labels would be show, like on ConfigMaps

**Comment by spadgett** [comment]
Fixed in 3.9: https://github.com/openshift/origin-web-console/pull/2805

/close
