### ISSUE TITLE
RBAC DENY: system:serviceaccount:openshift-infra:image-import-controller cannot "create" resource "imagestreammapping.image.openshift.io" cluster-wide

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#16987]
Start latest master, do `oc create -f examples/image-streams/image-streams-centos7.json -n openshift`

```
I1020 22:17:48.789919    8898 rbac.go:116] RBAC DENY: user "system:serviceaccount:openshift-infra:image-import-controller" groups ["system:serviceaccounts" "system:serviceaccounts:openshift-infra" "system:authenticated"] cannot "create" resource "imagestreammapping.image.openshift.io" cluster-wide
```

Presumably need to add missing rule and check why this slipped test coverage.

**Comment by jim-minter** [comment]
@bparees please can you assign?

**Comment by bparees** [comment]
@jim-minter i can't recreate this....  and if it were really broken i'd expect our importing to be failing which would fail lots of tests...

from what I can see we've never given this permission before:
https://github.com/openshift/origin/blob/0818d5700f29ab66dcba88130b108c8c505224bc/pkg/cmd/server/bootstrappolicy/controller_policy.go#L237-L246

so i'm not sure why we'd be seeing this error now (also it doesn't seem to be breaking anything about image import).

@legionus @dmage do you know where(if anywhere) we might be using the imagestreamimportcontroller SA to try to create imagestreammappings or why the RBAC denial would not be breaking anything?

**Comment by enj** [comment]
Maybe the way @jim-minter is starting the master creates different bindings?

**Comment by bparees** [comment]
@enj maybe, i'm just doing openshift start.

but i don't know where my cluster would be getting the additional binding from, based on the code i pasted...  (though i have to admit i'm slightly surprised that imagestreammapping is not in that list..but i also think it might be a deprecated api.  @dmage and @legionus will have to educate me)

**Comment by jim-minter** [comment]
@bparees are you running with loglevel 2?

**Comment by bparees** [comment]
@jim-minter ah, I saw the message was an Info, did not look to see the entire block was an if-loglevel2.  I do see the denial w/ level 2 now.

regardless, it's not hurting import that i can see, so will still need to hear from @legionus and @dmage

**Comment by legionus** [comment]
This is not a bug. This message occurs when imagestreamimport controller verifies credentials.

**Comment by bparees** [comment]
looked into this with @dmage and @legionus and this denial is benign/intentional.  the code is checking the permissions of the user attempting to do an imagestream import to see if they can create imagestreammappings.  It looks like the denial message is the result of any failed SAR check (which i guess makes it a good thing it's level 2).
