### ISSUE TITLE
Builds with different images never succeed and application never works

### ISSUE THREAD

**Issue by victorsferreira** [openshift/origin#16988]
Builds never succeed and application never works after creating an application in the project

##### Version
3.6

##### Steps To Reproduce
1. Choose any of the following to create an application: php, nodejs, httpd

##### Current Result
1. Build status is always pending. Sometimes it says the pod was removed before the build completed.

2. "Application is not available

The application is currently not serving requests at this endpoint. It may not have been started or is still starting."

##### Expected Result
A fully functional application

##### Additional Information
The only image that worked was nodejs + mongodb. But the mongodb was not correctly built

I tried both 5.6 and 7.0 versions of PHP. None worked.

When build stucks it never displays its logs in the web console (is there a way to see the logs anywhere else?). It says "Loading log   " but nothing is showed.

I just tried nodejs + mongodb now and it didn't work. Same error as all the previous attempts.

**Comment by bparees** [comment]
Sounds like your cluster is broken.  Are you even able to run any pods on it?  (e.g. deploy the jenkins or database template and see if those pods enter a running state).

Alternatively, oc describe the build pod and see why it is in a pending state.

**Comment by bparees** [comment]
closing due to lack of information
