### ISSUE TITLE
Jenkins (Persistent) Pod can't be assigned to a node

### ISSUE THREAD

**Issue by tienhngnguyen** [openshift/origin#16993]
I can't start the Jenkins (Persistent) Pod with 2Gi Memory allocation. Pod allocation to a node is pending and allocation to a node won't succeed.
##### Version
OpenShift v3.6.0
##### Steps To Reproduce
1.) Installing OpenShift (local) with oc cluster up
2.) Running Jenkins Persistent with 2 Gi memory allocation in a pod.

##### Current Result
Jenkins will fail to allocate a pod to a node (only node is localhost due to the installation via oc cluster up) because memory of the node is too low.
##### Expected Result
Jenkins (Persistent) Pod is allocated to a node and starts automatically.
##### Additional Information / Question
How can I increase the memory in a running node to solve this problem and how can I connect to the shell to my OpenShift server in order to edit node-config.yaml file on my server with the path the /etc/origin/node/node-config.yaml?

**Comment by sjenning** [comment]
please provide output of `oc describe nodes`

**Comment by tienhngnguyen** [comment]
It seems that my memory was not enough for docker, which might be the reason why pod allocation failed... I have increased the memory in my docker preferences and restarted the cluster with the updated memory, which might solved the problem. Is it maybe possible to increase the memory in a running node without restarting the cluster?
The output of my oc describe nodes is as follows:
Name:			localhost
Role:			
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=localhost
Annotations:		volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:			<none>
CreationTimestamp:	Sat, 21 Oct 2017 10:42:06 +0200
Phase:			
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  OutOfDisk 		False 	Mon, 23 Oct 2017 23:16:21 +0200 	Sun, 22 Oct 2017 22:27:45 +0200 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Mon, 23 Oct 2017 23:16:21 +0200 	Sun, 22 Oct 2017 22:27:45 +0200 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  DiskPressure 		False 	Mon, 23 Oct 2017 23:16:21 +0200 	Sun, 22 Oct 2017 22:27:45 +0200 	KubeletHasNoDiskPressure 	kubelet has no disk pressure
  Ready 		True 	Mon, 23 Oct 2017 23:16:21 +0200 	Mon, 23 Oct 2017 22:58:39 +0200 	KubeletReady 			kubelet is posting ready status
Addresses:		192.168.65.2,192.168.65.2,localhost
Capacity:
 cpu:		4
 memory:	6100352Ki
 pods:		40
Allocatable:
 cpu:		4
 memory:	5997952Ki
 pods:		40
System Info:
 Machine ID:			
 System UUID:			69BC2037-4931-F334-95AC-C0CCC0A84389
 Boot ID:			6f25d3c7-9564-41aa-90ce-0060181ed1a4
 Kernel Version:		4.9.49-moby
 OS Image:			CentOS Linux 7 (Core)
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://Unknown
 Kubelet Version:		v1.6.1+5115d708d7
 Kube-Proxy Version:		v1.6.1+5115d708d7
ExternalID:			localhost
Non-terminated Pods:		(4 in total)
  Namespace			Name				CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----				------------	----------	---------------	-------------
  ci				cart-3-3plz6			200m (5%)	1 (25%)		512Mi (8%)	1Gi (17%)
  ci				jenkins-1-jq1wd			0 (0%)		0 (0%)		512Mi (8%)	512Mi (8%)
  default			docker-registry-1-j3pdr		100m (2%)	0 (0%)		256Mi (4%)	0 (0%)
  default			router-1-zg2cd			100m (2%)	0 (0%)		256Mi (4%)	0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  400m (10%)	1 (25%)		1536Mi (26%)	1536Mi (26%)
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  2d		1d		13	kubelet, localhost			Normal		NodeHasSufficientDisk	Node localhost status is now: NodeHasSufficientDisk
  2d		1d		13	kubelet, localhost			Normal		NodeHasSufficientMemory	Node localhost status is now: NodeHasSufficientMemory
  2d		1d		13	kubelet, localhost			Normal		NodeHasNoDiskPressure	Node localhost status is now: NodeHasNoDiskPressure
  2d		1d		18	kubelet, localhost			Normal		NodeReady		Node localhost status is now: NodeReady
  1h		1h		1	kubelet, localhost			Normal		Starting		Starting kubelet.
  1h		1h		1	kubelet, localhost			Warning		ImageGCFailed		unable to find data for container /
  1h		1h		1	kubelet, localhost			Normal		NodeHasSufficientDisk	Node localhost status is now: NodeHasSufficientDisk
  1h		1h		1	kubelet, localhost			Normal		NodeHasSufficientMemory	Node localhost status is now: NodeHasSufficientMemory
  1h		1h		1	kubelet, localhost			Normal		NodeHasNoDiskPressure	Node localhost status is now: NodeHasNoDiskPressure
  1h		1h		1	kubelet, localhost			Warning		Rebooted		Node localhost has been rebooted, boot id: 16be43b9-bdb6-4048-9949-786989bf572c
  18m		18m		1	kubelet, localhost			Normal		Starting		Starting kubelet.
  18m		18m		1	kubelet, localhost			Warning		ImageGCFailed		unable to find data for container /
  18m		18m		1	kubelet, localhost			Normal		NodeHasSufficientDisk	Node localhost status is now: NodeHasSufficientDisk
  18m		18m		1	kubelet, localhost			Normal		NodeHasSufficientMemory	Node localhost status is now: NodeHasSufficientMemory
  18m		18m		1	kubelet, localhost			Normal		NodeHasNoDiskPressure	Node localhost status is now: NodeHasNoDiskPressure
  18m		18m		1	kubelet, localhost			Warning		Rebooted		Node localhost has been rebooted, boot id: 6f25d3c7-9564-41aa-90ce-0060181ed1a4
  18m		18m		1	kubelet, localhost			Normal		NodeNotReady		Node localhost status is now: NodeNotReady
  17m		17m		1	kubelet, localhost			Normal		NodeReady		Node localhost status is now: NodeReady

Furthermore, I have another question posted on this link: https://github.com/jboss-openshift/application-templates/issues/382

Please, could you help me in this matter? I'm failing to start the Jenkins pipeline from this demo https://blog.openshift.com/openshift-pipelines-jenkins-blue-ocean/

**Comment by sjenning** [comment]
Typically nodes have a fixed amount of RAM but if you are running a VM and you add memory to it, you can delete the node from the API server and restart the node and it will re-register with the new capacity.

I suggest asking your question on the OpenShift users mailing list to reach a wider pool of experience:
https://lists.openshift.redhat.com/openshiftmm/listinfo/users
