### ISSUE TITLE
Allow cron jobs to be linked to deployments like hook pods

### ISSUE THREAD

**Issue by djdevin** [openshift/origin#17005]
Just like deployment hook pods, it should be possible for cron job pods to link to a deployment and have the same image, environment, secrets, and volumes associated with it.

I've checked https://docs.openshift.org/latest/dev_guide/cron_jobs.html#creating-a-cronjob and also the k8s documentation but this doesn't seem possible at the moment.

As a workaround we've been rsh'ing to an existing pod, and running a command.

##### Version
OpenShift Master:
v3.6.0+c4dd4cf
Kubernetes Master:
v1.6.1+5115d708d7

**Comment by smarterclayton** [comment]
You can set triggers on the cron job to update the image spec whenever a tag changes:

```
oc set triggers cronjob/test --from-image=IMAGE_STREAM_TAG -c CONTAINER
```

That won't launch the job when the image changes, but will keep the cron job up to date.

The direction for env, secrets, and volumes will be to use `PodPreset` when that comes out of alpha.

**Comment by djdevin** [comment]
Thanks for the quick reply. `PodPreset` looks very promising.
