### ISSUE TITLE
User privilege ONLY scale up or down of pod for ANY project.

### ISSUE THREAD

**Issue by prasenforu** [openshift/origin#17018]
This not issue but looking for support.

Want to create a user in openshift who can do ONLY scale up or down of pod for ANY project.

Other than any activity that user should NOT do.

**Comment by php-coder** [comment]
@enj I accidentally came across `replicationcontrollers/scale`, `deployments/scale` and `replicasets/scale` resources in Kubernetes and wondering whether could it be helpful for this issue?

**Comment by enj** [comment]
@prasenforu there are various resources that support the scale subresource:

```
"deploymentconfigs/scale"
"deployments/scale"
"replicasets/scale"
"replicationcontrollers/scale"
```

You need to create a cluster role that grants the appropriate verbs to the resources that you desire.  Then you need to create a cluster role binding that binds that cluster role to the appropriate user.

**Comment by pweil-** [comment]
It looks like the comments here from @enj address the question.  Closing for now.

**Comment by prasenforu** [comment]
@enj thanks.

I have very limited knowledge on openshift.

Can you please help me to do with command line.

**Comment by simo5** [comment]
@prasenforu sorry this is not a help forum, subscribe to the users mailing list and ask there please.
