### ISSUE TITLE
Router: Support specifying minimum TLS version

### ISSUE THREAD

**Issue by elyscape** [openshift/origin#17013]
Thanks to #14505, the HAProxy router now allows you to specify the TLS ciphers that will be used when listening over HTTPS. It would be nice if it also provided a way to specify the minimum version of TLS to support. The current behavior is to disable SSL 3.0, but some users may also want to disable TLS 1.0 and/or 1.1, and there is no good way to do that at present. It would be nice if an environment variable could be set in the deployment config to specify the minimum version of TLS that the HAProxy router should accept.

**Comment by briantward** [comment]
This was added in OCP 4 on the new router project that was split out:
https://github.com/openshift/router/pull/30
https://bugzilla.redhat.com/show_bug.cgi?id=1746467

PR #24400 submitted for backporting the change to openshift:release-3.11
RFE on 3.11: https://issues.redhat.com/browse/RFE-167

**Comment by ehashman** [comment]
All PRs are merged. This is now supported on both 3.11 and 4.3, can this be closed?
