### ISSUE TITLE
Latest oc cluster up with service-catalog fails on ubuntu 14.04

### ISSUE THREAD

**Issue by rthallisey** [openshift/origin#17017]
```oc cluster up --image=docker.io/openshift/origin --version=latest  --service-catalog=true``` fails on ubuntu 14.04.  This first appeared in a travis job and I've also been able to produce this locally.  From what I've been able to tell, the catalog apiserver is expecting a secret to be available to it when it starts and it's not there. So no containers are ever launched besides the origin container. 

It's worth noting that upgrading ubuntu to 16.04 fixes the issue, but travis only supports 14.04.  Also, running oc cluster up without ```--service-catalog=true``` works fine.  

```I1019 21:18:15.065705   20617 reconciler.go:257] operationExecutor.MountVolume started for volume "apiserver-ssl" (UniqueName: "kubernetes.io/secret/046ea5f9-b513-11e7-959b-42010a14003b-apiserver-ssl") pod "apiserver-1750219404-5cx7r" (UID: "046ea5f9-b513-11e7-959b-42010a14003b") 
I1019 21:18:15.065813   20617 secret.go:186] Setting up volume apiserver-ssl for pod 046ea5f9-b513-11e7-959b-42010a14003b at /var/lib/origin/openshift.local.volumes/pods/046ea5f9-b513-11e7-959b-42010a14003b/volumes/kubernetes.io~secret/apiserver-ssl
I1019 21:18:15.087211   20617 nsenter_mount.go:234] Failed findmnt command for path /var/lib/origin/openshift.local.volumes/pods/046ea5f9-b513-11e7-959b-42010a14003b/volumes/kubernetes.io~secret/apiserver-ssl: exit status 1
I1019 21:18:15.087392   20617 empty_dir.go:257] pod 046ea5f9-b513-11e7-959b-42010a14003b: mounting tmpfs for volume wrapped_apiserver-ssl
E1019 21:18:15.109097   20617 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/secret/046ea5f9-b513-11e7-959b-42010a14003b-apiserver-ssl\" (\"046ea5f9-b513-11e7-959b-42010a14003b\")" failed. No retries permitted until 2017-10-19 21:18:15.608974546 +0000 UTC (durationBeforeRetry 500ms). Error: MountVolume.SetUp failed for volume "apiserver-ssl" (UniqueName: "kubernetes.io/secret/046ea5f9-b513-11e7-959b-42010a14003b-apiserver-ssl") pod "apiserver-1750219404-5cx7r" (UID: "046ea5f9-b513-11e7-959b-42010a14003b") : exit status 1
```

##### Version
oc v3.7.0-alpha.1+50389c0-1262
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. Start an Ubuntu 14.04 vm
2. Run oc cluster up with the latest images and with the service catalog: ```oc cluster up --image=docker.io/openshift/origin --version=latest  --service-catalog=true```

##### Current Result
Only the origin pod launches.

##### Expected Result
Full OpenShift cluster with the service catalog running.

##### Additional Information
Full log: https://api.travis-ci.org/jobs/290189456/log.txt?deansi=true

cc @jmontleon

**Comment by rthallisey** [comment]
@jpeeler @pmorie Have folks seen this issue? I saw that the upstream catalog travis jobs are running fine. Maybe this is an issue with oc cluster up?

**Comment by jpeeler** [comment]
@rthallisey - I'm guessing here, but it looks like Ubuntu 14.04 doesn't include nsenter in the util-linux package: https://packages.ubuntu.com/trusty/amd64/util-linux/filelist, where as 16.04 does. Perhaps Travis is using an updated util-linux package or source compile for nsenter?

**Comment by rthallisey** [comment]
Did a little more digging and found where the issue is occurring. ```nsenter --mount=/rootfs/proc/1/ns/mnt -- /bin/systemd-run --description=Kubernetes transient mount for /var/lib/origin/openshift.local.volumes/pod\s/dc5d8f57-b83b-11e7-9532-525400983006/volumes/kubernetes.io~secret/service-catalog-apiserver-token-k1b1l --scope -- /bin/mount -t tmpfs tmpfs /var/lib/origin/openshift.local.volumes/pods/dc5d8f57-b83b-11e7-953\2-525400983006/volumes/kubernetes.io~secret/service-catalog-apiserver-token-k1b1l```

[root@rhallisey-KVM origin]# nsenter --mount=/rootfs/proc/1/ns/mnt -- ls /usr/bin | grep systemd
deb-systemd-helper
deb-systemd-invoke

**Comment by rthallisey** [comment]
@jpeeler it runs nsenter inside the origin container where it does exist

**Comment by rthallisey** [comment]
I think I found the issue. I outlined it in the go playground [here](https://play.golang.org/p/XSe4lcVVrR).  Relevant Kubernetes code is [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/nsenter/nsenter.go#L120-L124)

The second return value from a map is whether the key exists.  But, the key will always exist because the map was initialized [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/nsenter/nsenter.go#L70-L82).

I'm going to post an issue & PR upstream and link it back.

**Comment by pmorie** [comment]
Sorry @rthallisey, but ubuntu is not a distribution that we have bandwidth to support.  On the bright/terrible side, the issue here will affect all pods.

I'm happy to keep this open since you intend to make an upstream PR.

**Comment by pweil-** [comment]
Let's track this via an upstream issue if that's where the fix is going since it's not something we intend on supporting.

**Comment by rthallisey** [comment]
@pmorie no problem, I'll fix the issue. I'm just figuring out my upstream dev environment so I can properly test the patch.

**Comment by tnozicka** [comment]
@rthallisey did you ever get to file that upstream issue? I think I am hitting this now on Travis with nsenter missing

**Comment by joelsmith** [comment]
FYI to anyone tracking this issue, I have opened https://github.com/kubernetes/kubernetes/pull/59770
