### ISSUE TITLE
Nodes should have a unique user agent

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#17022]
Right now they are the generic openshift client agent, but they should be openshift/node (or similar).  It's too annoying to sort out what they do otherwise.

**Comment by mfojtik** [comment]
AFAIK, the agent should include the the command name by default:

```go
// buildUserAgent builds a User-Agent string from given args.
func buildUserAgent(command, version, os, arch, commit string) string {
  return fmt.Sprintf(
    "%s/%s (%s/%s) kubernetes/%s", command, version, os, arch, commit)
}

// DefaultKubernetesUserAgent returns a User-Agent string built from static global vars.
func DefaultKubernetesUserAgent() string {
  return buildUserAgent(
    adjustCommand(os.Args[0]),
    adjustVersion(version.Get().GitVersion),
    gruntime.GOOS,
    gruntime.GOARCH,
    adjustCommit(version.Get().GitCommit))
}
```

In OpenShift case I guess this will be always "openshift". I can add `CustomKubernetesUserAgent(string)` but it will be upstream change and we will have to plumb it somehow down to `KubeletServer` options?

**Comment by mfojtik** [comment]
@smarterclayton maybe something like this? https://github.com/mfojtik/origin/commit/fb257f0824e74b9e950c4d115417a8ec936ae45a
