### ISSUE TITLE
`osc delete type name` makes API GET call before deleting

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#1702]
This breaks the assumption that you can have permission to delete things you cannot read.

This is very useful for things like access tokens.

Visit $MASTER/oauth/token/request:

> How do I delete this token when I'm done?
> osc delete oauthaccesstoken NmJkZGYxYWEtYzZjYS00OWQ0LThiOWQtNmJiY2NkYTlhNWFh

**Comment by kargakis** [comment]
Upstream issue?

**Comment by liggitt** [comment]
Yes, opened at https://github.com/GoogleCloudPlatform/kubernetes/issues/6859
