### ISSUE TITLE
dockerregistry -prune flag not available

### ISSUE THREAD

**Issue by adbaldi** [openshift/origin#17038]
When trying to follow the registry hard prune documentation I run into a few issues.

https://docs.openshift.org/1.5/admin_guide/pruning_resources.html#hard-pruning-registry

The first issue is that my container has dockerregistry located at / instead of /usr/bin/ in the documentation.  The second issue is that the dockerregistry binary does not seem to know about the -prune flag.

I'm guessing the documentation is actually meant for the 3.6 version.  Is there a way to replicate the functionality in 1.5?

##### Version
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server 
openshift v1.5.1
kubernetes v1.5.2+43a9be4

oc describe dc docker-registry | grep Image
    Image:	openshift/origin-docker-registry:v1.5.1

##### Steps To Reproduce
1. follow doc for hard pruning linked above

##### Current Result
$ /dockerregistry --prune=check
flag provided but not defined: -prune
Usage of ./dockerregistry:
  -alsologtostderr
    	log to standard error as well as files
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging

##### Expected Result
orphaned docker images pruned

**Comment by dmage** [comment]
The documentation is meant for OpenShift Container Platform 3.5, in origin it will appear in 3.7. We will fix the docs, sorry for misleading.

**Comment by adbaldi** [comment]
Thanks for the info.

**Comment by miminar** [comment]
Addressed by openshift/openshift-docs#6077

The hard pruning is present in origin release 3.6 so the section needs to be removed just from the 1.4 and 1.5 releases.

**Comment by miminar** [comment]
The hard pruning section will be removed on next doc rebuild. Closing this now.
