### ISSUE TITLE
docker registry keep showing manifest unknown error for image pull after somedays of push image

### ISSUE THREAD

**Issue by aaryabhatt** [openshift/origin#17031]
I am facing a very strange behaviour of docker registry. When I pushed a image it works fine for some days and after somedays it start giving manifest unknown error while pulling image to any node, which is due to self sign certificate. when I pushed the image again to docker registry then it start working. This issue is not to a particular image, I am facing this issue to multiple images which I am using.

##### Version
Server https://qamasternode1.groupzeal.com:8443
openshift v1.5.1
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. Pushed to multiple images to docker registry
2. Use the image to deploy pods 
3. After someday try to use the image again.

##### Current Result
image pulling to node start giving manifest unknown error which is due to self sign certificate of register. please find below some of lines of docker registry logs while pulling the image.
`time="2017-10-25T11:40:29.560401847Z" level=debug msg="(*blobDescriptorService).Stat: could not stat layer link sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3 in repository default/nginx-admin-proxy: unknown blob" go.version=go1.7.5 http.request.host="172.30.16.81:5000" http.request.id=f1ac7e85-30cb-48bb-a189-fcbbba582694 http.request.method=GET http.request.remoteaddr="10.131.0.1:41488" http.request.uri="/v2/default/nginx-admin-proxy/manifests/sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.26.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=b6257207-4462-4d16-8ed4-e28c2d8a14a3 openshift.auth.user="system:serviceaccount:bayboon-common-data:default" openshift.logger=registry vars.name="default/nginx-admin-proxy" vars.reference="sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" 
time="2017-10-25T11:40:29.560500027Z" level=debug msg="filesystem.Stat(\"/docker/registry/v2/blobs/sha256/3d/3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3/data\")" go.version=go1.7.5 http.request.host="172.30.16.81:5000" http.request.id=f1ac7e85-30cb-48bb-a189-fcbbba582694 http.request.method=GET http.request.remoteaddr="10.131.0.1:41488" http.request.uri="/v2/default/nginx-admin-proxy/manifests/sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.26.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=b6257207-4462-4d16-8ed4-e28c2d8a14a3 openshift.auth.user="system:serviceaccount:bayboon-common-data:default" openshift.logger=registry trace.duration=21.749µs trace.file="/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/openshift/origin/vendor/github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=6b21ce62-0ec9-4b07-a1a0-dbb987c8a964 trace.line=137 vars.name="default/nginx-admin-proxy" vars.reference="sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" 
time="2017-10-25T11:40:29.560563132Z" level=debug msg="(*pullthroughManifestService).remoteGet: starting with dgst=sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" go.version=go1.7.5 http.request.host="172.30.16.81:5000" http.request.id=f1ac7e85-30cb-48bb-a189-fcbbba582694 http.request.method=GET http.request.remoteaddr="10.131.0.1:41488" http.request.uri="/v2/default/nginx-admin-proxy/manifests/sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.26.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=b6257207-4462-4d16-8ed4-e28c2d8a14a3 openshift.auth.user="system:serviceaccount:bayboon-common-data:default" openshift.logger=registry vars.name="default/nginx-admin-proxy" vars.reference="sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" 
time="2017-10-25T11:40:29.560596714Z" level=debug msg="(*cachedImageStreamGetter).getImageStream: returning cached copy" go.version=go1.7.5 instance.id=b6257207-4462-4d16-8ed4-e28c2d8a14a3 openshift.logger=registry 
time="2017-10-25T11:40:29.560655693Z" level=info msg="(*repository).getImage: returning cached copy of sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" go.version=go1.7.5 instance.id=b6257207-4462-4d16-8ed4-e28c2d8a14a3 openshift.logger=registry 
time="2017-10-25T11:40:29.582463099Z" level=debug msg="(*cachedImageStreamGetter).getImageStream: returning cached copy" go.version=go1.7.5 instance.id=b6257207-4462-4d16-8ed4-e28c2d8a14a3 openshift.logger=registry 
time="2017-10-25T11:40:29.582541602Z" level=debug msg="(*cachedImageStreamGetter).getImageStream: returning cached copy" go.version=go1.7.5 instance.id=b6257207-4462-4d16-8ed4-e28c2d8a14a3 openshift.logger=registry 
I1025 11:40:29.589047       1 logs.go:41] http: TLS handshake error from 10.128.2.1:34170: EOF
time="2017-10-25T11:40:29.58904177Z" level=error msg="error getting remote repository for image \"172.30.16.81:5000/default/nginx-admin-proxy:latest\": Get https://172.30.16.81:5000/v2/: x509: certificate signed by unknown authority" go.version=go1.7.5 http.request.host="172.30.16.81:5000" http.request.id=f1ac7e85-30cb-48bb-a189-fcbbba582694 http.request.method=GET http.request.remoteaddr="10.131.0.1:41488" http.request.uri="/v2/default/nginx-admin-proxy/manifests/sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.26.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=b6257207-4462-4d16-8ed4-e28c2d8a14a3 openshift.auth.user="system:serviceaccount:bayboon-common-data:default" openshift.logger=registry vars.name="default/nginx-admin-proxy" vars.reference="sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" 
time="2017-10-25T11:40:29.589157868Z" level=error msg="response completed with error" err.code="manifest unknown" err.detail="Get https://172.30.16.81:5000/v2/: x509: certificate signed by unknown authority" err.message="manifest unknown" go.version=go1.7.5 http.request.host="172.30.16.81:5000" http.request.id=f1ac7e85-30cb-48bb-a189-fcbbba582694 http.request.method=GET http.request.remoteaddr="10.131.0.1:41488" http.request.uri="/v2/default/nginx-admin-proxy/manifests/sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.26.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=89.215108ms http.response.status=404 http.response.written=139 instance.id=b6257207-4462-4d16-8ed4-e28c2d8a14a3 openshift.auth.user="system:serviceaccount:bayboon-common-data:default" openshift.logger=registry vars.name="default/nginx-admin-proxy" vars.reference="sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3" 
10.131.0.1 - - [25/Oct/2017:11:40:29 +0000] "GET /v2/default/nginx-admin-proxy/manifests/sha256:3d682e445326bd456d83f080b3a5844965899b5cfb31fae57f130ffeb1510bd3 HTTP/1.1" 404 139 "" "docker/1.12.6 go/go1.7.4 kernel/3.10.0-514.26.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"
`

##### Expected Result
It should be able to pull image.

**Comment by dmage** [comment]
Which storage is used by the registry? When you start it with `oc cluster up` it uses a temporary directory (emptyDir) which is erased upon each restart of the registry:
```
$ oc -n default get dc/docker-registry -o yaml
...
      volumes:
      - emptyDir: {}
        name: registry-storage
...
```

It may be also configured by the environment variable REGISTRY_STORAGE or by a config file.

**Comment by aaryabhatt** [comment]
thanks @dmage, great help, I did not check that option, you are right it restarted, we can close it.

**Comment by vglaiju** [comment]
Thanks a lot dmage we were facing image not found error and trying RBAC, tokens all attempts causing same error.
Now we realise the internal docker reigistry has track of only those images that it has visibility while as long as it is running. Old images/tags which were tracked by old registry pods cannot be pulled then..because they are not persisted..?

**Comment by dmage** [comment]
@vglaiju yes, you'll have imagestreams, but you'll loose layers and manifests (basically the things that you download when you say `docker pull`). As a result, you won't be able to pull these images from the integrated registry anymore.
