### ISSUE TITLE
after ./osc login no other auth works

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#1704]
I ran ./osc login with the combination admin/password but when I think try to pass flag to ./osc it barfs.

spousty@localhost openshift-client$ ./openshift ex new-project testproject --username='anyuser' --password='anypassword'
F0411 22:41:27.025906   29605 new_project.go:44] Error getting client: more than one authentication method found for  admin.  Found [token basicAuth], only one is allowed

**Comment by brenton** [comment]
The only authentication mechanisms that are valid for the openshift api are token and client certificate.  Other authentication methods are used only for obtaining tokens.  I'm guessing we shouldn't allow `--usename` and `--password` on the rest of the cli.  @deads2k, @liggitt, either of you know who this should be assigned to?

**Comment by deads2k** [comment]
I'll take a stab at it.

**Comment by thesteve0** [comment]
But then how would we handle someone who has two or three different
accounts? Do you have to run through osc login each time you want to switch
accounts?

**Comment by deads2k** [comment]
There are a couple ways to organize it, but I think our go-to would be to use `osc project`.  `osc project` actually takes a namespace or a **context** as its argument.  The context includes, server, user identity, and namespace name.  That would allow a user to switch back and forth between projects located in different clusters with different identities.
