### ISSUE TITLE
Container creation fails because of "Failed create pod sandbox"

### ISSUE THREAD

**Issue by Ocimum-basilicum** [openshift/origin#17047]
Pods are not getting created anymore

##### Version
oc v3.6.173.0.7
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://api.starter-ca-central-1.openshift.com:443
openshift v3.7.0-0.143.7
kubernetes v1.7.0+80709908fd

##### Steps To Reproduce
1. create a application (e.g. resid (persistent) from catalog)
2. check pod/container creation 
3. wait for timeouts

##### Current Result
Warn messages on pod: 
`1:33:46 PM | Normal | Sandbox changed | Pod sandbox changed, it will be killed and re-created.
2 times in the last 5 minutes
-- | -- | -- | --
1:33:42 PM | Warning | Failed create pod sand box | Failed create pod sandbox.
2 times in the last 5 minutes`
--> pod is not created

the only real error I could grab was : 
`Failed kill pod | error killing pod: failed to "KillPodSandbox" for "c4c2ec61-ba29-11e7-8b2c-02d8407159d1" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"redis-1-deploy_instantsoundbot\" network: CNI request failed with status 400: 'Failed to execute iptables-restore: exit status 4 (Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n)\n'"`

##### Expected Result
 pod should start up as the used to do...

##### Additional Information
Couldn't get oc adm diagnostics working atm
I guess it could have to do with the introduction of https://github.com/openshift/origin/pull/15880

**Comment by tumido** [comment]
I'm facing the same in the `starter-us-east-1.openshift.com` environment. It's been unstable for couple of days already...

**Comment by sjenning** [comment]
This is a known issue that has a fix and it being rolled out to the starter clusters presently.

**Comment by skjolber** [comment]
I think 'm facing the same issue at starter-ca-central-1.openshift.com:

10:04:10 AM | Normal | Deadline exceeded | Pod was active on the node longer than the specified deadline
-- | -- | -- | --
10:00:03 AM | Normal | Sandbox changed | Pod sandbox changed, it will be killed and re-created.14 times in the last 58 minutes
-- | -- | -- | --
9:59:40 AM | Warning | Failed create pod sand box | Failed create pod sandbox.14 times in the last 58 minutes

When will the fix finish rolling out?

**Comment by 14yannick** [comment]
Facing same issue not possible to rollout anything on starter-ca-central-1.openshift.com. Hope will be fixed soon.

**Comment by osamahassan245** [comment]
i got same issue , i tried to create application using tomcat 8 , and try to build source code that exist in this path
[](https://github.com/osamahassan245/samplepp)

i got build error , when tried to check the log , got this log 

> container "sti-build" in pod   is not available

**Comment by Artod** [comment]
Same problem on starter-ca-central-1.openshift.com
>  error streaming logs from build pod: sii-test/app-5-build container: , container "sti-build" in pod "app-5-build" is not available

**Comment by osamahassan245** [comment]
issue solved , i tried to use " Red Hat JBoss Web Server 3.1 Tomcat 8 1.0 " , it's working fine now

**Comment by edevyatkin** [comment]
The issue is still actual on starter-us-east-1.openshift.com

**Comment by izderadicka** [comment]
Still problem on ca-central

**Comment by brianHollingsworth** [comment]
Glad I'm not the only one seeing this issue. It's been occurring for me on console.starter-us-west-1.openshift.com since last weekend (11/4).

**Comment by sothawo** [comment]
still seeing this on starter-ca-central-1.openshift.com

**Comment by mchangxe** [comment]
Also seeing this running a local cluster using local-up-cluster.sh

**Comment by mavajsunco** [comment]
I have same issue . error streaming logs from build pod: mavajsunco-website/mavajsunco-msc-6-build container: , container "sti-build" in pod "mavajsunco-msc-6-build" is not available

**Comment by axl8713** [comment]
Same issue deploying rhscl/mysql-57-rhel7 on starter-us-east-1.

**Comment by sjenning** [comment]
@dcbw this is the all too familiar iptables-restore issue.  You are closer to this that I am and hopefully can provide better feedback about the progress.

**Comment by warmchang** [comment]
👍

**Comment by nevadascout** [comment]
Still having this problem on `starter-us-west-2`.

I've got 7 failed deployments in a row for this error message.

**Comment by skoorupa** [comment]
^same

**Comment by DanyC97** [comment]
@dcbw @sjenning any input as to where the issue might be?

**Comment by jherson** [comment]
Seeing this the last couple of days on pro-us-east-1 as well

**Comment by shreyasgombi** [comment]
Same here!!! Observing on pro-us-east-1.

**Comment by saurabhdevops** [comment]
Hey Folks! Any update on this one, do you have a fix already on openshift or openshift ansible repos that I can pick up. Is there a temporary workaround for this issue? We are facing the same issue with our openshift cluster on AWS.

Version
OpenShift Master:
v3.7.0+7ed6862
Kubernetes Master:
v1.7.6+a08f5eeb62

**Comment by saurabhdevops** [comment]
@pweil- , @jupierce  are you still looking into this issue. Is there any progress or workaround available?

**Comment by pweil-** [comment]
@dcbw  @knobunc ping

**Comment by agajdosi** [comment]
I am facing similar issue using OCP v3.9.30 with CDK. In my case I have Che deployed on OpenShift and when I start a new workspace, its node crashes on `sandbox changed`:
```
11:52:32 AM 	Normal 	Killing  	Killing container with id docker://container:Need to kill Pod
11:52:30 AM 	Normal 	Sandbox Changed  	Pod sandbox changed, it will be killed and re-created.
11:52:28 AM 	Normal 	Started  	Started container
11:52:28 AM 	Normal 	Created  	Created container

``` 
Is there any update on this issue @dcbw?

**Comment by 14yannick** [comment]
I used Openshift for more more than 5 years. Spend a lot time making my app running on v2 again. At the end traffic was just not rooted anymore. Mooved to heroku took me 2 hours to migrate all my data(db) and make the necessary Source Code changes. Since then no more Problems. Sorry Openshift

**Comment by alexbuzzbee** [comment]
Seeing this (or something similar) currently on OpenShift Online starter-us-west-1. Unable to build or deploy because of it. Status page says all green.

**Comment by jhaohai** [comment]
We still see this issue on okd 3.7.1

**Comment by matthewmcneilly** [comment]
I am seeing this issue or something simular when deploying 3Scale API Management Platform on Openshift in particular system-sidekiq. 

``    Failed create pod sandboxc: rpc error: code = Unknown desc = failed to set up sandbox container "2cc1e1d064082f2a2b8cd7a10efb7d135a8a150e7d95fb7b939d6368e1717309" network for pod "system-sidekiq-6-deploy-    	debug": NetworkPlugin cni failed to set up pod "system-sidekiq-6-deploy-debug_mmcneilly-3scale-onprem" network: CNI request failed with status 400: 'pods "system-sidekiq-6-deploy-debug" not found '
