### ISSUE TITLE
Wrong order when importing image tags

### ISSUE THREAD

**Issue by jtudelag** [openshift/origin#17055]
When importing all the images of a container image (with the command oc import-image)  they are imported in the wrong order.

##### Version

oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.77:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce

Run the following command, (having MaxImagesBulkImportedPerRepository:20)
`oc import-image my-openshift3/ose-pod --from=registry.access.redhat.com/openshift3/ose-pod --confirm --all`

##### Current Result

latest
v3.6
v3.5
v3.4
v3.3
v3.2
v3.1
v3.0.0.0
v3.0.0.1
v3.0.1.0
v3.0.2.0
etc..

##### Expected Result
latest
v3.6
v3.5
v3.4
v3.3
v3.2
v3.1
v3.6.0.21
v3.6.173.0.5-4
v3.6.173.0.5-2
etc..

##### Additional Information
Code here: 
https://github.com/openshift/origin/blob/master/pkg/image/apis/image/helper.go#L861

Comment about the logic when ordering the tags, point 3 is not being honoured.

// PrioritizeTags orders a set of image tags with a few conventions:
//
// 1. the "latest" tag, if present, should be first
// 2. any tags that represent a semantic minor version ("5.1", "v5.1", "v5.1-rc1") should be next, in descending order
// 3. any tags that represent a full semantic version ("5.1.3-other", "v5.1.3-other") should be next, in descending order
// 4. any remaining tags should be sorted in lexicographic order

**Comment by bparees** [comment]
this behavior is deprecated anyway.  If you want to control what tags are imported, you must define the tags in the spec explicitly, e.g.: https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L34-L47

closing as won't fix.

**Comment by juanluisvaladas** [comment]
Since the documentation doesn't say it's deprecated [1], would you merge it if I fix it myself and write the proper test?

1- https://docs.openshift.com/container-platform/3.6/install_config/master_node_configuration.html#master-config-image-config

**Comment by jtudelag** [comment]
@bparees @juanluisvaladas In that case, shouldn't we also fix this part of the docs??
[https://docs.openshift.com/container-platform/3.6/dev_guide/managing_images.html#importing-tag-and-image-metadata](https://docs.openshift.com/container-platform/3.6/dev_guide/managing_images.html#importing-tag-and-image-metadata)

**Comment by bparees** [comment]
@juanluisvaladas @jtudelag what's deprecated (as of 3.7) is using the spec.dockerImageRepository field on an imagestream, which is what you have to define in order to get bulk importing behavior.

So "is deprecated" is perhaps too strong a statement, but "is about to be deprecated in the first release we'd consider fixing this" is more accurate.

https://github.com/openshift/origin/blob/master/pkg/image/apis/image/v1/types.go#L183

In any case at this point changing the behavior is more likely to cause existing users problems (since it will suddenly change what is imported for them).
