### ISSUE TITLE
mailing list link unaccessible

### ISSUE THREAD

**Issue by lbrigman124** [openshift/origin#17065]
Clicking on the link on the github README.md that is presented with the repository lead to this error.
------------------
This site can’t be reached

lists.openshift.redhat.com refused to connect.

**Comment by xiaods** [comment]
Maybe:
https://wiki.centos.org/SpecialInterestGroup/PaaS/OpenShift-Origin-Support

**Comment by lbrigman124** [comment]
Sending mail to the list when you are not subscribed gets rejected.
users@lists.openshift.redhat.com
