### ISSUE TITLE
Misleading information returned by oc policy who-can for cluster-level resources

### ISSUE THREAD

**Issue by luksa** [openshift/origin#17067]
Imagine a user making a mistake and adding a cluster-level role with oc policy add-role-to-user instead of add-cluster-role-to-user. For example:
```
$ oc policy add-role-to-user self-provisioner system:serviceaccount:myproject:my-service-account
role "self-provisioner" added: "system:serviceaccount:myproject:my-service-account"
```

If anyone now uses `oc policy who-can` to check if the service account can create project requests, the information returned makes it appear as though it can create them, but that's not the case.
```
$ oc policy who-can create projectrequests
Namespace: myproject
Verb:      create
Resource:  projectrequests

Users:  system:admin
        system:serviceaccount:management-infra:management-admin
        system:serviceaccount:myproject:my-service-account                     <-----

Groups: system:authenticated:oauth
        system:cluster-admins
        system:masters
```

The output of who-can is exactly the same as when the cluster role is added properly. Basically, the root cause is in the `oc policy add-role-to-user` command not returning an error when adding a a cluster-role as a (non-cluster-level) role. 

##### Version
```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxx:8443
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. `oc policy add-role-to-user self-provisioner system:serviceaccount:myproject:my-service-account`
2. `oc policy who-can create projectrequests`

##### Current Result
```
Users:  system:admin
        system:serviceaccount:management-infra:management-admin
        system:serviceaccount:myproject:my-service-account                     <-----
```
##### Expected Result
my-service-account shouldn't be shown as being capable of creating project requests, because that's a cluster role.

**Comment by simo5** [comment]
Does creating a projectrequest with system:serviceaccount:myproject:my-service-account actually fail ?

**Comment by luksa** [comment]
Yes, it fails:
```
$ oc policy add-role-to-user self-provisioner system:serviceaccount:mluksa-test:my-service-account
role "self-provisioner" added: "system:serviceaccount:mluksa-test:my-service-account"
$ oc policy who-can create projectrequests
Namespace: mluksa-test
Verb:      create
Resource:  projectrequests

Users:  system:admin
        system:serviceaccount:management-infra:management-admin
        system:serviceaccount:mluksa-test:my-service-account

Groups: system:authenticated:oauth
        system:cluster-admins
        system:masters
$ oc --token $(cat token) whoami
system:serviceaccount:mluksa-test:my-service-account
$ oc --token $(cat token) new-project mluksa-test2
Error from server (Forbidden): You may not request a new project via this API.
```

And just to perform a double-check: if I then add the cluster role properly, it works:
```
$ oc adm policy add-cluster-role-to-user self-provisioner system:serviceaccount:mluksa-test:my-service-account
cluster role "self-provisioner" added: "system:serviceaccount:mluksa-test:my-service-account"
$ oc --token $(cat token) new-project mluksa-test2
Now using project "mluksa-test2" on server...
```

**Comment by adelton** [comment]
@luksa, is this a regression against older version?

**Comment by enj** [comment]
The correct way to run the `who-can` command for a cluster scoped resource is:

```
oc policy who-can create projectrequests --all-namespaces
```

We could use discovery information to warn when a role binding is being created for a cluster scoped resource.

**Comment by enj** [comment]
@fabianofranz assign this kind of stuff to @simo5 in the future.

/unassign @deads2k @liggitt

**Comment by luksa** [comment]
@adelton I don't know if it's a regression. Most likely not.

@enj If `--all-namespaces` is really required for cluster-level resources, then `who-can` shouldn't work when invoked for a cluster-level resource and without --all-namespaces (it currently works and shows the information correctly). Also, as a regular user, I'm not even allowed to run `who-can --all-namespaces`:
```
$ oc policy who-can create projectrequests --all-namespaces
Error from server (Forbidden): User "luksa" cannot create resourceaccessreviews at the cluster scope
```
But, as the same regular user, I can run it without `--all-namespaces` and get back the information I'm looking for:
```
$ oc policy who-can create projectrequests
Namespace: mluksa-test
Verb:      create
Resource:  projectrequests

Users:  system:admin
        system:serviceaccount:management-infra:management-admin
        system:serviceaccount:mluksa-test:my-service-account

Groups: system:authenticated:oauth
        system:cluster-admins
        system:masters
```

**Comment by enj** [comment]
> if `--all-namespaces` is really required for cluster-level resources, then `who-can` shouldn't work when invoked for a cluster-level resource and without `--all-namespaces`

`who-can`, just like all of RBAC, has no strict concept of resources or their scope - its just a string.  The best the `who-can` command  can do is warn the user if it thinks the command does not line up with discovery information.  The behavior of `who-can` will not change.  You asked it an incorrect question, and it answered that question.

> Also, as a regular user, I'm not even allowed to run who-can --all-namespaces

Normal users cannot create cluster role bindings either, so this is expected.  Normal users are not allowed to ask cluster wide questions.

> But, as the same regular user, I can run it without `--all-namespaces` and get back the information I'm looking for:

Except that is not the information you are looking for.  You are asking about `verb:create` `resource:projectrequests` `namespace:mluksa-test` when you really want `verb:create` `resource:projectrequests` `namespace:` (no namespace).  If you ask the wrong question, the answer you get back is irrelevant.

**Comment by adelton** [comment]
Is this merely wrong usage, or do we expect anything to be done about OpenShift's behaviour?

**Comment by liggitt** [comment]
Yes, it is incorrect usage

**Comment by adelton** [comment]
So is this OK to close this issue?

**Comment by enj** [comment]
Tracking via https://trello.com/c/pFw2YC9I
