### ISSUE TITLE
Extended cl.go tests delete/reuse namespace "ifexists" [RFE]

### ISSUE THREAD

**Issue by jmencak** [openshift/origin#17070]
##### Version
$ git describe
v3.7.0-alpha.1-494-g7bb08c04da

##### Steps To Reproduce
1. extended.test --ginkgo.focus="Load cluster" --viper-config=config/golang-cl-pause

##### Expected Result
Namespace deleted/reused before a test run.

##### Additional Information
Please add delete/reuse existing namespace functionality as supported by the old Python cluster-loader.

Example config:

- golang-cl-pause.yaml

      # e2e specific vars
      provider: local
      # delete namespace after exec
      deletenamespace: true
      # Cluster loader specific part
      ClusterLoader:
        projects:
          - num: 1
            basename: clusterproject
            tuning: default
            ifexists: [reuse|delete]
            pods:
              - num: 2
                image: gcr.io/google_containers/pause-amd64:3.0
                basename: pausepods
                file: pod-pause.json
        tuningsets: 
          - name: default
            pods:
              stepping:
                stepsize: 5
                pause: 3      # seconds
                timeout: 300  # seconds
              ratelimit:
                delay: 100    # milliseconds
            templates:
              stepping: 
                stepsize: 2
                pause: 2      # seconds
                timeout: 120  # seconds
              ratelimit: 
                delay: 200    # milliseconds

@sjug /cc @jeremyeder

**Comment by sjug** [comment]
Functionality now exists. As of https://github.com/openshift/origin/pull/19388.
