### ISSUE TITLE
Extended cl.go tests doesn't delete a namespace after a test run.

### ISSUE THREAD

**Issue by jmencak** [openshift/origin#17071]
The "deletenamespace: true" doesn't work as expected after an extended cl.go test run.

##### Version
$ git describe
v3.7.0-alpha.1-494-g7bb08c04da

##### Steps To Reproduce
1. extended.test --ginkgo.focus="Load cluster" --viper-config=config/golang-cl-pause

##### Current Result
Namespace "clusterproject0" is not deleted after a test run.

##### Expected Result
Namespace "clusterproject0" deleted after a test run if "deletenamespace: true".

##### Additional Information
- golang-cl-pause.xml

      # e2e specific vars
      provider: local
      # delete namespace after exec
      deletenamespace: true
      # Cluster loader specific part
      ClusterLoader:
        projects:
          - num: 1
            basename: clusterproject
            tuning: default
            ifexists: delete
            pods:
              - num: 2
                image: gcr.io/google_containers/pause-amd64:3.0
                basename: pausepods
                file: pod-pause.json
        tuningsets: 
          - name: default
            pods:
              stepping:
                stepsize: 5
                pause: 3      # seconds
                timeout: 300  # seconds
              ratelimit:
                delay: 100    # milliseconds
            templates:
              stepping: 
                stepsize: 2
                pause: 2      # seconds
                timeout: 120  # seconds
              ratelimit: 
                delay: 200    # milliseconds

@sjug /cc @jeremyeder

**Comment by sjug** [comment]
Hey Jiri,

The parameters not nested inside
```
ClusterLoader:

```

Are e2e related parameters.

In order to delete namespaces created by Cluster Loader, just add 

```
ClusterLoader:
  Cleanup: true
```
