### ISSUE TITLE
Service with containerPort set stops working after pod restart

### ISSUE THREAD

**Issue by jpechane** [openshift/origin#1707]
When there is a service whose configuration does container containerPort then the nat table contains a record like
```
DNAT       tcp  --  anywhere             172.30.17.85         /* openshift-mysql-db */ tcp dpt:sgi-arrayd to:10.34.75.127:52784
```

If I locate the container that represents the pod behind the service and execute ```docker kill``` then the record in question is removed from the NAT and the service stops working.

If I modify the same config file to not contain containerPort then the record is updated and service operates as expected.

**Comment by mrunalp** [comment]
@jpechane Could you give more details? I created a redis pod with a redis container specifying the containerPort. I then created a redis-service and a DNAT rule was created as expected. Next, I docker kill'ed the redis container, but the service DNAT rule was still present.

**Comment by mrunalp** [comment]
I think we can close this one as we are unable to reproduce the issue with latest origin. @danmcp ping.

**Comment by jpechane** [comment]
I agree with the previous comment - it is quite an old issue and it seems it is not longer a problem.
