### ISSUE TITLE
test flake template instances not found as internalservererror

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#17085]
```
/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:377
Expected error:
    <*client.ServerError | 0xc421b9e280>: {
        StatusCode: 500,
        Description: "templateinstances.template.openshift.io \"e59793bb-1338-4cf5-9851-b95ac273e735\" not found",
    }
    Internal Server Error: templateinstances.template.openshift.io "e59793bb-1338-4cf5-9851-b95ac273e735" not found
not to have occurred
/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:172
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/5924/test_pull_request_openshift_ansible_extended_conformance_install_update/3031/

**Comment by smarterclayton** [comment]
@openshift/sig-developer-experience

**Comment by ironcladlou** [comment]
Pretty sure this is from a race condition in the garbage collector related to the spotty support for cluster scoped owner references. If the owner is cluster scoped and the dependent is namespaced, and if the GC happens to observe and process the dependent before the owner, [a virtual node](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/graph_builder.go#L377) is created internally which inherits the namespace of the dependent. After that, the GC will always look for the owner using the dependent's namespace (which will fail, as the owner is cluster scoped). The dependent will be considered dangling and will be deleted.

The solution to this may not be obvious, as OwnerReference doesn't have the information needed to create an accurate virtual reference (as Namespace isn't part of the reference). In the meantime we'll need an upstream issue and simpler test to reproduce, which I can create.

**Comment by caesarxuchao** [comment]
The analysis sounds right. I think we can make two improvements:
1. restmapper knows if a resource is scoped or not, so the virtual node creation could use that as a reference.
2. restmapper could be stale, so if the GC got 404 from the apiserver for a virtual node, it could retry the GET as a cluster scope object.

**Comment by ironcladlou** [comment]
Don't have time to get the k8s issue ready today, but I started work on two pieces which elaborate on the problematic behaviors:

* A [unit test](https://github.com/ironcladlou/kubernetes/blob/cluster-scoped-owner-gc-fix/pkg/controller/garbagecollector/garbagecollector_test.go#L675) which demonstrates some problematic cases
* An [integration test](https://github.com/ironcladlou/kubernetes/blob/cluster-scoped-owner-gc-fix/test/integration/garbagecollector/garbage_collector_test.go#L433) which reproduces [this unit test](https://github.com/ironcladlou/kubernetes/blob/cluster-scoped-owner-gc-fix/pkg/controller/garbagecollector/garbagecollector_test.go#L736) (the problem reported in this GH issue). Requires `stress` to reproduce.

Tomorrow I'll get an upstream issue created and start trying to work on some patches.

**Comment by ironcladlou** [comment]
xref https://github.com/kubernetes/kubernetes/issues/54940

**Comment by ironcladlou** [comment]
xref https://bugzilla.redhat.com/show_bug.cgi?id=1509022
