### ISSUE TITLE
Consistent release of artifacts to Centos YUM site and DockerHub for OpenShift Origin

### ISSUE THREAD

**Issue by LarsMilland** [openshift/origin#17086]
It appears that the process of releasing binary artifacts for releases of OpenShift Origin binaries is not fully consistent.

Especially if one wants to install and update OpenShift Origin installations on RHEL or Centos using the Ansible based installers from:

https://github.com/openshift/openshift-ansible

The Ansible installer would expect to find RPM images published to the Centos mirror location - here I assume:

http://mirror.centos.org/centos/7/paas/x86_64/

Take for example the recent 3.6.1 release where I am still not certain that the RPM binaries are published anywhere in a publicly available YUM repository, that one would either have selected per default from the Ansible installer or could point to as an alternative location. Could those binaries be published somehow?

Same goes for the Alpha and release candidate releases, they are published to DockerHub and as downloads on GitHub, but where they would reside in RPM form in YUM  repositories.

So what I am asking for is some insight in the release process, and if it could maybe be so that all releases are published so that the Ansible installers can be used with them.

Best regards
Lars Milland

**Comment by xiaods** [comment]
what reason for the conflict sync? anyone can explain it workflow asap.

**Comment by LarsMilland** [comment]
@smunilla could you give an indication on ETA of the OpenShift Origin 3.6.1 RPM images to the Centos repositories, before going all in on designing a fully consistent release process. We are looking for a way forward towards the upcoming 3.7.0 release, and would very much like to start with an upgrade to the 3.6.1 release first - with the Ansible installer picking up the binaries from where it picks up its other released binaries from.

**Comment by coreydaley** [comment]
@LarsMilland This issue seems to be out-of-date (referring to 3.6.1 release).  Is this issue still relevant?

**Comment by LarsMilland** [comment]
@coreydaley - Issue is just as relevant now as it was with OpenShift release 3.6.1. The process leading up to the 3.7.0 release was also not fully consistent, and still is not fully completed. I am quite sure that it took a good number of extra days before the Centos repositories where populated with RPM binaries also for the 3.7.0 release - if I remember correctly 3.7.0 was released close to November 29th 2017, and the Centos binaries where not fully there before December 11th 2017 or December 25th 2017 depending on which components that one is needing (http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin37/).

Also the Metrics components that should accompany the Origin release for the 3.7.0 release is not yet tagged on Docker Hub:
https://hub.docker.com/r/openshift/origin-metrics-hawkular-metrics/tags/

So I would still state the release process could need some more consistency.

**Comment by coreydaley** [comment]
@LarsMilland Thanks for the updated information.  Let me see if I can track down who needs to take a look at this.

**Comment by LarsMilland** [comment]
@coreydaley With the OpenShift Origin 3.7.1 release now announced on the github website 17 days ago I don't think the RPM binaries are yet to find on the Centos mirror. Could it  possible be so that the release process can get a consistent process from release to release.

**Comment by DanyC97** [comment]
@LarsMilland not sure if you still interested in this issue however i'll make few notes...

In case you haven't seen few months back (beginning of the year) the CentOS PaaS SIG people in charge of releasing the rpms decided to pass on the baton and step down. 

As such myself and others step up trying to help and not let it go south.
there are few backlog items to improve however in meantime we are trying to release the new OpenShift Origin/ ansible rpms as faster as we can.

Hopefully 3.10 will be out soon, a bit delayed as few things have changed / shifted hence the delay.

should you want to help out we are welcoming you, we have a meeting every Wednesday 17:00 UTC
