### ISSUE TITLE
have a place to store DeploymentConfigs that are generated by a build before they become active then a way to tag them?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#1708]
in a CI system where we run a build we typically generate a new docker image with a tag each build. We can then use tags on images to choose when that generated image gets deployed into a particular environment. 

e.g. a build could make a dev/latest image, then folks can try it out and then label it 'test' to get it auto-deployed to a test environment. So doing a build doesn't always immediately deploy in all environments (though it often does in development; there's usually an approval/CD process for other environments).

In fabric8 land we tend to generate the kubernetes json at build time; we then generate a versioned blob of json for each build. So we use a maven repository to store each versioned kubernetes json etc. Then at some point we may choose to deploy it in an environment.

I wonder if OpenShift needs to work with DeploymentConfigs in a similar way to docker images; that many versions can be generated by a build and added to a registry of DeploymentConfigs (e.g. many versions) and then we can use tags to choose which version of the DeploymentConfig to use in a particular environment. 

e.g. for a given environment, we may use the tag "dev" to find the image+deploymentConfig, another environment may use the tag "test" to find the image+deploymentConfig. It'd be nice to use the same mechanism/tag for both DeploymentConfigs and docker container images?

Another approach is we could generate the DeploymentConfig in a fabric8 build and store it in maven and then have some kind of UI / mechanism to choose to apply a version of a DeploymentConfig in an environment. But it feels like this should be a thing in OpenShift?

Or are there other approaches to track different versions of DeploymentConfigs across environments?

**Comment by jstrachan** [comment]
if its not clear from my comments above - the problem is that DeploymentConfigs change over time as containers are added/removed to pods, labels change, env vars change. Then the images referenced in each DeploymentConfig change too. So you can't really just use 1 DeploymentConfig for a project across all environments (dev, tests, uat, pre-prod, prod) and just change the tags inside per environment. So being able to pair them together with the image tag/version might be better

**Comment by jstrachan** [comment]
Something like helm is looking like a good option for this (i.e. a git repo with a helm like versioned packaging)
http://helm.sh/

more background:
https://github.com/kubernetes/kubernetes/issues/17027

**Comment by kargakis** [comment]
One example:

https://coreos.com/blog/quay-application-registry-for-kubernetes.html
https://github.com/app-registry

**Comment by jstrachan** [comment]
FWIW now openshift 3.6 uses API groups we can use Helm charts to store versioned copies of kubernetes + openshift resources

**Comment by kargakis** [comment]
I am going to close this issue since it doesn't seem as something that needs to be handled inside the core of Origin now with API groups.
