### ISSUE TITLE
How to upgrade from v3.6.0 to v3.6.1

### ISSUE THREAD

**Issue by eliu** [openshift/origin#17100]
I use openshift ansible playbooks to install OpenShift Origin cluster according to instructions for Advanced Installation.

I need suggestions for upgrading from v3.6.0 to v3.6.1

Thanks in advance.

##### Version

```bash
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://`host`:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Current Result
Can't find an effective way to upgrade to v3.6.0

##### Expected Result
An effective method to provide for upgrading OpenShift Origin from v3.6.0 to v3.6.1

**Comment by pweil-** [comment]
Please review the upgrade documentation here: https://docs.openshift.com/container-platform/3.6/install_config/upgrading/automated_upgrades.html#upgrading-to-ocp-3-6

If you are having a specific issue feel free to open a new issue.  Thanks!
