### ISSUE TITLE
oc rollout history should show me the images that each revision run

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17128]
Upstream issue: https://github.com/kubernetes/kubernetes/issues/54932

We need to do this for DCs, too

/sig master
/area apps

cc: @tnozicka @mfojtik

**Comment by kargakis** [comment]
Today:
```
$ oc rollout history dc/plank
deploymentconfigs "plank"
REVISION	STATUS		CAUSE
30		Complete	config change
31		Complete	config change
32		Complete	config change
```

**Comment by pweil-** [comment]
@kargakis was /area supposed to add the component label?

**Comment by kargakis** [comment]
No, it only adds `area/*` labels.

**Comment by kargakis** [comment]
I have been labeling stuff across a bunch of different repos so my command usage ironically is a bad example.

**Comment by kargakis** [comment]
Closing in favor of the upstream issue
