### ISSUE TITLE
ICT triggered builds not guaranteed to use correct image

### ISSUE THREAD

**Issue by bparees** [openshift/origin#1712]
this change:
https://github.com/openshift/origin/commit/c431087f0321a0da31f6c975d0421e67bde2e94e#diff-717854e27d42bef56a972e64d148b529L78

though line 90 means that when we have a build triggered by an ICT, we are no longer guaranteed to build using the image that caused the ICT to fire, we're using the current image associated with the tag when the build finally runs (because that's when the reference gets resolved now, instead of it being set at the time the event occurs).

**Comment by soltysh** [comment]
@bparees since we now have [TriggeredByImage](https://github.com/openshift/origin/blob/master/pkg/build/api/types.go#L451) field set in [image_change_controller.go](https://github.com/openshift/origin/blob/master/pkg/build/controller/image_change_controller.go#L121-L124) to exact docker reference, is this issue still valid?

**Comment by bparees** [comment]
@soltysh I don't think we actually consume that field when constructing the Build object, do we?  it's just metadata about what triggered the build, but we still resolve the ImageStreamTag referenced by the BC, to a value when we create the Build object.  we don't just copy over the TriggeredByImage field to use as the builder image.  (and we can't, since we're about to allow builds to be triggered by random image changes)

**Comment by soltysh** [comment]
Looking at [generator.go](https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L130) we only save that in the trigger information. Do we still want to trigger that particular image that cause it? Even if we allow triggering by random image, we can check for the image origin and use that info for running a build, I guess. The question is rather do we want this to happen or are we ok that we'll always use the latest available image for builds, in which case this issue can be closed, imho.

**Comment by soltysh** [comment]
Still, cleaning the Builds and validation is part of [this trello card](https://trello.com/c/xrPu7upe/590-3-clean-up-validation-logic-in-builds-future-build).

**Comment by bparees** [comment]
@soltysh ultimately I think we want to do the following:
1) if the build was triggered by an image AND that image corresponds to the Strategy.From reference, we should build using the imageid that triggered the build
2) otherwise (build triggered by random image, or manual build, or hook, or whatever), we should resolve the Strategy.From to the current imageid and build using that (which is what we do today in all cases).

However this also might get totally reworked if we do level triggered builds.

**Comment by smarterclayton** [comment]
I believe this was fixed by @kargakis.

**Comment by bparees** [comment]
yes we now use the imageid from the trigger when there is one.
