### ISSUE TITLE
need some clarify for developer workflow.

### ISSUE THREAD

**Issue by xiaods** [openshift/origin#17126]
i follow the HACK.md to do some development, i found it build period is long time on build rpm. so i use hack/build-local-image.py to quick setup the openshift cluster environment.

##### Version

```
$ oc version
oc v3.7.0-alpha.0+8fc2fe6-2000
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth
Unable to connect to the server: x509: certificate signed by unknown authority
```

##### Steps To Reproduce
1. make
2. ./hack/build-local-images.py

##### Current Result

i fount many more untag images in my local docker storage. 
<img width="725" alt="2017-11-01 2 57 46" src="https://user-images.githubusercontent.com/37678/32263596-958af788-bea8-11e7-9155-12a8233b9593.png">

##### Expected Result

only build and tag specified version of openshift image. remove untag docker

**Comment by php-coder** [comment]
CC @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@bparees isn't this the known downside of the local build script? You add the binary over and over again and retag, so you get a lot of storage used.

**Comment by bparees** [comment]
@stevekuznetsov that's a separate issue.  What @xiaods is concerned with is the fact that when we create a new "latest" image, the old image is left around (but with no tag).  That's typical docker behavior (build a new image, any old image with that tag becomes an untagged image).

The recommended solution is to clean up untagged images, e.g.:
`docker images | grep "<none>" | awk '{print $3}' | xargs docker rmi -f`

But yes it is also true that the image you are building will continue to grow in size on each iteration, unless you periodically pull down a fresh base image from dockerhub to reset things.

**Comment by xiaods** [comment]
@bparees thanks all.
