### ISSUE TITLE
Can't create owner ref to service catalog resource with blockOwnerDeletion: true

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#17130]
I'd like to create an owner ref from a secret to a service catalog service instance with `blockOwnerDeletion: true` so that it gets garbage collected when the instance is deleted (if not in 3.7, in a future release where that works). I see a 403 error trying to create the secret, however.

If I use `blockOwnerDeletion: false`, there are no errors.

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "secrets \"mongodb-persistent-parameterso04kv\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: User \"sam\" cannot update serviceinstances/finalizers.servicecatalog.k8s.io in project \"mongo-test\", \u003cnil\u003e",
  "reason": "Forbidden",
  "details": {
    "name": "mongodb-persistent-parameterso04kv",
    "kind": "secrets"
  },
  "code": 403
}
```

Here is the POST request body:

```json
{
   "apiVersion":"v1",
   "kind":"Secret",
   "metadata":{
      "name":"mongodb-persistent-parameterso04kv",
      "ownerReferences":[
         {
            "apiVersion":"servicecatalog.k8s.io/v1beta1",
            "kind":"ServiceInstance",
            "name":"mongodb-persistent-jjhmd",
            "uid":"3ff6e085-bf0f-11e7-bf11-0242ac110002",
            "controller":false,
            "blockOwnerDeletion":true
         }
      ]
   },
   "type":"Opaque",
   "stringData":{
      "parameters":"{\"DATABASE_SERVICE_NAME\":\"mongodb\",\"MEMORY_LIMIT\":\"512Mi\",\"MONGODB_DATABASE\":\"sampledb\",\"MONGODB_VERSION\":\"3.2\",\"NAMESPACE\":\"openshift\",\"VOLUME_CAPACITY\":\"1Gi\"}"
   }
}
```

cc @pmorie @deads2k @jwforres

**Comment by deads2k** [comment]
@liggitt side-effect of having the check based on finalization. Want to allow end-users to finalize so we can let them set ownerrefs?

/assign liggitt

**Comment by liggitt** [comment]
Why is `blockOwnerDeletion: true` required? It will get cleaned up without that, right?

**Comment by spadgett** [comment]
It won't get cleaned up in this case. This is the secret used for parameters when provisioning the service instance, and it isn't deleted by the service catalog.

**Comment by liggitt** [comment]
An ownerref without blockOwnerDeletion is still supposed to result in the child object being reaped.

**Comment by spadgett** [comment]
OK, so it only impacts behavior of foreground deletion? It might not be needed then.

My main concern is that the secret is eventually garbage collected.

**Comment by spadgett** [comment]
Closing since `blockOwnerDeletion` isn't needed for garbage collection
