### ISSUE TITLE
Why does the RPM build take so long?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#17139]
Currently, full RPM build (linux/amd64 only) takes about 20 minutes.

Of that time, steps are:

1. create source tar (tito -> rpm) (~30s)
2. unpack source tar to temp location (~15s depending on IO)
3. run a full clean build-cross
    1. runs static binaries for images (3-4m?)
    2. runs non-static binaries for main projects: openshift, oc, kubefed, templateservicebroker (5-6m)
    3. build release tars
4. builds extended.test, ginkgo, then runs a bunch of man page generations
5. builds service catalog 
6. builds cluster capacity (3-4m)
7. moves things around on disk
8. creates the resulting rpms (cpio) and verifies them, looks like single core (2-3m)
9. copy output directory back to core

Some obvious changes we should be making:

1. service-catalog, kubefed, and cluster-capacity all belong out of tree
2. build release tars is unnecessary and just leads to extra work - save that for build-cross job only
3. running static builds then non static builds seems to clear the package cache, which means we don't get package reuse on repeat builds, and ALSO we are building everything twice.  According to godoc this shouldn't be happening, maybe this is `-installsuffix` or something?  Fixing this would be huge
4. we can't reuse artifacts from the current directory because of tito, which always uses source RPM setup.  There's a way around this - `rpmbuild -ba origin.spec --define "no_source 1" --define "_sourcedir $PWD"` where we have an if block around source, then symlink the BUILD directory in the rpm build root back to the current working directory.  The end result is that the input to the RPM is the current tree, which means we can in theory skip a boatload of work and reuse binary artifacts (if we can fix 3 above), and still reasonably collapse back to the slow mode for release builds
5. avoid the final copy back because of 4
6. we can skip the actual build part with a custom rpm define (do_build = 0) that would then reuse binary artifacts in your output dir.  this takes about 11s

In testing this out, the total overhead of the RPM process takes about 3m30s on a 6core vm without any changes to source (that includes copying around some large binaries that we might get rid of).  If we can address the items above, a flat build can probably 7-8m total, and rebuilds can be closer to 3m.

@derekwaynecarr @deads2k

**Comment by smarterclayton** [comment]
@stevekuznetsov

**Comment by smarterclayton** [comment]
I confirmed that CGO_ENABLED on/off causes the entire package dir to be regenerated.  We should avoid compiling anything that touches a large percentage of the code tree as CGO_ENABLED=0, and then also use a separate pkg dir for cgo enabled.

**Comment by smarterclayton** [comment]
Fixing the CGO part in #17140

**Comment by smarterclayton** [comment]
Extracted release tar creation in #17141

**Comment by xiaods** [comment]
@smarterclayton col

**Comment by stevekuznetsov** [comment]
The other side of this was the flag that Cesar added to just allow us to package pre-built binaries into an RPM in the specifle. Fixing these doesn't seem awful but at the same time the other approach seems easier?

**Comment by xiaods** [comment]
performance is king, in my development cycle, it very important for me.

**Comment by smarterclayton** [comment]
Down to 15 minutes most of the time.  Getting service cat and cluster capacity out will probably give us 5-8 minutes.  Federation should remove a nice small bit.  After that, the primary goal will be being able to bypass the source RPM step (the workaround described above).

**Comment by smarterclayton** [comment]
#17229 fixes it so that we reuse all built artifacts automatically unless we're doing a clean build.  The splits will be handled elsewhere.  After that merges, the new jenkins jobs from @csrwng can simply run build-rpms without clean and get incremental artifacts respected.
