### ISSUE TITLE
Ingress IP Self-Service documentation results in a 404

### ISSUE THREAD

**Issue by gbraad** [openshift/origin#17165]
Missing target for link related to Ingress IP Self-Service

##### Additional Information
https://docs.openshift.org/latest/minishift/openshift/exposing-services.html links to a non-existent link https://docs.openshift.org/latest/dev_guide/getting_traffic_into_cluster.html#using-ingress-IP-self-service

Related issue; https://github.com/minishift/minishift/issues/1651

**Comment by pweil-** [comment]
opening this against the docs repo.  Thanks for reporting it.

https://github.com/openshift/openshift-docs/issues/6142
