### ISSUE TITLE
networking: missing route after failed upgrade took down entire cluster

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#17162]
During an upgrade of our CI cluster from Origin 3.7.0-alpha.0 to -rc.0 we were missing this route:

```
172.16.0.0/16 dev tun0 scope link 
```

This meant that there was no node-to-node connectivity and no pod-to-service connectivity, which rendered the cluster useless.

We have this in our master config

```yaml
networkConfig:
  clusterNetworkCIDR: 172.16.0.0/16
  clusterNetworks:
  - cidr: 172.16.0.0/16
    hostSubnetLength: 9
  externalIPNetworkCIDRs:
  - 0.0.0.0/0
  hostSubnetLength: 9
  networkPluginName: redhat/openshift-ovs-subnet
  serviceNetworkCIDR: 172.30.0.0/16
```

Here are other related infos:

```
# oc get endpoints kubernetes
NAME         ENDPOINTS                                         AGE
kubernetes   10.128.0.2:8443,10.128.0.2:8053,10.128.0.2:8053   64d
```

```
# oc get hostsubnets
NAME                  HOST                  HOST IP       SUBNET           EGRESS IPS
origin-ci-ig-m-11v4   origin-ci-ig-m-11v4   10.128.0.2    172.16.6.0/23    []
origin-ci-ig-n-3hjt   origin-ci-ig-n-3hjt   10.128.0.12   172.16.0.0/23    []
origin-ci-ig-n-451g   origin-ci-ig-n-451g   10.128.0.5    172.16.8.0/23    []
origin-ci-ig-n-b2jj   origin-ci-ig-n-b2jj   10.128.0.8    172.16.2.0/23    []
origin-ci-ig-n-gj0x   origin-ci-ig-n-gj0x   10.128.0.7    172.16.10.0/23   []
origin-ci-ig-n-kkhm   origin-ci-ig-n-kkhm   10.128.0.9    172.16.4.0/23    []
origin-ci-ig-n-kwtq   origin-ci-ig-n-kwtq   10.128.0.10   172.16.14.0/23   []
origin-ci-ig-n-n7xn   origin-ci-ig-n-n7xn   10.128.0.4    172.16.16.0/23   []
origin-ci-ig-n-tdfd   origin-ci-ig-n-tdfd   10.128.0.11   172.16.18.0/23   []
origin-ci-ig-n-x5hm   origin-ci-ig-n-x5hm   10.128.0.3    172.16.20.0/23   []
```

I had restarted, in order:

```
# systemctl restart openvswitch
# systemctl restart docker
# systemctl restart origin-node
```

This did not help. Here are node startup logs from there:

```
systemd[1]: Starting OpenShift Node...
origin-node[93992]: I1102 20:29:46.197330   93992 node.go:146] Initializing SDN node of type "redhat/openshift-ovs-subnet" with configured hostname "origin-ci-ig-m-11v4" (IP ""), iptables sync period "30s"
origin-node[93992]: I1102 20:29:46.525619   93992 node.go:358] Starting openshift-sdn network plugin
origin-node[93992]: I1102 20:29:46.567746   93992 kubelet.go:328] cloud provider determined current node name to be origin-ci-ig-m-11v4
origin-node[93992]: I1102 20:29:46.567763   93992 kubelet.go:271] Watching apiserver
origin-node[93992]: I1102 20:29:46.582720   93992 kubelet.go:507] Hairpin mode set to "none"
origin-node[93992]: I1102 20:29:46.583042   93992 plugins.go:196] Loaded network plugin "cni"
origin-node[93992]: I1102 20:29:46.596562   93992 sdn_controller.go:190] [SDN setup] full SDN setup required
ovs-vsctl[94035]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --if-exists del-br br0 -- add-br br0 -- set Bridge br0 fail-mode=secure protocols=OpenFlow13
origin-node[93992]: I1102 20:29:46.602925   93992 plugins.go:196] Loaded network plugin "cni"
origin-node[93992]: I1102 20:29:46.602978   93992 docker_service.go:210] Docker cri networking managed by cni
origin-node[93992]: I1102 20:29:46.646315   93992 kubelet.go:1796] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
ovs-vsctl[94044]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --if-exists del-port br0 vxlan0
ovs-vsctl[94049]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --may-exist add-port br0 vxlan0 -- set Interface vxlan0 ofport_request=1 type=vxlan "options:remote_ip=\"flow\"" "options:key=\"flow\""
ovs-vsctl[94066]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --if-exists del-port br0 tun0
ovs-vsctl[94069]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --may-exist add-port br0 tun0 -- set Interface tun0 ofport_request=2 type=internal
origin-node[93992]: I1102 20:29:47.136254   93992 sdn_controller.go:261] AddHostSubnetRules for origin-ci-ig-n-gj0x (host: "origin-ci-ig-n-gj0x", ip: "10.128.0.7", subnet: "172.16.10.0/23")
origin-node[93992]: I1102 20:29:47.139537   93992 node.go:418] Starting openshift-sdn pod manager
origin-node[93992]: I1102 20:29:47.161057   93992 sdn_controller.go:261] AddHostSubnetRules for origin-ci-ig-n-kkhm (host: "origin-ci-ig-n-kkhm", ip: "10.128.0.9", subnet: "172.16.4.0/23")
origin-node[93992]: I1102 20:29:47.173710   93992 node.go:461] openshift-sdn network plugin ready
origin-node[93992]: I1102 20:29:47.185283   93992 sdn_controller.go:261] AddHostSubnetRules for origin-ci-ig-n-kwtq (host: "origin-ci-ig-n-kwtq", ip: "10.128.0.10", subnet: "172.16.14.0/23")
origin-node[93992]: I1102 20:29:47.192757   93992 network.go:88] Using iptables Proxier.
origin-node[93992]: W1102 20:29:47.199964   93992 proxier.go:472] missing br-netfilter module or unset sysctl br-nf-call-iptables; proxy may not work as intended
origin-node[93992]: W1102 20:29:47.200068   93992 proxier.go:488] clusterCIDR not specified, unable to distinguish between internal and external traffic
origin-node[93992]: I1102 20:29:47.200938   93992 network.go:119] Tearing down userspace rules.
origin-node[93992]: I1102 20:29:47.213442   93992 sdn_controller.go:261] AddHostSubnetRules for origin-ci-ig-n-n7xn (host: "origin-ci-ig-n-n7xn", ip: "10.128.0.4", subnet: "172.16.16.0/23")
origin-node[93992]: I1102 20:29:47.238781   93992 sdn_controller.go:261] AddHostSubnetRules for origin-ci-ig-n-3hjt (host: "origin-ci-ig-n-3hjt", ip: "10.128.0.12", subnet: "172.16.0.0/23")
origin-node[93992]: I1102 20:29:47.267542   93992 sdn_controller.go:261] AddHostSubnetRules for origin-ci-ig-n-b2jj (host: "origin-ci-ig-n-b2jj", ip: "10.128.0.8", subnet: "172.16.2.0/23")
origin-node[93992]: I1102 20:29:47.283702   93992 proxier.go:187] Setting proxy IP to 10.128.0.2 and initializing iptables
origin-node[93992]: I1102 20:29:47.295064   93992 sdn_controller.go:261] AddHostSubnetRules for origin-ci-ig-n-451g (host: "origin-ci-ig-n-451g", ip: "10.128.0.5", subnet: "172.16.8.0/23")
origin-node[93992]: I1102 20:29:47.320842   93992 sdn_controller.go:261] AddHostSubnetRules for origin-ci-ig-n-tdfd (host: "origin-ci-ig-n-tdfd", ip: "10.128.0.11", subnet: "172.16.18.0/23")
origin-node[93992]: I1102 20:29:47.352838   93992 sdn_controller.go:261] AddHostSubnetRules for origin-ci-ig-n-x5hm (host: "origin-ci-ig-n-x5hm", ip: "10.128.0.3", subnet: "172.16.20.0/23")
systemd[1]: Started OpenShift Node.
origin-node[93992]: I1102 20:29:47.365033   93992 network.go:226] Started Kubernetes Proxy on 0.0.0.0
origin-node[93992]: I1102 20:29:47.365177   93992 config.go:202] Starting service config controller
origin-node[93992]: I1102 20:29:47.365189   93992 controller_utils.go:1025] Waiting for caches to sync for service config controller
origin-node[93992]: I1102 20:29:47.365228   93992 config.go:102] Starting endpoints config controller
origin-node[93992]: I1102 20:29:47.365233   93992 controller_utils.go:1025] Waiting for caches to sync for endpoints config controller
origin-node[93992]: I1102 20:29:47.365294   93992 network.go:52] Starting DNS on 127.0.0.1:53
origin-node[93992]: I1102 20:29:47.379592   93992 server.go:82] Monitoring dnsmasq to point cluster queries to 127.0.0.1
```

This did not help. I believe Clayton had to restart `ovs-vswitchd` -- if we can get `systemctl restart openvswtich` to restart the component services too (if that is not the case today) that would be awesome @sdodson.

/cc @knobunc @danwinship 
/fyi @kargakis @csrwng @smarterclayton

**Comment by stevekuznetsov** [comment]
Also to be clear this is what I saw when things were broken:

```
# ip route
default via 10.128.0.1 dev eth0 proto static metric 100 
10.128.0.1 dev eth0 proto static scope link metric 100 
10.128.0.2 dev eth0 proto kernel scope link src 10.128.0.2 metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.30.0.0/16 dev tun0 
```

And this is what it looked like when things were fine:

```
# ip route
default via 10.128.0.1 dev eth0 proto static metric 100 
10.128.0.1 dev eth0 proto static scope link metric 100 
10.128.0.2 dev eth0 proto kernel scope link src 10.128.0.2 metric 100 
172.16.0.0/16 dev tun0 scope link 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.30.0.0/16 dev tun0 
```

**Comment by danwinship** [comment]
Also, from when it was failing:
    # oc get clusternetwork default -o yaml
    apiVersion: v1
    hostsubnetlength: 9
    kind: ClusterNetwork
    metadata:
      creationTimestamp: 2017-08-30T15:04:52Z
      name: default
      resourceVersion: "11625282"
      selfLink: /oapi/v1/clusternetworks/default
      uid: 9378c7b9-8d94-11e7-a412-42010a800002
    network: 172.16.0.0/16
    pluginName: redhat/openshift-ovs-subnet
    serviceNetwork: 172.30.0.0/16

(Note: 3.6-era ClusterNetwork with `network` set but `clusterNetworks` not set.) The (3.7) master is supposed to fix this on startup, but apparently didn't, and the nodes are failing to deal backward-compatibly. (The nodes not dealing is not a problem, right? We require the master to be upgraded first, so 3.6 nodes have to be able to deal with a 3.7 master, but 3.7 nodes don't have to be able to deal with a 3.6 master, right?)

**Comment by danwinship** [comment]
I can't see how the master wouldn't fix this on startup... pkg/network/master/master.go:clusterNetworkChanged() returns true if `len(old.ClusterNetworks) != len(obj.ClusterNetworks)`. `old.ClusterNetworks` would be the ClusterNetwork record above, which has 0 ClusterNetworks, and `obj.ClusterNetworks` is the one constructed in Start(), which is guaranteed to have non-0 ClusterNetworks, so it should have returned true, so it should have updated the object.

Do you have the master logs from when things were failing? Did it log `Updated ClusterNetwork ...` after `Initializing SDN master of type ...`?

**Comment by stevekuznetsov** [comment]
We don't have logs from the restart unfortunately.

**Comment by danwinship** [comment]
> Also, from when it was failing:
> 
>     # oc get clusternetwork default -o yaml
>     apiVersion: v1
>     hostsubnetlength: 9

Wait, that's not the output of a 3.7 master. Even if clusterNetworks wasn't set, the field is not marked optional/omitempty. So there should have been a line `clusterNetworks: []` there. Eg:

    danw@w541:origin (master)> cat /tmp/testing-clusternetwork.yaml 
    apiVersion: v1
    kind: ClusterNetwork
    metadata:
      name: testing
    network: 10.128.0.0/14
    hostsubnetlength: 9
    serviceNetwork: 172.30.0.0/16
    pluginName: redhat/openshift-ovs-multitenant
    danw@w541:origin (master)> oc create -f /tmp/testing-clusternetwork.yaml 
    clusternetwork "testing" created
    danw@w541:origin (master)> oc get clusternetwork testing -o yaml
    apiVersion: v1
    clusterNetworks: []
    hostsubnetlength: 9
    kind: ClusterNetwork
    metadata:
      creationTimestamp: 2017-11-03T18:04:33Z
      name: testing
      resourceVersion: "2816"
      selfLink: /oapi/v1/clusternetworks/testing
      uid: 71e56d85-c0c1-11e7-8617-024202439325
    network: 10.128.0.0/14
    pluginName: redhat/openshift-ovs-multitenant
    serviceNetwork: 172.30.0.0/16

So it looks like you were running 3.7 nodes against a 3.6 master at that point

**Comment by danwinship** [comment]
> So it looks like you were running 3.7 nodes against a 3.6 master at that point

well, 3.7.0-rc.0 nodes against a 3.7.0-alpha.0 master anyway. The multi-clusterNetworks stuff happened between alpha.1 and rc.0

**Comment by smarterclayton** [comment]
The master config is upgraded in place.  Old clusters won't necessarily
have the new fields in master-config.  A cluster upgrade step has to set
each net new field

**Comment by stevekuznetsov** [comment]
@danwinship in case it's useful, current output:

```
$ oc version
oc v3.7.0-alpha.0+ff11ac6-545
kubernetes v1.7.0+695f48a16f
features: Basic-Auth

Server https://api.ci.openshift.org:443
openshift v3.7.0-rc.0+bd64aab-99
kubernetes v1.7.6+a08f5eeb62

$ oc get clusternetwork default -o yaml
apiVersion: v1
clusterNetworks:
- CIDR: 172.16.0.0/16
  hostSubnetLength: 9
hostsubnetlength: 9
kind: ClusterNetwork
metadata:
  creationTimestamp: 2017-08-30T15:04:52Z
  name: default
  resourceVersion: "11636657"
  selfLink: /oapi/v1/clusternetworks/default
  uid: 9378c7b9-8d94-11e7-a412-42010a800002
network: 172.16.0.0/16
pluginName: redhat/openshift-ovs-subnet
```

**Comment by danwinship** [comment]
@smarterclayton no, it's not about the master-config. If you run a 3.7 master against a 3.6 master-config.yaml, it will work just fine. It will just use the old master-config values to set the new ClusterNetwork values (and then update the default ClusterNetwork object in etcd to contain both old and new values). And even if for some reason that failed, you would still see the (empty) new 3.7 `clusterNetworks` field in the `oc get clusternetwork` response. The output we saw indicates that we were talking to a master that didn't even know about multiple cluster CIDRs.

**Comment by smarterclayton** [comment]
I double checked this - at no point did we have a newer node against an
older master, because of the other problems with ansible.

**Comment by danwinship** [comment]
Is there some sort of database upgrade process that happens the first time you run a new master with changed API definitions, that might possibly have failed in this case? In my tests, a current 3.7 master always returns *something* for `clusterNetworks`, even if it's just `[]`. Whereas the CI master a few days ago seemed to not know that field existed.
