### ISSUE TITLE
ref v1.Image.dockerImageSignatures can not be found in swagger json file 

### ISSUE THREAD

**Issue by AvTiMp** [openshift/origin#17168]
https://raw.githubusercontent.com/openshift/origin/release-3.6/api/swagger-spec/oapi-v1.json
definitions in this file contains a ref named "v1.Image.dockerImageSignatures" which can't be resolved

##### Version
origin 3.6

##### Steps To Reproduce
1. just search v1.Image.dockerImageSignatures in [oapi-v1.json](https://raw.githubusercontent.com/openshift/origin/release-3.6/api/swagger-spec/oapi-v1.json)

##### Current Result
this term can't be resloved

**Comment by mfojtik** [comment]
hrm:

```json
     "dockerImageSignatures": {
      "type": "array",
      "items": {
       "$ref": "v1.Image.dockerImageSignatures"
      },
      "description": "DockerImageSignatures provides the signatures as opaque blobs. This is a part of manifest schema v1."
     },
```

The `DockerImageSignatures` is `[][]byte`... I guess this is a swagger bug? @deads2k ?

**Comment by AvTiMp** [comment]
the definition **time.Duration** also can't be resolved in the same file, @mfojtik

**Comment by surajssd** [comment]
Yes anyone looking at this issue?

cc: @mfojtik 

Also another question on top of it, when is the OpenAPI specification for OpenShift being released?
