### ISSUE TITLE
kubelet authorizer/authenticator checks to master fail after first rotation

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#17189]
Some kubelet API calls appear to fail after cert rotation - specifically checking permissions against the server.

```
32 server.go:240] Unable to authenticate the request due to an error: the server has asked for the client to provide credentials (post tokenreviews.authentication.k8s.io)
32 server.go:240] Unable to authenticate the request due to an error: the server has asked for the client to provide credentials (post tokenreviews.authentication.k8s.io)
32 webhook.go:185] Failed to make webhook authorizer request: the server has asked for the client to provide credentials (post subjectaccessreviews.authorization.k8s.io)
32 server.go:256] Authorization error (user=system:openshift-node-admin, verb=get, resource=nodes, subresource=stats)%!(EXTRA *errors.StatusError=the server has asked for the clie
```

Looks like the authorizer / authenticator is not being rotated.

**Comment by smarterclayton** [comment]
@liggitt should the node be able to perform token reviews?

```
oc adm policy who-can create tokenreviews.authentication.k8s.io --all-namespaces
Namespace: <all>
Verb:      create
Resource:  tokenreviews.authentication.k8s.io

Users:  system:admin
        system:kube-controller-manager
        system:serviceaccount:default:router
        system:serviceaccount:extended-test-openshift-template-service-broker-96gnh-2sl6k:apiserver
        system:serviceaccount:extended-test-openshift-template-service-broker-mcsrm-qsj9q:apiserver
        system:serviceaccount:extended-test-openshift-template-service-broker-rkrxn-trvtf:apiserver
        system:serviceaccount:kube-system:prometheus
        system:serviceaccount:management-infra:management-admin

Groups: system:cluster-admins
        system:cluster-readers
        system:masters
```

**Comment by liggitt** [comment]
Nodes are allowed to create token reviews

Node authorizer doesn't yet inform resource access reviews which back `who-can`

Possible a separate client is being constructed for the remote authenticator/authorizer and is detached from the client that gets rotated

**Comment by smarterclayton** [comment]
Yeah, I was looking for that.  Will have to dig in tomorrow.


On Nov 5, 2017, at 3:30 PM, Jordan Liggitt <notifications@github.com> wrote:

Nodes are allowed to create token reviews

Node authorizer doesn't yet inform resource access reviews which back
who-can

Possible a separate client is being constructed for the remote
authenticator/authorizer and is detached from the client that gets rotated

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/17189#issuecomment-342002850>,
or mute the thread
