### ISSUE TITLE
Aggregated Logs instructions do not install for Openshift on macos

### ISSUE THREAD

**Issue by npiper** [openshift/origin#17182]
In following the [Aggregating Container Logs](https://docs.openshift.com/enterprise/3.2/install_config/aggregate_logging.html) instructions for a local install on Mac OSX there were several omissions in the instructions.

I put the required changes to create required user accounts, permissions into a shell script, however even after modifying these to get the template installed the pods did not start.

##### Version
[provide output of the `openshift version` or `oc version` command]

oc v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4

Mac OS 10.12.6

Docker Version 1.12.3 (13776)
Channel: Stable
583d1b8ffe

##### Steps To Reproduce
1. Follow instructions on https://docs.openshift.com/enterprise/3.2/install_config/aggregate_logging.html#troubleshooting-kibana into a scripted install (attached file)
2. Execute Shell script  [project.sh.txt](https://github.com/openshift/origin/files/1443112/project.sh.txt)

3. Elastic search fails to start
[install.log](https://github.com/openshift/origin/files/1443113/install.log)

```

[2017-11-03 03:20:26,255][INFO ][container.run            ] Checking if Elasticsearch is ready on https://localhost:9200
--
  | log4j:WARN No appenders could be found for logger (bootstrap).
  | log4j:WARN Please initialize the log4j system properly.
  | log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
  | Exception in thread "main" ElasticsearchException[searchguard.ssl.transport.keystore_filepath must be set if transport ssl is reqested.]
```

##### Current Result

```
>oc get pods
NAME                          READY     STATUS             RESTARTS   AGE
logging-curator-1-qbc59       1/1       Running            0          1d
logging-deployer-gksxl        0/1       Completed          0          1d
logging-es-1rx4334p-1-xtn4s   0/1       CrashLoopBackOff   10         1d
logging-kibana-1-deploy       0/1       Error              0          1d


oc get dc
NAME                  REVISION   DESIRED   CURRENT   TRIGGERED BY
logging-curator       1          1         1         
logging-es-1rx4334p   1          1         1         
logging-kibana        1          1         0  


```

##### Expected Result

Instructions should indicate extra steps needed to successfully install - 5 new service accounts & role/permission changes were required for the install script to finish & pods to be installed. (in shell script)

Template should result in succesfull install and pods start correctly so EFK functionality can be trialled.

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by pweil-** [comment]
It looks like you are running 1.5 origin but using install instructions from the 1.2 (3.2) time frame.  I would suggest here to use the updated instructions and installers in order to avoid unsupported configurations.  If you run into issues with installing 1.5 aggregated logging on the 1.5 cluster please reach out.

/cc @jcantrill

**Comment by npiper** [comment]
Found this article which helped just for demoing EFK locally, I'm on a single mac-os so didn't want to set up a full blown clustered install (yet):

https://stefanopicozzi.blog/2016/11/29/logging-with-openshift/

`oc cluster up --logging=true` - sets up EFK to start - not sure if is this using the same template?
