### ISSUE TITLE
An error occurred creating the route

### ISSUE THREAD

**Issue by syui** [openshift/origin#17183]
## oc version

oc v3.6.173.0.5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://api.starter-us-east-1.openshift.com:443
openshift v3.6.173.0.5
kubernetes v1.6.1+5115d708d7

## An error occurred creating the route

I am using OpenShift Online Starter.

I was able to create routes until October.

At the time of route creation an error occurs.

> An error occurred creating the route. 
> Reason: Route "xxxxxxx" is invalid: spec.host: Forbidden: you do not have permission to set the host field of the route

ref : https://github.com/openshift/openshift-docs/issues/6086

**Comment by kmb385** [comment]
I am having the same issue.

**Comment by jkkj93** [comment]
I met the same problem.

**Comment by mfojtik** [comment]
@simo5 @enj the forbidden error looks like validation

**Comment by dgoodwin** [comment]
Custom routes were intentionally disabled in starter clusters late last week, was not intended to be a permanent feature. 

CC @Miciah

**Comment by dgoodwin** [comment]
@abhgupta as well.

**Comment by eparis** [comment]
All of our starter clusters have had an additional restriction added which now prevents the creation of any route with the 'host' field set. When creating a route please do not set `spec.host`. The system will fill out `spec.host` for you after the route is created.

**Comment by wgordon17** [comment]
This is inline with the Starter restriction of [no custom domains allowed](https://www.openshift.com/pricing/index.html#online-plan-comparison).

**Comment by syui** [comment]
Can it handle CNAME or redirect?

> Application is not available

**Comment by wgordon17** [comment]
In order for a CNAME to be accepted, the route with the appropriate host must be created first. This @syui is a restriction of the Starter plan. If you need a custom domain, you will have to upgrade to Pro.

**Comment by syui** [comment]
ok, thanks

**Comment by bradley-s** [comment]
thats not great

**Comment by abhgupta** [comment]
For additional context, custom host names in routes were always blocked. However, that restriction/validation was lost during an upgrade (regression) and was re-applied last week.

**Comment by kmb385** [comment]
Looks like I will be switching hosting environments.  Digital Ocean = $5 month

**Comment by jkkj93** [comment]
Got it.Thank you for answering.

**Comment by wpg4665** [comment]
@kmb385 Digital ocean is a great and affordable resource for basic web hosting, but if you need the advanced capabilities of a system for automating deployment, scaling, and management of containerized applications, then I'll use OpenShift all day long!
