### ISSUE TITLE
install and use oc cluster up from master

### ISSUE THREAD

**Issue by krasi-georgiev** [openshift/origin#17181]
I expect to be able to do the following

```
cd cmd/oc
go install
oc cluster up
```

The result is 
```
Starting OpenShift using : ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for : image ... FAIL
   Error: unexpected error inspecting image :
   Caused By:
     Error: Error response from daemon: {"message":"no such image: :: invalid reference format"}
exit status 1
```

if building oc from source would require some additional configuration this should be  noted in the doc files.

##### Version
```
oc version
oc unknown
kubernetes v1.7.6+$Format:%h$
features: Basic-Auth
```

##### Additional Information
```
oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
[Note] No client configuration specified; skipping client and cluster diagnostics.
[Note] Summary of diagnostics execution (version unknown):
[Note] Completed with no errors or warnings seen.
```

**Comment by mfojtik** [comment]
I'm pretty sure the 'unknown' as version is what is broken here. The `oc` binary is trying to pull the openshift/origin image but failing because it can't detect the version. I guess you can use `--image` flag to fix this or just build the oc binary using `./hack/build-go.sh cmd/oc`.

**Comment by xiaods** [comment]
yes

**Comment by krasi-georgiev** [comment]
I also tried specifing an image with `--image=openshift/origin:v3.7.0-rc.0` but didn't make a difference.

building it with `./hack/build-go.sh cmd/oc` works ok 
Thanks

**Comment by pweil-** [comment]
looks like you're up and running now and since the contributing guide instructions have you build before running cluster up (rather than a `go install`) I am resolving this.
