### ISSUE TITLE
openshift_release is 3.6.1 which is not a valid release for a 3.6 upgrade

### ISSUE THREAD

**Issue by eliu** [openshift/origin#17199]
The official upgrade guide does not help. A more detailed steps for upgrading from v3.6.0 to v3.6.1 is required.

##### Version
```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.example.com:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. Change all version stamp from v3.6.0 to v3.6.1 in ansible inventory host file.
2. run `ansible-playbook /usr/share/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml`

##### Current Result
```
Failure summary:


  1. Hosts:    master.example.com
     Play:     Verify upgrade can proceed on first master
     Task:     fail
     Message:  openshift_release is 3.6.1 which is not a valid release for a 3.6 upgrade
```
##### Expected Result
Upgrade succeeded without errors

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by eliu** [comment]
There's no such directory within openshift-ansible like `v3_6_minior`, the OpenShift Origin documentation might be latest:

https://docs.openshift.org/latest/install_config/upgrading/automated_upgrades.html#upgrading-to-openshift-origin-1-1-z-releases

**Comment by xiaods** [comment]
see here: https://github.com/openshift/origin/issues/17192

**Comment by pweil-** [comment]
Please give the `openshift_repos_enable_testing=true` solution a shot and see if that resolves your issue.  If not let's consolidate on #17192.  Thanks!

**Comment by eliu** [comment]
@pweil- @xiaods This method did not work on my cluster. After added this openshift_repos_enable_testing=true into my inventory file, the openshift ansible still report the same failure message as before:

```
Failure summary:


  1. Hosts:    master.msrv.infinitus.com
     Play:     Verify upgrade can proceed on first master
     Task:     fail
     Message:  openshift_release is 3.6.1 which is not a valid release for a 3.6 upgrade
```
