### ISSUE TITLE
When is the origin 3.6.1 update to centos yum source?

### ISSUE THREAD

**Issue by pennpeng** [openshift/origin#17192]
Hi,When is the origin 3.6.1 rpm package update to centos yum source?

**Comment by sdodson** [comment]
set openshift_repos_enable_testing=true to enable those repos at install time.

**Comment by pennpeng** [comment]
@sdodson  ok,thank you

**Comment by sdodson** [comment]
3.6.1 rpms posted http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin36/
