### ISSUE TITLE
build error: fatal: unable to access 'https://github.com/redhat-iot/summit2017/': Failed connect to github.com:443;

### ISSUE THREAD

**Issue by kamran000** [openshift/origin#17193]
Cloning "https://github.com/redhat-iot/summit2017" ...
WARNING: timed out waiting for git server, will wait 1m4s
WARNING: timed out waiting for git server, will wait 4m16s
error: build error: fatal: unable to access 'https://github.com/redhat-iot/summit2017/': Failed connect to github.com:443;

**Comment by mfojtik** [comment]
@kamran000 can you provide more details? Is this online, local environment? What version of openshift?

**Comment by kamran000** [comment]
@mfojtik its local environment v3.6.1

**Comment by bparees** [comment]
your pod can't reach external hosts.  you have a networking issue in your cluster.

**Comment by kamran000** [comment]
@bparees Thanks issue Solved, but now facing following issue in building app 


Registry server Address:
--

**Comment by bparees** [comment]
sounds like you still have a networking issue (your host nodes running your docker daemon can't reach the registry service.  is it pushing to the registry using the registry service hostname, or ip address?)

**Comment by kamran000** [comment]
@bparees Thanks issue resolved by redeploying Docker Registry with default image and parameters.
