### ISSUE TITLE
Need to give help to users when service catalog fails to start in cluster up

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#17201]
When service catalog fails to start during cluster up we should help users debug the problem.

Could be something as simple as telling them to log in as the admin and run `oc status -n kube-service-catalog`.  Otherwise a new user has no idea how to figure out what went wrong.

**Comment by xiaods** [comment]
@jwforres i have testing start service catalog with upstream origin, it works like a charm. have a try.

**Comment by jwforres** [comment]
This issue is not that it is broken, but that when it does fail we don't give users the next steps for debugging what went wrong. We have seen it fail often enough for random reasons in our heavy usage of cluster up on the console team.

**Comment by jmrodri** [comment]
+1 I'm trying to start it with `oc cluster up --service-catalog=true` and it is failing. Yet not quite sure how to debug it.
