### ISSUE TITLE
origin/examples/statefulsets/mysql/galera/ not up to date 

### ISSUE THREAD

**Issue by MONTATICH** [openshift/origin#17211]
when i try to create the docker image "erkules/galera:basic" stated in the mysql-galera.yaml, I get this error:

W: Failed to fetch http://releases.galeracluster.com/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

Even when I try to fix it by putting the right path, then try to deploy the mysql-galera.yaml, I get this error 

chown: invalid user: 'mysql:mysql'

Can you please Update this deployment ? Thank you

**Comment by php-coder** [comment]
CC @soltysh

**Comment by MONTATICH** [comment]
@php-coder @soltysh @pweil- 
Hello, sorry to bother you !!
Would you be able to update the repo anytime soon, because i needed for an urgent deployment.
 Thanks

**Comment by xiaods** [comment]
i have testing on it. failed caused that  erkules/galera.
1、erkules/galera:basic is not found anymore, use erkules/galera:latest
2、Dockerfile no User, we need update or change another image source.

**Comment by xiaods** [comment]
@MONTATICH use alternative way.
https://github.com/adfinis-sygroup/openshift-mariadb-galera

**Comment by xiaods** [comment]
@MONTATICH are u try this repo:

https://github.com/kubernetes/contrib/tree/d6e4be066cc076fbb91ff69691819e117711b30b/pets

**Comment by xiaods** [comment]
check the upstream repo, it also not update on it. maybe need update the contrib repo on k8s project.

**Comment by MONTATICH** [comment]
@xiaods 
The petsets example still uses the same docker images erkules/galera:latest 

I created the docker image myself based on the erkules/galera:latest dockerfile 
and updated the galeracluster packages path in the dockerfile after contacting galeracluster and were able to update their page http://galeracluster.com/documentation-webpages/docker.html#building-the-container-image

from 
RUN add-apt-repository 'deb http://releases.galeracluster.com/ubuntu xenial main'
to 
RUN add-apt-repository 'deb http://releases.galeracluster.com/galera-3/ubuntu trusty main'
RUN add-apt-repository 'deb http://releases.galeracluster.com/mysql-wsrep-5.6/ubuntu trusty main'

But then when I deploy the mysql-galera.yaml file using my own editable new image of rkules/galera:latest, I get this error

 chown: invalid user: 'mysql:mysql'

and the pod won't initialize 

I contacted the erkules/galera:latest image owner and notify him of the galera changecluster package change, he said he will make the changes and rebase the image

**Comment by soltysh** [comment]
This example doesn't exist anymore.
/close
