### ISSUE TITLE
get services should show # of running pods

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#1721]
doing 
'osc get services' should also show the number of running pods per service. The web console does this and it would be very helpful for 1) debugging non running services 2) quick estimates of resource usage

Here is an example of how it could look:
spousty@localhost openshift-client$ ./osc get services
NAME                LABELS                                   SELECTOR            IP                  PORT     PODS
database            template=application-template-stibuild   name=database       172.30.17.25        5434     6
frontend            template=application-template-stibuild   name=frontend       172.30.17.26        5432   0

**Comment by liggitt** [comment]
`osc get` is just a passthrough to the API call for that one object type. Try `osc describe service [name]`

**Comment by jwforres** [comment]
Describe doesn't appear to show this today, but it probably should.

**Comment by kargakis** [comment]
Apparently the number of a service's pods is the number of its endpoints.

While working on changing it upstream, I argued that we shouldn't let the user guess about it, though I can see the point of not correlating services with pods but with endpoints. As @liggitt mentioned, you can derive the pod number from `osc describe svc <name>`.
