### ISSUE TITLE
VMware fusion reference need to be removed from https://www.openshift.org/minishift/

### ISSUE THREAD

**Issue by budhrg** [openshift/origin#17232]
`VMware fusion` driver was never properly tested in Minishift and we are dropping its support now. See https://github.com/minishift/minishift/pull/1643.

Please update the page https://www.openshift.org/minishift/ as well.

NOTE: I couldn't find the code from where above documentation is being rendered. Hence, creating here.

/cc @csrwng

**Comment by LalatenduMohanty** [comment]
Please open the issue in https://github.com/openshift/openshift.org.

**Comment by budhrg** [comment]
Closing it now as I have sent the PR here https://github.com/openshift/openshift.org/pull/81.
