### ISSUE TITLE
Metrics not working for oc cluster up --latest --metrics

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#17237]
I ran the following command:

```
$ oc cluster up --version=latest --service-catalog --metrics
```

I see the following error in the openshift-ansible-metrics-job pod:

> fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "The conditional check 'lookupip.stdout not in ansible_all_ipv4_addresses' failed. The error was: error while evaluating conditional (lookupip.stdout not in ansible_all_ipv4_addresses): Unable to look up a name or access an attribute in template string ({% if lookupip.stdout not in ansible_all_ipv4_addresses %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/validate_hostnames.yml': line 11, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n failed_when: false\n - name: Warn user about bad openshift_hostname values\n ^ here\n"}

Full log: [openshift-ansible-metrics-job-c8v7d.log](https://github.com/openshift/origin/files/1454095/openshift-ansible-metrics-job-c8v7d.log)

All of my metrics pods are failed:

```
$ oc get pods -n openshift-infra
NAME                                  READY     STATUS    RESTARTS   AGE
openshift-ansible-metrics-job-c8v7d   0/1       Error     0          46m
openshift-ansible-metrics-job-k4qbx   0/1       Error     0          47m
openshift-ansible-metrics-job-kqz2z   0/1       Error     0          51m
openshift-ansible-metrics-job-nn4bb   0/1       Error     0          49m
```

##### Version

oc v3.7.0-alpha.1+b953213-1499
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.7.0-rc.0+b953213-158
kubernetes v1.7.6+a08f5eeb62

cc @jwforres @csrwng @rhamilto

**Comment by jcantrill** [comment]
@sdodson  or @ewolinetz  Do you know anything about this error?

**Comment by wozniakjan** [comment]
The merged https://github.com/openshift/origin/pull/19209 decided to remove --logging and --metrics instead of #18628

**Comment by jwforres** [comment]
@jcantrill did you add a separate card / bug / issue for tracking the new `oc cluster add metrics` workflow

**Comment by jcantrill** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1565239
