### ISSUE TITLE
OpenAPI Spec enhancement request

### ISSUE THREAD

**Issue by tanaka-takayoshi** [openshift/origin#17231]
[provide a description of the issue]

##### Version
3.6 (not depends on client/server, only on the spec file on the GitHub)
https://github.com/openshift/origin/blob/release-3.6/api/swagger-spec/openshift-openapi-spec.json

##### Steps To Reproduce
1.  Creating a client library with [autorest](https://github.com/Azure/autorest)

##### Current Result
-[Fatal]Error generating client model: Please specify a field with type of System.Byte[] to deserialize the file contents to
- Generated C# library has compilation errors.

##### Expected Result
No error.

##### Additional Info
I generate .NET Framework Client Library for OpenShift. [The current OpenAPI Spec](https://github.com/openshift/origin/blob/release-3.6/api/swagger-spec/openshift-openapi-spec.json) has two issues. 

- MIME Type is specified as ``*/*``
There are several values ``*/*`` in ``produces`` and ``consumes``. Autorest doesn't work for ``*/*``. Could you specify a specific MIME type? If not, could you tell me the reason because I'll find a workaround?

- ``uniqueItems`` validation is specified in the filed whose type is ``string``
According to the JSON Scheme RFC (draft), ``uniqueItems`` validation is intended for the list items.
https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.3.4
Could you tell me why ``uniqueItems`` validation is specified in type ``string``?

--

**Comment by xiaods** [comment]
need more steps.

**Comment by pweil-** [comment]
@juanvallejo @fabianofranz is this something you cover? /cc @mfojtik
