### ISSUE TITLE
Race during TestDNS integration test to create default namespace

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1724]
Seeing this happen in some integration tests, which means it's racing for the default namespace which seems very strange.  Should we be waiting for the default namespace to be created in this test (or in StartTestMaster) @derekwaynecarr @deads2k ?

```
E0413 17:17:51.732585   10005 kubelet.go:569] Unable to update node status: Update node status exceeds retry count
--- FAIL: TestDNS (16.26s)
	dns_test.go:49: ;; opcode: QUERY, status: NOERROR, id: 62101
		;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
		
		;; QUESTION SECTION:
		;kubernetes.default.local.	IN	 A
		
		;; ANSWER SECTION:
		kubernetes.default.local.	30	IN	A	172.30.0.2
		
	dns_test.go:66: unexpected error: Service "headless" is forbidden: Namespace default does not exist
FAIL
```

**Comment by derekwaynecarr** [comment]
It could be that the namespace actually does exist, but the watch/list in the admission control has not been propagated with that state.  For Origin resources, I added a hook where if a namespace is not found in the store, we make a final call to etcd to check again for the namespace.  This avoided a similar race for Origin resources, looks like if you are still seeing it I need to add that change to upstream Kube as well.

**Comment by smarterclayton** [comment]
This is fixed.
