### ISSUE TITLE
Application on OpenShift Online are not accessible(STARTER PLAN West-1-California)

### ISSUE THREAD

**Issue by stanky91** [openshift/origin#17246]
oc v3.6.173.0.5
kubernetes v1.6.1+
features: Basic-Auth

Server https://api.starter-us-west-1.openshift.com:443
openshift v3.6.173.0.5
kubernetes v1.6.1+

I can't access my application on OpenShift Online (STARTER PLAN West-1-California).But the pods are still running normally.I found some sites running on West-1-California servers through Google with the keywords "west   openshiftapps.com",And they are not available at all.

**Comment by jhonnymertz** [comment]
Same problem here, port forwarding is working properly but external access not. Maybe it's a route/DNS problem.

**Comment by stanky91** [comment]
My application is available now.Thanks for the staffs of Red Hat.

**Comment by jhonnymertz** [comment]
Solved here too. This issue can be closed.
