### ISSUE TITLE
Pods can't resolve service name

### ISSUE THREAD

**Issue by samiaben88** [openshift/origin#17256]
[provide a description of the issue]

I have an openshift cluster above an openstack iaas, I followed this https://github.com/redhat-openstack/openshift-on-openstack , I have one master one node "infra" that have the registry and the Haproxy router in it , and I have 2 slaves. I followed this: https://docs.openshift.com/enterprise/3.1/admin_guide/sdn_troubleshooting.html and seems like everything is ok.

##### Version
openshift v1.5.1
kubernetes v1.5.2+43a9be4
etcd 3.1.0

##### Steps To Reproduce
from a pod I cannot ping or curl another service by name or by IP adress (172.x.x.x) , but I can from all the nodes.

##### Current Result
When I run some pods that where supposed to know each other I get unKnownHost: <service_name> 
##### Expected Result
that the pod have no unKnownHost error and , recognise each other
##### Additional Information
I use a wildcard in my dns server that serves my external URL services which is "cloudapp.nubo.xxx.fr"  and I'm suspicious when I see the /etc/resolv.conf (which is the same from all pods, but the nameserver which is the same as the node where they run):

search test2-fabric8.svc.cluster.local svc.cluster.local cluster.local openstacklocal nubo.xxx.fr cluster.local                        
nameserver 192.168.0.15                                                                                                                 
nameserver 192.168.0.15                                                                                                                 
options ndots:5   

 I'm also suspicious about the option "ndots:5" which constraint the pod to use the "search url"  in the resolv.conf file.

How could I resolve this and what are the best practice to debug this problem, any help please

**Comment by knobunc** [comment]
I suspect you are not using a network plugin.  Was this created with `oc cluster up`?  If so, nothing enables hairpin mode on the docker bridge, so the service traffic flows from the pod to the node, gets natted, and then returns to the docker bridge, at which point it is dropped.
