### ISSUE TITLE
WaitForRunningBuild isn't handling watch errors properly

### ISSUE THREAD

**Issue by bparees** [openshift/origin#17266]
As seen here:
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/279/testReport/junit/(root)/Extended/_image_ecosystem__Slow__openshift_sample_application_repositories__image_ecosystem__php__test_php_images_with_cakephp_ex_db_repo__Building_cakephp_mysql_app_from_new_app_should_build_a_cakephp_mysql_image_and_run_it_in_a_pod__Suite_openshift_/

```
Nov 10 18:49:50.625: INFO: Running 'oc logs --config=/tmp/extended-test-cakephp-mysql-repo-test-lxvtx-t759j-user.kubeconfig --namespace=extended-test-cakephp-mysql-repo-test-lxvtx-t759j -f bc/cakephp-mysql-example --timestamps'
Nov 10 18:49:50.987: INFO: Error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc [oc logs --config=/tmp/extended-test-cakephp-mysql-repo-test-lxvtx-t759j-user.kubeconfig --namespace=extended-test-cakephp-mysql-repo-test-lxvtx-t759j -f bc/cakephp-mysql-example --timestamps] []   Error from server (BadRequest): unable to wait for build cakephp-mysql-example-1 to run: received unknown object while watching for builds: *v1.Status
 Error from server (BadRequest): unable to wait for build cakephp-mysql-example-1 to run: received unknown object while watching for builds: *v1.Status
 [] <nil> 0xc420ecdd40 exit status 1 <nil> <nil> true [0xc421c3a168 0xc421c3a190 0xc421c3a190] [0xc421c3a168 0xc421c3a190] [0xc421c3a170 0xc421c3a188] [0x17c2760 0x17c2860] 0xc421996f60 <nil>}:
Error from server (BadRequest): unable to wait for build cakephp-mysql-example-1 to run: received unknown object while watching for builds: *v1.Status
```

The code in question is:
https://github.com/openshift/origin/blob/d076bb5669a279b16b15ceb126c3e75fca3ebb31/pkg/build/registry/rest.go#L24-L36

So i don't see that there is anything wrong w/ the client logic...why are were getting back a non-build resource object on our watch?

@mfojtik @deads2k @smarterclayton

**Comment by bparees** [comment]
and @liggitt for good measure.

**Comment by liggitt** [comment]
you're not checking the watch event type... if it's an error event (as is the case when the watch expires), the event object type will be a status object:


```
{"type":"ERROR","object":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"etcdserver: mvcc: required revision has been compacted","reason":"Expired","code":410}}
```

**Comment by bparees** [comment]
thanks @liggitt

**Comment by smarterclayton** [comment]
You can get status from a watch

On Nov 10, 2017, at 2:41 PM, Ben Parees <notifications@github.com> wrote:

thanks @liggitt <https://github.com/liggitt>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/17266#issuecomment-343567075>,
or mute the thread
