### ISSUE TITLE
template-instance-controller has wrong permissions

### ISSUE THREAD

**Issue by enj** [openshift/origin#17260]
Not sure what the intent of this line is:

https://github.com/openshift/origin/blob/3153f8042f31328a19448e483dfa9e307b518669/pkg/cmd/server/bootstrappolicy/controller_policy.go#L159

This fails closed since there is no such object in that group.

cc @openshift/sig-security

**Comment by bparees** [comment]
Pretty sure we can just delete that line, but not sure what it was intended to be @jim-minter ?

**Comment by bparees** [comment]
also not sure why this is a p1. nothing is breaking, right?

**Comment by enj** [comment]
> also not sure why this is a p1. nothing is breaking, right?

If its just an extra unneeded permission, then yeah, its not a p1.

If you are missing permissions that you actually need, then its a p1 because there is some functionality that is not being tested (otherwise tests would be failing with permission errors).

**Comment by bparees** [comment]
> If you are missing permissions that you actually need, then its a p1 because there is some functionality that is not being tested (otherwise tests would be failing with permission errors).

right, i'm confident our test coverage would have exposed this.  the TI controller is only creating SARs, not trying to retrieve them.  So it definitely doesn't need this.

I'm less clear on whether someone cut+pasted the wrong group here and was trying to grant get/list/watch on some other resource, but again i'm pretty sure we'd be seeing failures if so.

**Comment by jim-minter** [comment]
Thanks for spotting @enj.  Not the best line of code I've ever written.  I think the line can just be removed.
