### ISSUE TITLE
oc rsync - copy from pod to pod

### ISSUE THREAD

**Issue by ramato-procon** [openshift/origin#17269]
Currently **oc rsync** only allows to copy files from/to local machine.
Please extend **oc rsync** to copy files between pods directly.

**Comment by juanvallejo** [comment]
Created feature card for this here: https://trello.com/c/vL2fsUOG

**Comment by juanvallejo** [comment]
Closing. This is not something we will do, as it could introduce unneeded complexity / potential bugs to the command. As it currently stands, copying from a pod, to local machine, back to a second pod is a viable user experience.

**Comment by tsega** [comment]
I disagree with your conclusion, a particular use case when copy files between environments e.g. PROD and TEST
