### ISSUE TITLE
Extended test documentation broken link

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17279]
https://github.com/openshift/origin/tree/master/test/extended#extended-tests-structure

`hack/test-extended/[group]/run.sh` is no more.

**Comment by kargakis** [comment]
@stevekuznetsov are you familiar with this move?

**Comment by stevekuznetsov** [comment]
Super old doc, I think we always use `test/extended/core.sh` as the entrypoint and have special ones for e.g. networking or conformance
