### ISSUE TITLE
I am accessing dashboard by http://dashboard-redhat-iot.apps.127.0.0.1.nip.io(From system in which test bed/openshift server is installed ), How to access it in Local area (From other PC))

### ISSUE THREAD

**Issue by kamran000** [openshift/origin#17273]

**Comment by pweil-** [comment]
For non-http traffic you can either try a passthrough route (assuming the traffic support SNI) or node port services.  Please see https://docs.openshift.org/latest/dev_guide/expose_service/index.html for more info
