### ISSUE TITLE
The oc cp doesn't work as one expects from help strings.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#17275]
The ``oc cp`` help strings say:

```
Copy files and directories to and from containers.

Usage:
  oc cp <file-spec-src> <file-spec-dest> [options]

Examples:
  # !!!Important Note!!!
  # Requires that the 'tar' binary is present in your container
  # image.  If 'tar' is not present, 'kubectl cp' will fail.

  # Copy /tmp/foo_dir local directory to /tmp/bar_dir in a remote pod in the
default namespace
  oc cp /tmp/foo_dir <some-pod>:/tmp/bar_dir

  # Copy /tmp/foo local file to /tmp/bar in a remote pod in a specific container
  oc cp /tmp/foo <some-pod>:/tmp/bar -c <specific-container>
```

If you create a local directory ``/tmp/foo_dir`` with files in it and run:

```
oc cp /tmp/foo_dir <some-pod>:/tmp/bar_dir
```

as help strings shows, you do not end up with a directory ``/tmp/bar_dir``. You instead end up with ``/tmp/foo_dir``. No where is a directory called ``bar_dir`` created in the container.

The only way you end up with ``/tmp/bar_dir`` with your files inside of it, is if you pre-create the target directory ``/tmp/bar_dir`` and then use the command:

```
oc cp /tmp/foo_dir <some-pod>:/tmp/bar_dir/
```

That is, you must also add a trailing slash to the target path.

The help strings are either wrong, or the implementation is just broken and doesn't behave in a sane way.

There is also a similar problem with copying a single file as well.

If have a local file called ``/tmp/foo`` and run:

```
oc cp /tmp/foo <some-pod>:/tmp/bar
```

the result is a file in the container called ``/tmp/foo``.

##### Version

```
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce

See above.

##### Current Result

Don't get target directory or file created as expected.

##### Expected Result

Would expect to see directory or file as given for the target in the command, not use the name from the source.

##### Additional Information

I have not even attempted to test copying files back from the container, that should be tested as well.

The ``oc cp`` command just appears to be broken. Better to use ``oc rsync`` as it at least works.

**Comment by juanvallejo** [comment]
These usability issues were addressed upstream recently:
https://github.com/kubernetes/kubernetes/pull/51215
https://github.com/kubernetes/kubernetes/pull/52465

Will be introduced to `oc` in the next rebase. A backport to older version of `oc` is not planned.
