### ISSUE TITLE
Builds sporadically fail with EOF

### ISSUE THREAD

**Issue by iocanel** [openshift/origin#17294]
Builds via `oc start-build` or via `fabric8 maven plugin` sporadically fail (false negative) in our rh-idev cluster with an EOF error.

From oc:
    
    oc start-build mybuild  --from-archive=/tmp/archive.tar.gz  

which results

     Uploading archive file "/tmp/archive.tar.gz" as binary input for the build ...
     Unable to connect to the server: EOF

 From fmp:

    mvn clean install fabric8:build

which results

    [INFO] F8: ==================================================================
    [INFO] F8: Starting S2I Java Build .....
    [INFO] F8: S2I binary build from fabric8-maven-plugin detected
    [INFO] F8: Copying binaries from /tmp/src/maven to /deployments ...
    [INFO] F8: ... done
    [INFO] F8: 
    [INFO] F8: Pushing image 172.30.39.149:5000/syndesis-ci/syndesis-rest:latest ...
    [INFO] F8: Pushed 0/23 layers, 0% complete
    [INFO] F8: Pushed 1/23 layers, 4% complete
    [INFO] F8: Pushed 2/23 layers, 9% complete
    [INFO] F8: Pushed 3/23 layers, 13% complete
    [INFO] F8: Pushed 4/23 layers, 17% complete
    [INFO] F8: Pushed 5/23 layers, 22% complete
    [INFO] F8: Pushed 6/23 layers, 26% complete
    [INFO] F8: Pushed 7/23 layers, 30% complete
    [INFO] F8: Pushed 8/23 layers, 35% complete
    [INFO] F8: Pushed 9/23 layers, 39% complete
    [INFO] F8: Pushed 10/23 layers, 43% complete
    [INFO] F8: Pushed 11/23 layers, 48% complete
    [INFO] F8: Pushed 12/23 layers, 52% complete
    [INFO] F8: Pushed 13/23 layers, 57% complete
    [INFO] F8: Pushed 14/23 layers, 61% complete
    [INFO] F8: Pushed 15/23 layers, 65% complete
    [INFO] F8: Pushed 16/23 layers, 70% complete
    [INFO] F8: Pushed 17/23 layers, 74% complete
    [INFO] F8: Pushed 18/23 layers, 78% complete
    [INFO] F8: Pushed 19/23 layers, 83% complete
    [INFO] F8: Pushed 20/23 layers, 87% complete
    [INFO] F8: Pushed 21/23 layers, 91% complete
    [INFO] F8: Pushed 22/23 layers, 96% complete
    [INFO] F8: Pushed 23/23 layers, 100% complete
    [INFO] F8: Push successful
    java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:60)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Upon log inspection I can see that the build succeeded after all.

##### Version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.rh-idev.openshift.com:443
openshift v3.6.173.0.49
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce

I can sporadically reproduce with this approach (via fmp):

    git clone https://github.com/syndesisio/syndesis-rest.git
    cd syndesis-rest
    mvn -B -U clean install fabric8:build

An other approach (via oc):

    git clone https://github.com/syndesisio/syndesis-ci.git
    cd syndesis-ci
    ./bin/build.sh --skip-tests --docker-username <docker user> --docker-email <docker email> --docker-password <docker password>

This does take a while, but is more consistent in reproducing.

##### Current Result
EOF error.

##### Expected Result
Successful build

##### Additional Information

**Comment by bparees** [comment]
this EOF appears to be coming from the fabric plugin+the client it uses, so the issue should be opened there.  ("java.io.EOF")

You didn't include any output from your "build.sh" reproducer, or the content of your "build.sh" script, so it's pretty hard to diagnose anything on that front.

**Comment by iocanel** [comment]
@bparees: Updated the description with output from the oc command. 

Regarding the build.sh script, it can be found at: https://github.com/syndesisio/syndesis-ci/blob/master/bin/build.sh

The image that consistently triggers the EOF is: https://github.com/syndesisio/syndesis-ci/tree/master/images/jenkins-slave-full-centos7

The build.sh script creates a buildconfig with a command like:

     cat Dockerfile | oc new-build --name=jenkins-slave-full-centos7 --dockerfile=- --to=docker.io/syndesis/jenkins-slave-full-centos7:latest --to-docker=true --strategy=docker 

and then kicks the build:

    oc start-build jenkins-slave-full-centos7 --from-archive=/tmp/archive.tar.gz -F

where archive.tar.gz is a tarball with the contents of  https://github.com/syndesisio/syndesis-ci/tree/master/images/jenkins-slave-full-centos7

**Comment by bparees** [comment]
@iocanel what you updated isn't the log from the build.

please run this and gist the output somewhere:

`oc start-build mybuild  --from-archive=/tmp/archive.tar.gz  --loglevel=8 --build-loglevel=8 -F`

**Comment by bparees** [comment]
also check your registry pod for errors in the logs corresponding to the time of your build failures.

**Comment by iocanel** [comment]
@bparees: Yes, the actual log, shows nothing of interest. The build is successful (that's what I mean by false negative). I'll use more verbose logging and update my post.

**Comment by coreydaley** [comment]
@iocanel any update in regard to the verbose logging post update?

**Comment by iocanel** [comment]
@coreydaley: I am afraid not!
Nothing of interest there and in the ended up working around the issue.

**Comment by coreydaley** [comment]
@iocanel i'm going to close this issue.  Feel free to re-open or open a new issue if you come up with anything.
