### ISSUE TITLE
SYN drop during HAproxy router reload does not apply when using IPv6

### ISSUE THREAD

**Issue by alexcern** [openshift/origin#17306]
Hello

When applying https://docs.openshift.org/latest/install_config/router/default_haproxy_router.html#preventing-connection-failures-during-restarts nothing happens if the router binds on IPv6 addresses (including dual-stack)

##### Version

```
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. `oc env dc/router ROUTER_IP_V4_V6_MODE=v4v6` (or `v6`)
2. Apply https://docs.openshift.org/latest/install_config/router/default_haproxy_router.html#preventing-connection-failures-during-restarts

It is not necessary to actually have an IPv6 stack, just setting the mode to v4v6 on an IP4-only node will reproduce the issue.

##### Current Result
Iptables is not modified during config reloads, SYNs are not dropped

##### Expected Result
IPtables is modified to drop SYNs during config reloads to prevent connection failures

##### Additional Information
It seems https://github.com/openshift/origin/blob/release-3.6/images/router/haproxy/reload-haproxy#L88  only matches IPv4 bindings.

Something like this appears to work with both IPv4 and IPv6 on the generated haproxy config file:
```
grep -E --only-matching '^\s*bind\s+:(::)?[[:digit:]]+\w' "$config_file" | sed -e 's/:::/:/' | cut …
```

Though this would still only drop SYNs for TCP4. It may be needed to explicitly drop TCP6 SYNs as well.

**Comment by knobunc** [comment]
This is obsolete with OpenShift 3.9.  There we have haproxy 1.8 and take advantage of the seamless reloads.
