### ISSUE TITLE
Dead container cleaning

### ISSUE THREAD

**Issue by yangpeng14** [openshift/origin#17318]
[provide a description of the issue]

##### Version
version 1.5.1

##### Steps To Reproduce
1.Issues
$ docker ps -a | grep Dead

9cffacc405ff        openshift/origin-pod:v1.5.1                                                     "/pod"                   5 days ago          Dead                                          k8s_POD.50d4dca2_smartstudy-backend-test-3766556469-vjztd_c-test_43e474d7-c511-11e7-8974-00163e305e10_522451be
b358ab83c7eb        openshift/origin-pod:v1.5.1                                                     "/pod"                   5 days ago          Dead                                          k8s_POD.50d4dca2_zhikewang-test-2442923192-wn3x6_c-test_9635384f-c503-11e7-8974-00163e305e10_ef32ee44
8ff265b6f84f        openshift/origin-pod:v1.5.1                                                     "/pod"                   6 days ago          Dead

2. Excuse me, how do these dead containers clean up

##### Current Result
You can't remove these containers using docker rm

##### Expected Result
These dead containers need to be cleaned out

##### Additional Information
null

**Comment by pweil-** [comment]
Garbage collection is performed on the node and is typically run every minute.  This is configurable with parameters described in https://docs.openshift.org/latest/admin_guide/garbage_collection.html (which also describes how something becomes eligible for collection). 

It doesn't look like you've surpassed `maximum-dead-containers-per-container` or `maximum-dead-containers`

**Comment by yangpeng14** [comment]
There are already 13 Dead containers on node, and the following parameters are set, but you can't clear the Dead.

  minimum-container-ttl-duration:
  - '60s'
  maximum-dead-containers-per-container:
  - '2'
  maximum-dead-containers:
  - '2'

**Comment by pweil-** [comment]
Thanks for the update @yangpeng14 I'll reopen this so folks can take a closer look.

**Comment by sjenning** [comment]
@aveshagarwal PTAL

**Comment by yangpeng14** [comment]
I've found the reason for this, because the fluentd service mounts the container log directory (/var/log/containers /), because the fluentd service USES the dead container directory, resulting in the container being unreleased. But now the new question comes, why the dead container, the fluentd service why not release the dead container directory?
