### ISSUE TITLE
Error trying to set a role in a user starting with -

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#17328]
I have a user with following name: __-pepe__ (not the real one, but similar has been provided)

I want to add admin permission to the user, so I do:

```
$ oc policy add-role-to-user admin '-pepe'
Error: unknown shorthand flag: 'p' in -pepe
```

I can add the permission through the UI without a problem.

![image](https://user-images.githubusercontent.com/78350/32853103-86cf64d4-ca3a-11e7-9306-bb4dd1cab15a.png)

##### Version
1.7.0-rc.0

**Comment by simo5** [comment]
When a user has a username starting in - then that string get's interpreteed as a command line option.
For that case you have to do cmd arg "escaping" by prepending the standard termination of cmd line options:
use:
oc policy add-role-to-admin admin -- -pepe

**Comment by simo5** [comment]
Not a bug, work as expected

**Comment by jorgemoralespou** [comment]
@simo5, where can I find that in the documentation? If nowhere, I would say it's still a bug.

**Comment by simo5** [comment]
It's the standard way in all unix commands with long options ever.
