### ISSUE TITLE
Tweak resync interval in build controller rather than in build integration test

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#17322]
This https://github.com/mfojtik/origin/blob/master/test/common/build/controllers.go#L40 means that when the integration test fail to meet the expectation (like build pod is not removed/etc),  the integration will wait 6 minutes until it give up.

I believe this is due to reconcile period in build controller and 6 minutes allows it to run. I think this is wrong and we should tweak the reconcile period in the build controller instead and decrease this timeout.

**Comment by bparees** [comment]
We'd have to *decrease* the reconcile period (make it reconcile more frequently) to do what you're describing.  We're not going to do that.

(If anything we want to increase those periods, which will be a problem for this test also)

also if we're routinely having these tests fail and hit the 6 minute timeout, that is what should be fixed.

All that said, i'm not even entirely clear on the need for reconciliation here...I don't know why we have a test that depends on reconciliation to catch an event and so perhaps the test itself should be restructured to not be dependent on that (unless reconciliation is what it is testing).

**Comment by bparees** [comment]
i'm not aware of any issues w/ this test failing, the watch timeout might be unnecessarily high but i'm not interested in refactoring something that's working and not obviously wrong.

in cases where it does fail, 6 minutes to hit a failure isn't egregious (and again, if it starting failing, it needs to be fixed, not just have the "timeout before it fails" reduced)
