### ISSUE TITLE
error: build error: devmapper: Error mounting /dev/mapper/...

### ISSUE THREAD

**Issue by bparees** [openshift/origin#17330]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17094/test_pull_request_origin_extended_builds/634/

docker build failed:
```
---->
Step 1 : FROM centos/ruby-22-centos7:latest
 ---> 2143e48226c2
Step 2 : USER root
 ---> Running in cd445b51553f
 ---> ae58eb778691
Removing intermediate container cd445b51553f
Step 3 : RUN yum -y install expect
 ---> Running in e4cc54793540
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirror.cogentco.com
 * extras: reflector.westga.edu
 * updates: mirror.cs.vt.edu
Resolving Dependencies
--> Running transaction check
---> Package expect.x86_64 0:5.45-14.el7_1 will be installed
--> Processing Dependency: libtcl8.5.so()(64bit) for package: expect-5.45-14.el7_1.x86_64
--> Running transaction check
---> Package tcl.x86_64 1:8.5.13-8.el7 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
 Package         Arch            Version                    Repository     Size
================================================================================
Installing:
 expect          x86_64          5.45-14.el7_1              base          262 k
Installing for dependencies:
 tcl             x86_64          1:8.5.13-8.el7             base          1.9 M
Transaction Summary
================================================================================
Install  1 Package (+1 Dependent package)
Total download size: 2.1 M
Installed size: 4.9 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                               10 MB/s | 2.1 MB  00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:tcl-8.5.13-8.el7.x86_64                                    1/2 
  Installing : expect-5.45-14.el7_1.x86_64                                  2/2 
  Verifying  : 1:tcl-8.5.13-8.el7.x86_64                                    1/2 
  Verifying  : expect-5.45-14.el7_1.x86_64                                  2/2 
Installed:
  expect.x86_64 0:5.45-14.el7_1                                                 
Dependency Installed:
  tcl.x86_64 1:8.5.13-8.el7                                                     
Complete!
 ---> 5cbdd0393036
Removing intermediate container e4cc54793540
Step 4 : RUN echo "root:redhat" | chpasswd
 ---> Running in a7151bce5647
 ---> d103b79ea2e5
Removing intermediate container a7151bce5647
Step 5 : USER 1001
 ---> Running in 0b3f72281da8
 ---> b32b97288061
Removing intermediate container 0b3f72281da8
Step 6 : COPY ./adduser /usr/libexec/s2i/
 ---> dca45971feab
Removing intermediate container be36da1f72ad
Step 7 : COPY ./assemble /usr/libexec/s2i/
 ---> 31b086153888
Removing intermediate container 8158ae31f784
Step 8 : ENV "OPENSHIFT_BUILD_NAME" "rootable-ruby-1" "OPENSHIFT_BUILD_NAMESPACE" "extended-test-build-s2i-dropcaps-85kbw-p9cnc"
 ---> Running in 07749c297bb5
error: build error: devmapper: Error mounting '/dev/mapper/docker-202:2-92453254-3f6e632f403acf8226bf82a67db75aff2104d359dc5dc9c756ce2f0b72911b46' on '/var/lib/docker/devicemapper/mnt/3f6e632f403acf8226bf82a67db75aff2104d359dc5dc9c756ce2f0b72911b46': invalid argument
<----end of log for "rootable-ruby-1-build"
```

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/280/testReport/junit/(root)/Extended/_Feature_Builds__Slow__extremely_long_build_bc_names_are_not_problematic__build_with_long_names_delete_builds_with_long_names_without_collateral_damage__Suite_openshift_/

**Comment by bparees** [comment]
something has regressed, i'm seeing this in more and more failures.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17314/test_pull_request_origin_extended_builds/662/

**Comment by bparees** [comment]
@derekwaynecarr fyi.

**Comment by bparees** [comment]
@jwhonce @derekwaynecarr I need someone to at least triage this bug.

https://ci.openshift.redhat.com/jenkins//job/test_branch_origin_extended_builds/285/testReport/junit/(root)/Extended/_Feature_Builds__Slow__incremental_s2i_build__Building_from_a_template_should_create_a_build_from___tmp_fixture_testdata_dir912815358_test_extended_testdata_builds_incremental_auth_build_json__template_and_run_it__Suite_openshift_/

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/285/testReport/junit/(root)/Extended/_Feature_Builds__Slow__completed_builds_should_have_digest_of_the_image_in_their_status__Docker_build_started_with_log_level__5_should_save_the_image_digest_when_finished__Suite_openshift_/

**Comment by bparees** [comment]
@jim-minter fyi since you're watching the extended tests this sprint.

**Comment by runcom** [comment]
Could you guys please provide output of docker version and info subcommands, lvs, dmsetup table and status, and journald entries for the period of failure. Thanks!

**Comment by jwhonce** [comment]
@runcom What exists for that period will be under the 'S3 Artifacts' tab on the left-hand side of screen.

docker info and journal entries are there.

**Comment by jim-minter** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/287/testReport/junit/(root)/Extended/_Feature_Builds__Slow__completed_builds_should_have_digest_of_the_image_in_their_status__Docker_build_started_with_log_level__5_should_save_the_image_digest_when_finished__Suite_openshift_/
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/288/testReport/junit/(root)/Extended/_Feature_Builds__Slow__completed_builds_should_have_digest_of_the_image_in_their_status__Docker_build_started_with_log_level__5_should_save_the_image_digest_when_finished__Suite_openshift_/

**Comment by jim-minter** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/291/testReport/junit/(root)/Extended/_Feature_Builds__Slow__build_can_have_Docker_image_source__creating_a_build_with_an_input_source_image_and_s2i_strategy_should_resolve_the_imagestream_references_and_secrets__Suite_openshift_/
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/292/testReport/junit/(root)/Extended/_Feature_Builds__Slow__can_use_build_secrets__build_with_secrets_should_contain_secrets_during_the_docker_strategy_build__Suite_openshift_/

**Comment by bparees** [comment]
This is flaking a huge number of our build tests and resulting in excess triage work having to be done by our team.

**Comment by rhvgoyal** [comment]
Is there a way to reproduce this problem. Right now only error message I see is "invalid argument" and that  really does not tell much in terms of what went wrong.

So that means we need to narrow it down. Is there a docker file which I can take and run on my VM and reproduce this?

Is the storage still fine in the system after the error occurs or one needs to reset storage to get going again.

**Comment by jim-minter** [comment]
I don't have a simplified way to reproduce the problem but it is happening on pretty much every test_branch_origin_extended_builds job, so it is hardly rare.

**Comment by rhvgoyal** [comment]
If we want to solve this issue, we will have to narrow it down. Otherwise I don't see how to make progress on this. So somebody needs to spend some time and try to reproduce it on smaller cluster and narrow it down.

**Comment by bparees** [comment]
@rhvgoyal You can add any debug/system information gathering you want to the extended test framework and repeatedly run the test jobs against your debug PR.

**Comment by rhvgoyal** [comment]
@bparees Sorry, I don't know enough about openshift to be able to do that. I will expect somebody in openshift team to narrow it down for me.

**Comment by bparees** [comment]
> @bparees Sorry, I don't know enough about openshift to be able to do that. I will expect somebody in openshift team to narrow it down for me.

I don't consider that an acceptable expectation.  The containers team is part of the openshift team.  @jwhonce @derekwaynecarr

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17662/test_pull_request_origin_extended_conformance_gce/12607/

**Comment by coreydaley** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/304/testReport/junit/(root)/Extended/_Feature_Builds__Conformance__build_without_output_image__building_from_templates_should_create_an_image_from_a_docker_template_without_an_output_image_reference_defined__Suite_openshift_conformance_parallel_/

**Comment by coreydaley** [comment]
@rhvgoyal Do you have any updates on resolving this issue?

**Comment by derekwaynecarr** [comment]
@jwhonce -- what do you think about also moving to overlay in this test environment?

**Comment by coreydaley** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/306/testReport/junit/(root)/Extended/_Feature_Builds__Slow__starting_a_build_using_CLI__start_build_test_context_binary_builds_should_reject_binary_build_requests_without_a___from_xxxx_value__Suite_openshift_/

**Comment by tnozicka** [comment]
This is flaking a lot. We need to fix it asap or move to overlay2.

I don't feel this is getting enough attention being P0 :/

**Comment by rhvgoyal** [comment]
A fix has been backported. We just need to make sure appropriate build is being used.

https://github.com/projectatomic/docker/pull/288

**Comment by tnozicka** [comment]
thanks; @stevekuznetsov is this something you can verify?

**Comment by stevekuznetsov** [comment]
We're running this in CI:

```
$ rpm -q docker
docker-1.12.6-68.gitec8512b.el7.x86_64
```

**Comment by rhvgoyal** [comment]
BTW, make sure kernel is atleast rhel7.4. This fix is more of a work around for the leaked mount issue and associated SELinux problems and works only if kernel is atleast rhel 7.4.

**Comment by rhvgoyal** [comment]
I think this will require `docker-1.12.6-71.git3e8e77d.el7.x86_64.rpm`

**Comment by calston** [comment]
We have run into this issue on the enterprise version, which effectively renders the entire S2I feature set broken. 

How are people now running around like their hair is on fire?

**Comment by stevekuznetsov** [comment]
@calston this is an intermittent and annoying but ultimately re-tryable error on our end. Do you have a 100% reproducer?

**Comment by calston** [comment]
@stevekuznetsov Given the totality of the error message it may be up to a higher power or quantum mechanics to decide what we actually have

```
error: Execution of post execute step failed
--
  | error: build error: building demo/nodejs-mongodb-example-8:50986bc8 failed when committing the image due to error: Error response from daemon: {"message":"devmapper: Error mounting '/dev/mapper/docker-253:1-192453-2b4b154f295b028f345c0cee3c726e9a2b1bf7b44cd68a26bae6ba7de82f751b' on '/var/lib/docker/devicemapper/mnt/2b4b154f295b028f345c0cee3c726e9a2b1bf7b44cd68a26bae6ba7de82f751b': invalid argument"}
```

**Comment by sosiouxme** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17773/test_pull_request_origin_extended_conformance_install/5224/ looks like https://github.com/openshift/origin/issues/17902 which refers here

**Comment by stevekuznetsov** [comment]
@rhvgoyal @jwhonce do we have any updates here?

**Comment by rhvgoyal** [comment]
@stevekuznetsov Updates are already there in comments. Please check.

**Comment by stevekuznetsov** [comment]
Ah, sorry, missed that -- do you know when that pacakge should be available in the RHEL 7 Next compose?

**Comment by calston** [comment]
This happens always when using the XFS based thinpool docker configuration produced by docker-storage-setup. Reverting back to overlay2 doesn't produce the issue anymore

**Comment by smarterclayton** [comment]
We've seen this happening in `docker-1.12.6-68.gitec8512b.el7.x86_64` in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18133/test_pull_request_origin_extended_conformance_install/5693/

**Comment by stevekuznetsov** [comment]
We are waiting to tag in `docker-1.12.6-71.git3e8e77d.el7.x86_64.rpm` - the job tagging it in is broken, @michaelgugino is working on fixing it in https://github.com/openshift/aos-cd-jobs/pull/999

**Comment by jim-minter** [comment]
@stevekuznetsov any update?

**Comment by stevekuznetsov** [comment]
The job trying to push this up is [here](https://buildvm.openshift.eng.bos.redhat.com:8443/job/ci/job/package-dockertested/). It has flaked in the last four runs on conformance testing. If we need this faster, we can tag the new `docker` RPM through manually but in the past that has broken the entire Origin queue, hence the testing. If y'all feel like we need to manually tag this in, please let me know, but I will also need a commitment from one or more people to monitor the queue and ensure that regressions are caught immediately and we can revert quickly.

**Comment by bparees** [comment]
looks like that job is about to fail again.  What caused the breakage last time? The rpm was actually bad?

**Comment by bparees** [comment]
btw it's going to fail because of the image GC problem:
```
  Normal   BackOff                4m (x60 over 19m)  kubelet, ip-172-18-7-2.ec2.internal  Back-off pulling image "openshift/origin-deployer:8b81ebd"
```
so if we could get the storage issue fixed, the job might have passed.

**Comment by stevekuznetsov** [comment]
The job was broken before because the installer entrypoints were changed but that job was not updated. Hmm. I'll see if I can get the storage stuff tackled today.

**Comment by stevekuznetsov** [comment]
The AMIs now have `docker-1.12.6-71.git3e8e77d.el7`

**Comment by bparees** [comment]
closing in the assumption this is supposed to be fixed by that level.  will reopen as needed.

**Comment by smarterclayton** [comment]
Linked a run that failed that started at 2018-01-25 21:48 EST.  Did that include the fix?

**Comment by smarterclayton** [comment]
It's probably not in the GCP image if the change didn't make it to the ops mirror or another prerelease location (tagged into centos7).

**Comment by stevekuznetsov** [comment]
We're pushing Docker into the `dockertested` repo as we always have been. What do you mean?

**Comment by smarterclayton** [comment]
https://github.com/openshift/release/pull/570 will merge after the overlay fix merges

**Comment by sosiouxme** [comment]
[Appears to still be broken](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18641/test_pull_request_origin_extended_conformance_install/8624/)
