### ISSUE TITLE
"cache" issues in web console cause weird behaviors

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1733]
I have noticed a lot of issues with the console that I can only attribute to "caching". What I mean by this is that, for example, if I click the "OpenShift Origin" logo at the top, I am taken to the project list, but it displays old information.

It seems that to force an actual reload of a page I can't click anything. I have to use F5 or re-enter the URL in the browser and hit enter.

I can't really nail down all the instances where this happens, but I'll try to capture them in this issue.

**Comment by jwforres** [comment]
This would only be an issue on the projects page right now, we use websockets everywhere else to get constantly up to date information.  We didn't want to watch on projects.  The fact that clicking on the origin logo doesn't reload the page when you are already on that page is a bug and probably related to the fact that the URL doesnt change so it doesnt trigger angular to re-render anything.

**Comment by spadgett** [comment]
We're already watching projects in nav.js to update the projects dropdown.

```
        $scope.$watch("projects", function(projects) {
          select.empty();
          updateOptions(projects);
          select.selectpicker('refresh');
        });
```

I'm not clear on the difference here. It seems like we should watch in both places or neither if there's a performance concern. @liggitt ?

**Comment by derekwaynecarr** [comment]
There is no ability to WATCH projects since its auth-filtered, you have to poll LIST.

**Comment by liggitt** [comment]
`$scope.$watch` is an angular subscription to the `projects` field. We're only making `list` calls on projects:

```
assets/app/scripts/controllers/project.js:
   54:       DataService.list("projects", $scope, function(projects) {

assets/app/scripts/controllers/projects.js:
   18:       DataService.list("projects", $scope, function(projects) {
```

**Comment by liggitt** [comment]
We need to make sure that clicking the logo while already on the projects page makes another API call to get the projects again.
