### ISSUE TITLE
No Metrics images for v3.8.0-alpha.0

### ISSUE THREAD

**Issue by matzew** [openshift/origin#17347]
doing `oc cluster up --metrics --version=v3.8.0-alpha.0`
bring up the cluster, but in the `openshift-infra` infro project, I am getting errors, because there are no images for `v3.8.0-alpha.0` on the different metric containers, like:

https://hub.docker.com/r/openshift/origin-metrics-cassandra/tags/

These three images do lack a matching v3.8.0-alpha.0 tag:

* origin-metrics-heapster:v3.8.0-alpha.0
* origin-metrics-hawkular-metrics:v3.8.0-alpha.0
* origin-metrics-cassandra:v3.8.0-alpha.0
* openshift/origin-ansible:v3.8.0-alpha.0 

##### Version
v3.8.0-alpha.0

##### Steps To Reproduce
1. oc cluster up --metrics --version=v3.8.0-alpha.0
2. go the the infra project, and see that images can not be pulled

##### Current Result
no images available - no images get pulled

Getting this error:
```
Failed to pull image "openshift/origin-ansible:v3.8.0-alpha.0": rpc error: code = 2 desc = manifest for docker.io/openshift/origin-ansible:v3.8.0-alpha.0 not found
```

##### Expected Result
images are available on dockerhub, hence it would pull

**Comment by pweil-** [comment]
consolidating to https://github.com/openshift/origin/issues/17676
