### ISSUE TITLE
How to run oc commands in Raspberry Pi 3

### ISSUE THREAD

**Issue by kamran000** [openshift/origin#17346]
Tried to deploy Linux version of openshift client tool but getting following error:
bash: ./oc: cannot execute binary file: Exec format error

**Comment by xiaods** [comment]
rasp is arm platform, you need build again on it platform.

**Comment by kamran000** [comment]
@xiaods thanks, where can i find source of openshift client tool, as this code is complete openshift origin, I just need to run oc commands, need to access remote openshift origin server from pi

**Comment by xiaods** [comment]
the oc source code is builtin in origin source code. you can make release to rebuild oc binary.

**Comment by kamran000** [comment]
@xiaods thanks
