### ISSUE TITLE
Warning		FailedScheduling	0/1 nodes are available: 1 NodeUnderDiskPressure.

### ISSUE THREAD

**Issue by bparees** [openshift/origin#17352]
I don't know if it's a legitimate warning or something broken, but we're seeing a lot of test fail because pods don't get scheduled due to this error.

So either we need more disk space on our instances, or we need to see why the nodes are confused about their capacity.

```
Name:		test-pod-fbb1307f-ca8c-11e7-9fec-0ee2507ca112
Namespace:	extended-test-s2i-usage-hmpwm-sdggx
Node:		ip-172-18-5-103.ec2.internal/172.18.5.103
Start Time:	Thu, 16 Nov 2017 05:19:21 +0000
Labels:		name=test-pod-fbb1307f-ca8c-11e7-9fec-0ee2507ca112
Annotations:	openshift.io/scc=restricted
Status:		Pending
IP:		
Containers:
  test:
    Container ID:	
    Image:		openshift/perl-516-centos7
    Image ID:		
    Port:		<none>
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-sjl4r (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-sjl4r:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-sjl4r
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	region=infra
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From					SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----					-------------	--------	------			-------
  15m		10m		21	default-scheduler					Warning		FailedScheduling	0/1 nodes are available: 1 NodeUnderDiskPressure.
  9m		9m		1	default-scheduler					Normal		Scheduled		Successfully assigned test-pod-fbb1307f-ca8c-11e7-9fec-0ee2507ca112 to ip-172-18-5-103.ec2.internal
  9m		9m		1	kubelet, ip-172-18-5-103.ec2.internal			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-sjl4r" 
  9m		4m		25	kubelet, ip-172-18-5-103.ec2.internal			Warning		FailedCreatePodSandBox	Failed create pod sandbox.
```

@stevekuznetsov @smarterclayton @sjenning

**Comment by smarterclayton** [comment]
We have pretty big instances, this could indicate that we're downloading
too much.  Easy way to do it is to ssh into a running test and observe disk
usage.

**Comment by bparees** [comment]
> We have pretty big instances, this could indicate that we're downloading too much.

too much what? images?  is this warning about docker storage or general disk storage? or both?

**Comment by sjenning** [comment]
There are a few flags in the kubelet that handle this

https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource

```
--eviction-soft
--eviction-soft-grace-period
--eviction-hard
--eviction-minimum-reclaim
```

Basically if the hard threshold is exceed OR the soft threshold is exceeded for more than a grace-period duration, eviction occurs and node conditions are set.

`eviction-minimum-reclaim` controls the "chunk" the will attempt to be reclaimed once a threshold is exceeded.

`minimum-image-ttl-duration` might be excluding all images from GC consideration if they are being pulled in a short period of time.

There should be messages in the node log if it is unable to free resources in response to reaching a threshold.  Something like "attempted to free X, but could only free Y"

@derekwaynecarr can you check my understanding here

**Comment by bparees** [comment]
@sjenning based on the message `0/1 nodes are available: 1 NodeUnderDiskPressure.` is this imagefs or nodefs?  It certainly sounds more like the latter.

**Comment by stevekuznetsov** [comment]
What does `generated/filesystem.info` show you in those jobs?

**Comment by smarterclayton** [comment]
Oh wait, this is ec2, not GCE.  GCE is 150gb disks.  I bet ec2 is a lot
smaller.

**Comment by sjenning** [comment]
@bparees the same node condition is set for either so I really couldn't say

**Comment by stevekuznetsov** [comment]
We harvest disk info for this exact reason. @bparees can you link some jobs with this failure?

**Comment by bparees** [comment]
@stevekuznetsov i will do so next time i see a failure like this.

**Comment by sjenning** [comment]
@stevekuznetsov what are the disk sizes for /var/lib/docker on these  test instances?

**Comment by sjenning** [comment]
ah so it is still using devicemapper.  35G seems like it should be enough.  though i'm not sure what all is being done on the test instances.

**Comment by stevekuznetsov** [comment]
We had to bump to 35G since some of the image publishing jobs were using up the whole store. I don't think test jobs come close. however, it's simple to verify if we see any of these types of failures in the future -- every job has as an artifact `generated/filesystem.info` where this will be stored.

**Comment by stevekuznetsov** [comment]
Should be fixed now.

/close
