### ISSUE TITLE
Origin GCE e2e Jobs Broken -- No Nodes

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#17361]
None of our GCE clusters are bringing up _any_ nodes. We start the instances but the `origin-node.service` on them includes only:

```
-- No entries --
```

The installer does not seem to break on this. Perhaps this is a node scaling group issue?

/kind bug
/cc @deads2k @bparees @liggitt @sdodson 
/assign @smarterclayton @kwoodson

**Comment by stevekuznetsov** [comment]
Maybe addressed by https://github.com/openshift/openshift-ansible/pull/6167 ?

**Comment by liggitt** [comment]
that only affects the rebase, not master

**Comment by stevekuznetsov** [comment]
@smarterclayton also massively suspect how the [`zz_origin_gce_image`](https://ci.openshift.redhat.com/jenkins/job/zz_origin_gce_image/577/) job passed to push this out

**Comment by stevekuznetsov** [comment]
Or did we get broken by a new push of node base image?

**Comment by stevekuznetsov** [comment]
We are running with https://github.com/openshift/openshift-ansible/commit/6cfc4a162cff36bb2ba7bb482135060e76c5d5a1 in the `openshift/origin-gce:latest` image

**Comment by smarterclayton** [comment]
```
Could not find or access '/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/initialize_groups.yml'
Build step 'Execute shell' marked build as failure
```

is why we haven't picked up a new image.  I suspect infra problems first, then changes to release / origin.

**Comment by smarterclayton** [comment]
Broke between:

```
11469 2017-11-16 08:00 EST took 18m35s
11468 2017-11-16 07:57 EST took 2h19m
11467 2017-11-16 07:56 EST took 54m38s
```

Who made changes at 8am yesterday?

**Comment by smarterclayton** [comment]
This was the last passing branch build:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/test_branch_origin_extended_conformance_gce/1943/

I think someone merged something to master that broke us at 7:56 AM EST yesterday

**Comment by smarterclayton** [comment]
Nothing has passed since #17344 and @mfojtik merged

**Comment by liggitt** [comment]
that reverted to master to be identical to 11235db179aab5be728b3c8219996c9e730c1fce which was bot-merged

**Comment by stevekuznetsov** [comment]
How are we expecting changes to Origin to have caused this? I'm not even seeing the `origin-node.service` attempt to be started by `systemd` on those nodes. Not like it's failing to come up.

**Comment by sdodson** [comment]
> Could not find or access '/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/initialize_groups.yml'
> Build step 'Execute shell' marked build as failure

Is a change in openshift-ansible that was made recently, we need to update origin-gce for this change I guess.

**Comment by stevekuznetsov** [comment]
Right but that change is blocking _new_ origin-gce releases, so it's not the proximal change here.

**Comment by smarterclayton** [comment]
Gce uses a different base image, which wasn’t updated (or rather, someone
would have had to do that without me noticing).

On Nov 17, 2017, at 12:33 PM, Steve Kuznetsov <notifications@github.com>
wrote:

How are we expecting changes to Origin to have caused this? I'm not even
seeing the origin-node.service attempt to be started by systemd on those
nodes. Not like it's failing to come up.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/17361#issuecomment-345310520>,
or mute the thread

**Comment by smarterclayton** [comment]
gcloud is now returning an error trying to update the project metadata on GCE, which prevents bootstrapping from working.  Investigating whether there is an updated gcloud available from the package manager, or whether i'll have to hack it up.

**Comment by smarterclayton** [comment]
https://issuetracker.google.com/issues/69409423

**Comment by stevekuznetsov** [comment]
Not blocking the queue any longer.

**Comment by liggitt** [comment]
resolved
