### ISSUE TITLE
NFS shares and running containers as Openshift project owner

### ISSUE THREAD

**Issue by woopla** [openshift/origin#17370]
Hello,

We have large NFS shares with user-created data, using permissions to restrict access. I'd like for the users to be able to create a project on Openshift and run an application on it that has access to that data.

I could put all the users in the `anyuid` or `nonroot` SCCs, but that's more dangerous than it needs :) I don't see a feature to have the containers run as the same uid/gid of the project creator/owner. Authentication is done through LDAP, and their uid/gid is in there so the info could be used.

Is there currently a way to do this, or are you planning to? I think it's pretty much needed for entreprise users using shared storage that's also in use by programs outside of Openshift.

Version info:
```
c v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://<host>:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

Thanks,

Clément

**Comment by xiaods** [comment]
hi, could you please share your step, let me familiar your context.

**Comment by woopla** [comment]
Hi @xiaods  sorry about the delay. Let's say I'm user1 on Linux. I'm also a member of group1. I have access to a large NFS share called `/data` that is available to all members of group1.

It would be great that all the projects that I create on Origin run as user1 (the user I'm logging  in through LDAP on Origin), because then I'd have access to this /data NFS share, without needing the Origin admin to add me to the `anyuid` or `nonroot` SCCs.

Is that more clear?

Thanks,

Clément

**Comment by woopla** [comment]
@xiaods I do already have storage used by tools external to Origin. Now I want to access that storage from pods running on Origin, without creating a PV/PVC combination.

This part: https://docs.openshift.com/container-platform/3.6/install_config/persistent_storage/persistent_storage_nfs.html#nfs-supplemental-groups, combined with an SCC that has hostmount set to true, might do the trick, right?

Thanks,

Clément
