### ISSUE TITLE
Openshift orign: Global template library is missing

### ISSUE THREAD

**Issue by garyyang6** [openshift/origin#17371]
[provide a description of the issue]
I installed openshift-origin-server-v3.6.1-008f2d5-linux-64bit.tar.gz at CentOS 7. The global template library is missing when I logon to the web console and create project.
##### Version
[provide output of the `openshift version` or `oc version` command]

./openshift version
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
etcd 3.2.1

 oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64

##### Steps To Reproduce
1. [step 1]
Download openshift origin at https://github.com/openshift/origin/releases/download/v3.6.1/openshift-origin-server-v3.6.1-008f2d5-linux-64bit.tar.gz. Install it at CentOS 7
2. [step 2]
Logon to https://localhost:8443. Create a project. But, the global template library is not there.

##### Current Result
Glocal template liburary is missing.
##### Expected Result
The Browse Catalog should show global template library.
Please see    https://docs.openshift.org/latest/dev_guide/templates.html#uploading-a-template at "2. Select a template from the list of templates in your project, or provided by the global template library:"

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by pweil-** [comment]
Hi @garyyang6.  The template library is something the administrator must set up by installing the templates into the shared `openshift` namespace.

Info about using the quickstart templates can be found [here](https://docs.openshift.org/latest/dev_guide/templates.html#using-the-instantapp-templates)

Info about the installation process for default templates can be found in the [installation and configuration guide](https://docs.openshift.org/latest/install_config/imagestreams_templates.html#install-config-imagestreams-templates)

**Comment by garyyang6** [comment]
@pweil- I read the "Installation and configuration guide". I got "Permission denied" and "unreachable" error. I run the script at docker01.works.com as root. But, it complains "Permission denied" and "unreachable" at docker01.works.com. I think it is a bug.

ansible-playbook  -vvv ~/openshift-ansible/playbooks/byo/config.yml
........
TASK [Gathering Facts] ******
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<docker01.works.com> ESTABLISH SSH CONNECTION FOR USER: root
<docker01.works.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/f94ef48be1 docker01.works.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<docker02.works.com> ESTABLISH SSH CONNECTION FOR USER: None
<docker02.works.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/0ab4c283da docker02.works.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<docker01.works.com> (255, '', 'Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n')
fatal: [docker01.works.com]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
}

Here are the details. 
I login as root at docker01.works.com. As root, I am able to ssh to docker02.works.com without password. Also, as root, at docker02.works.com, I am able to ssh to docker01.works.com without password. But, I got Permission denied when I run ansible-playbook as root at docker01.works.com.

cat /etc/ansible/hosts
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

openshift_deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
docker01.works.com

# host group for etcd
[etcd]
docker02.works.com

# host group for nodes, includes region info
[nodes]
docker01.works.com

**Comment by pweil-** [comment]
@garyyang6 can you confirm you can ssh from docker01.works.com to itself with no password too?

**Comment by garyyang6** [comment]
You are right. I was not able to ssh from docker01.works.com to itself. I fixed it. But, I got new errors.

fatal: [docker01.works.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "allow_downgrade": false, 
            "conf_file": null, 
            "disable_gpg_check": false, 
            "disablerepo": null, 
            "enablerepo": null, 
            "exclude": null, 
            "install_repoquery": true, 
            "installroot": "/", 
            "list": null, 
            "name": [
                "origin-clients"
            ], 
            "security": false, 
            "skip_broken": false, 
            "state": "present", 
            "update_cache": false, 
            "validate_certs": true
        }
    }, 
    "msg": "Repository 'puppet-deps' is missing name in configuration, using id\nRepository base is listed more than once in the configuration\nRepository epel is listed more than once in the configuration\nRepository updates is listed more than once in the configuration\n\n\nTransaction check error:\n  file /usr/bin/kubectl from install of origin-clients-3.6.1-1.0.008f2d5.x86_64 conflicts with file from package kubectl-1.8.4-0.x86_64\n\nError Summary\n-------------\n\n", 
    "rc": 1, 
    "results": [
        "Loaded plugins: fastestmirror, langpacks\nLoading mirror speeds from cached hostfile\n * base: mirrors.cmich.edu\n * extras: linux.mirrors.es.net\n * updates: mirror.compevo.com\nResolving Dependencies\n--> Running transaction check\n---> Package origin-clients.x86_64 0:3.6.1-1.0.008f2d5 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package          Arch     Version              Repository                 Size\n================================================================================\nInstalling:\n origin-clients   x86_64   3.6.1-1.0.008f2d5    centos-openshift-origin    41 M\n\nTransaction Summary\n================================================================================\nInstall  1 Package\n\nTotal download size: 41 M\nInstalled size: 267 M\nDownloading packages:\nRunning transaction check\nRunning transaction test\n"
    ]
}
	to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP **********************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0   
docker01.works.com : ok=82   changed=3    unreachable=0    failed=1   
docker02.works.com : ok=96   changed=5    unreachable=0    failed=0   


INSTALLER STATUS ****************************************************************************************************************************************************
Initialization             : Complete (0:02:21)
Health Check               : Complete (0:00:52)
etcd Install               : Complete (0:01:40)
Master Install             : In Progress (0:01:19)
	This phase can be restarted by running: playbooks/byo/openshift-master/config.yml



Failure summary:


  1. Hosts:    docker01.works.com
     Play:     Create OpenShift certificates for master hosts
     Task:     Install clients
     Message:  Repository 'puppet-deps' is missing name in configuration, using id
               Repository base is listed more than once in the configuration
               Repository epel is listed more than once in the configuration
               Repository updates is listed more than once in the configuration
               
               
               Transaction check error:
                 file /usr/bin/kubectl from install of origin-clients-3.6.1-1.0.008f2d5.x86_64 conflicts with file from package kubectl-1.8.4-0.x86_64
               
               Error Summary
               -------------
               
I removed  /usr/bin/kubectl
ls /usr/bin/kubectl 
ls: cannot access /usr/bin/kubectl: No such file or directory

But, I still got, file /usr/bin/kubectl from install of origin-clients-3.6.1-1.0.008f2d5.x86_64 conflicts with file from package kubectl-1.8.4-0.x86_64

**Comment by pweil-** [comment]
looks like the `kubectl-1.8.4-0.x86_64` package needs uninstalled.  At this point there are unknown other dependency conflicts since I recall that you were attempting to use a combination of Kube and OpenShift prior to this install.   You might want to try removing any other kube rpms that you may have installed before trying again (if there are any).
