### ISSUE TITLE
How to stop Openshift from Creating LoadBalancer and Security Group if I don't want to?

### ISSUE THREAD

**Issue by bzon** [openshift/origin#17376]
I want Openshift to be able to use AWS EBS as our containers Persistent Storage. I installed the Openshift cluster using advanced playbook installation without any AWS specific configuration. Post installation, I followed this guide https://docs.openshift.org/latest/install_config/configuring_aws.html, and did it successfully. Using the appropriate API Keys that can list, detach, and attach volumes, I was able to create a PV for an EBS volume.

However, Openshift suddenly starts making API calls to create Load balancers for my existing services which are not my intention. I just want Openshift to be able to use AWS EBS and not use AWS ELB because this is something that I still have to figure out how to use properly.

##### Version
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.5.1
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. Install Openshift cluster in AWS EC2 instances using Advanced install playbook. Centos 7 servers.
2. Configure all nodes https://docs.openshift.org/latest/install_config/configuring_aws.html
3. Deploy an application and then try to create a `LoadBalancer` service type for it. 

##### Current Result

```bash
2017-11-19 04:38:20 +0000 UTC   2017-11-19 04:30:12 +0000 UTC   3         test-app   Service             Normal    CreatingLoadBalancer   {service-controller }   Creating load balancer
2017-11-19 04:38:20 +0000 UTC   2017-11-19 04:30:12 +0000 UTC   3         test-app   Service             Warning   CreatingLoadBalancerFailed   {service-controller }   Error creating load balancer (will retry): Failed to create load balancer for service xxx/test-app: UnauthorizedOperation: You are not authorized to perform this operation.
                                status code: 403, request id:
```

##### Expected Result

I should be able to create a Service without Openshift trying to create an Elastic Load Balancer.

**Comment by propyless** [comment]
Having the same issue after adding AWS cloud-provider to OpenShift 3.6.
Found this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1367229 which could be related, but should have been fixed a couple of releases ago.
