### ISSUE TITLE
Request for an API to be able to get the MetricsURL from within a pod

### ISSUE THREAD

**Issue by crobby** [openshift/origin#17384]
I have a webui that runs inside a pod.  I'd like to have that webui show some customized metrics (They happen to be metrics for a Spark cluster running in Openshift).  Currently, I can't think of a reasonable way to get the MetricsPublicURL into the pod so it can be used by my webui.

Most recently tried with: 
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Current Result
Not able to have a programmatic way to get MetricsPublicURL into a pod

##### Expected Result
Any given pod could know the cluster's MetricsPublicURL programmatically

**Comment by pweil-** [comment]
/cc @jcantrill 

This is in the same vein as other requests for discovery of infra services via some mechanism.
