### ISSUE TITLE
oc who-can don't show the expected result

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#17381]
I have 2 users user01 and user02. user01 has created a project my-project to which he is admin. user01 runs oc policy add-role-to-user view user02. user02 can now see my-project.

Now, user01 wants to see a list of users that can look at the contents of his project. He expects to see a list that includes himself and user02. But what he gets is the below:

```
$ oc policy who-can view project/my-project
Namespace: my-project
Verb:      view
Resource:  project/my-project

Users:  admin
        system:admin

Groups: system:cluster-admins
        system:masters
```

While if I list the rolebindings I see it:

```
$ oc get rolebinding
NAME                    ROLE                    USERS            GROUPS                          SERVICE ACCOUNTS   SUBJECTS
admin                   /admin                  user01
system:deployers        /system:deployer                                                         deployer
system:image-builders   /system:image-builder                                                    builder
system:image-pullers    /system:image-puller                     system:serviceaccounts:user01
view                    /view                      user02
```

Expected result would be that with __who-can__ I would be able to see the expected result.

**Comment by liggitt** [comment]
`view` is not an api verb. also, `who-can` takes the resource name as a separate arg.

`oc policy who-can get project my-project` would show what you expect
