### ISSUE TITLE
Smarter project cleanup

### ISSUE THREAD

**Issue by miminar** [openshift/origin#17387]
Bootstrap project template (the one set in `projectRequestTemplate` of `master-config.yaml` file) can create resources that are not cleaned up when the project is deleted such as cluster role bindings.

We should allow for automated cleanup of such resources. This was requested by one of our customers - it was suggested to allow to specify some `projectDeletionTemplate`.

**Comment by erikbsap** [comment]
Here Erik from SAP. We have a project template that requires a clusterrolebinding to get helm/tiller running. Having a user configuration option to delete this would be really helpful in that usecase. Thanks for creating that ticket.

**Comment by erikbsap** [comment]
What can I do that people start working on this? The visibility to big customers is high.
