### ISSUE TITLE
error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

### ISSUE THREAD

**Issue by acossette1979** [openshift/origin#17399]
##### Version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Deploy an images with a service account

##### Current Result
error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

##### Expected Result
secret is not on the disk...
```console
$ ls -lsa volumes/pods/062671fe-ce66-11e7-ad1b-3241c5621f9f/volumes/kubernetes.io~secret/
total 0
```

##### Additional Information

ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:156]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected

       ERROR: [DP1001 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:54]
              could not read the service account token: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected

       [Note] Summary of diagnostics execution (version v3.6.1+008f2d5):
       [Note] Errors seen: 1

     time="2017-11-21T02:35:34.418731054Z" level=error msg="response completed with error" err.code="blob unknown" err.detail=sha256:255a0a0695b4693108750a4f511d79aa07cef5d467cf6adc2d4e13be2ef72913 err.message="blob unknown to registry" go.version=go1.7.6 http.request.host="172.30.1.1:5000" http.request.id=3bcafd19-0707-4446-afd5-b397386d303a http.request.method=HEAD http.request.remoteaddr="192.168.65.2:47092" http.request.uri="/v2/myproject/cadc-sdm/blobs/sha256:255a0a0695b4693108750a4f511d79aa07cef5d467cf6adc2d4e13be2ef72913" http.request.useragent="docker/17.09.0-ce go/go1.8.3 git-commit/afdb6d4 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.0-ce \\(darwin\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=16.46326ms http.response.status=404 http.response.written=157 instance.id=906b861c-d5a4-4a76-8744-8ba2a37ea103 openshift.auth.user=developer openshift.auth.userid=e48fe8a2-ce22-11e7-ad1b-3241c5621f9f openshift.logger=registry vars.digest="sha256:255a0a0695b4693108750a4f511d79aa07cef5d467cf6adc2d4e13be2ef72913" vars.name="myproject/cadc-sdm"

**Comment by simo5** [comment]
@pweil- sounds more of a kubelet issue than auth
