### ISSUE TITLE
`oc cluster-up` fails with 'repository name must be canonical'

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#17394]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17385/test_pull_request_origin_extended_clusterup/100/

-- Checking for openshift/origin:v3.8.0-alpha.0 image ... 
   Pulling image openshift/origin:v3.8.0-alpha.0
FAIL
   Error: error pulling Docker image openshift/origin:v3.8.0-alpha.0
   Caused By:
     Error: repository name must be canonical

post-rebase issue

cc @openshift/sig-master

**Comment by juanvallejo** [comment]
Seeing this on https://github.com/openshift/origin/pull/17332 and when doing `oc cluster up` locally as well

**Comment by liggitt** [comment]
fix in #17395
