### ISSUE TITLE
Builders not pushing images to integrated registry / Cannot resolve docker-registry.default.svc

### ISSUE THREAD

**Issue by jtcressy** [openshift/origin#17392]
On a fresh install using openshift-ansible (branch release-3.6), builds fail to push images to the docker-registry. I've already tried re-deploying the registry, restarting the masters, and output from ``oc adm diagnostics`` is attached below.

##### Version
3.6.1

##### Current Result
Builder pods cannot resolve docker-registry.default.svc thus can't push images.
~~Builder pods cannot push to docker-registry.default.svc because the registry is not serving https on port 5000~~
##### Expected Result
Builder pods push images to registry and registry is serving https at port 5000.
##### Additional Information
Output of ``oc adm diagnostics``: [sprunge paste](http://sprunge.us/EJWI)
Build logs with `BUILD_LOGLEVEL=5`: [accountmanager-7.log](https://github.com/openshift/origin/files/1488717/accountmanager-7.log)

EDIT:
Re-attached registry-certificates and registry-config to the registry pod, which solves the problem with the registry not serving https, but I still get the 'no such host' error.
Updated builder log with `BUILD_LOGLEVEL=5`: [accountmanager-8.log](https://github.com/openshift/origin/files/1488793/accountmanager-8.log)
Log summary: ```F1120 18:58:15.463499       1 helpers.go:119] error: build error: Failed to push image: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp: lookup docker-registry.default.svc on 192.168.246.107:53: no such host```

**Comment by jtcressy** [comment]
After digging through https://github.com/openshift/origin/issues/16097
and https://github.com/openshift/openshift-ansible/issues/5466

I solved it by running this on every host (master, infra and nodes)
```
echo "search cluster.local" >> /etc/resolv.conf
```
Now i'm just *really* hoping this sticks after a restart.

**Comment by marthenlt** [comment]
Encounter the same thing, but actually you don't have to add cluster.local manually in /etc/resolv.conf

All you need to do if you're running RHEL like myself is to restart your NetworkManager and it will auto populate the correct search value with proper nameserver IP.

`systemctl restart NetworkManager`
