### ISSUE TITLE
Template services not appearing in front page

### ISSUE THREAD

**Issue by galderz** [openshift/origin#17401]
Using OpenShift Origin v3.7.0-rc.0+e92d5c5

The Infinispan* services I've created from my templates are not appearing the front page of OpenShift:
https://www.dropbox.com/s/qpjks2szhk2fhs2/Screen%20Shot%202017-11-21%20at%2010.38.54.png?dl=0

I have to click `Select from Project`, then select `openshift` and then I can see them:
https://www.dropbox.com/s/yfkegpea6yp65n8/Screen%20Shot%202017-11-21%20at%2010.39.11.png?dl=0

These services have been created using these commands:

    oc login -u developer -p developer
    oc project openshift
    oc adm policy add-cluster-role-to-group system:openshift:templateservicebroker-client system:unauthenticated system:authenticated
    oc create -f openshift/infinispan-centos7-imagestream.json || true
    oc create -f openshift/infinispan-persistent-template.json || true
    oc create -f openshift/infinispan-ephemeral-template.json || true

Output:

```
Using project "myproject".
+ oc project openshift
Now using project "openshift" on server "https://127.0.0.1:8443".
+ oc adm policy add-cluster-role-to-group system:openshift:templateservicebroker-client system:unauthenticated system:authenticated
cluster role "system:openshift:templateservicebroker-client" added: ["system:unauthenticated" "system:authenticated"]
+ oc create -f openshift/infinispan-centos7-imagestream.json
imagestream "infinispan" created
+ oc create -f openshift/infinispan-persistent-template.json
template "infinispan-persistent" created
+ oc create -f openshift/infinispan-ephemeral-template.json
template "infinispan-ephemeral" created
```

Finally, the templates used can be found in [this folder](https://github.com/infinispan-demos/streaming-data-kubernetes/tree/master/openshift).

**Comment by jwforres** [comment]
Probably something with the relist period from svc catalog to the TSB
@bparees

**Comment by galderz** [comment]
I've been out and came back and seems like eventually they appear:

https://www.dropbox.com/s/uk22s918rwim02p/Screen%20Shot%202017-11-21%20at%2013.27.54.png?dl=0

But they have a weird hash name on them, whereas the `Select from Project` method shows their template name. Any ideas where this name would come from? Any fields we should add to the templates above?

**Comment by jwforres** [comment]
https://docs.openshift.org/latest/dev_guide/templates.html#writing-templates

**Comment by bparees** [comment]
as far as i know, brokers can't choose their own relist interval yet, that's up to the service catalog configuration.  @pmorie
