### ISSUE TITLE
Can not start Open Shift　grpc　getsockopt: connection refused"

### ISSUE THREAD

**Issue by i-prakasa** [openshift/origin#17400]
When check Open Shift Status with these command 
-----------------------------------------------------------------------
$ systemctl status atomic-openshift-master
I got error 
grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp xx.xx.xx.xx:2379: getsockopt: connection refused"; Reconnecting to {master.co.jp:2379 <nil>}
----------------------------------------------------------------------

This was happen when I restart my server PC.
Before, when I install Open Shift, it automatically active. But after restart computer I got above failed.
I already check ping and nslookup master.co.jp and no problem.
Is Open Shift look at different setting when install and setting after reboot ? 
there any setting I should change?
Anyone can give hint or help?
Anyway I install my own DNS server on Master PC server

**Comment by pweil-** [comment]
this is the etcd port, is your etcd started if you are using standalone etcd?

**Comment by xiaods** [comment]
please checking etcd servie is running correctly.

**Comment by i-prakasa** [comment]
@pweil-  Thank you for your response. 
After check etcd it seems not start. 
I solve it and start manually. 
So when PC server reboot we should run this service manually? Or there is any setting to keep this etcd active even we reboot ?

**Comment by i-prakasa** [comment]
@xiaods Thank you very much for your response.
I started it using this command 
`systemctl start etcd`
and start again my Open Shift and it active again. Thank you very much

**Comment by pweil-** [comment]
you can use `systemctl` to enable the service on boot.  

```
Enabling simply hooks the unit into various suggested places (for example, so that the unit is automatically
           started on boot or when a particular kind of hardware is plugged in).
```

More info is available about this command in the man page.
