### ISSUE TITLE
Some API calls to /oapi/rolebindings on one master returning different results than rbac.authorization.k8s.io

### ISSUE THREAD

**Issue by simo5** [openshift/origin#17412]
We are seeing an intermittent failure to return rolebindings from an oc 3.6 client asking a 3.7.9 server.
Only 1 out of three masters returns empty results and only for a specific project as far as I can tell

**Comment by smarterclayton** [comment]
Also from a master oc client - confirmed that it was API only.  

The failure is that /oapi/rolebindings returns nothing on one of three masters.  The underlying call made by the virtual resource goes to /apis/rbac.authorization.k8s.io/rolebindings, but all three masters return a valid value for that api endpoint.

**Comment by liggitt** [comment]
Version of all masters was consistent?

**Comment by smarterclayton** [comment]
Server version was consistent.  The kube rbac call was correct on all three
masters.  The openshift was wrong on one of them.

**Comment by simo5** [comment]
So this turned out to be a case of a cluster that was in a bad state, due to human action.
One of the three masters had been downgraded to 3.6
3.6 does not proxy to RBAC but relies on a controller that syncs Policy and RBAC. The sync controller was not running though, as it does not exist in 3.7 and 3.6 was not in control.

So closing as it is not a bug, just a mess-up by the admins.
