### ISSUE TITLE
GCE suddenly testing many fewer test cases (including serial)

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#17416]
Only running 176 e2e tests, instead of (i think) about 243 pre rebase.

**Comment by smarterclayton** [comment]
@openshift/sig-master not sure where the error is, but we're running less tests and it looks like the gcloud provider is not running.

**Comment by smarterclayton** [comment]
Pre-rebase (and pre-GCE dying) https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/test_branch_origin_extended_conformance_gce/1942/ 249

Post-rebase https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17405/test_pull_request_origin_extended_conformance_gce/11770/ 176

**Comment by soltysh** [comment]
Fixed in #17417.
