### ISSUE TITLE
break: test-cmd broke because of image for ppc64le arch no longer being imported from docker hub

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#17436]
Since 2:30 EST on 11/22:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17314/test_pull_request_origin_cmd/6415/#githubcomopenshiftorigintestcmdimagesimagestreams-testcmdimagessh150-executing-oc-get-istag-test-nginx-multiarch-streamlinux-ppc64le---templateimagedockerimagemetadataarchitecture-expecting-success-and-text-ppc64le

```
=== BEGIN TEST CASE ===
test/cmd/images.sh:150: executing 'oc get istag test-nginx-multiarch-stream:linux-ppc64le --template={{.image.dockerImageMetadata.Architecture}}' expecting success and text 'ppc64le'
FAILURE after 0.233s: test/cmd/images.sh:150: executing 'oc get istag test-nginx-multiarch-stream:linux-ppc64le --template={{.image.dockerImageMetadata.Architecture}}' expecting success and text 'ppc64le': the output content test failed
Standard output from the command:
amd64
There was no error output from the command.
=== END TEST CASE ===
```

Could be #17391 (unlikely, but merged at same time) or could be something else like Docker changing the images on the hub

@openshift/sig-developer-experience @deads2k

**Comment by bparees** [comment]
docker manifest isn't providing anything except amd64 anymore:
https://paste.fedoraproject.org/paste/zAws11LEKRD-EtJxq-hg7A

looks like they reverted to schema2.v1 manifests?

we're just going to have to disable the test for now, unless you know of an image that does have other a v2 manifest.

**Comment by bparees** [comment]
well I did that wrong, but even once i request v2 + manifestlist schemas, i'm just getting back a regular manifest, not a manifest list.

**Comment by bparees** [comment]
well w/ some logging I am seeing manifestlists coming back. I don't know why my curl invocation won't give me one.  investigating why we're not seeing ppc

**Comment by bparees** [comment]
ok, s390x exists as a secondary arch, but ppc no longer does.  updated the test to use that for now, but we probably need to create our own manifestlist image on dockerhub in the future, if someone can help me figure out how to push a manifestlist.

**Comment by bparees** [comment]
updated the test to use a repository under our control w/ a multiarch manifestlist, so this won't get broken in the future if docker changes random image manifests.

**Comment by smarterclayton** [comment]
oc image mirror should be able to easily copy

On Nov 22, 2017, at 11:46 PM, Ben Parees <notifications@github.com> wrote:

updated the test to use a repository under our control w/ a multiarch
manifestlist, so this won't get broken in the future if docker changes
random image manifests.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/17436#issuecomment-346531310>,
or mute the thread

**Comment by bparees** [comment]
> oc image mirror should be able to easily copy

copy what? to where?

**Comment by smarterclayton** [comment]
oc image mirror SRC DST where SRC is a manifest list and DST is a repo
under our control on the hub

On Nov 22, 2017, at 10:10 PM, Ben Parees <notifications@github.com> wrote:

ok, s390x exists as a secondary arch, but ppc no longer does. updated the
test to use that for now, but we probably need to create our own
manifestlist image on dockerhub in the future, if someone can help me
figure out how to push a manifestlist.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/17436#issuecomment-346523589>,
or mute the thread

**Comment by bparees** [comment]
> oc image mirror SRC DST where SRC is a manifest list and DST is a repo
under our control on the hub

per my comments in the PR, i've already created a repo under our control w/ a proper manifest list.  And i'm not sure where i would have SRCed a valid one from if i hadn't created one from scratch, since as already established, the one we were using doesn't contain ppc anymore.

**Comment by priyankakhetawat** [comment]
Hi,
I am trying to do oc cluster up, I am getting this same error on rhel 7 with sys architecture as ppc64le
