### ISSUE TITLE
[Question] Why Glide when we have dep?

### ISSUE THREAD

**Issue by budhrg** [openshift/origin#17438]
I recently saw few commits for `glide.yaml` [commit1](https://github.com/openshift/origin/commit/9e214041e98db015dbf03b8fd9748e9db3a2f03f) and [commit2](https://github.com/openshift/origin/commit/4de2dc54177bda8875a3dc4b2d688fc5d724efe1)

Are we migrating from Dep to Glide?

Glide is in support mode and no new feature development happens there. The Go community now has the [dep](https://github.com/golang/dep) project to manage dependencies.

#### From the Glide homepage:

> The Go community now has the dep project to manage dependencies. Please consider trying to migrate from Glide to dep. If there is an issue preventing you from migrating please file an issue with dep so the problem can be corrected. Glide will continue to be supported for some time but is considered to be in a state of support rather than active feature development.

**Comment by mfojtik** [comment]
@deads2k @sttts I think we owe an email to users list describing why we picked glide over dep.

Basically from what I heard dep has still issues handling multi-level dependencies in vendor directory and we will have to plumb dep to make it work the same way as glide does today. I think it is reasonable to switch to dep when it can handle all the edge cases origin currently have (forks, different levels for deps, nested vendor dirs, etc..).

**Comment by abs51295** [comment]
@mfojtik IIUC your response then we are using glide to manage dependencies. Then why do we still have `Godeps.json` in the repository. Also, what's more confusing is that the file only manages two dependencies namely `etcdserver` and `kubernetes/pkg/api` which are already present in `glide.lock` with different versions.
