### ISSUE TITLE
Prometheus example configuration: route leads to 404 page not found

### ISSUE THREAD

**Issue by exquisitus** [openshift/origin#17447]
The template https://github.com/openshift/origin/blob/master/examples/prometheus/prometheus.yaml creates a setup which does not seem to be functioning completely correctly

##### Version
oc v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f

(Tested on two different oc clusters)
##### Steps To Reproduce
1. download https://github.com/openshift/origin/blob/master/examples/prometheus/prometheus.yaml
2. oc process -f prometheus.yaml | oc create -f -
serviceaccount "prometheus" created
clusterrolebinding "prometheus-cluster-reader" created
route "prometheus" created
service "prometheus" created
secret "prometheus-proxy" created
statefulset "prometheus" created
configmap "prometheus" created
route "alerts" created
service "alerts" created
secret "alerts-proxy" created
configmap "prometheus-alerts" created

##### Current Result
When visiting the second route created by the template ( https://alerts-kube-system.127.0.0.1.nip.io/ )

404 page not found
##### Expected Result
Web interface of the alert manager

**Comment by smarterclayton** [comment]
Did you try on rc.0?

**Comment by exquisitus** [comment]
Now I did, and I got the same result

**Comment by smarterclayton** [comment]
I’m actually not sure the alert manager has anything other than an API.

**Comment by exquisitus** [comment]
Sorry, I think you are right that this is intended behaviour and I was confused.

I have seen an Alertmanager web interface e.g. here: https://thenewstack.io/contributing-prometheus-history-alertmanager/ . But the example prometheus.yaml does not try to expose that in a service or route.

What it exposes instead as "alerts" route is (port 9099, behind a proxy on port 9443) the alert-buffer API, and not the Alertmanager. And indeed, https://alerts-kube-system.127.0.0.1.nip.io/topics/alerts is working.
