### ISSUE TITLE
deployer_controller doesn't copy tolerations to deployer pod

### ISSUE THREAD

**Issue by polaru** [openshift/origin#17445]
When creating a DeploymentConfig that includes tolerations, the deployer pod get's created w/o the tolerations. Because it uses the same nodes as the regular pods, it fails to start (because the nodes were tainted, that's why we included the tolerations in the config in the first place).

##### Version
```
$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```
##### Steps To Reproduce
1. Taint nodes
2. Create a DeploymentConfig using those nodes in NodeSelector and include a toleration for the taint on the nodes
3. Observe:
- deploy pod stuck in pendig
`router-external-8-deploy   0/1       Pending   0          1h        <none>           `
- deploy pod missing tolerations
```
$ oc describe po/router-external-8-deploy | grep Tolerations:
Tolerations:	<none>
```
- rc gets created and has the right tolerations:
`rc/router-external-8    0         0         0         1h`
```
$ oc export rc/router-external-8 | grep -A 3 " tolerations"
      tolerations:
      - key: role
        operator: Equal
        value: gateway
```
So if I edit the deploy pod to add the tolerations, it gets scheduled and the regular pods have no issue running.

##### Current Result
Deploy pod is stuck in pending because it doesn't match tolerations/tains
```
$ oc describe po/router-external-8-deploy | grep FailedScheduling | tail -n 1
  22s		7s		5	default-scheduler			Warning		FailedScheduling	No nodes are available that match all of the following predicates:: MatchNodeSelector (52), PodToleratesNodeTaints (7).
```
##### Expected Result
Deploy pod should get the tolerations mentioned in the DeploymentConfig.

##### Additional Information
Although I'm running 3.6, the code is the same in master, so I don't expect it to be different with a newer version: https://github.com/openshift/origin/blob/master/pkg/apps/controller/deployer/deployer_controller.go#L378

**Comment by mfojtik** [comment]
@tnozicka i will work on this... also this reminds me that we probably need a test where we check if every field is copied to deployer pod properly (probably have blacklist for fields we don't copy).
