### ISSUE TITLE
oc command is slow

### ISSUE THREAD

**Issue by dernasherbrezon** [openshift/origin#17441]
Running simple command using oc takes more than 2 seconds.

##### Version
$ oc version
oc v3.5.5.31.24

##### Steps To Reproduce
1. On windows
2. Run the following command: powershell -Command "Measure-Command {oc.exe --help}"

##### Current Result
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 110
Ticks             : 31107311
TotalDays         : 3,60038321759259E-05
TotalHours        : 0,000864091972222222
TotalMinutes      : 0,0518455183333333
TotalSeconds      : 3,1107311
TotalMilliseconds : 3110,7311

##### Expected Result

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0

##### Additional Information
This slowness might be related to various Windows settings. I don't have Administrator permissions to run process monitor (https://docs.microsoft.com/en-us/sysinternals/downloads/procmon). Some ideas:
- oc.exe size is 88mb (!) and it takes some time for antivirus to scan
- loading 88Mb into memory takes some time

**Comment by smarterclayton** [comment]
On a modern system loading 88mb into memory should come from the page cache and take less than a few tens of ms.  Antivirus settings are one culprit.  Recommend Fabiano look

**Comment by dernasherbrezon** [comment]
Run the command with ```--loglevel=8```:
```
   I1201 09:12:25.300155    4020 cached_discovery.go:123] failed to write cache to H:\.kube\openshift cluster name\servergroups.json due to chmod H:\.kube\openshift cluster name\
```

Took almost 1 sec to fail. 

Is it possible to change cache directory without changing windows profile location?

**Comment by DonSchenck** [comment]
FYI, running this on Windows 10, Build 16299.192 on a Mac using Parallels, I get:
`PS C:\Users\dschenck> oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth
PS C:\Users\dschenck> powershell -Command "Measure-Command {oc.exe --help}"


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 267
Ticks             : 2672607
TotalDays         : 3.09329513888889E-06
TotalHours        : 7.42390833333333E-05
TotalMinutes      : 0.004454345
TotalSeconds      : 0.2672607
TotalMilliseconds : 267.2607`

**Comment by juanvallejo** [comment]
@dernasherbrezon could you post the full (redacted if needed) output of --loglevel=8?

**Comment by sudheerchekka** [comment]
Running in to the same issue. On my mac, oc version is taking 12 secs to respond. Here is the output with --loglevel=10

https://pastebin.com/tCLm01Z3

**Comment by juanvallejo** [comment]
cc @soltysh 
From the logs, it looks like about 8 seconds are spent between [this line](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/transport/round_trippers.go#L386) and [this one](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/transport/round_trippers.go#L405). Per the logs, the actual round trip only seems to take 88ms - which might suggest the delay could be happening [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/transport/round_trippers.go#L389) or [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/transport/round_trippers.go#L402).

@sudheerchekka just to make sure, could you run a command without hitting the server?
Something like: `$ oc label -f mypod.yaml KEY=VAL --local --loglevel 8`

**Comment by sudheerchekka** [comment]
thanks for looking into it. here is the output:

https://pastebin.com/Wd4VHw3k

**Comment by juanvallejo** [comment]
It looks like about 8 seconds are being spent decoding and returning cached discovery data.
@sudheerchekka are you also using version 3.5? could you post your `oc version` output?

**Comment by sudheerchekka** [comment]
I am using 3.7

**oc v3.7.23
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth
Server https://192.168.64.7:8443
openshift v3.7.14
kubernetes v1.7.6+a08f5eeb62**

I realized I was using OpenShift version of oc client.
When I switched over to Origin version, no more delay and here is the output of that oc client:

**oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://192.168.64.7:8443
openshift v3.7.14
kubernetes v1.7.6+a08f5eeb62**

May be I should open a ticket for enterprise version.

**Comment by soltysh** [comment]
@juanvallejo so it's the OCP v3.7.23, that's causing this delay, only. It was reported elsewhere (ping me for the source) the exact same situation. Switching to origin 3.7.1 solved the problem.

**Comment by dernasherbrezon** [comment]
Hi @juanvallejo, here it is:

> oc version --loglevel=8
> I0220 10:06:24.784253   18348 loader.go:354] Config loaded from file H:\/.kube/config
> oc v3.5.5.31.24
> kubernetes v1.5.2+43a9be4
> features: Basic-Auth
> I0220 10:06:24.941470   18348 round_trippers.go:296] GET /api
> I0220 10:06:25.155323   18348 round_trippers.go:321] Response Status: 200 OK in 170 milliseconds
> ...
> I0220 10:06:25.213913   18348 round_trippers.go:296] GET /apis
> ...
> I0220 10:06:25.297892   18348 round_trippers.go:321] Response Status: 200 OK in 14 milliseconds
> ...
> I0220 10:06:26.508752   18348 cached_discovery.go:123] failed to write cache to H:\.kube\openshift cluster name\servergroups.json due to chmod H:\.kube\openshift cluster name
> I0220 10:06:26.523400   18348 round_trippers.go:296] GET /version
> ...
> I0220 10:06:26.609332   18348 round_trippers.go:321] Response Status: 200 OK in 16 milliseconds
> ...
> I0220 10:06:26.857363   18348 round_trippers.go:296] GET /version/openshift
> ...
> I0220 10:06:26.946224   18348 round_trippers.go:321] Response Status: 200 OK in 14 milliseconds
> ...
> Server openshift cluster name
> openshift v3.7.23
> kubernetes v1.7.6+a08f5eeb62

According to logs there is 1.211 seconds between reading response from server and failed attempt to save into H:\.kube. 

The issue is definitely in the shared disk.

**Comment by juanvallejo** [comment]
@dernasherbrezon
> The issue is definitely in the shared disk.

Thanks for confirming this. Does it still take ~1 second to save when you place (and use) ~/.kube in a local drive?

**Comment by dernasherbrezon** [comment]
@juanvallejo Unfortunately, I cannot change home directory (I am not an administrator). 

I was wondering if there is a way to change cache directory?

**Comment by sudheerchekka** [comment]
In my case, I have OpenShift running locally on my laptop. So the client and the server on the same laptop

**Comment by dernasherbrezon** [comment]
Always wondered about these auto-close bots. I've spent hours trying to help improve application, logged in, raised issue, gave detailed explanation and steps to reproduce. And now this. Really demotivated helping the community.
