### ISSUE TITLE
login with system:admin failed

### ISSUE THREAD

**Issue by kuramal** [openshift/origin#17449]
when I login my openshift cluster  with command: 
`oc login -u system:admin  --config=/etc/origin/master/admin.kubeconfig `
but  I get an error
`error: Forbidden`

##### Version
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
etcd 3.2.1
oc v3.6.1+008f2d5
##### Steps To Reproduce
`oc login -u system:admin  --config=/etc/origin/master/admin.kubeconfig `

##### Current Result
`error: Forbidden`
##### Expected Result
login successed

**Comment by mali0190** [comment]
Same error... Any one resolve this error... 
when I login my openshift cluster with command:
oc login -u system:admin --config=/etc/origin/master/admin.kubeconfig
but I get an error
error: Forbidden

Version
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
etcd 3.2.1
oc v3.6.1+008f2d5

Steps To Reproduce
oc login -u system:admin --config=/etc/origin/master/admin.kubeconfig

Current Result
error: Forbidden

Expected Result
login successed
