### ISSUE TITLE
osc get nodes still showing "Schedulable"

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1744]
AIUI the "Schedulable" status has gone away, but it's in the output of "osc get nodes" messing up the output.

```
# osc get nodes
NAME           LABELS        STATUS
172.16.4.164   Schedulable   region=infra,zone=NA       Ready
172.16.4.167   Schedulable   region=primary,zone=east   Ready
172.16.4.168   Schedulable   region=primary,zone=west   Ready
```

Same for "get minions"

**Comment by smarterclayton** [comment]
Why has schedulable gone away?

**Comment by sosiouxme** [comment]
Good question, I just happened to notice the status type constant for it was no longer defined (or at least moved somewhere non-obvious). Maybe I'm wrong about the specifics there, it would seem to be valuable to be able to mark a node as NON-schedulable... 

Certainly the column heading are messed up here though.

**Comment by smarterclayton** [comment]
Unschedulable hasn't been dropped to my knowledge.

**Comment by sosiouxme** [comment]
You're right, it has simply moved from being a NodeCondition to being part of the node spec.

https://github.com/GoogleCloudPlatform/kubernetes/commit/ef56dca6b6d3848de80888895e90d76dc13e33c2

So, just fix the header :)

**Comment by smarterclayton** [comment]
There's an upstream issue on that (I saw it when I searched).

**Comment by nak3** [comment]
It looks like upstream fixed here https://github.com/GoogleCloudPlatform/kubernetes/pull/6886/files

Also Just FYI, https://github.com/GoogleCloudPlatform/kubernetes/pull/7039

I guess we will get some reports about this on Beta 3 release.

**Comment by danmcp** [comment]
Any remaining issues here?

**Comment by sosiouxme** [comment]
Looks good in latest. Thanks.
