### ISSUE TITLE
router link dead on services tab 

### ISSUE THREAD

**Issue by austincunningham** [openshift/origin#17440]
[provide a description of the issue]
router link dead on services tab

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v3.7.0-rc.0+e92d5c5
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.0-rc.0+e92d5c5
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
![openshift error](https://user-images.githubusercontent.com/16667688/33167586-e27fd7a4-d035-11e7-9f8f-e6f41ea83e61.gif)

##### Current Result
404
##### Expected Result
render docs link
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jwforres** [comment]
This is already fixed in master to point to the new pages, and they will also be setting up redirects from the old pages to the new ones.
