### ISSUE TITLE
Error "Server connection interrupted. Refresh" shows while using nginx reversing proxy to openshift web console

### ISSUE THREAD

**Issue by eliu** [openshift/origin#17456]
I use nginx to create a reverse proxy to the OpenShift web console for some reason. The web page can display but shows `Server connection interrupted` error notification intermittently.

The nginx conf file is something like this:

```nginx
server {
   listen 80;
   server_name *.app.example.com;
   location / {
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_pass http://192.168.123.155/;
   }
}
server {
    listen 8443 ssl;
    server_name master.example.com;
    ssl_certificate     master.server.crt;
    ssl_certificate_key master.server.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass https://192.168.123.155/;
    }
}
```

##### Version
[provide output of the `openshift version` or `oc version` command]

oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.example.com:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by mfojtik** [comment]
probably need some wisdom from @knobunc team ;-)

**Comment by jwforres** [comment]
That message means there are issues establishing websocket connections. Check that you have properly configured nginx to allow websocket connections through.

**Comment by eliu** [comment]
@jwforres thanks for the tips! Now the error notification faded away after handling websocket stuff within nginx.

**Comment by dajudge** [comment]
@jwforres would you mind sharing the nginx configuration that you ended up with that worked?
