### ISSUE TITLE
5 MatchNodeSelector

### ISSUE THREAD

**Issue by syui** [openshift/origin#17455]
I am using OpenShift Online Starter.

## oc version

```sh
$ oc version
oc v3.6.173.0.5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth
Server https://api.starter-us-east-1.openshift.com:443
openshift v3.7.9
kubernetes v1.7.6+a08f5eeb62
```

## 5 MatchNodeSelector

Error : `0/260 nodes are available: 255 Insufficient memory, 5 MatchNodeSelector.`

```sh
$ oc new-app mysql
$ oc get all
  po/mysql-${n}-deploy 0/1 Pending
```

**Comment by vymiyai** [comment]
Experiencing the same problem every time I try to redeploy an image.

**Comment by mmahut** [comment]
Follow the starter outages at https://status.starter.openshift.com/

**Comment by abhgupta** [comment]
The issues should now all be resolved and you should be able to create your application.
