### ISSUE TITLE
How to insecure search/inspect images in OpenShift web console

### ISSUE THREAD

**Issue by fushilong** [openshift/origin#17450]
From an existing project In OpenShift web console, click "Add to project" ---> "Deploy Image" --->"Image Name", in the below text field,we can fill specified registry and image name then click magnifier button to inspect the image. So the question is the "Searching" behaviour is secured or unsecured? Is this configurable? If I want to insecure  to connect the registry,how can I do?

Any advice or suggestion would be appreciated! Thank you!

**Comment by jwforres** [comment]
It's not actually a search API, it is just a dry-run mode of the imagestream import API. More details on image import:
https://docs.openshift.com/container-platform/3.6/dev_guide/managing_images.html#importing-tag-and-image-metadata

The image import API creates an imagestream in your project so you need the correct permissions in that project to run it.

Today the console doesn't let you set up credentials to the registry as part of the deploy image dialog, so if you are trying to deploy an image from a private registry make sure to set up a dockercfg secret in your project first.

**Comment by fushilong** [comment]
@jwforres Thank you so much for the explanation,that's very useful!
