### ISSUE TITLE
Support for running on Windows using Linux Containers for Windows (LCOW)

### ISSUE THREAD

**Issue by gbraad** [openshift/origin#17461]
As part of the Windows 10 Pro 1709 and the Docker edge release, it is possible to activate "Linux Containers on Windows" (LCOW). This means that in future versions, the user needs to choose the older MobyLinuxVM or use LCOW. Either this needs to be made comptaible, or documented.

I was running *Docker for Windows* + *Hyper-V* + `oc cluster up`
Then I decided to update *Docker for Windows* to  [Edge channel](https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows) according the docs : "Edge builds are released once per month."

After that *Docker for Windows* + *Hyper-V* + `oc cluster up` stopped to work and show this error message:  "Windows does not support privileged mode".

##### Steps To Reproduce
1. install Windows Pro 10, version 1709
2. install Docker for Windows (Edge)
![image_of_edge](https://user-images.githubusercontent.com/6443576/32949834-fa1109cc-cb82-11e7-86b9-aafb23b4f301.PNG)
3. enable Linux Containers on Windows (LCOW)
![image_7702d8a0-6b78-449d-9b7b-cf9a34b080c3](https://user-images.githubusercontent.com/1894/33237160-be856ed6-d2a6-11e7-9caf-77d406038874.png)
4. run `oc cluster up`

##### Current Result
"Windows does not support privileged mode".
![image_of_error](https://user-images.githubusercontent.com/6443576/32949837-fa2cd2c4-cb82-11e7-9a3d-0f9150d587f5.PNG)

##### Expected Result
Startup succeeds or informs me beforehand that this is not possible.

##### Additional Information
It seems "Enable Linux Containers on Windows" (LCOW) does not support "privileged mode" => https://github.com/bucharest-gold/nodeshift/issues/127#issuecomment-346983617

The check in Moby/Docker can be found here:
https://github.com/moby/moby/blob/a2f3f6660d08dfb667f091e0fd8454c815dd1c81/runconfig/hostconfig_windows.go#L75-L84

###### Requirements

  * Insider build of Windows (1709)  
    https://insider.windows.com/en-us/
  * Docker for Windows (edge channel)  
    https://download.docker.com/win/edge/Docker%20for%20Windows%20Installer.exe

###### References

  * https://github.com/containerd/containerd/issues/1185
  * https://cloudblogs.microsoft.com/hybridcloud/2017/04/18/dockercon-2017-powering-new-linux-innovations-with-hyper-v-isolation-and-windows-server/
  * https://blog.docker.com/2017/09/preview-linux-containers-on-windows/

##### Example
```
C:\Users\gbraad>docker run -it --privileged --pid=host gbraad/hostenter /bin/sh
docker: Error response from daemon: Windows does not support privileged mode.
```

**Comment by bparees** [comment]
@gbraad please point me to the documentation that lead to you try this on windows and i'll put an appropriate note there.  oc cluster up is not going to support windows (it doesn't even support MacOS anymore).

**Comment by gbraad** [comment]
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#windows-with-docker-for-windows

**Comment by bparees** [comment]
Thanks, fixing it here:
https://github.com/openshift/origin/pull/20725
