### ISSUE TITLE
no kind "ControllerRevisionList" is registered for version "apps/v1beta1"

### ISSUE THREAD

**Issue by megian** [openshift/origin#17460]
The openshift-ansible upgrade from openshift/origin:v3.6.1 to openshift/origin:v3.7.0-rc.0 failed with the error : exited without processing all resources: no kind "ControllerRevisionList" is registered for version "apps/v1beta1"

The upgrade process stops at playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml "Upgrade all Storage"

After manually executed
oc adm policy reconcile-cluster-roles --additive-only=false --confirm
the command completed successfully.

It seams that the openshift-ansible playbook did it not execute "oc adm policy reconcile-cluster-roles" before "oc adm migrate storage"

##### Version
3.7.0-rc.0

##### Steps To Reproduce
1. Upgrade the container version from v3.6.1 to v3.7.0-rc.0

##### Current Result
fatal: [host]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/oc", "adm", "--config=/etc/origin/master/admin.kubeconfig", "migrate", "storage", "--include=*", "--confirm"], "delta": "0:01:10.399981", "end": "2017-11-12 21:14:09.823237", "failed": true, "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2017-11-12 21:12:59.423256", "stderr": "", "stderr_lines": [], "stdout": "summary: total=625 errors=0 ignored=0 unchanged=550 migrated=75\nerror: exited without processing all resources: no kind \"ControllerRevisionList\" is registered for version \"apps/v1beta1\"", "stdout_lines": ["summary: total=625 errors=0 ignored=0 unchanged=550 migrated=75", "error: exited without processing all resources: no kind \"ControllerRevisionList\" is registered for version \"apps/v1beta1\""]}

##### Expected Result
oc adm migrate storage --confirm
summary: total=928 errors=0 ignored=0 unchanged=817 migrated=111

**Comment by soltysh** [comment]
> no kind "ControllerRevisionList" is registered for version "apps/v1beta1"

That message doesn't look like it's related to roles not being reconciled. This is caused by a resource (here `ControllerRevisionList`) not being known to the oc command. Comparing apps/v1beta1 in [3.6](https://github.com/openshift/origin/blob/release-3.6/vendor/k8s.io/kubernetes/pkg/apis/apps/v1beta1/types.go) and [3.7](https://github.com/openshift/origin/blob/release-3.7/vendor/k8s.io/kubernetes/pkg/apis/apps/v1beta1/types.go) it's clear that 3.6 does not have `ControllerRevisionList`. So my guess is that this step was performed with oc 3.6, but should be with 3.7.

@megian can you check the oc versions ansible and you used?

**Comment by bigg01** [comment]
We are running containerized installation. It looks like upgrade doesn't update the /usr/local/bin/oc client. 
Is there a possibility to run it ? openshift_container_binary_sync

**Comment by megian** [comment]
Possible that the client has been upgraded afterwards. The current version is:

/usr/local/bin/oc version  
oc v3.7.0-rc.0+e92d5c5
kubernetes v1.7.6+a08f5eeb62

**Comment by soltysh** [comment]
@sdodson can you verify that in our ansible installer, it looks like a bug in the installer. Nothing the master team can own.

**Comment by sdodson** [comment]
@megian If it's been updated afterwards you should be able to re-run the playbooks and complete the upgrade. We'll look into ordering to ensure that the client is updated after the control plane is updated and before the second storage migration.

**Comment by megian** [comment]
I can confirm that the second migration did complete without any issue. It seams to be an sequence problem, when the client will be deployed.

**Comment by sdodson** [comment]
Yeah, for RPM based installs the client gets updated as soon as the master packages are updated due to RPM dependencies. However with containerized installations that has to be a deliberate step.

**Comment by ayen-tibco** [comment]
I got the same error message and my containerized Openshift got upgrade to 3.7 while my oc client tool remains at 3.6. How do I upgrade my client tools? I don't sse in the Quick or Advance installation docs. Was it left out intentionally?

https://docs.openshift.com/container-platform/latest/install_config/install/rpm_vs_containerized.html

# oc version
oc v3.6.173.0.83
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://somehost:8443
openshift v3.7.14
kubernetes v1.7.6+a08f5eeb62
