### ISSUE TITLE
SubnetAllocator issues with multiple subnets

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#17475]
If you have multiple clusterNetworkCIDR values, then at startup, the master creates a netutils.SubnetAllocator for each range, but it passes the complete list of currently-allocated subnets to each NewSubnetAllocator call, which will result in each one printing `"Provided subnet doesn't belong to network"` messages for each subnet that belongs to a different range. It shouldn't do that. Either master/subnets.go should split up the subnets into multiple lists before calling NewSubnetAllocator, or else NewSubnetAllocator should just silently ignore out-of-range subnets.

(Also, if NewSubnetAllocator is going to spew errors, it should use glog, not fmt.Println.)

**Comment by JacobTanenbaum** [comment]
@danwinship do you have a preference? I think it would be okay to remove the check of the subranges in use, the call to ParseNetworkInfo checks that all existing subnets appear in a clusterNetworkCIDR range

**Comment by danwinship** [comment]
Slight preference for the more complicated solution. Otherwise I would have just fixed it myself. :)

Actually, SubnetAllocator is only used by pkg/network/master anyway. So how about we just move it there, and then go ahead and remove the warning in NewSubnetAllocator() because we can just assume that the caller has already checked it in that case
