### ISSUE TITLE
Support execing into non-pod resources

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17470]
```
$ oc exec -it deploy/prometheus -c alertmanager -- curl -vvv -XPOST localhost:9093/-/reload
error: invalid resource name "deploy/prometheus": [may not contain '/']
```
@mfojtik @openshift/sig-user-interface

**Comment by droslean** [comment]
It would be nice to have this !!!! 

Right now we use some alternative approach like:

``
PODNAME=$(oc get po -l name=pod_label -o=custom-columns=:.metadata.name --no-headers)
``
``
oc exec -it $PODNAME -- some_commands
``

instead we should use 
``
oc -it deploy/test -- some_commands
``

**Comment by jwforres** [comment]
the exec command comes from upstream kubectl, I would recommend opening this issue in kubernetes repo instead and getting the attention of sig-cli. We'd be unlikely to patch around exec to make this work.
