### ISSUE TITLE
GSSAPI test failure due to run command error: watch closed before Until timeout

### ISSUE THREAD

**Issue by enj** [openshift/origin#17481]
This is possibly related to https://github.com/kubernetes/kubernetes/pull/50102

From https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_gssapi/272/

```
Some command failed in a script: test/extended/gssapi.sh:109: `oc run "${image_name}" --image="${project_name}/${image_name}" --generator=run-pod/v1 --restart=Never --attach --env=SERVER="${server_config}" > "${pod_log_location}" 2>> "${junit_gssapi_output}"` exited with status 1.
```

The `oc run` command failed due to:

```
error: watch closed before Until timeout
```

@openshift/sig-master @openshift/sig-security @openshift/cli-review

**Comment by enj** [comment]
@mfojtik @pweil- @eparis @simo5 @liggitt marking this as P1 since we have 0 coverage for GSSAPI without these tests.

**Comment by liggitt** [comment]
seeing these errors:

Dec 11 20:11:51 ip-172-18-4-167.ec2.internal dockerd-current[1381]: time="2017-12-11T20:11:51.723307032Z" level=error msg="Handler for GET /v1.24/images/docker.io/gssapiproxy/fedora-gssapi-base:latest/json returned error: No such image: docker.io/gssapiproxy/fedora-gssapi-base:latest"

the local builds we're building/tagging aren't matching the unqualified pullspecs

**Comment by liggitt** [comment]
the problem is that the image couldn't run, not that the watch timed out

**Comment by arocki7** [comment]
If you use an AWS Load balancer, you want to increase the timeout value.
