### ISSUE TITLE
Remove auto-migration as part of kubeconfig loader

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#17483]
Tracking https://github.com/openshift/origin/pull/17357#discussion_r153302979

This issue tracks the [removal of migration-rules](https://github.com/openshift/origin/blob/master/pkg/oc/cli/config/loader.go#L30) (and auto-migration of existing kubeconfig files in general), as the default location has not changed in over two years.

cc @deads2k @smarterclayton @liggitt

**Comment by deads2k** [comment]
@smarterclayton It's been years, I don't think we need to support `~/.kube/.config` anymore
@juanvallejo direct code link please.

**Comment by juanvallejo** [comment]
What this issue aims to get rid of: https://github.com/openshift/origin/blob/master/pkg/oc/cli/config/loader.go#L30

Moved to [pkg/client/config/loader.go](https://github.com/openshift/origin/pull/17357/files#diff-479af547682bc81dcd6b91ac607bc4a9R26) in pull/17357
