### ISSUE TITLE
Very large clusters cause excessive prometheus memory use due to certain high cardinality prometheus metrics

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#17495]
High cardinality series on us-east-1 - #17494 covers the SDN metrics, but cadvisor is blowing out the rest.  We're at around 5-6GB with only node and master metrics, but with cadvisor enabled we jump to 20-22GB.

Things we probably don't care about out of this list:

* tasks_state
* memory_failures_total?
* spec_memory_swap_limit_bytes

Just reducing the cardinality of certain of these series would be huge.

```
container_cpu_usage_seconds_total{} | 274210
-- | --
container_tasks_state{} | 262600
container_fs_reads_total{} | 242271
container_fs_writes_total{} | 242271
container_fs_reads_bytes_total{} | 221052
container_fs_writes_bytes_total{} | 221052
container_memory_failures_total{} | 210080
openshift_sdn_pod_setup_latency{} | 55197
container_memory_usage_bytes{} | 52520
container_cpu_user_seconds_total{} | 52520
container_memory_swap{} | 52520
container_start_time_seconds{} | 52520
container_memory_working_set_bytes{} | 52520
container_cpu_system_seconds_total{} | 52520
container_memory_cache{} | 52520
container_last_seen{} | 52520
container_memory_failcnt{} | 52520
container_memory_rss{} | 52520
container_spec_cpu_shares{} | 52469
container_spec_cpu_period{} | 52469
container_spec_memory_swap_limit_bytes{} | 52424
container_spec_memory_limit_bytes{} | 52424
openshift_sdn_pod_teardown_latency{} | 41898
storage_operation_duration_seconds_bucket{} | 39636
container_fs_read_seconds_total{} | 22146
container_fs_usage_bytes{} | 22146
container_fs_limit_bytes{} | 22146
container_fs_sector_reads_total{} | 22146
container_fs_write_seconds_total{} | 22146
container_fs_writes_merged_total{} | 22146
container_fs_io_time_seconds_total{} | 22146
container_fs_io_current{} | 22146
container_fs_inodes_total{} | 22146
container_fs_reads_merged_total{} | 22146
container_fs_sector_writes_total{} | 22146
container_fs_io_time_weighted_seconds_total{} | 22146
container_fs_inodes_free{} | 22146
container_spec_cpu_quota{} | 21079
container_cpu_cfs_throttled_seconds_total{} | 21079
container_cpu_cfs_throttled_periods_total{} | 21079
container_cpu_cfs_periods_total{} | 21079
openshift_sdn_pod_setup_latency_count{} | 18399
openshift_sdn_pod_setup_latency_sum{} | 18399
```

**Comment by smarterclayton** [comment]
Not sure what our best option is, but if we doubled the number of pods we would double the prometheus memory usage (roughly).

**Comment by smarterclayton** [comment]
@eparis this is why us-east-1 is OOMing - we're using somewhere north of 30gb by default (25 of it coming from cadvisor), and the only way out is to cut metrics or give it more memory.

**Comment by smarterclayton** [comment]
Temporarily dropped the following metrics and stet scrape interval at 3m.

```
       metric_relabel_configs:
       - source_labels: [__name__]
         action: drop
         regex: 'container_(tasks_state|memory_failcnt|memory_failures_total|spec_memory_swap_limit_bytes|fs_(.*)_bytes_total|spec_(.*))|openshift_sdn_pod_setup_latency'
```

This took us from > 30gb to ~20gb and holding steady.  Will bump the interval back down after a while.  I suspect that each million series costs us about 10gb or so.

**Comment by sjenning** [comment]
fyi @derekwaynecarr 

@smarterclayton what does the number after the metric indicate?

Some triage:

`tasks_state` cardinality is magnified by the possible process running states of which there are 5
https://github.com/google/cadvisor/blob/0bde1c615c6d66ab9bfec9040b497e2488ffc30a/metrics/prometheus.go#L719-L748

I don't see that metrics being very useful.  Might help diagnosing a bunch of processes hung on I/O or something...

All the `container_spec_` "metrics" are really just values that never change, at least not until we have vertical pod scaling.  Either way, these aren't even metrics in my mind.  More like static properties of the pod, discoverable from the pod spec.

`container_memory_failures_total` cardinality is magnified by the 2x2 fault types ([container, heirarchy] x [pgfault, pgmajfault]) 
https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L250-L273

`container_fs_` metrics magnify due to the number of block devices mounted on the nodes.

**Comment by smarterclayton** [comment]
Number of unique series - 1 series is one metric and one unique combination of labels.  If you have a label with high cardinality (pod name) you get one series per label minimum.  

One problem with container_fs in general is that block devices aren't as useful - we have the domain model so we should know that certain block devices "belong" or are associated to pods.  I.e. a PVC belonging to prometheus should really be charged to prometheus.  This is one example where a more kube specific domain model for this metric would help.

**Comment by smarterclayton** [comment]
And we're broken again, going to have to strip out more

**Comment by LiliC** [comment]
@smarterclayton @sjenning I noticed that `container_memory_failures_total` is still one of the top high cardinality metrics in 4.3, while searching I found this is the only place we reference it in the openshift org. Was there any reason why container_memory_failures_total was not removed during this issue? Or can I safely drop it?
