### ISSUE TITLE
extended conformance install downward api failure

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#17519]
From https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17480/test_pull_request_origin_extended_conformance_install/3130/

or https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/3130/consoleFull

```
[k8s.io] Downward API volume
/tmp/openshift/shell/rpm/BUILD/origin-3.8.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:666
  should update annotations on modification [Conformance] [sig-storage] [Suite:openshift/conformance/parallel] [Suite:k8s] [It]
  /tmp/openshift/shell/rpm/BUILD/origin-3.8.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:154

  Timed out after 120.001s.
  Expected

<did not copy / paste the log data >

to contain substring
    <string>: builder="foo"
    
/tmp/openshift/shell/rpm/BUILD/origin-3.8.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:153
```

I found no errors for the downwardapi_volume pod in question in the node logs.  Nor could I find anything amiss in the master logs around the REST invocations for that pod.

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17516/test_pull_request_origin_extended_conformance_install/3219/
