### ISSUE TITLE
POD logs JSON to stdout, but log entries get wrapped with  {"log":<raw_log_data>}

### ISSUE THREAD

**Issue by raffian** [openshift/origin#17524]
We have Java apps in Openshift outputting logs as json to STDOUT, which is redirected to `/var/log/containers/<app>.log`; the raw json from the app -- before it's redirected -- looks something like this:

`{"@timestamp":"2017-11-29T11:19:47.853-05:00","level":"INFO","transactionId":"1234567”}`

..but after log entries end up in `/var/log/container/…` they appear to get wrapped inside another json object with key `log`; all quotes in the raw log data gets escaped with `\”`.

`{"log":"{\"@timestamp\":\"2017-11-29T15:28:20.257+00:00\",\"level\":\"INFO\",\"transactionId\":\"1234567\”}}`

We collect all log data using splunk and want to index data at collection time, unfortunately, when splunk collects these logs, the relevant data is no longer json, just plain text, so we can't index at collection time without using complex patterns/regex.

What configuration in Openshift handles this wrapping of log entries? 

λ oc version
oc v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7

**Comment by jcantrill** [comment]
> We collect all log data using splunk ...
How are you collecting via splunk?  Are you using fluentd forwarding to a custom splunk container? Are you collecting a log using your own container?

**Comment by raffian** [comment]
@jcantrill Splunk agent installed on all master/infra/app nodes, collects logs directly from `var/log/containers/...`

I don't believe splunk is the problem because the json logs generated from the app to STDOUT appear different after getting redirected to `/var/log/containers/...`, before splunk collects anything.

I think I understand what's wrapping the logs; `--log-driver` for dockerd is "json-file" by default, and we're not overriding any dockerd config:

```
> cat /etc/docker/daemon.json
{}```

Assuming I'm on the right track, `journald` is the only alternative which perhaps does not wrap raw log entries with another json object?

**Comment by smarterclayton** [comment]
@openshift/sig-pod

**Comment by raffian** [comment]
@smarterclayton  broken link?

**Comment by smarterclayton** [comment]
No, I'm assigning the appropriate team.

**Comment by sepulworld** [comment]
@raffian did you find a work around? We use a Splunk forwarder in a similar fashion and have this same issue.

**Comment by raffian** [comment]
No, we decided to leave docker and json-driver as-is. In splunk, instead of collection-time indexing, we use search-time indexing like this, works fine, queries take a little longer but it's negligible...

```
index=oridx
  | spath input=log
  | search appname="myapp"
    AND namespace="orders-dev" 
```

**Comment by abhij22** [comment]
@sepulworld If you wish to do it at index time as opposed to search time, you have to use a splunk heavy forwarder. Putting this in props.conf in the heavy forwarder solved it for us:
```

**Comment by raffian** [comment]
@abhij22 no changes to json-driver, just splunk heavy forwarder? looks interesting, will try it!
