### ISSUE TITLE
Unpredictable oc binary path for version 3.7.0

### ISSUE THREAD

**Issue by LalatenduMohanty** [openshift/origin#17527]
Till v3.7.0-rc.0 release `oc` binaries were published in github release page [1] but with 3.7.0 the location has changed and causing ` minishift start --openshift-version v3.7.0` to fail. 

From Minishift side we can change the code to point it to the new location but the new location is difficult to guess programmatically  e.g. ` https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/branch-logs/origin/v3.7.0/builds/test_branch_origin_cross/1032/artifacts/zips/` 

I can not figure out how we can predict the link for future Origin releases. If we can not predict the location then Minishift users can not use a new version of Origin without code changes in Minishift which is not desirable. 

[1] https://github.com/openshift/origin/releases/tag/v3.7.0-rc.0

##### Version
v3.7.0

**Comment by LalatenduMohanty** [comment]
Also we should not change stuff like this between v3.7.0-rc.0 and v3.7.0

**Comment by gbraad** [comment]
It seems to contain a build id: `/1032/` which makes it hard for third parties to determine the final release. At the moment we would have to extract the GitHub message and look in the release notes for the URL? :-/

**Comment by wanghaoran1988** [comment]
Maybe you can use the github related api to do this, related links:
https://developer.github.com/v3/repos/contents/#get-archive-link
https://developer.github.com/v3/repos/releases/
https://developer.github.com/v3/repos/downloads/
https://stackoverflow.com/questions/25923939/how-do-i-download-binary-files-of-a-github-release

**Comment by gbraad** [comment]
@wanghaoran1988 this is what we do, but we can not for 3.7.0, as there are NO releases in the actual release on GitHub => see #1771

**Comment by gbraad** [comment]
Notice the difference:

## v3.7.0-rc0
![image](https://user-images.githubusercontent.com/1894/33418403-a286010e-d5e0-11e7-962b-c8ff818cd3fa.png)


## v3.7.0
![image](https://user-images.githubusercontent.com/1894/33418368-7e9bca6c-d5e0-11e7-9298-636a1215aa2f.png)

For the v3.7.0 release the heading "Downloads" is not part of the GitHub downloads, but it is part of the release notes.

**Comment by budhrg** [comment]
Also, the URL 
```
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/branch-logs/origin/v3.7.0/builds/test_branch_origin_cross/1032/artifacts/zips/
```

contains lots of `test` term which is making thing more doubtful.

**Comment by wgordon17** [comment]
I see the builds have been re-included on the [releases page](https://github.com/openshift/origin/releases/tag/v3.7.1). Does this effectively solve this issue?

/remove-lifecycle stale

**Comment by budhrg** [comment]
> I see the builds have been re-included on the releases page. Does this effectively solve this issue?

Yes @wgordon17 it is solving at the moment. 
I think we can close this issue @LalatenduMohanty
