### ISSUE TITLE
Prometheus when installed to the cluster should start and expose a secured proxy and unsecured metrics

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17529]
```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/prometheus/prometheus.go:117
Did not find tsdb_samples_appended_total, tsdb_head_samples_appended_total, or prometheus_tsdb_head_samples_appended_total in:
map[string]*io_prometheus_client.MetricFamily(nil),
Expected
    <bool>: false
to be true
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/prometheus/prometheus.go:83
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17516/test_pull_request_origin_extended_conformance_gce/12132/

**Comment by mfojtik** [comment]
Seen here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17626/test_pull_request_origin_extended_conformance_gce/12464/

**Comment by theute** [comment]
@oourfali it seems to be an installer issue rather than an issue in P8s itself ?

**Comment by zgalor** [comment]
@kargakis was prometheus installed using openshift-ansible?
what inventory file was used?

**Comment by kargakis** [comment]
@zgalor this issue comes up in [extended_gce](https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_branch_origin_extended_conformance_gce.yml). Unclear how Prometheus is installed in that job but I think openshift ansible is used.

cc: @smarterclayton

**Comment by smarterclayton** [comment]
This is likely caused by #18317.  This is the stock prometheus config in origin.
