### ISSUE TITLE
oc: rollout latest doesn't auto-resolve deploymentconfig names

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#17521]
This is frustrating:

```
$ oc rollout latest jenkins-config-updater -n ci-openshift-ansible
deploymentconfig "jenkins-config-updater" rolled out
$ oc rollout status jenkins-config-updater -n ci-openshift-ansible
the server doesn't have a resource type "jenkins-config-updater"
```

/kind bug
/cc @kargakis @juanvallejo @fabianofranz 
@openshift/sig-user-interface

**Comment by kargakis** [comment]
Yes, `rollout` is not meant to auto-resolve to DCs since we want it to also work for upstream Deployments, StatefulSets, and DaemonSets.

cc: @mfojtik @tnozicka

**Comment by stevekuznetsov** [comment]
Wait, it's not? Why does it work for`rollout latest`? Would much rather have it auto-resolve in all cases.

**Comment by kargakis** [comment]
`latest` supports both formats but the NAME syntax is there probably for historical reasons and it's not something we want to spread.

**Comment by tnozicka** [comment]
Defaulting to one resource type is historical when it dealt only with DCs. We have 4 resources to deal with now and it is causing inconsistency. If we get enough courage we should deprecate the resource type defaulting.

**Comment by kargakis** [comment]
I didn't mention anything about deprecating because I am reminded of `oc logs` - we still support `oc logs PODNAME` and I am sure lots of people are using it.

**Comment by tnozicka** [comment]
Oh, I am quite positive people use this as well. We can still deprecate it and support it for several releases to allow them to migrate, right?

**Comment by stevekuznetsov** [comment]
NOTABUG

/close
