### ISSUE TITLE
Image stream status tags no longer sorted newest first

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#17552]
The web console relies on the server sorting the image stream status tags according to semver so that we can show the newest first in the UI. The tags no longer seem to be sorted in that order.

See

https://github.com/openshift/origin-web-catalog/issues/573
https://github.com/openshift/origin-web-console/pull/302

##### Version
oc v3.8.0-alpha.0+24cf6b7-321
kubernetes v1.8.1+0d5291c
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.8.0-alpha.0+33c21b7-276
kubernetes v1.8.1+0d5291c

##### Steps To Reproduce
Run

```
$ oc get -o yaml is/nodejs -n openshift
```

##### Current Result

The status tags are not sorted newest first.

##### Expected Result

The status tags for nodejs should be sorted 6, 4, 0.10.

cc @bparees @miminar

**Comment by miminar** [comment]
Why is it a responsibility of master API to return an array which is actually a serialized map (inherently unsorted) sorted?

This functionality isn't documented anywhere. It's the client's responsibility to sort items according to its liking - different client may have different sorting preferences and master shouldn't care.

**Comment by spadgett** [comment]
It was a change made to fix this bug:

https://bugzilla.redhat.com/show_bug.cgi?id=1325069
https://github.com/openshift/origin/pull/9606

We used to sort on the client. I believe it was changed to the server so we could get proper semver sorting since we don't have a client library for that.

**Comment by spadgett** [comment]
@jwforres
