### ISSUE TITLE
Build stuck on pending for hours

### ISSUE THREAD

**Issue by antaka1** [openshift/origin#17567]
I am trying to do the most basic stuff. I've created a new application using Tomcat and tried to build and deployed the application ( Spring Boot application) from GitHub ( public repo ).

##### Version
openshift v3.6.173.0.5
Servet https://api.starter-us-west-1.openshift.com:443

##### Steps To Reproduce
1. Create new app with Tomcat and add git url

##### Current Result
Build is stuck on pending status
On events tab I see the following message : No nodes are available that match all of the following predicates:: Insufficient memory (88), MatchNodeSelector (5).

##### Expected Result
Application is built and deployed

##### Additional Information
oc get all -o returns : 
`{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "BuildConfig",
            "metadata": {
                "annotations": {
                    "openshift.io/generated-by": "OpenShiftWebConsole"
                },
                "creationTimestamp": "2017-12-03T18:55:01Z",
                "labels": {
                    "app": "lp"
                },
                "name": "lp",
                "namespace": "lp",
                "resourceVersion": "475729598",
                "selfLink": "/oapi/v1/namespaces/lp/buildconfigs/lp",
                "uid": "7789b79e-d85b-11e7-94f1-06579ed29230"
            },
            "spec": {
                "nodeSelector": null,
                "output": {
                    "to": {
                        "kind": "ImageStreamTag",
                        "name": "lp:latest"
                    }
                },
                "postCommit": {},
                "resources": {},
                "runPolicy": "Serial",
                "source": {
                    "git": {
                        "ref": "master",
                        "uri": "https://github.com/antaka1/lp"
                    },
                    "type": "Git"
                },
                "strategy": {
                    "sourceStrategy": {
                        "from": {
                            "kind": "ImageStreamTag",
                            "name": "jboss-webserver30-tomcat8-openshift:1.3",
                            "namespace": "openshift"
                        }
                    },
                    "type": "Source"
                },
                "triggers": [
                    {
                        "generic": {
                            "secret": "753ce041436eea0c"
                        },
                        "type": "Generic"
                    },
                    {
                        "github": {
                            "secret": "33c47f4b88af129c"
                        },
                        "type": "GitHub"
                    },
                    {
                        "imageChange": {
                            "lastTriggeredImageID": "registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift@sha256:0089883f8e4387618946cd24378a447b8cf7e5dfaa146b94acab27fc5e170a14"
                        },
                        "type": "ImageChange"
                    },
                    {
                        "type": "ConfigChange"
                    }
                ]
            },
            "status": {
                "lastVersion": 1
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Build",
            "metadata": {
                "annotations": {
                    "openshift.io/build-config.name": "lp",
                    "openshift.io/build.number": "1",
                    "openshift.io/build.pod-name": "lp-1-build"
                },
                "creationTimestamp": "2017-12-03T18:55:01Z",
                "labels": {
                    "app": "lp",
                    "buildconfig": "lp",
                    "openshift.io/build-config.name": "lp",
                    "openshift.io/build.start-policy": "Serial"
                },
                "name": "lp-1",
                "namespace": "lp",
                "ownerReferences": [
                    {
                        "apiVersion": "build.openshift.io/v1",
                        "controller": true,
                        "kind": "BuildConfig",
                        "name": "lp",
                        "uid": "7789b79e-d85b-11e7-94f1-06579ed29230"
                    }
                ],
                "resourceVersion": "475729607",
                "selfLink": "/oapi/v1/namespaces/lp/builds/lp-1",
                "uid": "77914dc6-d85b-11e7-b468-06e7d92b1aa4"
            },
            "spec": {
                "nodeSelector": null,
                "output": {
                    "pushSecret": {
                        "name": "builder-dockercfg-z6r7t"
                    },
                    "to": {
                        "kind": "ImageStreamTag",
                        "name": "lp:latest"
                    }
                },
                "postCommit": {},
                "resources": {},
                "serviceAccount": "builder",
                "source": {
                    "git": {
                        "ref": "master",
                        "uri": "https://github.com/antaka1/lp"
                    },
                    "type": "Git"
                },
                "strategy": {
                    "sourceStrategy": {
                        "from": {
                            "kind": "DockerImage",
                            "name": "registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift@sha256:0089883f8e4387618946cd24378a447b8cf7e5dfaa146b94acab27fc5e170a14"
                        }
                    },
                    "type": "Source"
                },
                "triggeredBy": [
                    {
                        "imageChangeBuild": {
                            "fromRef": {
                                "kind": "ImageStreamTag",
                                "name": "jboss-webserver30-tomcat8-openshift:1.3",
                                "namespace": "openshift"
                            },
                            "imageID": "registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift@sha256:0089883f8e4387618946cd24378a447b8cf7e5dfaa146b94acab27fc5e170a14"
                        },
                        "message": "Image change"
                    }
                ]
            },
            "status": {
                "config": {
                    "kind": "BuildConfig",
                    "name": "lp",
                    "namespace": "lp"
                },
                "output": {},
                "outputDockerImageReference": "172.30.148.65:5000/lp/lp:latest",
                "phase": "Pending"
            }
        },
        {
            "apiVersion": "v1",
            "kind": "ImageStream",
            "metadata": {
                "annotations": {
                    "openshift.io/generated-by": "OpenShiftWebConsole"
                },
                "creationTimestamp": "2017-12-03T18:55:01Z",
                "generation": 1,
                "labels": {
                    "app": "lp"
                },
                "name": "lp",
                "namespace": "lp",
                "resourceVersion": "475729589",
                "selfLink": "/oapi/v1/namespaces/lp/imagestreams/lp",
                "uid": "778411a4-d85b-11e7-86ac-06d5ca59684e"
            },
            "spec": {
                "lookupPolicy": {
                    "local": false
                }
            },
            "status": {
                "dockerImageRepository": "172.30.148.65:5000/lp/lp"
            }
        },
        {
            "apiVersion": "v1",
            "kind": "DeploymentConfig",
            "metadata": {
                "annotations": {
                    "openshift.io/generated-by": "OpenShiftWebConsole"
                },
                "creationTimestamp": "2017-12-03T18:55:01Z",
                "generation": 1,
                "labels": {
                    "app": "lp"
                },
                "name": "lp",
                "namespace": "lp",
                "resourceVersion": "475729593",
                "selfLink": "/oapi/v1/namespaces/lp/deploymentconfigs/lp",
                "uid": "7783c424-d85b-11e7-86ac-06d5ca59684e"
            },
            "spec": {
                "replicas": 1,
                "selector": {
                    "deploymentconfig": "lp"
                },
                "strategy": {
                    "activeDeadlineSeconds": 21600,
                    "resources": {},
                    "rollingParams": {
                        "intervalSeconds": 1,
                        "maxSurge": "25%",
                        "maxUnavailable": "25%",
                        "timeoutSeconds": 600,
                        "updatePeriodSeconds": 1
                    },
                    "type": "Rolling"
                },
                "template": {
                    "metadata": {
                        "creationTimestamp": null,
                        "labels": {
                            "app": "lp",
                            "deploymentconfig": "lp"
                        }
                    },
                    "spec": {
                        "containers": [
                            {
                                "image": "lp:latest",
                                "imagePullPolicy": "Always",
                                "name": "lp",
                                "ports": [
                                    {
                                        "containerPort": 8080,
                                        "protocol": "TCP"
                                    },
                                    {
                                        "containerPort": 8443,
                                        "protocol": "TCP"
                                    },
                                    {
                                        "containerPort": 8778,
                                        "protocol": "TCP"
                                    }
                                ],
                                "resources": {},
                                "terminationMessagePath": "/dev/termination-log",
                                "terminationMessagePolicy": "File"
                            }
                        ],
                        "dnsPolicy": "ClusterFirst",
                        "restartPolicy": "Always",
                        "schedulerName": "default-scheduler",
                        "securityContext": {},
                        "terminationGracePeriodSeconds": 30
                    }
                },
                "test": false,
                "triggers": [
                    {
                        "imageChangeParams": {
                            "automatic": true,
                            "containerNames": [
                                "lp"
                            ],
                            "from": {
                                "kind": "ImageStreamTag",
                                "name": "lp:latest",
                                "namespace": "lp"
                            }
                        },
                        "type": "ImageChange"
                    },
                    {
                        "type": "ConfigChange"
                    }
                ]
            },
            "status": {
                "availableReplicas": 0,
                "conditions": [
                    {
                        "lastTransitionTime": "2017-12-03T18:55:01Z",
                        "lastUpdateTime": "2017-12-03T18:55:01Z",
                        "message": "Deployment config does not have minimum availability.",
                        "status": "False",
                        "type": "Available"
                    }
                ],
                "latestVersion": 0,
                "observedGeneration": 1,
                "replicas": 0,
                "unavailableReplicas": 0,
                "updatedReplicas": 0
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Route",
            "metadata": {
                "annotations": {
                    "openshift.io/generated-by": "OpenShiftWebConsole",
                    "openshift.io/host.generated": "true"
                },
                "creationTimestamp": "2017-12-03T18:55:01Z",
                "labels": {
                    "app": "lp"
                },
                "name": "lp",
                "namespace": "lp",
                "resourceVersion": "475729595",
                "selfLink": "/oapi/v1/namespaces/lp/routes/lp",
                "uid": "77877829-d85b-11e7-94f1-06579ed29230"
            },
            "spec": {
                "host": "lp-lp.a3c1.starter-us-west-1.openshiftapps.com",
                "port": {
                    "targetPort": "8080-tcp"
                },
                "to": {
                    "kind": "Service",
                    "name": "lp",
                    "weight": 100
                },
                "wildcardPolicy": "None"
            },
            "status": {
                "ingress": [
                    {
                        "conditions": [
                            {
                                "lastTransitionTime": "2017-12-03T18:55:01Z",
                                "status": "True",
                                "type": "Admitted"
                            }
                        ],
                        "host": "lp-lp.a3c1.starter-us-west-1.openshiftapps.com",
                        "routerCanonicalHostname": "elb.a3c1.starter-us-west-1.openshiftapps.com",
                        "routerName": "router",
                        "wildcardPolicy": "None"
                    }
                ]
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "annotations": {
                    "openshift.io/generated-by": "OpenShiftWebConsole"
                },
                "creationTimestamp": "2017-12-03T18:55:01Z",
                "labels": {
                    "app": "lp"
                },
                "name": "lp",
                "namespace": "lp",
                "resourceVersion": "475729596",
                "selfLink": "/api/v1/namespaces/lp/services/lp",
                "uid": "7789f87c-d85b-11e7-b468-06e7d92b1aa4"
            },
            "spec": {
                "clusterIP": "172.30.153.54",
                "ports": [
                    {
                        "name": "8080-tcp",
                        "port": 8080,
                        "protocol": "TCP",
                        "targetPort": 8080
                    },
                    {
                        "name": "8443-tcp",
                        "port": 8443,
                        "protocol": "TCP",
                        "targetPort": 8443
                    },
                    {
                        "name": "8778-tcp",
                        "port": 8778,
                        "protocol": "TCP",
                        "targetPort": 8778
                    }
                ],
                "selector": {
                    "deploymentconfig": "lp"
                },
                "sessionAffinity": "None",
                "type": "ClusterIP"
            },
            "status": {
                "loadBalancer": {}
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Pod",
            "metadata": {
                "annotations": {
                    "kubernetes.io/limit-ranger": "LimitRanger plugin set: cpu, memory request for container sti-build; cpu, memory limit for container sti-build",
                    "openshift.io/build.name": "lp-1",
                    "openshift.io/scc": "privileged"
                },
                "creationTimestamp": "2017-12-03T18:55:01Z",
                "labels": {
                    "openshift.io/build.name": "lp-1"
                },
                "name": "lp-1-build",
                "namespace": "lp",
                "ownerReferences": [
                    {
                        "apiVersion": "build.openshift.io/v1",
                        "controller": true,
                        "kind": "Build",
                        "name": "lp-1",
                        "uid": "77914dc6-d85b-11e7-b468-06e7d92b1aa4"
                    }
                ],
                "resourceVersion": "475729604",
                "selfLink": "/api/v1/namespaces/lp/pods/lp-1-build",
                "uid": "7795ae04-d85b-11e7-b468-06e7d92b1aa4"
            },
            "spec": {
                "activeDeadlineSeconds": 3600,
                "containers": [
                    {
                        "args": [
                            "--loglevel=0"
                        ],
                        "env": [
                            {
                                "name": "BUILD",
                                "value": "{\"kind\":\"Build\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"lp-1\",\"namespace\":\"lp\",\"selfLink\":\"/apis/build.openshift.io/v1/namespaces/lp/builds/lp-1\",\"uid\":\"77914dc6-d85b-11e7-b468-06e7d92b1aa4\",\"resourceVersion\":\"475729599\",\"creationTimestamp\":\"2017-12-03T18:55:01Z\",\"labels\":{\"app\":\"lp\",\"buildconfig\":\"lp\",\"openshift.io/build-config.name\":\"lp\",\"openshift.io/build.start-policy\":\"Serial\"},\"annotations\":{\"openshift.io/build-config.name\":\"lp\",\"openshift.io/build.number\":\"1\"},\"ownerReferences\":[{\"apiVersion\":\"build.openshift.io/v1\",\"kind\":\"BuildConfig\",\"name\":\"lp\",\"uid\":\"7789b79e-d85b-11e7-94f1-06579ed29230\",\"controller\":true}]},\"spec\":{\"serviceAccount\":\"builder\",\"source\":{\"type\":\"Git\",\"git\":{\"uri\":\"https://github.com/antaka1/lp\",\"ref\":\"master\"}},\"strategy\":{\"type\":\"Source\",\"sourceStrategy\":{\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift@sha256:0089883f8e4387618946cd24378a447b8cf7e5dfaa146b94acab27fc5e170a14\"},\"forcePull\":true}},\"output\":{\"to\":{\"kind\":\"DockerImage\",\"name\":\"172.30.148.65:5000/lp/lp:latest\"},\"pushSecret\":{\"name\":\"builder-dockercfg-z6r7t\"}},\"resources\":{},\"postCommit\":{},\"nodeSelector\":null,\"triggeredBy\":[{\"message\":\"Image change\",\"imageChangeBuild\":{\"imageID\":\"registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift@sha256:0089883f8e4387618946cd24378a447b8cf7e5dfaa146b94acab27fc5e170a14\",\"fromRef\":{\"kind\":\"ImageStreamTag\",\"namespace\":\"openshift\",\"name\":\"jboss-webserver30-tomcat8-openshift:1.3\"}}}]},\"status\":{\"phase\":\"New\",\"outputDockerImageReference\":\"172.30.148.65:5000/lp/lp:latest\",\"config\":{\"kind\":\"BuildConfig\",\"namespace\":\"lp\",\"name\":\"lp\"},\"output\":{}}}\n"
                            },
                            {
                                "name": "SOURCE_REPOSITORY",
                                "value": "https://github.com/antaka1/lp"
                            },
                            {
                                "name": "SOURCE_URI",
                                "value": "https://github.com/antaka1/lp"
                            },
                            {
                                "name": "SOURCE_REF",
                                "value": "master"
                            },
                            {
                                "name": "ORIGIN_VERSION",
                                "value": "v3.6.173.0.5"
                            },
                            {
                                "name": "ALLOWED_UIDS",
                                "value": "1-"
                            },
                            {
                                "name": "DROP_CAPS",
                                "value": "KILL,MKNOD,SETGID,SETUID,SYS_CHROOT"
                            },
                            {
                                "name": "PUSH_DOCKERCFG_PATH",
                                "value": "/var/run/secrets/openshift.io/push"
                            }
                        ],
                        "image": "registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder:v3.6.173.0.5",
                        "imagePullPolicy": "Always",
                        "name": "sti-build",
                        "resources": {
                            "limits": {
                                "cpu": "1",
                                "memory": "512Mi"
                            },
                            "requests": {
                                "cpu": "60m",
                                "memory": "307Mi"
                            }
                        },
                        "securityContext": {
                            "privileged": true
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "FallbackToLogsOnError",
                        "volumeMounts": [
                            {
                                "mountPath": "/var/run/docker.sock",
                                "name": "docker-socket"
                            },
                            {
                                "mountPath": "/var/run/secrets/openshift.io/push",
                                "name": "builder-dockercfg-z6r7t-push",
                                "readOnly": true
                            },
                            {
                                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "name": "builder-token-hzm49",
                                "readOnly": true
                            }
                        ]
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "imagePullSecrets": [
                    {
                        "name": "builder-dockercfg-z6r7t"
                    }
                ],
                "nodeSelector": {
                    "type": "compute"
                },
                "restartPolicy": "Never",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "serviceAccount": "builder",
                "serviceAccountName": "builder",
                "terminationGracePeriodSeconds": 30,
                "volumes": [
                    {
                        "hostPath": {
                            "path": "/var/run/docker.sock"
                        },
                        "name": "docker-socket"
                    },
                    {
                        "name": "builder-dockercfg-z6r7t-push",
                        "secret": {
                            "defaultMode": 420,
                            "secretName": "builder-dockercfg-z6r7t"
                        }
                    },
                    {
                        "name": "builder-token-hzm49",
                        "secret": {
                            "defaultMode": 420,
                            "secretName": "builder-token-hzm49"
                        }
                    }
                ]
            },
            "status": {
                "conditions": [
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2017-12-03T18:55:01Z",
                        "message": "No nodes are available that match all of the following predicates:: Insufficient memory (88), MatchNodeSelector (5).",
                        "reason": "Unschedulable",
                        "status": "False",
                        "type": "PodScheduled"
                    }
                ],
                "phase": "Pending",
                "qosClass": "Burstable"
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Pod",
            "metadata": {
                "annotations": {
                    "kubernetes.io/limit-ranger": "LimitRanger plugin set: cpu, memory request for container pod-diagnostics; cpu, memory limit for container pod-diagnostics",
                    "openshift.io/scc": "restricted"
                },
                "creationTimestamp": "2017-12-03T19:14:48Z",
                "generateName": "pod-diagnostic-test-",
                "name": "pod-diagnostic-test-l099b",
                "namespace": "lp",
                "resourceVersion": "475762465",
                "selfLink": "/api/v1/namespaces/lp/pods/pod-diagnostic-test-l099b",
                "uid": "3b2761df-d85e-11e7-94f1-06579ed29230"
            },
            "spec": {
                "activeDeadlineSeconds": 3600,
                "containers": [
                    {
                        "command": [
                            "openshift",
                            "infra",
                            "diagnostic-pod",
                            "-l",
                            "1"
                        ],
                        "image": "registry.access.redhat.com/openshift3/ose-deployer:v3.6.173.0.5",
                        "imagePullPolicy": "Always",
                        "name": "pod-diagnostics",
                        "resources": {
                            "limits": {
                                "cpu": "1",
                                "memory": "512Mi"
                            },
                            "requests": {
                                "cpu": "60m",
                                "memory": "307Mi"
                            }
                        },
                        "securityContext": {
                            "capabilities": {
                                "drop": [
                                    "KILL",
                                    "MKNOD",
                                    "NET_RAW",
                                    "SETGID",
                                    "SETUID",
                                    "SYS_CHROOT"
                                ]
                            },
                            "privileged": false,
                            "runAsUser": 1072520000,
                            "seLinuxOptions": {
                                "level": "s0:c269,c214"
                            }
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "volumeMounts": [
                            {
                                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "name": "default-token-tz2l2",
                                "readOnly": true
                            }
                        ]
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "imagePullSecrets": [
                    {
                        "name": "default-dockercfg-jv181"
                    }
                ],
                "nodeSelector": {
                    "type": "compute"
                },
                "restartPolicy": "Never",
                "schedulerName": "default-scheduler",
                "securityContext": {
                    "fsGroup": 1072520000,
                    "seLinuxOptions": {
                        "level": "s0:c269,c214"
                    }
                },
                "serviceAccount": "default",
                "serviceAccountName": "default",
                "terminationGracePeriodSeconds": 30,
                "volumes": [
                    {
                        "name": "default-token-tz2l2",
                        "secret": {
                            "defaultMode": 420,
                            "secretName": "default-token-tz2l2"
                        }
                    }
                ]
            },
            "status": {
                "conditions": [
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2017-12-03T19:14:48Z",
                        "message": "No nodes are available that match all of the following predicates:: Insufficient memory (88), MatchNodeSelector (5).",
                        "reason": "Unschedulable",
                        "status": "False",
                        "type": "PodScheduled"
                    }
                ],
                "phase": "Pending",
                "qosClass": "Burstable"
            }
        }
    ],
    "kind": "List",
    "metadata": {},
    "resourceVersion": "",
    "selfLink": ""
}
`

**Comment by antaka1** [comment]
Update : the build is completed now but the deployment fails with the following error :

W1204 15:27:53.359451       1 reflector.go:323] github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:509: watch of *api.Pod ended with: too old resource version: 477843242 (477872712)
error: update acceptor rejected lp-3: pods for rc "lp-3" took longer than 600 seconds to become ready

**Comment by bparees** [comment]
> Build is stuck on pending status
On events tab I see the following message : No nodes are available that match all of the following predicates:: Insufficient memory (88), MatchNodeSelector (5).

@mfojtik that would pretty clearly point to infrastructure issues.  But now it's a deployment issue anyway (though probably really an infrastructure issue also, likely a container failing to start?):

> W1204 15:27:53.359451 1 reflector.go:323] github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:509: watch of *api.Pod ended with: too old resource version: 477843242 (477872712)
error: update acceptor rejected lp-3: pods for rc "lp-3" took longer than 600 seconds to become ready

**Comment by mfojtik** [comment]
@bparees seems like `Insufficient memory` might mean it is not able to find a node with enough memory to run the build?

**Comment by bparees** [comment]
> @bparees seems like Insufficient memory might mean it is not able to find a node with enough memory to run the build?

insufficient memory presumably means the cluster can't find a node w/o enough memory to meet the pod's "memory request" value.  In this case, the pod's request is typical, 300megs:

```
"image": "registry.reg-aws.openshift.com:443/openshift3/ose-sti-builder:v3.6.173.0.5", "imagePullPolicy": "Always", "name": "sti-build", "resources": { "limits": { "cpu": "1", "memory": "512Mi" }, "requests": { "cpu": "60m", "memory": "307Mi" } },
```
