### ISSUE TITLE
Misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#17570]
On OSX with the latest master (on empty config dir) you get this when running via `oc cluster up`:

```
F1204 10:44:52.886699   28172 node.go:264] failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"
```

I figured that to fix this you have to stick this into node-config.yaml:

```
kubeletArguments:
  cgroup-driver:
  - "cgroupfs"
```

@smarterclayton @sjenning i wonder if we should make this default for cluster up.

**Comment by sjenning** [comment]
@mfojtik when was the last version that defaulted to cgroupfs?

since fedora/centos/rhel all use systemd, that is the safe default.  though, iiuc, it seems like it was able to autodetect this in the past? or the default changed?

**Comment by smarterclayton** [comment]
Might be a bug caused by refactoring the master config and defaulting

**Comment by sjenning** [comment]
seems there is code to handle this:
https://github.com/openshift/origin/pull/13964/files

maybe it isn't working right on OSX?

**Comment by mfojtik** [comment]
@sjenning @smarterclayton yeah, on OSX this is broken, the `oc cluster up` fails with:

```
     F1211 09:38:19.639482   29754 node.go:264] failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"
```

**Comment by mfojtik** [comment]
I think I found the problem... It seems to be related to version detection for Docker on Mac (it use different semver...)

**Comment by mfojtik** [comment]
Alright, pebkac... I had some old `oc` for testing stuff in 3.6 branch... The detection is enabled starting at version 3.7...

**Comment by kareiva** [comment]
This issue still persists with`oc cluster up --version=v3.9.0-alpha.3`

**Comment by jkroepke** [comment]
Even on v3.9.0 GA

**Comment by alberttwong** [comment]
Confirmed issue on latest v3.9.30-2

```
albertredhatcom-MacBook-Pro:~ alwong$ oc cluster up --create-machine=true                   --use-existing-config                   --host-data-dir=/tmp                 --metrics=true                          --image=registry.access.redhat.com/openshift3/ose                 --version=latest
```

**Comment by alberttwong** [comment]
So it's fixed after I resetted my docker machine (mac 17.09.1-ce-mac42) and then running

`oc cluster up --image=registry.access.redhat.com/openshift3/ose --version=latest`
