### ISSUE TITLE
oc cluster up --logging rewrite config to ~/.kube/config file instead append

### ISSUE THREAD

**Issue by praveenkumar** [openshift/origin#17592]
`oc cluster up --logging` currently destroy (rewrite) ~/.kube/config instead append the kube configuration.

##### Version
[provide output of the `openshift version` or `oc version` command]
```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. Check your current `~/.kube/config` file.

```
$ cat ~/.kube/config | wc -l
76
```

2. Start oc cluster up using `logging` option

```
$ oc cluster up --logging
[...]
OpenShift server started.

The server is accessible via web console at:
    https://127.0.0.1:8443

The kibana logging UI is available at:
    https://kibana-logging.127.0.0.1.nip.io

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

```

3. Check again your `~/.kube/config` file content.
```
$ cat ~/.kube/config | wc -l
38
```

##### Current Result
oc cluster up rewrite existing `~/.kube/config` file instead append.

##### Expected Result
config should be appended.

**Comment by praveenkumar** [comment]
CC @csrwng

**Comment by csrwng** [comment]
@praveenkumar is this still an issue?
