### ISSUE TITLE
Flake: [Feature:Builds][pruning] prune builds based on settings in the buildconfig should prune completed builds based on the successfulBuildsHistoryLimit setting [Suite:openshift/conformance/parallel] 

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#17601]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17513/test_pull_request_origin_extended_conformance_install/3498/

```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:102
Expected
    <bool>: false
to be true
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:68
```

**Comment by bparees** [comment]
Failed due to dev mapper, there's an open issue for that already (owned by the container team)

**Comment by tnozicka** [comment]
please link the issue when you are closing it as dupe

**Comment by bparees** [comment]
@tnozicka was responding on my phone.  Didn't really consider linking the dupe all that important in this case.  but here: https://github.com/openshift/origin/issues/17330
