### ISSUE TITLE
executing 'oc get secrets -o name --all-namespaces; oc describe appliedclusterresourcequota/for-deads-by-annotation -n quota-bar --as deads' expecting any result and text 'secrets.

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17604]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17599/test_pull_request_origin_cmd/6974/

@deads2k you've got your name on it, you own it

/assign deads2k 
/kind test-flake
/sig master

**Comment by mfojtik** [comment]
@deads2k flaked 11 times in last 5 days (http://snowstorm-dev.app.mfojtik.io)

**Comment by deads2k** [comment]
> @deads2k flaked 11 times in last 5 days (http://snowstorm-dev.app.mfojtik.io)

I was looking for this.  Fixed by https://github.com/openshift/origin/pull/18338
