### ISSUE TITLE
Extended.[Feature:Prometheus][Feature:Builds] Prometheus when installed to the cluster should start and expose a secured proxy and verify build metrics

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#17629]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/299/testReport/junit/(root)/Extended/_Feature_Prometheus__Feature_Builds__Prometheus_when_installed_to_the_cluster_should_start_and_expose_a_secured_proxy_and_verify_build_metrics__Suite_openshift_conformance_parallel_/

**Comment by jim-minter** [comment]
I think the issue is that the test ran concurrently with some other builds, which showed as Cancelled.  Therefore the terminal test which expected # Cancelled builds to be zero failed.

**Comment by jim-minter** [comment]
I'm not sure if there's much else to be done but remove the tests which expect # Cancelled and # Failed each to be zero?

**Comment by gabemontero** [comment]
I think your cause analysis is spot on @jim-minter - I come to the same conclusion

And yeah, with tests running concurrently (I failed to remember that detail when first constructing the tests, and to be frank, I'm surprised this is the first we've noticed this), and the total metric being cross namespace, testing for precise values for *ANY* of the states is problematic.  We's either need to

a) somehow cross reference with the active_time_seconds, which has namespace, but that is problematic with the prometheus sliding window wrt those constant metrics

b) marking the suite as serial came to mind, but even still, it depends on which tests ran first ... prior tests may have left builds in cancelled, etc.

c) just test to make sure we get a propertly structured response from the query with this end to end flow, but ignore the values.  The end to end flow was really what I wanted to still cover when we left this extended test in after adding the unit tests that were patterned off of what you did with templates (and those verifies precise values).

I'm leaning to c), but will pause for response comments before diving in.

@bparees fyi ^^

**Comment by bparees** [comment]
As a slight variation on (c) you can just check that the values are greater than or equal to what you expect.  (which admittedly in the case of expecting zero, is a pretty loose test but at least ensures something is being returned, as @gabemontero aluded to in (c))
