### ISSUE TITLE
Configure nodes [localhost] openshift_node : Restart cri-o

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17622]
This test fails consistently in the postsubmit job for crio.

https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/test_branch_origin_extended_conformance_crio/195/
https://deck-ci.svc.ci.openshift.org/?type=postsubmit&job=test_branch_origin_extended_conformance_crio

/assign mrunalp runcom 
/area tests

**Comment by runcom** [comment]
This is an issue with the installer, not an original test failure. We're discussing it here https://github.com/openshift/aos-cd-jobs/pull/901#issuecomment-349451695

**Comment by kargakis** [comment]
Awesome.
