### ISSUE TITLE
node exporter runs only on nodes with region=primary label

### ISSUE THREAD

**Issue by mrsiano** [openshift/origin#17639]
In order to use node-exporter we have to issue the command 
`oc annotate ns openshift-metrics openshift.io/node-selector= --overwrite`

otherwise, the node selector pod + node exporter pods will fail, or will work only for primary node
 
Bug-Url:
https://bugzilla.redhat.com/show_bug.cgi?id=1522797

##### Version
openshift v3.7.0-0.190.0

**Comment by pweil-** [comment]
as this is already tracked in Bugzilla I am closing the GH issue.  Thanks for providing the link!
