### ISSUE TITLE
3.7.0 cluster can't run pods: MountVolume.SetUp failed for volume...

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#17638]
Cluster was created by `oc cluster up --version=v3.7.0`

```
$ oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

All pod (including deployers for registry and router) are stuck on `ContainerCreating` (https://travis-ci.org/tnozicka/openshift-acme/builds/312537376#L1389)

This error is repeating very frequently:

```
E1206 17:38:26.399937    9919 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/secret/439509e0-daac-11e7-8160-42010a1400bd-deployer-token-kbtwg\" (\"439509e0-daac-11e7-8160-42010a1400bd\")" failed. No retries permitted until 2017-12-06 17:38:26.89990613 +0000 UTC (durationBeforeRetry 500ms). Error: MountVolume.SetUp failed for volume "deployer-token-kbtwg" (UniqueName: "kubernetes.io/secret/439509e0-daac-11e7-8160-42010a1400bd-deployer-token-kbtwg") pod "router-1-deploy" (UID: "439509e0-daac-11e7-8160-42010a1400bd") : exit status 1
```

master log is here: https://travis-ci.org/tnozicka/openshift-acme/builds/312537376#L2196

**Comment by tnozicka** [comment]
(3.6.1 works fine)

**Comment by sjenning** [comment]
When I try, I get this error event on all pods:
```
Error: failed to start container "deployment": Error response from daemon: {"message":"oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:364: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/var/lib/origin/openshift.local.volumes/pods/63c18b21-def4-11e7-a418-1c1b0deeddfa/volumes/kubernetes.io~secret/deployer-token-vz4gl\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/65e637731cffd516b61a69293b3e354f3d3a4472bdf2bd57723dd469b477d043/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/65e637731cffd516b61a69293b3e354f3d3a4472bdf2bd57723dd469b477d043/merged/run/secrets/kubernetes.io/serviceaccount\\\\\\\" caused \\\\\\\"mkdir /var/lib/docker/overlay2/65e637731cffd516b61a69293b3e354f3d3a4472bdf2bd57723dd469b477d043/merged/run/secrets/kubernetes.io: read-only file system\\\\\\\"\\\"\"\n"}
```
@jsafrane likely a problem with containerized node mounting volume.  Any help?

**Comment by jsafrane** [comment]
Containerized mount is alpha (i.e. behind a feature gate) in 1.9, mount propagation is alpha in 1.8, still behind a gate. This must be something else.

**Comment by sjenning** [comment]
@joelsmith PTAL

**Comment by tnozicka** [comment]
oc cluster up for 3.7.1 seems borked as well https://github.com/openshift/origin/issues/18262

**Comment by tnozicka** [comment]
@joelsmith bump

I'll like to see what's the root cause of it ; with 3.9 approaching we should figure out what's the cause so we don't release it broken even for 3.9

**Comment by tnozicka** [comment]
see some concrete failures at loglevel 5
```
I0212 20:04:21.647681    8190 nsenter_mount.go:117] nsenter Mounting tmpfs /var/lib/origin/openshift.local.volumes/pods/ea020a4a-102f-11e8-8a53-42010a1400d9/volumes/kubernetes.io~secret/pvinstaller-token-ff4ks tmpfs []
I0212 20:04:21.647692    8190 nsenter_mount.go:120] Mount command: nsenter [--mount=/rootfs/proc/1/ns/mnt -- /systemd-run --description=Kubernetes transient mount for /var/lib/origin/openshift.local.volumes/pods/ea020a4a-102f-11e8-8a53-42010a1400d9/volumes/kubernetes.io~secret/pvinstaller-token-ff4ks --scope -- /bin/mount -t tmpfs tmpfs /var/lib/origin/openshift.local.volumes/pods/ea020a4a-102f-11e8-8a53-42010a1400d9/volumes/kubernetes.io~secret/pvinstaller-token-ff4ks]
I0212 20:04:21.661500    8190 create_dockercfg_secrets.go:147] Updating token secret acme-aaa/builder-token-8tjgm
I0212 20:04:21.669942    8190 graph_builder.go:475] GraphBuilder process object: v1/Secret, namespace acme-aaa, name builder-token-8tjgm, uid ea39dc52-102f-11e8-8a53-42010a1400d9, event type update
I0212 20:04:21.694406    8190 nsenter_mount.go:234] Failed findmnt command for path /var/lib/origin/openshift.local.volumes/pods/ea04c0b9-102f-11e8-8a53-42010a1400d9/volumes/kubernetes.io~secret/deployer-token-jh78d: exit status 1
```

**Comment by tnozicka** [comment]
travis is missing `nsenter` and the detection kube is wrong (per https://github.com/openshift/origin/issues/17017#issuecomment-339085804)

**Comment by joelsmith** [comment]
@tnozicka I'm not sure that is the issue you're seeing in 3.7 since it shouldn't be using the containerized kubelet in 3.7. If you've moved on to 3.9, then perhaps that is responsible for your issue. Either way, I've opened an upstream PR to address the broken detection. https://github.com/kubernetes/kubernetes/pull/59770

**Comment by tnozicka** [comment]
@joelsmith thanks for addressing the detection. Here is where I got: I am running v3.7.1 but travis was missing `nsenter`, after I've compiled it manually it now fails on missing `systemd-run` which I am trying to address now to see where it takes me

**Comment by tnozicka** [comment]
```
nsenter_mount.go:124] Output of mounting tmpfs to /var/lib/origin/openshift.local.volumes/pods/ab316326-104a-11e8-976e-42010a140032/volumes/kubernetes.io~secret/pvinstaller-token-hc7zd: nsenter: failed to execute /systemd-run: No such file or directory
```

**Comment by joelsmith** [comment]
There is a related issue that prevents pods from starting if they try to mount secrets. The issue has been reported to occur on Fedora 26 and 27 and produces the error that @sjenning mentioned above. If you see anything like this:
`caused \\\\\\\"mkdir /var/lib/docker/ ...snip...  /run/secrets/kubernetes.io: read-only file system\\\\\\\"\\\"\"\n"}`
Then there's a good chance that your docker is affected.

See  https://bugzilla.redhat.com/show_bug.cgi?id=1504709 and #15038 for more information. If you are running docker on Fedora 26 and 27, you can try updating your docker. If you are using docker-latest, the latest packages may not have a fix yet. You could try the work-around mentioned in https://github.com/openshift/origin/issues/15038#issuecomment-345252400 which is (edited to be less drastic):
```
mv /usr/share/rhel/secrets /usr/share/rhel/secrets.bak
```

**Comment by tnozicka** [comment]
This is Travis CI - so Ubuntu Trusty unfortunately still on InitV; although there are some detections in kube for systemd-run (not present there), it still tries to use it

**Comment by tnozicka** [comment]
So I've finally got this working with the 2 hacks bellow confirming what's the exact issue is.

1. `oc cluster up` >=3.7 requires `nsenter`
I don't think there is a way to avoid it's just required.
**Action item**: We should fail with `nsenter` not present. (Now we just log "... exit 1" on Info level 5 and continue.)

2. `oc cluster up` >=3.7 has a bug detecting Systemd vs. Init and forces `systemd-run` calls even when running on Init.
**Action item**: We need to backport https://github.com/kubernetes/kubernetes/pull/59786 to release-3.7 (and higher)

```
    # OpenShift >= 3.7 requires nsenter
    if ! which nsenter > /dev/null; then
      echo "Did not find nsenter. Installing it."
      NSENTER_BUILD_DIR=$(mktemp -d /tmp/nsenter-build-XXXXXX)
      pushd ${NSENTER_BUILD_DIR}
      curl https://www.kernel.org/pub/linux/utils/util-linux/v2.31/util-linux-2.31.tar.gz | tar -zxf-
      cd util-linux-2.31
      ./configure --without-ncurses
      make nsenter
      sudo cp nsenter /usr/local/bin
      rm -rf "${NSENTER_BUILD_DIR}"
      popd
    fi
    # OpenShift >= 3.7 requires systemd-run (but Ubuntu Trusty still uses Init)
    # Should be in Kubernetes to correctly detect if systemd-run is present -
    # Hack it till then
    if ! which systemd-run > /dev/null; then
      echo "Did not find systemd-run. Hacking it to work around Kubernetes calling it."
      echo '#!/bin/bash
      echo "all arguments: "$@
      while [[ $# -gt 0 ]]
      do
        key="$1"
        if [[ "${key}" != "--" ]]; then
          shift
          continue
        fi
        shift
        break
      done
      echo "remaining args: "$@
      exec $@' | sudo tee /usr/bin/systemd-run >/dev/null
      sudo chmod +x /usr/bin/systemd-run
    fi
```

**Comment by joelsmith** [comment]
Nice work figuring it out! Once the upstream detection PR is ready, we can try to get it backported for 3.9. But I'm not sure how high of a priority it will be considering that we mostly only support distros that have nsenter and systemd. So if the backport isn't pretty quick, this will probably not be considered a blocker for 3.9.

**Comment by tnozicka** [comment]
Sure, we don't want to block 3.9 release for this as it is now conformed that it doesn't affect the main platforms; backport is fine.
