### ISSUE TITLE
Extended.[image_ecosystem][Slow] openshift sample application repositories [image_ecosystem][nodejs] test nodejs images with nodejs-ex db repo Building nodejs-mongodb app from new-app should build a nodejs-mongodb image and run it in a pod [Suite:openshift]

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#17649]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/305/testReport/junit/(root)/Extended/_image_ecosystem__Slow__openshift_sample_application_repositories__image_ecosystem__nodejs__test_nodejs_images_with_nodejs_ex_db_repo__Building_nodejs_mongodb_app_from_new_app_should_build_a_nodejs_mongodb_image_and_run_it_in_a_pod__Suite_openshift_/

**Comment by jim-minter** [comment]
Nodejs server never returned a page with page view count "1".  Bit of a mystery.

**Comment by jim-minter** [comment]
Closing because additional debug has been added and haven't seen recurrence

**Comment by legionus** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/397/

**Comment by bparees** [comment]
from what i've seen this crops up periodically when the nodejs app seems to report no connection to the DB even though the DB should be up before the nodejs app starts.  Needs further investigation, should be easy to reproduce locally (provision the template, hit the app, see if you get no DB connection)

/assign @wozniakjan

**Comment by bparees** [comment]
(in some cases the nodejs page shows no DB connection, but it's actually incrementing the mongodb counter value and then eventually the page shows the new total, so we never see "1")

**Comment by wozniakjan** [comment]
https://github.com/openshift/origin/pull/19584 given we now tolerate any nonzero page count, is it safe to assume this issue can be closed?

cc @jim-minter @bparees @coreydaley

**Comment by bparees** [comment]
yeah we'll hopefully not see this anymore w/ that test change.
