### ISSUE TITLE
OpenShift and billing

### ISSUE THREAD

**Issue by roberto-gomez** [openshift/origin#1764]
Hello.

I am very interested in if you have some idea or plan for the billing in OpenShift v3

**Comment by roldancer** [comment]
Hi, any idea how will be the billing system/report for OPenShift V3 ?

**Comment by smarterclayton** [comment]
If your'e looking for snapshots of usage, you will be able to use the resource limits and resource quotas objects to capture the full usage of the system at any point in time.  You'll be able to capture at periodic intervals the number of items of each quantity in use and process that as you like.

To see instantaneous usage (pods used per hour) you can watch the global pods list and record that as "pod create" and "pod delete" and record the usage to your own records (I have a few examples based on watching etcd here https://github.com/openshift/origin/compare/master...smarterclayton:archiver which is one way of extracting this data).  It should be easy to capture and transform usage data from the system for your own needs - it's possible today though to grab and transform the data on the fly.

That's what is there today - coming in the future:

We are working upstream in Kubernetes on total process resource usage (actual, vs provisioned) and rolling that up and reporting it via cAdvisor and Heapster.  That will be post 3.0.  

Post 3.0, we'll also be looking at rolling up quota based on "accounts" - projects will be bucketed under one or more accounts, and those accounts can have quota and limits of their own.  That will be complemented by tools to make it easier to build a full audit log of your entire cluster and deployment, which you can feed into other tools to pull that information.

**Comment by SoothingMist** [comment]
Am unable to see how to limit the amount of money the account can absorb. There needs to be an easy way to do that.

**Comment by dragon9783** [comment]
LGTM

**Comment by alikhajeh1** [comment]
@smarterclayton any update or links we can checkout to learn more about your future plans?

**Comment by sspeiche** [comment]
I think the best way to handle this is to look at how solutions were done with [tools like ManageIQ/CloudForms](https://access.redhat.com/documentation/en/red-hat-cloudforms/4.0/monitoring-alerts-and-reporting/chapter-5-chargeback) There is no plans to provide native support for billing.
