### ISSUE TITLE
no matches for servicecatalog.k8s.io

### ISSUE THREAD

**Issue by megian** [openshift/origin#17642]
##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master1:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
##### Steps To Reproduce
ansible-playbook -i hosts playbooks/byo/openshift-cluster/service-catalog.yml

##### Current Result
TASK [ansible_service_broker : Create the Broker resource in the catalog]
fatal: [master1]: FAILED! => {"changed": false, "failed": true, "msg": {"cmd": "/usr/local/bin/oc create -f /tmp/brokerout-2AWk1W -n default", "results": {}, "returncode": 1, "stderr": "error: unable to recognize \"/tmp/brokerout-2AWk1W\": no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker\n", "stdout": ""}}

##### Expected Result
no error

**Comment by cscetbon** [comment]
@megian Can you tell me why you closed this issue. I got the same error. Even using `catalog` instead of `servicecatalog` doesn't help

**Comment by megian** [comment]
The issue is still open, but i guess more an openshift-ansible issue. That's why I created another issue here: https://github.com/openshift/openshift-ansible/issues/6377

**Comment by cscetbon** [comment]
Okay I see. I have the same issue with `minikube` :(

**Comment by megian** [comment]
Reopen the issue, because it seams not only to be openshift-ansible related.

**Comment by bortek** [comment]
Same issue here, any progress ?

**Comment by megian** [comment]
It seams to occur, if there is no StorageClass defined, asb-etcd in the namespace openshift-ansible-service-broker is waiting for permanent storage and does fail. This causes asb to fail and adding the resource is not possible.
