### ISSUE TITLE
test_branch_origin_extended_clusterup

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#17652]
clusterup test flaked not able to access master API:

```
-- Checking container networking ... 
FAIL
   Error: containers cannot communicate with the OpenShift master
   Details:
     The cluster was started. However, the container networking test failed.
   Solution:
     Ensure that access to ports tcp/8443, udp/53 and udp/8053 is allowed on 172.18.8.133.
     You may need to open these ports on your machine's firewall.
   Caused By:
     Error: Docker run error rc=1
     Details:
       Image: openshift/origin:d1561b6
       Entrypoint: [/bin/bash]
       Command: [-c #!/bin/bash
       set -e
       echo 'Testing connectivity to master API'
       failed=0
       for i in {1..40}; do
       	if curl -s -S -k -m 1 https://${MASTER_IP}:8443; then
       	  failed=0
       	  break
       	else
       	  failed=1
       	fi
       done
       if [[ failed -eq 1 ]]; then
           exit 1
       fi
       echo 'Testing connectivity to master DNS server'
       for i in {1..40}; do
          if curl -s -S -k -m 1 https://kubernetes.default.svc.cluster.local; then
             exit 0
          fi
       done
       exit 1
       ]
       Output:
         Testing connectivity to master API
       Error Output:
         curl: (6) Could not resolve host: ; Name or service not known
```

**Comment by jim-minter** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_clusterup/50/console

**Comment by jim-minter** [comment]
@bparees @knobunc it rather looks like MASTER_IP contained the text "; Name or service not known" - any thoughts how this could happen?

**Comment by bparees** [comment]
digging through the cluster up logic it seems like it just runs the origin container with "openshift start --print-ip" and that value becomes the MASTER_IP value.  Certainly not immediately clear to me how that would go wrong.

probably worth poking @csrwng too.

**Comment by jim-minter** [comment]
@knobunc @csrwng any thoughts on the above?

**Comment by csrwng** [comment]
Hey @jim-minter I looked through the code and don’t see where we would try to resolve a dns name when `openshift start —print-ip` is invoked. The only thing I can think of to do for the future is to output any env vars that were used when invoking the `docker run` that failed.

**Comment by bparees** [comment]
doesn't seem to have recreated that i'm aware of. closing.
