### ISSUE TITLE
remove all builds when build configuration is removed oc delete buildconfig should start builds and delete the buildconfig 

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#17659]
Flaking hard today.

```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:137
Dec  7 11:40:52.022: EOF
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/cli.go:588
```

It might be not related to builds?

**Comment by bparees** [comment]
@mfojtik link to the job?  And yes, we've seen this EOF in various places and I believe @jim-minter noted that it's not build related, it's something just crashing hard.

**Comment by jim-minter** [comment]
Previous instance of this happening was https://github.com/openshift/origin/issues/16732 - I had only seen it happen once.
Depending on the logs that @mfojtik appends, perhaps the thing to do is instrument util.FatalErr and get it to print a backtrace and see if that helps?

**Comment by mfojtik** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17627/test_pull_request_origin_extended_conformance_gce/12550/

This is the fresh one, I've seen this many times today.

**Comment by jim-minter** [comment]
I think this looks very similar to #16732 - still looking, but seems highly likely the failure is occurring in the generic k8s BeforeEach.  If so, nothing to do with builds at all.

**Comment by bparees** [comment]
stack trace has been added, nothing else we can do on this until/unless it creates w/ the stack trace code in place.
