### ISSUE TITLE
FailedMount: Unable to mount volumes for pod "mysql-slave-1-622rn_extended-test-mysql-replication-0-5nw8g-lkzjc(2f1d5ac3-da43-11e7-ab75-0ee1f589dd4a)": timeout expired

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#17651]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/306/testReport/junit/(root)/Extended/_image_ecosystem__mysql__Slow__openshift_mysql_replication__MySQL_replication_template_for_5_7__https___raw_githubusercontent_com_sclorg_mysql_container_master_examples_replica_mysql_replica_json__Suite_openshift_/

**Comment by jim-minter** [comment]
@bparees looks like the test failed because mysql-slave-1-622rn failed to mount a PV in time.  @mfojtik please could one of your team take a look?

**Comment by bparees** [comment]
probably more a question for @sjenning or possibly the storage team.

**Comment by sjenning** [comment]
Node logs show that the `mysql-slave` PVC is in `Pending` state.  Seems that a PV is not available for binding.

```
desired_state_of_world_populator.go:274] Error processing volume "mysql-slave-data" for pod "mysql-slave-1-622rn_extended-test-mysql-replication-0-5nw8g-lkzjc(2f1d5ac3-da43-11e7-ab75-0ee1f589dd4a)": error processing PVC "extended-test-mysql-replication-0-5nw8g-lkzjc"/"mysql-slave": PVC extended-test-mysql-replication-0-5nw8g-lkzjc/mysql-slave has non-bound phase ("Pending") or empty pvc.Spec.VolumeName ("")
```
controller logs confirm there is no volume available
```
pv_controller.go:221] synchronizing PersistentVolumeClaim[extended-test-mysql-replication-0-5nw8g-lkzjc/mysql-slave]: phase: Pending, bound to: "", bindCompleted: false, boundByController: false
pv_controller.go:264] synchronizing unbound PersistentVolumeClaim[extended-test-mysql-replication-0-5nw8g-lkzjc/mysql-slave]: no volume found
pv_controller.go:595] updating PersistentVolumeClaim[extended-test-mysql-replication-0-5nw8g-lkzjc/mysql-slave] status: set phase Pending
```

**Comment by bparees** [comment]
@coreydaley is already chasing another of our replica tests that is having (different) PV issues.

@coreydaley this test creates its own hostpath PV and then mounts it.  I wonder if either something else is grabbing our PV, or we're not freeing it properly.  A simple workaround might be to just create some extra PVs and call it a day:

https://github.com/openshift/origin/blob/master/test/extended/image_ecosystem/mysql_replica.go#L74

(we currently create exactly the 2 we need for the test)

**Comment by bparees** [comment]
PVs were added to address this, closing in hopes we don't see it again.
