### ISSUE TITLE
I/O timeout when connecting to server that is not up

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1766]
Should probably not try to connect for as long as it does (30s?).  TCP connection establishment should be shorter in most cases.

**Comment by sosiouxme** [comment]
Agreed, but there's no central place to configure that timeout...

**Comment by smarterclayton** [comment]
Actually the default transport can do this for us.  Just not sure it's the right place.

**Comment by smarterclayton** [comment]
@juanvallejo can you close this against something you've done recently?

**Comment by juanvallejo** [comment]
@sosiouxme 
> Agreed, but there's no central place to configure that timeout...

Would `--request-timeout` work in this case?

@smarterclayton A related PR for this would  be https://github.com/openshift/origin/pull/12571, however it only ensures that `oc project <context_for_server_that_is_down>` does not hang / fail, provided that the context name is valid.

Also, I am not able to replicate an `I/O` timeout that lasts for 30s, using latest master, all of my requests fail almost immediately if the current server is down:
```
$ kill <server_pid>
$ oc login ...
error: dial tcp 10.13.137.149:8443: getsockopt: connection refused

$ oc whoami
The connection to the server 10.13.137.149:8443 was refused - did you specify the right host or port?
```

**Comment by smarterclayton** [comment]
Usually it's from a blackhole'd IP (where a firewall is dropping connection
requests to unexposed ports on old IPs).  I believe there are good examples
out there of replicating this
