### ISSUE TITLE
How to customize template metadata.annotations.tags

### ISSUE THREAD

**Issue by zonArt** [openshift/origin#17660]
Hi,

I've a very simple question: Is it possible to create some custom metadata.annotations.tags within openshift template (in order that they don't fall into the default "Uncategorized" if none is matching what you want) ? If yes how ?

Thank you in advance

**Comment by pweil-** [comment]
Hi @zonArt.  Since this is for reporting bugs/issues please submit this question to the mailing list or stack exchange.  Thanks!
