### ISSUE TITLE
oc new-app give an error unauthorized: authentication required

### ISSUE THREAD

**Issue by mibaboo** [openshift/origin#17679]
I have an image on my local Docker server "test/hello" . When I try to create a new app using this docker image it does not deploy. I get the error in oc events 

> Failed to pull image "test/hello:latest": rpc error: code = 2 desc = unauthorized: authentication required

So for testing purposes I downloaded the docker.io/openshift/hello-openshift
and ran 
`oc new app docker.io/openshift/hello-openshift`
This works as expected.
If I tag this docker image test/hello
and run new-app
`oc new app test/hello`

I start getting the error 
> Failed to pull image "test/hello:latest": rpc error: code = 2 desc = unauthorized: authentication required

##### Version
openshift version
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
etcd 3.2.1

oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.28.102.29:8443
openshift v3.6.1+008f2d5

##### Steps To Reproduce
docker pull docker.io/openshift/hello-openshift
docker tag 566fae6786e4 test/hello
oc new-app test/hello

 Found Docker image 566fae6 (18 hours old) from  for "test/hello:latest"

 This image will be deployed in deployment config "hello"
Ports 8080/tcp, 8888/tcp will be load balanced by service "hello"
 Other containers can access this service through the hostname "hello"
 WARNING: Image "test/hello:latest" runs as the 'root' user which may not be permitted by your cluster administrator

Creating resources ...
deploymentconfig "hello" created
  service "hello" created
 Success
Run 'oc status' to view your app.

##### Current Result
> Failed to pull image "test/hello:latest": rpc error: code = 2 desc = unauthorized: authentication required
##### Expected Result
new app to deploy successfully

**Comment by php-coder** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
"test/hello" only exists on your local machine, it doesn't exist in a registry, thus openshift cannot pull it and run it.

You need to push your image to a registry (such as dockerhub) and reference it at that location.

if you can't "docker pull foo/bar" then you can't run it on openshift either.  Tagging it locally isn't sufficient.
