### ISSUE TITLE
Deploymentconfig trigger: {} value not allowed

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin#17673]
When trying to disable the config change trigger by providing an empty trigger spec, a value that I used on a 3.6.1 server no long works on a 3.9.0-alpha server.

##### Version
oc v3.9.0-alpha.0+f9f2130-61
kubernetes v1.8.1+0d5291c
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ip-172-18-3-182.ec2.internal:8443
openshift v3.9.0-alpha.0+f9f2130-61
kubernetes v1.8.1+0d5291c

##### Steps To Reproduce
1. Create a template with a DC using api version "v1" and add `trigger: {}` to the spec
2. oc create -f the template file

##### Current Result

Receive error
```
Error from server (BadRequest): error when creating "/tmp/openshift-logging-ansible-FI6P7i/templates/logging-es-dc.yml": DeploymentConfig in version \"v1\" cannot be handled as a DeploymentConfig: json: cannot unmarshal object into Go struct field DeploymentConfigSpec.triggers of type v1.DeploymentTriggerPolicies
```

##### Expected Result

DC object to be created successfully.

##### Additional Information

Using `trigger: {}` worked on 3.6.1 server.
Updating the DC api version to be `apps.openshift.io/v1` resulted in the same error.
If I update my spec to have `trigger: []` instead and still using api version "v1" it is created successfully (for v3.9.0-alpha)

cc @mfojtik @soltysh

**Comment by soltysh** [comment]
@mfojtik started looking into it, so I'll assign it to him.
