### ISSUE TITLE
Reconcile with RBAC file step fails with error unknown shorthand flag: 'f' in -f"

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#17692]
```
TASK [template_service_broker : Reconcile with RBAC file] **********************
task path: /usr/share/ansible/openshift-ansible/roles/template_service_broker/tasks/install.yml:51
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": "oc process -f \"/tmp/tsb-ansible-JOHLFz/rbac-template.yaml\" | oc auth reconcile -f -", 
    "delta": "0:00:00.282855", 
    "end": "2017-12-08 16:23:19.100164", 
    "failed": true, 
    "generated_timestamp": "2017-12-08 16:23:19.117477", 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2017-12-08 16:23:18.817309", 
    "stderr": [
        "Error: unknown shorthand flag: 'f' in -f", 
        "", 
        "", 
        "Usage:", 
        "  oc auth [options]", 
        "", 
        "Available Commands:", 
        "  can-i       Check whether an action is allowed", 
        "", 
        "Use \"oc <command> --help\" for more information about a given command.", 
        "Use \"oc options\" for a list of global command-line options (applies to all commands)."
    ], 
    "stdout": []
}
```

Seen there: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17687/test_pull_request_origin_extended_conformance_install/3790/

**Comment by php-coder** [comment]
CC @stevekuznetsov

**Comment by enj** [comment]
Uh from the error output it also looks like the entire `reconcile` command is missing from under `oc auth`?

cc @simo5 @deads2k @juanvallejo

**Comment by enj** [comment]
Also do pipes / stdout / stderr work correctly when a command is run like this?

**Comment by simo5** [comment]
Uhmm why are there escaped quotes around the file name ? is that right ?

**Comment by juanvallejo** [comment]
@enj 
> Uh from the error output it also looks like the entire reconcile command is missing from under oc auth?

Yeah, will try to look into this

> Also do pipes / stdout / stderr work correctly when a command is run like this?

Usually the [resource builder "FilenameParam"](https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/auth/reconcile.go#L98) takes care of reading from stdin if `-` is passed

@simo5 
> Uhmm why are there escaped quotes around the file name ? is that right ?

Yeah, I believe this should not impact the filepath parsed by `process`

**Comment by juanvallejo** [comment]
If I'm reading the linked logs correctly, it looks like the tests are using oc ~v3.6?
If so, only `can-i` was available under `oc auth` back then https://github.com/openshift/origin/blob/release-3.6/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/auth/auth.go

**Comment by simo5** [comment]
then that's the bug, oc v3.7 is needed here

**Comment by stevekuznetsov** [comment]
That was a PR against `release-3.6`. Newer OC is not appropriate. Looks like the wrong version of the installer was used
