### ISSUE TITLE
[Feature:Builds][Conformance] s2i build with a quota Building from a template should create an s2i build with a quota and run it [Suite:openshift/conformance/parallel]

### ISSUE THREAD

**Issue by enj** [openshift/origin#17695]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17617/test_pull_request_origin_extended_conformance_install/3767/

```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/s2i_quota.go:71
Expected
    <string>: 2017-12-08T06:48:24.801389147Z Receiving source from STDIN as archive ...
    failed to open log file "/var/log/pods/c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a/sti-build_0.log": open /var/log/pods/c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a/sti-build_0.log: no such file or directory
to contain substring
    <string>: MEMORY=209715200
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/s2i_quota.go:61
```

**Comment by bparees** [comment]
Issue w/ getting the pod logs, so sending to pod team.

**Comment by bparees** [comment]
note that despite what this claims:
```
Dec  8 06:49:12.803: INFO: Running 'oc logs --config=/tmp/extended-test-s2i-build-quota-gsfc7-28ksz-user.kubeconfig --namespace=extended-test-s2i-build-quota-gsfc7-28ksz pod/s2i-build-quota-1-build'
Dec  8 06:49:13.151: INFO: Log for pod "s2i-build-quota-1-build"
---->
failed to open log file "/var/log/pods/c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a/sti-build_0.log": open /var/log/pods/c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a/sti-build_0.log: no such file or directory
<----end of log for "s2i-build-quota-1-build"
```

the pod does exist and has run:
```
Dec  8 06:49:12.803: INFO: Describing pod "s2i-build-quota-1-build"
Name:           s2i-build-quota-1-build
Namespace:      extended-test-s2i-build-quota-gsfc7-28ksz
Node:           ip-172-18-15-47.ec2.internal/172.18.15.47
Start Time:     Fri, 08 Dec 2017 06:48:13 +0000
Labels:         openshift.io/build.name=s2i-build-quota-1
Annotations:    openshift.io/build.name=s2i-build-quota-1
                openshift.io/scc=privileged
Status:         Succeeded
Containers:
  sti-build:
    Container ID:  docker://e8c2fc66cdc000498dc0ddf61f872e4dbad2b66bebb1340ee9914ea7aa95de1d
    Image:         openshift/origin-sti-builder:112d0be
    Image ID:      docker://sha256:90d4539e3310a041a529ade6f0d54b4abb466f0e40518ae19a35c4c1f1bb9e7c
    Port:          <none>
    Command:
      openshift-sti-build
    Args:
      --loglevel=0
    State:          Terminated
      Reason:       Completed
```

(I think there may already be an issue for this.  Likely related to GC cleaning up the containers too quickly/aggressively or something)

**Comment by sjenning** [comment]
@aveshagarwal PTAL

**Comment by aveshagarwal** [comment]
was trying to find if there is any recent failure and I did find: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18235/test_pull_request_origin_extended_conformance_install/6251/

**Comment by aveshagarwal** [comment]
The issue: 
```
failed to open log file "/var/log/pods/c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a/sti-build_0.log": open /var/log/pods/c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a/sti-build_0.log: no such file or directory
```
might be related to some similar issues related to symlink in kube upstream: https://github.com/kubernetes/kubernetes/issues/45911
https://github.com/kubernetes/kubernetes/issues/52172

Still investigating though.

**Comment by aveshagarwal** [comment]
Openshift default logging driver is journald, why are we running these tests with json-file (which is default for docker) driver? is there any specific reason for that? @stevekuznetsov  do you have idea about it?

**Comment by aveshagarwal** [comment]
> Openshift default logging driver is journald, why are we running these tests with json-file (which is default for docker) driver? is there any specific reason for that? @stevekuznetsov do you have idea about it?

Discard this comment, as I verified that the default now is `json-file`.

**Comment by aveshagarwal** [comment]
So my current investigation says that when the pod's logs were being obtained, the pod's container existed, but symlink to the log file was missing. Because the error was:

```
failed to open log file "/var/log/pods/c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a/sti-build_0.log": open /var/log/pods/c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a/sti-build_0.log: no such file or directory
```

Because if the container was not present, the error would be different and look something following (`No such container`) (the following error is from my local cluster just to show the difference in the error):

```
failed to get container status {"docker" "14098fa33001a04c995fa1e25aa342064d20989f98dd7e6c683ecffe08159352"}: rpc error: code = Unknown desc = Error: No such container: 14098fa33001a04c995fa1e25aa342064d20989f98dd7e6c683ecffe08159352
```

**Comment by aveshagarwal** [comment]
> (I think there may already be an issue for this. Likely related to GC cleaning up the containers too quickly/aggressively or something)

So it does not seem like GC cleaning containers too early, see my previous comment: https://github.com/openshift/origin/issues/17695#issuecomment-360552207

**Comment by stevekuznetsov** [comment]
So we should be reasonably certain that the doubling of storage will keep GC at bay and this should be fixed (ish) for now?

**Comment by bparees** [comment]
@stevekuznetsov i don't think so.  @aveshagarwal's last update says it does NOT seem like GC cleaning was the issue.

**Comment by stevekuznetsov** [comment]
Reading comprehension in my drive-by review here was at an all time low ... :(

**Comment by aveshagarwal** [comment]
@stevekuznetsov yes GC does not seem an issue as I checked in the node logs that the container was present even after the error occurred. Seems like either the symbolic log file got deleted or not even created though I suspect the former more for now.

**Comment by aveshagarwal** [comment]
So these symlink log files are being created here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L150  when a container is being started and I do not think after looking at the code that there is any issue that the log file wont be created. In case, someone disagrees let me know why.

So still investigating what might have deleted the log file.

**Comment by aveshagarwal** [comment]
I think I see the reason why the log file symlink was not created, and the reason is that I see "Started Container" event for init containers (git-clone and manage-dockerfile) but NOT for the main container (sti-build) in the node logs:

Dec 08 06:48:18 ip-172-18-15-47.ec2.internal origin-node[20160]: I1208 06:48:18.260152   20160 server.go:228] Event(v1.ObjectReference{Kind:"Pod", Namespace:"extended-test-s2i-build-quota-gsfc7-28ksz", Name:"s2i-build-quota-1-build", UID:"c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a", APIVersion:"v1", ResourceVersion:"4537", FieldPath:"spec.initContainers{git-clone}"}): type: 'Normal' reason: 'Started' Started container

Dec 08 06:48:30 ip-172-18-15-47.ec2.internal origin-node[20160]: I1208 06:48:30.086723   20160 server.go:228] Event(v1.ObjectReference{Kind:"Pod", Namespace:"extended-test-s2i-build-quota-gsfc7-28ksz", Name:"s2i-build-quota-1-build", UID:"c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a", APIVersion:"v1", ResourceVersion:"4537", FieldPath:"spec.initContainers{manage-dockerfile}"}): type: 'Normal' reason: 'Started' Started container 


but not sure why this happened.

**Comment by aveshagarwal** [comment]
And there are "Created container" event for all 3 containers: 2 init and 1 main:

Dec 08 06:48:17 ip-172-18-15-47.ec2.internal origin-node[20160]: I1208 06:48:17.396425   20160 server.go:228] Event(v1.ObjectReference{Kind:"Pod", Namespace:"extended-test-s2i-build-quota-gsfc7-28ksz", Name:"s2i-build-quota-1-build", UID:"c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a", APIVersion:"v1", ResourceVersion:"4537", FieldPath:"spec.initContainers{git-clone}"}): type: 'Normal' reason: 'Created' Created container

Dec 08 06:48:29 ip-172-18-15-47.ec2.internal origin-node[20160]: I1208 06:48:29.244127   20160 server.go:228] Event(v1.ObjectReference{Kind:"Pod", Namespace:"extended-test-s2i-build-quota-gsfc7-28ksz", Name:"s2i-build-quota-1-build", UID:"c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a", APIVersion:"v1", ResourceVersion:"4537", FieldPath:"spec.initContainers{manage-dockerfile}"}): type: 'Normal' reason: 'Created' Created container

Dec 08 06:48:39 ip-172-18-15-47.ec2.internal origin-node[20160]: I1208 06:48:39.852370   20160 server.go:228] Event(v1.ObjectReference{Kind:"Pod", Namespace:"extended-test-s2i-build-quota-gsfc7-28ksz", Name:"s2i-build-quota-1-build", UID:"c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a", APIVersion:"v1", ResourceVersion:"4537", FieldPath:"spec.containers{sti-build}"}): type: 'Normal' reason: 'Created' Created container

**Comment by aveshagarwal** [comment]
After the main container created, the node rebooted:

```
Dec 08 06:48:40 ip-172-18-15-47.ec2.internal systemd[1]: origin-node.service: main process exited, code=exited, status=255/n/a
Dec 08 06:48:40 ip-172-18-15-47.ec2.internal systemd[1]: Unit origin-node.service entered failed state.
Dec 08 06:48:40 ip-172-18-15-47.ec2.internal systemd[1]: origin-node.service failed.
Dec 08 06:48:46 ip-172-18-15-47.ec2.internal systemd[1]: origin-node.service holdoff time over, scheduling restart.
Dec 08 06:48:46 ip-172-18-15-47.ec2.internal systemd[1]: Starting OpenShift Node...
```

**Comment by aveshagarwal** [comment]
And the cause of node restart is:

Dec 08 06:48:40 ip-172-18-15-47.ec2.internal origin-node[20160]: F1208 06:48:40.732534   20160 healthcheck.go:96] SDN healthcheck detected unhealthy OVS server, restarting: <nil>

**Comment by stevekuznetsov** [comment]
@knobunc for triaging SDN issues

**Comment by sjenning** [comment]
yikes, origin-node self terminating in the middle of a test run?! nasty

**Comment by aveshagarwal** [comment]
I have created upstream issue for this: https://github.com/kubernetes/kubernetes/issues/59206#issuecomment-362322284

I also have a preliminary fix, not sent to upstream yet as still discussing ways to address this more appropriately:  https://github.com/aveshagarwal/kubernetes/pull/9  (note this PR is not sent to upstream yet).

**Comment by sosiouxme** [comment]
@aveshagarwal any opinion on whether the second form of test failure is the same flake? [Just observed the same today](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18641/test_pull_request_origin_extended_conformance_install/8624/):

```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/s2i_quota.go:45
Expected
    <bool>: false
to be true
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/s2i_quota.go:54
```

**Comment by aveshagarwal** [comment]
@sosiouxme this one is very different from the original failure.
