### ISSUE TITLE
A lot of actions are (wrongly) forbidden since upgrading `oc` from `3.6` to `3.7`

### ISSUE THREAD

**Issue by vindvaki** [openshift/origin#17691]
A lot of actions have become forbidden since upgrading from `3.6` to `3.7`. 

##### Version
```
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth
```

##### Steps To Reproduce
(after logging in successfully):
```bash
oc rollout latest $POD
```

##### Current Result
```
Error from server (Forbidden): User "$USER" cannot update apps.openshift.io.deploymentconfigs in project "$PROJECT"
```

where the actual values of `$PROJECT` and `$USER` can vary

##### Expected Result

It should trigger a rollout as it used to with version `3.6`

##### Additional Information

The diagnostics were pretty useless -- everything was just forbidden.

**Comment by enj** [comment]
@vindvaki could you provide details on how you upgraded?  For example, did you use ansible?  Did the 3.7 server reconcile RBAC on start? (you will see this on start up).

cc @simo5

**Comment by vindvaki** [comment]
Thanks for the quick response @enj !
> Did the 3.7 server reconcile RBAC on start?

I think I should clarify my situation: This is only after an upgrade of the Client (`oc`). I installed `openshift-cli` via homebrew; I am on macOS Sierra (not High Sierra), and this is broken after a `brew upgrade openshift-cli.

Does your question still apply? If it does, could you please clarify what you meant by "server" and how I can find out if it "reconciled RBAC on start"?

In the meantime am going to try these two things and report back:

(1) I'll verify that downgrading to 3.6.1 from your releases page actually works (I believe it will)

(2) I'll check if the official latest release differs from the one supplied by homebrew, and try the official release in case the homebrew one is different

**Comment by vindvaki** [comment]
Ok, just verified that downgrading to 3.6.1, everything works again.

**Comment by enj** [comment]
@vindvaki you have probably not reconciled cluster roles after upgrading.  In 3.6-, this must be manually done.  So with your 3.6 client, run:

`oc adm policy reconcile-cluster-roles --additive-only=true`

This will do a dry run and show you all the cluster roles it plans to update.  Run it with `--confirm` to commit the changes.  After this your 3.7 client should work fine.

Note that a lot of changes happened in between those releases, and the 3.7 client is defaulting to the newer APIs which result in a slightly different permission check.
