### ISSUE TITLE
k8s.io/kubernetes/pkg/kubelet/deviceplugin TestDevicePluginReRegistration

### ISSUE THREAD

**Issue by enj** [openshift/origin#17698]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17617/test_pull_request_origin_unit/6710/

```
<autogenerated>:12: 
                          
	Error Trace:	manager_test.go:74
Error:      	Not equal: 
expected: 2
actual: 0
Messages:   	Devices are not updated.
```

**Comment by enj** [comment]
@eparis @pweil- bumping this to P1 since I have seen it flake unit tests a lot.

**Comment by sjenning** [comment]
@vikaschoudhary16 PTAL.  coming from the device plugin tests.

**Comment by vikaschoudhary16** [comment]
There are known race conditions in the way this test is currently written. Here is the PR upstream to fix its behavior:
https://github.com/kubernetes/kubernetes/pull/52616

**Comment by enj** [comment]
Can we disable this until it get fixed upstream?

**Comment by vikaschoudhary16** [comment]
I think we can close this now since vendored kube has this fix PR:
https://github.com/kubernetes/kubernetes/pull/53028
