### ISSUE TITLE
`oc cluster up --host-volumes-dir` Not Working

### ISSUE THREAD

**Issue by eliu** [openshift/origin#17703]
The option `--host-volumes-dir=/path/to/custom/volumes/dir` does not work when using `oc cluster up` to launch a all-in-one openshift origin cluster.

##### Version
[provide output of the `openshift version` or `oc version` command]

```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. launch origin using `oc cluster up --host-volumes-dir=/path/to/dir`

##### Current Result
The origin still uses `/var/lib/origin/openshift.local.volumes` as default volume path

##### Expected Result
The origin can use custom path by specifying `--host-volumes-dir` option

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by wewang58** [comment]
I used oc v3.6.0+c4dd4cf, the origin uses dir which I pathed.

**Comment by eliu** [comment]
@wewang58 Strange it is. Have you already checked the logs of the origin container?

**Comment by wewang58** [comment]
@eliu I didn't see info about volume path, but can see dir's size are larger ,and default volume dir size is no change, how do you check using default volume path?

**Comment by wewang58** [comment]
just info : Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes

**Comment by eliu** [comment]
@wewang58 i'll trying to reproduce it and get the log details. will get u updated later..

**Comment by eliu** [comment]
what is your output of `oc cluster status`? @wewang58 

Here is mine:

```
# oc cluster status
Web console URL: https://openshift.hand-china.com:8443

Config is at host directory /u01/openshift/local/config
Volumes are at host directory
Persistent volumes are at host directory /u01/openshift/local/pv
Data is at host directory /u01/openshift/local/data
```

**Comment by eliu** [comment]
Hey, you're right. the size of that volume directory is actually growing. I was fooled by `oc cluster status`, where list volume info as `Volumes are at host directory`

**Comment by eliu** [comment]
I can close this issue since it's been clarified. thanks everyone.

**Comment by wewang58** [comment]
@eliu , thank you too
