### ISSUE TITLE
Attach a storage class to a specific project

### ISSUE THREAD

**Issue by jocelynthode** [openshift/origin#17715]
Hi,

I'm currently using Openshift v3.6.0. I would like to use storage classes to quickly provision new PV, however I would like my Storage Classes to be linked to a project. This way users from project Y could not see that a storage class for project X exists (and thus would not know that project X exists).

Is there a way to achieve this currently ?

**Comment by pweil-** [comment]
Hi @jocelynthode storage classes are a cluster-scoped object and are do not exist in the project scope.  There is no way to tie them specifically to a project.
