### ISSUE TITLE
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#17714]
Looks like maybe an issue writing to the persistent volume.

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/314/testReport/junit/(root)/Extended/_image_ecosystem__postgresql__Slow__local__openshift_postgresql_replication__postgresql_replication_works_for_postgresql_9_2__Suite_openshift_/

##### Version
oc v3.6.0-rc.0+d1561b6-2902
kubernetes v1.8.1+0d5291c
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.50.14:8443
openshift v3.6.0-rc.0+d1561b6-2902
kubernetes v1.8.1+0d5291c

##### Steps To Reproduce
1. oc new-app -f https://raw.githubusercontent.com/sclorg/postgresql-container/master/examples/replica/postgresql_replica.json -p IMAGESTREAMTAG=postgresql:9.2
2. [step 2]

##### Current Result
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose svc/postgresql-master' 
     'oc expose svc/postgresql-slave'
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by bparees** [comment]
Seems likely to be an issue with whatever/however PVs are configured in the test cluster, or getting the permissions set correctly when the volume is mounted to the pod.

**Comment by bparees** [comment]
The PV is actually created by the test itself:
https://github.com/openshift/origin/blob/master/test/extended/util/framework.go#L1079-L1122

and we did have to change the chcon rules at some point to ensure it was writable, but assuming this is only failing intermittently, that should not be the issue here.

**Comment by bparees** [comment]
@coreydaley I don't see the error you quoted (`cannot create directory`) in the logs you linked.

**Comment by coreydaley** [comment]
@bparees the cannot create directory came from my machine, i was able to duplicate the error locally.

**Comment by wewang58** [comment]
I tried, pvc is always pending, cannot mount any pv, pv is automaticlly created in origin now?
