### ISSUE TITLE
oc cluster up: did not find version in command output

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#17716]
Unable to reproduce locally, will continue to monitor tests to see if it was just a one time flake

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_clusterup/55/consoleFull#-4939476675898c58db7602c31c0eab717

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. oc cluster up --loglevel=2

##### Current Result
   Creating initial OpenShift configuration
FAIL
   Error: could not update OpenShift configuration
   Caused By:
     Error: did not find version in command output
##### Expected Result
It should work

**Comment by bparees** [comment]
Seems like we need to run at a higher log level or add more logging to cluster up in order to understand what is actually happening when this goes wrong.  Can you look into that?

**Comment by wewang58** [comment]
@coreydaley I cannot reproduce your issue, here is my result:
# oc cluster up --loglevel=2
-- Checking OpenShift client ... 
-- Checking Docker client ... 
-- Checking Docker version ... 
-- Checking for existing OpenShift container ... 
-- Checking for openshift/origin:v3.7.0-rc.0 image ... 

   Pulling image openshift/origin:v3.7.0-rc.0
   Pulled 2/4 layers, 51% complete
   Pulled 3/4 layers, 93% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... 
-- Checking for available ports ... 
I1212 00:57:20.753312   18113 helper.go:960] Used ports in container: map[int]struct {}{22:struct {}{}, 25:struct {}{}}
-- Checking type of volume mount ... 

   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... 
-- Finding server IP ... 
I1212 00:57:26.577717   18113 up.go:1368] Cannot use the Docker host IP(): <nil>

   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ... 

   Creating initial OpenShift configuration
I1212 00:57:35.301837   18113 helper.go:585] Copying OpenShift config to local directory /tmp/openshift-config070325311
Done extracting tar stream
I1212 00:57:36.704011   18113 helper.go:609] Reading master config from /tmp/openshift-config070325311/master/master-config.yaml
I1212 00:57:39.186872   18113 crypto.go:367] Generating new CA for  cert, and key in /tmp/openshift-config070325311/front-proxy-ca.crt, /tmp/openshift-config070325311/front-proxy-ca.key
I1212 00:57:47.719499   18113 helper.go:598] Reading node config from /tmp/openshift-config070325311/node-localhost/node-config.yaml
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... 
-- Installing registry ... 

   scc "privileged" added to: ["system:serviceaccount:default:registry"]
-- Installing router ... 
-- Importing image streams ... 
I1212 00:58:18.369746   18113 up.go:1270] Importing centos7 from examples/image-streams/image-streams-centos7.json
-- Importing templates ... 
I1212 00:58:18.942354   18113 up.go:1270] Importing mysql from examples/db-templates/mysql-persistent-template.json
I1212 00:58:18.958564   18113 up.go:1270] Importing dancer quickstart from examples/quickstarts/dancer-mysql-persistent.json
I1212 00:58:19.000155   18113 up.go:1270] Importing sample pipeline from examples/jenkins/pipeline/samplepipeline.yaml
I1212 00:58:19.025941   18113 up.go:1270] Importing cakephp quickstart from examples/quickstarts/cakephp-mysql-persistent.json
I1212 00:58:19.067493   18113 up.go:1270] Importing django quickstart from examples/quickstarts/django-postgresql-persistent.json
I1212 00:58:19.092223   18113 up.go:1270] Importing nodejs quickstart from examples/quickstarts/nodejs-mongodb-persistent.json
I1212 00:58:19.176494   18113 up.go:1270] Importing rails quickstart from examples/quickstarts/rails-postgresql-persistent.json
I1212 00:58:19.202927   18113 up.go:1270] Importing jenkins pipeline ephemeral from examples/jenkins/jenkins-ephemeral-template.json
I1212 00:58:19.217648   18113 up.go:1270] Importing mongodb from examples/db-templates/mongodb-persistent-template.json
I1212 00:58:19.244984   18113 up.go:1270] Importing mariadb from examples/db-templates/mariadb-persistent-template.json
I1212 00:58:19.345541   18113 up.go:1270] Importing postgresql from examples/db-templates/postgresql-persistent-template.json
I1212 00:58:19.360196   18113 up.go:1270] Importing jenkins pipeline persistent from examples/jenkins/jenkins-persistent-template.json
I1212 00:58:19.385737   18113 up.go:1270] Importing prometheus from examples/prometheus/prometheus.yaml
I1212 00:58:19.505174   18113 up.go:1270] Importing heapster standalone from examples/heapster/heapster-standalone.yaml
-- Login to server ... 

   Login successful.

   You don't have any projects. You can try to create a new project, by running

        new-project <projectname>

-- Creating initial project "myproject" ... 
-- Removing temporary directory ... 
-- Checking container networking ... 
-- Server Information ... 

   OpenShift server started.

   The server is accessible via web console at:
       https://127.0.0.1:8443

   You are logged in as:
       User:     developer
       Password: <any value>

   To login as administrator:
       oc login -u system:admin

**Comment by coreydaley** [comment]
I will continue to monitor and see if it happens regularly

**Comment by jtudelag** [comment]
@coreydaley It happens to me from time to time with oc origin client, version 3.7.

$ oc cluster up
Starting OpenShift using openshift/origin:v3.7.0 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... 
   Deleted existing OpenShift container
-- Checking for openshift/origin:v3.7.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... 
   WARNING: Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients.
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
FAIL
   Error: could not update OpenShift configuration
   Caused By:
     Error: did not find version in command output


$ oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO
