### ISSUE TITLE
Support Merge Request Events in Build Config Webhooks

### ISSUE THREAD

**Issue by sherl0cks** [openshift/origin#17727]
This is a feature request.

##### Version
All versions supporting webhooks

##### Steps To Reproduce
1. See latest docs https://docs.openshift.org/latest/dev_guide/builds/triggering_builds.html#webhook-triggers and https://docs.openshift.com/container-platform/3.7/dev_guide/builds/triggering_builds.html#webhook-triggers

##### Current Result
from the docs:

 > OpenShift Container Platform webhooks currently only support their analogous versions of the push event for each of the Git based source code management systems (SCMs). All other event types are ignored. When the push events are processed, a confirmation is made as to whether the branch reference inside the event matches the branch reference in the corresponding BuildConfig. If they match, then the exact commit reference noted in the webhook event is checked out for the OpenShift Container Platform build. If they do not match, no build is triggered.

##### Feature Request
Support the ability to receive merge request events in webhooks, in order to support JenkinsPipeline strategy build configs that due builds for these merge requests. It's likely that the branch filtering operation will need to be disabled by default when using merge request events.

**Comment by bparees** [comment]
If you're running a jenkins pipeline you should use the various jenkins plugins for triggering your job from the jenkins side(based on SCM changes), rather than openshift webhooks.

**Comment by sherl0cks** [comment]
@bparees I'll take a look again if that is doable. possible new features are out there in the ecosystem. my experience with that approach is that it requires configuration outside of the Jenkinsfile on per a job basis in order to get branching / merging / triggers configured correctly ([example](https://jenkins.io/blog/2015/12/03/pipeline-as-code-with-multibranch-workflows-in-jenkins/)). If this is true, it basically eliminates the option to rely on jenkins-sync-plugin to create jobs based on BC's with pipeline strategy (which is very useful and widely used by consulting). 

If you have examples handy, please do share.
