### ISSUE TITLE
e2e core.sh: executing 'oc logs dc/failing-dc' expecting success

### ISSUE THREAD

**Issue by sjenning** [openshift/origin#17721]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17479/test_pull_request_origin_end_to_end/6613/

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17553/test_pull_request_origin_end_to_end/6603/

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17479/test_pull_request_origin_end_to_end/6606/

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17719/test_pull_request_origin_end_to_end/6610/

```
=== BEGIN TEST CASE ===
test/end-to-end/core.sh:422: executing 'oc logs dc/failing-dc-mid' expecting success and text 'test mid hook executed'
FAILURE after 0.248s: test/end-to-end/core.sh:422: executing 'oc logs dc/failing-dc-mid' expecting success and text 'test mid hook executed': the output content test failed
Standard output from the command:
error: update acceptor rejected failing-dc-mid-1: pods for rc 'test/failing-dc-mid-1' took longer than 20 seconds to become available

There was no error output from the command.
=== END TEST CASE ===
```

```
=== BEGIN TEST CASE ===
test/end-to-end/core.sh:408: executing 'oc logs dc/failing-dc' expecting success and text 'test pre hook executed'
FAILURE after 0.278s: test/end-to-end/core.sh:408: executing 'oc logs dc/failing-dc' expecting success and text 'test pre hook executed': the output content test failed
There was no output from the command.
There was no error output from the command.
=== END TEST CASE ===
```

**Comment by stevekuznetsov** [comment]
Also:

```
=== BEGIN TEST CASE ===
test/end-to-end/core.sh:408: executing 'oc logs dc/failing-dc' expecting success and text 'test pre hook executed'
FAILURE after 0.312s: test/end-to-end/core.sh:408: executing 'oc logs dc/failing-dc' expecting success and text 'test pre hook executed': the output content test failed
Standard output from the command:
--> pre: Running hook pod ...

There was no error output from the command.
=== END TEST CASE ===
```


/assign @bparees 
/kind bug

@soltysh this can't have anything to do with the `journald` changes lately, could it? Looks like a lot of `oc logs` bugs.

**Comment by tnozicka** [comment]
@stevekuznetsov your failure is caused by https://github.com/openshift/origin/issues/17747

the original one is pod not starting in 5s; the timeout is being raised in https://github.com/openshift/origin/pull/17728 but that hangs on flakes

**Comment by tnozicka** [comment]
actually I think all are https://github.com/openshift/origin/issues/17747
here is the pull to disable the frequently failing test https://github.com/openshift/origin/pull/17746
