### ISSUE TITLE
The HAProxy router should expose prometheus metrics for a route" flakes with error "timed out waiting for the condition"

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#17731]
Seen there: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17702/test_pull_request_origin_extended_conformance_install/3946/

**Comment by mfojtik** [comment]
According to http://snowstorm-dev.app.mfojtik.io this flaked 15 times in last 5 days.

**Comment by mfojtik** [comment]
@knobunc FYI

**Comment by mfojtik** [comment]
Raising severity as this is now flaking for every second PR. @smarterclayton @knobunc will you be fine to disable this test until the problem is resolved?

**Comment by mfojtik** [comment]
(also this is not just 3.8 but master as well)

**Comment by smarterclayton** [comment]
No, this is just exposing a very serious bug in openshift-sdn, and there are several tests that flake.  #18317.

**Comment by adambkaplan** [comment]
Potentially similar issue with:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19532/test_pull_request_origin_extended_conformance_gce/19841/
