### ISSUE TITLE
UI should redirect to login page when websocket reconnections fail with 401 errors

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#1773]
When the web console's websockets timeout and attempt to reconnect, if the auth token is no longer valid the websocket connection will fail.  Our websocket retry logic kicks in and eventually displays the message that the connection to the server was interrupted and to refresh, refreshing will then trigger the login flow.

It would be better if we can detect on the websocket reconnect that the failure was due to authentication and kick off the login flow then.

**Comment by liggitt** [comment]
We currently do sensical things (show an error about the connection being interrupted with a "Refresh" button... when you refresh, you get prompted to log in again), so lowering the priority

**Comment by liggitt** [comment]
#2302 actually fixed the timeout issue. This now only surfaces if the token is invalidated server-side, while viewing a page using watches. On navigate (or refresh, which you are prompted to do), you are directed to log in.

**Comment by liggitt** [comment]
@jwforres I could see closing this... not sure how I feel about background failures kicking you to a login page
