### ISSUE TITLE
Failed to get cgroup stats for "/user.slice/..": unknown container "/user.slice/..."

### ISSUE THREAD

**Issue by vmaksimov** [openshift/origin#17730]
##### Version
openshift version 
openshift v3.9.0-alpha.0+4d15c88-84
kubernetes v1.8.1+0d5291c
etcd 3.2.8

##### Steps To Reproduce
1. docker pull openshift/origin
2. sudo dokerd  --exec-opt native.cgroupdriver=systemd
3. sudo docker run -d --name "origin" \
        --privileged --pid=host --net=host \
        -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
        -v /var/lib/docker:/var/lib/docker:rw \
        -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave \ 
        openshift/origin start

##### Current Result
docker logs -f origin

proxier.go:1621] Failed to delete stale service IP 172.30.0.1 connections, error: error deleting connection tracking state for UDP service IP: 172.30.0.1, error: error looking for path of conntrack: exec: "conntrack": executable file not found in $PATH
summary.go:92] Failed to get system container stats for "/user.slice/user-1000.slice/session-c2.scope": failed to get cgroup stats for "/user.slice/user-1000.slice/session-c2.scope": failed to get container info for "/user.slice/user-1000.slice/session-c2.scope": unknown container "/user.slice/user-1000.slice/session-c2.scope"

"Browse Catalog" in https://myip:8443/console/ is not displayed:
![screenshot from 2017-12-12 18-00-35](https://user-images.githubusercontent.com/5646768/33891571-5ae6bec0-df67-11e7-9061-2b27183ff76d.png)

Why does this error occur and how fix?

**Comment by sjenning** [comment]
There is no bug here.  Only problem is that the templates are not added to Openshift when you start it this way.  Please use `oc cluster up`.
