### ISSUE TITLE
container logs lose line(s) (the last one)

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#17747]
At least the last line of logs get lost sometimes causing flakes in various tests. Test use `oc logs` command.

I've found some old hack with [sleep 1](https://github.com/tnozicka/origin/commit/28e79e24dc67f08896ce0dec9ac1b8add3202156#diff-10eb0b1a257069656bc468c050aa1d0bR29) at the end of the container command which appear to mitigate the issue mostly, but flake sometimes as well.

Here are some flakes caused by this:
- https://github.com/openshift/origin/issues/17631#issuecomment-350769675
- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17606/test_pull_request_origin_extended_conformance_gce/12465/
- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17576/test_pull_request_origin_end_to_end/6690/
- more ...

cc: @mfojtik @soltysh @deads2k

**Comment by tnozicka** [comment]
this is likely related:
https://github.com/openshift/origin/pull/12143#discussion_r94793391
https://github.com/moby/moby/pull/29863

**Comment by soltysh** [comment]
So I was talking about https://github.com/openshift/origin/issues/9285, but it looks like the bits mentioned in https://github.com/projectatomic/docker/pull/218 should be in already.

**Comment by tnozicka** [comment]
@soltysh I don't think we have https://github.com/projectatomic/docker/pull/218 that pr was closed

**Comment by soltysh** [comment]
We'd need to check the current docker or get @runcom look into it

**Comment by runcom** [comment]
> We'd need to check the current docker or get @runcom look into it

I guess we can re-open https://github.com/projectatomic/docker/pull/218 for the latest docker(s) we support and have @nalind ack on it to get it in

**Comment by tnozicka** [comment]
https://github.com/projectatomic/docker/pull/291

**Comment by stevekuznetsov** [comment]
In our test AMIs we are using 

```
$ rpm -q docker
docker-1.12.6-68.gitec8512b.el7.x86_64
```

**Comment by tnozicka** [comment]
that version of docker already has that particular fix (https://github.com/projectatomic/docker/blob/ec8512ba42f349cbe5a63140c4d9c810f7afa527/daemon/logger/journald/read.go#L262-L269)

It must be something else then

**Comment by tnozicka** [comment]
- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17479/test_pull_request_origin_end_to_end/6606/
- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17479/test_pull_request_origin_end_to_end/6613/
- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17553/test_pull_request_origin_end_to_end/6603/

**Comment by stevekuznetsov** [comment]
We need to revert the `journald` limit disable PR.

**Comment by soltysh** [comment]
We've discussed this with Steve yesterday, I'll open a PR which will enable the journald for all our tests, for now the revert in #17758 should stabilize the queue, slightly.

**Comment by tnozicka** [comment]
Is this really just jurnald rate limit? I find it suspicious that rate limiting would strip only the last line in the same specific test.

**Comment by stevekuznetsov** [comment]
I think it ends up being how reproducible our tests are -- always run the same N tests in the same order and generate the same log lines, so if we trigger a rate-limit it will be fairly often in the same place.

**Comment by tnozicka** [comment]
Last time it was on the last line of different test and we had to add `sleep 1` there. Seems like too much of a coincidence.

**Comment by stevekuznetsov** [comment]
There was also some weirdness with the way that the logs were gathered in `docker` that Andy was working around by asking for them twice, but I don't think that ever made it in.

**Comment by tnozicka** [comment]
@stevekuznetsov it is in the docker version you've pasted https://github.com/openshift/origin/issues/17747#issuecomment-351479695

**Comment by stevekuznetsov** [comment]
No, @soltysh knows more about that patch from Andy
