### ISSUE TITLE
how can i Using Prometheus in Grafana  with origin 3.7?

### ISSUE THREAD

**Issue by pennpeng** [openshift/origin#17742]
##### Version
```
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. i have deploy prometheus use ansible "openshift-ansible/playbooks/byo/openshift-cluster/openshift-prometheus.yml"
2. and  i deploy grafana,but  prometheus use https, the grafana datasource can't connect the prometheus.......

**Comment by pweil-** [comment]
Thanks for contacting us @pennpeng.   For general support/configuration questions please direct this to stack exchange or the dev mailing list.  Thanks!
