### ISSUE TITLE
pkg/apis/core/validation TestValidatePersistentVolumeClaimUpdate 0.01s

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#17769]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17749/test_pull_request_origin_unit/6887/

validation_test.go:1428: Unexpected failure for scenario: valid-size-update-resize-enabled - [spec: Forbidden: is immutable after creation except resources.requests for bound claims]

```
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/apis/core/validation TestValidatePersistentVolumeClaimUpdate 0.01s

validation_test.go:1428: Unexpected failure for scenario: valid-size-update-resize-enabled - [spec: Forbidden: is immutable after creation except resources.requests for bound claims]
```

@openshift/sig-storage

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/test_pull_request_origin_unit/6932/

**Comment by deads2k** [comment]
Well, this flakes because it is racing another test that is also twiddling global feature flags.

**Comment by deads2k** [comment]
opened https://github.com/kubernetes/kubernetes/pull/57199 to fix it upstream

**Comment by deads2k** [comment]
@liggitt want https://github.com/kubernetes/kubernetes/pull/57199 or want a giant lock for a pick?

**Comment by gnufied** [comment]
@deads2k are you sure this is because of feature flag? it sounds like, the feature flag was turned on - https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L1797 but the PVC had some other change other than storage size.

**Comment by gnufied** [comment]
This is related to https://github.com/kubernetes/kubernetes/pull/56395

**Comment by deads2k** [comment]
> This is related to kubernetes/kubernetes#56395

In a serially run for loop, how would that mutation flake?

**Comment by deads2k** [comment]
> This is related to kubernetes/kubernetes#56395

As an alternative theory, the global feature flag was switched before you entered the if and instead of tolerating some changes, you ran in the very tight "only allow X" block.

**Comment by liggitt** [comment]
> In a serially run for loop, how would that mutation flake?

testcases are iterating over a map, so order is random

**Comment by gnufied** [comment]
> As an alternative theory, the global feature flag was switched before you entered the if and instead of tolerating some changes, you ran in the very tight "only allow X" block.

I am not sure how will that happen. My theory is -`ValidatePersistentVolumeClaimUpdate` mutates  the oldPVC at least in 2 places and each test case gets same copy of `pvc` (at least for old version). It is likely that one test case is using side-effect of another test case.
