### ISSUE TITLE
Ceph RBD needs keyring on nodes to release lock

### ISSUE THREAD

**Issue by jocelynthode** [openshift/origin#17777]
When releasing the lock, rbd tries to use a keyring located in /etc/ceph/ instead of using the secret provided to unlock the image. 

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Start a pod with a volume mounted using a secret while the keyring is not present in /etc/ceph
2. Scale down the pod
3. Scale up the pod in a way that makes it scale up on a new node

##### Current Result
The pod is stuck because there is a lock on the image
##### Expected Result
The lock should have been released when the pod scaled down using the ceph secret

**Comment by hufon** [comment]
Hi!, i reproduce the issue with OpenShift 3.7

**Comment by hufon** [comment]
the solution is to have the keyring in /etc/ceph ?

**Comment by jocelynthode** [comment]
Yes having the key in etc/ceph solves the issue. However I think it is impractical to have to copy a key for each user, especially if you intend to have a user per project.

And since openshift is fully capable of locking and mounting the image without having this keyring (which it doesn't need as it has everything it needs with the secrets) I think it should unlock and/or blacklist without the need a keyring

**Comment by hufon** [comment]
What is the behaviour, if the node has a "brutal" shutdown ? Who is responsible to unlock in this case?

**Comment by jocelynthode** [comment]
If you look into rbu_utils.go you can see that in this case the other than has the charge of recreating the pod will remove the previous lock if this lock has no more watchers. 

Le 18 décembre 2017 11:29:25 GMT+01:00, Hubert FONGARNAND <notifications@github.com> a écrit :
>What is the behaviour, if the node has a "brutal" shutdown ? Who is
>responsible to unlock in this case?  
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openshift/origin/issues/17777#issuecomment-352386644

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by jocelynthode** [comment]
/remove-lifecycle stale

Do we have any feedback on this?

**Comment by nak3** [comment]
@jocelynthode @hufon

I have tested steps you provided, but the issue could not be reproduced on OpenShift 3.9. Could you please check if I misunderstood your steps or not?

#### 1. Running pod on knakayam-ose39-crs-node2

~~~
[joe@knakayam-ose39-crs ~]$ oc get pod -o wide
NAME               READY     STATUS    RESTARTS   AGE       IP           NODE
ceph-pod-1-hgrn9   1/1       Running   0          5m        10.128.0.2   knakayam-ose39-crs-node2.example.com
~~~

#### 2. Scale down pod

~~~
[joe@knakayam-ose39-crs ~]$ oc scale --replicas=0 dc ceph-pod 
deploymentconfig "ceph-pod" scaled

[joe@knakayam-ose39-crs ~]$ oc get pod -o wide -w
NAME               READY     STATUS        RESTARTS   AGE       IP           NODE
ceph-pod-1-hgrn9   1/1       Terminating   0          6m        10.128.0.2   knakayam-ose39-crs-node2.example.com

[joe@knakayam-ose39-crs ~]$ oc get pod -o wide -w
~~~

#### 3. Scale up the pod. The new pod was launched on another node (knakayam-ose39-crs-node2)

~~~
[joe@knakayam-ose39-crs ~]$ oc scale --replicas=1 dc ceph-pod 
deploymentconfig "ceph-pod" scaled

[joe@knakayam-ose39-crs ~]$ oc get pod -o wide -w
NAME               READY     STATUS              RESTARTS   AGE       IP        NODE
ceph-pod-1-8mz6x   0/1       ContainerCreating   0          4s        <none>    knakayam-ose39-crs-node1.example.com
ceph-pod-1-8mz6x   1/1       Running   0         12s       10.129.0.12   knakayam-ose39-crs-node1.example.com
~~~

#### 4. Make sure that ceph rbd is mounted on new pod as well.

~~~
[joe@knakayam-ose39-crs ~]$ oc rsh ceph-pod-1-8mz6x mount |grep rbd
/dev/rbd0 on /usr/share/busybox type ext4 (rw,seclabel,relatime,stripe=1024,data=ordered)
~~~

**Comment by nak3** [comment]
I am wondering that this issue happened when Rolling strategy instead of Recreate was used. (Though it is different from [Steps To Reproduce](https://github.com/openshift/origin/issues/17777#issue-282041066))
