### ISSUE TITLE
error: unable to recognize kind=HorizontalPodAutoScaler

### ISSUE THREAD

**Issue by yeshy1987** [openshift/origin#17775]
We are using json file format template to create the deployment config. I am also trying to include the auto scaler object as part of this deployment template. While including this in the template and trying to process the same, encounter this issue:
error: unable to recognize /v1, Kind=HorizontalPodAutoscaler: no matches for /, Kind=HorizontalPodAutoscaler.

Env: OpenShift v3.4.1.44.26.

Appreciate any help.

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by DirectXMan12** [comment]
HPA is in the `autoscaling/v1` API group not just `v1`.  Please make sure you've specified the correct API version, and re-open if necessary.
