### ISSUE TITLE
[k8s conformace failure] validates resource limits of pods that are allowed to run

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17782]
```
[Fail] [sig-scheduling] SchedulerPredicates [Serial] [It] validates resource limits of pods that are allowed to run [Conformance] 
/data/src/github.com/openshift/origin/_output/components/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:4675
```
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_k8s/182/consoleFull#9553647145898c58db7602c31c0eab717

/sig pod
/area tests
@openshift/sig-pod 
/assign sjenning

**Comment by kargakis** [comment]
Seems broken
/priority P0
/kind test-flake

**Comment by kargakis** [comment]
https://deck-ci.svc.ci.openshift.org/?job=test_branch_origin_extended_conformance_k8s

**Comment by aveshagarwal** [comment]
This one and the other scheduler predicate tests here https://github.com/openshift/origin/issues/17682 are failing for the same reason that the router-1-deploy pod is failing to scheduler due to following reason:

```
Dec 14 12:47:18.978: INFO: router-1-deploy                                            Pending         [{PodScheduled False 0001-01-01 00:00:00 +0000 UTC 2017-12-14 11:39:48 +0000 UTC Unschedulable 0/4 nodes are available: 1 NodeUnschedulable, 4 MatchNodeSelector.}]
```

**Comment by aveshagarwal** [comment]
```
UTC Unschedulable 0/4 nodes are available: 1 NodeUnschedulable, 4 MatchNodeSelector.}]
```

Either we changed something w.r.t. NodeSelectors or the node where the router-1-deploy pod could be scheduled is going into Unscheduable state.

**Comment by aveshagarwal** [comment]
Since https://github.com/openshift/origin/issues/17682 is closed, I am closing this too as this was failing for the same reason. Please reopen if the issue persists.
