### ISSUE TITLE
Unable to monitor quota for openshift resources

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#17784]
Seen in integration test logs:

`
E1214 09:29:03.747036   30369 resource_quota_controller.go:170] initial monitor sync has error: [couldn't start monitor for resource {"route.openshift.io" "v1" "routes"}: unable to monitor quota for resource "route.openshift.io/v1, Resource=routes", couldn't start monitor for resource {"image.openshift.io" "v1" "imagestreamtags"}: unable to monitor quota for resource "image.openshift.io/v1, Resource=imagestreamtags", couldn't start monitor for resource {"network.openshift.io" "v1" "egressnetworkpolicies"}: unable to monitor quota for resource "network.openshift.io/v1, Resource=egressnetworkpolicies"]
`

Seems to be related to our generic informer:

`
I1214 14:13:31.868263   18394 resource_quota_monitor.go:179] QuotaMonitor unable to use a shared informer for resource "route.openshift.io/v1, Resource=routes": no informer found for {route.openshift.io v1 routes}
`

Seems to not be breaking anything, just producing annoying logs, bumping priority.

**Comment by dmage** [comment]
it might affect the registry extended tests: openshift/origin#17786
