### ISSUE TITLE
"oc auth can-i" command should not exit 0 if the user can't execute a command

### ISSUE THREAD

**Issue by dmsimard** [openshift/origin#17812]
Right now, regardless if a user has the privileges to execute a command or not, the "oc auth can-i" command will exit 0.

This means when programmatically using the command, we need to rely on parsing the string response of the command instead of using the exit code.

(Simplified) example:
oc auth can-i prune images && oc prune images
oc auth can-i prune images || echo "error: current user can't prune images"; exit 1

##### Version
oc v3.7.0-rc.0+e92d5c5
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.7.0-rc.0+e92d5c5
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
- Run an "oc auth can-i" command that the current user is expected to be able to run
- Run an "oc auth can-i" command that the current user is not expected to be able to run

##### Current Result
```
# oc auth can-i prune images && echo $?
no - User "system:serviceaccount:default:some.service" cannot "prune" "images" with name "" in project "master"
0
```
```
# oc auth can-i prune images && echo $?
yes
0
```

##### Expected Result
```
# oc auth can-i prune images || echo $?
no - User "system:serviceaccount:default:some.service" cannot "prune" "images" with name "" in project "master"
1
```
```
# oc auth can-i prune images && echo $?
yes
0
```

**Comment by fbac** [comment]
I created a PR in kubernetes a few days ago addressing this issue: https://github.com/kubernetes/kubernetes/pull/59579

That way we give some consistency to the can-i exit code.

**Comment by dmsimard** [comment]
@fbac thanks for the PR! It's a small quality of life thing :)
