### ISSUE TITLE
github.com/openshift/origin/test/cmd/observe test/cmd/observe.sh:34: executing 'oc observe services --once --all-namespaces -a "bad{ .metadata.annotations.unset }key" --strict-templates' expecting failure and text 'annotations is not found'

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#17811]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17717/test_pull_request_origin_cmd/7451/

```
=== BEGIN TEST CASE ===
test/cmd/observe.sh:34: executing 'oc observe services --once --all-namespaces -a "bad{ .metadata.annotations.unset }key" --strict-templates' expecting failure and text 'annotations is not found'
FAILURE after 0.322s: test/cmd/observe.sh:34: executing 'oc observe services --once --all-namespaces -a "bad{ .metadata.annotations.unset }key" --strict-templates' expecting failure and text 'annotations is not found': the output content test failed
Standard output from the command:
# 2017-12-14T15:13:01Z Sync started

Standard error from the command:
error: unable to write arguments: error executing template 'bad{ .metadata.annotations.unset }key': 'unset is not found'
----data----
map[kind:Service apiVersion:v1 metadata:map[annotations:map[service.alpha.kubernetes.io/tolerate-unready-endpoints:true] name:galera namespace:default selfLink:/api/v1/namespaces/default/services/galera uid:5ee8d7ac-e0df-11e7-8591-0242ac110002 resourceVersion:1446 creationTimestamp:2017-12-14T14:59:23Z labels:map[app:mysql]] spec:map[clusterIP:None type:ClusterIP sessionAffinity:None ports:[map[targetPort:3306 name:mysql protocol:TCP port:3306]] selector:map[app:mysql]] status:map[loadBalancer:map[]]]
=== END TEST CASE ===
```

Seems like a rebase kind of thing, but did not investigate in detail.  Re-categorize if needed please.

Marking as test flake as well, but did not see if it happens consistently locally.

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17989/test_pull_request_origin_cmd/8090/

**Comment by bparees** [comment]
@mfojtik who's investigating this flake? what have they discovered so far?

**Comment by ironcladlou** [comment]
@bparees 
>who's investigating this flake? what have they discovered so far?

I just discovered that I'm investigating

**Comment by ironcladlou** [comment]
Add an annotation to a service, like services/kubernetes: `service.alpha.kubernetes.io/tolerate-unready-endpoints=true`, then run:

`oc observe services --once --all-namespaces -a "bad{ .metadata.annotations.unset }key" --strict-templates`

and the error is reproduced. I assume because `annotations` exists, but the `unset` key doesn't, causing the error to not match the test's expectation.

Seems like the [test case](https://github.com/openshift/origin/blob/master/test/cmd/observe.sh#L34) should tolerate objects with both missing and empty annotation field?

**Comment by juanvallejo** [comment]
@ironcladlou 
> Seems like the test case should tolerate objects with both missing and empty annotation field?

I agree, the test should be updated to tolerate both cases
