### ISSUE TITLE
No external connectivity to Services (Apps)

### ISSUE THREAD

**Issue by hussainaljamri** [openshift/origin#17824]
Using a route to gain external access to services fails, connection refused.

##### Version
[provide output of the `openshift version` or `oc version` command]
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8

i installed Openshift Origin 3.7 on AWS using the advanced installation method (Ansible). it is a 4-node setup. Everything works as expected. I can access pods/services from within the cluster. I am using nip.io for wildcard DNS.

##### Current Result
when I create a route for any given service (or it is created automatically for me) and try to access it from my local machine, the page does not load. when I try it using /dev/tcp/hostname/port i get connection refused. when I try it from within the cluster using the cluster IP of the given service (or pod), it works. everything works perfectly from within the cluster.

##### Expected Result
Opening web pages using the created routes should work. and it did work briefly. 

##### Additional Information
The operating system is CentOS 7.

I can also ping ANY cluster IP that is assigned to the nodes from within the cluster. so connectivity between nodes is fine. I went through this guide [https://docs.openshift.org/latest/admin_guide/sdn_troubleshooting.html#debugging-a-service](url) 

The only thing that seems a bit awkward is that when I try to get the endpoint for a specific service using 'oc', it does not return anything. when I use '--all-namespaces' it shows me the endpoints for everything.

The Ansible hosts file used for the installation:

[oo_hosts.txt](https://github.com/openshift/origin/files/1562056/oo_hosts.txt)

**Comment by hussainaljamri** [comment]
Solved. The IP I should use in the Routes needs to point to the openshift router. I was using the master node IP for some reason. There is (I believe) nothing that explains that in the docs.

**Comment by pweil-** [comment]
Thanks for following up.  We briefly mention in docs that routers must be exposed externally and that configuration of a CNAME for a route should point to the router's canonical host name.  In order to help usability would you mind telling us where you were looking in the docs, maybe we can put some of this information in a more obvious section.  Thanks!

**Comment by hussainaljamri** [comment]
I was following the advanced installer section. I think it would be very helpful to mention this in the pre-requisites section where all the required ports are listed. Also in the Ansible inventory section for the variables.
