### ISSUE TITLE
TestStartingResourceVersion flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17825]
```
panic: interface conversion: runtime.Object is nil, not *example.Pod [recovered]
panic: interface conversion: runtime.Object is nil, not *example.Pod

goroutine 702 [running]:
testing.tRunner.func1(0xc4208f4780)
/usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0x16983e0, 0xc42095f340)
/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/tests.TestStartingResourceVersion(0xc4208f4780)
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/tests/cacher_test.go:519 +0xba5
testing.tRunner(0xc4208f4780, 0x188a2e8)
/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
/usr/local/go/src/testing/testing.go:789 +0x569
FAIL	github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/tests	5.699s
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17746/test_pull_request_origin_unit/7012/
/sig storage
/kind test-flake
/area tests
@openshift/sig-storage

**Comment by jsafrane** [comment]
/sig master
@openshift/sig-master 
"storage" here refers to storage of API objects in etcd, not storage volumes.

**Comment by ironcladlou** [comment]
When's the last time this was observed? 3000 runs of TestStartingResourceVersion with `stress` and no failures so far.

**Comment by soltysh** [comment]
@ironcladlou if you haven't been able to reproduce it and didn't find any recent failures in our CI lower the priority and if it doesn't happen in some time - you're free to close it.

**Comment by ironcladlou** [comment]
@soltysh 
>@ironcladlou if you haven't been able to reproduce it and didn't find any recent failures in our CI lower the priority and if it doesn't happen in some time - you're free to close it.

I have no idea how to assess its frequency given the state of our CI analysis tooling. I'm going to lower the priority until somebody complains.

**Comment by ironcladlou** [comment]
Closing. Please re-open if there's still a problem.
