### ISSUE TITLE
node to master communication : error x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by esquare666** [openshift/origin#17847]
Description of the issue: 
We have installed openshift with 3 master, 3 infra node and 3 application node. created F5 VIP with own CA certificate for master. When node is trying to connect to master and ends up with an error
Dec 18 10:12:06 infra-01 atomic-openshift-node[130154]: I1218 10:12:06.294946  130154 start_node.go:251] Reading node configuration from /etc/origin/node/node-config.yaml
Dec 18 10:12:06 infra-01 atomic-openshift-node[130154]: F1218 10:12:06.336639  130154 start_node.go:140] cannot fetch "default" cluster network: Get https://ocp-master.dev.internal.abc.co.xx:443/oapi/v1/clusternetworks/default: x509: certificate signed by unknown authority

##### Version
oc v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ocp-master.dev.internal.abc.co.xx:443
openshift v3.6.173.0.49
kubernetes v1.6.1+5115d708d7

##### Current Result
The node servers are unable to connect to master node

##### Expected Result
Node server should be communicate with master server through F5 VIP. Would like to add the F5 CA certificate to node / master servers.

**Comment by sdodson** [comment]
@esquare666 Do you need to terminate TLS at the F5 device? We've always assumed that layer 4 load balancing was used so that the load balancer need not terminate TLS.

**Comment by esquare666** [comment]
@sdodson, Thanks for the information.  We are terminating SSL  on f5, since we use same F5 VIP for master console. Is that separate F5 VIP required for node to master communication and master console ?
