### ISSUE TITLE
Ceph RBD user secret should be optional in StorageClass

### ISSUE THREAD

**Issue by madddi** [openshift/origin#17853]
`userSecretName` is a mandatory parameter for the `kubernetes.io/rbd` storage provisioner. Ceph RBD persistent volumes however don't need the `secretRef`. If no secret is given, a local keyring file (`/etc/ceph/keyring`) on the node will be used. This behaviour should also work with the storage provisioner. If no `userSecretName` parameter is given, no `secretRef` should be created in the resulting persistent volume. 

I could submit a patch making the parameter optional.

##### Version
OpenShift Origin v3.7.0

##### Steps To Reproduce
1. Create a StorageClass with an empty `userSecretName`
2. Create a PVC for this StorageClass
3. The volume cannot be provisioned: `failed to provision volume for claim "test-ns/some-pvc" with StorageClass "rbd": missing user secret name`

1. Create a volume and a corresponding PersistentVolumeClaim without a `secretRef`
2. Place a keyring file on the node
3. The volume gets attached

##### Current Result
RBD StorageClasses can only be used with secrets in the target namespaces 

##### Expected Result
RBD StorageClasses should have the same mandatory parameters as the corresponding PersistentVolumes.

##### Additional Information
The error is thrown in rbd.go: https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd.go#L475

**Comment by php-coder** [comment]
Looks like upstream issue.

CC @openshift/sig-storage

**Comment by jsafrane** [comment]
Yes, please fix it in Kubernetes and it will appear in the next OpenShift release.
