### ISSUE TITLE
buildconfig env variables not propagated to language builder

### ISSUE THREAD

**Issue by bparees** [openshift/origin#1787]
if a user sets env variables on the STI strategy, they should be available to the assemble/run scripts.

currently they are not.

@thoraxe @mfojtik

**Comment by danmcp** [comment]
@bparees Still an issue?

**Comment by bparees** [comment]
nope, fixed with:
https://github.com/openshift/origin/pull/1983
and
https://github.com/openshift/origin/pull/1808

I thought this comment would auto-close the issue when the PR merged, but apparently not:
https://github.com/openshift/origin/pull/1808#issuecomment-94347503
