### ISSUE TITLE
OC login : TLS handshake timeout in macSierra (Version 10.12.6)

### ISSUE THREAD

**Issue by mohansidda** [openshift/origin#17871]
I am unable to login using oc command in mac latptop. can you please help me to fix this issue??

1. I tried with OCP 3.7.9 (latest and tried) still seeing same error. 

dhcp-65-177:Downloads msidda$ oc version
oc v3.7.9
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

error: server took too long to respond with version information.

2. I downloaded OCP 3.6 and tried. same error:
dhcp-65-177:Downloads msidda$ ./oc version
oc v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
features: Basic-Auth
error: server took too long to respond with version information.

dhcp-65-177:Downloads msidda$

3. I tried login --insecure (FYI below URL) still getting same error. 
 oc login https://master.hb.rht-labs.com --insecure-skip-tls-verify=true
4. Tried with login port 8443 still same error. oc login https://master.hb.rht-labs.com:8443

5. I don't find ˜/.kube directory in my laptop ??

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
features: Basic-Auth
##### Steps To Reproduce
1. [step 1]
oc login https://master.hb.rht-labs.com 
(OR)
 oc login https://master.hb.rht-labs.com --insecure-skip-tls-verify=true
2. [step 2]

##### Current Result
error: net/http: TLS handshake timeout
##### Expected Result
Shold be able login openshift

##### Additional Information
diagnostices : 
-------
msidda-OSX:camel-jdbc-jms-transaction msidda$ oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
[Note] No client configuration specified; skipping client and cluster diagnostics.
[Note] Summary of diagnostics execution (version v3.6.173.0.49):
[Note] Completed with no errors or warnings seen.
---------
msidda-OSX:camel-jdbc-jms-transaction msidda$ oc get all -o json -n master.hb.rht-labs.com
Unable to connect to the server: net/http: TLS handshake timeout
msidda-OSX:camel-jdbc-jms-transaction msidda$
-----------
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by pweil-** [comment]
I do not think we have enough information to go on here.  It appears the client is not getting a response so you'd need to ensure that it is actually reaching the server and if so, what is happening servers side (via the logs, set to an appropriate log level for debugging).  

Just as a quick test, I was able to reach master.hb.rht-labs.com, the console displays fine and a cli login attempt seems to give me  a 401 access denied when using test/test. 

I would recommend first ensuring you can login from the server to ensure there are not network issues and posting install questions to stack exchange or the dev mailing list.  It may help you debug if you add `--loglevel=9` to the cli command so you can see more details (example below):


```
[pweil@localhost origin]$ oc login -u test -p test https://master.hb.rht-labs.com --loglevel=9
...snip...
I1219 07:16:35.071224   17227 round_trippers.go:405] HEAD https://master.hb.rht-labs.com:443/  in 552 milliseconds
I1219 07:16:35.071252   17227 round_trippers.go:411] Response Headers:
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

I1219 07:16:40.112817   17227 round_trippers.go:386] curl -k -v -XGET  -H "X-Csrf-Token: 1" https://master.hb.rht-labs.com:443/oauth/authorize?client_id=openshift-challenging-client&response_type=token
I1219 07:16:41.224186   17227 round_trippers.go:405] GET https://master.hb.rht-labs.com:443/oauth/authorize?client_id=openshift-challenging-client&response_type=token 401 Unauthorized in 1111 milliseconds
..snip...
I1219 07:16:41.477239   17227 round_trippers.go:405] GET https://master.hb.rht-labs.com:443/oauth/authorize?client_id=openshift-challenging-client&response_type=token 401 Unauthorized in 252 milliseconds
I1219 07:16:41.477311   17227 round_trippers.go:411] Response Headers:
I1219 07:16:41.477354   17227 round_trippers.go:414]     Www-Authenticate: Basic realm="openshift"
I1219 07:16:41.477384   17227 round_trippers.go:414]     Content-Type: text/plain; charset=utf-8
I1219 07:16:41.477420   17227 round_trippers.go:414]     Content-Length: 0
I1219 07:16:41.477479   17227 round_trippers.go:414]     Date: Tue, 19 Dec 2017 12:16:41 GMT
I1219 07:16:41.477613   17227 basicauth.go:51] already handled basic challenge
Login failed (401 Unauthorized)
```

**Comment by mohansidda** [comment]
Hi Paul, 
Thanks for quick response. find here screen snippets -

msidda-OSX:~ msidda$ oc login -u test -p test https://master.hb.rht-labs.com --loglevel=9
I1219 20:35:50.963874    2599 round_trippers.go:386] curl -k -v -XHEAD  https://master.hb.rht-labs.com:443/
I1219 20:36:01.831396    2599 round_trippers.go:405] HEAD https://master.hb.rht-labs.com:443/  in 10867 milliseconds
I1219 20:36:01.831418    2599 round_trippers.go:411] Response Headers:
F1219 20:36:01.832804    2599 helpers.go:119] error: net/http: TLS handshake timeout
----------------
msidda-OSX:~ msidda$ curl -k -v -XGET  -H "X-Csrf-Token: 1" https://master.hb.rht-labs.com:443/oauth/authorize?client_id=openshift-challenging-client&response_type=token
[1] 2942
msidda-OSX:~ msidda$ Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 52.63.144.47...
* TCP_NODELAY set
* Connected to master.hb.rht-labs.com (127.0.0.1) port 443 (#0)
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: 172.30.0.1
* Server certificate: openshift-signer@1509387991
> GET /oauth/authorize?client_id=openshift-challenging-client HTTP/1.1
> Host: master.hb.rht-labs.com
> User-Agent: curl/7.54.0
> Accept: */*
> X-Csrf-Token: 1
>
< HTTP/1.1 302 Found
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Expires: Fri, 01 Jan 1990 00:00:00 GMT
< Location: https://master.hb.rht-labs.com/oauth/token/implicit?error=unsupported_response_type&error_description=The+authorization+server+does+not+support+obtaining+a+token+using+this+method.
< Pragma: no-cache
< Date: Tue, 19 Dec 2017 12:40:22 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host master.hb.rht-labs.com left intact
------------
