### ISSUE TITLE
[sig-storage] Downward API volume should update labels on modification [Conformance] [Suite:openshift/conformance/parallel] [Suite:k8s] 3m21s

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#17882]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17876/test_pull_request_origin_extended_conformance_install/4421/

[sig-storage] Downward API volume should update labels on modification [Conformance] [Suite:openshift/conformance/parallel] [Suite:k8s] 3m21s
```
    content of file "/etc/labels": key1="value1"
    key2="value2"
    content of file "/etc/labels": key1="value1"
    key2="value2"
    
to contain substring
    <string>: key3="value3"
    
/tmp/openshift/build-rpm-release/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:144
```

**Comment by tnozicka** [comment]
https://github.com/openshift/origin/issues/17882

**Comment by sosiouxme** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18186/test_pull_request_origin_extended_conformance_install/5951/

**Comment by sosiouxme** [comment]
Is this different from https://github.com/openshift/origin/issues/12629 ?

**Comment by jpeeler** [comment]
From https://github.com/openshift/openshift-ansible/pull/7095:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/7095/test_pull_request_openshift_ansible_extended_conformance_install/5078/
