### ISSUE TITLE
While the jUnit report found no failed tests, the `go test` process failed.

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#17881]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17773/test_pull_request_origin_unit/7205/

Infrastructure failure? I couldn't see anything that actually failed.

```
[INFO] No compiled `junitreport` binary was found. Attempting to build one using:
[INFO]   $ hack/build-go.sh tools/junitreport
++ Building go targets for linux/amd64: tools/junitreport
[INFO] hack/build-go.sh exited with code 0 after 00h 00m 08s
[INFO] jUnit XML report placed at _output/scripts/test-go/artifacts/gotest_report_2ggl5.xml
Of 7896 tests executed in 2809.503s, 7872 succeeded, 0 failed, and 24 were skipped.
[...]
[WARNING] While the jUnit report found no failed tests, the `go test` process failed.
[WARNING] This usually means that the unit test suite failed to compile.
[ERROR] hack/test-go.sh exited with code 1 after 00h 34m 01s
make: *** [test-unit] Error 1
[ERROR] PID 12710: hack/lib/build/environment.sh:170: `return "${exitcode}"` exited with status 2.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/build/environment.sh:170: `return "${exitcode}"`
[INFO] 		  2: hack/lib/build/environment.sh:279: os::build::environment::withsource
[INFO] 		  3: hack/env:42: os::build::environment::run
[INFO]   Exiting with code 2.
```

**Comment by stevekuznetsov** [comment]
We have this code in the script:

```sh
    if [[ -s "${test_error_file}" ]]; then
        os::log::warning "\`go test\` had the following output to stderr:
$( cat "${test_error_file}") "
    fi
```

So since we don't see that, `go test` didn't spit out anything to `stderr` and failed without any failed tests? Weird. Can you reproduce this?

**Comment by sosiouxme** [comment]
Nope, haven't seen it before or since. If there's no progress to be made, seems fine to close it until it shows up again.

**Comment by stevekuznetsov** [comment]
Seems reasonable to me

/close

**Comment by gabemontero** [comment]
I'll defer to @stevekuznetsov and @jupierce on whether to reopen this, but I just saw this with 
PR https://github.com/openshift/origin/pull/18272 and unit test run https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18272/test_pull_request_origin_unit/9214/

This is the first time I've seen it with this PR

about to retest there  .... I'll report back if there is any consistency with the failure

**Comment by gabemontero** [comment]
Yeah no more failures for me on several test runs after seeing this.
