### ISSUE TITLE
oc 1.5 breaks against go >= 1.8

### ISSUE THREAD

**Issue by khatribharat** [openshift/origin#17898]
`oc` breaks against go >= 1.8 due to a breaking change in `net/url`
The release notes for `net/url` are available [here](https://golang.org/doc/go1.8#net_url)

This is the breaking change in `net/url`
```
Following RFC 3986, Parse now rejects URLs like this_that:other/thing instead of 
interpreting them as relative paths (this_that is not a valid scheme). To force 
interpretation as a relative path, such URLs should be prefixed with "./". 
The URL.String method now inserts this prefix as needed.
```
[This](https://github.com/openshift/origin/blob/v1.5.1/pkg/generate/git/git.go#L23) is the cause of error.

##### Version
```
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth
```

##### Steps To Reproduce
```
> oc new-build  openshift/nodejs-010-centos7~git@bitbucket.org:me/myrepo.git --dry-run
error: Unable to connect to the server: first path segment in URL cannot contain colon
```

**Comment by php-coder** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
Known issue, fixed in newer releases.

**Comment by khatribharat** [comment]
In that case, the build process `make all WHAT=cmd/oc GOFLAGS=-v` should fail if the go version is above 1.7.
