### ISSUE TITLE
No graceful stop for rolling deploys?

### ISSUE THREAD

**Issue by perfectglitch** [openshift/origin#17895]
Hi,

Whenever OS3 pod dies during startup while Spring + Liquibase are applying changesets to database schema a lock stays in DB that doesn't allow subsequent pods to start(Liquibase change log lock).

I implemented a shutdown hook in Spring app Java code that removes locks created by current host before shutting down.

Now to the problem...

Java runtime shutdown hooks are not executing in OS3 when container is shut down during rolling deploy or cancelled deployment. Same hook is always called when running the app locally in Docker and doing `docker stop [container]`

I tried extending the grace period for pod shutdown but that didn't help.

##### Workarond
Currently using Kubernetes preStop hook to issue linux pkill command, which seems to gracefully stop running Spring app and my Java hook gets executed too.

##### Version
OpenShift Master:
v1.3.3
Kubernetes Master:
v1.3.0+52492b4

##### Steps To Reproduce
1. add shutdown hook to Java app using 
`Runtime.getRuntime()..addShutdownHook(new Thread...`
2. deploy app in Docker container to OS3.
3. make another deploy to roll over current deployment

##### Current Result
Java process is killed without shutdown hook ever executing.

##### Expected Result
Java process is ended gracefully with defined hook executing before process is ended and pod deleted.

**Comment by perfectglitch** [comment]
Somebody already showed me the light: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by roshandawrani** [comment]
Hi, can you please throw some more light on what light did you see in that article? I have just run into the same issue of the shutdown hook not executing in a rolling deployment related shutdown and was curious about your closing views in the thread above.

**Comment by perfectglitch** [comment]
If I'm not mistaken I modified the startup shell script so that it would propagate SIGTERM to the Java process. http://veithen.io/2014/11/16/sigterm-propagation.html

**Comment by roshandawrani** [comment]
Thank you for replying. For now, I went ahead using Kubernetes' "preStop" lifecycle handler (with an httpGet to invoke the piece I wanted to get executed in my shutdown-hook), but I'll go through both you links here. Seem interesting.
