### ISSUE TITLE
Problem importing S2I builder into management console catalog

### ISSUE THREAD

**Issue by lance** [openshift/origin#17905]
The instructions [here](https://docs.openshift.com/container-platform/3.7/dev_guide/managing_images.html#writing-image-streams-for-s2i-builders) to create and import an image stream so that it will display in the catalog, do not have the intended result. 

The image stream is imported, and appears in Build -> Images. However, after import, it does not appear in the catalog. To ensure there was no problem with `JSON`, or even the format of my file, I tried the same thing with the example YAML on the documentation page referenced above still with no luck.

![screen shot 2017-12-19 at 5 52 41 pm](https://user-images.githubusercontent.com/15952/34222100-673bb9ce-e588-11e7-93ed-59b16a360122.png)

The `ImageStream` being imported may be found [here](https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/image-streams.centos7.json).

##### Version

```txt
~/s/centos7-s2i-nodejs (master $=) oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce
1. `git clone https://github.com/bucharest-gold/centos7-s2i-nodejs.git`
2. `cd centos7-s2i-nodejs`
3. `oc import -f ./image-streams-centos7.json`

##### Current Result

```sh
~/s/centos7-s2i-nodejs (master $=) oc create -f image-streams.centos7.json
imagestream "centos7-s2i-nodejs" created
```

However the image stream does not appear in the catalog.

##### Expected Result

The image stream should appear in the catalog.

##### Additional Information
<details><summary>
~/s/centos7-s2i-nodejs (master $=) oc adm diagnostics
</summary>
<code><pre>
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/Users/lanceball/.kube/config'
[Note] Could not configure a client with cluster-admin permissions for the current server, so cluster diagnostics will be skipped

[Note] Running diagnostic: ConfigContexts[default/192-168-99-102:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0010 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'default/192-168-99-102:8443/system:admin':
       The server URL is 'https://192.168.99.102:8443'
       The user authentication is 'system:admin/127-0-0-1:8443'
       The current project is 'default'
       (*url.Error) Get https://192.168.99.102:8443/apis/project.openshift.io/v1/projects: dial tcp 192.168.99.102:8443: i/o timeout

       This means that when we tried to connect to the master API server,
       we could not reach the host at all.
       * You may have specified the wrong host address.
       * This could mean the host is completely unavailable (down).
       * This could indicate a routing problem or a firewall that simply
         drops requests rather than responding by resetting the connection.
       * It does not generally mean that DNS name resolution failed (which
         would be a different error) though the problem could be that it
         gave the wrong address.

[Note] Running diagnostic: ConfigContexts[myproject/192-168-99-102:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0010 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'myproject/192-168-99-102:8443/system:admin':
       The server URL is 'https://192.168.99.102:8443'
       The user authentication is 'system:admin/192-168-99-102:8443'
       The current project is 'myproject'
       (*url.Error) Get https://192.168.99.102:8443/apis/project.openshift.io/v1/projects: dial tcp 192.168.99.102:8443: i/o timeout

       This means that when we tried to connect to the master API server,
       we could not reach the host at all.
       * You may have specified the wrong host address.
       * This could mean the host is completely unavailable (down).
       * This could indicate a routing problem or a firewall that simply
         drops requests rather than responding by resetting the connection.
       * It does not generally mean that DNS name resolution failed (which
         would be a different error) though the problem could be that it
         gave the wrong address.

[Note] Running diagnostic: ConfigContexts[testing-nodeshift/192-168-99-100:8443/developer]
       Description: Validate client config context is complete and has connectivity

Info:  For client config context 'testing-nodeshift/192-168-99-100:8443/developer':
       The server URL is 'https://192.168.99.100:8443'
       The user authentication is 'developer/192-168-99-100:8443'
       The current project is 'testing-nodeshift'
       Successfully requested project list; has access to project(s):
         [myproject]

[Note] Running diagnostic: ConfigContexts[circuit-breaker-demo/192-168-99-101:8443/developer]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0010 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'circuit-breaker-demo/192-168-99-101:8443/developer':
       The server URL is 'https://192.168.99.101:8443'
       The user authentication is 'developer/192-168-99-101:8443'
       The current project is 'circuit-breaker-demo'
       (*url.Error) Get https://192.168.99.101:8443/apis/project.openshift.io/v1/projects: dial tcp 192.168.99.101:8443: i/o timeout

       This means that when we tried to connect to the master API server,
       we could not reach the host at all.
       * You may have specified the wrong host address.
       * This could mean the host is completely unavailable (down).
       * This could indicate a routing problem or a firewall that simply
         drops requests rather than responding by resetting the connection.
       * It does not generally mean that DNS name resolution failed (which
         would be a different error) though the problem could be that it
         gave the wrong address.

[Note] Running diagnostic: ConfigContexts[mong-js-project/192-168-99-100:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0013 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'mong-js-project/192-168-99-100:8443/system:admin':
       The server URL is 'https://192.168.99.100:8443'
       The user authentication is 'system:admin/192-168-99-100:8443'
       The current project is 'mong-js-project'
       (*errors.StatusError) User "system:anonymous" cannot list projects.project.openshift.io at the cluster scope: User "system:anonymous" cannot list all projects.project.openshift.io in the cluster (get projects.project.openshift.io)

       This means that when we tried to make a request to the master API
       server, your kubeconfig did not present valid credentials to
       authenticate your client. Credentials generally consist of a client
       key/certificate or an access token. Your kubeconfig may not have
       presented any, or they may be invalid.

[Note] Running diagnostic: ConfigContexts[/192-168-99-104:8443/developer]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0010 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context '/192-168-99-104:8443/developer':
       The server URL is 'https://192.168.99.104:8443'
       The user authentication is 'developer/192-168-99-104:8443'
       The current project is 'default'
       (*url.Error) Get https://192.168.99.104:8443/apis/project.openshift.io/v1/projects: dial tcp 192.168.99.104:8443: i/o timeout

       This means that when we tried to connect to the master API server,
       we could not reach the host at all.
       * You may have specified the wrong host address.
       * This could mean the host is completely unavailable (down).
       * This could indicate a routing problem or a firewall that simply
         drops requests rather than responding by resetting the connection.
       * It does not generally mean that DNS name resolution failed (which
         would be a different error) though the problem could be that it
         gave the wrong address.

[Note] Running diagnostic: ConfigContexts[default/192-168-99-104:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0010 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'default/192-168-99-104:8443/system:admin':
       The server URL is 'https://192.168.99.104:8443'
       The user authentication is 'system:admin/192-168-99-104:8443'
       The current project is 'default'
       (*url.Error) Get https://192.168.99.104:8443/apis/project.openshift.io/v1/projects: dial tcp 192.168.99.104:8443: i/o timeout

       This means that when we tried to connect to the master API server,
       we could not reach the host at all.
       * You may have specified the wrong host address.
       * This could mean the host is completely unavailable (down).
       * This could indicate a routing problem or a firewall that simply
         drops requests rather than responding by resetting the connection.
       * It does not generally mean that DNS name resolution failed (which
         would be a different error) though the problem could be that it
         gave the wrong address.

[Note] Running diagnostic: ConfigContexts[/192-168-99-103:8443/developer]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0010 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context '/192-168-99-103:8443/developer':
       The server URL is 'https://192.168.99.103:8443'
       The user authentication is 'developer/192-168-99-103:8443'
       The current project is 'default'
       (*url.Error) Get https://192.168.99.103:8443/apis/project.openshift.io/v1/projects: dial tcp 192.168.99.103:8443: i/o timeout

       This means that when we tried to connect to the master API server,
       we could not reach the host at all.
       * You may have specified the wrong host address.
       * This could mean the host is completely unavailable (down).
       * This could indicate a routing problem or a firewall that simply
         drops requests rather than responding by resetting the connection.
       * It does not generally mean that DNS name resolution failed (which
         would be a different error) though the problem could be that it
         gave the wrong address.

[Note] Running diagnostic: ConfigContexts[myproject/192-168-99-102:8443/developer]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0010 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'myproject/192-168-99-102:8443/developer':
       The server URL is 'https://192.168.99.102:8443'
       The user authentication is 'developer/192-168-99-102:8443'
       The current project is 'myproject'
       (*url.Error) Get https://192.168.99.102:8443/apis/project.openshift.io/v1/projects: dial tcp 192.168.99.102:8443: i/o timeout

       This means that when we tried to connect to the master API server,
       we could not reach the host at all.
       * You may have specified the wrong host address.
       * This could mean the host is completely unavailable (down).
       * This could indicate a routing problem or a firewall that simply
         drops requests rather than responding by resetting the connection.
       * It does not generally mean that DNS name resolution failed (which
         would be a different error) though the problem could be that it
         gave the wrong address.

[Note] Running diagnostic: ConfigContexts[lball1/api-starter-us-east-2-openshift-com:443/lball1@redhat.com]
       Description: Validate client config context is complete and has connectivity

Info:  For client config context 'lball1/api-starter-us-east-2-openshift-com:443/lball1@redhat.com':
       The server URL is 'https://api.starter-us-east-2.openshift.com:443'
       The user authentication is 'lball1@redhat.com/api-starter-us-east-2-openshift-com:443'
       The current project is 'lball1'
       Successfully requested project list; has access to project(s):
         [lball1 lball1-che lball1-jenkins lball1-run lball1-stage]

[Note] Running diagnostic: ConfigContexts[default/127-0-0-1:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0015 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'default/127-0-0-1:8443/system:admin':
       The server URL is 'https://127.0.0.1:8443'
       The user authentication is 'system:admin/127-0-0-1:8443'
       The current project is 'default'
       (*url.Error) Get https://127.0.0.1:8443/apis/project.openshift.io/v1/projects: dial tcp 127.0.0.1:8443: getsockopt: connection refused
       Diagnostics does not have an explanation for what this means. Please report this error so one can be added.

[Note] Running diagnostic: ConfigContexts[/192-168-99-101:8443/admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0010 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context '/192-168-99-101:8443/admin':
       The server URL is 'https://192.168.99.101:8443'
       The user authentication is 'admin/192-168-99-101:8443'
       The current project is 'default'
       (*url.Error) Get https://192.168.99.101:8443/apis/project.openshift.io/v1/projects: dial tcp 192.168.99.101:8443: i/o timeout

       This means that when we tried to connect to the master API server,
       we could not reach the host at all.
       * You may have specified the wrong host address.
       * This could mean the host is completely unavailable (down).
       * This could indicate a routing problem or a firewall that simply
         drops requests rather than responding by resetting the connection.
       * It does not generally mean that DNS name resolution failed (which
         would be a different error) though the problem could be that it
         gave the wrong address.

[Note] Running diagnostic: ConfigContexts[default/192-168-99-100:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

Info:  For client config context 'default/192-168-99-100:8443/system:admin':
       The server URL is 'https://192.168.99.100:8443'
       The user authentication is 'system:admin/127-0-0-1:8443'
       The current project is 'default'
       Successfully requested project list; has access to project(s):
         [default kube-public kube-system myproject openshift openshift-infra openshift-node]

[Note] Running diagnostic: ConfigContexts[lball1/console-starter-us-east-2-openshift-com:443/lball1@redhat.com]
       Description: Validate client config context is complete and has connectivity

Info:  For client config context 'lball1/console-starter-us-east-2-openshift-com:443/lball1@redhat.com':
       The server URL is 'https://console.starter-us-east-2.openshift.com:443'
       The user authentication is 'lball1@redhat.com/console-starter-us-east-2-openshift-com:443'
       The current project is 'lball1'
       Successfully requested project list; has access to project(s):
         [lball1 lball1-che lball1-jenkins lball1-run lball1-stage]

[Note] Running diagnostic: ConfigContexts[default/192-168-99-103:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0010 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'default/192-168-99-103:8443/system:admin':
       The server URL is 'https://192.168.99.103:8443'
       The user authentication is 'system:admin/127-0-0-1:8443'
       The current project is 'default'
       (*url.Error) Get https://192.168.99.103:8443/apis/project.openshift.io/v1/projects: dial tcp 192.168.99.103:8443: i/o timeout

       This means that when we tried to connect to the master API server,
       we could not reach the host at all.
       * You may have specified the wrong host address.
       * This could mean the host is completely unavailable (down).
       * This could indicate a routing problem or a firewall that simply
         drops requests rather than responding by resetting the connection.
       * It does not generally mean that DNS name resolution failed (which
         would be a different error) though the problem could be that it
         gave the wrong address.

[Note] Running diagnostic: ConfigContexts[default/192-168-99-101:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0010 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'default/192-168-99-101:8443/system:admin':
       The server URL is 'https://192.168.99.101:8443'
       The user authentication is 'system:admin/127-0-0-1:8443'
       The current project is 'default'
       (*url.Error) Get https://192.168.99.101:8443/apis/project.openshift.io/v1/projects: dial tcp 192.168.99.101:8443: i/o timeout

       This means that when we tried to connect to the master API server,
       we could not reach the host at all.
       * You may have specified the wrong host address.
       * This could mean the host is completely unavailable (down).
       * This could indicate a routing problem or a firewall that simply
         drops requests rather than responding by resetting the connection.
       * It does not generally mean that DNS name resolution failed (which
         would be a different error) though the problem could be that it
         gave the wrong address.

[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint

Info:  Output from the diagnostic pod (image openshift/origin-deployer:v3.7.0):
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected

       Info:  Service account token successfully authenticated to master
       Info:  Service account token was authenticated by the integrated registry.

       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected

       [Note] Summary of diagnostics execution (version v3.7.0+7ed6862):
       [Note] Completed with no errors or warnings seen.

[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint

ERROR: [DNet2001 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:84]
       Checking network plugin failed. Error: User "developer" cannot get clusternetworks.network.openshift.io at the cluster scope: User "developer" cannot get clusternetworks.network.openshift.io at the cluster scope (get clusternetworks.network.openshift.io default)

[Note] Summary of diagnostics execution (version v3.7.0+7ed6862):
</pre></code>
</details>

**Comment by php-coder** [comment]
@openshift/sig-user-interface @openshift/sig-developer-experience

**Comment by bparees** [comment]
You may need to import it in the openshift namespace. Not sure. @spadgett @jwforres

**Comment by coreydaley** [comment]
I believe @bparees is correct, I ran into this same issue before and it was because I was importing it into my own namespace instead of the openshift namespace.

**Comment by jim-minter** [comment]
I'd have expected you to run `oc create -n openshift -f image-streams.centos7.json` (not `oc import`).  Does that work?

**Comment by lance** [comment]
@jim-minter @bparees @coreydaley yes, this did work. Thank you. Here are the steps I took.

```sh
$ oc login -u system:admin -n openshift --config=~/.kube/config
Logged into "https://192.168.99.100:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
    myproject
  * openshift
    openshift-infra
    openshift-node

Using project "openshift".
$ oc create -n openshift -f image-streams.centos7.json
imagestream "centos7-s2i-nodejs" created
$
```

I read through the [docs](https://docs.openshift.com/container-platform/3.7/dev_guide/managing_images.html#writing-image-streams-for-s2i-builders) again, and there is no guidance regarding these commands. Is there some place else in the documentation where this is discussed?

**Comment by lance** [comment]
One more quick question about this. Previously it was possible for non-admin accounts to import/create these builder image streams in the catalog for their accounts only. Is this no longer possible?

**Comment by bparees** [comment]
> I read through the docs again, and there is no guidance regarding these commands. Is there some place else in the documentation where this is discussed?

Likely not.  But at one point I thought valid imagestreams that existed in your current project would be shown to you (much like templates in your current project used to be shown to you).  So i'd like confirmation from @jwforres or @spadgett that this behavior is expected before we document that you must create your imagestream in the "openshift" namespace to see it in the console as a builder image.

> One more quick question about this. Previously it was possible for non-admin accounts to import/create these builder image streams in the catalog for their accounts only. Is this no longer possible?

Normal users can definitely create the imagestreams in your own project and then use them (define a buildconfig that references them, or use oc new-app to reference them).  But again if they used to show up in the web console, then that is a change in behavior that @spadgett and @jwforres will have to comment on.

**Comment by spadgett** [comment]
https://github.com/openshift/origin-web-console/pull/2563 will let you see builder images in your own project in 3.9 as long as they're properly annotated as builders. If you use Add to Project -> Browse Catalog from within the project that has the builder, it'll show up in the catalog.

**Comment by jwforres** [comment]
@lance does that answer all your questions? can this be closed now?

**Comment by lance** [comment]
@spadgett when you say "properly annotated as builders", does that mean something different than what is described in this [documentation](https://docs.openshift.com/container-platform/3.6/dev_guide/managing_images.html#writing-image-streams-for-s2i-builders)?

**Comment by jwforres** [comment]
@lance it needs to have the "builder" tag on it as shown in bullet 7 in that doc

**Comment by lance** [comment]
@jwforres ok thanks. I think that covers it then. I'll go ahead and close this.
