### ISSUE TITLE
Console Overview doesn't scale well with >8 replicas

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#1790]
When adding some larger number of replicas (screenshot has 14) the pods push off the screen and cause the service/deployment to be pushed off.

osc v0.4.3-208-g4ea9dfc
kubernetes v0.14.1-582-gb12d75d

![many-replicas](https://cloud.githubusercontent.com/assets/727196/7206832/4cbdf3c4-e503-11e4-95f3-933223e70ca0.png)

/cc @jwforres @liggitt

**Comment by smarterclayton** [comment]
We should be collapsing at >5 probably

**Comment by jwforres** [comment]
Will address this as part of the overview re-theme work this sprint.

**Comment by liggitt** [comment]
should be wrapping now, will scale layout separately
