### ISSUE TITLE
Console Overview not showing proper ports for routes

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#1791]
I have a simple node app which routes 8080 to 3000, the console overview seems to be missing some of the port information (see screenshot) and the service port is not correct one (should be 3000 instead of 8080)

The app I used is:

    osc new-app https://github.com/sspeiche/node-echo.git

I did use `-o json` and modified the config to map port 3000.

![console-ports](https://cloud.githubusercontent.com/assets/727196/7207023/52ea543a-e504-11e4-884d-47d46a62ee30.png)

/cc @jwforres @liggitt

**Comment by jwforres** [comment]
Looks like this is a result of the multi-port services changes.  Needs to be fixed in https://github.com/kubernetes-ui/object-describer as well

**Comment by jwforres** [comment]
The Browse -> Services page also needs an update.

**Comment by rhcarvalho** [comment]
Screenshot of the Browse -> Services page:

![screenshot from 2015-04-23 11 06 14](https://cloud.githubusercontent.com/assets/88819/7294271/caee7c4e-e9ab-11e4-9fdd-f60b01e803c2.png)

**Comment by sudksing** [comment]
Edit the Service YAML file as mentioned in image below;
![image](https://user-images.githubusercontent.com/25577192/42052407-58226a3e-7b2c-11e8-9976-808219202066.png)
