### ISSUE TITLE
TestValidatePersistentVolumeClaimUpdate unit test flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#17911]
```
validation_test.go:1428: Unexpected failure for scenario: valid-size-update-resize-enabled - [spec: Forbidden: is immutable after creation except resources.requests for bound claims]
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17314/test_pull_request_origin_unit/7268/

**Comment by deads2k** [comment]
@bparees we merged https://github.com/openshift/origin/pull/17876 to fix it.  I think it was after your run.
