### ISSUE TITLE
open shift configuration

### ISSUE THREAD

**Issue by fmontaldo** [openshift/origin#17919]
##### Version
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8

##### Steps To Reproduce
1. I made the following /etc/ansible/hosts
```ini
[OSEv3:children]
masters
nodes
nfs
etcd

[masters]
master.xxxxx openshift_schedulable=true containerized=false

[nfs]
master.xxxxx

[etcd]
master.dev.nps.com

[nodes]
master.xxxxxx openshift_node_labels="{'region': 'infra', 'zone': 'infra'}"
node01.xxxxxxx openshift_node_labels="{'region': 'primary', 'zone': 'infra'}" openshift_schedulable=true
node02.xxxxxx openshift_node_labels="{'region': 'primary', 'zone': 'infra'}" openshift_schedulable=true

[OSEv3:vars]
ansible_user=openshift
ansible_ssh_user=origin
ansible_become=yes

enable_excluders=false
enable_docker_excluder=false

containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

openshift_node_kubelet_args={'pods-per-core': ['10']}

deployment_type=origin
openshift_deployment_type=origin

openshift_release=v3.7.0
openshift_pkg_version=v3.7.0
openshift_image_tag=v3.7.0

# Required for Service Catalog
openshift_hosted_etcd_storage_kind=nfs
openshift_hosted_etcd_storage_nfs_options="*(rw,root_squash,sync,no_wdelay)"
openshift_hosted_etcd_storage_nfs_directory=/opt/osev3-etcd
openshift_hosted_etcd_storage_volume_name=broker-ansible-etcd
openshift_hosted_etcd_storage_access_modes=["ReadWriteOnce"]
openshift_hosted_etcd_storage_volume_size=1G
openshift_hosted_etcd_storage_labels={'storage': 'etcd'}

osm_use_cockpit=true

openshift_metrics_install_metrics=True

openshift_logging_install_logging=True
openshift_logging_image_version=v3.7

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

openshift_public_hostname=master.xxxx
openshift_master_default_subdomain=apps.xxxxx
```

##### Current Result
I made the odm diagnostics
```
ERROR: [DNet2008 from diagnostic NetworkCheck@openshift/origin/pkg/diagnostics/network/run_pod.go:154]
       [Logs for network diagnostic pod on node "master.dev.nps.com" failed: container "network-diag-pod-f5jvj" in pod "network-diag-pod-f5jvj" is not available, Logs for network diagnostic pod on node "node02.dev.nps.com" failed: container "network-diag-pod-lcqdj" in pod "network-diag-pod-lcqdj" is not available, Logs for network diagnostic pod on node "node01.xxxxx" failed: container "network-diag-pod-m2qzz" in pod "network-diag-pod-m2qzz" is not available]

ERROR: [AGL0095 from diagnostic AggregatedLogging@openshift/origin/pkg/diagnostics/cluster/aggregated_logging/diagnostic.go:128]
       There were no Pods found for DeploymentConfig 'logging-es-data-master-arxmfuqd'.  Try running
       the following commands for additional information:

         $ oc describe dc logging-es-data-master-arxmfuqd -n logging
         $ oc get events -n logging

ERROR: [AGL0225 from diagnostic AggregatedLogging@openshift/origin/pkg/diagnostics/cluster/aggregated_logging/diagnostic.go:128]
       There are no endpoints found for service 'logging-es'. This means that no pods provide this service and this component is not functioning.

ERROR: [AGL0225 from diagnostic AggregatedLogging@openshift/origin/pkg/diagnostics/cluster/aggregated_logging/diagnostic.go:128]
       There are no endpoints found for service 'logging-es-cluster'. This means that no pods provide this service and this component is not functioning.
```
##### Expected Result
log in as admin but I do not have the permitions

##### Additional Information

I made the dnsmasq configuration.

-Install pacakges: dnsmasq and bind utils
-Add the following entries to /etc/dnsmasq.conf
	- address=/master.xxxx/ip
	-resolv.file=/etc/resolv.conf
	
Create /etc/resolv.dnsmasq with the following:
	- nameserver <GATEWAY IP>

**Comment by fmontaldo** [comment]
I am new on this and I don't know the way to diagnose the errors. Thanks in advance.

**Comment by php-coder** [comment]
@fmontaldo To make it clear, what is the issue? You can't login as admin? Could you post the output of the `oc login` command with `--loglevel=8` parameter?

**Comment by fmontaldo** [comment]
Hi,

I made this installation.

Three server

master
node01
node02

•	Master node has up to 16G memory.
•	On all nodes, free space on physical volume is required to create a new volume group for Docker Direct LVM.
•	The /var partition need to have 40 GB of space

Each of the nodes got the same configuration.

On All Nodes, Create a user for installation to be used in Ansible and also grant root privileges to him.

useradd origin
passwd origin
echo -e 'Defaults:origin !requiretty\norigin ALL = (root) NOPASSWD:ALL' | tee /etc/sudoers.d/openshift
chmod 440 /etc/sudoers.d/openshift

On All Nodes, install OpenShift Origin 3.7 repository and Docker. Next, create a volume group for Docker Direct LVM to setup LVM Thinpool like follows.

yum -y install docker-1.12.6

Add --insecure-registry 172.30.0.0/16 to /etc/sysconfig/docker.

Edit the following line:

OPTIONS='--selinux-enabled --insecure-registry 172.30.0.0/16 --log-driver=journald --signature-verification=false'

If enabled, disable the LVM cluster feature.

lvmconf --disable-cluster
Edit docker-storage-setup to use storage mounted on /dev/[x]vdb, then complete the installation using the proper command-line tools.
cat /etc/sysconfig/docker-storage-setup
DEVS=/dev/sdb
VG=docker-vg
docker-storage-setup
INFO: Device node /dev/sdb1 exists.
  Physical volume "/dev/sdb1" successfully created.
  Volume group "docker-vg" successfully created
ERROR: Docker has been previously configured for use with devicemapper graph driver. Not creating a new thin pool as existing docker metadata will fail to work with it. Manual cleanup is required before this will succeed.
INFO: Docker state can be reset by stopping docker and by removing /var/lib/docker directory. This will destroy existing docker images and containers and all the docker metadata.
Create a systemd drop-in directory for the docker service:

mkdir -p /etc/systemd/system/docker.service.d

Create a file called 

/etc/systemd/system/docker.service.d/http-proxy.conf

That adds the HTTP_PROXY environment variable:

cat /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://xx.x.xx.xx:3128/"

Restart the service daemon and reload the service 

rm -rf /var/lib/docker/*
systemctl daemon-reload
systemctl enable docker && systemctl restart dokcer

Verify the paramenters

systemctl show --property=Environment docker
Environment=GOTRACEBACK=crash DOCKER_HTTP_HOST_COMPAT=1 PATH=/usr/libexec/docker:/usr/bin:/usr/sbin HTTP_PROXY=http://xx.xx.xx.xx:3128/

vgs
  VG        #PV #LV #SN Attr   VSize    VFree
  docker-vg   1   1   0 wz--n- <100.00g 60.00g
  vg_root     1  10   0 wz--n-  <89.52g  8.00m

On Master Node, login with a user created above and set SSH keypair with no pass-phrase.

su – origin
ssh-keygen -q -N "" 
Enter file in which to save the key (/home/origin/.ssh/id_rsa):

vi ~/.ssh/config

# create new ( define nodes )
Host master
    Hostname master
    User origin
Host node01
    Hostname node01
    User origin
Host node02
    Hostname node02
    User origin

chmod 600 ~/.ssh/config

on each host I isntalled bind-utils and dnsmasq.

I made the follwing confgiuration for DNS resolution. 

Instalation master and nodes

-Install pacakges: dnsmasq and bind utils
-Add the following entries to /etc/dnsmasq.conf
	- address=/master.xxxx/ip
	-resolv.file=/etc/resolv.conf
	
Create /etc/resolv.dnsmasq witht he follwoing:
	- nameserver <GATEWAY IP>

I pull the openshfit docker images as origin user

sudo docker pull openshift/origin
sudo docker pull cockpit/kubernetes
sudo docker pull openshift/origin-deployer:v3.7.0
sudo docker pull openshift/origin-docker-registry:v3.7.0
sudo docker pull openshift/origin-haproxy-router:v3.7.0
sudo docker pull openshift/origin-pod:v3.7.0

Create the file that will hold the httpd passwords

mkdir –p /etc/origin/master/

touch /etc/origin/master/htpasswd

Then I made the following ansible host file

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=origin
ansible_become=true
openshift_deployment_type=origin

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
openshift_master_default_subdomain=apps.dev.nps.com

openshift_docker_insecure_registries=172.30.0.0/16

[masters]
master.dev.nps.com openshift_schedulable=true containerized=false

[etcd]
master

[nodes]
masteropenshift_node_labels="{'region': 'infra', 'zone': 'infra'}"
node01openshift_node_labels="{'region': 'primary', 'zone': 'infra'}" openshift_schedulable=true
node02 openshift_node_labels="{'region': 'primary', 'zone': 'infra'}" openshift_schedulable=true

After configuration the oadm diagnostics shows me the following

ERROR: [DCli0013 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'default/master-dev-nps-com:8443/admin':
       The server URL is 'https://master.dev.nps.com:8443'
       The user authentication is 'admin/master-dev-nps-com:8443'
       The current project is 'default'
       (*errors.StatusError) User "system:anonymous" cannot list projects.project.openshift.io at the cluster scope: User "system:anonymous" cannot list all projects.project.openshift.io in the cluster (get projects.project.openshift.io)

       This means that when we tried to make a request to the master API
       server, your kubeconfig did not present valid credentials to
       authenticate your client. Credentials generally consist of a client
       key/certificate or an access token. Your kubeconfig may not have
       presented any, or they may be invalid.

How Can I resolve that I already ecport eh variable for KUBECONFIG for the user origin.
