### ISSUE TITLE
cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp: lookup accounts.google.com

### ISSUE THREAD

**Issue by adawolfs** [openshift/origin#17923]
Hello I'm configuring an Openshift Cluster but I had this error, I cant connect my instance to the cloudsql database, the same configuration is used for GKE and its working, and if mount the instance over minishift it worked, can you please help me to know what is happening here?

  | 2017/12/21 20:44:45 Listening on 127.0.0.1:3306 for myinstance:europe-west1:cloudsql-dev-1
  | 2017/12/21 20:44:45 Ready for new connections
  | 2017/12/21 20:44:47 New connection for "myinstance:europe-west1:cloudsql-dev-1"
  | 2017/12/21 20:44:47 couldn't connect to "myinstance:europe-west1:cloudsql-dev-1": Post https://www.googleapis.com/sql/v1beta4/projects/myinstance/instances/cloudsql-dev-1/createEphemeral?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp: lookup accounts.google.com on 138.201.198.48:53: server misbehaving

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

**Comment by php-coder** [comment]
Looks like DNS issue.
Could be the same as https://github.com/kubernetes/kubernetes/issues/39980

**Comment by php-coder** [comment]
@openshift/sig-networking

**Comment by adawolfs** [comment]
I have been noticed that my containers cant resolve internet domains I'm able to handle it just after configure 8.8.8.8 as nameserver in /etc/resolv.conf by default it uses the node IP as nameserver, if I try to ping some domain from the node it resolves, any idea?

**Comment by adawolfs** [comment]
After see this 
https://developers.redhat.com/blog/2015/11/19/dns-your-openshift-v3-cluster/

I and check over the nodes I've found that dnsmasq is up and running so I've added this lines to the **/etc/dnsmasq.conf**
```
server=8.8.8.8
server=8.8.4.4
```
