### ISSUE TITLE
TestRouter flakiness

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#17924]
```
=== RUN   TestRouter
--- FAIL: TestRouter (0.00s)
	router_test.go:1416: Error validating master addr 172.18.15.1:8080 : Get https://172.18.15.1:8443: dial tcp 172.18.15.1:8443: getsockopt: connection refused
	router_test.go:62: Unable to start http server: tls: failed to find any PEM data in certificate input
=== RUN   TestRouterPathSpecificity
--- FAIL: TestRouterPathSpecificity (0.00s)
	router_test.go:393: Unable to start http server: tls: failed to find any PEM data in certificate input
=== RUN   TestRouterDuplications
--- FAIL: TestRouterDuplications (0.00s)
	router_test.go:752: Unable to start http server: listen tcp 172.18.15.1:8080: bind: address already in use
=== RUN   TestRouterStatsPort
--- FAIL: TestRouterStatsPort (0.00s)
	router_test.go:884: Unable to start http server: listen tcp 172.18.15.1:8080: bind: address already in use
=== RUN   TestRouterHealthzEndpoint
--- FAIL: TestRouterHealthzEndpoint (0.00s)
	router_test.go:937: Unable to start http server: listen tcp 172.18.15.1:8080: bind: address already in use
=== RUN   TestRouterServiceUnavailable
--- FAIL: TestRouterServiceUnavailable (0.00s)
	router_test.go:975: Unable to start http server: listen tcp 172.18.15.1:8080: bind: address already in use
=== RUN   TestRouterReloadCoalesce
--- FAIL: TestRouterReloadCoalesce (0.00s)
	router_test.go:1416: Error validating master addr 172.18.15.1:8080 : Get https://172.18.15.1:8443: dial tcp 172.18.15.1:8443: getsockopt: connection refused
	router_test.go:1525: Unable to start http server: listen tcp 172.18.15.1:8080: bind: address already in use
=== RUN   TestRouterBindsPortsAfterSync
--- FAIL: TestRouterBindsPortsAfterSync (3.46s)
	router_test.go:1416: Error validating master addr 172.18.15.1:8080 : Get https://172.18.15.1:8443: dial tcp 172.18.15.1:8443: getsockopt: connection refused
	router_test.go:1674: Unable to start http server: listen tcp 172.18.15.1:8080: bind: address already in use
=== RUN   TestIngressConfiguredRouter
--- FAIL: TestIngressConfiguredRouter (0.00s)
	router_test.go:1416: Error validating master addr 172.18.15.1:8080 : Get https://172.18.15.1:8443: dial tcp 172.18.15.1:8443: getsockopt: connection refused
	router_test.go:1721: Unable to start http server: listen tcp 172.18.15.1:8080: bind: address already in use
```
Seen in https://github.com/openshift/origin/pull/17868, https://github.com/openshift/origin/pull/17860

Logs:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/17868/test_pull_request_origin_end_to_end/7174/build-log.txt, https://storage.googleapis.com/origin-ci-test/pr-logs/pull/17860/test_pull_request_origin_end_to_end/7145/build-log.txt

@openshift/sig-networking

**Comment by tnozicka** [comment]
also on release-3.7 https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17620/test_pull_request_origin_end_to_end/7355/

**Comment by tnozicka** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17599/test_pull_request_origin_end_to_end/7339/

blocks release-3.7 branch

**Comment by tnozicka** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17620/test_pull_request_origin_end_to_end/7360/

**Comment by tnozicka** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17599/test_pull_request_origin_end_to_end/7361/

**Comment by tnozicka** [comment]
@stevekuznetsov can this be test-infra related?

**Comment by enj** [comment]
> blocks release-3.7 branch

I have seen this as well: https://openshift-gce-devel.appspot.com/pr/17789

**Comment by sjenning** [comment]
My PR on the 3.8 branch is hitting this on _every_ run
https://openshift-gce-devel.appspot.com/pr/17839

**Comment by sjenning** [comment]
Same on a 3.7 PR (merged manually):
https://openshift-gce-devel.appspot.com/pr/17722

**Comment by stevekuznetsov** [comment]
If it's hitting 3.7 and 3.8 I would expect this to be a Go version issue. We have not had the possibility of testing non-`master` Origin PRs with different versions of Go ever in the past, so I would expect those tests to simply be broken. I would suggest testing locally and merging manually for now. We anticipate better support in the future.

**Comment by pravisankar** [comment]
Fixed by https://github.com/openshift/origin/pull/17989
