### ISSUE TITLE
openshift_version cannot be determined after move to foreman/katello repositories

### ISSUE THREAD

**Issue by ybaumy** [openshift/origin#17937]
i am currently working on automatically installing an openshift cluster via foreman/katello. katello is the repository management plugin for foreman.
since i added my cluster nodes as clients to katello and they get their repos from there. i can no longer install the playbooks.

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. add nodes to katello 3.5 server
2. create repos for openshift 3.7
3. attach those to the nodes
4. run playbook eg.
ansible-playbook -i inventory/hosts playbooks/deploy_cluster.yml

##### Current Result

here is my inventory file:

```ini
[OSEv3:children]
masters
nodes
etcd
lb

[OSEv3:vars]
ansible_ssh_user=root
ansible_become=true
debug_level=2
openshift_deployment_type=origin
openshift_master_default_subdomain=ocp.vdc1-ext.local

openshift_management_storage_class=nfs_external
openshift_management_storage_nfs_external_hostname=qnap4.inside.local
openshift_management_storage_nfs_base_dir=/ocpshare

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

openshift_master_cluster_method=native
openshift_public_hostname=ocp-lb-1.vdc1-ext.local
openshift_master_cluster_hostname=ocp-lb-1.vdc1-ext.local
openshift_master_cluster_public_hostname=ocp-lb-1.vdc1-ext.local
openshift_node_kubelet_args={'pods-per-core': ['10'], 'max-pods': ['250'], 'image-gc-high-threshold': ['90'], 'image-gc-low-threshold': ['80']}
openshift_clock_enabled=true

openshift_enable_service_catalog=true
openshift_service_catalog_image_prefix=openshift/origin-
openshift_service_catalog_image_version=latest
ansible_service_broker_registry_user=<user>
ansible_service_broker_registry_password=<pass>
ansible_service_broker_registry_organization="qscag"

[masters]
ocp-master-1.vdc1-ext.local openshift_hostname=ocp-master-1.vdc1-ext.local
ocp-master-2.vdc1-ext.local openshift_hostname=ocp-master-2.vdc1-ext.local
ocp-master-3.vdc1-ext.local openshift_hostname=ocp-master-3.vdc1-ext.local

[etcd]
ocp-etcd-1.vdc1-ext.local
ocp-etcd-2.vdc1-ext.local
ocp-etcd-3.vdc1-ext.local

[lb]
ocp-lb-1.vdc1-ext.local

[nodes]
ocp-master-[1:3].vdc1-ext.local openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
ocp-worker-1.vdc1-ext.local openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
ocp-worker-2.vdc1-ext.local openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
ocp-worker-3.vdc1-ext.local openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
```

and here is the error

[https://paste.ubuntu.com/26264627/](https://paste.ubuntu.com/26264627/)

this is how yum repolist looks like on a client

[https://paste.ubuntu.com/26264692/](https://paste.ubuntu.com/26264692/)

##### Expected Result

that the check for the version passes.

**Comment by php-coder** [comment]
Look like an issue in the openshift-ansible, so it's better to fill the issue there, but as far I can see, the issue already exist: https://github.com/openshift/openshift-ansible/issues/6560 and https://github.com/openshift/openshift-ansible/issues/6568

CC @sdodson

**Comment by sdodson** [comment]
@ybaumy can you confirm that the hosts have /usr/bin/repoquery from the yum-utils package? I suspect we just don't have that installed and you can work around this by ensuring that it's installed on all hosts prior to running openshift-ansible.

If it's installed then we likely need to fix a bug in our repoquery module, can you provide the output of 
`/usr/bin/repoquery --quiet --pkgnarrow=repos --queryformat=%{version}|%{release}|%{arch}|%{repo}|%{version}-%{release} --show-duplicates origin`

/assign kwoodson vrutkovs
