### ISSUE TITLE
Setting docker storage openshift

### ISSUE THREAD

**Issue by i-prakasa** [openshift/origin#17930]
I tried to install openshift. But I stuck on this part.

https://docs.openshift.com/container-platform/3.6/install_config/install/host_preparation.html#configuring-docker-storage
I tried use option A,
My partition disk like this:

```console
[root@~]# lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda             8:0    0 465.8G  0 disk
└sda1          8:1    0     1G  0 part /boot
└sda2          8:2    0   441G  0 part
 └rhel-root  253:0    0   100G  0 lvm  /
   └rhel-swap 253:1    0   5.8G  0 lvm  [SWAP]
   └rhel-home 253:2    0 195.6G  0 lvm  /home
   └rhel-sdb  253:3    0  93.1G  0 lvm  /sdb
   └rhel-vdc  253:4    0  46.6G  0 lvm  /run/media/root/3f71e934-a805-415e-9491-
sr0            11:0    1  1024M  0 rom
```
Then I set docker setup like this:
```console
[root@master ~]# vim /etc/sysconfig/docker-storage-setup
DEVS=sda2/rhel-sdb
VG=rhel
```
But when run docker-storage-setup I got this error.
```console
[root@master ~]# docker-storage-setup
ERROR: /dev/sda2/rhel-sdb is not a valid block device.
```
Why not valid?
In fact I have that partition.
Anyone can help?

**Comment by php-coder** [comment]
It looks like an issue in the documentation: https://bugzilla.redhat.com/show_bug.cgi?id=1436369

CC @vikram-redhat
