### ISSUE TITLE
Occasional bad permissions

### ISSUE THREAD

**Issue by eivantsov** [openshift/origin#17933]
Occasionally when deploying apps, I can see that directories mounted by PVCs have bad permissions. For example, when deploying Eclipse Che Multi-User, we deploy Postgres, Keycloak and Che itself. Sometimes, we see errors when [PSQL] (https://github.com/eclipse/che/tree/master/dockerfiles/init/modules/openshift/files/scripts/multi-user/postgres) is initialized:

```
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```
The same may happen when Keycloak or Che starts.

##### Version

```
eugene@ivantsoft ~ $ oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.codenvy.openshift.com:443
openshift v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
```

However, same glitches are observed with 3.7 too.

The only thing that helps is `oc cluster down` and removing all PVs. Sometimes, just deleting a namespace solves the issue.

Is there a way I can debug bad PVCs when it happens again?

**Comment by php-coder** [comment]
Does it happen always on the same namespace? What PostgreSQL image are you using (is it official from dockerhub or it's https://github.com/sclorg/postgresql-container or something else)?

I suspect that it could be related to SCC: if a pod is being admitted by `restricted` SCC, it will get dynamically allocated UID. So, it's possible that in the different runs, a pod has different UIDs.

**Comment by eivantsov** [comment]
@php-coder thanks for your reply

We use s2i strategy for Postgres and Keycloak images (to provide our own config that is customized before being used), but that is not the point here I think.

Yes, it looks like when a PV is being re-used it has bad permissions. Yes, we run OpenShift with a dynamically allocated UID - this is the default I think.

Can you tell what can go wrong in this sequence?

1. I run a successful deployment. A PVC is assigned to a PV.
2. I remove the namespace, including the PVC.
3. I try to deploy again, by creating the same namespace and deployment there.
4. I run into this sort of permission denied issue - in any deployment - postgres, keycloak, tomcat.

Only recreating a cluster helps. Not sure if it's relevant here, but we use a recycler pod https://kubernetes.io/docs/concepts/storage/persistent-volumes/#recycling

**Comment by php-coder** [comment]
Yes, you have this issue because you're re-creating namespaces. Every namespace has annotation openshift.io/sa.scc.uid-range that contains a range of uids that will be used by the pods in this namespace. When you create a new namespace you have a different range and hence a different UID.

Typically we're using groups and make all the files writable for a group, so they don't depend on the UID. But supplemental groups behave in the same way, they use openshift.io/sa.scc.supplemental-groups annotation.

If you can't modify your workflow to not use different namespaces, I think that the only way is to use a fixed UID/GID. In this case, a pod should specify uid/gid in its manifest and you should grant appropriate permissions to a user/service account to use SCC that allows arbitrary uids/gids.

@bparees Perhaps, you know a better way?

**Comment by eivantsov** [comment]
@php-coder thanks - yes, we suspected smth like that. And we do handle such situations in other scenarios by setting write permissions for a group for directories we're particularly interested in. However, we cannot do so in certain cases, for example when using official images.

Anyway, thanks for shedding some light on the problem. It's more or less clear what workarounds are worth trying now.

**Comment by bparees** [comment]
@php-coder it sounds to me like the PVs are not being recycled properly.  When the PV is assigned to a new pod (whether in a new namespace or not), it should not have any content from the prior usage, thus prior permissions should be irrelevant.  

If there's something oc cluster up needs to configure to ensure the PVs are properly recycled, then we'll need guidance from the storage team on that.  assigning to @childsb

**Comment by php-coder** [comment]
> it should not have any content from the prior usage, thus prior permissions should be irrelevant.

I agree it could be leftovers from the previous run. I had another theory where PV is empty but has a different owner.

@bparees Thank you!

**Comment by eivantsov** [comment]
@php-coder @bparees I'll make sure I'll check the PV when permission denied happens again to see if the PV has wrong permissions or it has leftovers from previous runs.

Maybe there are clues in OpenShift events - the ones related to recycler pod.
