### ISSUE TITLE
Deployment stuck on waiting for image update at ImageStreamTag

### ISSUE THREAD

**Issue by FromZeus** [openshift/origin#17938]
Deployment stuck on waiting for image update at ImageStreamTag

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.244:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. `oc new-project test`
2. Login to openshift registry
3. `docker pull python:3.5-alpine`
    `docker pull rabbitmq:3.6.12-alpine`
    `docker tag python:3.5-alpine $(minishift openshift registry)/test/python:3.5-alpine`
    `docker tag rabbitmq:3.6.12-alpine $(minishift openshift registry)/test/rabbitmq:3.6.12-alpine`
    `docker push $(minishift openshift registry)/test/python:3.5-alpine`
    `docker push $(minishift openshift registry)/test/rabbitmq:3.6.12-alpine`
4. Clone my test repo and checout to `feature/openshift` branch.
    `git clone https://github.com/FromZeus/drweb.git`
5. Try to deploy application from it
    `oc new-app openshift/templates/template-mystack.yml`

##### Current Result
Hangs on `A new deployment will start automatically when an image is pushed to test/mystack:latest`
Image pushes to registry successfully. It could be pulled from there: `docker pull 172.30.1.1:5000/test/mystack`, also there are correct ImageStream and ImageStreamTag.

##### Expected Result
Deployment continues without hanging.

##### Additional Information
Files attached
[get-all.log](https://github.com/openshift/origin/files/1589175/get-all.log)
[diagnostic.log](https://github.com/openshift/origin/files/1589176/diagnostic.log)

**Comment by mfojtik** [comment]
@tnozicka seems like the trigger should trigger as the ImageStreamTag 'latest' is present.

**Comment by FromZeus** [comment]
Still an issue in v3.10.0 release. /reopen
