### ISSUE TITLE
Very slow for installing openshift

### ISSUE THREAD

**Issue by lanliu99** [openshift/origin#17946]
When using advanced installation with ansible to install openshift 3.7 on RHEL7.3, process is very slow.
##### Version
in /etc/ansible/hosts:
openshift_service_catalog_image_version=v3.7

##### Steps To Reproduce
1. [step 1]
Config hosts for disconnected installation according to 
https://access.redhat.com/documentation/en-us/openshift_container_platform/3.7/html-single/installation_and_configuration/#install-config-install-disconnected-install
2. [step 2]
ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/$component/config.yml
for example: 
ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-master/config.yml

##### Current Result
The components can be installed with no error, but takes about 3 hours.
For other components, it took from half hour to 3 hours differently.

##### Expected Result
The component should be installed within reasonable time.

##### Additional Information
During the installation, I disconnected connection from internet, no error happened, it should verify the installation was using local yum and image hub.

I am using guest RHEL7.3 virbuebox on a host runing win10 professional, configuration info:
win10 pro: I5, 16G, SSD
virtuebox 5.2 on win10
RHEL7.3 run as guest on win10, 1 vm for master, 1 vm for node, each vm is 1 cpu/2G mem.

During installation, monitoring vm resource by using vmstat, seldom CPU runs into zero free, in most of the time, CPU idle > 90%, memory and IO is ok too.
No resource thirsty observed on win10.
No dynamic resize of vdi file was observed.

Some others told me installing on 1Master + 2Nodes with ansible should be finished in about 1 hour.
What's the possible reason for this and how to trace this issue?

**Comment by php-coder** [comment]
Looks like it's related to ansible installer and it's better to create it there: https://github.com/openshift/openshift-ansible

CC @sdodson

**Comment by lanliu99** [comment]
Hi, Coder,

That works for me.

Best regards

Lan

**Comment by lanliu99** [comment]
After using the latest playbook yml file, issue was solved.
