### ISSUE TITLE
Openshift Pods reporting AGE<invalid>

### ISSUE THREAD

**Issue by subodhp** [openshift/origin#17949]
The Openshift Origin 3.7 on RHEL 7.4 reporting Registry/Registry-Console/Router pods ages as <invalid> in "oc get pods".

openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

[root@myadmin ~]# oc get pods --all-namespaces=true
NAMESPACE   NAME                       READY     STATUS    RESTARTS   AGE
default     docker-registry-1-j4rds    1/1       Running   0          <invalid>
default     registry-console-3-g6qq4   1/1       Running   0          <invalid>
default     router-2-dsrcf             1/1       Running   0          <invalid>
[root@myadmin ~]#

Please suggest.

Thanks,
Subodh Pachghare

**Comment by juanvallejo** [comment]
Hi @subodhp any chance you are still able to replicate this?
If so, could you post the value of the `creationTimestamp` field for at least one of your pods?

e.g.
```
$ oc get pods docker-registry-1-j4rds -n default --template='{{ .metadata.creationTimestamp  }}'
``
