### ISSUE TITLE
couldn't get resource list for servicecatalog - crashes controllers

### ISSUE THREAD

**Issue by megian** [openshift/origin#17940]
The unavailability of the servicecatalog crashes loops all OpenShift controllers and does result in a complet cluster outage. After removing the servicecatalog api, everything went back to green.

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server
openshift v3.9.0-alpha.0+a0adcf4
kubernetes v1.8.1+0d5291c

##### Steps To Reproduce
1. Unavailability of the service catalog

##### Current Result
The active controller does stop/crash with the errors:

E1227 22:03:27.783022       1 memcache.go:159] couldn't get resource list for servicecatalog.k8s.io/v1beta1: an error on the server ("Error: 'dial tcp 172.30.188.31:443: getsockopt: no route to host'\nTrying to reach: 'https://172.30.188.31:443/apis/servicecatalog.k8s.io/v1beta1'") has prevented the request from succeeding
E1227 22:03:33.798096       1 controllermanager.go:486] Error starting "garbagecollector"
F1227 22:03:33.798144       1 controllermanager.go:158] error starting controllers: failed to get supported resources from server: unable to retrieve the complete list of server APIs: servicecatalog.k8s.io/v1beta1: an error on the server ("Error: 'dial tcp 172.30.188.31:443: getsockopt: no route to host'\nTrying to reach: 'https://172.30.188.31:443/apis/servicecatalog.k8s.io/v1beta1'") has prevented the request from succeeding

The next controller is getting the lease and is crashing too. And so on...

##### Expected Result
The controller should NEVER EVER crash, because of the unavailability of the service catalog api!

##### Additional Information
The issue stopped occur after removing the service catalog api:

oc delete apiservices.apiregistration.k8s.io/v1beta1.servicecatalog.k8s.io --ignore-not-found -n kube-service-catalog

**Comment by jwforres** [comment]
@openshift/sig-master I think this should have been triaged to you guys because this appears to be a problem with aggregated APIs

**Comment by liggitt** [comment]
tracked upstream in https://github.com/kubernetes/kubernetes/issues/55022, fixed in kube 1.9 and in master of origin
