### ISSUE TITLE
What is the standard logging convention for platform events?

### ISSUE THREAD

**Issue by raffian** [openshift/origin#17945]
oc v3.6.173.0.49
kubernetes v1.6.1+5115d708d7

General Question
============
We're using splunk to collect log data from `/var/log/messages`. and want to develop queries for detecting [platform events](https://docs.openshift.com/container-platform/3.6/dev_guide/events.html) as they occur, regardless of pod, node, container, etc, we want to collect everything. Some platform event names are sufficiently unique on which to query, such as `HostNetworkNotSupported`, `FreeDiskSpaceFailed`, etc., others are not:  `Failed`, `Pulled`, `Pulling`. Anyway, I started browsing our log files to make sure platform events as defined in the documentation correlated to event names in the physical logs,

```
Dec 28 10:54:16 someNode openshift-node MountVolume.SetUp succeeded
Dec 28 12:59:30 someNode dockerd-current:  level=info msg="containerd: 123:123 (pid 346) has become an orphan, killing it"
Dec 19 14:26:16 someNode openshift-node: kubelet_node_status.go:410] Recording NodeSchedulable event message for node dvdlosapp03.den.ofi.com
```

Not exactly what I had in mind; `NodeSchedulable` is a platform event, but the log entry before it is too generic; is that an actual "container killed" event?  I was hoping to find event entries in the log in this form:

```
myApp     Pod       failedValidation   {kubelet ose3-acme.example.com}   Error validating pod myApp...
```

At least with this type of log entry I can query on `Pod failedValidation`, ensuring that combo can only mean a pod failed validation. Perhaps I'm looking in the wrong place; is `/var/log/messages` not the correct location for collecting platform events?

**Comment by pweil-** [comment]
If you are trying to track all events I think what you may want to look into is the `observe` command.  That would allow you to watch for all events in the system and receive the event api object for processing rather than trying to scrape the log messages.  

Closing this as it is more of a general support question and should be directed to the mailing list or stack exchange.

**Comment by raffian** [comment]
I'm assuming the use of {{observe}} requires a Go implementation? If so, is there a simple example demonstrating its use? I've never programmed in Go

**Comment by pweil-** [comment]
It is a command available via the oc binary, you call out to a script you write yourself that can be a non-go implementation.

An example from the help docs of that command that uses shell scripts for some of the various options:

```
For example, you may wish to ensure that every node that is added to Kubernetes is added to your cluster inventory along
with its IP: 

  $ cat add_to_inventory.sh
  #!/bin/sh
  echo "$1 $2" >> inventory
  sort -u inventory -o inventory
  
  $ cat remove_from_inventory.sh
  #!/bin/sh
  grep -vE "^$1 " inventory > /tmp/newinventory
  mv -f /tmp/newinventory inventory
  
  $ cat known_nodes.sh
  #!/bin/sh
  touch inventory
  cut -f 1-1 -d ' ' inventory
  
  $ oc observe nodes -a '{ .status.addresses[0].address }' \
    --names ./known_nodes.sh \
    --delete ./remove_from_inventory.sh \
    -- ./add_to_inventory.sh
```

There is also an image published: https://hub.docker.com/r/openshift/observe/
