### ISSUE TITLE
skip_pv marker file doesn't work as expected for oc cluster up

### ISSUE THREAD

**Issue by praveenkumar** [openshift/origin#17948]
As per https://github.com/openshift/origin/pull/16631 a user can skip pv creation by adding marker file to pv directory.

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
```
$ mkdir -p /tmp/pv
$ touch /tmp/pv/.skip_pv
$ oc cluster up --host-pv-dir=/tmp/pv/
```

##### Current Result

It still create PVs.

##### Expected Result

It should skip creating PVs.

**Comment by LalatenduMohanty** [comment]
Can someone mark/pin it so that stale bot can not close it?
