### ISSUE TITLE
Verify heketi service fails, because of not matching glusterfs_heketi_admin_key

### ISSUE THREAD

**Issue by megian** [openshift/origin#17947]
If you run playbooks/deploy_cluster_glusterfs.yml multiple times, the deployment of deploy-heketi does still exists with another admin key. So the deployment of deploy-heketi must be always deleted or the playbook should get the key from the deployment.

A workaround is to add the task after "Delete pre-existing heketi resources" in roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml 

- name: Delete deploy-heketi resources
  oc_obj:
    namespace: "{{ glusterfs_namespace }}"
    kind: "{{ item.kind }}"
    name: "{{ item.name | default(omit) }}"
    selector: "{{ item.selector | default(omit) }}"
    state: absent
  with_items:
  - kind: "template,route,service,dc,jobs,secret"
    selector: "deploy-heketi"
  failed_when: False

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server
openshift v3.9.0-alpha.0+a0adcf4
kubernetes v1.8.1+0d5291c

##### Steps To Reproduce
1. ansible-playbook -i hosts playbooks/deploy_cluster_glusterfs.yml
2. restart it a second time

##### Current Result
TASK [openshift_storage_glusterfs : Verify heketi service] *************************************************************************************************************************
Thursday 28 December 2017  13:43:04 +0000 (0:00:00.577)       0:04:54.443 ***** 
fatal: [host1]: FAILED! => {"changed": false, "cmd": ["/usr/local/bin/oc", "rsh", "--namespace=glusterfs", "deploy-heketi-storage-1-kxpr7", "heketi-cli", "-s", "http://localhost:8080", "--user", "admin", "--secret", "8mpQ1ELFZUhKbEFAwHY8YjcZ5lwXu916ANDONh$5Sao=", "cluster", "list"], "delta": "0:00:01.463582", "end": "2017-12-28 14:43:06.949889", "msg": "non-zero return code", "rc": 255, "start": "2017-12-28 14:43:05.486307", "stderr": "Error: signature is invalid\ncommand terminated with exit code 255", "stderr_lines": ["Error: signature is invalid", "command terminated with exit code 255"], "stdout": "", "stdout_lines": []}

##### Expected Result
TASK [openshift_storage_glusterfs : Verify heketi service] *************************************************************************************************************************
Friday 29 December 2017  08:25:20 +0000 (0:00:00.764)       0:06:23.548 ******* 
ok: [host1]

**Comment by miminar** [comment]
I've just hit this and can confirm that running `oc delete -n default dc deploy-heketi-storage` followed by a new playbook run solved the issue for me.

**Comment by DanyC97** [comment]
@megian @miminar can you please close this issue and open a new on on openshift-ansible repo as that is the right location for this issue and not origin.

Tag me when you done and will see if can help out, thx

**Comment by bigon** [comment]
FTR I was hit by this too and I opened https://github.com/openshift/openshift-ansible/issues/9068

**Comment by patlachance** [comment]
A [bugzilla case](https://bugzilla.redhat.com/show_bug.cgi?id=1637105) referencing this issue was opened.
