### ISSUE TITLE
daemonset does not create pods until the controller is restarted

### ISSUE THREAD

**Issue by megian** [openshift/origin#17943]
TASK [openshift_storage_glusterfs : Wait for GlusterFS pods] ***********************************************************************************************************************
Thursday 28 December 2017  13:31:15 +0000 (0:00:46.481)       0:05:53.222 ***** 
FAILED - RETRYING: Wait for GlusterFS pods (30 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (29 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (28 retries left).
...
FAILED - RETRYING: Wait for GlusterFS pods (3 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (2 retries left).
FAILED - RETRYING: Wait for GlusterFS pods (1 retries left).

The storage pods are not created until the origin-master-controllers is restarted.

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server
openshift v3.9.0-alpha.0+a0adcf4
kubernetes v1.8.1+0d5291c

##### Steps To Reproduce
1. Create a daemonset

##### Current Result
oc describe daemonset glusterfs-storage
Name:		glusterfs-storage
Selector:	glusterfs=storage-pod
Node-Selector:	glusterfs=storage-host
Labels:		glusterfs=storage-daemonset
Annotations:	description=GlusterFS DaemonSet
		tags=glusterfs
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:	glusterfs=storage-pod
		glusterfs-node=pod
  Containers:
   glusterfs:
    Image:	gluster/gluster-centos:latest
    Port:	<none>
    Requests:
      cpu:	100m
      memory:	100Mi
    Liveness:	exec [/bin/bash -c systemctl status glusterd.service] delay=40s timeout=3s period=25s #success=1 #failure=15
    Readiness:	exec [/bin/bash -c systemctl status glusterd.service] delay=40s timeout=3s period=25s #success=1 #failure=15
    Environment:
      GB_GLFS_LRU_COUNT:	15
      TCMU_LOGDIR:		/var/log/glusterfs/gluster-block
    Mounts:
      /dev from glusterfs-dev (rw)
      /etc/glusterfs from glusterfs-etc (rw)
      /etc/ssl from glusterfs-ssl (ro)
      /run from glusterfs-run (rw)
      /run/lvm from glusterfs-lvm (rw)
      /sys/fs/cgroup from glusterfs-cgroup (ro)
      /var/lib/glusterd from glusterfs-config (rw)
      /var/lib/heketi from glusterfs-heketi (rw)
      /var/lib/misc/glusterfsd from glusterfs-misc (rw)
      /var/log/glusterfs from glusterfs-logs (rw)
  Volumes:
   glusterfs-heketi:
    Type:	HostPath (bare host directory volume)
    Path:	/var/lib/heketi
   glusterfs-run:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
   glusterfs-lvm:
    Type:	HostPath (bare host directory volume)
    Path:	/run/lvm
   glusterfs-etc:
    Type:	HostPath (bare host directory volume)
    Path:	/etc/glusterfs
   glusterfs-logs:
    Type:	HostPath (bare host directory volume)
    Path:	/var/log/glusterfs
   glusterfs-config:
    Type:	HostPath (bare host directory volume)
    Path:	/var/lib/glusterd
   glusterfs-dev:
    Type:	HostPath (bare host directory volume)
    Path:	/dev
   glusterfs-misc:
    Type:	HostPath (bare host directory volume)
    Path:	/var/lib/misc/glusterfsd
   glusterfs-cgroup:
    Type:	HostPath (bare host directory volume)
    Path:	/sys/fs/cgroup
   glusterfs-ssl:
    Type:	HostPath (bare host directory volume)
    Path:	/etc/ssl
Events:		<none>

##### Expected Result
oc describe daemonset glusterfs-storage 
Name:		glusterfs-storage
Selector:	glusterfs=storage-pod
Node-Selector:	glusterfs=storage-host
Labels:		glusterfs=storage-daemonset
Annotations:	description=GlusterFS DaemonSet
		tags=glusterfs
Desired Number of Nodes Scheduled: 2
Current Number of Nodes Scheduled: 2
Number of Nodes Scheduled with Up-to-date Pods: 2
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 1 Failed
Pod Template:
  Labels:	glusterfs=storage-pod
		glusterfs-node=pod
  Containers:
   glusterfs:
    Image:	gluster/gluster-centos:latest
    Port:	<none>
    Requests:
      cpu:	100m
      memory:	100Mi
    Liveness:	exec [/bin/bash -c systemctl status glusterd.service] delay=40s timeout=3s period=25s #success=1 #failure=15
    Readiness:	exec [/bin/bash -c systemctl status glusterd.service] delay=40s timeout=3s period=25s #success=1 #failure=15
    Environment:
      GB_GLFS_LRU_COUNT:	15
      TCMU_LOGDIR:		/var/log/glusterfs/gluster-block
    Mounts:
      /dev from glusterfs-dev (rw)
      /etc/glusterfs from glusterfs-etc (rw)
      /etc/ssl from glusterfs-ssl (ro)
      /run from glusterfs-run (rw)
      /run/lvm from glusterfs-lvm (rw)
      /sys/fs/cgroup from glusterfs-cgroup (ro)
      /var/lib/glusterd from glusterfs-config (rw)
      /var/lib/heketi from glusterfs-heketi (rw)
      /var/lib/misc/glusterfsd from glusterfs-misc (rw)
      /var/log/glusterfs from glusterfs-logs (rw)
  Volumes:
   glusterfs-heketi:
    Type:	HostPath (bare host directory volume)
    Path:	/var/lib/heketi
   glusterfs-run:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
   glusterfs-lvm:
    Type:	HostPath (bare host directory volume)
    Path:	/run/lvm
   glusterfs-etc:
    Type:	HostPath (bare host directory volume)
    Path:	/etc/glusterfs
   glusterfs-logs:
    Type:	HostPath (bare host directory volume)
    Path:	/var/log/glusterfs
   glusterfs-config:
    Type:	HostPath (bare host directory volume)
    Path:	/var/lib/glusterd
   glusterfs-dev:
    Type:	HostPath (bare host directory volume)
    Path:	/dev
   glusterfs-misc:
    Type:	HostPath (bare host directory volume)
    Path:	/var/lib/misc/glusterfsd
   glusterfs-cgroup:
    Type:	HostPath (bare host directory volume)
    Path:	/sys/fs/cgroup
   glusterfs-ssl:
    Type:	HostPath (bare host directory volume)
    Path:	/etc/ssl
Events:
  FirstSeen	LastSeen	Count	From		SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----		-------------	--------	------			-------
  18s		18s		1	daemon-set			Normal		SuccessfulCreate	Created pod: glusterfs-storage-d8t4w
  18s		18s		1	daemon-set			Normal		SuccessfulCreate	Created pod: glusterfs-storage-5bjhz

**Comment by sjenning** [comment]
Sounds like a daemonset controller panic to me

**Comment by megian** [comment]
Unable to reproduce it constantly. Closing issue.
