### ISSUE TITLE
[Proposal] Unify names for template parameters

### ISSUE THREAD

**Issue by wtrocki** [openshift/origin#17956]
## Motivation

When working with OpenShift templates sometimes there is need to merge two or more templates together to create end user application template. Currently many upstream templates have the same names which makes it difficult to quickly merge two templates.

While default OpenShift workflow suggest to create all services separately in practical deployments users will always need end user application template that will incorporate multiple services etc. 

## Example 

Duplicated parameters from:
https://github.com/openshift/origin/tree/master/examples/db-templates

- MEMORY_LIMIT
- VOLUME_CAPACITY

etc.

## Problem

After merging templates together name will clash and resulting template will fail to create resources. Manual changes are always needed.

Adding prefix to variables will help users to process templates with parameters and avoid name collisions. For example:

`MEMORY_LIMIT` => `MONGODB_MEMORY_LIMIT`  

This seems very trivial, but I found that to be the biggest problem when training how templates can be build and reused.  I'm happy to contribute to this change if that's something that may be useful. 

Having this will also allow to automatically merge templates together without forking them and modifying the parameters. OpenShift community build tooling to automatically merge and refresh templates once they are updated, but issue above prevents from using them directly.

https://github.com/feedhenry/openshift-template-tool

**Comment by bparees** [comment]
There is a consistency tradeoff involved in doing this, I think it will need more discussion.  

There's also a tradeoff in terms of the intended purpose of the existing templates (between being starting point/examples intended to be modified, and being official product content intended to be consumed directly).
