### ISSUE TITLE
Reduce GitLab oauth's scope from api (full access) to read_user

### ISSUE THREAD

**Issue by alikhajeh1** [openshift/origin#17954]
Currently the [GitLab oauth implementation](https://github.com/openshift/origin/blob/master/pkg/auth/oauth/external/gitlab/gitlab.go#L20-L27) uses the `api` scope, which results in users seeing this from GitLab: `Full access to GitLab as the user, including read/write on all their groups and projects`.

GitLab introduced `read_user` in version 8.15, which seems better suited for this purpose, the description of the scope is `Read-only access to the user's profile information, like username, public email and full name`. I think that would make it similar to what Origin does for GitHub.

##### Version
oc v3.6

**Comment by mfojtik** [comment]
@alikhajeh1 the "read_user" exists from version 8.15 and up, right? If users deploy lower versions, this will break the auth?

**Comment by alikhajeh1** [comment]
@mfojtik yeah it was added in 8.15 (so released just over a year ago): https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/5951
Yeah it'll probably break auth for older GL versions so I wonder if https://docs.openshift.org/latest/install_config/configuring_authentication.html#GitLab could have it as a configuration option?

**Comment by enj** [comment]
@alikhajeh1 have you tried using GitLab's OIDC support to reduce the scope to `openid`?  See https://trello.com/c/DXntmEOV for details.
