### ISSUE TITLE
Restore registry tests as registry moved to external repo

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#17958]
As part of the [1.8 rebase](https://github.com/openshift/origin/pull/17115) (https://github.com/openshift/origin/commit/4e138933d41d0d31cad139f6687e3951df1345a6 specifically) removed registry from origin's repository to an external one -> https://github.com/openshift/image-registry.
The problem with that is that some tests where removed along the way, we need to investigate and bring those missing ones back.

**Comment by bparees** [comment]
@soltysh are you saying we need to enable tests in the origin repo, or in the image-registry repo?

I'm pretty sure @dmage already re-enabled all tests in the image-registry repo, but i'll let him assess this.

**Comment by soltysh** [comment]
@bparees iirc the idea was to have some of those tests in origin, at least the ones that can and should exist there. @mfojtik might remember the details, as he was the one stripping that part out 😉

**Comment by dmage** [comment]
@soltysh thanks, I found in this commit 2 more tests.
https://github.com/openshift/origin/commit/4e138933d41d0d31cad139f6687e3951df1345a6#diff-4214e89bfb45549e49735af038578123
https://github.com/openshift/origin/commit/4e138933d41d0d31cad139f6687e3951df1345a6#diff-d1daafcc0a0ef1e009d0dd44848d8ac4

**Comment by dmage** [comment]
openshift/image-registry#38
openshift/image-registry#39

Feel free to create new issues if you find another tests.

**Comment by soltysh** [comment]
Thanks!
