### ISSUE TITLE
After upgrade from 3.6 to 3.7, service catalog ansible playbook does not set etcd servers for apiserver properly

### ISSUE THREAD

**Issue by pacepace** [openshift/origin#17951]
Upgraded a 3.6 Cluster to 3.7.  Now attempting to install the Service Catalog via the Ansible openshift-ansible/playbooks/openshift-service-catalog/config.yml playbook (just pulled from master).  The kube-service-catalog apiserver does not get configured with the proper etcd servers.  All three etcd servers are listed in the Ansible inventory file.

##### Version
c v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://HIDDEN:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. Upgrade cluster from 3.6 to 3.7
2. Install service catalog via ansible playbook

##### Current Result
Etcd servers for apiserver are not configured properly.  Uses only one of the 3 etcd servers, uses incorrect port 4001 instead of 2379.

##### Expected Result
All configured etcd servers from Ansible inventory and correct port are placed into the apiserver daemonset configuration

**Comment by creiche** [comment]
This also appears to happen when upgrading from OCP 3.7.9 to 3.7.14

**Comment by jpeeler** [comment]
I highly suspect that this (https://github.com/openshift/openshift-ansible/pull/6736) solves the problem.

**Comment by jpeeler** [comment]
/close
Please reopen if problems are still occurring.
