### ISSUE TITLE
After upgrade from 3.6 to 3.7, service catalog ansible playbook does not configure controller manager ssl properly

### ISSUE THREAD

**Issue by pacepace** [openshift/origin#17952]
Upgraded a 3.6 Cluster to 3.7.  Now attempting to install the Service Catalog via the Ansible openshift-ansible/playbooks/openshift-service-catalog/config.yml playbook (just pulled from master).  The controller-manager does not start because of an error with certificates.  It gets the following error:

request.go:1038] body was not decodable (unable to check for Status): Object 'Kind' is missing in 'Error: 'x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "service-catalog-signer")'
Trying to reach: 'https://x.x.x.x:443/apis/servicecatalog.k8s.io/v1beta1''

Tried to curl the address from controller manager pod using k8s secret supplied certificates: curl --cacert /var/run/kubernetes-service-catalog/apiserver.crt https://x.x.x.x:443/apis/servicecatalog.k8s.io/v1beta1

Curl cannot connect either with unknown authority error.

##### Version
c v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://HIDDEN:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. Upgrade cluster from 3.6 to 3.7
2. Install service catalog via ansible playbook

##### Current Result
Controller Manager unable to connect to API server due to incorrect SSL configuration

##### Expected Result
Controller Manager configured with proper SSL certificates.

**Comment by bortek** [comment]
I am trying the same thing on ver 3.7.14 and I get the same error. Any progress or finding on this ? I can see two bugzilla reports without any answer. 

https://bugzilla.redhat.com/show_bug.cgi?id=1523625
https://bugzilla.redhat.com/show_bug.cgi?id=1526150

Can anyone comment on this?

**Comment by varac** [comment]
Same problem here. A fix would be appreciated!

**Comment by Filirom1** [comment]
To solve this, I had to run this command and execute again the installer:
```
oc delete apiservices.apiregistration.k8s.io/v1beta1.servicecatalog.k8s.io -n kube-service-catalog
```

For information, to get the service catalog working I also had to do the following steps:

```
# Missing node-selector for openshift-template-service-broker
oc edit ns openshift-template-service-broker
    openshift.io/node-selector: ""

# By default apiserver configuration is referencing master1 as etcd server. Which is not our case
oc edit ds apiserver -n kube-service-catalog
```

**Comment by btito** [comment]
Thanks!.. it also seems that the today's  pull of the ansible-openshift repo also fixed asb-etcd issues i had.

**Comment by ephillipe** [comment]
I'm getting this error yet.

/ TASK [ansible_service_broker : Create the Broker resource \
\ in the catalog]                                           /
 -----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [ip-172-30-6-111.ec2.internal]: FAILED! => {"changed": false, "failed": true, "msg": {"cmd": "/bin/oc create -f /tmp/brokerout-OdpeuR -n default", "results": {}, "returncode": 1, "stderr": "error: unable to recognize \"/tmp/brokerout-OdpeuR\": no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker\n", "stdout": ""}}
	to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/service-catalog.retry

**Comment by pacepace** [comment]
Attempting to rerun the ansible installed gets me this:

> fatal: [MasterFQDN]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to MasterFQDN closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_8QEIUG/ansible_module_repoquery.py\", line 641, in <module>\r\n    main()\r\n  File \"/tmp/ansible_8QEIUG/ansible_module_repoquery.py\", line 631, in main\r\n    rval = Repoquery.run_ansible(module.params, module.check_mode)\r\n  File \"/tmp/ansible_8QEIUG/ansible_module_repoquery.py\", line 587, in run_ansible\r\n    results = repoquery.repoquery()\r\n  File \"/tmp/ansible_8QEIUG/ansible_module_repoquery.py\", line 546, in repoquery\r\n    rval = self._repoquery_cmd(repoquery_cmd, True, 'raw')\r\n  File \"/tmp/ansible_8QEIUG/ansible_module_repoquery.py\", line 384, in _repoquery_cmd\r\n    returncode, stdout, stderr = _run(cmds)\r\n  File \"/tmp/ansible_8QEIUG/ansible_module_repoquery.py\", line 355, in _run\r\n    stderr=subprocess.PIPE)\r\n  File \"/usr/lib64/python2.7/subprocess.py\", line 711, in __init__\r\n    errread, errwrite)\r\n  File \"/usr/lib64/python2.7/subprocess.py\", line 1327, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n", "msg": "MODULE FAILURE", "rc": 0}

I'm guessing it is trying to install an RPM as this comes right after this task: TASK [openshift_version : Set openshift_version for rpm installation]

Running in verbose mode reveals some more:

> <MasterFQDN> (0, 'Traceback (most recent call last):\r\n  File "/tmp/ansible_1uqNPl/ansible_module_repoquery.py", line 641, in <module>\r\n    main()\r\n  File "/tmp/ansible_1uqNPl/ansible_module_repoquery.py", line 631, in main\r\n    rval = Repoquery.run_ansible(module.params, module.check_mode)\r\n  File "/tmp/ansible_1uqNPl/ansible_module_repoquery.py", line 587, in run_ansible\r\n    results = repoquery.repoquery()\r\n  File "/tmp/ansible_1uqNPl/ansible_module_repoquery.py", line 546, in repoquery\r\n    rval = self._repoquery_cmd(repoquery_cmd, True, \'raw\')\r\n  File "/tmp/ansible_1uqNPl/ansible_module_repoquery.py", line 384, in _repoquery_cmd\r\n    returncode, stdout, stderr = _run(cmds)\r\n  File "/tmp/ansible_1uqNPl/ansible_module_repoquery.py", line 355, in _run\r\n    stderr=subprocess.PIPE)\r\n  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__\r\n    errread, errwrite)\r\n  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 41453\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to MasterFQDN closed.\r\n')

I still don't know what it is looking for that is missing...

**Comment by aizuddin85** [comment]
Having same trouble, despite unable to get scc but seems like policy is still in working order.

**Comment by soltysh** [comment]
For reference, this bug is affecting `oc get scc` for some unknown reason to me. See https://bugzilla.redhat.com/show_bug.cgi?id=1525014 for further details.

**Comment by fvanraem** [comment]
Running into a very similar looking problem on a OCP 3.9.30 master.

root@master6:~ # oc version
oc v3.9.30
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://cluster.example.com:8443
openshift v3.9.30
kubernetes v1.9.1+a0ce1bc657

root@master6:~ # oc get dc
the server doesn't have a resource type "dc"

root@master6:~ # oc get deploymentconfig
NAME               REVISION   DESIRED   CURRENT   TRIGGERED BY
docker-registry    13         1         1         config
registry-console   6          1         1         config
router             16         3         3         config
root@master6:~ # oc get dc --loglevel=1
I0621 08:42:10.773178   74398 shortcut_restmapper.go:81] Error loading discovery information: an error on the server ("Error: 'x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"service-catalog-signer\")'\nTrying to reach: 'https://172.30.2.125:443/apis/servicecatalog.k8s.io/v1alpha1'") has prevented the request from succeeding
the server doesn't have a resource type "dc"

**Comment by Juanker92** [comment]
fulano
