### ISSUE TITLE
OriginNamespaceLifecycle must not reject objects not in latest.RESTMapper

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1796]
It should not be required for 

```
	defaultVersion, kind, err := latest.RESTMapper.VersionAndKindForResource(a.GetResource())
	if err != nil {
		return err
	}
```

to succeed for `pkg/project/admission/admission.go`

**Comment by smarterclayton** [comment]
Or rather, it's likely that we could use ObjectTyper instead on the passed runtime.Object

**Comment by derekwaynecarr** [comment]
Where is this causing a problem so I can understand the issue better?

**Comment by derekwaynecarr** [comment]
And does the same change also then need to be made for upstream Kube?

**Comment by smarterclayton** [comment]
RESTMapper is not required to be authoritative on whether an endpoint exists.  It's more to provide a pattern.  If RESTMapper doesn't know about a resource, but the admission controller is called, it just means the admission controller doesn't know about the resource

----- Original Message -----
