### ISSUE TITLE
An error occurred getting metrics.

### ISSUE THREAD

**Issue by badreddine16** [openshift/origin#17963]
When you launch the cluster, (current version 3.7.0), impossible to access/launch the metrics app.
## Using the URL : 
Application is not available
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.
## After investigation, you have an error :
Failed to pull image "openshift/origin-ansible:v3.7.0": rpc error: code = 2 desc = Error response from daemon: {"message":"manifest for openshift/origin-ansible:v3.7.0 not found"}

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. oc cluster up --public-hostname="${public_hostname}" --routing-suffix="${public_ip}.nip.io" --metrics=true --logging --loglevel=5
PS : I'm using a VM on AWS EC2 (Ubuntu 16.04)

##### Current Result
When you access to the project **openshift-infra**
`Failed to pull image "openshift/origin-ansible:v3.7.0": rpc error: code = 2 desc = Error response from daemon: {"message":"manifest for openshift/origin-ansible:v3.7.0 not found"}`

Which is normal, since there is no docker image with tag v3.7.0 https://hub.docker.com/r/openshift/origin-ansible/tags/

**Comment by jcantrill** [comment]
@jupierce Can you comment regarding the tagging for this ansible image?

**Comment by jupierce** [comment]
@jcantrill my team only builds and publishes rhel/ose images. @smarterclayton publishes origin releases.

**Comment by badreddine16** [comment]
Hola Chicos ! Any news regarding this issue ?!
