### ISSUE TITLE
Build Secret Not working for Git Clone

### ISSUE THREAD

**Issue by bobbydeveaux** [openshift/origin#17968]
Having trouble using `git clone` over ssh within a Dockerfile. Permission denied. 

##### Version
 oc version
oc v3.7.0-rc.0+e92d5c5
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://51.179.219.187:8443
openshift v3.7.0-rc.0+e92d5c5
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
Builder Secret not working

`ssh-keygen -t ed25519 -C "deploy@me.com" -f deploy_key`

**Added key to GitHub**

**confirmed key works**

`oc new-project test1`

`oc secrets new-sshauth deploykey --ssh-privatekey=./deploy_key`

`oc secrets add serviceaccount/builder secrets/deploykey`

`oc new-build --name web3 --binary --build-secret deploykey`

`oc patch buildConfig web3 -p '{"spec":{"source":{"sourceSecret":{"name":"deploykey"}}}}'`

`oc set env bc/web3 --env=GIT_SSL_NO_VERIFY=true`

`oc start-build web3 --from-file=. --follow`

Dockerfile
```
FROM ubuntu:latest

RUN apt-get update -y && apt-get install -y git

COPY git_ssh .

RUN chmod 0755 git_ssh

ENV GIT_SSH=./git_ssh

RUN ls -la var

RUN git clone git@github.com:bobbydeveaux/php-show-my-hostname.git
```

git_ssh
```
#!/bin/sh
exec /usr/bin/ssh -vvv -o StrictHostKeyChecking=no  "$@"
```

##### Current Result
```
Cloning into 'php-show-my-hostname'...
OpenSSH_7.2p2 Ubuntu-4ubuntu2.2, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "github.com" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to github.com [192.30.253.113] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: SELinux support disabled
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
debug1: Remote protocol version 2.0, remote software version libssh_0.7.0
debug1: no match: libssh_0.7.0
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to github.com:22 as 'git'
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-dss,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib,zlib@openssh.com
debug2: compression stoc: none,zlib,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS received
debug2: key: /root/.ssh/id_rsa ((nil))
debug2: key: /root/.ssh/id_dsa ((nil))
debug2: key: /root/.ssh/id_ecdsa ((nil))
debug2: key: /root/.ssh/id_ed25519 ((nil))
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /root/.ssh/id_rsa
debug3: no such identity: /root/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_dsa
debug3: no such identity: /root/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ecdsa
debug3: no such identity: /root/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ed25519
debug3: no such identity: /root/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error: build error: The command '/bin/sh -c git clone git@github.com:bobbydeveaux/php-show-my-hostname.git' returned a non-zero code: 128
error: the build test1/web3-3 status is "Failed"
```
##### Expected Result
Expected a successful build.

##### Additional Information
build config

```
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: '2018-01-03T14:19:43Z'
  labels:
    build: web3
  name: web3
  namespace: test1
  resourceVersion: '3746420'
  selfLink: /apis/build.openshift.io/v1/namespaces/test1/buildconfigs/web3
  uid: 246d49f5-f091-11e7-9799-fa163ea4d9ea
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'web3:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    secrets:
      - destinationDir: .
        secret:
          name: deploykey
    sourceSecret:
      name: deploykey
    type: Binary
  strategy:
    dockerStrategy:
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: 55HSHBMh92njSkOe3d4X
      type: GitHub
    - generic:
        secret: 5HRvgFabHmu8I9R79yK_
      type: Generic
status:
  lastVersion: 3

```

**Comment by bobbydeveaux** [comment]
I understand sourceSecret is meant for S2I builds, which is why I have also added the 'secrets' stuff too. It's a public repo too!

Any clues? :)

Much appreciated

**Comment by php-coder** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
first off, since you're doing a binary build sourceSecret is irrelevant.

It looks like you're trying to inject a secret so you can use it to do the git clone, but if your repo is public, i'm not sure why you're doing that either.  

this:
```
secrets:
      - destinationDir: .
        secret:
          name: deploykey
```

is going to make the content of deployKey available in your docker build working directory, but I don't see your Dockerfile referencing it.  I do see your Dockerfile referencing:

```
COPY git_ssh .
```

but i'm not sure where "git_ssh" is supposed to come from?  Is that a key in your "deployKey" secret?

What happens if you remove all the ssh logic from your Dockerfile and just do a straight git clone?  What if you do the git clone over http instead of ssh?

**Comment by bobbydeveaux** [comment]
Thanks @bparees  - full understand sourceSecret is irrelevant, was kinda clutching at straws.

The git_ssh is referenced in my issue, it's to skip host name verification. If do a standard 'git clone' without the git_ssh stuff, I get the host name verification error, as this happens before checking ssh credentials.

I appreciate this is a public repository, but even public repositories requires ssh authentication when cloning over SSH, hence injecting the ssh key.

However, my *actual* project is a Private repo, where I encountered this issue. I was trying to go back to basics, and even a 'cut down' public repository doing a git clone doesn't work, hence the issue :)

This should work though, right? Can you see that I'm doing something incorrectly? I shouldn't have to use https, as ssh is a perfectly valid way to clone, right? :)

**Comment by bparees** [comment]
you don't need git_ssh to skip verification, "GIT_SSL_NO_VERIFY=true" covers that.

I still don't see where "git_ssh" is coming from.  Is it part of the local directory you are doing a binary build from?


If you want to use the content of "deployKey" during your git clone operation, then you need a COPY statement that will copy it from the docker build workdir into your image so it can be used by your subsequent Dockerfile operations.

I would note that this is really not the way i'd go about this.  I would suggest instead you define your build with a git source input (at which point the sourceSecret will be used to clone): 
https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#source-code

You can then add a "COPY . ." to copy the content that is cloned into your image.

you might find this to be useful reading as well:
https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#how-build-inputs-work

**Comment by bobbydeveaux** [comment]
Thanks.

I'm not able to use the source for an S2I image, as this is an app being ported from Heroku with a rather large Dockerfile. I'm just simplifying for this example.

The git_ssh file simply has this:

```
#!/bin/sh
exec /usr/bin/ssh -i deploykey2 -vvv -o StrictHostKeyChecking=no  "$@"
```

But, as you say, "GIT_SSL_NO_VERIFY" is meant to sort the host name thing, so what happens if I leave it out?

```
FROM ubuntu:latest

RUN apt-get update -y 

RUN apt-get install -y git

#COPY git_ssh .

#RUN chmod 0755 git_ssh

#ENV GIT_SSH=./git_ssh

RUN ls -la var

RUN git clone git@github.com:bobbydeveaux/php-show-my-hostname.git
```

```
Cloning into 'php-show-my-hostname'...
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error: build error: The command '/bin/sh -c git clone git@github.com:bobbydeveaux/php-show-my-hostname.git' returned a non-zero code: 128
error: the build disciple-api2/web3-10 status is "Failed"
```

So, that didn't work. Hence why I'm using the git_ssh hack, which doesn't seem to do any harm really. 

So, I should be able to `COPY deploykey .`  ?

```
FROM ubuntu:latest

RUN apt-get update -y 

RUN apt-get install -y git

COPY deploykey .

#COPY git_ssh .

#RUN chmod 0755 git_ssh

#ENV GIT_SSH=./git_ssh

RUN ls -la var

RUN git clone git@github.com:bobbydeveaux/php-show-my-hostname.git
```

this results in:

```
Uploading directory "." as binary input for the build ...
build "web3-11" started
Receiving source from STDIN as archive ...
Step 1 : FROM ubuntu:latest
 ---> 00fd29ccc6f1
Step 2 : ENV "GIT_SSL_NO_VERIFY" "true"
 ---> Using cache
 ---> 98860610da29
Step 3 : RUN apt-get update -y
 ---> Using cache
 ---> aa8c0620afa5
Step 4 : RUN apt-get install -y git
 ---> Using cache
 ---> aa675f6fa987
Step 5 : COPY deploykey .
error: build error: lstat deploykey: no such file or directory
error: the build disciple-api2/web3-11 status is "Failed"
```

Thanks for those links, but I have been reading about the build secrets and service account and build inputs for a few days (thx Google), as I have been trying to figure this issue out.. :(

Any other tips would be much appreciated!

Many thanks

**Comment by bparees** [comment]
Using git source is not tied to doing an s2i build.  So you could still use a git source input with your Dockerfile if you wanted.  

> So, I should be able to COPY deploykey . ?

not precisely.  "deploykey" is a secret that contains a set of keys.  Those keys will be mounted in as files.  It is those files you need to copy.  

Take a look at this example:

Some secrets that are defined:
https://github.com/openshift/origin/blob/master/test/extended/testdata/builds/build-secrets/test-secret.json
https://github.com/openshift/origin/blob/master/test/extended/testdata/builds/build-secrets/test-secret-2.json

A build that uses the secrets as inputs:
https://github.com/openshift/origin/blob/master/test/extended/testdata/builds/build-secrets/test-docker-build.json#L15-L28

A dockerfile that copies the secret content into the image that's being built:
https://github.com/openshift/origin/blob/master/test/extended/testdata/builds/build-secrets/Dockerfile

**Comment by bobbydeveaux** [comment]
Excellent thanks for those examples! I shall first play around with those secrets again, but as you say it's not ideal to have that key on the image..! 

Knowing that I can use the GitHub source AND use a Dockerfile is very interesting. I've not seen any docs/examples surrounding that one? Dare suppose you have any?

I shall have a play with those COPY secret stuff for now.

Thanks again! :)

**Comment by bparees** [comment]
> Knowing that I can use the GitHub source AND use a Dockerfile is very interesting. I've not seen any docs/examples surrounding that one? Dare suppose you have any?

https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-dockerbuild.json#L96-L165

**Comment by bparees** [comment]
opened docs PR to improve this:
https://github.com/openshift/openshift-docs/pull/7214
