### ISSUE TITLE
CLI panic when running oc status

### ISSUE THREAD

**Issue by MarkRx** [openshift/origin#17977]
oc cli panics when running oc status:

> >oc status
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0xe8 pc=0x1b646ac]
> 
> goroutine 1 [running]:
> panic(0x3833240, 0xc042004090)
>         /usr/lib/golang/src/runtime/panic.go:500 +0x1af
> github.com/openshift/origin/pkg/deploy/graph.AddVolumeClaimEdges(0x61365c0, 0xc042f43a40, 0x612edc0, 0x6273688, 0x6130bc0, 0xc042f43a40, 0xc042f43a70, 0xc042f43
> a40, 0xc0429bfbf0)
>         /builddir/build/BUILD/atomic-openshift-git-0.f95b0e7/_output/local/go/src/github.com/openshift/origin/pkg/deploy/graph/edges.go:95 +0x4c
> github.com/openshift/origin/pkg/deploy/graph.AddAllVolumeClaimEdges(0x61365c0, 0xc042f43a40, 0x612edc0, 0x6273688, 0x6130bc0, 0xc042f43a40, 0xc042f43a70, 0xc042
> f43a40)
>         /builddir/build/BUILD/atomic-openshift-git-0.f95b0e7/_output/local/go/src/github.com/openshift/origin/pkg/deploy/graph/edges.go:117 +0xbf
> github.com/openshift/origin/pkg/cmd/cli/describe.(*ProjectStatusDescriber).MakeGraph(0xc042f68960, 0xc042ecbbe0, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /builddir/build/BUILD/atomic-openshift-git-0.f95b0e7/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/describe/projectstatus.go:139 +0x1adf
> github.com/openshift/origin/pkg/cmd/cli/describe.(*ProjectStatusDescriber).Describe(0xc042f68960, 0xc042ecbbe0, 0x17, 0x0, 0x0, 0xc042ed87b0, 0x0, 0x0, 0x1)
>         /builddir/build/BUILD/atomic-openshift-git-0.f95b0e7/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/describe/projectstatus.go:151 +0xe6
> github.com/openshift/origin/pkg/cmd/cli/cmd.StatusOptions.RunStatus(0xc042ecbbe0, 0x17, 0x0, 0x0, 0x0, 0xc042f68960, 0x6102a80, 0xc042024010, 0x0, 0xc042257d49,
>  ...)
>         /builddir/build/BUILD/atomic-openshift-git-0.f95b0e7/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/status.go:182 +0x3af
> github.com/openshift/origin/pkg/cmd/cli/cmd.NewCmdStatus.func1(0xc04222afc0, 0x6273688, 0x0, 0x0)
>         /builddir/build/BUILD/atomic-openshift-git-0.f95b0e7/_output/local/go/src/github.com/openshift/origin/pkg/cmd/cli/cmd/status.go:80 +0x150
> github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc04222afc0, 0x6273688, 0x0, 0x0, 0xc04222afc0, 0x6273688)
>         /builddir/build/BUILD/atomic-openshift-git-0.f95b0e7/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x44
> 0
> github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc042255440, 0xc042024008, 0xc042024018, 0xc042255440)
>         /builddir/build/BUILD/atomic-openshift-git-0.f95b0e7/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x36
> e
> github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042255440, 0x2, 0xc042255440)
>         /builddir/build/BUILD/atomic-openshift-git-0.f95b0e7/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x32
> 
> main.main()
>         /builddir/build/BUILD/atomic-openshift-git-0.f95b0e7/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:36 +0x19d

##### Version

> >oc version
> oc v3.6.173.0.21
> kubernetes v1.6.1+5115d708d7
> features: Basic-Auth
> 
> Server ***
> openshift v3.6.173.0.21
> kubernetes v1.6.1+5115d708d7

This uses the windows oc client.

##### Steps To Reproduce
1. Run oc status. A panic occurs.

State of project:

> >oc get all
> NAME                            REFERENCE                         TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
> hpa/n2-perspectium-autoscaler   DeploymentConfig/ten-perspect-b   <unknown> / 80%   1         1         0          20d

**Comment by php-coder** [comment]
CC @juanvallejo

**Comment by mfojtik** [comment]
@MarkRx can you please provide YAML version of that deployment config?

**Comment by MarkRx** [comment]
The yaml is similar to what other teams are using. I am not aware of anyone else having any issues. I suspect it is either from the autoscaler or some corrupt data in the project.

It seems oc status only has the stacktrace after the dc is deleted.

ten-perspect-b.yaml:
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2018-01-03T20:59:32Z
  generation: 2
  name: ten-perspect-b
  namespace: n2a-ten-perspectium-pyx
  resourceVersion: "31483453"
  selfLink: /oapi/v1/namespaces/n2a-ten-perspectium-pyx/deploymentconfigs/ten-perspect-b
  uid: ff03bb20-f0c8-11e7-8cbc-005056b9b8aa
spec:
  replicas: 1
  selector:
    name: ten-perspect-b
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[{"name":"ten-perspect-config-cnt-b","image":"foobar.com/ten-tools/ten-tools-perspectium-config:master.108","env":[{"name":"SELECTED_ENV","value":"n2a"},{"name":"DATACENTER","value":"wdc"},{"name":"PROJECT_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}}],"resources":{"limits":{"memory":"1024M"}},"volumeMounts":[{"name":"config-dir","mountPath":"/config"},{"name":"log-dir","mountPath":"/logs"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}]'
        pod.beta.kubernetes.io/init-containers: '[{"name":"ten-perspect-config-cnt-b","image":"foobar.com/ten-tools/ten-tools-perspectium-config:master.108","env":[{"name":"SELECTED_ENV","value":"n2a"},{"name":"DATACENTER","value":"wdc"},{"name":"PROJECT_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}}],"resources":{"limits":{"memory":"1024M"}},"volumeMounts":[{"name":"config-dir","mountPath":"/config"},{"name":"log-dir","mountPath":"/logs"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}]'
      creationTimestamp: null
      labels:
        name: ten-perspect-b
    spec:
      containers:
      - env:
        - name: SELECTED_ENV
          value: n2a
        - name: DATACENTER
          value: wdc
        - name: PROJECT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: foobar.com/ten-tools/ten-tools-perspectium-app:master.108
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - /config/app/heartbeat.sh
          failureThreshold: 3
          initialDelaySeconds: 25
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ten-perspect-cnt-b
        readinessProbe:
          exec:
            command:
            - sh
            - /config/app/connectivity.sh
          failureThreshold: 3
          initialDelaySeconds: 25
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1024M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-dir
        - mountPath: /logs
          name: log-dir
      dnsPolicy: ClusterFirst
      initContainers:
      - env:
        - name: SELECTED_ENV
          value: n2a
        - name: DATACENTER
          value: wdc
        - name: PROJECT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: foobar.com/ten-tools/ten-tools-perspectium-config:master.108
        imagePullPolicy: IfNotPresent
        name: ten-perspect-config-cnt-b
        resources:
          limits:
            memory: 1024M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-dir
        - mountPath: /logs
          name: log-dir
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: config-dir
      - emptyDir: {}
        name: log-dir
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-01-03T20:59:36Z
    lastUpdateTime: 2018-01-03T21:00:17Z
    message: replication controller "ten-perspect-b-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-01-04T09:07:06Z
    lastUpdateTime: 2018-01-04T09:07:06Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1

```

n2-perspectium-autoscaler.yaml:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: 2017-12-14T13:40:57Z
  name: n2-perspectium-autoscaler
  namespace: n2a-ten-perspectium-pyx
  resourceVersion: "31416828"
  selfLink: /apis/autoscaling/v1/namespaces/n2a-ten-perspectium-pyx/horizontalpodautoscalers/n2-perspectium-autoscaler
  uid: 6a54380c-e0d4-11e7-8cbc-005056b9b8aa
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: ten-perspect-b
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 1
  desiredReplicas: 1
  lastScaleTime: 2018-01-03T20:22:21Z
```

**Comment by MarkRx** [comment]
One more detail - this uses the windows oc client.

**Comment by mfojtik** [comment]
@MarkRx have you tested linux/osx client? Just want to rule out the cause of this being windows specific.

**Comment by mfojtik** [comment]
(I tried to recreate this with your DC and autoscaled, but `oc status` seems to be working fine (on OSX))

**Comment by juanvallejo** [comment]
> It seems oc status only has the stacktrace after the dc is deleted.

@mfojtik @soltysh 
Can confirm. I was able to recreate this on linux by creating the DC and hpa that @MarkRx posted,
deleting only the dc, and then calling `oc status`.

Here is the output of `oc status` prior to deleting the deploymentconfig:
```
In project My Project (myproject) on server https://127.0.0.1:8443

dc/ten-perspect-b deploys
  foobar.com/ten-tools/ten-tools-perspectium-app:master.108
  deployment #1 running for about a minute - 0/1 pods
  foobar.com/ten-tools/ten-tools-perspectium-config:master.108
  deployment #1 running for about a minute - 0/1 pods

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```

<details>
<summary>And here is the stacktrace received from `oc status` after deleting only the deploymentconfig</summary>
<p>
<code>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf0 pc=0x220d5f5]

goroutine 1 [running]:
github.com/openshift/origin/pkg/apps/graph.AddVolumeClaimEdges(0x7a3f2e0, 0xc421442900, 0x7a36680, 0x7e49a88, 0x7a385c0, 0xc421442900, 0xc421442930, 0xc421442900, 0xc421608000)
        /home/jvallejo/Documents/go/src/github.com/openshift/origin/pkg/apps/graph/edges.go:95 +0x45
github.com/openshift/origin/pkg/apps/graph.AddAllVolumeClaimEdges(0x7a3f2e0, 0xc421442900, 0x7a36680, 0x7e49a88, 0x7a385c0, 0xc421442900, 0xc421442930, 0xc421442900)
        /home/jvallejo/Documents/go/src/github.com/openshift/origin/pkg/apps/graph/edges.go:117 +0x98
github.com/openshift/origin/pkg/oc/cli/describe.(*ProjectStatusDescriber).MakeGraph(0xc4214700e0, 0xc4204c5790, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jvallejo/Documents/go/src/github.com/openshift/origin/pkg/oc/cli/describe/projectstatus.go:150 +0x1889
github.com/openshift/origin/pkg/oc/cli/describe.(*ProjectStatusDescriber).Describe(0xc4214700e0, 0xc4204c5790, 0x9, 0x0, 0x0, 0xc420d1b0f0, 0x7a17480, 0xc420d1afe0, 0x7a17a00)
        /home/jvallejo/Documents/go/src/github.com/openshift/origin/pkg/oc/cli/describe/projectstatus.go:162 +0xf0
github.com/openshift/origin/pkg/oc/cli/cmd.StatusOptions.RunStatus(0xc4204c5790, 0x9, 0x0, 0x0, 0x0, 0xc4214700e0, 0x79f8b00, 0xc42000e018, 0x0, 0xc4204c51f0, ...)
        /home/jvallejo/Documents/go/src/github.com/openshift/origin/pkg/oc/cli/cmd/status.go:209 +0x3b8
github.com/openshift/origin/pkg/oc/cli/cmd.NewCmdStatus.func1(0xc420455200, 0x7e49a88, 0x0, 0x0)
        /home/jvallejo/Documents/go/src/github.com/openshift/origin/pkg/oc/cli/cmd/status.go:83 +0x149
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420455200, 0x7e49a88, 0x0, 0x0, 0xc420455200, 0x7e49a88)
        /home/jvallejo/Documents/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x234
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420432240, 0x202e811, 0xc420432240, 0xc420374360)
        /home/jvallejo/Documents/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420432240, 0x2, 0xc420432240)
        /home/jvallejo/Documents/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /home/jvallejo/Documents/go/src/github.com/openshift/origin/cmd/oc/oc.go:41 +0x293
</code>
</p>
</details>

**Comment by juanvallejo** [comment]
Suggested a solution for the above comment here https://github.com/openshift/origin/pull/17983#issuecomment-357091868
