### ISSUE TITLE
oc cluster up --metrics broken for v3.7.0

### ISSUE THREAD

**Issue by praveenkumar** [openshift/origin#17986]
##### Version
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. oc cluster up --metrics

##### Current Result

It doesn't pull out the origin-ansible image from docker hub and pod creation fails.
```
$ docker logs origin
[...]
E0104 12:34:21.118042   13661 pod_workers.go:186] Error syncing pod 7b831a06-f14b-11e7-87f3-507b9d472811 ("openshift-ansible-metrics-job-q6tw2_openshift-infra(7b831a06-f14b-11e7-87f3-507b9d472811)"), skipping: failed to "StartContainer" for "openshift-ansible-metrics-job" with ErrImagePull: "rpc error: code = 2 desc = manifest for docker.io/openshift/origin-ansible:v3.7.0 not found"
```

##### Expected Result

metrics should be provisioned successfully 

##### Additional Information
Looks like tag on docker hub https://hub.docker.com/r/openshift/origin-ansible/tags/ is not updated :(

**Comment by php-coder** [comment]
@stevekuznetsov Do you know, who is responsible for dockerhub images?

**Comment by stevekuznetsov** [comment]
@sdodson do we currently have a process for publishing `openshift/origin-ansible`?

**Comment by sdodson** [comment]
@stevekuznetsov this looks to publish it https://ci.openshift.redhat.com/jenkins/job/build-and-release-latest-openshift-ansible-images/

**Comment by jorgemoralespou** [comment]
It is not only about publishing the images, but also about proper tagging.
Tagging scheme seems to have changed in 3.7+, and for many images there scheme has changed from 3.7.x to only 3.7, also for 3.9, etc... while previously to 3.7.0 all tags had the Major.Minor.Patch elements in the scheme.

It's possible to tag 3.7 as 3.7.0 and problem will be easily solved.

**Comment by smarterclayton** [comment]
v3.7.0 is now tagged from v3.7

**Comment by jorgemoralespou** [comment]
Now, the images for metrics and logging do need also to be properly tagged (or released):

Not properly tagged:
- https://hub.docker.com/r/openshift/origin-logging-elasticsearch/tags/
- https://hub.docker.com/r/openshift/origin-logging-kibana/tags/
- https://hub.docker.com/r/openshift/origin-logging-curator/tags/
- https://hub.docker.com/r/openshift/origin-logging-fluentd/tags/

Not even released:
- https://hub.docker.com/r/openshift/origin-metrics-heapster/tags/
- https://hub.docker.com/r/openshift/origin-metrics-hawkular-metrics/tags/
- https://hub.docker.com/r/openshift/origin-metrics-cassandra/tags/

Thanks

**Comment by jorgemoralespou** [comment]
@smarterclayton @jupierce it would be nice if OpenShift CI would catch this.

**Comment by praveenkumar** [comment]
Even after this is fixed looks like other images which @jorgemoralespou mentioned should need to be released/tagged properly.

```
E0115 08:32:40.546945    3006 remote_image.go:108] PullImage "openshift/origin-metrics-heapster:v3.7.0" from image service failed: rpc error: code = 2 desc = Tag v3.7.0 not found in repository docker.io/openshift/origin-metrics-heapster
E0115 08:32:40.547035    3006 kuberuntime_image.go:50] Pull image "openshift/origin-metrics-heapster:v3.7.0" failed: rpc error: code = 2 desc = Tag v3.7.0 not found in repository docker.io/openshift/origin-metrics-heapster
```

**Comment by jorgemoralespou** [comment]
It seems like logging is already solved, but still not metrics.

**Comment by jorgemoralespou** [comment]
@praveenkumar Seems like it is finally fixed for 3.7.0

@smarterclayton Now, for 3.7.1 we still need origin-ansible 3.7.1 (https://hub.docker.com/r/openshift/origin-ansible/tags/)

It looks like cutting an origin release should automate the release of some images in the CI process.

**Comment by jcantrill** [comment]
@smarterclayton Can this be full filled with your new tagging scheme and process?  This issue is still most likely blocked and would dup: https://github.com/openshift/openshift-ansible/issues/7006

**Comment by michaelpaesold** [comment]
Can this be fixed, or is there a work around?

**Comment by gihad** [comment]
`oc cluster up --metrics`
> Error: unknown flag: --metrics

`oc cluster up --enable=metrics`
> error: cannot use --enable when the cluster is already initialized, use cluster add instead

If starting the cluster first and then trying to add:

`oc cluster add metrics`
> Error: unknown component "metrics", valid component names are: "automation-service-broker,centos-imagestreams,persistent-volumes,registry,rhel-imagestreams,router,sample-templates,service-catalog,template-service-broker,web-console"


Same results with the logging component, perhaps docs [here](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#installing-metrics) are old?

**Comment by Vermillionaire** [comment]
I'm seeing the same issues as @gihad. The documented steps to deploy metrics/logging using `oc cluster up` is no longer valid and there doesnt seem to be a way to deploy metrics/logging with the current oc command.
