### ISSUE TITLE
failure: repodata/repomd.xml from origin-local-release: [Errno 256] No more mirrors to try.

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#17995]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_end_to_end/7544/consoleFull#-2459382805717850ae4b077d9ca921b55

failure: repodata/repomd.xml from origin-local-release: [Errno 256] No more mirrors to try.

[openshift/origin-docker-registry] failure: repodata/repomd.xml from origin-local-release: [Errno 256] No more mirrors to try.
[openshift/origin-docker-registry] file:///srv/origin-local-release/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /srv/origin-local-release/repodata/repomd.xml"
[openshift/origin-docker-registry] running '/bin/sh -c export "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"; INSTALL_PKGS="origin-dockerregistry" &&     yum --enablerepo=origin-local-release install -y ${INSTALL_PKGS} &&     rpm -V ${INSTALL_PKGS} &&     yum clean all' failed with exit code 1
[WARNING] Retrying image build for openshift/origin-docker-registry:latest, attempt 1...
[openshift/origin-docker-registry] --> FROM openshift/origin-base
[openshift/origin-docker-registry] --> RUN INSTALL_PKGS="origin-dockerregistry" &&     yum --enablerepo=origin-local-release install -y ${INSTALL_PKGS} &&     rpm -V ${INSTALL_PKGS} &&     yum clean all
[openshift/origin-docker-registry] Loaded plugins: fastestmirror, ovl
[openshift/origin-docker-registry] file:///srv/origin-local-release/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /srv/origin-local-release/repodata/repomd.xml"
[openshift/origin-docker-registry] Trying other mirror.
[openshift/origin-docker-registry]  One of the configured repositories failed (OpenShift Origin Release from Local Source),
[openshift/origin-docker-registry]  and yum doesn't have enough cached data to continue. At this point the only
[openshift/origin-docker-registry]  safe thing yum can do is fail. There are a few ways to work "fix" this:
[openshift/origin-docker-registry]      1. Contact the upstream for the repository and get them to fix the problem.
[openshift/origin-docker-registry]      2. Reconfigure the baseurl/etc. for the repository, to point to a working
[openshift/origin-docker-registry]         upstream. This is most often useful if you are using a newer
[openshift/origin-docker-registry]         distribution release than is supported by the repository (and the
[openshift/origin-docker-registry]         packages for the previous distribution release still work).
[openshift/origin-docker-registry]      3. Run the command with the repository temporarily disabled
[openshift/origin-docker-registry]             yum --disablerepo=origin-local-release ...
[openshift/origin-docker-registry]      4. Disable the repository permanently, so yum won't use it by default. Yum
[openshift/origin-docker-registry]         will then just ignore the repository until you permanently enable it
[openshift/origin-docker-registry]         again or use --enablerepo for temporary usage:
[openshift/origin-docker-registry]             yum-config-manager --disable origin-local-release
[openshift/origin-docker-registry]         or
[openshift/origin-docker-registry]             subscription-manager repos --disable=origin-local-release
[openshift/origin-docker-registry]      5. Configure the failing repository to be skipped, if it is unavailable.
[openshift/origin-docker-registry]         Note that yum will try to contact the repo. when it runs most commands,
[openshift/origin-docker-registry]         so will have to try and fail each time (and thus. yum will be be much
[openshift/origin-docker-registry]         slower). If it is a very temporary problem though, this is often a nice
[openshift/origin-docker-registry]         compromise:
[openshift/origin-docker-registry]             yum-config-manager --save --setopt=origin-local-release.skip_if_unavailable=true
[openshift/origin-docker-registry] failure: repodata/repomd.xml from origin-local-release: [Errno 256] No more mirrors to try.
[openshift/origin-docker-registry] file:///srv/origin-local-release/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /srv/origin-local-release/repodata/repomd.xml"
[openshift/origin-docker-registry] running '/bin/sh -c export "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"; INSTALL_PKGS="origin-dockerregistry" &&     yum --enablerepo=origin-local-release install -y ${INSTALL_PKGS} &&     rpm -V ${INSTALL_PKGS} &&     yum clean all' failed with exit code 1
[ERROR] PID 19547: hack/lib/constants.sh:56: `return "${result}"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/constants.sh:56: `return "${result}"`
[INFO] 		  2: hack/build-images.sh:25: os::build::images
[INFO]   Exiting with code 1.
[ERROR] hack/build-images.sh exited with code 1 after 00h 00m 09s
make: *** [build-images] Error 1
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace

**Comment by simo5** [comment]
duplicate: #17985
