### ISSUE TITLE
Support Bitbucket Server as a Webhook Trigger

### ISSUE THREAD

**Issue by donovanmuller** [openshift/origin#17997]
Annoyingly, [Bitbucket](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html) and [Bitbucket Server](https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html) do not share the same event payload schemas/structures ([bitbucket.org](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html) vs. [Bitbucket Server](https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html)). Which means the [existing](https://docs.openshift.org/latest/dev_guide/builds/triggering_builds.html#bitbucket-webhooks) Bitbucket Webhook Trigger does not work with Bitbucket Server [webhooks](https://confluence.atlassian.com/bitbucketserver/managing-webhooks-in-bitbucket-server-938025878.html) (introduced in version [5.4](https://confluence.atlassian.com/bitbucketserver/bitbucket-server-5-4-release-notes-935388966.html#BitbucketServer5.4releasenotes-Webhooksarehere!)).

Given that many OpenShift installations would be on premise, it makes sense to support the on prem. version of Bitbucket, Bitbucket Server.

**Comment by donovanmuller** [comment]
Doh, ignore this. As usual, just after creating the issue I got it working 😬

Contrary to the [docs](https://docs.openshift.org/latest/dev_guide/builds/triggering_builds.html#bitbucket-webhooks) the `curl` header value for a [Push](https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html#Eventpayload-Push) is not `curl -H "X-Event-Key: repo:push" ...` but rather `curl -H "X-Event-Key: repo:refs_changed" ...`. The docs should probably be changed to:

```diff
--$ curl -H "X-Event-Key: repo:push" -H "Content-Type: application/json" -k -X POST --data-binary @payload.json https://<openshift_api_host:port>/oapi/v1/namespaces/<namespace>/buildconfigs/<name>/webhooks/<secret>/bitbucket
++$ curl -H "X-Event-Key: repo:refs_changed" -H "Content-Type: application/json" -k -X POST --data-binary @payload.json https://<openshift_api_host:port>/oapi/v1/namespaces/<namespace>/buildconfigs/<name>/webhooks/<secret>/bitbucket
```

**Comment by andreaseger** [comment]
just in case someone else stumbles upon this issue. Support for bitbucket server was apparently added in 3.7 https://bugzilla.redhat.com/show_bug.cgi?id=1500731
