### ISSUE TITLE
Login as system:admin through web console

### ISSUE THREAD

**Issue by BoZhaoUTSC** [openshift/origin#18009]
[provide a description of the issue]

##### Version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

Is there a way to login as system:admin through web console? I can login as system:admin by entering oc login -u system:admin.

Thanks!

**Comment by pweil-** [comment]
In practice you should be creating  users and granting them the correct administrative roles.  They could then log in via the console with the auth method you've configured for the cluster.  You should treat (and protect) system:admin and it's associated config/certificates as you would root on your servers.
