### ISSUE TITLE
Cleanup of unused secrets/service accounts

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#18014]
We have a bunch of unused secrets sitting in a namespace, some of which link back to an idle service account while other are orphaned. Is there a way to do a bulk-cleanup of all secrets (and probably service accounts) not used by any pod{,template}? Or at least something that shows me what do I need to have and what is idle?

@openshift/sig-master

**Comment by mfojtik** [comment]
@kargakis do you have some examples for those secrets?

**Comment by kargakis** [comment]
```
sinker-token-4p12j                       kubernetes.io/service-account-token   4         111d
sinker-token-565mp                       kubernetes.io/service-account-token   4         130d
sinker-token-bfczj                       kubernetes.io/service-account-token   4         111d
sinker-token-m87xz                       kubernetes.io/service-account-token   4         130d
$ oc get sa sinker
NAME      SECRETS   AGE
sinker    2         130d
```

**Comment by kargakis** [comment]
Not sure how the second set of secrets showed up. dockercfg secrets are also duplicate.

In terms of letting me know that I have idle secrets, I was thinking of a warning/info in `oc status`.

**Comment by mfojtik** [comment]
@kargakis this is 3.9/master ?

**Comment by mfojtik** [comment]
These secrets should be owned and pruned by the controller, right @deads2k ?

**Comment by kargakis** [comment]
> @kargakis this is 3.9/master ?

No, this is the CI cluster - `v3.7.0-rc.0+bd64aab-99`

**Comment by kargakis** [comment]
Maybe @openshift/sig-security folks are interested.

**Comment by liggitt** [comment]
> These secrets should be owned and pruned by the controller, right @deads2k ?

No. Those are secrets that can be used externally, rather than mounted into containers. If the service account was removed, those would be removed by the controller, but not otherwise.
