### ISSUE TITLE
Upgrade to 3.6.1 Fails during "Mark node unschedulable" - "(NotFound): nodes"

### ISSUE THREAD

**Issue by olsib** [openshift/origin#18018]
Upgrade from 1.5.1 to 3.6.1 fails

##### Version
# oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. Run ansible-playbook openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml

##### Current Result
TASK [Mark node unschedulable] **********************************************************************************************************************
FAILED - RETRYING: Mark node unschedulable (10 retries left).
FAILED - RETRYING: Mark node unschedulable (9 retries left).
FAILED - RETRYING: Mark node unschedulable (8 retries left).
FAILED - RETRYING: Mark node unschedulable (7 retries left).
FAILED - RETRYING: Mark node unschedulable (6 retries left).
FAILED - RETRYING: Mark node unschedulable (5 retries left).
FAILED - RETRYING: Mark node unschedulable (4 retries left).
FAILED - RETRYING: Mark node unschedulable (3 retries left).
FAILED - RETRYING: Mark node unschedulable (2 retries left).
FAILED - RETRYING: Mark node unschedulable (1 retries left).
fatal: [t1devocm1.XXXX.com -> t1devocm1.XXXXX.com]: FAILED! => {"attempts": 10, "changed": false, "msg": {"results": [{"cmd": "/usr/local/bin/oc get node ip-10-35-196-145.mdevlab.com -o json", "results": [{}], "returncode": 1, "stderr": "Error from server (NotFound): nodes \"ip-10-35-196-145.mdevlab.com\" not found\n", "stdout": ""}], "returncode": 1}}

##### Expected Result
Step succeeds
##### Additional Information
3 master (etcd embedded) + 2 worker node  Cluster -> Deployed on AWS

**Comment by php-coder** [comment]
CC @sdodson

**Comment by sdodson** [comment]
Can you get `oc get nodes` and also provide your nodes section from the inventory? Has a node gone missing?

**Comment by kargakis** [comment]
@openshift/sig-cluster-lifecycle 

(testing the bot)

**Comment by olsib** [comment]
ignore this, I re-cloned the right branch and I do not seem to get this.
