### ISSUE TITLE
OpenShift OAUTH2 server doesn't support userinfo endpoint

### ISSUE THREAD

**Issue by boeboe** [openshift/origin#18013]
I am trying to use OpenShift's build-in OAUTH2 server to delegate my GitLab Authentication towards OpenShift. However, the OpenShift's OAUTH2 server does not seem to support a **userinfo** endpoint, which is _unfortunately_ required by GitLab.

    "authorization_endpoint": "https://<master>/oauth/authorize"
    "token_endpoint": "https://<master>/oauth/token"
    "user_info_endpoint": "https://<master>/???"

I was wondering if a **userinfo** endpoint really doesn't exist, or is simply undocumented. Any plans to provide such an endpoint in the future, as some applications might require and/or benefit from this?

      option :client_options, { # Defaults are set for GitLab example implementation
        site: 'https://gitlab.com', # The URL for your OAuth 2 server
        user_info_url: '/api/v3/user', # The endpoint on your OAuth 2 server that provides user info for the current user
        authorize_url: '/oauth/authorize', # The authorization endpoint for your OAuth server
        token_url: '/oauth/token' # The token request endpoint for your OAuth server
      }

Some references / background information: 

- http://openid.net/specs/openid-connect-core-1_0.html#UserInfo
- https://gitlab.com/satorix/omniauth-oauth2-generic#gitlab-config-example
- https://gitlab.com/satorix/omniauth-oauth2-generic/blob/master/lib/omniauth/strategies/oauth2_generic.rb
- https://gitlab.com/gitlab-org/gitlab-ee/issues/4490

**Comment by enj** [comment]
It is unclear to me what exactly this user info endpoint is supposed to return (seems arbitrarily dynamic?).

If the entity contacting the endpoint can send a bearer token for the user (or otherwise correctly authenticate as the user to openshift), you can use the `~` user:

```
$ oc get --raw '/apis/user.openshift.io/v1/users/~' --loglevel=7 | jq
I0108 16:00:15.793163    4195 loader.go:357] Config loaded from file /home/.../.kube/config
I0108 16:00:15.793792    4195 round_trippers.go:414] GET https://...:8443/apis/user.openshift.io/v1/users/~
I0108 16:00:15.793802    4195 round_trippers.go:421] Request Headers:
I0108 16:00:15.793817    4195 round_trippers.go:424]     Accept: application/json, */*
I0108 16:00:15.793820    4195 round_trippers.go:424]     User-Agent: oc/v1.9.0 (linux/amd64) kubernetes/3258431
I0108 16:00:15.793826    4195 round_trippers.go:424]     Authorization: Bearer TOKEN
I0108 16:00:15.802233    4195 round_trippers.go:439] Response Status: 200 OK in 8 milliseconds
```

```json
{
  "kind": "User",
  "apiVersion": "user.openshift.io/v1",
  "metadata": {
    "name": "developer",
    "selfLink": "/apis/user.openshift.io/v1/users/developer",
    "uid": "179733ec-f4b2-11e7-baee-507b9dac97ff",
    "resourceVersion": "792",
    "creationTimestamp": "2018-01-08T20:25:39Z"
  },
  "identities": [
    "anypassword:developer"
  ],
  "groups": null
}
```

Does that work?

**Comment by simo5** [comment]
@boeboe does the comment from @enj help ?

**Comment by boeboe** [comment]
Hi @simo5 and @enj 

Sorry for the lat reply. In the meanwhile we have chosen to not deploy GitLab in OpenShift cluster, because there were more issues then just this one. As a result I do not have an easy setup/env anymore to test whether this would work or not.

Suggesting to close this issue but still some good points for someone that wants to try the same integration once GitLab did it's homework w.r.t. containerisation.

Thanks for pointing out to that ~ endpoint. I'll sure keep that in mind if I bump on this with other applications.

Kind regards,
Bart

**Comment by rikkuness** [comment]
From some of the implementations I've seen where it suggests an endpoint in "OpenID" format, although arbitrary it would seem one key field a lot of implementations look for is "email", but that's not really something you could have exposed in this context unless you spoofed it with something like `<metadata.name>@openshift.local`. Not ideal.

**Comment by enj** [comment]
The internal OAuth server in openshift does not implement the OpenID spec (it just does OAuth2) so I doubt we will ever support anything more than the `users ~` endpoint.  Using something like http://www.keycloak.org via the `OpenIDIdentityProvider` is a better solution for users that require the OpenID features.

**Comment by kardasa** [comment]
I found this issue report while trying to achive the same thing as @boeboe using OpenShift 3.9 enterprise - and failed. Just to update I tried to add  /oapi/v1/users/ as user info url and  /oapi/v1/users/~ and With the first end point Gitlab is displaying info as such:

**Comment by stratus-ss** [comment]
This is the same thing with grafana

https://community.grafana.com/t/auth-generic-oauth-no-id-token-found/19259/3

From @enj comments I assume this will never work as expected

**Comment by xakepp35** [comment]
@enj Rock into your garden for not conforming OIDC standart at lease in simpliest form. Thats very bad, because imagine you need username - for everyone you can just use regular openid flow, extracting it from a wellknown `sub` claim of a wellknown jwt format. But integrate that flow with openshift? No, you will have to write custom code paths, polluting a code with unknown endpoints `/apis/user.openshift.io/v1/users/~` and `UserV1AlphaBetaGamma123` structures from heavy client libraries.

is there a valid reason not serving jwt token in a standart format, with username, email, so on (as everyone do)? 
why you need to promote custom user structure over jwt, which everyone else have?
