### ISSUE TITLE
can-i is not checking for the valid verb and kind

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#18019]
This leads into:

```
$ oc policy can-i rule world
no
```

However, when I login as "system:admin" it seems like I can rule the world ;-).
@liggitt @enj not sure if this is an issue or this works as designed (as you can add more verbs? and with CRD you can have custom resource names). However, this might lead into typo bugs in scripts?

**Comment by liggitt** [comment]
that is working as designed. the authorization layer does not validate verbs and resource names
