### ISSUE TITLE
oc adm migrate fail on timeouts

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#18028]
Need to fail on timeouts, but try to do all resources.

Additionally we might need to override --include with --exclude but first find a good reason to add --exclude.

**Comment by mfojtik** [comment]
@enj FYI

**Comment by enj** [comment]
What?  It should _not_ fail on timeouts (server timeouts that is - they are safe to retry).  Also, it always tries all resources.

**Comment by enj** [comment]
@smarterclayton wanted `--exclude`, though I am not sure we really need it.

**Comment by mfojtik** [comment]
@enj this was coming from a trello card, was not sure what to do with it if something. If we don't need `--exclude` then we can close this issue. (the trello card did not had too much description, but I think you opened it ;-)

**Comment by enj** [comment]
@mfojtik I opened that card per a conversation with @smarterclayton.  We should sync up if we need such a flag (i.e. what is the use case for a customer).

**Comment by pweil-** [comment]
leaving it to you guys to sync up and close if necessary.  Thanks!

**Comment by simo5** [comment]
@mfojtik @enj can we close this one ?

**Comment by enj** [comment]
@smarterclayton any strong reason to add `--exclude`?  Seems like we always want people to run `--include=*` (which migrates everything it can and never quits early).  `--exclude` only makes sense if you have something you never want to migrate (which is an invalid scenario) or if you know migrate will fail because of some resource `x` (which is also invalid because we allow you to skip the migrate command during an upgrade if you so choose, and you can always run migrate out of band before and after upgrade).

**Comment by enj** [comment]
cc @sdodson @jupierce in case they have opinions.

**Comment by sdodson** [comment]
I think as long as we have a way to list the resources that would be included in `--include=*` we can build an --include to exclude anything we want. Are those resource types defined in the client or dynamically from the API?

Side though, How does migrate work when features like builds are disabled?

**Comment by enj** [comment]
@sdodson 

> I think as long as we have a way to list the resources that would be included in `--include=*` we can build an --include to exclude anything we want. Are those resource types defined in the client or dynamically from the API?

It is built using client side knowledge and discovery and is logged: https://github.com/openshift/origin/blob/master/pkg/oc/admin/migrate/migrator.go#L219

> Side though, How does migrate work when features like builds are disabled?

It should, though I have never tested such a thing.
