### ISSUE TITLE
Advanced install of cluster logging - parameter openshift_logging_image_version broken

### ISSUE THREAD

**Issue by Neikius** [openshift/origin#18029]
Advanced install of logging - specifying openshift_logging_image_version broken

Installing cluster logging via advanced install ansible script and specifying the parameter openshift_logging_image_version=v3.7 in host file. Script then tries to load openshift/oauth-proxy:v3.7 which does not exist (only v1.0.0 and v1.1.0) exist. This is specified in default_images.yml:
`__openshift_logging_elasticsearch_proxy_image_version: "{{openshift_logging_image_version | default('v1.0.0') }}"`

##### Version
oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://cloud.example.com:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
[root@openshift1 ~]# openshift version
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8

Using release-3.7 branch of ansible scripts.

##### Steps To Reproduce
1. Installed openshift origin using advanced install, multimaster, glusterfs, skipped logging
2. inventory file used when installing logging:
```
[OSEv3:children]
openshift_logging_storage_kind=dynamic
#  NOTE: this is seems wrong in docs, the default seems to be false while the docs claim this setting is true by default since v3.7
openshift_logging_install_logging=true
# NOTE: by default latest tag is taken, is this correct? Latest tag also produces a different result (albeit still not a success)
openshift_logging_image_version=v3.7
openshift_logging_es_pvc_dynamic=true
openshift_logging_es_pvc_size=50G
openshift_logging_es_number_of_replicas=1

# NOTE: this is not mentioned in docs at all, but rather in the error message you receive when you omit it
openshift_master_dynamic_provisioning_enabled=True
```
3. ansible-playbook -i ./hosts openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.yml

##### Current Result
oc describe logging-es-master-... shows that installing openshift/oauth-proxy:v3.7 is attempted and that image does not exist.

Not using the parameter seems to be OK, but the *latest* version of ES image is taken (not 3.7 as I would expect) by default and v1.0.0 of the proxy container.

edit: This probably belongs in https://github.com/openshift/openshift-ansible/issues, can this be moved?

**Comment by wdbasson** [comment]
There are only 2 versions available on dockerhub: v1.0.0 and v1.1.0.

**Comment by Neikius** [comment]
@wdbasson: I somehow managed to install it in the end by doing some ugly hacking. I didn't touch this setting in the end, since it proved to be pointless and just used :latest for ES and 1.0.0 which is the default for proxy.

**Comment by wdbasson** [comment]
@Neikius: I'm having a lot of trouble getting an EFK cluster up and running. I've opened a [issue](https://github.com/openshift/origin/issues/18107). Did you have similar problems?

**Comment by jcantrill** [comment]
Closing.  This should be logged against https://github.com/openshift/openshift-ansible/issues if still an issue.
