### ISSUE TITLE
oc set triggers should support update/replace option to update static ImageStreamTags

### ISSUE THREAD

**Issue by ankushchadha** [openshift/origin#18025]
The pain point is the steps involved in upgrading a containerized application. 

If dynamic ImageStreamTags such as latest, current, etc are used, then this problem doesn't exist. But if we want to use static ImageStreamTags such as 1.1, 1.2, etc, then there is no easy way to update the ImageStreamTag reference i.e. part of the ImageChange trigger (under DeploymentConfig)

So far, the option that I used is to write an upgrade function with following commands -

```

upgrade() {
 oc set triggers dc $1
 oc set triggers dc $1 --remove-all
 oc set triggers dc $1 --from-image=$1:$2 --containers=$1
 oc set triggers dc $1
}

export DC="microservice1 microservice2 microservice3"

for i in $DC; do
 upgrade $i $APP_TO_VERSION
done
     
```
The problem with this approach is the not ideal UX and also that have to preserve the value of the automated trigger of the ConfigChange trigger.

The other option is to use a patch but it doesn't work in updating the ImageChange trigger -
```
oc patch DeploymentConfig microservice1 -p '{"spec":{"triggers[1]": {"imageChangeParams": {"from": {"name": "microservice1:1.10"}}}}}'
```

##### Version
oc v3.6.173.0.83
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server xxxx
openshift v3.6.173.0.83
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Create an ImageStream object with static tag such as 1.10, 1.11 (1.10 imagestream tag points to 1.10 docker tag)
2. Create a DeploymentConfig object that includes an ImageChange trigger that points to this ImageStreamTag (1.10)
3. Attempt to upgrade the application from 1.10 to 1.11

##### Current Result
Upgrade works but the UX is not ideal. Why there should be a need to write a script to handle the updates of ImageStreamTags?

##### Expected Result
The ideal approach is to have an --update option as part of oc set triggers to allow updates of static ImageStreamTags to allow easier upgrades of microservices on OpenShift.

**Comment by mfojtik** [comment]
@juanvallejo @liggitt not sure if `--update` is the best option, how about overriding the existing trigger when oc set triggers is called? In that case we can warn that you are overriding existing config?

**Comment by juanvallejo** [comment]
@mfojtik 
> not sure if --update is the best option, how about overriding the existing trigger when oc set triggers is called? In that case we can warn that you are overriding existing config?

I am not sure I fully understand overwriting an existing trigger. Would a user specify the name of the trigger as part of the value of a new `--overwrite` flag? (e.g.):

```
$ oc set triggers dc/mydc --from-image my-image:v2 --overwrite=my-image:v1  --container=...
```

Or would we be replacing a previous `image` trigger, for example, if a new --from-image option is specified with an `--overwrite` flag?

**Comment by ankushchadha** [comment]
@mfojtik @juanvallejo - yes that can be an option. overwrite is better than an update.

In addition, if the `--from-image` points to the same image, then the ImageStreamTag should be overwritten by default. Not sure if there should be a `--force` or `--overwrite` option in this case. Are there use cases to have ImageTriggers with the same ImageStream but different ImageStream tags?

If we take a step back, the DeploymentConfig can point to -
1. Multiple initContainers to bootstrap a microservice
2. A single docker image i.e. the microservice via ImageStreamTags  (Is this a good assumption of referring a single docker image in DeploymentConfig?)

What does it mean to add new ImageTriggers and not overwrite existing one? Are there use cases to have multiple image triggers where -
1. ImageTrigger points to several docker images of multiple (dependent) microservices?
2. ImageTrigger points to different versions of the same microservice? (This is exactly the current behavior with no `--overwrite` flag and if old ImageTriggers are not cleaned up).

The use case is to update a containerized application by moving to a new static ImageStreamTag.

**Comment by mfojtik** [comment]
@juanvallejo there is usually just one trigger defined per container, so:

```
$ oc set triggers dc/mydc --from-image my-image:v2  --container=foo
```

should be enough? It will just override the existing image with new image. The trigger always override the container image when it 'triggers' (IOW. an image update happen).

**Comment by tnozicka** [comment]
> Are there use cases to have ImageTriggers with the same ImageStream but different ImageStream tags?

some generic images like centos you could have one container script based on centos:6 the other one on centos:7, or the same way with language runtimes like python 2.7, 3.0 in the same imagestream

I guess that break @mfojtik example as you might need to specify more containers

**Comment by mfojtik** [comment]
```
~/.../openshift/origin → oc get dc
NAME              REVISION   DESIRED   CURRENT   TRIGGERED BY
test-deployment   1          1         1         config,image(busybox:latest)
~/.../openshift/origin → oc set triggers dc/test-deployment --from-image=busybox:v1 -c test-deployment
deploymentconfig "test-deployment" updated
~/.../openshift/origin → oc get dc
NAME              REVISION   DESIRED   CURRENT   TRIGGERED BY
test-deployment   1          1         1         config,image(busybox:latest),image(busybox:v1)
~/.../openshift/origin → oc set triggers dc/test-deployment --from-image=busybox:v2 -c test-deployment
deploymentconfig "test-deployment" updated
~/.../openshift/origin → oc get dc
NAME              REVISION   DESIRED   CURRENT   TRIGGERED BY
test-deployment   1          1         1         config,image(busybox:latest),image(busybox:v1),image(busybox:v2)
```

This seems wrong to me. The intention here is clearly to set a new trigger for container "test-deployment" to a new image, but instead this command keep adding new triggers to the list.

What is the use-case for the current behavior? Do we expect users will have more then 1 trigger per 1 container? So when an image that is not the image the container runs currently is changed, we will trigger a deployment based on this image?

This will lead into unpredictable behavior as it is not clear which image the Pod will run at the end (whatever image will trigger first). I think this is a bug, but @smarterclayton can prove me wrong.

**Comment by tnozicka** [comment]
> I guess that breaks @mfojtik example as you might need to specify more containers

I was confused by writing `--container=foo` instead of `--containers`. It should work fine.

> What is the use-case for the current behavior? Do we expect users will have more then 1 trigger per 1 container? So when an image that is not the image the container runs currently is changed, we will trigger a deployment based on this image?

I agree that this should always overwrite if there is no case to be made for the current behaviour. Having more than 1 image trigger for 1 container looks like undefined behaviour to me.

**Comment by juanvallejo** [comment]
Sounds good to me. Will open PR to address this

**Comment by mfojtik** [comment]
@juanvallejo too late :) https://github.com/openshift/origin/pull/18120
