### ISSUE TITLE
Upgrade from 1.5.1 to v3.6 fails with "Storage backend in /etc/origin/master/master-config.yaml must be set to 'etcd3'"

### ISSUE THREAD

**Issue by olsib** [openshift/origin#18026]
I'm trying to upgrade to openshift origin v3.6 from openshift origin v1.5.1. 

##### Version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://t1.mdevlab.com:8443
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
Run:
ansible-playbook openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml

##### Current Result
TASK [fail] *****************************************************************************************************************************************
fatal: [t1devocm3.mdevlab.com]: FAILED! => {"changed": false, "msg": "Storage backend in /etc/origin/master/master-config.yaml must be set to 'etcd3' before the upgrade can continue"}
fatal: [t1devocm1.mdevlab.com]: FAILED! => {"changed": false, "msg": "Storage backend in /etc/origin/master/master-config.yaml must be set to 'etcd3' before the upgrade can continue"}
fatal: [t1devocm2.mdevlab.com]: FAILED! => {"changed": false, "msg": "Storage backend in /etc/origin/master/master-config.yaml must be set to 'etcd3' before the upgrade can continue"}
        to retry, use: --limit @/root/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.retry

PLAY RECAP ******************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0
t1devocm1.mdevlab.com      : ok=28   changed=0    unreachable=0    failed=1
t1devocm2.mdevlab.com      : ok=24   changed=0    unreachable=0    failed=1
t1devocm3.mdevlab.com      : ok=24   changed=0    unreachable=0    failed=1
t1devocn1.mdevlab.com      : ok=21   changed=0    unreachable=0    failed=0
t1devocn2.mdevlab.com      : ok=21   changed=0    unreachable=0    failed=0

Failure summary:

  1. Hosts:    t1devocm1.mdevlab.com, t1devocm2.mdevlab.com, t1devocm3.mdevlab.com
     Play:     Verify master processes
     Task:     fail
     Message:  Storage backend in /etc/origin/master/master-config.yaml must be set to 'etcd3' before the upgrade can continue

##### Expected Result
Suceed

**Comment by php-coder** [comment]
Looks like installer issue that should be reported at https://github.com/openshift/openshift-ansible

CC @sdodson
