### ISSUE TITLE
oc cluster up failed on Mac

### ISSUE THREAD

**Issue by WarnerHooh** [openshift/origin#18033]
oc cluster up failed on Mac

##### Version
oc v3.7.0+7ed6862

##### Steps To Reproduce
1. oc cluster up

##### Current Result
Starting OpenShift using openshift/origin:v3.7.0 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.7.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
FAIL
   Error: could not create OpenShift configuration
   Caused By:
     Error: Docker run error rc=139
     Details:
       Image: openshift/origin:v3.7.0
       Entrypoint: []
       Command: [start --images=openshift/origin-${component}:v3.7.0 --volume-dir=/var/lib/origin/openshift.local.volumes --dns=0.0.0.0:53 --write-config=/var/lib/origin/openshift.local.config --master=127.0.0.1 --hostname=localhost --public-master=https://127.0.0.1:8443]

##### Expected Result
local cluster to up

##### Additional Information

Does any one know about this issue? I have struggled with this for couple of days. Thanks a lot!

**Comment by spadgett** [comment]
@csrwng have you seen this?

**Comment by csrwng** [comment]
@WarnerHooh please try resetting your Docker data (you can find the option in the reset panel of the Docker preferences dialog). Also, what version of Docker are you using?

**Comment by WarnerHooh** [comment]
@csrwng @spadgett Problem solved as you said resetting Docker data. The docker version is Version 17.12.0-ce-mac45 (21669). Thank you so much for the quick turnaround. 🙂

**Comment by spadgett** [comment]
@WarnerHooh Glad to hear it's working

**Comment by rvm8h** [comment]
@csrwng  What is the line command for resetting Docker data ?

**Comment by spadgett** [comment]
@rvm8h Try Preferences -> Reset -> Remove all data
