### ISSUE TITLE
OpenShift: Regions and zones

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#1804]
Hi All,
     Any idea how bill be supported Regions and Zones, OpenShift will use Docker labels for regions and zones organizations ?

Thanks.

**Comment by brenton** [comment]
Hi, 

Take a look at our current scheduler documentation: http://docs.openshift.org/latest/dev_guide/scheduler.html.  Specifically look at the section titled "Affinity and Anti Affinity".  If you prefer you can watch a recent video one of the main developers recorded: https://www.youtube.com/watch?v=R5eHPk9YcRA&feature=youtu.be.
