### ISSUE TITLE
How can I delete an automatically generated environment variable?

### ISSUE THREAD

**Issue by jamespegg** [openshift/origin#18042]
I'm trying to deploy a Kafka REST Proxy image (confluentinc/cp-kafka-rest) which uses a specific set of environment variables to run correctly. The issue is that a few of the environment variables are deprecated within the application itself, however they are automatically added by Openshift / Kubernetes. In this specific image, it errors when "KAFKA_REST_PORT" gets passed in.

Setting the variable manually to an empty string stops the first error, but the application still tries to use it. I've also tried to remove the environment variable using the CLI : `oc set env deploymentconfigs/kafka-rest KAFKA_REST_PORT-`

Unfortunately this isn't the only time we've had problems with the automatically generated environment variables.

Is there any way to remove a specific generated environment variable from the deployment?

##### Version
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Deploy confluentinc/cp-kafka-rest image
2. Provide only the required / supported environment variables (KAFKA_REST_ZOOKEEPER_CONNECT & KAFKA_REST_HOST_NAME)

##### Current Result
Container crashes because KAFKA_REST_PORT environment variable has been automatically provided

##### Expected Result
Container does not error

**Comment by php-coder** [comment]
> Deploy confluentinc/cp-kafka-rest image

@jamespegg How do you deploy the image? Where did you get templates/pod definitions?

**Comment by jamespegg** [comment]
I was deploying the image directly from Docker Hub, although now I've had to update it to run as a different user to get around the permission model.

For the time being I've re-deployed all the images with different names so that the automatically generated environment variables don't clash with the variables that the image is expecting.
