### ISSUE TITLE
Need indication when consistently failing apps causing endless in console or cli

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#1805]
I had a Node.js app that failed on every startup, which caused a new container to be spun up about every 6 seconds and quickly consuming disk space and slow down the host.  It would be good if the console or cli provided some indication that this is happening.  For example in "osc status" or "osc get pods".

**Comment by jwforres** [comment]
there should be events happening for this, osc describe will render the events  @fabianofranz 

for the web console we were considering whether we might render events in the new sidebar pane that shows metadata for objects in the overview @liggitt

**Comment by smarterclayton** [comment]
Tied to https://github.com/GoogleCloudPlatform/kubernetes/pull/6361

**Comment by smarterclayton** [comment]
And https://github.com/GoogleCloudPlatform/kubernetes/issues/6014

**Comment by smarterclayton** [comment]
We don't even need events, ContainerStatus has last start time and restart count

**Comment by jwforres** [comment]
Wouldn't we want a little more info, seems like you want to know the number of restarts within a given timeframe.  I may not care if my pod had some issue 5 days ago but was now stable.

**Comment by smarterclayton** [comment]
Fixed upstream in https://github.com/GoogleCloudPlatform/kubernetes/pull/7116

**Comment by danmcp** [comment]
Anything left here?

**Comment by liggitt** [comment]
We still need to bubble container status up to the pod in the overview page.

**Comment by liggitt** [comment]
Sam, this is a good place to track showing an indication of problematic container status and/or container restart in the overview, and making sure the details pane for a pod prioritizes container status

**Comment by spadgett** [comment]
@smarterclayton What situations should we flag in the web console? I talked to @liggitt, and we considered the following:

1. Looping Container
  * Restart count > n
  * Recent last start time

1. Failed Container
  * Pod is running
  * Container is terminated

   Is this ever expected? Should we consider Pod `restartPolicy`?

1. Stuck Container
  * Pod is running
  * Container is waiting

  Is this ever expected?

I plan to flag pods with problems in the overview page and show detailed container state in the sidebar when you click a pod.

**Comment by liggitt** [comment]
> Recent last start time

maybe some delta after pod start time?

**Comment by smarterclayton** [comment]
Yeah, containers restarted recently should pop out to a user (not as an error, but as a note).

----- Original Message -----

**Comment by smarterclayton** [comment]
----- Original Message -----
> @smarterclayton What situations should we flag in the web console? I talked
> to @liggitt, and we considered the following:
> 
> 1. Looping Container
>   * Restart count > n
>   * Recent last start time
> 
> 1. Failed Container
>   * Pod is running
>   * Container is terminated
> 

Failed is possible, a failed restart policy always pod means something different than a failed run once pod.  A failed pod is "done" like a successful pod, so those phases / states are important to visually present.

>    Is this ever expected? Should we consider Pod `restartPolicy`?
> 
> 1. Stuck Container
>   * Pod is running
>   * Container is waiting

Pending > X time is important.

**Comment by derekwaynecarr** [comment]
It's helpful to refer to the following:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1724

A pod in failed phase is always failed and done forever and ever.

A pod with failed containers may or may not result in a failed phase depending on the restart policy.

Only way I could follow was that method, so its useful to reference.

**Comment by liggitt** [comment]
@spadgett looking at the godocs, I think I found one more scenario we should probably flag... a running container where `ready` is false even N minutes after `startedAt`... indicates a container that started, and has a readiness check, which is not passing. @smarterclayton is that a reasonable thing to surface as a potential problem?

**Comment by liggitt** [comment]
@spadgett I think `state.termination.exitCode != 0` is an indicator of whether a terminated container should be considered potentially problematic

**Comment by smarterclayton** [comment]
Absolutely.  Also, make sure there are good comments on these cases so we can copy them in the cli

**Comment by spadgett** [comment]
Another helpful link: [Life of a pod](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/pod-states.md) (Wasn't that a book by Yann Martel?)

Thoughts on the following? I plan to flag the pods somehow on the overview page.

**Scenario 1**

* Pod running
* Container restart count > 2
* Last started < 5 minutes ago

**Scenario 2**

* Pod running
* Container terminated
* Container exit code != 0
* Any restart policy

**Scenario 3**

* Pod running
* Container is waiting
* Pending > 5 minutes

**Scenario 4**

* Pod running
* Container running
* Container ready == false
* Container started > 5 minutes ago

**Comment by liggitt** [comment]
Scenario 1, 2, and 4 look pretty good to me, though I'd want someone better versed in container status to take a look as well.

Scenario 3 is important, but I'm not sure you have the data to compute "pending > 5 minutes". The container `waiting` state doesn't include a timestamp, nor does pod status. All you have left is the creationTimestamp of the pod itself, which is not a good indication of when the kubelet started trying to start the container.

**Comment by liggitt** [comment]
I wonder if you could do something clever with the container status lastState (if it exists) or the timestamps of peer container status objects (if they exist).

**Comment by smarterclayton** [comment]
> On May 14, 2015, at 8:03 PM, Jordan Liggitt <notifications@github.com> wrote:
> 
> Scenario 1, 2, and 4 look pretty good to me, though I'd want someone better versed in container status to take a look as well.
> 
> Scenario 3 is important, but I'm not sure you have the data to compute "pending > 5 minutes". The container waiting state doesn't include a timestamp, nor does pod status. All you have left is the creationTimestamp of the pod itself, which is not a good indication of when the kubelet started trying to start the container.
> 
Although technically if a pod hasn't been scheduled or started in 5 minutes that's also a problem.

**Comment by liggitt** [comment]
> Although technically if a pod hasn't been scheduled or started in 5 minutes that's also a problem.

Pods that aren't getting scheduled (`pod.status.phase == "Pending" && (now() - pod.metadata.creationTimestamp) > X minutes`?) is a good scenario to flag, albeit a separate one.

If it took a long time (e.g. 4:59) to schedule, but finally did, it feels weird to only give the container 1 second to start before we'll flag it again as worrisome.

**Comment by smarterclayton** [comment]
We may want to show the age of a pod in seconds / minutes when < 10 minutes when not in running.  Ie "pending 30s"
