### ISSUE TITLE
Feature Request: allow authentication against Github Enterprise

### ISSUE THREAD

**Issue by cringdahl** [openshift/origin#18084]
Feature Request: allow authentication against Github Enterprise

Please allow OAuth authentication against Github Enterprise. Would it be as simple as including a 'url' key inside the 'github' ident provider, then replacing 'github.com' with the value as a variable?

**Comment by soltysh** [comment]
@openshift/sig-security fyi

**Comment by enj** [comment]
We are already tracking this RFE in https://trello.com/c/1zmyNYYi

**Comment by enj** [comment]
@cringdahl I do not think this will be a lot of work, we just have not had the cycles to look into it.

**Comment by cringdahl** [comment]
@enj heh yeah, I see the origin date on that card :/

Someone should hand that to an intern, imo 😃
