### ISSUE TITLE
'Service "asb" is invalid' during ansible install

### ISSUE THREAD

**Issue by cringdahl** [openshift/origin#18083]
Running an advanced-install, the 'asb' service fails to create, thus halting the full ansible playbook.

##### Version
release-3.7.0day

##### Steps To Reproduce
`ansible-playbook -i path/to/config playbooks/byo/config.yml`

##### Current Result
    TASK [ansible_service_broker : create ansible-service-broker service] 
    *************************************************************
    Thursday 11 January 2018  10:22:14 -0800 (0:00:00.118)       1:26:58.264 ****** 
    fatal: [openshift-lab-01.example.com]: FAILED! => {"changed": false, "failed": true, "msg": 
    {"cmd": "/bin/oc replace -f /tmp/asb-KKqSyV -n openshift-ansible-service-broker", "results": {}, 
    "returncode": 1, "stderr": "The Service \"asb\" is invalid: spec.clusterIP: Invalid value: \"\": field is 
    immutable\n", "stdout": ""}}
##### Expected Result
Successful installation.

##### Additional Information
ansible config:

	# Create an OSEv3 group that contains the masters, nodes, and etcd groups
	[OSEv3:children]
	masters
	nodes
	etcd

	# hosts
	[OSEv3:vars]
	ansible_user=validuser
	ansible_become=true
	openshift_deployment_type=origin

	# root disks currently 14GB
	openshift_disable_check=disk_availability

	openshift_master_default_subdomain=openshift.example.com

	[masters]
	openshift-lab-01.example.com

	[etcd]
	openshift-lab-01.example.com

	[nodes]
	openshift-lab-01.example.com
	openshift-lab-02.example.com
	openshift-lab-03.example.com
	openshift-lab-04.example.com

**Comment by cringdahl** [comment]
Results of `ansible-worker -vvv`:

	TASK [ansible_service_broker : create ansible-service-broker service] *************************************************************
	task path: /Users/validuser/Code/openshift-ansible/roles/ansible_service_broker/tasks/install.yml:152
	Thursday 11 January 2018  12:37:35 -0800 (0:00:00.106)       0:09:25.252 ****** 
	Using module file /Users/validuser/Code/openshift-ansible/roles/lib_openshift/library/oc_obj.py
	<openshift-lab-01.example.com> ESTABLISH SSH CONNECTION FOR USER: validuser
	<openshift-lab-01.example.com> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=validuser -o ConnectTimeout=10 -o ControlPath=/Users/validuser/.ansible/cp/%h-%r openshift-lab-01.example.com '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-uijvtfsadoevqwtikhkqaittwrmnmbvp; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
	<openshift-lab-01.example.com> (1, '\n{"msg": {"returncode": 1, "cmd": "/bin/oc replace -f /tmp/asb-j6aoGH -n openshift-ansible-service-broker", "results": {}, "stderr": "The Service \\"asb\\" is invalid: spec.clusterIP: Invalid value: \\"\\": field is immutable\\n", "stdout": ""}, "failed": true, "invocation": {"module_args": {"files": null, "kind": "Service", "force": false, "name": "asb", "all_namespaces": null, "namespace": "openshift-ansible-service-broker", "delete_after": false, "kubeconfig": "/etc/origin/master/admin.kubeconfig", "content": {"path": "/tmp/asbsvcout", "data": {"kind": "Service", "spec": {"ports": [{"protocol": "TCP", "targetPort": 1338, "name": "port-1338", "port": 1338}], "selector": {"app": "openshift-ansible-service-broker", "service": "asb"}}, "apiVersion": "v1", "metadata": {"labels": {"app": "openshift-ansible-service-broker", "service": "asb"}, "namespace": "openshift-ansible-service-broker", "name": "asb", "annotations": {"service.alpha.openshift.io/serving-cert-secret-name": "asb-tls"}}}}, "state": "present", "debug": false, "selector": null}}}\n', '')
	fatal: [openshift-lab-01.example.com]: FAILED! => {
	    "changed": false, 
	    "failed": true, 
	    "invocation": {
	        "module_args": {
	            "all_namespaces": null, 
	            "content": {
	                "data": {
	                    "apiVersion": "v1", 
	                    "kind": "Service", 
	                    "metadata": {
	                        "annotations": {
	                            "service.alpha.openshift.io/serving-cert-secret-name": "asb-tls"
	                        }, 
	                        "labels": {
	                            "app": "openshift-ansible-service-broker", 
	                            "service": "asb"
	                        }, 
	                        "name": "asb", 
	                        "namespace": "openshift-ansible-service-broker"
	                    }, 
	                    "spec": {
	                        "ports": [
	                            {
	                                "name": "port-1338", 
	                                "port": 1338, 
	                                "protocol": "TCP", 
	                                "targetPort": 1338
	                            }
	                        ], 
	                        "selector": {
	                            "app": "openshift-ansible-service-broker", 
	                            "service": "asb"
	                        }
	                    }
	                }, 
	                "path": "/tmp/asbsvcout"
	            }, 
	            "debug": false, 
	            "delete_after": false, 
	            "files": null, 
	            "force": false, 
	            "kind": "Service", 
	            "kubeconfig": "/etc/origin/master/admin.kubeconfig", 
	            "name": "asb", 
	            "namespace": "openshift-ansible-service-broker", 
	            "selector": null, 
	            "state": "present"
	        }
	    }, 
	    "msg": {
	        "cmd": "/bin/oc replace -f /tmp/asb-j6aoGH -n openshift-ansible-service-broker", 
	        "results": {}, 
	        "returncode": 1, 
	        "stderr": "The Service \"asb\" is invalid: spec.clusterIP: Invalid value: \"\": field is immutable\n", 
	        "stdout": ""
	    }
	}

**Comment by sdodson** [comment]
> release-3.7.0day

Don't use that branch, use release-3.7 which continues to receive fixes.
Is your ASB already deployed?

/assign fabianvf

**Comment by cringdahl** [comment]
Using release-3.7, I get a different ASB error, which is, verbosely, this:

	fatal: [openshift-lab-01.example.com]: FAILED! => {
	    "changed": false, 
	    "failed": true, 
	    "invocation": {
	        "module_args": {
	            "all_namespaces": null, 
	            "content": {
	                "data": "apiVersion: servicecatalog.k8s.io/v1beta1\nkind: ClusterServiceBroker\nmetadata:\n  name: ansible-service-broker\nspec:\n  authInfo:\n    bearer:\n      secretRef:\n        kind: Secret\n        name: asb-client\n        namespace: openshift-ansible-service-broker\n  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0dmNHVnUKYzJocFpuUXRjMmxuYm1WeVFERTFNVFV4TVRBeE5UTXdIaGNOTVRnd01UQTBNak0xTlRVeldoY05Nak13TVRBegpNak0xTlRVMFdqQW1NU1F3SWdZRFZRUUREQnR2Y0dWdWMyaHBablF0YzJsbmJtVnlRREUxTVRVeE1UQXhOVE13CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNtZU05aUpxRDhxejJMOFlIRGFQMU0KTVpnSWswZzlZbE9ENzhpVFhYREpnWEdmeDJyYTcvVmpKcEdRdHZLTGZDOU96Rk81aXdHSjljYUN6c2JvcXFZcwowZ2krR3g1cnhWR0o5TGV3ZDFzVjRNSGJOQ2VPeUlrOFpqOFVSUS9qTUp1NmNRL01zYmRNRURoNitUUCtwTTFUCjhFbW1SQm9DVjBzdmZ2bkNuSDZ6RGsxeCtrTFN0ZjY3SW9hd1NzQkxMTi9UMzI4RUFWcTZQblNIMTRpUWNKTkkKOSt3blFEenFBRHVUL2RuUjJvVGNwWEpBc0o2UFVZNDFwazh6T1FTOC9DaHpDeUFhaHFLVDd6dUxmWlFJOG42VApFZ2l3WnpqVHBJZTEwOVdRZ1dLZ0ZiWk1mUExxOVp2cnBvNU5KVjFsazFlNTRKSi95VVpzOFk1RkxieGg2RCtOCkFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQld3dmcxMXp3bGJWN3NqaWFqaXl5dnhDNTlPWGdtQWRETEVXcnZXckZ5NTcxZQpHdlhDMkNveWZtck0vaTJ2Z0NxN28wYmEwVjY5aGpTNnRQdWc0UlUxUkk3TU1zdVEzMVRIUXZnY0hsamY3S2R1Ck9QOFdpVHIzOHMrWmpob3lkQnZ0TEZhZ243K3BtVkQzek8xMVYvRjYyWWE5NG95c3k5UUErVzZ5N3hoMnVPdTIKM0pBL1FyZnBocW1EZFpCbUJLTVZmZnVZVGwyenNaVmk2N2ZITnlKaHprNnBic2xRSjBVRHJBRW5zMTI5c01RWApZdk1ybFcrb1c1VUlUeEtEd1ZqUk9Oa1duZ1NhSTRVSDZ5TC9kQzE2ZmwwZWZhN2JyaTlTanRmdThwaVBFNXI5CndXRVRKOS9xa2xycG44UGUzMTdXL0RnMUFmRGFDNUJzTzIxbERYeTQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoKLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVRRd01nWURWUVFEREN0dmNHVnUKYzJocFpuUXRjMlZ5ZG1salpTMXpaWEoyYVc1bkxYTnBaMjVsY2tBeE5URTFNVEV3TVRVME1CNFhEVEU0TURFdwpOREl6TlRVMU5Gb1hEVEl6TURFd016SXpOVFUxTlZvd05qRTBNRElHQTFVRUF3d3JiM0JsYm5Ob2FXWjBMWE5sCmNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVFV4TlRFeE1ERTFORENDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBS29DZjBCc08wTWE4MlZuMFR4aUllNUYrR3ZUSTdaWmRHZXFabTBQWHpjKwpwOWd5eklRVEw0eVFQUHYrZi9XZzM3RWNuTVdQdVZnR2VEbVJ6R0ZZWm1wNmlmOGlvZ3BpNVI3Q0x5dGd4SnQ3Cm5jc1JSY0RCSFVNMk5aUFJTNWMyUWp2RjJVU2YzQU1neVVQSVBGU0trNkJGbUpyaE1SUzhWK1NXekU4ZEZnMEsKVXo2Y2ZUemdxS2RqUmxsRSs4M2syeGdDYXZyZmVKY2wxVE8rSm5UbjM2L1FTbTlMTFZtYVVrZXRjN2RxUnFrRwpxVzVvUUdISHdobWpIRGlSN2daVHBrNVFaZXkybGxLL1JyTlJvVkdCMEEyOGRsWlNycDdSS0lHNmZXYmtEWkx1CklId3VRbGh1VThuQjVoNUZkRWpWV243bGpVR3VGR1l1NXBhbDNlNkwvNmNDQXdFQUFhTWpNQ0V3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUUveQp1MDdDOFYydU43MTBCdHZLWTBOV0E3UWE0RU1oRkNpY3pyZkdVd0pLdUN2YlJnaWpQdnJGcys5SjZaNWNlczFrClh5T0svZmYyWjFhNG9qK1lES0tBbXlDZHBqZm10RzVDVXZkMWE2dzR3MUsrS2ZpbFZva3dtNDFvMldjTmVjUS8KZjF2MEp6MnVEaU5UR2VBcGVNb0QweGVObEtiL0tXL2Qvb0pub1htQWxsdFBTRk0rYmk1L29XekJEeWozWStxLwptejB3TmNMcmh5RG5qaTNPZHZOVEFzcGo4eDNVR2lLSlZMS3lYOVh6eFk2c0JqV3dqcEZMVUlaY1VGUUFFN1JSCnk4MjUxK2plWnBVdVEzSnVhRzlyTFRXY0ZMT1lkTWkveDhXK2VTNzdnR0RMUWpZZHMzTGpRc0R6WmMwS0tOM2sKSzJPRnZiMWVsMWd3NU1OK1NZaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=\n  url: https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker\n", 
	                "path": "/tmp/brokerout"
	            }, 
	            "debug": false, 
	            "delete_after": false, 
	            "files": null, 
	            "force": false, 
	            "kind": "ClusterServiceBroker", 
	            "kubeconfig": "/etc/origin/master/admin.kubeconfig", 
	            "name": "ansible-service-broker", 
	            "namespace": "default", 
	            "selector": null, 
	            "state": "present"
	        }
	    }, 
	    "msg": {
	        "cmd": "/bin/oc create -f /tmp/brokerout-EoZjCo -n default", 
	        "results": {}, 
	        "returncode": 1, 
	        "stderr": "error: unable to recognize \"/tmp/brokerout-EoZjCo\": no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker\n", 
	        "stdout": ""
	    }
	}

Here is the traceback:

	An error happened while generating a summary of failures:
	Traceback (most recent call last):
	  File "/Users/cringdahl/Code/openshift-ansible/roles/openshift_health_checker/callback_plugins/zz_failure_summary.py", line 49, in v2_playbook_on_stats
	    self._display.display(failure_summary(self.__failures, self.__playbook_file))
	  File "/Users/cringdahl/Code/openshift-ansible/roles/openshift_health_checker/callback_plugins/zz_failure_summary.py", line 86, in failure_summary
	    entries = format_failure(failure)
	  File "/Users/cringdahl/Code/openshift-ansible/roles/openshift_health_checker/callback_plugins/zz_failure_summary.py", line 183, in format_failure
	    (u'Message', stringc(msg, C.COLOR_ERROR)),
	  File "/usr/local/Cellar/ansible/2.3.1.0/libexec/lib/python2.7/site-packages/ansible/utils/color.py", line 91, in stringc
	    return "\n".join([u"\033[%sm%s\033[0m" % (color_code, t) for t in text.split('\n')])
	AttributeError: 'dict' object has no attribute 'split'

**Comment by taneem-ibrahim** [comment]
@cringdahl did you also notice x509 cert messages in the node log? This [PR](https://github.com/openshift/origin/issues/18083) might be relevant.

**Comment by cringdahl** [comment]
Unsure, I've reset the environment and gone to 3.6 since then. I can have a look.
