### ISSUE TITLE
Cluster up is broken on LinuxKit based Docker for Mac

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#18109]
I can see this using `oc cluster up` with `v3.9.0-alpha.2` and latest HEAD version of openshift:

```
  Type     Reason       Age               From                Message
  ----     ------       ----              ----                -------
  Normal   Scheduled    6m                default-scheduler   Successfully assigned test-1-deploy to localhost
  Warning  FailedMount  1m (x10 over 6m)  kubelet, localhost  MountVolume.SetUp failed for volume "deployer-token-49r5k" : exit status 1
  Warning  FailedMount  1m (x2 over 3m)   kubelet, localhost  Unable to mount volumes for pod "test-1-deploy_myproject(d67a427b-f9e9-11e7-bc52-025000000001)": timeout expired waiting for volumes to attach/mount for pod "myproject"/"test-1-deploy". list of unattached/unmounted volumes=[deployer-token-49r5k]
```

There is nothing special about this deployment or setup, the container is stuck in `ContainerCreating` state. 

I can see this in master log:

```
I0115 11:55:36.185268   18230 reconciler.go:262] operationExecutor.MountVolume started for volume "deployer-token-g4sg9" (UniqueName: "kubernetes.io/secret/900ecc5c-f9e9-11e7-bc52-025000000001-deployer-token-g4sg9") pod "router-1-deploy" (UID: "900ecc5c-f9e9-11e7-bc52-025000000001")
I0115 11:55:36.185376   18230 secret.go:186] Setting up volume deployer-token-g4sg9 for pod 900ecc5c-f9e9-11e7-bc52-025000000001 at /var/lib/origin/openshift.local.volumes/pods/900ecc5c-f9e9-11e7-bc52-025000000001/volumes/kubernetes.io~secret/deployer-token-g4sg9
I0115 11:55:36.188747   18230 nsenter_mount.go:168] Failed findmnt command for path /var/lib/origin/openshift.local.volumes/pods/900ecc5c-f9e9-11e7-bc52-025000000001/volumes/kubernetes.io~secret/deployer-token-g4sg9: exit status 1
I0115 11:55:36.191493   18230 nsenter_mount.go:168] Failed findmnt command for path /var/lib/origin/openshift.local.volumes/pods/900ecc5c-f9e9-11e7-bc52-025000000001/volumes/kubernetes.io~secret/deployer-token-g4sg9: exit status 1
I0115 11:55:36.191549   18230 empty_dir.go:264] pod 900ecc5c-f9e9-11e7-bc52-025000000001: mounting tmpfs for volume wrapped_deployer-token-g4sg9
E0115 11:55:36.193728   18230 nestedpendingoperations.go:263] Operation for "\"kubernetes.io/secret/900ecc5c-f9e9-11e7-bc52-025000000001-deployer-token-g4sg9\" (\"900ecc5c-f9e9-11e7-bc52-025000000001\")" failed. No retries permitted until 2018-01-15 11:57:38.193695802 +0000 UTC m=+761.957148542 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"deployer-token-g4sg9\" (UniqueName: \"kubernetes.io/secret/900ecc5c-f9e9-11e7-bc52-025000000001-deployer-token-g4sg9\") pod \"router-1-deploy\" (UID: \"900ecc5c-f9e9-11e7-bc52-025000000001\") : exit status 1"
```

EDIT: This is caused by a recent updated of Docker for Mac (Version 17.12.0-ce-mac47-stable) which brings a new VM based on LinuxKit that dropped some of the binaries required by nsenter. As a consequence the `oc cluster up` will not work on OSX.

**Comment by mfojtik** [comment]
(I guess it would be useful to show the output of the command that is failing, not just exit code?)

**Comment by mfojtik** [comment]
@smarterclayton are we missing the `findmnt` command in the alpha-2 release images See: https://github.com/kubernetes/kubernetes/pull/58284

**Comment by mfojtik** [comment]
@smarterclayton K, so the command is there, but the error suggests the `PATH` is wrong?

**Comment by mfojtik** [comment]
@smarterclayton @deads2k seems like we missed https://github.com/openshift/origin/pull/3168 during rebase? 

(shame to Clayton for not following our commit message rules and the verification seemed not to catch this)

**Comment by mfojtik** [comment]
hrm, it seems like it will search in `/rootfs/usr/bin/findmt` according to https://github.com/mfojtik/origin/blob/9e98436e109dc2e39022748ff09f86f9d41868c7/vendor/k8s.io/kubernetes/pkg/util/nsenter/nsenter.go#L90

Not sure what the `/rootfs/` here is, but it seems to be failing for me on OSX Docker.

**Comment by mfojtik** [comment]
OK, this seems to be OSX specific I guess... The `/rootfs/usr/bin/` does not include `findmnt` (and other binaries) anymore. I guess they were removed from the Docker VM ?

**Comment by mfojtik** [comment]
@csrwng this means the `cluster up` for Docker on Mac is now broken (starting from Version 17.12.0-ce-mac46 (21698))

**Comment by mfojtik** [comment]
Filled https://github.com/docker/for-mac/issues/2433

**Comment by mfojtik** [comment]
@bparees FYI (I know that devexp does not own the cluster up for now, but in case people will start asking)

**Comment by csrwng** [comment]
@mfojtik this is actually caused by cluster up not correctly figuring whether it should be using the nsenter mounter. I recently submitted a PR to fix this https://github.com/openshift/origin/pull/18052. Can you please try with oc compiled from master and see if you can reproduce?

**Comment by mfojtik** [comment]
@csrwng will check thanks

**Comment by mfojtik** [comment]
@csrwng right, this fixed it... But I wonder if we really need a special case for non-RH docker here.

**Comment by mfojtik** [comment]
Closing this as @csrwng patch seems to fix the issue for `cluster up`.
