### ISSUE TITLE
Validate resource types in bootstrap policy

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#1811]
It is possible to fat-finger resource names when creating bootstrap policy (c.f. https://github.com/liggitt/origin/commit/1aacef2a319455bd520ba0fcd7e279bf11b7b126#diff-1d38b34f638332aebf97978ff71d9664R153). We should probably validate the named resources are known.

**Comment by fabianofranz** [comment]
@liggitt still an issue?

**Comment by deads2k** [comment]
> @liggitt still an issue?

Yes, still an issue.
