### ISSUE TITLE
openshift-master-api does not shut down gracefully

### ISSUE THREAD

**Issue by aliscott** [openshift/origin#18131]
Stopping origin-master-api using `systemctl stop origin-master-api` does not do it gracefully on a multi-master cluster. Internal references to the kubernetes service endpoint can fail to connect for several seconds following this.

It can take up to 15s for the endpoints in the kubernetes service to be reconciled to remove the stopped master.

Should the endpoint be removed before stopping the `origin-master-api` service?

##### Version
```
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
etcd 3.2.1
```

**Comment by ironcladlou** [comment]
Closing due to age. Pretty sure graceful shutdown was solved in one way for 3.9 and of course the apiserver and control plane were switched to self-hosted components, so I doubt this issue still applies.
