### ISSUE TITLE
Downward API volume should update labels on modification

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#18136]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18074/test_pull_request_origin_extended_conformance_install/5696/

Happens frequently

@openshift/sig-storage 
/kind test-flake

**Comment by sosiouxme** [comment]
Is this different from https://github.com/openshift/origin/issues/17882 ?

**Comment by dcbw** [comment]
> Is this different from #17882 ?

Looks like the same one...

**Comment by mfojtik** [comment]
Attempted fix: https://github.com/openshift/origin/pull/18444.

The other failure related to downward api seemed to be fixed in https://github.com/openshift/origin/pull/18387, maybe this one will be same.
