### ISSUE TITLE
Update the vendor package 'github.com/containers/storage'

### ISSUE THREAD

**Issue by louyihua** [openshift/origin#18153]
Currently, openshift has a reference to the deprecated package `github.com/docker/engine-api` **only** from the vendor package 'github.com/containers/storage'. This package is updated recently to remove the dependency of this deprecated package. Maybe it is the time to update this package, so that openshift can also eliminate the reference to the deprecated package `github.com/docker/engine-api`.

**Comment by mfojtik** [comment]
@rhatdan FYI
