### ISSUE TITLE
oc login does not honor --request-timeout option

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#18159]
Try to log into a cluster that is not up, e.g. 127.0.0.2

```
$ time oc login https://127.0.0.2:8443 -u developer --request-timeout=1s
error: dial tcp 127.0.0.2:8443: i/o timeout - verify you have provided the correct host and port and that the server is currently running.

real	0m30.145s
user	0m0.156s
sys	0m0.031s
```

Even though I've set a 1s timeout, it takes 30s to fail

##### Version
oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

**Comment by juanvallejo** [comment]
This was originally patched in https://github.com/openshift/origin/pull/12062
Will take a look

**Comment by juanvallejo** [comment]
@jorgemoralespou I can't seem to replicate this using the same version of the client.

```
➜ time oc login https://127.0.0.2:8443 -u developer --request-timeout=1s
error: dial tcp 127.0.0.2:8443: getsockopt: connection refused - verify you have provided the correct host and port and that the server is currently running.
oc login https://127.0.0.2:8443 -u developer --request-timeout=1s  0.17s user 0.02s system 126% cpu 0.150 total
```
```
➜ oc version
oc v3.7.0+7ed6862-dirty
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth
```

Any chance you could post `--loglevel 8` output / your kubeconfig contents?

**Comment by jorgemoralespou** [comment]
@juanvallejo I'm on Mac, maybe that makes a difference. Will post log web
back on computer on Monday.

**Comment by juanvallejo** [comment]
@jorgemoralespou friendly ping

**Comment by jorgemoralespou** [comment]
@juanvallejo sorry for taking so long, I missed the notification. I've tried with a clean install. No kubeconfig

All of the below, are using the macOS clients.

```
export KUBECONFIG=/tmp/config
time oc-origin login https://127.0.0.2:8443 -u developer --request-timeout=1s --loglevel=8
I0216 19:47:11.673205    4035 loader.go:357] Config loaded from file /Users/jmorales/.kube/config
I0216 19:47:11.673801    4035 round_trippers.go:383] HEAD https://127.0.0.2:8443/
I0216 19:47:11.673815    4035 round_trippers.go:390] Request Headers:
I0216 19:47:41.675635    4035 round_trippers.go:408] Response Status:  in 30001 milliseconds
I0216 19:47:41.675669    4035 round_trippers.go:411] Response Headers:
F0216 19:47:41.675747    4035 helpers.go:120] error: dial tcp 127.0.0.2:8443: i/o timeout - verify you have provided the correct host and port and that the server is currently running.

real	0m30.150s
user	0m0.165s
sys	0m0.033s
```
I've tried with:
```
$ oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth
```
and
```
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth
```
and
```
oc v3.7.23
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth
```
and
```
oc v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth
```

All giving me the same behaviour. 30s timeout.

**Comment by juanvallejo** [comment]
@jorgemoralespou no problem, thanks for posting that log output. From what I can see, the 30-second delay is happening when we make the HEAD request, to see if the server can even be reached. Although we set a timeout value in the restclient config we use to obtain a round-tripper, that value ultimately does not appear to be relayed to the round tripper that ends up making the request here: https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/login/helpers.go#L77

[I have put together a PR to address this](https://github.com/openshift/origin/pull/18651). Please try it out locally, and let me know if it does solve the problem.

Thanks

**Comment by jorgemoralespou** [comment]
@juanvallejo can you build/attach a client built for this PR for
darwin/Mac. I can't build origin. Or point to the ci server location for
the binary, if there's one.

**Comment by shilpa481** [comment]
I am still seeing this issue. 

I am running minishift (minishift v1.34.1+c2ff9cb), openshift-origin-client-tools-v3  on Mac Mojave 10.14.6 
Minishift & Minikube are running
When I try oc login I get this error. error: dial tcp 192.168.99.115:8443: i/o timeout - verify you have provided the correct host and port and that the server is currently running
I have cleaned up, restarted-no luck.

Currently using:
minishift v1.34.1+c2ff9cb
minikube version: v1.3.1
openshift v3
