### ISSUE TITLE
Strange error when getting logs for terminating pod

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#18173]
3.9 master, using json-file driver with docker 1.12.6-68

I had just deleted this pod.  I get this when I call logs briefly

```
$ oc logs -n kube-system sts/prometheus -c prometheus
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
```

@openshift/sig-pod

**Comment by smarterclayton** [comment]
I'll move this to a bug if this isn't already known

**Comment by smarterclayton** [comment]
@sjenning if you can have someone at your team look at this - not sure what we're doing wrong, but looks broken.

**Comment by sjenning** [comment]
@joelsmith PTAL

**Comment by sjenning** [comment]
xref https://bugzilla.redhat.com/show_bug.cgi?id=1537237

**Comment by smarterclayton** [comment]
I *think* I opened a bug, but can't find the tab anymore.

**Comment by joelsmith** [comment]
Upstream issued filed here: https://github.com/kubernetes/kubernetes/issues/59296
Upstream PR posted here: https://github.com/kubernetes/kubernetes/pull/59297
