### ISSUE TITLE
bump disk storage capacity for ami used with build/image_ecosystem extended tests

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#18190]
First, apologies if the quantity of labels is a negative ... wanted to make sure it had the right exposure (and all the colors are pretty :-) )

Opening as part of my hand off as devexp extended test runner from last sprint at @bparees request.

Per recent communications between @stevekuznetsov , @bparees , @pweil- , and myself, we've started seeing a fair amount of image pruning during the build and image_ecosystem nightly runs.

While some of that pruning was misguided because images used by sandboxes were getting pruned (@sjenning just had a k8s PR merge for this which will be picked into origin soon), generally speaking any image pruning during the middle of the build and image_ecosystem runs (which in large part are creating images) will flake if the image is removed in the middle of the test.

image pruning currently cannot be turned off at the k8s layer

So we need a bump in the ami's storage to avoid pruning activity.

The relevant subset of the `docker info` the extended test runs:
```
Server Version: 1.12.6
Storage Driver: devicemapper

 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data Space Total: 26 GB
 Metadata Space Total: 37.75 MB


```

**Comment by sjenning** [comment]
Pick from upstream to protect the sandbox image from imageGC
https://github.com/openshift/origin/pull/18189

**Comment by stevekuznetsov** [comment]
Should be addressed by https://github.com/openshift/origin-ci-tool/commit/57be583045146475fee46cb31233ead39d1c95f0

Launching new AMI jobs to get the updated images now

**Comment by stevekuznetsov** [comment]
Should be fixed

```
$ curl http://169.254.169.254/latest/meta-data/ami-id
ami-d93f0fa3
$ pvs
  PV         VG     Fmt  Attr PSize   PFree 
  /dev/xvdb1 docker lvm2 a--  <50.00g 21.00g
$ vgs
  VG     #PV #LV #SN Attr   VSize   VFree 
  docker   1   2   0 wz--n- <50.00g 21.00g
$ lvs
  LV                    VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker-pool           docker twi-a-t--- <13.90g             21.66  0.99                            
  openshift-xfs-vol-dir docker -wi-ao---- <15.00g                                                    
```
