### ISSUE TITLE
missing service/route (service "webconsole" not found)

### ISSUE THREAD

**Issue by queer** [openshift/origin#18207]
After applying the workaround suggested in #14766, I get this issue when connecting to the origin container at `https://ip:8443/`. 

##### Version
```
[root@host origin]# openshift version
openshift v3.9.0-alpha.3+3fefaa2-90
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.8
```

##### Steps To Reproduce
1. Run `openshift/origin` with the exact command listed in the docs.
2. Wait a few minutes for it to come up
3. Attempt to go to `https://ip:8443/`

##### Current Result

Error from the title:
```
missing service (service "webconsole" not found)
missing route (service "webconsole" not found)
```

##### Expected Result

I get the web console.

##### Additional Information

I don't get this using `openshift/origin:v3.7.1`.

**Comment by siddharthjoshi745** [comment]
I am running openshift origin in a container and i can see the same message on my browser.
missing service (service "webconsole" not found)
missing route (service "webconsole" not found)

Openshift origin service seems to run on the correct port. 
[root@master ~]# netstat -nlp | grep 8443
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      12622/openshift

But somehow console is not working. 
Any resolution yet?

**Comment by PhilipGough** [comment]
Seeing this also on MacOSX with `oc cluster up`

**Comment by mindfury** [comment]
Same result as well.

**Comment by arbhoj** [comment]
Are you using the docker based quick start for Openshift? If yes then this looks like a bug with the current build. Try with an older build. e.g.:
sudo docker run -d --name "origin" \
        --privileged --pid=host --net=host \
        -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
        -v /var/lib/docker:/var/lib/docker:rw \
        -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave \ 
        openshift/origin:v3.7.1 start

**Comment by mindfury** [comment]
That works, thanks for the tip!

**Comment by spadgett** [comment]
Note that in 3.9, the web console no longers runs as part of the master. It runs in a pod in the openshift-web-console namespace. oc cluster up and openshift-ansible will both install the console for you.

If you run OpenShift a different way, you'll have to instantiate the console template. Edit install/origin-web-console/console-config.yaml for your cluster and run

```
$ oc create namespace openshift-web-console
$ oc process -f install/origin-web-console/console-template.yaml -p "API_SERVER_CONFIG=$(cat install/origin-web-console/console-config.yaml)" | oc apply -n openshift-web-console -f -
```

**Comment by spadgett** [comment]
I've added these instructions to the origin-web-console-server README. We might link to that somewhere from the origin repo.

https://github.com/openshift/origin-web-console-server#installing-the-console

Let me they work for you.

**Comment by spadgett** [comment]
Closing per my comments above.  #18680 adds a better error page when the console is not installed.

/close

**Comment by cdancy** [comment]
> If yes then this looks like a bug with the current build. Try with an older build.

Is there an open BUG/ISSUE to track this when starting with docker containers? For devs coming across the [INSTALL SECTION](https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container) they are going to be a bit confused as to why things are not working properly.

**Comment by spadgett** [comment]
@cdancy Thanks for pointing this out. I opened an issue: https://github.com/openshift/openshift-docs/issues/8088

We'll get that updated.

**Comment by cdancy** [comment]
@spadgett awesome and thanks. We just picked up a story to start playing around with origin and I've been banging my head the past couple hours trying to figure out why things were not working though the doc clearly states it should.

**Comment by spadgett** [comment]
@cdancy Sure. I'd recommend downloading oc 3.7 and running `oc cluster up`. It should be a better first experience. I don't think the topic you link will install a router or registry either, but cluster up will.

https://github.com/openshift/origin/releases/tag/v3.7.0
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md

**Comment by cdancy** [comment]
Using 3.7.0 does indeed work. Yeah I'd rather a pure docker experience if at all possible so I don't have to worry about installing additional dependencies and can easily wire up a gradle script say with the [gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) and get going fairly easily.
