### ISSUE TITLE
No xpaas template showed on admin console

### ISSUE THREAD

**Issue by lanliu99** [openshift/origin#18203]
After successfully created is/jboss-webserver30-tomcat7-openshift and template/jws31-tomcat7-basic-s2i, no template was showed on master:8443->browse catalog->middleware

language template (such as java, http server, ruby...) can be seen.

##### Version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://master.exampledis.com:8443
openshift v3.7.9
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
open http://https://master.exampledis.com:8443/console/
go to browse catalog->middleware, nothing there.
but under languages tab, several icons were showed there.

##### Current Result
```console
$ oc describe is jboss-webserver30-tomcat7-openshift_new2
Name:                   jboss-webserver30-tomcat7-openshift_new2
Namespace:              openshift
Created:                2 hours ago
Labels:                 <none>
Annotations:            openshift.io/display-name=Red Hat JBoss Web Server 3.0 Apache Tomcat 7
                        openshift.io/image.dockerRepositoryCheck=2018-01-20T11:08:48Z
                        openshift.io/provider-display-name=Red Hat, Inc.
                        version=1.4.7
Docker Pull Spec:       172.30.133.49:5000/openshift/jboss-webserver30-tomcat7-openshift_new2
Image Lookup:           local=false
Unique Images:          1
Tags:                   1

1.3
  tagged from registry.exampledis.com/jboss-webserver-3/webserver30-tomcat7-openshift:1.3

  JBoss Web Server 3.0 Apache Tomcat 7 S2I images.
  Tags: builder, tomcat, tomcat7, java, jboss, hidden
  Supports: tomcat7:3.0, tomcat:7, java:8
  Example Repo: https://github.com/jboss-openshift/openshift-quickstarts.git

  * registry.exampledis.com/jboss-webserver-3/webserver30-tomcat7-openshift@sha256:0111a7e7f901e4bbc8289e87bc470c33ba6d48cf36cdb93571801e8dc262cbad
      2 hours ago
$ oc describe template jws31-tomcat7-basic-s2i
Name:           jws31-tomcat7-basic-s2i
Namespace:      openshift
Created:        About an hour ago
Labels:         <none>
Description:    Application template for JWS applications built using S2I.
Annotations:    iconClass=icon-rh-tomcat
                openshift.io/display-name=JBoss Web Server 3.1 Apache Tomcat 7 (no https)
                openshift.io/provider-display-name=Red Hat, Inc.
                tags=tomcat,tomcat7,java,jboss
                version=1.4.7

Parameters:
    Name:               APPLICATION_NAME
    Display Name:       Application Name
    Description:        The name for the application.
    Required:           true
    Value:              jws-app

    Name:               HOSTNAME_HTTP
    Display Name:       Custom http Route Hostname
    Description:        Custom hostname for http service route.  Leave blank for default hostname, e.g.: <application-name>-<project>.<default-domain-suffix>
    Required:           false
    Value:              <none>

    Name:               SOURCE_REPOSITORY_URL
    Display Name:       Git Repository URL
    Description:        Git source URI for application
    Required:           true
    Value:              https://github.com/jboss-openshift/openshift-quickstarts.git

    Name:               SOURCE_REPOSITORY_REF
    Display Name:       Git Reference
    Description:        Git branch/tag reference
    Required:           false
    Value:              1.2

    Name:               CONTEXT_DIR
    Display Name:       Context Directory
    Description:        Path within Git project to build; empty for root project directory.
    Required:           false
    Value:              tomcat-websocket-chat

    Name:               JWS_ADMIN_USERNAME
    Display Name:       JWS Admin Username
    Description:        JWS Admin User
    Required:           true
    Generated:          expression
    From:               [a-zA-Z0-9]{8}

    Name:               JWS_ADMIN_PASSWORD
    Display Name:       JWS Admin Password
    Description:        JWS Admin Password
    Required:           true
    Generated:          expression
    From:               [a-zA-Z0-9]{8}

    Name:               GITHUB_WEBHOOK_SECRET
    Display Name:       Github Webhook Secret
    Description:        GitHub trigger secret
    Required:           true
    Generated:          expression
    From:               [a-zA-Z0-9]{8}

    Name:               GENERIC_WEBHOOK_SECRET
    Display Name:       Generic Webhook Secret
    Description:        Generic build trigger secret
    Required:           true
    Generated:          expression
    From:               [a-zA-Z0-9]{8}

    Name:               IMAGE_STREAM_NAMESPACE
    Display Name:       ImageStream Namespace
    Description:        Namespace in which the ImageStreams for Red Hat Middleware images are installed. These ImageStreams are normally installed in the openshift namespace. You should only need to modify this if you've installed the ImageStreams in a different namespace/project.
    Required:           true
    Value:              openshift

    Name:               MAVEN_MIRROR_URL
    Display Name:       Maven mirror URL
    Description:        Maven mirror to use for S2I builds
    Required:           false
    Value:              <none>

    Name:               ARTIFACT_DIR
    Description:        List of directories from which archives will be copied into the deployment folder. If unspecified, all archives in /target will be copied.
    Required:           false
    Value:              <none>


Object Labels:  template=jws31-tomcat7-basic-s2i,xpaas=1.4.7

Message:        A new JWS application for Apache Tomcat 7 has been created in your project. The username/password for administering your JWS is ${JWS_ADMIN_USERNAME}/${JWS_ADMIN_PASSWORD}.

Objects:
    Service             ${APPLICATION_NAME}
    Route               ${APPLICATION_NAME}
    ImageStream         ${APPLICATION_NAME}
    BuildConfig         ${APPLICATION_NAME}
    DeploymentConfig    ${APPLICATION_NAME}
```

##### Expected Result
templates for tomcat image should be there  under browser catalog->middleware

##### Additional Information
Could this be an issue of my subscription on the hosts?
```console
[root@node1 ~]# subscription-manager list --available --matches '*OpenShift*'
No available subscription pools were found matching the expression "*OpenShift*".
```

**Comment by php-coder** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
@lanliu99 which project did you create the imagestream and templates in?  you should be creating them in the openshift namespace.

**Comment by jim-minter** [comment]
To load the template, I'm doing:
```
oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/jboss-image-streams.json -n openshift
oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws31-tomcat7-basic-s2i.json -n openshift
```
If I've already got the console open, I find that I need to press F5 to refresh it before the Tomcat template image appears.  @spadgett ?

Note that the images in jboss-image-streams.json don't show up as builders in the console because they are marked as hidden.

**Comment by spadgett** [comment]
> If I've already got the console open, I find that I need to press F5 to refresh it before the Tomcat template image appears.

Yeah, this is expected. We don't watch templates since they don't change often (and I don't think watch is supported for the templates resource?)

**Comment by lanliu99** [comment]
I always press F5 after I created a new template in openshift namespace, could this be an issue of my subscription on the hosts?

[root@node1 ~]# subscription-manager list --available --matches '*OpenShift*'
No available subscription pools were found matching the expression "*OpenShift*".

**Comment by bparees** [comment]
no, subscriptions are not causing this.

@spadgett what tags/annotation must a template have for it to show up under "middleware"?

**Comment by lanliu99** [comment]
I used another browser, it doesn't help.
I can use this template to new-app, but can not see it on screen, only language(java, php, etc.) templates are shown on http://master.example.com:8443  -> browse catalog 
I can get the template from -n openshift as the following:
$ oc describe template jws31-tomcat7-mysql-persistent-s2i-new -n openshift
error: You must be logged in to the server (the server has asked for the client to provide credentials (get templates jws31-tomcat7-mysql-persistent-s2i-new))

lanliu@LANLIU-GPS-REDHAT MINGW64 ~
$

lanliu@LANLIU-GPS-REDHAT MINGW64 ~
$

lanliu@LANLIU-GPS-REDHAT MINGW64 ~
$ oc login -u admin -p redhat https://master.exampledis.com:8443
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    hello
  * jws-app
    kube-public
    kube-system
    logging
    management-infra
    myservlet2
    openshift
    openshift-infra
    openshift-node
    test1

Using project "jws-app".

lanliu@LANLIU-GPS-REDHAT MINGW64 ~
$ oc describe template jws31-tomcat7-mysql-persistent-s2i-new -n openshift
Name:           jws31-tomcat7-mysql-persistent-s2i-new
Namespace:      openshift
Created:        About an hour ago
Labels:         <none>
Description:    An example JBoss Web Server application with a MySQL database. For more information about using this template, see https://github.com/jboss-openshift/application-templates.
Annotations:    iconClass=icon-rh-tomcat
                openshift.io/display-name=Red Hat JBoss Web Server 3.1 Apache Tomcat 7 + MySQL (with https)
                openshift.io/provider-display-name=Red Hat, Inc.
                tags=tomcat,tomcat7,java,jboss
                template.openshift.io/documentation-url=https://access.redhat.com/documentation/en/red-hat-jboss-web-server/
                template.openshift.io/long-description=This template defines resources needed to develop Red Hat JBoss Web Server 3.1 Apache Tomcat 7 based application, including a build configuration, application deployment configuration, database deployment configuration for MySQL using persistence and secure communication using https.
                template.openshift.io/support-url=https://access.redhat.com
                version=1.4.7

Parameters:
    Name:               APPLICATION_NAME
    Display Name:       Application Name
    Description:        The name for the application.
    Required:           true
    Value:              jws-app

    Name:               HOSTNAME_HTTP
    Display Name:       Custom http Route Hostname
    Description:        Custom hostname for http service route.  Leave blank for default hostname, e.g.: <application-name>-<project>.<default-domain-suffix>
    Required:           false
    Value:              <none>

    Name:               HOSTNAME_HTTPS
    Display Name:       Custom https Route Hostname
    Description:        Custom hostname for https service route.  Leave blank for default hostname, e.g.: secure-<application-name>-<project>.<default-domain-suffix>
    Required:           false
    Value:              <none>

    Name:               SOURCE_REPOSITORY_URL
    Display Name:       Git Repository URL
    Description:        Git source URI for application
    Required:           true
    Value:              https://github.com/jboss-openshift/openshift-quickstarts

    Name:               SOURCE_REPOSITORY_REF
    Display Name:       Git Reference
    Description:        Git branch/tag reference
    Required:           false
    Value:              1.2

    Name:               CONTEXT_DIR
    Display Name:       Context Directory
    Description:        Path within Git project to build; empty for root project directory.
    Required:           false
    Value:              todolist/todolist-jdbc

    Name:               DB_JNDI
    Display Name:       Database JNDI Name
    Description:        Database JNDI name used by application to resolve the datasource, e.g. jboss/datasources/mysqlDS
    Required:           false
    Value:              jboss/datasources/defaultDS

    Name:               DB_DATABASE
    Display Name:       Database Name
    Description:        Database name
    Required:           true
    Value:              root

    Name:               VOLUME_CAPACITY
    Display Name:       Database Volume Capacity
    Description:        Size of persistent storage for database volume.
    Required:           true
    Value:              512Mi

    Name:               DB_MIN_POOL_SIZE
    Display Name:       Datasource Minimum Pool Size
    Description:        Sets xa-pool/min-pool-size for the configured datasource.
    Required:           false
    Value:              1

    Name:               DB_MAX_POOL_SIZE
    Display Name:       Datasource Maximum Pool Size
    Description:        Sets xa-pool/max-pool-size for the configured datasource.
    Required:           false
    Value:              3

    Name:               DB_TX_ISOLATION
    Display Name:       Datasource Transaction Isolation
    Description:        Sets transaction-isolation for the configured datasource.
    Required:           false
    Value:              <none>

    Name:               MYSQL_LOWER_CASE_TABLE_NAMES
    Display Name:       MySQL Lower Case Table Names
    Description:        Sets how the table names are stored and compared.
    Required:           false
    Value:              <none>

    Name:               MYSQL_MAX_CONNECTIONS
    Display Name:       MySQL Maximum number of connections
    Description:        The maximum permitted number of simultaneous client connections.
    Required:           false
    Value:              10

    Name:               MYSQL_FT_MIN_WORD_LEN
    Display Name:       MySQL FullText Minimum Word Length
    Description:        The minimum length of the word to be included in a FULLTEXT index.
    Required:           false
    Value:              <none>

    Name:               MYSQL_FT_MAX_WORD_LEN
    Display Name:       MySQL FullText Maximum Word Length
    Description:        The maximum length of the word to be included in a FULLTEXT index.
    Required:           false
    Value:              <none>

    Name:               MYSQL_AIO
    Display Name:       MySQL AIO
    Description:        Controls the innodb_use_native_aio setting value if the native AIO is broken.
    Required:           false
    Value:              <none>

    Name:               DB_USERNAME
    Display Name:       Database Username
    Description:        Database user name
    Required:           true
    Generated:          expression
    From:               user[a-zA-Z0-9]{2}

    Name:               DB_PASSWORD
    Display Name:       Database Password
    Description:        Database user password
    Required:           true
    Generated:          expression
    From:               [a-zA-Z0-9]{5}

    Name:               JWS_ADMIN_USERNAME
    Display Name:       JWS Admin Username
    Description:        JWS Admin User
    Required:           true
    Generated:          expression
    From:               [a-zA-Z0-9]{5}

    Name:               JWS_ADMIN_PASSWORD
    Display Name:       JWS Admin Password
    Description:        JWS Admin Password
    Required:           true
    Generated:          expression
    From:               [a-zA-Z0-9]{5}

    Name:               GITHUB_WEBHOOK_SECRET
    Display Name:       Github Webhook Secret
    Description:        GitHub trigger secret
    Required:           true
    Generated:          expression
    From:               [a-zA-Z0-9]{3}

    Name:               GENERIC_WEBHOOK_SECRET
    Display Name:       Generic Webhook Secret
    Description:        Generic build trigger secret
    Required:           true
    Generated:          expression
    From:               [a-zA-Z0-9]{3}

    Name:               IMAGE_STREAM_NAMESPACE
    Display Name:       ImageStream Namespace
    Description:        Namespace in which the ImageStreams for Red Hat Middleware images are installed. These ImageStreams are normally installed in the openshift namespace. You should only need to modify this if you've installed the ImageStreams in a different namespace/project.
    Required:           true
    Value:              openshift

    Name:               MAVEN_MIRROR_URL
    Display Name:       Maven mirror URL
    Description:        Maven mirror to use for S2I builds
    Required:           false
    Value:              http://192.168.56.109:8091/nexus/content/groups/public/

    Name:               ARTIFACT_DIR
    Description:        List of directories from which archives will be copied into the deployment folder. If unspecified, all archives in /target will be copied.
    Required:           false
    Value:              <none>

    Name:               MYSQL_IMAGE_STREAM_TAG
    Display Name:       MySQL Image Stream Tag
    Description:        The tag to use for the "mysql" image stream.  Typically, this aligns with the major.minor version of MySQL.
    Required:           true
    Value:              5.5


Object Labels:  template=jws31-tomcat7-mysql-persistent-s2i,xpaas=1.4.7

Message:        A new persistent JWS application for Apache Tomcat 7 (using MySQL) has been created in your project. The username/password for administering your JWS is ${JWS_ADMIN_USERNAME}/${JWS_ADMIN_PASSWORD}. For accessing the MySQL database "${DB_DATABASE}" use the credentials ${DB_USERNAME}/${DB_PASSWORD}. Please be sure to create the "jws-service-account" service account.

Objects:
    Service                     ${APPLICATION_NAME}
    Service                     ${APPLICATION_NAME}-mysql
    Route                       ${APPLICATION_NAME}
    Route                       secure-${APPLICATION_NAME}
    ImageStream                 ${APPLICATION_NAME}
    BuildConfig                 ${APPLICATION_NAME}
    DeploymentConfig            ${APPLICATION_NAME}
    DeploymentConfig            ${APPLICATION_NAME}-mysql
    PersistentVolumeClaim       ${APPLICATION_NAME}-mysql-claim

**Comment by jim-minter** [comment]
I am unable to recreate this issue on origin or ose v3.7.9 (which you indicate you're running).
```
oc cluster up --version=v3.7.9
oc login -u system:admin
oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws31-tomcat7-mysql-persistent-s2i.json -n openshift
```

"Red Hat JBoss Web Server 3.1 Apache Tomcat 7 + MySQL" icon is present in console under Middleware / Runtimes & Frameworks.

**Comment by spadgett** [comment]
@lanliu99 Are you using the template service broker? If so, there's a 15 minute re-list interval. You can force it to relist with `oc edit clusterservicebroker template-service-broker` and incrementing `relistRequests`

**Comment by lanliu99** [comment]
Thanks, I don't think I am using service broker, this issue happened for days.

**Comment by spadgett** [comment]
@lanliu99 Just following up to make sure this is still an issue. Do you have the problem with any other middleware templates or just this one? Are you using the same template as @jim-minter in his comment above? https://github.com/openshift/origin/issues/18203#issuecomment-359462064

**Comment by lanliu99** [comment]
@spadgett the template can be found under openshift project, but not in the home page, seems it needs some extra attentions to make it displayed on home page, but making them appeared under openshift project had solved my issue, thanks for your attention.
