### ISSUE TITLE
Missing default serviceaccount, roles, rolebinding for every new project after upgrading from 3.6 to 3.7

### ISSUE THREAD

**Issue by davistran86** [openshift/origin#18206]
I'm using multi master cluster with origin 3.6
I upgraded to 3.7 using command

```
ansible-playbook -i <path/to/inventory/file> \
    </path/to/upgrade/playbook>
```

After sucess upgrading it to 3.7 I got errors and cannot deploy new project because of missing role binding. Every new project created is missing rolebinding, roles, default serviceaccount

```
oc get rolebinding.rbac -n test-role
**No resources found.**
```

![image](https://user-images.githubusercontent.com/23651625/35204480-f54d8d5e-ff60-11e7-8ad8-0fad97a502e7.png)

I also tried commands below but nothing works:

```
# oadm policy reconcile-cluster-roles \
    --additive-only=true \
    --confirm

# oadm policy reconcile-cluster-role-bindings \
    --exclude-groups=system:authenticated \
    --exclude-groups=system:authenticated:oauth \
    --exclude-groups=system:unauthenticated \
    --exclude-users=system:anonymous \
    --additive-only=true \
    --confirm

```

**Comment by php-coder** [comment]
@simo5 @enj Looks like RBAC-related. Is it something related to our area or it's about upgrade mechanism?

**Comment by simo5** [comment]
@php-coder sounds like a 3.6 master with the policy controller is still running and actively deleting all RBAC that are created by 3.7 masters, to keep them consistent with it's view of the world (3.6 policy controller considers only 3.6 policy authoritative and syncs RBAC to conform to it).

**Comment by php-coder** [comment]
For the record: https://github.com/openshift/openshift-ansible/issues/6787 (the same issue but for the installer).

**Comment by davistran86** [comment]
hi guys,
Is there any command to recreate (fix) them for whole cluster ? 
Every new project will have no default serviceaccount and roles, and I also see them using old 3.6.1 deployer image for S2I,

Thanks alot.

**Comment by enj** [comment]
@davistran86 looks like you have a partial upgrade (mixed 3.6 and 3.7 components).  You need to downgrade everything back to 3.6 (restore a backup).  Then run `oc adm migrate authorization` and report its output.

**Comment by davistran86** [comment]
@enj thanks, I will try it :)

**Comment by davistran86** [comment]
hi @enj this is what I got ( I restored from snapshot not backup though):
summary (dry run): total=209 errors=0 ignored=0 unchanged=209 migrated=0

**Comment by enj** [comment]
@davistran86 what is the output of `oc version` run against each of your masters now?

**Comment by davistran86** [comment]
@enj Hi, this is what I got: 
```
[root@origin-etcd1 ~]# oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.aavn.local:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

[root@origin-etcd2 ~]# oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.aavn.local:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

[root@origin-etcd3 ~]# oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.aavn.local:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
```

**Comment by enj** [comment]
@davistran86 ok run `oc adm migrate authorization` again and confirm no errors.  Also make sure the controllers you are running are version 3.6 as well (check the RPM version probably).

Once that is done, make a backup, and upgrade to 3.7 again (make sure no changes are made to the cluster during upgrade).  Then check that every component is restarted and upgraded to 3.7 (clients, server, controllers, nodes, etc).
