### ISSUE TITLE
Failed to create container (Pod error 'CrashLoopBackOff')

### ISSUE THREAD

**Issue by MichalDuma** [openshift/origin#18213]
I try to get the pod running in Openshift. I used 2 Docker images: CentOS base and Ubuntu. None of them successfully got up. I keep getting the error 'CrashLoopBackOff'. After some time it changes the state into 'Error'. Logs show nothing and 'oc describe' still shows 'Error syncing pod'.

All steps are taken as system:admin under the default project. To avoid the privileges issues I added the following command:
'oc adm policy add-scc-to-user anyuid -z default'
 
##### Version
[root@master imagebase]# oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.openshift.me:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
[root@master imagebase]# openshift version
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
etcd 3.2.1
[root@master imagebase]# 

##### Steps To Reproduce
1. docker pull openshift/base-centos7
2. oc new-app --docker-image=openshift/base-centos7 --name=test300

##### Current Result
# oc get pods
NAME               READY     STATUS             RESTARTS   AGE
test300-1-deploy   1/1       Running            0          14s
test300-1-ggpnj    0/1       CrashLoopBackOff   1          13s

##### Expected Result
POD up and running

##### Additional Information
I also created Dockerfile with additional user but it didn't help.
With some other images it was working fine.

**Comment by mfojtik** [comment]
When the container is in CrashLoop, can you see the container logs via `oc logs pod/test300-1-ggpnj` ?

Additionally can you describe the pod? `oc describe pod/test300-1-ggpnj` ? That should reveal the events.

**Comment by MichalDuma** [comment]
@mfojtik - thank you for answer. 
`oc logs pod/test300-1-ggpnj` doesn't show anything
`oc describe pod/test300-1-ggpnj` gives a lot of output. In my opinion "error syncing pod" is the most interesting (but whole output I attached to this issue)
[pod-test300.txt](https://github.com/openshift/origin/files/1658943/pod-test300.txt)

**Comment by pweil-** [comment]
```
Containers:
  test300:
    Container ID:	docker://df26bbfcae954d1a5faff2030847ac4bd3dfac103db35d6584426db6470be920
    Image:		openshift/base-centos7@sha256:aea292a3bddba020cde0ee83e6a45807931eb607c164ec6a3674f67039d8cd7c
```

You're trying to run a base image.  There is no long running command that would keep this container alive.  To be specific, if you `docker run` that image you'll get:

```
$ docker run openshift/base-centos7 
This image serves as the base image for all OpenShift v3 S2I builder images.
It provides all essential libraries and development tools needed to
successfully build and run an application.

To use this image as a base image, you need to have 's2i/bin' directory in the
same directory as your S2I image Dockerfile. This directory should contain S2I
scripts.

This base image also provides the default user you should use to run your
application. Your Dockerfile should include this instruction after you finish
installing software:

USER default

The default directory for installing your application sources is
'/opt/app-root/src' and the WORKDIR and HOME for the 'default' user is set
to this directory as well. In your S2I scripts, you don't have to use absolute
path, but rather rely on the relative path.

To learn more about S2I visit: https://github.com/openshift/source-to-image
```
and the container will exit which is what is happening in your environment.  You can see from the output that your container completed with exit code 0:

```
   Last State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Mon, 04 Dec 2017 19:13:58 +0100
      Finished:		Mon, 04 Dec 2017 19:13:58 +0100
```
