### ISSUE TITLE
aws node bootstrapping fails with default instance hostname

### ISSUE THREAD

**Issue by abutcher** [openshift/origin#18222]
Nodes provisioned with default hostnames (eg `uname -n` returns `ip-172-31-49-88`) are unable to register.

I'm following [openshift-ansible AWS provisioning](https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/README.md) which starts nodes with a bootstrap kubeconfig.

Bootstrapped nodes generate a CSR and the CN of the certificate request matches the default instance hostname.

```
# oc get csr node-csr-3-UnJQOB3rVCxInQ-gGISkUB5xXH29w9AumPZgV2J3I -o yaml | awk '/request:/ { print $2 }' | base64 -d | openssl req -noout -text | grep CN=
        Subject: O=system:nodes, CN=system:node:ip-172-31-49-88
```

After approving certificate requests, node configs are laid down in which nodename is the default instance hostname and the node is unable to register.

```
Jan 22 20:37:35 ip-172-31-49-88.ec2.internal origin-node[5087]: E0122 20:37:35.856352    5087 kubelet_node_status.go:106] Unable to register node "ip-172-31-49-88.ec2.internal" with API server: nodes "ip-172-31-49-88.ec2.internal" is forbidden: node "ip-172-31-49-88" cannot modify node "ip-172-31-49-88.ec2.internal"
```

Additionally, at some point after the node service is started (~30 minutes), nodes will begin to create CSRs with their FQDN (eg `ip-172-31-49-88.ec2.internal`) because the hostname of the system has been updated (`uname -n` now reports `ip-172-31-49-88.ec2.internal`). I'm not sure if the node is responsible for changing the hostname but it changes without any input from me. Nodes with fully qualified hostnames start and register without a problem.

```
# oc get csr
NAME                                                   AGE       REQUESTOR                                                 CONDITION
node-csr-DOxrsHGgwdET1p0xQfTh0H5puJxhvctbdkq9knGwjVE   1m        system:serviceaccount:openshift-infra:node-bootstrapper   Pending
node-csr-EgQlwhD92OsjXZWlfr8afz6mdxPonoE8p26wnnzeCkE   31m       system:serviceaccount:openshift-infra:node-bootstrapper   Pending
node-csr-Od7vTTxG5EaaGcg0nnrfiOxCzY1Js2wyvwmDNygvTe8   1m        system:serviceaccount:openshift-infra:node-bootstrapper   Pending
node-csr-So11V8ySgzw4BejRnFlKyYWUaPmpNWd5y64blx2n2nE   31m       system:serviceaccount:openshift-infra:node-bootstrapper   Pending
node-csr-Zr9-syAZkLLTH0YiOdzzW-dyf2ZIKi4PCVJjiB1otsI   1m        system:serviceaccount:openshift-infra:node-bootstrapper   Pending
node-csr-atDnlRb735YlrfpdS0Uitw8Cj3VDRIdeoO-ILrGWLNk   31m       system:serviceaccount:openshift-infra:node-bootstrapper   Pending
node-csr-e3RwkiIXS7f9m_mN_-t7yBG-J_QQMQG9K8TZzOFf-HU   31m       system:serviceaccount:openshift-infra:node-bootstrapper   Pending
node-csr-ePGK0q_wW5LY8HZZAdox8mEE-T4V5CCCXplLUgEN3hQ   31m       system:serviceaccount:openshift-infra:node-bootstrapper   Pending
node-csr-sVTpaop8Lsb9q0iCoEBKQ5OtwyWUBCXl66WXrqeMlZk   1m        system:serviceaccount:openshift-infra:node-bootstrapper   Pending


# for csr in `oc get csr --no-headers | awk '{ print $1 }'`; do oc get csr $csr -o yaml | awk '/request:/ { print $2 }' | base64 -d | openssl req -noout -text | grep CN=; done
        Subject: O=system:nodes, CN=system:node:ip-172-31-60-113.ec2.internal
        Subject: O=system:nodes, CN=system:node:ip-172-31-55-174.ec2.internal
        Subject: O=system:nodes, CN=system:node:ip-172-31-54-182.ec2.internal
        Subject: O=system:nodes, CN=system:node:ip-172-31-49-39
        Subject: O=system:nodes, CN=system:node:ip-172-31-49-39.ec2.internal
        Subject: O=system:nodes, CN=system:node:ip-172-31-54-182
        Subject: O=system:nodes, CN=system:node:ip-172-31-60-113
        Subject: O=system:nodes, CN=system:node:ip-172-31-52-209
        Subject: O=system:nodes, CN=system:node:ip-172-31-52-209.ec2.internal
```

/cc @kwoodson and @smarterclayton who thought this may be related to a recent rebase

##### Version
oc v3.9.0-alpha.2+673e0be-78
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Provision cluster in AWS following https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/README.md

**Comment by smarterclayton** [comment]
My worry is that we lost something in the rebase with regards to hostname
handling.  Looking at the current code, node name should have been honored
by the kubelet.

**Comment by smarterclayton** [comment]
I don't see how this ever worked (the cloud provider overrides the hostname we provide).  I think we're going to have to stop setting NodeName, but not sure who else that might break.

**Comment by DanyC97** [comment]
@abutcher how does your inventory file looks in terms of the master/ nodes groups ?

**Comment by abutcher** [comment]
@DanyC97 I'm provisioning masters and nodes as I go so the [inventory](https://github.com/openshift/openshift-ansible/blob/06f8c2176bcd810112f0d8c4c5ec577620e948c9/playbooks/aws/provisioning-inventory.example.ini) is pretty minimal. Nodes are provisioned using a prepared AMI w/ [userdata ](https://github.com/openshift/openshift-ansible/blob/06f8c2176bcd810112f0d8c4c5ec577620e948c9/roles/openshift_aws/templates/user_data.j2#L23-L26) that: 
* ensures the hostname (`sysctl kernel.hostname`) is the FQDN of the instance
* drops a kubeconfig containing a token for bootstrapping
* starts and enables the node service

**Comment by DanyC97** [comment]
cheers @abutcher . I was asking cause i'm hitting https://github.com/openshift/openshift-ansible/issues/5692 

Unfortunately i cannot use the internal generated hostnames (too cryptic for day2ops + breaks apps service discovery) .
If i get to the bottom of it, will update

**Comment by bjwschaap** [comment]
/remove-lifecycle stale
Any updates on this issue? I'm hitting the same problem..
