### ISSUE TITLE
Need docs for cluster role aggregation

### ISSUE THREAD

**Issue by enj** [openshift/origin#18232]
@deads2k you added the feature, add the docs as well.

@openshift/sig-security

**Comment by enj** [comment]
I do not care if you just copy https://kubernetes.io/docs/admin/authorization/rbac/#aggregated-clusterroles into our docs, but I don't want more of https://bugzilla.redhat.com/show_bug.cgi?id=1537426

**Comment by deads2k** [comment]
> I do not care if you just copy https://kubernetes.io/docs/admin/authorization/rbac/#aggregated-clusterroles into our docs, but I don't want more of https://bugzilla.redhat.com/show_bug.cgi?id=1537426

@ahardin-rh the docs already exist upstream.  Can you do the copy?



> @deads2k you added the feature, add the docs as well.

@enj You sort of get lucky on this one, but in general anyone can add new features and @openshift/sig-security ends up owning them (including whatever docs you want).
