### ISSUE TITLE
Flake: no route to host from service to pod IP test

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#18258]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18254/test_pull_request_origin_extended_conformance_gce/14885/

```
    stderr:
    wget: can't connect to remote host (172.30.155.166): No route to host
    command terminated with exit code 1
```

But there is error logging in the test now

@openshift/networking

**Comment by danwinship** [comment]
dup of #14385. current best guess is a race condition in kube-proxy but I'd forgotten to dig in further
