### ISSUE TITLE
error: error converting YAML to JSON: yaml: line 311: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by IBM-Ronnie** [openshift/origin#18257]
Hi,

Source: https://github.com/openshift/origin/blob/release-3.6/examples/quickstarts/cakephp-mysql.json

When I try to execute oc create -f https://github.com/openshift/origin/blob/release-3.6/examples/quickstarts/cakephp-mysql.json -n openshift to add the cakephp-mysql this template to my own project in Openshift origin v3.7, the linux throws the error, "error: error converting YAML to JSON: yaml: line 311: mapping values are not allowed in this context".

Could someone help me to solve it?

Thanks in advance.

**Comment by php-coder** [comment]
@openshift/sig-developer-experience

**Comment by php-coder** [comment]
@IBM-Ronnie What OpenShift version you are using? `oc version` output could be helpful.

**Comment by jim-minter** [comment]
Please do `oc create -f https://raw.githubusercontent.com/openshift/origin/release-3.6/examples/quickstarts/cakephp-mysql.json -n openshift`.

**Comment by IBM-Ronnie** [comment]
@php-coder First, thanks for your feedback.
# oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

Thanks

**Comment by bparees** [comment]
@IBM-Ronnie did you see @jim-minter's solution to your problem?

**Comment by IBM-Ronnie** [comment]
@jim-minter I try your command in my own environment, but it showed this template was existed in server.
However, I can not find this template in the browse catalog of the project. It's strange. 
Sorry, I am junior on Openshift Origin, maybe this kind of question is easy...
And one more question, how can I import the jenkins, gitlab, nexus etc. Devops tools to Openshift Origin v3.7.....
Thanks.
And thanks for your reminder @bparees

**Comment by bparees** [comment]
> However, I can not find this template in the browse catalog of the project. It's strange.

@spadgett another case of a user loading templates and them not showing up in browse catalog...

> And one more question, how can I import the jenkins, gitlab, nexus etc. Devops tools to Openshift Origin v3.7.....

@IBM-Ronnie not sure what you mean.  How to load the templates for these things?  How to deploy them?
