### ISSUE TITLE
Intermittent resolve failure for heketi-storage-glusterfs.router.default.svc.cluster.local causing more volume created than requested in glusterfs

### ISSUE THREAD

**Issue by plmnko** [openshift/origin#18275]
When creating pvc of glusterfs with heketi, there is intermittent resolve failure for name **heketi-storage-glusterfs.router.default.svc.cluster.local**. However, heketi did receive the rest call, and created a volume, but pv_controller retried the volume creation, and causing more volume created than requested. 

`Jan 24 18:28:53 master1 origin-master-controllers[28766]: I0124 18:28:53.872676   28766 glusterfs.go:708] glusterfs: got gid [2001] for PVC zookeeper-pvc`

`Jan 24 18:28:53 master1 origin-master-controllers[28766]: I0124 18:28:53.872954   28766 glusterfs.go:775] glusterfs: create volume of size: 1073741824 bytes and configuration {url:http://heketi-storage-glusterfs.router.default.svc.cluster.local user:admin userKey: secret
Namespace:glusterfs secretName:heketi-storage-admin-secret secretValue:KKuuOusOYi0Epaa9saL3uVhVmKnYI8I4nlyzUV2b9rM= clusterID: gidMin:2000 gidMax:2147483647 volumeType:{Type:replicate Replicate:{Replica:3} Disperse:{Data:0 Redundancy:0}}}`

`Jan 24 18:28:53 master1 origin-master-controllers[28766]: E0124 18:28:53.877594   28766 glusterfs.go:793] glusterfs: error creating volume Get http://heketi-storage-glusterfs.router.default.svc.cluster.local/queue/c79dd21c5a1a3c95aed9117bee6e5e6d: dial tcp: lookup heketi
-storage-glusterfs.router.default.svc.cluster.local: no such host`

`Jan 24 18:28:53 master1 origin-master-controllers[28766]: E0124 18:28:53.878204   28766 glusterfs.go:716] glusterfs: create volume err: error creating volume Get http://heketi-storage-glusterfs.router.default.svc.cluster.local/queue/c79dd21c5a1a3c95aed9117bee6e5e6d: dial
 tcp: lookup heketi-storage-glusterfs.router.default.svc.cluster.local: no such host.`

`Jan 24 18:28:53 master1 origin-master-controllers[28766]: I0124 18:28:53.878497   28766 pv_controller.go:1338] failed to provision volume for claim "default/zookeeper-pvc" with StorageClass "glusterfs-storage": glusterfs: create volume err: error creating volume Get http://heketi-storage-glusterfs.router.default.svc.cluster.local/queue/c79dd21c5a1a3c95aed9117bee6e5e6d: dial tcp: lookup heketi-storage-glusterfs.router.default.svc.cluster.local: no such host`

There is no resolve issue when rsh to those glusterfs pods. 

##### Version
$ openshift version
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8

##### Steps To Reproduce
1. Install openshift with ansible on 3 nodes, all master, with glusterfs running as containers. Heketi is also deployed. 
````
$ oc get pod -n glusterfs
NAME                                          READY     STATUS    RESTARTS   AGE
glusterblock-storage-provisioner-dc-1-tvnbz   1/1       Running   0          2h
glusterfs-storage-vgxhk                       1/1       Running   0          2h
glusterfs-storage-vz2m4                       1/1       Running   0          2h
glusterfs-storage-vz9jw                       1/1       Running   0          2h
heketi-storage-1-xdgt7                        1/1       Running   0          2h
````

2. Create pvc using glusterfs. 
````
$ cat zookeeper-pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: zookeeper-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: glusterfs-storage
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
$ oc create -f ./zookeeper-pvc.yaml 
````

**Comment by php-coder** [comment]
@openshift/sig-storage
