### ISSUE TITLE
Segmentation Fault error

### ISSUE THREAD

**Issue by surajnarwade** [openshift/origin#18282]
for openshift version v3.9.0-alpha.3, I am getting following error,

```
[snarwade@localhost openshift-origin-client-tools-v3.9.0-alpha.3-78ddc10-linux-64bit]$ ./oc version
Segmentation fault
```

**Comment by kargakis** [comment]
@smarterclayton

**Comment by mfojtik** [comment]
(it works on master branch)

**Comment by mfojtik** [comment]
@smarterclayton the OSX zip https://github.com/openshift/origin/releases/download/v3.9.0-alpha.3/openshift-origin-client-tools-v3.9.0-alpha.3-78ddc10-mac.zip.download.zip contains another zip that is broken :-) (can't unpack it).

**Comment by droslean** [comment]
same issue here 
gdb says 
oc": not in executable format: File format not recognized

./oc
Segmentation fault

And when trying to untar it 
tar -xvf openshift-origin-client-tools-v3.9.0-alpha.3-78ddc10-linux-64bit.tar.gz 
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.selinux'
openshift-origin-client-tools-v3.9.0-alpha.3-78ddc10-linux-64bit/oc

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by juanvallejo** [comment]
@droslean I believe you might have better luck using `delve` instead of `gdb`: https://blog.gopheracademy.com/advent-2015/debugging-with-delve/

Mind posting your output using delve?

@surajnarwade Is `Segmentation fault` the only output you are seeing?

**Comment by juanvallejo** [comment]
@mfojtik I am getting the same error that @droslean is seeing when trying to untar [the client tools for linux](https://github.com/openshift/origin/releases/download/v3.9.0-alpha.3/openshift-origin-client-tools-v3.9.0-alpha.3-78ddc10-linux-64bit.tar.gz.download.zip):

```
$ tar xvzf openshift-origin-client-tools-v3.9.0-alpha.3-78ddc10-linux-64bit.tar.gz.download/openshift-origin-client-tools-v3.9.0-alpha.3-78ddc10-linux-64bit.tar.gz
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.selinux'
openshift-origin-client-tools-v3.9.0-alpha.3-78ddc10-linux-64bit/oc

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by droslean** [comment]
Yea basically a re-compression of the binary is needed.

**Comment by smarterclayton** [comment]
Will need to look at it again.  Something is fiddly with these downloads.

On Feb 6, 2018, at 7:23 AM, Juan Vallejo <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> friendly ping

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/18282#issuecomment-363455686>,
or mute the thread

**Comment by kargakis** [comment]
Fixed now.
