### ISSUE TITLE
provide version of OpenShift release via REST

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#1828]
Since you changed the way of retrieving build logs, I would like to know, if the master supports the new way, or still the old one. I would prefer something like this:
```
if master.get_version() <= "0.4.1":
  use_old_way()
else:
  use_new_way()
```
Method `get_version` would access REST API, e.g. `GET /osapi/v1beta1/release`.

Would it be possible to create such API call?

**Comment by mfojtik** [comment]
I think we can expose this information under the API entrypoint or send it as `Server` HTTP header (http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.38)

**Comment by mfojtik** [comment]
@smarterclayton do you think there is a need for this? I'm more inclined to convert this into Trello card for platform team :)

**Comment by TomasTomecek** [comment]
Since origin has reached a milestone of a stable API, I believe we can close this. (I still think this would be pretty useful)

**Comment by kargakis** [comment]
https://github.com/openshift/origin/pull/7964
