### ISSUE TITLE
The new pods have a slow response?

### ISSUE THREAD

**Issue by yangpeng14** [openshift/origin#18283]
##### Version
openshift 1.5

##### Steps To Reproduce
1. New pods, the pods respond to the first request about 15s, and the second or NTH response is fast.
2. SDN is the default setting.
3. node set networkConfig mtu:1450 networkPluginName: redhat/openshift-ovs-subnet

##### Current Result
1. The first response was slow (about 15s)
##### Expected Result
1. In theory, the first response is fast, not 15s.

**Comment by pweil-** [comment]
@yangpeng14 I do not think our networking team has enough information to go on here.  What is running in the pod, how are you doing a request, are you using the service, going through the router, are you pinging from a node or from a machine outside the cluster?  To start off with please include some yaml of the pod and any debugging you've already done.

**Comment by yangpeng14** [comment]
@pweil-   I ran the nodejs program in pods. In a node machine in the cluster, wget requests and ping requests, the new pods will delay 15s for the first time. This is not the case for the next n requests. Here is the pods yaml configuration file.

#######################################################
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"edu-test","name":"sls-frontend-test-3279163164","uid":"88e8eb7f-ec40-11e7-8974-00163e305e10","apiVersion":"extensions","resourceVersion":"17701931"}}
    openshift.io/scc: anyuid
  creationTimestamp: 2018-01-26T09:37:24Z
  generateName: sls-frontend-test-3279163164-
  labels:
    name: sls-frontend-test
    pod-template-hash: "3279163164"
  name: sls-frontend-test-3279163164-36wr4
  namespace: edu-test
  resourceVersion: "17702154"
  selfLink: /api/v1/namespaces/edu-test/pods/sls-frontend-test-3279163164-36wr4
  uid: 83f7613c-027c-11e8-8974-00163e305e10
spec:
  containers:
  - image: harbor.smartstudy.com/edu-test/sls-frontend-test:20171229102544-a15d65
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /title.ico
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: sls-frontend-test
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /title.ico
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources: {}
    securityContext:
      capabilities:
        drop:
        - MKNOD
        - SYS_CHROOT
      privileged: false
      seLinuxOptions:
        level: s0:c11,c0
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-x6w9q
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: harbor-certification
  nodeName: os-node2
  nodeSelector:
    label: test
  restartPolicy: Always
  securityContext:
    seLinuxOptions:
      level: s0:c11,c0
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-x6w9q
    secret:
      defaultMode: 420
      secretName: default-token-x6w9q
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-01-26T09:37:24Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-01-26T09:38:04Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-01-26T09:37:24Z
    status: "True"
    type: PodScheduled
  containerStatuses:
    lastState: {}
    name: sls-frontend-test
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-01-26T09:37:26Z
  hostIP: 192.168.162.248
  phase: Running
  podIP: 172.20.5.21
  startTime: 2018-01-26T09:37:24Z
#######################################################
