### ISSUE TITLE
Use grafana datasrouce as configuration

### ISSUE THREAD

**Issue by mrsiano** [openshift/origin#18289]
In continuing to https://github.com/openshift/origin/pull/17114
We should use datasource file as configuration, once grafana 5.0 will be released.

motivation:
 -use the most updated grafana
 -tune it accordingly if needed. 

see also 
https://github.com/grafana/grafana/pull/9504

**Comment by wtrocki** [comment]
Changes are now available in beta release: https://github.com/grafana/grafana/releases/tag/v5.0.0-beta1

**Comment by mrsiano** [comment]
yep, thanks.
