### ISSUE TITLE
Backport ceph luminous upgrade to 3.6 and 3.7?

### ISSUE THREAD

**Issue by gregswift** [openshift/origin#18297]
We recently installed a new data center, and our new ceph cluster was installed with Luminious. Our Openshift cluster is at v1.5.  We could never get PVs working, despite proving that they worked manually from any of the OpenShift nodes.

After digging in further we found that all of the current 'stable' origin images only have 0.94.5 (hammer) of ceph-common installed.  This was fixed in #17350, but since 3.6, and 3.7.x havent been rebuilt since before that was merged, they are still on the old version.

We were able to get things working by setting the tunable *profile* to `firefly` which lowers the *min_required_version* to `hammer` which allows us to connect again.

##### Version
```
Server https://rsi.rackspace.net:443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. Install a ceph luminious cluster using ceph-ansible
2. Try to provision a PV

##### Current Result
```
Jan 22 18:31:30 master-001 dockerd-current[32215]: 2018-01-22 18:31:26.791339 7fb6698667c0  0 monclient(hunting): authenticate timed out after 300
Jan 22 18:31:30 master-001 dockerd-current[32215]: 2018-01-22 18:31:26.791527 7fb6698667c0  0 librados: client.admin authentication error (110) Connection timed out
Jan 22 18:31:30 master-001 dockerd-current[32215]: rbd: couldn't connect to the cluster!
Jan 22 18:31:30 master-001 dockerd-current[32215]: E0122 18:31:26.796641       1 rbd_util.go:341] rbd: Error creating rbd image: exit status 1
Jan 22 18:31:30 master-001 dockerd-current[32215]: E0122 18:31:26.796693       1 rbd.go:310] rbd: create volume failed, err: exit status 1
Jan 22 18:31:30 master-001 dockerd-current[32215]: I0122 18:31:26.796754       1 pv_controller.go:1306] failed to provision volume for claim "test/test-volume" with StorageClass "standard": rbd: create volume failed, err: exit status 1
```

##### Expected Result
PV to be created and attachable

##### Additional Information
I'm attaching a simple session of me working from the openshift/origin:v1.5.0 image and testing connections to ceph.
[ceph-hammer-to-luminious.txt](https://github.com/openshift/origin/files/1665672/ceph-hammer-to-luminious.txt)

**Comment by pweil-** [comment]
Hi @gregswift.  Generally, as an upstream repository, Origin is forward only feature-wise.  There are some exceptions made but that is usually reserved for critical security fixes.  However, if you are using OCP rather than Origin, a back port can be requested through a customer case.
