### ISSUE TITLE
oc cluster up --metrics broken for v3.9.0

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin#18291]
Metrics fails to run using `oc cluster up --metrics`.  

Metrics pod logs include:

```
Using /usr/share/ansible/openshift-ansible/ansible.cfg as config file
ERROR! the playbook: playbooks/byo/openshift-cluster/openshift-metrics.yml could not be found
```

##### Version
oc v3.8.0-alpha.0+189d01b-1092-dirty
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.9.0-alpha.3+189d01b-196
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. oc cluster up --metrics
2. visit https://hawkular-metrics-openshift-infra.127.0.0.1.nip.io/hawkular/metrics

##### Current Result
1.  Web server returns "Application is not available"

##### Expected Result
1.  Web server returns Hawkular landing page

cc: @spadgett who can provide a bit more technical insight

**Comment by sosiouxme** [comment]
With 3.9 the playbook has moved to `playbooks/openshift-metrics/config.yml` and similar for logging.

**Comment by spadgett** [comment]
cc @oourfali

**Comment by oourfali** [comment]
Hawkular is in the responsibility of @theute

**Comment by spadgett** [comment]
This fixes the playbook path, but metrics still don't install.

```
$ oc cluster up --version=v3.9 --loglevel=2 --metrics
```

Fails with this error:

```
TASK [Gather Cluster facts] ****************************************************
--
  | Sunday 04 February 2018  17:27:07 +0000 (0:00:00.052)       0:00:09.660 *******
  | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'ansible_default_ipv4'
  | fatal: [127.0.0.1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_9kWMfv/ansible_module_openshift_facts.py\", line 1687, in <module>\n    main()\n  File \"/tmp/ansible_9kWMfv/ansible_module_openshift_facts.py\", line 1674, in main\n    additive_facts_to_overwrite)\n  File \"/tmp/ansible_9kWMfv/ansible_module_openshift_facts.py\", line 1339, in __init__\n    additive_facts_to_overwrite)\n  File \"/tmp/ansible_9kWMfv/ansible_module_openshift_facts.py\", line 1368, in generate_facts\n    defaults = self.get_defaults(roles, deployment_type, deployment_subtype)\n  File \"/tmp/ansible_9kWMfv/ansible_module_openshift_facts.py\", line 1400, in get_defaults\n    ip_addr = self.system_facts['ansible_default_ipv4']['address']\nKeyError: 'ansible_default_ipv4'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

oc v3.9.0-alpha.3+4f520a1-351
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.9.0-alpha.4+bd6b0ce-90
kubernetes v1.9.1+a0ce1bc657

**Comment by spadgett** [comment]
@jcantrill I see there's another bug tracking the second problem. I'll close this agin. Sorry for the noise.

https://github.com/openshift/openshift-ansible/issues/7006

/close

**Comment by mareklibra** [comment]
I'm still facing the original issue, updated https://github.com/openshift/origin/pull/18420 with logs and question
