### ISSUE TITLE
OpenShift unable to complete deployment

### ISSUE THREAD

**Issue by galderz** [openshift/origin#18303]
Hi,

I'm using OpenShift 3.7.1 and Fabric 8 maven plugin version 3.5.33.

Sometimes when I call `mvn fabric8:deploy` OpenShift cannot complete deployment, I see these messages appearing in the event log in a loop:

```
3:19:08 PM | app-5-x5np6 | Pod | Normal | Back-off | Back-off pulling image "app:latest"6 times in the last 2 minutes
-- | -- | -- | -- | -- | --
3:19:08 PM | app-5-x5np6 | Pod | Warning | Failed | Error: ImagePullBackOff6 times in the last 2 minutes
3:18:37 PM | app-5-x5np6 | Pod | Warning | Failed | Error: ErrImagePull4 times in the last 2 minutes
3:18:37 PM | app-5-x5np6 | Pod | Warning | Failed | Failed to pull image "app:latest": rpc error: code = 2 desc = Error response from daemon: {"message":"repository app not found: does not exist or no pull access"}4 times in the last 2 minutes
3:18:35 PM | app-5-x5np6 | Pod | Normal | Pulling | pulling image "app:latest"
```

Any idea what could be causing it? I'm using `oc cluster up` and a Mac with Docker 1.13.1.

Cheers,
Galder

**Comment by galderz** [comment]
I've been doing some testing with 3.6.1 and seems to work fine so far...

**Comment by galderz** [comment]
I've created an [issue](https://github.com/fabric8io/fabric8-maven-plugin/issues/1168) in the Fabric8 Maven Plugin, but they're hinting this is actually a [problem](https://github.com/fabric8io/fabric8-maven-plugin/issues/1130) with OpenShift itself. Anyone care to comment?

**Comment by csrwng** [comment]
@galderz after you run `mvn fabric8:deploy` can you inspect the following in OpenShift and include the results in a gist?

```
oc get is -o yaml
oc get builds -o yaml
oc get dc -o yaml
```

I don't think this is Mac specific. It looks like the image that the deployment config expects is not getting tagged in the image stream.

**Comment by galderz** [comment]
This appears to be a known issue now:
https://github.com/openshift/origin/issues/18406#issuecomment-363067144 (via https://github.com/fabric8io/fabric8-maven-plugin/issues/1130#issuecomment-364101775)
