### ISSUE TITLE
[Feature:DeploymentConfig] deploymentconfigs with test deployments [Conformance] should run a deployment to completion and then scale to zero [Suite:openshift/conformance/parallel]

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#18315]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18307/test_pull_request_origin_extended_conformance_gce/15138/

```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:303
Expected error:
    <*util.ExitError | 0xc421ef72f0>: {
        Cmd: "oc logs --config=/tmp/extended-test-cli-deployment-hnrjg-mtmjs-user.kubeconfig --namespace=extended-test-cli-deployment-hnrjg-mtmjs -f pods/deployment-test-3-deploy",
        StdErr: "Error from server (NotFound): pods \"deployment-test-3-deploy\" not found",
        ExitError: {
            ProcessState: {
                pid: 430,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 257142},
                    Stime: {Sec: 0, Usec: 45957},
                    Maxrss: 68600,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 16246,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 1629,
                    Nivcsw: 5,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
not to have occurred
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:347
```

/kind test-flake
/priority p1

**Comment by tnozicka** [comment]
was looking into it but master-controllers.service is just 2MB. 
V4 logs are missing

@stevekuznetsov any changes in CI setting recently?

**Comment by stevekuznetsov** [comment]
@sdodson @michaelgugino any idea on loglevel settings for controllers?

**Comment by tnozicka** [comment]
bump; we need V4 logs for master controllers to hunt down flakes

**Comment by sdodson** [comment]
@stevekuznetsov Assuming these vars applied it should set loglevel 5 https://github.com/openshift/aos-cd-jobs/blob/master/sjb/inventory/group_vars/OSEv3/general.yml#L2
Where are the artifacts like /etc/sysconfig/* and the controller logs in the referenced job?

**Comment by tnozicka** [comment]
I always find them in jenkins in S3 artifacts because in the other artifacts they are missing

**Comment by sdodson** [comment]
It'd be awesome if we emitted all command line args during startup or at least log level.

**Comment by stevekuznetsov** [comment]
Artifacts [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/15138/s3/), @tnozicka is correct, we currently do not push that to GCS, only S3. 

@smarterclayton @deads2k y'all like the idea of 

> It'd be awesome if we emitted all command line args during startup or at least log level.

**Comment by bparees** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18416/test_pull_request_origin_extended_conformance_gce/15621/

**Comment by tnozicka** [comment]
@sdodson `masters/qqcm/journals/origin-master-controllers.service` is still unusable (1,9 MiB)

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/15621/s3/

**Comment by kargakis** [comment]
> @stevekuznetsov Assuming these vars applied it should set loglevel 5 https://github.com/openshift/aos-cd-jobs/blob/master/sjb/inventory/group_vars/OSEv3/general.yml#L2

I don't think the gce job is using those vars. @smarterclayton will know better but my guess is https://github.com/openshift/release/pull/581

**Comment by sdodson** [comment]
@tnozicka After https://github.com/openshift/aos-cd-jobs/pull/1064 the controllers log is now > 60MiB.

**Comment by tnozicka** [comment]
@sdodson thanks!

I'll see if we get another report of this issue here.

**Comment by tnozicka** [comment]
no flake report for 2+ months
