### ISSUE TITLE
Extended.[Feature:Builds][Slow] openshift pipeline build Pipeline with env vars should build and complete successfully

### ISSUE THREAD

**Issue by bparees** [openshift/origin#18324]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/356/

```
/tmp/openshift/build-rpm-release/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:511
Expected
    <string>: OpenShift Build extended-test-jenkins-pipeline-6mhgz-dchdf/sample-pipeline-withenvs-1
    [Pipeline] node
    Running on master in /var/lib/jenkins/jobs/extended-test-jenkins-pipeline-6mhgz-dchdf/jobs/extended-test-jenkins-pipeline-6mhgz-dchdf-sample-pipeline-withenvs/workspace
    [Pipeline] {
    [Pipeline] echo
    FOO1 is BAR1
    [Pipeline] echo
    FOO2 is null
    [Pipeline] }
    [Pipeline] // node
    [Pipeline] End of Pipeline
    Finished: SUCCESS
    
to contain substring
    <string>: FOO2 is BAR2
/tmp/openshift/build-rpm-release/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/pipeline.go:542
```

**Comment by gabemontero** [comment]
Hmmm ... from the jenkins pod logs, this is most likely the cause:

```
Jan 28, 2018 8:02:33 PM hudson.model.ParametersAction filter
WARNING: Skipped parameter `FOO2` as it is undefined on `extended-test-jenkins-pipeline-6mhgz-dchdf/extended-test-jenkins-pipeline-6mhgz-dchdf-sample-pipeline-withenvs`. Set `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` to allow undefined parameters to be injected as environment variables or `-Dhudson.model.ParametersAction.safeParameters=[comma-separated list]` to whitelist specific parameter names, even though it represents a security breach or `-Dhudson.model.ParametersAction.keepUndefinedParameters=false` to no longer show this message.
```

The big question will be why that is occurring now.  This test passed with the last sit of PR validations for sync plugin, and recent overnight runs best as I noticed.

Will be seeing if I can reproduce locally.

**Comment by gabemontero** [comment]
Figures ... with the latest openshift and jenkins image, I'm not seeing this problem when running this manually (either command line or extended test).  And correspondingly the WARNING message I noted above does not appear.

So a timing issue.

With that in mind, upon further perusal of the jenkins pod log, I this time also noticed:

```
Jan 28, 2018 8:02:28 PM io.fabric8.jenkins.openshiftsync.BuildWatcher flushBuildsWithNoBCList
INFO: triggering job run for previously skipped build sample-pipeline-withenvs-1
```

This means the build event arrived before the build config event .... perhaps this is the crux of the timing change that results in our inability to add environment variables.

I'll revisit the code with that lens, see if I notice anything.  If not, I'll see if I can force the build before bc flow (temporarily no-oping the build config watch / poll) and reproduce that way.

**Comment by gabemontero** [comment]
OK I tried delays varying from 5 seconds to 5 milliseconds, and while I could reproduce the build event comes before the build config event, I could not reproduce the skipped undefined param issue.

At delays of less than 5 seconds, I could not even reliably reproduce forcing the event order a certain way.

My instincts still tell me this is some sort of concurrency issue between job create and run instantiate on the jenkins side, but proof is elusive.

This is looking at either:
a) ignoring and see how frequent it occurs before making any changes 
b) add more standard, always occurring logging around job and run param creation
c) adding delays in either the test case between bc and build creation
d) adding delays in the plugin around bc create events triggering cached build events 

if we don't do a), c) and maybe b) are my initial preferences.

In addition to corresponding here, may seek out @bparees for face to face when he frees up from conf calls

**Comment by gabemontero** [comment]
After @bparees and I talked, set out with conjuring up verification logic that the job has new "dynamic parameter"  ... in doing so, I believe I've discovered a) where we could force the persistence of the job update to avoid the timing window, b) perhaps learned where we need to insert an impersonate call so that we can read the job and verify its contents

Should have a PR up soon

**Comment by gabemontero** [comment]
actually I'll reopen until I cut the new openshift jenkins centos image
