### ISSUE TITLE
Add .NET Core image streams

### ISSUE THREAD

**Issue by tmds** [openshift/origin#18330]
Openshift Container Platform includes RHEL-based image streams for .NET Core built from https://github.com/redhat-developer/s2i-dotnetcore/. Recently we have added [CentOS based image streams](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/dotnet_imagestreams_centos.json). Can those be included out-of-the-box in OpenShift Origin?

**Comment by php-coder** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
@tmds yes, just submit a PR updating the centos imagestreams in origin:  https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json
