### ISSUE TITLE
[secret] When the secret is deleted, a new one isn't automatically generated

### ISSUE THREAD

**Issue by alicealvy** [openshift/origin#18345]
my new project  have three default service account,When their secret is deleted, a new one isn't automatically generated

##### Version
# oc version
oc v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.example.com:8443
openshift v3.6.173.0.49
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. get sa
```console
# oc get sa
NAME       SECRETS   AGE
builder    2         21h
default    2         21h
deployer   2         21h
```
2. get secret
```console
# oc get secret
NAME                       TYPE                                  DATA      AGE
builder-dockercfg-5t67n    kubernetes.io/dockercfg               1         18h
builder-token-kb5jz        kubernetes.io/service-account-token   4         18h
builder-token-tj5vf        kubernetes.io/service-account-token   4         18h
default-dockercfg-q7ps9    kubernetes.io/dockercfg               1         18h
default-token-fv618        kubernetes.io/service-account-token   4         18h
default-token-gpr7l        kubernetes.io/service-account-token   4         18h
deployer-dockercfg-xn559   kubernetes.io/dockercfg               1         18h
deployer-token-mvtqk       kubernetes.io/service-account-token   4         18h
deployer-token-swlbq       kubernetes.io/service-account-token   4         18h
```
3. delete secret
```console
# oc delete secret builder-token-kb5jz builder-token-tj5vf default-token-fv618 default-token-gpr7l deployer-token-mvtqk deployer-token-swlbq builder-dockercfg-5t67n default-dockercfg-q7ps9 deployer-dockercfg-xn559
secret "builder-token-kb5jz" deleted
secret "builder-token-tj5vf" deleted
secret "default-token-fv618" deleted
secret "default-token-gpr7l" deleted
secret "deployer-token-mvtqk" deleted
secret "deployer-token-swlbq" deleted
secret "builder-dockercfg-5t67n" deleted
secret "default-dockercfg-q7ps9" deleted
secret "deployer-dockercfg-xn559" deleted
```
4. get secret
```console
# oc get secret
NAME                    TYPE                                  DATA      AGE
builder-token-x664r     kubernetes.io/service-account-token   4         2s
default-token-zkrq7     kubernetes.io/service-account-token   4         2s
deployer-token-v41zl    kubernetes.io/service-account-token   4         2s
```
##### Current Result
When the secret is deleted, a new one isn't automatically generated

##### Expected Result
When the secret is deleted, a new one is automatically generated

**Comment by php-coder** [comment]
Why do you think that it should automatically generated? Is is documented somewhere?

**Comment by alicealvy** [comment]
@php-coder 
please look 
https://docs.openshift.com/container-platform/3.7/dev_guide/service_accounts.html
[Managing Service Accounts]

**Comment by php-coder** [comment]
I couldn't reproduce it on 3.6, 3.7 and the master. Looks like origin isn't affected by this. I'll try to find OSE 3.6 to reproduce it there.

**Comment by php-coder** [comment]
@alicealvy Could it be related to a user or specific namespace? Please, provide the output of the `oc project` and `oc whoami` commands.

**Comment by php-coder** [comment]
I was unable to reproduce this issue on
```
oc v3.6.173.0.103
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xx.yy.example.com:8443
openshift v3.6.173.0.103
kubernetes v1.6.1+5115d708d7
```
I tried to delete the secrets from different users and by different commands.

@alicealvy If it's possible, provide more details for reproducing the issue. Try to create a new project and delete its secrets, for example. Ideally, it's better to upgrade a cluster to a newer version.
