### ISSUE TITLE
Failed connect to github.com:443; Connection refused

### ISSUE THREAD

**Issue by silentwu** [openshift/origin#18346]
hello,
i build java project , face this error. can not access github.com

Cloning "https://github.com/silentwu/openshift-tomcat.git" ...
--
  | error: build error: fatal: unable to access 'https://github.com/silentwu/openshift-tomcat.git/': Failed connect to github.com:443; Connection refused

**Comment by php-coder** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
this is a networking issue in your environment.

**Comment by Prathambarca** [comment]
> this is a networking issue in your environment.

how to fix that?? Any suggestions?? Because I tried to add pull secret with my github credentials but still it got refused
