### ISSUE TITLE
Support for Bazel

### ISSUE THREAD

**Issue by abergmeier** [openshift/origin#18349]
Would be good to have rules for deployment and similar to enable IaC when using Bazel.

**Comment by php-coder** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
@abergmeier please elaborate.  And what is "IaC"?

**Comment by pweil-** [comment]
There is not enough info here to create a feature request or reply with how the platform may satisfy what you need already.  If you'd like to pursue this please describe your use cases and requirements in more detail.
