### ISSUE TITLE
facing an error when install flex volume driver 

### ISSUE THREAD

**Issue by testfielder** [openshift/origin#18361]
OS: Atomic Host release 7.4

when i install flexvolume drive like that as https://docs.openshift.org/latest/install_config/persistent_storage/persistent_storage_flex_volume.html#flex-volume-installation :
```
# mkdir -p /usr/libexec/kubernetes/kubelet-plugins/volume/exec/openshift.com~nfs
mkdir: cannot create directory ‘/usr/libexec/kubernetes’: Read-only file system
```

**Comment by php-coder** [comment]
@openshift/sig-storage

**Comment by jsafrane** [comment]
Unfortunately, Atomi Host is immutable. OpenShift / Kubernetes considers to have this directory configurable, https://github.com/kubernetes/features/issues/500, but not in the short term.

How do you install Kubernetes there? On AtomicHost, OpenShift runs inside container(s) and flex volume drivers should be in these containers.

**Comment by testfielder** [comment]
thx.
