### ISSUE TITLE
CrashLoopBackOff

### ISSUE THREAD

**Issue by bikej** [openshift/origin#18362]
##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.****:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. oc new-app centos or oc new-app alpine or oc new-app debian...
2. oc status -v
Errors:
  * pod/centos-1-dl5dp is crash-looping

    The container is starting and exiting repeatedly. This usually means the container is unable
    to start, misconfigured, or limited by security restrictions. Check the container logs with

      oc logs centos-1-dl5dp -c centos

3. oc logs centos-1-dl5dp -c centos gives nothing

##### Expected Result
A running pod

##### Additional Information
First I deployed httpd and there was a problem with permissions so i did
oadm policy add-scc-to-user anyuid -z default  and it fixed it.

oc edit scc anyuid
users:
- system:serviceaccount:myproject:default

What am I missing?

**Comment by php-coder** [comment]
What was the expected result of the running `oc new-app centos`? CentOS/Debian/Alpine images don't do anything useful and typically are used as a base image for the application images. In this case, I'd say that the behavior you're seeing is expected.

CC @openshift/sig-developer-experience

**Comment by bparees** [comment]
yeah, if the image's entrypoint is not a long running process, the container will simply terminate after starting, and get restarted, hence crashloop.  you need to use an image w/ a long running entrypoint.

**Comment by bikej** [comment]
Thanks guys, I didn't have the big picture here.
