### ISSUE TITLE
pods don't have access to external resources

### ISSUE THREAD

**Issue by dvlro** [openshift/origin#18373]
I have been having this issue for some time. 
Can someone assist me in solving it? 
For example I want to clone a github repository and get timeout every time I run a build.

**Comment by php-coder** [comment]
About what exactly pod you're talking about? Did you create a pod manually and trying to do `git clone` from it or you're using Builds that creates a pod and clones a repo?

**Comment by bparees** [comment]
regarding @php-coder's suggestion, the easiest way to investigate this is to deploy the jenkins image and then oc rsh into it and attempt a git clone (the jenkins image includes git).  This will replicate what the build is doing when it tries to clone your code.

Assuming that fails, show us the output, but it's almost certainly either a DNS configuration issue, or a networking configuration issue.  So it would also be useful to know more about your cluster environment and how it was created.

**Comment by dvlro** [comment]
@bparees I did what you suggested, deployed jenkins and tried to git clone. As a result: Failed connect to github.com:443; Connection timed out.

Also pinged google the same result.
bash-4.2$ ping google.com
PING google.com.contaboserver.net (91.194.91.220) 56(84) bytes of data.

Regarding the steps that I made to install it on Centos 7 are here : http://gdbb.blog.fc2.com/blog-entry-1183.html .

iptables-save output below:

[root@vmi153203 ~]# iptables-save
# Generated by iptables-save v1.4.21 on Thu Feb  1 21:33:36 2018
*nat
:PREROUTING ACCEPT [6:752]
:INPUT ACCEPT [6:752]
:OUTPUT ACCEPT [25:1513]
:POSTROUTING ACCEPT [25:1513]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORT-CONTAINER - [0:0]
:KUBE-NODEPORT-HOST - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-PORTALS-CONTAINER - [0:0]
:KUBE-PORTALS-HOST - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-2VNFJLC7WGB3NWHE - [0:0]
:KUBE-SEP-B6D6ICEZEURPNU42 - [0:0]
:KUBE-SEP-BEFWBIRTQVZNZIKW - [0:0]
:KUBE-SEP-C7SAPSPXVGHWS7ZP - [0:0]
:KUBE-SEP-DR5LJRZM7EUMKBVP - [0:0]
:KUBE-SEP-EA7ZOM7TD426ZFVZ - [0:0]
:KUBE-SEP-KNAHRHIQTI3NAZFD - [0:0]
:KUBE-SEP-OROJRS45ARZAZZ46 - [0:0]
:KUBE-SEP-TQEECANCIQQY77XE - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-3VQ6B3MLH7E2SZT4 - [0:0]
:KUBE-SVC-4JCRTMMYZAAYMIJ2 - [0:0]
:KUBE-SVC-BA6I5HTZKAAAJT56 - [0:0]
:KUBE-SVC-ECTPRXTXBM34L34Q - [0:0]
:KUBE-SVC-FBW2BSC3OFAPYTV4 - [0:0]
:KUBE-SVC-GFZNOSGDZVT3L5DV - [0:0]
:KUBE-SVC-GQKZAHCS5DTMHUQ6 - [0:0]
:KUBE-SVC-IKV43KYNCXS2W7KZ - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
-A PREROUTING -m comment --comment "handle ClusterIPs; NOTE: this must be before the NodePort rules" -j KUBE-PORTALS-CONTAINER
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A PREROUTING -m addrtype --dst-type LOCAL -m comment --comment "handle service NodePorts; NOTE: this must be the last rule in the chain" -j KUBE-NODEPORT-CONTAINER
-A OUTPUT -m comment --comment "handle ClusterIPs; NOTE: this must be before the NodePort rules" -j KUBE-PORTALS-HOST
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m addrtype --dst-type LOCAL -m comment --comment "handle service NodePorts; NOTE: this must be the last rule in the chain" -j KUBE-NODEPORT-HOST
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x1/0x1
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x1/0x1 -j MASQUERADE
-A KUBE-SEP-2VNFJLC7WGB3NWHE -s 173.249.6.143/32 -m comment --comment "default/router:1936-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-2VNFJLC7WGB3NWHE -p tcp -m comment --comment "default/router:1936-tcp" -m tcp -j DNAT --to-destination 173.249.6.143:1936
-A KUBE-SEP-B6D6ICEZEURPNU42 -s 173.249.6.143/32 -m comment --comment "default/kubernetes:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-B6D6ICEZEURPNU42 -p udp -m comment --comment "default/kubernetes:dns" -m recent --set --name KUBE-SEP-B6D6ICEZEURPNU42 --mask 255.255.255.255 --rsource -m udp -j DNAT --to-destination 173.249.6.143:8053
-A KUBE-SEP-BEFWBIRTQVZNZIKW -s 173.249.6.143/32 -m comment --comment "default/router:80-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-BEFWBIRTQVZNZIKW -p tcp -m comment --comment "default/router:80-tcp" -m tcp -j DNAT --to-destination 173.249.6.143:80
-A KUBE-SEP-C7SAPSPXVGHWS7ZP -s 173.249.6.143/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-C7SAPSPXVGHWS7ZP -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-C7SAPSPXVGHWS7ZP --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 173.249.6.143:8443
-A KUBE-SEP-DR5LJRZM7EUMKBVP -s 172.17.0.5/32 -m comment --comment "default/docker-registry:5000-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-DR5LJRZM7EUMKBVP -p tcp -m comment --comment "default/docker-registry:5000-tcp" -m recent --set --name KUBE-SEP-DR5LJRZM7EUMKBVP --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 172.17.0.5:5000
-A KUBE-SEP-EA7ZOM7TD426ZFVZ -s 173.249.6.143/32 -m comment --comment "default/router:443-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-EA7ZOM7TD426ZFVZ -p tcp -m comment --comment "default/router:443-tcp" -m tcp -j DNAT --to-destination 173.249.6.143:443
-A KUBE-SEP-KNAHRHIQTI3NAZFD -s 172.17.0.3/32 -m comment --comment "openshift/jenkins-jnlp:agent" -j KUBE-MARK-MASQ
-A KUBE-SEP-KNAHRHIQTI3NAZFD -p tcp -m comment --comment "openshift/jenkins-jnlp:agent" -m tcp -j DNAT --to-destination 172.17.0.3:50000
-A KUBE-SEP-OROJRS45ARZAZZ46 -s 172.17.0.3/32 -m comment --comment "openshift/jenkins:web" -j KUBE-MARK-MASQ
-A KUBE-SEP-OROJRS45ARZAZZ46 -p tcp -m comment --comment "openshift/jenkins:web" -m tcp -j DNAT --to-destination 172.17.0.3:8080
-A KUBE-SEP-TQEECANCIQQY77XE -s 173.249.6.143/32 -m comment --comment "default/kubernetes:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-TQEECANCIQQY77XE -p tcp -m comment --comment "default/kubernetes:dns-tcp" -m recent --set --name KUBE-SEP-TQEECANCIQQY77XE --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 173.249.6.143:8053
-A KUBE-SERVICES -d 172.30.46.6/32 -p tcp -m comment --comment "default/router:80-tcp cluster IP" -m tcp --dport 80 -j KUBE-SVC-GQKZAHCS5DTMHUQ6
-A KUBE-SERVICES -d 172.30.46.6/32 -p tcp -m comment --comment "default/router:443-tcp cluster IP" -m tcp --dport 443 -j KUBE-SVC-IKV43KYNCXS2W7KZ
-A KUBE-SERVICES -d 172.30.46.6/32 -p tcp -m comment --comment "default/router:1936-tcp cluster IP" -m tcp --dport 1936 -j KUBE-SVC-4JCRTMMYZAAYMIJ2
-A KUBE-SERVICES -d 172.30.32.105/32 -p tcp -m comment --comment "openshift/jenkins-jnlp:agent cluster IP" -m tcp --dport 50000 -j KUBE-SVC-FBW2BSC3OFAPYTV4
-A KUBE-SERVICES -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-BA6I5HTZKAAAJT56
-A KUBE-SERVICES -d 172.30.1.1/32 -p tcp -m comment --comment "default/docker-registry:5000-tcp cluster IP" -m tcp --dport 5000 -j KUBE-SVC-ECTPRXTXBM34L34Q
-A KUBE-SERVICES -d 172.30.36.102/32 -p tcp -m comment --comment "openshift/jenkins:web cluster IP" -m tcp --dport 80 -j KUBE-SVC-GFZNOSGDZVT3L5DV
-A KUBE-SERVICES -d 172.30.0.1/32 -p udp -m comment --comment "default/kubernetes:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-3VQ6B3MLH7E2SZT4
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-3VQ6B3MLH7E2SZT4 -m comment --comment "default/kubernetes:dns" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-B6D6ICEZEURPNU42 --mask 255.255.255.255 --rsource -j KUBE-SEP-B6D6ICEZEURPNU42
-A KUBE-SVC-3VQ6B3MLH7E2SZT4 -m comment --comment "default/kubernetes:dns" -j KUBE-SEP-B6D6ICEZEURPNU42
-A KUBE-SVC-4JCRTMMYZAAYMIJ2 -m comment --comment "default/router:1936-tcp" -j KUBE-SEP-2VNFJLC7WGB3NWHE
-A KUBE-SVC-BA6I5HTZKAAAJT56 -m comment --comment "default/kubernetes:dns-tcp" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-TQEECANCIQQY77XE --mask 255.255.255.255 --rsource -j KUBE-SEP-TQEECANCIQQY77XE
-A KUBE-SVC-BA6I5HTZKAAAJT56 -m comment --comment "default/kubernetes:dns-tcp" -j KUBE-SEP-TQEECANCIQQY77XE
-A KUBE-SVC-ECTPRXTXBM34L34Q -m comment --comment "default/docker-registry:5000-tcp" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-DR5LJRZM7EUMKBVP --mask 255.255.255.255 --rsource -j KUBE-SEP-DR5LJRZM7EUMKBVP
-A KUBE-SVC-ECTPRXTXBM34L34Q -m comment --comment "default/docker-registry:5000-tcp" -j KUBE-SEP-DR5LJRZM7EUMKBVP
-A KUBE-SVC-FBW2BSC3OFAPYTV4 -m comment --comment "openshift/jenkins-jnlp:agent" -j KUBE-SEP-KNAHRHIQTI3NAZFD
-A KUBE-SVC-GFZNOSGDZVT3L5DV -m comment --comment "openshift/jenkins:web" -j KUBE-SEP-OROJRS45ARZAZZ46
-A KUBE-SVC-GQKZAHCS5DTMHUQ6 -m comment --comment "default/router:80-tcp" -j KUBE-SEP-BEFWBIRTQVZNZIKW
-A KUBE-SVC-IKV43KYNCXS2W7KZ -m comment --comment "default/router:443-tcp" -j KUBE-SEP-EA7ZOM7TD426ZFVZ
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-C7SAPSPXVGHWS7ZP --mask 255.255.255.255 --rsource -j KUBE-SEP-C7SAPSPXVGHWS7ZP
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-C7SAPSPXVGHWS7ZP
COMMIT
# Completed on Thu Feb  1 21:33:36 2018
# Generated by iptables-save v1.4.21 on Thu Feb  1 21:33:36 2018
*filter
:INPUT ACCEPT [2864:563898]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [2728:553077]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-NODEPORT-NON-LOCAL - [0:0]
:KUBE-SERVICES - [0:0]
-A INPUT -m comment --comment "Ensure that non-local NodePort traffic can flow" -j KUBE-NODEPORT-NON-LOCAL
-A INPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A INPUT -j KUBE-FIREWALL
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
COMMIT
# Completed on Thu Feb  1 21:33:36 2018
[root@vmi153203 ~]#

**Comment by bparees** [comment]
@dcbw @danwinship can one of you help w/ @dvlro's networking issue?

**Comment by danwinship** [comment]
> bash-4.2$ ping google.com
> PING google.com.contaboserver.net (91.194.91.220) 56(84) bytes of data.

"google.com.contaboserver.net"? That seems wrong. Is your DNS misconfigured?
