### ISSUE TITLE
`oc adm policy remove-cluster-role-from-group` does not remove the group from role

### ISSUE THREAD

**Issue by nak3** [openshift/origin#18386]
##### description of the issue

`oc adm policy remove-cluster-role-from-group` does not
remove the group from role.

##### Version

Confirmed with the latest build ed354cf337c58d073e121051a5db5c76dd958881 and
 OCP 3.7's binary both.

~~~
# oc version
oc v3.7.9
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO
~~~

###### 1. Add role to group

~~~
# oc adm policy add-role-to-group cluster-reader testgroup
role "cluster-reader" added: "testgroup"
~~~

###### 2. Remove role from the group

~~~
# oc adm policy remove-cluster-role-from-group cluster-reader testgroup
cluster role "cluster-reader" removed: "testgroup"
~~~

###### 3. Check the rolebinding

~~~
# oc get rolebinding cluster-reader
NAME             ROLE              USERS     GROUPS      SERVICE ACCOUNTS   SUBJECTS
cluster-reader   /cluster-reader             testgroup
~~~

##### Current Result

As you can see step-3, the role remains.

##### Expected Result

Role removed.

##### Additional Information

Due to this issue, https://github.com/openshift/origin/pull/18383
failed to the command test.

**Comment by enj** [comment]
This is working as expected.  @nak3 you are combining commands that work against different resources - cluster role binding vs role binding.

@simo5 I will let you close.

**Comment by nak3** [comment]
@enj Actually I still don't understand it what was wrong... (I'm sorry, my bad knowledge).

1. When I ran `oc adm policy add-role-to-group`

~~~
  # oc adm policy add-role-to-group cluster-reader foooo
  role "cluster-reader" added: "foooo"
~~~

2. Surely I can see that it was added to `rolebinding`.

~~~
  # oc get rolebinding  |grep foooo
  cluster-reader          /cluster-reader                   testgroup, testgroup11, foooo
~~~

But it was not added to cluster rolebinding

~~~
  # oc get clusterrolebinding  |grep foooo
  #
~~~

3. Then, even if I ran `remove-cluster-role-from-group`, the added group in step-1 was not removed.

~~~
  # oc adm policy remove-cluster-role-from-group cluster-reader foooo
  cluster role "cluster-reader" removed: "foooo"

  # oc get rolebinding  |grep foooo
  cluster-reader          /cluster-reader                   testgroup, testgroup11, foooo
~~~

If it was not a bag, how I can remove the `foooo` from `/cluster-reader` in `oc get rolebinding`.
