### ISSUE TITLE
Extended.[Feature:ImagePrune][registry][Serial] Image prune with default --all flag should prune both internally managed and external images 

### ISSUE THREAD

**Issue by bparees** [openshift/origin#18384]
test flaked.

```
/tmp/openshift/build-rpm-release/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/test/extended/images/prune.go:124
Expected error:
    <*errors.errorString | 0xc420225fc0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/tmp/openshift/build-rpm-release/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/test/extended/images/prune.go:319
```

as seen in:

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_registry/103/testReport/junit/(root)/Extended/_Feature_ImagePrune__registry__Serial__Image_prune_with_default___all_flag_should_prune_both_internally_managed_and_external_images__Suite_openshift_/

**Comment by legionus** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_registry/122/consoleFull
