### ISSUE TITLE
Incorrect schema

### ISSUE THREAD

**Issue by surajnarwade** [openshift/origin#18381]
In this schema https://raw.githubusercontent.com/openshift/origin/master/api/swagger-spec/oapi-v1.json from master, keys like `replicas`, `test` shown as `required` but they are not.

**Comment by php-coder** [comment]
@openshift/sig-master

**Comment by soltysh** [comment]
This might be related to https://github.com/openshift/origin/issues/17610, I'll try to check it out later this week.
