### ISSUE TITLE
Regular user can't grant update privileges to update route.openshift.io/routes/custom-host

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#18397]
role.authorization.openshift.io "openshift-acme" is forbidden: user "developer" cannot grant extra privileges:
{Verbs:["update"], APIGroups:["route.openshift.io"], Resources:["routes/custom-host"]}

he can grant create though. I think he can also update it manually so not being able to grant update seems like a bug. (likely he should be also able to do patch, ...)

@liggitt @enj ?

**Comment by enj** [comment]
See https://github.com/openshift/origin/pull/18177#issuecomment-360660024 https://github.com/openshift/origin/pull/18312

Closing this since it will get sorted out in that PR.

**Comment by tnozicka** [comment]
thanks @enj 

For the record I was wrong, I couldn't even update it. That PR is what I need.
