### ISSUE TITLE
`oc get all` not getting all

### ISSUE THREAD

**Issue by micah** [openshift/origin#18396]
I wanted to remove all resources related to a prometheus deployment I did, so I looked for them all this way:

```
oc get all --all-namespaces|grep -i prometheus
```

and then deleted them.... but I was surprised because pods were still being created, and eventually I found there was a daemon-set configured, but that did not show up in the `get all`. I even tried a `oc get all` scoped to the namespace that it was in, and it did not show it at all. 

I also found that there was a service account that also was not found, also in that namespace, that did not show up in the `oc get all` either.

##### Version
```
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.7.0+7ed6862
```

##### Steps To Reproduce
1. Create a daemonset in a namespace
2. Create a service account in a namespace
3. `oc get all --all-namespaces` will not show either of the above, nor will `oc get all -n <namespace>`

##### Expected Result

I expect to get *all* resources from `oc get all --all-namespaces` and to get all the resources in the namespace when specified with `oc get all -n <namespace>`

**Comment by juanvallejo** [comment]
The `all` alias does not include all resources.
See https://github.com/openshift/origin/issues/3740

**Comment by micah** [comment]
@juanvallejo indeed, it does not include all resources, but #3740 only indicates that it does not include secrets, and that is by design. This issue is about it not including other non-secret resources.

**Comment by juanvallejo** [comment]
@micah looking at this further, 3.7 clients expanded `all` a bit differently than newer clients.
3.7 clients expand `all` to the set of available resources in the server from the union of [an Origin-specific resource list](https://github.com/openshift/origin/blob/release-3.7/pkg/cmd/util/clientcmd/factory_object_mapping.go#L85-L91) and an [upstream-specific resource list](https://github.com/openshift/origin/blob/release-3.7/vendor/k8s.io/kubernetes/pkg/kubectl/resource/categories.go#L113-L123).

A 3.9 client, for example, "discovers" from the server which resources should be listed as part of `all`. This list does include `DaemonSets`.

**Comment by micah** [comment]
> @micah looking at this further, 3.7 clients expanded `all` a bit differently than newer clients.
> 3.7 clients expand `all` to the set of available resources in the server from the union of [an Origin-specific resource list](https://github.com/openshift/origin/blob/release-3.7/pkg/cmd/util/clientcmd/factory_object_mapping.go#L85-L91) and an [upstream-specific resource list](https://github.com/openshift/origin/blob/release-3.7/vendor/k8s.io/kubernetes/pkg/kubectl/resource/categories.go#L113-L123).
>
> A 3.9 client, for example, "discovers" from the server which resources should be listed as part of `all`. This list does include `DaemonSets`.

Thanks for finding that!

Where can I find the details of 3.9 clients? I only see a 3.7 release.

**Comment by juanvallejo** [comment]
@micah you can see the changelog and download a binary of the latest client here https://github.com/openshift/origin/releases/tag/v3.9.0-alpha.3
