### ISSUE TITLE
oc cluster up should install webconsole for 3.9

### ISSUE THREAD

**Issue by vrutkovs** [openshift/origin#18408]
The cluster is up, but no web console available when `oc cluster up --version='v3.9.0'` is running

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.9.0-alpha.4+49100d9-88
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. `oc cluster up --version='v3.9.0'` ( or `--version=latest`)
2. Open `https://127.0.0.1:8443`

##### Current Result
Web server returns:
```
missing service (service "webconsole" not found)
missing route (service "webconsole" not found)
```

##### Expected Result
Web Console is deployed

**Comment by spadgett** [comment]
> oc v3.7.0+7ed6862

Your `oc` is too old. You need a current `oc` from master to install the console.

**Comment by spadgett** [comment]
Please reopen if see the issue with `oc` built from current master.

**Comment by mandibuswell** [comment]
I have this issue my versions are
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657
