### ISSUE TITLE
Patching a DC - Image is not possible

### ISSUE THREAD

**Issue by Andreas-Maier-NTT** [openshift/origin#18413]
I'm trying to patch the image of a deployment using 
 oc patch dc dc-name --patch='{"spec":{"template":{"spec":{"containers[0]":{"image":"image-name:tag"}}}}}'

However, if I try that the log says that the dc is not patched. 

##### Version
$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server server name
openshift v3.7.23
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. Deploy deployment config
2. Try to patch the image

##### Current Result
DC is not patched
##### Expected Result
DC is patched

**Comment by mfojtik** [comment]
@Andreas-Maier-NTT does the DC have image change trigger defined?

**Comment by Andreas-Maier-NTT** [comment]
Not yet. I just had a "full qualified" image in there including the tag to use. And I want to update that.

**Comment by tnozicka** [comment]
@Andreas-Maier-NTT could you please provide `oc get dc <name> -o yaml` before applying the patch and after?

I think it says not patched when the value is already there.

**Comment by tnozicka** [comment]
More precisely it says not patched when the object hasn't changed.

Your patch line seems wrong - you are adding a new key instead of indexing the array - should be like this:

`oc patch dc <name> --patch='{"spec":{"template":{"spec":{"containers":[{"name": "<container-name>", "image":"image-name:tag"}]}}}}'`

**Comment by Andreas-Maier-NTT** [comment]
That seems to work! Thank you so much! But I at least think it worked previously. Anyways...thanks for helping! :)

**Comment by uvkr** [comment]
oc patch dc ratestar -p '{"spec": {"template": {"spec": {"containers": [{"name": "","resources": {"limits": {"cpu": "500m","memory": "512Mi"}}}]}}}}'
The DeploymentConfig "ratestar" is invalid:
* spec.template.spec.containers[0].name: Required value
* spec.template.spec.containers[0].image: Required value

**Comment by uvkr** [comment]
I got this error if run same command
