### ISSUE TITLE
templates appear twice with `oc cluster up --service-catalog`

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#18446]
When I run `oc cluster up --service-catalog` and browse the console, each template appears twice - once as a TSB item, once as a legacy template item - is this intended?

**Comment by spadgett** [comment]
@jim-minter This should be fixed in latest. Can you make sure you've pulled the latest openshift/origin-web-console image? You might need to use

```
oc cluster up --version=v3.9 --service-catalog
```

**Comment by jim-minter** [comment]
Can't reproduce with `--version=latest`, thanks
