### ISSUE TITLE
Unable to build origin with golang 1.10rc1

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#18447]
So I've tried building origin with `go1.10rc1` and that fails with:
```
# github.com/openshift/origin/vendor/github.com/apcera/gssapi
vendor/github.com/apcera/gssapi/name.go:214: cannot use n.C_gss_name_t (type _Ctype_gss_name_t) as type _Ctype_gss_const_name_t in argument to func literal
```

@openshift/sig-security since we'll have to solve it soon, I guess.

**Comment by soltysh** [comment]
@openshift/sig-master fyi

**Comment by simo5** [comment]
So did go1.10 start to become annoying with C const casting ?
This is not going to be fun ...

**Comment by simo5** [comment]
@bparees @soltysh wouldn't it be more effective to open an issue on the upstream repo ?

**Comment by bparees** [comment]
@simo5 definitely not my area of expertise.  I'm just handling issue assignment duties for some group leads.  You're welcome to make it an upstream issue as far as i'm concerned.

**Comment by simo5** [comment]
@enj FYI

**Comment by soltysh** [comment]
@simo5 I'm worried that the upstream (I do hope you're talking about gssapi project) isn't maintained for quite a while, but I'll give it a try, maybe we just have some older version. /me crosses fingers and tries...

**Comment by soltysh** [comment]
I've opened https://github.com/apcera/gssapi/issues/54 and waiting to hear from maintainers.

**Comment by simo5** [comment]
Ok, if they do not reply timely we will then just fork ...

**Comment by enj** [comment]
https://github.com/apcera/gssapi/issues/54#issuecomment-363989014
