### ISSUE TITLE
`oc get all` lost backward compatibility from 3.9 to 3.6

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#18473]
For some reason `oc get all` (on 3.9) shows nothing when talking to 3.6 server. 
@deads2k @juanvallejo can this be related to something we did when 3.9 stated to show some resources twice?

```
$ oc get all
No resources found.

$ oc-v3.6.1 get all 
NAME          HOST/PORT      PATH      SERVICES       PORT      TERMINATION     WILDCARD
routes/test   xxxxxxx             non-existing   <all>     edge/Redirect   None

$ oc version
oc v3.9.0-alpha.4+709c3a8-24
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

$ oc get all
No resources found.

```

**Comment by tnozicka** [comment]
`oc get route` works so this is likely something about discovery

**Comment by deads2k** [comment]
We support n-1 from oc/kubectl.  This is beyond the scope.  In this case, it's because 3.6 discovery doesn't have categories.

**Comment by tnozicka** [comment]
Ok, tried 3.7 (which is n-1 since 3.8 doesn't count) and it shows the route there (in `oc get all`), but twice :/

**Comment by deads2k** [comment]
> Ok, tried 3.7 (which is n-1 since 3.8 doesn't count) and it shows the route there (in oc get all), but twice :/

3.7 is bugged.  Need picks of https://github.com/openshift/origin/pull/18219 and https://github.com/openshift/origin/pull/18085 into 3.7 I guess.

@juanvallejo

**Comment by juanvallejo** [comment]
@deads2k on it
