### ISSUE TITLE
Occasionally OpenShift pods creation fails

### ISSUE THREAD

**Issue by akorneta** [openshift/origin#18472]
Hi, I'm from the [Che](https://github.com/eclipse/che) team. 
We have a problem while executing our integration tests.
A small intro what’s going on. We deploy Che on an OpenShift instance(OCP deployed on docker). Che is configured with user credentials to be able to create the OpenShift objects(pods, services, routes) on behalf of the user in different projects. For interaction with OpenShfit API, we’re using `fabric8io/kubernetes-client`.
In our tests Che creates OpenShift objects in different projects in several threads and sometimes it fails while creating a pod because of the following error:

<details>
<summary>response error</summary>

```
Failure executing: POST at: https://172.19.20.43:8443/api/v1/namespaces/workspace8cvdb4ialql0zpoj/pods.
Message: No API token found for service account "default", retry after the token is automatically created and added to the service account. 
Received status: Status(apiVersion=v1, code=500, details=StatusDetails(causes=[], group=null, kind=serviceaccounts, name=create pod, retryAfterSeconds=1, uid=null, additionalProperties={}), kind=Status, message=No API token found for service account "default", retry after the token is automatically created and added to the service account, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=ServerTimeout, status=Failure, additionalProperties={}).
```
</details> <br>

In OpenShift master logs I've found the next lines related to that namespace:

<details>
<summary>log</summary>

```
{"log":"I0205 17:18:00.949584   29164 trace.go:76] Trace[117766802]: \"Create /api/v1/namespaces/workspace8cvdb4ialql0zpoj/secrets\" (started: 2018-02-05 17:17:50.899770003 +0000 UTC) (total time: 10.049796s):\n","stream":"stderr","time":"2018-02-05T17:18:00.949638371Z"}
{"log":"Trace[117766802]: [10.049796s] [10.049737318s] END\n","stream":"stderr","time":"2018-02-05T17:18:00.949651153Z"}
{"log":"E0205 17:18:00.950093   29164 tokens_controller.go:266] error synchronizing serviceaccount workspace8cvdb4ialql0zpoj/default: timeout\n","stream":"stderr","time":"2018-02-05T17:18:00.950181639Z"}
```
</details>

##### Version

```
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce
I did not find a way to stably reproduce this problem(but I'm working on it)

##### Current Result
Pod creation failed

##### Expected Result
Pod must be created and become a Running

##### Additional Information
I have OCP deployed on docker.
Docker version: 17.04.0-ce
API version:  1.28

OS version: openSUSE 42.3 (x86_64)

fabric8 client version:
openshift-client: 3.1.0
kubernetes-model: 2.0.4

**Comment by jwforres** [comment]
cc @liggitt
