### ISSUE TITLE
Build resource should align with upstream v1beta3 conventions

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#1848]
We should assess if we want to align our Build resource with changes made upstream as part of v1beta3.

I can see an argument for doing the following:

1. Modify Build to clearly separate BuildSpec from BuildStatus
2. Place BuildParameters and Config in BuildSpec since these are user modifiable fields
3. Rename current Build.Status to Build.Phase to align with terminology changes upstream
4. Place Build.Phase, Build.Message, Build.StartTimestamp and Build.CompletionTimestamp in BuildStatus since these are fields only modifiable by our build controller

Separate API to support updates of BuildSpec separate from BuildStatus so you have

PUT /build/foo -> updates ObjectMeta and BuildSpec
PUT /build/foo/status -> updates BuildStatus only

Policy should only allow the build controller to update BuildStatus

Discuss @smarterclayton @bparees @liggitt @deads2k

**Comment by derekwaynecarr** [comment]
Hmm, I may be off here, and I was forgetting about the BuildConfig object being the one more traditionally modified by an end-user.  If that was the case, I am less concerned, but not a huge expert in this area yet.

**Comment by smarterclayton** [comment]
----- Original Message -----
> We should assess if we want to align our Build resource with changes made
> upstream as part of v1beta3.
> 
> I can see an argument for doing the following:
> 
> 1. Modify Build to clearly separate BuildSpec from BuildStatus
> 2. Place BuildParameters and Config in BuildSpec since these are user
> modifiable fields

Config must be immutable (also probably not able to be set after creation).  We don't really need parameters to be anything other than an embedded object though - I don't think we need:

{
  "spec: {
    "parameters": {
      "output": {
      }
    }
  }
}

but 

{
  "spec: {
    "output": {
    },
    "from": {
    }
  }
}

And internally:

type BuildSpec struct {
  BuildParameters `json:",inline"`
  From *ObjectReference
}

**Comment by deads2k** [comment]
> Config must be immutable (also probably not able to be set after creation).

We can have separate permission for create and update.  Should project admins and editors be allowed to create buildConfigs, but not update them?  Are there other asymmetric resources like that?

**Comment by smarterclayton** [comment]
Immutability is handled in the rest update code like uid immutability.  Doesn't have to be handled with policy.

----- Original Message -----
