### ISSUE TITLE
`test_pull_request_origin_unit` sometimes fails without an explanation or (obvious) reason

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#18497]
It says:
```
[WARNING] While the jUnit report found no failed tests, the `go test` process failed.
[WARNING] This usually means that the unit test suite failed to compile.
[ERROR] hack/test-go.sh exited with code 1 after 00h 36m 10s
make: *** [test-unit] Error 1
[ERROR] PID 12927: hack/lib/build/environment.sh:172: `return "${exitcode}"` exited with status 2.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/build/environment.sh:172: `return "${exitcode}"`
[INFO] 		  2: hack/lib/build/environment.sh:281: os::build::environment::withsource
[INFO] 		  3: hack/env:42: os::build::environment::run
[INFO]   Exiting with code 2.
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: RUN UNIT TESTS [00h 38m 35s] ##########
```

Started to see this here https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18495/test_pull_request_origin_unit/9196/
Went through the S3 artifacts but couldn't see what failed :/ (Apparently something in the test image does.)

The I saw the same just now with https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18495/test_pull_request_origin_unit/9196/ from https://github.com/openshift/origin/pull/18495/files which is very unlikely to make unit tests not to compile given how the change is small and where it's located.

**Comment by stevekuznetsov** [comment]
Yeah, I've noticed this as well but wasn't really sure what to do here... the process had no output to `stderr` and just exited non-zero. Wasn't really sure how to debug this in any way. @tnozicka any thoughts?

**Comment by tnozicka** [comment]
Not really sure what that could be, I guess we hide the error somewhere. Can we run with `bash -x` for a while inside the image?

**Comment by stevekuznetsov** [comment]
We could but not sure that would help, the `stderr` redirect is below that level

https://github.com/openshift/origin/blob/master/hack/test-go.sh#L140

**Comment by stevekuznetsov** [comment]
It is empty because `go test` had no output to `stderr`

**Comment by tnozicka** [comment]
badly phrased; meant the same thing. The question is why there is no error output but exit status 2.

`bash -x` was really all I had :(

**Comment by stevekuznetsov** [comment]
See also https://github.com/openshift/origin/issues/17881

**Comment by sosiouxme** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16658/test_pull_request_origin_unit/9523/ yesterday
