### ISSUE TITLE
Accessing Jolokia - TLS Handshake Timeout

### ISSUE THREAD

**Issue by glennodickson** [openshift/origin#18499]
I've successfully deployed the [Camel AMQ QuickStart](https://github.com/fabric8-quickstarts/karaf2-camel-amq) to Openshift and would like to view the queues, messages etc from console from the "Open Java Console" link. Everytime I click this I get TLS timeout error.

So I ran this command on the master and this is the results.

##### Current Result
Command:
`curl -v https://192.168.99.100:8443/api/v1/namespaces/default/pods/https:karaf2-camel-amq-4-9nltg:8778/proxy/jolokia/version -H "Authorization: Bearer CfL-RAV91E98lw7cS9tZuJqKLyEDU9yLlFHQAd4_00k" --insecure`

Output:

> * STATE: INIT => CONNECT handle 0x6000911d0; line 1402 (connection #-5000)
> * Added connection 0. The cache now contains 1 members
> * Trying 192.168.99.100...
> * STATE: CONNECT => WAITCONNECT handle 0x6000911d0; line 1455 (connection #0)
> * Connected to 192.168.99.100 (192.168.99.100) port 8443 (#0)
> * STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x6000911d0; line 1562 (connection #0)
> * ALPN, offering http/1.1
> * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
> * successfully set certificate verify locations:
> * CAfile: /usr/ssl/certs/ca-bundle.crt
> CApath: none
> * TLSv1.2 (OUT), TLS header, Certificate Status (22):
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> * STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x6000911d0; line 1576 (connection #0)
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Request CERT (13):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Certificate (11):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS change cipher, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
> * ALPN, server accepted to use http/1.1
> * Server certificate:
> * subject: CN=10.0.2.15
> * start date: Nov 14 16:16:44 2017 GMT
> * expire date: Nov 14 16:16:45 2019 GMT
> * issuer: CN=openshift-signer@1510676202
> * SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
> * STATE: PROTOCONNECT => DO handle 0x6000911d0; line 1597 (connection #0)
> * GET /api/v1/namespaces/default/pods/https:karaf2-camel-amq-4-9nltg:8778/proxy/jolokia/version HTTP/1.1
> * Host: 192.168.99.100:8443
> * User-Agent: curl/7.49.0
> * Accept: /
> * Authorization: Bearer CfL-RAV91E98lw7cS9tZuJqKLyEDU9yLlFHQAd4_00k
> *
> * STATE: DO => DO_DONE handle 0x6000911d0; line 1659 (connection #0)
> * STATE: DO_DONE => WAITPERFORM handle 0x6000911d0; line 1786 (connection #0)
> * STATE: WAITPERFORM => PERFORM handle 0x6000911d0; line 1796 (connection #0)
> * HTTP 1.1 or later with persistent connection, pipelining supported
> * HTTP/1.1 503 Service Unavailable
> * Cache-Control: no-store
> * Date: Tue, 06 Feb 2018 15:45:10 GMT
> * Content-Length: 100
> * Content-Type: text/plain; charset=utf-8
> * Error: 'net/http: TLS handshake timeout'
> * STATE: PERFORM => DONE handle 0x6000911d0; line 1955 (connection #0)
> * multi_done
> * Connection #0 to host 192.168.99.100 left intact
> Trying to reach: 'https://172.17.0.10:8778/jolokia/version'
> 

##### Version
Openshift version: 
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v3.7.0-rc.0+e92d5c5
kubernetes v1.7.6+a08f5eeb62

OS : Windows 10 Prof
VM : Virtual Box

##### Steps To Reproduce
1. Karaf pod successfully running
2. In the Web Console I clicked on the link "Open Java Console" but returns TLS timeout error.

If anyone can help I would really appreciate it.

**Comment by jwforres** [comment]
@openshift/sig-master 

since the TLS timeout is the proxy communicating with the pod

**Comment by liggitt** [comment]
is the pod running successfully? if you run `oc port-forward` to that pod on that port, are you able to access it via localhost?

**Comment by glennodickson** [comment]
Thanks for your responce. Yep tried the following:

> oc port-forward karaf-camel-rest-ose-cbpmt 5005:8778
> https://locahost:5005/jolokia/?maxDepth=7&maxCollectionSize=500&ignoreErrors=true&canonicalNaming=false

Returns 'site can't be reached'
The image in the pom.xml is : 
    <docker.from>registry.access.redhat.com/jboss-fuse-6/fis-karaf-openshift:1.0</docker.from>
I'm really unsure how to explore this issue as I'm kind of new to OCP so any suggestions would be really great!

**Comment by glennodickson** [comment]
@jimmidyson  hi I read your [article](https://blog.fabric8.io/fabric8-s-kubernetes-tooling-for-java-developers-c8edd1617383) and was wondering if you could assist regarding jolokia. It's really frustrating!
 
Thanks

**Comment by glennodickson** [comment]
@rhuss I saw your [post](https://github.com/fabric8io/agent-bond/issues/14) and was wondering if you could suggest anything pls? I would greatly appreciate it.

**Comment by rhuss** [comment]
> https://locahost:5005/jolokia/?maxDepth=7&maxCollectionSize=500&ignoreErrors=true&canonicalNaming=false

I guess you already spotted the typo here, should be `localhost`, not `locahost`.
If you can rule out that's a typo, then Jolokia has not been properly attached to the JVM during startup. Unfortunately I'm on the road this week, but I can have a look to the mentioned quickstart to try to reproduce it.

But please check first, whether you can't really connect (you can also try a 'telnet localhost 5005' just to check the socket).
