### ISSUE TITLE
use oauthauthorizetoken can not obtain an OAuthAccessToken

### ISSUE THREAD

**Issue by testfielder** [openshift/origin#18502]
`# oc get oauthauthorizetoken -o yaml`
```
apiVersion: v1
items:
- apiVersion: oauth.openshift.io/v1
  clientName: openshift-challenging-client
  codeChallenge: PC99YReTy6bIyeKKt4vK2IaHPxiXW4ZP35d1eJ-NLxE
  codeChallengeMethod: S256
  expiresIn: 500
  kind: OAuthAuthorizeToken
  metadata:
    creationTimestamp: 2018-02-07T14:32:02Z
    name: n9uDhb6B2b2XA2h1WbbvnOIVToU__ze9miV6gTzqBQg
    namespace: ""
    resourceVersion: "249000"
    selfLink: /apis/oauth.openshift.io/v1/oauthauthorizetokens/n9uDhb6B2b2XA2h1WbbvnOIVToU__ze9miV6gTzqBQg
    uid: a9c91a35-0c13-11e8-af4d-fa163eafcb96
  redirectURI: https://host-maste:8443/oauth/token/implicit
  scopes:
  - user:full
  userName: pm1
  userUID: 8d1734d8-0bde-11e8-a951-fa163eafcb96
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
```
# curl -k  -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/json" "https://host-maste:8443/oauth/token?code=n9uDhb6B2b2XA2h1WbbvnOIVToU__ze9miV6gTzqBQg&grant_type=authorization_code&redirect_uri=https://host-master:8443/oauth/token/implicit&client_id=openshift-challenging-client&client_secret=''" 
{"error":"unauthorized_client","error_description":"The client is not authorized to request a token using this method."}
```

**Comment by testfielder** [comment]
Hi all, pls help about that,thx.

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by liggitt** [comment]
The authorize token was obtained with a PKCE challenge (note the codeChallenge and codeChallengeMethod fields set), so the token request must also include a code_verifier parameter.

See https://tools.ietf.org/html/rfc7636 for more information

/close

**Comment by testfielder** [comment]
hi, @liggitt i follow this [tutorial](https://tools.ietf.org/html/rfc6749#section-4.1.3)
```
Access Token Request

   The client makes a request to the token endpoint by sending the
   following parameters using the "application/x-www-form-urlencoded"
   format per Appendix B with a character encoding of UTF-8 in the HTTP
   request entity-body:

   grant_type
         REQUIRED.  Value MUST be set to "authorization_code".

   code
         REQUIRED.  The authorization code received from the
         authorization server.

   redirect_uri
         REQUIRED, if the "redirect_uri" parameter was included in the
         authorization request as described in Section 4.1.1, and their
         values MUST be identical.

   client_id
         REQUIRED, if the client is not authenticating with the
         authorization server as described in Section 3.2.1.

   If the client type is confidential or the client was issued client
   credentials (or assigned other authentication requirements), the
   client MUST authenticate with the authorization server as described
   in Section 3.2.1.

```

**Comment by liggitt** [comment]
Yes, but that assumes you obtained the authorization code using https://tools.ietf.org/html/rfc6749#section-4.1.1

The authorization code you referenced was obtained with additional PKCE parameters as described in https://tools.ietf.org/html/rfc6749#section-4.1.1

**Comment by testfielder** [comment]
@liggitt that is very nice of you,thx. I will learn more deeply.

**Comment by testfielder** [comment]
‵‵‵
# oc get oauthauthorizetoken -o yaml
apiVersion: v1
items:
- apiVersion: oauth.openshift.io/v1
  clientName: openshift-challenging-client
  expiresIn: 500
  kind: OAuthAuthorizeToken
  metadata:
    creationTimestamp: 2018-02-08T02:36:36Z
    name: hPYr_7kKPoughokLf2piKo1IX9jdtu_3sfzVcrYzAho
    namespace: ""
    resourceVersion: "337469"
    selfLink: /apis/oauth.openshift.io/v1/oauthauthorizetokens/hPYr_7kKPoughokLf2piKo1IX9jdtu_3sfzVcrYzAho
    uid: e26a4b28-0c78-11e8-af4d-fa163eafcb96
  redirectURI: https://host-master:8443/oauth/token/implicit
  scopes:
  - user:full
  userName: pm1
  userUID: 8d1734d8-0bde-11e8-a951-fa163eafcb96
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
[root@host-172-16-120-148 master]# curl -k "https://host-master:8443/oauth/token?code=hPYr_7kKPoughokLf2piKo1IX9jdtu_3sfzVcrYzAho&grant_type=authorization_code&redirect_uri=https://host-master:8443/oauth/token/implicit&client_id=openshift-challenging-client%3Atestclient&client_secret=''"
{"error":"unauthorized_client","error_description":"The client is not authorized to request a token using this method."}
```

**Comment by liggitt** [comment]
Your client id and secret are incorrect. Client id should be `openshift-challenging-client` and your client secret should be empty, not `''`

**Comment by testfielder** [comment]
@liggitt thanks a lot.
