### ISSUE TITLE
Avoid using routes for prometheus by using services instead

### ISSUE THREAD

**Issue by e-minguez** [openshift/origin#18500]
https://github.com/openshift/origin/blob/d5f8d8b4877885df02fe09082ac7ed07696209ac/examples/grafana/setup-grafana.sh#L53

I think it would be better to avoid going through the route to query prometheus. Maybe deploying grafana in the same project than prometheus or joining the projects will be better instead.

**Comment by zeari** [comment]
> I think it would be better to avoid going through the route to query prometheus. Maybe deploying grafana in the same project than prometheus or joining the projects will be better instead.

@e-minguez What would be the benefit of joining them? I dont think going through ha route is that much overhead

cc @mrsiano

**Comment by e-minguez** [comment]
Basically avoid generating unneeded network traffic to the routers using services instead. I have no idea if grafana generates a big amount of traffic, but I think *ideally* you don't want to go outside the OCP SDN through the router to go "inside"

**Comment by mrsiano** [comment]
Intersting.
the traffic depends on queries \ the dashbord which holds collection of diffrent queries and their duration.
the thing is grafana must have some datasource in our case is prometheus, and by design any datasource typically needs a url.

to use the service directly, we probably gonna need a custom grafana datasource form.

but on the other hand, we should have the ability to use route.

**Comment by jeremyeder** [comment]
A route to prometheus is itself useful (and probably a requirement at least for us as it is the best place to prototype new queries).  But that does not mean Grafana has to talk to Prometheus over the route.  I agree there's no reason for Grafana to talk to Prom over a route if a service also works.  And co-locating them is also a useful optimization in that it will reduce network bandwidth and latency between the associated components (although it's not very heavy).  Service traffic still goes through kube-proxy, but at least it wouldn't make a round-trip through the router.  Overall I'd support this small change.  Seems obvious in retrospect.

A 2nd optimization would be to use an affinity rule (or similar scheduler feature) to make Grafana land on the same node as Prometheus.
