### ISSUE TITLE
osc new-project needs a better message for collisions

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1851]
```
$ osc new-project satellite-content
F0422 01:00:05.987077    2977 request_project.go:58] namespaces "satellite-content" already exists
```

Doesn't give the pretty message.  Also, shouldn't show the generic message, should show "A project named "" already exists" when it gets a conflict error.  Also, Dan was wrong, as usual.

**Comment by deads2k** [comment]
I accidentally fixed this at some point.  You now get
```
osc new-project foo
Error from server: project "foo" already exists
```

@liggitt please close.
