### ISSUE TITLE
What are our plans for exposing utilities for consumers of client-go?

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#18516]
There are loads of utilites in places like `pkg/image/apis/image/helper.go` that are super useful when working with the ... intricacies ... of some of our API surfaces. Do we have a plan to expose these in a stand-alone repository so they can be imported by *i.e.* consumers of `client-go`?

/cc @smarterclayton @deads2k @bparees 
/kind question

**Comment by mfojtik** [comment]
instead of moving them to client-go, we can clean them up to be importable externally without importing half of origin :-)

**Comment by stevekuznetsov** [comment]
Also true!
