### ISSUE TITLE
Cluster provision failed - ansible cannot reach API (DNS issue)

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#18525]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18437/test_pull_request_origin_extended_conformance_gce/15858/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/13701/test_pull_request_origin_extended_conformance_gce/15857/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18478/test_pull_request_origin_extended_conformance_gce/15855//test_pull_request_origin_extended_conformance_gce/15851/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/test_pull_request_origin_extended_conformance_gce/15850/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18476/test_pull_request_origin_extended_conformance_gce/15849/

Forked from https://github.com/openshift/origin/issues/14597#issuecomment-364097983
/priority P0
/sig cluster-lifecycle 
/assign @smarterclayton @sdodson

**Comment by smarterclayton** [comment]
I’m on a plane.  @sdodson or someone from @openshift/sig-master is going to need to look.

**Comment by sdodson** [comment]
`fatal: [ci-prtest-5a37c28-15857-ig-m-km2p]: FAILED! => {"attempts": 120, "changed": false, "cmd": ["curl", "--silent", "--tlsv1.2", "--cacert", "/etc/origin/master/ca-bundle.crt", "https://internal-api.prtest-5a37c28-15857.origin-ci-int-gce.dev.rhcloud.com:8443/healthz/ready"], "delta": "0:00:00.012001", "end": "2018-02-08 10:56:15.785153", "msg": "non-zero return code", "rc": 6, "start": "2018-02-08 10:56:15.773152", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}`

curl exit code 6 is dns

**Comment by kargakis** [comment]
Lowering prio as this does not seem as a P0 anymore

/remove-priority P0
/priority P2
