### ISSUE TITLE
OpenShift Deployments cannot reach GitHub

### ISSUE THREAD

**Issue by gauravojha** [openshift/origin#18521]
When I try to deploy the ruby-ex example on my OpenShift Origin instance, it times out when trying to clone the repo from GitHub. However, the host on which OpenShift is running on can easily clone the same. 

If it is cluster networking issue, can someone post any ideas as to where I might look. For instance, a list of ports I could enable and check if that helps. I currently have opened ports 8443 and 53. 

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. on OpenShift Origin, oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git
2. Open the build log on the web console

##### Current Result
The build fails when trying to clone the ruby-ex github

##### Expected Result
It shouldn't fail. 

##### Additional Information
Issues with similar description are available on GitHub, but I couldn't find any resolutions on any one. Either they are still open, or have been closed due to inactivity.

**Comment by mfojtik** [comment]
Ben, we should probably have some troubleshooting for these problems somewhere :-)

**Comment by gauravojha** [comment]
Solved it by using the following instructions at the following [link](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md)

firewall-cmd --permanent --new-zone dockerc
firewall-cmd --permanent --zone dockerc --add-source 172.17.0.0/16
firewall-cmd --permanent --zone dockerc --add-port 8443/tcp
firewall-cmd --permanent --zone dockerc --add-port 53/udp
firewall-cmd --permanent --zone dockerc --add-port 8053/udp
firewall-cmd --reload

Thanks.  Closing the issue.
