### ISSUE TITLE
pod application in go code sees i/o: timeout error when making a put request to HTTP server

### ISSUE THREAD

**Issue by DanyC97** [openshift/origin#18535]
We have observed in one capture a pause, the dump file is available in a box location

##### Version
```
oc version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://dev3-ivp-coe-vip:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

```

##### Steps To Reproduce
We still trying to have a consistent reproducible test case however we do have the initial tcpdump capture (took from a node using `tcpdump -i any`) which i can share

##### Current Result
The application log receive a `i/o timeout` error which is causing packets to be lost

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by rajatchopra** [comment]
Assuming its the openshift-sdn plugin running,
Is the http request okay from the node?
Can you capture tcpdump on the tun0 device also and share?

**Comment by DanyC97** [comment]
thank you @rajatchopra but after exteding testing we couldn't get to a reproducible pattern to exercise and collect all the info, it was all intermittent.

Will close the issue for now, thanks again for interest
