### ISSUE TITLE
Openshift reports a project as deleted before it's completely removed

### ISSUE THREAD

**Issue by pgier** [openshift/origin#18566]
Using the 'oc delete project <name>' command returns quickly with the message "project <name> deleted".  However, at this point it has only been marked for deletion and has not been removed from the system.  The message should say instead "project <name> marked for deletion".

Immediately after the oc delete command has returned, using 'oc projects' will still show the deleted project.  In addition, there is still some time after the project disappears from 'oc projects' where a new project with the same name cannot be added to the system.

##### Version
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. oc new-project foo
2. oc delete project foo && oc projects | grep foo && oc new-project foo

##### Current Result
'oc delete project foo' prints "project foo deleted"
Project disappears from output of 'oc projects' before it's completely removed from the system.

##### Expected Result
'oc delete project foo' should print "project foo marked for deletion"
When 'oc projects' no longer contains the project, it should be possible to create a new project with the same name.

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by liggitt** [comment]
> there is still some time after the project disappears from 'oc projects' where a new project with the same name cannot be added to the system.

that is expected, and is caused by the permissions for the user (which are recorded inside the names) getting removed as part of namespace termination, prior to the namespace itself being removed.
