### ISSUE TITLE
access to docker registry through other subnet via the load balancer?

### ISSUE THREAD

**Issue by ybaumy** [openshift/origin#18560]
Trying to get docker registry to work from another network through the loadbalancer HAproxy.

Im getting an error here and need help setting up the haproxy.cfg

docker login -u $(oc whoami) -p $(oc whoami -t) docker-registry-default.os.vdc1-ext.local:5000
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to https://docker-registry-default.os.vdc1-ext.local:5000/v2/ failed with status: 400 Bad Request

##### Version

oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://os-lb-1.vdc1-ext.local:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce

setup origin with default registry like it is created through ansible playbook config.yml

then

try to connect via load balancer and openshift provided from the exposed service.

setup haproxy.cfg to connect to port 5000. you may also need to setup iptables on the LB

i also copied the ca.crt from the load balancer to the client

the oc router is configured as passthrough

here the config

---- haproxy.cfg start -----

global
    maxconn     20000
    log         /dev/log local0 info
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    user        haproxy
    group       haproxy
    daemon
    ssl-server-verify none
    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL). This list is from:
    #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
    ssl-default-bind-options no-sslv3

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats
    tune.ssl.default-dh-param 2048

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          300s
    timeout server          300s
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 20000

listen stats
    bind :9000
    mode http
    stats enable
    stats uri /

frontend  atomic-openshift-api
    bind *:8443
    default_backend atomic-openshift-api
    mode tcp
    option tcplog

backend atomic-openshift-api
    balance source
    mode tcp
    server      master0 192.168.50.72:8443 check
    server      master1 192.168.50.71:8443 check
    server      master2 192.168.50.70:8443 check

frontend registry
    mode http
    bind :5000 ssl crt /etc/haproxy/foo.pem no-sslv3 ciphers TLSv1.2
    http-request set-header X-Forwarded-Proto https if { ssl_fc }
    option httpclose
    option forwardfor
    log global
    default_backend registryback

backend registryback
    mode http
    option forwardfor
    server registryback docker-registry-default.os.vdc1-ext.local:5000 ssl check fastinter 1000
    rspidel ^server
    option http-server-close
    cookie SERVERID insert indirect nocache
    option            redispatch
    rspadd  Server:\ w00t\ (Poneycom;\ Unix4lulz/0.1.8)

---- haproxy.cfg end  -----

##### Current Result
Error response from daemon: login attempt to https://docker-registry-default.os.vdc1-ext.local:5000/v2/ failed with status: 400 Bad Request

##### Expected Result

if this is not supposed to work then please show me a way how i can enable external (other vlan/subnet) access to the docker registry.

**Comment by kargakis** [comment]
@openshift/sig-networking 
/kind question

**Comment by ybaumy** [comment]
even a .. thats not how it works and nobody works like that ..  would help me
