### ISSUE TITLE
[3.7][blocked] - openshift-web-console install block realease-3.7 where it even shouldn't be installed

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#18573]
installing openshift-web-console **permanently blocks** tests/merges on release-3.7 branch where it shouldn't be installed at all (per https://github.com/openshift/origin/issues/18569#issuecomment-364927103)

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18524/test_pull_request_origin_extended_conformance_gce/16052/

and 20+ more

@openshift/sig-continuous-delivery

**Comment by sdodson** [comment]
@smarterclayton @stevekuznetsov Sam's PR will make this problem go away, but we should look into making the GCE jobs use the same branch of openshift-ansible as they do for origin.
