### ISSUE TITLE
Add support to update specific environment variables from resources

### ISSUE THREAD

**Issue by PhilipGough** [openshift/origin#18574]
[Add support to update specific environment variables from resources]

When running the `oc env --from` command, I would like to be able to specify which keys from the ConfigMap or Secret that should be set.

This is useful incases where there is a ConfigMap or Secret shared between multiple applications in a namespace, but all environment variables might not be required/wanted in the application itself.

Provide a way to pass a list of keys that would be mounted.

**Comment by soltysh** [comment]
Adding @PhilipGough who's actually working on it.

**Comment by PhilipGough** [comment]
Linking to upstream change https://github.com/kubernetes/kubernetes/pull/60636
