### ISSUE TITLE
Issue with adding new express routes

### ISSUE THREAD

**Issue by pazzipanda** [openshift/origin#18609]
Can't get new express routes to work

##### Version
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
openshift v3.7.23

##### Steps To Reproduce
1. Install the repository
2. copy the app.get('/pagecount' [...]) and change it to app.get('/page'[..]) ((or basicly anything)

##### Current Result
Throws  Cannot GET /page 

##### Expected Result
Same as GET /pagecount

##### Additional Information
So I tried adding another route to the express router. It worked just fine on localhost, but when I push the code to openshift, a get to the new route returns with the "Cannot GET /...". I simpled it down to just copy-paste the existing app route /pagecount and just changed the name to app.get('page*' [..]) so that I'm sure nothing else interferes with the route. Still not getting me any results when GETting the route with postman or visiting it directly on the browser.

I'm pretty  new to openshift, have I missed something? Do I maybe need to create the routes at some other place than the server.js too? Help's appretiated!

**Comment by pazzipanda** [comment]
here's the link to my server.js file

https://github.com/pazzipanda/leagueStatus/blob/master/server.js

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by coreydaley** [comment]
Same issue as here, which was resolved: https://github.com/sclorg/nodejs-ex/issues/164
