### ISSUE TITLE
oc editing all resources -  '--all' unknown parameter

### ISSUE THREAD

**Issue by AuHau** [openshift/origin#18644]
I am trying to patch all resources in my namespace with following command:

`oc patch dc --all -p '{"spec":{"template": {"spec": {"containers": [{"resources": {"limits" : {"cpu": "150m", "memory": "150Mi"}}}]}}}}'`

But I get an error `unkown flag: --all`. 

When I run it without it I get an error: `error: resource(s) were provided, but no name, label selector, or --all flag specified`.

Am I missing something? Or is it a bug? 

##### Version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.nine.ch:8443
openshift v3.6.173.0.96
kubernetes v1.6.1+5115d708d7

**Comment by AuHau** [comment]
Small update I tried similar thing with the `scale` command (I wanted to scale all DeploymentConfigs to fixed number of replicas) and got the same error and messages.

**Comment by damemi** [comment]
I think I have an upstream patch for this, will update here
