### ISSUE TITLE
Document Container Garbage Collection

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#1865]
We need to have some documentation on container garbage collection configuration.

**Comment by danmcp** [comment]
@sdodson Should this be against openshift-docs?

**Comment by sdodson** [comment]
@danmcp either developer or admin/user documentation is fine. 

I've wedged my OSE3 host a few times with thousands of failed containers so I was looking for some description as to how and when non running containers were removed. I couldn't find anything that described the expected behavior.

Though looking at the code again https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/node.go#L179 seems to indicate that there should be no more than 100 dead containers, i've currently got 800+ so I'm not certain that GC is working at all.

**Comment by danmcp** [comment]
@csrwng Any updates?

**Comment by csrwng** [comment]
So the issue that @sdodson was seeing has been fixed because we are now actually doing gc in origin. Just as in Kube. So the only thing is that we need to add it to the user doc. I wouldn't say this is a release blocker.

**Comment by smarterclayton** [comment]
GC is controllable via direct kubelet arguments (same flag as upstream), set onto kubeletArguments in the config.  Be aware it is a map of string keys to an array of string values in YAML.

**Comment by smarterclayton** [comment]
This should be a docs bug

**Comment by csrwng** [comment]
Garbage collection is already documented in kubernetes... can we just point to it? 
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/garbage-collection.md

**Comment by smarterclayton** [comment]
We'd want to include it int he origin docs.

**Comment by sdodson** [comment]
Docs issue asking that kubernetesMaster and kubeletArguments documentation be automatically generated? https://github.com/openshift/openshift-docs/issues/1151

**Comment by sdodson** [comment]
I'm not terribly interested in container GC specifically, at the time it wasn't working, now it is.
