### ISSUE TITLE
no route to github from pod

### ISSUE THREAD

**Issue by cedrico2016** [openshift/origin#18655]
[provide a description of the issue]
Creation of a new app using S2I providing a github repository. A backslash is added a the end of the repository URL causing a failure while pulling the repository. 

##### Version
[provide output of the `openshift version` or `oc version` command]

oc v3.7.23
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.1+a8deba5-34
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
I tried it several times with different URLs
`oc new-app centos/ruby-22-centos7 https://github.com/openshift/ruby-ex.git`

##### Current Result
 ```
| Cloning "https://github.com/openshift/ruby-ex.git " ...
  | error: fatal: unable to access 'https://github.com/openshift/ruby-ex.git/':  Failed connect to github.com:443; No route to host

```
##### Expected Result
Expected should be that the repository is correctly pulled. 

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]: output can be found here: https://gist.github.com/cedrico2016/74dd31216a6e849b2a85845e69e7e00a#file-ocadmdiagnostics-txt

[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]: Ouptut can be found here: https://gist.github.com/cedrico2016/74dd31216a6e849b2a85845e69e7e00a#file-ocgetall-json

[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
The slash is not the issue. You're networking is broken. Hence no route to github.

@jwforres fyi.

**Comment by cedrico2016** [comment]
@bparees  it may be possible that a broken networking was the problem. because i tried it once more later and everything was ok. Thank you.
