### ISSUE TITLE
proxy protocol is not working

### ISSUE THREAD

**Issue by apekshasao** [openshift/origin#18671]
hi,
 I am trying to enable proxy protocol in my setup which is running in AWS after running the oc command my total openshift stack is unreachble. Could you please help me with the same.

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v1.4.1

##### Steps To Reproduce
1. [step 1]oc env dc/(your)router ROUTER_USE_PROXY_PROTOCOL=true

##### Current Result
 It is not enabling proxy protocol
##### Expected Result
Proxy protocol should be enbled
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jwforres** [comment]
@openshift/sig-networking
