### ISSUE TITLE
Missing Centos PaaS RPM packages for openshift origin v3.7.1

### ISSUE THREAD

**Issue by ogunheper** [openshift/origin#18679]
Although the latest release seems to be 3.7.1 at https://github.com/openshift/origin/releases/latest since 16th of Jan., the Centos PaaS RPMs seems missing at http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/

Would it be possible to build RPM packages for v3.7.1 and release them on the Centos PaaS repository?

I will be more then happy if I could help to build those rpms, so feel free to show me the way.

Best regards and thanks is advance :)

**Comment by DanyC97** [comment]
@ogunheper i think this can be closed in favor of https://github.com/openshift/origin/issues/18184

**Comment by jwforres** [comment]
closing in favor or #18184
