### ISSUE TITLE
Why is the oc tool so big?

### ISSUE THREAD

**Issue by daald** [openshift/origin#18672]
The file openshift-origin-client-tools-v3.7.1-ab0f056-linux-64bit.tar.gz is 38.4M in size, and the extracted oc tool has a size of 191M.

This is far the biggest linux executable file I've ever seen, and the high compression ratio of almost 5:1 shows that there is not that much binary inside.

Looking inside, I find uncompressed html and css, which could at least be compressed. But I also wonder what's the reason for a html page inside a command line tool.

##### Version
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

but the file is big since at least oc 1.4.1

##### Steps To Reproduce
1. Download the file from https://github.com/openshift/origin/releases/download/v3.7.1/openshift-origin-client-tools-v3.7.1-ab0f056-linux-64bit.tar.gz
2. Check its size

##### Current Result

```
$ ls -lh ./oc
-rwxr-xr-x 1 dev dev 191M Jan 31 08:25 ./oc
```

##### Expected Result

    a size of about 20M

Some of the biggest executables on my system, to compare:

```
# find / -type f -executable -exec du \{\} + | sort -n

-rwxr-xr-x 1 dev  dev  31M Jan 31 09:05 /opt/Android/Sdk/emulator/qemu/linux-x86_64/qemu-system-aarch64
-rwxr-xr-x 1 dev  dev  77M Jan 24 23:02 /opt/Postman/Postman
-rwxr-xr-x 1 root root 31M Oct 12 04:38 /usr/bin/dockerd
-rwxr-xr-x 1 root root 23M Oct 14 22:35 /usr/lib/gcc/x86_64-linux-gnu/7/cc1plus
-rwxr-xr-x 1 root root 73M Jan 30 15:33 /usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjfxwebkit.so
-rwxr-xr-x 1 dev  dev  191M Jan 31 08:25 /usr/local/bin/oc
```

**Comment by mar1ged** [comment]
What you describe applies to all binaries compiled by golang, so openshift can't be blamed for the admittedly inefficient way Go creates its binaries

**Comment by php-coder** [comment]
@stevekuznetsov @smarterclayton

**Comment by stevekuznetsov** [comment]
We've had this comment a number of times. The comment about this being an issue with Go, the compiler, and generated code is correct. Not sure we can really do much about it. See also [the official doc](https://golang.org/doc/faq#Why_is_my_trivial_program_such_a_large_binary).
