### ISSUE TITLE
Build is failing with HTTP 502 for big repositories.

### ISSUE THREAD

**Issue by droslean** [openshift/origin#18674]
Build is failing when trying to clone a big repository.
strategy: sourceStrategy
type: Git

##### Error
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly

##### Version
oc v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f

##### Steps To Reproduce
1. Create a build with sourceStrategy and a big git repo.
2. Start the build

##### Current Result
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly

**Comment by coreydaley** [comment]
@droslean How big of a repo are you using?  Is it publicly available so that I can test with it?

**Comment by droslean** [comment]
@coreydaley The repo I used is 160MB with a lot of files (specific 4235). 
Unfortunately, the repo is not publicly available to test it.

**Comment by coreydaley** [comment]
@droslean Thanks for the info.

**Comment by coreydaley** [comment]
@droslean I was able to set the source for a build to https://github.com/torvalds/linux, which is quite large, and did not encounter any issues or errors.

Can you try using a large repo on github as the source and see if you have the same issues?  It could potentially be an issue with cloning over a VPN to the internal source?  Are you able to clone that repository to your workstation that is running Origin?

**Comment by coreydaley** [comment]
It may also be worth checking the origin logs and see if you are running out of resources on your workstation.

**Comment by bparees** [comment]
Is it hosted on github or elsewhere? There could be an issue in the git server, certainly a 502 would make me think it's a git server problem.

**Comment by droslean** [comment]
The strange thing is that I am able to clone the repo from a container but not from a Build.  I am convinced that the problem should be in the git server but it's a pity that openshift doesn't give us the ability to find out why. Maybe it's needed to make more configuration in git for builds to include also cases like this.

Is there any way to provide you more information on what is happening while I getting that error?

**Comment by coreydaley** [comment]
@droslean 
Are you using an http proxy on your workstation?

**Comment by droslean** [comment]
@coreydaley no

**Comment by bparees** [comment]
Try doing the clone manually from within a pod running on your cluster (via
oc rsh).  The jenkins image is good for this.  That will allow you to debug
whatever you want and simulates what the build is doing.


Ben Parees | OpenShift

**Comment by droslean** [comment]
@bparees I have already done that. Please check previous comments.

**Comment by bparees** [comment]
> @bparees I have already done that. Please check previous comments.

sorry I missed that, but that effectively replicates what the build does.  The only differences would be:

1) possibly the git version in the build pod vs the pod you ran
2) the node the pod is running on.

Is the issue intermittent?  Can you confirm you can manually git clone from within a pod running on the same node that your build pods fail on?

**Comment by coreydaley** [comment]
@droslean bump, any updates on the requested info from @bparees ?

**Comment by coreydaley** [comment]
@droslean bump ^^

**Comment by droslean** [comment]
@coreydaley  With v3.10.0 of the origin-sti-builder image, it seems the issue is resolved. The issue can be closed.
