### ISSUE TITLE
Upgrade from 1.5.1 to 3.6 fails.

### ISSUE THREAD

**Issue by nelsong** [openshift/origin#18681]
I'm trying to do a test upgrade before hitting up the production servers and I'm getting an error when running the upgrade playbook.

##### Version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. ansible-playbook -i ../dev playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml -e openshift_disable_check=disk_availability,memory_availability

##### Current Result
  1. Hosts:    osmaster.devbox.int
     Play:     Verify upgrade can proceed on first master
     Task:     fail
     Message:  openshift_release is 1.5.1 which is not a valid release for a 3.6 upgrade

**Comment by mar1ged** [comment]
I would say going from 1.5 to 3.6 is a giant leap. If possible at all I guess you need to update to some of the versions in between first

https://docs.openshift.org/latest/install_config/upgrading/index.html

**Comment by nelsong** [comment]
I tried running the 3.5 upgrade to get to the latest 1.5 release and it said the same thing. I'll be closing this issue and moving it to openshift-ansible since it really isn't an openshift problem.
