### ISSUE TITLE
OC cluster oc v3.9.0 up webconsole not access from centos 7 vm to outside and not able to pull image in oc cluster getting timeout error

### ISSUE THREAD

**Issue by vaibhavpatil123** [openshift/origin#18682]
[provide a description of the issue]

##### Version
oc v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. After oc cluster up running on VM not accesable outside vm
 ./oc cluster up --host-data-dir=/mydata --use-existing-config  --public-hostname='127.0.0.1'                              
![image](https://user-images.githubusercontent.com/9848325/36443968-4911e72c-16a0-11e8-865e-15b17040a86b.png)

On Centos 7 vm getting below runing but webconsole url not acceable from out side VM with below URL
https://localhost:8443/console/ 
**HTTP -ERROR -502** 

2. Pull images with oc command getting connection time out 
**error: couldn't get deployment nodejs-1: Get https://172.30.0.1:443/api/v1/namespaces/new/replicationcontrollers/nodejs-1: dial tcp 172.30.0.1:443: i/o timeout**
for all images pull I am getting timeout exception 
please help to proceed we are evalauting this openshift for our project

Inside vm I can access webconsole but outside vm not able to access console

![image](https://user-images.githubusercontent.com/9848325/36443951-3907d29c-16a0-11e8-8999-26b1dae83611.png)

##### Current Result
Webconsole not access able outside vm 
Pull images getting time out exception 
##### Expected Result
Webconsole should access exteranlly outside vm 
We should able to pull and deploy image in centos vm oc cluster application
##### Additional Information
root@openshift-origin-server-v3.9.0-alpha.3-78ddc10-linux-64bit]# ./openshift-diagnostics network-diagnostic-pod
[Note] Running diagnostic: CheckExternalNetwork
       Description: Check that external network is accessible within a pod

[Note] Running diagnostic: CheckNodeNetwork
       Description: Check that pods in the cluster can access its own node.

ERROR: [DNodeNet1001 from diagnostic CheckNodeNetwork@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/networkpod/node.go:50]
       Unauthorized

[Note] Running diagnostic: CheckPodNetwork
       Description: Check pod to pod communication in the cluster. In case of ovs-subnet network plugin, all pods should be able to communicate with each other and in case of multitenant network plugin, pods in non-global projects should be isolated and pods in global projects should be able to access any pod in the cluster and vice versa.

ERROR: [DPodNet1001 from diagnostic CheckPodNetwork@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/networkpod/pod.go:60]
       Checking network plugin failed. Error: Unauthorized

[Note] Running diagnostic: CheckServiceNetwork
       Description: Check pod to service communication in the cluster. In case of ovs-subnet network plugin, all pods should be able to communicate with all services and in case of multitenant network plugin, services in non-global projects should be isolated and pods in global projects should be able to access any service in the cluster.

ERROR: [DSvcNet1001 from diagnostic CheckServiceNetwork@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/networkpod/service.go:60]
       Checking network plugin failed. Error: Unauthorized

[Note] Running diagnostic: CollectNetworkInfo
       Description: Collect network information in the cluster.

ERROR: [DColNet1001 from diagnostic CollectNetworkInfo@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/networkpod/collect.go:47]
       Fetching local node info failed: Unauthorized

[Note] Summary of diagnostics execution (version v3.9.0-alpha.3+78ddc10):
[Note] Errors seen: 4

**Comment by Yajuvendradesai** [comment]
I am also getting same exception, please help here.

**Comment by jwforres** [comment]
sounds like a networking issue, but also including @spadgett in case there are issues related to console now being in a pod

**Comment by spadgett** [comment]
It looks like the console isn't working because the console image couldn't be pulled. If we can solve the image pull problem, it should also solve the console problem.

**Comment by vaibhavpatil123** [comment]
@spadgett Can you porvide point cuts for above issue ? We are using centos7. In short I am facing below issues:
1 Webconsole url - not acceable from Window machine but on VM machine I can access same
2 On VM machine I cant able to docker images

**Comment by spadgett** [comment]
It would be better for someone on the networking team like @knobunc to comment, but this seems like a networking configuration issue in your VM. I wouldn't expect using `localhost` on the host system to connect to the web console running inside a VM. (That also doesn't match the public hostname you used for cluster up.)

**Comment by vaibhavpatil123** [comment]
@spadgett/@jwforres thanks colleageus for point cuts, issue was due to local VM network firewall settings.
I have fixed this issue using below link 
Install Docker with your platform's package manager.

Configure the Docker daemon with an insecure registry parameter of 172.30.0.0/16

In RHEL and Fedora, edit the /etc/sysconfig/docker file and add or uncomment the following line:

INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'
or edit the /etc/docker/daemon.json file and add the following:

{
   "insecure-registries": [
     "172.30.0.0/16"
   ]
}
After editing the config, reload systemd and restart the Docker daemon.

$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
Ensure that your firewall allows containers access to the OpenShift master API (8443/tcp) and DNS (53/udp) endpoints. In RHEL and Fedora, you can create a new firewalld zone to enable this access:

Determine the Docker bridge network container subnet:

docker network inspect -f "{{range .IPAM.Config }}{{ .Subnet }}{{end}}" bridge
You should get a subnet like: 172.17.0.0/16

Create a new firewalld zone for the subnet and grant it access to the API and DNS ports:

firewall-cmd --permanent --new-zone dockerc
firewall-cmd --permanent --zone dockerc --add-source 172.17.0.0/16
firewall-cmd --permanent --zone dockerc --add-port 8443/tcp
firewall-cmd --permanent --zone dockerc --add-port 53/udp
firewall-cmd --permanent --zone dockerc --add-port 8053/udp
firewall-cmd --reload
Download the Linux oc binary from openshift-origin-client-tools-VERSION-linux-64bit.tar.gz and place it in your path.

Please be aware that the 'oc cluster' set of commands are only available in the 1.3+ or newer releases.

Open a terminal with a user that has permission to run Docker commands and run:

$ oc cluster up

----------------------------------------------------------------------------------------------------
Finally added below firewall settings 

> $ firewall-cmd --zone=public --add-port=8443/tcp --permanent
> f$ irewall-cmd --reload 

Current outcomes 
![image](https://user-images.githubusercontent.com/9848325/36637016-6bf65114-19f8-11e8-8b0d-cd0a039fdf7a.png)

Thanks again for ontime inputs!!

**Comment by vaibhavpatil123** [comment]
Now both issues -image pull and console view fixed so closing this ticket and enjoying new journay with openshift!! :1st_place_medal:

**Comment by jwforres** [comment]
Great! Glad you were able to get it working
