### ISSUE TITLE
oc rsh should support -n option

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#18696]
`oc rsh` silently ignores `-n` option.

##### Version
```console
$ oc version
oc v3.9.0-alpha.4+f59e2aa-338-dirty
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.34.129.218:8443
openshift v3.9.0-alpha.4+a658a12-334-dirty
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
1. `oc cluster up`
2. `oc login -u system:admin`
3. `oc get pods -n openshift-web-console`
4. `oc rsh webconsole-67475666c5-5l89z -n openshift-web-console`

##### Current Result
```console
Error from server (NotFound): pods "webconsole-67475666c5-5l89z" not found
```
##### Expected Result
The shell session to a pod should be created.

**Comment by juanvallejo** [comment]
Looking into this. Something appears to be clearing the value of the `--namespace` flag by the time its value is parsed in the `rsh` command.

**Comment by wanghaoran1988** [comment]
hmm, oc rsh -n <namespace> <pod> works well

**Comment by juanvallejo** [comment]
@wanghaoran1988 what version of `oc` are you using?

When I try this locally, the value of `--namespace` was being cleared by the time `f.DefaultNamespace()` was called in the `rsh` command. Will try testing locally again.

**Comment by juanvallejo** [comment]
Ah nevermind, I see what the issue is.
@php-coder this is not a bug, but rather the way that `rsh` parses flags.
For the `-n` flag to work, you need to specify it before the pod name.

Specifying it afterwards will cause it to be interpreted as an argument to execute in the pod.

**Comment by php-coder** [comment]
@juanvallejo Wow, thank you!
