### ISSUE TITLE
Filipino Localization

### ISSUE THREAD

**Issue by cordeta** [openshift/origin#18693]
I would like to offer free Filipino Translation to your documents. Rest assure that my service is credible

**Comment by jwforres** [comment]
When you say documents do you mean our documentation website, if so this issue should go here https://github.com/openshift/openshift-docs/issues

**Comment by cordeta** [comment]
I believe I am referring to your documentation website how may I be of help for Filipino Localization?

**Comment by php-coder** [comment]
@openshift/team-documentation

**Comment by vikram-redhat** [comment]
@cordeta - you are welcome to submit a PR against the origin docs and it can then be evaluated.

**Comment by spadgett** [comment]
@cordeta Thanks for the offer. Please work with team in the openshift/openshift-docs repo

/close
