### ISSUE TITLE
Add ntp dependancy in origin-master-api.service to avoid unability

### ISSUE THREAD

**Issue by dclairac** [openshift/origin#18699]
On master reboot, If NTP generates a negative time offset (return in the past) after starting the origin-master-api service, the API does not work.

##### Version
oc v3.7.23
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. On an OpenShift cluster with 3 master:
2. Restart one of the 3 master 
3. On master 3: curl https://master-host:8443/healthz/ping -k

##### Current Result
User "system:anonymous" cannot get path "/healthz/ping": User "system:anonymous" cannot "get" on "/healthz/ping"

##### Expected Result
ok

##### Additional Information
VM based on RHV with this bug [https://bugzilla.redhat.com/show_bug.cgi?id=1474213].
The VM starts with a UTC +2 timer.
The origin-master-api service starts while the machine is in UTC +2
The NTP service starts and runs the machine again in UTC +1
The API is unusable until the service is restarted.

The original problem is related to the change of schedule which should not take place (processing in progress with Red Hat support), however, a security would be to add a dependency on ntp service in the startup of the API.
Below is the correction that could be generalized:
File: /usr/lib/systemd/system/atomic-openshift-master-api.service

[Unit]
Description=Atomic OpenShift Master API
Documentation=https://github.com/openshift/origin
After=network-online.target
After=etcd.service
**Before=chronyd.service**
Before=atomic-openshift-node.service
Requires=network-online.target
 
[Service]
Type=notify
EnvironmentFile=/etc/sysconfig/atomic-openshift-master-api
Environment=GOTRACEBACK=crash
ExecStart=/usr/bin/openshift start master api --config=${CONFIG_FILE} $OPTIONS
LimitNOFILE=131072
LimitCORE=infinity
WorkingDirectory=/var/lib/origin
SyslogIdentifier=atomic-openshift-master-api
Restart=always
RestartSec=5s
 
[Install]
WantedBy=multi-user.target
WantedBy=atomic-openshift-node.service

**Comment by jwforres** [comment]
@openshift/sig-cluster-lifecycle

**Comment by sdodson** [comment]
I think you mean to use `After=chronyd.service` if we want to start the API after chronyd. But even that i don't think there's any assurance that just because chrony or ntpd have started before the API server that it will have fully adjusted the clock by the time the API starts. Do you have a BZ or Case number I can follow for the support ticket?

**Comment by dclairac** [comment]
You are right, this does not prove that the time adjustment will be complete (even if in our case, the result is immediate).

We did not open a ticket on this point because it is not an Openshift bug (the case of synchronization is linked to a RHV bug, which is not the normal case). On the other hand, we have an open ticket at Red Hat for the time problem on RHV (but not related to OpenShift).

In the end, I can't guarantee that starting the API after chrony will avoid the problem in all cases. It will in any case avoid it in some cases, avoiding a few hours of research on the causes of non functioning of the API.

**Comment by sdodson** [comment]
/assign fabianvf 
Lets add 'After=chronyd.service' and 'After=ntpd.service' to our api, controllers, and node services. The installer will accept either ntp implementation so we should add both. We should not add Requires as we don't know for sure which service is in use.
