### ISSUE TITLE
AggregatedLogging breaks oc adm diagnostics

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#18705]
If logging is not installed, you cannot run `oc adm diagnostics`.

##### Version
```
$ oc version
oc v3.9.0-alpha.4+2f9dbe3-416-dirty
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.122:8443
openshift v3.9.0-alpha.4+9ab7a71
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
1. `oc cluster up` or `minishift start`
2. `oc adm diagnostics`

##### Current Result
```
ERROR: [CED3001 from controller openshift/origin/pkg/oc/admin/diagnostics/diagnostics.go]
       Encountered fatal error while building diagnostics: default logging project not found, use '--logging-project' to specify logging project
```

... except you *can't* specify `--logging-project` at this level. And execution halts entirely.

##### Additional Information

This was [supposed to be an optional parameter on a sub-command](https://github.com/openshift/origin/pull/18437#pullrequestreview-94171593). The diagnostic should be skipped and others should proceed. It should not be an error, either when building the diagnostic or when running it.

Note also that the flag is only available on the `aggregatedlogging` subcommand, or with a different name under the `all` subcommand.

**Comment by wozniakjan** [comment]
Not having logging deployed has always been an error in diagnostics, just never a fatal one. @pravisankar recommended in https://github.com/openshift/origin/pull/18437 we make it a fatal error so I will defer to him for a rationale.

The original intention was to use sensible defaults and report normal error if defaults fail. Also, allow the user to rout diagnostics to own `--logging-project` as a special case to comply with current openshift-ansible option `openshift_logging_namespace`. But this was rejected as unnecessary and instead suggested https://github.com/openshift/origin/pull/18567

**Comment by sosiouxme** [comment]
Previously, the logic would look for a master config, and (if there) look for the loggingPublicURL to identify where logging was deployed. If master config was not available, the diagnostic was skipped. If loggingPublicURL was missing, the diagnostic logic returned without raising an error. That's what I'd like to continue happening, although the detection method has changed. If you haven't deployed logging, that's a legitimate choice, not an error diagnostics needs to inform you of. If you have a project that looks like it's supposed to have logging components deployed in it but doesn't, or some are missing, that's when you raise the flag.

Thanks for the PR, I think it'll be an easy enough fix.

**Comment by wozniakjan** [comment]
@sosiouxme looking at the last working AggregatedLogging diagnostics, I dare to disagree. If masterConfig or loggingPublicURL were not found, it appears diagnostics would fatal error
https://github.com/openshift/origin/blob/042a63f8c1effc2fb911ce2cf494458872e9f8a3/pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go#L163-L177

and then if it was unable to fetch the project, it would diagnose an error
https://github.com/openshift/origin/blob/042a63f8c1effc2fb911ce2cf494458872e9f8a3/pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go#L238-L247

But yes, we can implement diagnostics in such way, that if no argument is provided and neither logging nor openshift-logging projects are present in the cluster, skip aggregated diagnostics alltogether. It is just not consistent with previous behavior

**Comment by sosiouxme** [comment]
Ooh, cool new github feature :)

@wozniakjan `CanRun()` errors only bubble up as skip messages. Not reported to the user as an error. I can see how that's confusing to the developer though. `Complete()` errors bomb the whole run, `CanRun()` errors are just notes.

The second bit of code ran only if there was a `loggingPublicURL` specified, which would only be the case if logging was deployed. You would never get this far otherwise.

Not having logging deployed is a valid choice and should continue not to be an error. But the method of determining whether it's expected to be deployed has had to change.

**Comment by wozniakjan** [comment]
@sosiouxme I see, the test that I performed was still returning an error
```
[root@devconf ~]# ./oc adm diagnostics aggregatedlogging                                                                                                                                                  [69/2786]
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/root/.kube/config'
Info:  Using context for cluster-admin access: 'default/devconf:8443/system:admin'

[Note] Skipping diagnostic: AggregatedLogging
       Description: Check aggregated logging integration for proper configuration
       Because: No master config file was provided
       
ERROR: [CED3001 from controller openshift/origin/pkg/oc/admin/diagnostics/diagnostics.go]
       Encountered fatal error while building diagnostics: Requested diagnostic(s) skipped; nothing to run. See --help and consider setting flags or providing config to enable running.
```

but this was due to the fact I specifically requested AggregatedLogging diagnostics, right? I will update the PR to make it determine the valid logging project in `CanRun()` and that should give us what we want.

**Comment by sosiouxme** [comment]
Right - you get an error if all diagnostics get skipped, because it's kind of silly to report success when you haven't tested anything. There are still a lot of ways the logic and messaging could be improved *sigh*.

**Comment by wozniakjan** [comment]
fixed in https://github.com/openshift/origin/pull/18714
