### ISSUE TITLE
Update route rest to use generic etcd

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#1870]
Currently the route resource's rest implementation is an old implementation of pre-generic etcd rest.  It needs to be refactored to use generic etcd

**Comment by pweil-** [comment]
Reminder: there is a TODO in the rest update method to update annotations for generated host names when the old object is available.

**Comment by liggitt** [comment]
@pweil- at least ensure the right etcdhelper is being used so the configured prefix (`openshift.io/` by default) is used

**Comment by smarterclayton** [comment]
This is mustfix because there is objectmeta validation not being done.

**Comment by pweil-** [comment]
PR: https://github.com/openshift/origin/pull/4425
