### ISSUE TITLE
examples should run on OpenShift online

### ISSUE THREAD

**Issue by aidun** [openshift/origin#18724]
While investigating a another issue with the examples provided in the repository I tried to deploy the sample-app at OpenShift online. While create the app, some error showed up, saying that I not have the permission to do something.

Also the resource limits of the examples are sometimes to big for the default account.

It would be a good behavior, that all examples run flawlessly at the free account of OpenShift online. 

is it worthwhile to investigate further?

##### Steps To Reproduce
1. git clone https://github.com/openshift/origin
2. cd origin/examples/sample-app
3 oc new-app application-template-stibuild.json

##### Current Result
--> Creating resources ...
    secret "dbsecret" created
    service "frontend" created
    error: Route "route-edge" is invalid: spec.host: Forbidden: you do not have permission to set the host field of the route
    imagestream "origin-ruby-sample" created
    imagestream "ruby-22-centos7" created
    buildconfig "ruby-sample-build" created
    deploymentconfig "frontend" created
    service "database" created
    deploymentconfig "database" created
##### Expected Result
No Error´s

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
we provide quickstarts in the online env that work in online.    The online env has its own set of constraints and we aren't/can't/shouldn't going to constrain our generic examples to those limitations.

/close
