### ISSUE TITLE
service-catalog test assumes location of master config from cluster-up

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#18722]
There is a single script that doesn't take into account openshift levels for testing service-catalog in the CI.  https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_pull_request_origin_service_catalog.yml#L75-L84

`oc cluster up` in 3.9 unconditionally wrote to a specified `--host-config-dir`, making the behavior while running from config unreliable.  To match `openshift start`'s consistency, if you specify your config, we no longer write it.  In addition, in 3.9 it would write to an absolute path location by default.  `openshift start` didn't do that because it leads to weird behavior running in different contexts.

The default behavior now is to use a tempdir (may later use a local directory like `openshift.local.clusterup`), but the location is changing and the existing CI doesn't handle it.

One solution is to use the `--write-config` flag like https://github.com/openshift/origin/pull/18601 does in the `test/extended/clusterup.sh` and then use the config you specified.  You may still drift over version.

Another option is to use the suggested login command ` oc login -u system:admin` and then `oc config view --raw` piped to a file of your choosing.

@openshift/sig-master @mfojtik @derekwaynecarr hit this on the path to separating kube and openshift apiservers in cluster up
@pmorie @jboyd01 thanks for helping me find the spot.  Hopefully one of these options will work for you.

**Comment by jboyd01** [comment]
@jpeeler FYI, are there other jobs we should update like this?

**Comment by jpeeler** [comment]
Yes, I'll comment on the jobs PR.
