### ISSUE TITLE
external services not exposed as environment variables

### ISSUE THREAD

**Issue by phemmer** [openshift/origin#18725]
The [documentation]( https://docs.openshift.org/latest/dev_guide/integrating_external_services.html#mysql-define-service-using-fqdn) states that external services will be exposed to pods as environment variables. This is not happening. The service is discoverable via DNS, but not as environment variables.

##### Version
```
$ oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://192.168.99.102:8443
openshift v3.7.1+a8deba5-34
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce
```
$ cat > /tmp/test.yaml <<'EOF'
apiVersion: v1
kind: Service
metadata:
  name: google
spec:
  type: ExternalName
  externalName: google.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
selector: {}
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: test
spec:
  template:
    metadata:
      labels:
        name: test
    spec:
      containers:
        - name: test
          image: alpine
EOF

$ oc create -f /tmp/test.yaml
service "google" created
deploymentconfig "test" created

$ oc debug dc/test -- env | grep SERVICE
```

##### Current Result
```
$ oc debug dc/test -- env | grep SERVICE
Debugging with pod/test-debug, original command: /bin/sh
Waiting for pod to start ...
KUBERNETES_SERVICE_PORT_DNS_TCP=53
KUBERNETES_SERVICE_HOST=172.30.0.1
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_DNS=53

$ oc debug dc/test -- ping google.test.svc.cluster.local
Debugging with pod/test-debug, original command: /bin/sh
Waiting for pod to start ...
PING google.test.svc.cluster.local (172.217.30.142): 56 data bytes
```

##### Expected Result
```
$ oc debug dc/test -- env | grep SERVICE
...
GOOGLE_SERVICE_HOST=google.com
GOOGLE_SERVICE_PORT=80
```

**Comment by jwforres** [comment]
@openshift/sig-networking @openshift/sig-pod not sure who should look into this, or if the docs are just wrong

**Comment by DirectXMan12** [comment]
The docs don't tell the full story -- the Kubernetes logic behind this code *explicitly* ignores services that don't have a ClusterIP set (https://github.com/openshift/origin/blob/e28a3b2fdb4671a3277bb44a2c32a2e08752283e/vendor/k8s.io/kubernetes/pkg/kubelet/envvars/envvars.go#L37-L42) since the `_HOST` is based off of IP.

We should probably fix the docs.

At any rate, I'd probably recommend using DNS instead of the environment variables, if you can.

**Comment by smarterclayton** [comment]
This was intentional for external name services, since we're looking to move away from environment variables being auto injected and instead require them to be explicitly requested via the downward API.

**Comment by phemmer** [comment]
Maybe I'm missing something about the downward API, but I thought it was only capable of exposing information about the pod itself, and that it can't reference fields of other objects.

As for using DNS, this doesn't provide the same functionality as you can only get the IP of the service, not the port, or protocol.

**Comment by sjenning** [comment]
I think what @smarterclayton meant to say was manually injecting the envvars like this
https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#define-an-environment-variable-for-a-container

In that case, the service doesn't do much for you.

Using DNS for service discovery is the best way as @DirectXMan12 mentioned.  This will CNAME `google.<project>.svc.cluster.local` (by default) to `google.com`
https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
