### ISSUE TITLE
Allows to trigger multiple branches with single webhook

### ISSUE THREAD

**Issue by lightyou** [openshift/origin#18730]
Jenkins allows what they call multibranch builds. A single build (jenkinsfile type) can be triggered from any branch or PR. This launches the build in Jenkins with the commit/branch/PR.
It seems to be how blue ocean ui is designed for (each build is associated to a branch ou PR). 

Today, build are triggered only for the branch specified in the buildconfig .spec.source.git.ref matches exactly the triggered ref.

The change may have to be only to be able to use a pattern for the ref in GitRefMatches (pkg/build/webhook/webhook.go)

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
trello'd. 
https://trello.com/c/m2koT73W

**Comment by SteveOzo** [comment]
Is this possible in the newest versions?

**Comment by bparees** [comment]
no this has not been implemented
