### ISSUE TITLE
CRI-O: CI broken 

### ISSUE THREAD

**Issue by runcom** [openshift/origin#18732]
This is the first build that started the red row in Prow: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_crio/4618/

Prow is basically red (whether we were 1 red/20 jobs before the break): https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_conformance_crio

The test failing is:

```
• Failure [122.244 seconds]
[Conformance][templates] templateservicebroker end-to-end test
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:38
  
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:358
    should pass an end-to-end test [Suite:openshift/conformance/parallel] [It]
    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:372

    Expected error:
        <*client.ServerError | 0xc4217c9400>: {
            StatusCode: 500,
            Description: "templateinstances.template.openshift.io \"6e63b1c2-0a39-457c-8670-1209b0a98147\" not found",
        }
        Internal Server Error: templateinstances.template.openshift.io "6e63b1c2-0a39-457c-8670-1209b0a98147" not found
    not to have occurred

    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:274
```

We're pretty sure CRI-O hasn't caused the break, could someone help fix this back to green? @derekwaynecarr @mrunalp @stevekuznetsov @smarterclayton

**Comment by smarterclayton** [comment]
_install is broken due to a 1.13 issue, it’s possible this is related (either via exec or build).

**Comment by smarterclayton** [comment]
Docker 1.13 that is

**Comment by runcom** [comment]
@smarterclayton the failure in question goes back before the switch to 1.13 (yesterday). Is it possible something else got merged that broke CRI-O?

**Comment by smarterclayton** [comment]
Look at the commits that merged before and after the last good build and the first break?

**Comment by jwforres** [comment]
Also see https://github.com/openshift/origin/issues/18726  in case it is the same issue

**Comment by runcom** [comment]
@bparees PTAL, seems like we're hitting https://github.com/openshift/origin/pull/18416/files#diff-5701ddddca0f76334108f1dc45461d7aR53 where the Get returns 500, could you help?

**Comment by bparees** [comment]
Nothing we can do, you need to get the test updated so it's running with the latest TSB image (so it picks up the fix), i'm guessing it's currently running with the 3.9 alpha release or something, which didn't include the fix.

**Comment by bparees** [comment]
(by test I mean test job)

**Comment by runcom** [comment]
> you need to get the test updated so it's running with the latest TSB image

where is this set? is aos-cd-jobs?

**Comment by bparees** [comment]
@stevekuznetsov should be able to help you w/ that.

**Comment by stevekuznetsov** [comment]
Y'all should be running with the latest built stuff, which is built after every merge to master.

**Comment by bparees** [comment]
@stevekuznetsov clearly not... whether that's an installer issue or what i'm not sure.

```
Feb 21 00:12:59.891: INFO: Running 'oc get --config=/etc/origin/master/admin.kubeconfig --namespace=openshift-template-service-broker pods -o yaml'
```

```
  image: docker.io/openshift/origin-template-service-broker:v3.9.0-alpha.4
```

**Comment by runcom** [comment]
ping @stevekuznetsov ^^

**Comment by stevekuznetsov** [comment]
How do we build the TSB images? Where? I mean the job starts with a latest Origin build.

**Comment by bparees** [comment]
> How do we build the TSB images? Where? I mean the job starts with a latest Origin build.

this issue isn't how/where the TSB image is built, the issue is that the installer is installing the TSB w/ a reference to something other than "v3.9" or "latest".  So this is an issue w/ how the TSB is being installed, presumably by the openshift ansible installer if i recall this flow correctly, but possibly it's being installed by some special extended test cluster setup logic.  Either way, it's not parameterizing the TSB template correctly, i suspect.
