### ISSUE TITLE
How to Get Session token??

### ISSUE THREAD

**Issue by LahariGuntha** [openshift/origin#18749]
Hi,

Do we have any Rest API to get session token???
The token that we get when we use the command:
oc whoami -t

Is there any REST API available???

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by enj** [comment]
There is no "REST API" per se, you must go through a challenge + OAuth flow.

See the code at:

https://github.com/openshift/origin/blob/6c42efdc632cc0c01e35e4ea1178dcf3a938dd11/pkg/oc/util/tokencmd/request_token.go#L72

Note that OAuth tokens are meant to be used by humans, not automated processes.  Service accounts are what you would want to use for this.  See `oc sa get-token` for some ideas.

https://stackoverflow.com/questions/tagged/openshift is a better place to ask questions in regards to building workflows.
