### ISSUE TITLE
Flake on conflicts in deployment config test during conformance test

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#18743]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18741/test_pull_request_origin_extended_conformance_gce/16699/#featuredeploymentconfig-deploymentconfigs-when-run-iteratively-conformance-should-only-deploy-the-last-deployment-suiteopenshiftconformanceparallel

Looks like we hit a lot of conflicts and then gave up.  Increasing the number of retries or identifying why we got so many conflicts (maybe controller badness) is sufficient.

@openshift/sig-master

**Comment by tnozicka** [comment]
@smarterclayton this is the server side patch failing, I don't think we can do more here then just fix the test as @mfojtik did

The test is forcing random changes on DC which the controllers react to.

**Comment by smarterclayton** [comment]
So we won the lottery of repeated conflict failures.

On Feb 27, 2018, at 11:50 AM, Tomáš Nožička <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> this is the server side
patch failing, I don't think we can do more here then just fix the test as
@mfojtik <https://github.com/mfojtik> did

The test is forcing random changes on DC which the controllers react to.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/18743#issuecomment-368945748>,
or mute the thread
