### ISSUE TITLE
Cant connect to docker-registry

### ISSUE THREAD

**Issue by flipkill1985** [openshift/origin#18748]
[provide a description of the issue]
Cant connect to Openshift Docker Registry

[provide output of the `openshift version` or `oc version` command]
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
NAME                   CLUSTER-IP      EXTERNAL-IP   PORT(S)                   AGE
svc/docker-registry    172.30.1.249    <none>        5000/TCP                  11h
##### Current Result
[root@master01 ~]# telnet 172.30.1.249 5000
Trying 172.30.1.249...
telnet: connect to address 172.30.1.249: Connection refused
##### Expected Result

Connect to the Docker Resgistry

I cant telnet the docker Registry with port 5000 why??

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
is there a registry pod running?  (oc get pods -n default)
are you able to access other services on your cluster from that machine?
