### ISSUE TITLE
audit config file path is resolved local to the config

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#18753]
Seems like this should be local to the CWD or required to be absolute.

**Comment by soltysh** [comment]
Both are acceptable. If you don't specify full path CWD is being used.

**Comment by deads2k** [comment]
> Both are acceptable. If you don't specify full path CWD is being used.

I don't anyone ever expects logs to end up in local to their config.  I certainly didn't.  It is using pwd of the config, not cwd from where it is launched.

**Comment by soltysh** [comment]
It is working analogically to all the files specified in `master-config.yaml`, that's why I went with this. If we decide that's not the case we can't break existing users. We'd need to start with adding a warning in the validation logic to require full path and eventually in release or most probably two full path. wdyt?

**Comment by deads2k** [comment]
> We'd need to start with adding a warning in the validation logic to require full path and eventually in release or most probably two full path. wdyt?

Yeah, I'm ok with that.  I'm also ok resolving relative to CWD eventually.

I don't think we have any other destination directories specified in the master-config.yaml, do we?

**Comment by soltysh** [comment]
> Yeah, I'm ok with that. I'm also ok resolving relative to CWD eventually.

I'm confused, so you want CWD or not. I thought the purpose was to entirely get rid of CWD.

> I don't think we have any other destination directories specified in the master-config.yaml, do we?

No we don't. This is the only non-configuration element that we use.

**Comment by deads2k** [comment]
> Yeah, I'm ok with that. I'm also ok resolving relative to CWD eventually.
> I'm confused, so you want CWD or not. I thought the purpose was to entirely get rid of CWD.

I'm ok with your plan to allow fully qualified paths only over two releases.  We can deal with CWD later if we need or want to.
