### ISSUE TITLE
kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"

### ISSUE THREAD

**Issue by robdaems** [openshift/origin#18776]
##### Version
```
[root@rhel ~]# openshift version
openshift v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8
[root@rhel ~]# uname -a
Linux rhel 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@rhel ~]# docker --version
Docker version 17.12.1-ce, build 7390fc6
[root@rhel ~]#
```

##### Steps To Reproduce
On a Clean RHEL 7.4 server (1 machine) installation I try to run openshift as a All-in-One
```
[root@rhel ~]# openshift start
```
Googling around doesn't give me a proper solution.

##### Current Result
```
W0228 16:22:37.679295    2019 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
I0228 16:22:37.753317    2019 docker_service.go:209] Docker cri networking managed by kubernetes.io/no-op
F0228 16:22:37.761061    2019 node.go:264] failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"
```

**Comment by jwforres** [comment]
@openshift/sig-pod

**Comment by aveshagarwal** [comment]
This seems just a configuration issue, change docker's cgroup driver to systemd.

**Comment by aveshagarwal** [comment]
use with docker: `--exec-opt native.cgroupdriver=systemd`

**Comment by robdaems** [comment]
@aveshagarwal 
> use with docker: --exec-opt native.cgroupdriver=systemd

Which file(s) do I've to change and which variable?
Since I found this solution also on google, but it didn't help. So I started again with a clean install.

**Comment by robdaems** [comment]
It's fixed by adapting the line in `/usr/lib/systemd/system/docker.service`
```
ExecStart=/usr/bin/dockerd \
          --exec-opt native.cgroupdriver=systemd
```

**Comment by krumware** [comment]
Seeing this issue in WSL.
We don't have easy control over systemd, so the above instructions are difficult to follow.

Users may also be able to add the instructions in the file `/etc/default/docker`.
Adding the line:  `DOCKER_OPTS="--exec-opt native.cgroupdriver=systemd"`

After doing this, our new error is 
```
F0627 12:04:35.582876    3520 network.go:179] error: Could not initialize Kubernetes Proxy. You must run this process as root (and if containerized, in the host network namespace as privileged) to use the service proxy: failed to initialize iptables: error appending rule: exit status 1: iptables: No chain/target/match by that name.
```

**Comment by harshalkwagh** [comment]
in my case i already have   --exec-opt native.cgroupdriver=systemd  option in /usr/lib/systemd/system/docker.service file but still my CgroupDriver is using cgroupfs

ExecStart=/usr/bin/dockerd-current \
          --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current \
          --default-runtime=docker-runc \
          --exec-opt native.cgroupdriver=systemd \
          --userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
          --init-path=/usr/libexec/docker/docker-init-current \
          --seccomp-profile=/etc/docker/seccomp.json \

**Docker info:**
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9c3c5f853ebf0ffac0d087e94daef462133b69c7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)

How to change cgroup to systemd

**Comment by sirsikar-lalit** [comment]
I was able to resolve this issue for my use-case by having the same cgroup driver for docker and kubelet. In my case on CentOS 7.6 I could fix the issue by adding `--exec-opt native.cgroupdriver=systemd` to docker systemd process and adding `--cgroup-driver=systemd` to kubelet systemd process. This way both kubelet and docker are consuming the same cgroup-driver and both operate normally.

Most likely these drivers can be set with any other driver types as well but that was not a part of my testing.
