### ISSUE TITLE
FAILURE: BUILD AN OPENSHIFT-ANSIBLE RELEASE

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#18771]
conformance_install fails on tito tagging (likely because of the 3.10 branch?)
```
+ tito tag --offline --accept-auto-changelog
Creating output directory: /tmp/tito
Tagging new version of openshift-ansible: 3.9.0-0.53.0 -> 3.9.1-1
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 203, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 671, in main
    return tagger.run(self.options)
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 114, in run
    self._tag_release()
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 136, in _tag_release
    self._check_tag_does_not_exist(self._get_new_tag(new_version))
  File "/usr/lib/python2.7/site-packages/tito/tagger/main.py", line 502, in _check_tag_does_not_exist
    raise Exception("Tag %s already exists!" % new_tag)
Exception: Tag openshift-ansible-3.9.1-1 already exists!
```
/kind bug
/priority P0
@openshift/sig-continuous-delivery 
@openshift/sig-cluster-lifecycle

**Comment by deads2k** [comment]
@sdodson is this the commit you have to make each time or something different?

**Comment by sdodson** [comment]
The CI automation does a git describe, bumps the version and then attempts to build that. When release-3.9 was cut there was a 3.9.1-1 tag created on that branch but on the master branch it was still 3.9.0 so therefore the CI job attempts to tag 3.9.1-1 and there's a conflict.

Tagged openshift-ansible-3.10.0-0.1.0 here https://github.com/openshift/openshift-ansible/commit/ac5de18329dc24f9d81d2faebaa4950b4716d198

We need to add this to our branching automation.

**Comment by jupierce** [comment]
@sdodson  Thanks - I've added this to the CD SOP for release-cut.

**Comment by jupierce** [comment]
Should be fixed.

**Comment by wozniakjan** [comment]
happening again with "Exception: Tag openshift-ansible-3.10.1-1 already exists!"

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_aggregated_logging_ansible_json_file/1349/
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/494/consoleFull#-133243262958b6e51eb7608a5981914356

/cc @openshift/sig-developer-experience

**Comment by stevekuznetsov** [comment]
/close

Issues in the jobs are due to a configuration issue.
