### ISSUE TITLE
new-app command should accept a symbolic identifier for STI type

### ISSUE THREAD

**Issue by jpechane** [openshift/origin#1878]
Now if the user uses new-app and wants to generate STI-based apps then he either needs to rely on autodetection of STI image or provide Docker image address. The problem is that
1) Autodetection is not unique for Java web apps - for example Tomcat or WildFly could be used for the same app
2) With auto-detection the community images are configured which is not good for OSE
3) Docker image address are less than user friendly

I envision to have a configuration file that will contain key, value pairs where key is the symbolic name of application environment to be generated - like EAP-6.4, JWS-7-3.0 etc. and value is image name to be used. This will enable easy way how to switch to product images in OSE and not force user to rely on image paths. Also it is more aligned with OS-2.x cartridge name and version approach.

**Comment by smarterclayton** [comment]
The auto detection as is is really not good enough to be supported.  

We have two approaches for this.  One, a set of hardcoded detections in the binary which will never be able to tease out the true complexity.  At best, we can detect things like "java" and then search the visible image repositories to give users a list of the available options.  Two, the forthcoming Git server integration should have hooks that allow a custom container to do detection at a deep level.

@csrwng we should change new-app detectors to return a set of known tokens ("java","java=1.8") and to do a search over the IS's in the visible namespaces and display those as imperfect search results (if there is more than one).  Then we should add those token searches as annotations and document it.  Make sense?

**Comment by csrwng** [comment]
yes makes sense

**Comment by smarterclayton** [comment]
I think for sanity sake we should support the following.

1. Accept inputs for form `[<registry>/][<namespace>/]<name>[:<tag>]`
  1. By convention, accept `docker.io` os the shorter form of `docker.index.io`
  2. By convention, `<name>` should correspond to the name of the language, `ruby`, `php`, `python`
  3. By convention, `<tag>` should correspond to the major supported version, `5.5`, `3.1`, `0.10`
  4. When `<tag>` is omitted, assume it means "the latest stable supported version"
2. If an image stream exists with the given name and tag exactly in any of the searched namespaces, use it directly.
3. If no direct match exists, look for image stream tags with the annotation `supports` with a comma delimited list of exact names: `ruby:1.9.3,ruby:1.9,ruby:1.9.x,ruby`.  
  1. If the "<name>:<tag>" segment matches one of the supports exactly, use that value.
  2. If multiple image streams match, sort by ??? (create a deterministic order here)
  3. By default, `osc new-app` should display multiple results, but should also have a "pick first" mode

**Comment by smarterclayton** [comment]
This was implemented.
