### ISSUE TITLE
rook configmaps "rook-config-override" is forbidden: cannot set blockOwnerDeletion

### ISSUE THREAD

**Issue by zhwenh** [openshift/origin#18784]
$ oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

rook
Rook is an open source orchestrator for distributed storage systems running in cloud native environments.
https://github.com/rook/rook

rook-operator v0.7.0 show Error after starting！
but rook-operator v0.6.2 is OK ，There is no problem。

rook-operator v0.7.0 show Error after starting：

2018-02-28 07:47:54.494361 I | op-cluster: starting cluster in namespace rook
2018-02-28 07:48:00.510035 E | op-cluster: failed to create cluster in namespace rook. **failed to create override configmap rook. configmaps "rook-config-override" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion v1alpha1 Kind Cluster: allowed by openshift authorizer, no matches for /, Kind=Cluster**
2018-02-28 07:48:06.511003 E | op-cluster: failed to create cluster in namespace rook. **failed to create override configmap rook. configmaps "rook-config-override" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion v1alpha1 Kind Cluster: allowed by openshift authorizer, no matches for /, Kind=Cluster**

How to deal with this problem?
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:rook:rook-operator
oc adm policy add-role-to-user rook-operator system:serviceaccount:rook:rook-operator
add ClusterRole to rook-operator

apiVersion: v1
kind: ClusterRole
metadata:
  creationTimestamp: 2018-03-01T08:43:13Z
  name: rook-operator
  resourceVersion: "9439535"
  selfLink: /oapi/v1/clusterroles/rook-operator
  uid: 94301a5b-1d2c-11e8-be33-525400edb5ed
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - events
  - namespaces
  - nodes
  - nodes/proxy
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - customresourcedefinitions
  - daemonsets
  - deployments
  - replicasets
  - thirdpartyresources
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  attributeRestrictions: null
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  attributeRestrictions: null
  resources:
  - storageclasses
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - rook.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-operator
  namespace: rook-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-operator
  namespace: rook-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-operator
subjects:
- kind: ServiceAccount
  name: rook-operator
  namespace: rook-system

**Comment by zhwenh** [comment]
I found the problem.
rook/pkg/operator/cluster/controller.go

func ClusterOwnerRef(namespace, clusterID string) metav1.OwnerReference {
blockOwner := true
return metav1.OwnerReference{
APIVersion: ClusterResource.Version,
Kind: ClusterResource.Kind,
Name: namespace,
UID: types.UID(clusterID),
BlockOwnerDeletion: &blockOwner,
}
}
change this to
func ClusterOwnerRef(namespace, clusterID string) metav1.OwnerReference {
return metav1.OwnerReference{
APIVersion: ClusterResource.Version,
Kind: ClusterResource.Kind,
Name: namespace,
UID: types.UID(clusterID)
}
}

BlockOwnerDeletion: &blockOwner, get rid of this line.

need to find a way to add this permission to get objects SecurityPolicySelfSubjectReview,

I added cluster-admin role to rook-operator "oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:rook:rook-operator" there are the errors "failed to create override configmap rook. configmaps "rook-config-override" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion v1alpha1 Kind Cluster"

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by liggitt** [comment]
this is an upstream issue. it looks like kube does not use a dynamic restmapper for configuring admission plugins:

```
	// TODO: use a dynamic restmapper. See https://github.com/kubernetes/kubernetes/pull/42615.
	restMapper := legacyscheme.Registry.RESTMapper()

	quotaConfiguration := quotainstall.NewQuotaConfigurationForAdmission()

	kubePluginInitializer := kubeapiserveradmission.NewPluginInitializer(client, sharedInformers, cloudConfig, restMapper, quotaConfiguration)
```

that means the `OwnerReferencesPermissionEnforcement` admission plugin upstream cannot resolve references to custom resources or extension API server resources

**Comment by zhwenh** [comment]
How setup to accept this in the openshift "BlockOwnerDeletion: true," !
 
func ClusterOwnerRef(namespace, clusterID string) metav1.OwnerReference {
blockOwner := true
return metav1.OwnerReference{
APIVersion: ClusterResource.Version,
Kind: ClusterResource.Kind,
Name: namespace,
UID: types.UID(clusterID),
**BlockOwnerDeletion: true,**
}
}

**Comment by alikhajeh1** [comment]
@piascikj is https://github.com/imdone/kubernetes/issues/59 the issue we should watch for updates? Seems like that's needed for this issue to be resolved?

**Comment by piascikj** [comment]
@alikhajeh1 No, the [imdone/kubernetes](https://github.com/imdone/kubernetes) project is just an example of integrating TODO comments as github issues with [imdone.io](https://imdone.io).  But based on the fact that you referenced this issue, it appears it would be helpful for the kubernetes team to use it!

**Comment by travisn** [comment]
@liggitt is this issue fixed with https://github.com/kubernetes/kubernetes/pull/62810? I don't see a reference to the TODO anymore. Thanks!

**Comment by liggitt** [comment]
it was fixed in https://github.com/kubernetes/kubernetes/pull/62659

**Comment by debianmaster** [comment]
is there any workaround till upstream k8s is merged ?
