### ISSUE TITLE
Show detailed info about pending status on the web UI

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#1880]
When a pod status is pending, we could show more info in a tooltip like this:

![selection_005](https://cloud.githubusercontent.com/assets/88819/7294716/1fdeae32-e9b0-11e4-9fce-fc99cd555553.png)

The information in this screenshot comes from:
```bash
$ osc get pod database-2-dpl0c --template='{{ with index .status.containerStatuses 0 }}{{ .state.waiting.reason }}{{ end }}'
Image: openshift/invalid-image-name is not ready on the node
```

**Comment by liggitt** [comment]
clicking on a pod now shows the full details in the details sidebar
