### ISSUE TITLE
nfs/hostPath persistent volumes cannot create path

### ISSUE THREAD

**Issue by izapolsk** [openshift/origin#18817]
When I'm going to create persistent volumes from template thru api, I have to connect to openshift via ssh and create appropriate folders beforehand. 
It would be good to add some option to nfs/hostPath persistent volumes which would make persistent volume to create path during first use.

**Comment by deads2k** [comment]
@openshift/storage

**Comment by gnufied** [comment]
I am not sure I understand completely. Can you give an example of which paths aren't created by Openshift and you had to manually create the paths?
