### ISSUE TITLE
[infra] openshift-origin-bot synchronization issues

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#18826]
This is an issue tracker for [openshift-origin-bot](http://openshift-origin-publishing-bot.svc.ci.openshift.org/healthz). The bot will report any errors that happened during synchronization under this issue.

(this is not a bug, just a placeholder for the bot to log errors)

**Comment by mfojtik** [comment]
@sttts @deads2k ^^ these failures are pretty weird... the bot worked just fine last week, it seems to break after I changed the rules to synchronize online `release-3.9` branch to `release-1.9.1`... I expected no-op as we already have all these commits (including the bump?).

**Comment by liggitt** [comment]
verified https://github.com/openshift/kubernetes-gengo/commits/openshift-3.9 was up to date with https://github.com/openshift/origin/tree/release-3.9/vendor/k8s.io/gengo

pushed https://github.com/openshift/kubernetes-gengo/commit/a38df30a39ca0f0766f908d4aba13522b90f899d to https://github.com/openshift/kubernetes-gengo/commits/openshift-3.9 to record origin commit
