### ISSUE TITLE
Origin v.3.7 POD Failed to start "Failed to stop sandbox"

### ISSUE THREAD

**Issue by olsib** [openshift/origin#18827]
[provide a description of the issue]

Mar  5 11:56:07 a3devocn24 journal: E0305 11:56:07.453328   82170 kuberuntime_gc.go:152] Failed to stop sandbox xxxx network: could not retrieve port mappings: checkpoint is not found.

##### Version
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xx,xx,xx:8443
openshift v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
Start pod using deployment config.

Pod gets stuck in ContainerCreating

##### Current Result
Mar  5 11:56:07 a3devocn24 journal: E0305 11:56:07.453328   82170 kuberuntime_gc.go:152] Failed to stop sandbox xxxx network: could not retrieve port mappings: checkpoint is not found.
##### Expected Result
Pod start correctly

##### Additional Information
The issue is happening only on specific nodes. This used to work fine before. Issue reported recently

**Comment by jwforres** [comment]
@openshift/sig-pod

**Comment by sjenning** [comment]
The checkpoint file to which is it referring is under `/var/lib/dockershim`.  Might try looking there for clues.

**Comment by Misterhex** [comment]
I am having a similar issue #19604

**Comment by DanyC97** [comment]
see the BZ mentioned in https://github.com/openshift/origin/issues/19138#issuecomment-389112756
