### ISSUE TITLE
Sample pipeline template doesn't work with cluster up

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#18845]
Trying to instantiate the sample pipeline template with cluster up fails:

> Cannot create build config "sample-pipeline". Jenkins pipeline template openshift/jenkins-ephemeral not found

/assign @bparees 
/kind bug

Sorry, @bparees, maybe my fault (#18230)

**Comment by bparees** [comment]
@spadgett I need more information on what you did.  From what I see cluster up should not be trying to instantiate the ephemeral template.  Exact steps/versions/etc please.

**Comment by spadgett** [comment]
@bparees You can reproduce by instantiating the jenkins-pipeline-example template.

```
$ oc new-app jenkins-pipeline-example
```

**Comment by spadgett** [comment]
By "with cluster up," I mean trying to instantiate the template after having run cluster up to create the cluster.

**Comment by spadgett** [comment]
I clustered up with version 3.10

```
$ oc cluster up --version=v3.10
```

**Comment by bparees** [comment]
ok, it looks like @deads2k broke something in 3.10.  With 3.9 we explicitly configure the jenkins autodeploy logic to use the persistent template:
https://github.com/openshift/origin/blob/release-3.9/pkg/oc/bootstrap/docker/openshift/helper.go#L839

Guessing that logic isn't getting invoked/used anymore with the 3.10 refactor.

I confirmed this works on the 3.9 branch.
