### ISSUE TITLE
[RFE] Cluster Loader should clean-up namespaces after receiving INT signal.

### ISSUE THREAD

**Issue by jmencak** [openshift/origin#18859]
This is a Request For Enhancement.  During cluster loader tests, extended-test-cl* namespaces are created.  They are cleaned up after runs finishe.  However, when pressing "Ctrl+C" or sending an INT signal to the extended.test process, the namespaces are not removed.

It would be nice to have the INT signal caught and a cleanup routine called.

##### Version
Any version.

##### Steps To Reproduce
1. Run extended.test  --ginkgo.focus="Load cluster"  "configuration" and press Ctrl+C during the run.

##### Current Result
Accumulating extended-test-cl* namespaces.

##### Expected Result
No extended-test-cl* namespaces.

/cc @sjug

**Comment by jeremyeder** [comment]
Hmm, is trapping int and triggering cleanup really what we want?

**Comment by jmencak** [comment]
Perhaps not cleanup of the objects created by cluster loader, but removal of extended-test-cl* namespaces would definitely be appreciated to keep things clean.
