### ISSUE TITLE
Enable multicast Openshift 3.6 failes

### ISSUE THREAD

**Issue by cello86** [openshift/origin#18855]
We tried to enable multicast on a specific project into Openshift 3.6.1 but the namaspace can't be found from oc client.

```
[root@dev-openshift01 ~]# oc annotate netnamespace default \
netnamespace.network.openshift.io/multicast-enabled="true"
Error from server (NotFound): netnamespaces.network.openshift.io "default" not found
```

##### Version
```
[root@dev-openshift01 ~]# oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://dev-openshift.test.local
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
```
##### Steps To Reproduce
1. we execute the command oc annotate after the login as system:admin user.

##### Current Result
The multicast isn't enable into the project namespace

##### Expected Result
We would enable the multicast on a project

**Comment by jwforres** [comment]
@openshift/sig-networking
