### ISSUE TITLE
Deploying any pod eg, the router on a schedulable master with two network cards with region=infra results in "could not get deployment for router-1: 172.30.0.1 dial tcp i/o timeout"

### ISSUE THREAD

**Issue by sonykphilip** [openshift/origin#18851]
Deploying any pod eg, the router on a schedulable master with region=infra results in "could not get deployment for router-1: 172.30.0.1 dial tcp i/o timeout"

The master has two network cards and the routing table/rules are working for the internal cluster network via the second card. The first card is the "public ip" to the openshift console.

However, pods get deployed fine from 2 other nodes. Master(schedulable node with region=infra) and Node1 on same subnet and Node2 on a different subnet.

##### Version
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xx,xx,xx:8443
openshift v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. oc rollout latest dc/router

2. 

##### Current Result
"could not get deployment for router-1: 172.30.0.1 dial tcp i/o timeout"

##### Expected Result
router gets deployed on the master.

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by sonykphilip** [comment]
I see traffic coming out of tun0 for port 443:
10.128.0.170 -> 172.30.0.1:443

but nothing come back, while it works on the other nodes.
Heres the relevant section of my inventory file and I made the master schedulable and set region=infra post-install:
<img width="1016" alt="new-ansible-hosts" src="https://user-images.githubusercontent.com/18544650/37053083-3ae60e88-21a1-11e8-95bc-e3f2472b5895.png">

ip ro
<img width="863" alt="screen shot 2018-03-06 at 04 18 25" src="https://user-images.githubusercontent.com/18544650/37053153-66838c5a-21a1-11e8-8b1b-b0724d663978.png">

route-Bond0
<img width="438" alt="screen shot 2018-03-06 at 04 20 02" src="https://user-images.githubusercontent.com/18544650/37053211-8c84dbb6-21a1-11e8-811e-1576669f88c3.png">


route-Bond1
<img width="462" alt="screen shot 2018-03-06 at 04 20 18" src="https://user-images.githubusercontent.com/18544650/37053232-941a3920-21a1-11e8-8278-2aa8116242ad.png">


rule-Bond0
<img width="402" alt="screen shot 2018-03-06 at 04 21 03" src="https://user-images.githubusercontent.com/18544650/37053246-9fac0264-21a1-11e8-99cb-10ca5f5e559e.png">


rule-Bond1
<img width="384" alt="screen shot 2018-03-06 at 04 21 14" src="https://user-images.githubusercontent.com/18544650/37053265-a90c016a-21a1-11e8-8a74-450c7842ccec.png">

**Comment by sonykphilip** [comment]
Fixed this myself. Looks like it was a PEBKAC:
default via 10.145.31.20 dev Bond1 table 2 caused the problem. But this was added so I could reach the master via Bond1 and not have to ssh into it via Bond0. Pods get deployed now on the master after I deleted the default route on Bond1.
