### ISSUE TITLE
User with only 'edit' role on a project can delete project

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1885]
Since editors can't directly delete local policy or quota for a project, it doesn't really make sense that they can do it indirectly by deleting the project.

FYI @deads2k

**Comment by smarterclayton** [comment]
Edit on something gives you delete.

**Comment by deads2k** [comment]
There is a reasonable argument that having the power to delete a project, effectively escalates an editor's privileges by allowing them to delete policy and quota on the project.

**Comment by smarterclayton** [comment]
How does deleting a project let you avoid quota?

----- Original Message -----

**Comment by deads2k** [comment]
It lets you delete things you can't ordinarily delete because finalizers run and destroy the project's contents.

**Comment by smarterclayton** [comment]
But.... then they're deleted....  Edit on a project is a very powerful role.  Most people should not have it (even project admins).  I don't know whether most folks would expect delete of project to be a project admin role.

----- Original Message -----

**Comment by sosiouxme** [comment]
So without getting too bogged down in semantics here... what I'm trying to point out is that when someone does `osadm policy add-role-to-user edit cletus` they probably don't expect cletus to be able to delete the project, even though they are giving cletus the ability to delete almost everything in the project. So maybe that command gives cletus edit on everything *except* the project; I don't know the exact implementation, I just think the current one is surprising.

**Comment by smarterclayton** [comment]
Oh.  Yes, editors on project shouldn't have edit/delete on the project.  Only project admins should be able to delete project.
