### ISSUE TITLE
Failed to delete project servicecatalog dial tcp 172.30.0.1:443: getsockopt: connection refused

### ISSUE THREAD

**Issue by disappear89** [openshift/origin#18875]
On some random project deletion fails with error:

```
Mar 07 09:06:44 vmxxx.openshift.xxx.lan origin-master-controllers[26697]: E0307 09:06:44.639362   26697 namespace_controller.go:148] [an error on the server ("Internal Server Error: \"/apis/servicecatalog.k8s.io/v1beta1/namespaces/tti-test2/serviceinstances\": Post https://172.30.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews: dial tcp 172.30.0.1:443: getsockopt: connection refused") has prevented the request from succeeding (delete serviceinstances.servicecatalog.k8s.io), an error on the server ("Internal Server Error: \"/apis/servicecatalog.k8s.io/v1beta1/namespaces/tti-test2/servicebindings\": Post https://172.30.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews: dial tcp 172.30.0.1:443: getsockopt: connection refused") has prevented the request from succeeding (delete servicebindings.servicecatalog.k8s.io)]
```

##### Version
```
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce
1. Create a project
2. On some random project deletion will fail and stuck in infinite terminating state.

##### Current Result
Project stuck in terminating state.

##### Expected Result
Project will be deleted.

##### Additional Information

The problem looks a bit like https://github.com/openshift/origin/issues/18125 but i am not 100% sure.
The kube-service-katalog pods looking good, but the service IP doesn`t match to the IP in the error:

```
[root@ ~]# oc get pods -n kube-service-catalog
NAME                       READY     STATUS    RESTARTS   AGE
apiserver-6xbcm            1/1       Running   3          13d
controller-manager-ld252   1/1       Running   5          13d

[root@ ~]# oc get service -n kube-service-catalog
NAME                 CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
apiserver            172.30.106.48   <none>        443/TCP    13d
controller-manager   172.30.169.18   <none>        6443/TCP   13d
```

**Comment by jwforres** [comment]
@pmorie @jboyd01 is this the known issue you guys already resolved?

**Comment by jboyd01** [comment]
It does look a bit similar to https://github.com/openshift/origin/issues/18125  but we'd really want to understand the root failure as #18125 was a general issue.
Can we get the Service Catalog logs that show this error with connection refused?

```
oc logs -n kube-service-catalog controller-manager-ld252 > /tmp/controller.logs
oc logs -n kube-service-catalog apiserver-6xbcm > /tmp/api-server.logs
```
and also the output from
```
oc describe serviceinstances -n tti-test2
oc describe servicebindings -n tti-test2
```

**Comment by disappear89** [comment]
Sure, here are the logs.

Thanks,
Thomas
[Logs.zip](https://github.com/openshift/origin/files/1796269/Logs.zip)

**Comment by jboyd01** [comment]
Thanks Thomas!

from the logs it appears that the Ansible Service Broker is not functioning properly:
```W0309 07:21:21.510839       1 controller_broker.go:216] ClusterServiceBroker "ansible-service-broker": Error getting broker catalog: Get https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker/v2/catalog: dial tcp 172.30.129.135:1338: getsockopt: no route to host
I0309 07:21:21.510998       1 controller_broker.go:665] ClusterServiceBroker "ansible-service-broker": Updating ready condition to False
I0309 07:21:21.512256       1 event.go:218] Event(v1.ObjectReference{Kind:"ClusterServiceBroker", Namespace:"", Name:"ansible-service-broker", UID:"9950e263-17ab-11e8-8817-0a580a820202", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"1795457", FieldPath:""}): type: 'Warning' reason: 'ErrorFetchingCatalog' Error getting broker catalog: Get https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker/v2/catalog: dial tcp 172.30.129.135:1338: getsockopt: no route to host
I0309 07:21:21.573139       1 request.go:480] Throttling request took 185.517887ms, request: PUT:https://172.30.0.1:443/apis/servicecatalog.k8s.io/v1beta1/clusterserviceclasses/ca1262b5-17a8-11e8-b88d-aedf6b1b68a3
```
**Get https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker/v2/catalog: dial tcp 172.30.129.135:1338: getsockopt: no route to host**

Do you know if Ansible Service Broker was removed or the deployment deleted or any details around it's health?

**Comment by disappear89** [comment]
Hi @jboyd01 

i just installed the cluster with the ansible installer and didn`t do anything to the service broker.
The deployment was created automatically since the cluster was rolled out.

Do you need any further logs / information?

Cause i will disable the service broker as suggested by jkroepke for now.

Thanks,
Thomas

**Comment by jboyd01** [comment]
It appears to me Service Catalog is working as designed, but the issue is that the Ansible Broker is not running or is misconfigured. @jwmatthews  could someone from the ASB team take a look?

**Comment by bevinhex** [comment]
Agreed, service catalog is trying to connect to 1338 port , which should belong to ansible-service-broker, spent two days googling for this already, so far no luck
