### ISSUE TITLE
Openshift node memory leak

### ISSUE THREAD

**Issue by ksemaev** [openshift/origin#18872]
One of Five absolutely identical nodes leaks memory after upgrade from 3.6.0 to 3.7.0. Even when scheduling is disabled and the node is drained - still origin-node.service keeps using more and more memory (4Gb leaked in 14 days).

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://opsmaster.elpass:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. start origin cluster
2. monitor node memory usage

##### Current Result
Memory leak
##### Expected Result
No memory leak
##### Additional Information
$ oc adm diagnostics output (everything's fine):

_[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/root/.kube/config'
Info:  Using context for cluster-admin access: 'openshift-infra/opsmaster-elpass:8443/system:admin'
[Note] Performing systemd discovery

[Note] Running diagnostic: ConfigContexts[glusterfs/opsmaster-elpass:8443/system:admin]
       Description: Validate client config context is complete and has connectivity

Info:  For client config context 'glusterfs/opsmaster-elpass:8443/system:admin':
       The server URL is 'https://opsmaster.elpass:8443'
       The user authentication is 'system:admin/opsmaster-elpass:8443'
       The current project is 'glusterfs'
       Successfully requested project list; has access to project(s):
         [default elpass glusterfs kube-public kube-system logging management-infra openshift openshift-infra openshift-node]

[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint

WARN:  [DCli2013 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:180]
       See the warnings below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected

       Info:  Service account token successfully authenticated to master

       WARN:  [DP1007 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:118]
              DNS resolution for registry address docker-registry.default.svc.cluster.local returned no results; either the integrated registry is not deployed, or container DNS configuration is incorrect.

       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected

       [Note] Summary of diagnostics execution (version v3.7.0+7ed6862):
       [Note] Warnings seen: 1

[Note] Running diagnostic: NetworkCheck
       Description: Create a pod on all schedulable nodes and run network diagnostics from the application standpoint

Info:  Output from the network diagnostic pod on node "opsnode01.elpass":
       [Note] Running diagnostic: CheckExternalNetwork
              Description: Check that external network is accessible within a pod

       [Note] Running diagnostic: CheckNodeNetwork
              Description: Check that pods in the cluster can access its own node.

       [Note] Running diagnostic: CheckPodNetwork
              Description: Check pod to pod communication in the cluster. In case of ovs-subnet network plugin, all pods should be able to communicate with each other and in case of multitenant network plugin, pods in non-global projects should be isolated and pods in global projects should be able to access any pod in the cluster and vice versa.

       [Note] Running diagnostic: CheckServiceNetwork
              Description: Check pod to service communication in the cluster. In case of ovs-subnet network plugin, all pods should be able to communicate with all services and in case of multitenant network plugin, services in non-global projects should be isolated and pods in global projects should be able to access any service in the cluster.

       [Note] Running diagnostic: CollectNetworkInfo
              Description: Collect network information in the cluster.

       [Note] Summary of diagnostics execution (version v3.7.0+7ed6862):
       [Note] Completed with no errors or warnings seen.

Info:  Output from the network diagnostic pod on node "opsnode02.elpass":
       [Note] Running diagnostic: CheckExternalNetwork
              Description: Check that external network is accessible within a pod

       [Note] Running diagnostic: CheckNodeNetwork
              Description: Check that pods in the cluster can access its own node.

       [Note] Running diagnostic: CheckPodNetwork
              Description: Check pod to pod communication in the cluster. In case of ovs-subnet network plugin, all pods should be able to communicate with each other and in case of multitenant network plugin, pods in non-global projects should be isolated and pods in global projects should be able to access any pod in the cluster and vice versa.

       [Note] Running diagnostic: CheckServiceNetwork
              Description: Check pod to service communication in the cluster. In case of ovs-subnet network plugin, all pods should be able to communicate with all services and in case of multitenant network plugin, services in non-global projects should be isolated and pods in global projects should be able to access any service in the cluster.

       [Note] Running diagnostic: CollectNetworkInfo
              Description: Collect network information in the cluster.

       [Note] Summary of diagnostics execution (version v3.7.0+7ed6862):
       [Note] Completed with no errors or warnings seen.

Info:  Output from the network diagnostic pod on node "opsnode04.elpass":
       [Note] Running diagnostic: CheckExternalNetwork
              Description: Check that external network is accessible within a pod

       [Note] Running diagnostic: CheckNodeNetwork
              Description: Check that pods in the cluster can access its own node.

       [Note] Running diagnostic: CheckPodNetwork
              Description: Check pod to pod communication in the cluster. In case of ovs-subnet network plugin, all pods should be able to communicate with each other and in case of multitenant network plugin, pods in non-global projects should be isolated and pods in global projects should be able to access any pod in the cluster and vice versa.

       [Note] Running diagnostic: CheckServiceNetwork
              Description: Check pod to service communication in the cluster. In case of ovs-subnet network plugin, all pods should be able to communicate with all services and in case of multitenant network plugin, services in non-global projects should be isolated and pods in global projects should be able to access any service in the cluster.

       [Note] Running diagnostic: CollectNetworkInfo
              Description: Collect network information in the cluster.

       [Note] Summary of diagnostics execution (version v3.7.0+7ed6862):
       [Note] Completed with no errors or warnings seen.

Info:  Output from the network diagnostic pod on node "opsnode03.elpass":
       [Note] Running diagnostic: CheckExternalNetwork
              Description: Check that external network is accessible within a pod

       [Note] Running diagnostic: CheckNodeNetwork
              Description: Check that pods in the cluster can access its own node.

       [Note] Running diagnostic: CheckPodNetwork
              Description: Check pod to pod communication in the cluster. In case of ovs-subnet network plugin, all pods should be able to communicate with each other and in case of multitenant network plugin, pods in non-global projects should be isolated and pods in global projects should be able to access any pod in the cluster and vice versa.

       [Note] Running diagnostic: CheckServiceNetwork
              Description: Check pod to service communication in the cluster. In case of ovs-subnet network plugin, all pods should be able to communicate with all services and in case of multitenant network plugin, services in non-global projects should be isolated and pods in global projects should be able to access any service in the cluster.

       [Note] Running diagnostic: CollectNetworkInfo
              Description: Collect network information in the cluster.

       [Note] Summary of diagnostics execution (version v3.7.0+7ed6862):
       [Note] Completed with no errors or warnings seen.

[Note] Skipping diagnostic: AggregatedLogging
       Description: Check aggregated logging integration for proper configuration
       Because: No LoggingPublicURL is defined in the master configuration

[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry

WARN:  [DClu1002 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:189]
       There is no "docker-registry" service in project "default". This is not strictly required to
       be present; however, it is required for builds, and its absence probably
       indicates an incomplete installation.

       Please consult the documentation and use the 'oc adm registry' command
       to create a Docker registry.

[Note] Running diagnostic: ClusterRoleBindings
       Description: Check that the default ClusterRoleBindings are present and contain the expected subjects

Info:  clusterrolebinding/system:controller:horizontal-pod-autoscaler has more subjects than expected.

       Use the `oc adm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.

Info:  clusterrolebinding/system:controller:horizontal-pod-autoscaler has extra subject {ServiceAccount  horizontal-pod-autoscaler openshift-infra}.

Info:  clusterrolebinding/system:controller:horizontal-pod-autoscaler has more subjects than expected.

       Use the `oc adm policy reconcile-cluster-role-bindings` command to update the role binding to remove extra subjects.

Info:  clusterrolebinding/system:controller:horizontal-pod-autoscaler has extra subject {ServiceAccount  horizontal-pod-autoscaler kube-system}.

[Note] Running diagnostic: ClusterRoles
       Description: Check that the default ClusterRoles are present and contain the expected permissions

[Note] Running diagnostic: ClusterRouterName
       Description: Check there is a working router

[Note] Running diagnostic: MasterNode
       Description: Check if master is also running node (for Open vSwitch)

Info:  Found a node with same IP as master: opsmaster.elpass

[Note] Running diagnostic: MetricsApiProxy
       Description: Check the integrated heapster metrics can be reached via the API proxy

[Note] Running diagnostic: NodeDefinitions
       Description: Check node records on master

WARN:  [DClu0003 from diagnostic NodeDefinition@openshift/origin/pkg/diagnostics/cluster/node_definitions.go:111]
       Node opsmaster.elpass is ready but is marked Unschedulable.
       This is usually set manually for administrative reasons.
       An administrator can mark the node schedulable with:
           oc adm manage-node opsmaster.elpass --schedulable=true

       While in this state, pods should not be scheduled to deploy on the node.
       Existing pods will continue to run until completed or evacuated (see
       other options for 'oc adm manage-node').

[Note] Running diagnostic: RouteCertificateValidation
       Description: Check all route certificates for certificates that might be rejected by extended validation.

[Note] Running diagnostic: ServiceExternalIPs
       Description: Check for existing services with ExternalIPs that are disallowed by master config

[Note] Running diagnostic: AnalyzeLogs
       Description: Check for recent problems in systemd service logs

Info:  Checking journalctl logs for 'origin-node' service
Info:  Checking journalctl logs for 'docker' service

[Note] Running diagnostic: MasterConfigCheck
       Description: Check the master config file

WARN:  [DH0005 from diagnostic MasterConfigCheck@openshift/origin/pkg/diagnostics/host/check_master_config.go:52]
       Validation of master config file '/etc/origin/master/master-config.yaml' warned:
       assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console

[Note] Running diagnostic: NodeConfigCheck
       Description: Check the node config file

Info:  Found a node config file: /etc/origin/node/node-config.yaml

[Note] Running diagnostic: UnitStatus
       Description: Check status for related systemd units

[Note] Summary of diagnostics execution (version v3.7.0+7ed6862):
[Note] Warnings seen: 4_

**Comment by jwforres** [comment]
@openshift/sig-pod

**Comment by DirectXMan12** [comment]
Hmm... a heap profile would probably be a good idea.  Looks like we don't serve the heap profile pprof endpoint, but if you run the openshift node process with the `OPENSHIFT_PROFILE=mem` environment variable, it should write a profile out to the node's working directory...

**Comment by ksemaev** [comment]
update to 3.9 resolved the issue
