### ISSUE TITLE
Old storage version for openshift resources

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#18874]
All the openshift resources I've checked:

* deployments
* builds, buildconfigs
* images, imagestreams
* oauth-related objects
* user-related objects
* routes

are all stored using the non-groupfied version. We should enforce all of them to use the new groupified versions asap.

@openshift/sig-master

**Comment by liggitt** [comment]
this is resolved, etcd_storage_path_test.go verifies the stored versions are groupified

/close
