### ISSUE TITLE
update glide.yaml to use fork of docker/docker

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#18884]
@mfojtik We've had to add a patch for docker.  https://github.com/openshift/origin/pull/18882

I've created the fork and branch here https://github.com/openshift/moby-moby/tree/b68221c, but I haven't done the special commit and bot update before.

If no one has to glide update before my AM, perhaps you can walk me through it tomorrow.

**Comment by liggitt** [comment]
and https://github.com/openshift/origin/pull/18883 in 3.9 (will need to update glide.yaml in both branches)

**Comment by deads2k** [comment]
Trying `git commit --allow-empty -m "Origin-commit: 46258f80c241a75f52d29cbf8c49a6893fbab3f0"`

**Comment by liggitt** [comment]
where did you try that?

**Comment by deads2k** [comment]
> where did you try that?

here: https://github.com/openshift/moby-moby/commits/b68221c to allow the bot to run
