### ISSUE TITLE
iscsi-initiator-utils not included in the Openshift origin container image

### ISSUE THREAD

**Issue by porrua** [openshift/origin#18880]
I deployed Openshift 3.7 on a VM and attempted to use iSCSI storage. Openshift origin is running as a container. When I tried to discover iSCSI targets (using NetApp's Trident), it fails saying that the iscsiadm command is not found:

	------------------

	Mar  6 09:47:47 openshift journal: I0306 14:47:47.420758   11198 operation_generator.go:413] MountVolume.WaitForAttach entering for volume "trident" (UniqueName: "kubernetes.io/iscsi/10.250.118.144:3260:iqn.2010-01.com.solidfire:73ck.trident.306868:0") pod "trident-3585078476-hqmqx" (UID: "2470e05c-214c-11e8-9913-000c296b9679") DevicePath ""
	Mar  6 09:47:47 openshift journal: 2018-03-06 14:47:47.541541 I | mvcc: store.index: compact 2355
	Mar  6 09:47:47 openshift journal: I0306 14:47:47.543696   11198 compact.go:159] etcd: compacted rev (2355), endpoints ([https://127.0.0.1:4001])
	Mar  6 09:47:47 openshift journal: 2018-03-06 14:47:47.544545 I | mvcc: finished scheduled compaction at 2355 (took 1.21733ms)
	Mar  6 09:47:47 openshift journal: E0306 14:47:47.620170   11198 iscsi_util.go:202] iscsi: could not read iface default error:
	Mar  6 09:47:47 openshift journal: E0306 14:47:47.620265   11198 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/iscsi/10.250.118.144:3260:iqn.2010-01.com.solidfire:73ck.trident.306868:0\"" failed. No retries permitted until 2018-03-06 14:49:49.62024249 +0000 UTC (durationBeforeRetry 2m2s). Error: MountVolume.WaitForAttach failed for volume "trident" (UniqueName: "kubernetes.io/iscsi/10.250.118.144:3260:iqn.2010-01.com.solidfire:73ck.trident.306868:0") pod "trident-3585078476-hqmqx" (UID: "2470e05c-214c-11e8-9913-000c296b9679") : **executable file not found in $PATH**
	Mar  6 09:47:55 openshift journal: 172.17.0.1 - - [06/Mar/2018:14:47:55 +0000] "GET /healthz HTTP/1.1" 200 0 "" "Go-http-client/1.1"
	Mar  6 09:47:55 openshift journal: 172.17.0.1 - - [06/Mar/2018:14:47:55 +0000] "GET /healthz HTTP/1.1" 200 0 "" "Go-http-client/1.1"
	Mar  6 09:47:58 openshift journal: E0306 14:47:58.199950   11198 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted

	---------------

So, I went ahead and checked the origin container and see if iscsiadm was installed:

	[admin@openshift trident-installer]$ docker ps
	CONTAINER ID        IMAGE                                                                                                                COMMAND                  CREATED             STATUS              PORTS               NAMES
	2b72e93bfef1        docker.io/openshift/origin-docker-registry@sha256:26a876a04bc50b3784bc4c98520b70c5e39858e438a2bb9a4b6554e2e79c3a91   "/bin/sh -c '/usr/bin"   4 minutes ago       Up 4 minutes                            k8s_registry_docker-registry-1-zrmn6_default_d2664a0e-216c-11e8-a5c6-000c296b9679_0
	8ec3c40be516        docker.io/openshift/origin-haproxy-router@sha256:a218e302a711a250db705e0fb0b27aabd0aef3229185bebb41053cf3fd751fdd    "/usr/bin/openshift-r"   4 minutes ago       Up 4 minutes                            k8s_router_router-1-rh4cp_default_d24cd7f4-216c-11e8-a5c6-000c296b9679_0
	4edfc5aa00d4        openshift/origin-pod:v3.7.1                                                                                          "/usr/bin/pod"           4 minutes ago       Up 4 minutes                            k8s_POD_docker-registry-1-zrmn6_default_d2664a0e-216c-11e8-a5c6-000c296b9679_0
	605def5aca5f        openshift/origin-pod:v3.7.1                                                                                          "/usr/bin/pod"           4 minutes ago       Up 4 minutes                            k8s_POD_router-1-rh4cp_default_d24cd7f4-216c-11e8-a5c6-000c296b9679_0
	023496ce6dc5        openshift/origin:v3.7.1                                                                                              "/usr/bin/openshift s"   4 minutes ago       Up 4 minutes                            origin

	# Logging into the origin container to see if iscsiadm is installed
	[admin@openshift trident-installer]$ docker exec -it origin bash

	# Not installed by default
	[root@openshift origin]# which iscsiadm
	/usr/bin/which: no iscsiadm in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)

##### Version
$ oc version
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. Install Origin (latest)
2. oc rsh to origin pod and look for iscsiadm using which

##### Current Result
isciadm not installed

##### Expected Result
iscsi-initiator-utils installed (essentially, be able to execute iscsiadm commands)

##### Additional Information
n/a

**Comment by jwforres** [comment]
@openshift/sig-storage

**Comment by eparis** [comment]
@rootfs @jsafrane does the kubelet look for this inside the container or on the host?

**Comment by gnufied** [comment]
@porrua how did you install openshift?

**Comment by jsafrane** [comment]
Containerized OpenShift looks for iscsiadm inside the container. Only `mount` is done  on the host.
