### ISSUE TITLE
osc login between users creates a bunch of contexts

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1889]
Create users 'alice' and 'joe' and try switching between them a few times using only `osc login`

```
osc login -u alice
osc login -u joe
osc login -u alice
osc login -u joe
[...]
```

It works fine, but you will end up with a ton of contexts in your config (in this example, joe and alice were two users with access to the `demo` project):

```
$ osc config view
[...]
contexts:
- context:
    cluster: master-osv3-example-com-8443
    user: alice-3
  name: alice-3
- context:
    cluster: master-osv3-example-com-8443
    namespace: demo
    user: joe
  name: demo
- context:
    cluster: master-osv3-example-com-8443
    namespace: demo
    user: alice
  name: demo-alice
- context:
    cluster: master-osv3-example-com-8443
    namespace: demo
    user: alice-0
  name: demo-alice-0
- context:
    cluster: master-osv3-example-com-8443
    namespace: demo
    user: alice-1
  name: demo-alice-1
- context:
    cluster: master-osv3-example-com-8443
    namespace: demo
    user: alice-2
  name: demo-alice-2
- context:
    cluster: master-osv3-example-com-8443
    namespace: demo
    user: alice-3
  name: demo-alice-3
- context:
    cluster: master-osv3-example-com-8443
    namespace: demo
    user: joe-0
  name: demo-joe-0
- context:
    cluster: master-osv3-example-com-8443
    namespace: demo
    user: joe-1
  name: demo-joe-1
```

It might be the case that the user "shouldn't do that" but it seems like the most natural way to switch (if you don't know about `osc config use-context`), and should in any case do something more reasonable than this.

**Comment by derekwaynecarr** [comment]
I ran into the same issue today as well.  I agree with the sentiment expressed here.

**Comment by deads2k** [comment]
At some point in the past couple days this was largely fixed.  Now you get one context for each server, user, namespace tuple.  In the common scenario, you'll end up with two namespaces per user: one with an empty namespace and one with their new-project namespace.

Unfortunately, this also a victim of the namespace="" can sometimes actually mean "default".  You can't safely repurpose a context with an empty namespace because that empty namespace doesn't mean missing, it means "default".  We can only eliminate the empty namespace context if we're ok with ignoring it's sometimes meaning.

**Comment by deads2k** [comment]
@smarterclayton Can I get a ruling on whether we should ignore the occasional meaning of empty namespace to eliminate the "extra" contexts?

**Comment by smarterclayton** [comment]
I'd prefer contexts ONLY have a non-empty namespace.  The config author is responsible for filling out "default" if they mean default, and empty namespaces can be ignored.  If that's what you're looking for.

**Comment by deads2k** [comment]
That will do.  Empty namespaces will now mean that a namespace isn't set, which makes it legal to re-use the context and set a namespace on it as a result of `osc project` or `osc new-project`.

**Comment by deads2k** [comment]
@liggitt fixed by https://github.com/openshift/origin/pull/2226
