### ISSUE TITLE
Router reload script, why not use pidof instead ?

### ISSUE THREAD

**Issue by jhaohai** [openshift/origin#18892]
https://github.com/openshift/origin/blob/2ea2e99d13292b3bdbe256793339493f7c16c8b0/images/router/haproxy/reload-haproxy#L80

`pidof` is built in the image. Why not use this command which is far more 'elegent'

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by knobunc** [comment]
@jhaohai No good reason... I'll make the change.
