### ISSUE TITLE
Verify Requirements [localhost] Run variable sanity checks 0.12s

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#18916]
All conformance jobs are failing on this. This is not a flake.  Our queue is blocked.

```
Verify Requirements [localhost] Run variable sanity checks 0.12s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Verify\sRequirements\s\[localhost\]\sRun\svariable\ssanity\schecks$'
```

https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_conformance_install

**Comment by deads2k** [comment]
The only pull merged into origin between success and failure is https://github.com/openshift/origin/pull/18778  That looks highly unlikely for this error.


```
1. Hosts:    localhost
     Play:     Verify Requirements
     Task:     Run variable sanity checks
     Message:  last_checked_host: localhost, last_checked_var: openshift_image_tag;openshift_image_tag must be in the format
               v#.#.#[-optional.#]. Examples: v1.2.3, v3.5.1-alpha.1
               You specified openshift_image_tag=8fecfd8
```

**Comment by deads2k** [comment]
@sdodson @stevekuznetsov doesn't look like an origin code change.  Ansible or CI infrastructure maybe?

**Comment by mfojtik** [comment]
https://github.com/openshift/openshift-ansible/pull/7399 is suspicious, @michaelgugino

**Comment by sdodson** [comment]
In the first job that fails openshift_image_tag is set where as in all previous jobs it wasn't set.
```
+ ansible-playbook -vv --become --become-user root --connection local --inventory sjb/inventory/ -e openshift_deployment_type=origin -e etcd_data_dir=/tmp/etcd -e openshift_master_default_subdomain=172.18.12.9.nip.io -e openshift_pkg_version=-3.10.0-0.alpha.0.168.c86959ad -e openshift_release=3.10 -e openshift_image_tag=c86959ad -e 'oreg_url=openshift/origin-${component}:c86959ad' -e openshift_node_port_range=30000-32000 -e 'osm_controller_args={"enable-hostpath-provisioner":["true"]}' '-e @sjb/inventory/master.cfg' /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
```

**Comment by sdodson** [comment]
https://github.com/openshift/aos-cd-jobs/commit/6c31a38a03c5474bf2a11372e0f02499fa86c514 added image_tag to those jobs but I think we should relax the validation of openshift_image_tag, this is an "I know what I'm doing, give me this exact image tag" flag but we may be relying on it for some early version dependent logic today and we should stop doing that.

@michaelgugino thoughts?

**Comment by jcantrill** [comment]
The fix looks to be something like: https://github.com/openshift/aos-cd-jobs/pull/1211/files#diff-4dc6b38f06ee5b2498ba3766484130e0R11 but I cant seem to find it in the generated jobs

**Comment by smarterclayton** [comment]
We should relax the validation.

**Comment by smarterclayton** [comment]
I bet there are customers who have mirrored images who depend on this.  The check is too explicit.

**Comment by deads2k** [comment]
picked @smarterclayton's change from another pull into https://github.com/openshift/openshift-ansible/pull/7472 to fix this.

**Comment by stevekuznetsov** [comment]
We've been passing a SHA for the tag for ages. I can change the jobs to pass a version, I guess?

**Comment by deads2k** [comment]
> We've been passing a SHA for the tag for ages. I can change the jobs to pass a version, I guess?

The concern about mirrored images remains.  I'd change the installer to warn, not fail.  The current patch hacks out the check entirely.

**Comment by michaelgugino** [comment]
@smarterclayton @deads2k @sdodson @stevekuznetsov 

There are two issues here.  We probably need to remove the validation because it happens before openshift_version runs; openshift_version will properly complain if openshift_image_tag is not properly formatted, I believe.

We use set_fact to override openshift_image_tag (This has been done for some time, not preferable, we can probably refactor this cycle) to set openshift_image_tag to a more specific version when only given a two digit tag.

I think this will still be an issue, because we enforce openshift_image_tag == openshift_pkg_version for rpm installs.

**Comment by stevekuznetsov** [comment]
Removed the explicit pass of `openshift_image_tag`.

/close

**Comment by kargakis** [comment]
Still an issue

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18903/test_pull_request_origin_extended_conformance_install/8821/

**Comment by kargakis** [comment]
Wait this is an old job, sorry for the noise
