### ISSUE TITLE
kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin#18915]
Hi , 

I have setup origin version using quick installation method using "openshift start" command : 

oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.30.3.181:8443
openshift v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62

Everything works fine, but whenever I deploy pod i get this as warning in events:

kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.

Can anyone tell me why I am getting this and how to resolve? Thanks a lot in advance !

**Comment by zhonglin6666** [comment]
the same issue, as followers:
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  2m		2m		1	default-scheduler			Normal		Scheduled		Successfully assigned nginx1-1-deploy to 172.23.151.37
  2m		2m		1	kubelet, 172.23.151.37			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "deployer-token-mn6qn" 
  25s		25s		1	kubelet, 172.23.151.37			Warning		FailedCreatePodSandBox	Failed create pod sandbox.
  2m		11s		2	kubelet, 172.23.151.37			Warning		MissingClusterDNS	kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.

**Comment by jwforres** [comment]
@openshift/sig-pod not sure if this goes to you guys or networking

**Comment by jwforres** [comment]
also cc @sdodson since this is referencing quick installer

**Comment by sjenning** [comment]
Does the `node-config.yaml` generated have the `dnsIP` field set? That error indicates that the `--cluster-dns` flag to the underlying kubelet is not being set.

**Comment by priyanka5** [comment]
@sjenning No it does not have dnsIP set , this field is empty. I tried adding it manually but again when I start the node it disappears.

**Comment by sdodson** [comment]
> also cc @sdodson since this is referencing quick installer

This is just `openshift start` where there's no installer involved whatsoever.
