### ISSUE TITLE
Crash Loop Back-off Error: listen EADDRINUSE 0.0.0.0:8080 unable to listen to any port 

### ISSUE THREAD

**Issue by Cariaga** [openshift/origin#18929]
code works locally but not on openshift online server
tried using socket.io or websocket or ws
already tried changing port to 3000 or 8080 or 8081

index client html
`  <script>
     var hostname = window.document.location.hostname;
      var ws = new WebSocket('ws://'+hostname+':8080');
      ws.onmessage = function (event) {
        alert(event.data);
      };
</script>
`
------------------------------------------------------------------------------------------------

server.js
`var server = require('http').createServer(app);

const wss = new WebSocket.Server({ server });

wss.on('connection', function connection(ws, req) {
  const location = url.parse(req.url, true);
  // You might use location.query.access_token to authenticate or share sessions
  // or req.headers.cookie (see http://stackoverflow.com/a/16395220/151312)

  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });
  ws.send('something');
});

server.listen(8080, function listening() {
  console.log('Listening on %d', server.address().port);
});
`
`

events.js:160
--
  | throw er; // Unhandled 'error' event
  | ^
  |  
  | Error: listen EADDRINUSE 0.0.0.0:8080
  | at Object.exports._errnoException (util.js:1020:11)
  | at exports._exceptionWithHostPort (util.js:1043:20)
  | at Server._listen2 (net.js:1258:14)
  | at listen (net.js:1294:10)
  | at net.js:1404:9
  | at _combinedTickCallback (internal/process/next_tick.js:83:11)
  | at process._tickCallback (internal/process/next_tick.js:104:9)
  | at Module.runMain (module.js:606:11)
  | at run (bootstrap_node.js:389:7)
  | at startup (bootstrap_node.js:149:9)
  |  
  | npm info lifecycle nodejs-ex@0.0.1~start: Failed to exec start script
  | npm ERR! Linux 3.10.0-693.15.2.el7.x86_64
  | npm ERR! argv "/opt/rh/rh-nodejs6/root/usr/bin/node" "/opt/rh/rh-nodejs6/root/usr/bin/npm" "run" "-d" "start"
  | npm ERR! node v6.11.3
  | npm ERR! npm  v3.10.9
  | npm ERR! code ELIFECYCLE
  | npm ERR! nodejs-ex@0.0.1 start: `node server.js`
  | npm ERR! Exit status 1
  | npm ERR!
  | npm ERR! Failed at the nodejs-ex@0.0.1 start script 'node server.js'.
  | npm ERR! Make sure you have the latest version of node.js and npm installed.
  | npm ERR! If you do, this is most likely a problem with the nodejs-ex package,
  | npm ERR! not with npm itself.
  | npm ERR! Tell the author that this fails on your system:
  | npm ERR!     node server.js
  | npm ERR! You can get information on how to open an issue for this project with:
  | npm ERR!     npm bugs nodejs-ex
  | npm ERR! Or if that isn't available, you can get their info via:
  | npm ERR!     npm owner ls nodejs-ex
  | npm ERR! There is likely additional logging output above.
  |  
  | npm ERR! Please include the following file with any support request:
  | npm ERR!     /opt/app-root/src/npm-debug.log

` #

**Comment by jwforres** [comment]
@openshift/sig-networking
