### ISSUE TITLE
FAILURE: FORWARD GCS CREDENTIALS TO REMOTE HOST

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#18937]
Seems like the tests are failing randomly at:

```
++ OCT_CONFIG_HOME=/var/lib/jenkins/jobs/test_pull_request_origin_unit/workspace/.config
+ scp -F ./.config/origin-ci-tool/inventory/.ssh_config /var/lib/jenkins/.config/gcloud/gcs-publisher-credentials.json openshiftdevel:/data/credentials.json
lost connection
```

Unit test example: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_unit/10633/consoleFull#101797057758b6e51eb7608a5981914356

**Comment by stevekuznetsov** [comment]
Yet another instance of us losing connection to EC2. Really not much we can do about this unless we figure out a fancy way of re-trying SSH here. We should get exit code 255 if it's an internal failure.

FYI @paradigm

**Comment by stevekuznetsov** [comment]
@mfojtik do we have a measure of how often this happens?

**Comment by stevekuznetsov** [comment]
Super low-level investigation:

```
# ls /var/lib/jenkins/jobs/test_*/builds/*/log | wc -l
17476
# grep 'lost connection' /var/lib/jenkins/jobs/test_*/builds/*/log | wc -l
310
```

**Comment by stevekuznetsov** [comment]
```
# for f in $( grep -l 'lost connection' /var/lib/jenkins/jobs/test_*/builds/*/log ); do stat --format=%y $f | awk '{ print $1 }'; done | sort | uniq -c
      1 2017-02-10
      1 2017-02-22
      1 2018-03-02
      3 2018-03-06
     18 2018-03-07
     34 2018-03-08
     21 2018-03-09
      9 2018-03-10
      8 2018-03-11
     51 2018-03-12
    128 2018-03-13
      8 2018-03-14
```

Definitely a huge uptick in the last couple of days but beware -- we don't have logs for old jobs on the server so this could have been a persistent issue for a while. In any case we can look at doing retries in the jobs?

**Comment by stevekuznetsov** [comment]
No clear action items here. We have retries now.
/close
