### ISSUE TITLE
S2I build stops with error: too many links

### ISSUE THREAD

**Issue by MarWestermann** [openshift/origin#18936]
While building new images we suddenly get error message when pushing to the openshift registry. Here is the log:

S2I binary build from fabric8-maven-plugin detected
--
  | Copying binaries from /tmp/src/maven to /deployments ...
  | ... done
  | error: Execution of post execute step failed
  | error: build error: building fipa-test/officeline-customer-service-s2i-22:4340a73c failed when committing the image due to error: Error response from daemon: {"message":"link /var/lib/docker/overlay/bf126a465b6989f718ba8a95ccbbcea701c71bde2dbbc3808c66a51969a1b90e/root/var/lib/yum/yumdb/l/de98a95d9c8b6c75f9c747096419d5e3c5017e0d-libdb-5.3.21-19.el7-x86_64/installed_by /var/lib/docker/overlay/1b5c4cab2b62a4bfb7075b3e5465ec09f6b0ef7e55c54033c8e70d2f8ddbb1e5/tmproot651958016/var/lib/yum/yumdb/l/de98a95d9c8b6c75f9c747096419d5e3c5017e0d-libdb-5.3.21-19.el7-x86_64/installed_by: too many links"}

##### Version
oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master1.xxx.xxxx.xx:8443
openshift v1.5.0
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
try to build new version of image using fabric8-maven-plugin: mvn clean vertx:package fabric8:build
Not sure how / why this error occurs.

##### Current Result
Error: see above for error log

##### Expected Result
Success

**Comment by php-coder** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
This is a result of something that is being done in the builder image logic, not s2i. s2i simply runs your assemble script inside a container and commits the image.  If the image is not commitable because the assemble script created some sort of overly nested folder structure or recursive symlnks, the image/assemble script needs to be corrected.
