### ISSUE TITLE
'openshift admin add-role-to-user' always gives error (and is vague)

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#1894]
```
# openshift admin policy add-role-to-user admin sspeiche -n dummy1
F0424 02:47:53.504583     153 add_user.go:33] You must specify two arguments

# openshift version
openshift v0.4.4-9-g09f87e4
kubernetes v0.14.1-582-gb12d75d
```

**Comment by mfojtik** [comment]
@jhadvig this should be on your radar :-)

On Fri, Apr 24, 2015 at 3:12 PM, Steve Speicher <notifications@github.com>
wrote:

> # openshift admin policy add-role-to-user admin sspeiche -n dummy1
> F0424 02:47:53.504583     153 add_user.go:33] You must specify two arguments
>
> # openshift version
> openshift v0.4.4-9-g09f87e4
> kubernetes v0.14.1-582-gb12d75d
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/1894>.
>



-- 
-----------------------------------------------
Michal Fojtik <mi@mifo.sk <mfojtik@mifo.sk>>
Red Hat OpenShift, Engineering

**Comment by deads2k** [comment]
This looks like a cobra bug.   `openshift admin policy add-role-to-user [admin | policy] users` gives back arguments `users`.

**Comment by deads2k** [comment]
fixed, but not auto-closed.
