### ISSUE TITLE
oc client doesn't work in Alpine containers

### ISSUE THREAD

**Issue by orhuidobro** [openshift/origin#18942]
`oc` client doesn't work in Alpine containers, because it fails to find dynamically linked dependencies.

##### Version
```
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
But the same problem happens in `v3.6.1`.

##### Steps To Reproduce
1. Create a docker image based in this Dockerfile:
```
FROM java:8-jdk-alpine

# ENV OO_VERSION 3.6.1
# ENV OO_HASH 008f2d5

ENV OO_VERSION 3.7.1
ENV OO_HASH ab0f056

RUN apk add --update curl tar
RUN curl -sSLo oc_client.tar.gz https://github.com/openshift/origin/releases/download/v${OO_VERSION}/openshift-origin-client-tools-v${OO_VERSION}-${OO_HASH}-linux-64bit.tar.gz
RUN tar -xzf oc_client.tar.gz -C /bin --strip-components 1 

ENTRYPOINT /bin/sh
```

2. Create a Docker container based in that image, run it, and connect to its shell.
Execute: `oc`

##### Current Result
```
/ # oc
/bin/sh: oc: not found
```

##### Expected Result
```
/ # oc
OpenShift Client
This client helps you develop...
```

##### Additional Information
The 64 bits `oc` is dynamically linked, as opposite to **the old [oc client 1.5.1 32 bits](https://github.com/openshift/origin/releases/download/v1.5.1/openshift-origin-client-tools-v1.5.1-7b451fc-linux-64bit.tar.gz), which was statically linked, and worked out-of-the-box in Alpine**.
```
/ # /lib/ld-musl-x86_64.so.1 --list /bin/oc
	/lib64/ld-linux-x86-64.so.2 (0x7fe7b04ea000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fe7b04ea000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fe7b04ea000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe7b04ea000)
```
The problem is, these dependencies in Alpine containers are located in `/lib` folder, instead of `/lib64`.
Current workaround is to run `oc` in the following way:
```
/lib/ld-musl-x86_64.so.1 --library-path /lib /bin/oc $@
```

But the real solution could be to build `oc` client, statically linked.

**Comment by php-coder** [comment]
Could it be the same issue as #11135 ?

**Comment by orhuidobro** [comment]
Hi @php-coder, yes, it seems exactly the same problem.
Good catch! I wasn't able to find it.

Anyway, it's unclear to me if the proposed solution is to use this "unofficial" image ([frolvlad/alpine-glibc](https://hub.docker.com/r/frolvlad/alpine-glibc/)), and `RUN apk add --update ca-certificates`. Or if there is some plan to build oc client statically linked (as it used to be with 32 bits clients).

Do you have any suggestion?

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by zoobab** [comment]
How hard is it to statically compile the oc client so that it works on any distro?

I did a Dockerfile for a similar go project:

https://github.com/zoobab/terraform-provider-infoblox/blob/Dockerfile/Dockerfile

**Comment by mdeknowis** [comment]
Same issue with oc 4.1

```
> ls -la /usr/local/bin/oc 
-rwxr-xr-x    1 root     root      71485480 Jun 17 12:24 /usr/local/bin/oc
> /usr/local/bin/oc
/usr/local/bin/oc: not found
> /lib/ld-musl-x86_64.so.1 --list /usr/local/bin/oc
        /lib64/ld-linux-x86-64.so.2 (0x7fc800a40000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fc800a40000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fc800a40000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fc800a40000)
> /lib/ld-musl-x86_64.so.1 --library-path /lib /usr/local/bin/oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.2", GitCommit:"9252851b0", GitTreeState:"clean", BuildDate:"2019-06-12T15:11:24Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zoobab** [comment]
@mdeknowis making a static binary is hard (tm), even with GO.

**Comment by thpham** [comment]
Hello, I had the same problem and I resolved it by installing `apk add gcompat` like described [Running glibc programs on Alpine](https://wiki.alpinelinux.org/wiki/Running_glibc_programs).

Hope it helps !

**Comment by dersimn** [comment]
Either download the binary + `apk add gcompat` (I used the one from here: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/) as @thpham suggested,

### or

..build oc for this alpine glib thingy:

```
FROM alpine:3 as builder

ADD https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-src.tar.gz /

RUN apk add --no-cache \
        alpine-sdk \
        go \
        linux-headers \
        krb5-dev

RUN mkdir /source && \
    tar xfz \
        /openshift-client-src.tar.gz \
        -C /source \
        --strip-components 1 

WORKDIR /source

RUN make oc && \
    cp oc /oc

# ------------------------------------------------------------------------------

FROM alpine:3

COPY --from=builder /oc /usr/local/bin
```

Final container will be ≈150 MB
