### ISSUE TITLE
Proposal: Add prefix (wildcard) matching on role resourceNames

### ISSUE THREAD

**Issue by phemmer** [openshift/origin#18958]
This is a request to add prefix matching on the `resourceNames` parameter of a Role rule.

Currently matching only supports exact match. This is problematic as many resources are automatically created by OpenShift, with a name prefix of what created them. For example a `DeploymentConfig` with name `foo` will create a `ReplicationController` with name `foo-1`, which will then create pods named `foo-1-abcde`. Or a `BuildConfig` named `bar` will create a `Build` named `bar-1`.
Thus we are unable to grant permissions to these resources without granting permissions on the whole namespace.

The use case for this is when we have a shared project (e.g. "production" or "staging") which numerous different applications are deployed to, and we want to allow an application owner access to their own resources, without being able to access the resources belonging to others.

`nonResourceURLs` already supports this in the way of adding a trailing `*` to the end of the value. This proposal is to do the same for `resourceNames`.

&nbsp;

Alternatively, another solution which would satisfy this goal is if a role could match on labels (like any normal selector could). But prefix matching support is probably simpler.

**Comment by ZeeFiix** [comment]
@phemmer Why you have closed it ?
It's still not possible to use it in this way

**Comment by phemmer** [comment]
Because this is more of a kubernetes problem than openshift. The corresponding kubernetes issue can be found here: https://github.com/kubernetes/kubernetes/issues/56582#issuecomment-545636707
