### ISSUE TITLE
Is there a way or workaround to make sure cronjob run on the host with certain pod?

### ISSUE THREAD

**Issue by jeffrey4l** [openshift/origin#18959]
##### Version

openstack 3.6

##### Steps To Reproduce

Setup a pod and a cronjob. If these two containes both need access certain pvc, which is read and write once type. cronjob will not be mount the pvc and failed to start. Because cronjob may run on the different host with pod

##### Expected Result

Is the any possible a mechanism or workaround to make sure cronjob run on the node of the pod?

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by sttts** [comment]
Running anything co-located with a pod is a general problem, not much
related to a job. The canonical solution in kube is a container in the same
pod (of course you then loose the CronJob scheduling).

The usual answer to that question is another question: why do you need that?

Best regards,
   Stefan

**Comment by jeffrey4l** [comment]
currently, my main concern is gitlab backup case.  I am using ceph rbd as backend storage now. So the volume cannot be mounted on more than one node. but gitlab backup script requires to access the disk file. so if the cronjob and pod run on the same node, cronjob will be failed.

**Comment by sttts** [comment]
Take a look at pod anti-affinity:
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity

This might be what you need.

Not sure about our support level (it's beta AFAIK) in OpenShift.

There are also dirty hacks with node ports to simulate pod anti-affinity.
Pod with the same node port won't run on the same node. The scheduler will
eventually find a node where the node port is not taken. But this is so
2016. Pod affinity/anti-affinity is the way to go.

Best regards,
   Stefan

**Comment by jeffrey4l** [comment]
yes. pod affinity should work. i will try it. thanks a lot.
