### ISSUE TITLE
flake: registry returns unauthorized: authentication required when pushing origin image

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#18960]
Seen here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18957/test_pull_request_origin_extended_conformance_gce/17585/

and https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18948/test_pull_request_origin_extended_conformance_gce/17584/
```
[WARNING] Pushing local :13b98b9 images to registry.svc.ci.openshift.org/*:v3.9,:v3.9.0
[INFO] Pushing registry.svc.ci.openshift.org/openshift/origin:v3.9...
The push refers to a repository [registry.svc.ci.openshift.org/openshift/origin]
59bf1254fb1c: Preparing
54f01455206c: Preparing
578db27597cd: Preparing
b03095563b79: Preparing
unauthorized: authentication required
[ERROR] PID 5795: hack/push-release.sh:76: `docker push ${PUSH_OPTS} "${OS_PUSH_BASE_REGISTRY-}${image}${tag}"` exited with status 1.
```

**Comment by legionus** [comment]
This information is not enough.

**Comment by dmage** [comment]
Wrong credentials at /var/lib/jenkins/.docker/config.json?

**Comment by legionus** [comment]
Master API is not ready ?

**Comment by bparees** [comment]
@mfojtik @stevekuznetsov we can't investigate these issues w/o registry logs at a minimum, and I don't see registry logs being collected in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/17585/s3/

**Comment by bparees** [comment]
(also seems plausible that hack/push-release.sh did not setup docker creds properly.  it's not like the registry rejected the credentials, it says you didn't supply any credentials)

**Comment by stevekuznetsov** [comment]
@bparees please let me know who I should give access to the registry logs. It's a simple login to the api.ci cluster with GitHub OAuth.

**Comment by stevekuznetsov** [comment]
Also to be clear those registry logs you're asking for are from the registry on the long-standing cluster, not the registry stood up in the test. The flow is:

 - build images
 - push to persistent registry
 - run ansible, pull from persistent registry

**Comment by bparees** [comment]
> @bparees please let me know who I should give access to the registry logs. It's a simple login to the api.ci cluster with GitHub OAuth.

for now i guess you can give access to me.

Are we continuing to see this specific failure mode (`unauthorized: authentication required`) in jobs?

**Comment by stevekuznetsov** [comment]
@bparees you have the right already since last we looked at registry bits

```
# for f in $( grep -l 'unauthorized: authentication required' /var/lib/jenkins/jobs/test_*/builds/*/log ); do stat --format=%y $f | awk '{ print $1 }'; done | sort | uniq -c | sort -n -k2
<snip>
     66 2017-03-01
      7 2017-01-27
     75 2017-03-07
     29 2018-03-10
     40 2018-03-09
     41 2018-03-07
     42 2018-03-14
     58 2018-03-12
     58 2018-03-13
      7 2018-03-11
     82 2018-03-08
```

**Comment by bparees** [comment]
@stevekuznetsov I don't see anything in hack/push-release.sh that does a docker login, so where are the docker credentials seutp?  (I assume this is running on the temporary ec2 instance and not the jenkins master instance)

**Comment by bparees** [comment]
``
INFO] Pushing registry.svc.ci.openshift.org/openshift/origin:v3.9...
The push refers to a repository [registry.svc.ci.openshift.org/openshift/origin]
```

```
time="2018-03-14T19:05:09.527407823Z" level=error msg="OpenShift access denied: User \"system:serviceaccount:ci-pr-images:builder\" cannot update imagestreams/layers.image.openshift.io in project \"openshift\"" 
```

So is this job pushing to the right namespace?  Seems like it should not be pushing to the openshift namespace, or the serviceaccount needs its permissions fixed.

**Comment by stevekuznetsov** [comment]
Good point -- @smarterclayton did you plumb through the prefix override correctly there?

**Comment by stevekuznetsov** [comment]
@bparees the credentials get copied over for the job

**Comment by bparees** [comment]
> @bparees the credentials get copied over for the job

yup, sorted that out, that part looks ok.  Suspicious part is that those credentials don't appear to have permission to push to the openshift namespace.

**Comment by smarterclayton** [comment]
This is a different bug - I failed in reviewing a PR.  New runs should be
correct.

**Comment by bparees** [comment]
Ok.  Steve has added timestamps to the job logs so hopefully if we hit this again we can correlate it better to the registry logs.

**Comment by bparees** [comment]
running @stevekuznetsov's handy filter, I see no incidents of this so far today:
```
  29 2018-03-10
     30 2018-03-08
     30 2018-03-15
     40 2018-03-09
     58 2018-03-12
     58 2018-03-13
      7 2018-03-11
     94 2018-03-14
```

**Comment by bparees** [comment]
@stevekuznetsov i'm not seeing your timestamps in recent failures, e.g:
```
/var/lib/jenkins/jobs/test_pull_request_origin_extended_conformance_gce_39/builds/lastUnsuccessfulBuild/log
```

**Comment by stevekuznetsov** [comment]
That run was against 3.9, we need to backport the PR.

**Comment by bparees** [comment]
unfortunately the text @stevekuznetsov grepped on is expected output from our tests:
```
Running test/end-to-end/core.sh:321: executing 'docker push '172.30.1.1:5000/missing/image:tag'' expecting failure and text 'authentication required'...
SUCCESS after 0.083s: test/end-to-end/core.sh:321: executing 'docker push '172.30.1.1:5000/missing/image:tag'' expecting failure and text 'authentication required'
```

So do we actually have evidence of a build/job that failed due to push issues lately?

**Comment by bparees** [comment]
@stevekuznetsov any sense of whether this is still happening now that the cluster has been upgraded?

**Comment by stevekuznetsov** [comment]
I don't think so

/close
