### ISSUE TITLE
Unable to restart service origin-node

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#18963]
Seen in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18957/test_pull_request_origin_extended_conformance_install/9007/

```
  1. Hosts:    localhost
     Play:     Configure nodes
     Task:     restart node
     Message:  Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.
```

Not sure if this failure is related:

```
Configure nodes [localhost] nickhammond.logrotate : nickhammond.logrotate | Setup logrotate.d scripts 21m31s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Configure\snodes\s\[localhost\]\snickhammond\.logrotate\s\:\snickhammond\.logrotate\s\|\sSetup\slogrotate\.d\sscripts$'
```

**Comment by sdodson** [comment]
The node never sends the systemd notification that it's started successfully even though it looks to be running just fine.

Mar 13 12:36:12 ip-172-18-15-85.ec2.internal systemd[1]: Starting OpenShift Node...
... five minutes later ...
Mar 13 12:41:12 ip-172-18-15-85.ec2.internal systemd[1]: origin-node.service start operation timed out. Terminating.
Mar 13 12:41:12 ip-172-18-15-85.ec2.internal origin-node[3143]: I0313 12:41:12.256208    3143 docker_server.go:73] Stop docker server
Mar 13 12:41:12 ip-172-18-15-85.ec2.internal systemd[1]: origin-node.service: main process exited, code=exited, status=1/FAILURE
Mar 13 12:41:12 ip-172-18-15-85.ec2.internal systemd[1]: Failed to start OpenShift Node.
Mar 13 12:41:12 ip-172-18-15-85.ec2.internal systemd[1]: Unit origin-node.service entered failed state.
Mar 13 12:41:12 ip-172-18-15-85.ec2.internal systemd[1]: origin-node.service failed.
Mar 13 12:41:17 ip-172-18-15-85.ec2.internal systemd[1]: origin-node.service holdoff time over, scheduling restart.
Mar 13 12:41:17 ip-172-18-15-85.ec2.internal systemd[1]: Starting OpenShift Node...

**Comment by sdodson** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18985/test_pull_request_origin_extended_conformance_install/9106/

**Comment by sjenning** [comment]
Possibly related to https://github.com/openshift/origin/pull/18886.
Was there a corresponding change in the systemd unit for the node to switch it to `Type=notify` (if it isn't already)
