### ISSUE TITLE
Get routing suffix in template

### ISSUE THREAD

**Issue by eivantsov** [openshift/origin#18976]
Hi,

Is it possible to have an env that will automatically resolve to routing suffix of my OpenShift cluster? I need it as env value in one of deployment configs in a template.

**Comment by jwforres** [comment]
@openshift/sig-developer-experience @openshift/sig-networking

**Comment by bparees** [comment]
No, there is no mechanism for this.  The closest you can get is to have a parameter in your template and make users fill in the value appropriately when instantiating the template.  (And then use the parameter to define the env value in your DC)
