### ISSUE TITLE
Do more checks when docker connection refused

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1897]
There are many reasons why OpenShift, when running in a container, can't talk to docker
1. Daemon not listening on unix socket
2. Daemon using TLS
3. No client cert or client cert invalid
4. Socket not mounted into container (does not exist)
5. Socket not a socket, is a file instead (or directory)
6. Selinux denial

We should check for more of these conditions and print them if they occur to help debug it.

**Comment by bparees** [comment]
@smarterclayton yours unless you decide to close it or pick a victim
