### ISSUE TITLE
Web Console Deployment Failing on GCP Tests

### ISSUE THREAD

**Issue by DirectXMan12** [openshift/origin#18972]
Web console deployment on for the GCP test appears to be failing, which seems to be causing the GCP tests to fail (since the cluster doesn't come up).

For example:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18926/test_pull_request_origin_extended_conformance_gce/17627/

The reason seems to be a scheduling failure due to node unreadiness:

```
    "LAST SEEN   FIRST SEEN   COUNT     NAME                                           KIND         SUBOBJECT   TYPE      REASON              SOURCE                  MESSAGE", 
        "4s          10m          37        webconsole-5b4d568df4-rmgkz.151b963cf006b27e   Pod                      Warning   FailedScheduling    default-scheduler       0/4 nodes are available: 4 MatchNodeSelector, 4 NodeNotReady.", 
        "10m         10m          3         webconsole-5b4d568df4.151b963caef5fd7c         ReplicaSet               Warning   FailedCreate        replicaset-controller   Error creating: pods \"webconsole-5b4d568df4-\" is forbidden: error looking up service account openshift-web-console/webconsole: serviceaccount \"webconsole\" not found", 
        "10m         10m          1         webconsole-5b4d568df4.151b963ceffda594         ReplicaSet               Normal    SuccessfulCreate    replicaset-controller   Created pod: webconsole-5b4d568df4-rmgkz", 
        "10m         10m          1         webconsole.151b963cab5ad578                    Deployment               Normal    ScalingReplicaSet   deployment-controller   Scaled up replica set webconsole-5b4d568df4 to 1"
    ]
}
```

Noticed it in #18950 and #18926, but it seems to be affecting others as well ATM.  Seems to happen reliably on retests, so it's either a high-frequency flake or a consistent problem.

**Comment by mfojtik** [comment]
It seems like the nodes are not ready, consequently some other tests are failing as well:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18944/test_pull_request_origin_extended_clusterup/596/

Marking as P0 as this is blocking the queue currently.

**Comment by mfojtik** [comment]
/cc @stevekuznetsov @sjenning 

@sdodson @spadgett  the service account missing is something that ansible provide before webconsole installation?

**Comment by spadgett** [comment]
@mfojtik It's all part of the same template. I think the event is a red herring.

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_web_console/files/console-template.yaml#L108-L114

**Comment by mfojtik** [comment]
@spadgett might be the controller has not noticed it yet, I think the main problem here are the nodes unavailable.

**Comment by spadgett** [comment]
@smarterclayton - @deads2k wants to know if this is the error we made GCP non blocking on.

**Comment by stevekuznetsov** [comment]
No, GCP was made non-blocking to facilitate a change in how we push images.

**Comment by stevekuznetsov** [comment]
@mfojtik are there action items for me here? Are we missing logs? Do we need more data from the infra?

**Comment by smarterclayton** [comment]
This is why I send emails out to aos-devel about things being broken :)

If your pods don't schedule because nodes aren't ready, it's almost 100% of the time because openshift sdn didn't deploy.  In all likelihood you're waiting for https://github.com/openshift/openshift-ansible/pull/7502 to merge.

**Comment by DirectXMan12** [comment]
Ah, I had missed that email.  Too much noise on aos-devel :-/.  Closing this as per @smarterclayton's email.
