### ISSUE TITLE
Permission denied with pod

### ISSUE THREAD

**Issue by ibaboo** [openshift/origin#18974]
I am testing openshift on the ALL in one server. My Pod which contains a jboss docker images, is not starting up successfully because jboss cannot write to the logs directory. 

/jboss-eap-7.1/standalone/log/gc.log due to Permission denied

The container is not run as root but as a jboss user.

##### Version
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
create a docker container which runs as a user jboss
push container to registry
create deployment with container

##### Current Result
Pod does not start up successfully because of Permission denied
##### Expected Result
Pod to start successfully with jboss running

##### Additional Information
This docker images runs successfully on native docker. It also works as expected in minikube. Not sure why I am having issues with openshift.

**Comment by php-coder** [comment]
Unfortunately, without details I can only guess what's happening there. Obviously, the log directory has permissions/owner that doesn't match with UID under which a container is running.

In order to prove that, I need to see a pod definition and Dockerfile.

**Comment by ibaboo** [comment]
Yes you are correct. The docker container uses a user called jboss UID 1001. Is it possible to use the same user in openshift? I see the POD is getting a UID of 1000000

**Comment by php-coder** [comment]
> Is it possible to use the same user in openshift?

Yes, it's possible.

The first step is to request a particular UID by setting `securityContext.runAsUser: 1001` (see for details: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)

The second step is to ensure that Service Account is able to request arbitrary UID. By default, they can't do that (by security reasons). But cluster administrator can grant such power by granting access to SecurityContextConstraints (SCC) that allows arbitrary UIDs. For example, you can grant access to `anyuid` SCC. Here is an example: https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile Note that this examples grants access to all authenticated users, but it's too much in your case and you only need to grant access to a particular service account (most likely to `system:<project name>:default`).

Please, close this issue if this helps you.

**Comment by php-coder** [comment]
P.S. Perhaps, you don't need the 2nd step as it seems that your service account already has such permissions. Again, I can only guess because you haven't share Dockerfile and a pod definition.

**Comment by ibaboo** [comment]
thanks , you pay close this ticket
