### ISSUE TITLE
Istio: OpenShift unable to show logs from builds and deployments

### ISSUE THREAD

**Issue by jamesfalkner** [openshift/origin#18997]
When using Istio auto-injection, builder and deployer pods get sidecar proxies auto injected.

When a build is created, and `oc logs -f bc/bcname` is issued, it errors:

```
% oc new-app --name fail-project nodejs~https://github.com/openshift/nodejs-ex
% oc logs -f bc/fail-project
Cloning "https://github.com/openshift/nodejs-ex" ...
	Commit:	93fc25fd35068aa311f4722e4d7e5187b06edd7b (Merge pull request #170 from dharmit/add-minishift-to-readme)
	Author:	Ben Parees <bparees@users.noreply.github.com>
	Date:	Tue Mar 6 13:34:31 2018 -0500
error retrieving logs for build pod: foo/fail-project-1-build container: , a container name must be specified for pod fail-project-1-build, choose one of: [sti-build istio-proxy] or one of the init containers: [git-clone manage-dockerfile istio-init]
```

##### Version
```
oc v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
See Description. it's `oc new-app` and `oc logs -f`.

##### Current Result
See Description for error message.

##### Expected Result
No error message and show me the logs.

##### Additional Information
This is under an auto-injected project using Istio 0.6.0. A sidecar proxy is injected into _any_ pod in the namespace, including _builder_ and _deployer_ pods.

**Comment by jwforres** [comment]
@openshift/sig-developer-experience @openshift/sig-master 

at a guess this is because our API's for build logs and deployment logs are assuming the build/deploy pods only have a single container, and in this case they now have two and so the logs API requires you to specify which container.

**Comment by bparees** [comment]
we'll need to set the container name here:
https://github.com/openshift/origin/blob/master/pkg/build/registry/buildlog/rest.go#L309

but the container name can vary, so we'll have to inspect the build pod and find the right container name (sti-build, docker-build, possibly something else in the future) to specify there.

**Comment by bparees** [comment]
@jamesfalkner please clone this issue for the deployment logs problem, it's a separate team that will need to address it.

**Comment by jamesfalkner** [comment]
Ok... one other thing I was thinking - aside from supporting multiple containers in builder and deployer pods, I wonder if Istio should have some provision for kubernetes vendors to provide "hints" (e.g. annotations) that specify that some kinds of pods shouldn't automatically get proxied, namely pods not created directly by applications, like builder and deployer pods, which are ephemeral and sort of like "worker" pods that don't expose services or participate in the service mesh. Do we need circuit breakers for builders anyway? :)

**Comment by bparees** [comment]
> Do we need circuit breakers for builders anyway

yeah my initial reaction was that istio shouldn't be doing this, there's really no value to adding it to a build pod, it's just wasted resources.  But the sidecar handles outbound traffic too, right?  In theory that could be relevant.

**Comment by jamesfalkner** [comment]
Yeah, good point - in fact I was surprised that the build succeeded at all because I thought that by default Istio prevented egress outside the network.. but my maven builds were able to download the internet (as they always do) with no special config. But I could see a use case that would prevent builder pods from doing that, to prevent pulling in untrusted code, so I guess the proxy would be useful for builders and deployers as a safeguard.

**Comment by bparees** [comment]
>  I thought that by default Istio prevented egress outside the network.. but my maven builds were able to download the internet (as they always do) with no special config.

The maven part of the build runs in a container that is not part of the pod (though it should have the same network namespace as the pod, so I guess i'd expect istio to still intercept?).  The git clone, however, does run inside an initcontainer in the pod, so the clone should be impacted..unless of course because it's run in an initcontainer, the istio sidecar isn't up yet and thus isn't doing anything.
