### ISSUE TITLE
Istio: OpenShift deployer pods fail when injected with sidecar envoy proxies

### ISSUE THREAD

**Issue by jamesfalkner** [openshift/origin#18993]
##### Version
```
oc v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
1. Install Istio 0.6.0 to OpenShift 3.9.0.beta3 following the [Kubernetes Quickstart](https://istio.io/docs/setup/kubernetes/quick-start.html)
2. Enable [automatic sidecar injection](https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection) (also requires that you enable the `MutatingAdmissionWebhook` and the Kubernetes certificate signing service)
3. Create new project `oc new-project foo`
4. Mark it as auto-injectable `oc label namespace foo istio-injection=enabled`
5. deploy any app and carefully watch the _deployer_ pod attempt to deploy pods.

##### Current Result
When the application's _deployer_ pod is spun up, it immediately fails when it tries to access the master to retrieve the DeploymentConfig object through the REST API. For example, deploying an application called nodejs-example, the error is:

```
error: couldn't get deployment nodejs-example-1: Get https://172.30.0.1:443/api/v1/namespaces/fail/replicationcontrollers/nodejs-example-1:  dial tcp 172.30.0.1:443: getsockopt: connection refused
```

After employing the workaround described below (adding sleep time before `/usr/bin/openshift-deploy is called`), the deployment succeeds, _however_ the Deployer pod never "exits" because one of the containers in the pod (the one running the envoy proxy) never exits, so OpenShift thinks the deployment is still in progress forever, until eventually timing out (after about 6 hours) and rolling the deployment back.

##### Expected Result
The deployer pod should successfully deploy the application.

##### Additional Information
I believe the root cause for the inability to contact the master when the deployer pod boots up is [this Istio bug](https://github.com/istio/istio/issues/3533), however I also believe that this OpenShift-specific pod and associated executable (`/usr/bin/openshift-deploy`) should attempt some amount of retries before giving up.

For example, if I add some sleep time before `openshift-deploy` is called, it works every time and is my current workaround (in the DeploymentConfig):

```yaml
spec:
  strategy:
    customParams:
      command: 
      - /bin/sh
      - '-c'
      - 'sleep 5; echo slept for 5; /usr/bin/openshift-deploy'
```

**Comment by Stono** [comment]
Hey, 
I notice you cross linked my istio issue.
The sleeps aren't deterministic enough and i've found that sometimes it takes longer than 5 seconds for the envoy sidecars to sync their config (which sucks) so you might want to look at something which retries.

We use this:

```
echo "Waiting for Kubernetes API to be available (istio-proxy bollocks)...."
until $(curl -k --output /dev/null --silent --fail https://kubernetes.default/version); do
		CURRENT_ATTEMPT=$((CURRENT_ATTEMPT+1))
    printf '.'
    sleep 2
		if [ "$CURRENT_ATTEMPT" = "$MAX_TRIES" ]; then
			echo "Failed to get kubernetes version after $MAX_TRIES"
			exit 1
		fi
done
```

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by tnozicka** [comment]
> Enable automatic sidecar injection (also requires that you enable the MutatingAdmissionWebhook and the Kubernetes certificate signing service)

Seems like istio default admission injected a pod that usually messes up with iptables and broke kubernetes internal networking.

On the question of the init container staying, you are not allowed to auto inject that into deployer pod to make it's lifetime infinite. I guess istio needs to detect if it is the only one container running and end but preferably not inject it blindly everywhere. Prolonging the lifetime of random pods will break so much more. (Jobs, any controlled pod, ...)

Anyways those are istio issues and should be solved there. I don't see this being OpenShift specific.

We can't add retries everywhere if istio is breaking networking. I would recommend you to use upstream Deployments to avoid having istio messing up with deployer pod.
