### ISSUE TITLE
flake: Control plane install failed

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#19001]
Seen: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18983/test_pull_request_origin_extended_conformance_gce/17707/ (but I saw this yesterday as well)

```
Failure summary:
  1. Hosts:    ci-prtest-5a37c28-17707-ig-m-0ckp
     Play:     Configure masters
     Task:     Report control plane errors
     Message:  Control plane install failed.
```

Seems to be related to:

`
Mar 15 14:31:22 ci-prtest-5a37c28-17707-ig-m-0ckp origin-node[16754]: E0315 14:31:22.019323   16754 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://internal-api.prtest-5a37c28-17707.origin-ci-int-gce.dev.rhcloud.com:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dci-prtest-5a37c28-17707-ig-m-0ckp&limit=500&resourceVersion=0: dial tcp 35.185.30.156:8443: getsockopt: connection refused 
`

**Comment by lomori** [comment]
+1.

**Comment by fmq** [comment]
I'm getting this same error.
