### ISSUE TITLE
Can I specify the namespace of ImageStrema and Template？

### ISSUE THREAD

**Issue by fenggolang** [openshift/origin#19015]
Can I specify the namespace of ImageStream and Template, not the default openshift namespace?

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by miminar** [comment]
@wpengcheng Maybe I misunderstood, but does the following answer your question?
```
$ oc create --namespace testproject -f wordpress/template/wordpress-mysql.json
template "wordpress-mysql-example" created
$ oc get template --namespace testproject
NAME                      DESCRIPTION                                                                        PARAMETERS     OBJECTS
wordpress-mysql-example   An example WordPress application with a MySQL database.For more information a...   10 (3 blank)   7
$ oc new-app --namespace testproject --template=wordpress-mysql-example
--> Deploying template "testproject/wordpress-mysql-example" to project testproject
```

Analogically for imagestream.

**Comment by bparees** [comment]
@wpengcheng also possibly relevant to your question...you can control what namespace objects from a template get defined in via a parameter, see the "Note" at the end of this section:
https://docs.openshift.org/latest/dev_guide/templates.html#writing-object-list

**Comment by bparees** [comment]
@fenggolang i think we've addressed your question but please comment back if we have not.
