### ISSUE TITLE
User with admin rights fail to call openshift api; gets forbidden error 

### ISSUE THREAD

**Issue by jasjeetkaur2211** [openshift/origin#19022]
I want to call the openshift api from withing a container to fetch the scale of other deployments and modify them. I have tried to do so using normal serviceaccount with user:info, but I am getting a forbidden error as above for even fetching the scale and getting denied when I try to update the scope to user:full for the serviceaccount. I have the admin rights.

Version openshift v1.5.0

On firing the below command, getting forbidden error
```
curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/apps/v1/namespaces/$NAMESPACE/deployments/$NAME/scale

```

##### Steps To Reproduce
1. assign admin role to user xyz
2. verify via "oc get rolebindings"

```
NAME                    ROLE                    USERS           GROUPS                             SERVICE ACCOUNTS   SUBJECTS
admin                   /admin                  admin, xyz                                                         
edit                    /edit                   xyz                                                                
system:deployers        /system:deployer        xyz                                             deployer           
system:image-builders   /system:image-builder                                                      builder            
system:image-pullers    /system:image-puller                    system:serviceaccounts:<namespace>                      
view                    /view                   ABC                                                                   



```

2. Fire the above command for getting the scale of the deployment

RESULT:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User xyz cannot get apps.deployments/scale in project ..",
  "reason": "Forbidden",
  "details": {
    "name": <name of deployment>,
    "group": "apps",
    "kind": "deployments/scale"
  },
  "code": 403
}
```

Expected Result: scale of the deployment

Can anybody please point out, what I am doing wrong here?

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by liggitt** [comment]
> openshift v1.5.0

deployments did not exist in the apps API group until v3.6.0

/close

**Comment by enj** [comment]
Use `https://$ENDPOINT/apis/extensions/v1beta1/namespaces/$NAMESPACE/deployments/$NAME/scale` instead.

**Comment by jasjeetkaur2211** [comment]
@enj Here, the $NAME would the be the name as per the deployment config, right?

**Comment by jasjeetkaur2211** [comment]
I am sorry, the version of oc is oc v3.6.0+c4dd4cf
