### ISSUE TITLE
data race in writerlease.go

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#19049]
From https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19005/test_pull_request_origin_unit/10982/

    === RUN   TestWaitForLeader
    --- PASS: TestWaitForLeader (0.00s)
    === RUN   TestBecomeLeaderAfterRetry
    --- PASS: TestBecomeLeaderAfterRetry (0.00s)
    === RUN   TestBecomeFollowerAfterRetry
    --- PASS: TestBecomeFollowerAfterRetry (0.00s)
    === RUN   TestRunOverlappingWork
    --- PASS: TestRunOverlappingWork (0.00s)
    	writerlease_test.go:97: processing first
    	writerlease_test.go:108: waiting for second item to be added
    	writerlease_test.go:118: second item added
    	writerlease_test.go:99: processing second
    	writerlease_test.go:101: processing done
    === RUN   TestExtend
    --- PASS: TestExtend (0.00s)
    ==================
    WARNING: DATA RACE
    Read at 0x0000006e6260 by goroutine 26:
      github.com/openshift/origin/pkg/util/writerlease.(*WriterLease).work()
          github.com/openshift/origin/pkg/util/writerlease/_test/_obj_test/writerlease.go:248 +0x1b3
      github.com/openshift/origin/pkg/util/writerlease.(*WriterLease).Run.func1()
          github.com/openshift/origin/pkg/util/writerlease/_test/_obj_test/writerlease.go:118 +0xa9
    
    Previous write at 0x0000006e6260 by goroutine 23:
      github.com/openshift/origin/pkg/util/writerlease.TestExtend.func2()
          /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/util/writerlease/writerlease_test.go:126 +0x3d
      github.com/openshift/origin/pkg/util/writerlease.TestExtend()
          /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/util/writerlease/writerlease_test.go:160 +0x561
      testing.tRunner()
          /usr/local/go/src/testing/testing.go:746 +0x16c
    
    Goroutine 26 (running) created at:
      github.com/openshift/origin/pkg/util/writerlease.(*WriterLease).Run()
          github.com/openshift/origin/pkg/util/writerlease/_test/_obj_test/writerlease.go:115 +0xe2
    
    Goroutine 23 (finished) created at:
      testing.(*T).Run()
          /usr/local/go/src/testing/testing.go:789 +0x568
      testing.runTests.func1()
          /usr/local/go/src/testing/testing.go:1004 +0xa7
      testing.tRunner()
          /usr/local/go/src/testing/testing.go:746 +0x16c
      testing.runTests()
          /usr/local/go/src/testing/testing.go:1002 +0x521
      testing.(*M).Run()
          /usr/local/go/src/testing/testing.go:921 +0x206
      main.main()
          github.com/openshift/origin/pkg/util/writerlease/_test/_testmain.go:98 +0x2f0
    ==================
    FAIL
    coverage: 66.4% of statements
    FAIL	github.com/openshift/origin/pkg/util/writerlease	0.016s

**Comment by pravisankar** [comment]
If this was not happening before, it could be related to https://github.com/openshift/origin/pull/19018 (recent changes to writerlease.go)

**Comment by danwinship** [comment]
> If this was not happening before, it could be related to #19018 (recent changes to writerlease.go)

There didn't seem to be any existing bug report of it, so yeah, it's probably new

**Comment by smarterclayton** [comment]
Fixed
