### ISSUE TITLE
Using the oauth token to edit the scale of a deploymentconfig

### ISSUE THREAD

**Issue by jasjeetkaur2211** [openshift/origin#19048]
I am trying to update the scale of other deployments in a project from within a container in the project.

I use WebAuth api to get a token, from domain oauth on my server, for assigning scope [user:info] to a service account created.  I am able to access the services offered by other containers using this approach.

But now I am trying to update the scale of other deployments.

Version
```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxx:8443
openshift v1.5.0
kubernetes v1.5.2+43a9be4
```

Steps To Reproduce [Testing from within an oc shell of the service]
1. Get the access token by performing an authorized login and using a serviceaccount with scope[user:info] 
2. Got an access token - $TOKEN
3. Use this token to fetch the deploymentconfig scales
```
curl -k 
    -H "Authorization: Bearer $TOKEN" 
    -H 'Accept: application/json' 
https://xxx:8443/oapi/v1/namespaces/test/deploymentconfigs/$NAME/scale
```
Current Result:

```{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "scopes [user:info] prevent this action; User \"jk\" cannot get deploymentconfigs/scale in project \"test\"",
  "reason": "Forbidden",
  "details": {
    "name": ...,
    "kind": "deploymentconfigs/scale"
  },
  "code": 403
}
```

Expected Result:

If I use the token as follows from within the container:

`TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"`

and then execute the same command

```
curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \ 
      https://xxx:8443/oapi/v1/namespaces/test/deploymentconfigs/$NAME/scale
`
The response is as follows:

`{
  "kind": "Scale",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    ...
  },
  "spec": {
    "replicas": 2
  },
  "status": {
    "replicas": 2,
    "selector": {
      ....
    },
    "targetSelector": ...
  }
```

Can anybody please suggest how to use the token correctly?

Additional Information
user 'jk' has admin rights on the namespace.

**Comment by liggitt** [comment]
cc @openshift/sig-security

**Comment by simo5** [comment]
The token is used correctly but it is scoped (ie restricted) to only work for [user:info]. why are you getting a scoped token if you do not want the restriction ?

**Comment by jasjeetkaur2211** [comment]
I am allocating the token via outh api and when I try to allocate scope[user:full] or try to omit the scope altogether, my request is denied.

**Comment by simo5** [comment]
you need to change the oauthclient configuration for the service account to allow it to request user:full
See https://docs.openshift.com/container-platform/3.7/architecture/additional_concepts/authentication.html#service-accounts-as-oauth-clients

**Comment by liggitt** [comment]
`user:full` is never allowed for a service account. at most, you can ask for a specific role within the service account's namespace (e.g. `role:edit:<namespace>` would let you scale things in the namespace)

**Comment by jasjeetkaur2211** [comment]
@liggitt @simo5  Thanks it worked.. :)
