### ISSUE TITLE
RHEL74 "Package 'origin-3.9*' not found"

### ISSUE THREAD

**Issue by piyushkv1** [openshift/origin#19047]
TASK [openshift_version : fail] *****************************************************************************************************************************************************************************************
task path: /root/openshift-ansible/roles/openshift_version/tasks/check_available_rpms.yml:8
fatal: [openshift.node.1]: FAILED! => {
    "changed": false,
    "msg": "Package 'origin-3.9*' not found"
}
        to retry, use: --limit @/root/openshift-ansible/playbooks/deploy_cluster.retry

PLAY RECAP **************************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0
openshift.node.1           : ok=26   changed=0    unreachable=0    failed=1
openshift.node.2           : ok=17   changed=0    unreachable=0    failed=0

INSTALLER STATUS ********************************************************************************************************************************************************************************************************
Initialization             : In Progress (0:00:28)

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
ansible-playbook -i /root/hosts openshift-ansible/playbooks/deploy_cluster.yml -e openshift_deployment_type=origin  -vvv
TASK [openshift_version : fail] *****************************************************************************************************************************************************************************************
task path: /root/openshift-ansible/roles/openshift_version/tasks/check_available_rpms.yml:8
fatal: [openshift.node.1]: FAILED! => {
    "changed": false,
    "msg": "Package 'origin-3.9*' not found"
}
        to retry, use: --limit @/root/openshift-ansible/playbooks/deploy_cluster.retry

PLAY RECAP **************************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0
openshift.node.1           : ok=25   changed=2    unreachable=0    failed=1
openshift.node.2           : ok=16   changed=2    unreachable=0    failed=0

INSTALLER STATUS ********************************************************************************************************************************************************************************************************
Initialization             : In Progress (0:00:30)

**Comment by zhwenh** [comment]
3.9.0 yum installation package has not been released ！

**Comment by phemmer** [comment]
You need to set `openshift_repos_enable_testing=True`

**Comment by jwforres** [comment]
@openshift/sig-cluster-lifecycle

**Comment by sdodson** [comment]
Yes, until the 3.9 RPMs have shipped in Centos PaaS SIG you'll need `openshift_repos_enable_testing=True` I'll check on status of those builds during their meeting tomorrow.

**Comment by infinitydon** [comment]
Am still getting the same error after enabling openshift_repos_enable_testing=True

Message:  Package 'origin-3.9*' not found

**Comment by pgeorgiev333** [comment]
after setting "openshift_repos_enable_testing=true" run the "prerequisites.yml" playbook, and then try again with the "deploy_cluster.yml" playbook. That fixed it for me.

**Comment by infinitydon** [comment]
Thanks.. That fixed it..

**Comment by DanyC97** [comment]
@infinitydon @piyushkv1 you no longer need `openshift_repos_enable_testing=true` since yesterday we promoted the rpms into the official centos repo.

with that said can we close this issue ?

**Comment by sdodson** [comment]
3.9 packages have shipped to the released repos in centos.
