### ISSUE TITLE
[Conformance][Area:Networking][Feature:Router] The HAProxy router converges when multiple routers are writing conflicting status

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#19058]
Seen here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18988/test_pull_request_origin_extended_conformance_gce/17867/

```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/router/stress.go:168
Expected
    <int>: 3
to be <
    <int>: 3
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/router/stress.go:278
```

**Comment by mfojtik** [comment]
@smarterclayton i remember you had PR that was fixing the router status or something related :-)

**Comment by smarterclayton** [comment]
This was fixed two days ago, which looks like when the job ran.

**Comment by mfojtik** [comment]
@smarterclayton it is back again:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19301/test_pull_request_origin_extended_conformance_gce/18922/

```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/router/stress.go:168
Expected
    <int>: 18
to be <
    <int>: 10
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/router/stress.go:263
				
```

**Comment by sjenning** [comment]
Very frequently
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19288/test_pull_request_origin_extended_conformance_gce/18993/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19288/test_pull_request_origin_extended_conformance_gce/18993/

**Comment by smarterclayton** [comment]
Those are different, but #19175 is the reason and the PR which contains several important router fixes.

**Comment by knobunc** [comment]
Argh... and it's happening again.

**Comment by gabemontero** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19612/test_pull_request_origin_extended_conformance_gce/20075/

**Comment by jpeeler** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19637/test_pull_request_origin_extended_conformance_gce/20084/

**Comment by bparees** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19664/test_pull_request_origin_extended_conformance_gce/20199/

**Comment by bparees** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19677/test_pull_request_origin_extended_conformance_gce/20223/

Seems pretty frequent again.
