### ISSUE TITLE
vsphere: Global.WorkingDir is empty

### ISSUE THREAD

**Issue by phemmer** [openshift/origin#19068]
When using the vsphere cloud provider with the configured `working-dir = ""`, the api server throws an error and fails to start. The documentation states that `working-dir` can be left empty if VMs are located in the root folder.

##### Version
```
$ openshift version
openshift v3.9.0-alpha.4+881f1dd-440
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.8
```

##### Steps To Reproduce
1. configure system according to [the documentation](https://docs.openshift.com/container-platform/3.9/install_config/configuring_vsphere.html#vsphere-enabling) with `working-dir = ""`.
2. run advanced installation via openshift-ansible repo

##### Current Result
```
Mar 22 14:26:46 openshift-master-dev atomic-openshift-master-api[15533]: E0322 14:26:46.915383   15533 vsphere.go:260] Global.WorkingDir is empty!
Mar 22 14:26:46 openshift-master-dev atomic-openshift-master-api[15533]: F0322 14:26:46.915416   15533 start_api.go:67] error setting the external host value: "vsphere" cloud provider could not be initialized: could not init cloud provider "vsphere": Global.WorkingDir is empty!
```

##### Expected Result
No error

**Comment by phemmer** [comment]
Another issue I just stumbled across:
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html
According to that ^ documentation, the `vsphere.conf` format for kubernetes 1.9.x doesn't even have a `working-dir` param. That param is supposed to be for 1.8.x or below. All the params [documented for OpenShift 3.9](https://docs.openshift.com/container-platform/3.9/install_config/configuring_vsphere.html#vsphere-enabling) seem to correspond to the 1.8.x documentation of the vSphere storage module.

**Comment by jwforres** [comment]
@mfojtik recommendations on who should look into this?

**Comment by dgabrysch** [comment]
Same for me :(
