### ISSUE TITLE
see if we can shorten our build tests

### ISSUE THREAD

**Issue by bparees** [openshift/origin#19077]
Our build extended bucket now takes almost 2 hours to run.  We should look for some low hanging fruit to simplify/speed up.

See:
https://ci.openshift.redhat.com/jenkins//job/test_branch_origin_extended_builds/411/consoleText

and search for `SLOW TEST`.

Anything over 120s we should examine to see if we can speed it up or fold it into another test so we aren't paying the setup costs over and over again.

Things that make our build tests slow:

1) pushing images when we could have just skipped the push step
2) building a large repo or complex app when a smaller repo or simpler app would do  (we should never git clone origin, it's huge)
3) builds that have to pull large/unique base images

**Comment by coreydaley** [comment]
If a test needs multiple builds, such as the build pruning tests, can we change them from serial to parallel builds? That might shave a bit off also.
It looks like one of the valueFrom tests is pretty bad > 400, i'll take a look at it and see if I can pair that down some.

**Comment by coreydaley** [comment]
@bparees i just want to verify, the [SLOW TEST] applies to the test ABOVE it correct? (that would make the most sense I guess)

**Comment by wozniakjan** [comment]
just to put some highlights for the slowest tests, I see some repeats in `test/extended/builds/pipeline.go` but it is not always slow there. For example `Waiting for openshift-jee-sample-1 to complete` on average takes about a minute, only in one case it was 10 minutes. I will try to come up with some smarter and at least semi-automated evaluation from the logs so we can correlate multiple logs from runs

```
1. candidate - 650.503 seconds
------------------------------
test/extended/builds/pipeline.go
STEP: starting the pipeline build and waiting for it to complete
Mar 22 18:46:58.436: INFO: Waiting for openshift-jee-sample-1 to complete
Mar 22 18:55:29.500: INFO: Done waiting for openshift-jee-sample-1: util.BuildResult{BuildPath:"build/openshift-jee-sample-1", BuildName:"openshift-jee-sample-1", StartBuildStdErr:"", StartBuildStdOut:"build/   openshift-jee-sample-1", StartBuildErr:error(nil), BuildConfigName:"", Build:(*build.Build)(0xc4217f7200), BuildAttempt:true, BuildSuccess:true, BuildFailure:false, BuildCancelled:false, BuildTimeout:false,     LogDumper:(util.LogDumperFunc)(nil), Oc:(*util.CLI)(0xc4211161c0)}


2. candidate - 644.797
----------------------
test/extended/builds/pipeline.go
STEP: starting the pipeline build and waiting for it to complete, pass: 0
Mar 22 18:25:30.087: INFO: Waiting for sample-pipeline-openshift-client-plugin-1 to complete
Mar 22 18:32:11.099: INFO: Done waiting for sample-pipeline-openshift-client-plugin-1: util.BuildResult{BuildPath:"build/sample-pipeline-openshift-client-plugin-1", BuildName:"sample-pipeline-openshift-client-  plugin-1", StartBuildStdErr:"", StartBuildStdOut:"build/sample-pipeline-openshift-client-plugin-1", StartBuildErr:error(nil), BuildConfigName:"", Build:(*build.Build)(0xc4213eb500), BuildAttempt:true,           BuildSuccess:true, BuildFailure:false, BuildCancelled:false, BuildTimeout:false, LogDumper:(util.LogDumperFunc)(nil), Oc:(*util.CLI)(0xc420856000)}

3. candidate - 500.601
----------------------
test/extended/builds/pipeline.go
STEP: waiting for jenkins deployment
Mar 22 17:56:50.958: INFO: waiting for deploymentconfig extended-test-jenkins-pipeline-t74td-xsn5j/jenkins to be available with version 1
Mar 22 18:01:11.967: INFO: deploymentconfig extended-test-jenkins-pipeline-t74td-xsn5j/jenkins available after 4m21.009321811s 
...
STEP: starting the pipeline build and waiting for it to complete
Mar 22 18:01:36.706: INFO: Waiting for openshift-jee-sample-1 to complete
Mar 22 18:04:27.744: INFO: Done waiting for openshift-jee-sample-1: util.BuildResult{BuildPath:"build/openshift-jee-sample-1", BuildName:"openshift-jee-sample-1", StartBuildStdErr:"", StartBuildStdOut:"build/   openshift-jee-sample-1", StartBuildErr:error(nil), BuildConfigName:"", Build:(*build.Build)(0xc421404300), BuildAttempt:true, BuildSuccess:true, BuildFailure:false, BuildCancelled:false, BuildTimeout:false,     LogDumper:(util.LogDumperFunc)(nil), Oc:(*util.CLI)(0xc420e61a40)}

4. candidate - 492.598
----------------------
test/extended/builds/pipeline.go
STEP: waiting for jenkins deployment
Mar 22 18:24:47.008: INFO: waiting for deploymentconfig extended-test-jenkins-pipeline-m6z9h-84g7j/jenkins to be available with version 1
Mar 22 18:26:15.023: INFO: deploymentconfig extended-test-jenkins-pipeline-m6z9h-84g7j/jenkins available after 1m28.014736361s
...
Mar 22 18:27:03.702: INFO:
STEP: waiting for the build to complete
STEP: Waiting for the build uri
STEP: Waiting for the approval prompt
STEP: Approving the current build
Posting to Jenkins resource: "http://172.30.132.38:80/job/extended-test-jenkins-pipeline-m6z9h-84g7j/job/extended-test-jenkins-pipeline-m6z9h-84g7j-bluegreen-pipeline/1/input/Approval/proceedEmpty"
STEP: verifying that the main route has been switched to green
Mar 22 18:30:09.133: INFO: Running 'oc get --config=/tmp/extended-test-jenkins-pipeline-m6z9h-84g7j-user.kubeconfig --namespace=extended-test-jenkins-pipeline-m6z9h-84g7j route nodejs-mongodb-example -o         jsonpath={ .spec.to.name }'

5. candidate - 482.616
----------------------
test/extended/builds/start.go
STEP: start the builds, wait for and confirm successful completion
Mar 22 18:47:58.687: INFO: Waiting for bc-with-pr-ref-docker-1 to complete
Mar 22 18:50:04.779: INFO: Done waiting for bc-with-pr-ref-docker-1: util.BuildResult{BuildPath:"build/bc-with-pr-ref-docker-1", BuildName:"bc-with-pr-ref-docker-1", StartBuildStdErr:"", StartBuildStdOut:"build/bc-with-pr-ref-docker-1", StartBuildErr:error(nil), BuildConfigName:"", Build:(*build.Build)(0xc4213f9500), BuildAttempt:true, BuildSuccess:true, BuildFailure:false, BuildCancelled:false, BuildTimeout:false,    LogDumper:(util.LogDumperFunc)(nil), Oc:(*util.CLI)(0xc420e60700)}
...
Mar 22 18:50:05.534: INFO: Waiting for bc-with-pr-ref-1 to complete
Mar 22 18:55:51.542: INFO: Done waiting for bc-with-pr-ref-1: util.BuildResult{BuildPath:"build/bc-with-pr-ref-1", BuildName:"bc-with-pr-ref-1", StartBuildStdErr:"", StartBuildStdOut:"build/bc-with-pr-ref-1",   StartBuildErr:error(nil), BuildConfigName:"", Build:(*build.Build)(0xc421884c00), BuildAttempt:true, BuildSuccess:true, BuildFailure:false, BuildCancelled:false, BuildTimeout:false, LogDumper:(util.             LogDumperFunc)(nil), Oc:(*util.CLI)(0xc420e60700)}
```

**Comment by bparees** [comment]
the pipeline tests will probably be the hardest ones to improve since they depend on standing up jenkins (which is inherently slow), but the start.go tests are definitely worth looking at.

(also @coreydaley and @gabemontero are already working on improving the pipeline tests)

**Comment by gabemontero** [comment]
On Wed, Apr 4, 2018 at 7:24 AM, jwozniak <notifications@github.com> wrote:

> @coreydaley <https://github.com/coreydaley> , @gabemontero
> <https://github.com/gabemontero> , @bparees <https://github.com/bparees>
> if you are still looking at our tests as well, I started a short 'script'
> that parses the output of our extended tests and tries to identify and
> report slowest parts.
> Maybe you will find it helpful https://github.com/wozniakjan/test_eval
>
Thanks for the pointer Jan - maybe that link should be added to the
template of the
extended test babysitter card, so future assignees can reference ...

@bparees thoughts?

But to your question, I'm done with ext test changes for the time being,
but I'm sure
that is only a temporary condition.

**Comment by bparees** [comment]
>  maybe that link should be added to the template of the extended test babysitter card, so future assignees can reference

sure , feel free to put it on there.

**Comment by wozniakjan** [comment]
Looking at the 25 slowest tests and their bottlenecks, there is one pattern that repeats a lot in pretty much every test and frequently takes ~4 minutes
```
Running 'oc start-build ...'
Waiting for [xyz_build] to complete
Done waiting for [xyz_build]
```

This happens even with s2i php (valuefrom.go:83) or ruby (contextdir.go:101) based images. 

Tryin the builds locally without the test framework around it, it looks like culprits may be pulling the project's dependencies (1-2 minutes) and then pushing the image to a registry (1-2 minutes). I will try to enrich the extended test logs with `oc logs -f [build_pod]` to either confirm or deny my assumption. Partially https://github.com/openshift/origin/pull/19197 confirms this, there the waiting for build took ~5 minutes and switching to a leaner build (python app without any dependencies) decreased this to ~1 minute.

I would like to try fixing this with:
1) using the same build base image wherever possible
2) reduce dependencies in the test apps (ideally to 0, like in #19197 )
3) pre-push the shared build base image to the registry so each test pushes only its new layer (this may already be happening and the slowest 25 tests are among the first to try to push its base image)

**Comment by bparees** [comment]
> pre-push the shared build base image to the registry so each test pushes only its new layer (this may already be happening and the slowest 25 tests are among the first to try to push its base image)

since we're using pullthrough now for all the system defined imagestreams, the base image should end up cached in the registry when we pulled it, meaning it should not have to be pushed back.  So nothing explicit should need to be done here.  (Unless the tests are using their own unique imagestream definitions for the base images, or not using imagestreams at all)

The other two suggestions sound reasonable to me.
