### ISSUE TITLE
Compilation of 3.7.2 fails with go 1.10 on macOS

### ISSUE THREAD

**Issue by fxcoudert** [openshift/origin#19086]
Compilation of 3.7.2 fails with go 1.10 on macOS:

```
[FATAL] Detected Go version: go version go1.10 darwin/amd64.
[FATAL] Origin builds require Go version 1.8 or greater.
[ERROR] hack/build-go.sh exited with code 1 after 00h 00m 00s
```

This prevents us from updating to the latest version in Homebrew: https://github.com/Homebrew/homebrew-core/pull/25401

**Comment by ilovezfs** [comment]
Please note that is just the tip of the iceberg.

If the version test is corrected, the build still fails:
```
github.com/openshift/origin/pkg/oc/bootstrap/docker/openshift
github.com/openshift/origin/pkg/oc/cli/cmd/image
github.com/openshift/origin/pkg/oc/bootstrap/docker
github.com/openshift/origin/pkg/oc/cli/cmd/cluster
[ERROR] PID 34375: hack/lib/build/binaries.sh:202: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -pkgdir "${OS_OUTPUT_PKGDIR}/${platform}" -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags="${local_ldflags}" "${goflags[@]:+${goflags[@]}}" "${nonstatics[@]}"` exited with status 2.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/build/binaries.sh:202: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -pkgdir "${OS_OUTPUT_PKGDIR}/${platform}" -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags="${local_ldflags}" "${goflags[@]:+${goflags[@]}}" "${nonstatics[@]}"`
[INFO] 		  2: hack/lib/build/binaries.sh:158: os::build::internal::build_binaries
[INFO] 		  3: hack/build-go.sh:43: os::build::build_binaries
[INFO]   Exiting with code 2.
[ERROR] hack/build-go.sh exited with code 2 after 00h 01m 23s
make: *** [all] Error 2
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make all WHAT=cmd/oc GOFLAGS=-v OS_OUTPUT_GOPATH=1
```

**Comment by mfojtik** [comment]
Interesting :-) It fails with different error for me (`vendor/github.com/google/certificate-transparency` need a bump). 

I would recommend to use the `gvm` until upstream (kubernetes) switch to go 1.10.

**Comment by jwforres** [comment]
@stevekuznetsov adding you since among other issues it looks like our version check isn't handling 1.8 < 1.10 correctly

**Comment by warmchang** [comment]
@fxcoudert You can test :
https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-locally-on-your-host
`Currently, OpenShift is built with go 1.9 and uses Docker 1.13 on Fedora/CentOS/RHEL. MacOS supports builds with go 1.9 and Docker CE 17.09.1 - newer versions of go and Docker are not supported. The exact requirement for Docker is documented here.`

**Comment by stevekuznetsov** [comment]
Not sure we have 3.7 builds as a very high priority right now
/close
