### ISSUE TITLE
"template-service-broker-registration" not found

### ISSUE THREAD

**Issue by felixbecker** [openshift/origin#19081]
Hi, 
I encountered an issue with minishift and the service catalag. I filed the issue here: https://github.com/minishift/minishift/issues/2116 and was ask to report it here since it seems to be an origin issue as I was told.

##### Version

Minishift version:
**v.1.14.0 / openshift/origin:v3.7.0** 
OS: Linux / macOS / Windows
**Mac El Capitan**
Hypervisor: KVM / xhyve / Hyper-V / VirtualBox
**xhyve**

##### Steps To Reproduce
1.) install minishift
2.) MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --service-catalog
##### Current Result

```
 -- Registering template service broker with service catalog ... FAIL
   Error: cannot register the template service broker
   Caused By:
     Error: cannot retrieve template "template-service-broker-registration" from namespace "openshift-infra"
     Caused By:
       Error: templates.template.openshift.io "template-service-broker-registration" not found
Error during 'cluster up' execution: Error starting the cluster.
```

##### Expected Result
Service Catalog should work
##### Additional Information
detailed logs: https://gist.github.com/felixbecker/6b1b498f597bb584d9ed06077ceaad4a
issue at the minihub repo: https://github.com/minishift/minishift/issues/2116

**Comment by jwforres** [comment]
@openshift/sig-developer-experience since this TSB issue is on 3.7
