### ISSUE TITLE
Unable to start  openshift origin services after a node reboot 

### ISSUE THREAD

**Issue by toni-moreno** [openshift/origin#19094]
[provide a description of the issue]

Can not reboot the nodes after  a successfull opensift v3.7.1 install ,if done the pod's anymore are running ok

##### Version

[root@openshift01 ~]# oc version
oc v3.7.1+282e43f-42
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift01:8443
openshift v3.7.1+282e43f-42
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
With this inventory file.

````ini
[OSEv3:children]
masters
nodes
etcd

[masters]
192.168.1.111 openshift_ip=192.168.1.111 openshift_schedulable=true

[etcd]
192.168.1.111 openshift_ip=192.168.1.111

[nodes]
192.168.1.111 openshift_ip=192.168.1.111 openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

[OSEv3:vars]
ansible_ssh_user=root
enable_excluders=False
enable_docker_excluder=False
ansible_service_broker_install=False

containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

openshift_node_kubelet_args={'pods-per-core': ['10']}

deployment_type=origin
openshift_deployment_type=origin

openshift_release=v3.7.1
openshift_pkg_version=v3.7.1
openshift_image_tag=v3.7.1
openshift_service_catalog_image_version=v3.7.1
template_service_broker_image_version=v3.7.1
openshift_metrics_image_version=v3.7.1

osm_use_cockpit=true

openshift_metrics_install_metrics=True
openshift_logging_install_logging=True

openshift_hosted_prometheus_deploy=true
openshift_prometheus_namespace=openshift-metrics
openshift_prometheus_node_selector={"region":"infra"}

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

openshift_public_hostname=console.myorg.org
openshift_master_default_subdomain=apps.myorg.org
````

1. ansible-playbook -i inventory.ini openshift-ansible/playbooks/byo/config.yml
2. reboot

##### Current Result

![image](https://user-images.githubusercontent.com/5883405/37903299-a1040912-30f7-11e8-9f8e-ebe1abf770fe.png)
![image](https://user-images.githubusercontent.com/5883405/37903382-f88b682e-30f7-11e8-9df1-dd88428f0784.png)

##### Expected Result

All working ok as it does before the reboot

**Comment by toni-moreno** [comment]
attached the output for the oc_adm_diagnostics

[oc_adm_diagnostics_20180326.txt](https://github.com/openshift/origin/files/1847591/oc_adm_diagnostics_20180326.txt)

**Comment by jwforres** [comment]
@openshift/sig-networking since the events largely seem to revolve around networking issues
