### ISSUE TITLE
Customizing the Router Service Ports, but  the router can not work

### ISSUE THREAD

**Issue by alicealvy** [openshift/origin#19092]
Customizing the Router Service Ports, but  the router can not work

##### Version
# oc version
oc v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.example.com:8443
openshift v3.6.173.0.49
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1.  create router
$ oc adm router --replicas=0 --ports='10080:10080,10443:10443'  --host-network=false

$ oc set env dc/router ROUTER_SERVICE_HTTP_PORT=10080 \
ROUTER_SERVICE_HTTPS_PORT=10443

$ oc scale dc/router --replicas=1

2. router is ok
# oc get svc
NAME               CLUSTER-IP      EXTERNAL-IP       PORT(S)                        AGE
router             172.30.60.81    <none>            1936/TCP,10080/TCP,10443/TCP   1h 

# oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
router-2-3s3xb             1/1       Running   1          1h

##### Current Result
1. return no route when accessing the router
# curl docker-registry-default.router.default.svc.cluster.local
curl: (7) Failed connect to docker-registry-default.router.default.svc.cluster.local:80; No route to host

PS: I don't know the return port is 80?

##### Expected Result
1. return correct information

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by alicealvy** [comment]
sorry, it is my fault. the router can work,
curl docker-registry-default.router.default.svc.cluster.local:10080 
i should change the default port(80) to 10080
