### ISSUE TITLE
"no service for this pod" is confusing

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1909]
![noxfory](https://cloud.githubusercontent.com/assets/29690/7326056/8d1dd096-ea90-11e4-8628-38c38d6a8425.png)

I think the use of "this" is confusing in the context shown. Your eye doesn't necessarily go halfway across the screen to see what "this" is attached to by a small line.

Having "There are currently no pods for this service." referring to the thing above (which is fairly clear) makes it really following to then have "There is no service for this pod." referring to the thing below.

Perhaps just "There is no service for the pod below." Or just not show a service box at all. Or group all un-serviced pods under a "bare pod" heading.

It's minor, just thought I'd mention it.

BTW, the context is that a build ran but for whatever reason didn't deploy. So the app service has no pod and the build pod has no service. It's not hard to get here.

**Comment by smarterclayton** [comment]
I don't think the grouping or the background is appropriate even for monopods, so we can probably deal with that in the redesign.

**Comment by spadgett** [comment]
@sg00dwin Something to look at as you work on overview designs.

**Comment by sg00dwin** [comment]
With the redesigned overview page, this issue has been addressed to better convey the connection between a service and associated pods; when a service has no pods,  and when their is no service for an pod.

![screen shot 2015-06-30 at 12 03 39 pm](https://cloud.githubusercontent.com/assets/1874151/8435835/d5130036-1f21-11e5-9564-406a2a8b6ae9.png)

**Comment by spadgett** [comment]
We could remove the message and dashed border. I'm worried the pod will look like it belongs to the service above it, however.

<img width="481" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/8533732/188fe2f6-2405-11e5-92f4-2efa3e5673ed.png">

Keeping the dashed border might help.

<img width="479" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/8533831/9853d20e-2405-11e5-8038-1e9f331b487b.png">

**Comment by smarterclayton** [comment]
Eventually we want to enable a service via a click - we'd want something for the affordabce for that.  I like the dashed.
