### ISSUE TITLE
v3.9.0 doesn't have Assets attached in it's tag

### ISSUE THREAD

**Issue by dipak-pawar** [openshift/origin#19101]
I cann't see any assets under `v3.1.9` tag. When do we expect release of `v3.1.9`?

**Comment by jwforres** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
What is 3.1.9?

**Comment by dipak-pawar** [comment]
@smarterclayton It's by mistake. I mean when do we expect final release of `v3.9.0`?
