### ISSUE TITLE
Q: Issue #281 from old repo "No route to host" due to endpoint removal.

### ISSUE THREAD

**Issue by jcias** [openshift/origin#19124]
On OpenShift Origin 1.5.1 I've encountered similar behavior to described in the [Issue 281](https://github.com/openshift/openshift-sdn/issues/281) form old [openshift/openshift-sdn](https://github.com/openshift/openshift-sdn) repo, that still has "Open" status while all development was moved here. Was this issue transferred here or maybe addressed anyhow?

**Comment by jwforres** [comment]
@openshift/networking

**Comment by jcias** [comment]
It looks like this was resolved actually somewhere between 1.5.1 and 1.7 (3.7) version as after we've upgraded to 3.7 we did not encounter such behavior any more. It appears this is a known bug which was described [here](https://access.redhat.com/solutions/3077711) and [here](https://bugzilla.redhat.com/show_bug.cgi?id=1462338), resolved by OpenShift version 3.5.5.31, most probably not resolved in upstream 1.5.
