### ISSUE TITLE
Connector on project overview page misaligned when text wraps

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#1912]
See screenshot. The connector for the service is in the wrong spot when text wraps.

![misaligned-connector](https://cloud.githubusercontent.com/assets/1167259/7327211/6207ba58-ea99-11e4-9840-2d9a739de1ad.png)

@sg00dwin @jwforres fyi

**Comment by jwforres** [comment]
This is most likely to happen at mobile resolution, but basically any time the service details wrap.

**Comment by spadgett** [comment]
Seems to be fixed by #1972. Closing.
