### ISSUE TITLE
v3.7.2:origin-node, docker-shim, checkpoint is not found issue forcing manual intervention to restart daemonset pods after reboot

### ISSUE THREAD

**Issue by mshutt** [openshift/origin#19138]
We are seeing issues with nodes after a reboot wherein the following log entries are seen on an origin-node:

```
Mar 28 15:11:26 [redacted].com origin-node[8316]: E0328 15:11:26.926022    8416 kuberuntime_manager.go:570] killPodWithSyncResult failed: failed to "KillPodSandbox" for "a39f4081-31f4-11e8-8260-9418827a0864" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"apiserver-66r8n_openshift-template-service-broker\" network: could not retrieve port mappings: checkpoint is not found."
Mar 28 15:11:26 [redacted].com origin-node[8316]: E0328 15:11:26.926038    8416 pod_workers.go:186] Error syncing pod a39f4081-31f4-11e8-8260-9418827a0864 ("apiserver-66r8n_openshift-template-service-broker(a39f4081-31f4-11e8-8260-9418827a0864)"), skipping: failed to "KillPodSandbox" for "a39f4081-31f4-11e8-8260-9418827a0864" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"apiserver-66r8n_openshift-template-service-broker\" network: could not retrieve port mappings: checkpoint is not found."
```
To actually clean this up, the following is run:

```
docker rm $(docker ps -qa --no-trunc --filter "status=exited")
```

##### Version

```
oc v3.7.2+5eda3fa-5
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://[redacted].com:443
openshift v3.7.2+5eda3fa-5
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce
Shut down a system running origin-node with active daemonset pods with the `restartPolicy: always`

##### Current Result
```
openshift-template-service-broker                    apiserver-66r8n                                            0/1       Error       0          1d 
```
##### Expected Result

DaemonSet containers with `restartPolicy: always` restart after a node is rebooted unexpectedly

##### Additional Information

This seems to have been fixed upstream and cherry picked to k8s 1.8, but unfortunately since we're running 3.7.2, this is not the case for us...

https://github.com/kubernetes/kubernetes/issues/55819
https://github.com/kubernetes/kubernetes/pull/55826

/label bug

**Comment by jwforres** [comment]
@openshift/sig-pod

**Comment by sjenning** [comment]
Sorry, we don't do backports of non-critical fixes in non-latest versions Origin.  Best way to have this fixed is to move up to 3.9 (latest).

**Comment by mshutt** [comment]
@sjenning thanks :)  At the time of this issue report, 3.9 was not GA :) 

Regards,
--Miranda

**Comment by sjenning** [comment]
Very true :)  Thanks for reporting!

**Comment by DanyC97** [comment]
@sjenning while i understand and not question RH backport policy, what should users who were on v3.7.0 and just migrated to v3.7.2 should do? 

Telling them to "run extra lap" (ie - v3.7. -> v3.8 -> v3.9) although they just tried to complete first lap surely doesn't work in a production environment.

I'm curious how you guys handle this issue in OCP? i suspect it has been cherry picked otherwise your paying customers will get very angry ....

**Comment by DanyC97** [comment]
@sjenning after more digging ..surprise, surprise ;) https://bugzilla.redhat.com/show_bug.cgi?id=1576777#c2 

A bit disappointed to see that such a nasty bug which seems is present even in 3.7.1 is not being considered "critical" for origin but is for OCP ...

**Comment by mshutt** [comment]
Yeah I mean I'm 3.9 in our lab but we can only move so fast.  I just had a fire drill with this when a user created cronjobs that didn't exit clean and the cronjob scheduler just kept creating pods ad infinitum.  I can't control how users define these things and the restartPolicy and such and if one goes awry, I just have to deal with nodes that have issues and report PLEG timeouts and bounce from Ready to NotReady and I have to come and drain, clean docker, restart origin-node, uncordon, etc... It's a real blast.
