### ISSUE TITLE
oc cluster up claims openshift/origin:v3.10 is unavailable

### ISSUE THREAD

**Issue by jmontleon** [openshift/origin#19140]
oc cluster up claims openshift/origin:v3.10 is unavailable

##### Version
oc v3.10.0-alpha.0+1691e4d-400
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.10.0-alpha.0+942dfa5-404
kubernetes v1.9.1+a0ce1bc657
##### Steps To Reproduce
```
$ oc cluster up --routing-suffix=172.18.0.1.nip.io --service-catalog=true 
error: FAIL
   Error: cannot create container using image openshift/origin:v3.10
   Caused By:
     Error: Error: No such image: openshift/origin:v3.10

$ docker pull openshift/origin:v3.10
Trying to pull repository registry.fedoraproject.org/openshift/origin ... 
Trying to pull repository docker.io/openshift/origin ... 
sha256:67157492f83ff99bfdb6ccbaf049d96de1ef3d1e007fd67db9e0eaa24ab6ecde: Pulling from docker.io/openshift/origin
Digest: sha256:67157492f83ff99bfdb6ccbaf049d96de1ef3d1e007fd67db9e0eaa24ab6ecde
Status: Image is up to date for docker.io/openshift/origin:v3.10
```

##### Current Result
Fails to run without --tag=latest

##### Expected Result
Should run correctly.

**Comment by mfojtik** [comment]
Tried on the latest HEAD, seems to be working fine:

```
~/.../openshift/origin → oc cluster up --routing-suffix=172.18.0.1.nip.io --service-catalog=true
Pulling image openshift/origin:v3.10
Pulled 2/4 layers, 51% complete
```

Can you try again?

**Comment by mfojtik** [comment]
It might be that it only tries to pull trough registry.fedoraproject.org/openshift/origin ? (haven't tried to have two registries configured). I will check the pulling code, but I believe we use the docker client directly so it should know how to pull even if it has 2 registries configured.

**Comment by jmontleon** [comment]
Not sure what changed, but this seems to be working with the latest client. Thanks!
