### ISSUE TITLE
Openshift Connect Local USB Device to POD

### ISSUE THREAD

**Issue by flipkill1985** [openshift/origin#19160]
Hello,

its a Question, not a bug. Is it possible to map a local USB Device to a POD?
and how is that possible?

best regards Jan

**Comment by jwforres** [comment]
@openshift/sig-storage

**Comment by gnufied** [comment]
there are couple of ways:

1. You can plug the USB device and mount it on the host and use the hostpath within a pod.
2. You can additionally use local volumes as documented - https://docs.openshift.com/container-platform/3.9/install_config/persistent_storage/persistent_storage_local.html

Closing this.

**Comment by flipkill1985** [comment]
Hello,
i try both Solutions but without success.
The USB did not work with that Solution. Any other Ideas?
best reagards Jan
