### ISSUE TITLE
openshift is permanently removing docker images from registry

### ISSUE THREAD

**Issue by nightman68** [openshift/origin#19178]
When I run the origin server permanently all docker images in my private registry are deleted. Is there any reason or this, can this behaviour be disabled?

Additionally the images for origin's web-console, deployer etc. permanently removed.

##### Version
CentOS-7-x86_64-DVD-1708 inside VirtualBox VM on MAC OS X

oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657

docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:09:15 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:13:03 2018
  OS/Arch:	linux/amd64
  Experimental:	false

##### Steps To Reproduce
1. Download a Docker image, don't deploy a container
2. Start openshift server

##### Current Result
After some time the download images from step 1. is away. The images are not deleted when a container is in place.

##### Expected Result
Existing images without a container in place are not deleted. Additionally the openshift containers are not deleted permanently. It make no sense that these containers are downloaded permanently!

**Comment by bparees** [comment]
> When I run the origin server permanently all docker images in my private registry are deleted.

what do you mean your "private registry"?  Do you mean your machine's local docker image storage?

> After some time the download images from step 1. is away. The images are not deleted when a container is in place.

i can't interpret this sentence.  "is away"?

> Existing images without a container in place are not deleted.  Additionally the openshift containers are not deleted permanently. It make no sense that these containers are downloaded permanently!

I'm really struggling to understand what you are seeing but it *sounds* like you are saying that some(but not all) local images that do not have containers associated with them, are being deleted.  The most likely cause of that would be imageGC which attempts to remove local images from the host node if there is filesystem pressure.

@sjenning can give you some tips on how to confirm if that is what is deleting your images, and how to configure its behavior.

**Comment by nightman68** [comment]
The private registry is the on my CentOS box, on the machine were origin is running.

> I'm really struggling to understand what you are seeing but it sounds like you are saying that some(but not all) local images that do not have containers associated with them, are being deleted.
> 
Sorry for my poor English but this is the behaviour.

> The most likely cause of that would be imageGC which attempts to remove local images from the host node if there is filesystem pressure.
>
Is the garbage collection performed by the origin server? I never have seen this on a box without a running origin server. On the server 12 GiB of free storage is available...

> @sjenning can give you some tips on how to confirm if that is what is deleting your images, and how to configure its behavior.
> 
Would be great!

I made another test on this. I removed all images from my registry and started the origin server again. It's downloading the required origin images. Then I started the deployment of a docker image from another VM (GitLab). I created a secret for this registry. The meta information was shown in the origin Web frontend but the deployment failed due to "unauthorised access"?! This is not understandable from my POV. I pulled the images in the origin VM and after that the deployment finished sucessfully. After the deployment except the origin pod image all other origin images are gone. This is a bit surprising.

**Comment by bparees** [comment]
> Is the garbage collection performed by the origin server? 

i believe it's performed on any origin node.


>  I removed all images from my registry 

You keep saying registry but i think you are referring to your machine's local docker image storage.  That's not the same thing as a registry.  If you're running "docker rmi" that's your local docker image storage.

> The meta information was shown in the origin Web frontend but the deployment failed due to "unauthorised access"?!

that would imply your secret for pulling the image is incorrect.

>  After the deployment except the origin pod image all other origin images are gone.

how are you checking for the presence/absence of these images?

**Comment by nightman68** [comment]
> You keep saying registry but i think you are referring to your machine's local docker image storage. That's not the same thing as a registry. If you're running "docker rmi" that's your local docker image storage.
> 
You're right, sorry.

 I tried again the last test after a VM restart. Here the content of my registry before I started the origin server:

``` 
[root@cloud ~]$ docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
registry.mac.pro/registry/test   5.2.2               f55974e82463        24 hours ago        1.44GB
openshift/origin-pod             v3.9.0              1b36bf755484        3 days ago          217MB
```

The content about 2 minutes after origin start:
```
[root@cloud ~]$ docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
registry.mac.pro/registry/test                      5.2.2               f55974e82463        24 hours ago        1.44GB
openshift/origin-web-console                        v3.9                60938911a1f9        3 days ago          485MB
openshift/origin-docker-registry                    v3.9.0              2663c9df9123        3 days ago          455MB
openshift/origin-pod                                v3.9.0              1b36bf755484        3 days ago          217MB
quay.io/external_storage/local-volume-provisioner   v1.0.1              af7214b5b9ae        8 months ago        40.5MB
```
Approximately 1 more minute later (my image is away):
```
[root@cloud ~]$ docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-web-console                        v3.9                60938911a1f9        3 days ago          485MB
openshift/origin-docker-registry                    v3.9.0              2663c9df9123        3 days ago          455MB
openshift/origin-pod                                v3.9.0              1b36bf755484        3 days ago          217MB
quay.io/external_storage/local-volume-provisioner   v1.0.1              af7214b5b9ae        8 months ago        40.5MB

[root@cloud ~]$ df -h
Filesystem                     Size  Used Avail Use% Mounted on
/dev/mapper/centos_cloud-root   72G   59G   13G  83% /
devtmpfs                       1.2G     0  1.2G   0% /dev
tmpfs                          1.2G     0  1.2G   0% /dev/shm
tmpfs                          1.2G  9.4M  1.2G   1% /run
tmpfs                          1.2G     0  1.2G   0% /sys/fs/cgroup
/dev/sda1                     1014M  207M  808M  21% /boot
```

After deployment initiation ("pulling image "openshift/origin-deployer:v3.9.0"):
```
[root@cloud ~]$ docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-web-console                        v3.9                60938911a1f9        3 days ago          485MB
openshift/origin-docker-registry                    v3.9.0              2663c9df9123        3 days ago          455MB
openshift/origin-deployer                           v3.9.0              378ccd170718        3 days ago          1.25GB
openshift/origin-pod                                v3.9.0              1b36bf755484        3 days ago          217MB
quay.io/external_storage/local-volume-provisioner   v1.0.1              af7214b5b9ae        8 months ago        40.5MB
```

After the "manual" pull of my images and the finished deployment. This time with an error - I changes the image):
```
[root@cloud ~]$ docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-deployer        v3.9.0              378ccd170718        3 days ago          1.25GB
openshift/origin-pod             v3.9.0              1b36bf755484        3 days ago          217MB
```

In the Events log I see this:
```
Time | Name | Kind | Severity | Reason | Message
-- | -- | -- | -- | -- | --
7:48:54 PM | csvn-2-9smnb | Pod | Warning | Failed Scheduling | 0/1 nodes are available: 1 NodeUnderDiskPressure.8 times in the last minute
7:47:51 PM | csvn-2 | Replication Controller | Normal | Successful Create | Created pod: csvn-2-9smnb
7:47:38 PM | csvn-2-vp55j | Pod | Warning | Back-off | Back-off restarting failed container8 times in the last 3 minutes
7:47:36 PM | csvn-2-vp55j | Pod | Normal | Started | Started container5 times in the last 3 minutes
7:47:36 PM | csvn-2-vp55j | Pod | Normal | Created | Created container5 times in the last 3 minutes
7:47:36 PM | csvn-2-vp55j | Pod | Normal | Pulled | Container image "registry.mac.pro/registry/csvn@sha256:dc9523495fdf331e2cb86db9b74116aaf9ce0740b650c75883efc76430a82291" already present on machine5 times in the last



Time | Name | Kind | Severity | Reason | Message
-- | -- | -- | -- | -- | --
7:48:54 PM | csvn-2-9smnb | Pod | Warning | Failed Scheduling | 0/1 nodes are available: 1 NodeUnderDiskPressure.8 times in the last minute
7:47:51 PM | csvn-2 | Replication Controller | Normal | Successful Create | Created pod: csvn-2-9smnb
7:47:38 PM | csvn-2-vp55j | Pod | Warning | Back-off | Back-off restarting failed container8 times in the last 3 minutes
7:47:36 PM | csvn-2-vp55j | Pod | Normal | Started | Started container5 times in the last 3 minutes
7:47:36 PM | csvn-2-vp55j | Pod | Normal | Created | Created container5 times in the last 3 minutes
7:47:36 PM | csvn-2-vp55j | Pod | Normal | Pulled | Container image "registry.mac.pro/registry/csvn@sha256:dc9523495fdf331e2cb86db9b74116aaf9ce0740b650c75883efc76430a82291" already present on machine5 times in the last
```

**Comment by nightman68** [comment]
Regarding the wrong secret: it's my ```.docker/config.json``` I'm using also for the "manual" pull which works...

**Comment by bparees** [comment]
Sounds like imageGC is what is removing your images to me, but again @sjenning should be able to help you confirm that.

**Comment by nightman68** [comment]
OK, let's see.

**Comment by sjenning** [comment]
Yes, looks like that is what is happening.  imageGC is very aggressive in the case that you hit a eviction disk limit in that _all_ images are GCed.

You can verify by looking in the node logs for "imageGCManager".

You should not use images that are only available locally.  Any image referenced in a pod should be able to be pulled from a registry.
