### ISSUE TITLE
oc cluster join fails with " Error: could not start OpenShift container "origin"

### ISSUE THREAD

**Issue by alnhk** [openshift/origin#19176]
Please advice resolution to scaleup openshift on oracle linux virtualized environment. Steps to reproduce:
**Version detail :** openshift v3.9.0+191fece

1. Ran below command for "oc cluster up ..." on master host
$oc cluster up --public-hostname xx.xx.xx.xx   --host-data-dir="/opt/openshift/openshift.local.volumes" --host-volumes-dir="/opt/openshift/openshift.local.config" --http-proxy='http://proxy:80' --https-proxy='http://proxy:80' --no-proxy='localhost,127.0.0.1,172.30.1.1,10.0.0.0/8'

**And it completed successfully**

2. on one node, attempted to run "oc cluster join..."
oc cluster join --use-existing-config --host-data-dir="/opt/openshift/openshift.local.volumes" --host-volumes-dir="/opt/openshift/openshift.local.config"  --secret="$(cat admin.kubeconfig)"   --public-hostname  xx.xx.xx.xx1
Pulling image openshift/origin:v3.9.0
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 78% complete
Pulled 3/4 layers, 87% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
Using Docker shared volumes for OpenShift volumes
Using   xx.xx.xx.xx1 as the server IP
-- Joining OpenShift cluster ... 
   Starting OpenShift Node using container 'origin'
**FAIL
   Error: could not start OpenShift container "origin"**
   Details:
     Last 10 lines of "origin" container log:
           --kubernetes='https://localhost:8443': removed in favor of --kubeconfig
           --latest-images=false: If true, attempt to use the latest images for the cluster instead of the latest release.
           --listen='https://0.0.0.0:8443': The address to listen for connections on (scheme://host:port).
           --network-plugin='': The network plugin to be called for configuring networking for pods.
           --recursive-resolv-conf='': An optional upstream resolv.conf that will override the DNS config.
           --volume-dir='openshift.local.volumes': The volume storage directory.
           --write-flags=false: When this is specified only the arguments necessary to start the Kubelet will be output.

     Use "openshift options" for a list of global command-line options (applies to all commands).

**Comment by mfojtik** [comment]
/cc @deads2k 

I believe that that `oc cluster join` is going away. It was broken before and there is no intention to fix or support it into the future.

**Comment by deads2k** [comment]
> I believe that that oc cluster join is going away. It was broken before and there is no intention to fix or support it into the future.

Yeah.  We actually did the deletion in 3.10.  The command was experimental.  If it's confusing, we can backport the delete I suppose.

**Comment by alnhk** [comment]
Thanks for that, i was told by zalenium team to try openshift which we can avoid minikube which is limited to "local". So I tried with this, hence this is confusing. 

Anyways, thanks for letting us know about this. I have already informed zalenium to update the doc...

**Comment by pearj** [comment]
Just for the record here @alnhk don't take this response to mean that OpenShift doesn't support clustering, quite the opposite. Instead you need to use the [Advanced installation](https://docs.openshift.org/latest/install_config/install/advanced_install.html) for more than 1 nodes in a cluster.
