### ISSUE TITLE
How to build ose image and oc client based source code?

### ISSUE THREAD

**Issue by cucushift** [openshift/origin#19177]
Hi all:
   I am a novice of openshift, it is very usefull and available, now i have a confusion when i use oc cluster up to deploy a all-in-one cluster, i want to try new functions about openshift,so i need very very new `ose images `and `oc client`, i did not find some docs about how to create them based source code.pls help me,thx.

**Comment by mfojtik** [comment]
@cucushift to build openshift locally, you can run `make`, then the binaries are in `_output` directory.
After that you can run `./hack/build-local-images.py` which should give you the current images.

Also I think we do publish `:latest` images now, so you probably don't need the second step.

**Comment by cucushift** [comment]
[this](https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-locally-on-your-host) solve my problem.
