### ISSUE TITLE
sandbox: rpc error: code = Unknown desc = rewrite resolv.conf failed for pod 

### ISSUE THREAD

**Issue by aland-zhang** [openshift/origin#19174]
cluster setup with containerized=true
ansible hosts :
containerized=true
After the installation is complete，
oc get pod
NAME                        READY     STATUS              RESTARTS   AGE
docker-registry-1-deploy    0/1       **ContainerCreating**   0          31m
registry-console-1-deploy   0/1       **ContainerCreating**   0          20m
router-1-deploy             0/1       **ContainerCreating**   0          31m
**oc describe pod router-1-deploy 
show errors:
 Warning  FailedCreatePodSandBox  31m                  kubelet, 10.10.21.192  Failed create pod sandbox: rpc error: code = Unknown desc = rewrite resolv.conf failed for pod "router-1-deploy": ResolvConfPath "/data/docker/containers/65c16b2ea0a2f00151a8a4260b8d6e1507bde1b920519a4f74687e2925ed190c/resolv.conf" does not exist**

Version
oc v3.9.0+191fece
openshift v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
oc get pod

##### Current Result
NAME                        READY     STATUS              RESTARTS   AGE
docker-registry-1-deploy    0/1       ContainerCreating   0          31m
registry-console-1-deploy   0/1       ContainerCreating   0          20m
router-1-deploy             0/1       ContainerCreating   0          31m
##### Expected Result
oc describe pod router-1-deploy 
##### Additional Information
 **Warning  FailedCreatePodSandBox  31m                  kubelet, 10.10.21.192  Failed create pod sandbox: rpc error: code = Unknown desc = rewrite resolv.conf failed for pod "router-1-deploy": ResolvConfPath "/data/docker/containers/65c16b2ea0a2f00151a8a4260b8d6e1507bde1b920519a4f74687e2925ed190c/resolv.conf" does not exist**

**Comment by vishnugan** [comment]
@aland-zhang does the issue got resolved? If yes, what was the resolution given?
I face the same issue. Node shows active, but none of the pod is getting deployed in that node.
