### ISSUE TITLE
Copy files to pod before starting pod

### ISSUE THREAD

**Issue by bigquant** [openshift/origin#19181]
Scenario: I want to run a script in openshift cluster:
- copy local files to the pod
- run the entrypoint
- copy the output files to local machine
- exit pod and release resources (GPUs/CPU/Mem)

Is there a good solution for that: copy the files to pod before the entrypoint run and copy files after it stops.

**Comment by mfojtik** [comment]
@bparees this looks like binary build to me?

/sig devexp

**Comment by bparees** [comment]
@mfojtik I don't think so.  binary build would mean pushing the new image somewhere, then pulling it back and still solving the problem of how to extract the files to your local machine.  It really only solves the first 2 steps (copy local files to the pod, run the entrypoint).

**Comment by bparees** [comment]
@bigquant for now i think you'd have to manually orchestrate this:

1) define your image to have a long running entrypoint (e.g. sleep 600, if 10 mins is long enough for you to do what you need to do)
2) run the pod
3) use oc rsync to copy files into the pod
4) use oc exec to run your main script to operate on the files
5) use oc rsync to copy the result files out of the pod
6) (optionally) delete the pod (or just wait for the sleep to timeout and terminate it)
