### ISSUE TITLE
Support -o json in oc version

### ISSUE THREAD

**Issue by gastaldi** [openshift/origin#19182]
It would be nice if the `oc version` output were available as a JSON (by supporting -o json), as this could be used in applications that require knowing the target openshift version

**Comment by mfojtik** [comment]
@soltysh do you know if something was proposed upstream to support this? sounds reasonable request to me.

**Comment by soltysh** [comment]
Nope, I doubt there's any value in returning plain json. If user needs to, he can easily request that version directly accessing `/version` or `/version/openshift` which will return json output the reporter asks. The first endpoint returns k8s version, the latter openshift.
