### ISSUE TITLE
Allow template service broker to view templates from all namespaces

### ISSUE THREAD

**Issue by rthallisey** [openshift/origin#19201]
If I create a namespaces for a user, I would like for any template they create to be viewed in the service-catalog.  Instead of adding this new namespaces to the template broker config, I'd like the template-service-broker to look for templates for all namespaces.

**Comment by rthallisey** [comment]
Makes sense Ben. This configuration is permissive so I would expect the user to be cluster-admin or they would get a permission error.

**Comment by bparees** [comment]
Even displaying all those template offerings in the service catalog is going to be problematic, if most users can't provision most of them.

**Comment by rthallisey** [comment]
@bparees do you have any docs you can point me to on how to build and test changes?

**Comment by bparees** [comment]
@rthallisey follow the normal openshift build processes to build new images which would include a new TSB image and then deploy it (openshift/origin-template-service-broker:latest)

templates/resources to install the TSB are here:
https://github.com/openshift/origin/tree/master/install/templateservicebroker

Alternatively, you can just do a make build to produce a new template-service-broker binary and then run `hack/build-local-images.sh openshift/origin-template-service-broker` which will layer the new TSB binary into the existing TSB image (and then deploy that new image).

**Comment by jwmatthews** [comment]
I spoke to @rthallisey about this request.

For background, this was an RFE that was discussed from work on KubeVirt.  
We need to get more info on the requesting UseCase so we can understand what is prompting the need to read templates from all namespaces.

The concern, as Ben pointed out, is that items published to the Service Catalog are intended to be consumable by all users of the cluster, while a cluster-admin user may have sufficient access rights the other users on the cluster are likely to not be able to access all namespaces.

@rthallisey will attempt to get more info on the requesting UseCase before we proceed further.
