### ISSUE TITLE
I experienced many errors on node  when created apps via s2i

### ISSUE THREAD

**Issue by openstacks** [openshift/origin#19206]
##### Version
# oc version
oc v1.3.2
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Post 60 s2i requests concurrently
2. Check the log on node

##### Current Result
1 deploys pod is pending status
2 Many error are saw in log file on node。

##### Expected Result
all 60 pods should be created successfully.

##### Additional Information
logs

   Apr 03 17:40:35 node atomic-openshift-node[29323]: E0403 17:40:35.241287   29323 pod_workers.go:182] Error syncing pod d17547e1-371f-11e8-896c-005056aaafec ("pt-app-source2301-1-build_svt(d17547e1-371f-11e8-896c-005056aaafec)"), skipping: failed to "KillPodSandbox" for "d17547e1-371f-11e8-896c-005056aaafec" with KillPodSandboxError: "rpc error: code = 4 desc = context deadline exceeded"

Apr 03 17:50:55 node atomic-openshift-node[29323]: E0403 17:50:55.818021   29323 remote_runtime.go:86] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod "pt-app-source453-1-build_svt" network: CNI request failed with status 400: 'failed to run IPAM for c6c99b558e87f063d26edf50bfa86e58d900d0c35a7e2d6423b2e8298df31b07: failed to run CNI IPAM ADD: no IP addresses available in network: openshift-sdn

Apr  3 16:03:23 node atomic-openshift-node: E0403 16:03:23.257126   29323 remote_runtime.go:109] StopPodSandbox "24c40934c684755104d5b2373be1d821a452cc121228f0763011d384027e973a" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "pt-app-source2002-1-build_perftest" network: CNI failed to retrieve network namespace path: Error: No such container: 24c40934c684755104d5b2373be1d821a452cc121228f0763011d384027e973a
Apr  3 16:03:23 phynode5 atomic-openshift-node: E0403 16:03:23.257169   29323 kuberuntime_gc.go:138] Failed to stop sandbox 

Orphaned pod "1c8f3db8-f133-11e7-aa9a-005056aaafec" found, but volume paths are still present on disk

  Apr 03 17:44:02 node atomic-openshift-node[29323]: W0403 17:44:02.833512   29323 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "pt-app-source653-1-build_svt": Unexpected command output nsenter: cannot open : No such file or directory

  Apr 03 17:53:12 node atomic-openshift-node[29323]: W0403 17:53:12.059829   29323 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "pt-app-source1651-1-deploy_svt": Unexpected command output nsenter: cannot open : No such file or directory

Apr  3 16:03:23 node atomic-openshift-node: E0403 16:03:23.267928   29323 remote_runtime.go:109] StopPodSandbox "252f20cd1303a21ea8ddfa20e935154d125aabf5e104b909b270b904ca76b35c" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "logging-fluentd-1k261_logging" network: CNI failed to retrieve network namespace path: Error: No such container: 252f20cd1303a21ea8ddfa20e935154d125aabf5e104b909b270b904ca76b35c

Apr  3 16:03:23 node atomic-openshift-node: E0403 16:03:23.267956   29323 kuberuntime_gc.go:138] Failed to stop sandbox "252f20cd1303a21ea8ddfa20e935154d125aabf5e104b909b270b904ca76b35c" before removing: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "logging-fluentd-1k261_logging" network: CNI failed to retrieve network namespace path: Error: No such container: 252f20cd1303a21ea8ddfa20e935154d125aabf5e104b909b270b904ca76b35c

{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.

Apr  3 18:18:28 node atomic-openshift-node: E0403 18:18:28.108814   29323 proxier.go:1331] Failed to execute iptables-restore: exit status 4 (Another app is currently holding the xtables lock. Perhaps you want to use the -w option?

**Comment by sjenning** [comment]
Origin v1.3 is _super_ old.  Please, try upgrading to 3.9.
