### ISSUE TITLE
multicast test flake

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#19218]
eg, https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/test_branch_origin_extended_conformance_gce/2788/, https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/test_branch_origin_extended_conformance_gce/2764/

    [Area:Networking] multicast when using one of the plugins 'redhat/openshift-ovs-multitenant, redhat/openshift-ovs-networkpolicy' should allow multicast traffic in namespaces where it is enabled [Suite:openshift/conformance/parallel]
    ...
    /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/networking/multicast.go:45
    Expected success, but got an error:
        <*errors.errorString | 0xc4208a8330>: {
            s: "pod 1 failed to send multicast to pod 2",
        }
        pod 1 failed to send multicast to pod 2
    /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/networking/multicast.go:47

This seems to happen sporadically. Not sure if it's easily reproducible outside of CI yet. We may need to add some more debugging.

**Comment by danwinship** [comment]
It might just be random UDP packet loss too. Maybe instead of sending a single multicast packet, we should send multiple packets and consider the test to have passed as long as any of them made it through.

**Comment by sdodson** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/9382/pull-ci-openshift-openshift-ansible-e2e-gcp-crio/9/
