### ISSUE TITLE
setting kubeconfig causes oc cluster up to die

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#19230]
If you set KUBECONFIG and then run oc cluster, things go nuts

```
(12:44:48 PM) pmorie__: export KUBECONFIG=<path to your dir>/openshift.local.clusterup/kube-apiserver/admin.kubeconfig
(12:44:54 PM) pmorie__: blast openshift.local.*
(12:44:58 PM) pmorie__: and then do oc cluster up
```

/assign

**Comment by pmorie** [comment]
This is only an issue if `KUBECONFIG` is inside a directory that `run_self_hosted.go#BuildConfig` tests for existence, but was quite confusing to me.
