### ISSUE TITLE
image_ecosystem extended test timeout

### ISSUE THREAD

**Issue by wozniakjan** [openshift/origin#19241]
image_ecosystem extended test has failed twice in past two days with the same error

```
[image_ecosystem][Slow] openshift images should be SCL enabled
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/scl.go:122
  
  /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/scl.go:126
    using the SCL in s2i images
    /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/scl.go:64
      "centos/ruby-22-centos7" should be SCL enabled [Suite:openshift] [It]
      /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/scl.go:65

      Expected error:
          <*errors.errorString | 0xc4203520d0>: {
              s: "timed out waiting for the condition",
          }
          timed out waiting for the condition
      not to have occurred

      /tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/image_ecosystem/scl.go:95
```
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/438
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/439

cc: @openshift/sig-developer-experience

**Comment by wozniakjan** [comment]
@bparees it looks like it is timing out obtaining logs from one of the pods
https://github.com/openshift/origin/blob/5e9bbe1dd90cc6c9e79f083daf70d77d388f9fd6/test/extended/image_ecosystem/scl.go#L84-L95

but correlating similar parts across various test runs, it looks like past two days, aws machines that ran the tests were extra slow in those parts of tests. Last previous successful command took 4x the normal time

```
Apr  4 11:20:21.359: INFO: namespace extended-test-jenkins-plugin-nz85c-tgmrl deletion completed in 6.149620191s
```
vs
```
Apr  5 11:55:39.054: INFO: namespace extended-test-jenkins-plugin-rtd6f-2j8h7 deletion completed in 24.160489471s
Apr  6 11:46:48.568: INFO: namespace extended-test-s2i-ruby-6snsr-5pxfr deletion completed in 24.254050982s
```

And I will run the tests locally asap

**Comment by bparees** [comment]
@wozniakjan check out my PR here: https://github.com/openshift/origin/pull/19243

i think it's actually completing quickly and we weren't checking to see if that's what the error meant.
