### ISSUE TITLE
Can we use Default StorageClasses for NFS

### ISSUE THREAD

**Issue by gkarthiks** [openshift/origin#19245]
Its more of a question and suggestion. To use the NFS as PVs, don't we need to specify any StorageClasses?
When I execute **oc get**  in my company's cluster, I get the following.
> error: Required resource not specified.

If I execute **kubectl get** I get the below, guess this is more clearer.

> *storageclasses (aka 'sc')error: Required resource not specified.

##### Version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server <internal>
openshift v3.7.9
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. Login to OC with token from console.
2. Run `oc get` or `kubectl get` ( with kubectl config pointing to the OC Cluster).

##### Current Result
error: Required resource not specified.

##### Expected Result
If no a default Storage class can be used for PVs provisioned from NFS then the result of get command should give the following.
> No Errors / Default StorageClasses are in Use.

**Comment by gnufied** [comment]
We do not do dynamic provisioning of NFS volumes out of box and that is why there is no default storageclasses for it.

If you are interested in nfs dynamic provisioner you may be interested in https://github.com/kubernetes-incubator/external-storage/tree/master/nfs
