### ISSUE TITLE
Cannot use ingressIPNetworkCIDR with vsphere cloud provider

### ISSUE THREAD

**Issue by phemmer** [openshift/origin#19252]
When using the vSphere cloud provider, OpenShift refuses to let you assign a value to the `networkConfig.ingressIPNetworkCIDR` config parameter.

I suspect this is just a sanity check to prevent people from using the automatic external IP address provisioning when on a cloud provider where this is done for them. However the vSphere cloud provider does not have this functionality. In my case I am attempting to have OpenShift allocate IPs from a subnet which our external firewalls perform DNAT on.

##### Version
```
openshift v3.9.0-alpha.4+881f1dd-440
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.8
```

##### Steps To Reproduce
1. Use the vmware cloud provider
2. Set `networkConfig.ingressIPNetworkCIDR` in the `master-config.yaml`.

##### Current Result
```
Invalid MasterConfig /etc/origin/master/master-config.yaml
networkConfig.ingressIPNetworkCIDR[0]: Invalid value: "10.128.69.0/24": should not be provided when a cloud-provider is enabled
```

##### Expected Result
success

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by phemmer** [comment]
I've found a really evil hack to get around the issue:

```
osm_controller_args={'cloud-provider':['','vsphere'],'cloud-config':['/etc/origin/cloudprovider/vsphere.conf']}
osm_api_server_args={'cloud-provider':['','vsphere'],'cloud-config':['/etc/origin/cloudprovider/vsphere.conf']}
```
By adding the above to the inventory for the openshift-ansible repo, it makes it so that the first cloud provider is an empty string, which tricks the verification check into thinking there's no cloud provider in use. However when doing things which actually integrate with vsphere (storage volume management), it ignores the empty string provider, and skips to the vsphere provider which works fine.

**Comment by phemmer** [comment]
Nevermind, I thought that solution worked, but I just built a new cluster and it does not (maybe last time I was doing it on a cluster that was already built). The manual setting of `osm_controller_args` and `osm_api_server_args` is getting overridden by:
https://github.com/openshift/openshift-ansible/blob/release-3.9/roles/openshift_master/tasks/update-vsphere.yml#L9-L11

**Comment by snuxoll** [comment]
/remove-lifecycle rotten

Just got hit with this myself

**Comment by Reamer** [comment]
/reopen
/remove-lifecycle rotten
Any workaround known? I have also problems to add [EgressIPs](https://docs.okd.io/latest/admin_guide/managing_networking.html#enabling-static-ips-for-external-project-traffic)
