### ISSUE TITLE
Grafana example is broken

### ISSUE THREAD

**Issue by timbrd** [openshift/origin#19254]
I have tried to roll out grafana onto my openshift cluster by using the example of this repo. Unfortunately it is not possible to create the stateful set:

```
Failed to create new replica set "grafana-1844991881": replicasets.extensions "grafana-1844991881" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion extensions/v1beta1 Kind Deployment: allowed by openshift authorizer, no matches for extensions/, Kind=Deployment
```

There is another error, which might be related to the stateful set error though:

```
Error creating: No API token found for service account "grafana", retry after the token is automatically created and added to the service account
```

##### Version
```
oc v3.7.23
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ocp.my-cluster.com:8443
openshift v3.7.23
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce
1. Follow the instructions of the grafana example:
`./setup-grafana.sh -n my-datasource -a -e`

**Comment by pgier** [comment]
I wasn't able to reproduce this using minishift with openshift v3.7.2.  The issue looks similar to #18784
