### ISSUE TITLE
error: build error: Failed to push image: Get http://172.30.1.1:5000/v2/:  net/http: request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by kkzz8888** [openshift/origin#19267]
Running the latest version of docker for Mac: 18.03.0-ce-mac60
Trying to deploy several example images in openshift, and always getting the following errors:

For example for wildly I am using the sample repository:

......
[INFO] Webapp assembled in [23 msecs]
--
  | [INFO] Building war: /opt/app-root/src/target/ROOT.war
  | [INFO] ------------------------------------------------------------------------
  | [INFO] BUILD SUCCESS
  | [INFO] ------------------------------------------------------------------------
  | [INFO] Total time: 20.969 s
  | [INFO] Finished at: 2018-04-09T01:26:11+00:00
  | [INFO] Final Memory: 14M/134M
  | [INFO] ------------------------------------------------------------------------
  | Moving built war files into /wildfly/standalone/deployments for later deployment...
  | Moving all war artifacts from /opt/app-root/src/target directory into /wildfly/standalone/deployments for later deployment...
  | '/opt/app-root/src/target/ROOT.war' -> '/wildfly/standalone/deployments/ROOT.war'
  | Moving all ear artifacts from /opt/app-root/src/target directory into /wildfly/standalone/deployments for later deployment...
  | Moving all rar artifacts from /opt/app-root/src/target directory into /wildfly/standalone/deployments for later deployment...
  | Moving all jar artifacts from /opt/app-root/src/target directory into /wildfly/standalone/deployments for later deployment...
  | ...done
  |  
  | Pushing image 172.30.1.1:5000/test/openshift-jee-sample:latest ...
  | Registry server Address:
  | Registry server User Name: serviceaccount
  | Registry server Email: serviceaccount@example.org
  | Registry server Password: <<non-empty>>
  ******| error: build error: Failed to push image: Get http://172.30.1.1:5000/v2/:  net/http: request canceled (Client.Timeout exceeded while awaiting headers)******

##### Version

oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. oc cluster up
2. from the console deploy wildly (or nginx) using sample repository

##### Current Result
| Pushing image 172.30.1.1:5000/test/openshift-jee-sample:latest ... failed with error
##### Expected Result
should succeed so that the image can be deployed. 
[ocgetall.txt](https://github.com/openshift/origin/files/1888222/ocgetall.txt)

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by kkzz8888** [comment]
[ocadmdignostics.txt](https://github.com/openshift/origin/files/1888239/ocadmdignostics.txt)

**Comment by kkzz8888** [comment]
I log in as system:admin to deploy, to clarify.

**Comment by naveenmereddi** [comment]
In a similar situation. Would love to provide any diagnostic information if needed.

**Comment by lucax88x** [comment]
same.

**Comment by lucax88x** [comment]
I resolved mine.. I was pushing to local docker instead of the openshift one.

using eval $(minishift docker-env)

**Comment by jwforres** [comment]
@mfojtik sounds like this issue stems from folks using docker for mac

**Comment by paivaric** [comment]
Any fix or workaround for this?

**Comment by mike-newman** [comment]
'error: build error: Failed to push image: Get http://172.30.1.1:5000/v2/:  net/http: request canceled (Client.Timeout exceeded while awaiting headers)
'

Having the same issue on Mac.

**Comment by bushidocodes** [comment]
I am also having this issue on Docker for Mac. I'm pretty sure that [this issue is the culprit.](https://github.com/openshift/origin/issues/18596)

**Comment by benweizhu** [comment]
What? just close?
