### ISSUE TITLE
oc cluster up generates a JSON file for openshift.local.clusterup/openshift-apiserver/master-config.yaml

### ISSUE THREAD

**Issue by djwhatle** [openshift/origin#19283]
##### Issue
`oc cluster up` generates a JSON file for `openshift.local.clusterup/openshift-apiserver/master-config.yaml`

##### Version
openshift v3.10.0-alpha.0+e0b02fb-617

##### Steps To Reproduce
1. Run oc cluster up
2. `openshift.local.clusterup/openshift-apiserver/master-config.yaml` will be formatted as JSON instead of YAML

**Comment by deads2k** [comment]
@liggitt I thought json was valid yaml.  Is it not?

**Comment by deads2k** [comment]
> @liggitt I thought json was valid yaml. Is it not?

Though I suppose I can admit that even if it is, most people would expect the "normal" yaml file.

**Comment by liggitt** [comment]
it is... but is going to be fairly unexpected for people
