### ISSUE TITLE
RBAC diagnostics output is not useful under cluster role aggregation

### ISSUE THREAD

**Issue by enj** [openshift/origin#19289]
`oc adm diagnostics` is clearly based off of the "default" rules of the bootstrap cluster roles.  However, since we aggregate into admin, edit and view, there are no "default" rules for these cluster roles anymore.  Thus the command thinks every rule is "new", making the diagnostic useless.

See output in #19163

@openshift/sig-security 

@php-coder @adelton Either of you have cycles to pick this up?  We can discuss specifics on IRC.

**Comment by enj** [comment]
cc @juanvallejo @sosiouxme

**Comment by nak3** [comment]
`oc adm diagnostics` was removed by https://github.com/openshift/origin/pull/20814 I think this issue should be closed.
