### ISSUE TITLE
extended tests: yum could not contact any CDS load balancers

### ISSUE THREAD

**Issue by wozniakjan** [openshift/origin#19293]
Lot of extended tests failed today with:

```
TASK [openshift_node : Install GlusterFS storage plugin dependencies] **********
task path: /usr/share/ansible/openshift-ansible/roles/openshift_node/tasks/storage_plugins/glusterfs.yml:2
FAILED - RETRYING: Install GlusterFS storage plugin dependencies (2 retries left).
FAILED - RETRYING: Install GlusterFS storage plugin dependencies (1 retries left).
fatal: [localhost]: FAILED! => {
    "attempts": 2, 
    "changed": false, 
    "generated_timestamp": "2018-04-10 11:00:03.313020", 
    "msg": "Failure talking to yum: Could not contact any CDS load balancers: rhui2-cds01.us-east-1.aws.ce.redhat.com, rhui2-cds02.us-east-1.aws.ce.redhat.com."
}
```

- https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/430/consoleFull#128639248958b6e51eb7608a5981914356
- https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/443/consoleFull#-149189893258b6e51eb7608a5981914356
- https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_registry/173/consoleFull#-96353014258b6e51eb7608a5981914356

cc: @openshift/sig-developer-experience

**Comment by stevekuznetsov** [comment]
/shrug

Not something we can really do anything about
/close

**Comment by gabemontero** [comment]
Saw of this in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins-client-plugin/138/test_pull_request_jenkins_client_plugin/81/ as well

Whatever this red hat CDS stuff is, it has spotty availability today.

**Comment by philipakash** [comment]
We are seeing lose of internet connectivity due to crashing open vswitch BR0 network interface during the deployment. We have seen the same error during the advance installation - openshift 3.7
@wozniakjan @gabemontero 
Not sure if this is related
