### ISSUE TITLE
API server does not start with "tls: DialWithDialer timed out" on arm64

### ISSUE THREAD

**Issue by tobru** [openshift/origin#19290]
Starting the OpenShift API server on an arm64 board leads to an error `F0407 21:12:11.723006 28502 start_api.go:67] tls: DialWithDialer timed out` and the API stops.

##### Version

```
$ openshift version
openshift v3.7.1+c2ce2c0-1
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8
```

##### Steps To Reproduce
See the following Gist for a full log: https://gist.github.com/tobru/a0595aace60410933a3a416a23f96ae1

##### Current Result

```
$ openshift start master api --config=etc/openshift/master/master-config.yaml
[...]
F0407 21:12:11.723006 28502 start_api.go:67] tls: DialWithDialer timed out
```

##### Expected Result

OpenShift API server starting without the `tls: DialWithDialer timed out` error.

##### Additional Information

See the Gist, it contains all commands used and log output. And: Kubernetes 1.7 runs on this board without issues (bootstrapped using `kubeadm`).

**Comment by tobru** [comment]
Tried it again with a 3.9 build (see #19236) but it behaves exactly like 3.7.

```
$ openshift version
openshift v3.9.0+191fece-dirty
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16
```

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by tobru** [comment]
Is there any chance that someone from @openshift/sig-master could have a look into this? Would be very lovely to get OpenShift running on ARM boards, just for demo purposes (conferences, Meetups, techtalks, ...)
