### ISSUE TITLE
10 of the past 10 GCE jobs failing on yum maybe?

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#19295]
Looking at the first ten jobs on  https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_extended_conformance_gce, they are all failed and they all say something like

```
"https://cds.rhel.updates.googlecloud.com/pulp/repos/content/dist/rhel/rhui/server/7/7Server/x86_64/os/libnetfilter_cthelper-1.0.0-9.el7.x86_64.rpm: [Errno 14] curl#6 - \"Could not resolve host: cds.rhel.updates.googlecloud.com; Name or service not known\"\nTrying other mirror.\nhttps://cds.rhel.updates.googlecloud.com/pulp/repos/content/dist/rhel/rhui/server/7/7Server/x86_64/os/conntrack-tools-1.4.4-3.el7_3.x86_64.rpm: [Errno 14] curl#6 - \"Could not resolve host: 
```
in the log

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19247/test_pull_request_origin_extended_conformance_gce/18863/

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19292/test_pull_request_origin_extended_conformance_gce/18862/

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19063/test_pull_request_origin_extended_conformance_gce/18861/

for reference.  Is this a thing we control or are we just screwed?

/assign @sdodson 
/assign @stevekuznetsov

**Comment by sdodson** [comment]
dnsmasq is failing to start likely due to dbus problems in this bug https://bugzilla.redhat.com/show_bug.cgi?id=1550582


```
-- Logs begin at Tue 2018-04-10 08:49:49 UTC, end at Tue 2018-04-10 08:57:08 UTC. --
Apr 10 08:54:10 ci-prtest-5a37c28-18857-build-image-instance systemd[1]: Started DNS caching server..
Apr 10 08:54:10 ci-prtest-5a37c28-18857-build-image-instance systemd[1]: Starting DNS caching server....
Apr 10 08:54:10 ci-prtest-5a37c28-18857-build-image-instance dnsmasq[3849]: dnsmasq: DBus error: Connection ":1.27" is not allowed to own the service "uk.org.thekelleys.dnsmasq" due to security policies in the configuration file
Apr 10 08:54:10 ci-prtest-5a37c28-18857-build-image-instance systemd[1]: dnsmasq.service: main process exited, code=exited, status=5/NOTINSTALLED
Apr 10 08:54:10 ci-prtest-5a37c28-18857-build-image-instance systemd[1]: Unit dnsmasq.service entered failed state.
```

@cgwalters @michaelgugino what were the paths that led to this failing? I thought this only happened when dbus was upgraded across the rebase boundary?

@stevekuznetsov does that happen in these jobs?

**Comment by michaelgugino** [comment]
This is caused by having dbus from 7.4, enabling 7.5, and installing dnsmasq.

If the base system is updated to 7.5 first (using yum update), this won't be an issue.

**Comment by stevekuznetsov** [comment]
We haven't touched the base AMI since March 8th

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-ansible/pull/7878 fixed this
