### ISSUE TITLE
Implementation of a status viewer for Builds.

### ISSUE THREAD

**Issue by droslean** [openshift/origin#19297]
### Implementation of a status viewer for Builds.

It would be very useful if openshift will implement a status viewer also for builds.
The "rollout" commands can apply for builds, and make all the script more stable. 
Right now we are trying to use some "hacks" in order to wait for a build to finish or get the history or cancel the build etc....

**Comment by bparees** [comment]
> @bparees I guess it is better to add the same functionality of "rollout" command for the builds as well.

unfortunately the deployment behavior and build behavior are not the same, hence we cannot simply create the equivalent command.  You do not have queued deployments and you don't have parallel deployments.  Hence my questions about what you'd want reported by such a command.  

(And also what behavior you'd want when waiting...wait for the current build to finish?  wait for the current newest build in the queue to run+finish?)

**Comment by droslean** [comment]
For example,  waiting for some second before getting the logs of a build, and some other parsing hacks in order to find out what happened to the build and so on. Of course, the build has different behavior and that's why it has to be developed from the beginning I guess. 
The question is if we will have benefits of it.

**Comment by kargakis** [comment]
@bparees, chatted with @droslean, he does not run parallel builds and needs to wait for build completion and act based on the build result. So `rollout status build/foo-1` or even `rollout status bc/foo` / `rollout status bc/foo --revision=1` could work for him.

**Comment by bparees** [comment]
@kargakis thanks, so the request is "a CLI way to wait for a specific build to complete, and report whether that build succeeded or failed"

**Comment by kargakis** [comment]
Exactly.

**Comment by bparees** [comment]
trello'd: https://trello.com/c/ySo00Lz6
