### ISSUE TITLE
timeout tearing down namespaces in extended tests

### ISSUE THREAD

**Issue by bparees** [openshift/origin#19322]
Starting to see this semi frequently, did the rebase impact namespace teardown time?

```
Apr 11 17:35:40.242: Couldn't delete ns: "extended-test-cli-build-run-policy-plqzv-pck5n": namespace extended-test-cli-build-run-policy-plqzv-pck5n was not deleted with limit: timed out waiting for the condition, pods remaining: 1 (&errors.errorString{s:"namespace extended-test-cli-build-run-policy-plqzv-pck5n was not deleted with limit: timed out waiting for the condition, pods remaining: 1"})
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_builds/1318/consoleFull

**Comment by liggitt** [comment]
Not that I was aware of. Looks like a stuck pod more than something specific to namespace deletion. 

None of the e2e tests failed with namespace deletion timeouts, though I don't know if they exercise stuck pod scenarios. 

cc @sjenning
