### ISSUE TITLE
single node cluster - unable to reach outside network

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [openshift/origin#19342]
[provide a description of the issue]
Unable to reach outside world from inside the pod.

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v3.9.0+191fece

##### Steps To Reproduce

Bring up single node cluster using  "oc cluster up --service-catalog=true"

go to any pod and ping.
ping resolves but no response.
```
# oc rsh po/webconsole-7dfbffd44d-l87c5
sh-4.2$ 
sh-4.2$ ping google.com 
PING google.com (74.125.24.100) 56(84) bytes of data.

```

##### Current Result
ping resolves but no response.

##### Expected Result
ping should work.

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

oc adm output: https://paste.fedoraproject.org/paste/Sx~87vGRpVI65DB0byLaCw

**Comment by jwforres** [comment]
What system are you running oc cluster up on? Fedora / Mac?
