### ISSUE TITLE
Post-rebase to 3.10, 3 failing conformance tests

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#19357]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_k8s/426/#showFailuresLink

Looks like its expecting to proxy logs, which we disable for security reasons (shouldn't be conformance).  The other two look weird, not sure why they are failing (maybe same thing, or firewall rules).

@liggitt

**Comment by liggitt** [comment]
The only thing I know of that changed in 1.10 was *removal* of two tests:

https://github.com/kubernetes/kubernetes/commit/7b4722964d21c994e0fdf36c0d7f5b0dc703a9c2#diff-178a0a673bda44ea7a86bd94070df78c

**Comment by liggitt** [comment]
It looks like you're running pre-rebase tests against a rebase binary

**Comment by smarterclayton** [comment]
Sigh.  https://github.com/openshift/origin/pull/19381

**Comment by smarterclayton** [comment]
Switched 3.9 to run it, next build in https://openshift-gce-devel.appspot.com/builds/origin-ci-test/logs/test_branch_origin_extended_conformance_k8s_39/ will contain the 1.9 conformance tests.

**Comment by smarterclayton** [comment]
Pushed a commit to release-3.9 to test (it doesn't have a branch job)

**Comment by jwforres** [comment]
Based on discussion im assuming this is resolved, closing.
