### ISSUE TITLE
Unable to deploy MariaDB

### ISSUE THREAD

**Issue by gkarthiks** [openshift/origin#19353]
I am following the (instructions here)[https://docs.openshift.com/container-platform/3.3/using_images/db_images/mariadb.html] for the deployment of MariaDB in our dev cluster. But the deployment shows success in the terminal and shows `Failed` status in the `console`.

##### Expected Result
Should deploy the Maria DB

**Comment by gkarthiks** [comment]
Any help is much appreciated!

**Comment by jwforres** [comment]
Your deployer service account does not appear to have the correct permissions in the project by default. If you check the role bindings in your project, there should be a role binding that has the deployer service account getting the system:deployer cluster role. Does that role binding exist? 

How was this cluster installed? Are you overriding the default project template in any way?

@openshift/sig-master

**Comment by gkarthiks** [comment]
@jwforres  I guess you are right. Let me try that and get back.
