### ISSUE TITLE
oc client: allow --no-o, --no-g and --omit-dir-times  arguments when running "oc rsync"

### ISSUE THREAD

**Issue by adietish** [openshift/origin#19365]
In https://issues.jboss.org/browse/JBIDE-25700 we're trying to "oc rsync" a local folder with java classes to a pod. The specificity of our use case is that the pod is running an exploded spring-boot application (that's running on a fabric8/s2i-java docker image). The destination path in the pod is at /deployment/BOOT-INF/classes. 
Unfortunately when running "oc rsync" to rsync a hierarchy of local folders to a destination folder in the pod rsync tries to change group ownership to these folders and fails because the rsync process in the pod lacks the permissions to do so:

```
oc rsync --token=<TOKEN> --server=<SERVER> --exclude=.git --no-perms=true --insecure-skip-tls-verify=true <LOCAL PATH> <POD-ID:POD_PATH>
```
results in:
```
rsync: chgrp "/deployments/BOOT-INF/classes/org" failed: Operation not permitted (1)
``` 
If we now try to add --no-o and --no-g options to "oc rsync" oc will quit with an error:
```
oc rsync --token=<TOKEN> --server=<SERVER> --insecure-skip-tls-verify=true --exclude=.git --no-perms=true --no-o --no-g <LOCAL PATH> <POD-ID:POD_PATH>
```
```
Error: unknown flag: --no-o

Usage:
  oc rsync SOURCE DESTINATION [options]

Examples:
  # Synchronize a local directory with a pod directory
  oc rsync ./local/dir/ POD:/remote/dir
  
  # Synchronize a pod directory with a local directory
  oc rsync POD:/remote/dir/ ./local/dir

Options:
  -c, --container='': Container within the pod
      --delete=false: If true, delete files not present in source
      --exclude=[]: If true, exclude files matching specified pattern
      --include=[]: If true, include files matching specified pattern
      --no-perms=false: If true, do not transfer permissions
      --progress=false: If true, show progress during transfer
  -q, --quiet=false: Suppress non-error messages
      --strategy='': Specify which strategy to use for copy: rsync, rsync-daemon, or tar
  -w, --watch=false: Watch directory for changes and resync automatically

Use "oc options" for a list of global command-line options (applies to all commands).
```

We'd thus therefore love to get an enhancement to oc where we can add "--no-g" and "--no-o" to the command line when running "oc rsync"

**Comment by adietish** [comment]
@csrwng we'd be very grateful if this could make it to the repo/build/release in a timely manner. Possible?

**Comment by csrwng** [comment]
@openshift/sig-developer-experience

**Comment by adietish** [comment]
@bparees I'd think that ownership and permissions are distinct matters, that's at least how I read the rsync man-page. Wrong?

**Comment by adietish** [comment]
@bparees any hints how to manually rsync to a pod, please?

**Comment by csrwng** [comment]
@adietish if running on linux, the general form of the command is:
```
rsync [flags] -e "oc rsh" [source] [destination]
```

If running on windows, the -e flag doesn't work due to incompatible streams with cygwin. Therefore, you need to start the rsync daemon on the pod first, expose it to a port locally then run rsync:

```
# First rsh into the pod so you can start the rsync daemon
oc rsh [pod]
# (and inside the pod):
$ printf "pid file = /tmp/rsync.pid\n[root]\n  path = /\n  use chroot = no\n  read only = no" > /tmp/rsync.conf
$ rsync --no-detach --daemon --config=/tmp/rsync.conf --port 9000
$ exit
```
Back on your client machine:
```
# Expose the rsync daemon from the pod locally:
oc port-forward [pod] 9000:9000

# Perform the rsync to the daemon:
rsync [your-flags] [source] rsync://127.0.0.1:9000/root/[path]
```

The command does this for you, and makes sure that the port you use is free, and that the rsync daemon started in the pod is cleaned up, etc.

**Comment by csrwng** [comment]
Forgot to mention, in the case of linux, the destination takes the form of 
```
[pod-name]:/[path]
```

**Comment by adietish** [comment]
@csrwng awesome, thx! in the doing...

**Comment by adietish** [comment]
@csrwng turns out that we need the following additional flags:
* --no-g 
* --no-o
* --omit-dir-times

Here's the output of what I ran, incrementally adding the above flags:
```
[adietish@localhost classes]$ rsync -avz  --no-perms=true /home/adietish/Documents/jboss-workspaces/jbosstools-github/runtime-openshift/.metadata/.plugins/org.jboss.ide.eclipse.as.core/camel-ose-springboot-xml@camel-ose-springboot-xml/deploy/ rsync://127.0.0.1:9000/root/deployments/BOOT-INF/classes/
sending incremental file list
./
rsync: chgrp "/deployments/BOOT-INF/classes/." (in root) failed: Operation not permitted (1)
org/
rsync: chgrp "/deployments/BOOT-INF/classes/org" (in root) failed: Operation not permitted (1)
org/mycompany/
rsync: chgrp "/deployments/BOOT-INF/classes/org/mycompany" (in root) failed: Operation not permitted (1)
spring/
rsync: chgrp "/deployments/BOOT-INF/classes/spring" (in root) failed: Operation not permitted (1)

sent 2,725 bytes  received 656 bytes  1,352.40 bytes/sec
total size is 22,451,400  speedup is 6,640.46
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
```
```
[adietish@localhost classes]$ rsync -avz  --no-perms=true --no-o --no-g /home/adietish/Documents/jboss-workspaces/jbosstools-github/runtime-openshift/.metadata/.plugins/org.jboss.ide.eclipse.as.core/camel-ose-springboot-xml@camel-ose-springboot-xml/deploy/ rsync://127.0.0.1:9000/root/deployments/BOOT-INF/classes/
sending incremental file list
./
rsync: failed to set times on "/deployments/BOOT-INF/classes/." (in root): Operation not permitted (1)
org/
rsync: failed to set times on "/deployments/BOOT-INF/classes/org" (in root): Operation not permitted (1)
org/mycompany/
rsync: failed to set times on "/deployments/BOOT-INF/classes/org/mycompany" (in root): Operation not permitted (1)
spring/
rsync: failed to set times on "/deployments/BOOT-INF/classes/spring" (in root): Operation not permitted (1)

sent 2,702 bytes  received 696 bytes  1,359.20 bytes/sec
total size is 22,451,400  speedup is 6,607.24
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]

```
```
[adietish@localhost classes]$ rsync -avz  --no-perms=true --no-o --no-g /home/adietish/Documents/jboss-workspaces/jbosstools-github/runtime-openshift/.metadata/.plugins/org.jboss.ide.eclipse.as.core/camel-ose-springboot-xml@camel-ose-springboot-xml/deploy/ rsync://127.0.0.1:9000/root/deployments/BOOT-INF/classes/


$[adietish@localhost classes]$ rsync -avz --no-perms=true --no-o --no-g --omit-dir-times \
>  /home/adietish/Documents/jboss-workspaces/jbosstools-github/runtime-openshift/.metadata/.plugins/org.jboss.ide.eclipse.as.core/camel-ose-springboot-xml@camel-ose-springboot-xml/deploy/\
>  rsync://127.0.0.1:9000/root/deployments/BOOT-INF/classes/
sending incremental file list

sent 2,690 bytes  received 221 bytes  1,164.40 bytes/sec
total size is 22,451,400  speedup is 7,712.61
```

**Comment by csrwng** [comment]
@adietish so it sounds like you always want these flags to be passed, right? owners/groups are going to be different anyway inside a container vs the host system. I would think that if the flags don't need to be exposed, then that seems like a less disruptive fix. 

@bparees wdyt?

**Comment by adietish** [comment]
@csrwng sounds reasonable to me, no objections.

**Comment by bparees** [comment]
@csrwng you're proposing those flags be the default behavior for oc rsync?

**Comment by bparees** [comment]
(default and not user selectable)

**Comment by csrwng** [comment]
@bparees yes

**Comment by bparees** [comment]
i guess i can convince myself that's ok.

**Comment by apupier** [comment]
What is the status exactly?
A solution has been accepted and needs to be implemented? Or I misunderstood the comment threads?
Do you have an estimated time when it will be fixed? Or how much effort it will require?

**Comment by bparees** [comment]
> A solution has been accepted and needs to be implemented? 

yes

> Do you have an estimated time when it will be fixed? Or how much effort it will require?

it's not the highest priority, so no one is actively working on it.  it shouldn't take much work to implement.

**Comment by adietish** [comment]
Given that this bug affects Windows, which is the vast majority of our users, we'd appreciate if this small issue could get fixed in a timely manner.

**Comment by bparees** [comment]
@adietish there's now a PR in flight: https://github.com/openshift/origin/pull/19972

**Comment by adietish** [comment]
@bparees awesome!
