### ISSUE TITLE
oauthproxy.go:399: ErrorPage 500 Internal

### ISSUE THREAD

**Issue by jihed** [openshift/origin#19376]
Hi all;

I tried to install prometheus using the examples/prometheus/prometheus.yaml on openshift 3.7.23.
Everything went well; except; I got an Error 500 internal when I connect to the GUI. 

2018/04/16 15:57:14 oauthproxy.go:399: ErrorPage 500 Internal Error Internal Error
2018/04/16 15:59:11 oauthproxy.go:657: 172.16.16.1:51530 Cookie "_oauth_proxy" not present
2018/04/16 15:59:11 provider.go:347: authorizer reason: User "system:anonymous" cannot get namespaces in project "prometheus"
2018/04/16 15:59:17 oauthproxy.go:582: error redeeming code (client:172.16.16.1:51530): Post https://master.xxxxxxxx.ovh/oauth/token:  x509: certificate signed by unknown authority
2018/04/16 15:59:17 oauthproxy.go:399: ErrorPage 500 Internal Error Internal Error

Cheers.
/JM

**Comment by enj** [comment]
PTAL at https://github.com/openshift/oauth-proxy/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+x509+unknown

You need to fix the x509 error.  Closing since this repo does not track issues for OAuth proxy.
