### ISSUE TITLE
build-logs should provide some indication of push completion

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#1937]
So, it's nice that we cleaned up the build logs a but, but now all you see is:

`2015-04-27T21:13:24.186895243Z I0427 17:13:24.186562       1 sti.go:78] Pushing 172.30.17.213:5000/wiring/origin-ruby-sample image ...`

It would be nice if we maybe spit out percentage completion messages at /10 or /25 percentage, just so you know things are moving.

**Comment by smarterclayton** [comment]
We theorized this is a missing flush somewhere

**Comment by smarterclayton** [comment]
Also, there is no progress indication possible that isn't wall of text

**Comment by mfojtik** [comment]
@smarterclayton we suppressed the push output for the default verbosity level to make the build log output not noisy. You can get full push log if you add BUILD_LOGLEVEL env var into your buildConfig or if you start the OpenShift server with --loglevel > 1

**Comment by mfojtik** [comment]
@thoraxe ^^

**Comment by smarterclayton** [comment]
Two parts: the last chunk of the log isn't being shown (what I was referring to earlier), and we don't want to show the incremental output at full volume.

**Comment by bparees** [comment]
@kargakis hopefully we can just add a flush to get the success message showing up in the logs.  Can you take a look?

nothing much we can do about the progress/percentage as @smarterclayton noted.

**Comment by kargakis** [comment]
I managed to run a build (before updating Docker to 1.6 and messing up everything with my vagrant) and got the failed error mesage `Failed to push image:` (I hadn't setup the --insecure-registry flag). Same with both STI and Docker builds. @thoraxe can you please make sure you are using the latest master, re-run a build and post its tail?

**Comment by mfojtik** [comment]
Also try to update the 'sti-builder' Docker images (the change was made not that far ago)

**Comment by bparees** [comment]
i added a flush here: https://github.com/openshift/origin/pull/1983
hopefully it will fix this.

**Comment by bparees** [comment]
@thoraxe let me know if you're still seeing this on master now.

**Comment by smarterclayton** [comment]
Is that the right issue?  No flush I see

**Comment by bparees** [comment]
@smarterclayton https://github.com/openshift/origin/pull/1983/files#diff-b9627ec6ab0689e50e5fa3e5d958c1d3R86

**Comment by smarterclayton** [comment]
Thanks

**Comment by danmcp** [comment]
@thoraxe Is there a remaining issue here?

**Comment by thoraxe** [comment]
I'll try to confirm tomorrow.

**Comment by bparees** [comment]
if you're willing to take my word for it, i can confirm now :)

**Comment by thoraxe** [comment]
Works for me!
