### ISSUE TITLE
Validation error on setting environment variables via web ui

### ISSUE THREAD

**Issue by AuthorProxy** [openshift/origin#19370]
Cannot set environment variables on build definition, with .net appsetings.json depth > 1 from openshift web ui, simplest example is:

```
ConnectionStrings:DefaultConnection=Host=postgres.db;Database=some_db;Username=some_user;Password=some_pw
```
This is default way at asp.net core to override project specific envs:
```
{
 "Logging": {
    ...
  },
  "App": {
    ...
  },
  "ConnectionStrings": {
    "DefaultConnection": "..."
  }
}
```

Used like `Configuration.GetConnectionString("DefaultConnection")`

Said that there validation error, cannot use nonregex symbols.

**Comment by jwforres** [comment]
@openshift/sig-user-interface

**Comment by bparees** [comment]
Yeah this is an upstream restriction, see: https://github.com/kubernetes/kubernetes/issues/16863#issuecomment-154984982

and see also:
```
$ export A:B=c
-bash: export: `A:B=c': not a valid identifier
```

/close

**Comment by bparees** [comment]
My only suggestion would be to set the key without the colon and as part of your container entrypoint script, detect the key and set a new var using the key with a colon.
