### ISSUE TITLE
Available ports test fails when docker pull for the discard container is not possible

### ISSUE THREAD

**Issue by gbraad** [openshift/origin#19387]
A misleading error will be returned when the pull of the container image fails. This might be related to DNS or an unreliable network (or maybe even offline?). While the error says "No such image", the majority of people think the port is claimed bu something.

```
   Error: Cannot get TCP port information from Kubernetes host
   Caused By:
     Error: cannot create container using image openshift/origin:v3.7.1
     Caused By:
       Error: Error: No such image: openshift/origin:v3.7.1
```

The error is caused by this part of code:

https://github.com/openshift/origin/blob/d9928e06f94dc5cd1c74084a0be55f0682227df5/pkg/oc/bootstrap/docker/openshift/helper.go#L74-L87

For more info, see https://github.com/minishift/minishift/issues/2037

**Comment by LalatenduMohanty** [comment]
cc @deads2k , if this can be fixed during restructuring of the code.

**Comment by deads2k** [comment]
@mfojtik fyi

**Comment by gbraad** [comment]
Feels like container pull should be step by itself, as the error for this would make more sense when prepended with "Pulling origin container ... " or similar

**Comment by gbraad** [comment]
Feels like container pull should be step by itself, as the error for this would make more sense when prepended with "Pulling origin container ... " or similar

**Comment by gbraad** [comment]
still relevant, howevermight have changed due to the new 3.10
implementation.
