### ISSUE TITLE
cri-o jobs failing with error

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#19380]
```
        "Apr 16 02:02:57 ip-172-18-15-104.ec2.internal origin-node[21840]: E0416 02:02:57.241842   21840 remote_runtime.go:187] CreateContainer in sandbox \"0816c035eb3b3266f5667c09e9797e648ac17f30efc428ceb4e9fba836512f60\" from runtime service failed: rpc error: code = Unknown desc = path \"/etc/origin/master/\" is mounted on \"/etc\" but it is not a shared or slave mount", 
        "Apr 16 02:02:57 ip-172-18-15-104.ec2.internal origin-node[21840]: E0416 02:02:57.241897   21840 kuberuntime_manager.go:733] container start failed: CreateContainerError: path \"/etc/origin/master/\" is mounted on \"/etc\" but it is not a shared or slave mount", 
        "Apr 16 02:02:57 ip-172-18-15-104.ec2.internal origin-node[21840]: E0416 02:02:57.241933   21840 pod_workers.go:186] Error syncing pod 39889149b61ef7707a95a6f2c8118836 (\"master-api-ip-172-18-15-104.ec2.internal_kube-system(39889149b61ef7707a95a6f2c8118836)\"), skipping: failed to \"StartContainer\" for \"api\" with CreateContainerError: \"path \\\"/etc/origin/master/\\\" is mounted on \\\"/etc\\\" but it is not a shared or slave mount\"", 
        "Apr 16 02:02:57 ip-172-18-15-104.ec2.internal origin-node[21840]: I0416 02:02:57.241960   21840 server.go:428] Event(v1.ObjectReference{Kind:\"Pod\", Namespace:\"kube-system\", Name:\"master-api-ip-172-18-15-104.ec2.internal\", UID:\"39889149b61ef7707a95a6f2c8118836\", APIVersion:\"v1\", ResourceVersion:\"\", FieldPath:\"spec.containers{api}\"}): type: 'Warning' reason: 'Failed' Error: path \"/etc/origin/master/\" is mounted on \"/etc\" but it is not a shared or slave mount", 
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/7960/test_pull_request_openshift_ansible_extended_conformance_install_crio/4504/

**Comment by mrunalp** [comment]
@smarterclayton The first error indicates that the host path has not been prepared for mount propagation. Is this something new that was added or a regression? I think docker is doing this automatically and we could do the same if required.

**Comment by mrunalp** [comment]
I just tested with docker and we do need to prepare the source mount for propagation ourselves. Something like https://github.com/kubernetes-incubator/cri-tools/blob/240a840375cdabb5860c75c99e8b0d0a776006b4/pkg/validate/container_linux.go#L165
From the error it appears as if a step like this wasn't made or failed silently.

**Comment by smarterclayton** [comment]
No idea, ask @sjenning or the storage team

On Apr 16, 2018, at 8:53 PM, Mrunal Patel <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> The first error
indicates that the host path has not been prepared for mount propagation.
Is this something new that was added or a regression? I think docker is
doing this automatically and we could do the same if required.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/19380#issuecomment-381795025>,
or mute the thread

**Comment by sjenning** [comment]
This is more fallout from MountPropagation going beta and on by default in kube 1.10.

@jsafrane any guidance for @mrunalp on how best to resolve?

**Comment by runcom** [comment]
the `atomic-openshift-utils` error might be related to https://github.com/openshift/openshift-ansible/pull/5563 @sdodson  should I remove the "yum install atomic-openshift-utils" from the cri-o job as well?

**Comment by sdodson** [comment]
> the atomic-openshift-utils error might be related to openshift/openshift-ansible#5563 @sdodson should I remove the "yum install atomic-openshift-utils" from the cri-o job as well?

Yeah, s/atomic-openshift-utils/openshift-ansible/ everywhere

**Comment by runcom** [comment]
@smarterclayton @mrunalp @sdodson created a PR to fix the installation issues: https://github.com/openshift/aos-cd-jobs/pull/1309 (weird the crio rpm job wasn't triggered though :( )

**Comment by smarterclayton** [comment]
Once the test is green we can turn it back on for all jobs.

**Comment by smarterclayton** [comment]
https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/directory/test_pull_request_openshift_ansible_extended_conformance_install_crio

Looks to be still failing

**Comment by runcom** [comment]
The OpenShift ansible installation went through actually, probably still the mount stuff
