### ISSUE TITLE
PVC mount timeout with large number of files

### ISSUE THREAD

**Issue by tpolekhin** [openshift/origin#19403]
Hello! This is a question
Im running origin 1.5 cluster on aws with pvc for jenkins
I have a large number of jobs on jenkins configured
When jenkins pod fails and schedules on another node it fails to start with pvc mount timeout error.

I checked on the instance itself and EBS volume is attached and i can walk though it on the node.
I noticed using lsof that openshift process on the node is going through the filesystem of attached volume. Increasing startup timeout of jenkins pod i was able to make it start after 20-30 minutes of wait time.

My question is: what openshift is doing with volume, why its doing it and why its taking so long?
Thanks!

##### Version
```
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth

openshift v1.5.1
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. create a pvc volume with large number of files
2. make pod reschedule on another node

**Comment by jwforres** [comment]
@openshift/sig-pod @openshift/sig-storage

**Comment by sjenning** [comment]
This is a known issue on PVs with large numbers of files. The node must chown all the files in the PV to make them accessible to the uid the pod is using.  Depending on the speed of the storage, this can take a very long time.

https://bugzilla.redhat.com/show_bug.cgi?id=1459106

There is no known solution to this other than to architect your application to not store a bunch of files in a single PV.

**Comment by tpolekhin** [comment]
Thanks for the explanation!
