### ISSUE TITLE
osc get selector filtering not working

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#1940]
Whenever I use a selector, `osc get rc` returns empty list:

```bash
$ osc get rc 
CONTROLLER   CONTAINER(S)           IMAGE(S)                                                                                                   SELECTOR                                                        REPLICAS
database-1   django-demo-database   openshift/postgresql-92-centos7                                                                            deployment=database-1,deploymentconfig=database,name=database   1
frontend-1   django-demo            172.30.250.133:5000/demo/django-example:076f0e5ddaa3370dafb1500a252bb8191e003bb4cf62504fee9f4d376803ecf9   deployment=frontend-1,deploymentconfig=frontend,name=frontend   4
$ osc get rc -l 'name=frontend'
CONTROLLER   CONTAINER(S)   IMAGE(S)   SELECTOR   REPLICAS
```

**Comment by ncdc** [comment]
Does your rc itself have the name label set to frontend?

**Comment by kargakis** [comment]
@rhcarvalho can you post the output of the following commands? 
```
$ osc describe rc/frontend-1
$ osc describe rc/database-1
```

**Comment by rhcarvalho** [comment]
@kargakis 

```bash
$ osc describe rc frontend-1
Name:           frontend-1
Image(s):       172.30.250.133:5000/demo4/django-example:532488cba497e94f093309e7d4cc76be014b6d936a35e31e1d30b90ce2423c85
Selector:       deployment=frontend-1,deploymentconfig=frontend,name=frontend
Labels:         template=application-template-stibuild
Replicas:       8 current / 8 desired
Pods Status:    8 Running / 0 Waiting / 0 Succeeded / 0 Failed
No events.

$ osc describe rc database-1
Name:           database-1
Image(s):       openshift/postgresql-92-centos7
Selector:       deployment=database-1,deploymentconfig=database,name=database
Labels:         template=application-template-stibuild
Replicas:       1 current / 1 desired
Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 0 Failed
No events.
```

**Comment by ncdc** [comment]
`osc get <type> -l '....'` searches for labels on the typed objects. In your case, you'd need to do `osc get rc -l 'template=application-template-stibuild'`. That's the only label on the rc.

**Comment by rhcarvalho** [comment]
@ncdc thank you, I understood it. But I couldn't figure out how to set labels for the replication controllers. I looked into code and tried something like this with no success:

```json
    {
      "kind": "DeploymentConfig",
      "apiVersion": "v1beta1",
      "metadata": {
        "name": "frontend"
      },
      "template": {
        "controllerTemplate": {
          // ...
        },
        "strategy": {
          // ...
        },
        "metadata": {
          "labels": {
            "name": "frontend-rc"
          }
        }
      },
      "triggers": [
        // ...
      ]
    },
```

Any pointers?

**Comment by ncdc** [comment]
@ironcladlou ^

**Comment by kargakis** [comment]
> But I couldn't figure out how to set labels for the replication controllers.

This will be enabled after this gets merged: https://github.com/openshift/origin/pull/1944

```
[vagrant@openshiftdev sample-app]$ osc get rc
CONTROLLER          CONTAINER(S)   IMAGE(S)                                  SELECTOR                                                                                REPLICAS
docker-registry-1   registry       openshift/origin-docker-registry:v0.4.4   deployment=docker-registry-1,deploymentconfig=docker-registry,docker-registry=default   1
[vagrant@openshiftdev sample-app]$ osc label rc docker-registry-1 rsc=rc
CONTROLLER          CONTAINER(S)   IMAGE(S)                                  SELECTOR                                                                                REPLICAS
docker-registry-1   registry       openshift/origin-docker-registry:v0.4.4   deployment=docker-registry-1,deploymentconfig=docker-registry,docker-registry=default   1
[vagrant@openshiftdev sample-app]$ osc describe rc docker-registry-1
Name:		docker-registry-1
Image(s):	openshift/origin-docker-registry:v0.4.4
Selector:	deployment=docker-registry-1,deploymentconfig=docker-registry,docker-registry=default
Labels:		docker-registry=default,rsc=rc
Replicas:	1 current / 1 desired
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
No events.
```

The labeling functionality is in place, I just need to work on the stop functionality.

**Comment by ironcladlou** [comment]
Currently, labels can be applied to the `controllerTemplate` within the DeploymentConfig ([example here](https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json#L107)). There's not an API for specifying labels for the deployment/ReplicationController itself.

What's the use case for applying a label to the ReplicationController via the DeploymentConfig? I'm not opposed to the idea, but would like to better understand the intent.

**Comment by ironcladlou** [comment]
>Currently, labels can be applied to the controllerTemplate within the DeploymentConfig (example here). There's not an API for specifying labels of the deployment/ReplicationController itself.

>What's the use case for applying a label to the ReplicationController via the DeploymentConfig? I'm not opposed to the idea, but would like to better understand the intent.

Looks like I spoke too soon: labels set on the DeploymentConfig are copied to the deployment/ReplicationController.

**Comment by ironcladlou** [comment]
@rhcarvalho 
Try this:

```json
{
  "kind": "DeploymentConfig",
  "apiVersion": "v1beta1",
  "metadata": {
    "name": "frontend",
    "labels": {
      "name": "frontend-rc"
    }
  },
  "template": {
    "controllerTemplate": {},
    "strategy": {}
  },
  "triggers": []
}
```

**Comment by rhcarvalho** [comment]
@ironcladlou the intent was to be able to do:

```bash
osc edit rc $(osc get rc -l 'name=frontend-rc' -t '{{ with index .items 0 }}{{ .metadata.name }}{{ end }}')
```

That would allow me to, for instance, update the number of replicas without having to know the specific name of the replication controller.

Your suggestion does work, indeed adding the label to the deployment config copies it to the replication controller.

Summing up, I think the filtering works, as long as I properly set the labels. I'm closing this issue.

**Comment by smarterclayton** [comment]
The resize command will be provided shortly to cover this.
