### ISSUE TITLE
test/cmd/newapp.sh is failing due to missing wordpress-mysql.json

### ISSUE THREAD

**Issue by nak3** [openshift/origin#19419]
`test/cmd/newapp.sh` points to https://raw.githubusercontent.com/openshift/origin/master/examples/wordpress/template/wordpress-mysql.json:

https://github.com/openshift/origin/blob/fedbc3bc882693dd8a61fc25ed95fab8895c742c/test/cmd/newapp.sh#L516

However, the wordpress-mysql.json was deleted by https://github.com/openshift/origin/pull/19262

e.g https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19355/test_pull_request_origin_cmd/12715/

**Comment by bparees** [comment]
thanks @nak3, fixing the test in #19421

**Comment by smarterclayton** [comment]
Beat you by one :)

**Comment by bparees** [comment]
> Beat you by one :)

well maybe you should have linked it here so I knew :)
