### ISSUE TITLE
specify path to value when config is invalid

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#1942]
I upgraded from `0.4.3` to `0.4.4`. OpenShift was unable to start:
```
Invalid MasterConfig /var/lib/openshift/master.yaml
masterPublicURL: invalid value '': must contain a scheme (e.g. https://)
masterPublicURL: invalid value '': must contain a host
```
My config has 2 such values, both of them are filled:
```bash
$ grep "masterP" -C 3 master.yaml
apiVersion: v1
assetConfig:
  logoutURL: ""
  masterPublicURL: https://172.16.125.41:8443
  publicURL: https://172.16.125.41:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
--
      clientCA: openshift.local.certificates/proxy/ca.crt
      headers:
      - X-Remote-User
  masterPublicURL: https://172.16.125.41:8443
  masterURL: https://172.16.125.41:8443
```
So I'm assuming there was some change between 0.4.3 and 0.4.4, and some new `masterPublicURL` popped up somewhere. Unfortunately it's impossible for me to figure out the change.

Would be great if logs would precisely stat what is missing and where. Or, make the keys unique and list them somewhere.

**Comment by liggitt** [comment]
the message actually does include the full config key... in this case, `masterPublicURL` is required at the top level as well. The reason for the duplication is that the stanzas are independent... the assetConfig stanza is passed to the UI server, etc.

**Comment by TomasTomecek** [comment]
Right, understood. We can close this now I think.
