### ISSUE TITLE
[gce] Conflict when approving the CSR

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#19430]
Seen this flake in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19424/test_pull_request_origin_extended_conformance_gce/19348/
 
```
 1. Hosts:    ci-prtest-5a37c28-19348-ig-m-st4c
     Play:     masters
     Task:     Bootstrap all nodes that were identified with bootstrap metadata
     Message:  [{u'cmd': u'/bin/oc adm certificate approve csr-jh7qw', u'returncode': 0, u'results': {}}, {u'cmd': u'/bin/oc adm certificate approve csr-klkjj', u'returncode': 1, u'results': {}, u'stderr': u'Error from server (Conflict): Operation cannot be fulfilled on certificatesigningrequests.certificates.k8s.io "csr-klkjj": the object has been modified; please apply your changes to the latest version and try again\n', u'stdout': u'No resources found\n'}]
```

Opened and closed https://github.com/kubernetes/kubernetes/pull/62846 after talking to @deads2k 

@sdodson i guess we have to make the ansible retry on conflict in this case (and check the preconditions first).

**Comment by sdodson** [comment]
@mfojtik I think it's better if the client handles the retry rather than wrapping this in retries in ansible, do you?

**Comment by mfojtik** [comment]
@sdodson the client don't know what changed in the object so it can't make educated decisions whether the request for update is still valid or not. Think that somebody else approved the CSR meanwhile, client will don't know what to do and retrying will just make it override the existing approval....

/cc @deads2k

**Comment by smarterclayton** [comment]
Yes, ansible should retry on conflict.

**Comment by smarterclayton** [comment]
And it should be the high level code that's trying the update (the CSR approver), not the low level client.  The low level client doesn't know whether conflicts are safe to retry.

**Comment by smarterclayton** [comment]
Opened an upstream
