### ISSUE TITLE
oc create route cannot label routes

### ISSUE THREAD

**Issue by cldmnky** [openshift/origin#19447]
We use route labels to select routers when creating routes. When using `oc create route edge` there is no option to add labels to the route being created.

##### Version
```
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://console.xxxx.xx:443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
``` 
##### Steps To Reproduce
1. Create a route using `oc create route edge [options]`, try adding `-l key=value` at creation.

##### Current Result
````
oc create route edge --service=frontend --insecure-policy=allow -l tier=staging
Error: unknown shorthand flag: 'l' in -l
``` 

##### Expected Result
The route is created with the labels specified.

**Comment by jwforres** [comment]
@openshift/sig-networking 

also an issue of general CLI consistency @soltysh
