### ISSUE TITLE
Metrics for OpenShift Origin 3.9 fails due to incorrect image tags

### ISSUE THREAD

**Issue by haroldwongms** [openshift/origin#19440]
When deploying Metrics on OpenShift Origin 3.9, I get errors that the following images are not found:
docker.io/openshift/origin-metrics-cassandra:v3.9.0
docker.io/openshift/origin-metrics-hawkular-metrics:v3.9.0
docker.io/openshift/origin-metrics-heapster:v3.9.0

I looked at docker hub and see that these images have a tag of v3.9 and not v3.9.0.

##### Version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxxxx
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Install OpenShift Origin with Metrics enabled via hosts file
2. Or Install Metrics post cluster stand up using: 
ansible-playbook openshift-ansible/playbooks/openshift-metrics/config.yml -e openshift_metrics_install_metrics=True -e openshift_metrics_cassandra_storage_type=dynamic

##### Current Result
All the pods associated with metrics in an ImagePullBackOff status

hawkular-cassandra-1-c27b4   0/1       ImagePullBackOff   0          18m
hawkular-metrics-zsvkb       0/1       ImagePullBackOff   0          18m
heapster-78w7j               0/1       ImagePullBackOff   0          18m

##### Expected Result
All the pods are in running state

##### Additional Information
Events for heapster pod show:

Failed to pull image "docker.io/openshift/origin-metrics-heapster:v3.9.0": rpc error: code = Unknown desc = manifest for docker.io/openshift/origin-metrics-heapster:v3.9.0 not found

**Comment by pennpeng** [comment]
```-e openshift_metrics_image_version=v3.9```  will be ok

**Comment by jwforres** [comment]
@smarterclayton looks like we are missing 3.9.0 image tags for metrics

**Comment by MarWestermann** [comment]
I face the same error

**Comment by kkorada** [comment]
same problem here
please tag it with v3.9.0

**Comment by mickuehl** [comment]
this is still open and breaks the openshift-ansible playbooks ...

**Comment by JarleB** [comment]
Any news. Should trivial to add that tag for consistency? 

Attempting to work around by 

`set openshift_image_tag=v3.9`

in inventory fails with 

> fatal: [kube-sandbox-m02.uio.no]: FAILED! => {"msg": "last_checked_host: kube-sandbox-m02.uio.no, last_checked_var: openshift_image_tag;openshift_image_tag must be in the format\nv#.#.#[-optional.#]. Examples: v1.2.3, v3.5.1-alpha.1\nYou specified openshift_image_tag=v3.9"}

**Comment by uocxp** [comment]
please tag these images with v3.9.0 !

**Comment by CelsoSantos** [comment]
How come after all these months this is still not fixed??? 

Not in the playbooks, not in docker hub... Come on it can't be that hard..
