### ISSUE TITLE
oc cluster up (v3.9.0) seems to timeout waiting for the API server to start listening when running on Travis-ci

### ISSUE THREAD

**Issue by crobby** [openshift/origin#19449]
When running oc cluster up within Travis-ci, the cluster up fails seemingly due to a timeout.  Below is the end of the output where the error is thrown.  I have seen our setup on Travis-ci run correctly about 2 out of 20 runs.  For the full log of the travis-ci job with the cluster-up failing, you can go to:  https://travis-ci.org/crobby/oshinko-webui/jobs/368800182

I0419 19:11:36.089373    6754 helper.go:189] Container running = true
   Waiting for API server to start listening
I0419 19:11:36.289528    6754 net.go:92] Got error tls.timeoutError{}, trying again: "10.20.0.184:8443"
I0419 19:11:37.490043    6754 net.go:92] Got error tls.timeoutError{}, trying again: "10.20.0.184:8443"
I0419 19:11:38.690400    6754 net.go:92] Got error tls.timeoutError{}, trying again: "10.20.0.184:8443"
I0419 19:11:39.890772    6754 net.go:92] Got error tls.timeoutError{}, trying again: "10.20.0.184:8443"
I0419 19:11:41.091214    6754 net.go:92] Got error tls.timeoutError{}, trying again: "10.20.0.184:8443"
FAIL
   Error: cannot access master readiness URL https://10.20.0.184:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     INFO: 2018/04/19 19:11:52 ccBalancerWrapper: new subconn: [{127.0.0.1:4001 0  <nil>}]
     INFO: 2018/04/19 19:11:52 balancerWrapper: handle subconn state change: 0xc429b58780, CONNECTING
     INFO: 2018/04/19 19:11:52 ccBalancerWrapper: updating state and picker called by balancer: CONNECTING, 0xc4242e74a0
     INFO: 2018/04/19 19:11:52 balancerWrapper: handle subconn state change: 0xc429b58780, SHUTDOWN
     INFO: 2018/04/19 19:11:52 ccBalancerWrapper: updating state and picker called by balancer: TRANSIENT_FAILURE, 0xc4242e74a0
     INFO: 2018/04/19 19:11:52 balancerWrapper: handle subconn state change: 0xc429b58830, CONNECTING
     INFO: 2018/04/19 19:11:52 ccBalancerWrapper: updating state and picker called by balancer: CONNECTING, 0xc4242e74a0
     WARNING: 2018/04/19 19:11:52 Failed to dial 127.0.0.1:4001: grpc: the connection is closing; please retry.
     WARNING: 2018/04/19 19:11:52 Failed to dial 127.0.0.1:4001: grpc: the connection is closing; please retry.
     INFO: 2018/04/19 19:11:52 balancerWrapper: got update addr from Notify: [{127.0.0.1:4001 <nil>}]
   Caused By:
     Error: Get https://10.20.0.184:8443/healthz/ready: read tcp 10.20.0.184:34024->10.20.0.184:8443: read: connection reset by peer

##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Attempt to run oc cluster up inside Travis-ci (or presumably another sufficiently slow environment)
2. Note that you will mostly likely run into timing-out/max retries while "Waiting for API server to start listening"

##### Current Result
oc cluster up fails inside Travis (most of the time)

##### Expected Result
oc cluster up works (even if we have to supply some other flag to increase the timeout/retries value)

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by crobby** [comment]
It looks like maybe our travis script was trying to start oc cluster up with sudo, which may have been causing our issues.  We have removed our unnecessary and probably wrong use of sudo and our tests are running nicely.  I'd be ok with closing this issue.
