### ISSUE TITLE
Add logging-rate and flow detection to cluster-config-mirror

### ISSUE THREAD

**Issue by jeremyeder** [openshift/origin#19454]
We need to incorporate a logging rate to the cluster-config-mirror.

* Quantity of pods
* Rate of log lines per pod
* Histogram of logging rates per pod
* Length (bytes) of log lines

Cluster-loader must then be extended to support these inputs.

@sjug @mffiedler @portante @tkatarki @richm @jcantrill

**Comment by richm** [comment]
something like this?  https://github.com/ViaQ/logging-load-driver

**Comment by jeremyeder** [comment]
No, we have load generators, what we don't have is a way to build a "load profile" from an existing cluster and build test scenarios to replay that load.

**Comment by sjug** [comment]
Wouldn't passing a file or environment variable be sufficient for the functionality listed? What were you thinking as a mechanism for passing this into the pods?

**Comment by sjug** [comment]
Where can one measure these metrics?

How were you thinking that cluster loader passes this information to the pods?
