### ISSUE TITLE
Cannot create security context constraints "anyuid". securitycontextconstraints.security.openshift.io "anyuid" already exists.

### ISSUE THREAD

**Issue by mipam007** [openshift/origin#19469]
updating security context constraints "anyuid" in project via application template failed with error:

Cannot create security context constraints "anyuid". securitycontextconstraints.security.openshift.io "anyuid" already exists.

##### Version

```
oc version
oc v3.6.173.0.96
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://FQDN:8443
openshift v3.6.173.0.96
kubernetes v1.6.1+5115d708d7
```

```
openshift version
openshift v3.6.173.0.96
kubernetes v1.6.1+5115d708d7
etcd 3.2.1

```
##### Steps To Reproduce
1. In project click to add project button
2. and selecting json template

```
{
        "apiVersion": "v1",
        "kind": "Template",
        "metadata": {
                "description": "pojďme se najest",
                "name": "dotaznik"
        },
        "objects": [
                {
                        "apiVersion": "v1",
                        "kind": "ImageStream",
                        "metadata": {
                                "annotations": {
                                "description": "sleduje změny v aplikačním obraze"
                                },
                                "name": "dotaznikis"
                        }
                },
                {
                        "apiVersion": "v1",
                        "kind": "ServiceAccount",
                        "metadata": {
                                "name": "sa-apache"
                        }
                },
                {
                        "kind": "SecurityContextConstraints",
                        "apiVersion": "v1",
                        "metadata": {
                                        "name": "anyuid"
                        },
                        "seLinuxContext": {
                            "type": "MustRunAs"
                        },
                        "runAsUser": {
                            "type": "RunAsAny"
                        },
                        "supplementalGroups": {
                            "type": "RunAsAny"
                        },
                        "fsGroup": {
                            "type": "RunAsAny"
                        },
                        "users": [
                                "system:serviceaccount:barvyovy:sa-apache"
                        ]
                },
...........
```

##### Current Result
receiving error message Cannot create security context constraints "anyuid". securitycontextconstraints.security.openshift.io "anyuid" already exists

##### Expected Result
application is created with anyuid scc

##### Additional Information
Unfortunately I haven't found in the documentation nor on the google how to update SCC within template.I am not interested in commands. I need to have template which will set all needed stuff. 

Even in OpenShift for Developers is missing such needed information how to write templates.

**Comment by jwforres** [comment]
Are you trying to update the anyuid SCC or do you want to create a new SCC object? Your error message is that you are creating an SCC that already exists.

If you want to create a new one then you should parameterize the metadata.name of the resource, that is generally a good rule to follow for Templates or you'll just get errors when you re-create it in the same project.

If you want to update an existing resource, then you don't want to pipe the results of processing the template into create.  Instead you can process the template and pipe it into `oc apply`.

@openshift/sig-developer-experience  may have other recommendations they can offer

**Comment by mipam007** [comment]
Hi, thank you for answer! I am trying to update template. My goal is to create template which cloudform could use for deploying application. Your proposal is good but means some additional steps. I have to think about it again :)

Thank you very much
Jindra
23. 4. 2018 v 16:00, Jessica Forrester <notifications@github.com>:

**Comment by bparees** [comment]
i think @jwforres covered all the suggestions/comments i'd have.

also note that in general using templates to update cluster scoped resources has some issues and i'd encourage you to avoid it.  Such templates won't work well(if at all) when instantiated via the TemplateInstanceController or the TemplateServiceBroker.
