### ISSUE TITLE
oc cluster up does not work when specifying --image

### ISSUE THREAD

**Issue by jmontleon** [openshift/origin#19461]
oc cluster up does not work when specifying --image

##### Version
 oc version
oc v3.10.0-alpha.0+5f7eae1-812
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
Unable to connect to the server: x509: certificate signed by unknown authority

##### Steps To Reproduce
1. oc cluster up --image=docker.io/openshift/origin-control-plane --tag=latest

##### Current Result
oc cluster up times out

##### Expected Result
oc cluster up should complete

##### Additional Information
I've tried all of these and none work.
--image=docker.io/openshift/origin-control-plane
--image=openshift/origin-control-plane
--image=docker.io/openshift/origin
--image=docker.io/openshift/origin-control-plane:latest
--image=openshift/origin-control-plane:latest

--image=openshift/origin-control-plane:latest seems to most closely emulate what I see if I watch docker ps without specifying an image, but it still doesn't work.

**Comment by mfojtik** [comment]
This is being fixed here: https://github.com/openshift/origin/pull/19339 i'm going to make that PR mergeable today.

/cc @deads2k 
/assign @mfojtik

**Comment by mfojtik** [comment]
@jmontleon maybe you misunderstood the flag, the flag is to set a 'format' for the images to use, like:

```
--image='openshift/origin-${component}:${version}'
```

This allows you to override the default repository and use your set of images if needed, or use a registry different than DockerHub. (this is not yet working).

**Comment by jmontleon** [comment]
@mfojtik Thanks. We had been successfully using it just set to docker.io/openshift/origin (or set to our internal registry where we've sync'd the openshift+our images) up until about a week ago. Regardless I'll start setting it as you described.

**Comment by malli31** [comment]
> @jmontleon maybe you misunderstood the flag, the flag is to set a 'format' for the images to use, like:
> 
> ```
> --image='openshift/origin-${component}:${version}'
> ```
> 
> This allows you to override the default repository and use your set of images if needed, or use a registry different than DockerHub. (this is not yet working).

Is this working now??
oc cluster up --image "private repo url"

I am running 

oc cluster up --image="myreporul/openshift/origin-control-plane:v3.11"

I am facing 

Error: error creating node config: could not run "create-kubelet-flags": cannot start container 75bea1c224af587f599706798b950d4022eb42b10315eaa69ede93bf0e0bac3e; caused by: cannot start container 75bea1c224af587f599706798b950d4022eb42b10315eaa69ede93bf0e0bac3e

Will this work??
Because now with docker restriction to pull images this feature is very much needed.
