### ISSUE TITLE
We should test that the console and service-catalog work correctly together when installed by oc cluster add

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#19464]
I found a bug where the service-catalog did not work correctly with the console when they were both installed by oc cluster add (see https://github.com/openshift/origin/pull/19460 for fix). We should have a test in the service-catalog job that establishes that the console correctly shows serviceclasses/plans.

##### Version

master

##### Steps To Reproduce
1. create a cluster with `oc cluster up`
2. run `oc cluster add` to install `service-catalog` and `openshift-web-console`
3. load catalog in console

**Comment by pmorie** [comment]
@luksa are you interested in this at all?

**Comment by luksa** [comment]
@pmorie Sure, why not.
