### ISSUE TITLE
cluster up docs should have a prerequisite around disk space

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#19477]
The docs currently at https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#prerequisites

There's no mention of free disk space, and I've seen this torpedo a number of `oc cluster up` users - they try to run oc cluster up on a system where `/` is 95% full and it doesn't work. We should have a note about this in the doc.

##### Version
master

**Comment by jwforres** [comment]
@pmorie you should probably open this issue against openshift-docs repo instead

**Comment by pmacko1** [comment]
@psturc @jhellar we should have something similar in our docs as well wdyt
