### ISSUE TITLE
oc apply on dc patch fails after creation with new-app

### ISSUE THREAD

**Issue by djohnston89** [openshift/origin#19479]
Patching deployment config fails after creation by new-app. (https://github.com/openshift/jenkins-client-plugin/issues/149)

##### Version
I'm using OpenShift DSL Jenkins pipeline plugin (https://github.com/openshift/jenkins-client-plugin) for OpenShift Jenkins v3.9 and the issue was recreated by @gabemontero with the oc cli.

##### Steps To Reproduce
https://github.com/openshift/jenkins-client-plugin/issues/149

##### Current Result
Updating deployment config after new-app with oc apply gives errors.

##### Expected Result
Deployment config updated as desired.

**Comment by gabemontero** [comment]
Actually I figured this one out ... continuing the discussion in https://github.com/openshift/jenkins-client-plugin/issues/149
