### ISSUE TITLE
504 Gateway Timeout on some static assets

### ISSUE THREAD

**Issue by ServerNinja** [openshift/origin#19474]
We have a pod that runs a few containers (1 for rails/unicorn and 1 for nginx). Assets are precompiled during the docker image build. When the pod starts up, the rails/unicorn container copies assets to a shared-volume that the nginx container has access to. Both containers run under a limited user context. All assets have same permissions and ownership (same user nginx runs as in the container)

In one of our OpenShift environments, we're running into an interesting issue where some assets will be delivered via HTTP GET and some won't. 

We're not sure why this would be. Is it possible that something about the SDN or the internal load balancing with the services could be blocking certain MIME Types from being able to pass through. We haven't seen this on other OpenShift installations and are not sure what would cause this. Any ideas would be greatly appreciated.

##### Version
```
$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://osemaster01.xxxxxxxxxx.com:8443
openshift v1.3.3
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
- Basic Nginx configuration with Rails / Unicorn. Assets pre-compiled but are served by nginx
/etc/nginx/nginx.conf
```
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server_tokens off;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/error.log  main;

    # Avoid issues when the host, port, and/or scheme that Nginx sees differ
    # from those the client is using
    absolute_redirect off;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    gzip            on;
    gzip_types      text/plain application/json application/javascript text/css;

    charset         'utf-8';
    charset_types   text/plain application/json application/javascript text/css;

    keepalive_timeout  65;

    root /usr/share/nginx/html;

    include /etc/nginx/conf.d/*.conf;
}
```
/etc/nginx/conf.d/unicorn.conf (only file in this directory)
```
upstream unicorn {
    server unix:/usr/share/nginx/socket/unicorn.sock fail_timeout=0;
}

server {
    listen 8080;
    client_max_body_size 100M;

    error_page  500 502 503 504 /500.html;
    error_page  404 /404.html;

    if (-f $document_root/system/maintenance.html) {
        return 503 /system/maintenance.html;
    }

    location @rails {
        proxy_redirect  off;
        expires         off;
        proxy_pass      http://unicorn;
    }

    location / {
        proxy_set_header  X-Forwarded-Host "";
        try_files         $uri @rails;
    }
}
```

##### Current Result
To keep it simple, there is a css file and an image (svg format). This is what we are seeing:

- We can GET the SVG file when we hit the router but the CSS file gives a 504 gateway timeout (when using cURL or browser)
- We can GET the SVG file when we curl the POD IP directly but the CSS file gives a "504 Gateway Timeout" - using curl to hit the IP and port of the pod from within the SDN. However, if we're on the same OpenShift node that the pod resides on, we can GET both the css and svg file with no problem.
- If we `oc rsh` to the pod, we can GET both the svg file and the css file with no problem. 

##### Expected Result
All assets should GET the same when using cURL no matter where its run from. Not sure whats causing this.

**Comment by johnr-spindance** [comment]
Update on this:

So it seems to be an issue where assets over 6.5K are getting the 504 Gateway Timeout response...

**Comment by jwforres** [comment]
@openshift/sig-networking
