### ISSUE TITLE
Peer's certificate issuer has been marked as not trusted by the user

### ISSUE THREAD

**Issue by HP-dufeng** [openshift/origin#19482]
#### Description
when start build , occurs errors:
```
error: fatal: unable to access 'https://github.com/openshift/nodejs-ex.git/':  Peer's certificate issuer has been marked as not trusted by the user.
```

I after set GIT_SSL_NO_VERIFY = false, then occurs errors:
```
error: fatal: unable to access 'https://github.com/openshift/nodejs-ex.git/':  The requested URL returned error: 503
```
##### Version
openshift-origin: v3.9

**Comment by jfmatth** [comment]
getting the same on 3.6 as of yesterday.

WTF?

**Comment by jwforres** [comment]
@openshift/sig-developer-experience any thoughts here?

**Comment by gabemontero** [comment]
@HP-dufeng @jfmatth - how were the build configs created?  and how long ago were they created?

I just did an `oc new-app https://github.com/nodejs-ex` for example and the build worked fine.

**Comment by HP-dufeng** [comment]
I found this is probably a problem with my DNS setup.
I used a separate machine for DNS server.
Below is my /etc/dnsmasq.d/openshift-cluster.conf file config
192.168.3.53 is my openshift master node
```
strict-order
listen-address=192.168.3.53,127.0.0.1
address=/cefcfco.com/192.168.3.53
```
when I change this line `address=/cefcfco.com/192.168.3.53`
with  `address=/apps.cefcfco.com/192.168.3.53`
The above problem has not appeared.

Why?

**Comment by danwinship** [comment]
> when I change this line `address=/cefcfco.com/192.168.3.53`
> with `address=/apps.cefcfco.com/192.168.3.53`
> The above problem has not appeared.
> 
> Why?

`address=/cefcfco.com/192.168.3.53` means "if a client asks about any host in the `cefcfco.com` domain, say that that host has IP `192.168.3.53`". Which is a weird thing to configure. Are you sure you didn't mean `server=/cefcfco.com/192.168.3.53`? ("if a client asks about any host in the `cefcfco.com` domain, then delegate that query to the DNS server at `192.168.3.53`.")

**Comment by HP-dufeng** [comment]
Oh, I,m sorry,
I made a mistake in this paragraph 
**192.168.3.52** is my dns server
192.168.3.53 is my openshift master node
```
strict-order
listen-address=192.168.3.52,127.0.0.1
address=/cefcfco.com/192.168.3.53
```
when I change this line address=/cefcfco.com/192.168.3.53
with address=/apps.cefcfco.com/192.168.3.53
The above problem has not appeared.

**Comment by th-lee** [comment]
# vi /etc/resolv.conf

search cluster.local
nameserver 192.168.3.53
nameserver 8.8.8.8

# chattr +i /etc/resolv.conf

then,
master process restart

**Comment by bparees** [comment]
@HP-dufeng is this resolved based on your comment above?

**Comment by afshinpaydar** [comment]
@HP-dufeng It's because when a pod try to resolve "github.com" (for example), add cluster domainname as suffix to the end of query: "github.com.cefcfco.com", "github.com.svc.cefcfco.com", ...
Then dnsmasq resolve all of this query to one IP (for example:192.168.3.53) by this config: `address=/cefcfco.com/192.168.3.53` this lead to "Peer's certificate issuer" Error!
To solve this problem change "dnsmasq.conf" to more specific like this: `address=/apps.cefcfco.com/192.168.3.53`.
