### ISSUE TITLE
Jenkins Build and completionDeadlineSeconds is not working

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#19481]
[provide a description of the issue]

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

##### Steps To Reproduce
1. create a BuildConfig of type JenkinsPipeline
2. Add option `completionDeadlineSeconds: 60` to the spec.

##### Current Result

Nothing, openshift is not taking this into account, like done for example on docker based build : 

https://github.com/openshift/origin/blob/86f9b3689efcfbeffe0574d51f3b07083826a094/pkg/build/controller/strategy/docker.go#L159-L161

##### Expected Result

Build stopped after a certain amount of time if still running,

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by gabemontero** [comment]
Yeah `CompletionDeadlineSeconds` is only supported by the build strategies where the build controller running in openshift is in play

For this to work in Jenkins, with no build controller, etc. in play, we would have to update the sync plugin to check for that value and abort the job if the deadline is exceeded

So the lack of support is not an omission per se

Interesting idea ... but IMO feature request for the sync plugin (https://github.com/openshift/jenkins-sync-plugin)

@chmouel - can you open a trello card at https://trello.com/b/wqe9UaaZ/developer-experience ?  If not, I can, but it would be better if it came from you.

**Comment by gabemontero** [comment]
Short term submitted update to docs to clarify support here.

**Comment by gabemontero** [comment]
Actually, we are just going with the doc restriction.  We'll continue to monitor both upstream and subscription customer usage to see if further demand / requests arise.
