### ISSUE TITLE
Openshift Origin 3.9 - Ansible - WebConsole

### ISSUE THREAD

**Issue by fajnatakibana** [openshift/origin#19480]
I do successful ansible installation of openshift 3.9, but WebConsole not working and i guess not exist.

##### Version

oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server: ***
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce

1. Install WebConsole from playbook

`INSTALLER STATUS *********************************************************************************************************************************************************************************
Initialization             : Complete (0:00:31)
Web Console Install        : Complete (0:00:04)
`
This installation pass and it did not give an effect, 

Next im trying to install a web console from this instruction:
https://github.com/openshift/origin-web-console-server#installing-the-console

But, after this pod with webconsole was in pending state all the time...
with error:
`Warning  FailedScheduling  4s (x8 over 1m)  default-scheduler  0/1 nodes are available: 1 MatchNodeSelector.`

##### Current Result

Project web-console not exist and webpage:
`missing service (service "webconsole" not found)
missing route (service "webconsole" not found)`

##### Expected Result

Working webconsole

_________________________
any ideas?

**Comment by pennpeng** [comment]
you shoud make the master node openshift_schedulable=true, because the webconsole pod would be run on master node。

**Comment by fajnatakibana** [comment]
@pennpeng , In v3.9 master are schedulable by default, to be sure i did the command for making schedulable, and this not take any effect on webconsole :(

**Comment by spadgett** [comment]
@fajnatakibana Can you run this command to see if the masters are correctly labelled and ready?

```
$ oc get nodes -l node-role.kubernetes.io/master=true
```
