### ISSUE TITLE
Feature Request: Rename an application with oc command

### ISSUE THREAD

**Issue by sbuvaneshkumar** [openshift/origin#19495]
Sometimes I need to rename the application that I've created earlier using `oc new-app --name=foo...`.
It's quite a bit time-consuming task to redeploy the application with the desired name.
The other way is to change the definition of service, route, deployconfig etc files just to rename the application.

It would be great if we have a command line option in oc to rename the application. 
Something like `oc rename-app foo bar` ?

**Comment by bparees** [comment]
It's not possible to change kubernetes resource names after creating them so the best we could do is delete and recreate which you can already do yourself so I don't see much value in wrapping that operation. 

See: https://github.com/kubernetes/kubernetes/issues/13629#issuecomment-139041750

/close
