### ISSUE TITLE
openshift Jenkins pipeline build faild at sti build stage 

### ISSUE THREAD

**Issue by luxiangqing** [openshift/origin#19503]
[provide a description of the issue]
I use the openshift jenkins pipeline for source code build and image deploy,but sometimes there are errors at jenkins build logs,but it is normal after rescheduling the build task.this error is accidental, i tried to solve this problem, but did not succeed

The partial jenkins build logs:
[Pipeline] sh
[cicd-ilifesoa-test] Running shell script
+ rm -rf oc-build
+ mkdir -p oc-build/deployments
[Pipeline] sh
[cicd-ilifesoa-test] Running shell script
+ cp /tmp/workspace/iLifeSOA-Dist/iLifeSOA.zip oc-build/deployments/
[Pipeline] sh
[cicd-ilifesoa-test] Running shell script
+ oc delete bc,dc,svc,route -l app=ilifesoa -n dev
buildconfig "ilifesoa" deleted
deploymentconfig "ilifesoa" deleted
service "ilifesoa" deleted
route "ilifesoa" deleted
[Pipeline] sh
[cicd-ilifesoa-test] Running shell script
+ oc new-build --name=ilifesoa --image-stream=weblogic-base-ilifesoa:12.2.1.3-jre8 --binary=true --labels=app=ilifesoa -n dev
--> Found image 9af7021 (3 weeks old) in image stream "openshift/weblogic-base-ilifesoa" under tag "12.2.1.3-jre8" for "weblogic-base-ilifesoa:12.2.1.3-jre8"

    WebLogic 12.2.1.3 for jre8 
    -------------------------- 
    Platform for building and running Java applications on WebLogic 12.2.1.3

    Tags: builder, java, weblogic 12.2.1.3

    * A source build using binary input will be created
      * The resulting image will be pushed to image stream "ilifesoa:latest"
      * A binary build was created, use 'start-build --from-dir' to trigger a new build

--> Creating resources with label app=ilifesoa ...
    error: imagestreams.image.openshift.io "ilifesoa" already exists
    buildconfig "ilifesoa" created
--> Failed
+ true
[cicd-ilifesoa-test] Running shell script
[Pipeline] sh
+ oc start-build ilifesoa --from-dir=oc-build --wait=true -n dev
Uploading directory "oc-build" as binary input for the build ...
Error from server (InternalError): Internal error occurred: error sending request: Post https://szdc04266:10250/attach/dev/ilifesoa-1-build/sti-build?error=1&input=1&output=1: x509: certificate is valid for SZDC04267, 10.6.0.192, not szdc04266
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

##### Version
[provide output of the `openshift version` or `oc version` command]
[root@SZDC04267 ~]# oc version 
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ipaas.openshift.sz.clio:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jwforres** [comment]
@openshift/sig-developer-experience
