### ISSUE TITLE
The HAProxy router should expose prometheus metrics for a route Expected     <float64>: 10 to be >=     <float64>: 20

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#19516]
Seen https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19496/test_pull_request_origin_extended_conformance_gce/19606/#conformanceareanetworkingfeaturerouter-the-haproxy-router-should-expose-prometheus-metrics-for-a-route-suiteopenshiftconformanceparallel

Seems different than https://github.com/openshift/origin/issues/17731

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by bparees** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20176/test_pull_request_origin_extended_conformance_install/12911/

i think it's the same (slightly different expected values):
```
  The HAProxy router
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/metrics.go:82
    should expose prometheus metrics for a route [Suite:openshift/conformance/parallel] [It]
    /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/router/metrics.go:95

    Expected
        <float64>: 20
    to be >=
        <float64>: 40
```
@ironcladlou
