### ISSUE TITLE
Application deployment failing when cluster setup using oc cluster up on Mac

### ISSUE THREAD

**Issue by praveenkumar** [openshift/origin#19528]
##### Version
$ ./oc version
oc v3.10.0-alpha.0+a7199cf-874
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

##### Steps To Reproduce

1. Start the cluster using oc cluster up
```
$ oc cluster up --base-dir /tmp/base --loglevel 10
[...]
The server is accessible via web console at:
    https://127.0.0.1:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

WARNING: An HTTP proxy (docker.for.mac.http.internal:3128) is configured for the Docker daemon, but you did not specify one for cluster up
WARNING: An HTTPS proxy (docker.for.mac.http.internal:3129) is configured for the Docker daemon, but you did not specify one for cluster up
WARNING: A proxy is configured for Docker, however 172.30.1.1 is not included in its NO_PROXY list.
   172.30.1.1 needs to be included in the Docker daemon's NO_PROXY environment variable so pushes to the local OpenShift registry can succeed.
```

2. Deploy an aplication from existing template.
```
$ ./oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git
--> Found Docker image 9edbf3b (9 days old) from Docker Hub for "centos/ruby-22-centos7"

    Ruby 2.2 
[..]
--> Success
    Build scheduled, use 'oc logs -f bc/ruby-ex' to track its progress.
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose svc/ruby-ex' 
    Run 'oc status' to view your app.

$ ./oc logs -f bc/ruby-ex
Cloning "https://github.com/openshift/ruby-ex.git" ...
	Commit:	bbb670185b6ce67294cc461ae9c18710e6f26089 (Merge pull request #18 from durandom/master)
	Author:	Ben Parees <bparees@users.noreply.github.com>
	Date:	Thu Dec 7 14:53:36 2017 -0500
---> Installing application source ...
---> Building your Ruby application from source ...
---> Running 'bundle install --retry 2 --deployment --without development:test' ...
Fetching gem metadata from https://rubygems.org/...............
Installing puma 3.10.0
Installing rack 2.0.3
Using bundler 1.7.8
Your bundle is complete!
Gems in the groups development and test were not installed.
It was installed into ./bundle
---> Cleaning up unused ruby gems ...

Pushing image 172.30.1.1:5000/test/ruby-ex:latest ...
Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: Get http://172.30.1.1:5000/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

##### Current Result
Not able to push to registry.
##### Expected Result
Able to push to registry and application should be deployed.

##### Additional Information
```
 $ docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

CC @mfojtik

**Comment by mfojtik** [comment]
/cc @csrwng 

I think this is a known issue, there is no workaround AFAIK. This is also not a regression, this issue pre-existed the cluster up refactoring.

**Comment by csrwng** [comment]
That is correct. The only known work-around is to downgrade Docker for Mac to version 17.09 or earlier

**Comment by sanjusoftware** [comment]
I am not able make the downgraded version of docker-for-mac to start.. it just gets hung in the starting mode. I am on:
![image](https://user-images.githubusercontent.com/232573/40485842-3df10e38-5f7d-11e8-9f9d-3c7486b19145.png)

and I am trying install version 17.09.0-ce-mac35 build 19611 https://download.docker.com/mac/stable/19611/Docker.dmg

any help will me much appreciated!

**Comment by csrwng** [comment]
@sanjusoftware try resetting docker to factory defaults. See https://docs.docker.com/docker-for-mac/#reset

**Comment by sanjusoftware** [comment]
@csrwng problem is that I am not able to get to that menu at all because as soon as I start docker app, it just doesn't come up

![image](https://user-images.githubusercontent.com/232573/40487017-7fc54326-5f80-11e8-9907-2a7d6b72cf33.png)

I also tried : https://github.com/docker/for-mac/issues/2117#issuecomment-334778824 but to no avail.

**Comment by diegolovison** [comment]
> That is correct. The only known work-around is to downgrade Docker for Mac to version 17.09 or earlier

Do you know exactly what is the Docker version?
The version `Docker version 17.09.1-ce, build 19e2cf6` is not working

**Comment by diegolovison** [comment]
My workaround is:
brew cask install minishift
minishift config set vm-driver virtualbox
minishift start
