### ISSUE TITLE
Openshift v3.9 router seem broken

### ISSUE THREAD

**Issue by ahmadou** [openshift/origin#19527]
[provide a description of the issue]

When i deploy a gitlab image on my cluster it overwrites all the routes i defined and everything resolves to the gitlab service.

##### Version

oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master-lb.xxxxxxxxxxxx:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
deploy  gitlab/gitlab-ce:10.7.1-ce.0  image
configure gitlab instance to listen on route url (external_url 'https://gitlab.xxxxxxx' and provide certificates
define passthrough route for https://gitlab.xxxxxxx.

##### Current Result
The service is working and is accessible but then all the predefined routes (hawkular, kibana etc ... and custom routes) are overrided and everything resolves to gitlab.

As soon as the gitlab route is deleted all other routes resolve to their normal services.
##### Expected Result

gitlab is resolvable but so are the other services.

##### Additional Information
output of : 

```
default                            docker-registry    docker-registry.mycompany                                       docker-registry    5000-tcp           passthrough          None
default                            registry-console   registry-console-default.mycompany                              registry-console   registry-console   passthrough          None
kube-service-catalog               apiserver          apiserver-kube-service-catalog.mycompany                        apiserver          secure             passthrough          None
logging                            logging-kibana     kibana.mycompany                                                logging-kibana     <all>              reencrypt/Redirect   None
openshift-ansible-service-broker   asb-1338           asb-1338-openshift-ansible-service-broker.mycompany             asb                1338               reencrypt            None
openshift-infra                    hawkular-metrics   hawkular-metrics.mycompany                                      hawkular-metrics   <all>              reencrypt            None
pic-outils                         filemanager        filemanager-pic-outils.mycompany                               filemanager        80-tcp             edge                 None
pic-outils                         gitlab             gitlab-pic-outils.mycompany                                    gitlab             443-tcp            passthrough          None

```

oc get all -o json 

https://gist.github.com/ahmadou/e9cee8ce192851ca45050dac4e482300

**Comment by ahmadou** [comment]
For additional information , the routes will continue to work until you connect the first time to the gitlab instance. After that all the request sent from the browser seem to resolve to the gitlab instance.

On the other hand if i open a browser in private mode and open the gitlab instance the problem does not seem to show up.
I guess it's related to cookies or something.
It might be specific to the product but on the other hand i find it strange that the router can get confused by a deployed application and completely broke all the other services.

**Comment by ahmadou** [comment]
The problem seems fixed by setting up gitlab to listen on port 80 and changing the route from passthrough to edge.

I still would like to get an explanation (if possible) to avoid future mistakes.

**Comment by ahmadou** [comment]
Hi,

Do you have some new informations on this ?

**Comment by zachariahtimothy** [comment]
@ahmadou Did you ever discover a resolution to this? I am receiving the same thing.

**Comment by ahmadou** [comment]
Had to change my gitlab settings regarding rproxy configuration. Not at work right now so I can't give you the exact answer
