### ISSUE TITLE
Openshift Origin server 3.9 Failed to get system container stats for "/user.slice/user-0.slice/session-4.scope": failed to get cgroup stats for "/user.slice/user-0.slice/session-4.scope": failed to get container info for "/user.slice/user-0.slice/session-4.scope": unknown container "/user.slice/user-0.slice/session-4.scope"

### ISSUE THREAD

**Issue by sadahamrc** [openshift/origin#19535]
I'm having issues when starting openshift server. When I start it by
./openshift start (as instructed in the origin docs)
it produces this error all the time. (see ##### Current Result)

##### Version
openshift v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16

##### Steps To Reproduce
1. ./openshift start

##### Current Result
I'm getting two errors.
[One]
E0427 12:19:34.473195   11668 summary.go:92] Failed to get system container stats for "/user.slice/user-0.slice/session-4.scope": failed to get cgroup stats for "/user.slice/user-0.slice/session-4.scope": failed to get container info for "/user.slice/user-0.slice/session-4.scope": unknown container "/user.slice/user-0.slice/session-4.scope"

[Two]
E0427 12:19:06.220993   11668 dnsmasq.go:105] unable to periodically refresh dnsmasq status: The name uk.org.thekelleys.dnsmasq was not provided by any .service files

##### Expected Result
Openshift all in one cluster up and running and can be accessible by web console

##### Additional Information
I'm a newbie to openshift/ docker and kube. So I can;t figure out how this error generating. Please help.

**Comment by wenchma** [comment]
I have the same issue:

##Environment info
```
openshift-origin-server-v3.9.0-191fece-linux-64bit
# cat /etc/redhat-release 
CentOS Linux release 7.0.1406 (Core)
# uname -a
Linux i-lwfsocpz 4.16.6-1.el7.elrepo.x86_64 #1 SMP Sun Apr 29 16:50:56 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##Got results

```
E0503 11:51:02.187057   13590 summary.go:92] Failed to get system container stats for "/user.slice/user-0.slice/session-189.scope": failed to get cgroup stats for "/user.slice/user-0.slice/session-189.scope": failed to get container info for "/user.slice/user-0.slice/session-189.scope": unknown container "/user.slice/user-0.slice/session-189.scope"
E0503 11:51:02.388686   13590 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
W0503 11:51:02.389072   13590 reflector.go:341] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:86: watch of *v1beta1.PodSecurityPolicy ended with: The resourceVersion for the provided watch is too old.
```

**Comment by leoterry-ulrica** [comment]
I have the same issue as above. 

Failed to get system container stats for "/user.slice/user-0.slice/session-882.scope": failed to get cgroup stats for "/user.slice/user-0.slice/session-882.scope": failed to get container info for "/user.slice/user-0.slice/session-882.scope": unknown container "/user.slice/user-0.slice/session-882.scope"
E0603 17:36:08.269943    2033 dnsmasq.go:105] unable to periodically refresh dnsmasq status: The name uk.org.thekelleys.dnsmasq was not provided by any .service files

**Comment by slawekgh** [comment]
i have the same issue

**Comment by jamesddube** [comment]
I facing the same issue, trying to install openshift will try dig around and come up with a solution

**Comment by rishikapoor028** [comment]
Did anybody manage to get this resolved, I am facing the same issue.

**Comment by tonylook** [comment]
I have the same issue, can anyone help?

**Comment by spadeq** [comment]
Me 2. Both installation from openshift.tar.gz and YUM source have the same result. I'm so disappointed by RH and considerin' to try CloudFoundry now.

**Comment by Mikedu1988** [comment]
same issue here, also so disappointed

**Comment by vladf3000** [comment]
I had the same issue, then used 'sudo oc cluster up' instead, as recommended [here](https://github.com/openshift/origin/issues/17730)
That showed an error about insecure regisry, so I had to update /etc/docker/daemon.json  as described [here](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md)

**Comment by hsafe** [comment]
I have the same issue i.e with the /user.slice/user-0.slice/session-1.scope and dnsmasq error messages when running the binary openshift start...:(
@openshift team can you guys help us out?What above guys suggested to put in /etc/docker/daemon.json did not do any help for me :(

**Comment by hsafe** [comment]
Btw it is a Centos 7.5 minimal install with openshift 3.10.0 and a hint I could say that the service can be successfully start with oc cluster up...but it is not desired production and can't help complaining that there is no single source of A-z installation and set-up of openshift 3.10 with binary out there ...either they are too old-not applicable to the new modern approach-or otherwise it is the kubeshift /oc cluster up which honestly does not get you far...

**Comment by lbrigman124** [comment]
Same issue on 3.11 with Centos 7.5 every 10 seconds

`
origin-node: E0301 09:48:46.768464    6434 summary.go:102] Failed to get system container stats for "/system.slice/origin-node.service": failed to get cgroup stats for "/system.slice/origin-node.service": failed to get container info for "/system.slice/origin-node.service": unknown container "/system.slice/origin-node.service"
`

**Comment by lbrigman124** [comment]
version: 
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://example.com:8443
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0
uname -a
Linux example.com 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps reproduce:
Single node standup with openshift-ansible playbooks deploy_cluster.yml

**Comment by icheko** [comment]
Is everyone getting this error when using xfs with d_type = 0 ?

I noticed @dove-young's error. I'm going to try to redeploy with d_type = 1 per docker (https://docs.docker.com/v17.09/engine/userguide/storagedriver/overlayfs-driver/#prerequisites) and see if it gets rid of the stats error.

```
[root@OpenShift]# docker info
...
WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
```

**Comment by lbrigman124** [comment]
I'm getting the error cgroup stats error message but I don't have the above warning from docker.
In my case, a reboot of the node cleared the error message.

**Comment by vanloswang** [comment]
I have the same issue on 3.11. you should add some config below ```kubeletArguments``` in ```/etc/origin/node/node-config.yaml```.My fix is as following:
```
# vim /etc/origin/node/node-config.yaml
  runtime-cgroups:
  - /systemd/system.slice
  kubelet-cgroups:
  - /systemd/system.slice
```
do not forget to restart node service.

**Comment by vanloswang** [comment]
This issue should be fix in openshift-ansible. refer to https://github.com/vanloswang/openshift-ansible/commit/cabe815bc1733ba62088fc1c8c04ac0ca8bd0cd7. I CANNOT make a pull request now because github return Ooops with code 500 to me.

**Comment by lejeczek** [comment]
I see the same/similar when I try to deploy a cluster on Centos 7.x with:

openshift-ansible-playbooks-3.11.37-1.git.0.3b8b341.el7.noarch
openshift-ansible-roles-3.11.37-1.git.0.3b8b341.el7.noarch
openshift-ansible-docs-3.11.37-1.git.0.3b8b341.el7.noarch
openshift-ansible-3.11.37-1.git.0.3b8b341.el7.noarch

a cluster off KVM guests, 3 nodes of which 1 is a master, and on all three nodes show:
...
0408 18:32:03.587431   30412 summary.go:102] Failed to get system container stats for "/system.slice/origin-node.service": failed to get cgroup stats for "/system.slice/origin-node.service": failed to get container info for "/system.slice/origin-node.service": unknown container "/system.slice/origin-node.service"
E0408 18:32:13.606530   30412 summary.go:102] Failed to get system container stats for "/system.slice/origin-node.service": failed to get cgroup stats for "/system.slice/origin-node.service": failed to get container info for "/system.slice/origin-node.service": unknown container "/system.slice/origin-node.service"
E0408 18:32:23.612086   30412 summary.go:102] Failed to get system container stats for "/system.slice/origin-node.service": failed to get cgroup stats for "/system.slice/origin-node.service": failed to get container info for "/system.slice/origin-node.service": unknown container "/system.slice/origin-node.service"

Above is logged while deploy_cluster process is working and spits out:
...
FAILED - RETRYING: Verify that the catalog api server is running (57 retries left).
FAILED - RETRYING: Verify that the catalog api server is running (56 retries left).
FAILED - RETRYING: Verify that the catalog api server is running (55 retries left).
FAILED - RETRYING: Verify that the catalog api server is running (54 retries left).
...
