### ISSUE TITLE
mysql/mongodb replica tests failing

### ISSUE THREAD

**Issue by bparees** [openshift/origin#19552]
we're seeing failures in the image ecosystem tests when setting up NFS for PVs:

```
Apr 28 12:32:43.702: INFO: Error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc [oc patch --config=/tmp/e2e-test-mongodb-petset-replica-pkv9v-user.kubeconfig --namespace=e2e-test-mongodb-petset-replica-pkv9v template/mongodb-petset-replication --type json -p [{"op": "test", "path": "/objects/0/kind", "value":"PersistentVolumeClaim"},{"op": "add", "path":"/objects/0/spec/selector", "value": {"matchLabels":{"namespace":"e2e-test-mongodb-petset-replica-pkv9v"}}}]] []   Error from server: Testing value /objects/0/kind failed
 Error from server: Testing value /objects/0/kind failed
```

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/463/testReport/junit/(root)/Extended/_Conformance__image_ecosystem__mongodb__Slow__openshift_mongodb_replication__with_statefulset___should_instantiate_the_template__Suite_openshift_/

/cc @gabemontero

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/463/testReport/

**Comment by bparees** [comment]
actually it looks like maybe the patch errors are benign but the tests are definitely consistently failing.

**Comment by bparees** [comment]
(it's affecting both the mongo and mysql tests, but not the jenkins)

**Comment by coreydaley** [comment]
From taking a quick look at the mysql test, this may be the same issue as the cakephp error, looks like it's failing the readiness probe to localhost (127.0.0.1) also.  I'll try to look deeper into it later tonight.

```
Warning  Unhealthy              3m    kubelet, ip-172-18-11-70.ec2.internal  Readiness probe failed: sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
```

**Comment by coreydaley** [comment]
> actually it looks like maybe the patch errors are benign but the tests are definitely consistently failing.

The test for the patch command shows as failed if it doesn't pass, which is kind of annoying but that is how it works, but that failing won't cause the test to fail.

**Comment by bparees** [comment]
> From taking a quick look at the mysql test, this may be the same issue as the cakephp error, looks like it's failing the readiness probe to localhost (127.0.0.1) also. 

i think the ioctl part is benign but the can't connect certainly isn't (unless that's just an early failure before the pod came up).

i'd be sort of surprised if it was related to the php errors, but i suppose it's possible something changed in pod networking that broke 127.0.0.1 in a weird way.

**Comment by coreydaley** [comment]
Closing as fixed via https://github.com/openshift/origin/pull/19776
