### ISSUE TITLE
Pull fails if remote registry image is deleted even it has already been mirrored

### ISSUE THREAD

**Issue by Schnitzel** [openshift/origin#19554]
We are ImageStreams with remote registries and `referencePolicy.type: Local` and `mirrorpullthrough: true`. Everything works fine, if an image is pulled the first time it is mirrored (visible in the registry logs). But if the image in the remote registry is deleted the local registry also stops working, even the image is fully mirrored. I believe that there is probably still a remote registry manifest check which then causes some issues.

##### Version
```
oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://console-vicsdp.amazeeio.hosting:443
openshift v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. Push Image to Remote Registry, like DockerHub
2. Create ImageStream from remote registry: `oc -n myproject tag --reference-policy=local --source=docker  schnitzel/ssh:latest ssh:latest` 
3. Pull this Image: `docker pull [registry]/myproject/ssh:latest` (all works), also check in registry logs for `Completed mirroring`
4. Delete Image o DockerHub (not only the tag, the whole image)
5. Try to pull again: `docker pull [registry]/myproject/ssh:latest` which will fail now with `Error response from daemon: manifest for [registry]/myproject/ssh:latest not found`

##### Current Result

oc: `Error response from daemon: manifest for [registry]/myproject/ssh:latest not found`\
Registry Logs: `level=error msg="error getting manifest from remote location \"schnitzel/ssh:latest\": manifest unknown: manifest unknown"`

##### Expected Result

Already mirrored image streams and tags can still be pulled even though they are deleted in remote registry

**Comment by legionus** [comment]
> openshift v3.6.173.0.49

Manifest mirroring added in v3.10.0-alpha.0 [1]. Prior to this, only blobs were mirrored. This was done to speed up the work, and not for fault tolerance.

[1] https://github.com/openshift/image-registry/commit/263bb041308286023c43973c5accafdbbeb113ed

**Comment by dmage** [comment]
in v3.9.0-alpha.4. Please update your cluster at least to 3.9.

**Comment by Schnitzel** [comment]
@legionus @dmage awesome, thank you :)
