### ISSUE TITLE
Can't upgrade from 3.7 to 3.9 via ansible

### ISSUE THREAD

**Issue by hdonati** [openshift/origin#19560]
Hi,
I'm trying to upgrade our cluster from 3.7 to 3.9. It had been installed with ansible, so I'm using the same method to perform upgrade.

It fails with message : 
      _1. Hosts:    oomaster1.in.ac-caen.fr
         Play:     Determine openshift_version to configure on first master
         Task:     assert openshift_release in openshift_image_tag
         Message:  openshift_image_tag must match same major version as openshift_release. You provided: 3.8 and v3.9_

How could I get rid of that and perform the upgrade ?

Thanks in advance

##### Version
CentOS Linux release 7.4.1708 (Core)

oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://oomaster1.in.ac-caen.fr:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
ansible-playbook openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade.yml
(with same /etc/ansible/hosts used to install 3.7)

##### Current Result
fatal: [oomaster1.in.ac-caen.fr]: FAILED! => {
    "assertion": "openshift_release in openshift_image_tag",
    "changed": false,
    "evaluated_to": false,
    "msg": "openshift_image_tag must match same major version as openshift_release. You provided: 3.8 and v3.9\n"
}

##### Expected Result
Upgrade to 3.9.0

##### Additional Information
oadm diagnostics shows only 2 WARNs : 
_WARN:  [DClu1012 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:298]
       The pod logs for the "docker-registry-5-vkkpd" pod belonging to
       the "docker-registry" service indicated unknown errors.
       This could result in problems with builds or deployments.
       Please examine the log entries to determine if there might be
       any related problems:
...
WARN:  [DH0005 from diagnostic MasterConfigCheck@openshift/origin/pkg/diagnostics/host/check_master_config.go:52]
       Validation of master config file '/etc/origin/master/master-config.yaml' warned:
       assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
       oauthConfig.identityProvider[0].provider.insecure: Invalid value: true: validating passwords over an insecure connection could allow them to be intercepted
...
_

**Comment by hdonati** [comment]
In -vvv mode : 
```
...
TASK [openshift_version : debug] *************************************************************************************************************************************************************************
task path: /root/openshift-ansible-3.9/roles/openshift_version/tasks/first_master.yml:55
ok: [oomaster1.in.ac-caen.fr] => {
    "openshift_image_tag": "v3.9"
}
...
TASK [set_fact] ******************************************************************************************************************************************************************************************
task path: /root/openshift-ansible/playbooks/common/openshift-cluster/upgrades/pre/version_override.yml:14
ok: [oomaster1.in.ac-caen.fr] => {
    "ansible_facts": {
        "openshift_release": "3.8",
        "openshift_upgrade_min": "3.7",
        "openshift_upgrade_target": "3.8",
        "openshift_version": "3.8"
    },
    "changed": false
}
```
(Please note that /root/openshift-ansible is a symlink to /root/openshift-ansible-3.9)

openshift_image_tag remains v3.9 while openshift_release is then set to 3.8

So it can't work. Did I forget or misunderstand Something ?

**Comment by jwforres** [comment]
@openshift/sig-cluster-lifecycle

**Comment by sdodson** [comment]
Do you have both the 3.8 and 3.9 repos enabled on the hosts?

**Comment by hdonati** [comment]
@sdodson 
No version mention in repo on the master :
```
[root@oomaster1 ~]# cat /etc/yum.repos.d/CentOS-OpenShift-Origin.repo
[centos-openshift-origin]
name=CentOS OpenShift Origin
baseurl=http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS

[centos-openshift-origin-testing]
name=CentOS OpenShift Origin Testing
baseurl=http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/
enabled=0
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/openshift-ansible-CentOS-SIG-PaaS

[centos-openshift-origin-debuginfo]
name=CentOS OpenShift Origin DebugInfo
baseurl=http://debuginfo.centos.org/centos/7/paas/x86_64/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/openshift-ansible-CentOS-SIG-PaaS

[centos-openshift-origin-source]
name=CentOS OpenShift Origin Source
baseurl=http://vault.centos.org/centos/7/paas/Source/openshift-origin/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/openshift-ansible-CentOS-SIG-PaaS
```
This was, I presume, populated by ansible 3.7 install.
Same thing on nodes, except thar repos are all enabled.
Do I need to enable all repos on master ?

**Comment by hdonati** [comment]
I git cloned branch release-3.9 either than latest  and this error disappeared. Upgrade could go on, even if I have another issue later (I will open another ticket)
Consider this one as closed
