### ISSUE TITLE
nvidia-device-plugin fails with unknown capability and permission denied on nvidia.sock creation

### ISSUE THREAD

**Issue by jonkstevenson** [openshift/origin#19575]
Using the following blog as a starting point:

https://blog.openshift.com/use-gpus-with-device-plugin-in-openshift-3-9

I was able to work through everything but the deployment of the nvidia-device-plugin is failing.

##### Version

oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxxxxx.:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce

Followed step by step the blog instructions and everything worked as expected up until the deployment phase.

##### Current Result

 Error: failed to start container "nvidia-device-plugin-ctr": Error response from daemon: linux spec capabilities: Unknown capability to add: "CAP_*"

##### Expected Result
 oc logs nvidia-device-plugin-daemonset-s9ngg
2018/01/23 10:39:30 Loading NVML
2018/01/23 10:39:30 Fetching devices.
2018/01/23 10:39:30 Starting FS watcher.
2018/01/23 10:39:30 Starting OS watcher.
2018/01/23 10:39:30 Starting to serve on /var/lib/kubelet/device-plugins/nvidia.sock
2018/01/23 10:39:30 Registered device plugin with Kubelet

##### Additional Information

Now if I execute on the system itself the container:
 docker run --security-opt=no-new-privileges --cap-drop=ALL --network=none -it -v /var/lib/kubelet/device-plugins:/var/lib/kubelet/device-plugins nvidia/k8s-device-plugin:1.9

2018/05/01 12:51:35 Loading NVML
2018/05/01 12:51:35 Fetching devices.
2018/05/01 12:51:35 Starting FS watcher.
2018/05/01 12:51:35 Starting OS watcher.
2018/05/01 12:51:35 Could not start device plugin: listen unix /var/lib/kubelet/device-plugins/nvidia.sock: bind: permission denied
2018/05/01 12:51:35 Could not contact Kubelet, retrying. Did you enable the device plugin feature gate?
2018/05/01 12:51:35 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2018/05/01 12:51:35 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start

However if i check the node config and yaml:

kubeletArguments:
  node-labels:
  - region=Oregon
  - zone=gpu
  feature-gates:
  - DevicePlugins=true

and I can see that the socket got created:

ls -l /var/lib/kubelet/device-plugins/kubelet.sock
srwxr-xr-x. 1 root root 0 May  1 08:26 /var/lib/kubelet/device-plugins/kubelet.sock

So not sure where to proceed,

Thanks,
Jon

**Comment by jonkstevenson** [comment]
Just on a side note:

The docker configuration looks good:

[root@awslosedgpu1 lib]# docker run  -e NVIDIA_VISIBLE_DEVICES=all --rm debian:stretch nvidia-smi
Unable to find image 'debian:stretch' locally
Trying to pull repository registry.access.redhat.com/debian ...
Trying to pull repository docker.io/library/debian ...
stretch: Pulling from docker.io/library/debian
cc1a78bfd46b: Pull complete
Digest: sha256:de3eac83cd481c04c5d6c7344cd7327625a1d8b2540e82a8231b5675cef0ae5f
Status: Downloaded newer image for docker.io/debian:stretch
Tue May  1 12:57:50 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   29C    P8    15W / 150W |      0MiB /  7618MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

and

docker run -it --rm docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done

**Comment by ravisantoshgudimetla** [comment]
cc @zvonkok

**Comment by jwforres** [comment]
@openshift/sig-pod

**Comment by jeremyeder** [comment]
Yeah, apparently @zvonkok can reproduce this...

**Comment by ravisantoshgudimetla** [comment]
@jeremyeder It happened with us too but I removed `defaultAddCapabilities` and the error has gone away, I have not reached a stage where we could test the GPU pod successfully yet.(It is getting scheduled though).

**Comment by jonkstevenson** [comment]
okay excuse me for my absence from the conversation. When I really thought I was crazy and completely thrashed the cluster. Took some time to rebuild.

I am presently again at those errors presented above.

Additional info:  @jeremyeder  I did remove the defaultAddCapabilities  and that did remove the error. However, when the device plugin is deployed the pod crashes over and over again with.

nvidia-device-plugin-ctr_6.log
[root@ip-10-6-67-18 573c9c2e-4ef7-11e8-a72b-0acc000744d0]# cat nvidia-device-plugin-ctr_6.log
{"log":"2018/05/03 17:33:54 Loading NVML\n","stream":"stderr","time":"2018-05-03T17:33:54.18776412Z"}
{"log":"2018/05/03 17:33:54 Fetching devices.\n","stream":"stderr","time":"2018-05-03T17:33:54.192718764Z"}
{"log":"2018/05/03 17:33:54 Starting FS watcher.\n","stream":"stderr","time":"2018-05-03T17:33:54.19900536Z"}
{"log":"2018/05/03 17:33:54 Failed to created FS watcher.\n","stream":"stderr","time":"2018-05-03T17:33:54.200239488Z"}

Docker Version:

docker-1.13.1-58.git87f2fab.el7.x86_64

Note:  all commands still work to verify nvidia driver 

[root@ip-10-6-67-18 573c9c2e-4ef7-11e8-a72b-0acc000744d0]# docker run -it --rm docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
[root@ip-10-6-67-18 573c9c2e-4ef7-11e8-a72b-0acc000744d0]# docker run -e NVIDIA_VISIBLE_DEVICES=all --rm debian:stretch nvidia-smi
Thu May  3 17:39:24 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   30C    P8    15W / 150W |      0MiB /  7618MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
[root@ip-10-6-67-18 573c9c2e-4ef7-11e8-a72b-0acc000744d0]#

**Comment by jeremyeder** [comment]
can you run ```ls -alZ /dev/nvidia*``` on ip-10-6-67-18 please?

**Comment by jonkstevenson** [comment]
Now here's a twist.

Usually number by number by but just tried to do this:

apiVersion: v1
kind: Pod
metadata:
 name: cuda-vector-add
 namespace: nvidia
spec:
 restartPolicy: OnFailure
 containers:
   - name: cuda-vector-add
     image: "docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1"
     env:
       - name: NVIDIA_VISIBLE_DEVICES
         value: all
       - name: NVIDIA_DRIVER_CAPABILITIES
         value: "compute,utility"
       - name: NVIDIA_REQUIRE_CUDA
         value: "cuda>=8.0"

And I got:

[root@ip-10-6-67-33 nvidia]# oc logs po/cuda-vector-add
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done


DAMN THING RAN LIKE A CHAMP!!!!!!

**Comment by jonkstevenson** [comment]
I would have to boot backup the gpu system.
But did follow the documentation and executed: chcon -t container_file_t  /dev/nvidia*

If found that the changes aren't persistent across reboots.  But if I fail to do this, the container will not start.

As you saw though in my post, I am able to get GPU containers both scheduled and running correctly now without the use of the nvidia plugin pod.  In my case, I have a zone dedicated to gpu(s) so I set the nvidia namespace up with a specific zone selection of gpu.   Everything appears to be working.

I can boot up the box if this isn't what you were looking for by your question.

**Comment by php-coder** [comment]
> Using the following blog as a starting point:
> https://blog.openshift.com/use-gpus-with-device-plugin-in-openshift-3-9

Unfortunately, the SCC from the blog is incorrect and that's why you have this error.

```yaml
defaultAddCapabilities:
- '*'
```
Specifying this makes no sense, because these values are passed to a container runtime directly. So, essentially, it invokes Docker with `--cap-app CAP_*` parameter.

**Comment by jeremyeder** [comment]
We fixed some things in the 3.9 blog, and for the 3.10 version we stopped embedding the yaml files in the blog itself, and now store them in git (linked in the blog).

I'm going to close this now.  Please run through the 3.10 howto blog, and report any feedback.

https://blog.openshift.com/how-to-use-gpus-with-deviceplugin-in-openshift-3-10/
