### ISSUE TITLE
Cmd test fails "github.com/openshift/origin/test/cmd/newapp test/cmd/newapp.sh:428: executing 'oc delete all -l app=testapp2' expecting success 1.66s"

### ISSUE THREAD

**Issue by adambkaplan** [openshift/origin#19587]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jwforres** [comment]
@adambkaplan was this a test flake in CI or an issue you hit locally, if it was in CI please include a link to the job where you saw it

**Comment by jwforres** [comment]
actually is this a duplicate of https://github.com/openshift/origin/issues/19588 ?

**Comment by adambkaplan** [comment]
yes...not clear how this was posted twice...
