### ISSUE TITLE
pod-to-service communication is broken and got "No route to host" error for both Origin v3.6.0 and v3.7.1

### ISSUE THREAD

**Issue by yychy** [openshift/origin#19597]
[provide a description of the issue]

In Origin v3.6.0 or Origin v3.7.1 pod, we cannot connect to any services in the project and got "No route to host" error. But after restart origin node service, sometimes it works.

##### Version
[provide output of the `openshift version` or `oc version` command]

# openshift version
openshift v3.7.1+c2ce2c0-1
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8

# oc v3.7.1+c2ce2c0-1
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.7.1+c2ce2c0-1
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. create sample app in a project
2. oc rsh <app_pod> and curl -v <service_ip>:port, got No route to host
3. restart origin node service in the pod node, and repeat above, sometimes it works

##### Current Result
cannot connect (curl) to any service:port with error

##### Expected Result
can connect (curl) to any service:port without any issue

##### Additional Information
iptables in pod node is not updated for some reason. After restart app node, then iptables is OK

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by yychy** [comment]
can someone help to answer this question or suggestion

**Comment by sbht04** [comment]
The main root cause of our issue here is that kube-proxy that runs on every node is not updating the IP tables when a new "pod" is created. However when a new service is created,  IP tables are updated to reflect the IP address of this new service.

The kube-proxy is running in the "iptables" mode See below the settings from node-config.yaml file
proxyArguments:
  proxy-mode:
     - iptables

How do we mitigate this issue? How do we get kube-proxy to update all the routing tables rules?
Any suggestion? Or Feedback?

**Comment by sbht04** [comment]
@knobunc Do you have any suggestions or feedback for this issue

**Comment by knobunc** [comment]
What network plugin are you using?  My bet is that you are using the docker default, and hairpin mode is not set on the docker bridge, so when the natted service traffic comes back to the same pod, the bridge drops it.

**Comment by sbht04** [comment]
We are using redhat/openshift-ovs-multitenant as our Network Plugin..How do we check hairpin mode on the docker bridge?

**Comment by sbht04** [comment]
@knobunc  We have Hairpin Mode set to None (see below the sample log output from Origin Node). Docker cri networking managed by cni. What else are we missing here?? Any other suggestions or feedback for this issue

May 31 12:58:52 node1.abc.com origin-node[51331]: I0531 12:58:52.816305   51331 server.go:838] Using root directory: /var/lib/origin/openshift.local.volumes
May 31 12:58:52 node1.abc.com origin-node[51331]: I0531 12:58:52.816343   51331 kubelet.go:271] Watching apiserver
May 31 12:58:52 node1.abc.com origin-node[51331]: I0531 12:58:52.819049   51331 sdn_controller.go:261] AddHostSubnetRules for node1.abc.com (host: "node1.abc.com", ip: “xx.xx.xxxx.xx”, subnet: “xx.xxx.xx.x/xx”)
May 31 12:58:52 node1.abc.com origin-node[51331]: I0531 12:58:52.820328   51331 kubelet.go:507] Hairpin mode set to "none"
May 31 12:58:52 node1.abc.com origin-node[51331]: I0531 12:58:52.820682   51331 plugins.go:196] Loaded network plugin "cni"
May 31 12:58:52 node1.abc.com origin-node[51331]: I0531 12:58:52.835010   51331 plugins.go:196] Loaded network plugin "cni"
May 31 12:58:52 node1.abc.com origin-node[51331]: I0531 12:58:52.835099   51331 docker_service.go:209] Docker cri networking managed by cni

**Comment by yychy** [comment]
In the link, https://github.com/kubernetes/kubernetes/issues/44187, mentioned "In v1.6, kubernetes no longer configures hairpin mode. hairpin mode should now be configured by the 3rd-party CNI plugin in use.". So, in our Origin 3.6 or 3.7, CNI is openshift-sdn. does this CNI support "hairpin mode"? do you or someone have any idea how to configure openshift origin CNI plug-in's"hairpin mode"?

**Comment by sbht04** [comment]
@knobunc  Do you have any suggestions or feedback for this issue?

**Comment by johnarok** [comment]
It looks like there is a stalled listener.. we added some logging to the shared_informer and we see the length of the pending notifications queue keeps increasing at the range of 2000 to 5000+..  Any suggestions on how to debug this further? are we looking at the right code path for endpoints?  I have asked this question on kubernetes-dev slack as well, waiting for reply.

**Comment by johnarok** [comment]
Removing egress policies in the cluster allowed the endpoints changes to be propagated immediately on the nodes. thank you @knobunc @jwforres for checking on this, will open a new issue with detailed steps to reproduce when we get to it.
