### ISSUE TITLE
oc cluster up with --enable=service-catalog is failing

### ISSUE THREAD

**Issue by jmontleon** [openshift/origin#19590]
docker exec -it `origin pod` /bin/bash
oc logs -f -n kube-service-catalog                `apiserver pod` -c apiserver

The apiserver pod shows:
```
Error: unknown flag: --admission-control
The main API entrypoint and interface to the storage system. The API server is
also the focal point for all authorization decisions.
Usage:
  apiserver [flags]
```

##### Version
oc v3.10.0-alpha.0+2075da4-930
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.17.0.1:8443
openshift v3.10.0-alpha.0+2075da4-930
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. oc cluster up with --enable=service-catalog

##### Current Result
oc cluster up fails

##### Expected Result
oc cluster up works

##### Additional Information
oc edit deployment.apps/apiserver and remove --admission-control option and the apiserver and controller-manager pods come up.

https://github.com/openshift/origin/blob/master/examples/service-catalog/service-catalog.yaml#L44

**Comment by jmontleon** [comment]
It looks like there is a new option:
--admission-control-config-file string                    File with admission control configuration.

I guess this might need to be created and pointed at.

**Comment by jwforres** [comment]
cc @pmorie

**Comment by magick93** [comment]
Hi

Is there any updates to this?

I'm getting the following"
```
oc cluster  add --enable=service-catalog,metrics
Error: unknown flag: --enable
```

## Version
```
 oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
```
