### ISSUE TITLE
whats the canonical way to wire the api server REST endpoint into pods/containers via services or env vars?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#196]
So we've a [console in fabric8](http://fabric8.io/v2/runFabric.html#start-fabric8) that works off the kubernetes/openshift REST API to view whats running etc. 

I can imagine a few other containers needing access (e.g. management / monitoring containers, for activemq clusters to view all the containers present so they can store/forward between them or custom auto-scalers etc).

Right now we've hard coded a host/port into our config.json which feels kinda dirty ;).
https://github.com/fabric8io/fabric8/blob/2.0/apps/fabric8.json#L32

I wonder is there a more canonical way to make it available to containers without having to make everything a template? e.g. via an environment variable (like we can use to find the services) or as a kind of kubernetes service (if there was maybe a magic port number that kube-proxy could wire to)?

Is there already some way to do this; or is it intended for JSON files to be specific to a single openshift environment - so hard coding of the API Server is OK?

**Comment by smarterclayton** [comment]
Also we now have DNS (openshift.default.local resolves).  Marking fixed.
