### ISSUE TITLE
SandboxChanged Pod sandbox changed. StopPodSandbox x from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod x network: could not retrieve port mappings: checkpoint is not found.

### ISSUE THREAD

**Issue by Misterhex** [openshift/origin#19604]
We are seeing pods not getting rescheduled and getting stuck after encountering the event "SandboxChanged    Pod sandbox changed, it will be killed and re-created"

What I noticed was these pods are emitting this event in a loop ( 288883 count ) and getting stuck

“openshift-infra            4m          44d          288883    hawkular-metrics-5t5cs.151d5bb4148eb74f                Pod                                                Normal    SandboxChanged          kubelet, xxx   Pod sandbox changed, it will be killed and re-created.”

Describing this pod from oc, show us that this pod is still in the “Running” phrase although its containers has terminated with non-zero error. Also, restart count for the container is zero.

Name:           hawkular-metrics-5t5cs
Status:         Running
Containers:
  hawkular-metrics:
    State:          Terminated
      Reason:       Error
      Exit Code:    1
    Ready:          False
    Restart Count:  0

// Systemd logs

May 2nd 2018, 20:57:49.000	W0502 20:57:49.419343    8140 docker_sandbox.go:337] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "hawkular-metrics-5t5cs_openshift-infra": CNI failed to retrieve network namespace path: Cannot find network namespace for the terminated container "c961845a87f53f72f8212f92cd2f0306ac4906216216452df693e5b0d7d21405"	atomic-openshift-node.service

May 2nd 2018, 20:57:49.000	W0502 20:57:49.425423    8140 cni.go:258] CNI failed to retrieve network namespace path: Cannot find network namespace for the terminated container "c961845a87f53f72f8212f92cd2f0306ac4906216216452df693e5b0d7d21405"	atomic-openshift-node.service

May 2nd 2018, 20:57:49.000	time="2018-05-02T20:57:49.427331285+08:00" level=error msg="Handler for POST /v1.24/containers/c961845a87f53f72f8212f92cd2f0306ac4906216216452df693e5b0d7d21405/stop returned error: Container c961845a87f53f72f8212f92cd2f0306ac4906216216452df693e5b0d7d21405 is already stopped"	docker.service

May 2nd 2018, 20:57:49.000	E0502 20:57:49.427946    8140 remote_runtime.go:114] StopPodSandbox "c961845a87f53f72f8212f92cd2f0306ac4906216216452df693e5b0d7d21405" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "hawkular-metrics-5t5cs_openshift-infra" network: could not retrieve port mappings: checkpoint is not found.	atomic-openshift-node.service

May 2nd 2018, 20:57:49.000	E0502 20:57:49.428118    8140 kuberuntime_manager.go:775] Failed to stop sandbox {"docker" "c961845a87f53f72f8212f92cd2f0306ac4906216216452df693e5b0d7d21405"}	atomic-openshift-node.service

##### Version

OpenShift Master:
v3.7.14
Kubernetes Master:
v1.7.6+a08f5eeb62

##### Current Result
Pod stuck.

##### Expected Result
Pod should be rescheduled.

**Comment by jwforres** [comment]
@openshift/sig-pod

**Comment by sjenning** [comment]
fyi @dcbw 

I would delete that Node i.e oc get node <node>, which will cause all the pods on it to be deleted and restarted elsewhere (since a drain will not work as the pod sanboxes are blocked from terminating cleanly), stop the node service, delete everything from under /var/lib/dockershim where the CNI checkpoint files reside on the node, and restart the node service so it will re-register with the master. 

That should get the node back into working order.

**Comment by Misterhex** [comment]
@sjenning Thanks for your help. Has this bug been fixed in 3.9? Thanks.

**Comment by Misterhex** [comment]
@sjenning you mentioned to delete everything under '/var/lib/dockershim', do you know what the directory structure would be like for 'overlay2'? 

are there any articles/documentations about CNI checkpoints files and where they reside?

many thanks.

**Comment by Misterhex** [comment]
@sjenning would it be possible to disable checkpoints?

**Comment by sjenning** [comment]
> are there any articles/documentations about CNI checkpoints files and where they reside?

No, they are a well kept secret unfortunately

> would it be possible to disable checkpoints?

No. Checkpointing is needed by the CNI in order to re-associate network resources with pods in the event of a node/kubelet restart.

**Comment by Misterhex** [comment]
@sjenning it seems like we are running the "kubelet" (atomic.node) in a container and the "/var/lib/dockershim" folder was not mount on the host machine, in the event of container restart, the checkpoint files are lost.  Could this be the issue you would envision? Thanks.

**Comment by Misterhex** [comment]
We resolved the issue by bind mounting "/var/lib/dockershim" in atomic-kubelet-node container to the host "/var/lib/dockershim"

**Comment by bilalcaliskan** [comment]
@Misterhex hi!

I've been struggling with that problem about 1 week and i use OKD 3.11 . In OKD, there is sync pods which runs on openshift nodes as daemonset, and it mounts /etc/origin/node, /var/lib/origin etc. So i guessed that non-atomic version of your case is sync pods, so i have mounted /var/lib/dockershim to the sync daemonset. I have not seen the problem so far, i hope it was the right solution. Do you have any idea what cause that kind of problem?
