### ISSUE TITLE
Cannot access master readiness URL on oc cluster up

### ISSUE THREAD

**Issue by ashearer23** [openshift/origin#19614]
I am trying to run OpenShift Origin on my CentOS 7.4 behind a corporate firewall and a static IP address. I have the server and the client tools tar files unzipped on my machine and 'oc' added to my PATH.

##### Version
oc v3.9.0+191fece

##### Steps To Reproduce
1. oc cluster up --http-proxy='...' --https-proxy='...' --public-hostname='MACHINE'S IP'

##### Current Result
Using nsenter mounter for OpenShift volumes
Using public hostname IP ... as the host IP
Using ... as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://IP:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0503 17:57:07.022156    3013 status_manager.go:140] Starting to sync pod status with apiserver
     I0503 17:57:07.022169    3013 kubelet.go:1768] Starting kubelet main sync loop.
     I0503 17:57:07.022179    3013 kubelet.go:1779] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
     I0503 17:57:07.022260    3013 volume_manager.go:248] Starting Kubelet Volume Manager
     E0503 17:57:07.022475    3013 container_manager_linux.go:584] [ContainerManager]: Fail to get rootfs information unable to find data for container /
     I0503 17:57:07.025810    3013 controller.go:538] quota admission added evaluator for: { events}
     W0503 17:57:07.060018    3013 lease_endpoint_reconciler.go:176] Resetting endpoints for master service "kubernetes" to [IP]
     I0503 17:57:07.122707    3013 kubelet_node_status.go:296] Setting node annotation to enable volume controller attach/detach
     I0503 17:57:07.124746    3013 kubelet_node_status.go:82] Attempting to register node localhost
     I0503 17:57:07.128176    3013 kubelet_node_status.go:85] Successfully registered node localhost

   Caused By:
     Error: Get https://IP:8443/healthz/ready: Access Denied

**Comment by praveenkumar** [comment]
@ashearer23 You might have to add your server IP in no proxy to make sure when oc cluster up makes the request to check server status it doesn't go through the proxy.

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by ashearer23** [comment]
Thank you @praveenkumar, that worked!

**Comment by patrickHub** [comment]
Thanks @praveenkumar, it's also work for me.
