### ISSUE TITLE
Docker build failed :No route to host

### ISSUE THREAD

**Issue by MohamedElso** [openshift/origin#19626]
Hi All,
i hope someone can give me some suggestions for this I have this error when i try to build docker file 
it stuck at this step:
==========
RUN yum install -y php-cli.x86_64
# RUN yum install -y php-common.x86_64 ## Should already be there installing cli

ENV HTTP_PROXY= HTTPS_PROXY= http_proxy= https_proxy=
======
here some info  
==============
openshift v3.7.42
kubernetes v1.7.6+a08f5eeb62

====================
here is the error 
===================
---> Running in c549e7a0ef34
--
  | Loaded plugins: fastestmirror, ovl
  |  
  | One of the configured repositories failed (Unknown),
  | and yum doesn't have enough cached data to continue. At this point the only
  | safe thing yum can do is fail. There are a few ways to work "fix" this:
  | 1. Contact the upstream for the repository and get them to fix the problem.
  | 2. Reconfigure the baseurl/etc. for the repository, to point to a working
  | upstream. This is most often useful if you are using a newer
  | distribution release than is supported by the repository (and the
  | packages for the previous distribution release still work).
  | 3. Run the command with the repository temporarily disabled
  | yum --disablerepo=<repoid> ...
  | 4. Disable the repository permanently, so yum won't use it by default. Yum
  | will then just ignore the repository until you permanently enable it
  | again or use --enablerepo for temporary usage:
  | yum-config-manager --disable <repoid>
  | or
  | subscription-manager repos --disable=<repoid>
  | 5. Configure the failing repository to be skipped, if it is unavailable.
  | Note that yum will try to contact the repo. when it runs most commands,
  | so will have to try and fail each time (and thus. yum will be be much
  | slower). If it is a very temporary problem though, this is often a nice
  | compromise:
  | yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
  | Cannot find a valid baseurl for repo: base/7/x86_64
  | Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
  | 14: curl#7 - "Failed connect to xyz:80; No route to host"
  | error: build error: The command '/bin/sh -c yum install -y php-cli.x86_64' returned a non-zero code: 1

Thanks

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
How are you building it? And can you provide your dockerfile?

**Comment by MohamedElso** [comment]
Hi ,
i am build from inside openshift , kind: BuildConfig

here is the dockerfile 
======
FROM docker.elastic.co/logstash/logstash:6.2.3

USER root
RUN yum install -y php-cli.x86_64
# RUN yum install -y php-common.x86_64 ## Should already be there installing cli

ENV HTTP_PROXY= HTTPS_PROXY= http_proxy= https_proxy=

RUN chgrp -R 0 /usr/share/logstash && \
    chmod -R g+w /usr/share/logstash && \
	echo "" > /usr/share/logstash/config/logstash.yml

**Comment by MohamedElso** [comment]
Hi,
xyz:80 is the proxy url.
P.S : just replace any critical data by "xyz"
this my buildConfig.yaml

==================
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: ''
  labels:
    build: elastash
  name: elastash
  namespace: elastic-connector
  resourceVersion: '23164912'
  selfLink: /oapi/v1/namespaces/xyz/buildconfigs/elastash
  uid: xyz
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'elastash:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'http://xyz/elastash.git'
    type: Git
  strategy:
    dockerStrategy:
      env:
        - name: http_proxy
          value: 'http://xyz:80'
      from:
        kind: ImageStreamTag
        name: 'logstash:6.2.3'
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: xyz
      type: GitHub
    - generic:
        secret: xyz
      type: Generic
    - imageChange:
        lastTriggeredImageID: >-
          docker.elastic.co/logstash/logstash@xyz
      type: ImageChange
    - type: ConfigChange
status:
  lastVersion: 26

====

Thanks

**Comment by bparees** [comment]
can I see the full output from your build log?  preferably using --build-loglevel=5


it seems like your "env http_proxy=" line is not clearing out the http_proxy env var you are setting in your buildconfig, i'd like to see which is being processed first.

**Comment by MohamedElso** [comment]
Cloning "http://xyz/elastash.git" ...
	Commit:	xyz (add proxies)
	Author:	
	Date:	
Step 1 : FROM docker.elastic.co/logstash/logstash@xyz
 ---> 5ce052f3ad18
Step 2 : ENV "HTTP_PROXY" "http://xyz:80/" "HTTPS_PROXY" "http://xyz:80/" "NO_PROXY" "
 ---> Using cache
 ---> 218ff1879986
Step 3 : USER root
 ---> Using cache
 ---> 214e3c4cb425
Step 4 : ENV HTTP_PROXY xyz:80 HTTPS_PROXY xyz:80 http_proxy xyz:80 https_proxy xyz:80
 ---> Using cache
 ---> 02673ba4a007
Step 6 : RUN yum install -y php-cli.x86_64
 ---> Running in 39e0afa48374
Loaded plugins: fastestmirror, ovl

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:
     1. Contact the upstream for the repository and get them to fix the problem.
     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).
     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...
     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:
            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>
     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:
            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
Cannot find a valid baseurl for repo: base/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#7 - "Failed connect to xyz:80; No route to host"
error: build error: The command '/bin/sh -c yum install -y php-cli.x86_64' returned a non-zero code: 1

**Comment by bparees** [comment]
are you sure your dockerfile says
```
ENV HTTP_PROXY= HTTPS_PROXY= http_proxy= https_proxy=
```

because this log would imply otherwise:
```
Step 4 : ENV HTTP_PROXY xyz:80 HTTPS_PROXY xyz:80 http_proxy xyz:80 https_proxy xyz:80
```

Also the commit message for the commit the build cloned says:
```
Commit: xyz (add proxies)
```

So I strongly suspect your dockerfile doesn't say what you think it says.

**Comment by MohamedElso** [comment]
yes, I am sure even if I added the proxy url directly inside the dockerfile it is not working also, i don't know if it is a network problem or something else, related to yum Repo. in the machine , or proxy policy block the traffic.
Thanks

**Comment by bparees** [comment]
Adding the proxy url *is* the problem.

```
"Failed connect to xyz:80; No route to host"
```

means your docker network cannot reach your proxy host.

I thought you were trying to *unset* the proxy.  If you are trying to make sure all your yum traffic goes through that proxy, then you need to sort out why your docker containers are unable to resolve "xyz".
