### ISSUE TITLE
New feature request for Cluster-Loader to support passing option "--skip-config-write=true" when creating new projects

### ISSUE THREAD

**Issue by wabouhamad** [openshift/origin#19628]
Need cluster-loader (test/extended/cluster/cl.go) to supporting passing the option "--skip-config-write=true" when creating new projects with oc new-project command.  This will accelerate the time it takes to create large number of projects during scale and system tests.

##### Version
oc v3.10.0-0.32.0
openshift v3.10.0-0.32.0
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. Create 500+ projects.  
2. This is a new feature request.  Need to be able to pass from command line or from config yaml file the option "--skip-config-write=true" in the argument list to call to oc new-project, line: https://github.com/openshift/origin/blob/master/test/extended/cluster/cl.go#L97.
With "--skip-config-write=true", the project will not be set as a cluster entry in kubeconfig after being created.

##### Current Result
Bulk project creation (500+) can take several hours to create
##### Expected Result
The "--skip-config-write=true" option to oc new-project call, will help reduce project creation time especially when creating 500+ projects
##### Additional Information
Support for parallelism will also greatly reduce bulk project creation time.

**Comment by jwforres** [comment]
@openshift/sig-scalability

**Comment by sjug** [comment]
Hey @wabouhamad is there any reason this shouldn't be the default for project creation?

**Comment by mffiedler** [comment]
@sjug It should be the default.   Having it set to false puts the user into the context of the new project which is good for interactive, but unnecessary for automation and scripts.

**Comment by wabouhamad** [comment]
@sjug we can probably wait for the concurrency PR to merge if it is close to completion

**Comment by sjug** [comment]
Closing, created PR https://github.com/openshift/origin/pull/19645

**Comment by sjug** [comment]
@wabouhamad @mffiedler Can you please review and /lgtm the PR?
