### ISSUE TITLE
 TASK [openshift_version : Get available origin version]  pkg_version['release'] = pkg_info[1] IndexError: list index out of range

### ISSUE THREAD

**Issue by Kisen-Chin** [openshift/origin#19633]
[root@master ~]# openshift version
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16

[root@master ~]# oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.example.com:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
[root@master ~]# 

I have master and three nodes. And during the installation, I got such error:
TASK [openshift_version : Get available origin version] *********************************************************************************************************************
ok: [node.example.com]
ok: [node2.example.com]
fatal: [node1.example.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to node1.example.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_xNhav1/ansible_module_repoquery.py\", line 642, in <module>\r\n    main()\r\n  File \"/tmp/ansible_xNhav1/ansible_module_repoquery.py\", line 632, in main\r\n    rval = Repoquery.run_ansible(module.params, module.check_mode)\r\n  File \"/tmp/ansible_xNhav1/ansible_module_repoquery.py\", line 588, in run_ansible\r\n    results = repoquery.repoquery()\r\n  File \"/tmp/ansible_xNhav1/ansible_module_repoquery.py\", line 552, in repoquery\r\n    processed_versions = Repoquery.process_versions(rval['results'].strip())\r\n  File \"/tmp/ansible_xNhav1/ansible_module_repoquery.py\", line 475, in process_versions\r\n    pkg_version['release'] = pkg_info[1]\r\nIndexError: list index out of range\r\n", "msg": "MODULE FAILURE", "rc": 1}

It seems my master node and node node2 are ok. But node1 failed with this error. Could someone figure out why this happens?

**Comment by jwforres** [comment]
@openshift/sig-cluster-lifecycle

**Comment by Kisen-Chin** [comment]
Hi, I found my node2 is centos 7.4 and other nodes are 7.3.  I reinstalled my node2 to be 7.3 and the issue don't happen again. Maybe the system version cause this issue?

**Comment by sdodson** [comment]
@Kisen-Chin That shouldn't cause this problem. It was likely a temporary repository problem, the error message is less than helpful but I don't think this is a reproducible problem.

**Comment by billyfoss** [comment]
I ran into this during a test build last night.  

TASK [openshift_version : Get available origin version] ************************
Wednesday 23 May 2018  05:16:09 +0000 (0:00:00.055)       0:00:24.059 ********* 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [oshiftmaster-10-10-14-7.mydomain....com]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_olcxlB/ansible_module_repoquery.py\", line 642, in <module>\n    main()\n  File \"/tmp/ansible_olcxlB/ansible_module_repoquery.py\", line 632, in main\n    rval = Repoquery.run_ansible(module.params, module.check_mode)\n  File \"/tmp/ansible_olcxlB/ansible_module_repoquery.py\", line 588, in run_ansible\n    results = repoquery.repoquery()\n  File \"/tmp/ansible_olcxlB/ansible_module_repoquery.py\", line 552, in repoquery\n    processed_versions = Repoquery.process_versions(rval['results'].strip())\n  File \"/tmp/ansible_olcxlB/ansible_module_repoquery.py\", line 475, in process_versions\n    pkg_version['release'] = pkg_info[1]\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

This environment is running CentOS 7.5 with openshift-ansible-3.9.29.  

I'm going to run the job again (hoping it was just another temporary repo issue and not reproducible)

**Comment by billyfoss** [comment]
Following up...
I reran the job and did not see the error again.

**Comment by amon-ra** [comment]
@billyfoss  same problem here but I rerun and it is not fixed. Anyone has a solution

**Comment by amon-ra** [comment]
I have solved! It was a DNS error, changed DNS and got working. Hope it helps anyone that came here

**Comment by fabiomartinelli** [comment]
same problem here

**Comment by brynjellis** [comment]
I'm getting the same issue.  @amon-ra when you say "changed DNS and got working" what did you change please?

I'm running scaleup.yml on  an existing production cluster and getting the same error.  Not had this problem before and I've run scaleup many times.
