### ISSUE TITLE
Separate identityProvider name from the login screen name

### ISSUE THREAD

**Issue by calston** [openshift/origin#19634]
The 'name' field of an identityProvider is used in the login template.

Currently there seems no way to separate these two things, so you get ugly provider names in the login screen unless you rewrite the whole template, or use a pretty name as the name (which limits your choice of names and grammar).

There should be a "display name" or some such field to let people customise how an identity provider is shown to the user. Unless of course there is already one and the parameter is just not documented anywhere at all

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by enj** [comment]
The expectation is that you customize the template as you see fit (either via Go code or JS).  There are no plans to add a "display name" field to the identity providers struct.

**Comment by calston** [comment]
Seems excessive to require people write a custom login screen for such a simple thing

**Comment by simo5** [comment]
It's just a tweak of existing templates, not a whole new log-in screen.
