### ISSUE TITLE
dc.status returns stale data

### ISSUE THREAD

**Issue by containscafeine** [openshift/origin#19644]
Retrieving the replica count in 2 different ways returns different results.

```console
$ oc get pods    
NAME                         READY     STATUS    RESTARTS   AGE                            
jenkins-5-vbzpn              1/1       Running   0          29m                            
               
$ oc get dc      
NAME                 REVISION   DESIRED   CURRENT   TRIGGERED BY                           
jenkins              5          1         1         config                                 

$ oc export dc jenkins
...
redacted
...
status:               
  availableReplicas: 0                       
  latestVersion: 0    
  observedGeneration: 0                      
  replicas: 0         
  unavailableReplicas: 0                     
  updatedReplicas: 0  
```

So dc.status does not return the current state of the Deployment Config. The pods are up and running and healthy, the expected replica count is 1, but dc.status returns 0.

##### Version
```
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.starter-us-east-2.openshift.com:443
openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657
```

CC: @jaseemabid

**Comment by mfojtik** [comment]
@containscafeine does it eventually update? it might that just the controller is slow updating the DC state.

**Comment by jaseemabid** [comment]
@mfojtik We were playing around on a relatively low load cluster and the update did not propagate for at least 15 minutes. Would you want us to wait longer and check if it will eventually happen or is 15m too long anyway? Happy to help! :+1:

**Comment by tnozicka** [comment]
use `oc get dc <name> -o yaml` if you want to see the status.

```
oc export -h
Export resources so they can be used elsewhere.
...
Fields that cannot be specified on create will be set to empty
...
The status part of objects is also cleared.
```

/close

**Comment by containscafeine** [comment]
@tnozicka ah, got it. But then `oc export` should not even print the `dc.status` field because that is printing incorrect information which is very misleading for the end user. Is there an issue to remove the status field for `oc export` output altogether?

**Comment by jaseemabid** [comment]
@tnozicka I'd expect export to either return the correct value or return nothing at all. This is quite non intuitive and i'd say is a bug.

**Comment by mfojtik** [comment]
@containscafeine @jaseemabid i agree it looks bad, but the status field is not optional and thus the serializer will default all fields when exporting the object. The export is more suitable when you want to backup and then restore (apply/create) the object again, where the status does not matter at all. If you want to introspect the YAML of the resource, the `oc get -o yaml` will get you want you want.

/cc @soltysh @juanvallejo

**Comment by containscafeine** [comment]
@mfojtik the field not being optional and hence printing default values, is an implementation detail, which should be fixed so as to not output incorrect information to the end user. The point is to not return incorrect information, right?
The status field could be explicitly deleted after serialization, WDYT?
IMO, printing incorrect information to the user is a pretty serious bug.

**Comment by soltysh** [comment]
`oc export` is deprecated, in favor of `oc get --export`.

**Comment by jaseemabid** [comment]
@soltysh Returning wrong information even through a deprecated command seems wrong imo. We could just delete the keys after the serialization step?

**Comment by jaseemabid** [comment]
Can we please reopen this till the command either returns no data or the correct data? "Its said in the manual" or "the serializer does so" are both not good enough arguments to return incorrect data.
