### ISSUE TITLE
Unable to resolve proxy from git clone of openshift-jee-sample repo

### ISSUE THREAD

**Issue by ashearer23** [openshift/origin#19640]
I have Origin 3.9 installed on my CentOS 7.4 VM and I am trying to install the sample Java project in Wildfly

##### Version
openshift v3.9.0+d0f9aed-12
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Go to webconsole
2. Select Wildfly
3. click Next
4. Add to an open project
5. for the Git Repository, just under it click 'try Sample Repository' and it is auto filled with: https://github.com/openshift/openshift-jee-sample.git and the App name is auto filled with: openshift-jee-sample
6. Click Create and it will say it was successful, but when I go to the project I added it to, it failed with the following error:

Cloning "https://github.com/openshift/openshift-jee-sample.git " ...
--
  | error: fatal: unable to access 'https://github.com/openshift/openshift-jee-sample.git/':  Could not resolve proxy: [PROXY IS HERE]; Unknown error

**Comment by jwforres** [comment]
do any of the examples work? sounds like a problem with your default proxy settings

@openshift/sig-developer-experience

**Comment by ashearer23** [comment]
Looks like I didn't have git installed on the machine. once I installed it and configured the global http and https proxies it worked.
