### ISSUE TITLE
openshift stuck at cloning a repo 

### ISSUE THREAD

**Issue by Kisen-Chin** [openshift/origin#19646]
Cloning "https://github.com/nichochen/mybank-demo-maven.git " ...
  | Commit:	5f550ef361dc1abad8a32a00334a327f3e713568 (Fix Chinese characters)
  | Author:	Geng Chen <nicosoftware@msn.com>
  | Date:	Thu Aug 25 23:30:23 2016 +0800

I want to build a simple java app on openshift web console. But after create project->add to project -> select wildfly -> filled github repo url ->start build and deploy, it stucks at cloning as above. 
Can anyone figure out how to solve such problem?
I can clone the repo from my either master or node, but stucks at openshift web console.

[root@master mybank-demo-maven]# openshift version
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16

**Comment by dempile** [comment]
I have the same problem

Cloning "https://github.com/openshift/openshift-jee-sample.git" ...
--
 pulling image "openshift/wildfly-101-centos7@sha256:e6b024745274fc786155a5103fbe4913bbfe1d5c51a31bd7f634a08c3b012750" timed out after 2m0s

**Comment by Kisen-Chin** [comment]
more log here:
Cloning "https://github.com/nichochen/mybank-demo-maven.git " ...
	Commit:	5f550ef361dc1abad8a32a00334a327f3e713568 (Fix Chinese characters)
	Author:	Geng Chen <nicosoftware@msn.com>
	Date:	Thu Aug 25 23:30:23 2016 +0800
pulling image error : pulling image "docker.io/openshift/wildfly-101-centos7@sha256:e6b024745274fc786155a5103fbe4913bbfe1d5c51a31bd7f634a08c3b012750" timed out after 2m0s
error: build error: unable to get docker.io/openshift/wildfly-101-centos7@sha256:e6b024745274fc786155a5103fbe4913bbfe1d5c51a31bd7f634a08c3b012750

**Comment by Kisen-Chin** [comment]
But the main problem is that git clone is so slow...if I git clone directly on master or slave node, the speed is fast . But if I use web console to deploy, the git clone could be very very slow.

**Comment by jwforres** [comment]
the web console isn't doing anything special here, everything is happening on the backend, its just streaming the build logs to the console

if you get the logs for that same build through the CLI, does it still look stuck?

@openshift/sig-developer-experience @openshift/sig-user-interface

**Comment by bparees** [comment]
based on this:

```
pulling image error : pulling image "docker.io/openshift/wildfly-101-centos7@sha256:e6b024745274fc786155a5103fbe4913bbfe1d5c51a31bd7f634a08c3b012750" timed out after 2m0s
error: build error: unable to get docker.io/openshift/wildfly-101-centos7@sha256:e6b024745274fc786155a5103fbe4913bbfe1d5c51a31bd7f634a08c3b012750
```

it is not the clone that is timing out, it is docker attempting to pull an image.  Can you successfully pull this image from your docker daemon on your host nodes?

**Comment by Kisen-Chin** [comment]
Hi, I think the git clone now works fine. Maybe these days I have poor network. Thanks your help on this issue.
