### ISSUE TITLE
Privileged pod cannot write to hostPath volume

### ISSUE THREAD

**Issue by travisn** [openshift/origin#19649]
In OpenShift a privileged pod cannot write to a `hostPath` mounted volume. The pod is denied access from any writes. The writes are denied if the scc constraints `allowHostDirVolumePlugin` and `allowPrivilegedContainer` are set to `true`. 

It is entirely possible that some policy is missing on the cluster role, although when the policies are set as described above, even `system:admin` hits this issue.

##### Version
```
$ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://192.168.99.115:8443
kubernetes v1.10.0
```

##### Steps To Reproduce
- `oc edit scc restricted`
```
# set the following flags:
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
```
- Create a privileged pod that mounts a hostPath. Here is an [example pod](https://gist.github.com/travisn/4c59b34cc2f9fc146e61cb47b79c2c72).
- `kubectl create -f privileged-host-path.yaml`
- `kubectl exec -it priveleged-host-path sh`
- From inside the pod:
```
/ $ cd /var/lib/myhost/
/var/lib/myhost $ mkdir mydir
mkdir: can't create directory 'mydir': Permission denied
```

##### Current Result
Write access denied

##### Expected Result
Successful writes

**Comment by travisn** [comment]
This really does look like an issue with the `restricted` scc. When using the `privileged` scc, the writes succeed to the host path volume. Now to find what needs to be added to the scc...

**Comment by travisn** [comment]
Ok, i found that setting the following on the restricted scc allows the pod to be created:
```
runAsUser:
  type: RunAsAny
```

Is there a more restrictive policy that would be better to use? If not, we can close this.

**Comment by simo5** [comment]
Not clear to me why you would modify the restrictive SCC instead of creating a new one, but seem like there is nothing to be actually solved in this issue, so closing.
Thanks.
