### ISSUE TITLE
Could not create Openshift Configuration

### ISSUE THREAD

**Issue by rvm8h** [openshift/origin#19651]
Starting a clean install of Openshift Origin V3.7.2  I got the following error.
 Error: could not create OpenShift configuration

##### Steps To Reproduce
oc cluster up 

##### Current Result
Image pull complete
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.7.2 image ... 
   Pulling image openshift/origin:v3.7.2
   Pulled 1/4 layers, 26% complete
   Pulled 1/4 layers, 45% complete
   Pulled 1/4 layers, 63% complete
   Pulled 2/4 layers, 77% complete
   Pulled 3/4 layers, 87% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 127.0.0.1 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
FAIL
   Error: could not create OpenShift configuration
   Caused By:
     Error: cannot start container 3aa5149efdc13f3d082a356e6d00d770a93669b33c49c4c7baed61b47bc7e371
     Caused By:
       Error: Error response from daemon: {"message":"linux mounts: Could not find source mount of /var/lib/origin/openshift.local.volumes"}

##### Expected Result
Openshift cluster up 

##### Additional Information
oc v3.7.2+282e43f
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO
Centos 7
docker   Version:      18.05.0-ce-rc1

**Comment by system-dev-formations** [comment]
Sorry  I am using the latest version of Docker which is not suitable for Openshift now.

**Comment by rvm8h** [comment]
Ok, you should use docker version docker-ce-17.09.1.ce-1.el7.centos, this version of docker is the latest for running Openshift 
ATTENTION: If you do a `yum -y update,` your docker version is upgraded and Openshift doesn't work anymore.
