### ISSUE TITLE
Memory disparity, possible leak. 

### ISSUE THREAD

**Issue by mdunnerelx** [openshift/origin#19652]
Description:

When examining memory utilization I see a disparity between what open shift reports via hawkular, and what docker stats reports. This creates issues when setting resource limits. 

##### Version

oc version
oc v3.7.2+282e43f
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://openshift-master.els-ols.com:443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce

Deploy app. 
Examine metrics in hawkular and docker stats xxxx --no-stream

##### Current Result

Memory usage as shown by hawkular is higher than what docker stats reports. 

##### Expected Result

hawkular and docker stats to be in sync. 

##### Additional Information
<img width="1158" alt="stats" src="https://user-images.githubusercontent.com/37843876/39769595-9daf7dc0-52ba-11e8-8ffe-6f9619675111.png">

<img width="1425" alt="stats" src="https://user-images.githubusercontent.com/37843876/39769527-75558a90-52ba-11e8-9d66-c64b6b2d44e7.png">

**Comment by DirectXMan12** [comment]
There's an "issue" with stats reporting for build pods, but that's somewhat expected.  Can you clarify what exactly the issue is?  Are the hawkular stats always showing the limit?  You'll need to provide more details.
