### ISSUE TITLE
helm cannot connect to tiller in openshift

### ISSUE THREAD

**Issue by wenchma** [openshift/origin#19661]
helm cannot connect to Tiller server  installed by openshift tiller-template

##### Version
```
# oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.9.0+d0f9aed-12
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
1. 
```
# oc process -f https://github.com/openshift/origin/raw/master/examples/helm/tiller-template.yaml -p TILLER_NAMESPACE="${TILLER_NAMESPACE}" | oc create -f -
```
2. 
```
# helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
E0509 17:50:55.277646   21142 portforward.go:331] an error occurred forwarding 34815 -> 44134: error forwarding port 44134 to pod 23218498b118f61b87e8e747bb354c64e71997edc551533790d5b2ea63782764, uid : exit status 1: 2018/05/09 09:50:55 socat[21147] E connect(5, AF=2 10.35.0.2:44134, 16): Connection refused
Error: cannot connect to Tiller

```

##### Current Result
Error: cannot connect to Tiller

##### Expected Result
success to connect to Tiller

##### Additional Information
```
# oc rollout status deployment tiller
deployment "tiller" successfully rolled out

# oc get all
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/tiller   1         1         1            1           1h

NAME                   DESIRED   CURRENT   READY     AGE
rs/tiller-654999c4c8   1         1         1         1h

NAME                         READY     STATUS    RESTARTS   AGE
po/tiller-654999c4c8-n6n8s   1/1       Running   0          1h
```

**Comment by djzager** [comment]
My belief is that you will have to specifically target the namespace in which tiller resides in helm. Example: 

```
helm version --tiller-namespace=${TILLER_NAMESPACE}
```

**Comment by djzager** [comment]
I can confirm that you must supply the `--tiller-namespace` argument to helm.

```
$ oc process -f https://github.com/openshift/origin/raw/master/examples/helm/tiller-template.yaml -p TILLER_NAMESPACE="myproject" | oc create -f -
serviceaccount "tiller" created
role.authorization.openshift.io "tiller" created
rolebinding.authorization.openshift.io "tiller" created
deployment.extensions "tiller" created

$ oc get all -n myproject
NAME                          READY     STATUS    RESTARTS   AGE
pod/tiller-6996dfff85-kj75f   1/1       Running   0          32s

NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/tiller   1         1         1            1           32s

NAME                                DESIRED   CURRENT   READY     AGE
replicaset.apps/tiller-6996dfff85   1         1         1         32s

$ helm version --tiller-namespace=myproject
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
```

**Comment by jwforres** [comment]
@wenchma if this answers your question please close the issue

@openshift/sig-developer-experience

**Comment by wenchma** [comment]
it works for the following running cmd:
```
# helm version --tiller-namespace tiller --host 172.17.0.2:44134
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
```

**Comment by wenchma** [comment]
@djzager  I have another problem,  any idea ? Thanks.
```
# helm install -n nginx nginx --debug
[debug] SERVER: "172.17.0.2:44134"

[debug] Original chart version: ""
[debug] CHART PATH: /root/helm/docs/examples/nginx

Error: the server has asked for the client to provide credentials
````

**Comment by djzager** [comment]
@wenchma I'm glad that I was able to help out, even if only a little bit. I have played around with helm & tiller in OpenShift to have know what is needed for helm to be able to communicate with tiller, but I do not have a whole lot of experience with specific helm charts (or even what this specific error message is trying to tell you). According to [Helm's listed support channels(https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#support-channels), you can find the `#Helm-users` room in the [Kubernetes Slack](http://slack.kubernetes.io/). That room will be filled with people who have the knowledge/experience to better assist you going forward.

**Comment by wenchma** [comment]
@jim-minter  I see your blog [getting-started-helm-openshift](https://blog.openshift.com/getting-started-helm-openshift/), it's very good for a beginner.  Do you run into the problem of installing helm chart ? Do I also need to modify `.kube/config` or other config ?  thanks.

**Comment by wenchma** [comment]
@djzager thanks for your msg, it's very helpful 👍

**Comment by jim-minter** [comment]
I've retested the instructions at https://blog.openshift.com/getting-started-helm-openshift/ on a clean openshift cluster, with both helm 2.6.1 and 2.9.0.  Both worked fine.
Make sure you are using the same version of the helm client and tiller server - in your comment above there's a mismatch (2.6.1 / 2.8.2).  I wouldn't be surprised if that's causing the `server has asked for the client to provide credentials` error.
If you are not using 2.6.1, when you deploy tiller set the HELM_VERSION parameter to the version you are using (it defaults to 2.6.1):

`oc process -f https://github.com/openshift/origin/raw/master/examples/helm/tiller-template.yaml -p TILLER_NAMESPACE="${TILLER_NAMESPACE}" -p HELM_VERSION="v2.9.0" | oc create -f -`

**Comment by jim-minter** [comment]
I have updated the blog post to reference 2.9.0 seeing as 2.6.1 was a little stale.

**Comment by wenchma** [comment]
@jim-minter thanks for your reply, it very benefits me. 👍
