### ISSUE TITLE
AWS: Creating LoadBalancer service fails if more than one SGs with same `kubernetes.io/cluster/openshift-cluster` tag are attached to worker nodes

### ISSUE THREAD

**Issue by jjo** [openshift/origin#19666]
[provide a description of the issue]
Creating a Service `type=LoadBalancer` in AWS fails if worker nodes have more than one SG with same 
`kubernetes.io/cluster/openshift-cluster` tag, error message:

```
Error creating load balancer (will retry): failed to ensure load balancer for service default/router: Multiple tagged security groups found for instance i-[...]; ensure only the k8s security group is tagged
```

This was reported in Kubernetes upstream at kubernetes/kubernetes#23339 , fixed 2 years ago by kubernetes/kubernetes#23340

##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://x.x.x.x:8443
openshift v3.9.25
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Deploy OpenShift 3.9 on AWS, attach more than one SG with `kubernetes.io/cluster/openshift-cluster` tag to worker nodes
2. Try adding/patching a Service as `type=LoadBalancer`, it will fail with below error
##### Current Result
```
$ oc describe svc <service_name>
[...]
Error creating load balancer (will retry): failed to ensure load balancer for service default/router: Multiple tagged security groups found for instance i-[...]; ensure only the k8s security group is tagged
```
##### Expected Result
```
[...]
$ oc describe svc <service_name>
  Normal  EnsuringLoadBalancer  6m (x2 over 8m)  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   6m (x2 over 8m)  service-controller  Ensured load balancer

```
##### Additional Information
Workaround: let only one of the SGs attached to worker nodes to have the `kubernetes.io/cluster/openshift-cluster` tag, LB service creation will retry and succeed.

**Comment by jwforres** [comment]
@openshift/sig-networking
