### ISSUE TITLE
Unable to log into Jenkins pod

### ISSUE THREAD

**Issue by ashearer23** [openshift/origin#19669]
When I installed the Jenkins application to its own pod and go to the provided route I get the login screen for Jenkins, but I don't have a login that I know of for this service.

##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Install the Jenkins service to a project
2. go to the project you installed jenkins to
3. click the route provided
4. try to log in

##### Current Result
no login credentials so I can't login
##### Expected Result
log into Jenkins

**Comment by enj** [comment]
You log in with your OpenShift credentials.

cc @gabemontero

**Comment by gabemontero** [comment]
@enj is correct .... use the same login you use for entering the openshift console ... or if you are only using the cli, run `oc whomai` and use that ID

**Comment by gabemontero** [comment]
reopen if you still have questions @ashearer23 after processing the responses from @enj and myself
