### ISSUE TITLE
RFE:  Need ability to specify multiple protected registry credentials for all nodes in cluster at a global scope

### ISSUE THREAD

**Issue by jwmatthews** [openshift/origin#19690]
I'm looking for the ability to configure multiple protected image registries at a global basis for entire cluster, so all nodes would be given the credentials and able to pull from the protected registries....i.e. I don't want to limit credentials to ImagePullSecrets linked to specific service accounts and/or namespaces.  

I'm looking for ability to configure at a global scope credentials so anyone on the cluster is able to create a Pod and pull down a protected image.  

The UseCase I'm targetting is related to the Service Catalog and Automation Broker serving APBs  from the partner registry, Red Hat Connect ISV registry (registry.connect.redhat.com).  This will likely also impact ~3.11 once the terms based registry is available.

Partner/ISVs are creating 'APBs'  (https://github.com/ansibleplaybookbundle) and after certification, they are published in the partner side of the redhat registry, currently registry.connect.redhat.com.  This registry requires a token to pull images.

I want to provide credentials to talk to the Red Hat Connect ISV registry and allow any user on the cluster to be able to pull images from it.

The issue we are trying to solve is when the Automation Broker is discovering all certified and published APBs from the partner registry, it informs the Service Catalog of each available APB.  The Service Catalog makes those entries available at a cluster scope in ClusterServiceClasses.  It is expected any user is able to provision one of those ClusterServiceClasses into their namespace.  For cases when the referenced image has not yet been pulled to the cluster I need to ensure that the pull of the protected image will be successful, i.e. I won't know which service account/namespace ahead of time to load ImagePullSecrets into.

Today we have a short-term workaround of ssh'ing to each node and executing a "docker login" along with copying the credentials into /var/lib/origin/.docker/ for the kubelet.

This issue is for requesting a better long-term solution that does not rely on configuring the host, as per @smarterclayton 

@liggitt @deads2k @bparees @jwforres @sdodson @derekwaynecarr 

@openshift/sig-ansible-service-broker

**Comment by deads2k** [comment]
> This issue is for requesting a better long-term solution that does not rely on configuring the host, as per @smarterclayton

Not configuring the host seems like more of a statement about how you're putting the credentials on the node today (SSH) than a statement about the node/kubelet being the wrong place to indicate which set of credentials to use.

You're describing a credential for pulling an image that the pod creator does not own, does not set, and does not logically require visibility to.  It is exactly the use-case that we created the kubelet level credentials to solve.  Having a kubelet level credential allows a registry to be secured without a user being aware of the credential being used on their behalf.

I can imagine a few different ways to plumb a credential to the kubelet (secret reference from a node-group kubelet config, token request using the kubelet's credentials, file stamped out with node group bootstrapping credentials, etc), but all of them involve the kubelet having the secret and the user never even knowing it was used.

**Comment by sdodson** [comment]
@smarterclayton Create a configmap for docker/config.json then have the node sync pod land it in /var/lib/origin/.docker/config ?

**Comment by jwmatthews** [comment]
cc @mhrivnak

**Comment by sdodson** [comment]
/close
Fixed in https://github.com/openshift/openshift-ansible/pull/9717
