### ISSUE TITLE
Unable to run maven on Jenkins-Persistent pod

### ISSUE THREAD

**Issue by rvm8h** [openshift/origin#19696]
I installed Jenkins persistent out-of-the Openshift origin catalog,  I am unable to use Maven (mvn) on that pod. 
I checked in Manage Jenkins -> Configure System this is a kubernetes  Pod Templates with a name Maven referencing a container template `docker.io/openshift/jenkins-slave-maven-centos7:v3.9 ` but that's all. 

##### Version
Jenkins 2.89.4 core and libraries:
##### Steps To Reproduce
install Jenkins from a Openshift Origin Catalog

##### Current Result
Error mvn  not found

##### Expected Result
mvn found 

##### Additional Information
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.9.0+d0f9aed-12
kubernetes v1.9.1+a0ce1bc657
docker Version:      17.09.1-ce

**Comment by rvm8h** [comment]
Ok,I found this issue I have to install Maven manually from Jenkins using  Manage Jenkins -> Global Tool Configuration

**Comment by jwforres** [comment]
closing since it sounds like you resolved your issue
