### ISSUE TITLE
Easy way to check login status via OC?

### ISSUE THREAD

**Issue by flightofthunder** [openshift/origin#19705]
Hello, I am looking for a concise way to verify that a user is currently logged in to the OC client. I have been using `oc status` as this gives me the following error when I am l logged out `error: You must be logged in to the server`

However, after I've logged in once, and subsequently logout and try `oc logout`, I no longer get the error and instead get `You don't have any projects. Contact your system administrator to request a project.`

I am looking for a more reliable and concise command to verify the current authentication status that will tell me clearly whether I am logged in or not via the oc client.

Version info :
```
oc v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
features: Basic-Auth
```

**Comment by jwforres** [comment]
`oc whoami`

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by liggitt** [comment]
yes, `oc whoami`

/close

**Comment by flightofthunder** [comment]
Thanks, that works better.

Is it the expected behaviour for `oc status` to still display `You don't have any projects. Contact your system administrator to request a project.` **after** I've logged in and the subsequently logged out?
