### ISSUE TITLE
can't run scripts due to permission denied

### ISSUE THREAD

**Issue by Kisen-Chin** [openshift/origin#19701]
When I deploy myself images to openshift, it can't run script due to permission denied.

##### Version
[root@master rct]# openshift version
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16

##### Steps To Reproduce
this is my image's Dockerfile:

```
FROM centos

COPY ./jdk7.rpm /tmp
COPY ./Tomcat6.tar.gz /tmp

WORKDIR /tmp
RUN yum install -y jdk7.rpm && \
    rm -rf jdk7.rpm && \
    tar -zvxf Tomcat6.tar.gz && \
    rm -rf Tomcat6.tar.gz

WORKDIR /tmp/Tomcat6/webapps
COPY ./rct.war ./ 
RUN chmod 777 ./rct.war 

WORKDIR /tmp/Tomcat6/bin
RUN chmod 777 * 

EXPOSE 8080
CMD ["/bin/bash" , "startup.sh"]
```

I use this Dockerfile to generate a image and pushed it into openshift registry.

Then I use 'user-2/password' to create a project named 'rct'
```
[root@master rct]# oc whoami
user-2
[root@master rct]# oc project
Using project "rct" on server "https://master:8443".
```

But when I deploy this image, it said permission denied like this:
```
startup.sh: line 64: /tmp/Tomcat6/bin/catalina.sh: Permission denied
--
  | startup.sh: line 64: exec: /tmp/Tomcat6/bin/catalina.sh: cannot execute: Permission denied
```

 But if I directly use docker exec to run this script, it can run successfully.

So I did some search on web and found one thing called scc and I ran command like this:
`oc adm  policy add-scc-to-user privileged -z default -n rct`
I added the rct project's default user privileged permission.

But it still failed due to permission denied.
Could anyone help me on this?

##### Current Result
Failed due to permission denied
##### Expected Result
should deploy successfully

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by simo5** [comment]
sounds more for @mrunalp team  ?

**Comment by Kisen-Chin** [comment]
I solved this issue .
It's not due to can't run script
The root cause is I can't access /tmp/Tomcat6 this dir.
Thanks all of you and close this issue.
