### ISSUE TITLE
Flake: [Conformance][Area:Networking][Feature:Router] router headers The HAProxy router should set Forwarded headers appropriately

### ISSUE THREAD

**Issue by vrutkovs** [openshift/origin#19718]
Fails a lot during `ci/openshift-jenkins/gcp` tests:

[Conformance][Area:Networking][Feature:Router] router headers The HAProxy router should set Forwarded headers appropriately [Suite:openshift/conformance/parallel] 1m21s

go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\[Conformance\]\[Area\:Networking\]\[Feature\:Router\]\srouter\sheaders\sThe\sHAProxy\srouter\sshould\sset\sForwarded\sheaders\sappropriately\s\[Suite\:openshift\/conformance\/parallel\]$'

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/8360/test_pull_request_openshift_ansible_extended_conformance_gce_39/275/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/8361/test_pull_request_openshift_ansible_extended_conformance_gce_39/276/

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by jpeeler** [comment]
This is the same as #19887

**Comment by jpeeler** [comment]
Fixed now.
