### ISSUE TITLE
ImageStream poll with webhook

### ISSUE THREAD

**Issue by barakbd** [openshift/origin#19724]
Is there a way to trigger an ImageStream update with a webhook from third party registry (non-OpenShift)?

##### Version
OpenShift Master:
v3.6.173.0.49
Kubernetes Master:
v1.6.1+5115d708d7
 
Sorry if this is not the right place to ask. I would appreciate being referred to the correct forum.

**Comment by bparees** [comment]
Not a webhook per se.

The typical solution is to just used scheduled imports so the imagestream polls the external registry for updates.

If you want to force an imagestream to refresh/import, you can create an imagestreamimport object via the openshift rest api:
https://docs.openshift.org/latest/rest_api/apis-image.openshift.io/v1.ImageStreamImport.html
