### ISSUE TITLE
[NetworkPolicy] Deny all works on every project but one

### ISSUE THREAD

**Issue by SS-TT** [openshift/origin#19735]
I'm trying to use NetworkPolicy with a [default-deny](https://github.com/redhat-cop/openshift-toolkit/blob/master/networkpolicy/policies/baseline/default-deny.yml) policy.

From my understanding this policy should prevent *any* traffic to *any* pod, and this is exactly what happens on all of my projects. For one of them, however, it doesn't.

This project contains 2 .Net Core apps (frontend + backend) and 1 MySQL Database, both the web apps are exposed on public network with a route.

Once the policy is applied, only the frontend is blocked while the backend can still be reached from the external network and it can still execute queries on the db, meaning that database's traffic is not blocked either.

##### Version

> oc v3.9.0+ba7faec-1
> kubernetes v1.9.1+a0ce1bc657
> features: Basic-Auth GSSAPI Kerberos SPNEGO
> 
> Server -
> openshift v3.9.0+ba7faec-1
> kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. `oc apply -f default-deny.yml -n myNamespace`
2. `curl http://my-webapp.mynamespace.svc/swagger`

##### Current Result
`curl` returns the html page for Swagger on the backend.
Backend can still be reached with a browser and it can execute queries on the database.

##### Expected Result
`curl` should exit with an error about the host not being reachable (I don't remember the exact error).
Backend should not be reachable with a browser and it should not be able to execute queries on the database.

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jwforres** [comment]
@openshift/sig-networking
