### ISSUE TITLE
[RFE] Egress static ip enhancements

### ISSUE THREAD

**Issue by mcelep** [openshift/origin#19758]
Egress static IP enhancements
##### Version
3.9
##### Current Result
Current Egress static IP solution has the following limitation:

> Egress IPs are implemented as additional IP addresses on the primary network interface, and must be in the same subnet as the node’s primary IP

##### Expected Result
Egress static IP solution should be configurable for IP's that are not on the primary network and/or in the same subnet as the node’s primary IP. Customers want to be able to set different IP's as egress source that are part of different VLANs.

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by ddeimeke** [comment]
This is driven by us, since our network zoning concept uses several VLANs to separate application traffic. OpenShift App nodes have a bonded interface configured with the VLANs needed.

**Comment by git001** [comment]
How about to add the `host network` permission to a squid dc and set the `source ip` in squid?
This requires a own squid image.

**Comment by danwinship** [comment]
closing this; customer RFEs should go in bugzilla, not github (and this has already also been filed in bugzilla)
