### ISSUE TITLE
Deployment Config does not work for Windows

### ISSUE THREAD

**Issue by rajatchopra** [openshift/origin#19751]
##### Version
3.9

##### Steps To Reproduce
1. Create new-app with a windows based pod

##### Current Result

The deployment fails because the deployer pod is launched on the Windows node, but it is a Linux container.

##### Expected Result

The deployer pod should be launched on Linux and the actual pod should be launched on Windows.

##### Additional Information
A potential fix:  #19521

**Comment by mpbarrett** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use of Kube deployments for Windows](https://trello.com/c/IEBUoVB2/1561-use-of-kube-deployments-for-windows)
