### ISSUE TITLE
OpenShift demo cluster doesn't auto-start on node reboot

### ISSUE THREAD

**Issue by sudhaker** [openshift/origin#19753]
OpenShift demo cluster doesn't auto-start on node reboot

##### Version
[provide output of the `openshift version` or `oc version` command]
v3.6.1
or v3.9.0

##### Steps To Reproduce
1. Install a single node demo cluster using `oc cluster up` ; validate - all good?
2. Reboot the host VM; the OpenShift service (origin container) won't start

##### Current Result
Origin container (and others) doesn't start, can find it using "docker ps -a"

##### Expected Result
By default the demo cluster should start automatically after host reboots

**Comment by jwforres** [comment]
oc cluster up is not designed to for this, if you want to make sure you can bring the cluster back up then you should use the command line flags (check `oc cluster up --help`) that will persist your config/data/volumes to disk. You can then run oc cluster up again to bring the cluster back up with the same config and data

@openshift/sig-master fyi
