### ISSUE TITLE
prevent a project-admin from removing their own admin rights

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#1976]
Right now, a project-admin is one typo away from removing their rights to manage their project.  While not catastrophic, it is highly annoying and probably not what a user really wants to do.

We can make the default update of a rolebinding prevent self-removal from a role that grants permission to modify roles.  We could add a subresource for: `remove-my-powers-I-really-mean-it` and a corresponding `--force` flag on the command line to have the ability, but preventing it by default seems reasonable.

**Comment by fabianofranz** [comment]
@deads2k still an issue?

**Comment by deads2k** [comment]
> @deads2k still an issue?

Yes, still an issue.

**Comment by deads2k** [comment]
still an issue.
