### ISSUE TITLE
Deploy in dependency for mono project(all apps in same git uri)

### ISSUE THREAD

**Issue by duxianpeng** [openshift/origin#19761]
Hi, Experts,

I encounter a scenario which cannot be found solution in internet and documents, can you please share your idea.

My project is using Spring Cloud, there will be multiple application such Eureka, Config, Hytrix etc, I put all applications in same GIT URI, I saw this kind of source management called Mono project structure, the prop is that we don't need to create a individual git repository for a new microservice project, just need add it in existing repository.

In this case, I plan to deploy all applications into Openshift in a loop.
But I encounter a tough point that some applications deployment must be started after a particular application, let me give example.

There are 2 application
Project 1: Spring Cloud Config
Project 2: Spring Cloud Eureka

Project 2 must be deployed after Project 1 success, that means I must know the status of Project 1 deployment once it's fully successful.
Can you share there is any strategy in existing template config or OC command line to implement this case. 

Creating individual project for each micro service is not recommended because that will need many git repository and deploy node in Udeploy.

**Comment by jwforres** [comment]
have you considered using a jenkins pipeline to control your rollout of new deployments?

@openshift/sig-developer-experience

**Comment by jwforres** [comment]
could also consider using operators https://github.com/operator-framework/operator-sdk

**Comment by jwforres** [comment]
Closing since we've offered a few recommendations here
