### ISSUE TITLE
executing 'oc get pods' expecting any result and text 'jenkins-1-deploy

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#19785]
Seen here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19778/test_pull_request_origin_extended_clusterup/1466/

This seems to be flaking pretty hard for last few days.

**Comment by mfojtik** [comment]
@bparees does something changed in the way how Jenkins is provisioned in TSB?

**Comment by mfojtik** [comment]
found this locally:

```
2 (latest)
  tagged from registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.10
    prefer registry pullthrough when referencing this tag

  Provides a Jenkins 2.X server on RHEL 7. For more information about using this container image, including OpenShift considerations, see https://github.com/openshift/jenkins/blob/master/README.md.
  Tags: jenkins

  ! error: Import failed (InternalError): Internal error occurred: error parsing HTTP 404 response body: invalid character 'F' looking for beginning of value: "File not found.\""
      6 minutes ago
```

**Comment by legionus** [comment]
I can't get manifest from the `registry.access.redhat.com`:
```
$ boater get-manifest registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.10
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
2018/05/21 11:59:31 500 INTERNAL SERVER ERROR
```

**Comment by mfojtik** [comment]
@legionus the importer error is different, are we failing to forward the original error to users? We should probably report this as '500 - failed to get manifest from registry x.y.z'

**Comment by mfojtik** [comment]
@bparees so here is what is happening...

I ran `oc cluster up ` locally, basically following the cluster-up extended test... I got into a broken state as described in https://github.com/openshift/origin/issues/19785#issuecomment-390608309

At this point the DC will just wait for the IS update as that tag does not exists in RH registry (v3.10)....

Now, while I was digging, I updated my centos Docker, which caused that all containers created by cluster up were terminated (by Docker restart)... I brought it back by running cluster up on existing base dir (etcd), and now, surprise, everything works normally... Well the image seems to be now imported from the `docker.io`, where the tag actually exists:

```
2 (latest)
  tagged from docker.io/openshift/jenkins-2-centos7:v3.10
    prefer registry pullthrough when referencing this tag

  Provides a Jenkins v2.x server on CentOS 7. For more information about using this container image, including OpenShift considerations, see https://github.com/openshift/jenkins/blob/master/README.md.
  Tags: jenkins

  * docker.io/openshift/jenkins-2-centos7@sha256:18b9397f369b0e0646ae21d40db997e9196138b6c0cbe05db06ea95b7af1c190
      5 minutes ago
```

Also the error somehow went away... I guess this is the source of the flake.

**Comment by mfojtik** [comment]
OK explained by @dmage ... the problem is with the LDFLAG in constants is using old path after @deads2k moved it from `pkg/boostrap` to `pkg/clusterup`... if that is not set, we will import both image streams...

He will send the PR soon.
