### ISSUE TITLE
Print request/response headers and cookies in the router http log

### ISSUE THREAD

**Issue by rsevilla87** [openshift/origin#19782]
It would be nice to be able to configure HAProxy router to print additional request/response information in the http log without having to modify the default haproxy router template.
HAProxy allows this using the `capture request/response header` and 'capture cookies` options as stated by the official docs https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#8.7

This PR tries to address this feature https://github.com/openshift/origin/pull/19704

**Comment by jwforres** [comment]
@openshift/sig-networking
