### ISSUE TITLE
No route to host: when pulling images from local registry

### ISSUE THREAD

**Issue by eivantsov** [openshift/origin#19784]
##### Version

Origin  3.9
Fedora 28
Cluster started just with `oc cluster up --routing_suffix=$suffix`

##### Steps To Reproduce

I am trying to create a pod from the image that is pushed to an internal registry 
`docker-registry.default.svc:5000/openshift/rhel-php`. It's in the list of imagestreams.

```
rhel-php         172.30.1.1:5000/openshift/rhel-php         latest                       20 seconds ago
```

Everything is OK when cluster IP, however, I want to use an internal registry dns in a pod template that will work for all clusters.

##### Current Result

No route to host

##### Expected Result

Image pulled

Currently, I fix it by modifying `/etc/hosts`. Anything else I can do so that `docker-registry.default.svc` is resolved to cluster IP?

It works fine on OpenShift Online for example.

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by knobunc** [comment]
How did you install your cluster?  And how is the dns on the nodes set up?

**Comment by eivantsov** [comment]
@knobunc it's just `oc cluster up` on my Fedora laptop.

My question sounds more like:

Can I expect that `docker-registry.default.svc:5000` will point to an internal Docker registry in a cluster deployed with Ansible according to official docs?

**Comment by knobunc** [comment]
Not using oc cluster up :-(

You need something to tell the docker how to get to the internal registry.  Adding the hosts entry is reasonable.   Ansible installs set up dnsmasq to do it.

**Comment by eivantsov** [comment]
@knobunc that makes sense. Just needed a confirmation. Thanks a lot.
