### ISSUE TITLE
cluster up ordering issues

### ISSUE THREAD

**Issue by bparees** [openshift/origin#19793]
When using oc cluster up to start multiple components, most of them don't come up properly due to ordering dependencies.

Notably, if you enable the service catalog and web console, the web console doesn't actually recognize the SC is available unless you restart the WC pods.

It seems like this really only works if you use oc cluster add to explicitly add each component manually in the right order.

If we're not going to enforce ordering of the startup of components, then it seems like we shouldn't let users think they can do this as it leads to a pretty confusing experience.

**Comment by mfojtik** [comment]
@deads2k should we handled this via operator? (eg. the service catalog updating the openshift web console CR).

@bparees we discussed this with David couple times during arch calls and I think the result was that we don't want to introduce ordering ever. The components should be smart enough to determine stuff they require to run or make modification to other components themself.

**Comment by deads2k** [comment]
> @deads2k should we handled this via operator? (eg. the service catalog updating the openshift web console CR).

Yes we should.  That's *exactly* the sort of thing that the operator is for.

@bparees @spadgett What conditions does the operator need to kick the webconsole pods for re: service catalog?

**Comment by spadgett** [comment]
It doesn't need to be kicked now. Since 3.9, we detect if service catalog and template service broker are there on console load without needing config.

**Comment by spadgett** [comment]
> Notably, if you enable the service catalog and web console, the web console doesn't actually recognize the SC is available unless you restart the WC pods.

No longer a problem :)

**Comment by bparees** [comment]
> No longer a problem :)

as of when?  I just hit this yesterday w/ all v3.10 images.

**Comment by spadgett** [comment]
Since 3.9. If you can recreate, I'd like to debug because the order shouldn't matter.

**Comment by spadgett** [comment]
Specifically since this PR: https://github.com/openshift/origin-web-console/pull/2800
