### ISSUE TITLE
custom routing in openshift 

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin#19804]
Hi I have openshift 3.9 running and I need to set custom routing, so that request from route goes to the specific pods instead of providing weights to services. 

I came  across this link https://blog.openshift.com/ocp-custom-routing/ but somehow I can not access app on Wildcard DNS after providing DNS with HTTP header.

Attached is my haproxy config file. Please let me know if there is anything else needed to achieve this.
Thanks a lot in advance!
[haproxy-config.txt](https://github.com/openshift/origin/files/2027482/haproxy-config.txt)

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by priyanka5** [comment]
hi , can anyone please put some comments on the issue? thanks
