### ISSUE TITLE
can't connect to docker-registry.default.svc from router (but only on fedora 28)

### ISSUE THREAD

**Issue by djdevin** [openshift/origin#19813]
Little bit of a crazy issue and can't figure it out.

On Fedora 27 Atomic from the router pod:

```
curl -k -v https://docker-registry.default.svc:5000
[blah blah, etc]
< HTTP/1.1 200 OK
```

On Fedora 28 Atomic from the router pod:
```
curl -k -v https://docker-registry.default.svc:5000
[hang]
```

Which breaks a lot of things. In this case it was the exposed route to the registry since the router can't talk to it. Registry console also wouldn't work.

Since it's Atomic host I was able to switch between 27/28 to confirm the issue. It required downgrading to F27 on the router and also the master (the nodes running these pods).

I tried searching to see if this is fixed in 3.7+ but couldn't find anything.

What's different between F27/F28 that breaks it?

##### Version
3.6.1
containerized=true

##### Additional
The router and registry pod are on different nodes (router node, master node). S2I builds on other nodes seemed to work.

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by djdevin** [comment]
This doesn't happen anymore, with Fedora 28 and 3.7+.
