### ISSUE TITLE
Openshift unable to find internal image stream to Import images it search for imagestreams.image.openshift.io  DNS name externally 

### ISSUE THREAD

**Issue by dongascan** [openshift/origin#19832]
I m working with groovy based openshift deployment pipeline , ones i try to import openshift/base-centos7 image openshift it can't find the image to import . it search for   imagestreams.image.openshift.io externally . This is not a DNS so it given 502 Bad Gateway error . I have pushed the image manually to default openshift project and my pipline project ( devlop) image streams as well . Im working behind cooperate proxy but how ever i have passed same set of environmental variables  from openshift GUI container environmental variables, from my groovy pipeline scrips and even from jenkins global  configuration tools. Does any one have an idea to resolve this this.

error
---------

============ERROR: raw command [import-image, --from openshift/base-centos7, base-centos7, --confirm] returned an error;{reference={}, err=Error from server (InternalError): an error on the server ("<html><head><title>502 Bad Gateway</title></head>\r\n<body><h1 DNS error</h1>\r\n<p>DNS error (the host name of the page you are looking for does not exist)<br><br>Please check that the host name has been spelled correctly.<br></p>\r\n</body></html>") has prevented the request from succeeding (get imagestreams.image.openshift.io base-centos7), verb=, cmd=oc --server=IAS --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=devlop --token=XXXXX  import-image --from openshift/base-centos7 base-centos7 --confirm , out=, status=1}
Finished: FAILURE=================

proxy settings (company domain int.kn)
--------------
  http_proxy                           : "http://zscaler.proxy.int.kn:80",
  https_proxy                          : "https://zscaler.proxy.int.kn:80",
  no_proxy                             : ".int.kn,172.30.0.1:443,172.30.0.1,172.30.1.1,172.30.1.1:5000,.svc,.local,.cluster,.kube,.kubernetes,localhost",

  HTTP_PROXY                           : "http://zscaler.proxy.int.kn:80",
  HTTPS_PROXY                          : "https://zscaler.proxy.int.kn:80",
  NO_PROXY                             : ".int.kn,172.30.0.1:443,172.30.0.1,172.30.1.1,172.30.1.1:5000,.svc,.local,.cluster,.kube,.kubernetes,localhost",

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
@dongascan can you share the pipeline you're running and in particular the command you're executing that is failing?

**Comment by dongascan** [comment]
@bparees 

package main.groovy.lib

import groovy.transform.Field

@Field centosBaseImageMapping =
  [
    remoteTagToImport   : "openshift/base-centos7",
    localImageStreamName: "base-centos7"
  ]

def setupVertxApplicationBaseImageStreamIn(String targetNamespace)
{

  lock('imageAvalability') {

   // withEnv(["PATH+OC=${tool name: 'IAS oc client 1.4.1', type: 'oc'}"]) {
      openshift.withCluster('IAS') {

        openshift.withProject(targetNamespace) {

          echo "Jenkins OpenShift Plugin now using project: ${openshift.project()}"
          echo "Ensuring namespace ${targetNamespace} contains our base image '${centosBaseImageMapping.localImageStreamName}' based on remote image '${centosBaseImageMapping.remoteTagToImport}'"

          echo "creating/updating imagestream ${centosBaseImageMapping.localImageStreamName} in namespace ${targetNamespace}"
            sh "env"
// command to import images . It should check the local image stream first but its cheeking for public DNS as local image stream.
          echo openshift.raw("import-image", "--from" , " ${centosBaseImageMapping.remoteTagToImport}", centosBaseImageMapping.localImageStreamName, "--confirm").out

        }
      }
   // }
  }
}

/**
 * Returns the full tag name for the FROM declaration of the Dockerfile of the Vert.x application runtime image.
 * This is currently fixed to base-centos7.
 *
 * So the resulting dependency chain is:
 *
 * vertx-app-image  -> vertx-app-runtime-image -> runtime-image-base-image
 * which might resolve to e.g.:
 * ias-comref-store -> vertxjdk8runtime        -> openshift/base-centos7
 */
def getRuntimeImageBaseImageNameForNamespace(namespace) {
  return "${namespace}/${centosBaseImageMapping.localImageStreamName}"
}

return this;

**Comment by bparees** [comment]
can you add --loglevel 8 to your import command and provide the resulting output?

**Comment by dongascan** [comment]
@bparees  sorry i was out during the time , here what you asked 

ERROR: raw command [import-image,  openshift/base-centos7, --from, base-centos7, --confirm, --loglevel 8] returned an error;
{reference={}, err=I0529 07:25:35.660174    1878 round_trippers.go:414] GET http://IAS/apis/image.openshift.io/v1/namespaces/devlop/imagestreams/base-centos7
I0529 07:25:35.664470    1878 round_trippers.go:421] Request Headers:
I0529 07:25:35.664477    1878 round_trippers.go:424]     Accept: application/json, */*
I0529 07:25:35.664482    1878 round_trippers.go:424]     User-Agent: oc/v1.9.1+a0ce1bc657 (linux/amd64) kubernetes/a0ce1bc
I0529 07:25:35.768830    1878 round_trippers.go:439] Response Status: 502 Bad Gateway in 104 milliseconds
I0529 07:25:35.768857    1878 round_trippers.go:442] Response Headers:
I0529 07:25:35.768862    1878 round_trippers.go:445]     Server: Zscaler/6.0
I0529 07:25:35.768866    1878 round_trippers.go:445]     Content-Type: text/html
I0529 07:25:35.768870    1878 round_trippers.go:445]     Connection: close
I0529 07:25:35.769172    1878 request.go:874] Response Body: <html><head><title>502 Bad Gateway</title></head>
<body><h1>DNS error</h1>
<p>DNS error (the host name of the page you are looking for does not exist)<br><br>Please check that the host name has been spelled correctly.<br></p>
</body></html>
I0529 07:25:35.773891    1878 helpers.go:201] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "an error on the server (\"\u003chtml\u003e\u003chead\u003e\u003ctitle\u003e502 Bad Gateway\u003c/title\u003e\u003c/head\u003e\\r\\n\u003cbody\u003e\u003ch1\u003eDNS error\u003c/h1\u003e\\r\\n\u003cp\u003eDNS error (the host name of the page you are looking for does not exist)\u003cbr\u003e\u003cbr\u003ePlease check that the host name has been spelled correctly.\u003cbr\u003e\u003c/p\u003e\\r\\n\u003c!--Zscaler/6.0--\u003e\u003c/body\u003e\u003c/html\u003e\") has prevented the request from succeeding (get imagestreams.image.openshift.io base-centos7)",
  "reason": "InternalError",
  "details": {
    "name": "base-centos7",
    "group": "image.openshift.io",
    "kind": "imagestreams",
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "\u003chtml\u003e\u003chead\u003e\u003ctitle\u003e502 Bad Gateway\u003c/title\u003e\u003c/head\u003e\r\n\u003cbody\u003e\u003ch1\u003eDNS error\u003c/h1\u003e\r\n\u003cp\u003eDNS error (the host name of the page you are looking for does not exist)\u003cbr\u003e\u003cbr\u003ePlease check that the host name has been spelled correctly.\u003cbr\u003e\u003c/p\u003e\r\n\u003c!--Zscaler/6.0--\u003e\u003c/body\u003e\u003c/html\u003e"
      }
    ]
  },
  "code": 502
}]
F0529 07:25:35.773947    1878 helpers.go:119] Error from server (InternalError): an error on the server ("<html><head><title>502 Bad Gateway</title></head>\r\n<body><h1>DNS error</h1>\r\n<p>DNS error (the host name of the page you are looking for does not exist)<br><br>Please check that the host name has been spelled correctly.<br></p>\r\n</body></html>") has prevented the request from succeeding (get imagestreams.image.openshift.io base-centos7), verb=, cmd=oc --server=IAS --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=devlop --token=XXXXX  import-image  openshift/base-centos7 --from base-centos7 --confirm --loglevel 8 , out=, status=255}

Finished: FAILURE

**Comment by bparees** [comment]
@dongascan what is "IAS"?  Where is that value coming from?

```
GET http://IAS/apis/image.openshift.io/v1/namespaces/devlop/imagestreams/base-centos7
```

that seems to be what the is being used as your openshift api server hostname and that is what is not being looked up successfully.

**Comment by bparees** [comment]
Note that you may need to set a NO_PROXY value to prevent your requests to openshift api server from going through your proxy, if they are not supposed to.

**Comment by dongascan** [comment]
@bparees i found the issue using --loglevel 8. I missed to configure open shift client in my Jenkins settings.  Im bit new to openshift . Thank you
