### ISSUE TITLE
oc create gives an error if an annotation name has a hyphen (when passed via --annotation)

### ISSUE THREAD

**Issue by grdryn** [openshift/origin#19850]
If I try to add an annotation to an object using the `--annotation` option when creating with `oc create`, then it will fail if the annotation name contains a hyphen. Given that `oc annotate` can create the annotation with a hyphen just fine, this would seem to be a bug.

##### Version
```
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ocp2.skunkhenry.com:8443
openshift v3.7.9
kubernetes v1.7.6+a08f5eeb62
```
(I noticed this originally with a version 3.7.2 of `oc`, but I installed the newer version above before opening this issue, to make sure it wasn't already fixed)

##### Steps To Reproduce

1. Try creating an object and specifying an annotation with a name that has a hyphen in it (maybe other special characters have the same issue
```
oc create imagestreamtag my-jenkins-agent:latest --from-image=quay.io/feedhenry/jenkins-agent-nodejs6-centos7:latest --annotation=slave-label="nodejs nodejs6 centos centos7"
```

##### Current Result

`error: annotations must be of the form key=value and can only contain letters, numbers, and underscores`

##### Expected Result

`imagestreamtag "my-jenkins-agent:latest" created`

##### Additional Information

Annotations with hyphens can be created fine if specified in a yaml or json file with, or with `oc annotate`.

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by soltysh** [comment]
@juanvallejo since you're touching currently

**Comment by juanvallejo** [comment]
This appears to have been fixed in newer clients. I am no longer able to replicate this error with 3.10 and above.
