### ISSUE TITLE
Importing image from non-https external registry

### ISSUE THREAD

**Issue by malc0lm** [openshift/origin#19865]
##### Version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://****:8443
openshift v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
##### Steps To Reproduce
1. Create a private docker registry secret with a regular domain 'example.com'.
2. Use oc import-image --insecure=true example.com/test/web-test --confirm

##### Current Result
The import completed with errors.

Name:                   web-test
Namespace:              handsome
Created:                About a minute ago
Labels:                 <none>
Annotations:            openshift.io/image.dockerRepositoryCheck=2018-05-29T10:13:59Z
Docker Pull Spec:       docker-registry.default.svc:5000/handsome/web-test
Image Lookup:           local=false
Unique Images:          1
Tags:                   1

latest
  tagged from harbor.testos39.com/test/web-test
    will use insecure HTTPS or HTTP connections

  ! error: Import failed (Unauthorized): you may not have access to the Docker image "harbor.testos39.com/test/web-test:latest"
      Less than a second ago
  * harbor.testos39.com/test/web-test@sha256:bb94bf5ea1c2fe99a6276f3cca99daa85eb26d50a674e364e14fe151d4df866e
      About a minute ago

error: tag latest failed: you may not have access to the Docker image "harbor.testos39.com/test/web-test:latest"
##### Expected Result
The import completed with success
##### Additional Information

I follow the origin3.9 doc strictly, but it always return Unauthorized! Finally, I see the  code (https://github.com/openshift/origin/blob/release-3.9/pkg/image/importer/credentials.go#L85) that we should add a explicit port '80' in http registry which is not mentioned in  origin3.9 doc. So why not add it in origin3.9 doc?

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
> Create a private docker registry secret with a regular domain 'example.com'.

`example.com` or `testos39.com` ?  I would expect the latter

>  Finally, I see the code (https://github.com/openshift/origin/blob/release-3.9/pkg/image/importer/credentials.go#L85) that we should add a explicit port '80' in http registry which is not mentioned in origin3.9 doc. So why not add it in origin3.9 doc?

so it worked for you once you added the port to the url in your docker secret?

**Comment by bparees** [comment]
> I think it better add it to origin3.9 document---"If import a image from non-https external registry, you must add a explicit port 80 (like example.com:80) with docker registry domain in secret. "

sure, I agree, just wanted to make sure i understood what you were doing.  thanks!
