### ISSUE TITLE
oc cluster up (v3.10) creates an static resolv.conf for kubedns, not working if it changes

### ISSUE THREAD

**Issue by rgordill** [openshift/origin#19877]
When doing a first cluster up, some files are stored in local persistent volumes (folders). One of this folders is kubedns, and one file is resolv.conf, which configures the upstream DNS for skydns.

If someone moves from a network to another network with different nameservers, this file is not renewed anyway, so any external cluster resolution is completely lost.

##### Version
oc v3.10.0-0.50.0
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.120.0.1:8443
openshift v3.10.0-alpha.0+14da41d-1334
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. oc cluster up
2. change resolv.conf in host

##### Current Result
kubedns/resolv.conf with old configuration.

##### Expected Result
kubedns/resolv.conf refreshed with new configuration.

##### Additional Information
Maybe this is related with #18943

**Comment by mfojtik** [comment]
@rgordill you can copy the /etc/resolv.conf over to that volume which should work. The resolv.conf is created during MakeKubeDNSConfig phase which is only ran when the baseDir is empty.

Maybe we can relax this check: https://github.com/mfojtik/origin/blob/e67f48d8107781c34e4fba7b651bd1e0d4988dd0/pkg/oc/clusterup/run_self_hosted.go#L336 and write it every time you run cluster up, but it sounds ugly.. @deads2k ?

**Comment by deads2k** [comment]
> Maybe we can relax this check: https://github.com/mfojtik/origin/blob/e67f48d8107781c34e4fba7b651bd1e0d4988dd0/pkg/oc/clusterup/run_self_hosted.go#L336 and write it every time you run cluster up, but it sounds ugly.. @deads2k ?

Keeping that file up to date seems reasonable.  I'd do it by adding an extra copy step *after* the configs are written and before we start the kubelet.

**Comment by rgordill** [comment]
Is there any alternative to check periodically and update it if needed? I am also concerned to have to restart the cluster any time the DNS resolver is changed.
