### ISSUE TITLE
need instructions or disclaimer of some sort for running `oc` as is on linux distros like alpine

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#19882]
See https://github.com/openshift/jenkins-client-plugin/issues/158

Already had some preliminary discussions with @juanvallejo and @deads2k on this.

Whether its saying "certain linux libs need to be present...", or "oc is only certified on ..." or "you need to make X adjustments", I at least don't have a strong preference.

Ultimately, I want to link to whatever doc update is made (either the README or some such in this repo or docs.openshift.org is fine at least for me as well) from https://github.com/openshift/jenkins-client-plugin

@openshift/sig-master

**Comment by juanvallejo** [comment]
Adding a note on the docs here: https://github.com/openshift/openshift-docs/pull/9681

**Comment by soltysh** [comment]
The docs pr merge, so I think this is fixed. @gabemontero feel free to re-open if you don't agree.

**Comment by gabemontero** [comment]
On Wed, Jun 6, 2018 at 11:46 AM Maciej Szulik <notifications@github.com>
wrote:

> The docs pr merge, so I think this is fixed. @gabemontero
> <https://github.com/gabemontero> feel free to re-open if you don't agree.
>
I agree.  Already referring to the new doc with our Jenkins stuff that uses
‘oc’
