### ISSUE TITLE
Node labels are lost after Deregister/Register Node events

### ISSUE THREAD

**Issue by skynardo** [openshift/origin#19899]
After stopping/starting a Node (AWS EC2 instance) node labels:
logging-infra-fluentd=true,node-role.kubernetes.io/compute=true
Are missing after the node registers and becomes READY

##### Version
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. oc get node ip-177-77-77-100.ec2.internal --show-labels
NAME                            STATUS    ROLES     AGE       VERSION             LABELS
ip-177-77-77-100.ec2.internal   Ready     compute   6d        v1.9.1+a0ce1bc657   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1a,kubernetes.io/hostname=ip-177-77-77-100.ec2.internal,**logging-infra-fluentd=true,node-role.kubernetes.io/compute=true**,region=primary,zone=default
2. Shut down EC2 Instance 
3. Start up EC2 Instance
4. Run oc get node ip-177-77-77-100.ec2.internal --show-labels

##### Current Result
oc get node ip-177-77-77-100.ec2.internal --show-labels
NAME                            STATUS    ROLES     AGE       VERSION             LABELS
ip-177-77-77-100.ec2.internal   Ready     <none>    1m        v1.9.1+a0ce1bc657   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1a,kubernetes.io/hostname=ip-177-77-77-100.ec2.internal,region=primary,zone=default
##### Expected Result
We expect to still have the labels **logging-infra-fluentd=true,node-role.kubernetes.io/compute=true** after reboot.

**Comment by jwforres** [comment]
@openshift/sig-pod

**Comment by DanyC97** [comment]
@skynardo how did you sent the labels nodes in first place ?

**Comment by skynardo** [comment]
We ran the playbook below after upgrading to version 3.9 to deploy openshift logging. These playbooks must set the logging-infra-fluentd=true on all nodes.
/usr/share/ansible/openshift-ansible/playbooks/openshift-logging/config.yml

We ran the upgrade playbook below which sets the role.kubernetes.io/compute=true /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade.yml

We also have group_var files to set Openshift Roles for nodes, and masters (shown below). 
These help the installer set Role=compute for worker nodes and Role=master for master nodes.

cat tag_OpenShift_Role_node
---
openshift_schedulable: true
openshift_node_labels:
  region: primary
  zone: default
  openshift_node_group_name: node-config-node

cat tag_OpenShift_Role_master
---
openshift_schedulable: true
openshift_node_labels:
  region: master
  zone: default
  openshift_node_group_name: node-config-master

**Comment by sjenning** [comment]
This is a known issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1559271

Upstream discussions:
https://github.com/kubernetes/kubernetes/pull/45986
https://github.com/kubernetes/kubernetes/issues/46442
