### ISSUE TITLE
Some unit tests fail in a pod because they use in cluster context

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#19902]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19827/pull-ci-origin-unit/1002401727812472832/

has a number of failures due to being run in a pod on a kube cluster:

```
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/config TestAuthenticationDetection/skip_bad_in_cluster_config
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/util/webhook TestKubeConfigFile 0.13s
github.com/openshift/origin/vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook TestNewFromConfig 0.03s
github.com/openshift/origin/vendor/k8s.io/kubernetes/plugin/pkg/admission/imagepolicy TestNewFromConfig 0.03s
```

Blocks moving origin unit tests to ci-operator (which runs the tests in a pod on the cluster).  We can do one of two things - work around this in the unit tests by clearing the env var explicitly, or fix the tests to do that themselves.  I don't have a strong preference, although the latter seems better in the long run (the tests themselves giving incorrect results due to env).

@openshift/sig-master @stevekuznetsov @kargakis

**Comment by stevekuznetsov** [comment]
We fixed this by removing the k8s in-cluster vars last time AFAIK.... @csrwng do you remember?
