### ISSUE TITLE
routes with port

### ISSUE THREAD

**Issue by oeresundsgruppen** [openshift/origin#19900]
I can set up routes to service. E.g. the route ABC points to service S1 with port 9011. Now I cannot use ABC:9011 from external, but only ABC. How can I allow to use port also ?

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by ironcladlou** [comment]
@oeresundsgruppen can you provide a use case in the form of the YAML or JSON for the `Route` and `Service` objects you're working with? Thanks.

**Comment by oeresundsgruppen** [comment]
Service S has ports P1 and P2. Route R1 points to S:P1 and R2 points to S:P2. Now we can use R1 and R2 in a browser/javascript/frontend, but we cannot use R1:P1 or R2:P2 - or can this be made possible somehow ?

**Comment by ironcladlou** [comment]
Ports are static per router deployment (80/443 by default), and can't be customized by an individual `Route`. If you need external ports exposed per service, you might consider [exposing Services directly](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).

/cc @knobunc to fact check me

**Comment by knobunc** [comment]
LGTM.  Thanks @ironcladlou
