### ISSUE TITLE
RFE: Support command to switch oc client version

### ISSUE THREAD

**Issue by nak3** [openshift/origin#19906]
##### Motivation

There are two motivations.

1. Some users have different clusters with different version. Although it is possible to switch server context by `oc login`, client version cannot. Since k8s/openshift supports only N±1 version, oc client sometimes incompatible.
2. During upgrade, [playbook upgrade.yml](https://github.com/openshift/openshift-ansible/blob/73079a70fc93d63abfbb31fe33104b5e096e45f7/playbooks/openshift-master/private/upgrade.yml) executes:

   step-1. Run some **pre** operations with oc command like `# oc adm migrate storage` in [pre upgrade storage ](https://github.com/openshift/openshift-ansible/blob/73079a70fc93d63abfbb31fe33104b5e096e45f7/playbooks/openshift-master/private/upgrade.yml#L56).
   step-2. Update client package (e.g oc v3.7->3.9).
   step-3. Run some **post** operations with updated oc command like `# oc adm migrate storage`.

  So, If playbook failed at step-3, re-running playbook from step-1 will fail due to incompatible client version.

##### Additional Information

One possible solution is that switching symbolic link by a script. However, the motivation #2 needs a official solution from client options or RPM package release.

**Comment by soltysh** [comment]
I don't this kind of functionality should ever be handled by oc itself. It's rather a higher level tool that would do that. Similarly to others available for switching runtime language (python, go, etc).

**Comment by aditya-konarde** [comment]
I landed here looking for exactly the same thing as @nak3 ; I do agree that this shouldn't be handled by oc itself, but instead wrapper. For example there's something along these lines available for docker: https://github.com/newrelic/dkenv

I'll try to get something up as a weekend project. Juggling multiple client versions is a pain :)
