### ISSUE TITLE
oc apply does not work on objects created with a resourceVersion field

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#19905]
Related comment: https://github.com/openshift/release/pull/901#issuecomment-393963467

When creating an object via `oc apply -f resource.yaml`, subsequent patches to that object fail if the initial object in `resource.yaml` contained a `metadata.resourceVersion` field.

Example:

```yaml
# given the following dc with a metadata.resourceVersion field, I will create it via oc apply
$ cat simpledc.yaml
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: simple-dc
  creationTimestamp: null
  resourceVersion: "111"
  labels:
    name: test-deployment
spec:
  replicas: 1
  selector:
    name: test-deployment
  template:
    metadata:
      labels:
        name: test-deployment
    spec:
      containers:
      - image: openshift/origin-ruby-sample
        name: helloworld

$ oc apply -f simpledc.yaml
deploymentconfig.apps.openshift.io "simple-dc" created

# modify the original dc, removing the resourceVersion field
$ cat simpledc_modified.yaml
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: simple-dc
  creationTimestamp: null
  labels:
    name: test-deployment
spec:
  replicas: 2
  selector:
    name: test-deployment
  template:
    metadata:
      labels:
        name: test-deployment
    spec:
      containers:
      - image: openshift/origin-ruby-sample
        name: helloworld

# attempt to run oc apply again
$ oc apply -f simpledc_modified.yaml
The deploymentconfigs "simple-dc" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

If I run the steps above without setting a `metadata.resourceVersion` field when I create the dc via `oc apply`, I do not get the error seen, and the operation succeeds as expected.

Is this a bug, or an expected behavior of apply?

cc @stevekuznetsov @soltysh @liggitt

**Comment by soltysh** [comment]
> Is this a bug, or an expected behavior of apply?

I wonder if it's worth the hassle now that there's work upstream towards server-side apply.

**Comment by liggitt** [comment]
apply should likely do something better here, but creating with a resourceVersion to begin with is suspect

**Comment by aarthipa** [comment]
I have the same error "metadata.resourceVersion: Invalid value: 0x0: must be specified for an update"  
but in my case the dc does not contain resourceVersion parm at all!

**Comment by Asgoret** [comment]
Same problem. Any workarounds?

**Comment by HomemBravo** [comment]
Having same issue.

**Comment by Avni-Sharma** [comment]
+1 for this issue

**Comment by dariodsa** [comment]
It worked when I change apply to replace, so you can try with it.

**Comment by teamdefinex** [comment]
> It worked when I changed apply to replace, so you can try with it.

"The imperative replace command replaces the existing spec with the newly provided one, dropping all changes to the object missing from the configuration file. This approach should not be used with resource types whose specs are updated independently of the configuration file."
It is not an alternative for apply.
We are still having the same issue.

**Comment by codytipton-hpg** [comment]
Commenting for anyone else coming along chasing this issue.  In my case, I wanted to apply changes to resources that had been created outside of `oc apply` and still leverage apply for upper environment promotion in our pipeline--as they didn't yet exist in upper environment namespaces.  The solution that worked for me was simple:

`oc apply set-last-applied -f deploy.yaml --create-annotation=true`

refer to `oc apply set-last-applied --help`
