### ISSUE TITLE
master-config.yaml with invalid keys are not validated

### ISSUE THREAD

**Issue by gnufied** [openshift/origin#19914]
Sometimes our users put keys in YAML in subtly incorrect indentation. This does not cause any validation errors or anything like that and master controllers start just fine but intended purpose of putting the key in YAML does not work.

YAML being whitespace senstive makes it harder to notice. Can we just start validating the keys in YAML and print warning or errors or even refuse to start the process if something is wrong with YAML?

Examples:
1. https://bugzilla.redhat.com/show_bug.cgi?id=1582231
2. https://bugzilla.redhat.com/show_bug.cgi?id=1570085

**Comment by gnufied** [comment]
cc @liggitt @smarterclayton

**Comment by enj** [comment]
Just waiting on Go 1.10 for #19106

It warns on unexpected fields but does not fail.
