### ISSUE TITLE
oc cp called from a container to pull file from another container

### ISSUE THREAD

**Issue by edmacabebe** [openshift/origin#19921]
[provide a description of the issue]

##### Version
oc v3.9.0+191fece
--
  | kubernetes v1.9.1+a0ce1bc657
  | features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. bake into the container oc v3.9 client
2. oc cp somepod:/tmp /home/me

##### Current Result
error: /tmp no such file or directory

##### Expected Result
The folder exist, copy its contents to local fs folder

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/home/osoadmin/.kube/config'
Info:  Using context for cluster-admin access: 'default/masterdnsi46qdxvn6fjhg-southeastasia-cloudapp-azure-com:443/system:admin'
[Note] Performing systemd discovery

ERROR: [DH0002 from controller openshift/origin/pkg/oc/admin/diagnostics/diagnostics/host/util.go]
       Could not read master config file '/etc/origin/master/master-config.yaml':
       (*os.PathError) open /etc/origin/master/master-config.yaml: permission denied
       
ERROR: [DH0002 from controller openshift/origin/pkg/oc/admin/diagnostics/diagnostics/host/util.go]
       Could not read master config file '/etc/origin/master/master-config.yaml':
       (*os.PathError) open /etc/origin/master/master-config.yaml: permission denied
       
ERROR: [CED3001 from controller openshift/origin/pkg/oc/admin/diagnostics/util/util.go]
       Encountered fatal error while building diagnostics: [open /etc/origin/master/master-config.yaml: permission denied, open /etc/origin/master/master-config.yaml: permission denied]
       
[Note] Summary of diagnostics execution (version v3.9.0+ba7faec-1):
[Note] Errors seen: 3

**Comment by soltysh** [comment]
@juanvallejo mind looking at this?

**Comment by juanvallejo** [comment]
@edmacabebe is this issue still happening? Could you verify that there is a `/tmp` directory in the target pod?
