### ISSUE TITLE
Error: ErrImagePull

### ISSUE THREAD

**Issue by mvlach** [openshift/origin#19930]
Installed OpenShift Origin 3.7 version. When pulling images from internal registry there are sometimes errors 

Failed to pull image "docker-registry.default.svc:5000/production/ccv-module@sha256:94f7e44fd70f8351aed27ee56736abd8aa622eb5d6639c2db38d76cbdafb9127": rpc error: code = 2 desc = error parsing HTTP 404 response body: json: cannot unmarshal number 24105772564739525879304305977802563659019470122550583812611063987423416657694538338221683534227388560460648201176360091142439455340642015045012751183847654955654323963315036980588817959765280050765505410321429027868320520610887641336618058072569615592108855436627440187915971347559033316768659335379555843069682624277095015250081282007182336019268103505082693616595927515873390004234375126087158591833647945714270252716412136156569575728291843140017577652372605874572382341057125736165285483498563988820719563802135547200338438110704719024462521985667055008901915002478450035266383397598145564044396450734264189907657 into Go struct field Error.detail of type float64

When we rebuild image production/ccv-module the deployement is successful. 

##### Version
oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server ********
openshift v3.7.2+5eda3fa-5
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
Don't know - sometimes it happens.

**Comment by dmage** [comment]
@mvlach was the image in ccv-module created by import-image or by pushing into the internal registry?

If it was created by import-image, that that's a problem on the remote registry (an invalid certificate, the error contains details about the certificate which the Docker client can't parse). We'll fix the error reporting in the next release.

**Comment by mvlach** [comment]
The image is created via the S2I build process. When I build  application after some time the image "disappear".

**Comment by dmage** [comment]
Which storage is used for the registry? Do all images disappear or only some of them?

**Comment by mvlach** [comment]
The storage is the NFS mounted on the POD. Only one image disappear - I'm able to pull s2i builder image... @dmage

**Comment by mvlach** [comment]
solved.

docker registry was configured with the persistent volume (stored on NFS). But somebody replaced the volume claim with the EmptyDir, so all new images aren't stored on the permanent storage. 

Thanks all for help.
