### ISSUE TITLE
Login with GitLab is broken due to their V3 API no longer being supported

### ISSUE THREAD

**Issue by alikhajeh1** [openshift/origin#19937]
Logging in with GitLab shows an authentication error; the master logs show `AuthenticationError: Could not retrieve GitLab id`. The issue seems to be that GitLab's V3 API, which is [used by Origin](https://github.com/openshift/origin/blob/v3.7.2/pkg/auth/oauth/external/gitlab/gitlab.go#L26
), stopped working tonight:
```
curl -i "https://gitlab.com/api/v3/user" -H "Private-Token: SECRET"
{"error":"API V3 is no longer supported. Use API V4 instead."}
```

If the GitLab code is being updated, it might also be nice to address https://github.com/openshift/origin/issues/17954
 
##### Version
Origin 3.9

##### Steps To Reproduce
1. Setup Origin to Login with GitLab
2. Try logging in and notice the authentication error

##### Current Result
User can't login with GitLab.

##### Expected Result
User should be able to login with GitLab.

**Comment by aliscott** [comment]
Relevant GitLab discussion: https://gitlab.com/gitlab-org/gitlab-ce/issues/47565#note_80041904 (Consider bringing back v3 endpoint for OAuth endpoints)
