### ISSUE TITLE
Can't deploy MySQL because it contains unresolved images

### ISSUE THREAD

**Issue by Poltorackiy** [openshift/origin#19955]
Hello, I created MySQL database service and when I try to deploy it says that it contains unresolved images.

![unresolved images](https://user-images.githubusercontent.com/4964993/41218465-5d71e8de-6d85-11e8-8846-a57aa96ac1ec.PNG)

Steps To Reproduce
1. Create MySQL service in Catalog
2. Added route to this service
3. Go to Application -> Deployments -> MySQL service -> Click Deploy

I have no images in Image Stream section.

How to set MySQL DB and get access from Visual Studio .NET Core project to debug MySQL on local PC?

**Comment by lletelier** [comment]
Which version are you running?
`minishift version
minishift v1.18.0+756b128`

**Comment by jwforres** [comment]
As a cluster administrator you may want to check the imagestreams in the "openshift" namespace. That is where the OOTB mysql imagestream is defined. See if there are any issues there with those imagestreams not getting synced.

@openshift/sig-developer-experience

**Comment by bparees** [comment]
@Poltorackiy were you able to confirm your openshift namespace imagestreams were successfully imported?

**Comment by bparees** [comment]
closing due to lack of followup information needed to pursue.

**Comment by raj4linux** [comment]
Even I am getting the similar issue with OpenSHift 3.10 fresh installation. See the screen shot:

![image](https://user-images.githubusercontent.com/8280560/46092583-cbb91f00-c1d2-11e8-925d-763030481619.png)


OC STATUS says:
```
[root@master playbooks]# oc status
In project rk project for demo (rkproject) on server https://master.rkdomain.test:8443

dc/php deploys openshift/php:7.0
  deployment #1 waiting on image


2 infos identified, use 'oc status -v' to see details.
[root@master playbooks]#
```

**Comment by glennodickson** [comment]
Hi I am receiving the exactly the same as @Poltorackiy  error too. Why?

Currently, running:
openshift v3.10.0+fd501dd-48
kubernetes v1.10.0+b81c8f8

**Comment by Poltorackiy** [comment]
@glennodickson Hi! It appeared because not enough resources, not enough memory, it was openshift error

**Comment by glennodickson** [comment]
@Poltorackiy It can resolve external images however it cannot reference images on the internal docker registry.

**Comment by shyam-biradar** [comment]
@Poltorackiy : I am also facing the same issue with openshift 3.11 fresh install. I see default image streams are configured on my cloud. But still I am getting same 'unresolved image' error for all images. I tried for httpd, mysql, postgresql.

**Comment by MerinYan** [comment]
@shyam-biradar: I face the same issue with openshif 3.11.
I found that I chose the wrong Namespace of imagestream, default is openshift.
You can try it.

**Comment by jdorel** [comment]
It might come from you changing the Namespace entry when configuring the template. This is the **ImageStream** Namespace, and not the project you want it to be included to.

**Comment by nscooper** [comment]
done all the above yet still getting the same error!!

**Comment by toretest** [comment]
Same problem v 3.11

**Comment by madipietro** [comment]
Same problem on fresh install!!, some clue ?

**Comment by kuzmanzs** [comment]
Cloning "https://github.com/openshift/openshift-jee-sample.git " ...
--
  | error: fatal: unable to access 'https://github.com/openshift/openshift-jee-sample.git/':  **Could not resolve host: github.com; Unknown error**
