### ISSUE TITLE
start-build should optionally take resource.Builder arguments

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1995]
So that someone can xargs it.

**Comment by kargakis** [comment]
Supporting both syntaxes will make the command more complex for both the end user and the code. How about a change to the resource builder altogether?

**Comment by smarterclayton** [comment]
We can potentially support a default resource type in builder.  It has to be opt in (someone has to explicitly support it).

**Comment by kargakis** [comment]
How about making the `--from-build` flag a boolean that will dictate that default type?

**Comment by smarterclayton** [comment]
Not sure - could go either way.

----- Original Message -----

**Comment by bparees** [comment]
@smarterclayton what's your xargs use case?  you can always run "xargs -n 1" for things that don't cleanly handle a stream of input.

**Comment by bparees** [comment]
or is this referring to the "build/my-build-name" format?

**Comment by smarterclayton** [comment]
Yeah

On Jun 29, 2015, at 4:51 PM, Ben Parees <notifications@github.com> wrote:

or is this referring to the "build/my-build-name" format?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/1995#issuecomment-116843434>.

**Comment by kargakis** [comment]
@smarterclayton is it possible for the resource builder to work with subresources right now? I don't think so. `start-build` is kind of messy because the input object is never created, instead we define a BuildRequest and query the `builds/clone` or `buildConfigs/instantiate` endpoints.

I was thinking of not using the resource builder for this, instead parse the cli for type/name args. Thoughts?

**Comment by smarterclayton** [comment]
It is not possible to work with sub resources.  I don't think this is a
high priority item - there are other decisions that need to be made.

On Mon, Jul 13, 2015 at 10:21 AM, Michail Kargakis <notifications@github.com
> wrote:

> @smarterclayton <https://github.com/smarterclayton> is it possible for
> the resource builder to work with subresources right now? I don't think so.
> start-build is kind of messy because the input object is never created,
> instead we define a BuildRequest and query the builds/clone or
> buildConfigs/instantiate endpoints.
>
> I was thinking of not using the resource builder for this, instead parse
> the cli for type/name args. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/1995#issuecomment-120944545>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift
