### ISSUE TITLE
CronJobs in OpenShift web console 

### ISSUE THREAD

**Issue by biconou** [openshift/origin#19966]
It seems like *CronJobs* is a kind of object not shown in the web console.

If I want to list then I must issue this command : 
`oc get cronjobs`

##### Version
origin 3.9

**Comment by enj** [comment]
@openshift/sig-user-interface

**Comment by spadgett** [comment]
It looks like CronJob isn't showing up in Other Resources because it's not in the batch/v1 API group, only batch/v1beta1. We're only showing batch/v1 resources there.

/kind bug
/priority p2
/assign

**Comment by benjaminapetersen** [comment]
@spadgett should we migrate to web console repo?

**Comment by spadgett** [comment]
Cron jobs are available in the admin console in 3.11 and will be part of the converged console in OpenShift 4.0.

Closing this issue as it's also tracked by a Bugzilla RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1567976

/close
