### ISSUE TITLE
oc cp does not error when not logged in

### ISSUE THREAD

**Issue by whitel** [openshift/origin#19984]
If you are not logged in, "oc cp" fails silently.

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.41:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. oc logout
2. oc cp <podname>:/dir1/dir2 /localdir/

##### Current Result
appears to complete correctly

##### Expected Result
similar to error from "oc exec" 
e.g. error: You must be logged in to the server (the server has asked for the client to provide credentials)

**Comment by soltysh** [comment]
This should be fixed in the latest oc.
/close
