### ISSUE TITLE
Update example repos that were moved to sclorg

### ISSUE THREAD

**Issue by adambkaplan** [openshift/origin#19998]
Many of the GitHub repos for our example templates (ex: `django-ex`) have been moved to sclorg.

These should be updated so we don't rely on the redirect.

**Comment by adambkaplan** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
the templates actually live in those upstream repos (the imagestreams also have this issue, in their sampleRepo field), so the changes need to be made there and then propagated down.
