### ISSUE TITLE
All users in OpenShift org should be able to approve bindata changes

### ISSUE THREAD

**Issue by enj** [openshift/origin#20007]
@stevekuznetsov I assume the bot does not have the concept of an organization?

cc @deads2k

**Comment by stevekuznetsov** [comment]
No. There is a mechanism for defining "groups" but in general we did not want to use GitHub groupings as there is no audit trail for membership changes to them. How often is this an issue?

**Comment by deads2k** [comment]
> No. There is a mechanism for defining "groups" but in general we did not want to use GitHub groupings as there is no audit trail for membership changes to them. How often is this an issue?

Not very often.  It's a frustrating thing we don't need for bindata though.  We want to control that at the source.

**Comment by stevekuznetsov** [comment]
Not likely to see support.

/close
