### ISSUE TITLE
When build feature is disabled, new-app should not attempt to create buildconfigs 

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#20002]
In case where the builds are disabled in master-config and thus the build/buildConfig endpoint is not exposed, the new-app should give user error when user is trying to create an app from the GIT repo.

Today, users will get something like this:

```
--> Creating resources ...
    imagestream "ruby-22-centos7" created
    imagestream "ruby-ex" created
    error: unable to recognize /__internal, Kind=BuildConfig: no matches for /, Kind=BuildConfig
    deploymentconfig "ruby-ex" created
    service "ruby-ex" created
--> Failed
```

If we know beforehand that we can't create BuildConfig, instead of creating resources we should error out (and tell user that the cluster configuration does not allow to run builds)

**Comment by bparees** [comment]
more background in the original bug: https://bugzilla.redhat.com/show_bug.cgi?id=1591003
