### ISSUE TITLE
update docs for ``oc cluster up``

### ISSUE THREAD

**Issue by pmacko1** [openshift/origin#20018]
update docs for ``oc cluster up`` (I'm using fedora 28)
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#overview

##### Original docs
``docker network inspect -f "{{range .IPAM.Config }}{{ .Subnet }}{{end}}" bridge``

##### Updated docs
``sudo docker network inspect -f "{{range .IPAM.Config }}{{ .Subnet }}{{end}}" bridge``

##### Why?
all ``docker`` cmd's require ``sudo``
https://docs.docker.com/install/linux/linux-postinstall/

**Comment by mfojtik** [comment]
@pmacko1 can you send a PR with this fix?

**Comment by pmacko1** [comment]
@mfojtik apologies, busy. could you ping someone from openshift-docs?

**Comment by finp** [comment]
@pmacko1  I run docker on Fedora without sudo, see https://docs.docker.com/install/linux/linux-postinstall/

**Comment by pmacko1** [comment]
@finp and that was what i actually had to do in order to get oc cluster up working.

**Comment by pmacko1** [comment]
Very good point @finp I suggest then to tell user to configure docker to do this procedure https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user
