### ISSUE TITLE
Unknown types take forever to resolve as missing

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#20037]
Something to do with APIServer responses?

Compare a type that does not exist:
```
$ time oc get ist clonerefs:latest
the server doesn't have a resource type "ist"

real	0m4.969s
user	0m0.340s
sys	0m0.080s
```

With an object that does not exist:
```
$ time oc get is nonexistant
Error from server (NotFound): imagestreams "nonexistant" not found

real	0m0.977s
user	0m0.405s
sys	0m0.054s
```

Why?

/cc @smarterclayton @deads2k @liggitt 
/kind bug
/area kubernetes

**Comment by liggitt** [comment]
Unknown types force full rediscovery, to see if the type you specified exists in a hitherto undiscovered group version. This is run in parallel in 1.11, which speeds it up immensely 

/close
