### ISSUE TITLE
GitHub webhook couldn't connect to server

### ISSUE THREAD

**Issue by ffly827** [openshift/origin#20046]
I'm a complete starter on OpenShift so please forgive me if I'm wrong about stuffs XD.

I was setting up the webhook for my ruby example on GitHub, following the guide here: https://docs.openshift.org/3.9/getting_started/developers_console.html#developers-console-configure-auto-builds. But GitHub is giving me a "We couldn’t deliver this payload: Couldn't connect to server" error when delivering the ping payload.

##### Version
oc v3.9.0+48cff0c-24
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v3.9.0+48cff0c-24
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Create a project on OpenShift Origin
2. Add the ruby example to it
3. Copy the webhook link to the forked repository on GitHub

##### Current Result
<img width="580" alt="capture" src="https://user-images.githubusercontent.com/39611871/41635997-73ae15d2-747e-11e8-8cec-ac05cb2ecf6f.PNG">

##### Expected Result
Successful delivery.

**Comment by aossama** [comment]
I noticed that the exposed URL is a nip.io and the server is localhost, which means that this is a local installation, probably using "oc cluster up". For GitHub webhooks to be able to trigger remote builds on your OpenShift, the OpenShift needs to be exposed to the internet and GitHub must be able to access it.

Is your OpenShift instance exposed to the internet at all and accessible by GitHub webhooks?

**Comment by ffly827** [comment]
Oh gotcha! I won't be exposing my OpenShift instance for now so I guess I'll just do the manual rebuild as an alternative :).

**Comment by SreyemSOR** [comment]
so how can solve I face this problem also

**Comment by SreyemSOR** [comment]
We couldn’t deliver this payload: Couldn't connect to server

**Comment by gangware72** [comment]
Mine is exposed to the internet yet it still produces that error.
