### ISSUE TITLE
Deployment hook environment isn't inherited from target container

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#2005]
When defining a deployment lifecycle hook, only the environment specified on the hook itself is present in the environment of the hook container. The hook container environment should be inherited from the container the hook points to, and additional environment specified on the hook definition should override the inherited defaults.

**Comment by ironcladlou** [comment]
@smarterclayton 

Do you agree that the hook containers should inherit env from the template container they point at?

**Comment by thoraxe** [comment]
Think about it this way:

If they don't, you end up duplicating the podTemplate's container's env vars, and, if they were to change, you would have to then edit *two* places in your buildConfig -- the pod itself, and its hook pre- or post- hook (ok, maybe even 3 edits!).
