### ISSUE TITLE
test-integration never reports failed even with failed tests

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#20067]
Working on the [rebase branch](https://github.com/openshift/origin/pull/20033) it seems that test-integration never reports red.

/assign @stevekuznetsov

**Comment by stevekuznetsov** [comment]
This does seem to only be on your branch.

The way the test logs get cut off mid-run makes me thing something is killing the test container. Can you export `OS_DEBUG=true` at the top of `hack/lib/init.sh` in your PR so we can see more information?

**Comment by stevekuznetsov** [comment]
Hmm... the latest run on your PR [here](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20033/test_pull_request_origin_integration/18742/) exported jUnit results and failed as expected.

**Comment by stevekuznetsov** [comment]
As seen [here](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/20033/test_pull_request_origin_integration/18729/artifacts/scripts/shell/logs/scripts.log) the test container exited with zero code when it failed that weird way...

```
[DEBUG] [17:50:46+0000] Starting container 284b1428ab12885b6dc93866234a395ce9155ca811a0ad741482b6e1fa8ecf63
[DEBUG] [17:50:47+0000] Following container logs
[DEBUG] [18:35:56+0000] Container exited with 0

```

**Comment by stevekuznetsov** [comment]
Let's revisit this if it's consistent on your PR again since it seems to have abated
