### ISSUE TITLE
does not start on MacOS with virtualbox

### ISSUE THREAD

**Issue by sekaijin** [openshift/origin#20088]
Hi
>minishift start
-- Starting profile 'minishift'
-- Check if depereccated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ......... FAIL E0624 15:16:07.834406    6082 start.go:407] Error starting the VM: Error starting stopped host: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version **_5.0.12_** that is is supposed to fix this issue. Retrying.
Error starting the VM: Error starting stopped host: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version **_5.0.12_** that is is supposed to fix this issue

but the virtualbox version is : 
>VBoxManage --version
**5.2.12**r122591

Bye

**Comment by praveenkumar** [comment]
@mfojtik  Thanks, I mapped the issue https://github.com/minishift/minishift/issues/2499 please close it from here. 

@sekaijin We can have discussion over minishift issue to more info.
