### ISSUE TITLE
Restore -v in set deployment-hook and status commands

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#20097]
As part of the 1.11 rebase (https://github.com/openshift/origin/pull/20033) we've dropped `-v` support in `oc set deployment-hook` and `oc status` commands we need to restore them back.

**Comment by deads2k** [comment]
@soltysh @mfojtik I think we're less likely to miss a bugzilla.  This is a backwards compatibility thing.

**Comment by soltysh** [comment]
Opened https://bugzilla.redhat.com/show_bug.cgi?id=1595669 but I'll leave this one open. I have a few of these that I'll be sweeping through post-rebase.
