### ISSUE TITLE
new-app creates unnecessary imagestream

### ISSUE THREAD

**Issue by bparees** [openshift/origin#20107]
https://github.com/openshift/origin/pull/20052 appears to have broken new-app's behavior.

Running in an empty project:
```
oc new-app https://github.com/openshift/nodejs-ex
```

creates an imagestreamtag named "nodejs:10" in the current namespace.

The buildconfig it creates references the openshift/nodejs:10 IST as expected, but the currentnamespace/nodejs:10 IST is also created.

**Comment by bparees** [comment]
(I haven't confirmed that was the PR that broke it, but it seems suspicious anyway)

**Comment by coreydaley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Reuse existing imagestreams with new-app [app_creation][tech_debt]](https://trello.com/c/BOR33gza/1559-3-reuse-existing-imagestreams-with-new-app-appcreationtechdebt)
