### ISSUE TITLE
Error: failed to start the web console server: timed out waiting for the condition

### ISSUE THREAD

**Issue by amrit28** [openshift/origin#20110]
I am able to successfully build and create image of openshit/origin from customized openshift/origin source code.
Now i am facing issue with oc cluster up with locally created image .
"Error: failed to start the web console server: timed out waiting for the condition"

##### Version
oc v3.9.0+191fece-dirty
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
Docker version 18.03.1-ce, build 9ee9f40
go version go1.9 linux/amd64

##### Steps To Reproduce
1. git clone the openshift/origin v3.9.0
2. build the base image using "hack/env hack/build-base-images.sh"
3. created full build image using "hack/env make release".
4. Facing issue with using below command
   oc cluster up --version="$(git log -1 --pretty=%h )" --public-hostname=172.40.16.100
   Output of above command:
##### Current Result
[root@localhost origin]# oc cluster up --version=191fece --public-hostname=172.40.16.100
Using nsenter mounter for OpenShift volumes
Using public hostname IP 172.40.16.100 as the host IP
Using 172.40.16.100 as the server IP
Starting OpenShift using openshift/origin:191fece ...
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ...
   scc "privileged" added to: ["system:serviceaccount:default:registry"]
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Importing internal templates ... OK
-- Installing web console ... FAIL
   Error: failed to start the web console server: timed out waiting for the condition
##### Expected Result

[root@localhost origin]# oc cluster up --version=191fece --public-hostname=172.40.16.100
Using nsenter mounter for OpenShift volumes
Using public hostname IP 172.40.16.100 as the host IP
Using 172.40.16.100 as the server IP
Starting OpenShift using openshift/origin:191fece ...
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ...
   scc "privileged" added to: ["system:serviceaccount:default:registry"]
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Importing internal templates ... OK
-- Installing web console ... OK
   ...................................
The server is accessible via web console at:
    https://172.40.16.100:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

**Comment by mfojtik** [comment]
Can you please provide logs from cluster up origin container? Just grep for "console".

**Comment by boukandouramhamed** [comment]
Same issue. 
PS: i'm running behind a proxy.
