### ISSUE TITLE
Failed to pull image "registryip:5000/openwhiskpoc/action-nodejs-6@sha256

### ISSUE THREAD

**Issue by MohamedElso** [openshift/origin#20121]
Hi guys,
i am trying to deploy openwhisk on RedHat openshift cluster, I got this error when spinning up the pods, I tried to deploy on minishift and it works well. any suggestions would be appreciated. thanks
================
Failed to pull image "registryip:5000/openwhiskpoc/action-nodejs-6@sha256:bd3176824ead9191cbdd4b87ab2ec594c14f9b86cf37f7bab4d254a19792ef16": rpc error: code = 2 desc = error parsing HTTP 404 response body: json: cannot unmarshal number  into Go struct field Error.detail of type float64: "{\"errors\":[{\"code\":\"MANIFEST_UNKNOWN\",\"message\":\"manifest unknown\",\"detail\":{\"Op\":\"Get\",\"URL\":\"https://registry-1.docker.io/v2/\",\"Err\":{\"Certificate\":

**Comment by bparees** [comment]
looks like a certificate issue w/ the openshift registry not trusting "https://registry-1.docker.io/v2/" for some reason.  Do you have a proxy in place?

/cc @dmage

**Comment by dmage** [comment]
```
Issuer: DC=ca, DC=bce, DC=corp, DC=bell, CN=Bell Issuing CA 4
Subject: C=CA, ST=ON, L=Mississauga, O=BELL, OU=ISE, CN=dm1cme.on.bell.ca
```

It's not a valid certificate for the Docker registry.

**Comment by bparees** [comment]
> It's not a valid certificate for the Docker registry.

good eyes.

**Comment by bparees** [comment]
> do you know how to start tracking in this issue

I'd start by creating your own pod in the cluster, oc rsh'ing in, and dig into the networking flow that is happening when you try to access docker.io.  Again, it seems like there is a proxy or dns issue here where you're not getting directly connected to docker.io, something is intercepting the traffic and providing its own cert.

**Comment by MohamedElso** [comment]
@bparees @dmage hi guys i am not sure if the cause of the error because of the registry, [https://ibb.co/ewuMCJ](url) as you can see all of the pods in the project spinning up except one pod with this error that i mentioned before 
Failed to pull image "registryiphere:5000/openwhiskpoc/action-nodejs-6@sha256:bd3176824ead9191cbdd4b87ab2ec594c14f9b86cf37f7bab4d254a19792ef16": rpc error: code = 2 desc = error parsing HTTP 404 response body: json: cannot unmarshal number 
any ideas ?
i also pulled and push the image to the registry put still the same error . any of you guys could pulish the project on his own cluster and let me know if he face the same issue .
https://github.com/projectodd/openwhisk-openshift
Thanks
