### ISSUE TITLE
publisher bot cannot check out new repo

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#20144]
seen in deployment/openshift-kubernetes-bot:

```
I0629 03:09:48.814588       1 publisher_logger.go:79] git clone --no-tags https://github.com/openshift/kubernetes-sample-controller.git /go-workspace/src/k8s.io/kubernetes-sample-controller
E0629 03:09:48.818577       1 publisher_logger.go:93] exit status 129
    	error: unknown option `no-tags'
```

I'm not sure if our image is old or has an old version of git, but I had to clone that repo manually, omitting the `--no-tags` arg

/assign @mfojtik @sttts

**Comment by sttts** [comment]
`--no-tags` was added in git 2.14. We have 2.1.4 in the image.
