### ISSUE TITLE
pull-ci-origin-unit: operator Run the tests for unit in a pod and wait for success or failure

### ISSUE THREAD

**Issue by wozniakjan** [openshift/origin#20149]
the test appears to be flaky, few different PRs recently failed some of the runs with the same message

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19673/pull-ci-origin-unit/581/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20145/pull-ci-origin-unit/575/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20145/pull-ci-origin-unit/573/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20095/pull-ci-origin-unit/567/

**Comment by adambkaplan** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20064/pull-ci-origin-unit/595/

**Comment by deads2k** [comment]
@wozniakjan @adambkaplan Hey guys, this is helpful, but can you chase it the extra step to find the test that actually failed?  

@wozniakjan you're hitting https://github.com/openshift/origin/issues/20136

@adambkaplan you have a different error

**Comment by wozniakjan** [comment]
got it, thanks! I don't know why I thought that was actually the name of the failing test, closing this as a dupe
