### ISSUE TITLE
publisher bot cannot reset branch

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#20143]
seen in deployment/openshift-kubernetes-bot:

```
I0629 03:11:19.642584       1 publisher_logger.go:79] git branch -f release-1.9.1 origin/release-1.9.1
E0629 03:11:19.644222       1 publisher_logger.go:93] exit status 128
    	fatal: Cannot force update the current branch.
```

should ensure we are not on the branch we are trying to force reset

/assign @mfojtik @sttts

**Comment by sttts** [comment]
> should ensure we are not on the branch we are trying to force reset

Yes.

What worries me more: the `LoadRules` above that call does not specify the branch. @mfojtik should we go to master or some other branch specified in the config?
