### ISSUE TITLE
Certain tools should be split from the Origin repo

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#20162]
There are a number of tools, listed below, with dependencies on our vendored copy of kubernetes.
These tools should be split out either into their own separate repo, aggregated with others in a different repo, or re-writen to not depend on k8s packages, in order to prevent the overhead of dependency conflicts during rebases:

- **tools/clicheck** (depends on)
  - k8s.io/kubernetes/pkg/kubectl/cmd/templates
- **tools/etcdhelper**
  - k8s.io/apimachinery/pkg/runtime/serializer/json
  - k8s.io/kubernetes/pkg/kubectl/scheme
  - k8s.io/kube-aggregator/pkg/apis/apiregistration/install
  - k8s.io/kubernetes/pkg/apis/core/install
- **tools/gendocs**
  - k8s.io/kubernetes/pkg/kubectl/cmd/util
- **tools/genapidocs**
  - k8s.io/apimachinery/pkg/runtime/schema
- **tools/genman**
  - k8s.io/kubernetes/cmd/genutils
- **tools/rebasehelpers**
  - k8s.io/apimachinery/pkg/util/sets
- **tools/buildanalyzer**
  - k8s.io/apimachinery/pkg/apis/meta/v1
- **tools/testdebug**
  - k8s.io/apimachinery/pkg/util/net
  - k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/rbac/internalversion
  - k8s.io/kubernetes/pkg/kubectl/cmd/util

cc @smarterclayton @deads2k

**Comment by juanvallejo** [comment]
cc @soltysh

**Comment by soltysh** [comment]
> tools/etcdhelper

This is tightly integrated with openshift API as well, since this is used to read objects from etcd. I'm not sure why you didn't list origin deps here as well.

**Comment by soltysh** [comment]
Additionally, of all the tools `etcdhelper` might be the hardest to split out.

**Comment by deads2k** [comment]
> Additionally, of all the tools etcdhelper might be the hardest to split out.

I care most about tools that are copy/pasted into new repos and have bad packages that need fixing and deps I don't care about.  Let's say these as the starting point:


https://github.com/openshift/service-serving-cert-signer/tree/master/tools

**Comment by smarterclayton** [comment]
The new gotest2junit replaces junitreport and has no dependencies outside of stdlib, so you can omit that one.  See https://github.com/openshift/service-catalog to see the absolute latest go 1.10 version of the hack tools.

**Comment by juanvallejo** [comment]
@deads2k 
> I care most about tools that are copy/pasted into new repos and have bad packages that need fixing 
> and deps I don't care about. Let's say these as the starting point:
>
> https://github.com/openshift/service-serving-cert-signer/tree/master/tools

`changelog` and `import-verifier` do not appear to depend on any non-stdlib packages
