### ISSUE TITLE
Deployment process pod is not tagged

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2018]
Probably should be, with something that allows it to be grouped under the thing that owns it.

**Comment by smarterclayton** [comment]
Giving it the parent DC's labels has issues (potentially)

**Comment by smarterclayton** [comment]
Also... the deployment process pod name should be deterministic for a dc - which would prevent duplicate deployments from being run.

**Comment by smarterclayton** [comment]
The last point is probably more important than the first two points.

**Comment by ironcladlou** [comment]
@abhgupta I know you're working at least part of this... want to go ahead and take the issue?

**Comment by abhgupta** [comment]
@smarterclayton Agreed. @ironcladlou and I just discussed it this morning - the fact that we need to make the deployment pod name deterministic to prevent multiple pods for the same deployment version from running concurrently.

By the way, the deployment (rc) name is already deterministic and ensures that we do not have multiple deployments for the same dc version.

**Comment by abhgupta** [comment]
@ironcladlou Sure, I can pick this up - will just need inputs on the tagging piece.

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/issues/2254 is the deterministic pod name that is mustfix for the release, this is a nice to have.

**Comment by ironcladlou** [comment]
@smarterclayton @abhgupta As part of other work we've done, all deployer pods have a label which correlates them to their parent deployment. Can this issue be closed?

**Comment by abhgupta** [comment]
Yes, this is now complete. I am closing it and @smarterclayton can re-open if there is something else desired for this.

**Comment by abhgupta** [comment]
Specifically, the "grouping" using labels was achieved by https://github.com/openshift/origin/pull/2582
