### ISSUE TITLE
apiserver with etcd metric and all values are "0"

### ISSUE THREAD

**Issue by Reamer** [openshift/origin#20194]
Metric endpoint of apiserver/controller reports etcd metric and all values of etcd metrics are "0"

##### Version
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.avm.de:443
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
1. Install Openshift 3.11
2. Login to Openshift `oc login openshift.mycompany.com`
3. Get Your Token `oc whoami -t`
4. curl apiserver metric endpoint with a valid Token
```
 curl -k -H "Authorization: Bearer [My-Token]"  https://openshift.mycompany.com:[apiserver_port]/metrics | grep etcd
```
##### Current Result
```
...
# HELP etcd_server_has_leader Whether or not a leader exists. 1 is existence, 0 is not.
# TYPE etcd_server_has_leader gauge
etcd_server_has_leader 0
# HELP etcd_server_leader_changes_seen_total The number of leader changes seen.
# TYPE etcd_server_leader_changes_seen_total counter
etcd_server_leader_changes_seen_total 0
# HELP etcd_server_proposals_applied_total The total number of consensus proposals applied.
# TYPE etcd_server_proposals_applied_total gauge
etcd_server_proposals_applied_total 0
# HELP etcd_server_proposals_committed_total The total number of consensus proposals committed.
# TYPE etcd_server_proposals_committed_total gauge
etcd_server_proposals_committed_total 0
...
```

##### Expected Result
In case of an external etcd-cluster, etcd-metrics should not reported from the api server.

##### Additional Information
I have a three node etcd cluster.
Direct metric curl to a etcd node works as expected.
```
curl -s --cacert "/etc/origin/master/master.etcd-ca.crt" --cert "/etc/origin/master/master.etcd-client.crt" --key "/etc/origin/master/master.etcd-client.key" https://etcd1.mycompany.com:2379/metrics
```
```
...
# HELP etcd_server_has_leader Whether or not a leader exists. 1 is existence, 0 is not.
# TYPE etcd_server_has_leader gauge
etcd_server_has_leader 1
# HELP etcd_server_leader_changes_seen_total The number of leader changes seen.
# TYPE etcd_server_leader_changes_seen_total counter
etcd_server_leader_changes_seen_total 1
# HELP etcd_server_proposals_applied_total The total number of consensus proposals applied.
# TYPE etcd_server_proposals_applied_total gauge
etcd_server_proposals_applied_total 1.9855194e+07
# HELP etcd_server_proposals_committed_total The total number of consensus proposals committed.
# TYPE etcd_server_proposals_committed_total gauge
etcd_server_proposals_committed_total 1.9855194e+07
...
```

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by sttts** [comment]
These metrics are etcd server metrics. I guess these only exist in our openshift binary because we still link in etcd for all-in-one mode. But as your etcd cluster is external, you have to grab those metrics from there.

**Comment by Reamer** [comment]
@sttts 
It is possibly to disable the exported metric?

**Comment by sttts** [comment]
They come from here: https://github.com/openshift/origin/blob/master/vendor/github.com/coreos/etcd/etcdserver/metrics.go#L70

To avoid auto-exporting them, one has to get rid of the init func there and make the registration explicit in the main.go.

@gyuho is maintaining etcd. He can probably comment on this.

**Comment by gyuho** [comment]
Hmm,

> Metric endpoint of apiserver/controller reports etcd metric

Is `apiserver/controller` using etcd with `embed` package?

etcd only exposes etcd metrics via its client ports.

**Comment by Reamer** [comment]
Hi @gyuho,
It seems so, I use rpm based installation.

**Comment by Reamer** [comment]
If you need more informations let me know.

**Comment by Reamer** [comment]
Still present in v3.10
```
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://s-cp-lb-01.cloud.mycompany.com:443
openshift v3.10.0+7eee6f8-2
kubernetes v1.10.0+b81c8f8
```

**Comment by Reamer** [comment]
I'm using now [openshift/origin-control-plane:v3.10.0](https://hub.docker.com/r/openshift/origin-control-plane/tags/)

**Comment by alekonko** [comment]
same issue with openshift 3.9

**Comment by Reamer** [comment]
Still present in v3.11
```
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://s-cp-lb-01.cloud.mycompany.com:443
openshift v3.11.0+84fe0ad-23
kubernetes v1.11.0+d4cacc0
```

**Comment by rhnewtron** [comment]
With 3.11 Prometheus is now GA, however the etcd metrics are still empty. Checking etcd health (latency, disk usage etc) is an essential part of monitoring an production openshift cluster. 

If I understand openshift 3.11 correctly, I would need to scrape the etcd system pods in kube-system under /metrics using a client cert. However, as Openshift is using client cert auth for Master to Etcd authentication, this requires Prometheus to use a certificate from the etcd CA too. With this certificate, as etcd RBAC (https://coreos.com/etcd/docs/latest/op-guide/authentication.html) seems to be disabled in openshift 3.11, prometheus would habe the same permissions as the API Server (GET and Update on etcd resources), which opens a huge security issue from my perspective.

So for me this is not easily solvable right now. 

Either I manually enable RBAC for etcd and configure everything properly (using the master cert CN's as user names) - high risk of breaking the cluster.

OR 

Wait till someone comes up with a proper way to do this (e.g. disable TLS auth for /metrics endpoint)

Any Inputs on this one ?

**Comment by Reamer** [comment]
/remove-lifecycle stale
Updated initial issue message.

**Comment by SteveKeller** [comment]
same issue here..

- etcd is installed on master nodes
- openshift version: v3.11.117
- kubernetes version: v1.11.0+d4cacc0

**Comment by Reamer** [comment]
/remove-lifecycle stale
Can not reproduce this with okd 4.3. I'll let this issue open, because okd 4.3 is still in alpha and I have okd 3.11 in production.
