### ISSUE TITLE
oc new-app sets wrong label in DeploymentConfig

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#20193]
I'm instantiating a template, when using `oc new-app` with a label to be set, it borks the deploymentConfig. If I use `oc process` instead it works fine.

[provide a description of the issue]

##### Version
oc v3.10.0-rc.0+c20e215

##### Steps To Reproduce
1. Execute:
``` 
oc new-app -f https://raw.githubusercontent.com/eclipse/che/6.6.0/deploy/openshift/template/multi/postgres-template.yaml -p CHE_VERSION=6.6.0 -l app=che
```

##### Current Result
DeploymentConfig is not created because following error
```
Error from server (Invalid): DeploymentConfig "postgres" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"che"}: `selector` does not match template `labels`
```

##### Expected Result
Everything should be properly created with the labels properly applied.

##### Additional Information
When instead you run `oc process` everything works fine.
```
oc process -f https://raw.githubusercontent.com/eclipse/che/6.6.0/deploy/openshift/templates/multi/postgres-template.yaml -p CHE_VERSION=6.6.0 -l app=che -o yaml | oc apply -f -
```

When looking into the generated DC from oc new-app, the spec.template.metadata.labels is wrongly replaced. This field should keep the original value, as only the spec.metadata.labels should be affected by the -l flag in new-app.

**Comment by jwforres** [comment]
@openshift/sig-developer-experience
