### ISSUE TITLE
Stage FORWARD PARAMETERS TO THE REMOTE HOST [00h 00m 00s] failed. Indication 1

### ISSUE THREAD

**Issue by bparees** [openshift/origin#20214]
Seeing this w/ increasing frequency.  Is there no retry logic that can be added?

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/536/

**Comment by stevekuznetsov** [comment]
We poll until the machine is ready:

```
TASK [aws-up : wait for SSH to be available] ***********************************
task path: /var/lib/jenkins/origin-ci-tool/4b405957477ba1b70cfacd1cf43c6d41a605fc8e/lib/python2.7/site-packages/oct/ansible/oct/playbooks/provision/roles/aws-up/tasks/main.yml:175
ok: [localhost] => {
    "changed": false, 
    "elapsed": 30, 
    "generated_timestamp": "2018-07-05 08:37:11.300110", 
    "path": null, 
    "port": 22, 
    "search_regex": null, 
    "state": "started"
}
```

Then in that link, looks like the machine went down?

```
+ scp -F /var/lib/jenkins/jobs/test_branch_origin_extended_image_ecosystem/workspace/.config/origin-ci-tool/inventory/.ssh_config /var/lib/jenkins/.config/gcloud/gcs-publisher-credentials.json openshiftdevel:/data/credentials.json
lost connection
```

We looped on that 10 times to give it retries, and they all failed. I think this is a symptom of a dead VM of some sort. Not clear that more retries would have helped.

**Comment by bparees** [comment]
> We looped on that 10 times to give it retries, and they all failed. I think this is a symptom of a dead VM of some sort. Not clear that more retries would have helped.

what about going all the way back to launching a new VM in this scenario?

**Comment by bparees** [comment]
(that is what i meant by retry: retry launching the VM)

**Comment by stevekuznetsov** [comment]
The new `ci-vm-operator` should fix that by using a controller with a workqueue to retry VM lifecycle management. Attempting to hack this into some bash in `sjb` seems futile.

**Comment by bparees** [comment]
ok.
