### ISSUE TITLE
Race between creation of a Pod and adding image pull secret to SA, that never gets reconciled

### ISSUE THREAD

**Issue by bparees** [openshift/origin#20225]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_image-registry/106/pull-ci-image-registry-e2e/70/

The image pulls are failing because these tests are not waiting for the service account secrets to be created before creating the pods, so the pull is being done w/ no credentials.  That was fine when the pull went to docker.io, but now the pulls go to the internal registry, so credentials must be supplied.

/cc @openshift/sig-master since @mfojtik is on PTO.

**Comment by tnozicka** [comment]
@bparees I am not sure I am understanding this right. The timeout for that test is 5 minutes - that should be more that enough for the SA to be provisioned? If it goes to backoff, which in the case of SA missing is correct, when the SA gets provisioned it should pull just fine - but from the master logs it is unable to pull through all that time:
```
čec 05 22:56:45 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:56:45.120264   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:56:56 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:56:56.135025   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:57:08 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:57:08.516620   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ErrImagePull: "rpc error: code = Unknown desc = unauthorized: authentication required"
čec 05 22:57:21 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:57:21.136039   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:57:36 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:57:36.112090   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:57:49 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:57:49.112907   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:58:01 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:58:01.133299   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:58:14 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:58:14.117185   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:58:27 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:58:27.117494   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:58:40 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:58:40.444563   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ErrImagePull: "rpc error: code = Unknown desc = unauthorized: authentication required"
čec 05 22:58:52 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:58:52.117214   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:59:06 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:59:06.147943   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:59:17 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:59:17.806975   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:59:31 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:59:31.909867   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 22:59:46 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 20:59:46.111806   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 23:00:00 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 21:00:00.112615   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 23:00:16 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 21:00:16.111998   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
čec 05 23:00:29 ci-op-vts6l96v-f7020-ig-n-zfmr origin-node[10812]: E0705 21:00:29.154997   10812 pod_workers.go:186] Error syncing pod c35db0f6-8095-11e8-8b65-42010a8e0005 ("example-1-fphn9_e2e-test-cli-deployment-mtncp(c35db0f6-8095-11e8-8b65-42010a8e0005)"), skipping: [failed to "StartContainer" for "ruby" with ImagePullBackOff: "Back-off pulling image \"docker-registry.default.svc:5000/openshift/ruby@sha256:d93797a0ef82beaa1cf92e3511b11f2d5bd3120d675b5e2bf6eed0603f6c8949\""
```
seems like it never gets a SA or there is related issue with (re)-auth

**Comment by bparees** [comment]
I don't know what the image pull logic is for a pod..  if a pod is in image pull backpoff and then the secret appears, will it use the secret on the next attempt, or has it already concluded no secret should be used when pulling and ignores the secret?  These are questions for the pod team.  But we have logic to wait for service accounts in our build tests and we never see a case where the service accounts/secrets do not get provisioned, nor with pulling images.

**Comment by tnozicka** [comment]
> Will it use the secret on the next attempt, or has it already concluded no secret should be used when pulling and ignores the secret? These are questions for the pod team.

@openshift/sig-pod

I don't want to hack it if it would be actually a bug in kubelet. Seems like it should reconcile, unless there is good reason not to.

**Comment by liggitt** [comment]
> I don't know what the image pull logic is for a pod.. if a pod is in image pull backpoff and then the secret appears, will it use the secret on the next attempt, or has it already concluded no secret should be used when pulling and ignores the secret?

pull secrets for the internal registry are added to service accounts as the pull secrets are provisioned, which happens asynchronously

pull secrets are copied from a service account to a pod spec at the point in time when the pod is created. the pod is never updated from that point on

**Comment by tnozicka** [comment]
> pull secrets are copied from a service account to a pod spec at the point in time when the pod is created. the pod is never updated from that point on

This makes me concerned - if a user executes `oc new-project myproject && oc create -f mydeployment.yaml` I really hope we don't just expect the race to work in his favor or **never reconcile**.

Has this been discussed previously?

**Comment by bparees** [comment]
Sounds like that's exactly what's going to happen.  Note that this didn't use to be as big a deal since most images users typically referenced were public images (stuff on docker hub or RHCC).  Since now all the default content is a pullthrough via the internal registry, auth is required for the default images, so while the race always existed, it's much more likely someone hits it now.  (Previously they'd only hit it if they were referencing a private image intentionally, in which case their flow would have been to create the project, create the secret if necessary(i.e. if the default service account didn't have credentials to pull the private image, which it might already have if it's pulling from the internal registry), and then create the deployment, in which case the secret would definitely exist before the pod.

**Comment by sjenning** [comment]
> pull secrets are copied from a service account to a pod spec at the point in time when the pod is created. the pod is never updated from that point on

@liggitt The *contents* of the secret aren't copied right?  There is an `imagePullSecrets` field in the pod spec with the name of the secret and an attempt to obtain that secret is done each time through the sync loop:

https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go#L833-L849

https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go#L1615-L1616

**Comment by liggitt** [comment]
> @liggitt The contents of the secret aren't copied right? There is an imagePullSecrets field in the pod spec with the name of the secret and an attempt to obtain that secret is done each time through the sync loop

Correct. Just the secret names. There's a race after the creation of the service account between the creation of the pod and the creation/addition of the image pull secret to the service account

**Comment by bparees** [comment]
> There is an imagePullSecrets field in the pod spec with the name of the secret 

which will not be populated if the pod was created before the secret existed.

**Comment by tnozicka** [comment]
/unassign

not sure who to re-assign this to, probably someone from the Pod team?

**Comment by bparees** [comment]
@tnozicka this is core k8s behavior, you can consider it a bug/RFE if you want but I doubt it's going to get changed soon.  In the meantime it's a flaky test that's going to keep breaking people, so please put a workaround in place (wait for the service account secret to be present before starting your test)

There is a helper for this:
https://github.com/openshift/origin/blob/master/test/extended/util/framework.go#L718

Also an unassignment w/o making sure *someone* else owns it (even if they may disagree and pass it on) is not a good idea, it just makes it easier for the issue to slip through the cracks since now no one is responsible for it.

/assign @tnozicka

**Comment by tnozicka** [comment]
Added a hack for DC tests to avoid this bug in https://github.com/openshift/origin/pull/20278

"Flake" is about to be suppressed, so for the root cause as I didn't get any answer on who else would own the fix, I am gonna assume this is @openshift/sig-pod :
/unassign @tnozicka
/assign @sjenning
