### ISSUE TITLE
TestServerRunWithSNI failure

### ISSUE THREAD

**Issue by bparees** [openshift/origin#20220]
```
=== RUN   TestServerRunWithSNI
coverage: 27.4% of statements
panic: test timed out after 2m0s
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20064/pull-ci-origin-unit/846/

@openshift/sig-master

**Comment by sttts** [comment]
https://github.com/kubernetes/kubernetes/pull/65899 might be the cure.

**Comment by smarterclayton** [comment]
I separated out the test to make it clearer why it would fail in 66008, which shouldn't block your change.

**Comment by sttts** [comment]
With https://github.com/openshift/origin/pull/20309 merged 5 days ago, this should be fixed. @bparees please report back if we see the flake again.

Optimistically closing.
