### ISSUE TITLE
Incorrect CLI error for CRD on `oc logs`

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#20226]
Origin 3.11 post-rebase

```
$ oc logs pj/5cdf78fc-80b1-11e8-9651-720000710580
error: no kind "ProwJob" is registered for version "prow.k8s.io/v1"
```

The error is wrong, should have said something like "no logs could be found for type prowjob" (which is a CRD)

@openshift/cli-review

**Comment by soltysh** [comment]
Which exact version, I've just tried master and it appears to be working as expected.
