### ISSUE TITLE
Init:CrashLoopBackOff Pod status when deploying application in Openshift

### ISSUE THREAD

**Issue by kamesh2229** [openshift/origin#20233]
[provide a description of the issue]
I am deploying an application in openshift cluster and the service is not coming up as the pod status always show as CrashLoopBackOff and the container is in cyclic restarts.

oc get pods
NAME                                    READY     STATUS                  RESTARTS   AGE
elasticsearch-client-7754b98dc6-tr4f8   0/1       Init:CrashLoopBackOff   5          3m
elasticsearch-data-77c8b59978-hmnk7     0/1       Init:CrashLoopBackOff   10         28m
elasticsearch-master-7865cd56cd-w659k   0/1       Init:CrashLoopBackOff   10         28m
elasticsearch-master-7865cd56cd-xszj7   0/1       Init:CrashLoopBackOff   10         28m

##### Version
[provide output of the `openshift version` or `oc version` command]

oc v3.9.30
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Describe Pod output 

Events:
  Type     Reason                 Age               From                                     Message
  ----     ------                 ----              ----                                     -------
  Normal   Scheduled              6m                default-scheduler                        Successfully assigned elasticsearch-client-7754b98dc6-tr4f8 to cen1-ocpnod06.dcp.ericsson.net
  Normal   SuccessfulMountVolume  6m                kubelet, cen1-ocpnod06.dcp.ericsson.net  MountVolume.SetUp succeeded for volume "storage"
  Normal   SuccessfulMountVolume  6m                kubelet, cen1-ocpnod06.dcp.ericsson.net  MountVolume.SetUp succeeded for volume "default-token-tww8k"
  Normal   Started                5m (x4 over 6m)   kubelet, cen1-ocpnod06.dcp.ericsson.net  Started container
  Normal   Pulled                 4m (x5 over 6m)   kubelet, cen1-ocpnod06.dcp.ericsson.net  Container image "172.30.213.178:5000/prod-ams-audit-log/os" already present on machine
  Normal   Created                4m (x5 over 6m)   kubelet, cen1-ocpnod06.dcp.ericsson.net  Created container
  Warning  BackOff                1m (x25 over 6m)  kubelet, cen1-ocpnod06.dcp.ericsson.net  Back-off restarting failed container

oc get events for the project 

32m          1         elasticsearch-master-7865cd56cd-xszj7.153ec750756ba952   Pod                                                Normal    Scheduled               default-scheduler                         Successfully assigned elasticsearch-master-7865cd56cd-xszj7 to cen1-ocpnod02.dcp.ericsson.net
32m         32m          1         elasticsearch-master-7865cd56cd-xszj7.153ec750811b3adf   Pod                                                Normal    SuccessfulMountVolume   kubelet, cen1-ocpnod02.dcp.ericsson.net   MountVolume.SetUp succeeded for volume "storage"
32m         32m          1         elasticsearch-master-7865cd56cd-xszj7.153ec7508187e4b5   Pod                                                Normal    SuccessfulMountVolume   kubelet, cen1-ocpnod02.dcp.ericsson.net   MountVolume.SetUp succeeded for volume "default-token-tww8k"
30m         32m          5         elasticsearch-master-7865cd56cd-xszj7.153ec750a7e00cc5   Pod          spec.initContainers{init-myservice}   Normal    Pulled                  kubelet, cen1-ocpnod02.dcp.ericsson.net   Container image "172.30.213.178:5000/prod-ams-audit-log/os" already present on machine
30m         32m          5         elasticsearch-master-7865cd56cd-xszj7.153ec750b50ba5f6   Pod          spec.initContainers{init-myservice}   Normal    Created                 kubelet, cen1-ocpnod02.dcp.ericsson.net   Created container
30m         32m          5         elasticsearch-master-7865cd56cd-xszj7.153ec750bce9ec18   Pod          spec.initContainers{init-myservice}   Normal    Started                 kubelet, cen1-ocpnod02.dcp.ericsson.net   Started container
2m          32m          136       elasticsearch-master-7865cd56cd-xszj7.153ec7512ed1f46a   Pod          spec.initContainers{init-myservice}   Warning   BackOff                 kubelet, cen1-ocpnod02.dcp.ericsson.net   Back-off restarting failed container
32m         32m          1         elasticsearch-master-7865cd56cd.153ec75072a08ee0         ReplicaSet                                         Normal    SuccessfulCreate        replicaset-controller                     Created pod: elasticsearch-master-7865cd56cd-w659k
32m         32m          1         elasticsearch-master-7865cd56cd.153ec75074d5d6d0         ReplicaSet                                         Normal    SuccessfulCreate        replicaset-controller                     Created pod: elasticsearch-master-7865cd56cd-xszj7
32m         32m          1         elasticsearch-master.153ec750705199af                    Deployment                                         Normal    ScalingReplicaSet       deployment-controller                     Scaled up replica set elasticsearch-master-7865cd56cd to 2

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
I am deploying an elastic search application which should have a cent os to be installed as pre-requsite.
When installing the same the pods are not comming up and is going for cyclic reboots.

When checked the pod logs i am not getting any clue except that the container is restarted.
I am using a template (yaml file) that has the parameters defined to install the same and not assuming issue with the template as it is succesfully done on another similar server and works fine.

But when installed on other server facing this issue and not able to get any clue from logs or other info and please help me in how to solve the same.

**Comment by jwforres** [comment]
Have you tried using `oc debug` ? That will let you get the pod running with a shell as the entrypoint instead, then you'll have the pod up in the same container environment. At that point you can try running your normal entrypoint and see what happens without the container crashing and being deleted.

**Comment by kamesh2229** [comment]
No i will do that .. You mean deploying the service using oc debug command right ?

**Comment by jwforres** [comment]
right, don't delete your deployment object, and then just run `oc debug deployment/name`

run `oc debug --help` for my info

**Comment by kamesh2229** [comment]
Hi,

I tried deploying using oc debug -f and getting the below error.

oc debug -f elasticsearch-template.yml
error: cannot debug elasticsearch: unable to extract pod template from type *template.Template

So deployed the normal way how i was doing and still facing the problem but now the container is not at all started in this case

oc process -f elasticsearch-template.yml PROJECT_NAME=sampleName APPLICATION_NAME=elasticsearch | oc apply -f -

Events:
Type Reason Age From Message

Normal Scheduled 5m default-scheduler Successfully assigned elasticsearch-master-7865cd56cd-wdhgx to server
Normal SuccessfulMountVolume 5m kubelet, MountVolume.SetUp succeeded for volume "storage"
Normal SuccessfulMountVolume 5m kubelet, MountVolume.SetUp succeeded for volume "default-token-tww8k"
Warning FailedCreatePodContainer 10s (x25 over 5m) kubelet, unable to ensure pod container exists: failed to create container for /kubepods/burstable/pode99ea512-8357-11e8-8880-005056a07a77 : dbus: connection closed by user

oc get pods
NAME READY STATUS RESTARTS AGE
elasticsearch-client-7754b98dc6-z6q89 0/1 Init:0/3 0 29m
elasticsearch-data-77c8b59978-8trjh 0/1 Init:0/3 0 29m
elasticsearch-master-7865cd56cd-6d489 0/1 Init:0/3 0 29m
elasticsearch-master-7865cd56cd-wdhgx 0/1 Init:0/3 0 29m

Tried to get some debug logs by attaching the pod but it is hung in waiting to pod start status.

oc debug elasticsearch-client-7754b98dc6-z6q89
Defaulting container name to elasticsearch-client.
Use 'oc describe pod/elasticsearch-client-7754b98dc6-z6q89-debug -n default-project' to see all of the containers in this pod.
Debugging with pod/elasticsearch-client-7754b98dc6-z6q89-debug, original command: 
Waiting for pod to start ...

Not sure if something wrong is done here ...

**Comment by kamesh2229** [comment]
I see there is some problem in running the init containers in this case the elastic search service will first install centos image as init container and openshift has some privileges required to run,, 

may be i am not completely getting the technical details of the same.. any help would really greatful..
