### ISSUE TITLE
Intermittent DNS errors: service IP returned as 127.0.53.53

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#2024]
We're using DNS to look up services rather than env vars. As there is a short TTL for DNS entries DNS requests are issued quite regularly (every 30s I believe by default). While this works most of the time, we have observed that even with running pods & no errors in openshift logs, service IPs sometimes resolve to 127.0.53.53. I have confirmed that this is happening because the pod is failing over to the secondary nameserver in /etc/resolv.conf.

I have been able to repeat this problem by running in a pod:

    watch -n 0.1 -g dig +short +search nexus

At first the service IP resolves fine, but at some point it resolves to 127.0.53.53, indicating that the master isn't serving the DNS request. I have been unable to repeat this on the master with `@localhost` as the server to query - it consistently returns the correct service IP address.

**Comment by detiber** [comment]
@jimmidyson Could you provide more information regarding your deployment topology?  From he description it sounds like some type of intermittent network partition happening.

**Comment by jimmidyson** [comment]
This is all running on a single host.

**Comment by detiber** [comment]
@jimmidyson 2 docker containers on a single host or native binaries on a single host?  

Also, (just wondering here) if some of the iptables manipulation being done (between openshift, docker, and kubernetes) could be playing a part.

**Comment by jimmidyson** [comment]
Everything's running in containers, openshift all-in-one in a container. Pods are running on same host as master. No other nodes in cluster.

**Comment by detiber** [comment]
I'll have to defer to someone that is more familiar with that type of environment. @smarterclayton any suckers^H^H^H^H^H^H^Hvolunteers you can think of?

**Comment by smarterclayton** [comment]
@pweil- or I probably need to look - it could be skydns returning that address due to an internal error.

**Comment by jimmidyson** [comment]
@smarterclayton - like i said when hitting skydns from the host i couldn't reproduce the issue. From a container it was fairly quickly reproducible. Changing to use the secondary nameserver (dig @8.8.4.4 ...) returned 127.0.53.53, hence my suspicion that it was failing over to secondary nameserver.

**Comment by smarterclayton** [comment]
Ok - maybe it's latency then on the DNS resolution.  Can you include the /etc/resolv.conf from the container here?

**Comment by jimmidyson** [comment]
```
nameserver 172.18.25.34
nameserver 8.8.8.8
nameserver 8.8.4.4
search default.local local osop.rhcloud.com
```

Master IP is 172.18.25.34 so this is configured correctly.

**Comment by smarterclayton** [comment]
Thanks, will try to repro.  You're on master - what base image are you on?

**Comment by jimmidyson** [comment]
We're running openshift/origin:v0.4.4.

**Comment by smarterclayton** [comment]
Still looking into this...

**Comment by Sacro** [comment]
Just a passing guy who spotted this post on Google!

Firstly, don't use internal and external resolvers, it's a fun way to get intermittent resolving issues.

Secondly, you're seeing this IP appear because you're using a domain name that you don't own, and is possibly going to be someone else's in the near future.

What is the full domain you're trying to use?

**Comment by danmcp** [comment]
@smarterclayton Any updates?

**Comment by smarterclayton** [comment]
This is being investigated in #2482

**Comment by smarterclayton** [comment]
Fixed by the changes to put master DNS entry in host /etc/resolv.conf and disabling the open forwarding on the master

----- Original Message -----
