### ISSUE TITLE
dockerImageReference refers to external image even dockerImageRepository points to a private one

### ISSUE THREAD

**Issue by yuanlinios** [openshift/origin#20249]
I am using openshift origin in an isolated environment and thus do not want public/external images are pulled during application deployment. So I downloaded dockerhub images first, tagged them, and then pushed to the integrated private registry.

But when I deploy an app from image stream, I can still see openshift is trying to pull image from docker.io

##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.lab.local:443
openshift v3.9.0+a96a520-22
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. pull the image locally from a machine that has internet access
```
docker pull docker.io/centos/php-56-centos7:latest
```
2. tag the image and push to private registry
```
docker tag docker.io/centos/php-56-centos7:latest docker-registry.default.svc:5000/openshift/php:5.6
docker push docker-registry.default.svc:5000/openshift/php:5.6
```
3. check the image stream created
```
oc get is php -n openshift -o yaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: 2018-07-07T10:41:46Z
  generation: 1
  name: php
  namespace: openshift
  resourceVersion: "193501"
  selfLink: /apis/image.openshift.io/v1/namespaces/openshift/imagestreams/php
  uid: 58e10bdf-81d2-11e8-bab4-000c29e6c9ea
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/openshift/php
  tags:
  - items:
    - created: 2018-07-07T10:42:11Z
      dockerImageReference: docker.io/centos/php-56-centos7@sha256:f3c95020fa870fcefa7d1440d07a2b947834b87bdaf000588e84ef4a599c7546
      generation: 1
      image: sha256:f3c95020fa870fcefa7d1440d07a2b947834b87bdaf000588e84ef4a599c7546
    tag: "5.6"
```
Although dockerImageRepository is pointing to the private registry, the dockerImageReference uses remote image from "docker.io". When I deploy application from this image stream, I can see openshift is trying to pull image from docker.io which is not accessible in my environment

```
oc describe po/php-1-gzcs2
...
Normal   Pulling                6m                kubelet, node09.lab.local  pulling image "docker.io/centos/php-56-centos7@sha256:f3c95020fa870fcefa7d1440d07a2b947834b87bdaf000588e84ef4a599c7546"
```

##### Current Result
openshift is trying to pull image from docker.io

##### Expected Result
openshift should use image from private registry

How can I make openshift use image from local registry?

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
seems to be working fine for me.

can you share the deploymentconfig yaml for your registry DC?
Did the php imagestream exist before you did your push?

Before push (i imported the default php imagestream so it's got more tags than yours):
https://gist.github.com/bparees/2f0e0a57f77842b7040b9273b3472441#file-gistfile1-txt-L122

after push:
https://gist.github.com/bparees/c6723ef3321691a50da54ca72886a7ac#file-gistfile1-txt-L122

**Comment by yuanlinios** [comment]
I could not reproduce the issue any longer. 
Delete old php image stream and push, the dockerImageRespository and dockerImageReference are now consistent.
