### ISSUE TITLE
`oc logs --all-containers` throws error

### ISSUE THREAD

**Issue by vrutkovs** [openshift/origin#20259]
`oc logs --all-containers` won't show logs for all containsd

##### Version
```
oc v3.11.0-alpha.0+a8517dd-270
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ip-172-18-10-125.ec2.internal:8443
openshift v3.11.0-alpha.0+a8517dd-270
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
1. Run a pod with multiple containers
2. `oc logs --all-containers=true`

##### Current Result
Error:
```
# oc --config=/etc/origin/master/admin.kubeconfig -n openshift-autoheal logs --all-containers=true --tail=50 deployment/autoheal                               
Error from server (BadRequest): a container name must be specified for pod autoheal-7df6b98b66-tzqb9, choose one of: [proxy receiver]
```

##### Expected Result
Shows logs for both containers

##### Additional Information
Works fine for a pod with one container or container name is specified:
```
# oc --config=/etc/origin/master/admin.kubeconfig -n openshift-autoheal logs -c proxy --tail=50 deployment/autoheal                                            
2018/07/09 15:40:34 provider.go:98: Defaulting client-id to system:serviceaccount:openshift-autoheal:autoheal
2018/07/09 15:40:34 provider.go:103: Defaulting client-secret to service account token /var/run/secrets/kubernetes.io/serviceaccount/token
```

This affects openshift-ansible, as it relies on this feature to work correctly in order to display more details

**Comment by liggitt** [comment]
> This affects openshift-ansible, as it relies on this feature to work correctly in order to display more details

this is a new feature in kubectl 1.11, and is not supported on objects other than pods. see https://github.com/kubernetes/kubernetes/pull/66398 for more details, but it is not supported on deployment objects, at least for now.
