### ISSUE TITLE
Nine secrets of new project can't be all created when secrets quota is less than 9

### ISSUE THREAD

**Issue by AvTiMp** [openshift/origin#20254]
##### Version
oc v3.9.14
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift-cluster.example.com:8443
openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. register a new user and  set a  corresponding clusterreousrcequota which has the secrets limit set to 9
2. create a new project

##### Current Result
the new project has three service account, but the num of secrets is always less than 9
##### Expected Result
the new project should has three service accounts (default , deployer, builder) and nine corresponding secrets (each sa has two token secrets and one docker pull secret)

**Comment by jwforres** [comment]
The quota system is behaving as expected.  If you want to allow the default secrets to get created your quota needs to account for them.

**Comment by AvTiMp** [comment]
@jwforres  i mean,  i found that the openshift needs more than nine secret when a new project is created  which is unusual, since only three serviceaccounts  and only nine corresponding secrets are needed when creating project, I didn't say the quota system doesn't perform correctly. I means something unkown creates a secret when a new project occurs
