### ISSUE TITLE
auto-create OpenShift Routes when a Service is created (if there's metadata/annotations on the service)?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#2026]
One of the awesome things about Kubernetes is that the Service, Pods, Replication Controller JSON/YAML can be run on any environment and namespace/project. 

Right now Routes are completely environment and namespace specific since they refer to the globally unique host name to expose the service. However its kinda painful writing/generating lots of JSON for each service; if you've lots of services, thats lots of JSON of the Routes.

It would be nice if either by default, or if some OpenShift metadata/annotation were present on the Service, when a Service gets created OpenShift it would automatically also create a Route for the service on host ${serviceId}.${namespace}.${OPENSHIFT_DOMAIN} where OPENSHIFT_DOMAIN is either a global configuration; or we specify the ${namespace}.${OPENSHIFT_DOMAIN} as an annotation on the Project.

i.e. we could make Services which can be deployed anywhere and if they are deployed on OpenShift then a Route is automatically created.

Folks could add extra annotations to help the generation of the Route; such as session affinity or TLS termination etc. i.e. we can put all the relevant metadata into the Service (as, say, annotations) and then it'll just work in any Kubernetes environment - and then in any OpenShift namespace/project it'd get a Route (if annotated correctly)

**Comment by kargakis** [comment]
@jstrachan shortly you will be able to generate routes from services with `osc expose`.
https://github.com/openshift/origin/pull/2045

**Comment by smarterclayton** [comment]
We've talked about auto creating routes based on metadata on the service.  It should be easy.

**Comment by jstrachan** [comment]
agreed - I think it would really help app developers too; they'd be able to generate standard kubernetes json that works on any kubernetes environment; and then have routes created automatically if on OpenShift (or any other kubernetes environment that wishes the respect the OpenShift route metadata)

**Comment by jstrachan** [comment]
as an aside a workaround for this issue; we've a simple command for java folks to lazily create any missing routes: [mvn fabric8:create-routes](http://fabric8.io/guide/mavenFabric8CreateRoutes.html).

It'd be much nicer for this to happen on the fly by OpenShift though

**Comment by jstrachan** [comment]
how about reusing the loadBalancer flag from kubernetes to indicate whether a Route should be created?

**Comment by smarterclayton** [comment]
I'd be ok with that.  However, loadBalancer should be using the router
anyway for a lot of customer deployments.  @eparis related to what we
discussed yesterday in regards to ingress/egress - if loadBalancer is
served by the routers (or by a router that exists to handle TCP routing)
we'd still need IP allocation in a regular environment.

On Fri, Jul 17, 2015 at 4:20 AM, James Strachan <notifications@github.com>
wrote:

> how about reusing the loadBalancer flag from kubernetes to indicate
> whether a Route should be created?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2026#issuecomment-122213291>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by rawlingsj** [comment]
+1 - it would be great to see this happen.

**Comment by jstrachan** [comment]
I'm wondering if OpenShift should follow the GKE approach of respecting the `type: 'LoadBalancer` on the Service; if that type is set to `LoadBalancer` then auto-create a Route?

Then as a developer making a service which needs an external load balancer (like a web app), you'd just set `type: 'LoadBalancer'` and know your service will work properly on at least GKE and OpenShift. Then any other kubernetes environment should try to respect the LoadBalancer type too

**Comment by jstrachan** [comment]
BTW for now I've patched [our fork of helm](https://github.com/fabric8io/helm) to do this for us when creating a Service which is of type `LoadBalancer` as a workaround. We basically just run `oc expose service cheese` after creating the service if its type is `LoadBalancer` https://github.com/fabric8io/helm/blob/openshift-all/action/openshift.go#L56

**Comment by dustymabe** [comment]
+1 for this feature.

**Comment by smarterclayton** [comment]
I think there's a good precedent for this.  The challenge is identifying which ports to expose.  Will keep this on the list of things to look at.
