### ISSUE TITLE
Update the router to do a periodic refresh of certificates

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#2029]
In order to guarantee that certificates on disk have not changed from what is stored in memory the router should periodically refresh all certificates on disk.  This can be done by writing a new directory and swapping it out with the current directory.

Since this should occur in its own goroutine we need to either ensure that the state is guarded by an RWMutex or it is implemented on the controller level to share the lock that the handlers currently share which guarantees that there will only ever be one reader/writer at a time.

**Comment by smarterclayton** [comment]
Closing due to age.
