### ISSUE TITLE
TestSchedulerWithVolumeBinding race condition detected

### ISSUE THREAD

**Issue by ramr** [openshift/origin#20295]
TestSchedulerWithVolumeBinding fails with race detected during execution of test. 

##### Version
3.11

##### Current Result
Failure - see additional information.

##### Expected Result
Success

##### Additional Information
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler TestSchedulerWithVolumeBinding 18s

go run hack/e2e.go -v -test --test_args='--ginkgo.focus=github\.com\/openshift\/origin\/vendor\/k8s\.io\/kubernetes\/pkg\/scheduler\sTestSchedulerWithVolumeBinding$'

testing.go:699: race detected during execution of test
				
==================
WARNING: DATA RACE
Write at 0x0000024c8500 by goroutine 20:
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler.TestSchedulerWithVolumeBinding()
      /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go:161 +0xb9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c

Previous read at 0x0000024c8500 by goroutine 26:
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/core.podFitsOnNode()
      /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:471 +0x51c
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/core.findNodesThatFit.func1()
      /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:324 +0x289
  github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue.Parallelize.func1()
      /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:47 +0xad

Goroutine 20 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:921 +0x206
  main.main()
      github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/_test/_testmain.go:102 +0x2f0

Goroutine 26 (finished) created at:
  github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue.Parallelize()
      /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:43 +0x13c
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/core.findNodesThatFit()
      /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:348 +0xe94
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/core.(*genericScheduler).Schedule()
      /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:136 +0x4c4
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler.(*Scheduler).schedule()
      github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/_test/_obj_test/scheduler.go:152 +0xeb
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler.(*Scheduler).scheduleOne()
      github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/_test/_obj_test/scheduler.go:419 +0x632
  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler.(*Scheduler).(github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler.scheduleOne)-fm()
      github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/scheduler/_test/_obj_test/scheduler.go:142 +0x41
  github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1()
      /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x6f
  github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xcd
  github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait.Until()
      /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x5a

See build logs : https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19891/test_pull_request_origin_unit/13586/   for more details.

**Comment by jwforres** [comment]
@openshift/sig-pod
