### ISSUE TITLE
_post_repository_binding: update returns status 403

### ISSUE THREAD

**Issue by burrsutter** [openshift/origin#2032]
osc build-logs returns
Successfully built 172.30.17.205:5000/demo3/sinatra-app-example
Successfully pushed 172.30.17.205:5000/demo3/sinatra-app-example

and osc status returns
build 2 succeeded 14 minutes

but nothing shows up in the Image Stream

The logs on the docker registry pod include the following:
http://pastebin.test.redhat.com/280335

**Comment by detiber** [comment]
The original issue was related to the docker registry service missing values for OPENSHIFT_CERT_DATA and OPENSHIFT_KEY_DATA, however the lack of error to the end user and having to dig the error out of the registry pod logs is non-intuitive.

**Comment by ncdc** [comment]
You have to pass `--credentials=/path/to/openshift-registry kubeconfig`

**Comment by ncdc** [comment]
In master, omitting credentials is not allowed for `osadm registry` so this issue should go away in newer builds.

**Comment by ncdc** [comment]
Ah, but we aren't checking that the cert and key data are present in the specified credentials. We'll need to do that.

**Comment by smarterclayton** [comment]
That should be a warning - I can use a registry that takes a different type of credentials if I choose
