### ISSUE TITLE
FAIL: TestStuckMethodCount 

### ISSUE THREAD

**Issue by bparees** [openshift/origin#20330]
```
=== RUN   TestStuckMethodCount
--- FAIL: TestStuckMethodCount (0.02s)
	healthy_gprc_test.go:59: expected 0, got 1
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20318/pull-ci-origin-unit/1444/

/cc @openshift/sig-master

**Comment by soltysh** [comment]
I haven't seen this in a while.
/close
