### ISSUE TITLE
`unknown field "masterCount" in object *config.MasterConfig`

### ISSUE THREAD

**Issue by vrutkovs** [openshift/origin#20336]
API server doesn't recognize `masterCount` setting in master-config.yaml. Not sure if this field needs to be removed, but openshift-ansible specifically sets it.

##### Version
v1.11.0+d4cacc0

##### Steps To Reproduce
1. Check API server logs

##### Current Result
```
E0717 10:51:38.509098       1 helpers.go:133] Encountered config error json: unknown field "masterCount" in object *config.MasterConfig, raw JSON:
{"admissionConfig":{"pluginConfig":{"BuildDefaults":{
...
,"masterCount":3,
...
```
https://s3.amazonaws.com/aos-ci/ghprb/openshift/openshift-ansible/2dcc10a7b4f7486e7903e6aa4f54fd93df2d0498.3.1531823269373004930/artifacts/container_logs/k8s_api_master-api-172.16.69.50_kube-system_d7680114883f7dda4bfa57d530be9b6a_0_00.log

##### Expected Result
No warning

##### Additional Information
That doesn't seem to be breaking anything though

**Comment by mriedmann** [comment]
same here. `oc adm diagnostics` on an updated (from 3.10) 3.11 cluster reports this:
```
EncE1017 07:46:38.012924   11458 helpers.go:134] Encountered config error json: unknown field "masterCount" in object *config.MasterConfig, raw JSON:...
```
It does not seem to affect the cluster but is annoying when hunting other bugs.

**Comment by kameshsampath** [comment]
when configuring all in openshift nodes with OKD 3.11 I see the api server breaking because of this issue and all of sudden access via console and cli is broken.
