### ISSUE TITLE
host 127.0.0.1 doesn't work on any pod of the minishift or even openshift?

### ISSUE THREAD

**Issue by zhangtbj** [openshift/origin#20339]
After I asked minishift guys, they think it should also be an openshift issue, this is the original issue in minishift:
https://github.com/minishift/minishift/issues/2605

I don't have an openshift environment, can you please help take a look if openshift have this issue too.

Thanks a lot!

### General information

  * Minishift version:  `minishift v1.21.0+a8c8b37`
  * OS: Linux / macOS / Windows: `Ubuntu 14.04.5`
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox: `VirtualBox`

### Steps to reproduce

  1. Execute `minishift start --cpus 4 --disk-size 100G --memory 8G --vm-driver virtualbox`
  2. Access any of the pod on minishift
  3. Execute `host 127.0.0.1` or `host -r 127.0.0.1`
  4. 

### Expected
```
uaa/1265515:/# host 127.0.0.1
1.0.0.127.in-addr.arpa domain name pointer localhost.
```

### Actual
```
root@hostpath-provisioner:/go/src/app# host -r 127.0.0.1
Host 1.0.0.127.in-addr.arpa. not found: 3(NXDOMAIN)
root@hostpath-provisioner:/go/src/app# host 127.0.0.1
Host 1.0.0.127.in-addr.arpa. not found: 3(NXDOMAIN)
```

It works fine on minikube
There is no any DNS in minishift to resolve it? Or can I install/config a DNS to resolve it. Or is there anything wrong?

### Logs
```
root@cf-lite-dev:~/backup/scf-deployer# minishift addons list
- admin-user	 : enabled	P(0)
- anyuid	 : enabled	P(0)
- registry-route : enabled	P(0)
- xpaas		 : enabled	P(0)
```

**Comment by gbraad** [comment]
This seems to fail CloudFoundry deployments on OpenShift. The router related pre-check scripts will check that... :(, for example:

https://github.com/cloudfoundry/routing-release/blob/87d5f821179587d0a3da3486165ec08ad6d9c16d/jobs/gorouter/templates/run_gorouter.erb#L12

https://github.com/cloudfoundry/routing-release/blob/dca19fb30607b5044883fbb7c42e84f0f5c147fc/jobs/routing-api/templates/routing-api_ctl.erb#L24

https://github.com/cloudfoundry/routing-release/blob/dca19fb30607b5044883fbb7c42e84f0f5c147fc/jobs/tcp_router/templates/tcp_router_ctl.erb#L116

**Comment by jwforres** [comment]
@openshift/sig-network-edge

**Comment by gbraad** [comment]
Likely an issue on the user's machine.

**Comment by zhangtbj** [comment]
Yes, it works on my Mac. Thanks a lot!
