### ISSUE TITLE
Support sensitive template parameters

### ISSUE THREAD

**Issue by megakoresh** [openshift/origin#20361]
I would like to have a template that asks user for their github credentials and creates secret from those, giving it the appropriate name to be used in build configurations and so on. But the UI does not support sensitive data and pasting unmasked password these days leaves a nasty feeling.

Would be useful to have a feature that allows you to define template parameters as sensitive, so that the UI will automatically mask values user enters there.

##### Version
3.9

##### Steps To Reproduce
Make template with parameters

##### Current Result
All parameters must be unmasked

##### Expected Result
Sensitive parameters are masked

##### Additional Information
N/A

**Comment by spadgett** [comment]
We need a way to set parameters as sensitive in the template itself before we can add this to the UI.

/assign @bparees 
/kind enhancement

**Comment by megakoresh** [comment]
That seems sort of obvious:

```yml
parameters:
- name: PASSWORD
   displayName: Your password
   required: true
   sensitive: true
```

Is there a problem with that?

**Comment by spadgett** [comment]
Right, just remarking that I'm not the right owner because it requires an API change to templates

**Comment by bparees** [comment]
> Is there a problem with that?

not as such, but we've been pretty reluctant to add features to template parameters historically.  (the other common request is a "validation_rule" field that would allow UIs to validate the parameter value supplied by the user against some sort of rule like a regex, or list of allowed values).

We'll leave this open and see where it goes.

**Comment by bparees** [comment]
converting this to a JIRA issue:
https://jira.coreos.com/browse/DEVEXP-120
