### ISSUE TITLE
Can't oc cluster up on vanilla fedora - image openshift/origin-control-plane:v3.10 might be corrupted ?

### ISSUE THREAD

**Issue by pmacko1** [openshift/origin#20368]
Followed https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md and couldn't get oc cluster up to run

##### Version
oc v3.10.0-rc.0+c20e215
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. install fedora on vm
2. install docker as per docs.docker.org
3. install oc as per https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md
4. run `$ oc cluster up`
``$ oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
error: unexpected error inspecting image openshift/origin-control-plane:v3.10``

##### Additional Information
`$sudo docker version`
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:45 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:14:07 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by collinjlesko** [comment]
Would love an update on this, incredibly frustrating...

**Comment by tnozicka** [comment]
Have you checked the prerequisities? https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#prerequisites

Have you tried the `docker` package, I don't think the 18.06.0-ce is supported, not sure if it's causing this issue though.

for me
```
dnf info docker
Last metadata expiration check: 0:00:19 ago on St 15. srpna 2018, 12:32:32 CEST.
Installed Packages
Name         : docker
Epoch        : 2
Version      : 1.13.1
Release      : 61.git9cb56fd.fc28
Arch         : x86_64
Size         : 67 M
Source       : docker-1.13.1-61.git9cb56fd.fc28.src.rpm
Repo         : @System
From repo    : updates
Summary      : Automates deployment of containerized applications
URL          : https://github.com/projectatomic/docker
License      : ASL 2.0
Description  : Docker is an open-source engine that automates the deployment of any
             : application as a lightweight, portable, self-sufficient container that will
             : run virtually anywhere.
             : 
             : Docker containers can encapsulate any payload, and will run consistently on
             : and between virtually any server. The same container that a developer builds
             : and tests on a laptop will run at scale, in production*, on VMs, bare-metal
             : servers, OpenStack clusters, public instances, or combinations of the above.
```

**Comment by pmacko1** [comment]
Hi @tnozicka, thanks for the message. Yes I've satisfied the prereqs.
```
asdf@localhost ~]$ dnf info docker-ce
Last metadata expiration check: 0:02:11 ago on Wed 15 Aug 2018 12:42:55 PM CEST.
Installed Packages
Name         : docker-ce
Version      : 18.06.0.ce
Release      : 3.fc28
Arch         : x86_64
Size         : 168 M
Source       : docker-ce-18.06.0.ce-3.fc28.src.rpm
Repo         : @System
From repo    : docker-ce-stable
Summary      : The open-source application container engine
URL          : https://www.docker.com
License      : ASL 2.0
Description  : Docker is an open source project to build, ship and run any application
             : as a lightweight container.
             : 
             : Docker containers are both hardware-agnostic and platform-agnostic. This
             : means they can run anywhere, from your laptop to the largest cloud
             : compute instance and everything in between - and they don't require you
             : to use a particular language, framework or packaging system. That makes
             : them great building blocks for deploying and scaling web apps,
             : databases, and backend services without depending on a particular stack
             : or provider.
```

**Comment by pmacko1** [comment]
I have re-installed the vm and I had problems installing the docker-ce, `sudo dnf update` and subsequent installing on docker-ce fixed the problem. 

Although, I had to use the second option for setting the insecure registries parameter
```or edit the /etc/docker/daemon.json file and add the following:
{
   "insecure-registries": [
     "172.30.0.0/16"
   ]
}```

**Comment by tnozicka** [comment]
using `18.06.0.ce` doesn't satisfy the requirement for `==1.13` although it may work

> I can now run oc cluster up. Couldn't replicate the bug. I'm using qemu/kvm with fedora from getfedora.org.

Anyways since you can't reproduce it and it is working for you I am gonna close the bug.
/close

**Comment by nimrodshn** [comment]
`sudo systemctl start docker.service` - Solved it for me.
