### ISSUE TITLE
Haproxy stats non tls

### ISSUE THREAD

**Issue by mjudeikis** [openshift/origin#20375]
I might miss this on the docs but:

Haproxy template stats endpoint is non tls:
https://github.com/openshift/origin/blob/6c639af3985de43e99fa34f260f9a0a79df87155/images/router/haproxy/conf/haproxy-config.template#L130-L135

And most of our Prometheus examples expects tls:
https://github.com/openshift/origin/blob/60a595ad74ae242b5dc91c7b0915805b6b4dfe96/examples/prometheus/prometheus.yaml#L712

the result is not working haproxy metrics in Prometheus out of the box. 
```
sh-4.2$ curl -u admin:xxxxxx https://localhost:1936/metrics
curl: (35) TCP connection reset by peer

sh-4.2$ curl -u admin:xxxxxx http://localhost:1936/metrics
# HELP apiserver_audit_event_total Counter of audit events generated and sent to the audit backend.
# TYPE apiserver_audit_event_total counter
apiserver_audit_event_total 0
# HELP apiserver_client_certificate_expiration_seconds Distribution of the remaining lifetime on the certificate used to authenticate a request.
```

**Comment by mjudeikis** [comment]
@openshift/sig-networking ptal.

**Comment by pweil-** [comment]
@thanasisk FYI
