### ISSUE TITLE
Missing /sys/fs/cgroup/cpuacct,cpu 

### ISSUE THREAD

**Issue by Bubblemelon** [openshift/origin#20398]
```
kubelet.go:1312] Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/cpuacct,cpu: no such file or directory
```

This may not be a kubelet issue, as this also occurred with `runc`.

#### Version
`openshift/origin-node:latest` i.e. `openshift v3.11.0-alpha.0+90e2736-260`

#### [Steps To Reproduce](https://github.com/openshift/os/issues/145#issuecomment-403602118)
1. Complete [Libvirt-howto guide](https://github.com/coreos/tectonic-installer/blob/master/Documentation/dev/libvirt-howto.md)
2. Install the latest RHCOS image http://aos-ostree.rhev-ci-vms.eng.rdu2.redhat.com/rhcos/images/cloud/latest/
3. Add ` --cgroup-driver=systemd \` to `kubelet.service` within master node:
```
[Unit]
Description=Kubernetes Kubelet
...

[Service]
...

ExecStart=/usr/bin/docker \
  run \
    .
    .
  "openshift/origin-node:latest" \
    kubelet \
      .
      .
      . 
      --cgroup-driver=systemd \
```
3. `sudo systemctl daemon-reload && sudo systemctl restart kubelet`
4.  `journalctl -u docker` and `journalctl -u kubelet` shows the same output:

```
kubelet.go:1312] Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/cpuacct,cpu: no such file or directory                 
kubelet.service: main process exited, code=exited, status=255/n/a                                                                                                 
Unit kubelet.service entered failed state.
kubelet.service failed.
```
#### Links related to this issue

Debug logs and Github discussion:  https://github.com/openshift/os/issues/145 
Jira Issue Card discussion: https://projects.engineering.redhat.com/browse/COREOS-220

**Comment by jwforres** [comment]
@openshift/sig-pod

**Comment by sjenning** [comment]
What OS name, OS version, and kernel version are you running?

**Comment by Bubblemelon** [comment]
```bash
cat /etc/os-release

NAME="Red Hat CoreOS"
VERSION="3.10"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION_ID="3.10"
PRETTY_NAME="Red Hat CoreOS 3.10"
```
```bash
rpm -qa kernel 
kernel-3.10.0-862.2.3.el7.x86_64
```
```
$ pwd
/sys/fs/cgroup/cpu,cpuacct
$ ls
cgroup.clone_children  cgroup.sane_behavior  cpuacct.usage_percpu  cpu.rt_period_us   cpu.stat           system.slice
cgroup.event_control   cpuacct.stat          cpu.cfs_period_us     cpu.rt_runtime_us  notify_on_release  tasks
cgroup.procs           cpuacct.usage         cpu.cfs_quota_us      cpu.shares         release_agent      user.slice
```
Please see referenced issue above, if you haven't already :smile: 

There's a [workaround for this problem](https://github.com/kubernetes/kubernetes/issues/32728#issuecomment-252469277) but we might as well resolve this error.

```bash
  sudo mount -o remount,rw '/sys/fs/cgroup'
  sudo ln -s /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/cpuacct,cpu
```
