### ISSUE TITLE
 [Question] Will Origin work with the data service Apache CouchDB?

### ISSUE THREAD

**Issue by c0ntainerize** [openshift/origin#20390]
I saw under database service's there is MongoDB. I was wondering for development if I were to use [Apache CouchDB](https://couchdb.apache.org/) with Origin would there be any foreseeable issues I might run into? 
![origin](https://user-images.githubusercontent.com/41249167/43061895-d38c74c0-8e0b-11e8-81ce-2c505a844488.png)

**Comment by jwforres** [comment]
That list is just some of what we ship and test ourselves, that doesn't mean other DBs won't work. The main thing to consider is that openshift's default security profiles lock down the uid that container processes can run as. Take a look at SCCs for more information: https://developers.redhat.com/blog/2016/10/21/understanding-openshift-security-context-constraints/

This dockerfile example works around that https://hub.docker.com/r/andrewklau/couchdb/
