### ISSUE TITLE
Volumes dir selinux denials when using openshift binary

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#2041]
Starting openshift via the binary doesn't set the correct selinux labels on the openshift.local.volumes dir, meaning volumes are not writable until chcon'ing volumes dir. Should be labelled with `svirt_sandbox_file_t` I think.

**Comment by ncdc** [comment]
The code is in place: https://github.com/openshift/origin/blob/f19f36255415b28d95e179385d7d4f9461bcca16/pkg/cmd/server/kubernetes/node.go#L122. I'm running via the binary exclusively (`sudo _output/local/go/bin openshift start`) in enforcing mode and I haven't seen issues since we put the chcon code in place. Can you confirm how you're running it?

**Comment by ncdc** [comment]
```
$ sudo ls -laZ openshift.local.volumes/pods/6a2a0297-f0ba-11e4-95f1-080027f1df16/volumes/kubernetes.io~empty-dir/registry-storage
drwxr-x---. root root unconfined_u:object_r:svirt_sandbox_file_t:s0 .
drwxr-x---. root root unconfined_u:object_r:svirt_sandbox_file_t:s0 ..
```

**Comment by ncdc** [comment]
Also, what OS?

**Comment by jimmidyson** [comment]
Started from scratch again & it seems to have worked as expected. Not sure what happened last time. Sorry for the erroneous bug report. If it resurfaces, I'll reopen. Thanks!

**Comment by jimmidyson** [comment]
Reopening as this has just happened again on Fedora 21 with docker 1.6

**Comment by pmorie** [comment]
The problem is that the code that drives the rootcontext option of the tmpfs mount used by the secret volume plugin uses the root dir (`/var/lib/openshift` in this case) to drive the context, not the volume dir.

**Comment by pmorie** [comment]
For now the workaround is to `chcon -t svirt_sandbox_file_t /var/lib/openshift`
