### ISSUE TITLE
Cannot modify existing cluster role to refer to CRD in 3.9

### ISSUE THREAD

**Issue by miminar** [openshift/origin#20415]
In 3.9, it's no longer possible to modify clusterroles `admin`, `edit` and `view`.

In 3.7, one could for example extend the admin clusterrole to permit updates to a CRD:

    $ oc patch --type=json clusterrole admin \
        -p '[{"op":"add", "path":"/rules/-", "value":{
          "apiGroups":["example.com"],
          "resources":["mycluster","mc"],
          "verbs":["create","delete","get","list","update","watch"]
        }}]'
    clusterrole "admin" patched
    
The same command executed on 3.9 produces the same output but does nothing.
And the same applies to `oc edit`.

If it's truly against the current rules, the commands should error out instead of lying.

BTW the server actually sends a response with the full clusterrole object containing the added entry.
Next GET retrieves the same old role with resourceVersion bumped.

**Comment by miminar** [comment]
Confirmed on 3.10 as well.

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by liggitt** [comment]
These roles are now aggregated roles. To contribute additional permissions to them, create distinct appropriately labeled clusterroles,  and the aggregating controller will combine their permissions into the admin, edit, or view role. 

See https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles  for more details

**Comment by enj** [comment]
We have better docs https://docs.openshift.org/latest/admin_guide/custom_resource_definitions.html#creating-aggregated-cluster-role-crd_admin-guide-custom-resources

**Comment by miminar** [comment]
Thanks for the pointers. That's what I needed.
I still find it unfortunate that changes are silently dropped on edit/patch though.
