### ISSUE TITLE
eclipse che on openshift cluster cannot create workspace because permission denied

### ISSUE THREAD

**Issue by kingkeivn** [openshift/origin#20424]
I had deploy openshift3.9 cluster on my computer (master node:1,slave node:2)

oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

I tried to deply a example which name is cakephp-ex on this cluster ,and it worked fine.

I tring  to deploy eclipse che on this cluster.
steps are as fllows.

oc create serviceaccount che -n che2
oc adm policy add-scc-to-user anyuid system:serviceaccount:che2:che
oc adm policy add-scc-to-user privileged system:serviceaccount:che2:che
oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:che2:che
oc adm policy add-scc-to-group anyuid system:authenticated

oc DEPLOY_ROOT_URL=https://raw.githubusercontent.com/eclipse/che/master/deploy/openshift/templates
curl -fsSL ${DEPLOY_ROOT_URL}/che-server-template.yaml -o che-server-template.yaml
curl -fsSL ${DEPLOY_ROOT_URL}/pvc/che-server-pvc.yaml -o che-server-pvc.yaml
oc create new-project che2
oc new-app -f che-server-template.yaml -p ROUTING_SUFFIX=master.10.121.198.81.nip.io
oc apply -f pvc/che-server-pvc.yaml
oc set volume dc/che --add -m /data --name=che-data-volume --claim-name=che-data-volume
I tring to add parameter "privileged" in che yaml file.like this :
securityContext:
  privileged: true
  allowPrivilegeEscalation: true

Then eclipse che can show on the browse.
There was an error when I tried to create a workspace on eclipse che.
error message is shown below:
Loading...
mkdir -p /tmp/bootstrapper/ /workspace_logs/bootstrapper
mkdir: cannot create directory ‘/workspace_logs/bootstrapper’: Permission denied
command terminated with non-zero exit code: Error executing in Docker Container: 1
Bootstrapping of machine dev-machine failed. Cause: mkdir: cannot create directory ‘/workspace_logs/bootstrapper’: Permission denied
command terminated with non-zero exit code: Error executing in Docker Container: 1

sameone can resove this issue?

**Comment by kingkeivn** [comment]
logs in che pod :
Machine dev-machine error from owner=che env=default workspace=workspacejxtcmersa5p69t8g text=`mkdir: cannot create directory ‘/workspace_logs/bootstrapper’: Permission denied

this is pvc's yaml:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
annotations:
pv.kubernetes.io/bind-completed: "yes"
pv.kubernetes.io/bound-by-controller: "yes"
creationTimestamp: 2018-07-25T09:16:48Z
labels:
che.workspace.volume_name: projects
che.workspace_id: workspaces8nz1anpko35tdj2
name: claim-che-workspace-wpmbw7xx
namespace: che2
resourceVersion: "1441761"
selfLink: /api/v1/namespaces/che2/persistentvolumeclaims/claim-che-workspace-wpmbw7xx
uid: 75483633-8feb-11e8-967c-0cda411da757
spec:
accessModes:

ReadWriteOnce
resources:
requests:
storage: 1Gi
volumeName: pv0005
status:
accessModes:
ReadWriteOnce
ReadWriteMany
ReadOnlyMany
capacity:
storage: 3Gi
phase: Bound

this pvc provider with eclipse che .
And I create the pv:
pv yaml :
apiVersion: v1
kind: PersistentVolume
metadata:
annotations:
pv.kubernetes.io/bound-by-controller: "yes"
creationTimestamp: 2018-07-25T09:17:45Z
labels:
volume: pv0005
name: pv0005
resourceVersion: "1441759"
selfLink: /api/v1/persistentvolumes/pv0005
uid: 9794ef50-8feb-11e8-967c-0cda411da757
spec:
accessModes:

ReadWriteOnce
ReadWriteMany
ReadOnlyMany
capacity:
storage: 3Gi
claimRef:
apiVersion: v1
kind: PersistentVolumeClaim
name: claim-che-workspace-wpmbw7xx
namespace: che2
resourceVersion: "1441575"
uid: 75483633-8feb-11e8-967c-0cda411da757
hostPath:
path: /opt/data
type: ""
persistentVolumeReclaimPolicy: Recycle
status:
phase: Bound

**Comment by kingkeivn** [comment]
[#10530](https://github.com/eclipse/che/issues/10530)

**Comment by kingkeivn** [comment]
[I asked a question in eclipse/che](https://github.com/eclipse/che/issues/10530)

**Comment by kingkeivn** [comment]
this is create workspace's yaml provider by eclipse che
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: anyuid
    org.eclipse.che.container.container.machine_name: dev-machine
  creationTimestamp: 2018-07-26T09:25:11Z
  generateName: workspace0finsrj6jhac6ojm.dockerimage-7c98578dc4-
  labels:
    che.original_name: dockerimage
    che.workspace_id: workspace0finsrj6jhac6ojm
    pod-template-hash: "3754134870"
  name: workspace0finsrj6jhac6ojm.dockerimage-7c98578dc4-pfrm2
  namespace: che1
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: workspace0finsrj6jhac6ojm.dockerimage-7c98578dc4
    uid: a61ae409-90b5-11e8-8372-0cda411da757
  resourceVersion: "1634919"
  selfLink: /api/v1/namespaces/che1/pods/workspace0finsrj6jhac6ojm.dockerimage-7c98578dc4-pfrm2
  uid: cb814559-90b5-11e8-8372-0cda411da757
spec:
  containers:
  - env:
    - name: CHE_MACHINE_TOKEN
    - name: CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS
      value: -XX:MaxRAM=600m -XX:MaxRAMFraction=1 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
        -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
        -Dsun.zip.disableMemoryMapping=true -Xms50m -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
    - name: JAVA_OPTS
      value: -XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
        -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
        -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
    - name: CHE_PROJECTS_ROOT
      value: /projects
    - name: CHE_API
      value: http://che-che1.master.10.121.198.81.nip.io/api
    - name: MAVEN_OPTS
      value: -XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
        -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
        -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
    - name: CHE_WORKSPACE_LOGS_ROOT__DIR
      value: /workspace_logs
    - name: CHE_MACHINE_NAME
      value: dev-machine
    - name: CHE_API_INTERNAL
      value: http://che-che1.master.10.121.198.81.nip.io/api
    - name: CHE_WORKSPACE_ID
      value: workspace0finsrj6jhac6ojm
    - name: CHE_API_EXTERNAL
      value: http://che-che1.master.10.121.198.81.nip.io/api
    - name: CHE_AUTH_ENABLED
      value: "false"
    - name: CHE_WORKSPACE_MAVEN__SERVER__JAVA__OPTIONS
      value: -XX:MaxRAM=128m -XX:MaxRAMFraction=1 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
        -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
        -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
    image: eclipse/ubuntu_jdk8
    imagePullPolicy: Always
    name: container
    ports:
    - containerPort: 4401
      protocol: TCP
    - containerPort: 4412
      protocol: TCP
    - containerPort: 8080
      protocol: TCP
    - containerPort: 4403
      protocol: TCP
    - containerPort: 4411
      protocol: TCP
    - containerPort: 8000
      protocol: TCP
    resources:
      limits:
        memory: "2147483648"
      requests:
        memory: "2147483648"
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /projects
      name: claim-che-workspace-jzbxnyqt
      subPath: workspace0finsrj6jhac6ojm/projects
    - mountPath: /workspace_logs
      name: claim-che-workspace-swqvs3l4
      subPath: workspace0finsrj6jhac6ojm/che-logs-dockerimage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-zkpd2
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-mpk75
  nodeName: node2.10.121.198.83.nip.io
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c15,c10
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: claim-che-workspace-jzbxnyqt
    persistentVolumeClaim:
      claimName: claim-che-workspace-jzbxnyqt
  - name: claim-che-workspace-swqvs3l4
    persistentVolumeClaim:
      claimName: claim-che-workspace-swqvs3l4
  - name: default-token-zkpd2
    secret:
      defaultMode: 420
      secretName: default-token-zkpd2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-07-26T09:25:11Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-07-26T09:25:15Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-07-26T09:25:11Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://5416d5ac39e8307c1b69f83f16ffca47d353ce2fbe16c437f3364fd21d3e785e
    image: docker.io/eclipse/ubuntu_jdk8:latest
    imageID: docker-pullable://docker.io/eclipse/ubuntu_jdk8@sha256:99752f0ab6bc83abdf54fd7f7679a782fa3ba97de1682676b6b4199db194a085
    lastState: {}
    name: container
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-07-26T09:25:15Z
  hostIP: 10.121.198.83
  phase: Running
  podIP: 10.129.1.164
  qosClass: Burstable
  startTime: 2018-07-26T09:25:11Z

**Comment by kingkeivn** [comment]
I resolve it by mount volumes with nfs

**Comment by davidwindell** [comment]
@zeyuanpinghe do you mind me asking how you solved this? I am having a similar problem (permission denied on /plugins/sidecars) on a non-openshift infrastructure using a node persistent volume path. Thanks!

**Comment by zeyuanpinghe** [comment]
> @zeyuanpinghe do you mind me asking how you solved this? I am having a similar problem (permission denied on /plugins/sidecars) on a non-openshift infrastructure using a node persistent volume path. Thanks!

Open permissions on mounted pv volumes
