### ISSUE TITLE
How to expose UDP ports range for pod/container

### ISSUE THREAD

**Issue by testuser-2018** [openshift/origin#20425]
Hello gentlemen.

I have an issue with making a pod working with Kurento Media Server. All UDP ports should be opened but there is no mention in the official documents how it can be done. I have found a mention about hostNetwork mode of pod in Kubernetes but not in OpenShift. Otherwise I have found hostNetwork in Openshift Pod API but when I try to turn this mode on many errors occur.
Could anybody help with opening all pod UDP ports if this is of course possible.
OpenShift Container Platform cluster is deployed on AWS cloud service.

Thank you in advance.

**Comment by adambkaplan** [comment]
Please provide the YAML for your pod or deployment config (with anything sensitive redacted), as well as any logs from the pod.

**Comment by testuser-2018** [comment]
I will provide the required information certainly as soon as possible but I have one clarifying question.
By API definition (https://docs.openshift.com/container-platform/3.9/rest_api/api/v1.Pod.html) a pod schema creation has hostNetwork field with the following annotation: "If this option is set the ports must be specified". In what field should they be specified and is it possible to specify a range?
Thanks.

**Comment by sjenning** [comment]
since the OpenShift router only handles HTTP(S) traffic, UDP routing needs to be don with kubernetes Services.  If you want to connect to an on-cluster UDP service from inside the cluster, you should use a Service with type `NodePort` (or `LoadBalancer`) if you are on GCP/AWS.

**Comment by adambkaplan** [comment]
There is an existing issue/debate upstream for this use case - kubernetes/kubernetes#23864

**Comment by testuser-2018** [comment]
Hello community.
Not exactly, the similar debate was the following https://github.com/openshift/origin/issues/7609 but it ended without any solution. I don't need to open certain ports even though there are a lot of them but I need to open all UDP ports as it's said in official Kubernetes documentation. So as I understand the only way is to define each port of 65536 udp ports using NodePort service type?

**Comment by sjenning** [comment]
Yes, but that is a weird use case and not the intended use for NodePort (i.e. to forward all ports on all nodes to the same ports on a single service in the cluster)

https://docs.openshift.com/container-platform/3.10/dev_guide/expose_service/expose_internal_ip_nodeport.html

Note that, by default, the NodePort range is only 30000-32767

**Comment by testuser-2018** [comment]
I've got it, @sjenning.
And what about any udp port availability inside a cluster. Can I use this behaviour and redirect ingress traffic using OS ip route from node server interface inside the cluster?
Thank you in advance.

**Comment by nkt** [comment]
/remove-lifecycle stale
There is a proposal to kubernetes https://github.com/kubernetes/kubernetes/commit/2cf5af1f8cc33e2d22ed1968aca05e5323ef9a0b?short_path=780cede#diff-780cede107ebaf89f85c7d6333912275
