### ISSUE TITLE
the endpoint couldn't be changed when using headless svc without selector

### ISSUE THREAD

**Issue by AvTiMp** [openshift/origin#20422]
[provide a description of the issue]

##### Version
```
oc v3.9.14
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
1.  create a headless svc without the selector, and an endpoint with same name
2.  use a sa to modify the endpoint (in pod)  by adding a Pod ip in same project to its subset

##### Current Result
the server deny  this operation
##### Expected Result
it should do allow this

**Comment by jwforres** [comment]
@openshift/sig-networking
