### ISSUE TITLE
Support `osc delete deploymentcontroller/foo --cascade`

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#2043]
Upstream recently added a `--cascade` flag for `kubectl delete` that cleans up resources logically owned by the deleted thing.  For instance, deleting a replication controller with `--cascade` cleans up the pods as well.

@ironcladlou  Does this sound reasonable for deploymentconfigs?  It's kind of annoying to chase everything down.

**Comment by ironcladlou** [comment]
@deads2k 

#1657 tracks the requirements for deleting a single DeploymentConfig. It's not clear to me whether there would be a distinction between `--cascade` and a plain `delete` in this case; the behavior we desribed so far seems like an implicit cascade.

**Comment by liggitt** [comment]
I think upstream made `--cascade=true` the default, which seems dangerous to me

**Comment by deads2k** [comment]
> I think upstream made --cascade=true the default, which seems dangerous to me

Don't you think that's likely to be the intent almost all the time?  Delete this thing and all the bits that descended from it?  I'm hard pressed to think of a case where I'd want to delete a replicationcontroller, but keep the pods it created.

**Comment by liggitt** [comment]
For some things, yes. There's also discussion about adding a reaper for deploymentconfigs. I'm not as sure that deleting a deployment config should delete all created deployments by default.

**Comment by kargakis** [comment]
> There's also discussion about adding a reaper for deploymentconfigs.

First thing I have to do after https://github.com/openshift/origin/pull/2158 gets merged. (Resizer is a prerequisite for implementing the reaper for dcs). It will probably get in through https://github.com/openshift/origin/pull/1944

**Comment by liggitt** [comment]
@kargakis it will be good to have the option to cascade from deploymentconfig to clean up deployments, I'm just not sure that should be the default. I don't think we'll get to have different defaults for `--cascade` for different objects

**Comment by kargakis** [comment]
@liggitt can you describe a case where you would want to delete a dc but not the resources it manages?

**Comment by ironcladlou** [comment]
I'm not sure what user experience is expected when a deploymentConfig is deleted while leaving orphaned deployments. You're not going to be able to manipulate them via the API/tooling other than as plain RCs, and if a new deploymentConfig is created matching the name of the old one used by the orphans, I'm not sure the behavior is going to be predictable (without introducing extra logic to make the new config look like the old one in terms of the old's LatestVersion, etc).

The easiest way to keep the system state consistent at the moment would be to make the deployments live and die with their config. I'm not saying this is necessarily the best choice long term, but I'm a bit concerned about us getting into unsupportable states in the near term.

**Comment by liggitt** [comment]
> You're not going to be able to manipulate them via the API/tooling other than as plain RCs

Why not?

**Comment by ironcladlou** [comment]
>>You're not going to be able to manipulate them via the API/tooling other than as plain RCs
>Why not?

I should have been more specific: you won't be able to manipulate them via the deployment specific APIs. For example, rollbacks, redeployments/inspection via the new `deploy` command, viewing the deployment topology with `describe`... all of these things are framed in terms of a deploymentConfig. If the config's gone, you're left with generic RC APIs.

**Comment by ironcladlou** [comment]
Can somebody explain the use case where you want to delete a config but not the deployments for the config?

**Comment by smarterclayton** [comment]
This is fixed
