### ISSUE TITLE
Expose console URL via the API (and oc)

### ISSUE THREAD

**Issue by rhuss** [openshift/origin#20447]
It would be awesome if the URL for the console could be queried from the API. In our use case we want to link from our UI to certain pod logs in the console. However as we can determine reliably the URL to the console we have to force this URL as input in our installation. If this data would be queriable somehow (via the API, ideally exposed also via `oc`), then we could save this step, making the installation easier.

##### Version

```
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://192.168.64.84:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```

**Comment by jwforres** [comment]
It is unlikely we would make an API endpoint or CLI command specifically for this. The new console we are working towards will have a different deployment model and will not be proxied through the masters, and instead has a Route in front of it. So if you are able to view that route you'd be able to discover the hostname for the console.

Longer term we are having some discussions about this problem generally, how do you discover the public hostnames for cluster infrastructure components.

cc @smarterclayton @spadgett

**Comment by spadgett** [comment]
/remove-lifecycle stale
/assign @benjaminapetersen 

We should consider putting the public URL of the console in a config map in 4.0. Our operator should know what it is.

**Comment by spadgett** [comment]
/remove-lifecycle stale
/close

In OpenShift 4.1, the console URL is in the `console-public` config map in the `openshift-config-managed` namespace with key `consoleURL`. All authenticated users can read this config map. You can get the URL using oc with the command:

```
$ oc whoami --show-console
```

**Comment by rhuss** [comment]
fyi @zregvart , might be useful for the integration of the console link into syndesis activity tracking view --> https://github.com/openshift/origin/issues/20447#issuecomment-511042444
