### ISSUE TITLE
Failed to create app with new-app when quota is set

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#20445]
Stumbled upon this when trying to reproduce different quota bug. In latest master, when you create quota with following limits:

```
[mfojtik@dev ~]$ oc get quota compute-resources -o yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: 2018-07-27T08:40:36Z
  name: compute-resources
  namespace: kareiva-2vts-syst
  resourceVersion: "3210"
  selfLink: /api/v1/namespaces/kareiva-2vts-syst/resourcequotas/compute-resources
  uid: bbb360ab-9178-11e8-8dfe-001c421d1186
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 24Gi
    pods: "35"
    requests.cpu: 500m
    requests.memory: 24Gi
status:
  hard:
    limits.cpu: "4"
    limits.memory: 24Gi
    pods: "35"
    requests.cpu: 500m
    requests.memory: 24Gi
  used:
    limits.cpu: "0"
    limits.memory: "0"
    pods: "0"
    requests.cpu: "0"
    requests.memory: "0"
```

And then you try to create an app (using new-app examples):

```
$ oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git
```

The Build gets into a "failed" state with following event:

```
Events:
  Type		Reason		Age			From			Message
  ----		------		----			----			-------
  Warning	FailedCreate	18s (x14 over 59s)	build-controller	Error creating: pods "ruby-ex-1-build" is forbidden: failed quota: compute-resources: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```

Additional concerning thing is that while the build is "failed", the number of events are increasing over time, which might suggest that the controller is still trying to create the pod? I think when the build is failed, the controller should not requeue?

**Comment by mfojtik** [comment]
Do we need to set some reasonable resource limit defaults for the builder pods?

**Comment by bparees** [comment]
>  I think when the build is failed, the controller should not requeue?

It's a failure to create the pod, since we don't analyze the specific reason why, we will retry creating the pod (via requeue), so i don't think this behavior is incorrect.  Determining what is a "retryable" failure for a pod creation is going to be difficult (not to mention the condition is correctable by adding a default limit to your project, right?)

> Do we need to set some reasonable resource limit defaults for the builder pods?

I'm very against this.  We never manage to pick correct defaults and if you don't have a quota then you're going to complain that we are artificially limiting you or broke your app because the limit is too low.

This isn't going to be the only place this problem shows up..if you have no project defaults, then you're going to have trouble creating all manner of workload resources, no?

About the only thing i'd consider doing here is allowing you to pass --request and --limit args to explicitly set it to something, but in general our rule on new-app at this point has been "if you need more than what it does today, run oc new-app -o yaml and tweak the output (or use oc edit after creating the resources)"

**Comment by mfojtik** [comment]
>> I think when the build is failed, the controller should not requeue?
> It's a failure to create the pod, since we don't analyze the specific reason why, we will retry creating > the pod (via requeue), so i don't think this behavior is incorrect. Determining what is a "retryable" > failure for a pod creation is going to be difficult (not to mention the condition is correctable by adding a default limit to your project, right?)

I would think that when the build is reported as "Failed", it is failed and it can't transition to "Succeeded" anymore. It should add some backoff maybe and keep the Build as "pending" (and report the events) and after some time it should move it to Failed and stop retries?

 > I'm very against this. We never manage to pick correct defaults and if you don't have a quota then you're going to complain that we are artificially limiting you or broke your app because the limit is too low.

To me the inability to create a build, even if I have enough quota/resources just because there are some limits set is concerning. How can a user fix it so the build will run?

**Comment by bparees** [comment]
> I would think that when the build is reported as "Failed", it is failed and it can't transition to "Succeeded" anymore.

it can, if you fix the problem that's blocking the build from progressing.

>  It should add some backoff maybe and keep the Build as "pending" (and report the events) and after some time it should move it to Failed and stop retries?

requeuing already has backoff built in, and it should stop retrying after 15 requeues.  I'm not sure how long that takes, i think the backoff peaks at a minute so it might take 10-15 minutes to retry it 15 times.

> To me the inability to create a build, even if I have enough quota/resources just because there are some limits set is concerning. How can a user fix it so the build will run?

edit the build to add resource limits

or cancel the build and edit the buildconfig and rerun the build

or add default project limits to your project

**Comment by bparees** [comment]
(is the build actually in a failed state?  i would expect the build itself is in phase new or pending since it hasn't created the pod yet)

**Comment by mfojtik** [comment]
@bparees what I saw was that the build is in Failed state (and it did not succeeded creating the pod ;-).

**Comment by bparees** [comment]
@mfojtik you sure?  here's what i see:

$ oc get builds -w
NAME                  TYPE      FROM      STATUS                       STARTED   DURATION
ruby-sample-build-1   Source    Git       New (CannotCreateBuildPod)             

and after i deleted the quota, the build eventually transitioned into a running state (presumably creating a default limit would have also worked).

**Comment by bparees** [comment]
closing this based on my last update (that the build remains in a "new" state and can be coaxed to proceed by fixing the issue that is preventing the pod from being created).
