### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by Kisen-Chin** [openshift/origin#20442]
[provide a description of the issue]

##### Version
[root@master ~]# oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
When I developing my website. I'd like to use "iFrame" tag to show openshift in my own website. But unfortunatly, I got this error: "Refused to display in a frame because it set 'X-Frame-Options' to 'DENY'"  
Does anyone knows how to solve this problem? I searched many pages and told me to set Nginx/Apache. But I can't find the correct conf file which running for openshift.
Could anyone help me?

**Comment by jwforres** [comment]
we intentionally set this in core console server code, its to help avoid clickjacking attacks against web console users. If you insist on changing this you would need to front the console with something that can change response headers and strip the header off yourself.

@openshift/sig-user-interface

**Comment by Kisen-Chin** [comment]
@jwforres  hi,
can I modify the openshift source code to discard "Xframe Options"? or change the "Xframe options" from "deny" to "allow" or something elese? 
For your reply, it seems that I need to modify the response header instead of change openshift origin source code?

**Comment by jwforres** [comment]
It is set in the web console server code https://github.com/openshift/origin-web-console-server/blob/5ae5aa17fce4769a686135da5744a92797efd52f/pkg/assets/handlers.go#L60

We wouldn't accept any changes to this, but yes you could alter this in your own fork and rebuild the console server image. There are a number of proxies you could set up that do header manipulation, which would let you do this without requiring code changes.

I would still highly discourage allowing iframe-ing of the console.

**Comment by benjaminapetersen** [comment]
@Kisen-Chin definitely do your [clickjacking](https://www.owasp.org/index.php/Clickjacking) homework before trying this...

**Comment by david-martin** [comment]
> I would still highly discourage allowing iframe-ing of the console.

@jwforres Other than to prevent clickjacking, are there other reasons you would discourage iframe-ing the console?
Is there anything that would be broken in that scenario?

I'm looking at iframing a different service that is using an OAuthClient in OpenShift.
For the oauth flow to succeed in the iframe, it needs to redirect to the web console (standard stuff).
Right now I'm wondering what the chance is of getting a change merged where you could configure the value for the X-Frame-Options header so it could be locked down to specific host(s).

**Comment by spadgett** [comment]
> For the oauth flow to succeed in the iframe, it needs to redirect to the web console (standard stuff).

It shouldn't need to redirect to web console... Are you sure it's not the OAuth server that's setting `X-Frame-Options` in your case?

**Comment by david-martin** [comment]
> It shouldn't need to redirect to web console... Are you sure it's not the OAuth server that's setting `X-Frame-Options` in your case?

Good question.

This is the error.

```
Refused to display 'https://master.blablabla.openshiftworkshop.com/oauth/authorize/approve?.............' in a frame because it set 'X-Frame-Options' to 'deny'.
```

**Comment by spadgett** [comment]
Yeah, that's the OAuth server setting the header, not console. I believe `X-Frame-Options` is always set, and it's not configurable.

cc @enj

**Comment by david-martin** [comment]
Thanks @spadgett @enj
