### ISSUE TITLE
`openshift start node` taxes docker daemon

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#2044]
Just running idle on first start (no pods, replication controllers, etc), makes the docker daemon (Docker version 1.6.0, build 3eac457/1.6.0) take 50% of one 3.5GHz i7 core on Fedora21.  The openshift node process is idling near zero.

@smarterclayton Is this expected?  I wouldn't've noticed, but my fan is a little loud.

**Comment by ncdc** [comment]
If you comment out the line that requires 1.6 and downgrade to 1.5, any difference in behavior?

**Comment by deads2k** [comment]
> If you comment out the line that requires 1.6 and downgrade to 1.5, any difference in behavior?

I don't have a full dev env here, (running off the images from dockerhub).  I'll see what I can put together on Monday to try.

**Comment by smarterclayton** [comment]
I've seen similar.  Could be a daemon thing.
