### ISSUE TITLE
cluster_up_down.md#linux suggests that docker should be installed from platform repos - potential for outdated packages

### ISSUE THREAD

**Issue by pmacko1** [openshift/origin#20454]
SSIA

**Comment by pmacko1** [comment]
users should be imo pointed to https://docs.docker.com/ for docker installation.
Also we had to follow steps in https://docs.docker.com/install/linux/linux-postinstall/ to make docker work for our application (docs.aerogear.org)

**Comment by pmacko1** [comment]
users should be imo pointed to https://docs.docker.com/ for docker installation.
Also I had to follow steps inhttps://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user to run oc cluster up on fedora 28

**Comment by jwforres** [comment]
@openshift/sig-master
