### ISSUE TITLE
Openshift doesn't recognize own CA with separate docker registry.

### ISSUE THREAD

**Issue by Gundersanne** [openshift/origin#20461]
##### Version
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce

1. The test suite configures/starts oc in the following way:
```
# Write the config, this will later be overwritten by oc cluster up but will set up the local node correctly for compatilibity with current tests
openshift start --write-config=/openshift.local.config --master='https://127.0.0.1:8443' --listen='https://0.0.0.0:8443'
oc cluster up --use-existing-config --host-config-dir=/openshift.local.config/ --host-data-dir=/openshift.local.etcd/ --host-volumes-dir=/openshift.local.volumes/
sed -i  "s/\(  allowedRegistriesForImport:\)/\1\n  - domainName: 'localhost:5555'/g" /openshift.local.config/master/master-config.yaml
```

2. In cockpit's test suite we have a docker registry using openshifts' master crt/key. It's started in the following way:
```
$ docker run -d -p 5555:5000 --name testreg -v /openshift.local.config/master/:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/master.server.crt -e REGISTRY_HTTP_TLS_KEY=/certs/master.server.key registry:2
```

(3.) When verifying it seems ok:
```
$ openssl s_client -connect localhost:5555  -verify_return_error -CAfile /openshift.local.config/master/ca.crt -verify 5
...
depth=1 CN = openshift-signer@1532810890
verify return:1
...
    Verify return code: 0 (ok)
...
```

4. Import tags via openshift API:

##### Current Result

The following results in unknown CA error:
```
{'apiVersion':'v1','kind':'ImageStream','metadata':{'name':'test-some-2','namespace':'marmalade'},'spec':{'tags':[{'name':'2.11','importPolicy':{},'from':{'kind':'DockerImage','name':'localhost:5555/juggs:2.11'}}]}}
```

The following works, but you have to pass insecure as `importPolicy`.
```
{'apiVersion':'v1','kind':'ImageStream','metadata':{'name':'test-some-3','namespace':'marmalade'},'spec':{'tags':[{'name':'2.11','importPolicy': {'insecure':true},'from':'kind':'DockerImage','name':'localhost:5555/juggs:2.11'}}]}}
```

##### Expected Result

Openshift would recognize it's own CA and allow to securely import tags from the docker registry.

##### Additional Information

Took place in the marmalade namespace:
[marmalade.namespace.txt](https://github.com/openshift/origin/files/2240547/marmalade.namespace.txt)

**Comment by adambkaplan** [comment]
@openshift/sig-developer-experience fyi

**Comment by bparees** [comment]
@openshift/sig-master @openshift/sig-security the CA in question should be accessible to the api server (that's where the imageimport is happening, so that's where it needs to be).  I would expect that's already the case, so it's not obvious to me what has gone wrong here, but if it's not the case, it does seem like it should be so that the api server(+ controllers) can trust services using service serving certs.

In 3.9 this would mean putting the CA on the master host.

in 3.10+ it means the CA needs to be in the pod running the api server.
