### ISSUE TITLE
Openshift oauth, combining two different level scopes

### ISSUE THREAD

**Issue by jasjeetkaur2211** [openshift/origin#20465]
I have developed an angular application that is deployed over openshift. For authentication, I am using oauth api from openshift and users that have access to openshift will get access here too.

oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.165:8443
openshift v3.9.0+d0f9aed-12
kubernetes v1.9.1+a0ce1bc657

Currently, I am by default giving all the users, the `scope:role:edit:<namespace>`. So all the users are able to access other services deployed in Openshift and do all the CRUD operations over these services. Now I wanted to restrict access to the users dynamically as per their access rights as specified in openshift rolebindings. 
 
For that purpose, I have done the following:
1. Create a custom cluster role providing read access t the clusterrole/role bindings and add that role to the user.
 ```
oc create clusterrole roleget --verb=<verb_list> --resource=<resource_list>
oc adm policy add-role-to-user roleget developer
```
2. This user already has view/edit rights.
```
oc adm policy add-role-to-user edit developer
```
Now when I change the scope in my application to `scope:role:roleget:<namespace>`, I get read access to the rolebindings in the namespace. I checked this with the following curl command:
```
curl -k -H "Authorization: Bearer $TOKEN" -H 'Accept: application/json' https://$ENDPOINT/apis/rbac.authorization.k8s.io/v1beta1/namespaces/$NAMESPACE/rolebindings
```
But now, I am not able to access other services in the openshift, i.e. for example, following fails:
```
 curl -k -H "Authorization: Bearer $TOKEN" -H 'Accept: application/json' https://$ENDPOINT/api/v1/namespaces/$NAMESPACE/pods
```

I want to have a combination of the aforementioned two scope i.e. `scope:role:edit:<namespace>` and `scope:role:roleget:<namespace>`

Does anybody has any idea how to do this?

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by enj** [comment]
I am not fully clear on what kind of app you are building.  I think you have an angular front end to allow users who already have access to a namespace to manipulate things in that namespace.  And I believe you are using the scopes to limit the amount of actions the angular app can do on behalf of the user.  This feels similar to the standard web console that comes with OpenShift.

To answer your question, the way you combine scopes (logical OR) in OAuth is via a space delimited string (`foo bar` means both scope `foo` and `bar`).  So `scope:role:edit:<namespace> scope:role:roleget:<namespace>` is what your app should pass as the scope parameter.

As an aside, https://github.com/openshift/oauth-proxy may be of interest to you.

**Comment by jasjeetkaur2211** [comment]
@enj thanks for your response. I will try this out.

**Comment by enj** [comment]
Feel free to reopen if you encounter further issues.
