### ISSUE TITLE
Kubernetes TestRoundTrip  test timed out after 2m0s

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#20460]
Logs: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20404/pull-ci-origin-unit/2003/

/cc @sttts 
/cc @deads2k

**Comment by mfojtik** [comment]
Flagging as P1 as this is a unit test failure which is always more concerning.

**Comment by sjenning** [comment]
Just saw this again
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/23182/pull-ci-openshift-origin-release-3.11-unit/311
