### ISSUE TITLE
`oc cluster up` should not prune images

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#20479]
When running `oc cluster up` locally on my laptop, it often prunes all of the images in my local dockerd. This is pretty annoying because I have to rebuild all of them afterwards.

##### Version
```
$ oc version
oc v3.9.0
kubernetes v1.9.1+cbc5b49
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```

##### Expected Result
There is an option in `oc cluster up` which can configure pruning.

**Comment by mfojtik** [comment]
I would suggest to run cluster up in VM. The cluster up will run kubelet that will connect directly to the local machine VM and will try to garbage collect images in order to free space.

**Comment by mfojtik** [comment]
Also I think this behavior can be configured in kubelet (or node config)

/cc @sjenning

**Comment by sjenning** [comment]
There are ways to tune the image GC in the kubelet but, in the end, the kubelet assumes sovereignty over the runtime and is at liberty to do image GC whenever it determines it is needed.  I agree with @mfojtik that you might want to run `oc cluster up` in a VM if you care about keeping images locally.

**Comment by TomasTomecek** [comment]
Is there an easy one liner to edit the kubelet configuration? I tried `oc edit node localhost` but no such config was displayed.

**Comment by sjenning** [comment]
There once was `--write-config` flag that would write the config files to the host, you could change them, then use `--host-config-dir` and `--use-existing-config=true` to use those configs.  Not sure if that path still works.

**Comment by mfojtik** [comment]
`--write-config` is still supported

**Comment by TomasTomecek** [comment]
Looks good, thank you, gentlemen!
