### ISSUE TITLE
why Openshift 3.6 put the skydns binded 127.0.0.1 on each node?  what's benefit for ? 

### ISSUE THREAD

**Issue by wenma** [openshift/origin#20494]
Why Openshift 3.6 put the skydns binded 127.0.0.1 on each node?  what's benefit for ? 
Prior to 3.6,  skydns just put on master node,  what is the reason for this change?

**Comment by jwforres** [comment]
@openshift/sig-network-edge

**Comment by Miciah** [comment]
@wenma, the reason for deploying SkyDNS in this way is to enable DNS to continue to function during master or API outages.
