### ISSUE TITLE
Can not get real client ip when using external ip (ingress ip)

### ISSUE THREAD

**Issue by masayoshi-louis** [openshift/origin#20493]
When exposing service using external ip (172.29.0.0/16), the pod can not obtain real client ip. It seems that the openshift routing infrastructure performs source NAT.

I have the external ip and routing setup properly (follow [the reference](https://docs.openshift.com/container-platform/3.3/admin_guide/tcp_ingress_external_ports.html#unique-external-ips-ingress-traffic-configure-service)), and expose some services (including nginx ingress controller). My service must be able to get the client's ip, but currently it can only get the router node's tun0 ip (10.128.0.1).

##### Version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server ........hidden..........
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Setup nginx ingress controller
2. Create an associated LoadBalancer typed service
3. Access the nginx service from a client PC: curl 172.29.92.146

##### Current Result
Nginx prints client ip: 10.128.0.1

##### Expected Result
Real client ip, like 192.168.x.y

**Comment by jwforres** [comment]
@openshift/sig-network-edge
