### ISSUE TITLE
The origin-metrics with tag 3.9.0 do not exists in dockerhub

### ISSUE THREAD

**Issue by sistemat** [openshift/origin#20506]
all images related to metrics do not exist in version 3.9.0 in the docker hub, as in YAML we have __openshift_metrics_image_version: "{{openshift_image_tag}}"
if it is not informed a standard version that is 3.9.0 will be passed, resulting in an error when the container was created

**Comment by jwforres** [comment]
@stevekuznetsov any thoughts why the 3.9.0 tags are missing, the 3.9 tag is there

**Comment by richm** [comment]
I don't know - maybe @jsanda knows about the origin-metrics images
