### ISSUE TITLE
hack/env hack/build-rpms.sh fails

### ISSUE THREAD

**Issue by adambkaplan** [openshift/origin#20501]
When running `hack/build-rpms.sh` inside of `hack/env` (ex: `hack/env make build-images`), it fails with the following:

```
+ touch --reference=/tmp/openshift/build-rpms/rpm/SOURCES/origin-3.11.0.tar.gz /tmp/openshift/build-rpms/rpm/BUILDROOT/origin-3.11.0-0.alpha.0.680.ba3b3ef.x86_64/usr/sbin/origin-excluder
touch: failed to get attributes of '/tmp/openshift/build-rpms/rpm/SOURCES/origin-3.11.0.tar.gz': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.JgCw5D (%install)
```

@sosiouxme it appears your recent change to `origin.spec` is where this is being called from.

**Comment by jwforres** [comment]
No idea if this is still an issue, adam's out for a few more weeks. @sosiouxme sent your way in case you know anything / can close this as working
