### ISSUE TITLE
Jenkins image bootsrap takes very long

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#20512]
The Jenkins image takes a very long time to bootstrap since it now upgrades itself and all its plugins to newer versions. With the default resource settings, it takes up to 5 min to start. 

Adjusting cpu limit to 4 core and mem limit to 4 Gi helped to reduce the bootstrap time to 1.5 min. 

Are there any recommendations on how to reduce it for especially demos and workshops?

**Comment by adambkaplan** [comment]
If you're using the Jenkins templates provided by origin, you can set the "Disable memory intensive administrative monitors" to `true` - however this may lead to security warnings being displayed in the Jenkins dashboard.

**Comment by siamaksade** [comment]
Thanks
