### ISSUE TITLE
when is 3.10 release?   

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#20513]
Any ETA on 3.10 release dates?

**Comment by DanyC97** [comment]
just been released as you might have seen and we are working now on getting the rpms for CentOS. Once that is done we'll announce on dev mailer, hopefully people will be willing to help testing

**Comment by DanyC97** [comment]
please close this issue as Origin v3.10 has been released now and let's track the rpm for centOS in https://github.com/openshift/openshift-ansible/issues/8550 or https://github.com/openshift/openshift-ansible/issues/8399 (hopefully one of the issues will be closed).

**Comment by DanyC97** [comment]
@debianmaster are you planning to close this issue or should we do it ? thank you

**Comment by debianmaster** [comment]
thanks!
