### ISSUE TITLE
Consider enabling admission webhooks by default with oc cluster up

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#20530]
We should consider enabling admission webhooks by default with oc cluster up. This will significantly decrease friction when users evaluate extensions on oc cluster up.

**Comment by pmorie** [comment]
cc @deads2k @smarterclayton

**Comment by mfojtik** [comment]
I don't see the reason for don't doing it.

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by nstielau** [comment]
There are enabled by default in upstream k8s 1.11: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#which-plugins-are-enabled-by-default

For context, the new CI workflow for OKD doesn't allow master config changes at this point, so it doesn't allow testing mutating/validating webhooks, or any features that rely on them (knative, istio).  If we properly lock down the RBAC, this will also enable per-customer customizations.

**Comment by sttts** [comment]
There were good reasons we had webhooks off (compare https://github.com/openshift/origin/pull/20743). But that was fixed and they are not enabled: https://github.com/openshift/origin/pull/20744.
