### ISSUE TITLE
master service failed to start with  errors in the logs related to certificate expired.

### ISSUE THREAD

**Issue by ajalboush** [openshift/origin#20538]
[provide a description of the issue]

master service failed to start

i see errors in the logs related to certificate expired.

##### Version

[root@master byo]# oc version
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75

##### Steps To Reproduce
 systemctl start origin-master

##### Current Result
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75
[root@master byo]# systemctl status origin-master
● origin-master.service - Origin Master Service
   Loaded: loaded (/usr/lib/systemd/system/origin-master.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2018-08-04 04:42:43 GST; 56ms ago
     Docs: https://github.com/openshift/origin
  Process: 42285 ExecStart=/usr/bin/openshift start master --config=${CONFIG_FILE} $OPTIONS (code=exited, status=255)
 Main PID: 42285 (code=exited, status=255)

Aug 04 04:42:43 master.dhcpaas.com systemd[1]: Unit origin-master.service entered failed state.
Aug 04 04:42:43 master.dhcpaas.com systemd[1]: origin-master.service failed.

##### Expected Result
the master service should work fine
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]

ERROR: [DS3001 from diagnostic UnitStatus@openshift/origin/pkg/diagnostics/systemd/unit_status.go:46]
       The origin-master systemd unit is intended to start at boot but is not currently active.
       An administrator can start the origin-master unit with:

         # systemctl start origin-master

       To ensure it is not failing to run, check the status and logs with:

         # systemctl status origin-master
         # journalctl -ru origin-master

ERROR: [DS3001 from diagnostic UnitStatus@openshift/origin/pkg/diagnostics/systemd/unit_status.go:46]
       The origin-node systemd unit is intended to start at boot but is not currently active.
       An administrator can start the origin-node unit with:

         # systemctl start origin-node

       To ensure it is not failing to run, check the status and logs with:

         # systemctl status origin-node
         # journalctl -ru origin-node

################# some logs
Aug  4 04:36:27 master systemd: Starting Origin Master Service...
Aug  4 04:36:27 master systemd: origin-node.service holdoff time over, scheduling restart.
Aug  4 04:36:28 master origin-master: W0804 04:36:28.138077   38699 start_master.go:267] assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
Aug  4 04:36:28 master origin-master: W0804 04:36:28.138252   38699 start_master.go:267] assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console
Aug  4 04:36:29 master origin-master: I0804 04:36:29.210570   38699 plugins.go:71] No cloud provider specified.
Aug  4 04:36:29 master origin-master: I0804 04:36:29.375218   38699 start_master.go:380] Starting master on 0.0.0.0:8443 (v1.1.4)
Aug  4 04:36:29 master origin-master: I0804 04:36:29.375295   38699 start_master.go:381] Public master address is https://master.dhcpaas.com:8443
Aug  4 04:36:29 master origin-master: I0804 04:36:29.375339   38699 start_master.go:385] Using images from "openshift/origin-<component>:v1.1.4"
Aug  4 04:36:29 master origin-master: I0804 04:36:29.614781   38699 run_components.go:200] Using default project node label selector:
Aug  4 04:36:30 master origin-master: W0804 04:36:30.134941   38699 controller.go:297] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default  242d0a47-977a-11e8-91ea-005056bc2980 
4640 0 2018-08-04 04:05:48 +0400 GST <nil> <nil> map[] map[]} [{[{10.11.13.81 <nil>}] [] [{https 8443 TCP} {dns 53 UDP} {dns-tcp 53 TCP}]}]}
Aug  4 04:36:30 master origin-master: I0804 04:36:30.467541   38699 master.go:262] Started Kubernetes API at 0.0.0.0:8443/api/v1
Aug  4 04:36:30 master origin-master: I0804 04:36:30.467612   38699 master.go:262] Started Kubernetes API Extensions at 0.0.0.0:8443/apis/extensions/v1beta1
Aug  4 04:36:30 master origin-master: I0804 04:36:30.467624   38699 master.go:262] Started Origin API at 0.0.0.0:8443/oapi/v1
Aug  4 04:36:30 master origin-master: I0804 04:36:30.467633   38699 master.go:262] Started OAuth2 API at 0.0.0.0:8443/oauth
Aug  4 04:36:30 master origin-master: I0804 04:36:30.467643   38699 master.go:262] Started Login endpoint at 0.0.0.0:8443/login
Aug  4 04:36:30 master origin-master: I0804 04:36:30.467650   38699 master.go:262] Started Web Console 0.0.0.0:8443/console/
Aug  4 04:36:30 master origin-master: I0804 04:36:30.467658   38699 master.go:262] Started Swagger Schema API at 0.0.0.0:8443/swaggerapi/
Aug  4 04:36:30 master origin-master: I0804 04:36:30.807696   38699 ensure.go:184] Ignoring bootstrap policy file because cluster policy found
Aug  4 04:36:30 master origin-master: E0804 04:36:30.809655   38699 ensure.go:201] error waiting for policy cache to initialize: Post https://master.dhcpaas.com:8443/oapi/v1/subjectaccessreviews: 
x509: certificate has expired or is not yet valid
Aug  4 04:36:30 master origin-master: E0804 04:36:30.812220   38699 ensure.go:164] Unable to create default security context constraint privileged.  Got error: Post https://master.dhcpaas.com:8443/api/v1/securitycontextconstraints:
 x509: certificate has expired or is not yet valid
Aug  4 04:36:30 master origin-master: E0804 04:36:30.815462   38699 ensure.go:164] Unable to create default security context constraint nonroot.  Got error: Post https://master.dhcpaas.com:8443/api/v1/securitycontextconstraints: 
x509: certificate has expired or is not yet valid
Aug  4 04:36:30 master origin-master: E0804 04:36:30.817376   38699 ensure.go:164] Unable to create default security context constraint hostmount-anyuid.  Got error: 
Post https://master.dhcpaas.com:8443/api/v1/securitycontextconstraints: x509: certificate has expired or is not yet valid
Aug  4 04:36:30 master origin-master: E0804 04:36:30.821028   38699 ensure.go:164] Unable to create default security context constraint hostaccess.  Got error: Post https://master.dhcpaas.com:8443/api/v1/securitycontextconstraints:
 x509: certificate has expired or is not yet valid
Aug  4 04:36:30 master origin-master: E0804 04:36:30.828632   38699 ensure.go:164] Unable to create default security context constraint restricted.  Got error: Post https://master.dhcpaas.com:8443/api/v1/securitycontextconstraints: 
x509: certificate has expired or is not yet valid
Aug  4 04:36:30 master origin-master: E0804 04:36:30.837964   38699 ensure.go:164] Unable to create default security context constraint anyuid.  Got error: Post https://master.dhcpaas.com:8443/api/v1/securitycontextconstraints: 
x509: certificate has expired or is not yet valid
Aug  4 04:36:30 master origin-master: E0804 04:36:30.842581   38699 ensure.go:164] Unable to create default security context constraint hostnetwork.  Got error: Post https://master.dhcpaas.com:8443/api/v1/securitycontextconstraints: x509: certificate has expired or is not yet valid
Aug  4 04:36:30 master origin-master: E0804 04:36:30.856975   38699 ensure.go:105] Error adding service account roles to "default" namespace: Get https://master.dhcpaas.com:8443/api/v1/namespaces/default: x509: certificate has 
expired or is not yet valid
Aug  4 04:36:30 master origin-master: E0804 04:36:30.860037   38699 ensure.go:52] Error creating namespace openshift-infra: Post https://master.dhcpaas.com:8443/api/v1/namespaces: x509: certificate has expired or is not yet valid
Aug  4 04:36:30 master origin-master: W0804 04:36:30.864690   38699 run_components.go:179] Could not start DNS: listen tcp4 0.0.0.0:53: bind: address already in use
Aug  4 04:36:30 master systemd: Started Origin Master Service.
Aug  4 04:36:30 master origin-master: I0804 04:36:30.865392   38699 start_master.go:524] Controllers starting (*)
Aug  4 04:36:30 master systemd: Starting Origin Node...
Aug  4 04:36:31 master origin-master: F0804 04:36:31.177855   38699 run_components.go:421] Unable to initialize namespaces: unable to refresh the security allocation UID blocks:
 Get https://master.dhcpaas.com:8443/api/v1/namespaces: x509: certificate has expired or is not yet valid
Aug  4 04:36:31 master systemd: origin-master.service: main process exited, code=exited, status=255/n/a
Aug  4 04:36:31 master systemd: Unit origin-master.service entered failed state.
Aug  4 04:36:31 master systemd: origin-master.service failed.

**Comment by ajalboush** [comment]
also i issued below command and found most of certificate are expired:

[root@master openshift-cluster]# for i in /etc/origin/master/*.crt; do echo $i; openssl x509 -in $i -noout -enddate; done
/etc/origin/master/admin.crt
notAfter=Mar 29 16:18:19 2018 GMT
/etc/origin/master/ca-bundle.crt
notAfter=Mar 28 16:18:17 2021 GMT
/etc/origin/master/ca.crt
notAfter=Mar 28 16:18:17 2021 GMT
/etc/origin/master/etcd.server.crt
notAfter=Mar 29 16:18:19 2018 GMT
/etc/origin/master/master.etcd-ca.crt
notAfter=Aug  4 00:03:52 2019 GMT
/etc/origin/master/master.etcd-client.crt
notAfter=Aug  4 00:04:31 2019 GMT
/etc/origin/master/master.kubelet-client.crt
notAfter=Mar 29 16:18:18 2018 GMT
/etc/origin/master/master.proxy-client.crt
notAfter=Mar 29 16:18:17 2018 GMT
/etc/origin/master/master.server.crt
notAfter=Mar 29 16:18:18 2018 GMT
/etc/origin/master/openshift-master.crt
notAfter=Mar 29 16:18:18 2018 GMT
/etc/origin/master/openshift-registry.crt
notAfter=Mar 29 16:18:21 2018 GMT
/etc/origin/master/openshift-router.crt
notAfter=Mar 29 16:18:20 2018 GMT

**Comment by mfojtik** [comment]
@soltysh what is 'oc v1.1.4' ?

**Comment by soltysh** [comment]
Version 1.1.4 is super old, if you can reproduce this with a newer version feel free to reopen this issue.
