### ISSUE TITLE
Building OpenShift takes a lot

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#2053]
```
$ time make build
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift
++ Placing binaries

real	0m33.458s
user	0m57.875s
sys	0m11.161s
```

OS: Fedora 21
CPU: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
RAM: 12gb

cc: @ironcladlou

**Comment by ncdc** [comment]
Takes 14s real time for me, F21 VM.

**Comment by ncdc** [comment]
On a different F21 VM, this one in VirtualBox, it takes 28-33 seconds. My first VM is in Parallels.

**Comment by ironcladlou** [comment]
Don't forget to do a clean build...

```
$ time make clean build
rm -rf _output Godeps/_workspace/pkg
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift
++ Placing binaries

real    0m20.620s
user    0m47.424s
sys     0m10.517s
```

F21 bare metal, i7-3520M CPU @ 2.90GHz w/ 16GB RAM.

**Comment by ncdc** [comment]
My timings were with clean, yes

**Comment by ironcladlou** [comment]
I agree this is pretty slow, but I personally don't have time to dig in and look for optimizations at the moment.

**Comment by kargakis** [comment]
I had run clean separately.

```
$ time make clean build 
rm -rf _output Godeps/_workspace/pkg
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift
++ Placing binaries

real	0m33.606s
user	0m58.482s
sys	0m11.261s
```

**Comment by kargakis** [comment]
> I agree this is pretty slow, but I personally don't have time to dig in and look for optimizations at the moment.

I guess it's not a big problem, but it's good to have it at least as an open issue.

**Comment by smarterclayton** [comment]
We're compiling about 150M of source.  That's pretty good, how long does it take Java?  :)

**Comment by rhcarvalho** [comment]
VirtualBox VM is way slower...

```bash
$ time make build
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
++ Placing binaries

real    1m19.906s
user    0m23.318s
sys     0m55.057s
```

```bash
$ time make clean build
rm -rf _output Godeps/_workspace/pkg
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
++ Placing binaries

real    2m17.554s
user    2m2.764s
sys     1m30.302s
```

**Comment by smarterclayton** [comment]
It's because of shared disk.  Use the rsync plugin (much faster) or NFS
plugin (somewhat faster).

On Wed, Jul 22, 2015 at 10:21 AM, Rodolfo Carvalho <notifications@github.com
> wrote:

> VirtualBox VM is way slower...
>
> $ time make build
> hack/build-go.sh
> ++ Building go targets for linux/amd64: cmd/openshift cmd/oc
> ++ Placing binaries
>
> real    1m19.906s
> user    0m23.318s
> sys     0m55.057s
>
> $ time make clean build
> rm -rf _output Godeps/_workspace/pkg
> hack/build-go.sh
> ++ Building go targets for linux/amd64: cmd/openshift cmd/oc
> ++ Placing binaries
>
> real    2m17.554s
> user    2m2.764s
> sys     1m30.302s
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2053#issuecomment-123738896>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by rhcarvalho** [comment]
Thanks @smarterclayton!! Indeed that helps a lot:

Changed my `.vagrant-openshift.json` file to:
```
{
  ...
  "sync_folders_type": "rsync",
  ...
}
```

`vagrant up` took considerably longer rsync'ing ~2GB, but then:

```bash
$ time make build
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
++ Placing binaries

real	0m2.076s
user	0m1.164s
sys	0m0.694s
```

```bash
$ time make clean build
rm -rf _output Godeps/_workspace/pkg
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
++ Placing binaries

real	0m44.215s
user	1m4.080s
sys	0m17.559s
```

The only problem is getting both-way sync to work. Maybe moving away to a different provider might be a best long term solution.

**Comment by smarterclayton** [comment]
It's a shame that vboxsf isn't fast.

On Wed, Jul 22, 2015 at 11:36 AM, Rodolfo Carvalho <notifications@github.com
> wrote:

> Thanks @smarterclayton <https://github.com/smarterclayton>!! Indeed that
> helps a lot:
>
> Changed my .vagrant-openshift.json file to:
>
> {
>   ...
>   "sync_folders_type": "rsync",
>   ...
> }
>
> vagrant up took considerably longer rsync'ing ~2GB, but then:
>
> $ time make build
> hack/build-go.sh
> ++ Building go targets for linux/amd64: cmd/openshift cmd/oc
> ++ Placing binaries
>
> real    0m2.076s
> user    0m1.164s
> sys 0m0.694s
>
> $ time make clean build
> rm -rf _output Godeps/_workspace/pkg
> hack/build-go.sh
> ++ Building go targets for linux/amd64: cmd/openshift cmd/oc
> ++ Placing binaries
>
> real    0m44.215s
> user    1m4.080s
> sys 0m17.559s
>
> The only problem is getting both-way sync to work. Maybe moving away to a
> different provider might be a best long term solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2053#issuecomment-123760707>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by soltysh** [comment]
Yeah, for that reason I switched to using libvirt instead.

**Comment by rhcarvalho** [comment]
Looking at these old numbers reminds me of how fast "slow" was. Nowadays it takes me ~200s with go 1.6.2
