### ISSUE TITLE
Failing to deploy with oc cluster up and --public-hostname flag from 3.10

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#20544]
##### Version
oc v3.10.0+dd10d17

##### Steps To Reproduce
$ oc cluster up --public-hostname remote_hostname 

##### Current Result

```
+ oc cluster up --public-hostname=openshift.chmouel.com --routing-suffix=openshift.chmouel.com
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0806 07:41:11.250258   11500 config.go:42] Running "create-master-config"
I0806 07:41:31.627782   11500 config.go:46] Running "create-node-config"
I0806 07:41:43.564934   11500 flags.go:30] Running "create-kubelet-flags"
I0806 07:41:59.618588   11500 run_kubelet.go:48] Running "start-kubelet"
I0806 07:42:09.478322   11500 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
[.. wait forever ..]
```

##### Expected Result

```
+ oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0806 07:51:03.639150   15459 flags.go:30] Running "create-kubelet-flags"
I0806 07:51:08.905069   15459 run_kubelet.go:48] Running "start-kubelet"
I0806 07:51:11.649326   15459 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
I0806 07:51:46.652985   15459 interface.go:26] Installing "kube-proxy" ...
I0806 07:51:46.653364   15459 interface.go:26] Installing "kube-dns" ...
[... Go on and installing .. ]
```

##### Additional Information

Trying to deploy with `oc cluster up` to a remote hostname keeps failing for me, looking over the origin docker container i see those errors : 

```
E0806 07:49:14.948741   12558 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:461: Failed to list *v1.Node: Get https://localhost:8443/api/v1/nodes?fieldSelector=metadata.name%3Dlocalhost&limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: getsockopt: connection refused
E0806 07:49:15.076491   12558 event.go:209] Unable to write event: 'Patch https://localhost:8443/api/v1/namespaces/default/events/localhost.15483bbb5ce3cb2a: dial tcp 127.0.0.1:8443: getsockopt: connection refused' (may retry after sleeping)
I0806 07:49:15.104982   12558 kuberuntime_manager.go:513] Container {Name:api Image:openshift/origin-hypershift:v3.10 Command:[/bin/bash -c] Args:[#!/bin/bash
set -euo pipefail
if [[ -f /etc/origin/master/master.env ]]; then
  set -o allexport
  source /etc/origin/master/master.env
fi
exec hypershift openshift-kube-apiserver --config=/etc/origin/master/master-config.yaml
] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:master-config ReadOnly:false MountPath:/etc/origin/master/ SubPath: MountPropagation:<nil>} {Name:master-cloud-provider ReadOnly:false MountPath:/etc/origin/cloudprovider/ SubPath: MountPropagation:<nil>} {Name:master-data ReadOnly:false MountPath:/var/lib/origin/ SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:healthz,Port:8443,Host:,Scheme:HTTPS,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Always SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
I0806 07:49:15.105103   12558 kuberuntime_manager.go:757] checking backoff for container "api" in pod "master-api-localhost_kube-system(c447e6a5a1f3a6bd9b13a247b700d66d)"
I0806 07:49:15.105251   12558 kuberuntime_manager.go:767] Back-off 2m40s restarting failed container=api pod=master-api-localhost_kube-system(c447e6a5a1f3a6bd9b13a247b700d66d)
E0806 07:49:15.105314   12558 pod_workers.go:186] Error syncing pod c447e6a5a1f3a6bd9b13a247b700d66d ("master-api-localhost_kube-system(c447e6a5a1f3a6bd9b13a247b700d66d)"), skipping: failed to "StartContainer" for "api" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=api pod=master-api-localhost_kube-system(c447e6a5a1f3a6bd9b13a247b700d66d)"
```

It was working on openshift 3.9 and when I remove  the --public-hostname=$DOMAIN options

It's maybe a configuration issue with my VM but I am not sure what needs to be changed/opened (and it was working until 3.10

**Comment by mfojtik** [comment]
you can try --write-config and then change the hostname inside master config directly. I believe this was fixed in 3.11 but not backported to 3.10

**Comment by andersonlfeitosa** [comment]
I have the same problem:

user@machine ~ $ oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0809 16:55:37.900544   59134 config.go:42] Running "create-master-config"
I0809 16:55:42.188590   59134 config.go:46] Running "create-node-config"
I0809 16:55:42.834248   59134 flags.go:30] Running "create-kubelet-flags"
I0809 16:55:43.264582   59134 run_kubelet.go:48] Running "start-kubelet"
I0809 16:55:43.375980   59134 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
E0809 17:00:43.372943   59134 run_self_hosted.go:542] API server error: Get https://192.168.99.100:8443/healthz?timeout=32s: dial tcp 192.168.99.100:8443: connect: connection refused ()
Error: timed out waiting for the condition

Any help?

**Comment by literalice** [comment]
I have the same problem on master branch(v3.11.0).
I use macOS with Docker Machine.
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#mac-os-x-with-docker-machine

```
$ oc cluster up --tag="48a1596"
Getting a Docker client ...
Checking if image openshift/origin-control-plane:48a1596 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:48a1596 is available ...
Starting OpenShift using openshift/origin-control-plane:48a1596 ...
I0810 15:25:53.915941   99918 flags.go:30] Running "create-kubelet-flags"
I0810 15:25:54.975695   99918 run_kubelet.go:48] Running "start-kubelet"
I0810 15:25:55.253054   99918 run_self_hosted.go:179] Waiting for the kube-apiserver to be ready ...
E0810 15:30:55.258534   99918 run_self_hosted.go:550] API server error: Get https://192.168.99.101:8443/healthz?timeout=32s: dial tcp 192.168.99.101:8443: connect: connection refused ()
Error: timed out waiting for the condition
```

**Comment by chmouel** [comment]
Not sure if it's related but i have another error here with regard to the router : 

```error: router could not be created; service account "router" is not allowed to access the host network on nodes, grant access with oc adm policy add-scc-to-user hostnetwork -z router```

**Comment by chmouel** [comment]
I believe I figured what's going on, I need to make sure to remove all installations files from 3.9 (or even between runs)

If I make sure before installing to remove all the configurations and the ~/.kube  from previous setups it will install fine,

I don't think 3.9 needed that.

(here is my script that cleanup/reinstall if someone want to look  at it https://gist.github.com/chmouel/da2595de9a19025af27d823506aaffa3)

I am keeping this issue open in case it's a different issue for other people.

**Comment by rguderlei** [comment]
Thanks for the hint to remove all configurations. It worked for me!

**Comment by simonpasquier** [comment]
+1 for the script @chmouel. I had one that looked similar but it was missing the removal of the base directory!

**Comment by laugimethods** [comment]
Like @chmouel , I'm not able to successfully rerun `oc cluster up` on Mac OS v10.13.6, Docker 18.06.1-ce-mac73 (26764), Openshift 3.11, but after a full reset of Docker and `brew uninstall --force openshift-cli`.

Even after erasing `/var/lib/origin/cluster-up` and `~/.kube` (and a Docker restart to avoid `error: a port needed by OpenShift is not available`), I cannot rerun OpenShift...

```
> docker run -it --rm --privileged --pid=host justincormack/nsenter1 /bin/sh -c 'rm -rf /var/lib/origin/cluster-up-OLD'
> docker run -it --rm --privileged --pid=host justincormack/nsenter1 /bin/sh -c 'mv /var/lib/origin/cluster-up /var/lib/origin/cluster-up-OLD'
> rm -rf ~/.kube

> oc cluster up
...
I1106 09:42:19.174026   49779 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
```

I've been even more hardcore with a `docker run -it --rm --privileged --pid=host justincormack/nsenter1 /bin/sh -c 'rm -rf /var/lib/kubelet/device-plugins'`, but then the cluster is definitely broken (`Error: error creating node config: could not create OpenShift configuration: cannot start container`).

Any help from someone using `oc cluster up` in MacOS?
Btw, 3.10 `cluster down/up` was fine.
