### ISSUE TITLE
Example on how to use a volume in a openshift container?

### ISSUE THREAD

**Issue by DennisD2** [openshift/origin#20572]
I have not yet find out how to use a volume in OpenShift. After creating the volume with RWO
the volume is attached to the running container. It can be seen with 'df'.
Problem is that the permissions of the mount point are r-xr-xr-x and the mount point is owned by root:root. 
My container is running as non-root, this looks to be the fixed default in OpenShift. 

So I cannot put any data on that volume. 

Can anyone reading this give a hint or example how to solve this issue?

##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://deleted.by.me:8443
openshift v3.7.23
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. Create a volume with RWO and mount point
2. Try to create file or directory on volume -> fails due to missing permissons

##### Current Result

I can create and attach, but not use a volume by a container/pod.

##### Expected Result

Being able to use a volume by a container/pod to store data.

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by gnufied** [comment]
Make sure that your pod is running with restricted SCC. If your pod is not running with restricted SCC then make sure that your pod specifies a fsGroup.

https://docs.openshift.com/container-platform/3.10/install_config/persistent_storage/pod_security_context.html for more information.

Support questions like these can be sent to openshift's user mailing list. Using github issues for help is kinda discouraged.
