### ISSUE TITLE
openshift/origin-pod not tagged with v0.5

### ISSUE THREAD

**Issue by anderssv** [openshift/origin#2058]
Trying to run OpenShift locally with all-in-one and when I issue '''osc start-build ...''' the server gives:

    E0505 13:44:04.348236   14833 kubelet.go:1313] Failed to create pod infra container: Tag v0.5 not found in repository openshift/origin-pod; Skipping pod "myapp-build-1_default"

Am I missing something here, or is this a glitch? Workaround?

**Comment by ncdc** [comment]
Until we have the v0.5 images tagged and uploaded, you can start OpenShift with `--images='openshift/origin-${component}:v0.4.4'

**Comment by mfojtik** [comment]
@mnagy fyi

**Comment by smarterclayton** [comment]
Fixed now, I forgot to run the last part of the release process.
