### ISSUE TITLE
Router becomes unable to modify the routing table

### ISSUE THREAD

**Issue by miminar** [openshift/origin#20586]
On `openshift v3.9.33` cluster, there was a router pod that spewed errors like this into its log:

    E0808 16:10:22.640804       1 limiter.go:137] failed to write route table: open /var/lib/haproxy/router/routes.json: permission denied
    E0808 16:10:27.641073       1 limiter.go:137] failed to write route table: open /var/lib/haproxy/router/routes.json: permission denied

With a high frequency. This caused all the new routes to not work at all (the infra routes used to work just fine since they were old enough), returning 503 and a message like:

```
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Possible reasons you are seeing this page:

The host doesn't exist. Make sure the hostname was typed correctly and that a route matching this hostname exists.
The host exists, but doesn't have a matching path. Check if the URL path was typed correctly and that the route was created using the desired path.
Route and path matches, but all pods are down. Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
```

Deleting the router pod and waiting until the new one gets deployed resolved the issue. Figuring this out took an awful lof of time though.

This bug report suggests to:

  - making the router pod not healthy when it finds out it cannot update routes
  - record some kind of error in the route's status that would suggest that the route does not work

Unfortunately, the current router pod does not behave wrong anymore, therefor I cannot provide any meaningful data on what actually caused the above errors.

**Comment by jwforres** [comment]
@openshift/sig-network-edge

**Comment by akram** [comment]
@miminar we are also facing this issue.
Were you using router shards ?

**Comment by miminar** [comment]
> Were you using router shards ?

@akram no I wasn't. I used either
* plain old `oc adm router router --service-account=router`
* or the defaults during the [advanced installation](https://docs.openshift.com/container-platform/3.9/install_config/install/advanced_install.html)

**Comment by akram** [comment]
@miminar we found out that this issue was caused by a cron script in our environment running *aide*


aide.conf is the configuration file for Advanced Intrusion Detection Environment. aide.conf contains the runtime configuration aide uses to initiailize or check the aide database.

It was doing chown root:root on all files in /var/lib/docker/** .
Up to OCP 3.6 the openshift router is not run anymore as privileged and thus it was failing to modify routes.json 


HTH
