### ISSUE TITLE
oc cluster up still does not recognize --insecure-registry argument in 3.10

### ISSUE THREAD

**Issue by dove-young** [openshift/origin#20581]
Although https://github.com/openshift/origin/issues/8997 is closed, but I had  `oc cluster up` failed at error msg `did not detect an --insecure-registry argument on the Docker daemon`, even though there is `--insecure-registry xxxxxxxx:5000` parameter on `dockerd` engine. 

And the workaroud in 8997 does not work for me. 

##### Version

```
[root@openshift-1 OpenShift_BaseDir]# oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
[root@openshift-1 OpenShift_BaseDir]#
[root@openshift-1 OpenShift_BaseDir]# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
[root@openshift-1 OpenShift_BaseDir]# docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:08:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:10:42 2018
  OS/Arch:          linux/amd64
  Experimental:     false
[root@openshift-1 OpenShift_BaseDir]#
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Current Result

```
I0809 02:57:17.728539   25629 helper.go:183] Inspecting docker container "origin"
I0809 02:57:17.729078   25629 helper.go:187] Container "origin" was not found
Checking for supported Docker version (=>1.22) ...
I0809 02:57:17.729098   25629 helper.go:99] Retrieving Docker version
I0809 02:57:17.729613   25629 helper.go:105] Docker version results: &types.Version{Version:"18.06.0-ce", APIVersion:"1.38", MinAPIVersion:"1.12", GitCommit:"0ffa825", GoVersion:"go1.10.3", Os:"linux", Arch:"amd64", KernelVersion:"3.10.0-862.2.3.el7.x86_64", Experimental:false, BuildTime:"2018-07-18T19:10:42.000000000+00:00"}
Checking if insecured registry is configured properly in Docker ...
I0809 02:57:17.729655   25629 registryconfig.go:30] Contains 1 --insecure-registry entries
F0809 02:57:17.729699   25629 helpers.go:119] error: did not detect an --insecure-registry argument on the Docker daemon
[root@openshift-1 ~]#
```

##### Expected Result

`oc cluster up` would recognize `insecure-registry` and in both parameter and `daemon.json`

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by pmacko1** [comment]
on fedora 28 only /etc/docker/daemon.json approach worked. i did not test the dockerd parameter approach

**Comment by enj** [comment]
@openshift/sig-master

**Comment by vroomvroomvroom** [comment]
Either I'm doing something wrong, or none of the three methods appear to work on 16.04.1-Ubuntu

oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

## more /etc/docker/daemon.json 
{
  "insecure-registry": "0.0.0.0:5555"
}

 oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
error: did not detect an --insecure-registry argument on the Docker daemon

same result as above if set DOCKER_OPTS='insecure-registry 127.0.0.1:5555'

using dockerd --insecure-registry 127.0.0.1:5555
.. 
## oc cluster up in another terminal shows:
ERRO[0006] Handler for GET /v1.27/containers/origin/json returned error: No such container: origin

**Comment by martinvelos** [comment]
> Yup, i was doing it wrong .. but not all methods work.
> this does NOT work:
> more /etc/docker/daemon.json
> {
> "insecure-registry": "172.30.0.0/16"
> }

You need to have the IP(s) in array like this:
```
{
        "insecure-registries": [
                "172.30.0.0/16"
        ]
}
```
At least that worked for me.

**Comment by perevertysh** [comment]
Restarting machine, and shutdown of docker daemon and starting again helped. It need to execute
`sudo oc cluser down` 
too. 
Then up cluster again.
