### ISSUE TITLE
[doc] Compatible version of docker is not updated for oc 3.10

### ISSUE THREAD

**Issue by amitkrout** [openshift/origin#20598]
[provide a description of the issue]

##### Version
$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#prerequisites
2. [step 2]

##### Current Result
oc 3.10 compatible version of docker is not available in the list
##### Expected Result
A compatible docker version should added to the list
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by pmacko1** [comment]
@mfojtik ping. Sorry to bother you. We use `oc cluster up` as part of our community project aerogear.org. Will you be able to find a time in your schedule to take a look at these issues? If you can't, could you please refer me/assign it to someone you believe could help with these? Thanks a lot.:)
https://github.com/openshift/origin/issues/20057
https://github.com/openshift/origin/issues/20018
https://github.com/openshift/origin/issues/19477
https://github.com/openshift/origin/issues/19304

**Comment by pmacko1** [comment]
neither for 3.11
fyi @psturc @jhellar @finp
