### ISSUE TITLE
"oc delete all --all" does not clean all resources properly

### ISSUE THREAD

**Issue by amitkrout** [openshift/origin#20600]
[provide a description of the issue]
I think the issue header is self explanatory

##### Version
$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. Run ```oc cluster up``` on macOS as per the [doc](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#macos-with-docker-for-mac)
```
$ oc cluster up
```
2. apply eap71 image stream and template from https://github.com/openshift/openshift-ansible/tree/release-3.9/roles/openshift_examples/files/examples/v3.9/xpaas-streams and https://github.com/openshift/openshift-ansible/tree/release-3.9/roles/openshift_examples/files/examples/v3.9/xpaas-templates respectively.
```
oc apply -f xpaas-streams/eap71-image-stream.json -n openshift
oc apply -f xpaas-templates/eap71-tx-recovery-s2i.json -n openshift
```
3. Deploy the template 
```
oc new-app eap71-tx-recovery-s2i
```
4. Then delete all the resource through ```oc delete all --all```
```
$ oc delete all --all
pod "eap-app-1-build" deleted
pod "eap-app-1-bwdxs" deleted
pod "eap-app-migration-1-s2nqb" deleted
replicationcontroller "eap-app-1" deleted
replicationcontroller "eap-app-migration-1" deleted
service "eap-app" deleted
service "eap-app-ping" deleted
deploymentconfig.apps.openshift.io "eap-app" deleted
deploymentconfig.apps.openshift.io "eap-app-migration" deleted
buildconfig.build.openshift.io "eap-app" deleted
build.build.openshift.io "eap-app-1" deleted
imagestream.image.openshift.io "eap-app" deleted
route.route.openshift.io "eap-app" deleted
```
5. Check the status
```
$ oc status
In project My Project (myproject) on server https://192.168.64.6:8443

pod/eap-app-migration-1-s2nqb runs 172.30.1.1:5000/myproject/eap-app@sha256:5d0043302a69ce18d5fae8bf7bc8842de5fd48f3a3b1092bf39dfdab0362c6aa

You have no services, deployment configs, or build configs.
Run 'oc new-app' to create an application.
```

##### Current Result
Pod is still in running after delete

##### Expected Result
Should cleaned up

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by LalatenduMohanty** [comment]
cc @deads2k Is this a timing issue?

**Comment by deads2k** [comment]
Right.  In 3.10, `oc delete` does not wait for the thing to actually be deleted, it just issues the delete and finalizers (like GC) run.  In 3.11, it should wait.
