### ISSUE TITLE
certificate for the integrated registry is signed by unknown authority

### ISSUE THREAD

**Issue by dmage** [openshift/origin#20604]
#### [Conformance][templates] templateinstance readiness test  [It] should report ready soon after all annotated objects are ready [Suite:openshift/conformance/parallel]
```
Aug  9 15:02:37.071: INFO: At 2018-08-09 14:44:48 +0000 UTC - event for cakephp-mysql-example-1-hook-pre: {kubelet ci-op-7zbtnkjy-f7020-ig-n-189r} Failed: Failed to pull image "172.30.100.193:5000/e2e-test-templates-nsmz2/cakephp-mysql-example@sha256:3494b291ff81f736cd75d99e0e625ff79d0bb3fa62bf7f4ac31a71e3ae90a96b": rpc error: code = Unknown desc = Get https://172.30.100.193:5000/v2/: x509: certificate signed by unknown authority
Aug  9 15:02:37.071: INFO: At 2018-08-09 14:44:48 +0000 UTC - event for cakephp-mysql-example-1-hook-pre: {kubelet ci-op-7zbtnkjy-f7020-ig-n-189r} Failed: Error: ErrImagePull
Aug  9 15:02:37.071: INFO: At 2018-08-09 14:44:49 +0000 UTC - event for cakephp-mysql-example-1-hook-pre: {kubelet ci-op-7zbtnkjy-f7020-ig-n-189r} SandboxChanged: Pod sandbox changed, it will be killed and re-created.
Aug  9 15:02:37.071: INFO: At 2018-08-09 14:44:51 +0000 UTC - event for cakephp-mysql-example-1-hook-pre: {kubelet ci-op-7zbtnkjy-f7020-ig-n-189r} Failed: Error: ImagePullBackOff
Aug  9 15:02:37.071: INFO: At 2018-08-09 14:44:51 +0000 UTC - event for cakephp-mysql-example-1-hook-pre: {kubelet ci-op-7zbtnkjy-f7020-ig-n-189r} BackOff: Back-off pulling image "172.30.100.193:5000/e2e-test-templates-nsmz2/cakephp-mysql-example@sha256:3494b291ff81f736cd75d99e0e625ff79d0bb3fa62bf7f4ac31a71e3ae90a96b"
```

#### [Feature:Builds][Conformance] s2i build with a root user image  [It] should create a root build and pass with a privileged SCC [Suite:openshift/conformance/parallel]
```
Aug  9 14:46:30.810: INFO: Running 'oc logs --config=/tmp/admin.kubeconfig --namespace=e2e-test-s2i-build-root-2rpv6 pod/nodejspass-1-build -c sti-build -n e2e-test-s2i-build-root-2rpv6'
Aug  9 14:46:31.106: INFO: Log for pod "nodejspass-1-build"/"sti-build"
---->
pulling image error : Get https://172.30.100.193:5000/v2/: x509: certificate signed by unknown authority
error: build error: unable to get 172.30.100.193:5000/e2e-test-s2i-build-root-2rpv6/nodejsroot@sha256:14e02688141a069782da0d32697dc8344780d203c64489afc9f29676fde9672f
<----end of log for "nodejspass-1-build"/"sti-build"

... REDACTED ...

Pushing image docker-registry.default.svc:5000/e2e-test-s2i-build-root-2rpv6/nodejsroot:latest ...
Pushed 0/9 layers, 1% complete
Pushed 1/9 layers, 18% complete
Pushed 2/9 layers, 27% complete
Pushed 3/9 layers, 36% complete
Pushed 4/9 layers, 49% complete
Pushed 5/9 layers, 59% complete
Pushed 6/9 layers, 67% complete
Push successful
```

/kind test-flake

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_image-registry/118/pull-ci-image-registry-e2e/106/

Other instances of this flake: https://unsid.com/openshift/pull-ci-image-registry-e2e/106/?resource=similar&segment=6686289:168439

**Comment by bparees** [comment]
@deads2k you recently changed how the internal registry hostname lookup is done... we're now seeing flakes in which certain operations are using the registry service ip instead of the registry hostname. Possible your change has introduced some inconsistency/failures in that lookup path?

**Comment by bparees** [comment]
(the imagestream api contains a decorator that updates the imagestream w/ the internal registry hostname,which i think is the value that's ultimately showing up here and causing problems)

**Comment by bparees** [comment]
(referring to this PR: https://github.com/openshift/origin/pull/20546)

**Comment by sdodson** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/7581/pull-ci-openshift-openshift-ansible-e2e-gcp/1191/

**Comment by bparees** [comment]
@sdodson since ansible creates that certificate, i don't suppose you have any theories on why the service ip wouldn't be in the certificate?

(i looked at the registry role, it certainly seems like it attempts to include the service ip, so unless the service ip is changing after the fact for some reason, it should work)

**Comment by bparees** [comment]
@dmage is doing some debugging here: https://github.com/openshift/origin/pull/20607

**Comment by bparees** [comment]
from his PR:
```
[It] should report ready soon after all annotated objects are ready [Suite:openshift/conformance/parallel]
  /tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateinstance_readiness.go:127
STEP: CN=docker-registry.default.svc [docker-registry.default.svc docker-registry.default.svc.cluster.local] []
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20607/pull-ci-origin-e2e-gcp/2237/

so clearly the service IP is not getting set.

**Comment by bparees** [comment]
@sdodson @stevekuznetsov is there any output from the ansible install that would help us see why ansible might not have put the service ip into the secret it created?

**Comment by bparees** [comment]
it's worth noting that this behavior only seems to occur in the GCP job, so it seems like *something* is different in that environment.

**Comment by bparees** [comment]
(that cert is also missing all the other hostnames that ansible would have setup, which makes me think the registry certificate is not being created by ansible in these jobs)

**Comment by mffiedler** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1614025 reports the same issue

/cc: @schituku @vikaslaad

**Comment by sdodson** [comment]
testing a revert of https://github.com/openshift/openshift-ansible/pull/9181 however commits from the suspect PR are NOT in 3.11.0-0.11.0, the first build they're in is 3.11.0-0.12.0

**Comment by bparees** [comment]
it seems like https://github.com/openshift/openshift-ansible/pull/9533 should resolve this, however it would still be good to understand why the cert on GCP is missing the svc ip, hopefully now that we're going to have ansible logs for gcp we can look at that.

**Comment by bparees** [comment]
> testing a revert of openshift/openshift-ansible#9181 however commits from the suspect PR are NOT in 3.11.0-0.11.0, the first build they're in is 3.11.0-0.12.0

weird, the env var was definitely missing on the registry DC and adding it fixed things.  Of course again we're mixing envs here.. this issue is about the GCP env which has two problems:  missing registry env(probably) and missing ip in the cert.

mike's cluster also had two problems:  missing registry env(definitely), and missing CA.

**Comment by simo5** [comment]
Is there a good reason why the CA cert is not deployed as before ?
Is it to allow for later rotation of the CA cert ? Or something else ?

Simo.

**Comment by bparees** [comment]
I don't want to lose track of the service clusterip aspect of this... 

@smarterclayton can you think of any reason why the registry service's spec.clusterip would be empty on GCP, at least for some period of time (when ansible is looking at it?)

@sdodson @stevekuznetsov do we have ansible install logs on GCP now?

**Comment by sdodson** [comment]
> @sdodson @stevekuznetsov do we have ansible install logs on GCP now?

No, I'm still not sure where to find those.

**Comment by smarterclayton** [comment]
Docker is dynamic, cri-o should be if it wants to be compatible.

I don't know of anything that should be depending on the CA on the host.

**Comment by mrunalp** [comment]
A quick look at the code in containers/image makes me think that cri-o should be fine but will let @mtrmac confirm it.

**Comment by mtrmac** [comment]
From a quick look (*not testing*), it seems that _both_ Docker and CRI-O:

1. Read the files in `/etc/{docker,container}/certs.d/`_$hostname_ again on every pull.
2. Read the system CAs (`/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` and the like) again on every pull _if at least one `/etc/{docker,container}/certs.d/$host/*.crt` (trusted root CA) exists_
3. Read the system CAs only once per process runtime (on first use) if no `/etc/{docker,container}/certs.d/$host/*.crt` exists.  This list of CAs is not refreshed even if 2. happens for a different $host and the files are physically read for that host.

(I’m pretty sure the difference between 2. and 3. is an unexpected implementation artifact.)

One difference between Docker and CRI-O that may or may not matter: Docker can support multiple `*.crt` (trusted root CA)` in the `*/certs.d` directory; CRI-O seems to be buggy and only use the last one (in lexicographic order).

**Comment by mtrmac** [comment]
> CRI-O seems to be buggy and only use the last one (in lexicographic order).

https://github.com/containers/image/pull/489 FWIW.

**Comment by mtrmac** [comment]
(It’s not really clear to me what is the state of this issue, what is known/unknown about the problem, and the like. E.g. the very start of this issue somehow makes a jump from `certificate signed by unknown authority` to “service ip wouldn't be in the certificate”.

I’m happy enough to just answer specific questions if y’all know what is going on; if you want me to take a more active role than that, please either describe the full setup or suggest how I can reproduce all of this.)

**Comment by sdodson** [comment]
@mtrmac due to a regression in openshift-ansible /etc/docker/certs.d/docker-registry.default.svc:5000/ did not have a link to the cluster CA which is the root cause there and that's been resolved. Given how we're building that link I think we're fine with or without your fix to CRI-O.

Consensus seems to be that we should not be adding the cluster CA to the host's trust stores because that just masks other problems that may occur in the future as components move from running on the host to running inside pods.

AFAIK the only outstanding question at this point is confirming whether or not we were properly generating the certificate for the registry with the service IP or not. For that we're waiting to get logs from the GCP jobs.

**Comment by ashishxooa** [comment]
No action was taken on this?

**Comment by bparees** [comment]
@ashishxooa reading through the history it looks like some ansible changes were made that resolved the problem.  not aware of this still being an issue anywhere, and it works significantly differently in 4.x.

**Comment by stobias123** [comment]
@bparees  - just hit this issue in 4.5 :(

**Comment by bparees** [comment]
@stobias123 please file a bug at bugzilla.redhat.com with details on how you configured your cluster, what action you were taking when you hit the problem, and the error output.
