### ISSUE TITLE
Build default sort order seems incorrect

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#20613]
`oc get build` in 3.11 against api.ci in a namespace is returning builds sorted by creationTimestamp.  It should be returning builds sorted by name (all resources should be returned by the server in name order).

@bparees @juanvallejo @liggitt server side sort should be in the natural sort order of the store in order to correctly support paging.  Builds are not behaving that way.

**Comment by liggitt** [comment]
I don't see anything order specific in https://github.com/openshift/origin/tree/master/pkg/build/apiserver/registry/build

**Comment by bparees** [comment]
we definitely don't have special logic for them.  we've had lengthy discussions about the behavior:
https://github.com/openshift/origin/issues/8643#issuecomment-292741421

builds sorted by name (which it was doing last i saw) is actually bad imho for the reasons described in that issue.  Either sorting by timestamp, or explicitly sorting by build number (if we even have it in the build object, i don't recall if we do) would seem better.

And of course there's the issue @kargakis called out which is that if you have builds from different buildconfigs, it would be nice to group them too, but then you do get into pagination issues i imagine.

Sorting by timestamp wouldn't seem to create pagination problems as long as the pagination logic also sorted by creation timestamp.

But again, regardless, i don't think we have any special logic for ordering builds today.
