### ISSUE TITLE
Switch from runtime.EmbeddedObject to runtime.Object

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#2063]
`runtime.EmbeddedObject` is obsolete.  We should be using `runtime.Object` instead.  This type is used inside of our API objects.

**Comment by stevekuznetsov** [comment]
@deads2k since EmbeddedObject embeds Object and doesn't offer any new methods with it as the receiver, is this find/replace?

**Comment by deads2k** [comment]
> @deads2k since EmbeddedObject embeds Object and doesn't offer any new methods with it as the receiver, is this find/replace?

I'm not sure.  Feel free to try it.  We're using it for advanced authentication configs and for self-subject access reviews.

**Comment by kargakis** [comment]
I don't see us using EmbeddedObject anywhere in our codebase anymore.
