### ISSUE TITLE
Hide credentials

### ISSUE THREAD

**Issue by employe1** [openshift/origin#20634]
Hello, I have been using openshift shortly and written some yaml files. In the yaml files I have passed parameters of git username and password. Is there any way I could hide the password or token credentials there on the Ui. example the password is replaced by asterisk "*".

**Comment by ramato-procon** [comment]
You should store credentials in a secret. Here you will find an example: https://github.com/openshift/origin/blob/master/examples/db-templates/postgresql-persistent-template.json

**Comment by jwforres** [comment]
It sounds like you are processing a Template? And are hoping we would autodetect fields named "password". No, we don't support this with basic template instantiation and don't expect we will.

If you go through the service catalog / service broker route instead then the UI is using JSON schema generated forms, those have added support for fields designated as passwords, for those we automatically use an input type password and require you to re-type it in a confirmation input. But a service broker might be a lot of overhead depending on what you are trying to accomplish.
