### ISSUE TITLE
Endpoint hostname missing

### ISSUE THREAD

**Issue by ramato-procon** [openshift/origin#20632]
I would like to create a RabbitMQ cluster using the Kubernetes Autodiscovery plugin.
It uses the EndpointSubset --> Hostname to discover the other RabbitMQ nodes.

According to the Kubernetes documentation for each pod a hostname is assigned with the Pod's name:
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods

When creating a headless service a DNS record for the pod should be created:
**hostname.headless-service.namespace.svc.cluster.local**

The hostname should also be added to "Endpoints --> Subsets --> Addresses --> Hostname".

Both is not working. 
Only the DNS resolution with A record is working. It seems to be the same issue: the hostname is not set for the pod.

> Note: Because A records are not created for Pod names, hostname is required for the Pod’s A record to be created. A Pod with no hostname but with subdomain only will only create the A record for the headless service (default-subdomain.my-namespace.svc.cluster.local), pointing to the Pod’s IP address.

The OpenShift documentation I can only find information regarding the headless services:
https://docs.openshift.com/container-platform/3.7/architecture/core_concepts/pods_and_services.html#headless-service-creation

I'm using a DeploymentConfig. Or is this only working for StatefulSets? If so there is no hint in any documentation (neither Kubernetes nor OpenShift).

##### Version
3.7.46

##### Steps To Reproduce
1. Create a deployment config
2. Create a headless service for the deployment config

##### Current Result
`nslookup podname.service-name.namespace.svc.cluster.local `
fails
##### Expected Result
`nslookup podname.service-name.namespace.svc.cluster.local `
returns the pod IP address

**Comment by ramato-procon** [comment]
If I read the code correctly, the Endpoint hostname is set here:
https://github.com/kubernetes/kubernetes/blob/a945b5d9281ac5cba5e4a2976a0747592c0cff87/pkg/controller/endpoint/endpoints_controller.go#L447
If pod.Spec.Hostname is set and pod.Spec.Subdomain == service.Name
Both fields are set for a statefulset:
https://github.com/kubernetes/kubernetes/blob/249ecab74e418b087797a255929ac51bde6924db/pkg/controller/statefulset/stateful_set_utils.go#L184
I don't find it anywhere else and also not in in de deployment-controller.
Is there any reason this feature was added for StatefulSets only? 
In my opinion the documentations and apis should als state this field is only set for statefulsets.

**Comment by jwforres** [comment]
@openshift/sig-network-edge
