### ISSUE TITLE
Identity provider supports UMA protocol?

### ISSUE THREAD

**Issue by fisache** [openshift/origin#20648]
When uses identity provider for authentication in multi openshifts sharing a Idp,
I wanna control to access a cluster each user, role in Idp even group in Idp.
For this, needs [UMA](https://en.wikipedia.org/wiki/User-Managed_Access) protocol.

if think needing and have no plan, I wanna make that using [keycloak UMA](https://www.keycloak.org/docs/latest/authorization_services/index.html#_overview)

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by simo5** [comment]
This is a request for a feature we do not plan to implement directly in openshift.
