### ISSUE TITLE
freeipa support

### ISSUE THREAD

**Issue by pyguy** [openshift/origin#20650]
Is it possible to have OKD integrated with freeipa?

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by stlaz** [comment]
I believe you could just use https://docs.okd.io/3.10/install_config/configuring_authentication.html#LDAPPasswordIdentityProvider

**Comment by enj** [comment]
Feel free to reopen if the docs are not sufficient.

**Comment by simo5** [comment]
The best option is probably to use https://docs.okd.io/3.10/install_config/configuring_authentication.html#RequestHeaderIdentityProvider and mod_auth_gssapi in apache for Single Sign On authnetication via GSSAPI which is supported by oc login.
Ldap syncing may be used to import groups.

In general FreeIPA integration is a composition of krb or LDAP authentication and sycning.
