### ISSUE TITLE
Add parameters for common/built-in metadata

### ISSUE THREAD

**Issue by rcernich** [openshift/origin#2065]
It would be nice if there were parameters for built-in details, e.g.:

 * namespace
 * domain
 * ???

An example usecase might be looking up DNS SRV records, where kubernetes service name, namespace and domain are required.

**Comment by rcernich** [comment]
Should have specified that this is for template parameters.

**Comment by smarterclayton** [comment]
These are things we're trying to get added to Kube upstream.  @pmorie added the first bit (namespace) which is now possible to add to pod template env vars (fieldRef: fieldPath: metadata.name)

**Comment by smarterclayton** [comment]
Will come in the next rebase

**Comment by smarterclayton** [comment]
Was delivered to master a few weeks ago.

----- Original Message -----

**Comment by rcernich** [comment]
So how would I define a parameter in a template that represents:
 * the default domain configured for OpenShift
 * the namespace in which the template is being processed
For example, say I have a parameter APP_NAME and I'd like to configure the Host field on a Route to ${APP_NAME}.${DEFAULT_DOMAIN}.

**Comment by smarterclayton** [comment]
Infrastructure domain?  Not supported, but @pmorie can help.  What's the default domain being used for (to get the route?)

----- Original Message -----

**Comment by rcernich** [comment]
DEFAULT_DOMAIN would be the domain configured on OpenShift.  Another example might be that I want to configure the route to simply project-name.default-domain, where project-name is the name of the project in which the route is being instantiated and default-domain is the domain configured on OpenShift.  For example, out of the box default config might result in: default.cluster.local.

Likewise, I might want to templatize something such that I get something like: service-name.project.domain.  I'm specifying service-name in the template, so that I know, but I don't know and don't know of a way to inject the project/namespace name nor the domain configured for the cluster.

**Comment by rcernich** [comment]
Sorry if I didn't make this clear in my original comment.

**Comment by smarterclayton** [comment]
The search order at a minimum should prevent you needing to know the cluster DNS suffix.  Seems reasonable that cluster namespace would be available via downward API, although that might be solvable via other clever mechanisms

**Comment by rcernich** [comment]
Right, I understand that for accessing services, but I was suggesting using something like this as the host name for a route.  That said, I would most likely default to application.project.domain, but it's always nice to have options. ;)

**Comment by smarterclayton** [comment]
Routes are in the search order internally - but you're mentioning the cluster DNS route?  That'll be available eventually from DNS on the service (this service is exposed as this name externally) or from the downward API.

**Comment by rcernich** [comment]
So are you saying, if I specify host=foo and the default domain is cluster.local, and my project bar, the router will route to the route's service if the host specified is foo.bar.cluster.local?  If so, that's great to know.

**Comment by smarterclayton** [comment]
If your route is named "foo" in namespace "bar", it will be available at "foo.bar.router.default".  You may want to set ndots to 3.

Host is special - you'd have to have internal DNS do that (which we don't yet do, but it's possible).
