### ISSUE TITLE
Project Overview - Create button wraps oddly with medium screen width

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2066]
The Create button, normally on the right, wraps to a weird spot. This looks strange to my eyes. Maybe pull it all the way to the left.

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7475870/2458231e-f318-11e4-9684-a7aee4913b61.png)

**Comment by liggitt** [comment]
Wrapping of the label filter widget itself is weird as well

**Comment by spadgett** [comment]
The Filter button wraps first and then is pulled back up when the Create button wraps as you keep sizing the window smaller.

![filter-button-wrapping](https://cloud.githubusercontent.com/assets/1167259/7493024/5b64af7c-f3cb-11e4-8aae-a69edc9401fe.png)

Wrapping doesn't seem right with filters set either.

![weird-wrap](https://cloud.githubusercontent.com/assets/1167259/7493146/3346991e-f3cc-11e4-99ea-c1cb1b63de9d.png)
