### ISSUE TITLE
Rest API authentication

### ISSUE THREAD

**Issue by roberto-gomez** [openshift/origin#2067]
Hello.

I am trying to do a request to the REST API and I suppose I have a problem with the authentication.

$ curl -X GET -k "https://localhost:8443/osapi/v1beta1/images"
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "\"/osapi/v1beta1/images\" is forbidden because system:anonymous cannot list on images in ",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}

How can I do a correct request?

**Comment by ncdc** [comment]
Attempting to get a list of images will be forbidden for all users except the system registry in the future, but regardless, if you want to make an authenticated request, you can do:

    curl --cacert openshift.local.config/master/ca.crt --cert openshift.local.config/master/admin.crt --key openshift.local.config/master/admin.key https://localhost:8443/osapi/v1beta1/...
