### ISSUE TITLE
origin-metrics-schema-installer docker image missing in docker hub

### ISSUE THREAD

**Issue by cjohnston23** [openshift/origin#20676]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]

openshift v3.10.0+7eee6f8-2
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. [step 1]
Use openshift ansible to install 3.10, use the following vars to enable metrics (hawkular/heapster/cassandra)

openshift_metrics_install_metrics: true
openshift_metrics_hawkular_hostname: hawkular-metrics.ame1-g1.apa.comcast.net
metrics_image_tag: v3.10.0-rc.0
openshift_metrics_cassandra_image: "docker.io/openshift/origin-metrics-cassandra:{{ metrics_image_tag }}"
openshift_metrics_hawkular_agent_image: "docker.io/openshift/origin-metrics-hawkular-openshift-agent:{{ metrics_image_tag }}"
openshift_metrics_hawkular_metrics_image: "docker.io/openshift/origin-metrics-hawkular-metrics:{{ metrics_image_tag }}"
openshift_metrics_schema_installer_image: "docker.io/openshift/origin-metrics-schema-installer:{{ metrics_image_tag }}"
openshift_metrics_heapster_image: "docker.io/openshift/origin-metrics-heapster:{{ metrics_image_tag }}"

2. [step 2]

##### Current Result

oc get po
NAME                            READY     STATUS             RESTARTS   AGE
hawkular-cassandra-1-6pqm4      1/1       Running            0          1h
hawkular-metrics-ggmb2          0/1       Running            10         1h
hawkular-metrics-schema-5gm8l   0/1       ImagePullBackOff   0          3h
heapster-9dn8g                  0/1       Running            6          1h

# oc logs hawkular-metrics-schema-5gm8l
Error from server (BadRequest): container "hawkular-metrics-schema" in pod "hawkular-metrics-schema-5gm8l" is waiting to start: trying and failing to pull image

The hawkular-metrics-schema pod fails to come up because it is trying to deploy an image that doesn't exist in docker hub.  Because this fails, the cassandra db never gets a schema applied so hawkular or heapster also are never able to get to the ready state.  

image: docker.io/openshift/origin-metrics-schema-installer:v3.10.0-rc.0

##### Expected Result

That origin-metrics-schema-installer exists on docker hub and can be pulled.  

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by slaterx** [comment]
Reproducible on OKD 3.10.

**Comment by jwforres** [comment]
@openshift/sig-hawkular-metrics

**Comment by slaterx** [comment]
For anyone manually generating their own image, this is the job template used by openshift-ansible:

https://github.com/openshift/openshift-ansible/blob/release-3.10/roles/openshift_metrics/templates/hawkular_metrics_schema_job.j2

**Comment by Episodio1** [comment]
Yes, someone uploaded the image to https://hub.docker.com/r/alv91/origin-metrics-schema-installer/ 
And it is tagged as "v3.10", not "v3.10.0-rc.0" as official metrics images. So you should have in inventory file: https://github.com/openshift/origin-metrics/issues/429#issuecomment-418271287

**Comment by netoralves** [comment]
The image version of schema is different of others PODs, for v3.10 use latest version of schema:

ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/openshift-metrics/config.yml \
    -e openshift_metrics_install_metrics=True \
    -e openshift_metrics_hawkular_hostname=$METRICS_URI \
    -e openshift_metrics_cassandra_image=docker.io/openshift/origin-metrics-cassandra:v3.10.0-rc.0 \
    -e openshift_metrics_hawkular_metrics_image=docker.io/openshift/origin-metrics-hawkular-metrics:v3.10.0-rc.0 \
    -e openshift_metrics_schema_installer_image=docker.io/alv91/origin-metrics-schema-installer:latest \
    -e openshift_metrics_heapster_image=docker.io/openshift/origin-metrics-heapster:v3.10.0-rc.0

**Comment by jwforres** [comment]
3.10.0 images are missing for all the metrics images, also see https://github.com/openshift/origin/issues/20913

cc @smarterclayton

**Comment by jwforres** [comment]
[Schema installer tags](https://hub.docker.com/r/openshift/origin-metrics-schema-installer/tags/) are there for 3.11 

missing 3.10 tags completely for schema installer and the other metrics images we only have the rc.0 pushed

**Comment by jwforres** [comment]
cc @rubenvp8510

**Comment by alextremblay** [comment]
Is there a valid workaround for this or a known fix?

I'm using OKD 3.10 and there are currently no 3.10 tags for this image in docker hub
