### ISSUE TITLE
[3.9] gcp job borked on cluster provisioning - failed expects hostvars is a dict

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#20679]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19957/test_pull_request_origin_extended_conformance_gce_39/307/

```
TASK [openshift_master_certificates : Generate the loopback master client config] ***
Friday 17 August 2018  09:28:24 +0000 (0:00:00.107)       0:14:25.481 ********* 
ERROR! |failed expects hostvars is a dict
++ export status=FAILURE
++ status=FAILURE
+ set +o xtrace
########## FINISHED STAGE: FAILURE: PROVISION TEST CLUSTER [00h 14m 53s] ##########
```

/assign @stevekuznetsov 
/cc @openshift/sig-continuous-delivery

**Comment by tnozicka** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19957/test_pull_request_origin_extended_conformance_gce_39/308/

**Comment by sdodson** [comment]
@stevekuznetsov who can make sure that docker.io/openshift/origin-ansible:v3.9.0 is rebuilt with https://github.com/openshift/openshift-ansible/pull/9125

**Comment by sdodson** [comment]
Or, alternatively rebuild with Ansible 2.4 rather than 2.6. Either will work.

**Comment by tnozicka** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19957/test_pull_request_origin_extended_conformance_gce_39/316/

**Comment by smarterclayton** [comment]
The Ansible release-3.9 job push_openshift_ansible_39 or branch_openshift_ansible_extended_conformance_gce_39 jobs should push it if they pass.

**Comment by sdodson** [comment]
Clayton, or someone, build and pushed a new v3.9 tag. Going to verify that has resolved the issue.

**Comment by tnozicka** [comment]
seems like is has moved a bit further; now borked on checking out 3.10 ansible roles for 3.9 testing...
```
Wednesday 29 August 2018  14:42:54 +0000 (0:00:00.828)       0:16:34.668 ****** 
fatal: [prtest-20891fe-319-ig-m-qt0m -> localhost]: FAILED! => {"changed": true, "cmd": ["tar", "-C", "/usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/", "-cvf", "/tmp/openshift-ansible-4KW35TJ/openshift-examples.tar", "."], "delta": "0:00:00.626784", "end": "2018-08-29 14:42:55.072795", "msg": "non-zero return code", "rc": 2, "start": "2018-08-29 14:42:54.446011", "stderr": "tar: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now", "stderr_lines": ["tar: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.10/: Cannot open: No such file or directory", "tar: Error is not recoverable: exiting now"], "stdout": "", "stdout_lines": []}
```
https://openshift-gce-devel.appspot.com/build/origin-/pr-logs/pull/19957/test_pull_request_origin_extended_conformance_gce_39/319/
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce_39/319/console

**Comment by smarterclayton** [comment]
Verify the aos-cd-job is cloning the right repo.

**Comment by sdodson** [comment]
I'm looking into the new failure.

**Comment by tnozicka** [comment]
@sdodson any luck?

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19957/test_pull_request_origin_extended_conformance_gce_39/426/

**Comment by tnozicka** [comment]
still not fixed, and the 3.9 CI is borked

I am trying to merge a PR to 3.9 branch for 23 days :/
 (https://github.com/openshift/origin/pull/19957)

**Comment by sdodson** [comment]
@tnozicka I don't know when it will be fixed. I'd work w/ your team lead to decide if it's appropriate to merge without this test having passed. Older branches having working CI is a chronic problem.

**Comment by tnozicka** [comment]
I though we went down that road and finally decided that we won't merge by hand ;)

Yes, it's a chronic problem, one would say we could learn to version our resources after all that.

The branch is known to be borked for 21 days, I understand everyone is busy but that's a really week SLA. It's really just -1 release.

I am giving up, but I don't think this is ok.

/close
