### ISSUE TITLE
How to actually make sure a PodTemplate provided via a ConfigMap is used by default?

### ISSUE THREAD

**Issue by svenstaro** [openshift/origin#20689]
I hope this is the appropriate tracker for this question. The docs [here](https://docs.openshift.com/container-platform/3.10/using_images/other_images/jenkins.html#configuring-the-jenkins-kubernetes-plug-in) explain how to add a custom PodTemplate to OpenShift using the kubernetes-jenkins plugin as well as the OpenShift Sync plugin. Now, this actually works but I'm curious how I can make this new PodTemplate be the default for ALL slaves that do not explicitly overwrite this?

As it stands, the PodTemplate is appended to the back of the list of PodTemplate which now looks like this: maven, nodejs, mytemplate. However, I want everything to always use mytemplate unless otherwise specified. I didn't find a way to do this.

##### Version
3.10.0

##### Steps To Reproduce
1. Add a PodTemplate as specified [here](https://docs.openshift.com/container-platform/3.10/using_images/other_images/jenkins.html#configuring-the-jenkins-kubernetes-plug-in)
2. Look http://yourjenkins/configure

##### Current Result
Your new template is added to the list of PodTemplates.

##### Expected Result
I want some way to make this new PodTemplate the default.

**Comment by bparees** [comment]
not sure it's possible, if it is possible, I would expect it would be a Jenkins level thing where you'd need to tell jenkins "by default run all my jobs on slaves that have label `foo` (and then you'd put label `foo` on the slave pod template you wanted them to use), because this is really a question of "how do i make sure my jobs run on a particular jenkins slave by default"

**Comment by gabemontero** [comment]
@bparees is correct in that this notion is a Jenkins thing, and nothing we can directly control via our sync plugin integration.

Based on my research, there is no way to currently override the use of master as a default.  In fact, in doc like https://wiki.jenkins.io/display/JENKINS/Distributed+builds there are hints that this is a conscious decision, to protect against the serializable requirements that agent based slave execution requires.  The pattern is to consciously choose on a job/project basis to leverage agents.

Depending on how much you'd like such a feature, you should pursue opening an new req at https://issues.jenkins-ci.org/
