### ISSUE TITLE
ZSH Completion not working: command not found: __kubectl_debug

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#20706]
zsh completion fails after trying to complete (i.e: press <kbd>tab</kbd>) on a file after a `-f` argument.

##### Version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server https://192.168.64.37:8443
openshift v3.10.0+a5e4ac9-10
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. zsh -i
2. source <(oc completion zsh)
3. oc create -f <kbd>TAB</kbd>

##### Current Result

`__kubectl_filedir:20: command not found: __kubectl_debug`

##### Expected Result

Completion after -f on files

##### Additional information

```zsh 5.5.1 (x86_64-apple-darwin17.5.0)```

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by chmouel** [comment]
probably related
https://github.com/kubernetes/kubernetes/issues/61017#issuecomment-372656711

**Comment by sttts** [comment]
We have:

```
__oc_debug()
{
    if [[ -n ${BASH_COMP_DEBUG_FILE} ]]; then
        echo "$*" >> "${BASH_COMP_DEBUG_FILE}"
    fi
}
```

**Comment by bernardgut** [comment]
I have the same problem. 

Also `source <(oc completion zsh)` returns 127

oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.100.2.228:8443
openshift v3.10.0+8a70964-87
kubernetes v1.10.0+b81c8f8

zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

**Comment by soltysh** [comment]
Does running `oc completion zsh` works for you? I tried it and it runs fine.

**Comment by chmouel** [comment]
This is still hapenning fyi,

**Comment by agiertli** [comment]
What is the solution to this issue? It still persists.

**Comment by chmouel** [comment]
I still have the issue as of today : 

```
 % oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0+7599337-146", GitCommit:"7599337aee", GitTreeState:"clean", BuildDate:"2019-05-15T09:23:59Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+8cd4e29", GitCommit:"8cd4e29", GitTreeState:"clean", BuildDate:"2019-05-09T19:20:33Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

 % source <(oc completion zsh)
 % oc create -f [TAB] __kubectl_filedir:3: command not found: __kubectl_debug
__kubectl_filedir:20: command not found: __kubectl_debug       
```

**Comment by chmouel** [comment]
I guess it just need to :

```
% source <(kubectl completion zsh)
```

just before doing the source of  `oc completion zsh` to get it to work. That's a bit clunky tho,

oh well for whoever that needs it, that's the solution,

**Comment by rhopp** [comment]
Wow... For so long I have been iritated by this bug and the solution is THAT simple! Thanks @chmouel!!!

**Comment by agiertli** [comment]
@chmouel you are my hero!!! It's still shame that nobody from dev team actually look into this for so long, but anyway, thanks for this tip!!

**Comment by lxop** [comment]
Alternatively, add `kubectl` to the list of plugins in your `~/.zshrc`

**Comment by chmouel** [comment]
@lxop I believe you are speaking in the context where you run your configuration under a ready made configuration framework like oh-my-zsh, prezto or others which is not the case for everyone (or at least I don't)
