### ISSUE TITLE
HAProxy router isn't working after installing cluster

### ISSUE THREAD

**Issue by azimovMichael** [openshift/origin#20705]
After installing a 3.9 cluster, the router pods are not coming up.
In the log we see 
`E0808 16:10:22.640804       1 limiter.go:137] failed to write route table: open /var/lib/haproxy/router/routes.json: permission denied`

##### Version
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://OUR_SERVER:8443
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Installing the cluster from openshift 3.9 ansible playbook

##### Current Result
router service isn't working properly
##### Expected Result
router service working
##### Additional Information
My cluster is on a private offline network so i can't provide any more details

**Comment by azimovMichael** [comment]
Problem fixed.
It was the SELinux that was misbehaving

**Comment by xmorano2** [comment]
Hi!

Hitting the same problem on my platform...

> Problem fixed.
> It was the SELinux that was misbehaving

@azimovMichael , What resolution you applied to get the router working?

thanks in advance

**Comment by azimovMichael** [comment]
Well actually Idk what was the exact problem, but it was caused by a wrong installation process. 
We installed 3.11 with fresh VMs, with the full recommended architechture, and all is working.

**Comment by xmorano2** [comment]
Thx @azimovMichael  !!  :)
