### ISSUE TITLE
When I try to curl to my Service IP:PORT (tomcat-openshift)  it doesn't work

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#2071]
Hi All,
    When I try to curl to my Service IP:PORT (tomcat-openshift)  it doesn't work, but if I curl the the Pod's IP:PORT (tomcat-openshift) it works, any idea ?

[oseuser2@ose1 beta3]$ osc get pods
POD                       IP         CONTAINER(S)       IMAGE(S)                    HOST                        LABELS                                                                               STATUS    CREATED
hello-openshift           10.1.1.4   hello-openshift    openshift/hello-openshift   ose3.novalocal/10.78.29.4   name=hello-openshift                                                                 Running   5 hours
hello-openshift-1-ivcje   10.1.1.3   hello-openshift    openshift/hello-openshift   ose3.novalocal/10.78.29.4   deployment=hello-openshift-1,deploymentconfig=hello-openshift,name=hello-openshift   Running   4 days
tomcat-openshift          10.1.0.4   tomcat-openshift   tomcat:latest               ose2.novalocal/10.78.29.3   name=tomcat-openshift                                                                Running   About a minute

This curl works OK

[oseuser2@ose1 beta3]$ curl "http://10.1.0.4:8080"

But when I try to curl to the Service URL it doesn't work, for instance...

[oseuser2@ose1 beta3]$ osc get services

NAME                      LABELS    SELECTOR                IP              PORT(S)
hello-openshift-service   <none>    name=hello-openshift    172.30.17.227   27017/TCP
tomcat-openshift          <none>    name=tomcat-openshift   172.30.17.231   28017/TCP

[oseuser2@ose1 beta3]$ curl "http://172.30.17.231:28017"
curl: (56) Recv failure: Connection reset by peer

IPTables rules in the current host:

[root@ose1 ~]# iptables -t nat -nvL
........
........
Chain KUBE-PORTALS-CONTAINER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            172.30.17.70         /* default/router: */ tcp dpt:80 redir ports 45967
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            172.30.17.124        /* default/router8: */ tcp dpt:80 redir ports 58137
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            172.30.17.229        /* default/router9: */ tcp dpt:80 redir ports 60961
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            172.30.17.227        /* produban/hello-openshift-service: */ tcp dpt:27017 redir ports 48588
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            172.30.17.2          /* default/kubernetes: */ tcp dpt:443 redir ports 55542
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            172.30.17.1          /* default/kubernetes-ro: */ tcp dpt:80 redir ports 49253
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            172.30.17.231        /* produban/tomcat-openshift: */ tcp dpt:28017 redir ports 59497

Chain KUBE-PORTALS-HOST (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            172.30.17.70         /* default/router: */ tcp dpt:80 to:10.78.29.2:45967
    1    60 DNAT       tcp  --  *      *       0.0.0.0/0            172.30.17.124        /* default/router8: */ tcp dpt:80 to:10.78.29.2:58137
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            172.30.17.229        /* default/router9: */ tcp dpt:80 to:10.78.29.2:60961
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            172.30.17.227        /* produban/hello-openshift-service: */ tcp dpt:27017 to:10.78.29.2:48588
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            172.30.17.2          /* default/kubernetes: */ tcp dpt:443 to:10.78.29.2:55542
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            172.30.17.1          /* default/kubernetes-ro: */ tcp dpt:80 to:10.78.29.2:49253
    3   180 DNAT       tcp  --  *      *       0.0.0.0/0            172.30.17.231        /* produban/tomcat-openshift: */ tcp dpt:28017 to:10.78.29.2:59497

Node agent logs when I curl the Service.

[root@ose1 ~]# journalctl -f -u openshift-node | grep -i tomcat

May 05 11:46:59 ose1.novalocal openshift-node[8937]: I0505 11:46:59.164210    8937 roundrobin.go:127] NextEndpoint for service "produban/tomcat-openshift:", srcAddr=10.78.29.2:57125: endpoints: [10.1.0.4:28017]
May 05 11:46:59 ose1.novalocal openshift-node[8937]: I0505 11:46:59.164238    8937 proxier.go:77] Mapped service "produban/tomcat-openshift:" to endpoint 10.1.0.4:28017

**Comment by smarterclayton** [comment]
@sdodson @brenton is this familiar?

**Comment by roldancer** [comment]
Hi All, this is my Service JSON file

[oseuser2@ose1 beta3]$ more tomcat-service.json
{
  "id": "tomcat-openshift",
  "kind": "Service",
  "apiVersion": "v1beta1",
  "port": 29017,
  "selector": {
    "name": "tomcat-openshift"
  }
}

If I add   the line "containerPort": 8080, the Service works OK, I have read that the parameter containerPort is optional, container's port discovery is part of the Kubernet labeling magic, Am I wrong ?

Thanks.

**Comment by sdodson** [comment]
I've certainly had this happen to me before but I never got to the root of it. I think the IPTables rules look OK, the problem we were looking at before was k8s failing to create the nat table all together during startup. (https://github.com/GoogleCloudPlatform/kubernetes/issues/7370)

You're using openshift-sdn, correct? Can you dump the service, `osc describe service tomcat-openshift` to see if there are endpoints?

**Comment by roldancer** [comment]
Hi @sdodson , right now it is working, I just added the parameter  "containerPort": 8080 to Service object.


[root@ose1 ~]# osc describe service tomcat-openshift -n produban
Name:			tomcat-openshift
Labels:			<none>
Selector:		name=tomcat-openshift
IP:			172.30.17.12
Port:			<unnamed>	28017/TCP
Endpoints:		10.1.0.4:8080
Session Affinity:	None
No events.

**Comment by mrunalp** [comment]
@roldancer Did you ever see the issue again?
