### ISSUE TITLE
project-request template shows up in the "select a template" page

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2072]
Within a project, select "Create..."
Select "Browse all templates..."
The "project-request" template appears (but fails on creation)

**Comment by liggitt** [comment]
@deads2k any way we can avoid that template appearing?

**Comment by deads2k** [comment]
> any way we can avoid that template appearing?

"hidden" annotation?  Does the UI already have a concept of that?

**Comment by spadgett** [comment]
@deads2k We don't have a generic "hidden" annotation. We do hide things like deployment pods and build pods based using annotations, however.

https://github.com/spadgett/origin/blob/19075d1df4c264290b1fe4d0cd1aa64d20a75a57/assets/app/scripts/controllers/overview.js#L141

**Comment by deads2k** [comment]
> We don't have a generic "hidden" annotation.

Do you want one?  Using annotations to indicate the intent of a template doesn't seem unreasonable, though if we were going to do that, we'd want to describe what "project-request" is and use that instead of using "hidden"

/cc @smarterclayton

**Comment by smarterclayton** [comment]
The template should be in default by default, not Openshift.  But we probably need a system annotation specific to our use of templates to separate the intent of the template.

Not sure the UI should have to hide this particular template.

**Comment by smarterclayton** [comment]
Just move the template to the default namespace for 3.0

**Comment by liggitt** [comment]
is that the first thing we're creating in `default`?

**Comment by liggitt** [comment]
> Not sure the UI should have to hide this particular template.

Creating a project in your project is not likely to work well... ever...

**Comment by deads2k** [comment]
> is that the first thing we're creating in default?

The registry and router get created in there, though I would have said we should move those *out* as opposed to moving more things *in*.  I thought that `openshift` was the spot for things like this.  Annotations are easy, why not choose an annotation name if that's what we really want?

**Comment by smarterclayton** [comment]
Openshift is not the place for this.  Openshift is for public things all users should see.

**Comment by smarterclayton** [comment]
Because they should never see it in the first place.

**Comment by deads2k** [comment]
> Openshift is not the place for this.  Openshift is for public things all users should see.

`default` doesn't seem like a great place either, since it's a space used in kube to represent "I don't care about namespaces".

**Comment by smarterclayton** [comment]
It's not.  It's "the first namespace" which is historically the place where all the admin stuff can go.

We should default to looking up the template in `default`

----- Original Message -----

**Comment by liggitt** [comment]
https://github.com/openshift/origin/pull/2267 will no longer write the template to the openshift namespace, which will fix this issue
