### ISSUE TITLE
docker:dind is not working in privileged container 

### ISSUE THREAD

**Issue by tsum-test** [openshift/origin#20740]
I'm trying to run docker:dind (docker in docker) in privileged openshift container, but it doesn't work:

[root@osh user]# oc logs docker-3-zj2km
mount: permission denied (are you root?)
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
mount: permission denied (are you root?)

If I run debug, I see that I unable to mount securityfs:

[root@osh user]# oc debug docker-3-zj2km
Defaulting container name to docker.
Use 'oc describe pod/docker-3-zj2km-debug -n dev' to see all of the containers in this pod.

Debugging with pod/docker-3-zj2km-debug, original command: dockerd-entrypoint.sh
Waiting for pod to start ...
Pod IP: 10.128.0.162
If you don't see a command prompt, try pressing enter.
/ # mount -t securityfs none /sys/kernel/security
mount: permission denied (are you root?)
/ # mount -t securityfs none /mnt/
mount: permission denied (are you root?)

I run as anyuid privileged scc:

[root@osh user]# oc describe pod docker-3-zj2km
Name:           docker-3-zj2km
Namespace:      dev
Node:           osh.node.ru/198.19.15.3
Start Time:     Thu, 23 Aug 2018 11:38:23 +0300
Labels:         app=docker
                deployment=docker-3
                deploymentconfig=docker
Annotations:    openshift.io/deployment-config.latest-version=3
                openshift.io/deployment-config.name=docker
                openshift.io/deployment.name=docker-3
                openshift.io/generated-by=OpenShiftNewApp
                openshift.io/scc=anyuid
Status:         Running
IP:             10.128.0.156
Controlled By:  ReplicationController/docker-3
Containers:
  docker:
    Container ID:   docker://2183e84db1ccfc269cd79e702cda4e68e91304c89520191f46c3efac675c1019
    Image:          docker@sha256:07db91f1abaf9f21ffee337c5198fa15e7ced1d96d1c84a82fd4fbcf51f812ea
    Image ID:       docker-pullable://docker.io/docker@sha256:07db91f1abaf9f21ffee337c5198fa15e7ced1d96d1c84a82fd4fbcf51f812ea
    Port:           2375/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 23 Aug 2018 11:44:15 +0300
      Finished:     Thu, 23 Aug 2018 11:44:15 +0300
    Ready:          False
    Restart Count:  6
    Environment:    <none>
    Mounts:
      /var/lib/docker from docker-volume-1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2bgmk (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  docker-volume-1:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-2bgmk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2bgmk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  node-role.kubernetes.io/compute=true
Tolerations:     <none>
Events:
  Type     Reason     Age               From                    Message
  ----     ------     ----              ----                    -------
  Normal   Scheduled  8m                default-scheduler       Successfully assigned docker-3-zj2km to osh.node.ru
  Normal   Pulled     6m (x5 over 8m)   kubelet, osh.node.ru  Container image "docker@sha256:07db91f1abaf9f21ffee337c5198fa15e7ced1d96d1c84a82fd4fbcf51f812ea" already present on machine
  Normal   Created    6m (x5 over 8m)   kubelet, osh.node.ru  Created container
  Normal   Started    6m (x5 over 8m)   kubelet, osh.node.ru  Started container
  Warning  BackOff    3m (x25 over 8m)  kubelet, osh.node.ru  Back-off restarting failed container

[root@osh user]# oc get scc
NAME               PRIV      CAPS      SELINUX     RUNASUSER          FSGROUP     SUPGROUP    PRIORITY   READONLYROOTFS   VOLUMES
anyuid             true      []        MustRunAs   RunAsAny           RunAsAny    RunAsAny    10         false            [configMap downwardAPI emptyDir hostPath persistentVolumeClaim projected secret]
hostaccess         false     []        MustRunAs   MustRunAsRange     MustRunAs   RunAsAny    <none>     false            [configMap downwardAPI emptyDir hostPath persistentVolumeClaim projected secret]
hostmount-anyuid   false     []        MustRunAs   RunAsAny           RunAsAny    RunAsAny    <none>     false            [configMap downwardAPI emptyDir hostPath nfs persistentVolumeClaim projected secret]
hostnetwork        false     []        MustRunAs   MustRunAsRange     MustRunAs   MustRunAs   <none>     false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]
nonroot            false     []        MustRunAs   MustRunAsNonRoot   RunAsAny    RunAsAny    <none>     false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]
privileged         true      [*]       RunAsAny    RunAsAny           RunAsAny    RunAsAny    <none>     false            [*]
restricted         true      []        MustRunAs   RunAsAny           MustRunAs   RunAsAny    <none>     false            [configMap downwardAPI emptyDir hostPath persistentVolumeClaim projected secret]

[root@osh user]# oc get scc anyuid -o json
{
    "allowHostDirVolumePlugin": true,
    "allowHostIPC": true,
    "allowHostNetwork": true,
    "allowHostPID": true,
    "allowHostPorts": false,
    "allowPrivilegedContainer": true,
    "allowedCapabilities": null,
    "apiVersion": "security.openshift.io/v1",
    "defaultAddCapabilities": null,
    "fsGroup": {
        "type": "RunAsAny"
    },
    "groups": [
        "system:cluster-admins"
    ],
    "kind": "SecurityContextConstraints",
    "metadata": {
        "annotations": {
            "kubernetes.io/description": "anyuid provides all features of the restricted SCC but allows users to run with any UID and any GID."
        },
        "creationTimestamp": "2018-08-22T16:05:55Z",
        "name": "anyuid",
        "resourceVersion": "114353",
        "selfLink": "/apis/security.openshift.io/v1/securitycontextconstraints/anyuid",
        "uid": "4008f0ea-a625-11e8-b572-5c546d719c3d"
    },
    "priority": 10,
    "readOnlyRootFilesystem": false,
    "requiredDropCapabilities": [
        "MKNOD"
    ],
    "runAsUser": {
        "type": "RunAsAny"
    },
    "seLinuxContext": {
        "type": "MustRunAs"
    },
    "supplementalGroups": {
        "type": "RunAsAny"
    },
    "users": [
        "system:serviceaccount:default:default",
        "system:serviceaccount:dev:default"
    ],
    "volumes": [
        "configMap",
        "downwardAPI",
        "emptyDir",
        "hostPath",
        "persistentVolumeClaim",
        "projected",
        "secret"
    ]
}

But it works inside native docker on this host:

[root@osh user]# docker ps|grep dind
856ffb6d9056        docker:dind                                                                                                                             "dockerd-entrypoin..."   26 minutes ago      Up 26 minutes       2375/tcp            zen_swanson
[root@osh user]# docker exec -it 856ffb6d9056 sh
/ # mount -t securityfs none /mnt/
/ # mount|grep /mnt
none on /mnt type securityfs (rw,relatime)
/ # ps -ef|grep docker
    1 root      0:02 dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375
   25 root      0:11 docker-containerd --config /var/run/docker/containerd/containerd.toml
  304 root      0:00 grep docker

##### Version
[root@osh user]# oc version
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://somehost:8443
openshift v3.10.0+a5e4ac9-10
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. Configure anyuid scc for allowing privileged containers
2. oc new-app docker:dind

##### Current Result
[root@osh user]# oc logs docker-3-zj2km
mount: permission denied (are you root?)
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
mount: permission denied (are you root?)
##### Expected Result
docker should start inside the container like in native docker

**Comment by rhatdan** [comment]
Did you see any AVC messages?  Could it be SELinux?

**Comment by tsum-test** [comment]
I disabled SElinux at all.

root@osh openshift-ansible]# getenforce
Disabled

**Comment by jwforres** [comment]
@openshift/sig-containers

**Comment by mschaefers** [comment]
same behavior for me. Any ideas on how to drive this issue?

**Comment by rhatdan** [comment]
Are you sure this is running a --privileged container.  In OpenShift, I believe that their definition of privileged might not be the same.

YOu need to make sure that the container is running with all caps and seccomp disabled, as well as AppArmor/SELinux disabled.

**Comment by rhatdan** [comment]
Mount failing probably means you either do not have CAP_SYS_ADMIN or seccomp is blocking the mount syscall.

**Comment by mschaefers** [comment]
Thanks, @rhatdan, the are indeed missing capabilities. To run docker:dind in openshift, you have to run the container in the `privileged` SCC, as well as add at least two capablities:

```
spec:
  containers:
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - SYS_ADMIN
```

With these caps added to my deployment config, I am able to run the container:

```
API listen on 0.0.0.0:2375
API listen on /var/run/docker.sock
```

**Comment by rhatdan** [comment]
Of course, I think it would be easier to run podman then use dind. :^)

**Comment by cevich** [comment]
woops...too fast to click w/o reading...this one ok to close @mschaefers

**Comment by manuelnucci** [comment]
Sorry to revive this issue but I'm getting an error after replicating everything @mschaefers did (more details [here](https://github.com/GoogleContainerTools/kaniko/issues/758#issuecomment-931406363)).

Is the error still consistent with some lack of permissions? What else can I add?
