### ISSUE TITLE
[RFE] pod status of "pending" not very useful

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2074]
"Pending" can have lots of different meanings. One, for example, is that the underlying host is doing a docker pull of the image. But "osc get pods" doesn't tell you that.

Is it possible to add "more" status to the Pending line? For example: Pending:Pulling 

I'm not sure what other pending states there are.

**Comment by ncdc** [comment]
Definitely a good request, although I assume this will need to go to Kubernetes upstream

**Comment by thoraxe** [comment]
Darnit, sorry.

**Comment by thoraxe** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/7784
