### ISSUE TITLE
NFS recycler broken

### ISSUE THREAD

**Issue by ctron** [openshift/origin#20748]
A new installation of OpenShift fails to recycle NFS volumes:

~~~
Aug 24 15:48:13 cluster00 origin-node[2162]: E0824 15:48:13.820063    2162 pod_workers.go:186] Error syncing pod a6a4b962-a7a3-11e8-8d13-9600000eef71 ("recycler-for-pv-12_openshift-infra(a6a4b962-a7a3-11e8-8d13-9600000eef71)"), skipping: failed to "StartContainer" for "pv-recycler" with ImagePullBackOff: "Back-off pulling image \"docker.io/openshift/origin-recycler:v1.10.0\""
~~~

##### Version

~~~
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://cluster00…
openshift v3.10.0+a5e4ac9-10
kubernetes v1.10.0+b81c8f8
~~~

##### Steps To Reproduce
1. Install OpenShift 3.10
2. Create and delete PVC based on NFS

##### Current Result

PV not recycled.

##### Expected Result

PV recycled.

**Comment by gnufied** [comment]
It is a known issue - https://github.com/openshift/origin/pull/20609 should fix it.

/sig storage

**Comment by Fodoj** [comment]
And what's the fix for running clusters?

**Comment by Fodoj** [comment]
@gnufied  Thanks, tagging image helped. I was trying to fix it this way https://github.com/openshift/origin/issues/20818, but that whole feature seems to be not implemented :)

**Comment by gnufied** [comment]
Yeah - no code change has actually happened between version of images, we are planning to fix this for good in 3.11 so as specifying custom path works properly.

**Comment by gnufied** [comment]
Closing since related PR was merged.

**Comment by Fodoj** [comment]
@gnufied what about https://github.com/openshift/origin/issues/20818 ?

**Comment by gnufied** [comment]
It is possible that- just the pv-recycler arguments are being masked by patch openshift carries to match versioning. I will look into it. The plan for 3.11 is to get rid of that custom patch and allow users to configure it and ship with reasonable default in openshift-ansible.
