### ISSUE TITLE
Router working inconsistently

### ISSUE THREAD

**Issue by azimovMichael** [openshift/origin#20742]
I have a cluster of 5 nodes: 3 masters and 5 (the 3 masters are also nodes) nodes.
After installing with the Ansible playbook, and deploying 3 demo apps there is a very strange problem.

We configured a dns similar to this: *.company.com so that every url with that suffix will go to one of the node IPs.

We configured routes (app1.company.com, app2.company.com, app3.company.com)  to the services, the router is on 5 instances, but when trying to access the routes via a browser it sometimes works and sometimes doesn't.

There isn't any visible similarity between the status of the service when it works and when it doesnt (sometimes the pod is running on node x and working, sometimes not) nor similarity between the IPs that the DNS sends the browser to.

##### Version
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://OUR_SERVER:8443
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1.Install cluster with ansible playbook
2.deploy new apps
3.create a DNS suffix that resolves to one of the 5 node IPs
4. create routes to your services with the specified suffix
5. try to access the apps via browser

##### Current Result
Sometimes we get the app sometimes we get the error page of the router.

##### Expected Result
Always get the app.

##### Additional Information
We run on an offline private network so this is the best info I can offer

**Comment by faust64** [comment]
Any chance your application was actually unavailable? What about your liveness and readiness probes? Any indication something flapped in your application's namespace?

Any chance the openshift-node service on the node running your application could have failed reporting to an openshift-master? Leading the routers to beleive your app was unavailable? In doubt: avoid proxies and load balancers here.

**Comment by jwforres** [comment]
@openshift/sig-network-edge
