### ISSUE TITLE
Error creating image secret

### ISSUE THREAD

**Issue by nightman68** [openshift/origin#20759]
When I try to create an images secret in GUI I receive an error:

`An error occurred while creating the secret.
 Reason: Secret "registry" is invalid: data[.dockercfg]: Required value`

##### Version
openshift v3.10.0+dd10d17

oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. In the UI navigate to Resources/Secrets
2. Select Image Secret
3. For Authentication Type select Configuration File
4. Open the config.json file in $HOME/.docker
5. Finish via Create

##### Current Result
`An error occurred while creating the secret.
 Reason: Secret "registry" is invalid: data[.dockercfg]: Required value`

##### Expected Result
The secret is created like in release 3.9 were it was working in the same way.

##### Additional Information
Creating the secret via cmd is working with the same file

`oc create secret generic secret --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson`

**Comment by jmwilkinson** [comment]
Also reproducible with `openshift v3.11.0-alpha.0+5a0e291-1298`

**Comment by jwforres** [comment]
@openshift/sig-user-interface

**Comment by nccurry** [comment]
Seeing this issue in the UI as well
