### ISSUE TITLE
oc new-project should have a flag that allows success if the project already exists

### ISSUE THREAD

**Issue by cunningt** [openshift/origin#20751]
oc new-project should have a flag that allows success if the project already exists.    At the moment, if you oc new-project an existing project

```
tcunning@tcunning-OSX:/tmp/prometheus-operator$ ~/bin/oc-v3.10/oc new-project myproject
Error from server (AlreadyExists): project.project.openshift.io "myproject" already exists
tcunning@tcunning-OSX:/tmp/prometheus-operator$ echo $?
1
```

There should be a flag like oc new-project --succeed-if-exists or something like that where the result is 0 even if the namespace previously exists.

In the case of minishift-addons, you want to be able have a conditional add of a new-project if it exists (see https://github.com/minishift/minishift-addons/pull/143).     A flag would enable that.

**Comment by ericavonb** [comment]
You can accomplish a conditional create with `oc new-project myproject || oc project myproject`. I'm going to close this issue for now.
```bash
$ oc new-project myproject || oc project myproject;
Error from server (AlreadyExists): project.project.openshift.io "myproject" already exists
Now using project "myproject" on server "https://127.0.0.1:8443".
$ echo $?
0
```
