### ISSUE TITLE
etcd.server.crt needs to be signed with all bind addresses

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#2075]
Due to etcd's propensity to advertise the list of machines as IP addresses, we need to ensure that etcd.server.crt is also signed for the IP address of the interfaces it may bind to. Please ensure that the etc.server.crt is signed for all IP addresses when binding to 0.0.0.0.

Note: this will only apply for embedded single etcd instances. etcd clusters will be on their own to build out certs using incantations `openshift admin create-server-cert` to generate certificates in those scenarios.

CC: @deads2k

**Comment by liggitt** [comment]
We can add more detected IP addresses to the certs, but that won't help in cases where the certs/config are generated on a machine other than the master.
