### ISSUE TITLE
origin clusterup 3.10 CI is broken

### ISSUE THREAD

**Issue by bparees** [openshift/origin#20766]
https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/directory/test_pull_request_origin_extended_clusterup_310

@stevekuznetsov @deads2k @smarterclayton

**Comment by jboyd01** [comment]
/assign jboyd01
I own service catalog.
3.10 is picking up 3.11 Service Catalog binary.

**Comment by jboyd01** [comment]
I may be looking in the wrong place, but this seems wrong:

https://github.com/openshift/aos-cd-jobs/blob/9b9020a119925e6ae325a96dc0d8093b0d286c57/sjb/config/test_cases/test_pull_request_origin_extended_clusterup_310.yml#L2

aos-cd-jobs/sjb/config/test_cases/test_pull_request_origin_extended_clusterup_310.yml
```
parent: 'common/test_cases/origin_release.yml'
```
I'd expect that to be using origin_release_310.yml.  It looks to me like origin_release and origin_release_310 is where we pick up the image releases to use.

**Comment by jboyd01** [comment]
discussed with cewong, he pointed me at https://github.com/openshift/origin/blob/720e11781483c0b1a729565085781347090948c7/test/extended/clusterup.sh#L369-L372

This is always going to pull the latest image.

It looks like web-console and docker-registry will have the same issue

**Comment by bparees** [comment]
> It looks like web-console and docker-registry will have the same issu

yes this was a bit of tech debt we punted on.

for console and registry I think it didn't matter since:

1) there were no changes that mattered between versions
2) the cluster up tests weren't intended to test those components in a meaningful way

anyway i think you can just change that `:latest` to `:v3.10` in the v3.10 branch?

**Comment by jboyd01** [comment]
@bparees sounds good to me - I was going to parameterize it but hard coding is quicker/easier.

**Comment by bparees** [comment]
> @bparees sounds good to me - I was going to parameterize it but hard coding is quicker/easier.

why fix it permanently when we can leave a ticking timebomb for someone else to waste time on in the future? :)

but seriously, if it weren't for how much of this is going to change in 4.0 anyway, i might argue for a better solution.

**Comment by stevekuznetsov** [comment]
Is this fixed with #20785?

**Comment by bparees** [comment]
looks like it, since cluster up job passed on that PR.
