### ISSUE TITLE
Node_exporter Dashboard

### ISSUE THREAD

**Issue by ionutancuta** [openshift/origin#20776]
Hello,

Can you please tell me on which version of Grafana is Node_exporter Dashboard made? And also if it can be used with a prometheus datasource? I tried to use the the suggested one from the description but it has  different label names.

Thanks a lot! :)

**Comment by jwforres** [comment]
When you say you used the suggested one from the description, what do you mean, can you point to which docs you were looking at? If it was the existing promehteus / grafana related examples in this repo, these are very outdated and are being replaced in favor of the [cluster-monitoring-operator](https://github.com/openshift/cluster-monitoring-operator) setup
cc @openshift/sig-monitoring
