### ISSUE TITLE
how to setup origin cluster from own source

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin#20771]
Hi , I have installed openshift origin OKD recently using ansible installer , which works fine. I know that it pulls source code from here https://github.com/openshift/origin .

Can anyone tell me where in ansible inventory the source code location is defined , we are looking to clone the code and have it on private git repo for some customization. 

Is it possible to do it? Please let me know if we can deploy cluster from git source other than public git and where it can be defined in ansible inventory.

Thanks a lot!

**Comment by jwforres** [comment]
@priyanka5 since this is a question mainly about openshift-ansible, you might want to open the issue to that repo instead

**Comment by sdodson** [comment]
Openshift-ansible installs rpms from the Centos PaaS SiG by default. You would need to build rpms which I believe can be handled by hack/build-rpms.sh in the origin repo. Then you would need to build a yum repo and ensure that's configured for hosts that you intent to use. 

Beyond that, you'll want to build images and push those to a registry and configure the installer to use images from that registry by setting oreg_url as described in openshift-ansible repo.
