### ISSUE TITLE
secure(https) route breaks on deployed eap template

### ISSUE THREAD

**Issue by amitkrout** [openshift/origin#20770]
[provide a description of the issue] 
Template (JBoss EAP 7.1 + PostgreSQL (Persistent with https)) deployment went fine, however the problem arises while accessing the secure(https) route whereas http route works fine.

##### Version
```
$ ./oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.10.0+720e117-14
kubernetes v1.10.0+b81c8f8
```
##### Steps To Reproduce
1. oc cluster up
2. oc login -u system:admin
3. oc apply -f xpaas/xpaas-streams/ -n openshift
```
Image stream location - https://github.com/openshift/openshift-ansible/tree/release-3.9/roles/openshift_examples/files/examples/v3.9/xpaas-streams
```
4. oc apply -f xpaas/xpaas-templates/ -n openshift
```
Template location - https://github.com/openshift/openshift-ansible/tree/release-3.9/roles/openshift_examples/files/examples/v3.9/xpaas-templates
```
5. oc login -u developer -p developer
6. oc apply -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/secrets/eap7-app-secret.json -n myproject
7. Deploy template JBoss EAP 7.1 + PostgreSQL (Persistent with https) trough console or using oc (oc new-app eap71-postgresql-persistent-s2i)
8. Access the secure route
```
$ curl -k https://secure-eap-app-myproject.127.0.0.1.nip.io 
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to secure-eap-app-myproject.127.0.0.1.nip.io:443
```
##### Current Result
$ curl -k https://secure-eap-app-myproject.127.0.0.1.nip.io 
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to secure-eap-app-myproject.127.0.0.1.nip.io:443
##### Expected Result
Should be accessible

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jwforres** [comment]
@openshift/sig-network-edge

**Comment by TomasTomecek** [comment]
I have the same problem.
