### ISSUE TITLE
v3.10 - Add externalIPNetworkCIDRs in master-config.yaml breaks the cluster.

### ISSUE THREAD

**Issue by Jorge-Dacal** [openshift/origin#20773]
## Description of the issue
If I modify `externalIPNetworkCIDRs: null` with my ip network "10.30.38.0/23" in `/etc/origin/master/master-config.yaml` and openshift don't start.
```
"externalIPNetworkCIDRs": "10.30.38.0/23"
```
I need it because I want to make the service of a database inside OpenShift accessible from the outside for example with MongoDB Compass.
```
# oc get service
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
mongodb   ClusterIP   172.30.164.12   <none>        27017/TCP   4h
```
To do that I now that I need to make the service external. Openshift need the first step to allow it, if not:
```
# oc patch svc mongodb -p '{"spec":{"externalIPs":["10.30.39.36"]}}'
The Service "mongodb" is invalid: spec.externalIPs: Forbidden: externalIPs have been disabled
```
But when I try to start openshift, the cluster doesn't start.

If I go to `./openshift.local.clusterup/kube-apiserver/master-config.yaml` and I put the `"externalIPNetworkCIDRs": null` again, openshift up correctly and I can acces to webconsole and all apps that have normal routes, but offcourse, I can't add external ip for a services.

**PS**: I want to take this opportunity to tell you **this file have all the configuration in the same line, and it is very annoying to read it**.

---
##### Version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. `$ sudo su`
2. Starts Openshift: `# oc cluster up --public-hostname='10.30.39.36'`
3. Enter in a running openshift container: `# docker exec -it origin bash`
4. Edit master-config.yaml: `# vi ./openshift.local.config/master/master-config.yaml` and **modify** `externalIPNetworkCIDRs: null` **for** `externalIPNetworkCIDRs: 10.30.38.0/23` (ip address of my machine) and **save** with `:wq`
5. Exit for the running container: `# exti`
6. Restart openshift: `# oc cluster down` and `# oc cluster up --public-hostname='10.30.39.36'`

##### Current Result
```
# oc cluster up --public-hostname='10.30.39.36'
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 10.30.39.36 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0828 09:36:55.253815    4142 flags.go:30] Running "create-kubelet-flags"
I0828 09:36:55.877287    4142 run_kubelet.go:48] Running "start-kubelet"
I0828 09:36:56.158482    4142 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
E0828 09:41:56.161633    4142 run_self_hosted.go:542] API server error: Get https://10.30.39.36:8443/healthz?timeout=32s: dial tcp 10.30.39.36:8443: getsockopt: connection refused ()
Error: timed out waiting for the condition
```
If I ask about openshift status I obtained this:
```
# oc status
The connection to the server 10.30.39.36:8443 was refused - did you specify the right host or port?
The connection to the server 10.30.39.36:8443 was refused - did you specify the right host or port?
```
I also try to add this ip to the docker insecure-registry, but the error persists, I guess it has nothing to do, but I tried.

##### Expected Result
Openshift starts correctly and I can use the ip for openshift services as an external ip.

##### Some of your documentation that I follow to do it:
- https://docs.okd.io/3.10/install_config/configuring_sdn.html#external-access-to-the-cluster-network
- https://docs.okd.io/3.10/architecture/core_concepts/pods_and_services.html
- https://docs.openshift.com/container-platform/3.10/architecture/core_concepts/pods_and_services.html#service-externalip
- https://docs.openshift.com/container-platform/3.10/admin_guide/tcp_ingress_external_ports.html#unique-external-ips-ingress-traffic-configure-cluster

##### Additional Information
```
# oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/root/.kube/config'

ERROR: [CED1008 from controller openshift/origin/pkg/oc/admin/diagnostics/cluster.go]
       Unknown error testing cluster-admin access for context 'insere/10-30-39-36:8443/admin':
       Post https://10.30.39.36:8443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews: dial tcp 10.30.39.36:8443: getsockopt: connection refused

ERROR: [CED1008 from controller openshift/origin/pkg/oc/admin/diagnostics/cluster.go]
       Unknown error testing cluster-admin access for context 'default/10-30-39-36:8443/system:admin':
       Post https://10.30.39.36:8443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews: dial tcp 10.30.39.36:8443: getsockopt: connection refused

[Note] Could not configure a client with cluster-admin permissions for the current server, so cluster diagnostics will be skipped

[Note] Running diagnostic: ConfigContexts[myproject/10-30-39-36:8443/admin]
       Description: Validate client config context is complete and has connectivity

ERROR: [DCli0015 from diagnostic ConfigContexts@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/client/config_contexts.go:299]
       For client config context 'myproject/10-30-39-36:8443/admin':
       The server URL is 'https://10.30.39.36:8443'
       The user authentication is 'admin/10-30-39-36:8443'
       The current project is 'myproject'
       (*url.Error) Get https://10.30.39.36:8443/apis/project.openshift.io/v1/projects: dial tcp 10.30.39.36:8443: getsockopt: connection refused
       Diagnostics does not have an explanation for what this means. Please report this error so one can be added.

[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint

ERROR: [DCli2001 from diagnostic DiagnosticPod@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/client/pod/run_diagnostics_pod.go:97]
       Creating diagnostic pod with image openshift/origin-deployer:v3.10.0 failed. Error: (*url.Error) Post https://10.30.39.36:8443/api/v1/namespaces/insere/pods: dial tcp 10.30.39.36:8443: getsockopt: connection refused

[Note] Summary of diagnostics execution (version v3.10.0+dd10d17):
[Note] Errors seen: 4
```

**Comment by mickuehl** [comment]
Jorge, did you test/try this on an actual Openshift cluster or just locally via 'oc cluster up' ? Just a hunch here but it might be that the *local/containerized* OpenShift behaves differently than the real thing...

**Comment by Jorge-Dacal** [comment]
I only test it on a remote machine with Centos7 using Openshift Origin v3.10 and starting it with the command `oc cluster up`

```
# hostnamectl
   Static hostname: nldcavm43374805
   Pretty hostname: NLDCAVM43374805
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 37fff67c54f945cabc44b14430c1c0ae
           Boot ID: 77dd89c63ebf4d5abf8b7d8ed60c43d7
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-862.6.3.el7.x86_64
      Architecture: x86-64
```

The only difference between the two clusters is on ./openshift.local.clusterup/kube-apiserver/master-config.yaml
**It does not work:** "externalIPNetworkCIDRs":"10.36.38.0/23"
**It works (it is the default config):** "externalIPNetworkCIDRs":null

These are the complete logs:
- [non externalIPNetworkCIDRs (level5).log](https://github.com/openshift/origin/files/2339393/non.externalIPNetworkCIDRs.complete.-.level5.log)
- [externalIPNetworkCIDRs (level5).log](https://github.com/openshift/origin/files/2339472/externalIPNetworkCIDRs.complete.short.-.level5.log)

**Comment by isaldarriaga** [comment]
@Jorge-Dacal try

```
networkConfig:
  externalIPNetworkCIDRs:
  - 10.30.38.0/23
```
externalIPNetworkCIDRs node behaves like a list.

that worked for me.

**Comment by jwforres** [comment]
Yeah sounds like the API server is failing to start because it had an invalid master-config.yaml, previous comment would be strong evidence of that if you are setting a single value where it is expecting it to be a list.

The errors which caused the master to fail to start could probably be surfaced better.

cc @openshift/sig-master 

But since it seems like fundamentally this was an invalid master-config I'm closing this particular issue.

@Jorge-Dacal if the [config change](https://github.com/openshift/origin/issues/20773#issuecomment-422837093) doesn't fix your issue, feel free to re-open

**Comment by Jorge-Dacal** [comment]
I tried to write it in many ways.
```
"externalIPNetworkCIDRs": "10.30.38.0/23"
```
```
externalIPNetworkCIDRs:
- 10.30.38.0/23
```
```
externalIPNetworkCIDRs: [10.30.38.0/23]
```
And none worked. In addition, from the previous version, when reading this type of files appear by console as badly formatted, and this did not happen in previous versions 3.6.

**Comment by ChaitanyaKr** [comment]
@Jorge-Dacal Hi, were you able to get this working? I tried the list thing and using the `oc patch ...` command too, but it always reports `spec.externalIPs: Forbidden: externalIPs have been disabled` despite it being set in master-config.yaml.

I have been using the `oc` binary on an Ubuntu VM, to toy around with OpenShift and I'm able to do most things (deploy, expose services), except getting external IPs working.
I'm starting to think its because of my setup but can someone confirm if that's the case?
