### ISSUE TITLE
[Conformance][Area:Networking][Feature:Router] The HAProxy router should support reencrypt to services backed by a serving certificate automatically

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#20794]
Seems like the test is permanently broken and it blocks entire queue:

Example:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20790/pull-ci-origin-e2e-gcp/2978/

Marking as P0.

**Comment by ironcladlou** [comment]
Ack, will prioritize it today

**Comment by sdodson** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/9801/pull-ci-openshift-openshift-ansible-e2e-gcp/1865/

**Comment by ironcladlou** [comment]
We're observing two flakes in the extended router tests. The first one is an intermittent image pull failure for `nginx:latest`:

```
Aug 29 11:58:56.020: INFO: At 2018-08-29 11:55:39 +0000 UTC - event for serving-cert: {default-scheduler } Scheduled: Successfully assigned e2e-test-router-reencrypt-rxpwr/serving-cert to ci-op-wskwd3q5-eb354-ig-n-spsk
Aug 29 11:58:56.020: INFO: At 2018-08-29 11:55:47 +0000 UTC - event for serving-cert: {kubelet ci-op-wskwd3q5-eb354-ig-n-spsk} Pulling: pulling image "nginx:latest"
Aug 29 11:58:56.020: INFO: At 2018-08-29 11:55:51 +0000 UTC - event for serving-cert: {kubelet ci-op-wskwd3q5-eb354-ig-n-spsk} Failed: Failed to pull image "nginx:latest": rpc error: code = Unknown desc = no supported platform found in manifest list
Aug 29 11:58:56.020: INFO: At 2018-08-29 11:55:51 +0000 UTC - event for serving-cert: {kubelet ci-op-wskwd3q5-eb354-ig-n-spsk} Failed: Error: ErrImagePull
Aug 29 11:58:56.020: INFO: At 2018-08-29 11:56:08 +0000 UTC - event for serving-cert: {kubelet ci-op-wskwd3q5-eb354-ig-n-spsk} BackOff: Back-off pulling image "nginx:latest"
Aug 29 11:58:56.020: INFO: At 2018-08-29 11:56:08 +0000 UTC - event for serving-cert: {kubelet ci-op-wskwd3q5-eb354-ig-n-spsk} Failed: Error: ImagePullBackOff
```

The pull failure needs diagnosed.

The other problem is a race condition with some test pods which reference secrets created by the service cert signing service at the same time, causing intermittend pod volume mount failures at pod creation time:

* https://github.com/openshift/origin/blob/master/test/extended/testdata/reencrypt-serving-cert.yaml
* https://github.com/openshift/origin/blob/master/test/extended/testdata/router-config-manager.yaml

```
Aug 29 10:45:51.057: INFO: At 2018-08-29 10:42:41 -0400 EDT - event for serving-cert: {default-scheduler } Scheduled: Successfully assigned e2e-test-router-reencrypt-4tnfk/serving-cert to dmace-ig-n-bw3j
Aug 29 10:45:51.057: INFO: At 2018-08-29 10:42:42 -0400 EDT - event for serving-cert: {kubelet dmace-ig-n-bw3j} FailedMount: MountVolume.SetUp failed for volume "cert" : secrets "serving-cert" not found
```

The tests and fixtures will need refactored to create the service, wait for the secret, and then create the pod which depends on the secret.

**Comment by ironcladlou** [comment]
Re: https://github.com/openshift/origin/issues/20794#issuecomment-417067486, @deads2k pointed out that the pods should wait for the secret automatically, and so our root cause diagnosis is incorrect.

**Comment by ironcladlou** [comment]
@bparees any idea about the pull failure in https://github.com/openshift/origin/issues/20794#issuecomment-417067486?

**Comment by bparees** [comment]
@ironcladlou that's just a pod trying to run docker.io/library/nginx:latest?

**Comment by bparees** [comment]
So basically it's either a docker hub flake (serving a bad manifestlist periodically), or it's a node bug that the node is trying to pull/look for the wrong architecture.

nginx (and the other "library" images in docker hub) all have manifestlists which means they support multiple architectures.

If you can move to another image, i'd do that.  Possibly pulling nginx and pushing it to your own docker hub repository.

**Comment by Miciah** [comment]
https://github.com/openshift/openshift-docs/blob/60f49ce0cfc3c7a5d70b1b658d82db7055445ac3/dev_guide/secrets.adoc#restrictions states,

> When a template contains a secret definition, the only way for the template to use the provided secret is to ensure that the secret volume sources are validated and that the specified object reference actually points to an object of type Secret. Therefore, a secret needs to be created before any pods that depend on it.

Arguably, "a secret definition" means an explicit `kind: Secret` object as opposed to a secret specified using the `service.alpha.openshift.io/serving-cert-secret-name` annotation, but this is not clear—and does it matter how the secret is defined? In any case, the section on restrictions immediately follows the section on service-serving certificates, so the quoted text would appear to be a caveat for service-serving certificates.

So the test is depending on not just undocumented behavior, but _contrary_-to-documented behavior. 

Should I submit a PR against openshift-docs to clarify that something (what specifically—the kubelet? the scheduler?) waits until any and all secrets volumes referenced in the pod spec are ready before scheduling/starting the pod?

**Comment by ironcladlou** [comment]
@bparees 
>So basically it's either a docker hub flake (serving a bad manifestlist periodically), or it's a node bug that the node is trying to pull/look for the wrong architecture.

>nginx (and the other "library" images in docker hub) all have manifestlists which means they support multiple architectures.

>If you can move to another image, i'd do that. Possibly pulling nginx and pushing it to your own docker hub repository.

I guess I don't see how this fixture is different than any other I see in the extended test fixtures, many of which I've spot checked use public images from dockerhub in exactly the same way. I'm not opposed to changing the way we do it, just wanted to state it doesn't yet seem like a problem specific to the router test in question.

**Comment by bparees** [comment]
> I guess I don't see how this fixture is different than any other I see in the extended test fixtures, many of which I've spot checked use public images from dockerhub in exactly the same way. 

Are the other fixtures using images from "library"?  library is a bit unique since those images use manifestlists (which appears to be what caused the issue here) and most other images do not.

The other possibility is that it's flat out a corruption issue in dockerhub..perhaps one registry instance has a bad manifestlist and when you hit that one, you get this issue.  Have you tried pulling the image repeatedly yourself or otherwise attempted to recreate it?  

How long has this been going on? how often does it happen?

>  just wanted to state it doesn't yet seem like a problem specific to the router test in question.

Agreed, it's not the test's fault, it is either:
1) dockerhub serving bad content sporadically
2) (less likely) a node issue pulling the image where it mishandles the manifestlist periodically.

**Comment by ironcladlou** [comment]
Since it appears we no longer have any way of tracking flake stats, I'm going to say https://github.com/openshift/origin/pull/20809 closes this and we can re-open the issue if errors continue to be observed.
