### ISSUE TITLE
 Error: a port needed by OpenShift is not available caused By:      Error: ports in use: [80 443 8443 10250 53 8053]

### ISSUE THREAD

**Issue by intalent** [openshift/origin#20802]
[i have insatlled openshift origin with the help of below link]
https://github.com/vipin-k/Openshift-Cluster/blob/master/manual

##### Version
oc version
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

#### Environment:
0s:centos 7minimal
use two vms inside the virtual machine on local box

[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [ follow the above mentioned link steps to setup the the open shift cluster]
2. [ ]oc cluster up --public-hostname=192.168.122.184 --loglevel=8

##### Current Result

I0829 22:53:12.990988   13066 helper.go:934] Used ports in container: map[int]struct {}{10250:struct {}{}, 8444:struct {}{}, 10444:struct {}{}, 22:struct {}{}, 1936:struct {}{}, 8443:struct {}{}, 443:struct {}{}, 111:struct {}{}, 8053:struct {}{}, 10256:struct {}{}, 25:struct {}{}, 2379:struct {}{}, 2380:struct {}{}, 80:struct {}{}, 53:struct {}{}, 10443:struct {}{}}
F0829 22:53:12.991095   13066 helpers.go:119] error: FAIL
   Error: a port needed by OpenShift is not available
   Caused By:
     Error: ports in use: [80 443 8443 10250 53 8053]

for detailed error
https://paste.fedoraproject.org/paste/~dWKmuYpYmhs-88z~uEZcw

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by intalent** [comment]
Thanks, i tried like below options.
Stop the below services and do cluster up and start the services its working
origin-master-api
origin-master-controllers
origin-node-dep

**Comment by trevlin-armugam** [comment]
Have you tried restarting docker @intalent ? I ran into the same issue and a simple restart freed the port which was previously blocked
