### ISSUE TITLE
latest rebase doesn't provide for ability to specify where certs go

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2081]
When executing the following (string array):

`["/usr/bin/openshift", "start", "master", "--write-config=/etc/openshift/master", "--portal-net=172.30.17.0/24", "--etcd-dir=/var/lib/openshift/", "
--master=https://ose3-master.example.com:8443", "--public-master=https://ose3-master.example.com:8443", "--listen=https://0.0.0.0:8443", "--images=openshift3_beta/ose-${component}:${version}"]`

You end up with all of the generated certificates in `/etc/openshift/master`

I don't see any option to configure where certificates go:

```
[root@ose3-master openshift-ansible]# openshift start --help                                                                                                                                               [2/4108]
Start an OpenShift all-in-one server

This command helps you launch an OpenShift all-in-one server, which allows
you to run all of the components of an OpenShift system on a server with Docker. Running

    $ openshift start

will start OpenShift listening on all interfaces, launch an etcd server to store persistent
data, and launch the Kubernetes system components. The server will run in the foreground until
you terminate the process.  This command delegates to "openshift start master" and 
"openshift start node".


Note: starting OpenShift without passing the --master address will attempt to find the IP
address that will be visible inside running Docker containers. This is not always successful,
so if you have problems tell OpenShift what public address it will be via --master=<ip>.

You may also pass --etcd=<address> to connect to an external etcd server.

You may also pass --kubeconfig=<path> to connect to an external Kubernetes cluster.

Available Commands: 
  master      Launch OpenShift master
  node        Launch OpenShift node

Options:
      --cors-allowed-origins=[]: List of allowed origins for CORS, comma separated.  An allowed origin can be a regular expression to support subdomain matching.  CORS is enabled for localhost, 127.0.0.1, and th
e asset server by default.
      --create-certs=true: Indicates whether missing certs should be created
      --etcd='https://0.0.0.0:4001': The address of the etcd server (host, host:port, or URL). If specified, no built-in etcd will be started.
      --etcd-dir='openshift.local.etcd': The etcd data directory.
      --hostname='ose3-master.example.com': The hostname to identify this node with the master.
      --images='openshift/origin-${component}:${version}': When fetching images used by the cluster for important components, use this format on both master and nodes. The latest release will be used by default.
      --latest-images=false: If true, attempt to use the latest images for the cluster instead of the latest release.
      --listen='https://0.0.0.0:8443': The address to listen for connections on (scheme://host:port).
      --master='https://localhost:8443': The master address for use by OpenShift components (host, host:port, or URL). Scheme and port default to the --listen scheme and port. When unset, attempt to use the firs
t public IPv4 non-loopback address registered on this host.
      --master-config='': Location of the master configuration file to run from. When running from configuration files, all other command-line arguments are ignored.
      --network-plugin='': The network plugin to be called for configuring networking for pods.
      --node-config='': Location of the node configuration file to run from. When running from configuration files, all other command-line arguments are ignored.
      --nodes=[]: The hostnames of each node. This currently must be specified up front. Comma delimited list
      --portal-net=172.30.0.0/16: A CIDR notation IP range from which to assign portal IPs. This must not overlap with any IP ranges assigned to nodes for pods.
      --public-master='https://localhost:8443': The master address for use by public clients, if different (host, host:port, or URL). Defaults to same as --master.
      --volume-dir='openshift.local.volumes': The volume storage directory.
      --write-config='': Directory to write an initial config into.  After writing, exit without starting the server.

Use "openshift start <command> --help" for more information about a given command.
```

**Comment by liggitt** [comment]
the certs and config files go under the `--write-config` directory

**Comment by smarterclayton** [comment]
Working as designed.

**Comment by liggitt** [comment]
if you want the certs elsewhere, you can put them anywhere you want and modify the references to them in the config file

**Comment by thoraxe** [comment]
Certs are not configuration and do not belong in /etc. Yaml is
configuration and does not belong in /var

Having a configuration generator that then requires tons of effort to
massage its output after use just to be able to conform to Linux filesystem
standards makes the generator mostly useless.

**Comment by smarterclayton** [comment]
Consumability and easy setup trumps Linux filesystem conventions.  I'm not even sure I care about the conventions, since you should not be massaging this output for arbitrary reasons.

**Comment by thoraxe** [comment]
Consumability by whom? 

Easy setup for whom? 

How does putting files in the nonstandard place, that almost all other Linux software conforms to well, cause difficulty in either setup or consumability?

**Comment by thoraxe** [comment]
Sorry, I meant "how does it prevent", but you get my gist.

**Comment by liggitt** [comment]
At the moment, one of the two main use cases for the output of the bootstrapped config is to bundle it up into a secret, and inject it into a pod so we can run OpenShift in a pod on GCE. Spreading the generated config files across multiple directories would prevent that.

> Certs are not configuration and do not belong in /etc

I would disagree... server certs are definitely part of the server configuration

**Comment by sdodson** [comment]
I think there's plenty of prior art on our side too, apache and other services store their certs in /etc, just look in /etc/pki.

**Comment by thoraxe** [comment]
So @sdodson is voting for multi-directory, too.  :-) 

And why would having the files in multiple dirs be a problem if you're injecting the configuration? Wouldn't it just have a path? The cert files have to be injected into the container, too, don't they?

**Comment by liggitt** [comment]
the mechanism we have for injecting config containing secret data is Kubernetes secrets, which are limited to flat file lists.

**Comment by thoraxe** [comment]
I don't understand what that means in the context of "foo.crt" versus "/etc/pki/tls/foo.crt"

**Comment by liggitt** [comment]
it means you couldn't package up things in multiple directories into a Kubernetes secret to inject into a pod

**Comment by sdodson** [comment]
Hmm, what I meant is that I'm fine with it as is in origin/master right now.

**Comment by thoraxe** [comment]
If you can't package things in multiple directories into a Kubernetes secret to inject into a pod, doesn't that indicate a shortcoming in Kubernetes/secrets?
