### ISSUE TITLE
oc cluster up with all features enabled fails

### ISSUE THREAD

**Issue by magick93** [openshift/origin#20811]
[provide a description of the issue]

##### Version

oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. Run `oc cluster up --h`. Notice that there is an option to include `--enable=[*]`
2. Run `oc cluster up --enable=[*]`

FYI, I also tried the folowing:

```
➜  git oc cluster up --enable=[*]
zsh: no matches found: --enable=[*]
➜  git oc cluster up --enable=[metrics]
zsh: no matches found: --enable=[metrics]
➜  git oc cluster up --enable=["metrics"]
zsh: no matches found: --enable=[metrics]
➜  git oc cluster up --enable=['metrics']
zsh: no matches found: --enable=[metrics]
```

##### Current Result

`no matches found: --enable=[*]`
##### Expected Result
Expect openshift cluster to be up with all features enabled.

**Comment by jorgemoralespou** [comment]
have you tried `oc cluster up --enable=*`?

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by juanvallejo** [comment]
Try putting the value of --enable in quotes `--enable="[*]"`

**Comment by magick93** [comment]
> Try putting the value of --enable in quotes --enable="[*]"

Thanks @juanvallejo - that works.

Its probably worth updating the docs so that the use of `" "` is mentioned.
