### ISSUE TITLE
oc get --export scc/<name> doesn't work like oc export scc/<name>

### ISSUE THREAD

**Issue by IlonkaO** [openshift/origin#20813]
After recognized the message that "oc export" is deprecated and I should use "oc get --export" I tried it with the command "oc get --export scc/privileged" and get only the description of the scc that would appears also without the option --export

##### Version
oc v3.10.14
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server xxx:8443
openshift v3.10.14
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. oc export scc/privileged
2. oc get --export scc/privileged (or oc get scc/privileged --export)

##### Current Result
``
NAME         PRIV      CAPS      SELINUX    RUNASUSER   FSGROUP    SUPGROUP   PRIORITY   READONLYROOTFS   VOLUMES
privileged   true      [*]       RunAsAny   RunAsAny    RunAsAny   RunAsAny   <none>     false            [*]
``

##### Expected Result
```
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
apiVersion: v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:nodes
- system:masters
kind: SecurityContextConstraints
metadata:
....
```

**Comment by IlonkaO** [comment]
Update: 
The challenge is not only for scc. I tried it also for user and deploymentconfig. Always the same issue

**Comment by enj** [comment]
@openshift/sig-master @openshift/sig-security

**Comment by juanvallejo** [comment]
This is expected. Only a few resources have a custom export strategy defined server-side.
For exporting resources it is ultimately better to export all of the data as-is (in a lossless manner), then modify the object at import-time with any specific changes that it needs.

cc @deads2k

**Comment by soltysh** [comment]
That is correct, besides `oc export ` is deprecated since 3.10 and is slated for removal in the next release. `oc get --export` is the only available option for now.

**Comment by IlonkaO** [comment]
I understand your arguments, but in the OpenShift docs would be mentioned that I can export any information like in my example above. And that doesn't work with oc get --export. So the note that oc export is deprecated and I should use oc get --export is not correct!
And I'm wondering where then I can get the relevant information???

**Comment by soltysh** [comment]
`oc get <resource> -o yaml --export` is all you need.

**Comment by jwforres** [comment]
Closing based on discussion
