### ISSUE TITLE
Re-enable disable 'starting a build without a --from-xxxx value' test

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#20828]
This is part of the extended build test and got broken recently. It seems like a validation problem in the `start-build` command. 

The test was disabled in https://github.com/openshift/origin/pull/20772.

/cc @bparees 
/cc @juanvallejo 
/sig master

**Comment by bparees** [comment]
this isn't just about fixing a test, it's about fixing what is now a nil pointer error that occurs when you do this, right?

i'm closing this and opening a BZ so we do not ship 3.11 w/ this issue.

https://bugzilla.redhat.com/show_bug.cgi?id=1624950
