### ISSUE TITLE
Propogate back the BuildFailureReasons in the build logs API

### ISSUE THREAD

**Issue by HackToHell** [openshift/origin#20827]
Errors in the openshift build logs API in case of failure do not propagate the underlying reason back to the caller.

##### Version
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Start a build, delete the build pod
2. Hit the logs API, you will get a 400 BadRequest with a very generic errror.

##### Current Result
`Error from server (BadRequest): build bc-281-4 is in an error state. No logs are available.`
##### Expected Result
The Reason field of StatusError should contain the same error which caused the build to fail

##### Additional Information

The specific line of code, 
https://github.com/openshift/origin/blob/master/pkg/build/apiserver/registry/buildlog/rest.go#L115.

I can send a PR if you think this is a okay way to go.

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
@HackToHell sure, open a PR and we can discuss it there, sending back the build object's status message, if there is one available, seems like a useful enhancement.
