### ISSUE TITLE
OKD 3.10 forbidden pull images from internal registry

### ISSUE THREAD

**Issue by cello86** [openshift/origin#20834]
On a fresh installation OKD 3.10 cluster we can't deploy a new pod into a project because the compute nodes receive a forbidden result during the pull of the container image from the internal registry.

```
Failed to pull image "docker-registry.default.svc:5000/test-dev/rocketchat@
sha256:cd89f9d942d18d625d1d64c716e455a9621e5051b85d7da82d3ee967cf1f9d7e": 
rpc error: code = Unknown desc = Get https://docker-registry.default.svc:5000/v2/: Forbidden
```
##### Version
```
# oc version
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://dev-openshift.fineco.it:443
openshift v3.10.0+8e19bad-29
kubernetes v1.10.0+b81c8f8
```
##### Steps To Reproduce
1. create a new deployment config from web UI related to an image stream tag from the internal registry
2. start the first deployment or force a new deploy.

##### Current Result
The pod fails the startup with error reported above.

##### Expected Result
The pod completes the startup phase

##### Additional Information
We have already checked the project configuration for role system:puller for the authenticated users.

```
# oc get rolebinding | grep puller
system:image-pullers      /system:image-pullers                             system:serviceaccounts:test-dev                      
system:image-pullers-0    /system:image-pullers                             system:authenticated                                   
system:image-pullers     /system:image-pullers                             system:serviceaccounts:test-dev  
```

**Comment by jwforres** [comment]
How are you deploying the cluster, via openshift-ansible, or `oc cluster up`

@openshift/sig-developer-experience

**Comment by bparees** [comment]
you're trying to pull an image from a project named "test-dev", what project is your pod in?

how did you create the imagestreamtag in the first place?
