### ISSUE TITLE
Change password on server LDAP it has no effect [CLI]

### ISSUE THREAD

**Issue by 22RC** [openshift/origin#20841]
Hi all,
I use LDAPPasswordIdentityProvider as authentication method. I see that the `oc login` command automatically creates and manages CLI configuration files. All information gathered by the command is stored in a configuration file located in ~/.kube/config. Well, in case of i would changed password of a specific user ( on server LDAP ), and re-connected my user with `oc login` command, I expect that it wants again a password (because the last token is differt to new password). But it logged my user succesfully, without inserting password. 

##### Version
`$ oc version: oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8 `

##### Steps To Reproduce
1. `oc login -u joe`
result:
`Authentication required for https://serverOKD:8443 (openshift)
Username: joe
Password: `
2. change password on Server LDAP
3. `oc login -u joe`
result:
`Logged into "https://serverOKD:8443" as "joe" using existing credentials.`

##### Additional Information
When i delete user and it identity:
`oc delete user joe;
 oc delete identity/ldap_identity:uid:joe,ou=Users,dc=ldap,dc=com`
I can re-insert password on log-in, but i think it is wrong way.

**Comment by ericavonb** [comment]
Yes. This is because the token had not yet expired. By default, tokens have a 24hr lifetime: https://docs.okd.io/3.10/install_config/configuring_authentication.html#token-options .
