### ISSUE TITLE
Add a TILLER_NAMESPACE env variable via OC CLI

### ISSUE THREAD

**Issue by gkarthiks** [openshift/origin#20851]
Adding a `TILLER_NAMESPACE` env variable and putting the current `Project` into that and refreshing that env variable when even user is changing to other projects. Because its painful to append the tiller-namespace in helm every time.

##### Version
oc v3.9.0+191fece

##### Current Result
Doesn't put ant env variable.

##### Expected Result
Puts an env variable named `TILLER_NAMESPACE` with the current project as value.

As of now I am doing that with the below bash. But doesn't work if I change project.
export TILLER_NAMESPACE=$(echo $(oc config current-context)| cut -d'/' -f 1)

/component/cli 
@openshift/sig-master

**Comment by gkarthiks** [comment]
I am using some bash function like here.

https://github.com/gkarthiks/ocp

**Comment by jwforres** [comment]
are you asking for `oc project` to set the TILLER_NAMESPACE env for you whenever you switch projects?

@openshift/sig-master

**Comment by gkarthiks** [comment]
@jwforres  yeah, that right. Because as I mentioned in my previous comment I am doing that with a utility function [https://github.com/gkarthiks/ocp](https://github.com/gkarthiks/ocp) sourced into my profile. Works fine.. but thought it would be great to have as part of `oc cli`.

**Comment by soltysh** [comment]
I'm hesitant to add support for such functionality. `TILLER_NAMESPACE` is something external to oc, and expecting `oc` to set it is not something I'd approve. Why having an alias or bash funciton that does just is wrong approach?
