### ISSUE TITLE
Oc command not found 

### ISSUE THREAD

**Issue by lordcf** [openshift/origin#20861]
i did follow all the steps as mentioned but while doing oc cluster up I am getting an error that oc command not found 
using 
AWS VM with 8GB RAM
centos version 7
openshift origin v3.10.0

**Comment by deads2k** [comment]
Try making sure that you're running the `oc` you expect.  Depending on how you got `oc` you may have to make sure that it is in your path.  For instance, if you downloaded an archive, you can expect to have to do `./oc` or `/path/to/oc`.

**Comment by jwforres** [comment]
Without knowing which steps you were following it will be difficult to provide any other feedback on this issue. As suggested you should make sure oc is in your path.
