### ISSUE TITLE
Duplicated DNS 'A' records for services with more than one port

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2087]
If you have service defined with more then one port the DNS subsystem will add additional A record for the endpoint for each port defined. This cause to have duplicated A records.

To reproduce, you can create this template: 
https://github.com/mfojtik/origin/blob/etcd_example/examples/etcd/template.json

Then scale it up to 3 pods and docker exec into one of the Pods. Then use this command:

```
dig etcd A +search +short
```

This will return duplicated A records for each Pod.

**Comment by mfojtik** [comment]
@smarterclayton @rajatchopra FYI

**Comment by mfojtik** [comment]
I think the problem is here:

https://github.com/openshift/origin/blob/master/pkg/dns/serviceresolver.go#L77

This should not be loop but we should just take the first port, correct?

**Comment by smarterclayton** [comment]
Probably.  There are other DNS changes I need to make though, partially to fit to 6666 upstream, so I want to hold off right now before we do that (otherwise srv records are broken too)

**Comment by smarterclayton** [comment]
Will be fixed by https://github.com/openshift/origin/pull/2208
