### ISSUE TITLE
Creating secret with empty string value causes value changes 

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#20875]
After creating a secret with a empty string value I see that the value is changing back and forth between `null` and `''`
```
[jhadvig@dhcp-0-147 origin-web-console]$ oc get secret empty -o yaml
apiVersion: v1
data:
  test: null
kind: Secret
metadata:
  creationTimestamp: 2018-09-05T08:46:32Z
  name: empty
  namespace: jakub
  resourceVersion: "5009685"
  selfLink: /api/v1/namespaces/jakub/secrets/empty
  uid: 308f508a-b0e8-11e8-b920-42010a8e0002
type: Opaque

[jhadvig@dhcp-0-147 origin-web-console]$ oc get secret empty -o yaml
apiVersion: v1
data:
  test: ""
kind: Secret
metadata:
  creationTimestamp: 2018-09-05T08:46:32Z
  name: empty
  namespace: jakub
  resourceVersion: "5009685"
  selfLink: /api/v1/namespaces/jakub/secrets/empty
  uid: 308f508a-b0e8-11e8-b920-42010a8e0002
type: Opaque
```

Weird thing is that the resourceVersion does not change.
Found while working on https://github.com/openshift/console/pull/485
@mfojtik @deads2k thoughts ?

**Comment by mfojtik** [comment]
@jhadvig is this 3.11 ?

**Comment by soltysh** [comment]
@jhadvig additionally how did you create the secret, I just tried 3.11 `oc` with empty file and it always returns empty string.

**Comment by juanvallejo** [comment]
@jhadvig 
> Weird thing is that the resourceVersion does not change.

Sounds like a decoding issue maybe? What version of `oc` are you using?

**Comment by jhadvig** [comment]
OpenShift Master: v3.11.0-alpha.0+c8f4a14-1035
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.0-alpha.0+7bfc41b-12

I've create the secret via web-console

**Comment by juanvallejo** [comment]
@jhadvig Just to confirm, you are not seeing the value as `null` if you fetch the raw object data from the server right? `oc get --raw /api/v1/namespaces/<namespace>/secrets/empty`

**Comment by jhadvig** [comment]
So here is the way how to reproduce:
```
oc create secret generic my-secret --from-literal=key1=
[jhadvig@dhcp-0-147 origin-web-console]$ oc get secret my-secret -o yaml
apiVersion: v1
data:
  key1: ""
kind: Secret
metadata:
  creationTimestamp: 2018-09-06T14:33:55Z
  name: my-secret
  namespace: jakub
  resourceVersion: "5553482"
  selfLink: /api/v1/namespaces/jakub/secrets/my-secret
  uid: e26b6f2a-b1e1-11e8-b920-42010a8e0002
type: Opaque
[jhadvig@dhcp-0-147 origin-web-console]$ oc get secret my-secret -o yaml -w
apiVersion: v1
data:
  key1: null
kind: Secret
metadata:
  creationTimestamp: 2018-09-06T14:33:55Z
  name: my-secret
  namespace: jakub
  resourceVersion: "5553482"
  selfLink: /api/v1/namespaces/jakub/secrets/my-secret
  uid: e26b6f2a-b1e1-11e8-b920-42010a8e0002
type: Opaque
```

so it appears that there is difference when you get and watch the secret with empty value.

**Comment by soltysh** [comment]
There is a chance that when you use watch the processing is different. We don't support server-side printing with watches, yet. But from my local tests I couldn't reproduce it. I've setup up tests running for several minutes and all succeeded.

**Comment by soltysh** [comment]
There is a chance that when you use watch the processing is different. We don't support server-side printing with watches, yet. But from my local tests I couldn't reproduce it. I've setup up tests running for several minutes and all succeeded.

**Comment by juanvallejo** [comment]
@jhadvig We will be fixing `oc get --watch` upstream to deal with Table objects as part of our updates in the next release. I believe this update might fix the de-serialization issue that you're seeing

**Comment by jhadvig** [comment]
@juanvallejo thanks ! Can we keep this issue opened and track it since it's not resolved yet ?

**Comment by juanvallejo** [comment]
@jhadvig 
> Can we keep this issue opened and track it since it's not resolved yet ?

Sure, makes sense to me
