### ISSUE TITLE
Question: how to find nightly build repos or origin/okd?

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#20878]
Where can i get nightly or releases like (https://github.com/openshift/openshift-ansible/releases/tag/openshift-ansible-3.11.0-0.28.0) repos ?

i'd like to try installing cluster from these temporary releases.

**Comment by alexandrevicenzi** [comment]
@debianmaster probably here https://mirror.openshift.com/pub/openshift-v3/clients/ you will find the latest ones, but not sure about nightly builds.

**Comment by debianmaster** [comment]
thanks @alexandrevicenzi
