### ISSUE TITLE
Reverse proxy from a external server causes openshift routes to fail

### ISSUE THREAD

**Issue by rahulbats** [openshift/origin#20884]
hi,
i have a external nginx which i want to reverse proxy to a openshift route 
But openshift route seems to fail because it cant understand the host i think.
I tried setting the host using proxy_set_header, but still did not work.
I am defining the route in nginx conf like this 
```
location /health {
	proxy_set_header Host confirmer-dev.subnotif.oapp-top01.com;
	proxy_pass https://confirmer-dev.subnotif.oapp-top01.com/health;
}	
```	
I am not sure if it is a certificate issue though.
i am really not understanding how to overcome this

**Comment by klzsysy** [comment]
try:

proxy_pass https://confirmer-dev.subnotif.oapp-top01.com/health/;
