### ISSUE TITLE
CustomResourceDefinition delete issuesO

### ISSUE THREAD

**Issue by iocanel** [openshift/origin#20891]
I have a custom resource definiton, which I am trying to delete using the fabric8 java client.
Server responds with 200, though the resource is not getting deleted.

The server should delete the resource or respond with a non 200 code if the request was invalid.

The delete operation seems to work fine when using the `oc` binary.

After debuging and comparing the requests between the two clients the only difference I see is in the `DeleteOptions`.

The fabric8 client sends: 

https://127.0.0.1:8443/apis/networking.istio.io/v1alpha3/namespaces/myproject/gateways/greeting-gateway

    {"apiVersion":"v1","kind":"DeleteOptions","orphanDependents":true}

while the oc client just sends:

   
    {"orphanDependents":false}

I've also tried to use orpanDependants = false, with no luck.
Completely, removing the DeleteOptions from the body does work around the issue.

##### 3.10
[provide output of the `openshift version` or `oc version` command]

oc v3.10.0+maistra-0.1.0-4+9afc0e2
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.10.0+e3465d0-44
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
For anyone interested to reproduce: @geoand has created a reproducer which is available at: https://github.com/geoand/k8s-client-customresource-delete.

**Comment by enj** [comment]
@openshift/sig-master
