### ISSUE TITLE
oc projects --v=5 or --loglevel=5 doesn't show more info

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#20893]
### Version

- oc : oc v3.9.0+191fece

### Use case

According to the `options` command, it is possible to increase the logging level using either the option `--v` or `--loglevel` when we issue a command

```
oc options
The following options can be passed to any command:
...
      --loglevel=0: Set the level of log output (0-10)
      --v=0: Set the level of log output (0-10)
```

### Result

We don't have more logging message using the following commands

```
oc projects --v 5
oc projects --v=5
oc projects --loglevel=5
oc projects --loglevel 5
```

Does the option logging is working ?

**Comment by cmoulliard** [comment]
only level `v>= 6` are working but doc of the command mentions `-v=0: Set the level of log output (0-10)`


```
oc projects --v=5
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
    myproject - My Project
  * odo-test
    openshift
    openshift-infra
    openshift-node
    openshift-web-console

Using project "odo-test" on server "https://192.168.65.6:8443".

oc projects --v=6
I0907 15:15:34.775874   76554 loader.go:357] Config loaded from file /Users/dabou/.kube/config
I0907 15:15:34.786074   76554 round_trippers.go:405] GET https://192.168.65.6:8443/apis/project.openshift.io/v1/projects/odo-test 200 OK in 9 milliseconds
I0907 15:15:34.787287   76554 round_trippers.go:405] GET https://192.168.65.6:8443/apis/project.openshift.io/v1/projects 200 OK in 0 milliseconds
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
    myproject - My Project
  * odo-test
    openshift
    openshift-infra
    openshift-node
    openshift-web-console
```
Can the description of the `oc options` command updated please ?

**Comment by soltysh** [comment]
This is not a bug, each command decides on its own what it logs and at what level. There are a few levels that apply to all commands. These are starting from 6 and up, which are showing you the actual traffic between the client and server. The higher you go the more information you'll get. Up to 9, which shows not only full requests and responses but also curl commands you can use to test specific requests. 
The levels below 5 are interpreted by each command on its own, some are using them and others don't. Looking into [projects.go](https://github.com/openshift/origin/blob/2c3c2a0f5c66dc3a761995ca0cf716b2dd58f75c/pkg/oc/cli/projects/projects.go) it clearly is not using any.

**Comment by cmoulliard** [comment]
You should nevertheless add a comment within the command's output to mention that level info is variable and could only display additional information for higher values

**Comment by soltysh** [comment]
There are quite a lot of details that will go into oc output, I'm going to update our docs with that information in more details.
