### ISSUE TITLE
oc 3.10 cluster up not working on gce 

### ISSUE THREAD

**Issue by javilinux** [openshift/origin#20909]
oc cluster up fail to start timing out waiting for the kube-apiserver to be ready

##### Version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

docker-1.13.1-74.git6e3bb8e.el7.centos.x86_6

##### Steps To Reproduce
1. create instance with gcloud compute instances create occlusterup --image-family centos-7 --image-project centos-cloud --machine-type n1-standard-1 --tags default-allow-http,default-allow-https,openshift-console --zone europe-west1-b
2. Once the instance is ready, install the prerequisites:
yum install docker wget git screen -y
cat << EOF > /etc/docker/daemon.json
{
   "insecure-registries": [
	 "172.30.0.0/16"
   ]
}
EOF
systemctl enable docker
systemctl start docker
systemctl disable firewalld
systemctl stop firewalld
3. Get the latest client:
curl -L --silent -o oc.tar.gz https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz && mkdir /tmp/oc && tar -xvf oc.tar.gz -C /tmp/oc && find /tmp/oc -name "oc" -type f -exec mv {} /usr/bin \; && rm -rf /tmp/oc oc.tar.gz

4. Try oc cluster up:
oc cluster up --public-hostname=$(curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip)

##### Current Result
oc cluster up --public-hostname=$(curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0   1845      0 --:--:-- --:--:-- --:--:--  2000
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Pulling image openshift/origin-control-plane:v3.10
Pulled 2/5 layers, 42% complete
Pulled 3/5 layers, 60% complete
Pulled 4/5 layers, 86% complete
Pulled 5/5 layers, 100% complete
Extracting
Image pull complete
Pulling image openshift/origin-cli:v3.10
Pulled 1/4 layers, 42% complete
Pulled 2/4 layers, 59% complete
Pulled 3/4 layers, 75% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
Pulling image openshift/origin-node:v3.10
Pulled 5/6 layers, 96% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 35.241.254.143 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0907 18:37:08.530966    2040 config.go:42] Running "create-master-config"
I0907 18:37:12.651647    2040 config.go:46] Running "create-node-config"
I0907 18:37:13.964306    2040 flags.go:30] Running "create-kubelet-flags"
I0907 18:37:14.737140    2040 run_kubelet.go:48] Running "start-kubelet"
I0907 18:37:14.912243    2040 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
E0907 18:42:14.919288    2040 run_self_hosted.go:542] API server error: Get https://35.241.254.143:8443/healthz?timeout=32s: dial tcp 35.241.254.143:8443: getsockopt: connection refused ()
Error: timed out waiting for the condition

##### Expected Result
cluster to start

##### Additional Information
If not using --public-hostname the installation goes a bit further but still fails:
[...]
I0907 18:56:52.026288    5329 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
I0907 18:57:17.030821    5329 interface.go:26] Installing "kube-proxy" ...
I0907 18:57:17.031321    5329 interface.go:26] Installing "kube-dns" ...
I0907 18:57:17.031332    5329 interface.go:26] Installing "openshift-apiserver" ...
I0907 18:57:17.031450    5329 apply_template.go:83] Installing "openshift-apiserver"
I0907 18:57:17.033246    5329 apply_template.go:83] Installing "kube-proxy"
I0907 18:57:17.034712    5329 apply_template.go:83] Installing "kube-dns"
I0907 18:57:25.380181    5329 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-apiserver"
Error: timed out waiting for the condition

**Comment by javilinux** [comment]
After adding the following rules:

firewall-cmd --permanent --new-zone dockerc
firewall-cmd --permanent --zone dockerc --add-source 172.17.0.0/16
firewall-cmd --permanent --zone dockerc --add-port 8443/tcp
firewall-cmd --permanent --zone dockerc --add-port 53/udp
firewall-cmd --permanent --zone dockerc --add-port 8053/udp
firewall-cmd --reload

oc cluster up works when no public-hostname is used.

I also tried adding the following rules:
firewall-cmd --permanent --add-port=8443/tcp
firewall-cmd --permanent --add-port=8053/tcp
firewall-cmd --permanent --add-port=53/udp

But still same results for when specifying --public-hostname.

I forgot to comment that with the same gce firewall-rules but using oc 3.9 it works.

**Comment by Jaraill** [comment]
Thanks to you, I've found a way how to run it ~ correctly, except web-console
I've set NO_PROXY OS env variable (it was not obvious for me)  with my public ip, and it started up
