### ISSUE TITLE
Enabling Cluster Metrics fails for v3.10

### ISSUE THREAD

**Issue by preinking** [openshift/origin#20913]
When enabling metrics in v3.10 the deployment scripts select images tagged v3.10.
These images do not exist at all, only v3.10.0-rc.0 is available and v.310 is missing

To complicate matters openshift_metrics_image_version has been removed in v3.10 so a work arround does no longer seem possible

##### Version
openshift v3.10.0+e3465d0-44

##### Steps To Reproduce
openshift_metrics_install_metrics=True

##### Current Result
images tagged v3.10 are not found when enabling metrics

##### Expected Result
images tagged v3.10 should be present since it has been released

**Comment by klzsysy** [comment]
I use:
```
openshift/origin-metrics-cassandra:v3.9
origin-metrics-hawkular-metrics:v3.9
openshift/origin-metrics-heapster:v3.11
```
ignore hawkular-metrics-schema 

Runs well here.

**Comment by klzsysy** [comment]
The image of 3.10 is now updated N times a day, I am desperate, I don't know if I want to update -_-||

**Comment by jwforres** [comment]
Consolidating this into one issue, please follow here https://github.com/openshift/origin/issues/20676
