### ISSUE TITLE
OpenShift docker registry can't pull an image from registry-1.docker.io

### ISSUE THREAD

**Issue by MateuszPrzybyla** [openshift/origin#20915]
When I want to deploy the app from a custom Redis template (https://github.com/openshift/origin/blob/master/examples/db-templates/redis-ephemeral-template.json), the docker registry pod cannot pull Redis docker image from `registry-1.docker.io` and cannot resolve the domain.

##### Version
`oc version` result:
```
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.10.0+e3465d0-44
kubernetes v1.10.0+b81c8f8
```

##### Steps To Reproduce
1. Start the local OpenShift cluster by following steps: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux

2. Deploy a Redis instance and since there is no default Redis template (there are 20 default templates), load it as a JSON template from the URL: https://github.com/openshift/origin/blob/master/examples/db-templates/redis-ephemeral-template.json

##### Current Result
When creating the app from this template, the Redis pod cannot start up and signals a following error:

> Failed to pull image "172.30.1.1:5000/openshift/redis@sha256:0cf7163e0589baab918b1d70cd1ed4c711e2430c618c672b9121f1fd35cf562a": rpc error: code = Unknown desc = Error response from daemon: unknown: unable to pull manifest from docker.io/centos/redis-32-centos7:latest: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

When I'm deploying the app by providing a docker image `openshiftroadshow/parksmap-katacoda:1.0.0` - it's being pulled and deployed successfully.

##### Expected Result
Docker registry pulls Redis image and Redis pod starts up successfully.

##### Additional Information
I have logged into the container published at `172.30.1.1:5000` that hosts a docker registry for the OpenShift and there is clearly a problem with resolving `registry-1.docker.io` domain:
```
bash-4.2$ nslookup registry-1.docker.io
;; connection timed out; no servers could be reached
```
If I specify `8.8.8.8` DNS, everything is fine:
```
bash-4.2$ nslookup registry-1.docker.io 8.8.8.8
Server:     8.8.8.8
Address:    8.8.8.8#53

Non-authoritative answer:
Name:   registry-1.docker.io
Address: 52.22.67.152
....
```
I looked into `/etc/resolv.conf` file and here is its content:
```
bash-4.2$ cat /etc/resolv.conf 
nameserver 172.30.0.2
search default.svc.cluster.local svc.cluster.local cluster.local home
options ndots:5
```

Adding `oc adm diagnostics` output. [diagnostics.txt](https://github.com/openshift/origin/files/2364252/diagnostics.txt)

**Comment by WalterMeier** [comment]
Have this exact problem.
Started recently experimenting with okd for the first time. Running on Centos7.5

```
[root@centos7 ~]# oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.57.80.36:8443
kubernetes v1.11.0+d4cacc0
```

When I manually pull the desired image from dockerhub that is failing in the `docker-regsitry` it gets downloaded fine.
```
[root@centos7 ~]# docker pull openshift/jenkins-2-centos7
Using default tag: latest
latest: Pulling from openshift/jenkins-2-centos7
7dc0dca2b151: Pull complete
89297ec2ab9b: Pull complete
b0ad566301c1: Pull complete
34795a676aa3: Pull complete
dc2ca306d9f0: Pull complete
8ebe9da151bd: Pull complete
75381006f959: Pull complete
8762478ca27d: Pull complete
724d73f4824d: Pull complete
6783bbec8834: Pull complete
bb89c5e06b5c: Pull complete
Digest: sha256:fd3e24d9c26f9632f8c0a884201a68c45bfad7e6b8bd38afa837c8fe11d45d7e
Status: Downloaded newer image for openshift/jenkins-2-centos7:latest
```

**Comment by WalterMeier** [comment]
Update. Fixed it by manualy specifying the DNS for the docker daemon. Found the DNS that works for my host machine and specified the same for docker.

Did it via `/etc/docker/daemon.json`
```json
{
    "insecure-registries" : ["172.30.0.0/16"],
    "dns" : ["10.57.27.34"]
}
```

**Comment by Ethns** [comment]
the issue still exists on:
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0
```
