### ISSUE TITLE
does Route support a Service which has 2 ports?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#2092]
I'm trying 0.5 of OpenShift and I've a service with 2 ports; http on 80 and ssh on 22; I figured the Router would just pick the http 80 port by default when serving requests for http://hostname/. 

Its looking like its load balancing over both ports. 

It looks like you can't currently specify the route ports yet - [this line](https://github.com/openshift/origin/blob/master/pkg/route/api/v1beta3/types.go#L26) is commented out:

```
type RouteSpec struct {
    // Ports are the ports that the user wishes to expose.
    //Ports []RoutePort `json:"ports,omitempty"`
        ...
}
```

Is there a way to get Routes working with Services with more than one port; or do we need to keep services as having only 1 port for now?

**Comment by jimmidyson** [comment]
As an example, got a service (gogs) that exposes both port 80 for http traffic & 22 for ssh traffic. HAProxy config is generated currently like this:

```
backend be_http_default-Gogs-route
 
  mode http
  balance leastconn
  timeout check 5000ms
 
  server default-gogs 172.17.0.43:22 check inter 5000ms
 
  server default-gogs 172.17.0.43:3000 check inter 5000ms
```

Which obviously breaks stuff when routed to ssh service port.

**Comment by pweil-** [comment]
FYI, link to the existing trello card for this work https://trello.com/c/UyLwfTY6/701-route-spec-and-support-mulitple-ports-protocols-routing-future

**Comment by smarterclayton** [comment]
This was implemented with the routePort selector (users can set it to pick a port), but we can't change the default behavior.
