### ISSUE TITLE
Can't create persistent firewalld rules to block incoming traffic (including traffic from pods)

### ISSUE THREAD

**Issue by soukron** [openshift/origin#20938]
I can create persistent rules to block incoming traffic to a node but I cannot block the traffic coming from pods running in that node.
Firewalld chains are a later order than OpenShift so even firewalld default direct rules won't apply.

I need to remark: this is to block also connections from the pods to the host where the pods are running. To block traffic to other nodes I can use OPENSHIFT-ADMIN-OUTPUT-RULES but they don't apply if the destination is the same node where the pods run.

##### Version
3.7+

##### Steps To Reproduce
1. Spin a debug pod 
```
$ oc run busybox --image=busybox:latest --replicas=0
$ oc debug dc/busybox
```
2. Connect to the host where the pod is running
```
$ ssh root@node04
```
3. Add a firewall rule to block outgoing connections to other nodes:
```
# firewall-cmd --permanent --direct --add-chain ipv4 filter OPENSHIFT-ADMIN-OUTPUT-RULES
# firewall-cmd --permanent --direct --add-rule ipv4 filter OPENSHIFT-ADMIN-OUTPUT-RULES  0 -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -j REJECT
# firewall-cmd --reload
```
4. Try to connect from debug pod to different nodes from node04
```
/ # telnet master01 22
telnet: can't connect to remote host: Connection refused
```
5. Try to connect from debug pod to node04
```
/ # telnet node04 22
SSH-2.0-OpenSSH_7.4
```
6. Add a direct rule to firewalld to block incoming connections from any pods:
```
# firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -s <clusterNetworkCIDR> -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -j REJECT
# firewall-cmd --reload
```
7. Try to connect from debug pod to node04
```
/ # telnet node04 22
SSH-2.0-OpenSSH_7.4
```
8. Add a direct rule to firewalld to block incoming connections from any pods using OPENSHIFT-FIREWALL-ALLOW chain:
```
# firewall-cmd --permanent --direct --add-rule ipv4 filter OPENSHIFT-FIREWALL-ALLOW 0 -s <clusterNetworkCIDR> -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -j REJECT
```
9. Try to connect from debug pod to node04
```
/ # telnet node04 22
telnet: can't connect to remote host: Connection refused
```
10. Reload firewall and/or services
```
# firewall-cmd --reload
```
11. Try to connect from debug pod to node04
```
/ # telnet node04 22
SSH-2.0-OpenSSH_7.4
```

##### Current Result
- Traffic blocked in OPENSHIFT-ADMIN-OUTPUT-RULES works as expected in step 4 as it blocks traffic in FORWARD chain. Good. 
- Traffic blocked in OPENSHIFT-ADMIN-OUTPUT-RULES doesn't work to block traffic to node04 as it goes through INPUT chain instead of FORWARD. 
- Traffic blocked with a simple direct rule in INPUT chain is not blocked as shown in step 7 due to the order of rules in INPUT chain. Bad.
- Adding a direct rule to OPENSHIFT-FIREWALL-ALLOW does the job but gets flushed every time OpenShift reloads. Bad

##### Expected Result
Be able to set persistent rules to block incoming traffic including traffic which comes from pods running in the node.

##### Additional Information
Actual firewall rules for INPUT are:
```
-A INPUT -j KUBE-FIREWALL
-A INPUT -m comment --comment "Ensure that non-local NodePort traffic can flow" -j KUBE-NODEPORT-NON-LOCAL
-A INPUT -m comment --comment "firewall overrides" -j OPENSHIFT-FIREWALL-ALLOW
-A INPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes externally-visible service portals" -j KUBE-EXTERNAL-SERVICES
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -j INPUT_direct
-A INPUT -j INPUT_ZONES_SOURCE
-A INPUT -j INPUT_ZONES
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -j REJECT --reject-with icmp-host-prohibited
```
As you can see INPUT_direct is below than OPENSHIFT-FIREWALL-ALLOW.

And, if we take a look to that chain,
```
-A OPENSHIFT-FIREWALL-ALLOW -p udp -m udp --dport 4789 -m comment --comment "VXLAN incoming" -j ACCEPT
-A OPENSHIFT-FIREWALL-ALLOW -i tun0 -m comment --comment "from SDN to localhost" -j ACCEPT
-A OPENSHIFT-FIREWALL-ALLOW -i docker0 -m comment --comment "from docker to localhost" -j ACCEPT
```
It allows all traffic without a method to block any traffic specifically.

##### Fix suggestions:
 - Implement a new chain OPENSHIFT-ADMIN-INPUT-RULES to let administratos filter also input traffic.
 - Consider adding OpenShift rules after INPUT_direct chain.

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by soukron** [comment]
Is this something under consideration? Can you provide guidelines about how to block such traffic without any modification in the code?
