### ISSUE TITLE
Dockerfile Strategy,  unkown flag: chown from ADD --chown

### ISSUE THREAD

**Issue by FedericoPonzi** [openshift/origin#20946]
[provide a description of the issue]

##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.54:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Create a dockerfile with an operation ADD --chown

##### Current Result
Step 4/10 : ADD --chown=gradle . /home/gradle/project
error: build error: Unknown flag: chown

##### Expected Result
Add working as per https://docs.docker.com/engine/reference/builder/#add

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
Openshift uses a level of docker that does not support this syntax.

As a workaround, you can use the ImageOptimization policy which uses an alternate mechanism to build your image (it does not use docker) and which supports the newer syntaxes:

https://github.com/openshift/api/blob/master/build/v1/types.go#L645-L664
https://github.com/openshift/api/blob/master/build/v1/types.go#L696-L703

Or you can update your docker version to one that supports the newer syntax, though that will not be a version of docker that is explicitly supported by openshift.
