### ISSUE TITLE
Allow self-signed certificate for `oc cluster up` (proxy peek/slice)

### ISSUE THREAD

**Issue by gbraad** [openshift/origin#20943]
When using `oc cluster up`, there is no way to specify a CA cert that might be used in a corporate environment for connections that are using a corporate proxy. When peek/slice is enabled (to do TLS re-encyption) often a self-signed certificate might be used. This causes connections to fail.

```
$ oc cluster up --http-proxy http://bigcorp:3128 --https-proxy://bigcorp:3128
```

##### Version
v3.9.0

##### Current Result
TLS connections report a failure for signing.

    W0911 17:28:10.589301   17664 dockerimagelookup.go:233] Docker registry lookup failed: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority

##### Expected Result
Traffic that is re-encrypted should succeed

**Comment by gbraad** [comment]
basically what needs to happen is that the CA cert needs to be 'injected' in the bundle:
```
echo [cert] | sudo tee -a /etc/pki/tls/certs/ca-bundle.crt > /dev/null"
```

**Comment by LalatenduMohanty** [comment]
@deads2k @mfojtik Any comments?

**Comment by jwforres** [comment]
@openshift/sig-master
