### ISSUE TITLE
RFC Add document tell how to change the default password 

### ISSUE THREAD

**Issue by netroby** [openshift/origin#20948]
The getting start document should lead user change their default password as soon as possible, Or the `OKD` will not security.

https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md

**Comment by alexandrevicenzi** [comment]
The `oc cluster <command>` is intended to run on your local machine for **testing** purpose as far as I understand. Thus said, it's not a security problem.

**Comment by jwforres** [comment]
oc cluster up should never be used for production servers, as mentioned it is only for a local test environment. It is set up with the [allow all identity provider](https://docs.okd.io/latest/install_config/configuring_authentication.html#AllowAllPasswordIdentityProvider) which means **any** user and password combination can authenticate and will auto-generate a user for that username. If you don't want this behavior you need to [change to a different identity provider](https://docs.okd.io/latest/install_config/configuring_authentication.html#identity-providers-configuring).
