### ISSUE TITLE
Duplicated fqdn

### ISSUE THREAD

**Issue by roberto-gomez** [openshift/origin#2094]
Hello.

I am testing the OpenShift v3 beta3 and I am using the training documentation (https://github.com/openshift/training/blob/master/beta-3-setup.md).

I have 2 projects. I created the entire Pod-Service-Route example (hello-openshift) with the test-complete.json on each project with the default configuration. The problem I see now is there are two services with the same fqdn and the system doesn't control if the fqdn exists before create it.

**Comment by smarterclayton** [comment]
@pweil-

**Comment by pweil-** [comment]
@roberto-gomez You are correct, currently there is no validation of uniqueness for the fqdn (the Host field) within the route.  We plan on introducing this type of validation as part of the sharding effort which will validation uniqueness within the shard.  If you'd like to keep up with the progress here is the trello card. https://trello.com/c/DtPlixdb/592-8-router-sharding-routing-future

**Comment by roberto-gomez** [comment]
Ok. Thank you for the information.
