### ISSUE TITLE
Proxy settings set in containers do not have lowercase environment variables

### ISSUE THREAD

**Issue by gbraad** [openshift/origin#20942]
After deploying using `oc cluster up`:
```
$ docker exec -it origin /bin/sh
$ env
```

will only show `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`.

    NO_PROXY=localhost,127.0.0.1,172.30.1.1,127.0.0.1,192.168.42.163,localhost,172.30.1.1,172.30.1.2,172.30.0.0/8,192.168.122.228
    HTTPS_PROXY=192.168.42.1:3128                                                                            
    HTTP_PROXY=192.168.42.1:3128      

Due to this, a command like `curl http://gbraad.nl -v --insecure` will fail;

```
sh-4.2# curl http://gbraad.nl -v --insecure           
* About to connect() to gbraad.nl port 80 (#0)
*   Trying 104.28.24.71...   
```

it hangs around, while `curl http://gbraad.nl -v --insecure --proxy $HTTP_PROXY` succeeds.

After setting:

```
export http_proxy=$HTTP_PROXY
export https_proxy=$HTTPS_PROXY
export no_proxy=$NO_PROXY
```

##### Version
v3.9.0

##### Current Result
certain commands and pulls fail to succeed as they use lowercase reference during the build process.

##### Expected Results
`curl` command will succeed

**Comment by jwforres** [comment]
@openshift/sig-containers

**Comment by runcom** [comment]
I'll take a look at this

**Comment by runcom** [comment]
I believe this is not a containers issue. This is the result of building the origin image w/o the lowercase proxy variables. Who's in charge of that image and where's the Dockerfile for it? How's that image built as well?
Can anyone change assignments?
