### ISSUE TITLE
default projects "master, openshift and default"

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#2095]
Hi All, can someone explain me the meaning of "default,master and openshift" project ? 
What are the differences ?

[root@ose1 openshift]# osc get projects
NAME        DISPLAY NAME     STATUS
default                      Active
master                       Active
openshift                    Active

many thanks.

**Comment by derekwaynecarr** [comment]
Let me take a stab at this:

1. The ```default``` project contains artifacts required to run the embedded Kubernetes server.  Most notably, it contains ```Service``` objects that provide information on how to speak back to the Kubernetes server from a Pod.  Events from ```Node``` and other non-namespaced objects currently go in the ```default``` namespace as well.
2. The ```master``` project contains artifacts that describe cluster-wide policy information that spans all other projects.  I think once https://github.com/openshift/origin/pull/2057 lands, this project will no longer be necessary to hold cluster policy information.
3. The ```openshift``` project is intended to hold cluster-wide application templates that users can reference from our web console in any of their projects during the "Create" content flow.

**Comment by roldancer** [comment]
Hi @derekwaynecarr , which users should have delete/create permissions on those projects (default,master,openshift) ?
I'm asking this because we have created a user called oseuser, we didn't assign any special permission on "default", by a mistake this user have deleted all the Replication Controller deployed on "default" project, is this right ?

Many thanks.

**Comment by deads2k** [comment]
By default, users should not have access to delete anything.  How did you create the user and did you run any policy related commands that referenced this user?

**Comment by roldancer** [comment]
Hi @deads2k , before deleting the objects, we were playing with the REST API, so we have executed the following command to bypass the 401 error code when you try to curl ...

openshift admin policy add-role-to-group cluster-admin system:authenticated system:unauthenticated --config=/var/lib/openshift/openshift.local.config/master/admin.kubeconfig"

Does this command give us full access to all projects ?

thanks.

**Comment by deads2k** [comment]
> Does this command give us full access to all projects ?

Yes.  It grants anyone (authenticated or not) full access to every resource in your cluster in any project.
