### ISSUE TITLE
Some fields are absent from oc explain module

### ISSUE THREAD

**Issue by camabeh** [openshift/origin#20952]
Hello,

just a quick question. Is it a bug or oc explain is not intended to provide docs for every field?

```
$ oc explain bc.spec.triggers.imageChangeParams
error: field "imageChangeParams" does not exist
```
```
$ oc explain bc.spec.triggers.type
FIELD: type <string>

DESCRIPTION:
     type is the type of build trigger
```

Source:
https://docs.openshift.com/container-platform/3.9/dev_guide/deployments/basic_deployment_operations.html#image-change-trigger

**Comment by jwforres** [comment]
@camabeh did you find other examples of this?

@openshift/sig-developer-experience since the one referenced is on a BC
@openshift/sig-master for the general question

**Comment by bparees** [comment]
You're running explain against a buildconfig, the docs you referenced are for deploymentconfigs.
