### ISSUE TITLE
oc cluster up fails with timeout on ctl plane

### ISSUE THREAD

**Issue by fabiand** [openshift/origin#20951]
I'm using oc cluster on travis [here](https://travis-ci.com/fabiand/traviskube/jobs/145223185).

Quite often I see teh following timeout:

```
+oc cluster up --skip-registry-check
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0912 11:04:30.930379    7791 flags.go:30] Running "create-kubelet-flags"
I0912 11:04:31.666996    7791 run_kubelet.go:48] Running "start-kubelet"
I0912 11:04:31.874825    7791 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
E0912 11:09:31.876755    7791 run_self_hosted.go:542] API server error: Get https://127.0.0.1:8443/healthz?timeout=32s: dial tcp 127.0.0.1:8443: getsockopt: connection refused ()
Error: timed out waiting for the condition
```
This can often be fixed by re-running the job. Thus in general I think it's not a performance issue.

##### Version
+oc version
oc v3.10.0+dd10d17

##### Steps To Reproduce
1. `+oc cluster up --skip-registry-check --enable=-router,-sample-templates`
2. and the a few cycles of `oc cluster down` and `up`

##### Current Result
See above

##### Expected Result
Reliable down and up.

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by fabiand** [comment]
And again https://travis-ci.com/fabiand/traviskube/jobs/145239710

**Comment by fabiand** [comment]
Likely a dupe of https://github.com/openshift/origin/issues/20929

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by juanvallejo** [comment]
cc @deads2k

**Comment by mshutt** [comment]
Basically, starting after `oc cluster up` and `oc cluster down` is sporadic at best with 3.11 bits.  With 3.10, it always failed.  I've decided to go another route for my testing, so this is largely irrelevant at this point to me.  But ether way....
