### ISSUE TITLE
How to install openshift on an existing K8S cluster?

### ISSUE THREAD

**Issue by chicco785** [openshift/origin#20956]
Not sure this is the best place to ask for that, but assuming you have an already running K8S cluster, how do you install openshit on top or upgrade k8s cluster to openshift?

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by smarterclayton** [comment]
We don't support that today for a few reasons

1. Kubernetes is more than just binaries that run on a machine - specific versions of operating systems, container runtimes, and directories - and we focus OpenShift-the-distribution on providing correct and consistent versions of those as well
2. Some of the OpenShift security integrations run as admission controllers that are not yet externalized
3. The version of Kubernetes OpenShift uses contains patches for backwards compatibility that may regress or break some users upgrading
4. The automated upgrades coming with openshift also upgrade the control plane and nodes, which means installing just some components on top of Kube would lose most of the value.

In the 4.0 version of OpenShift, it should be possible to run some components of OpenShift on top of a stock kube cluster, but for the reasons mentioned above it won't be "OpenShift", it'll just be a subset of features.

**Comment by chicco785** [comment]
So, any way to migrate to openshift from k8s? and what will you lose? i.e. are there services that you can add on top of k8s that cannot work with openshift? (e.g. nginx-ingress, autoscaler, aws-efs, external-dns, ...)

**Comment by esevan** [comment]
@smarterclayton Can I have detail of that feature?

I wonder
1. What components will be running on the existing k8s?
2. What features won't be supported if detached from "openshift"?
