### ISSUE TITLE
OKD Atomic Host: Persistent Volume Permission denied in container

### ISSUE THREAD

**Issue by kgw4it** [openshift/origin#20961]
I set up OKD on CentOS Atomic Host (7.1807 (2018-08-20 10:28:14)) using the ansible installer and this worked without any issues. Then I tried to create a pod that includes a persistent volume that is mounted via a custom flexvolume driver (https://github.com/fstab/cifs). This worked also quite well once I modifed the driver to return
```{ "status": "Success", "message": "The fstab/cifs flexvolume plugin was initialized successfully", "capabilities": { "attach": false, "selinuxRelabel": false } }```.
I had to add `capabilities.selinuxRelabel: false`, otherwise it was complaining about selinux not being allowed to relabel sth.

The problem now is that the user that is running in the container is not allowed to access the mounted volume in the container. This is also the case if I connect to the container as the root user.

Any idea what this could be caused by?

##### Version
oc v3.10.0+39fe4f6-38
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Set up a OKD cluster (3 master nodes, 2 infra nodes, 2 worker nodes) running in containers on CentOS Atomic Host using the ansible installer
2. Deploy the flexvolume driver for cifs
3. Create a persistent volume mounted via the cifs driver
4. Create a pod that mounts the previously created persistent volume
5. Try to access the mount in the container

##### Current Result
Accessing the mount in the container fails with `Permission denied`

##### Expected Result
Accessing the mount in the container is working without a `Permission denied` error

##### Additional Information
I also created a persistenvolume using the `hostpath` type and I also was not able to access the volume in the container.

**Comment by jwforres** [comment]
@openshift/sig-storage
