### ISSUE TITLE
[oc cluster up] no --routing-suffix options for oc cluster up master build

### ISSUE THREAD

**Issue by praveenkumar** [openshift/origin#20984]
I tried to test some changes around oc cluster up from current master and looks like now there is no option for `--routing-suffix`, is it expected?

##### Version

```
$ ./oc version
oc v4.0.0-alpha.0+30739d0-11
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. `oc cluster up --base-dir /var/lib/minishift/base --public-hostname 192.168.42.111 --routing-suffix 192.168.42.111.nip.io`

##### Current Result
Error: unknown flag: --routing-suffix

##### Expected Result
`--routing-suffix` should be present.

cc @mfojtik

**Comment by derekwaynecarr** [comment]
The master branch has been updated to install the following:

1. kubelet (containerized)
1. etcd
1. kube-apiserver, kube-controller-manager, kube-scheduler
1. kube-proxy, kube-dns
1. openshift-service-cert-signer-operator, openshift-apiserver, openshift-controller-manager

All other components not in that list will reappear in `oc cluster up` pending completion of the operator that manages them.  Some of those components above will also transition to being managed by alternative operators.  This means any options or flags that appeared in `oc cluster up` that were specific to what will be configured by that components operator custom resource in the future will not appear as a flag or option in `oc cluster up`.
