### ISSUE TITLE
Bad certificate in Openshift Web Console

### ISSUE THREAD

**Issue by rvm8h** [openshift/origin#20980]
When installing from the tar file Openshift Origin in All-in-One on a local KVM Virtual Machine using centos 7, I got a bad certificate from the browser and a console blank screen. 
but 
Doing the same install on a VM in cloud using public IP address all is fine 

##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.122.245:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. install Openshift Origin 
2. start  oc cluster up --public-hostname=192.168.122.245 --host-data-dir=/home/centos/opens_data

##### Current Result
Blank screen 
##### Expected Result
Openshift Origin console

**Comment by jwforres** [comment]
@openshift/sig-user-interface

**Comment by spadgett** [comment]
> When installing from the tar file Openshift Origin in All-in-One on a local KVM Virtual Machine using centos 7, I got a bad certificate from the browser and a console blank screen.

Does the browser not prompt you to accept the certificate? It won't be trusted by default with cluster up.
