### ISSUE TITLE
local-storage-provisioner failed to create container

### ISSUE THREAD

**Issue by wenchma** [openshift/origin#20994]
[local-storage-provisioner template failed to create container]

##### Version
```
# oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift-1:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
refer to the doc https://github.com/openshift/origin/blob/master/examples/storage-examples/local-examples/README.md

##### Current Result
Events:

5:25:35 PM | Warning | Failed | Error: Error response from daemon: No command specified

##### Expected Result
success to create container

**Comment by jwforres** [comment]
@openshift/sig-storage
