### ISSUE TITLE
Jenkins image openshift/jenkins is deprecated

### ISSUE THREAD

**Issue by lioramilbaum** [openshift/origin#20995]
Deploying Jenkins from the Service Catalog (via minishift) uses the openshift/jenkins image.
According to Dockerhub, this image is [deprecated](https://hub.docker.com/_/jenkins/). 

##### Version
openshift v3.10.0+e3465d0-44

https://github.com/minishift/minishift/issues/2806

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
OCP versions ship the latest LTS available at the time of their release.  For OCP 3.10, that was 2.107, which i assume is the version you're seeing (you put it on your other issue,  don't know why you didn't put that information here).

In any case, what you linked to is not the openshift jenkins image and the openshift jenkins image is not deprecated.  you can find the openshift jenkins image here:

https://hub.docker.com/r/openshift/jenkins-2-centos7/tags/
