### ISSUE TITLE
i/o timeout when trying to install automatioin-broker

### ISSUE THREAD

**Issue by cunningt** [openshift/origin#20991]
[provide a description of the issue]

##### Version
tcunning@ovpn-126-56:~$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8

Mac OS X 

##### Steps To Reproduce
oc cluster up  --routing-suffix=172.17.0.1.nip.io --public-hostname=172.17.0.1.nip.io --enable=service-catalog,router,registry,web-console,persistent-volumes,rhel-imagestreams,automation-service-broker 
(see https://github.com/openshift/ansible-service-broker - these are the suggested options)

##### Current Result

I0914 14:25:05.869731    1044 round_trippers.go:386] curl -k -v -XGET  -H "X-Csrf-Token: 1" https://172.17.0.1.nip.io:8443/oauth/authorize?client_id=openshift-challenging-client&code_challenge=0T22MMC295ijusOONPNCjbS07Ls5_n-Oz71ttjjeCJI&code_challenge_method=S256&redirect_uri=https%3A%2F%2F172.17.0.1.nip.io%3A8443%2Foauth%2Ftoken%2Fimplicit&response_type=code
I0914 14:25:35.874808    1044 round_trippers.go:405] GET https://172.17.0.1.nip.io:8443/oauth/authorize?client_id=openshift-challenging-client&code_challenge=0T22MMC295ijusOONPNCjbS07Ls5_n-Oz71ttjjeCJI&code_challenge_method=S256&redirect_uri=https%3A%2F%2F172.17.0.1.nip.io%3A8443%2Foauth%2Ftoken%2Fimplicit&response_type=code  in 30004 milliseconds
I0914 14:25:35.875145    1044 round_trippers.go:411] Response Headers:
Error: dial tcp 172.17.0.1:8443: i/o timeout

##### Expected Result

openshift starts up

**Comment by cunningt** [comment]
[log.txt](https://github.com/openshift/origin/files/2384532/log.txt)

**Comment by jwforres** [comment]
If you don't include the "automation-service-broker" in the list of things to enable do you still get the error?

@openshift/sig-ansible-service-broker

**Comment by jmontleon** [comment]
The status from the last broker probe is, `"status":{"conditions":[{"type":"Complete","status":"True","lastProbeTime":"2018-09-14T18:25:06Z","lastTransitionTime":"2018-09-14T18:25:06Z"}],"startTime":"2018-09-14T18:22:21Z","completionTime":"2018-09-14T18:25:06Z","succeeded":1}}`

Then we have this indicating the install succeeded, `I0914 14:25:05.504721    1044 interface.go:41] Finished installing "rhel-imagestreams" "openshift-router" "openshift-web-console-operator" "openshift-image-registry" "persistent-volumes" "automation-service-broker" "openshift-service-catalog"

Then interestingly at the end we have `Error: dial tcp 172.17.0.1:8443: i/o timeout`. It would be interesting if this didn't happen just by removing the automation-service-broker option. I wonder if the `--routing-suffix` and `--public-hostname` options could be an issue here?

Not on a Mac, but I had success with the same command line:

```
$ docker pull docker.io/openshift/origin-node:v3.10
Trying to pull repository docker.io/openshift/origin-node ... 
sha256:84b6b6d35a66dfe3b1a8e3d5aab4a3d3a0f62571aa819bc21b898589690f45ba: Pulling from docker.io/openshift/origin-node
Digest: sha256:84b6b6d35a66dfe3b1a8e3d5aab4a3d3a0f62571aa819bc21b898589690f45ba
Status: Image is up to date for docker.io/openshift/origin-node:v3.10

$ docker cp $(docker create docker.io/openshift/origin-node:v3.10):/usr/bin/oc ~/bin/oc 

$ oc version
oc v3.10.0+e3465d0-44
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

$ oc cluster up --routing-suffix=172.17.0.1.nip.io --public-hostname=172.17.0.1.nip.io --enable=service-catalog,router,registry,web-console,persistent-volumes,rhel-imagestreams,automation-service-broker
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0918 08:58:58.074738   18236 config.go:42] Running "create-master-config"
I0918 08:59:00.562331   18236 config.go:46] Running "create-node-config"
I0918 08:59:01.892349   18236 flags.go:30] Running "create-kubelet-flags"
I0918 08:59:02.769140   18236 run_kubelet.go:48] Running "start-kubelet"
I0918 08:59:03.332169   18236 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
I0918 08:59:29.337124   18236 interface.go:26] Installing "kube-proxy" ...
I0918 08:59:29.337164   18236 interface.go:26] Installing "kube-dns" ...
I0918 08:59:29.337184   18236 interface.go:26] Installing "openshift-apiserver" ...
I0918 08:59:29.337234   18236 apply_template.go:83] Installing "kube-proxy"
I0918 08:59:29.337275   18236 apply_template.go:83] Installing "openshift-apiserver"
I0918 08:59:29.337281   18236 apply_template.go:83] Installing "kube-dns"
I0918 08:59:31.514120   18236 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-apiserver"
I0918 09:00:20.558409   18236 run_self_hosted.go:224] openshift-apiserver available
I0918 09:00:20.558451   18236 interface.go:26] Installing "openshift-controller-manager" ...
I0918 09:00:20.558479   18236 apply_template.go:83] Installing "openshift-controller-manager"
I0918 09:00:22.832409   18236 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding rhel-imagestreams ...
Adding automation-service-broker ...
Adding service-catalog ...
Adding registry ...
Adding router ...
Adding persistent-volumes ...
Adding web-console ...
I0918 09:00:22.858449   18236 interface.go:26] Installing "rhel-imagestreams" ...
I0918 09:00:22.858476   18236 interface.go:26] Installing "automation-service-broker" ...
I0918 09:00:22.858492   18236 interface.go:26] Installing "openshift-service-catalog" ...
I0918 09:00:22.858508   18236 interface.go:26] Installing "openshift-image-registry" ...
I0918 09:00:22.858531   18236 interface.go:26] Installing "openshift-router" ...
I0918 09:00:22.858546   18236 interface.go:26] Installing "persistent-volumes" ...
I0918 09:00:22.858562   18236 interface.go:26] Installing "openshift-web-console-operator" ...
I0918 09:00:22.858628   18236 apply_list.go:68] Installing "rhel-imagestreams"
I0918 09:00:22.859296   18236 apply_template.go:83] Installing "openshift-web-console-operator"
I0918 09:00:22.863515   18236 apply_template.go:83] Installing "automation-service-broker"
I0918 09:00:22.911107   18236 apply_template.go:83] Installing "service-catalog"
I0918 09:02:42.576445   18236 interface.go:41] Finished installing "rhel-imagestreams" "automation-service-broker" "openshift-service-catalog" "openshift-image-registry" "openshift-router" "persistent-volumes" "openshift-web-console-operator"
Login to server ...
Creating initial project "myproject" ...
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://172.17.0.1.nip.io:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin
```

**Comment by cunningt** [comment]
I've tried on two different Macs now and can reproduce on both.     What I am seeing though is that if you remove the routing-suffix and public-hostname, cluster starts up cleanly, although I am not sure whether the removal of routing-suffix/public-hostname affect the operation of the broker.

**Comment by jmontleon** [comment]
They shouldn't be necessary for the broker to function. I think @johnkim76 mentioned he was able to get oc cluster up using the same binary version you listed to work on his Mac.

I'm not sure if this comes down to configuration of the docker daemon on Mac, etc. I don't personally have a Mac where I am able to dig into Mac specifics further and I don't understand why the error, `Error: dial tcp 172.17.0.1:8443: i/o timeout` would happen with the broker vs without. This is outside of and after the automation broker apb has completed. At that point I believe it should be common code.

**Comment by jmontleon** [comment]
We were able to reproduce this even without enabling the automation-service-broker. It seems it's something to do with the --routing-suffix or --public-hostname options on mac.

```
$ time ./oc cluster up --routing-suffix=172.17.0.1.nip.io --public-hostname=172.17.0.1.nip.io --enable=service-catalog,router,registry,web-console,persistent-volumes,rhel-imagestreams
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking prerequisites for port forwarding ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0918 12:52:00.394183   82228 config.go:42] Running "create-master-config"
I0918 12:52:03.260974   82228 config.go:46] Running "create-node-config"
I0918 12:52:05.089378   82228 flags.go:30] Running "create-kubelet-flags"
I0918 12:52:06.342568   82228 run_kubelet.go:48] Running "start-kubelet"
I0918 12:52:06.878599   82228 run_self_hosted.go:172] Waiting for the kube-apiserver to be ready ...
I0918 12:52:29.231458   82228 interface.go:26] Installing "kube-proxy" ...
I0918 12:52:29.231488   82228 interface.go:26] Installing "kube-dns" ...
I0918 12:52:29.231498   82228 interface.go:26] Installing "openshift-apiserver" ...
I0918 12:52:29.231820   82228 apply_template.go:83] Installing "kube-proxy"
I0918 12:52:29.232114   82228 apply_template.go:83] Installing "kube-dns"
I0918 12:52:29.232147   82228 apply_template.go:83] Installing "openshift-apiserver"
I0918 12:52:31.610223   82228 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-apiserver"
I0918 12:53:07.683125   82228 run_self_hosted.go:224] openshift-apiserver available
I0918 12:53:07.683155   82228 interface.go:26] Installing "openshift-controller-manager" ...
I0918 12:53:07.683173   82228 apply_template.go:83] Installing "openshift-controller-manager"
I0918 12:53:10.144182   82228 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding registry ...
Adding service-catalog ...
Adding rhel-imagestreams ...
Adding router ...
Adding persistent-volumes ...
Adding web-console ...
I0918 12:53:10.243222   82228 interface.go:26] Installing "openshift-image-registry" ...
I0918 12:53:10.243244   82228 interface.go:26] Installing "openshift-service-catalog" ...
I0918 12:53:10.243254   82228 interface.go:26] Installing "rhel-imagestreams" ...
I0918 12:53:10.243264   82228 interface.go:26] Installing "openshift-router" ...
I0918 12:53:10.243273   82228 interface.go:26] Installing "persistent-volumes" ...
I0918 12:53:10.243282   82228 interface.go:26] Installing "openshift-web-console-operator" ...
I0918 12:53:10.243373   82228 apply_list.go:68] Installing "rhel-imagestreams"
I0918 12:53:10.247077   82228 apply_template.go:83] Installing "openshift-web-console-operator"
I0918 12:53:10.334522   82228 apply_template.go:83] Installing "service-catalog"
I0918 12:53:29.653111   82228 interface.go:41] Finished installing "openshift-image-registry" "openshift-service-catalog" "rhel-imagestreams" "openshift-router" "persistent-volumes" "openshift-web-console-operator"
Login to server ...
Error: dial tcp 172.17.0.1:8443: i/o timeout
```

**Comment by jmontleon** [comment]
It might just be that the address 172.17.0.1(.nip.io) will not work on Mac. The docker daemon runs in a VM with this address but it does not seem accessible to the host system.

**Comment by jwmatthews** [comment]
Running on mac with the latest oc binary from 3.10 release on github.

$ ./oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

If I use --routing-suffix and --public-hostname, oc cluster up fails with the i/o timeout.

If I run the below without --routing-suffix/--public-hostname the cluster comes up

This works on mac:
./oc cluster up --enable=service-catalog,router,registry,web-console,persistent-volumes,rhel-imagestreams,automation-service-broker


For my mac, the mac host has no route entry to handle 172.17.0.1, 172.17.0.1 is an IP of an interface inside of the docker VM and it does not appear to be exposed outside of the docker VM.


When I drop --routing-suffix/--public-hostname I see the k8s api is set to 127.0.0.1:8443 and this works as a 'socat' process is forwarding traffic to the docker container

socat -s TCP-L:8443,reuseaddr,fork,backlog=20,bind=127.0.0.1 SYSTEM:"docker exec -i origin socat - TCP\:localhost\:8443"
