### ISSUE TITLE
openshift should support multiple localization language（chinese, japanese, korean,etc）on web console

### ISSUE THREAD

**Issue by b43646** [openshift/origin#20996]
openshift support multiple localization language（chinese, japanese, korean,etc） to enhance user experience.

Do you have any plan about it ?

@spadgett  @jwforres @deads2k

**Comment by jwforres** [comment]
@openshift/sig-user-interface

**Comment by spadgett** [comment]
We still have a story in our backlog. See #5831 for some background.

We have not translated the console yet in part because we are in the midst of switching frontend frameworks from AngularJS 1.x to React.

/kind enhancement
