### ISSUE TITLE
Make build errors more specific/actionable

### ISSUE THREAD

**Issue by muff1nman** [openshift/origin#21002]
##### Version
3.9.41

##### Steps To Reproduce
1. Start a build that will get OOMkilled
2. Wait for Build to fail

##### Current Result
On the bulids list - notice "Generic build failed" but no further details/call to action

##### Expected Result
The same exit status as the Pod ("OOMKilled") or at least a more descriptive/actionable error message

##### Additional Information
This is a very frequent pain point with folks that are new to openshift. They create a resource hungry build, see it failed, but do not know where to go next. The real details are hidden in the associated pod details/logs/events page, but there is no hint to go look there. Perhaps adding a link to the associated pod would be helpful?

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
This has been fixed in 3.11 to report oom killed information.

https://bugzilla.redhat.com/show_bug.cgi?id=1596440
