### ISSUE TITLE
Secondary sidebar selection not highlighted

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2100]
The selected "Browse ..." sidebar link is not highlighted, making it less obvious what's selected.

@sg00dwin fyi

![no-highlight](https://cloud.githubusercontent.com/assets/1167259/7498430/c10327dc-f3ee-11e4-9294-6a231c473dc9.png)

**Comment by sg00dwin** [comment]
Fix merged - current location is represented in secondary sidenav

![screen shot 2015-06-09 at 1 43 41 pm](https://cloud.githubusercontent.com/assets/1874151/8065225/1921c08e-0eae-11e5-9d8d-4280915d976f.png)
