### ISSUE TITLE
"oc get triggers" should exist

### ISSUE THREAD

**Issue by galderz** [openshift/origin#21016]
If there is `oc set triggers...`, why isn't there a `oc get triggers...` to retrieve triggers associated with a a resource?

In 3.10 this fails:

```
$ oc get triggers
error: the server doesn't have a resource type "triggers"
```

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by mfojtik** [comment]
`oc get` is reserved for a GET operation for resources. Triggers are not resources, just fields on deployment configs. `oc set triggers` will by default print the list of triggers.

**Comment by galderz** [comment]
Calling `oc set...` to print some values just does not make sense
