### ISSUE TITLE
[oc cluster up] components are failed to apply if used specific version of images during cluster up

### ISSUE THREAD

**Issue by praveenkumar** [openshift/origin#21011]
Components are failed to apply if used a specific version for images during the oc cluster up.

##### Version
```
$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
```
$ oc cluster up --image 'openshift/origin-${component}:v3.10.0' 
[...]
The server is accessible via web console at:
    https://127.0.0.1:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

$ oc cluster add service-catalog
I0917 06:01:41.692467    8547 interface.go:26] Installing "openshift-service-catalog" ...
I0917 06:01:41.768154    8547 apply_template.go:83] Installing "service-catalog"
E0917 06:02:11.794159    8547 interface.go:34] Failed to install "openshift-service-catalog": failed to install "service-catalog": cannot create container using image openshift/origin-cli:v3.10; caused by: cannot create container using image openshift/origin-cli:v3.10
I0917 06:02:11.794189    8547 interface.go:41] Finished installing "openshift-service-catalog"
Error: failed to install "service-catalog": cannot create container using image openshift/origin-cli:v3.10; caused by: cannot create container using image openshift/origin-cli:v3.10
```
##### Current Result
Not able to apply the component.

##### Expected Result
Should able to apply the component.

##### Additional Information
Looks like if you have `openshift/origin-cli:v3.10.0` then it not taken into consideration during the `oc cluster add` but if you tag it to `openshift/origin-cli:v3.10` then it works as expected so looks like something is not honoring the images tags.

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by deads2k** [comment]
> Looks like if you have `openshift/origin-cli:v3.10.0` then it not taken into consideration during the `oc cluster add` but if you tag it to `openshift/origin-cli:v3.10` then it works as expected so looks like something is not honoring the images tags.

The --image flag isn't saved anywhere.  You specify it on the commands you want to use it for, so you'll need to specify it for `oc cluster add` if you want to use specific images for `oc cluster add`.
