### ISSUE TITLE
Openshift avahi-deamon Inside Container (mDNS)

### ISSUE THREAD

**Issue by flipkill1985** [openshift/origin#21034]
Hello,

ist there a solution to run avahi-deamon and get the Traffic Inside the Container?
Did not work with Stock Openshift Utils right?

best regards Jan

**Comment by jwforres** [comment]
@openshift/sig-network-edge

**Comment by flipkill1985** [comment]
Unfortunately, it still does not work in openshift the possibility to use the docker functionality "--net = host"?
