### ISSUE TITLE
Documentation seems too centric to RHEL and Fedora

### ISSUE THREAD

**Issue by sr229** [openshift/origin#21032]
While it is possible to run OpenShift on other OSes, the documentation seems to be written for RHEL and Fedora in mind. Given this state, it will be hard for some people to use OKD since its a very RHEL/Fedora-centric setup and installation documentation.

So areas to improve should be as follows:

- Cover some popular OS cases aside from Fedora/RHEL, (Debian and Ubuntu seems to be popular).
- Add some notices on some methods only tested in Fedora/RHEL since distros have different methods of compilation strategies and package selection (Like Setting up a Cluster Section for `oc`).

I'll be open to improve the documentation by myself given I can get the server to work on other OSes, which is coming later. Anyone is free to do this task with me (if I get to it) should you wish to.

**Comment by jwforres** [comment]
Are the concerns primarily around docs within the origin repo itself, or the ones on https://docs.okd.io/
If its the latter, then this issue should really be opened in https://github.com/openshift/openshift-docs/issues

**Comment by sr229** [comment]
Mirroring issue over there, thanks for informing me
