### ISSUE TITLE
oc delete project returns Forbidden the when project does not exists 

### ISSUE THREAD

**Issue by diegolovison** [openshift/origin#21045]
`oc delete project my_custom_project` returns Forbidden the when project does not exists 

##### Version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.10.0+e3465d0-44
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. oc cluster up
2. oc login -u developer -p developer
2. oc delete project my_custom_project

##### Current Result
Error from server (Forbidden): projects.project.openshift.io "my_custom_project" is forbidden: User "developer" cannot delete projects.project.openshift.io in the namespace "my_custom_project": User "developer" cannot delete projects.project.openshift.io in project "my_custom_project"

##### Expected Result
I different error message like: Project "my_custom_project" not found

**Comment by alexandrevicenzi** [comment]
I can't reproduce.

```
$ oc delete project my_custom_project
Error from server (NotFound): namespaces "my_custom_project" not found
```

oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
openshift v3.10.0+e3465d0-44

**Comment by diegolovison** [comment]
Hi @alexandrevicenzi please let me know what kind of information do you need from our side.

Keep in mind that you need to remove a project that does not exist.

**Comment by alexandrevicenzi** [comment]
@diegolovison I followed your steps and couldn't reproduce. For me, it works as expected.

Can you reproduce in another machine? btw, I'm using Fedora 28 and Docker 1.13.

**Comment by diegolovison** [comment]
I am using a Mac
```
$ docker -v
Docker version 17.09.1-ce, build 19e2cf6
```

but we were able to reproduce in ****.openshift:
```
$ oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://********.openshift.com:443
openshift v3.9.31
kubernetes v1.9.1+a0ce1bc657
```

**Comment by alexandrevicenzi** [comment]
@diegolovison I'm also able to reproduce on openshift.com.

```
$ oc delete project my_custom_project

Error from server (Forbidden): projects.project.openshift.io "my_custom_project" is forbidden: User "xxx@gmail.com" cannot delete projects.project.openshift.io in the namespace "my_custom_project": no RBAC policy matched
```

```
$ oc version

oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxxx.openshift.com:443
openshift v3.11.0-0.21.0
kubernetes v1.11.0+d4cacc0
```

**Comment by enj** [comment]
This is the expected behavior.  You have to pass authorization before the API request is processed by the underlying storage (which is what would respond with the `NotFound`).

```
$ oc login -u system:admin
Logged into "https://192.168.43.69:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default
    kube-public
    kube-system
    openshift
    openshift-infra
    openshift-node

Using project "default".

$ oc delete project does-not-exist
Error from server (NotFound): namespaces "does-not-exist" not found

$ oc login -u developer -p p
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

$ oc delete project does-not-exist
Error from server (Forbidden): projects.project.openshift.io "does-not-exist" is forbidden: User "developer" cannot delete projects.project.openshift.io in the namespace "does-not-exist": no RBAC policy matched
```

**Comment by diegolovison** [comment]
For the step `oc delete project does-not-exist`, should we receive `Error from server (NotFound)` instead of `Error from server (Forbidden)`?

**Comment by enj** [comment]
> For the step `oc delete project does-not-exist`, should we receive `Error from server (NotFound)` instead of `Error from server (Forbidden)`?

If you have access to delete the project (for example, if you are `system:admin` which has access to do everything) you will see `NotFound`, otherwise you will see `Forbidden`.
