### ISSUE TITLE
system:admin can't login

### ISSUE THREAD

**Issue by damozhiying** [openshift/origin#21055]
openshift start   standalone
![image](https://user-images.githubusercontent.com/10277950/45808420-580da280-bcf8-11e8-868b-2009c22f2801.png)

how to login with the system:admin

**Comment by alexandrevicenzi** [comment]
What's the output of `oc version`?

**Comment by damozhiying** [comment]
openshift-origin-server-v3.7.1-ab0f056-linux-64bit

**Comment by damozhiying** [comment]
@alexandrevicenzi openshift-origin-server-v3.7.1-ab0f056-linux-64bit

**Comment by enj** [comment]
See https://github.com/openshift/origin/issues/21079#issuecomment-423981132
