### ISSUE TITLE
Local Volumes "raw block devices"

### ISSUE THREAD

**Issue by flipkill1985** [openshift/origin#21052]
[Local Volumes "raw block devices"]

##### Version
[oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://console.openshift.mohs-home.de:8443
openshift v3.10.0+e3465d0-44
kubernetes v1.10.0+b81c8f8
]

##### Steps To Reproduce
I tried this Manuel: https://docs.openshift.com/container-platform/3.10/install_config/configuring_local.html#local-volume-raw-block-devices

But get that Error:

I0919 22:59:47.366550       1 common.go:255] StorageClass "block-devices" configured with MountDir "/mnt/local-storage/block-devices", HostDir "/mnt/local-storage/block-devices", BlockCleanerCommand ["/scripts/quick_reset.sh"]

  | I0919 22:59:47.366745       1 main.go:42] Configuration parsing has been completed, ready to run...
  | I0919 22:59:47.367761       1 common.go:315] Creating client using in-cluster config
  | I0919 22:59:47.411252       1 main.go:52] Starting controller
  | I0919 22:59:47.411320       1 controller.go:42] Initializing volume cache
  | I0919 22:59:47.419333       1 populator.go:85] Starting Informer controller
  | I0919 22:59:47.419611       1 populator.go:89] Waiting for Informer initial sync
  | I0919 22:59:48.429104       1 controller.go:72] Controller started
  | E0919 22:59:48.429491       1 discovery.go:149] Error reading directory: open /mnt/local-storage/block-devices: no such file or directory
  | E0919 22:59:58.431219       1 discovery.go:149] Error reading directory: open /mnt/local-storage/block-devices: no such file or directory
  | E0919 23:00:08.433138       1 discovery.go:149] Error reading directory: open /mnt/local-storage/block-devices: no such file or directory

##### Current Result

I0919 22:59:47.366550       1 common.go:255] StorageClass "block-devices" configured with MountDir "/mnt/local-storage/block-devices", HostDir "/mnt/local-storage/block-devices", BlockCleanerCommand ["/scripts/quick_reset.sh"]

  | I0919 22:59:47.366745       1 main.go:42] Configuration parsing has been completed, ready to run...
  | I0919 22:59:47.367761       1 common.go:315] Creating client using in-cluster config
  | I0919 22:59:47.411252       1 main.go:52] Starting controller
  | I0919 22:59:47.411320       1 controller.go:42] Initializing volume cache
  | I0919 22:59:47.419333       1 populator.go:85] Starting Informer controller
  | I0919 22:59:47.419611       1 populator.go:89] Waiting for Informer initial sync
  | I0919 22:59:48.429104       1 controller.go:72] Controller started
  | E0919 22:59:48.429491       1 discovery.go:149] Error reading directory: open /mnt/local-storage/block-devices: no such file or directory
  | E0919 22:59:58.431219       1 discovery.go:149] Error reading directory: open /mnt/local-storage/block-devices: no such file or directory
  | E0919 23:00:08.433138       1 discovery.go:149] Error reading directory: open /mnt/local-storage/block-devices: no such file or directory

**Comment by jwforres** [comment]
@openshift/sig-storage
