### ISSUE TITLE
Nginx Router doesn't work correctly with default docker registry

### ISSUE THREAD

**Issue by avenging** [openshift/origin#21067]
**Describe the bug**
The default Nginx router configuration template doesn't work correctly with the default container registry installed in Openshift/Minishift.

The Nginx router configuration generated is causing the registry to send a re-direct to a port that is not open.

**To reproduce**
This example uses Minishift, but is guaranteed not to work in an oc cluster up set-up as well.
Follow the docs to:
Start up a Minishift instance
Build the nginx-router and deploy it replacing the default HAProxy router.

Then:
Install docker and the oc binary on a centos7 server separate to Minishift then try and login to the docker registry in the Minishift instance.
For instance a Minishift instance running in Virtualbox with IP 172.16.1.103:
1. yum -y install docker wget
2. systemctl start docker
3. wget https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-server-v3.10.0-dd10d17-linux-64bit.tar.gz
4. tar zxf openshift-origin-server-v3.10.0-dd10d17-linux-64bit.tar.gz
5. cp openshift-origin-server-v3.10.0-dd10d17-linux-64bit/oc /usr/bin
6. oc login -u developer https://172.16.1.103:8443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y
7. Enter user password (typically anything in Minishift)
8. Add the Minishift docker registry as an insecure registry
[root@centos-server ~]# cat <<END > /etc/docker/daemon.json
{
  "insecure-registries" : ["docker-registry-default.172.16.1.103.nip.io"]
}
END
9. Attempt to login to the docker registry:
[root@centos-server ~]# docker login -u developer -p $(oc whoami -t) docker-registry-default.172.16.1.103.nip.io
Error response from daemon: Get https://docker-registry-default.172.16.1.103.nip.io/v2/: Get https://docker-registry-default.172.16.1.103.nip.io:10444/openshift/token?account=developer&client_id=docker&offline_token=true: dial tcp 172.16.1.103:10444: getsockopt: connection refused

**Expected behavior**
Registry login should succeed as it does with the HAProxy router:
[root@centos-server ~]# docker login -u developer -p $(oc whoami -t) docker-registry-default.172.16.1.103.nip.io
Login Succeeded

**Your environment**
* Minishift version
$ ./minishift version
minishift v1.22.0+7163416
Running Openshift 3.9
OC Version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.16.1.103:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

* NGINX router version
Latest from master branch of origin repo.

**Additional context**
Removing:
proxy_set_header X-Forwarded-Port $server_port;
From the Nginx configuration fixes the problem.

**Comment by jwforres** [comment]
@openshift/sig-network-edge @openshift/sig-developer-experience

**Comment by bparees** [comment]
this seems to be wholly a nginx router configuration issue, removing devex.
