### ISSUE TITLE
Glusterfind with GlusterFS in converged mode does not work

### ISSUE THREAD

**Issue by jocelynthode** [openshift/origin#21068]
##### Version
```
openshift v3.10.0+e3465d0-44
kubernetes v1.10.0+b81c8f8
```

##### Steps To Reproduce
1. Install glusterfs in converged mode
2. try to run glusterfind create from one of the glusterfs pod

##### Current Result
Glusterfind tries to connect to the host and fails since key are created in /root in the pod. Even when mounting /root into the pod it fails as glusterfs is not present on the host

##### Expected Result
Be able to run glusterfind to backup files in the cluster

##### Additional Information
If it is intended to not be able to run glusterfind from the converged mode, I think it should be specified in the documentation as it can be a big problem in case people want to backup their volumes.

Otherwise is there a work around for this issue ?

**Comment by jwforres** [comment]
@openshift/sig-storage
