### ISSUE TITLE
Install multi DC cassandra on two separate Openshift Origin clusters to get HA and DR

### ISSUE THREAD

**Issue by Natarajan77** [openshift/origin#21069]
[provide a description of the issue]

We are in the process of installing Cassandra as multi DC on Openshift origin and running into challenges.
 
So we have two openshift clusters which are separated by Datacenter
 
Openshift Origin AB hosted in datacenter ELC
 
Openshift Origin CD hosted in datacenter CLC
 
Going to install cassandra cluster on AB and CD. Both cassandra cluster on AB and CD should be able to talk with each other. So that we get HA and DR. 
 
Current challenge cassandra cluster in AB and CD they are not able to talk with each other.
 
Cassandra broadcasts on pod ip and unfortunately pod ips are accessible only in local origin cluster not across remote. How to make the pod ip accessible across open shift origin clusters? 

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jwforres** [comment]
@openshift/sig-network-edge for the networking questions, and @openshift/sig-hawkular-metrics since they are familiar with cassandra

**Comment by jsanda** [comment]
The upstream Apache Cassandra does provide multi-DC support. We never implemented it though for OpenShift. There are no plans to do so now since Hawkular Metrics and Cassandra have been deprecated in 3.11.
