### ISSUE TITLE
Unable to create an openshift multi-node cluster - openshift-node fails to start

### ISSUE THREAD

**Issue by ramr** [openshift/origin#2108]
Tried launching an OpenShift multi-node cluster and the minions fail with errors stating Docker 1.6 is required. That rpm doesn't exist on Fedora 20. 

Tried to delete the current Fedora 20 vagrant box/image and tried to launch a new cluster 
``` export OPENSHIFT_DEV_CLUSTER=1;  vagrant up``` 

but it still launches a F20 box and that doesn't have docker 1.6. 

Looks like we probably need a new Fedora 21 image at  https://mirror.openshift.com/pub/vagrant/boxes/openshift3/  and modify the Vagrantfile to use that new image.

**Workaround:**
 Launch a Fedora 20 based cluster that fails to startup.
 Manually update the 2 minions to Fedora 21 (https://fedoraproject.org/wiki/Upgrading_Fedora_using_yum)
 Restart the openshift-node service on the 2 minions.   

/CC @pweil-  and @pravisankar  as they ran into this issue as well

Edit:  Updated workaround.

**Comment by ncdc** [comment]
You can install the candidate 1.6 RPMs for F20 from here: http://koji.fedoraproject.org/koji/buildinfo?buildID=635273.

**Comment by liggitt** [comment]
Might be fixed by #2149

**Comment by rajatchopra** [comment]
This issue should be closed now. A similar situation faced by QE has been fixed and marked verified.
https://bugzilla.redhat.com/show_bug.cgi?id=1221019
