### ISSUE TITLE
Can't set a dashboardURL from template service broker

### ISSUE THREAD

**Issue by aidenkeating** [openshift/origin#21082]
Currently, when provisioning using the template service broker, you cannot specify a dashboardURL. It is hardcoded to null. 

https://github.com/openshift/origin/blob/master/pkg/templateservicebroker/servicebroker/provision.go#L393

It would be nice if it were possible to set a Route name, or directly specify a `dashboardURL` in the template.

##### Version
```
openshift v3.10.34
kubernetes v1.10.0+b81c8f8
```

##### Steps To Reproduce
1. Take a template with a route (e.g. https://github.com/integr8ly/installation/blob/68245364ae623806379920a0768d0890ff173f97/evals/roles/walkthroughs/templates/crud_spboot_example.yml), try to add a dashboardURL
##### Current Result
There's no option to set a `dashboardURL`

##### Expected Result
There's some way to specify a `dashboardURL`

**Comment by jwforres** [comment]
@openshift/sig-ansible-service-broker
