### ISSUE TITLE
Intra-cluster authorization broken after upgrade to 3.10

### ISSUE THREAD

**Issue by AlbertoPeon** [openshift/origin#21094]
This is a follow-up of https://github.com/openshift/origin/issues/21066

We are trying to find what is wrong with our apiserver after the automated upgrade to 3.10.

What we see is that the apiserver fails to start with plenty of errors in the form of:

```shell
I0925 10:00:39.656452       1 rbac.go:118] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "list" resource "serviceaccounts" cluster-wide
I0925 10:00:39.656531       1 authorization.go:60] Forbidden: "/api/v1/serviceaccounts?limit=500&resourceVersion=0", Reason: "User \"system:anonymous\" cannot list all serviceaccounts in the cluster"
I0925 10:00:39.656596       1 wrap.go:42] GET /api/v1/serviceaccounts?limit=500&resourceVersion=0: (202.398µs) 403 [[openshift/v1.10.0+b81c8f8 (linux/amd64) kubernetes/b81c8f8] XXX.XXX.XXX.XXX:40870]
I0925 10:00:39.656760       1 rbac.go:118] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "list" resource "imagestreams.image.openshift.io" cluster-wide
I0925 10:00:39.656820       1 authorization.go:60] Forbidden: "/apis/image.openshift.io/v1/imagestreams?limit=500&resourceVersion=0", Reason: "User \"system:anonymous\" cannot list all imagestreams.image.openshift.io in the cluster"
I0925 10:00:39.656871       1 wrap.go:42] GET /apis/image.openshift.io/v1/imagestreams?limit=500&resourceVersion=0: (172.955µs) 403 [[openshift/v1.10.0+b81c8f8 (linux/amd64) kubernetes/b81c8f8] XXX.XXX.XXX.XXX:40870]
I0925 10:00:39.657042       1 rbac.go:118] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "list" resource "clusterroles.rbac.authorization.k8s.io" cluster-wide
```
The full log is attached - [apiserver.log](https://github.com/openshift/origin/files/2414780/apiserver.log)

The same happens in both of our masters. 

From our side, all certificates look fine - they are not expired, in fact they have not been modified by the upgrade. 

To us it seems like a problem with the RBAC authorization. Even operations that do not require any kind of credentials fail in the same way, see for instance the check for the health endpoint:

```shell
# curl -k -v https://127.0.0.1:8443/healthz
* About to connect() to 127.0.0.1 port 8443 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
* Server certificate:
*       subject: CN=128.142.243.75
*       start date: Mar 26 12:07:18 2018 GMT
*       expire date: Mar 25 12:07:19 2020 GMT
*       common name: 128.142.243.75
*       issuer: CN=openshift-signer
> GET /healthz HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8443
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Cache-Control: no-store
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< Date: Tue, 25 Sep 2018 10:22:55 GMT
< Content-Length: 282
<
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/healthz\": User \"system:anonymous\" cannot \"get\" on \"/healthz\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
* Connection #0 to host 127.0.0.1 left intact
``` 

Do you have any idea what we can do to recover our apiserver? 

We have already tried to restore an older (from before the upgrade) etcd backup but it has not changed anything.

##### Version
```
oc v3.10.0-cern.0+cdc91b4
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

The openshift RPM is our own build based on the release 1.10 branch.

The apiserver runs in a system container using the upstream image (ref. `openshift/origin-control-plane:v3.10.0`) as set by openshift-ansible.

**Comment by enj** [comment]
> The openshift RPM is our own build based on the release 1.10 branch.

Can you reproduce using an official RPM?

---

Aside from that, are able to perform actions as `system:admin`?

For example, does this work correctly:

```bash
export KUBECONFIG=.../master/admin.kubeconfig
oc get --raw '/healthz'
oc get users '~' -o yaml
```

Seems like nothing can authenticate, including the process doing the RBAC caching.  Authorization failures are expected since the cache has no data to validate the request against.

**Comment by enj** [comment]
@AlbertoPeon what version did you upgrade this cluster from?  Was any custom work done in regards to the certificates being used by infra components?

Please retry those commands with the `openshift-master.kubeconfig` file instead (should be in the same folder).

**Comment by AlbertoPeon** [comment]
Hi @enj. Thanks a lot for your help!

It was also a custom build for 3.9 - the build consisted in the official release for 3.9.0 + a tiny patch to make a custom flexvolume to work. Nothing was changed about certificates at all.

---

The same commands with `openshift-master.kubeconfig` also fail:

```shell
[root@oomastertest-XXXX master]# export KUBECONFIG=/etc/origin/master/openshift-master.kubeconfig
[root@oomastertest-XXXX master]#  oc get --loglevel 5 --raw '/healthz'
I1002 10:00:45.817039    7469 helpers.go:201] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/healthz\": User \"system:anonymous\" cannot \"get\" on \"/healthz\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}]
F1002 10:00:45.817352    7469 helpers.go:119] Error from server (Forbidden): forbidden: User "system:anonymous" cannot get path "/healthz": User "system:anonymous" cannot "get" on "/healthz"
I1002 10:01:22.531309    7565 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v1.10.0+b81c8f8 (linux/amd64) kubernetes/b81c8f8" https://oomastertest-XXXX.domain.com:8443/apis?timeout=32s
I1002 10:01:22.531915    7565 round_trippers.go:405] GET https://oomastertest-XXXX.domain.com:8443/apis?timeout=32s 403 Forbidden in 0 milliseconds
I1002 10:01:22.531947    7565 round_trippers.go:411] Response Headers:
I1002 10:01:22.531968    7565 round_trippers.go:414]     Cache-Control: no-store
I1002 10:01:22.531976    7565 round_trippers.go:414]     Content-Type: application/json
I1002 10:01:22.531984    7565 round_trippers.go:414]     X-Content-Type-Options: nosniff
I1002 10:01:22.531991    7565 round_trippers.go:414]     Content-Length: 244
I1002 10:01:22.531999    7565 round_trippers.go:414]     Date: Tue, 02 Oct 2018 08:01:22 GMT
I1002 10:01:22.532024    7565 request.go:897] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:anonymous\" cannot get path \"/apis\": User \"system:anonymous\" cannot
\"get\" on \"/apis\"","reason":"Forbidden","details":{},"code":403}
I1002 10:01:22.532106    7565 cached_discovery.go:128] skipped caching discovery info, no groups found
F1002 10:01:22.532214    7565 helpers.go:119] error: the server doesn't have a resource type "users"
```

This time however, the apiserver thinks the user is `system:anonymous`. This is not normal, isn't it?

Do you believe the certificates are somehow incorrect? From what I can see they have not been changed at all during the upgrade and they are not expired.

**Comment by enj** [comment]
> The history of the cluster goes from 3.4 -> 3.5 -> 3.6 -> 3.7 -> 3.9 -> 3.10.

I assume you have been using ansible playbooks to do the upgrades?  (3.8 was actually a version as well but it was hidden by the playbooks)

---

> Do you believe the certificates are somehow incorrect?

There is something wrong with the `openshift-master.kubeconfig` file at the very least.  Before making any changes, I suggest backing up everything.  Then see if you can fix `openshift-master.kubeconfig` either manually or by restoring a backup (be careful not to post it here).

If you are unable to fix it, take a look at the following command to try to recreate it (be careful with this command as it can easily overwrite existing files):

`oc adm ca create-master-certs --help`

Once you get that file fixed, everything should start working again.

**Comment by AlbertoPeon** [comment]
@enj Thanks a lot for your help! 

Once you pointed us to `openshift-master.kubeconfig` we were able to fix the issue! The file was indeed misconfigured pointing to a context that didn't exist (this was due to a configuration change we did on the masters, nothing to do with OpenShift itself).

Thanks again!
