### ISSUE TITLE
OCP 3.10 - Local volume not allocated to a claim.

### ISSUE THREAD

**Issue by whitingjr** [openshift/origin#21108]
[provide a description of the issue]

The local volumes created by the provisioner are not being allocated to a claim.

##### Version

> # oc version
> oc v3.10.34
> kubernetes v1.10.0+b81c8f8
> features: Basic-Auth GSSAPI Kerberos SPNEGO
> 
> Server https://benchserver7:8443
> openshift v3.10.34
> kubernetes v1.10.0+b81c8f8
> #

##### Steps To Reproduce
1. install ocp 3.10 from the branch in Git
2. configure the local volume provisioner
3. configure at least 1 pv 
4. create a pod with a pvc that uses the storage class configured in step 2.

##### Current Result

Claims stuck in Pending state.

> NAME                    STATUS    VOLUME                 CAPACITY   ACCESS MODES   STORAGECLASS   AGE
> backend-redis-storage   Pending                                                    local-ssd	  39m
> mysql-storage           Pending                                                    local-ssd	  1h
> system-redis-storage    Pending                                                    local-ssd	  1h
> system-storage          Bound     pvnfs.system-storage   100Mi      RWX                           6d

##### Expected Result
All claims allocated a persistent volume.

##### Additional Information

> # docker logs 9fd26a1352e5
> I0926 12:55:56.295183       1 common.go:255] StorageClass "local-ssd" configured with MountDir "/mnt/local-storage/local-ssd", HostDir "/mnt/local-storage/local-ssd", BlockCleanerCommand ["/scripts/quick_reset.sh"]
> I0926 12:55:56.295244       1 main.go:42] Configuration parsing has been completed, ready to run...
> I0926 12:55:56.295407       1 common.go:315] Creating client using in-cluster config
> I0926 12:55:56.309038       1 main.go:52] Starting controller
> I0926 12:55:56.309056       1 controller.go:42] Initializing volume cache
> I0926 12:55:56.311407       1 populator.go:85] Starting Informer controller
> I0926 12:55:56.311425       1 populator.go:89] Waiting for Informer initial sync
> I0926 12:55:56.322058       1 cache.go:55] Added pv "local-pv-3d1345ab" to cache
> I0926 12:55:56.322076       1 cache.go:55] Added pv "local-pv-850e763b" to cache
> I0926 12:55:56.322082       1 cache.go:55] Added pv "local-pv-ca9ccf2" to cache
> I0926 12:55:57.311643       1 controller.go:72] Controller started
> W0926 13:13:39.418510       1 reflector.go:341] github.com/kubernetes-incubator/external-storage/local-volume/provisioner/pkg/populator/populator.go:87: watch of *v1.PersistentVolume ended with: The resourceVersion for the provided watch is too old.
> I0926 13:13:40.421862       1 cache.go:64] Updated pv "local-pv-3d1345ab" to cache
> I0926 13:13:40.421894       1 cache.go:64] Updated pv "local-pv-850e763b" to cache
> I0926 13:13:40.421904       1 cache.go:64] Updated pv "local-pv-ca9ccf2" to cache

**Comment by whitingjr** [comment]
Found the cause. Which I suspect is a defect.
The PVC was requesting 1014Mi storage size and the PV was 1014Mi in size. That's the mounted size of the mountpoint. But the 2 were never successfully associated by Openshift. The status of the PVC/PV was never updated to Bound.

 What succeeded for me was to re-create the PVC with a smaller size. Adjusting it from 1014Mi to 500Mi size.

 After doing that the PVC and PV were associated and the status of both set to Bound.

**Comment by jwforres** [comment]
@openshift/sig-storage

**Comment by jsafrane** [comment]
@whitingjr, it seems the provisioner created some PV, so at least that part is somewhat working. Can you please share yaml of the  created PV? It seems its capacity is wrong. How wrong is it?

**Comment by whitingjr** [comment]
@jsafrane here is the pv that is Bound

> # oc get pv|grep backend-redis-storage
> local-pv-f4098e94      1014Mi     RWO            Delete           Bound       3scale/backend-redis-storage   local-ssd                13d
> #
