### ISSUE TITLE
Containers (pod) leaks

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#2112]
Hi All,
    After one week testing OpenShift V3, we have seen lots of stopped docker containers in the nodes, I think that OpenShift should provide some kind of house-keeping tasks, I think that openshift node should be responsible of deleting all the non running containers.

Many thanks.

**Comment by smarterclayton** [comment]
The node is supposed to garbage collect containers, but we have had anecdotal reports that is not working properly.  What version are you on?  The gc is containers older than 10s, no more than five copies of the same container, and no more than 100 total containers.  Pods in fail loops appeared to be the most common culprit for exceeding the gc limit.

**Comment by roldancer** [comment]
[root@ose1 ~]# osadm version
osadm v0.4.3.2-125-g1104fae
kubernetes v0.14.1-582-gb12d75d

For instance, I have 18 stopped instances of the router pod....

[root@ose1 ~]# docker ps -a | grep Exited | grep -i router | wc -l
18

Question:

is it possible to customize the gc containers parameters?

**Comment by smarterclayton** [comment]
> On May 11, 2015, at 4:18 AM, Cristian <notifications@github.com> wrote:
> 
> [root@ose1 ~]# osadm version
> osadm v0.4.3.2-125-g1104fae
> kubernetes v0.14.1-582-gb12d75d
> 
> For instance, I have 18 stopped instances of the router pod....
> 
That's probably within the expected bounds then, although 0.4.3 is old enough that it might actually be before this problem surfaced.
> [root@ose1 ~]# docker ps -a | grep Exited | grep -i router | wc -l
> 18
> 
> Question:
> 
> is it possible to customize the gc containers parameters?
> 
Not today, but it's something that could be added to the node config without much trouble.

**Comment by smarterclayton** [comment]
Apparently was just recently fixed upstream

**Comment by smarterclayton** [comment]
This has been fixed with https://github.com/openshift/origin/pull/2323
