### ISSUE TITLE
hack/env make build WHAT=cmd/oc fails on mojave

### ISSUE THREAD

**Issue by ecordell** [openshift/origin#21137]
Attempting to build `oc` on MacOS mojave fails on master:

```
hack/build-go.sh cmd/oc
++ Building go targets for linux/amd64: cmd/oc
[INFO] hack/build-go.sh exited with code 0 after 00h 03m 44s
[WARNING] Copying _output/local/releases from the container failed!
[WARNING] Error: No such container:path: 1d2272e019788ae739f3b9e164d84f2fe290bc311cbdfe54df0cc1ad7018f196:/go/src/github.com/openshift/origin/_output/local/releases
Error response from daemon: remove origin-build-tmp-a0490b96f6bf9458b3b46d90ff5fcffab242b91d: volume is in use - [3e3aea69756fa1cbbf4d19d3463bb65656406028ec5ce7521be039e0db1600a4]
[ERROR] hack/lib/build/environment.sh:236: `[[ -n "${OS_DEBUG:-}" ]]` exited with status 1.
```

##### Version
master

##### Steps To Reproduce
1. Have macOS mojave
2. `hack/env make build WHAT=cmd/oc`

##### Current Result

> [ERROR] hack/lib/build/environment.sh:236: `[[ -n "${OS_DEBUG:-}" ]]` exited with status 1.

##### Expected Result

An oc binary

##### Additional Information
docker 18.06.1-ce-mac73

**Comment by smarterclayton** [comment]
What version of bash does Mojave have?

**Comment by ecordell** [comment]
> What version of bash does Mojave have?

Comes with 3.2; I updated to 4.4 but had the same error.
