### ISSUE TITLE
Hardcoded images in oc cluster up for automation broker, openshift-service-cert-signer-operator

### ISSUE THREAD

**Issue by rgordill** [openshift/origin#21148]
When looking at other templates for oc cluster up, the image is a param, so it can be customized with --image (ex: https://github.com/openshift/origin/blob/release-3.11/install/templateservicebroker/apiserver-template.yaml#L6). However this does not happen for those components, or the param is not used in the template.

See:

https://github.com/openshift/origin/blob/release-3.11/install/automationservicebroker/install.yaml#L25
https://github.com/openshift/origin/blob/release-3.11/install/openshift-service-cert-signer-operator/install.yaml#L67

##### Version
oc v3.11.17
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.99.100:8443
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
oc cluster up --image "XXXX/openshift3/ose-${component}:${version}" --enable automation-service-broker

##### Current Result
docker images:
docker.io/automationbroker/automation-broker-apb                                              v3.11
docker.io/openshift/origin-service-serving-cert-signer                                           v3.11

##### Expected Result
XXXX/openshift3/ose-automation-broker-apb                                                       v3.11
XXXX/openshift3/ose-service-serving-cert-signer                                                 v3.11

**Comment by jmontleon** [comment]
https://github.com/openshift/origin/issues/20888 exists for the openshift/origin-service-serving-cert-signer image.

My team is aware that this isn't ideal for the automation-broker, but as our images are not published under openshift3 we can't rely on the default location existing and I don't believe there's a way to pass in parameters to components so we have no other means to provide a mechanism. Hopefully with the new operator approach we can make this work a little more smoothly.
