### ISSUE TITLE
Pods in Pending status during 13hs

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#2115]
Hi All, I have created an application with Replicas=3, 1 pod started successfully but two pods were in Pending status... from the osc client side I haven't received any error message, everything was OK.

[oseuser2@ose1 ~]$ osc get pods
POD                          IP          CONTAINER(S)           IMAGE(S)                    HOST                        LABELS                                                                               STATUS    CREATED
tomcatfullcontroller-aaokg   10.1.1.19   tomcatfull-container   tomcat:latest               ose3.novalocal/10.78.29.4   name=tomcatfullPod                                                                   Running   13 hours
tomcatfullcontroller-i24mw               tomcatfull-container   tomcat:latest               <unassigned>                name=tomcatfullPod                                                                   Pending   13 hours
tomcatfullcontroller-iqztz               tomcatfull-container   tomcat:latest               <unassigned>                name=tomcatfullPod                                                                   Pending   13 hours

I have found the following error in the openshift master's logs

ay 07 05:45:26 ose1.novalocal openshift-master[11796]: E0507 05:45:26.283543   11796 factory.go:274] Error scheduling produban tomcatfullcontroller-i24mw: failed to find fit for pod: {{ } {tomcatfullcontroller-i24mw tomcatfullcontroller- produban /api/v1beta3/namespaces/produban/pods/tomcatfullcontroller-i24mw d24a4d6c-f42e-11e4-a9a0-fa163e3f2365 173749 2015-05-06 16:31:06 -0400 EDT <nil> map[name:tomcatfullPod] map[]} {[] [{tomcatfull-container tomcat:latest [] []  [{ 48080 8080 TCP }] [{FOO BAR}] {map[] map[]} [] <nil> <nil> <nil> /dev/termination-log false Always {[] []}}] Always ClusterFirst map[]  false} {Pending []    []}}Node ose2.novalocal: PodFitsPortsNode ose3.novalocal: PodFitsPortsNode ose1.novalocal: Region; retrying
May 07 05:45:26 ose1.novalocal openshift-master[11796]: I0507 05:45:26.283598   11796 factory.go:370] Backing off 1m0s for pod tomcatfullcontroller-i24mw
May 07 05:45:28 ose1.novalocal openshift-master[11796]: E0507 05:45:28.286917   11796 endpoints_controller.go:93] Failed to find an IP for pod produban/tomcatfullcontroller-i24mw
May 07 05:45:28 ose1.novalocal openshift-master[11796]: E0507 05:45:28.286945   11796 endpoints_controller.go:93] Failed to find an IP for pod produban/tomcatfullcontroller-iqztz
May 07 05:45:30 ose1.novalocal openshift-master[11796]: I0507 05:45:30.270523   11796 factory.go:200] About to try and schedule pod tomcatfullcontroller-iqztz
May 07 05:45:30 ose1.novalocal openshift-master[11796]: I0507 05:45:30.270552   11796 scheduler.go:106] Attempting to schedule: &{{ } {tomcatfullcontroller-iqztz tomcatfullcontroller- produban /api/v1beta3/namespaces/produban/pods/tomcatfullcontroller-iqztz 210676f6-f42f-11e4-a9a0-fa163e3f2365 173798 2015-05-06 16:33:18 -0400 EDT <nil> map[name:tomcatfullPod] map[]} {[] [{tomcatfull-container tomcat:latest [] []  [{ 48080 8080 TCP }] [{FOO BAR}] {map[] map[]} [] <nil> <nil> <nil> /dev/termination-log false Always {[] []}}] Always ClusterFirst map[]  false} {Pending []    []}}

After changing the quota limit  "resourcequotas": "4", it was initially in 1, everything started to works ok.

root@ose1 beta3]# more quota.json 
{
  "apiVersion": "v1beta3",
  "kind": "ResourceQuota",
  "metadata": {
    "name": "test-quota"
  },
  "spec": {
    "hard": {
      "memory": "512Mi",
      "cpu": "200m",
      "pods": "10",
      "services": "10",
      "replicationcontrollers": "3",
      "resourcequotas": "4"
    }
  }
}

NOTE: In order to understand what is happening from the client perspective, It could be useful to get an error message indicating that some resources limits were reached, also timeout for the scheduler will be welcomed.

Many thanks.

**Comment by derekwaynecarr** [comment]
The problem and your solution do not quite mesh.  Ability to find fits for a pod in the scheduler are not related to how many ResourceQuota objects you have in your project.  Given the issue description it's hard to diagnose further, but I will provide more information to help you debug issues if you encounter them in the future.

Tip number 1:  If you are not seeing any activity for the object being scheduled to a node, or a replication controller does not appear to be sizing up or sizing down the number of replicas, I recommend you look at the Events in the project to debug why.

```
$ osc get events
```

Will you give you a listing of all things that are happening in the project that could affect schedulability, or quota constraints.  In addition, if you do the following:

```
$ osc describe rc <your replication controller>
```

It would print out any events related to just your single replication controller discussing why it can or cannot size up the number of replicas.  If it was a quota constraint, you would see messages like "Limited to %s memory" or "Limited to % cpu", "Limited to 5 pods", etc.

Also if your pods are using hostIPs, it is possible that you may not have enough nodes with the available hosts to satisfy scheduling.  If so, the scheduler would throw an event in the events table documenting that.

**Comment by roldancer** [comment]
Hi @derekwaynecarr , many thanks for the tips!!!! I will try to reproduce the problem ....

Thanks.

**Comment by liggitt** [comment]
@derekwaynecarr that'd be helpful to throw in https://github.com/openshift/origin/blob/master/docs/debugging-openshift.md

**Comment by sdodson** [comment]
I'm running into forever pending pods as well.

```
# osc get ev -n sdodson
FIRSTSEEN                         LASTSEEN                          COUNT     NAME                     KIND      SUBOBJECT   REASON      SOURCE         MESSAGE
Fri, 15 May 2015 18:52:25 +0000   Fri, 15 May 2015 18:52:25 +0000   1         deploy-database-13ae11   Pod                   scheduled   {scheduler }   Successfully assigned deploy-database-13ae11 to 172.16.17.45
Fri, 15 May 2015 18:52:26 +0000   Fri, 15 May 2015 18:52:26 +0000   1         ruby-sample-build-1      Pod                   scheduled   {scheduler }   Successfully assigned ruby-sample-build-1 to 172.16.17.43
Fri, 15 May 2015 18:52:46 +0000   Fri, 15 May 2015 18:52:46 +0000   1         database-1-r8vkm         Pod                   scheduled   {scheduler }   Successfully assigned database-1-r8vkm to 172.16.17.44
Fri, 15 May 2015 18:53:36 +0000   Fri, 15 May 2015 18:53:36 +0000   1         deploy-frontend-1qcmon   Pod                   scheduled   {scheduler }   Successfully assigned deploy-frontend-1qcmon to 172.16.17.46

# osc get pods -n sdodson
POD                      IP        CONTAINER(S)               IMAGE(S)                                                                   HOST                        LABELS                                                                                                                  STATUS      CREATED
database-1-r8vkm                   ruby-helloworld-database   registry.access.redhat.com/openshift3_beta/mysql-55-rhel7                  172.16.17.44/               deployment=database-1,deploymentconfig=database,name=database,template=application-template-stibuild                    Pending     36 minutes
deploy-frontend-1qcmon             deployment                 docker-registry.ops.rhcloud.com/openshift3_beta/ose-deployer:v0.4.3.2      172.16.17.46/               <none>                                                                                                                  Pending     35 minutes
ruby-sample-build-1                sti-build                  docker-registry.ops.rhcloud.com/openshift3_beta/ose-sti-builder:v0.4.3.2   172.16.17.43/172.16.17.43   build=ruby-sample-build-1,buildconfig=ruby-sample-build,name=ruby-sample-build,template=application-template-stibuild   Succeeded   36 minutes

[root@172 ~]# osc describe rc database-1 -n sdodson
Name:		database-1
Image(s):	registry.access.redhat.com/openshift3_beta/mysql-55-rhel7
Selector:	deployment=database-1,deploymentconfig=database,name=database
Labels:		template=application-template-stibuild
Replicas:	1 current / 1 desired
Pods Status:	0 Running / 1 Waiting / 0 Succeeded / 0 Failed
No events.
```

I do see repeated failed to find ip for pod messages in my master logs.
```
# journalctl -u openshift-master | grep database-1-r8vkm
May 15 18:52:40 172.16.17.221 openshift-master[14670]: I0515 18:52:40.859486   14670 factory.go:200] About to try and schedule pod database-1-r8vkm
May 15 18:52:40 172.16.17.221 openshift-master[14670]: I0515 18:52:40.859509   14670 scheduler.go:106] Attempting to schedule: &{{ } {database-1-r8vkm database-1- sdodson /api/v1beta3/namespaces/sdodson/pods/database-1-r8vkm 9028baab-fb33-11e4-ab11-0a5c4484828d 175094 2015-05-15 18:52:40 +0000 UTC <nil> map[deployment:database-1 deploymentconfig:database name:database template:application-template-stibuild] map[deploymentConfig:database deploymentVersion:1 deployment:database-1]} {[] [{ruby-helloworld-database registry.access.redhat.com/openshift3_beta/mysql-55-rhel7 [] []  [{ 0 3306 TCP }] [{MYSQL_USER user2IM} {MYSQL_PASSWORD Y7gyTCD3} {MYSQL_DATABASE root}] {map[] map[]} [] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Always ClusterFirst map[]  false} {Pending []    []}}
May 15 18:52:40 172.16.17.221 openshift-master[14670]: I0515 18:52:40.860074   14670 priorities.go:67] database-1-r8vkm -> 172.16.17.45: Least Requested Priority, AbsoluteRequested: (0, 0) / (2000, 7405715456) Score: (10, 10)
May 15 18:52:40 172.16.17.221 openshift-master[14670]: I0515 18:52:40.860158   14670 priorities.go:67] database-1-r8vkm -> 172.16.17.46: Least Requested Priority, AbsoluteRequested: (0, 0) / (2000, 7405715456) Score: (10, 10)
May 15 18:52:40 172.16.17.221 openshift-master[14670]: I0515 18:52:40.860186   14670 priorities.go:67] database-1-r8vkm -> 172.16.17.43: Least Requested Priority, AbsoluteRequested: (0, 0) / (2000, 7405715456) Score: (10, 10)
May 15 18:52:40 172.16.17.221 openshift-master[14670]: I0515 18:52:40.860209   14670 priorities.go:67] database-1-r8vkm -> 172.16.17.44: Least Requested Priority, AbsoluteRequested: (0, 0) / (2000, 7405715456) Score: (10, 10)
May 15 18:52:40 172.16.17.221 openshift-master[14670]: I0515 18:52:40.860339   14670 factory.go:321] Attempting to bind database-1-r8vkm to 172.16.17.44
May 15 18:54:10 172.16.17.221 openshift-master[14670]: E0515 18:54:10.037701   14670 endpoints_controller.go:93] Failed to find an IP for pod sdodson/database-1-r8vkm
May 15 18:55:26 172.16.17.221 openshift-master[14670]: E0515 18:55:26.237424   14670 endpoints_controller.go:93] Failed to find an IP for pod sdodson/database-1-r8vkm
```

pod json
```
# osc get pod -n sdodson database-1-r8vkm -o json
{
    "kind": "Pod",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "database-1-r8vkm",
        "generateName": "database-1-",
        "namespace": "sdodson",
        "selfLink": "/api/v1beta1/pods/database-1-r8vkm?namespace=sdodson",
        "uid": "9028baab-fb33-11e4-ab11-0a5c4484828d",
        "resourceVersion": "175097",
        "creationTimestamp": "2015-05-15T18:52:40Z",
        "labels": {
            "deployment": "database-1",
            "deploymentconfig": "database",
            "name": "database",
            "template": "application-template-stibuild"
        },
        "annotations": {
            "deployment": "database-1",
            "deploymentConfig": "database",
            "deploymentVersion": "1"
        }
    },
    "spec": {
        "volumes": null,
        "containers": [
            {
                "name": "ruby-helloworld-database",
                "image": "registry.access.redhat.com/openshift3_beta/mysql-55-rhel7",
                "ports": [
                    {
                        "containerPort": 3306,
                        "protocol": "TCP"
                    }
                ],
                "env": [
                    {
                        "name": "MYSQL_USER",
                        "value": "user2IM"
                    },
                    {
                        "name": "MYSQL_PASSWORD",
                        "value": "stuff"
                    },
                    {
                        "name": "MYSQL_DATABASE",
                        "value": "root"
                    }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent",
                "capabilities": {}
            }
        ],
        "restartPolicy": "Always",
        "dnsPolicy": "ClusterFirst",
        "host": "172.16.17.44"
    },
    "status": {
        "phase": "Pending"
    }
}
```

**Comment by sdodson** [comment]
The culprit in my environment seems to have been failed sdn, restarting the sdn resolved the issues.

**Comment by derekwaynecarr** [comment]
Is this a similar issue to what you opened here:
https://github.com/openshift/origin/issues/2048

If so, are you ok with tracking a fix to a deployment that took too long in the referenced issue?

**Comment by deanpeterson** [comment]
I am seeing the same thing.  I ran the persistent storage mongodb example and my pod is in pending state perpetually.  I ran ./oc describe rc mongodb-1 and see:

LastSeen	Count	From				SubobjectPath	Reason			Message
  15m		15m		1	{deployer }					failedUpdate		Error updating deployment test/mongodb-1 status to Pending
  15m		15m		1	{replication-controller }			successfulCreate	Created pod: mongodb-1-csirq


There is nothing in the Openshift console that looks like a problem:
I0912 22:15:48.049428    4775 kubelet.go:1749] Starting kubelet main sync loop.
E0912 22:15:48.103108    4775 util.go:68] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:62
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:53
/usr/lib/golang/src/runtime/asm_amd64.s:401
/usr/lib/golang/src/runtime/panic.go:387
/usr/lib/golang/src/runtime/panic.go:42
/usr/lib/golang/src/runtime/sigpanic_unix.go:26
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/secret/secret.go:59
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/plugins.go:223
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/volumes.go:83
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/volumes.go:59
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/persistent_claim/persistent_claim.go:82
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/volumes.go:91
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/volumes.go:111
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1201
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:356
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:109
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:118
/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:153
/usr/lib/golang/src/runtime/asm_amd64.s:2232

**Comment by liggitt** [comment]
Fixed in https://github.com/openshift/origin/pull/4384/files#diff-d5743d081660f6153bf9bd1b5b0c0e0bR59, will be in 1.0.6

**Comment by deanpeterson** [comment]
Great, thanks!

**Comment by deanpeterson** [comment]
Do you know when 1.0.6 will be out; or is there a work around for now?

**Comment by deanpeterson** [comment]
I see the process for building from source is not too bad.  I will do that.

**Comment by deanpeterson** [comment]
I built from source and have the latest fixes to openshift.  Now when I try to deploy the mongodb persistent example I get the following error in the console:

E0913 12:17:58.857886    5660 persistentvolume_claim_binder_controller.go:142] PVClaimBinder could not update claim mongodb: Error updating volume: persistentvolumeclaims "mongodb" cannot be updated: the object has been modified; please apply your changes to the latest version and try again

**Comment by deanpeterson** [comment]
I built from source to get past a problem I have deploying the mongdb persistent example template. When deploying, the pod is created but it stays in pending state forever. I upgraded to the latest master by building binaries from source. However, I am still having the same problem. The pod still just stays in pending state forever.

**Comment by raffian** [comment]
@sdodson In your comment above regarding "Failed to find an IP", what is "sdn"?
