### ISSUE TITLE
Could not load image metadata.

### ISSUE THREAD

**Issue by cycwll** [openshift/origin#21168]
#### Description
I installed openshift cluster by ansible（version 3.10）, one master, two compute node, one infra node.
![image](https://user-images.githubusercontent.com/6410130/46416498-3a115a80-c75a-11e8-8b75-c45c1509a6ae.png)

I configured  HTTP_PROXY and HTTPS_PROXY for docker  in /etc/sysconfig/docker file（not in the ansible inventory file ）, and I am sure that every node can be download the image by docker pull nginx.

![image](https://user-images.githubusercontent.com/6410130/46416250-b3f51400-c759-11e8-99d2-8f8032f26891.png)

#### Problem
I have a problem, when I Deploy Image to my project by OpenShift web console:

 Could not load image metadata.
Internal error occurred: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

![image](https://user-images.githubusercontent.com/6410130/46415559-1b11c900-c758-11e8-98af-02f6eaa34d49.png)

The same problem happened, when I by Image Stream Tag 
![image](https://user-images.githubusercontent.com/6410130/46417628-ae4cfd80-c75c-11e8-919b-3b2f557d6db7.png)

```
#### [root@master ~]# oc get pod -n default
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-3-cwxfm    1/1       Running   0          19m
registry-console-1-2gjvz   1/1       Running   0          5h
router-4-c8kr7             1/1       Running   0          19m

#### [root@master ~]# oc get is -n openshift
NAME             DOCKER REPO                                                 TAGS                         UPDATED
dotnet           docker-registry.default.svc:5000/openshift/dotnet           2.0
dotnet-runtime   docker-registry.default.svc:5000/openshift/dotnet-runtime   2.0
httpd            docker-registry.default.svc:5000/openshift/httpd            2.4
jenkins          docker-registry.default.svc:5000/openshift/jenkins          1,2
mariadb          docker-registry.default.svc:5000/openshift/mariadb          10.1,10.2
mongodb          docker-registry.default.svc:5000/openshift/mongodb          3.2,3.4,2.4 + 1 more...
mysql            docker-registry.default.svc:5000/openshift/mysql            5.5,5.6,5.7
nginx            docker-registry.default.svc:5000/openshift/nginx            1.12,1.8,1.10
nodejs           docker-registry.default.svc:5000/openshift/nodejs           0.10,4,6 + 1 more...
perl             docker-registry.default.svc:5000/openshift/perl             5.24,5.16,5.20
php              docker-registry.default.svc:5000/openshift/php              5.5,5.6,7.0 + 1 more...
postgresql       docker-registry.default.svc:5000/openshift/postgresql       9.4,9.5,9.6 + 1 more...
python           docker-registry.default.svc:5000/openshift/python           3.3,3.4,3.5 + 2 more...
redis            docker-registry.default.svc:5000/openshift/redis            3.2
ruby             docker-registry.default.svc:5000/openshift/ruby             2.4,2.5,2.0 + 2 more...
wildfly          docker-registry.default.svc:5000/openshift/wildfly          10.0,10.1,11.0 + 3 more...
```

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
@openshift/sig-user-interface I don't know what calls you guys are making in these flows, so i need details on that before i can help.

**Comment by spadgett** [comment]
For image name, we are using `ImageStreamImport`:

https://github.com/openshift/origin-web-console/blob/master/app/scripts/services/images.js#L23-L40

For image stream tag, we get the `ImageStreamImage`.

**Comment by bparees** [comment]
@cycwll please run:

```
$ oc get istag nginx:1.10 -n openshift
NAME         IMAGE REF                                                                                                                  UPDATED
nginx:1.10   docker-registry.default.svc:5000/openshift/nginx@sha256:67a1757a7f4e4185b72dcac2a19efdfc82d59f574c3352d25c215c900653ea58   About a minute ago
```

then based on the output, run:

```
$ oc get imagestreamimage nginx@sha256:67a1757a7f4e4185b72dcac2a19efdfc82d59f574c3352d25c215c900653ea58 -n openshift
```

where you replace "sha256:xxxxxxxxxxxxxx" with the value you get from the first command (you can see I used the value from my output in my invocation)

I would expect you to see an output like:
```
NAME                                                                            UPDATED
nginx@sha256:67a1757a7f4e4185b72dcac2a19efdfc82d59f574c3352d25c215c900653ea58   About a minute ago
```

**Comment by bparees** [comment]
regarding this error:
```
Could not load image metadata.
Internal error occurred: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

That would point to your openshift apiserver being unable to talk to docker.io for some reason (possibly temporary).
