### ISSUE TITLE
Simple way to delete everything in a project

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#2116]
As usual, I'm probably missing something, but if I do something along the lines of:

`osc delete builds,buildconfigs,deploymentconfigs,imagerepositories,pods,replicationcontrollers,routes,services,templates --all`

It doesn't remove the controllers before removing the pods, therefore typically the result is:
* pods deleted
* replication controllers start spinning up new pods
* replication controllers deleted
* new pods exist when IMO they shouldn't

Can it be ensured that if a user requests in one go to delete all RCs and pods, that the end result is that everything is gone?
Also out of interest is it already guaranteed that if two separate requests are made in order, first to delete RCs, second to delete pods, that the end result is no pods left?

**Comment by smarterclayton** [comment]
Try `osc delete all --all`

**Comment by liggitt** [comment]
at that point, should you just delete the project?

**Comment by smarterclayton** [comment]
Don't want to delete perms, members, quota, etc....

**Comment by liggitt** [comment]
And `osc delete all` magically leaves those things?

**Comment by smarterclayton** [comment]
Yup

**Comment by smarterclayton** [comment]
You see, "all" probably doesn't mean what you think it means.

**Comment by liggitt** [comment]
...

**Comment by smarterclayton** [comment]
Careful, there's a dot shortage and comic sans is running low.

**Comment by jim-minter** [comment]
I reckon that "osc all --all" plus fixing #2043 does everything I need.  As far as I'm concerned this can be closed.
