### ISSUE TITLE
[3.11 router] dynamic configuration manager support for custom configuration templates

### ISSUE THREAD

**Issue by alexcern** [openshift/origin#21170]
The router dynamic configuration manager introduced by https://github.com/openshift/origin/pull/19073 for the upcoming 3.11 release is a very welcome addition, many thanks @ramr !

We would be interested to make it work with [customized router templates](https://docs.okd.io/latest/install_config/router/customized_haproxy_router.html#router-configuration-template) when the customization involves new, custom annotations.

##### Version
3.11 alpha

##### Steps To Reproduce
1. Enable [dynamic configuration manager](https://docs.okd.io/latest/install_config/router/default_haproxy_router.html#using-the-dynamic-configuration-manager)
2. Set up a [customized haproxy router template](https://docs.okd.io/latest/install_config/router/customized_haproxy_router.html#router-configuration-template) involving custom route annotations. For instance add something like this to `backend` definitions:

  ```
    {{ if isTrue (index $cfg.Annotations "my-custom-annotation")  }}
      acl my_condition src -m ip 1.2.3.4/32
      tcp-request content reject unless my_condition
    {{ end }}
  ```
3. Create a route with annotation `my-custom-annotation=true`

##### Current Result

`my-custom-annotation` is not taken into account when matching the new annotated route to a blueprint. Thus a blueprint without the annotation is used, and the custom configuration associated with `my-custom-annotation` is not applied.

##### Expected Result

A blueprint matching the custom annotation is selected, or no blueprint with that annotation is found and router configuration is reloaded completely to enforce the custom configuration.

##### Additional Information
It seems to me this there could be two ways to support a customized router template with the dynamic manager:
* allow an empty pool of blueprints so every route added or changed causes a full reload, this may be as simple as allowing `0` for the minimum value of `ROUTER_BLUEPRINT_ROUTE_POOL_SIZE` in https://github.com/openshift/origin/blob/4295f8b703e841c136e3e362493397e40238be42/pkg/cmd/infra/router/template.go#L169 -  the dynamic manager remains interesting for dynamic management of endpoints
* add a new router configuration option where one can specify a list of additional custom annotations that need to be taken into account when matching blueprints. This would be merged with the default annotation list in https://github.com/openshift/origin/blob/4295f8b703e841c136e3e362493397e40238be42/pkg/router/template/configmanager/haproxy/manager.go#L1095-L1116

I would be happy to submit a PR for either option.

**Comment by jwforres** [comment]
@openshift/sig-network-edge

**Comment by alexcern** [comment]
Thanks @ramr 

The `skip-route-blueprint-match` annotation makes a lot of sense. I will prepare a PR with this and an environment variable to override the list of annotations for blueprint match.

Ideally we would set this together with the template itself, since the list of annotations to match is exactly the list of annotations used by the template to vary the configuration. But I could not think of a fine way to integrate this in the template definition.

**Comment by ramr** [comment]
@isantospardo  thanks for the PR ... sorry for the delay in reviewing - have been out of commission for a while. I left some comments/requested some changes on the PR. Thanks again.
