### ISSUE TITLE
Following cluster up getting started documentation will lead to "did not detect an --insecure-registry argument on the Docker daemon"

### ISSUE THREAD

**Issue by tiraboschi** [openshift/origin#21172]
Following cluster up getting started documentation will lead to "did not detect an --insecure-registry argument on the Docker daemon".

https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#getting-started says that you have to set

```
[registries.insecure]
registries = ['172.30.0.0/16']
```
in `/etc/containers/registries.conf` OR
```
{
   "insecure-registries": [
     "172.30.0.0/16"
   ]
}
```
in `/etc/docker/daemon.json` but you instead need BOTH.

Then

```
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
```

##### Version
```
[stirabos@openshift linux]$ oc version
oc v3.11.0-alpha.0+f7602dd-1284
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
[stirabos@openshift linux]$ yum list installed | grep docker
docker.x86_64                        2:1.13.1-75.git8633870.el7.centos @extras  
docker-client.x86_64                 2:1.13.1-75.git8633870.el7.centos @extras  
docker-common.x86_64                 2:1.13.1-75.git8633870.el7.centos @extras  
python-docker-pycreds.noarch         1.10.6-4.el7                      @extras  
python2-docker.noarch                2.4.2-1.el7.centos                @ansible-service-broker
```

##### Steps To Reproduce
1. Try to deploy con Centos 7 following https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#getting-started
2. oc cluster up

##### Current Result
```
did not detect an --insecure-registry argument on the Docker daemon
```

##### Expected Result
Successful deployment

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jwforres** [comment]
@openshift/sig-containers

**Comment by mtrmac** [comment]
@tiraboschi Do you have the `atomic-registries` package installed and working?

The contents of `/etc/containers/registries.conf` should ordinarily be converted into a `/run/containers/registries.conf` which causes `--insecure-registry` options to be added among the options passed to the docker daemon.

Or maybe you need just an `systemctl restart registries.service` before restarting the Docker daemon?

**Comment by vchepeli** [comment]
> @tiraboschi Do you have the `atomic-registries` package installed and working?
> 
> The contents of `/etc/containers/registries.conf` should ordinarily be converted into a `/run/containers/registries.conf` which causes `--insecure-registry` options to be added among the options passed to the docker daemon.
> 
> Or maybe you need just an `systemctl restart registries.service` before restarting the Docker daemon?

Without `systemctl restart registries.service` no file is created in `/run/containers/registries.conf`. Then when docker is started it automatically load registries from `/run/containers/registries.conf`

**Comment by planetf1** [comment]
I can confirm the same issue here. Install Centos 7, latest fixes, docker CE stable, and follow the original quick start instructions 'oc cluster up' results in the same error

**Comment by planetf1** [comment]
I can confirm that this is now working
 * By removing docker-ce, and installing docker from centos release
 * My changing BOTH files listed above to specify the insecure regsitry

The docs DO NOT make this clear and NEED to be updated.
