### ISSUE TITLE
Allow to pass NAMESPACE_LABELS or ROUTE_LABELS at the creation time of the router

### ISSUE THREAD

**Issue by bigon** [openshift/origin#21171]
Hi,

When creating a new router for sharding, it's not possible to add the NAMESPACE_LABELS or ROUTE_LABELS atomically. That means that all the existing routes will be exposed to the new created router.

The only way is to set the number of replicas to 0 for the new router, then set the NAMESPACE_LABELS and then scale up, but this feels like a hack:

1. `oc adm router router-ldv --labels='router=ldv' --selector='router=ldv'  --service-account=router --replicas=0`
2. `oc set env dc/router-ldv NAMESPACE_LABELS="router=ldv"`
3. `oc scale deploymentconfig.apps.openshift.io/router-ldv --replicas=1`

Shouldn't a way to set the *_LABELS be added to the `oc adm router` command?

3.10

**Comment by jwforres** [comment]
@openshift/sig-network-edge
