### ISSUE TITLE
imagestream local lookup failure case in origin 3.10 with oc cluster up

### ISSUE THREAD

**Issue by tmckayus** [openshift/origin#21180]
Local imagestream lookup is not working for this reproducer with oc cluster up in origin 3.10.
Same reproducer works in a full origin 3.10 install and with oc cluster up under 3.7
This may be a separate case from https://github.com/openshift/origin/issues/19663

##### Version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

works for
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. download oc client and run "oc cluster up"
2. run the attached podfail.sh which will:
    create a random project
    create an image stream by pushing docker.io/hello-world to the integrated registry (lookup not set)
    create a hello-world pod that references it
    enable local lookup for the image stream
    create a hello-world2 pod using the same manifest (only the name is different)
3. watch pods with "oc get pods"

##### Current Result
pods hello-world and hello-world2 both get an image pull error and go into ImagePullBackOff

##### Expected Result
pod hello-world should get an image pull error and go into ImagePullBackOff
pod hello-world2 should complete and go into CrashLoopBackOff

##### Additional Information
I reproduced this on a clean rhel 7.5 box
docker version 1.13.1
[podfail.sh.gz](https://github.com/openshift/origin/files/2448086/podfail.sh.gz)

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
cluster up does not provide the correct configuration for the image policy plugin to work by default.  The master team was looking into this.

**Comment by galderz** [comment]
I'm seeing a very similar issue locally. The following script does not work when using `oc cluster up` or minishift based on 3.10. Both @maschmid and @dsimansk have tried this with OpenShift enterprise set up and it works fine:

```bash
#!/usr/bin/env bash

oc cluster down
rm -drf openshift.local.clusterup
oc cluster up

oc create -f \
  https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/71-1.0.TP/amq-broker-7-image-streams.yaml
oc create -f \
  https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/71-1.0.TP/templates/amq-broker-71-statefulset-clustered.yaml

oc new-app amq-broker-71-statefulset-clustered \
  -p AMQ_USER=test \
  -p AMQ_PASSWORD=test \
  -p IMAGE=amq-broker-71-openshift:1.0
``` 

Events shows:

```
5s          5s           1         broker-amq-0.155eb955f0b6740d   Pod           spec.containers{broker-amq}   Warning   Failed             kubelet, localhost       Failed to pull image "amq-broker-71-openshift:1.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for amq-broker-71-openshift, repository does not exist or may require 'docker login'
```

**Comment by galderz** [comment]
Any updates on this?
