### ISSUE TITLE
vagrant unable to setup multi-machine environment in cloud

### ISSUE THREAD

**Issue by akostadinov** [openshift/origin#2118]
Specifically I'm using OpenStack. With the changes in #2107 it looks like everything would be working except that handling of `openshift.local.config` directory seems broken to me. As far as I see it would fail on AMZ as well.

In `vagrant/provision-master.sh` I see:

```
  SERVER_CONFIG_DIR="`pwd`/openshift.local.config"
  MASTER_CONFIG_DIR="${SERVER_CONFIG_DIR}/master"
  CERT_DIR="${MASTER_CONFIG_DIR}"

  # Master certs
  /usr/bin/openshift admin create-master-certs \
    --overwrite=false \
    --cert-dir=${CERT_DIR} \
    --master=https://${MASTER_IP}:8443 \
    --hostnames=${MASTER_IP},${MASTER_NAME}

  # Certs for nodes
  for (( i=0; i<${#MINION_NAMES[@]}; i++)); do
    minion=${MINION_NAMES[$i]}
    ip=${minion_ip_array[$i]}

    /usr/bin/openshift admin create-node-config \
      --node-dir="${SERVER_CONFIG_DIR}/node-${minion}" \
...
```

This generates `openshift.local.config` on the master node but there is no mechanism to sync that to the minion nodes. Thus minions fail with:

```
==> akostadi-minion-1: + cp -r /vagrant/openshift.local.config /
==> akostadi-minion-1: cp: 
==> akostadi-minion-1: cannot stat ‘/vagrant/openshift.local.config’
==> akostadi-minion-1: : No such file or directory
==> akostadi-minion-1: An error occurred. The error will be shown after all tasks complete.
...
```

So I am wondering how to implement syncing from master to nodes. One approach would be to generate the files locally and sync them to nodes as regular vagrant sync dirs. Or given master can scp to minions, then we can scp.

First approach issue is ensuring the operations can be performed reliably locally.

Second approach issue is synchronizing script executions. This is feasible to implement though, minions could wait in a loop for the target directory to be populated.

**Comment by jwhonce** [comment]
@akostadinov Have you reviewed the work in [openshift-ansible](https://github.com/openshift/openshift-ansible) to see if that provides what you need?

**Comment by akostadinov** [comment]
There were some issues with SDN and something else last week. Not sure if those were fixed. In any case, having your machines started automatically and managed from one place is much more convenient than spawning machines by yourself and doing manual preparations on them before you can get to automated setup. So I don't think ansible is solving this problem. Actually ansible could be made part of the vagrant solution but is not a replacement.

**Comment by pweil-** [comment]
closing, openshift-ansible is the recommended way of deploying at this point
