### ISSUE TITLE
How to pass separate template files to oc process?

### ISSUE THREAD

**Issue by lomholdt** [openshift/origin#21190]
When I `oc process -f template.yaml` I would like to split my different objects into several files such as `service.yaml`, `route.yaml`, `deploymentconfig.yaml`. Basically I should be able to do something like `oc process -f service.yaml -f route.yaml` This is how Kubernetes does it. But when I do it with `oc process` I get only one of the templates outputted. Is this not possible in `oc`?

##### Version
```
oc v3.6.173.0.83
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://openshift
openshift v3.7.64
kubernetes v1.7.6+a08f5eeb62
```
##### Steps To Reproduce
`oc process -f deploymentconfig.yaml -f service.yaml`

##### Current Result
Only one of the resources is outputted

##### Expected Result
A complete list of the resources inputted

##### Additional Information
N/A

**Comment by soltysh** [comment]
It's not a bug, that's how this was originally written, though I agree we should allow multiple, changing to enhancement.

**Comment by the-zucc** [comment]
Just bumping this, this would be very useful. Something like a -R flag could be useful, for example for processing multiple templates at once and using the same param-file

**Comment by soltysh** [comment]
@adambkaplan fyi

**Comment by adambkaplan** [comment]
cc @dperaza4dustbit
