### ISSUE TITLE
How to automate builds on github releases

### ISSUE THREAD

**Issue by raduachim** [openshift/origin#21200]
Hi,

I've tried searching for this question but couldn't find an answer.
Basically I'm wondering how can my Openshift build receive the events from the github hook when a release is made and automatically build?
I've assumed I could use a Regex for the `ref` but that doesn't seem to work.

Is this something currently impossible to do and if so is there any plan to add this feature? 
(I don't think I know people that deploy a branch)

**Comment by matihost** [comment]
It is a problem not only for github triggers, but also bitbucket.

In a nutshell 

Please add support to  regex  (especially `*) wildcard for  `ref` 

Essentially what is recommended git flow with BuildConfigs?

Each feature branch  requires from developer:
- create BuildConfig with ref point to branch on OKD cluster
- create / point Webhook to new BuildConfig trigger URL

it is cumbersome - having regex allows to reuse one BuildConfig for many branches.

**Comment by bparees** [comment]
Currently our recommendation is to use a CI system to manage more complex build triggering logic like this.  E.g. use openshift's built in jenkins image to run a jenkins server, setup triggering against a jenkins job and have that jenkins job kick/create an appropriate openshift build parameterized in the way you need.

In the meantime this has been put on our backlog (not currently public but hopefully soon): https://jira.coreos.com/browse/DEVEXP-179
