### ISSUE TITLE
Decide which storage versions we want to keep in kube-apiserver

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#21239]
The old openshift start have the following tweaks for storage versions: 
- https://github.com/openshift/origin/blob/181c59be898a97317595a68dde5f1ff598c28a79/pkg/cmd/server/kubernetes/master/master_config.go#L171
- https://github.com/openshift/origin/blob/181c59be898a97317595a68dde5f1ff598c28a79/pkg/cmd/server/kubernetes/master/master_config.go#L199

which were caught when switching integration to the new setup in #21096:

```
etcd_storage_path_test.go:1034: GVK for apiregistration.k8s.io/v1, Kind=APIService does not match, expected apiregistration.k8s.io/v1beta1, Kind=APIService got apiregistration.k8s.io/v1, Kind=APIService
etcd_storage_path_test.go:1034: GVK for apiregistration.k8s.io/v1beta1, Kind=APIService does not match, expected apiregistration.k8s.io/v1beta1, Kind=APIService got apiregistration.k8s.io/v1, Kind=APIService
etcd_storage_path_test.go:1034: GVK for extensions/v1beta1, Kind=PodSecurityPolicy does not match, expected extensions/v1beta1, Kind=PodSecurityPolicy got policy/v1beta1, Kind=PodSecurityPolicy
etcd_storage_path_test.go:1034: GVK for policy/v1beta1, Kind=PodSecurityPolicy does not match, expected extensions/v1beta1, Kind=PodSecurityPolicy got policy/v1beta1, Kind=PodSecurityPolicy
```

Additionally we have this patch: https://github.com/openshift/origin/blob/181c59be898a97317595a68dde5f1ff598c28a79/pkg/cmd/server/origin/master.go#L130

which results in the following failure in the aforementioned switch:

```
etcd_storage_path_test.go:1023: failed to get from etcd for security.openshift.io/v1, Kind=SecurityContextConstraints: &errors.errorString{s:"no keys found for \"/kubernetes.io/securitycontextconstraints/scc2\""}
```

/assign @deads2k

**Comment by deads2k** [comment]
APIService - new version
PSP - new version

Still thinking about SCC.
