### ISSUE TITLE
It is impossible to use add-role-to-user to create a role with a different subject namespace

### ISSUE THREAD

**Issue by svenstaro** [openshift/origin#21316]
I have two projects `p1` and `p2`. I want to grant the `edit` role to a ServiceAccount `sa1` for `p2` which itself resides in project `p1`. I want to be able to do:

    oc policy add-role-to-user -n p2 edit -z sa1 --rolebinding-name sa1_edit --subject-namespace p1

However, this last flag is imaginary and doesn't exist. I want that flag.

I think this is an important oversight as granting permissions to roles in projects to other projects seems fairly basic to me.

##### Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server xxxx
openshift v3.11.16
kubernetes v1.11.0+d4cacc0

**Comment by aramalipoor** [comment]
To allow service account `sa1` of project `p1` to `edit` role in project `p2` we do something like:
```
oc policy add-role-to-user edit system:serviceaccounts:p1:sa1 -n p2
```

Is this what you're looking for?
