### ISSUE TITLE
osc login after token expiry

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#2132]
`osc login` works great, but once the token stored in `~/.config/openshift/config` expires, what is the process for logging in again?

Running `osc login` again returns:

    Login failed (401 Unauthorized)
    Unauthorized

With no prompting to re-authenticate.

**Comment by jimmidyson** [comment]
So it seems like now I can do `osc login` multiple times, but `~/.config/openshift/config` then contains multiple users, even for the same user name. The `current-context` is set to the latest user & osc commands work using that, but having multiple entries for the same user login, including expired tokens, is a bit smelly.

**Comment by fabianofranz** [comment]
@liggitt this is fixed in master.

**Comment by liggitt** [comment]
Fixed by #2226
