### ISSUE TITLE
[Feature Request] include one template in another (with/without parameter substitution)

### ISSUE THREAD

**Issue by amirmasud** [openshift/origin#21330]
A project may contain dependencies to other projects (e.g. a DB which another template exists to create it). Moreover, it may want to use a constant value for some parameters of DB template (e.g. need a specific version) or it may want the user select the parameter (e.g. version) from the new template too.

Is there any way to include one template into another one to address mentioned need?

##### Version
v3.10

**Comment by AliKarami** [comment]
any update on this?
it's very useful feature which can simplify pipelines.
