### ISSUE TITLE
OKD upgrade to v 3.11 fail when package origin-docker-excluder not found.

### ISSUE THREAD

**Issue by aawm** [openshift/origin#21344]
3 hosts cluster, 1 master/compute node and 2 compute nodes, centos 7, running OKD 3.10.
##### Version
oc version
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.origin.xxxx:3443
openshift v3.10.0+456651d-57
kubernetes v1.10.0+b81c8f8

##### Issue
Trying to upgrade OKD 3.10 cluster to 3.11, but it failed with the message "Package origin-docker-excluder not found", but it was installed. Seems like origin-docker-excluder v 3.11 is not in the repo yet.

 yum info origin-docker-excluder
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.its.sfu.ca
 * extras: mirror.layeronline.com
 * updates: mirror.layeronline.com
Installed Packages
Name        : origin-docker-excluder
Arch        : noarch
Version     : 3.10.0
Release     : 1.el7.git.0.0c4577e
Size        : 2.4 k
Repo        : installed
From repo   : centos-openshift-origin
Summary     : Exclude docker packages from updates
URL         : https://github.com/openshift/origin
License     : ASL 2.0
Description : Certain versions of OpenShift will not work with newer versions
            : of docker.  Exclude those versions of docker.
            :
            : origin-docker-excluder exclude - No major docker updates
            : origin-docker-excluder unexclude - docker packages can be updated

[provide a description of the issue]

[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jkroepke** [comment]
You have to add the CentOS PAAS Sig Test repo for the installation now.

```
openshift_additional_repos=[{'id': 'centos-okd-ci', 'name': 'centos-okd-ci', 'baseurl' :'http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin311/', 'gpgcheck' :'0', 'enabled' :'1'}]
```
See: https://lists.openshift.redhat.com/openshift-archives/dev/2018-October/msg00038.html
