### ISSUE TITLE
Pods Resolve All Non-Local Hostnames to the Default Router IP

### ISSUE THREAD

**Issue by blurtonator** [openshift/origin#21354]
All of my pods are resolving non-local hosts to the default router IP.

##### Version
oc v3.11.16
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server cluster.host.name:8443
openshift v3.11.16
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. Install OpenShift (I am using OpenShift-Enterprise)
2. Point *.default.domain at the desired router IP
3. Launch a Pod
4. Issue an nslookup for an external (non-local) host

##### Current Result
All non-local hosts are resolved to the default router's IP address
##### Expected Result
Non-local hosts should be resolved correctly.

##### Additional Information
origin-dns.conf:
```
no-resolv
domain-needed
no-negcache
max-cache-ttl=1
enable-dbus
dns-forward-max=10000
cache-size=10000
bind-dynamic
min-port=1024
except-interface=lo
# End of config
```

99-origin-upstream-dns.conf:
```
server=10.222.160.37
server=10.222.160.38
```

Host DNS output:
```
[root@ocp-master01 ~]# nslookup www.google.com
Server:         10.222.178.10
Address:        10.222.178.10#53

Non-authoritative answer:
Name:   www.google.com
Address: 173.194.219.99
Name:   www.google.com
Address: 173.194.219.103
Name:   www.google.com
Address: 173.194.219.104
Name:   www.google.com
Address: 173.194.219.106
Name:   www.google.com
Address: 173.194.219.147
Name:   www.google.com
Address: 173.194.219.105
```

Pod DNS lookup for external host(s):
Pod initiated with:  oc run --rm -i -t alpine-bash --image=bashell/alpine-bash --restart=Never '/bin/bash'
```
bash-4.4# nslookup www.google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      www.google.com
Address 1: 10.222.178.30

bash-4.4# nslookup github.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      github.com
Address 1: 10.222.178.30
```

**Comment by blurtonator** [comment]
This corresponds to an issue with the pod's /etc/resolv.conf searching the wildcard app domain. Fixed by removing it from the domain search line.

**Comment by tech-mint** [comment]
> This corresponds to an issue with the pod's /etc/resolv.conf searching the wildcard app domain. Fixed by removing it from the domain search line.

how should one do this for all pods in a Statefulset?
