### ISSUE TITLE
make update-deps fails - Error resolving imports

### ISSUE THREAD

**Issue by adambkaplan** [openshift/origin#21394]
Fails to resolve import `golang.org/x/text/language`

```
[DEBUG] Package golang.org/x/text/internal imports golang.org/x/text/language
[DEBUG] In vendor: golang.org/x/text/language
[DEBUG] Trying to open golang.org/x/text/internal/tag (/home/adkaplan/.glide/cache/src/https-golang.org-x-text/internal/tag)
[ERROR] Failed to retrieve a list of dependencies: Error resolving imports
```

Fuller [glide.log](https://github.com/openshift/origin/files/2534773/glide.log) attached.

@openshift/sig-master

**Comment by mfojtik** [comment]
`glide cc` ?

**Comment by adambkaplan** [comment]
did that :frowning_face:

**Comment by deads2k** [comment]
Works fine on my linux box.  You're on mac os right?  Try running it on a linux machine.

**Comment by adambkaplan** [comment]
I've switched to Fedora 28 (4.18 kernel though...)

**Comment by adambkaplan** [comment]
glide version v0.13.2

**Comment by bparees** [comment]
make update-deps also worked for me.  closing as this seems to be environmental.
