### ISSUE TITLE
How to pass Build Name in OKD binary build config?

### ISSUE THREAD

**Issue by imranrazakhan** [openshift/origin#21400]
I am building a image using binary BuildConfig, in every build a new image with the tag latest is created 
```
"output": {
 "to": {
    "kind": "ImageStreamTag"
    "name": "myImage:latest"
   }
}
```
I tried following commands

Following command is successfull and generate image like  "myImage:latest"
`oc start-build my-bc --from-file=my.tar.gz --follow=true`

tried to use --build-arg 
```
oc start-build my-bc --from-file=my.tar.gz --follow=true  --build-arg buildNumber=1.0.9
WARNING: Specifying build arguments with binary builds is not supported.
```
Try to use parameters
```
oc start-build my-bc --from-file=my.tar.gz --follow=true -p buildNumber=1.0.9
Error: unknown shorthand flag: 'p' in -p
```
tried to use environment variable
```
oc start-build my-bc --from-file=my.tar.gz --follow=true  --env=buildNumber=1.0.9
WARNING: Specifying environment variables with binary builds is not supported.
```
How i can pass parameter or environment variable to achieve below???
```
"output": {
 "to": {
    "kind": "ImageStreamTag"
    "name": "myImage:${buildNumber}"
   }
}
```
##### Version
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8

**Comment by ThomVivet** [comment]
/remove-lifecycle stale
Same issue for me, can't specify environment variables with binary builds (seems not supported)...

**Comment by Biboba** [comment]
Same for me.
Any workaround ?

Thanks

**Comment by ThomVivet** [comment]
Use `oc tag` and/or `oc annotate` after start-build finished...
Even better: generate a **.s2i/environment** file (with KEY=value lines). 
This file used by `start-build --from-dir` will sets the environment variables as you wish :-)

**Comment by toxsick** [comment]
This is very frustrating. Can anybody tell me why `WARNING: Specifying build arguments with binary builds is not supported.` is a thing?
