### ISSUE TITLE
Application on OpenShift Online are not accessible(STARTER PLAN ca-central-1) 

### ISSUE THREAD

**Issue by michaelcplusplus** [openshift/origin#21419]
Server: 193b.starter-ca-central-1.openshiftapps.com
openshift v3.11.16
kubernetes v1.11.0+d4cacc0

I can't access sporadically  my application on OpenShift Online (STARTER PLAN ca-central-1). But the pod is still running normally.

The malfunction has been frequent for a week now. 

The first access to the application usually fails. The second access then usually works again.

**Comment by skjolber** [comment]
I also have this problem. Basically the starter is dead in the water and useless.
