### ISSUE TITLE
openshift/openvswitch image for version okd 3.11 is missing

### ISSUE THREAD

**Issue by yuanlinios** [openshift/origin#21418]
there is no v3.11.0 or v3.11 tag for docker.io/openshift/openvswitch image. Is this image still needed for OKD 3.11?

**Comment by jkroepke** [comment]
I looks like its not used already in v3.10.

See also: https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/openshift3/openvswitch

I also can not see it in my 3.10 installation. Since the Container `openvswitch` runs the origin-node image.

**Comment by yuanlinios** [comment]
thanks. The deployment is successful without this image
