### ISSUE TITLE
Template json files have newlines double-escaped

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2141]
Seeing `\\n` in files like application-template-stibuild.json

**Comment by bparees** [comment]
double escapes appear to be required for json format so certs end up with newlines in the right place.
https://github.com/openshift/origin/blob/master/pkg/route/registry/route/rest.go#L154

(please reopen if you read that differently than me)

**Comment by bparees** [comment]
more background:
https://code.google.com/p/v8/issues/detail?id=616

**Comment by liggitt** [comment]
we want newlines encoded in the JSON. `"foo":"bar\nbaz"` is the right way to do that.

**Comment by liggitt** [comment]
for spec compliance, see the JSON "string" definition at http://json.org/

You can't embed a literal newline (because it's a control character), but a string can include an escaped newline, (e.g. `\n`)

**Comment by liggitt** [comment]
The example on the code.google.com site is misleading. See the comment: https://code.google.com/p/v8/issues/detail?id=616#c2

The first step is to construct the string you want to parse, like this:
```
var s = '{"test":"test\\ntest"}';
```
Because JavaScript is interpreting the string, `\\n` becomes `\n` in the string. That is equivalent to loading a JSON file with the content:
```
{"test":"test\ntest"}
```

You can then pass it to `JSON.parse(...)`

**Comment by bparees** [comment]
thanks for the clarification.

**Comment by bparees** [comment]
@liggitt you still want this open for @pweil- 's updates?

**Comment by liggitt** [comment]
no, I'll spawn a lower priority one
