### ISSUE TITLE
okd 3.11 oc cluster up --metrics --logging failed

### ISSUE THREAD

**Issue by Jooho** [openshift/origin#21445]
[provide a description of the issue]
The latest oc version does not have --metrics --logging flags

how to deploy metrics and logging?

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1.oc cluster up --metrics --logging

##### Current Result
Error: unknown flag: --metrics

##### Expected Result
deploy metrics

**Comment by Drakkai** [comment]
This is because of openshift/origin#19209
