### ISSUE TITLE
canceled builds is still showing running icon

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#2144]
osc v0.5-117-gd6036ef
kubernetes v0.16.2-338-gc07896e

running `osc cancel-build` cancels the build and status label gets updated but the icon is still the animated running icon.

![build-cancel-icon](https://cloud.githubusercontent.com/assets/727196/7543037/7d9370a4-f58f-11e4-979e-c164b93cb955.png)

also on the overview page, the canceled build looks like a running build

![canceled-builds-overview](https://cloud.githubusercontent.com/assets/727196/7543283/3e2b62c6-f591-11e4-87fe-0e5d3c0aa4a1.png)

/cc @spadgett

**Comment by spadgett** [comment]
@liggitt please assign to me. I have a fix.
