### ISSUE TITLE
deployments are listed oldest first, opposite of builds

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#2145]
I'd recommend having the most recent at the top.  Also would be nice if the status was a bit more obvious to the casual viewer, icon and/or color to accompany the label.  A nice summary like Jenkins has is helpful: last successful and last failure.  Would be good if consistent between build and deploy pages <endofrant/>

![deployment-order](https://cloud.githubusercontent.com/assets/727196/7543119/2348a5aa-f590-11e4-954b-b38c48c995d5.png)

/cc @spadgett

**Comment by smarterclayton** [comment]
The deployment page should look more like osc status (and osc describe dc, although that needs another pass to clean it up.)

**Comment by spadgett** [comment]
Fixed by #2178.
