### ISSUE TITLE
Web console scaling with large #'s of builds and deployments

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#2146]
Currently the web console shows _ALL_ builds and deployments.  I would assume if someone wasn't properly pruning their build and deploy history over time this would cause the UI performance to take a hit.  I have only done some local testing, might be good to see if test org can do some UI scale testing.

/cc @spadgett

**Comment by liggitt** [comment]
@derekwaynecarr is looking at pruning
The API doesn't support pagination, so pruning will be necessary. Even if we hid some of the builds/deployments in the UI, there would still be performance issues loading them all. I'd rather leave the issue visible and make sure the pruning is happening.

**Comment by spadgett** [comment]
@liggitt @derekwaynecarr Should we add paging the to the API? We might also tell users in the web console how to prune old builds.

**Comment by liggitt** [comment]
> should we add paging

Yes, we should (and sorting), but to every list op in a consistent way, which is a much bigger change (involves upstream, etc)

**Comment by spadgett** [comment]
@liggitt So nothing to do?

**Comment by spadgett** [comment]
#4177 hides old deployments behind a show more link, and #3812 hides old builds under a show more link.

**Comment by spadgett** [comment]
This is arguably problem again now that we've updated the browse pages. The browse pages for deployment configs and build configs show all deployments and all builds in a table, although it should scale better than the tile view we used before.

We could add paging to the tables, but we'd still be getting all the data from the server.

**Comment by jwforres** [comment]
Moving this to trello https://trello.com/c/b3QnayXY
