### ISSUE TITLE
x86_64 static pods deployed on aarch64

### ISSUE THREAD

**Issue by TheMysteriousX** [openshift/origin#21467]
Opening a ticket here as suggested in openshift/openshift-ansible#10668

It seems that kubelet is getting deployed properly, but it's pulling down static pod images for x86_64 rather than aarch64. It was indicated in the above ticket that this may be because there is not a static pod image targetting aarch64.

```
[root@atl-master-001 origin]# file /var/lib/docker/overlay2/c64c7436a38c62ec4089299c3ea2c821fba138b36270dcdb75bd568f87ed3040/diff/usr/local/bin/etcd
/var/lib/docker/overlay2/c64c7436a38c62ec4089299c3ea2c821fba138b36270dcdb75bd568f87ed3040/diff/usr/local/bin/etcd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=6a1521c44ad9f095d4f476fc93abf963843ddaeeA, stripped
[root@atl-master-001 origin]# uname -a
Linux atl-master-001.osc.redacted 4.18.16-300.fc29.aarch64 #1 SMP Sat Oct 20 23:12:22 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```

Please see the linked ticket for log files and debug output.

##### Version
```
# oc version
oc v3.11.0-rc.0+0cbc58b
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
Use the ansible playbooks to deploy a cluster onto aarch64

##### Current Result

Playbook fails to run to completion as the static pods do not start up due to the wrong CPU being targetted. The failure is silent.

##### Expected Result

Static pods for the correct arch should be deployed.

##### Additional Information
API is not running, so additional information via `oc` is not available.

**Comment by adam-bishop** [comment]
/remove-lifecycle stale

I tested this again last week, and origin is still not usable on atomic aarch64.

**Comment by TheMysteriousX** [comment]
/remove-lifecycle stale

I tested this again last week, and origin is still not usable on atomic aarch64.

**Comment by rmandrad** [comment]
same on May - still no aarch64 images
