### ISSUE TITLE
oc client 3.9.0 running on windows rsync does not follow symbolic links for a container in Linux. 

### ISSUE THREAD

**Issue by jjwallaby** [openshift/origin#21498]
[provide a description of the issue]
when want to copy all files in a container folder (that is linux based) both rsync and  --strategy="tar"
to a windows FOLDER it does not follow symbolic links like the native rsync command does -L.  How to force follow symbolic links ?
##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://xxxxxx
openshift v3.9.33
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1.  oc rsync containername:/opt/src/app .

##### Current Result
ERROR: Error extracting link "app/node_modules/.bin/JSONStream": symlink ..\JSONStream\bin.js app\app\node_modules\.bin\JSONStream: A required privilege is not held by the client.
ERROR: Error extracting tar stream
Ignoring the following flags because they only apply to rsync: --no-perms
error: error extracting tar at destination directory: symlink ..\JSONStream\bin.js app\app\node_modules\.bin\JSONStream: A required privilege is not held by the client.
##### Expected Result
able to copy files that are links and create them.  
##### Additional Information
pwd
/opt/src/app/node_modules
cd .bin
pwd
/opt/src/app/node_modules/.bin
ls -l
total 0
lrwxrwxrwx    1 root     root            20 Oct 15 11:55 JSONStream -> ../JSONStream/bin.js

pwd
/opt/src/app/node_modules/.bin
ls -lL JSONStream
-rwxr-xr-x    1 root     root           251 Oct 14 01:23 JSONStream
ls -l  JSONStream
lrwxrwxrwx    1 root     root            20 Oct 15 11:55 JSONStream -> ../JSONStream/bin.js
cd ../JSONStream
pwd
/opt/src/app/node_modules/JSONStream
ls -l
total 36
-rw-r--r--    1 root     root           586 May 22 22:38 LICENSE.APACHE2
-rw-r--r--    1 root     root          1088 May 22 22:38 LICENSE.MIT
-rwxr-xr-x    1 root     root           251 Oct 14 01:23 bin.js
drwxr-xr-x    2 root     root            25 Oct 15 11:55 examples
-rwxr-xr-x    1 root     root          5466 Oct 14 01:23 index.js
-rw-r--r--    1 root     root          1824 Oct 15 11:55 package.json
-rw-r--r--    1 root     root          5722 May 22 22:38 readme.markdown
drwxr-xr-x    3 root     root          4096 Oct 15 11:55 test

[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by vmartico** [comment]
/remove-lifecycle rotten

Same issue here:
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
openshift v3.9.0+ba7faec-1
