### ISSUE TITLE
oc cluster not working on mac anymore

### ISSUE THREAD

**Issue by kylearctiq** [openshift/origin#21512]
Can't run oc cluster up anymore with the latest oc client

Temps-MacBook-Pro:Downloads kyle.bassett$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

docker version
Version 18.06.1-ce-mac73 (26764)

[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
Temps-MacBook-Pro:Downloads kyle.bassett$ oc cluster up --public-hostname 192.168.2.42
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Using public hostname IP 192.168.2.42 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking prerequisites for port forwarding ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I1116 22:36:40.112147    9765 config.go:40] Running "create-master-config"
I1116 22:36:42.858285    9765 config.go:46] Running "create-node-config"
I1116 22:36:44.475045    9765 flags.go:30] Running "create-kubelet-flags"
I1116 22:36:45.512840    9765 run_kubelet.go:49] Running "start-kubelet"
Error: error creating node config: could not create OpenShift configuration: cannot start container e6a79f7d2d35bb25b4fe373b41fb46d18104ecadd97b2f383d11dbee9a64d83b; caused by: cannot start container e6a79f7d2d35bb25b4fe373b41fb46d18104ecadd97b2f383d11dbee9a64d83b
Temps-MacBook-Pro:Downloads kyle.bassett$

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by adambkaplan** [comment]
`cluster up` for 3.11 is not supported on macOS directly. Use [minishift](https://www.okd.io/minishift/) instead to run 3.11 clusters on mac. FWIW `cluster up` does not exist in OpenShift 4.0.

@openshift/sig-master have we updated the okd docs so that it's clear `cluster up` is not supported on mac?

**Comment by gustavonalle** [comment]
indeed. Nothing was easier than doing a ```oc cluster up``` and having a single node cluster running. Minishift setup is not as simple and it involves virtualization https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#for-linux
