### ISSUE TITLE
enable running rootless podman inside a pod

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#21514]
We would like to run rootless podman containers inside openshift pods so that we can take advantage of openshift's scheduling superpowers and have access to a root environment (via user namespacing) from a pod.

We are tracking podman work for this in here: https://github.com/containers/libpod/issues/1092

In the current iteration, the blocker is that openshift is dropping `cap_set_{uid,gid}` capabilities which podman needs to construct a user namespace.

What would be the best way to solve this issue? Can a solution for this land in the default SCC?

##### Version
```
oc v3.11.0+0cbc58b
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
https://github.com/TomasTomecek/rootless-podman-in-openshift

**Comment by cgwalters** [comment]
See also https://github.com/projectatomic/bubblewrap/issues/284

For Kubernetes/OpenShift this also blocks on user namespaces https://github.com/kubernetes/enhancements/issues/127

**Comment by jamescassell** [comment]
Fixed, or no longer desired?

**Comment by TomasTomecek** [comment]
I'm no longer interested in this so I closed. Feel free to open a new one. (I think that it could possibly work with --isolation chroot)
