### ISSUE TITLE
Need to be able to easily delete everything that comes out of a template

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2152]
Need to be able to easily delete everything that comes out of a template
- that includes pods, which means delete of RC doesn't quite do what we want

**Comment by liggitt** [comment]
extracted from #718

**Comment by smarterclayton** [comment]
Delete all -l template=foo

**Comment by liggitt** [comment]
What does `all` mean here? Will that handle any object type created from the template? Will that handle generated names? Do we automatically label things created from a template, or do you have to have the foresight to apply a label when creating?

**Comment by smarterclayton** [comment]
> On May 11, 2015, at 10:54 AM, Jordan Liggitt <notifications@github.com> wrote:
> 
> What does all mean here? Will that handle any object type created from the template?
> 
In practical terms, yes.
> Will that handle generated names?
> 
No.
> Do we automatically label things created from a template, or do you have to have the foresight to apply a label when creating?
> 
Templates can automatically label themselves.  That's the primary mechanism.

**Comment by liggitt** [comment]
> In practical terms, yes.

So, no? :)

**Comment by smarterclayton** [comment]
In theory no, in practice yes.

----- Original Message -----

**Comment by smarterclayton** [comment]
Consider this fixed.
