### ISSUE TITLE
Vagrant box fedora_20_latest.box is missing

### ISSUE THREAD

**Issue by rhuss** [openshift/origin#2153]
When using Vagrant with `$OPENSHIFT_DEV_CLUSTER=1` it [references](https://github.com/openshift/origin/blob/master/Vagrantfile#L122) an URL https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_20_latest.box
which does not exist anymore (but according to Google cache happened to exist)

**Comment by liggitt** [comment]
Might be fixed by #2149

**Comment by rhuss** [comment]
Thanks, works for me now.
