### ISSUE TITLE
provide working example for CLI how to use Git secrets

### ISSUE THREAD

**Issue by peterducai** [openshift/origin#21537]
there is no clear and working example how to check out git from CLI (which is needed for our Gitlab automation). Any manual steps (editing yaml and so on) is NO GO as we're talking about automation

##### Version

oc v3.11.0+0cbc58b
kubernetes v1.10.0+d4cacc0

openshift v3.10.0+456651d-57
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce

```
oc secrets new-sshauth gitlab-key-rsa --ssh-privatekey=/home/peter/.ssh/id_rsa_gitlab_deploy_okd
oc secrets link builder gitlab-key-rsa
oc get bc
oc set build-secret --source bc/ignore11111 gitlab-key-rsa
oc start-build bc/ignore11111
oc logs build.build.openshift.io/ignore11111-2

Cloning "git@xxx/okd_cli_devtool.git" ...
error: Warning: Permanently added 'xxx,301.122.22.4' (ECDSA) to the list of known hosts.
GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```
```
oc patch bc/ignore11111 -p '{"spec":{"source":{"sourceSecret":{"name":"gitlab-key-rsa"}}}}'
oc start-build bc/ignore11111
oc logs build.build.openshift.io/ignore11111-3

Cloning "git@xxx/okd_cli_devtool.git" ...
error: Warning: Permanently added 'xxx,301.122.22.4' (ECDSA) to the list of known hosts.
GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

##### Expected Result

clone of Git repo and following build.

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]

```
Info:  Output from the diagnostic pod (image openshift/origin-deployer:v3.11.0):
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected
              
       Info:  Service account token successfully authenticated to master
       Info:  Service account token was authenticated by the integrated registry.
       
       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected
              
       [Note] Summary of diagnostics execution (version v3.11.0+0323629-61):
       [Note] Completed with no errors or warnings seen.
       
[Note] Summary of diagnostics execution (version v3.11.0+0cbc58b):
[Note] Completed with no errors or warnings seen.
```

[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by peterducai** [comment]
any info on this?

**Comment by bparees** [comment]
I assume you've been through https://docs.okd.io/latest/dev_guide/builds/build_inputs.html#source-clone-secrets

your steps look generally correct to me, i'd double check that the credentials you're providing in the secret actually work to clone the repo in question.

running the build with --build-loglevel=5 may also provide more insight about whether your credentials are being picked up and used during the clone.
