### ISSUE TITLE
EgressNetworkPolicy maximum number

### ISSUE THREAD

**Issue by AlerantAppNGIN** [openshift/origin#21532]
Hi!

We would like to add egress network policies to our projects.
However, we have run into the problem, that only 50 policies are allowed for a project.
So far, I have found that it is not configurable, and it is not mentioned in the following article:
[https://docs.openshift.com/container-platform/3.11/scaling_performance/cluster_limits.html#scaling-performance-cluster-limits](https://docs.openshift.com/container-platform/3.11/scaling_performance/cluster_limits.html#scaling-performance-cluster-limits)

Is there a reason for this restriction?
Do you have a solution for this?

##### Version
`oc v3.11.0+0323629-61`
`kubernetes v1.11.0+d4cacc0`
`features: Basic-Auth GSSAPI Kerberos SPNEGO`

##### Steps To Reproduce
Add an egress policy json file with more than 50 rules.

**Comment by krejkrejkrej** [comment]
I've also run in to this issue, and am interested in a higher policy limit.

**Comment by barabali** [comment]
In the end I did this change in the linked commit, then built openshift and used the generated base image:
https://github.com/barabali/origin/commit/3b919934c15f66a3d03d08ae40a3cc9e4a0082ce
