### ISSUE TITLE
Pods fail to start if defining args and not command

### ISSUE THREAD

**Issue by bigon** [openshift/origin#21547]
Hi,

I'm trying to pass an argument to the entrypoint.

Reading the k8s and openshift documentation it seems that I need to pass an "args" array with my arguments in the pod in deployementconfig.

The [k8s documentation](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/) says that: "The command and arguments that you define in the configuration file override the default command and arguments provided by the container image. If you define args, but do not define a command, the default command is used with your new arguments."

But if I'm not defining a command it seems that openshift is trying to start my parameter instead of the executable: `container_linux.go:247: starting container process caused "exec: \"--first_arg=foo\": executable file not found in $PATH"`

If I'm explicitly setting the command or adding the command as arg0 the container starts

##### Version
oc v3.10.45
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Edit the deployment config
2. Add an "args" array in the pod configuration

##### Current Result
The pods fails to start because it's trying to exec the arg0

##### Expected Result
The entrypoint defined in the pod is use and the arguments defined in the dc are passed to it

##### Additional Information
I'm using an image based on the redhat openjdk 1.8 one

**Comment by jwforres** [comment]
@bigon it will likely help if you can provide an example of what your DC definition looks like, at least for the pod spec

@openshift/sig-pod

**Comment by bigon** [comment]
[template.txt](https://github.com/openshift/origin/files/2624062/template.txt)

**Comment by sjenning** [comment]
it is likely that that container image does not have an entrypoint set.  you can check the entrypoint for the image with `docker inspect <image-pull-spec> | grep -A3 Entrypoint`

If the entrypoint is null, then then the first argument is used as the command.

**Comment by bigon** [comment]
Indeed the Entrypoint is null

So that's different from what k8s is doing?

**Comment by sjenning** [comment]
It is kinda complex.

Kubernetes `command` in the pod spec is basically an "entrypoint override" similar to `docker run --entrypoint`.  Kubernetes `args` in the pod spec are arguments to either then image entrypoint or the `command`.  If no image entrypoint or kubernetes `command` is provided, then the first arguement of `args` is the command.
