### ISSUE TITLE
Cluster Up/Down document is missing

### ISSUE THREAD

**Issue by lveyde** [openshift/origin#21553]
[A cluster up/down document that was available at https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md got missing]

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [Try to open https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md]

##### Current Result
The document is missing.

##### Expected Result
The document should be available or at least to point to the new location.

**Comment by jwforres** [comment]
@mfojtik @derekwaynecarr second bz/issue i've seen today about this doc missing, people are expecting it to be there, should we put in a tombstone or something

**Comment by matihost** [comment]
...after digging it was removed  on 14NOV with this commit:

https://github.com/openshift/origin/commit/f1206f2e637b4cc958fc7ef7dfca0015f43deb58#diff-e3e2a9bfd88566b05001b02a3f51d286

intention was to favor 
https://github.com/openshift/installer to start cluster
but main readme.md still shows that oc cluster up is to be used to start the cluster.

and 
https://github.com/openshift/installer show that it needs KVM to start openshift.
so essentially it differs from what 'oc cluster up' does .

so the question is - whether it is possible to start local OKD cluster w/o virtualization.

**Comment by matihost** [comment]
It would be nice if OpenShift / OKD 4.x supports local development  with OpenShift and not require virtualization, AWS deployment etc - like it was possible with OKD 3.x

**Comment by AndrewMorsillo** [comment]
I'm just starting to explore OpenShift and I've run into a bunch of confusion and inconsistent documentation. How do I start a local cluster? Do I use `oc cluster up`? Do I use `openshift/installer`? Do I use `oc-cluster-wrapper`? I've seen pointers to all three of those in various documentation. This is very confusing for people new to OpenShift.

**Comment by devops-csaa** [comment]
Give up and go somewhere else

**Comment by devops-csaa** [comment]
The best documentation for OKD is often found in archive.org - thanks
cluster_up_down.md  is at:
https://web.archive.org/web/20180925151411/https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md

**Comment by magick93** [comment]
> It would be nice if OpenShift / OKD 4.x supports local development with OpenShift and not require virtualization, AWS deployment etc - like it was possible with OKD 3.x

If this is what RedHat expects people to do then they should expect an exodus of users. `oc cluster up` is extremely useful. And the ansible approach to installing is also very good. Its a shame what they are doing.

**Comment by erickhagstrom** [comment]
I'm working through the O'Reilly book, _DevOps with OpenShift_. It guides readers through the **oc cluster up** process, and references the subject document (_cluster_up_down.md_). If you don't want people to use that process any more, that's cool, but please provide SOME document called _cluster_up_down.md_ so that people can learn about the new process when they come here looking for the old one. As things stand, one must do a bit of research just to find this issue. And eventually this issue will go away.

Thanks

**Comment by matihost** [comment]
My research update:
okd 3.11 is more than 1 year old and no more releases - forget about it
okd 4.x is alpha - openshift-intaller - aka cloud only installer

For local usage only OCP 4.x  - only with embedded VM : https://code-ready.github.io/crc/ - for Ubuntu requires customization: https://github.com/code-ready/crc/issues/917#issuecomment-573460297

However it  requires  spawning VM, it needs additional ~10 GB RAM just to run it and 27 GB storage, but it is full OpenShift with operators, dashboard, etc.

If you need something smaller - try minikube with "none" provider (aka no VM)  or microk8s - but it will differ from OpenShift a lot.

if you need similar to OCP stack (k8s with crio, podman, buildah stack), run minikube with crio as container engine - however it is challenging to run (and minikube warns that it is not tested config permutation).

I was able to run it with tons of workaround: https://github.com/matihost/learning/blob/master/k8s/minikube/start-minikube.sh - in case you want to minikube w/o VM with crio as container engine (works under Ubuntu).  Of course it has no operators, okd dashboard, htpasswd authen  etc.

**Comment by magick93** [comment]
You can find the `oc cluster up` docs at https://github.com/openshift/origin/blob/release-3.11/docs/cluster_up_down.md
