### ISSUE TITLE
x509: certificate signed by unknown authority error trying to deploy from private and secured registry

### ISSUE THREAD

**Issue by serrodcal** [openshift/origin#21560]
I am getting x509: certificate signed by unknown authority error trying to deploy from private and secured registry.

##### Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. ~$ oc cluster up
2. ~$ oc new-app own.registry.net/mbcdaas/kafka:1.1.0 

##### Current Result
W1128 08:44:02.920358   29186 dockerimagelookup.go:233] Docker registry lookup failed: Get https://own.registry.net/v2/: x509: certificate signed by unknown authority
W1128 08:44:02.945790   29186 newapp.go:479] Could not find an image stream match for "own.registry.net/mbcdaas/kafka:1.1.0". Make sure that a Docker image with that tag is available on the node for the deployment to succeed.
--> Found Docker image d5a60dc (4 months old) from own.registry.net for "own.registry.net/mbcdaas/kafka:1.1.0"

    * This image will be deployed in deployment config "kafka"
    * Ports 2181/tcp, 8778/tcp, 9092/tcp, 9779/tcp will be load balanced by service "kafka"
      * Other containers can access this service through the hostname "kafka"
    * WARNING: Image "own.registry.net/mbcdaas/kafka:1.1.0" runs as the 'root' user which may not be permitted by your cluster administrator

--> Creating resources ...
    error: deploymentconfigs.apps.openshift.io "kafka" already exists
    service "kafka" created
--> Failed

##### Additional Information

I need to pull image from a private and secure registry. How can I configure ca.crt to be able to pull and to deploy images?

**Comment by albertoclarit** [comment]
same issue... ib my case... the pods dont trust other certificates

**Comment by dmage** [comment]
https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#trusting-registries

Does this solve the problem?

**Comment by albertoclarit** [comment]
I encounter this problem when our internal dns catch all https request to point to  the openshift master...

**Comment by denikaryadi-2606** [comment]
Hi Bro.. This issue same as with my problem.
Openshift cannot import-image for nexus repository, the sintax is
_oc import-image nexus-coba:3.5 --from=192.168.250.250:8083/node-nexus --confirm_
error: tag latest failed: Internal error occurred: Get https://192.168.250.250:8083/v2/: x509: certificate signed by unknown authority
imagestream.image.openshift.io/nexus-coba imported with errors
This Solution only add **--insecure** after --confirm.

_oc import-image nexus-coba:3.5 --from=192.168.250.250:8083/node-nexus --confirm --confirm_
