### ISSUE TITLE
oc version check

### ISSUE THREAD

**Issue by fgiloux** [openshift/origin#21585]
This issue is to follow up the discussion started with the PR here: https://github.com/openshift/origin/pull/21505

@soltysh, when you write: "If you want to perform such check it should be handled server-side, such that every request gets verified if it passes minimum required version." do you mean that every single request to the API server should go through the check? This would add unnecessary latency and load for a check that is to provide an advice, wouldn't it? Provided you mean only the login requests this check does not belong IMHO to the endpoint used for requesting a token, which also does not have the client version passed by at the time being. In that case it would be necessary to extend the API for this additional check. This would however require the client to be modified for making the extra call and/or passing the client version which conflicts with your next statement: "This will allow for a centralized control over this requirement and enforce all oc to be upgraded immediately rather then only when they actually run a newer version that has that check".
What am I missing? How do you see the implementation?

Thanks,

Frédéric

**Comment by soltysh** [comment]
Have a look at https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook which should do exactly what you're looking for. As for passing the client version, it's part of `User-Agent` header (see https://tools.ietf.org/html/rfc7231#page-46), it's something like `User-Agent: oc/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0` when you combine the two you should be able to achieve what you're looking for.

**Comment by fgiloux** [comment]
I have now had time to look at that again. If I am not mistaken validating admission webhooks either accept or reject the request. It is black or white. I haven't found a way to accept the request but still return a warning. Also IMHO the check should only happen once per session. Rejecting the request is already implemented here: https://docs.openshift.com/container-platform/3.11/install_config/configuring_authentication.html#configuring-user-agent
I haven't seen it however in use at companies deploying OpenShift. In many companies I have been at developers have constrained work stations: they cannot install whatever software they want. That combined with the fact that OpenShift users are spread over many departments and that the distribution of the oc client is not automated may just prevent them of working if queries with old oc clients are rejected. It is surely better for them not to have access to newer functionalities but still be able to work and just be notified by a warning that something should be done (which may take weeks). This was the intent of my PR.
