### ISSUE TITLE
openshift master port 8443 unstable

### ISSUE THREAD

**Issue by zhaoshenhao** [openshift/origin#21645]
Hi Guys,

I got a strange issue. The master port 8443 is unstable. I verified the api and web console container are running. I tried curl inside the container. On the master node, the port 8443 disappears randomly. Restarting the host will bring back the port. But after a while, it's gone again. Sometime, it comes back. Even in the installation procedure, it's gone. And installation failed. I need to try many times and finally get everything installed by luck.

Is there any clue or any way to debug this issue?

##### Version
openshift v3.11.0+62803d0-1
I also tried 3.10, same problem.

##### Steps To Reproduce
1. Restart the master node
2. Try different oc commands, it will finally fail

oc get nodes
The connection to the server xyz.abc.com:8443 was refused - did you specify the right host or port?

netstat -an | grep 8443
Nothing displayed

##### Additional Information
oc adm diagnostics failed due to 8443 port is not open.

hosts file

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
os_firewall_use_firewalld=True
openshift_additional_repos=[{'id': 'centos-okd-ci', 'name': 'centos-okd-ci', 'baseurl' :'https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin311/', 'gpgcheck' :'0', 'enabled' :'1'}]
ansible_ssh_user=root
openshift_deployment_type=origin
openshift_enable_excluders=false
openshift_enable_docker_excluder=false
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

# Other
openshift_docker_disable_push_dockerhub=true

openshift_disable_check=memory_availability,disk_availability

[masters]
tpaas0.mycompany.com

[etcd]
tpaas0.mycompany.com

[nodes]
tpaas0.mycompany.com openshift_node_group_name='node-config-master'
tpaas1.mycompany.com openshift_node_group_name='node-config-infra'
tpaas2.mycompany.com openshift_node_group_name='node-config-compute'
tpaas3.mycompany.com openshift_node_group_name='node-config-compute'
tpaas4.mycompany.com openshift_node_group_name='node-config-compute'

**Comment by koksj** [comment]
I have had the same experience, having been trying to complete the install for almost a month now with no luck.  Tried many different approaches and inventory files. Also tried Grant Shipley's  install script. It always end with the same problem:

The connection to the server xyz.abc.com:8443 was refused - did you specify the right host or port?

**Comment by Juancarlosmartin10** [comment]
Same problem

**Comment by akash-prajapati** [comment]
Any alternative or luck? We are facing same issues with CentOS & RedHat subscription based setup.

**Comment by koksj** [comment]
After many hours trying and failing I managed to complete a successful installation on Openstack Rocky with 4 Centos VM's using image CentOS-7-x86_64-GenericCloud-1809.

In the hope it might help someone here is my  install steps and  inventory file.

[okd-3.11-install.txt](https://github.com/openshift/origin/files/2677510/okd-3.11-install.txt)
[okd-3.11-inventory.ini.txt](https://github.com/openshift/origin/files/2677516/okd-3.11-inventory.ini.txt)

**Comment by vitruxv** [comment]
> After many hours trying and failing I managed to complete a successful installation on Openstack Rocky with 4 Centos VM's using image CentOS-7-x86_64-GenericCloud-1809.
> 
> In the hope it might help someone here is my install steps and inventory file.
> 
> [okd-3.11-install.txt](https://github.com/openshift/origin/files/2677510/okd-3.11-install.txt)
> [okd-3.11-inventory.ini.txt](https://github.com/openshift/origin/files/2677516/okd-3.11-inventory.ini.txt)

Worked like a champ for me! Thanks a ton

**Comment by barleyer** [comment]
I think master api log will help a lot.

**Comment by sidd-harth** [comment]
Hi guys, even I am facing the same issue in 3.10
I am using `oc cluster up` cmd to start the instance.

I do not want to use ansible scripts, did anyone find a workaround for this issue with oc cluster up?
@imcsk8 

I tried this in CentOS. Is there any other OS(Ubuntu/RHEL?) where this error does not occur?

**Comment by perelengo** [comment]
/remove-lifecycle stale
Still happens to me.
