### ISSUE TITLE
"+" sign in path running "cluster up" causes the openshift/origin-node to exit

### ISSUE THREAD

**Issue by lholmquist** [openshift/origin#21643]
[provide a description of the issue]

I was trying to run a "oc cluster up" and i kept getting stalled at the "kube-api-server is starting" section.  I noticed that there were no docker containers running after doing a "docker ps".  So i did a "docker ps -a" and saw that the "openshift/origin-node:v3.11 " image had exited.

Looking at the logs for that image, it looked like the `hyperkube` command that it was running failed because of some bad options that it was passed.  You can see that in this gist, https://gist.github.com/lholmquist/822e0c47f1711b9b2e67b1f110f77683

Upon further inspection of that container, https://gist.github.com/lholmquist/513453c7c629dc19f31eafeb4de9c7ea, i noticed that the `--root-dir` options was enclosed in double quotes.  the directory i was running this in had a `+` in the path, so i think whatever `oc` does to setup this command, is escaping that `+` which then messes up the call to `hyperkube`

possibly this is a bug. I've stopped adding a `+` in my path so everything will work. Just wanted to report this. 

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. `mkdir some_dir_with+in_it`
2. `oc cluster up`

##### Current Result

https://gist.github.com/lholmquist/d77a7c1d80fed088dd9db0cc8069ae88

##### Expected Result

successfully bring up an openshift cluster

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by imcsk8** [comment]
This seems like a bug, i've managed to reproduce it
