### ISSUE TITLE
Web console showing build pods

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2166]
Looks like a timing issue: if the pods response comes back before the builds response when loading the overview, we don't properly filter out build pods.

CC @liggitt

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7570708/341f9efe-f7e0-11e4-82c0-3774f45220a9.png)

**Comment by liggitt** [comment]
#2168 will add an `openshift.io/build.name` annotation to build pods, which we should use instead of correlating with builds
