### ISSUE TITLE
Error message is wrong when login is timed out

### ISSUE THREAD

**Issue by Masterxilo** [openshift/origin#21673]
Apparently my login was timed out so I had to do "oc login" again.

But before that, "oc logs --version 3 dc/... -n ..." just indicated "error: resource type dc not known" instead of pointing out to me that I maybe should try to log in again...

**Comment by imcsk8** [comment]
Do you have a log snippet?
How did you make sure that your login timed out?
Were you able to reproduce the problem?

**Comment by Masterxilo** [comment]
Well I was mainly pointing out that resource type dc is not known is never a correct error message anyways, because that resource type must exist on a valid connection. So the error should have been indicating a connection problem.
