### ISSUE TITLE
OpenShift should automatically verify signatures on images during pod deployments.

### ISSUE THREAD

**Issue by ServerNinja** [openshift/origin#21689]
OpenShift should automatically verify signatures on images during pod deployments. Unfortunately, it doesn't see to be possible.

Also as I re-read documentation, it seems to not be supported either (correct me if I'm wrong)... As stated here: https://docs.openshift.com/container-platform/3.9/admin_guide/image_signatures.html#importing-signatures-from-sigstore

> "Signatures imported automatically by OpenShift Container Platform will be unverified by default and will have to be verified by image administrators."

It seems like it would be good if OpenShift actually did automatically verify signatures. Automation behind the verification of signatures as images are pulled for pod deployments would be very valuable for ensuring good security practices in the pipeline. 

Currently, regardless of whether an image has a signature or not, the image is pulled and deployed and never verified against signatures. Having to verify this manually (`oc adm verify-image-signature` command) doesn't seem to be very useful for automation and prevention of unwanted and / or compromised docker images from being deployed to pods. 

##### Version
```
$ oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://a-dev-osemaster-int.dev.bluescape.com:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
Scenario 1:
Sign image and push to atomic registry in OpenShift
OpenShift notices new container and rolls out new deployment.

Scenario 2:
Push an unsigned image to atomic registry in OpenShift
OpenShift notices new container and rolls out new deployment.

##### Current Result
Scenario 1: Pod successfully rolls out new deployment using the signed image
Scenario 2: Pod successfully rolls out new deployment using the unsigned image

Note that in both scenarios, the image is rolled out because OpenShift doesn't verify the signatures as part of its rollout process.

##### Expected Result
Scenario 1: Pod successfully rolls out new deployment using the signed image after its signature has been successfully verified.
Scenario 2: Pod tries to roll out new deployment using the unsigned image but fails because its signature has failed to verified image.

In both scenarios, OpenShift verifies the image before a new set of pods are rolled out with that image. **Unsigned images are not rolled out because they fail to verify against signatures (or were deployed without signatures) thus _protecting the hosted apps_ from being compromised by code injection, untested or malicious code, or manual deploys from developers who try to deploy code without going through the pipeline.**

**Comment by aizuddin85** [comment]
While atomic can do the filtering via `/etc/containers/policy.json`.  
  
On full RHEL with docker this is not possible unless we do it via pipeline(or manual) to check image signature status and annotate the image as `images.openshift.io/deny-execution: true` when unverified.
