### ISSUE TITLE
Sweep annotations for namespacing and consistent key names

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2169]
The UI uses the following annotations which are not namespaced (`openshift.io/...`) or are formatted using camel-case instead of dashes (`fieldName` vs `field-name`).

I'm not sure we want to namespace all of these, or change them from camelCase to hyphenated. We should decide if we want to, and if we do, sooner is better than later.

Object | Annotations
---------|----------------
ReplicationController | fixed in #2227<br>openshift.io/encoded-deployment-config<br>openshift.io/deployment-config.name<br>openshift.io/deployment.phase<br>openshift.io/deployment-config.latest-version
Template | tags<br>helplink.\*.title<br>helplink.\*.url<br>displayName<br>version<br>provider<br>summary<br>description<br>iconClass<br>icon
Pod | fixed in #2227<br>openshift.io/deployment.name
TagReference | tags
Project/Namespace | displayName<br>description

**Comment by smarterclayton** [comment]
Deployment should definitely be changed.  Project should definitely be changed.  We should change replication controller before launch.  Who the heck added all the template annotations :)

**Comment by smarterclayton** [comment]
@ironcladlou can we change the deployment ones very soon?  Would like that baked before we cut 0.5.1 so we don't have to claim backwards compat.

**Comment by ironcladlou** [comment]
Shouldn't be an issue; I can probably knock this out right after I'm finished with rolling deployments.

**Comment by liggitt** [comment]
need to coordinate to make sure web UI and osc update use of the annotations

**Comment by liggitt** [comment]
the template annotations don't bother me so much, since it's our object. The icon one concerns me a bit because of the size

**Comment by derekwaynecarr** [comment]
@stevekuznetsov for historical purposes, this is the PR that went and originally set the annotation that we need to now prefix, should give you a hint of where to change: https://github.com/openshift/origin/pull/1868

**Comment by liggitt** [comment]
So, for display name, `openshift.io/display-name` everywhere?

**Comment by liggitt** [comment]
@stevekuznetsov see #2227 as well for central places to put mappings to a new annotation key
