### ISSUE TITLE
Unable to connect to the server: Forbidden

### ISSUE THREAD

**Issue by birajdarabhishek1** [openshift/origin#21695]
I have installed Minishift with Proxy setting. 
The server is accessible via web console at:
    https://192.168.42.76:8443/console

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

Issue: 
[root@minishift ~]# oc status
Unable to connect to the server: Forbidden

[root@minishift ~]# oc login -u system:admin
error: Forbidden

[root@minishift ~]# curl https://192.168.42.76:8443/console
curl: (56) Received HTTP code 403 from proxy after CONNECT

How can I connect console from my VM, or Outside Network. 

#minishift #Linux

**Comment by RashaHaj** [comment]
I'm running into the same issue , trying to install openshift cluster. Eventually, the cluster is indeed deployed 
```
[root@master openshift-master]# oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
Unable to connect to the server: Forbidden
```
but I'm unable to excute any of the commands without having the output

```
[root@master playbooks]# oc get nodes
Unable to connect to the server: Forbidden
```
May you tell me how you fix it ?

**Comment by pavenova** [comment]
Issue is still in place (oc client v 3.11)
