### ISSUE TITLE
output Image is not resolved when creating Build from Rest API of Openshift

### ISSUE THREAD

**Issue by somayeh-karami** [openshift/origin#21702]
I am trying to create a Build thorough Openshift REST APi. the strategy is source, I am trying to create the build from a git repository with python code in it. I haven't created a buildconfig prior to creating the build, and when i call the API, the build is created in Openshift, but its status is pending and it says: "Invalid output reference"
3.9 Version
[provide output of the `openshift version` or `oc version` command]

here is the body of API Call:

##### Steps To Reproduce
{
"kind": "Build",
"apiVersion": "build.openshift.io/v1",
  "metadata": {
  				"name": "sample-blog-6",
               "labels": {
                    "app": "sample-blog"
                }
            
  },
   "spec": {
    	"serviceAccount": "builder",
                "source": {
                    "type": "Git",
                    "git": {
                        "uri": "https://git.******/somayeh/djangoblog.git",
                        "ref": "master"
                    },
                    "sourceSecret":{ "name" :"gitreposecret"}
                },
                   "strategy": {
                    "type": "Source",
                       "sourceStrategy": {
                        "from": {
                            "kind": "ImageStreamTag",
                            "name": "python:latest"
                        }
                    }

                },
                   "output": {
                    "to": {
                        "kind": "ImageStreamTag",
                        "name": "sample-blog:latest"
                    }
                
            }

}
}
here is the YAML created by openshift:

apiVersion: build.openshift.io/v1
kind: Build
metadata:
  creationTimestamp: '2018-12-22T06:32:43Z'
  labels:
    app: sample-blog
  name: sample-blog-6
  namespace: djangoproject3
  resourceVersion: '9947838'
  selfLink: /apis/build.openshift.io/v1/namespaces/djangoproject3/builds/sample-blog-6
  uid: 6359a388-05b3-11e9-a252-005056bd766c
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'sample-blog:latest'
  postCommit: {}
  resources: {}
  serviceAccount: builder
  source:
    git:
      ref: master
      uri: 'https://git.*****/somayeh/djangoblog.git'
    sourceSecret:
      name: gitreposecret
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:latest'
    type: Source
  triggeredBy: null
status:
  message: Output image could not be resolved.
  output: {}
  phase: New
  reason: InvalidOutputReference

**Comment by bparees** [comment]
do you have an imagestream named "sample-blog" with a tag named "latest" in it?  if not, that is why you are getting this error.
