### ISSUE TITLE
Can not reliably remove self-provisioner role from system:authenticated:oauth

### ISSUE THREAD

**Issue by mlbiam** [openshift/origin#21703]
When wanting to eliminate self provisioning of projects, I tried following the advise in https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html, first

`oc patch clusterrolebinding.rbac self-provisioners -p '{"subjects": null}'`

then

`oc adm policy remove-cluster-role-from-group self-provisioner system:authenticated system:authenticated:oauth`

which produces the output:

```
Warning: Your changes may get lost whenever a master is restarted, unless you prevent reconciliation of this rolebinding using the following command: oc annotate clusterrolebinding.rbac self-provisioners 'rbac.authorization.kubernetes.io/autoupdate=false' --overwritecluster role "self-provisioner" removed: ["system:authenticated" "system:authenticated:oauth"]
```

I tried to run `oc annotate clusterrolebinding.rbac self-provisioners 'rbac.authorization.kubernetes.io/autoupdate=false' --overwritecluster` however this produced the output:

```
Error: unknown flag: --overwritecluster
.
.
.
```

Restarting the master resets this policy.

even once i get this error resolved, what other impact would this cause?  Is there a better way to disable self provisioning of projects then by disabling the reconciliation entirely?  I assume there are other policies that get fixed (such as during an upgrade)?

##### Version
[provide output of the `openshift version` or `oc version` command]

```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://openshift.tslocal.lan:8443
openshift v3.11.51
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
1.  follow steps https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#disabling-self-provisioning
2.  Restart masters

##### Current Result

"Create Project" button returns to the ui

##### Expected Result

"Create Project" should remain invisible.

**Comment by phhutter** [comment]
had exactly the same problem,
@mlbiam - looks like the warning message is a bit outdated in your current version:

> Warning: Your changes may get lost whenever a master is restarted, unless you prevent reconciliation of this rolebinding using the following command: oc annotate clusterrolebinding.rbac self-provisioners 'rbac.authorization.kubernetes.io/autoupdate=false' --overwritecluster role "self-provisioner" removed: "system:authenticated:oauth"

current 3.11 warning message can be found here:
https://github.com/openshift/origin/blob/598e13a204c3400168ed4194f5286b4d469252a7/test/cmd/admin.sh#L122

give it a shot:
```oc annotate clusterrolebinding.rbac self-provisioners 'rbac.authorization.kubernetes.io/autoupdate=false' --overwrite
```
after the **oc annotate** command you can try to run your **oc adm policy** command again:
```
oc adm policy remove-cluster-role-from-group self-provisioner system:authenticated:oauth
cluster role "self-provisioner" removed: "system:authenticated:oauth"
```

maybe they just upgraded the oc binary first and forgot to update the message as well.😧
