### ISSUE TITLE
e2e-aws-all failure on "should create functioning node port"

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#21708]
NodePort e2e test fails - we try to connect to master node port (to get routed to the pod on a worker) and we hang.  If you SSH to the master and try the local node port the same issue happens.  If you curl the pod directly it works from the master.  Are node ports not being properly routed off master to a worker?  (note the test goes to the master because they are the only ones with external IPs)

Blocks turning on e2e-aws-all.

/assign @openshift/sig-networking 

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21700/pull-ci-openshift-origin-master-e2e-aws-all/23#openshift-tests-sig-network-services-should-be-able-to-create-a-functioning-nodeport-service-suiteopenshiftconformanceparallel-suitek8s

```
$ openshift-tests run-test "[sig-network] Services should be able to create a functioning NodePort service [Suite:openshift/conformance/parallel] [Suite:k8s]"
I1227 10:38:24.206883   93696 e2e.go:59] The --provider flag is not set.  Treating as a conformance test.  Some tests may not be run.
Dec 27 10:38:24.207: INFO: >>> kubeConfig: /Users/clayton/Downloads/cluster-bot-2018-12-27-151231.kubeconfig
Dec 27 10:38:24.208: INFO: Waiting up to 30m0s for all (but 100) nodes to be schedulable
Dec 27 10:38:24.662: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Dec 27 10:38:24.998: INFO: 3 / 3 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Dec 27 10:38:24.998: INFO: expected 0 pod replicas in namespace 'kube-system', 0 are Running and Ready.
Dec 27 10:38:25.017: INFO: Waiting for pods to enter Success, but no pods in "kube-system" match label map[name:e2e-image-puller]
Dec 27 10:38:25.017: INFO: Dumping network health container logs from all nodes...
Dec 27 10:38:25.174: INFO: e2e test version: v1.11.0+6d83aa7d70
Dec 27 10:38:25.188: INFO: kube-apiserver version: v1.11.0+6d83aa7
I1227 10:38:25.188056   93696 e2e.go:59] The --provider flag is not set.  Treating as a conformance test.  Some tests may not be run.
[BeforeEach] [Top Level]
  /Users/clayton/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/test.go:63
[BeforeEach] [sig-network] Services
  /Users/clayton/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:141
STEP: Creating a kubernetes client
Dec 27 10:38:25.188: INFO: >>> kubeConfig: /Users/clayton/Downloads/cluster-bot-2018-12-27-151231.kubeconfig
STEP: Building a namespace api object
Dec 27 10:38:27.265: INFO: About to run a Kube e2e test, ensuring namespace is privileged
Dec 27 10:38:27.959: INFO: No PodSecurityPolicies found; assuming PodSecurityPolicy is disabled.
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-network] Services
  /Users/clayton/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/network/service.go:83
[It] should be able to create a functioning NodePort service [Suite:openshift/conformance/parallel] [Suite:k8s]
  /Users/clayton/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/network/service.go:471
STEP: creating service nodeport-test with type=NodePort in namespace e2e-tests-services-kbxjf
STEP: creating pod to be part of service nodeport-test
Dec 27 10:38:28.069: INFO: Waiting up to 2m0s for 1 pods to be created
Dec 27 10:38:28.122: INFO: Found 0/1 pods - will retry
Dec 27 10:38:30.144: INFO: Found all 1 pods
Dec 27 10:38:30.144: INFO: Waiting up to 2m0s for 1 pods to be running and ready: [nodeport-test-qcnqz]
Dec 27 10:38:30.144: INFO: Waiting up to 2m0s for pod "nodeport-test-qcnqz" in namespace "e2e-tests-services-kbxjf" to be "running and ready"
Dec 27 10:38:30.160: INFO: Pod "nodeport-test-qcnqz": Phase="Pending", Reason="", readiness=false. Elapsed: 15.764781ms
Dec 27 10:38:32.185: INFO: Pod "nodeport-test-qcnqz": Phase="Pending", Reason="", readiness=false. Elapsed: 2.04056728s
Dec 27 10:38:34.219: INFO: Pod "nodeport-test-qcnqz": Phase="Pending", Reason="", readiness=false. Elapsed: 4.074255972s
Dec 27 10:38:36.241: INFO: Pod "nodeport-test-qcnqz": Phase="Running", Reason="", readiness=true. Elapsed: 6.096402108s
Dec 27 10:38:36.241: INFO: Pod "nodeport-test-qcnqz" satisfied condition "running and ready"
Dec 27 10:38:36.241: INFO: Wanted all 1 pods to be running and ready. Result: true. Pods: [nodeport-test-qcnqz]
STEP: hitting the pod through the service's NodePort
Dec 27 10:38:36.241: INFO: Testing HTTP reachability of http://34.203.191.64:30161/echo?msg=hello
Dec 27 10:38:41.244: INFO: Got error testing for reachability of http://34.203.191.64:30161/echo?msg=hello: Get http://34.203.191.64:30161/echo?msg=hello: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Dec 27 10:38:43.249: INFO: Testing HTTP reachability of http://34.203.191.64:30161/echo?msg=hello
Dec 27 10:38:48.249: INFO: Got error testing for reachability of http://34.203.191.64:30161/echo?msg=hello: Get http://34.203.191.64:30161/echo?msg=hello: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

```
# iptables-save | grep e2e-tests-services-kbxjf
-A KUBE-NODEPORTS -p tcp -m comment --comment "e2e-tests-services-kbxjf/nodeport-test:" -m tcp --dport 30161 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "e2e-tests-services-kbxjf/nodeport-test:" -m tcp --dport 30161 -j KUBE-SVC-XVH6ZTNQ5XRP3PL3
-A KUBE-SEP-CNK4LSJF4J46Z2CA -s 10.129.2.10/32 -m comment --comment "e2e-tests-services-kbxjf/nodeport-test:" -j KUBE-MARK-MASQ
-A KUBE-SEP-CNK4LSJF4J46Z2CA -p tcp -m comment --comment "e2e-tests-services-kbxjf/nodeport-test:" -m tcp -j DNAT --to-destination 10.129.2.10:80
-A KUBE-SERVICES -d 172.30.190.182/32 -p tcp -m comment --comment "e2e-tests-services-kbxjf/nodeport-test: cluster IP" -m tcp --dport 80 -j KUBE-SVC-XVH6ZTNQ5XRP3PL3
-A KUBE-SVC-XVH6ZTNQ5XRP3PL3 -m comment --comment "e2e-tests-services-kbxjf/nodeport-test:" -j KUBE-SEP-CNK4LSJF4J46Z2CA
```

**Comment by smarterclayton** [comment]
Also @openshift/sig-network-edge

**Comment by danwinship** [comment]
> If you SSH to the master and try the local node port the same issue happens.

Using what IP? The test is using an external/public AWS IP, so that adds another layer of possible failure modes. Were you testing with that same IP or with the node's actual IP? (Or 127.0.0.1.)

The iptables rules you quoted look right, and the pod logs from the test you linked also look right:

    I1226 03:30:52.900040    5232 service.go:309] Adding new service port "e2e-tests-services-jnnxf/nodeport-test:" at 172.30.200.232:80/TCP
    I1226 03:30:52.942327    5232 proxier.go:1393] Opened local port "nodePort for e2e-tests-services-jnnxf/nodeport-test:" (:30439/tcp)
    I1226 03:31:08.049428    5232 roundrobin.go:310] LoadBalancerRR: Setting endpoints for e2e-tests-services-jnnxf/nodeport-test: to [10.128.2.16:80]

**Comment by smarterclayton** [comment]
I don't remember, someone would have to try again.  This fails consistently so it's not a flake.

**Comment by smarterclayton** [comment]
I am disabling this test https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-all-4.0/23/#openshift-tests-sig-network-services-should-be-able-to-create-a-functioning-nodeport-service-suiteopenshiftconformanceparallel-suitek8s from the conformance suite until this is fixed (so we can cut the jobs over).

This is high priority to triage and fix for beta @knobunc

**Comment by danwinship** [comment]
This seems to be caused by a tightening up of our AWS security groups. In particular, assuming I'm reading things right, [this rule in openshift/installer](https://github.com/openshift/installer/blob/master/data/data/aws/vpc/sg-worker.tf#L169) allows access to ports 30000-32767 on worker nodes *only* from other worker nodes (with another rule below that allowing access from the console), whereas [the rule in openshift-ansible](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_aws/defaults/main.yml#L385) allowed access to those ports from everywhere.

It seems like the new rule is wrong; the whole point of forcing NodePort services into the high port range was to make it safe to allow access to them without exposing any "real" services on the nodes.

**Comment by danwinship** [comment]
I don't know what /sig this is...

**Comment by danwinship** [comment]
> whereas [the rule in openshift-ansible](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_aws/defaults/main.yml#L385) allowed access to those ports from everywhere.

Actually, reading that again, 3.x only allowed access to NodePort ports from infra nodes, and we presumably hacked the test in some way to ensure that it get scheduled to an infra node. (Or maybe all the nodes got the infra node rules in CI?)

So anyway, it appears that in 3.x on AWS, we allowed (externally-available) NodePort services on infra nodes, but not on worker nodes, and in 4.x, since we no longer have infra nodes, we don't allow (externally-available) NodePort services anywhere, so there is no way for the conformance test to run successfully.

**Comment by smarterclayton** [comment]
I am reenabling and testing in https://github.com/openshift/origin/pull/22143, we must allow externally available NodePort services everywhere to ship.

**Comment by smarterclayton** [comment]
We need to fix this test.

**Comment by danwinship** [comment]
also being tracked as https://bugzilla.redhat.com/show_bug.cgi?id=1711603
