### ISSUE TITLE
API in 4.0 should listen on 8443 as before

### ISSUE THREAD

**Issue by akostadinov** [openshift/origin#21725]
Hi, historically OpenShift API has been listening to 8443, in 4.0 it uses 6443. This might be an issue with upgrades. Also proxies in our company have been allowing CONNECT to 8443 but I don't see that allowed for 6443.
Can we make the default back to 8443?

**Comment by wking** [comment]
Links to competing defaults:

* Kubernetes [defaulting to 6443][1].
* Us [defaulting to 8443][2].

CC @openshift/master @openshift/installer @openshift/networking @openshift/sig-networking (I dunno what the difference between those last two is).  Anyone else that should be looped in here?

[1]: https://github.com/kubernetes/kubernetes/blob/v1.13.1/cmd/kubeadm/app/apis/kubeadm/v1alpha3/defaults.go#L37-L38
[2]: https://github.com/openshift/origin/blob/v3.11.0/pkg/cmd/server/start/start_api.go#L77

**Comment by wking** [comment]
Moved to https://bugzilla.redhat.com/show_bug.cgi?id=1663453
