### ISSUE TITLE
Some images on image-streams-rhel7.json are not present in registry.redhat.io

### ISSUE THREAD

**Issue by lucky-sideburn** [openshift/origin#21732]
##### Version
openshift v3.11.51

##### Steps To Reproduce
1. oc create -f /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/latest/image-streams/image-streams-rhel7.json  -n openshift

##### Current Result

Many images from Registry Console return the following errors:

Internal error occurred: Get https://registry.redhat.io/v2/openshift3/mongodb-24-rhel7/manifests/latest: received unexpected HTTP status: 503 Service Unavailable. Timestamp: 2019-01-06T07:28:20Z Error count: 2 Edit image stream

Internal error occurred: Get https://registry.redhat.io/v2/openshift3/mysql-55-rhel7/manifests/latest: received unexpected HTTP status: 503 Service Unavailable. Timestamp: 2019-01-06T07:28:19Z Error count: 2 Edit image stream

Internal error occurred: Get https://registry.redhat.io/v2/rhoar-nodejs/nodejs-8/manifests/latest: received unexpected HTTP status: 503 Service Unavailable. Timestamp: 2019-01-06T07:28:28Z Error count: 2 Edit image stream

**Comment by bparees** [comment]
these appear to be available now, i think there were redhat registry issues that made these images appear to be unavailable.  please reopen if you still have issues.
