### ISSUE TITLE
Feature: tag in tests collides with upstream

### ISSUE THREAD

**Issue by jsafrane** [openshift/origin#21748]
Upstream uses `[Feature:.+]` to tag tests that need either special SW installed on the host (`[Feature:Volumes]`) or need an alpha gate enabled.

Most Kubernetes tests run with `--ginkgo.skip=\[Feature:.+\]`, (e.g. [pull-kubernetes-e2e-gce](https://github.com/kubernetes/test-infra/blob/edb7d375d17f391c53112d5311a69151caee25d5/config/jobs/kubernetes/sig-gcp/sig-gcp-gce-config.yaml#L53)) and only specific features are enabled in alpha jobs (e.g. [pull-kubernetes-e2e-gce-alpha-features](https://github.com/kubernetes/test-infra/blob/edb7d375d17f391c53112d5311a69151caee25d5/config/jobs/kubernetes/sig-gcp/sig-gcp-gce-config.yaml#L170))

It would be great if OpenShift e2e tests could skip upstream tests with `Feature:.+` too, because they usually have very little chance of succeeding* and the features change with every Kubernetes release, so syncing them [manually](https://github.com/openshift/origin/blob/a654f51ef83210dde34361c212737a5778ed4da3/test/extended/util/test.go#L288) is error prone. However, OpenShift uses `Feature:` to tag various areas of test. A different tag should be used for these.

*) Some `Feature:` tests succeed, e.g. iSCSI ones do have iscsiadm installed in coreos image, but there are just few of them.

@smarterclayton, not sure what is the right team, but you fiddle up with tests a lot these days.

**Comment by smarterclayton** [comment]
We generally don't do that because we have a definition of "success".  For
our product to work, those features have to pass, to merge, you must
continue to support those features.

**Comment by smarterclayton** [comment]
We explicitly run Feature tests as part of the openshift conformance suite.

**Comment by jsafrane** [comment]
Ok, I can see we run Feature:NodeAuthorizer, Feature:SecurityContext and some network stuff in ci/prow/e2e-aws, so skipping all Feature:.* is not possible.

Is there any better way how to skip tests for alpha features? They're different in each Kubernetes release and someone has to manually update list of skipped features during rebase. Current list (1.14-ish) is `Feature:(Audit|BlockVolume|PodPreset|ExpandPersistentVolumes|VolumeSubpathEnvExpansion|RunAsGroup|TTLAfterFinished|NodeLease|CSINodeInfo|CSIDriverRegistry|CSISkipAttach)` and changes with every release as new alpha features appear and old features graduate to beta.
