### ISSUE TITLE
OKD Origin is not supported sdn network plugin CNI?

### ISSUE THREAD

**Issue by mmgil** [openshift/origin#21743]
I will trying to install origin with CNI plugIn in the SDN Network, but, in TASK [openshift_cluster_monitoring_operator : Wait for the ServiceMonitor CRD to be created], i receive errors

##### Version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift-internal.mmgil.com.br:8443
openshift v3.11.0+1a90c5c-83
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. In inventory file add:

openshift_use_openshift_sdn=false
os_sdn_network_plugin_name=cni

##### Current Result

Jan  7 17:03:52 master1 origin-node: W0107 17:03:52.533095   46567 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Jan  7 17:03:52 master1 origin-node: E0107 17:03:52.533295   46567 kubelet.go:2101] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jan  7 17:03:57 master1 origin-node: W0107 17:03:57.539299   46567 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Jan  7 17:03:57 master1 origin-node: W0107 17:03:57.539299   46567 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Jan  7 17:03:57 master1 origin-node: E0107 17:03:57.539594   46567 kubelet.go:2101] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jan  7 17:03:57 master1 origin-node: E0107 17:03:57.901856   46567 summary.go:102] Failed to get system container stats for "/system.slice/origin-node.service": failed to get cgroup stats for "/system.slice/origin-node.service": failed to get container info for "/system.slice/origin-node.service": unknown container "/system.slice/origin-node.service"
Jan  7 17:03:57 master1 origin-node: E0107 17:03:57.901856   46567 summary.go:102] Failed to get system container stats for "/system.slice/origin-node.service": failed to get cgroup stats for "/system.slice/origin-node.service": failed to get container info for "/system.slice/origin-node.service": unknown container "/system.slice/origin-node.service"

##### Expected Result

Execute 
ansible-playbook -i inventory/hosts.mmgil ../openshift-ansible/playbooks/deploy_cluster.yml
with success

**Comment by magick93** [comment]
Did you manage to solve this issue?
