### ISSUE TITLE
openshift-test should work with `oc run`

### ISSUE THREAD

**Issue by sferich888** [openshift/origin#21770]
It would be nice if we had a way to run the test suite on a running cluster so that we could see/confirm that the cluster is functioning. 

##### Version
$ oc get clusterversion -o jsonpath='{.items[].status.current.version}{"\n"}'
4.0.0-9

##### Steps To Reproduce
1. `$ oc run --generator=deployment/v1beta1 --attach --stdin --tty -f auth/kubeconfig:/etc/kube/kubeconfig --env KUBECONFIG=/etc/kube/kubeconfig --image=openshift/origin-v4.0:tests --command -- openshift-tests help run `

##### Current Result

Failed              kubelet, ip-10-0-143-162.ec2.internal   Error: container create failed: container_linux.go:336: starting container process caused "exec: \"help\": executable file not found in $PATH"

##### Expected Result

This should show the output of the `openshift-test help run` output and tell a user how to run tests. 
Due to the fact that we are providing a kubeconfig with `-f` and setting the proper env_var for openshift-test to work, something like this should be possible. 

##### Additional Information

cc: @smarterclayton can you have a look and help me understand if / how to make something like this work?

**Comment by sferich888** [comment]
This also seems to have issues if you SSH to a master and try and run this directly (supplying the kubeconfig on the system). 

```
sudo podman run -v /etc/kubernetes/kubeconfig:/etc/kubernetes/kubeconfig -e KUBECONFIG=/etc/kubernetes/kubeconfig -it registry.svc.ci.openshift.org/openshift/origin-v4.0:tests openshift-tests run openshift/conformance
```

**Comment by sferich888** [comment]
Due to https://bugzilla.redhat.com/show_bug.cgi?id=1665341 I don't think I can run a command that just starts the container. 

However, I have seen success doing: 

```
oc run --generator=deployment/v1beta1 --env KUBECONFIG=/etc/kube/kubeconfig --image=openshift/origin-v4.0:tests openshift-tests --command -- sleep 500
oc set volumes deployment/openshift-tests --add --name=kubeconfig --mount-path=/etc/kube/ --configmap-name=kubeconfig
```

Then sshing to the node where the pod is deployed and running: 

```
sudo crictl exec -it $(sudo crictl ps | grep openshift-tests | awk '{print $1}') openshift-tests run openshift/conformance
```

**Comment by smarterclayton** [comment]
You want `oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:NAMESPACE:DEFAULT`

**Comment by sferich888** [comment]
Why? I think, I have this working, with out any policy changes. Based on a test I just ran. I need to double check the flow, to be sure.

**Comment by sferich888** [comment]
I feel we can close this; I was able to use the following to get this working. 

```
$ oc new-project tests
$ oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:tests:default
$ oc create configmap kubeconfig --from-file=kubeconfig
$ oc run --attach --stdin --tty --image=openshift/origin-v4.0:tests --overrides='{"kind":"Pod","apiVersion":"v1","metadata":{"name":"openshift-tests","creationTimestamp":null,"labels":{"run":"openshift-tests"}},"spec":{"containers":[{"name":"openshift-tests","image":"openshift/origin-v4.0:tests","env":[{"name":"KUBECONFIG","value":"/kubeconfig/kubeconfig"}],"args":["/bin/bash","-c","openshift-tests run openshift/conformance"],"resources":{},"imagePullPolicy":"IfNotPresent","volumeMounts":[{"name":"kubeconfig-volume","mountPath":"/kubeconfig"}]}],"restartPolicy":"Never","dnsPolicy":"ClusterFirst","volumes":[{"configMap":{"name":"kubeconfig"},"name":"kubeconfig-volume"}]}}' --rm --restart=Never openshift-tests‍‍‍‍
```
