### ISSUE TITLE
Unable to create new app behind corporate proxy

### ISSUE THREAD

**Issue by shockogit** [openshift/origin#21774]
When running the following command to create a test app after setup I get the following:

oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
warning: Cannot find git. Ensure that it is installed and in your path. Git is required to work with git repositories.
**error: unable to load template file "https://github.com/sclorg/nodejs-ex": Get https://github.com/sclorg/nodejs-ex: dial tcp 140.
2.118.3:443: i/o timeout
error: git ls-remote failed w**ith: git binary not available;  local file access failed with: CreateFile https://github.com/sclorg/
odejs-ex: The filename, directory name, or volume label syntax is incorrect.
error: unable to locate any images in image streams, templates loaded in accessible projects, template files, local docker images
with name "https://github.com/sclorg/nodejs-ex"

##### Version
**minishift v1.29.0+72fa7b2**

##### Steps To Reproduce
1. Windows 10 Machine behind corporate proxy (with or without proxy auth)
2. Deploy minishift to Oracle Virtual box with the following:

.\minishift.exe start  --http-proxy=http://10.112.64.203:8080 --https-proxy=http://10.112.64.203:8080  --docker-env  HTTPS_PROXY=http://10.112.64.203:8080 --docker-env  HTTP_PROXY=http://10.112.64.203:8080 

The try and deploy an app with:
oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp

##### Current Result
**error: unable to load template file "https://github.com/sclorg/nodejs-ex": Get https://github.com/sclorg/nodejs-ex: dial tcp 140.

##### Expected Result

Successful pull of app  image from repository

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by sspreitzer** [comment]
Before running oc, set the environment variables like:

```shell
$ export HTTP_PROXY="http://10.112.64.203:8080"
$ export HTTPS_PROXY="http://10.112.64.203:8080"
$ export NO_PORXY=".whatever.example.com,.xip.io"
```

and try again

**Comment by phhutter** [comment]
Tested the same way as @shockogit did and can reproduce the same error as well.
wierd fact; i can easily wget the url (eg. wget https://github.com/sclorg/nodejs-ex) and I can pull it (eg docker pull https://github.com/sclorg/nodejs-ex) - everything seems to work fine - except oc 

Even when i export following env. variables:
```
export HTTP_PROXY="http://proxy.net:8080"
export HTTPS_PROXY="https://proxy.net:8080"
export http_proxy="http://proxy.net:8080"
export https_proxy="https://proxy.net:8080"
```

also tried adding the proxy at cluster startup
```
oc cluster up --http-proxy="http://proxy.net:8080" --https-proxy="https://proxy.net:8080 ... "
```

and added the proxy to the docker systemd service configuration as well
```
[Service]
Environment="HTTP_PROXY=http://proxy.net:8080/"
Environment="HTTPS_PROXY=https://proxy.net:8080/"
```

oc version 
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0
```

**Comment by shockogit** [comment]
> Before running oc, set the environment variables like:
> 
> ```shell
> $ export HTTP_PROXY="http://10.112.64.203:8080"
> $ export HTTPS_PROXY="http://10.112.64.203:8080"
> $ export NO_PORXY=".whatever.example.com,.xip.io"
> ```
> 
> and try again
> 
> ```shell
> $ oc new-project sledgehammer
> $ oc new-app https://github.com/sclorg/nodejs-ex -l name=myapp
> ```

I'm on windows though.

**Comment by phhutter** [comment]
@shockogit never did it before on a windows client, but you could give it a try:

> https://docs.cloudfoundry.org/cf-cli/http-proxy.html
> - Setting https_proxy in Windows

**Comment by shockogit** [comment]
Thanks. Why would we need to set a proxy in Windows (even if this works). ? I thought oc.exe simply talked to the open shift instance running in the VM/Docker in virtual box so proxy is needed there no??

**Comment by shockogit** [comment]
Guys, wondering why this is such a struggle? Has anyone got this working on windows behind a proxy?

**Comment by pdebuitlear** [comment]
**Version**
```
minishift v1.32.0+009893b

[docker@minishift ~]$ oc version
oc v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
kubernetes v1.11.0+d4cacc0

```

Same issue reproducing here.

**Comment by zak-nye** [comment]
@shockogit or anyone else. Did you manage to get anywhere on this. I'm suffering the same issues with oc new-app or import-image not using the proxy settings used when originally setting up the cluster. I'm on Windows 10 1607 with Minishift version v1.31.0+d06603e.

There are multiple issues open about this on the Minishift repo but I'm informed changes to proxy values in Openshift origin may be the cause (see [bottom of Minishift issue 3200](https://github.com/minishift/minishift/issues/3200) )

**Comment by 62mkv** [comment]
@zak-nye @shockogit probably related with Minishift 1.34.0 / OpenShift 3.11.0 (my pain is in the latest comments here: https://github.com/minishift/minishift/issues/3125#issuecomment-510418238)

**Comment by tinytongolai** [comment]
What is the status of this potential issue ? i am not attaching any logs.... as i do have the same behavior.... Thanks..

**Comment by hppanja** [comment]
I have this issue as well, and tried many possible solutions. I am on Windows with oc running in Centos7 Virtualbox. Looks like this is impossible for the moment, until a newer release, hopefully.
