### ISSUE TITLE
restart iptables caused docker daemon restart

### ISSUE THREAD

**Issue by yekaifeng** [openshift/origin#21780]
Docker daemon which is managed by origin-node, get restarted when restarting iptables in systemd

##### Version
[provide output of the `openshift version` or `oc version` command]
~~~
# oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      07f3374/1.13.1
 Built:           Fri Dec  7 16:13:51 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      07f3374/1.13.1
 Built:           Fri Dec  7 16:13:51 2018
 OS/Arch:         linux/amd64
 Experimental:    false
~~~

##### Steps To Reproduce
1. restart iptables by command 
~~~
# systemctl restart iptables
~~~

2. docker daemon was restarted
![image](https://user-images.githubusercontent.com/17564158/51113356-b11bbc00-183c-11e9-9ef0-9e33835aadf1.png)

##### Current Result
Docker daemon restarted

##### Expected Result
Restart iptables shouldn't affect the docker daemon

##### Additional Information
The are 84 iptables in the system
![image](https://user-images.githubusercontent.com/17564158/51113527-2f785e00-183d-11e9-86aa-17677071cb71.png)

**Comment by linzhaoming** [comment]
[Openshift Ansible roles](https://github.com/openshift/openshift-ansible/blob/release-3.9/roles/container_runtime/tasks/systemcontainer_docker.yml)  will install the Drop-In Systemd unit

```
- name: Configure Container Engine Service File
  template:
    dest: "{{ container_engine_systemd_dir }}/custom.conf"
    src: systemcontainercustom.conf.j2
```

The content of custome.conf(Will be the systemd Drop-In Unit) is:

```
# {{ ansible_managed }}

[Unit]
Wants=iptables.service
After=iptables.service

# The following line is a work-around to ensure docker is restarted whenever
# iptables is restarted.  This ensures the proper iptables rules will be in
# place for docker.
# Note:  This will also cause docker to be stopped if iptables is stopped.
PartOf=iptables.service
```

Which means **when iptables restarted, docker damon will also be restarted**.
