### ISSUE TITLE
Template parameters should have optional displayName field

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2179]
When building a UI around template parameters, it's ugly to display names intended for programmatic use as form labels, e.g. ADMIN_USERNAME, ADMIN_PASSWORD, etc. The `description` field is nice for hover help, but invites descriptions (surprise!) that are too long to use as labels.

An optional "displayName" field in the Parameter type would make it possible to build nicer looking UI's around templates. If no displayName was specified, the UI would use name instead.

**Comment by mfojtik** [comment]
@bparees assign this to me ;)

**Comment by bparees** [comment]
make sure you get @smarterclayton to review the api change.

**Comment by smarterclayton** [comment]
Fixed
