### ISSUE TITLE
Docker Hub description for origin-haproxy-router dead link

### ISSUE THREAD

**Issue by git001** [openshift/origin#21811]
[provide a description of the issue]

The link to the router repository is a dead link

https://hub.docker.com/r/openshift/origin-haproxy-router

**Comment by tux-o-matic** [comment]
Indeed, no such thing as https://github.com/openshift/origin/blob/master/images/router/haproxy

**Comment by git001** [comment]
For the upcoming 4.x are the ingress controller in https://github.com/openshift/router
