### ISSUE TITLE
Reconnection of Jenkins Slaves

### ISSUE THREAD

**Issue by rdepke** [openshift/origin#21830]
We have a Jenkins master running in OpenShift that spawns agents to build jobs. When the cluster/pods are restarted, while a agent is processing a build the Jenkins master waits forever for the build result, because the agent can reconnect to the master.

##### Version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth
Server https://my.cluster:8443
openshift v3.11.59
kubernetes v1.11.0+d4cacc0
--

##### Steps To Reproduce
1. Have a Jenkins master running that spawns agents automatically
2. Trigger a build
3. e.g. restart cluster 

##### Current Result
The Jenkins master waits for ever for the build result

##### Expected Result
Jenkins notices the agent is gone or the agent is able to reconnect to the master.

**Comment by bparees** [comment]
https://github.com/openshift/jenkins is a more appropriate location for this sort of issue/request.
