### ISSUE TITLE
Example application issues

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2183]
Couple issues I found today following the sample-app README:

* `openshift ex registry --create` (step 7.)` does not work until you create a project. Without project, you will get this error message (that won't tell you have to create project to fix it ;-):

```
Error: "/osapi/v1beta1/deploymentConfigs?namespace=default" is forbidden because test-admin cannot create on deploymentConfigs in default
Error: "/api/v1beta1/services?namespace=default" is forbidden because test-admin cannot create on services in default
```

* When you create project and re-run the command above everything creates successfully but the the deployment fails with this message:

```
[root@openshiftdev origin]# osc log deploy-docker-registry-14n2hh
2015-05-12T08:50:30.819206516Z F0512 08:50:30.818897       1 deployer.go:64] Get https://192.168.121.138:8443/api/v1beta1/replicationControllers/docker-registry-1?namespace=test: dial tcp 192.168.121.138:8443: no route to host
```

(This is a new Vagrant box running on libvirt, I also tried to run with`--public-master=localhost` but no luck).
The workaround for this is to stop the `firewalld`

* The curl command to check if the Docker Registry is running is incorrect, the correct command is:

```
$ curl -v -H 'Accept: application/json' `osc get service docker-registry --template="{{ .spec.portalIP }}:{{ with index .spec.ports 0 }}{{ .port }}{{ end }}/v2/" --config=openshift.local.config/master/admin.kubeconfig
```

( i will fix this in PR )

* After I start the build, the builder container is not able to reach outside world:

```
[root@ruby-sample-build-2 openshift]# curl -v https://github.com/mfojtik/ruby-etcd-sample
* About to connect() to github.com port 443 (#0)
*   Trying 192.30.252.129...
```

So all builds fail. This is the template I'm using: https://gist.github.com/mfojtik/f09572b86ad7105e7bcf#file-template-json-L28

(solved by restarting docker after stopping firewalld)

* The STI builder is using wrong (old) Docker image when I did pullimages.sh:

```
[root@openshiftdev origin]# docker images | grep origin-sti
docker.io/openshift/origin-sti-builder       latest              0c47bf61a0f5        3 hours ago         366.8 MB
openshift/origin-sti-builder                 latest              438f88cf733f        3 months ago        507.4 MB
```

**Comment by mfojtik** [comment]
@bparees ^^

**Comment by mfojtik** [comment]
https://github.com/openshift/origin/pull/2191

**Comment by bparees** [comment]
@mfojtik 
1) i've never had to create a project to create a registry, as long as you're doing it as cluster admin it should create it in the default project.

2) stopping firewalld is a requirement that's documented in the readme.

3) the github reachability problem i've seen before, basically the docker containers have no outside access.  I don't believe it's related to firewalld, but i've always fixed it by restarting dockerd just like you did.  not an issue w/ the sample imho.

4) the image issue is a docker 1.6 problem, you need to remove your old openshift/origin-sti-builder image.  Docker did some funky things when they started explicitly putting docker.io into the names.

So I think that leaves: the check to see if the registry is running.  This command should be matched to what we're doing in e2e.

**Comment by bparees** [comment]
@mfojtik i think is all addressed between your PR and my comments, can we close?
