### ISSUE TITLE
Remapping ports for headless services does not work

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2187]
I have this this service:

```
[root@openshiftdev origin]# osc describe service etcd
Name:			etcd
Labels:			name=etcd,template=etcd
Selector:		name=etcd
IP:			None
Port:			client	4001/TCP
Endpoints:		client	172.17.0.19:2379,172.17.0.21:2379
Port:			server	2380/TCP
Endpoints:		server	172.17.0.19:2380,172.17.0.21:2380
Session Affinity:	None
No events.
```

Now, if I `curl http://etcd:4001` I get 'Connection refused'. But if I `curl http://etcd:2379` it gives me 404.

**Comment by mfojtik** [comment]
@smarterclayton @rajatchopra FYI

**Comment by mfojtik** [comment]
According to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#headless-services there is no load-balancing done for the headless services. If that also means that there is no port-mapping done, I think this is a bug that should be fixed in upstream. Kubernetes should give you validation error if you try to remap the ports for headless services.

**Comment by smarterclayton** [comment]
As soon as #6666 closes im going to expose endpoints as a separate DNS name on all services, not just headless.  But until then, yes.

And yes, we should validate upstream that mapping does not occur (but it should also be valid to define no ports as headless).

**Comment by smarterclayton** [comment]
Please open an upstream issuers this.

**Comment by smarterclayton** [comment]
Should be fixed, please verify.

----- Original Message -----

**Comment by danmcp** [comment]
@mfojtik ^^

**Comment by mfojtik** [comment]
it works, thanks!
