### ISSUE TITLE
TestWatchFileChanged unit test failed

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#21876]
Seen: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21874/pull-ci-openshift-origin-master-unit/2280

```
=== RUN   TestWatchFileChanged
E0128 12:42:45.419320    8724 file_linux.go:61] Unable to read config path "/tmp/dir-test952203281": error while processing inotify event ("/tmp/dir-test952203281": 0x400 == IN_DELETE_SELF): the watched path is deleted
--- FAIL: TestWatchFileChanged (0.25s)
	file_linux_test.go:402: expected empty update, got types.PodUpdate{Pods:[]*v1.Pod{(*v1.Pod)(0xc4208e1500)}, Op:0, Source:"file"}
```

**Comment by sjenning** [comment]
Compiled that packages tests into a binary.  When run serially, 100% pass rate.  When run 100 in parallel, very high failure rate.
```
$ for i in $(seq 1 100); do ./config.test 2>&1; done | grep -e PASS$ -e FAIL$ | sort | uniq -c
    100 PASS
[sjennings@cerebellum origin]$ for i in $(seq 1 100); do ./config.test 2>&1 & done | grep -e PASS$ -e FAIL$ | sort | uniq -c
     35 FAIL
     65 PASS
```
Still trying to figure out what the bad interaction is.

**Comment by rphillips** [comment]
@soltysh are there multiple test instances running on the machine? Bazel will create a sandbox with a new /tmp, isolating the test run environment.

**Comment by mfojtik** [comment]
@rphillips i'm pretty sure the /tmp is shared for tests... @smarterclayton to confirm.

**Comment by soltysh** [comment]
@rphillips we don't explicitly force serial anywhere in the tests, I'm not sure how bazel is handling those cases, though.

**Comment by sjenning** [comment]
I see no evidence that this is flaking upstream
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestWatchFileChanged

I think we've established they isolate their tests differently upstream.
