### ISSUE TITLE
Error getting client: invalid configuration: default cluster has no server defined

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#2188]
Hi All,
    I'm a little confuse, some days ago I was able to create projects, but now is not possible ... I 'getting the following error message...

[root@ose1 openshift]# osadm new-project holamundo
F0512 07:28:07.276425    6336 new_project.go:44] Error getting client: invalid configuration: default cluster has no server defined

Any idea? What configuration change can cause the kind of error ?

**Comment by roldancer** [comment]
problem fixed ... when you install via Ansible, it creates the file /root/.config/openshift/.config, by a mistake we have deleted that file, this is the step to recover the .config file:

cp /var/lib/openshift/openshift.local.certificates/openshift-client/.kubeconfig /root/.config/openshift/.config

Enjoy!!

**Comment by cmoulliard** [comment]
We also get this error with latest deployment of openshift within a Virtual Machine (VirtualBox) created by Vagrant - https://github.com/fabric8io/fabric8/blob/master/Vagrantfile
