### ISSUE TITLE
Advanced Audit doesn't show username during failed login attempt

### ISSUE THREAD

**Issue by Hakulaku** [openshift/origin#21898]
Advanced Audit doesn't provide username used during failed login attempt on webconsole

##### Version
oc v3.11.0-alpha.0+1ff2229-9
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://masters.sanitized.domain:443
openshift v3.11.0+1c3e643-87
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. Setup auditing according to the user documentation on: "https://docs.okd.io/latest/install_config/master_node_configuration.html#master-node-config-advanced-audit"
2. Make an unsuccesful login on the webconsole.

##### Current Result

Note that i set "JSON" as formatting for the audit log.

```json
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2019-01-29T12:25:05Z"},"level":"Metadata","timestamp":"2019-01-29T12:25:05Z","auditID":"3aa70b72-0dab-45f5-ac2f-ed781e9ea85a","stage":"RequestReceived","requestURI":"/login/Identity%20Provider","verb":"post","user":{},"sourceIPs":["xxx.xxx.xxx.xxx"],"requestReceivedTimestamp":"2019-01-29T12:25:05.514100Z","stageTimestamp":"2019-01-29T12:25:05.514100Z"}
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2019-01-29T12:25:05Z"},"level":"Metadata","timestamp":"2019-01-29T12:25:05Z","auditID":"3aa70b72-0dab-45f5-ac2f-ed781e9ea85a","stage":"ResponseComplete","requestURI":"/login/Identity%20Provider","verb":"post","user":{},"sourceIPs":["xxx.xxx.xxx.xxx"],"responseStatus":{"metadata":{},"code":302},"requestReceivedTimestamp":"2019-01-29T12:25:05.514100Z","stageTimestamp":"2019-01-29T12:25:05.770419Z"}
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2019-01-29T12:25:05Z"},"level":"Metadata","timestamp":"2019-01-29T12:25:05Z","auditID":"61aea890-7e10-4362-b171-9c308a0f265b","stage":"RequestReceived","requestURI":"/login/Identity%20Provider?reason=access_denied\u0026then=%2Foauth%2Fauthorize%3Fclient_id%3Dopenshift-web-console%26idp%3DIdentity%2BProvider%26redirect_uri%3Dhttps%253A%252F%252Fmasters.santized.domain%252Fconsole%252Foauth%26response_type%3Dcode%26state%3DTOKEN","verb":"get","user":{},"sourceIPs":["xxx.xxx.xxx.xxx"],"requestReceivedTimestamp":"2019-01-29T12:25:05.879504Z","stageTimestamp":"2019-01-29T12:25:05.879504Z"}
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2019-01-29T12:25:05Z"},"level":"Metadata","timestamp":"2019-01-29T12:25:05Z","auditID":"61aea890-7e10-4362-b171-9c308a0f265b","stage":"ResponseComplete","requestURI":"/login/Identity%20Provider?reason=access_denied\u0026then=%2Foauth%2Fauthorize%3Fclient_id%3Dopenshift-web-console%26idp%3DIdentity%2BProvider%26redirect_uri%3Dhttps%253A%252F%252Fmasters.santized.domain%252Fconsole%252Foauth%26response_type%3Dcode%26state%3DTOKEN","verb":"get","user":{},"sourceIPs":["xxx.xxx.xxx.xxx"],"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2019-01-29T12:25:05.879504Z","stageTimestamp":"2019-01-29T12:25:05.910918Z"}
```
##### Expected Result
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2019-01-29T12:25:05Z"},"level":"Metadata","timestamp":"2019-01-29T12:25:05Z","auditID":"3aa70b72-0dab-45f5-ac2f-ed781e9ea85a","stage":"RequestReceived","requestURI":"/login/Identity%20Provider","verb":"post","user":{**USERNAME**},"sourceIPs":["xxx.xxx.xxx.xxx"],"requestReceivedTimestamp":"2019-01-29T12:25:05.514100Z","stageTimestamp":"2019-01-29T12:25:05.514100Z"}
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2019-01-29T12:25:05Z"},"level":"Metadata","timestamp":"2019-01-29T12:25:05Z","auditID":"3aa70b72-0dab-45f5-ac2f-ed781e9ea85a","stage":"ResponseComplete","requestURI":"/login/Identity%20Provider","verb":"post","user":{**USERNAME**},"sourceIPs":["xxx.xxx.xxx.xxx"],"responseStatus":{"metadata":{},"code":302},"requestReceivedTimestamp":"2019-01-29T12:25:05.514100Z","stageTimestamp":"2019-01-29T12:25:05.770419Z"}
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2019-01-29T12:25:05Z"},"level":"Metadata","timestamp":"2019-01-29T12:25:05Z","auditID":"61aea890-7e10-4362-b171-9c308a0f265b","stage":"RequestReceived","requestURI":"/login/Identity%20Provider?reason=access_denied\u0026then=%2Foauth%2Fauthorize%3Fclient_id%3Dopenshift-web-console%26idp%3DIdentity%2BProvider%26redirect_uri%3Dhttps%253A%252F%252Fmasters.santized.domain%252Fconsole%252Foauth%26response_type%3Dcode%26state%3DTOKEN","verb":"get","user":{***USERNAME***},"sourceIPs":["xxx.xxx.xxx.xxx"],"requestReceivedTimestamp":"2019-01-29T12:25:05.879504Z","stageTimestamp":"2019-01-29T12:25:05.879504Z"}
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2019-01-29T12:25:05Z"},"level":"Metadata","timestamp":"2019-01-29T12:25:05Z","auditID":"61aea890-7e10-4362-b171-9c308a0f265b","stage":"ResponseComplete","requestURI":"/login/Identity%20Provider?reason=access_denied\u0026then=%2Foauth%2Fauthorize%3Fclient_id%3Dopenshift-web-console%26idp%3DIdentity%2BProvider%26redirect_uri%3Dhttps%253A%252F%252Fmasters.santized.domain%252Fconsole%252Foauth%26response_type%3Dcode%26state%3DTOKEN","verb":"get","user":{**USERNAME**},"sourceIPs":["xxx.xxx.xxx.xxx"],"responseStatus":{"metadata":{},"code":401},"requestReceivedTimestamp":"2019-01-29T12:25:05.879504Z","stageTimestamp":"2019-01-29T12:25:05.910918Z"}
```
##### Additional Information

Hi,

I've been trying to setup advanced auditing on the API to audit for (LDAP) login failures on my local Openshift Origin installation. I've followed the instructions in the openshift documentation (https://docs.okd.io/latest/install_config/master_node_configuration.html#master-node-config-advanced-audit) which shows a sample configuration. The specific part for login failures i've added to my auditting:

```yaml
  # Log login failures from the web console or CLI. Review the logs and refine your policies.
  - level: Metadata
    nonResourceURLs:
    - /login* 
    - /oauth* 
```

my current audit file is:
```yaml
apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  - level: Metadata
    nonResourceURLs:
      - /login*
      - /oauth*
```

Now, when i try an unsuccesful login i see a set of events in the audit loginfile (see current result), but it doesn't show the username which was used to authenticate with and it also doesn't show 401 errors. Am i doing something wrong or is this expected behavior?

**Comment by prasenforu** [comment]
Same for me ... Not getting "user"

**Comment by deepakdk13** [comment]
please use this 

 - level: Metadata
    userGroups: ["system:authenticated:oauth"]

**Comment by Hakulaku** [comment]
> please use this
> 
> * level: Metadata
>   userGroups: ["system:authenticated:oauth"]

Hi,

I've just tested it by changing our audit file:

```
apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  - level: Metadata
    userGroups: ["system:authenticated:oauth"]
```
After restarting the api only succesful login attempts are now mentioned. No failures.

also changing the usergroups to "system:unauthenticated" has no positive outcome.

What i'm looking for is what username was provided for the failed authentication attempt. With debugging enabled i'm able to see it, but i guess that's not the way to go to receive this information. Would be great to get this information from the api auditting instead.

**Comment by george-rudenko** [comment]
> please use this
> 
> * level: Metadata
>   userGroups: ["system:authenticated:oauth"]

Seems that it does not work. Have you got some other ideas how to fix that problem?

**Comment by george-rudenko** [comment]
> > please use this
> > 
> > * level: Metadata
> >   userGroups: ["system:authenticated:oauth"]
> 
> Hi,
> 
> I've just tested it by changing our audit file:
> 
> ```
> apiVersion: audit.k8s.io/v1beta1
> kind: Policy
> rules:
>   - level: Metadata
>     userGroups: ["system:authenticated:oauth"]
> ```
> 
> After restarting the api only succesful login attempts are now mentioned. No failures.
> 
> also changing the usergroups to "system:unauthenticated" has no positive outcome.
> 
> What i'm looking for is what username was provided for the failed authentication attempt. With debugging enabled i'm able to see it, but i guess that's not the way to go to receive this information. Would be great to get this information from the api auditting instead.

@Hakulaku, have you solved the described problem?
I've got the same(

**Comment by deepakdk13** [comment]
> > > please use this
> > > 
> > > * level: Metadata
> > >   userGroups: ["system:authenticated:oauth"]
> > 
> > 
> > Hi,
> > I've just tested it by changing our audit file:
> > ```
> > apiVersion: audit.k8s.io/v1beta1
> > kind: Policy
> > rules:
> >   - level: Metadata
> >     userGroups: ["system:authenticated:oauth"]
> > ```
> > 
> > 
> > After restarting the api only succesful login attempts are now mentioned. No failures.
> > also changing the usergroups to "system:unauthenticated" has no positive outcome.
> > What i'm looking for is what username was provided for the failed authentication attempt. With debugging enabled i'm able to see it, but i guess that's not the way to go to receive this information. Would be great to get this information from the api auditting instead.
> 
> @Hakulaku, have you solved the described problem?
> I've got the same(

yes i did 3 months back
