### ISSUE TITLE
TestNewManagerImplStartProbeMode unit race

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#21895]
See: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21857/pull-ci-openshift-origin-master-unit/2304/

```
=== RUN   TestNewManagerImplStartProbeMode
2019/01/28 19:48:51 Starting to serve on /tmp/device_plugin150613950/device-plugin.sock
E0128 19:48:51.287615    8025 plugin_watcher.go:115] error stat file /tmp/device_plugin150613950/device-plugin.sock failed: stat /tmp/device_plugin150613950/device-plugin.sock: no such file or directory when handling create event: "/tmp/device_plugin150613950/device-plugin.sock": CREATE
E0128 19:48:51.287773    8025 plugin_watcher.go:120] error could not find plugin for deleted file /tmp/device_plugin150613950/device-plugin.sock when handling delete event: "/tmp/device_plugin150613950/device-plugin.sock": REMOVE
==================
WARNING: DATA RACE
Write at 0x00c4205e4a80 by goroutine 18:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:325 +0x0
  github.com/openshift/origin/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents()
      /go/src/github.com/openshift/origin/vendor/github.com/fsnotify/fsnotify/inotify.go:287 +0x787
```

**Comment by soltysh** [comment]
I've managed to hit this problem running following script:

**Comment by RobertKrawitz** [comment]
Reproduces reliably with this change:

```diff --git a/vendor/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager_test.go b/vendor/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager_test.go
index 7168f2342c..3396a0a812 100644
--- a/vendor/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager_test.go
+++ b/vendor/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager_test.go
@@ -269,6 +269,7 @@ func setupInProbeMode(t *testing.T, devs []*pluginapi.Device, callback monitorCa
 }
 
 func cleanup(t *testing.T, m Manager, p *Stub, w *pluginwatcher.Watcher) {
+	t.Logf("   pluginwatcher %#+v", w)
 	p.Stop()
 	m.Stop()
 	if w != nil {
```

**Comment by RobertKrawitz** [comment]
Actually, appears to be in the same code but not exactly the same place.  So possible false result.

**Comment by rphillips** [comment]
I suspect `t.Logf("   pluginwatcher %#+v", w)` is copying the mutex and the waitgroup leading to a false result.

**Comment by rphillips** [comment]
This issue seems closely related to https://github.com/openshift/origin/issues/21876 - using /tmp for temporary files. Seems like there is a sandboxing issue we should address.

**Comment by RobertKrawitz** [comment]
There's an issue there, but I doubt it's the same one.  I'm able to reproduce it roughly 1/5:

```diff --git a/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go b/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go
index de2addd284..c9fa610915 100644
--- a/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go
+++ b/vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go
@@ -188,6 +188,7 @@ func (w *Watcher) traversePluginDir(dir string) error {
 			}
 		case mode&os.ModeSocket != 0:
 			go func() {
+				time.Sleep(5 * time.Second)
 				w.fsWatcher.Events <- fsnotify.Event{
 					Name: path,
 					Op:   fsnotify.Create,
```

Interestingly, if I add

```time.Sleep(5 * time.Second)```

it reproduces even more reliably.  There certainly appears to be a timing window in here.

**Comment by mfojtik** [comment]
@RobertKrawitz @rphillips https://github.com/openshift/origin/pull/21897 see the description of this. I think the unit tests are running in slower manner than in upstream and if there are races caused by slow go routine scheduling, we will likely hit them here.

**Comment by RobertKrawitz** [comment]
It's possible; I'm able to reproduce it on my local machine, but it takes quite a few iterations.
There is clearly a condition whereby the interaction between the plugin watcher's Stop method and its traversePluginDir method.  The latter walks a directory and sends an event on the watcher's events channel for each qualifying path; if Stop is called in the interim, it will suddenly try to write to a nonexistent channel.
Stop is advertised as "stops probing the creation of plugin sockets at the path", implying to me that the plugin dir walking should stop.  So I think I will go after it that way.
