### ISSUE TITLE
TestCreatePodSandbox_RuntimeClass unit test failed

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#21890]
Seen here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21885/pull-ci-openshift-origin-master-unit/2307

```
=== RUN   TestCreatePodSandbox_RuntimeClass/missing_RuntimeClass
    --- FAIL: TestCreatePodSandbox_RuntimeClass/missing_RuntimeClass (0.00s)
    	assertions.go:254: 
    			Error Trace:	kuberuntime_sandbox_test.go:88
    			Error:      	"[Version]" does not contain "RunPodSandbox"
    			Test:       	TestCreatePodSandbox_RuntimeClass/missing_RuntimeClass
```

**Comment by mrunalp** [comment]
@runcom is looking at it.

**Comment by runcom** [comment]
afaict, that unit test isn't even hitting crio, it uses a fake runtime service to mock runtime calls, @sjenning could you verify?

**Comment by sjenning** [comment]
must be erroring out before getting here
https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go#L62
