### ISSUE TITLE
Flakes in stateful set tests

### ISSUE THREAD

**Issue by gnufied** [openshift/origin#21910]
Bunch of stateful set tests are flaking:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/3631?log#log

Our first instict was, it could be binding which is taking time but it doesn't look like that. Using failure `openshift-tests [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should adopt matching orphans and release non-matching pods [Suite:openshift/conformance/parallel] [Suite:k8s] 16m0s` from above link:

```
I0129 13:59:57.268755       1 aws_util.go:111] Successfully created EBS Disk volume aws://us-east-1b/vol-07c9cec691f92993e
I0129 14:00:09.820453       1 operation_generator.go:336] AttachVolume.Attach succeeded for volume "pvc-28ecdd35-23ce-11e9-b3d1-0a9a5ed9d58c" (UniqueName: "kubernetes.io/aws-ebs/aws://us-east-1b/vol-07c9cec691f92993e") from node "ip-10-0-144-81.ec2.internal"
```

So it took not more than 12seconds for attach to finish. Also from e2e logs:

```
STEP: Saturating stateful set ss
Jan 29 13:59:56.697: INFO: Waiting for stateful pod at index 0 to enter Running
Jan 29 13:59:56.845: INFO: Found 0 stateful pods, waiting for 1
Jan 29 14:00:06.866: INFO: Waiting for pod ss-0 to enter Running - Ready=false, currently Pending - Ready=false
Jan 29 14:00:16.863: INFO: Waiting for pod ss-0 to enter Running - Ready=false, currently Pending - Ready=false
Jan 29 14:00:26.898: INFO: Waiting for pod ss-0 to enter Running - Ready=false, currently Running - Ready=false
Jan 29 14:00:26.898: INFO: Resuming stateful pod at index 0
Jan 29 14:00:26.915: INFO: Running '/usr/bin/kubectl --server=https://ci-op-crbjjlj9-5a633-api.origin-ci-int-aws.dev.rhcloud.com:6443 --kubeconfig=/tmp/admin.kubeconfig exec --namespace=e2e-tests-statefulset-f4xpb ss-0 -- /bin/sh -c touch /data/statefulset-continue; sync'
```

So the stateful set was created approx. 13.59.56, and attach finished at 14.00. Pod's UUID is -`28f11dc9-23ce-11e9-b3d1-0a9a5ed9d58c`.

I suspect this is a problem with `kubectl exec` not working as expected.

**Comment by mrunalp** [comment]
See - https://github.com/kubernetes/kubernetes/pull/69755/files
cc: @smarterclayton

**Comment by mrunalp** [comment]
https://github.com/openshift/origin/pull/21914

**Comment by gnufied** [comment]
@mrunalp but this specific e2e does not uses NFS fwiw. Is this a problem for remote storage like EBS too?

**Comment by mrunalp** [comment]
It could be related to NFS or any remote storage like EBS. At the time I saw this in CRI-O CI, sync was getting stuck on NFS from tests that ran earlier. We definitely need to debug the root cause of sync failure.

**Comment by mrunalp** [comment]
Here is the kernel bug for the sync hang - https://bugzilla.redhat.com/show_bug.cgi?id=1671764. We need to provide more details there.
