### ISSUE TITLE
aws cn-northwest region support 

### ISSUE THREAD

**Issue by tj13** [openshift/origin#21933]
[provide a description of the issue]

please add support for aws cn-northwest region which already lunched in 2017

##### Version
[provide output of the `openshift version` or `oc version` command]
$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

**Comment by dmage** [comment]
@tj13 is it about the integrated registry?

**Comment by tj13** [comment]
not only about the registry, also the cloud provider intergration
