### ISSUE TITLE
.local suffix doesn't work well on OS X

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#2194]
Current pattern uses this naming convention:  <service name>.router.default.local

[.local has a "special" meaning on Mac OSX](https://support.apple.com/en-us/HT201275) which makes it a littler harder to handle but claims multi-level domains are fine such as foo.bar.local.

It would be *nice* to have an option on Create to change the default, though the default could be better.  I like using *.apps pattern, easy to setup DNS rules for in local test/dev env.

/cc @spadgett

**Comment by liggitt** [comment]
I think you can change the default DNSDomain that gets appended for your installation in the config (dnsDomain in master-config.yaml, I believe). @pweil- does the router pick that up when generating hosts?

**Comment by liggitt** [comment]
@sspeiche I thought the UI already exposed an option to set a custom host on a route... @jcantrill spent a long time working on that particular interaction.

**Comment by sspeiche** [comment]
@liggitt I don't know where to locate it.  This is all what I see on the Create flow...

![routing](https://cloud.githubusercontent.com/assets/727196/7601929/543e0fc0-f8eb-11e4-82f6-9930192ea6da.png)

**Comment by liggitt** [comment]
@jcantrill, am I crazy? Don't answer that. Did the route creation not make it in?

**Comment by pweil-** [comment]
> @pweil- does the router pick that up when generating hosts?

In the master, the route allocation plugin will take the default `OpenShiftRouteSubdomain   = "router.default.local"` or use an env var `subdomain := env("OPENSHIFT_ROUTE_SUBDOMAIN", OpenShiftRouteSubdomain)`.  

/cc @ramr - this is one of the last config items still using an env var and needs to be updated.

**Comment by liggitt** [comment]
Oops, I misspoke, there is no config option in master-config.yaml... there is `dnsDomain` in the node config

**Comment by jcantrill** [comment]
@liggitt  @sspeiche   The widgit to support all the routing stuff is in the code base but it is not currently available in the UI.  There were some changes made during 'new-app' development the complicated the route generation and made it clear what was the expected outcome, one of which was the service generation that needed a service to support multiple ports.  That feature of services is now in origin so the custome route generation pieces could be added back in.  We should probably sync this part of with the CLI's new-app flow.  /cc @bparees

**Comment by smarterclayton** [comment]
We aren't running masters in production on macs so local resolution isn't that critical.  Also, we're stepping up a level Indus to cluster.local so you should be able to configure a priority rule on that sub domain if necessary

**Comment by sspeiche** [comment]
Understand for production but for demos and development, it is handy to not have to jump through too many hoops.  Though using some of the ways mentioned above, I can make sure I set env var prior to launch.  Though a slightly different default would ease, though not a high priority

**Comment by smarterclayton** [comment]
What is the environment you're set up with?  We are weak on the design of "i want to demo and dev on Mac" in a way that is truly sustainable.  I would want to have a really clear solution.

----- Original Message -----

**Comment by sspeiche** [comment]
For demo, I try to use `docker run openshift/origin:latest`, run scripts to create router and registry, setup image streams. I now have an additional setting to set the env var.  I use dnsmasq on my Mac host to for *.domain routes.  That way I can stay in the console and demo new app from GitHub, build it and click on the route with my browser on Mac.  Similar setup for dev, though I use vagrant.

**Comment by smarterclayton** [comment]
Can dnsmasq on the mac properly send *.cluster.local to the vm?  That's the new DNS suffix that will be defaulted.

----- Original Message -----

**Comment by sspeiche** [comment]
Here's what I observe, so somewhere something isn't working as advertised.  I will continue to look into it.  As said before, I just set the env var on all-in-one and I'm moving.

```
~$ping -c 1 foo.apps
PING foo.apps (192.168.59.103): 56 data bytes
64 bytes from 192.168.59.103: icmp_seq=0 ttl=64 time=3.586 ms

--- foo.apps ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 3.586/3.586/3.586/0.000 ms
~$ping -c 1 foo.default.local
ping: cannot resolve foo.default.local: Unknown host
~$grep 192.168.59.103 /usr/local/etc/dnsmasq.conf
address=/default.local/192.168.59.103
address=/apps/192.168.59.103
```

**Comment by smarterclayton** [comment]
I think now that we're using cluster.local this should work better

**Comment by jwforres** [comment]
@sspeiche is this still a problem with the cluster.local suffix?

**Comment by jwforres** [comment]
@sspeiche bump, can this be closed?

**Comment by sspeiche** [comment]
@jwforres Well, the .local TLD as a default is still problematic. A good summary is [here on stackoverflow](http://apple.stackexchange.com/questions/159111/network-issues-since-upgrading-to-yosemite-unable-to-find-local-systems). I already work around this by overriding the default.  Just would be nice if it worked, with DNS plugins for vagrant like landrush, without having to override the defaults.

**Comment by sspeiche** [comment]
@csrwng I've been working ok with .local TLD for some time and dnsmasq. I think this issue should be closed. I think some odd network behavior from time to time but ruled out the special TLC .local as the cause.
