### ISSUE TITLE
Errors roundtriping of new-app -o json with create -f

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#2195]
Using a simple flow that is outlined below, I'm getting errors when taking the -o json output "as-is" from new-app and feeding it into create -f.  Note this GitHub repo works fine for Create in web console or directly with new-app (bypassing -o).

```
$ osc new-app https://github.com/sspeiche/nodejs-example -o json > new1.json
$ osc create -f new1.json
imageStreams/nodejs-example
buildConfigs/nodejs-example
Error: deploymentConfig "nodejs-example" is invalid: triggers[1].imageChangeParams.from.kind: invalid value 'ImageStreamTag': kind must be 'ImageStream' or 'ImageRepository'
$ osc version
osc v0.5-156-g72c6472
kubernetes v0.16.2-338-gc07896e
```

See [new1.json](https://gist.github.com/sspeiche/8c3afd2bf9f3735b5831#file-new1-json)

/cc @ironcladlou @smarterclayton

**Comment by ironcladlou** [comment]
[This validation](https://github.com/openshift/origin/blob/master/pkg/deploy/api/validation/validation.go#L196) might be wrong.
