### ISSUE TITLE
oc cluster up - Still redirects to 127.0.0.1

### ISSUE THREAD

**Issue by DarkBlaez** [openshift/origin#21953]
All:

I have seen this issue persist for what seems like years. Every time In install using containerized with oc cluster up it always redirects to 127.0.0.1

I have tried:

oc cluster up--public-hostname=X.X.X.X and it does hit the destination but then redirects to 127.0.01 before even the login screen pops.

I have tried:

Editing the server reference in file./openshift.local.clusterup/openshift-controller-manager/openshift-master.kubeconfig  and it still results in the same redirect

My thought is all this takes is a fresh VM install which is less than $5 in any given amount of time it takes to debug this issue. This issue persist and has persisted based on all of the Issue entries.

Is there any thoughts around what is causing this and/or resolution so that this issue can be closed one and for all?

This issue exist on Centos 7, Fedora 29 Server, Fedora 29 Atomic, Ubuntu, MacOS. I have tested this across all of the OS

The only thing that resolves this is going direct <IP>:8443/console

This is not something that should still exist for the amount of time it has as an outstanding issue

Thanks
DB

**Comment by rplescia** [comment]
I'm still having this issue and none of the workarounds seem to work for me
