### ISSUE TITLE
Some builder images did not appear on first load

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2199]
After loading the example builder images (https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-rhel7.json), I visited $master/console/project/$project/catalog/images?builderfor=https:%2F%2Fgithub.com%2Fopenshift%2Fruby-hello-world

On first load, only two builders appeared. When I refreshed the page, several more appeared.

**Comment by spadgett** [comment]
Same as #2224?

**Comment by liggitt** [comment]
I don't think so, they appeared on next refresh

**Comment by liggitt** [comment]
Might have been a slow image change controller... c.f. https://github.com/openshift/origin/issues/2224#issuecomment-102117686

**Comment by spadgett** [comment]
@liggitt close? It sounds like there's simply a delay as they're processed.
