### ISSUE TITLE
"cluster-status" role Resources blank when describing clusterPolicy

### ISSUE THREAD

**Issue by adellape** [openshift/origin#2200]
When describing cluster policy with `osc describe clusterPolicy default`, the "cluster-status" role doesn't show anything in the `[]` for Resources:

```
cluster-status		Verbs					Resources															Resource Names	Extension
					[get]					[]																	[]		
```

It is apparently supposed to show "/healthz, /version, /api (but nothing lower), /osapi (but nothing lower)", per @deads2k.

**Comment by liggitt** [comment]
the describer is not showing "non-resources"
