### ISSUE TITLE
[3.10] Continuous <nil> garbage collector errors

### ISSUE THREAD

**Issue by rezie** [openshift/origin#22019]
After upgrading from 3.9 to 3.10, I'm seeing a lot of garbage collector errors and warnings that keep repeating every 1 second from the master controller logs:

```
E0212 14:15:14.330548       1 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:125: Failed to list <nil>: the server could not find the requested resource

<repeat some number of times, then finally...>
--
  W0212 14:22:24.502724       1 reflector.go:341] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:125: watch of <nil> ended with: unexpected object: &{map[code:410 kind:Status apiVersion:v1 metadata:map[] status:Failure message:The resourceVersion for the provided watch is too old. reason:Expired]}

<then repeat from the top>
```

Turning up the loglevel to 6 doesn't improve diagnosing this issue. Any suggestions or ideas to help with troubleshooting?

##### Version
oc v3.10.0+67ef696-102
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
At least in our case, just upgrade to 3.10.

**Comment by xavierbaude** [comment]
I get the same error with a redhat cluster (from 3.9 to 3.10.111). 
I get another issue with this upgrade : unable to delete object. A finalizer(foreground) is setup on the deploymentConfig but nothing happens.
(same for job, route replicationcontroller, pod object...)
When delete the finalizer, the object disappear but replicationcontroller still exist !
All seems to point a point to the garbage collector.

**Comment by rezie** [comment]
This seems to persist after upgrading to 3.11 from that 3.10 cluster mentioned earlier. I also did a 3.11 install from scratch and the same issue shows up.

> I get the same error with a redhat cluster (from 3.9 to 3.10.111).
> I get another issue with this upgrade : unable to delete object. A finalizer(foreground) is setup on the deploymentConfig but nothing happens.
> (same for job, route replicationcontroller, pod object...)
> When delete the finalizer, the object disappear but replicationcontroller still exist !
> All seems to point a point to the garbage collector.

Re: unable to delete object. We also had that issue at some point - try removing the finalizer (or more generally, updating any non-immutable fields in the resource). That should cause the resource to be removed immediately.
