### ISSUE TITLE
Projects dropdown is not always ordered

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2201]
Sometimes it looks like this:

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7597249/395bc6aa-f8c0-11e4-8216-d81960aa45da.png)

But sometimes it looks like this:

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7597263/4ca24086-f8c0-11e4-9493-5205a30629e1.png)

**Comment by spadgett** [comment]
The projects page is also unordered.

**Comment by derekwaynecarr** [comment]
The API is ordering by name.  I suspect you are rendering on Display Name so need to sort on client.

**Comment by spadgett** [comment]
@derekwaynecarr Not always from what I've observed... I'm looking at a response to `/osapi/v1beta1/projects` now where `items` isn't ordered by `metadata.name`.

Either way, we should sort by display name since it's what we're showing.

**Comment by derekwaynecarr** [comment]
Oh yeah, good point, I forgot we added the sort in the CLI and not the API.

----- Original Message -----
