### ISSUE TITLE
Unable to access Kibana 

### ISSUE THREAD

**Issue by fmq** [openshift/origin#22013]
After configuring a new install of 3.11 with logging I can't access Kibana, it's returning a 500 Internal Error after I login to Kibana.

##### Version
```
 oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://originm-dt.hospitalaleman.com:8443
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0
```
##### Steps To Reproduce
1. Fres innstall of OKD 3.11 with the following logging vars:
## LOGGING
openshift_logging_install_logging=true
openshift_logging_purge_logging=false
openshift_logging_kibana_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_logging_curator_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_logging_es_nodeselector={"node-role.kubernetes.io/infra": "true"}
openshift_logging_es_memory_limit=2Gi
openshift_logging_storage_kind=dynamic
openshift_logging_es_pvc_dynamic=true
openshift_logging_es_pvc_size=100Gi
openshift_logging_elasticsearch_storage_type=pvc
openshift_logging_kibana_proxy_debug=true
openshift_logging_kibana_hostname=os-kibana-dt.example.com

2. [step 2]
Navigate to any pod and click on View Archive

##### Current Result
The Kibana console request user to login and once user is logged in it shows a 
500 Internal Error screen.

##### Expected Result
The Kibana console should appear

**Comment by mrik974** [comment]
I suggest you take a look at this parameter : `openshift_logging_master_url`. It should be set to the internal url of your master web url such as `https://ose-master.infra.mydns.com`
Also, login on your openshift with `admin` and check the logs of your `Kibana` pod, especially the `kibana-proxy` container. You should get more information about your error there.
