### ISSUE TITLE
4.0 release golf outing!  (Was: OpenShift engineering needs some fresh air)

### ISSUE THREAD

**Issue by jeremyeder** [openshift/origin#22022]
The OpenShift team needs some fresh air. This design proposal is to build critical mass for a round of golf on a Saturday morning at the same course we went to in 2017. Survey below:

##### Version
4.0 GA

##### Steps To Reproduce
1. Release 4.0
2. Flip table, go golfing

##### Current Result
1. 4.0 yet to GA
2. Tables not yet flipped

##### Expected Result
1. 4.0 released
2. All tables flipped

##### Interest/Date survey
https://goo.gl/forms/pVH1zq1zX4fRGLyN2

@sosiouxme @eparis @brenton @sg00dwin @sdodson @vikaslaad @blomquisg @BigN @rhamilto @kwoodson @twiest @smunilla @ironcladlou @abutcher @smarterclayton @pmorie @tiwillia @jwforres @bparees @derekwaynecarr @csrwng @deads2k @spadgett @gabemontero @benjaminapetersen @tracyrankin @joelddiaz @adammhaile @juanvallejo @jupierce @enj @lancejjohnson @cuppett @adambkaplan @sanchezl @bradmwilliams @jewzaam @mwoodson @blrm @dbaker-rh @jcantrill @Miciah @jstuever @jboyd01 @staebler @preethit @dustymabe @jtligon @akrzos @chaitanyaenr @sjug @adellape @bmcelvee @ahardin-rh @kalexand-rh @rjhowe @sjwalter2 @sferich888 @mffiedler @wabouhamad @schituku 
(this took a while to type)

[Was: https://github.com/openshift/origin/issues/15167]

**Comment by jeremyeder** [comment]
@sjug @adellape @bmcelvee @ahardin-rh @kalexand-rh @rjhowe @sjwalter2 @sferich888 @mffiedler @wabouhamad @schituku

**Comment by adambkaplan** [comment]
survey needs its own gh repo (dates are off)

**Comment by jeremyeder** [comment]
> survey needs its own gh repo (dates are off)

fixed the dates ;)
