### ISSUE TITLE
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications with PVCs [Suite:openshift/conformance/parallel] [Suite:k8s]

### ISSUE THREAD

**Issue by wongma7** [openshift/origin#22084]
In this test, a statefulset is scaled down then back up, so its volume gets detached then immediately attached again.

Recent failure:
https://gubernator.k8s.io/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/4335
In this failure, detach from /dev/xvdbn succeeds at 55:23, and the node.Status.AttachedVolumes must have been updated to remove it beforehand 
https://github.com/kubernetes/kubernetes/blob/54c4428eb4e7c99c825e96d2a480ad4e79bc580f/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L214, yet somehow the kubelet still sees the volume at /dev/xvdbn in its node.Status.AttachedVolumes at 55:27 https://github.com/kubernetes/kubernetes/blob/bf20886f4ea6f99f2d56def9ac9785fab47b1104/pkg/volume/util/operationexecutor/operation_generator.go#L1242

I0217 18:55:23.870200       1 operation_generator.go:420] DetachVolume.Detach succeeded for volume "pvc-237bdecc-32e5-11e9-a8d2-0e426a8ffbde" (UniqueName: "kubernetes.io/aws-ebs/aws://us-east-1b/vol-001b1bc78d3acc117") on node "ip-10-0-144-165.ec2.internal"

Feb 17 18:55:27 ip-10-0-144-165 hyperkube[4173]: I0217 18:55:27.803986    4173 operation_generator.go:1205] Controller attach succeeded for volume "pvc-237bdecc-32e5-11e9-a8d2-0e426a8ffbde" (UniqueName: "kubernetes.io/aws-ebs/aws://us-east-1b/vol-001b1bc78d3acc117") pod "ss-0" (UID: "91effd5a-32e5-11e9-a8d2-0e426a8ffbde") device path: "/dev/xvdbn"

Could this have something to do with there being multiple apiservers, any ideas??

(Another failure a while ago: https://gubernator.k8s.io/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/3676. I concluded the AWS API was somehow giving inconsistent/out-of-date information, i.e. DescribeVolumes says a volume is detached but DescribeInstances ~200ms later wrongly says it is still attached, causing it to wait ~45 minutes for it to show up instead of calling AttachVolume. Unsure what we can do about this one.)

**Comment by wongma7** [comment]
@openshift/storage 
/kind test-flake
this is among the top 10 flaky tests https://testgrid.k8s.io/redhat-openshift-release-blocking#redhat-release-openshift-origin-installer-e2e-aws-4.0&sort-by-flakiness=&width=5

**Comment by wongma7** [comment]
also, note this test does not flake at all upstream.

**Comment by wongma7** [comment]
failure https://gubernator.k8s.io/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/4394 is the same as https://gubernator.k8s.io/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/3676. So it seems there are two concrete causes of these failures.


I0218 18:21:58.689566       1 aws.go:2167] waitForAttachmentStatus returned non-nil attachment with state=detached: {
  AttachTime: 2019-02-18 18:18:35 +0000 UTC,
  DeleteOnTermination: false,
  Device: "/dev/xvdbx",
  InstanceId: "i-05651344c9dd4207f",
  State: "detaching",
  VolumeId: "vol-085a1327d063be07a"
}
I0218 18:21:58.689622       1 operation_generator.go:420] DetachVolume.Detach succeeded for volume "pvc-9544837e-33a9-11e9-8bda-0a4f5a5c3ee4" (UniqueName: "kubernetes.io/aws-ebs/aws://us-east-1c/vol-085a1327d063be07a") on node "ip-10-0-169-147.ec2.internal" 
I0218 18:21:58.717837       1 reconciler.go:289] attacherDetacher.AttachVolume started for volume "pvc-9544837e-33a9-11e9-8bda-0a4f5a5c3ee4" (UniqueName: "kubernetes.io/aws-ebs/aws://us-east-1c/vol-085a1327d063be07a") from node "ip-10-0-169-147.ec2.internal" 
W0218 18:21:58.958447       1 aws.go:1653] Got assignment call for already-assigned volume: bx@vol-085a1327d063be07a
I0218 18:21:58.996366       1 aws.go:1924] Waiting for volume "vol-085a1327d063be07a" state: actual=detached, desired=attached

"aws.go:1653] Got " means that a device was already assigned according to DescribeInstances https://github.com/kubernetes/kubernetes/blob/9fd23b217800a312a45dbaedb70f4ffa65ec661b/pkg/cloudprovider/providers/aws/aws.go#L1750. How can this be if the device was successfully detached ~300ms ago and its assignment released, according to DescribeVolumes?

@jsafrane do you have any ideas about this since you have touched this code before... thx

**Comment by gnufied** [comment]
The kubelet seeing a volume that was detached previously as attached and AWS returning a detached volume in `describeInstance` call are separate issues right?

**Comment by gnufied** [comment]
One way to handle the eventual nature of AWS api is to - call `checkIfAttachedToNode` after `DetachDisk` and make sure that instance stops reporting the volume as attached before returning from `DetachDisk`. This will probably solve second instance of the problem?

**Comment by jsafrane** [comment]
It's a long time ago since I touched the code, I don't see how a volume could have a device assigned while it's detached.
