### ISSUE TITLE
Secrets are not getting the Template labels

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2211]
When you define a 'Secret' resource in the Template it will not get the `template` label when you create it. However the `process` will add the labels into it. This might be an upstream bug (or feature?)

**Comment by mfojtik** [comment]
@smarterclayton @kargakis FYI

**Comment by smarterclayton** [comment]
Why are we still adding template label?  That should have been removed.  That's what object labels are for.

**Comment by danmcp** [comment]
Closing in favor of: https://bugzilla.redhat.com/show_bug.cgi?id=1213273
