### ISSUE TITLE
'oc cp' doesn't show the progress 

### ISSUE THREAD

**Issue by alexxa** [openshift/origin#22118]
I was copying a local file of +30G to a remote pod. There was no any progress displayed, just a blinking cursor, and I wasn't sure if evrth was ok, and how much time it would take to finish.

##### Version
oc v3.11.69
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. oc cp \<a veeeery big local file\> \<remote pod\>:/tmp/

##### Current Result
a blinking cursor 
##### Expected Result
a progress bar as minimum, otherwise output like wget has

**Comment by x775** [comment]
I was about to open a new issue on this very situation, but then I realised this was closed unresolved.

I can confirm that `oc cp` still exhibits this issue with large file transfers (~28GB in my case).

Using version `4.16.8`.

**Comment by alexxa** [comment]
/reopen
as per the comment above. The progress bar / some progress visual for a user would be good to have regardless the file size.
