### ISSUE TITLE
set external ip range for project

### ISSUE THREAD

**Issue by hniedlich** [openshift/origin#22129]
Hello, 

Can anyone provide me info if there is possibility to set project specific external IP range, just like setting cluster wide parameter `externalIPNetworkCIDRs` in `/etc/origin/master/master-config.yaml`.

I was trying setting it manually with many combination of parameters, but none was working. Also searching for this topic was unsuccessfull.

**Comment by mozgbrasil** [comment]
Hello
Good afternoon
I'm also having trouble exposing a MySQL database for remote access, any tips?
