### ISSUE TITLE
Any tool to use to validate an Openshift deployment configuration? 

### ISSUE THREAD

**Issue by manuq21** [openshift/origin#22121]
Wanted to know if there's any tool that can be used to validate that all the features in the deploy configuration file template are well created after the deploy finished. 
Ex. if we defined routes, persistent volumes, services, etc in the config file, if all those features exist, as we requested, after deployment has finished.

thanks

**Comment by adambkaplan** [comment]
When you deploy a template, OpenShift creates a `TemplateInstance` object which reports if the template has been successfully deployed. You can mark certain objects in your template as "critical" by adding the `"template.alpha.openshift.io/wait-for-ready": "true"` annotation, in which case the template instance won't report itself as "Ready" until those objects have themselves deployed and reported ready.

See https://docs.okd.io/3.11/dev_guide/templates.html#waiting-for-template-readiness

@manuq21 does this help?

**Comment by manuq21** [comment]
Thanks. And if we see it from the QA perspective for example? Independently of this check that we can add to be performed. If we want to automate a testing to make sure all features are there, do you know any tool that can achieve that ? I know that we can assume that if "template.alpha.openshift.io/wait-for-ready": "true" is set to each feature, they should be there after deployed, but I'm thinking on the QA side how to check that after deployed.
