### ISSUE TITLE
Add ./hack/rebuild-image.sh to speed up testing of changes made to Docker images

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2212]
Currently if I make a change to pkg/build/builder/cmd I have to run `make release` to get the image updated and tagged as the latest so I can test it. @ncdc provided a nice workaround: https://gist.github.com/ironcladlou/cbf7be944ac87e9f8ead which I wish is what we should have as `./hack/rebuild-image.sh openshift/origin-sti-builder`. 

We can then re-use this script in `make release` passing a second optional attribute with GIT ref.

**Comment by mfojtik** [comment]
@smarterclayton do you think this is a good idea?

**Comment by soltysh** [comment]
:+1: I've been going through that process quite a few times already, just recently when working on git secrets.

**Comment by smarterclayton** [comment]
Isn't this what @ironcladlou's changes do?

**Comment by ironcladlou** [comment]
I think he meant me, not @ncdc. The thing in my gist is a huge hack that takes a local origin binary and commits it into the `latest` tag for `openshift/origin-deployer`. It doesn't count as an image rebuild since it doesn't do a docker build at all.

**Comment by mfojtik** [comment]
@ironcladlou yes, I meant you :-) Right, I can execute the same commands to get origin-sti-builder image updated. The command I propose just simplify this process.

**Comment by smarterclayton** [comment]
Closing due to age.
