### ISSUE TITLE
Is the Openshift API swagger.json exposed anywhere?

### ISSUE THREAD

**Issue by lholmquist** [openshift/origin#22122]
I know there are swagger endpoint docs accessible at `OPENSHIFT_URL/openapi/v2` and also `OPENSHIFT_URL/swagger.json` for the Kubernetes related API's.

Is there also an equivalent endpoint for the Openshift api in swagger format.  I see in this repo, there is this document,  https://raw.githubusercontent.com/openshift/origin/master/api/swagger-spec/openshift-openapi-spec.json,  but i'm not really sure if that is exposed as an endpoint in my Openshift Cluster.

**Comment by jboxman** [comment]
@lholmquist, as near as I can tell, for release-3.11 that file is generated by this script: https://github.com/openshift/origin/blob/release-3.11/hack/update-generated-swagger-spec.sh

Out of curiosity, what were you planning on doing with spec file?

**Comment by lholmquist** [comment]
We have a Node.js module, [openshift-rest-client](https://github.com/nodeshift/openshift-rest-client), that we created and have been adding functionality "manually".

we are looking to refactor the library so it generates the api automatically, instead of us adding things in manually.  There is a nice [kubernetes node module](https://github.com/godaddy/kubernetes-client), which does something similar.  One of the ways it can load the api is querying the running clusters `/openapi/v2` or `/swagger.json` endpoint.

If there isn't a similar endpoint for the Openshift api's,  i can just use this file,  which i've started to do, https://github.com/nodeshift/openshift-rest-client/pull/113

**Comment by jboxman** [comment]
@lholmquist, that looks quite interesting.

My own interest in this is using the OpenShift OpenAPI specs to create REST API docs. I'll let you know if I learn anything helpful.

It does look like a running cluster is queried to generate the spec for 3.11 here: https://github.com/openshift/origin/blob/b6db8e68d78723f943eba6710ab6adc8d4254a2f/hack/update-generated-swagger-spec.sh#L40
