### ISSUE TITLE
OpenShift - 172.30.1.1 needs to be included in the Docker daemon's NO_PROXY environment variable

### ISSUE THREAD

**Issue by Victoria2202** [openshift/origin#22133]
##### Description
My company uses a proxy and if I start the OpenShift Cluster with the following command:

> oc cluster up --skip-registry-check=true --version=v3.6.0

I get the following warnings:

> WARNING: An HTTPS proxy (http://sysetlassi:L9538521@194.114.63.23:8080) is configured for the Docker daemon, but you did not specify one for cluster up
> 
> WARNING: A proxy is configured for Docker, however 172.30.1.1 is not included in its NO_PROXY list.
> 
> 172.30.1.1 needs to be included in the Docker daemon's NO_PROXY environment variable so pushes to the local OpenShift registry can succeed.

How can I start OpenShift, to resolve the Proxy-Problem?

##### Version
v3.6.0

**Comment by adambkaplan** [comment]
@Victoria2202 this is likely a Docker related issue - please provide your OS and version of Docker.

**Comment by Victoria2202** [comment]
The version of the OS is CentOS Linux release 7.5.1804 (Core) and the version of Docker is 18.06.0-ce

**Comment by adambkaplan** [comment]
@Victoria2202 See here for instructions on how to use cluster-up with a proxy: https://github.com/openshift/origin/blob/release-3.6/docs/cluster_up_down.md#using-a-proxy

**Comment by Victoria2202** [comment]
Ok, if I run following command: 
oc cluster up --env NO_PROXY="172.30.1.1"

I tried the following as well:
oc cluster up --no-proxy=[172.30.1.1]


I get still the same error
