### ISSUE TITLE
`oc cluster {up,down,status}` fails when using docker-podman

### ISSUE THREAD

**Issue by bplaxco** [openshift/origin#22147]
#### Is podman supported? 

I have docker-podman installed and when I run oc cluster up, down, or status I get an error complaining that the docker daemon is not running.

```
$ oc cluster status
Error: cannot get state of OpenShift container origin
Caused By:
  Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

##### Version
```
$ oc version
oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. Uninstall docker
1. Install docker-podman
1. Run `oc cluster up`

(I had ran cluster up once before when I had docker installed, not sure if that would make a difference.)

##### Current Result

```
oc cluster status --loglevel=10
I0225 20:46:33.846958    4468 client.go:309] No Docker environment variables found. Will attempt default socket.
I0225 20:46:33.847002    4468 client.go:314] No Docker host (DOCKER_HOST) configured. Will attempt default socket.
I0225 20:46:33.847348    4468 helper.go:230] Inspecting docker container "origin"
I0225 20:46:33.847514    4468 helper.go:237] An error occurred inspecting container "origin": Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: cannot get state of OpenShift container origin
Caused By:
  Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

##### Expected Result
I would expect it to bring up a local cluster (if podman is intended to be supported).

##### Additional Information
```
cat /etc/fedora-release 
Fedora release 29 (Twenty Nine)
```

```
cat `which docker`
#!/usr/bin/sh
[ -f /etc/containers/nodocker ] || \
echo "Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg." >&2
exec /usr/bin/podman "$@"
```

**Comment by rhatdan** [comment]
You need to change to CRI-O if you want to use openshift without Docker. CRI-O is the replacement for kubernetes work loads.

**Comment by bplaxco** [comment]
Ack, thanks. Will go ahead and close this out.

**Comment by praiskup** [comment]
> You need to change to CRI-O

This is first-hit when googling;  what's the way to do this?

**Comment by rhatdan** [comment]
Doesn't https://cri-o.io cover this?
https://github.com/cri-o/cri-o/blob/master/tutorials/kubeadm.md
