### ISSUE TITLE
imagestream limits

### ISSUE THREAD

**Issue by faust64** [openshift/origin#22166]
Looking at https://docs.openshift.com/container-platform/3.11/admin_guide/limits.html#image-stream-limits

If I understand properly, the `openshift.io/image-tag` limitation is broken.

##### Version

```
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
[...]
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce

1. Create sample LimitRange, eg:

```
apiVersion: v1
kind: LimitRange
metadata:
  name: image
spec:
  limits:
  - type: openshift.io/ImageStream
    max:
      openshift.io/image-tags: 1
```

2. Create a BuildConfig, start a build

3. Edit BuildConfig, change the ImageStreamTag, setting a different tag, still pushing to the same ImageStream. Start a new build.

Or:

3. (alt) `oc tag -n <my-ns> <my-image>@<existing-ref> <my-image>:<non-existing-tag>`

##### Current Result

Re-starting a build: new image pushed to registry, new tag created, does show in my ImageStream spec.

Or using `oc tag`: new tag created, does show in my ImageStream spec.

##### Expected Result

According to docs:

> length( uniqueimagetags( imagestream.spec.tags ) ) less than or equal to Max[openshift.io/image-tags]

As such, I would have assumed I should hit an error somewhere, trying to push my image to a new tag, or using `oc tag` on an IS that already reached its `openshift.io/image-tag` limitation.

In practice, I haven't seen anything, I can have 3 tags on my IS, while my LimitRange should prevent having more than 1.

```
$ oc get is
[...]
jenkins-agent-node-sonar   docker-registry.default.svc:5000/scripting/jenkins-agent-node-sonar   retest,letest,latest   3 hours ago
```

Note the doc is a bit confusing on that matter, as it states:

> Resource openshift.io/image-tags represents unique image references. Possible references are an ImageStreamTag, an ImageStreamImage and a DockerImage. They may be created using commands oc tag and oc import-image or by using tag tracking. No distinction is made between internal and external references. However, each unique reference tagged in the image stream’s specification is counted just once. *It does not restrict pushes to an internal container image registry in any way, but is useful for tag restriction*.

Then, assuming a `BuildConfig` would be exempted from that limitation, somehow, `oc tag` should still fail, shouldn't it?

**Comment by adambkaplan** [comment]
@openshift/sig-developer-experience fyi

**Comment by bparees** [comment]
i'm not sure where the division of responsibility is once you get into specific resources like imagestreamtags, but in general quota is the purview of @openshift/sig-master
