### ISSUE TITLE
RFE: Query all roles for a user/serviceaccount

### ISSUE THREAD

**Issue by afcollins** [openshift/origin#22162]
Requesting an enhancement for CLI.  Something like `oc adm policy what-can-i-do <user|serviceaccount>`

Currently, can just use grep on two commands, but seems like a nice-to-have for a single command to return back the same.
```
oc describe clusterrolebindings | grep <user|serviceaccount>
oc describe rolebindings --all-namespaces | grep <user|serviceaccount>
```

**Comment by ryran** [comment]
Agreed. In a perfect world, I would love to query a user or group and be able to see a list of each of the roles that were assigned them. Not sure if the back-end RBAC implementation makes this possible, but that's what I want as an admin.
