### ISSUE TITLE
Typo in osc create error message

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2217]
Notice the missing 'n' in namespace: ` in amespace=foo`
```
❯ osc create -f examples/image-streams/image-streams-centos7.json -namespace=foo
Error: "/osapi/v1beta1/imageStreams?namespace=amespace%3Dfoo" is forbidden because admin cannot create on imageStreams in amespace=foo
```

**Comment by liggitt** [comment]
To use the long form, I think you have to use two dashes: `--namespace=foo`
It seems like `-namespace=foo` is parsing as `-n amespace=foo`, which surprises me.

**Comment by spadgett** [comment]
The space after `-n` is optional using POSIX command-line conventions. I don't think we should change it. My mistake.
