### ISSUE TITLE
Nginx container can't resolve internal DNS hostnames

### ISSUE THREAD

**Issue by atoy3731** [openshift/origin#22216]
When using a variable to proxy to an internal Openshift service within an nginx container's `proxy_pass` config, NGINX can't resolve the service's DNS due to a required `resolver`. For instance:

```
location /api/ {
   set $pass_url http://service.namespace.svc:8080$request_uri;
   proxy_pass  $pass_url;
}
```
When using standard Kubernetes, I can use `kube-dns.kube-system.svc.cluster.local` as the resolver:

```
resolver kube-dns.kube-system.svc.cluster.local;
```

But Openshift doesn't provide this. I've tried using the IP that is in the container's `/etc/resolv.conf`, which is just one of the nodes in my cluster that is running the DNS server, but it still can't resolve.

Weirdest part is `nslookup service.namespace.svc` from inside the container terminal uses the nameserver in `/etc/resolv.conf` and works fine.

Is there an equivalent to the Kubernetes DNS hostname in Openshift I could use?

##### Version
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. Use an NGINX container.
2. Modify a location block in the NGINX configuration to point to an internal service:

```
location /api/ {
   set $pass_url http://service.namespace.svc:8080$request_uri;
   proxy_pass  $pass_url;
}
```
3. Use `ps aux | grep nginx` to find the master PID and reload NGINX via `kill -HUP <pid>`
4. Hit the route at `/api/`
5. Check the NGINX logs.

##### Current Result
NGINX can't resolve internal hostname.

##### Expected Result
NGINX proxies to the internal service.

**Comment by Vandborg** [comment]
I am facing the exact same problem. So I'll just watch this issue, if anybody comes up with a solution. :)

**Comment by ainiml** [comment]
/reopen

having the same issue, unable to use `kube-dns.kube-system.svc.cluster.local` as the resolver

**Comment by omnibrain** [comment]
/reopen

Having the same problem

**Comment by robertofabrizi** [comment]
Anyone has resolved this? I read to use the DNS at master-ip port 8053, but it still fails to resolve (nginx, doing a manual curl from inside the nginx container does work)

**Comment by ainiml** [comment]
> Anyone has resolved this? I read to use the DNS at master-ip port 8053, but it still fails to resolve (nginx, doing a manual curl from inside the nginx container does work)

I wonder if there's been a change to docker

I used to could ping other containers by their docker container name, but not anymore now

**Comment by timothy-thomas** [comment]
I'm having the same problem. Has anyone found a solution to this issue?

**Comment by smsoumitra** [comment]
`resolver  dns-default.openshift-dns.svc.cluster.local valid=10s;`
