### ISSUE TITLE
Image streams not showing up in web console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2224]
Sometimes the Browse -> Image Streams page is empty. Note that the "No images stream" message is not there, and there are no errors in the Chrome dev tools console. I only see this in some projects.

/cc @gshipley 

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7618373/c3c3f9b0-f97f-11e4-894c-a0ec3b53b564.png)

**Comment by spadgett** [comment]
Same problem when creating from source repository.

![openshift_management_console_and_spadgett_on_freenode_irc_network_ _gshipley__gshipley_138_91_145_100_and_css_ _bootstrap](https://cloud.githubusercontent.com/assets/1167259/7618524/93bb292c-f980-11e4-9789-b7bf36364f5b.png)

**Comment by spadgett** [comment]
We're not showing image streams missing `status.tags`.

@ncdc @smarterclayton should that always be defined?

**Comment by smarterclayton** [comment]
You can have empty image streams.  We probably want to revisit the visual display of image stream tags right now.  Let's talk tomorrow.

----- Original Message -----

**Comment by spadgett** [comment]
@smarterclayton @liggitt 

Here's how I loaded the images streams.

```
➜  origin git:(master) osc new-project project4
Now using project "project4" from context named "project4-1" on server "https://localhost:8443".
➜  origin git:(master) osc create -f examples/image-streams/image-streams-centos7.json
imageStreams/ruby
imageStreams/nodejs
imageStreams/perl
imageStreams/php
imageStreams/python
imageStreams/wildfly
imageStreams/mysql
imageStreams/postgresql
imageStreams/mongodb

➜  origin git:(master) osc get imageStreams
NAME         DOCKER REPO                       TAGS
mongodb      openshift/mongodb-24-centos7
mysql        openshift/mysql-55-centos7
nodejs       openshift/nodejs-010-centos7
perl         openshift/perl-516-centos7
php          openshift/php-55-centos7
postgresql   openshift/postgresql-92-centos7
python       openshift/python-33-centos7
ruby         openshift/ruby-20-centos7
wildfly      openshift/wildfly-8-centos

➜  origin git:(master) osc describe imageStreams mongodb                                                                                                                                  <<<
Name:		mongodb
Created:	About an hour ago
Labels:		<none>
Tags:		<none>
Registry:	openshift/mongodb-24-centos7
```

Here's the JSON. `status.tags` is missing, which the web UI requires.

```
    {
      "metadata": {
        "name": "mongodb",
        "namespace": "project4",
        "selfLink": "/osapi/v1beta1/imageStreams/mongodb?namespace=project4",
        "uid": "c7b66c01-fa40-11e4-a132-766512d070d3",
        "resourceVersion": "957",
        "creationTimestamp": "2015-05-14T13:54:46Z"
      },
      "spec": {
        "dockerImageRepository": "openshift/mongodb-24-centos7",
        "tags": [
          {
            "name": "latest"
          }
        ]
      },
      "status": {
        "dockerImageRepository": "openshift/mongodb-24-centos7"
      }
    }
```

**Comment by smarterclayton** [comment]
That means the image change controller is not running.

----- Original Message -----

**Comment by ncdc** [comment]
I don't think this will make a difference (and if it does, it's probably a bug that needs fixing), but please remove `spec.tags` from your json and try again. You only need to include entries there if you're configuring tag annotations or tag tracking.

**Comment by spadgett** [comment]
This is working for me now. I believe the issue was environmental. I'll reopen if I can reproduce.
