### ISSUE TITLE
MetalLB failed to assign ip in OpenShift

### ISSUE THREAD

**Issue by ormazz** [openshift/origin#22246]
hey, 
I'm using openshift 3.9.31 in an on premise environment
i'm trying to use [metalb](https://github.com/google/metallb) and there is a problem with the externalIp mechanism described [here](https://github.com/google/metallb/issues/342)
is there any way to disable to extrnalIP controller? 

thank you, best regards.

**Comment by yboaron** [comment]
@ormazz 
I tried to deploy the METALLB on my Openshift environment (following the instructions from https://metallb.universe.tf/tutorial/layer2/) , and I got the following errors (related to SCC and permissions) [1] upon creating of the controller deployment and speaker daemonset .

Did you change/customize the metallb manifest file?
Thanks 
Yossi
[1] https://pastebin.com/ZVLJM3Lv

**Comment by hniedlich** [comment]
@yboaron You need to add controller and speaker serviceaccounts to privileged scc, than it will deploy without warning.

**Comment by ormazz** [comment]
> @yboaron You need to add controller and speaker serviceaccounts to privileged scc, than it will deploy without warning.

yes i added privileged scc to controller and speaker  and also hostnetwork scc to the speaker as well

one more thing that i did is to change the externalIPNetworkCIDRs: to 0.0.0.0/16 (in this configuration it only assign one time externalIP and not going into loop)

**Comment by zdzichu** [comment]
Ping?

**Comment by smarterclayton** [comment]
If externalIPCIDR is unset the controller should be disabled.

**Comment by jijiechen** [comment]
Another year has past, I hope the original author had solved the problem.
For those who run into this issue again and are looking for solutions, here you are:

For OpenShift 3.x versions, to disable this "gift" of auto assigning IPs, Please update `ingressIPNetworkCIDR` to `0.0.0.0/32` in your `master-config.yaml`. Please follow [instructions in the docs](https://access.redhat.com/documentation/en-us/openshift_container_platform/3.10/html/cluster_administration/admin-guide-unique-external-ips-ingress-traffic) to update this file and restart your master nodes.

```yaml
networkConfig:
  ingressIPNetworkCIDR: '0.0.0.0/32'
```
