### ISSUE TITLE
CatalogImagesController.templatesByTag is never called

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2225]
The `templatesByTag` function in `CatalogImagesController` never appears to be used.

**Comment by spadgett** [comment]
Strange that jshint doesn't warn about this. @benjaminapetersen do you know why?

Related to #3423

**Comment by benjaminapetersen** [comment]
Great Q.  Could be because jshint isn't running for both watch & build until after #3423 gets pulled in, or because the .jshint configs in ./ and ./test have had inconsistent rules.
