### ISSUE TITLE
oc cluster can't connect to outside resources

### ISSUE THREAD

**Issue by GaramNick** [openshift/origin#22269]
OC Can't connect to resources outside.
##### Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Ubuntu 18.04.02 on AWS EC2
All outgoing connections are allowed.

##### Steps To Reproduce
1. Fresh install v3.11
2. oc cluster up
3. Create new project with public git repo ~ in my case https://github.com/encode/rest-framework-tutorial.git

##### Current Result
Build failed: Fetch source failed

Cloning "https://github.com/encode/django-rest-framework.git " ...
WARNING: timed out waiting for git server, will wait 1m4s
error: fatal: unable to access 'https://github.com/encode/django-rest-framework.git/': Could not resolve host: github.com; Unknown error

##### Expected Result
Build Succeeds

##### Additional Information
Diagnostics:
```
ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/oc/cli/admin/diagnostics/diagnostics/client/pod/run_diagnostics_pod.go:208]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected
              
       Info:  Service account token successfully authenticated to master
       
ERROR: [DP1014 from diagnostic PodCheckAuth@openshift/origin/pkg/oc/cli/admin/diagnostics/diagnostics/client/pod/in_pod/auth.go:172]
              Request to integrated registry timed out; this typically indicates network or SDN problems.
              
       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected
              
WARN:  [DP2014 from diagnostic PodCheckDns@openshift/origin/pkg/oc/cli/admin/diagnostics/diagnostics/client/pod/in_pod/dns.go:145]
              A request to the nameserver [172.30.0.2] timed out.
              This could be temporary but could also indicate network or DNS problems.
              
       [Note] Summary of diagnostics execution (version v3.11.0+d0c29df-98):
       [Note] Warnings seen: 1
       [Note] Errors seen: 1
```

**Comment by jiangytcn** [comment]
hello Experts

I also had the issue with dns resolution.

Created a sample dockerfile build, but failed to fetch alpine repository. And I could manually build container image in the host  and also verified the network is working fine in the `dns` pod, is there anything I missed or some extra networking policies need to be configured ? 

thanks

```
FROM alpine:latest

COPY . /data
WORKDIR /data

RUN echo "===> install pkgs" && \
    apk add python --repository http://dl-3.alpinelinux.org/alpine/v3.9/main

CMD echo "hello"
```

BC logs

```
Removing intermediate container 5aa7bcb278b8
 ---> 2d25ec7e3b24
Step 6/9 : RUN echo "===> install pkgs" &&     apk add python --repository http://dl-3.alpinelinux.org/alpine/v3.9/main
 ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
 ---> Running in 61d3566e823b
===> install pkgs
fetch http://dl-3.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-3.alpinelinux.org/alpine/v3.9/main: DNS lookup error
WARNING: Ignoring APKINDEX.4aa28c02.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/main: DNS lookup error
WARNING: Ignoring APKINDEX.b89edf6e.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/community: DNS lookup error
WARNING: Ignoring APKINDEX.737f7e01.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  python (missing):
    required by: world[python]
Removing intermediate container 61d3566e823b
error: build error: The command '/bin/sh -c echo "===> install pkgs" &&     apk add python --repository http://dl-3.alpinelinux.org/alpine/v3.9/main' returned a non-zero code: 1
```

**Comment by srinivas-kandula** [comment]
I am having the same issue Getting below error:
`
       Info:  Service account token successfully authenticated to master

       ERROR: [DP1014 from diagnostic PodCheckAuth@openshift/origin/pkg/oc/cli/admin/diagnostics/diagnostics/client/pod/in_pod/auth.go:172]
              Request to integrated registry timed out; this typically indicates network or SDN problems.

       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected

       WARN:  [DP2014 from diagnostic PodCheckDns@openshift/origin/pkg/oc/cli/admin/diagnostics/diagnostics/client/pod/in_pod/dns.go:145]
              A request to the nameserver [172.30.0.2] timed out.
              This could be temporary but could also indicate network or DNS problems.

       [Note] Summary of diagnostics execution (version v3.11.0+01dd962-225):
       [Note] Warnings seen: 1
       [Note] Errors seen: 1
`

Am i missing anything? Any help on this regard is appreciated.
