### ISSUE TITLE
APPLICATION_DOMAIN is empty in container if route is default set from openshift

### ISSUE THREAD

**Issue by elytscha** [openshift/origin#22276]
APPLICATION_DOMAIN gets not set as env variable to container from template if its default

##### Steps To Reproduce
1. provide the APPLICATION_DOMAIN as Variable in a Template like:
```
    {
      "name": "APPLICATION_DOMAIN",
      "displayName": "Application Hostname",
      "description": "Enter a valid URL for your Nextcloud, eg *.cloud.example.com",
      "value": "",
    },
```
2. substitute the variable to a deploymentconfig like:
```
{
                    "name": "APPLICATION_DOMAIN",
                    "value": "${APPLICATION_DOMAIN}"
},
```
3. Deploy the Template without setting a APPLICATION_DOMAIN
4. Template Instance gets provisioned with default route
5. open a terminal to the container in the webinterface or via the OC CLI and print: 
`env | grep APPLICATION_DOMAIN`

##### Current Result
`APPLICATION_DOMAIN=`

##### Expected Result
`APPLICATION_DOMAIN=automatically-added-route.apps.example.com
`
##### Additional Information
So i didnt found a way to get the container to know his route if no route is set and default route is applied

Workaround:
```
    {
      "name": "APPLICATION_DOMAIN",
      "displayName": "Application Hostname",
      "description": "Enter a valid URL for your Nextcloud, eg *.cloud.example.com",
      "value": "",
      "required": true
    },
```
set required: true so you have to set the route by your own, btw specify it directly in the rest-api call to create a new template instance
then the result from:
`env | grep APPLICATION_DOMAIN`
is like:
`APPLICATION_DOMAIN=self-set-route.apps.example.com`

**Comment by atgreen** [comment]
/remove-lifecycle stale

This is an annoying limitation.  I hope that it is fixed.
