### ISSUE TITLE
failed to allocate for range 0: no IP addresses available in range set

### ISSUE THREAD

**Issue by faust64** [openshift/origin#22353]
Running a test cluster, 3.11. While I've seen that very same behavior on several production clusters (3.9)

##### Version

Seen on OKD 3.11 : v3.11.0+d0c29df-98

As well as OCP 3.9.51

##### Steps To Reproduce

1. deploy Pods to cluster (having deployed cluster setting  `openshift_use_crio=True` ?)

2. wait for it ...

##### Current Result

Eventually, Pods are no longer able to start on some given nodes.

```
Mar 16 02:21:27 master3 crio: time="2019-03-16 02:21:27.115669603+01:00" level=error msg="Error adding network: CNI request failed with status 400: 'failed to run IPAM for be725fadc530ab74ffa4f3e833e0b5d55191dbe886da83a23e4ab388bc43a8c3: failed to run CNI IPAM ADD: failed to allocate for range 0: no IP addresses available in range set: 10.130.0.1-10.130.1.254
Mar 16 02:21:27 master3 crio: '"
Mar 16 02:21:27 master3 crio: time="2019-03-16 02:21:27.115766944+01:00" level=error msg="Error while adding to cni network: CNI request failed with status 400: 'failed to run IPAM for be725fadc530ab74ffa4f3e833e0b5d55191dbe886da83a23e4ab388bc43a8c3: failed to run CNI IPAM ADD: failed to allocate for range 0: no IP addresses available in range set: 10.130.0.1-10.130.1.254
Mar 16 02:21:27 master3 crio: '"
```

##### Expected Result

Pods starts. Whenever a Pod is somehow removed from a node, OpenVSwitch database should get updated.

##### Additional Information

Can be fixed by draining affected nodes, then removing  `/var/lib/cni/networks/openshift-sdn/*`
and `/etc/origin/openvswitch/conf.db`.

The cluster I'm running has no more than 85 Pods spread among 11 nodes. It was deployed 27 days ago, which seems enough to exhaust about 512 IPs.

I'm seeing that behavior on 3.9 clusters as well. So far, I've only seen that behavior on clusters running crio (either crio only, or alongside docker). Yet I'm not certain there's a relation.

Having a workaround is nice. Yet when running a production cluster, it's barely acceptable.
Draining production nodes can take over 30 minutes, leading to cri-o corruptions (see https://bugzilla.redhat.com/show_bug.cgi?id=1666198), zombies process can be left while crio runtime was shut down, ... leading to database corruptions/having two processes accessing the same PVs, ... All in all, purging OVS databases on a prod cluster can take up to 1 hour per node.

**Comment by faust64** [comment]
/remove-lifecycle rotten

that's still an issue, on 3.11. Couldn't check 4.x as of yet.

**Comment by faust64** [comment]
yet-another-customer contacting me about this.
Running 3.11.141. with crio and docker runtime.

**Comment by jfcoz** [comment]
Issue is still present

/remove-lifecycle stale
