### ISSUE TITLE
application build taking a very long time if the compute node placed on different host/machine

### ISSUE THREAD

**Issue by gielvandanu** [openshift/origin#22352]
I have installed Openshift OKD 3.11 cluster with 3 nodes (CentOS 7) on 2 hosts/machine using Proxmox 5.1 with this setup :
1. Host A : 1 Master-infra node & 1 Compute-2 node
2. Host B : 1 Compute-1 node

inventory file :

> [OSEv3:children]
> masters
> nodes
> etcd
> 
> 
> [OSEv3:vars]
> 
> ansible_ssh_user=root
> 
> 
> openshift_deployment_type=origin
> openshift_disable_check=disk_availability,memory_availability
> 
> openshift_master_default_subdomain=apps.opensif.it
> 
> AllowAllPasswordIdentityProvider
> openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
> openshift_master_htpasswd_file='/etc/origin/master/htpasswd'
> 
> [masters]
> master.opensif.it
> 
> [etcd]
> master.opensif.it
> 
> [nodes]
> master.opensif.it openshift_node_group_name="node-config-master-infra"
> compute-1.opensif.it openshift_node_group_name="node-config-compute"
> compute-2.opensif.it openshift_node_group_name="node-config-compute"

The problem is when I try to create new app (example app from okd) via web console, it takes a lot of time to complete if the new app build assigned to **compute-1 node** which is on different proxmox host. (the total duration is 27 minutes, 51 seconds).

oc get events :
> 4:23:56 PM	django-ex-1-9j4qs	Pod	Normal	Started 	Started container
4:23:55 PM	django-ex-1-9j4qs	Pod	Normal	Created 	Created container
4:23:54 PM	django-ex-1-9j4qs	Pod	Normal	Pulled 	Successfully pulled image "docker-registry.default.svc:5000/python/django-ex@sha256:9ff1313551e35d3a5b74d1a0fcaaea2e469831eb3ed8e4cb8c6f9cbbe3d0db58"
4:23:54 PM	django-ex-1-9j4qs	Pod	Normal	Pulling 	pulling image "docker-registry.default.svc:5000/python/django-ex@sha256:9ff1313551e35d3a5b74d1a0fcaaea2e469831eb3ed8e4cb8c6f9cbbe3d0db58"
4:23:51 PM	django-ex-1-9j4qs	Pod	Normal	Scheduled 	Successfully assigned python/django-ex-1-9j4qs to compute-1.opensif.it
4:23:51 PM	django-ex-1	Replication Controller	Normal	Successful Create 	Created pod: django-ex-1-9j4qs
4:23:50 PM	django-ex-1-deploy	Pod	Normal	Started 	Started container
4:23:50 PM	django-ex-1-deploy	Pod	Normal	Created 	Created container
4:23:49 PM	django-ex-1-deploy	Pod	Normal	Pulled 	Container image "docker.io/openshift/origin-deployer:v3.11.0" already present on machine
4:23:48 PM	django-ex-1	Build	Normal	Build Completed 	Build python/django-ex-1 completed successfully
**4:23:47 PM	django-ex-1-deploy	Pod	Normal	Scheduled 	Successfully assigned python/django-ex-1-deploy to compute-2.opensif.it**
4:23:47 PM	django-ex	Deployment Config	Normal	Deployment Created 	Created new replication controller "django-ex-1" for version 1
**3:56:16 PM	django-ex-1-build	Pod	Normal	Started 	Started container**
3:56:15 PM	django-ex-1-build	Pod	Normal	Created 	Created container
3:56:14 PM	django-ex-1-build	Pod	Normal	Pulled 	Container image "docker.io/openshift/origin-docker-builder:v3.11.0" already present on machine
3:56:12 PM	django-ex-1-build	Pod	Normal	Started 	Started container
3:56:11 PM	django-ex-1-build	Pod	Normal	Created 	Created container
3:56:10 PM	django-ex-1-build	Pod	Normal	Pulled 	Container image "docker.io/openshift/origin-docker-builder:v3.11.0" already present on machine
3:56:03 PM	django-ex-1	Build	Normal	Build Started 	Build python/django-ex-1 is now running
3:56:02 PM	django-ex-1-build	Pod	Normal	Started 	Started container
3:56:01 PM	django-ex-1-build	Pod	Normal	Created 	Created container
3:56:00 PM	django-ex-1-build	Pod	Normal	Pulled 	Container image "docker.io/openshift/origin-docker-builder:v3.11.0" already present on machine
3:55:59 PM	django-ex-1-build	Pod	Normal	Scheduled 	Successfully assigned python/django-ex-1-build to **compute-1.opensif.it**

Seems like the build temporarily stop/wait about more than 20 minutes before its start to deploy (from 3:56:17 PM to 4:23:27 PM). 

For comparison, if the app build assigned to compute-2 node which on the same proxmox host with the master-infra node. No issue, the build complete below 5 minutes using example app from the okd. 
oc get events : 

> 4:35:06 PM	dancer-ex-1-ssvpk	Pod	Normal	Started 	Started container
4:35:06 PM	dancer-ex-1-ssvpk	Pod	Normal	Created 	Created container
4:35:05 PM	dancer-ex-1-ssvpk	Pod	Normal	Pulled 	Successfully pulled image "docker-registry.default.svc:5000/perl/dancer-ex@sha256:ed1939b03f98b1d87f9bd488def8c9a7c113816ed477f3f0a36ba7c61f560f29"
4:35:05 PM	dancer-ex-1-ssvpk	Pod	Normal	Pulling 	pulling image "docker-registry.default.svc:5000/perl/dancer-ex@sha256:ed1939b03f98b1d87f9bd488def8c9a7c113816ed477f3f0a36ba7c61f560f29"
4:35:03 PM	dancer-ex-1-ssvpk	Pod	Normal	Scheduled 	Successfully assigned perl/dancer-ex-1-ssvpk to compute-2.opensif.it
4:35:03 PM	dancer-ex-1	Replication Controller	Normal	Successful Create 	Created pod: dancer-ex-1-ssvpk
4:35:01 PM	dancer-ex-1-deploy	Pod	Normal	Started 	Started container
4:35:01 PM	dancer-ex-1-deploy	Pod	Normal	Created 	Created container
4:35:00 PM	dancer-ex-1-deploy	Pod	Normal	Pulled 	Container image "docker.io/openshift/origin-deployer:v3.11.0" already present on machine
4:34:56 PM	dancer-ex-1	Build	Normal	Build Completed 	Build perl/dancer-ex-1 completed successfully
4:34:56 PM	dancer-ex-1-deploy	Pod	Normal	Scheduled 	Successfully assigned perl/dancer-ex-1-deploy to compute-1.opensif.it
4:34:56 PM	dancer-ex	Deployment Config	Normal	Deployment Created 	Created new replication controller "dancer-ex-1" for version 1
4:31:22 PM	dancer-ex-1-build	Pod	Normal	Started 	Started container
4:31:21 PM	dancer-ex-1-build	Pod	Normal	Created 	Created container
4:31:21 PM	dancer-ex-1-build	Pod	Normal	Pulled 	Container image "docker.io/openshift/origin-docker-builder:v3.11.0" already present on machine
4:31:19 PM	dancer-ex-1-build	Pod	Normal	Started 	Started container
4:31:19 PM	dancer-ex-1-build	Pod	Normal	Created 	Created container
4:31:19 PM	dancer-ex-1-build	Pod	Normal	Pulled 	Container image "docker.io/openshift/origin-docker-builder:v3.11.0" already present on machine
4:31:13 PM	dancer-ex-1	Build	Normal	Build Started 	Build perl/dancer-ex-1 is now running
4:31:13 PM	dancer-ex-1-build	Pod	Normal	Started 	Started container
4:31:12 PM	dancer-ex-1-build	Pod	Normal	Created 	Created container
4:31:12 PM	dancer-ex-1-build	Pod	Normal	Pulled 	Container image "docker.io/openshift/origin-docker-builder:v3.11.0" already present on machine
4:31:10 PM	dancer-ex-1-build	Pod	Normal	Scheduled 	Successfully assigned perl/dancer-ex-1-build to **compute-2.opensif.it**

There is no problem with the network/LAN, since our VM for production run on the same machine too, and it work perfectly.

Do you guys have any suggestions, what should I check? Since proxmox using KVM for its VM guest. Could be this is the problem?

##### Version
[root@master ~]# oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.opensif.it:8443
openshift v3.11.0+92b7c41-132
kubernetes v1.11.0+d4cacc0

[root@master ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-91.git07f3374.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      07f3374/1.13.1
 Built:           Wed Feb 13 17:10:12 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-91.git07f3374.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      07f3374/1.13.1
 Built:           Wed Feb 13 17:10:12 2019
 OS/Arch:         linux/amd64
 Experimental:    false

##### Steps To Reproduce
1. Create new application via web console

##### Current Result
The build taking very long time to complete, if the build assiged to compute node on different host.

##### Expected Result
Normal build duration wherever the compute node is placed. the same host with master or different host

##### Additional Information
At first I think it was the network. But then I install the cluster using the same setup except it runs on 2 vmware esxi hosts, and it connect to the same network too.

**Comment by adambkaplan** [comment]
@gielvandanu Check the actual build log with timestamps - `$ oc logs build/django-ex-1 --timestamps`

**Comment by gielvandanu** [comment]
I resolved the problem. The problem was the kernel on Host B which run different kernel than Host A. I migrate the compute-1 node to Host C (has the same kernel version with Host A). The build duration is normal.

Thank You.
