### ISSUE TITLE
Can't get to console with Firefox with bad certificate

### ISSUE THREAD

**Issue by mnagy** [openshift/origin#2235]
When using either libvirt or aws vagrant provider, following the sample-app walkthrough, I fail to get to the web console. After warning that the connection is insecure, clicking on "Add exception" does nothing. Using chrome works.

**Comment by mnagy** [comment]
cc @rhcarvalho

**Comment by rhcarvalho** [comment]
Isn't it a Firefox bug? The problem for me was that clicking the button to
ignore the certificate has no effect.

**Comment by mnagy** [comment]
I'm not sure, but this never happened to me for other sites, so I suspect that maybe retrieving the certificate from the server might have failed and chrome doing something different. Would be nice to test it with some other firefox version.

**Comment by liggitt** [comment]
There is a bug with the "Add exception" button in Firefox 37 (fixed in Firefox 38)

**Comment by liggitt** [comment]
That said, we were just made aware of another issue with Firefox 38 which is rejecting certificates containing IP addresses as DNS subjectAltName entries. The bootstrap certificates we generate contain IP addresses as DNS subjectAltName entries for compatibility with various TLS implementations (Python and Windows prior to Windows 10, to name a couple).

**Comment by danmcp** [comment]
Closing in favor of: https://bugzilla.redhat.com/show_bug.cgi?id=1218486
