### ISSUE TITLE
error: a port needed by OpenShift is not available

### ISSUE THREAD

**Issue by Steinbjarne** [openshift/origin#22381]
Oc cluster up give error message, port not avaialbe.

##### Version
RHEL 7.6 (maipo)

```oc version```

```
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://os-m.dev.centevo.no:8443
openshift v3.11.0+92b7c41-132
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
```oc cluster up```

##### Current Result
```
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
error: a port needed by OpenShift is not available
```

##### Expected Result
cluster starts

**Comment by Genzer** [comment]
I second this. Today I got the same issue. We are installing OKD onto our AWS infrastructure using Ansible (only for the deployment).

We got the same issue when we executed `oc cluster up`.

**Comment by sushilkumarm** [comment]
@Genzer @Steinbjarne We are also getting same error in OKD oc v3.11 while bringing up the cluster.  Please suggest if you found some solution for it. 

 #oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...

**Comment by Steinbjarne** [comment]
Sort of.
My case was that I had some left overs from a previous installation, so some processes and installation procedures are not cleaned up properly. Port 53 was in use and I had to clean it manually.

**Comment by nayakmahesh** [comment]
Same here
oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
error: a port needed by OpenShift is not available

**Comment by vinchauhan** [comment]
Need to stop running existing instance of minukube..

**Comment by benweizhu** [comment]
```
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking prerequisites for port forwarding ...
Checking if required ports are available ...
error: a port needed by OpenShift is not available
```

I have the same issue on mac. I resolve this by turn on and turn off kubernetes.

![image](https://user-images.githubusercontent.com/5471228/56941680-94d03080-6b48-11e9-93fc-fcf2f9a29f16.png)

I guess it's the kube docker process the some ports.

**Comment by sushilkumarm** [comment]
I am not clear with the solution. Could you please help me with command to stop kubernetes service in openshift deployment ?

**Comment by vinchauhan** [comment]
minikube stop. If you are running on local

**Comment by sushilkumarm** [comment]
It's not a minikube setup

**Comment by Steinbjarne** [comment]
I used the tar ball installation of OpenShift, not minikube.

To clean up, I manually deleted all existing openshift configuration and docker containers and -images. Some of the configuration could not be removed because "file in use".
Thus had to reboot server. Restarting services for docker did not help.

After reboot, I deleted images and configuration again, successful this time, and just to make sure, I restarted docker service.

After that, it was possible to install with oc cluster up, but it is just too many bugs in the install so we chose to abandon and wait for 4.0, or install Kubernetes or Docker Swarm instead.

**Comment by ivandov** [comment]
I hit this as well after doing an `oc cluster down` ... restarting the Docker service seems to fix it pretty quickly.

**Comment by ShaoLun6503** [comment]
```
oc cluster down
systemctl restart docker
systemctl list-units --type=service
```
Then use `systemctl stop` to stop service which you think it might be relative to OKD.
Now `oc cluster up` works

**Comment by Steinbjarne** [comment]
This is an old case, and case is closed. Both last two suggestings were attempted, either dreict or indirect.
Full clean of all containers, restarting docker, tweeking docker, manually removing kubernetes containers, restarting all related services and so on. One of the bugfixes in release after fixed the issues.

**Comment by anandrkskd** [comment]
In my case, I was using microk8s on my machine, I stopped microk8s service and then tried again and then it worked fine for me.
So, I suppose that 
-  first stop k8s service
-  second retry `oc cluster up`
hope it helps!

**Comment by Genzer** [comment]
I had shutdown and retried and the process succeeded.

One important thing: I always had problems using Ansible 2.7 to run the playbook of v3.11 tag. Using Ansible 2.6.5 guaranteed the playbook successful.

**Comment by rfwankenobi** [comment]
I didn't have minikube enabled, but I did have microk8s installed too. Stopped microk8s and oc cluster up worked.

**Comment by omeryounus** [comment]
make sure that kubelet.service is not running while starting up oc cluster

**Comment by yurisyb** [comment]
You can stop and start kubelet.
before installation 
systemctl stop kubelet.
#then
oc cluster up --public-hostname=127.0.0.1
#run
systemctl start kubelet
