### ISSUE TITLE
Rolling Params missing in application-template-stibuild.json

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin#2242]
Ref https://github.com/openshift/origin/issues/2216#issuecomment-102035323

@ironcladlou  A change you made to the sample template?

/cc @spadgett

**Comment by ironcladlou** [comment]
The params are missing in the template because they're not required: we supply defaults. I'll check into why that might not be happening in #2216.

**Comment by ironcladlou** [comment]
Looks like there's some issue with the REST API causing defaults to not be applied (whereas create the same resource w/ the same JSON payload with `osc create` works fine). Still investigating.
