### ISSUE TITLE
Failed to decode DeploymentConfig from controller: couldn't get version/kind: unexpected end of JSON input

### ISSUE THREAD

**Issue by brenton** [openshift/origin#2245]
Has anyone seen this?  I just built the latest from master and I tried creating the registry with --latest-images.

**Comment by brenton** [comment]
@smarterclayton, it seems like something is wrong with the v0.5.1 deployer image in the dockerhub.  I built the latest images locally and things are working as expected.

**Comment by smarterclayton** [comment]
@ironcladlou ?

**Comment by brenton** [comment]
Specifically the image that is failing is `docker.io/openshift/origin-deployer                v0.5.1              c4dd8800050b`

**Comment by ironcladlou** [comment]
That one's new to me... when will new images be pushed to dockerhub?

**Comment by smarterclayton** [comment]
So 0.5.1 is broken.

----- Original Message -----

**Comment by 126ium** [comment]
I got the same error. After I rolled back to a version released on last week, everything works perfect with v0.5.1 c4dd8800050b. So is something wrong with our new code updates instead of the image?

**Comment by smarterclayton** [comment]
@abhgupta this may have broken.

**Comment by liggitt** [comment]
We need a new tag. Starting with --latest-images works

**Comment by liggitt** [comment]
The problem is the 0.5.1 tagged version of the deployer not being able to find the annotations when running against a daily build. The annotation was changed in https://github.com/openshift/origin/pull/2227

**Comment by smarterclayton** [comment]
The annotations should have been backward compatible.

**Comment by liggitt** [comment]
not sure how that's possible. by double annotating?

**Comment by liggitt** [comment]
I thought the point was to stop adding unnamespaced annotations to core k8s objects...

**Comment by smarterclayton** [comment]
We should have been to be forward compatible.  But someone didn't think through the implications.

----- Original Message -----

**Comment by abhgupta** [comment]
We cut a new version and built new images. We chose not to fix this.
