### ISSUE TITLE
Apparent memory leak in master-api pods OKD v3.10 after applying CentOS updates

### ISSUE THREAD

**Issue by skynardo** [openshift/origin#22491]
We had an existing, stable cluster running 3 master nodes, 3 separate etcd nodes, 3 infra nodes and several worker nodes.  We applied rolling updates (yum update all) to all nodes followed by reboots. A few hours laster we noticed Memory utilization climbing on our Master nodes. Checking top on the Masters show the master-api process as being the culprit, high cpu and growing memory utilization. Once the EC2 instance reaches 90% memory utilization we have been issuing /usr/local/bin/master-restart api to free up memory.

##### Version
[root@ip-172-20-20-30 ~]# oc version
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.apps.nonprod.openshift.local:443
openshift v3.10.0+c99b16a-90
kubernetes v1.10.0+b81c8f8provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
set yum repo to centos-openshift-origin310
run yum update (on all nodes in cluster serially, then reboot to pick up new kernel)
Watch memory utilization on master nodes, observe continuous increasing utilization for master-api
master-api log and /var/log/messages scrolling the error below (multiple times per second)
Apr  5 12:58:40 ip-172-20-20-30 journal: E0405 12:58:40.092264       1 watch.go:274] unable to encode watch object: expected pointer, but got invalid kind
I know there were updates to both docker and etcd versions applied. I will attach a yum.log from one of the systems.
[master0.yum.log.gz](https://github.com/openshift/origin/files/3048035/master0.yum.log.gz)

######## Expected results
Stable cluster and memory utilization

##### Additional Information

[master0.var.log.messages.gz](https://github.com/openshift/origin/files/3048003/master0.var.log.messages.gz)
![top](https://user-images.githubusercontent.com/26174514/55629967-23d06f80-577a-11e9-89b3-a4802c122383.png)

**Comment by skynardo** [comment]
Further troubleshooting found that we had several ( over 30 ) project jenkins ci pods were continuously spewing errors like the below:

Apr  5 12:37:26 ip-172-20-22-100 journal: INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Apr  5 12:37:26 ip-172-20-22-100 journal: Apr 05, 2019 12:37:26 PM okhttp3.internal.platform.Platform log
Apr  5 12:37:26 ip-172-20-22-100 journal: INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Apr  5 12:37:26 ip-172-20-22-100 journal: Apr 05, 2019 12:37:26 PM okhttp3.internal.platform.Platform log

We ran a job to kill all of these Jenkins pods and this resolved the issue with our overloaded masters.

**Comment by ct-23** [comment]
We are seeing the same behavior since 2019-04-29 08:50.

It seems like all Jenkins suddenly started to spew errors like the one mentioned above. 
The requests of the Jenkins' led to a memory utilization up to a point where Linux oom-killed the master-api-process.
![image](https://user-images.githubusercontent.com/358385/57136829-4b811a80-6dae-11e9-807a-9bbfe60a9de3.png)

Killing all Jenkins Pods solved the issue until now.


**Version**
~ $ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://os.xxx.de:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
 timme04@xxx

**Comment by skynardo** [comment]
So you are saying that killing your Jenkins pods did not resolve the issue? When we patched our prod environment a couple weeks ago we had the same issue (only have one Jenkins in prod however) and killing it resolved the errors/requests. It seemed to have started while patching / rebooting our 3 etcd instances (we are running etcd on separate ec2 instances.  Also, see using HTTP/2 on the following page. We have not implemented this (yet). https://wiki.jenkins.io/display/JENKINS/Starting+and+Accessing+Jenkins

**Comment by ct-23** [comment]
Killing the Jenkins pods _did_ resolve the issue. So, thanks for that hint.
We will continue to monitor the issue, but we still don't quite get its root cause.
Our etcd is colocated on our master. I'm not aware of any restarts of etcd when the issue arose.

**Comment by skynardo** [comment]
Unfortunately this problem persists at OKD v3.11.  This past weekend we temporarily lost our primary master which triggered the start of the "ALPN callback dropped: HTTP/2 is disabled." (We have now dubbed this the Alpine Loop) on our 40 plus Jenkins PODS which in turn flooded the master-api and ran the EC2 instance out of memory.
