### ISSUE TITLE
Not possible to create paused ImageChangeTrigger on BuildConfig with CLI

### ISSUE THREAD

**Issue by JohanNordlinder** [openshift/origin#22538]
##### Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
Try to create an ImageChangeTrigger on a BuildConfig using `oc set triggers bc/foo --from-image bar`  without triggering a build upon creation.

##### Current Result
Not possible

##### Expected Result
Being able to specify the parameter `--paused=true` or similar

##### Additional Information
The possibility to create a paused ICT to a BC was added in https://github.com/openshift/origin/pull/19624 but it seems the oc cli was never updated to also support this.

**Comment by adambkaplan** [comment]
@openshift/sig-developer-experience
