### ISSUE TITLE
Provide better experience for new users with 'oc cluster up'

### ISSUE THREAD

**Issue by amalic** [openshift/origin#22541]
For users wanting to play around with `oc cluster up` on `Docker` the experience is quite painful. 

In my opinion running a local cluster for playing around should be configured as open as possible. Both outgoing networking and installing docker containers from Dockerhub should work out of the box.

I would prefer to lern how to secure stuff, instead of how do I remove security.

For me, the experience was painful. Tutorials did not work, because Openshift was not able to access Gitlab repos. Running containers from Gitlab did not work because of the default security context.

I don't know if you expect people to have already secure registries and a hardened setup in place when the start playing around with Openshift. I believe users migth decide against Openshift after having all those issues.

**Comment by praveenkumar** [comment]
@amalic there is no more `oc cluster up` for openshift-4 and it is replaced with `openshift-install` https://github.com/openshift/installer take a look into it.

**Comment by amalic** [comment]
Thanks @praveenkumar . Will look into it after work. As I see, there is a tutorial for CentOs. If OpenShift is in reality focussing on RHEL based Linux flavors, it would be great to have this as a big fat hint on the website, so people don't waste their time trying to figure out what they did wrong.

Please keep in mind that most development clusters will run on a Debian based Linux (if people don't give up first). Currently on Distrowatch Top 5 distros are Debian based. I started yesterday already to resize my partitions to squeeze an additional CentOS on my workstation to see if the installation experience is going to be better.

**Comment by magick93** [comment]
@amalic - sounds like you need to make the default `developer` into a cluster admin. Also there maybe issues with dns resolution. 

If you have problems with dns resolution try editing `openshift.local.clusterup/kubedns/resolv.conf` and adding:
```
nameserver 8.8.8.8
```
As the only nameserver.

Unfortunately OpenShift 4.1 and the `openshift-installer` looks to be far more complicated that `oc cluster up`. I wouldnt recommend using OpenShift 4 until they can make easier, at least as easy, if not easier, that using `oc cluster up`. Compare running a single command to all the steps and problems that come with https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md

**Comment by svenstaro** [comment]
`oc cluster up` is really quite important for our developers and considering that we'll be switching to 4.1 soon, I'm curious what the new "get started easily as a developer" guide is. Does such a thing exist?

**Comment by amalic** [comment]
I actually managed to get it worki g on Ubuntu 18.04+

I had to replace `systemd-resolved` with `dnsmasq`. Wasn't aware of that until i did some ETFM. Would be cool if `oc cluster up` could check this on startup.

**Comment by pingers** [comment]
Another solution without installing dnsmasq would be to copy the actual systemd resolv.conf into your openshift data-dir and restart your cluster. E.g.
```
cp /run/systemd/resolve/resolv.conf /your-data-dir/kubedns/resolv.conf
```
I.e. that file contains the actual nameservers.
I found this thanks to: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues
