### ISSUE TITLE
sourceStrategy `scripts` can not use http url from git raw

### ISSUE THREAD

**Issue by kunyan** [openshift/origin#22579]
According from  https://blog.openshift.com/override-s2i-builder-scripts/
The `scripts` could using a git raw url

```
oc patch bc/myapp -p '{"spec":{"strategy":{"sourceStrategy":{"scripts": "https://raw.githubusercontent.com/demo/wsgi-s2i-scripts/master"}}}}'
```

But actually, it doesn't work. The build log will show fetch scripts error

I think the root cause is the git raw directory is not readable, it return 404 error.
However, if the blog using it as an example, it should be worked before.

I think it should be a bug need to fix

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. Create a git repo with s2i scripts (run/assemble)
2. Put the raw file url of directory in `scripts` yaml
3. Run Build

##### Current Result

Fetch scripts failed

##### Expected Result

Fetched scripts and overwrite the default s2i scripts

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by adambkaplan** [comment]
@GrahamDumpleton not sure if we can update the blog post - has the content moved to https://github.com/OpenShiftDemos/os-sample-python?

**Comment by kunyan** [comment]
@adambkaplan my point is not the repo in the blog not exists. 

I'm curious why the `scripts` stored in a git repo can not be use any more.

The raw files hosts on a git server(github or gitlab) it will not provide directory access. if you visit any exists directory from raw url, it always return 404 error.

for example:

Pls assume the file will be `run` script
https://raw.githubusercontent.com/kunyan/openshift-template-generator/master/src/index.tsx

it could be accessed. but the directory are not.
https://raw.githubusercontent.com/kunyan/openshift-template-generator/master/src/


I think the `scripts` in template, the backend code will visit the directory to check if it return 200 success. if not , it will return fetch error. 
Although the url with `run` or `assemble`  are readable, the backend code won't do that.

This is what I think to improve.

Thanks

**Comment by GrahamDumpleton** [comment]
What do you have for `scripts`?

It is meant to refer to the notional directory. The HTTP directory doesn’t need to be scannable. It will only use `assemble` and `run` from it. It isn’t going to use your `index.tsx` file, nor can you refer to that file from an `assemble` script unless your script downloads it separately.
