### ISSUE TITLE
Infinite wait when try to drain a node that has POD with PDB.

### ISSUE THREAD

**Issue by phlbrz** [openshift/origin#22583]
Original issue: https://github.com/openshift/openshift-ansible/issues/11503
Run upgrade_nodes playbook.
During the Task Drain Node for Kubelet upgrade it hangs forever.
Pods with PDB associated with "min available" hangs drain.
Node cannot be upgrade and the playbook don't fail or get success.
The task: https://github.com/openshift/openshift-ansible/blob/9a0120f7502d753fcc8230597c50142017127742/playbooks/common/openshift-cluster/upgrades/upgrade_nodes.yml#L41

##### Version
```
oc v3.11.98
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://server.xxx:443
openshift v3.11.98
kubernetes v1.11.0+d4cacc0

```

##### Steps To Reproduce
1. Run `sudo ansible-playbook -i inventory.ini /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_11/upgrade_nodes.yml`

##### Current Result
Playbook stuck.

##### Expected Result
Playbook success.

##### Additional Information
I had to do:
```
oc adm manage-node nodexxx --schedulable=false
# Look for pods that has PDB:
oc get pdb --all-namespaces
oc delete po podxx1 -n xx
oc delete po podxx2 -n xy
oc adm drain nodexx --grace-period=20 --ignore-daemonsets --force --delete-local-data --timeout=20s
oc label --overwrite node nodexx maintenance=true
sudo ansible-playbook -i inventory.ini /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_11/upgrade_nodes.yml -e openshift_upgrade_nodes_serial="1" -e openshift_upgrade_nodes_label="maintenance=true" -vvvv
```
Sources about the problem:
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pdb-example

**Comment by patrickdillon** [comment]
/close 

The PDB is set to minAvailable 1 with a Pod that has 1 replica. It is expected behavior to block draining in this situation, because the PDB is preventing the only replica from being killed.
