### ISSUE TITLE
https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_virtualbox_inst.box not found

### ISSUE THREAD

**Issue by andrewcheny** [openshift/origin#22587]
Run vagrant up and get the 404 error for URL
https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_virtualbox_inst.box

**Comment by andrewcheny** [comment]
Run vagrant up and get the 404 error for URL
https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_virtualbox_inst.box

**Comment by gtaman** [comment]
Same here...
Bringing machine 'openshiftdev' up with 'virtualbox' provider...
==> openshiftdev: Box 'fedora_inst' could not be found. Attempting to find and install...
    openshiftdev: Box Provider: virtualbox
    openshiftdev: Box Version: >= 0
==> openshiftdev: Box file was not detected as metadata. Adding it directly...
==> openshiftdev: Adding box 'fedora_inst' (v0) for provider: virtualbox
    openshiftdev: Downloading: https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_virtualbox_inst.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found

**Comment by mmahut** [comment]
This seems legit.
