### ISSUE TITLE
connect: connection refused (OC login)

### ISSUE THREAD

**Issue by yeganx** [openshift/origin#22617]
I try to add master node to my cluster as HA . 
then I try to install HAproxy as load blancer to this 2 master.
my openshift version is : 3.11
```
oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
then i try to set my load blancer IP to as web console URL by editting webconsole-config  configmap
`oc edit configmap/webconsole-config -n openshift-web-console`
now my clinet cant connect to none of my master or LB
`oc login https://X.X.X.X:8443`
error: dial tcp X.X.X.X:8443: connect: connection refused - verify you have provided the correct host and port and that the server is currently running.

**Comment by Mejriamal** [comment]
same issue !! any help ?
