### ISSUE TITLE
No pull request will pass the tests in release-3.10 as the tests fail without any change in the code

### ISSUE THREAD

**Issue by soukron** [openshift/origin#22639]
I'm trying to get a PR (https://github.com/openshift/origin/pull/22500) merged but tests fail while my files are not involved.

I've sent an "empty" pull request (https://github.com/openshift/origin/pull/22637) with a new-line in the README.md file and the result is the same. Some of the required test fail.

##### Steps To Reproduce
1. Clone this repo
2. Checkout to release-3.10
3. Create a new file
4. Send the pull-request and let the test run

##### Current Result
Required tests fail.

##### Expected Result
Tests should work by default. Otherwise people sending pull-requests will frustrate/confuss with errors not related with their own changes.

**Comment by soukron** [comment]
@sjenning @smarterclayton @stevekuznetsov any feedback? How is release-3.10 being tested?

**Comment by stevekuznetsov** [comment]
Are we accepting PRs to release-3.10? Must be best-effort then. I can't tell what's wrong with the unit test in that dummy pR

**Comment by soukron** [comment]
@stevekuznetsov I hope you're accepting PRs, otherwise this backport won't reach the release https://github.com/openshift/origin/pull/22500. 

I submitted the empty PR to prove that there's no issue in the code in the backport PR but in the current released code (or in the tests), which fails in unit tests.

**Comment by stevekuznetsov** [comment]
@smarterclayton @jwforres PTAL
