### ISSUE TITLE
why template nodejs-mongodb.json is not merged into nodejs-sample-pipeline.yaml

### ISSUE THREAD

**Issue by idavollen** [openshift/origin#22681]
Hi,

this is not concerning any issue, on the contrary, it is a question on rationale why it is done in this way in code example, https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/nodejs-sample-pipeline.yaml

_nodejs-sample-pipeline.yaml_ template defines a **BuildConfig** with _jenkinsPipelineStrategy_, referencing to a Jenkinsfile that uses another temaplate https://raw.githubusercontent.com/openshift/nodejs-ex/master/openshift/templates/nodejs-mongodb.json to create a new app at _create_stage_. Why should it be done in this way? Can't we merge the nodejs-mongodb.json template together with the _nodejs-sample-pipeline.yaml_ template, simplifying the Jenkinsfile, which currently looks very complex? Why do we have to have a separate template only for BuildConfig?

My company is currently  using the Jenkins Pipeline, and the Jenkinsfile for all Java projects look very simple. I can't understand why the concerned Jenkinsfile with Openshift Pipeline is so complex? Hopefully someone could shed the light on it. 

Thanks in advance!

**Comment by adambkaplan** [comment]
@idavollen the nodejs template is a sample template that we ship with OpenShift - it's used as a quick-start for building nodejs apps on OpenShift. This example shows how you can use a template in a pipeline, thereby watching other builds that would be run concurrently.
