### ISSUE TITLE
No language matched the source repository

### ISSUE THREAD

**Issue by omiozil** [openshift/origin#22680]
Receiving error as  No language matched the source repository while creating new-app  

Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Steps To Reproduce
1) git clone https://github.com/omiozil/Minishift.git
2) oc new-app https://github.com/omiozil/Minishift.git

Current Result
error: No language matched the source repository

Expected Result
Create a POD with my service running in it.

Additional Information
Here i a have created an service in camel. which i have pushed in my git repository. All i am trying to do is deploying that service in minishift.

Is there should be a docker file ......kindly look into app in git repository. please check am i missing something.

**Comment by Mehar-Abbas** [comment]
I'm having the same error, please kindly look into the matter as posted by omiozil
thanks
