### ISSUE TITLE
new-app: Tags are not imported if new stream is backed by a Docker repo

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#2273]
Background: https://github.com/openshift/origin/pull/2089#issuecomment-101212486

If I do the same thing on the latest master, imported tags are gone.
```
[vagrant@openshiftdev sample-app]$ osc new-app https://github.com/openshift/ruby-hello-world -l name=hello
imageStreams/ruby-20-centos7
imageStreams/ruby-hello-world
buildConfigs/ruby-hello-world
deploymentConfigs/ruby-hello-world
services/ruby-hello-world
A build was created - you can run `osc start-build ruby-hello-world` to start it.
Service "ruby-hello-world" created at 172.30.118.42 with port mappings 8080.

[vagrant@openshiftdev sample-app]$ osc get is/ruby-20-centos7
NAME              DOCKER REPO                 TAGS
ruby-20-centos7   openshift/ruby-20-centos7   
```

Probably happens due to the latest api conversions? @smarterclayton @bparees

**Comment by bparees** [comment]
if tags aren't being imported, e2e would be failing since we create+reference the ruby-20-centos7 imagestream there too and the build can't succeed if we haven't imported from the repository.  is there any difference in how new-app is defining the imagestream object vs how the STI template json does it?

**Comment by smarterclayton** [comment]
Hrm - @csrwng may have seen this as well, definitely a bug.  The test-cmd.sh should be catching this - @kargakis you were the last one to touch that code in hack/test-cmd.sh, can you try with the old hack/test-cmd.sh commands to verify?

----- Original Message -----

**Comment by kargakis** [comment]
@bparees new-app relies on setting spec.dockerImageRepository to the Docker repo: https://github.com/openshift/origin/blob/3b03c184f0ad1e37b2fa3c601ba4ce4df9fe83e5/pkg/generate/app/app.go#L259

**Comment by smarterclayton** [comment]
Which should trigger import.

----- Original Message -----

**Comment by bparees** [comment]
@kargakis that's exactly what the sti sample does:
https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json#L54

**Comment by kargakis** [comment]
Nuked my vagrant and started over. Seems like a false alarm:)
```
[vagrant@openshiftdev sample-app]$ osc get is
NAME               DOCKER REPO                                 TAGS
ruby-20-centos7    openshift/ruby-20-centos7                   latest,v0.4
ruby-hello-world   172.30.201.131:5000/mike/ruby-hello-world   latest
```
