### ISSUE TITLE
a single openshift 'apply json' command line that can accept templates, configs, pods, services, replication controllers?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#228]
Right now the CLI is very different based on whats inside the JSON.

It'd be nice to just have 1 command to apply some JSON. Say....

```
$ openshift apply -c foo.json
```

which then applies configs, pods, services, replication controllers (maybe even templates too?). It'd make the CLI a little easier to type too ;).

i.e. the command looks inside the json to see the kind; then delegates to the underlying openshift kube command based on the shape of the json?

**Comment by smarterclayton** [comment]
This is now resolved.
