### ISSUE TITLE
Indicate the version of the server in a way that surfaces in the UI

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2281]
on the login page, or in a footer, or...

**Comment by jwforres** [comment]
The console doesnt have a footer, so there isnt a great place for it to always show up.  Discussed with @liggitt and we should probably have it appear somewhere in the login page.

**Comment by sspeiche** [comment]
I would look for it under the drop-down for the logged-in user.

Though footer is a decent option, though I don't think I need to see it all the time. 
Jenkins does it in the footer, it is nice in it shows the version and it is a hyperlink to Jenkins homepage (I'd prefer to the release notes for the current release) and another nice feature it the URL for the REST API.

**Comment by jwforres** [comment]
assigned to @fabianofranz since the about page is going to show version info
