### ISSUE TITLE
Cannot build base images properly on CentOS7.5 in Azure

### ISSUE THREAD

**Issue by gnychis** [openshift/origin#22815]
I have a CentOS7.5 system image running in Azure.  I am trying to follow the [contribution guide](https://github.com/openshift/origin/blob/release-4.2/CONTRIBUTING.adoc#openshift-development) to build the `release-4.2` branch.

I have followed the instructions to yum install all of the required libraries properly, and I have setup my Go environment variables as described.

When I try to build the base images I get:

```
[centos@openshift-george-test origin]$ hack/env hack/build-base-images.sh
Unable to find image 'openshift/origin-release:golang-1.11' locally
Trying to pull repository docker.io/openshift/origin-release ...
golang-1.11: Pulling from docker.io/openshift/origin-release
8ba884070f61: Pulling fs layer
c31ea3dbf6fb: Pulling fs layer
8ba884070f61: Verifying Checksum
8ba884070f61: Download complete
8ba884070f61: Pull complete
c31ea3dbf6fb: Verifying Checksum
c31ea3dbf6fb: Download complete
c31ea3dbf6fb: Pull complete
Digest: sha256:25b3ba74a80fd3eeeeabb4299c3a2b9b185e9628d36965769d1396b44e322d85
Status: Downloaded newer image for docker.io/openshift/origin-release:golang-1.11
[openshift/origin-source] open /go/src/github.com/openshift/origin/images/source/Dockerfile: no such file or directory
[WARNING] Retrying image build for openshift/origin-source:latest, attempt 1...
[openshift/origin-source] open /go/src/github.com/openshift/origin/images/source/Dockerfile: no such file or directory
[ERROR] hack/build-base-images.sh:56: `return "${result}"` exited with status 1.
[WARNING] Copying _output/local/bin from the container failed!
[WARNING] Error response from daemon: lstat /var/lib/docker/overlay2/08d5571ca6554611cd1bf2d72e8e5e3c263a842177b6d81a9eed615e1dbb9930/merged/go/src/github.com/openshift/origin/_output/local/bin: no such file or directory
[WARNING] Copying _output/local/releases from the container failed!
[WARNING] Error response from daemon: lstat /var/lib/docker/overlay2/08d5571ca6554611cd1bf2d72e8e5e3c263a842177b6d81a9eed615e1dbb9930/merged/go/src/github.com/openshift/origin/_output/local/releases: no such file or directory
[ERROR] hack/lib/build/environment.sh:170: `return "${exitcode}"` exited with status 1.
```

What I am confused about is that there is also no `images/source/Dockerfile` file in the directory structure.

Am I missing a step first?

##### Version
Origin `release-4.2` branch

##### Steps To Reproduce
1. `hack/env hack/build-base-images.sh`

##### Current Result

```
[openshift/origin-source] open /go/src/github.com/openshift/origin/images/source/Dockerfile: no such file or directory
```

##### Expected Result

No error.

##### Additional Information

None yet.

**Comment by SwagMuffinMcYoloPants** [comment]
I'm running on Ubuntu locally and I get the same issue.

**Comment by waseem-h** [comment]
Same issue here. Trying to build it on MacOS Mojave

**Comment by bjhuangr** [comment]
Same issue.

**Comment by bjhuangr** [comment]
The files were removed by: https://github.com/openshift/origin/pull/22218
Seems the build scripts was not updated accordingly ..

**Comment by RiteshWalia** [comment]
I'm also hitting same issue. Trying to build on CentOS 7. 
Is there any workaround/fix ?

**Comment by sosiouxme** [comment]
I suspect the build script is obsolete. Some images were moved to https://github.com/openshift/images -- not sure if that helps.
