### ISSUE TITLE
Bash completion still failed _get_comp_words_by_ref: command not found

### ISSUE THREAD

**Issue by dove-young** [openshift/origin#22822]
[provide a description of the issue]

./openshift-install cre-bash: _get_comp_words_by_ref: command not found

##### Version
[provide output of the `openshift version` or `oc version` command]

openshift-install-linux-4.1.0-rc.1.tar.gz

##### Steps To Reproduce
1. Download installer wget -c https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-4.1.0-rc.1.tar.gz
2. Unpack installer `tar -xzf openshift-install-linux-4.1.0-rc.1.tar.gz`
3. Generate completion:  `./openshift-install completion bash > oc-completion`
4. Source completion `. oc-completion`
5. Try completion `./openshift-install cre-bash: _get_comp_words_by_ref: command not found`

##### Current Result
`./openshift-install cre-bash: _get_comp_words_by_ref: command not found`
##### Expected Result

`./openshift-install create`

##### Additional Information

I saw this issue was closed in 2017 https://github.com/openshift/origin/issues/14657 , but reload Bash does not work for me.

**Comment by dove-young** [comment]
Here is my environment info

```
[root@openshift-test1 ~]# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="OpenShift Enterprise"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
[root@openshift-test1 ~]# bash -version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[root@openshift-test1 ~]#
```

**Comment by dove-young** [comment]
I got the clue.  I need to install `bash-completion` package in my system and reload my bash.

**Comment by abdennour** [comment]
`sudo yum install -y bash-completion bash-completion-extras`

and for debian guys, use:

```sh
sudo apt-get install -y bash-completion binutils
```
