### ISSUE TITLE
Update the UI to use osapi/v1beta3

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2283]

**Comment by liggitt** [comment]
needs to wait until v1beta3 is baked (probably when we switch storage to it), then happen as fast as possible. @smarterclayton, ideas on timeframe for the storage switch?

**Comment by smarterclayton** [comment]
~week.  Still stomping on conversion problems.  @bparees or @derekwaynecarr or @pweil- if they have any API changes to v1beta3 they want to see done before then.

**Comment by bparees** [comment]
i think the STI->source changes are the only imminent changes we'd want in v1b3 that immediately come to mind for me.

Do we consider the single Status.Message string to be sufficient for any status we want to provide about the build?  As opposed to an array of strings that represent significant events in the lifecycle of the build that have occurred?

Obviously we can concatenate into that field if we need to.

**Comment by smarterclayton** [comment]
Should be consistent with Pods - I think a single Reason is adequate for now.

**Comment by pweil-** [comment]
I'd like to see the route get a secret name instead of the keys but I don't think there will be time for that in the next week.

**Comment by smarterclayton** [comment]
It's less important than getting security of pods done.

----- Original Message -----
