### ISSUE TITLE
IpFailover hanging

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/origin#22838]
Hi,
I have a problem with my IpFailover

I deploy cluster with okd 3.11 with config
1 Master
1 Infra node
2 app nodes

I also add Ipfailover to project to default using this command:
oc login
oc adm policy add-scc-to-user privileged -z ipfailover
oc adm ipfailover --selector="node-role.kubernetes.io/infra=true" --virtual-ips="10.0.3.80" --watch-port=80 --replicas=1 --create

I also create DNS Wildcard on address 10.0.3.80 pointing on my VIP and add also
10.0.3.70 to DNS record such as my cluster console address :
10.0.3.70 is also Master address
First when ipfailover hangs I cant access my cluster console and any app in OKD
also i get this error
ipfailover-2-hpsh6 May 15, 9:12 am Generated from default-scheduler 13 times in the last hour 0/4 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 3 node(s) didn't match node selector.

Can any1 explain me what to do or help to resolve this issue or what i doing wrong.

**Comment by disappear89** [comment]
Hey,

one infra node with ipfailover does not make much sense. There is keepalived running inside a pod, you need at least two infra nodes..

Good luck.

**Comment by ZrytyADHD** [comment]
Ok so the ipfailover hanging beacuse i have only one infra node ? Or not ? Can you help me resolve this oraz just erase ipfailover from my cluster.

**Comment by disappear89** [comment]
Just add a second infra node and see what happens.

**Comment by disappear89** [comment]
Or remove ipfailover and point your App wildcard record to the infra node IP.

**Comment by ZrytyADHD** [comment]
Ok i will try it tommorow and post result of my observe pleasse do not close this tread yet.
Thanks for all your help
