### ISSUE TITLE
"osc exec" results in a dumb terminal and no tty

### ISSUE THREAD

**Issue by brenton** [openshift/origin#2284]
It's important to the users coming from 2.x that `osc exec` be roughly the same experience as ssh in earlier versions.  This issue is meant to track progress towards making this a reality for GA.

#### Current State ####
Right now we're using nsenter under the covers.  As best I can tell nsenter doesn't actually create a tty nor have the ability to.  In addition a `dumb` terminal is set up by default.  This means:

* Using 'less' on a file will result in the following output:

          root@nginx:/var/log# less yum.log 
          WARNING: terminal is not fully functional
          yum.log  (press RETURN)

 This could be addressed today by setting a reasonable value for `$TERM` here: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/dockertools/manager.go#L994.  I hardcoded `TERM=xterm` in my environment and that mostly worked.  The trick with this approach is that it would be more correct to automatically set this based on the terminal the user is actually using.

 It's important to add that simply connecting with `osc exec` and setting `TERM=xterm` does not work correctly today in both Kubernetes and Origin.  Try doing so, running `less` and then using the up and down arrows and you'll see the problem.  Even if `Docker exec` doesn't set a default terminal in docker-1.6.0-6.el7.x86_64 it's doing something to make things work as expected.

* Without a TTY things like screen and tmux won't work.  I suspect we'll get complaints about that.  The workaround right now is to run `script /dev/null -c tmux` to trick the executable you want to run.  That really seems like a hack.

**Comment by brenton** [comment]
@ncdc, you might want to follow along here too.

**Comment by brenton** [comment]
@smarterclayton, what labels/milestone should we put on this?

**Comment by smarterclayton** [comment]
P2, bug, component/kubelet

----- Original Message -----

**Comment by smarterclayton** [comment]
We need `dockerexec` in our builds and packages stat.  We probably want to vendor it into the all in one binary since I *think* 99% of the things it calls are already part of our import tree.

**Comment by ncdc** [comment]
@smarterclayton last I read, upstream just wanted `docker exec` and wasn't interested in our `dockerexec`. How do you want to handle this? I'd like to avoid permanent UPSTREAM commits that add support for `dockerexec` if at all possible.

**Comment by smarterclayton** [comment]
Upstream needs to support arbitrary executors, and we should get our stuff as a plugin in the upstream code.

**Comment by ncdc** [comment]
@smarterclayton @mrunalp FYI I tried to swap in our dockerexec late last night. 1st issue I hit was its attempt to get the `hostname` file - this exists in the infra container's directory, but not the target container's. I commented that out, and the next thing I got was a panic trying to terminate the spawned process (apparently the initial spawning failed, so it tried to kill it, and that panicked). I'm starting to dig into the details this morning.

**Comment by ncdc** [comment]
Upstream issue: https://github.com/kubernetes/kubernetes/issues/13585

**Comment by ibotty** [comment]
Note, that the workaround of setting `TERM`, as implied in the bug report, does not work. At least SIGWINCH is still ignored.

**Comment by ncdc** [comment]
Yes, we need to add SIGWINCH support. That is the only way to fix. There was an upstream community member who was interested in adding support, but I haven't seen any updates in a while. We'll get around to it eventually but there are higher priority items at the moment.
