### ISSUE TITLE
Cluster-Up Proxy / ApiServer

### ISSUE THREAD

**Issue by malins** [openshift/origin#22892]
Hello! I'm trying to use 'oc cluser up' in a proxied environment, but I have problems with using ImageStreams as they reference an external repository (docker.io).

##### Version
oc v3.11.0+0cbc58b

##### Steps To Reproduce
1. Start cluster with the following command:
./oc cluster up --http-proxy http://proxy:8080 --https-proxy http://proxy:8080
2. Try to update image stream with the following command:
./oc -n openshift import-image jenkins:2

##### Current Result
  ! error: Import failed (InternalError): Internal error occurred: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

##### Expected Result
ImageStream should be imported.

##### Additional Information
After adding environment variables HTTP_PROXY and HTTPS_PROXY to openshift-apiserver everything works, but I would expect those environment variables be set via --http-proxy and --https-proxy parameters on oc cluster up.

**Comment by fjakop** [comment]
I have the very same issue as well. How did you add HTTP_PROXY and HTTPS_PROXY to openshift-apiserver?

**Comment by wambowams** [comment]
I need the HTTP_PROXY on the openshift-apiserver too. It would be nice if u can tell us how u did it.

**Comment by malins** [comment]
$ cat ./openshift.local.clusterup/openshift-apiserver/master.env
set HTTP_PROXY=proxy:8080
set HTTPS_PROXY=proxy:8080
set NO_PROXY=172.17.0.0/16

**Comment by wambowams** [comment]
Thank u. Did u add the path to this file somewhere or will it automatically appended to the pod

**Comment by malins** [comment]
No, this file is picked up automatically, IIRC.

**Comment by wambowams** [comment]
Hmm that doesn't work for me, but thank u.
