### ISSUE TITLE
openshift version no longer shown

### ISSUE THREAD

**Issue by cben** [openshift/origin#22901]
After #21434, `/version/openshift` API is gone, and `oc version` only returns k8s version info.
This is a problem for users, for bug reports, and supportability.

##### Version
On an openshift 4.1.0-rc.3 cluster installed via cloud.redhat.com, I see:
```
$ oc version  # from origin-clients-3.11.1-1.fc29.x86_64
oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.cben-oapi.bexf.p1.openshiftapps.com:6443
kubernetes v1.13.4+8cd4e29

$ ~/Downloads/oc version  # oc 4.1 that the console linked to
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0", GitCommit:"27816e1b1", GitTreeState:"clean", BuildDate:"2019-05-17T21:49:38Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+8cd4e29", GitCommit:"8cd4e29", GitTreeState:"clean", BuildDate:"2019-05-09T19:20:33Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

(To make things worse, I see no commit 8cd4e29 in kubernetes/kubernetes, nor in openshift/origin!? Is this because it’s a downstream image?)

The closest replacement seems to be `oc get clusterversion`, or as it's fully spelled:
```
$ oc get clusterversions.config.openshift.io
NAME      VERSION      AVAILABLE   PROGRESSING   SINCE     STATUS
version   4.1.0-rc.3   True        False         4d23h     Cluster version is 4.1.0-rc.3
```
(see the end about permissions to read this)

I guess there are more moving parts now and one might also care about `oc get clusterserviceversions.operators.coreos.com --all-namespaces` or stuff like that (?)

##### Steps To Reproduce
1. run `oc version`
2. run `oc version` while unpriviledged / not logged in ?
3. look in UI console "About"

##### Current Result
see Version section above :)

UI too shows k8s version only:
![image](https://user-images.githubusercontent.com/273688/58327212-ab139880-7e37-11e9-8ea7-9de2f59075de.png)

##### Expected Result

- [ ] `oc version` should show openshift version, or hint how to obtain it.
  - [ ] Ideally, old `oc` 3.x should be able to query 4.x clusters version.  People who have `oc` binary are unlikely to upgrade it as long as mostly works.
    - [x] `oc get clusterversion` does work with oc 3.x, if one knows to use it.
  - [ ] Ideally, new `oc` 4.x should be able to query 3.x clusters version.  People are even less likely to downgrade `oc`.  I don't see any way at all to use new oc to access /version/openshift.  (`curl --insecure $API/version/openshift` is easy, _if one knows to use it_, but I don't think that's satisfactory.)

- [ ] This repo's issue reporting template show instruct how to supply sufficient version info.

- [x] UI should show openshift version.
  https://github.com/openshift/console/pull/1588 will show it, if you have permission to read clusterVersion.

- [ ] Permissions: `/version/openshift` was typically available to unauthenticated queries (and `/version` still is).  This is not true for clusterversions:
  ```
   $ curl --insecure $API/apis/config.openshift.io/v1/clusterversions/version
   ...
   "message": "clusterversions.config.openshift.io \"version\" is forbidden: User \"system:anonymous\" cannot get resource \"clusterversions\" in API group \"config.openshift.io\" at the cluster scope",
   ...
   ```
   Clayton has mentioned in a mail currently only cluster admins can read the version (?)
   Let's see: `$ oc adm policy who-can get clusterversions`
   <details><summary>who-can output</summary>
   <code><pre>
    Namespace: default
    Verb:      get
    Resource:  clusterversions.config.openshift.io
    
    Users:  system:admin
            system:serviceaccount:kube-system:clusterrole-aggregation-controller
            system:serviceaccount:kube-system:generic-garbage-collector
            system:serviceaccount:kube-system:namespace-controller
            system:serviceaccount:openshift-apiserver-operator:openshift-apiserver-operator
            system:serviceaccount:openshift-apiserver:openshift-apiserver-sa
            system:serviceaccount:openshift-authentication-operator:authentication-operator
            system:serviceaccount:openshift-authentication:oauth-openshift
            system:serviceaccount:openshift-cloud-credential-operator:default
            system:serviceaccount:openshift-cluster-version:default
            system:serviceaccount:openshift-controller-manager-operator:openshift-controller-manager-operator
            system:serviceaccount:openshift-controller-manager:openshift-controller-manager-sa
            system:serviceaccount:openshift-image-registry:cluster-image-registry-operator
            system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator
            system:serviceaccount:openshift-kube-apiserver:installer-sa
            system:serviceaccount:openshift-kube-controller-manager-operator:kube-controller-manager-operator
            system:serviceaccount:openshift-kube-controller-manager:installer-sa
            system:serviceaccount:openshift-kube-scheduler-operator:openshift-kube-scheduler-operator
            system:serviceaccount:openshift-kube-scheduler:installer-sa
            system:serviceaccount:openshift-machine-config-operator:default
            system:serviceaccount:openshift-machine-config-operator:machine-config-controller
            system:serviceaccount:openshift-monitoring:cluster-monitoring-operator
            system:serviceaccount:openshift-network-operator:default
            system:serviceaccount:openshift-operator-lifecycle-manager:olm-operator-serviceaccount
            system:serviceaccount:openshift-service-ca-operator:service-ca-operator
            system:serviceaccount:openshift-service-catalog-apiserver-operator:openshift-service-catalog-apiserver-operator
            system:serviceaccount:openshift-service-catalog-controller-manager-operator:openshift-service-catalog-controller-manager-operator
    
    Groups: system:cluster-admins
            system:cluster-readers
            system:masters
   </pre></code>
   </details>

   - [ ] All authenticated users should be able to read cluster version.
   - [ ] Consider allowing reading version without any authentication?

cc @spadgett @smarterclayton

**Comment by cben** [comment]
One more regression:

- [ ] Previously, oc version included exact origin git commit it was built from.
  I don't see a precise commit anywhere in `oc describe clusterversion`.

  The most exact part is `Image: quay.io/openshift-release-dev/ocp-release@sha256:713aae8687cf8a3cb5c2c504f65532dfe11e1b3534448ea9eeef5b0931d3e208`.
  I tried `docker image inspect` hoping for informative labels, but no such luck:
  ```
    "Labels": {
        "io.openshift.release": "4.1.0-rc.3",
        "io.openshift.release.base-image-digest": "sha256:e852a1e8f12c5a08a27f1c58cfb599acc7269a2e1ca71f2dd7eb85860c821d33"
    },
  ```

**Comment by smarterclayton** [comment]
Please open a bugzilla, not a GitHub issue.

To see commit info on the cluster you should use "oc adm release info
--commits".

**Comment by mfranczy** [comment]
@cben did you create a bugzilla for that? If yes, could you send a link?
