### ISSUE TITLE
Replication controllers fight with each other during `delete all --all` in hack/test-cmd.sh

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2295]
Deletion of the project (delete all --all) is incredibly slow now.  It looks like it's related to the serial nature of the deletion reaper with upstream changes.  It's also possible that the replication controller is getting backlogged, which means that it takes O(minutes) to wait for the controller to reach zero.

This is probably unacceptable for production use, so we need to optimize and fix the issues.

Some things to investigate:

1. Why does it take so long for the replication controller to spin down the existing pods?
  1. Investigate whether we should set to zero and continue on to the next one before coming back and deleting it
  2. Fix whatever is causing the controller to be so slow
  3. Consider whether we should set it to 0, then delete the pods ourself.
2. What happens if someone modifies the DC (or an image changes) while we're reaping?
  1. We may want to disable DC triggers before cleaning up the RCs
  2. We may want to reap in the background the sub items of the DC.

May need changes upstream.

**Comment by derekwaynecarr** [comment]
So this is just deleting the content in the project but not the project itself?

**Comment by smarterclayton** [comment]
This is the cli deletion code for the deployment config and replication controllers

**Comment by derekwaynecarr** [comment]
Ok.  Project deletion is much faster now so was wondering if there was something odd there.

**Comment by smarterclayton** [comment]
Deletion should be sub second of an rc and deployment config.

**Comment by kargakis** [comment]
@smarterclayton did you try to run a deletion locally? Doesn't seem slow on my machine... [Except if 6 seconds for spinning down 20 pods is regarded as slow](http://pastebin.com/Bf8C5pCg). There are some parts of the reaper interface I would like to rewrite though, specifically reducing HTTP calls since both `stop` and `delete` already use the resource builder (and then go on GETing the objects).

+1 for 2.

**Comment by smarterclayton** [comment]
There should be no reason deleting 20 pods should take longer than about 30ms.

----- Original Message -----

**Comment by kargakis** [comment]
Gonna have a look at the controller tomorrow

**Comment by smarterclayton** [comment]
Stop docker and run hack/test-cmd (you should see the problem then)

**Comment by kargakis** [comment]
The times @smarterclayton mentioned regarding pod deletion align with what I've [found](http://pastebin.com/gaLPpqSU).

It turns out that the reaper uses a high poll interval ([3 seconds](https://github.com/GoogleCloudPlatform/kubernetes/blob/10339d72b66a31592f73797a9983e7c207481b22/pkg/kubectl/stop.go#L30)) and deletion ends up finishes in times, multiples of 3 (6 seconds, 9 seconds, 12 seconds, got them all)

I've setup an interval of 100ms and got the following results: http://pastebin.com/34PwnajF

Examples are run directly with a replication controller, the dc reaper is two HTTP calls more so essentially the difference is negligible.
```
[vagrant@openshiftdev sample-app]$ time osc delete dc ruby-hello-world
deploymentconfigs/ruby-hello-world

real	0m3.466s
user	0m0.103s
sys	0m0.171s
```

**Comment by smarterclayton** [comment]
It's a pretty terrible experience for an end user - how can we tune the reaper for a more reasonable behavior for users?  We definitely want to limit the amount of simultaneous requests to the server, but that's also something the server is capable of managing.

----- Original Message -----

**Comment by smarterclayton** [comment]
Causing travis to fail randomly:

```
error: timed out waiting for the condition
!!! Error in hack/test-cmd.sh:538
  'osc delete all --all' exited with status 1
Call stack:
  1: hack/test-cmd.sh:538 main(..
```

**Comment by kargakis** [comment]
> It's a pretty terrible experience for an end user - how can we tune the reaper for a more reasonable behavior for users? We definitely want to limit the amount of simultaneous requests to the server, but that's also something the server is capable of managing.

This is not a reaper but a resizer problem. Some higher level places we can probably change and get something out of it are reducing the poll interval and make `osc resize` wait for the replicas it spins up so we can be sure that all replicas are up and running when we are going to spin them down. 

Other than that we will probably have to make changes deeper in the rc controller.

**Comment by kargakis** [comment]
> Causing travis to fail randomly:

Seems like this isn't a very random flake. 
```
buildConfigs/ruby-sample-build
buildConfigs/sinatra-app-example
buildConfigs/sinatra-example-1
buildConfigs/sinatra-example-2
builds/ruby-sample-build-1
builds/sinatra-app-example-1
builds/sinatra-example-1-1
imageStreams/sinatra-app-example
imageStreams/sinatra-example-1
imageStreams/sinatra-example-2
deploymentConfigs/database
deploymentConfigs/frontend
deploymentConfigs/sinatra-app-example-a
deploymentConfigs/sinatra-app-example-b
deploymentConfigs/sinatra-example-1
deploymentConfigs/sinatra-example-2
I0520 17:25:05.015028    8749 replication_controller.go:353] Replication Controller has been deleted example/frontend-1
I0520 17:25:06.608967    8749 replication_controller.go:353] Replication Controller has been deleted example/database-1
replicationcontrollers/database-app-1
I0520 17:25:26.142547    8749 replication_controller.go:353] Replication Controller has been deleted example/database-app-1
replicationcontrollers/database-rc-1
I0520 17:25:29.424315    8749 replication_controller.go:353] Replication Controller has been deleted example/database-rc-1
E0520 17:26:22.062804    8749 kubelet.go:637] Image garbage collection failed: unable to find data for container /
E0520 17:26:22.119250    8749 reflector.go:165] watch of *api.Node ended with: very short watch
E0520 17:26:28.258455    8749 reflector.go:165] watch of *api.Namespace ended with: very short watch
E0520 17:30:59.984030    8749 reflector.go:165] watch of *api.PersistentVolumeClaim ended with: very short watch
replicationcontrollers/frontend-rc-1
I0520 17:31:14.501456    8749 replication_controller.go:353] Replication Controller has been deleted example/frontend-rc-1
services/database
services/database-app
services/database-rc
services/empty-service
services/frontend
services/frontend-app
services/hello-openshift
services/sinatra-app-example
services/sinatra-example-1
services/sinatra-example-2
pods/deploy-frontend-1kheeo
pods/hello-openshift
pods/lonely-pod
error: timed out waiting for the condition
!!! Error in hack/test-cmd.sh:548
  'osc delete all --all' exited with status 1
```

Same place as the one posted above. There are five replication controllers brought down by that delete all --all instance and another one hangs around due to timeout (named `frontend-app-1` -not sure it's the same as the one from @smarterclayton's report). Maybe related to the [number](https://github.com/openshift/origin/blob/359d7d639d33f2fd49c44c17de5931ef1fb3e37b/pkg/cmd/server/kubernetes/master.go#L108) of workers the rc manager has? Needs more investigation...

**Comment by kargakis** [comment]
@smarterclayton updating a dc by removing its triggers may trigger a new deployment right? So what happens in the meantime and until that new deployment propagates to the system?

Another question is shouldn't the dc reaper delete all the deployments of a config instead of just the latest?

**Comment by smarterclayton** [comment]
> On Jun 2, 2015, at 8:58 AM, Michail Kargakis <notifications@github.com> wrote:
> 
> @smarterclayton updating a dc by removing its triggers may trigger a new deployment right?
> 
It should not.  If it does, that's a big.
> So what happens in the meantime and until that new deployment propagates to the system?
> 
> Another question is shouldn't the dc reaper delete all the deployments of a config instead of just the latest?
> 
Yes, if you're deleting a DC all rc should get removed.

**Comment by kargakis** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/8999 will make this faster

**Comment by smarterclayton** [comment]
Dropping priority since we're so close and it's involved

**Comment by liggitt** [comment]
goroutine dumps while hung on `delete all --all`:

Full goroutine dump:
http://pastebin.test.redhat.com/291927

Interesting goroutine:
http://pastebin.test.redhat.com/291929

**Comment by smarterclayton** [comment]
Thanks for digging - this is pretty important.

**Comment by liggitt** [comment]
Theories of possible causes:
1. replication manager is correctly scaling pods to 0, then failing to update rc.status.replicas
2. replication manager watch is missing the notification of rc.spec.replicas being set to 0

Inspecting etcd during the hang to see if pods were removed for the RC should let us rule out 2

**Comment by deads2k** [comment]
We might be getting bit by multiple RCs matching a single pod.  During deletions, one is scaling down, but another is staying put during that time.  If you delete in the wrong order, then you'll have one RC continually fighting another.  

https://github.com/GoogleCloudPlatform/kubernetes/pull/10415 allows for identification of the problem.  It happens frequently in `hack/test-cmd.sh`
```
[deads@deads-dev-01 kubernetes]$ grep "Multiple controllers matched for pod" /tmp/openshift-cmd.RWDn/openshift.log 
W0626 14:54:21.791354    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-app-1-9j3ob.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:54:22.170895    5119 replication_controller.go:208] Multiple controllers matched for pod example/database-2-x0h18.  Choosing the first of: example/database-app-1, example/database-rc-1, example/database-2.
W0626 14:54:22.190090    5119 replication_controller.go:208] Multiple controllers matched for pod example/database-1-j25dy.  Choosing the first of: example/database-app-1, example/database-rc-1, example/database-1.
W0626 14:54:22.203886    5119 replication_controller.go:208] Multiple controllers matched for pod example/database-2-x0h18.  Choosing the first of: example/database-app-1, example/database-rc-1, example/database-2.
W0626 14:54:22.291550    5119 replication_controller.go:208] Multiple controllers matched for pod example/database-1-j25dy.  Choosing the first of: example/database-app-1, example/database-rc-1, example/database-1.
W0626 14:54:22.309438    5119 replication_controller.go:208] Multiple controllers matched for pod example/database-2-x0h18.  Choosing the first of: example/database-app-1, example/database-rc-1, example/database-2.
W0626 14:54:22.499714    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-2-v414o.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1, example/frontend-2.
W0626 14:54:22.614418    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-2-v414o.  Choosing the first of: example/frontend-2, example/frontend-app-1, example/frontend-rc-1.
W0626 14:54:22.640446    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-2-v414o.  Choosing the first of: example/frontend-2, example/frontend-app-1, example/frontend-rc-1.
W0626 14:54:22.726453    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-1-koxrr.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1, example/frontend-1.
W0626 14:54:22.815416    5119 replication_controller.go:208] Multiple controllers matched for pod example/database-1-j25dy.  Choosing the first of: example/database-1, example/database-app-1, example/database-rc-1.
W0626 14:54:22.875035    5119 replication_controller.go:208] Multiple controllers matched for pod example/database-1-j25dy.  Choosing the first of: example/database-app-1, example/database-rc-1, example/database-1.
W0626 14:54:22.940294    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-1-koxrr.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1, example/frontend-1.
W0626 14:54:23.387132    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-1-koxrr.  Choosing the first of: example/frontend-1, example/frontend-app-1, example/frontend-rc-1.
W0626 14:54:39.294732    5119 replication_controller.go:208] Multiple controllers matched for pod example/database-app-1-1w479.  Choosing the first of: example/database-app-1, example/database-rc-1.
W0626 14:54:41.058765    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-app-1-fwcjw.  Choosing the first of: example/frontend-rc-1, example/frontend-app-1.
W0626 14:57:47.106420    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-1-koxrr.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1, example/frontend-1.
W0626 14:57:47.223630    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-2-65ft3.  Choosing the first of: example/frontend-2, example/frontend-app-1, example/frontend-rc-1.
W0626 14:57:47.363125    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-2-65ft3.  Choosing the first of: example/frontend-2, example/frontend-app-1, example/frontend-rc-1.
W0626 14:57:47.375113    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-app-1-vbxeo.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:57:47.391643    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-app-1-vbxeo.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:57:47.485358    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-app-1-zf9bq.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:57:47.528968    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-app-1-vbxeo.  Choosing the first of: example/frontend-rc-1, example/frontend-app-1.
W0626 14:57:47.722160    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-2-65ft3.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1, example/frontend-2.
W0626 14:58:18.759279    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-2-65ft3.  Choosing the first of: example/frontend-2, example/frontend-app-1, example/frontend-rc-1.
W0626 14:58:19.553904    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-app-1-9j3ob.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:58:19.556180    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-app-1-vbxeo.  Choosing the first of: example/frontend-rc-1, example/frontend-app-1.
W0626 14:58:19.633117    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-rc-1-jpyed.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:58:19.655735    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-rc-1-w6xvf.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:58:19.662017    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-rc-1-jdpet.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:58:19.663376    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-rc-1-jpyed.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:58:19.676507    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-rc-1-w6xvf.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:58:19.762643    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-rc-1-jdpet.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
W0626 14:58:19.907462    5119 replication_controller.go:208] Multiple controllers matched for pod example/frontend-rc-1-w6xvf.  Choosing the first of: example/frontend-app-1, example/frontend-rc-1.
```

**Comment by deads2k** [comment]
This pull fixes it: https://github.com/openshift/origin/pull/3467.  It needs some tidying.

**Comment by liggitt** [comment]
#3467 helps with fighting replication controllers.

@bparees looks like build controllers are also copying build's labels into build pods (see `build/controller/strategy/util.go#getPodLabels`) which is making build pods be selected by replication controllers. We probably shouldn't be setting labels on build or deployment pods

**Comment by ironcladlou** [comment]
>@bparees looks like build controllers are also copying build's labels into build pods (see build/controller/strategy/util.go#getPodLabels) which is making build pods be selected by replication controllers. We probably shouldn't be setting labels on build or deployment pods

The deployer pod has only one label, `openshift.io/deployer-pod-for.name`, so should be okay.

**Comment by liggitt** [comment]
yeah, I could see one well-namespaced label for selection purposes... just not copying all labels from the deploymentconfig/build down to a pod

**Comment by smarterclayton** [comment]
I think the one Dan proposes is ok.  The rest are probably wrong.

----- Original Message -----

**Comment by bparees** [comment]
I can't remember why we are copying the labels.. @soltysh looks like you made the change, do you remember why?  https://github.com/openshift/origin/pull/1275

**Comment by soltysh** [comment]
Can't recall anything special other than information purposes. I guess the best would be to remove and see what will happen. I can deal with that on Mon if you want to.

**Comment by bparees** [comment]
yeah please remove it.

we should also consider removing the "build" label we're putting on all the builds and chang the logic that's currently using the "build" label to use the "openshift.io/build.name" annotation instead.

that should be a safely backwards compatible change since the annotation will be on any existing build objects too.

**Comment by ironcladlou** [comment]
>we should also consider removing the "build" label we're putting on all the builds and chang the logic that's currently using the "build" label to use the "openshift.io/build.name" annotation instead.

It's important to be able to efficiently query builds and deployments, and since labels can be namespaced, we can keep a correlating label around without much fear of conflict.

**Comment by bparees** [comment]
@ironcladlou i keep getting mixed messages on whether labels are really anything special in terms of query-ability.  My current understanding is that:
1) nothing is queryable from an etcd perspective, so it's all going to come across the wire at a minimum
2) you can filter objects in the watch api using any fieldselector you want, we just don't happen to have one for annotations yet, so we should create one and stop making things labels that shouldn't be labels just to satisfy the need to filter in a watch.

**Comment by liggitt** [comment]
Between etcd and the API, there is no filtering (other than namespace)

Between the API and clients (even in process clients like controllers) label selector filtering is genetically supported for all objects and field selector filtering is minimally and inconsistently supported for a few fields on a few objects. 

I don't think the full set of annotations will be made available to filter on, but I could be wrong

**Comment by liggitt** [comment]
Filtering is still beneficial to prevent encoding/transfer/decode cost between the API and client

**Comment by bparees** [comment]
@liggitt yeah sorry if my summary wasn't as clear is it could have been.

my point was:  etcd -> watchendpoint  :  everything must go over that wire
watchendpoint -> client  :  filtering can be used to limit what goes over this wire, but currently annotations can't be used in that filter.  but nothing really prevents us from adding that ability, except that k8s says annotations aren't supposed to be used by selection so we'd be sort of violating that principle.

**Comment by bparees** [comment]
@csrwng has opinions here too.

**Comment by smarterclayton** [comment]
----- Original Message -----
> yeah please remove it.
> 
> we should also consider removing the "build" label we're putting on all the
> builds and chang the logic that's currently using the "build" label to use
> the "openshift.io/build.name" annotation instead.

Yes

**Comment by csrwng** [comment]
Yup, just pointed out that annotations are not filterable by design (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/annotations.md). They don't have the same restrictions as labels. If we need to use a label instead of an annotation or change the name of a label, we could use an in-place migration in the etcd registry for builds.

**Comment by smarterclayton** [comment]
We can filter annotations.  We just chose not to at the start.  At some point, this is just semantics around "I need to make call X more efficient, so I have to tell the server that I only need Y".  For now, a namespaced label is ok to filter on.  

----- Original Message -----

**Comment by bparees** [comment]
so again the simplest backwards compatible change for the build logic is to switch to using and filtering on the existing annotation and stop applying the "build" label (and all the other labels).

anything else is going to require more migrattion work to ensure we don't miss build objects that only have the "build" label and not whatever new label we come up with (eg openshift.io/build.name)

**Comment by smarterclayton** [comment]
Why can't you support the old label and the new label, and only set the new label?

----- Original Message -----

**Comment by bparees** [comment]
@smarterclayton i said simplest.  i'd rather not retain logic that filters/queries on "label1 || label2" in our codebase forever.

**Comment by smarterclayton** [comment]
I'm not sure we're ready to filter on annotations.  We're going to have to deal with this eventually, might as well be this change that forces us to doc through the flow and describe how it's supported.

----- Original Message -----

**Comment by ironcladlou** [comment]
>@smarterclayton i said simplest. i'd rather not retain logic that filters/queries on "label1 || label2" in our codebase forever.

If I'm following correctly, we've dealt with this in deployments. The way we settled on for now is to refactor all internal lookups of annotations/labels to flow through normalized utility methods which map all known previous API key names to the current internal key names:

https://github.com/openshift/origin/blob/master/pkg/deploy/util/util.go#L58

So then your filtering setup throughout the code can use the utility methods, and the translation between API versions can be isolated to the utility.

Would that strategy help here?

**Comment by liggitt** [comment]
It helps for reading annotations, it doesn't help if you're wanting to filter the API call using labels

**Comment by bparees** [comment]
Yeah in this case it's about the selector we'd have to pass to the watch api.

Granted we can still have utility logic to generate that selector, i just hate the idea of forever retaining a selector on a "build" label precisely because it's so generic that it'll probably come back to haunt us.

**Comment by ironcladlou** [comment]
I still don't follow how it's different than deployments. We use the utility to generate a selector using the mapped label keys. For the record I don't like it much either, but it works and insulates us from key renames across API versions at the moment.

**Comment by deads2k** [comment]
> I still don't follow how it's different than deployments. We use the utility to generate a selector using the mapped label keys. For the record I don't like it much either, but it works and insulates us from key renames across API versions at the moment.

Ummm... I think that's actually a little broken.  See https://github.com/openshift/origin/pull/3483.

**Comment by smarterclayton** [comment]
You can set a deprecation for after 3.1 if you introduce in 3.0.1.

On Jun 29, 2015, at 10:03 AM, Ben Parees <notifications@github.com> wrote:

Yeah in this case it's about the selector we'd have to pass to the watch
api.

Granted we can still have utility logic to generate that selector, i just
hate the idea of forever retaining a selector on a "build" label precisely
because it's so generic that it'll probably come back to haunt us.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2295#issuecomment-116676999>.

**Comment by bparees** [comment]
@smarterclayton noted.  @soltysh since the original issue here got closed, can you open and work on a new one to 
1) add a new label (openshift.io/build.name)
2) only add that label to build pods and no other labels
3) update the filter logic in our various controllers to use the new label || the old label
4) note that the old label is deprecated ( @smarterclayton how exactly do we do that? )
?

**Comment by liggitt** [comment]
Already opened a tracking issue at https://github.com/openshift/origin/issues/3502

**Comment by bparees** [comment]
already noted the tracking issue and updated it :)

**Comment by bparees** [comment]
(now's when you say you already noted that i noted it)

**Comment by liggitt** [comment]
Fortunately I stopped just short of pasting your comment into the new issue immediately after you
