### ISSUE TITLE
Build OpenShift using Go 1.4 on RHEL

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2296]
We need to tag in the 1.4 packages to our build chain to build.  The perf benefits from 1.4 are sufficient enough that we need to do it for 3.0.

@detiber / @sdodson

**Comment by brenton** [comment]
Looks like we're already building with 1.4:
~~~
$ brew list-tagged --inherit --latest rhose-3.0-rhel-7-build golang
Build                                     Tag                   Built by
----------------------------------------  --------------------  ----------------
golang-1.4.2-3.el7ose                     rhose-3.0-rhel-7-candidate  lmandvek
~~~

**Comment by brenton** [comment]
I verified that is the package we're using in the brew output as well.
