### ISSUE TITLE
buildconfig webhook invocation call returns wrong selflink

### ISSUE THREAD

**Issue by clemensutschig** [openshift/origin#23038]
HTTP POST to a webhook returns wrong selflink

##### Version
[provide output of the `openshift version` or `oc version` command]
3.11

##### Steps To Reproduce
1. Trigger a pipeline based build thru webhook

`curl -k -X POST APIHOST/oapi/v1/namespaces/NAMESPACE/buildconfigs/BUILDCONFIG/webhooks/SECRET/generic`

##### Current Result
call returns
`"selfLink":"/apis/build.openshift.io/v1/namespaces/NAMESPACE/buildconfigs/BUILDNAME/instantiate`

which is wrong - NO new build config is created, but a build!

##### Expected Result
should return
`/apis/build.openshift.io/v1/namespaces/NAMESPACE/builds/BUILDNAME`

**Comment by clemensutschig** [comment]
I am happy to take a stab on a fix - but I was unable to find the sources ... :(

**Comment by adambkaplan** [comment]
@clemensutschig this certainly feels like a bug, and we'd be happy to take a look at a PR that addresses this issue.

That said @openshift/openshift-team-master is doing a significant refactor of the openshift apiserver (which owns the REST interface). I would wait for the dust to settle on that before submitting a fix.

fyi @openshift/openshift-team-developer-experience

**Comment by clemensutschig** [comment]
@adambkaplan - where is the rest piece hidden:-)? Happy to contribute
