### ISSUE TITLE
self-subject access reviews (IsPersonalSubjectAccessReview) doesn't work

### ISSUE THREAD

**Issue by nak3** [openshift/origin#2303]
Please see following output.

~~~
$ _output/local/go/bin/osc --v=4 get IsPersonalSubjectAccessReview
I0517 21:23:47.755036    6852 selector.go:53] Unable to list "ispersonalsubjectaccessreviews": the server could not find the requested resource
~~~

Even though `printIsPersonalSubjectAccessReview()` is implemented in [`pkg/cmd/cli/describe/printer.go`](https://github.com/openshift/origin/blob/53e8a0d27c6a7e8ee663898a437fde6908c368c5/pkg/cmd/cli/describe/printer.go#L449-L452), its rest API is not implemented and `master.go` doesn't register the API during the start.

However, according to this discussion [pull/139](https://github.com/openshift/origin/pull/1392), it is not clear if `IsPersonalSubjectAccessReview` will be obsolete.

I open here as a new issue to track.

**Comment by smarterclayton** [comment]
Personal subject access review is called by other methods.  The printer may still need to be called, but it's possibly not wired up correctly.

**Comment by liggitt** [comment]
IsPersonalSubjectAccessReview isn't an API resource... it's a possible attribute restriction on a role. You can see it in use in the default policy with `osc describe clusterrolebindings default`

**Comment by nak3** [comment]
I understand.

So, the below column is not used?

https://github.com/openshift/origin/blob/cdd1903e0576b178669c2e83866cdf67db3b7356/pkg/cmd/cli/describe/printer.go#L52-L53

Actually I hope that the resource which can't get by `osc get <RESOURCE>` isn't included in [`NewHumanReadablePrinter()`](https://github.com/openshift/origin/blob/cdd1903e0576b178669c2e83866cdf67db3b7356/pkg/cmd/cli/describe/printer.go#L60)
Because bash-completion is created by the resources which are included in `NewHumanReadablePrinter()`. So `osc get TAB TAB` will show `ispersonalsubjectaccessreview`.

@liggitt is it possible to change the implementation of `ispersonalsubjectaccessreview`? I know bash-completion is not high priority, but if you can.

**Comment by deads2k** [comment]
The human readable printer is used to print AttributeRestrictions from https://github.com/openshift/origin/blob/cdd1903e0576b178669c2e83866cdf67db3b7356/pkg/cmd/cli/describe/describer.go#L739 and provides a somewhat discoverable way to print them.

I could see other envision other factorings, but changing the factorization for bash completion seems weak.  Bash completion lists should be built from the `RESTMappings`, intersected with the additional restrictions of what you're trying to do (as a for instance, not all resources can be updated or deleted).

**Comment by nak3** [comment]
No, I mean the column headar below is not used anywhere.
https://github.com/openshift/origin/blob/cdd1903e0576b178669c2e83866cdf67db3b7356/pkg/cmd/cli/describe/printer.go#L52-L53
~~~
	// known custom role extensions
	IsPersonalSubjectAccessReviewColumns = []string{"NAME"}
~~~
But please ignore if I misunderstand. I will understand it by myself.

As you said, it looks like `RESTMappings` should be used for resources lists.
