### ISSUE TITLE
Client TLS negotiation is slow, consider a temporary session ticket cache

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2304]
The CLI spends a fair amount of CPU and network back and forth establishing TLS connections to the server.  It might be nice to have something like ssh-agent that reuses connections to the server in the background to reduce the startup cost of the cli.

Essentially, this would be a local tls proxy over http that required a unique secret between the cli and the proxy to work.

Possible flow:

1. `osc proxy &` - starts a background process that will proxy http using the current configuration.  A secret is created that is a hash of the security info used to connect to the server.  Could be on a Unix domain socket
2. `osc get ...` checks for a proxy - if one is listening, starts an HTTP connection over the socket and passes a header with the hashed secret of the current user context (matching above)
3. The proxy tests the secret and then forwards requests to the backing server

This also has applications for forwarding - the proxy keeps access to the secrets, the client could in theory not be enabled (but instead must access the secret some other way).  

The proxy would automatically shut down after a period of inactivity.

**Comment by derekwaynecarr** [comment]
I am noticing this while populating data from CLI calls in bulk.

**Comment by smarterclayton** [comment]
I thought at one point that NSS had some concept like this but I can't find any record of it.

**Comment by smarterclayton** [comment]
Not a problem anymore
