### ISSUE TITLE
Build a client and admin client binary during release

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2305]
As the server binary has grown it's increased the startup time for clients.  We should test building a separate binary that holds the user facing cli (osc, kubectl) and measure both total size and startup time.  Assuming it is smaller and faster to startup, build-cross should make a separate binary and update the symlinks.

**Comment by sdodson** [comment]
First estimate, 40% smaller binary, no noticeable change in `osc get pods` on a host with one pod over 10 iterations.

```
[root@ose3 ~]# ls -la ./osc /usr/bin/openshift
-rwxr-xr-x. 1 root root 42726944 May 19 17:00 ./osc
-rwxr-xr-x. 1 root root 71172794 May 19 17:10 /usr/bin/openshift
```

If we strip both binaries osc still roughly 40% smaller and both seem marginally faster like 0.38s versus 0.42s.

```
[root@ose3 ~]# ls -la ./osc /usr/bin/openshift
-rwxr-xr-x. 1 root root 30373640 May 19 17:14 ./osc
-rwxr-xr-x. 1 root root 49292840 May 19 17:15 /usr/bin/openshift
```

**Comment by smarterclayton** [comment]
You may have to trim more dependencies, can you send me the branch you used?

**Comment by sdodson** [comment]
Yeah, it looks like a lot of things got pulled in that I wasn't expecting.

https://github.com/openshift/origin/compare/master...sdodson:build-clients

**Comment by smarterclayton** [comment]
It's possible there's also too much crosslinking.  We don't want to strip symbols, and I'm not sure a 20 meg reduction is a benefit.  Maybe we can do a quick look this week and dig into whether there is anything else we can tease apart.

**Comment by danmcp** [comment]
@sdodson Any updates?

**Comment by sdodson** [comment]
No, I've not looked at this recently. I'll look at it early next week.

**Comment by smarterclayton** [comment]
Let's come back to this post 3.0.  We can live with it with no user impact.

**Comment by sdodson** [comment]
Change the milestone to 1.1 then?

**Comment by brenton** [comment]
@smarterclayton is there a reason why no one has created cmd/oadm.go and added it as a `OS_CROSS_COMPILE_TARGETS` in https://github.com/openshift/origin/blob/master/hack/common.sh#L46

It looks like the `oc` part of this issue is done.  If the `oadm` one isn't needed we might as well close this.

**Comment by smarterclayton** [comment]
There's enough overlap between what an admin might want and what's in
openshift that we choose not to.

On Thu, Aug 20, 2015 at 4:33 PM, Brenton Leanhardt <notifications@github.com
> wrote:

> @smarterclayton <https://github.com/smarterclayton> is there a reason why
> no one has created cmd/oadm.go and added it as a OS_CROSS_COMPILE_TARGETS
> in https://github.com/openshift/origin/blob/master/hack/common.sh#L46
>
> It looks like the oc part of this issue is done. If the oadm one isn't
> needed we might as well close this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2305#issuecomment-133162732>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by brenton** [comment]
Makes sense.  I'm going to close this then.

**Comment by smarterclayton** [comment]
On Thu, Aug 20, 2015 at 4:42 PM, Clayton Coleman <ccoleman@redhat.com> wrote:
>
> There's enough overlap between what an admin might want and what's in openshift that we choose not to.
>
> On Thu, Aug 20, 2015 at 4:33 PM, Brenton Leanhardt <notifications@github.com> wrote:
>>
>> @smarterclayton is there a reason why no one has created cmd/oadm.go and added it as a OS_CROSS_COMPILE_TARGETS in https://github.com/openshift/origin/blob/master/hack/common.sh#L46
>>
>> It looks like the oc part of this issue is done. If the oadm one isn't needed we might as well close this.

Trying to see whether rich text mode breaks this, ignore....

>>
>> —
>> Reply to this email directly or view it on GitHub.
>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift




-- 
Clayton Coleman | Lead Engineer, OpenShift
