### ISSUE TITLE
[RFE] enhance `oc get node` to be able to report RPMs on RHCOS host

### ISSUE THREAD

**Issue by miabbott** [openshift/origin#23062]
As much as we would like for users to rely on the cluster mechanics to manage the RHCOS nodes, they are still going to be curious and want to get information about the packages on a node.  An example would be allowing a user doing a security audit to inspect the nodes for installed packages.

To make this information more easily available, I think it would be beneficial for users to be able to do something like `oc get node --packages <node>` and have a list of packages installed on the host returned.  Or maybe just the list of packages that were used in the RHCOS compose.

While this could be accomplished with `oc debug node` and a few extra commands, this kind of helper functionality could improve usability.

**Comment by cgwalters** [comment]
FWIW I disagree with this RFE as stated and think a more generally useful pattern would be supporting *unprivileged* containers that mount the host read-only.  All that's needed for this is to mount the host's `/usr` read-only, don't need to run as real root just to read the rpmdb, etc.

I think this would require some special support in the SCCs or a custom admission controller but it would be way more flexible.
