### ISSUE TITLE
getting logs via API prepends timestamp

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#2309]
In our case the timestamp is a bit disturbing since our logs already have timestamps:

`docker logs`
```
2015-05-18 04:51:59,912 - dock.plugins.squash - DEBUG - Archive generated
```

API
```
2015-05-18T08:51:59.918042576Z 2015-05-18 04:51:59,912 - dock.plugins.squash - DEBUG - Archive generated
```

`osc build-logs`
```
2015-05-18T08:51:59.918094714Z 2015-05-18 04:51:59,912 - dock.plugins.squash - DEBUG - Archive generated
```

Would it possible to disable timestamping? Or even better, make it configurable.

**Comment by mfojtik** [comment]
@TomasTomecek +100 this is annoying me for a pretty long time. I think we should not use 'glog' to return logs here but just Printf()

**Comment by mfojtik** [comment]
@smarterclayton @TomasTomecek wonder if this add the first timestamp or the second...

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L223

**Comment by mfojtik** [comment]
Upstream: https://github.com/GoogleCloudPlatform/kubernetes/pull/8407
