### ISSUE TITLE
Building origin using ./hack/build-release.sh is broken

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2312]
We initially found this when we were doing release of STI v0.0.5 and we were not able to cross-compile the binary for Mac and Windows. We were getting this error:

```console
++ Building go targets for linux/amd64: cmd/openshift
++ Building go targets for darwin/amd64: cmd/openshift
# runtime
/usr/lib/golang/src/runtime/atomic_amd64x.c:9 6c: No such file or directory: textflag.h
```

It turns out that `yum install go` pulls the GO 1.4 which is not compatible with some of the packages we have in GoDeps (namely `github.com/Sirupsen/logrus` and some Docker pkgs). The problem as described here: http://stackoverflow.com/a/28265813 is that `syscall` was deprecated with `sys` package...

Today, when you upgrade the origin-release Docker image we use to build Origin releases, you get the same error as well.

@vbatts @smarterclayton @bparees FYI.

**Comment by smarterclayton** [comment]
We need to get fixes in upstream and then carry them as UPSTREAM patches.

----- Original Message -----

**Comment by bparees** [comment]
fixed.
