### ISSUE TITLE
Token expired message should be implemented

### ISSUE THREAD

**Issue by nak3** [openshift/origin#2314]
When token has expired, the client would get following error message.

~~~
[joe@ose3-master ~]$ osc get pod
Error: the server has asked for the client to provide credentials (get pods)
[joe@ose3-master ~]$ osc --v=5 get pod
F0518 10:04:15.615550    4100 get.go:70] Error: the server has asked for the client to provide credentials (get pods)
~~~

It should say `Token expired, please login again` or something. 

I tested a little bit old version, so if it has already done, I'm sorry.
~~~
# osc version
osc v0.4.3.2-125-g1104fae
kubernetes v0.14.1-582-gb12d75d
~~~

**Comment by liggitt** [comment]
An expired token is currently not distinguishable from an invalid token from the API

**Comment by sosiouxme** [comment]
In the API it's not distinguishable.

However, the client could make a reasonable guess that if it has a token for an identity, but the API rejects authentication, probably the token is expired.

It's pretty jarring to receive this as the user. At the very least, the client message could give a little context to why the server might be requiring credentials. IMHO...
