### ISSUE TITLE
Deployer pod isn't deleted when the deployment is

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#2316]
When deleting a replication contoller in the cli, its respective deployer pod stays around.

cc: @ironcladlou @smarterclayton

**Comment by smarterclayton** [comment]
@abhgupta FYI, also @bparees / @csrwng because of parallels to build pods (same solution should be in both)

**Comment by ironcladlou** [comment]
Keep in mind that if a user deletes a deployment, as described in #2809 the deployment might automatically get recreated on the next config update even without triggers or a trigger-worthy change.

**Comment by abhgupta** [comment]
Agreed, but this is no different than the deployer pods being deleted for a successful deployment and then the user going ahead an deleting the deployment. A new deployment will be created for any DC update (without a trigger or a bump in LatestVersion) in such a case as well.

**Comment by ironcladlou** [comment]
Also important to note that if you have a configChange trigger and delete the latest deployment, the deployment could get re-created automatically when the deploymentConfigController re-processes events during a reflector resync.

**Comment by ironcladlou** [comment]
In origin we're only registering a single reaper, for DeploymentConfigs. We'll need to add another reaper to handle ReplicationControllers. Caveat: reaping is only performed during delete if cascading is enabled.

**Comment by liggitt** [comment]
does the reaping happen client-side or server-side?

**Comment by kargakis** [comment]
> In origin we're only registering a single reaper, for DeploymentConfigs. We'll need to add another reaper to handle ReplicationControllers. Caveat: reaping is only performed during delete if cascading is enabled.

We already use the Kubernetes reaper for replication controllers. Essentially that's what the dc reaper is under the hood, a wrapper for upstream.

**Comment by liggitt** [comment]
Right, but if you delete an rc directly, does reaping occur?

**Comment by kargakis** [comment]
> does the reaping happen client-side or server-side?

Not sure I understand this question. Client-side the reaper updates the rc.status.replicas and server-side the rc manager takes care of scaling down the controller. Then back on the client we delete the rc.

**Comment by kargakis** [comment]
> Right, but if you delete an rc directly, does reaping occur?

Yep, we default on the [rc reaper](https://github.com/openshift/origin/blob/5cf57679e0744d6946f4523cd6b6512b3c255111/pkg/deploy/reaper/reaper.go#L23)

**Comment by kargakis** [comment]
> Not sure I understand this question. Client-side the reaper updates the rc.status.replicas and server-side the rc manager takes care of scaling down the controller. Then back on the client we delete the rc.

Sorry, I meant the rc.**spec**.replicas

**Comment by ironcladlou** [comment]
I don't see any use of any upstream reapers here:

https://github.com/ironcladlou/origin/blob/master/pkg/cmd/util/clientcmd/factory.go#L123

**Comment by ironcladlou** [comment]
>Right, but if you delete an rc directly, does reaping occur?

Only if you specify --cascade, according to my reading of: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/delete.go#L103

**Comment by kargakis** [comment]
> I don't see the use of any upstream reapers here:
> 
> https://github.com/ironcladlou/origin/blob/master/pkg/cmd/util/clientcmd/factory.go#L123

That's because deploy.ReaperFor is the actual wrapper. It will either return the dc reaper, or if the passed kind isn't a dc, it will defer to [kubectl.ReaperFor](https://github.com/openshift/origin/blob/5cf57679e0744d6946f4523cd6b6512b3c255111/pkg/deploy/reaper/reaper.go#L23)

**Comment by kargakis** [comment]
> Only if you specify --cascade, according to my reading of: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/delete.go#L103

Note though that `--cascade` is [true](https://github.com/openshift/origin/blob/5cf57679e0744d6946f4523cd6b6512b3c255111/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/delete.go#L76) by default.

**Comment by ironcladlou** [comment]
>That's because deploy.ReaperFor is the actual wrapper. It will either return the dc reaper, or if the passed kind isn't a dc, it will defer to kubectl.ReaperFor

Now I see. We should be doing the pass-through in factory.go, not in the deploy package. As it stands, the deploy-specific reaper is effectively the global reaping entrypoint.

**Comment by kargakis** [comment]
You may be right but functionality-wise it will make no difference.

**Comment by ironcladlou** [comment]
Okay, now that we've cleared that all up, consider: If the deployment for the current config version is deleted, the deployment will be recreated automatically the next time the deploymentConfigController's sync interval hits because the system has no means to infer the user's intent. At the post-delete state, the system looks like it would if a new config version were present due to a trigger or other change, and so it'll make a deployment.

**Comment by smarterclayton** [comment]
We shouldn't wrap something unless we actually intend to change this.

----- Original Message -----

**Comment by ironcladlou** [comment]
Would it be okay to spit out some sort of warning when deleting the latest deployment to inform the user that it will be probably be recreated? I have no solution for preventing said redeployment right now.

**Comment by smarterclayton** [comment]
I don't think we have to do anything here today on this.

**Comment by smarterclayton** [comment]
On the last deployment being deleted and then recreated, that is.  As long as our delete order is correct
