### ISSUE TITLE
Release 4.1

### ISSUE THREAD

**Issue by ricardosouzamorais** [openshift/origin#23188]
Guys,
I did not find any information about the release date of OKD 4.1.
Do you guys know?

Thank you so much.

**Comment by ted-bunny** [comment]
Hey, check this blog post out about okd4 and its future:

https://blog.openshift.com/openshift-commons-briefing-okd4-release-and-road-map-update-with-clayton-coleman-red-hat/

**Comment by edysli** [comment]
@ted-bunny That blog post doesn't really explain why this project's releases page barely has a "4.1.0" tag (and no binaries to download) while RedHat already released [OpenShift Container Platform 4.1](https://access.redhat.com/announcements/4180011) a month ago, does it?

**Comment by ted-bunny** [comment]
Hello @edysli 

> @ted-bunny That blog post doesn't really explain why this project's releases page barely has a "4.1.0" tag (and no binaries to download) (...)

No, it doesn't

(...) while RedHat already released [OpenShift Container Platform 4.1](https://access.redhat.com/announcements/4180011) a month ago, does it?

At least it clarifies a bit why OKD hadn't a 4.0 release so far.

**Comment by normanschlatter** [comment]
fyi 4.1 is missing the Dev Console, in a nutshell its a unfinished product, I already deployed 4.1 on premise.

wait for 4.2

![image](https://user-images.githubusercontent.com/37834432/60720639-ae686c80-9f2b-11e9-87f1-eac6a68352c1.png)

**Comment by mliker** [comment]
Hi @normanschlatter can you share your notes on onpremise okd 4.1 install? I don't mind the missing bits a pieces since I build and run Openshift clusters for living and would like to familiarise myself with the new stack.

**Comment by normanschlatter** [comment]
> Hi @normanschlatter can you share your notes on on premise okd 4.1 install? I don't mind the missing bits a pieces since I build and run Openshift clusters for living and would like to familiarise myself with the new stack.

sorry, Im talking about OCP, OKD isnt ready right now, there is no Fedora CoreOS download right now available, please see: https://blog.openshift.com/openshift-commons-briefing-okd4-release-and-road-map-update-with-clayton-coleman-red-hat/

**Comment by amalic** [comment]
It is becoming obvious that OKD has not only low priority at Redhat/IBM.

Here's what is completelly useless for the community:

- The name change from OpenShift Origin to OKD
- The introduction of OpenShift Commons

What the community wants to see:

- A community release with a parallel release cycle to the Enterprise Version
- **A migration path from 3.11 to 4**

If OpenShift continues this path, I see the community looking for alternatives, and recommending other products at their workplaces.

To IBM: Here's how Open Source nowadays works. Organisations who can afford Enterprise Support will always go with this option if available. Organisations who can not afford Enterprise Support will use the community version or alternatives that work. People who have good experience with an Open Source product are very likley to recommend the Enterprise Version of this product at their day-time jobs.

**Comment by jkroepke** [comment]
I recommend to look for alternative before installing OKD 4.

If you really want to use Openshift you have to buy a subscription.

**Comment by amalic** [comment]
Don't get me wrong. I have 3.11 running, and am mostly happy with it.

But at some point projects will require Kubernetes 1.12 and higher. And if there's no upgrade path, people will look for alternatives.

My organisation can not afford an infrastructure group for on-premise cloud computing.

**Comment by philipp1992** [comment]
any news on this? is there any official information about when the open-source version of OpenShift 4.x will be released and installable?

**Comment by jkroepke** [comment]
@philipp1992 since Openshift 4 requires RH CoreOS we have to wait utils Fedora CoreOS is ready.

https://getfedora.org/en/coreos/download/

**Comment by ThinkBriK** [comment]
> The stable release of Fedora CoreOS is expected in late 2019
From https://github.com/coreos/fedora-coreos-tracker

**Comment by ricardo-aspira** [comment]
My main concern is how we would be able to migrate from 3.11 to 4.1 or 4.2.

**Comment by aneagoe** [comment]
afaik it won't be possible to upgrade from 3.11 to 4.x. however, migrating resources and projects should be trivial. With an external LB, you should have an easy time setting up a separate 4.x cluster and migrate workloads at your convenience. You get a fresh start and probably drop a lot of baggage you've accumulated in 3.11. And on the upside, once you're on 4.x it *should* be trivial to stay up to date. While I agree there's some appeal in having some form of upgrade from 3.x to 4.x, in reality it's something quite complex and error prone, with high chances of failure. Even if there was such a thing, I'd still prefer a fresh deployment as a safer migration path.

**Comment by borehack** [comment]
is a little frustrating to have openshift commercial 4x available for month and no progress nor timeline for openshift open-source . as I understand the Red Hat business model that they create commercial products from the open-source base and do some hardening. am I misunderstanding something ?

**Comment by shinebayar-g** [comment]
This is no brainer, they don't wanna release open source version for community. :P

**Comment by sapkra** [comment]
They have to wait until Fedora CoreOS is stable and have to adapt the docs and installer scripts I guess.

The Fedora release is scheduled for late 2019.

**Comment by aneagoe** [comment]
As per https://blog.openshift.com/introducing-red-hat-openshift-4-2-developers-get-an-expanded-and-improved-toolbox (section "Note for community users of OKD") RedHat has actively started working on releasing OKD 4.x. Even more information can be found on the forum: https://groups.google.com/forum/#!forum/okd-wg
However, it is somewhat frustrating to have to go out of your way to understand the current state of affairs with OKD. Communication around OKD seems to be in need of improvement.

**Comment by h-vetinari** [comment]
Fedora CoreOs has an associated github [project](https://github.com/orgs/coreos/projects/84) that gives an overview over the open issues. Late 2019 seems ambituous IMO, but maybe the tracker is not fully representative / up to date.

Also, a roadmap for OKD was merged in openshift/community#55 about a week ago.

**Comment by shulinwz** [comment]
Com'on guys, it's been over a year since the last stable release of OKD...

**Comment by ricardo-aspira** [comment]
I have just migrated to Rancher.

**Comment by shinebayar-g** [comment]
@ricardo-aspira when I move to Rancher I miss Openshift's "PaaS" feeling. Rancher is more like vanilla kubernetes. But good project tho.

**Comment by h-vetinari** [comment]
Some movement with https://github.com/openshift/origin/commit/8189ff86d2478d3701c3aa0e7486de7db07ec2ad (pointing to new OKD info [repo](https://github.com/openshift/okd)), first preview release [here](https://github.com/openshift/okd/releases)...

OKD4 github project [here](https://github.com/orgs/openshift/projects/1).

**Comment by warmchang** [comment]
[OKD 4.x]: first preview drop
https://lists.openshift.redhat.com/openshift-archives/dev/2019-November/msg00005.html
https://mobile.twitter.com/smarterclayton/status/1196477646885965824

**Comment by anroots** [comment]
This is ironic :point_up: 

Openshift 4 / OKD 4 seems stale + rotten. To the developers - I appreciate the work you've been doing (especially on Openshift 3.x OS); but comms around progress / timeline + visible "moving forward" are not optimal. As a community user, I've been trying to figure out what's going on, but can't get a conclusive, clear answer. Best I gathered is that The Company has sidelined/ditched the open source project and only separated a small dev team to it; for lip service. Roadmap seems to always be Soon :tm:.

Hence, after a year+ of silence (and commercial version already being 3 releases ahead), I'm ditching Openshift and moving to vanilla Kubernetes - who has regular releases and is still supported open-source. I will miss Openshift, but I can't see a clear future with it.

> If OpenShift continues this path, I see the community looking for alternatives, and recommending other products at their workplaces.

> is a little frustrating to have openshift commercial 4x available for month and no progress nor timeline for openshift open-source 

Please fix comms around the project to keep others with it. Say clearly what's going on, and what to expect - especially with timelines. Clarify how much effort is put to it compared to the commercial version.

:wave: , :bowing_man: - :fish:

**Comment by edysli** [comment]
/remove-lifecycle rotten
please?
I'd like to see an official reply here.

**Comment by claudio-walser** [comment]
I am in the same boat, this is kind of a joke. I was a huge fan of coreos. Had a hard time to learn/adapt about fedora coreos and redhat enterprise linux coreos.
Was confused about openshift as well, installed a openshift 4 cluster to learn i would need to pay around 60k for licensing my hardware. Gave okd a 4 preview a chance and am now waiting for a stable okd 4 release for a full year. You are loosing a lot of people because of this and as an enduser, it feels like kind of a big mess.
Okd vs openshift is a bit like fcos vs rhelcos. Open Source Versions are upstream, paid versions have stable releases but the os version of both have kind of unsure futures. I really don't get this.

I might shift to vanilla kubernetes as well within the next few weeks...
Which is sad, i liked openshift alot but what happens here is not acceptable.
You should focus to the professional versions maybe and drop the open source versions completly, doing it half helps nobody.

**Comment by philipp1992** [comment]
@dmueller2001 is there an official statement from RH regarding the state of OKD4? Will it become the upstream to RH OpenShift in the future again? Ive followed development of OKD4 and i also think its really sad, that RH is not putting more resources into it.

**Comment by claudio-walser** [comment]
Latest Meeting Minutes are interesting regarding the release timeline:
https://youtu.be/VSnerYEzxtE?t=904

**Comment by vboufleur** [comment]
The video posted in the comment above says that OKD 4 will probably be released together with OCP 4.5 in June or July, this year.
