### ISSUE TITLE
Orign-node service fail to start 

### ISSUE THREAD

**Issue by srvmsr** [openshift/origin#23216]
[origin-node service fail to start]
We are facing below issue in one of our openshift deployments. Origin node service continuously fail to start. can you please have a look.

Error: cannot create kubelet args: cannot parse node address: missing port in address

##### Version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. All in one node deployment with openshift ansible playbook

##### Current Result
 Failed to start OpenShift Node.

##### Expected Result
Origin-node service running without error

##### Additional Information

logs from journalctl -ru origin-node.service

Jun 19 18:49:09 xdxx systemd[1]: Starting OpenShift Node...
Jun 19 18:49:09 xdxx systemd[1]: Stopped OpenShift Node.
Jun 19 18:49:09 xdxx systemd[1]: origin-node.service holdoff time over, scheduling restart.
Jun 19 18:49:03 xdxx systemd[1]: origin-node.service failed.
Jun 19 18:49:03 xdxx systemd[1]: Unit origin-node.service entered failed state.
Jun 19 18:49:03 xdxx systemd[1]: Failed to start OpenShift Node.
Jun 19 18:49:03 xdxx systemd[1]: origin-node.service: main process exited, code=exited, status=1/FAILURE
Jun 19 18:49:03 xdxx origin-node[27904]: Error: cannot create kubelet args: cannot parse node address: missing port in address

[root@xdxx net.d]# systemctl status -l origin-node.service
● origin-node.service - OpenShift Node
   Loaded: loaded (/etc/systemd/system/origin-node.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-06-19 23:21:35 CEST; 2s ago
     Docs: https://github.com/openshift/origin
  Process: 33542 ExecStart=/usr/local/bin/openshift-node (code=exited, status=1/FAILURE)
 Main PID: 33542 (code=exited, status=1/FAILURE)

Jun 19 23:21:35 xdxx systemd[1]: Failed to start OpenShift Node.
Jun 19 23:21:35 xdxx systemd[1]: Unit origin-node.service entered failed state.
Jun 19 23:21:35 xdxx  systemd[1]: origin-node.service failed.

As it was working since 5 days and today the time it crash at same time following file get change and right no content in them

/etc/origin/node/node-config.yaml

and oc adm diagnostics , doesn't report anything as cluster is not running.
dial tcp 10.11.0.34:8443: connect: connection refused

**Comment by imranrazakhan** [comment]
Please share `oc adm diagnostics` output
