### ISSUE TITLE
test-integration tests should all be moved to e2e

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#23258]
`[deads@deads-02 origin]$ grep -h -r "func Test" test/integration/ | awk '{print $2}' | sed 's/.\{2\}$//' | sort | xargs -n1 echo "- [ ] "`

**Build controller tests that do not test valid configuration mechanisms (13) - devex**
- [ ]  TestBuildDefaultAnnotations
- [ ]  TestBuildDefaultEnvironment
- [ ]  TestBuildDefaultGitHTTPProxy
- [ ]  TestBuildDefaultGitHTTPSProxy
- [ ]  TestBuildDefaultLabels
- [ ]  TestBuildDefaultNodeSelectors
- [ ]  TestBuildDeleteController
- [ ]  TestBuildOverrideAnnotations
- [ ]  TestBuildOverrideForcePull
- [ ]  TestBuildOverrideForcePullCustomStrategy
- [ ]  TestBuildOverrideLabels
- [ ]  TestBuildOverrideNodeSelectors
- [ ]  TestBuildOverrideTolerations

**ImageImport tests that rely on unreachable servers or custom config (7) - devex**
- [ ]  TestImageStreamImport
- [ ]  TestImageStreamImportAuthenticated
- [ ]  TestImageStreamImportOfMultiSegmentDockerReference
- [ ]  TestImageStreamImportOfV1ImageFromV2Repository
- [ ]  TestImageStreamImportScheduled
- [ ]  TestImageStreamImportTagsFromRepository
- [ ]  TestRegistryWhitelistingValidation - wired from non-existent config

**OAuth server tests that are not testing validly built configurations (16) - auth**
- [ ]  TestAccessOriginWebConsoleMultipleIdentityProviders
- [ ]  TestAuthProxyOnAuthorize -- sally
- [ ]  TestOAuthBasicAuthPassword -- standa
- [ ]  TestOAuthExpiration
- [ ]  TestOauthExternal
- [ ]  TestOAuthHTPasswd -- standa
- [ ]  TestOAuthLDAP -- matt
- [ ]  TestOAuthOIDC
- [ ]  TestOAuthRequestHeader --matt
- [ ]  TestOAuthRequestTokenEndpoint
- [ ]  TestOAuthServerHeaders
- [ ]  TestOAuthServiceAccountClient
- [ ]  TestOAuthServiceAccountClientEvent
- [ ]  TestOAuthStorage
- [ ]  TestOAuthTimeout
- [ ]  TestOAuthTimeoutNotEnabled
- [ ]  TestUserInitialization - this is tightly coupled to oauth-server

**Remaining integration tests**
- [x]  TestAllowedSCCViaRBAC
- [x]  TestAuthorizationResourceAccessReview
- [x]  TestAuthorizationSubjectAccessReview
- [x]  TestAuthorizationSubjectAccessReviewAPIGroup
- [x]  TestAutomaticCreationOfPullSecrets
- [x]  TestBasicGroupManipulation
- [x]  TestBasicUserBasedGroupManipulation
- [x]  TestBootstrapPolicySelfSubjectAccessReviews
- [x]  TestBrowserSafeAuthorizer
- [x]  TestBuildCompletePodDeleteController
- [x]  TestBuildRunningPodDeleteController
- [x]  TestCLIGetToken
- [x]  TestClusterQuota
- [x]  TestClusterReaderCoverage
- [x]  TestClusterResourceOverridePluginWithLimits
- [x]  TestClusterResourceOverridePluginWithNoLimits
- [x]  TestDefaultWatchCacheSize
- [x]  TestDeploymentConfigDefaults
- [x]  TestDeployScale
- [x]  TestDockercfgTokenDeletedController
- [x]  TestEndpointAdmission
- [ ]  TestEtcd3StoragePath
- [x]  TestFrontProxy
- [x]  TestGroupCommands - already tested in test-cmd
- [x]  TestImageAddSignature
- [x]  TestImageRemoveSignature
- [x]  TestImageStreamAdmitSpecUpdate
- [x]  TestImageStreamAdmitStatusUpdate
- [x]  TestImageStreamImportDockerHub
- [x]  TestImageStreamImportQuayIO
- [x]  TestImageStreamImportRedHatRegistry
- [x]  TestImageStreamMappingCreate
- [x]  TestImageStreamTagLifecycleHook
- [x]  TestImageStreamTagsAdmission
- [x]  TestImageStreamWithoutDockerImageConfig
- [x]  TestIngressIPAllocation - non-functional, it's active/active test . We trust leader election.
- [x]  TestIntegration
- [x]  TestInvalidRoleRefs
- [x]  TestLegacyClusterRoleBindingEndpoint
- [x]  TestLegacyClusterRoleEndpoint
- [x]  TestLegacyEndpointConfirmNoEscalation
- [x]  TestLegacyLocalRoleBindingEndpoint
- [x]  TestLegacyLocalRoleEndpoint
- [x]  TestLogin
- [x]  TestMasterTLSDefaults
- [x]  TestMasterTLSOverrides
- [x]  TestMultipleImageChangeBuildTriggers
- [x]  TestNewAppAddArguments
- [x]  TestNewAppBuildConfigEnvVarsAndSecrets
- [x]  TestNewAppBuildOutputCycleDetection
- [x]  TestNewAppDetectSource
- [x]  TestNewAppListAndSearch
- [x]  TestNewAppNewBuildEnvVars
- [x]  TestNewAppResolve
- [x]  TestNewAppRunAll
- [x]  TestNewAppRunBuilds
- [x]  TestNewAppSourceAuthRequired
- [x]  TestOAuthDisabled
- [x]  TestPodNodeConstraintsAdmissionPluginSetNodeNameClusterAdmin
- [x]  TestPodNodeConstraintsAdmissionPluginSetNodeNameNonAdmin
- [x]  TestPodNodeConstraintsAdmissionPluginSetNodeSelectorClusterAdmin
- [x]  TestPodNodeConstraintsAdmissionPluginSetNodeSelectorNonAdmin
- [x]  TestPodUpdateSCCEnforcement
- [x]  TestPolicyBasedRestrictionOfBuildConfigCreateAndInstantiateByStrategy
- [x]  TestPolicyBasedRestrictionOfBuildCreateAndCloneByStrategy
- [x]  TestPolicyCommands
- [x]  TestProjectIsNamespace
- [ ]  TestProjectRequestError
- [x]  TestProjectRequestLimitAsSystemAdmin
- [x]  TestProjectRequestLimitEmptyConfig
- [x]  TestProjectRequestLimitMultiLevelConfig
- [x]  TestProjectRequestLimitSingleConfig
- [x]  TestProjectWatch
- [x]  TestProjectWatchWithSelectionPredicate
- [x]  TestRegistryClientAPIv2ManifestV2Schema1
- [x]  TestRegistryClientAPIv2ManifestV2Schema2
- [x]  TestRegistryClientConnect
- [x]  TestRegistryClientConnectPulpRegistry
- [x]  TestRegistryClientDockerHubV1
- [x]  TestRegistryClientDockerHubV2
- [x]  TestRegistryClientQuayIOImage
- [x]  TestRegistryClientRegistryNotFound
- [x]  TestRestrictUsers
- [x]  TestRootRedirect
- [x]  TestRunOnceDurationAdmissionPlugin
- [x]  TestRunOnceDurationAdmissionPluginProjectLimit
- [x]  TestScopedImpersonation
- [x]  TestScopedProjectAccess
- [x]  TestScopedTokens
- [x]  TestScopeEscalations
- [x]  TestSelfSubjectAccessReviewsNonExistingNamespace
- [x]  TestSimpleImageChangeBuildTriggerFromImageStreamTagCustom
- [x]  TestSimpleImageChangeBuildTriggerFromImageStreamTagCustomWithConfigChange
- [x]  TestSimpleImageChangeBuildTriggerFromImageStreamTagDocker
- [x]  TestSimpleImageChangeBuildTriggerFromImageStreamTagDockerWithConfigChange
- [x]  TestSimpleImageChangeBuildTriggerFromImageStreamTagSTI
- [x]  TestSimpleImageChangeBuildTriggerFromImageStreamTagSTIWithConfigChange
- [x]  TestTemplate
- [x]  TestTemplateTransformationFromConfig
- [x]  TestTLSDefaults
- [x]  TestTLSOverrides - when we support this, we'll write a new test
- [x]  TestTokensWithIllegalScopes
- [x]  TestTriggers_configChange
- [x]  TestTriggers_imageChange
- [x]  TestTriggers_imageChange_nonAutomatic
- [x]  TestTriggers_manual
- [x]  TestTriggers_MultipleICTs
- [x]  TestUnknownScopes
- [x]  TestUnprivilegedNewProject
- [x]  TestUnprivilegedNewProjectDenied
- [ ]  TestUnprivilegedNewProjectFromTemplate
- [x]  TestWatchCacheSizeWithFlag
- [x]  TestWebhook
- [x]  TestWebhookGitHubPing
- [x]  TestWebhookGitHubPushWithImage
- [x]  TestWebhookGitHubPushWithImageStream
- [x]  TestWebhookTokenAuthn - when we support this, we'll write a new test
- [x]  TestWellKnownOAuth
- [x]  TestWellKnownOAuthOff

**Comment by deads2k** [comment]
`TestClusterReaderCoverage` has been broken because we didn't test it in a real config.  Moved the broken test.

**Comment by deads2k** [comment]
`TestTLSDefaults` has been broken because we didn't test it in an actual cluster

**Comment by sttts** [comment]
We have the oauth tests on the radar and will focus on working on them in the next sprint, tracked in https://jira.coreos.com/browse/MSTR-736 and https://jira.coreos.com/browse/MSTR-511. So they shouldn't block splitting.
