### ISSUE TITLE
Switch PullSecretName and PushSecretName to be ObjectReferences

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2326]
Have to switch from simple strings to ObjectReference for these fields as that is currently the way that upstream agreed on.

Validation needs to check if the namespace is set or not. Currently only 'Name' field will be supported.

Discussion: https://github.com/GoogleCloudPlatform/kubernetes/issues/7018#issuecomment-99630042 and https://github.com/GoogleCloudPlatform/kubernetes/issues/8190#issuecomment-102537079  and https://github.com/GoogleCloudPlatform/kubernetes/pull/7974#issuecomment-102200951

(thanks to @liggitt for providing this info)

**Comment by mfojtik** [comment]
@bparees -> can you assign this to me? will fix this tomorrow morning.

**Comment by bparees** [comment]
you own it.

**Comment by liggitt** [comment]
Make sure we only allow values we honor (currently, just `Name`) to be set.

**Comment by bparees** [comment]
should change the BuildSource SourceSecretName field too, I think.  (including renaming it)

**Comment by mfojtik** [comment]
@bparees I believe there will be more fields.

**Comment by mfojtik** [comment]
cc @smarterclayton

**Comment by liggitt** [comment]
I think that ideally, you would end up with an ObjectReference with Kind, Namespace, and Name set. Kind would be locked to "Secret", Namespace would be locked to the build's namespace, Name would be free, and all other fields would be empty.

**Comment by mfojtik** [comment]
@liggitt Namespace should be empty, or not? And if set, then validation will have to check if it match with Build namespace.

**Comment by mfojtik** [comment]
FYI, we are going to just rename the fields and update documentation (no conversion/backward compat) as it was not out long enough.

**Comment by liggitt** [comment]
Follow the comment thread in https://github.com/GoogleCloudPlatform/kubernetes/pull/7974/files#r30552925 ... eight seconds after that gets resolved, @deads2k will have his PR updated, and you can cherry pick any new type (e.g. `LocalObjectReference`) to use

**Comment by mfojtik** [comment]
@liggitt i'm going to implement the ObjectReference now and do follow up when @deads2k PR lands. I think it would be useful to have at least 'Kind' in the LocalObjectReference. In future we can have more Secret types for example.

**Comment by deads2k** [comment]
> I think it would be useful to have at least 'Kind' in the LocalObjectReference. In future we can have more Secret types for example.

I expect that we'd still handle those like we do today: One `Secret` kind subdivided by `Type`.

**Comment by mfojtik** [comment]
@deads2k does LocalObjectReference has 'Type'? I mean I can have something like:

```json
"pullSecret": {
  "name": "foo",
  "kind": "SecretBar"
}
```

**Comment by deads2k** [comment]
> does LocalObjectReference has 'Type'? I mean I can have something like:

For my immediate purpose, I only need a `name` since it's a list of all one `kind`.  I wasn't going to add more yet, figuring that fewer fields would lead to less contention.

**Comment by mfojtik** [comment]
@deads2k I'm OK with that, was just asking for the future. Current the name of the field (`pushSecret`) already contain the kind.

**Comment by soltysh** [comment]
@mfojtik is there still something left in here to be done or can we close it as is?

**Comment by mfojtik** [comment]
this is done
