### ISSUE TITLE
Remove icons from buttons

### ISSUE THREAD

**Issue by ajacobs21e** [openshift/origin#2329]
![screen shot 2015-05-18 at 2 17 33 pm](https://cloud.githubusercontent.com/assets/6415742/7688607/c08e8ae2-fd73-11e4-99d9-26b35f595fad.png)

Icons on buttons are unnecessarily and add visual clutter. Remove icons (+, -, ->, etc) from all buttons (not just the three shown as examples)

**Comment by liggitt** [comment]
Is `Filter` clear enough by itself? Would you want `Add Filter` instead?

I like having `...` on action buttons that require more information to do what they say. Clicking "Create" doesn't create, it asks you for more info. `...` is a hint that makes me feel safer clicking something, knowing I'll have at least one more step to back out if I want.

**Comment by ajacobs21e** [comment]
Let me check with patternfly tomorrow about filter vs add filter. 

I mentioned on the other issue that ellipses are used to denote truncated text, not additional actions. The button names should be clear what they do and whether or not you're at the end of a task. I don't think having a button that says "Create" on the overview page implies that you'll create something just by clicking that button - @rhamilto what are your thoughts? Another option is to change this to a link which implies that it will take you somewhere else to do stuff (although that's not a strict relationship anymore) but that will make it more obvious and I assume creating an app or component is a primary action from the overview page.

**Comment by rhamilto** [comment]
I agree with @liggitt about "Add Filter" vs "Filter".

I agree with @ajacobs21e about ellipses in button labels and @liggitt about using "Create" if there is more to go.  Maybe the button label on this page is simply "Next"?

**Comment by ajacobs21e** [comment]
"Add Filter" works for me then. 

The "Create" button on the overview page is how you enter the create wizard. Within that wizard any intermediate steps should say Next (which it already does) and the final step should be "Create". I don't think having a "Create" button on the overview page implies that there are no secondary steps. 

Here's an example from our support case list - There's a "Create" button at the top of the form which then brings you to the case creation wizard. 
![screen shot 2015-05-19 at 10 11 16 am](https://cloud.githubusercontent.com/assets/6415742/7704985/9bdc82d4-fe0f-11e4-9f08-5d3cf376da6c.png)

**Comment by liggitt** [comment]
@rhamilto is very agreeable today :)

I still prefer an ellipsis on the button that launches you into create wizard. Ellipses have been used to indicate "more information required" by both major operating systems for decades. `Open File...`, `Save Page As...`, and `Print...`, just in my Firefox File menu.

**Comment by ajacobs21e** [comment]
While using ellipses on a menu or even on a button isn’t wrong it is an older UI style and doesn’t match patternfly. It adds length to the button and isn’t necessary from a UX perspective. 

Allie
calendar: https://www.google.com/calendar/b/1/embed?src=ajacobs@redhat.com&ctz=America/New_York

**Comment by ajacobs21e** [comment]
@liggitt I talked with @smarterclayton and he mentioned that in the CLI the closest equivalent to this action uses the command "New". Would you be ok with renaming the button on the overview page to "New"?

**Comment by liggitt** [comment]
sure, Create, New, Add, I'm fine with whatever. I like the ellipsis leading into a wizard flow, but I'm not going to die if it's removed.

**Comment by ajacobs21e** [comment]
If you're ok with it I think changing this button to "New" to match the CLI command and distinguish it from the final action (create) is the best option.

**Comment by spadgett** [comment]
@ajacobs21e @smarterclayton The proposal is to change both `Create` buttons to `New`, right? On the projects page as well as the overview?

@ajacobs21e @liggitt How do you feel about just `Add` for the add filter button? It does say `Filter by labels` above the field.

**Comment by ajacobs21e** [comment]
@spadgett what page do you mean by "projects page"?

**Comment by spadgett** [comment]
The initial console page that shows all the projects.

**Comment by ajacobs21e** [comment]
![screen shot 2015-05-20 at 11 38 10 am](https://cloud.githubusercontent.com/assets/6415742/7729797/b86cfd7c-fee4-11e4-8dce-d2f8d0bfce1e.png)

That page? I don't see a create button. Is there going to be one added?

**Comment by spadgett** [comment]
Yeah, sorry. It's merged, but the staging server doesn't have it.

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7729849/f93c8944-fee4-11e4-9bd8-6b7c7d415e50.png)

**Comment by ajacobs21e** [comment]
Ah ok thanks Sam. Yeah I would make that button also "New" assuming that it will take you to some sort of wizard to create a project with "Create" being the final step of that wizard.

**Comment by spadgett** [comment]
Right. It's a one page form rather than a wizard, but `Create` is the button label when you're done.

**Comment by liggitt** [comment]
> How do you feel about just Add for the add filter button?

Fine with me
