### ISSUE TITLE
Enhancement: ETA progress bars for image builds

### ISSUE THREAD

**Issue by mcandre** [openshift/origin#23292]
On image build pages, include a progress bar tracking the current time against the estimated build time, based on the average build time for earlier runs of the same image build. This helps users get a ballpark figure for when the image build will conclude, which the user can then factor into decisions about what to work on while the image is building (10 seconds vs 10 minutes).

https://xkcd.com/303/

Jenkins offers a similar helpful feature, and I think it's really handy!

**Comment by adambkaplan** [comment]
fyi @openshift/openshift-team-developer-experience @openshift/openshift-team-user-interface
