### ISSUE TITLE
Inconsistent tooltips

### ISSUE THREAD

**Issue by ajacobs21e** [openshift/origin#2330]
![screen shot 2015-05-18 at 1 24 57 pm](https://cloud.githubusercontent.com/assets/6415742/7688622/e88a5ee0-fd73-11e4-908a-84af0d764130.png)
![screen shot 2015-05-18 at 1 25 14 pm](https://cloud.githubusercontent.com/assets/6415742/7688623/ea368b4c-fd73-11e4-999f-020a4b37044c.png)
![screen shot 2015-05-18 at 1 30 39 pm](https://cloud.githubusercontent.com/assets/6415742/7688626/eccffe88-fd73-11e4-8422-bd3d6acef8f0.png)

Three different tooltip styles are used in the UI with differing functionality. All tooltips should use the styling of the first example (from the Settings menu) with a white background and the tooltip pointing towards the (?) icon. Tooltips should appear on hover.

**Comment by spadgett** [comment]
@ajacobs21e Where did you see the "Please fill out this field" tooltip? That one comes from the browser, not us, but there might be something we can do.

**Comment by ajacobs21e** [comment]
![tooltip 1](https://cloud.githubusercontent.com/assets/6415742/7709876/f73d6b8e-fe2d-11e4-98b7-cb82bc867917.png)

I can't recreate it now though. I think @rhamilto originally found this tooltip

**Comment by spadgett** [comment]
The tooltip on the settings page is actually a Bootstrap popover, which is a different component. We can change it to a tooltip to get the hover behavior and adjust the Bootstrap tooltip styles so it is black text on a white background.

**Comment by ajacobs21e** [comment]
That sounds good. I did find another issue that seems like it won't be an issue if the popovers are switched to tooltips - if you click on a (?) before the content has loaded, once the page loads, the popover stays where it was instead of 'following' the tooltip icon. In this case it's now floating in the middle of the table. 
![screen shot 2015-05-19 at 3 43 11 pm](https://cloud.githubusercontent.com/assets/6415742/7712217/f279ff62-fe3d-11e4-9cb7-f293f0b43efe.png)

**Comment by liggitt** [comment]
can you open another issue for that?

**Comment by ajacobs21e** [comment]
@liggitt will it still be an issue if the tooltip only appears on hover?

**Comment by liggitt** [comment]
I don't know

**Comment by spadgett** [comment]
#2388 removes the "Please fill out this field" tooltip. #2543 changes the popup to a tooltip on the settings page. These were the two inconsistencies I knew of. I haven't changed the styling to a white background, but I don't think we should do that for 3.0. I think we can close when #2543 is merged.

**Comment by ajacobs21e** [comment]
Sounds good thanks @spadgett

**Comment by spadgett** [comment]
@liggitt or @ajacobs21e close this one?
