### ISSUE TITLE
cri-o uid/gid mapping fails for root inside container, pod does not work

### ISSUE THREAD

**Issue by markusdd** [openshift/origin#23325]
we use openshift 3.11 on bare metal with single master and 3 nodes for our CI cluster purposes. We switched to crio when installing 3.11 but are facing issues when spawning our gitlab-runner pod. When looking inside the main user gets not properly mapped to root but has some arbitrary user id, causing all kinds of weird side effects because it cannot access /root (e.g. it tries to create a .gitconfig file in filesystem root /)

We know that podman and crio use that user id mapping concept for better security and enabling rootless containers, but this particular one gets launched by root on the CI host and must be root inside as well.

##### Version
3.11

##### Steps To Reproduce
1. use a crio based 3.11 node with EL7/CentOS7 as bare metal base
2. deploy a gitlab-runner pod (or possibly anything that relies on being root inside the container)

##### Current Result
user in container is some unknown entity with id 10000800 and can do basically nothing because it has no home and no rights (*sadface* :( )

##### Expected Result
crio is called using proper UID/GID mappings so process in container thinks it runs as root.

Documentation is very limited on how to use crio with OKD 3.11. Any help?

**Comment by rjhowe** [comment]
Not an issue with the runtime, by default OKD runs pods with the restricted SCC, which sets the user for the containers to a high UID based on the `openshift.io/sa.scc.uid-range` project annotation. 

If you wish to run as a different user you will need to add the service account used by your pod to a SCC that allows you to run as a user of your choosing.
<https://docs.okd.io/3.11/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root>

**Comment by markusdd** [comment]
Yes, we have figured that out by now. I recommend that this is made clearer in the documentation because it wasn't obvious in any way and caused a 1 day debugging session for 2 people until we understood what is causing this remapping.
But it's all good now, this can be closed (except for the documentation request maybe)
