### ISSUE TITLE
Remove ellipses

### ISSUE THREAD

**Issue by ajacobs21e** [openshift/origin#2332]
![screen shot 2015-05-18 at 1 43 09 pm](https://cloud.githubusercontent.com/assets/6415742/7688698/b0a64ad8-fd74-11e4-93fd-7f88c37e5aa7.png)

Remove ellipses from link (and all links/buttons within the UI).

**Comment by liggitt** [comment]
Not all buttons, surely...
without ellipsis, change text to "Show details"/"Hide details"?

**Comment by ajacobs21e** [comment]
Ellipses should only be used when text is cut off, like this https://github.com/openshift/origin/pull/2328

In this case they're used to try to show an action so any cases like that ellipses should be removed. 

And yes action words like "show" "hide" are better than "more / less"

**Comment by spadgett** [comment]
If we remove the ellipsis from the `Create...` buttons, we should add an object. `Create Project` and maybe `Create Component` or `Create Application`?

`Create` on its own looks strange because there's not enough context to know what you're creating. With the ellipsis at least you know there's another page and you aren't creating some unknown thing immediately. There's a comfort knowing you can cancel.

The `Create...` button on the all project page looks too much like the `Create...` button after selecting a project. They're in the same place with the same label, but do very different things.

**Comment by liggitt** [comment]
+1 for "Create Project"
Not sure what I would say for "Create Application"/"Create Component"...

**Comment by ajacobs21e** [comment]
That's what I've struggled with. What is the user creating? What are all of
the potential things that can be created? Are "application" or "component"
the only two options?

On Tue, Jun 23, 2015 at 9:49 AM, Jordan Liggitt <notifications@github.com>
wrote:

> +1 for "Create Project"
> Not sure what I would say for "Create Application"/"Create Component"...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2332#issuecomment-114512259>.
>



-- 

Allie Jacobs
UXD

calendar
<https://www.google.com/calendar/b/1/embed?src=ajacobs@redhat.com&ctz=America/New_York>

**Comment by liggitt** [comment]
They are creating "stuff" in a project

**Comment by ajacobs21e** [comment]
Would a term like "populate project" work better then?
Or "add to project"?

On Tue, Jun 23, 2015 at 10:16 AM, Jordan Liggitt <notifications@github.com>
wrote:

> They are creating "stuff" in a project
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2332#issuecomment-114519896>.
>



-- 

Allie Jacobs
UXD

calendar
<https://www.google.com/calendar/b/1/embed?src=ajacobs@redhat.com&ctz=America/New_York>

**Comment by spadgett** [comment]
I like "Add to Project" or "Add Components."

Maybe "New Project" instead of "Create Project" on the all projects page.

**Comment by spadgett** [comment]
New Project or Create Project? Command line is `oc new-project`.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8413456/93b052ba-1e5e-11e5-9e43-f56305da4c39.png)

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8413463/a3c08b20-1e5e-11e5-858b-f4f18214e2d8.png)

**Comment by ajacobs21e** [comment]
New to match the command line sounds best

On Mon, Jun 29, 2015 at 12:59 PM, Sam Padgett <notifications@github.com>
wrote:

> New Project or Create Project? Command line is oc new-project.
>
> [image: openshift_web_console]
> <https://cloud.githubusercontent.com/assets/1167259/8413456/93b052ba-1e5e-11e5-9e43-f56305da4c39.png>
>
> [image: openshift_web_console]
> <https://cloud.githubusercontent.com/assets/1167259/8413463/a3c08b20-1e5e-11e5-858b-f4f18214e2d8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2332#issuecomment-116761462>.
>



-- 

Allie Jacobs
UXD

calendar
<https://www.google.com/calendar/b/1/embed?src=ajacobs@redhat.com&ctz=America/New_York>

**Comment by spadgett** [comment]
How about `New App` to mirror CLI `oc new-app`?

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8414424/dc574cce-1e65-11e5-9916-c5e7cce78da8.png)

**Comment by liggitt** [comment]
new-app is half of what that button exposes... the other half (create from template) isn't really covered by "New App"

**Comment by spadgett** [comment]
I thought you could create from template using `new-app`?

https://docs.openshift.org/latest/dev_guide/new_app.html#specifying-a-template

**Comment by ajacobs21e** [comment]
@liggitt that's why I think something like "Add to Project" or "Add Components" is a better label. Does "Add Services" make sense?

**Comment by liggitt** [comment]
Yeah, I prefer "Add to Project", even if `oc new-app` does let you create
from templates (which I didn't realize)

**Comment by ajacobs21e** [comment]
Sorry @liggitt @spadgett I forgot there was a reason to not use "New Project". Patternfly uses "Create" for action labels so this button should say "Create Project" to align with patternfly. The CLI should use patternfly terminology as well.

**Comment by liggitt** [comment]
the OpenShift UI should align with the OpenShift CLI first... can open a separate issue to change CLI terminology if you like

**Comment by spadgett** [comment]
OK, here's "Add to Project." I'll update the pull request.

![openshift_web_console_and__no_service_for_this_pod__is_confusing_ _issue__1909_ _openshift_origin](https://cloud.githubusercontent.com/assets/1167259/8415712/e4ff89d2-1e6e-11e5-8bbc-23842ea9a285.png)
