### ISSUE TITLE
error: build error: Failed to push image: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp 172.30.120.155:5000: connect: no route to host

### ISSUE THREAD

**Issue by PhilippeA1** [openshift/origin#23330]
I have an issue after installing a fresh okd 3.11 with 1 master and 2 nodes : 

error: build error: Failed to push image: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp 172.30.120.155:5000: connect: no route to host. 

[provide a description of the issue]

**Version** 

oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.11.0+3a34b96-217
kubernetes v1.11.0+d4cacc0

Steps to Reproduce 

1) Install OKD 3.11 with 1 master,infra and 2 worker node
2) Create a new project and a new sample application

 oc new-project sdn-test
 => OK
 
 oc new-app centos/httpd-24-centos7~https://github.com/sclorg/httpd-ex
 
 Pushing image docker-registry.default.svc:5000/sdn-test/httpd-ex:latest ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Warning: Push failed, retrying in 5s ...
Registry server Address:
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
**error: build error: Failed to push image: After retrying 6 times, Push image still failed due to error: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp 172.30.120.155:5000: connect: no route to host**

Expected Result

OKD should be creating and running the pod successfully

[root@tstoshiftm1 ~]# oc get svc

NAME       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
httpd-ex   ClusterIP   172.30.107.22   <none>        8080/TCP,8443/TCP   5m

[root@tstoshiftm1 ~]# oc get pods 

NAME               READY     STATUS    RESTARTS   AGE
httpd-ex-1-build   0/1       Error     0          5m

[root@tstoshiftm1 ~]# nslookup docker-registry.default.svc

Server:         192.168.210.197
Address:        192.168.210.197#53

Name:   docker-registry.default.svc.cluster.local

[root@tstoshiftm1 ~]# curl -k -v https://docker-registry.default.svc:5000

About to connect() to docker-registry.default.svc port 5000 (#0)
  Trying 172.30.120.155...
Connected to docker-registry.default.svc (172.30.120.155) port 5000 (#0)
Initializing NSS with certpath: sql:/etc/pki/nssdb
skipping SSL peer certificate verification
SSL connection using TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
Server certificate:
      subject: CN=172.30.120.155
      start date: jui 04 13:09:22 2019 GMT
      expire date: jui 03 13:09:23 2021 GMT
      common name: 172.30.120.155
      issuer: CN=openshift-signer@1562245304
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: docker-registry.default.svc:5000
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Date: Mon, 08 Jul 2019 12:27:34 GMT
< Content-Length: 0
<
* Connection #0 to host docker-registry.default.svc left intact

**Comment by rjhowe** [comment]
This looks like an issue with the install of your cluster.
On the node where the build ran, see you can connect to the registry service ip and pod endpoint ip, if those fails check to make you have 4789/udp open between your nodes.

**Comment by PhilippeA1** [comment]
How can i connect to the registry service ip and pod endpoint ? 

On my firewall 4789/udp seems open : 

[root@tstoshiftm1 ~]# firewall-cmd --list-ports
10250/tcp 10256/tcp 80/tcp 443/tcp **4789/udp** 9000-10000/tcp 1936/tcp 2379/tcp 2380/tcp 8443/tcp 8444/tcp 8053/tcp 8053/udp 5000/tcp
