### ISSUE TITLE
Remove or collapse details on success messages

### ISSUE THREAD

**Issue by ajacobs21e** [openshift/origin#2333]
![screen shot 2015-05-18 at 1 52 17 pm](https://cloud.githubusercontent.com/assets/6415742/7688701/b9cfbdf6-fd74-11e4-857c-73a3ab956eb6.png)

Success message displays with details expanded. Details are redundant for a success message and should not be displayed or if they must be displayed should be collapsed with a “more details” link.

**Comment by spadgett** [comment]
Fixed by https://github.com/openshift/origin-web-console/pull/225
