### ISSUE TITLE
Add "manage all projects" link

### ISSUE THREAD

**Issue by ajacobs21e** [openshift/origin#2334]
![screen shot 2015-05-18 at 12 59 49 pm](https://cloud.githubusercontent.com/assets/6415742/7688712/dcdf712e-fd74-11e4-9cf1-2076af73cbb2.png)

Add “Manage all projects” link below project list, separated by a horizontal rule.
[FUTURE: add “create project” link here as well.]

**Comment by spadgett** [comment]
@ajacobs21e where does "manage all projects" take you?

**Comment by ajacobs21e** [comment]
@spadgett https://console.stg.openshift.com/console/

**Comment by spadgett** [comment]
Not sure on the label because you can't really manage the projects from that page, only look at them and click on them. "View All Projects" or "Console Home"?

Create project is done, so we could add a Create Project option.

**Comment by ajacobs21e** [comment]
“View all projects” and “Create a project” work

Allie
calendar: https://www.google.com/calendar/b/1/embed?src=ajacobs@redhat.com&ctz=America/New_York

**Comment by liggitt** [comment]
Right now, knowing whether we have project creation ability requires a request to the server.

**Comment by spadgett** [comment]
@benjaminapetersen

**Comment by benjaminapetersen** [comment]
Quick progress update on this item.  
- We get this component from Patternfly, who pull bootstrap-select as a third party component.
- I'm attempting to get the HTML generation out of the JS (directives/nav.js) and into the html template (/views/directives/_project-nav.html) where it belongs.
- bootstrap-select doesn't handle ng-repeat bindings well, it struggles with rendering & errors out ([example issue](https://github.com/silviomoreto/bootstrap-select/issues/864))
- There is a third party component wrapper called [angular-bootstrap-select](https://github.com/joaoneto/angular-bootstrap-select) that seems to fix the binding problem
- I'm reviewing this wrapper for performance/payload/bugs to see what we would gain by using it
- fixing this issue will allow us to add the hr & link right into the template file after the project links block

**Comment by benjaminapetersen** [comment]
Todos
- [ ] test out [angular-bootstrap-select](https://github.com/joaoneto/angular-bootstrap-select)
- [ ] integrate, or create a new simple directive to wrap & deal with the render issue
- [ ] then add the rule & link.

**Comment by jwforres** [comment]
Not having a "View all" drives me crazy, so I'm bumping up the priority on this :)

**Comment by spadgett** [comment]
Opinions on the label? Since you can now create and delete projects, I'm fine with "Manage Projects."

**Comment by jwforres** [comment]
Eh, to me "manage" implies more than just being able to delete them.  I would probably just leave it as "View all projects"

**Comment by ajacobs21e** [comment]
Are there other actions that can be taken on projects (in the CLI) other
than add and delete?

On Fri, Sep 4, 2015 at 4:21 PM, Jessica Forrester <notifications@github.com>
wrote:

> Eh, to me "manage" implies more than just being able to delete them. I
> would probably just leave it as "View all projects"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2334#issuecomment-137844011>.
>



-- 

Allie Jacobs
UXD

calendar
<https://www.google.com/calendar/b/1/embed?src=ajacobs@redhat.com&ctz=America/New_York>

**Comment by spadgett** [comment]
Changed label to "View all projects" in the pull (for now at least). I don't have a strong opinion on the name.
