### ISSUE TITLE
Rolling updates of routers

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#2335]
As an administrator how do I perform a rolling update of routers when a router is binding to host ports and running in an HA mode.  

Issue: if there are limited nodes (ie. 2) and a router is running on both nodes the rolling update has nowhere to bring up new routers since no nodes will be considered as available due to the host port being taken.

/cc @smarterclayton @ramr @ironcladlou @abhgupta

**Comment by smarterclayton** [comment]
This may mean rolling-update is fundamentally broken in the context of scheduler constraints, which is another big problem.

**Comment by smarterclayton** [comment]
Or that we need a strategy or tunable that takes that into account

**Comment by ramr** [comment]
So in the past [in a square world], we have used a procedure where we operated on 1 instance at a time to do a stop/deploy new code/start. 
In the brave new [perfectly kubeoid] world (minecraft), could this be done via a procedure that's something like: 
1. There exists a current replication controller RC1 with  'n' replicas. For true HA, n > 1, anything else means you like your downtime!!
2.  Create the next version of the RC for the rolling update/upgrade - let's call it RC2.
3. Set replica count of RC2 to n.
4. Loop until RC1 has 0 replicas and RC2 has n.  Sum of RC1 + RC2 replicas should be atleast 'n'  (will be more if you have more available nodes and that's good but if not it will be 'n' to start off with). 
5.  Basically in the case of n == 2 and 2 nodes, this means RC1 will have n replicas and RC2 will have 0 to start off with (and you could well be "1 node/step closer to disaster").
6. Reduce RC1 replica count by 1 and ensure 'n' replicas exist - if needed, wait till RC2 has enough (1 more) to ensure the 'n' replicas. 
7. Go back to 4 and loop through again. 

Its a bit rough but hopefully it explains what I wanted to say. 
In the case of more nodes available than the replicas requested for, the step 6 above would be a ```NOOP``` till the number of replicas for RC1 is reduced to a point where the number of available nodes (satisfying the 80/443 requirement is exhausted). 
And in the case of n=2 and number of nodes = 2 - that means we will spin down 1 container for RC1 and wait for the new RC (RC2) to get a replica up and running - so there is some degradation in capacity.

Just some thoughts.

**Comment by smarterclayton** [comment]
It sounds like a custom rolling update strategy which is n-x, where x is the downtime you're willing to accept.

**Comment by smarterclayton** [comment]
We should fix this by double checking our default router config for the correct rolling parameters
