### ISSUE TITLE
`oc debug node/` is broken

### ISSUE THREAD

**Issue by cgwalters** [openshift/origin#23371]
Using an oc from master as of ~yesterday:

```
$ oc debug node/ip-10-0-163-63.us-east-2.compute.internal
error: cannot debug ip-10-0-163-63.us-east-2.compute.internal: unable to extract pod template from type *v1.Node
$
```

Works fine when built from the `v4.1.0` tag.

**Comment by lance** [comment]
I am experiencing the same problem while following these steps to access the registry from the cluster following these steps. https://docs.openshift.com/container-platform/4.1/registry/accessing-the-registry.html#registry-accessing-directly_accessing-the-registry

**Comment by bryantson** [comment]
Encountering the same issue as well. What is the underlying cause of this?

**Comment by Drakkai** [comment]
Did anyone find a workaround for this issue? I faced the same problem.

**Comment by dongwangdw** [comment]
https://access.redhat.com/solutions/5214171

**Comment by SISheogorath** [comment]
Came across this as well, hit the RH paywall, but hey, fiddling a bit around I noticed that my local oc version where it didn't work and my toolbox container one, where it did work, had different versions.

So if you hit this, you probably run and old `oc` version e.g. from the Fedora packages. `dnf remove origin-clients` should remove the old version and your cluster should offer a download for the new client.
