### ISSUE TITLE
Official OKD 4 Timeline

### ISSUE THREAD

**Issue by thecrudge** [openshift/origin#23554]
Could use a timeline for the OKD 4 release

##### Version

4

##### Steps To Reproduce
1. Try to install branch release-4.*

##### Current Result
Not able

##### Expected Result
Install OKD 4

**Comment by AkihiroSuda** [comment]
see https://github.com/openshift/origin/issues/23188#issuecomment-508733375

**Comment by thecrudge** [comment]
Hi @AkihiroSuda 

I guess my point of this Issue, is that I did not ass an issue opened so that the community could follow the progress being made for OKD 4, and that maybe there should be.
