### ISSUE TITLE
Should `oc ... -o json` have warnings on stderr, not stdout?

### ISSUE THREAD

**Issue by eedrah** [openshift/origin#23588]
I'm new to Openshift, so let me know if this belongs somewhere else, or if I'm doing something wrong :)

When I do a command that outputs JSON, yet also produces a warning, my warning shows up in the output, and I cannot parse this as JSON. Example below.

##### Version
```
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0+b4261e0", GitCommit:"b4261e07ed", GitTreeState:"clean", BuildDate:"2019-07-06T03:16:01Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+6569b4f", GitCommit:"6569b4f", GitTreeState:"clean", BuildDate:"2019-07-10T19:31:33Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
```

##### Steps To Reproduce
1. `cd` to a git repository (mine is private, but that may not be necessary)
2. `oc new-app $(git remote get-url origin) --dry-run --context-dir my-dir --name mw -o json > my.json` (`--context-dir` may not be necessary)

##### Current Result
File `my.json` should be pure json

No warnings or errors show up on the command line through stderr

##### Expected Result
Line 1 of file `my.json` has `warning: Cannot check if git requires authentication.`

Stderr should show the warning.

**Comment by eedrah** [comment]
# Current workaround 
(Will try and keep this updated with a link to the best solution in the below comments)

Manually examine and pass to `tail -n +2` if one line of warnings is shown

**Comment by thanhnamit** [comment]
It seems under the path /pkg/oc/lib/newapp/app/sourcelookup.go Line 318, the warning message is redirected to standard out:

`fmt.Print("warning: Cannot check if git requires authentication.\n")`

Where the common pattern in other file is using 

`fmt.Fprint(io.Writer, "Message")`

Should it be: `fmt.Fprint(r.ErrOut, "warning: Cannot check if git requires authentication.\n")`
