### ISSUE TITLE
Popover doesn't move with tooltip icon if more content loads

### ISSUE THREAD

**Issue by ajacobs21e** [openshift/origin#2361]
if you click on a (?) before the content has loaded, once the page loads, the popover stays where it was instead of 'following' the tooltip icon. In this case it's now floating in the middle of the table. 
![screen shot 2015-05-19 at 3 43 11 pm](https://cloud.githubusercontent.com/assets/6415742/7712411/40a83fea-fe3f-11e4-9924-fb623a4a55cf.png)

**Comment by spadgett** [comment]
Unfortunately, using a tooltip rather than a popover doesn't fix the problem.

**Comment by liggitt** [comment]
Not sure we'll be able to fix the issue with tooltips following shifting content. An alternative fix might be to wait until the content is loaded to show the quota section at all...

**Comment by spadgett** [comment]
I believe the problem was `data-container="body"`, which I didn't remove when first testing the tooltip. #2543 may fix. I'll test.

**Comment by spadgett** [comment]
It's still a problem, although it's probably less likely to occur now. You have to have your mouse over the (?) icon just as the content loads.

**Comment by spadgett** [comment]
I suggest we close this. It's not a serious, and it's a problem in the Bootstrap component, not our code. Tooltip placement has also changed in Bootstrap 4 alpha.

**Comment by liggitt** [comment]
Agree
