### ISSUE TITLE
Failure to push image to OpenShift’s Registry when backed by gluster storage

### ISSUE THREAD

**Issue by yeganx** [openshift/origin#23623]
I have install containrized glusterfs storage on my openshift cluster.
```
oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://lb.example.com:8443
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0
```
my docker register backed by gluster 
and every thing was ok 
now I have error in pushing images to registery 
`error: build error: Failed to push image: received unexpected HTTP status: 500 Internal Server Error`
I check the registery pod :
```
oc rsh docker-registry-5-ttq7n
sh-4.2$ df -h
Filesystem                                           Size  Used Avail Use% Mounted on
192.168.96.217:vol_85c90d08571da259f83f6a69941fbe9d  3.0G  3.0G     0 100% /registry

```
how can I increase the volume or set it dynamic size?

**Comment by adambkaplan** [comment]
The disk for the registry is full. You need to allocate more storage to your gluster storage, and then you may need to delete the registry pod (a new one will spawn with the larger volume).
