### ISSUE TITLE
Expose `OPENSHIFT_BUILD_*` parameters as Docker Build `ARG` values.

### ISSUE THREAD

**Issue by greg-pendlebury** [openshift/origin#23638]
## Feature Suggestion
Expose `OPENSHIFT_BUILD_*` parameters as Docker Build `ARG` values.

Unless I am missing something (apologies if so) I cannot see a way for the Dockerfile to reference these values. Reading through `builder/common.go` and `builder/docker.go` it looks like the various `OPENSHIFT_BUILD_*` values are provided in string literal form and appended onto the Dockerfile to provide `ENV` values inside the container. They are not supplied as parameters which can be accessed using `ARG`.

## Version
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://<snip>
openshift v3.11.117
kubernetes v1.11.0+d4cacc0
```

## Use case
Our current build tool in Azure DevOps supplies the `BUILD_ID` as an `ARG` to the Dockerfile. During the image build, once the ID of the image is known, all static assets have this included in their file names. This serves two purposes:
 1. Cache busting of static assets to ensure that release of a new image requires clients to use new static assets.
 2. Avoids file name clashes and overwrites when static assets are migrated to a CDN during a rolling deploy when both images might still be serving traffic and both versions of static assets should remain addressable.

Current code stub to achieve this:
```
ARG BUILD_ID                                   # Get value from DevOps
ENV BUILD_ID ${BUILD_ID:-B0000}                # Safety line with default fallback
RUN sh startup-scripts/addHash.sh $BUILD_ID    # Add hash value to static assets
```

## Possible Workaround
I suspect we could possibly do something similar using `buildArgs` under `dockerStrategy`. It requires an extra layer of work, but I think it would work... just I'm not currently aware of what variables I can access there that would be useful. Anything unique to the build is useful/workable, hence I was looking for any of `OPENSHIFT_BUILD_*`.

e.g.:
```
  strategy:
    dockerStrategy:
      buildArgs:
        name: BUILD_ID
        value: ${SOME_VARIABLE_HERE}
```

**Comment by adambkaplan** [comment]
fyi @openshift/openshift-team-developer-experience

**Comment by greg-pendlebury** [comment]
This would still be very useful to us in aligning metadata between version control and the docker image stream.

/remove-lifecycle rotten
