### ISSUE TITLE
Adding labels to images built with S2I binary build

### ISSUE THREAD

**Issue by FabianWilms** [openshift/origin#23643]
To have a better overview what each image we built contains we want to add a label to each image with the artifacts version as a value.

To build the images we start a S2I binary-build by uploading a .jar-File to Openshift with the `oc start-build` command. I expected to be able to define labels with the start-build-Command and tried adding `--build-arg --label="foo=bar"` for testing purposes and following dockers way to label images but the label doesn't show up in the resulting image. 

Is there any other way to accomplish this that I haven't found? It would also be an option to annotate the resulting image if that is easier to accomplish.

##### Version

v3.10.101 

##### Steps To Reproduce

1. `oc start-build --from-file=artifact.jar --build-arg "--label"="foo=bar"

##### Current Result

No label get's added to the resulting image.

##### Expected Result

The image  created by the S2I-Build contains the label `foo` with value `bar`.

**Comment by adambkaplan** [comment]
@FabianWilms you can add a label to an image by editing the `output` portion of the BuildConfig. However, this isn't something that can be set on a per-build basis (as one would with `oc start-build`).

**Comment by FabianWilms** [comment]
@adambkaplan Thanks for the reply!

Do you have another solution on how to add this information to an image via `start-build`? We just want to be able to determine the contents of the image without creating loads of tags.
