### ISSUE TITLE
Can't import image via imagestreams

### ISSUE THREAD

**Issue by MrMEEE** [openshift/origin#23642]
I can't get imagestreams to work with my local registry.....

`
[root@aptacmaster01 spilbraetv1]# oc create secret docker-registry harbor-secret --docker-server=registry.aperta.dk:5000 --docker-username=************* --docker-password="***********"
secret/harbor-secret created
[root@aptacmaster01 spilbraetv1]# oc create imagestream fafnir-sso
imagestream.image.openshift.io/fafnir-sso created
[root@aptacmaster01 spilbraetv1]# oc secrets link default secrets/harbor-secret --for=pull
[root@aptacmaster01 spilbraetv1]# oc --loglevel 9 import-image fafnir-sso --from=registry.aperta.dk:5000/spilbraet/fafnir-sso:1.0.84 
I0821 14:59:00.708190   35344 loader.go:359] Config loaded from file /root/.kube/config
I0821 14:59:00.715796   35344 loader.go:359] Config loaded from file /root/.kube/config
I0821 14:59:00.717787   35344 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0" 'https://aptacmaster01.aperta.lan:8443/apis/image.openshift.io/v1/namespaces/spilbraet/imagestreams/fafnir-sso'
I0821 14:59:00.754104   35344 round_trippers.go:405] GET https://aptacmaster01.aperta.lan:8443/apis/image.openshift.io/v1/namespaces/spilbraet/imagestreams/fafnir-sso 200 OK in 35 milliseconds
I0821 14:59:00.754378   35344 round_trippers.go:411] Response Headers:
I0821 14:59:00.754804   35344 round_trippers.go:414]     Cache-Control: no-store
I0821 14:59:00.754983   35344 round_trippers.go:414]     Content-Type: application/json
I0821 14:59:00.755158   35344 round_trippers.go:414]     Content-Length: 465
I0821 14:59:00.755333   35344 round_trippers.go:414]     Date: Wed, 21 Aug 2019 12:59:00 GMT
I0821 14:59:00.755561   35344 request.go:897] Response Body: {"kind":"ImageStream","apiVersion":"image.openshift.io/v1","metadata":{"name":"fafnir-sso","namespace":"spilbraet","selfLink":"/apis/image.openshift.io/v1/namespaces/spilbraet/imagestreams/fafnir-sso","uid":"632e9036-c413-11e9-8dc6-1ec7681e0568","resourceVersion":"8195714","generation":1,"creationTimestamp":"2019-08-21T12:58:35Z"},"spec":{"lookupPolicy":{"local":false}},"status":{"dockerImageRepository":"docker-registry.default.svc:5000/spilbraet/fafnir-sso"}}
I0821 14:59:00.760311   35344 request.go:897] Request Body: {"kind":"ImageStreamImport","apiVersion":"image.openshift.io/v1","metadata":{"name":"fafnir-sso","namespace":"spilbraet","resourceVersion":"8195714","creationTimestamp":null},"spec":{"import":true,"images":[{"from":{"kind":"DockerImage","name":"registry.aperta.dk:5000/spilbraet/fafnir-sso:1.0.84"},"to":{"name":"latest"},"importPolicy":{},"referencePolicy":{"type":""}}]},"status":{}}
I0821 14:59:00.764283   35344 round_trippers.go:386] curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: oc/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0" 'https://aptacmaster01.aperta.lan:8443/apis/image.openshift.io/v1/namespaces/spilbraet/imagestreamimports'
I0821 14:59:00.994152   35344 round_trippers.go:405] POST https://aptacmaster01.aperta.lan:8443/apis/image.openshift.io/v1/namespaces/spilbraet/imagestreamimports 201 Created in 228 milliseconds
I0821 14:59:00.994267   35344 round_trippers.go:411] Response Headers:
I0821 14:59:00.994284   35344 round_trippers.go:414]     Cache-Control: no-store
I0821 14:59:00.994297   35344 round_trippers.go:414]     Content-Type: application/json
I0821 14:59:00.994309   35344 round_trippers.go:414]     Content-Length: 1674
I0821 14:59:00.994322   35344 round_trippers.go:414]     Date: Wed, 21 Aug 2019 12:59:00 GMT
I0821 14:59:00.995801   35344 request.go:897] Response Body: {"kind":"ImageStreamImport","apiVersion":"image.openshift.io/v1","metadata":{"name":"fafnir-sso","namespace":"spilbraet","selfLink":"/apis/image.openshift.io/v1/namespaces/spilbraet/imagestreamimports/fafnir-sso","uid":"7202f026-c413-11e9-8dc6-1ec7681e0568","resourceVersion":"8195714","creationTimestamp":"2019-08-21T12:59:00Z"},"spec":{"import":true,"images":[{"from":{"kind":"DockerImage","name":"registry.aperta.dk:5000/spilbraet/fafnir-sso:1.0.84"},"to":{"name":"latest"},"importPolicy":{},"referencePolicy":{"type":"Source"}}]},"status":{"import":{"metadata":{"name":"fafnir-sso","namespace":"spilbraet","uid":"632e9036-c413-11e9-8dc6-1ec7681e0568","resourceVersion":"8195768","generation":2,"creationTimestamp":"2019-08-21T12:58:35Z","annotations":{"openshift.io/image.dockerRepositoryCheck":"2019-08-21T12:59:00Z"}},"spec":{"lookupPolicy":{"local":false},"tags":[{"name":"latest","annotations":null,"from":{"kind":"DockerImage","name":"registry.aperta.dk:5000/spilbraet/fafnir-sso:1.0.84"},"generation":2,"importPolicy":{},"referencePolicy":{"type":"Source"}}]},"status":{"dockerImageRepository":"docker-registry.default.svc:5000/spilbraet/fafnir-sso","tags":[{"tag":"latest","items":null,"conditions":[{"type":"ImportSuccess","status":"False","lastTransitionTime":"2019-08-21T12:59:00Z","reason":"Unauthorized","message":"you may not have access to the Docker image \"registry.aperta.dk:5000/spilbraet/fafnir-sso:1.0.84\"","generation":2}]}]}},"images":[{"status":{"metadata":{},"status":"Failure","message":"you may not have access to the Docker image \"registry.aperta.dk:5000/spilbraet/fafnir-sso:1.0.84\"","reason":"Unauthorized","code":401},"tag":"1.0.84"}]}}
error: tag 1.0.84 failed: you may not have access to the Docker image "registry.aperta.dk:5000/spilbraet/fafnir-sso:1.0.84"
imagestream.image.openshift.io/fafnir-sso imported with errors

Name:                   fafnir-sso
Namespace:              spilbraet
Created:                26 seconds ago
Labels:                 <none>
Annotations:            openshift.io/image.dockerRepositoryCheck=2019-08-21T12:59:00Z
Docker Pull Spec:       docker-registry.default.svc:5000/spilbraet/fafnir-sso
Image Lookup:           local=false
Unique Images:          0
Tags:                   1

latest
  tagged from registry.aperta.dk:5000/spilbraet/fafnir-sso:1.0.84

  ! error: Import failed (Unauthorized): you may not have access to the Docker image "registry.aperta.dk:5000/spilbraet/fafnir-sso:1.0.84"
      1 second ago
`

##### Version
`
[root@aptacmaster01 spilbraetv1]# oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://aptacmaster01.aperta.lan:8443
openshift v3.11.0+d72920c-223
kubernetes v1.11.0+d4cacc0
`

##### Current Result
Imagestream fails
##### Expected Result
Imagestream was created

**Comment by amalic** [comment]
I had similar issues. Was in the end a misconfigured MTU setting in the router node. I recommend checking the network troubleshoting guide from openshift.
