### ISSUE TITLE
Following instructions in the Resource Quota topic: "error: no objects passed to create"

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2366]
Following instructions here, I see a "no objects passed to create" error.

http://docs.openshift.org/latest/dev_guide/quota.html

```
➜  OpenShift  cat resource-quota.json
{
  "apiVersion": "v1beta3",
  "kind": "ResourceQuota",
  "metadata": {
    "name": "quota",
  },
  "spec": {
    "hard": {
      "memory": "1Gi",
      "cpu": "20",
      "pods": "10",
      "services": "5",
      "replicationcontrollers":"5",
      "resourcequotas":"1",
    },
  }
}
➜  OpenShift  osc create -f resource-quota.json
error: no objects passed to create
```

**Comment by ncdc** [comment]
@spadgett not sure if this is the issue, but there are extraneous trailing commas that need to be removed.

**Comment by spadgett** [comment]
@ncdc That was the issue. Thanks.

`osc create` should tell you it's invalid JSON. The doc also has those trailing commas.

**Comment by derekwaynecarr** [comment]
Trailing commas used to be OK when we had different conversion logic in Kubernetes.

I wonder how many other examples in our docs have trailing commas.

**Comment by derekwaynecarr** [comment]
The issue is fixed as noted.  I do not have a close button.

**Comment by derekwaynecarr** [comment]
@spadgett - if you agree with the doc fix that was merged, please close this issue ;-)

**Comment by spadgett** [comment]
@derekwaynecarr I was waiting for #2610 although we also have issue #2412, so I'll close.
