### ISSUE TITLE
bad encoding creating certificates

### ISSUE THREAD

**Issue by akostadinov** [openshift/origin#2367]
Looks like openshift is generating certificates with wrong encoding (at least according to firefox 38 and RFC 5280).
I was wondering whether to file the issue against openshift-ansible or here. But it appears to me that the openshift executable is generating the certs so bug should belong to origin. Let me know if I'm wrong.

So the issue is that after following instrucitons from v3 beta3 training, I cannot open the openshift console with firefox 38 getting:
```
 security library: improperly formatted DER-encoded message. (Error code: sec_error_bad_der) 
```

According to [FF docs](https://wiki.mozilla.org/SecurityEngineering/x509Certs), this error means "A certificate is not properly encoded according to ASN.1 (DER) encoding".

Certificate works with `curl` and `chrome`. But not with `midory` and `firefox 38`. But I have no clue as to why it fails.

Filed a bug with mozilla as well so hopefully they can shed some more light:
https://bugzilla.mozilla.org/show_bug.cgi?id=1166514

**Comment by liggitt** [comment]
Fixed in master in https://github.com/openshift/origin/pull/2259

More details in that pull
