### ISSUE TITLE
oc image mirror fails with wincred

### ISSUE THREAD

**Issue by Gladskih** [openshift/origin#23680]
`oc image mirror` on Windows 10 fails to authenticate in Docker registry when credentials are stored in **wincred**.
It logs 

> found valid config.json

 and 

> Found secret to match

but then just `curl -k -v -XGET  '<scope token url>'` without Authorization header!
If credentials saved in config.json explicitely all work correctly.
Looks like the problem could be imported from github.com/docker/distribution/registry/client/auth

##### Version
> oc v3.11.0+f8b6451-269
> kubernetes v1.11.0+d4cacc0
> features: Basic-Auth SSPI Kerberos SPNEGO

##### Steps To Reproduce

1. docker login... (source)
2. docker login... (destination)
3. oc image mirror...

##### Current Result

> unauthorized: authentication required

##### Expected Result

> Mirroring completed

**Comment by cdjohnson** [comment]
It appears that `oc image mirror` doesn't support the Mac osx keychain credential store either.

A workaround is to do the following:
1.  Edit the `~/.docker/config.json` file
2.  Remove the line with `credStore`

This will force docker to store the credentials directly in the `config.json` file which is NOT secure.
