### ISSUE TITLE
Expose TCP/IP (No HTTP/s) services

### ISSUE THREAD

**Issue by jxadro** [openshift/origin#23699]
Hi

How can be a service that does not use HTTP/s be exposed in OKD 3.11?

I think routes only support HTTP/s traffic.

I have read about using ExternalIP configuration for services but that makes the operation of the cluster complicated and static compared to routes/ingress.

NodePort is more for development that for production due to the opening of ports in all the nodes, lack of control about port numbers, etc.

For example Nginx-ingress-controller allows it with special configurations: https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

Are there more options with OKD to expose TCP ports?

Thank you.

**Comment by reavessm** [comment]
Bump.  I'd love to be able to use RTMP in my openshift but currently only limited to HTTP
