### ISSUE TITLE
Openshift v3.11 :: pod fails and restarts frequently - CrashLoopBackOff - Back-off restarting failed container

### ISSUE THREAD

**Issue by shneha** [openshift/origin#23729]
Created one pod using Docker image, which contains simple Hello World! JAVA code.

I analysed logs for pod but it gives no error, all log data is as expected for a successfully running app. 
Log showing Hello World! - as expected.

Events for reference -

Events:
  Type     Reason     Age               From                                   Message
  ----     ------     ----              ----                                   -------
  Normal   Scheduled  9m                default-scheduler                      Successfully assigned javatest/hello-v2-1-fjchl to csswn001d.openshift.smart.ph
  Normal   Created    46s (x4 over 1m)  kubelet, csswn001d.openshift.smart.ph  Created container
  Normal   Started    46s (x4 over 1m)  kubelet, csswn001d.openshift.smart.ph  Started container
  Warning  BackOff    15s (x7 over 1m)  kubelet, csswn001d.openshift.smart.ph  Back-off restarting failed container
  Normal   Pulled     1s (x5 over 1m)   kubelet, csswn001d.openshift.smart.ph  Container image "10.110.25.141:8082/hello:SNAPSHOT-1.0" already present on machine

Please assist what is the issue here, how can I run this code as daemon.

**Comment by toubib** [comment]
If your program exits, your pod will be on failure state.
If you want a daemon you can run a webserver who print Hello World! as a response of http requests.

**Comment by shneha** [comment]
Thanks for the reply!
Will create a web service and try to deploy,
