### ISSUE TITLE
How to access default image registry in OpenShift 4.1

### ISSUE THREAD

**Issue by Piping** [openshift/origin#23721]
How can I use `podman` to login the openshift default registry in 4.1?

I have read through the documentation and cannot find any useful information that 
1) get server address either with dns name or ip address for the image registry
2) cannot use docker/podman command to login the registry and push the image/container.

The current install is default installtion with 3 mater and 4 nodes.
And current registry persistent volume is set to emptyDir.

##### Version
```
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.8-201907241243+785687c-dirty", GitCommit:"785687c", GitTreeState:"dirty", BuildDate:"2019-07-24T19:44:04Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+4b86cc5", GitCommit:"4b86cc5", GitTreeState:"clean", BuildDate:"2019-07-24T19:42:25Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
```

##### Current Result
```
podman login -u kubeadmin -p $(oc whoami -t) image-registry.openshift-image-registry.svc:5000

Error: error authenticating creds for "image-registry.openshift-image-registry.svc:5000": pinging docker registry returned: Get https://image-registry.openshift-image-registry.svc:5000/v2/: dial tcp: lookup image-registry.openshift-image-registry.svc on 127.0.0.1:53: no such host
```
##### Additional Information
```
oc adm diagnostics
error: unknown command "diagnostics"
See 'oc adm -h' for help and examples.
```

**Comment by adambkaplan** [comment]
fyi @openshift/openshift-team-developer-experience

**Comment by Piping** [comment]
Question is answered here: 
https://github.com/openshift/origin/issues/16097#issuecomment-527774854
