### ISSUE TITLE
Feature request: support for Jenkins scheduled pipeline trigger

### ISSUE THREAD

**Issue by bendehaan** [openshift/origin#23732]
In similar fashion to the Jenkins scheduled pipeline, I would like to be able to automatically periodically trigger an OpenShift pipeline according to a cron(-like) specification. 

The use case is for a security pipeline: long-running security jobs should not disrupt the regular build pipeline, and new security findings could arise in code that hasn't been touched for a while. A solution is to run the security pipeline periodically.

Note that we use ephemeral Jenkins, so configuring it there or through the Jenkinsfile wouldn't work.

The current workaround is to create an OpenShift 'cron job' that triggers the pipeline (`oc start-build security-pipeline`). However, doing this incurs the overhead of creating another image, while ideally it'd be configured in the regular buildconfig within the `jenkinsPipelineStrategy`.

If it's possible some other way, input is very welcome!

**Comment by waveywaves** [comment]
@bendehaan It would make more sense if you could reopen this issue in https://github.com/openshift/jenkins-sync-plugin and close this on as this is not the right place. We can continue the discussion there.

**Comment by bendehaan** [comment]
@waveywaves thanks! We can continue here: https://github.com/openshift/jenkins-sync-plugin/issues/336
