### ISSUE TITLE
Cloning "https://github.com/openshift/cakephp-ex.git " ... error: fatal: unable to access 'https://github.com/openshift/cakephp-ex.git/':  Could not resolve host: github.com; Unknown error

### ISSUE THREAD

**Issue by alokmajumder** [openshift/origin#23787]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by alokmajumder** [comment]
description: When trying to build a php application using git link getting the following error.

version:
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0

Steps To Reproduce
1. click php catalog.
2. put git link https://github.com/openshift/cakephp-ex.git
3. build

**Comment by m86194** [comment]
If you create a pod in your cluster and `oc rsh` to it, can you then access the outside world or do you need to use a https proxy to do so?

**Comment by alokmajumder** [comment]
Hi, I ran my oc as
oc cluster up --http-proxy

oc cluster up --http-proxy=proxy.host --https-proxy=proxy.host

after that I created a demo app using php which gives the error at the time for build. Document attached with screenshot


![Screenshot from 2019-09-16 15-46-40](https://user-images.githubusercontent.com/49674329/64963875-407ce180-d89a-11e9-852f-aed0359601fc.png)
![Screenshot from 2019-09-16 15-49-20](https://user-images.githubusercontent.com/49674329/64963885-4246a500-d89a-11e9-85d4-a54fe056a91f.png)

**Comment by adambkaplan** [comment]
@alokmajumder can you update the BuildConfig YAML to set the log level to 6? This turns on verbose logs so we can (hopefully) see the proxy connect info.

```
spec:
  strategy:
    sourceStrategy: 
      env:
      - name: BUILD_LOGLEVEL
        value: "6"
```
