### ISSUE TITLE
Improvements for Vagrant scripts

### ISSUE THREAD

**Issue by rcernich** [openshift/origin#2382]
Sorry for not simply providing a patch, but I don't have a working Vagrant setup to test with.  These suggestions come from manually setting up an OS instance with libvirt/kvm and our user experience of the last couple of months:
- docker.service should be added to After clause for openshift-node.service
- --dns-ip should be added to create-node-config command (and maybe --volume-dir too)
- sdn script should use DOCKER_NETWORK_OPTIONS instead of OPTIONS.  This would feel more natural, especially since sdn is setting network options for docker
- We've seen issues with file permissions on master, specifically accessing etcd in /vagrant.  It may be helpful to move master config out of the /vagrant folder.
- The registry should have a static service ip (like kubernetes) to prevent it from changing between restarts.
- I'm not entirely sure how the router should work, but pinning it to a specific minion would make things a bit easier from a development perspective as the ip for routes remains static (I update my /etc/hosts file with my route hostnames; if the ip changes, e.g. if the cluster is restarted, then I also need to update my hosts file).

Obviously, those last two apply to a general environment, outside of Vagrant.

Feel free to split this up into multple issues to address specific items in the list.

**Comment by smarterclayton** [comment]
Closing due to age.  Most of these have been addressed by oc cluster up which is easier.
