### ISSUE TITLE
OC Cluster never goes up Error: timed out waiting for the condition

### ISSUE THREAD

**Issue by stramzik** [openshift/origin#23840]
HI All,

When ever i try to get the cluster up using "oc cluster up"
Below is the error I get
```
[mano@mano ~]$ oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I0923 13:40:32.364326   15396 config.go:40] Running "create-master-config"
I0923 13:40:59.938492   15396 config.go:46] Running "create-node-config"
I0923 13:41:10.721711   15396 flags.go:30] Running "create-kubelet-flags"
I0923 13:41:18.241285   15396 run_kubelet.go:49] Running "start-kubelet"
I0923 13:41:23.016238   15396 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E0923 13:46:23.023479   15396 run_self_hosted.go:571] API server error: Get https://127.0.0.1:8443/healthz?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused ()
Error: timed out waiting for the condition
```
Found few article but cant find a solution please guide me if there is a solution for the issue

##### Version
OC version
```
[mano@mano` ~]$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Additional Information
```[mano@mano ~]$ oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
[Note] No client configuration specified; skipping client and cluster diagnostics.

ERROR: [CED3001 from controller openshift/origin/pkg/oc/cli/admin/diagnostics/util/util.go]
       Encountered fatal error while building diagnostics: Requested diagnostic(s) skipped; nothing to run. See --help and consider setting flags or providing config to enable running.
       
[Note] Summary of diagnostics execution (version v3.11.0+0cbc58b):
[Note] Errors seen: 1
[mano@mano ~]$ 
```

**Comment by rniksch** [comment]
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Seeing same issue on centos 7

**Comment by fabstao** [comment]
Same issue here with CentOS 7:

``` 
$ oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I1122 17:54:53.356491    5764 flags.go:30] Running "create-kubelet-flags"
I1122 17:54:55.397093    5764 run_kubelet.go:49] Running "start-kubelet"
I1122 17:54:56.397439    5764 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E1122 17:59:56.402642    5764 run_self_hosted.go:571] API server error: Get https://127.0.0.1:8443/healthz?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused ()
Error: timed out waiting for the condition

$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux oshiftm1.novalocal 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


```

**Comment by paoloromagnoli** [comment]
Having the same issue with centos 7. Can anyone help?

oc cluster up --http-proxy=<myproxy>:3128 --public-hostname=<myip> --base-dir=/tmp/okdconf
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Pulling image openshift/origin-control-plane:v3.11
E0212 14:36:07.054882   15780 helper.go:179] Reading docker config from /home/okd/.docker/config.json failed: open /home/okd/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-control-plane:v3.11 anonymously
Pulled 3/5 layers, 72% complete
Pulled 4/5 layers, 84% complete
Pulled 5/5 layers, 100% complete
Extracting
Image pull complete
Pulling image openshift/origin-cli:v3.11
E0212 14:36:24.017758   15780 helper.go:179] Reading docker config from /home/okd/.docker/config.json failed: open /home/okd/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11 anonymously
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP <myip> as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I0212 14:36:33.812760   15780 config.go:40] Running "create-master-config"
I0212 14:36:37.223182   15780 config.go:46] Running "create-node-config"
I0212 14:36:39.941180   15780 flags.go:30] Running "create-kubelet-flags"
I0212 14:36:41.172245   15780 run_kubelet.go:49] Running "start-kubelet"
I0212 14:36:41.589179   15780 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E0212 14:43:15.596483   15780 run_self_hosted.go:571] API server error: Get https://<myip>:8443/healthz?timeout=32s: context deadline exceeded (Client.Timeout exceeded while awaiting headers) ()
Error: timed out waiting for the condition


oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

uname -a
Linux okd.corp.local 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nilesh303** [comment]
any solution for this ?
