### ISSUE TITLE
new-app from our sample template fails 

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2390]
```
$ osc new-app examples/sample-app/application-template-stibuild.json
image repositories must be of the form [<namespace>/]<name>[:<tag>|@<digest>]
```

1. It shouldn't fail
2. The message is insufficient - looks like it's failing to find the referenced image (which we don't care about)
3. It's probably failing to round trip the image stream correctly
4. It's possible the changes @kargakis made to creating image streams is also breaking
5. It should be prefixed with "error: " because that's how our errors are supposed to be handled by cmdutil.CheckErr

@fabianofranz @csrwng

**Comment by smarterclayton** [comment]
```
$ osc process -f examples/sample-app/application-template-stibuild.json | osc create -f -
```
works as expected

**Comment by smarterclayton** [comment]
We need to add this test to hack/test-cmd as well.

**Comment by fabianofranz** [comment]
It was working when `new-app <template` was initially merged, but only from stored templates referred by name. That seems to be broken as well.

**Comment by smarterclayton** [comment]
Actually, I don't even think this scenario should work, but the error needs to be either "use -f to pass a template to this command" or "you can't use a filesystem template to create apps.

**Comment by csrwng** [comment]
@smarterclayton - unless we do some extra magical checking, we can't tell that this is not a valid image repo, until we try to resolve it, which is much later in the process. We could check beforehand to see if the argument corresponds to an existing file, but even if there is a file named "foo/bar/baz", you really may mean to use image "foo/bar/baz". 

Would you be ok with us checking if there's an existing file corresponding to your argument...tell you that you must use osc -f with the file, and if it's really an image repo to specify --docker-image or --image?

**Comment by smarterclayton** [comment]
> On May 22, 2015, at 1:33 PM, Cesar Wong <notifications@github.com> wrote:
> 
> @smarterclayton - unless we do some extra magical checking, we can't tell that this is not a valid image repo, until we try to resolve it, which is much later in the process. We could check beforehand to see if the argument corresponds to an existing file, but even if there is a file named "foo/bar/baz", you really may mean to use image "foo/bar/baz".
> 
> Would you be ok with us checking if there's an existing file corresponding to your argument...tell you that you must use osc -f with the file, and if it's really an image repo to specify --docker-image or --image?
> 
Yes.  "You must provide an unambiguous argument", and support -f for templates or configs.

**Comment by thesteve0** [comment]
The new-app command is abigious on this. I tried the --template and pointed to a local file and it barfs. Not what I expected. please make sure everything can be executed based on local files

**Comment by smarterclayton** [comment]
Did you pass -f?

**Comment by csrwng** [comment]
new-app doesn't handle local files for templates. That fix is in my PR for this issue (along with other fixes) which should be in on Monday. It will work with the --file or -f param.

**Comment by thesteve0** [comment]
Then why is that the first example in the help? Please document properly in
new-app

**Comment by mfojtik** [comment]
this works because I changed it to be in the suggested format (see my
migration PR)
