### ISSUE TITLE
problems building openshift

### ISSUE THREAD

**Issue by brutif** [openshift/origin#23956]
I'm trying to build from source on RHEL as described here:

https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc

export BUILD_LOGLEVEL=5
hack/env hack/build-base-images.sh

produces:
```
[openshift/origin-source] open /go/src/github.com/openshift/origin/images/source/Dockerfile: no such file or directory
[WARNING] Retrying image build for openshift/origin-source:latest, attempt 1...
[openshift/origin-source] open /go/src/github.com/openshift/origin/images/source/Dockerfile: no such file or directory
[ERROR] hack/build-base-images.sh:56: `return "${result}"` exited with status 1.
[ERROR] hack/lib/build/environment.sh:170: `return "${exitcode}"` exited with status 1.
```

I got similar results on a Mac.  Adding a few echo statements to image.sh shows the "no such file" message is coming from imagebuilder, but I'm not sure how to fix this so the file is available.  Any help is appreciated. 
```
[openshift/origin-source] *** call imagebuilder now
[openshift/origin-source] open /go/src/github.com/openshift/origin/images/source/Dockerfile: no such file or directory
[openshift/origin-source] *** imagebuilder returned

```

**Comment by yeuleh** [comment]
I met the same problem while following the contributing document on the branch release-4.2 and release-4.3

**Comment by yeuleh** [comment]
The file `/go/src/github.com/openshift/origin/images/source/Dockerfile` is removed in commit 7aedc3cb19c39e22b382eff96380bef245f92352. Message in this commit may help.

**Comment by cgruver** [comment]
The HACKING.md and CONTRIBUTING.md files don't appear to have been updated for building the 4.X family of Openshift.  The instructions are still relevant to the 3.X family.

If anyone has insight into how to build the OKD 4.X components, I would love to get access to those instructions.
