### ISSUE TITLE
Latest CRC Installer does fails to run

### ISSUE THREAD

**Issue by ajaysimha** [openshift/origin#23985]
[provide a description of the issue]
When I start CRC I get an error "Error getting bundle metadata: xz: data is truncated or corrupt"
##### Version
[asimha@asimha-fedora crc-linux-1.0.0-rc.0-amd64]$ crc version
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831 (embedded in binary)

##### Steps To Reproduce
Download and install CRC on Fedora 30.
Download pull-secret.txt

both downloads from https://cloud.redhat.com/openshift/install/crc/installer-provisioned

After that:
- run crc setup
- run crc start -p pull-secret.txt
##### Current Result
[asimha@asimha-fedora crc-linux-1.0.0-rc.0-amd64]$ crc start -p pull-secret.txt 
INFO Checking if running as non-root              
INFO Checking if oc binary is cached              
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if libvirt is enabled               
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists 
INFO Extracting bundle: crc_libvirt_4.2.0-0.nightly-2019-09-26-192831.crcbundle ... 
ERRO Error occurred: Error getting bundle metadata: xz: data is truncated or corrupt 

##### Expected Result
Complete crc start without errors and be ready to execute crc oc-env command
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by praveenkumar** [comment]
@ajaysimha did you verified the sha256sum of the downloaded binary, this looks like you have corrupted binary. sha256sum available https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/sha256sum.txt here.

**Comment by praveenkumar** [comment]
@ajaysimha Also this is `crc` issue not the `openshift/orgin` one so better to create it https://github.com/code-ready/crc/issues
