### ISSUE TITLE
Show `none` when no container statuses

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2400]
In the details sidebar, we show an empty section rather than showing the message `none`.

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7735782/6c6303a8-ff0d-11e4-88d2-c1786e4163a9.png)

**Comment by liggitt** [comment]
could just hide the section...

**Comment by spadgett** [comment]
If we hide the section, we should probably do the same in other places. For instance,

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7750141/88a6a766-ffa0-11e4-9dd9-2145074e97f0.png)
