### ISSUE TITLE
Deployment pods are showing up in web console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2401]
Possibly a side effect of #2227?

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7736166/0545b56e-ff10-11e4-9280-55cc51d854b3.png)

```
Annotations

openshift.io/deployment.name
database-1
```

Looks like we're still keying on...

```
        if (pod.metadata.annotations.deployment) {
          return false;
        }
```

/cc @liggitt

**Comment by liggitt** [comment]
will fix
