### ISSUE TITLE
Can't see long annotation names in details sidebar

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2403]
The annotation names are aggressively elided. There's enough room to show more. Notice the empty whitespace in the screenshot.

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7736270/a5dcfbf4-ff10-11e4-83c7-4aa85e6d021a.png)

Hovering your mouse over the value does show the full name, at least on Chrome.

**Comment by spadgett** [comment]
Different to see what's what with namespaces.

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7756908/5c41be32-ffcc-11e4-86dd-7c59870baede.png)

**Comment by sg00dwin** [comment]
Fix merged - Annotations name is now given more space to lessen the amount that could be hidden ...

narrow
![screen shot 2015-06-09 at 2 01 47 pm](https://cloud.githubusercontent.com/assets/1874151/8065647/b84e4892-0eb0-11e5-8acd-f80b4fec8309.png)

wide
![screen shot 2015-06-09 at 2 02 04 pm](https://cloud.githubusercontent.com/assets/1874151/8065648/bdafd06c-0eb0-11e5-83c9-7ea4cc5772fd.png)
