### ISSUE TITLE
Minishift not notarized to run on macOS Catalina

### ISSUE THREAD

**Issue by MaiHameed** [openshift/origin#24035]
The new Mac update Catalina, requires apps to be notarized, and thus the minishift CLI stopped working for me. I tried reinstalling using `brew cask reinstall minishift`, but same error occurred.

![image](https://user-images.githubusercontent.com/26514093/67705523-88a91c80-f98d-11e9-85cc-da9da4b6c5d0.png)

It occurs whenever I try running any minishift command. Is there a temporary workaround for this? I regret updating my Mac since it caused a whole slew of related issues...

**Comment by MaiHameed** [comment]
Nevermind, temporarily disabled gatekeeper using `sudo spctl --master-disable`, everything works fine.

**Comment by PeterHeja** [comment]
This problem still exists.
The above solution is just for running it temporarily, this should be fixed by getting the binary notarized.
