### ISSUE TITLE
[RFE] orchestration / provisioning of external service/endpoint

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2406]
Codifying the information in https://lists.openshift.redhat.com/openshift-archives/dev/2015-February/msg00089.html into an official RFE.

User story:

As a user of OpenShift
I want to be able to
Specify an external service/endpoint (eg: MS SQL DB running on Azure)
Provide credentials (eg: API credentials)
Provision the service using the credentials

This is a real customer use case today with V2 and extends to V3. It would be nice if OpenShift could provide this external service provisioning.

**Comment by pweil-** [comment]
This looks like it will be handled by the service catalog provision and bind functionality (3.6).  Closing
