### ISSUE TITLE
Logout command does not remove the server information

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#2409]
When I do 

osc logout

it removes the auth information but not the server information. There is also no documentation in the 

osc login -h 

that shows how to change the server. 

---------------------

spousty@localhost v05$ ./osc logout
Error from server: the server has asked for the client to provide credentials (get users ~)
spousty@localhost v05$ ./osc login
Username: admin
Authentication required for https://localhost:8443 (openshift)

Password: spousty@localhost v05$ ./osc login --help
Logs in to the OpenShift server and saves a config file that
will be used by subsequent commands.

First-time users of the OpenShift client must run this command to configure the server,
establish a session against it, and save it to a configuration file. The default
configuration will be in your home directory under ".config/openshift/config".

The information required to login, like username and password, a session token, or
the server details, can be provided through flags. If not provided, the command will
prompt for user input as needed.

Options:
  -p, --password='': Password, will prompt if not provided
  -u, --username='': Username, will prompt if not provided
      --certificate-authority='': Path to a cert. file for the certificate authority.
      --insecure-skip-tls-verify=false: If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.

--------------------

**Comment by liggitt** [comment]
`osc logout` is only intended to remove auth info.

Some of the help issues are fixed in master:
```
$ osc login -h
Log in to an OpenShift server and save config for future use

First-time users of the OpenShift client should run this command to connect to a server,
establish an authenticated session, and save connection to the configuration file. The
default configuration will be saved to your home directory under
".config/openshift/config".

The information required to login -- like username and password, a session token, or
the server details -- can be provided through flags. If not provided, the command will
prompt for user input as needed.

Usage: 
  osc login [URL] [options]

Examples:
  // Log in interactively
  $ osc login

  // Log in to the given server with the given certificate authority file
  $ osc login localhost:8443 --certificate-authority=/path/to/cert.crt

  // Log in to the given server with the given credentials (will not prompt interactively)
  $ osc login localhost:8443 --username=myuser --password=mypass

Options:
  -p, --password='': Password, will prompt if not provided
  -u, --username='': Username, will prompt if not provided
      --certificate-authority='': Path to a cert. file for the certificate authority.
      --insecure-skip-tls-verify=false: If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.
```

**Comment by thesteve0** [comment]
So then how can I change the server once I have set oe?

**Comment by liggitt** [comment]
`osc login https://new-server.com`
or
`osc login --server=https://new-server.com`

**Comment by thesteve0** [comment]
Those didn't work with 0.5

**Comment by fabianofranz** [comment]
@thesteve0 Is this issue still valid? If so can you specify what's happening when using `osc login <server>` to switch between servers?

**Comment by fabianofranz** [comment]
Fixed in master.
