### ISSUE TITLE
osc create doesn't announce parse failures

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#2412]
```
$ osc create -f pv.json                                                                                                                                                                
error: no objects passed to create
$ osc create -f pv.json --loglevel=4                                                                                                                                                   
I0521 15:04:27.107644    2153 visitor.go:223] Unable to load file "pv.json": unable to get type info from "pv.json": couldn't get version/kind; json parse error: invalid character '\n' in string literal
F0521 15:04:27.107704    2153 create.go:51] error: no objects passed to create
```

I would like to find out that there was a parsing error (I left out a comma) without having to crank up the loglevel.

**Comment by spadgett** [comment]
See also #2366

**Comment by fabianofranz** [comment]
The `create` command is [configured to run](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/create.go#L83) as `ContinueOnError` upstream, which allows it to ignore entries that are not recognized as API objects, and continue to process valid entries after failures.

So requires a change of behavior upstream. Another option would be to always run `create` with a higher log level by default ("2" would be enough for parse failures).
