### ISSUE TITLE
Ordinary user can't create or even list PersistentVolumeClaims

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#2413]
@deads2k or @liggitt I *think* this is probably just a matter of adding PVCs to the default policy for things project admins/editors/viewers should have access to?

```
$ osc login -u bob
Authentication required for https://10.179.135.126:8443 (openshift)
Password: 
Login successful.

Using project "whatever".

$ cat pvc.json
{
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "metadata": {
        "name": "claim1"
    },
    "spec": {
        "accessModes": [ "ReadWriteOnce" ],
        "resources": {
            "requests": {
                "storage": "5Gi"
            }
        }
    }
}

$ osc create -f pvc.json 
Error from server: "/api/v1/namespaces/whatever/persistentvolumeclaims" is forbidden because bob cannot create on persistentvolumeclaims in whatever
```

**Comment by sosiouxme** [comment]
```
$ osc get pv
Error from server: "/api/v1beta3/persistentvolumes" is forbidden because bob cannot list on persistentvolumes in 
```

I'm... honestly not sure if ordinary users ought to be allowed to see the backing volumes. I don't think there's a need for it unless the PVs have some user-required information that's not expressed by the claim.

**Comment by liggitt** [comment]
@markturansky what is the expected level of access for users to persistent volumes and persistent volume claims?

**Comment by sosiouxme** [comment]
It occurred to me, actually, creating these might be something we don't want to allow by default (let the user change that policy).

However, if a cluster administrator creates one in your namespace, it seems reasonable for an ordinary user of that project to be able to list it. I don't think you could even create a pod to use a volume claim otherwise.

**Comment by markturansky** [comment]
PersistentVolumes are expected to be provisioned by an administrator without any namespace.

PersistentVolumeClaims will be created by users within a namespace.

**Comment by liggitt** [comment]
@markturansky can you add the correct permissions to the `admin` (and `edit`) roles in `GetBootstrapClusterRoles`? Might be as simple as adding "persistentvolumeclaims" to the `KubeExposedGroupName` list in the `GroupsToResources` map. @deads2k can probably give guidance there.

**Comment by markturansky** [comment]
@liggitt will do.

**Comment by sosiouxme** [comment]
I think the `view` role ought to see PVCs too.

**Comment by markturansky** [comment]
Thanks to @deads2k for his guidance.  See https://github.com/openshift/origin/pull/2445

**Comment by markturansky** [comment]
@sosiouxme can this issue be closed?

**Comment by sosiouxme** [comment]
Yes, looks good. Thanks!
