### ISSUE TITLE
Developer UI Add From Git complains about invalid URL

### ISSUE THREAD

**Issue by jarielpa** [openshift/origin#24156]
UI Git Repo URL accepts only http or https urls without port number.
Even ssh://git@git.p... is not accepted

##### Version
Client Version: v4.2.5
Server Version: 4.2.2
Kubernetes Version: v1.14.6+868bc38

##### Steps To Reproduce
1. Add+ -> From Git,  Add value to GIt Repo URL form field
2. add any git http(s) that has port number
3. add any ssh git url

**Comment by ybrock** [comment]
I confirm,
if you try to add a Git Repo URL with either : a port number (:port) or a user  (gituser@server), Openshift complains about the validity of the URL with "Invalid Git URL".

To be able to use our internal Bitbucket server with Openshift, I need to be able to use URL like this : 

ssh://git@git.domain.net:7999/dci/docker-sftp.git
https://git.domain.net:8443/scm/dci/docker-sftp.git
