### ISSUE TITLE
Angular expression visible in deployment config warning tooltip

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2415]
See screenshot.

![screen_shot_2015-05-21_at_12_56_19_pm](https://cloud.githubusercontent.com/assets/1167259/7754221/e6f7cc38-ffb8-11e4-9150-e2ba23464e95.png)

/cc @liggitt

**Comment by spadgett** [comment]
I've seen problems using Angular expressions inside of `title` attributes with Bootstrap tooltips. Might be easiest just to leave the ID out of the message, particularly if it doesn't exist anymore anyway.

**Comment by liggitt** [comment]
might be related to #2411

**Comment by liggitt** [comment]
feel free to remove the id, but I question whether we even want to show the warning if it's missing. @smarterclayton, I got the impression that deleting a deployment config was likely to delete all the deployments spawned from it... if so, not sure we need to worry about the "deployment config doesn't exist any more" case

**Comment by smarterclayton** [comment]
You can bypass it, so they could be left behind.  They're still deployments, just orphaned.

----- Original Message -----
