### ISSUE TITLE
osc first class support for a terminal

### ISSUE THREAD

**Issue by johnkeck** [openshift/origin#2417]
Would be nice if instead of 
    osc exec -p PODID -c CONTAINER -i -t -- bash -il

you could do something like
    osc terminal -p PODID -c CONTAINER

and the terminal command would attempt to use a list of shells in the container and automatically setup terminal features.

**Comment by smarterclayton** [comment]
Fixed.

**Comment by smarterclayton** [comment]
`oc rsh`
