### ISSUE TITLE
Is 3.11 the last version of Origin/OKD ?

### ISSUE THREAD

**Issue by freeeflyer** [openshift/origin#24170]
Openshift commercial continues to be regularly updated, but Origin/OKD stays stuck to the 3.11 version since more that one year.
I know it's a community based product, so I'm not blaming anyone, I'm just asking for infos.
Will there be a release 4.x and so on ?

**Comment by JaroslavMajera** [comment]
It's not the last version of OKD. I don't know if its officially released/annouced but there is a first preview of 4.3 in https://github.com/openshift/okd.

**Comment by jomeier** [comment]
Some of the core binaries of OKD v3.11 still are built through Openshift‘s CI and can be found online if you know where. But its nothing „official“. The RPMs are neither signed nor published in the Repos. 

Some Docker images are up to two years old. You must patch them with „yum update“ to get them through the security scanner. Some images are built every hour.

I wish there would be an intermediate version available. Maybe some v3..11.1 gets released before OKD4 comes out.

But as @freeeflyer said: it‘s a community project and we can be glad that there are people which take care about it so we can use this great software for free.

**Comment by mmacfadden** [comment]
What's the relationship between this repo and the new OKD repo?
