### ISSUE TITLE
openshift router metrics are gauge but counter

### ISSUE THREAD

**Issue by jixuju** [openshift/origin#24179]
When using openshift version 3.9, relevant metrics are normal, but after upgrading to 3.11, we found that some metrics information is growing, which looks like counter, however, in the notes, the type is guage, for example：
```
# TYPE haproxy_server_connections_total gauge
haproxy_server_connections_total{namespace="",pod="",route="",server="fe_no_sni",service=""} 497831
haproxy_server_connections_total{namespace="",pod="",route="",server="fe_sni",service=""} 1.318495e+06

# TYPE haproxy_server_current_sessions gauge
haproxy_server_current_sessions{namespace="",pod="",route="",server="fe_no_sni",service=""} 439
haproxy_server_current_sessions{namespace="",pod="",route="",server="fe_sni",service=""} 8710

# TYPE haproxy_server_http_average_response_latency_milliseconds gauge
haproxy_server_http_average_response_latency_milliseconds{namespace="test",pod="superwind-test-1-7nr5f",route="superwind-test-route",server="10.131.0.61:8080",service="superwind-test"} 1308
haproxy_server_http_average_response_latency_milliseconds{namespace="test",pod="superwind-test-1-gwc8l",route="superwind-test-route",server="10.131.0.62:8080",service="superwind-test"} 1434
```
By view the code change, it is found that there is this code in [`[8f0119b]`](https://github.com/openshift/origin/commit/8f0119bdd9c3b679cdfdf2962143435a95e08eae#diff-58216897083787e1c87c90955aabceff):
![image](https://user-images.githubusercontent.com/16171790/69244943-e6bdce00-0be0-11ea-9d4c-a197d5859a96.png)

Is this a problem? 

View the stats information of haproxy in the browser, and there is no cumulative situation, as shown in the following figure:
![image](https://user-images.githubusercontent.com/16171790/69244754-7f078300-0be0-11ea-9853-b478f405f604.png)

##### Version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
openshift v3.11.0+bdd37ad-314

##### Steps To Reproduce
1. get Prometheus format statistics of router
```bash
$ curl <user>:<password>@<router_IP>:<STATS_PORT>
# for example:
$ curl admin:test@10.254.254.35:1936/metrics
```

##### Current Result
`haproxy_server_current_sessions` and `haproxy_server_http_average_response_latency_milliseconds` and so on are growing

##### Expected Result
A, B, etc. show gauge values

**Comment by huang-cn** [comment]
We're experiencing exact same issue in our environment, we're using the metric `haproxy_server_http_average_response_latency_milliseconds`, but it seems the value gradually increasing overtime. 
 in our case, a simple html page which only takes less than 10ms to load, the latency begin with 7ms and now the `haproxy_server_http_average_response_latency_milliseconds` is increasing to 13,000+ ms, the actual latency barely changed. 

we're using the router metric api `http://user:pass@router_ip:1936/metrics`
the env info:
```
openshift v3.11.0+fef6f83-275
kubernetes v1.11.0+d4cacc0
```
I also came across discussion thread [openshift router and its own metrics](http://lists.openshift.redhat.com/openshift-archives/dev/2019-August/msg00010.html) talking about similar `haproxy_server_http_average_response_latency_milliseconds` seems accumulating problem.
