### ISSUE TITLE
oc cli - oc set probe skips query parameters

### ISSUE THREAD

**Issue by bszeti** [openshift/origin#24231]
Trying to set readiness/liveness probe with oc command line:
oc set probe dc/myapp --readiness --get-url='http://:8080/health?param=1&param=2'

Query parameters are ignored.
A workaround is to urlencode '?'. This works:
oc set probe dc/myapp --readiness --get-url='http://:8080/health%3Fparam=1&param=2'

##### Version
Client Version: v4.3.0
Server Version: 4.2.2
Kubernetes Version: v1.14.6+868bc38

##### Steps To Reproduce
1. Have a DeploymentConfig e.g. "myapp"
2. oc set probe dc/myapp --readiness --get-url='http://:8080/health?param=1&param=2'
3. Check readinessProbe: 
  oc get dc myapp -o jsonpath='{.spec.template.spec.containers[0].readinessProbe.httpGet.path}'

##### Current Result
/health

##### Expected Result
/health?param=1&param=2

##### Additional Information
The REST Api request is missing the params already, so the issue is probably in oc cli. Adding '--loglevel 9':
...
Request Body: {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"myapp"}],"containers":[{"name":"myapp","readinessProbe":{"httpGet":{"path":"/health"}}}]}}}}

**Comment by xingxingxia** [comment]
The cause seems to be from "net/url" package per https://github.com/openshift/oc/blob/913a2b5/pkg/cli/set/probe.go#L221-L238 :
```
		url, err := url.Parse(o.HTTPGet)
                ...
			Path:   url.Path,
```
```
See:
$ cat test.go
package main

import ("net/url"; "fmt")
func main() {
  urls := []string{"http://:8080/health?param=1&param=2", "http://:8080/health%3Fparam=1&param=2"}
  for _, u := range urls {
    url, err := url.Parse(u)
    if err != nil {
      fmt.Errorf("could not be parsed as a valid URL: %v", err)
    } else {
      fmt.Println("when url is:", url)
      fmt.Println("  url.Parse(...) gets url.Path:", url.Path)
    }
  }
}

$ go run test.go 
when url is: http://:8080/health?param=1&param=2
  url.Parse() gets url.Path: /health
when url is: http://:8080/health%3Fparam=1&param=2
  url.Parse() gets url.Path: /health?param=1&param=2
```
/assign @soltysh
