### ISSUE TITLE
origin-node service crashing on 3.11 - "failed to run Kubelet: cannot create certificate signing request: Unauthorized"

### ISSUE THREAD

**Issue by benscottub** [openshift/origin#24242]
All of our control plane and worker nodes have suddenly gone into Not Ready state. I believe this is 
 due to an internal certificate expiring and causing the kubelets to shut down on each host. The error message in journalctl (from one of the control plane servers) is as follows:

Dec 01 17:08:42 osm1.acsu.buffalo.edu origin-node[57436]: E1201 17:08:42.224397   57436 bootstrap.go:195] Part of the existing bootstrap client certificate is expired: 2019-06-15 11:22:08 +0000 UTC
Dec 01 17:08:42 osm1.acsu.buffalo.edu origin-node[57436]: I1201 17:08:42.224419   57436 bootstrap.go:56] Using bootstrap kubeconfig to generate TLS client cert, key and kubeconfig file
Dec 01 17:08:42 osm1.acsu.buffalo.edu origin-node[57436]: I1201 17:08:42.225996   57436 certificate_store.go:131] Loading cert/key pair from "/etc/origin/node/certificates/kubelet-client-current.pem".
Dec 01 17:08:42 osm1.acsu.buffalo.edu origin-node[57436]: F1201 17:08:42.266078   57436 server.go:262] failed to run Kubelet: cannot create certificate signing request: Unauthorized
Dec 01 17:08:42 osm1.acsu.buffalo.edu systemd[1]: Unit origin-node.service entered failed state.
Dec 01 17:08:42 osm1.acsu.buffalo.edu systemd[1]: origin-node.service failed.

From looking around online, it seems that some kube token has expired and can no longer register with the cluster, but I don't know how to rectify this in openshift.

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://webapps.buffalo.edu:443
openshift v3.11.0+bcca01e-65
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. Wait for the /etc/origin/node/certificates/kubelet-client-current.pem to expire
2. Observe that the cert rotation process is failing with the above errors

##### Current Result
The nodes are unable to create CSRs for approval. 

##### Expected Result
The nodes are able to create CSRs for approval.

##### Additional Information
We tried running the upgrade openshift-ansible playbook to get on the latest version of 3.11, but the playbook fails because none of the masters or nodes are in a Ready state. Is there a way to upgrade an offline/down cluster? 

We are also seeing a large number of Pending CSR's when running 'oc get csr' as follows:

NAME        AGE       REQUESTOR                           CONDITION
csr-24rlr   21h       system:node:osn4.acsu.buffalo.edu   Pending
csr-25b9b   21h       system:node:osn1.acsu.buffalo.edu   Pending
csr-2cmmj   17h       system:node:osn2.acsu.buffalo.edu   Pending
csr-2jkb2   17h       system:node:osn4.acsu.buffalo.edu   Pending
csr-2m6gj   20h       system:node:osn4.acsu.buffalo.edu   Pending
csr-2pkbm   21h       system:node:osn2.acsu.buffalo.edu   Pending
csr-2wxzk   23h       system:node:osn3.acsu.buffalo.edu   Pending

We have 4 nodes (osn1..4) and there are >250 pending CSRs in this list. There are no pending CSRs from the control plane node services.

**Comment by alexcern** [comment]
Hi, also faced this issue. The solution was to refresh the node bootstrap kubeconfig:

```
mv /etc/origin/node/bootstrap.kubeconfig /etc/origin/node/bootstrap.kubeconfig.bak
cp /etc/origin/master/admin.kubeconfig  /etc/origin/node/bootstrap.kubeconfig
systemctl restart origin-node
```
