### ISSUE TITLE
oc logs not working with label selector (kubectl working)

### ISSUE THREAD

**Issue by guimou** [openshift/origin#24268]
When fetching logs using oc with labels, an error is thrown, whereas it works well with kubctl.

##### Version
oc version 
Client Version: openshift-clients-4.2.2-201910250432
Server Version: 4.2.4
Kubernetes Version: v1.14.6+dc8862c

##### Steps To Reproduce
1. oc logs -l serving.knative.dev/service=logevents -c user-container -n event-display -f => error
2. kubectl logs -l serving.knative.dev/service=logevents -c user-container -n event-display -f => working

##### Current Result
```
oc logs -l serving.knative.dev/service=logevents -c user-container -n event-display -f
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
   '-f rsrc.yaml'
   '--filename=rsrc.json'
   '<resource> <name>'
   '<resource>'
```
with kubectl:
```
kubectl logs -l serving.knative.dev/service=logevents -c user-container -n event-display -f
☁️  cloudevents.Event
Validation: valid
Context Attributes,
  specversion: 0.2
  type: dev.knative.kafka.event
  source: /apis/v1/namespaces/event-display/kafkasources/kafka-source#storage
  id: partition:73/offset:0
  time: 2019-12-09T13:59:19.983Z
  contenttype: application/json
...
```
##### Expected Result
Both commands should work the same.

**Comment by xingxingxia** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1774366
