### ISSUE TITLE
Updating project quota has no effect on project . Based on beta3 training 

### ISSUE THREAD

**Issue by ivanthelad** [openshift/origin#2426]
I’m trying to update the quota after applying  changes to  the config file but it does not take effect (quota.json )

Steps performed, see (1)
1) apply quota.json to a project
2) confirm quota is applied (getting details )
3)update quota.json file. changing replication controllers from 3 to 4 
4) apply using command osc update -f quota.json
	doing osc edit also has no effect
5) view quota for project. quota information has not changed. when view using "osc describe”  command 

Whats interesting is if I execute “osc edit quota test-quota” its shows that the quota specification has taken effect but not applied, see (2). restarting the openshift master has no effect 

Has any body experienced this?  It would seem its taken effect in the “specification” of the quota but the status of the quota has not changed. 
So far the only way i can change quotas is by removing them completely and then applying changes 

Cheers
Ivan

(1) steps performed 
[root@ose3-master beta3]# osc create -f  quota.json
resourcequotas/test-quota
[root@ose3-master beta3]# cd beta3/^C
[root@ose3-master beta3]# osc get quota test-quota
NAME
test-quota
[root@ose3-master beta3]# osc describe  quota test-quota
Name:			test-quota
Resource		Used	Hard
--------		----	----
cpu			0m	200m
memory			0	512Mi
pods			2	3
replicationcontrollers	2	3
resourcequotas		1	1
services		2	3

[root@ose3-master beta3]# vim quota.json
[root@ose3-master beta3]# osc update -f  quota.json
resourcequotas/test-quota
[root@ose3-master beta3]# cat quota.json
{
  "apiVersion": "v1beta3",
  "kind": "ResourceQuota",
  "metadata": {
    "name": "test-quota"
  },
  "spec": {
    "hard": {
      "memory": "512Mi",
      "cpu": "200m",
      "pods": "3",
      "services": "3",
      "replicationcontrollers": "4",
      "resourcequotas": "1"
    }
  }
}
[root@ose3-master beta3]# osc describe  quota test-quota
Name:			test-quota
Resource		Used	Hard
--------		----	----
cpu			0m	200m
memory			0	512Mi
pods			2	3
replicationcontrollers	2	3
resourcequotas		1	1
services		2	3

[root@ose3-master beta3]#

(2)quota edit

[root@ose3-master beta3]# osc create -f  quota.json
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1beta3
kind: ResourceQuota
metadata:
  creationTimestamp: 2015-05-12T13:12:46Z
  name: test-quota
  namespace: quickstart
  resourceVersion: "104739"
  selfLink: /api/v1beta1/resourceQuotas/test-quota?namespace=quickstart
  uid: 94cdfeb0-f8a8-11e4-b6d5-0800279f8e01
spec:
  hard:
    cpu: 200m
    memory: 512Mi
    pods: "3"
    replicationcontrollers: "4"
    resourcequotas: "1"
    services: "3"
status:
  hard:
    cpu: 200m
    memory: 512Mi
    pods: "3"
    replicationcontrollers: "3"
    resourcequotas: "1"
    services: "3"
  used:
    cpu: 0m
    memory: "0"
    pods: "2"
    replicationcontrollers: "2"
    resourcequotas: "1"
    services: "2"

**Comment by derekwaynecarr** [comment]
This is fixed at head but if required I can back port to beta3.

**Comment by ivanthelad** [comment]
not required. 

cheers
ivan

**Comment by derekwaynecarr** [comment]
Since this is fixed at HEAD, are you ok with closing the issue?

Upstream fix was here: 
https://github.com/GoogleCloudPlatform/kubernetes/pull/6935
