### ISSUE TITLE
Port mappings text extends outside service box

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2427]
See screenshot.

![openshift_management_console](https://cloud.githubusercontent.com/assets/1167259/7758243/35ef3db8-ffd6-11e4-8853-1d75e9ac8a40.png)

/cc @liggitt @sg00dwin

**Comment by sg00dwin** [comment]
@spadgett The nowrap class on the span is the issue. If we can put each port mapping their own <span class="nowrap">... that will allow multiple mappings to stack. I assume like this.. http://pastebin.test.redhat.com/286111 ,but I don't have a way to test. If this does wrap each in their own span I can add this to my next pull request.

**Comment by spadgett** [comment]
@sg00dwin Your proposed fix works.

**Comment by danmcp** [comment]
@sg00dwin @spadgett Any update here?

**Comment by spadgett** [comment]
@danmcp PR #2563 from @sg00dwin contains the fix. Still under review.
