### ISSUE TITLE
"osc get deployments" does not list deployments

### ISSUE THREAD

**Issue by adellape** [openshift/origin#2429]
Web console and `osc status`/`osc describe dc <deploymentconfig>` show that I have active deployments, so I expected `osc get deployments` to show the same, however the output is blank:

```
$ osc get deployments
NAME      STATUS    CAUSE
```

More details:

https://gist.github.com/adellape/6e00683f81ebf7723da1

Interested to know whether this is just a bad expectation on my part.

```
$ openshift version
openshift v0.5.2-43-g54cc564
kubernetes v0.17.0-441-g6b6b47a
```

**Comment by ironcladlou** [comment]
The `deployment` resource won't be in v1 final. It has been deprecated for a long time.

Use `rc` to view the deployment as a replication controller instead.

@smarterclayton, do we need to take any special action right now to prepare for removing these old types?

**Comment by smarterclayton** [comment]
Yank them from old and new versions, remove all traces.

**Comment by ironcladlou** [comment]
The deployment resource was removed with https://github.com/openshift/origin/pull/2534, so this issue can be closed.
