### ISSUE TITLE
oc cluster up only working with sudo

### ISSUE THREAD

**Issue by didona** [openshift/origin#24310]
`oc cluster up` does not work without sudo priviledges.

##### Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Run `oc cluster up` as a regular user

##### Current Result
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I1217 09:13:51.490388   26496 flags.go:30] Running "create-kubelet-flags"
I1217 09:13:52.833699   26496 run_kubelet.go:49] Running "start-kubelet"
Error: error creating node config: could not create OpenShift configuration: cannot start container 178c41bf5f55fea04532022f698ba2671e3d3ca82970106415c68d8a3fa93542; caused by: cannot start container 178c41bf5f55fea04532022f698ba2671e3d3ca82970106415c68d8a3fa93542

##### Expected Result
The cluster should be up as if I started it with sudo (as shown below)

Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I1217 09:14:59.120352   27367 flags.go:30] Running "create-kubelet-flags"
I1217 09:15:00.427103   27367 run_kubelet.go:49] Running "start-kubelet"
I1217 09:15:00.789114   27367 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I1217 09:15:16.810368   27367 interface.go:26] Installing "kube-proxy" ...
I1217 09:15:16.810391   27367 interface.go:26] Installing "kube-dns" ...
I1217 09:15:16.810403   27367 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I1217 09:15:16.810413   27367 interface.go:26] Installing "openshift-apiserver" ...
I1217 09:15:16.810440   27367 apply_template.go:81] Installing "kube-proxy"
I1217 09:15:16.810469   27367 apply_template.go:81] Installing "openshift-apiserver"
I1217 09:15:16.810484   27367 apply_template.go:81] Installing "kube-dns"
I1217 09:15:16.810592   27367 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1217 09:15:18.927095   27367 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I1217 09:16:06.976223   27367 run_self_hosted.go:242] openshift-apiserver available
I1217 09:16:06.976271   27367 interface.go:26] Installing "openshift-controller-manager" ...
I1217 09:16:06.976305   27367 apply_template.go:81] Installing "openshift-controller-manager"
I1217 09:16:09.263159   27367 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding registry ...
Adding sample-templates ...
Adding persistent-volumes ...
Adding web-console ...
Adding centos-imagestreams ...
Adding router ...
I1217 09:16:09.283932   27367 interface.go:26] Installing "openshift-image-registry" ...
I1217 09:16:09.283968   27367 interface.go:26] Installing "sample-templates" ...
I1217 09:16:09.283989   27367 interface.go:26] Installing "persistent-volumes" ...
I1217 09:16:09.284012   27367 interface.go:26] Installing "openshift-web-console-operator" ...
I1217 09:16:09.284032   27367 interface.go:26] Installing "centos-imagestreams" ...
I1217 09:16:09.284051   27367 interface.go:26] Installing "openshift-router" ...
I1217 09:16:09.284399   27367 apply_list.go:67] Installing "centos-imagestreams"
I1217 09:16:09.284448   27367 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I1217 09:16:09.284506   27367 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I1217 09:16:09.284529   27367 interface.go:26] Installing "sample-templates/django quickstart" ...
I1217 09:16:09.284550   27367 interface.go:26] Installing "sample-templates/rails quickstart" ...
I1217 09:16:09.284574   27367 interface.go:26] Installing "sample-templates/mariadb" ...
I1217 09:16:09.284596   27367 interface.go:26] Installing "sample-templates/mysql" ...
I1217 09:16:09.284616   27367 interface.go:26] Installing "sample-templates/postgresql" ...
I1217 09:16:09.284636   27367 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I1217 09:16:09.284657   27367 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I1217 09:16:09.284679   27367 interface.go:26] Installing "sample-templates/sample pipeline" ...
I1217 09:16:09.284703   27367 interface.go:26] Installing "sample-templates/mongodb" ...
I1217 09:16:09.284720   27367 apply_list.go:67] Installing "sample-templates/django quickstart"
I1217 09:16:09.284750   27367 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I1217 09:16:09.284752   27367 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I1217 09:16:09.284817   27367 apply_list.go:67] Installing "sample-templates/mongodb"
I1217 09:16:09.284836   27367 apply_list.go:67] Installing "sample-templates/mysql"
I1217 09:16:09.284921   27367 apply_list.go:67] Installing "sample-templates/postgresql"
I1217 09:16:09.285007   27367 apply_template.go:81] Installing "openshift-web-console-operator"
I1217 09:16:09.284989   27367 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I1217 09:16:09.284751   27367 apply_list.go:67] Installing "sample-templates/rails quickstart"
I1217 09:16:09.284802   27367 apply_list.go:67] Installing "sample-templates/mariadb"
I1217 09:16:09.284838   27367 apply_list.go:67] Installing "sample-templates/sample pipeline"
I1217 09:16:09.284873   27367 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I1217 09:16:11.100883   27367 interface.go:41] Finished installing "sample-templates/cakephp quickstart" "sample-templates/dancer quickstart" "sample-templates/django quickstart" "sample-templates/rails quickstart" "sample-templates/mariadb" "sample-templates/mysql" "sample-templates/postgresql" "sample-templates/nodejs quickstart" "sample-templates/jenkins pipeline ephemeral" "sample-templates/sample pipeline" "sample-templates/mongodb"
I1217 09:16:11.542530   27367 interface.go:41] Finished installing "openshift-image-registry" "sample-templates" "persistent-volumes" "openshift-web-console-operator" "centos-imagestreams" "openshift-router"
Server Information ...
OpenShift server started.

The server is accessible via web console at:
    https://127.0.0.1:8443

##### Additional Information
Output of `oc adm diagnostics`

ERROR: [CED3015 from controller openshift/origin/pkg/oc/cli/admin/diagnostics/diagnostics.go]
       Client configuration failed to load; skipping client and cluster diagnostics due to error: No contexts found in config file.
       
ERROR: [CED3001 from controller openshift/origin/pkg/oc/cli/admin/diagnostics/util/util.go]
       Encountered fatal error while building diagnostics: Requested diagnostic(s) skipped; nothing to run. See --help and consider setting flags or providing config to enable running.

**Comment by nandor-poka** [comment]
Does docker in general work for you as normal user? If your user is not in the docker group docker will not work.
