### ISSUE TITLE
osc project resets the current-context

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#2432]
Running OpenShift as pod on Kubernetes:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/openshift-origin

I do the following:

```
[0] $ docker run --privileged --entrypoint="/usr/bin/bash" -it -e="OPENSHIFTCONFIG=/config/admin.kubeconfig" -v ${OPENSHIFT_CONFIG}:/config openshift/origin
[1] $ osc config use-context public-default
[2] $ osc project default
[3] $ osc config view
```

Expected result:
The current namespace for the public-default context should be "default" and the current-context should not change.

Actual result:
The context switches back to default from "public-default", and now osc cant contact the server anymore.

@deads2k - any idea why osc project is switching the current-context?

**Comment by deads2k** [comment]
Yeah.  In `osc project <arg>`, the `arg` is actually **either** a context or a project.  If it matches on context, then that's the match that wins.  In your case, you have a context named "default", so it switched to it.

Address complaints to @smarterclayton.

An issue regarding keys that don't look like the keys we generate from `osc project` and `osc login` would be in order.

**Comment by deads2k** [comment]
Thinking about it, fixing the keys could be a candidate for @stevekuznetsov

**Comment by smarterclayton** [comment]
Should we flip the names?  Are most admins going to be using the internal address or the external address?  Seems like initially they'll use internal then switch to external.

**Comment by deads2k** [comment]
internal is the default.
