### ISSUE TITLE
The build pod was killed due to an out of memory condition.

### ISSUE THREAD

**Issue by lordbentner** [openshift/origin#24342]
Hi , i tried to build a golang github project in the console-openshift-console but it give me 
this error when i click to star build : The build pod was killed due to an out of memory condition.

I tried also to install the client-go github but i have some errors
Thank you

**Comment by adambkaplan** [comment]
Not an issue.

Check the memory limits on the pod that ran the build - depending on your environment the project can set default resource limits for builds that can be exhausted quickly.
