### ISSUE TITLE
Allow server to parse empty strings

### ISSUE THREAD

**Issue by Gl4di4torRr** [openshift/origin#24345]
### Version
4.2

##### Steps To Reproduce
1. Template I pulled from the docs and removed some of the values 

```
 oc process -f fulllimitrange.yaml 
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "apiVersion": "v1",
            "kind": "LimitRange",
            "metadata": {
                "name": "core-resource-limits"
            },
            "spec": {
                "limits": [
                    {
                        "max": {
                            "cpu": "2",
                            "memory": "1Gi"
                        },
                        "min": {
                            "cpu": "200m",
                            "memory": "6Mi"
                        },
                        "type": "Pod"
                    },
                    {
                        "default": {
                            "cpu": "300m",
                            "memory": "200Mi"
                        },
                        "defaultRequest": {
                            "cpu": "200m",
                            "memory": "100Mi"
                        },
                        "max": {
                            "cpu": "2",
                            "memory": "1Gi"
                        },
                        "maxLimitRequestRatio": {
                            "cpu": ""
                        },
                        "min": {
                            "cpu": "",
                            "memory": ""
                        },
                        "type": "Container"
                    }
                ]
            }
        }
    ]
}
```

2.  `oc process -f fulllimitrange.yaml `
This will return valid json

3. 
```
$ oc process -f fulllimitrange.yaml | oc apply -f-
Error from server (BadRequest): LimitRange in version "v1" cannot be handled as a LimitRange: v1.LimitRange.Spec: v1.LimitRangeSpec.Limits: []v1.LimitRangeItem: v1.LimitRangeItem.Min: MaxLimitRequestRatio: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|:{"cpu":""},"min":{"|..., bigger context ...|","memory":"1Gi"},"maxLimitRequestRatio":{"cpu":""},"min":{"cpu":"","memory":""},"type":"Container"}|...
```

##### Expected Result

The server should see the empty strings and omit those from the structure.

##### Additional Information
There are a number of tools that are trying to solve for this problem. If I had the ability to provide an Openshift object with all the defined variables and then send it to the server with a subset of the values defined, that would be a huge win. Then, I would be able to stay with the oc command and not have to use external tooling.

**Comment by adambkaplan** [comment]
@Gl4di4torRr Does `oc apply` work if the objects with empty values are removed?

**Comment by Gl4di4torRr** [comment]
@adambkaplan `oc apply` will work if I remove the objects with empty values.

 For instance, if I use this object where I removed the empty values.

```
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "apiVersion": "v1",
            "kind": "LimitRange",
            "metadata": {
                "name": "core-resource-limits"
            },
            "spec": {
                "limits": [
                    {
                        "max": {
                            "cpu": "2",
                            "memory": "1Gi"
                        },
                        "min": {
                            "cpu": "200m",
                            "memory": "6Mi"
                        },
                        "type": "Pod"
                    }
                ]
            }
        }
    ]
}
```

However, this does not solve my problem. In our current environment, we have over 10 OpenShift clusters. In the sandbox environment, I want to supply a min, max, default, etc. for a LimitRange. In the higher environments (INT, PROD), I do NOT want to supply a value. That is, empty string. The reason is so each application has to explicitly define Requests and Limits in their Deployment Config to ensure the application (Pods) is "Right-Sized".

In our automation to create namespaces and apply objects to the namespaces (LimitRange, ResourceQuota, etc.), I want the ability to have one template per object and pass in values that I want to create. Right now, I have to create a `limitrange-with-defaults.yaml`, `limitrange-without-defaults.yaml`, etc. I have to customize the template to ensure when I apply that template there are no empty values. I would prefer the server to read those empty strings and implicitly not create them. So the template in my first post, I would expect a LimitRange object to be created with a Max and Min for type Pod and a default, defaultRequest and max for type Container. Make sense?

**Comment by adambkaplan** [comment]
@Gl4di4torRr unfortunately this is not how the Kubernetes API works for resource requirements. If you provide anything here, Kubernetes will verify that the value is valid. This is well-established, so I doubt you will be able to convince folks upstream to change this behavior.
