### ISSUE TITLE
PersistentVolume remains Bound after PVC is deleted

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#2434]
Wondering if there is supposed to be a controller for this too, or if this is just a gap.

Following [the docs](https://github.com/sosiouxme/openshift-docs/blob/e675db4e8ac7dcde582a17dd8e1e83c68348d421/dev_guide/volumes.adoc) if I then delete my pod and PVC, the PV remains in Bound state:

```
$ osc delete pod/mypod
pods/mypod
# osc delete pvc/claim1
persistentvolumeclaims/claim1
# osc get pv -o json
{
    "kind": "List",
    "apiVersion": "v1beta3",
    "metadata": {},
    "items": [
        {
            "kind": "PersistentVolume",
            "apiVersion": "v1beta3",
            "metadata": {
                "name": "pv1",
                "selfLink": "/api/v1beta3/persistentvolumes/pv1",
                "uid": "8c5b0cd6-ffec-11e4-ae4e-22000ab3877e",
                "resourceVersion": "3311",
                "creationTimestamp": "2015-05-21T19:06:56Z"
            },
            "spec": {
                "capacity": {
                    "storage": "5Gi"
                },
                "nfs": {
                    "server": "10.179.135.126",
                    "path": "/mnt/export"
                },
                "accessModes": [
                    "ReadWriteOnce"
                ],
                "claimRef": {
                    "kind": "PersistentVolumeClaim",
                    "namespace": "whatever",
                    "name": "claim1",
                    "uid": "921edd60-ffec-11e4-ae4e-22000ab3877e",
                    "apiVersion": "v1beta3",
                    "resourceVersion": "3308"
                }
            },
            "status": {
                "phase": "Bound"
            }
        }
    ]
}
```

I don't know if it should go back to being unbound, or proceed to some other phase (completed? so that something knows the data needs to be wiped if something else is going to bind it). Staying in Bound doesn't seem right.

**Comment by sosiouxme** [comment]
Update: I tried creating the PVC again. At that point I noticed the PV actually was in Released state, though still had the claimRef from before. The new PVC remained in Pending, wasn't attached to the released PV. This is repeatable:

```
# osc delete pv/pv1
persistentvolumes/pv1
# osc create -f pv.json 
persistentvolumes/pv1
# osc get pv
NAME      LABELS    CAPACITY     ACCESSMODES   STATUS      CLAIM
pv1       map[]     5368709120   RWO           Available   
# osc create -f pvc.json                                                                                                                                                                 
persistentvolumeclaims/claim1
# osc get pv
NAME      LABELS    CAPACITY     ACCESSMODES   STATUS    CLAIM
pv1       map[]     5368709120   RWO           Bound     whatever/claim1
# osc get pvc
NAME      LABELS    STATUS    VOLUME
claim1    map[]     Bound     pv1
# osc delete pvc/claim1
persistentvolumeclaims/claim1
# osc get pv
NAME      LABELS    CAPACITY     ACCESSMODES   STATUS    CLAIM
pv1       map[]     5368709120   RWO           Bound     whatever/claim1
# osc create -f pvc.json 
persistentvolumeclaims/claim1
# osc get pv
NAME      LABELS    CAPACITY     ACCESSMODES   STATUS    CLAIM
pv1       map[]     5368709120   RWO           Bound     whatever/claim1
# osc get pvc
NAME      LABELS    STATUS    VOLUME
claim1    map[]     Pending   
```

Is this as expected (currently)? Need to document the full lifecycle here, as well as failure cases...

**Comment by sosiouxme** [comment]
For instance, should we allow deleting the PVC when a pod refers to it? Currently this is just peachy.

Also, once the PVC is deleted, the describe for PV looks wonky:

```
# osc describe pv/pv1
Name:   pv1
Labels: <none>
Status: %!d(api.PersistentVolumePhase=Bound)
Claim:  %!d(string=whatever/claim1)
```

**Comment by derekwaynecarr** [comment]
@markturansky

**Comment by markturansky** [comment]
pv.Spec.ClaimRef will remain non-nil and phase will be "Released" until manual reclamation occurs.

There is a "Recycler" PR upstream that will take a PV from "Released" through "Recycled" phases and finally "Availalble" again.   https://github.com/GoogleCloudPlatform/kubernetes/pull/8334

**Comment by sosiouxme** [comment]
Alright, so currently we can manually reclaim (by nuking the PV, doing whatever needs to be done to clear what's stored, and creating the PV again). The move from "Bound" to "Released" seems a little slow but this is pretty much wiorking as expected until the recycler comes through. We should just document the current "lifecycle" to set expectations.

**Comment by markturansky** [comment]
Discussed this with @smarterclayton in email.  I am going to push #8334 upstream and hopefully get this piece merged, but we can carry a patch as necessary.  I'd rather update the docs with the ability to recycle than to describe that limitation :)

**Comment by sosiouxme** [comment]
Sounds good to me +1

**Comment by manojRy** [comment]
oc patch pv/PVNAME --type json -p $'- op: remove\n  path: /spec/claimRef'

**Comment by finkr** [comment]
**Data loss warning:**

Removing `claimRef` (or setting it to `null`) will cause the volume the be immediately removed by the storage class if `persistentVolumeReclaimPolicy`:`Delete`.

Also, removing `claimRef` (or setting it to `null`) will make the PV volume available for any new PVC. 

I have written a procedure to migrate/re-use a PV: https://stackoverflow.com/questions/66078689/move-or-change-a-volume-namespace/66078690#66078690
