### ISSUE TITLE
Can't export resources and use them in different namespaces using get --export.

### ISSUE THREAD

**Issue by ammarzia** [openshift/origin#24372]
If I backup a resource in a namespace using `$ oc get --export` and then apply it to a different namespace, I get the following error:

`error: the namespace from the provided object "dev" does not match the namespace "prod". You must pass '--namespace=dev' to perform this operation.`

`$ oc get --export` exported the `dev` namespace which means I can only apply it in that namespace. I can't apply it elsewhere. This happens because `$ oc get --export` exports additional metadata about kubernetes resources that the deprecated `$ oc export` doesn't export.

It looks like this behavior is intentional:
https://github.com/kubernetes/kubernetes/pull/73787#issuecomment-461514213
https://github.com/kubernetes/kubernetes/issues/57898
https://github.com/openshift/origin/issues/10091#issuecomment-241430675

I can remove namespaces from the resource using [jq](https://github.com/stedolan/jq) or [yq](https://github.com/mikefarah/yq), but is there a better solution specifically for OpenShift that doesn't involve editing the resource?

##### Version
v3.11.146

**Comment by soltysh** [comment]
This functionality is removed by now. I'm going to close this.
/close
