### ISSUE TITLE
How to enable DynamicProvisioningScheduling feature gate in 3.11 ?

### ISSUE THREAD

**Issue by tamalsaha** [openshift/origin#24377]
I am creating OpenShift cluster on GitHub actions using `oc cluster up --skip-registry-check=true`. I want to enable the DynamicProvisioningScheduling feature gate so that I can install rancher/local-path-provisioner to dynamically provision PVCs.

I was able to get this working using Kind on Github actions for 1.11. https://github.com/tamalsaha/k8s-111-local-path-demo/blob/master/hack/kubernetes/kind.yaml

But I don't understand how to enable these feature gates in oc 3.11 ?

I read the docs here https://docs.openshift.com/container-platform/3.11/admin_guide/disabling_features.html . But I don't understand how do I get `/etc/origin/master/master-config.yaml` file and restart master service, when everything is running inside Docker.

**Comment by timbrd** [comment]
Here you can find the documentation on how to configure the cluster: https://github.com/openshift/origin/blob/release-3.11/docs/cluster_up_down.md#configuration

If you initalize the cluster with ```oc cluster up --skip-registry-check=true --write-config=true```, it generates all the necessary config files:

```
$ ./oc cluster up --write-config=true --skip-registry-check=true
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if required ports are available ...
W0108 21:20:01.782554   13036 up.go:765] Port 80 is already in use and may cause routing issues for applications.
W0108 21:20:01.783559   13036 up.go:765] Port 443 is already in use and may cause routing issues for applications.
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I0108 21:20:01.794820   13036 config.go:40] Running "create-master-config"
I0108 21:20:05.410222   13036 config.go:46] Running "create-node-config"
Wrote config to: "/root/openshift.local.clusterup"
```

You can find the master-config.yaml file in the directory ```/root/openshift.local.clusterup/kube-apiserver/``` then.

```bash
$ find /root/openshift.local.clusterup/kube-apiserver/ -name master-config.yaml
/root/openshift.local.clusterup/kube-apiserver/master-config.yaml
```

Edit the file and start the cluster with ```oc cluster up --skip-registry-check=true --base-dir=/root/openshift-local.clusterup```. I'm not sure why the documentation states you should use the parameter ```--host-config-dir```, since it does not exist.

**Comment by tamalsaha** [comment]
@timbrd , I tried your command and found that scheduler was not getting this flag. So, I added this flag to scheduler and controller-manager and built my own oc binary and tried. 
https://github.com/kmodules/origin/commit/085aea1165c49c0e3bb7fe3876856e942087ff3c

Now, I see that PVC get the `volume.alpha.kubernetes.io/selected-node` annotation from scheduler. But it is still missing the `volume.beta.kubernetes.io/storage-provisioner` which I understand is assigned by the pv_controller in controller-manager. Looking at the controller manager code, I see that it is waiting for a consumer.

https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/controller/volume/persistentvolume/pv_controller.go#L321-L343

```
I0109 11:12:35.466493       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"local-path-pvc", UID:"e51d3a7d-32cd-11ea-81cf-002522c2ca40", APIVersion:"v1", ResourceVersion:"2798", FieldPath:""}): type: 'Normal' reason: 'WaitForFirstConsumer' waiting for first consumer to be created before binding
```

I see that a bug was fixed around this spot that affected 1.12 and the code was same in 1.11. So, I don't know if I hit that bug.
https://github.com/kubernetes/kubernetes/pull/79696

**Comment by timbrd** [comment]
@tamalsaha Sorry, I can't help you with that. I don't have any insight into the openshift code.

Are you sure, Red Hat is shipping the DynamicProvisioningingSchedule feature with OpenShift 3.11? It's actually not listed in the [feature list.](https://docs.openshift.com/container-platform/3.11/admin_guide/disabling_features.html#admin-guide-list-feature-gates).

**Comment by tamalsaha** [comment]
@jsafrane , I wonder if you have why the dynamic volume provisioning is not working with OpenShift 3.11 .

**Comment by tamalsaha** [comment]
@timbrd , It is the `DynamicVolumeProvisioning` feature. Since I was able to get it wroking on k8s 1.11, I would think that it will work on Openshift 3.11 .

**Comment by jsafrane** [comment]
You can enable `DynamicProvisioningScheduling` feature as describe in https://docs.openshift.com/container-platform/3.11/admin_guide/disabling_features.html#admin-guide-list-feature-gates (of course with `DynamicProvisioningScheduling=true`). It must be enabled everywhere, i.e. in apiServerArguments, controllerArguments and kubeletArguments.
