### ISSUE TITLE
oc cluster up fails with unexpected EOF

### ISSUE THREAD

**Issue by rajputvishwas** [openshift/origin#24375]
[provide a description of the issue]
I want to setup all in one OKD (3.11) cluster on ubuntu hosted on AWS instance. I did this earlier as well I came across strange error

##### Version
[provide output of the `openshift version` or `oc version` command]

root@CapstoneNode-Test-new1:~/okd# oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
root@CapstoneNode-Test-new1:~/okd# hostname -i
10.65.117.237
root@CapstoneNode-Test-new1:~/okd# oc cluster up --public-hostname=10.65.117.237Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Using public hostname IP 10.65.117.237 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I0108 08:58:43.159330     874 config.go:40] Running "create-master-config"
I0108 08:58:45.108180     874 config.go:46] Running "create-node-config"
I0108 08:58:46.168367     874 flags.go:30] Running "create-kubelet-flags"
I0108 08:58:47.023909     874 run_kubelet.go:49] Running "start-kubelet"
I0108 08:58:47.208103     874 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E0108 09:03:47.209262     874 run_self_hosted.go:571] API server error: Get https://10.65.117.237:8443/healthz?timeout=32s: dial tcp 10.65.117.237:8443: connect: connection refused ()
Error: timed out waiting for the condition
root@CapstoneNode-Test-new1:~/okd# oc cluster down
root@CapstoneNode-Test-new1:~/okd# oc cluster up --public-hostname=10.65.117.237Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Pulling image openshift/origin-control-plane:v3.11
E0108 09:04:02.574310    4407 helper.go:179] Reading docker config from /root/.docker/config.json failed: open /root/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-control-plane:v3.11 anonymously
Image pull complete
Pulling image openshift/origin-cli:v3.11
E0108 09:04:05.652202    4407 helper.go:179] Reading docker config from /root/.docker/config.json failed: open /root/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11 anonymously
Image pull complete
Creating shared mount directory on the remote host ...
Determining server IP ...
Using public hostname IP 10.65.117.237 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I0108 09:04:10.109555    4407 flags.go:30] Running "create-kubelet-flags"
I0108 09:04:11.005458    4407 run_kubelet.go:49] Running "start-kubelet"
I0108 09:04:11.186258    4407 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0108 09:04:29.195411    4407 interface.go:26] Installing "kube-proxy" ...
I0108 09:04:29.195435    4407 interface.go:26] Installing "kube-dns" ...
I0108 09:04:29.195447    4407 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0108 09:04:29.195458    4407 interface.go:26] Installing "openshift-apiserver" ...
I0108 09:04:29.195462    4407 apply_template.go:81] Installing "kube-proxy"
I0108 09:04:29.195472    4407 apply_template.go:81] Installing "kube-dns"
I0108 09:04:29.195484    4407 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0108 09:04:29.195476    4407 apply_template.go:81] Installing "openshift-apiserver"
I0108 09:04:30.841805    4407 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: Get https://10.65.117.237:8443/apis/apiregistration.k8s.io/v1beta1/apiservices: unexpected EOF

##### Current Result
Error: Get https://10.65.117.237:8443/apis/apiregistration.k8s.io/v1beta1/apiservices: unexpected EOF

##### Expected Result
Should start cluster and display URL and credentials to access cluster

root@CapstoneNode-Test-new1:~/okd# oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
[Note] No client configuration specified; skipping client and cluster diagnostics.

ERROR: [CED3001 from controller openshift/origin/pkg/oc/cli/admin/diagnostics/util/util.go]
       Encountered fatal error while building diagnostics: Requested diagnostic(s) skipped; nothing to run. See --help and consider setting flags or providing config to enable running.
       
[Note] Summary of diagnostics execution (version v3.11.0+0cbc58b):
[Note] Errors seen: 1

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by mwolski89** [comment]
I'm stuck with the same problem

**Comment by bill-keller** [comment]
same issue for me on ubuntu 18.0.4 LTS. Works fine on CentOS 7

**Comment by robertofabrizi** [comment]
Same issue on centos 7.4
