### ISSUE TITLE
oc login password input is visible on Windows/msys/git bash

### ISSUE THREAD

**Issue by MisterMX** [openshift/origin#24385]
When using the `oc login` command the password input is visible on the console.

This happens when using git bash on Windows. The password is hidden when logging in with Windows Powershell.

##### Version

Openshift version:
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server *****
openshift v3.9.78
kubernetes v1.9.1+a0ce1bc657
```

Git bash version:
```
mintty 3.0.2 (x86_64-pc-msys)
```

##### Steps To Reproduce
1. Open new console window
2. Login to openshift cluster using `oc login`

##### Current Result
When typing in the password. It is visible on the screen.

##### Expected Result
The password input should stay hidden. Similar to `read -s`.

**Comment by erwinolszewski** [comment]
/reopen
/remove-lifecycle rotten

the problem still exists

**Comment by erwinolszewski** [comment]
please reopen. the problem still exists

**Comment by dariodsa** [comment]
Not stale, issue is still present.

**Comment by vajravelu1** [comment]
Yes this issue still exists and its important because its related to security.
really surprising to see such important security issues not getting traction in community !
