### ISSUE TITLE
image stream pulls not reconciled properly

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#24424]
We have a template with the default service account specifying an image pull secret, the secret, and an image stream, among other things. If the image stream is created before the service account is updated with the secret, the image stream never manages to pull the image from the private registry (gets stuck with 401).

##### Version

3.11.157

##### Steps To Reproduce
Apply a template with the following objects ordered in it:
1) image stream
2) `default` service account with an image pull secret
3) image pull secret

##### Current Result

The image stream is not authorized to pull image from the private registry.

##### Expected Result

The image stream should retry the pull since the default service account has the proper access right after the stream is created.

##### Additional Information

For now, we have worked around this issue by ordering the resources properly in the template.

**Comment by adambkaplan** [comment]
Unfortunately ImageStreams do not have the typical semantics one finds with CRDs. Imagestream import runs as a synchronous action on the `openshift-apiserver`. Today there is no controller which retries imagestream imports on failure.

**Comment by smarterclayton** [comment]
Yeah, and partially that was intentional so that we wouldn’t blow up upstream servers.

Note that image registries are allowed to return “not authorized” when the pull spec doesn’t exist, so even the error doesn’t really help us.

For now, setting the tag as scheduled is the closest analogue to retrying errors.
