### ISSUE TITLE
"Management Console" terminology

### ISSUE THREAD

**Issue by adellape** [openshift/origin#2444]
From a conversation recently with @joefern1 and @mpbarrett, there was a desire to sync up language in marketing materials and documentation to "web console" instead of "Management Console". After some brief poking around, the only spot I could find of an actual reference to "Management Console" in the product was the title bar in browser.

If the decision is indeed to switch that terminology, I presume the title bar (and any other instances in the product itself) should probably change as well.

cc: @liggitt

**Comment by liggitt** [comment]
@adellape, yeah, just let me know if that's decided on

**Comment by joefern1** [comment]
I would like to go ahead with the switch to "Web Console" to be in line with our marketing materials and web copy.
