### ISSUE TITLE
The build pod was killed due to an out of memory condition.

### ISSUE THREAD

**Issue by karthikeyanbaluchamy** [openshift/origin#24464]
Hi ,

I have registered for free demo version in ocp 4.3 and 
when i tried to do a build of my JAVA spring boot application  by giving the git url i am getting the below error 
I am new to OCP I am trying to understand the deployment.
Can anyone please help to fix the issue 

my git repo URL
https://github.com/karthikeyanbaluchamy/research-micro

Copying blob sha256:00f17e0b37b0515380a4aece3cb72086c0356fc780ef4526f75476bea36a2c8b
Copying blob sha256:38445d7aa2f471c91841137964473752cfd05f515c86ffb35995ca09920711f9
Copying config sha256:9a6cd285b6c8a3580c37e158c5e08544f30513897c59e7e29e862a7e3151df8e
Writing manifest to image destination
Storing signatures

**Comment by adambkaplan** [comment]
OpenShift starter pods have very low memory limits. Building a Spring Boot app is inherently memory intensive, I'm not surprised that the build was killed. If you're looking to demo builds on Starter clusters, I recommend trying one of the Ruby or NodeJS examples.

**Comment by karthikeyanbaluchamy** [comment]
Hi Adam, 
I tried to deploy the same application before two months that time I was able to deploy from trial login,
Since it got expired I created one more trial login  with that I could not able to deploy the application.
Any additional confirguration needed

**Comment by aeroxy** [comment]
Even Node.js programs with c++ bindings would fail to build. For example I have a program with lz4 binding that gets the same error message.
