### ISSUE TITLE
[Bug] Cannot create a customresourcedefinition that has been exported via 'oc get -o yaml|json' command and then deleted

### ISSUE THREAD

**Issue by radtriste** [openshift/origin#24476]
For our testing of operator in Openshift, there can be some updates of the crd file(s). And so we need temporarily to import the new crd file(s) and save the current crd existing (to be reimported after the test).

So, exporting via `oc get -o yaml` command into a file, delete the current, create the new crds and after the tests, remove the crd created for the test and create back old crd from the file(s).

This does not work ...

##### Version
Client Version: openshift-clients-4.2.0-201910041700
Server Version: 4.3.0-rc.3
Kubernetes Version: v1.16.2

##### Steps To Reproduce
1. oc get crd {CRD_NAME} -o yaml > file
2. oc delete crd {CRD_NAME}
3. oc create -f file

##### Current Result

`The CustomResourceDefinition "{CRD_NAME}" is invalid: spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead`

##### Expected Result

Creation ok

##### Additional Information
No CR existing in the cluster for the specified CRD.

If crd is already existing into the cluster and I try to apply the exported file, there is no error raised.

**Comment by radtriste** [comment]
Does happen also on OpenShift 4.3 release.

**Comment by benluddy** [comment]
@radtriste Have you seen this: https://github.com/kubernetes/kubernetes/issues/87231? You may need use the v1beta1 API to export your CRD if it doesn't validate against v1.

**Comment by radtriste** [comment]
wow missed that one. Thanks for the tip !
