### ISSUE TITLE
`osc get minions` has no output whatsoever

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#2449]
```
# osc get minions
# osc get nodes
NAME              LABELS    STATUS
ip-10-231-41-89   <none>    Ready
# osc get minions --loglevel=4
I0522 14:39:29.952106   15494 selector.go:53] Unable to list "minions": the server could not find the requested resource
# osc get bogus
error: no resource "bogus" has been defined
```

I'm not sure what output `osc get minions` *should* have but I think it should probably be *something*. Either a deprecation notice or more like `osc get bogus`.

**Comment by smarterclayton** [comment]
Minions is going to get nuked shortly so this lowers the priority a bit

**Comment by sosiouxme** [comment]
That ought to "fix" it.

----- Original Message -----

**Comment by fabianofranz** [comment]
I think most users are actually going to see a "forbidden" when doing `get minions`. I'd lower this to P3, any objections @smarterclayton @sosiouxme?

**Comment by sosiouxme** [comment]
I dunno about most users, but cluster-admin (who is the only one likely to care) gets nothing at this time.

**Comment by sosiouxme** [comment]
It's a p3 though, unless it's super easy.

**Comment by smarterclayton** [comment]
Minions are dead.
