### ISSUE TITLE
why does the openshift router(haproxy) not use the service for backend ?

### ISSUE THREAD

**Issue by philipp1992** [openshift/origin#24516]
Hi,

simple question:
Why does the haproxy of the openshift router not connect to the pod trough the service, but instead modifies the haproxy.config with the pods IP, every time a pod get updated?

/var/lib/haproxy/conf/haproxy.config:  server pod:simple-nginx-deployment-669595b85f-g58bz:simple-nginx:10.130.1.30:80 10.130.1.30:80 cookie 0bc0ce6798223297275029d73f849580 weight 256 check inter 5000ms

Wouldnt it be better to connect to the cluster-ip of the service? or the dns name of the service?

kind regards
Philipp

**Comment by foosinn** [comment]
I saw this issue by looking for something else, but i can give you an answer:

The openshift router allows sticky-sessions (sending a user always to the same backend). This is not possible with a service.

See: https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#routes-sticky-sessions
