### ISSUE TITLE
osadm registry doesn't support --selector flag

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#2451]
Like the router, users may wish to specify where their registry runs by providing a nodeSelector via `--selector` flag when creating the registry.

**Comment by brenton** [comment]
It's technically true we could live without this, however we know admins are going to use `osadm` to create the registry.  Having to manually add the node selector after the fact and recreate the pod is going to be a hassle.

**Comment by sosiouxme** [comment]
AKA https://trello.com/c/3Yba4GAv/720-enable-specifying-node-selectors
