### ISSUE TITLE
How to delete specific image from Openshift internal docker registry to free disk space

### ISSUE THREAD

**Issue by mnovak1** [openshift/origin#24559]
Is there a way how to delete given image from internal Openshift docker registry?

I've found (https://docs.okd.io/latest/admin_guide/pruning_resources.html#pruning-images):
`oc adm prune images --registry-url=$REGISTRY_URL --confirm`
but this does not allow to specify image I want to get rid of. 

If there is no such way at this moment, can new feature requirement be created?

**Comment by adambkaplan** [comment]
@mnovak1 the request to "delete given image from internal Openshift docker registry" can get very nuanced - are you looking to:

1. Delete an image with a specific tag, like `$ docker rmi myrepo/myimage:v4`?
2. Delete an image with a specific sha, like `$ docker rmi myrepo/myimage@sha256:<sha>`?
3. Delete all images within an imagestream?

**Comment by mnovak1** [comment]
@adambkaplan in my case it's like option 1. and .2. (I'll just note here that afaict `docker rmi ...` does not physically remove image from registry and does not free space)

What I'd like to see to work is:

- Find image to delete using grep command, something like:
 - `oc get images| grep image-registry.openshift-image-registry.svc:5000 | grep image-to-remove` which will return list like:
   - `sha256:09f4a3884403950b8e8042a322139d341d6fd5ad4072c4c4def0ee562f82d243   image-registry.openshift-image-registry.svc:5000/73-mnovak/helloworld-rs-build-artifacts@sha256:09f4a3884403950b8e8042a322139d341d6fd5ad4072c4c4def0ee562f82d243`
- and now to delete it like:
  - `oc adm prune images --image-hash=sha256:09f4a3884403950b8e8042a322139d341d6fd5ad4072c4c4def0ee562f82d243`

Option `--image-hash` does not exist, it's just how I would image it would work. There might be different option  `--image-reference=` for image reference `image-registry.openshift-image-registry.svc:5000/73-mnovak/helloworld-rs-build-artifacts@sha256:09f4a3884403950b8e8042a322139d341d6fd5ad4072c4c4def0ee562f82d243`  

Well it does not have to be directly in `oc adm prune images` command as quite intuitive is command `oc delete image sha256:<hash>` where new option to prune registry might be added, for example `--prune-registry` but I guess in this case it's tricky as it might be remote registry so most likely not possible.

**Comment by adambkaplan** [comment]
@dmage would `oc delete image sha256:<sha>` work? Does this delete the image on the registry, or just the metadata in etcd?

**Comment by dmage** [comment]
@adambkaplan users must never delete image objects. It'll just corrupt metadata and hide the image from `oc adm prune images`.

**Comment by dmage** [comment]
Because layers are shared between namespaces, there is no easy way to delete a single image. The layer cannot be delete from the storage until the entire cluster is scanned for references. If you want to delete the image you should:

1. remove all references to the image (i.e. delete all image stream tags),
2. run `oc adm prune images`.

**Comment by mnovak1** [comment]
@dmage exactly, the whole openshift must be scanned. The issue is that `oc adm prune images` is too big gun and is cleaning everything. Not just the image I want delete to free space in registry.

afaict `oc adm prune images` command creates graph of references/dependencies to given image and is able to delete image streams referencing it atm. With this information:
`oc adm prune images --image-hash=sha256:09f4a3884403950b8e8042a322139d341d6fd5ad4072c4c4def0ee562f82d243` 
could be able to delete single image and image streams referencing it. 

 In case that image would be referenced by:
- any running Pods.
- any pending Pods.
- any ReplicationControllers.
- any DeploymentConfigs.
- any Build Configurations.
- any Builds. 
then prune of this image would fail (with providing information why it cannot be deleted, what's referencing it)

**Comment by vglaiju** [comment]
Excellent request, im searching for the same that will free images accumulated under mounted HDD space of the atomic-registry.
adm prune is not releasing this as straight forward as an enduser would like to.
