### ISSUE TITLE
Routes can't be created if namespace has 63 chars

### ISSUE THREAD

**Issue by jpkrohling** [openshift/origin#24553]
We had a problem in the Jaeger Operator where some resources would fail to be created if the length of the namespace + name is bigger than 63 chars. While solving this problem in our operator, I faced a situation where OpenShift would allow a namespace to be created with 63 chars, but every route within it would fail due to `InvalidHost`, as the host is a combination of name + namespace as well.

Not sure whether there's anything that can or should be done, but perhaps a resource shouldn't be allowed to be created if it's known that it won't work.

**Comment by jpkrohling** [comment]
@kevinearls, @jkandasa, should I close this? I think there's nothing we can do in the operator's side, other than perhaps breaking the reconciliation cycle and not attempting to create anything...

**Comment by kevinearls** [comment]
@jpkrohling Yes, go ahead and close it.
