### ISSUE TITLE
Usability issues with deployments 

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2455]
* Verify `osc rollback` disables triggers and it's possible to restore them (probably something osc deploy should do) (https://github.com/openshift/origin/issues/3008)
* I should be able to "fail back" a deployment - scale back up the N-1 deployment and mark the latest failed, even after it's complete.  Example - I rollout a change, I realize it's bad, i don't want to disable automatic updates, but I do want to not deploy until another automatic change happens.  I want to scale N-1 back up, scale N down to zero, and mark N failed. (https://github.com/openshift/origin/issues/2854)
* Rolling update deployment strategies should support canary on readiness test at minimum (https://github.com/openshift/origin/issues/2637)
* I should be able to see that automatic deployments are disabled in `osc status` and `osc deploy` (https://github.com/openshift/origin/issues/2853)

**Comment by smarterclayton** [comment]
I should be able to enable/disable triggers on osc deploy.

**Comment by deads2k** [comment]
I'll take a stab at: I should be able to see that automatic deployments are disabled in osc status and osc deploy

**Comment by abhgupta** [comment]
@deads2k Thanks! Please spin off a new issue and link it here.

**Comment by abhgupta** [comment]
I have picked up deployment "fall-back"

**Comment by smarterclayton** [comment]
Reenabling triggers is the last item remaining here.
