### ISSUE TITLE
Deploy pods remain after deployment - OCP 4.3

### ISSUE THREAD

**Issue by cptmorgan-rh** [openshift/origin#24569]
Deploy Pods are not deleting after a deployment completes.

##### Version
OpenShit 4.3

### 3.11 App deployment progression ###
Step 1: Build
httpd-ex-1-build   1/1       Running   0          10s

Step 2: Deploy
httpd-ex-1-build    0/1       Completed           0          35s
httpd-ex-1-deploy   0/1       ContainerCreating   0          1s

Step 3: App begins to create
httpd-ex-1-build    0/1       Completed           0          38s
httpd-ex-1-deploy   1/1       Running             0          4s
httpd-ex-1-xtsx5    0/1       ContainerCreating   0          1s

Step 4: App finishes deploying, and deploy pod automatically deletes
httpd-ex-1-build   0/1       Completed   0          42s
httpd-ex-1-xtsx5   1/1       Running     0          5s

### 4.3 App deployment progression ###
Step 1: Build
httpd-1-build   1/1     Running   0          50s

Step 2: Deploy
httpd-1-build    0/1     Completed           0          52s
httpd-1-deploy   0/1     ContainerCreating   0          1s

Step 3: App begins to create
httpd-1-b6d54    0/1     ContainerCreating   0          2s
httpd-1-build    0/1     Completed           0          62s
httpd-1-deploy   1/1     Running             0          11s

Step 4: App finishes deploying, BUT deploy pod does not delete
httpd-1-b6d54    1/1     Running     0          9m15s
httpd-1-build    0/1     Completed   0          10m
httpd-1-deploy   0/1     Completed   0          9m24s

##### Current Result

Deploy pod is not deleted.

##### Expected Result

Deploy pods to be deleted once a deployment completes sucessfully.

##### Additional Information

I know you can modify revisionHistoryLimit in the DeploymentConfig to limit the amount of ReplicaSets you have and this prunes the deploy pod. 

However, I am unsure if this is the intended outcome or if this is a bug especially since the deploy pod is automatically deleted in OCP 3.11 and there is no mention of this change in the documentation.

**Comment by grtea** [comment]
What was the solution to this issue?
