### ISSUE TITLE
osadm registry should be able to update the registry

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2458]
Messed up my credentials, had no way to update the registry short of deletion and recreate.

**Comment by smarterclayton** [comment]
Needs to be a flag that allows that

**Comment by ncdc** [comment]
--update?

**Comment by sosiouxme** [comment]
But you just said it was P3 :) https://github.com/openshift/origin/issues/1175

**Comment by stevekuznetsov** [comment]
Dupe of https://github.com/openshift/origin/issues/1175

**Comment by fabianofranz** [comment]
Dupe of https://github.com/openshift/origin/issues/1175
