### ISSUE TITLE
Nest `osadm` certificate sub-commands

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2461]
We have several cert-related commands:
```
  create-master-certs               Create certificates for an OpenShift master
  create-key-pair                   Create a public/private key pair
  create-server-cert                Create a signed server certificate and key
  create-signer-cert                Create a signer (certificate authority/CA) certificate
```

Might be good to combine them under a subcommand

**Comment by pravisankar** [comment]
Can we do this:
```
  oc  cert-key  master      Create certificates and keys for an OpenShift master
  oc  cert-key  key-pair    Create a public/private key pair
  oc  cert-key  server      Create a signed server certificate and key
  oc  cert-key  signer      Create a signer (certificate authority/CA) certificate and key
```
@liggitt @smarterclayton

**Comment by liggitt** [comment]
Should be under oadm
I don't think "cert-key" is a great grouping command. Not sure if something like "cert", "certs", or "pki" would be better.

**Comment by smarterclayton** [comment]
Certs or cert is probably better than pki for most users.  Although pki is
accurate in a better way than cert.  "signing" might be more accurate.
Brainstorm a bit more I think

On Jun 29, 2015, at 8:00 PM, Jordan Liggitt <notifications@github.com>
wrote:

Should be under oadm
I don't think "cert-key" is a great grouping command. Not sure if something
like "cert", "certs", or "pki" would be better.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2461#issuecomment-116882723>.

**Comment by liggitt** [comment]
Etcd's cert tool is `etcd-ca`

**Comment by smarterclayton** [comment]
"oadm ca" isn't bad

On Jun 29, 2015, at 10:18 PM, Jordan Liggitt <notifications@github.com>
wrote:

Etcd's cert tool is etcd-ca

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2461#issuecomment-116914115>.

**Comment by adellape** [comment]
Seems like this was meant to be closed by https://github.com/openshift/origin/pull/3557.

**Comment by pravisankar** [comment]
Yes, Fixed in https://github.com/openshift/origin/pull/3557
@liggitt can you close this issue, thx.
