### ISSUE TITLE
Make oc cluster up works with crio

### ISSUE THREAD

**Issue by jbtrystram** [openshift/origin#24610]
I am not sure if `oc cluster up` is still the recommended way to easily get a local cluster for developpement, but that is still on the front page of https://www.okd.io/, written in large font :) 

I wanted to switch to podman / cri-o as a container runtime, but I found that `oc cluster up` does not support it.

##### Version
```
oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1. Install cri-o on fedora (and remove docker)
2. Run `oc cluster up`

##### Current Result
```
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
error: unexpected error inspecting image openshift/origin-control-plane:v3.11
```

**Comment by ZaMaZaN4iK** [comment]
I've faced the same issue. Any updates?

**Comment by rovandep** [comment]
So funny enough, there is podman-docker to mimic the docker CLI but this doesn't not help. 
Also, there is "--skip-registry-check" parameter but again, no luck.

**Comment by jbtrystram** [comment]
maybe it's supported in OKD 4 :)
