### ISSUE TITLE
osadm new-project should use a template like osc new-project

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#2464]
and it should allow a `--template` argument

**Comment by liggitt** [comment]
How is this different than just using `osc process <f> | osc create -f -`?

**Comment by liggitt** [comment]
`osadm new-project` makes assumptions about what parameters are in the template, right?

**Comment by deads2k** [comment]
> osadm new-project makes assumptions about what parameters are in the template, right?

Yes, and our default template isn't written anywhere.

**Comment by liggitt** [comment]
that's why I made `osadm create-bootstrap-project-template`

**Comment by deads2k** [comment]
> that's why I made osadm create-bootstrap-project-template

Yeah.... I'm still going to say that `new-project` is a whole lot nicer to use to get started.  Templates feel hard when you're first starting.

**Comment by liggitt** [comment]
should it use the default template by default?

**Comment by liggitt** [comment]
outside my head, that question sounds stupid

**Comment by derekwaynecarr** [comment]
but when is a default really default?

**Comment by liggitt** [comment]
actually, maybe it's not stupid... the template assumes a project admin... if you don't provide one, what happens?

**Comment by deads2k** [comment]
empty string?  Could be worse.
