### ISSUE TITLE
Helm server is not installed on OpenShift 4.3 

### ISSUE THREAD

**Issue by vanchikovan** [openshift/origin#24689]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by vanchikovan** [comment]
The helm version is not showing the output of helm server. 

[kni@provisioner linux-amd64]$ ./helm version
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Error: forwarding ports: error upgrading connection: unable to upgrade connection: error dialing backend: dial tcp 172.22.0.36:10010: connect: no route to host
[kni@provisioner linux-amd64]

**Comment by vanchikovan** [comment]
The port 10010 also added on firewall but still face the same issue

**Comment by Nessa-G22** [comment]
[https://raw.githubusercontent.com/adobe/spectrum-web-components/master/README.md](github) 
Duplicate of # 24690

**Comment by Nessa-G22** [comment]
@Nessa-G22 ``

**Comment by vanchikovan** [comment]
Installed the correct version on both master and client , Helm is installed on Openshift 4.3
