### ISSUE TITLE
When first connecting to console ui, get redirected to internal ip

### ISSUE THREAD

**Issue by withinboredom** [openshift/origin#2473]
I'm experimenting with openshift origin 3, and using boot2docker. When trying to connect for the first time: https://192.168.99.100:8443/console/ gets redirected to https://10.0.2.15:8443/oauth/authorize...

The bug is that it shouldn't redirect to another host. In the real world, there would probably be some kind of VIP that the machine is behind and the user would be unlikely to be able to access the internal network directly.

**Comment by liggitt** [comment]
Pass `--public-master=https://192.168.99.100:8443` when starting OpenShift to tell it the public address to use.

**Comment by withinboredom** [comment]
Thanks, that's a great workaround!

**Comment by liggitt** [comment]
That's the official way to indicate the web-facing address to use. It can't just use the requesting address, because the server needs to know the hostname at start time to generate a valid certificate and set up allowed OAuth login redirect URLs.
