### ISSUE TITLE
Strange failures in West Pennsylvania...

### ISSUE THREAD

**Issue by withinboredom** [openshift/origin#2474]
Saw this in the logs:

```
I0524 02:52:24.958370       1 provider.go:91] Refreshing cache for provider: *gcp_credentials.dockerConfigUrlKeyProvider
E0524 02:52:25.161341       1 metadata.go:131] Unsupported URL scheme: <html><head><meta http-equiv="refresh" content="0;url=http://autosearch.zoominternet.net/search/?q=http://metadata.google.internal/computeMetadata/v1/instance/attributes/google-dockercfg-url&t=0"/></head><body><script>window.location="http://autosearch.zoominternet.net/search/?q="+escape(window.location)+"&r="+escape(document.referrer)+"&t=0";</script></body></html>
```

and

```
I0524 02:47:06.531571       1 provider.go:91] Refreshing cache for provider: *gcp_credentials.dockerConfigKeyProvider
E0524 02:47:08.457217       1 config.go:144] while trying to parse blob "<html><head><meta http-equiv=\"refresh\" content=\"0;url=http://autosearch.zoominternet.net/search/?q=http://metadata.google.internal/computeMetadata/v1/instance/attributes/google-dockercfg&t=0\"/></head><body><script>window.location=\"http://autosearch.zoominternet.net/search/?q=\"+escape(window.location)+\"&r=\"+escape(document.referrer)+\"&t=0\";</script></body></html>": invalid character '<' looking for beginning of value
E0524 02:47:08.457360       1 metadata.go:109] while reading 'google-dockercfg' metadata: invalid character '<' looking for beginning of value
```

Apparently an ISP in West PA overrides DNS failures with a "pretty search page" ... This is easily resolved by changing dns settings to opendns/google dns. However, this has left my openshift installation in a completely broken state.

Mostly reporting this so that if someone else hits this, they know what to do... start over from scratch.

**Comment by liggitt** [comment]
Well, we're unlikely to support the `<html><head><meta http-equiv="refresh" content="0;url=http` url scheme, popular as it is in PA ;)

I would be interested to know what broke in that scenario. Seems like that would be similar to recovering from a DNS cache poisoning attack, etc, which we do care about.

**Comment by withinboredom** [comment]
Basically everything broke. Any attempt to start a new build would fail, even after fixing the dns issue, keys in the kv store were probably still completely boinked. I'm still too new to openshift to be able to just look at something and know what is broken... Wouldn't be hard to reproduce with a simple bind config.

**Comment by smarterclayton** [comment]
Closing due to age.
