### ISSUE TITLE
Error in logs: "Image garbage collection failed"

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#2481]
```
May 26 02:19:00 vm openshift-node[37324]: E0526 02:19:00.985231   37324 kubelet.go:637] Image garbage collection failed: non-existent label "docker-images"
```
```shell
$ journalctl -u openshift-node | grep "Image garbage collection failed" | wc -l                                                                                   
49
```
The node was running for ~16 hours. It's `0.5.2`.
Is this an error? Should I be concerned?

**Comment by smarterclayton** [comment]
That error seems to be coming from cAdvisor.  What does cAdvisor print for `Filesystem partitions: ...` in the logs?  It looks like it's not detecting your docker installation.

**Comment by TomasTomecek** [comment]
I checked logs briefly and couldn't find any such message. Will try to restart node and master and will report again.

**Comment by danmcp** [comment]
Please reopen if you can recreate.

**Comment by pbabinca** [comment]
Same problem here:
```
# journalctl -o cat -u openshift-node | grep "Image garbage collection failed" | sed 's,.*\(Image \),\1,' | sort | uniq -c
    118 Image garbage collection failed: non-existent label "docker-images"
      6 Image garbage collection failed: unable to find data for container /
```
`openshift-node-0.5.2`, `openshift-master-0.5.2`, `docker-1.6.2-10`

I run out of pods:
```
# osc describe node $(hostname) | egrep 'Pods:|maxpods:'
 maxpods:       200
Pods:                           (200 in total)
```

Suddenly after couple of reboots of openshift-node the problem disappeared .
