### ISSUE TITLE
Unable to create a SCC using helm chart on OC 4.3

### ISSUE THREAD

**Issue by deekshahegde86** [openshift/origin#24836]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]
Client Version: v4.3.1
Server Version: 4.3.5
Kubernetes Version: v1.16.2

##### Steps To Reproduce
I am trying to create a SCC using helm chart on OC 4.3. I get error:
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "SecurityContextConstraints" in version "v1"

My template :
`apiVersion: v1`
`kind: SecurityContextConstraints`
`metadata:`
  `name: twistlock-console`
`users:`
`- system:serviceaccount:{{ .Values.namespace }}:twistlock-console`

Doesnt work with apiVersion: v1 as well.

##### Current Result
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "SecurityContextConstraints" in version "v1"
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by Kali-lightsaber** [comment]
Classic
