### ISSUE TITLE
Project create page should be updated

### ISSUE THREAD

**Issue by wjiangjay** [openshift/origin#2483]
Due to this PR(https://github.com/openshift/origin/pull/2351), project name rules has been changed.
And better to let the Create button is disabled when the input can not pass validation.
For the current codebase,  the create button is active when I just type one char.

**Comment by liggitt** [comment]
@spadgett should be super quick

**Comment by wjiangjay** [comment]
After this fix, when I enter some invalid name "#$%&^$%&*", the prompt message "Project anmes may only contain lower-case letters, numbers, and dashes. They may not start or end with a dash." will not come out.

**Comment by liggitt** [comment]
I think the message appears when the focus leaves the field.

**Comment by wjiangjay** [comment]
@liggitt oh, yes, you are right.
