### ISSUE TITLE
The origin-version-change command problems with templates

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2485]
I'm trying to convert all samples we have in origin repo to v1beta3 and I found interesting error. One sample (examples/project-quota/application-template-with-resources.json) failed to convert throwing this:

``` console
2015/05/26 12:47:53 Unable to decode Template objects: [quantities must match the regular expression '^([+-]?[0-9.]+)([eEimkKMGTP]*[-+]?[0-9]*)$' quantities must match the regular expression '^([+-]?[0-9.]+)([eEimkKMGTP]*[-+]?[0-9]*)$' quantities must match the regular expression '^([+-]?[0-9.]+)([eEimkKMGTP]*[-+]?[0-9]*)$']
```

When I looked into the template I found this:

``` json
"limits": {
    "cpu": "${MYSQL_RESOURCES_LIMITS_CPU}",
    "memory": "${MYSQL_RESOURCES_LIMITS_MEMORY}"
  }
},
```

@smarterclayton can we somehow relax the k8s validation to ignore the following errors?

**Comment by liggitt** [comment]
I'm surprised a straight serialize/deserialize is running validation

**Comment by mfojtik** [comment]
@liggitt it might be conversion error but I can't find any in k8s conversion functions...

**Comment by smarterclayton** [comment]
V1beta1 resources were messed up, so they have to be converted.  Not sure you're going to be able to automatically change this.

**Comment by smarterclayton** [comment]
Closing due to age.
