### ISSUE TITLE
Deprecate / Remove the osc build-log command

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2488]
As the build pods now matches the name of the build, there is no difference between doing `osc log foo` and `osc build-log foo`.

@smarterclayton @jhadvig  PTAL

**Comment by soltysh** [comment]
:+1: agreed

**Comment by smarterclayton** [comment]
SGTM, don't have time today to review.

**Comment by jhadvig** [comment]
:+1: sounds good

**Comment by soltysh** [comment]
Given https://github.com/openshift/origin/pull/2552 I think we'd better leave build-log command as is.

**Comment by smarterclayton** [comment]
Build log should continue to exist.  I thought this was a different issue.  Build logs provide additional semantics over pods - build logs guarantee waits prior to the pod existing.  Closing.
