### ISSUE TITLE
Can't start cluster on Fedora CoreOS

### ISSUE THREAD

**Issue by jesusalvb** [openshift/origin#24890]
I'm trying to start up a OKD 3.x on Fedara CoreOS 31

[core@localhost openshift-origin-server-v3.11.0-0cbc58b-linux-64bit]$ sudo ./oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Checking type of volume mount ...
error: cannot start container 0ac3ec5c14ff854382df99de6dcbee8d5a581348245ba0cd7d294c969088f087

Docker version 18.09.8, build 0dd43dd
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.11.0+0cbc58b

**Comment by leolb-aphp** [comment]
I think Fedora CoreOS is to use with OKD 4.x not 3.x
For OKD 3.x you can use CentOS Atomic Host
