### ISSUE TITLE
Docker Hub Installation Methods at docs.okd.io is outdated

### ISSUE THREAD

**Issue by ismailyenigul** [openshift/origin#24898]
Installation method "Method 1: Running in a Container" mentioned 
https://docs.okd.io/3.11/getting_started/administrators.html#running-in-a-docker-container is outdated. 
a quote from https://hub.docker.com/r/openshift/origin  

```
NO LONGER UPDATED: This image was deprecated after the 3.10 OpenShift release, being split into multiple other images. It is no longer used by commands like oc cluster up or the openshift-ansible install.
```

so please update the documentation to avoid conflict and misunderstanding.

##### Version
# oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1.  visit https://hub.docker.com/r/openshift/origin 
2. visit https://docs.okd.io/3.11/getting_started/administrators.html#running-in-a-docker-container

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by zerodayz** [comment]
@ismailyenigul  This is openshift-docs component and the Running in container section should be removed see https://github.com/openshift/openshift-docs/issues/13870

**Comment by zerodayz** [comment]
Now discussing in the openshift-docs issue and PR is here https://github.com/openshift/openshift-docs/pull/21942

**Comment by zerodayz** [comment]
@ismailyenigul documentation has been updated.

**Comment by zerodayz** [comment]
docs has been updated in openshift-docs repository

/close
