### ISSUE TITLE
Openshift fails to bootstrap

### ISSUE THREAD

**Issue by mentaldriller** [openshift/origin#24910]
When I try to bootstrap OpenShift using the openshift-install via the command

openshift-install waot-for bootstrap-complete --log-level debug

the output gets stuck saying:
Still waiting for Kubernetes API : Get https://api.devops.yemenmobile.com.ye/version?timeout=32s: EOF
##### Version
the version of OpenShift is 4.3.5 and the version of oc is 4.3.5
##### Steps To Reproduce
1. run openshift-install waot-for bootstrap-complete --log-level debug

##### Current Result
Still waiting for Kubernetes API : Get https://api.devops.yemenmobile.com.ye/version?timeout=32s: EOF
##### Additional Information
I am deploying OpenShift on a restricted network using VMware vSphere. the output of 
openshift-install gather bootstrap --bootstrap 10.76.150.247 --master 10.76.150.248 --key ~./ssh/id_rsa

is uploaded in the tar.gz file

**Comment by mentaldriller** [comment]
[log-bundle.tar.gz](https://github.com/openshift/origin/files/4518074/log-bundle.tar.gz)

**Comment by zerodayz** [comment]
@mentaldriller Did you during the installation, ssh'd to the bootstrap node and stopped and started bootkube?

bootkube.sh[100750]: Error: error creating container storage: the container name "etcd-signer" is already in use by "6f62cb71992c902b50cd3ccdc82368b9c91e8d541a572da4c12ddfeeb916c34f". You have to remove that container to be able to reuse that name.: that name is already in use
Apr 22 17:17:09 etcd-3 systemd[1]: bootkube.service: Failed with result 'exit-code'.

Do you still have the problem or have you workaround it?

**Comment by mentaldriller** [comment]
Thank you @zerodayz, I have already solved it by regenerating the ignition configs because they have expired and are only valid for 24 Hours. Another issue was that I was installing on a slow storage which caused the etcd service to disconnect regularly.

**Comment by zerodayz** [comment]
Hi @mentaldriller if the issue is solved. Can you resolve the issue in Github as well? Thank you.

**Comment by mentaldriller** [comment]
Sorry my bad!
