### ISSUE TITLE
Error creating host: Error creating the VM: Error creating machine: Error in driver during machine creation: exit status 1

### ISSUE THREAD

**Issue by sayom88** [openshift/origin#24918]
Hello,

I want to install Openshift on my laptop Win 10 using Red Hat CodeReady Containers. From my command prompt, I am giving the command as crc start, and then I get the error as Error creating host: Error creating the VM: Error creating machine: Error in driver during machine creation: exit status 1. Can anyone help please. I am also sharing the screenshot.

![Error](https://user-images.githubusercontent.com/16284729/80279807-73832f80-871d-11ea-83c0-8dbc38319aa4.png)

**Comment by zerodayz** [comment]
Hi @sayom88 please can you attach the ~/.crc/crc.log file to the created issue.

**Comment by tomas-ortega** [comment]
Same for me :(

![image](https://user-images.githubusercontent.com/14965364/82123311-ff2a3200-9798-11ea-96a6-f55a158d1a93.png)

**Comment by sayom88** [comment]
Any resolution for this issue please

**Comment by praveenkumar** [comment]
@sayom88 Can you please file issue on https://github.com/code-ready/crc/issues with all the details?

**Comment by jmonteros81** [comment]
help! i have the seem problem

**Comment by tomas-ortega** [comment]
Try the next:

- Very important, you need use a user with no admin privileges and other user with admin privileges in the system
- For the test, turn off any antivirus, like Avast
- Be sure, you have almost in your hardware more than 4 cpu, with only 4 cpu, will be all slow
- Be sure, you have almost in your hardware 16GB RAM
- Be sure, Hyper-V has already installed with the windows admin user, restart

- crc cleanup (To clean latest configuration)
- crc setup
- crc start -p pull-secret -m 15360

With default memory, i remember... 9 Gb, some cluster operator would have problem to start

Good Luck!

If any problems, don't hesitate to continue the thead!

Currently i have a running crc but in VM (VMWare) of CentOS 7.7, and always it's ok

**Comment by jmonteros81** [comment]
from
![crc-e1](https://user-images.githubusercontent.com/19291961/83288169-365e0180-a1e3-11ea-89e6-f3996c9eab7c.jpg)
![crc-e2](https://user-images.githubusercontent.com/19291961/83288178-39f18880-a1e3-11ea-9bf6-95c06cd4e5fd.jpg)

 my side just i saw the min req that showed on the official page,

First things first, you need a decent workstation to run OpenShift 4. The minimum requirements are 4 vCPUs, 8 GB RAM, and 35 GB disk space. And even with that, I constantly saw HyperKit (the VM backend CRC uses) consuming 100-200% CPU and 12+ GB of RAM (sheesh!)....but 16 gb i dont hvae it...some help...and just i have 4 cpu...thks in advance kind regards

**Comment by godiaz89** [comment]
Any news on this issue? Im having the same problem, I tried @tomas-ortega solution but it  didnt worked for me. Thanks in advance, Regards

**Comment by SirTediousOfFoo** [comment]
This probably won't be helpful to a lot of people but it seems to have fixed this issue for me.

I had Docker Desktop installed and running in the background. After fully quitting Docker and letting its VMs shut down i ran 'crc cleanup' and 'crc start' which seems to have fixed the issue for me.

Therefor: Check if you're running any other VMs or if you have some machines installed that you dont know about that could be using HyperV. This can be checked via the HyperV Manager

hoping it helps someone

**Comment by talk2gopijj** [comment]
You are right about docket desktop... crossed this step but got below error when crc start
ERRO Error determining host IP: Temporary Error: unknown error occurred

**Comment by praveenkumar** [comment]
I am closing this issue from origin side, if you still face issues with crc better to create it https://github.com/code-ready/crc/issues and discuss.

/close
