### ISSUE TITLE
UX design: oc version should offer OpenShift version of the server.

### ISSUE THREAD

**Issue by docwhat** [openshift/origin#24935]
The output  of `oc version` should include the version of OpenShift on the server.

```sh
# Current output
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.example.com:6443
kubernetes v1.16.2
```

```sh
# Proposal
$ oc version
Client:
  oc: v3.11.0+0cbc58b
  kubernetes: v1.11.0+d4cacc0
  features: Basic-Auth GSSAPI Kerberos SPNEGO

Server:
  openshift: v4.3
  endpoint: https://api.example.com:6443
  kubernetes: v1.16.2
```

**Comment by zerodayz** [comment]
@docwhat Isn't this more of a oc component issue rather than origin?

https://github.com/openshift/oc/issues

**Comment by zerodayz** [comment]
This seems relevant to this issue: https://github.com/openshift/origin/issues/22901 I can see you are using oc client 3.11 querying the 4.x cluster. You should be able to get the cluster from 'oc get clusterversion' but also I can see there is another pull request open on this  https://github.com/openshift/oc/pull/235
