### ISSUE TITLE
error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by mentaldriller** [openshift/origin#24934]
[provide a description of the issue]
When the bootstrap machine is ignitied the Kubernetes API fails to start. More over, the port 6443, 22623 are not opened in the bootstrap machine!

Platform:
VMware vSphere 6.7
#of master nodes 3
#of worker nodes 2

Network:
Restricted network architecture.
Registry is already mirrored to the bastion server

##### Version
Client version 4.3.5
Unable to connect to the server EOF

##### Steps To Reproduce
1. create iginition configs 
   openshift-install create ignition-configs --dir=.
2. [step 2]
   Run the bootstrap installer
   openshift-install wait-for bootstrap-complete --dir=. --log-level debug
##### Current Result
penShift Installer v4.3.5                   
DEBUG Built from commit 82f9a63c06956b3700a69475fbd14521e139aa1e 
INFO Waiting up to 30m0s for the Kubernetes API at https://api.devops.yemenmobile.com.ye:6443... 
DEBUG Still waiting for the Kubernetes API: Get https://api.devops.yemenmobile.com.ye:6443/version?timeout=32s: EOF 

##### Expected Result

Kubernetes API is up bootstrap complete 

##### Additional Information
output from the bootstrap machine 

-- Logs begin at Wed 2020-04-29 14:03:50 UTC, end at Wed 2020-04-29 17:45:37 UTC. --
Apr 29 14:04:30 localhost systemd[1]: Starting Download the OpenShift Release Image...
Apr 29 14:04:30 localhost release-image-download.sh[2671]: Pulling quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:32 localhost podman[2683]: 2020-04-29 14:04:32.227421944 +0000 UTC m=+1.672780081 system refresh
Apr 29 14:04:33 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:33 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:34 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:34 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:35 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:35 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:36 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:36 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:37 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:37 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:37 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:37 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:38 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:38 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:39 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:39 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:40 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:40 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:41 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:41 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:43 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:43 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:43 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:43 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:45 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:45 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:46 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:46 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:47 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:47 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:47 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:47 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:48 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:48 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:50 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:50 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:51 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:51 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:51 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:51 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:53 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:53 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:04:53 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:04:53 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...
Apr 29 14:05:08 localhost release-image-download.sh[2671]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a: error pinging docker registry quay.io: Get https://quay.io/v2/: x509: certificate has expired or is not yet valid
Apr 29 14:05:08 localhost release-image-download.sh[2671]: Pull failed. Retrying quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a...

**Comment by zerodayz** [comment]
Hi @mentaldriller 

Have you got the chance to login to bootstrap node and check the SSL certificate

`openssl s_client -connect quay.io | openssl x509 -noout -text`

Likely the issue is on the bootstrap node with wrong time set.

**Comment by mentaldriller** [comment]
Hi @zerodayz,
thank you for your response. The time was set correctly I checked by SSHing to the bootstrap node via the core account. It turned out that my ignition files has expired. I did not know that they are only valid for 24 hours. So, I regenerated the ignition configs and installed the cluster.

**Comment by zerodayz** [comment]
Hi @mentaldriller If the issue is resolved, can you solve the issue in Github as well? Thank you.

**Comment by mentaldriller** [comment]
Sorry totally forgot!
