### ISSUE TITLE
Can not find openshift/jenkins-ephemeral template while creating maven pipeline build 

### ISSUE THREAD

**Issue by rathohit311356** [openshift/origin#24970]
##### Version - 3.11
While trying to create template from https://bitbucket.org/ashu0183team1/maven-pipe-01/src/master/maven-pipeline.yaml via import yaml to our devops namespace

We do not have jenkins-ephemeral image in openshift namespace and its failing , we dont not have access to openshift namespace ,

While creating we getting error that it can not found jenkins-ephemeral template in openshift namespace

##### Steps To Reproduce
1. Create Devops namespace
2. Use the template given above and try creating template
3. We should not have jenkins-ephermeral image in openshift namespace
4. Admin access to only devops namespace 

##### Current Result
Error: maven-pipeline failed to create 
can not create build config 'openshift-jee-sample", jenkins-piepline template openshift/jenkins-ephemeral not found

##### Expected Result
Pipeline template should be created

**Comment by uselessidbr** [comment]
> ##### Version - 3.11
> While trying to create template from https://bitbucket.org/ashu0183team1/maven-pipe-01/src/master/maven-pipeline.yaml via import yaml to our devops namespace
> 
> We do not have jenkins-ephemeral image in openshift namespace and its failing , we dont not have access to openshift namespace ,
> 
> While creating we getting error that it can not found jenkins-ephemeral template in openshift namespace
> 
> ##### Steps To Reproduce
> 1. Create Devops namespace
> 2. Use the template given above and try creating template
> 3. We should not have jenkins-ephermeral image in openshift namespace
> 4. Admin access to only devops namespace
> 
> ##### Current Result
> Error: maven-pipeline failed to create
> can not create build config 'openshift-jee-sample", jenkins-piepline template openshift/jenkins-ephemeral not found
> 
> ##### Expected Result
> Pipeline template should be created

I don't know if you copied the error or rewrited it but i see that there's a mistype:

Error: maven-pipeline failed to create
can not create build config 'openshift-jee-sample", **jenkins-piepline** template openshift/jenkins-ephemeral not found

As a workaround i suggest you to try this:

# curl -L https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/jenkins-ephemeral-template.json -o jenkins-ephemeral-template.json

# oc create -f jenkins-ephemeral-template.json

**Comment by rathohit311356** [comment]
Thanks that worked
