### ISSUE TITLE
Deleting a project doesn't delete the deploymentConfigs

### ISSUE THREAD

**Issue by brenton** [openshift/origin#2499]
This can be reproduced with the router.  Create it, delete the default project.  Once it comes back automatically try to recreate the router.  The old deploymentConfig will still be there.

**Comment by derekwaynecarr** [comment]
This is tricky.

The ```default``` namespace is created in Kubernetes.

The list of ```Finalizers``` on a Namespace is immutable post-creation.

Option A: Change upstream to allow Finalizers to be mutable
1) Allow the list of Finalizers to be appended in upstream
2) Author OpenShift admission controller to ensure that if you create OpenShift resource in a Namespace, that that Namespace has OpenShift finalizer set.

Option B: Do not allow OpenShift resources in default namespace
1) Author OpenShift admission controller to reject creation of OpenShift content in a Namespace that does not have it as a named finalizer.

@smarterclayton - any opinions on this?

**Comment by smarterclayton** [comment]
Can we make finalizers append / add only?

**Comment by derekwaynecarr** [comment]
I will submit a PR to do that and go Option A.

**Comment by derekwaynecarr** [comment]
@smarterclayton - I have been working too much and became scatter-brained.  

We need no upstream change to support this.  I will just modify the admission controller in Origin to verify that the Namespace.Spec.Finalizers list has openshift listed prior to admitting OpenShift content, if it does not, I will update the list with /finalize, and things will be fine.

**Comment by smarterclayton** [comment]
K
