### ISSUE TITLE
router status handler should not use a hardcoded password

### ISSUE THREAD

**Issue by brenton** [openshift/origin#2500]
https://github.com/openshift/origin/blob/master/images/router/haproxy/conf/haproxy-config.template#L32

Apologies in advance if this is already being tracked elsewhere.

**Comment by pweil-** [comment]
On my list of TODOs but not tracked.  Thanks for the issue, @brenton

**Comment by brenton** [comment]
Yeah, with all the choas I just wanted to make sure we didn't miss this. :)

**Comment by pweil-** [comment]
PR is submitted.  I've also emailed @bmeng to add the new config items to a QE test case since this is in github only (not trello or BZ).  Will make a docs pr to specify the required input (FYI, it's only `stats-password` when using osadm, the user/port will default to admin/1936)  Happy routing!
