### ISSUE TITLE
OC login issue: TLS handshake timeout

### ISSUE THREAD

**Issue by darpan91** [openshift/origin#25016]
Hi Team,
I have installed RHCOS . i have login to master node  where oc login failing with below error. 
[core@master0 openshift]$ oc login -u system:admin --insecure-skip-tls-verify
**Server [https://localhost:8443]: https://api.ocp4.bacadgsl.com:6443                             
error: net/http: TLS handshake timeout**

Also  please find below output of oc command.
[core@master0 openshift]$ oc version
Client Version: 4.3.7-202003130552-62c8cca

**[core@master0 openshift]$ oc status
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.**

Please help to resolve the same. 

Regards,
Darpan

**Comment by travier** [comment]
Closing. See https://github.com/openshift/os/blob/master/docs/faq.md#q-where-should-i-report-issues-with-openshift-container-platform-or-red-hat-coreos for RHCOS specific support.

/close
