### ISSUE TITLE
DC, RC and pods don't indicate nodeSelector

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2509]
Looking at the DC or the RC via "describe" doesn't provide any indication that a nodeSelector is
applied, and looking at a pod doesn't give any indication why it was scheduled where it was scheduled.

```
osc v0.4.3.2-141-g3a39f33
kubernetes v0.14.1-582-gb12d75d
```

**Comment by abhgupta** [comment]
This was created based on discussion in an email thread and the proposed resolution was to include the node selector for al three resources in their "describe" output.

**Comment by thoraxe** [comment]
Is this still relevant? It's ancient.
