### ISSUE TITLE
Is there a disconnected installation for okd 3.11 ?

### ISSUE THREAD

**Issue by bessalahAmar** [openshift/origin#25092]
Hello,

is the disconnected installation available for okd 3.11 ? I can see that it's available for openshift 3.11 at this link ( https://docs.openshift.com/container-platform/3.11/install/disconnected_install.html ) wondering if it will work for okd 3.11 ?

Thanks :)

**Comment by vglaiju** [comment]
I was looking for some answeres here. Tyring to get the community version(OKD) installed using disconnected mode will be a great addition. I only find enterprise(OCP) documentations in this regard as the reporter of this thread has share above.
