### ISSUE TITLE
DeploymentConfig ImageChange trigger should use an object reference of ImageStreamTag and not ImageStream

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#2511]
Changes needed:
* Validation needs to be updated to support the ImageStreamTag format
* The deployment ImageChange controller needs to be updated to work with ImageStreamTags

**Comment by csrwng** [comment]
@ironcladlou fyi

**Comment by ironcladlou** [comment]
This one can be assigned to me. Spoke earlier with @csrwng and @ncdc and deployments should support From.Kind=ImageStreamTag *only* just as builds do.
