### ISSUE TITLE
OpenShift regenerates admin.kubeconfig upon restart

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#2516]
Steps:
1. start OpenShift server
2. change to an existing project "demo": `osc project demo`
3. restart the server
4. `osc project` returns `Using project "default" on server "https://10.0.2.15:8443".`

I expected the last command to return `"demo"`. If the server restarts while a client is interacting with `osc`, there's no way to know that the context for the next command has suddenly changed and a `osc project demo` is needed again.

**Comment by liggitt** [comment]
The cluster admin kubeconfig (openshift.local.config/master/admin.kubeconfig) is currently regenerated when running `openshift start`. This is to ensure the kubeconfig has the correct hostname and credentials for the cluster admin.

Normal users should probably not be running from the cluster-admin's kubeconfig, though it would be nice to handle that situation better.

**Comment by smarterclayton** [comment]
Closing due to age.
