### ISSUE TITLE
Default pod manifest config dir for a node

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#2517]
Right now there seems to be no default config dir for per-pod manifests (see https://github.com/openshift/origin/blob/cdd1903e0576b178669c2e83866cdf67db3b7356/pkg/cmd/server/start/node_args.go#L126).

Does making this configurable & also defaulting to something like `openshift.local.volumes` with a 1 second watch would seem reasonable?

**Comment by liggitt** [comment]
I really don't want to default to enabling static pods... it should be possible, but discouraged

**Comment by jimmidyson** [comment]
Why not? In the absence of a per-node controller as we've discussed when talking about secrets in static pods, this is the only option for certain supporting services, like fluentd logging, unless we just deploy normal docker containers which would lose the benefits of running in openshift.

**Comment by jimmidyson** [comment]
@liggitt So is that a definite no to this? If so then I'll need to document how to reconfigure the openshift node config file on every node to enable this if you want cluster wide logging.

**Comment by liggitt** [comment]
I don't think we should turn on watching a directory for static pods by default. I think enabling that should be a choice admins make. @smarterclayton, what say you?

**Comment by smarterclayton** [comment]
Optional, defaults false
