### ISSUE TITLE
openshifts-tests gives SCC error when using non-cluster-admin user

### ISSUE THREAD

**Issue by joeldavis84** [openshift/origin#25237]
When logged in as a user with a custom role most tests succeed but occasionally (and seemingly randomly) a test will fail with an error message similar to the following:

```
fail [k8s.io/kubernetes/test/e2e/framework/pods.go:83]: Error creating Pod
Unexpected error:
    <*errors.StatusError | 0xc0021eb7c0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "pods \"client-containers-ffecd499-d4f4-48df-8284-5da169060110\" is forbidden: unable to validate against any security context constraint: []",
            Reason: "Forbidden",
            Details: {
                Name: "client-containers-ffecd499-d4f4-48df-8284-5da169060110",
                Group: "",
                Kind: "pods",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 403,
        },
    }
    pods "client-containers-ffecd499-d4f4-48df-8284-5da169060110" is forbidden: unable to validate against any security context constraint: []
occurred

Jul 02 14:43:28.101 I ns/container-probe-2746 pod/liveness-4131ece0-a632-42a7-9d60-f84b07666b61 node/master-0 container/liveness reason/Started
Jul 02 14:43:28.221 W ns/gc-437 pod/simpletest.rc-2nb5g node/master-1 reason/BackOff Back-off restarting failed container (3 times)
Jul 02 14:43:28.228 E ns/gc-437 pod/simpletest.rc-2nb5g node/master-1 container/nginx container exited with code 1 (Error):
Jul 02 14:43:28.228 W ns/gc-437 pod/simpletest.rc-2nb5g node/master-1 container/nginx reason/Restarted
Jul 02 14:43:28.244 W ns/gc-437 pod/simpletest.rc-xc4db node/master-1 reason/BackOff Back-off restarting failed container (3 times)
Jul 02 14:43:28.250 E ns/gc-437 pod/simpletest.rc-xc4db node/master-1 container/nginx container exited with code 1 (Error):
Jul 02 14:43:28.250 W ns/gc-437 pod/simpletest.rc-xc4db node/master-1 container/nginx reason/Restarted
Jul 02 14:43:28.312 I ns/gc-437 pod/simpletest.rc-brw74 node/master-0 container/nginx reason/Pulled image/docker.io/library/nginx:1.14-alpine

failed: (500ms) 2020-07-02T14:43:28 "[k8s.io] Docker Containers should be able to override the image's default command and arguments [NodeConformance] [Conformance] [sig-node] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]"
```
If I give the test user account access to the privileged scc that seems to work around the issue but that's not ideal for the current goal of running unprivileged. 

I've pulled kube-api audit logs to see if a particular request is being 403'd and I am seeing the above containers being allowed by RBAC but still getting a 403 back. If I set `--count 2` then the test suites appear to run successfully the second time. If I leave `--count` at the default of `1` then the tests that do fail seem more or less random. [Here](https://drive.google.com/file/d/1pLvtn4wHzA_6-HpaPcaIQm2ZlEky4KK7/view) is a log of some test runs I made yesterday. 

##### Version
```
[kni@kni1-master-2 ~]$ oc version
Client Version: 4.4.6
Server Version: 4.4.6
Kubernetes Version: v1.17.1+f63db30
```

##### Steps To Reproduce
1. Disconnect from the internet, deploy OpenShift 4.4.6
2. [Configure IDP, create users](https://github.com/e-minguez/ose-tests/blob/master/README.md), create custom role, add custom role to test user
3. Manually deploy external images required for testing.
4. Execute [the minimal conformance test suite](https://raw.githubusercontent.com/e-minguez/ose-tests/master/tests-lists/openshift-conformance-minimal.txt) with: `openshift-tests run --count 2 --junit-dir=./ -f openshift-conformance-minimal.txt > openshift-conformance-minimal-output-${RANDOM}.txt 2>&1`
5. Observe results

##### Current Result

Some tests succeed, others fail. Retrying the tests 2-3 times via `--count` or logging in as a user with access to the `privileged` SCC appears to work around the issue.

##### Expected Result
Each test run produces the same list of problematic tests and the ones that fail contain an error message explaining what SCC issue it may be running into.

##### Additional Information
junit XML File: https://drive.google.com/file/d/1tRuBJoHCPC_SFO3h3REe4ID9Ey0b9LQo/view?usp=sharing

junit HTML File: https://drive.google.com/file/d/1gUvAt5ZaNpNpnpj2t88OTXYC6IOjbUBc/view?usp=sharing

openshift-tests command line output: https://drive.google.com/file/d/1j92LpaYG0hKIjwkZbvnRRPN7JOLspsYz/view?usp=sharing

**Comment by e-minguez** [comment]
I've been able to reproduce this as well in bare metal IPI with 4.4.11, 4.4.12 and 4.4.13 but no in AWS 4.4.11, 4.4.12, 4.4.13 or 4.5.2. The procedure has been the same as documented here https://github.com/e-minguez/ose-tests/blob/master/README.md but in a connected environment.
