### ISSUE TITLE
Sometimes pod fails to perform a healthcheck with message "No route to host"

### ISSUE THREAD

**Issue by truongkendy** [openshift/origin#25337]
Sometimes pods in a node of my openshift cluster loose the connection with message "No route to host"

##### Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xyz:8443
openshift v3.11.0+bd0bee4-337
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. Sometimes, pod loose its connection with message "No route to host" and fail to perform a healthcheck, which causes pod restart but it still doesn't work.
2. I need to delete pods (then it recreates) in order to make it works.

##### Current Result
Error message:
Liveness probe failed: Get http://10.128.2.24:8080/healthz/ready: dial tcp 10.128.2.24:8080: connect: no route to host
##### Expected Result
Pod runs smoothly

**Comment by dpliangjl** [comment]
通过关闭防火墙试试
