### ISSUE TITLE
Getting namespace does not exist error on admission

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2549]
With the NamespaceExists admission controller in place, I'm seeing spurious "Namespace X does not exist" errors.

I see this when I create a namespace and immediately try to create something in it. The store used by the admission controller must not be up to date yet, so it rejects.

**Comment by derekwaynecarr** [comment]
Will cherry-pick: 

https://github.com/GoogleCloudPlatform/kubernetes/pull/8696
