### ISSUE TITLE
How to start/stop a pod / docker container without recreating a new one

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#2550]
If, for any reasons, we have to restart a docker container created by openshift/kubernetes, the only way to achieve that is to use the `docker stop` and `docker start` cmd. The issue is that when we run a docker stop, then openshift/kubernetes will recreate a new docker container

```
dabou:~/$ docker ps | grep gerrit
1d42e44b000f        cmoulliard/gerrit:1.0                     "/home/gerrit/conf-a   3 minutes ago       Up 2 minutes                                                                           k8s_gerrit-container.840a547_gerrit-controller-6l7i7_default_23c11929-046b-11e5-86fd-0800275503ae_870d7886              
382ff64e0c30        openshift/origin-pod:v0.5.1               "/pod"                 16 hours ago        Up 16 hours                                                                            k8s_POD.dd39df9e_gerrit-controller-6l7i7_default_23c11929-046b-11e5-86fd-0800275503ae_8df9d9cf                          
dabou:~/$ docker stop 1d42e44b000f
1d42e44b000f
dabou:~/$ docker ps | grep gerrit
382ff64e0c30        openshift/origin-pod:v0.5.1               "/pod"                 16 hours ago        Up 16 hours                                                                            k8s_POD.dd39df9e_gerrit-controller-6l7i7_default_23c11929-046b-11e5-86fd-0800275503ae_8df9d9cf                          
dabou:~/$ docker ps | grep gerrit
6574d19d0ac5        cmoulliard/gerrit:1.0                     "/home/gerrit/conf-a   About a minute ago   Up Less than a second                                                                      k8s_gerrit-container.840a547_gerrit-controller-6l7i7_default_23c11929-046b-11e5-86fd-0800275503ae_8f1b17fa              
382ff64e0c30        openshift/origin-pod:v0.5.1               "/pod"                 16 hours ago         Up 16 hours
``` 

Questions : 
- Can we avoid this behavior - that a new docker container is recreated ?
- Is it planned to offer an openshift client command to start/stop a pod and/or container ?

**Comment by danmcp** [comment]
We do have osc stop today.  Which is essentially a shortcut to osc scale 0 (was osc resize).  And to restart you would do an osc scale 1 (or more).  If your use case is to restart a single container or maybe pod that belongs to a scaled up replication controller it doesn't exist yet.  It's possible targeted pod restart will be added at some point for debugging/development purposes.  But the general mindset is to rely on liveness/readiness style checks to automatically discover broken containers and fix them automatically.

**Comment by Oswald-Dsa** [comment]
There are many use cases where one would need to gracefully terminate a specific container and at the same time reduce the container target count by 1; examples include:
1) We want the container counts to increase/reduce during high/low times based on some external metrics criteria. simply put..... for example:
      a) Based on job-wait-time in a external queuing system and/or SLA of job processing
      b) Based on queue size in the external queuing system
2) However, we dont want to terminate the container when a job is in progress;
3) This leaves us with one option - when the application in the container knows a particular job processing is complete, it can determine it is not needed anymore based on some business logic - at that point, it can send some command/signal to OpenShift to increase/decrease the container by 1 - OpenShift can then accordingly make the config change and KILL THAT SPECIFIC CONTAINER WITHOUT having to spawn another container.
