### ISSUE TITLE
Cancelled deployments leave orphaned hook pods

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#2556]
When cancelling a deployment during a hook execution, only the deployer pod is cancelled. Whatever hook pod it was executing will continue running to completion.

**Comment by ironcladlou** [comment]
cc @abhgupta 

Hook names aren't deterministic at the moment. If we made them deterministic, we could discover the pods and also set deadlines on them.

**Comment by ironcladlou** [comment]
After some discussion, we decided it would be nicer to make a new label for hook pods like `openshift.io/depoy-hook.deployment=<deployment name>` for use in a pod query to find and terminate hook pods.

**Comment by abhgupta** [comment]
- We decided on labels since we can query on them. 
 - We can recommend users to apply those labels on deployment hook pods in case they use custom deployment strategies. This would allow us to reap them in case of cancellation.
 - Initially, we've stayed away from using labels for these purposes (favoring annotations instead) since labels could conflict with service/RC selectors. However, with prefixes, this should no longer be an issue.

**Comment by abhgupta** [comment]
@smarterclayton Need a quick +1 from you on this.

**Comment by smarterclayton** [comment]
Why aren't hook pods deterministic?

**Comment by smarterclayton** [comment]
Why would there ever be more than one?

**Comment by abhgupta** [comment]
@smarterclayton Agree - we need to make hook pod names deterministic as well. For custom deployment strategies, the user manages the hooks and we won't be able to guarantee deterministic pod names. However, as a simple measure, we can recommend that users apply a certain label on their deployment hook pod that will allow us to identify and terminate such pod(s) if the deployment were cancelled or in other such cases.

If we are talking about custom deployment strategies, there is a possibility that the deployer pod spins up multiple "worker" pods as part some "hook-like" mechanism. If we are hoping to address custom deployment scenarios, having a label is more flexible.

**Comment by smarterclayton** [comment]
Im fine with labels as long as the things we control are deterministically named.

**Comment by ironcladlou** [comment]
Agree, no reason to not use deterministic naming where possible. We can use @csrwng's new utility in https://github.com/openshift/origin/pull/2552 for hook names just like with the deployer pod.
