### ISSUE TITLE
Deployment retry is broken

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#2558]
Deployment retries are now broken due to deterministic deployer pod naming. When the retry command resets the deployment status to New, the deployment controller sees the existing deployer pod from the failed deployment, assumes that there's nothing to do, and transitions the deployment to Pending. Then a later reconciliation sees the previously failed deployer pod and transitions the deployment back to Failed.

**Comment by ironcladlou** [comment]
cc @abhgupta 

Unfortunately, I think the deterministic names invalidate the approach I took for retries. I can think of two ways to go about it now:

1. Retry deletes the existing deployer pod (and hook pods?) before resetting the deployment phase
2. Retry becomes a synonym for `--latest` and we don't re-use the deployment.

**Comment by liggitt** [comment]
does approach 1 mean logs from the failed deployment immediately disappear?

**Comment by ironcladlou** [comment]
@liggitt 
>does approach 1 mean logs from the failed deployment immediately disappear?

Yeah. That's a pretty big drawback.

**Comment by ironcladlou** [comment]
I think at this point, rather than trying to introduce more complexity around retry, I think it might be best to just use `--latest` to start a new deployment if the last one failed. It eats a version number but behaves correctly.

@smarterclayton thoughts? I'd say either remove `--retry` (and update docs to suggest `--latest` when a retry is desired), or make `--retry` a synonym for `--latest`.

**Comment by smarterclayton** [comment]
Retry should start a new deployment.

**Comment by abhgupta** [comment]
Posting here since this is the original issue:

@liggitt @ironcladlou @smarterclayton If we create a new deployment, there won't be a difference between --latest and --retry any more. 

Also, retries originally retried the previous deployment faithfully since the deployment config was serialized as an annotation and not affected by subsequent changes to the deployment config. If we implement option 2, we are not guaranteed to retry the exact same deployment - strategy could be different, hooks is another thing that could change (part of strategy config).

**Comment by abhgupta** [comment]
@liggitt @ironcladlou I really don't see an issue with deleting the deployer pod for the previous failed deployment. This is a user-driven command and the user has the option to check/backup any log files before the retry command.

**Comment by ironcladlou** [comment]
@abhgupta 
>@liggitt @ironcladlou I really don't see an issue with deleting the deployer pod for the previous failed deployment. This is a user-driven command and the user has the option to check/backup any log files before the retry command.

Good point...

**Comment by liggitt** [comment]
Are we sure it is always user-driven? Is it expected that retrying will remove access to the previous failure?

**Comment by abhgupta** [comment]
@liggitt A retry is always user-driven ( @ironcladlou pls confirm ). User expectation is something that can be set via docs and usage text. If not acceptable, I would suggest removing the retry option altogether.

**Comment by ironcladlou** [comment]
>@liggitt A retry is always user-driven ( @ironcladlou pls confirm ). User expectation is something that can be set via docs and usage text. If not acceptable, I would suggest removing the retry option altogether.

The only user facing way we provide to retry is via the CLI. There's no discrete API for it. So, as it stands, always user driven.

**Comment by smarterclayton** [comment]
Retry shouldn't restart a successful deployment.  That's the difference

**Comment by abhgupta** [comment]
Agreed - Retry will always retry the last deployment, provided it failed. If not, it errors and exits. However, you missed addressing the main question/concern:

Retries originally retried the previous failed deployment faithfully since the deployment config was serialized as an annotation and not affected by subsequent changes to the deployment config. If we implement option 2, we are not guaranteed to retry the exact same deployment - strategy could be different, hooks is another thing that could change (part of strategy config).

**Comment by smarterclayton** [comment]
> On May 28, 2015, at 2:04 PM, Abhishek Gupta <notifications@github.com> wrote:
> 
> Agreed - Retry will always retry the last deployment, provided it failed. If not, it errors and exits. However, you missed addressing the main question/concern:
> 
> Retries originally retried the previous failed deployment faithfully since the deployment config was serialized as an annotation and not affected by subsequent changes to the deployment config. If we implement option 2, we are not guaranteed to retry the exact same deployment - strategy could be different, hooks is another thing that could change (part of strategy config).
> 
How would they have changed?

**Comment by liggitt** [comment]
If I'm reading correctly, if the deployment config had changed, retry would actually revert the config back to the one it was retrying

**Comment by smarterclayton** [comment]
The intent of retry is to redeploy the most recent failed deployment if it exists.  A delta between DC and RC should be something the user needs to know about

**Comment by abhgupta** [comment]
@liggitt Retry does not revert the "config" back. It merely tries to run a deployment using the previous config/strategry/hooks.

**Comment by liggitt** [comment]
ah

**Comment by abhgupta** [comment]
Here is a sequence of events:

 - Deployment 5 started
 - DC updated without bumping up LatestVersion
 - Deployment 5 fails
 - User retries deployment 5
 - Deployment 6 is created (as part of retry) with newer config

**Comment by abhgupta** [comment]
The above assumes the implementation where retry just starts a NEW deployment.

**Comment by smarterclayton** [comment]
I think retry should use 5 as the base or warn the user and require --confirm to recreate 5, or tell the user to use --latest for 6.

**Comment by abhgupta** [comment]
Great! At least we have consensus on the problem statement.
So, our options are:

1. Reset the status of the failed deployment and delete the deployer pod
 - We seem to have a dislike for this given that the pod logs will be lost
2. Create Deployment 6 (New) using DC annotation from Deployment 5 (Failed)
 - If the LatestVersion for the deployment and the DC annotation will not match (potential issues)
3. Perform a comparison of the DC stored on the failed deployment with the current DC
 - Need to write comparison code

Can we settle on a approach? I still favor the first option.

**Comment by smarterclayton** [comment]
I'd be fine with 1 or 2, no time for 3.  1 seems simplest.

**Comment by ironcladlou** [comment]
https://github.com/openshift/origin/pull/2582 will provide a the support to easily identify the group of deployer and related pods to delete.
