### ISSUE TITLE
OpenAPI Spec file missing for 4.6

### ISSUE THREAD

**Issue by ctron** [openshift/origin#25643]
Past versions of this repository provided the OpenShift OpenAPI spec, for example: https://raw.githubusercontent.com/openshift/origin/release-4.5/api/swagger-spec/openshift-openapi-spec.json

This useful for generating clients, e.g. OpenShift client for Rust: https://github.com/ctron/openshift-openapi

In version 4.6, I can no longer find the file.

##### Version
 4.6

##### Steps To Reproduce
1. Look at the repository

##### Current Result

File not found

##### Expected Result

File found

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by tmds** [comment]
@ctron if you have a cluster you may get it like this:
```
oc get --raw /openapi/v2
```

@bparees was this removed intentionally?

**Comment by bparees** [comment]
@mfojtik @deads2k did openshift-openapi-spec.json move to another repo/location?

**Comment by tmds** [comment]
ping@mfojtik @deads2k

**Comment by ctron** [comment]
Looks like it is also missing for 4.7!

**Comment by ctron** [comment]
> @ctron if you have a cluster you may get it like this:
> 
> ```
> oc get --raw /openapi/v2
> ```
> 
> @bparees was this removed intentionally?

I just checked your proposal. It actually contains all CRDs I have in my cluster. So it is not the OpenShift API, but a combination of OpenShift + <all-my-stuff> … which is not what I want.
