### ISSUE TITLE
"osc help get" should return a complete list of resources that support "get"

### ISSUE THREAD

**Issue by ryanj** [openshift/origin#2566]
For new users that are unfamiliar with kubernetes and V3 terminology.

The current response includes:

```
Display one or many resources.

Possible resources include builds, buildConfigs, services, pods, etc.
```

**Comment by pmorie** [comment]
+1 to this; I've had to dig through the code to find the correct resource name before.

**Comment by stevekuznetsov** [comment]
Currently if you use the bash autocompletions `oc get <tab> <tab>` does this. Is there any benefit to also putting that information in the help text?

**Comment by kargakis** [comment]
The help text already shows a bunch of them..

**Comment by stevekuznetsov** [comment]
We may be able to close this, then.

**Comment by fabianofranz** [comment]
`oc get` without args or flags also print a bunch of them.
