### ISSUE TITLE
Use server time for UI time difference calculations

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2568]
The UI uses relative time in several places:
- Showing how how long a build has been running
- Determing when to warn that a pod has been pending for a long time
- ...

Those differences are currently calculated using creation timestamps on objects and comparing with browser time. When the client or server clocks are off, times can get weird, causing problems like:
- As a pod starts, it briefly shows a warning style on the overview page.
- Elapsed times can be negative

We should have a way to determine server time (or the offset between server time and client time)

**Comment by liggitt** [comment]
something in isTroubledPod?

**Comment by spadgett** [comment]
@liggitt Do you see this? I think it might be a clock skew between my laptop and OpenShift running inside a VM.

**Comment by liggitt** [comment]
oh, that's fun... server clock skew

**Comment by spadgett** [comment]
I've verified that my server clock is way off. This isn't a timezone issue.

@liggitt let me know how you want to handle this. I'd say either close or lower the severity.

**Comment by spadgett** [comment]
I wonder if it's possible to have messages like "Build started 2 minutes from now" or "Build has been running for -2 minutes" ...

**Comment by jwforres** [comment]
kubectl handled this in upstream by saying if something was less than two minutes into the future, just assume it is actually now.  More than two minutes they were showing as an error in the timestamp column.

Could make relative-timestamp not allow future times, or optionally allow it to have future times by passing in a flag, in case there are things down the road that are future like jobs scheduled for a certain time.

Doesn't solve the reverse issue of client clock being ahead of the server clock.

**Comment by jwforres** [comment]
Opened API issue for returning Date header https://github.com/openshift/origin/issues/5762

**Comment by jwforres** [comment]
We have the Date header being returned by the API now and it is correctly allowed through the CORS security

**Comment by jwforres** [comment]
Consolidating with bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1371764
