### ISSUE TITLE
Not able to deny all the traffic using Network policy in openshift 

### ISSUE THREAD

**Issue by ashokkumar2706** [openshift/origin#25686]
Created a Network policy to deny all the traffic. As expected i am not able to connect to test-namespace from other projects.

But i expect also, my current namespace [test-namespace] should not connect to other project. When i checked this senario, its able to ping from inside to other namespaces. Kindly help how to implement this policy?
 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: test-namespace
spec:
  podSelector: {}
  policyTypes:
    - Ingress

**Comment by kvsheejith** [comment]
I guess you must use [ ]  not {}
