### ISSUE TITLE
Control Plane state after install OCP 4.5.19 ist unknown

### ISSUE THREAD

**Issue by IlonkaO** [openshift/origin#25714]
[provide a description of the issue]
After  fresh install of OpenShift 4.5.19 bare metal install the Web GUI shows status of the Control Plane as unknown. In the events ther are 3 critical alerts:
**KubeControllerManager has disappeared from Prometheus target discovery.**
**KubeScheduler has disappeared from Prometheus target discovery**
**KubeAPI has disappeared from Prometheus target discovery**
The pods of the control plane are all running without any special errors in the logs. Also the Prometheus Pods doesn't show any error.
I haven't got any idea where to search for this issue
##### Version
[provide output of the `openshift version` or `oc version` command]
Client Version: 4.5.19
Server Version: 4.5.19
Kubernetes Version: v1.18.3+10e5708

##### Steps To Reproduce
1. Install a OCP 4.5.19 bare maetal cluster
2. After installation completly finsihed Control Plane has a unknown status

##### Current Result
Control Plane is in unknown state, The KubeApi, KubeControllerManager, and KubeScheduler are dissapeared from Prometheus

##### Expected Result
Everything is ready

##### Additional Information
- 7 node cluster
- 3 master, 4 worker
- VMs based on libvirt
- VMs are provided with matchbox 
- GoBetween as LoadBalancer
- Traefik as Router
- OAuth = htpasswd
- Enabling stop and resume following https://blog.openshift.com/enabling-openshift-4-clusters-to-stop-and-resume-cluster-vms/
- no network restrictions, no proxy

**Comment by siwyroot** [comment]
Hello,
Same problem on VMware UPI install 4.5.20, BigIP F5 LB, 3 masters 4 workers.
