### ISSUE TITLE
Failed to pull image docker.io/openshift/origin-deployer:v3.11.0 - too many requests

### ISSUE THREAD

**Issue by cassanellicarlo** [openshift/origin#25734]
Failing to pull Openshift origin-deployer image from Docker Hub because of the pull rate limit.

##### Version
Kubernetes v1.11.0+d4cacc0
OKD v3.11.0+1b5fc2d-513

##### Current Result
Failed to pull image docker.io/openshift/origin-deployer:v3.11.0: rpc error: code = Unknown desc = too many requests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

##### Expected Result
Not having this error for the origin deployer. 
Is there a way to solve this problem? We would like to not configure secrets for the docker hub on every deployment. Maybe the solution is to switch to another registry?

**Comment by tetsushiawano** [comment]
having the same issue today.
we trying to proceeding by purchasing a dockerhub pro license.

**Comment by cassanellicarlo** [comment]
Yes you can do that. But you still have to specify the pull secret in all the deployments. That's a bit annoying.

**Comment by manusa** [comment]
I think that the Docker images for 3.11/3.11.0 are being updated (maybe quay too), but the content might not be the same.

We're starting to get issues in our [E2E ](https://github.com/eclipse/jkube/actions/runs/409582284)tests for 3.11 environment, especially when running requests like `https://127.0.0.1:8443/apis/build.openshift.io/v1/namespaces/myproject/builds/quarkus-rest-s2i-12?watch=true`

We're getting internal server error (500) responses with the following body:
```
invalid upgrade response: status code 200
```

This started to happen 4 days ago, I first thought that it was related with our codebase. However today I noticed that the base images have changed (at least the date), and I think our issue might be cause by this.
