### ISSUE TITLE
"Cannot create undefined undefined" error message

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2574]
If the `details` property is missing in the error response, we show `undefined` in the UI. This was creating from a source repository in the web console.

The error itself is legitimate, but we should handle error responses with no `details` in the client.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/7869132/bf8d3a34-054e-11e5-81d2-ba1111459b7a.png)

```
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}
```

**Comment by spadgett** [comment]
Related to #2313, but in a different controller.

**Comment by liggitt** [comment]
Can you do a quick sweep, and maybe see if there's something you could factor out to get details consistently?
