### ISSUE TITLE
Unable to apply 4.6.0-0.okd-2020-12-12-13535 -> syncRequiredMachineConfigPools: pool master has not progressed to latest configuration

### ISSUE THREAD

**Issue by acsecengtesting** [openshift/origin#25782]
[mco.zip](https://github.com/openshift/origin/files/5775835/mco.zip)

Unable to apply 4.6.0-0.okd-2020-12-12-135354: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration

##### Version
Client Version: 4.6.0-0.okd-2020-11-27-200126
(upgrading to 4.6.0-0.okd-2020-12-12-135354)

##### Steps To Reproduce
1. Apply cluster upgrade to 4.6.0-0.okd-2020-12-12-135354 (N.B. needed to force due to https://github.com/openshift/okd/issues/426) 

##### Current Result
Upgrade fails to proceed and blocks on the machine config operator
Unable to apply 4.6.0-0.okd-2020-12-12-135354: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: controller version mismatch for rendered-master-5a032982847665a0a7261dbf1ad27372 expected eb9778355a9020673e8ce9aee092cb98d80cde5e has 5a9e6b4eedaf72ecc2534355173843e011f19765: 0 (ready 0) out of 3 nodes are updating to latest configuration rendered-master-be834a6a05b0b65e63a1725d4dc447c2, retrying

I can't see any errors in the MCO or MCDs - so not sure how it got stuck or how to fix from here. 

##### Expected Result
Cluster upgrades to .6.0-0.okd-2020-12-12-135354

##### Additional Information
Will attach get all from openshift-machine-config-operator namespace

**Comment by schadom** [comment]
Same here @acsecengtesting . Could you fix this in the meantime?
