### ISSUE TITLE
hello-openshift won't run with "no such file or directory"

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2579]
When I try to define a pod, I get this error. Then, trying to run the image directly doesn't seem to work, either.

```
[root@ose3-master beta4]# osc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/hello-openshift/hello-pod.json
pods/hello-openshift
[root@ose3-master beta4]# osc get pod
POD               IP         CONTAINER(S)      IMAGE(S)                    HOST                                    LABELS                 STATUS    CREATED      MESSAGE
hello-openshift   10.1.0.6                                                 ose3-master.example.com/192.168.133.2   name=hello-openshift   Pending   21 seconds   
                             hello-openshift   openshift/hello-openshift                                                                  Waiting                API error (404): Cannot start container d43086b159bcf40e39e5a914aa94a08c21d4932ccfcb2a08817987cd14eff6ff: [8] System error: no such file or directory
```

```
[root@ose3-master beta4]# docker run -it openshift/hello-openshift
Timestamp: 2015-05-28 18:21:26.78563384 -0400 EDT
Code: System error

Message: [/usr/bin/tar -cf /var/lib/docker/tmp/298bbecec47d3c707a4b6288ae8e075e374239432a54d8f4e2aad835d827f4a2234841957/_tmp.tar -C /var/lib/docker/devicemapper/mnt/298bbecec47d3c707a4b6288ae8e075e374239432a54d8f4e2aad835d827f4a2/rootfs/tmp .] failed: /usr/bin/tar: /var/lib/docker/devicemapper/mnt/298bbecec47d3c707a4b6288ae8e075e374239432a54d8f4e2aad835d827f4a2/rootfs/tmp: Cannot chdir: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
: exit status 2

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@30
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@29
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: runtime
File: asm_amd64.s@2232
FATA[0001] Error response from daemon: : exit status 2
```

```
[root@ose3-master beta4]# osc version
osc v0.5.2.2-11-g4efd399
kubernetes v0.17.1-804-g496be63
```

**Comment by bparees** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1223662

**Comment by derekwaynecarr** [comment]
I guess my fedora 21 and docker 1.6 Kube setup did work and it was just the image that was the problem.  I am ashamed to say how much time I spent trying to debug this exact same issue.

**Comment by ncdc** [comment]
There is a tmpfs issue with our Docker RPM, and our hello-openshift binary needs to be built statically. Once both of those are fixed, the image will work again.

**Comment by derekwaynecarr** [comment]
Do you know if this affects many other images?  I had a pull to migrate upstream Kube vagrant setup to F21 and docker 1.6, but found issues with this and with selinux mounting /usr which we do with Kube-apiserver pod.

**Comment by ncdc** [comment]
The tmpfs issue appears to affect images built from scratch that are single binary images without a tmp dir (I think). Not sure what other images may have issues. I'd talk to Dan Walsh about the /usr selinux issues.

**Comment by bparees** [comment]
@ncdc are you saying we need to do "go build -ldflags '-d'" to construct the binary?

I tried that and now i just get a cryptic:
$ docker run hello
FATA[0002] Error response from daemon: : exit status 2  

but perhaps that's progress.

**Comment by derekwaynecarr** [comment]
Ben I had seen both errors in my own use.  It appeared to be related to whether it was after a first pull of the image, or a subsequent run for me which made no sense at the time.

**Comment by ncdc** [comment]
@bparees either build with `-tags netgo` or install glibc-static prior to building.

**Comment by bparees** [comment]
i've pushed a staticly built version that works with "docker run -v /tmp:/tmp openshift/hello-openshift"

but we still need the /tmp problem fixed to fully solve this.

for now i'll update the pod definition to define a volume for tmp.

**Comment by bparees** [comment]
@thoraxe please retry after 2700 merges.

**Comment by bparees** [comment]
neither installing glibc-static nor using the --tags netgo flag create a static binary on centos7.  still digging in to see if that's a known issue/limitation.

**Comment by bparees** [comment]
@vbatts might need your assistance here, seems like it has something to do with how the centos golang package is build vs the fedora one  (CGO_ENABLED=0)
https://groups.google.com/forum/#!topic/golang-nuts/S2WDcm47bhA

**Comment by vbatts** [comment]
Try `-installsuffix netgo`? ( from https://groups.google.com/forum/m/#!topic/golang-dev/JKM7UaKRT6g )
I'll need test debug this on a centos7 machine

**Comment by bparees** [comment]
@vbatts awesome that worked, thanks... now to figure out how to bolt custom build args into our build release flow.

**Comment by vbatts** [comment]
Good to hear.

**Comment by bparees** [comment]
fixed.
