### ISSUE TITLE
Wanted: osc command that shows only builder images in a namespace

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#2583]
I had a couple requests today for an analog for `rhc cartridge-list` -- seems like this might be a virtual resource on top of image stream that is only streams w/ the builder annotation.

**Comment by derekwaynecarr** [comment]
Annotation or label?  Seems like we could have a namespaced label and if there it would be a simple label selector query

**Comment by pmorie** [comment]
I was thinking annotation because there's already an annotation.

**Comment by derekwaynecarr** [comment]
Prefer label.  Seems like a good use case for a label to be honest.

**Comment by smarterclayton** [comment]
This is just variants of osc get image streams.  The columns for an IS should show this info.

**Comment by bparees** [comment]
have heard no recent requests for this
