### ISSUE TITLE
Wanted: show replica count / current number of pods in deployment view

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#2584]
This view should show the current replica count for the deployed RC and pod count.

http://www.screencast.com/t/sIG8C83OP0

**Comment by spadgett** [comment]
This is available in the browse deployments page, but easy enough to add to the overview.

From browse deployments:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8012955/4630340c-0b93-11e5-889e-fc42a78b4f4e.png)
