### ISSUE TITLE
Retryable deployment hooks can't be cancelled

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#2592]
https://github.com/openshift/origin/pull/2582 implements the majority of the work needed to support cancelling deployments, hooks, and any other related pods for a deployment. However, a new bug with the cancellation mechanism is exposed: hook retries are implemented by automatically starting a new hook pod when the previous pod fails. This means the hook can't be cancelled.

Hook pod names should be deterministic (https://github.com/openshift/origin/issues/2556). The hook retry logic might need to delete the hook pod in order to recreate it (similar to the approach for deployment itself in https://github.com/openshift/origin/issues/2558).

Automatically deleting the hook pod means the failed containers will be lost. This is acceptable for deployments since the delete is essentially user-initated, but in this scenario the delete will be automated, leaving no opportunity for the user to inspect the container of the failed hook.

Are there any other approaches for implementing retryable hooks? If we can't do it safely, we could consider removing support for hook retries altogether.

**Comment by ironcladlou** [comment]
cc @abhgupta @smarterclayton

**Comment by ironcladlou** [comment]
Spoke with @abhgupta and we thought of a way to handle retries sanely. Basically, when the Retry hook policy is set, we'll translate that to a pod OnFailure restart policy. This means the kublet will handle retrying the failed hook up until the hook deadline expires. We can then remove all manual retry handling and have correct deadline integration.

Since the retryable policy won't retry forever (due to deadlines), we'll assume (and document) that the hook should cause the deployment to abort if the hook pod failure reason is a deadline expiration.

**Comment by smarterclayton** [comment]
Very clean.  Awesome.
