### ISSUE TITLE
Retry pushing of the result image after successful build

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2593]
We've seen a lot of flake tests that fails because the push failed for random reason, like this:

```console
Failed to push image: Error pushing to registry: lstat /var/lib/docker/devicemapper/mnt/a644a10c6b42fa825e2d5e4221913ad9dd20cf5fdb221dc640cba94ded951784/rootfs/usr/include/signal.h: input/output error
Build error: Failed to push image: Error pushing to registry: lstat /var/lib/docker/devicemapper/mnt/a644a10c6b42fa825e2d5e4221913ad9dd20cf5fdb221dc640cba94ded951784/rootfs/usr/include/signal.h: input/output error
```

When this happen and the build retries, it fails as well:

```console
Failed to push image: API error (500): push 172.30.84.128:5000/test/origin-ruby-sample is already in progress
Build error: Failed to push image: API error (500): push 172.30.84.128:5000/test/origin-ruby-sample is already in progress
```

We should retry the first push if possible (and perhaps make the # of retries configurable, with some sane default).

**Comment by mfojtik** [comment]
@ncdc @soltysh @smarterclayton FYI

**Comment by ncdc** [comment]
I know we can't prevent users from running `osc start-build` multiple times, but in the e2e test it would be nice to figure out why this happens. The 2nd build's error that it couldn't push because another push was already in progress means that there really was another push in progress. This means that 2 builds were both running at the same time, as best I can tell. I'd like to figure out why that happens.

**Comment by mfojtik** [comment]
@ncdc I just realized that retrying push in build container won't help in this particular case as it will fail till the other build finish pushing.
However I still think that retry push is valuable especially when the registry is temporarily down and you don't want to restart the whole build just to retry the push (think that build can take long time in case if jboss apps...)

**Comment by ncdc** [comment]
@mfojtik retry can help. If you have 2 builds going at the same time, 1 starts pushing, the 2nd fails b/c of the 1st in-progress push. If the 2nd waits long enough (until the 1st push is done), it could push successfully.

**Comment by smarterclayton** [comment]
I'm not opposed to retrying once or twice, but agree with Andys concern around understanding why there are two builds.  It's probably because the build is being triggered automatically by image import (it should *always*) trigger

**Comment by mfojtik** [comment]
@smarterclayton if this is 3.0 item, I can add retries into builder on Monday

**Comment by smarterclayton** [comment]
It's not

**Comment by bparees** [comment]
if it's not a 3.0 item it should be p3.  But I think @mfojtik has started a fix for this anyway.

**Comment by mfojtik** [comment]
@bparees this is post-3.0... my fix is just temporary and we will eventually get something more intelligent in future :-)

**Comment by mfojtik** [comment]
@bparees we can keep this closed for how, I created trello card to track this: https://trello.com/c/HcTaBOvI/589-make-push-retries-more-intelligent-future-build
