### ISSUE TITLE
Customize OpenShift route HTTP redirection status code

### ISSUE THREAD

**Issue by scoulomb** [openshift/origin#25937]
Customize OpenShift route HTTP redirection status code

##### Version

OpenShift 3.11 

##### Steps To Reproduce

Use OpenShift route with `insecureEdgeTerminationPolicy` set to `Redirect`.

##### Current Result

OpenShift route redirection always returns a `302 Found`.

##### Expected Result

Would it be possible to tune the status code, in order to return a `HTTP`  `301`, `303`, `307` or `308`.

##### Additional Information

Why?

In my specific use-case I use a route, where it returns a `302`, several http client change the `PUT/POST` to a `GET` or alter the body.
I would like to use a `HTTP 307` to prevent this issue.

See mdn: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307

> **The only difference between 307 and 302 is that 307 guarantees 
> that the method and the body will not be changed when the redirected request is made.
> With 302, some old clients were incorrectly changing the method to GET**: 
> the behavior with non-GET methods and 302 is then unpredictable on the Web, whereas the behavior with 307 is predictable. For GET requests, their behavior is identical.

See also: https://stackoverflow.com/questions/66464822/openshift-route-to-return-a-308-permanent-redirect

**Comment by tobixen** [comment]
While this may not be the top priority to fix, I don't think this is a rotten issue.
