### ISSUE TITLE
Inconsistent trigger name capitalization

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#2594]
API v1 BuildConfigs have triggers: `github`, `generic`, `imageChange` ([source](https://github.com/openshift/origin/blob/a72d50170d7b38f0d3777dc4e80f7680a3c5683c/pkg/build/api/v1/types.go#L332-L344)), while DeploymentConfigs have: `ImageChange`, `ConfigChange` ([source](https://github.com/openshift/origin/blob/a72d50170d7b38f0d3777dc4e80f7680a3c5683c/pkg/deploy/api/v1/types.go#L226-L233)).

**Comment by rhcarvalho** [comment]
@smarterclayton @bparees PTAL

**Comment by smarterclayton** [comment]
Constants should be CamelCase (type), fields should be camelCase

**Comment by rhcarvalho** [comment]
I'm referring to what end up as values for trigger types in JSON.
BuildConfigs and DeploymentConfigs' triggers differ in how their trigger names are capitalized.

@smarterclayton if we take [one template JSON file](https://github.com/openshift/origin/blob/b690eb9f8fb61f1c8d2c86f8c611f8a3248a9458/examples/sample-app/application-template-stibuild.json) as example:

```
{
  "items": [
    ...
    {
      "kind": "BuildConfig",
      ...
      "triggers": [
        ...
        {
          "imageChange": {},
          "type": "imageChange"                      ## why here it is *imageChange*
        }
      ]
    },
    {
      "kind": "DeploymentConfig",
      ...
      "triggers": [
        {
          "imageChangeParams": {
            "automatic": true,
            "containerNames": [
              "ruby-helloworld"
            ],
            "from": {
              "name": "origin-ruby-sample"
            },
            "tag": "latest"
          },
          "type": "ImageChange"                      ## while here it is *ImageChange*?
        },
        {
          "type": "ConfigChange"
        }
      ]
    },
   ...
  ],
 ...
}
```

Why one trigger is called "imageChange" with lowercase i, and the other is "ImageChange" with uppercase I?

**Comment by smarterclayton** [comment]
----- Original Message -----
> I'm referring to what end up as values for trigger types in JSON.
> BuildConfigs and DeploymentConfigs' triggers differ in how their trigger
> names are capitalized.
> 
> @smarterclayton if we take [one template JSON
> file](https://github.com/openshift/origin/blob/b690eb9f8fb61f1c8d2c86f8c611f8a3248a9458/examples/sample-app/application-template-stibuild.json)
> as example:

This is a bug in build configs, but needs to be handled only in v1beta3 (via a conversion) and @liggitt needs to be aware.

**Comment by liggitt** [comment]
@spadgett fyi if a fix for this happens in v1beta3, we need to update the UI here:
```
      if(input.buildConfig.buildOnImageChange){
        triggers.push({
          imageChange: {},
          type: "imageChange"
        });
      }
```

**Comment by rhcarvalho** [comment]
It's not clear to me what would be the right trigger names in JSON.

1. github, generic, imageChange, configChange
2. Github, Generic, ImageChange, ConfigChange
3. gitHub, generic, imageChange, configChange
4. GitHub, Generic, ImageChange, ConfigChange

1, 2, 3 or 4? ([GitHub](https://help.github.com/) is spelled with capital H)

**Comment by bparees** [comment]
@rhcarvalho sounds like @smarterclayton wants Generic, ImageChange, ConfigChange and I guess we better do GitHub.

so 4.
