### ISSUE TITLE
Remove registry/router from `openshift ex`

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#2596]
@smarterclayton is there any reason why it remains experimental?

**Comment by liggitt** [comment]
`registry` and `router` have already been added under `osadm`.

**Comment by liggitt** [comment]
need to sweep docs/examples to make sure all references point to `osadm ...`

**Comment by kargakis** [comment]
So these two commands are not going to be a part of `osc` right? I can remove them and replace all `ex` references.

**Comment by liggitt** [comment]
right, those are admin commands, so `osadm`
