### ISSUE TITLE
osc edit should handle users editing name

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#2601]
I see two possible outcomes:
1. reject changes to name outright with a good message
2. create a new object with the new name, but everything else the same.  delete the old object

I like option 2 better, because I just tried to do that without thinking about it.  Perhaps a confirmation of the creation of a deletion of the old and creation new object to make sure the user really means it.

**Comment by liggitt** [comment]
option 3: create, leave old object

**Comment by derekwaynecarr** [comment]
I have issues with all 3 options.  What should happen with uid?

**Comment by liggitt** [comment]
ok, I like option 1 the best now.

**Comment by smarterclayton** [comment]
The code should be rejecting name changes

**Comment by smarterclayton** [comment]
That was the original intended behavior (and may have even worked, briefly)

**Comment by derekwaynecarr** [comment]
I am good with 1 as well.

**Comment by deads2k** [comment]
> I have issues with all 3 options.  What should happen with uid?

Option 1 is fine, but why is the UID for creation any more complicated than clearing it?  Shouldn't the API server do that automatically anyway?

**Comment by smarterclayton** [comment]
I just don't want to add it yet.  We can come back to it post 3.0

**Comment by smarterclayton** [comment]
Option 4: do nothing about this for 1.5 years and then close.  Sold!
