### ISSUE TITLE
Build ImageChangeController is racy

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#2604]
Example race scenario with the code as it is today:
1. The build triggers on changes to the ruby-20-centos7 image stream
2. The ruby-20-centos7 image stream has spec.dockerImageRepository set to point at a repo on the Hub
3. The image ImportController pulls down information about openshift/ruby-20-centos7 and posts an ImageStreamMapping for each tag, creating multiple watch events for the image stream
4. The build ImageChangeController only watches for changes to the image stream, so it gets multiple events
5. When it sees the first event, the ImageChangeController makes an API request to the BuildGenerator to instantiate a build. This makes 2 updates to etcd:
   1. Create a new build
   2. Update the build config, bumping LastVersion and the image change trigger's LastTriggeredImageID
6. If there are multiple events for the same ImageStream and they arrive quickly enough, it's possible for the ImageChangeController to determine `shouldBuild=true` because its cache of BuildConfigs is slightly stale, and it hasn't seen the update to LastTriggeredImageID yet
7. In our case, openshift/ruby-20-centos7 has multiple tags (latest, v0.4), so 2 events are generated fairly quickly. Additionally, when it's finished processing all of an image stream's tags, the image ImportController performs 1 more update to the stream to indicate that it's completed the import. This means there are 3 image stream updates that the ImageChangeController could potentially react to

Proposed fix:
1. When the ImageChangeController determines a new build is needed, the **only** thing it does is try to update the BuildConfig's LastVersion and LatestTriggeredImageID
2. (optional???) Add a new config change controller for BuildConfigs that updates the LastVersion if a config change is detected
3. Modify the webhook controller to update the LastVersion instead of calling Instantiate
4. Add a new controller that watches for changes to BuildConfigs
   1. For every BuildConfig event, as long as LastVersion != "", try to create a Build
5. Remove BuildGenerator (do we need to update Eclipse?)

Questions:
1. If any of the attempts to bump LastVersion fail, should they be retried?

**Comment by ncdc** [comment]
@smarterclayton @bparees @mfojtik @danmcp @ironcladlou @pmorie @deads2k @liggitt @soltysh

**Comment by ironcladlou** [comment]
I can't yet think of a reason not to retry BC update failures (other than conflict/notfound).

**Comment by ncdc** [comment]
@ironcladlou for a conflict, should it get the latest, apply the bump changes, and try to resubmit?

**Comment by smarterclayton** [comment]
In the future we would also change webhooks to only update the source revision part of the bc, which would result in a leve driven source build and dedup multiple hooks for the same source

**Comment by ncdc** [comment]
Which would be handled by a config change controller?

**Comment by smarterclayton** [comment]
The build controller notices the build config # doesn't match.

**Comment by ironcladlou** [comment]
@ncdc 
> for a conflict, should it get the latest, apply the bump changes, and try to resubmit?

Would throwing a retryable error for the ImageStream be fine? If the BuildConfig still needs updated next time through, then the version will get bumped appropriately, or no-op otherwise.

**Comment by ncdc** [comment]
@ironcladlou I think that would work, although it would have to do it at the end of the loop instead of restarting early, as we discussed previously.

**Comment by ironcladlou** [comment]
@ncdc 
>@ironcladlou I think that would work, although it would have to do it at the end of the loop instead of restarting early, as we discussed previously.

Yeah, efficiency penalty no-op'ing through everything over again, but it *should* be consistent. Or we could drop the failed event and just miss the build if the confidence level in the re-processing is low.

**Comment by ncdc** [comment]
> In the future we would also change webhooks to only update the source revision part of the bc, which would result in a leve driven source build and dedup multiple hooks for the same source

I think we need to figure out something for this. We are currently including the revision in the BuildRequest that the webhook controller passes to the BuildGenerator, and that revision is persisted on the Build but not on the BuildConfig.

If we get rid of the BuildGenerator and BuildRequests, we need some way to include the revision in the Build that gets generated. Maybe we need a LastTriggeredRevision in the webhook triggers?

**Comment by ncdc** [comment]
I'm going to start prototyping this. Let's decide on Monday if we want to proceed with this kind of approach, or if there's something simpler that can work short term.

**Comment by smarterclayton** [comment]
Ben proposed writing the BC prior to starting the build, which would get us past 3.0.  That's something that someone on dev exp can look at Monday morning.

**Comment by smarterclayton** [comment]
Why would we get rid of build request?  It would just mutate BC.

We have a field for this - it's sourcerevision.

**Comment by ncdc** [comment]
That still doesn't solve the stale cache problem though, does it?

**Comment by ncdc** [comment]
BuildRequest is only used by the BuildGenerator to start a build, and it includes the revision info. The generator copies the revision to the new Build. I don't think we'll want BuildRequest any more.

**Comment by smarterclayton** [comment]
Yes, to trigger a build on a build config

**Comment by ncdc** [comment]
Could you describe that in more detail?

**Comment by smarterclayton** [comment]
I'm a client.  I want to build x based on a source repo.  Build request is a virtual resource that when you post to it updates the bc correctly.

**Comment by soltysh** [comment]
>The build ImageChangeController only watches for changes to the image stream, so it gets multiple events

Shouldn't that controller watch for events on specific resources allowed in From field, that will be ImageStreamImage, ImageStreamTag and DockerImage?

The whole purpose of BuildGenerator was to create single place where all builds are created, at certain point in time we have 3 or even 4 such places, each creating builds slightly differently which was really hard to maintain. I'll be the first defending that solution as I was fighting hard to introduce that solution.

**Comment by smarterclayton** [comment]
> On May 29, 2015, at 3:20 PM, Maciej Szulik <notifications@github.com> wrote:
> 
> The build ImageChangeController only watches for changes to the image stream, so it gets multiple events
> 
> Shouldn't that controller watch for events on specific resources allowed in From field, that will be ImageStreamImage, ImageStreamTag and DockerImage?
> 
> The whole purpose of BuildGenerator was to create single place where all builds are created, at certain point in time we have 3 or even 4 such places, each creating builds slightly differently which was really hard to maintain. I'll be the first defending that solution as I was fighting hard to introduce that solution.
> 
The proposal changes so that only one place creates builds - a build controller.  At that point no one else creates builds.  Creating builds from multiple locations is part of the problem, not the solution.

**Comment by soltysh** [comment]
>The proposal changes so that only one place creates builds - a build controller.  At that point no one else creates builds.  Creating builds from multiple locations is part of the problem, not the solution.

That's what I've meant, I'll be fighting to defend that solution. I was rather proposing limiting the amount of events the ImageChangeController is getting by not listening to ImageStream but specific object such as ImageStreamImage or ImageStreamTag, I'm not suer DockerImage allows that option.

**Comment by smarterclayton** [comment]
The solution is to use a level driven patrern

> On May 29, 2015, at 3:42 PM, Maciej Szulik <notifications@github.com> wrote:
> 
> The proposal changes so that only one place creates builds - a build controller. At that point no one else creates builds. Creating builds from multiple locations is part of the problem, not the solution.
> 
> That's what I've meant, I'll be fighting to defend that solution. I was rather proposing limiting the amount of events the ImageChangeController is getting by not listening to ImageStream but specific object such as ImageStreamImage or ImageStreamTag, I'm not suer DockerImage allows that option.
> 
That's not really going to fix the problem, just move it around and reduce the frequency.  Ultimately, a user requests a build and gets a build object.  Since we already update the build config to change the version and last image id, we're already matching the DC pattern.  Basically a request modifies the BC, and the result of that modification is a new build created.  The build controller does the latter, image change, webhooks, and manual build requests do the former.

**Comment by ncdc** [comment]
> I'm a client.  I want to build x based on a source repo.  Build request is a virtual resource that when you post to it updates the bc correctly.

I think we're ultimately basically on the same page, and I see your point that it's useful for a client to be able to request a build of a specific revision.

We're not currently ever modifying BuildConfig...Revision, even via the BuildRequest. The BuildGenerator takes the Revision from the BuildRequest and sets it on the new Build, but not on the BuildConfig. So my question still stands - when a client says I want to build Revision X, and they put it on a BuildRequest, what actually triggers the BuildConfigController to create a Build? And how does it know what revision to build?

**Comment by smarterclayton** [comment]
> On May 29, 2015, at 7:25 PM, Andy Goldstein <notifications@github.com> wrote:
> 
> I'm a client. I want to build x based on a source repo. Build request is a virtual resource that when you post to it updates the bc correctly.
> 
> I think we're ultimately basically on the same page, and I see your point that it's useful for a client to be able to request a build of a specific revision.
> 
> We're not currently ever modifying BuildConfig...Revision, even via the BuildRequest. The BuildGenerator takes the Revision from the BuildRequest and sets it on the new Build, but not on the BuildConfig. So my question still stands - when a client says I want to build Revision X, and they put it on a BuildRequest, what actually triggers the BuildConfigController to create a Build? And how does it know what revision to build?
> 
Today?  Or in the future?  In the future, build request should modify the BC and set source revision onto the spec.  That would then be propagated.  The goal is for the BC to represent the desire for a build to exist representing a set of parameters, and hooks, requests, and image changes the BC.

**Comment by ncdc** [comment]
I'd say both today (so we can fix this for 3.0) and in the future so we know what to do long term.

**Comment by bparees** [comment]
keep in mind a level driven solution loses one of the current behaviors which is that you're guaranteed a build for every image change (or code change), not just the last one.  It sounds like we're ok losing that behavior, but it's an important distinction imho.

**Comment by smarterclayton** [comment]
Beyond just release risk there's also the slightly unusual behavior of the API.  I'd also want to discuss how we do build queuing in the new model.

**Comment by bparees** [comment]
@ncdc the cache staleness issue could be solved by doing an explicit get of the BuildConfig for "well qualified" BuildConfigs that we find in the cache, before concluding shouldBuild=true.  What do you think?

**Comment by soltysh** [comment]
I'm backing @bparees idea of enot changing the behavior where each change (source/image) triggers a build. IMHO we should focus on fixing the cache or its contents. Is there a chance to invalidate value from the cache, that would allow us to use @bparees's idea of "well qualified" BC. Eventually we could force update of a value in cache, but that's too much overkill, because we'd do that for every BC update, the former solution seems less overkill.

**Comment by ncdc** [comment]
That could certainly work. Let's talk tomorrow.

**Comment by ncdc** [comment]
You can't invalidate the cache easily across multiple controllers (HA setup).

**Comment by bparees** [comment]
Working around this by double-checking the imageid value before launching the build here:
https://github.com/openshift/origin/pull/2654

lowering this to p3 so we can come back and do the refactor of the algorithm post 3.0.

**Comment by smarterclayton** [comment]
Closing due to age.
