### ISSUE TITLE
segmentation fault on apple m1

### ISSUE THREAD

**Issue by hjchanna** [openshift/origin#26108]
The `oc` command fails with the error message `segmentation fault` on ARM based Apple M1 Macbook Pro.

##### Version
openshift-origin-client-tools-v3.11.0-0cbc58b-mac

##### Steps To Reproduce
1. Just run the oc command

##### Current Result
[1]    13704 segmentation fault  ./oc

**Comment by fathiraz** [comment]
any update with this?

**Comment by JCzz** [comment]
Any alternatives?

**Comment by androidfanatic** [comment]
+1

**Comment by shahzebs** [comment]
Try installing it via homebrew. I think the issue is in the 3.x version of oc and not M1 in particular. Homebrew ships with version 4.x. I am using it with an OpenShift cluster at version 3.11 and the client works fine at version 4.x.

**Comment by thygesen** [comment]
+ 100

**Comment by sudharsanpunniyakotti** [comment]
+1

**Comment by aldokkani** [comment]
+1

**Comment by xiaosTyy** [comment]
> Try installing it via homebrew. I think the issue is in the 3.x version of oc and not M1 in particular. Homebrew ships with version 4.x. I am using it with an OpenShift cluster at version 3.11 and the client works fine at version 4.x.

still doesn't work, has your mac m1 been resolved?

**Comment by JasonHao123** [comment]
sadly, +1

**Comment by janimikael** [comment]
+1

**Comment by Reuber-Parreira** [comment]
+1

**Comment by Reuber-Parreira** [comment]
brew install openshift-cli
