### ISSUE TITLE
Trigger build on BuildConfig changes

### ISSUE THREAD

**Issue by tmds** [openshift/origin#26172]
Changes to the BuildConfig don't trigger new builds.

The docs have a comment about this:
> Configuration change triggers currently only work when creating a new BuildConfig. In a future release, configuration change triggers will also be able to launch a build whenever a BuildConfig is updated.

Is this feature planned?

I'm trying some things with `helm` and OpenShift, and it feels weird that `helm upgrade` is not enough to apply changes. An additional `oc start-build` is needed to manually start a build.

cc @bparees

**Comment by bparees** [comment]
> Is this feature planned?

at this point i'd say it's unlikely that the configchangetrigger will evolve further.

cc @adambkaplan in case he's aware of plans that i am not
