### ISSUE TITLE
URL of generic webhook copied to clipboard lacks secret on build page

### ISSUE THREAD

**Issue by miminar** [openshift/origin#2618]
On web console with URL https://os-master.miminar.local:8443/console/project/wiring/browse/builds
a generic webhook's URL stored to clipboard with a button click is invalid because it lacks secret:

    https://os-master.miminar.local:8443/osapi/v1beta1/buildConfigHooks/ruby-sample-build//generic?namespace=wiring

Correct URL which is exposed with a click on "Show URL" is:

    https://os-master.miminar.local:8443/osapi/v1beta1/buildConfigHooks/ruby-sample-build/secret101/generic?namespace=wiring

OpenShift version:

    $ osc version
    osc v0.4.3.2-141-g3a39f33
    kubernetes v0.14.1-582-gb12d75d

**Comment by mfojtik** [comment]
@mnagy PTAL

**Comment by spadgett** [comment]
@csrwng didn't you look at a similar problem?

**Comment by spadgett** [comment]
See #2368
