### ISSUE TITLE
Duplicate CORS headers when proxying service requests

### ISSUE THREAD

**Issue by rhuss** [openshift/origin#2619]
When a proxied backend set CORS headers on their own, they get not removed when the OpenShift proxy sets his `Allow-Origin` header. This results in duplicate headers, which makes the browser croak. 

It seems, that this [code](https://github.com/openshift/origin/blame/945fb793cf68ba3836a75239b14b05fcbe44427a/pkg/util/httpproxy/upgradeawareproxy.go#L249-L256) is not called when doing a proxy request.

See fabric8io/fabric8#4033 for details.

**Comment by liggitt** [comment]
That code only applies when OpenShift is proxying to an external Kubernetes.
When Kube itself is proxying a pod, it needs to do something similar. That needs to happen in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/generic/rest/proxy.go

@csrwng

**Comment by rhuss** [comment]
This was indeed fixed for OpenShift V3 1.0.0 but now we have again the very same issue. I don't know whether it's an problem with OpenShift or Kubernetes Proxy, but using an URL like `https://vagrant.f8:8443/api/v1/proxy/namespaces/fabric8/pods/quickstart-war-camel-servlet-57drd:8778/jolokia/` results in the following request & response headers which which makes the browser barf:

![image](https://cloud.githubusercontent.com/assets/99080/8874241/70838752-320f-11e5-881c-8ef956176bfb.png)

**Comment by rhuss** [comment]
Can we please reopen this issue ?

**Comment by rhuss** [comment]
The versions use are:

````
oc v1.0.3
kubernetes v1.0.0
````

**Comment by liggitt** [comment]
I'm pretty sure the `/api/v1/proxy/...` and `/api/v1/namespaces/n/pods/p/proxy` calls use different proxy code. You should almost certainly use the latter, since the top level proxy is restricted to cluster admins. 

Can you verify the latter still works correctly? @csrwng, can you open a separate issue for fixing CORS headers in the top-level proxy?

**Comment by rhuss** [comment]
Thanks, will check that out ASAP (need some changes here to bubble through).

**Comment by rhuss** [comment]
I can confirm that when using the namespaced proxy URL that the CORS headers are filtered out correctly:

![image](https://cloud.githubusercontent.com/assets/99080/8888792/d414cf80-32bc-11e5-81ed-46a218ff5484.png)

Thank you ...
