### ISSUE TITLE
builder images matches docker credentials differently

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#2624]
The Kubelet matches docker credentials based on docker keyring logic that includes partial matches.  The builder images does not.  It should be updated.  See https://github.com/openshift/origin/blob/master/pkg/build/builder/cmd/dockercfg/cfg.go#L62  and https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/credentialprovider/keyring.go#L129 .

@bparees I'd call this p2.

**Comment by mfojtik** [comment]
we have this logic already in https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L346 for ServiceAccount secrets... This matching is done only when you manually specify the PushSecret or PullSecret which in that case there is (IMHO) no need to go via keyring.

**Comment by deads2k** [comment]
I'm not very familiar with the build code paths, but this looks like it would allow me to create a pull secret that works for regular image pulls, but fail when using it for a build because it matches URLs differently.  Is that not the case?

**Comment by mfojtik** [comment]
@deads2k yeah, I will rework that to use the same pattern as we use in generator (just with one secret)

**Comment by deads2k** [comment]
(I stumbled onto this when I realized that the deserialization path doesn't match the kube deserialization path: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/credentialprovider/config.go#L159 .  I figured you'd get both at once, but I can make a new issue if you prefer.

**Comment by bparees** [comment]
fixed.
