### ISSUE TITLE
Improve error message in `osc new-app`

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#2625]
```bash
$ osc new-app https://github.com/openshift/django-ex
error: No search terms were specified.
$ osc new-app https://github.com/openshift/django-ex --loglevel=2 
F0601 12:46:18.278174   17575 newapp.go:80] error: No search terms were specified.
```
Apparently `new-app` did not detect that the repo contains a Python app. I'd expect the message to be more clear about that.

[This](https://github.com/openshift/origin/blob/2e53c1fe514ebecdeb7b9eda526c747c9dcbb54e/pkg/generate/app/cmd/newapp.go#L506) is the line reported in the error message.

`new-app` works fine if I prefix the repo with a Python image:

```bash
$ osc new-app openshift/python-33-centos7~https://github.com/openshift/django-ex
imageStreams/python-33-centos7
imageStreams/django-ex
buildConfigs/django-ex
deploymentConfigs/django-ex
services/django-ex
A build was created - you can run `osc start-build django-ex` to start it.
Service "django-ex" created at 172.30.16.213 with port mappings 8080.
```

**Comment by kargakis** [comment]
new-app currently doesn't support detecting Python source code.

**Comment by kargakis** [comment]
@smarterclayton @csrwng we should probably hardcode all of our images in our searcher for now until [this](https://github.com/openshift/origin/blob/6f3776993b7ac4b6c2340878f0e79f85ddc0648a/pkg/generate/app/builder.go#L27) happens.

**Comment by smarterclayton** [comment]
If rather fix the problem since its on the punch list

**Comment by csrwng** [comment]
related to https://github.com/openshift/origin/issues/1878
