### ISSUE TITLE
Security Context Constraints

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#2626]
This issue tracks items for SCCs that are lower priority than the go path use case for 3.0.  Add items here that need addressed but are not must-haves for launch.

HostNetworkSources - migrate into SCC from capabilities.go

related PR https://github.com/openshift/origin/pull/2609

**Comment by pweil-** [comment]
> What admission is happening on the kubelet? Shouldn't it assume the context in the pod has been validated? That's how other admission bits (quota, secret usage, etc) work

The only piece that requires kubelet information to work would be the use case of "run as non-root" but not having preallocated uids.  In this case, the user may submit a pod with no `RunAsUser` specified and be expecting the image to container a `USER` directive that the kubelet would need to check and ensure is non-root.  If that use case is not required then we're fine with not changing the kubelet's `CanRunPod` method for now.

**Comment by pweil-** [comment]
remove omitempty from the bool fields so they are shown in the `-o json` output.  re: https://github.com/openshift/origin/pull/2863#issuecomment-110090148

**Comment by smarterclayton** [comment]
Support and document the following modes naturally:

1. Administrator enables a specific namespace to run containers that can run as any user, just not privileged.  UIDs are not defaulted or mapped.  Can set that as the installation default.
2. Administrator enables a namespace to run containers that can run as any non-root user, or sets that as the installation default.

**Comment by pweil-** [comment]
Control ability to set host ports

**Comment by pweil-** [comment]
Code item summary and PRs:

1.  HostNetwork: https://github.com/openshift/origin/pull/3496
2.  RunAsNonRoot: https://github.com/openshift/origin/pull/3481
3.  HostPorts: in progress - eta 30 Jun
4.  Add new start flag for pre-canned sets of SCC strategies to support the configurations mentioned in https://github.com/openshift/origin/issues/2626#issuecomment-112948013.  Ie. `openshift start --scc-strategy=[pre-allocated (today's default)|non-root|noPrivileged|...]`.  Will discuss to ensure I'm interpreting this requirement correctly.  The modes described are functioning with the current code and PRs.

Documentation tasks
1.  Describe common modes of SCC sets as described in https://github.com/openshift/origin/issues/2626#issuecomment-112948013

**Comment by smarterclayton** [comment]
On Jun 29, 2015, at 3:18 PM, Paul Weil <notifications@github.com> wrote:

Code item summary and PRs:

   1. HostNetwork: #3496 <https://github.com/openshift/origin/pull/3496>
   2. RunAsNonRoot: #3481 <https://github.com/openshift/origin/pull/3481>
   3. HostPorts: in progress - eta 30 Jun
   4. Add new start flag for pre-canned sets of SCC strategies to support
   the configurations mentioned in #2626 (comment)
   <https://github.com/openshift/origin/issues/2626#issuecomment-112948013>.
   Ie. openshift start --scc-strategy=[pre-allocated (today's
   default)|non-root|noPrivileged|...]. Will discuss to ensure I'm
   interpreting this requirement correctly. The modes described are
   functioning with the current code and PRs.

I think we need more than this - something that ties it to project or
service account.  The global flag either won't work after restart, or would
potentially overwrite user input.  If we went down that route, we'd be back
to the earlier proposal of the "default" SCC applied to each project, with
admins able to override per project.  The use cases I'm hearing are all dev
focused (I want to demo this for a regular docker image), not addressing
real customers at scale (no admin wants to make root containers the default
unless they're crazy).



Documentation tasks
1. Describe common modes of SCC sets as described in #2626 (comment)
<https://github.com/openshift/origin/issues/2626#issuecomment-112948013>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2626#issuecomment-116801380>.

**Comment by pweil-** [comment]
PRs for hostnetwork/hostport/non-root have merged.  Closing
