### ISSUE TITLE
End to end tests fail due to selinux denials

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#263]
In some fedora environments hack/test-end-to-end.sh fails due to selinux denials:

https://gist.github.com/jwforres/a68a4109d05185fca4d5
https://gist.github.com/jwforres/4181fb02b2af85b16510
https://gist.github.com/jwforres/684e557ed2ef7dd248d9
https://gist.github.com/jwforres/dcdf702f081682b2cf36

**Comment by bparees** [comment]
refocusing this issue on the need to setenforce 0 to successfully access the bound docker socket.

The error looks like this:
https://gist.github.com/bparees/2f0781144a3b36e99831

Notice in that gist I attempted to bind the docker socket with :Z to do selinux relabeling but it appears to have had no effect.

**Comment by bparees** [comment]
I've been informed by Dan Walsh that mount based relabeling support is not there yet, so manual relabeling on the host is required.  Per the docker man page:
              To work around this, at time of writing this man page, the following com‐
              mand needs to be run in order for the proper SELinux policy type label to
              be attached to the host directory:

                     # chcon -Rt svirt_sandbox_file_t /var/db

                     Now, writing to the /data1 volume in the container will be allowed
                     and the changes will also be reflected on the host in /var/db.

However that does not seem to solve the problem either.

**Comment by rhatdan** [comment]
What is the latest problem?  Are you getting AVC's?

**Comment by bparees** [comment]
@rhatdan  yes:
type=SYSCALL msg=audit(1421362969.119:55204): arch=c000003e syscall=42 success=no exit=-13 a0=4 a1=c208041090 a2=17 a3=0 items=0 ppid=27224 pid=28343 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="openshift-sti-b" exe="/usr/bin/openshift" subj=system_u:system_r:svirt_lxc_net_t:s0:c99,c670 key=(null)
type=PROCTITLE msg=audit(1421362969.119:55204): proctitle="/usr/bin/openshift-sti-build"
type=AVC msg=audit(1421426370.601:55910): avc:  denied  { connectto } for  pid=26416 comm="openshift-sti-b" path="/run/docker.sock" scontext=system_u:system_r:svirt_lxc_net_t:s0:c71,c318 tcontext=system_u:system_r:docker_t:s0 tclass=unix_stream_socket permissive=0

 ls -lZ /var/run/docker.sock 
srw-rw----. root docker system_u:object_r:svirt_sandbox_file_t:s0 /var/run/docker.sock

**Comment by rhatdan** [comment]
Allowing a process within a container to connect to /var/run/docker.sock is the equivalent of turning off all security and running the process as root.

This is a bad idea, if necessary I would recommend you run this container --permissive.

**Comment by ncdc** [comment]
These are the containers OpenShift uses to perform builds, so they need access to the host's Docker socket.

**Comment by rhatdan** [comment]
Fine then run them in permissive mode or with selinux disabled for the container.

--security-opt=label:disabled

**Comment by rhatdan** [comment]
I meant --privileged mode.  If you can talk to docker, there is no security.  If users are able to run random scripts within the Dockerfile there is no security.

**Comment by smarterclayton** [comment]
Yes, this is why we'd have a docker proxy.  We also need docker build to be able to run in a secure context, and yum not to require root to run.  Basically, this is the list of things we've known for the last year that we need from Docker.

**Comment by smarterclayton** [comment]
We also need docker build to run in a cgroup (Ideally a child of the caller)

**Comment by smarterclayton** [comment]
I'll spawn a separate tracker upstream for this - I've gotten distracted with all the other security stuff, but this is the biggest hole in docker today.

**Comment by smarterclayton** [comment]
We can flip the builds back to being running privileged for now

**Comment by rhatdan** [comment]
I actually found a docker bug which we might want to fix.  Currently we are not transitioning to a confined domain when doing a docker build as opposed to a docker run.  I would like to fix this on Rawhide, but I am not sure if docker build needs more privs then docker run

**Comment by rhatdan** [comment]
This would be something you would probably want if you are going to allow users to upload their own Dockerfiles.

**Comment by smarterclayton** [comment]
Definitely.

**Comment by bparees** [comment]
@smarterclayton using privileged containers for the build pod gets through the build step, but the docker-registry container appears to also need to run privileged.

In addition, just enabling the privileged capability appears to require an upstream change, I don't see anywhere to feed this value in as a config setting on the cli:
https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/capabilities/capabilities.go#L49

**Comment by csrwng** [comment]
@bparees it's actually set in the command line https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kubelet/kubelet.go#L57 the line you point out above only executes if no Capabilities have been set. But they are set here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/standalone/standalone.go#L187

**Comment by bparees** [comment]
@csrwng that must be part of a rebase we haven't picked up yet, i was only looking in our vendored version.

**Comment by bparees** [comment]
I have for now resolved the selinux disable requirement by using privileged containers in this PR:
https://github.com/openshift/origin/pull/661

**Comment by smarterclayton** [comment]
Opened https://github.com/openshift/origin/issues/662 to track docker build being insecure

**Comment by smarterclayton** [comment]
And https://github.com/openshift/origin/issues/663 to make the registry unprivileged.

**Comment by danmcp** [comment]
What are the remaining issues here?

**Comment by bparees** [comment]
e2e passes with selinux enforcing in my f21 environment.  closing.
