### ISSUE TITLE
add descriptions to all v1 API resource fields across all APIs

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#2632]
https://github.com/openshift/origin/issues/2628

~~"github.com/openshift/origin/pkg/authorization/api/v1" (see pr)~~
~~"github.com/openshift/origin/pkg/build/api/v1" (see pr)~~
~~"github.com/openshift/origin/pkg/deploy/api/v1" (was already good)~~
~~"github.com/openshift/origin/pkg/image/api/v1" (see pr)~~
~~"github.com/openshift/origin/pkg/oauth/api/v1" (see pr)~~
~~"github.com/openshift/origin/pkg/project/api/v1" (see pr)~~
~~"github.com/openshift/origin/pkg/route/api/v1" (see pr)~~
~~"github.com/openshift/origin/pkg/sdn/api/v1" (see pr)~~
~~"github.com/openshift/origin/pkg/template/api/v1" (see pr)~~
~~"github.com/openshift/origin/pkg/user/api/v1" (see pr)~~

**Comment by smarterclayton** [comment]
Marking punch list closed (description unit test can finish after)
