### ISSUE TITLE
Support canary for rolling deployments

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#2637]
During rolling deployment, a canary check should be performed for the first new replica to avoid rolling out a bunch of broken replicas. Wait for the first replica, and fail the deployment if the pod doesn't start successfully. 

Outstanding design issues:

* Should there be a distinct timeout on `RollingDeploymentStrategyParams` for the canary check? The only possible existing parameter which could be reused is `TimeoutSeconds` which defaults to 120 seconds and is intended to represent the time to wait for a given replica count to be achieved (which is roughly analagous, but doesn't account for pod/container status).

This issue will require carring an upstream patch for the rolling updater.

Punch list item for https://github.com/openshift/origin/issues/2628.

**Comment by ironcladlou** [comment]
The upstream implementation supports continuing a partial rollout. So, should the canary check be performed when the target replica count is currently 1, or should we do the canary check once per rollout attempt (on the first iteration, so when replica count is either 1, or whatever the last count was the next time we try to resume a partial rollout)?

One problem with doing the check "the first scale-up regardless of the existing replica count" is that now we have to choose which container in the existing replica set to act as the canary. If we only check when the replica count is 1, we use the replicaSelector to find the pod. If the replica set could be >1, then how do we decide which pod in the set to consider the canary?

**Comment by ironcladlou** [comment]
cc @smarterclayton @abhgupta

**Comment by smarterclayton** [comment]
We should go up to 1 replica, wait for canary, then move on.

**Comment by abhgupta** [comment]
I believe that the readiness check for a "canary" is relevant only for the first pod. If the first pod for the RC passes that check, we don't need to repeat the check for subsequent pods. The check is aimed at validating the image (for the most part), and hence checking a single pod is sufficient.

**Comment by ironcladlou** [comment]
Agree, thanks.

**Comment by smarterclayton** [comment]
Well... in general, readiness IS relevant for rolling an update.  You shouldn't go from 0->1, then go from 1-50 without checking readiness.  Each *chunk* of rolling deployment should be judged by readiness.

----- Original Message -----

**Comment by ironcladlou** [comment]
>Well... in general, readiness IS relevant for rolling an update. You shouldn't go from 0->1, then go from 1-50 without checking readiness. Each *chunk* of rolling deployment should be judged by readiness.

Is there some way to know what RC was created when I'm doing a chunk and go from say 10 to 11? THe replica selector will match them all.

**Comment by smarterclayton** [comment]
Do you have pods available on only replica selectors?  Either way, after a chunk, get pods, check for ready.  We can just do the first chunk now in this pull, but the other chunks will bear relevant later.

----- Original Message -----

**Comment by ironcladlou** [comment]
@smarterclayton @abhgupta we need to address "Outstanding design issues:" since it could be an API addition (I assume additive changes are fine, but want to be sure).

**Comment by smarterclayton** [comment]
Reuse the timeout.

**Comment by ironcladlou** [comment]
Reuse will be okay for now, but it's very rough... the time it takes to scale up the RC count is a scheduling timeout, while the canary time is how long it takes your app to start up.

**Comment by smarterclayton** [comment]
A deployment that is fast but you don't know whether it's broken isn't very useful :)

----- Original Message -----
