### ISSUE TITLE
Recreate deployment strategy should support a third intermediate hook

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#2639]
Once the recreate strategy scales in the correct order (https://github.com/openshift/origin/issues/2638), it should support a third hook which executes after the scale down but before the scale up.

Punch list item for https://github.com/openshift/origin/issues/2628.

**Comment by kargakis** [comment]
@smarterclayton you can close this now

**Comment by smarterclayton** [comment]
I want to move this to Rolling as well, so that someone can run a hook as soon as the first pod passes the readiness hook.  Need to circle back.

**Comment by kargakis** [comment]
Opened https://github.com/openshift/origin/issues/8887 for rolling
