### ISSUE TITLE
Unprocessed template output in web UI pages

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#2640]
![selection_015](https://cloud.githubusercontent.com/assets/88819/7916425/02758512-0884-11e5-8091-9817508a37fe.png)

@liggitt FYI

**Comment by liggitt** [comment]
```
Error: [$injector:unpr] Unknown provider: projectOverviewURLFilterProvider <- projectOverviewURLFilter
```

**Comment by rhcarvalho** [comment]
For I don't know what reason I'm not observing that anymore... if nobody can reproduce it we can close this issue.

**Comment by liggitt** [comment]
we can't reproduce... closing, can reopen if you see it again
