### ISSUE TITLE
OKD4 Services node is running out of space

### ISSUE THREAD

**Issue by WillNilges** [openshift/origin#26418]
I've been running an OKD 4 setup on Proxmox since about October (OKD V4.5 ish), and it seems that, slowly but surely, its 50GB disk has filled to 91%. **I'm wondering if anyone has an explanation for this, and any solutions besides increasing the size of the disk?**

##### Version
4.7.0-0.okd-2021-06-19-191547

##### Steps To Reproduce
1. Install OKD4 cluster
2. Wait 10 months

##### Current Result
```
[root@okd4-services ~]# df -h
Filesystem                              Size  Used Avail Use% Mounted on
devtmpfs                                1.9G     0  1.9G   0% /dev
tmpfs                                   2.0G     0  2.0G   0% /dev/shm
tmpfs                                   786M  1.1M  785M   1% /run
/dev/mapper/fedora_okd4--services-root   47G   43G  4.7G  91% /
tmpfs                                   2.0G  4.0K  2.0G   1% /tmp
/dev/sda1                              1014M  289M  726M  29% /boot
/dev/rbd2                                98G   33G   61G  36% /var/nfs/registry
tmpfs                                   393M     0  393M   0% /run/user/0
```
VERY high disk usage. No obvious cause.

##### Expected Result
Reasonable disk usage. Maybe 50%.

**Comment by sandrobonazzola** [comment]
This issue should be transferred to https://github.com/openshift/okd

**Comment by WillNilges** [comment]
Haha, turns out that we had LOTS of etcd backups that weren't getting deleted. Sorry to bother you!
