### ISSUE TITLE
ruby new-app cannot find image using v1beta3

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#2642]
Be sure you have https://github.com/openshift/origin/pull/2641

```
OPENSHIFTCONFIG=openshift.local.config/master/admin.kubeconfig osadm registry --credentials=openshift.local.config/master/openshift-registry.kubeconfig
osc login
osc new-project ruby
osc new-app https://github.com/openshift/ruby-hello-world -l app=ruby --api-version=v1beta3
```

The command succeeds, but the deployment is never created and I see these messages in the master log every 60 seconds or so:
```
E0601 11:38:42.563222   21577 factory.go:68] couldn't create initial Deployment for DeploymentConfig ruby/ruby-hello-world:0: DeploymentConfig "ruby-hello-world" is invalid: triggers[1].imageChange.tag: invalid value 'latest': no image recorded for ruby/ruby-hello-world:latest
E0601 11:38:42.565499   21577 factory.go:68] couldn't create initial Deployment for DeploymentConfig ruby/ruby-hello-world:0: DeploymentConfig "ruby-hello-world" is invalid: triggers[1].imageChange.tag: invalid value 'latest': no image recorded for ruby/ruby-hello-world:latest
```

@ironcladlou @csrwng

**Comment by deads2k** [comment]
The replication controller is created if you have new-app use `v1beta1`.  I suspect the problem is due to a missing tag on an image stream, 

This for v1beta3
```
- apiVersion: v1beta3
  kind: ImageStream
  metadata:
    creationTimestamp: 2015-06-01T15:28:20Z
    labels:
      app: ruby
    name: ruby-hello-world
    namespace: ruby
    resourceVersion: "160"
    selfLink: /osapi/v1beta3/namespaces/ruby/imagestreams/ruby-hello-world
    uid: d5bbada4-0872-11e5-9479-28d2447dc82b
  spec:
    tags:
    - name: latest
  status:
    dockerImageRepository: 172.30.27.191:5000/ruby/ruby-hello-world
```

versus this for v1beta1
```
- apiVersion: v1beta3
  kind: ImageStream
  metadata:
    creationTimestamp: 2015-06-01T15:45:20Z
    labels:
      app: ruby
    name: ruby-hello-world
    namespace: ruby
    resourceVersion: "148"
    selfLink: /osapi/v1beta3/namespaces/ruby/imagestreams/ruby-hello-world
    uid: 359959f2-0875-11e5-a389-28d2447dc82b
  spec:
    tags:
    - name: latest
  status:
    dockerImageRepository: 172.30.68.53:5000/ruby/ruby-hello-world
    tags:
    - items:
      - created: 2015-06-01T15:45:20Z
        dockerImageReference: library/ruby-hello-world:latest
        image: ""
      tag: latest

```

@ncdc Just in case something occurs to you.

**Comment by ncdc** [comment]
The output from v1beta3 actually looks more correct to me. From the v1beta1 output, it's creating an image reference to a repo on the Hub called ruby-hello-world (library is implicit).

What does generated BuildConfig look like?

**Comment by deads2k** [comment]
The build actually works correctly, but `v1beta1` creates the tag ahead of time (before the runs) and `v1beta3` does not.  That causes the deployment controller to print that message in the `v1beta3` case.  After the build is run, the tag is created and the depoyment controller is happy.

**Comment by ncdc** [comment]
@deads2k there are 2 issues with the v1beta1 output:

1. Setting spec.tags[0].name=latest does nothing and is not needed (but it's harmless)
2. Setting status.tags[latest].items[0] to what it's doing above is incorrect. It is correct to have 0 tags until an image has been pushed, at which point there should be 1.

**Comment by deads2k** [comment]
> Setting status.tags[latest].items[0] to what it's doing above is incorrect. It is correct to have 0 tags until an image has been pushed, at which point there should be 1.

Ok, so `v1beta3` is working correctly and `v1beta1` is behaving incorrectly?  I light of that, I will update `hack/test-cmd.sh`.

**Comment by ncdc** [comment]
@deads2k well... you said in the description that the deployment is never created. Is that still the case?

**Comment by deads2k** [comment]
> @deads2k well... you said in the description that the deployment is never created. Is that still the case?

After running the build, the deployment is created.

**Comment by ncdc** [comment]
Which makes sense. Did the build not start automatically?

**Comment by deads2k** [comment]
> Which makes sense. Did the build not start automatically?

No, is it supposed to?

**Comment by ncdc** [comment]
@csrwng ^^^^ ?

**Comment by csrwng** [comment]
@ncdc @deads2k - the build wasn't starting automatically, but it will now with -> https://github.com/openshift/origin/pull/2697

**Comment by smarterclayton** [comment]
Where are we on this?

**Comment by csrwng** [comment]
builds should be getting triggered automatically now. @deads2k - can you please check that #2697 fixes this issue?

**Comment by deads2k** [comment]
Fixed.  @liggitt please close.
