### ISSUE TITLE
Create osc add-volume cmd  that adds things to a pod template

### ISSUE THREAD

**Issue by pravisankar** [openshift/origin#2643]
#2628

**Comment by smarterclayton** [comment]
Please add a description of your proposed design here before starting implementation

**Comment by pravisankar** [comment]
CLI cmd for volumes:
--
`osc volume` cmd can be used to add, update, delete and list volumes on selected or all containers in pods or any object that has a pod template (rc or dc).

Like other cmds, cmd theme can be:

`osc volume <resource-selection> <operation> <mandatory-args> <optional-args>`

Resource selection:

* <name>, resource name, examples: dc/registry, pods                                                       
* --selector, label selector to filter resources 
* --all, all resources of the specified resource type                                                      

Operation: 

* --add, Add volume and/or volume mounts for containers
* --delete, Delete volume and/or volume mounts for containers                                                    
* --list, List volume and volume mounts

Optional generic args for all operations: 

* --resource-version, update object only if current resource version matches (valid for single resource)
* --output, display changed object(s) instead of updating them, either in json/yaml (not valid for list op)
* --output-version, output changed object(s) in given version format                                       
 
Add operation args:                                                                                      
  - Mandatory:
  
    * <name>, name of the volume
    * --source, details of volume source as json string, example: "{'secret': {'secretName': 'xyz'}}"        
    * --source-file, file containing details of volume source.                                               
    Either --volume-source or --volume-source-file must be specified
    
    We can optionally provide `osc volume-source-format <type>`, type can be gce,nfs, etc. that can generate meta data of the volume source for the given type in json. User can populate the needed fields and can pass as --volume-source-file argument to add operation.
    
    Current volume sources: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L179 


  - Optional:                                                                                              
    * --mount, mount path inside the container                                                               
    * --containers, selected or all containers                                                               
    * --overwrite, this will simulate update volume and volume mount                                         
  
Delete operation args:                                                                                   
  - Mandatory:
    * <name>, name of the volume                                                                             
  - Optional:                                                                                              
    * --containers, selected or all containers                                                               
  
      If there are any containers (not selected by the delete op) using the given volume, then only the volume mounts on the selected containers will be removed but not the volume.

List operation args:                                                                                     
  - Optional:
    * <name>, name of the volume

**Comment by smarterclayton** [comment]
Please add examples of how you would actually use this (I want to see a CLI command line per use case)

1. A user adds a new volume to an existing deployment config based on a new directory.
2. A user wants to change the type of volume from emptyDir to a persistent volume

If you have additional use cases you've thought of please add them.  

----- Original Message -----

**Comment by pravisankar** [comment]
Some use cases:                                                   
                                                                         
- Add new volume to deployment config 'registry' based on host directory
  
  `osc volume dc/registry reg-vol --add --mount=/reg --source='{"hostPath": {"path": "/opt"}}'`
  
- Add new volume to pod 'p1' based on secret                             
  `osc volume pod/p1 vol1 --add --mount=/etc --source='{"secret": {"secretName": "magic"}}'`
  
- Change rc 'r1' to use persistent volume instead of emptyDir (name: vol1).
  
  `osc volume rc/r1 vol1 --add --overwrite --source='{"persistentVolumeClaim": {"claimName": "pvc1"}}'`                                     
  
- Add new volume to dc 'registry' based on RBD (anything that has a lot of config params)
  * `osc volume-source-format rbd > rbd-sample.json`
  * User edits rbd-sample.json based on requirement                  
  * `osc volume dc/registry vol1 --add --source-file=rbd-sample.json`    
  
- Delete volume 'v1' from dc 'reg'                                     
  `osc volume dc/reg v1 --delete`
 
- Unmount volume v1 from container c1 on pod p1 and delete the volume v1 if it is not referenced by any containers on pod p1.                     
  `osc volume pod/p1 v1 --delete --containers=c1`
   
- List volumes defined on rc 'r1'                          
  `osc volume rc/r1 --list`
 
- List volumes defined on all pods                                       
  `osc volume pods --all --list`                                         
  
- Output yaml object with volume info for dc 'reg' but don't alter the object on server

   `osc volume dc/reg vol1 --add --mount=/reg --source='{"emptyDir":{}}' -o yaml`                                                                  
   `osc volume dc/reg vol1 --delete -o json`

**Comment by pravisankar** [comment]
@smarterclayton @danmcp @markturansky  let me know your feedback

**Comment by ncdc** [comment]
You shouldn't be passing any json in on the command line (--source=...). It'd be much nicer to support flags for the range of volume types and their params.

**Comment by smarterclayton** [comment]
This is intended for new users of Openshift - we need to easily be able to expose the most important options for the volume in a structured fashion and explain the arguments to users.  For this pull, let's concentrate on selecting the type of volume and emphasizing emptydir (the default) and a pv ref.

**Comment by pravisankar** [comment]
Updated volume cli cmd options and the use cases
@smarterclayton @ncdc @jwhonce PTAL

**Comment by smarterclayton** [comment]
Add should be the default action, I think.

**Comment by smarterclayton** [comment]
`--mount` should be `--path`

**Comment by smarterclayton** [comment]
--delete should require --confirm

**Comment by smarterclayton** [comment]
`--delete` should be `--remove`

**Comment by smarterclayton** [comment]
Changing volume type should require `--confirm`

**Comment by smarterclayton** [comment]
Drop `--overwrite` since we have name uniqueness and `--confirm`

**Comment by smarterclayton** [comment]
`--source` for JSON string seems fine

**Comment by smarterclayton** [comment]
Looks really good Ravi - I think with those changes above we're good to go
