### ISSUE TITLE
add osadm policy view commands for easier management

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#2646]
`osadm policy` commands allow easy mutation of rolebindings, but do not provide functionality for:
 1. viewing bindings
 1. viewing roles
 1. mutating roles
 1. viewing your powers

@liggitt p3?

**Comment by jimmidyson** [comment]
Would really like to see this, as well as listing roles for a user & taking this further "what a user (or group) can actually do (the union of the verb/noun grants of their roles)" (@liggitt's idea).

Being able to query this through the REST API would be awesome, especially for a UI being able to enable/disable functionality based on user perms.

**Comment by deads2k** [comment]
> "what a user (or group) can actually do (the union of the verb/noun grants of their roles)"

See https://github.com/openshift/origin/issues/3220

**Comment by fabianofranz** [comment]
@deads2k still an issue?

**Comment by deads2k** [comment]
Yes

**Comment by deads2k** [comment]
rar, sar, rulesreview, resolve this pretty well.  Turns out we don't mutate roles very often.
