### ISSUE TITLE
Can't get favicon.ico in openshift dev server

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#2651]
I'm running OpenShift in VirtualBox with:

    sudo /data/src/github.com/openshift/origin/_output/local/go/bin/openshift start --public-master=localhost

Looking at Chrome's console:
GET https://localhost:8443/favicon.ico 403 (Forbidden)

I'd expect to get 404 if the file didn't exist, not 403?

@liggitt FYI

**Comment by liggitt** [comment]
We don't serve a favicon. Any urls not explicitly whitelisted return a 403.

**Comment by liggitt** [comment]
I don't think we want to whitelist a URL just to change a 403 to a 404... does the 403 cause any problems?

**Comment by rhcarvalho** [comment]
I thought it could be this https://github.com/openshift/origin/blob/master/assets/app/favicon.ico...

Apart from semantics, I believe 403 cause no problems. If we do return 403 to all non-whitelisted URLs, then I agree we should not change it :-)

**Comment by liggitt** [comment]
@sg00dwin can you look into referencing the favicon we make available under the console context root in the index.html `<head>`? not sure that will prevent all browser requests to `/favicon.ico` but it might help.

**Comment by liggitt** [comment]
favicon is now referenced explicitly in a `<link>` relation in the index.html
