### ISSUE TITLE
SDN conflicts with node self-registration

### ISSUE THREAD

**Issue by detiber** [openshift/origin#2655]
When configuring a previously unregistered node with the sdn plugin enabled, the openshift-node process times out waiting for an assigned sdn subnet.

The node should attempt to self-register before initializing the sdn plugin, or at least not fail to reach the self-registration step before failing when an sdn subnet is not present.

**Comment by detiber** [comment]
@rajatchopra @mrunalp

**Comment by rajatchopra** [comment]
Race condition here. We cannot start the openshift-sdn after registration because registration happens inside 'kubelet'.
Only quick solution I see is setting RegisterNode = false in kubelet and auto-register in ansible itself.

**Comment by rajatchopra** [comment]
The other way is to register the node in OpenShift itself. Copy this code and execute outside of kubelet - 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L732-L769

@smarterclayton your opinion needed here.

**Comment by smarterclayton** [comment]
The kubelet should start first, openshift-sdn should not allow pods to be created until a subnet is bound.  Once a subnet is bound openshift-sdn shouldn't have to check again.

**Comment by rajatchopra** [comment]
Fixed with https://github.com/openshift/origin/pull/2719

**Comment by smarterclayton** [comment]
This causes docker to reboot every time SDN is initialized, but the kubelet is already started.  We're going to need to find a different solution.

**Comment by smarterclayton** [comment]
What's the status on this?  This is still p0 for 1.0

**Comment by rajatchopra** [comment]
There is a workaround done in Ansible scripts.
1. Start node without network plugin. The node auto-registers.
2. Start node with network plugin.

If someone were to do this without ansible, the only way is to pre-register the node manually. That is how it is done in the vagrant setup as an example.

**Comment by smarterclayton** [comment]
That's not acceptable - we need a real fix.  Yo shouldn't have to use crazy scripting just to work around a bug in the code.

----- Original Message -----

**Comment by detiber** [comment]
@smarterclayton @rajatchopra: We went back to pre-registering the node in openshift-ansible, since playing orchestration games to make the self-registration work (it also makes the node labeling more straight-forward, until we can do that with node self-registration).

**Comment by smarterclayton** [comment]
I need a code fix for this for 3.0

----- Original Message -----

**Comment by smarterclayton** [comment]
We can arbitrarily delay the startup of the pod sync loop, so I'm tempted to say that we should be able to optionally gate startup on a channel.  Will take a look.

**Comment by smarterclayton** [comment]
@rajatchopra I have a tentative fix up in #2984 - please test and verify that the SDN behaves correctly and also verify the Kubelet is working correctly.  The change delays the arrival of notifications about pods (including whether pods have been seen, such that old pods can be deleted) until after the SDN signals it's ready.

A scenario that you need to test - start a pod, stop the kubelet, then start the kubelet again.  The pod should not be restarted (you may need to try this a couple of times to be sure it's not racing).  Then delete the pod - and verify it's removed from the kubelet.  The SeenAllSources check had to be modified and I'm not totally positive the logic is safe.
