### ISSUE TITLE
Not working in macOS Monterey

### ISSUE THREAD

**Issue by haibuiminh** [openshift/origin#26553]
[provide a description of the issue]

##### Version
oc version v3.10, v3.8
macOS mentorey 12.0.1

##### Steps To Reproduce
1. Just run ```oc version``` and recieve this issue in screen short
##### Current Result
<img width="978" alt="Screen Shot 2021-10-30 at 4 58 46 PM" src="https://user-images.githubusercontent.com/61405445/139528477-487d2dbb-5c27-4ad0-ad90-e64e3b98b53d.png">

##### Expected Result
oc version works well, and I can do my business job

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by gormers** [comment]
Not exaclty a fix, but the version you can install with brew (openshift-cli) seems to work fine. I got the same error with this version.

**Comment by geisa-integrasi** [comment]
> Not exaclty a fix, but the version you can install with brew (openshift-cli) seems to work fine. I got the same error with this version.

this worked for me

**Comment by haibuiminh** [comment]
I have installed Openshift-Cli with homebrew (v 4.6), but my server uses version 3.6.0 and I still get the issue with the message that is
```Error from server (NotAcceptable): the server was unable to respond with a content type that the client supports (get pods)```

**Comment by b-zurg** [comment]
> Not exaclty a fix, but the version you can install with brew (openshift-cli) seems to work fine. I got the same error with this version.

Really strange but this also worked for me. I had previously installed by simply downloading from github releases and then copying over to `usr/local/bin`.  

I had to delete the executable that I had copied over before installing from homebrew though.

**Comment by Themodem** [comment]
[https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue](https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue)

I have a hacky "fix" which works for me. Im only using a tiny subset of functionality though (getting tokens for pushing images and a couple of info commands) so not sure if this makes the entire `oc` binary work.

Im also on an intel mac so not sure if this will work for arm.
docker is used to build all the tools so you will need docker up and running too.

```shell
git clone https://github.com/openshift/origin.git
cd origin
git checkout v3.11.0
```

Then patch `hack/lib/build/binaries.sh` to comment out the go install command

```diff
diff --git a/hack/lib/build/binaries.sh b/hack/lib/build/binaries.sh
index 7a5cbb5eb3..3fa2a028c3 100644
--- a/hack/lib/build/binaries.sh
+++ b/hack/lib/build/binaries.sh
@@ -233,13 +233,13 @@ os::build::internal::build_binaries() {
       fi

       if [[ ${#nonstatics[@]} -gt 0 ]]; then
-        GOOS=${platform%/*} GOARCH=${platform##*/} go install \
-          -pkgdir "${pkgdir}/${platform}" \
-          -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" \
-          -ldflags="${local_ldflags}" \
-          "${goflags[@]:+${goflags[@]}}" \
-          -gcflags "${gogcflags}" \
-          "${nonstatics[@]}"
+        # GOOS=${platform%/*} GOARCH=${platform##*/} go install \
+        #   -pkgdir "${pkgdir}/${platform}" \
+        #   -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" \
+        #   -ldflags="${local_ldflags}" \
+        #   "${goflags[@]:+${goflags[@]}}" \
+        #   -gcflags "${gogcflags}" \
+        #   "${nonstatics[@]}"

         # GOBIN is not supported on cross-compile in Go 1.5+ - move to the correct target
         if [[ $platform != $host_platform ]]; then
```

```shell
OS_BUILD_ENV_GOLANG=1.11 OS_ONLY_BUILD_PLATFORMS=darwin ./hack/build-release.sh
```

This will build the binaries for mac and dump them in `_output/local/bin/darwin/ARCH`

```shell
❯ l _output/local/bin/darwin/amd64/
.rwxr-xr-x 206M lee 16 Nov 10:57 hyperkube
.rwxr-xr-x 260M lee 16 Nov 10:57 hypershift
.rwxr-xr-x 107M lee 16 Nov 10:57 kubectl
.rwxr-xr-x 2.1M lee 16 Nov 10:57 oadm
.rwxr-xr-x 107M lee 16 Nov 10:57 oc
.rwxr-xr-x 240M lee 16 Nov 10:57 openshift
.rwxr-xr-x  28M lee 16 Nov 10:57 openshift-node-config
.rwxr-xr-x  66M lee 16 Nov 10:57 template-service-broker
```

```
oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth
```

Hope that helps!

**Comment by patchon** [comment]
> ```shell
> ```shell
> OS_BUILD_ENV_GOLANG=1.11 OS_ONLY_BUILD_PLATFORMS=darwin ./hack/build-release.sh
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Thanks for this, really!
Took me hours to get here. 
🥳  🚀

**Comment by patchon** [comment]
> https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue
> 
> I have a hacky "fix" which works for me. Im only using a tiny subset of functionality though (getting tokens for pushing images and a couple of info commands) so not sure if this makes the entire `oc` binary work.
> 
> Im also on an intel mac so not sure if this will work for arm. docker is used to build all the tools so you will need docker up and running too.
> 
> ```shell
> git clone https://github.com/openshift/origin.git
> cd origin
> git checkout v3.11.0
> ```
> 
> Then patch `hack/lib/build/binaries.sh` to comment out the go install command
> 
> ```diff
> diff --git a/hack/lib/build/binaries.sh b/hack/lib/build/binaries.sh
> index 7a5cbb5eb3..3fa2a028c3 100644
> --- a/hack/lib/build/binaries.sh
> +++ b/hack/lib/build/binaries.sh
> @@ -233,13 +233,13 @@ os::build::internal::build_binaries() {
>        fi
> 
>        if [[ ${#nonstatics[@]} -gt 0 ]]; then
> -        GOOS=${platform%/*} GOARCH=${platform##*/} go install \
> -          -pkgdir "${pkgdir}/${platform}" \
> -          -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" \
> -          -ldflags="${local_ldflags}" \
> -          "${goflags[@]:+${goflags[@]}}" \
> -          -gcflags "${gogcflags}" \
> -          "${nonstatics[@]}"
> +        # GOOS=${platform%/*} GOARCH=${platform##*/} go install \
> +        #   -pkgdir "${pkgdir}/${platform}" \
> +        #   -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" \
> +        #   -ldflags="${local_ldflags}" \
> +        #   "${goflags[@]:+${goflags[@]}}" \
> +        #   -gcflags "${gogcflags}" \
> +        #   "${nonstatics[@]}"
> 
>          # GOBIN is not supported on cross-compile in Go 1.5+ - move to the correct target
>          if [[ $platform != $host_platform ]]; then
> ```
> 
> ```shell
> OS_BUILD_ENV_GOLANG=1.11 OS_ONLY_BUILD_PLATFORMS=darwin ./hack/build-release.sh
> ```
> 
> This will build the binaries for mac and dump them in `_output/local/bin/darwin/ARCH`
> 
> ```shell
> ❯ l _output/local/bin/darwin/amd64/
> .rwxr-xr-x 206M lee 16 Nov 10:57 hyperkube
> .rwxr-xr-x 260M lee 16 Nov 10:57 hypershift
> .rwxr-xr-x 107M lee 16 Nov 10:57 kubectl
> .rwxr-xr-x 2.1M lee 16 Nov 10:57 oadm
> .rwxr-xr-x 107M lee 16 Nov 10:57 oc
> .rwxr-xr-x 240M lee 16 Nov 10:57 openshift
> .rwxr-xr-x  28M lee 16 Nov 10:57 openshift-node-config
> .rwxr-xr-x  66M lee 16 Nov 10:57 template-service-broker
> ```
> 
> ```
> oc version
> oc v3.11.0+0cbc58b
> kubernetes v1.11.0+d4cacc0
> features: Basic-Auth
> ```
> 
> Hope that helps!

Thanks for this, really!
Took me hours to get here.
🥳 🚀

**Comment by JtMotoX** [comment]
I am also running into issues when trying to patch & build.

```
diff --git a/hack/lib/build/binaries.sh b/hack/lib/build/binaries.sh
index 7a5cbb5eb3..827efb7db9 100644
--- a/hack/lib/build/binaries.sh
+++ b/hack/lib/build/binaries.sh
@@ -233,14 +233,6 @@ os::build::internal::build_binaries() {
       fi
 
       if [[ ${#nonstatics[@]} -gt 0 ]]; then
-        GOOS=${platform%/*} GOARCH=${platform##*/} go install \
-          -pkgdir "${pkgdir}/${platform}" \
-          -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" \
-          -ldflags="${local_ldflags}" \
-          "${goflags[@]:+${goflags[@]}}" \
-          -gcflags "${gogcflags}" \
-          "${nonstatics[@]}"
-
         # GOBIN is not supported on cross-compile in Go 1.5+ - move to the correct target
         if [[ $platform != $host_platform ]]; then
           local platform_src="/${platform//\//_}"
```

```
> OS_BUILD_ENV_GOLANG=1.11 OS_ONLY_BUILD_PLATFORMS=darwin ./hack/build-release.sh
Unable to find image 'openshift/origin-release:golang-1.11' locally
golang-1.11: Pulling from openshift/origin-release
2d473b07cdd5: Already exists
9864ffd6f914: Pulling fs layer
9864ffd6f914: Verifying Checksum
9864ffd6f914: Download complete
9864ffd6f914: Pull complete
Digest: sha256:2cbbde804fb377bfacf11d25d02dfd7e99724deb6cf4c0a8f9310d3253db70dd
Status: Downloaded newer image for openshift/origin-release:golang-1.11
/tmp/testing/origin/hack/lib/build/version.sh: line 83: go: command not found
[ERROR] PID 72538: hack/lib/build/version.sh:82: `KUBE_GIT_VERSION=$(go run "${OS_ROOT}/tools/godepversion/godepversion.go" "${OS_ROOT}/Godeps/Godeps.json" "k8s.io/kubernetes/pkg/api" "comment")` exited with status 127.
[INFO]          Stack Trace: 
[INFO]            1: hack/lib/build/version.sh:82: `KUBE_GIT_VERSION=$(go run "${OS_ROOT}/tools/godepversion/godepversion.go" "${OS_ROOT}/Godeps/Godeps.json" "k8s.io/kubernetes/pkg/api" "comment")`
[INFO]            2: hack/lib/build/version.sh:29: os::build::version::kubernetes_vars
[INFO]            3: hack/lib/build/version.sh:19: os::build::version::git_vars
[INFO]            4: hack/build-release.sh:33: os::build::version::get_vars
[INFO]   Exiting with code 127.
/tmp/testing/origin/hack/lib/build/environment.sh: line 111: $2: unbound variable
```
