### ISSUE TITLE
Add example command to connect to jboss-eap cli on the pod window

### ISSUE THREAD

**Issue by rettori** [openshift/origin#2656]
In the pods window, if a pod is running jboss-eap, there should be a list of example commands one could use inside that pod, like how to access the jboss-cli.

**Comment by jwforres** [comment]
This could be contributed as an extension.  cc @gashcrumb

**Comment by jwforres** [comment]
I don't think this is something that is going to be implemented as part of origin.  If someone wants to go write an extension that does this and needs an extension point to plug into, then a request can be opened in the origin-web-console repo for a new extension point.
