### ISSUE TITLE
Kustomize Version Output

### ISSUE THREAD

**Issue by jmcudd** [openshift/origin#26613]
There is no way of determining the version of kustomize. This is important when debugging issues with kustomize and consulting the kustomize documentation.

##### Version
4.7.19

##### Steps To Reproduce
1. oc kustomize --version

##### Current Result
Error: unknown flag: --version
See 'oc kustomize --help' for usage.

##### Expected Result
{Version:4.4.0 GitCommit:$Format:%H$ BuildDate:2021-09-29T10:27:55Z GoOs:linux GoArch:amd64}

##### Additional Information
The catalyst for this issue was seeing differences in behaviour between `kubectl apply -k` and `oc apply -k` which lead me to look into which versions of kustomize each CLI is using.

##### Related issues:
https://github.com/kubernetes/kubectl/issues/797
https://github.com/kubernetes-sigs/kustomize/issues/1424

**Comment by dariusdev** [comment]
/reopen

it is not resolved yet
