### ISSUE TITLE
can't hide details tab in console

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2665]
It would be nice if there was an "x" or some kind of button to hide the details tab in the console. I'm fine with it being open by default but I would think that tab/area would get annoying if I had a complicated project with lots of components.

```
[joe@ose3-master beta4]$ osc version
osc v0.5.2.2-11-g4efd399
kubernetes v0.17.1-804-g496be63
```

**Comment by jwforres** [comment]
this has been moved to trello https://trello.com/c/J0r0lifV
