### ISSUE TITLE
Is it ok to use docker push via the router on the OpenShift registry?

### ISSUE THREAD

**Issue by rawlingsj** [openshift/origin#2667]
Should it be possible to to a plain `docker push` of a custom image to the OpenShift private registry via a route and then run it?

I've got a route set up to a service from port 80 to 5000 so I can push an image successfully from my laptop to a cloud hosted.  When I try to run the image however it doesn't seem to find the imageStream unless I specify the service ip and port in the image name.

```
osc get service
NAME              LABELS                                    SELECTOR                  IP(S)            PORT(S)
docker-registry   docker-registry=default                   docker-registry=default   172.30.194.135   5000/TCP
kubernetes        component=apiserver,provider=kubernetes   <none>                    172.30.0.2       443/TCP
kubernetes-ro     component=apiserver,provider=kubernetes   <none>                    172.30.0.1       80/TCP
registry          <none>                                    docker-registry=default   172.30.146.248   80/TCP
router            router=router                             router=router             172.30.122.189   80/TCP
```

I can see the imageStream..
```
osc get imageStream
NAME             DOCKER REPO                                  TAGS
my-image   			 172.30.194.135:5000/default/my-image   			latest
```

But when I reference the imageStream name in a RC pod then it os not found, it only works when I specify the full  `172.30.194.135:5000/default/my-image` which I'd like to avoid incase the service is deleted and a new ip is used.

```
W0601 14:48:45.868702   24135 manager.go:1420] Failed to pull image "my-image" from pod "my-image-controller-hr1yk_default" and container "my-image-container": Error: image library/my-image:latest not found
```

Even once the image is found using the full repository the container is started and then stopped a few seconds after with no failure of error that I've been able to find.  the RC then starts a new container that causes an endless loop.

This might well be two issues and I can help to provide more info but I wanted to check first that I should be able to use plain docker push (using the right namespace) and run the image using the image stream name?

**Comment by ncdc** [comment]
You can do this, but not with an RC (which, as you've seen, requires a full image reference). You'll need to use a DeploymentConfig with an ImageChange trigger. See https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json#L195-L207 for an example.

**Comment by rawlingsj** [comment]
ah great, thanks @ncdc

**Comment by rawlingsj** [comment]
This worked perfectly.  Thank you.
