### ISSUE TITLE
osc expose needs to add host option and the doc needs fixing

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#2670]
the osc expose command should allow me to add the host in the command. For example:
osc expose apache -h www.example.com 

should add the following metadata to the route

"spec": {
                "host": "www.example.com",
                "to": {
                    "kind": "Service",
                    "name": "apache"
                },

There is also some issues with the current doc. 

The doc says port is required 
"      --port=-1: The port that the service should serve on. Required."

but in the two examples you give there are no ports listed

"Examples:
// Create a route based on service nginx. The new route will re-use nginx's labels.
$ osc expose service nginx

// Create a route and specify your own label.
$ osc expose service nginx --labels name=myroute
"

Does the "port the service should serve on" have to match the port exposed by the service, or will the route take something coming in on a different port and then send it to the listening port for a service?

Should this say route rather than service?
" --name='': The name for the newly created service."

These two are not clear just from reading the help but I think that is because I need to read more in depth documentation about Load Balancers and routes. Does documentation exist for the concepts discussed here?
"--create-external-load-balancer=false: If true, create an external load balancer for this service (trumped by --type). Implementation is cloud provider dependent. Default is 'false'.
"
 "--type='': Type for this service: ClusterIP, NodePort, or LoadBalancer. Default is 'ClusterIP' unless --create-external-load-balancer is specified."

**Comment by kargakis** [comment]
The help doc is baggage from [Kubernetes](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl_expose.md) but I hope we can remove the defaults at least. 

>Does the "port the service should serve on" have to match the port exposed by the service, or will the route take something coming in on a different port and then send it to the listening port for a service?

The `--port` flag is required for exposing services (`--generator=services/v1`), routes don't need any port specified.

>Should this say route rather than service?
" --name='': The name for the newly created service."

That message should be generic (*The name for the newly created object.*).

>These two are not clear just from reading the help but I think that is because I need to read more in depth documentation about Load Balancers and routes. Does documentation exist for the concepts discussed here?

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#external-services

**Comment by kargakis** [comment]
Opened this issue upstream which will solve the problem with the help doc if fixed: https://github.com/spf13/pflag/issues/28

**Comment by thesteve0** [comment]
What about the adding a host to the route

**Comment by kargakis** [comment]
> What about the adding a host to the route

Fairly easy, I'll add it later today or tomorrow.

**Comment by kargakis** [comment]
@pweil- @smarterclayton by specifying a host we should also specify another service that the route should point to right? Does adding a --hostname option to expose makes sense?

**Comment by pweil-** [comment]
Allowing people to specify the host of the route through expose makes sense to me since not everyone will want an auto-generated name if they already own a domain.  If the service it is already pointing to is correct there is no need to create another.
