### ISSUE TITLE
Change default openshift default registry url 

### ISSUE THREAD

**Issue by ariyaee1367** [openshift/origin#26725]
Hi Dears , 
We use openshift 4.7, how can I change default regitstry (default tegistry is docker.io) . 
I try for change config file but did not wolrk . 
Change default openshift default registry url . 

cat /etc/containers/registries.conf
unqualified-search-registries = ["dockerhub.ir"]

[[registry]]
prefix = "my repo"
location = "my repo"
insecure = false

**Comment by Plataformaalgoritmica** [comment]
Hello World.
