### ISSUE TITLE
new-app needs search/list functionality

### ISSUE THREAD

**Issue by fabianofranz** [openshift/origin#2672]
From the 1.0 Punch List https://github.com/openshift/origin/issues/2628.

**Comment by fabianofranz** [comment]
@smarterclayton @danmcp I'll start drawing a proposal for the command design (args, flags, etc). Feel free to fill if you have anything in mind already.

**Comment by smarterclayton** [comment]
I believe the original commit had examples

**Comment by fabianofranz** [comment]
[This](https://github.com/openshift/origin/commit/c1f2d2ff1ea09c8a330a1ee4b12697e74e908124#diff-27232336beeebaf3f07c4c3d487ae5c9R22) seems to be the only reference in terms of proposed syntax still in the history. There is a rough searcher initial implementation in that commit. It was later removed [here](https://github.com/openshift/origin/commit/adfd0076be22aa7b884193c807ebdf98a61ad4e5#diff-afcd3de00e57205c8c11cfaee21bbf9eR22). 

I'll start with something along those lines. `osc new-app -S <query>` and `osc new-app --search <query>`.

**Comment by csrwng** [comment]
Related issues: 
https://github.com/openshift/origin/issues/2672
https://github.com/openshift/origin/issues/2625

**Comment by fabianofranz** [comment]
One idea I just had here: instead of using the `-S|--search` flag as a string that takes the string query to search for, make it a `boolean` that, when specified, act as a search. That would allow searching as arguments *and* use some of the flags if you want to refine where to search for it. Examples:

```
osc new-app mysql --search
osc new-app --search mysql
```

and refined as

```
osc new-app --search --docker-image=mysql
osc new-app --search --image=mysql
osc new-app --search --template=mysql
```

@csrwng @smarterclayton what do you think?

**Comment by smarterclayton** [comment]
Not unreasonable, how complex is is to implement.

**Comment by fabianofranz** [comment]
Places where the existing resolvers framework don't fit very well in a searching/listing scenario (notes for myself to decide what to do): 

- [ ] The `Resolve` method in the `Resolver` interface return one single `ComponentMatch` which is a struct, not an interface. For search results we would like every possible match to be returned. Could be changed to return a slice of `ComponentMatch`. Could make `ComponentMatch` an interface and implementations that hold one or multiple. If we want to avoid changing the existing `Resolve` method, could add a new one to the interface, like `Search(value string) (*ComponentMatch[], error)`.
- [ ] `TemplateResolver` and `ImageStreamResolver` rely on `client.Get(name)` which will not find any partial matches, is case sensitive, etc ("mysq", "MYSQL" won't find anything). Can be solved with new resolvers that list and find by string proximity, but `Resolve` still need to support returning multiple matches.
- [ ] Need a new `WeightedResolver` that returns all matches, e.g. `AllMatchesResolver`. Relying on `ErrMultipleMatches` smells bad, so again `Resolve` should support multiple.

**Comment by csrwng** [comment]
@fabianofranz I agree... call the things that do the actual searching Searcher instead of resolver. Keep the current searcher interface (https://github.com/openshift/origin/blob/master/pkg/generate/app/imagelookup.go#L307-L309) and make the low-level things that can return multiple results (like DockerClientResolver, DockerRegistryResolver, etc.) searchers. And the thing that aggregates them like the WeightedResolver a resolver. If you are doing a search, then use a Searcher aggregator instead of a resolver.

**Comment by smarterclayton** [comment]
> On Jun 5, 2015, at 1:21 AM, Fabiano Franz <notifications@github.com> wrote:
> 
> Places where the existing resolvers framework don't fit very well in a searching/listing scenario (notes for myself to decide what to do):
> 
>  The Resolve method in the Resolver interface return one single ComponentMatch which is a struct, not an interface. For search results we would like every possible match to be returned. Could be changed to return a slice of ComponentMatch. Could make ComponentMatch an interface and implementations that hold one or multiple. If we want to avoid changing the existing Resolve method, could add a new one to the interface, like Search(value string) (*ComponentMatch[], error).
Search
>  TemplateResolver and ImageStreamResolver rely on client.Get(name) which will not find any partial matches, is case sensitive, etc ("mysq", "MYSQL" won't find anything). Can be solved with new resolvers that list and find by string proximity, but Resolve still need to support returning multiple matches.
Search should call code that fetches the lists
>  Need a new WeightedResolver that returns all matches, e.g. AllMatchesResolver. Relying on ErrMultipleMatches smells bad, so again Resolve should support multiple.
Search

**Comment by smarterclayton** [comment]
Exactly what Cesar said

**Comment by fabianofranz** [comment]
I agree, thanks folks. Relying on the existing `Resolver` would make sense if we wanted the search results behave like in create (e.g. if there's an exact match, return only that). The `Searcher` idea is pretty much what I started doing yesterday when using the existing stuff started to smell bad.

**Comment by fabianofranz** [comment]
@smarterclayton please close.
