### ISSUE TITLE
JavaScript in the sample-app is incorrect

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#2675]
In the latest version of sample-app it looks like the route only works over https. The problem is that in the javascript that does all the form interactions the code uses http.

    xmlHttp.open( "POST", "http://"+window.location.hostname+":"+window.location.port+"/keys/"+document.getElementById("key").value, false );

in latest chrome and FF this causes a mixed content error - which prevents the page from working
IN chrome:
 Mixed Content: The page at 'https://localhost:1443/#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:1443/keys/steve'. This content should also be served over HTTPS.

in FF
Blocked loading mixed active content "http://localhost:1443/keys/name"
https://localhost:1443/#
Line 66

Either make the site available over HTTP or change the javascript.

Thanks

**Comment by bparees** [comment]
i think the real issue here is that the route should be an http route.

**Comment by bparees** [comment]
or you can do the fix that @liggitt suggested on your PR so it'll work for https+http.
