### ISSUE TITLE
OC client error on new version of macOS Monterey

### ISSUE THREAD

**Issue by kshitij241** [openshift/origin#26785]
OC clinet throwing the error as its build on go 1.10

##### Version
OC Client version 3.11

##### Steps To Reproduce
Mac OS  Monterey 12.1

##### Current Result

fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x37ead3b, 0x21)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0x7ff7bfeffaa8 sp=0x7ff7bfeffa88 pc=0x102ae91
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeffad8 sp=0x7ff7bfeffaa8 pc=0x1028a13
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:501 +0xd6 fp=0x7ff7bfeffb40 sp=0x7ff7bfeffad8 pc=0x102d786
runtime.rt0_go(0x7ff7bfeffb70, 0x3, 0x7ff7bfeffb70, 0x1000000, 0x3, 0x7ff7bfeffca8, 0x7ff7bfeffcab, 0x7ff7bfeffcaf, 0x0, 0x7ff7bfeffcbb, ...)
	/usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeffb48 sp=0x7ff7bfeffb40 pc=0x1056af4

##### Expected Result

OC client output or oc version output with oc version command, 

##### Additional Information
issue with simple OC command too. Find this thred about go version as OC client is build on 1.10 version of golang.
https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue

is it going to be new OC client which is build on go 1.11 or highter?  
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by vishal-hegde** [comment]
Facing the same issue. Is there any update on this issue?

**Comment by kshitij241** [comment]
I have installed the latest version of oc clinet with` brew install openshift-cli` 
its working for me so far. Some command has changed with updated version.

**Comment by amirhosseinNouri** [comment]
@kshitij241 's answer works well.

**Comment by leroy0211** [comment]
@kshitij241 's answer worked, but installs the openshift v4 client.  Some things like flags are removed or replaced, keep that in mind!

**Comment by lengerrong** [comment]
if you installed oc before, please remember run below command:
 
 ```brew link openshift-cli```
 
 otherwise, the ```oc``` command still links to the old one and still reports the same issue.
