### ISSUE TITLE
Host System self-referencing requires FQDN to resolve (correctly)

### ISSUE THREAD

**Issue by kanarip** [openshift/origin#268]
Following the quide listed at:

  https://blog.openshift.com/openshift-v3-deep-dive-docker-kubernetes/

may result in a non-functional environment, which at the stage of applying the Docker Registry Config would return in an infinite loop attempting to allocate a healthy Docker host(?).

After a little investigation, error messages disclose:

    E1027 13:17:38.626580 04954 pod_cache.go:84] Error synchronizing container: Get http://:10250/podInfo?podID=deploy-docker-registry: dial tcp :10250: connection refused

as well as:

    E1027 13:26:21.350905 05232 healthy_registry.go:77] some.domain.tld failed health check with error: Get http://some.domain.tld:10250/healthz: dial tcp w.x.y.z:10250: i/o timeout

where some.domain.tld should not be resolving to an w.x.y.z IP address.

While it is (in hindsight) abbundantly clear why system's FQDNs should properly resolve, it is not mentioned anywhere in the docs, and other utilities and configuration seem to all be using IP addresses -- so this one component requiring proper DNS resolving in order to self-reference was a little bit surprising.

**Comment by smarterclayton** [comment]
There's more documentation available on this now.  Is there something concrete that could be done today to improve this, or can we close this out?

**Comment by jim-minter** [comment]
Now that there are more installation pieces for standard usage, personally this doesn't bother me any more.

**Comment by smarterclayton** [comment]
You ok with closing then?

**Comment by jim-minter** [comment]
Yes.
