### ISSUE TITLE
Make descriptions for template parameters more meaningful

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2689]
Current we have descriptions like this:

```json
    {
      "name": "MONGODB_USER",
      "description": "database username",
      "generate": "expression",
      "from": "user[A-Z0-9]{3}"
    },
    {
      "name": "MONGODB_PASSWORD",
      "description": "database password",
      "generate": "expression",
      "from": "[a-zA-Z0-9]{8}"
    },
    {
      "name": "MONGODB_DATABASE",
      "description": "database name",
      "value": "sampledb"
    }
```

Since we want to display this to users the descriptions should be more informative and capitalized (otherwise they look pretty ugly in UI).

**Comment by mfojtik** [comment]
@bparees @soltysh @mnagy FYI

**Comment by bparees** [comment]
@mnagy since you're updating the templates can you take this?  thanks.

**Comment by spadgett** [comment]
Was just about to open this. Here's what it will look like in the UI if we always show template parameters:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/7937062/9e273b54-090b-11e5-9ef7-f2b1911e66e0.png)

**Comment by liggitt** [comment]
@spadgett descriptions should be tighter to the field they are describing... make sure we handle super long ones well

**Comment by mfojtik** [comment]
@liggitt currently we are not validating length of description... I guess we should set some reasonable maximum value.

**Comment by liggitt** [comment]
what I really want is `displayName string` (defaults to empty and UI falls back to showing `name`) and `required bool` (defaults to false). Most of the existing `description` fields are trying to be display names

**Comment by liggitt** [comment]
https://github.com/openshift/origin/issues/2179

**Comment by mnagy** [comment]
Fix is in #2644

**Comment by mnagy** [comment]
#2644 was merged, @bparees can you please close this?

**Comment by bparees** [comment]
thanks @mnagy!
