### ISSUE TITLE
new-build command that creates a new build

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#2695]
From the 1.0 Punch List #2628.

new-build command should be similar to new-app in that it should create *just* the `BuildConfig` object.

**Comment by liggitt** [comment]
`new-build` and `start-build` are going to be easily confused

**Comment by smarterclayton** [comment]
Use cases for new-build

* An admin wants to fork an openshift image and add a layer which is built automatically - they want to take ruby:2.0 and add a layer that adds their own custom libraries.
* A user wants to customize the DB image that they get from their ops team by adding a config file in it to change how mysql works
