### ISSUE TITLE
Console UI components-block not displaying properly in IE when content is left aligned at mobile res

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#2698]
![ie11-components-flex-bug](https://cloud.githubusercontent.com/assets/1874151/7941938/988e052a-0928-11e5-8483-525f432ad98a.png)

**Comment by liggitt** [comment]
IE only

**Comment by sg00dwin** [comment]
Fix verified in IE 10 & 11

![screen shot 2015-06-09 at 12 14 18 pm](https://cloud.githubusercontent.com/assets/1874151/8063150/3bc13460-0ea1-11e5-9ccc-76c4b0ad9ba9.png)
