### ISSUE TITLE
origin-version-change trips over templates

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#2702]
I was trying to update https://github.com/openshift/origin/blob/master/examples/project-quota/application-template-with-resources.json which is a template where resource limits are specified using template values, like this:
```
"resources": {
  "limits": {
    "cpu": "${BUILD_RUBY_RESOURCES_LIMITS_CPU}",
    "memory": "${BUILD_RUBY_RESOURCES_LIMITS_MEMORY}"
  }
},
```

This causes origin-version-change to throw following, correct error:
```
quantities must match the regular expression '^([+-]?[0-9.]+)([eEimkKMGTP]*[-+]?[0-9]*)$'
```

Still the version update should work.

@mfojtik @smarterclayton fyi

**Comment by smarterclayton** [comment]
This is why we don't do conversions on templates generally.

----- Original Message -----

**Comment by bparees** [comment]
not sure how this can ever work, since by definition the api objects inside a template can be "not well formed/not syntactically correct' due to the use of parameter variables.

@soltysh reopen if you have a suggestion for how we'd make this work without crazy hackery in our api object parsing logic.

**Comment by mfojtik** [comment]
would be nice to have option that disable validation.

**Comment by deads2k** [comment]
> would be nice to have option that disable validation.

That's not possible in the general case.  Consider v1 has a string attribute foo that is "INT/INT".  v2 has two int fields.  The template contains foo="${sub}".  What does the conversion do?

**Comment by soltysh** [comment]
> @soltysh reopen if you have a suggestion for how we'd make this work without crazy hackery in our api object parsing logic.

Yeah, only hackery substitution for the time of update and then substitute back is in my head right now. If I come with some smart solution, I'll reopen.

**Comment by mfojtik** [comment]
@soltysh @deads2k @bparees then I think we should leave this tool to not be perfect :-) IOW. human intervention is needed if this breaks on invalid values.

**Comment by smarterclayton** [comment]
It's going to be really hard to get templates upstream if we can't solve
this.
