### ISSUE TITLE
how to enable HPAScaleToZero feature gate?

### ISSUE THREAD

**Issue by LinghaoYu** [openshift/origin#27145]
I am trying to enable HPAScaleToZero feature gate. The only openshift specific  instruction I found is https://docs.openshift.com/container-platform/4.8/nodes/clusters/nodes-cluster-enabling-features.html, and it talks about enabling featureset first in order to enable a feature gate? But I don't find any featurset that contains HPAScaleToZero, and I only want HPAScaleToZero, not other feature gates. Can someone please instruct me how to only enable HPAScaleToZero?

##### Version
[4.8.36]

**Comment by rutvik23** [comment]
/remove-lifecycle stale
Based on the table below, it was supposed to be shipped as Beta after k8s 1.16, but the status still appears as Alpha.
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
Could anyone from the workload team shed more light on this feature's availability?

**Comment by machine424** [comment]
Hello,

If you don't/cannot wait for it to go GA, I developed https://github.com/machine424/kube-hpa-scale-to-zero
