### ISSUE TITLE
Deployment config reaper does not appear to be deleting rcs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2721]
Seeing this from hack/test-cmd against master - deleting the DC should have removed many more of those RCs prior to creation.

```
buildConfigs/ruby-sample-build
buildConfigs/sinatra-app-example
buildConfigs/sinatra-example-1
buildConfigs/sinatra-example-2
builds/ruby-sample-build-1
builds/sinatra-app-example-1
builds/sinatra-example-1-1
imageStreams/sinatra-app-example
imageStreams/sinatra-example-1
imageStreams/sinatra-example-2
deploymentConfigs/database
deploymentConfigs/frontend
deploymentConfigs/sinatra-app-example-a
deploymentConfigs/sinatra-app-example-b
deploymentConfigs/sinatra-example-1
deploymentConfigs/sinatra-example-2
replicationcontrollers/database-2
replicationcontrollers/database-app-1
replicationcontrollers/database-rc-1
replicationcontrollers/frontend-1
replicationcontrollers/frontend-2
replicationcontrollers/frontend-app-1
```

**Comment by smarterclayton** [comment]
I'm also seeing races here in hack/test-cmd on a slow machine:

```
osc delete dc docker-registry
osc delete svc docker-registry
[ ! "$(osc get rc docker-registry-1)" ]
```

where the last command fails (but never should).

**Comment by smarterclayton** [comment]
Failing in travis too:

```
services/docker-registry
!!! Error in hack/test-cmd.sh:348
  '[ ! "$(osc get rc docker-registry-1)" ]' exited with status 1
Call stack:
  1: hack/test-cmd.sh:348 main(...)
Exiting with status 1
[FAIL] !!!!! Test Failed !!!!
```

**Comment by kargakis** [comment]
We were deleting based on the latest version, switching to deleting based on the dc selector (https://github.com/openshift/origin/pull/2692) will probably solve this.

**Comment by ironcladlou** [comment]
After a careful audit of the log and DeploymentConfigController code, I'm thinking this is the timeline (as suspected by @smarterclayton in https://github.com/openshift/origin/pull/2765#issuecomment-108607692):

1. The deployment/RC is deleted; at this time, the config version is 1
2. The reaper updates the config with empty triggers
3. The DeploymentConfigChangeController ignores the config event since the triggers are empty
4. The DeploymentConfigController gets the same event, sees that there's no deployment out there for version 1, and so creates a deployment

cc @abhgupta

**Comment by ironcladlou** [comment]
Right now my thought is that the deploymentConfig should always be deleted before its deployments. This would prevent any further system behavior for those deployments. We wouldn't need to update the triggers on the deploymentConfig before deleting it. Then prune the orphaned deployments.

Thoughts?

**Comment by ironcladlou** [comment]
Working on a PR with this approach.

**Comment by smarterclayton** [comment]
Why don't we set the triggers first?

**Comment by ironcladlou** [comment]
@smarterclayton 
>Why don't we set the triggers first?

The triggers are on the config, deleting the config deletes the triggers atomically and ensures no behavior will be triggered (as none of the controllers react to the delete of the config, including the trigger controllers).

**Comment by smarterclayton** [comment]
Why are controllers reacting to trigger changes?

**Comment by ironcladlou** [comment]
>Why are controllers reacting to trigger changes?

Setting the field on the config causes a mod event which is picked up by the DeploymentConfigController. The DeploymentConfigController has no way to know that the absence of a deployment for the current version is because it never existed (in which case it should deploy) or because it was deleted by a pruning function which is implicitly signaling the death of the DeploymentConfig.

Rather than trying to weave that sort of guard logic throughout the controllers, why not just delete the config? In one atomic step there is no longer any behavior to guard against. Then the deployments can be pruned. The fact that they're disassociated with a config doesn't cause any undesirable behavior at all (that I know of).

**Comment by ironcladlou** [comment]
This also prevents external clients from causing the same sort of scenarios during the stop.

**Comment by ironcladlou** [comment]
https://github.com/openshift/origin/pull/2772 is my take on the config-deleted-first approach.

**Comment by smarterclayton** [comment]
> On Jun 3, 2015, at 8:10 PM, Dan Mace <notifications@github.com> wrote:
> 
> Why are controllers reacting to trigger changes?
> 
> Setting the field on the config causes a mod event which is picked up by the DeploymentConfigController. The DeploymentConfigController has no way to know that the absence of a deployment for the current version is because it never existed (in which case it should deploy) or because it was deleted by a pruning function which is implicitly signaling the death of the DeploymentConfig.
> 
If there are no triggers... It does know that there shouldn't be a deployment.  Deployments shouldn't get created without a config change or image change trigger

**Comment by liggitt** [comment]
> Deployments shouldn't get created without a config change or image change trigger

The update that removes the triggers is indistinguishable from a config change update, hence the deployment

**Comment by liggitt** [comment]
Are you saying that a deployment config without any triggers should never result in a controller-spawned deployment? If so, it sounds like the DeploymentConfigController is doing something different

**Comment by ironcladlou** [comment]
>If there are no triggers... It does know that there shouldn't be a deployment. Deployments shouldn't get created without a config change or image change trigger

There's never a point in time we can guarantee this anyway: the config resource we're acting upon could have been updated while we were in the process of making the RC. We can double-check and narrow the window.

Or we could just delete the config first and avoid all potential side effects. Why not?

**Comment by smarterclayton** [comment]
The update doesn't have any triggers.  So it shouldn't cause a deployment.

**Comment by smarterclayton** [comment]
Yes.  If it's not, it's broken.  No triggers means no deployments.

**Comment by ironcladlou** [comment]
Lack of triggers is still valid and can cause deployments in our current design. If you have no triggers, you can still kick off deployments manually by incrementing the version yourself (which is what the `deploy --latest` command does). How does the controller distinguish between that config update and an "inert" config updated by the reaper?

**Comment by smarterclayton** [comment]
> On Jun 3, 2015, at 8:34 PM, Dan Mace <notifications@github.com> wrote:
> 
> If there are no triggers... It does know that there shouldn't be a deployment. Deployments shouldn't get created without a config change or image change trigger
> 
> There's never a point in time we can guarantee this anyway: the config resource we're acting upon could have been updated while we were in the process of making the RC. We can double-check and narrow the window.
> 
That's a fair point - deployments can be arbitrarily delayed.  The point is if we delete the DC we don't have any way, if interrupted, to go back and delete it again.  So we need to fix the trigger problem, and then we're at least in the state that we can check that post rc creation we have no subsequent updates.

**Comment by smarterclayton** [comment]
> On Jun 3, 2015, at 8:37 PM, Dan Mace <notifications@github.com> wrote:
> 
> Lack of triggers is still valid and can cause deployments in our current design. If you have no triggers, you can still kick off deployments manually by incrementing the version yourself (which is what the deploy --latest command does). How does the controller distinguish between that config update and an "inert" config updated by the reaper?
> 
If you are kicking off manual deployment be you need to do that by creating a new rc.  The point of manual deployment is that they are "manual"

**Comment by ironcladlou** [comment]
@smarterclayton 
>If you are kicking off manual deployment be you need to do that by creating a new rc. The point of manual deployment is that they are "manual"

We've never discussed trying to enable clients to construct deployment/RC directly... the DeploymentConfigController is the thing that knows how to construct a deployment.

I'm still not sure what trying to untangle this buys us, when deleting the config first seems like a simple side-effect free to tear the deployment stuff down

**Comment by liggitt** [comment]
it's not re-entrant...

**Comment by smarterclayton** [comment]
Not being able to turn off a deployment config is a serious issue.

**Comment by ironcladlou** [comment]
@liggitt 
>it's not re-entrant...

That depends. The reaper only needs the config namespace and name to do its work. If it couldn't find the config to delete, it could still go on and find all the related orphaned resources based on that name and tear them down to finish the job.

**Comment by liggitt** [comment]
> If you are kicking off manual deployment be you need to do that by creating a new rc. The point of manual deployment is that they are "manual"

No, the point is that you *triggered* it manually. I don't want multiple things needing to understand how to turn a deployment+strategy into a replication controller.

**Comment by ironcladlou** [comment]
>Not being able to turn off a deployment config is a serious issue.

Removing triggers from the config today "turns them off" for some useful definition of "turn off". Manual deployments would continue to work, which seems fine.

**Comment by ironcladlou** [comment]
>If you are kicking off manual deployment be you need to do that by creating a new rc. The point of manual deployment is that they are "manual"
>>No, the point is that you triggered it manually. I don't want multiple things needing to understand how to turn a deployment+strategy into a replication controller.

Agree

**Comment by smarterclayton** [comment]
That's what an instantiate endpoint is for

**Comment by smarterclayton** [comment]
Would they?  That's my primary concern (no auto) but we can't redesign manual significantly at this point.

**Comment by ironcladlou** [comment]
>Would they? That's my primary concern (no auto) but we can't redesign manual significantly at this point.

Definitely... I use that often during testing. I create DCs with no triggers and use `deploy --latest` when I want a new one.

**Comment by ironcladlou** [comment]
@liggitt succinctly outlined the surprising behavior with delete in this case:
>create DC with no triggers, do a manual deployment, delete the RC, update the DC and another deployment gets auto-created

I agree that's a bad thing.

**Comment by ironcladlou** [comment]
I think there's more conversation to have about this, and I agree we need more changes to how triggers/manual are handled. In the short term, a re-entrant config-deleting reaper gets us past the races and leaves us with the possibility of an auto-deployment in @liggitt's use case (which is a condensed user-oriented version of the current reaper/stop bug scenario).

So is the config-first reaping is at least less broken? :smile: Think of the poor merge queue...

**Comment by liggitt** [comment]
deleting is different than pausing... as long as it is re-entrant, I'm fine with deleting DC first in the reaper

separately, we do need to be able to pause a DC, and I like moving manual deployments to an instantiate pattern for that

**Comment by smarterclayton** [comment]
How can it be reentrant if we delete the DC first? What DC am I going to delete the second time?  What if the DC has already been deleted?  Do I stop?

**Comment by smarterclayton** [comment]
Let's talk in the morning.

**Comment by liggitt** [comment]
you can reap the RC's for the deployment without the deployment config object

**Comment by smarterclayton** [comment]
What if someone else has created a new DC in the meantime?

**Comment by liggitt** [comment]
> What if someone else has created a new DC in the meantime?

fire them

**Comment by smarterclayton** [comment]
That's my line
