### ISSUE TITLE
can't modify default route when creating app via console

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2722]
When I point the console to a code repo and create an app, I can either create a route or not. The route that I create cannot be modified from its default.

```
[root@ose3-master beta4]# osc version
osc v0.5.2.2-18-gbf80a71
kubernetes v0.17.1-804-g496be63
```
![screenshot from 2015-06-02 21 31 56](https://cloud.githubusercontent.com/assets/94413/7950893/dc38ebc8-096e-11e5-8999-7a7ed70d1e24.png)

**Comment by jwforres** [comment]
Closing the issue since this has been trello'ed  https://trello.com/c/WSVk6KQk
