### ISSUE TITLE
Error in associateDeploymentConfigTriggersToBuild (overview.js)

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2725]
I noticed this error in the console after leaving the browser idle for a while.

```
TypeError: Cannot read property 'triggers' of undefined
    at associateDeploymentConfigTriggersToBuild (overview.js:289)
    at overview.js:316
    at Object.forEach (angular.js:331)
    at Object.<anonymous> (overview.js:315)
    at fire (jquery.js:3094)
    at Object.self.fireWith (jquery.js:3206)
    at Object.self.fire (jquery.js:3213)
    at data.js:627
    at Scope.$eval (angular.js:14383)
    at Scope.$apply (angular.js:14482)(anonymous function)
```

> @ angular.js:14484DataService._watchOpOnMessage @ data.js:626proxy

Here is the line with the problem in overview.js:

```
for (var i = 0; i < deploymentConfig.spec.triggers.length; i++) {
```

**Comment by liggitt** [comment]
that's curious...the API doesn't seem like it can return null for `spec`

**Comment by spadgett** [comment]
Hm, I'm not sure how this could happen unless the server sent us a deployment config with `spec` unset. I don't see us defaulting to `{}` or similar if `deploymentConfig` is `undefined`. I could add a null guard, but it shouldn't be necessary?

I also can't reproduce this problem. Looking at the stack trace, I see it happened when a deployment config was added or modified.

**Comment by spadgett** [comment]
Ah, this happens when the deployment config is deleted.

**Comment by liggitt** [comment]
good to know... as we start processing individual items in watch callbacks, we'll need to keep that in mind

**Comment by spadgett** [comment]
`spec` is defined, but `triggers` is not. This can be reproduced by deleting a deployment configuration such as `database` in the ruby hello world sample.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/7961839/f66518d2-09d7-11e5-8901-52d227f2a688.png)

**Comment by liggitt** [comment]
So that error, I understand (and we should always guard for), but the original error ("Cannot read property 'triggers' of undefined") I still don't get

**Comment by spadgett** [comment]
@liggitt Lower the severity or close and reopen if we see it again? #2738 fixes the reproducible problem.

**Comment by spadgett** [comment]
I suspect we're getting an error object back from the server, but `_watchOpOnMessage` is passing it to the controller as the deployment config.

**Comment by liggitt** [comment]
Yeah, that's it
