### ISSUE TITLE
deployment following build resets scale

### ISSUE THREAD

**Issue by bparees** [openshift/origin#2726]
1) deploy the ruby sample template, it runs 2 pods
2) scale it up to 4 pods (osc scale --replicas=4 dc frontend)
3) see 4 pods running
4) trigger another build
5) after the build completes and deploys, the new deployment has only 2 pods running (and a desired replica count of 2)

my understanding is that we're supposed to preserve the old number of replicas in this situation.

@smarterclayton

**Comment by smarterclayton** [comment]
Yes

**Comment by bparees** [comment]
@ironcladlou is this your area?

**Comment by ironcladlou** [comment]
Yeah, I'll audit the replica count preservation behavior.

**Comment by smarterclayton** [comment]
Or get Michaelis involved

**Comment by ironcladlou** [comment]
@bparees is this with `examples/sample-app/application-template-stibuild.json`?

**Comment by ironcladlou** [comment]
I tricked @kargakis into looking at it.

**Comment by kargakis** [comment]
Yep, I reproduced it. Looking
