### ISSUE TITLE
DNS search suffixes wrong post v1 DNS schema change

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#2731]
As discussed in https://github.com/openshift/origin/pull/2208#issuecomment-108311231:

The container search suffixes don't seem to have been updated to work with the new DNS schema. With 0.5.3 the search suffixes include `<namespace>.cluster.local` & `cluster.local` but not `<namespace>.svc.cluster.local`. Need to be able to query services in the same namespace from a pod without knowing namespace.

As an example:

```
$ cat /etc/resolv.conf 
nameserver 192.168.0.5
nameserver 8.8.8.8
nameserver 4.4.4.4
search default.cluster.local cluster.local localnet
$ dig +short +search kubernetes
$ dig +short +search kubernetes.default.svc.cluster.local
172.30.0.2
```

**Comment by smarterclayton** [comment]
We need to back port the upstream changes to the Kubelet - just landed yesterday https://github.com/GoogleCloudPlatform/kubernetes/pull/9080

**Comment by mwringe** [comment]
It looks like we can also remove the need for headless services with the new "<name>.<namespace>.endpoints.cluster.local".

So we have:
<name>.<namespace>.svc.cluster.local
<name>.<namespace>.endpoints.cluster.local

But we can only ever setup resolv.conf to resolve 'foo' to one of those endpoints, not both. So adding svc.<namespace>.cluster.local isn't going to solve the problem.

It might make sense to rename them to:

<name>.svc.<namespace>.cluster.local & <name>.endpoints.<namespace>.cluster.local 

And then just keep the search section of resolve.conf as is

That way if I want the service endpoint, I can do a lookup on "foo.svc" and if I want the list of pods, I can do a lookup on "foo.endpoints"

**Comment by jimmidyson** [comment]
True.

It's a shame that just endpoints was added tbh. Why couldn't just svc exist with A records for service ip & SRV records for service endpoints but using same name?

**Comment by smarterclayton** [comment]
What do you mean?  We can always expose endpoints differently.  Also, if you have port mappings the srv records won't be quite what you want.  Open to suggestions there

**Comment by smarterclayton** [comment]
What about _endpoints.<service>?

**Comment by jimmidyson** [comment]
I was thinking it would be nice to query DNS for different record types but same name, as in:

    dig srv <service>

to retrieve endpoints &:

    dig a <service>

to retrieve actual service IP.

Thinking about it though I guess it does make more sense to use a different name to retrieve the endpoints so you could use SRV records for a service to simply look up address & port for a service (using A records you obviously need to know the port you want to connect to) or even potentially do discovery across kube clusters or datacentres & properly prioritise those services (e.g. prefer local). Not sure about port mapping as haven't used it.

It feels much nicer to be able to query `<service>` rather than `<service>.svc` so would like at least the `svc.<namespace>.cluster.local` in the search suffixes. Much prefer `_endpoints.<service>` to `<service>.endpoints` as it is currently too but not precious about it. Using the `_endpoints` prefix means you don't need the `endpoints.<namespace>.cluster.local` as a search suffix either.

But I feel this is important to be consistent with upstream to enable portability so if we do make this change I'd like to see it pushed upstream if at all possible.

**Comment by smarterclayton** [comment]
9080 needs to be backported, assigning to @derekwaynecarr

**Comment by sdodson** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1228798
