### ISSUE TITLE
CONTRIBUTING.md creation request

### ISSUE THREAD

**Issue by nikitakoselev** [openshift/origin#27346]
The project is missing a CONTRIBUTING.md file.
The project is also missing any open "good first issue" tickets, which makes it harder for newcomers to contribute.

It might be a good idea to create a "good first issue" issue, with a request to create a CONTRIBUTING.md file.
It would be nice to provide a template for this file, based on other projects of OpenShift.

It would be also nice to mention all the different ways people can contribute to the project, in this CONTRIBUTING.md file:
* sharing insights of the project on Twitter
* maintaining project
* fixing tickets of all kinds
* checking existing issues and commenting on them, wherever it's needed
* ...

**Comment by Tasups** [comment]
I agree! I'd like to contribute and was just looking for a Code of Conduct and Contributing file.

**Comment by nikitakoselev** [comment]
Of course, it's OK. Even if CONTRIBUTING.md is empty, it's still better than nothing :)

Thank you for your contribution.

**Comment by Tasups** [comment]
Well, I'll see if I can do more than that!

**Comment by Vaani-pathariya** [comment]
can I do this one though I am new to openshift

**Comment by Avinash-Acharya** [comment]
> The project is missing a CONTRIBUTING.md file. The project is also missing any open "good first issue" tickets, which makes it harder for newcomers to contribute.
> 
> It might be a good idea to create a "good first issue" issue, with a request to create a CONTRIBUTING.md file. It would be nice to provide a template for this file, based on other projects of OpenShift.
> 
> It would be also nice to mention all the different ways people can contribute to the project, in this CONTRIBUTING.md file:
> 
> * sharing insights of the project on Twitter
> * maintaining project
> * fixing tickets of all kinds
> * checking existing issues and commenting on them, wherever it's needed
> * ...

Is there any way that I can contribute to this open source, as a rookie I have no idea how I can be of any help . being a student and knowing java I really want to learn many things, looking at guys like you out there always encourages me to know more .
