### ISSUE TITLE
Overview tab is not highlighted as selected after creating from template

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2736]
After clicking `Create` when creating from a template, you're taken back to the project overview. The `Overview` tab on the left does not have the selected style, however.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/7962480/8f42c484-09db-11e5-99aa-a9e9dc9b5748.png)

**Comment by spadgett** [comment]
This also happens after creating a new project in the Web Console.

**Comment by spadgett** [comment]
Unfortunately this is still an issue with the latest `hawtio-core-navigation`. It also occurs when picking a project from the all projects page, so nothing to do with URL query parameters.

**Comment by spadgett** [comment]
It looks like this check fails in some cases.

hawtio-core-navigation.js line 680:
```
answer = _.startsWith(path, href.path());
```

`path` is `"project/project1/overview"` and `href.path()` is `"/project/project1/overview"` with a leading `/`.

**Comment by spadgett** [comment]
Changing `href.path()` above to `itemPath` fixes both this and #2945.

**Comment by liggitt** [comment]
Make sure that works when running  under the root context, and when running under a sub context, like /console when running the compiled version

**Comment by liggitt** [comment]
The href check is attempting to normalize relative urls

**Comment by spadgett** [comment]
Earlier we have

```
        var href = new URI(tmpLink[0].href);
        var itemPath = trimLeading(href.path(), '/');

        var current = new URI();
        var path = trimLeading(current.path(), '/');
```

The sub tab check looks like this.

```
          if (item.isSubTab && _.startsWith(path, itemPath)) {
```

It looks like it might be an oversight not using `itemPath` later on. I'll test with root and sub contexts.

**Comment by liggitt** [comment]
Ah, probably an oversight
