### ISSUE TITLE
Sample-app gives 500 error error when pushing ruby-sample-app (using Vagrant)

### ISSUE THREAD

**Issue by guidoos** [openshift/origin#2740]
When following the sample app using the vagrant image (https://github.com/openshift/origin/blob/master/examples/sample-app/README.md) I try to build the sample app by using the following command:

osc process -f application-template-stibuild.json | osc create -f -

However, the build of ruby-sample-app fails because it cannot push the image to the docker registry:

Pushing 172.30.8.217:500/test/origin-ruby-sample:latest image ...
Failed to push image: Error pushing to registry: Server error: unexpected 500 response status trying to initiate upload of test/origin-ruby-sample

When I look at the logs of the running docker registry, I only see the following:
173.17.42.1 - - [03/Jun/2015:13:26:19 +0000] "POST /v2/test/origin-ruby-sample/blobs/uploads/ HTTP/1.1" 500 203 "" "docker/1.6.0 go/go1.4.2 kernel/3.17.4-301.fc21.x86_64 os/linux arch/amd64"

I retried the the complete instructions, but I can't seem to figure out the problem.

**Comment by gabemontero** [comment]
Hi - looked at a few permutations in trying to reproduce this, but did not have any luck.  I'll detail some of the specifics of my most recent attempt:

level of code:

[vagrant@openshiftdev ~]$ openshift version
openshift v0.5.4-34-g546fda9
kubernetes v0.17.1-804-g496be63

And I did it on a Fedora 21 system.

Of course, if there is a discrepancy of note with the openshift version, an upgrade in openshift could be warranted.

Steps from  origin/examples/sample-app/README.md that I executed:

step 2
step 3
step 4
step 5
( step 6 really no longer necessary ... we will be updating the readme)
step 7
step 8
step 10
step 15

[vagrant@openshiftdev sample-app]$ osc process -f application-template-stibuild.json | osc create -f -
services/frontend
routes/route-edge
imagestreams/origin-ruby-sample
imagestreams/ruby-20-centos7
buildconfigs/ruby-sample-build
deploymentconfigs/frontend
services/database
deploymentconfigs/database

As a side note, there is an easier alternative to the osc process pipping into osc create with newer builds, namely "osc new-app application-template-stibuild.json".  Also, some augmentation of the README.md and CONTRIBUTING.adoc have stemmed from our repro attemps, so thanks, though the items which generated these improvements were not issues in pushing to the registry.

But in any event, based on any repro's at later builds you might try, or any compare/constrast with the precise steps taken, we can see about next steps (including if need be resetting the openshift config files).

thanks,
gabe

**Comment by guidoos** [comment]
Thanks for your reply! I have retried all steps on a different machine (so no old openshift config present), no difference. I am on a Windows 8 machine, latest version of vagrant and virtualbox. My previous try was on a Windows 7 machine with the latest version of vagrant and virtualbox.

[vagrang@openshiftdev origin origin] openshift version
openshift v0.5.4-200-g1374886-dirty
kubernetes v0.17.1-804-g496be63

I did found the following when executing step 6 (curl the registry):
{"errors":[{"code":ÜNAUTHORIZED","message":"access to the requested resource is not authorized","detail":null}]}

I didn't noticed this earlier, but it seems that the error is related to no be able to push to the registry.

Sidenote: I also noted the following in the README: $OPENSHIFTCONFIG is set for /openshift.local.conf/master/admin.kubeconfig, but I think this should be /data/src/github.com/openshift/origin/example/sample-app/openshift.local.config/master/admin.kubeconfig. The outcome is the same though, no matter what $OPENSHIFTCONFIG is pointing to.

**Comment by liggitt** [comment]
@ncdc did something with registry auth change the steps needed to curl the registry?

**Comment by ncdc** [comment]
@liggitt the only unprotected registry route is /healthz now

**Comment by ncdc** [comment]
And if it's working, it will return an empty json map `{}`

**Comment by liggitt** [comment]
So this step should change in the readme:
```
Confirm the registry is accessible (you may need to run this more than once):

$ curl -H 'Accept: application/json' -v `oc get service docker-registry --template="{{ .spec.portalIP }}:{{ with index .spec.ports 0 }}{{ .port }}{{ end }}/v2/" --config=openshift.local.config/master/admin.kubeconfig`
```

**Comment by ncdc** [comment]
Yes

**Comment by liggitt** [comment]
@gabemontero can you update the readme with the /healthz URL and make sure the output is described correctly?

**Comment by mfojtik** [comment]
@liggitt @ncdc do we still have livenessProbe disabled for registry?

**Comment by ncdc** [comment]
@mfojtik yes. It's probably time to reenable it. https://github.com/openshift/origin/blob/master/pkg/cmd/admin/registry/registry.go#L246

**Comment by gabemontero** [comment]
Will do.

----- Original Message -----

**Comment by bparees** [comment]
@liggitt we're already removing the "curl the registry" step from the readme entirely, @gabemontero is on it.

**Comment by gabemontero** [comment]
Check that - we (Meaning Ben, Cesar, and I) had been proposing simply removing that curl step as no longer necessary / useful.

----- Original Message -----

**Comment by gabemontero** [comment]
@guidoos try unsetting  $OPENSHIFTCONFIG ;  I had to do that to work cluster config validation.  Perhaps you are hitting that as well under the covers.

**Comment by gabemontero** [comment]
I stumbled upon a repro of this issue doing some new feature development on a local openshift server.  Other than it not being on Vagrant, the error codes in the build and openshift internal docker registry logs were exactly the same.  I'm proposing  that the Vagrant vs. local distinction has no bearing.

With an assist from @ncdc (who I have sent the logs of my repro to), I have a work around that allowed my builds to finish after repeated builds failed.

You have to run:

sudo chcon -R -t svirt_sandbox_file_t   < path to your openshift.local.volumes directory > 

on the hosts where your openshift server is running.

**Comment by gabemontero** [comment]
Created PR https://github.com/openshift/origin/pull/3702 for the doc update Andy, Ben, and I discussed offf line.
