### ISSUE TITLE
Segfault on login

### ISSUE THREAD

**Issue by mgrabovsky** [openshift/origin#27478]
When I try to log in using the command generated by the OpenShift console, `oc login` fails with a segfault.

##### Version

    $ rpm -q origin-clients
    origin-clients-3.11.2-7.fc36.x86_64
    $ oc version
    oc v3.11.0+20c5b86
    kubernetes v1.10.0+b3b92b2
    features: Basic-Auth GSSAPI Kerberos SPNEGO
    
    Server [redacted]
    kubernetes v1.22.8+9e95cb9

##### Steps To Reproduce

1. Log in to an OpenShift console via the web UI.
2. Use the “Copy login command” function.
3. Copy and paste the generated command and press enter.

##### Current Result

`oc login` segfaults:

    $ oc login --token=sha256~[redacted] --server=[redacted]
    Logged into "[redacted]" as "mgrabovs" using the token provided.

    You have access to 523 projects, the list has been suppressed. You can list all projects with 'oc projects'

    Using project "".
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x41493c]

    goroutine 1 [running]:
    reflect.mapiternext(0x40?)
            /usr/lib/golang/src/runtime/map.go:1378 +0x19
    github.com/openshift/origin/vendor/github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x0?)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/modern-go/reflect2/unsafe_map.go:136 +0x32
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc00107fc50, 0xc0009f57a8, 0xc00106a780)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_map.go:273 +0x335
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc0005cc370?, 0xc96c87?, 0xc00106a798?)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:325 +0x22
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0010ad530, 0x2140d04?, 0xc00106a780)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc0010ad680, 0xc000ff6fc0?, 0xc00106a780)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x652
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc0005cc4e8?, 0xc96c87?, 0xc00106a798?)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:325 +0x22
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0010ad8f0, 0x20b24f3?, 0xc00106a780)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc0010ad950, 0xc0005cc620?, 0xc00106a780)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x652
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*sliceEncoder).Encode(0xc0006667b0, 0xc0015047e8, 0xc00106a780)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_slice.go:38 +0x2bb
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0010dc480, 0x20be9db?, 0xc00106a780)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc0010dc570, 0x0?, 0xc00106a780)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x652
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0005cc848?, 0x4103a5?, 0x238a080?)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_optional.go:74 +0xa4
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0007f2150, 0xc001504790, 0xc0005cc898?)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:213 +0x82
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*Stream).WriteVal(0xc00106a780, {0x24716e0, 0xc001504790})
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:93 +0x158
    github.com/openshift/origin/vendor/github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000186400, {0x24716e0, 0xc001504790})
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/config.go:296 +0xc9
    github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc0004e6770?, {0x2d20998?, 0xc001504790?}, {0x2d106a0, 0xc0010dd800})
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:226 +0x6d
    github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0001930e0, {0x2d20948?, 0xc00106b440}, {0x2d106a0, 0xc0010dd800})
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:221 +0x7c6
    github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime.Encode({0x7f184452a288, 0xc0001930e0}, {0x2d20948, 0xc00106b440})
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:46 +0x64
    github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd.Write(...)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd/loader.go:426
    github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0010dd1a0}, 0xc0010dd6e0, 0xc0010dd740, 0xc0010dd770, {0xc001099680, ...}, ...}, ...)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd/loader.go:406 +0xa8
    github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd.ModifyConfig({0x2d3a240, 0xc000f49b30}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0009f8300}, 0xc0009f8330, 0xc0009f8360, ...}, ...)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd/config.go:268 +0xb38
    github.com/openshift/origin/pkg/oc/cli/login.(*LoginOptions).SaveConfig(0xc0005cd790)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/login/loginoptions.go:382 +0x227
    github.com/openshift/origin/pkg/oc/cli/login.LoginOptions.Run({{0xc00005f980, 0x36}, {0x0, 0x0}, 0x0, {0xc00001d090, 0x8}, {0x0, 0x0}, {0x0, ...}, ...})
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/login/login.go:179 +0x38
    github.com/openshift/origin/pkg/oc/cli/login.NewCmdLogin.func1(0xc0012e5b80?, {0xc0015158e0, 0x0, 0x2})
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/login/login.go:59 +0x1c5
    github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc0012e5b80, {0xc001515880, 0x2, 0x2})
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:760 +0x663
    github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0012e5900)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:846 +0x2dc
    github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(...)
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:794
    main.main()
            /builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:70 +0x4db

And I'm still not logged in, `oc projects` doesn't list anything:

    $ oc projects
    Error from server (Forbidden): namespaces is forbidden: User "system:anonymous" cannot list resource "namespaces" in API group "" at the cluster scope

##### Expected Result

`oc login` succeeds and logs me in to the OpenShift instance. `oc projects` lists available projects on the corresponding instance.

##### Additional Information

Diagnostics:

    $ oc adm diagnostics
    [Note] Determining if client configuration exists for client/cluster diagnostics
    Info:  Successfully read a client config file at '/home/mgrabovs/.kube/config'
    [Note] Could not configure a client with cluster-admin permissions for the current server, so cluster diagnostics will be skipped

    [Note] Running diagnostic: ConfigContexts[/api-[redacted]/mgrabovs]
        Description: Validate client config context is complete and has connectivity
        
    ERROR: [DCli0002 from diagnostic ConfigContexts@openshift/origin/pkg/oc/cli/admin/diagnostics/diagnostics/client/config_contexts.go:221]
        The current client config context '/api-[redacted]/mgrabovs' is unusable:
            Client config context '/api-[redacted]/mgrabovs' has a user 'mgrabovs/api-[redacted]' which is not defined.
        
    [Note] Running diagnostic: DiagnosticPod
        Description: Create a pod to run diagnostics from the application standpoint
        
    ERROR: [DCli2001 from diagnostic DiagnosticPod@openshift/origin/pkg/oc/cli/admin/diagnostics/diagnostics/client/pod/run_diagnostics_pod.go:109]
        Creating diagnostic pod with image openshift/origin-deployer:v3.11.0 failed. Error: (*errors.errorString) an empty namespace may not be set during creation
        
    [Note] Summary of diagnostics execution (version v3.11.0+20c5b86):
    [Note] Errors seen: 2

**Comment by mgrabovsky** [comment]
@AObuchow Thanks for the tip. Though I'd prefer if this was fixed upstream – I'm using the Fedora package with the expectation that it Just Works.

**Comment by djdevin** [comment]
See also [#27166](https://github.com/openshift/origin/issues/27166)
