### ISSUE TITLE
Uniquely identify BuildPodController user

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#2774]
Currently builders are run under the user `system:openshift-client`.  However, builders may require escalated privileges which need to be controller by a security context constraint.  Granting an SCC to `system:openshift-client` is not a good solution since replication controllers also run with that user and we would effectively give escalated privileges to all pods.

/cc @csrwng @liggitt @pmorie

**Comment by liggitt** [comment]
To clarify, this is the user creating the build pod, not the service account for the pod itself
