### ISSUE TITLE
template parameter values to support expressions?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#2778]
it would be nice to default a template parameter value to use an expression.

e.g. when installing gogs (or any kind of SCM), you typically need to configure the hostname folks will use to access the git repos so folks can clone it. For a given namespace and environment that will map to some name. e.g. `gogs.${NAMESPACE}.mydomain.com.`

When creating services/routes, the `mydomain.com` would be parameterised; am sure other template areas would need this too.

So the gogs host name value should default to something like `gogs.${NAMESPACE}.${DOMAIN}` where `NAMESPACE` is the current namespace the template is being instantiated inside and `DOMAIN` is the global default domain.

e.g. 

```
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "gogs"
  },
  "parameters": [
    {
      "name": "GOGS_SERVER_DOMAIN",
      "description": "The gogs server name",
      "value": "gogs.${NAMESPACE}.${DOMAIN}"
    },
    {
      "name": "NAMESPACE",
      "description": "The current namespace"
    }
    {
      "name": "DOMAIN",
      "description": "The domain name applications are installed on",
      "value": "mydomain.com"
    }
  ]
}
```

Then when processing this template, the template parameter values would have their expressions replaced first; before the parameter values are used.

Right now it appears that the expressions inside a value are not replaced. i.e. the value of the `GOGS_SERVER_DOMAIN` is expanded to be `gogs.${NAMESPACE}.${DOMAIN}` rather than `gogs.cheese.mydomain.com`

**Comment by mfojtik** [comment]
@jstrachan this is actually pretty easy to implement... see the PR

**Comment by jstrachan** [comment]
@mfojtik lovely!

**Comment by mfojtik** [comment]
@smarterclayton @liggitt @bparees 

Resurrecting the discussion here. The main points from the PR were:

* Need to guard against cycles
* Need to think about the UI (the parameter referenced will appear in the UI text boxes)

I think the 1) item is doable as it just requires some code plumbing and error reporting. The 2) item might be hard as the UI will display the parameters which will be ugly and it also require users to understand what the parameters are and what names the parameters have.

**Comment by smarterclayton** [comment]
We should consider adding a specific type of parameter, rather than
changing the behavior of the default.  However, I'm still not convinced
this is a must have.

On Jul 7, 2015, at 6:21 AM, Michal Fojtik <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> @liggitt
<https://github.com/liggitt> @bparees <https://github.com/bparees>

Resurrecting the discussion here. The main points from the PR were:

   - Need to guard against cycles
   - Need to think about the UI (the parameter referenced will appear in
   the UI text boxes)

I think the 1) item is doable as it just requires some code plumbing and
error reporting. The 2) item might be hard as the UI will display the
parameters which will be ugly and it also require users to understand what
the parameters are and what names the parameters have.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2778#issuecomment-119161260>.

**Comment by bparees** [comment]
Anything done in this space should be tied in with the request to support defining parameters in terms of env variables, and also the ability to do env variable transformation.

https://trello.com/c/wFL654bW/608-support-translating-of-environment-variables-for-upstream-images

**Comment by smarterclayton** [comment]
Kube can now transform env vars in the pod definition.

On Jul 7, 2015, at 11:46 AM, Ben Parees <notifications@github.com> wrote:

Anything done in this space should be tied in with the request to support
defining parameters in terms of env variables, and also the ability to do
env variable transformation.

https://trello.com/c/wFL654bW/608-support-translating-of-environment-variables-for-upstream-images

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2778#issuecomment-119237407>.

**Comment by karelstriegel** [comment]
Use case : auto generation of routes, I allow users to define the prefix of their route, not the full address. 
E.g : <user_defined>.apps.mycloud.com

It would be an improvement if I could make use of the project/namespace in the template design, to force something like <user_defined>.<project>.apps.mycloud.com

**Comment by mfojtik** [comment]
@bparees all yours now :-)

**Comment by bparees** [comment]
@karelstriegel what you want is this card https://trello.com/c/zcRQFri0

**Comment by bparees** [comment]
closing based on age and not hearing any other requests for this capability.  We do still have the open card mentioned above for allowing ${NAMESPACE} to be a special parameter that gets auto-resolved for you.

also worth noting that the original issue could be resolved by simply referencing multiple parameters in a single field at the point of substutition, eg:

name: "${APP_NAME}.${NAMESPACE}.${DOMAIN}"

(and then having those 3 parameters defined).  it's not quite as clean as a single parameter defined in terms of the other 3 but i don't think it's that far off, especially relative to the complexity of implementing the requested feature and ensuring users understand how to use it correctly)
