### ISSUE TITLE
`osadm router --dry-run` doing test instead?

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#2783]
```
[root@master ~]# osadm router --dry-run \
> --credentials=/etc/openshift/master/openshift-router.kubeconfig
error: router "router" does not exist (no service)
[root@master ~]# osadm router  --credentials=/etc/openshift/master/openshift-router.kubeconfig
deploymentConfigs/router
services/router
```

Seems to me that first one should tell me everything is fine, not complain about the router not existing.

**Comment by brenton** [comment]
This is basically the same as https://github.com/openshift/origin/issues/2647.  I'll just close mine.

**Comment by sosiouxme** [comment]
Slight difference, this is with enough params to create the router, without --dry-run.

**Comment by fabianofranz** [comment]
@sosiouxme still an issue?

**Comment by sosiouxme** [comment]
@fabianofranz yes actually, though of course now it looks like:

```
# oadm policy  add-scc-to-user privileged system:serviceaccount:default:router
# oadm router --dry-run --credentials=/etc/origin/master/openshift-router.kubeconfig 
error: router "router" does not exist (no service)
# oadm router --credentials=/etc/origin/master/openshift-router.kubeconfig 
info: password for stats user admin has been set to FBQxBygNhX
deploymentconfig "router" created
service "router" created
```

**Comment by pweil-** [comment]
@fabianofranz @sosiouxme what is the correct behavior here?  It appears that the code is saying that if it is a dry run then tell the user that the router service does not exist which should mean it can be created.

This seems to be what the registry does as well:

```
[pweil@localhost origin]$ oadm registry --dry-run
error: Docker registry "docker-registry" service does not exist
[pweil@localhost origin]$ oadm router --dry-run
error: Router "router" service does not exist
```

**Comment by sosiouxme** [comment]
I would expect that the output would be simliar to what is output when
running without --dry-run.

```
# oadm router
info: password for stats user admin has been set to 00CeYcxiz9
serviceaccount "router" created
error: rolebinding "router-router-role" already exists
deploymentconfig "router" created
service "router" created
```

It seems to me the purpose of --dry-run is just to reflect what it would do
without actually doing it.

**Comment by sosiouxme** [comment]
```
$ oc adm router --dry-run
error: Router "router" service does not exist
```

Obviously... issue has been around for years, does not seem to raise much concern. Perhaps we'll be doing the router and registry differently soon anyway.
