### ISSUE TITLE
need client tools in db images

### ISSUE THREAD

**Issue by bparees** [openshift/origin#2805]
We need to make sure all the common client tools are installed in our db images.  it looks like they might be missing for mysql at a minimum.

@gshipley @thesteve0 fyi.

**Comment by mfojtik** [comment]
@bparees what you mean with client tools? the mysql command shouldnbe there.

**Comment by bparees** [comment]
@mfojtik @gshipley mentioned mysql-devel and i wasn't thinking at the time...  obviously mysql-devel makes no sense for the DB image since we're not building in them.  so we may have everything we need here.

i'm going to close it, @gshipley and @thesteve0 you can reopen if you find something critical missing.
