### ISSUE TITLE
osadm router/registry should determine images from master config

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2818]
So, as an example, when using enterprise, we shouldn't be referencing origin issues by default. The master has a config setting for the image naming string, but osadm router/registry don't inherit that.

It would be nice if osadm router --create would figure out the right image based on the master's config. Otherwise I have to override it _every time_ even if my master is "correctly" configured...

**Comment by thoraxe** [comment]
@sdodson

**Comment by danmcp** [comment]
@ncdc FYI

**Comment by liggitt** [comment]
router/registry commands don't have the master config...

**Comment by sdodson** [comment]
Could they just submit the ${component} and let the master evaluate the image template for that component rather than submitting the full image name?

**Comment by ncdc** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1228370

**Comment by smarterclayton** [comment]
You can probably mutate the constant during the OSE build.  The only other option is take master config as an argument and that may not be appropriate for other reasons.

**Comment by thoraxe** [comment]
@liggitt why don't router/registry commands have the master config? those commands talk to the master's API, and the master has its own config. Why doesn't the master interpret the API commands based on its configuration? It makes no sense...

**Comment by smarterclayton** [comment]
You can deploy any registry image you want.  The registry client does
nothing that any other app on openshift cannot achieve.

We could make the images flag required, and tell users to pick the
appropriate image name based on their image source (we can suggest
values).  Alternatively, the constant we use for the default value should
be set by the enterprise build.  The latter is probably better for users.

On Jul 3, 2015, at 10:04 AM, Erik M Jacobs <notifications@github.com> wrote:

@liggitt <https://github.com/liggitt> why don't router/registry commands
have the master config? those commands talk to the master's API, and the
master has its own config. Why doesn't the master interpret the API
commands based on its configuration? It makes no sense...

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2818#issuecomment-118359686>.

**Comment by thoraxe** [comment]
Requiring an images flag doesn't make sense to anyone -- OpenShift already knows what image format should be used by default. Why doesn't this particular command?

Setting the constant in the enterprise build makes a little bit of sense, but requires that each build system for OpenShift be configured to set such a thing.

Using the master's config file, which the master knows about, and is the endpoint for all commands (registry/router included), seems the most logical to me. I'm having a tough time understanding why a default setting of "if no --images flag is defined, use the master's configuration for images to determine the image name" is seemingly so unreasonable and is receiving such pushback...

What am I missing? This would work for origin, enterprise, and in just about any scenario imaginable, and would make sense to any user or administrator out there.

**Comment by ncdc** [comment]
I think trying to use the master config sounds good. **But**, it may not be available - an admin may run `oadm registry|router` from another system. Something to keep in mind...

**Comment by thoraxe** [comment]
@ncdc it shouldn't matter where I run `oadm registry` from. That command talks to an API that lives on the master, and the master is what interprets that command and turns it into a DC for the registry/router. Therefore, on the back-end of that command, the master config is *always* available, isn't it?

Yes, the CLI cannot read the master config, but the CLI isn't what's ultimately acting on that request. The Master is.

Unless what you are saying is `oadm registry` actually sends JSON/YAML to the Master API that defines the DC for the registry based on the user input? If that is the case then that was what I was missing.

**Comment by smarterclayton** [comment]
There is no reason a user has to install the same images the master has
configured to run a registry.  This is something the OSE build should
change the default constant on.

On Jul 3, 2015, at 5:06 PM, Erik M Jacobs <notifications@github.com> wrote:

@ncdc <https://github.com/ncdc> it shouldn't matter where I run oadm
registry from. That command talks to an API that lives on the master, and
the master is what interprets that command and turns it into a DC for the
registry/router. Therefore, on the back-end of that command, the master
config is *always* available, isn't it?

Yes, the CLI cannot read the master config, but the CLI isn't what's
ultimately acting on that request. The Master is.

Unless what you are saying is oadm registry actually sends JSON/YAML to the
Master API that defines the DC for the registry based on the user input? If
that is the case then that was what I was missing.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2818#issuecomment-118425432>.

**Comment by liggitt** [comment]
> Unless what you are saying is oadm registry actually sends JSON/YAML to the Master API that defines the DC for the registry based on the user input? If that is the case then that was what I was missing.

That's exactly what they do

**Comment by thoraxe** [comment]
OK -- now I understand why using the master config may be troublesome. It definitely leaves us in an interesting place in terms of user experience.

**Comment by sdodson** [comment]
I'll work on patching the default for OSE next week as that seems like the best way forward.

What's the general model we want to follow with these sort of tweaks? Patch the code? Set them at build time via ldflags?

**Comment by smarterclayton** [comment]
You should be able to override a single constant via ldflags (as an env
var, ideally).

On Jul 4, 2015, at 9:11 AM, Scott Dodson <notifications@github.com> wrote:

I'll work on patching the default for OSE next week as that seems like the
best way forward.

What's the general model we want to follow with these sort of tweaks? Patch
the code? Set them at build time via ldflags?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2818#issuecomment-118511571>.

**Comment by sdodson** [comment]
This seems like a corner case that's not likely to be problematic, but I just wanted to verify that we're ok with different builds of oadm (OSE vs Origin) having different defaults even though the same binary may ultimately be used against different environments (OSE vs Origin vs Online)?

**Comment by liggitt** [comment]
I'm not thrilled with it... especially when I see recommendations on mailing lists to "grab the latest client" to use against your server. As we move the router and registry to use service accounts, I'm wondering if those commands could be largely replaced with shipped registry and router templates, with correct image sources

**Comment by smarterclayton** [comment]
Yes, in the future.

On Jul 6, 2015, at 11:25 AM, Jordan Liggitt <notifications@github.com>
wrote:

I'm not thrilled with it... especially when I see recommendations on
mailing lists to "grab the latest client" to use against your server. As we
move the router and registry to use service accounts, I'm wondering if
those commands could be largely replaced with shipped registry and router
templates, with correct image sources

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2818#issuecomment-118890279>.

**Comment by ncdc** [comment]
+1 to baking in templates

**Comment by smarterclayton** [comment]
It's a good way to ensure our API is solving hard problems - like adding
secrets and volumes.  We lose some flexibility though, so I don't think
this is a straight up change.

On Jul 6, 2015, at 11:55 AM, Andy Goldstein <notifications@github.com>
wrote:

+1 to baking in templates

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2818#issuecomment-118907975>.

**Comment by thoraxe** [comment]
`oc adm router` is still a command. It looks like #54 that @sdodson referenced fixed this a long time ago?

**Comment by sdodson** [comment]
It's fixed in so much that the default image for OCP points at registry.access.redhat.com/openshift3/ose-... it's not fixed if you truly want the the image format string to be evaluated. I don't see this ever being fixed though.
