### ISSUE TITLE
Clean up test scripts for build logs

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2827]
Some of the test scripts switch back to cluster-admin user to do builds in order to view build logs. This is no longer necessary, and should be cleaned up so we exercise build logs as a normal user.

**Comment by stevekuznetsov** [comment]
This is in `test-cmd`? Is this still relevant with the refactor to buckets?

**Comment by wtrocki** [comment]
It looks like this issue is outdated and it can be closed.
Only place when login is happening:
https://github.com/openshift/origin/blob/master/hack/test-cmd.sh#L107

End to end tests:
https://github.com/openshift/origin/blob/master/hack/test-end-to-end.sh#L45-L52

**Comment by stevekuznetsov** [comment]
We still do quite a lot of `oc login` in the tests but I'm not seeing any use of `oc logs` with an elevated token or following an admin `oc login` in `test/end-to-end/core.sh`
