### ISSUE TITLE
Rolling-update should have a tunable for the % of pods to bring up at once

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#2828]
Make the rolling update scale amount configurable as a percent of the replica count.

Introduce a new optional deployment API field `strategy.rollingParams.updatePercent`. If specified, the amount of replicas scaled up and down each interval will be computed as a percentage of the desired replicas (for the new deployment) and the actual replicas (of the old deployment) respectively. If the field is nil, one replica will be scaled up and down each interval.

Depends on https://github.com/GoogleCloudPlatform/kubernetes/pull/10062.

**Comment by ironcladlou** [comment]
cc @abhgupta @smarterclayton

**Comment by ironcladlou** [comment]
This would have to be an upstream patch we'd carry, and seems nontrivial.

**Comment by smarterclayton** [comment]
Why?  We're only going to carry this for a matter of weeks, and the upstream code shouldn't be changing.

**Comment by abhgupta** [comment]
@smarterclayton I believe @ironcladlou's comments were in support of our argument for potentially pushing this past 3.0. Its ok if we don't want to make this determination right now and I am fine with it staying in P2. In the very least, I would suggest considering this lower priority than the other deployment items we are currently working on.

**Comment by smarterclayton** [comment]
Post 3.0

----- Original Message -----

**Comment by ironcladlou** [comment]
This should integrate with https://github.com/GoogleCloudPlatform/kubernetes/pull/10062

**Comment by ironcladlou** [comment]
Is there implied symmetry with the scale-down? When scaling up X%, should X% then be scaled down each interval?

**Comment by smarterclayton** [comment]
I think so.  I don't see a need for a difference

On Jun 29, 2015, at 3:27 PM, Dan Mace <notifications@github.com> wrote:

Is there implied symmetry with the scale-down? When scaling up X%, should
X% then be scaled down each interval?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2828#issuecomment-116806707>.

**Comment by ironcladlou** [comment]
@smarterclayton 

Should this wait for an upstream merge of https://github.com/GoogleCloudPlatform/kubernetes/pull/10062? If not, should it be developed in origin on top of our patch?

**Comment by smarterclayton** [comment]
Should not not wait

On Wed, Jul 1, 2015 at 10:33 AM, Dan Mace <notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton>
>
> Should this wait for an upstream merge of
> GoogleCloudPlatform/kubernetes#10062
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/10062>? If not,
> should it be developed in origin on top of our patch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2828#issuecomment-117696909>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
@smarterclayton 

I have a WIP upstream branch where I'm developing the support on top of the UpdateAcceptor commit:

https://github.com/GoogleCloudPlatform/kubernetes/compare/master...ironcladlou:rolling-updater-tunables?expand=1

Adding the scale amount tunable wasn't too bad, but the problem now is testing it. The complexity of `RollingUpdater.Update` is getting pretty large, and the test cases are becoming almost incomprehensible. I'm afraid it might be time to refactor this thing and the tests before bolting on even more stuff. What do you think?

**Comment by smarterclayton** [comment]
Up to you - i'd rather not get weighed down in a big refactor though if we
can selectively introduce parts of it.  Agree RollingUpdater.Update is
large today.

On Wed, Jul 1, 2015 at 5:09 PM, Dan Mace <notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton>
>
> I have a WIP upstream branch where I'm developing the support on top of
> the UpdateAcceptor commit:
>
>
> https://github.com/GoogleCloudPlatform/kubernetes/compare/master...ironcladlou:rolling-updater-tunables?expand=1
>
> Adding the scale amount tunable wasn't too bad, but the problem now is
> testing it. The complexity of RollingUpdater.Update is getting pretty
> large, and the test cases are becoming almost incomprehensible. I'm afraid
> it might be time to refactor this thing and the tests before bolting on
> even more stuff. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2828#issuecomment-117825379>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
I don't really want to carry a big refactor. I'm going to see if I can limp by with the existing tests for the moment.

**Comment by ironcladlou** [comment]
Regarding symmetry: if you choose 20% and have an asymmetrical old/new (10 old, 20 desired for new), should old AND new be scaled down by 4 each interval, or should old scale by 2 and new by 4?

**Comment by smarterclayton** [comment]
I don't think we need asymmetry - haven't heard a compelling use case

On Jul 2, 2015, at 11:58 AM, Dan Mace <notifications@github.com> wrote:

Regarding symmetry: if you choose 20% and have an asymmetrical old/new (10
old, 20 desired for new), should old AND new be scaled down by 4 each
interval, or should old scale by 2 and new by 4?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/2828#issuecomment-118077032>.

**Comment by ironcladlou** [comment]
@smarterclayton 

[My upstream branch](https://github.com/GoogleCloudPlatform/kubernetes/compare/master...ironcladlou:rolling-updater-tunables?expand=1) has unit tested code to support the percentage configuration. I had to do a bit of refactoring to the rolling updater so that I could reign in the tests. They're much better than before IMO, but it's a lot of test code. You want to review it and decide if it looks like something we want to try and carry in a patch?

**Comment by smarterclayton** [comment]
I can't comment on the branch (have a few things) but it looks acceptable
to carry.

On Thu, Jul 2, 2015 at 1:23 PM, Dan Mace <notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton>
>
> My upstream branch
> <https://github.com/GoogleCloudPlatform/kubernetes/compare/master...ironcladlou:rolling-updater-tunables?expand=1>
> has unit tested code to support the percentage configuration. I had to do a
> bit of refactoring to the rolling updater so that I could reign in the
> tests. They're much better than before IMO, but it's a lot of test code.
> You want to review it and decide if it looks like something we want to try
> and carry in a patch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2828#issuecomment-118098780>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
For an upstream pull, should I replace https://github.com/GoogleCloudPlatform/kubernetes/pull/10062 with a new PR containing the UpdateAcceptor commit and the new percentage stuff? Or keep them separate and link the new one as a dependency of the first?

**Comment by smarterclayton** [comment]
update the existing PR and change the descriptions to match

On Thu, Jul 2, 2015 at 3:47 PM, Dan Mace <notifications@github.com> wrote:

> For an upstream pull, should I replace
> GoogleCloudPlatform/kubernetes#10062
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/10062> with a new
> PR containing the UpdateAcceptor commit and the new percentage stuff? Or
> keep them separate and link the new one as a dependency of the first?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/2828#issuecomment-118144132>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
I've expanded https://github.com/GoogleCloudPlatform/kubernetes/pull/10062 to include both the UpdateAcceptor and the tunable.
