### ISSUE TITLE
Docker Hub image openshift/origin-cli no longer available to the public

### ISSUE THREAD

**Issue by donkeybanana** [openshift/origin#28339]
The Docker repo at https://hub.docker.com/r/openshift/origin-cli is now gone/private, while the repo at https://quay.io/repository/openshift/origin-cli is still available publicly.

This seems to have happened overnight so currently unable to find any reasoning stated publicly.

##### Version
Any valid image tag for `openshift/origin-cli`.

##### Steps To Reproduce
1. `docker pull openshift/origin-cli`
2. Note the error below

##### Current Result

Unable to pull the image from Docker Hub.

```
docker pull openshift/origin-cli
Using default tag: latest
Error response from daemon: pull access denied for openshift/origin-cli, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

##### Expected Result

Image pull works the same as the repo at https://quay.io/repository/openshift/origin-cli.

##### Additional Information

The other images are still publicly available at Docker Hub so the fact this particular image has been removed/made private is confusing.

**Comment by DavidSint** [comment]
Registering that I am also affected by this issue

**Comment by desjoyce** [comment]
me too.


**Version**
Any valid image tag for openshift/origin-control-plane.

**Step**
1. docker pull openshift/origin-control-plane:v3.11
2. Note the error below

```
Error response from daemon: pull access denied for openshift/origin-control-plane, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by thurcombe** [comment]
We also experienced this over the weekend with the logging curator image.

`$ docker pull openshift/origin-logging-curator5:v3.11
Error response from daemon: pull access denied for openshift/origin-logging-curator5, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by jupierce** [comment]
Hi all. Docker is looking into the disappearance of these repositories for us. Please let me know what you are using this distribution channel for. To the best of my knowledge, this is not an official channel for any content and no image in docker `openshift/*` has received security patches in a very long time. OpenShift v3.11 is [end-of-life](https://access.redhat.com/support/policy/updates/openshift).
Public OKD images from quay.io are a viable alternative (but any EOL release, like v3.11, should be assumed to be vulnerable to known CVEs).

**Comment by LorbusChris** [comment]
It seems a lot of the ImageStream examples in this repo are outdated.

Should this be switched to inherit the imagestreams from https://github.com/openshift/library (similar to what is done for https://github.com/openshift/cluster-samples-operator/)?

I recently cleaned out a lot of deprecated imagestreams from library in https://github.com/openshift/library/pull/350,
but it looks like there's no automation to update the cluster-samples-operator ISs from there (some images acutely breaking CI were removed manually in https://github.com/openshift/cluster-samples-operator/pull/519)

**Comment by dedavide** [comment]
> Hi all. Docker is looking into the disappearance of these repositories for us. Please let me know what you are using this distribution channel for. To the best of my knowledge, this is not an official channel for any content and no image in docker `openshift/*` has received security patches in a very long time. OpenShift v3.11 is [end-of-life](https://access.redhat.com/support/policy/updates/openshift). Public OKD images from quay.io are a viable alternative (but any EOL release, like v3.11, should be assumed to be vulnerable to known CVEs).

so the removal was not planned but it's an accident?

**Comment by jupierce** [comment]
An ownership transfer caused the problem. So the disappearance was not planned. *However*, I do expect these repositories to be shutdown in the future, so I recommend everyone migrate @dedavide .
