### ISSUE TITLE
SDN assigns duplicate subnets

### ISSUE THREAD

**Issue by detiber** [openshift/origin#2834]
When adding additional nodes to a running cluster, we are seeing that duplicate subnets are being defined.

output of osc get hostSubnet prior to adding nodes:
ip-172-19-48-236.ec2.internal   ip-172-19-48-236.ec2.internal   172.19.48.236   10.0.0.0/16
ip-172-19-53-204.ec2.internal   ip-172-19-53-204.ec2.internal   172.19.53.204   10.3.0.0/16
ip-172-19-53-205.ec2.internal   ip-172-19-53-205.ec2.internal   172.19.53.205   10.2.0.0/16
ip-172-19-53-206.ec2.internal   ip-172-19-53-206.ec2.internal   172.19.53.206   10.5.0.0/16
ip-172-19-53-207.ec2.internal   ip-172-19-53-207.ec2.internal   172.19.53.207   10.4.0.0/16
ip-172-19-53-208.ec2.internal   ip-172-19-53-208.ec2.internal   172.19.53.208   10.1.0.0/16
ip-172-19-60-228.ec2.internal   ip-172-19-60-228.ec2.internal   172.19.60.228   10.6.0.0/16

output of osc get hostSubnet after adding nodes:
ip-172-19-46-156.ec2.internal   ip-172-19-46-156.ec2.internal   172.19.46.156   10.10.0.0/16
ip-172-19-46-157.ec2.internal   ip-172-19-46-157.ec2.internal   172.19.46.157   10.1.0.0/16
ip-172-19-46-158.ec2.internal   ip-172-19-46-158.ec2.internal   172.19.46.158   10.5.0.0/16
ip-172-19-46-159.ec2.internal   ip-172-19-46-159.ec2.internal   172.19.46.159   10.7.0.0/16
ip-172-19-46-160.ec2.internal   ip-172-19-46-160.ec2.internal   172.19.46.160   10.4.0.0/16
ip-172-19-46-161.ec2.internal   ip-172-19-46-161.ec2.internal   172.19.46.161   10.0.0.0/16
ip-172-19-46-162.ec2.internal   ip-172-19-46-162.ec2.internal   172.19.46.162   10.3.0.0/16
ip-172-19-46-163.ec2.internal   ip-172-19-46-163.ec2.internal   172.19.46.163   10.8.0.0/16
ip-172-19-46-164.ec2.internal   ip-172-19-46-164.ec2.internal   172.19.46.164   10.11.0.0/16
ip-172-19-46-165.ec2.internal   ip-172-19-46-165.ec2.internal   172.19.46.165   10.9.0.0/16
ip-172-19-46-166.ec2.internal   ip-172-19-46-166.ec2.internal   172.19.46.166   10.6.0.0/16
ip-172-19-46-167.ec2.internal   ip-172-19-46-167.ec2.internal   172.19.46.167   10.2.0.0/16
ip-172-19-48-236.ec2.internal   ip-172-19-48-236.ec2.internal   172.19.48.236   10.0.0.0/16
ip-172-19-53-204.ec2.internal   ip-172-19-53-204.ec2.internal   172.19.53.204   10.3.0.0/16
ip-172-19-53-205.ec2.internal   ip-172-19-53-205.ec2.internal   172.19.53.205   10.2.0.0/16
ip-172-19-53-206.ec2.internal   ip-172-19-53-206.ec2.internal   172.19.53.206   10.5.0.0/16
ip-172-19-53-207.ec2.internal   ip-172-19-53-207.ec2.internal   172.19.53.207   10.4.0.0/16
ip-172-19-53-208.ec2.internal   ip-172-19-53-208.ec2.internal   172.19.53.208   10.1.0.0/16
ip-172-19-60-228.ec2.internal   ip-172-19-60-228.ec2.internal   172.19.60.228   10.6.0.0/16

**Comment by detiber** [comment]
@rajatchopra We are seeing this in the demo env. It only seems to affect us when adding nodes after the initial cluster spinup (say a day later).  openshift-master is also restarted in between the initial nodes being added and subsequent nodes being added.

@sdodson @brenton @thoraxe: FYI for beta4

**Comment by rajatchopra** [comment]
Fixed with https://github.com/openshift/openshift-sdn/pull/82
Tested on a running cluster and the fix works. Test with new cluster creation pending.
