### ISSUE TITLE
Better documentation for getting started with Openshift3

### ISSUE THREAD

**Issue by frankcarey** [openshift/origin#2848]
I ran into some snags that were confusing, and I think should be documented in the Getting started sections to save people some headache. It says docker is the easiest way to get started, but it should have a bit more info there to make it actually easy to get started. [I'll update this as I go, in getting things setup]
- _Needs to use https:// urls, not http_ - This really threw me for a loop. I as using http, but connecting to the 8443 port. This causes strange behavior in chrome where a blank page is downloaded and almost no errors. I finally noticed that 8443 is probably and alternative for 443 (SSL) and then changing to https fixed it. I think this should be clarified up front. (Why doesn't it just use 443 anyways?)
- You NEED to set the external ip / hostname when starting openshift container for the console to work, otherwise you get redirected to the internal ip address. 
- Not clear how to setup users. Seems like the easy way to get started is just to use: 
  `sudo docker exec -it openshift-origin bash -c "osadm policy add-cluster-role-to-gro
  up cluster-admin system:authenticated system:unauthenticated --config=/var/lib/openshift/openshift.local.config/mas
  ter/admin.kubeconfig"`
- Is there a specific host OS that I need to use? I wanted to use the base images that come with google compute engine. First I tried CentOS 6.6, but that didn't come with docker out of the box (no surprise), Then I tried a CoreOS image, but stable didn't have docker 1.6 (which I read somewhere is required?), So then I moved to CoreOS beta, which has docker-1.6. That is where I ended up figuring out the https issue, and now I can log into the management console. It would be nice to know early, if there are any host restrictions (like am I going down the wrong path by using CoreOS?)
- A visualization of what's going on would also be helpful, especially for the networking... I'm still not sure if the master / nodes (running on the host in docker) are going to create new containers within themselves (docker within docker) or if they will live on the host... If I recall, I don't think docker was installed in the openshift/origin container.
- Part of my debugging involved trying a different openshift/origin version(tag) like so: `run -d --name "openshift-origin" --net=host --privileged     -v /var/run/docker.sock:/var/run/docker.sock     openshift/origin:v0.5.4 start`  (note the :v0.5.4 tag) .. does it make more sense to grab master or an actual beta release.
- The M version (M4, M5) vs github version (0.4.x, 0.5.x) vs openshift major version (2 or 3) vs beta versioning (openshift 3 beta 4 is v0.5.4?) was really confusing to me, and made finding instructions, etc really hard. It would be nice to have a cheat sheet in the readme perhaps?

**Comment by danmcp** [comment]
> Needs to use https:// urls, not http - This really threw me for a loop. I as using http, but connecting to the 8443 port. This causes strange behavior in chrome where a blank page is downloaded and almost no errors. I finally noticed that 8443 is probably and alternative for 443 (SSL) and then changing to https fixed it. I think this should be clarified up front. (Why doesn't it just use 443 anyways?)

Where is the reference to http:// or a reference without https://?

**Comment by frankcarey** [comment]
You are correct of course, that https is shown at https://github.com/openshift/origin/#web-console .. Where I had trouble was partly that I didn't notice the https:// there, but also since `localhost` wasn't relevant to me setting things up remotely, I had to change it to a specific ip address and when I did that without https:// specifically stated, the browser (chrome at least) assumes that it's http, and then gets all kinds of confused when trying to access the SSL port via http. I think this might be a more common issue since the SSL port isn't the default. It was confusing where the issue was, so I ended up debugging things at each layer (container, host, remote) using curl and working from the "inside-out" to make sure the port mappings,etc were working. (I'll make a patch for everything here to help the next folks, because if it wasn't for these confusing issues slowing me down for hours, getting up with docker is super nice :) ..I"ll keep plugging away and put it all in this ticket, get some feedback, and then I'll help update any docs.

**Comment by zakjan** [comment]
> You NEED to set the external ip / hostname when starting openshift container for the console to work, otherwise you get redirected to the internal ip address.

It happens for me. How can I set the hostname during `docker run ... openshift/origin start`?

**Comment by liggitt** [comment]
Add `--public-master=https://<reachable-ip-or-host>:8443`

**Comment by max-zelinski** [comment]
@liggitt add where?

**Comment by liggitt** [comment]
To the docker run, as args to the `start` command

**Comment by Anandanr** [comment]
Hi, When I trying to add public master like follows, no success. any clue.
root@apachestratos-1a:~# docker run -d --name "origin"         --privileged --pid=host --net=host     --public-master=https://10.10.103.246:8443  -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw         -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes         openshift/origin start
flag provided but not defined: --public
See 'docker run --help'.
root@apachestratos-1a:~#

**Comment by rudijs** [comment]
@Anandanr I just found this issue as it's related to a problem I have as well.

The solution for me is to use `--public-master=https://10.10.103.246:8443` as an option to openshift not to docker.

This means adding `--public-master=https://10.10.103.246:8443` at the end of your command.

I'm using a local VM with docker machine. This is my start command:

```
docker run -d --name "origin" \
        --privileged --pid=host --net=host \
        -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw \
        -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes \
        --net host openshift/origin start --public-master=https://192.168.33.100:8443
```

**Comment by pweil-** [comment]
closing due to age.  The contributing guide is being updated with the latest ways to get started
