### ISSUE TITLE
custom-build: enable mounting volumes from host

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#2849]
We have a use case where we want to mount a directory from host to build container during build. We would like to use this to propagate some build artifacts from build to some NFS shares. Does this make sense?

**Comment by bparees** [comment]
@markturansky how feasible is this?  if we define a build pod with some NFS volume, and then the build pod is deleted, i assume the NFS volume gets reclaimed?

@TomasTomecek is this output only?  or do you want those artifacts to be consumed by the next build too?

**Comment by markturansky** [comment]
@bparees Recycling an NFS volume is optional.  The field PV.Spec.PersistentVolumeClaimPolicy defaults to Retain but would need to be set to Recycle.  The volume is only recycled when the claim to it is deleted (volume is released).

Using NFS to keep builds around in between pods would work just fine.  When the build server pod deletes its PVC, that's when the NFS volume is recycled (if set to recycle).

**Comment by TomasTomecek** [comment]
We would use it probably just for one build. Then we would spin another volume. Tbh I'm still not sure about the overall design. Let me think about this a bit more.

**Comment by TomasTomecek** [comment]
We have figure this out: since build container is privileged, we can mount directly inside it -- no need to interact with host.

Another use case for this is for debugging: when you want bindmount stuff from your host inside build container without continual rebuilding of the build image.

Feel free to wontfix this.

**Comment by bparees** [comment]
Thanks @TomasTomecek , closing.
