### ISSUE TITLE
Update UI to oapi/v1

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2851]
oapi/v1
- [ ] de-embedding Image from ImageStreamTag and ImageStreamImage
- [ ] remove imageName from ImageStreamTag and ImageStreamImage
- [ ] Change trigger values to initial upper-case (GitHub, Generic, ImageChange)

api/v1
- [ ] status change from "termination" to "terminated"
- [ ] null `replicas` field in replication controller means 1, undefined means 0
- [ ] changes in https://github.com/openshift/origin/issues/3331
- [ ] Container.Image changed can be missing (though validation still requires it)
- [ ] ServiceSpec.portalIP -> ServiceSpec.clusterIP
- [ ] ServiceSpec.createExternalLoadBalancer deleted
- [ ] ServiceSpec.publicIPs -> ServiceSpec.deprecatedPublicIPs
- [ ] StatusDetails.id -> StatusDetails.name
- [ ] PodSpec.privileged deprecated
- [ ] PodSpec.capabilities deprecated
- [ ] PodSpec.serviceAccount -> PodSpec.serviceAccountName
- [ ] PodSpec.host -> PodSpec.nodeName
- [ ] PodStatus.Condition -> PodStatus.conditions
- [ ] PodStatus.termination -> PodStatus.terminated
- [ ] ReplicationControllerSpec.replicas default (when missing) is 1. Can be 0, so watch out for falsiness.
- [ ] Endpoints.IP -> Endpoints.ip

**Comment by ncdc** [comment]
I'm working on de-embedding Image from ImageStreamTag and ImageStreamImage. The UI will need to be updated accordingly, e.g. scope.image = image.image (probably should rename the first image to imageStreamTag).

**Comment by spadgett** [comment]
@liggitt any issues if we stay on v1beta3 and we get a template that uses v1?

**Comment by spadgett** [comment]
Or an encoded deployment config annotation that uses v1?

**Comment by liggitt** [comment]
the only place we use `encodedDeploymentConfig` is in `deploymentCauses`, and that already recognizes v1.
For templates, we should probably make `DataService.createList` tolerant of getting types it doesn't recognize and surfacing errors.

**Comment by liggitt** [comment]
Changes in kubernetes v1beta3 -> v1:

Container.Image changed can be missing (though validation still requires it)

ServiceSpec.portalIP -> ServiceSpec.clusterIP
ServiceSpec.createExternalLoadBalancer deleted
ServiceSpec.publicIPs -> ServiceSpec.deprecatedPublicIPs

StatusDetails.id -> StatusDetails.name

PodSpec.privileged deprecated
PodSpec.capabilities deprecated
PodSpec.serviceAccount -> PodSpec.serviceAccountName
PodSpec.host -> PodSpec.nodeName

PodStatus.Condition -> PodStatus.conditions
PodStatus.termination -> PodStatus.terminated

ReplicationControllerSpec.replicas default (when missing) is 1. Can be 0, so watch out for falsiness.

Endpoints.IP -> Endpoints.ip
