### ISSUE TITLE
Fail back a deployment

### ISSUE THREAD

**Issue by abhgupta** [openshift/origin#2854]
Separate issue for item listed in https://github.com/openshift/origin/issues/2455

I should be able to "fail back" a deployment - scale back up the N-1 deployment and mark the latest failed, even after it's complete. Example - I rollout a change, I realize it's bad, i don't want to disable automatic updates, but I do want to not deploy until another automatic change happens. I want to scale N-1 back up, scale N down to zero, and mark N failed.

**Comment by abhgupta** [comment]
@smarterclayton @ironcladlou Here are my thoughts/questions.

1. We will fail-back to the last successful deployment.
2. If the latest deployment is in new/pending/running state, the user will have to cancel it first.
3. If the latest deployment is in the failed state, we will simply revert back to the last successful deployment. 
4. If the latest deployment is in the completed state, we will mark this deployment as failed and then revert back to the last successful deployment.

**Comment by smarterclayton** [comment]
----- Original Message -----
> @smarterclayton @ironcladlou Here are my thoughts/questions.
> 
> 1. We will fail-back to the last successful deployment.

What if I scaled up my failed deployment?

> 2. If the latest deployment is in new/pending/running state, the user will
> have to cancel it first.
> 3. If the latest deployment is in the failed state, we will simply revert
> back to the last successful deployment.

What do you mean by revert?

> 4. If the latest deployment is in the completed state, we will mark this
> deployment as failed and then revert back to the last successful deployment.

I don't know what that means.

**Comment by abhgupta** [comment]
----- Original Message -----

> From: "Clayton Coleman" <notifications@github.com>
> To: "openshift/origin" <origin@noreply.github.com>
> Cc: "Abhishek Gupta" <abhgupta@redhat.com>
> Sent: Friday, June 5, 2015 8:51:49 AM
> Subject: Re: [origin] Fail back a deployment (#2854)

> ----- Original Message -----
> > @smarterclayton @ironcladlou Here are my thoughts/questions.
> >
> > 1. We will fail-back to the last successful deployment.

> What if I scaled up my failed deployment?

This is covered by point 2 and 4. 

> > 2. If the latest deployment is in new/pending/running state, the user will
> > have to cancel it first.
> > 3. If the latest deployment is in the failed state, we will simply revert
> > back to the last successful deployment.

> What do you mean by revert?
"Revert" was just the name of the flag that I was thinking about using for the <osc deploy> command. 
Revert will behave the same as rollback to a specific previous deployment. 
The user could use: 
osc deploy <dc-name> --revert 
and this could "revert" back to the last successful deployment. 
Revert will create a new deployment, just as rollback does. 

> > 4. If the latest deployment is in the completed state, we will mark this
> > deployment as failed and then revert back to the last successful
> > deployment.

> I don't know what that means.
This is what you had mentioned in the issue. If the latest deployment is successful, 
we will mark that as failed and then revert the DC to the config of the last successful deployment. 
This will not be the latest deployment since that is now placed in the failed state. 
We will also bump up the LatestVersion so that a new deployment will be created.

**Comment by smarterclayton** [comment]
----- Original Message -----
> ----- Original Message -----
> 
> > From: "Clayton Coleman" <notifications@github.com>
> > To: "openshift/origin" <origin@noreply.github.com>
> > Cc: "Abhishek Gupta" <abhgupta@redhat.com>
> > Sent: Friday, June 5, 2015 8:51:49 AM
> > Subject: Re: [origin] Fail back a deployment (#2854)
> 
> > ----- Original Message -----
> > > @smarterclayton @ironcladlou Here are my thoughts/questions.
> > >
> > > 1. We will fail-back to the last successful deployment.
> 
> > What if I scaled up my failed deployment?
> 
> This is covered by point 2 and 4.
> 
> > > 2. If the latest deployment is in new/pending/running state, the user
> > > will
> > > have to cancel it first.
> > > 3. If the latest deployment is in the failed state, we will simply revert
> > > back to the last successful deployment.
> 
> > What do you mean by revert?
> "Revert" was just the name of the flag that I was thinking about using for
> the <osc deploy> command.
> Revert will behave the same as rollback to a specific previous deployment.
> The user could use:
> osc deploy <dc-name> --revert
> and this could "revert" back to the last successful deployment.
> Revert will create a new deployment, just as rollback does.

Why would we have revert and rollback?  If a deployment fails it should clean itself up or stop.  If we just stop, then we need a clean up, which is either scale=0 or happens automatically.

Think about this from the perspective of an automated security update.

1. App is at deployment #2
2. Security update triggers, resulting in a new build
3. App starts rolling out #3
4. Canary fails

What does the user want?  They really don't want any of #3 still deployed (they don't want it taking traffic, which could be readiness).  There's no point to having a revert... because there won't be a new #3 created.

> 
> > > 4. If the latest deployment is in the completed state, we will mark this
> > > deployment as failed and then revert back to the last successful
> > > deployment.
> 
> > I don't know what that means.
> This is what you had mentioned in the issue. If the latest deployment is
> successful,
> we will mark that as failed and then revert the DC to the config of the last
> successful deployment.

Why are we reverting the DC?  The whole point of stopping is to scale the new thing down to 0.

**Comment by abhgupta** [comment]
We currently don't perform any clean up when a deployment fails. 

We will set the replica to 0 for the failed deployment. This update will be performed in a single shot (replicas updated to 0 directly).

Q: Should we automatically scale up the previous successful deployment? Also, can we simply set the replicas to the final/expected/desired value in a single shot? I don't think it makes sense to stagger the scale up and deal with readiness checks and canaries and so forth.

**Comment by smarterclayton** [comment]
----- Original Message -----
> We currently don't perform any clean up when a deployment fails.
> 
> We will set the replica to 0 for the failed deployment. This update will be
> performed in a single shot (replicas updated to 0 directly).
> 
> Q: Should we automatically scale up the previous successful deployment? 

If we scale down to 0, we have to restore the previous.  If we leave as is, we wouldn't change the previous.  If the attempt to reset the counters fails, we retry a few times and then die.  Restore to previous can be one shot.

**Comment by ironcladlou** [comment]
The previous deployment's desired replicas will be in the `DesiredReplicasAnnotation` annotation, so that's at least one way to restore a previously valid number, but it doesn't necessarily match what the replica count was at the time of scale-down (the user could have manually resized it).

**Comment by abhgupta** [comment]
@ironcladlou One possible solution is to use the `DesiredReplicasAnnotation` value of the current/failed deployment. I am leaning towards this at the moment.

**Comment by ironcladlou** [comment]
>@ironcladlou One possible solution is to use the DesiredReplicasAnnotation value of the current/failed deployment. I am leaning towards this at the moment.

That seems reasonable, as the value was computed based on the replicas of the prior deployment. Sounds like a winner to me.

**Comment by abhgupta** [comment]
@ironcladlou and I were discussing this and he brought up an interesting point:

Question: who should be responsible for the clean up in case of a failed deployment?

 - Let the platform do the clean up
   - individual strategies need not worry about clean up
   - will also cover custom strategies
 - Let each individual strategy manage clean up
   - custom strategies will have greater control over the clean up in case of different falures
   - we will have to provide the clean up implementation for our own strategies

@smarterclayton Thoughts?

**Comment by abhgupta** [comment]
@smarterclayton unless I hear from you otherwise, I am going to work on adding the clean up logic in the platform code and apply it generically to all deployments, regardless of strategy.

**Comment by smarterclayton** [comment]
> On Jun 9, 2015, at 4:34 PM, Abhishek Gupta <notifications@github.com> wrote:
> 
> @ironcladlou and I were discussing this and he brought up an interesting point:
> 
> Question: who should be responsible for the clean up in case of a failed deployment?
> 
> Let the platform do the clean up
> individual strategies need not worry about clean up
> will also cover custom strategies
This sounds like a good place to start
