### ISSUE TITLE
Deployment hook pods are left behind after deployment is complete

### ISSUE THREAD

**Issue by abhgupta** [openshift/origin#2858]

**Comment by abhgupta** [comment]
@smarterclayton @ironcladlou Need quick feedback/consensus on the approach:

I plan to delete the deployment hook pods once the entire deployment completes successfully. Also, the deployment hook pods will be deleted only on successful completion of the deployment and be left alone in case of a failure (allowing the user to inspect logs).

**Comment by ironcladlou** [comment]
Is this a duplicate of #2857? My opinion on the correct behavior is at https://github.com/openshift/origin/issues/2857#issuecomment-109353070.

**Comment by abhgupta** [comment]
Closing this as a duplicate of #2857
