### ISSUE TITLE
Add osc tag command

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#2861]
Add image promotion CLI command (be able to take an image or tag and add it somewhere else).

Proposed command:

`osc tag [--docker] <source> <dest> [<dest>...]`

`<source>` is a valid ImageStreamTag (`<ns>/<stream>:<tag>`), ImageStreamImage (`<ns>/<stream>@<id>`) or DockerImage (pull spec) reference
`<dest>` is an ImageStreamTag reference
`--docker` indicates the source is a DockerImage

Examples:

```
$ osc tag openshift/ruby:2.0 myruby:latest
# looks up the latest image for tag 2.0 from the image stream openshift/ruby and sets it as the current image for myruby:latest

$ osc tag openshift/ruby@55e166ff myruby:latest
# looks up the image with short name 55e166ff from the image stream openshift/ruby and sets it as the current image for myruby:latest

$ osc tag --docker openshift/ruby:latest myruby:latest
# sets the DockerImage openshift/ruby:latest as the current image for myruby:latest

$ osc tag openshift/ruby:2.0 myruby:latest yourruby:2.0
# looks up the latest image for tag 2.0 from the image stream openshift/ruby and sets it as the current image for myruby:latest and yourruby:2.0
```

**Comment by ncdc** [comment]
For #2628

**Comment by ncdc** [comment]
@smarterclayton PTAL before I start coding :smile:

**Comment by smarterclayton** [comment]
`osc tag`

**Comment by smarterclayton** [comment]
one source, many dests

**Comment by smarterclayton** [comment]
support docker image source

**Comment by ncdc** [comment]
@smarterclayton description updated

**Comment by smarterclayton** [comment]
I think --docker should replace the first argument -- `--docker=<image>` and then only specify destinations.  I don't know if someone would expect --docker as a boolean to apply to the destinations.

**Comment by ncdc** [comment]
My intent with --docker was to be able to distinguish between openshift/ruby as a reference to an image on the Hub vs a reference to an ImageStreamTag. I agree that it's not as intuitive as it could be. Do you have any thoughts on a nice clean way to do this? I'd prefer to avoid having to specify 1 of --from-docker=<pullspec>, --from-imagestream-tag=<istag>, --from-imagestreamimage=<isimage> for the source.

**Comment by smarterclayton** [comment]
It's fine for now we can change later
