### ISSUE TITLE
Builds continue getting attempted after namespace and buildconfig is deleted

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2864]
I created a namespace, created a buildconfig, and the build controller started trying to run a build.
While that was happening, I deleted the namespace, which cleaned up all objects.
This continues in the log for a long time afterward (5 minutes and counting):
```
E0605 12:41:59.715464   16702 factory.go:35] pods "nodejs-ex-1-build" not found
E0605 12:42:00.715916   16702 factory.go:35] pods "nodejs-ex-1-build" not found
E0605 12:42:01.715720   16702 factory.go:35] pods "nodejs-ex-1-build" not found
E0605 12:42:02.715606   16702 factory.go:35] pods "nodejs-ex-1-build" not found
E0605 12:42:03.715221   16702 factory.go:35] pods "nodejs-ex-1-build" not found
E0605 12:42:04.715460   16702 factory.go:35] pods "nodejs-ex-1-build" not found
E0605 12:42:05.716030   16702 factory.go:35] pods "nodejs-ex-1-build" not found
E0605 12:42:06.716312   16702 factory.go:35] pods "nodejs-ex-1-build" not found
E0605 12:42:07.715911   16702 factory.go:35] pods "nodejs-ex-1-build" not found
E0605 12:42:08.715481   16702 factory.go:35] pods "nodejs-ex-1-build" not found
```

**Comment by derekwaynecarr** [comment]
It's determined to build!

**Comment by bparees** [comment]
@liggitt i'm having trouble reproducing this...  1) how current was your code (i'm wondering if the pod/build sync deletion logic fixed/changed this behavior, it went in about a week ago...i doubt you're on anything that old, but...) 2) what state was the build in when you deleted the project?

my guess is that ultimately we'd give up on this anyway once we hit the retry time limit which is something like 30 minutes, but obviously it would be better if we realized it was a permanent failure early on.

**Comment by bparees** [comment]
@liggitt also if you can recreate it consistently, --loglevel=4 would be extremely helpful.

**Comment by liggitt** [comment]
I was running from master as of this morning... no idea on the state of the build. I'm fine with lowering severity.

**Comment by bparees** [comment]
@liggitt take a look at my PR for this, my vote would be to optimistically close this when that merges.

**Comment by bparees** [comment]
@liggitt this should be fixed now with https://github.com/openshift/origin/pull/2896
