### ISSUE TITLE
More robust deployment e2e tests are needed

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#2865]
We need e2e tests for deployment scenarios such as:

1. `oc deploy --latest`
2. `oc deploy --retry`
3. `oc deploy --cancel`
4. `oc rollback`

They should include a variety of hook scenarios as well.

**Comment by kargakis** [comment]
We now have extended tests that cover a variety of hook scenarios. I am adding an extended test for rollback in https://github.com/openshift/origin/pull/9135, and `deploy` is already covered.
