### ISSUE TITLE
openshift-tests command failed to run without FeatureGate filter in dryRun

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [openshift/origin#28681]
`openshift-tests` command failed to run without FeatureGate filter in dryRun

##### Version
As we are intending to do a dry run, the version shouldn't be necessary.

##### Steps To Reproduce
Have golang installed
1. Clone openshift/origin repo
2. Run make GO_REQUIRED_MIN_VERSION:= WHAT=cmd/openshift-tests to build openshift-tests binary
3. cp ./openshift-tests /usr/local/bin
4. Run command `openshift-tests run kubernetes/conformance --dry-run`

##### Current Result
```
+ openshift-tests run kubernetes/conformance --dry-run
Unable to get admin rest config, skipping apigroup check in the dry-run mode: could not load client configuration: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
time="2024-03-29T02:18:52Z" level=info msg="Decoding provider" clusterState="<nil>" discover=true dryRun=true func=DecodeProvider providerType=
  W0329 02:18:52.866818      13 test_context.go:547] Unable to find in-cluster config, using default host : https://127.0.0.1:6443
Unable to get server version through discovery client, skipping apigroup check in the dry-run mode: <nil>
error converting to options: unable to build FeatureGate filter: Get "http://localhost/apis/config.openshift.io/v1/featuregates/cluster": dial tcp [::1]:80: connect: connection refusederror: unable to build FeatureGate filter: Get "http://localhost/apis/config.openshift.io/v1/featuregates/cluster": dial tcp [::1]:80: connect: connection refused
```

##### Expected Result
Should list the tests.

**Comment by vrutkovs** [comment]
I think this is intentional - test list in the suite depends on the enabled features and may vary. We could make it skip this check and assume no feature gates are enabled, but in that case the output would miss some tests
