### ISSUE TITLE
Pods in the web console show text "Allocating IP..." when terminating

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2877]
To reproduce:

1. Open the web console
1. Use `osc edit rc` to increase the number of desired replicas to a large number.
1. Use `osc edit` again to reduce to the number of desired replicas.

You can see in the web console the pods that are terminating have the incorrect message `Allocating IP...`, which we default to when the pod does not have an IP.

**Comment by liggitt** [comment]
should only show that when status is pending or running, probably
/cc @pmorie

**Comment by spadgett** [comment]
I looked closer at this, and I was wrong. Some of the pods were still pending when I lowered the replica count. It was those pods I saw and incorrectly assumed that the message was because they were terminating.

Closing as invalid.

**Comment by liggitt** [comment]
It's actually an issue we should fix. We should only show that text in pending and running states, probably

**Comment by spadgett** [comment]
Fixed by #3068
