### ISSUE TITLE
Allow debugging docker push

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#2880]
This [commit](https://github.com/openshift/origin/commit/e957864a407db893019d77511f9c22efcf40adf2) silenced docker push, which is ok, but not where you're trying to debug the lengthy times of actual docker push. There should be an option or loglevel where we should allow seeing those push details.

**Comment by smarterclayton** [comment]
Don't we log a message immediately after push?

**Comment by soltysh** [comment]
We do we log start and end. I was rather I interested in a full debug
information about every single layer being pushed.

**Comment by ncdc** [comment]
+1 to being able to see the push details again. I was hoping for this a couple of days ago when debugging something.

**Comment by smarterclayton** [comment]
How about capture error, and on error dump a subset of them (all of the progress lines can be nuked).

**Comment by mfojtik** [comment]
+1 @smarterclayton

**Comment by soltysh** [comment]
I was rather interested in the whole process of push, especially the timing, so the error dump is not enough. I'd say this is similar to debugging tar contents, which we do for sti at the highest level (3 looking [here](https://github.com/openshift/source-to-image/blob/master/docs/cli.md#log-levels)).

**Comment by smarterclayton** [comment]
We can set that as an ENV var now, right (debugging it)?  Then include dump when glog.V(4) is true.

----- Original Message -----

**Comment by soltysh** [comment]
We do have an env var for builds its `BUILD_LOGLEVEL` but currently we don't use that for showing the push information. I can agree to even add 6th loglevel to cover just that.

**Comment by smarterclayton** [comment]
Hooking it into the build log level makes sense to me.

----- Original Message -----
