### ISSUE TITLE
"IP on node" shown with no value in details sidebar

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2888]
This is under Pod Status. If there is no IP, it should either be hidden or say `None`.

![screen shot 2015-06-05 at 3 28 16 pm](https://cloud.githubusercontent.com/assets/1167259/8014518/8cf4cfb8-0b9f-11e5-82b1-6098af9561a8.png)

(Not obvious from the screen capture, but there's no value.)

**Comment by spadgett** [comment]
Fix complete for k8s-object-describer, but requires a new openshift-object-describer release.

**Comment by spadgett** [comment]
Hm, maybe wait for a fix to #2572.

**Comment by spadgett** [comment]
#3867 has the object describer fix.

**Comment by liggitt** [comment]
@spadgett can we close this since #3867 merged?
