### ISSUE TITLE
Command in kubernetes config prevents container from being accessible

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#2890]
If the 'command' section is added to the kubernetes configuration file, then the application will not be accessible at its IP endpoint. 

See https://gist.github.com/mwringe/5abe6b5ec95bd093a7eb for a simple example illustrating this. There are two pods and services created, the only difference (other than the name) is that one has a 'command' section defined which contains the same content as the CMD found in the dockerfile.

**Comment by smarterclayton** [comment]
What error do you get in the docker container?

**Comment by mwringe** [comment]
None, the container starts up properly (I can docker exec into it and use localhost to access the site) it just that its not available at its endpoint or its service's endpoint. Maybe its an issue with the binding address and JBoss when setting it up this way. Let me check with a different container to see if that makes a difference or not.

**Comment by smarterclayton** [comment]
@rhcarvalho can you help mrwinge debug this?

**Comment by rhcarvalho** [comment]
@smarterclayton yes, trying to reproduce it locally.

**Comment by rhcarvalho** [comment]
@mwringe the problem was in the specification of the command. You need to pass each argument as a separate string: `["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]`

I was able to get both foo and bar working after updating your example:
https://gist.github.com/rhcarvalho/faecb6790731aeff6f5f

**Comment by danmcp** [comment]
Please reopen if this is still a problem.
