### ISSUE TITLE
ImageStream not imported from registry

### ISSUE THREAD

**Issue by bparees** [openshift/origin#2913]
twice now i've created an imagestream in one project, and then created basically the identical imagestream in a second project under the same user, and the second imagestream never gets imported (thus also no build ever gets kicked off).  it doesn't seem 100% consistent as i also saw it work at least once.

here's the "good" imagestream:
       {
            "kind": "ImageStream",
            "apiVersion": "v1beta3",
            "metadata": {
                "name": "ruby-20-centos7",
                "namespace": "foo",
                "selfLink": "/osapi/v1beta3/namespaces/foo/imagestreams/ruby-20-centos7",
                "uid": "8a0fb356-0d6b-11e5-b05e-3c970e3bf0b7",
                "resourceVersion": "270",
                "creationTimestamp": "2015-06-07T23:18:43Z",
                "labels": {
                    "template": "application-template-dockerbuild"
                },
                "annotations": {
                    "openshift.io/image.dockerRepositoryCheck": "2015-06-07T23:18:45Z"
                }
            },
            "spec": {
                "dockerImageRepository": "openshift/ruby-20-centos7"
            },
            "status": {
                "dockerImageRepository": "openshift/ruby-20-centos7",
                "tags": [
                    {
                        "tag": "latest",
                        "items": [
                      "tag": "latest",
                        "items": [
                            {
                                "created": "2015-06-07T23:18:45Z",
                                "dockerImageReference": "openshift/ruby-20-centos7:latest",
                                "image": "2912cc9993d1ad6515c454ffe6af61b45acf94b47a6c199ae75f38e7bbac3c9f"
                            }
                        ]
                    },
                    {
                        "tag": "v0.4",
                        "items": [
                            {
                                "created": "2015-06-07T23:18:44Z",
                                "dockerImageReference": "openshift/ruby-20-centos7:v0.4",
                                "image": "c7dbf059225847a7bfb4f40bc335ad7e70defc913de1a28aabea3a2072844a3f"
                            }
                        ]
                    }
                ]
            }
        }

and here's the "bad" one..notice there's no annotation indicating it ever checked the docker repository:
{
            "kind": "ImageStream",
            "apiVersion": "v1beta3",
            "metadata": {
                "name": "ruby-20-centos7",
                "namespace": "sti",
                "selfLink": "/osapi/v1beta3/namespaces/sti/imagestreams/ruby-20-centos7",
                "uid": "46a16285-0d84-11e5-b05e-3c970e3bf0b7",
                "resourceVersion": "2093",
                "creationTimestamp": "2015-06-08T02:15:47Z",
                "labels": {
                    "template": "application-template-stibuild"
                }
            },
            "spec": {
                "dockerImageRepository": "openshift/ruby-20-centos7"
            },
            "status": {
                "dockerImageRepository": "openshift/ruby-20-centos7"
            }
        }

I'm wondering if there's some caching that's no sufficiently keyed to recognize these imagestreams are in two different namespaces, so it ignores the 2nd one?

**Comment by bparees** [comment]
@ncdc @smarterclayton fyi

**Comment by smarterclayton** [comment]
P0

**Comment by ncdc** [comment]
I saw this the other day, although with just a single repo I was trying to import. I kept seeing it get a 401 when trying to get the token from the Hub, and it wouldn't import until I restarted the master. I can't say for sure if restarting fixed the issue, or if it was just a coincidence of timing (perhaps the Hub was having issues and they were fixed right around the time I restarted). We do cache the info about each remote repo we try to import, but in this case because it was getting a 401, nothing should be cached. Are you still able to reproduce this?

**Comment by bparees** [comment]
can't reproduce so far, still trying.  but i do we not have a controller that periodically scans for imagestreams that have not done a repo-check and runs one?  i guess i know we never implemented polling so maybe not.

**Comment by ncdc** [comment]
We do have such a controller

**Comment by bparees** [comment]
I can't reproduce this today, will lower severity.

**Comment by bparees** [comment]
closing, will reopen if it recreates at some point, but longer term i'm guessing this sort of issue will be fixed by the introduction of the controller/polling logic.
