### ISSUE TITLE
error: open /openshift.local.config/master/admin.kubeconfig: permission denied

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#2916]
In a fedora box even after chmoding admin.kubeconfig (chmod had worked before but not now - not sure why), I hit the error in the title when I am trying to login. 

cc: @liggitt @danmcp @mnagy

**Comment by kargakis** [comment]
The following works:
```
$ oc describe service docker-registry --config=openshift.local.config/master/admin.kubeconfig
```
The registry isn't running, not sure if it's related though:
```
I0608 12:12:23.166386    1889 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"docker-registry-1-deploy", UID:"a6e8c89c-0dcd-11e5-836a-080027c5bfa9", APIVersion:"v1beta3", ResourceVersion:"322", FieldPath:""}): reason: 'failedSync' Error syncing pod, skipping: Tag v0.2 not found in repository docker.io/openshift/origin-pod
```
Skimming through tags in [openshift/pod](https://registry.hub.docker.com/u/openshift/origin-pod/tags/manage/) I didn't find any 0.2 tag

**Comment by liggitt** [comment]
`v0.2`? what version of openshift are you running?

**Comment by liggitt** [comment]
What does this show:
```
sudo ls -la /openshift.local.config/master/admin.kubeconfig
sudo more /openshift.local.config/master/admin.kubeconfig
```

**Comment by kargakis** [comment]
Hmm, I had to chmod the absolute path in order for it to work. Probably the [sample-app](https://github.com/openshift/origin/blob/master/examples/sample-app/README.md#application-build-deploy-and-update-flow) example needs to be fixed to use that as well?

Re openshift version
```
[vagrant@openshiftdev sample-app]$ openshift version
openshift v0.2-3345-g4b56626
kubernetes v0.17.1-804-g496be63
```
Not sure how v0.2 sneaked in there, I always make clean build on the latest master (in my host)...

**Comment by liggitt** [comment]
Probably a mix of relative and absolute paths... the sample app readme assumes you run everything with the sample app as the working dir, iirc

**Comment by kargakis** [comment]
I am using the sample app dir too

**Comment by liggitt** [comment]
did you start openshift in that dir as per the readme, or was it running from a service?

**Comment by liggitt** [comment]
ah, I see that readme tries to address vagrant users as well... in that case, the paths to kubeconfig files are wrong...

**Comment by kargakis** [comment]
Most probably...

**Comment by smarterclayton** [comment]
The vagrant vm doesn't provision correctly, or you need to update your vm

**Comment by kargakis** [comment]
https://github.com/openshift/origin/pull/2943#issuecomment-116601483
