### ISSUE TITLE
Running docker inside an app

### ISSUE THREAD

**Issue by robertoandrade** [openshift/origin#2927]
Do I actually need all the recent work done on Origin to make it Docker-based in order to run Docker client/daemon inside a cartridge/app?

I'm trying to do this with the current version of OpenShift Online and people keep referring me to the work done in Origin to support Docker. I don't want to run a Docker image in OpenShift, I just want to be able to run docker inside an app for the purpose for building images (not necessarily running them).

**Comment by smarterclayton** [comment]
Unfortunately docker build requires root access to build images which is not available in OpenShift Online.
