### ISSUE TITLE
Adding volume emptyDirs for new-app flows

### ISSUE THREAD

**Issue by mnagy** [openshift/origin#2929]
From the v1.0 punch list: #2628 

Modify new-app to add emptyDir specification into created pods, by default. Eventually we should support a flag that would make the volumes persistent (optionally) or read metadata from the pod annotations about which volumes should be persistent by default.

This depends on upstream PR https://github.com/GoogleCloudPlatform/kubernetes/pull/9384

**Comment by bparees** [comment]
@smarterclayton the design for this is that when running new-app and creating a pod definition for an image that has a volume defined, we'll create an emptydir volume definition.  Is that what you had in mind?

**Comment by smarterclayton** [comment]
Yes, each volume should have an emptydir volume definition.  There are a few open design questions, like what to do if you create pods with multiple containers - should their volumes be shared if they have the same path, etc.

----- Original Message -----

**Comment by mnagy** [comment]
Fixed in #3098

**Comment by johnjelinek** [comment]
what are the docs for this feature?

**Comment by bparees** [comment]
@johnjelinek it probably belongs here under"artifacts created":
https://docs.openshift.org/latest/dev_guide/new_app.html#new-app-output

@mnagy can you do a docs PR for this on monday?

**Comment by mnagy** [comment]
@bparees sorry, had PTO and was extremely busy, had no time to respond. I'll do it ASAP.

**Comment by mnagy** [comment]
Here: https://github.com/openshift/openshift-docs/pull/677
