### ISSUE TITLE
DeploymentConfig keeps attempting to create a deployment even if exists

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#2932]
I did the following:

```shell
oc new-project example
oc new-app openshift/hello-openshift -l frontend=static
```

I get a deployment and the pod running as expected, but I see the following event produced every minute.

```shell
openshift cli describe deploymentConfig hello-openshift
Name:		hello-openshift
Created:	7 minutes ago
Labels:		frontend=static
Latest Version:	1
Triggers:	Config, Image(hello-openshift@latest, auto=true)
Strategy:	Recreate
Template:
	Selector:	deploymentconfig=hello-openshift
	Replicas:	1
	Containers:
		NAME		IMAGE					ENV
		hello-openshift	openshift/hello-openshift:latest	
Deployment #1 (latest):
	Name:		hello-openshift-1
	Created:	7 minutes ago
	Status:		Complete
	Replicas:	1 current / 1 desired
	Selector:	deployment=hello-openshift-1,deploymentconfig=hello-openshift
	Labels:		frontend=static
	Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Events:
  FirstSeen				LastSeen			Count	From		SubobjectPath	Reason		Message
  Mon, 08 Jun 2015 14:37:49 +0000	Mon, 08 Jun 2015 14:43:52 +0000	4	{deployer }			alreadyExists	Deployment already exists for DeploymentConfig: example/hello-openshift:1
```

**Comment by derekwaynecarr** [comment]
@ironcladlou @abhgupta - is this expected?  it seems like whatever code is trying to create something could do a get to validate that its already there and then not generate an event which looks like an error scenario.

**Comment by ironcladlou** [comment]
Agree, I don't think we should be creating an event in this case.

**Comment by abhgupta** [comment]
@derekwaynecarr This was expected to be fixed by https://github.com/openshift/origin/pull/2742 that went in last Thursday. Can you confirm that you were using the latest code/build for your testing?

**Comment by abhgupta** [comment]
I think I've found the issue - should be addressed shortly.

**Comment by derekwaynecarr** [comment]
@abhgupta - this was from this morning.

**Comment by derekwaynecarr** [comment]
@abhgupta - can you cc me on the PR that you think is the source?  I am trying to look at what happens with OpenShift once its running for awhile, and things like this where we spawn calls every minute or so per project stood out to me.

**Comment by abhgupta** [comment]
@derekwaynecarr working on the fix now - will copy you on the PR
