### ISSUE TITLE
SCC: manage security modes of the cluster

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#2933]
Create commands to manage the default security modes of the cluster.  Currently there is a PR open to create a default SCC for the cluster https://github.com/openshift/origin/pull/2863 but the management of SCCs needs to be an administrative function.

**Comment by smarterclayton** [comment]
On startup we should be creating initial SCCs to match a configured default policy.

I'm imagining three global default config modes:

1. Isolated namespaces (each namespace gets its own uidrange / mcs label)
2. Non-root namespaces
3. ???

Those config modes on startup are like bootstrap policy and define initial SCCs.  Subsequent actions are edits of those SCCs.  Our default is probably 2.  We can create all three and enforce them on projects via the admission controller (which can look at the namespace to select the appropriate SCC).

**Comment by pweil-** [comment]
Just a reminder, since RunAsNonRoot required kubelet changes we pushed it as lower priority in https://github.com/openshift/origin/issues/2626#issuecomment-107431609.  We can start with isolated and open.  

Isolated should create a set of SCCs that look up the namespace values, open would create an SCC that looks like the one in the linked PR.  Will discuss during the call.

**Comment by liggitt** [comment]
You can create the constraints for those three modes, then control configuration by adding and removing groups to the constraints.

**Comment by smarterclayton** [comment]
Groups for what?  Namespaces?  I'm more thinking about how admins want to apply SCC and it's likely to be on a per namespace basis.  In that case we want to apply the constraints at admission time via a lookup on the namespace annotation

**Comment by liggitt** [comment]
> In that case we want to apply the constraints at admission time via a lookup on the namespace annotation

So, that's three ways to figure out what SCC applies to a pod create?
1. user/group mapping of calling user (implemented)
2. user/group mapping of pod's service account (implemented)
3. some annotation on a namespace? first I've heard of this

**Comment by pweil-** [comment]
> You can create the constraints for those three modes, then control configuration by adding and removing groups to the constraints.

Yes, good point.  All the SCCs can be created by default and the "cluster policy" is really just ensuring that the SCCs are managed in a way that gives access.

**Comment by smarterclayton** [comment]
----- Original Message -----
> > In that case we want to apply the constraints at admission time via a
> > lookup on the namespace annotation
> 
> So, that's three ways to figure out what SCC applies to a pod create?
> 1. user/group mapping of calling user (implemented)
> 2. user/group mapping of pod's service account (implemented)
> 3. some annotation on a namespace? first I've heard of this

If we can have 

SCC 1 - assigned to all service accounts
SCC 2 - assigned to a subset of service accounts

Then we don't need 3.

**Comment by liggitt** [comment]
> If we can have
> SCC 1 - assigned to all service accounts
> SCC 2 - assigned to a subset of service accounts
> Then we don't need 3.

Easy, as long as you remember that SCC (like policy) is additive, so you can't assign an SCC to all service accounts and then override it with a more restrictive SCC for a few.

It's easy to do this:

"restricted" SCC includes the groups "system:authenticated" and "system:serviceaccounts"
"privileged" SCC includes the groups "system:cluster-admins", "system:serviceaccounts:my-super-cool-namespace", and "system:serviceaccount:my-lame-namespace:my-super-cool-service-account"

There is no third thing

**Comment by pweil-** [comment]
> Easy, as long as you remember that SCC (like policy) is additive, so you can't assign an SCC to all service accounts and then override it with a more restrictive SCC for a few.

Yes, this is perfectly doable.  The most important thing for SCCs to remember is that if you make no requests we expect to default your values.  Pods requiring certain privileges/uids/caps MUST make requests for the items they need or they will get defaulted and validate 100% of the time against any SCC they have access to.

**Comment by liggitt** [comment]
is it our preference that the most restrictive SCC be the one to validate? if so, testing the pod against the applicable SCC's in sorted order would accomplish that. would need a sort function.

**Comment by smarterclayton** [comment]
Sounds good, we're set.

**Comment by liggitt** [comment]
With https://github.com/openshift/origin/pull/2777 merged, you can now include the build controller service account specifically in the privileged security context constraints.

**Comment by pweil-** [comment]
Excellent, I will rebase admission and give it a test with e2e and the real SCCs

**Comment by pweil-** [comment]
PR: https://github.com/openshift/origin/pull/2868
