### ISSUE TITLE
add key mapping options to osc secrets new

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#2951]
We need to be able to specify a mapping between filenames and keys when creating secrets.  Some discussion happened here:  https://github.com/openshift/origin/pull/2866#issuecomment-109433597 .

I think I like the idea of `osc secrets new SecretName key-a=file1 key-b=file2` best out of the suggestions so far.  It means we couldn't use this command to handle secrets with `=` in them, but those people can always bundle their secrets manually.

**Comment by deads2k** [comment]
@liggitt @mfojtik @smarterclayton for continued discussion.

**Comment by smarterclayton** [comment]
People will `=` in their secret names will eventually die out.

**Comment by deads2k** [comment]
> People will = in their secret names will eventually die out.

I never like them much anyways. :)

**Comment by deads2k** [comment]
@stevekuznetsov take a look at this one.  You'll want to pull https://github.com/openshift/origin/pull/2866 to get started.  See https://gist.github.com/piscisaureus/3342247 for how to do the checkout.

**Comment by deads2k** [comment]
@liggitt please assign to @stevekuznetsov.  This will help our secrets story for builds.

**Comment by mfojtik** [comment]
@deads2k this is post-3.0, right?

**Comment by deads2k** [comment]
> @deads2k this is post-3.0, right?

Probably depends on how it goes.  I'd like to see this in to make it easier for people to generate their ssh keys and then create secrets from them without manually creating json.

**Comment by mfojtik** [comment]
so for the source secret the command will be:

```console
$ osc secrets new source ssh-privatekey=$HOME/.ssh/id_rsa 
```

**Comment by deads2k** [comment]
@mfojtik yes.

**Comment by stevekuznetsov** [comment]
Format will be `key-name=path-to-key`:
* `oc secrets new <name> <key-name=path-to-key>...`

Will support un-named keys by giving them a default name of their filename:
* `oc secrets new <name> <path-to-key>...`

Will support un-named directories by giving all valid keys inside the default name of their filename:
* `oc secrets new <name> <path-to-dir>...`

Will forbid giving a name to a directory:
* `oc secrets new <name> <key-name=path-to-dir>...`

Will forbid giving a name containing an `=`:
* `oc secrets new <name> <impossible=name=path-to-dir>...`

@deads2k @mfojtik @smarterclayton  any other considerations?

**Comment by smarterclayton** [comment]
Sounds fine.

----- Original Message -----

**Comment by deads2k** [comment]
@stevekuznetsov make sure that give good messages on key collisions.
