### ISSUE TITLE
OpenShift UI does not clear notifications when I switch project contexts

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#2964]
User scenario:

1. Create a project from web console
2. Create content in project from template
3. Content is created, and get a nice notification text explaining
4. Switch to another project, or go to main project listing and create a new project
5. Should see a project with no notification

Actual results:
Still see the notification text from the other project rendering in the current project

@spadgett @liggitt

**Comment by liggitt** [comment]
Those can actually contain more than notifications, like status of long-running requests. I guess we don't have many (any?) long-running requests, but I'm not sure about discarding all the notifications when you switch projects.

**Comment by liggitt** [comment]
@spadgett might need to segment tasklist by project, and persist/show the notifications for the current project only? need to think about that

**Comment by derekwaynecarr** [comment]
@liggitt - it was most confusing when I created a template twice in the same project, got told an already exists, and then created a new project, and was told an already exists notification.  I hadn't yet created content in the project, so I think other users will be confused if we dont clear notifications or scope them to a project.

**Comment by spadgett** [comment]
See also

https://bugzilla.redhat.com/show_bug.cgi?id=1224640

**Comment by jwforres** [comment]
Closing since we are tracking this in bugzilla too
