### ISSUE TITLE
Fix edge case where multiple port mappings extend beyond its container in the ui

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#2971]
See https://github.com/openshift/origin/pull/2563#issuecomment-110140459

**Comment by sg00dwin** [comment]
I wasn't able to reproduce this edge case https://github.com/openshift/origin/pull/2563#issuecomment-110140459 on Chrome or Firefox.  

Multiple port mappings "and x others" inline (default)
![screen shot 2015-06-09 at 12 41 46 pm](https://cloud.githubusercontent.com/assets/1874151/8064392/67662948-0ea8-11e5-85fb-5a1eeea1145b.png)

Multiple port mappings "and x others" blocked (@media (max-width: 991px) and (min-width: 768px), (max-width: 380px))
![screen shot 2015-06-09 at 12 42 17 pm](https://cloud.githubusercontent.com/assets/1874151/8064426/95d3dff0-0ea8-11e5-9b69-e12abe6defd3.png)

**Comment by jwforres** [comment]
@spadgett are you still able to reproduce this?  (you reported the original problem in the other PR)

**Comment by spadgett** [comment]
I can't reproduce now that we shortened the message.
