### ISSUE TITLE
Port OpenShift to Swift

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2974]
Will be much faster an run on iOS

**Comment by liggitt** [comment]
[face]

**Comment by pmorie** [comment]
:trollface:

**Comment by mrunalp** [comment]
Swift for linux also coming out soon :D Meanwhile I suggest Rust...

**Comment by pmorie** [comment]
> Swift for linux also coming out soon :D Meanwhile I suggest Rust...

Clearly D is the right choice.  It can even embed lua!

**Comment by mrunalp** [comment]
@danmcp I suggest the 4.0 tag ;)

**Comment by mrunalp** [comment]
@pmorie Let us shoot for the stars. Haskell for 4.0. Agda for 5.0 :D

**Comment by smarterclayton** [comment]
I've always wanted to box my pointers

**Comment by mrunalp** [comment]
Ha ha :)

**Comment by jhadvig** [comment]
:+1: 
Will it be available on AppStore ?

**Comment by mfojtik** [comment]
@smarterclayton you should wait till Apple open-source it

**Comment by kargakis** [comment]
OpenSwift

**Comment by sspeiche** [comment]
We should port it to TaylorSwift, target a new demographic

**Comment by smarterclayton** [comment]
We're gonna Shake Your Legacy Infra, Shake it Off

**Comment by danmcp** [comment]
Closing due to no longer being funny.  Feel free to reopen if for some reason it becomes amusing again.

**Comment by smarterclayton** [comment]
Just got really funny.

**Comment by derekwaynecarr** [comment]
:laughing:

**Comment by liggitt** [comment]
I just chuckled a little as well, was able to recreate

**Comment by liggitt** [comment]
though I quickly stopped laughing, lowering severity

**Comment by smarterclayton** [comment]
This change is Approved

**Comment by sspeiche** [comment]
Adding mockup of new UI

![image](https://cloud.githubusercontent.com/assets/727196/8090360/88de75ca-0f7b-11e5-83fd-58f15304c03c.png)
