### ISSUE TITLE
Failed builds shown as running in web console overview

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2975]
All three of these builds had failed. It's possible this only happens under certain conditions.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8047525/6b39f44e-0e14-11e5-8c5c-675d0b2a023d.png)

We should probably put the build name in the overview message as well.

**Comment by liggitt** [comment]
the UI stayed stuck in new status?

**Comment by spadgett** [comment]
@liggitt yes, looks like it. In overview.js, we never clear `trigger.builds`, and the deployment trigger from doesn't match the build output to.

Deployment trigger:

```
             "from": {
                "kind": "ImageStreamTag",
                "name": "nodejs-ex:latest"
              }
```

Build output:

```
      "output": {
        "to": {
          "kind": "DockerImage",
          "name": "172.30.227.240:5000\/test\/nodejs-ex:latest"
        },
        "pushSecret": {
          "name": "builder-dockercfg-96bhx"
        }
      }
```

If I'm reading the code right, this test is failing.

```
          if (buildOutputImage !== deploymentTriggerImage) {
              continue;
          }
```

**Comment by spadgett** [comment]
Hm, output to when the build starts is different.

```
"output":{"to":{"kind":"ImageStreamTag","name":"nodejs-ex:latest"}
```

**Comment by liggitt** [comment]
I think we don't clear them because we want to show completed/failed things until they timeout

**Comment by liggitt** [comment]
@bparees is it expected for the `build.spec.output.to` to change during a run?

**Comment by spadgett** [comment]
This could a problem only in my environment, but here is the build error in the logs.

```
I0608 23:17:39.898776       1 sti.go:99] Pushing 172.30.227.240:5000/test/nodejs-ex image ...
E0608 23:17:40.026742       1 dockerutil.go:47] push for image 172.30.227.240:5000/test/nodejs-ex failed, will retry in 10s ...
E0608 23:17:50.140645       1 dockerutil.go:47] push for image 172.30.227.240:5000/test/nodejs-ex failed, will retry in 10s ...
F0608 23:18:00.301381       1 builder.go:70] Build error: Failed to push image: API error (500):  v1 ping attempt failed with error: Get http://172.30.227.240:5000/v1/_ping: read tcp 172.30.227.240:5000: connection reset by peer
```

**Comment by liggitt** [comment]
looks like https://github.com/openshift/origin/commit/41596110b6d279fa130319b8d80e8d47f032d8ae#diff-661252da3ac92a7bc8779d5eee2f7601R95 mutates spec.output.to when the build pod gets created. @smarterclayton that seems... not good

**Comment by liggitt** [comment]
that also means if the UI isn't quick enough to see the build in its new state (with an ImageStreamTag spec.output.to), it has no way to correlate it to a deployment's ImageChange trigger

**Comment by smarterclayton** [comment]
This should really be an annotation on the pod or part of build status, not part of the encoded build.  Builds

**Comment by smarterclayton** [comment]
That field isn't visible externally in v1.  We only return a kind dockerimage.  So there's no way to get that info anymore.

**Comment by liggitt** [comment]
Opened https://github.com/openshift/origin/issues/2977 for build controller issue.

@spadgett we can do this:
```
      var buildName = build.metadata.name;
      for (var i = 0; i < deploymentConfig.spec.triggers.length; i++) {
        var trigger = deploymentConfig.spec.triggers[i];
        if (trigger.type === "ImageChange") {
          if (trigger.builds && trigger.builds[buildName]) {
          	trigger.builds[buildName] = build;
            continue;
          }
```

**Comment by liggitt** [comment]
> That field isn't visible externally in v1

`build.spec.output.to`? It's still in the API...

**Comment by smarterclayton** [comment]
In v1beta3 there are two fields - a docker image reference and a to.  The existing build code was violating the API behavior by setting both to and dockerimage reference (only one is valid, and it was setting them to different values).  That didn't survive conversion.

In v1 there is only one field, to.  Right now it's being rewritten to dockerimage before being encoded which is what the build needs.  But there was no test case for the ui.  Long term, the uid shouldn't be reading anything expect an annotation on the pod, and passing the whole build Json down into the pod is also questionable.

**Comment by liggitt** [comment]
@spadgett https://github.com/openshift/origin/pull/2978 fixes the issue with build.spec.output.to mutating during a build. Lowering the priority on this, but leaving it open to clean up builds and fix up the logic so we update builds that already made it into triggers.

**Comment by spadgett** [comment]
I've verified builds update in the UI since #2978 merged.
