### ISSUE TITLE
Build spec.output.to mutates from ImageStream to DockerImage during run

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2977]
Introduced in https://github.com/openshift/origin/commit/41596110b6d279fa130319b8d80e8d47f032d8ae#diff-661252da3ac92a7bc8779d5eee2f7601 which sets dockerreference and deletes output.to when creating the build pod

This confuses the UI, which associates builds with deployment triggers (https://github.com/openshift/origin/issues/2975)

**Comment by smarterclayton** [comment]
We need to add an annotation on the encoded build for the original to, or set the actual push value as an annotation on the encoded build.  I like the latter

**Comment by smarterclayton** [comment]
Will require a build image change

**Comment by liggitt** [comment]
what "encoded build" are you talking about? we're watching the actual builds

**Comment by liggitt** [comment]
spec shouldn't change over the lifetime of a build

**Comment by smarterclayton** [comment]
The build never changes (or shouldn't).  The pod's version of the build Json is what is changed.

**Comment by liggitt** [comment]
I didn't know the pod had build JSON, we're not watching that. The build is getting modified.

**Comment by smarterclayton** [comment]
The code you're point to is not supposed to mutate the build.  Could be a pointer copy error.

**Comment by liggitt** [comment]
Should the mutation in https://github.com/openshift/origin/commit/41596110b6d279fa130319b8d80e8d47f032d8ae#diff-661252da3ac92a7bc8779d5eee2f7601 have happened after the copy?

**Comment by liggitt** [comment]
yeah, a pointer gets passed in, mutated, then the build updated in the calling function

**Comment by smarterclayton** [comment]
K, we need to move the copy up then.

**Comment by bparees** [comment]
um, i don't think so.

that code needs to be doing what it does to resolve an ImageStreamTag into a DockerImage so the build can successfully push somewhere.

the "right" way to do fix this is to resolve the ImageStreamTag when the build object is originally created, instead of waiting until the build controller sees the build object.

**Comment by bparees** [comment]
(which is what I believe @soltysh was doing at one point and then we ran into conversion stuff and short-cutted a solution, a couple days ago)

**Comment by bparees** [comment]
ok i take it back (or rather @liggitt corrected me).  i guess what's being done here is ok though it'd still be more correct imho to fix this by resolving the imagestream when the original build object is created, not when we noticed it exists.

**Comment by soltysh** [comment]
@bparees I've trelloed that [here](https://trello.com/c/xrPu7upe/590-clean-validation-in-builds-future-build). Although initially it's talking about just validation I've put there link to my work you were referring to which was moving the Image "decoding" into build creation, which is what you'd like to see, but of course post 3.0.

**Comment by liggitt** [comment]
@soltysh also see https://github.com/openshift/origin/issues/2982

**Comment by soltysh** [comment]
@liggitt added to the aforementioned trello, you can sing me up for the issue as well. I'm hoping to deal with all of those.

**Comment by bparees** [comment]
@soltysh @liggitt I think we concluded last night we need to leave the spec field as is because the UI is dependent on having the ImageSTreamTag information available in the build definition.

So the only change here should be to add the status field.  And @soltysh i've asked @mfojtik to work on this.

**Comment by liggitt** [comment]
> leave the spec field as is because the UI is dependent on having the ImageSTreamTag information available in the build definition.

Not just the UI... it makes logical sense for the spec field to connect to the buildconfig, and resolved values go in the spec

**Comment by soltysh** [comment]
Fine by me.

**Comment by smarterclayton** [comment]
Resolved values go in the status.

----- Original Message -----
