### ISSUE TITLE
Console: make it possible to collapse a build

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#2979]
It would be nice to be able to collapse a build to just a summary.  You wind up having to scroll a lot when you have a ton of build configs and a ton of builds (I know this since I did 50 builds on Sat to test something in our demo environment).

@liggitt

**Comment by spadgett** [comment]
@pmorie I'm considering showing the last build (and maybe last failed build) for each build config, then putting other old builds for a config under one collapsed section. Thoughts?

It would partially fix #2146 as well, although not any underlying performance problem.
