### ISSUE TITLE
Make the Source secret key name consistent with the filename

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#2991]
Currently, the 'key' name for the Source secret has to be `ssh-privatekey`. However, the file it contains is `id_rsa` or `id_dsa` and it actually can be whatever (I personally have >4 SSH private keys for different systems). So:
- We should make the 'key' name match the filename
- We should have a 'SSHKey' type secret

**Comment by mfojtik** [comment]
@soltysh @smarterclayton (post-3.0)

**Comment by smarterclayton** [comment]
Why do we have to make the key name match the file name?

**Comment by mfojtik** [comment]
@smarterclayton we are doing that for .dockercfg I thought it would be nice to be consistent.

**Comment by smarterclayton** [comment]
In this case it's not the only reason to do something.  Let's get some practical use first.

**Comment by mfojtik** [comment]
@liggitt @smarterclayton do we have 'SSH' secret type? IOW. is there a way to know that this secret has SSH payload inside?

**Comment by smarterclayton** [comment]
Right now, a secret with a key name of ssh-privatekey is our only mechanism.

----- Original Message -----

**Comment by soltysh** [comment]
@mfojtik you need to keep in mind that based on the secret name (specifically secret's data name) we distinguish which mechanism is going to be used to provide you with the secret. Whether it'll be ssh-privatekey (is this is the only implemented solution) or others such as token or user+password.

**Comment by soltysh** [comment]
> In this case it's not the only reason to do something. Let's get some practical use first.

@smarterclayton #2866 is that use case, if we add that subcommand people will expect this work for source secrets as well, unless we'll add `oc secrets new-source` allowing to pass the appropriate type of secrets, similarly to `oc secrets new-dockercfg` introduced in that PR.

**Comment by bparees** [comment]
this has not caused any user angst in the last 2.5 years that i'm aware of.
