### ISSUE TITLE
Icons and descriptions are not showing up for builder images in Web Console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2992]
Creating from source repository in the Web Console:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8058829/34d041c6-0e8a-11e5-9dc0-fbeffbb2089b.png)

Here are the annotations for the ruby image stream, for example. `ruby:2.0` (and probably others) should have an image and description.

```
    "spec": {
        "dockerImageRepository": "openshift/ruby-20-centos7",
        "tags": [
            {
                "name": "2.0",
                "annotations": {
                    "description": "Build and run Ruby 2.0 applications",
                    "iconClass": "icon-ruby",
                    "tags": "builder,ruby",
                    "version": "2.0"
                },
                "from": {
                    "kind": "ImageStreamTag",
                    "name": "latest"
                }
            },
            {
                "name": "latest"
            }
        ]
    }
```

/cc @bparees

**Comment by spadgett** [comment]
The annotation filter is trying to split on `.`, but there is a `.` in the name `2.0`.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8059446/0c5314d6-0e8e-11e5-9602-d680c472431b.png)

**Comment by bparees** [comment]
@liggitt @spadgett seems like a p2 if not p1 to me.

**Comment by spadgett** [comment]
@bparees +1
