### ISSUE TITLE
start node never reaches SdNotify("READY=1")

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#2996]
Something has changed between v0.5.2 and origin/master preventing the notification from being sent to systemd which means that systemd kills the process after 90 second timeout

**Comment by sdodson** [comment]
@smarterclayton Would #2718 have changed things such that nodeConfig.RunKubelet() blocks in a way it didn't previously?

https://github.com/openshift/origin/blob/master/pkg/cmd/server/start/start_node.go#L250-L253

**Comment by smarterclayton** [comment]
Yeah run kubelet blocks.  We can abuse the change I had for Rajats SDN issue I think.

**Comment by smarterclayton** [comment]
Should be fixed now

**Comment by sdodson** [comment]
READY=1 is still not getting sent.

**Comment by smarterclayton** [comment]
By observation if this isn't getting called then go routines are blocking which is unpossible.  This was on master?

**Comment by sdodson** [comment]
Yeah, current as of 5cf57679e0744d6946f4523cd6b6512b3c255111

**Comment by sdodson** [comment]
I'll see if I can verify there's not something in my environment that's screwing with it, but given that master is notifying properly I doubt that's the case.

**Comment by smarterclayton** [comment]
The code looks exactly the same, will add some trace.

----- Original Message -----
