### ISSUE TITLE
/metrics & /stats kubelet endpoints should be accessible without auth

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#3020]
All access to the kubelet endpoints currently requires a client certificate to access. Access to the `/stats/*` & `/metrics` endpoints is required for any metrics gathering service such as Heapster or Prometheus & so needs to be accessible without certificate auth.

/cc @smarterclayton

**Comment by liggitt** [comment]
cert auth is an all or nothing thing with the kubelet server at the moment... we don't have the option to protect some paths with cert auth and not others

**Comment by jimmidyson** [comment]
This is pretty essential to have any kind of centralised metrics service. I guess only option right now is to mint a client cert & use it as a secret in metrics pod? Sounds pretty dangerous like you said earlier.

**Comment by smarterclayton** [comment]
If we expose metrics they'll have to be on a different port in order to bypass the cert.  We may still want to put some kind of protection on them. 

----- Original Message -----

**Comment by liggitt** [comment]
are we expecting pods to have network visibility to the ports exposed by the nodes?

**Comment by smarterclayton** [comment]
It would probably be better for them not to.

----- Original Message -----

**Comment by jimmidyson** [comment]
@smarterclayton If we use a service account we could re-use the JWT for auth? Not sure if it contains claims in the JWT too that would simplify authz on it?

@liggitt Good question. If we do start network segregation how about a management namespace that does have access to node ports? Would be useful.

**Comment by liggitt** [comment]
JWT auth is only good against the master currently...

**Comment by jimmidyson** [comment]
Currently, but wouldn't it makes sense to re-use the JWT for other services?

**Comment by smarterclayton** [comment]
We could conceivably write a JWT that the node could validate.  That's what we were going to do for geard.

----- Original Message -----

**Comment by jimmidyson** [comment]
The read only port for metrics & stats on the kubelet is implemented upstream - https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/server.go#L81.

I take it we can't just reuse that?

**Comment by jimmidyson** [comment]
This has been deliberately disabled in openshift & not configurable ( https://github.com/openshift/origin/blob/f59053a0a62249190a721ab6a67d45986d80f596/pkg/cmd/server/kubernetes/node_config.go#L110) so I guess not. How would you feel about making it configurable via node config file but defaulted to disabled?

**Comment by liggitt** [comment]
We strongly discourage enabling something like unsecured readonly access.

That said, all kubelet settings that have corresponding command-line flags can already be set using the `kubeletArguments` map in the node config file, with the caveat that it can result in insecure, untested, and/or invalid configurations.

See https://github.com/openshift/origin/blob/f59053a0a62249190a721ab6a67d45986d80f596/pkg/cmd/server/api/v1/types.go#L49-L52

**Comment by jimmidyson** [comment]
Thanks @liggitt. Enough for me to carry on with for now, but need a proper solution to this.

**Comment by jimmidyson** [comment]
See GoogleCloudPlatform/heapster#320

**Comment by smarterclayton** [comment]
We'll look at exposing the port protected by an opaque secret defined in the config, accessed in the bearer token.  For now, using the direct kubelet argument to set a read only port should work - let us know if it doesn't.

**Comment by jimmidyson** [comment]
Using the extra args for the read-only port as @liggitt suggested works fine, just in time for a demo tomorrow - phew!

Could this secret be generated & a service account or secret be created at bootstrap time that can just be referenced in pod spec for monitoring apps?

**Comment by jimmidyson** [comment]
@smarterclayton @liggitt Has there been any further thought on this? This is essential for use with any metrics tools like Heapster or Prometheus.

**Comment by smarterclayton** [comment]
The only question is what security will we enforce - a secret token or a
signed assertion.

On Jul 14, 2015, at 7:31 AM, Jimmi Dyson <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> @liggitt
<https://github.com/liggitt> Has there been any further thought on this?
This is essential for use with any metrics tools like Heapster or
Prometheus.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3020#issuecomment-121209618>.

**Comment by jimmidyson** [comment]
If there was any way to reuse the service account that would simplify things from a client perspective. Perhaps an endpoint to retrieve a jwt containing appropriate claims from api server & use this to auth against the kubelet?

**Comment by jimmidyson** [comment]
Expanding on this a little bit more, there are likely to be other infrastructure services that rely on this same idea of a signed assertion, logging & metrics to name 2 that spring to mind. Locking down access to certain logs or metrics (e.g. only allowing authorized users to access a namespace/project centralised logs would seem kind of important in a multitenant env). Reusing a signed assertion would simplify this.

**Comment by sosiouxme** [comment]
Seems like OpenShift could provide both scoped tokens and signed assertions for different use cases. But it also seems to me that a JWT would be both easier for OpenShift to implement (no real change to authorization validations) and more immediately useful (selfishly, for authorizing access to logs and metrics, where we don't actually care what you can do with the API and would just as soon not have to round trip to the API to figure it out).

**Comment by liggitt** [comment]
> we don't actually care what you can do with the API and would prefer not have to round trip to the API to figure it out

You have to be careful not to conflate id tokens and access tokens (OpenShift only provides access tokens currently). If an id token lets you access logs/metrics, it is no longer an id token, it's an access token :)

**Comment by sosiouxme** [comment]
Well, what are you going to do with an ID token other than use it to authorize something?

**Comment by jimmidyson** [comment]
Another option would be to generate a client cert secret for metrics pods to use when connecting to the kubelet, but this still has the problem of no authzn I guess.

**Comment by jimmidyson** [comment]
@liggitt @smarterclayton Any news on this? Really want to get rid of the need for the insecure read only port to get metrics.

**Comment by smarterclayton** [comment]
We need to get a card into the platform management board and queue it up.
It's going to need to get into 3.1

On Aug 6, 2015, at 11:06 PM, Jimmi Dyson <notifications@github.com> wrote:

@liggitt <https://github.com/liggitt> @smarterclayton
<https://github.com/smarterclayton> Any news on this? Really want to get
rid of the need for the insecure read only port to get metrics.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3020#issuecomment-128508237>.

**Comment by jimmidyson** [comment]
Obviously this is something that will be needed upstream too.

**Comment by mwringe** [comment]
As there been any update on this? Or a link to the trello card?

We will need this to be able to run Heapster and Metrics on OpenShift without configuring the read only port option.

**Comment by jimmidyson** [comment]
This same discussion is being had in Kubernetes too...

**Comment by smarterclayton** [comment]
@pweil- can you create a card?

**Comment by pweil-** [comment]
existing card: https://trello.com/c/kej8gRJg/488-provide-access-to-metrics-and-stats-endpoints-without-auth  crosslinked to this discussion

**Comment by mwringe** [comment]
Instead of changing the authentication mechanism for all of the node endpoints, would it be possible to open a new endpoint under another port and proxy the /stats and /metrics there? And have this endpoint be secured using tokens authenticated via a subjectaccessreview?

Just trying to think of what our options are here without having to rewrite how all the nodes are configured and secured.

**Comment by liggitt** [comment]
I think there are enough variations we'll need that we should go ahead and solve the real problem.

Slices of permissions we're likely to want:
* Everything (master)
* read-only metrics/stats
* read-only log streaming
* read/write container exec access
* ...

Each of those are different roles we're likely to want to be able to isolate. Multiple ports seem difficult to manage for things like that.

**Comment by jimmidyson** [comment]
@mwringe We can achieve that with the openshift auth proxy thingy to the read-only port & have that bind to localhost. IMO it's a fallback position in case proper authzn doesn't make it in time.
