### ISSUE TITLE
Console: differentiate throbber for waiting and running builds

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#3029]
Currently, in the console, the throbber displayed for a 'waiting' build is the same as for a build which is running.  This is confusing to users since:

1.  It looks like builds begin running immediately
2.  They notice the timer when it resets from how long the build pod has been waiting to how long the build hs been running, don't understand that the timer is now displaying a different piece of information, and think the timer has reset.

I suggest that we differentiate these two states by differentiating the throbber for the two states.  The current throbber should be for the running state, and we should have a new throbber for the waiting state.

@liggitt

**Comment by sg00dwin** [comment]
This pull request addresses this issue
https://github.com/openshift/origin/pull/3185

**Comment by sg00dwin** [comment]
@pmorie can you verify and close this issue. thx

**Comment by sg00dwin** [comment]
@jwforres can be closed
