### ISSUE TITLE
Consider time-based retries for deployments

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3051]
#3035 exposes some undesirable retry configuration in the deployment controllers. The controllers could be taking advantage of the latest RetryManager improvements which add time-based retries.

Here's a breakdown of how retry handling works for the various deployment controllers today:

1. DeploymentConfigController
  1. Explicitly marked transient errors are retried indefinitely (rate limited)
  2. All other nonfatal errors are retried once immediately
2. DeploymentController
  1. Nonfatal errors are retried once immediately
3. DeployerPodController
  1. All errors are retried once immediately
4. ConfigChangeController
  1. Nonfatal errors are retried once immediately
5. ImageChangeController
  1. Nonfatal errors are retried once immediately

For each controller and error class we can choose to retry indefinitely, up to a certain amount of time, or up to a certain number of times. Let's use this issue to define the requirements for each controller.

**Comment by ironcladlou** [comment]
Consider that many important retries are implicitly occuring automatically based on periodic Reflector resyncs into FIFOs backing the controllers. So even with no explicit retry management we're re-processing the current state of things every once in a while.

**Comment by liggitt** [comment]
That's true, but longer timeouts on the API server will make full resyncs from dropped watches less frequent. Artificially short resyncs become a performance issue.

**Comment by ironcladlou** [comment]
>That's true, but longer timeouts on the API server will make full resyncs from dropped watches less frequent. Artificially short resyncs become a performance issue. 

Totally agree, just wanted to point out that we shouldn't actually miss retries entirely today, just that they'll happen inefficiently without resolution of this issue.

**Comment by ironcladlou** [comment]
My current impression is #2828 is higher priority than this issue. Should this be a p3?

**Comment by smarterclayton** [comment]
What's the status of this (@kargakis?)

**Comment by kargakis** [comment]
If @ironcladlou hasn't worked on it already locally then I guess it still needs fixing...

**Comment by ironcladlou** [comment]
Still needs work, and also need to audit error logging/event surfacing of each retry path. Pretty sure there are some places where we'll silently fail after a single retry limit is exceeded.

**Comment by kargakis** [comment]
Superseded by https://github.com/openshift/origin/issues/9468
