### ISSUE TITLE
Large amount of memory usage in service account controller

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#3053]
Scenario:

1. Create 500 projects
2. Wait 10 minutes
3. Capture heap

Results:

Service account controllers are holding on to large amounts of memory

![heap](https://cloud.githubusercontent.com/assets/6233452/8086336/e3c6aaca-0f62-11e5-932f-c73dcbd86d14.png)

**Comment by derekwaynecarr** [comment]
/cc @liggitt @deads2k @smarterclayton 

This was unexpected

**Comment by derekwaynecarr** [comment]
If I restart openshift with the same data set, the service account controllers then consume about 6MB in a steady state.

**Comment by derekwaynecarr** [comment]
See heap after restart:

![heap-after](https://cloud.githubusercontent.com/assets/6233452/8086530/e30d5074-0f63-11e5-99c9-476c36638d27.png)

**Comment by smarterclayton** [comment]
Spawned https://github.com/GoogleCloudPlatform/kubernetes/issues/9581 for prometheus and potential unbounded rest stat growth

**Comment by smarterclayton** [comment]
Prometheus fixes in #3056 and #3058

**Comment by derekwaynecarr** [comment]
Will run tests again to see how things improve when they merge.

**Comment by derekwaynecarr** [comment]
Things look better.

![heap-fix](https://cloud.githubusercontent.com/assets/6233452/8093404/bf6c8fba-0f8e-11e5-93d8-e8828c4a113d.png)

**Comment by liggitt** [comment]
hooray
