### ISSUE TITLE
osc edit can not find editor on windows

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#3062]
We need to make it have a sensible default like maybe notepad to allow it to work out of the box

**Comment by smarterclayton** [comment]
You can set the editor via "OSC_EDITOR" or just "EDITOR"

**Comment by kargakis** [comment]
I cannot imagine running by default on notepad though we can probably set it if runtime.GOOS equals windows.

**Comment by smarterclayton** [comment]
Can you make that change?  Also change OSC_EDITOR to OC_EDITOR

----- Original Message -----

**Comment by kargakis** [comment]
> Can you make that change? Also change OSC_EDITOR to OC_EDITOR

Sure, tomorrow.
