### ISSUE TITLE
Need the ability to execute scripts when a container is destroyed

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#3065]
When scaling down or destroying a container for any reason we should have the ability to execute scripts in the container. It can be an environment variable that points to the scripts. 

Use case is scale down on a database which has master/slaves and you want something to happen when you scale down. @ryguyrg has use case as well

**Comment by derekwaynecarr** [comment]
Have you looked at PreStopHooks?


https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L745

**Comment by smarterclayton** [comment]
I believe this is covered by PreStop
