### ISSUE TITLE
Deployments: use deployment config label to retrieve replication controllers in deployer pod

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#3071]
Main concern is running up the memory in the deployer process if you happen to have a large number of unrelated RC's

**Comment by smarterclayton** [comment]
P2 if we merge canary

**Comment by ironcladlou** [comment]
We don't set labels on the deployment for this purpose (as we used to be able to rely only on annotations for correlation), but we can easily make the change now.

**Comment by csrwng** [comment]
Sorry, closed by mistake.
