### ISSUE TITLE
Adding example DB from template/image-streams in openshift namespace using web console doesn't work

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#3085]
Run this:
```
oc create -n openshift -f examples/image-streams/image-streams-centos7.json
oc create -n openshift -f examples/db-templates
```

In the web console:
1. Log in as "foo"
2. Create a project "test"
3. In the project, do Create... > Browse all templates > Select mongodb-ephemeral > Create

The resulting DeploymentConfig doesn't indicate the `from` ImageStreamTag is in the openshift namespace:
```
$ oc get dc/mongodb -n test -o json
...
    "kind": "DeploymentConfig",
    "metadata": {
        "name": "mongodb",
        "namespace": "test",
...
    },
    "spec": {
...
        "triggers": [
            {
                "type": "ImageChange",
                "imageChangeParams": {
                    "automatic": true,
                    "containerNames": [
                        "mongodb"
                    ],
                    "from": {
                        "kind": "ImageStreamTag",
                        "name": "mongodb:latest"
                    }
                }
            },
... 
       ],
```

What is responsible for setting that namespace?

**Comment by liggitt** [comment]
Server log has errors like this:
```
E0611 01:05:59.924500    4779 factory.go:68] couldn't create initial Deployment for DeploymentConfig test/mongodb:0: DeploymentConfig "mongodb" is invalid: triggers[0].imageChange.from: invalid value 'mongodb': imageStream "mongodb" not found
E0611 01:05:59.982511    4779 factory.go:68] couldn't create initial Deployment for DeploymentConfig test/mongodb:0: DeploymentConfig "mongodb" is invalid: triggers[0].imageChange.from: invalid value 'mongodb': imageStream "mongodb" not found
```
which is completely expected since I have no mongodb imagestream in the test project

**Comment by mnagy** [comment]
Isn't this expected since the ImageStream is in a different namespace?

**Comment by liggitt** [comment]
Yes, but we're promoting use of the shared namespace for templates and image streams, so we need to make sure it works.

**Comment by bparees** [comment]
@liggitt we're still discussing exactly how we want to handle imagestream namespaces and the namespace templates reference to pick up images, but i'm probably going to end up adding the openshift namespace to the DB templates.

**Comment by bparees** [comment]
(and having out of the box instructions that say "create an openshift project, grant everyone view access,  create the imagestreams in it")

**Comment by liggitt** [comment]
ok. you want to leave this open to track the user-facing issue, or is there another one that covers it?

**Comment by bparees** [comment]
@liggitt i'll use this issue to fix the db templates.  is that what you mean by "user facing issue"?

**Comment by ncdc** [comment]
Isn't the openshift project auto created?

**Comment by liggitt** [comment]
An issue to make sure this end-to-end scenario works

**Comment by liggitt** [comment]
@ncdc yes

**Comment by bparees** [comment]
@liggitt @ncdc is it autocreated with everyone defaulting to view access?

**Comment by liggitt** [comment]
by default, all authenticated users have get and list permissions on templates and imagestreams

@ncdc do we need to add get on imagestream/layers for a builder or deployer in another namespace to be able to pull from that namespace?

**Comment by ncdc** [comment]
@liggitt I would assume so, if it doesn't work with the current policy.

**Comment by ncdc** [comment]
@liggitt I just tested with a regular user trying to docker pull from an image stream in the openshift namespace and it failed... When I granted system:image-puller to the user in the openshift namespace, then the push worked.

**Comment by ncdc** [comment]
@liggitt @deads2k @smarterclayton do we want to grant system:imagie-puller to system:authenticated in the openshift namespace by default?

**Comment by smarterclayton** [comment]
Yes

----- Original Message -----

**Comment by liggitt** [comment]
Or add `imagestreams/layers` to the shared openshift viewer role

**Comment by liggitt** [comment]
Either way, yes

**Comment by deads2k** [comment]
Since I'd like to assert absolute ownership of `system:*` roles for openshift to mutate at will, I'd rather have `get` on `imagestreams/layers` added to the shared openshift viewer role.  Binding a role to all-authenticated that we may choose to change in the future without warning seems bad.

**Comment by bparees** [comment]
@liggitt the db templates have been fixed to reference the openshift namespace..anything else left to do here?

**Comment by liggitt** [comment]
nope
