### ISSUE TITLE
[beta4] --dry-run deems to always fail when using it with creating a router

### ISSUE THREAD

**Issue by ljozsa** [openshift/origin#3089]
When going through the tutorial for openshift/origin I hit the following error in the 'Creating the Router' section.

> [root@master ~]# osadm router --dry-run \
> --credentials=/etc/openshift/master/openshift-router.kubeconfig
error: router "router" does not exist (no service)

I have also tried to run the fourth command from this section (with --dry-run appended) with the same result:

> [root@master ~]# osadm router --default-cert=cloudapps.router.pem \
> --credentials=/etc/openshift/master/openshift-router.kubeconfig \
> --selector='region=infra' \
> --images='registry.access.redhat.com/openshift3_beta/ose-${component}:${version}' --dry-run
error: router "router" does not exist (no service)

After running the aforementioned command without --dry-run, an error didn't appear.

> [root@master ~]# osadm router --default-cert=cloudapps.router.pem --credentials=/etc/openshift/master/openshift-router.kubeconfig --selector='region=infra' > --images='registry.access.redhat.com/openshift3_beta/ose-${component}:${version}' 
deploymentConfigs/router
services/router

When the router wasn't created the osc status command revealed:

> [root@master ~]# osc status
> In project default
> 
> service kubernetes (172.30.0.2:443)
> 
> service kubernetes-ro (172.30.0.1:80)
> 
> To see more information about a Service or DeploymentConfig, use 'osc describe service <name>' or 'osc describe dc <name>'.
You can use 'osc get all' to see lists of each of the types described above.

osc status after creating the router (without --dry-run):

> [root@master ~]# osc status
> In project default
> 
> service kubernetes (172.30.0.2:443)
> 
> service kubernetes-ro (172.30.0.1:80)
> 
> service router (172.30.41.160:80)
>  router deploys registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.5.2.2
>     #1 deployment running for 10 seconds - 1 pod
> 
> To see more information about a Service or DeploymentConfig, use 'osc describe service <name>' or 'osc describe dc <name>'.
You can use 'osc get all' to see lists of each of the types described above.

**Comment by sosiouxme** [comment]
Same as #2783

**Comment by danmcp** [comment]
Closing as dup.
