### ISSUE TITLE
Fix error messages in empty-dir and SCC

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#3092]
Post 3.0 text changes for error messages.

https://github.com/pweil-/origin/commit/3cfbf51fba94070d17c72b4be55265db1f4452bf#commitcomment-11634560

~~https://github.com/openshift/origin/pull/2868/files#r32329026~~

~~https://github.com/pweil-/origin/commit/e09662d7281b832624f25738d986003cc2269b25#commitcomment-11634656~~ taken care of in https://github.com/openshift/origin/pull/3115

**Comment by smarterclayton** [comment]
Fixed
