### ISSUE TITLE
Template referencing

### ISSUE THREAD

**Issue by SillyMoo** [openshift/origin#3099]
It would be nice to be able to create hierarchies of templates. So for example I may create a template for kicking off 'application A' and a template for kicking off 'application B'. I can share those templates around thus encouraging re-use, but I also want a 'system template' which launches both A and B. Right now to do this I would have to cut and paste the templates for A and B in to a new system template, which is not overly nice.

I would like to suggest a new resource that could be used within templates of the kind "templateReference". In this case I can use "oc create -f template_A" and "oc create -f template_B" to create my two application templates, and then "oc create -f system_template" which will contain template references to template_A and template_B (presumably through a selector?).

I would also suggest that the template reference should be able to specify parameters to be applied to the referenced template. Any parameters in the reference template that are not specified will become parameters of the template doing the referencing (i.e in our example the 'system_template').

**Comment by bparees** [comment]
we don't have plans to extend templates in this manner.  For more sophisticated use cases like this, other tools may be appropriate.
