### ISSUE TITLE
OpenShift goes in failed state reporting too many opened files

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#3126]
Environment:

OpenShift all-in-one

Scenario:
1. Create 500 projects
2. Create 100 users
3. Add a quota to each project
4. Wait

Get errors like following in log:

Jun 12 02:25:55 openshiftdev.local openshift[18587]: E0612 02:25:55.618495   18587 errors.go:66] apiserver received an error that is not an api.Status: 501: All the given peers are not reachable Get https://10.0.2.15:4001/v2/keys/kubernetes.io/pods/project-402?quorum=false&recursive=true&sorted=true: dial tcp 10.0.2.15:4001: too many open files]

Result:
Eventually OpenShift goes in a Failed state in systemd.

**Comment by derekwaynecarr** [comment]
Not 100% sure on this being the cause, but the resource quota controller could be optimized some.

If the status.used value is 0 for a particular quantity, we do not need to recalculate the value on a subsequent quota sync because it will still be 0.  Only if the value is > 0 (because admission controller incremented the value) do we need to check for deletes in resource quota controller.

Will patch and see if that helps.

**Comment by derekwaynecarr** [comment]
That being said, I still am suprised that this failure is failing the process and not sure why etcd is reporting too many open files if my ulimit is unlimited.

ideas @smarterclayton ?

**Comment by liggitt** [comment]
could be ephemeral port exhaustion

**Comment by smarterclayton** [comment]
Is your unlimited truly unlimited?  Lots of times I find it's not - I generally try a concrete # like 10k

**Comment by smarterclayton** [comment]
Or that

**Comment by smarterclayton** [comment]
Lots of watches is lots of trouble if we aren't reusing TCP connections (our limit is 500 right now) - but # of watches should be independent of # of projects

**Comment by derekwaynecarr** [comment]
A ulimit is only unlimited when its not ... will try setting explicit value

**Comment by smarterclayton** [comment]
The metrics endpoint should report # of open files as well

**Comment by derekwaynecarr** [comment]
lsof | grep openshift | wc -l peaked around 9261 before it crashed, could have gone higher.  will set a higher ulimit.

**Comment by derekwaynecarr** [comment]
My ulimit -n was 20000, going to try out my theory on quota piece to see if that makes things better.

**Comment by derekwaynecarr** [comment]
Ok, the quota controller needs some optimization for systems at rest.

Rough proposal:

ResourceQuota.Status should have a dirty flag that is set by Admission Control when a change is made in a namespace.

ResourceQuotaController only updates quota documents in background task if their dirty status flag is true.

**Comment by smarterclayton** [comment]
Is it the resync loop on the quota controller?

**Comment by derekwaynecarr** [comment]
Yup.  I could batch process them better as well in smaller loops.  Will need to do something.  Egg on face.  Hides in shame preparing to make a fix for tomorrow.

**Comment by smarterclayton** [comment]
We could make resync longer

**Comment by derekwaynecarr** [comment]
It needs to be longer and in bursts.  But the dirty flag and watching only quotas that have been marked dirty would make whole thing better I think

**Comment by derekwaynecarr** [comment]
Making resync longer without bursts will only hide problem until the resync happens.

**Comment by derekwaynecarr** [comment]
I think the dirty flag could cause a race condition if the quota is marked dirty and is observed in quota controller before pod was actually persisted post admission control.  I think maybe the quota controller should use a fifo queue and only pick N items off queue to process each iteration. Once queue is exhausted it could relist all.  That is probably the least invasive change.  Need to think more.  Negative is that deletes will take longer to observe, but maybe I can couple it with watching pods if it got bad.
