### ISSUE TITLE
regular users able to pull images from openshift namespace and shouldn't be.

### ISSUE THREAD

**Issue by bparees** [openshift/origin#3128]
while testing this pull:
https://github.com/openshift/origin/pull/3127

I created the imagestreams and templates in the openshift namespace using cluster-admin

then i logged into the console as "test-admin" and instantiated one of the templates.

The pod successfully started, meaning it pulled the image from the imagestream in the openshift namespace.  @liggitt says that it wasn't supposed to be able to do that because his PR to allow it is still pending.

@ncdc

**Comment by liggitt** [comment]
Andy, without the changes in #3103 a pull from another namespace's service account should have failed. What's the best way to debug the SAR the registry is running?

**Comment by liggitt** [comment]
@bparees which imagestreams did you create in the openshift namespace? if they were the example centos/rhel ones, those refer to public docker pullspecs, so a pull from them wouldn't actually run against the internal registry.

When I tried pulling from the registry for another project, things worked as I expected.

To test this, I did the following:

1. Started `sudo openshift start --latest-images`, and created the registry
2. Created stuff in openshift namespace:

  ```
oc create -n openshift -f examples/db-templates`
oc create -n openshift -f examples/image-streams/image-streams-centos7.json`
  ```

3. In the UI, created project `test1`, went through a create from source flow, selecting the node-js example repo and the node-js builder image stream (from the openshift namespace).

  The build succeeded. The builder pod looked like this:
  ```
"containers": [{
  "name": "sti-build",
  "image": "openshift/origin-sti-builder:latest",
  "env": [{
    "name": "BUILD",
    "value": "{\"kind\":\"Build\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"nodejs-ex-1\",\"namespace\":\"test1\",\"selfLink\":\"/oapi/v1/namespaces/test1/builds/nodejs-ex-1\",\"uid\":\"dcb6c150-10b9-11e5-83ef-3c970e4b7ffe\",\"resourceVersion\":\"349\",\"creationTimestamp\":\"2015-06-12T04:16:56Z\",\"labels\":{\"buildconfig\":\"nodejs-ex\",\"generatedby\":\"OpenShiftWebConsole\",\"name\":\"nodejs-ex\"}},\"spec\":{\"serviceAccount\":\"builder\",\"source\":{\"type\":\"Git\",\"git\":{\"uri\":\"https://github.com/openshift/nodejs-ex\",\"ref\":\"master\"}},\"strategy\":{\"type\":\"Source\",\"sourceStrategy\":{\"from\":{\"kind\":\"DockerImage\",\"name\":\"openshift/nodejs-010-centos7:latest\"}}},\"output\":{\"to\":{\"kind\":\"DockerImage\",\"name\":\"172.30.244.250:5000/test1/nodejs-ex:latest\"},\"pushSecret\":{\"name\":\"builder-dockercfg-05g3a\"}},\"resources\":{}},\"status\":{\"phase\":\"Pending\",\"config\":{\"kind\":\"BuildConfig\",\"namespace\":\"test1\",\"name\":\"nodejs-ex\"}}}"
...
  ```
  Both the container `image` and the `from` image were pulled from dockerhub. The output image was pushed to the local namespace.

4. I then
  1. output the deployment config from my local namespace

    `oc get dc nodejs-ex -n test1 > dc.json`,
  2. edited the namespace and added an explicit namespace (`test1`) to the `imageChangeParams.from` stanza
  3. and created it in a new project

    `oc create -f dc.json -n test2`

5. The deployment in the `test2` namespace hung trying to pull the image from the `test1` image stream. I saw API logs like this:

  ```
W0612 00:40:34.985017    1937 manager.go:1481] Failed to pull image "172.30.244.250:5000/test1/nodejs-ex@sha256:97db4852ec63dbfb3f712cfba6a6863a3b3ba0b2554c52b56ac26fc8e4d603d2" from pod "nodejs-ex-2-1iw23_test2" and container "nodejs-ex": Error: image test1/nodejs-ex@sha256:97db4852ec63dbfb3f712cfba6a6863a3b3ba0b2554c52b56ac26fc8e4d603d2 not found
  ```
  and logs from the registry like this:
  ```
time="2015-06-12T04:39:34Z" level=debug msg="OpenShift auth: checking for access to repository:test1/nodejs-ex:pull" 
time="2015-06-12T04:39:34Z" level=error msg="OpenShift access denied: User \"system:serviceaccount:test2:default\" cannot get imagestreams/layers in project \"test1\""
  ```

6. Those errors continued occasionally. I then authorized test2 to pull from test1:

  ```
  oc policy add-role-to-user system:image-puller system:serviceaccount:test2:default
  ```
  and the pull and deployment immediately succeeded

**Comment by liggitt** [comment]
Closing, since I think this is working as intended. @bparees reopen if you actually saw an unauthorized pull from another namespace's image in the internal registry.

**Comment by bparees** [comment]
@ncdc @liggitt you're correct, I was pulling from an external registry.  I thought the fact that it was referencing through an imagestreamtag (rather than a direct dockerimage reference) was sufficient to inject a security check.  If that's not the case then I agree, not a bug.

**Comment by liggitt** [comment]
the service accounts had visibility on imagestreams in the openshift namespace (which is enough to resolve the external reference), but not imagestreams/layers (which would have prevented pulling)
