### ISSUE TITLE
registry Authorize check returns early

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#3129]
AccessController#Authorized loops over requested access records:
```
	for _, access := range accessRecords {
		log.Debugf("OpenShift auth: checking for access to %s:%s:%s", access.Resource.Type, access.Resource.Name, access.Action)

		switch access.Resource.Type {
		case "repository":
                        ...
			return WithUserClient(ctx, client), nil
		case "admin":
			switch access.Action {
			case "prune":
				...
				return ctx, nil
			default:
				challenge.err = fmt.Errorf("Unknown action: %s", access.Action)
				return nil, challenge
			}
		}
	}
```

If the first accessRecord requested is allowed, the method returns and doesn't check the rest.

Also, if an unknown resource type is encountered, it is ignored, rather than failing

**Comment by liggitt** [comment]
definitely need to add test cases to cover this as well

**Comment by liggitt** [comment]
also, what does returning `ctx, nil` from this method do? I see that's what we return in the admin/prune case... does that mean `ctx` has elevated privileges?

**Comment by ncdc** [comment]
Agree that it's a problem that needs fixing. I'm off today. Can it wait until Monday?

**Comment by liggitt** [comment]
I can fix the early return... I'm just unclear about the significance of returning the original `ctx`

**Comment by ncdc** [comment]
You're allowed to add things to the context of you want. Or replace it, I suppose. Basically if auth is denied, return the challenge with an error. Otherwise return the ctx and no error.
