### ISSUE TITLE
Not able to get kubernetes info in origin v3 taken from source code

### ISSUE THREAD

**Issue by Yashu5** [openshift/origin#3131]
Hi, I am trying to build origin v3 server in fedora 22 from latest source code taken from here: 
https://github.com/openshift/origin/releases

When I start origin server using "./openshift start" its seems up and web console is also accessible at localhost:8443/console.

But I am not able to run any kubernetes command using "./openshift kube". It always gives 

" Error in configuration: default cluster has no server defined"

What does this mean?? is it not setting up kubernetes cluster properly , is there any solution or workaround for this as I am not able to perform any task because of this.

Thank-you so much in advance for any suggestion! 

~yash

**Comment by liggitt** [comment]
`openshift start` outputs a config file containing server information and cluster admin credentials to `./openshift.local.config/master/admin.kubeconfig`.

To run commands as a cluster admin, point `openshift kube` at the generated admin config file by passing `--config=openshift.local.config/master/admin.kubeconfig` (or by setting the `KUBECONFIG` envvar)

To run commands as a regular user, try logging in first (which generates a config file in the default location, `~/.kube/config`)
```
oc login --certificate-authority=openshift.local.config/master/ca.crt
```

**Comment by Yashu5** [comment]
Hi @liggitt , thanks its working now :)
