### ISSUE TITLE
oc login error: mkdir /openshift.local.certificates: permission denied

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#3132]
Running OpenShift aaf73b80cff01fd168924bc1a57edf7df8b84f4e on VirtualBox with
```
sudo /data/src/github.com/openshift/origin/_output/local/go/bin/openshift start --public-master=localhost
```

```
$ oc login
OpenShift server [https://localhost:8443]: 
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Username: demo
Authentication required for https://localhost:8443 (openshift)
Password: 
Login successful.

You don't have any projects. You can try to create a new project, by running

    $ oc new-project <projectname>

error: mkdir /openshift.local.certificates: permission denied
```

@mfojtik PTAL

**Comment by liggitt** [comment]
openshift.local.certificates has been gone for some time. How old is this box?

**Comment by rhcarvalho** [comment]
I just noticed that we changed from OPENSHIFTCONFIG to KUBECONFIG. Exporting KUBECONFIG=/data/src/github.com/openshift/origin/openshift.local.config/master/admin.kubeconfig
 solved the issue.

But the error message from `oc login` is weird. With other commands it tells me that I'm missing some config:

```
$ oc project
error: invalid configuration: default cluster has no server defined
see 'oc project -h' for help.
```

**Comment by liggitt** [comment]
`oc login` is designed to take you from a "no config" state to a "logged in" state, which is why it isn't surprised to have no config file available. The other commands expect to have config (server URL, credentials, etc)
