### ISSUE TITLE
The follow parameter for build logs is missing in API docs

### ISSUE THREAD

**Issue by mmilata** [openshift/origin#3137]
`GET /oapi/v1/namespaces/{namespaces}/builds/{name}/log` takes QueryParameter `follow`, however it cannot be seen in the swagger UI. It is also missing in http://docs.openshift.org/latest/rest_api/openshift_v1.html which I guess is a consequence of this.

**Comment by csrwng** [comment]
Fixed in https://github.com/GoogleCloudPlatform/kubernetes/pull/10426

**Comment by bparees** [comment]
fixed.
