### ISSUE TITLE
Use of cache.Store in build and deployment controllers is a memory leak

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3141]
The deployment and build controllers both have places which rely on maintaining a `cache.Store` populated with resources across all namespaces (e.g. builds, replication controllers, pods). This is clearly a major memory leak in the absence of support for a data structure which can spool to disk or something.

**Comment by ironcladlou** [comment]
cc @smarterclayton @bparees @abhgupta @pmorie

**Comment by liggitt** [comment]
Not sure I'd call it a memory leak inherently. The store caches etcd state, including deletions.

**Comment by smarterclayton** [comment]
No.... this is intentional to the design.  Databases are for persistent state - cache.Stores are for managing local views of the data.  Scaling past memory size is handled by sharding and other issues.
