### ISSUE TITLE
Missing validation for Service.Spec.TargetPort 

### ISSUE THREAD

**Issue by sdminonne** [openshift/origin#3143]
@smarterclayton @derekwaynecarr 
This is totally an upstream topic but I'm pushing here since we spoke about this during the scrum.

@pmorie FYI

Porting our blueprints we run into a quite bad UX.
Someone defined this kind of blueprint for a service

```javascript
{
   "kind":"Service",
   "apiVersion":"v1",
 ...
   "spec":{
      "ports": [
        {
          "port":6379,
          "targetPort": "6379"
        }
      ],
...
   }
}
```

The issue is that the "targetPort" is a string (accepted since the k8s accepts Int and String). 
The situation is quite misleading since the swagger-spec declares thiese fileds as `string`...

_result_: no endpoint found for this service.

My point here is that there's no validation for port String type except for empty strings and this is not enough.

I wrote a small patches here https://github.com/sdminonne/kubernetes/tree/bug_fix2
I've implemented almost this https://tools.ietf.org/html/rfc6335#section-5.1 (extended a little bit since I tested using my /etc/services) but well this is just to give an idea.

Thoughts?

**Comment by smarterclayton** [comment]
It makes sense but we'll definitely need to get upstream to agree on it.

----- Original Message -----

**Comment by sdminonne** [comment]
Thanks. I'm going to forward this to upstream

**Comment by sdminonne** [comment]
I'm going to modify my k8s to simplify the dicussion implementing only https://tools.ietf.org/html/rfc6335#section-5.1

**Comment by sdminonne** [comment]
ref PR https://github.com/GoogleCloudPlatform/kubernetes/pull/9736

**Comment by liggitt** [comment]
Fixed in master
