### ISSUE TITLE
Web console shows template description text of any length

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3144]
At some point, we need to elide or truncate the description. Likely a problem with image stream tag annotations as well.

See also #3116

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8135060/3f06bc9a-1102-11e5-9b77-dce9ebc81543.png)

**Comment by spadgett** [comment]
Project descriptions have the same issue.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8135256/def57452-1103-11e5-8bbe-2d0c60bb4ef9.png)

**Comment by liggitt** [comment]
Sometimes I like to tell little stories in my project descriptions

**Comment by spadgett** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1233576

We should be careful about names as well.
