### ISSUE TITLE
Toolbar elements take up too much space at mobile screen sizes

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3149]
We should consider hiding the toolbar items under a menu at small screen sizes. They take up nearly half the visible window. Also the filter `Add` button sometimes wraps onto its own line.

For example, here is the Web Console on an iPhone 5:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8137784/c6fab582-1113-11e5-9e24-f848d0a8b5d7.png)

/cc @sg00dwin

**Comment by sg00dwin** [comment]
Proposed collapsed/expanded nav for mobile resolution.

Static version
![revised-mobile-nav](https://cloud.githubusercontent.com/assets/1874151/8437926/5bae829c-1f30-11e5-9cdc-7977144ba15f.png)

**Comment by spadgett** [comment]
Steve, the repeated menu buttons on top of each other are a bit confusing. I see it's not new...

I'd suggest putting all navigation under a single menu button. Then at mobile resolutions, have the project name, a button with a filter icon for filters, and a button with a `+` icon for create. This would be much more compact. You can still switch projects by clicking the OpenShift Origin logo to get the list, so the dropdown isn't strictly necessary.

Thoughts?

/cc @ajacobs21e

**Comment by ajacobs21e** [comment]
I agree that two hamburgers doesn't look great. 

Here's a very rough idea of another way to lay this out. 
![mobileidea](https://cloud.githubusercontent.com/assets/6415742/8527649/cc8ba7c4-23db-11e5-8d4d-19b09f50c9ac.png)
This could be shrunk more by using the icons Sam suggested

**Comment by spadgett** [comment]
Rough mockup of what I was thinking.

<img width="394" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/8528275/1cdd512e-23e0-11e5-9f2c-42078fda453a.png">

**Comment by ajacobs21e** [comment]
Yeah project name should be above overview and any actions (filter, add). 
Are you thinking the menu icon will reveal docs / user menu? How would you get to Browse or Settings? What happens when clicking the filter icon?

I'm free after 2 if you want to get together to talk through this.

**Comment by sg00dwin** [comment]
A pass at moving project subnav items into one menu and placing filter and create actions associated with the  project name.

![revised-mobile-nav3](https://cloud.githubusercontent.com/assets/1874151/8528569/ad304974-23e1-11e5-9988-b315e5903ee6.png)

**Comment by spadgett** [comment]
@ajacobs21e Steve's last mockup is close to what I was thinking. Filter would be a toggle button that shows or hides the filter control. I'd want to prototype it to see how well it works.

@sg00dwin I'd make the project name bigger than the overview header text and use a button style closer to what I had above. Add a bolder line to separate documentation and user from the nav items above? Or a different background color.

Are we planning on adding more to the user menu? If not, it could just be a `Log out <username>...` link rather than a dropdown.

I'm open to ideas, but I think this better than what we had before.

**Comment by ajacobs21e** [comment]
Is there a reason to use vertical buttons rather than tabs?

**Comment by spadgett** [comment]
@ajacobs21e Not necessarily. How would the secondary browse nav items look?

**Comment by sg00dwin** [comment]
@ajacobs21e, @spadgett Listing the tertiary nav beneath vertical list makes more sense. And adding more nav items then tabs would start stacking.

**Comment by ajacobs21e** [comment]
@spadgett I don't know of anything else to add to the user menu at this time. The only reason I could see for keeping it as a dropdown is so you have to take two steps to logout and don't accidentally select it. 

https://rawgit.com/patternfly/patternfly/master/tests/basic.html Here's an example of patternfly that shows the utility nav links first, then the first level navigation links shown. "Browse" would have a down caret and would expand to show the secondary nav items like the user menu does in the example.

**Comment by spadgett** [comment]
@ajacobs21e Is this the example you mean?

<img width="241" alt="basic_-_patternfly" src="https://cloud.githubusercontent.com/assets/1167259/8531391/01149852-23f5-11e5-86ea-9d7f0e5948bc.png">

I would prefer this to the current implementation. Right now if you click `Browse`, the menu collapses immediately without giving you a chance to pick the secondary nav item.

**Comment by ajacobs21e** [comment]
Yep, clicking browse would expand a second menu like that one

On Mon, Jul 6, 2015 at 3:40 PM, Sam Padgett <notifications@github.com>
wrote:

> @ajacobs21e <https://github.com/ajacobs21e> Is this the example you mean?
>
> [image: basic_-_patternfly]
> <https://cloud.githubusercontent.com/assets/1167259/8531391/01149852-23f5-11e5-86ea-9d7f0e5948bc.png>
>
> I would prefer this to the current implementation. Right now if you click
> Browse, the menu collapses immediately without giving you a chance to
> pick the secondary nav item.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3149#issuecomment-118974928>.
>



-- 

Allie Jacobs
UXD

calendar
<https://www.google.com/calendar/b/1/embed?src=ajacobs@redhat.com&ctz=America/New_York>

**Comment by spadgett** [comment]
That looks good to me.

This Patternfly example is pretty close to our UI. The top navbar items and the tabs below collapse down into one vertical list at mobile sizes, which is what we're proposing here. I think it's a much better for mobile.

**Comment by jwforres** [comment]
Most of this has been resolved the remaining issue is https://github.com/openshift/origin/issues/4371
