### ISSUE TITLE
Sync docs/cli with oc command grouping

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#3165]
[cli.md](https://github.com/openshift/origin/blob/master/docs/cli.md#oc-command-line-interface) should be updated with the latest oc [grouping](https://github.com/openshift/origin/blob/6e489683eb043eabd175a0e2c00f00e03214b6bf/pkg/cmd/cli/cli.go#L67-L134).

**Comment by kargakis** [comment]
@tnguyen-rh can you work on this?

**Comment by tnguyen-rh** [comment]
@kargakis 
Sure.  Could you please describe what needs to be done?
I guess that before things weren't grouped, but now they are, so the task is to rearrange the already-written descriptions and examples to be in those groups.  Is that close?
The more precise you can describe the task, the quicker i can start on it.

**Comment by kargakis** [comment]
Yes, this is pretty straight-forward. Just re-arrange the commands based on https://github.com/openshift/origin/blob/6e489683eb043eabd175a0e2c00f00e03214b6bf/pkg/cmd/cli/cli.go#L69-L132
Also note that some commands are missing from the document such as oc types, oc export, oc whoami, oc tag, etc. 
Track their descriptions/examples in https://github.com/openshift/origin/tree/master/pkg/cmd/cli/cmd and add them as well.
It would be nice to have a small description for every group too. If you have a hard time coming up with those, 
@smarterclayton can help.


----- Original Message -----

**Comment by tnguyen-rh** [comment]
Docs card: https://trello.com/c/6gujzl2I

**Comment by adellape** [comment]
@tnguyen-rh May want to sync with @bfallonf on https://trello.com/c/Z4cRqhe2/668-review-the-cli-reference-guide-for-completeness-and-accuracy.

Looks like it may already be getting taken care of in https://github.com/openshift/openshift-docs/pull/586.

Also note the following recent inclusion, though it's still being worked out https://github.com/openshift/openshift-docs/pull/560.

**Comment by adellape** [comment]
@tnguyen-rh Oh sorry, just remembered this PR this was for the `docs/cli.md`. Disregard.

**Comment by tnguyen-rh** [comment]
@adellape No worries.  I've added [origin] to the docs card title as a reminder.

**Comment by tnguyen-rh** [comment]
@kargakis @danmcp @smarterclayton @adellape 
wip: https://github.com/tnguyen-rh/origin/blob/doc-command-grouping/docs/cli.md
Please let me know if you see anything amiss (missing, out of place).  In particular, i created additional heading *Miscellaneous?* for `oc namespace` because i could not determine where it belongs in the other groups.  Clue welcome!

**Comment by smarterclayton** [comment]
`oc namespace` should have been deleted - not supported anymore

**Comment by tnguyen-rh** [comment]
@smarterclayton Thanks.  I removed that section/command.

**Comment by tnguyen-rh** [comment]
@smarterclayton Just added a "synonym redirect" from `oc config` to `kubectl config`.  My quetions are:

    * Is that correct?
    * If so, is that the preferred way to link to upstream (kubernetes) docs?

**Comment by tnguyen-rh** [comment]
@kargakis Is `cli.md` to be the reference for all the oc commands, with each command's options fully documented there?  Another way to ask the question: Where should the documentation for the options for every `oc foo` live?

**Comment by kargakis** [comment]
> @kargakis Is cli.md to be the reference for all the oc commands, with each command's options fully documented there? Another way to ask the question: Where should the documentation for the options for every oc foo live?

Yes, cli.md is the place inside the origin repo documenting the cli interface.

**Comment by tnguyen-rh** [comment]
@kargakis 
All the commands are in place (see wip link above).
I've squashed (https://github.com/tnguyen-rh/origin/tree/doc-command-grouping) and created PR: https://github.com/openshift/origin/pull/3559

**Comment by kargakis** [comment]
Fixes by #3559
