### ISSUE TITLE
Incorrect log messages being printed by deployment or build pod controller

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3169]
```
controller.go:151] No Build found for pod default/docker-registry-1-deploy
```

**Comment by deads2k** [comment]
Looks right to me: https://github.com/openshift/origin/blob/master/pkg/build/controller/controller.go#L151 .  It's a v(5) trace statement indicating why its not taking any action for a given pod.

That we get the message does suggest that the watch should be more selective.

**Comment by smarterclayton** [comment]
The message is redundant - it provides no useful value (ignoring pods that aren't a criteria).

----- Original Message -----

**Comment by ironcladlou** [comment]
This shouldn't have the `component/deployments` label.

**Comment by bparees** [comment]
I agree with @deads2k which is why i put the message there.  Consider the case where the buildStore contents is wrong (ie we really should have found a build for a particular pod and didn't)?  That's the point of tracing there.

**Comment by liggitt** [comment]
Can the watch be more selective? I noticed that field selectors mappings are missing from v1 upstream... might that be causing a field selector to be ignored and return a broader match?

**Comment by bparees** [comment]
@liggitt does it matter?  my understanding is the filtering is all client side so whether it happens at the watch or in the handler is pretty much moot.

**Comment by deads2k** [comment]
> @liggitt does it matter? my understanding is the filtering is all client side so whether it happens at the watch or in the handler is pretty much moot.

Same as my original comment.  With a more restrictive watch, your handle wouldn't even be called.  Why check more than you have to even if it doesn't gain much performance it makes the intent more clear: "I want to look at all pods like this".

**Comment by bparees** [comment]
is there a p99?

**Comment by smarterclayton** [comment]
There is no value in printing something like this.  Instead, print "hey, i found a pod to match" at V(5) if you want.  By observation you can determine that the pod is not ignored.   Watches being more selective is a  good thing as well.

Spamming crap into logs at v(5) makes every problem harder to debug.

**Comment by bparees** [comment]
@smarterclayton how is printing every pod we're invoked against any less spammy?

**Comment by smarterclayton** [comment]
If you have 10k pods in a deployment, and 100 builds at any time, I'd prefer we wrote 100 messages at v(5) instead of 9,900.  And by prefer, I mean... why would you want to print a meaningless log message O(N) times?  You mean you'd prefer to filter out those 9,900 messages from a running production system you're trying to debug?

----- Original Message -----

**Comment by smarterclayton** [comment]
You're not putting 9,900 pods across the watch wire, you're putting 100.  Pretty significant.

----- Original Message -----

**Comment by liggitt** [comment]
> my understanding is the filtering is all client side

I'm not familiar with how this is filtering, but some filtering can happen server-side

**Comment by smarterclayton** [comment]
Yeah, we filter several things on the server.  It's just not filtered in etcd.
