### ISSUE TITLE
Stats password generation for router not usable by other components

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3170]
3de5d2d7 introduced stats password generation in the create router command, but this isn't a solution that allows other infrastructure to integrate with the routers in a predictable way.  We should not be generating a password in this fashion.

**Comment by liggitt** [comment]
The password is able to be set rather than generated if desired. What did you have in mind.

**Comment by smarterclayton** [comment]
It needs to be secured like other infrastructure components.  The stat collectors really shouldn't be dependent on passing passwords around.

**Comment by smarterclayton** [comment]
This is fixed by using infrastructure auth checking for metrics on the router in 3.9.
