### ISSUE TITLE
Custom builder missing branch/tag/ref info

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#3176]
Custom builder passes `SOURCE_REPOSITORY` env variable pointing to git URL, but does not pass branch/tag/ref (`Ref` field from `GitBuildSource` struct). We should either remove `SOURCE_REPOSITORY` env var since the entire `Build` object is being serialized or update it to point the branch/tag/ref part as well.

@bparees @mfojtik fyi

**Comment by mfojtik** [comment]
We should add `SOURCE_REF` variable to help custom builders. I don't think we should require custom builders to implement deserialization of BUILD variable... More vars we can give them to help, better.

**Comment by soltysh** [comment]
@bparees please close per @mfojtik PR.
