### ISSUE TITLE
Sample app build keps failing

### ISSUE THREAD

**Issue by aries1980** [openshift/origin#3177]
[root@csibesz openshift]# oc create -f application-template-dockerbuild.json
    [root@csibesz openshift]# oc new-app ruby-helloworld-sample
    services/frontend
    routes/route-edge
    imagestreams/origin-ruby-sample
    imagestreams/ruby-20-centos7
    buildconfigs/ruby-sample-build
    deploymentconfigs/frontend
    services/database
    deploymentconfigs/database
    Service "frontend" created at 172.30.209.103 with port mappings 5432->8080.
    A build was created - you can run `oc start-build ruby-sample-build` to start it.
    Service "database" created at 172.30.77.208 with port mappings 5434->3306.

Then

    [root@csibesz openshift]# oc status
    In project OpenShift 3 Sample (test)

    service database (172.30.77.208:5434 -> 3306)
      database deploys docker.io/openshift/mysql-55-centos7:latest 
        #1 deployment failed 20 seconds ago

    service frontend (172.30.209.103:5432 -> 8080)
      frontend deploys origin-ruby-sample:latest <- docker build of git://github.com/openshift/ruby-hello-world.git 
        build 1 running for 6 seconds
        #1 deployment waiting on image or update

    To see more information about a Service or DeploymentConfig, use 'oc describe service <name>' or 'oc describe dc <name>'.
    You can use 'oc get all' to see lists of each of the types described above.

I checked events on the web console too:

1:11:58 PM 	frontend 	DeploymentConfig 	failedCreate 	Couldn't create initial deployment: DeploymentConfig "frontend" is invalid: triggers[0].imageChange.tag: invalid value 'latest': no image recorded for test/origin-ruby-sample:latest (6 times in the last 4 minutes, 2 seconds) 
1:10:27 PM 	ruby-sample-build-2-build 	Pod 	killing 	Killing ea9055421edec43385336bde38b51b54bbefdf088b51ff9e1367a5eee4a8a869 

Do I miss something?

**Comment by sosiouxme** [comment]
First question: are you running on CentOS? In which case https://github.com/openshift/origin/issues/3150 would apply and would explain why your database (or any) deployment failed.

Second question: what happens if you wait for the frontend build to finish? The event you saw is normal for the case where the image to be deployed hasn't been built yet.

**Comment by aries1980** [comment]
I run it on Fedora 22.
I've tried to rebuild it, but the effect is the some.

**Comment by bparees** [comment]
did the build succeed including pushing the image?  (oc build-logs <build name>)

**Comment by mfojtik** [comment]
@bparees @csrwng this sounds similar to the issue we had with deployer image some time ago. 

@aries1980 have you tried to pull the latest deployer image?

**Comment by abhat** [comment]
+1 on the image push issue. I am running origin on RHEL7.

**Comment by bparees** [comment]
@abhat sorry, what push issue are you seeing?

**Comment by abhat** [comment]
@bparees, actually that might have been a misconfigured openshift-sdn solution. One of the nodes didn't have the right overlay IP causing the image repository push to fail.

**Comment by bparees** [comment]
@aries1980 are you still having issues?

**Comment by bparees** [comment]
closing without prejudice, feel free to reopen if you are still having issues.
