### ISSUE TITLE
OpenShift server hangs after some time

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#3178]
This is happening randomly on Vagrant (libvirt) with F21. At some point, the OpenShift starts eating 100% of CPU and refuse to accept new new TCP connections.

I managed to get a stack dump when this happen: http://omicron.mifo.sk/server.log.txt

@smarterclayton FYI

**Comment by ncdc** [comment]
I routinely see OpenShift using 100% cpu after I suspend and later resume my VM with OpenShift running. Here's a goroutine dump from 1 of those times: https://gist.githubusercontent.com/ncdc/3e2d162c6f052163dfc0/raw/openshift.log

**Comment by mfojtik** [comment]
it might be related to docker somehow. when this happens docker also become unresponsive and docker ps just hangs... also this error is not related to sleep/unsleep in make case it happens randomly, sometimes few minutes after I spawn vagrant.

**Comment by ncdc** [comment]
Probably 2 different issues, then.

**Comment by smarterclayton** [comment]
Michal's case shows a lot of things waiting for 72 minutes which seems like some sort of degenerate failure case - the network subsystem failed or similar.  Andy's lacks that.  Suspect it's two different issues.

**Comment by smarterclayton** [comment]
If you can recreate this consistently, enable OPENSHIFT_PROFILE=web, start a cpu profile, then trigger the problem.

**Comment by smarterclayton** [comment]
Also, grab the metrics dump and let's look for insanely large numbers of things. (hit /metrics with a valid user)

**Comment by smarterclayton** [comment]
Michal, do you have tcp4 reuse_port set?

**Comment by smarterclayton** [comment]
Michal's trace shows that UDP packets were being received consistently until about 72 minutes before he aborted (the DNS UDP listener was seeing consistent traffic).  That's indicative of things like port exhaustion, which is possible if we overload etcd as @derekwaynecarr has learned and don't have port reuse in place.  A wedge seems unlikely, unless it was a true wedge in the core golang runtime, since events continued to be delivered.  Can you try capturing the number of TCP ports you have in TIME_WAIT via lsof if you can create?

**Comment by smarterclayton** [comment]
Andy's has three goroutines in runnable - all three are cadvisor - one for OOM streamer, one for stat gathers, and one from processing stats.  Possible those got preempted and are just waiting, or also possible they're in a hot loop.  The AddStats() call is in a quick sort - it's possible that the call is sorting a massive amount of items in memory (in which case a heap dump would tell us if there is a ton of stuff in memory).  Andy, what commit is this?

**Comment by derekwaynecarr** [comment]
ulimit of 1024 is also really low if you were on a VM.  See fix for that here 
https://github.com/openshift/vagrant-openshift/pull/270

But if etcd was running long enough to need a snapshot, it would easily crash for me with lower limit and then openshift would go in an unresponsive state as well.

**Comment by ncdc** [comment]
@smarterclayton I unfortunately don't have the commit as the log is from last week and I've already updated. If it happens again, I can post another log along with the specific commit. If you have specific commands I should run or actions to take the next time I see this behavior, please let me know.

**Comment by smarterclayton** [comment]
The heap dump is relevant and the CPU capture

**Comment by mfojtik** [comment]
It is happening again today and it is very random... I can't consistently reproduce this :-( One thing that I think might be useful is that i'm not running on VirtualBox (as rest of the guys here) but on libvirt Vagrant.
They are not experiencing this on VirtualBox.... I wonder if we should not spend more time testing OpenShift  running in OpenStack or something that runs on KVM. Maybe there is a virtualization problem.

**Comment by mfojtik** [comment]
@smarterclayton so this is what I did:

```
sysctl net.ipv4.tcp_tw_reuse=1
sysctl fs.file-max=404476
echo "root hard nofile 4096" >> /etc/security/limits.conf
```

I'm going to test this today if I hit this issue again.

**Comment by mfojtik** [comment]
More details about my environment:

VM (created by libvirt vagrant plugin)
```console
Linux openshiftdev.local 3.17.4-301.fc21.x86_64 #1 SMP Thu Nov 27 19:09:10 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

[root@openshiftdev origin]# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 350a636/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 350a636/1.6.0
OS/Arch (server): linux/amd64

[root@openshiftdev origin]# go version
go version go1.4.2 linux/amd64

[root@openshiftdev origin]# cat /etc/fedora-release 
Fedora release 21 (Twenty One)
```

Host:

```console
Linux pi 4.0.4-303.fc22.x86_64 #1 SMP Thu May 28 12:37:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by liggitt** [comment]
https://github.com/openshift/origin/issues/5154 open for this error:
```
rcode is not equal to success
```

there's lots of instances of `github.com/google/cadvisor/manager.(*containerData).housekeeping` in the captured stack as well... I'm guessing https://github.com/openshift/origin/issues/1370 fixed that issue

Closing, please reopen if you observe this again
