### ISSUE TITLE
Main content "bounces" when typing in filter control in IE 10

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3180]
The nav bar is resized slightly larger and then smaller, causing the content to bounce slightly as you type filters. I've only seen it in IE 10. This doesn't happen in Chrome, Firefox, or Safari.

**Comment by spadgett** [comment]
Looks like the height of the filter input field is changing on focus. Also part of the `y` in the placeholder text is clipped.

![ie10_-_win7__running_](https://cloud.githubusercontent.com/assets/1167259/8161325/32eb7984-1344-11e5-9e21-a1a44ba22823.png)

**Comment by spadgett** [comment]
@jwforres fyi

Note that the entire pages bounces as you type... It's pretty ugly. I think it should be higher than P3.

**Comment by spadgett** [comment]
@sg00dwin can you take a look? @jwforres mentioned you styled this widget. It seems to be related to the CSS.

**Comment by liggitt** [comment]
ugly only gets you p3 :)
