### ISSUE TITLE
Expected directory permissions to be: -rwxrwxr-x; got: -rwxrwxrwx

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#3182]
As I add applications like [rails-ex](https://github.com/openshift/rails-ex) to my OpenShift server (VirtualBox, Fedora 21, 6dcc145909841495984dbe5b), I often see errors like these in the logs:

```
E0615 15:17:31.423202    1616 empty_dir.go:238] Expected directory "/data/src/github.com/openshift/origin/openshift.local.volumes/pods/718d7b95-1365-11e5-a12b-080027c5bfa9/volumes/kubernetes.io~empty-dir/registry-storage" permissions to be: -rwxrwxr-x; got: -rwxrwxrwx
E0615 15:17:41.772670    1616 empty_dir.go:238] Expected directory "/data/src/github.com/openshift/origin/openshift.local.volumes/pods/718d7b95-1365-11e5-a12b-080027c5bfa9/volumes/kubernetes.io~empty-dir/registry-storage" permissions to be: -rwxrwxr-x; got: -rwxrwxrwx
E0615 15:17:43.474667    1616 reflector.go:168] watch of *api.Namespace ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [820/752]) [1819]
E0615 15:17:51.864017    1616 empty_dir.go:238] Expected directory "/data/src/github.com/openshift/origin/openshift.local.volumes/pods/718d7b95-1365-11e5-a12b-080027c5bfa9/volumes/kubernetes.io~empty-dir/registry-storage" permissions to be: -rwxrwxr-x; got: -rwxrwxrwx
E0615 15:18:02.269898    1616 empty_dir.go:238] Expected directory "/data/src/github.com/openshift/origin/openshift.local.volumes/pods/718d7b95-1365-11e5-a12b-080027c5bfa9/volumes/kubernetes.io~empty-dir/registry-storage" permissions to be: -rwxrwxr-x; got: -rwxrwxrwx
```

I can't tell if they bring any misbehavior, but thought it was better to report it.

@pmorie FYI

**Comment by pmorie** [comment]
@rhcarvalho That might be a bug -- I'll take a look.

**Comment by pmorie** [comment]
This should be fixed now by #3038

**Comment by pmorie** [comment]
The repeat messages in the logs are fixed by #3038.  I still need to take a look at the issue doing chmods on vboxsf filesystems.

**Comment by soltysh** [comment]
@rhcarvalho I hit the same problem last week, thx to Paul and Andy I was told to move the volume dir to different directory than the one mounted with vboxsf, (see https://github.com/openshift/origin/pull/3256 where I've added that info to sample-app's readme) .

**Comment by ramr** [comment]
Ran into the same issue. Another alternative to the one @soltysh mentioned is to edit the ```/openshift.local.config/node-openshift-minion-*/node-config.yaml```  file and change the ```volumeDirectory``` entry to point to a local directory.  
Example:  ```volumeDirectory: /var/lib/openshift/openshift.local.volumes_openshift-minion-1```

As an aside, looks like we have a lot of ```openshift.local.*``` directories spread across ```/ (root)``` and ```/vagrant``` paths.  Maybe merge into something like ```/var/lib/openshift.local``` and have the config/volumes/etc be subdirectories in that single hierarchy.

**Comment by soltysh** [comment]
> Maybe merge into something like /var/lib/openshift.local and have the config/volumes/etc be subdirectories in that single hierarchy.

+1 on that idea.

**Comment by rhcarvalho** [comment]
> As an aside, looks like we have a lot of openshift.local.* directories spread across / (root) and /vagrant paths.

If I start the OS server by calling the binary, I just have `openshift.local.*` in the current working dir.
If I do `sudo systemctl start openshift`, then the files go into `/`. That seems reasonable to me.

**Comment by liggitt** [comment]
> Maybe merge into something like /var/lib/openshift.local and have the config/volumes/etc be subdirectories in that single hierarchy.

Let's not restructure our paths... that introduces a lot of issues with backwards compatibility for little benefit. We can already specify the volume dir to use...

**Comment by rhcarvalho** [comment]
@pmorie is there still anything to be done with this issue? If not, I'll close it.
