### ISSUE TITLE
Doing a re-list in response to an outdated watch should be delayed to avoid non-stop requests

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3183]
In some scenarios, IE begins to receive 304 not modified responses from the server. This causes watch window expired errors when trying to establish the web socket, which closes the web socket abnormally, which causes us to attempt to re-list, which gives a cached response, and so on. Loading the overview page can cause tens of thousands of requests if you leave it open for a few minutes.

304 Not Modified responses:

![ie10_-_win7__running_](https://cloud.githubusercontent.com/assets/1167259/8163453/20d61c56-1351-11e5-8a02-770be14da65e.png)

DEBUG log:

![ie10_-_win7__running_](https://cloud.githubusercontent.com/assets/1167259/8163466/30a4f68e-1351-11e5-869b-f1dd79443380.png)

I'm not certain under what conditions the 304 responses occur. I don't see any caching headers in the request.

Request:

![ie10_-_win7__running_](https://cloud.githubusercontent.com/assets/1167259/8163496/5e52ebfe-1351-11e5-8a0c-530274a2c5a8.png)

Response:

![ie10_-_win7__running_](https://cloud.githubusercontent.com/assets/1167259/8163502/668f6fc2-1351-11e5-81df-2ec41b44c855.png)

I've only seen this issue in IE 10.

**Comment by liggitt** [comment]
Spawning a p1 issue to set no-cache headers from the API: #3184

We should introduce a delay when doing a re-list as well, rather than spinning immediately.

**Comment by spadgett** [comment]
I've confirmed the error is indeed watch window expired. When I disable caching in IE developer tools, everything works as expected.

**Comment by smarterclayton** [comment]
Are you going to use this issue for the delay

**Comment by liggitt** [comment]
yes

**Comment by spadgett** [comment]
What's a reasonable delay? 30 seconds? 1 minute?

**Comment by liggitt** [comment]
probably the same as the requeue of the reopen, 1 second is fine, just to keep the CPU from racing.

**Comment by spadgett** [comment]
We might look at waiting to reset the retry count until we are able to successfully watch again. On the overview page we watch about 7 different lists. Even with a second delay, that's 7 re-lists per second, and the loop never breaks if the watch fails every time after a re-list.

I think we're also a bit aggressive even in cases when we don't re-list. Once per second per resource seems too fast.

**Comment by liggitt** [comment]
maybe moving the reset to `_watchOpOnMessage` after the `ERROR` handling bit?

**Comment by liggitt** [comment]
remember it's once per second for five seconds, then it stops trying (or is supposed to)
