### ISSUE TITLE
Filters not working on browse builds page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3193]
If I put in filter values that don't match anything, I still see builds (despite a message saying filters have hidden all builds).

![openshift_web_console_and_warning_icon_sometimes_flickers_briefly_on_browse_deployments_page_ _issue__2855_ _openshift_origin](https://cloud.githubusercontent.com/assets/1167259/8165862/dff247a8-1361-11e5-9abe-580212db6830.png)

**Comment by spadgett** [comment]
Same issue on the browse deployments page.

**Comment by spadgett** [comment]
Also an issue for monopods on the overview page.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8167598/581723d8-136d-11e5-9dfc-b2d9daedb265.png)

**Comment by spadgett** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1232250

**Comment by spadgett** [comment]
And https://bugzilla.redhat.com/show_bug.cgi?id=1232138

**Comment by spadgett** [comment]
For the builds page, it looks like we're not updating `$scope.buildsByBuildConfig` in the `onActiveFiltersChanged` listener. Likely a similar problem on the deployments page, which is not organized by deployment configuration.

On the overview page, we only filter services using the label selector. We make no effort to filter replication controllers or monopods with no service.

**Comment by liggitt** [comment]
overview page behavior is as-designed
