### ISSUE TITLE
CA cert provided to pods via service account

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#3209]
Re: GoogleCloudPlatform/kubernetes#7648

This is pretty much essential for any use of the API server from a pod without having to disable cert validation, which poses a security risk. As Origin is slightly more focused on security than upstream, any chance of getting this in to Origin soon & pushing upstream ASAP afterwards? Is it something you'd accept a PR for if I get a chance to take a look?

/cc @liggitt @smarterclayton

**Comment by liggitt** [comment]
Should be able to make use of https://github.com/GoogleCloudPlatform/kubernetes/pull/10264 once it merges and we pick it up

**Comment by jimmidyson** [comment]
@liggitt looks good! Thanks!

**Comment by jimmidyson** [comment]
@liggitt Now GoogleCloudPlatform/kubernetes#10264 is merged upstream I assume this will be picked up in next rebase? Any idea when that will be?

**Comment by liggitt** [comment]
correct... @smarterclayton do we have an ETA for that?

**Comment by jimmidyson** [comment]
@liggitt So this will be available in next release? Can this be closed now?

**Comment by smarterclayton** [comment]
Merged

**Comment by liggitt** [comment]
Ansible issue (https://github.com/openshift/openshift-ansible/issues/333) is still open to hook up the config value in the installer, but this is available now in origin

**Comment by jimmidyson** [comment]
Thanks!
