### ISSUE TITLE
required fields for builds listed as `omitempty`

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3212]
`omitempty` should only be specified on optional fields.  https://github.com/openshift/origin/blob/master/pkg/build/api/v1/types.go#L119 as an example.

 1. SourceBuildStrategy.From (why is this a pointer?)
 1. BuildSource.Type
 1. CustomBuildStrategy.From (why is this a pointer?)

@liggitt this is straightforward, I'll take it as I go through using it.

**Comment by deads2k** [comment]
@bparees do we want a message like this (what we have) `parameters.strategy.customStrategy: required value`  or do we want an "invalid field" error message that can indicate that the field is required because of the strategy type?

**Comment by bparees** [comment]
required value for a given object type seems sufficient to me.

**Comment by bparees** [comment]
and i don't remember why those are pointers or specified as omitempty.  probably just got cargo-culted from elsewhere.
