### ISSUE TITLE
New-app: Improve structure of code

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#3215]
It is difficult to follow which parts of the inputs are populated at a given time. New-app could benefit from a more functional-style flow with immutable inputs/outputs that can be more easily followed.

**Comment by deads2k** [comment]
Art or Math? :)

**Comment by soltysh** [comment]
:+1: I've been struggling to find anything in new-app I'm wiling to help with that as well.

**Comment by soltysh** [comment]
Linking this with #3016 as it's related.

**Comment by jhadvig** [comment]
+1 for doing this.

**Comment by mfojtik** [comment]
@csrwng it should also has more 'pipeline style' where you can easily plug in things like labels/annotations etc.

**Comment by jhadvig** [comment]
yeah, just adding envars only to the new-build cmd was a bit tricky ...

**Comment by bparees** [comment]
new-app has been repeatedly refactored and probably will continue to be refactored in the future, but i don't think it's worth carrying an issue.
