### ISSUE TITLE
build validation messages very hard to track to failing fields

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3216]
Creating a `Build` object by hand, I'm getting 

```
unexpected error: Build in version v1 cannot be handled as a Build: ImageStreamTag object references must be in the form <name>:<tag>: 
```

I suspect this is failing validation on the `from` field of the `stiStrategy`, but I'm not informed of that.

**Comment by smarterclayton** [comment]
I think the conversion is failing - conversion should probably not error on things it doesn't recognize, and make validation handle those cases (conversion defaults and transforms only, passes errors through, validation validates)
