### ISSUE TITLE
add `whatcanido` endpoint

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3220]
I want to know what I have rights to do in a project, but viewers don't have sufficient information to inspect their bindings and roles directly.  The information is available given sufficient SARs, but that is cumbersome and slow.

Adding a `users/username/whatcanido` that accepts json including a namespace will allow us to create an `oc policy whatcanido` command that can provide the rules that a user has in a particular project.  Passing namespace="" would check for rules provided by `clusterrolebindings`.

@liggitt @smarterclayton @derekwaynecarr thoughts?

**Comment by smarterclayton** [comment]
An interesting concept.  The name is terrible.

**Comment by liggitt** [comment]
> The name is terrible.

I know, but whatcanyoudo?

**Comment by derekwaynecarr** [comment]
I agree the name is horrible.... maybe this could just appear in a ```osc describe project``` output?

**Comment by liggitt** [comment]
For "simple" policy this seems useful. The more sophisticated our rules get (field level, or code driven, etc) I'm not sure how much sense the response will make to a client

**Comment by deads2k** [comment]
> maybe this could just appear in a osc describe project output?

The command or the endpoint?  A servers-side endpoint needs to exist, because efficiently determining access rights requires an escalation for most users.  They don't have rights to see the rolebindings in projects because that would give them additional knowledge of the organization.

**Comment by deads2k** [comment]
Closing in favor of https://trello.com/c/YqfYqKdS/545-policy-related-endpoints-need-work
