### ISSUE TITLE
canary check error message is vague

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#3222]
I'm getting a log message that's not too useful when my deployment fails:

```
# oc logs docker-registry-1-deploy
I0616 10:17:15.483846       1 deployer.go:171] No last completed deployment found
F0616 10:19:16.634310       1 deployer.go:63] timed out waiting for the condition
# oc scale dc/docker-registry --replicas=1                                                                                                                                                          
error: timed out waiting for the condition
```

This is on OSE 3 (0.6.1 -- RC2). I don't know why the deployment failed, but that's possibly a separate issue. There was no actual pod created, aside from the deployer. Current issue is this error doesn't help me figure out what's going on :)  Here's the command for creating the registry:

```
oadm registry --create --credentials=/etc/openshift/master/openshift-registry.kubeconfig --replicas=2 --mount-host=/mnt/registry                       
```

also `/mnt/registry` is present on all hosts, nfs mounted.

@ironcladlou

**Comment by ironcladlou** [comment]
I'm still triaging this one... the deployer output here doesn't seem to align with what's actually in the codebase or what you get if you run deployments with origin master.

**Comment by ironcladlou** [comment]
The output from origin looks like:

```
I0612 21:46:33.246952       1 deployer.go:171] No last completed deployment found
I0612 21:46:43.569894       1 recreate.go:110] Validating first replica of deploytester-2
I0612 21:46:45.638868       1 lifecycle.go:280] Waiting for pod test/deploytester-2-bxnfe container readiness
F0612 21:47:05.639331       1 deployer.go:63] First replica rejected for deploytester-2: timed out waiting for the condition
E0612 21:47:05.639333       1 reflector.go:168] watch of *api.Pod ended with: Stop requested
```

**Comment by ironcladlou** [comment]
Looks like the deployer image lacks #2892, which explains all the output.

**Comment by sosiouxme** [comment]
Worth mentioning that my original invocation lacked the correct `--images` flag.

```
oadm registry --create --credentials=/etc/openshift/master/openshift-registry.kubeconfig --images='docker-buildvm-rhose.usersys.redhat.com:5000/openshift3/ose-${component}:${version}' --replicas=2 --mount-host=/mnt/registry
```

It runs properly if I don't include the `--mount-host` flag. It times out as in the original report if I do. Is there some condition checking whether that directory is available on hosts or something before even attempting the pod placement?

**Comment by ironcladlou** [comment]
Okay, so I finally realized the registry DC is using the Recreate strategy instead of Rolling, which skips the canary checking, which leads to the vague error during the failure to scale up the deployment. The recreate strategy should emit a more useful log, but separately, the registry should be using the Rolling strategy. cc @pweil-

**Comment by liggitt** [comment]
> separately, the registry should be using the Rolling strategy. cc @pweil-

Same for the router, I think. Opened https://github.com/openshift/origin/pull/3239

**Comment by sosiouxme** [comment]
The actual problem (visible on the RC events, not the DC or status) was that --mount-host requires privileged access and the relevant service account didn't have it. Opened https://github.com/openshift/origin/issues/3244
