### ISSUE TITLE
Failure to deploy router & registry in 0.6.1

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#3226]
Running

    oadm router --create --credentials=/var/lib/openshift/openshift.local.config/master/openshift-router.kubeconfig

Deployer pods have the following error:

```
E0616 11:44:12.687586       1 clientcmd.go:128] Error reading BEARER_TOKEN_FILE "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
E0616 11:44:12.701880       1 clientcmd.go:146] Error reading BEARER_TOKEN_FILE "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
F0616 11:44:12.758851       1 deployer.go:63] couldn't get deployment default/router-1: User "system:anonymous" cannot get replicationcontrollers in project "default"
```

**Comment by liggitt** [comment]
What OS and docker version are you running?

**Comment by jimmidyson** [comment]
```
$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 8aae715/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 8aae715/1.6.0
OS/Arch (server): linux/amd64
```

```
$ cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core)
```

**Comment by liggitt** [comment]
There's a bug in the centos and rhel distributions of docker that is shadowing /var/run/secrets. You need docker 1.6.2-8+. Relevant issues:

centos: https://github.com/openshift/origin/issues/3093#issuecomment-111194195

rhel: https://github.com/openshift/origin/issues/2918#issuecomment-110585298

**Comment by jimmidyson** [comment]
Thanks @liggitt

**Comment by rawlingsj** [comment]
For info as far as I can tell the latest version of docker available to RHEL is docker-1.6.2-6.el7.x86_64 and this doesn't work..

```
[root@demo6 ~]# docker logs a2ecc0f53483
E0616 16:30:50.418720       1 clientcmd.go:128] Error reading BEARER_TOKEN_FILE "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
E0616 16:30:50.419339       1 clientcmd.go:146] Error reading BEARER_TOKEN_FILE "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
F0616 16:30:50.567965       1 deployer.go:63] couldn't get deployment default/docker-registry-1: User "system:anonymous" cannot get replicationcontrollers in project "default"
[root@demo6 ~]# docker version
Client version: 1.6.2.el7
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): f1561f6/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2.el7
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): f1561f6/1.6.2
OS/Arch (server): linux/amd64
[root@demo6 ~]# rpm -q docker
docker-1.6.2-6.el7.x86_64
[root@demo6 ~]#
```

**Comment by liggitt** [comment]
Correct, it is fixed in 1.6.2-8+. I'm not sure when that version will hit general repos.

**Comment by rawlingsj** [comment]
@jimmidyson did you mention you had joy with Centos earlier?  I must admit I'm struggling.  

I've tried on RHEL, Centos and Fedora. I guess either I'm doing something wrong or the 0.6.1 release wont work on Linux yet because none of the distributions I used have 1.6.2-8+ of docker available?

I'm only fairly familiar with Linux so maybe there's another way to install the right version of docker to run the router and registry?

**Comment by liggitt** [comment]
@rawlingsj I may have misspoken... docker 1.6.2-8+ on RHEL fixes the masking issue. @ncdc said he saw the mounting issue fixed on centos with docker 1.6.2-3 (he installed a build directly from http://cbs.centos.org/koji/packageinfo?packageID=30 since the official repos hadn't been updated yet)

**Comment by jimmidyson** [comment]
@rawlingsj I did exactly what @ncdc suggested, using rpm from that koji build, & it worked fine. You can see it in the fabric8 Vagrantfile.

**Comment by rawlingsj** [comment]
Thanks @liggitt and @jimmidyson it's working after getting the rpm from http://cbs.centos.org/koji/packageinfo?packageID=30
