### ISSUE TITLE
Custom builder output definition

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#3231]
Allow specifying other output artifacts (eg. URL) in Build's output structure. Currently we only support  

* DockerImage
* ImageStreamTag
* ImageStream

/fyi @bparees

**Comment by liggitt** [comment]
Be careful introducing new output kinds here... needs coordination with clients interpreting output values

**Comment by bparees** [comment]
I'm going to close this, you can specify any output parameter you want via an env variable that the custom build can respect.  Going beyond that feels like a rat-hole.  @soltysh feel free to reopen with counter-arguments.
