### ISSUE TITLE
deployments created against tag with no image

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3234]
I ran `oc new-app` and got resources that look like this: https://gist.github.com/deads2k/97bcb89212c5c13c3066.  They created a imagestream tag with no backing image for an image stream that does not have `dockerImageRepository` set.
```
[deads@deads-dev-01 openshift-docs]$ oc describe is/docker-nfs-server
Name:			docker-nfs-server
Created:		About an hour ago
Labels:			<none>
Docker Pull Spec:	<none>

Tag	Spec					Created			PullSpec				Image
latest	library/docker-nfs-server:latest	About an hour ago	library/docker-nfs-server:latest	
```

Deployments are still attempted and fail with 
```
Failed to pull image "library/docker-nfs-server:latest": Error: image library/docker-nfs-server:latest not found
```

Deployments shouldn't be triggered if there is no image to use for the pull.

@ironcladlou @ncdc

**Comment by ncdc** [comment]
It is valid to have a status.tags entry with no image. You can get this via `oc tag foo/bar:baz mystream:latest`. `foo/bar:baz` may exist, or not. Either way, you'd see output similar to what you have in your gist.

Unless we modify OpenShift to predetermine if an image exists and only trigger a deployment if it does, I don't see this as actionable.

**Comment by deads2k** [comment]
> Unless we modify OpenShift to predetermine if an image exists and only trigger a deployment if it does

That doesn't seem entirely unreasonable as long as we'll get re-notified if the image is suddenly available.  Will we?

**Comment by ncdc** [comment]
Not necessarily. If you rerun `oc tag`, it's not doing an import, so in this scenario the TagEvent's DockerImageReference would stay the same (foo/bar:baz) and the Image would too (""), so you'd be in the same situation - we'd have to query the external registry for the existence of the tag.

**Comment by deads2k** [comment]
Alright.  I'll wait for this until after my mind reading typewriter.
