### ISSUE TITLE
missing docker registry makes very noisy logs

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3235]
I forgot to run `oadm registry` and I tried to start a build.  That produces a repeating message in my log that drowns out everything.  Can we rate-limit the log message?

```
E0616 17:30:15.823292       1 factory.go:35] Build failed with error nfs/docker-nfs-server-2: the ImageStream nfs/docker-nfs-server cannot be used as the output for Build nfs/docker-nfs-server-2 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry
E0616 17:30:16.784478       1 factory.go:35] Build failed with error nfs/docker-nfs-server-2: the ImageStream nfs/docker-nfs-server cannot be used as the output for Build nfs/docker-nfs-server-2 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry
E0616 17:30:17.784262       1 factory.go:35] Build failed with error nfs/docker-nfs-server-2: the ImageStream nfs/docker-nfs-server cannot be used as the output for Build nfs/docker-nfs-server-2 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry
E0616 17:30:18.784395       1 factory.go:35] Build failed with error nfs/docker-nfs-server-2: the ImageStream nfs/docker-nfs-server cannot be used as the output for Build nfs/docker-nfs-server-2 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry
E0616 17:30:19.785514       1 factory.go:35] Build failed with error nfs/docker-nfs-server-2: the ImageStream nfs/docker-nfs-server cannot be used as the output for Build nfs/docker-nfs-server-2 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry
E0616 17:30:20.783200       1 factory.go:35] Build failed with error nfs/docker-nfs-server-2: the ImageStream nfs/docker-nfs-server cannot be used as the output for Build nfs/docker-nfs-server-2 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry
E0616 17:30:21.784540       1 factory.go:35] Build failed with error nfs/docker-nfs-server-2: the ImageStream nfs/docker-nfs-server cannot be used as the output for Build nfs/docker-nfs-server-2 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry
E0616 17:30:22.783397       1 factory.go:35] Build failed with error nfs/docker-nfs-server-2: the ImageStream nfs/docker-nfs-server cannot be used as the output for Build nfs/docker-nfs-server-2 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry
E0616 17:30:23.784306       1 factory.go:35] Build failed with error nfs/docker-nfs-server-2: the ImageStream nfs/docker-nfs-server cannot be used as the output for Build nfs/docker-nfs-server-2 because the integrated Docker registry is not configured, or the user forgot to set a valid external registry
```

@bparees

**Comment by bparees** [comment]
it is rate limited. once per second.

**Comment by bparees** [comment]
that is our retry behavior.

**Comment by deads2k** [comment]
I don't mind retrying every second, but can you limit the logging separately?  Once per second seems rather heavy.

**Comment by bparees** [comment]
@deads2k are you opening a separate issue for the secrets problem?

**Comment by deads2k** [comment]
> @deads2k are you opening a separate issue for the secrets problem?

Yes.

**Comment by bparees** [comment]
As part of fixing this we should manifest the error on the build object itself, as an Event, so user's can see what has gone wrong.

**Comment by deads2k** [comment]
> As part of fixing this we should manifest the error on the build object itself, as an Event, so user's can see what has gone wrong.

Yes please.

**Comment by deads2k** [comment]
@bparees  Thinking about this a little more,  why would we ever want to create a build for a buildConfig that wants to push to an image stream that doesn't have sufficient information to push to?  It seems like you'd want that to not create a build and you can listen for changes to the internal docker registry to know when its available and to the image stream to know when it's updated to be valid.

**Comment by bparees** [comment]
@deads2k it's no different than how we create pods today that can't pull their image because it doesn't exist.

**Comment by liggitt** [comment]
but will a build ever resolve it's output after it is created?

**Comment by bparees** [comment]
@liggitt because we resolve the output when we transition the build from new to pending.

**Comment by deads2k** [comment]
> @deads2k it's no different than how we create pods today that can't pull their image because it doesn't exist

It's a little different.  We may not be notified that a pod's image is suddenly available, but we can unambiguously determine "insufficient information" from "sufficient information" for a push target.

**Comment by bparees** [comment]
@deads2k we have to create the build.  if you tell me "build commit 1" then i need to create a build that represents that desire.  that is the build object.  I can't hang onto "hey david wanted to build commit 1" somewhere else and queue up some wait for the rest of the necessary conditions to exist.  the build object *is* that queue.

**Comment by bparees** [comment]
builds have more specific information about what to build than a buildconfig.

**Comment by liggitt** [comment]
I misunderstood when the output resolution happened... I thought it happened at build create time

**Comment by bparees** [comment]
@liggitt that's because you understood the way it should work and not the way it does work. :)

**Comment by bparees** [comment]
@liggitt this is how we got into your "the build output changed on me" issue.

**Comment by bparees** [comment]
this should actually already be better because we now only log the last failure, not every retry failure.

but i'm still going to make it an event too.
