### ISSUE TITLE
builder: Fallback branch in _get_build_version() has issues

### ISSUE THREAD

**Issue by mbarnes** [openshift/origin#3236]
Working on a repo that has no build tags, I ran into some issues with #1309.

See the fallback logic in `_get_build_version()` here:
https://github.com/openshift/origin/pull/1309/files#diff-b02a766e988e8037828b5f98bc9cbc71R57

The file is missing
````
import sys
from tito.common import get_spec_version_and_release
````

But more importantly it calls a function named `find_spec_file()` which, as far as I can tell, doesn't exist.  Did that get omitted accidentally in the merge?

**Comment by sdodson** [comment]
find_spec_file() seems to be in tito.common too, so just include that too, right?

https://github.com/dgoodwin/tito/blob/master/src/tito/common.py#L315

**Comment by mbarnes** [comment]
Oh yeah, you're right.  Then this is trivial.
