### ISSUE TITLE
oc status should tell me that my build pipeline won't work

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3243]
`oc status` should let me know if I have a pipeline that relies pushes to an imagestream that requires the internal docker registry, but the internal docker registry is not present.

**Comment by liggitt** [comment]
Is that condition discernible from the image stream API object? I'm not sure if the presence of the internal registry is detectable to typical API clients

**Comment by deads2k** [comment]
I just started talking about that with @ncdc and @smarterclayton  on IRC.  I don't think it is, but I do think its useful to know, so there should either be a guaranteed location or an API to get at it.

**Comment by smarterclayton** [comment]
Yes, 'status.dockerImageRepository' is empty.

**Comment by deads2k** [comment]
It's a question of knowing if the internal docker registry is present.  To my knowledge, the only way to know this is to guess at the namespace containing the docker registry.

**Comment by liggitt** [comment]
the typical user will not have access to the `default` namespace to go searching for services. Is `status.dockerImageRegistry` absence sufficient?

**Comment by ncdc** [comment]
As of right now, yes

**Comment by smarterclayton** [comment]
We'll always have that for things that have to be exposed.

----- Original Message -----
