### ISSUE TITLE
Registry deploy should use a service account that has privileged access

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#3244]
When deploying a registry with `oadm registry --mount-host` by default the deployment fails because mounting a host volume is privileged access and the service account doing the deploy doesn't have it.

Either we should add `system:serviceaccount:default:default` to the SCC privileged users or there should be another service account that's there by default that has this access. `oadm registry` should probably default to using said service account if it's not `default`.

Even better might be an option on `oadm registry` for mounting an NFS volume (which is what we probably really want anyway). You have to do that via `oc edit` if you want it now and I don't look forward to documenting it.

**Comment by liggitt** [comment]
I definitely don't think the default service account in the default namespace should be highly privileged.  I think it's too easy for a cluster admin to run pods under that service account without realizing they've done it (double defaults, both namespace, default service account )

**Comment by liggitt** [comment]
Do the volume commands not let you add an NFS volume mount?

**Comment by sosiouxme** [comment]
They would probably, except I don't think they're merged yet?

**Comment by pweil-** [comment]
As discussed on the bug scrub call, we will provide documentation for how to use a privileged SCC with the registry to enable folks to use host mounts.  Enabling this by default is not the recommended approach.

**Comment by pweil-** [comment]
Documentation provided in https://github.com/openshift/openshift-docs/pull/526.

**Comment by sosiouxme** [comment]
Thanks!
