### ISSUE TITLE
Provide a way to know why a build was kicked off

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#3245]
There is no easy way to know why a build was triggered. Could have been config change, webhook, manual or ??? Also be nice to know who cause it.

Would be good to have in:
 * `oc status`
 * `oc get|describe build bid`
 * web overview
 * web build details

See somewhat related issue #387

**Comment by sspeiche** [comment]
A few other suggestions for improvements in this space:
 * expose which "ref" is used for the build, currently the console only shows Git URL
 * include in the build resource, the last Git commit id.  Currently I'm not sure how to know what is in what was pulled (believe only manual builds have this problem)

**Comment by liggitt** [comment]
builds triggered by webhooks which provide commit info already log commit id, author, message, etc (and the UI surfaces that)

**Comment by bparees** [comment]
trello'd https://trello.com/c/wozDHSJ2/717-track-reason-a-build-was-run
