### ISSUE TITLE
Invalid service protocol field generated in web console

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#3253]
Reported by @oybed:

*Creating the application using the osc command (osc new-app) generates the service with uppercase TCP. However, using the web console generates lowercase "tcp".*

Web console should uppercase this.

@liggitt @smarterclayton

**Comment by liggitt** [comment]
Surprised there's not validation at create time for that

**Comment by smarterclayton** [comment]
Seems like a bug in the validation code
