### ISSUE TITLE
Web console Regression on formatting names with spaces

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#3260]
Project names with spaces now show a \ before the space. This wasn't happening before. 

Screen shot here

http://ibin.co/25Vhh4jcAmtJ

**Comment by spadgett** [comment]
I'm not seeing it. How did you create the project?

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8206720/0ca40bf6-14ca-11e5-97fe-7002adb34df6.png)

**Comment by thesteve0** [comment]
@jhonce actually created the project so it would be better to ask him

**Comment by thesteve0** [comment]
@jwhonce  can you respond to this one?

**Comment by jwhonce** [comment]
@spadgett @thesteve0 I'll fix this in the next virtualbox I deliver.
