### ISSUE TITLE
support Jenkins (or other CI tools) as a strategy for BuildConfig / BuildStrategy

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#3261]
due to the [lack of pipelines in OpenShift](https://github.com/openshift/origin/issues/1228) to chain together builds / tests / approvals we ended up using Jenkins for our [Fabric8 CI / CD solution](http://fabric8.io/guide/cdelivery.html) on OpenShift.

TL;DR; we use the Jenkins Job DSL to auto-generate Jenkins CI jobs and CD pipelines for each git repo in gogs/github/gitlab. For each git repo we generate an OpenShift `BuildConfig` which points to the git repo; we also annotate the BuildConfig to link to jenkins jobs, pipeline views, monitor views, team page, issue tracker, chat room, gerrit code reviews etc. Then the [hawtio-kubernetes](https://github.com/hawtio/hawtio-kubernetes) UI for kubernetes has buttons on the Build Configs page to easily link to the pipeline views, team page, issue tracker, code review and chat room etc.

The thing is though; OpenShift doesn't know how to trigger this build. If folks have a mixture of Jenkins builds and OpenShift STI builds; the BuildConfig view isn't quite consistent; you can't yet trigger a jenkins build from the OpenShift Build Configs view.

Now we could hack it and make Jenkins builds be a CustomBuildStrategy and have a standard docker build which just triggers the webhook of the jenkins build.

Though it feels like a neater solution would be to add a new kind of Strategy for delegating to Jenkins (or any CI / build system). For now lets call it `ServiceBuildStrategy` (as it delegates to another Service in kubernetes to do the build; could be Jenkins/Bamboo/Gocd/whatever). i.e. delegating to a Kubernetes Service to perform the build. 

Then the JSON for the ServiceBuildStrategy would configure:

* which kubernetes service performs the build via an ObjectReference (e.g. a particular distro of Jenkins or Bamboo) which could be running internally inside OpenShift as an internal Service or could be an [external service](http://docs.openshift.org/latest/dev_guide/integrating_external_services.html)
* which URI path within the service is used to view the builds
* which webhook URL is used to trigger the build

Then the trigger mechanism in OpenShift could trigger builds inside Jenkins / Bamboo and the metadata for BuildConfig is accurate and includes all possible kinds of builds; which then helps tooling and UIs to better integrate things together

**Comment by smarterclayton** [comment]
In progress, closing since we have basic agreement
