### ISSUE TITLE
Name input is missing red border when in error state.

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#3264]
![form-error-bug](https://cloud.githubusercontent.com/assets/1874151/8209060/e981e04e-14d8-11e5-9373-303dd8f3ac7d.png)

**Comment by liggitt** [comment]
I don't like the help text jumping when the error shows if it is directly below

**Comment by sg00dwin** [comment]
This was fixed with https://github.com/openshift/origin/commit/318d414ef2bb5d49d9d014a7f4917a578180b1d4
verified
