### ISSUE TITLE
Make use of (and secure) nodePort type services

### ISSUE THREAD

**Issue by eparis** [openshift/origin#3268]
kubernetes 1.0 removed publicIPs and shifted how the external->internal connectivity works.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#type--nodeport

All services now have a type and the closest approximation to the usable of publicIP is a service of type nodePort. A nodePort type service will be given a port on all nodes in the kubernetes cluster. Similar to listing the ip address of every node in the cluster in the old publicIPs list.

This can greatly simplify the 'enterprise router' setup and usage. As the enterprise router can be turned into a normal service+rc. The service will need to be of type nodePort and it will need to explicitly claim ports 80 and 443 (serviceSpec.ports[i].nodePort). Now the enterprise router can be dynamically scaled inside the cluster and ANY clusterIP will be able to respond! Weee.

But this also means that any user will be able to 'claim' low ports on every node. Which is likely not a good thing. I would suggest an openshift security policy that prevents non cluster admins from creating services which claim ports < 32k. OpenShift may prefer a policy that outright rejects all usage of services of type nodePort. But that is a security discussion that should happen.

**Comment by smarterclayton** [comment]
Probably need to enable an admission controller that can check policy for this.

**Comment by smarterclayton** [comment]
We could have the "simple" router mode that supports this, then a more complex mode where you have multiple routers.

**Comment by pweil-** [comment]
subscribed

**Comment by ncdc** [comment]
There's a button for that :tongue:

**Comment by eparis** [comment]
There is, but I think the e-mail headers are different if you just click the button vs actually participate...

**Comment by pweil-** [comment]
@ncdc I used both :-)  I figured I'd get tagged anyway so I wanted to make my presence known

**Comment by smarterclayton** [comment]
You can click the button twice, then it's as if you commented.  Explicit subscribe is different than implicit subscribe.

----- Original Message -----

**Comment by smarterclayton** [comment]
This won't fix routers for source ips until the kube-proxy moves to iptablea only
