### ISSUE TITLE
Create From Template -  JBoss icon is outdated

### ISSUE THREAD

**Issue by rettori** [openshift/origin#3270]
JBoss logo is outdated.
![screen shot 2015-06-17 at 10 16 38 am](https://cloud.githubusercontent.com/assets/2352755/8211054/fc25990c-14e2-11e5-907d-6b3b68b8a824.png)

**Comment by liggitt** [comment]
logo font needs an update, moving to steve

**Comment by sg00dwin** [comment]
Updated to the latest JBoss logo, https://engineering.redhat.com/pnt/p-559254/Logotype_RHJB...RGB_Black.png

This presents another issue, in the UI there are are locations where the logos are displayed at a 30x30 pixel size. In this case the new JBoss logo is unreadable. see screenshot.

**Comment by jwforres** [comment]
@rettori please see @sg00dwin's last comment about the logo size.  Is there a different logo we should be using for smaller sizes?

**Comment by smarterclayton** [comment]
Closing due to age.
