### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by maxandersen** [openshift/origin#3294]
Did this:

```
git clone https://github.com/openshift/origin.git
cd origin
export OPENSHIFT_DEV_CLUSTER=true
export OPENSHIFT_NUM_MINIONS=1
vagrant up
```

After a while I end up with:

```
==> minion-1: _output/local/go/src/github.com/openshift/origin/pkg/cmd/util/flags/flags.go:6: import /vagrant/Godeps/_workspace/pkg/linux_amd64/github.com/spf13/pflag.a: object is [linux amd64 go1.3.3 X:precisestack] expected [linux amd64 go1.4.2 X:precisestack]
==> minion-1: # github.com/mesos/mesos-go/mesosutil
==> minion-1: Godeps/_workspace/src/github.com/mesos/mesos-go/mesosutil/node.go:7: import /vagrant/Godeps/_workspace/pkg/linux_amd64/github.com/golang/glog.a: object is [linux amd64 go1.3.3 X:precisestack] expected [linux amd64 go1.4.2 X:precisestack]
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by liggitt** [comment]
You seem to have an image with go 1.3. Is it possible you have an older vagrant image you need to delete and re pull the latest?

**Comment by maxandersen** [comment]
this was from a fully clean vagrant install afaik.

Is there a command to ensure I have the latest update ?

`vagrant box update` gives:

`==> openshiftdev: Checking for updates to 'fedora_inst'
    openshiftdev: Latest installed version: 0
    openshiftdev: Version constraints:
    openshiftdev: Provider: virtualbox
The box 'fedora_inst' is not a versioned box. The box was added
directly instead of from a box catalog. Vagrant can only
check the versions of boxes that were added from a catalog
such as from the public Vagrant Server.`

**Comment by maxandersen** [comment]
running `vagrant destroy; vagrant up` to try with fully clean slate.

was hoping there was a less timeconsuming option to get latest dependencies.

**Comment by maxandersen** [comment]
running `vagrant destroy` (having delete all images) this still fails with same error. ;/

**Comment by maxandersen** [comment]
okey so I've now done:

```
rm -rf .vagrant
vagrant destroy
vagrant box remove fedora_inst
vagrant box remove fedora_deps
vagrant up
```

Now getting: 

````
==> master: _output/local/go/src/github.com/openshift/origin/pkg/cmd/util/flags/flags.go:6: import /vagrant/Godeps/_workspace/pkg/linux_amd64/github.com/spf13/pflag.a: object is [linux amd64 go1.3.3 X:precisestack] expected [linux amd64 go1.4.2 X:precisestack]
==> master: # github.com/mesos/mesos-go/mesosutil
==> master: Godeps/_workspace/src/github.com/mesos/mesos-go/mesosutil/node.go:7: import /vagrant/Godeps/_workspace/pkg/linux_amd64/github.com/golang/glog.a: object is [linux amd64 go1.3.3 X:precisestack] expected [linux amd64 go1.4.2 X:precisestack]
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
````

**Comment by maxandersen** [comment]
in comparison this guide just works: http://fabric8.io/guide/openShiftWithFabric8Vagrant.html

```
git clone https://github.com/fabric8io/fabric8-installer.git
cd fabric8-installer/vagrant/openshift-latest
vagrant up
```

So I highly suspect there is something not working with openshift's own vagrant setup out-of-the-box.

**Comment by kargakis** [comment]
What version of Go are you using?

**Comment by mfojtik** [comment]
also are you mounting the sources from you host machine? if so, I would suggest to make clean before you start vagrant to avoid Go version mismatch.

**Comment by thesteve0** [comment]
I have also found you should do:

vagrant box remove <your box> --force

**Comment by maxandersen** [comment]
i'm not using anything besides what is in the latest git repo of openshift.
I just run vagrant up. Nothing else. No magic mounting or whatnot. The commands I show in initial comment is what I do.

It should not be using *any* thing from my machine besides what is in the git repo.

As stated above it works fine when I use fabric8 vagrant setup.

**Comment by kargakis** [comment]
Make sure you are using go1.4.2

**Comment by maxandersen** [comment]
@kargakis where in this am I supposed to have any control over what go version the *vagrant* image is using ?

Does the vagrant image require specific version of go on my machine for running the vm's with openshift on it ?

If there are other requirements than installing vagrant - could we get that documented ?

**Comment by bparees** [comment]
@thesteve0 @jwhonce are you the guys who own this vagrant image?

**Comment by maxandersen** [comment]
so i'm back trying this - I haven't changed anything on my side afaik and now it works.

at least I have a very limited barebones origin running now.
