### ISSUE TITLE
Can't deploy jenkins with origin

### ISSUE THREAD

**Issue by xjvs** [openshift/origin#3303]
jenkins container boot up and exit with error:

    /usr/local/bin/jenkins.sh: line 25: /var/log/copy_reference_file.log: Permission denied

env (RHEL7 x86_64):

1. openshift: latest version

    ```
    $ oc version
    oc v0.6.2-4-g9e9c467-dirty
    kubernetes v0.17.1-804-g496be63
    ```

2. docker: happens with both upstream 1.6.0 and RHEL's 1.6.2

    ```
    $ docker version
    Client version: 1.6.0
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 4749651
    OS/Arch (client): linux/amd64
    Server version: 1.6.0
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): 4749651
    OS/Arch (server): linux/amd64
    ```

3. jenkins container:

    * with offical jenkins container, error:

            /usr/local/bin/jenkins.sh: line 25: /var/log/copy_reference_file.log: Permission denied

    * with openshift/jenkins-1-centos, error:

            Running from: /usr/lib/jenkins/jenkins.war
            webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
            Jun 18, 2015 6:15:40 AM winstone.Logger logInternal
            INFO: Beginning extraction from war file
            Jun 18, 2015 6:15:40 AM winstone.Logger logInternal
            INFO: Winstone shutdown successfully
            Jun 18, 2015 6:15:40 AM winstone.Logger logInternal
            SEVERE: Container startup failed
            java.io.FileNotFoundException: /var/jenkins_home/war/META-INF/MANIFEST.MF (No such file or directory)
                    at java.io.FileOutputStream.open(Native Method)
                    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
                    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
                    at winstone.HostConfiguration.getWebRoot(HostConfiguration.java:280)
                    at winstone.HostConfiguration.<init>(HostConfiguration.java:83)
                    at winstone.HostGroup.initHost(HostGroup.java:66)
                    at winstone.HostGroup.<init>(HostGroup.java:45)
                    at winstone.Launcher.<init>(Launcher.java:143)
                    at winstone.Launcher.main(Launcher.java:354)
                    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                    at java.lang.reflect.Method.invoke(Method.java:606)
                    at Main._main(Main.java:293)
                    at Main.main(Main.java:98)

There is no issue with both:

    docker run -it --rm jenkins

and 

    docker run -it --rm openshift/jenkins-1-centos

So I think it could be something wrong with OpenShift.

Please check the template and inspect info at: http://www.fpaste.org/233464/

**Comment by mfojtik** [comment]
@xjvs the permission denied error is because OpenShift now runs containers with random user UI. You have to make sure that the folder is writeable by any user...

**Comment by xjvs** [comment]
@mfojtik hi, do you mean that even the image has

    "User": "jenkins"

in ENV, openshift will run  the container with a random user rather than 'jenkins'?

If that's true, it doesn't make sense at all, since many images are built with a particular user (with related dir permissions, ...) setup and run the entrypoint scripts with that user, if OpenShift run it with a random user, many app containers can be broken to work without change for OpenShift.

**Comment by mfojtik** [comment]
@smarterclayton ^^

**Comment by mfojtik** [comment]
@xjvs I think there is a way how to run the image as the user defined in Dockerfile, it is just not 'default'.

**Comment by liggitt** [comment]
Allowing docker images to run with particular named users has security implications, so it is not allowed by default. @pweil- has a doc describing how to allow pods to run as any non root user, rather than getting allocated a random uid

**Comment by xjvs** [comment]
Hi, could you point me where the doc is?

**Comment by liggitt** [comment]
http://docs.openshift.org/latest/admin_guide/manage_scc.html#how-do-i

Find the "Enable Images to Run With USER in the Dockerfile" section

**Comment by liggitt** [comment]
@pweil- would `RunAsNonRoot` work as well in that section?

**Comment by smarterclayton** [comment]
Also we should probably have a non-privileged SCC that they can edit that uses the project selinux label but allows run as user.  Labels and privileged aren't really the problem here.

Also, we may want to grant access to raw sockets by default in the container.

----- Original Message -----

**Comment by xjvs** [comment]
Thanks, `MustRunAsNonRoot` (and `RunAsAny` of course) works for me.

**Comment by pweil-** [comment]
Sorry, was out on Friday.  Looks like this is taken care of.  

> Also we should probably have a non-privileged SCC that they can edit that uses the project selinux label but allows run as user.  Labels and privileged aren't really the problem here.

The restricted strategy fits this profile by changing the user strategy and leaving the SELinux strategy.

**Comment by smarterclayton** [comment]
Anything left on this?  Reopen if there is!

**Comment by bparees** [comment]
we also now have a jenkins image designed to run on openshift (can run as any user):
https://github.com/openshift/jenkins
