### ISSUE TITLE
define service host environment variables to point to DNS rather than IP addresses?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#3304]
due to cert validation rules, pods can't talk to the service portalIP addresses unless they disable all cert trust; which is kinda dodgy and a security nightmare. One fix to this is to add the service IP addresses to the certs when they are created.

So in general its going to be better to use DNS names, like `foo.default.svc.cluster.local` from a container to talk to the `foo` service rather than the portalIP address. 

The problem is its hard for a container to know the DNS suffix (e.g. `.default.svc.cluster.local`). 

So why not use the DNS names as the environment variables for `$FOO_SERVICE_HOST`?

Or define an environment variable name for each service; `$FOO_SERVICE` or something so at least code can discover how to talk to services via DNS names without having to disable cert trusting?

**Comment by jimmidyson** [comment]
Alternatively, as the service IP for `kubernetes` is fixed to <PORTAL_NET>.1 (see https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go#L312) couldn't we just add that IP into the server cert as a subject alt name? That would make the `KUBERNETES_SERVICE_HOST` env var actually useful without having to disable cert validation.

@liggitt / @smarterclayton We discussed this on IRC a few days ago IIRC but not sure on your thoughts on it?

**Comment by liggitt** [comment]
I don't think we should be reinforcing pinned IP addresses for services... putting special IP addresses in the cert makes it harder for someone to bring their own server certs. I think having the DNS name in the service envvar makes more sense.

**Comment by jimmidyson** [comment]
Happy with that. Anything that means we don't have to disable cert auth is fine by me. Just need to get the CA cert mounted in pods by default too but that's a separate issue.

**Comment by jstrachan** [comment]
I guess to be fair, this issue only relates to the KUBERNETES_SERVICE_HOST environment variable (and the portalIP of kubernetes REST API itself); since the cert doesn't apply to any other services. 

So defining another environment variable seems over the top - just setting $KUBERNETES_SERVICE_HOST to the value of something like `kubernetes.default.svc.cluster.local` sounds like a good fix

**Comment by jimmidyson** [comment]
@liggitt 

> grudging [merge]

You could have told us ;)

**Comment by smarterclayton** [comment]
We should still have service hosts post to DNS - that's something I need to
track upstream

On Tue, Sep 1, 2015 at 6:07 PM, Jimmi Dyson <notifications@github.com>
wrote:

> @liggitt <https://github.com/liggitt>
>
> grudging [merge]
>
> You could have told us ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3304#issuecomment-136877854>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by jimmidyson** [comment]
Agreed.
