### ISSUE TITLE
Indicate source file(s) for `oc config` data

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#3306]
```
$ oc config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

The one thing this doesn't tell me is the one I want to know -- where is oc looking for its config (and obviously failing)?

Enhance `oc config view` to indicate what file config was loaded from, if any, or where it should have been if $KUBECONFIG is set to something that doesn't exist (the typical problem I run into). Bonus points for indicating the sequence of files checked (perhaps provide an option for this).

**Comment by fabianofranz** [comment]
`--loglevel=6` indicates where the config comes from.
