### ISSUE TITLE
cannot process template from a different project

### ISSUE THREAD

**Issue by bparees** [openshift/origin#3307]
I registered a project in the openshift project using cluster-admin

then as a normal user I tried to process the template:

    $ oc process rails-postgresql-example -n openshift

This results in an error:
    
    error processing the template "rails-postgresql-example": User "test-admin" cannot create processedtemplates in project "openshift"

Two problems:
1) it shouldn't be an error
2) the error text is wrong (process doesn't create anything, it just spits back the processed result)

I also tried:
    
    oc process openshift/rails-postgresql-example

which results in a different failure:

    Error from server: User "test-admin" cannot get templates/rails-postgresql-example in project "test"

**Comment by liggitt** [comment]
Why shouldn't it be an error? Even if process doesn't create anything, I could see it eventually making use of data in the target namespace to populate the result, so I don't think we should allow anyone to process a template against just any namespace.

**Comment by bparees** [comment]
@liggitt i'm not trying to process it "against" the namespace, i'm trying to process a template that exists in a different namespace and which i have view access to. 

Which we allow, it's what you do in the console when you create from a template.

There should be no other data in the target namespace involved, we just need to be able to fetch the template json so we can run it through process.

**Comment by smarterclayton** [comment]
We need a way to clearly select the source namespace on the cli to make this truly work.  Nontrivial.  Agree it's important.

**Comment by bparees** [comment]
Not sure why it's non-trivial.. the webconsole has already enabled pretty much exactly this flow.  fetch template, submit template for processing.  for the matter doesn't new-app also handle this?  or does new-app only work if the template is in your project?

**Comment by smarterclayton** [comment]
User on the cli has to identify source namespace and destination namespace.  I don't really want to have to add another flag - instead I think we might want to move towards namespace as part of the resource tuple (which we've been talking about for a while).

**Comment by liggitt** [comment]
>  I think we might want to move towards namespace as part of the resource tuple

if we do, please make it unambiguous... e.g. namespace tuples also have to include the type

**Comment by smarterclayton** [comment]
Which also means even more typing, which makes them harder to use.

**Comment by liggitt** [comment]
inconsistency (or worse, variable behavior depending on server state) destroys the ability to learn a group of commands

**Comment by smarterclayton** [comment]
I'm just not sure the syntax should be the same.  There are lots of cases where you want to deal with homogenous resources across namespaces, where having to add the type each time starts to become excessive.  I'm not disagreeing that it needs to be internally consistent to end users - i'm merely stating that the naive approach may not be the right one.

----- Original Message -----

**Comment by bparees** [comment]
@smarterclayton there is no destination namespace for process, there is only a source namespace for where the template comes from.  for which the syntax "<namespace>/<templatename>" seems logical to me.

**Comment by bparees** [comment]
@liggitt @smarterclayton process only comsumes templates, so template/namespace/templatename would be unnecesary here.

**Comment by liggitt** [comment]
> process only consumes templates

today

**Comment by fabianofranz** [comment]
+1 to @bparees in "there is no destination namespace for process", destination is always the current and source should support  "<namespace>/<templatename>". 

When the source namespace is "openshift" it should maybe even work without providing a namespace. So in `oc process rails-postgresql-example` look for `process rails-postgresql-example` in the current namespace first, then "openshift". I *think* new-app does exactly that if you do `oc process rails-postgresql-example`.

**Comment by tcastberg** [comment]
Hi guys, any chance we can get a milestone for this? I'm running into exactly this problem right now which only leaves two options, not using templates or import templates into every single project.

**Comment by smarterclayton** [comment]
@fabianofranz even a `--into` or `--from` would probably work. `--from-namespace` maybe, although that's pretty long.  How discoverable would that be?

**Comment by tcastberg** [comment]
@smarterclayton I actually have to say I like @fabianofranz last suggestion. It seems intuitive and corresponds to expectations. (It's the first thing I tried.) :)

**Comment by smarterclayton** [comment]
Hrm - process is supposed to be lower level than new-app.

On Thu, Aug 20, 2015 at 10:44 AM, Tor Magnus Castberg <
notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton> I actually have to
> say I like @fabianofranz <https://github.com/fabianofranz> last
> suggestion. It seems intuitive and corresponds to expectations. (It's the
> first thing I tried.) :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3307#issuecomment-133036956>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
this is also being tracked as a bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1253736
