### ISSUE TITLE
Deployment canary check isn't always performed

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3308]
When using the rolling strategy, canary checking will be performed:

* During initial deployment if the replica count is >1
* During a from/to transition if the from replica count is >0

When using the recreate strategy, canary checking will be performed:

* During initial deployment if the replica count is >1
* During a from/to transition if the to replica count is >0

Canary checking should happen for the first replica in all cases regardless of the desired replica count of "to" or the current replica count of "from".

The [strategy docs](http://docs.openshift.org/latest/dev_guide/deployments.html#strategies) will also need updated.

**Comment by abhgupta** [comment]
@ironcladlou clarified that this is specific to the "initial deployment". 

So, the current behavior is:
- on initial deployment - if replica count is 1, no canary check performed
- on initial deployment - if replica count is >1, canary check is performed
- if from/to transition (subsequent deployments), then then canary is ALWAYS performed regardless of replicas

Note: "Initial deployment" would be all deployments till a deployment succeeds. 

Based on the above, downgrading the priority.

**Comment by ironcladlou** [comment]
I opened #3312 to solve the most important cases in this issue, and spawned #3313 to cover the remaining issue with the rolling update scenario which is less common/severe.
