### ISSUE TITLE
Unexpected fatal error in image change controller for build

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3309]
This *looks* like we incorrectly failed on a conflict.  Instead, we should be retrying?  Either way, this error needs to either be a lot more specific, or properly handled.

--------------------------

https://app.getsentry.com/red-hat/openshift-3-stg/group/69260337/

```
controller.ImageChangeControllerFatalError: fatal error handling ImageStream change: error updating BuildConfig project01/eap-app with new LastTriggeredImageID, root error was: buildconfig "eap-app" cannot be updated: the resource was updated to 841729
  File "/builddir/build/BUILD/openshift-git-26.701be15/_build/src/github.com/openshift/origin/pkg/cmd/util/serviceability/sentry.go", line 57, in CaptureError
  File "/builddir/build/BUILD/openshift-git-26.701be15/_build/src/github.com/openshift/origin/pkg/cmd/util/serviceability/panic.go", line 28, in CaptureError.fm
  File "/builddir/build/BUILD/openshift-git-26.701be15/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go", line 82, in HandleError
  File "/builddir/build/BUILD/openshift-git-26.701be15/_build/src/github.com/openshift/origin/pkg/build/controller/factory/factory.go", line 235, in func.007
  File "/builddir/build/BUILD/openshift-git-26.701be15/_build/src/github.com/openshift/origin/pkg/controller/controller.go", line 131, in Retry
...
(6 additional frame(s) were not displayed)
```

**Comment by bparees** [comment]
i believe it's a fatal error because we assume someone else was updating it (possibly another master) and if it turns out we should have run, we eventually will on a sync loop when we see the lastimagetriggerid isn't current.

but we can try to improve the message.

**Comment by smarterclayton** [comment]
Hrm - so something that is only truly fixed by fixing the build pattern.  K

**Comment by bparees** [comment]
@coreydaley please see if you can track down where this error was being thrown from and make it a cleaner log message

**Comment by coreydaley** [comment]
@bparees will do

**Comment by coreydaley** [comment]
@smarterclayton @bparees Is there an example procedure to reproduce this error?
Are there more logs at https://app.getsentry.com/red-hat/openshift-3-stg/group/69260337/ that I can get access to?

**Comment by bparees** [comment]
@coreydaley i think what we should do here is consider adding retry logic around the update path, where we fetch the updated buildconfig resource and then try to re-apply the update.  @PI-Victor is doing something similar here:
https://github.com/openshift/origin/pull/10817/files#diff-23acc8ba296661971473ad53a2cc00ccR188

**Comment by coreydaley** [comment]
From what I have tracked down, it looks like between https://github.com/openshift/origin/blob/master/pkg/build/controller/factory/factory.go#L179 and https://github.com/openshift/origin/blob/master/pkg/build/controller/factory/factory.go#L309 it's basically just saying not to retry.  I'll work on re factoring to retry instead.

**Comment by bparees** [comment]
yeah, changing the type of error that gets bubbled up so it gets retried should work.

**Comment by coreydaley** [comment]
@bparees @smarterclayton 
Upon deeper review it looks like this is already fixed as there are not errors being referenced as ImageChangeControllerFatalError, and retry code is already present if an error is produced that is NOT a fatal error.
