### ISSUE TITLE
Request project is returning incorrect errors

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3310]
A few problems here:

1. We should never be returning a raw error in a REST handler - so we need to wrap the errors created in request project with the appropriate api/error
2. This looks like it's request project - but if we find the namespace already exists, we shouldn't be trying to create other things in the namespace (namespace creation should be atomic)
3. It's possible that if you race to create the namespace today you can add both people to the same project, which is a security issue.

--------------------

https://app.getsentry.com/red-hat/openshift-3-stg/group/69257459/

```
*errors.errorString: apiserver received an error that is not an api.Status: [namespaces "rails-demo" already exists, RoleBinding "admins" already exists, RoleBinding "image-pullers" already exists, RoleBinding "image-builders" already exists]
  File "/builddir/build/BUILD/openshift-git-26.701be15/_build/src/github.com/openshift/origin/pkg/cmd/util/serviceability/sentry.go", line 57, in CaptureError
  File "/builddir/build/BUILD/openshift-git-26.701be15/_build/src/github.com/openshift/origin/pkg/cmd/util/serviceability/panic.go", line 28, in CaptureError.fm
  File "/builddir/build/BUILD/openshift-git-26.701be15/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go", line 82, in HandleError
  File "/builddir/build/BUILD/openshift-git-26.701be15/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/errors.go", line 66, in errToAPIStatus
  File "/builddir/build/BUILD/openshift-git-26.701be15/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go", line 298, in errorJSON
...
(31 additional frame(s) were not displayed)
```

**Comment by smarterclayton** [comment]
Can you triage the impact of this real quick?

**Comment by deads2k** [comment]
> Can you triage the impact of this real quick?

The hole definitely exists.  But I'm not sure that I see the case where two people end up with the project.  One of those two people will win the race for creating the "admins" rolebinding.  The project displayname and description won't match, but one should win.

I see two easy fixes:
 1. all or nothing templates.  This would be really nice, but I think I'm probably dreaming.
 1. move the project creation itself out of the template.  Its kind of a shame, because it's really nice to be able to parameterize fields that live on the project (think annotations or labels), but it may be preferable to the security hole.

**Comment by smarterclayton** [comment]
Can you grab the project out of the template after you process it?

----- Original Message -----

**Comment by deads2k** [comment]
> Can you grab the project out of the template after you process it?

Grab it and compare against what was created to try to see if they match and return a failure otherwise?  What should I do if the project description/displayname doesn't match the admin user?  At this point, I wish I'd made the namespaces random and allowed stem matching on `oc project`.

**Comment by liggitt** [comment]
No, grab it, submit it individually. If you get an already exists error, return. Otherwise bulk process the rest of the list.

**Comment by deads2k** [comment]
> No, grab it, submit it individually. If you get an already exists error, return. Otherwise bulk process the rest of the list.

And if users want crazy things, like a single project request produces two projects in their template (completely possible)?  It's not guaranteed correct, but as long as everyone knows that I'm ok with it.

**Comment by liggitt** [comment]
I'm ok with that edge case

**Comment by liggitt** [comment]
which is a big deal, for me

**Comment by deads2k** [comment]
> which is a big deal, for me

I was a little surprised you proposed inspecting an opaque, user provided value.  I expected it from @smarterclayton , but not you. :)

**Comment by smarterclayton** [comment]
The point of this command is create a single project and items in it.  The template gives you the option of templatizing the project.  Any technique we use exists to serve "creating a project correctly", not "doing crazy things in a template".

**Comment by smarterclayton** [comment]
Also, the edge case missing here is that the template doesn't need to contain a project at all to be valid.
