### ISSUE TITLE
Problems mounting emptyDir and secrets volumes when SELinux is disabled

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#3314]
When SELinux is disabled (ie, completely disabled, not operating in permissive mode), emptyDir and other volumes backed by it cannot be mounted:

```
Unable to mount volumes for pod  ... expected 4 fields in selinuxcontext; got 1 (context: ); skipping pod
```

**Comment by smarterclayton** [comment]
Pretty significant for dev

**Comment by pmorie** [comment]
Yeah i am gonna fix asap.
