### ISSUE TITLE
Please move the example dir to it's own repo

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#3315]
Most of the examples do not have a dependency on being colocated with the codebase (do any)?

The downside of having them there is that you have to checkout all of OpenShift just to get the example.

You also have to fork all of openshift if you want all of your own private examples. 

For teaching and demos we just want the examples. It will also be helpful to not have to go down several directories just to get to the examples.

Thanks

**Comment by danmcp** [comment]
There are plenty of examples that are forkable (the web framework ones):

https://github.com/openshift/nodejs-ex
https://github.com/openshift/rails-ex
https://github.com/openshift/django-ex
https://github.com/openshift/dancer-ex
https://github.com/openshift/cakephp-ex

If we do want to make another repo for the samples in origin, I would want to stick with the rule that unless the repo makes sense to fork by itself keep them in one repo together.  Forking sample-app by itself for example doesn't make a lot of sense.  And having 100s of sample repos makes it hard to find and organize.

**Comment by thesteve0** [comment]
I am talking about this entire directory

https://github.com/openshift/origin/tree/master/examples

That should be it's own repo. There are no frameworks here it is just
examples of how to spin up stuff in OpenSHift. Do any of these require
being in the same directory as the origin repo?

**Comment by smarterclayton** [comment]
We test and validate them automatically on every build - it makes that harder to manage

**Comment by thesteve0** [comment]
You mean you actually build each projects in there and run tests against
each of them with each build?

How about a git subrepo or something.

**Comment by chmouel** [comment]
just my 2c from my experience with large projects git submodules are usually always a bad idea on the long term

**Comment by thesteve0** [comment]
Ok thanks - but unless they are really being used in tests with the core
stuff I am not sure the good outweighs the bad

On Fri, Jun 19, 2015 at 12:36 AM, Chmouel Boudjnah <notifications@github.com

**Comment by thesteve0** [comment]
Bug #3302 is another example of why this should be broken out as well.

**Comment by liggitt** [comment]
Depends... we do run a lot of the examples in the tests that gate merges... having them in a different repo would let people modify them without realizing they were breaking the merge queue

**Comment by sdodson** [comment]
Currently the ansible installer is collecting examples and installing them for users who make use of ansible. See https://github.com/openshift/openshift-ansible/pull/289 There's a crude maintenance script that helps with retrieving and updating the examples but it's less than ideal.

I'd like to suggest the opposite of this. A contrib directory in origin where other groups can submit examples to be installed by admins.

**Comment by bparees** [comment]
my vote is to close this.  sample-app has probably outlived its usefulness as a "getting started example" so we should be pointing people to the other freestanding sample repos (the -ex dirs) but for use by our test infrastructure, we need to retain the content in our repo.

**Comment by liggitt** [comment]
> my vote is to close this [...] for use by our test infrastructure, we need to retain the content in our repo.

+1

**Comment by thesteve0** [comment]
I think I am +1, can you please explain more

**Comment by bparees** [comment]
what part would you like explained more?

**Comment by thesteve0** [comment]
What are the ex projects - is there doc or a trello card for them?

**Comment by bparees** [comment]
They're the repos Dan linked in his first comment. They all include doc in
their respective repos.

Ben Parees | OpenShift

**Comment by mfojtik** [comment]
@bparees @thesteve0 there are also replication examples in our database repositories. I would like to make them more visible at some point but I'm not sure if taking them away from the database repos would be good solution (especially if they depend on the image scripts)

**Comment by smarterclayton** [comment]
We should probably move to testing real examples (-ex) in e2e AND start
using the mock test more extensively.  We also need to start the process of
expanding our e2e infrastructure to resemble upstream's - and to run those
against our infra.  I'm ok with beginning to sunset sample app, but we will
have to do something about the blogs and supplementary doc that points to
them.

On Jul 6, 2015, at 11:36 PM, Ben Parees <notifications@github.com> wrote:

my vote is to close this. sample-app has probably outlived its usefulness
as a "getting started example" so we should be pointing people to the other
freestanding sample repos (the -ex dirs) but for use by our test
infrastructure, we need to retain the content in our repo.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3315#issuecomment-119062728>.

**Comment by bparees** [comment]
closing in light of existing test infrastructure needs for this and the existence of other forkable example repos.
