### ISSUE TITLE
Can't use secrets in templates for pods also in templates

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3318]
In order to mount a secret, the service account for a pod must have the secret in its list of mountable secrets.  If my secret is in my template and I don't want to create a new service account in that template, my pods will be rejected until my service account is updated.

We should have an option for creating a super-SA that can mount any secret in the namespace.  Two obvious implementations:
 1. flag obeyed by the admission controller that allow any secrets.
 1. flag obeyed by a controller that adds all secrets to the list of mountable secrets for the service account.

I think the dealbreak for option 2 is that if the modification of the service account  doesn't happen before the pod in the template is created, the pod will be rejected by admission.  Pretty sure that means it's option 1 only.

**Comment by smarterclayton** [comment]
This is pissing me off and is now p1.  I'd like this in before we cut 3.0.1

**Comment by liggitt** [comment]
can do this for non-enforcing service accounts, which is the default. lowering priority.

**Comment by liggitt** [comment]
actually, going to close this as fixed in https://github.com/openshift/origin/pull/3907
