### ISSUE TITLE
A way to cleanup the contexts  from oc config kubeconfig

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#3321]
The kubeconfig after a while get populated a lot of different contexts that are not working anymore if you delete/change projects it would be nice if there was a way to be able to clean them automatically

**Comment by smarterclayton** [comment]
Agree delete should purge them.

**Comment by smarterclayton** [comment]
`oc delete-contexts` now exists!

**Comment by wheelerlaw** [comment]
Can this be re-opened? This command no longer exists:

```
$ oc delete-contexts
Error: unknown command "delete-contexts" for "oc"
Run 'oc --help' for usage.
```

**Comment by mimber** [comment]
+1
