### ISSUE TITLE
"a build has completed" cannot be dismissed

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#3327]
![screenshot from 2015-06-18 19 24 06](https://cloud.githubusercontent.com/assets/94413/8244514/a6dc2ad4-15ef-11e5-91df-f4ecef23567b.png)

There's no "x" button... is this intended?  Do these ever go away?

![screenshot from 2015-06-18 19 25 37](https://cloud.githubusercontent.com/assets/94413/8244523/d2090f60-15ef-11e5-8054-e34c73e7cf70.png)

**Comment by liggitt** [comment]
It goes away after five minutes, there should probably be a way to manually dismiss it as well

**Comment by liggitt** [comment]
Successful notifications should probably go away quicker. Failures are useful longer, especially once we get the ability to rebuild or view logs.

**Comment by spadgett** [comment]
#3349 reduces the amount of time successful builds are visible to 1 minute after completion. (Failed builds are still 5.)

**Comment by spadgett** [comment]
Related to #3416
