### ISSUE TITLE
Builds should have an incrementing build number when generated from a build config

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#333]
Builds generated from a build config should have an incrementing number, its more user oriented to see and refer to build 115 of my_build than to see a GUID.

Similar to deployments which have an incrementing id when triggered from a deployment config

**Comment by bparees** [comment]
https://trello.com/c/jaBsS4IZ/520-name-builds-sequentially

**Comment by soltysh** [comment]
@bparees the PR is merged, can you close this now, please.

**Comment by bparees** [comment]
yup, thanks!
