### ISSUE TITLE
Bash completion seems not working

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#3330]
If I understand properly the bash completion is auto generated automatically with the spf13/cobra library but when trying to use it it just fails with an undefined function : 

    bash-4.3$ source rel-eng/completions/bash/oc
    bash-4.3$ oc bash: _init_completion: command not found

which I can see only referenced here : 

https://github.com/spf13/cobra/blob/master/bash_completions.go#L184

I am not sure where this is coming from (I guess I can report it on the cobra repo issue there as well) if you have any ideas?

PS: since I was sick of the typing I started creating a minimal zsh completion module here : 

https://github.com/chmouel/zsh-config/blob/master/functions/_osc

**Comment by liggitt** [comment]
are you seeing that with the latest completions?
```
$ source rel-eng/completions/bash/oc
$ oc get p<tab>
persistentvolume       pod                    policy                 project                
persistentvolumeclaim  podtemplate            policybinding          
```

**Comment by chmouel** [comment]
weird, i am using this on master but using that on macosx, any chances you can do a which _init_completions to see where is this coming from ?

**Comment by Miciah** [comment]
Your MacOS X system must have an old version of bash-completion.

https://bugzilla.redhat.com/show_bug.cgi?id=1226672#c14

https://bugzilla.redhat.com/show_bug.cgi?id=1232111

**Comment by chmouel** [comment]
Thanks, I guess brew/macosx has not updated on latest bash_completions :(
