### ISSUE TITLE
Update kubernetes v1 api types

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#3331]
#3592 migrates these fields and upper-cases port protocols:

origin 1.0.0 v1 | kubernetes v1
-----------|-------------------
PodSpec.serviceAccount | PodSpec.serviceAccountName
PodSpec.host | PodSpec.nodeName
ServiceSpec.portalIP | ServiceSpec.clusterIP

{Container,Endpoint,Service}Port.Protocol allows lowercase, Kube requires uppercase (#3520)

#3524 rebase added these fields:

origin 1.0.0 v1 | kubernetes v1
-----------|-------------------
*missing* | HTTPGetAction.scheme
*missing* | NodeSpec.providerID
*missing* | ObjectMeta.generation
*missing* | PodStatus.reason
*missing* | ReplicationControllerStatus.observedGeneration

TODO:
{Container,Endpoint,Service}Port.Name allows dns subdomain, Kube requires IANA_SERVICE_NAME

ContainerState.termination -> ContainerState.terminated

**Comment by stevekuznetsov** [comment]
@liggitt  fyi, if this gets merged https://github.com/GoogleCloudPlatform/kubernetes/pull/9965

**Comment by sdodson** [comment]
Are we going to migrate the no longer valid content or is that something that'll need to be done external to openshift?

**Comment by liggitt** [comment]
we will likely carry a conversion patch to migrate the content... deciding that now
