### ISSUE TITLE
Exec and port forwarding improvements

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#3332]
# Background
There are some areas for improvement with the design and implementation of exec and port forwarding

## Timeouts
The master has configurable settings for its HTTP server's `ReadTimeout`/`WriteTimeout`, which is good. The Kubelet's settings are hard-coded to 5 minutes. This means that the longest you can do I/O between `oc exec` and the process in the container is 5 minutes. We should at least make the Kubelet's settings configurable. 

## Protocol
The current implementation uses SPDY/3.1 via https://github.com/docker/spdystream. SPDY is essentially end-of-lifed, being replaced by HTTP/2. There is not yet support for HTTP/2 in Go, but when it arrives, we should switch to using it instead of SPDY.

## Components involved
The current implementation has the following flow:

`oc client` :left_right_arrow: `master` :left_right_arrow: `kubelet` :left_right_arrow: `docker daemon (exec)` :left_right_arrow: `desired process e.g. bash`

This is a significant number of hops. It can also be a burden on the master, kubelet, and/or docker daemon, as it requires all data from stdin/stdout/stderr to travel through each of these components.

It is preferable to remove the kubelet and docker daemon from the flow. After the master authenticates and authorizes the exec request, it will proxy to the kubelet as it currently does. The kubelet will create a process in the appropriate container that will listen for an exec request. The kubelet will issue an HTTP redirect to a single-use URL specifically for that exec session, which will be handled by the just-spawned process. The flow would look like this:

`oc client` :left_right_arrow: `master` :left_right_arrow: `spawned exec listener` :left_right_arrow: `desired process e.g. bash`

The master is still in the flow as it is a horizontally scalable component. It is better to proxy access to the container exec listener via the master, as it allows us to control authentication and authorization.

Note the removal of `docker daemon (exec)` from the flow. There are some issues with using docker's native exec handler, described next.

## Exec handler
We currently support 2 exec handlers: nsenter and docker's built-in exec API. The nsenter handler was the initial implementation, but because it runs the executed process as root and doesn't drop any privileges at all, we don't recommend using it any more. The docker handler proxies all data for stdin/stdout/stderr through the docker daemon, which is undesirable. It is also impossible to use an API to stop or kill the executed process. We also don't know its PID with absolute certainty, so we can't `kill` it when needed.

Given these shortcomings, we recommend using a new exec handler based on libcontainer that is able to run processes in existing containers, just like the docker daemon does, but without requiring the daemon and also with the ability to stop or kill them. We have https://github.com/openshift/dockerexec to serve this purpose.

## Terminal resizing
We never implemented support for terminal resizing and should do so. A prototype exists here: https://github.com/ncdc/origin/commit/13220dbb5208df5659568e282bc8483079463d2c#diff-1045e6cfdb618aa02412ba7a2c64c717. It uses Go's `binary.Read/Write` to encode/decode the new window width and height; there is probably a better way to do it, but it works in the prototype.

**Comment by brenton** [comment]
Do we think this could help the current situation with `oc exec` behind a proxy? https://github.com/openshift/openshift-docs/issues/732

**Comment by ncdc** [comment]
No, we're using a custom `RoundTripper` to do connection upgrading for SPDY, and we haven't added support for proxying yet. We're still evaluating design options. Trello card is here: https://trello.com/c/WZy2yFSF/200-8-exec-add-proxy-support-tech-debt

**Comment by brenton** [comment]
@ncdc, just to make sure we're talking about the same thing I want to be clarify things a bit.  There are two proxy scenarios that are currently not working with `oc exec`.  https://github.com/openshift/origin/issues/3370 is a forward proxy problem.  https://github.com/openshift/openshift-docs/issues/732 is a reverse proxy problem.

I'm really concerned about the latter because it prevents admins from putting an HTTP proxy in front of the Master.  It seems like even with the switch to HTTP/2 we'll still be a in a problem until the majority of HTTP proxies can support it.

**Comment by ncdc** [comment]
@brenton gotcha, sorry for the confusion. I don't think any of the changes described above will help with the reverse proxy problem. I've tested `kubectl exec` against a GCE cluster with nginx as a proxy in front of the master, and I believe it worked. I'll add a comment over in the docs issue.

**Comment by brenton** [comment]
Yeah, looking now it seems like nginx supports spdy natively.  I think we'll have to find a proxy example using stock RHEL components that support spdy.  Apache 2.4 doesn't unfortunately.  Thanks for the clarification.

**Comment by brenton** [comment]
It's definitely worth noting that the move to HTTP/2 should take reverse proxies into account.  Some that support spdy don't yet support HTTP/2.

**Comment by liggitt** [comment]
The need for spdy/http through proxies is lessened by https://github.com/openshift/origin/pull/4279 which allows an auth proxy without proxying the entire API. The use case is still valid, though

**Comment by ncdc** [comment]
The kubelet's read and write timeouts are not 60 minutes.

Changes to protocol, components, exec handler are all upstream issues.

Terminal resizing has been implemented.

@brenton @liggitt I'd recommend we create a separate issue about supporting reverse proxies for exec/attach/portforward.
