### ISSUE TITLE
Error when pulling from registry.access.redhat.com

### ISSUE THREAD

**Issue by kwoodson** [openshift/origin#3335]
I was attempting to build a base operations image based off rhel7:latest.  I received the following error:
newapp.go:88] error: no image or template matched "rhel7": the default tag "latest" has not been set on repository "library/rhel7"

Here is the --loglevel=5 output:
`$oc new-app --loglevel=5 -l name=oso-rhel7-ops-base https://github.com/kwoodson/oso-rhel7-ops-base -n kwoodson`
`I0619 13:02:57.866420   31914 newapp.go:184] No local Docker daemon detected: dial unix /var/run/docker.sock: permission denied`
`I0619 13:02:58.234514   31914 imagelookup.go:149] checking Docker registry for "library/rhel7"`
`I0619 13:02:58.234604   31914 client.go:228] Getting repository library/rhel7 from {https  <nil> index.docker.io   }`
`F0619 13:02:59.005724   31914 newapp.go:88] error: no image or template matched "rhel7": the default tag "latest" has not been set on repository "library/rhel7"`

I worked with @csrwng to do some debugging and it appears that docker hub attempts to redirect the client requests to registry.access.redhat.com.  This did not appear to be functioning correctly.  This **was** working in the beta4 (0.5.2) release in stage.

**Comment by bparees** [comment]
@kwoodson @csrwng is this still an issue or did you guys sort it out?
