### ISSUE TITLE
Builds should be removed from the overview 5 minutes after completion, not creation

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3344]
We remove finished builds from the overview after 5 minutes. We use the `build.metadata.creationTimestamp`, however. This means if the build takes more than 5 minutes to run, it will disappear immediately when it completes.

**Comment by liggitt** [comment]
We should be using the completionTimestamp if available

**Comment by liggitt** [comment]
Also see https://github.com/openshift/origin/issues/3327 for feedback on timing... a successful build could probably be removed 30-60 seconds after completion. A failed build should probably stick around longer after completion

**Comment by spadgett** [comment]
Not sure about this test.

```
ng-if="build.status.phase == 'New' || build.status.phase == 'Pending' || build.status.phase == 'Running' || (build.metadata.creationTimestamp | ageLessThan : 5 : 'minutes')"
```
 The expression is only evaluated during a digest cycle, right? So if nothing changes in your project, the build might stick around longer than 5 minutes? We've removed calls to `$interval`.

I'd personally prefer successful builds staying for a few minutes if you can dismiss them. If you aren't watching, they're be easy to miss. But I'm OK either way.

**Comment by liggitt** [comment]
As soon as we let you dismiss them, we have to remember you dismissed them, so we don't show them again if you refresh the page. Don't really want to get into stored user preferences at this moment
