### ISSUE TITLE
Names for examples should  be consistent across build configs and deployment configs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3358]
In our examples, when we have multiple components (a build config for a frontend and a deployment config for a frontend and backend) the build config, deployment config, service name, and route name should all match.

Example, nodejs.json:

```
service: nodejs-frontend
route: nodejs-example
build config: nodejs-example
deployment config: nodejs-frontend
image stream: nodes-example
container name: nodejs-example
source: https://github.com/openshift/nodejs-ex.git
```

It's hard to switch between these mentally - it would be better if we were consistent, nodejs-example completely or nodejs-frontend completely.

**Comment by gabemontero** [comment]
@smarterclayton All the sample repos have been updated.  Close or advise of additional changes at your discretion.  Thanks.

**Comment by smarterclayton** [comment]
Can you link the fixes you made to this issue?

**Comment by gabemontero** [comment]
cakephp-ex :  https://github.com/openshift/cakephp-ex/pull/10
dancer-ex:  https://github.com/openshift/dancer-ex/pull/18
django-ex:  https://github.com/openshift/django-ex/pull/21
golang-ex:  https://github.com/openshift/golang-ex/pull/2
nodejs-ex:  https://github.com/openshift/nodejs-ex/pull/23
rails-ex:  https://github.com/openshift/rails-ex/pull/34
origin doc improvements from testing of *-ex readme's : https://github.com/openshift/origin/pull/3522

**Comment by smarterclayton** [comment]
One thing - when someone deploys these examples, are they going to then
evolve them to be their own?  If so, having to find/replace "-example" in
the template is going to be somewhat annoying.  I think this is fine for
now, but something we need to consider in the future for naming.

2015-07-02 15:18 GMT-04:00 Gabe Montero <notifications@github.com>:

> cakephp-ex : openshift/cakephp-ex#10
> <https://github.com/openshift/cakephp-ex/pull/10>
> dancer-ex: openshift/dancer-ex#18
> <https://github.com/openshift/dancer-ex/pull/18>
> django-ex: openshift/django-ex#21
> <https://github.com/openshift/django-ex/pull/21>
> golang-ex: openshift/golang-ex#2
> <https://github.com/openshift/golang-ex/pull/2>
> nodejs-ex: openshift/nodejs-ex#23
> <https://github.com/openshift/nodejs-ex/pull/23>
> rails-ex: openshift/rails-ex#34
> <https://github.com/openshift/rails-ex/pull/34>
> origin doc improvements from testing of *-ex readme's : #3522
> <https://github.com/openshift/origin/pull/3522>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3358#issuecomment-118138981>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by gabemontero** [comment]
Hmm ... has there been any thought to, or how feasible is it to have,  a variable substitution mechanism for these json files' contents?  Especially if the name is the only variable, and folks will want to use them as-is otherwise.  It would be somewhat analogous to setting ENV vars in the JSON for runtime use in the containers.

**Comment by bparees** [comment]
yes the names are all parameterizable just like we do with the DB side, like here:
https://github.com/openshift/rails-ex/blob/master/openshift/templates/rails-postgresql.json#L250

so we could do the same for the rest of the names (with useful defaults).  @gabemontero if you want to open a new issue to track doing that and we can queue it up.

**Comment by gabemontero** [comment]
3571 is opened:  https://github.com/openshift/origin/issues/3571
