### ISSUE TITLE
We say the same words over and over and over again in the UI

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3361]
The pod template section is repeating a lot of redundant info redundantly.  Some things:

* We can probably omit the container name if there is a single container always
* The build name should be "nodejs-example #4" and be a link
* The image snippet is actually chopping off the @<sha7> section, probably a bug in my chopping code (the returned value is nodes-example@732498 but we make it nodes-exa), but could also be an API value snafu.

![screenshot 2015-06-20 21 44 17](https://cloud.githubusercontent.com/assets/1163175/8270022/a4c45436-1795-11e5-97cf-0d52569b8726.png)

**Comment by liggitt** [comment]
I think showing the full build pod name predated the names being derivable from the build config
The image snippet is truncating to 6-7ish characters, so it's never making it to the image hash

**Comment by smarterclayton** [comment]
Probably want the image field like we discussed as well

**Comment by spadgett** [comment]
Unfortunately, I don't see a build number property or annotation like we have for deployments. I'll have to figure it out from the end of the name and be careful about cloned builds (#3368).

**Comment by smarterclayton** [comment]
We should probably create those annotations with labels and then make sure they get surfaced up.  Rather you having to hack around it.

**Comment by spadgett** [comment]
First pass at this. Right now I'm showing the build name only since I can't easily get the number.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8292924/37d8d786-1900-11e5-8390-ef82dc376249.png)

Still looks busy to me. Wondering if we really need the labels (Image, Build, ...) or if the icons with alt text are enough. If we do keep the labels, it might look cleaner to left-align the values.

As an aside, it bugs me that the icon and text aren't aligned here:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8293069/1ab35e78-1901-11e5-8074-314e0dfb16c5.png)

**Comment by smarterclayton** [comment]
I would say "ruby-sample-build #7" as a link.  Image should probably be "[<namespace if different>/]<name>:<id or tag name or latest>" with something like "(from :<tag>)" if you show the ID.  Reason is that we want to focus on what you actually deployed right now (which is usually the ID, sometimes the tag) and then tell you where you came from (the tag) to clarify.

Agree they're aligned

**Comment by spadgett** [comment]
Changes so far. Tooltip shows the unabbreviated image value on hover.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8336340/bcbc8fc0-1a71-11e5-942a-894dea307783.png)

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8336336/b2e7c41a-1a71-11e5-8387-efc3f61f5a0f.png)

I've also updated the build status message:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8336371/ff8dbb76-1a71-11e5-819f-43517d33e3bc.png)

Working on showing `(from :tag)`. The only way I see is to look for `ImageStreamTag` triggers on the deployment config and match `lastTriggeredImage` to the container image, then split `from.name` on `:` to get the tag.

**Comment by liggitt** [comment]
heh, @smarterclayton's original comment got rendered strangely by github... link the entire build name + number
should we keep the "running build" part unlinked? you can already click on it and see details in the sidebar

**Comment by spadgett** [comment]
OK, I have `from :tag` for the image and removed the link from the running build.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8341133/02708160-1a91-11e5-89e0-18187613bfc7.png)

**Comment by smarterclayton** [comment]
Looks awesome

**Comment by smarterclayton** [comment]
eventually we want to break the components up and link them cleanly - this is a good step.  I'm tempted to change the font / formatting of the image id like a git commit id, but that's a broader discussion

**Comment by jwforres** [comment]
current state of things

![20150904_124743_](https://cloud.githubusercontent.com/assets/1467629/9689395/c2c1c410-5303-11e5-9a58-2e9f60459fc4.png)

**Comment by jwforres** [comment]
With a few more changes as part of overview rework:

![latest_overview](https://cloud.githubusercontent.com/assets/1467629/9689847/bfb6077e-5306-11e5-9731-fdcc13bda599.png)

**Comment by jwforres** [comment]
https://trello.com/c/dxghKjpu
