### ISSUE TITLE
Display empty deployment configs and latest deployments

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3363]
The console UI should show at least the most recent deployment when scaled to 0 (so you know a deployment existed), and probably should show recent deployments (<N-1) for a brief period of time before hiding them.  There should probably be a way in the UI to see older deployments.  Eventually we'll want to have a scale control on 0 deployments.

Empty RCs not in deployment configs should always be shown.

**Comment by jwforres** [comment]
@fabianofranz something to consider while you are looking at deployment stuff

**Comment by fabianofranz** [comment]
@jwforres ok, I'll have that in mind. ATM we just blindly display every deployment attached to the given dc, and deployments without a dc in a separate section, without any smarter handling about the history or scale.

**Comment by jwforres** [comment]
This is partially fixed by https://github.com/openshift/origin/pull/4726

need to look at what we want to show in the overview in some of these cases

**Comment by spadgett** [comment]
@jwforres So this is what happens when you show the donut chart with no data... The ring disappears. I feel like we could do better, but I'm not sure what. Thoughts?

<img width="530" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/10769831/6e6b02fc-7cbe-11e5-8f56-519c2fdf31f5.png">

**Comment by spadgett** [comment]
We could add a light gray ring with a custom tooltip, but that's what we use for pending today.

**Comment by liggitt** [comment]
that's a lot of space for a 0-pod deployment

**Comment by spadgett** [comment]
It's a very important 0 pod deployment.

**Comment by spadgett** [comment]
I could tighten the whitespace, but the scaling arrows might move as you click them... Assuming we leave the arrows.

**Comment by jwforres** [comment]
Arrows have to stay, if i accidentally click one time to many and suddenly i cant scale back up from here, panic ensues

**Comment by liggitt** [comment]
just say it's a transparent ring and move on ;-)

**Comment by jwforres** [comment]
@liggitt is joking, but i was going to suggest white with a black border? is that possible?

**Comment by spadgett** [comment]
> @liggitt is joking, but i was going to suggest white with a black border? is that possible?

You can set the stroke style on the arcs when no pods, which would give it an outline, but we'd have to add in a dummy data group to get c3 to draw the arc at all.

**Comment by spadgett** [comment]
Here's how it looks:

<img width="557" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/10774019/2e84bb80-7cd5-11e5-8629-5b025e4c675c.png">

**Comment by smarterclayton** [comment]
Oh that's beautiful

**Comment by jwforres** [comment]
@spadgett that works for me, just need the scale down arrow to not look
active

**Comment by liggitt** [comment]
It looks so… empty :-)

**Comment by smarterclayton** [comment]
All it wants is to be filled with pods.

On Oct 27, 2015, at 7:03 PM, Jordan Liggitt <notifications@github.com>
wrote:

It looks so… empty :-)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3363#issuecomment-151670067>.
