### ISSUE TITLE
Deflake builds and build systen

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3365]
Existing issues:
- [ ] Timeout on travis
- [x] racy testclient - https://github.com/openshift/origin/issues/3757
- [ ] ~~phantomjs flake in e2e~~ opened issue https://github.com/openshift/origin/issues/2286
- [ ] ~~Tests with external dependencies (like dockerhub)~~ opened issue https://github.com/openshift/origin/issues/3624

**Comment by pmorie** [comment]
@smarterclayton even snowflakes? :snowflake:

**Comment by liggitt** [comment]
haven't seen the travis timeout recently. please reopen a standalone issue if it reoccurrs.
