### ISSUE TITLE
cloning a build creates a name like "nodejs-example-1-1434930559"

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3368]
Should be "nodejs-example-2".

**Comment by smarterclayton** [comment]
If this is hard to fix without the larger build config change let's queue it up behind that.

**Comment by smarterclayton** [comment]
Or, if it's because we're creating a build out of sequence, let's try to make the number more meaningful (tie it to the restart sequence, or make it use the random name generator, or similar).  If it's just the start # that's not a great visual experience.

**Comment by liggitt** [comment]
The UI is just calling clone build. The API does this:
```
func getNextBuildNameFromBuild(build *buildapi.Build) string {
	buildName := build.Name
	if matched, _ := regexp.MatchString(`^.+-\d-\d+$`, buildName); matched {
		nameElems := strings.Split(buildName, "-")
		buildName = strings.Join(nameElems[:len(nameElems)-1], "-")
	}
	return fmt.Sprintf("%s-%d", buildName, int32(util.Now().Unix()))
}
```

**Comment by smarterclayton** [comment]
Unix number probably isn't friendly enough.  I don't think this is super high priority but the ideal case should help users understand what triggered the build more easily, the log number is effectively unreadable.

**Comment by soltysh** [comment]
The initial idea here was to mark know how the build was triggered, iow. the builds from BC are named buildconfigname-seq_number, whereas the ones cloned from existing builds are named buildname-seq_number. Having a BC name mybuild you'd get:
- build from BC: mybuild-1, mybuild-2, etc.
- clone from mybuild-1: mybuild-1-1, mybuild-1-2, etc.
Unfortunately I failed at the 2nd part (naming build clones), I was having some problems storing the necessary information in builds. If we still want that (IMHO it'll be cool to have it working) I can work again on this idea once again.

**Comment by liggitt** [comment]
Finding the next free sequence number for a clone could be a pain... also want to be careful whatever we end up with also handles clones of clones of clones... probably want to continue stemming off the base build name.

**Comment by soltysh** [comment]
Right, that was one of the reasons I dropped it there and just did unix timestamp. One other thought may be changing the unix timestamp to show actual date, so instead of random looking numbers you'd get mybuild-1-20150622150404, @smarterclayton any preference?

**Comment by smarterclayton** [comment]
Yeah, I'm thinking this is an offset build, loosely ordered.  Number of minutes from original build is something relevant but this is going to be so vanishingly rare an action that I'd almost prefer a search so we get linear order.  If 99% of all rebuilds are a 1.1 or 1.2 the perf of a search is negligible. If people are rebuilding builds that are not part of a build config frequently we should ask ourselves why (that's what build configs are supposed to do).

**Comment by liggitt** [comment]
that's true... list scoped to namespace to get the existing pool wouldn't be bad... conflict if you double-clicked clone would get you what?

**Comment by smarterclayton** [comment]
Immediate follow on thought - this is exactly like deploy latest.  Not sure why we would have a different experience (we should require a reason to differ).

**Comment by liggitt** [comment]
is it? You can clone builds other than the latest build

**Comment by soltysh** [comment]
Right, in the series of old builds, let's say I have 5 of them, I can clone 2nd and 5th one, how'd you name them?

**Comment by smarterclayton** [comment]
you can rollback to older deployments and you get the latest number.  If you rebuild Jenkins you get the newest number.  The important thing is that a newer build (one triggered by an image change or a webhook) should still happen with the next higher number, but that it won't automatically rebuild the last image.  That's the change we've discussed about making build configs be a stream, not a swamp.

**Comment by spadgett** [comment]
Rebuilding multiple times keeps appending long numbers, which results in some entertaining names.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/9643548/b6fa560c-5190-11e5-8e69-f6cebf3ab129.png)

**Comment by liggitt** [comment]
@csrwng I thought we fixed that for clone

**Comment by spadgett** [comment]
I think the builds fail to start once the names get this long.

**Comment by csrwng** [comment]
@liggitt I thought so too

**Comment by csrwng** [comment]
hmm, I'm not seeing that behavior in the CLI... latest master

**Comment by liggitt** [comment]
Problem is with the regex that reuses portions of the build's name:
```
if matched, _ := regexp.MatchString(`^.+-\d-\d+$`, buildName); matched {
```

that fails after 9+ builds have been done from the build config

**Comment by liggitt** [comment]
would also probably be clearer to capture the portion of the build name you want to reuse:

```
	re := regexp.MustCompile(`^(.+-\d+-)\d+$`)
	if matches := re.FindStringSubmatch(buildName); matches != nil {
		buildName = matches[1]
	}
```

**Comment by smarterclayton** [comment]
Also, stop using regex.

On Wed, Sep 2, 2015 at 5:02 PM, Jordan Liggitt <notifications@github.com>
wrote:

> would also probably be clearer to capture the portion of the build name
> you want to reuse:
>
>     re := regexp.MustCompile(`^(.+-\d+-)\d+$`)
>     if matches := re.FindStringSubmatch(buildName); matches != nil {
>         buildName = matches[1]
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3368#issuecomment-137243395>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift
