### ISSUE TITLE
osc exec is ignoring proxy

### ISSUE THREAD

**Issue by pillimede** [openshift/origin#3370]
When executing `osc exec`, the proxy configured with `HTTP_PROXY` is ignored. Other commands such as `osc logs -f ...` are respecting `HTTP_PROXY` and are working fine.

The command `osc exec -p xyz-6-aabv1 -- ls` fails with

    error: Error sending request: Get https://xxx:8443/api/v1beta3/namespaces/test/pods/xyz-6-aabv1/exec?command=ls&container=xyz&stderr=true&stdout=true: dial tcp xxx.xxx.xxx.xxx:8443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

I observed this with osc in version 0.5.2.2 running on windows 7 targeting our OSE beta 4 installation running on AWS (xxx-xxx-xxx-xxx). Additionally I configured `http_proxy` (lowercase) but I observed no difference.
      
Here the list of the network connections of osc:

    The connection to our company proxy:
       TCP    127.0.0.1:61363        ppp.ppp.ppp.ppp:8080  ESTABLISHED
    The attempt to open a connection to OpenShift is blocked by our company firewall:
       TCP    ccc.ccc.ccc.ccc:61393    ec2-xxx-xxx-xxx-xxx.eu-west-1.compute.amazonaws.com:8443  SYN_SENT  
    Connections related to windows (Active Directory):
       TCP    ccc.ccc.ccc.ccc:61361    WWCADS03.ch.doleni.net:epmap  ESTABLISHED
       TCP    ccc.ccc.ccc.ccc:61362    WWCADS03.ch.doleni.net:51000  ESTABLISHED

	   
The list shows

- osc communicating with our company proxy (ppp.ppp.ppp.ppp)
- the unsuccessful attempt to reach the OpenShift installation on AWS blocked by our firewalls (ccc.ccc.ccc.ccc is the ip address of the client)

**Comment by ncdc** [comment]
Exec and port forwarding use a custom `http.RoundTripper` that currently does not support proxies. This is ultimately an issue for Kubernetes upstream as we just pull in exec and pf from Kube. @smarterclayton does it make sense to try to add proxy support for `SpdyRoundTripper`?

**Comment by smarterclayton** [comment]
I don't know if arbitrary proxies support connection upgrade.  We may need
to figure out whether that even works first.

On Jun 29, 2015, at 1:14 PM, Andy Goldstein <notifications@github.com>
wrote:

Exec and port forwarding use a custom http.RoundTripper that currently does
not support proxies. This is ultimately an issue for Kubernetes upstream as
we just pull in exec and pf from Kube. @smarterclayton
<https://github.com/smarterclayton> does it make sense to try to add proxy
support for SpdyRoundTripper?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3370#issuecomment-116765122>.

**Comment by ncdc** [comment]
I hacked up SpdyRoundTripper and tested against Squid and was able to get exec to work through the Squid proxy. Is that enough validation to go and implement this for real?

**Comment by chmouel** [comment]
@ncdc was it a proxy with authentication?

**Comment by ncdc** [comment]
No. I suppose I could set one up and see if it works.

**Comment by smarterclayton** [comment]
An Apache mod proxy too?

On Jun 29, 2015, at 7:43 PM, Andy Goldstein <notifications@github.com>
wrote:

No. I suppose I could set one up and see if it works.

On Monday, June 29, 2015, Chmouel Boudjnah <notifications@github.com> wrote:

> @ncdc <https://github.com/ncdc> was it a proxy with authentication?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3370#issuecomment-116879432>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3370#issuecomment-116880519>.

**Comment by bparees** [comment]
also tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1241045

**Comment by ncdc** [comment]
Upstream WIP PR https://github.com/GoogleCloudPlatform/kubernetes/pull/11694

**Comment by fabianofranz** [comment]
@ncdc was this rebased from upstream already?

**Comment by ncdc** [comment]
It landed upstream after the most recent rebase. We cherry picked it in #5397. Closing.
