### ISSUE TITLE
etcd fail to recover after a disk full

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#3377]
We go hit as described by this bug :

https://github.com/coreos/etcd/issues/2819

This is running 2.0.1 as mentioned from the logs :

    etcdserver: datadir is valid for the 2.0.1 format

It seems that master has only 2.0.11 : 

https://github.com/openshift/origin/blob/master/Godeps/Godeps.json#L535

but from a chat on irc with @sdodson only 2.1 have a proper fix for this to recover

**Comment by bparees** [comment]
@smarterclayton are we expecting to get an upstream fix for this before 3.0.1?

**Comment by smarterclayton** [comment]
Not possible for 3.0.1 but a recovery helper is possible when I get a minute

On Jul 21, 2015, at 5:44 PM, Ben Parees <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> are we expecting to get
an upstream fix for this before 3.0.1?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3377#issuecomment-123486169>.

**Comment by sdodson** [comment]
I tried running etcd 2.1 against a corrupt data directory created by a panic'd master and it wouldn't clean things up. Should that've worked?

**Comment by smarterclayton** [comment]
Depends - open an issue at least upstream if you have a shareable data
store.

On Jul 21, 2015, at 5:52 PM, Scott Dodson <notifications@github.com> wrote:

I tried running etcd 2.1 against a corrupt data directory created by a
panic'd master and it wouldn't clean things up. Should that've worked?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3377#issuecomment-123488053>.

**Comment by chmouel** [comment]
I haven't tested it but i guess this can be closed ? since we are now on etcd 2.1
