### ISSUE TITLE
hack/test-cmd.sh timeout on `delete all --all`

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#3383]
Full goroutine dump:
http://pastebin.test.redhat.com/291927

Interesting goroutine:
http://pastebin.test.redhat.com/291929

**Comment by ncdc** [comment]
Related: #3365

**Comment by liggitt** [comment]
#3365 wins on flowery language and emoji. #3383 wins on helpful details. Happy to close either :)

**Comment by liggitt** [comment]
Dupe of #2295
