### ISSUE TITLE
Build hangs in New when BuildOutput is missing

### ISSUE THREAD

**Issue by mmilata** [openshift/origin#3391]
### Steps to reproduce

Using openshift 1.0.0 built from source on RHEL 7.1.
```
$ cat f.json
{
    "kind": "Build",
    "apiVersion": "v1",
    "spec": {
        "source": {
            "git": {
                "ref": "master",
                "uri": "https://github.com/mmilata/docker-hello-world.git"
            },
            "type": "Git"
        },
        "strategy": {
            "customStrategy": {
                "exposeDockerSocket": true,
                "from": {
                    "kind": "ImageStreamTag",
                    "name": "buildroot:latest"
                }
            },
            "type": "Custom"
        }
    },
    "metadata": {
        "name": "test-build-123"
    }
}

$ curl -k -X POST https://localhost:8443/oapi/v1/namespaces/default/builds/ --data @f.json
{
  "kind": "Build",
  "apiVersion": "v1",
  "metadata": {
    "name": "test-build-123",
    "namespace": "default",
    "selfLink": "/oapi/v1/namespaces/default/builds/test-build-123",
    "uid": "6384ccea-1995-11e5-8a39-525400189322",
    "resourceVersion": "965",
    "creationTimestamp": "2015-06-23T10:48:31Z"
  },
  "spec": {
    "source": {
      "type": "Git",
      "git": {
        "uri": "https://github.com/mmilata/docker-hello-world.git",
        "ref": "master"
      }
    },
    "strategy": {
      "type": "Custom",
      "customStrategy": {
        "from": {
          "kind": "ImageStreamTag",
          "name": "buildroot:latest"
        },
        "exposeDockerSocket": true
      }
    },
    "output": {},
    "resources": {}
  },
  "status": {
    "phase": "New"
  }
}

$ oc get builds
NAME                          TYPE      STATUS     POD
test-build-123                Custom    New        test-build-123-build

$ oc get pods
NAME                                READY     REASON       RESTARTS   AGE
```

### Results

Build stays in New state forever, no pods are created.

### Expected results

Build is started and the result is not pushed anywhere.
OR
API call returns an error.

### Context

[OSBS](https://github.com/DBuildService/osbs) uses custom builds where the build image pushes the result into [pulp server](http://www.pulpproject.org/) and discards the built docker image. Currently we need to provide dummy docker repository for `BuildOutput` to work around this issue.

Please note that [API docs](http://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-buildspec) list the `BuildOutput` as optional.

**Comment by soltysh** [comment]
@mmilata you're not supposed to create Build manually, that's the job of BuildController, the reason for that is during that process additional metadata are generated into Build object needed to perform the actual build, and that's why your build is ignored. You need to either use `oc start-build` command or kick it using one of webhook triggers.

**Comment by mmilata** [comment]
I see, I didn't know that. So the supported way of creating builds is to create a BuildConfig first and then trigger it as described [here](https://docs.openshift.org/latest/dev_guide/builds.html)?

**Comment by soltysh** [comment]
Correct. I also recommend reading through our [sample-app](https://github.com/openshift/origin/tree/master/examples/sample-app) which guides through all the necessary steps to run builds and applications in OpenShift. If you feel like it's solved, can you please close this issue also.

**Comment by bparees** [comment]
To be clear, not having an Output is supported.

and if you wanted to create a build directly you should be able to do what you did, but you can just run "oc create -f mybuild.json" instead of using curl.

i'm not sure if there's some other detail that's incorrect in your build definition that causes it to stay in the new state.  i'm guessing your builder imagestreamtag can't be resolved.

**Comment by mmilata** [comment]
@bparees thank you for clarification. The definition should be otherwise correct, if I just add the Output part to the provided JSON the build successfully finishes on my system.

I just tried `oc create` instead of curl and the behavior is the same. I used curl in the example because we are using OpenShift through its REST API.

**Comment by mfojtik** [comment]
@bparees right, and k8s is trying to resolve it forever I guess which makes the Build stay in NEW state. In that case you should check events/logs.

**Comment by soltysh** [comment]
Hmmm interesting, I just did a couple of tests to manually create builds from following (with `oc create -f` command):
```
{
    "kind": "Build",
    "apiVersion": "v1",
    "metadata": {
        "name": "mybuild1",
        "namespace": "test"
    },
    "spec": {
        "serviceAccount": "builder",
        "source": {
            "type": "Git",
            "git": {
                "uri": "git://github.com/openshift/ruby-hello-world.git"
            }
        },
        "strategy": {
            "type": "Source",
            "sourceStrategy": {
                "from": {
                    "kind": "DockerImage",
                    "name": "openshift/ruby-20-centos7:latest"
                }
            }
        }
    }
}
```
and it worked without any problems, iow. the build finished successfully. I've also tested with setting all the `metadata` fields you set - works perfectly. I don't see any other differences between yours and mine other than the namespace I'm using, but I guess you have appropriate access rights to create objects there, in which case it should work normally. 

As for automatic build creation, a couple of things done automatically by our build controller are:
* numbering builds (buildconfigname-1, buildconfigname-2, etc)
* setting labels which help to identify template, buildconfig the build was created from
* setting up secrets (git, docker)
Again I encourage to use the provided start build mechanisms.

**Comment by mmilata** [comment]
Can confirm that the above JSON does not suffer from the reported problem. However when the strategy type is changed to `Custom` and `sourceStrategy` renamed to `customStrategy` then the build seems to get stuck in `New` regardless of the image specified in the `from` object.

**Comment by soltysh** [comment]
We specified image output as optional, but didn't allow that in our custom builder. Fixed in linked issue.

**Comment by mmilata** [comment]
Thank you!

**Comment by mmilata** [comment]
Just tested this with 1.0.3 and the bug seems to be still there. Can you reopen please?

**Comment by bparees** [comment]
@mmilata please open a new issue and provide your buildconfig and imagestream definitions.  i'm not inclined to assume what you're seeing now is the same problem.
