### ISSUE TITLE
graph todos

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3394]
- [x] allow multiple edges between the same nodes with different kinds.  Need this to allow mountable secrets and pull secrets on service accounts
- [x] contains edges to allow the concept of nodes that are contained and only valid in the context of their containers.  Things like `PodSpec`.  It can be part of a pod, an rc spec, a dc spec, or a podtemplate, but all podspecs are subject to the same secret validation.
- [x] add graph validation.  This is needed to ensure the creation of a valid graph.  Things like "a given a node cannot be contained by multiple nodes"
- [x] add synthetic nodes.  This makes it easier to build a graph that has edges to non-existent nodes.  We'll know some information about the node based on other references, but also be aware that pieces are missing.  This is needed to give good status about missing parts of the graph. (imagestream doesn't exist, secret is missing, etc)
- [x] secret/serviceaccount/podspec/rcspec nodes and edges required to determine illegal pod requests.

@ncdc 
@liggitt I'll take this for now
@smarterclayton anything obvious I missed?

**Comment by deads2k** [comment]
done.

**Comment by smarterclayton** [comment]
Looks fine for now.  We can always come back.
