### ISSUE TITLE
`osc start-build` doesn't work under http(s) proxy

### ISSUE THREAD

**Issue by nak3** [openshift/origin#3395]
`git clone` executed here [git.go#L80](https://github.com/openshift/origin/blob/5fecfa3de3b743bd3b8e13101be2bfd8e9ec84ba/Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/git/git.go#L80) doesn't load http(s) proxy setting.

git clone under the proxy needs proxy setting by running `git config --global http.proxy http://proxy.example.com:8080` before `git clone`

**Comment by nak3** [comment]
> git clone under the proxy needs proxy setting by running git config --global http.proxy http://proxy.example.com:8080 before git clone

So, it seems that setting `env` in `sourceStrategy` doesn't work.

~~~
            "sourceStrategy": {
                "from": {
                    "kind": "DockerImage",
                    "name": "registry.access.redhat.com/openshift3_beta/ruby-20-rhel7:latest"
                },
                "env": [
                    {
                        "name": "HTTP_PROXY",
                        "value": "http://localhost:3128"
                    },
                    {
                        "name": "HTTPS_PROXY",
                        "value": "http://localhost:3128"
                    }
                ],
                "incremental": true
            }
~~~

**Comment by bparees** [comment]
as mentioned in the email thread, looks like this needs to be lower case:
https://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy

**Comment by bparees** [comment]
actually that may not fix it since the env variable is not available in the container performing the clone operation.

**Comment by bparees** [comment]
@mfojtik @soltysh fyi.  we might need to add HTTP* and http* to the whitelist of env variables we allow to be set on the builder pod:

https://github.com/openshift/origin/blob/master/pkg/build/controller/strategy/util.go#L20

**Comment by bparees** [comment]
[merge]
