### ISSUE TITLE
transient error handling DeploymentConfig: found previous inflight Deployment for default/docker-...

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3396]
Should this be an event?  What causes this event?

https://app.getsentry.com/red-hat/openshift-3-stg/group/69758277/

```
deploymentconfig.transientError: transient error handling DeploymentConfig: found previous inflight Deployment for default/docker-registry:6 - requeuing
  File "/builddir/build/BUILD/openshift-git-21.5837ae7/_build/src/github.com/openshift/origin/pkg/cmd/util/serviceability/sentry.go", line 61, in CaptureError
  File "/builddir/build/BUILD/openshift-git-21.5837ae7/_build/src/github.com/openshift/origin/pkg/cmd/util/serviceability/panic.go", line 28, in CaptureError.fm
  File "/builddir/build/BUILD/openshift-git-21.5837ae7/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go", line 82, in HandleError
  File "/builddir/build/BUILD/openshift-git-21.5837ae7/_build/src/github.com/openshift/origin/pkg/deploy/controller/deploymentconfig/factory.go", line 78, in func.007
  File "/builddir/build/BUILD/openshift-git-21.5837ae7/_build/src/github.com/openshift/origin/pkg/controller/controller.go", line 141, in Retry
...
(6 additional frame(s) were not displayed)
```

**Comment by smarterclayton** [comment]
@ironcladlou

**Comment by ironcladlou** [comment]
cc @abhgupta 

This message is logged when we get some config update for latestVersion=X when there's already a running deployment for latestVersion <X (the running deployment is considered "in flight"). The in flight deployment should get marked for cancelation, and the config update is re-queued.

Thinking about it now, I think an event makes more sense. We could create and event which explains that we want to make a new deployment for version X, but are still awaiting the cancelation of version [Y, Z, ...].

**Comment by smarterclayton** [comment]
How often would we send that event?  We may be sending too many events right now so I'm somewhat cautious.  If it's low that's ok.

**Comment by ironcladlou** [comment]
Seems like it should only be frequent if there's a lot of triggered churn in a deployment config which would result in a series of deploy/cancel/deploy/cancels. Repeated image updates, somebody making lots of small changes to a config template, etc. With just enough time between the updates to allow a deployment to be kicked off for each change.

**Comment by smarterclayton** [comment]
If we're talking a few per sync cycle I'm ok with an event.  Just wanted to be sure.

**Comment by smarterclayton** [comment]
This is happening an immense amount of times.  We need to figure out why this is happening still.

**Comment by smarterclayton** [comment]
Unless this is fixed by our change to error handling, but need to be sure.

**Comment by ironcladlou** [comment]
Looking back over this, I think the main source of complaint is that we're accomplishing the retries by returning an error to the controller framework, whose retry manager is sending all errors through `HandleError` before dealing with re-queues, etc. Since we might requeue this a lot of times while awaiting cancellation of the in-flight deployment, that means we'll keep producing log messages every on every re-queue, throttled only by the token bucket limiter.

I really don't want to produce a ton of events for this case, and we don't really need to log it more than once if at all. We could introduce a new error type (or repurpose `transientError`) that the retry implementation could ignore for logging. The drawback is that we'd be silently re-queueing the latest deployment. However, I wonder if this is the kind of case that the graph-based reporting should be handling. Based on the current deployment states we could easily generate a reason why the latest deployment isn't yet running (because another one is still going).

Should we just make this particular case silent and address reporting on it via status (etc.) separately?

**Comment by smarterclayton** [comment]
@bparees can you describe how we solved this in builds

On Fri, Jul 17, 2015 at 10:53 AM, Dan Mace <notifications@github.com> wrote:

> Looking back over this, I think the main source of complaint is that we're
> accomplishing the retries by returning an error to the controller
> framework, whose retry manager is sending all errors through HandleError
> before dealing with re-queues, etc. Since we might requeue this a lot of
> times while awaiting cancellation of the in-flight deployment, that means
> we'll keep producing log messages every on every re-queue, throttled only
> by the token bucket limiter.
>
> I really don't want to produce a ton of events for this case, and we don't
> really need to log it more than once if at all. We could introduce a new
> error type (or repurpose transientError) that the retry implementation
> could ignore for logging. The drawback is that we'd be silently re-queueing
> the latest deployment. However, I wonder if this is the kind of case that
> the graph-based reporting should be handling. Based on the current
> deployment states we could easily generate a reason why the latest
> deployment isn't yet running (because another one is still going).
>
> Should we just make this particular case silent and address reporting on
> it via status (etc.) separately?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3396#issuecomment-122300313>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
@smarterclayton @ironcladlou we modified our retry handler implementation to only call HandleError when we were about to give up on an event, not every time we retried it:
https://github.com/openshift/origin/blob/master/pkg/build/controller/factory/factory.go#L45

**Comment by ironcladlou** [comment]
@kargakis you want to pick this one up?

**Comment by kargakis** [comment]
> @kargakis you want to pick this one up?

Sure.
