### ISSUE TITLE
oc get --help Does not specify all things that can be gotten.

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#3407]
Current message is 
` Possible resources include builds, buildConfigs, services, pods, etc. `

This would be more helpful if it listed all things that could be gotten.

**Comment by liggitt** [comment]
I think bash autocompletion is more useful than a full list in help

**Comment by liggitt** [comment]
https://github.com/openshift/origin/pull/3379 updates autocomplete... `oc get <tab><tab>` shows all resources

**Comment by mfojtik** [comment]
@liggitt not everyone has autocomplete and bash, right?
