### ISSUE TITLE
UI shows "STI" as builder strategy

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3409]
Can we double check we're using "Source" in V1 and in the UI

**Comment by spadgett** [comment]
@smarterclayton Where in the UI are you seeing it?

I don't see any references searching under the assets folder. We're probably showing a value unchanged that came from the server. We're still on v1beta3.

**Comment by smarterclayton** [comment]
If so that's fine - this was on the keynote demo so I wanted to double check.  When we go to v1 API that will become Source

**Comment by liggitt** [comment]
Added to https://github.com/openshift/origin/issues/2851 checklist
