### ISSUE TITLE
Rolling deployment tunables

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3413]
We should expand the set of tunables for deployments, including the following:

* time to pause after containers are ready before scaling down old ones
* scale increment (% of units to increment by)
* over scale or under scale (whether to scale down first or up first - whether # replicas is max or min)

Pretty high priority

**Comment by ironcladlou** [comment]
Probably superceded by #2828 but I'll leave it for now.

**Comment by bparees** [comment]
closing based on 2828.
