### ISSUE TITLE
Unify the labels we use for the Docker images and annotations

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#3414]
Following up the email discussion here. The problem is that we are not using the namespaces in our labels consistently across our projects. For example:

* **S2I** is using following pattern: `io.s2i.scripts-url` (which follows the [Docker upstream format](https://docs.docker.com/userguide/labels-custom-metadata/))
* **Origin** is using this pattern: `openshift.io/*` (which seems to be what Kubernetes is using)

There are three proposals. They all assume that we are going to use `openshift` as the top level namespace:

1) `io.openshift.foo.example-something` and `io.openshift.s2i.scripts-url`
2) `openshift.io/foo/exampleSomething` and `openshift.io/s2i/scriptsUrl`
3) `openshift.io/foo/example-something` and `openshift.io/s2i/scripts-url`

We should pick one and stick with it in all projects as then eventually might become the standard API we will document.

**Comment by mfojtik** [comment]
@smarterclayton @bparees @danmcp @liggitt @soltysh PTAL (and please mark this with the `area/compatibility` label ;-)

**Comment by soltysh** [comment]
I'm voting for for 1) since this follows aforementioned docker upstream format and to force using `io.openshift.*` everywhere (including sti).

**Comment by mfojtik** [comment]
@soltysh i'm fine with 1), but we have to follow up with k8s upstream on unifying this with us...

**Comment by liggitt** [comment]
I prefer `openshift.io/...`... reverse dns seems unnecessary and I find it harder to read.
Also, is this referring to docker annotations only, or API object label/annotation keys?

**Comment by liggitt** [comment]
I also think changing the API object label/annotation keys (again) and convincing Kubernetes to change) would be harder and have a wider impact

**Comment by mfojtik** [comment]
@liggitt i doubt they will be for changing this at this stage, so I think we have to follow their schema, so 3) seems like a winner here :)

**Comment by smarterclayton** [comment]
We already discussed it and decided against it.

**Comment by smarterclayton** [comment]
If we're going with a pattern like 3 it should technically be "s2i.openshift.io/some-key".  That's part of the reason upstream went with the Java pattern - because it sorts cleanly.

**Comment by smarterclayton** [comment]
This discussion should only be about labels in docker images.  Kube labels and annotations are locked, we aren't going to change them.  It's only whether we want to match Docker suggested conventions on image annotations.  Kube upstream uses docker suggested labels in the Kubelet (io.foo.bar)

Other than a small API shift, there's not much impact to us picking the a Docker style.

**Comment by bparees** [comment]
why does k8s use docker labels for image labels and a different format for annotations?   [grumble].

But my vote is docker style for docker labels.  which means:
 io.openshift.foo.example-something and io.openshift.s2i.scripts-url

right?

**Comment by smarterclayton** [comment]
> On Jun 24, 2015, at 9:52 AM, Ben Parees <notifications@github.com> wrote:
> 
> why does k8s use docker labels for image labels and a different format for annotations? [grumble].
> 
> But my vote is docker style for docker labels. which means:
> io.openshift.foo.example-something and io.openshift.s2i.scripts-url
> 
> right?
> 
Yes.  I'm slightly in favor of this as well, balanced against the cost to change.  But it's harder to change later.

**Comment by mfojtik** [comment]
@bparees @smarterclayton OK, so I'm going to fix our Docker images to use the Docker labeling schema. I will keep the old labels in the RHEL7 images for backward compatibility.

**Comment by bparees** [comment]
@mfojtik +1

**Comment by bparees** [comment]
this has been fixed, thanks @mfojtik !
