### ISSUE TITLE
no default liveness probe for included builders/streams

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#3417]
With 1.0.0 we performed the following test:

use the nodejs example builder and example application
build/deploy
scale to 2 instances across 2 nodes
shutdown 1 node

the node goes to "notready" status but the pod continues to show alive/running and remains in the service endpoint table.

Since there is no liveness probe  by default, this will never get rectified automatically by openshift.

There are 2 options:

1) since we know the node is "notready" we should reschedule its existing workloads
2) all builders should at least involve some default tcp liveness probe so that the pods get marked dead and rescheduled

**Comment by thoraxe** [comment]
so after closer inspection it looks like one of the pods was *eventually* rescheduled but it took many, many minutes. This seems undesirable on the surface, as the failed pod remained in the service endpoint table which would've resulted in traffic being sent to it for several minutes while it was gone.

**Comment by mfojtik** [comment]
@thoraxe @bparees is this about the builder (the pod running the build) respond to to a healthcheck or the application built using our builder have liveness probe defined?

**Comment by thoraxe** [comment]
This is two-fold:

1) we don't have any default liveness probe for the resulting application "by default"
2) the pod restart on node failure default time is really quite high, which makes #1 more painful

**Comment by bparees** [comment]
moving to deployments then.  I thought this was about having a liveness check on build pods to ensure they were better managed by k8s.

**Comment by bparees** [comment]
@thoraxe i'm still not clear on what you would like to see changed to resolve this.  Are you wanting new-app to define a liveness probe on DCs it creates?  Also on define one in all the templates? 

or are you looking for more fundamentally built in behavior in DCs?

**Comment by thoraxe** [comment]
I guess it would be nice if new-app did that. Because right now you would have to go in after the fact and define one.

Since new-app already has a lot of processing logic, and it's clear it knows which builder it's going to recommend, it probably could also be wired to know how to add a liveness probe to the podtemplate.

Then perhaps allow a user to disable that behavior with `--no-liveness` or something.

Just some thoughts.

Oh, readiness too.

**Comment by thoraxe** [comment]
@smarterclayton this is what we just talked about.

**Comment by smarterclayton** [comment]
@bparees @jwforres hypothetically we need to introduce users to the
concepts of liveness and readiness (maybe in new-app, maybe in status via a
warning), figure out whether our builders can hint to new-app via
annotations about particular readiness checks that apply to their
framework, and include them in describers of the CLI and UI.  Sounds like a
card.

**Comment by bparees** [comment]
https://trello.com/c/EBgIP628/748-generate-liveness-and-readiness-checks-from-new-app
https://trello.com/c/hKx4e0Z1/747-3-add-readiness-and-liveness-checks-to-example-templates

**Comment by smarterclayton** [comment]
Third one - some command or set of commands that make it easy to add a
readiness check.

**Comment by bparees** [comment]
https://trello.com/c/D0SORKDy/749-tooling-to-add-liveness-and-readiness-checks-to-existing-deployment-configs

**Comment by jwforres** [comment]
web console https://trello.com/c/jInibpBk

**Comment by jwforres** [comment]
Whatever we do in new-app we should be consistent in console create from image.  I linked the two stories together in trello.

**Comment by bparees** [comment]
closing this issue since we've amply covered it in trello now (linked above).
