### ISSUE TITLE
JSHint has a build up of issues

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#3423]
I rand JSHint and it reported 258 problems, mostly small things like missing 'use strict', semicolons, unused variables, etc.  These would be easy to resolve, then it may be good to add JSHint as a pre-commit hook.

@liggitt @spadgett

**Comment by liggitt** [comment]
Worth fixing and hooking into build-assets

**Comment by benjaminapetersen** [comment]
I'm going to leave some notes here for items I can't address without further investigation and/or clarification from others.

- [ ] /app/scripts/services/userstore.js 'ttl' is defined but never used.
/app/scripts/services/userstore.js
```javascript 
setUser: function(user, ttl) {
  // TODO: honor ttl
  authLogger.log("MemoryUserStore.setUser", user);
   _user = user;
},
```
