### ISSUE TITLE
openshift/origin-docker-builder with tag v1.0.0 is missing from registry.hub.docker.com

### ISSUE THREAD

**Issue by tcastberg** [openshift/origin#3427]
Getting the following error:
'Failed to pull image "openshift/origin-docker-builder:v1.0.0": Tag v1.0.0 not found in repository docker.io/openshift/origin-docker-builder'
Any chance we can get an update of this image?

**Comment by bparees** [comment]
@smarterclayton any idea how this one got missed?

**Comment by smarterclayton** [comment]
We `set +e` when we push release normally (because docker hub is flaky) but we need to retry during push release.

**Comment by bparees** [comment]
@smarterclayton what's the best way to get this fixed?  want me to check out the v1.0 release, build the image, and push it?

**Comment by bparees** [comment]
it's been pushed now.  thanks @smarterclayton
