### ISSUE TITLE
Create page should display technology logo associated with component if it exists in _openshift-logos-icon

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#3432]
Ruby => .icon-ruby
PHP => .icon-php 
MongoDB => .icon-mongodb
etc...

if non exists then show default icon =>.fa-cubes

![screen shot 2015-06-24 at 1 32 09 pm](https://cloud.githubusercontent.com/assets/1874151/8355497/a1e7f0d4-1b1d-11e5-9fce-ae90e637dafa.png)

**Comment by jwforres** [comment]
@rhamilto would be good to finally fix this while we are working on stuff in this flow
