### ISSUE TITLE
Add label button should be disabled when a label name is already in use.

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#3436]
When adding labels, if a key is already used the key-value pair is simply discarded without notifying the user.  We should probably disable the add button whenever the label name matches & give a error message until the user updates the text.

files relevant:
- `directives/oscKeyValues.js`
- `views/directives/osc-key-values.html`

**Comment by spadgett** [comment]
Fixed by #7158.

**Comment by benjaminapetersen** [comment]
Hmm. apparently 
Fixes issue #3436
doesn't auto close?  Perhaps i need to remove "issue". will look that up.

**Comment by spadgett** [comment]
Yeah just "Fixes #issue-number"
