### ISSUE TITLE
The osc-key-values directive should be refactored into multiple directives

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#3441]
This is a refactor ticket, broken out of a comment I originally wrote on issue [#2881](https://github.com/openshift/origin/issues/2881)

The osc-key-values.html template for the oscKeyValues directive references controllers via ```ng-controller="{controllerName}"```.  This is limiting as it doesn't allow the linking function & controller to interact.  

The primary issue this would aim to solve is allowing the addEntry() function to also reset focus on the first input element.  I'll paste my original comment.

**Comment by benjaminapetersen** [comment]
Original comment:

Thinking about how to get the addEntry() button to focus the osc-key input again once its added the key and cleared the inputs. My initial inclination would be to do this in a directive linking function:

    link: function($scope, $elem, $attrs, ctrl) {
        // ctrl is this directive's controller
        ctrl.addEntry = function() {
            // do work... then:
            $elem.find('.osc-key-input').focus()
        }
    }
This might be a bit tricky since the functions live in a separate controller, the .controller("KeyValuesController" that is being pulled into the directive template via <div ng-controller="KeyValuesController". The hacky way would be to use jQuery from the addEntry() function to just scan the page for the input. The better way is probably to refactor the extra controllers & break this into a couple smaller directives, then do the linking function like above.

**Comment by spadgett** [comment]
This component is being rewritten as part of https://trello.com/c/Oh6Aqc52
