### ISSUE TITLE
Expand flexbox layout utilities

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#3442]
Original comments can be viewed on [this closed pull request](https://github.com/openshift/origin/pull/3421), the initial work done is saved on [this prototype branch](https://github.com/benjaminapetersen/origin/tree/bpeterse/prototype/flex-layout-attrs).

Original concept comments:

I expanded on _flexbox.less a bit, adding some additional utilities for describing layout in html. The additional css is inspired by the layout frameworks in the Angular Material & Polymer projects. Both use attribute selectors for layout (rather than classes) which makes it easier to reason about & change the markup. The idea is something like "attributes for layout, classes for look/feel". Check out the files changed & feel free to share any thoughts. Thanks!

Quick example, simplified to show how flex layout attrs can be used:
```html
<div layout row reverse align-items="center">
  <div flex>flex foo</div>
  <div layout column>
    <div flex grow="2" shrink="2">flex bar</div>
    <div>no flex baz</div>
  </div>
  <div>no flex.</div>
</div>
```
(This pull request is not yet ready, I have a few more items to address, but wanted to get some feedback early. Also, I'll have to update my html formatting before the final, I tend to have aggressively short line lengths.)

For media sizing, something like this is interesting:
```html
<div layout mobile="column" desktop="row">
  <div>nav</div>
  <div flex>content</div>
  <div>other</div>
</div>
```
And use media queries to apply the rules for [mobile="column"], etc. There may be better labels than [mobile] , [tablet], [desktop]... perhaps [layout-sm="column"], [layout-md="row"].

However, this is even lacking.  The overall page layout is helped by media queries (sidebar collapsing into main column on mobile, for example), but really we also want to solve the issue of widgets resizing to the immediate bounding box. A control doesn't really care about how widget the total viewport is, it should only be interested in the real estate it is assigned by its immediate parent.  

Items to address:
- [x] performance hit on css attr selectors
    - performance across selector types is [marginally different](http://benfrain.com/css-performance-revisited-selectors-bloat-expensive-styles/)
- [x] performance on full page flexbox layouts vs floats
    - older flexbox was slower, newer is fast.  perhaps not as fast as other layout methods, but it works harder.  [here](http://updates.html5rocks.com/2013/10/Flexbox-layout-isn-t-slow), [here](http://benfrain.com/css-performance-test-flexbox-v-css-table-fight/) or [here](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing?hl=en)
- [x] browser support for css attrib selectors (IE 10+, etc)
     - browser support [all the way down to IE 7](https://css-tricks.com/attribute-selectors/)
- [x] breakpoints for large scale changes
     - mobile, tablet, desktop, laptop, the standard views are easily supported
- [x] breakpoints for fine grained changes
    - element queries are hard to support in any layout framework at this point, requires some JS
- [ ] mobile complexity
    - unclear....
- [x] others using?
    - [Polymer](https://www.polymer-project.org/0.5/docs/polymer/layout-attrs.html), [Angular Material](https://material.angularjs.org/latest/#/layout/container),  [Foundation](http://foundation.zurb.com/apps/) (Foundation uses classes, not attribs)

**Comment by benjaminapetersen** [comment]
So this ticket has been a good motivator.  I've had a repo I've casually been working on for over a month addressing this in a generic way.  Take a look at [this repo](https://github.com/benjaminapetersen/layout.attrs) to get an idea where it is at currently.  The README.md is a good summary.  It doesn't address all of our issues yet, but it is much more robust than what I previously shared.  

@liggitt @spadgett  @sg00dwin

**Comment by benjaminapetersen** [comment]
Quick update, I'm intrigued by [this repository](https://github.com/tysonmatanich/elementQuery) as a way to further extend the layout attributes idea with element queries.  The quick idea is that element queries allow an element to know when its immediate parent changes size & then update it's internals.  The css feels intuitive:

```css
header[min-width~="500px"][max-width~="800px"] {
    background-color: #eee;
}
```
as it looks like media queries, but is applied right to the element itself, not the browser window.

**Comment by benjaminapetersen** [comment]
As a second option, I have a private repo going experimenting with a custom directive that could be configured with its own breakpoints.  This is a similar idea, allowing the element to know about the space it is in and adjust itself accordingly.  example code:

```html
<foo-element
      element-query
      element-breakpoints="sm:50 md:200 lg:400:default xl:800"
      outline>Foo Element</foo-element>
```
`element-query` is the directive, configured with `element-breakpoints`, which fires an event whenever there is a change in the breakpoint.  `foo-element` would have to `require: 'elementQuery'` to get access to its controller & register a listener, then decide how to respond (add a class? update template? etc.)

Open to thoughts if anyone has a preference!

**Comment by benjaminapetersen** [comment]
Been tinkering with that repo in spare time, updated and [made public here](https://github.com/benjaminapetersen/angular-element-query).  The README clarifies usage.  

@spadgett, I mentioned this yesterday, its open for thoughts!

**Comment by benjaminapetersen** [comment]
@jwforres this is the open ticket mentioned in scrum.  The [layout attribs repo is here](https://github.com/benjaminapetersen/layout.attrs).  I've also been tinkering with the concept of [element queries here](https://github.com/benjaminapetersen/angular-element-query).  

Appreciate your thoughts!

**Comment by benjaminapetersen** [comment]
Quick update, payload for the core components of [layout.attribs](https://github.com/benjaminapetersen/layout.attrs) is 18k, 9k minified.

**Comment by benjaminapetersen** [comment]
@sg00dwin pinging you on this one, since we have been discussing for a while.

**Comment by jwforres** [comment]
@benjaminapetersen should this issue still be open? is there anything else you want to address on it?

**Comment by benjaminapetersen** [comment]
@jwforres nope!  Ill close it.  We've installed it via bower. @sg00dwin and I have an open conversation going around enhancing this as we go.
