### ISSUE TITLE
Pods should line up in a grid on overview page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3446]
All the pods should line up with the same height and width in a grid. They're not perfectly aligned. (I've noticed this more on Firefox.)

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8365511/96feb7a0-1b5b-11e5-841e-38028e34972c.png)

Pods in the last row also expand to fill the space and are wider. They seem more important when they're not.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8365624/5616443c-1b5c-11e5-8ce2-7b6df4be2e7a.png)

/cc @liggitt @sg00dwin @benjaminapetersen

**Comment by spadgett** [comment]
Similar issue with the template catalog now that we use flexbox: the tiles are slightly different widths. Only a problem in Firefox.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8381072/a1bfcc6e-1bf7-11e5-8712-f271a3afd4ea.png)

**Comment by liggitt** [comment]
Is this fixed by your width:100% change?

**Comment by spadgett** [comment]
Unfortunately, no.

**Comment by benjaminapetersen** [comment]
I did some reading, I think the only way to fix is with adjusting the flex-basis.  The example you gave with 6 pods is clearest.  Flex won't evenly distribute rows on its own, it will fill each row before moving on to the next, then stretches everything in the last row.  If we use media queries to set the flex-basis at break points (something like mobile = 150px, tablet = 225px, etc) it sounds like it can be fixed...

**Comment by sg00dwin** [comment]
https://github.com/openshift/origin/pull/3501
this commit fixed the alignment, but the last row of pods will still expand to the container width based on how flex works.

**Comment by sg00dwin** [comment]
@jwforres With the overview rework this can be closed?
