### ISSUE TITLE
origin-haproxy-router v1.0.0 can not be launched

### ISSUE THREAD

**Issue by mistypig** [openshift/origin#3448]
I use this command to deploy a openshift router:
openshift admin router --create --credentials=master-config/openshift-router.kubeconfig

but the router pod cannot started. Then I check the pod logs got this:

I0626 03:36:33.895869       1 router.go:92] Creating a new template router
I0626 03:36:33.896160       1 router.go:93] Router will use test/router service to identify peers
I0626 03:36:33.896201       1 router.go:122] Reading any persisted state
I0626 03:36:33.896286       1 router.go:126] Performing initial commit
E0626 03:36:33.948971       1 router.go:249] Error reloading router: exit status 1
 Reload output: + config_file=/var/lib/haproxy/conf/haproxy.config
+ pid_file=/var/lib/haproxy/run/haproxy.pid
+ old_pid=
+ path_map_file=/var/lib/haproxy/conf/os_http_be.map
+ sort -r /var/lib/haproxy/conf/os_http_be.map -o /var/lib/haproxy/conf/os_http_be.map
+ '[' -f /var/lib/haproxy/run/haproxy.pid ']'
+ '[' -n '' ']'
+ /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid
[WARNING] 176/033633 (13) : Setting tune.ssl.default-dh-param to 1024 by default, if your workload permits it you should set it to at least 2048. Please set a value >= 1024 to make this warning disappear.
[ALERT] 176/033633 (13) : Starting frontend public: cannot bind socket [0.0.0.0:80]
[ALERT] 176/033633 (13) : Starting frontend public_ssl: cannot bind socket [0.0.0.0:443]
F0626 03:36:33.949187       1 router.go:65] exit status 1

so I use netstat command to check the ports 80 and 443 listening by which program:

tcp6       0      0 :::443                  :::*                    LISTEN      6090/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      6099/docker-proxy

it seems that everything is ok, is there some configurations I missed?

**Comment by pweil-** [comment]
@mistypig - you may be using an older version of the router image in conjunction with the latest OpenShift release.  In the 1.0 release of OpenShift containers will run as a non-root user by default.  This error usually indicates that the container was run with a non-root user who does not have permissions to bind to the low ports.  In the most recent image the haproxy executable is given `net_bind_service` capabilities to allow the privilege.  Reference https://github.com/openshift/origin/blob/master/images/router/haproxy/Dockerfile#L20.

Please try repulling and ensure you're running with the latest image.

**Comment by mistypig** [comment]
@pweil- Thank you, I try with the latest image, this error occured again. I don't know is it because I'm using ubuntu to running openshift, i'll change to centos and try again.

**Comment by mistypig** [comment]
@pweil- centos is ok, thank you.

**Comment by Host32** [comment]
Any solution for Ubuntu? Same problem here...
