### ISSUE TITLE
Proposal for additional DNS entries for services

### ISSUE THREAD

**Issue by plakat** [openshift/origin#3451]
We’re currently using the OpenShift builtin DNS-Server for services
communicating with each other, which works fine so far.

Going forward we’d like to use projects as developer sandboxes for
testing their own service implementations, pulling in instances of
services they depend upon. These may in turn depend on other services
and it would be very elegant if it were possible to set up an
environment, where services automatically call the instance that is
running in the same project context, without changing its configuration.
The easiest way I see to accomplish this would be to add another DNS
entry for each service following the pattern

    <servicename>.svc.<projectname>.cluster.local

The currently used layout of

    <servicename>.<projectname>.svc.cluster.local
does not bode well with the default search suffix
`<projectname>.cluster.local` configured in /etc/resolv.conf in the
containers as services would have to be reconfigured to use the project
name -- a potential source of error and an additional step that might
easily be avoided by the additional DNS entry mentioned above…

I can imagine that this extension might be of interest to others as well.

**Comment by liggitt** [comment]
This search suffix is also present in the resolv.conf:

    <projectname>.svc.cluster.local

This allows applications to reference services in their project by name.

**Comment by plakat** [comment]
We're using OpenShift beta 4, so maybe that is a rather new addition and does not show up there as of yet.
The contents of `/etc/resolv.conf` of a container running in a project within our testinstallation are (I replaced meaningless values with their respective descriptions):

    nameserver <ip of openshift master>
    nameserver <ip of local dns 1>
    nameserver <ip of local dns 2>
    search <projectname>.cluster.local cluster.local <domain of the node>

Actually I'd prefer to use a name as `<servicename>.svc.<projectname>.cluster.local`, i.e. having a service namespace within a project to avoid problems with name clashes between services and other components living within domains of the search suffix, but it would definitely help to have that additional suffix available within each container.

**Comment by liggitt** [comment]
The DNS resolution order is from Kubernetes. OpenShift picked up the addition of `.svc.` in https://github.com/openshift/origin/pull/2871

Reworking the DNS names of services would need to be proposed upstream.
