### ISSUE TITLE
oc create -f f.json useless error output

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#3452]
When passing json file with an error (missing } or alike), the output from `oc create` is:

```
[vagrant@openshiftdev origin]$ oc create -f f.json 
error: no objects passed to create
```

But at the same time if I do:
```
[vagrant@openshiftdev origin]$ cat f.json | oc create -f -
invalid character '}' looking for beginning of object key string
```
Than at least I know there's an error.
I'm not complaining here about the actual error, because I know that's an upstream issue, but rather about the difference in almost two identical calls of `oc create`.

That was tested with current master:
```
[vagrant@openshiftdev origin]$ oc version
oc v1.0.0-97-g9d5db12-dirty
kubernetes v0.17.1-804-g496be63
```

**Comment by liggitt** [comment]
@fabianofranz I thought we added validation to file input

**Comment by fabianofranz** [comment]
@liggitt we did - let me investigate what happened.

**Comment by fabianofranz** [comment]
@liggitt fixed by the latest rebase, please close.
