### ISSUE TITLE
Starting build fails in Web Console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3459]
> An error occurred while starting the build.BuildRequest "" is invalid: metadata.name: required value

We're using the v1beta3 OpenShift API. I don't think anything changed in this area in the Web Console, and I see `metadata.name` set in the request.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8383377/ac844f16-1c07-11e5-8773-d08a341660e1.png)

**Comment by spadgett** [comment]
Error response:

```
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "BuildRequest \"\" is invalid: metadata.name: required value",
  "reason": "Invalid",
  "details": {
    "kind": "BuildRequest",
    "causes": [
      {
        "reason": "FieldValueRequired",
        "message": "metadata.name: required value",
        "field": "metadata.name"
      }
    ]
  },
  "code": 422
}
```

**Comment by liggitt** [comment]
@spadgett can you include the full request body
@bparees this a known issue?

**Comment by bparees** [comment]
not known by me, no.

here's the buildrequest validation logic you're tripping over:
	allErrs = append(allErrs, validation.ValidateObjectMeta(&request.ObjectMeta, true, oapi.MinimalNameRequirements).Prefix("metadata")...)

**Comment by liggitt** [comment]
I notice `BuildRequest` is missing from the build conversions file... wonder if that is causing issues

**Comment by spadgett** [comment]
Full request called out in the first screen capture. It's simply

```
{"metadata":{"name":"ruby-sample-build"}}
```

**Comment by liggitt** [comment]
don't we need the kind and api version?

**Comment by spadgett** [comment]
I blame @deads2k

**Comment by liggitt** [comment]
He has a way of finding the problems in everybody else's code.  It's like a really annoying superpower

**Comment by liggitt** [comment]
Also, I'd like to add something to exercise the new project and create build flows in the UI e2e test
