### ISSUE TITLE
Deployment test race condition exists in test-cmd.sh

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3460]
[This test](https://github.com/openshift/origin/blob/master/hack/test-cmd.sh#L560-L565) in `test-cmd.sh` has a race. The `deploy --latest` command will result in the creation of `rc/test-deployment-config-1` with replicas=0 (as the deployment is new). Because the RC exists, control passes on to the pair of `oc scale` commands against the in-progress deployment. Sometimes this works because the deployment beats the scale commands, satisfying the expectations of `oc scale rc test-deployment-config-1 --current-replicas=1 --replicas=5`. Other times, the scale commands come before the deployment, causing the scale to fail because the replica count of 0 doesn't match `--curent-replicas=1`.

The test code should do a stronger check to wait for the deployment to reach 1 replica before proceeding with scale commands.

**Comment by ironcladlou** [comment]
Actually it's more complicated. Deployments launched via test-cmd.sh aren't even working. I think the only reason the 2nd scale is working is because it's racing with `oc scale dc test-deployment-config --replicas=1`, although I thought that was synchronous (and need to verify).

**Comment by liggitt** [comment]
pretty sure test-cmd.sh doesn't actually create any pods, since secret mounts require root to run...

**Comment by ironcladlou** [comment]
I also suspected a race between the scale and the deployment controller, like:

1. `deploy --latest` results in the creation of the deployment, replicaCount=0
2. `oc scale dc test-deployment-config --replicas=1` directly updates the deployment replicaCount=1
3. The deployment controller processing the "New" deployment creates the deployer pod and updates the deployment to "Pending", resetting the replicas to 0
4. `oc scale rc test-deployment-config-1 --current-replicas=1 --replicas=5` failes because it expects replicaCount=1

The problem with this theory is that I'd expect the deployment controller update to fail with a resourceVersion conflict.

There's definitely some weird interaction going on here between these three parts I just haven't put together yet. I'm starting to wonder about the point of this particular test (which is effectively trying to manually scale a failed deployment).
