### ISSUE TITLE
Indicate a deployment is in progress

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3474]
In the console, display empty rcs and also mark rcs as being deployed, failed, etc.

**Comment by liggitt** [comment]
Is there anything that indicates a failed or in progress rc?

**Comment by derekwaynecarr** [comment]
Not on a replication controller, but I thought deployment has a status
since I used it to do pruning operations.

**Comment by smarterclayton** [comment]
It should be a state in an annotation on the rc

On Jun 27, 2015, at 8:38 PM, Derek Carr <notifications@github.com> wrote:

Not on a replication controller, but I thought deployment has a status
since I used it to do pruning operations.

On Saturday, June 27, 2015, Jordan Liggitt <notifications@github.com> wrote:

> Is there anything that indicates a failed or in progress rc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3474#issuecomment-116166732>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3474#issuecomment-116172832>.

**Comment by spadgett** [comment]
Annotation: `openshift.io/deployment.phase`

```
// DeploymentPhase describes the possible states a deployment can be in.
type DeploymentPhase string

const (
	// DeploymentPhaseNew means the deployment has been accepted but not yet acted upon.
	DeploymentPhaseNew DeploymentPhase = "New"
	// DeploymentPhasePending means the deployment been handed over to a deployment strategy,
	// but the strategy has not yet declared the deployment to be running.
	DeploymentPhasePending DeploymentPhase = "Pending"
	// DeploymentPhaseRunning means the deployment strategy has reported the deployment as
	// being in-progress.
	DeploymentPhaseRunning DeploymentPhase = "Running"
	// DeploymentPhaseComplete means the deployment finished without an error.
	DeploymentPhaseComplete DeploymentPhase = "Complete"
	// DeploymentPhaseFailed means the deployment finished with an error.
	DeploymentPhaseFailed DeploymentPhase = "Failed"
)
```

**Comment by spadgett** [comment]
@jwforres fyi, related to your overview changes

**Comment by jwforres** [comment]
Partially fixed by https://github.com/openshift/origin/pull/4726

Need to look at overview
