### ISSUE TITLE
ImageStream tag improvements

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#3484]
If an ImageStream's spec.dockerImageRepository is set, this currently means that we try to import all the tags from the remote repository. There is no ability to specify that only certain tags should be imported.

Here is a list of some things that we could do to improve usability:

- allow users to enable/disable importing on a per-tag basis
- make it easy to refresh status.tags entries for imported/tracking tags, especially cross-stream (e.g. if I have spec.tags[foo].from=otherstream:latest, it would be nice if I could do `oc import-image mystream:foo` and have it update status.tags[foo].items[0] to match the latest in otherstream.)

**Comment by pweil-** [comment]
TODO: needs definition of use cases

**Comment by soltysh** [comment]
> allow users to enable/disable importing on a per-tag basis

should be handled with `reference` introduced in #4853, which when set to `true` will consider a tag as a reference and will not import its metadata. The 2nd is still valid, though.

**Comment by smarterclayton** [comment]
This is fully fixed with scheduled import and the changes to new app import.  Future work to support scheduled import on referenced tags can be a follow on issue if anyone needs it
