### ISSUE TITLE
Allow external customization of help URLs in web console

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#3493]
For locking doc links to versions, or different releases

**Comment by jwforres** [comment]
cc @sosiouxme

**Comment by jwforres** [comment]
@liggitt Should it be a formalized option in the openshift config file or were you thinking it should be a JS extension

@sosiouxme do you have any preference here

**Comment by liggitt** [comment]
Not sure... it's not just the base url... for any given release, there may or may not be specific help topics for all the topics we link... would probably need to be able to provide a base url, specific urls for topics, and a fallback for missing topics

**Comment by sosiouxme** [comment]
We're going to have OSE, AEP, Origin, and eventually Online to consider. I'm not sure the supported versions will have more than one docs site though, at least for the lifetime of v3.

This doesn't feel well-suited to config file options. Can it be a file that's just dropped into the console per product?

**Comment by spadgett** [comment]
@fabianofranz
