### ISSUE TITLE
Do not propagate build labels to build pods

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#3502]
Follow-up from https://github.com/openshift/origin/issues/2295

Adding a single label for selecting a build is ok (though the label should probably be more namespaced than "build"), but we should not be copying all labels from build API objects to their pods. Pods labels are used group pods under services and replication controllers, and copying random labels into builds pods is likely to get them routed to by services (which would be bad) or "managed" by replication controllers (which would also be bad).

**Comment by liggitt** [comment]
cc @bparees @smarterclayton @soltysh

**Comment by liggitt** [comment]
Copy code is in `build/controller/strategy/util.go#getPodLabels`

**Comment by bparees** [comment]
@liggitt thanks.  copying my final comment from the original issue over to here now:

@soltysh I think this needs to:
1) add a new label (openshift.io/build.name)
2) only add that label to build pods and no other labels
3) update the filter logic in our various controllers to use the new label || the old label
4) note that the old label is deprecated ( @smarterclayton how exactly do we do that? )

**Comment by smarterclayton** [comment]
On Jun 29, 2015, at 11:11 PM, Ben Parees <notifications@github.com> wrote:

@liggitt <https://github.com/liggitt> thanks. copying my final comment from
the original issue over to here now:

@soltysh <https://github.com/soltysh> I think this needs to:
1) add a new label (openshift.io/build.name)
2) only add that label to build pods and no other labels
3) update the filter logic in our various controllers to use the new label
|| the old label
4) note that the old label is deprecated ( @smarterclayton
<https://github.com/smarterclayton> how exactly do we do that? )

This issue should be tagged with the compat tag.  We should create a doc in
the root that describes what, when, and how we plan to change.  The when is
post 3.1 / 1.2.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3502#issuecomment-116930536>.

**Comment by smarterclayton** [comment]
We need to remove support for this before I cut 1.0.7

**Comment by bparees** [comment]
Remove support for the old label?

**Comment by smarterclayton** [comment]
Yeah

**Comment by bparees** [comment]
> The when is post 3.1 / 1.2.

so don't you want to cut 1.0.7 *before* we remove this?

**Comment by smarterclayton** [comment]
We announced in 1.0.6 we'd remove it in 1.0.7

**Comment by bparees** [comment]
removing here: https://github.com/openshift/origin/pull/5250
