### ISSUE TITLE
Deployer node selection should be more configurable

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3507]
The node selector assigned to the deployer pod is inherited from the deployment config template. This is a problem when:
1. The deployment's target nodes aren't available, causing the deployment to fail even though the deployment might be schedulable on other nodes.
2. The deployer pod has different resource requirements than the the deployment

There's currently no escape hatch for a user to proceed: either a.) the deployer pod and the deployment template lack a node selector, or b) the deployer pod and the deployment template must share a node selector.

We should consider making this more flexible. Some ideas:
1. Allow the deployer inheritance to be disabled with a boolean on the deployment config
2. Provide an explicit deployer node selector field on the deployment config
3. Both 1 and 2

**Comment by ironcladlou** [comment]
cc @smarterclayton @abhgupta

**Comment by ironcladlou** [comment]
This needs prioritized.

**Comment by kargakis** [comment]
Closing in favor of https://github.com/openshift/origin/issues/13874
