### ISSUE TITLE
Improve UI handling of ImageStreamImage fetches

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#3513]
To get the data required for the overview, pods, and deployments pages, we fetch all ImageStreamImages for all ImageStreams referenced by pod templates. As the number of images grows, this will become a performance problem.

**Comment by jwforres** [comment]
@liggitt did you have an improvement in mind here?

**Comment by liggitt** [comment]
Avoiding fetching all image streams + image stream tags if possible... either an API update to let us do this, or more intelligence on the client side to avoid fetching all tags once we find the one(s) we care about

**Comment by jwforres** [comment]
@liggitt we already only fetch the ones we care about

**Comment by spadgett** [comment]
Anything left to do here?

**Comment by liggitt** [comment]
if we're already doing targeted gets, that's all I was thinking of
