### ISSUE TITLE
Replica count for new deployments should be manually configurable

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3516]
I spoke with a user who encountered the following surprising deployment surprising behavior:

1. Create a deployment config with a template replica count of 1
2. `oc deploy ... --latest`
3. Use `oc edit` to update the deployment config's replica count to 2
4. `oc deploy ... --latest`
5. User expected the new deployment replica count to be 2, but got 1

I had to explain that the template replica count affects *only the initial deployment* and that subsequent replica counts are based on the count of the last completed deployment in order to maintain scaling continuity with what's actually deployed.

I think this reveals a gap: there's no way for the user to express their intent that "the next deployment should have replica count N" other than to scale the current deployment to N to drive the desired replica computation.

In the meantime, we should probably more clearly document the scaling mechanics with regards to the template replica count and existing deployments. I'm opening this issue to discuss how we should support the user's use case, which seems valid: you should probably be able to declare a new deployment replica count without scaling the *current deployment* to that replica count.

**Comment by ironcladlou** [comment]
@smarterclayton @liggitt this needs prioritized.

**Comment by smarterclayton** [comment]
Docs are p1, specifying desired scale count on deploy cli is p2

**Comment by ironcladlou** [comment]
@liggitt please label this.

**Comment by kargakis** [comment]
Add a `--replicas` flag similar to `oc scale` that will scale the new deployment? Make it work only with `--latest`?

**Comment by ironcladlou** [comment]
>Add a --replicas flag similar to oc scale that will scale the new deployment? Make it work only with --latest?

I think this is on the right track, but we'll also need to consider how to actually implement it in the controllers. Right now the config controller will compute the replicas when creating a new deployment. We'd have to provide some means for the user's replica count to be stored for use to override that computation. I haven't thought this through at all yet but just to start a discussion: what if we added the desired annotation to the config as part of the version update? If the annotation is present, it would be used instead of a computed value. We'd have to ensure that gets cleared, too.

**Comment by kargakis** [comment]
It sounds ok, we have to make sure though that those 3 different ways (we are adding the third one now) of the controller assigning the desired replica count to a new deployment are explicit in the code and easy to follow. Maybe a switch statement where the first case is the annotation check of the user overriding with `deploy --replicas=n --latest`, followed by the case of previous existing (completed) deployments, and in the end default to config.Template.ControllerTemplate.Replicas? An utility function that would scan all the previous deployments and filter out all but those which completed would be helpful here.

**Comment by thoraxe** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1250652

**Comment by smarterclayton** [comment]
I have to say that this is really low priority since you can use scale.

**Comment by thoraxe** [comment]
You can't use scale. That's the whole point of the bug. But it's related to this issue.

**Comment by smarterclayton** [comment]
Right I commended in the bug.  This issue is different - changing replicas
during a deployment is not something we are encouraging.  I don't see it as
a high priority issue for now.

On Wed, Aug 5, 2015 at 1:33 PM, Erik M Jacobs <notifications@github.com>
wrote:

> You can't use scale. That's the whole point of the bug. But it's related
> to this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3516#issuecomment-128085069>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by thoraxe** [comment]
OK. I'm with you now. I commented back. Sounds like we're in agreement.

**Comment by ironcladlou** [comment]
Is this a p3 for now?

**Comment by ironcladlou** [comment]
Closing this out and will continue tracking in trello: https://trello.com/c/PigQ4jr1
