### ISSUE TITLE
new-app uses wrong imagestreamtag

### ISSUE THREAD

**Issue by bparees** [openshift/origin#3525]
As reported by a user:

--------------------------------------------------------------------------------------------------------------------------

I encounter some issue when I running the following testing:

$ oc get is php -n openshift
NAME      DOCKER REPO                                               TAGS                                                                                                                     UPDATED
php       ci.dev.openshift.redhat.com:5000/openshift/php-55-rhel7   01a183e,025d0ab,1f72dc8,20a7e1b,285a248,307dde3,3233480,47b21ee,588fce8,9d40c86,a5d3241,aa61796,e055669,fae91d3,latest   3 hours ago

On node's local image, ci.dev.openshift.redhat.com:5000/openshift/php-55-rhel7:latest is already existing.
$ docker images|grep 'ci.dev.openshift.redhat.com:5000/openshift/php-55-rhel7'
ci.dev.openshift.redhat.com:5000/openshift/php-55-rhel7                             latest              1eef6b4537f7        14 hours ago        557.5 MB

$ oc new-app openshift/php~https://github.com/rjleaf/openshift-php-upload-demo
imagestreams/openshift-php-upload-demo
buildconfigs/openshift-php-upload-demo
deploymentconfigs/openshift-php-upload-demo
services/openshift-php-upload-dem
A build was created - you can run `oc start-build openshift-php-upload-demo` to start it.
Service "openshift-php-upload-dem" created at 172.30.45.104 with port mappings 8080.

$ oc log openshift-php-upload-demo-1-build
W0701 19:44:22.119201   14550 cmd.go:144] log is DEPRECATED and will be removed in a future version. Use logs instead.
I0701 07:41:50.965542       1 cfg.go:50] Problem accessing /root/.dockercfg: stat /root/.dockercfg: no such file or directory
I0701 07:41:50.967508       1 sti.go:77] Creating a new S2I builder with build config: "Builder Image:\t\tci.dev.openshift.redhat.com:5000/openshift/php-55-rhel7:a5d3241\nSource:\t\t\thttps://github.com/rjleaf/openshift-php-upload-demo\nOutput Image Tag:\t172.30.222.140:5000/jialiu/openshift-php-upload-demo\nEnvironment:\t\tOPENSHIFT_BUILD_NAMESPACE=jialiu,OPENSHIFT_BUILD_SOURCE=https://github.com/rjleaf/openshift-php-upload-demo,OPENSHIFT_BUILD_NAME=openshift-php-upload-demo-1\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I0701 07:41:51.275212       1 docker.go:187] Pulling image ci.dev.openshift.redhat.com:5000/openshift/php-55-rhel7:a5d3241
I0701 07:42:11.699678       1 docker.go:190] An error was received from the PullImage call: API error (500):  v1 ping attempt failed with error: Get http://ci.dev.openshift.redhat.com:5000/v1/_ping: dial tcp 184.73.182.48:5000: i/o timeout
F0701 07:42:11.699874       1 builder.go:70] Build error: unable to get ci.dev.openshift.redhat.com:5000/openshift/php-55-rhel7:a5d3241

sti build is trying to use downloading openshift/php-55-rhel7:a5d3241, but not openshift/php-55-rhel7:latest

Why it is selecting "a5d3241" tag for build, why not "latest", what is the logic? Is it possible to allow user to use specific tag?

I also tried oc new-app openshift/php:latest~https://github.com/rjleaf/openshift-php-upload-demo, the same behaviour.

------------------------------------------------------------------------------------------------------------------------------------

**Comment by ncdc** [comment]
It actually is an ok tag to pick - here is the list of tags to v1 image ids:

{
    "01a183e": "80775ff5d551ce3a60971188d5aab22d9c5465035c5394ceddc9eac735b2a033",
    "025d0ab": "5226a229b384a7cf960310a5f50e9be67e4e234fc7690016915b0aa1371c8688",
    "1f72dc8": "89cc6f49a4bb4150cf0ed096ee15cd2e0df9c67ad3fa7c414a69a9a55af9a405",
    "20a7e1b": "62a638e37cb3dca038fc0d9957e864c524725b034b44537ef6e1d8558beed335",
    "285a248": "7d9538cfce3e548c63cbbd7c5eb7cc3807f14eb8abd8f5e8e6b4f1b49f1fe5e6",
    "307dde3": "11fad4fc833647fdfc24408f8a19e9b02731bddad1a425830c83195ec941119d",
    "3233480": "0cfe8659c70e70b17866948854ad827caf5efb89e4b9c1e83dc856c69df39e03",
    "47b21ee": "71369735c6b989cba3efc1789e2b3ff46d195919f0d5b8ac6dd99f4657607e44",
    "588fce8": "7591453d4692beed241133c8269a12d2d8688393d73991ebd094babb40b06c99",
    "9d40c86": "2b8583f742ac6c759a342033dceedf360f5e4d7a1c3eef4d073f3ecbb9f492e2",
    "a5d3241": "1eef6b4537f74acaa2ab27d3ed7cf6910eac340248bc20cd08795fe27bbb5443",
    "aa61796": "4fe2fa87fc35ee0af4864a951f8d4c0c53931a321b91483941cc0c60d81aa2ef",
    "e055669": "a6b29ac7c6ec11b3bceae9d1d94e52fe7ec495164e80e05440fa499d80867d7b",
    "fae91d3": "8ea4c54644920a1882030214f5654a1fcb0782d7c15227a5a0991b683360531d",
    "latest": "1eef6b4537f74acaa2ab27d3ed7cf6910eac340248bc20cd08795fe27bbb5443"
}

You'll see that latest corresponds to image id 1eef6b, as does the tag a5d3241.

This is happening because there are multiple tags (latest, a5d3241) that map to the same actual image (1eef6b4537f74acaa2ab27d3ed7cf6910eac340248bc20cd08795fe27bbb5443). When we look up an ImageStreamTag (which is what the build generator does), it grabs the image associated with the tag from etcd (1eef...), and returns the pull spec for it.

$ oc get image/1eef6b4537f74acaa2ab27d3ed7cf6910eac340248bc20cd08795fe27bbb5443
NAME                                                               DOCKER REF
1eef6b4537f74acaa2ab27d3ed7cf6910eac340248bc20cd08795fe27bbb5443   ci.dev.openshift.redhat.com:5000/openshift/php-55-rhel7:a5d3241

An image only has 1 "DOCKER REF", and it's the value where we first saw it, even if there are multiple tags referring to it.

**Comment by ncdc** [comment]
So this isn't a bug with new-app or the build generator. It's a result of how we store images.

**Comment by bparees** [comment]
closing based on the @ncdc's excellent explanation.
