### ISSUE TITLE
Transient deployment trigger errors should be reported via status fields in API

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3526]
Sometimes the ConfigChange trigger fires but does nothing because image stream tags defined on the ImageChange trigger aren't yet available. #3492 describes why the events we currently generate should be removed. This condition isn't really an error that should be logged or reported via events; instead, it's is a reason for a state that the trigger (or possibly the DC itself) is currently in. Some ways this could be represented:

1. The ConfigChange trigger has a status and a message indicating that it's not currently incrementing the new deployment version because image tags aren't yet available
2. The DeploymentConfig status has some message indicating that its ConfigChange trigger is currently ineffective due to the lack of image tag availability

Essentially, the user needs to know why deployment triggers they've defined aren't having an expected effect. The case where image tags are triggered on but not yet populated on image streams appears to be very common, so we should report them in a more clear and useful way.

**Comment by ironcladlou** [comment]
@smarterclayton I don't see this happening in the short term; should it be p3?

**Comment by ironcladlou** [comment]
Turns out this needs to go in ASAP. It's a major usability issue today.

**Comment by ironcladlou** [comment]
@jwforres there's an opportunity here to enhance the console to help users understand why deployment's aren't happening.

**Comment by jwforres** [comment]
@ironcladlou is this similar to what was just done for builds? https://github.com/openshift/origin/pull/4872

**Comment by jwforres** [comment]
helps if i read the full description...  I'll spawn a UI issue and link it.

**Comment by ironcladlou** [comment]
@jwforres for a little more context, here's something I discussed in email:

The output of describe or status or something should be able to show stuff like:

* dc/frontend deploys myimage:latest
* If myimage (or myimage:latest) doesn't exist, warn that the trigger
won't fire right now
* If myimage doesn't exist but there's a build defined that produces
myimage, mention it in context of the deployment (the deployment won't
start until myimage is created; we notice there's a build for myimage.
We also notice that the last build for myimage failed; maybe check
your build)

**Comment by ironcladlou** [comment]
Those are some examples of the type of message that could appear in this field.

**Comment by jwforres** [comment]
Just update the UI issue https://github.com/openshift/origin/issues/4895 when the API changes are in
