### ISSUE TITLE
post-rebase todos

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3537]
- [x] support service account controller master CA content
 - [x] support kubectl patch
 - [x] fix proxier port range `NewProxier` in `node.go`
 - [x] diff all external json types
 - [x] pretty up oc get message back to `[ "$(oc get 2>&1 | grep 'you must provide one or more resources')" ]` from `Required resource not specified`
 - [x] disable skydns metrics: https://github.com/deads2k/origin/commit/84d4f1f855780f8444bfdbdaade83cbe2244cf0a#commitcomment-11981756   https://github.com/deads2k/origin/commit/84d4f1f855780f8444bfdbdaade83cbe2244cf0a#diff-029630314e09bbea89e2343756db1764R36
 - [x] expose proxier port
 - [x] fix new-app port naming.  IANA_SVC_NAME is crazy tight for a name
 - [x] integration test for SA mountable secret enforcement
 - [x] TODO this is the the CA used to verify the master's serving cert for SA controller
 - [x] bump kube godeps: pflag, cobra, github.com/elazarl/go-bindata-assetfs
 - [x] bump github.com/jteeuwen/go-bindata
 - [x]  should also update with output of hack/update-swagger-spec.sh to pick up changes in parameter descriptions

**Comment by liggitt** [comment]
regenerate swagger spec (`hack/update-swagger-spec.sh`)

**Comment by liggitt** [comment]
Ensure we migrate data from the k8s v1 API we shipped in 1.0.0 (see https://github.com/openshift/origin/issues/3331)

**Comment by deads2k** [comment]
individual issues opened and assigned.
