### ISSUE TITLE
Generated name for volumes should be human readable, not uid based

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3541]
oc volume created names with `d3e439d0-2035-11e5-8895-7831c1b76042` - should be human readable.

**Comment by smarterclayton** [comment]
@mfojtik didn't we have human readable names in builds and new-app for this?

**Comment by mfojtik** [comment]
@smarterclayton that is more question for @soltysh or @csrwng but I guess we do generate human readable names for builds now.

**Comment by smarterclayton** [comment]
This is more for the volume names - I believed one of them already did that.

On Thu, Jul 2, 2015 at 7:03 AM, Michal Fojtik <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> that is more question
> for @soltysh <https://github.com/soltysh> or @csrwng
> <https://github.com/csrwng> but I guess we do generate human readable
> names for builds now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3541#issuecomment-117999155>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by soltysh** [comment]
@smarterclayton not really, we're just doing [this](https://github.com/openshift/origin/blob/34402ef8605f6233b560015df65a9dca920fcaec/pkg/generate/app/app.go#L355-L359). If @pravisankar will be redoing that, I'd propose moving that generation code out of `pkg/cmd/cli/cmd/volume.go` and try to merge it with the `pkg/generate`. In the end I'd say we should do all our generation stuff in one package.

**Comment by soltysh** [comment]
And that was @mnagy doing that, actually.

**Comment by soltysh** [comment]
There's `pkg/util/namer/namer.go` we could use for name generation in this case I guess. Thx @mfojtik for pointing to that.

**Comment by mnagy** [comment]
@soltysh the code you referenced uses namer.go :)

**Comment by soltysh** [comment]
@mnagy right, I missed that :wink:
