### ISSUE TITLE
oc deploy should allow the user to view the logs of the latest deployment

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3544]
`oc deploy --logs` should show the logs of the current deployment (if available).  It maybe should support looking at older logs.

**Comment by smarterclayton** [comment]
@fabianofranz @kargakis or @ironcladlou whichever of you guys have time - need to keep in mind the same sorts of problems we have with oc build-logs

**Comment by ironcladlou** [comment]
>@fabianofranz @kargakis or @ironcladlou whichever of you guys have time - need to keep in mind the same sorts of problems we have with oc build-logs

@bparees what problems might @smarterclayton be referring to here?

**Comment by ironcladlou** [comment]
Are we talking about problems with `LocationStreamer` or with build specific stuff?

**Comment by bparees** [comment]
i'm guessing issues about the deployment pod not existing yet, or being removed, eg:
https://github.com/openshift/origin/issues/2541

we have various situation in which you can't get the logs yet because the pod isn't running yet, or it went away for some reason.

**Comment by smarterclayton** [comment]
And the user shouldn't get some crappy error, we have to smooth over that
pain.  Having a rest endpoint specifically for a deployments logs is def
preferred

On Jul 7, 2015, at 6:40 PM, Ben Parees <notifications@github.com> wrote:

i'm guessing issues about the deployment pod not existing yet, or being
removed, eg:
#2541 <https://github.com/openshift/origin/issues/2541>

we have various situation in which you can't get the logs yet because the
pod isn't running yet, or it went away for some reason.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3544#issuecomment-119364770>.

**Comment by soltysh** [comment]
As a side note, I'd suggest having some consistency introducing `oc deploy --logs` where we already have `oc build-logs` or just `oc logs`. My suggestion would be to have `oc deploy-logs` or alike, instead.

**Comment by smarterclayton** [comment]
I'm not sure that build-logs is the right direction in the long term.
Deploy and build are doing slightly different things, and a deployment
belongs to the DC in a different way than build belongs to build config.  A
DC has *at most* one active deployment (barring bugs or other).  That is
not how builds are handled.

On Jul 8, 2015, at 9:50 AM, Maciej Szulik <notifications@github.com> wrote:

As a side note, I'd suggest having some consistency introducing oc deploy
--logs where we already have oc build-logs or just oc logs. My suggestion
would be to have oc deploy-logs or alike, instead.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3544#issuecomment-119585302>.

**Comment by soltysh** [comment]
Makes sense, still for users it's easier to grasps/remember commands if they are similar. I'm not suggesting we should change stick to one or the other, I was rather suggesting to have them similar. It does provide better user experience, imho.

**Comment by smarterclayton** [comment]
It does, unless it forces us to create multiple similar commands that have
different use patterns.  It's probably better in the long run to have a
single logs command, as long as it fits within the framework we need.  But
a user will come into these commands in different circumstances and with
different levels of experience - there is also value in exposing function
in different contexts.

On Jul 8, 2015, at 5:03 PM, Maciej Szulik <notifications@github.com> wrote:

Makes sense, still for users it's easier to grasps/remember commands if
they are similar. I'm not suggesting we should change stick to one or the
other, I was rather suggesting to have them similar. It does provide better
user experience, imho.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3544#issuecomment-119730557>.
