### ISSUE TITLE
new-app warns about emptyDir volumes even when run with -o

### ISSUE THREAD

**Issue by mnagy** [openshift/origin#3547]
```
[vagrant@openshiftdev ~]$ oc new-app openshift/mysql-55-centos7 -o json
NOTICE: Image "mysql-55-centos7" uses an EmptyDir volume. Data in EmptyDir volumes is not persisted across deployments.
{
    "kind": "List",
    "apiVersion": "v1",
[snip]
```

Working on a fix.

**Comment by kargakis** [comment]
cc: @smarterclayton

**Comment by smarterclayton** [comment]
It's not necessarily a bad thing.

On Thu, Jul 2, 2015 at 8:18 AM, Michail Kargakis <notifications@github.com>
wrote:

> cc: @smarterclayton <https://github.com/smarterclayton>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3547#issuecomment-118012290>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by mnagy** [comment]
I think it is, you can't use the resulting json if you pipe to a file or another command. I think it's a lot more reasonable the notice out to stderr. That way users will notice it, but it won't break anything.

**Comment by bparees** [comment]
+1 to stderr

**Comment by smarterclayton** [comment]
It's not a bad thing if it goes to STDERR - but it should have been going
to stderr from the beginning.  We should never print anything informational
to users that is "out of band" that doesn't go to stderr

On Thu, Jul 2, 2015 at 9:44 AM, Ben Parees <notifications@github.com> wrote:

> +1 to stderr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3547#issuecomment-118038002>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by mnagy** [comment]
Agreed. Fixing this in #3548.

**Comment by bparees** [comment]
@mnagy is this fixed?

**Comment by mnagy** [comment]
@bparees waiting for review of #3548.
