### ISSUE TITLE
Postgres persistent template is asking for ReadWriteMany

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3551]
That is bad - it actually only needs ReadWriteOne, and we should not require that (not should the claim binder require ReadWriteMany to select a NFS volume, if that's why this was set).

@bparees @markturansky

**Comment by smarterclayton** [comment]
Also, we need to be clear that what the user ask for and what we give them have to be supported.  A user who asks for a ReadWriteOne volume should *not* have to worry about that volume being given to another of their pods unless they intervene (which I don't believe we do, but want to make sure we're all on the same page).

**Comment by markturansky** [comment]
Regarding your last point, though the volume is capable of ReadWriteMany, it would never be given to any other pod unless they specifically make it so via a ReplicationController with >1 replicas.

Regarding the 1st point, I think there is a gap between what is asked for (RWO) and what is provisioned (RWO+RWX).   Today, the claim exactly matches volumes WRT access modes.  That's why the template claim is asking for all those modes.  The NFS PVs have them all access modes set on the PVs.

It should probably be that a user asks for RWO and gets a volume capable of RWO+RWX.  They would get *more* capability than they asked for, which follows storage.  The user gets at least what they asked for but potentially more.

The NFS PVs can be assigned just the one access mode (RWO) and the Postgres template would be correct.

**Comment by bparees** [comment]
> It should probably be that a user asks for RWO and gets a volume capable of RWO+RWX. They would get more capability than they asked for, which follows storage. The user gets at least what they asked for but potentially more.

@markturansky so what happens today if we update the templates to request RWO?  my interpretation of your comment is that our templates use RWX today because RWO won't work because the underlying volumes don't support RWO?


@mnagy please take a look at this.  our other DB templates do the same thing.

**Comment by markturansky** [comment]
Each volume plugin has hard-coded access modes (PV.GetAccessModes func).  This defines what a volume *can* do.

Each instance of PersistentVolume posted to the API has a set of access modes.  Generally, they should probably match the capabilities of the volume.  *They do not have to*.

An NFS volume, for example, might be exported on the server as read-only.   The plugin is capable of ReadWriteMany, but this particular instance of an NFS volume is only ReadOnlyMany.

You can change the NFS PV to be ReadWriteOnce and leave the Postgres template alone.  The template then would be correct for all the other volumes.

**Comment by smarterclayton** [comment]
Um, postgres should not be readwritemany ever.

On Thu, Jul 2, 2015 at 2:16 PM, Mark Turansky <notifications@github.com>
wrote:

> Each volume plugin has hard-coded access modes (PV.GetAccessModes func).
> This defines what a volume *can* do.
>
> Each instance of PersistentVolume posted to the API has a set of access
> modes. Generally, they should probably match the capabilities of the
> volume. *They do not have to*.
>
> An NFS volume, for example, might be exported on the server as read-only.
> The plugin is capable of ReadWriteMany, but this particular instance of an
> NFS volume is only ReadOnlyMany.
>
> You can change the NFS PV to be ReadWriteOnce and leave the Postgres
> template alone. The template then would be correct for all the other
> volumes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3551#issuecomment-118114475>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by markturansky** [comment]
Excuse me, I wrote that wrong.  I meant the PV should have RWO and the Postgres template, too, that way it (the template) would be correct for all other volumes.

**Comment by smarterclayton** [comment]
You can have two pods running with an RC of 1.  Therefore, you NEVER want
to have an access mode that the platform might confuse as you actually
wanting to allow multi binding.  The platform *must* enforce that a volume
that was requested under Write-One is never given to multiple pods on the
same node, and that the logic in the attacher prefers to fail to attach
rather than risk being attached multiple times.

That behavior - ask for Write-Once should be our default on all our
templates, and the claim binder *can* give you more.  And that is a very
serious issue with expectations that we need to fix ASAP.  That's a p1 to
me w.r.t. volumes, because it means users are writing templates that lie
about what they really want in order to get the behavior they need.

On Thu, Jul 2, 2015 at 1:46 PM, Mark Turansky <notifications@github.com>
wrote:

> Regarding your last point, though the volume is capable of ReadWriteMany,
> it would never be given to any other pod unless they specifically make it
> so via a ReplicationController with >1 replicas.
>
> Regarding the 1st point, I think there is a gap between what is asked for
> (RWO) and what is provisioned (RWO+RWX). Today, the claim exactly matches
> volumes WRT access modes. That's why the template claim is asking for all
> those modes. The NFS PVs have them all access modes set on the PVs.
>
> It should probably be that a user asks for RWO and gets a volume capable
> of RWO+RWX. They would get *more* capability than they asked for, which
> follows storage. The user gets at least what they asked for but potentially
> more.
>
> The NFS PVs can be assigned just the one access mode (RWO) and the
> Postgres template would be correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3551#issuecomment-118107952>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by markturansky** [comment]
I agree an enhancement is needed to give the user more than they expected (a request for RWO can give you a volume with RWO+RWX). I'll make an issue upstream for that.

For this issue, change the PV and Postgres template to just RWO.

**Comment by smarterclayton** [comment]
I'd make it P0 except that's harsh.  But this *must* be fixed before we
ship 3.1, and preferably before 3.0.2

On Thu, Jul 2, 2015 at 2:27 PM, Clayton Coleman <ccoleman@redhat.com> wrote:

> You can have two pods running with an RC of 1.  Therefore, you NEVER want
> to have an access mode that the platform might confuse as you actually
> wanting to allow multi binding.  The platform *must* enforce that a volume
> that was requested under Write-One is never given to multiple pods on the
> same node, and that the logic in the attacher prefers to fail to attach
> rather than risk being attached multiple times.
>
> That behavior - ask for Write-Once should be our default on all our
> templates, and the claim binder *can* give you more.  And that is a very
> serious issue with expectations that we need to fix ASAP.  That's a p1 to
> me w.r.t. volumes, because it means users are writing templates that lie
> about what they really want in order to get the behavior they need.
>
> On Thu, Jul 2, 2015 at 1:46 PM, Mark Turansky <notifications@github.com>
> wrote:
>
>> Regarding your last point, though the volume is capable of ReadWriteMany,
>> it would never be given to any other pod unless they specifically make it
>> so via a ReplicationController with >1 replicas.
>>
>> Regarding the 1st point, I think there is a gap between what is asked for
>> (RWO) and what is provisioned (RWO+RWX). Today, the claim exactly matches
>> volumes WRT access modes. That's why the template claim is asking for all
>> those modes. The NFS PVs have them all access modes set on the PVs.
>>
>> It should probably be that a user asks for RWO and gets a volume capable
>> of RWO+RWX. They would get *more* capability than they asked for, which
>> follows storage. The user gets at least what they asked for but potentially
>> more.
>>
>> The NFS PVs can be assigned just the one access mode (RWO) and the
>> Postgres template would be correct.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/issues/3551#issuecomment-118107952>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by markturansky** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/10683
