### ISSUE TITLE
Document upgrade path and ensure we have a process for keeping it up to date and tested

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3554]
Development process for ensuring migration works as we add new features/code changes.

**Comment by smarterclayton** [comment]
@soltysh UPGRADE.md should be linked here once that merges and then we'll also need the formal doc around upgrades, as well as process.  David has some tests for verifying config doesn't break, we need the equivalent test for storage tests.

**Comment by smarterclayton** [comment]
@danmcp @deads2k @liggitt @bparees @ncdc all should be following and watching this issue

**Comment by sdodson** [comment]
If you evacuate pods that aren't scaled is there a disruption?

**Comment by sdodson** [comment]
Right now, what's our suggested method to update the registry? Ensure that it's using a persistent volume and update the DC to reflect the new image version?

**Comment by ncdc** [comment]
> Right now, what's our suggested method to update the registry? Ensure that it's using a persistent volume and update the DC to reflect the new image version?

Yes. We'll also need a plan for how to deal with images and image streams when we change from using the service IP to using cluster DNS to point to the registry (assuming that happens).

**Comment by smarterclayton** [comment]
Yes, singleton pods would take downtime.

**Comment by sdodson** [comment]
I'm assuming this issue is targeted at developer oriented documentation to be maintained in this repo and/or oriented towards container based installs so I've started drafting some content for openshift-docs in https://github.com/openshift/openshift-docs/pull/731

**Comment by soltysh** [comment]
Per @smarterclayton request linking the [UPGRADE.md](https://github.com/openshift/origin/blob/master/UPGRADE.md) document, which **needs** to be updated by everyone doing api changes in any way.

**Comment by sdodson** [comment]
@danmcp Can you clarify the expectations here? For each point release of OSE I've helped the docs team put together upgrade documentation but it's largely based on my interpretation of UPGRADE.md and undocumented items that I discover when attempting to upgrade. I'm not sure I'm the right person to maintain ugprade documentation in this repo as I won't know the details until after an origin release in most situations.

**Comment by danmcp** [comment]
@sdodson I am not sure what all @smarterclayton intended to accomplish from this issue.  I think we want an upgrade process that is as seamless as possible and automatically tested.  Perhaps that requires someone from platform management or cluster infrastructure to first develop the core of the process.  But I would envision the result of this issue being a set of tests that run on every merge or extended or somewhere in jenkins that continuously validate the upgrade path.

**Comment by soltysh** [comment]
That would mean we would have to introduce yet another testing suite that will cover that UC. I'd create a trello for our team to handle that @pweil- agree?

**Comment by pweil-** [comment]
> That would mean we would have to introduce yet another testing suite that will cover that UC. I'd create a trello for our team to handle that @pweil- agree?

Yes, let's formalize this process.  I just added something to UPGRADE.md so we can use it for testing (new strategies on SCCs) if we don't have another candidate.  Please add the 3.2 label to the card.

**Comment by soltysh** [comment]
Trelloed https://trello.com/c/PkdTa55k/530-test-to-cover-upgrade-path

**Comment by smarterclayton** [comment]
We still haven't solved this but it's not happening for 1.2.

**Comment by stevekuznetsov** [comment]
We've got an automated upgrade test in [`test_pull_request_origin_extended_conformance_install_update`](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/) -- do  we need anything else?

**Comment by sdodson** [comment]
I guess given that test found the unaccounted for new router variable it's good enough for now. We'll still miss new config items that aren't critical or tested but oh well.

**Comment by stevekuznetsov** [comment]
There is nothing stopping us from creating more, varied inventory files and e2e tests for other functionality.
