### ISSUE TITLE
templates should be parameterized for imagestream namespace reference with default value of "openshift"

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#3563]
"we can/should parameterize our templates so that the namespace of the imagestream reference is a parameter with a default value of openshift. that way you can change it to an imagestream in another namespace easily, but by default get working behavior. I don't see this is as a high priority, but it's worth knowing it can be done"

Currently, the S2I user story looks like:

* As a user
* I select a code repository
* And then select a builder image (which may be in the openshift namespace but may be in my own namespace)
* my buildconfiguration includes the correct namespace for the imagestream

However, when using a template, OpenShift will not crawl the openshift namespace when trying to find the imagestream for the buildconfiguration.

This is a somewhat inconsistent user experience, because I do not have to know where the imagestream is when directly using S2I.

It would be more consistent if the buildconfiguration logic on the back-end would check if an IS exists in the openshift namespace *and* the current namespace before deciding that the IS can't be found.

**Comment by bparees** [comment]
in the "create app from source" flow you're telling us what builder image (imagestream) you want to use so we know exactly what namespace it's in because you picked it. 

in the create from template flow, that does not happen so we have no idea what namespace the imagestream is supposed to be in.  And if the template explicilty says the imagestream is supposed to be in namespace FOO, we certainly don't want to go use an imagestream from namespace BAR.

if the template does not declare the namespace for the imagestream, we could consider falling back to 'openshift'.

the other thing that can be done here (as @thoraxe suggested i think) is to update the templates so that the imagestream namespace is a parameter that can be edited.

**Comment by liggitt** [comment]
Letting you select templates or builders from one of multiple namespaces up front is fine (though there shouldn't be anything special about the `openshift` namespace... that will eventually be configurable to let cluster admins choose which namespace(s) to use for "shared" templates/builders).

I don't want the back-end to do "search path"-style lookups on unqualified image stream references... you should be able to look at a build config (or deployment config) API object and know exactly what it points to.

**Comment by liggitt** [comment]
We also can't just pin un-namespaced imagestream refererences within a template to the originating namespace. There are two template-based scenarios:

1. A template defines image streams, build configs, and deployments in an un-namespaced way, so when you instantiate the template in namespace `foo` everything gets created in that namespace and local references resolve correctly
2. A template defines build configs and deployments in an un-namespaced way, pointing at image streams in a shared namespace. The intent is to let the template be instantiated in any namespace and make use of shared image streams. In this case, the template has to specify the namespace of the image stream references (which is what we've done in our templates intended for use in the `openshift` namespace). Allowing the shared namespace to be parameterized in the template would probably be the best way to handle that.

**Comment by bparees** [comment]
> Letting you select templates or builders from one of multiple namespaces up front is fine (though there shouldn't be anything special about the openshift namespace... that will eventually be configurable to let cluster admins choose which namespace(s) to use for "shared" templates/builders).

we already allow you to select templates from any namespace you have access to, right?

> I don't want the back-end to do "search path"-style lookups on unqualified image stream references... you should be able to look at a build config (or deployment config) API object and know exactly what it points to.

agree, when you define a template you should be making a statement about what you consume, having the inputs depend on the user's particular permissions/configuration/etc such that they could get different images feels problematic.

> A template defines image streams, build configs, and deployments in an un-namespaced way, so when you instantiate the template in namespace foo everything gets created in that namespace and local references resolve correctly

+1

> A template defines build configs and deployments in an un-namespaced way, pointing at image streams in a shared namespace. The intent is to let the template be instantiated in any namespace and make use of shared image streams. In this case, the template has to specify the namespace of the image stream references (which is what we've done in our templates intended for use in the openshift namespace). Allowing the shared namespace to be parameterized in the template would probably be the best way to handle that.

+1 and though i haven't tested it, i'm pretty sure you can already parameterize the namespace in the template.  so we could default it to "openshift" but it allow it to be parameterized so you could point elsewhere if you created the necessary imagestreams yourself.

**Comment by liggitt** [comment]
> we already allow you to select templates from any namespace you have access to, right?

`new-app` may, but at the moment, the UI only looks in the current namespace and `openshift`

> i'm pretty sure you can already parameterize the namespace in the template. so we could default it to "openshift" but it allow it to be parameterized so you could point elsewhere if you created the necessary imagestreams yourself

that would also let someone change the default value in just one place in the template if they wanted to use a different shared namespace in their installation

**Comment by bparees** [comment]
> new-app may, but at the moment, the UI only looks in the current namespace and openshift

definitely seems like the UI should present me with all the templates i can potentially see.  Otherwise i have to instantiate a template in the namespace it was defined in (except for the openshift namespace).

**Comment by thoraxe** [comment]
Part of the issue is that the JBoss guys broke the standard paradigm by essentially requiring a template to be used to use their image as a builder.

**Comment by liggitt** [comment]
> definitely seems like the UI should present me with all the templates i can potentially see

Hmm... not sure there's good API support for that

**Comment by bparees** [comment]
@thoraxe so if i can summarize what i think remains here:
1) we can/should parameterize our templates so that the namespace of the imagestream reference is a parameter with a default value of openshift.  that way you can change it to an imagestream in another namespace easily, but by default get working behavior.  I don't see this is as a high priority, but it's worth knowing it can be done

2) web console should present the user with all templates in all projects they can view, not just the current project and openshift project.

Is that an accurate summary of what you want out of this issue?  and if so, can you clarify in the description what you want this issue to solve (either (1) or (2), and open a second issue for the other part since they are unrelated issues?

**Comment by thoraxe** [comment]
Yes I think so. This issue is more related to (1). We can open a separate issue for (2) but (2) is actually related to #3833 which is "fixed" but still isn't particularly clear.

Should I reopen #3833 or open a new one?

**Comment by bparees** [comment]
i'd open a new one for (2)...  i agree it's related, but fundamentally it's a different issue.  If you want to also pick up your fight to make it clearer which project a template is from as part of the new issue for (2), i won't object (because i won't own that issue :) )

**Comment by bparees** [comment]
assigning to @gabemontero as he owns another template update/parameterizing issue already, so maybe he can kill two birds w/ one stone here.

**Comment by liggitt** [comment]
https://github.com/openshift/origin/issues/3901 is already open to improve grouping templates by namespace or indicating the "shared" nature of the ones from the "openshift" namespace. I don't think we would want to show all templates from all namespaces in the create flow for a particular namespace.

**Comment by bparees** [comment]
@liggitt I disagree...  the namespace you're in is where you want to instantiate the template, but it really has nothing to do with where that template is coming from.

**Comment by liggitt** [comment]
so I have access to 11 projects... you would want all templates from all projects to appear when I am creating stuff in project "foo"?

**Comment by bparees** [comment]
yes.  or at least the option to see those things.

**Comment by bparees** [comment]
I would not assume all the templates I want to instantiate will either be owned by me, or owned by someone with permission to put them into the openshift namespace.

**Comment by gabemontero** [comment]
@bparees - hoping to scope the inventory of this change to the following json files under origin's example directory which define templates:

./sample-app/application-template-custombuild.json:  "kind": "Template",
./sample-app/application-template-pullspecbuild.json:  "kind": "Template",
./sample-app/application-template-dockerbuild.json:  "kind": "Template",
./sample-app/application-template-stibuild.json:  "kind": "Template",
./etcd/template.json:  "kind": "Template",
./jenkins/jenkins-persistent-template.json:  "kind": "Template",
./jenkins/jenkins-ephemeral-template.json:  "kind": "Template",
./jenkins/application-template.json:  "kind": "Template",
./zookeeper/template.json:  "kind": "Template",
./wordpress/template/wordpress-mysql.json:  "kind": "Template",
./project-quota/application-template-with-resources.json:  "kind": "Template",
./db-templates/postgresql-persistent-template.json:  "kind": "Template",
./db-templates/postgresql-ephemeral-template.json:  "kind": "Template",
./db-templates/mysql-ephemeral-template.json:  "kind": "Template",
./db-templates/mysql-persistent-template.json:  "kind": "Template",
./db-templates/mongodb-ephemeral-template.json:  "kind": "Template",
./db-templates/mongodb-persistent-template.json:  "kind": "Template",
./storage-examples/gluster-examples/nginx_template/gluster-nginx-template.json:  "kind": "Template",
./quickstarts/django-postgresql.json:  "kind": "Template",
./quickstarts/dancer-mysql.json:  "kind": "Template",
./quickstarts/rails-postgresql.json:  "kind": "Template",
./quickstarts/nodejs-mongodb.json:  "kind": "Template",
./quickstarts/cakephp-mysql.json:  "kind": "Template",
./jenkins-master/jenkins-slave-template.json:  "kind": "Template",
./jenkins-master/jenkins-master-template.json:  "kind": "Template",

Is that acceptable to you?

**Comment by bparees** [comment]
@gabemontero i'd scope it even further:
db-templates
jenkins
jenkins-master
quickstarts (which need to be updated in their upstream repos and then vendored to origin, of course)

we don't need to do this for all our toy examples, just the real first class ones we point users to.

**Comment by gabemontero** [comment]
cool deal

**Comment by gabemontero** [comment]
I think for the templates in jenkins-master, all the ImageStream refs are for ImageStreams created in those templates ... don't think we want to parameterize the namespaces there ... same for the application template in the jenkins dir

**Comment by gabemontero** [comment]
well ... maybe one in the jenkins-slave .... a sample form I've not seen much:

`    {
      "kind": "ImageStream",
      "apiVersion": "v1",
      "metadata": {
        "name": "${IMAGE_STREAM_NAME}"
      },
      "spec": {
        "dockerImageRepository": "openshift/${IMAGE_STREAM_NAME}"
      }
    },
`

**Comment by bparees** [comment]
> I think for the templates in jenkins-master, all the ImageStream refs are for ImageStreams created in those templates ... don't think we want to parameterize the namespaces there

true.

basically it's only the places where we've hardcoded "openshift" today that we need to parameterize.
