### ISSUE TITLE
ImageChange trigger: no way to specify arbitrary ImageStreamTag

### ISSUE THREAD

**Issue by twaugh** [openshift/origin#3565]
For a Custom build strategy, the `from` field isn't necessarily the ImageStreamTag that's useful for ImageChange triggers to watch.

I'd like to request a field `Image` to specify that:

```
{
  "type": "imageChange",
  "imageChange": {
    "Image": {
      "Kind": "ImageStreamTag"
      "Name": "..."
    }
  }
}
```

**Comment by bparees** [comment]
Can you elaborate on your scenario?  Why do you need to run your build when an image other than your custom builder image, has changed?

We actually originally had an implementation that supported this, but it was fairly complex to maintain and document which is why we migrated to the simpler design in which the trigger is directly correlated to the builder image for the buildconfig.

**Comment by twaugh** [comment]
This is for [OSBS](https://github.com/DBuildService/osbs-client). The custom builder image builds an image using the host docker from a Dockerfile that needs to be altered in various ways at build time, and performs post-processing on that image. The Dockerfile comes from a git repository specified in the build environment, so the image that is useful to be the trigger is the one specified in that Dockerfile's FROM line.

**Comment by bparees** [comment]
and you'll have the image referenced in the FROM defined as an ImageStream in openshift?  If we do this, the imagetrigger will still be dependent on seeing an imagestream update (just like the existing imagetriggers)

**Comment by twaugh** [comment]
Yes, that will be taken care of.

**Comment by bparees** [comment]
@csrwng can close this now (feature delivered)?

**Comment by bparees** [comment]
this is delivered, docs here: https://docs.openshift.org/latest/dev_guide/builds.html#image-change-triggers

please reopen if you have any further questions/concerns about the implementation.
