### ISSUE TITLE
Tito tooling is not compatible with tito v0.6.0

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#3570]
Our tito custom builder relied on calling test-setup-specfile.pl which was removed from tito in v0.6.0. Need to update things to address this.

Feel free to assign this to me.

**Comment by sdodson** [comment]
```
$ tito build --test --rpm 
Building package [v0.0.1]
Wrote: /tmp/tito/openshift-git-4229.e23ec53.tar.gz
ERROR: Error running command: test-setup-specfile.pl /tmp/tito/rpmbuild-openshiftlOKPYi/SOURCES/openshift-git-4229.e23ec53/openshift.spec e23ec53 4229 openshift-git-4229.e23ec53 openshift-git-4229.e23ec53.tar.gz

Status code: 32512

Command output: sh: test-setup-specfile.pl: command not found
```

@mbarnes FYI

**Comment by mbarnes** [comment]
Thanks for the heads up.  Looks like we already hacked around it for AE (https://github.com/projectatomic/atomic-enterprise/pull/34) but I'll keep an eye on this.

**Comment by bparees** [comment]
@sdodson i removed the "build" component tag on this since that's intended for the openshit build-related components.

@danmcp if we anticipate more issues like this we might want a component/productization label or something.
