### ISSUE TITLE
Wrong "Documentation" link in Enterprise Web Console

### ISSUE THREAD

**Issue by rjleaf** [openshift/origin#3572]
**Version:** OpenShift Enterprise 3.0

**Issue:**
When I'm in the "Web Console," I see a "Documentation" link in the upper-right corner. This link points to http://docs.openshift.org/latest/welcome/index.html, which is a link to the Origin docs.

This should probably point to https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/ instead.

**Comment by liggitt** [comment]
Tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1233772 and already fixed in the master branch for OSE
