### ISSUE TITLE
[post-rebase-work] EmptyDir upstream pulls

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3577]
@pmorie upstream's 9844 seems to be a conglomeration of various UPSTREAM pulls to origin.  Can you organize the upstream commits to better match 044cd86be18df66a54963dacb60050e4491dbf4e, f4ca5d781da68422c6b9639ce8b4862449b09cfc, 78d612aef16c373c5d8aa871b161ec3d18878abe, 75ae6f1a51c0b9c6c9793686f458aeda6b3edee8, and e12b5952595939c2325858228c4f2eec8990f98a ?

@liggitt please assign

**Comment by liggitt** [comment]
@pmorie this was done, correct? can close?

**Comment by pmorie** [comment]
It's done, yeah
