### ISSUE TITLE
[post-rebase-work] what do we do about changing validation?

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3580]
Validation for fields might change over time.  In this case, it actually happened for the name of a container spec port.  This means that we might have data in etcd that is invalid, so we need to solve two problems:

 1. How do we detect that validation has tightened and made previously correct data invalid?
 1. How do we handle data in etcd that used to be valid, but is now invalid?

@smarterclayton @bparees @danmcp @liggitt

**Comment by smarterclayton** [comment]
Data in etcd can be invalid in specs - it just means subsequent updates by
users will have to correct those.  We probably need before - after tests
between upgrades that run through a suite of data objects to ensure they
are still valid.  However, I doubt we can guarantee we will catch all
problems like that, so we need to have a process and plan in place for
reviewing validation changes.

This probably should be moved to upstream as a discussion.

On Mon, Jul 6, 2015 at 3:49 PM, David Eads <notifications@github.com> wrote:

> Validation for fields might change over time. In this case, it actually
> happened for the name of a container spec port. This means that we might
> have data in etcd that is invalid, so we need to solve two problems:
>
>    1. How do we detect that validation has tightened and made previously
>    correct data invalid?
>    2. How do we handle data in etcd that used to be valid, but is now
>    invalid?
>
> @smarterclayton <https://github.com/smarterclayton> @bparees
> <https://github.com/bparees> @danmcp <https://github.com/danmcp> @liggitt
> <https://github.com/liggitt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3580>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
We've been handling this as, "don't do that for actively managed resources or you end up hotlooping in controllers".
