### ISSUE TITLE
[post-rebase-work] automatically detect API drift

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3584]
Since we shipped a v1 API before v1 was fully baked, we need a way to detect incompatible changes to this API.  This problem can be generalized to detecting whether we've made an API change that is incompatible with a version of the API that we have shipped.

Given access to the current types and the old types, it is possible to build a reflective test that compares some obvious problems like "this json serialization tag is now missing".  Unfortunately, I don't know of a particularly clean way to keep the old types around.

@liggitt @smarterclayton

**Comment by smarterclayton** [comment]
I think we'd have to consider having our tests build multiple versions of
the source (or operating on multiple versions of the source to write out
transformations).  For instance, reflective test that loads the objects and
outputs a list of the fields and outputs to a file for both new and old
version, and then ensures no lines were removed (only added).

On Mon, Jul 6, 2015 at 3:54 PM, David Eads <notifications@github.com> wrote:

> Since we shipped a v1 API before v1 was fully baked, we need a way to
> detect incompatible changes to this API. This problem can be generalized to
> detecting whether we've made an API change that is incompatible with a
> version of the API that we have shipped.
>
> Given access to the current types and the old types, it is possible to
> build a reflective test that compares some obvious problems like "this json
> serialization tag is now missing". Unfortunately, I don't know of a
> particularly clean way to keep the old types around.
>
> @liggitt <https://github.com/liggitt> @smarterclayton
> <https://github.com/smarterclayton>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3584>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Probably also upstream.

On Thu, Jul 16, 2015 at 10:27 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> I think we'd have to consider having our tests build multiple versions of
> the source (or operating on multiple versions of the source to write out
> transformations).  For instance, reflective test that loads the objects and
> outputs a list of the fields and outputs to a file for both new and old
> version, and then ensures no lines were removed (only added).
>
> On Mon, Jul 6, 2015 at 3:54 PM, David Eads <notifications@github.com>
> wrote:
>
>> Since we shipped a v1 API before v1 was fully baked, we need a way to
>> detect incompatible changes to this API. This problem can be generalized to
>> detecting whether we've made an API change that is incompatible with a
>> version of the API that we have shipped.
>>
>> Given access to the current types and the old types, it is possible to
>> build a reflective test that compares some obvious problems like "this json
>> serialization tag is now missing". Unfortunately, I don't know of a
>> particularly clean way to keep the old types around.
>>
>> @liggitt <https://github.com/liggitt> @smarterclayton
>> <https://github.com/smarterclayton>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/issues/3584>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
> I think we'd have to consider having our tests build multiple versions of
> the source (or operating on multiple versions of the source to write out
> transformations).  For instance, reflective test that loads the objects and
> outputs a list of the fields and outputs to a file for both new and old
> version, and then ensures no lines were removed (only added).

I'm ok with this.  We'll have more levels that upstream.  What timeframe do we want this in?

**Comment by smarterclayton** [comment]
Let's open a card but honestly it's not going to get prioritized highly in
3.1.  It should be in our "tech debt" group

On Fri, Jul 17, 2015 at 7:53 AM, David Eads <notifications@github.com>
wrote:

> I think we'd have to consider having our tests build multiple versions of
> the source (or operating on multiple versions of the source to write out
> transformations). For instance, reflective test that loads the objects and
> outputs a list of the fields and outputs to a file for both new and old
> version, and then ensures no lines were removed (only added).
>
> I'm ok with this. We'll have more levels that upstream. What timeframe do
> we want this in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3584#issuecomment-122254913>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
created https://trello.com/c/FgHkDSTL/469-detect-api-drift

**Comment by kargakis** [comment]
Closing in favor of the Trello card
