### ISSUE TITLE
[post-rebase-work] repair help message

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3585]
During the rebase, one of the casualties was the message you get back if you forget to specify a value for `oc get` and related commands.  It used to be [ "$(oc get 2>&1 | grep 'you must provide one or more resources')" ], but now it is "Required resource not specified".  I think the new message is harder to understand.

@liggitt who should we ask to figure out whether we want old or new?

**Comment by liggitt** [comment]
@smarterclayton @fabianofranz opinions on message?

**Comment by fabianofranz** [comment]
The older one sounds better, but nothing too strong. Both seem to work.

**Comment by smarterclayton** [comment]
Let's just try to fix upstream.  I think the issue that changed the message was recent

**Comment by fabianofranz** [comment]
@liggitt this is fixed.
