### ISSUE TITLE
[post-rebase-work] new-app should reconsider naming scheme for IANA_SVC_NAME fields

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3588]
Some fields are now enforced with IANA_SVC_NAME rules, including a 15 character max.  I resolved this in the rebase by hashing the content, but we should probably choose shorter names to start to avoid such harsh hashing.  Either that or convince upstream to loosen restrictions.

@liggitt I think this is @csrwng

**Comment by liggitt** [comment]
if it was just the port names, aren't the names optional?

**Comment by csrwng** [comment]
It is, we can just remove the name

**Comment by deads2k** [comment]
I thought that name was used later on to generate something in the service.

**Comment by csrwng** [comment]
It's used for the service port name... which now that I look at it, doesn't have 'omitempty' although the annotation says it's optional: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L1154

**Comment by liggitt** [comment]
Fixed in https://github.com/openshift/origin/pull/3756 by removing name from container ports, generating shorter name for service ports
