### ISSUE TITLE
[post-rebase-work] disable skydns metrics

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3589]
We should remove our own metrics now that prometheus is the default.  See  https://github.com/deads2k/origin/commit/84d4f1f855780f8444bfdbdaade83cbe2244cf0a#commitcomment-11981756

@smarterclayton  is probably the most familiar with what needs doing.

**Comment by bparees** [comment]
@smarterclayton does this need to go to someone else?  or can we move it to p2?

**Comment by smarterclayton** [comment]
p2

On Wed, Jul 22, 2015 at 4:15 PM, Ben Parees <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> does this need to go
> to someone else? or can we move it to p2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3589#issuecomment-123849454>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift
