### ISSUE TITLE
certs with overlapping issuer/serials being generated

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#3594]
Seen occasionally in test logs:
https://ci.openshift.redhat.com/jenkins/job/devenv_ami/1934/console

curl: (35) You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.

**Comment by smarterclayton** [comment]
Interesting

**Comment by liggitt** [comment]
a CA object holding a mutex gets created within each of the jobs run in parallel... they're not sharing a mutex
