### ISSUE TITLE
[post-rebase-work] Fix commited merge conflicts

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#3598]
These got checked in with merge conflicts:
- [ ] https://github.com/openshift/origin/pull/3038 / https://github.com/openshift/origin/commit/75ae6f1a51c0b9c6c9793686f458aeda6b3edee8#diff-30fb9438eacf8615ca263b8c3a8901fbR67

**Comment by deads2k** [comment]
> These got checked in with merge conflicts:

Test file.  Do we care?

**Comment by pmorie** [comment]
@deads2k It probably doesn't especially matter from a functional standpoint if the conflicts are only in a single test file, but it will continue to be an issue in future rebases until it's resolved.
