### ISSUE TITLE
delete-all has a new flake

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3602]
"Error from server: pods "db-1-deploy" not found"  See this log: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/3520/consoleText

**Comment by ncdc** [comment]
I wonder if we need to specify --ignore-not-found as well. Is this scenario possible:

1. delete cmd uses resource builder to get a list of resources to delete
1. it starts deleting them, eventually deleting the deployment config called `db`
1. the deletion of the deployment config cascades and reaps the `db-1-deploy` pod
1. the resource builder continues deleting, eventually visiting the `db-1-deploy` pod (which is still in its original list)
1. failure

Is that possible?

**Comment by deads2k** [comment]
> Is that possible?

It seems strange that it would be a "sometimes" failure in that case.  I didn't even notice the new flag.  `--ignore-not-found` is new and it used be "true" by default.  That leads to two things:
 1. set `ignore-not-found` @ncdc you want to it since you found it?
 1. Are we going to communicate the behavior change or is minor enough to not need a callout?

**Comment by liggitt** [comment]
Does the fetch occur across resource types prior to deletion of any particular type?

**Comment by liggitt** [comment]
That seems like a bad thing to change the default on

**Comment by ncdc** [comment]
> set ignore-not-found @ncdc you want to it since you found it?

I can if we all agree it's the correct fix.

> Does the fetch occur across resource types prior to deletion of any particular type?

I don't know yet - I'm still tracing through the code.

> That seems like a bad thing to change the default on

+1

**Comment by deads2k** [comment]
> That seems like a bad thing to change the default on

Looks like it changed here: https://github.com/GoogleCloudPlatform/kubernetes/pull/8628.  There's not a lot of detail about why.  I don't think we want to carry patches that make our command defaults different than kube's.

**Comment by deads2k** [comment]
> I can if we all agree it's the correct fix.

I think it's the right fix regardless of default changes.  That's our intent.

**Comment by liggitt** [comment]
Pretty sure whoever changed it didn't think about the implications of defaulting to false in combination with "delete all"

**Comment by liggitt** [comment]
Doesn't look like 8628 introduced the behavior change... looks like a prior PR started failing on NotFound errors

**Comment by ncdc** [comment]
Do we need to add `--ignore-not-found` to every invocation of `oc delete all ...` in hack/test-cmd.sh? We have a lot of them.

**Comment by ncdc** [comment]
@liggitt it was 8628 - see https://github.com/GoogleCloudPlatform/kubernetes/pull/8628/files#diff-7c126b9106a83157d89a336103eb3dbbL110

**Comment by liggitt** [comment]
Oh, you're right

**Comment by deads2k** [comment]
> Do we need to add --ignore-not-found to every invocation of oc delete all ... in hack/test-cmd.sh? 

I would do all of the `oc delete all`s.  I'd leave the `oc delete` to fail, since that's probably the intent.

**Comment by liggitt** [comment]
I don't want to change all the invocations... that's a good sign that compatibility is badly broken

**Comment by deads2k** [comment]
> I don't want to change all the invocations... that's a good sign that compatibility is badly broken

Are we going to carry patches that change kube defaults?  If not, why leave flakes in our merge queue?  If so, well that seems like it would be insanely frustrating for users.

**Comment by liggitt** [comment]
Opened https://github.com/GoogleCloudPlatform/kubernetes/issues/10828
