### ISSUE TITLE
unnamespaced label

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3605]
I stumbled on unnamespaced label in deployments.  Are these used?  https://github.com/openshift/origin/blob/4250e53a4b22ee0d8a0b56358f140c6441485fc3/pkg/deploy/api/types.go#L227-L234

@ironcladlou

**Comment by ironcladlou** [comment]
Both those unnamespaced labels used for the ReplicationController.Selector of the deployment.

**Comment by smarterclayton** [comment]
Probably should be namespaced.   Unlike builds its more dangerous to change this without an OR label selector

**Comment by kargakis** [comment]
Same fix as https://github.com/openshift/origin/pull/5733 for now.
