### ISSUE TITLE
"Routing traffic on" message no longer shows IP in web console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3610]
![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8548764/d0491720-2494-11e5-8917-fb7589539e50.png)

**Comment by liggitt** [comment]
@spadgett can you see if the API value has changed? The UI might need to handle empty values as well... the API docs possible values as "None", "", or a literal IP

**Comment by spadgett** [comment]
The property is the same, but it's coming back as `""` now. It's not clear to me what that means.

```
	// PortalIP is usually assigned by the master.  If specified by the user
	// we will try to respect it or else fail the request.  This field can
	// not be changed by updates.
	// Valid values are None, empty string (""), or a valid IP address
	// None can be specified for headless services when proxying is not required
	PortalIP string `json:"portalIP,omitempty description: IP address of the service; usually assigned by the system; if specified, it will be allocated to the service if unused, and creation of the service will fail otherwise; cannot be updated; 'None' can be specified for a headless service when proxying is not required"`
```

**Comment by spadgett** [comment]
I'm only seeing this for projects I populated before rebasing.

**Comment by jhadvig** [comment]
@spadgett me too

**Comment by spadgett** [comment]
I have a change locally to remove the "on ..." if `service.spec.portalIP` is `""`, but it's not clear to me it's the right fix. Might need to update k8s-object-describer, too.

**Comment by liggitt** [comment]
an empty string is valid, but I'm more concerned that the rebase may have caused services that previously got an IP to not get one... @smarterclayton did something change with services recently that would make them no longer get IP addresses?

**Comment by liggitt** [comment]
Ah, nm... it's the portalIP -> clusterIP rename in v1 we picked up with the rebase. https://github.com/openshift/origin/pull/3592 will fix that so we migrate data from our serialized pre-release v1 objects

**Comment by liggitt** [comment]
We should fix the UI to hide the "routing traffic" text when the portalIP field is empty, though

**Comment by spadgett** [comment]
Will probably wait for #3561 to get merged. The dash causes a problem when portalIP is empty, and 3561 removes it.

**Comment by smarterclayton** [comment]
We still need to do the better presentation of all the port / ip / exposure
stuff.  Need to probably get a design sorted out soon because this is a big
confusion point

On Jul 7, 2015, at 1:23 PM, Sam Padgett <notifications@github.com> wrote:

Will probably wait for #3561 <https://github.com/openshift/origin/pull/3561>
to get merged. The dash causes a problem when portalIP is empty, and 3561
removes it.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3610#issuecomment-119274854>.
