### ISSUE TITLE
docker push times out via service

### ISSUE THREAD

**Issue by craigmunro** [openshift/origin#3612]
I have a problem pushing to the docker registry hosted in OpenShift.  I first noticed it when doing an S2I build but I can reproduce it as follows:

I have a registry:
```
$ oc get se -n default
NAME              LABELS                                    SELECTOR                  IP(S)           PORT(S)
docker-registry   docker-registry=default                   docker-registry=default   172.30.53.207   5000/TCP
```
Pushes to this registry always hang:
```
$ docker push 172.30.53.207:5000/default/hello-openshift
The push refers to a repository [172.30.53.207:5000/default/hello-openshift] (len: 1)
43a576a8a7db: Image already exists
d9c4df52e735: Pushing [=================>                                 ] 589.8 kB/1.66 MB
```

Eventually I get:
```
d9c4df52e735: Image push failed
FATA[0929] Error pushing to registry: Put http://172.30.53.207:5000/v2/default/hello-openshift/blobs/uploads/0979a6d5-7e28-4d5d-a2f2-40af3497d433?_state=vOnhshHiTMeIpDxlxibiWTmdi2_r5vDrQitCcFq3hh57Ik5hbWUiOiJkZWZhdWx0L2hlbGxvLW9wZW5zaGlmdCIsIlVVSUQiOiIwOTc5YTZkNS03ZTI4LTRkNWQtYTJmMi00MGFmMzQ5N2Q0MzMiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTUtMDctMDdUMTQ6NTk6MDEuNjcyMjQ5Mjg0WiJ9&digest=sha256%3A9fdfbd3f3bb613e64e214875e6e5e9da20913186a458be52a6b581671474892c: write tcp 172.30.53.207:5000: connection timed out
```

But I can successfully push if I avoid the service and hit the registry directly:
```
$ iptables-save | grep registry
-A KUBE-PORTALS-CONTAINER -d 172.30.53.207/32 -p tcp -m comment --comment "default/docker-registry:" -m tcp --dport 5000 -j REDIRECT --to-ports 33484
-A KUBE-PORTALS-HOST -d 172.30.53.207/32 -p tcp -m comment --comment "default/docker-registry:" -m tcp --dport 5000 -j DNAT --to-destination 11.191.98.134:33484
```
```
$ docker push 11.191.98.134:33484/default/hello-openshift
The push refers to a repository [11.191.98.134:33484/default/hello-openshift] (len: 1)
43a576a8a7db: Image already exists
d9c4df52e735: Image successfully pushed
369dabcb8388: Image successfully pushed
Digest: sha256:3e3cb64901486993c1720abebf702ec71fcad9c8faf706abb6f9cb2c4f775d41
```

I don't have direct internet access so I have configured a proxy.

I have RHEL 7.1 boxes with the following versions:
```
$ oc version
oc v3.0.0.1-5-g279b678
kubernetes v0.17.1-804-g496be63
$  docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64
$ docker images
REPOSITORY                                                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry.access.redhat.com/openshift3/ose-docker-registry   v3.0.0.1            8d589cec84a6        7 days ago          312.8 MB
```

Any ideas?

**Comment by ncdc** [comment]
Are these libvirt VMs?

**Comment by craigmunro** [comment]
They're certainly KVMs. Can confirm tomorrow if they're using libvirt.

**Comment by mrunalp** [comment]
What network driver is in use? (Is it virtio)

**Comment by craigmunro** [comment]
They are using libvirt for management with a bridged network.  I've put the full domain xml here: https://gist.github.com/craigmunro/7aea54885656a9703f4b

**Comment by jim-minter** [comment]
I'm getting a very similar issue.  Docker pushes from inside the VM to OpenShift's docker registry on the same host via its Kubernetes service IP:5000 sometimes just hang.

```
# docker push 172.30.124.142:5000/demo/eap-openshift:latest
The push refers to a repository [172.30.124.142:5000/demo/eap-openshift] (len: 1)
d6860bcf975f: Image already exists 
49691d3538fc: Image successfully pushed 
85765d60ad46: Buffering to Disk 
```

For me, the output of netstat is diagnostic:
```
# netstat -atn | grep ESTABLISHED | grep 5000
tcp        0 416776 192.168.122.93:38222    172.30.124.142:5000     ESTABLISHED
```

To me, the 416776 figure indicates that the docker process has filled its network write buffer, and that the other end is not receiving bytes.

Via strace, it looks like the openshift node proxy accepts the incoming TCP connection and makes the outgoing connection OK, but doesn't seem to receive an epoll event to indicate that data is there to proxy on to the remote daemon.

This is odd, because some connections get through, and some don't.  I think I've also seen connections start, then hang.

@craigmunro is this similar for you, or should I stop spamming your issue and open my own? :)  Do you see the same thing with netstat on the host where you're pushing from?

**Comment by craigmunro** [comment]
Hi @jim-minter !

Yes, very similar for me:
```
# netstat -atn | grep ESTABLISHED | grep 5000
tcp        0 402784 11.191.98.134:40191     172.30.53.207:5000      ESTABLISHED
```

**Comment by jim-minter** [comment]
This is very odd.  See https://gist.github.com/jim-minter/f2bcc293225cbd21de80 for an strace of the node process accepting the incoming connection from docker, making the external one, making a speculative read on both FDs, and then going no further.  It'd be fine, BUT for the fact that actually I think there's data waiting to be read on FD 26 and an EPOLLIN event is never received from the kernel by golang.

At the same time as running the strace, here's the netstat:
```
# netstat -atn | grep ESTABLISHED | grep 5000
tcp        0    301 192.168.122.93:41264    172.30.124.142:5000     ESTABLISHED
```

I think that shows there's data waiting on the FD - the port number matches the strace.  How come it's only us getting this error - can others reproduce?

Craig and I are both running independent setups but both under KVM - don't see how virtualisation could be a contributing factor though?

**Comment by ncdc** [comment]
We've seen this under kvm/libvirt when not using the virtio driver. @mrunalp or @rajatchopra might have some more info.

**Comment by jim-minter** [comment]
I /am/ using virtio, not that I see that this should make a difference: all of my testing is inside one VM - from the VM's context, this isn't even hitting the network.

**Comment by jim-minter** [comment]
I've written a reproducer for this bug in Python at https://gist.github.com/jim-minter/ea17aaec8d81f990a1b0  . This is beginning to look very much like a kernel bug to me.  I'm wondering what it is about the environment that is causing it to be triggered.

**Comment by jim-minter** [comment]
Reproducer notes: run ```python testcase.py $IP_OF_eth0```.  Expected behaviour: loop forever.  Seen behaviour: hang on reading data, missing EPOLLIN event.

**Comment by jim-minter** [comment]
I'm going to continue my monologue :)

This is some sort of Qemu or KVM issue - I don't know that it's specifically virtio, but the way the external network is set up really does affect the behaviour even when the traffic is in-VM only.  Given that the issue is replicable in python, I think this is conclusively not an OpenShift bug.

I concur that with @craigmunro 's network domain xml below, it doesn't work for me:
```
    <interface type='bridge'>
      <mac address='54:52:00:a0:5f:e8'/>
      <source bridge='br0'/>
      <target dev='vnet10'/>
    </interface>
```

This alternative stanza, however, does work for me:
```
    <interface type='network'>
      <mac address='52:54:00:31:7e:a5'/>
      <source network='default'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </interface>
```

I'm not quite sure what the specific difference is.

@craigmunro , if you want SA help sorting this out next week, please get in touch via e-mail.

**Comment by craigmunro** [comment]
Switching to the virtio driver has resolved the issue.

```
    <interface type='bridge'>
      <mac address='54:52:00:bf:62:86'/>
      <source bridge='br0'/>
      <target dev='vnet2'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
```

@jim-minter I'll try and raise a support case for the underlying issue but it will be after next week.

**Comment by ivanthelad** [comment]
@jim-minter  did you ever opens a support case for this?

**Comment by jim-minter** [comment]
@ivanthelad case 01481562, but I haven't had a proper chance to follow it up :(

**Comment by ivanthelad** [comment]
i know that feeling ;)
Thx

**Comment by Tebro** [comment]
This is still a thing, thankfully Google led me here and my cluster now has a working registry.
