### ISSUE TITLE
Container all-in-one can't build ruby sample-app

### ISSUE THREAD

**Issue by flozanorht** [openshift/origin#3613]
As the documentation says using the container image would be the easiest way to start using OpenShift Origin 1.0 / OpenShift Enterprise 3.0 I decided to try this way. So i setup a KVM VM with RHEL7, installed docker from Red Hat repos and begin with OpenShift install.

I must say, documentation is somewhat fragmented. I was following / merging instructions from:
- https://github.com/openshift/origin/
- https://docs.openshift.org/latest/admin_guide/install/prerequisites.html
- https://github.com/openshift/origin/blob/master/examples/sample-app/container-setup.md

I installed the recommended packages, configured the insecure registry into docker, disabled NetworkManager and firealld. Then I configured no DNS, using just 8.8.8.8 and /etc/hosts for the VM hostname and www.example.com. I configured no docker storage, using the default loopback storage from docker. I also pre-pulled images.

It started with docker pull for the origin image, then started the origin container using the biggest command-line from all those docs. It looked to me there was no need to configure KUBECONFIG and CURL_CA_BUNDLE. Then started/created the internal openshift docker registy. 

So far so good. I can oc status, oc login, oc new-project and access the web console.

Some docs say I should start the registry with --create, others miss this option. It made no difference in my setup. Anyway "oc describe service docker-registry" showed the expected output. I could even curl the registry.

Problems started with creating the sample ruby app:

$ oc new-app -f
https://raw.githubusercontent.com/openshift/origin/master/examples/sample-app/application-template-stibuild.json

The database pod starts fine, but the frontend pod doesn't, because if failed at build. I tried rebuild it a few times with no success.

Logs show the resulting image can't be pushed to the internal registry:

$ osc build-logs ruby-sample-build-1
...
I0702 18:46:01.979495       1 sti.go:131] Using provided push secret for
pushing 172.30.46.199:5000/test/origin-ruby-sample image
I0702 18:46:01.979516       1 sti.go:134] Pushing
172.30.46.199:5000/test/origin-ruby-sample image ...
E0702 18:46:05.886696       1 dockerutil.go:50] push for image
172.30.46.199:5000/test/origin-ruby-sample failed, will retry in 10s ...
E0702 18:46:18.387417       1 dockerutil.go:50] push for image
172.30.46.199:5000/test/origin-ruby-sample failed, will retry in 10s ...
F0702 18:46:31.923328       1 builder.go:70] Build error: Failed to push
image: Error pushing to registry: Server error: unexpected 500 response
status trying to initiate upload of test/origin-ruby-sample

Logs from the registry pod, but they give no clue about what's wrong with the registry:

[root@teste-ose3 ~]# docker ps
CONTAINER ID        IMAGE  
COMMAND                CREATED             STATUS  
PORTS               NAMES
eca0f7f1fa92        openshift/mysql-55-centos7:latest        "run-mysqld.sh mysql   14 minutes ago      Up 14
minutes                          k8s_ruby-helloworld-database.4b02d161_database-1-rbsrc_test_762ded54-2111-11e5-85df-52540061c0ba_242b8ae0  
9654ead88d06        openshift/origin-pod:v1.0.1              "/pod"                 14 minutes ago      Up 14
minutes                          k8s_POD.b1d7e54c_database-1-rbsrc_test_762ded54-2111-11e5-85df-52540061c0ba_6abde4b9  
bf05783ab89c        openshift/origin-docker-registry:v1.0.1   "/bin/sh
-c 'REGISTR   19 minutes ago      Up 19 minutes                          k8s_registry.f54002f1_docker-registry-1-a4j2l_default_dcad7d19-2110-11e5-85df-52540061c0ba_b0387f67  
c4babec386c1        openshift/origin-pod:v1.0.1              "/pod"                 19 minutes ago      Up 19
minutes                          k8s_POD.a670e545_docker-registry-1-a4j2l_default_dcad7d19-2110-11e5-85df-52540061c0ba_a0967787  
9db36d7f08bf        openshift/origin:latest                  "/usr/bin/openshift    22 minutes ago      Up 22 minutes                          origin                                                                                                     

[root@teste-ose3 ~]# docker logs bf05783ab89c
...
time="2015-07-02T23:26:12Z" level=error msg="error authorizing context:
authorization header with basic token required"
http.request.host="172.30.251.229:5000"
http.request.id=d3b50c5d-6a40-4d46-8913-c010b8cc69f3
http.request.method=GET http.request.remoteaddr="172.17.42.1:49115"
http.request.uri="/v2/" http.request.useragent="docker/1.6.2 go/go1.4.2
kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"
instance.id=2e73c4f0-7e82-4638-b4bb-b0640e51f30c
172.17.42.1 - - [02/Jul/2015:23:26:12 +0000] "GET /v2/ HTTP/1.1" 401 114
"" "docker/1.6.2 go/go1.4.2 kernel/3.10.0-229.el7.x86_64 os/linux
arch/amd64"
time="2015-07-02T23:26:12Z" level=info msg="response completed"
http.request.host="172.30.251.229:5000"
http.request.id=d3b50c5d-6a40-4d46-8913-c010b8cc69f3
http.request.method=GET http.request.remoteaddr="172.17.42.1:49115"
http.request.uri="/v2/" http.request.useragent="docker/1.6.2 go/go1.4.2
kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"
http.response.contenttype="application/json; charset=utf-8"
http.response.duration=1.306566ms http.response.written=0
instance.id=2e73c4f0-7e82-4638-b4bb-b0640e51f30c
time="2015-07-02T23:26:15Z" level=debug msg="authorizing request"
http.request.host="172.30.251.229:5000"
http.request.id=f9fee7dd-09c5-4309-b233-75fa1fb9a35e
http.request.method=POST http.request.remoteaddr="172.17.42.1:49122"
http.request.uri="/v2/test/origin-ruby-sample/blobs/uploads/"
http.request.useragent="docker/1.6.2 go/go1.4.2
kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"
instance.id=2e73c4f0-7e82-4638-b4bb-b0640e51f30c
vars.name="test/origin-ruby-sample"
time="2015-07-02T23:26:15Z" level=debug msg="OpenShift auth: checking
for access to repository:test/origin-ruby-sample:pull"
time="2015-07-02T23:26:15Z" level=debug msg="OpenShift auth: checking
for access to repository:test/origin-ruby-sample:push"
time="2015-07-02T23:26:15Z" level=debug msg="(_layerStore).Upload"
http.request.host="172.30.251.229:5000"
http.request.id=f9fee7dd-09c5-4309-b233-75fa1fb9a35e
http.request.method=POST http.request.remoteaddr="172.17.42.1:49122"
http.request.uri="/v2/test/origin-ruby-sample/blobs/uploads/"
http.request.useragent="docker/1.6.2 go/go1.4.2
kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"
instance.id=2e73c4f0-7e82-4638-b4bb-b0640e51f30c
vars.name="test/origin-ruby-sample"
time="2015-07-02T23:26:15Z" level=info msg=Base.PutContent
trace.duration=134.7µs
trace.file="/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/distribution/registry/storage/driver/base/base.go"
trace.func="github.com/docker/distribution/registry/storage/driver/base.(_Base).PutContent"
trace.id=2d195e92-8337-4115-9329-337e3b658930 trace.line=67
time="2015-07-02T23:26:15Z" level=info msg="response completed"
http.request.host="172.30.251.229:5000"
http.request.id=f9fee7dd-09c5-4309-b233-75fa1fb9a35e http.request.mey
thod=POST http.request.remoteaddr="172.17.42.1:49122"
http.request.uri="/v2/test/origin-ruby-sample/blobs/uploads/"
http.request.useragent="docker/1.6.2 go/go1.4.2
kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"
http.response.contenttype="application/json; charset=utf-8"
http.response.duration=150.272569ms http.response.written=0
instance.id=2e73c4f0-7e82-4638-b4bb-b0640e51f30c
172.17.42.1 - - [02/Jul/2015:23:26:15 +0000] "POST
/v2/test/origin-ruby-sample/blobs/uploads/ HTTP/1.1" 500 111 ""
"docker/1.6.2 go/go1.4.2 kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"

I found Issue #2740 which looks very similar to my problems. So maybe the all-in-one container is not working for the sample ruby app? Just for it, or it won't work for any app that requires a build?

**Comment by ncdc** [comment]
What is the output of `sudo ls -laZ /var/lib/openshift/openshift.local.volumes/`?

**Comment by flozanorht** [comment]
from the VM (not the container)
[root@teste-ose3 ~]# ls -lZ /var/lib/openshift/openshift.local.volumes/
drwxr-x---. root root system_u:object_r:docker_var_lib_t:s0 plugins
drwxr-x---. root root system_u:object_r:docker_var_lib_t:s0 pods

**Comment by ncdc** [comment]
That's the problem. You need the volume dir to have a different label.
svirt_...something (I'm afk now and don't remember off the top of my head but
can get it to you later today.)

**Comment by flozanorht** [comment]
Docs tell to rm -rf /var/lib/openshift/* to clean up if something goes wrong... probably it was this lost the label.

Did a restorecon -Rv /var/lib/openshift and now

[root@teste-ose3 ~]# ls -lZ /var/lib/openshift/openshift.local.volumes/
drwxr-x---. root root system_u:object_r:openshift_var_lib_t:s0 plugins
drwxr-x---. root root system_u:object_r:openshift_var_lib_t:s0 pods

**Comment by ncdc** [comment]
It needs to be svirt_sandbox_file_t - the current policy is still built for
OpenShift v2.

**Comment by flozanorht** [comment]
Deleting everything under /var/lib/openshift and later changing its context to svirt_sandbox_file_t solved the issue, thanks a lot!

Should't this be documented in https://github.com/openshift/origin/blob/master/examples/sample-app/container-setup.md ?

So the registry container/pod was getting permission denied errors from selinux... how can I find those erros from openshift or docker logs? Note the logs I got showed only an HTTP 500 error, no more details.

As an aside: to clean /var/lib/openshift I had to reboot my RHEL 7.1 vm. I had already stopped and deleted all docker containers, and also stopped the docker service. Even then it was impossible to delete “/var/lib/openshift/openshift.local.volumes/pods/181ac933-25a7-11e5-89d8-52540061c0ba/volumes/kubernetes.io~secret/deployer-token-t7o5v because it was busy. I could not find who has this opened using lsof.

**Comment by smarterclayton** [comment]
@bparees do we need container-setup now?

**Comment by bparees** [comment]
Probably not as something separate from the main openshift readme/hacking/contributing readme, no.   But clearly we need to take another pass at our general getting started docs. And fold any useful content from the sample app container doc into there.

**Comment by smarterclayton** [comment]
Closing due to age.
