### ISSUE TITLE
Run upstream unit tests

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#3616]
We should consider how best to run the upstream unit tests.  During the last rebase, there was a conflict in a test file that was merged (see https://github.com/openshift/origin/issues/3598).  Especially when we carry upstream patches, it's important to ensure that the unit tests for the upstream code are solvent.

A couple options:

1.  Make a dedicated test script to run the upstream unit tests
2.  Make it an option to `hack/test-go.sh` to run the upstream unit tests

@ncdc @liggitt @derekwaynecarr

**Comment by stevekuznetsov** [comment]
Do we have a strategy as to how to determine which upstream packages we run tests for?

**Comment by pmorie** [comment]
we should just run them all IMO

**Comment by kargakis** [comment]
We run them now, don't we?

**Comment by stevekuznetsov** [comment]
No, for instance we do not run the tests in `go-ldap/ldap`. That package has some weird double-source going on where it is also hosted at `gopkg.in/ldap.v2`, and one of their tests imports that package to ensure the two are cross compatible. We have no need for that package, but would need to add it to our Godeps in order to run that unit test.

**Comment by liggitt** [comment]
@pmorie means all packages from k8s, I bet
I would include tests from any package we regularly carry UPSTREAM commits on

**Comment by pmorie** [comment]
We currently run all the upstream unit tests.  We could add a whitelist of other upstream packages to run tests on.

**Comment by deads2k** [comment]
If we're going to touch this again, I'd say that we only care about testing the UPSTREAM unit tests when a change in the pull affects a godep.  I wouldn't bother with a transitive checker, but a "if any godep code change, run all godep unit tests we care about" seems fair.

**Comment by smarterclayton** [comment]
This is effectively done
