### ISSUE TITLE
listing builds via REST transports json for all builds on a namespace

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#3626]
This means that when you have 150 builds in namespace, you'll end up with similar stats:

Listing all builds takes 23 seconds:

```
0.56s user 0.30s system 3% cpu 23.021 total
```

Size of the whole transfer is more than 4MB (we use annotations a lot).

Could we filter the final json somehow? We're interested only in status, build id and name of final image.

https://github.com/DBuildService/osbs-client/issues/153

**Comment by smarterclayton** [comment]
All filtering would do is reduce the transfer time to the client and client processing, but would not impact the server cup or memory use.  There are a few proposals to support this, but none close to implementation.  

It should not take 23 seconds for the server response to complete and run though - I might expect ~200ms at worst.  What specifically are you timing?  Curl?

**Comment by TomasTomecek** [comment]
Okay, 20 seconds was really of the hook (it included kerberos, getting token, writing whole response to file).

I did more performance testing and the whole curl `/osapi/v1beta3/namespaces/default/builds/` takes `0:00:04.377288`. That's still pretty bad (and not the 200 ms you've mentioned).

Pings:

```
PING host (1.2.3.4) 56(84) bytes of data.
64 bytes from host (1.2.3.4): icmp_seq=1 ttl=57 time=152 ms
64 bytes from host (1.2.3.4): icmp_seq=2 ttl=57 time=153 ms
64 bytes from host (1.2.3.4): icmp_seq=3 ttl=57 time=154 ms
64 bytes from host (1.2.3.4): icmp_seq=4 ttl=57 time=153 ms
64 bytes from host (1.2.3.4): icmp_seq=5 ttl=57 time=152 ms
^C
--- host ping statistics ---
6 packets transmitted, 5 received, 16% packet loss, time 5005ms
rtt min/avg/max/mdev = 152.835/153.585/154.391/0.590 ms

```

**Comment by liggitt** [comment]
should probably move this upstream as an API design issue

**Comment by TomasTomecek** [comment]
https://github.com/kubernetes/kubernetes/issues/13854
