### ISSUE TITLE
startup openshift based on kubernetes documentation fail with -f flag

### ISSUE THREAD

**Issue by onorua** [openshift/origin#3629]
Following command fail:
```
docker run -i -t --privileged -e="OPENSHIFTCONFIG=/config/admin.kubeconfig" -v ${OPENSHIFT_CONFIG}:/config openshift/origin ex bundle-secret openshift-config -f /config 
Error: unknown shorthand flag: 'f' in -f
Run 'openshift help' for usage.
```

**Comment by liggitt** [comment]
There is a pull request open to update that documentation and example scripts: https://github.com/GoogleCloudPlatform/kubernetes/pull/9938

Until that merges, the updated instructions can be viewed at https://github.com/stevekuznetsov/kubernetes/blob/skuznets/openshift-origin-example/examples/openshift-origin/README.md

**Comment by onorua** [comment]
Thanks!
