### ISSUE TITLE
New-app: Use DockerImage type of reference when image is only accessible in local docker

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#3637]
When searching for a base image, new-app will look into the local docker registry. If it finds a match there, it will create an image stream for the image and set up a trigger for it in the build config. 

If the image is only found locally and not in a registry, new-app should create a 'DockerImage' reference to it and not try to create an image stream. This allows new-app to create build configs for Dockerfiles that have a FROM an image that is not accessible in a public registry but will be available locally to the openshift nodes.

**Comment by bparees** [comment]
@csrwng I thought you added this?

**Comment by csrwng** [comment]
No, we still create the image stream. When we find the image locally we need to make sure it's not found in a registry and if it's not, then only use a DockerImage reference.
