### ISSUE TITLE
There is no openshift stop command

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin#3638]
I installed openshift using the binary.  I started the openshift application, it fires off etcd and kubernetes but now I am not able to stop the application.  How am I supposed to stop openshift?  There is nothing in the documentation.

**Comment by liggitt** [comment]
etcd and kubernetes start in-process... if you stop OpenShift, they stop as well

**Comment by deanpeterson** [comment]
I installed the BINARY.  I am not running openshift as a docker container.  It is running directly on the host machine.  I understand if I was running the openshift container I can just stop the container.  Since I am not running the container, I am running the BINARY version; how do I stop Openshift?

**Comment by smarterclayton** [comment]
SIGTERM or SIGINT to the process will stop it

**Comment by deanpeterson** [comment]
I do not see any openshift processes.  Are they named something other than "openshift"

**Comment by liggitt** [comment]
If you started openshift directly on the command-line (`openshift start ...`) you can ctrl+c or send a sigterm/sigint to kill it.

If you started openshift using systemd, you can also stop it with systemd (`systemctl stop openshift-master`)
