### ISSUE TITLE
Missing copyright and license notices

### ISSUE THREAD

**Issue by dtschan** [openshift/origin#3640]
At least some files are missing copyright and license notices. This is of particular importance for files that tend to get copied into user projects on their own, like images/builder/docker/custom-docker-builder/build.sh or examples/**.

**Comment by bparees** [comment]
@dtschan when you say "copied into user projects" can you clarify what you mean?  you mean because those files will be present in the image that the application is layered on top of?  or are you referring to actually copying the files into a project/repo for development purposes?

**Comment by dtschan** [comment]
I mean the latter, where the files get separated from the top-level license file, e.g.: https://github.com/puzzle/puzzle-ose3-docker-builder/commits/master

**Comment by brenton** [comment]
Hi @dtschan, sorry for the late response.  I had a discussion with Red Hat's legal counsel and they said inlining the license or copyright information was not needed in this case.

I'm going to close this issue for now.  If you feel like something else is needed feel free to re-open it.
