### ISSUE TITLE
Describe command doesn't accept multiple resources

### ISSUE THREAD

**Issue by miminar** [openshift/origin#3642]
however it says it does:

    oc describe pods
    error: you must provide one or more resources by argument or filename
    oc describe pods/hazelcast-blg7l pods/hazelcast-vd4qi
    error: multiple resources provided: [pods/hazelcast-blg7l pods/hazelcast-vd4qi]

**Comment by miminar** [comment]
By the way is there some simple way to list `pod` -> `node` associations for more pods/nodes at once? Something like `osc get pods` used to show.

**Comment by kargakis** [comment]
Can you rebuild using the latest master? This is fixed after the last Kube rebase

**Comment by kargakis** [comment]
> By the way is there some simple way to list pod -> node associations for more pods/nodes at once? Something like osc get pods used to show.

You can describe a node and you'll get back all the pods that are there:
```
[vagrant@openshiftdev sample-app]$ oc describe nodes openshiftdev.local --config=openshift.local.config/master/admin.kubeconfig
Name:			openshiftdev.local
Labels:			kubernetes.io/hostname=openshiftdev.local
CreationTimestamp:	Thu, 09 Jul 2015 08:38:07 +0000
Conditions:
  Type		Status	LastHeartbeatTime			LastTransitionTime			Reason					Message
  Ready 	True 	Thu, 09 Jul 2015 10:47:07 +0000 	Thu, 09 Jul 2015 08:38:07 +0000 	kubelet is posting ready status 	
Addresses:	127.0.0.1
Capacity:
 cpu:		2
 memory:	1017552Ki
 pods:		100
Version:
 Kernel Version:		3.17.4-301.fc21.x86_64
 OS Image:			Fedora 21 (Twenty One)
 Container Runtime Version:	docker://1.6.0
 Kubelet Version:		v0.20.0-157-g96828f2
 Kube-Proxy Version:		v0.20.0-157-g96828f2
ExternalID:			openshiftdev.local
Pods:				(9 in total)
  Namespace			Name
  default			docker-registry-1-p6nrz
  test				database-1-rce1s
  test				database-1-vigv7
  test				database-1-vpl9a
  test				frontend-1-e01xb
  test				frontend-1-uubb2
  test				ruby-hello-world-1-4koh9
  test				ruby-hello-world-1-build
  test				ruby-sample-build-1-build
No events.
```

**Comment by smarterclayton** [comment]
Fixed

**Comment by miminar** [comment]
@karkagis Thanks, that's what I was looking for. Haven't tried latest code yet. Once I do, I'll report back if it still applies.
