### ISSUE TITLE
Please fix documentation for deployment of openshift inside kubernetes

### ISSUE THREAD

**Issue by onorua** [openshift/origin#3644]
I've followed
https://github.com/stevekuznetsov/kubernetes/blob/skuznets/openshift-origin-example/examples/openshift-origin/README.md
everything seems working fine, but in logs I can see:
```E0709 16:47:31.159267       1 reflector.go:136] Failed to list *api.Namespace: User "system:openshift-master" cannot list all namespaces in the cluster```

then I've changed openshift-master.kubeconfig to look like kubeconfig and recreated the replication controller, error disappear but I stil get:
```
[root@06e0714b72b0 openshift]# oc get svc
Error in configuration: default cluster has no server defined
```
I've also replaced admin.kubeconfig with kubeconfig and replaced OPENSHIFTCONFIG with KUBECONFIG environment variable to get last step working. 

I still have problem with:
```
Error from server: the server could not find the requested resource (get policyBindings)
```

**Comment by stevekuznetsov** [comment]
Hey @onorua! Have you copied the serviceaccount public key into the OpenShift config and edited the `master-config.yaml` to reflect that? Not doing that will result in a lot of `Failure to list` errors.

**Comment by onorua** [comment]
Yes, I've done that

**Comment by stevekuznetsov** [comment]
@onorua There's an issue with transferring the secret sometimes - I'm looking into it. @smarterclayton please assign this to me.

**Comment by stevekuznetsov** [comment]
@onorua Upstream Kubernetes has removed support for `v1beta3` API endpoints so the OpenShift web UI wil not be able to resolve API endpoints until #2851 is fixed. However, the update to my [upstream pull](https://github.com/GoogleCloudPlatform/kubernetes/pull/9938) allows for cli use with the new serviceaccount key transfer script. Tag me there if you run into any more issues!

**Comment by liggitt** [comment]
Closing in favor of https://github.com/GoogleCloudPlatform/kubernetes/pull/9938
