### ISSUE TITLE
can we get periodic (say weekly/monthly) vagrant images we can just download? 

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#365]
Due to the recent service / iptables changes I've had to abandon running openshift natively on my mac (shame!) and had to start using vagrant. I've now been reminded of why I ditched it previously and moved to running it natively before ;).

It takes me a very long time to create the vagrant images (about an or so hour); and it seems quite brittle. During this hour or so while it takes a long time to perform yum install kinda stuff on the images (or my crappy and unreliable wifi) it often just flat out fails to install stuff. (e.g. vagrant suspend / resume doesn't seem to restart openshift & I've not been able to figure out the magic vagrant/openshift commands to get things to restart again). Usually I have to trash my clone of openshift; destroy all the images and start again from scratch and wait another hour or so.

Am sure others who are not using linux directly with openshift have similar vagrant issues; building multiple images on the fly all the time soon gets boring. Life's too short! OpenShift should be easy to use for folks.

So is there any chance we can get some automated script somewhere (or get someone to do a 'vagrant share' now and again) so we can just download vagrant images which are ready and work? Downloading and caching a big ass image is fine; as we can do that once and create/destroy vagrant images from it nice and quick. (Creating vagrant images from fedora20 is pretty fast and reliable here - its all the other stuff with yum install and the like that seems pretty flaky and extremely slow).

**Comment by smarterclayton** [comment]
Closing without prejudice - reopen if you continue to see this behavior.
