### ISSUE TITLE
GUI console doesn't show parameters while oc process shows it

### ISSUE THREAD

**Issue by onorua** [openshift/origin#3650]
I'm using 
```
REPOSITORY                       TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
openshift/origin                 latest              513499bb8e09        14 hours ago        409.7 MB
```
I've taken example template ruby-helloworld-sample, when I try to get parameters it shows me them:
```
[root@b39a5304ce57 openshift]# oc process --parameters -f tt.json 
NAME                DESCRIPTION              GENERATOR           VALUE
ADMIN_USERNAME      administrator username   expression          admin[A-Z0-9]{3}
ADMIN_PASSWORD      administrator password   expression          [a-zA-Z0-9]{8}
MYSQL_USER          database username        expression          user[A-Z0-9]{3}
MYSQL_PASSWORD      database password        expression          [a-zA-Z0-9]{8}
MYSQL_DATABASE      database name                                root
```
when I try to create deployment from template, I don't get parameters screen, which supposedly be there, according to documentation. 
am I doing something wrong, there is problem with documentation or there is a bug? 
![parameters](https://cloud.githubusercontent.com/assets/407040/8612674/04a97b08-2707-11e5-8387-929a67da87fd.jpeg)

**Comment by liggitt** [comment]
are you looking at the same template in the UI and in the CLI?

**Comment by onorua** [comment]
Yes, the same, but I've updated to fresh build and it seems working, weird.. maybe some cache used.. don't know

**Comment by spadgett** [comment]
@onorua any chance you were using an old copy of the template? If `apiVersion` is older (for instance, `v1beta1`), it might cause problems.

**Comment by liggitt** [comment]
@onorua any more info you can provide so we can recreate this?

**Comment by bparees** [comment]
closing without prejudice based on age and working in current builds.
