### ISSUE TITLE
Deployment rollback dry-run could show a diff of old/new

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3652]
Right now the deployment `rollback` command dry run option shows a human readable description of the proposed config for rollback. It could instead show a diff between old/new to make it more apparent what the rollback will do.

**Comment by ironcladlou** [comment]
cc @deads2k @liggitt for labeling

**Comment by kargakis** [comment]
We should transition any work from our cli tools, specifically `oc deploy` and `oc rollback` to `oc rollout` (https://github.com/openshift/origin/pull/8927). As far as rollback is concerned, this is `kubectl rollout undo` so we should ask for this upstream if we really want it.
