### ISSUE TITLE
Deployment config describer has inconsistent trailing newlines

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3653]
@deads2k has identified some case where the deployment config describer won't always return a newline at the end of its output, causing the user's prompt to sit inline with the final line of description output.

**Comment by ironcladlou** [comment]
cc @deads2k @liggitt for labeling

**Comment by deads2k** [comment]
I think this was actually a personal problem when I was playing with it.  Master looks happy to me.

**Comment by ironcladlou** [comment]
@deads2k 
>I think this was actually a personal problem when I was playing with it. Master looks happy to me.

Oh, cool. If you want to tell me your repro steps I can try it again to make sure and we can close this.

**Comment by deads2k** [comment]
> Oh, cool. If you want to tell me your repro steps I can try it again to make sure and we can close this.

Now I'm all embarrassed.  I was playing around trying to eliminate a double newline in `oc describe dc/ruby-hello-world` and did not clean before building your branch and so I screwed it up.  It looked inconsistent for me because at some point later I cleaned.  :(

**Comment by ironcladlou** [comment]
Good news: we get to close the issue without doing any work. :)
