### ISSUE TITLE
Strengthen identification checks when using deployment selector

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3654]
The `ConfigSelector` in `pkg/deploy/util.go` is used to filter a list of replicationControllers down to just those which are openshift deployments based on a namespaced label which should be present on all deployments. @deads2k expressed concerns that this filter may not be sufficient to avoid misidentifying plain RCs as deployments. One option would be to introduce another utility which could be used in conjunction with the selector and would further filter a list by discarding any controllers which are missing certain canonical annotations which should always be present on a valid deployment.

**Comment by ironcladlou** [comment]
My first question about this is: what's the user scenario that would land an RC in such a mis-labeled state?

**Comment by deads2k** [comment]
> My first question about this is: what's the user scenario that would land an RC in such a mis-labeled state?

I made `dc-1`, ran a few deployments.  I deleted `dc-1`, but did not cascade.  I create another `dc-1`.  `dc-1`'s label selector now returns unrelated RCs.

**Comment by ironcladlou** [comment]
>>My first question about this is: what's the user scenario that would land an RC in such a mis-labeled state?

>I made dc-1, ran a few deployments. I deleted dc-1, but did not cascade. I create another dc-1. dc-1's label selector now returns unrelated RCs.

We're talking about different things. ConfigSelector still behaved correctly: the orphaned deployments are still deployments for the config named `dc-1`. They got re-parented. I don't think we're going to be able to support what you're describing without re-thinking how we handle config->deployment associations in general (by the config's UID or something). I don't think a non-cascading delete of a config combined with the recreation of that same config *with the intent that the config is in no way associated with the previous config and its deployments* is something we can say we support right now.

**Comment by ironcladlou** [comment]
If selector namespacing is the concern, #3605 covers those.

**Comment by deads2k** [comment]
I think it's kind of crazy to allow DCs to claim RCs that they did not create.  So I think that #3605 would be necessary, but not sufficient.

I'm still not completely clear why claiming resources you didn't create (DC to RC or RC to Pods) is a good thing that users want and expect.

**Comment by ironcladlou** [comment]
I think that an attempt to create a DC whose name would cause it to inherit previously orphaned deployments should be rejected. DC deletes should always cascade, and until the orphans are gone, you shouldn't be able to make a new DC which would claim them.

**Comment by deads2k** [comment]
> I think that an attempt to create a DC whose name would cause it to inherit previously orphaned deployments should be rejected. DC deletes should always cascade, and until the orphans are gone, you shouldn't be able to make a new DC which would claim them.

That would satisfy me and I think it would be more understandable to users.

**Comment by ironcladlou** [comment]
Closing this in favor of #3654.
