### ISSUE TITLE
Node selector mismatch deploying router with multiple replicas

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#3655]
@ramr 

Deploying a router using the selector with multiple replicas resulted in a nodeSelectorMismatching error from the kubelet on the deployer pod.   Passing --replicas=2 on start does not work, but starting 1 and doing a oc scale --replicas=2 dc/router worked fine.

```
[root@172 ~]# #oadm router --default-cert=online.router.pem --credentials=/etc/openshift/master/openshift-router.kubeconfig --selector='type=infra' --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' --replicas=2
[root@172 ~]# oc get nodes
NAME           LABELS                                                                        STATUS
172.20.2.165   color=green,kubernetes.io/hostname=172.20.2.165,region=us-east,type=infra     Ready
172.20.2.166   color=green,kubernetes.io/hostname=172.20.2.166,region=us-east,type=infra     Ready
172.20.2.167   color=green,kubernetes.io/hostname=172.20.2.167,region=us-east,type=compute   Ready
172.20.2.168   color=green,kubernetes.io/hostname=172.20.2.168,region=us-east,type=compute   Ready
172.20.2.169   color=green,kubernetes.io/hostname=172.20.2.169,region=us-east,type=compute   Ready
```

```
Fri, 10 Jul 2015 10:10:07 -0400   Fri, 10 Jul 2015 10:10:07 -0400   1         router-1-deploy   Pod                                                         nodeSelectorMismatching   {kubelet 172.20.2.167}      Cannot start the pod due to node selector mismatch
```

Some logs: 

1.  http://pastebin.test.redhat.com/296380
1.  http://pastebin.test.redhat.com/296383

/cc @wshearn

**Comment by ramr** [comment]
@pweil- @wshearn  Will take a look and try and reproduce locally. The logs don't seem  to have much.
Is this running a specific OpenShift version or the current code (```HEAD```)?

**Comment by ramr** [comment]
@pweil- / @wshearn, Took me a while to get a dev env up but I just tried it with the latest commit: ```0e040b5bd46a5578b37e52eb5676ab43ea78eabb``` and it works fine for me on a 2 node (+master) cluster with the nodes labelled ```infra=true```. I tried it with both the standard router image ```via --latest-images``` (images built locally) as well as the ose-haproxy-router image (```--images='registry.access.redhat.com/openshift3/ose-${component}:latest'```). 
The latter test with ose-haproxy-router image I tried with a downloaded image as well as without having one available locally. It took about almost 8 minutes to download the ose-haproxy-router image on the node that the deployer ran on and another 5 odd minutes beyond that on the second node.

So gives me to think something else was awry - one possibility could be that the ose-haproxy-router or deployer images were still downloading whilst you were started/bailed out on the command the first time and when you ran it again it succeeded.  A way to test that hypothesis is to just delete the router DC, RC and SERVICE 
```  
oc delete rc router-1  
oc delete dc router  
oc delete se router  
```  
and wait for the pods to go away and retry the original command: 
```oadm router --default-cert=online.router.pem --credentials=/etc/openshift/master/openshift-router.kubeconfig --selector='type=infra' --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' --replicas=2```  
and see if that works. 

@wshearn can you please try that and confirm. Thx.

**Comment by liggitt** [comment]
@pweil- were you running an installed version with the scheduler.json configured? if so, https://github.com/openshift/openshift-ansible/issues/361 might be the cause... the scheduler was not honoring the nodeSelector, which meant pods would get scheduled, then fail at the node with a mismatch error

**Comment by pweil-** [comment]
@wshearn :point_up: this could've been the cause

**Comment by mrry550** [comment]
@wshearn Any luck? :)

**Comment by wshearn** [comment]
Yeah, this has been fixed for us, sorry should have said something.
