### ISSUE TITLE
[rfe] support git commit based rollback (in the cli)

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#3656]
Currently you have to specifically rollback to a deployment number (eg: foo-4).

It would be nice if we could rollback to a particular git commit (eg: 63f2a9).

Whether or not we need the entire commit hash I'm not really sure matters, but at least being able to supply the hash as part of `oc rollback` would probably be very beneficial.

**Comment by smarterclayton** [comment]
@bparees @bparees structurally we should be able to state

> As a user, I can choose to deploy the most recent image that matches a given Git commit, and the UI should accurately communicate the connection between the source that goes into an image and deployment of that source.

**Comment by mfojtik** [comment]
https://github.com/openshift/origin/pull/4569

@bparees this is probably dupe of https://github.com/openshift/origin/issues/4571

**Comment by bparees** [comment]
build portion of this is done.  closing this issue(the deployment part that remains) in deference to #4571.
