### ISSUE TITLE
[RFE] allow webhook to cause deployment

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#3659]
In the case where people are building Docker images externally and pushing them into external repositories, we currently can't monitor those repos/tags/metadata to trigger automatic deployments.

While it is possible to talk to the API today to cause a new deployment to trigger as part of the external build process, it's not easy.

It would be nice to have a webhook-like URL target that operates similar to a build webhook -- instead causing a new deployment of latest or whatever.

**Comment by ironcladlou** [comment]
We're not going to support webhooks directly for deployments, but we will support API endpoints for deploying latest, cancelation, retries, etc (https://trello.com/c/qCzTBO0h).

**Comment by ironcladlou** [comment]
cc @smarterclayton, this one needs closed.

**Comment by kargakis** [comment]
@smarterclayton needs closing

**Comment by smarterclayton** [comment]
I changed my mind :)  I think web hooks (generic triggers) on a lot of objects is great idea.  Just need to figure out how to do it.

**Comment by kargakis** [comment]
relevant: https://github.com/coreos/krud

**Comment by smarterclayton** [comment]
Yeah, I'm going to write up a suggestion about how we can make triggers
that apply equally to all objects and then support them transparently.

**Comment by kargakis** [comment]
Trello'd: https://trello.com/c/NwCisNFP/727-add-webhooks-to-deployments-accept-push-events-from-dockerhub

cc: @mfojtik
