### ISSUE TITLE
Orphaned deployments should block creation of new parent deploymentconfigs

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#3660]
If deployments become orphaned by the deletion of a deploymentconfig, it shouldn't be possible to create a new deploymentconfig with the same name as the deleted config, as doing so would effectively reparent the deployments with what's likely an alien config with a new UID.

It would be easier and safer to avoid state by rejecting creates for configs for which we can detect orphaned deployments based on the config name.

**Comment by ironcladlou** [comment]
cc @deads2k and @liggitt for labeling.

**Comment by smarterclayton** [comment]
I'm not sure I agree with this.  Why wouldn't I want to reparent previous deployments?

**Comment by liggitt** [comment]
It struck me a little odd as well

**Comment by smarterclayton** [comment]
EMOREREASONSNEEDED

**Comment by deads2k** [comment]
It's really strange to have dc-1 create a bunch resources, then I delete it.  For whatever reason, those things stick around.  Then I create a new thing called dc-1 that uses a different image or is different in some other significant way.  It's really strange and unexpected to have it own unrelated RCs.

**Comment by deads2k** [comment]
The RC to Pod argument also seems crazy.  I think users will hate us for it.  Label selectors are cool, but for resources and manage other resources, it's really unexpected to have them try to manage resources that don't match the sort of resources they create.  It may be a neat feature, it may be easy to code that way, it may make it possible to recover from some pathological cases, but it's really confusing when unrelated items are suddenly owned by a resource that treats things as fungible when one of them is different.

**Comment by ironcladlou** [comment]
I don't think sameness of a DC name is a strong enough indicator that a DC is actually *the same* as some deleted DC. The DC names could be something as generic as `frontend`. I don't know that the UID change of the DC causes any problems in the deployment code itself.

**Comment by smarterclayton** [comment]
Ultimately, I agree some of the concerns are valid, but I also don't think
our top priority is building in protection in the absence of use cases that
require it.  We're going to move deployments upstream, so I'm much more
concerned with proving the features we need vs extra limitations that have
to be justified upstream.

On Jul 13, 2015, at 9:07 AM, David Eads <notifications@github.com> wrote:

The RC to Pod argument also seems crazy. I think users will hate us for it.
Label selectors are cool, but for resources and manage other resources,
it's really unexpected to have them try to manage resources that don't
match the sort of resources they create. It may be a neat feature, it may
be easy to code that way, it may make it possible to recover from some
pathological cases, but it's really confusing when unrelated items are
suddenly owned by a resource that treats things as fungible when one of
them is different.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3660#issuecomment-120922185>.

**Comment by smarterclayton** [comment]
You would have to say "oc delete --cascade=false", which means that is what
you want. B

On Jul 13, 2015, at 9:04 AM, David Eads <notifications@github.com> wrote:

It's really strange to have dc-1 create a bunch resources, then I delete
it. For whatever reason, those things stick around. Then I create a new
thing called dc-1 that uses a different image or is different in some other
significant way. It's really strange and unexpected to have it own
unrelated RCs.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3660#issuecomment-120921740>.

**Comment by smarterclayton** [comment]
In general, if solution requires implementing an index and a distributed scanner, it's probably not worth fixing (especially if it changes create from an O(1) operation).  Users can leave things around.  We should tolerate them.  A user should be allowed to templatize a DC with an initial rc already created.  There are other reasons, but at a minimum we don't benefit from a dramatic complexity increase for a minor usability benefit.

**Comment by ironcladlou** [comment]
@smarterclayton want to close this one?
