### ISSUE TITLE
oadm build-chain doesn't handle non-existent tag

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3663]
```
[deads@deads-dev-01 origin]$ oadm build-chain ruby-hello-world
error: no tag latest exists in foo/ruby-hello-world
```

Tag latest does not exist **yet**.  Lack of a particular image stream tag does not mean that a particular image stream tag will not produce a series builds.  This can happen because bc-1 will push to imagestream:latest, which another build config depends upon.

The graph package solves this problem for `oc status`.  Create all bc, is, and ist nodes.  Create all buildInputOutput edges.  Locate the ist node of interest (if the tag doesn't exist, but a bc points to it you'll have a synthentic node, but it will be wired into the graph).  Build the subgraph from that ist node.  Traverse.

@bparees

**Comment by kargakis** [comment]
There is a [Trello card](https://trello.com/c/CeAq7lpA/528-2-use-graph-traversal-resources-in-build-chain-uicomp-future) about making build-chain use the graph package and I've been planning to work on it. I can start on it this Monday

**Comment by kargakis** [comment]
@bparees assign this to me

**Comment by kargakis** [comment]
Before I start on this, currently build-chain creates a graph of is nodes connected with edges that represent bc triggers. @bparees just to make sure, if we are going to create is, ist, and bc nodes, it will be a big change for the tool.

**Comment by bparees** [comment]
@kargakis yeah i think the idea here is to create the graph properly w/ the is/ist/bc nodes and then traverse the graph.  I assume you can't do that without the is/ist nodes (or at least it's easier to do it with them).

but if you have another approach that
1) retains the function of the tool
2) uses the graph library instead of manual traversal/processing

then i don't care if the IS/IST nodes are created.

**Comment by kargakis** [comment]
Unfortunately 1) cannot be done because of 2). TBH I don't like us using an internal structure and ignore the graph library so I'll go ahead and rework this.

**Comment by bparees** [comment]
@kargakis this is done now, right?

**Comment by kargakis** [comment]
> @kargakis this is done now, right?

Still working on it: https://github.com/openshift/origin/pull/3696
