### ISSUE TITLE
oc get componentstatus errors

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#3667]
With 1.0.1 release, following errors:

```
$ oc get componentstatus
NAME                 STATUS      MESSAGE   ERROR
controller-manager   Unhealthy             Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connection refused
scheduler            Unhealthy             Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connection refused
etcd-0               Unhealthy             Get http://172.17.42.1:4001/v2/keys/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

**Comment by liggitt** [comment]
I'm not familiar with componentstatus. It looks like it is checking hardcoded ports for status. 

OpenShift doesn't run the scheduler and controller manager in separate processes, so I'm not sure individual health endpoints exist for those. Etcd runs in https mode (which is also secured), so a plain HTTP get won't work to determine health.

**Comment by jimmidyson** [comment]
I'd not seen `componentstatus` before but it seems pretty useful as a quick check on the cluster. Either it should be made to work with oc or should be disabled as it could be confusing if users start trying it out.

**Comment by liggitt** [comment]
Yeah, the implementation from upstream assumes separate components for the controller manager, assumes everything is available via 127.0.0.1 from the master, and assumes no auth. All of those assumptions are invalid.. not sure the best way to rework it for openshift yet

**Comment by deads2k** [comment]
Whoever fixes this should a test to be sure it doesn't regress on another rebase.

**Comment by simon3z** [comment]
@deads2k @liggitt @smarterclayton is there anyone working on this one? It's not clear if #4646 is supposed to fix (or partly fix this). We would like to expose the component status in ManageIQ (at least we're already doing it for kubernetes).

**Comment by liggitt** [comment]
It is not being worked on now. Like I said, it would require rearchitecting the upstream implementation.

**Comment by liggitt** [comment]
Bootstrap policy also needs to include this resource for cluster reader

**Comment by jimmidyson** [comment]
Is this going to be given any time? This endpoint is really useful for a snapshot of component status in a kubernetes cluster, one shot request to get a quick snapshot of component health.

**Comment by liggitt** [comment]
it's not the most pressing thing on the list... an upstream issue to extract those assumptions would probably be a good place to start

**Comment by liggitt** [comment]
Current upstream proposal/replacement is at https://github.com/kubernetes/kubernetes/pull/13216, but may be stalled at the moment

**Comment by abessifi** [comment]
Anyone knows why this issue still not fixed ?

**Comment by liggitt** [comment]
because the componentstatus api still makes invalid assumptions about cluster topology.
