### ISSUE TITLE
Add Kubernetes service IP to cert name SANs (as per upstream)

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#3670]
In https://github.com/GoogleCloudPlatform/kubernetes/pull/10643, the `ServiceReadWriteIP` is added to the certificate SANs. This allows pods to address the API server via the `KUBERNETES_SERVICE_HOST` env var without having to disable hostname verification. This is another option to use in addition to using DNS, which is still sometimes flaky (IPv6 issues apparently).

**Comment by liggitt** [comment]
I have mixed feelings about this... it depends on pinning the IP of the service to the first one in the service IP range, which feels hokey. It also would mean introducing a non-loopback IP into the cert, which we've tried to keep limited to DNS names and loopback IPs.

**Comment by jimmidyson** [comment]
@liggitt The service is always & has always been the first IP in the service IP range. Is this even configurable? If not then I can't see the problem.

**Comment by liggitt** [comment]
I don't like putting the first service IP in the cert for the following reasons:
* requires knowing the service IP range when the cert is generated
* requires regenerating the cert if the service IP range changes
* makes it impossible to use a real CA to get a master API cert (which you could do today with a wildcard cert for *.my.cluster.suffix)

**Comment by jstrachan** [comment]
@liggitt so you're saying that only DNS should be used to access the kubernetes REST API? That we should never use $KUBERNETES_SERVICE_HOST / $KUBERNETES_SERVICE_PORT on OpenShift?

In that case is there going to be a canonical environment variable for the DNS domain? so we can use something like `kubernetes.default.svc.${KUBERNETES_DNS_DOMAIN}` to find the kubernetes REST API without hitting issues with the cert?

**Comment by liggitt** [comment]
The DNS domain is added to the DNS search path in resolv.conf. You can use https://kubernetes.default.svc

**Comment by liggitt** [comment]
If that partial DNS name isn't in the cert, it should be

**Comment by jstrachan** [comment]
@liggitt thats good to know. So are you saying on OpenShift we should never use $KUBERNETES_SERVICE_HOST and we should always use DNS right?

**Comment by liggitt** [comment]
That would be what I would expect. @smarterclayton?

FYI, #3985 is open to add all the DNS-resolveable names to the certs

**Comment by smarterclayton** [comment]
At some point in the future KUBERNETES_SERVICE_HOST will likely become a DNS name, not an IP.  Until then, we recommend using the DNS name.

**Comment by jimmidyson** [comment]
@liggitt Is there a way to add `kubernetes.default.svc` to the SANs in 1.0.4? Adding to master config somehow & recreating certs?

**Comment by liggitt** [comment]
if you just want the prefix names in the cert, you can generate a new api server certificate using `oadm ca create-server-cert`. Take a look at your existing cert's SANs to build the `--hostnames` arg, point at your existing CA cert/key/serial

**Comment by jimmidyson** [comment]
@liggitt Thanks! Worked perfectly.

**Comment by jimmidyson** [comment]
Closing now that we can use a discoverable address with a valid cert.
