### ISSUE TITLE
[RFE] Allow oc logs to only show the last N lines

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#3671]
"oc logs" seems by default to dump the whole logfile when using it.

it would be nice if there was an option to only show the last N line for example : 

     oc logs -n 100 POD [CONTAINER]

would print the last 100 lines from the POD

**Comment by chmouel** [comment]
This seems to be added by @smarterclayton  in https://github.com/kubernetes/kubernetes/issues/12447

**Comment by smarterclayton** [comment]
This landed in the rebase.

**Comment by kargakis** [comment]
> This landed in the rebase.

No, it will land in the next one

@soltysh fyi
