### ISSUE TITLE
Racy tests

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#3677]
http://pastebin.com/LTBwh561

Reported by Travis

The graph package is involved 
cc: @deads2k

**Comment by deads2k** [comment]
@smarterclayton I don't see it.  I tried to create a similar test like this:

```
func TestRace(t *testing.T) {
	wg := sync.WaitGroup{}
	lock := sync.Mutex{}
	foo := ""

	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func(l sync.Mutex) {
			defer wg.Done()
			l.Lock()
			defer l.Unlock()

			foo = fmt.Sprintf(foo+" %d", i)
		}(lock)
	}

	wg.Wait()
	fmt.Printf(foo)
}
```

but it works fine.

**Comment by deads2k** [comment]
recanted.  Needs a pointer to the mutex because ick.

**Comment by liggitt** [comment]
Simplifying the parallel load should fix this. Parallel run closures that each load a list into a typed variable visible to the closure, then serially process the results. No mutex needed.

**Comment by deads2k** [comment]
> Simplifying the parallel load should fix this. Parallel run closures that each load a list into a typed variable visible to the closure, then serially process the results. No mutex needed.

Can you demonstrate that?  I'm visualizing that as lots of very similar looking closures called in a "load" method that look like they should all be dry'ed out, but can't be due to types.

**Comment by smarterclayton** [comment]
David and I talked in person and floated an object per type that satisfied
an interface with a method "Load" and a method "AddToGraph()" - load is
parallel, add to graph is iterative.

On Mon, Jul 13, 2015 at 10:58 AM, David Eads <notifications@github.com>
wrote:

> Simplifying the parallel load should fix this. Parallel run closures that
> each load a list into a typed variable visible to the closure, then
> serially process the results. No mutex needed.
>
> Can you demonstrate that? I'm visualizing that as lots of very similar
> looking closures called in a "load" method that look like they should all
> be dry'ed out, but can't be due to types.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3677#issuecomment-120958146>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift
