### ISSUE TITLE
Switch router to host network

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#3681]
When https://github.com/openshift/origin/pull/3496 merges we'll have the ability to control the usage of host network and host ports in SCCs.  We can now switch the router to use host networking.

Issues to be aware of:

1.  Ip allocation: which IP address will the pod be given and how does that reflect in the service that can be used to identify router peers

Reference issues of previous work:

1.  https://github.com/openshift/origin/pull/3299
1.  https://github.com/openshift/origin/pull/3297

/cc @rajatchopra

**Comment by liggitt** [comment]
wasn't this already done?

**Comment by pweil-** [comment]
https://github.com/openshift/origin/pull/4026
