### ISSUE TITLE
build-chain should provide an option for returning a list of objects

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#3683]
Use-case:
One of my images turns out to be evil so I want to delete everything associated with it (imageStreams, buildConfigs).

```
$ oadm build-chain evil-image --involved | oc delete -f -
```

I am not sure though if we want to delete an imageStream just because of a tag. @ncdc thoughts on this?

@bparees fyi

**Comment by bparees** [comment]
do i just want an imagestream list here?  do i not also want the BCs that consume those ISes?

**Comment by kargakis** [comment]
> do i just want an imagestream list here? do i not also want the BCs that consume those ISes?

Right, updating the first post...

**Comment by ncdc** [comment]
@kargakis the other day I created #3485 which (when coded) might help somewhat?

**Comment by kargakis** [comment]
> @kargakis the other day I created #3485 which (when coded) might help somewhat?

Hmmm, that looks useful on it's own and build-chain could benefit from it.

**Comment by kargakis** [comment]
Moving to @bparees for assigning to somebody else

**Comment by bparees** [comment]
@kargakis couple questions on this:
1) what is "--involved" supposed to control?
2) why wouldn't we just support "-o json" or "-o yaml" and then you could pipe it to oc delete?
3) if you really want to delete all things related to evil image, you should be deleting the deploymentconfigs too, but it doesn't make sense to me that `build-chain` would output deploymentconfigs, so i don't know that this is the right command to solve your use case.

**Comment by kargakis** [comment]
> if you really want to delete all things related to evil image, you should be deleting the deploymentconfigs too, but it doesn't make sense to me that build-chain would output deploymentconfigs, so i don't know that this is the right command to solve your use case.

Correct. You can close this issue, we may want to come up with something different.
