### ISSUE TITLE
Cannot use custom docker registry config

### ISSUE THREAD

**Issue by wshearn** [openshift/origin#3686]
In the docker registry dockerfile /config.yml is appended to the command line. This causes dockerregistry to ignore the REGISTRY_CONFIGURATION_PATH env variable.

https://github.com/openshift/origin/blob/master/images/dockerregistry/Dockerfile#L16

**Comment by ncdc** [comment]
This code (https://github.com/openshift/origin/blob/master/cmd/dockerregistry/main.go#L19-L23) makes the command line arg take precedence over an env var. We should probably flip it so the env var wins, and switch to using an env var in the Dockerfile instead of an arg.

**Comment by liggitt** [comment]
Really? IMO, explicit command line option should always win

**Comment by ncdc** [comment]
@liggitt as long as it's easy to change the config.yml in the dc somehow, I'm ok either way.

**Comment by wshearn** [comment]
Or maybe just move /config.yml to a subdirectory so we(admins) can just clobber it with a secrets mount?

**Comment by liggitt** [comment]
> Or maybe just move /config.yml to a subdirectory so we (admins) can just clobber it with a secrets mount?

the parameter needs to be overrideable from outside the container... relying on being able to stomp a file in-place isn't great

**Comment by pweil-** [comment]
bumped priority based on email conversation with @smarterclayton
