### ISSUE TITLE
Openshift origin, IP not getting assigned

### ISSUE THREAD

**Issue by Vishalkale0409** [openshift/origin#3692]
Hi all,
I am following Open Shift Deployment on a virtual machine using guide  at link https://docs.openshift.org/origin-m4/oo_deployment_guide_vm.html#virtualbox ,
however when I start that VM, an IP address is blank. IP does not get assigned to the VM. I manually tried assigning IP address to it, but still I am unable to start internet connectivity on it. Do I need a DHCP server installed on my Host? please help.

Thank you in advance.

**Comment by smarterclayton** [comment]
This is the origin v3 repository - this issue is best asked in https://github.com/openshift/origin-server
