### ISSUE TITLE
oc commands should follow the hacking guide

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#3697]
Most of the cli commands don't comply to the structure laid out in the hacking guide, something we should fix at some point

https://github.com/openshift/origin/blob/master/docs/cli_hacking_guide.adoc#command-structure

See some example commands that follow the guide:
* [deploy](https://github.com/openshift/origin/blob/255307e708defdbdb66fc421cc3d45cce375a209/pkg/cmd/cli/cmd/deploy.go#L26)
* [rollback](https://github.com/openshift/origin/blob/255307e708defdbdb66fc421cc3d45cce375a209/pkg/cmd/cli/cmd/rollback.go#L95)
* [volume](https://github.com/openshift/origin/blob/255307e708defdbdb66fc421cc3d45cce375a209/pkg/cmd/cli/cmd/volume.go#L89)
* [build-chain](https://github.com/openshift/origin/blob/255307e708defdbdb66fc421cc3d45cce375a209/pkg/cmd/experimental/buildchain/buildchain.go#L44)

**Comment by fabianofranz** [comment]
Some commands were refactored to conform the hacking guide, but although it is recommended to follow the structure, it's not mandatory. Closing.

**Comment by Elizzy22** [comment]
Do you need help?I recommend you contact ( monitorywizard247@gmail.com) I contacted him for some assistant in hacking Facebook, whatsapp, gmail and mobile phone account, which he did successfully, now I got every proof about my fiancee. William is a computer engineer and he’s involved in different types of hacking services such as domains, whatsapp, gmail, Facebook, mobile phones, upgrade scores, gmail, domains, hotmail, yahoo and database.

**Comment by ambermatn** [comment]
BEST HACKER ALIVE 
Hi everyone, i don't know about others here but, If it's about getting hack jobs done, there's only one hacker i can vouch for, the same hacker that changed my life. Well I can only say hack.truth77@gmail.com is a reliable hacker/private investigator who handles such jobs with precision. Surprisingly, he offers a 24-hours total refund if you find his services unsatisfactory but he delivered way more than I expected. I’ll gladly list a couple of services he offers:
+Upgrade University Grades
+Facebook, Instagram, Twitter, Whatsapp, Line, Skype Hack
+Delete unwanted online Pictures and Videos on any website
+Remove Criminal Records
+Hack bank accounts
+increase your credit score
+increase your credit card limit
_ wipe your credit card debth
+Mastercard, Paypal, Bitcoin, WU, Money Gram with untraceable
credit on it etc.
+He also hacked facebook, twitter, instagram, yahoo,
gmail passwords etc.quite sure he’s into many more. You can’t underestimate what he can do for you. You might want to consider contacting him today. He’s definitely going to be of great help and Thank me later 
you can reach the hacker through:
EMail hack.truth77@gmail.com
