### ISSUE TITLE
Released 1.0.2 seems based on 0.20, 0.22 - missing CA certs in pods

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#3711]
```
$ openshift version
openshift v1.0.2
kubernetes v0.20.0-157-g96828f2
```

Noticed that CA certificate wasn't included in service account dir in recreated pods.

**Comment by jimmidyson** [comment]
See e.g. in Godeps.json (https://github.com/openshift/origin/blob/v1.0.2/Godeps/Godeps.json#L83-L87):

```
{
	"ImportPath": "github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver",
	"Comment": "v0.20.0-157-g96828f2",
	"Rev": "96828f203c8d960bb7a5ad649d1f38f77ae8910f"
}
```

**Comment by jimmidyson** [comment]
In fact there isn't a 0.22 tag of Kubernetes?

**Comment by liggitt** [comment]
The ca has to be added to the service account config stanza to be picked up (see https://github.com/openshift/origin/pull/3622/files#diff-381e09db7a55a712234f2c2413f7d987)

Existing service account tokens don't currently get the CA added, only new ones do. I have that on my list to fix, though I'm not sure mutated secrets get updated on the nodes (@pmorie might know more about that).

**Comment by jimmidyson** [comment]
@liggitt Thanks! Had to update master config, all worked after that. I did have to recreate service account tokens too. Closing this now as working for me, but might be good to update docs for those upgrading.

**Comment by jimmidyson** [comment]
@liggitt Out of interest, is the CA certificate secret enabled by default on new installations?

**Comment by jimmidyson** [comment]
@liggitt I also see no way to enable/disable this in the `openshift start` flags - have to manually edit the config file?

**Comment by liggitt** [comment]
Running from command-line or generating a new config will have the CA automatically. https://github.com/openshift/openshift-ansible/issues/333 is open to track adding the value in the installer.

**Comment by liggitt** [comment]
Opened https://github.com/openshift/origin/pull/3715 to add ca to existing secrets
