### ISSUE TITLE
Rough wrapping of pod template text on mobile

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3718]
The pod template information is there, but doesn't look good at mobile screen widths.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8700524/3f8a31aa-2ada-11e5-8bc5-fc18a1af2e28.png)

/cc @sg00dwin

**Comment by spadgett** [comment]
We also change line-height, font-size, and color often.

**Comment by smarterclayton** [comment]
We should probably do these in order:

1. Figure out any other structural changes we want to make to the template and deployment sections in the near term (3.1)
2. Make those changes or at least prototype them for steve/allie
3. Do a visual pass on the entire structure

**Comment by spadgett** [comment]
@jwforres FYI, I know you were looking at this.

**Comment by jwforres** [comment]
@sg00dwin fyi updated the comment on your PR for the pod template since you fixed this
