### ISSUE TITLE
UI inconsistently prefixes project namespace to images names when creating from template

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3720]
This is using `application-template-dockerbuild.json`. We're prefixing the project namespace on the builder image, but not on the deployment config image.

@liggitt the second image should be `project3/origin-ruby-sample`, right?

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8702449/d813ad9c-2ae5-11e5-870b-c7085914fef9.png)

**Comment by liggitt** [comment]
the container image is actually just a docker pull spec, so showing it as-is is correct. in this particular case, the deployment config has a trigger which will rewrite the container images with a resolved imagestreamtag pull spec... not sure how to show that on this page without lots more parsing of deployment configs
