### ISSUE TITLE
Empty parameters values confusing in UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3721]
Parameters that have no value are confusing in the UI. At first glance, the description looks like the value.

Always showing the text field instead of toggling to an edit state would fix the problem. We could also display  *none*.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8704797/6fbf5198-2af3-11e5-88f7-c502cfbd6f0a.png)

**Comment by liggitt** [comment]
I'm in favor of always being in edit mode. In general, that looks pretty rough... lots of long descriptions are ugly :-/

**Comment by spadgett** [comment]
@jwforres I can look at this.

**Comment by jwforres** [comment]
@spadgett might as well do this one at the same time while you are in that part of the code
https://github.com/openshift/origin/issues/4342
