### ISSUE TITLE
PVC is not created from a template in the web console

### ISSUE THREAD

**Issue by rassie** [openshift/origin#3722]
If creating an app from a template, an included PVC is not created.

Steps to reproduce (worked for me):

1. Create or clean a project.
2. Create an app from a template (`postgresql-persistent` in my case)
3. See the error message `Error syncing pod, skipping: failed to instantiate volume plugin [...]: persistentvolumeclaims "postgresql" not found`.

Creating the claim manually from the template's JSON instantiates a PVC successfully.

This is on 3.0.0, installed with `openshift-ansible` (tag `3.0.0-4`).

**Comment by markturansky** [comment]
@bparees Do you know who has done Template work?  I'm not sure this is a PV problem, though I'm glad to help debug if needed.  I have no knowledge of OS templates.

**Comment by bparees** [comment]
@markturansky i've done template work.  in this case the template in question is here:

https://github.com/openshift/origin/blob/master/examples/db-templates/postgresql-persistent-template.json#L43-L58

you can see the PVC definition, that's pretty much exactly the PVC that will get created, with parameters substituted, when the template is instantiated.

and here is where the deployment references the volume:
https://github.com/openshift/origin/blob/master/examples/db-templates/postgresql-persistent-template.json#L128-L133

and defines it:
https://github.com/openshift/origin/blob/master/examples/db-templates/postgresql-persistent-template.json#L143-L150

I think there is probably a bug here:
https://github.com/openshift/origin/blob/master/examples/db-templates/postgresql-persistent-template.json#L147

in that the claim name should match this:
https://github.com/openshift/origin/blob/master/examples/db-templates/postgresql-persistent-template.json#L46

if @rassle provided a non-default DATABASE_SERVICE_NAME then the two values wont match, would that lead to this error?

**Comment by rassie** [comment]
I don't think so. In this particular case, I've reproduced the error with `mysql-persistent`, which uses `mysql` as both `DATABASE_SERVICE_NAME` and its reference. In any case, I would expect a wrongly named and/or reference PVC to be created, which is not the case here.

BTW, I've just noticed that `oc delete all --all` does not delete PVCs -- is it possible that PVCs are missing from some kind of list of resource types, which would explain why PVCs are not deleted and also not created from templates?

**Comment by rassie** [comment]
A couple of other observations:

1. `oc get all` doesn't include PVCs either, so there is something amiss even though it might not be the culprit

2. `oc process -f /usr/share/openshift/examples/db-templates/postgresql-persistent-template.json | oc create -f -` correctly creates the PVC

3. `oc delete templates --all -n openshift ; oc create -f /usr/share/openshift/examples/db-templates/` and then creating an app out of `postgresql-persistent` **from the web console** still does not create a PVC.

4. 

```
# oc describe template postgresql-persistent
Name:		postgresql-persistent
Created:	About a minute ago
[....]
Objects:		 
    Service		${DATABASE_SERVICE_NAME}
    			
    DeploymentConfig	${DATABASE_SERVICE_NAME}
```
As we see, only a Service and a DeploymentConfig are shown, while I'd expect to see a PVC in this list.

Something is just not right.

**Comment by rassie** [comment]
@bparees Please re-open this issue, #3724 is correct for general case, however it doesn't fix this case.

**Comment by bparees** [comment]
Will take another look at this later.

**Comment by bparees** [comment]
@rassie can you do an "oc get template postgresql-template -o json" and see if the PVC shows up in that output?

**Comment by rassie** [comment]
@bparees Yes, it does.

**Comment by bparees** [comment]
> oc delete templates --all -n openshift ; oc create -f /usr/share/openshift/examples/db-templates/ and then creating an app out of postgresql-persistent from the web console still does not create a PVC.

@rassie why did you do this delete?  just to update with the changes I made?

it sounds like what you are observing is that:

oc process -f template.json | oc create -f -    # works
create from the same template via web console # fails to create PVC

is that accurate?

@liggitt @spadgett is it possible the webui is using an old api or not invoking the PVC endpoint to create the PVC?

**Comment by liggitt** [comment]
@spadgett looks like persistentvolumes and persistentvolumeclaims are missing from the API type map in data.js, so the UI doesn't know which API to post them to. Can you do the following:
* Sweep OpenShift and K8S API types and make sure the UI's type map is up to date
* Figure out why no error was surfaced about an unknown type (I would have expected that to surface in the UI during the create)

**Comment by liggitt** [comment]
also, there needs to be a BZ bug for this so QE can make sure there's a test case to cover it

**Comment by markturansky** [comment]
@liggitt this may be related:  https://bugzilla.redhat.com/show_bug.cgi?id=1236472

**Comment by liggitt** [comment]
@markturansky the steps for that BZ don't mention the web console... this issue is about the web UI not creating and PVC objects

**Comment by rassie** [comment]
@bparees Yes, I tried to get a clean slate in case I had old templates installed. And yes, it seems that the web UI can't handle PV/PVC properly.

**Comment by rassie** [comment]
@liggitt Is there something like `data.js` for the CLI? As I've mentioned earlier, `oc get all` does not include PVCs, so I suspect they have been forgotten in the CLI too.

**Comment by liggitt** [comment]
In the CLI, `all` aliases to `api/latest/latest.go`:
```
// UserResources are the resource names that apply to the primary, user facing resources used by
// client tools. They are in deletion-first order - dependent resources should be last.
var UserResources = []string{
	"buildConfigs", "builds",
	"imageStreams",
	"deploymentConfigs", "replicationControllers",
	"routes", "services",
	"pods",
}
```

If that list is incorrect, we should open a separate issue. @smarterclayton might know what the implications of adding things to that list are.

**Comment by smarterclayton** [comment]
You should add things to that list if you expect `oc delete all --all` to
delete them.  We should be deliberate about what goes into that list.

On Thu, Jul 16, 2015 at 11:53 AM, Jordan Liggitt <notifications@github.com>
wrote:

> In the CLI, all aliases to api/latest/latest.go:
>
> // UserResources are the resource names that apply to the primary, user facing resources used by
> // client tools. They are in deletion-first order - dependent resources should be last.
> var UserResources = []string{
>     "buildConfigs", "builds",
>     "imageStreams",
>     "deploymentConfigs", "replicationControllers",
>     "routes", "services",
>     "pods",
> }
>
> If that list is incorrect, we should open a separate issue.
> @smarterclayton <https://github.com/smarterclayton> might know what the
> implications of adding things to that list are.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3722#issuecomment-122000153>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by spadgett** [comment]
@liggitt I've got an open PR adding additional types.

A runtime JavaScript error prevents a message from being shown in the UI.

```
TypeError: Cannot read property 'indexOf' of undefined
    at i._urlForType (scripts.js:707) ...
```

**Comment by spadgett** [comment]
Better error trace:

```
TypeError: Cannot read property 'indexOf' of undefined
    at DataService._urlForType (data.js:851)
    at data.js:185
    at processQueue (angular.js:13170)
```

**Comment by liggitt** [comment]
Check in DataService.createList... if we can't resolve the type in `self._objectType(object.kind)`, we should push something onto failureResults immediately rather than continuing to call `create`  for that object.
