### ISSUE TITLE
E2E tests should exercise variable expansion

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#3738]
The E2E test should exercise kubernetes variable expansion in envs, cmd, and args.

**Comment by pmorie** [comment]
@bparees @mfojtik Any ideas come to mind about this?  I'm sure there are examples that we can start using this in.

**Comment by bparees** [comment]
Ideas as in semi realistic use cases for this that we could run as tests? Not really. The env variable in question would be defined on the node host? 

Maybe using it to define a proxy server env var within a pod?

**Comment by pmorie** [comment]
I'd much rather just run the upstream e2e for this than shoehorn it into a test where it doesn't naturally fit.

**Comment by mfojtik** [comment]
@pmorie @bparees we can add som tests to verify that our template expansion still works with upstream changes (that seems a good idea to me). And while we will be on that, I can also add some test cases for the upstream syntax.

**Comment by bparees** [comment]
@pmorie can you point me to some doc/information about this "variable expansion" feature you'd like tested?

**Comment by mfojtik** [comment]
@bparees https://github.com/kubernetes/kubernetes/blob/master/docs/design/expansion.md

**Comment by bparees** [comment]
fixed by https://github.com/openshift/origin/pull/5903
