### ISSUE TITLE
Deployment hook pods should inherit the secret volumes of the deployment

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#3739]
Deployment hook pods/containers should inherit the secret volumes of the pod spec being deployed and have those volumes mounted.

The use-case is to enable a deployment hook pod to do things that require the pod's secrets.

@ironcladlou @thoraxe

**Comment by ironcladlou** [comment]
cc @kargakis @liggitt @deads2k

**Comment by smarterclayton** [comment]
Volumes generically are problematic - you won't be able to mount unshareable volumes for instance.  Most of the emptyDir and other volumes are ok, and secrets from the service account are expected.

We can either whitelist by type, or let users specify what volumes they want. I'm pretty sure

**Comment by liggitt** [comment]
you get the service account secret for free if the hook pod specifies the same service account

**Comment by smarterclayton** [comment]
Pretty sure users don't want to have to specify secrets manually, but there isn't an automatic guarantee that you want *every* volume

**Comment by smarterclayton** [comment]
But not if you customized where the secret shows up.

On Thu, Jul 16, 2015 at 2:16 PM, Jordan Liggitt <notifications@github.com>
wrote:

> you get the service account secret for free if the hook pod specifies the
> same service account
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3739#issuecomment-122039462>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by sosiouxme** [comment]
Agreed you may not want every volume. Per https://github.com/openshift/origin/issues/4711 though you may want some. In that case to initialize a PVC that should be shared with the main pod. Perhaps the hook pod should provide a filter of the names of volumes to inherit from the main pod?

**Comment by smarterclayton** [comment]
What are the odds there's just one pod?  Only shared volumes can be reused,
but we'd still need the regular volumes for any pod that fails when it
doesn't have write access to a dir.  Tempted to say all of them should be
copied implicitly.

On Thu, Sep 17, 2015 at 3:49 PM, Luke Meyer <notifications@github.com>
wrote:

> Agreed you may not want every volume. Per #4711
> <https://github.com/openshift/origin/issues/4711> though you may want
> some. In that case to initialize a PVC that should be shared with the main
> pod. Perhaps the hook pod should provide a filter of the names of volumes
> to inherit from the main pod?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3739#issuecomment-141206195>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
Are there any dangers to copying unsharable volumes, or copying ones that are shareable but not intended to actually be shared? Requiring explicit references seems safest... for fuzzy matching, should we keep it simple and based on field selector syntax? Is there some other standard for such pattern matching within the system (e.g. regex)?

**Comment by smarterclayton** [comment]
For unsharable, if you're using an RC with an exclusive unsharable volume
and a post deployment hook, it will hang and never complete.  How about
just a list of the volumes you want, with some way to say "all volumes"

On Fri, Sep 18, 2015 at 9:50 AM, Dan Mace <notifications@github.com> wrote:

> Are there any dangers to copying unsharable volumes, or copying ones that
> are shareable but not intended to actually be shared? Requiring explicit
> references seems safest... for fuzzy matching, should we keep it simple and
> based on field selector syntax? Is there some other standard for such
> pattern matching within the system (e.g. regex)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3739#issuecomment-141456606>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
An explicit list of named volume references and a way to express "all" would be good.

**Comment by ironcladlou** [comment]
Does this need re-prioritized?

**Comment by smarterclayton** [comment]
Reprioritized

On Fri, Sep 18, 2015 at 12:41 PM, Dan Mace <notifications@github.com> wrote:

> Does this need re-prioritized?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3739#issuecomment-141503574>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by pweil-** [comment]
@kargakis - discussed with @ironcladlou, this is LOE and a good candidate for you to take a look at.  @ironcladlou will create a card or BZ for this, it will need QE.

**Comment by ironcladlou** [comment]
Trello card: https://trello.com/c/S1J0hGqB
