### ISSUE TITLE
[RFE] enable logging of commands run via "oc exec"

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#3742]
* At a minimum, it would be good if this was captured somewhere in the master's logs. For example, if someone does an exec of "ls foo/bar" that should somehow be available in the logs with the user who did the command, the pod on which it was run, the project, etc.

**Comment by pweil-** [comment]
This is now included in the audit log when auditing is enabled in the master config
```
 auditConfig:                                                                                        
   enabled: true 
```

includes user, impersonation,  namespace, and uri which shows the pod, container, and command.

```
I0921 05:17:13.712071   21526 audit.go:97] AUDIT: id="e7a15a1a-20e3-47ba-8d6c-a88be1dd7c7c" ip="10.200.136.223" method="POST" user="system:admin" as="<self>" asgroups="" namespace="default" uri="/api/v1/namespaces/default/pods/hello-openshift/exec?command=ls+-al&container=hello-openshift&container=hello-openshift&stderr=true&stdout=true"
``
