### ISSUE TITLE
[RFE] extend granularity rbac of "oc exec"

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#3743]
We should probably consider RBAC to wrap OC exec.

At a minimum we could start with very simple "interactive" vs "non-interactive". That still doesn't prevent all malicious behavior, so the next step forward might be to offer/allow some kind of whitelist/blacklist for commands.

**Comment by liggitt** [comment]
oc exec is already controlled by RBAC, but not at a granular level controlling which commands can run. Controlling allowed commands via policy is similar to field level policy. @deads2k

**Comment by adelton** [comment]
@liggit, could you please elaborate on the "field level policy"?

**Comment by liggitt** [comment]
"field-level policy" meaning policy that is based on contents of submitted objects, instead of attributes determined from the URL of the submitted request

**Comment by simo5** [comment]
@liggit I would like to close this as WONTIFX, RBAC is an API level construct and completely inadequate to represent permissions for oc exec. There should be a different, specific policy (like perhaps sudo based) that deal with that.
