### ISSUE TITLE
Need a better way to keep Web Console DataService type maps in sync

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3751]
We keep a map of types to API paths in `DataService.js`, but have to keep these in sync manually as the API changes. This can cause problems for templates in particular, which can create resources that we don't use in other places in the Web Console. Need a better way to keep the list in sync.

See #3722  

@liggitt

**Comment by jwforres** [comment]
@liggitt wont the api discovery stuff fix this

**Comment by liggitt** [comment]
yeah, this can be closed
