### ISSUE TITLE
API incompatibility creating build configurations

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3754]
Previously the Web Console was creating a build config using

```
        spec: {
          output: {
            to: {
              name: imageSpec.name
            }
          },
          ...
```

The server inferred that it was an image stream, and changed the kind to image stream tag using `:latest`.

This now gives an error:

```
BuildConfig "nodejs-example" is invalid: spec.output.to.kind: required value
```

Using `"kind": "ImageStream"` also results in an error:

```
BuildConfig "nodejs-ex" is invalid: spec.output.to.kind: invalid value 'ImageStream': the target of build output must be an 'ImageStreamTag' or 'DockerImage'
```

See #3752

@bparees @liggitt

**Comment by liggitt** [comment]
Might have happened with the build api refactor

**Comment by bparees** [comment]
yeah there have been some changes along the way in what was acceptable in different api levels and v1 was probably accepting more than it should have.

that said, i'll resume the old behavior of treating empty kind as an imagestreamtag with :latest i guess, unless we have a way to confirm that behavior is not part of our shipped api that we must support.

maybe i'll do a little historical digging first.

in the meantime, i'd still prefer to see the UI create an imagestreamtag with :latest if no other tag info is available, it's our preferred format for objectreferences now.

**Comment by spadgett** [comment]
@bparees Thanks, we've updated the UI in #3752 to use `ImageStreamTag` with `:latest`.
