### ISSUE TITLE
maybe we should run with --rm

### ISSUE THREAD

**Issue by johnjelinek** [openshift/origin#3758]
```
[11:25] <johnjelinek> this reminds me -- in Docker, it caches the build ... but I've noticed that every time I start a build, it takes the full length of time to generate a new image, instead of just handling the diffs. Is there a way to ensure it just handles diffs?
[11:25] <mfojtik_> johnjelinek: you mean Docker strategy cache the immediate layers?
[11:26] <mfojtik_> there is no guarantee that node which execute build will have those layers
[11:26] <johnjelinek> mfojtik_: yes, that's right
[11:26] <mfojtik_> maybe we should run with --rm
[11:26] <johnjelinek> ahh, I see
[11:27] <johnjelinek> mfojtik_: --rm could be good .. I see leftover containers of finished builds that failed to push to the docker registry
[11:27] <johnjelinek> however, it would be really nice to hold onto the leftovers and just retry a push to the docker registry rather than doing a new build over again
[11:27] <mfojtik_> johnjelinek: can you create an issue for this?
[11:28] <johnjelinek> sure
```

**Comment by mfojtik** [comment]
@bparees @smarterclayton FYI

I think we should execute the Docker strategy build with --rm option as the immediate layers will require more storage and there is no guarantee that next build (which can profit from the case) will be scheduled on the same node.

**Comment by ncdc** [comment]
--rm is the default, at least from the `docker build` command line. Need to check the API.

**Comment by smarterclayton** [comment]
I think that's a reasonable default.  I need to sync with you guys on a
future direction for builds.

On Fri, Jul 17, 2015 at 12:31 PM, Michal Fojtik <notifications@github.com>
wrote:

> @bparees <https://github.com/bparees> @smarterclayton
> <https://github.com/smarterclayton> FYI
>
> I think we should execute the Docker strategy build with --rm option as
> the immediate layers will require more storage and there is no guarantee
> that next build (which can profit from the case) will be scheduled on the
> same node.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3758#issuecomment-122333860>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
> I need to sync with you guys on a future direction for builds.

@smarterclayton can you elaborate?  is that just a general observation or does it have a specific impact on this change?

**Comment by smarterclayton** [comment]
With regard to the comment that you can't predict where a build will go so
there is no value in keeping the layers.  True today, but need to consider
future change to that.

On Fri, Jul 17, 2015 at 2:56 PM, Ben Parees <notifications@github.com>
wrote:

> I need to sync with you guys on a future direction for builds.
>
> @smarterclayton <https://github.com/smarterclayton> can you elaborate? is
> that just a general observation or does it have a specific impact on this
> change?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3758#issuecomment-122372762>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
@mfojtik @ncdc I certainly see "docker build" claim it is removing intermediate layers.  @mfojtik you think our programmatic docker build invocation is not doing that?

**Comment by mfojtik** [comment]
@bparees i'm going to check.

**Comment by mfojtik** [comment]
@bparees we do have `NoCache` option which is bool and by default I think it is `false`. Which means we are building with cache enabled.

I can:

1) Change the field to `Cache` (or `EnableCache`) which will make it false by default.
2) Change the default value to `false`.

I think 1) is more doable but it is "more" backward incompatible change. What do you think? ( @smarterclayton )

**Comment by ncdc** [comment]
It's not NoCache - it's rm in the api that needs to be set.

**Comment by bparees** [comment]
Yeah nocache is a different thing (though if you use --rm then caching won't work very well).

**Comment by ncdc** [comment]
Caching still works with --rm (--rm is true by default when you docker build)

**Comment by ncdc** [comment]
--rm affects removing intermediate containers, not images

**Comment by bparees** [comment]
@mfojtik ok this all comes back to what the programmatic invocation is doing w/ respect to the rm flag.  if it's being treated as set, we should do so.

**Comment by johnjelinek** [comment]
I upgraded to `v1.0.2` (by rebuilding my cluster) and now caching seems to work:
```
I0720 21:25:58.024214       1 tar.go:133] Adding to tar: /tmp/docker-build375728938/Dockerfile as Dockerfile
Step 0 : FROM library/debian:unstable
 ---> bf0fd686de78
Step 1 : MAINTAINER John Jelinek IV <john@johnjelinek.com>
 ---> Using cache
 ---> 35b7bf2dc615
Step 2 : ENV PUSHPIN_VERSION 1.4.0
 ---> Using cache
 ---> 5150a9c54561
Step 3 : RUN apt-get update && apt-get install -y pkg-config libqt4-dev libqca2-dev libqca2-plugin-ossl libqjson-dev libzmq3-dev python-zmq python-setproctitle python-jinja2 python-tnetstring python-sortedcontainers mongrel2-core zurl git build-essential
 ---> Using cache
 ---> 05cde2d50aa1
Step 4 : RUN git clone git://github.com/fanout/pushpin.git /pushpin && cd /pushpin && git checkout tags/v"$PUSHPIN_VERSION" && git submodule init && git submodule update && make && make install
 ---> Using cache
 ---> 1f161f84389a
Step 5 : RUN apt-get clean && rm -fr /var/lib/apt/lists/* && rm -fr /tmp/* && rm -fr /pushpin
 ---> Using cache
 ---> 49bc973a8a22
Step 6 : EXPOSE 7999 5561
 ---> Using cache
 ---> a79e2804c92b
Step 7 : VOLUME /config
 ---> Running in 54f6bb12daa8
 ---> 1ac2d63d2b42
Removing intermediate container 54f6bb12daa8
Step 8 : CMD pushpin
 ---> Running in 9ed4a53ad61b
 ---> 75ca10295c23
Removing intermediate container 9ed4a53ad61b
Step 9 : ENV OPENSHIFT_BUILD_NAME "pushpin-2" OPENSHIFT_BUILD_NAMESPACE "pushpin" OPENSHIFT_BUILD_SOURCE "https://gist.github.com/johnjelinek/5532e09d53edc937b058"
 ---> Running in ea23c0829e35
 ---> 3dba0b4476ae
Removing intermediate container ea23c0829e35
Successfully built 3dba0b4476ae
```

**Comment by bparees** [comment]
1) we are passing the equivalent of --rm to our docker build and have been since 2014 from what i can see:
https://github.com/openshift/origin/blob/master/pkg/build/builder/dockerutil.go#L97

2) we are now retrying pushes a few times if the push fails

3) cache/no-cache handles the orthogonal issue of whether existing layers should be reused.

Between those 3 things, I think we can close this issue.  @johnjelinek feel free to reopen if you think we've missed something.
