### ISSUE TITLE
scc/privileged RunAsAny does not apply

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#3762]
If I want to run a pod as root or a specific user, I cannot do so by editing the privileged SCC as described in https://docs.openshift.org/latest/admin_guide/manage_scc.html#grant-access-to-the-privileged-scc

If I add the service account user in the SCC, a pod is then allowed to mount host volumes, but not run as root. I have even tried adding the group `system:authenticated` to scc/privileged and it was still not allowed. Only when I modified the restricted SCC to allow RunAsAny could the pod run with the intended user.

@pweil- this is what I was trying to catch up with you about the other day. Wasn't sure if it was just an OSE bug but it seems to still be in Origin too.

**Comment by sosiouxme** [comment]
My test case was elasticsearch. See https://docs.openshift.org/latest/admin_guide/aggregate_logging.html#creating-an-elasticsearch-cluster

Those docs don't mention it, but it runs as root and then switches users. If it's not run as root, the only log you get is:

    chown: changing ownership of ‘/usr/share/elasticsearch/data’: Operation not permitted

I would further add that the SCC docs need an example of adding a service account user to the scc (instead of just e2euser), which is what you would usually want.

**Comment by pweil-** [comment]
@sosiouxme - I suspect what you're running in to is the fact that, unless specific requests are made, the pod will validate under the MOST restrictive SCC available that validates.  If you did not make any requests to run outside the normal range of the restricted SCC you would've still validated against it.


> If I add the service account user in the SCC, they're allowed to mount host volumes, but not run as root.

This does not make sense to me, if you made a request to mount a host volume, validated against the privileged SCC, and the privileged SCC had a user strategy of RunAsAny you would be able to run as root.  SCCs are not combined or applied partially.

FYI, you can check the SCC that you validated against in the annotations on the pod.  For more information about what SCCs were available to you the admission controller performs logging at V(4) if you grep the server logs for admission.  It will tell you who it sees creating the pod, what SCCs they have access to, and which SCC they validated against (or errors if none validated).

**Comment by sosiouxme** [comment]
@pweil- you are right, the pod annotation includes this:

    openshift.io/scc: restricted

It sounds like you are saying the pod needs to declare that it needs RunAsAny so that it can be validated against the privileged SCC. If so, is there doc on that? How would I modify the definition at https://docs.openshift.org/latest/admin_guide/aggregate_logging.html#creating-an-elasticsearch-cluster to declare that?

**Comment by pweil-** [comment]
rebuilding master and checking the example right now, you should just be able to add a security context to the pod spec that uses a `runAsUser: 0` which would be invalid against the restricted SCC but valid against the privileged SCC that you gave the SA access to.

**Comment by sosiouxme** [comment]
Trying to test this but I keep getting a syntax error trying to add the securityContext "did not find expected key" which isn't so helpful.

**Comment by sosiouxme** [comment]
Nevermind, I just can't write YAML. It works.

So, happy to just transfer this to a docs bug.

**Comment by pweil-** [comment]
thanks for testing it, my build has decided to take forever.  Tag me on the doc bug, I failed to mention that the SCCs are ordered and validated most restrictive to least and I should mention the annotation as well.
