### ISSUE TITLE
Make builders follow deployer pattern more closely

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#377]
@csrwng can you take a todo to follow up on the builders and make them match the deployer pattern more closely? They don't need to be flags right now, but over time we probably want to have typed ENV vars or CLI args that you can set env into more easily.

**Comment by ironcladlou** [comment]
Can this be closed, @csrwng?

**Comment by csrwng** [comment]
@ironcladlou - we still don't follow the deployer pattern with the builders. We're only taking the single env var with the build definition right now, so I think this issue is still valid.

**Comment by bparees** [comment]
i'm not fully understanding how the deployment pod handles this (it calls back to the api server to get the details about the deploymentconfig?  what access token does it use to do that?) but it seems like how builds are doing it (essentially passing the buildconfig as a parameter via an environment variable) isn't unreasonable as a solution, so i don't see why we'd invest in changing this.

but as an side, i would like to know how deployment pods are making calls back to the api server, if that's what is being done.

**Comment by csrwng** [comment]
closing for now - please reopen if you think it's still needed
