### ISSUE TITLE
Route spec is getting host set, but it should be inferred

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3771]
When a route has no host set by a user, the value should be left unset in the spec field (and inferred by the router).  The value should based on the route name, not the service name.

    $ oc expose svc/foo --name bar

creates a route with spec host `foo.<project>.<suffix>` set (the route name should be `bar.<project>.<suffix>`) and the spec.host field should be implicit, not set.  We should at minimum be setting a status field, not a spec field.

Blocks easy setup of blue green deployments.

**Comment by bparees** [comment]
fixed.

**Comment by smarterclayton** [comment]
Bot, you were confused.

**Comment by liggitt** [comment]
leaving it blank makes it hard for clients to know what URL to show/link... there's an annotation indicating whether the host was a generated default

**Comment by pweil-** [comment]
Per the last bug review convo, closing this in favor of the BZ issue that encompasses the naming for certificates https://bugzilla.redhat.com/show_bug.cgi?id=1249108

Also, https://github.com/openshift/origin/issues/4015

**Comment by smarterclayton** [comment]
To Jordan's comment, there should be a status field that shows the actual
host value.  Leaving it blank should mean that the user didn't specify
one.  If a user then set a value, we then wouldn't have to do anything to
the annotation (should only have one way to indicate something is set).

On Fri, Aug 21, 2015 at 9:32 AM, Paul Weil <notifications@github.com> wrote:

> Closed #3771 <https://github.com/openshift/origin/issues/3771>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3771#event-388794951>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment]
as long as there is a way for clients to get the hostname to use in links, and know whether the hostname was generated or not, I'm good. UI will need updates if we change the current annotation mechanism

**Comment by smarterclayton** [comment]
I think it's looking like we'll drop routes in favor of the upstream object
and maybe introduce a new route object.

On Fri, Aug 21, 2015 at 10:39 AM, Jordan Liggitt <notifications@github.com>
wrote:

> as long as there is a way for clients to get the hostname to use in links,
> and know whether the hostname was generated or not, I'm good. UI will need
> updates if we change the current annotation mechanism
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3771#issuecomment-133447993>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift
