### ISSUE TITLE
allow router to force redirect from http to https

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#3773]
following a discussion internally it would be nice if the router could support the redirection from http to https

**Comment by gravis** [comment]
while it can be done in the service itself, it's more the role of the router to handler this case, I agree.

**Comment by deanpeterson** [comment]
It seems this should already be possible with the default HAProxy router.  Can anyone provide instructions for this.  I am now running into this problem as well.

**Comment by gravis** [comment]
Yes, solution is in #5224
and already available. @smaterclayton  We can safely close this issue. Thanks

**Comment by deanpeterson** [comment]
Great, thanks!

**Comment by gravis** [comment]
Notifications don't seem to work when I reply by email, so @smarterclayton: you can close this issue.
