### ISSUE TITLE
oc status does not elide duplicate deployment config

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3775]
When two services overlap a DC, it should only be printed in detail once:

```
service ab-example - 172.30.76.170:8080
  ab-example deploys deployment-example:latest 
    #2 deployed about a minute ago - 1 pod
    #1 deployed 6 minutes ago
  ab-example-b deploys deployment-example:latest 
    #2 deployed 58 seconds ago - 1 pod
    #1 deployed 3 minutes ago

service ab-example-b - 172.30.114.157:8080
  ab-example-b deploys deployment-example:latest 
    #2 deployed 58 seconds ago - 1 pod
    #1 deployed 3 minutes ago
```

Should be

```
service ab-example - 172.30.76.170:8080
  ab-example deploys deployment-example:latest 
    #2 deployed about a minute ago - 1 pod
    #1 deployed 6 minutes ago
  ab-example-b deploys deployment-example:latest 
    #2 deployed 58 seconds ago - 1 pod
    #1 deployed 3 minutes ago

service ab-example-b - 172.30.114.157:8080
  ab-example-b deploys deployment-example:latest ...
```

**Comment by deads2k** [comment]
I'm not crazy about that because it means that you can't see whether "service ab-example-b" has any pods fulfilling it.  How do you feel about displaying only those deployments that have pods for the second service?

Actually, why is it important to know about old deployments without pods at all?

**Comment by smarterclayton** [comment]
On Jul 21, 2015, at 2:50 PM, David Eads <notifications@github.com> wrote:

I'm not crazy about that because it means that you can't see whether
"service ab-example-b" has any pods fulfilling it. How do you feel about
displaying only those deployments that have pods for the second service?


I meant the "..." To indicate that the item was already shown above (so you
scan up).  It shouldn't be hard to pair them, but I don't want to show the
same info or warnings twice

Actually, why is it important to know about old deployments without pods at
all?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3775#issuecomment-123439417>.

**Comment by smarterclayton** [comment]
Knowing when prior deployments happened is pretty critical - that's the
primary source of change in your environment, which is the primary source
of bugs.

On Jul 21, 2015, at 2:50 PM, David Eads <notifications@github.com> wrote:

I'm not crazy about that because it means that you can't see whether
"service ab-example-b" has any pods fulfilling it. How do you feel about
displaying only those deployments that have pods for the second service?

Actually, why is it important to know about old deployments without pods at
all?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3775#issuecomment-123439417>.

**Comment by deads2k** [comment]
@smarterclayton I still don't like the `...`.  Do you still like it?

**Comment by smarterclayton** [comment]
I don't particularly care what the indication is, just that we stop
repeating ourselves for redundant info.  Terminal characters are precious -
we should spend them only on the things that truly matter.  Once we've said
it once, we don't need to say it again.  If there's a better way to
represent that than an ellipsis, I'm open to it.

**Comment by deads2k** [comment]
@jwforres @fabianofranz Any advice on presentation?

**Comment by fabianofranz** [comment]
Use `....` and if it was used suggest `-v|--verbose` which would print the complete, redundant version?

**Comment by smarterclayton** [comment]
I don't know that suggesting is really that common.  If i have multiple DCs
pointing to the same thing, I'm going to see the previous data above.  Why
would I want to see the redundant data?

**Comment by deads2k** [comment]
> I don't know that suggesting is really that common.  If i have multiple DCs
> pointing to the same thing, I'm going to see the previous data above.  Why
> would I want to see the redundant data?

I like the locality of information over terse output.

**Comment by smarterclayton** [comment]
I don't.  The point of this output is to convey the important information
in minimal space.  Being redundant wastes space and reduces comprehension.
Any user who has this setup is already someone trying to do something
specific - forcing them to see the data presented each time is misleading
(it may convince them they aren't coupled)

**Comment by fabianofranz** [comment]
Another idea but I still prefer the ellipsis

```
service ab-example - 172.30.76.170:8080
  ab-example deploys deployment-example:latest 
    #2 deployed about a minute ago - 1 pod
    #1 deployed 6 minutes ago
  ab-example-b deploys deployment-example:latest [1]

service ab-example-b - 172.30.114.157:8080
  ab-example-b deploys deployment-example:latest [1]

[1] #2 deployed 58 seconds ago - 1 pod
    #1 deployed 3 minutes ago
```

**Comment by smarterclayton** [comment]
Yeah, I think that's worse than either.   If you had 5 of these it would be
a disaster.
