### ISSUE TITLE
It should be easy to "split" or "shard" a deployment config under a service via the CLI

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3777]
#3769 describes A/B deployments, which are currently too hard to implement in the CLI (user has to add common labels to a bunch of objects).  It should either be possible to create a new shard based on an existing DC/SVC, or parameterize new-app appropriately so that you can set up a shard originally.  In addition, because we specify the DC selector and template selector in new-app (vs defaulting them from the DC labels), you have to add labels to 2 fields per object, then change the service to use the new common label.  We need to find the most sustainable and easiest to implement tool path and then implement it.

**Comment by kargakis** [comment]
Related:
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions
https://github.com/kubernetes/kubernetes/issues/11505
