### ISSUE TITLE
Editing a deployment config to change the template labels does not trigger a new deployment

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3780]
Changing the template labels of a deployment config should trigger a deployment.

Discovered by #3769

**Comment by ironcladlou** [comment]
What field are you referring to here? I just made a unit test to add coverage for a change to `config.Template.ControllerTemplate.Template.Labels` and got a diff.

**Comment by smarterclayton** [comment]
It wasn't triggering a deployment.  I changed selector (shouldn't cause
deployment) and template labels (should have).

On Jul 21, 2015, at 2:13 PM, Dan Mace <notifications@github.com> wrote:

What field are you referring to here? I just made a unit test to add
coverage for a change to config.Template.ControllerTemplate.Template.Labels
and got a diff.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3780#issuecomment-123420879>.

**Comment by ironcladlou** [comment]
Verified using `oc edit`.

**Comment by ironcladlou** [comment]
My unit test was bad; I now reproduced this in an improved test for the deployment config controller. Looks like an issue with `kapi.Semantic.DeepEqual`.

**Comment by ironcladlou** [comment]
Oh, now I see the issue. We only compare `template.spec` for config change detection. I'm not sure why we don't compare the `PodTemplate` itself. Can you think of a reason not to compare the `PodTemplate`?
