### ISSUE TITLE
Deployment pod is not cleaned up promptly, deployment seems to lag unnecessarily

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3781]
When triggering deployments, the end of the deployment does not seem to align with when the pod is available and ready.  This could be a number of things - readiness check getting delayed (maybe a bug in kubelet), deployment controller not properly ending its loop, or a process pod not stopping within a window.

Seems to happen occasionally when I do `oc deploy foo --latest` - maybe 1/3 times it lags longer than it should.

We need to investigate more - it results in a perceived "bug" in deployment.  If we can prove it's actually all correctly timed then we should look at cleaning up the UI to give a better description of what is happening.

Noticed while working on #3769

**Comment by ironcladlou** [comment]
Do you mean that the deployment's status is transitioning to "Complete" too long after the deployment is actually done and pods available?

**Comment by smarterclayton** [comment]
Yes

On Wed, Jul 22, 2015 at 9:52 AM, Dan Mace <notifications@github.com> wrote:

> Do you mean that the deployment's status is transitioning to "Complete"
> too long after the deployment is actually done and pods available?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3781#issuecomment-123728944>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
We transition to complete when the deployer pod exits and we get a watch event for the pod. Do you know if the kubelet is updating Pod.Status.Phase on some interval, or based on events? If it's interval based then there would be a big variance depending on whether the pod completed towards the end of the interval timer vs. the beginning.

**Comment by smarterclayton** [comment]
It's possible that the kubelet missed an update window (hit a conflict and
waited until the next kubelet status sync interval)

On Wed, Jul 22, 2015 at 12:54 PM, Dan Mace <notifications@github.com> wrote:

> We transition to complete when the deployer pod exits and we get a watch
> event for the pod. Do you know if the kubelet is updating Pod.Status.Phase
> on some interval, or based on events? If it's interval based then there
> would be a big variance depending on whether the pod completed towards the
> end of the interval timer vs. the beginning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3781#issuecomment-123790574>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
@smarterclayton is this still a concern? Have you see it happen again?

**Comment by smarterclayton** [comment]
It's hard to say whether it was readiness or not, but I still see long lags.

On Tue, Aug 18, 2015 at 2:24 PM, Dan Mace <notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton> is this still a
> concern? Have you see it happen again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3781#issuecomment-132307728>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
Deployer container log:
```
...
I0819 10:52:18.687049       1 recreate.go:143] Deployment deploytester-1 successfully made active
```

Master log has nothing relevant until about 10 seconds later:
```
I0819 10:52:28.294204   11651 replication_controller.go:201] No controllers found for pod deploytester-1-deploy, replication manager will avoid syncing
I0819 10:52:28.295709   11651 config.go:276] Setting pods for source api : {[0xc20b51f800 0xc20dd30c00] 0 api}
I0819 10:52:28.297495   11651 status_manager.go:169] Status for pod "deploytester-1-deploy_test" updated successfully
I0819 10:52:28.311068   11651 replication_controller.go:383] Finished syncing controller "test/deploytester-1" (102.656µs)
I0819 10:52:28.311272   11651 controller.go:117] Updated Deployment test/deploytester-1 status from Running to Complete
```

The container exits, 10 seconds later the upstream infra reacts and updated the pod status. Within millseconds, OpenShift reacts and sets the deployment status in response to the pod status update.

It seems like we're doing everything right downstream and the delay is in the Kube code reacting to the container. Agree?

**Comment by ironcladlou** [comment]
Looked into the kubelet code. Status on the pod is updated per pod sync [here](https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go#L1143). Unless the kubelet is reacting to some event received from docker regarding a pod's container state changing (causing a chain of event reactions all the way back to origin's pod watch), seems like this will always be limited to the interval the kubelet is polling containers for pods. I'm still learning this kubelet code.

**Comment by smarterclayton** [comment]
Ok, then this can be marked upstream and probably closed on
https://github.com/kubernetes/kubernetes/issues/12540

On Wed, Aug 19, 2015 at 5:20 PM, Dan Mace <notifications@github.com> wrote:

> Looked into the kubelet code. Status on the pod is updated per pod sync
> here
> <https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go#L1143>.
> Unless the kubelet is reacting to some event received from docker regarding
> a pod's container state changing (causing a chain of event reactions all
> the way back to origin's pod watch), seems like this will always be limited
> to the interval the kubelet is polling containers for pods. I'm still
> learning this kubelet code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3781#issuecomment-132789151>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by kargakis** [comment]
@smarterclayton needs closing
