### ISSUE TITLE
Create better experience around container user security

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#3793]
We should have a better experience around restrictions for which user a container runs as.  Currently, the default is that service accounts receive access to the restricted security context constraints, which:
1.  Prevents users from running privileged containers
2.  Makes containers run as a random UID

People run into rough edges when they want to:
1.  Create containers that run as root
2.  Create containers that run as the user/group specified in the docker image metadata

We need some combination of:
1.  Improvement in making users aware of the consequences of running as root and how to enable the features they want
2.  Making it easy for administrators to set convenient defaults for their users
3.  Making it easier to switch between security context constraints, etc

@pweil- @ncdc @smarterclayton @liggitt @deads2k

**Comment by smarterclayton** [comment]
Any updates on this?  Should include discussion of GID use

On Mon, Jul 20, 2015 at 4:43 PM, Paul Morie <notifications@github.com>
wrote:

> We should have a better experience around restrictions for which user a
> container runs as. Currently, the default is that service accounts receive
> access to the restricted security context constraints, which:
>
>    1. Prevents users from running privileged containers
>    2. Makes containers run as a random UID
>
> People run into rough edges when they want to:
>
>    1. Create containers that run as root
>    2. Create containers that run as the user/group specified in the
>    docker image metadata
>
> We need some combination of:
>
>    1. Improvement in making users aware of the consequences of running as
>    root and how to enable the features they want
>    2. Making it easy for administrators to set convenient defaults for
>    their users
>    3. Making it easier to switch between security context constraints, etc
>
> @pweil- <https://github.com/pweil-> @ncdc <https://github.com/ncdc>
> @smarterclayton <https://github.com/smarterclayton> @liggitt
> <https://github.com/liggitt> @deads2k <https://github.com/deads2k>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3793>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by tnguyen-rh** [comment]
Documentation tracking via:
https://bugzilla.redhat.com/show_bug.cgi?id=1254767
