### ISSUE TITLE
How to define global env variables at the node level

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#3796]
Hi All,
    I would like to know if it possible to define environment variable at the node level, it means that all the containers (pod) running on that node will have by default all the node's env. variables, any idea?

Thanks.

**Comment by bparees** [comment]
it is not possible, no.

**Comment by roldancer** [comment]
In OSE V2.X it was possible to define env. variables at the node level, this feature could be very useful for on-premise PaaS, I hope to see this feature in OSE v3.

Thanks.
