### ISSUE TITLE
Wrong oc binary in 1.0.3 release ?

### ISSUE THREAD

**Issue by vbehar** [openshift/origin#3798]
Hi,

according to https://github.com/openshift/origin/releases/tag/v1.0.3, the oc client should have its own binary, but in the macos package I can see that it is not the case (same checksum as the openshift binary).

When compiling from source, I confirm that the oc binary is not the same as the openshift one, and is smaller (50 MB instead of 80 MB).

Perhaps the oc binary in the 1.0.3 is not the right one ? (although it is working correctly, and "oc version" report version 1.0.3)

Vincent (just trying to have a smaller oc binary client ;-)

**Comment by chmouel** [comment]
can reproduce :) on MacosX compiling the binary goes down to 50mb

**Comment by smarterclayton** [comment]
Looks like it didn't make it into the build output correctly.  Will dig in.

**Comment by liggitt** [comment]
was this resolved?

**Comment by smarterclayton** [comment]
Yes
