### ISSUE TITLE
Support hostDir backwards compat

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3822]
Upstream renamed hostDir to hostPath.  Needs a conversion.

**Comment by liggitt** [comment]
Are you sure? v1.0.0 used `hostPath`:
https://github.com/openshift/origin/blob/v1.0.0/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1/types.go#L203

**Comment by smarterclayton** [comment]
Ok, then never mind.

On Jul 22, 2015, at 10:21 PM, Jordan Liggitt <notifications@github.com>
wrote:

Are you sure? v1.0.0 used hostPath:
https://github.com/openshift/origin/blob/v1.0.0/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1/types.go#L203

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3822#issuecomment-123932447>.

**Comment by smarterclayton** [comment]
Then we just need to find any references in our repo.

On Jul 22, 2015, at 10:21 PM, Jordan Liggitt <notifications@github.com>
wrote:

Are you sure? v1.0.0 used hostPath:
https://github.com/openshift/origin/blob/v1.0.0/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1/types.go#L203

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3822#issuecomment-123932447>.

**Comment by liggitt** [comment]
I searched the whole repo and found nothing... did you see something broken that spawned this issue?

**Comment by smarterclayton** [comment]
QE hit this

On Jul 22, 2015, at 10:46 PM, Jordan Liggitt <notifications@github.com>
wrote:

I searched the whole repo and found nothing... did you see something broken
that spawned this issue?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3822#issuecomment-123940270>.

**Comment by bmeng** [comment]
@smarterclayton 
After I change the hostDir to hostPath, the volume in the pod is still emptyDir
https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/authorization/scc/pod_requests_hostdir.json

**Comment by smarterclayton** [comment]
Can you add what you submitted to create the pod/rc/dc and the output of
"oc get pods -o yaml" after you create it here?

On Wed, Jul 22, 2015 at 11:24 PM, Bo Meng <notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton>
> After I change the hostDir to hostPath, the volume in the pod is still
> emptyDir
>
> https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/authorization/scc/pod_requests_hostdir.json
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3822#issuecomment-123950443>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bmeng** [comment]
pod.json
{
  "apiVersion":"v1",
  "kind": "Pod",
  "metadata": {
    "name": "disk-pod",
    "labels": {
      "name": "disk-pod"
    }
  },
  "spec": {
    "containers": [{
      "name": "disk-pod",
      "image": "bmeng/hello-openshift",
      "volumeMounts" : [
                {
                "name":"testvol",
                "mountPath" : "/tmp/testdir"
                }
               ]
    }],
      "volumes": [{
                "name" : "testvol",
                "source" : {
                        "hostPath": {
                                "path": "/tmp/testdir"
                                   }
                           }
                }]

  }
}


output:
$ oc get po -o yaml
apiVersion: v1
items:
- apiVersion: v1  
  kind: Pod
  metadata:
    annotations:  
      openshift.io/scc: restricted
    creationTimestamp: 2015-07-23T03:22:01Z
    labels:
      name: disk-pod
    name: disk-pod
    namespace: u1p1
    resourceVersion: "120477"
    selfLink: /api/v1/namespaces/u1p1/pods/disk-pod
    uid: fbc7ab98-30e9-11e5-a95c-5254009c1bd6
  spec:
    containers:   
    - image: bmeng/hello-openshift
      imagePullPolicy: IfNotPresent
      name: disk-pod
      resources: {}
      securityContext:
        privileged: false
        runAsUser: 1000030000
        seLinuxOptions:
          level: s0:c6,c0
      terminationMessagePath: /dev/termination-log
      volumeMounts:
      - mountPath: /tmp/testdir
        name: testvol
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-apw8f
        readOnly: true
    dnsPolicy: ClusterFirst
    host: node2.bmeng.local
    imagePullSecrets:
    - name: default-dockercfg-gejb9
    nodeName: node2.bmeng.local
    restartPolicy: Always
    serviceAccount: default
    serviceAccountName: default
    volumes:
    - emptyDir: {}
      name: testvol
    - name: default-token-apw8f
      secret:
        secretName: default-token-apw8f
  status:
    conditions:   
    - status: "True"
      type: Ready 
    containerStatuses:
    - containerID: docker://62eed54d20d3aa348984db5d8f1d8e00a600722298b4a856eb6f53294565e085
      image: bmeng/hello-openshift
      imageID: docker://6ffea4d14661afe592781a665886e1d8085de9e69599d83a67c766c9d966cfa3
      lastState: {}
      name: disk-pod
      ready: true 
      restartCount: 0
      state:
        running:  
          startedAt: 2015-07-23T03:22:05Z
    hostIP: 10.66.129.116
    phase: Running
    podIP: 10.1.1.3
    startTime: 2015-07-23T03:22:01Z
kind: List
metadata: {}

**Comment by bmeng** [comment]
$ cat pod.json
```
{
  "apiVersion":"v1",
  "kind": "Pod",  
  "metadata": {   
    "name": "disk-pod",
    "labels": {   
      "name": "disk-pod"
    }
  },
  "spec": {
    "containers": [{
      "name": "disk-pod",
      "image": "bmeng/hello-openshift",
      "volumeMounts" : [
                { 
                "name":"testvol",
                "mountPath" : "/tmp/testdir"
                } 
               ]  
    }],
      "volumes": [{
                "name" : "testvol",
                "source" : {
                        "hostPath": {
                                "path": "/tmp/testdir"
                                   }
                           }
                }]

  }
}
```

output:
$ oc get po -o yaml
```
apiVersion: v1
items:
- apiVersion: v1  
  kind: Pod
  metadata:
    annotations:  
      openshift.io/scc: restricted
    creationTimestamp: 2015-07-23T03:22:01Z
    labels:
      name: disk-pod
    name: disk-pod
    namespace: u1p1
    resourceVersion: "120477"
    selfLink: /api/v1/namespaces/u1p1/pods/disk-pod
    uid: fbc7ab98-30e9-11e5-a95c-5254009c1bd6
  spec:
    containers:   
    - image: bmeng/hello-openshift
      imagePullPolicy: IfNotPresent
      name: disk-pod
      resources: {}
      securityContext:
        privileged: false
        runAsUser: 1000030000
        seLinuxOptions:
          level: s0:c6,c0
      terminationMessagePath: /dev/termination-log
      volumeMounts:
      - mountPath: /tmp/testdir
        name: testvol
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-apw8f
        readOnly: true
    dnsPolicy: ClusterFirst
    host: node2.bmeng.local
    imagePullSecrets:
    - name: default-dockercfg-gejb9
    nodeName: node2.bmeng.local
    restartPolicy: Always
    serviceAccount: default
    serviceAccountName: default
    volumes:
    - emptyDir: {}
      name: testvol
    - name: default-token-apw8f
      secret:
        secretName: default-token-apw8f
  status:
    conditions:   
    - status: "True"
      type: Ready 
    containerStatuses:
    - containerID: docker://62eed54d20d3aa348984db5d8f1d8e00a600722298b4a856eb6f53294565e085
      image: bmeng/hello-openshift
      imageID: docker://6ffea4d14661afe592781a665886e1d8085de9e69599d83a67c766c9d966cfa3
      lastState: {}
      name: disk-pod
      ready: true 
      restartCount: 0
      state:
        running:  
          startedAt: 2015-07-23T03:22:05Z
    hostIP: 10.66.129.116
    phase: Running
    podIP: 10.1.1.3
    startTime: 2015-07-23T03:22:01Z
kind: List
metadata: {}
```

**Comment by smarterclayton** [comment]
Ah - there is no "source" object - just place "hostPath" directly in the
volumes array. Source is only part of the go source object, not the json

On Jul 23, 2015, at 12:12 AM, Bo Meng <notifications@github.com> wrote:

$ cat pod.json

{
  "apiVersion":"v1",
  "kind": "Pod",
  "metadata": {
    "name": "disk-pod",
    "labels": {
      "name": "disk-pod"
    }
  },
  "spec": {
    "containers": [{
      "name": "disk-pod",
      "image": "bmeng/hello-openshift",
      "volumeMounts" : [
                {
                "name":"testvol",
                "mountPath" : "/tmp/testdir"
                }
               ]
    }],
      "volumes": [{
                "name" : "testvol",
                "source" : {
                        "hostPath": {
                                "path": "/tmp/testdir"
                                   }
                           }
                }]

  }
}

output:
$ oc get po -o yaml

apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: restricted
    creationTimestamp: 2015-07-23T03:22:01Z
    labels:
      name: disk-pod
    name: disk-pod
    namespace: u1p1
    resourceVersion: "120477"
    selfLink: /api/v1/namespaces/u1p1/pods/disk-pod
    uid: fbc7ab98-30e9-11e5-a95c-5254009c1bd6
  spec:
    containers:
    - image: bmeng/hello-openshift
      imagePullPolicy: IfNotPresent
      name: disk-pod
      resources: {}
      securityContext:
        privileged: false
        runAsUser: 1000030000
        seLinuxOptions:
          level: s0:c6,c0
      terminationMessagePath: /dev/termination-log
      volumeMounts:
      - mountPath: /tmp/testdir
        name: testvol
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-apw8f
        readOnly: true
    dnsPolicy: ClusterFirst
    host: node2.bmeng.local
    imagePullSecrets:
    - name: default-dockercfg-gejb9
    nodeName: node2.bmeng.local
    restartPolicy: Always
    serviceAccount: default
    serviceAccountName: default
    volumes:
    - emptyDir: {}
      name: testvol
    - name: default-token-apw8f
      secret:
        secretName: default-token-apw8f
  status:
    conditions:
    - status: "True"
      type: Ready
    containerStatuses:
    - containerID:
docker://62eed54d20d3aa348984db5d8f1d8e00a600722298b4a856eb6f53294565e085
      image: bmeng/hello-openshift
      imageID: docker://6ffea4d14661afe592781a665886e1d8085de9e69599d83a67c766c9d966cfa3
      lastState: {}
      name: disk-pod
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2015-07-23T03:22:05Z
    hostIP: 10.66.129.116
    phase: Running
    podIP: 10.1.1.3
    startTime: 2015-07-23T03:22:01Z
kind: List
metadata: {}

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3822#issuecomment-123958058>.

**Comment by bmeng** [comment]
That works after remove the "source".
Thanks very much!
