### ISSUE TITLE
`oc` binary not in release output zip

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3823]

**Comment by smarterclayton** [comment]
This missed 1.0.3 because it hadn't merged.  It *should* be in but someone needs to test (does a release build create a tar with two differently sized binaries).

**Comment by fabianofranz** [comment]
@smarterclayton right now in master the release tar created by `hack/build-release.sh` has all binaries, including `oc`, with the same size. I'll investigate.

**Comment by smarterclayton** [comment]
Have a fix
