### ISSUE TITLE
Builds are not sorted properly

### ISSUE THREAD

**Issue by mnagy** [openshift/origin#3826]
```
[vagrant@openshiftdev ~]$ oc get builds --watch
NAME                  TYPE      STATUS      POD
ruby-hello-world-1    Source    Complete    ruby-hello-world-1-build
ruby-hello-world-10   Source    Cancelled   ruby-hello-world-10-build
ruby-hello-world-2    Source    Error       ruby-hello-world-2-build
ruby-hello-world-3    Source    Cancelled   ruby-hello-world-3-build
ruby-hello-world-4    Source    Cancelled   ruby-hello-world-4-build
ruby-hello-world-5    Source    Cancelled   ruby-hello-world-5-build
ruby-hello-world-6    Source    Error       ruby-hello-world-6-build
ruby-hello-world-7    Source    Cancelled   ruby-hello-world-7-build
ruby-hello-world-8    Source    Cancelled   ruby-hello-world-8-build
ruby-hello-world-9    Source    Complete    ruby-hello-world-9-build
```

Maybe we should use few zeroes, or just do a better numeric sort?

**Comment by bparees** [comment]
not sure how easy this will be to fix, it's probably an upstream change.

**Comment by mnagy** [comment]
I did a quick research and the best solution in my opinion would be to sort builds here:
https://github.com/openshift/origin/blob/master/pkg/cmd/cli/describe/printer.go#L194
Though after some thought, sorting them according to a timestamp would be better.

@bparees can you assign this to me please?

**Comment by rhcarvalho** [comment]
I can reuse code from https://github.com/openshift/origin/pull/3890, it would be easy to solve this, sorting builds by (reverse) `CreationTimestamp`.
