### ISSUE TITLE
templates with same name in different namespaces cannot be differentiated in ui

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#3833]
If you "copy" the mysql-ephemeral template from the `openshift` namespace into the `arbitrary` namespace (my own), and try to create a new template instance, the webui will show me the same template name twice, and I do not know which comes from where.

This is a problem if the **reason** I copied the template into my own namespace was to make small changes.

How do I know which one is coming from my namespace?

Perhaps we need to segregate the templates, listing the current namespace first, THEN the rest?

**Comment by liggitt** [comment]
@spadgett I thought we surfaced the source project for the templates

**Comment by spadgett** [comment]
@thoraxe We show the namespace now. I think you might be on an old build.

<img width="733" alt="openshift_web_console_and_blue_jeans_network___video_collaboration_in_the_cloud" src="https://cloud.githubusercontent.com/assets/1167259/8834656/7b323924-3083-11e5-8b71-b3345694c484.png">

**Comment by spadgett** [comment]
Added in #3293

**Comment by thoraxe** [comment]
This depiction is OK, but it doesn't seem good enough.

Why wouldn't we present what the user owns (their own namespace) first, and clearly delineate from what's in OpenShift generally (openshift namespace)?

In the case of two templates with identical names and descriptions, yes, you'll see the differing namespace, but it is a very awkward user experience and is not very clear.

Listing the current project's templates **first** and then the rest of the templates is likely a better solution, no?
