### ISSUE TITLE
Pushing Image Fails

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin#3841]
I get the following error while trying to build with the sample application-template-stibuild.json

"dockerutil.go:50] push for image 172.30.75.223:5000/test/origin-ruby-sample failed, will retry in 10s ...
F0722 17:05:56.719020       1 builder.go:70] Build error: Failed to push image: API error (500):  v1 ping attempt failed with error: Get http://172.30.75.223:5000/v1/_ping: read tcp 172.30.75.223:5000: connection reset by peer"

My private registry gives me this information when I run ./oc describe service docker-registry:

Name:			docker-registry
Labels:			docker-registry=default
Selector:		docker-registry=default
Type:			ClusterIP
IP:			172.30.168.237
Port:			<unnamed>	5000/TCP
Endpoints:		172.17.0.11:5000
Session Affinity:	None
No events.

Where is the ip address: 172.30.75.223:5000 coming from in the build logs when trying to push the image.  Shouldn't that address be 172.30.168.237:5000?

**Comment by deanpeterson** [comment]
I received this on the openshift users list from Andy Goldstein:

"I'm guessing you created the registry, deleted it at some point, and then recreated it. You need to restart the master if you do that (we're working on eliminating this issue, but it's going to take some time)."

Andy

I did create it.  Then I recreated it  because the registry seems to disappear occasionally.

**Comment by liggitt** [comment]
The registry service deletion/recreation is what changes the IP and requires the restart for the master to pick up. That should never be deleted apart from user action.

**Comment by deanpeterson** [comment]
I'm not sure what happens.  After some time, I will run ./oc describe service docker-registry and it will display nothing.  So I rerun ./oadm registry --create --credentials=openshift.local.config/master/openshift-registry.kubeconfig --config=openshift.local.config/master/admin.kubeconf deploymentconfigs/docker-registry services/docker-registry.

After I rerun that command ./oc describe service docker-registry again shows the running registry information.

**Comment by liggitt** [comment]
Are you switching projects? `oc describe` looks in the current namespace

**Comment by deanpeterson** [comment]
I did do that but it seems I made sure I was under the system:admin account outside of any project before I ran the command.  I am not entirely sure.  That may be the problem; I will keep track of that now.

**Comment by liggitt** [comment]
You are never "outside of any project". The registry has to be in the "default" project/namespace, so make sure you are checking/creating there

**Comment by deanpeterson** [comment]
Ok, thanks.  Yes, I just restarted my master (by hitting ctrl-c in the terminal running openshift) and restarted.  The same ip address is still there.  I must have created a registry in two places.  In the test project namespace and the default namespace.  The registry in the test project namespace must be interfering somehow.

**Comment by deanpeterson** [comment]
hmm, Before doing anything I checked to see that the registry was running.  It was.  I logged in as my test-admin user and created the project, then started the build to create the test application.  I received the same error about not being able to push to the registry.  I ran the command to describe the registry.  Nothing appeared.  I logged out and logged in as system:admin.  I ran the command to describe the registry.  Still nothing appeared.

**Comment by liggitt** [comment]
What does `oc describe service docker-registry -n default` show?

**Comment by ncdc** [comment]
Can you provide the following output?

oc get -n default se/docker-registry
oc get -n test is -o yaml

**Comment by deanpeterson** [comment]
./oc describe service docker-registry -n default does in fact show the ip address I am not communicating successfuly with during the build process:

Name:			docker-registry
Labels:			docker-registry=default
Selector:		docker-registry=default
Type:			ClusterIP
IP:			172.30.75.223
Port:			<unnamed>	5000/TCP
Endpoints:		172.17.0.1:5000
Session Affinity:	None
No events.


So if that registry is in fact running under the default namespace shouldn't I be able to push to it during the build process?

**Comment by deanpeterson** [comment]
./oc get -n default se/docker-registry:
"docker-registry   docker-registry=default   docker-registry=default   172.30.75.223   5000/TCP"

./oc get -n test is -o yaml:

apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: 2015-07-22T18:55:13Z
    labels:
      template: application-template-stibuild
    name: origin-ruby-sample
    namespace: test
    resourceVersion: "239356"
    selfLink: /osapi/v1beta3/namespaces/test/imagestreams/origin-ruby-sample
    uid: 2f2d0e59-30a3-11e5-bf60-0023ae6f50aa
  spec: {}
  status:
    dockerImageRepository: 172.30.75.223:5000/test/origin-ruby-sample
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2015-07-22T18:55:14Z
    creationTimestamp: 2015-07-22T18:55:13Z
    labels:
      template: application-template-stibuild
    name: ruby-20-centos7
    namespace: test
    resourceVersion: "239376"
    selfLink: /osapi/v1beta3/namespaces/test/imagestreams/ruby-20-centos7
    uid: 2f306a77-30a3-11e5-bf60-0023ae6f50aa
  spec:
    dockerImageRepository: openshift/ruby-20-centos7
  status:
    dockerImageRepository: openshift/ruby-20-centos7
    tags:
    - items:
      - created: 2015-07-22T18:55:14Z
        dockerImageReference: openshift/ruby-20-centos7:latest
        image: fe8b986eb820ba6e9792d7d7f21efe9acf268870967a89b3cdf0ad31063f0e8c
      tag: latest
kind: List
metadata: {}

**Comment by ncdc** [comment]
Now that you've restarted the master and the ImageStream has the correct IP for the registry, what error are you getting when you push? Can you paste the build log from a new/recent build?

**Comment by deanpeterson** [comment]
I0722 19:14:58.541700       1 sti.go:388] Installing activerecord (4.1.7) 
I0722 19:15:01.185959       1 sti.go:388] Installing mysql2 (0.3.16) 
I0722 19:15:01.787991       1 sti.go:388] Installing rack (1.5.2) 
I0722 19:15:01.954151       1 sti.go:388] Installing rack-protection (1.5.3) 
I0722 19:15:02.095065       1 sti.go:388] Installing tilt (1.4.1) 
I0722 19:15:02.410688       1 sti.go:388] Installing sinatra (1.4.5) 
I0722 19:15:02.583794       1 sti.go:388] Installing sinatra-activerecord (2.0.3) 
I0722 19:15:02.584173       1 sti.go:388] Using bundler (1.3.5) 
I0722 19:15:02.585144       1 sti.go:388] Your bundle is complete!
I0722 19:15:02.585182       1 sti.go:388] It was installed into ./bundle
I0722 19:15:02.616898       1 sti.go:388] ---> Cleaning up unused ruby gems
I0722 19:15:08.220627       1 sti.go:131] Using provided push secret for pushing 172.30.75.223:5000/test/origin-ruby-sample image
I0722 19:15:08.220657       1 sti.go:134] Pushing 172.30.75.223:5000/test/origin-ruby-sample image ...
E0722 19:15:32.270768       1 dockerutil.go:50] push for image 172.30.75.223:5000/test/origin-ruby-sample failed, will retry in 10s ...
E0722 19:16:06.320776       1 dockerutil.go:50] push for image 172.30.75.223:5000/test/origin-ruby-sample failed, will retry in 10s ...
F0722 19:16:41.442187       1 builder.go:70] Build error: Failed to push image: API error (500):  v1 ping attempt failed with error: Get http://172.30.75.223:5000/v1/_ping: read tcp 172.30.75.223:5000: connection reset by peer

**Comment by ncdc** [comment]
Ok, you're now running into what looks like a networking issue. How have you deployed OpenShift? All-in-one? Master + nodes? Master/node combo?

**Comment by deanpeterson** [comment]
I am running the binary all-in-one but I have also added another physical node.  ./oc get nodes returns this:
localhost.localdomain   kubernetes.io/hostname=localhost.localdomain   Ready
rhel.node.2             kubernetes.io/hostname=rhel.node.2             Ready

I added rhel.node.2 to the /etc/hosts file too.

**Comment by bparees** [comment]
@rajatchopra @ramr @pravisankar can one of you look at this from a networking perspective?

**Comment by deanpeterson** [comment]
I had originally created the registry with this command:

oadm registry --create --credentials=openshift.local.config/master/openshift-registry.kubeconfig --config=openshift.local.config/master/admin.kubeconfig
  deploymentconfigs/docker-registry
  services/docker-registry

I noticed I needed to run ./oc delete deploymentconfig docker-registry in order to start from scratch.

I did that.  I ran the test build from scratch again and received this:

I0722 20:16:14.253235       1 sti.go:388] Using bundler (1.3.5) 
I0722 20:16:14.254343       1 sti.go:388] Your bundle is complete!
I0722 20:16:14.254363       1 sti.go:388] It was installed into ./bundle
I0722 20:16:14.290876       1 sti.go:388] ---> Cleaning up unused ruby gems
I0722 20:16:19.534260       1 sti.go:131] Using provided push secret for pushing 172.30.13.89:5000/test/origin-ruby-sample image
I0722 20:16:19.534559       1 sti.go:134] Pushing 172.30.13.89:5000/test/origin-ruby-sample image ...
E0722 20:16:19.538499       1 dockerutil.go:50] push for image 172.30.13.89:5000/test/origin-ruby-sample failed, will retry in 10s ...
E0722 20:16:29.545582       1 dockerutil.go:50] push for image 172.30.13.89:5000/test/origin-ruby-sample failed, will retry in 10s ...
F0722 20:16:40.266792       1 builder.go:70] Build error: Failed to push image: API error (500):  v1 ping attempt failed with error: Get https://172.30.13.89:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 172.30.13.89:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/172.30.13.89:5000/ca.crt

In my application-template-stibuild.json, there is hard coded ca certificate information:

{
      "kind": "Route",
      "apiVersion": "v1",
      "metadata": {
        "name": "route-edge",
        "creationTimestamp": null
      },
      "spec": {
        "host": "www.example.com",
        "to": {
          "kind": "Service",
          "name": "frontend"
        },
        "tls": {
          "termination": "edge",
          "certificate": "-----BEGIN CERTIFICATE-----.............-----END CERTIFICATE-----",
          "key": "-----BEGIN PRIVATE KEY-----...........-----END PRIVATE KEY-----",
          "caCertificate": "-----BEGIN CERTIFICATE-----...............-----END CERTIFICATE-----"
        }
      },
      "status": {}
    },
    {
      "kind": "ImageStream",
      "apiVersion": "v1",
      "metadata": {
        "name": "origin-ruby-sample",
        "creationTimestamp": null
      },
      "spec": {},
      "status": {
        "dockerImageRepository": ""
      }
    },


I notice the hard coded certificate information in the application-template-stibuild.json taken from the sample-app repository does not match what is in my master folder.  Do I need to replace that information with the is in my master admin.crt, ca.crt and ca.key file?  

Or maybe I need to add the --insecure-registry option to the second node's /etc/sysconfig/docker file?

**Comment by deanpeterson** [comment]
This can be closed.  User error.  I had to add the --insecure-registry option to the second node's /etc/sysconfig/docker file.  I had only added it to the master's /etc/sysconfig/docker file.

**Comment by bparees** [comment]
thanks @deanpeterson

**Comment by aravindreddygit** [comment]
By looking into the latest issue its certificate issue. I have my private git hub registry and i have generated self signed cert "self.crt" on my registry server and added cert "self.crt" to my master and  node @ path:/etc/pki/ca-trust/source/anchors and ran "update-ca-trust extract" to fix this "connection reset by peer" issue.
