### ISSUE TITLE
reconcile-cluster-roles should have a "union-of" option for rolling upgrades

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3848]
#3810 introduced the ability to replace cluster roles that have been updated, but there are cases where the cluster admin wants to get a union of the old role and new role.  See https://github.com/openshift/origin/pull/3810#issuecomment-123438661.

@bparees can I get a P1, upcoming release?  This isn't stop-ship for now (we only have additive changes), but we'll probably want it for next time.

**Comment by deads2k** [comment]
@liggitt Can you assign to @kargakis?

**Comment by liggitt** [comment]
If we envision the union mode being a temporary step in an upgrade, to be followed shortly by a run that stomps/re-tightens to the default rules, we don't need to do a complicated "covers" evaluation... the simplest implementation could just add rules if they don't exist exactly already.
