### ISSUE TITLE
Support setting CA certificates for build git repos

### ISSUE THREAD

**Issue by cgwalters** [openshift/origin#3853]
I have an OpenShift instance that I want to point at internal `https://` with my employer's CA cert.

I filed https://github.com/openshift/openshift-docs/issues/791 which is more the system administrator side, but it'd be nice if I could specify the equivalent of git's `http.sslCert` or `http.sslCAInfo` configs in the `v1.GitBuildSource`.

**Comment by cgwalters** [comment]
This is related to https://github.com/openshift/origin/issues/1753

**Comment by bparees** [comment]
being worked this sprint:
https://trello.com/c/l8s6oYpy/658-8-self-signed-certificates-on-git-clone-https-by-using-installing-a-configurable-pem-file-build

**Comment by bparees** [comment]
@jhadvig @csrwng should be closable (as complete), right?  can you update this w/ a pointer to the docs about how to do this now?

**Comment by csrwng** [comment]
https://docs.openshift.org/latest/dev_guide/builds.html#using-private-repositories-for-builds

**Comment by bparees** [comment]
@cgwalters closing based on feature delivery and doc, please reopen if you still have concerns.
