### ISSUE TITLE
Labels should be more present in the UI

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3855]
In general, we hide labels a bit too much in the web console and cli.

* The overview should have a way to see what labels are grouping a block (subtly or not).  They should probably be clickable.
* The describer in the web UI should do something a bit nicer with labels
* If we group DC / SVC blocks by labels, we should probably show those labels (dotted line output)
* The oc status command should probably have the ability to show labels
* Our output commands on the cli should show labels consistently (if we aren't)

**Comment by smarterclayton** [comment]
@liggitt @spadgett @jwforres @fabianofranz

**Comment by fabianofranz** [comment]
Related to https://trello.com/c/plIuBSC1/506-increase-the-importance-value-of-labels-to-end-users

**Comment by jwforres** [comment]
I'm going to close the issue since we have a trello card dedicated to this
