### ISSUE TITLE
Be able to launch read only containers via Kube

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3860]
Need to figure out if we want this upstream.

**Comment by soltysh** [comment]
Can you share some more light on the actual use case for that?

**Comment by smarterclayton** [comment]
It prevents containers from using host resources not controlled by volumes,
gives an admin control of quota (0), and forces users to deal with
immutable containers.  Also catches bugs when you write outside volumes.

On Jul 23, 2015, at 9:41 AM, Maciej Szulik <notifications@github.com> wrote:

Can you share some more light on the actual use case for that?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3860#issuecomment-124104899>.

**Comment by ironcladlou** [comment]
Is this still a p2? The deployments label seems a little premature.

**Comment by smarterclayton** [comment]
It's not deployments, it should be runtime or something lower level.  Or
security.

On Tue, Aug 18, 2015 at 2:36 PM, Dan Mace <notifications@github.com> wrote:

> Is this still a p2? The deployments label seems a little premature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3860#issuecomment-132312183>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by pweil-** [comment]
Now supported with read only root file systems
