### ISSUE TITLE
Router should use negative rollout percentage, default rollout percentage should be 10%

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3861]
Router should be created with rolling update -10% update percentage.  We should default rollout percentage to 10%.

Any component which is node bound should have a negative percentage on rolling update.

We should change our examples to describe percentage negative as well as positive.

Do we have a fencepost test for a rolling update with 1 pod with a negative update percent?

@ironcladlou @ramr @pweil-

**Comment by ironcladlou** [comment]
The rolling updater tests exercise fencepost conditions for other quantities, but not 1 specifically. In my local branch I made some that exercise a quantity of 1 with various bounds-checking negative values (-100, -50, -1) and the scale increment is 1 (which is correct). Wouldn't hurt to add those into the next patch that touches the updater.

**Comment by smarterclayton** [comment]
K

On Jul 23, 2015, at 9:08 AM, Dan Mace <notifications@github.com> wrote:

The rolling updater tests exercise fencepost conditions for other
quantities, but not 1 specifically. In my local branch I made some that
exercise a quantity of 1 with various bounds-checking negative values
(-100, -50, -1) and the scale increment is 1 (which is correct). Wouldn't
hurt to add those into the next patch that touches the updater.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3861#issuecomment-124090719>.

**Comment by sdodson** [comment]
Is this the right strategy to suggest for folks upgrading to 1.0.4?

```
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      timeoutSeconds: 120
      updatePercent: -10
      updatePeriodSeconds: 1
    type: Rolling
```

**Comment by smarterclayton** [comment]
Yes

On Fri, Jul 24, 2015 at 5:11 PM, Scott Dodson <notifications@github.com>
wrote:

> Is this the right strategy to suggest for folks upgrading to 1.0.4?
>
>   strategy:
>     resources: {}
>     rollingParams:
>       intervalSeconds: 1
>       timeoutSeconds: 120
>       updatePercent: -10
>       updatePeriodSeconds: 1
>     type: Rolling
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3861#issuecomment-124725768>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ramr** [comment]
This is fixed. Can someone please close this issue. Thanks.

**Comment by sdodson** [comment]
Agree, this can be closed. Upgrade docs instruct folks to update their existing deployments too.
