### ISSUE TITLE
Build hangs in New when BuildOutput is missing in 1.0.3

### ISSUE THREAD

**Issue by mmilata** [openshift/origin#3870]
This is pretty much clone of #3391 because I can still reproduce it in 1.0.3. Tagging @csrwng per his request.

### Steps to reproduce

Using openshift 1.0.3 built from source on RHEL 7.1.
```
$ cat build.json
{
    "kind": "Build",
    "apiVersion": "v1",
    "spec": {
        "source": {
            "git": {
                "ref": "master",
                "uri": "https://github.com/mmilata/docker-hello-world.git"
            },
            "type": "Git"
        },
        "strategy": {
            "customStrategy": {
                "exposeDockerSocket": true,
                "from": {
                    "kind": "DockerImage",
                    "name": "buildroot:latest"
                }
            },
            "type": "Custom"
        }
    },
    "metadata": {
        "name": "test-build-1"
    }
}

$ oc create -f build.json
builds/test-build-1

$ oc get builds
NAME                          TYPE      STATUS     POD
test-build-1                  Custom    New        test-build-1-build

$ oc get pods
NAME                                READY     REASON       RESTARTS   AGE

$ oc describe build test-build-1
Name:                   test-build-1
Created:                7 minutes ago
Labels:                 <none>
Status:                 New
Duration:               waiting for 7m3s
Build Pod:              test-build-1-build
Strategy:               Custom
Image Reference:        DockerImage buildroot:latest
Expose Docker Socket:   yes
Source Type:            Git
URL:                    https://github.com/mmilata/docker-hello-world.git
Ref:                    master
No events.

$ journalctl -b | grep test-build-1
Jul 23 10:33:19 rhel71.vagrant openshift-master[4783]: I0723 10:33:19.976368    4783 controller.go:47] Handling Build default/test-build-1
Jul 23 10:33:19 rhel71.vagrant openshift-master[4783]: I0723 10:33:19.976462    4783 custom.go:48] ExposeDockerSocket is enabled for test-build-1 build
Jul 23 10:33:19 rhel71.vagrant openshift-master[4783]: I0723 10:33:19.976486    4783 factory.go:37] Retrying Build default/test-build-1 with error: Build failed with error default/test-build-1: the strategy failed to create a build pod for Build default/test-build-1: the docker pull spec "" must be two or three segments separated by slashes
Jul 23 10:33:19 rhel71.vagrant openshift-master[4783]: I0723 10:33:19.976499    4783 controller.go:47] Handling Build default/test-build-1
```

No ImageStreams or other objects are defined. The custom image can be anything
(even non-existent), it is never started.

### Results

Build stays in New state forever, no pods are created.

### Expected results

Build is started and the result is not pushed anywhere.
OR
API call returns an error.

Note: the build succeeds if the following is added to the spec of the provided json:
```
"output": {
  "to": {
    "kind": "DockerImage",
    "name": "result:latest"
  }
}
```

With the output defined, the *docker pull spec "" must be two or three segments separated by slashes* log message does not appear.

### Context

[OSBS](https://github.com/DBuildService/osbs) uses custom builds where the build image pushes the result into [pulp server](http://www.pulpproject.org/) and discards the built docker image. Currently we need to provide dummy docker repository for `BuildOutput` to work around this issue.

Please note that [API docs](http://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-buildspec) list the `BuildOutput` as optional.

**Comment by csrwng** [comment]
@bparees I can reproduce this in the latest code

**Comment by lynxnathan** [comment]
I'm getting a similar problem (build hanging on new) though in my case I originated the app from `oc new-app . --context-dir=9.4 --strategy=docker` where 9.4 is the directory containing the Dockerfile. Taking a look at journalctl I see a:
```No build pod found for build project/docker-postgresql-2, sending delete event for build pod```

Would this be related?

**Comment by bparees** [comment]
@lynxnathan No that is a different issue...  please open a new issue and provide the output of "oc get bc -o json" so we can see your buildconfig, and also "oc get builds -o json"

if you can point us to the remote repo you are building that would be great too.
