### ISSUE TITLE
oc create doesn't respect object api versions

### ISSUE THREAD

**Issue by bparees** [openshift/origin#3872]
oc create appears to create all objects against the api version of the wrapping list, not the individual object api versions.

@deads2k

**Comment by liggitt** [comment]
doesn't it convert the objects in the list to that version? is that a problem?

**Comment by bparees** [comment]
I can't remember why this was a problem...  i think it may have been hit because we had a bad conversion in place so this was a secondary problem to that issue.

given that, you might be right that we can just close this (though now that the api endpoints only support a single version it's going to be a problem again, right?)

@deads2k any thoughts?

**Comment by liggitt** [comment]
if the top level has apiVersion="v1", does that mean all the APIs we submit to (kube, openshift, subgroups in the future) need to have a "v1"? I could see that being a problem

**Comment by bparees** [comment]
are you arguing w/ yourself now?

**Comment by liggitt** [comment]
No! Yes?

**Comment by deads2k** [comment]
With the introduction of API groups, you cannot assume that the top level "version" has a corresponding "version" for all contained objects.  In addition, we now have inconsistencies between levels of our API (rolebinding.subject and deploymentconfig.updatepercent come to mind), so I think its more proper to try to submit using the version specified in the API object itself.

Unfortunately, that intersects with version negotiation (does the server even have that level) and whether the API object version is authoritative (I *must* have) or preferential (I *want* to have).

I think I have now successfully argued for both.  :)  I suspect that upstream will resolve this one way or the other for API groups.

**Comment by liggitt** [comment]
Upstream is doing away with the monolithic API version negotiation and is working on API discovery as part of API groups

**Comment by bparees** [comment]
pretty sure this is either not broken or now broken in a completely new way, so closing.
