### ISSUE TITLE
Labels extend beyond modal at mobile resolutions

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#3874]
![screen shot 2015-07-23 at 11 44 30 am](https://cloud.githubusercontent.com/assets/1874151/8854922/6f882478-3130-11e5-8264-935a47ed8684.png)

**Comment by liggitt** [comment]
@spadgett can we just remove the modal now?

**Comment by spadgett** [comment]
It's already gone. @sg00dwin Rebase? Clear cache?

**Comment by sg00dwin** [comment]
yep, rebased and it's gone
