### ISSUE TITLE
broken link in doc 

### ISSUE THREAD

**Issue by jmccormick2001** [openshift/origin#3878]
if you go to this page

https://docs.openshift.org/latest/dev_guide/persistent_volumes.html

and click on the kube link at the bottom of the page, it appears to be broken today July 23

the  broken link is

https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/persistent-volumes

**Comment by bparees** [comment]
@markturansky can you clean this up?

**Comment by markturansky** [comment]
@bparees on it.

**Comment by markturansky** [comment]
see https://github.com/openshift/openshift-docs/pull/798

**Comment by bparees** [comment]
fixed.
