### ISSUE TITLE
Prune unit tests each take ~3s

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3887]
Should probably not.

**Comment by ncdc** [comment]
Which prune?

**Comment by smarterclayton** [comment]
I don't remember but I thought all of them.

On Aug 11, 2015, at 8:56 AM, Andy Goldstein <notifications@github.com>
wrote:

Which prune?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3887#issuecomment-129861691>.

**Comment by miminar** [comment]
Blocked on #3333.
