### ISSUE TITLE
[Persistent Volume] Wrong accessModes

### ISSUE THREAD

**Issue by talset** [openshift/origin#3891]
I have been trying to use persistent volume with NFS share [1] but i have stumbled on 2 issues with "accessModes".
According to the documentation [2] we have 3 allowed values (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)

- First issue : Persistent volume with multi accessModes

When you create a PV with 3 accessModes available
```json
cat persistent-volume1.json 
{
  "apiVersion": "v1",
  "kind": "PersistentVolume",
  "metadata": {
    "name": "pvrecycle0001"
  },
  "spec": {
    "capacity": {
        "storage": "5Gi"
    },
    "accessModes": [ "ReadWriteMany","ReadWriteOnce","ReadOnlyMany" ],
    "nfs": {
        "path": "/var/export/vol1",
        "server": "master.axadev.enoshift.com"
    },
    "persistentVolumeReclaimPolicy": "Recycle"
  }
}
```

and I verify the ACCESSMODES 
```json
oc get pv
NAME            LABELS    CAPACITY     ACCESSMODES   STATUS      CLAIM                    REASON
pvrecycle0001   <none>    5368709120   RWO,ROX,RWX   Available
```

then I am trying to create a pvc

```json
cat persistent-volume-claim.json
{
  "apiVersion": "v1",
  "kind": "PersistentVolumeClaim",
  "metadata": {
    "name": "phpclaim"
  },
  "spec": {
    "accessModes": [ "ReadWriteMany" ],
    "resources": {
      "requests": {
        "storage": "2Gi"
      }
    }
  }
}
```

Verify STATUS

```json
oc get pvc
NAME       LABELS    STATUS    VOLUME
phpclaim   map[]     Pending
```

It will get stuck  in pending. I assume this would work when claiming the pv with only ReadWriteMany mode ? Currently the only way it's working is  to create a pvc with "ReadWriteMany","ReadWriteOnce","ReadOnlyMany" together to get a bounced status.

- Second issue : Random value in accessModes

We can create a PV with random values in accessModes
```json
cat pvtest.json 
{
  "apiVersion": "v1",
  "kind": "PersistentVolume",
  "metadata": {
    "name": "pvrecycle0001"
  },
  "spec": {
    "capacity": {
        "storage": "20Gi"
    },
    "accessModes": [ "ReadTest"],
    "nfs": {
        "path": "/var/export/vol1",
        "server": "master.axadev.enoshift.com"
    },
    "persistentVolumeReclaimPolicy": "Recycle"
  }
}
```

then I verify that the ACCESSMODES are empty
```json
oc get pv
NAME            LABELS    CAPACITY      ACCESSMODES   STATUS      CLAIM     REASON
pvrecycle0001   <none>    21474836480                 Available 
```

And then create a PVcllaime with the "ReadTest" mode.
```json
cat pvc.json 
{
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "metadata": {
        "name": "sonatype-work"
    },
    "spec": {
        "accessModes": [ "ReadTest" ],
        "resources": {
            "requests": {
                "storage": "2Gi"
            }
        }
    }
}
```

Verify STATUS Bound
```bash
oc get pvc
NAME            LABELS    STATUS    VOLUME
sonatype-work   map[]     Bound     pvrecycle0001
```

Since it was empty at first, it should not be working, right?

[1] https://github.com/openshift/training/blob/master/beta-4-setup.md#create-a-persistentvolume
[2] https://docs.openshift.org/latest/architecture/additional_concepts/storage.html#pv-access-modes

**Comment by markturansky** [comment]
This will be fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/10833

**Comment by markturansky** [comment]
Will file an upstream bug issue for the 2nd point (allowing fake access modes matches the same fake access mode).

**Comment by markturansky** [comment]
Upstream fix for 2nd issue:  https://github.com/GoogleCloudPlatform/kubernetes/pull/11829

**Comment by markturansky** [comment]
Closing this issue.  Both upstream PR fixes have been merged into Origin.

**Comment by markturansky** [comment]
Sorry, can't close.  Someone can close it :)  I verified this code is in Godeps.
