### ISSUE TITLE
Instant Apps don't appear in the UI until refresh

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3893]
To reproduce:

1. Open a project in the Web Console before loading any templates
1. Click Add to Project
1. On the command line, load the ruby hello world sample

The UI does not show ruby hello world until after you refresh. It should update right away.

**Comment by liggitt** [comment]
Is this worth watching templates for?

**Comment by spadgett** [comment]
Is it a concern about performance or do templates just not change often?

Going to this page, not seeing your template, and loading it with `oc` might be common enough. Particularly now that we show the command at the bottom of the page.

**Comment by liggitt** [comment]
Templates just don't change much. I'd almost rather work on letting you create a template from that page.

**Comment by smarterclayton** [comment]
Templates will probably change every few years :)

**Comment by spadgett** [comment]
Looks like you can't watch templates in the `openshift` namespace anyway (403 forbidden).
