### ISSUE TITLE
Errors running with Vagrant instructions

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3894]
I see the following errors creating the ruby hello world sample following the instructions for Vagrant.

https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-on-virtual-machine-using-vagrant

```
E0724 12:46:16.508713   16562 empty_dir.go:320] Expected directory "/data/src/github.com/openshift/origin/_output/local/go/bin/openshift.local.volumes/pods/cf150403-3201-11e5-be57-080027c5bfa9/volumes/kubernetes.io~secret/builder-dockercfg-8brbq-push" permissions to be: -rwxrwxrwx; got: -rwxr-xr-x
E0724 12:46:16.512693   16562 pod_workers.go:111] Error syncing pod bea79196-3200-11e5-be57-080027c5bfa9, skipping: operation not supported
E0724 12:46:16.515250   16562 kubelet.go:1190] Unable to mount volumes for pod "ruby-sample-build-1-build_project1": operation not supported; skipping pod
E0724 12:46:16.515572   16562 kubelet.go:1190] Unable to mount volumes for pod "database-1-deploy_project1": operation not supported; skipping pod
E0724 12:46:16.518119   16562 pod_workers.go:111] Error syncing pod cf150403-3201-11e5-be57-080027c5bfa9, skipping: operation not supported
E0724 12:46:16.518681   16562 pod_workers.go:111] Error syncing pod ceb28822-3201-11e5-be57-080027c5bfa9, skipping: operation not supported
```

It runs OK when I use `sudo systemctl start openshift` as documented before.

Other issues I've noticed:

There's no logs directory under `bin`, so the start command fails:

```
$ cd _output/local/go/bin
$ sudo ./openshift start --public-master=localhost &> logs/openshift.log &
```

There's no `killall` command, so this command under cleanup fails:

```
$ sudo killall openshift
```

`pkill` is there, however.

**Comment by spadgett** [comment]
> To ensure you get the latest image. First run vagrant box remove fedora_inst and vagrant box remove fedora_deps.

```
➜  origin git:(pod-template-updates) vagrant box remove fedora_inst
Removing box 'fedora_inst' (v0) with provider 'virtualbox'...
➜  origin git:(pod-template-updates) vagrant box remove fedora_deps
The box you requested to be removed could not be found. No
boxes named 'fedora_deps' could be found.
```

**Comment by spadgett** [comment]
I assume I needed to do this:

> when using vagrant synced folder (by default your origin directory is mounted using synced folder into /data/src/github.com/openshift/origin) it is advised to use a different directory for volume storage than the one in the synced folder. This can be achieved by passing --volume-dir=/absolute/path to openshift start command.

I suggest we make this part of the previous start command with a working volume dir for Vagrant.

**Comment by gabemontero** [comment]
Ok ... I'll try first without updating any images in case it is an image difference cause for the issue (I did not catch on the call if that comparison had already been done).

**Comment by gabemontero** [comment]
Hmm ... after  syncing from upstream, and running only hack/build-relase.sh, I did not even get as far as Sam did.  My make clean build failed.

I get a cannot allocate memory error from gcc:

[vagrant@openshiftdev origin]$ make clean  build
rm -rf _output Godeps/_workspace/pkg
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
# github.com/openshift/origin/cmd/openshift
/usr/lib/golang/pkg/tool/linux_amd64/6l: running gcc failed: Cannot allocate memory
Makefile:31: recipe for target 'build' failed
make: *** [build] Error 1

Googling on that get some Go / Kubernetes github hits, but I'm not getting any insight from them.

I'll try a full build-releases.sh / build-images.sh cycle and see if it make any difference.

**Comment by gabemontero** [comment]
That didn't help either.  I'll spend some time reading the go/kube github github search hits on the out of memory errors I'm seeing, but in the interim, someone else might want to try these instructions and see what they get.

**Comment by smarterclayton** [comment]
You need ~4GB memory to compile openshift.  Also... why is it calling gcc?

**Comment by gabemontero** [comment]
That information certainly helps.  Has it always been that way, I was there a recent uptick (as I did not hit this mem constraint in early June when I first came on board and tried out the steps outlined in origin/CONTRIBUTING.adoc) ?

When I run top after doing the `vagrant up`, I see the VM only having 1 GB of memory allocated.  That seems to also correspond to this stanza I found in the Vagrantfile off of the origin repo root dir:

  vagrant_openshift_config = {
    "instance_name"     => "origin-dev",
    "os"                => "fedora",
    "dev_cluster"       => false,
    "insert_key"        => true,
    "num_minions"       => ENV['OPENSHIFT_NUM_MINIONS'] || 2,
    "rebuild_yum_cache" => false,
    "cpus"              => ENV['OPENSHIFT_NUM_CPUS'] || 2,
    "memory"            => ENV['OPENSHIFT_MEMORY'] || 1024,
    "sync_folders_type" => nil,
    "virtualbox"        => {
      "box_name" => "fedora_inst",
      "box_url" => "https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_virtualbox_inst.box"
    },

I'll start some experiments with setting OPENSHIFT_MEMORY and see if I can get the compile to go.

As to gcc, I can only venture that in producing the linux_amd64 binaries, it uses gcc under the covers.  I certainly did not modify anything in origin after the sync with upstream before running the make.

**Comment by gabemontero** [comment]
Yep - setting OPENSHIFT_MEMORY to 4096 did the trick.  We'll have to make a call whether the Vagrantfile should be updated, or if we update the CONTRIBUTING.adoc to cite the need to set OPENSHIFT_MEMORY if doing a `make clean build`

Moving on to see if I can repro.  thanks.

**Comment by gabemontero** [comment]
And yep, I'm seeing the same thing Sam was.  I can't speak to what precisely changed, but the need to specifying 4GB and the specific volume-dir were not required last time.  The log dir most likely was an oversight in the doc update last month ... not 100% sure if the presence of killall was another change, or and oversight from the doc update last time, but is easily corrected.  

Some of the  VAGRANT directives in the sample app readme also need adjustment.

Aside from getting confirmation from the team on whether to change Vagrantfile to specify 4GB or have users set OPENSHIFT_MEMORY, I'll get started on the doc changes now.

**Comment by gabemontero** [comment]
@soltysh Hey Maciej - if I'm using `git blame` correctly (today was my first foray with that command), it says you added the NOTE regarding vagrant synced folders.  A question has come up from @spadgett and my walk through the steps if that option should just be included in the supplied command line.  I suppose it comes down to where the 80/20 rule lands here.  Do agree that most folks out of the gate will be running with vagrant synced folders, and that the --volume-dirs option should just be supplied on the openshift start invocation, vs. the separate note?

**Comment by spadgett** [comment]
Won't the user will always be using a vagrant synced dir since they're running under `/data/src`? So we either add the arg or change the instructions to run `openshift start` from another location.

**Comment by gabemontero** [comment]
On Sam's experience with `vagrant box remove ... `, I was able to successfully run `vagrant box remove fedora_inst` repeatedly - we'd have to watch Sam reproduce it to see what differences are occurring in the steps we are taking.  For `vagrant box remove fedora_deps`, in looking at the Vagrantfile, that is only used if you are running a dev cluster.  Since the out of the box flow does not employ a dev cluster, that is why removal of fedora_deps failed for both Sam and I.  Unless I get direction stating otherwise, I'll at least clarify in the doc that removing fedora_deps applies when running dev clusters.
