### ISSUE TITLE
No way to see image streams in the openshift namespace in the UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3895]
We have Browse -> Image Streams to view image streams in a project, but there's no way to view image streams in the `openshift` namespace. I suggest showing `openshift` image streams in a separate grouping on the browse image streams page.

**Comment by liggitt** [comment]
I'm not sure we want to do that. image streams from other projects are only useful during a create flow. I don't want to show cross-namespace resources under Browse yet until we figure out what we want to do across projects in general.

**Comment by spadgett** [comment]
OK. Maybe it's better to show builder images first in the create flow in that case. Right now you have to enter your Git URL and click next to find out nothing is loaded.

**Comment by liggitt** [comment]
maybe so... that would let us do things like tailor the example source URL to the builder tags (show a node example for nodejs, rails for rails, etc)

**Comment by spadgett** [comment]
There's a Trello card for showing the builder images first. I'm going to close this issue since it's slightly different in favor of the card.

https://trello.com/c/TQr92yy9/459-create-from-source-should-present-builder-images-first-uicomp-future
