### ISSUE TITLE
Visually distinguish templates by namespace in the UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3901]
Show templates in the project namespace first, then shared templates in the `openshift` namespace.

See https://github.com/openshift/origin/issues/3833#issuecomment-124121272

**Comment by smarterclayton** [comment]
We should probably give shared templates an visual label like "shared" to further indicate they are not in your current namespace.

**Comment by jwforres** [comment]
@spadgett is this still relevant after your changes to the create page

**Comment by spadgett** [comment]
@jwforres Probably not as written. I don't think we should have groups within groups. We could do a better job of visually distinguishing the two, though, and possibly add a filter.

**Comment by spadgett** [comment]
We have a general card for improving the usability of the catalog. I'll link back to this issue.

https://trello.com/c/xlQaSaxT

**Comment by ajacobs21e** [comment]
I included a few ideas for handling this in wireframes posted to that trello card
