### ISSUE TITLE
build-chain should handle cyclic dependencies

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#3902]
Use what we already use in `oc status` plus fix the DFS traversal used in `humanReadableOutput`.

**Comment by kargakis** [comment]
Moving to @bparees for assigning to somebody else

**Comment by bparees** [comment]
@gabemontero is most familiar w/the graph library at this point, giving to him (low priority).

**Comment by gabemontero** [comment]
There are definitely some blanks I would need to get filled here before doing anything with this, but here is the initial connecting of dots I've managed so far:

1) the circular dependency check from `oc status` is [here](https://github.com/openshift/origin/blob/master/pkg/build/graph/analysis/bc.go#L133-L163)
2) ... would any of the other checks in this file make sense long term ??
3) The analogous `Describe` call for `oc status` that sucks in the marker from 1) and a bunch of others is [here](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/describe/projectstatus.go#L238-L240)
4) In theory, the `build-chain` `Describe` call located [here](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/describe/chaindescriber.go#L82-L119) would process the markers in a similar fashion as 3)

I was unable to infer the fix needed for the DFS traversal in `humanReadableOutput`, assuming it is still needed (there were changes made to that method back in April of this year ... perhaps the fix has occurred).

Thoughts @kargakis 

@bparees - this issue *could* be card worthy, especially for one of our new hires.

**Comment by kargakis** [comment]
@gabemontero since `build-chain` has moved to use the graph library, it could definitely benefit from the marking process we run for `status`.

**Comment by gabemontero** [comment]
After revisiting this, my interpretation was that the circular build check was the only one that really applied here; pending receiving some enlightenment during review, I followed the KISS principle for this one.  We also have the recently commissioned https://trello.com/c/hHx4HrCG/966-integrate-pipeline-stages-into-oc-status potentially having some bearing on `oadm build-chain`.

Will submit PR momentarily.
