### ISSUE TITLE
Separate between user and admin in the cli

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#3903]
Some commands may have different behavior depending on who is using them (user or admin) eg. `build-chain` given the `--all` flag will search all namespaces but "all namespaces" has different meaning between a user and an admin.

cc: @deads2k

**Comment by smarterclayton** [comment]
Why does all have different behavior between a user and an admin?

**Comment by kargakis** [comment]
> Why does all have different behavior between a user and an admin?

I am not talking about the alias but the `--all` flag of build-chain. `build-chain nodejs --all` will fetch the dependencies of `nodejs` from all namespaces but "all namespaces" can be either "all namespaces we can see" (user case) or "literately all namespaces" (admin case).

**Comment by smarterclayton** [comment]
Are you making two distinct calls there?

On Mon, Jul 27, 2015 at 4:43 AM, Michail Kargakis <notifications@github.com>
wrote:

> Why does all have different behavior between a user and an admin?
>
> I am not talking about the alias but the --all flag of build-chain. build-chain
> nodejs --all will fetch the dependencies of nodejs from all namespaces
> but "all namespaces" can be either "all namespaces we can see" (user case)
> or "literately all namespaces" (admin case).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3903#issuecomment-125128750>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by kargakis** [comment]
> Are you making two distinct calls there?

Not currently. That's why the issue:) I guess there are other commands that fall into this too

**Comment by smarterclayton** [comment]
Right now I don't worry too much about this :)  Elsewhere --all-namespaces
means "you have to be a cluster-admin", so I think --all meaning "all
projects I have access to" here is fine.

On Mon, Jul 27, 2015 at 3:43 PM, Michail Kargakis <notifications@github.com>
wrote:

> Are you making two distinct calls there?
>
> Not currently. That's why the issue:) I guess there are other commands
> that fall into this too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3903#issuecomment-125322866>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Is this actionable?  May want o close otherwise

**Comment by deads2k** [comment]
> Is this actionable? May want o close otherwise

This is essentially the same problem as `oc status` across multiple namespaces that we rediscovered recently and very similar to requests we've gotten for "all of X that I can see".  

I'd like to see progress on this by having a way to specify more than on target namespace on the cli.

**Comment by smarterclayton** [comment]
There are already issues to cover that upstream.

**Comment by kargakis** [comment]
Link those here and we can close this.
