### ISSUE TITLE
Is oc get roles should come back with something

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#3911]
I would expect with the list of roles available on the cluster (at least when I am logged as `system:admin`) but it doesn't seem to do much : 

<img width="783" alt="2015-07-24__23-46-54-4002" src="https://cloud.githubusercontent.com/assets/98980/8885260/4c70673c-325e-11e5-90d6-1e3163c932ed.png">

**Comment by liggitt** [comment]
Those are the roles defined in your current project (you don't have any locally defined roles). Try `oc get clusterroles`

**Comment by chmouel** [comment]
ah thanks that make sense, sorry for the noise :)
