### ISSUE TITLE
Container service environment variable

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#3914]
Hi All, 
         I would like to understand why my tomcat container can see all the defined services that are in my OSE cluster, from my point of view my container should only view the services's env. variable that is link to, there are two concerns:

1- Security: Why my container can view all services, OSE is multinant, right?
2- SysAdmin point of view, if at the end of this year I define 1000 services, my container will have more than 8000 env. variables, hard to manage ... 

[root@ose1 ~]# oc get svc
NAME                       LABELS                                               SELECTOR                   IP(S)            PORT(S)
mongodb                    template=mongodb-persistent-template                 name=mongodb               172.30.185.16    27017/TCP
test1                      template=springboot-template                         name=test1                 172.30.152.182   8080/TCP
test10                     name=test10                                          deploymentconfig=test10    172.30.51.199    tomcat-openshift-service   <none>                                               name=tomcat-openshift      172.30.125.64    8080/TCP
tomcat8                    <none>                                               deploymentconfig=tomcat8   172.30.198.109   8080/TCP

[root@ose1 ~]# oc exec -p tomcat-openshift -c tomcat-openshift -i -t -- bash -il

root@tomcat-openshift:/usr/local/tomcat# env | grep -i mongodb
MONGODB_PORT_27017_TCP=tcp://172.30.185.16:27017
MONGODB_PORT=tcp://172.30.185.16:27017
MONGODB_PORT_27017_TCP_PORT=27017
MONGODB_SERVICE_HOST=172.30.185.16
MONGODB_PORT_27017_TCP_PROTO=tcp
MONGODB_PORT_27017_TCP_ADDR=172.30.185.16
MONGODB_SERVICE_PORT=27017
MONGODB_SERVICE_PORT_MONGO=27017

root@tomcat-openshift:/usr/local/tomcat# env | grep -i test1  
TEST10_SERVICE_HOST=172.30.51.199
TEST10_PORT_8080_TCP_PROTO=tcp
TEST1_SERVICE_HOST=172.30.152.182
TEST1_PORT=tcp://172.30.152.182:8080
TEST1_PORT_8080_TCP_ADDR=172.30.152.182
TEST11_PORT_8080_TCP_PROTO=tcp
TEST10_SERVICE_PORT_TOMCAT_TCP_8080=8080
TEST10_PORT_8080_TCP_ADDR=172.30.51.199
TEST1_PORT_8080_TCP_PORT=8080
TEST11_PORT_8080_TCP=tcp://172.30.53.40:8080
TEST10_PORT=tcp://172.30.51.199:8080
TEST1_PORT_8080_TCP_PROTO=tcp
TEST11_SERVICE_PORT=8080
TEST11_PORT_8080_TCP_PORT=8080
TEST1_SERVICE_PORT=8080
TEST10_PORT_8080_TCP=tcp://172.30.51.199:8080
TEST11_SERVICE_HOST=172.30.53.40
TEST1_PORT_8080_TCP=tcp://172.30.152.182:8080
TEST11_PORT_8080_TCP_ADDR=172.30.53.40
TEST10_PORT_8080_TCP_PORT=8080
TEST11_PORT=tcp://172.30.53.40:8080
TEST11_SERVICE_PORT_TOMCAT_TCP_8080=8080
TEST10_SERVICE_PORT=8080
root@tomcat-openshift:/usr/local/tomcat# exit
logout

[root@ose1 ~]# oc export pod tomcat-openshift
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: restricted
  creationTimestamp: null
  labels:
    name: tomcat-openshift
  name: tomcat-openshift
spec:
  containers:
- image: docker.io/tomcat
  imagePullPolicy: IfNotPresent
  name: tomcat-openshift
  ports:
  - containerPort: 8080
    hostPort: 18080
    protocol: TCP
    resources:
    limits:
      cpu: 10m
      memory: 200M
    securityContext:
    capabilities: {}
    privileged: false
    terminationMessagePath: /dev/termination-log
    volumeMounts:
  - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    name: default-token-wln8q
    readOnly: true
    dnsPolicy: ClusterFirst
    host: ose3.novalocal
    imagePullSecrets:
- name: default-dockercfg-oowc9
  restartPolicy: Always
  serviceAccount: default
  volumes:
- name: default-token-wln8q
  secret:
    secretName: default-token-wln8q
  status:
  phase: Pending

**Comment by smarterclayton** [comment]
You should only be seeing environment variables from your current namespace, and the KUBERNETES service.  Anything else is a bug.

**Comment by liggitt** [comment]
@roldancer are you seeing envvars from services outside your namespace (other than the KUBERNETES service, which is special)?

**Comment by danmcp** [comment]
@roldancer Bump

**Comment by pweil-** [comment]
closing due to lack of response
