### ISSUE TITLE
Add command to unpack secrets to a directory

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3915]
`oc secrets extract ... <path>` or similar.

Used to actually, you know, use secrets.

**Comment by deads2k** [comment]
Things I want
 1. I'd like to be able to specify the `data` key as well.  Default to all, but allow me to specify.
 1. If we require a directory, add an `overwrite` flag to allow me to extract into a non-empty directory.  Do *not* enable this by default
 1. Allow me to output to stdout.  For single keys, no labelling.  For multiple keys, somehow distinguish output boundaries.

**Comment by smarterclayton** [comment]
Those all sound good to me.

On Mon, Jul 27, 2015 at 1:38 PM, David Eads <notifications@github.com>
wrote:

> Things I want
>
>    1. I'd like to be able to specify the data key as well. Default to
>    all, but allow me to specify.
>    2. If we require a directory, add an overwrite flag to allow me to
>    extract into a non-empty directory. Do *not* enable this by default
>    3. Allow me to output to stdout. For single keys, no labelling. For
>    multiple keys, somehow distinguish output boundaries.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3915#issuecomment-125282988>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by fabianofranz** [comment]
Trello story instead of GitHub issue?

**Comment by mfojtik** [comment]
@fabianofranz did a trello story for this was ever created? ;-)

**Comment by smarterclayton** [comment]
This is merged.  "oc extract"

**Comment by fabianofranz** [comment]
> did a trello story for this was ever created? ;-)

Yes, *and* already implemented in `oc extract`.  :)

I'll close this, feel free to reopen if there's anything missing in `oc extract` to consider this done.
