### ISSUE TITLE
ZooKeeper example fails

### ISSUE THREAD

**Issue by craigmunro** [openshift/origin#3920]
The current ZooKeeper example doesn't have sufficient privileges to run correctly.  

The following is in the logs:

```/opt/zookeeper/bin/config-and-run.sh: line 4: /opt/zookeeper/data/myid: Permission denied
/opt/zookeeper/bin/config-and-run.sh: line 7: /opt/zookeeper/conf/zoo.cfg: Permission denied```

It's not immediately obvious though as ZooKeeper still runs using the existing zoo.cfg but you then have three independent servers rather than a single cluster.

Worked around it by making them privileged for now.

**Comment by mfojtik** [comment]
the directories have to be world-writeable... fill fix this today

**Comment by craigmunro** [comment]
Don't changes to data within volumes have to be done before the volume is declared?  Putting the chmod before the volume fixes it for me.

**Comment by mfojtik** [comment]
@craigmunro fixed the dockerfile. thanks for pointing this out!  Can this issue be closed now?
