### ISSUE TITLE
frontend fe_no_sni in haproxy configuration should use mode http

### ISSUE THREAD

**Issue by nstrug** [openshift/origin#3926]
The frontend fe_no_sni, used for  terminating non-SNI connections does not work correctly for either reencrypting or edge terminating connections.

This is because it uses backends of the form:

use_backend be_edge_http_%[hdr(host), map......

These maps are unused, because hdr(host) is undefined.

This is easily fixed by adding 'mode http' to the frontend fe_no_sni definition.

NB - 'mode http' is already present in the frontend fe_sni used for SNI termination, so I presume it is just an oversight that it is missing in fe_no_sni.

**Comment by smarterclayton** [comment]
@pweil- @ramr

**Comment by ramr** [comment]
Fixed with https://github.com/openshift/origin/pull/3937

**Comment by ramr** [comment]
@danmcp @nstrug  - this has been fixed and @rajatchopra  and I can't seem to close out the issue. 
Can you please help close this. Thanks.
