### ISSUE TITLE
Build of image fails

### ISSUE THREAD

**Issue by david-strejc** [openshift/origin#3927]
I got one node / master setuped on one VM. I am still experiencing following:

I0728 12:11:48.665278       1 sti.go:269] Successfully built 172.30.160.216:5000/dst/cakephp-mysql-example:latest
I0728 12:11:49.028438       1 cleanup.go:23] Removing temporary directory /tmp/sti491122163
I0728 12:11:49.028479       1 fs.go:99] Removing directory '/tmp/sti491122163'
I0728 12:11:49.101727       1 cfg.go:46] PUSH_DOCKERCFG_PATH=/var/run/secrets/openshift.io/push/.dockercfg
I0728 12:11:49.102076       1 cfg.go:64] Using serviceaccount user for Docker authentication
I0728 12:11:49.102101       1 sti.go:146] Using provided push secret for pushing 172.30.160.216:5000/dst/cakephp-mysql-example:latest image
I0728 12:11:49.102111       1 sti.go:149] Pushing 172.30.160.216:5000/dst/cakephp-mysql-example:latest image ...
E0728 12:27:30.412386       1 dockerutil.go:50] push for image 172.30.160.216:5000/dst/cakephp-mysql-example:latest failed, will retry in 10s ...
E0728 12:43:17.573082       1 dockerutil.go:50] push for image 172.30.160.216:5000/dst/cakephp-mysql-example:latest failed, will retry in 10s ...

I don't know how to debug this problem. I can support you with logs from docker-registry, build-logs etc. but I need to find the way how to debug this issue.

Some advices?

**Comment by bparees** [comment]
@derekwaynecarr assigning to you since @ncdc is on pto.

@david-strejc logs from the docker registry would be a great start.

i'm also going to update the code in question to actually report the error it got when pushing.

**Comment by bparees** [comment]
https://github.com/openshift/origin/pull/4246

**Comment by smarterclayton** [comment]
Closing due to age.
