### ISSUE TITLE
openshift-node in a container breaks networking

### ISSUE THREAD

**Issue by rajatchopra** [openshift/origin#3940]
If openshift-node is run inside a container with openvswitch dependencies included, the multi-node SDN does not work. The reason is that SDN restarts docker daemon that ends up restarting the container itself.
Upon restart openshift-node figures that linux bridge is configured so it does not restart docker daemon again, but as part of skip setup the OVS rules do not get installed properly.

A fix is needed such that even if the setup is skipped upon restart the OVS rules should be examined and installed properly if found missing.

**Comment by rajatchopra** [comment]
cc @pravisankar

**Comment by marun** [comment]
Validation of this feature will require replicating the chain of events that was previously leading to multi-node communication not working.  On at least 2 nodes:

 - launch openshift
 - restart docker
 - restart openvswitch
 - restart openshift

Once the cluster is up, run the kube networking e2e tests to ensure that multi-node communication is achieved.

**Comment by marun** [comment]
@sdodson Can this issue be closed due to your work on containerization?

**Comment by sdodson** [comment]
@marun yes, I believe it can be.

**Comment by marun** [comment]
@eparis Please close.
