### ISSUE TITLE
Need to update Dockerhub readme for openshift/origin

### ISSUE THREAD

**Issue by mnagy** [openshift/origin#3942]
The readme at https://registry.hub.docker.com/u/openshift/origin/ is outdated. Namely, the docker instructions on how to run the image do not include mounting of host rootfs to `/rootfs` which results in pods failing to start because kubelet is not able to mount volumes. Other flags are missing as well.

Not sure who's responsible for the dockerhub readme, so filling an issue. Maybe we should update it automatically when pushing the new image?

**Comment by tnguyen-rh** [comment]
@mnagy The source is the top-level README.md.  I'll fix it.

**Comment by tnguyen-rh** [comment]
@mnagy I see the source is OK.  So really the question is: How is that page updated?  That is an administrative issue.  Hmmm...

**Comment by smarterclayton** [comment]
The page is not updated automatically.  I've updated it since.
