### ISSUE TITLE
Requesting a token returns a redirect containing the access token

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#3945]
I'm trying to request a token for API access using curl.  The auth succeeds, I can see the token returned embedded in the Location header, but (a) it's not easy to pick out, and (b) if I follow the Location Header, the next page is a 500.  Could that subsequent page instead nicely return me my token in JSON format or equivalent?

Caveat: I assume that what I'm trying to do is legitimate?

```
[demo@openshift ~]$ curl -L -D - -u username:password -H 'X-CSRF-Token: 1' 'https://openshift.example.com:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client'
HTTP/1.1 302 Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Location: https://openshift.example.com:8443/oauth/token/display#access_token=gO7z6AVvD67q4SGm-ZevazYPLvLCeZGIqNLGSP_ju_s&expires_in=86400&token_type=bearer
Pragma: no-cache
Set-Cookie: ssn=MTQzODE3ODAzNXxpcGZwZF90Y1BkNzhOOE5OZzFfRjdFcGV0WklSZi1xUFlhTzI0OUNESnRydHJianl5dzR4VmdVN0Jvckxjb2lrOExNSnRVMVV6WG00UnI2QmM5NGxoUkpwODdoSnI4OGc4WWpXZUpaTXZrT1NvWUxoZXNzem1MNGZwTDZGYzFWcG9RPT18Ffz2NhsJ9dOT-MUdW9md4n8NDYnmOGU3VJ3TNbjxiiI=; Path=/; Expires=Wed, 29 Jul 2015 14:53:55 UTC; Max-Age=3600; HttpOnly; Secure
Date: Wed, 29 Jul 2015 13:53:55 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

HTTP/1.1 500 Internal Server Error
Content-Type: text/html
Date: Wed, 29 Jul 2015 13:53:55 GMT
Content-Length: 386


<style>
	body    { font-family: sans-serif; font-size: 12pt; margin: 2em 5%; background-color: #F9F9F9; }
	pre     { padding-left: 1em; border-left: .25em solid #eee; }
	a       { color: #00f; text-decoration: none; }
	a:hover { text-decoration: underline; }
</style>


  Error handling auth request: Requested parameter not sent


<br><br>
<a href="request">Request another token</a>
[demo@openshift ~]$ 
```

**Comment by wjiangjay** [comment]
As far as I know, there are two ways to request a new token
1. 
   # openshift ex tokens request-token --v=6
   I0730 02:57:02.421371   24420 debugging.go:120] GET https://10.109.187.252:8443/oauth   /authorize?client_id=openshift-challenging-client&response_type=token 401 Unauthorized in 53 milliseconds
    Authentication required for https://10.109.187.252:8443 (openshift)
    Username: wjiang 
    Password: 
    I0730 02:57:06.601090   24420 debugging.go:120] GET https://10.109.187.252:8443/oauth/authorize?client_id=openshift-challenging-client&response_type=token 302 Found in 12 milliseconds
    -2E-uCnBPr5A9QxiAZoAqfbSTm7lukNza60hw5wernw

2. Access the page /oauth/token/request via browser, the api via browser is using 
oauth/authorize?client_id=openshift-browser-client&redirect_uri=https%3A%2F%2F10.109.187.252%3A8443%2Foauth%2Ftoken%2Fdisplay&response_type=code

# curl -k -L -D - -u username:password  'https://127.0.0.1:8443/oauth/authorize?response_type=code&client_id=openshift-browser-client' 
HTTP/1.1 302 Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Expires: Fri, 01 Jan 1990 00:00:00 GMT                                                                                                                           [0/522]
Location: https://10.109.187.252:8443/oauth/token/display?code=StMMyH76XZmCDVjXorE8HE0LzzWw-rG5pYPrPgDgMFM&state=
Pragma: no-cache
Set-Cookie: ssn=MTQzODIyNTk4NXwtU1dDUmM4VlJ2UG1WalhKNUhJbVVJX19iUko4eV96SExFRlJBci01NE1RVEE0Z2p6M2tmbFFZTXVjWVRIQUxKZXZqS282V3FGZTNzeGNRaUx0YVJSc2MyMjR3OXhra3B5T0d5Z0Zz
Z3pmZjNwV2VGZC1Qd0hTX0c3TjNNMVdBR0RRPT18hbIZN9DbO11mznNDTHGu0ITHLbQCZ2W2VQ0Q3H7soco=; Path=/; Expires=Thu, 30 Jul 2015 03:18:05 UTC; Max-Age=300; HttpOnly; Secure
Date: Thu, 30 Jul 2015 03:13:05 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

HTTP/1.1 200 OK
Content-Type: text/html
Date: Thu, 30 Jul 2015 03:13:05 GMT
Content-Length: 1071


<style>
        body    { font-family: sans-serif; font-size: 12pt; margin: 2em 5%; background-color: #F9F9F9; }
        pre     { padding-left: 1em; border-left: .25em solid #eee; }
        a       { color: #00f; text-decoration: none; }
        a:hover { text-decoration: underline; }
</style>


  <h3>Here is your brand new OAuth access token:</h3>
  <pre>{
   &#34;access_token&#34;: &#34;fIof3McZ5DVt1Uy6atsnUhis-y43dMctA5irrxH8ixk&#34;,
   &#34;expires_in&#34;: 86400,
   &#34;token_type&#34;: &#34;bearer&#34;
}</pre>

  <h3>How do I use this token?</h3>
  <pre>oc login --token=fIof3McZ5DVt1Uy6atsnUhis-y43dMctA5irrxH8ixk --server=https://10.109.187.252:8443</pre>
  <pre>curl -H "Authorization: Bearer fIof3McZ5DVt1Uy6atsnUhis-y43dMctA5irrxH8ixk" &hellip;</pre>

  <h3>How do I delete this token when I'm done?</h3>
  <pre>oc delete oauthaccesstoken fIof3McZ5DVt1Uy6atsnUhis-y43dMctA5irrxH8ixk</pre>
  <pre>curl -X DELETE &hellip;/oapi/v1/oauthaccesstokens/fIof3McZ5DVt1Uy6atsnUhis-y43dMctA5irrxH8ixk</pre>


<br><br>
<a href="request">Request another token</a>

And the render part actually check if the response url have a Param named "code", so when your request will not return with code, so got the error.

**Comment by liggitt** [comment]
By passing the `response_type=token` parameter, you are requesting an "Implicit Grant" OAuth flow (https://tools.ietf.org/html/rfc6749#section-4.2). This dictates that the access token be returned in the fragment portion of a redirect header.

If you request a token this way, you are expected to extract the token from the redirect header fragment yourself. If you follow the redirect, the access token in the fragment is not sent to the server, so it has no way to echo it back to you.

This will extract the token for you from the response header:
```
curl -L -D - -u username:password -H 'X-CSRF-Token: 1' 'https://openshift.example.com:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client' 2>&1 | grep -oP "access_token=\K[^&]*"
```

**Comment by jim-minter** [comment]
OK, so the use case here is wanting a straightforward way to get a token for 3rd party REST API access, but not wanting to rely on using the oc tool - so 'openshift ex tokens request-token' is out.

I'm aware that the token can be grepped as @liggitt mentioned, but it seems pretty non-standards compliant to return a token in a Location header whose end destination is broken.

Surely following the Location *would* send the token to the server, because it's in the querystring of the Location redirect itself.  Could the server not echo this back as a courtesy as a json document, just like you get a friendly HTML document if you go to /oauth/authorize?client_id=openshift-browser-client&response_type=code ?

**Comment by liggitt** [comment]
The token is in the fragment of the location header, not the query. Fragments are not sent to the server.

**Comment by jim-minter** [comment]
I see - I admit I don't quite understand the intricacies of this :/

I see that ```curl -L -u username:password 'https://openshift.example.com:8443/oauth/authorize?response_type=code&client_id=openshift-browser-client'``` returns an HTML page containing an access token.

My question is: does there exist/can we have an equivalent which as easily returns an access token without having to pick the token out of HTTP headers or HTML?  E.g. just returning the json which the HTML wraps, but as plain json?

**Comment by liggitt** [comment]
The contents of that page are not intended to be an API. There is already an API for obtaining an access token, which is the OAuth spec, supported by the /authorize and /token endpoints. I'm hesitant to introduce another API to provide the same thing.

**Comment by jim-minter** [comment]
So, https://tools.ietf.org/html/rfc6749#section-5 specifically covers the server returning access tokens in JSON format back to the client in a standard way.  I'd argue that our existing implementation with openshift-browser-client where we HTMLize the JSON response is the unusual piece.

It looks like both https://tools.ietf.org/html/rfc6749#section-4.3 and https://tools.ietf.org/html/rfc6749#section-4.4 define standard OAuth mechanisms which straightforwardly convert a username/password to an access token, returned to the client in JSON format.  I'm not quite clear which of them is more appropriate in the OSE case, but I don't see how there isn't a need here that we should be satisfying.

Can we have a straightforward mechanism which allows an API user with a username and password to get an access token?

**Comment by liggitt** [comment]
You are confusing the token/display endpoint for an API. That page exists simply to display an access token to a user. It makes a server side call to /token and exchanges an authorization code for an access token in JSON format. You are free to do the same thing, but you need a client is and secret to do so. 

Section 5 only applies to access tokens returned from the /token endpoint as part of an access token request, not from the /authorize endpoint in response to an authorization request. 

Section 4.3 is the only way in the OAuth spec to exchange a username and password for an access token directly. We can add a user story for implementing it, but I wouldn't recommend relying on that mechanism, because it presumes the authentication mechanism is username/password-based. 

When we add support for Kerberos or other negotiate auth mechanisms, clients that are limited to using the resource owner password method of obtaining an access token would be out of luck.

**Comment by liggitt** [comment]
Actually, the resource owner password method still requires a client_id and client_secret to be specified, which your client won't have unless you have your own OAuth client registered with the server.

**Comment by liggitt** [comment]
Updated description since 500 has been fixed

**Comment by liggitt** [comment]
Closing, working as designed (and per OAuth spec)

**Comment by sheikirfanbasha** [comment]
@liggitt 
Hi Jordan,

I am actually trying to make use of "/token" end point to receive the access token.

The payload with which I am making a POST request is:
{
grant_type: authorization_code
client_id: client-id
redirect_uri: http://localhost:9000
code: xgi1tfc1CiN8KdWfNiXOpoOQfWAMk7mOm2w0nRNK6VY
client_secret: secret
}

The response I am getting is:
{
  "error": "unauthorized_client",
  "error_description": "The client is not authorized to request a token using this method."
}

It would be very helpful if you can point me where and how i can do the configuration setup to make the client authorized.

**Comment by liggitt** [comment]
a couple things I couldn't tell from your example:

1. The body of the POST has to be form encoded, not JSON (e.g. "grant_type=authorization_code&code=...&…")
2. The client id should correspond to the name of an OAuthClient API object, and the client secret value should match that OAuthClient's secret field

**Comment by sheikirfanbasha** [comment]
@liggitt 
Thanks for the quick response. I am actually using "x-www-form-urlencoded" option in Postman(Chrome extension). So, encoding part is taken care. I actually wanted to know where exactly in the "master-config.yaml" we need to do the configuration to specify the client_id and client_secret and use those values when making a request through "/token" POST Request.

**Comment by liggitt** [comment]
It's not in the master config. Multiple OAuthClient objects are supported and are created as API objects. See https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#oauth

**Comment by sheikirfanbasha** [comment]
@liggitt 
Thanks a lot for pointing me to the right docs. Will use the API to create one.

**Comment by sheikirfanbasha** [comment]
@liggitt 
That helped Jordan. Thanks a lot :)

**Comment by daald** [comment]
I implemented what's written above in a little shell script:
```
generateToken() {
  tmpfile="$(tempfile)"
  curl -s \
    -D "$tmpfile" \
    --insecure \
    -u "$OC_USER:$OC_PASSWORD" \
    "${OC_BASEURL}oauth/authorize?response_type=token&client_id=openshift-browser-client" || return $?
  token="$(grep '^location' "$tmpfile")"
  rm -f "$tmpfile"
  token="${token#*access_token=}"
  token="${token%%&*}"
  echo "$token"
}

token=$(generateToken)
oc login --token=$token
```
