### ISSUE TITLE
Newapp: Will not create an image stream for an app if the name exists in openshift namespace

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#3947]
Using a source repository with the same name as an image stream that exists in openshift ('php', 'ruby', etc) results in no output image stream getting created.

**Comment by csrwng** [comment]
@bparees can you please assign to me?

**Comment by smarterclayton** [comment]
That is intentional?

**Comment by smarterclayton** [comment]
Ah, nm, read that wrong.
