### ISSUE TITLE
https://www.openshift.org SSL cert

### ISSUE THREAD

**Issue by seriu** [openshift/origin#3949]
Wasn't totally sure where to report this, if I've put this in the wrong section, please advise:
When going to https://www.openshift.org on chrome, it pops up a security warning about the SSL cert. It says that the cert is for *.rhcloud.com

![invalid cert](https://cloud.githubusercontent.com/assets/8479010/8965935/8657f2d4-35fc-11e5-886f-2b2802d674f9.png)

Since this is the default one linked from some documentation about Origin on the regular site, am I the only one who encountered this? 

Oh, as a side note, the https version doesn't redirect https://openshift.org to the webpage (small enough I didn't figure it warranted a separate bug)

![no redirect](https://cloud.githubusercontent.com/assets/8479010/8965961/968bd7ba-35fc-11e5-9b33-ae411826ffe8.png)

Encountered on Fedora 21&22, Chrome (44.0.2403.125) and Firefox (images not included, but same results)

**Comment by liggitt** [comment]
Thanks for the report. This isn't the right repo for that, but I've forwarded the info to the correct team.
