### ISSUE TITLE
[RFE] access to routing subdomain, default route, namespace in templates

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#3967]
It would be nice if we had access to a variable that represented the routing subdomain inside a template. It would also be nice to have a default route available.

This way, in a template, you could do something like:

```json
   {
      "kind": "Route",
      "apiVersion": "v1",
      "metadata": {
        "name": "keyvalue-route"
      },
      "spec": {
        "host": "${DEFAULT_ROUTE}",
        "to": {
          "kind": "Service",
          "name": "frontend"
        }
      }
    },
````

Or perhaps:

```json
   {
      "kind": "Route",
      "apiVersion": "v1",
      "metadata": {
        "name": "keyvalue-route"
      },
      "spec": {
        "host": "${GENERATED_EXPRESSION}.${NAMESPACE_VAR}.${SUBDOMAIN}",
        "to": {
          "kind": "Service",
          "name": "frontend"
        }
      }
    },
```

**Comment by thoraxe** [comment]
Note that the web console "create" workflow actually ends up generating a default route for you based on the subdomain and the namespace and the service name, but I don't think it does that via any kind of established variables.

**Comment by liggitt** [comment]
If you leave the host empty, you get the default generated route

**Comment by thoraxe** [comment]
yeah, just found that out.
