### ISSUE TITLE
Audit log

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#3976]
Hi All,
     I would like to  get all commands that were executed by all the users in my OSE V3 cluster, is there any audit log ?
I'm asking this because probably Corporate Security Team will ask me about this issue soon ...

Many thanks.

**Comment by bergerx** [comment]
Seems like basic auditing capabilities added on #8815

**Comment by priyanka5** [comment]
@roldancer @bergerx : apologies for writing on close thread, but just wanted to confirm did that work for you. I am trying to do same in openshift enterprise 3.2 but it doesnt work. any help?
