### ISSUE TITLE
dedicated Nodes

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#3979]
Hi All, I would like to know if it is possible to configure a dedicated group of nodes only for a specific security group, the idea is that only users that belongs to a specific group can deploy pods/service/rc/is/dc... etc on a specific group of nodes (dedicated nodes).

It is possible? or will be it planned for a future release ?

many thanks.

**Comment by smarterclayton** [comment]
You can do it today by labeling nodes with some thing like dedicated=1, assigning a project node selector that grants access to those nodes (and having a default project node selector that prohibits those nodes, I.e. dedicated=none).  A project you enable to have access to those nodes is thus the only group of users who can access those nodes.

With groups, if you assign groups to users directly or use the upcoming LDAP group sync you can manage the groups in LDAP and only grant the group a role on the project.  

If you are provisioning projects for users on request this is an easy way to control who gets added.  If you wanted to do this dynamically, there are several ways to build this with the API.

**Comment by danmcp** [comment]
Please reopen if there are any remaining issues/questions.
