### ISSUE TITLE
Can't sync imagestreamtag with docker hub image tag 

### ISSUE THREAD

**Issue by mdshuai** [openshift/origin#3980]
Use-case:
After add some tags on dockerhub I can use "oc import-image" to sync the tag in imagestream. But when delete some tags on dockerhub the tags can't be deleted in imagestream.

**Comment by ncdc** [comment]
Importing is a one-way import; it's not a two-way sync, and it's only additive. #3485 is the issue for being able to delete image stream tags.

**Comment by pweil-** [comment]
Closing as dupe of https://github.com/openshift/origin/issues/3980 which will add delete ability.
