### ISSUE TITLE
Pod template ports run together in UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3991]
![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/9046375/39cd7196-39f8-11e5-856f-0a29568e6f87.png)

@jwforres

**Comment by jwforres** [comment]
so at one point these where stacked vertically but that was probably when they were outside the container box.  it also looks like we dropped the rendering of the mapping of container port to host port and pod port?

**Comment by liggitt** [comment]
not sure what you mean by pod port... the mappings happen at the service level

**Comment by jwforres** [comment]
might just be thinking of host port

**Comment by jwforres** [comment]
host port is probably only relevant on one-off pods that aren't being routed to by services
