### ISSUE TITLE
Unclear what container port corresponds to name in UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3992]
![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/9046421/81430e32-39f8-11e5-9812-41671f83bd75.png)

Related to #3662 and #3991. (Same screenshot as #3991, but different problem.)

**Comment by spadgett** [comment]
Looking at the JSON, I see the name right there with the port in the container spec. This should be easy to add. @jwforres Are we keeping the pod template on the overview page?

**Comment by jwforres** [comment]
@spadgett i think so , but maybe we need a "minimal" pod template and a more detailed one?

**Comment by jwforres** [comment]
Partially fixed by https://github.com/openshift/origin/pull/5431

But need to update the object describers to match.
