### ISSUE TITLE
Show build trends in UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3994]
Add visual history/trend summary on the build config in the browse builds page.

See https://github.com/openshift/origin/pull/3812#issuecomment-123925715

**Comment by smarterclayton** [comment]
+1 - historical builds should be dense and useful info, rather than consume a lot of space.

**Comment by sspeiche** [comment]
+1 - it is quite helpful to have some simple summary as well: last successful build, last failed build, ...

**Comment by spadgett** [comment]
Related to #5186
