### ISSUE TITLE
hello-openshift example

### ISSUE THREAD

**Issue by Yashu5** [openshift/origin#3995]
Hi, i am just curious to know where is the port 6061 is defined in "examples/hello-openshift/" image?

Can anyone please explain how it is working in OpenShift v3?

Thanks,
Yash

**Comment by nak3** [comment]
README is wrong. port 6061 is not available after this PR https://github.com/openshift/origin/pull/3496/files#diff-4e8186fbcfd40aa5049ce30ff5781a70L18

**Comment by Yashu5** [comment]
Hi , Thanks :) I am able to access it on port 8080 and 8888 as defined in "hello_openshift.go" using 
curl 172.0.0.4:8080  instead of localhost

but this does not allow me to access it from browser , how can I access app from browser?


Thanks,
Yash

**Comment by nak3** [comment]
You can access app from external network by setting up routing[0]. 
I think it is a little difficult to setup, so if you have any further question, please ask us via user's ML[1].
We are happy to assist you.

[0] https://github.com/openshift/origin/blob/master/docs/routing.md 
[1] http://lists.openshift.redhat.com/openshiftmm/listinfo

**Comment by bparees** [comment]
closing as question has been answered, @Yashu5 feel free to reopen or post to the mailing list if you have further questions.  thanks!
