### ISSUE TITLE
[RFE] allow route behavior to be defined in route itself

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#3998]
Currently if you don't want sticky/cookies with the route you have to customize the router template which further requires rebuilding the router itself and doesn't allow for individualized behavior per-route.

We should be able to, in the route definition, specify the type of routing to do.

eg:
sticky/cookie
round-robin
etc.

**Comment by ramr** [comment]
@JacobTanenbaum, think the docs are missing for this. If you could update that please. Thx

@thoraxe , you can use annotations to specify this now.
Ref: https://github.com/openshift/origin/blob/master/images/router/haproxy/conf/haproxy-config.template#L251
Example:  `oc annotate route r1 haproxy.router.openshift.io/balance=sticky`

**Comment by ramr** [comment]
There is another related issue to the docs: https://github.com/openshift/openshift-docs/issues/2960

**Comment by pweil-** [comment]
resolved
