### ISSUE TITLE
openshift cloud driver in kubernetes

### ISSUE THREAD

**Issue by lexlapax** [openshift/origin#40]
I know we're attempting to use openshift on openshift where, the openshift components are deployed via kubernetes.

The flip side of this is, if you have an openshift 3.0 running and functional, you should be able to deploy a kubernetes pod configuration directly onto a running openshift 3.0 cluster via the kube.sh scripts in kubernetes source tree.. almost similar to azure, gce, but not quite.. in the sense those cloud drivers are IaaS drivers.. 

a little Meta, i know, but i'd like feedback on this..

**Comment by smarterclayton** [comment]
Closing this for now - I don't think we have any short term plans to do work on this, but there's some interesting ideas in it.
