### ISSUE TITLE
[RFE] certificate extraction via oc/oadm via "trust this server?" dialogue

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#4002]
Currently the installation process involves generating a CA certificate, but there is no way to actually get at it without having shell access to the system. This means that the installer/administrator must extract the CA certificate from the FS and then distribute it.

It would be great if the CA cert was somehow available via the API / web UI.

**Comment by liggitt** [comment]
The certs are returned with every connection... you can extract them like this:
```
$ openssl s_client -showcerts -connect localhost:8443 </dev/null
```

The first cert is the server cert. The second is the CA.

**Comment by thoraxe** [comment]
Updated the issue. Here's a user story:

* as a user of openshift
* when I first run the "oc" command and point it at a server
* I should be prompted to trust the server (if I don't already have the right CA)
* and the "oc" tool should download the certificate for later use

**Comment by smarterclayton** [comment]
For an customer using their own certs this seems like a bad thing to enable - organizations are responsible for distributing trust, not Openshift.  I think it might be nice to offer something like this, but we'd get asked to disable it for the most secure environments.

**Comment by liggitt** [comment]
I could see that being worse than the current "Do you want to allow connecting insecurely?" prompt, since it implies things are nice and secure, then the user might be trusting an imposter

**Comment by thoraxe** [comment]
How is that any different from when Firefox prompts you to ask if you want to trust the security of the remote site? It doesn't refuse to let you connect with SSL...

**Comment by liggitt** [comment]
oc doesn't refuse either, it prompts you to connect insecurely:
```
$ oc login
Server [https://localhost:8443]: 
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Username: jordan
Authentication required for https://localhost:8443 (openshift)
Password: 
Login successful.

You don't have any projects. You can try to create a new project, by running

    $ oc new-project <projectname>

Welcome! See 'oc help' to get started.
```

that connection is still made using TLS, but should be considered insecure.

**Comment by thoraxe** [comment]
Yeah, I guess.

Still is a pain to distribute the self-generated CA cert :)

**Comment by liggitt** [comment]
prompting for insecure mode allows connecting to insecure servers without implying they are secure
