### ISSUE TITLE
Add documentation about how to write extended test

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#4006]
We should add documentation, that will describe how a developer can:

1) Write a single extended test
2) Add a new group of extended tests
3) Run the tests he wrote (with server configuration he require)
4) Use the extended CLI framework to call 'oc' command
5) Use upstream E2E framework

**Comment by mfojtik** [comment]
@gabemontero @jhadvig FYI

**Comment by mfojtik** [comment]
@gabemontero I know that you and Jakub will work on this, just keep in mind that there is one issue that @deads2k will be looking at: https://github.com/openshift/origin/issues/4005

This might change the way you writing the extended tests but the Ginko framework or the OpenShift CLI framework we have there should not be affected.

**Comment by gabemontero** [comment]
@mfojtik OK - thx for the update / pointers

**Comment by bparees** [comment]
@mfojtik not sure if this ever got done?  if not you own it until it does :)  (but @jhadvig can help...and @gabemontero can review..)

**Comment by mfojtik** [comment]
@bparees @gabemontero as soon as https://github.com/openshift/origin/pull/4256 is merged I'm going to add document describing how to write extended test.

**Comment by mfojtik** [comment]
@bparees @gabemontero also what form it should have? just a markdown in `./docs` ?

**Comment by jhadvig** [comment]
@mfojtik let me know how may I help you on this one.

**Comment by mfojtik** [comment]
@jhadvig in fact, you can: https://github.com/openshift/origin/pull/4258

(you still have commit rights to my fork ;-)

**Comment by jhadvig** [comment]
@mfojtik with great power comes great responsibilties !

**Comment by stevekuznetsov** [comment]
@mfojtik Stick it in the README.md inside of `test/extended` and link it from HACKING.md

**Comment by bparees** [comment]
+1 @stevekuznetsov

**Comment by mfojtik** [comment]
Initial documentation added. Closing
