### ISSUE TITLE
Allow to specify arbitrary image for deployment lifecycle hook

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#4007]
When I want to use the 'post' deployment hook to verify my deployment, it would be nice if I can execute my verification (readiness?) check on arbitrary image instead of running it in the image I deploying.
The verification can call the `oc tag` command (in case I want to build simple continuous delivery tool) and I don't necessarily want to have the `oc` binary in my application image. 

The change I propose is to add 'PodSpec' to `ExecNewPodHook`:

```go
type ExecNewPodHook struct {
        // PodSpec is the specifaction of Pod I want to run
        Pod PodSpec `json:"pod" description:"a pod specification"`
}
```

instead of:

```go
type ExecNewPodHook struct {
	// Command is the action command and its arguments.
	Command []string `json:"command" description:"the hook command and its arguments"`
	// Env is a set of environment variables to supply to the hook pod's container.
	Env []kapi.EnvVar `json:"env,omitempty" description:"environment variables provided to the hook container"`
	// ContainerName is the name of a container in the deployment pod template
	// whose Docker image will be used for the hook pod's container.
	ContainerName string `json:"containerName" description:"the name of a container from the pod template whose image will be used for the hook container"`
}
```

The `PodSpec` should only allow specification of 'one-time' Pod (with no restart policy). The the Pod finishes, we should evaluate the Pod status and based on that fail/promote the deployment.

**Comment by mfojtik** [comment]
@bparees @smarterclayton FYI (making the lifecycle hooks more smarter)

**Comment by smarterclayton** [comment]
We didn't want to do this originally because it requires normal hook cases to get harder.  So I don't want to go back to it.

Can you describe the use cases where you're using a different image?  I want to figure out whether we need everything on a pod spec.  I also want to know what we *don't* want.

cc @ironcladlou

**Comment by mfojtik** [comment]
@smarterclayton I think we just need to pass a name of an arbitrary image that we execute the command defined in hook on.
The use-case is that I want to `oc tag` the image as part of the promotion process and I want to `oc tag` from the deployment hook. Right now, I will have to copy the `oc` binary to the image. As a workaround I can download it when I run the verification/promotion command, but I think that is ugly ;-)
Another use-case is that I want to use the image for other deployment(s)/images so I don't have to copy my verification/promotion script into N images.

**Comment by mfojtik** [comment]
@smarterclayton I think you don't need the full PodSpec (for example you don't need to define ports), but  you might want to use volume to store logs/etc.

**Comment by bparees** [comment]
what about just allowing an ObjectReference to an ImageStreamTag/ImageStreamImage/DockerImage as an additional field that is an alternative to ContainerName (ie one or the other must be provided, not both).

that wouldn't enable the volumes scenario @mfojtik just added as i was typing this though :)

regardless we could still keep the existing fields and add PodSpec as an alternate way to define what to run, rather than the only way, in order to avoid @smarterclayton 's concerns about simplicity.

**Comment by mfojtik** [comment]
@bparees we might also generate the hook by having better CLI about it, right? I mean we should not let users write this ideally ;-)

**Comment by smarterclayton** [comment]
This hook is really a simpler PodSpec.  If we can't make a case for a full
pod spec, then we should behave a lot like a regular pod spec (including
the image).  I don't think we have use cases that justify infinite
flexibility, but if we did, I'd say that we would do it with PodTemplates
and a reference, not embed it inline.

On Wed, Aug 5, 2015 at 1:46 PM, Michal Fojtik <notifications@github.com>
wrote:

> @bparees <https://github.com/bparees> we might also generate the hook by
> having better CLI about it, right? I mean we should not let users write
> this ideally ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4007#issuecomment-128088334>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
It seems just as easy to me to put this and all future requests to bed and support a new hook type which users can choose:

```go
// LifecycleHook defines a specific deployment lifecycle action.
type LifecycleHook struct {
	// FailurePolicy specifies what action to take if the hook fails.
	FailurePolicy LifecycleHookFailurePolicy
	// ExecNewPod specifies the options for a lifecycle hook backed by a pod.
	ExecNewPod *ExecNewPodHook
	// CustomPod specifies the template for a pod which implements arbitrary hook behavior.
	CustomPod *PodSpec
}
```

`ExecNewPod` and `CustomPod` would be mutually exclusive. If you write some doomed pod definition that blocks too long or does crazy stuff, it doesn't matter much to us: we'll set a deadline on it regardless ensuring it finishes eventually.

In hindsight, `ExecNewPod` is a poorly named field. :disappointed:

**Comment by mfojtik** [comment]
@ironcladlou :+1:

**Comment by smarterclayton** [comment]
I could live with that.  Also, it's not enough to do pod spec.  You have to
do PodTemplateSpec

On Wed, Aug 5, 2015 at 1:57 PM, Michal Fojtik <notifications@github.com>
wrote:

> @ironcladlou <https://github.com/ironcladlou> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4007#issuecomment-128091608>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
The best image is going to be a prepared one for users that handles a lot of common use cases simply - like can send an email, curl a URL, run an oc command, etc.

**Comment by ironcladlou** [comment]
@mfojtik please close this out and we'll track it in https://trello.com/c/37qFSFZO going forward
