### ISSUE TITLE
Add a command to add/edit/remove annotations

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4008]
Same as `oc label`, but for annotations. Needed for things like namespace nodeSelector editing, etc.

/cc @thoraxe

**Comment by smarterclayton** [comment]
Have we opened an upstream issue for this?

**Comment by deads2k** [comment]
> Have we opened an upstream issue for this?

Upstream recently merged this: https://github.com/GoogleCloudPlatform/kubernetes/pull/11779

**Comment by fabianofranz** [comment]
@liggitt I think this is fixed by `oc annotate`, can you close?
