### ISSUE TITLE
Generate CSRs to streamline signing with custom CA

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4009]
Instead of (or in addition to) generating certificates, generate certificate signing requests for the server and client certificates, to make it easier to use a custom CA.

/cc @sdodson

**Comment by sdodson** [comment]
We had a lengthy discussion about this today and the conclusion was that the area where using externally signed certs is most valuable would be on externally facing master interfaces. Either by establishing a second listening port (443!) or by putting a proxy in front of the environment. Consensus was that most deployments would be OK with internal components using the autogenerated CA/Certs.

**Comment by smarterclayton** [comment]
David and I had an even lengthier discussion on Friday after the platform management arch meeting, need to circle back with Jordan and discuss where we got to.
