### ISSUE TITLE
oadm registry -o yaml|json don't create valid definitions

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#4012]
As of OSE 3.0.1.0:

```
# oadm registry -o yaml  --replicas=2 --credentials=.kube/openshift-registry.kubeconfig \
                           --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' \
                           > registry.yaml
# oc create -f registry.yaml
[...bunch of json...]
error: no objects passed to create
# head registry.yaml
items:
- Details: null
  LatestVersion: 0
  Template:
    ControllerTemplate:
      replicas: 2
      selector:
        docker-registry: default
      template:
...
```

None of the definitions output specify kind or apiVersion. Think this needs a format update.

This means if you want to modify the registry, say to add an NFS volume, you have to create it and then modify it. Not the end of the world, but it should not be so.

**Comment by liggitt** [comment]
Looks like it's serializing the internal scheme (note upper-case keys), not a versioned scheme

**Comment by smarterclayton** [comment]
This is p0 - seems like a regression as well.
