### ISSUE TITLE
Builds of a particular type can be started even if you disable access to the /builds/[type] subresource

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#4017]
BZ reference:  https://bugzilla.redhat.com/show_bug.cgi?id=1246426
So if you have an existing BuildConfig of type Docker, and then disable access to the builds/docker subresource, you can still create new builds by just using `oc start-build [buildconfig]` 
Cause: The builds admission control will prevent creation of new Build objects, but using the /generate endpoint bypasses admission control by going directly to the etcd registry client.

Proposed solutions: 

1. Leave as is. 
    If you've created a BuildConfig already that has a particular build type, then you can create builds with it regardless whether you have permission to create that build type or not.  You can also set different permissions on the generate and build create endpoints - (ie. you could give somebody access to generate so they can create new builds from existing BuildConfigs but not give them access to create new Builds or BuildConfigs)

2. Change the client used by generate
    Instead of using the registry client, use the API client. It would require that the auth headers passed in the request to the generate endpoint be forwarded to the client request to create a build (didn't find a good way to do that with the current client framework, but no didn't see a reason it can't be done). Builds would then go through auth control and admission control. There would be no way to only grant permission to a user to generate builds. They would also need permission to create builds.

3. Change how the generate endpoint behaves by returning a new build object and not creating it for you. 
     The generate endpoint would get a new sequential name from the BuildConfig and update it, then return a new Build object. The client would then be responsible for creating the new Build. Forwarding of auth headers is not needed. We would need to figure out what to do with image triggers and the LastTriggeredImage because now we've decoupled creating a build from its generation. Needs more thought.

4. Change the generate endpoint to trigger level-driven builds. It would update the BuildConfig, and then a separate controller would create the build from the BuildConfig. For admission control to prevent generating new builds of a particular type, it would have to block the BuildConfig from getting updated, which means generate would have to use the API client, and just as in #2 above would need to have a way to do pass-thru auth.

**Comment by csrwng** [comment]
@bparees @deads2k @liggitt @smarterclayton - ptal - comments are welcome

**Comment by liggitt** [comment]
>  It would require that the auth headers passed in the request to the generate endpoint be forwarded to the client request to create a build (didn't find a good way to do that with the current client framework, but no didn't see a reason it can't be done).

That's not possible if the user was authenticated via certificate.

**Comment by csrwng** [comment]
@liggitt - thx, then that discards that option :-)

**Comment by liggitt** [comment]
I sort of like the ability to define a docker buildconfig and let lowly users generate builds from it without giving them the ability to run arbitrary docker builds

**Comment by csrwng** [comment]
I just realized I left out another option:
1a. Leave things mostly as they are and add a check to the generate endpoint in admission control. If you're trying to generate a build of a type you're not allowed to create, then you won't be allowed. This would preserve the ability to give different permisisons to generate and create builds

**Comment by bparees** [comment]
3+4 seem more involved than i'd want to get into for this.

so it seems that leaves 1 and 1a.  of which 1a seems like the way to go.

**Comment by liggitt** [comment]
I like 1a the best so far. would the admission check on generate be different than the admission check on build create? if not, how could you give different permisisons to generate and create builds?

**Comment by csrwng** [comment]
@liggitt it would be almost the same check. They are orthogonal resources. The builds/docker subresource is the one controlling whether you can create Docker builds. But apart from that you have /builds, /buildConfigs and /buildConfigs/generate controlling whether you can post something to those resources.

**Comment by liggitt** [comment]
right now, posting a docker build or a docker buildConfig both check "builds/docker". Would calling generate check "builds/docker" as well, or something different?

**Comment by csrwng** [comment]
it would check builds/docker as well

**Comment by liggitt** [comment]
so you couldn't let someone create non-docker builds, while letting them generate builds from a docker build config

**Comment by csrwng** [comment]
yes, true

**Comment by csrwng** [comment]
we can always come up with more subresources :)

**Comment by liggitt** [comment]
I think doing the `builds/<type>` admission check on generate still makes the most sense of the suggestions seen so far. What about cloning a build?

**Comment by csrwng** [comment]
it would still go through generate

**Comment by liggitt** [comment]
we'd need to make sure it went through admission with the right type and as the right user

**Comment by csrwng** [comment]
It does if it's initiated by the user (cli or web console). If a build config has image triggers though, the privileged client invokes generate and admission control would let it through, which I guess is ok.

**Comment by wewang58** [comment]
Disable the Docker build strategy so we set build restriction; if we also can trigger a build  from an existing docker buildconfig, I think we cannot controle the build .
