### ISSUE TITLE
Commands that don't accept args should fail when args are passed

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4021]
Not all commands are properly restricting the use of arguments.  This means that they will silently ignore these args, resulting in unexpected behavior.  For example:

```
oc whoami --context somevalue
```

should fail, but it runs without complaint.

We need to do a check of all the commands to make sure they have validation for this condition.

@stevekuznetsov ptal

**Comment by deads2k** [comment]
@tiwillia fyi

**Comment by juanvallejo** [comment]
@stevekuznetsov some commands, such as `oc config` are part of the k8s pkg, any pointers on how those should be approached?

https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/config/config.go

**Comment by liggitt** [comment]
upstream PRs :)

**Comment by juanvallejo** [comment]
Will do, thanks Jordan
