### ISSUE TITLE
Wrong cASE of trigger names cause template create failures

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#4024]
It is common that people may "guess" the wrong value for various things, like valid case in build trigger names such as "GitHub". If someone mis-types the name in the JSON which defines the template, the template is created fine. When that template is used, the build config isn't created due to "invalid trigger".

```
Cannot create BuildConfig jws-app. BuildConfig "jws-app" is invalid: [triggers[0].type: invalid value 'Github': invalid trigger type, parameters.source.git.uri: required value]
```

Granted, people should test their templates before deploying but I wonder why the names (which are the primary key) are case sensitive. Are we encouraging people to write 2 different build triggers "a" and "A"? I hope not.

A couple of usability things that could be done to improve this experience:
 1. make it easier to develop valid templates
 1. validate templates as they are created and make available
 1. make the trigger names ignore case
 1. create a build config but leave off the trigger, this would allow someone to still use the template and then add the trigger.

**Comment by smarterclayton** [comment]
We really want to avoid case insensitivity.  There should be an easier way to validate a template (although templates are designed so they can contain objects the server does not understand to facilitate aggregation of API services - foo and bar can be in the same template but not be aware of each other).

A dry run on create would help a lot, as would a way to validate a list of objects from the client.

**Comment by rhcarvalho** [comment]
> 4\. create a build config but leave off the trigger, this would allow someone to still use the template and then add the trigger.

This is the behavior since #4556 was merged 3 days ago. When the server sees an unknown trigger name (including wrong capitalization), it will output a warning (only on the server side), but the creation of the BuildConfig will proceed, ignoring the unknown triggers.

A dry run to instantiate objects from a template would be nice to have, as well as an easier way to create valid templates, perhaps a graphical tool within the Web Console.

**Comment by mfojtik** [comment]
@rhcarvalho is this issue resolved now?

**Comment by rhcarvalho** [comment]
@mfojtik, tl;dr we can probably close this issue.
Long version, by item originally mentioned:

> 1. make it easier to develop valid templates

We can improve this, but it should be a Trello card. Existing card I found:
https://trello.com/c/etnmoCP0/644-validate-template-dependencies

I didn't find a card about having some tooling for building valid templates, so I created one:
https://trello.com/c/Be7ovpXY/706-tooling-for-creating-valid-templates


> 2\. validate templates as they are created and make available

The first Trello card I mentioned above is about template validation. Not sure we can validate the template at time of "making available", as some errors will only show up when you instantiate it.


> 3\. make the trigger names ignore case

We'll not do this.
(See Clayton's comment above)


> 4\. create a build config but leave off the trigger, this would allow someone to still use the template and then add the trigger.

This is resolved. Unrecognized triggers are dropped from BCs.

**Comment by thesteve0** [comment]
@rhcarvalho  if we had a valid JSON schema we could actually at least allow the proper nesting of elements and also give hints like "oneOf:" and regex's for the form.

**Comment by rhcarvalho** [comment]
@thesteve0 thanks for the comment, I've extracted it into a docs issue -> https://github.com/openshift/openshift-docs/issues/1220. Please comment if you have further ideas or clarification.

**Comment by thesteve0** [comment]
Nope, I want the enum in the schema - not just in the doc. Would be good to
have in the doc but if you also put it in the schema then the doc can
autogenerate it and it can be checked with tooling.

**Comment by kcd83** [comment]
Sorry to comment on a closed issue but could there be user defined parameter validation?

A template author could specify [a-z]+ to prevent mistakes.

It would also prevent templates with multiple resources getting half created when some substitions don't follow openshift/kubernetes rules. Seems like low hanging fruit compared to implementing dry runs etc.

**Comment by bparees** [comment]
> Sorry to comment on a closed issue but could there be user defined parameter validation?

it's been discussed/considered: https://trello.com/c/T3imAczk

**Comment by kcd83** [comment]
Great!
