### ISSUE TITLE
router.go#routeKey produces ambiguous keys

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4035]
A route named "baz" in a namespace "foo-bar" and a route named "bar-baz" in a namespace "foo" both produce the same key "foo-bar-baz"

```
func (r *templateRouter) routeKey(route *routeapi.Route) string {
	return fmt.Sprintf("%s-%s", route.Namespace, route.Name)
}
```

/cc @pweil-

**Comment by ramr** [comment]
@liggitt  - can you please close this now that #4298 has merged .Thx
