### ISSUE TITLE
godep save fails

### ISSUE THREAD

**Issue by miminar** [openshift/origin#4041]
If I add a new dependency with `go get` and try to save it with `godep save ./...` I get:

```
godep: cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/securitycontextconstraints" in any of:
    /usr/lib/golang/src/github.com/GoogleCloudPlatform/kubernetes/pkg/securitycontextconstraints (from $GOROOT)
    /home/miminar/workspace/go/openshift/src/github.com/GoogleCloudPlatform/kubernetes/pkg/securitycontextconstraints (from $GOPATH)
godep: cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/securitycontextconstraints" in any of:
    /usr/lib/golang/src/github.com/GoogleCloudPlatform/kubernetes/pkg/securitycontextconstraints (from $GOROOT)
    /home/miminar/workspace/go/openshift/src/github.com/GoogleCloudPlatform/kubernetes/pkg/securitycontextconstraints (from $GOPATH)
godep: error loading dependencies
```

AFAIK `securitycontextconstraints` is being added in currently opened [PR#7893](https://github.com/GoogleCloudPlatform/kubernetes/pull/7893). If I add the directory [1] manually to `$GOPATH/src/github.com/GoogleCloudPlatform/kubernetes/pkg`. It succeeds but I'm not sure of it's correctness since it adds new entry to `Godeps/Godeps.json:`

```
    {
            "ImportPath": "github.com/GoogleCloudPlatform/kubernetes/pkg/securitycontextconstraints",
            "Comment": "v1.0.0",
            "Rev": "cd821444dcf3e1e237b5f3579721440624c9c4fa"
    },
```

and removes:

```
    Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/securitycontextconstraints/fake.go
```

Is there any (un)documented workaround to get this done cleanly?

[1] https://github.com/pweil-/kubernetes/tree/security-policy/pkg/registry/securitycontextconstraints

**Comment by mfojtik** [comment]
@miminar I don't think `godep save` will work properly as we do have some patches on top of kubernetes. The way I usually adding new packages to godeps is to manually copy the package to `Godeps/_workspace` and then manually update the Godeps.json. It is not ideal but that way works ;-)

**Comment by miminar** [comment]
@mfojtik I see. That's unfortunate. I'll do it this way too. Nevertheless, I'm not going to close this since it's a worrisome bug.

**Comment by mfojtik** [comment]
@miminar agree. we had some discussions (cc @csrwng) about forking kubernetes to OpenShift organization and apply our patches there. However, that could complicate our CI worflow (for example your PR depends on change in that repo).

**Comment by mfojtik** [comment]
also CC @smarterclayton and @bparees here ;-)

**Comment by bparees** [comment]
don't look at me, i resort to horrible hacky workflows whenever i need to do this stuff.

**Comment by csrwng** [comment]
`godep update [package]/...` almost works for existing packages, except that new dependencies are not added to Godeps.json

**Comment by smarterclayton** [comment]
There's no way to fix this when we have to carry upstream patches easily.  The fork, while nice for these sorts of problems, introduces other problems.  In general, we should try to avoid adding new packages into Godeps/ and add more work to hack/rebase-kube to handle these cases.

**Comment by smarterclayton** [comment]
Also, when you godep save ./... you typically delete the entire Godeps first to clear our carried patches.

**Comment by smarterclayton** [comment]
We have the two scripts now.
