### ISSUE TITLE
Previously visible build hidden in UI when clicking Start Build

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4045]
On the browse builds page, we show only the most recent build with a link to show more. When you click start build, however, the new running build takes the place of the older build. I found this confusing (even though I wrote the code...).

We should probably show the last complete build and any running builds on this page, hiding older builds. I think it's OK to replace the build-2 with build-3 when build-3 completes.

**Comment by spadgett** [comment]
See #3812

**Comment by spadgett** [comment]
I can't reproduce. Will reopen if I see it again.

**Comment by spadgett** [comment]
Closed the wrong issue :(

**Comment by jhadvig** [comment]
@spadgett I can still reproduce the issue. Or where not referring to this one ?

**Comment by spadgett** [comment]
@jhadvig Right, I typed my comment in the wrong issue.

**Comment by spadgett** [comment]
@jhadvig have you started looking at this?

**Comment by spadgett** [comment]
@jhadvig sorry if you've started on this. I was assigned it as a release blocker, so wanted to get a fix in.

**Comment by jhadvig** [comment]
@spadgett ok, no problem :)
