### ISSUE TITLE
Rebase follow up: Investigate the need to pass the etcd client to storage implementations

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#4048]
The new storage interface is meant to abstract away the underlying implementation so we no longer have access to the EtcdClient directly.  For now the client has been exposed on the master config so it can be passed back to the individual storage objects that require it.  Investigate if this can be removed.

Ref: https://github.com/pweil-/origin/commit/31785ae4ba2d106919b9a3ce5acf4ec0ddc28706#commitcomment-12589429

**Comment by legionus** [comment]
We have only two places where EtcdClient used directly:
https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/run_components.go#L169
https://github.com/openshift/origin/blob/master/pkg/cmd/server/start/start_master.go#L432
