### ISSUE TITLE
Problem with services & btrfs

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#405]
Running OpenShift in a Docker container with btrfs storage engine leads to services not working reliably. Not quite sure how the storage engine affects services, but I'm regularly getting:

    Failed to properly wire up service.  This can happen if you forget to launch with permissions to iptables.

OpenShift container is being run like:

    docker run -d --name=openshift \
        -v /var/run/docker.sock:/var/run/docker.sock \
        --privileged --net=host openshift/origin:latest start

Logs show:

````
Failed to properly wire up service.  This can happen if you forget to launch with permissions to iptables.  Access to the following services will be impaired:
````

followed by pretty much all the services I've requested creation of.

Docker info:

````
Containers: 17
Images: 126
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.17.2-200.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)
````

Using btrfs instead of devicemapper (which works with services fine btw) as it's just too slow at deleting containers & also leads to cannot delete container errors regularly.

**Comment by smarterclayton** [comment]
As far as I know there's no progress on btrfs and selinux. OverlayFS work is proceeding, which should resolve the performance issues.

**Comment by jimmidyson** [comment]
Thanks. Been playing with overlayfs & looks very promising. Do you know
where I can track the state of selinux support for overlayfs?
