### ISSUE TITLE
Flakiness in upstream tests

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#4050]
@pmorie - documenting this for further investigation.  So far what I've seen are failures in port forwarding, events, and exec.  Never locally, only in travis.

@ramr has seen them in the events test https://github.com/openshift/origin/pull/4026#issuecomment-128594902

**Comment by ramr** [comment]
And here's another example in a change to only docs #4038  - failing test in this case was: 
```
E0807 00:48:32.958913   11306 errors.go:56] apiserver received an error that is not an api.Status: type apiserver.UnregisteredAPIObject is not registered for "version" and it will be impossible to Decode it, therefore Encode will refuse to encode it.
--- FAIL: TestMaxInFlight-2 (1.03s)
	handlers_test.go:49: unexpected response: 429
2015/08/07 00:48:34 RoundTripper returned a response & error; ignoring response
FAIL
```

**Comment by liggitt** [comment]
Are you running locally with the same args that exercise raciness and multiple processes?

**Comment by pweil-** [comment]
I'm testing locally with `TEST_KUBE=1 PATH=~/gitbin:$PATH hack/test-go.sh ''  -p=4` which was the command I took from the travis log

**Comment by stevekuznetsov** [comment]
Seen issues with:

* [`TestForwardPorts`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/portforward/portforward_test.go#L290)
* [`TestEventf`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event_test.go#L59 )

**Comment by stevekuznetsov** [comment]
Also now seeing:

* `[TestRequestExecuteRemoteCommand]`(https://travis-ci.org/openshift/origin/jobs/75076860#L1453)

**Comment by stevekuznetsov** [comment]
Furthermore: 
* [`TestRequestAttachRemoteCommand`](https://travis-ci.org/openshift/origin/jobs/75271585#L1453)

**Comment by stevekuznetsov** [comment]
* [`TestServiceRegistryIPUpdate`](https://travis-ci.org/openshift/origin/jobs/75303537#L1519)

**Comment by liggitt** [comment]
opened individual issues for flakes. closing this issue.
