### ISSUE TITLE
Help message for 'oc get' is wrong

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4054]
```
$ oc get pvc --headers=false
Error: unknown flag: --headers
Run 'oc help' for usage.
```

Should be "Run 'oc get --help'".  This might be related to the template being shown here (fixing this might accidentally break other commands, so be careful).

**Comment by liggitt** [comment]
prints usage now, doesn't show incorrect help command
`oc get` prints `See 'oc get -h' for help and examples.`
