### ISSUE TITLE
hack/test-cmd generating credentials twice?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4062]
```
[INFO] Create certificates for the OpenShift server to /tmp/openshift-cmd/t2Tp/openshift.local.config/master
Generated new key pair as /tmp/openshift-cmd/t2Tp/openshift.local.config/master/serviceaccounts.public.key and /tmp/openshift-cmd/t2Tp/openshift.local.config/master/serviceaccounts.private.key
Generating node credentials ...
Created node config for 127.0.0.1 in /tmp/openshift-cmd/t2Tp/openshift.local.config/node-127.0.0.1
Wrote master config to: /tmp/openshift-cmd/t2Tp/openshift.local.config/master/master-config.yaml
Generating node credentials ...
Created node config for 127.0.0.1 in /tmp/openshift-cmd/t2Tp/openshift.local.config/node-127.0.0.1
```

Not sure that 'generating node credentials ...' should show up twice.

**Comment by liggitt** [comment]
We're running `create-node-config` and `start --write-config`, so I would expect it twice

**Comment by smarterclayton** [comment]
Hrm.  K

On Mon, Aug 10, 2015 at 1:11 PM, Jordan Liggitt <notifications@github.com>
wrote:

> We're running create-node-config and start --write-config, so I would
> expect it twice
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4062#issuecomment-129529067>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift
