### ISSUE TITLE
SELinux type for volume dir should be a config item

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#4067]
...to support custom policies.  Should be done whether directory was created by openshift binary or not.

@ncdc @smarterclayton

**Comment by smarterclayton** [comment]
Which volume dir are we talking about?  Root volume dir?  The argument was made if you want a custom policy, create the dir yourself.  Does that solve the problem?

**Comment by pmorie** [comment]
@smarterclayton it does -- I guess we need to add docs around custom SELinux policies that deal with this (unless you think no one wants to do this yet).

**Comment by smarterclayton** [comment]
I don't think we need it yet (the docs)

On Aug 27, 2015, at 2:13 AM, Paul Morie <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> it does -- I guess we
need to add docs around custom SELinux policies that deal with this (unless
you think no one wants to do this yet).

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4067#issuecomment-135294331>.

**Comment by swagiaal** [comment]
@pmorie can this be closed now since we can specify selinux context in the PodSecurityContext ?
