### ISSUE TITLE
oc policy add-role-to-user should have a shortcut for adding a service account

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4068]
It's difficult today to create a template that includes a role binding to a service account (because the name contains the namespace).  From the CLI, it would be useful to have

    oc policy add-role-to-user --service-account=router edit

We should also add an easy way to templatize the current namespace (@bparees).

@deads2k

**Comment by bparees** [comment]
like an implied parameter ${PROJECT} which always takes the value of the current project?

the only weird bit about that is currently "oc process" is basically project agnostic today, and it won't be if we do this.  but that's probably not a big deal.

**Comment by smarterclayton** [comment]
It'll probably get less agnostic over time - esp. if we want to do stream /
name deresolution for relative image names at process time.

David and I are still trying to sort out the
cluster-scoped-resource-that-can-also-be-accessed-in-a-namespace issue.  An
admin with no projects shouldn't be forced to create one to process the
template he uses to create a project.

On Aug 9, 2015, at 10:06 PM, Ben Parees <notifications@github.com> wrote:

like an implied parameter ${PROJECT} which always takes the value of the
current project?

the only weird bit about that is currently "oc process" is basically
project agnostic today, and it won't be if we do this. but that's probably
not a big deal.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4068#issuecomment-129274842>.

**Comment by smarterclayton** [comment]
Maybe make it an explicit generation target.  Implicit is bad for
discoverability.

On Aug 9, 2015, at 10:06 PM, Ben Parees <notifications@github.com> wrote:

like an implied parameter ${PROJECT} which always takes the value of the
current project?

the only weird bit about that is currently "oc process" is basically
project agnostic today, and it won't be if we do this. but that's probably
not a big deal.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4068#issuecomment-129274842>.

**Comment by bparees** [comment]
> Maybe make it an explicit generation target. Implicit is bad for discoverability.

i agree w/ the challenges of having an implicit/system parameter name, but i'm not clear what "make it an explicit generation target" means.

**Comment by liggitt** [comment]
We already support generators. Create a new "current namespace" generator

**Comment by bparees** [comment]
@liggitt ah, of course. thanks :)

**Comment by smarterclayton** [comment]
Sorry, wasn't communicating clearly.  I'll show some of what I'm talking
about tomorrow.

On Aug 9, 2015, at 11:19 PM, Ben Parees <notifications@github.com> wrote:

@liggitt <https://github.com/liggitt> ah, of course. thanks :)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4068#issuecomment-129287415>.
