### ISSUE TITLE
"Remember me" login

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#4073]
This would really help with usability, especially when using OpenShift oauth as a kind of SSO for multiple apps, normally with multiple registered oauthclients, or even with one reused oauthclient.

**Comment by liggitt** [comment]
what would "remember me" do? about the only thing it could do safely is extend the life of the granted OAuth token, which should be up to an admin already (they can make tokens last a week, etc, if they want)

**Comment by deads2k** [comment]
We could track identity for users that logged in via challenge/response and automatically fill in `-u` when the token is expired.

**Comment by deads2k** [comment]
Actually, this is a perfect case for issuing a JWT, isn't it?

**Comment by liggitt** [comment]
how is an expiring JWT different than an expiring OAuth token, user experience-wise?

**Comment by jimmidyson** [comment]
Oh please issue JWTs! But that's another story...

This was actually a problem with latest chrome beta causing problems not sending cookies reliably... I was using oauth endpoint to secure some cluster services & chrome beta was asking for authentication when switching between services. Annoying. Worked fine in chrome stable so don't care any more.

So about JWTs...

**Comment by deads2k** [comment]
A JWT could hold the name of the identity that it was issued for.  We could use that from login to auto-fill the `user` field without adding annotations to kubeconfig.

**Comment by liggitt** [comment]
:-1: on introspecting tokens. you don't even know that the username returned matches the login name the user would enter to log in

**Comment by jimmidyson** [comment]
From a user experience PoV, probably nothing - would expect it to be the
same.

But from a developer PoV, validation without call back to issuing server
for validation, no server side state for auth in services, ability to
propagate auth & claims around cluster microservices, Would love to see it.

**Comment by jimmidyson** [comment]
@liggitt Thinking of stuff like user connecting to UI protected with oauth; issued JWT; subsequent calls to UI coordinated to multiple microservices, which may (will) in turn call other microservices. Propagating JWT through distributed call stack for authn & authzn simplifies stuff in this regard.

**Comment by deads2k** [comment]
> on introspecting tokens. you don't even know that the username in the jwt would match the login name the user would enter to log in

Didn't say username, said identity.  Why not include identity.
