### ISSUE TITLE
Rebase follow up: review nsenter mounter

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#4076]
We are carrying a patch that is different from what went in upstream in the nsenter mounter.  The upstream version causes issues in the containerized e2e tests.  Investigate the differences and reset to upstream.

Patch being carried: https://github.com/pweil-/origin/commit/f6ebdae7c14476f887fa25fcae5709852af3377e

**Comment by smarterclayton** [comment]
Fixed by rebase.
