### ISSUE TITLE
[post-rebase-work] Fix conversion in generateConversionsForMap

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4087]
origin had:
```
       g.addImportByPath(inValue.PkgPath())
       g.addImportByPath(outValue.PkgPath())
```

the merged upstream PR (and rebase) had 
```
       g.addImportByPath(inKey.PkgPath())
       g.addImportByPath(outKey.PkgPath())
```

needs fixing and an upstream PR (see comment at https://github.com/GoogleCloudPlatform/kubernetes/pull/9971/files#diff-a04b3a7a947b2fc4e8a132fe9bf04569L155)

**Comment by pweil-** [comment]
submitted https://github.com/openshift/origin/pull/4091

**Comment by liggitt** [comment]
Fixed in the rebase
