### ISSUE TITLE
[post-rebase-work] Re-add "UPSTREAM: 8530: GCEPD mounting on Atomic (eeeda84)"

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4088]
eeeda84 was dropped in the rebase

**Comment by liggitt** [comment]
@kargakis is this on your radar for the current rebase? @pweil-, what's the status of #8530?

**Comment by pweil-** [comment]
8530 was merged upstream.  The current rebase was scoped at exploratory only due to changes we didn't want going in to 3.0.2.  https://github.com/openshift/origin/issues/4093 closes this issue, it's still waiting on a merge but has the ok from @markturansky and @swagiaal

**Comment by liggitt** [comment]
ah, ok

**Comment by pweil-** [comment]
merged
