### ISSUE TITLE
Test flake

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4096]
```
github.com/openshift/origin/pkg/cmd/server/admin.executeNodeConfig(0xc2082f1e58, 0x8, 0x8, 0x0, 0x0)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/admin/create_nodeconfig_test.go:107 +0x721
github.com/openshift/origin/pkg/cmd/server/admin.TestNodeConfigTLS(0xc2082c6990)
	/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/admin/create_nodeconfig_test.go:45 +0x402
testing.tRunner(0xc2082c6990, 0x1bd3e58)
	/usr/lib/golang/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/lib/golang/src/testing/testing.go:555 +0xd4e
*** Test killed: ran too long (2m0s).
```

**Comment by liggitt** [comment]
?

**Comment by liggitt** [comment]
cc @deads2k... I'm sort of at a loss on what could be flaking here... is it possible we just happen to be in this test when the timeout hits?

**Comment by smarterclayton** [comment]
It's possible, not sure how the timeout happened (or what caused it).

On Mon, Aug 10, 2015 at 5:06 PM, Jordan Liggitt <notifications@github.com>
wrote:

> cc @deads2k <https://github.com/deads2k>... I'm sort of at a loss on what
> could be flaking here... is it possible we just happen to be in this test
> when the timeout hits?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4096#issuecomment-129606179>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
It's not obvious to me either.

**Comment by liggitt** [comment]
can't recreate, I think the test ran long. reopen if you see it again
