### ISSUE TITLE
API: ImageStream points to the wrong location in status.dockerImageRepository

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4102]
If the integrated registry is installed, `imageStream.status.dockerImageRepository` should point to the internal location, not the value of spec.

**Comment by smarterclayton** [comment]
@ncdc

**Comment by smarterclayton** [comment]
Has backward API compatibility concerns.

**Comment by ncdc** [comment]
@smarterclayton what scenario are you seeing this for? If the user sets spec, we just use that it's not backed by the integrated registry. What's missing?

**Comment by smarterclayton** [comment]
I had a registry and the status value wasn't the integrated registry -
status.dockerImageRepository should be "where do I push to", not "where
does this pull from" (since image pull spec covers that).

On Aug 11, 2015, at 11:08 AM, Andy Goldstein <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> what scenario are you
seeing this for? If the user sets spec, we just use that it's not backed by
the integrated registry. What's missing?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4102#issuecomment-129922964>.

**Comment by ncdc** [comment]
We don't currently support wholesale imagestream-wide pulling from an external registry for all tags while pushing to the internal registry. Are you saying you want every image stream to always be backed for pushes by the internal registry?

**Comment by smarterclayton** [comment]
On Aug 11, 2015, at 3:52 PM, Andy Goldstein <notifications@github.com>
wrote:

We don't currently support wholesale imagestream-wide pulling from an
external registry for all tags while pushing to the internal registry. Are
you saying you want every image stream to always be backed for pushes by
the internal registry?

Why don't we support that?  Every image stream should be a possible push
target in our internal registry.  Spec.DIR is just a convenient import
mechanism (I want to have all tags from upstream).  We may want to revisit
the design here wrt importing and polling.  Ultimately, we want to define
"track", "import", and "reference" concepts on the IS.  Ref is a soft
link.  Track is a hardlink.  Import is a copy from the outside world.

We don't support pushing to an image stream via its reference from builds -
you should just be pushing to the upstream repository in that case.  I
don't think we care about using an IS as a soft link for push (since it
doesn't really seem common).

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4102#issuecomment-130043399>.

**Comment by ncdc** [comment]
@smarterclayton when you're free let's discuss the desired use cases and get this all figured out once & for all

**Comment by ncdc** [comment]
Related: #3484

**Comment by smarterclayton** [comment]
Can you set up time next week to discuss this?

On Mon, Aug 24, 2015 at 5:32 PM, Andy Goldstein <notifications@github.com>
wrote:

> Related: #3484 <https://github.com/openshift/origin/issues/3484>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4102#issuecomment-134370306>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Blocks the Dockerfile build type because output and input is the same.

**Comment by smarterclayton** [comment]
Fixing this now
