### ISSUE TITLE
Upgrade import registry client to v2 so that we can reference digests

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4103]
We should import v2 registries as v2 so we can get immutable tags.

@ncdc I think this is a pre-3.1 thing.

**Comment by ncdc** [comment]
We need to do the pruning work in that case. We can't upgrade the registry
godep until we refactor pruning as previously discussed so the registry is
responsible for its content, instead of having oadm prune images be the
driver.

**Comment by smarterclayton** [comment]
Is that card scheduled?  Being blocked there probably bad.

On Aug 10, 2015, at 8:20 PM, Andy Goldstein <notifications@github.com>
wrote:

We need to do the pruning work in that case. We can't upgrade the registry
godep until we refactor pruning as previously discussed so the registry is
responsible for its content, instead of having oadm prune images be the
driver.

On Monday, August 10, 2015, Clayton Coleman <notifications@github.com>
wrote:

> We should import v2 registries as v2 so we can get immutable tags.
>
> @ncdc <https://github.com/ncdc> I think this is a pre-3.1 thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4103>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4103#issuecomment-129654953>.

**Comment by ncdc** [comment]
I'm talking with Weil tomorrow morning about it.

**Comment by smarterclayton** [comment]
Is the auth dance the annoying part?

On Aug 10, 2015, at 8:40 PM, Andy Goldstein <notifications@github.com>
wrote:

I'm talking with Weil tomorrow morning about it.

On Monday, August 10, 2015, Clayton Coleman <notifications@github.com>
wrote:

> Is that card scheduled? Being blocked there probably bad.
>
> On Aug 10, 2015, at 8:20 PM, Andy Goldstein <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> We need to do the pruning work in that case. We can't upgrade the registry
> godep until we refactor pruning as previously discussed so the registry is
> responsible for its content, instead of having oadm prune images be the
> driver.
>
> On Monday, August 10, 2015, Clayton Coleman <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > We should import v2 registries as v2 so we can get immutable tags.
> >
> > @ncdc <https://github.com/ncdc> I think this is a pre-3.1 thing.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openshift/origin/issues/4103>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4103#issuecomment-129654953>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4103#issuecomment-129656855>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4103#issuecomment-129658162>.
