### ISSUE TITLE
We need to fake our factory

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#4105]
This will help a lot in unit testing cli commands (currently almost none tests [there](https://github.com/openshift/origin/tree/2f643e3ed91a558eb7f17f839a38e93bd1628f73/pkg/cmd/cli/cmd))

Some things that may need to be done:
* Export upstream fake factory (currently found in a [test](https://github.com/GoogleCloudPlatform/kubernetes/blob/44c91b1a397e0580d403eb9e9cecd1dac3da0b25/pkg/kubectl/cmd/cmd_test.go#L184) file)
* Override whatever we want, as we currently do with our real factory
* We will probably need to override our own factory methods as well such as f.Clients (inject a fake RESTClient is the way (?) to do it [currently](https://github.com/GoogleCloudPlatform/kubernetes/blob/44c91b1a397e0580d403eb9e9cecd1dac3da0b25/pkg/kubectl/cmd/cmd_test.go#L199-L201), would be much easier if f.Clients and f.Client where returning Interfaces instead of the implementations but this is another story).

@deads2k WDYT?

**Comment by deads2k** [comment]
> @deads2k WDYT?

I think that we need to refactor the entire `Factory` class into a set of interfaces and ripple those interfaces through the code to limit the scope of what has to be faked.  That's a whole lot of work, but it will make the whole thing much easier to follow.

In the meantime, I'm not opposed to other approaches.  Have you looked at how easy or hard it would be wire these directly into integration tests?  I know I've done that a couple times.  With clean `Options` structs, it's usually pretty easy and that tests most of the guts, combined with a `test-cmd.sh` test to two to make sure that the `Complete` method is wired correctly.

No matter which way, I agree with the goal and I'm not terribly picky about how we get there.
