### ISSUE TITLE
End to end test error in Vagrant environment

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4107]
I'm consistently seeing this error running the end to end tests in Vagrant (clean build against latest master).

> FATA[0011] Error response from daemon: v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry gcr.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/gcr.io/ca.crt

**Comment by liggitt** [comment]
@spadgett still an issue?

**Comment by spadgett** [comment]
Haven't gotten it to run cleanly, but the error I'm seeing now is different (clean build from this morning).

```
[INFO] Waiting for command to finish: 'oc get -n test builds | grep -i complete'...
ruby-sample-build-1   Source    Failed    ruby-sample-build-1-build
[FAIL] Returning early. Command Failed 'oc get -n test builds | grep -i complete'

[FAIL] !!!!! Test Failed !!!!
```

I'll check the container logs.

**Comment by spadgett** [comment]
Tried again this morning, and get the same build error as above. Here is the container log.

```
I0910 15:45:23.279709       1 cfg.go:50] Problem accessing /root/.dockercfg: stat /root/.dockercfg: no such file or directory
I0910 15:45:23.282301       1 sti.go:78] Creating a new S2I builder with build config: "Builder Image:\t\topenshift/ruby-20-centos7@sha256:dd24fd5dff4f262a02f69c16dc1b047dd01d4b2673d4a738a396e55b1d0cffad\nSource:\t\t\thttps://github.com/openshift/ruby-hello-world.git\nOutput Image Tag:\t172.30.238.189:5000/test/origin-ruby-sample\nEnvironment:\t\tOPENSHIFT_BUILD_NAMESPACE=test,OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/ruby-hello-world.git,OPENSHIFT_BUILD_NAME=ruby-sample-build-1\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I0910 15:45:23.290729       1 docker.go:187] Pulling image openshift/ruby-20-centos7@sha256:dd24fd5dff4f262a02f69c16dc1b047dd01d4b2673d4a738a396e55b1d0cffad
I0910 15:45:34.285633       1 docker.go:190] An error was received from the PullImage call: Tag sha256:dd24fd5dff4f262a02f69c16dc1b047dd01d4b2673d4a738a396e55b1d0cffad not found in repository docker.io/openshift/ruby-20-centos7
F0910 15:45:34.285686       1 builder.go:70] Build error: unable to get openshift/ruby-20-centos7@sha256:dd24fd5dff4f262a02f69c16dc1b047dd01d4b2673d4a738a396e55b1d0cffad
```

**Comment by spadgett** [comment]
It took maybe 30 minutes for the e2e tests to dump the logs in my Vagrant environment.

**Comment by bparees** [comment]
this isn't strictly an openshift image registry issue, but that's as close as i can guess (really it sounds like a docker problem)

**Comment by bparees** [comment]
I should also note that those builds run as part of e2e so this has to be somehow unique to this env.  

does it fail every time?

**Comment by spadgett** [comment]
> I should also note that those builds run as part of e2e so this has to be somehow unique to this env.

This env meaning my environment specifically or Vagrant?

> does it fail every time?

I've gotten this failure the last few times I've tried. I could `vagrant destroy`, but I'm hesitant to since I have Hawkular configured.

**Comment by bparees** [comment]
yours specifically (possibly the image your vagrant is running) since our e2e tests run on vagrant also.

**Comment by pweil-** [comment]
are you able to manually pull the image and see it in `docker images` with that sha?

It seemed to work in my vagrant env

```
# e2e log
[INFO] Success running command: 'oc get -n test builds | grep -i running' after 4 seconds
[INFO] Build ruby-sample-build-1 started
[INFO] Waiting for test namespace build to complete
[INFO] Waiting for command to finish: 'oc get -n test builds | grep -i complete'...
ruby-sample-build-1   Source    Complete   ruby-sample-build-1-build
[INFO] Success running command: 'oc get -n test builds | grep -i complete' after 96 seconds
[INFO] Build ruby-sample-build-1 finished


# build container log
I0910 17:19:04.080636       1 docker.go:187] Pulling image openshift/ruby-20-centos7@sha256:dd24fd5dff4f262a02f69c16dc1b047dd01d4b2673d4a738a396e55b1d0cffad
I0910 17:19:05.647670       1 sti.go:84] Starting S2I build from test/ruby-sample-build-1 BuildConfig ...
I0910 17:19:05.647692       1 sti.go:112] Building 172.30.191.94:5000/test/origin-ruby-sample

```

```
[vagrant@openshiftdev origin]$ docker images --digests
REPOSITORY                                         TAG                 DIGEST                                                                    IMAGE ID            CREATED             VIRTUAL SIZE
...snip...
docker.io/openshift/ruby-20-centos7                <none>              sha256:dd24fd5dff4f262a02f69c16dc1b047dd01d4b2673d4a738a396e55b1d0cffad   05c451f23cee        38 hours ago        396.6 MB
```

You might try deleting any ruby-20-centos7 images you already have first.

**Comment by pweil-** [comment]
closing due to age, please reopen if this is still an issue
