### ISSUE TITLE
Scheduler config serialization backwards compatility breakage

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#4112]
@abhgupta @liggitt If possible we need to make this change backwards compatible before OSE 3.0.2.

    $ git show 220fd6af3b805708045128b119c20a714670e424  Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go
    commit 220fd6af3b805708045128b119c20a714670e424
    Author: Paul Weil <pweil@redhat.com>
    Date:   Tue Aug 4 19:24:57 2015 -0400
     
        bump(github.com/GoogleCloudPlatform/kubernetes):b73c53c37d06bc246eb862a83df51c8fd75994f8
     
    diff --git a/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go b/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go
    index 1546412..8d9cc9b 100644
    --- a/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go
    +++ b/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go
    @@ -67,10 +67,10 @@ func defaultPriorities() util.StringSet {
                    factory.RegisterPriorityFunction("BalancedResourceAllocation", priorities.BalancedResourceAllocation, 1),
                    // spreads pods by minimizing the number of pods (belonging to the same service) on the same minion.
                    factory.RegisterPriorityConfigFactory(
    -                       "ServiceSpreadingPriority",
    +                       "SelectorSpreadPriority",
                            factory.PriorityConfigFactory{
                                    Function: func(args factory.PluginFactoryArgs) algorithm.PriorityFunction {
    -                                       return priorities.NewServiceSpreadPriority(args.ServiceLister)
    +                                       return priorities.NewSelectorSpreadPriority(args.ServiceLister, args.ControllerLister)
                                    },
                                    Weight: 1,
                            },
     

CC: @sosiouxme @detiber

**Comment by liggitt** [comment]
not sure what you mean... we already lay down a scheduler.json file that locks priorities, right?

**Comment by liggitt** [comment]
or are you saying the serialization format changed?

**Comment by liggitt** [comment]
ah, got it... can you include a default scheduler.json from 3.0.0 and 3.0.1 and I'll create a compatibility test

**Comment by sosiouxme** [comment]
Here was my scheduler:

```
{
  "predicates": [
    {"name": "MatchNodeSelector"},
    {"name": "PodFitsResources"},
    {"name": "PodFitsPorts"},
    {"name": "NoDiskConflict"},
    {"name": "Region", "argument": {"serviceAffinity" : {"labels" : ["region"]}}}
  ],"priorities": [
    {"name": "LeastRequestedPriority", "weight": 1},
    {"name": "ServiceSpreadingPriority", "weight": 1},
    {"name": "Zone", "weight" : 2, "argument": {"serviceAntiAffinity" : {"label": "zone"}}}
  ]
}
```

I did nothing but change `ServiceSpreadingPriority` to `SelectorSpreadPriority` and it started up again, but I can't claim to know if they're perfectly compatible.

**Comment by liggitt** [comment]
Broke in https://github.com/GoogleCloudPlatform/kubernetes/pull/10667/files#r36776577

I'll spawn an upstream issue and work on a fix

**Comment by abhgupta** [comment]
The previous priority function (ServiceSpreadingPriority) ONLY considered services and the new priority function (SelectorSpreadPriority) considers both services and replication controllers for spreading. 

Do we need to ensure backward compatibility in functionality as well? As in, do we create a ServiceSpreadingPriority that uses the new priority function but ignores the replication controllers (perhaps by passing an empty lister for RCs)?

**Comment by liggitt** [comment]
Fixed upstream in https://github.com/kubernetes/kubernetes/pull/12544
