### ISSUE TITLE
Ability to make env variables available to buildconfig with oc new-app command

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift/origin#4123]
We want to be able to pass environment variables that are used by the build process when we create an application. This can be achieved with .sti/environment but is not available via CLI.

**Comment by bparees** [comment]
should also apply to new-build command.

**Comment by mfojtik** [comment]
@jhadvig fyi

**Comment by jhadvig** [comment]
@mfojtik looking on this one

**Comment by jhadvig** [comment]
https://github.com/openshift/origin/issues/4233 is dealing with this issue but from the deploymentConfig perspective

**Comment by bparees** [comment]
per scrum discussion, we need to retain the ability to add an env variable to just the deployment config, because if you add an env variable to the buildconfig it gets baked into the image which might be undesirable.

so we need basically two flags, one to add env variables to the DC, and one to add them to the BC.

**Comment by bparees** [comment]
@csrwng fyi.

**Comment by jhadvig** [comment]
PR: https://github.com/openshift/origin/pull/4358

**Comment by smarterclayton** [comment]
This isn't really the intent of new-app - if you need to customize the build config, you should use oc env after you create the app.  Build accepting env is fine, but new-app is not intended to be infinitely customized.

**Comment by smarterclayton** [comment]
The solution to your problem veer is:

    oc new-app ... <common env>
    oc env bc/name <build env>
    oc env dc/name <dc env>

**Comment by bparees** [comment]
@smarterclayton by "build accepting env is fine" do you mean oc new-build?

**Comment by smarterclayton** [comment]
Yes, oc new-build should take <ENV> because it only creates a build.

**Comment by bparees** [comment]
@smarterclayton by "build accepting env is fine" do you mean oc new-build?

**Comment by smarterclayton** [comment]
I thought it already did, if it doesn't we can reopen this issue for it.

**Comment by bparees** [comment]
@jhadvig can you check and redirect your PR to new-build if it doesn't take those args?

**Comment by bparees** [comment]
@smarterclayton while I i can see your point that we don't want to invest a huge effort here, given that @jhadvig already did the work i don't see a lot of harm in merging it.

**Comment by jhadvig** [comment]
@bparees you mean port only the `--bc-env` to the `new-build` command ? 
And what about the `--dc-env` ?

**Comment by smarterclayton** [comment]
I don't want --bc-env or --dc-env in new-app.  It doesn't match what the point of new-app is.

**Comment by smarterclayton** [comment]
new-app is "given a limited set of inputs, create an app".  It is not intended to handle deep customization of each object.  Since we have the ENV command this the equivalent of --bc-env and --dc-env, adding more code to new-app contradicts that goal.  If your env doesn't apply to all the components of the app equally, its' not something that should be passed to new-app.

**Comment by smarterclayton** [comment]
What happens when services have an equivalent to env?  Should we add --svc-env?  What about the build secret?  or the deploy secret?  The line we've drawn with new-app is "a set of common inputs to build the framework for an app".  However... the env passed to new-app *should* go to the build config (that's not unreasonable) if it can be construed as useful.

**Comment by bparees** [comment]
@smarterclayton putting env in the buildconfig automatically is dangerous.  those env vars end up baked into the image.  there's a valid use case for "i want to provide env vars to my deployment, but i don't want it baked into the image".

given your arguments, i don't see why we support env vars on new-app at all.  either we should not support them, or we should support configuring exactly which objects the env vars apply to.  having them either apply to an arbitrary subset (the situation today) or having them apply to everything (what you seem to be proposing) both strike me as problematic.

**Comment by smarterclayton** [comment]
Env on new-app is arguments to the template or the deployment config.  Those are demonstrably useful to stay, which is why we have them - that is not arbitrary, that is use case driven.  If passing it to the build config is dangerous, then we shouldn't add them automatically.  But bc being dangerous to default doesn't make --bc-env fall within the scope of new-app.

**Comment by smarterclayton** [comment]
As an example, here are two approaches:

    $ oc new-app php DB_USER=foo DB_PASSWORD=bar
    $ oc env bc/php HTTP_PROXY=http://foo.bar

vs.

    $ oc new-app php DB_USER=foo DB_PASSWORD=bar --bc-env=HTTP_PROXY=http://foo.bar

The former is two cleanly decoupled commands.  Anyone who knows about bc can handle the former.  Anyone who doesn't know about bc isn't going to be using --bc-env.  The two command version is only 6 characters longer than the combined version.

**Comment by smarterclayton** [comment]
Adding --bc-env to new-app makes the help for new-app more complex, and also won't work when new-app creates something that doesn't have a builder (which is common).  The more complex the help for new-app gets, the harder it is for a new user to understand what it is doing.  So adding new arguments and new behaviors to new-app has a higher bar.

**Comment by jhadvig** [comment]
@smarterclayton if is it common not to have buildConfig in template, why do we have the `--context-dir` flag in the new-app command (which I guess is the customization param for the buildConfig) ?

**Comment by VeerMuchandi** [comment]
The only issue I see with the two command approach is that if you don't run
the second command immediately the build may get trigger immediately
without the env variables that need to be set and it would fail.
Including that in the new-app command will make sure there are no such
issues.

**Comment by smarterclayton** [comment]
So in that case you can do:

    oc new-build php HTTP_PROXY=http://foo.bar
    oc new-app php ...

**Comment by smarterclayton** [comment]
@jhadvig --context-dir is because some git repos are useless without content dir (a large fraction).  The number of builds that won't work without build config environment variables is much lower.  And if it is a high fraction, that's more of an infrastructure problem, and the infrastructure should be defaulting those things (if every build in your installation is going to need an HTTP proxy, that should be a global config variable that defaults that on every build config).

**Comment by smarterclayton** [comment]
Also if you need a custom CA cert for every build on your infrastructure, that should be something an admin configures by default across the entire environment, not set onto every single build config.

**Comment by jhadvig** [comment]
@smarterclayton I can see your point, although not sure if various combinations of commands in order to deploy something with desired environment variables is the best approach, saying "If you wanna add this envvars to this config run these set commands, otherwise run these commands in this order...". 
Sooner or later we will end up adding a flag(s) that are not fitting into your described new-app profile (eg the context-dir).
Nevertheless should the `--bc-env` flag (or some equivalent of that name) be introduced instead to the `new-build` command ?

Also I found out that the `--env` flag in the `new-app` command is not propagating the envVars to the deploymenConfigs - https://github.com/openshift/origin/issues/4363

**Comment by smarterclayton** [comment]
new-build should accept environment the same as new-app, but write that to
the build config.  I thought that was a review comment I left when
new-build was created - if not it's a bug and needs to be fixed.

new-app isn't about infinite flexibility.  It's about turning standard
images, source, or templates into apps.  Setting custom build config flags
doesn't really fit into that.  If you know about build config environment
variables, you're expected to know about the `env` command or `new-build`.
The rule of thumb for adding things to new-app is whether a new user to the
platform needs it to install their app.  Knowing about proxies is really an
admin responsibility, as are things like custom builds.

On Tue, Aug 25, 2015 at 1:22 PM, Jakub Hadvig <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> I can see your point,
> although not sure if various combinations of commands in order to deploy
> something with desired environment variables is the best approach, saying
> "If you wanna add this envvars to this config run these set commands,
> otherwise run these commands in this order...".
> Sooner or later we will end up adding a flag(s) that are not fitting into
> your described new-app profile (eg the context-dir).
> Nevertheless should the --bc-env flag (or some equivalent of that name)
> be introduced instead to the new-build command ?
>
> Also I found out that the --env flag in the new-app command is not
> propagating the envVars to the deploymenConfigs - #4363
> <https://github.com/openshift/origin/issues/4363>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4123#issuecomment-134658133>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
so to attempt to summarize, we want:

1) oc new-build to take an env argument which adds env to the BC it creates

2) oc new-app to take an env argument which adds env to the DC it creates (but does nothing to builds and does nothing when processing templates)

3) document in the new-app documentation that if you need to customize the BC new-app creates, use other commands to do so after creating it.  and if your build is going to fail to run w/o that customization, then either      
  a) accept that you'll have an initial failed build, or 
  b) output new-app json to a file, edit that file to remove all the build triggers, create the BC, then use oc commmands to customize it.
  c) output new-app json to a file, edit that file by hand to add the necessary env/etc, and create the BC
  d) (longer term) enable admins to setup openshfit deployments such that global proxies, global certs, etc, can be picked up automatically by buildconfigs.

have i missed anything?

**Comment by smarterclayton** [comment]
1. oc new-build should take env like oc new-app does - on the command line,
implicitly (oc new-app A=B)
2. oc new-app and oc new-build should also support --env correctly (it
looks like it's broken)

3e. If you don't like 3b/3c and your problem isn't solved by 3d, you should
be creating a template for your users.



On Tue, Aug 25, 2015 at 3:36 PM, Ben Parees <notifications@github.com>
wrote:

> so to attempt to summarize, we want:
>
> 1) oc new-build to take an env argument which adds env to the BC it creates
>
> 2) oc new-app to take an env argument which adds env to the DC it creates
> (but does nothing to builds and does nothing when processing templates)
>
> 3) document in the new-app documentation that if you need to customize the
> BC new-app creates, use other commands to do so after creating it. and if
> your build is going to fail to run w/o that customization, then either
>
> a) accept that you'll have an initial failed build, or
> b) output new-app json to a file, edit that file to remove all the build
> triggers, create the BC, then use oc commmands to customize it.
> c) output new-app json to a file, edit that file by hand to add the
> necessary env/etc, and create the BC
> d) (longer term) enable admins to setup openshfit deployments such that
> global proxies, global certs, etc, can be picked up automatically by
> buildconfigs.
>
> have i missed anything?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4123#issuecomment-134695972>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by csrwng** [comment]
> oc new-app and oc new-build should also support --env correctly (it looks like it's broken)

Apart from new-build not setting variables on bc's which is new behavior, new-app's current behavior should be correct. It only sets env vars on the deployment configs that it generates.

**Comment by smarterclayton** [comment]
If you specify a param that has the same name as an env variable passed to
new-app, it should probably override it.  If a user has a template with
MONGODB_USER, and they specify "oc new-app mongodb MONGODB_USER=foo" I'm
pretty sure they expect MONGODB_USER to be overridden.  However, if that's
the behavior we have today, then I think it's ok to not have other
variables automatically get added to the env... IF we tell the user they
won't get added.  "oc new-app mongodb MONGODB_USER=foo A=B" and we're not
creating a new DC and A=B is silently dropped, that's wrong too.  It might
be to give an error that tells the user to use --env.

On Tue, Aug 25, 2015 at 8:55 PM, Cesar Wong <notifications@github.com>
wrote:

> oc new-app and oc new-build should also support --env correctly (it looks
> like it's broken)
>
> Apart from new-build not setting variables on bc's which is new behavior,
> new-app's current behavior should be correct. It only sets env vars on the
> deployment configs that it generates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4123#issuecomment-134773150>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
>  oc new-app and oc new-build should also support --env correctly (it looks like it's broken)

broken how?

**Comment by jhadvig** [comment]
@bparees check https://github.com/openshift/origin/issues/4363.

**Comment by jhadvig** [comment]
@smarterclayton can't we have only one of `--param`, `--env`, that would do the same thing? I mean, if there is envvar with the same name, override it, if there isn't add it.

**Comment by smarterclayton** [comment]
We need to circle back on whether the complexity is necessary.

The argument today for -p being separate and env not applying is:

* templates provide parameterization
* if the template author wanted you to change the env, they would have
exposed the option

On the flip side, consider "oc new-app mongodb php~source" where mongodb is
a template.

If I specify MONGODB_PASSWORD, do I want PHP to get that as an env var?
Probably yes.

If I typo MONGODB_PASSWRD, do I expect that value to be silently ignored?
No.

What about MONGODB_DB_COLLATION or a mongo specific param? Probably no.

If I only specify a single template "oc new-app mongodb ...", I probably
expect everything I specify to apply.  If something I specify as a
parameter doesn't exist in at least one template, I would expect an error.

We have --env today so someone can be explicit about an argument in an
unusual form.

So in general, we have good reasons to separate them.  I'm slightly less in
favor of not applying argument env to templates now than I was before.

Other arguments about when certain things wouldn't apply?

On Aug 26, 2015, at 8:55 AM, Jakub Hadvig <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> can't we have only one
of --param, --env, that would do the same thing? I mean, if there is envvar
with the same name, override it, if there isn't add it.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4123#issuecomment-134963291>.
