### ISSUE TITLE
s2i incremental builds are broken

### ISSUE THREAD

**Issue by bparees** [openshift/origin#4127]
1) we don't pull the old version of the application image to the node unless forcePull is true.  We should always pull the old version of the image when incremental is true.  @mfojtik @soltysh @gabemontero 
2) we don't use credentials when pulling the old version of the image.  We need to use the push credentials (because we're pulling the image from the same place we're later going to push to) when we do the pull.

@ncdc fyi.

**Comment by bparees** [comment]
Also we currently remove the image after building it which is counter productive to using it for incremental builds:
https://github.com/openshift/origin/blob/master/pkg/build/builder/sti.go#L98

i'm not sure why we're doing that, we should probably rely on pruning to clean up local images.

**Comment by ncdc** [comment]
Pruning doesn't do anything with local image storage on a node. It only affects etcd and the registry's storage.

How likely is it that 2 successive builds get scheduled onto the same node? For a small cluster, probably a good chance. For a big cluster, I'd assume not very.

**Comment by ncdc** [comment]
Kube does do image garbage collection, btw. I'm not super familiar with the algorithm or details.

**Comment by bparees** [comment]
yeah i was using pruning generically, didn't mean to refer to the registry pruning.

**Comment by bparees** [comment]
as for the odds of a build hitting the same node....depends.  if you have nodes dedicated to running build pods, the odds go up.

**Comment by bparees** [comment]
and of course for developer use cases (eg i'm running a small cluster to play with) which is definitely a case where incremental would be useful (since you're probably doing a lot of rebuliding) you likely don't have many nodes.
