### ISSUE TITLE
Lock down cadvisor port

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4143]
Embedded cadvisor opens a port at 4194. Need to secure it or prevent it from being opened.

See https://github.com/kubernetes/kubernetes/issues/11710

cc @jimmidyson

**Comment by jimmidyson** [comment]
We should have no need for it to be open. Nothing uses it at the moment AFAIK - metrics are gathered through the read-only port via heapster under `/stats` or prometheus under `/metrics`.

**Comment by jimmidyson** [comment]
And it's `4194`, not ~~`4914`~~.

**Comment by jimmidyson** [comment]
Just tested by binding other process to `4194` before starting up kubelet so cadvisor couldn't bind & it's not required for `/stats` to work, even though https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/README.md says it is - outdated from before cadvisor was embedded I guess.

**Comment by jimmidyson** [comment]
See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_linux.go#L99-L103
