### ISSUE TITLE
new-app should not change the meaning of --template

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4144]
For commands that support the `-o` flag, `--template` has an expected meaning.   `oc new-app` is changing the meaning of `--template` making it hard to predict what is happening.  We should remove the colliding flag.

During the last rebase, this was fatal because of https://github.com/kubernetes/kubernetes/issues/12668.

@smarterclayton @csrwng @fabianofranz Can we break backwards compatibility for this flag to make it consistent with all others?

**Comment by smarterclayton** [comment]
No.

On Thu, Aug 13, 2015 at 1:08 PM, David Eads <notifications@github.com>
wrote:

> For commands that support the -o flag, --template has an expected
> meaning. oc new-app is changing the meaning of --template making it hard
> to predict what is happening. We should remove the colliding flag.
>
> During the last rebase, this was fatal because of
> kubernetes/kubernetes#12668
> <https://github.com/kubernetes/kubernetes/issues/12668>.
>
> @smarterclayton <https://github.com/smarterclayton> @csrwng
> <https://github.com/csrwng> @fabianofranz
> <https://github.com/fabianofranz> Can we break backwards compatibility
> for this flag to make it consistent with all others?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4144>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
> No.

Is that a statement of "backward compatibility at any cost" or a statement of "I like having flags that are standard across other commands being different on a few special ones"?

**Comment by smarterclayton** [comment]
In this context it's more important template means "the thing I create apps
from" than "something I can do to output".

On Aug 13, 2015, at 2:01 PM, David Eads <notifications@github.com> wrote:

No.

Is that a statement of "backward compatibility at any cost" or a statement
of "I like having flags that are standard across other commands being
different on a few special ones"?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4144#issuecomment-130781640>.

**Comment by deads2k** [comment]
Would something like `--template-name` satisfy instead?  I think the intent is still clear, but it wouldn't collide with standard fields.

**Comment by liggitt** [comment]
I'm pretty sure `--template` in new-app is a magic field that can be a file or a template object loaded in the system already

**Comment by csrwng** [comment]
It's not. Only a stored template. --file is used for template file.

**Comment by deads2k** [comment]
> I'm pretty sure --template in new-app is a magic field that can be a file or a template object loaded in the system already



> It's not. Only a stored template. --file is used for template file.


I present this as evidence that no one will be able to definitively say we broke backwards compatibility, because they probably don't know what it does today :)

**Comment by smarterclayton** [comment]
Can't change it :)

On Fri, Aug 14, 2015 at 10:38 AM, David Eads <notifications@github.com>
wrote:

> I'm pretty sure --template in new-app is a magic field that can be a file
> or a template object loaded in the system already
>
> It's not. Only a stored template. --file is used for template file.
>
> I present this as evidence that no one will be able to definitively say we
> broke backwards compatibility, because they probably don't know what it
> does today :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4144#issuecomment-131128219>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
@smarterclayton has spoken, so closing.

@deads2k you can reopen if you get him on board.
