### ISSUE TITLE
Parsing request info for OpenShift apis

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#4147]
When a request fails due to a feature being disabled (ie for Atomic) and a request is made for the disabled resource it ends up in the `serviceErrorHandler`.  This method attempts to parse the request info but it does not parse correctly because the request resolver does not know about the `oapi` and `osapi` when parsing segments from the URL.  Additionally, the error handler does not send the request info to the `NewGenericServerResponse` method which results in ambiguous errors like "the server could not find the requested resource".  

We should investigate making the request resolver aware of the OpenShift prefixes and update the call to `NewGenericServerResponse` to provide more information in the error message.

service error handler: https://github.com/pweil-/origin/blob/1c00a58c5cc91683dc31bd5f48b0cdce28fca360/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go#L166-166

found in: https://github.com/openshift/origin/pull/4115

**Comment by smarterclayton** [comment]
Closing due to age.
