### ISSUE TITLE
client awareness of server apis

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#4149]
Moving forward it is likely that someone could use a client build that does not match the server build.  The first use case of this is an OpenShift client running against an Atomic Enterprise server which has builds disabled.  The client should be aware of what is available on the server based on the swagger information and be able to adapt commands based on the available types.

Ref: https://github.com/openshift/origin/pull/4115

**Comment by smarterclayton** [comment]
This is in the path for cloud forms, either the API endpoint needs to return the objects we support or we should go to swagger.  Not sure which I prefer.  There is other info we need to change

**Comment by deads2k** [comment]
> This is in the path for cloud forms, either the API endpoint needs to return the objects we support or we should go to swagger. Not sure which I prefer. There is other info we need to change

Swagger was the first thing that occurred to me, but if we write out own endpoint, I'd like to to support two modes.  
 1.  Full list of endpoints (sounds a lot like swagger, though it could be substantially shorter).
 1.  Is a particular endpoint supported.

**Comment by smarterclayton** [comment]
The canonical behavior for an api doc is to display links to the items -
that's what "/foo/v1" should contain.  We need an upstream agreement though
before we do anything excessive.  At a minimum the resources you can reach,
the product name, and potentially some other way to flag selective behavior.

On Mon, Aug 17, 2015 at 7:38 AM, David Eads <notifications@github.com>
wrote:

> This is in the path for cloud forms, either the API endpoint needs to
> return the objects we support or we should go to swagger. Not sure which I
> prefer. There is other info we need to change
>
> Swagger was the first thing that occurred to me, but if we write out own
> endpoint, I'd like to to support two modes.
>
>    1. Full list of endpoints (sounds a lot like swagger, though it could
>    be substantially shorter).
>    2. Is a particular endpoint supported.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4149#issuecomment-131791350>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by danmcp** [comment]
Needs to move to card?

**Comment by smarterclayton** [comment]
This is mostly implemented, we need to round it out in 1.3.  Going to close
