### ISSUE TITLE
content of errors on the page can't be copied

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4169]
When I get a pop-up error in the lower right, I can't select text in the error to copy and paste.

![screenshot from 2015-08-14 10 45 24](https://cloud.githubusercontent.com/assets/8225098/9276400/b484e154-4271-11e5-934f-717655e09d4f.png)

**Comment by deads2k** [comment]
@liggitt please tag

Also, @fabianofranz the CLI can handle this correctly, but after the rebase, this fails from the console.  I don't think the test is doing what we think its doing.

**Comment by spadgett** [comment]
Need to change the CreateProjectController to use alerts instead of notifications. We use alerts for errors elsewhere that can be copied.

/cc @benjaminapetersen

**Comment by rhamilto** [comment]
@spadgett or @benjaminapetersen, how do I get the createProject to produce one of these notification errors?  As best I can tell, there is no easy way using solely the web ui.

**Comment by spadgett** [comment]
Easiest might be to temporarily remove the `metadata` stanza from the `DataService.create` request in the JS to force an error.

**Comment by benjaminapetersen** [comment]
You can fake it like this:

```javascript
// from createProject.js

angular.module('openshiftConsole')
  .controller('CreateProjectController', function ($scope, $location, AuthService, DataService, Notification) {

    AuthService.withUser();

    // anything you put here will always run.....
    $scope.alerts = {};
    $scope.alerts["stuff"] = {
      type: "warning",
      message: "Fake stuff out!"
    };


    $scope.createProject = function() {
      $scope.disableInputs = true;
```
