### ISSUE TITLE
[post-rebase-work] unbreak the multi-tenant plugin

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4170]
An interface changed and I stubbed in a `return nil, nil` to complete the rebase.  A real implementation is needed.  See https://github.com/openshift/origin/blob/master/plugins/osdn/multitenant/plugins.go#L69

@rajatchopra

**Comment by liggitt** [comment]
@pravisankar @rajatchopra ETA for bumping sdn to pick up the status check

**Comment by pravisankar** [comment]
@deads2k @liggitt 
Currently we don't depend on Status() hook interface. Stubbing this method is fine for now.
This will be handled properly when we tackle this card: https://trello.com/c/Df3tx5AW/112-move-ip-address-management-from-docker-to-openshift-sdn-support-ability-functionality

**Comment by rajatchopra** [comment]
@pravisankar The status hook does not need stubbing.. we can replace docker inspect directly anyway. This is already merged in openshift-sdn upstream, origin just needs a Godeps rebase:
https://github.com/openshift/openshift-sdn/pull/144

**Comment by dcbw** [comment]
Note that per https://github.com/openshift/origin/issues/4565 even ovssubnet is busted in v1.0.5 due to the Kubernetes Status hook missing in the ovssubnet plugin too.

**Comment by liggitt** [comment]
does that raise the priority of this to a stop ship issue?

**Comment by dcbw** [comment]
The fix for this bug got merged already...  this issue should be closed.

**Comment by eparis** [comment]
this is fixed via https://github.com/openshift/openshift-sdn/pull/144  right?
#4565 is the same thing but for multitenant, which is not a blocker.  So I think this should be closed.

**Comment by liggitt** [comment]
this is to track the multitenant one, sorry for crossing the streams

**Comment by liggitt** [comment]
yes, this can be closed if an impl was provided
