### ISSUE TITLE
[post-rebase-work] upstream flagtypes removed

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4172]
Several flagtypes were removed upstream.  The effort to replace them during the rebase was significant, so I made https://github.com/openshift/origin/commit/199adb7fd03ad0375ca9a7e8fa31aec9f372ab8b to temporarily patch it.

That commit needs to be reverted and our CLI code needs updating.

@fabianofranz

**Comment by fabianofranz** [comment]
`StringList`, `IP` and `IPNet`.
