### ISSUE TITLE
[post-rebase-work] api version is now enforced by api server

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4173]
The API server is now requiring that objects submitted to the API match the version they are being submitted against.  This restriction didn't exist before, but does now.

We should check to make sure the CLI is fully compatible.  One bug in the web console was found and fixed (https://github.com/openshift/origin/commit/866980cd38c72d0d795418fd1cb8bce2ca713317), but more may exist.

This does change existing behavior, but there's a strong argument for it being a bug fix.

**Comment by liggitt** [comment]
The main case I'm concerned about is processing templates containing resources with a mix of versions.

If a stored template has the following resources:
```
pod@v1beta3
pod@v1
deploymentconfig@v1beta3
deploymentconfig@v1
```

then clients that aren't capable of doing conversions in-memory to a current version (e.g. all clients except oc/kubectl) need to submit to four different endpoints (oapi/v1, osapi/v1beta3, api/v1, api/v1beta3). The UI certainly isn't set up for that (it doesn't know all context roots per version). Not sure about the eclipse client

**Comment by deads2k** [comment]
Clients should be doing conversions for objects stored in templates.  We stored the external serializations of those objects with version skewing allowed to handle exactly this case.  The objects in the template should be submitted against their specified versions.

**Comment by deads2k** [comment]
should **not** be doing conversions

**Comment by liggitt** [comment]
hmm... the process endpoint might unify the versions... not sure

**Comment by liggitt** [comment]
does the increased strictness at least let us submit an object without a version to a versioned endpoint?

**Comment by deads2k** [comment]
> hmm... the process endpoint might unify the versions when converting a template into a list... not sure

It uses one of the non-converting runtime types along with map inspection to do the substitution.  It should not be changing the version.  If it is, I think that would be bug.  It certainly can't do it before substitution, since any substituted field would be at risk of not matching expected types and failing the unmarshal.

**Comment by liggitt** [comment]
so if the API server doesn't enable v1beta3, but can still convert those types, we won't allow submitting them at all? and we require every client to know all the context roots for every version in order to submit a template/list? that seems onerous

**Comment by deads2k** [comment]
> and we require every client to know all the context roots for every version in order to submit a template/list?

Knowing how to talk to a versioned API server hardly seems onerous.



> so if the API server doesn't enable v1beta3 endpoints (e.g. it will never return v1beta3 objects), but can still convert those types, we won't allow submitting them at all?

This is a significant side-effect.  I'm not sure how I feel about it.  In this case, it's not just us being mean.  If we've eliminated the API version, there's no reason to believe that we can safely roundtrip the type no matter how friendly we want to be.

**Comment by liggitt** [comment]
>  If we've eliminated the API version, there's no reason to believe that we can safely roundtrip the type no matter how friendly we want to be.

If it doesn't have the type registered to that scheme any more, you'll get an error...

**Comment by deads2k** [comment]
> If it doesn't have the type registered to that scheme any more, you'll get an error...

So you're worried about the case where we still support an API, but the administrator has disabled it so you can't access it anymore.  In that case, while we still support roundtripping the scheme, you want to be able to submit a skewed version to the API server?  That seems like a pretty unlikely case.

The automatic migration of templates seems more problematic.  If I have a template that contains invalid values in fields, that could easily prevent version conversions from working correctly.  How do we help people migrate their templates to new versions?  Best effort and any failures are manually reconciled?  @bparees

**Comment by liggitt** [comment]
Might be related: https://github.com/openshift/origin/issues/3872

**Comment by liggitt** [comment]
I don't like this behavior, but it's definitely intentional upstream, and with the new api group/version stuff, isn't likely to change. Closing this since it is as-designed, tracking the web client update needed in #4410
