### ISSUE TITLE
[post-rebase-work] make the scheduler rate limiter configurable

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4174]
A new rate limiter was added.  I hard-coded the existing defaults, but we need to decide about exposing this.  There may be an existing flag we should respect.

https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/master.go#L163

**Comment by kargakis** [comment]
@deads2k @mfojtik still an issue?

**Comment by deads2k** [comment]
> @deads2k @mfojtik still an issue?

If it is, it would be a problem to address in kube.

@derekwaynecarr @mfojtik did you two ever sort out scheduler ownership?
