### ISSUE TITLE
oc deploy doesn't take "dc/dc-name" format

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4182]
`oc deploy` doesn't take "dc/dc-name" format, making it painful to pipe commands.

@ironcladlou

**Comment by deads2k** [comment]
or @fabianofranz I guess.

**Comment by ironcladlou** [comment]
@liggitt @smarterclayton can somebody label this as a bug?

**Comment by smarterclayton** [comment]
This is blocked on @kargakis's changes upstreams to default type.

**Comment by ironcladlou** [comment]
Blocked in what way? I already have a PR to fix it!

**Comment by smarterclayton** [comment]
If youre using the upstream work he did for plumbing this through resource.Builder?

**Comment by ironcladlou** [comment]
Ah! I cheated. That code isn't yet using resource.Builder, so I did some simple prefix-stripping with a TODO to consider resource.Builder in the future (#4267).

**Comment by smarterclayton** [comment]
Don't.

On Thu, Aug 20, 2015 at 11:27 AM, Dan Mace <notifications@github.com> wrote:

> Ah! I cheated. That code isn't yet using resource.Builder, so I did some
> simple prefix-stripping with a TODO to consider resource.Builder in the
> future (#4267 <https://github.com/openshift/origin/pull/4267>).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4182#issuecomment-133050162>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
The fix is like 4 lines and the code already doesn't use builder, so we could refactor it later and have the practical fix now. But suit yourself!

**Comment by smarterclayton** [comment]
I'd rather not encourage people to not switch to builder - even someone
seeing your example might copy it elsewhere.

On Thu, Aug 20, 2015 at 11:34 AM, Dan Mace <notifications@github.com> wrote:

> The fix is like 4 lines and the code already doesn't use builder, so we
> could refactor it later and have the practical fix now. But suit yourself!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4182#issuecomment-133053291>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
Fair enough.

Blocked by https://github.com/kubernetes/kubernetes/pull/10979

**Comment by ironcladlou** [comment]
Actually... is this really blocked? If no prefix is provided in the arguments, can't I just add the prefix and use resource.Builder as-is?

**Comment by smarterclayton** [comment]
Yes

On Thu, Aug 20, 2015 at 1:01 PM, Dan Mace <notifications@github.com> wrote:

> Actually... is this really blocked? If no prefix is provided in the
> arguments, can't I just add the prefix and use resource.Builder as-is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4182#issuecomment-133076900>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
Did this the better/long way in #4320.
