### ISSUE TITLE
oc status doesn't have colors

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4183]
Lack of colors on failing lines in `oc status` is annoying.  We know something has failed, but the summary really doesn't help it leap out at you.  I'd like to see:
 1. the failed deployment in red.  
 1. completely unfulfilled services with associated (but failing resources) in red
 1. any other service with failed deployments or RCs with 0 pods in yellow.

```
[deads@localhost ~]$ oc --config=openshift.local.config/master/admin.kubeconfig status
In project default

service/docker-registry - 172.30.201.81:5000
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:v1.0.4 
    #1 deployment failed 47 hours ago

service/kubernetes - 172.30.0.1:443

To see more, use 'oc describe <resource>/<name>'.
You can use 'oc get all' to see a list of other objects.
```

@fabianofranz if you already have an issue for this, feel free to close.

**Comment by fabianofranz** [comment]
@liggitt please tag and assign to me.

**Comment by fabianofranz** [comment]
Closing in favor of https://trello.com/c/r50Vp1Yd.

**Comment by stevekuznetsov** [comment]
@deads2k is this real life? What's happened since August?
