### ISSUE TITLE
should oc status show failure events from deployment pods?

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4184]
Knowing a deployment failed is useful, but it'd be nice to either recognize common failure events (failed to pull image) or pull the latest failing event.

**Comment by deads2k** [comment]
@smarterclayton @fabianofranz thoughts?

**Comment by kargakis** [comment]
As part of https://github.com/openshift/origin/issues/4192 I am going to tail the last line from the deployer pod (in case of a failed deployment) and emit it as an event. As part of https://github.com/openshift/origin/issues/8416, I am going to add a similar suggestion to the one we have for failed builds (`oc logs dc/foo` or `oc logs pod/foo-deploy-N` if we do https://github.com/openshift/origin/issues/9294).

**Comment by smarterclayton** [comment]
This is what termination logs are designed for, we shouldn't have to
read the logs.  Can we fix termination logs to be useful?

**Comment by kargakis** [comment]
What are termination logs? How can I get them from where?
