### ISSUE TITLE
Ruby application source build with standalone always fails

### ISSUE THREAD

**Issue by nak3** [openshift/origin#4185]
Env:
---
$ openshift version
openshift v1.0.4-237-g30861f3
kubernetes v1.1.0-alpha.0-1155-gb73c53c

Issue:
---
- `$ oc new-app https://PATH_TO_RUBY_SOURCE --strategy=source` always fails with origin standalone mode.
- I tested PHP, Python, Ruby, and Ruby(OSEv3 w/ master-node). Only Ruby build w/ origin standalone mode was failed. Please see the logs in Result

Result:
---
***Work condition***
- PHP, Python ... other language works fine. - [php s2i log](https://paste.fedoraproject.org/255540/)
- Ruby S2I build with OSEv3(v3.0.1.0-525-geddc479) on master-node configuration works fine.

***Not Work condition***
- Ruby S2I build on upstream's standalone
 - [ruby-hello-world's log](https://paste.fedoraproject.org/255539/) 
   - https://github.com/openshift/ruby-hello-world
 - [sti-ruby's log](https://paste.fedoraproject.org/255537/) 
   - https://github.com/openshift/sti-ruby/tree/master/2.2

**Comment by nak3** [comment]
As log files said, it is permission error. However, I couldn't find which permission should I change.

~~~
I0816 02:55:09.782717       1 sti.go:393] ---> Installing application source ...
E0816 02:55:09.784541       1 sti.go:419] cp: cannot create regular file '././Rakefile': Permission denied
E0816 02:55:09.784603       1 sti.go:419] cp: cannot create regular file '././Dockerfile': Permission denied
E0816 02:55:09.784612       1 sti.go:419] cp: cannot create regular file '././run.sh': Permission denied
E0816 02:55:09.784623       1 sti.go:419] cp: cannot create directory '././views': Permission denied
E0816 02:55:09.784630       1 sti.go:419] cp: cannot create regular file '././Gemfile': Permission denied
...
~~~

**Comment by nak3** [comment]
This issue can reproduce by S2I only. 

eg.
~~~
$ sti build https://github.com/openshift/sti-ruby.git --context-dir=2.0/test/puma-test-app/ openshift/ruby-20-centos7 ruby-sample-app  --loglevel=5
~~~

So, shall I open the New issue at [source-to-image](https://github.com/openshift/source-to-image/issues)?

**Comment by bparees** [comment]
I was able to run 

sti build https://github.com/openshift/sti-ruby.git --context-dir=2.0/test/puma-test-app/ openshift/ruby-20-centos7 ruby-sample-app  --loglevel=5

with no problem.  can you try again with --force-pull=true?

**Comment by nak3** [comment]
@bparees  
--force-pull=true didn't fix this issue.  But after I removed stored images `openshift/ruby-20-centos7` , it worked. 

Then, I found the reproduce steps. I realized that I built the `openshift/ruby-20-centos7` by myself. Please see the reproduce steps below.

Reproduce steps
---

1. Build `openshift/ruby-20-centos7` by myself followed by [here](https://github.com/openshift/sti-ruby/tree/master/2.2)

    $ git clone https://github.com/openshift/sti-ruby.git
    $ cd sti-ruby
    $ make build VERSION=2.0

1. Run sti build

    $ sti build https://github.com/openshift/sti-ruby.git --context-dir=2.0/test/puma-test-app/ openshift/ruby-20-centos7 ruby-sample-app --loglevel=5

1. You will hit same error with my report.

**Comment by bparees** [comment]
repull openshift/base-centos7 and then rebuild your image and it will work.

**Comment by bparees** [comment]
@mfojtik fyi.  looks like @nak3 and i both had a bad base-centos7 image that wasn't doing scl enablement properly.  once i updated base-centos7 and rebuilt ruby-20-centos7 i can't reproduce anymore.

**Comment by mfojtik** [comment]
@bparees cool. fyi we have special labels that might help identify what base version you have:

`io.openshift.builder-base-version` is a Git ref from which the base image was built

**Comment by nak3** [comment]
@mfojtik I can't output `io.openshift.builder-base-version`. It can  output only

~~~
Builder Name:           Ruby 2.0
Builder Image:          openshift/ruby-20-centos7
Builder Image Version:  a085e45
Source:                 https://github.com/openshift/sti-ruby.git
Context Directory:      2.0/test/puma-test-app/
Output Image Tag:       ruby-sample-app
Incremental Build:      disabled
Remove Old Build:       disabled
Force Pull:             enabled
Quiet:                  disabled
Layered Build:          disabled
Docker Endpoint:        unix:///var/run/docker.sock
~~~
Full log : https://paste.fedoraproject.org/256576/

Although it is supposed to output here... : 
https://github.com/openshift/source-to-image/blob/31db1baa8eebfed87a3762a3c7ff1855201cc762/pkg/api/describe/describer.go#L88-L90

**Comment by bparees** [comment]
@nak3 can you go ahead and pull the new base-centos7 and rebuild?

also @mfojtik was asking you do docker inspect the image, that will show you the label he referred to, assuming your image is new enough to have been built with those labels.

**Comment by nak3** [comment]
@bparees
repull openshift/base-centos7 and rebuild image fixed this issue. Thanks.

The base image which caused this issue was : https://paste.fedoraproject.org/256579/
Updated images is : https://paste.fedoraproject.org/256588/

**Comment by bparees** [comment]
Great.
