### ISSUE TITLE
Build with docker-build strategy failed when Dockerfile doesn't contain EXPOSE

### ISSUE THREAD

**Issue by nak3** [openshift/origin#4186]
Env
---
$ openshift version
openshift v1.0.4-237-g30861f3
kubernetes v1.1.0-alpha.0-1155-gb73c53c

Reproduce steps
---
1. Prepare **same** directory in github to build from Dockerfile
 - Test-A is built without `--context-dir`
 - Test-B is built with `--context-dir`

test-A: https://github.com/nak3/dockerfile-buildtest
test-B: https://github.com/nak3/Dockerfiles/tree/master/quicktest

1. Build test-A

~~~
$ oc new-app https://github.com/nak3/dockerfile-buildtest.git -l app=test-A
~~~

1. Build test-B
~~~
$ oc new-app https://github.com/nak3/Dockerfiles.git --context-dir=quicktest -l app=test-B
~~~

Result
---

- Test-A build would be failed with raw stack trace. Please see the output:
https://paste.fedoraproject.org/255543/

- Test-B build works fine
https://paste.fedoraproject.org/255544/

**Comment by csrwng** [comment]
@nak3 can you reproduce this with a recent build of origin? I couldn't reproduce with a recent build:
```
$ openshift version
openshift v1.0.4-321-g9b6a18d
kubernetes v1.1.0-alpha.0-1605-g44c91b1
```

**Comment by nak3** [comment]
The recent build can reproduce it. Then, I found why you couldn't reproduce it.
Please pull `docker.io/scratch:latest` before the test. (I pulled it because of test-B.)

1. Pull docker.io/scratch:latest

    `# docker pull docker.io/scratch:latest`

1. You can reproduce this issue with

    `# oc --loglevel=10 new-app https://github.com/nak3/dockerfile-buildtest.git -l app=test-A`

I tested above and could reproduce it. By contrast, I couldn't after removing the docker image.

* Additional info 

Non-working log : https://paste.fedoraproject.org/256036/
Working log: https://paste.fedoraproject.org/256037/

**Comment by bparees** [comment]
I was able to recreate this by doing the docker pull that @nak3 suggested.  I can only assume it has to do with the introspection we attempt to do on the image.

**Comment by nak3** [comment]
The strange thing is that we can't hit this issue with `--context-dir` option (test-B above).

**Comment by nak3** [comment]
Sorry, my test has a mistake. [test-A](https://github.com/nak3/dockerfile-buildtest) and [test-B](https://github.com/nak3/Dockerfiles/tree/master/quicktest) are not exactly same directly. test-A's Dockerfile doesn't have `EXPOSE`.

So, the panic happend here. 
https://github.com/openshift/origin/blob/5b4c8ed9dadbd1adc4ae9758e38690a43d6214c0/pkg/generate/app/cmd/newapp.go#L508

I fixed in https://github.com/openshift/origin/pull/4471

**Comment by nak3** [comment]
@csrwng @bparees 
Please feel free to close this report.
