### ISSUE TITLE
oc status should have a "suggestions" flag

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4189]
When using `oc status`, there are failures that have common responses.  Things like "your build failed, would you like to look at logs with `oc build-logs builds/foo` or retry with `oc start-build bc/bar`?  Similar help can be provided for failed deployments, service accounts with missing secrets, a stub for emptyDir volumes, etc.  Sometimes that level of detail is annoying, but a flag to turn it on would be nice.

@smarterclayton @fabianofranz what do you think?

**Comment by smarterclayton** [comment]
Definitely a lot of value.  Probably need to break it into a card and
brainstorm some ideas and get some feedback.  I'd like to be able to
resolve SME questions so they stop asking them.

We also need to figure out how the UI does the same thing, to keep rough
parity (not exact parity.

On Aug 16, 2015, at 10:07 AM, David Eads <notifications@github.com> wrote:

When using oc status, there are failures that have common responses. Things
like "your build failed, would you like to look at logs with oc build-logs
builds/foo or retry with oc start-build bc/bar? Similar help can be
provided for failed deployments, service accounts with missing secrets, a
stub for emptyDir volumes, etc. Sometimes that level of detail is annoying,
but a flag to turn it on would be nice.

@smarterclayton <https://github.com/smarterclayton> @fabianofranz
<https://github.com/fabianofranz> what do you think?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4189>.

**Comment by deads2k** [comment]
@kargakis since you're taking a first pass here.  We can open another issue if we end up needing more (likely).
