### ISSUE TITLE
[REBASE] Fix RESTClient to be Kubernetes upstream compatible

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#419]
Right now, we use https://github.com/openshift/origin/blob/master/pkg/cmd/client/api/types.go#L8 as a RESTClient interface, however the Client changed in upstream https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/restclient.go#L36

We should call `client.Post()` instead of `client.Verb("POST")` etc... This affects Config and several other places in our code.

**Comment by smarterclayton** [comment]
Reopen if there is something still left to be done here.
