### ISSUE TITLE
typo in oc start-build help

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4190]
"--from-webhook='': Specify a webhook URL for an existing **BuildConfign** to trigger"

**Comment by bparees** [comment]
did you really need to open an issue instead of a PR for this?  trying to give us some low hanging fruit to fix? :)

**Comment by deads2k** [comment]
I try not to work on weekends.  I don't have a dev env set up at home.  I'm just trying to use this to build out a small server I need at home and it's proving to be frustratingly difficult to figure out what's happening.
