### ISSUE TITLE
main openshift readme doesn't mention --insecure-registry for docker

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4191]
I don't see instructions for enabling `--insecure-registry` in `/etc/sysconfig/docker` to allow default buildconfigs to push to the internal registry.

`INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16' ` gets the job done.

**Comment by bparees** [comment]
can be copied from here:
https://github.com/openshift/origin/tree/master/examples/sample-app#docker-changes
