### ISSUE TITLE
deployments should try to propogate common failures as events

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4192]
I had a deployment fail because a pod for my RC came active (personal problem), but `oc describe dc/name` did not show me the failure during to timeout.  

I have this in my deployment pod's log:
```
F0816 14:37:53.611254       1 deployer.go:64] update acceptor rejected plex/plex-docker-1: pods for deployment "plex/plex-docker-1" took longer than 600 seconds to become ready
```
but the describe of the dc only produces this:

```
[deads@main origin]$ oc describe dc/plex-docker
Name:		plex-docker
Created:	2 days ago
Labels:		app=plex-docker
Latest Version:	1
Triggers:	Config, Image(plex-docker@latest, auto=true)
Strategy:	Rolling
Template:
  Selector:	deploymentconfig=plex-docker
  Replicas:	1
  Containers:
  NAME		IMAGE														ENV
  plex-docker	172.30.201.81:5000/plex/plex-docker@sha256:1e533eb7cbcd93ec6c0f665219bb3cf0e2f49427bc236f6d61f518501efb46b0	
Deployment #1 (latest):
	Name:		plex-docker-1
	Created:	16 minutes ago
	Status:		Failed
	Replicas:	0 current / 0 desired
	Selector:	deployment=plex-docker-1,deploymentconfig=plex-docker
	Labels:		app=plex-docker,openshift.io/deployment-config.name=plex-docker
	Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Events:
  FirstSeen				LastSeen			Count	From		SubobjectPath	Reason		Message
  Sun, 16 Aug 2015 09:12:12 -0400	Sun, 16 Aug 2015 10:26:49 -0400	38	{deployer }			failedCreate	Couldn't create initial deployment: DeploymentConfig "plex-docker" is invalid: triggers[1].imageChange.tag: invalid value 'latest': no image recorded for plex/plex-docker:latest
```

This is annoying and inaccurate.  That was the cause of my first deployment failure, but not the second deployment failure.

**Comment by ironcladlou** [comment]
What output would you like to see? One hiccup is the error from the deployer didn't actually generate an event you can deal with- it's just log output which isn't available to `describe`. Should an event be generated instead? Are we then somehow able to correlate that event with the latest deployment (I'm not totally familiar with the capabilities of the event API)?

**Comment by kargakis** [comment]
Tracked in Trello: https://trello.com/c/OIggCmzo/699-5-deployments-downstream-conditions
