### ISSUE TITLE
pod on UI has a caution sign, but I have no idea why

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4195]
My pod has a caution sign on the UI, but I can't figure out why.  I suspect it's because the pod is constantly getting restarted, but hovering and clicking on it doesn't make the cause obvious.

![screenshot from 2015-08-16 12 01 20](https://cloud.githubusercontent.com/assets/8225098/9294038/9aa55766-440e-11e5-8585-8dc72b7e6d3d.png)

**Comment by deads2k** [comment]
@spadgett fyi

**Comment by spadgett** [comment]
Yeah, it's the restart count. We should find a place in the UI to say why, maybe a tooltip or a warning icon in the sidebar by the field. We're looking overview changes anyway.

@jwforres @liggitt fyi
