### ISSUE TITLE
oc edit of unserialized fields behaves like a true update

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4197]
When using `oc edit`, if I modify the file with a tag that doesn't exist for the object, the command completes as normal and claims that than update was made, but the value is silently ignored.

It is possible to detect the no-op by round-tripping try value and comparing against the original.  I might understand why `oc replace` would have this behavior, but `oc edit` is supposed to be userfriendly.

@smarterclayton Who's the maintainer for this command?

**Comment by smarterclayton** [comment]
On Aug 16, 2015, at 2:17 PM, David Eads <notifications@github.com> wrote:

When using oc edit, if I modify the file with a tag that doesn't exist for
the object, the command completes as normal and claims that than update was
made, but the value is silently ignored.

It is possible to detect the no-op by round-tripping try value and
comparing against the original. I might understand why oc replace would
have this behavior, but oc edit is supposed to be userfriendly.

@smarterclayton <https://github.com/smarterclayton> Who's the maintainer
for this command?



Me specifically or Fabiano generally.


—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4197>.

**Comment by danmcp** [comment]
Should move to card?
