### ISSUE TITLE
BuildConfig: I want to tag my image multiple ways

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4198]
When I run a build, I want to tag it as "latest", but I also want to tag with git commit id.  I've also seen other build systems where it's reasonable to tag the image with a datetime.

@bparees Is there way to express this?  I didn't see anything in https://github.com/openshift/origin/blob/master/pkg/build/api/types.go#L302

**Comment by bparees** [comment]
There's currently no way to specify multiple output images/tags, let alone
name the tag based on the commit id. However all built images now (or soon
will) include labels with information about the commit they were built
from.

Ben Parees | OpenShift

**Comment by deads2k** [comment]
That doesn't have quite the same power.  Having the docker tag allows me to do things like `docker pull image:gitcommit` and it allows more natural usage with `kubectl run` without having to first a lookup by label selector.

**Comment by bparees** [comment]
i wasn't claiming it did.

**Comment by smarterclayton** [comment]
Would want to verify pushing multiple tags was fast / not inefficient.

**Comment by bparees** [comment]
assuming they are all going to the same registry/repository, it should be pretty fast.

**Comment by bparees** [comment]
trello'd https://trello.com/c/nOX8FTRq/686-support-multiple-tags-for-a-build-output

**Comment by YannMoisan** [comment]
In the meantime, my workaround is to run this command manually :

```
oc tag n/abc:latest n/abc:`oc get istag abc:latest -o json | jq -r ".image.dockerImageMetadata.Config.Labels.\"io.openshift.build.commit.id\""`
```

**Comment by smarterclayton** [comment]
We've discussed a couple of ways to implement this - id prefer for it to be in the image stream able to extract metadata from incoming images and give them dynamic tags.  I think that would be the easiest way to integrate many workflows, not just the build part.

**Comment by bparees** [comment]
>  id prefer for it to be in the image stream able to extract metadata from incoming images and give them dynamic tags. 

that would require builds to be able to set LABELs on the images they produce, though, right?  (I assume you'd be using docker LABEL for the metadata)

**Comment by smarterclayton** [comment]
Yes - but I think we want to do that anyway.

**Comment by YannMoisan** [comment]
I've created a custom builder to do that : 
- https://github.com/YannMoisan/openshift-tagger-custom-builder
- https://hub.docker.com/r/yamo/openshift-tagger-custom-builder/

**Comment by bparees** [comment]
@YannMoisan very cool.

**Comment by kevinkjt2000** [comment]
Has the Trello board disappeared?

https://trello.com/c/nOX8FTRq/686-support-multiple-tags-for-a-build-output is showing 
<img width="875" alt="image" src="https://user-images.githubusercontent.com/4098674/125521908-30009d8e-332d-4967-b6b5-a41a5f0606d8.png">

**Comment by bparees** [comment]
yes, the team migrated to jira quite a while ago.  For a while the boards were left around w/ refs to the migrated jira tickets, but i guess even that was cleaned up at some point.

as far as i know there's been no further prioritization of this feature request (likely it isn't being tracked as an RFE in jira any more at this point).

i believe this is the team's jira board now:
https://issues.redhat.com/projects/BUILD/issues/BUILD-254?filter=allopenissues

**Comment by kevinkjt2000** [comment]
Thanks!

I found https://issues.redhat.com/browse/BUILD-248 tracking dynamic tags based on policies such as 6 digits of a git-sha. This might eventually work out to supporting what I wanted to do with some human-readable semantic tags, so it seems promising. I wanted to tag version `:1.2.3` with the additional tags of `:1` and `:1.2` as is a pretty common practice in the docker hub community (e.g. `python:3.9.6`, `python:3.9`, `python:3`)

Meanwhile, in the absence of direct support for multiple build outputs, it looks like I'll be doing a custom builder similar to what [YannMoisan proposed](https://github.com/openshift/origin/issues/4198#issuecomment-182444466)
