### ISSUE TITLE
oc keeps drifting from kubectl

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4200]
`oc` is supposed to mirror `kubectl`, but it keeps drifting out.  In particular, I wanted `kubectl run`.  We need a unit test that builds the command tree and makes sure that we're a strict superset.

@fabianofranz

**Comment by fabianofranz** [comment]
We could run the `kubectl` tests as `oc`, if they allow such parametrization. I'll check.

**Comment by deads2k** [comment]
@fabianofranz I've got a pull fixing this
