### ISSUE TITLE
logs for pod in current deployment

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4201]
I used `oc new-app` to create an application.  By default that made `deploymentconfig` that specifies a `replicationcontroller` with 1 replica.  As I'm diagnosing my application (cycling update, push, rebuild, redeploy), it's annoying that I have to look up the correct pod each time.  Given that this our default for `new-app`, I think there's value in having a flag for deployment logs that will take a dc, if that that dc has one active deployment with replica size 1, locate the pod, open the logs for the requested container.

@kargakis this would be a follow on if neither @ironcladlou nor @smarterclayton object.

**Comment by smarterclayton** [comment]
Yes, deployment logs should accept DC (anything that has the word deploy in
it should support a DC, and the same for build and BC)

On Aug 16, 2015, at 4:23 PM, David Eads <notifications@github.com> wrote:

I used oc new-app to create an application. By default that made
deploymentconfig that specifies a replicationcontroller with 1 replica. As
I'm diagnosing my application (cycling update, push, rebuild, redeploy),
it's annoying that I have to look up the correct pod each time. Given that
this our default for new-app, I think there's value in having a flag for
deployment logs that will take a dc, if that that dc has one active
deployment with replica size 1, locate the pod, open the logs for the
requested container.

@kargakis <https://github.com/kargakis> this would be a follow on if
neither @ironcladlou <https://github.com/ironcladlou> nor @smarterclayton
<https://github.com/smarterclayton> object.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4201>.

**Comment by deads2k** [comment]
> Yes, deployment logs should accept DC (anything that has the word deploy in
> it should support a DC, and the same for build and BC)

I'm asking for something a little stranger.  Think `oc deploy logs dc/my-dc --pod`.  Given a structure of dc has one active rc (deployment), rc has one active pod, pod has one active container I want to have the container logs.  That would interoperate really well with the defaults used by new-app and allow someone to quickly cycle on push, build, deploy, borked, logs.

**Comment by ironcladlou** [comment]
I like the idea of simplifying the targetting of the container for log access, but the tool is rendered ineffective once the replica count becomes >1 (which very soon or always for all nontrivial apps). Does that make the idea too special-purpose?

**Comment by liggitt** [comment]
Other things defaults to using the first found item (like oc exec using the first container if none is specified). Would that work?

**Comment by deads2k** [comment]
> Other things defaults to using the first found item (like oc exec using the first container if none is specified). Would that work?

Choosing the first item found would satisfy me.

**Comment by smarterclayton** [comment]
I don't really like using first found pod.  There are probably other ways
to solve this.

On Mon, Aug 17, 2015 at 9:44 AM, David Eads <notifications@github.com>
wrote:

> Other things defaults to using the first found item (like oc exec using
> the first container if none is specified). Would that work?
>
> Choosing the first item found would satisfy me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4201#issuecomment-131821350>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
> There are probably other ways
> to solve this.

I bet I could solve this using bash!


or you know, go curl up crying in a fetal position on the floor.

**Comment by smarterclayton** [comment]
The reason I don't like using first found pod is because all other places
we use first found anything, there is a way to get the extra thing.  This
would be the first place where you can't get anything.  I don't disagree
this is useful.  I'm a little worried about the predictability / behavior.

On Mon, Aug 17, 2015 at 10:24 AM, David Eads <notifications@github.com>
wrote:

> There are probably other ways
> to solve this.
>
> I bet I could solve this using bash!
>
> or you know, go curl up crying in a fetal position on the floor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4201#issuecomment-131838240>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
> The reason I don't like using first found pod is because all other places
> we use first found anything, there is a way to get the extra thing.  This
> would be the first place where you can't get anything.  I don't disagree
> this is useful.  I'm a little worried about the predictability / behavior.

Could we agree to build out this functionality and fail if we can't match exactly with the possibility of being more tolerant in the future?  This was a serious pain point.

**Comment by smarterclayton** [comment]
Open an issue for it and let's take the discussion there.

On Mon, Aug 17, 2015 at 10:40 AM, David Eads <notifications@github.com>
wrote:

> The reason I don't like using first found pod is because all other places
> we use first found anything, there is a way to get the extra thing. This
> would be the first place where you can't get anything. I don't disagree
> this is useful. I'm a little worried about the predictability / behavior.
>
> Could we agree to build out this functionality and fail if we can't match
> exactly with the possibility of being more tolerant in the future? This was
> a serious pain point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4201#issuecomment-131844777>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
> Open an issue for it and let's take the discussion there.

Um, isn't this the issue?

**Comment by smarterclayton** [comment]
Oh, this got lumped in to the other thread for some reason.   I don't think failing is going to make users feel better - it would be better to just pick a random pod every time to show logs for and tell the user what pod they're seeing.

**Comment by smarterclayton** [comment]
I take back random, it should be the oldest pod (the most likely to trigger
a canary failure).

On Aug 17, 2015, at 10:58 AM, David Eads <notifications@github.com> wrote:

Open an issue for it and let's take the discussion there.

Um, isn't this the issue?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4201#issuecomment-131853526>.

**Comment by kargakis** [comment]
@danmcp assign this to me

**Comment by kargakis** [comment]
> I take back random, it should be the oldest pod (the most likely to trigger a canary failure).

@smarterclayton does it make sense  for `kubectl logs rc/` to support this?

**Comment by smarterclayton** [comment]
At some point we're going to have to deal with multiple pods.  However, if we implement that now, it means we can't handle it later.

**Comment by deads2k** [comment]
> At some point we're going to have to deal with multiple pods. However, if we implement that now, it means we can't handle it later.

`kubectl logs rc/foo` is unambiguous if there is only one pod owned by the RC.  That is commonly the case in development.  I'd like to special case the "rc has one pod" case and error in the other cases.  That would keep the door open for interleaving multiple logs (which is crazy btw).
