### ISSUE TITLE
oc volume should be multiple subcommands

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4202]
When I come into `oc volume` I know what I want to do (add/remove/list), but when I get help I get this massive blob on the page of all three, plus multiple sets of mutually exclusive options and illegal combinations.  I even know roughly what command I need to run and I still get bit by things like `error: --type|--path|--secret-name|--claim-name|--source|--overwrite are only valid for --add operation`

@smarterclayton let us split it?  Please?  Anyone who gets there knows whether they want to add, remove, or list.

**Comment by deads2k** [comment]
@fabianofranz you brought this up the CLI meeting.  You want this one?

**Comment by fabianofranz** [comment]
@deads2k yes, assign to me.

**Comment by kargakis** [comment]
Should be covered by `set`, and the still TBD `unset`, and `view` commands. There are upstream issues for tracking both.
