### ISSUE TITLE
`oc new-app` error message when template has invalid JSON

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#4206]
Trying to use `oc new-app` with an existing template (file exists and can be read) that contains invalid JSON (parsing fails) returns an error message that doesn't help figuring out you have a problem in your template:

```
$ cat > bad-template.json <<EOF                                                         
{
"there should not be a trailing comma": "here",
}
EOF
$ oc new-app bad-template.json
error: no image or template matched "bad-template.json"
```

This pops up some times when editing an existing template and make small mistakes.

**Comment by rhcarvalho** [comment]
I would expect to see a message about error parsing template / invalid JSON.

**Comment by smarterclayton** [comment]
I *think* this is dependent on an upstream issue where errors are being swallowed on parsing failure in resource.Builder.  But someone needs to check.
