### ISSUE TITLE
oc start-build bc/bc-name --commit=hash

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4208]
Yesterday, I really wanted to be able to build a particular commit in master.  I didn't see a flag in `oc start-build`.

@bparees is there a way to do this?

**Comment by mfojtik** [comment]
not without telling buildController to override the ref of the BC when generating a build afaik.

**Comment by mfojtik** [comment]
but +1 to make this work... sound pretty usefull

**Comment by mfojtik** [comment]
@deads2k alternative would be to teach start-build to:

* Fetch the BuildConfig
* Allow to modify the `Source` fields
* Submit a build directly

**Comment by deads2k** [comment]
While I'm wishing, it'd be nice to able to specify a "one-off tag" and a pony.

**Comment by jhadvig** [comment]
+1 for doing this.. and for the pony

**Comment by deads2k** [comment]
Fixed.
