### ISSUE TITLE
Deployments should have status timestamps

### ISSUE THREAD

**Issue by fabianofranz** [openshift/origin#4212]
Builds have timestamps attached to `status` for the start and completion (`status.startTimestamp` and `status.completionTimestamp`), along with the creation timestamp in metadata `metadata.creationTimestamp`. This allows to know exactly a build started and finished to run, and to calculate the exact duration it took. Deployments should have them too, and have these displayed in both `oc describe` and the web console.

**Comment by ironcladlou** [comment]
There was some discussion of this wayyyy back in #252. Should the start time be when the deployment transitions to `running` and the end time when it reaches a terminal phase? What if it goes right from `new` or `pending` to a terminal phase? Would there be a start time in that case?

**Comment by fabianofranz** [comment]
`Builds` also have `New`, `Pending` and `Running`. So I'd say the same rules should apply.

**Comment by ironcladlou** [comment]
@fabianofranz please close this in favor of https://trello.com/c/IfUBcN3I

**Comment by fabianofranz** [comment]
Ok, thanks @ironcladlou.
