### ISSUE TITLE
Router default backend

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#4215]
Currently, if no lookups are found for a route we fall through to 127.0.0.1:8080.  Since nothing is running there that call can hang for a bit before returning.  We need to test if this is indeed causing slowness in returning routes that are not found and consider having something there (or elsewhere) to respond quickly.  Or, see if we can just fall through to nothing so the lookup fails and returns more quickly.

To test: curl a route on a router that has no services

@ramr

**Comment by liggitt** [comment]
Someone who was actually serving something on 127.0.0.1:8080 would find it disconcerting for that thing to be served by the router as a fall through. I would vote for falling through to nothing, unless there are implications I'm missing

**Comment by smarterclayton** [comment]
We should fall through to a parking page like we had in v2.  Something suitable - "No application exists"

**Comment by ramr** [comment]
Hmm, think  apache just gave a 503 (service unavailable) in v2 - may be wrong. 

So, there's a couple of options here:  
1.  The simplest would be to remove that server ```127.0.0.1:8080``` from the ```openshift_default``` backend and haproxy will return a similar 503 error (```no server available to handle this request```). 
2.  If we want a custom message we need to either have  a backend service to return that message (haproxy doesn't really serve static files) or :cringe: I guess we could probably use an ```errorfile 200 /path/to/page``` in the fall through case - really abusing what errorfile is meant for ... 

I'd just go with the first case of removing that backend and letting haproxy return an error - no server for this request.

**Comment by ramr** [comment]
fyi @pweil- some info on the timings is in the PR - its a lot slower if there's nothing serving on port 8080 as opposed to just falling through and letting haproxy return a 503. Also added some comments/text in the config on how to add custom messages (custom backend or a 503 page).

**Comment by smarterclayton** [comment]
503 is a good place right now.  We also need to be able to add a custom
503, but if that was something a customer layered on top (i.e. let's create
one and put it in the image, and they can layer on top and change the file
if they want).

On Thu, Aug 20, 2015 at 2:35 PM, Ram Ranganathan <notifications@github.com>
wrote:

> fyi @pweil- <https://github.com/pweil-> some info on the timings is in
> the PR - its a lot slower if there's nothing serving on port 8080 as
> opposed to just falling through and letting haproxy return a 503. Also
> added some comments/text in the config on how to add custom messages
> (custom backend or a 503 page).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4215#issuecomment-133111354>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by pweil-** [comment]
> its a lot slower if there's nothing serving on port 8080

this is what I suspected was causing the slowness.  Thanks Ram

**Comment by ramr** [comment]
@pweil-  this has been fixed with the default backend and the default 503 page PRs. Can you please close this out.  Thx
