### ISSUE TITLE
Extended Test Script Difficult to Use

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4222]
I have encountered the following issues:
- When the script exits, it does not always kill the running OpenShift instance. This furthermore makes subsequent runs fail because they can't ping `healthz`. That's frustrating because:
- When the cluster can't be started, there's no good error message and seeing the `healthz` failure gives me no information
- When the cluster fails at a point between initial startup and mid-test, no error message is printed whatsoever.
- The `wait_for_command` on `oc get endpoints docker-registry` command doesn't always finish, even if the registry is up, running, and healthy

**Comment by deads2k** [comment]
> When the script exits, it does not always kill the running OpenShift instance.

Fixed in #4072 .

**Comment by stevekuznetsov** [comment]
Launcher has changed significantly, closing this.
