### ISSUE TITLE
Certificates are not bound to the master's IP address when creating configurations 

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#4225]
version: 1.0.4

When creating the configuration, the certificate files are not created using the masters IP address. 

What is happening here is that it is picking the IP address from one of the system network interfaces. If this IP address changes, then OpenShift will not be able to start and it doesn't really tell the user what the problem is (see https://gist.github.com/mwringe/5fd70dc86fb6027e84f9)

Steps to reproduce:
```
openshift start --write-config=openshift.local.config --hostname=$IP_ADDRESS --public-master=$IP_ADDRESS --master=$IP_ADDRESS
```

Open the created master.server.cert and see that its CN does not match the master's IP address that was specified.

If using a laptop, a good way to test this would probably be to set the IP_ADDRESS to that off the wifi network, disconnect from wifi and run the write-config option while connect via wired connection and then switch back to wifi only.

**Comment by liggitt** [comment]
Looks correct to me:
```
$ IP_ADDRESS=1.2.3.4

$ openshift start --write-config=openshift.local.config --hostname=$IP_ADDRESS --public-master=$IP_ADDRESS --master=$IP_ADDRESS

$ openssl x509 -in openshift.local.config/master/master.server.crt -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 12 (0xc)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=openshift-signer@1439783895
        Validity
            Not Before: Aug 18 04:23:32 2015 GMT
            Not After : Aug 17 04:23:33 2016 GMT
        Subject: CN=1.2.3.4
        ...
        X509v3 extensions:
            ...
            X509v3 Subject Alternative Name: 
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:localhost, DNS:openshift, DNS:openshift.default, DNS:openshift.default.svc, DNS:openshift.default.svc.cluster.local, DNS:1.2.3.4, DNS:10.3.112.21, DNS:127.0.0.1, DNS:172.17.42.1, DNS:192.168.1.114, DNS:192.168.122.1, IP Address:1.2.3.4, IP Address:10.3.112.21, IP Address:127.0.0.1, IP Address:172.17.42.1, IP Address:192.168.1.114, IP Address:192.168.122.1
```

The specified IP should at least be in the subjectAltNames

**Comment by mwringe** [comment]
Strange, it works with '1.2.3.4' but not when I use an actual network interface.  


>$ export IP_ADDRESS=**192.168.122.1**
$ openshift start --write-config=openshift.local.config --hostname=$IP_ADDRESS --public-master=$IP_ADDRESS --master=$IP_ADDRESS
$ openssl x509 -in openshift.local.config/master/master.server.crt -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 4 (0x4)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=openshift-signer@1439903241
        Validity
            Not Before: Aug 18 13:07:23 2015 GMT
            Not After : Aug 17 13:07:24 2016 GMT
        Subject: CN=**10.192.209.35**
        Subject Public Key Info:
        ...

**Comment by liggitt** [comment]
They might get sorted, check all the subjectAltNames

**Comment by liggitt** [comment]
Yeah, the specified IP is in the subject alt names:
```
$ export IP_ADDRESS=192.168.122.1
$ openshift start --write-config=openshift.local.config --hostname=$IP_ADDRESS --public-master=$IP_ADDRESS --master=$IP_ADDRESS
$ openssl x509 -in openshift.local.config/master/master.server.crt -noout -text
Certificate:
    Signature Algorithm: sha256WithRSAEncryption
        X509v3 extensions:
            X509v3 Subject Alternative Name: 
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:localhost, DNS:openshift, DNS:openshift.default, DNS:openshift.default.svc, DNS:openshift.default.svc.cluster.local, DNS:10.13.129.70, DNS:127.0.0.1, DNS:172.17.42.1, DNS:192.168.122.1, IP Address:10.13.129.70, IP Address:127.0.0.1, IP Address:172.17.42.1, IP Address:192.168.122.1
```

**Comment by danmcp** [comment]
Please reopen if there is still an issue here.

**Comment by mwringe** [comment]
There is still an issue, but this might not be the main cause. You cannot restart OpenShift if the network interface changes. After discussions on irc it looked like this might have been the case, but now I am not sure.
