### ISSUE TITLE
Inconsistencies in command names and its subcommands trees

### ISSUE THREAD

**Issue by fabianofranz** [openshift/origin#4226]
From discussions in the CLI Design meetings. 

We need to address some inconsistencies in 
* command names - some use nouns in singular and others in plural
* subcommands or flags for sub-actions of grouping commands (e.g. `noun list`, `noun --list`, or even `nouns`).

Examples of current inconsistencies
* `oc secrets new|add|...` (grouping command, *plural* but handle one secret at a time)
* `oc volume --add|--list|...` (relies on flags not grouping, singular)
* `oc label` (not grouping, *singular* but can take multiple labels in one command call. it's also a verb)
* `oadm groups new|add-users|...` (grouping command, *plural* but manage one group at a time)
* `oadm policy add-role-to-user|remove-user|...` (grouping command, singular)

Sometimes nouns are also verbs (label, group, etc).

**We don't necessarily need to come up with one strategy to rule them all, but some more consistency should be good.** We learned from `rhc` that having too many aliases lead to a lot of confusion, but one of the better accepted proposals would be:
* all nouns in plural by default (in help)
* but also accepting singular
* that's how resource names work (e.g. `oc get pod` and `oc get pods`)
* e.g. `oc secret` and `oc secret`

Also related: https://trello.com/c/Jo4V19Bf/633-unify-build-commands-with-deployments

**Comment by fabianofranz** [comment]
FYI @smarterclayton @bparees @jwforres 
Please tag @liggitt

**Comment by fabianofranz** [comment]
also @deads2k

**Comment by smarterclayton** [comment]
Does the plural in commands help?  It's just one more letter to type every time.  Does it improve comprehension?

**Comment by smarterclayton** [comment]
Policy is inherently plural.  Label is a verb, not a noun.  I'm not opposed to the proposal as long as perfect back compat is maintained

**Comment by bparees** [comment]
all singular: bad because in some cases the intuitive assumption will be plural
all plural: bad because in some cases the intuitive assumption will be plural
some singular, some plural:  bad because now i have to remember which is which.

that's how we arrived at "always support both forms"

i don't have a strong opinion about which form the help shows, ie which is the "canonical" form, but we should tolerate both.

**Comment by deads2k** [comment]
I'm fine with showing plural by default and accepting both.  I actually do tend to type plural for the nouns, but I couldn't say for sure that I haven't been trained by resources.

**Comment by smarterclayton** [comment]
I dislike the extra character in the plural for brevity and fitting our
commands into the space we have on the screen.  It's marginally more
discoverable.  It's marginally less clear for singular actions (oc secret
add).  We will probably always have a few singular nouns in the command set
- 'openshift start master' isn't going to be 'openshift start masters'.
Lists under nouns (volume, secret) will probably be special types of
listing (intended to aid in the actions under the command), not the more
generic "get foos".

Other pros/cons?

On Tue, Aug 18, 2015 at 8:34 AM, David Eads <notifications@github.com>
wrote:

> I'm fine with showing plural by default and accepting both. I actually do
> tend to type plural for the nouns, but I couldn't say for sure that I
> haven't been trained by resources.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4226#issuecomment-132193586>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment]
As a data point, resources accept both singular and plural

**Comment by bparees** [comment]
> I dislike the extra character in the plural for brevity and fitting our commands into the space we have on the screen. It's marginally more discoverable. 

are you arguing against tolerating plural, or against showing it in the help?

**Comment by smarterclayton** [comment]
Just making arguments both ways.  We say plural is more useful, for
discovery, but if both ways work for discovery and we support both
discoverability isn't useful (because you'll use whatever you see in help,
and like it)

On Tue, Aug 18, 2015 at 10:12 AM, Ben Parees <notifications@github.com>
wrote:

> I dislike the extra character in the plural for brevity and fitting our
> commands into the space we have on the screen. It's marginally more
> discoverable.
>
> are you arguing against tolerating plural, or against showing it in the
> help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4226#issuecomment-132223362>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
> (because you'll use whatever you see in help, and like it)

no I won't, because i'll forget if the help said "build" or "builds" and i'll try one and get it wrong.

i'm not making a discoverability argument, i'm making a memorization tax argument.

**Comment by smarterclayton** [comment]
>  We say plural is more useful, for discovery, but if both ways work for
discovery and we support both discoverability isn't useful (because you'll
use whatever you see in help, and like it)

"if ... we support both"

On Tue, Aug 18, 2015 at 11:41 AM, Ben Parees <notifications@github.com>
wrote:

> (because you'll use whatever you see in help, and like it)
>
> no I won't, because i'll forget if the help said "build" or "builds" and
> i'll try one and get it wrong.
>
> i'm not making a discoverability argument, i'm making a memorization tax
> argument.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4226#issuecomment-132253912>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by fabianofranz** [comment]
If we decide to tolerate both, then the argument for what we show in help can be cohesion/fluency, decided for each case individually. E.g.: `secret` and `group` because you manage once at a time, `labels` because multiple at a time or `label` if we see it more like a verb, etc.

**Comment by smarterclayton** [comment]
Label is a verb, not a noun.  Like annotate.  Verbs are vastly preferred,
but alas we cannot verb everything and still explain to users how to
accomplish things.  Which is why we have groups of commands (secrets,
volumes, policy).  We should probably describe and link that somewhere.

On Aug 18, 2015, at 2:14 PM, Fabiano Franz <notifications@github.com> wrote:

If we decide to tolerate both, then the argument for what we show in help
can be cohesion/fluency, decided for each case individually. E.g.: secret
and group because you manage once at a time, labels because multiple at a
time or label if we see it more like a verb, etc.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4226#issuecomment-132304828>.

**Comment by fabianofranz** [comment]
I did some hacking with Cobra + Levenshtein distance inspired by how `git` works and I came up with this. The nice thing about it is that, unlike aliases, it forces users to learn/use the correct commands, *and* helps with typos.

```
$ oc volumes
Error: unknown command "volumes" for "oc"

Did you mean this?
	volume

Run 'oc --help' for usage.
```

```
$ oc labels
Error: unknown command "labels" for "oc"

Did you mean this?
	label

Run 'oc --help' for usage.
```

```
$ oc creaet
Error: unknown command "creaet" for "oc"

Did you mean this?
	create

Run 'oc --help' for usage.
```

```
$ oc teg
Error: unknown command "teg" for "oc"

Did you mean this?
	tag
	get

Run 'oc --help' for usage.
```

Worth adding?

**Comment by bparees** [comment]
honesty the git "did you mean" always annoys me.  i always think "of course i did, i know it, you know it, why didn't you just run it correctly then?"

but that might be just me :)

**Comment by fabianofranz** [comment]
Well I like it, but probably only in `oc`, not in `openshift`. :)

**Comment by liggitt** [comment]
I like it. I'd still like to accept both singular and plural forms of some commands

**Comment by fabianofranz** [comment]
@liggitt np, if we decide to add aliases, they still have higher priority over suggestions.

**Comment by smarterclayton** [comment]
I like it

On Fri, Sep 11, 2015 at 3:57 PM, Fabiano Franz <notifications@github.com>
wrote:

> @liggitt <https://github.com/liggitt> np, if we decide to add aliases,
> they still have higher priority over suggestions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4226#issuecomment-139647349>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by fabianofranz** [comment]
The introduction of suggestions improved this a lot, but I'm still proposing a few aliases in https://github.com/openshift/origin/pull/5670. 

```
volume/volumes
config/configs
project/projects
secret/secrets
```

Note that since the last discussions here, `log/logs` were introduced upstream with an alias, with the plural form being the default in help.
