### ISSUE TITLE
openshift.spec file doesn't pick up change in static assets

### ISSUE THREAD

**Issue by xuant** [openshift/origin#4227]
I am trying to customize the static assets and make the corresponding RPM package.

What I did:
```
1. Modify `assets/app/index.html`

2. Build the assets

$ hack/install-assets.sh
$ hack/build-assets.sh
$ hack/build-go.sh

3. Build the RPM using `tito`:

$ tito build --test --rpm
```

The changes to the assets reflected upon the binary created in Step 2 but not upon the packages created in Step 3.

@detiber

**Comment by liggitt** [comment]
after the `hack/build-assets.sh` step, did you see a changed `bindata.go` file?
did you commit the changes to `index.html` and `bindata.go`? @detiber, do local changes need to be committed to be picked up in the build?

**Comment by xuant** [comment]
@liggitt Just tested it. After the `hack/build-assets.sh`, there are changes in `bindata.go` file and I do need to commit the change for it to be picked up in the build. Thanks!
