### ISSUE TITLE
Environment variables passed to the new-app should available in non-generated deploymentConfigs

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#4233]
When I create a new application via `new-app` cmd and pass a env var that I wanna to take place in launched containers, they will be available only in containers that were created by deploymentConfig which was generated via the `new-app` command, not those which are created from the template.

**Comment by jhadvig** [comment]
@csrwng fyi

**Comment by bparees** [comment]
per scrum discussion my vote would be to not do this.  templates have a mechanism for overriding parameters, but if you want new env variables you should create your own template or make parameters to represent them.

ok to close?

**Comment by jhadvig** [comment]
@bparees sounds good. Closing
