### ISSUE TITLE
Service account setup doesn't retry on race

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4234]
```
E0818 09:55:11.609058   54516 ensure.go:147] Error recording adding service account roles to default namespace: namespaces "default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
```

This means servers can start up and not initialize their service accounts.

**Comment by deads2k** [comment]
You want this fixed via a controller or multiple retries in ensure?

**Comment by liggitt** [comment]
That's just recording the fact that the setup happened. It'll retry recording on next startup.

**Comment by deads2k** [comment]
> That's just recording the fact that the setup happened. It'll retry recording on next startup.

True, but the risk remains for the `AddRole` immediately above right?

**Comment by liggitt** [comment]
Sure, still needs fixing, but I wouldn't call it p1

**Comment by smarterclayton** [comment]
Probably multiple retries and fail if you can't continue.  That's what the
masters do.  If initialization is required, we shouldn't be able to go past
initialization.  Hence why it got the P1 (it means you could start a
cluster and it wouldn't work, just because of race).

On Tue, Aug 18, 2015 at 10:24 AM, Jordan Liggitt <notifications@github.com>
wrote:

> Sure, still needs fixing, but I wouldn't call it p1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4234#issuecomment-132229061>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Still happening

```
E0106 23:08:03.012504   12835 ensure.go:150] Error recording adding service account roles to "default" namespace: namespaces "default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
E0106 23:08:03.929348   12835 ensure.go:150] Error recording adding service account roles to "openshift-infra" namespace: namespaces "openshift-infra" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
E0106 23:08:04.103790   12835 ensure.go:150] Error recording adding service account roles to "openshift" namespace: namespaces "openshift" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
```
