### ISSUE TITLE
Long env vars display poorly in UI details sidebar

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4238]
See screenshot. This is at ~850px wide.

<img width="216" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/9333641/cee4460a-4598-11e5-8662-a27fee52b1cd.png">

Similar to #2572

/cc @jwforres

**Comment by smarterclayton** [comment]
Has this been addressed?

**Comment by jwforres** [comment]
no, we haven't put much effort into bugs in the sidebar because we are seriously leaning towards dropping it in the new overview layout

**Comment by spadgett** [comment]
Closing as we've removed the sidebar.
