### ISSUE TITLE
Normalize the use of registry image naming and syntax

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin#424]
Normalize the use of how we specify registries and what their tags are.  In DeploymentConfig triggers we use:

```
"respositoryName" : "172.121.17.1:5001/mypath/tomyimage",
"tag" : "latest"
```
but in BuildConfig we do something like:

```
        "output" : { 
            "imageTag": "jcantrill/j2ee-wildfly-jee-sample",
            "registry": "172.121.17.1:5001"
        }  
```
or even
```
            "stiStrategy" : { 
                "builderImage": "openshift/wildfly-8-centos",
                "clean" : false
            }

```
We should have some consistency where when specifying a registry it is always part of the image uri, always separate, but is consistent across types

**Comment by danmcp** [comment]
Closing due to age without prejudice.

**Comment by smarterclayton** [comment]
This is fixed
