### ISSUE TITLE
Flake in travis on upstream test TestForwardPorts

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4240]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/portforward/portforward_test.go#L290

**Comment by liggitt** [comment]
https://travis-ci.org/openshift/origin/jobs/76951004#L369

**Comment by liggitt** [comment]
Pretty easily reproducible with 
```
watch GOMAXPROCS=4 TESTFLAGS=-p=4 hack/test-go.sh Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/portforward/
```

**Comment by soltysh** [comment]
Another one here: https://travis-ci.org/openshift/origin/jobs/76966294#L357
