### ISSUE TITLE
Flake in travis on upstream test TestMaxInFlight

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4242]
https://travis-ci.org/openshift/origin/jobs/74904847#L1444

**Comment by liggitt** [comment]
https://travis-ci.org/openshift/origin/jobs/76145782#L1444

**Comment by liggitt** [comment]
resolved by race fixes upstream, closing since I haven't seen it since we rebased on that

**Comment by liggitt** [comment]
https://travis-ci.org/openshift/origin/jobs/84629541#L333

**Comment by deads2k** [comment]
The link is bad, can you update it?  I pulled https://github.com/openshift/origin/pull/4881 that claimed to fix it....

**Comment by liggitt** [comment]
bah, rerunning a job in travis wipes the old results.

**Comment by deads2k** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3576/consoleText

**Comment by smarterclayton** [comment]
Are we still seeing this?

**Comment by liggitt** [comment]
I haven't seen it, closing, can reopen if needed
