### ISSUE TITLE
Flake in TestWebhookGitHubPushWithImageStream test

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4245]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/4235/console
Either a race in the test or in the actual API
```
--- FAIL: TestWebhookGitHubPushWithImageStream-2 (6.82s)
	webhookgithub_test.go:278: Wrong response code, expecting 200, got %!s(int=500): {
		  "kind": "Status",
		  "apiVersion": "v1",
		  "metadata": {},
		  "status": "Failure",
		  "message": "Internal error occurred: could not generate a build: buildconfig \"pushbuild\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again",
		  "reason": "InternalError",
		  "details": {
		    "causes": [
		      {
		        "message": "could not generate a build: buildconfig \"pushbuild\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again"
		      }
		    ]
		  },
		  "code": 500
		}!
FAIL
```

**Comment by stevekuznetsov** [comment]
@liggitt  or @bparees can you throw a flake tag on this? Couldn't find it when I made my dupe.

**Comment by liggitt** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3081/console

**Comment by bparees** [comment]
@csrwng looks like both the imagechangecontroller and configchangecontroller fired at the same time for this build:

I0824 18:45:16.778985   14154 image_change_controller.go:47] Build image change controller detected ImageStream change registry:3000/integration/imageStream
I0824 18:45:16.779015   14154 image_change_controller.go:106] Found ImageStream integration/image-stream with tag validTag
I0824 18:45:16.779030   14154 image_change_controller.go:122] Running build for BuildConfig integration/pushbuild
I0824 18:45:16.780579   14154 github.go:43] Checking if the provided secret for BuildConfig integration/pushbuild matches
I0824 18:45:16.780606   14154 github.go:48] Verifying build request for BuildConfig integration/pushbuild
I0824 18:45:16.890746   14154 generator.go:167] Generating Build from BuildConfig: integration/pushbuild, TriggeredBy: DockerImage/registry:3000/integration/imageStream:success with stream: ImageStreamTag/image-stream:validTag


I0824 18:45:17.181961   14154 config_controller.go:20] Handling BuildConfig integration/pushbuild
I0824 18:45:17.182361   14154 generator.go:441] Resolving ImageStreamReference namespace/builtimage of Kind DockerImage in namespace integration
I0824 18:45:17.182527   14154 generator.go:502] No secrets found for pushing or pulling the DockerImage  integration/namespace/builtimage
I0824 18:45:17.182547   14154 generator.go:441] Resolving ImageStreamReference registry:3000/integration/imageStream:success of Kind DockerImage in namespace integration
I0824 18:45:17.182660   14154 generator.go:502] No secrets found for pushing or pulling the DockerImage  integration/registry:3000/integration/imageStream:success
I0824 18:45:17.182677   14154 generator.go:185] Build /pushbuild-1 has been generated from integration/pushbuild BuildConfig
I0824 18:45:17.183197   14154 generator.go:189] Failed to update BuildConfig integration/pushbuild so no Build will be created

**Comment by bparees** [comment]
(which I believe we decided was to be expected but we probably need to fix this test case to disable ConfigChangeTrigger for the BuildConfig)

**Comment by csrwng** [comment]
@bparees but that should be ok... if the buildconfig can't be updated it means the build won't be started.

**Comment by csrwng** [comment]
I see yes

**Comment by liggitt** [comment]
Does this mean @csrwng is on the hook to fix this? When it comes to assigning build flakes, I have a hair trigger… :)

**Comment by csrwng** [comment]
@liggitt yes you can assign to me

**Comment by liggitt** [comment]
Should we have a test that enables both triggers and makes sure the expected result occurs?

**Comment by bparees** [comment]
so i looked at the code and the "pushbuild" buildconfig doesn't even have a configchangetrigger defined.....
https://github.com/openshift/origin/blob/master/test/integration/webhookgithub_test.go#L285-L299
https://github.com/openshift/origin/blob/master/test/integration/webhookgithub_test.go#L330-L345

**Comment by csrwng** [comment]
@bparees but the image change trigger would have the same effect

**Comment by csrwng** [comment]
@bparees it's one of those times when you get lucky and the build fires immediately
