### ISSUE TITLE
build log entries get duplicated when following

### ISSUE THREAD

**Issue by bparees** [openshift/origin#4255]
when streaming the logs the entries start over at some point, duplicating the initial values.

when viewing the logs after the build is complete (via oc build-logs) the duplication is not present.

duplication is seen at line 13:
https://gist.github.com/bparees/43727f4e80906cd42e47#file-gistfile1-txt-L13

**Comment by gabemontero** [comment]
Granted this is an old one, but I did not see this with a build I just tried.  Looking at the gist, I seems to leverage an incremental build.  In case that has some bearing, I'll see about finding/building such an example and try that as well.

**Comment by bparees** [comment]
it's definitely an old enough bug that i wouldn't be shocked if it's magically gone away.

make sure you're streaming the logs (ie `oc build-logs mybuild-1 --follow`) though.  (that's probably the command i was using back then, i should have included it in the report)

**Comment by gabemontero** [comment]
I've tried the streaming form of `oc start-build` and `oc build-logs` and well as trying `oc logs`, and tried a iteration with incremental=true with no luck at reproducing.

If you can reproduce, shoot me the relevant json/yaml and I'll start digging. Otherwise I think we should close this one.

**Comment by bparees** [comment]
good enough for me, thanks for checking into it.

**Comment by gabemontero** [comment]
cool deal / np / yw
