### ISSUE TITLE
add old config start tests to extended bucket

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4259]
https://github.com/openshift/origin/tree/master/test/old-start-configs was intended to be run as an extended test.  Now that extended tests are available, we should integrate this in.

**Comment by liggitt** [comment]
@deads2k fixed by https://github.com/openshift/origin/pull/4457?

**Comment by deads2k** [comment]
> @deads2k fixed by #4457?

Yeah. Who knew this existed?
