### ISSUE TITLE
api.SecurityContextConstraints: the server could not find the requested resource

### ISSUE THREAD

**Issue by mrGrab** [openshift/origin#4260]
hi,
I have installed external kubernetes v1.1.0 and etcd  v2.2.0
When I start openshift/origin (openshift v1.0.4) I get error: 
5459 reflector.go:180] pkg/security/admission/admission.go:59: Failed to list *api.SecurityContextConstraints: the server could not find the requested resource

$ oc get scc
Unable to list "securitycontextconstraints": the server could not find the requested resource

When I'm trying create new scc I get error:
error: could not read an encoded object: unable to recognize "file-name.yaml": no kind named "SecurityContextConstraints" is registered in versions ["" "v1"]

Looks like kubernetes doesn't have such type(kind)
Can you advise how can I create new kind "SecurityContextConstraints" ?

**Comment by deads2k** [comment]
@pweil- fyi

**Comment by pweil-** [comment]
SecurityContextConstraints are not yet merged into upstream Kubernetes yet.  If you are trying to use an external Kubernetes cluster then you will need to patch in this PR https://github.com/kubernetes/kubernetes/pull/7893.  FYI, we are currently opting to make the SCC type an OpenShift type in the meantime.  That PR is under review here: https://github.com/openshift/origin/pull/4252

**Comment by mrGrab** [comment]
it helped. Thanks.
I hope openshift and kubernetes will release new features simultaneously... ;)
