### ISSUE TITLE
Extended Test Launcher Needs Better Specificity

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4266]
Currently passing arguments to `hack/test-extended.sh` chooses which `run.sh` script under `hack/test-extended/` to run, which means that isolating specific tests is not possible unless the entire start script is copied for each test. As many tests need the same start-up, this is not concise. We need to parse the arguments to `hack/test-extended.sh` in the same manner as we do to `hack/test-integration.sh` - pass them to a `grep -E`.

**Comment by mfojtik** [comment]
Should be fixed here: https://github.com/openshift/origin/pull/4285

**Comment by bparees** [comment]
can now specify a focus when invoking extended tests. (test/extended/core.sh --focus=foo)
