### ISSUE TITLE
ImageStreamTag updated 292 years ago

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4275]
Using the following `ImageStream` definition:

```json

{
  "kind": "ImageStream",
  "apiVersion": "v1",
  "metadata": {
    "name": "openldap",
    "creationTimestamp": null
  },
  "spec": {
    "dockerImageRepository": "openshift/openldap-2441-centos7",
    "tags": [
      {
        "tag": "latest",
        "annotations": {
          "description": "Provides OpenLDAP v2.4.41",
          "iconClass": "fa-server",
          "tags": "server,openldap",
          "version": "2.4.41"
        }
      }
    ]
  },
  "status": {
    "dockerImageRepository": ""
  }
}
```
I do the following:

```sh
$ oc create -f test/extended/fixtures/ldap/ldapserver-imagestream.json 
imagestream "openldap" created
$ oc get imagestreamtag openldap:latest
NAME              DOCKER REF                                                                                                UPDATED         IMAGENAME
openldap:latest   openshift/openldap-2441-centos7@sha256:7f83fe368b8462bb53a8229bee0e7ba669012a3d2bc431714880b13f9e5e1f1a   292 years ago   sha256:7f83fe368b8462bb53a8229bee0e7ba669012a3d2bc431714880b13f9e5e1f1a
```

And I see that the last updated date was `292 years ago`.

@bparees

**Comment by liggitt** [comment]
1723 was a good year for builds

**Comment by smarterclayton** [comment]
Ah, the crop of 1723.  I remember it well.  All our processors had 0.00000000025 transistors, and we had to code in unary notation.

**Comment by benjaminapetersen** [comment]
This is great :smiley:

**Comment by ncdc** [comment]
What makes more sense to show - when the actual Docker image was created, or when the image metadata was imported into OpenShift?

**Comment by bparees** [comment]
both....

**Comment by ncdc** [comment]
So you want 2 time columns instead of 1?

**Comment by bparees** [comment]
yeah..i mean i thought about it and i can't convince myself that one is explicitly more important/useful/common than the other.

about the only argument i could come up with for just showing one is "this is the imagestreamtag, so show the date for the IST being updated.  if you want to know when the image it represents was updated, go look at the image", but even then a better column label might be in order.

**Comment by ncdc** [comment]
IST is a virtual resource. I'd say the date from the Docker image is probably the most relevant.

**Comment by bparees** [comment]
if i run an oc import i'd expect to see this information refreshed to indicate the last time it checked.

**Comment by ncdc** [comment]
Really? Even if nothing changed?

**Comment by bparees** [comment]
honestly i can see a lot of ways to go with this, but yes one way in my head would be "i want to know if this imagestream has the most current data in it" which means knowing when it last checked, not when it last found something new.

**Comment by ncdc** [comment]
There are 4 dates:

1. Docker image creation date
1. OpenShift image creation date (when the Docker image was imported into OpenShift)
1. ImageStream TagEvent creation date (stream.status.tags[latest][0].creationDate)
1. Last time tags were imported into the stream

When you 'oc get istag foo:latest', which of those 4 dates do you want to see? And what about when you 'oc describe' an IST?

**Comment by smarterclayton** [comment]
All of them, in the right places.  In this case 1,3. Image created two tags
ago, tagged an hour ago. The last import date is relevant on an IS

On Aug 24, 2015, at 4:07 PM, Andy Goldstein <notifications@github.com>
wrote:

There are 4 dates:

   1. Docker image creation date
   2. OpenShift image creation date (when the Docker image was imported
   into OpenShift)
   3. ImageStream TagEvent creation date
   (stream.status.tags[latest][0].creationDate)
   4. Last time tags were imported into the stream

When you 'oc get istag foo:latest', which of those 4 dates do you want to
see? And what about when you 'oc describe' an IST?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4275#issuecomment-134343109>.

**Comment by smarterclayton** [comment]
Today, you import an image stream, not an individual istag.  When we enable
that we'll need to fix the general design.

On Aug 24, 2015, at 3:58 PM, Ben Parees <notifications@github.com> wrote:

if i run an oc import i'd expect to see this information refreshed to
indicate the last time it checked.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4275#issuecomment-134339660>.
