### ISSUE TITLE
oc port-forward concurrency limitation

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#4287]
When attempting multiple connections over a port forwarded to a container (`oc port-forward`), there seems to be a limit of 5 on the number of concurrent connections. Once there are more, connections hang / timeout and don't seem to recover.

This was encountered with a nodejs container in trying to use the node-inspector debugger app which listens on two non-public ports, the HTTP port presenting an HTML5 webapp that loads a number of assets concurrently. Here is typical output from the port-forward:

```
I0819 13:28:57.321178   18067 portforward.go:225] Forwarding from 127.0.0.1:8080 -> 8080
I0819 13:28:57.321270   18067 portforward.go:225] Forwarding from [::1]:8080 -> 8080
I0819 13:28:57.321298   18067 portforward.go:225] Forwarding from 127.0.0.1:5858 -> 5858
I0819 13:28:57.321327   18067 portforward.go:225] Forwarding from [::1]:5858 -> 5858
I0819 13:29:13.399831   18067 portforward.go:251] Handling connection for 8080
I0819 13:29:37.633514   18067 portforward.go:251] Handling connection for 8080
I0819 13:29:37.633844   18067 portforward.go:251] Handling connection for 8080
I0819 13:29:37.633880   18067 portforward.go:251] Handling connection for 8080
I0819 13:29:37.633893   18067 portforward.go:251] Handling connection for 8080
I0819 13:29:38.107638   18067 portforward.go:251] Handling connection for 8080
I0819 13:29:38.108131   18067 portforward.go:251] Handling connection for 8080
E0819 13:30:07.719444   18067 portforward.go:310] An error occurred forwarding 8080 -> 8080: Timed out waiting for data stream
E0819 13:30:07.795932   18067 portforward.go:310] An error occurred forwarding 8080 -> 8080: Timed out waiting for data stream
E0819 13:30:07.795949   18067 portforward.go:310] An error occurred forwarding 8080 -> 8080: Timed out waiting for data stream
I0819 13:30:07.796389   18067 portforward.go:251] Handling connection for 8080
I0819 13:30:07.796474   18067 portforward.go:251] Handling connection for 8080
E0819 13:30:08.201089   18067 portforward.go:280] Error creating forwarding stream for port 8080 -> 8080: Timeout occured
E0819 13:30:08.201713   18067 portforward.go:280] Error creating forwarding stream for port 8080 -> 8080: Timeout occured
E0819 13:30:37.796628   18067 portforward.go:262] Error creating error stream for port 8080 -> 8080: Timeout occured
```

Individual serialized requests succeed indefinitely. Only concurrency seems to be an issue. This makes the debugger entirely unusable. Since it assumes two ports on the same host I can't even expose it usefully via service/route as a workaround. I haven't tried it with any other application yet; it's possible it would work differently.

**Comment by jcantrill** [comment]
cc @maxandersen FYI

**Comment by maxandersen** [comment]
ouch ;/

**Comment by liggitt** [comment]
@ncdc is this caused by the spdystream FRAME_WORKERS being set to 5 or is that just a coincidence?

**Comment by ncdc** [comment]
I haven't had any time to investigate yet. I sure hope not :-/

**Comment by ncdc** [comment]
It doesn't seem to be a limit of 5. I think there may be some sort of partial deadlock occurring. If I run 10 or even 100 simultaneous curls against nginx, several complete successfully, but after a certain point, attempts to handle new forwarded connections hang with various timeouts occurring. Each connection should result in 2 streams being created: 1 for the server to convey errors back to the client, and the other to carry the actual forwarded data. When things start hanging, stream creation times out, and it waits up to 30 seconds for the server to reply that it received a new stream. I'll keep investigating.

**Comment by ncdc** [comment]
I have found the root cause and have a fix locally that seems to work. I need to clean it up a bit and I'll have something to submit upstream next week if all goes well.

**Comment by ncdc** [comment]
Upstream issue & analysis: https://github.com/kubernetes/kubernetes/issues/13673

1 important item to note - my proposed fix will make it so older clients won't be able to do port forwarding against newer servers containing the fix. I'm wondering how much of an issue this will be?

**Comment by liggitt** [comment]
I really don't like the client-side allocation of stream ids... any way around that?

**Comment by ncdc** [comment]
https://github.com/kubernetes/kubernetes/pull/12283 just merged upstream.

@brenton @danmcp @sdodson @smarterclayton @sosiouxme @bparees @pweil- @liggitt do you want this cherry picked to origin now, or will we be doing another rebase that could pick this up?

**Comment by danmcp** [comment]
@ncdc A rebase is starting now.  And there will probably be 1 more.

**Comment by ncdc** [comment]
Ok, in that case, I would recommend just waiting to pick this fix up in a
rebase.

**Comment by sosiouxme** [comment]
+1

**Comment by ncdc** [comment]
This landed in the most recent rebase and QE verified the bz. @sosiouxme do you mind testing and closing assuming it works for you?

**Comment by sosiouxme** [comment]
tested, it works well, thanks!
