### ISSUE TITLE
DataService.get() streamlining

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#4313]
I'd like to see if we can streamline the DataService process a bit & remove some of the bookkeeping 
from the controller.  Here is my current code block, with a few numbered comments I'd like to tweak:

```javascript

// inside my controller

// 1.) context
var requestContext = {
  projectName: $routeParams.project,  
  projectPromise: $.Deferred()  // 2.) 
};

AuthService
  .withUser()
  .then(function(user) {
    return DataService
            .get('projects', requestContext.projectName, requestContext, {errorNotification: false})
            .then(function(project) {
              // though the above .get('projects') is really my project promise...
              requestContext.projectPromise.resolve(project);
              angular.extend(requestContext, {
                project: project
              });
              return project;
            }, function(e) {
              requestContext.projectPromise.reject(e);
            });
  })
  .then(function(project) {
    return DataService
            .get('builds', $routeParams.build, requestContext)
            .then(function(build) {
              angular.extend($scope, {
                build: build,
                logName: build.metadata.name
              });
              return build;
            });
  });

```

1.) Context adjusted to a hash instead of $scope
    - not sharing w/ service
    - not sharing w/other controllers
    - eliminates need for view coupling & DOM order dependencies breaking service requests:
```html
<div ng-controller="ProjectController">
      <div ng-controller="MyController">
```
2.) projectPromise 
    - my first DataService.get('projects')  really ought to be my project promise
    - having to .projectPromise.resolve(project) or .reject(project) in my controller seems unnecessary, since 3.) .then(function(project)) gets the resolved promise value of the project, which I can add to the context for my builds request.
    - We can probably change from jQuery.Deferred() to $q.defer() if we can't eliminate
    - There is an additional `var deferred = $q.defer();` created in DataService.get().  I imagine like we can consolidate these.
   - If we can either eliminate context.projectPromise or push it up into the service, that would be great. 
   - I imagine context.projectName is unnecessary as well, the context.project can probably provide
   - Subsequent calls (builds, logs, etc) the context can now build up with data for chained requests.

In the end this is what I'm aiming at:

```javascript
var requestContext = {};

AuthService
  .withUser()
  .then(function(user) {
    return DataService
            .get('projects', $routeParams.project, requestContext, {errorNotification: false})
            .then(function(project) {
              // build context for second request
              angular.extend(requestContext, {
                project: project
              });
              return project;
            });
  })
  .then(function(project) {
    return DataService
            .get('builds', $routeParams.build, requestContext)
            .then(function(build) {
              // requests progressively build $scope for view
              angular.extend($scope, {
                project: project,
                build: build
              });
              return build;
            });
  })
 .then(function(build) {
          return DataService
                  .get('builds/log', $routeParams.build, requestContext)
                  .then(function(log) {
                    angular.extend($scope, {
                        log: log
                    });
                  });
  });
  // can continue to build $scope with additional .then() if needed.
``` 

I imagine there may be ramifications for `.watch()` or other methods.  

@liggitt thoughts?

**Comment by liggitt** [comment]
The user->project bit is common between all controllers in the scope of a project... don't want that duplicated. @jwforres can jump in here... she did the initial nested project controller setup to share that prereq setup code.

**Comment by liggitt** [comment]
also, we want to make sure we parallelize things as much as possible... the build->build/log case has to be serial, but there's no reason we can't parallelize different resource types whenever possible

**Comment by benjaminapetersen** [comment]
Yup, parallels is fine, something like:

```javascript

$q
  .all([
    DataService.get('foo'), 
    DataService.get('bar')
  ])
  .then(_.spread(function(foo, bar) {
    angular.extend($scope, {
      foo: foo,
      bar: bar
    });
  }));

```
Not a problem to support both.  But I think we would benefit long term by decoupling DOM nesting with $scope across multiple controllers & service requests.

**Comment by benjaminapetersen** [comment]
@jwforres definitely appreciate your thoughts as well!

**Comment by jwforres** [comment]
We didn't want every single controller having to know it needed to first go get the user and then go get the project and then be able to make the rest of its requests.  If there is another way to accomplish that without DOM nesting I'd like to see it.

**Comment by benjaminapetersen** [comment]
Well, to avoid that we could probably create a wrapper service to hide away the details of the auth/user/project stuff.  something like:

```javascript
     currentProject
        .get()
        .then(function(project) {
          return $q.all([
            $q.when(project),  // just passing along
            DataService,get('builds', $routeParams.build, {project: project}),
            DataService,get('builds/log', $routeParams.build, {project: project}),
            $q.when('foo')
          ]);
        }).then(_.spread(function(project, builds, buildLogs, foo) {
            angular.extend($scope, {
               project: project,
               builds: builds,
               logs: buildLogs
               foo: foo
            });
        }));

```
Keeps the flow in one place & keeps the noise down.

**Comment by jwforres** [comment]
Not opposed to the idea, there is some other stuff that project controller
sets up on the scope as well.

**Comment by jwforres** [comment]
Started transitioning to using the project service in https://github.com/openshift/origin/pull/4726 but only for new controllers. Leaving this issue open as bookkeeping to go back and clean up the existing controllers.

**Comment by benjaminapetersen** [comment]
TODO list of remaining controller/view refactors needed based on the appearance of `ng-controller="ProjectController"`:

- [ ] views/browse/routes.html
- [ ] views/builds.html
- [ ] views/create/fromimage.html
- [ ] views/create/nextSteps.html
- [ ] views/create.html
- [ ] views/deployments.html
- [ ] views/events.html
- [ ] views/images.html
- [ ] views/newfromtemplate.html
- [ ] views/pods.html
- [ ] views/project.html
- [ ] views/services.html
- [ ] views/settings.html

**Comment by benjaminapetersen** [comment]
I think we have resolved this.  Ok to close?

**Comment by benjaminapetersen** [comment]
Yeah, we are good here.
