### ISSUE TITLE
oc new-imagestream command?

### ISSUE THREAD

**Issue by bparees** [openshift/origin#4325]
Thinking about the awkward management of our various imagestream.json files, I wonder if there's room for an "oc new-imagestream <docker repo> -n <namespace>" style command that will just create an imagestream for a given image.  One more option would be "--builder" which would automatically put the builder annotation on the imagestream so it shows up as a builder image in the web UI.

We could then potentially get rid of the imagestream json, replacing it with doc that just tells admins how to import the images (and the installer could still auto-run those import commands for images if we want to ensure a good out of box experience)

my concern about maintaining the existing imagestreams json is that we have more and more images that will not be under our control (middleware images, SCL images, third party images) and i'd like to stop treating "our" images as somehow special while simultaneously making it easier to add other images.

@fabianofranz @smarterclayton @csrwng @mfojtik what do you think?

I could also envision this being a useful webconsole feature, @jwforres

**Comment by bparees** [comment]
also (while i'm wishing) it'd be cool to be able to do what is described here:
https://github.com/openshift/origin/pull/4016/files#diff-763d7266463feb65b03e3184412cbd74R237

which is to have the import/new-imagestream command take a tarball as an input, where that tarball is a docker image that should be loaded/pushed into the openshift registry.

**Comment by smarterclayton** [comment]
I think you want oc tag and oc import-image, which can do the creation and tagging as of 1.0.4.  Annotation setting on tags is bit trickier, but probably belongs to the oc tag command.

    $ oc tag openshift/origin:latest somenewimagestream --confirm
    $ oc import-image --from=openshift/origin somenewimagestream --confirm

Having import image do the tar loading makes sense as a new flag.  We still need to implement spec import as well as whole repo import.

**Comment by bparees** [comment]
if oc tag will create non-existent imagestreams the help should be updated...  also is the oc import-image really needed, then?  wouldn't just doing oc tag create the imagestream and then an import would happen immediately for the new stream/tag?

**Comment by smarterclayton** [comment]
oc tag doesn't import images, it symlinks them.  You have no metadata when
you do that.  When we get the auth story sorted out that might be
reasonable.

On Sat, Aug 22, 2015 at 5:50 PM, Ben Parees <notifications@github.com>
wrote:

> if oc tag will create non-existent imagestreams the help should be
> updated... also is the oc import-image really needed, then? wouldn't just
> doing oc tag create the imagestream and then an import would happen
> immediately for the new stream/tag?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4325#issuecomment-133757266>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by kargakis** [comment]
fyi https://github.com/kubernetes/kubernetes/pull/14294

**Comment by bparees** [comment]
@kargakis i don't think that proposal makes this scenario easy enough, so i'd still want to see an explicit command where i can just provide some minimal information on the CLI and get the object created.

being thrown into an editor is also not scriptable.

**Comment by fabianofranz** [comment]
I'd suggest we move this to a Trello story (scope seems bigger than an enhancement).

**Comment by kargakis** [comment]
> I'd suggest we move this to a Trello story (scope seems bigger than an enhancement).

Trello'd: https://trello.com/c/X4zVMDRA/527-add-new-imagestream-command

**Comment by bparees** [comment]
Closing in deference to trello.
