### ISSUE TITLE
oc scale against a dc is fragile in the presence of races

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4327]
Attempting to scale a DC while the controller is creating new RCs returns confusing and vague error messages.  If the conditional create of an RC fails (because it's being updated by the DC), we should reload the RC and check that it still current (not failed or completed) and try once more to save.  Even a few retries (well factored) would make this a safer experience.

```
pod "test-deployment-config-1-deploy" deleted
deploymentconfig "test-deployment-config" created
Started deployment #2
CONTROLLER                 CONTAINER(S)      IMAGE(S)                                      SELECTOR                                                                                           REPLICAS   AGE
test-deployment-config-2   ruby-helloworld   127.0.0.1:5001/openshift/origin-ruby-sample   deployment=test-deployment-config-2,deploymentconfig=test-deployment-config,name=test-deployment   0          0s
Scaling the controller failed with: replicationControllers "test-deployment-config-3" not found; Current resource version Unknown
!!! Error in test/cmd/deployments.sh:41
  'oc scale dc test-deployment-config --replicas=1' exited with status 1
Call stack:
  1: test/cmd/deployments.sh:41 main(...)
```

**Comment by smarterclayton** [comment]
@kargakis @ironcladlou

**Comment by liggitt** [comment]
whatever we do here, we should come up with a pattern that makes sense for the `label`, `annotate`, `volume` commands

**Comment by smarterclayton** [comment]
Let's open an upstream issue - "Client commands tend to race against
controllers due to status changes / scheduling when used in bash" with the
fix being "client spec changes should be against spec only using generation
or <insert new solution here>"

On Tue, Aug 25, 2015 at 12:30 AM, Jordan Liggitt <notifications@github.com>
wrote:

> whatever we do here, we should come up with a pattern that makes sense for
> the label, annotate, volume commands
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4327#issuecomment-134464350>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
New/related to lay the foundation for safe concurrent scaling/deployment: https://github.com/kubernetes/kubernetes/issues/14062

**Comment by liggitt** [comment]
probably addressed by dc/scale changes

**Comment by ironcladlou** [comment]
Fixed by #5875

**Comment by smarterclayton** [comment]
Such confidence.

**Comment by ironcladlou** [comment]
`oc scale` against a dc no longer touches RCs as of #5875, so there's no longer a way for the reported condition to arise.

**Comment by kargakis** [comment]
It doesn't even touch the DC.

**Comment by kargakis** [comment]
But the scaling endpoint
