### ISSUE TITLE
oc status output for trigger deployments is misleading

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4328]
Recently oc status for a deployment started showing:

```
dc/test-deployment-config deploys 127.0.0.1:5001/openshift/origin-ruby-sample:latest 
  #3 deployment pending on update
  #2 deployment pending 3 minutes ago
```

but only with state:

```
$ oc get rc
CONTROLLER                 CONTAINER(S)      IMAGE(S)                                      SELECTOR                                                                                           REPLICAS   AGE
test-deployment-config-2   ruby-helloworld   127.0.0.1:5001/openshift/origin-ruby-sample   deployment=test-deployment-config-2,deploymentconfig=test-deployment-config,name=test-deployment   0          3m
```

The fake entry for the third deployment is confusing to new users (there is no deployment 3 yet).  It looks like a race condition in the deployment controller - somehow latestVersion of the object is 3. From deployments.sh:

```
oc create -f test/integration/fixtures/test-deployment-config.json
oc deploy test-deployment-config --latest
tryuntil oc get rc/test-deployment-config-2
# scale rc via deployment configuration
oc scale dc test-deployment-config --replicas=1
```

@deads2k @ironcladlou @kargakis

**Comment by smarterclayton** [comment]
This may also be a race condition in the DC where latestVersion is being bumped due to #4330, which would indicate why this is happening.  The controller manager may be confused about the versions (although it should still be creating a deployment).

**Comment by ironcladlou** [comment]
@smarterclayton @kargakis I still can't reproduce any bad behavior with rapid create/deletes. I've been trying things like:

```bash
for i in $(seq 1 25); do
  echo iteration $i

  oc create -f test/integration/fixtures/test-deployment-config.json
  oc deploy test-deployment-config
  [ "$(oc status dc/test-deployment-config | grep '1 deployment')" ]
  oc delete deploymentConfigs test-deployment-config
done
```

And sometimes using `delete all --all` and the version is never inconsistent. Any thoughts on how we can reliably break it?

**Comment by smarterclayton** [comment]
It was in hack/test-cmd that it happened - I was able to see it happen a
few times there.

On Tue, Sep 15, 2015 at 9:18 AM, Dan Mace <notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton> @kargakis
> <https://github.com/kargakis> I still can't reproduce any bad behavior
> with rapid create/deletes. I've been trying things like:
>
> for i in $(seq 1 25); do
>   echo iteration $i
>
>   oc create -f test/integration/fixtures/test-deployment-config.json
>   oc deploy test-deployment-config
>   [ "$(oc status dc/test-deployment-config | grep '1 deployment')" ]
>   oc delete deploymentConfigs test-deployment-configdone
>
> And sometimes using delete all --all and the version is never
> inconsistent. Any thoughts on how we can reliably break it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4328#issuecomment-140387756>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ironcladlou** [comment]
@smarterclayton should we remove the fake entry?

**Comment by smarterclayton** [comment]
Fake?

**Comment by ironcladlou** [comment]
From the issue description, "The fake entry for the third deployment". If there is no deployment for the latest version on the config, a status entry is "synthesized" trying to convey that while that deployment doesn't exist, it might soon (if a defined trigger is fired, etc.)

**Comment by smarterclayton** [comment]
Maybe we need to crisp up the fake one somehow, or better detect when the fake is going to be real

**Comment by ironcladlou** [comment]
This should be cleaned up at the same time as #3526

**Comment by kargakis** [comment]
This should be a side-effect of https://github.com/openshift/origin/issues/4330
