### ISSUE TITLE
deployment cancel seems to fail to change Phase

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4329]
```
oc create -f test/integration/fixtures/test-deployment-config.json
tryuntil oc get rc/test-deployment-config-1
oc deploy test-deployment-config --cancel
```

Leaves the RC in this state:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      kubectl.kubernetes.io/desired-replicas: "1"
      openshift.io/deployer-pod.name: test-deployment-config-1-deploy
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: test-deployment-config
      openshift.io/deployment.cancelled: "true"
      openshift.io/deployment.phase: Pending
      openshift.io/deployment.status-reason: The deployment was cancelled by the user
```

Shouldn't phase be altered?  Otherwise this happens:

```
$ oc deploy test-deployment-config --latest
error: #1 is already in progress (Pending).
Optionally, you can cancel this deployment using the --cancel option.
$ oc deploy test-deployment-config --retry
error: #1 is Pending; only failed deployments can be retried.
Optionally, you can cancel this deployment using the --cancel option.
```

Sure would be nice to be able to keep going...

**Comment by ironcladlou** [comment]
What state does your deployer pod end up in? We update the RC with the cancelation metadata which should trigger ActiveDeadlineSeconds being set on the deployer pod (should be an event and logs if that failed). When the deployer pod finally exits, then the deployment phase will be reconciled.

**Comment by smarterclayton** [comment]
The pod was still in pending.  If you have no nodes available that means
you wait forever. Probably it should terminate a pending pod immediately
(if it wins the race with the scheduler).

On Aug 24, 2015, at 11:03 AM, Dan Mace <notifications@github.com> wrote:

What state does your deployer pod end up in? We update the RC with the
cancelation metadata which should trigger ActiveDeadlineSeconds being set
on the deployer pod (should be an event and logs if that failed). When the
deployer pod finally exits, then the deployment phase will be reconciled.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4329#issuecomment-134215923>.

**Comment by ironcladlou** [comment]
The cancelation logic today relies exclusively on ActiveDeadlineSeconds, which is not useful when the pod hasn't scheduled (ADS is enforced by the kubelet against scheduled pods).

The deployment controller would need to handle cancelation by either setting ADS for scheduled pods or deleting pending pods. The deployer pod controller would need refactored to handle delete events, which is the larger piece of work.

**Comment by ironcladlou** [comment]
Actually, I think we could just just delete the pod in the deployment controller and transition to failed immediately: there's no reason to coerce an event to be handled by the deployer pod controller since there's no deployer pod anymore. Just set the status right after we know we deleted the pod.

**Comment by ironcladlou** [comment]
Fixed by #4364

**Comment by kargakis** [comment]
> The cancelation logic today relies exclusively on ActiveDeadlineSeconds, which is not useful when the pod hasn't scheduled (ADS is enforced by the kubelet against scheduled pods).

Oh, that's why my cancellation code never worked:)

Related: https://github.com/openshift/origin/issues/8439

**Comment by kargakis** [comment]
This is fixed
