### ISSUE TITLE
cgroup info available in container

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#4336]
Hi All,
    I would like to get the container's total memory available from inside a script that is running in a container, in order to configure the java heap size (% of Total memory) I need to get the total mem available for the container.
Is that information available in the container? 
How can I inject that information when pod is created?

many thanks.

**Comment by smarterclayton** [comment]
There is an upstream issue on this: https://github.com/kubernetes/kubernetes/issues/9473 - trying to get it in

**Comment by ncdc** [comment]
This has been merged to Kubernetes. It will be available in Origin in either the next rebase or the one after that.

**Comment by ncdc** [comment]
This is now in Origin.
