### ISSUE TITLE
The PATH for openshift binaries is wrong in Vagrant

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#434]
It seems like the PATH is pointing to a wrong location in Vagrant:

```
export PATH=/bin:/data/src/github.com/openshift/origin/_output/etcd/bin:/data/src/github.com/openshift/origin/_output/go/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```

I see the binaries are now placed into `/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64`

**Comment by ironcladlou** [comment]
@mfojtik this is resolved, correct?

**Comment by smarterclayton** [comment]
Reopen if this is not fixed.
