### ISSUE TITLE
Web Console: give URL to use for "oc login"

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#4344]
Users of the Web Console need to drop to the CLI for a number of things, assuming they already installed the CLI, they need to dig through old notes on what the URL is for the server to use for "oc login".  The Web Console directs the user for a number of things to use the CLI, perhaps this is a minor issue for people with only 1 instance to connect to.

I would be very handy to provide this in the Web UI, in the user drop down or projects page.

**Comment by jwforres** [comment]
With https://github.com/openshift/origin/pull/4728 we will at least be telling you this on the next steps page.  But we should still include this elsewhere in a Help type page that we have been discussing adding.
