### ISSUE TITLE
Dockerbuild fails unbound variable OS_GIT_MAJOR

### ISSUE THREAD

**Issue by LarsMilland** [openshift/origin#4354]
Hi

I am trying to use the Openshift V3 platform from a vagrant based locally build version with a simple Dockerfile based image.

I am running from the commit of:

commit 3dd83f8367c77cb130780bde58ea101899267c06
Merge: 5193c6b 88d8814
Author: OpenShift Bot <dmcphers+openshiftbot@redhat.com>
Date:   Sun Aug 23 16:40:12 2015 -0400

and my Dockerfile simply tries to start from:

FROM openshift/base-centos7

and then exposing some ports for the resulting Docker container so that I can installa Java and run a Java application in the Docker container. 

The Dockerfile is located locally on the Openshift servers filesystem and I create the application using this command:

oc new-app . --name=mstms

Every run I try I end up with this error - that the Docker image fails to start because it can't get the environment of "git and versions" to work proper:

Step 6 : RUN go get github.com/openshift/origin && hack/build-go.sh && cp _output/local/go/bin/* /usr/bin/ && mkdir -p /var/lib/openshift
 ---> Running in ef1b5e454a3e
hack/../hack/common.sh: line 459: OS_GIT_MAJOR: unbound variable
F0819 07:21:06.168408       1 builder.go:65] Build error: The command [/bin/sh -c go get github.com/openshift/origin && hack/build-go.sh && cp _output/local/go/bin/* /usr/bin/ && mkdir -p /var/lib/openshift] returned a non-zero code: 1

Otherwise the Dockerfile works fine, as the "Services" in Openshift are defined as specified by the EXPOSE configuration in the Dockerfile.

Is this due to some error or due to lack of support for this kind of "build" where the source of the Dockerfile is from the local filesystem and not from a git repository?

**Comment by smarterclayton** [comment]
@bparees @mfojtik

**Comment by bparees** [comment]
1) We definitely don't support building from anywhere except a remotely accessible git repo, so i'm surprised you even got this far.

2) Can you run "oc get bc -o json -n <your namespace>" and "oc get builds -o json -n <yournamespace> and show me the output?

3) also if you can gist the entire build-logs output that would help.

4) and what is in your Dockerfile?

5) if you run "docker build ." in the directory containing your Dockerfile does that work?

**Comment by mfojtik** [comment]
```
Step 6 : RUN go get github.com/openshift/origin && hack/build-go.sh && cp _output/local/go/bin/* /usr/bin/ && mkdir -p /var/lib/openshift
---> Running in ef1b5e454a3e
hack/../hack/common.sh: line 459: OS_GIT_MAJOR: unbound variable
```

Can you do instead of 'go get' git clone? I it fails because the source you are trying to build is not valid GIT repository (the OS_GIT_MAJOR is variable to determine the current version of OpenShift).

**Comment by bparees** [comment]
@LarsMilland please reopen if you are still having issues and are able to provide the information requested.
