### ISSUE TITLE
UI says manual deployment was "triggered by a config change"

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4359]
I ran this command:

```
[vagrant@openshiftdev ~]$ oc deploy database --latest -n project1
Started deployment #2
```

But I see this in the UI:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/9468238/857e67b8-4b0e-11e5-9610-a4648d23b32f.png)

@jwforres

**Comment by jwforres** [comment]
I'll fix this while I'm working on the overview

**Comment by jwforres** [comment]
@ironcladlou when we get an API endpoint for manually starting a deployment, can we get a different cause returned, like "Manual" or something.  Right now oc deploy essentially is creating a config change to trigger the deployment by bumping the version number.

**Comment by ironcladlou** [comment]
@jwforres 
>when we get an API endpoint for manually starting a deployment, can we get a different cause returned, like "Manual" or something. Right now oc deploy essentially is creating a config change to trigger the deployment by bumping the version number.

Perhaps... the need is real, but I know @smarterclayton had some opinion about the future of the cause API. It's trigger centric right now.

**Comment by smarterclayton** [comment]
Uh, I don't remember any more, but I don't see why not.  I am a little
scared about going crazy on this API prior to deployments upstream, but
having cause be a param makes sense.

On Aug 26, 2015, at 5:50 PM, Dan Mace <notifications@github.com> wrote:

@jwforres <https://github.com/jwforres>

when we get an API endpoint for manually starting a deployment, can we get
a different cause returned, like "Manual" or something. Right now oc deploy
essentially is creating a config change to trigger the deployment by
bumping the version number.

Perhaps... the need is real, but I know @smarterclayton
<https://github.com/smarterclayton> had some opinion about the future of
the cause API. It's trigger centric right now.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4359#issuecomment-135166829>.
