### ISSUE TITLE
oc keeps complaining about token missing without telling user how to fix it

### ISSUE THREAD

**Issue by maxandersen** [openshift/origin#4360]
Doing `oc login`:

```
oc login https://console.qe.openshift.com
Username: manderse@redhat.com
Login failed (401 Unauthorized)
You must obtain an API token by visiting https://api.qe.openshift.com/oauth/token/request
```

I go to the url and run `oc login --help` to get some info, it just talks about `--password`.

```
oc login https://console.qe.openshift.com --password=<secrettoken>
Username: manderse@redhat.com
Login failed (401 Unauthorized)
You must obtain an API token by visiting https://api.qe.openshift.com/oauth/token/request
```

And when I do that I get the exact same error.

it never mentions the *Actual* minimal solution:

```
oc login https://console.qe.openshift.com --token=<secrettoken>
Logged into "https://console.qe.openshift.com:443" as "manderse@redhat.com" using the token provided.

Using project "test1".

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * test1 (current)
  * test2
```

Suggestions:
a) if `--password` specified use it as alias for `--token`
b) document use of `--token` in `oc login --help`
c) Add line to login that ask to go to url to say to use `oc login <hostgiventoiniitiallogin> --token=<secrettoken> `

**Comment by liggitt** [comment]
We should document `--token` for `oc login`

`--password` is different than token, we shouldn't conflate/alias them

On the page where you request the token, it gives you the exact command to log in with oc:
```
How do I use this token?

oc login --token=<redacted> --server=https://api.qe.openshift.com
```

**Comment by liggitt** [comment]
@fabianofranz can we make sure `--token` info appears for `oc login`?

**Comment by maxandersen** [comment]
I can honestly say I did not notice the instructions on the token web page at all before you pointed it out to me.

I think that the first paragraph is basically just a json dump made my brain say "okey - everything else is just technical details, let me grab the token and get outta here" :)

Would be great if this page was a bit more visually styled IMO and even better had a few buttons to copy the relevant token and commands to a terminal. 

Right now its a tad tedious.

But anyway, having --token documented in oc would be a good start.

I don't really grok why --password and --token is separated out, is there ever a time where both make sense to specify ?

**Comment by liggitt** [comment]
--username and --password are used to get a token. --token is just checked against the API directly.

**Comment by liggitt** [comment]
That page is served by the API, so it's non-trivial to add additional resources like flash copy buttons, etc. We could style it more nicely

**Comment by smarterclayton** [comment]
Does it have to be served by the API?  Could we inject a template somehow that could be extended?

**Comment by liggitt** [comment]
sure, login, token display, etc, are currently templates that we could externalize or allow overriding

**Comment by fabianofranz** [comment]
@liggitt https://github.com/openshift/origin/pull/6023 exposes the `--token` flag in `oc login --help`.

**Comment by abhaynayak24** [comment]
Any idea about how to get the token information? because `oc whoami -t` responds with `error: no token is currently in use for this session` I dont know what the issue is

**Comment by sqqqrly** [comment]
I found the token using `oc config view` and reading it from the output.
