### ISSUE TITLE
`oc types` has wrong docs about oc projects

### ISSUE THREAD

**Issue by maxandersen** [openshift/origin#4361]
docs says  `oc projects` should exist but when using it that gives:

```
$ oc projects
Error: unknown command "projects"
Run 'oc help' for usage.
```

**Comment by liggitt** [comment]
should be `oc project`... which docs reference `projects`? We should fix the docs or alias `projects` as `project`

**Comment by maxandersen** [comment]
`oc types` prints out `oc projects`

**Comment by liggitt** [comment]
This what you are referring to:
```
  // View all projects you have access to
  $ oc get projects
```

`oc get ...` accepts plural or singular versions of resource names
`oc project` is a command group that currently only accepts the singular versopm

**Comment by maxandersen** [comment]
no, i'm referring to what is in the latest release oc output:

```
Examples:
  // View all projects you have access to
  $ oc projects
````
when I run that it gives an error.

Maybe the issue is fixed in master ?

**Comment by smarterclayton** [comment]
Probably not.  Good catch

**Comment by liggitt** [comment]
Shows `oc get projects` in master

**Comment by liggitt** [comment]
fixed in master, closing
