### ISSUE TITLE
New-app `--env` flag won't add specified envVars into the deploymentConfigs

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#4363]
Specified envVars are not present in the deployment config after running:
`oc new-app examples/sample-app/application-template-stibuild.json --env=FOO=bar`

**Comment by jhadvig** [comment]
demo http://pastebin.test.redhat.com/307955

**Comment by smarterclayton** [comment]
Need to deal with conflicts between `oc new-app A=B --env="A=C"`

**Comment by jhadvig** [comment]
So it appears that the `--env` flag work only when the `new-app` generated the template, not when its instantiating the template.  

@smarterclayton regarding your comment, I guess that the envVar which is set after the new-app cmd shall have bigger priority the the flag. Or ?

**Comment by smarterclayton** [comment]
They should not be allowed to conflict - if you specify conflicting, the
command should halt with an error.

On Tue, Aug 25, 2015 at 5:09 PM, Jakub Hadvig <notifications@github.com>
wrote:

> So it appears that the --env flag work only when the new-app generated
> the template, not when its instantiating the template.
>
> @smarterclayton <https://github.com/smarterclayton> regarding your
> comment, I guess that the envVar which is set after the new-app cmd shall
> have bigger priority the the flag. Or ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4363#issuecomment-134722968>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
--env should probably apply to the template as well.  I don't want the
arguments passed (A=B vs --env=A=B) to be inconsistent.  Does new-app have
another flag for sending param to the template (like --param?).  That might
also be wrong that there is a distinction.

On Tue, Aug 25, 2015 at 6:08 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> They should not be allowed to conflict - if you specify conflicting, the
> command should halt with an error.
>
> On Tue, Aug 25, 2015 at 5:09 PM, Jakub Hadvig <notifications@github.com>
> wrote:
>
>> So it appears that the --env flag work only when the new-app generated
>> the template, not when its instantiating the template.
>>
>> @smarterclayton <https://github.com/smarterclayton> regarding your
>> comment, I guess that the envVar which is set after the new-app cmd shall
>> have bigger priority the the flag. Or ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/issues/4363#issuecomment-134722968>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by jhadvig** [comment]
@smarterclayton yep there is `--param` that sets/overrides parameter values in the template.

**Comment by smarterclayton** [comment]
@fabianofranz but I think we should collapse these.  More discussion tmrw

On Aug 25, 2015, at 6:27 PM, Jakub Hadvig <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> yep there is --param
that sets/overrides parameter values in the template.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4363#issuecomment-134746934>.

**Comment by bparees** [comment]
@jhadvig did your PR for this ever land?

**Comment by bparees** [comment]
@jhadvig bump

**Comment by bparees** [comment]
fixed
