### ISSUE TITLE
Behavior of example repo link in console create page is strange

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#4365]
The node-js example link looks like a regular link that should take you to the github page, but clicking it actually autofills the textbox above it.  The first time I used it I CTRL clicked it because i thought it was an actual link, and it opens a new web console tab.

I think we can resolve the weird usability by changing the link styling.  I'm thinking make it dashed underline and regular text color.  The dashed underline will draw the eye / mouse, hover will show its clickable, but it won't look linky since its the regular text color.  Alternatively could make it the gray metadata text color. Just not blue.

**Comment by liggitt** [comment]
or make the repo name just text with a "Try it out!" clickable link beside it
