### ISSUE TITLE
Dockerfile USER directive issue on OSE V3

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#4367]
Hi
  We have an interesting issue with "Dockerfile" using directive "USER xxxx", let's see our Dockerfile

FROM centos:7
...
...
ENV APP_HOME /opt/app
RUN mkdir $APP_HOME

RUN groupadd  java && useradd -m -g java java
...
...
RUN chown -R java:java $APP_HOME
EXPOSE 8080
USER java
WORKDIR /

ENTRYPOINT [ "/control.sh" ]
CMD [ "start" ]

If I run this Docker image on an Ubuntu server, it works properly, user "java" can create/delete file in /opt/app ($APP_HOME).

When we start the Deployment Config using this Docker image everything works OK, but now the user that starts the java process 
is not able to create files in /opt/app ($APP_HOME), doing some troubleshooting via "docker inspect f6375fc40751" we found the following things:

1- The user "USER java" is not used anymore, now the java process is using a user ID "1000080000",

2- My project annotation uid-range is "openshift.io/sa.scc.uid-range=1000080000/10000"

3- My docker image is not working as I was expecting (design originally).

Questions

1) What I can do to run the image without any permission problem ?

2) Is there any best practice or documentation about this topic, I just read "Don't use root user..." ?

3) Is possible to solve this problem without using a privileged scc ?

I would appreciate any advice.

Many thanks.

**Comment by pat2man** [comment]
By default, pods run in the restricted security context. This context randomizes the user which is probably the only way to securely run a multi tenant server.

You can add your own context that allows running as the standard java user. There is documentation here: https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html

**Comment by roldancer** [comment]
Hi @pat2man, If I change the "restricted" SCC runAsUser : RunAsAny, it works

I don't like to change the default SCC restricted object so ...
Is it possible to assign a new SCC object to a Deployment Config (DC) ? how can I do that ?

Many thanks.

**Comment by smarterclayton** [comment]
Usually you would assign your service account to the scc.

Your service account name is "system:serviceaccount:<project>:default" (the last segment is different if you set the pods service account name field).  You can add that to the "users" field of the restricted SCC.

**Comment by smarterclayton** [comment]
The comment ate it but the third segment of your service account should be the project name

**Comment by roldancer** [comment]
many thanks for the information !!!

**Comment by iatomic** [comment]
this is like INSANITY to do simple things like running a simple springboot java application. Can you post some SIMPLE Dockerfle to get it working?
