### ISSUE TITLE
The jenkins example suffers from router not properly redirecting traffic from HTTP to HTTPS

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#4378]
It seems like the router is somehow messing up with the Jenkins example we have. When you create the Jenkins example from the template and then you navigate to "jenkins.ci.router.default.svc.cluster.local" ('ci' is the project name) a login screen pops up. When you login, you're redirected from https to http. To fix it, you have to manually rewrite the URL in browser to start with "https://" (and you're logged in). This also happens on several places in Jenkins UI (Manage Jenkins, etc...)...

I saw somewhere that we should set the `X-Forwarded-Proto` header somewhere to fix this but I'm not sure where and I'm not routing expert ;-)

@bparees  @rajatchopra FYI

**Comment by bparees** [comment]
From our email thread on the topic:
here's what Jenkins has to say on the subject:
https://wiki.jenkins-ci.org/display/JENKINS/Running+Jenkins+behind+Apache

"If you'd like to run Jenkins with reverse proxy in HTTPS, one user reported that HTTPS needs to be terminated at Jenkins, not at the front-end Apache. See this e-mail thread for more discussion.

Alternatively, you can add an additional ProxyPassReverse directive to redirect non-SSL URLs generated by Jenkins to the SSL side. Assuming that your webserver is your.host.com, placing the following within the SSL virtual host definition will do the trick:"


I'm suggesting the latter is what we need here.  (the equivalent of Apache ProxyPassReverse directive for our router)

**Comment by bparees** [comment]
that's intentional, the route is setup to do edge termination.

https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-ephemeral-template.json#L55

and the reason i did it that way is, as discussed, I didn't want to deal with setting up a cert for jenkins, and doing http to the router would be totally insecure.

edge termination is also how we ran in v2 generally.  and again i'm pretty sure it worked in v2 because we rewrote the redirect, not because of any special configuration in jenkins.  but i could be wrong.

**Comment by bparees** [comment]
As of this issue[https://issues.jenkins-ci.org/browse/JENKINS-23294] it should respect X-Forwarded-Port and X-Forwarded-Proto.

Not saying we *can't* rewrite redirects but Jenkins is supposed to do the right thing here, and redirects are only part of the battle. When you create self-links in the text, or in JSON, or in calling out to an OAuth solution, or in email... fixing the redirect is not going to help you.

**Comment by mfojtik** [comment]
@bparees alternatively we can run Apache proxy for the Jenkins that can do all this translations for us. But it one extra process you need to carry to run Jenkins.

**Comment by bparees** [comment]
@mfojtik :-1:

**Comment by sosiouxme** [comment]
If you use passthrough TLS and an apache proxy, it will add these headers correctly. But the haproxy should really set the headers (at least, when it does anything but passthrough TLS).

**Comment by mfojtik** [comment]
@sosiouxme that means I have to run apache pod (or add apache into jenkins image) which is no go (see @bparees finger down ;-)

**Comment by sosiouxme** [comment]
Right, just confirming it's a workaround. The best solution is for haproxy
to get it right to begin with.

**Comment by bparees** [comment]
closing in deference to https://github.com/openshift/origin/issues/4549

**Comment by mickael-kerjean** [comment]
I'm experiencing the exact same issue with a brand new instance created on rhcloud.

![image](https://cloud.githubusercontent.com/assets/13233076/17392650/22abcbda-5a62-11e6-9bb6-26e5639293d5.png)

**Comment by bparees** [comment]
@mickael-kerjean the issue and fix were for our v3 product, it sounds like you're using v2 which is unlikely to get addressed at this point.
