### ISSUE TITLE
How to apply a default quota/limits for every new project

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#4381]
Hi All,
    I would like to know if it is possible to define a default quota and limits for new projects ?

Many thanks.

**Comment by liggitt** [comment]
You can create a custom project template that includes quota/limits. See https://docs.openshift.org/latest/admin_guide/selfprovisioned_projects.html#template-for-new-projects

**Comment by roldancer** [comment]
Hi @liggitt , thanks for the information, but I don't see any information related to quota/limits in the project template, I'm using OSE V3.0.1

apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-request
objects:
- apiVersion: v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admins
    namespace: ${PROJECT_NAME}
  roleRef:
    name: admin
  userNames:
  - ${PROJECT_ADMIN_USER}
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:${PROJECT_NAME}
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-puller
  userNames: []
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-builder
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:builder
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:deployer
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:deployer
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER

**Comment by liggitt** [comment]
right... you can add a quota/limit objects to that template, upload the template to the API, then point to your custom template in the master config, and your customized version will get used when users create new projects

**Comment by roldancer** [comment]
Hi @liggitt many thanks for the information, I have created the following template.

Question, Do you know if it is possible create differents projects template, for instance small, medium, large, and apply that kind of template size during the project creation, I mean when I execute oadm new-project ?

apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: small-project
objects:
- apiVersion: v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admins
    namespace: ${PROJECT_NAME}
  roleRef:
    name: admin
  userNames:
  - ${PROJECT_ADMIN_USER}
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:${PROJECT_NAME}
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-puller
  userNames: []
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-builder
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:builder
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:deployer
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:deployer
- apiVersion: v1
  groupNames: []
  kind: ResourceQuota
  metadata:
    name: small.project
  spec:
    hard:
      cpu: "2"
      memory: 2Gi
      pods: "10"
      replicationcontrollers: "5"
      resourcequotas: "5"
      services: "5"
  status: {}

- apiVersion: v1
  groupNames: []
  kind: LimitRange
  metadata:
    name: small-limits
  spec:
    limits:
    - max:
        cpu: "2"
        memory: 1Gi
      min:
        cpu: 200m
        memory: 500Mi
      type: Pod
    - default:
        cpu: 200m
        memory: 500Mi
      max:
        cpu: "2"
        memory: 1Gi
      min:
        cpu: 200m
        memory: 500Mi
      type: Container
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER

**Comment by liggitt** [comment]
`oadm new-project` uses the default template.

`oc new-project` and the "Create a project" UI use the custom template, if specified, and only a single template is supported.

Cluster admins can use generic templates to create projects of different sizes using `oc process ... | oc create -f -`. You can set up as many templates as you want and use `oc process` to process the templates as generic templates which happen to create projects.

**Comment by roldancer** [comment]
Hi @liggitt , many thanks for your help!!!!

**Comment by Mangirdaz** [comment]
> Cluster admins can use generic templates to create projects of different sizes using oc process ... | oc create -f -. You can set up as many templates as you want and use oc process to process the templates as generic templates which happen to create projects.

This does not work. Because resource quota object does not have ability to pass namespace in the name.  So when you do oc process template <name> | oc create -f - where is no way to set on which prioject to set quota. K8s API kas namespace in the url, not payload, so it has to hit particular API endpoint, and looks like oc create -f is not smart enough to do this,

When you do this via projectrequest, i think logic behind this handles this edge case. Bus with k8s objects and templates its tricky :)

I hope I'm wrong but if not this may end up with bug :)

**Comment by liggitt** [comment]
`oc create -f -` creates the objects in the current namespace. You can specific it explicitly with `oc create -n <namespace> -f -`

**Comment by Mangirdaz** [comment]
What if I want to do this via API? I would need to parse each object after template process and submit to each api separately?

**Comment by liggitt** [comment]
yes, that's what `oc create -f -` does (you can see yourself by passing --loglevel=8)

**Comment by Mangirdaz** [comment]
Thanks :+1:  as always MVP :) API will require more stuff but oc will do

**Comment by scheng1** [comment]
@scheng

**Comment by scheng1** [comment]
@scheng1
