### ISSUE TITLE
Deployment status

### ISSUE THREAD

**Issue by roberto-gomez** [openshift/origin#4394]
Hello.

I would like to know if there is some way to know the status of a deployment. 

I am developing a system to deploy an application in OpenShift and I need to know if the deployment has finished well and if the application is stable. I've noticed that if the pod starts and fails, OpenShift tries to restart the pod again and again and the application is not stable, but OpenShift says that the deployment finished well.

Thanks.

**Comment by mfojtik** [comment]
@roberto-gomez have you tried the `oc status` command?

**Comment by mfojtik** [comment]
@roberto-gomez you can also define post-deployment hook to verify that the application is in OK state:

https://docs.openshift.org/latest/dev_guide/deployments.html#lifecycle-hooks

**Comment by roberto-gomez** [comment]
Hi @mfojtik 

I was reading about the post-deployment hooks but I can't understand well how it works, could you show me an example about it?

**Comment by smarterclayton** [comment]
You can also add a readiness check to your pod - that check can be an HTTP get, a TCP connect, or exec a script inside your container.  If you add that, deployments won't be considered successful until your check returns "ok".  Also, you won't be added as a load balancer target until it succeeds.

**Comment by roberto-gomez** [comment]
@smarterclayton thanks for the idea.

I am looking for an example in the documentation, but I don't found it, could you show me one?

**Comment by smarterclayton** [comment]
production-pods.md
<https://github.com/kubernetes/kubernetes/blob/e366f2c597df57494c647dd5d0e99305d887b321/docs/user-guide/production-pods.md#liveness-and-readiness-probes-aka-health-checks>
is
the best one right now

On Fri, Aug 28, 2015 at 9:52 AM, Roberto Gomez <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> thanks for the idea.
>
> I am looking for an example in the documentation, but I don't found it,
> could you show me one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4394#issuecomment-135766936>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by roberto-gomez** [comment]
Thank you for the example. I tried it and works well.
