### ISSUE TITLE
Pod stuck on pending status due to hung docker daemon

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#4398]
Origin/kubernetes should detect that case when a node is not able to service request such as a hung docker daemon, terminate the execution after some period of time and log an event/message. It would also be good if it attempted to launch the pod on a different healthy node.

I hit this issue recently with an instance that had been running for about a month. Things were working fine for a couple weeks.

/version reveals:
  "gitVersion": "v0.17.1-804-g496be63",
  "gitCommit": "496be63",

**Comment by smarterclayton** [comment]
Open an upstream issue please

**Comment by ncdc** [comment]
Let's plan to close this once we rebase in Kube 1.3.x, as the upstream issue has been closed for 1.3.

**Comment by soltysh** [comment]
@mfojtik this should be closed with yours or the next rebase, just fyi.
