### ISSUE TITLE
Feature Request - how do I know what commands are running inside a pod/container?

### ISSUE THREAD

**Issue by rettori** [openshift/origin#4399]
Show the command on the pod window?
java...
httpd...
node...

**Comment by smarterclayton** [comment]
It might be good if pod describe showed the command and args.  This is an upstream issue if they don't.  It should be possible to see from the console too in details.

**Comment by rettori** [comment]
This came in during the OSRoadshow in Montreal.

**Comment by smarterclayton** [comment]
This has been fixed if the user specified.  The image default is not shown.
