### ISSUE TITLE
Nav bar layout problems when resizing browser window

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4404]
When I size the browser narrow, wide, and then narrow, the toolbar icons are below the dropdown instead of beside it. @sg00dwin @jwforres 

<img width="482" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/9546953/b78afe76-4d64-11e5-9f86-1f7e407194c3.png">

**Comment by spadgett** [comment]
The filter widget always somehow disappeared on me as well. Notice that the Add to Project button is where filter should be. When I refreshed the page, filter came back.

<img width="948" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/9546998/14389390-4d65-11e5-92bf-3e3ff7f7ed0b.png">

I saw this once as well:

<img width="333" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/9547029/51cce710-4d65-11e5-8590-e572787e9f51.png">

**Comment by jwforres** [comment]
Yeah i think we knew about these but weren't too worried about them since most people are not going to be shrinking their browser window all the way down to mobile size and back.

**Comment by spadgett** [comment]
I'm not sure it's that uncommon since the breakpoint is 768px, which isn't really that small. I hit a problem almost immediately just resizing the window larger. The filter disappears.

**Comment by spadgett** [comment]
I've played this more. There are problems anytime you resize past the 768px breakpoint. You don't have to go back.

* Starting at 800px, resizing to 600px: the toolbar buttons stop working. You can't click them.
* Starting at 600px, resizing to 800px: the filter disappears.

It's not just layout problems, things stop working. I think this should be higher priority.

**Comment by jwforres** [comment]
Fixed
