### ISSUE TITLE
'oc types' is missing *builds* and *events*

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#4405]
The output for the `oc types` command is missing definitions for "builds" and "events". It also seems extraneous to have concept definitions in the output of this command.

Also the first example does not work:

```
  // View all projects you have access to
  $ oc projects
```

should be

```
  // View all projects you have access to
  $ oc get projects
```

**Comment by liggitt** [comment]
on master:
```
Examples:
  // View all projects you have access to
  $ oc get projects
```

**Comment by deads2k** [comment]
Do we want to keep this command as is or do we want to use something like https://github.com/kubernetes/kubernetes/pull/12677 instead?

**Comment by sspeiche** [comment]
I learned I get what I *almost* want (expected) from `oc get types` if I just do:

```
$ oc get

You must specify the type of resource to get. Valid resource types include:
   * componentStatuses (aka 'cs')
   * endpoints (aka 'ep')
   * events (aka 'ev')
   * limits
   * namespaces
   * nodes (aka 'no')
   * persistentVolumeClaims (aka 'pvc')
   * persistentVolumes (aka 'pv')
   * pods (aka 'po')
   * podTemplates
   * quota
   * replicationcontrollers (aka 'rc')
   * secrets
   * serviceAccounts
   * services
```

Still missing `builds`, `buildConfig`, `deploymentConfig`, ...

In other words, I'd expect an end user to want a concise list of things they can type with a short description. It would be preferable that `oc get types` look like the above + short (less than one line) description and the current `oc get types` tag an additional flag such as `--verbose` to give me more complete descriptions.

**Comment by kargakis** [comment]
Unfortunately that `oc get` message is hardcoded from upstream and there is no way currently to override it. I think as @deads2k mentioned, we probably want to use the `explain` command.

**Comment by kargakis** [comment]
Btw, the issue about `oc get`: https://github.com/openshift/origin/issues/3981

**Comment by sspeiche** [comment]
Not being able to fix `oc get` and adding yet another command would not be a very good user experience . The end user will get lost in whether they need to do `oc get`, `oc types`, `oc describe`, `oc explain`, `oc show`, `oc info`, `oc inspect` (ok, I made the last 3 up but you see where I'm going, git and docker have similar concepts but user may have to remember all of them).

I think we probably want to fix the get command upstream as well.

**Comment by kargakis** [comment]
https://github.com/openshift/origin/pull/5063 temporarily fixes the `oc get` issue.

**Comment by kargakis** [comment]
Regarding `oc types` and `oc explain` I think we should drop the former for the latter.
