### ISSUE TITLE
No Help in Build Logs

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin#4427]
I just pulled down the latest binary and followed all the steps I did before to get the sample application working.  However, this time, the build fails right away.  I get no help from the build log:

./oc build-logs ruby-sample-build-1
F0831 03:41:01.134580       1 builder.go:47] Build error: exit status 128

That's it.  There is no other information.  How do I find the cause of the problem?

**Comment by soltysh** [comment]
You can start with increasing your build log, define `BUILD_LOGLEVEL` env variable in your BuildConfig as described [here](https://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs) and set it to 5.

**Comment by mfojtik** [comment]
Since we are just forwarding the error from `Build()` my best guess would be this has something to do with `git` command that S2I is invoking.

**Comment by soltysh** [comment]
If that's the case, we should make it more verbose than above.

**Comment by jhadvig** [comment]
maybe it would be good to add this info to the build-logs help ?

**Comment by deanpeterson** [comment]
Thanks, increasing the build log level confirmed it was a git error caused by the docker daemon not being able to reach the internet.  I followed the advice <a href="https://github.com/openshift/origin/issues/1536">here</a> and restarted docker.
