### ISSUE TITLE
`oc secrets new-dockercfg` is not taking params from .dockercfg if passed as agrument

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#4430]
`oc secrets new-dockercfg /path/to/.dockercfg` 
should be similar to 
`oc secrets new-dockercfg --docker-username=... --docker-password=... --docker-mail=...`
but passing only the `.dockercfg` is not working.

**Comment by liggitt** [comment]
`oc secrets new my-secret /path/to/.dockercfg` does what you want. `new-dockercfg` is for creating one out of thin air. `new-dockercfg` should error since additional args aren't supported

**Comment by jhadvig** [comment]
@liggitt but in the `--help` we are telling user that he can also create dockercfg secret just by passing path to local `.dockercfg`, which would make sense.

https://github.com/openshift/origin/blob/master/pkg/cmd/cli/secrets/dockercfg.go#L40-L42

**Comment by jhadvig** [comment]
Also why shouldn't we support additional args ?

**Comment by liggitt** [comment]
`oc secret new` already does what you want, we should direct people to that

**Comment by jhadvig** [comment]
@liggitt ok I see your point, but shouldn't the `oc secrets new-dockercfg` also have that option. I would expect that the `new-dockercfg` would have this option to create (only) the dockercfg secrets and the `oc secrets new` would create any type of secret.
Also the `oc secrets new` is not providing validation if all the necessary params (in case of dockercfg - user/pw/registry-addr/mail) are present in the `.dockercfg`

**Comment by liggitt** [comment]
`oc secrets new` just adds the file content, and sets the type according to the name of file. I'm not sure we want to get in the business of validating file content client side... if it's invalid, it'll fail when you use it

**Comment by jhadvig** [comment]
@liggitt well I think that when you are creating the .dockercfg from a file we do wanna have at least some basic validation, whether all needed params are present. or ?

**Comment by jhadvig** [comment]
nm regarding the validation, I think I see the point and we dont wanna go there.

Regarding the `oc secrets new-dockercfg`. Is the way how to create and secret from file the `oc secrets new ..` ? If so I will remove the lines that refer that `oc secrets new-dockerfcg` can create from file.

**Comment by liggitt** [comment]
yup, `new-dockercfg` lets you provide the individual values and we combine it into a json dockercfg file. `new` lets you create a secret from any existing file

**Comment by jhadvig** [comment]
@liggitt the change was merged. We can close this one, unless anything else is not needed.
