### ISSUE TITLE
Rebase issues

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#4434]
A couple of things to take into account for the next rebase:

1) code.google imports in our dependencies - godep yells about them

`code.google.com/p/go-uuid/uuid`
Used by [docker/distribution](https://github.com/openshift/origin/issues/4339). We either have to bump it or most probably carry a patch on it that will use the [other duplicate package](https://github.com/openshift/origin/tree/master/Godeps/_workspace/src/github.com/pborman/uuid) we already have in our deps.

`code.google.com/p/gogoprotobuf/proto`
Used by etcd, already replaced in both etcd and Kubernetes.

 `code.google.com/p/gcfg`
Here is the PR removing it from Kube: https://github.com/kubernetes/kubernetes/pull/12227

2) The whole `k8s.io/kubernetes/pkg/client` directory has been moved under `k8s.io/kubernetes/pkg/client/unversioned`. Unfortunately it's a series of commits:
* https://github.com/kubernetes/kubernetes/commit/2a17dbff130cdad7543d24b4cac7d87a606cced5
* https://github.com/kubernetes/kubernetes/commit/7ba5b058cca6dc9b149db854171dc9be0ad9be44
* https://github.com/kubernetes/kubernetes/commit/9cea046f426e9ec6c6ebb34ece68fe4c2a097aeb
* https://github.com/kubernetes/kubernetes/commit/ae6c64d9bbfbd96ad14cf5a366f7994fe4c3da96

which makes it very difficult to backport them into Origin as they rely upon a handful of other commits that are not included into our Kube godeps. I'm going to catalog all of them if I manage to get to them. Maybe just replacing the imports is a workaround (?) :
```
$ find pkg/ -type f | xargs sed -i -e 's#kubernetes/pkg/client#kubernetes/pkg/client/unversioned#g'
$ find test/ -type f | xargs sed -i -e 's#kubernetes/pkg/client#kubernetes/pkg/client/unversioned#g'
$ find plugins/ -type f | xargs sed -i -e 's#kubernetes/pkg/client#kubernetes/pkg/client/unversioned#g'
```

3) Continue carrying [v1beta3](https://github.com/openshift/origin/commit/31d8f4a5178e67c4d27fa8ac49f8921ff66d0ce3) and [SCC](https://github.com/openshift/origin/commit/87cead531d4bea61313c1f37234f0e0767512e4d). Mentioning these because `godep save` complains about them. 

4) No need to run `NamespaceExists` as it's merged into the `NamespaceLifecycle` controller: https://github.com/kubernetes/kubernetes/pull/12605 / https://github.com/kubernetes/kubernetes/pull/13390

Please let me know of any other Kube issues I am missing that need to be documented here.

@smarterclayton @pweil- @liggitt @deads2k

**Comment by kargakis** [comment]
`client/unversioned/cache` and `client/unversioned/record` are being moved back in the client direcotry: https://github.com/kubernetes/kubernetes/pull/13341 and https://github.com/kubernetes/kubernetes/pull/13342

**Comment by liggitt** [comment]
kubectl create/replace commands added verification based on fetching the swagger spec. this happens for every invocation (which has performance implications) and will need work to enable for origin types

**Comment by smarterclayton** [comment]
We disable the validator today, I think we'd keep that (and because it's
dumb)

On Sep 10, 2015, at 3:31 PM, Jordan Liggitt <notifications@github.com>
wrote:

kubectl create/replace commands added verification based on fetching the
swagger spec. this happens for every invocation (which has performance
implications) and will need work to enable for origin types

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4434#issuecomment-139354687>.

**Comment by stefwalter** [comment]
Heads up, found (at least) three regressions in kubernetes upstream. Ideally openshift shouldn't have these same regressions after a rebase:

 * https://github.com/kubernetes/kubernetes/issues/13812
 * https://github.com/kubernetes/kubernetes/issues/13811
 * https://github.com/kubernetes/kubernetes/issues/13809

**Comment by kargakis** [comment]
@stefwalter I already have started rebasing (https://github.com/openshift/origin/pull/4663) so we will need to carry fixes for these regressions (I see a couple of them already in PRs but none merged) until the next (next) rebase. Thanks for the info!

**Comment by YannMoisan** [comment]
Is there a workaround ?
I'm stuck with this error :
```
godep restore -v ./...
godep: unable to detect version control system for code.google.com/ path
```

**Comment by kargakis** [comment]
@YannMoisan remove the code.google protobuf library from Godeps.json
