### ISSUE TITLE
oc exec / rsh hangs for a long time on exit

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#4445]
After exiting an interactive shell session in a pod, the terminal hangs for several seconds before I can type anything back in the host.

```
[vagrant@openshiftdev origin]$ oc get pods
NAME            READY     STATUS    RESTARTS   AGE
mysql-3-9zgou   1/1       Running   0          3m
[vagrant@openshiftdev origin]$ time oc rsh mysql-3-9zgou
bash-4.2$ exit
real    0m29.163s
user    0m0.431s
sys     0m0.110s
```

Same for other pods, e.g., `docker-registry`.

(@mfojtik FYI)

**Comment by mfojtik** [comment]
CC @ncdc 

I experiencing the same... After I exit from the `/bin/bash` session (`oc exec -it foo /bin/bash`) the terminal hangs for couple seconds.

**Comment by liggitt** [comment]
known issue tracked in https://github.com/kubernetes/kubernetes/issues/13395 and being worked on
