### ISSUE TITLE
rolebindings are hard to use in a template

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4449]
RoleBindings are virtual objects that actually contain the data used to drive the authorizer.  The most common usage inside of a template is, "I want to add this role to that subject".  That is very difficult since patches aren't first class API objects.

We could create a subresource "AddRoleToUser" or some such that contains a `RoleRef` and a `Subjects` list, but it's not obvious where that subresource would live.

@smarterclayton @liggitt comments?

**Comment by smarterclayton** [comment]
Hrm - to me RoleBindings are intended to be that addroletouser.  Their
internal workings are less important to me than the practical surface area
to end users.  This may be what we discussed this morning, but it's
probably less important to me to have exact resource parity in POST /
DELETE, but instead to map to the logical operation end users want/need.

ADD user TO role - POST /rolebindings
REMOVE user FROM project - DELETE ??
RESET/REDUCE user TO effective role - PUT ??
GET user's EFFECTIVE role ON project - GET ??

Those are the four most common client actions regarding my interaction (I
want to grant someone at least this role, I want to remove someone from
every role, I want to ensure the user has no more than X permissions, and I
want to see what their max role surface area is).  Those are the primitives
that folks should be making API calls against.  We should preserve
flexibility (you can have two roles that don't exactly overlap) but the end
user *must* be able to trust the system makes those changes (not more
primitive ones that could end up with the user still having some admin
role).


On Tue, Sep 1, 2015 at 10:18 AM, David Eads <notifications@github.com>
wrote:

> RoleBindings are virtual objects that actually contain the data used to
> drive the authorizer. The most common usage inside of a template is, "I
> want to add this role to that subject". That is very difficult since
> patches aren't first class API objects.
>
> We could create a subresource "AddRoleToUser" or some such that contains a
> RoleRef and a Subjects list, but it's not obvious where that subresource
> would live.
>
> @smarterclayton <https://github.com/smarterclayton> @liggitt
> <https://github.com/liggitt> comments?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4449>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
Ignoring the argument over names, where would this live?  A top level namespaced resource?  That seems like the easiest option, though the GET wouldn't fit very well.




> ADD **subjects** TO role - POST /rolebindings

Agree

> REMOVE **subjects** FROM project - DELETE ??

I could see the case for "remove entirely", but I think we should support "remove from role" as well.

> RESET/REDUCE **subjects** TO effective role - PUT ??

I'm not sold on this.  I don't think people would expect the behavior they'd get.

> GET **subject's** EFFECTIVE role ON project - GET ??

The result of that would either return multiple roles (perhaps not very useful) or a list of policy rules (perhaps hard to read).  Maybe we could return both.

**Comment by smarterclayton** [comment]
On Sep 2, 2015, at 8:05 AM, David Eads <notifications@github.com> wrote:

Ignoring the argument over names, where would this live? A top level
namespaced resource?



Maybe.


That seems like the easiest option, though the GET wouldn't fit very well.

ADD *subjects* TO role - POST /rolebindings

Agree

REMOVE *subjects* FROM project - DELETE ??

I could see the case for "remove entirely", but I think we should support
"remove from role" as well.



I don't think it's as common as you expect.


RESET/REDUCE *subjects* TO effective role - PUT ??

I'm not sold on this. I don't think people would expect the behavior they'd
get.


You mean, after they run it the user is guaranteed to have no more than
"edit"?  That's *exactly* what users expect when they tell the system to
change a role.  If you accept "update to have edit" but the user actually
still has admin, you've just conducted a social engineering attack on the
admin.

GET *subject's* EFFECTIVE role ON project - GET ??

The result of that would either return multiple roles (perhaps not very
useful) or a list of policy rules (perhaps hard to read). Maybe we could
return both.


Probably two modes - displaying roles to user is the first step (when non
overlapping).

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4449#issuecomment-137048710>.

**Comment by liggitt** [comment]
"Force to role" and "Add/remove role" are distinct cases. In v2, roles were ascending and fully overlapping. In v3, that is not necessarily the case. I would be annoyed if I added a role to someone and it removed all other roles I had assigned them.

**Comment by smarterclayton** [comment]
I think the primary action a naive project admin have will almost always be
"force to role".  The first time you surprise them with overlapping roles
you have created a serious issue.

On Wed, Sep 2, 2015 at 10:51 AM, Jordan Liggitt <notifications@github.com>
wrote:

> "Force to role" and "Add/remove role" are distinct cases. In v2, roles
> were ascending and fully overlapping. In v3, that is not necessarily the
> case. I would be annoyed if I added a role to someone and it removed all
> other roles I had assigned them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4449#issuecomment-137110926>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment]
set-role and add-role are different

**Comment by smarterclayton** [comment]
Yes.  100% of project admins need add-role.  95% of admins want remote user
from project totally.  10% of admins want set-role.  0.000005% of admins
want "remove this role that mostly overlaps with another role you already
have but you don't realize that so you think you're safe but really they're
still an admin"

On Wed, Sep 2, 2015 at 1:29 PM, Jordan Liggitt <notifications@github.com>
wrote:

> set-role and add-role are different
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4449#issuecomment-137180133>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by simo5** [comment]
I think this should be now covered by oc auth reconcile and the new RBAC stuff.
Please reopen if not,
