### ISSUE TITLE
Unexpected webhook url pattern

### ISSUE THREAD

**Issue by fbricon** [openshift/origin#4458]
Creating apps on a bunch of servers running OS3 v1, I noticed the webhooks the web console shows are of the form:
https://api.xxx.openshift.com/osapi/v1beta3/namespaces/ks/buildconfigs/eap-app/webhooks/mar2jBvT/github

The java rest client @jcantrill is working on generates urls following the actual OS version, i.e:
https://console.xxx.openshift.com/oapi/v1/namespaces/ks/buildconfigs/eap-app/webhooks/mar2jbvt/github

Turns out only the v1beta3 url work. Still, this seems unexpected. So the question is:
- should openshift servers use a v1 based webhook url
or
- should the java rest client be "fixed" to use v1beta3 urls instead of v1 when computing webhooks?

**Comment by liggitt** [comment]
the v1 pattern should work

**Comment by liggitt** [comment]
although... are you sure it isn't working? there's an integration test that exercises the v1 webhook:
https://github.com/openshift/origin/blob/master/test/integration/webhookgithub_test.go#L102

**Comment by maxandersen** [comment]
bigger question to me is why the api apparently returns two different results dependent on where it is used/called from. i.e. why do we get v1 but the console gets v3beta1 ?

**Comment by jcantrill** [comment]
Would really be nice if the server returned the webhook instead of the
clients needing to build them.  Something we should do as an annotation?

On Wed, Sep 2, 2015 at 2:48 AM, Max Rydahl Andersen <
notifications@github.com> wrote:

> bigger question to me is why the api apparently returns two different
> results dependent on where it is used/called from. i.e. why do we get v1
> but the console gets v3beta1 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4458#issuecomment-136954615>.
>



-- 
--
Jeff Cantrill
Senior Software Engineer, Red Hat Engineering
Red Hat, Inc.
*Office*: 703-748-4420 | 866-546-8970 ext. 8162420
jcantril@redhat.com
http://www.redhat.com

**Comment by fbricon** [comment]
@liggitt when using the v1 webhook, in this case https://console.xxx.openshift.com/oapi/v1/namespaces/fred/buildconfigs/cakephp-example/webhooks/apbh7tobprv1vyiqpbn4vsmq44hl60aede2imbbb/github, I get:
![](http://content.screencast.com/users/fbricon/folders/Jing/media/e29a31aa-8506-4066-bb29-bedb01b47b4f/00000172.png)

I have the same error if I use https://api.xxx.openshift.com/oapi/v1/... instead

**Comment by fbricon** [comment]
so I noticed the secret was all lower case in the webhook generated by the java client. But it doesn't change anything. Really using v1 instead of v1beta3 in the url is what breaks.

**Comment by liggitt** [comment]
The webhooks listed in the UI are working for me:
```
$ curl -X POST https://localhost:8443/oapi/v1/namespaces/te/buildconfigs/nodejs-ex/webhooks/94b7e5e6dc1d9a98/generic -v
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /home/jliggitt/go/src/github.com/openshift/origin/openshift.local.config/master/ca.crt
  CApath: none
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
* 	subject: CN=10.3.112.16
* 	start date: Sep 05 01:06:34 2015 GMT
* 	expire date: Sep 04 01:06:35 2016 GMT
* 	common name: 10.3.112.16
* 	issuer: CN=openshift-signer@1441155016
> POST /oapi/v1/namespaces/te/buildconfigs/nodejs-ex/webhooks/94b7e5e6dc1d9a98/generic HTTP/1.1
> User-Agent: curl/7.37.0
> Host: localhost:8443
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-store
< Date: Sat, 05 Sep 2015 01:17:15 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
```
and a build started correctly

github makes it past authentication, though I don't have a github payload handy:
```
$ curl -X POST -v -H "Content-Type: application/json" https://localhost:8443/oapi/v1/namespaces/te/buildconfigs/nodejs-ex/webhooks/2666868e9132ff08/github 
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /home/jliggitt/go/src/github.com/openshift/origin/openshift.local.config/master/ca.crt
  CApath: none
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
* 	subject: CN=10.3.112.16
* 	start date: Sep 05 01:06:34 2015 GMT
* 	expire date: Sep 04 01:06:35 2016 GMT
* 	common name: 10.3.112.16
* 	issuer: CN=openshift-signer@1441155016
> POST /oapi/v1/namespaces/te/buildconfigs/nodejs-ex/webhooks/2666868e9132ff08/github HTTP/1.1
> User-Agent: curl/7.37.0
> Host: localhost:8443
> Accept: */*
> Content-Type: application/json
> 
< HTTP/1.1 500 Internal Server Error
< Cache-Control: no-store
< Content-Type: application/json
< Date: Sat, 05 Sep 2015 01:19:18 GMT
< Content-Length: 353
< 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Internal error occurred: hook failed: Missing X-GitHub-Event or X-Gogs-Event",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "hook failed: Missing X-GitHub-Event or X-Gogs-Event"
      }
    ]
  },
  "code": 500
```

**Comment by fbricon** [comment]
Can you try with projects on the engint or qe platforms?

**Comment by liggitt** [comment]
worked fine on the engint environment for me

**Comment by liggitt** [comment]
closing as this is working against master and in all the environments I tried... please reopen with recreation steps if you still see it happening

**Comment by fbricon** [comment]
So turns out the issue was caused by the rest client lower-casing the secret in the url, making it invalid. This has been fixed in https://github.com/openshift/openshift-restclient-java/commit/411668022c0de303bad3cfa943af8340beb22087
