### ISSUE TITLE
Test failure -- "gave up waiting" for database pod

### ISSUE THREAD

**Issue by markturansky** [openshift/origin#4468]
Chronic test failure.  All database related container logs appear fine.  MySQL successfully shuts down in the ones I looked at.

@deads2k 

> Now using project "test" on server "https://172.18.4.57:8443".
e2e-user
[INFO] Applying STI application config
service "frontend" created
route "route-edge" created
imagestream "origin-ruby-sample" created
imagestream "ruby-20-centos7" created
buildconfig "ruby-sample-build" created
deploymentconfig "frontend" created
service "database" created
deploymentconfig "database" created
[INFO] Starting build from /tmp/origin/e2e/logs/stiAppConfig.json and streaming its logs...
[INFO] Waiting for test namespace build to start
[INFO] Waiting for command to finish: 'oc get -n test builds | grep -i running'...
ruby-sample-build-1   Source    Running   ruby-sample-build-1-build
[INFO] Success running command: 'oc get -n test builds | grep -i running' after 2 seconds
[INFO] Build ruby-sample-build-1 started
[INFO] Waiting for test namespace build to complete
[INFO] Waiting for command to finish: 'oc get -n test builds | grep -i complete'...
ruby-sample-build-1   Source    Complete   ruby-sample-build-1-build
[INFO] Success running command: 'oc get -n test builds | grep -i complete' after 81 seconds
[INFO] Build ruby-sample-build-1 finished
[INFO] Waiting for app in namespace test
[INFO] Waiting for database pod to start
[INFO] Waiting for command to finish: 'oc get -n test pods -l name=database | grep -i Running'...
[ ERR] Gave up waiting for: 'oc get -n test pods -l name=database | grep -i Running'
[FAIL] !!!!! Test Failed !!!!

**Comment by deads2k** [comment]
This was happening when we were having chronic docker problems.  Have you seen this recently @liggitt ?  (Mark works mostly in kube)

**Comment by liggitt** [comment]
No

**Comment by liggitt** [comment]
closing since it hasn't been seen in a month, likely docker-related
