### ISSUE TITLE
BuildConfig with Docker strategy should pass ENV to Dockerfile

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#4470]
We should stick the env variables from the BuildConfig directly after the FROM statement of the provided Dockerfile.
If the Dockerfile itself also defines those env vars, so be it.

cc @bparees @mfojtik

**Comment by bparees** [comment]
@rhcarvalho thanks.  please make sure this doc gets updated too: https://docs.openshift.org/latest/dev_guide/builds.html#configuring-the-source-environment

it needs to be refactored into "environment for s2i builds" vs "environment for docker type builds" vs "environment for custom type builds"

**Comment by bparees** [comment]
(which means probably moving the content into sections like this: https://docs.openshift.org/latest/dev_guide/builds.html#docker-strategy-options)

**Comment by bparees** [comment]
> (12:20:52 PM) jhadvig: bparees, regarding the inconsistency in our api doc for the buildStrategy env.. are you doing that ? just asking so we wont do the same work

@jhadvig: @rhcarvalho will be doing it here.

**Comment by rhcarvalho** [comment]
@bparees we discussed last week that we'll be adding the new environment variables right after the FROM line, so that the Dockerfile could potentially use variables defined during build. What should be the behavior when the Dockerfile contains multiple FROM lines?

**Comment by bparees** [comment]
put it after the last FROM?

i'm not even sure what docker's behavior is when you have multiple FROM commands?  what actually happens in terms of what ends up in your image?

**Comment by rhcarvalho** [comment]
@bparees from http://docs.docker.com/reference/builder/#from:

> FROM can appear multiple times within a single Dockerfile in order to create multiple images. Simply make a note of the last image ID output by the commit before each new FROM command.

I think we don't really support that in OpenShift, as we can only specify a single build output. We might need to write some documentation clarifying what happens, probably near where we talk about the labels we add.

**Comment by bparees** [comment]
that is silly :)

so it's a way to have multiple Dockerfiles without having multiple files, basically.

yeah, i stand by what i said then, append it after the last FROM

**Comment by rhcarvalho** [comment]
Update: since it doesn't add any complexity to us and for consistency, we'll be adding an ENV instruction after every FROM in the Dockerfile.

**Comment by rhcarvalho** [comment]
Docs PR: https://github.com/openshift/openshift-docs/pull/982

@bparees FYI ^^
