### ISSUE TITLE
Deployment Pods Don't Have Jolokia Connect Link

### ISSUE THREAD

**Issue by pat2man** [openshift/origin#4474]
When creating a pod that is part of a deployment the jolokia `Connect` link doesn't appear.

Exporting a pod that is part of a deployment and then importing it causes the `Connect` link to appear.

**Comment by pat2man** [comment]
Example pods: ```apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/created-by: '{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"test","name":"play-originv3-test-1","uid":"3c39d0a4-5105-11e5-8662-0684a0c1e17d","apiVersion":"v1","resourceVersion":"136467"}}'
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: play-originv3-test
      openshift.io/deployment.name: play-originv3-test-1
      openshift.io/scc: restricted
    creationTimestamp: null
    generateName: play-originv3-test-1-
    labels:
      deployment: play-originv3-test-1
      deploymentconfig: play-originv3-test
  spec:
    containers:
    - image: 172.30.62.175:5000/test/play-originv3-test@sha256:8e62b4e847ec091780efe37b08543588d62f49c241381ce418f91f50064fdfea
      imagePullPolicy: Always
      name: play-originv3-test
      ports:
      - containerPort: 9000
        protocol: TCP
      - containerPort: 8778
        name: jolokia
        protocol: TCP
      resources: {}
      securityContext:
        privileged: false
        seLinuxOptions:
          level: s0:c7,c4
      terminationMessagePath: /dev/termination-log
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-pxmtp
        readOnly: true
    dnsPolicy: ClusterFirst
    host: ip-10-0-0-75.ec2.internal
    imagePullSecrets:
    - name: default-dockercfg-5mrrp
    nodeName: ip-10-0-0-75.ec2.internal
    restartPolicy: Always
    serviceAccount: default
    serviceAccountName: default
    volumes:
    - name: default-token-pxmtp
      secret:
        secretName: default-token-pxmtp
  status:
    phase: Pending
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: restricted
    creationTimestamp: null
    generateName: jolokia-test-
  spec:
    containers:
    - image: 172.30.62.175:5000/test/play-originv3-test@sha256:8e62b4e847ec091780efe37b08543588d62f49c241381ce418f91f50064fdfea
      imagePullPolicy: Always
      name: play-originv3-test
      ports:
      - containerPort: 9000
        protocol: TCP
      - containerPort: 8778
        name: jolokia
        protocol: TCP
      resources: {}
      securityContext:
        privileged: false
        seLinuxOptions:
          level: s0:c7,c4
      terminationMessagePath: /dev/termination-log
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-pxmtp
        readOnly: true
    dnsPolicy: ClusterFirst
    host: ip-10-0-0-188.ec2.internal
    imagePullSecrets:
    - name: default-dockercfg-5mrrp
    nodeName: ip-10-0-0-188.ec2.internal
    restartPolicy: Always
    serviceAccount: default
    serviceAccountName: default
    volumes:
    - name: default-token-pxmtp
      secret:
        secretName: default-token-pxmtp
  status:
    phase: Pending
kind: List
metadata: {}```

**Comment by pat2man** [comment]
Screenshot:

![screen shot 2015-09-02 at 10 35 39 am 1](https://cloud.githubusercontent.com/assets/182580/9638967/5ea7bada-515e-11e5-9bfc-22962b36fad9.png)

**Comment by liggitt** [comment]
pods inside deployments render the template separately from the pod. standalone pods use the same object for both, which is why the port appears there.

**Comment by liggitt** [comment]
@benjaminapetersen this is part of what we want to look at for the extension point improvements

**Comment by pat2man** [comment]
Ah makes sense. So really the Connect link needs to be moved.

**Comment by jwforres** [comment]
@ajacobs21e the current location of the connect link doesn't work for deployments where you will have multiple pods, because when you connect you are connecting to the container within a specific pod.  We need to brainstorm a better place to have the connect link.

One option would be to move it into the details pane. So after you click on the pod you see a connect link show up with the container in the Containers section.

We need to make sure we have a connect link on the individual pod page as well though.  Now that we collapse the pods on the overview you won't always be able to get to a pod from the overview.

**Comment by liggitt** [comment]
+1 for individual pod page (and details sidebar if possible, though I know we have extension point injection difficulties there)

**Comment by gashcrumb** [comment]
maybe for the details sidebar just using fairly descriptive class names or IDs would work well enough, as then it should be possible to just use a plain angular directive to add/change content for an item in there...

**Comment by benjaminapetersen** [comment]
@jwforres if this now has a `priority/P1` tag && 1.1.0 milestone, I should put the extension point work back on high priority, correct?

**Comment by jwforres** [comment]
Not necessarily. This was already using the existing extension point stuff.
I think was just need to move the directive to a different place for now.

**Comment by ajacobs21e** [comment]
@jwforres I hadn't seen the screenshot Pat posted before. Are build & source clickable links? Putting links in the details sidebar are easier click targets and there won't be confusion with a user trying to click on the pod, etc, object. 

Most of this doc is outdated but check out slides 4, 14, and 15: https://drive.google.com/open?id=0BxppHkjprXoJeHhnMXZ3ZDZzb3c Those are some concepts I proposed for connecting to multiple containers. It's an extra click to open the details pane but I think it gives us more room to have links to other objects from there.

**Comment by gashcrumb** [comment]
With the changes to the overview and the addition of a separate pod detail page I don't think this bug is applicable any more.  The connect link should be available in the pod detail page in the corresponding container that advertises a "jolokia" port.

**Comment by pat2man** [comment]
I agree.
