### ISSUE TITLE
CLI is missing auto-completion for `oc get rc`

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4479]
`oc get replicationcontroller` correctly auto-completes.
`oc get rc` does not.

**Comment by nak3** [comment]
This behavior is same with kubernetes's. (`kubectl get rc <tab>` also doen't complete.) 

By adding 'rc' to `must_have_one_noun` list (https://github.com/openshift/origin/blob/9b11c486a5ee10a3bbf1dc0412b5e5a2feb9cd0f/rel-eng/completions/bash/oc#L606-L652), it will work.
However, I don't have good idea the way to modify the auto-generation.

**Comment by fabianofranz** [comment]
Thinking about this, I'm not confident (nor contradicted) it's a good idea. You would have different items in the same list that mean the same thing, but not for every resource. Also, the short form is, well, short (so no much point in completing it). 

```
$ oc get ^|
build
buildconfig
bc 
clusternetwork
(...)
```

Maybe we should just leave completions of resource names with the long form, seems cleaner. If you don't *know* about `rc` already, probably displaying `rc` in the list would not give you any new clue.

```
$ oc get ^|
build                          deployment                     imagestream                    node                           policy                         securitycontextconstraints
buildconfig                    deploymentconfig               imagestreamimage               oauthaccesstoken               policybinding                  service
clusternetwork                 endpoints                      imagestreamtag                 oauthauthorizetoken            project                        serviceaccount
clusterpolicy                  event                          ingress                        oauthclient                    replicationcontroller          template
clusterpolicybinding           group                          ispersonalsubjectaccessreview  oauthclientauthorization       resourcequota                  thirdpartyresource
clusterrole                    horizontalpodautoscaler        job                            persistentvolume               role                           user
clusterrolebinding             hostsubnet                     limitrange                     persistentvolumeclaim          rolebinding                    useridentitymapping
componentstatus                identity                       namespace                      pod                            route                          
daemonset                      image                          netnamespace                   podtemplate                    secret                         
```

**Comment by stevekuznetsov** [comment]
I don't quite care about whether or not `rc` is displayed for `oc get`. I *would* however, very much enjoy *not* having to type `replicationcontroller` to get the auto-completion. As we generate a lot of names for our objects, it is very nice to be able to forget about which alphanumeric suffix I am trying to type out ...

**Comment by nak3** [comment]
cobra started to support `argAliases`, and it will fix this issue. - ref. [bash_completions.md](https://github.com/spf13/cobra/blob/master/bash_completions.md#plural-form-and-shortcuts-for-nouns)

upstream fixed some of commands like `get`, `delete`, `edit` and so on as below.
https://github.com/kubernetes/kubernetes/pull/23262/commits/7e0bb885f14cfc248fcbe301dfe6c64690094ec9
https://github.com/kubernetes/kubernetes/pull/23798

**Comment by smarterclayton** [comment]
Closing due to age.
