### ISSUE TITLE
Create 'origin' user via rpm scriptlet during master installation

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#4487]
Feel free to assign this to me

**Comment by sdodson** [comment]
My vote is to name the user 'origin' as it matches /etc/origin and /var/lib/origin which are used by both origin and downstream projects but others may have differing opinions.

- [ ] create user via scriptlet
- [ ] change file ownership in specfile where appropriate

**Comment by detiber** [comment]
I'd rather see us get a reserved uid/gid (will need to get it reserved in fedora before we can reserve it in RHEL).  autogenerating the uid/gid will potentially lead to issues in clustered installations.

**Comment by sdodson** [comment]
Ok, I'll start looking into that.

**Comment by brenton** [comment]
@sdodson, is this still needed?

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
