### ISSUE TITLE
Whitespace is not removed from precompiled Angular templates

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4488]
We have a rule to run `htmlmin` on these. For some reason, leading whitespace is not being removed.

/cc @jwforres

**Comment by jwforres** [comment]
The side effect of this just being that the minimized file is bigger than it could be?

**Comment by spadgett** [comment]
> The side effect of this just being that the minimized file is bigger than it could be?

Yes.

**Comment by spadgett** [comment]
Fixed by #4826
