### ISSUE TITLE
Pod template can be clipped in UI at narrow screen widths

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4489]
In some cases, the bottom is cut off when the window width is ~300px.

![openshift_web_console_and__wip__reduce_whitespace_on_overview_and_collapse_pods_by_their_status_by_jwforres_ _pull_request__4486_ _openshift_origin](https://cloud.githubusercontent.com/assets/1167259/9645357/0978ef3a-5199-11e5-8ab4-34e1238700c7.png)

**Comment by jwforres** [comment]
need to see if this is still the case with the new overview layout

**Comment by spadgett** [comment]
> need to see if this is still the case with the new overview layout

Noticed it while testing that :) But it's not a new problem.

**Comment by jwforres** [comment]
Issue occurs when there is a long string of unbreakable text, interestingly adding word-wrap: break-word does not fix it
