### ISSUE TITLE
Nodes expose some master-only Prometheus metrics with zero values

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#4494]
e.g. skydns metrics are registered on nodes even though skydns shouldn't be running there.

I haven't done a full review of other stuff but assume other node unrelated metrics will be in there. Metrics should only be reported from a component if they are valid metrics for that component; otherwise can impact on aggregations across the cluster.

From querying a node:

```
$ curl -k http://<node>:10255/metrics|grep dns
# HELP dns_dnssec_cache_miss_count Counter of DNSSEC requests that missed the cache
# TYPE dns_dnssec_cache_miss_count counter
dns_dnssec_cache_miss_count 0
# HELP dns_dnssec_ok_count Counter of DNSSEC requests that were valid
# TYPE dns_dnssec_ok_count counter
dns_dnssec_ok_count 0
# HELP dns_forward_count Counter of DNS requests forwarded
# TYPE dns_forward_count counter
dns_forward_count 0
# HELP dns_lookup_count Counter of DNS lookups performed
# TYPE dns_lookup_count counter
dns_lookup_count 0
# HELP dns_name_error_count Counter of DNS requests resulting in a name error
# TYPE dns_name_error_count counter
dns_name_error_count 0
# HELP dns_no_data_count Counter of DNS requests that contained no data
# TYPE dns_no_data_count counter
dns_no_data_count 0
# HELP dns_request_count Counter of DNS requests made
# TYPE dns_request_count counter
dns_request_count 0
```

**Comment by jimmidyson** [comment]
@smarterclayton Do you remember why you did https://github.com/openshift/origin/blob/master/pkg/dns/server.go#L69-L98 instead of just changing https://github.com/openshift/origin/blob/master/pkg/dns/server.go#L36 to `server.RegisterMetrics("", "")`?

**Comment by jimmidyson** [comment]
Ah it exposes more metrics it seems than the defaults.

**Comment by jimmidyson** [comment]
Well different ones. @smarterclayton - would you be happy with this set of metrics that skydns exposes?

```
# TYPE dns_cache_miss_count counter
dns_cache_miss_count{type="response"} 18
# HELP dns_dnssec_ok_count Counter of DNSSEC requests.
# TYPE dns_dnssec_ok_count counter
dns_dnssec_ok_count 0
# HELP dns_error_count Counter of DNS requests resulting in an error.
# TYPE dns_error_count counter
dns_error_count{error="nxdomain"} 0
# HELP dns_request_count Counter of DNS requests made.
# TYPE dns_request_count counter
dns_request_count{type="udp"} 20
# HELP dns_request_external_count Counter of external DNS requests.
# TYPE dns_request_external_count counter
dns_request_external_count{type="lookup"} 6
dns_request_external_count{type="recursive"} 2
```

If we pick up latest skydns we'll get some more nice stuff too, like bucket for responses sizes, response times, etc.

Propose removing https://github.com/openshift/origin/blob/master/pkg/dns/server.go#L69-L98 & changing https://github.com/openshift/origin/blob/master/pkg/dns/server.go#L36 to `server.RegisterMetrics("", "")`. Will send in a PR.

**Comment by smarterclayton** [comment]
Hrm - I thought I had removed all of that.  I think I did at one point and
it may have gotten reverted.  Those changes are fine to me, be aware that
if you bump skydns there are some annoying patches we carry.

On Tue, Sep 15, 2015 at 10:11 AM, Jimmi Dyson <notifications@github.com>
wrote:

> Well different ones. @smarterclayton <https://github.com/smarterclayton>
> - would you be happy with this set of metrics that skydns exposes?
>
> # TYPE dns_cache_miss_count counter
> dns_cache_miss_count{type="response"} 18
> # HELP dns_dnssec_ok_count Counter of DNSSEC requests.
> # TYPE dns_dnssec_ok_count counter
> dns_dnssec_ok_count 0
> # HELP dns_error_count Counter of DNS requests resulting in an error.
> # TYPE dns_error_count counter
> dns_error_count{error="nxdomain"} 0
> # HELP dns_request_count Counter of DNS requests made.
> # TYPE dns_request_count counter
> dns_request_count{type="udp"} 20
> # HELP dns_request_external_count Counter of external DNS requests.
> # TYPE dns_request_external_count counter
> dns_request_external_count{type="lookup"} 6
> dns_request_external_count{type="recursive"} 2
>
> If we pick up latest skydns we'll get some more nice stuff too, like
> bucket for responses sizes, response times, etc.
>
> Propose removing
> https://github.com/openshift/origin/blob/master/pkg/dns/server.go#L69-L98
> & changing
> https://github.com/openshift/origin/blob/master/pkg/dns/server.go#L36 to server.RegisterMetrics("",
> ""). Will send in a PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4494#issuecomment-140405658>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift
