### ISSUE TITLE
improve the docs for oc

### ISSUE THREAD

**Issue by jprukner** [openshift/origin#4496]
Passing no arguments to oc cause that help is shown up:
"To create a new application, you can use the example app source. Login to your server and then
run new-app:

  $ oc login
  $ oc new-app openshift/ruby-20-centos7~https://github.com/openshift/ruby-hello-world.git

This will create an application based on the Docker image 'openshift/ruby-20-centos7' that builds
the source code at 'github.com/openshift/ruby-hello-world.git'. To start the build, run

  $ oc start-build ruby-hello-world --follow
...."
When I follow instructions:
 "$ oc new-app openshift/ruby-20-centos7~https://github.com/openshift/ruby-hello-world.git"
Build is started automatically. So I think the command  "$ oc start-build ruby-hello-world --follow" is unnecessary and may cause that build freezes - two builds are runnig at the same time.

**Comment by rhcarvalho** [comment]
We could improve the help message explaining that a build is created automatically by `oc new-app`, but if you still want to create a build manually you can use `oc start-build`.

**Comment by liggitt** [comment]
Fixed in #4528
