### ISSUE TITLE
Jenkins Flake on Integration Test TestDiagNodeConditions

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4499]
Seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/4745/console):

```
--- FAIL: TestDiagNodeConditions-2 (6.24s)
	diag_nodes_test.go:60: expected no errors making node unschedulable, but: &errors.StatusError{ErrStatus:api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"node \"ip-172-18-11-91\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again", Reason:"Conflict", Details:(*api.StatusDetails)(0xc20a4aca40), Code:409}}
FAIL
```

**Comment by liggitt** [comment]
Where is that test? I don't see it in master or in your branch

**Comment by liggitt** [comment]
nevermind, I needed to update master

**Comment by liggitt** [comment]
@sosiouxme you should update the test to fetch the node right before you update it, otherwise you're likely to get conflicts, since the node regularly updates its status. You should probably attempt the update at least twice if you get back an error that `api/errors.IsConflict(err)` returns true for

**Comment by sosiouxme** [comment]
I didn't think of that, thanks, will do ASAP.

**Comment by stevekuznetsov** [comment]
Seeing this again on unrelated PR: https://travis-ci.org/openshift/origin/jobs/83955964

**Comment by liggitt** [comment]
different flake is fixed in https://github.com/openshift/origin/pull/4989
