### ISSUE TITLE
Error pushing to registry: Server error: unexpected 400 response status trying to initiate upload

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#4510]
I setup a repetitive job to build, deploy, repeat.  It made it to build #86 before the build failed. It would be good to have a better message as why the registry started to fail, if it is a known message. 

Details from the registry: http://pastebin.test.redhat.com/310479

Details from the build log:

```
I0903 11:57:52.941852       1 sti.go:134] Pushing 172.30.15.144:5000/test/kitchensink-example image ...
E0903 11:58:09.053839       1 dockerutil.go:50] push for image 172.30.15.144:5000/test/kitchensink-example failed, will retry in 10s ...
E0903 11:58:34.769912       1 dockerutil.go:50] push for image 172.30.15.144:5000/test/kitchensink-example failed, will retry in 10s ...
F0903 11:59:01.105431       1 builder.go:70] Build error: Failed to push image: Error pushing to registry: Server error: unexpected 400 response status trying to initiate upload of test/kitchensink-example
```

**Comment by ncdc** [comment]
I'm not sure we have much flexibility in what Docker reports when it encounters an error pushing. We'll have to look at what sorts of errors the registry returns, then look in Docker to see how it handles the various errors and what information is presents to the user.

**Comment by jkaurredhat** [comment]
I am facing this same issue but each time the build fails with below error - 

Build error: Failed to push image: Error pushing to registry: Server error: unexpected 400 response status trying to initiate upload of myproject/cakephp-example

**Comment by mfojtik** [comment]
@jhadvig was doing the retry logic and error reporting for pushing. He might know if there is a better way to report errors registry send us.

**Comment by nkhare** [comment]
@jkaurredhat I also faced same issue and if I configure some persistent storage for registry then it works, I followed https://github.com/openshift/training/blob/master/07-Registry-and-Storage.md
