### ISSUE TITLE
Make it easier to start master api from config

### ISSUE THREAD

**Issue by miminar** [openshift/origin#4523]
Standalone API can't be started with current master. Running it with default config like this:

    openshift start --write-config=/vagrant/openshift.local.config
    openshift start master api --config=/vagrant/openshift.local.config/master/master-config.yaml

produces [this](http://ur1.ca/no4kh) and terminates within 20 seconds.

Same commands executed on [3 weeks older code](https://github.com/openshift/origin/commits/9a6dc91) run just [fine](http://ur1.ca/no503).

**Comment by deads2k** [comment]
@liggitt I'll take this

**Comment by mnagy** [comment]
@deads2k I've bisected this to https://github.com/openshift/origin/commit/efec9799b0d9302e30ec1e831b38c8d3a2bc4a72 (PR https://github.com/openshift/origin/pull/3599) though I'm not sure if the commit caused the bug or just exposed it..

**Comment by liggitt** [comment]
that caused it

**Comment by liggitt** [comment]
Starting just the api doesn't populate all the initial bootstrap policy, etc. You can work around this by starting a full master first. I'm not sure whether bootstrap policy is considered a controller task or an api task, and if we want those partial components doing bootstrap tasks

**Comment by miminar** [comment]
The problem with full master is that it terminates once its controller lease is lost. Thus all etcd peers are lost. I'd like to to multiple controller instances with one API on a single machine without terminating etcd. The only way I can think of to achieve this is to start standalone etcd storage - haven't tried it yet. Or is there a better solution?

**Comment by liggitt** [comment]
lowering priority... this is working as intended at the moment, though it would be nice to enable this somehow (maybe `openshift start master etcd`, etc?)

supporting running HA components without a true HA setup (standalone etcd cluster, etc) would be nice for dev/test, but isn't a release blocker

**Comment by deads2k** [comment]
etcd is now startable.
