### ISSUE TITLE
protobuf godep prevents `godep restore`

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#4526]
`code.google.com/p/gogoprotobuf/proto` has moved to `github.com/gogo/protobuf` & is unavailable at the old location (a full move, not an archive like most of the other projects on google code).

This breaks `godep restore` so anyone using origin itself as a godep has to hack stuff around to get it to work. This has already been migrated upstream.

**Comment by liggitt** [comment]
Tracked in https://github.com/openshift/origin/issues/4434 to pick up in the next rebase

**Comment by jimmidyson** [comment]
Ah ok thanks @liggitt.
