### ISSUE TITLE
OpenLDAP Extended Test Uses Regex Instead of `-o name`

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4534]
#4151 adds an extended test that uses regex to grab names of imagestreams, etc from command output instead of using `-o name`. When `-o name` is brought into OpenShift , we need to change this.

@deads2k FYI

**Comment by stevekuznetsov** [comment]
@liggitt Is this coming in the rebase? What should I monitor to know when to attack this?

**Comment by deads2k** [comment]
It should be in the rebase:  https://github.com/openshift/origin/pull/4663.

**Comment by stevekuznetsov** [comment]
Deprecated the Ginkgo tests, closing.
