### ISSUE TITLE
Runtime error when logging out of Web Console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4538]
> Cannot read property 'getToggleElement' of null

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/9692237/ba9743b6-5315-11e5-9dce-dcc50c85a884.png)

@jwforres fyi

**Comment by spadgett** [comment]
This doesn't prevent logout from succeeding. I only noticed because I had developer tools open.

**Comment by spadgett** [comment]
Also happens on the console home (all projects page).

**Comment by spadgett** [comment]
This happens on all pages.

**Comment by spadgett** [comment]
Fixing this unfortunately results in increased flicker because the page redirects a few times on logout.

**Comment by liggitt** [comment]
It redirects a few times now? Or with a fix?

**Comment by spadgett** [comment]
After fixing the runtime error, there is one more intermediate logout page that flickers briefly before the you are logged out message.

**Comment by liggitt** [comment]
Tag me for review on any modifications to the logout flow... there are some gotchas

**Comment by jwforres** [comment]
This is caused by an upstream bug in bootstrap.js with a dropdown closing when we are navigating away.  This is not causing anything in the logout flow to fail so lowering the priority.

We should open a fix against bootstrap upstream.
