### ISSUE TITLE
Failed build launched by `oc start-build --follow` has 0 return code

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#4557]
When the build started by `oc start-build --follow` fails, it should return a non-zero return code, so we could detect any failures with it in Jenkins.
http://pastebin.test.redhat.com/310931

**Comment by mfojtik** [comment]
+1 to fix this. If I have Jenkins job that executes `start-build --follow` and stream the logs to the Jenkins console, when the build fails, I don't get the non-zero exit status.

This means I have to parse the status of the last build which is not very nice.

**Comment by mfojtik** [comment]
I think the workflow should be:

1) If build succeed, exit 0
2) If build fails, exit 1
3) if SIGINT (ctrl+c), exit 0 (or 255?)

**Comment by soltysh** [comment]
@mfojtik I don't agree with 2, start-build is just for starting builds, not looking at the result. If the build didn't start - then yes agree to fail the command. But if it started ok but failed in the end, that's not what I'd expect from start-build to exit with 1.

**Comment by mfojtik** [comment]
@soltysh another suggestion to fix the Jenkins use case then? I don't see any other than having something like `oc wait-for-build` or something which is terribly ugly. I don't think returning != 0 from `start-build` will hurt something.

**Comment by soltysh** [comment]
If `--follow` follows upstream pattern (https://github.com/openshift/origin/pull/4451/files#diff-4263193b2ddc1d5f92abb4576e614e83R8) which fails only when reading stream failed I'm more in favor of wait-for-build or similar. On the other hand this either can be satisfied with events, or it falls into category of getting better build status information discussed in #341

**Comment by bparees** [comment]
fixed, right @mfojtik ?

**Comment by kargakis** [comment]
> fixed, right @mfojtik ?

yes
