### ISSUE TITLE
make build logs persistent

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#4558]
Right now, we are storing build logs as annotations. I think that is not what annotations are meant for b/c they are capped at 64k and we do reach that limit _very_ easily (/me waves at `yum`).

Would it possible to make the logs persistent? I think that build logs are something which is absolutely essential to build -- those should be available **always**. How do you figure out why your two-months old build failed when you don't have logs? (b/c pod/containers were already purged)

**Comment by jprukner** [comment]
How about adding flag for example "--persist-logs"? Is it possible? @rhcarvalho @mfojtik 
And then start openshift like: sudo ./openshift start --public-master=localhost --persist-logs

**Comment by mfojtik** [comment]
@TomasTomecek if you're using custom builder, then you can make the logs persistent just by calling the buildLogs and capturing the output (and then store it wherever you want). You can also add logs into the build image in that case.

**Comment by mfojtik** [comment]
@TomasTomecek also centralized logging is on the roadmap, so we should have better story about storing logs soon.

**Comment by mfojtik** [comment]
@bparees FYI this is the issue I was talking about ;-)

**Comment by liggitt** [comment]
@mfojtik link to relevant cards for tracking?

**Comment by mfojtik** [comment]
@liggitt dunno if there is relevant card but there is ongoing work for logging (see @aos-devel). Also docker recently got journald logging driver.

**Comment by TomasTomecek** [comment]
@mfojtik 
> @TomasTomecek if you're using custom builder, then you can make the logs persistent just by calling the buildLogs and capturing the output (and then store it wherever you want).

Yes, that's what we do now, pretty much. But I still feels like that if you have build objects, the essential part of a build is its log and it should be available _always_. Since docker can't do persistent logs, I was hoping that openshift could.

Michal, as you say, there was recently [a patch merged](https://github.com/docker/docker/pull/13707) to docker which enables feeding journal with container logs. Maybe this could work.

> You can also add logs into the build image in that case. 

Could you please elaborate?

> @TomasTomecek also centralized logging is on the roadmap, so we should have better story about storing logs soon.

If you are talking about whole ELK stack, I feel like that's overkill -- deploy several new services just for sake of build logs.

**Comment by bparees** [comment]
> If you are talking about whole ELK stack, I feel like that's overkill -- deploy several new services just for sake of build logs.

ELK will be the central platform logging, we're not going to do a separate one off log storage solution just for the build system when our builds are just another thing running on openshift.

**Comment by pweil-** [comment]
> ELK will be the central platform logging, we're not going to do a separate one off log storage solution just for the build system when our builds are just another thing running on openshift.
