### ISSUE TITLE
Question about OpenStack cinder volume in Openshift

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#4563]
Hi, I was looking at the Kubernetes documentation, 
https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-cinder-pd

It supports OpenStack cinder volume I would like to know if OpenShift supports this kind of volume for persistent storage, any idea ?

In Openshift documentation I have read only NFS examples ....

Many thanks.

**Comment by mfojtik** [comment]
@markturansky cc

**Comment by markturansky** [comment]
@roldancer We definitely will as part of the official 3.1 release.  I'm not sure if cinder has been patched into OpenShift yet, but it will be soon if it's not already.
