### ISSUE TITLE
Replace pinging URL before git clone with pure git solution

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#4564]
This is a follow-up to #4548. 

@bparees @liggitt @mfojtik @csrwng fyi

**Comment by bparees** [comment]
thanks @soltysh

**Comment by bparees** [comment]
The solution to this should also address the potential concern of a git clone operation that hangs due to a password prompt.  (also discussed in #4548 )

**Comment by soltysh** [comment]
Also related to https://github.com/openshift/source-to-image/issues/281, partially

**Comment by mfojtik** [comment]
@bparees assign this to me pls :-)
