### ISSUE TITLE
Add 'revision' information to OpenShift Docker images

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#4570]
It is pretty hard to know what revision the images were build from when you pull them from DockerHub:

```
docker.io/openshift/origin-docker-registry       latest              a4ed6d11ef7a        9 hours ago         288.6 MB
```

Since the labels are empty, I don't know if the fix I'm looking for is incorporated in this image (or what source revision was used to build this image).

We already adding the `LABEL io.openshift.builder-version=XYZ` label to all S2I image and perhaps we should do the same for all OpenShift images we build. It will help QA to report bugs and developers to see if the features we want are there.

**Comment by mfojtik** [comment]
@smarterclayton @bparees FYI

**Comment by bparees** [comment]
+1

**Comment by smarterclayton** [comment]
builder-version doesn't seem right.  What does that label mean?

**Comment by bparees** [comment]
builder-version means "version of the builder image" (eg "commit level of the ruby-20-centos7 image")

**Comment by smarterclayton** [comment]
hrm - why wouldn't we just identify origin-docker-registry as "built from this commit"?

**Comment by mfojtik** [comment]
@smarterclayton I'm not suggesting to use the same label, but something similar to that. Sorry for confusion.

**Comment by smarterclayton** [comment]
Np

On Tue, Sep 8, 2015 at 10:23 AM, Michal Fojtik <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> I'm not suggesting to
> use the same label, but something similar to that. Sorry for confusion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4570#issuecomment-138578590>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Are we fixed here?

**Comment by bparees** [comment]
yes, openshift-built application images now include an io.openshift.build.commit.xxxx set of labels w/ commit information.
