### ISSUE TITLE
Watching projects

### ISSUE THREAD

**Issue by petervo** [openshift/origin#4575]
The api docs (https://docs.openshift.org/latest/rest_api/openshift_v1.html#list-objects-of-kind-project) indicate that the project list endpoint accepts a watch parameter for watching projects. But that didn't work, after looking and the code it seems watches aren't implemented for projects. We can of course watch namespaces instead so maybe project watches aren't necessary, but the docs should probably be updated to remove the watch param for projects.

**Comment by kargakis** [comment]
Fixed in https://github.com/openshift/origin/pull/6828
