### ISSUE TITLE
`osc start-build` cannot push image when HTTP proxy is used

### ISSUE THREAD

**Issue by bcsontos** [openshift/origin#4577]
I had the same issue as which was described in #3395, and also the solution worked for me, but it led to another one.
In my installation I have a local Docker registry. When HTTPSProxy build source parameter is set pushing to this registry fails. Telling from its access log, these requests are also sent to the proxy server and can't reach the local registry.

**Comment by liggitt** [comment]
so... how do we indicate that _some_ requests should use the configured proxy, but not others...

**Comment by bparees** [comment]
the httpProxy field set on the source is not used for the docker push.  at least it should not be.  the variable is unset before the push is performed.

@bcsontos can you share our buildconfig json?

**Comment by bparees** [comment]
(to further clarify... the httpProxy/httpsProxy field on the source definition is only used for the git clone, not for docker operations)

**Comment by bcsontos** [comment]
This is a from a deployment test of cakephp-example.
```json
{
    "kind": "BuildConfig",
    "apiVersion": "v1",
    "metadata": {
        "name": "cakephp-example",
        "creationTimestamp": null,
        "labels": {
            "template": "cakephp-example"
        },
        "annotations": {
            "description": "Defines how to build the application"
        }
    },
    "spec": {
        "triggers": [
            {
                "type": "ImageChange",
                "imageChange": {}
            },
            {
                "type": "GitHub",
                "github": {
                    "secret": "aW6noSmSKVue3iBM5uVdfVLOTQtUMQx2RSspq3sk"
                }
            }
        ],
        "source": {
            "type": "Git",
            "git": {
                "uri": "https://github.com/openshift/cakephp-ex.git",
                "httpProxy": "http://10.12.0.17:3128",
                "httpsProxy": "http://10.12.0.17:3128"
            }
        },
        "strategy": {
            "type": "Source",
            "sourceStrategy": {
                "from": {
                    "kind": "ImageStreamTag",
                    "namespace": "openshift",
                    "name": "php:5.5"
                }
            }
        },
        "output": {
            "to": {
                "kind": "ImageStreamTag",
                "name": "cakephp-example:latest"
            }
        },
        "resources": {}
    },
    "status": {
        "lastVersion": 0
    }
}
```

**Comment by mfojtik** [comment]
@bparees I think the env vars for proxy somehow leaked to the pusher. I think we should make sure they are not set when we push images.

**Comment by mfojtik** [comment]
@bcsontos can you add environment variable `BUILD_LOGLEVEL` and set it to "5" ? Then kick a new build send us the bottom of the log... You should see something like:

```
glog.V(4).Infof("Resetting HTTPS_PROXY variable for Git to %s", origProxy["HTTPS_PROXY"])
```

**Comment by mfojtik** [comment]
@bparees hear this... I was able to reproduce this in the first build I made (got some error about basic auth something)... Then I set BUILD_LOGLEVEL=5 and the build passed... Then I started another build and it passed...

**Comment by bcsontos** [comment]
The variables are reset as it seems, but the the proxy address still shows up when the push attempt is made.

    I0910 04:35:25.283148       1 sti.go:251] Successfully built 172.30.148.240:5000/primal/cakephp-example:latest
    I0910 04:35:25.346023       1 cleanup.go:23] Removing temporary directory /tmp/sti093676441
    I0910 04:35:25.346043       1 fs.go:99] Removing directory '/tmp/sti093676441'
    I0910 04:35:25.386976       1 sti.go:127] Resetting HTTPS_PROXY variable for Git to
    I0910 04:35:25.387045       1 sti.go:129] Resetting https_proxy variable for Git to
    I0910 04:35:25.387056       1 sti.go:133] Resetting HTTP_PROXY variable for Git to
    I0910 04:35:25.387064       1 sti.go:135] Resetting http_proxy variable for Git to
    I0910 04:35:25.387121       1 cfg.go:78] Found Docker authentication configuration in '/root/.dockercfg'
    I0910 04:35:25.387129       1 cfg.go:46] PUSH_DOCKERCFG_PATH=/var/run/secrets/openshift.io/push/.dockercfg
    I0910 04:35:25.387133       1 cfg.go:78] Found Docker authentication configuration in '/var/run/secrets/openshift.io/push/.dockercfg'
    I0910 04:35:25.387376       1 cfg.go:64] Using serviceaccount user for Docker authentication
    I0910 04:35:25.387386       1 sti.go:146] Using provided push secret for pushing 172.30.148.240:5000/primal/cakephp-example:latest image
    I0910 04:35:25.387394       1 sti.go:149] Pushing 172.30.148.240:5000/primal/cakephp-example:latest image ...
    E0910 04:35:45.676003       1 dockerutil.go:50] push for image 172.30.148.240:5000/primal/cakephp-example:latest failed, will retry in 10s ...
    E0910 04:36:15.687807       1 dockerutil.go:50] push for image 172.30.148.240:5000/primal/cakephp-example:latest failed, will retry in 10s ...
    F0910 04:36:45.721838       1 builder.go:65] Build error: Failed to push image: API error (500): invalid registry endpoint "http://172.30.148.240:5000/v0/". HTTPS attempt: unable to ping registry endpoint https://172.30.148.240:5000/v0/
    v2 ping attempt failed with error: Get https://172.30.148.240:5000/v2/: Forbidden
     v1 ping attempt failed with error: Get https://172.30.148.240:5000/v1/_ping: Forbidden. HTTP attempt: unable to ping registry endpoint http://172.30.148.240:5000/v0/
    v2 ping attempt failed with error: Get http://172.30.148.240:5000/v2/: read tcp 10.12.0.17:3128: i/o timeout
     v1 ping attempt failed with error: Get http://172.30.148.240:5000/v1/_ping: read tcp 10.12.0.17:3128: i/o timeout

**Comment by liggitt** [comment]
I'm pretty sure os.Setenv doesn't apply to child processes... probably need to set `Env` in the launched Clone Cmd

**Comment by liggitt** [comment]
nope, I'm wrong... this does what I would expect

```
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	fmt.Println("FOO in process:", os.Getenv("FOO"))
	os.Setenv("FOO", "")
	fmt.Println("FOO in process after unset:", os.Getenv("FOO"))
	c := exec.Command("env")
	out, _ := c.CombinedOutput()
	fmt.Println(string(out))
}
```

```
$ FOO=bar go run test.go  | grep FOO
FOO in process: bar
FOO in process after unset: 
FOO=
```

**Comment by bparees** [comment]
I don't think docker pull/push even uses the HTTP_PROXY env variables, so i think there's another config coming into play here that is controlling the docker proxy...

I set mine to a bogus value and was still able to push to dockerhub:

```
sti-ruby (writable)$ env | grep -i http
http_proxy=http://192.168.111.111:3128
HTTPS_PROXY=http://192.168.111.111:3128
https_proxy=http://192.168.111.111:3128
HTTP_PROXY=http://192.168.111.111:3128
```

```
$ ping 192.168.111.111
PING 192.168.111.111 (192.168.111.111) 56(84) bytes of data.
^C
--- 192.168.111.111 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 999ms
```

**Comment by bparees** [comment]
> @bparees hear this... I was able to reproduce this in the first build I made (got some error about basic auth something)... Then I set BUILD_LOGLEVEL=5 and the build passed... Then I started another build and it passed... 

@mfojtik what exactly do you mean when you say you were able to reproduce this?  did you recreate a failure when using a proxy?  or it works for you when using a proxy?  of course it working for you when using a proxy doesn't mean much if your proxy can access your registry.  it has to be a proxy that can't reach the registry.

**Comment by bparees** [comment]
i just tested this using our company proxy which can't access my openshift registry (but can be used for the git clone operation) and it worked fine.  so again, there's something else at play here.

**Comment by bcsontos** [comment]
@bparees you are right. For the registry deployment to succeed I did set HTTP_PROXY and HTTPS_PROXY for docker. I guess I haven't thought of this before because I also did set NO_PROXY to "localhost,127.0.0.0/8,172.30.0.0/16" and had confidence that this would match the IP address of each service endpoint, including that of the registry (172.30.148.240). I tried clearing these variables and it worked.

**Comment by bparees** [comment]
cool, so can we close this?  sounds like there may be an issue that docker does not respect NO_PROXY that would be worth opening against docker.

**Comment by bcsontos** [comment]
Yes, the issue solved. Thank you for your help.

**Comment by priyanka6dell** [comment]
not work for me.
