### ISSUE TITLE
oc exec -i <pod> cat /etc/resolv.conf hangs on docker 1.6.2.fc21

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4581]
Does not fail in docker 1.8.1

**Comment by liggitt** [comment]
priority?

**Comment by mfojtik** [comment]
@smarterclayton f21 has now docker 1.8...

**Comment by smarterclayton** [comment]
We support 1.6.2 still for customers.  Unless we've suddenly forced
everyone to upgrade to Docker 1.8 in a patch release.

On Tue, Sep 8, 2015 at 2:03 PM, Michal Fojtik <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> f21 has now docker
> 1.8...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4581#issuecomment-138651146>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ncdc** [comment]
This appears to be an issue with Docker 1.6.2 (not sure if it's our versions or all) - I get a hang with just `docker exec -i <container> bash` followed by `exit<CR>`.

**Comment by smarterclayton** [comment]
Can you do a pull request for the README.md and CONTRIBUTING that update
that.

On Tue, Sep 8, 2015 at 4:55 PM, Andy Goldstein <notifications@github.com>
wrote:

> This appears to be an issue with Docker 1.6.2 (not sure if it's our
> versions or all) - I get a hang with just docker exec -i <container> bash
> followed by exit<CR>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4581#issuecomment-138697130>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift
