### ISSUE TITLE
Shouldn't be including the invidual html templates files in bindata anymore

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#4582]
Now that we are injecting the templates into the JS we should stop shipping the HTML versions in bindata so we can reduce the bindata size.

**Comment by jwforres** [comment]
@spadgett fyi, should just be changes to the gruntfile build steps

**Comment by jwforres** [comment]
It actually looks like they are getting included three different times, I'm guessing there is an intermediate js file that is also getting included and doesn't need to be.

**Comment by spadgett** [comment]
@jwforres In my testing before, the first template gets loaded using the HTML file in a separate request, then all subsequent templates are loaded form the cache. I'm not sure why the first template isn't pulled from the cache, but I'd need to debug before making this change.

It might be related to hawtio nav, or perhaps just a timing issue.

**Comment by jwforres** [comment]
my guess would be that its the order the JS is being loaded in

**Comment by spadgett** [comment]
That would make sense... I'll dig into it.

**Comment by spadgett** [comment]
Yeah it makes the XHR for the first template before any templates are added to the cache.

**Comment by jwforres** [comment]
For 1.1.0 I want to at least get rid of the third completely unminified instance that is getting included, looks like it is coming from "scripts/templates.js" getting included in bindata
