### ISSUE TITLE
cannot access Service from outside openshift , missing routing

### ISSUE THREAD

**Issue by imarmash** [openshift/origin#4589]
Hello,
I have created sample POD as below , and I can reach it via curl command
![pod](https://cloud.githubusercontent.com/assets/14195991/9759804/78e66c1c-56f8-11e5-8779-f72e48cbcf0d.JPG)
and i attached it to services and it is also accessible as below
![services](https://cloud.githubusercontent.com/assets/14195991/9759816/8d73b248-56f8-11e5-88bc-22768df9ffe1.JPG)
then I created a route to this service but i cannot access it from outside , I don't know if i have to create any other config
![route](https://cloud.githubusercontent.com/assets/14195991/9759831/a590d662-56f8-11e5-9eff-d8484c82de91.JPG)

**Comment by imarmash** [comment]
@liggitt  I hope if you can help me from your experience.

**Comment by imarmash** [comment]
new screenshot for routes
![route2](https://cloud.githubusercontent.com/assets/14195991/9760836/46ade21c-5701-11e5-93f1-21beae273515.JPG)

**Comment by imarmash** [comment]
from console
![console](https://cloud.githubusercontent.com/assets/14195991/9760858/6b53028c-5701-11e5-8a9e-9a9e1509bc6f.JPG)

**Comment by liggitt** [comment]
Did you install the router (`oadm router`)?
