### ISSUE TITLE
Cannot install router openshift , 

### ISSUE THREAD

**Issue by imarmash** [openshift/origin#4592]
when i executed the command below ,

[root@master setup]# ./oc get scc -t "{{range .items}}{{.metadata.name}}: n={{.allowHostNetwork}},p={{.allowHostPorts}}; {{end}}"

i got this error

Error from server: User "root" cannot list all securitycontextconstraints in the cluster

**Comment by deads2k** [comment]
That error means that your current user doesn't have permission see the security context constraints.  If your intent is for "root" to be a "cluster-admin" you'll need to grant him those rights via `oadm policy add-cluster-role-to-user cluster-admin root`.  Otherwise, you can use the `admin.kubeconfig` file to run the command by adding the `--config=<path to admin.kubeconfig>` option to your `oc get`.

**Comment by imarmash** [comment]
what is the user that can run the command 
oadm policy add-cluster-role-to-user cluster-admin root
i tried to run it but it fails , so i hope if you can guide me to the user that have super admin priv

**Comment by deads2k** [comment]
> i tried to run it but it fails , so i hope if you can guide me to the user that have super admin priv

Can you locate your "admin.kubeconfig" file?  It's a file named "admin.kubeconfig".  It contains credentials that allow you to run the privileged commands.  It'll probably be under "openshift.local.config/master" or under "/etc/openshift3/" somewhere.

**Comment by imarmash** [comment]
after that i can login using that user
./oc login

**Comment by imarmash** [comment]
here the content of the file , where is the username and password
and where can i login

apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.189.134:8443
  name: 192-168-189-134:8443
contexts:
- context:
    cluster: 192-168-189-134:8443
    namespace: test
    user: root/192-168-189-134:8443
  name: test/192-168-189-134:8443/root
current-context: test/192-168-189-134:8443/root
kind: Config
preferences: {}
users:
- name: root/192-168-189-134:8443
  user:
    token: AFQwRYFG33YCu0X6X9miw-OHXmHXtolhMqczTXIH6Zk

**Comment by imarmash** [comment]
here another output from other environment with same problem

    server: https://192.168.189.134:8443
  name: 192-168-189-134:8443
contexts:
- context:
    cluster: 192-168-189-134:8443
    namespace: default
    user: system:admin/192-168-189-134:8443
  name: default/192-168-189-134:8443/system:admin
current-context: default/192-168-189-134:8443/system:admin
kind: Config
preferences: {}
users:
- name: system:admin/192-168-189-134:8443
  user:

**Comment by liggitt** [comment]
what does `oc whoami` show?
can you run `oc login -u system:admin`?
if that succeeds, you should then be authenticated as the cluster admin and be able to edit scc objects or add the cluster-admin role to another user

**Comment by imarmash** [comment]
thank you,
I followed the steps and used --config=/mnt/setup/openshift.local.config/master/admin.kubeconfig
in needed commands.
but even so the router still not created.
can you guide me to manual for creating the router.

anyway i want to know if you can guide me to anyone can provide me with paid openshift training , i have project and i have no time to waste in learning

**Comment by liggitt** [comment]
The documentation at https://docs.openshift.org/latest/admin_guide/install/deploy_router.html is the best guide to installing the router. It assumes you are logged in as the cluster admin and are using the "default" namespace. Can you run this, and provide the output:
```
export KUBECONFIG=/mnt/setup/openshift.local.config/master/admin.kubeconfig
oc whoami
oc login -u system:admin -n default
oc whoami
```

Then try following the linked documentation for creating the router

**Comment by imarmash** [comment]
I followed the steps you mentioned and i logged in successfully and created
but when i got the error below when i run this command
[root@master setup]# ./oc get pods
NAME                      READY     STATUS         RESTARTS   AGE
docker-registry-1-vgqbn   1/1       Running        0          4h
route-1-deploy            0/1       ExitCode:255   0          9m
router-1-deploy           0/1       ExitCode:255   0          6m

**Comment by liggitt** [comment]
what do the router deployment logs show? `oc logs router-1-deploy`, etc

**Comment by imarmash** [comment]
I repeated the steps from scratch and the i installed the router as you mentioned 
kindly check the logs below
[root@localhost setup]# ./oc logs router2-1-deploy
I0910 08:57:35.782993       1 deployer.go:195] Deploying default/router2-1 for the first time (replicas: 1)
I0910 08:57:35.863757       1 recreate.go:112] Scaling default/router2-1 to 1 before performing acceptance check
I0910 08:57:38.026928       1 recreate.go:117] Performing acceptance check of default/router2-1
I0910 08:57:38.027010       1 lifecycle.go:279] Waiting 600 seconds for pods owned by deployment "default/router2-1" to become ready (checking every 1 seconds; 0 pods previously accepted)



[root@localhost setup]# ./oc get pods
NAME                       READY     STATUS         RESTARTS   AGE
docker-registry-1-8hne0    1/1       Running        0          13m
docker-registry-2-deploy   0/1       ExitCode:255   0          12m
router2-1-deploy           1/1       Running        0          3m
router2-1-gr854            0/1       Pending        0          3m
[root@localhost setup]#

**Comment by imarmash** [comment]
The router successfully installed but the application doesn't route from outside , it gives the error below
[root@localhost setup]# curl hello-openshift.cloudapps.assistahealth.me
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

and for the command ./oc logs router-1-deploy
I0910 09:40:48.547898       1 deployer.go:195] Deploying default/router-1 for the first time (replicas: 1)
I0910 09:40:48.666789       1 recreate.go:112] Scaling default/router-1 to 1 before performing acceptance check
I0910 09:40:50.797973       1 recreate.go:117] Performing acceptance check of default/router-1
I0910 09:40:50.798141       1 lifecycle.go:279] Waiting 600 seconds for pods owned by deployment "default/router-1" to become ready (checking every 1 seconds; 0 pods previously accepted)

 for pods
[root@localhost setup]# ./oc get pods
NAME                       READY     STATUS         RESTARTS   AGE
docker-registry-1-8hne0    1/1       Running        0          1h
docker-registry-2-deploy   0/1       ExitCode:255   0          59m
hello-openshift            1/1       Running        0          20m
router-1-deploy            1/1       Running        0          6m
router-1-q7kci             0/1       Pending        0          6m
router2-1-gr854            1/1       Running        0          49m


for services
NAME              CLUSTER_IP      EXTERNAL_IP   PORT(S)    SELECTOR                  AGE
docker-registry   172.30.150.66   <none>        5000/TCP   docker-registry=default   1h
hello-openshift   172.30.182.73   <none>        8888/TCP   name=hello-openshift      18m
kubernetes        172.30.0.1      <none>        443/TCP    <none>                    1h
router            172.30.88.188   <none>        80/TCP     router=router             6m
router2           172.30.67.5     <none>        80/TCP     router=router2            49m

**Comment by imarmash** [comment]
[root@localhost setup]# ./oc describe service/hello-service
Name:                   hello-service
Namespace:              default
Labels:                 name=hello-openshift
Selector:               name=hello-openshift
Type:                   ClusterIP
IP:                     172.30.148.55
Port:                   <unnamed>       8888/TCP
Endpoints:              172.17.0.6:8080
Session Affinity:       None
No events.

**Comment by liggitt** [comment]
Did you create a route for that service? Can you include its JSON definition?

**Comment by imarmash** [comment]
Yes i created route for that service as below, and i want to know if i created new service with route using another user does it use this router instance

  "kind": "Route",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "hello-route"
  },
  "spec": {
    "host": "hello-openshift.cloudapps.assistahealth.me",
    "to": {
      "kind": "Service",
      "name": "hello-service"
    }
  }
}
~

**Comment by smarterclayton** [comment]
Closing due to age.  We have various things that set the router up, which was the original question.
