### ISSUE TITLE
Routes don't properly respect multi-port services

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4603]
A service chooses to expose multiple ports from pods.  A route should choose to expose one or more ports from the service.  A route is implicitly L7, with some L4 behaviors.

* Route is TLS passthrough -> we can pass 80 -> http and 443 -> https
* Route is TLS reencrypt -> pass 80 -> http and 443 decodes and then needs to send to 443
* Route is TLS edge -> pass 80 -> http and 443 decodes and sends to 80
* Route has no TLS -> pass 80 -> http

Future:

* Custom router finds endpoints with a given name and routes them through on a port
* Exposes same routes on multiple ports with different behavior

Endpoints contain the name of the originating service port (if there is more than a single port).

For single port services, the following modes are available:

* TLS passthrough on 443 -> port
* TLS reencrypt on 443 -> port, 80 -> port
* TLS edge on 443 -> port, and 80 -> port
* No TLS -> 80 -> port

We can *infer* HTTP when:

* Path is set
* No TLS is set

We can infer TLS when:

* TLS is passthrough or reencrypt

When can infer TCP only if:

* We aren't inferring HTTP

In all other cases, we can only assume that the backends are identified.

A router should identify which ports it exposes.  This should be a property that is reported back to the service.  The rules for choosing which ports to expose should respect the settings on the router and the various inferences on the route.

Examples:

* The default HAProxy template router supports TLS passthrough, reencrypt, and edge.  It exposes 80 and 443 by default.
  * If the route is multi-port, we must guess which endpoint to use.
  * For passthrough we *could* support multiport selection for passthrough, but it's likely users don't want that by default (don't want to bypass TLS).  We can offer a setting that is distinct that indicates that we wish to enforce TLS
* Other template routers may only support a subset of these features.
* The F5 router supports TCP balancing.  It may expose arbitrary ports and IPs
  * It should be possible for the F5 to indicate to clients what ports and IPs they should get.

Proposed search order for multi-port services:

1. Allow the user to specify target port via a field on route
  * In the future, it would be desirable to support multiple target mappings
  * Out of scope for the default template router
2. Try to find a port that most closely represents the desired target - `http` or `https`
3. When we infer TLS, look for port named `https`, or a port 443
4. When we infer HTTP, look for a port named `http`, or a port 80
5. When we cannot infer any port, choose the first port in the endpoints list of the first subset.

**Comment by smarterclayton** [comment]
@ramr @pweil-

**Comment by smarterclayton** [comment]
@liggitt @spadgett

**Comment by pweil-** [comment]
+1 for making the route smarter in terms of support for multiport services.  I'm not sure what we buy if we're allowing the router to do the inferring though unless I'm reading this wrong.  I think I would prefer having the system do the inference only allowing the router to reject the route based on its capabilities.  That way inference for system objects is consistent.

My other caution is allowing a router to expose both secure and unsecure versions of a route by inference.  Granted, we can't really control that if someone customizes a template but I don't think we should encourage it.  If we give you a secure route then expose it securely or reject it as unsupported.

**Comment by smarterclayton** [comment]
The route is a policy document - we should be as unambiguous about what a user specifying each field of the route means.  If we can't honor it, that may still be the admin choice (they want to expose everything as port 80 over http).  We should try to be useful and do what the user tells us - that's mostly what i meant by infer.  We should not surprise the user.

Rejecting the route is hard - we would actually need to offer a new config template that rejects the routes based on reasons.  Not sure how we'd easily do that today.

**Comment by smarterclayton** [comment]
Because admins can configure the template, we have to be somewhat generous in our understanding of what the router has been doing.

**Comment by smarterclayton** [comment]
@jcantrill fyi as well, see the proposed change to the api

**Comment by smarterclayton** [comment]
Routes now have an optional routePort.  new-app and the UI should generate services that expose all ports.  expose should use the first service port as the route port (and never *not* set one).

**Comment by smarterclayton** [comment]
@kargakis is there a pull to make expose set routePort?

**Comment by kargakis** [comment]
There will be one tomorrow

**Comment by pweil-** [comment]
> There will be one tomorrow

cc @thoraxe

**Comment by kargakis** [comment]
> @kargakis is there a pull to make expose set routePort?

https://github.com/openshift/origin/pull/5067

**Comment by smarterclayton** [comment]
This core issue is resolved
