### ISSUE TITLE
Problem migrating v1.0.5/3.0.1 SDN config

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#4605]
When upgrading from v1.0.5 to master I get the following error.

```
Sep 09 16:54:17 ose3-master.example.com openshift-master[4726]: I0909 16:54:17.606882    4726 event.go:203] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ose3-node1.example.com", UID:"ose3-node1.example.com", APIVersion:"", ResourceVersion:"", FieldPath:""})
Sep 09 16:54:17 ose3-master.example.com openshift-master[4726]: I0909 16:54:17.606921    4726 event.go:203] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ose3-node2.example.com", UID:"ose3-node2.example.com", APIVersion:"", ResourceVersion:"", FieldPath:""})
Sep 09 16:54:18 ose3-master.example.com openshift-master[4726]: I0909 16:54:18.117534    4726 common.go:76] Self IP: 192.168.122.134.
Sep 09 16:54:18 ose3-master.example.com openshift-master[4726]: F0909 16:54:18.442188    4726 flatsdn.go:35] SDN initialization failed: A network already exists and does not match the new network's parameters - Existing: (10.1.0.0/16, 8, ); New: (10.1.0.0/16, 8, 172.30.0
```

CC: @danwinship

**Comment by liggitt** [comment]
Config additions have to be backwards compatible. May need to special case the addition of nodeIP (I assume that's what this is complaining about)

**Comment by sdodson** [comment]
Previous log output was truncated, here's the full line.

```
Sep 09 17:21:16 ose3-master.example.com openshift-master[13253]: F0909 17:21:16.075327   13253 flatsdn.go:35] SDN initialization failed: A network already exists and does not match the new network's parameters - Existing: (10.1.0.0/16, 8, ); New: (10.1.0.0/16, 8, 172.30.0.0/16)
```

**Comment by danwinship** [comment]
It's because of the serviceNetwork addition, but I'm not sure where to put the code to fill in the default value...

**Comment by liggitt** [comment]
https://github.com/openshift/origin/blob/master/pkg/cmd/server/api/v1/conversions.go#L11

Add a defaulting function for type *MasterNetworkConfig

**Comment by liggitt** [comment]
actually, that's the defaults for the server config... not sure about the ClusterNetwork object... might need a defaulting function in sdn/api/v1, though I'm not sure what you'd default to

**Comment by danwinship** [comment]
@rajatchopra suggested making plugins/osdn/osdn.go:WriteNetworkConfig() update the record in etcd with the new field value in this case, rather than bailing out. (Testing that now...)
