### ISSUE TITLE
CLI Options have implicit temporal structure

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4607]
Our CLI `Options` structs always need to be used in a specific manner - first `Complete`, then `Validate`, then `Run`. 

We expose each step publically but require this temporal ordering of calls. It seems it would bet better to only expose `Run` and force that ordering inside of that method.

Thoughts, @deads2k @liggitt @smarterclayton ?

**Comment by liggitt** [comment]
I like separating the phases. If you are composing a command from several simpler commands, you'd want to call all Complete functions, then all Validate, then all Run

**Comment by deads2k** [comment]
They should remain discrete steps.  Combining all of them together would change the meaning of things like `Run`.  Right now, `Run` means "take this complete set of options and perform the action".  If we smashed `Complete` into it, it would mean "take this maybe complete set of options, add this other command specific stuff to it (better have filled that magic container correctly from wherever you're calling from), and then try to run the command".

**Comment by deads2k** [comment]
Looking through your other comments from last night, this is why you thought `Options` objects should contain CLI options, not the information required to perform the action?  Do the comments in here help clarify?

**Comment by smarterclayton** [comment]
I might want to validate without running, or run without validating.

On Thu, Sep 10, 2015 at 7:54 AM, David Eads <notifications@github.com>
wrote:

> Looking through your other comments from last night, this is why you
> thought Options objects should contain CLI options, not the information
> required to perform the action? Do the comments in here help clarify?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4607#issuecomment-139213051>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by liggitt** [comment]
the trio has spoken

**Comment by kargakis** [comment]
cc: @rhcarvalho
