### ISSUE TITLE
Build already exists errors

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#4608]
Today I found interesting bug:

```
$ oc create -f test-buildconfig.json
$ oc start-build test # repeat several times
$ oc delete -f test-buildconfig.json
$ oc create -f test-buildconfig.json
$ oc start-build test
Error from server: build "test-1" already exists
```

So I have to call `start-build` X times to finally reach the name that was not taken ;-) I can also remove all builds manually, but this looks as an error to me in the first place. Why we reset the counter for the builds if I re-create the build config?

We have three choices I think:

1) When deleting BuildConfig, remove all associated builds
2) Instead of "build already exists", suggest user next action (remove all builds?)
3) Do not reset the counter for the builds

EDIT: If you delete DC all its deployments will be scaled down and deleted, why not to do the same for builds?

**Comment by mfojtik** [comment]
@bparees @soltysh

**Comment by kargakis** [comment]
Is there any reason to keep builds around when we delete the bc? I can't think of any and 1. seems the right thing to do. You would need to implement the reaper for bcs.

**Comment by soltysh** [comment]
:+1: for removing all builds, as @kargakis already mentioned the reaper will handle cascade delete of all related builds, and the user still can opt-out with `--cascade=false`

**Comment by bparees** [comment]
i'm a little wary of it since deleting the builds means the pods will get deleted which means you lose the build logs.

**Comment by soltysh** [comment]
Why would you want to keep build logs if you just removed the bc?

**Comment by mfojtik** [comment]
@bparees we will have to delete the build pods anyway (pruning) and I think the long term solution would be to have some centralized logging where you can pipe the build logs and they will be persisted. I don't think keeping the builds (even after you deleted the BC) just to keep the builds logs is something we want to do long term. But I can be wrong.

**Comment by bparees** [comment]
@soltysh @mfojtik i'm thinking about the accidental case, primarily.  (oops i deleted the wrong BC and now i lost all my logs along with it)

**Comment by mfojtik** [comment]
@bparees you better don't delete your BC in that case :-) I mean deleting DC causes the same, right? It puts your application down which might also be an accident... The output of the build is image which will not be removed... I think, one possible solution to persist build logs will be to copy the build log into the image we build at the end of the build... (just thinking laud)

**Comment by soltysh** [comment]
@bparees going this path we should not delete any resources at all, that's not valid argument against removing builds with bcs,, imho. We can't protect users from stupid mistakes.

**Comment by bparees** [comment]
> going this path we should not delete any resources at all, that's not valid argument against removing builds with bcs,, imho. 

that's a pretty false slippery slope argument.  obviously we wouldn't say you can never delete anything.  but chaining/recursively deleting things needs to be considered carefully.

> We can't protect users from stupid mistakes.

of course we can.

However if we have a precedent here for DCs then I can agree to carrying it forward to BCs.

**Comment by mfojtik** [comment]
@bparees transferring to trello?

**Comment by bparees** [comment]
trello'd https://trello.com/c/uRC4FRjR/683-delete-builds-when-buildconfig-is-deleted
