### ISSUE TITLE
"Connect" link for Java console should be disabled when pod is still pending

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4612]
The Connect link in the pod template shows up when the pod is still pending. Clicking it takes you to the Java console with a blank page and 503 service unavailable errors in web developer console.

We should probably show a reasonable error message as well in the Java console if we get a 503.

<img width="1552" alt="screen shot 2015-09-10 at 8 12 33 am" src="https://cloud.githubusercontent.com/assets/1167259/9787831/f12a518e-5793-11e5-9f86-cf26ee4152dc.png">

@gashcrumb

**Comment by liggitt** [comment]
also should probably only include the connect link if the status is active

**Comment by gashcrumb** [comment]
Yup, for sure...

**Comment by jwforres** [comment]
status active and readiness checks passed?

**Comment by gashcrumb** [comment]
@spadgett fyi -> https://github.com/openshift/origin/pull/4631
