### ISSUE TITLE
oc should work against a raw kube server

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4614]
`oc login` and `oc status` should at least function against a raw Kube server.

**Comment by liggitt** [comment]
What would you expect login to do?

**Comment by smarterclayton** [comment]
Discover it's a Kube server, use challenging client.

Also, we're hitting /osapi which is going to break in 3.1.

On Sep 10, 2015, at 11:43 AM, Jordan Liggitt <notifications@github.com>
wrote:

What would you expect login to do?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4614#issuecomment-139286124>.

**Comment by deads2k** [comment]
What endpoint should we use for getting the challenge?  Are you suggesting we gather the basic auth creds used and save them in the kubeconfig file instead of using a token?

**Comment by liggitt** [comment]
> we're hitting /osapi which is going to break in 3.1.

Not any more

**Comment by smarterclayton** [comment]
Still an issue, mostly fixed, someone should verify.
