### ISSUE TITLE
UI banner logo still a bit too hard to customize

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4617]
To customize the logo in an extension stylesheet, you need CSS like this:

```
.console-os .navbar-pf .navbar-header .navbar-brand .brand-logo {
  background-image: url("https://www.example.com/my-image.png");
  background-size: 160px 20px;
  width: 160px;
  height: 20px;
}
```

Two issues here:

1. The style is very specific, and a custom stylesheet would need the full selector due to CSS specificity. It would be nice if I could use something shorter like `.navbar-header .brand-logo` or perhaps an ID selector like `#banner-logo`.
1. I have to specify the height and width twice if it's not 160x10.

/cc @sg00dwin @jwforres @liggitt

**Comment by liggitt** [comment]
background-size shouldn't be set any more... should just need:
```
.brand-logo {
  background-image: url("https://www.example.com/my-image.png") !important;
  width: 160px;
  height: 20px;
}
```

**Comment by liggitt** [comment]
I could also live with an id selector
