### ISSUE TITLE
Is the --latest-images ignored?

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#4627]
I'm experiencing strange behavior with the latest master... I used to start OpenShift with `--latest-images` and then pull the latest Docker images for registry and router using `docker pull`.

However, last few days I see that the registry and router are not deployed. Just after I manually tag the two images as v1.0.5 and kick a new deployment for "router" and "docker-registry" they deploy successfully.

**Comment by mfojtik** [comment]
@ncdc @ironcladlou ?

**Comment by liggitt** [comment]
You also need to use `--latest-images` when running `oadm router` and `oadm registry`

**Comment by bparees** [comment]
when you docker pull the image gets the "docker.io/openshift/origin-FOO" tag.

If you have a local "openshift/origin-FOO" tag, that's still going to get used instead.

Is that what happened here?

**Comment by smarterclayton** [comment]
Closing due to age.
