### ISSUE TITLE
Project Overview page should stop prefixing Project in overview tab

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#4632]
This is a longstanding pet peeve of mine, but I see it all the time when I do a demo, or others do a demo, and it may be a dumb naming convention on my part.

Scenario:
Derek is demonstrating OpenShift and creates a Project called "Example Project"
Derek goes to Overview page for "Example Project" and sees

Project Example Project

Derek would prefer to just see

Example Project

with no prefix.

Derek would be less peeved if it said

Project: Example Project

Since that provides a clear separator between label and value.

cc @jwforres

**Comment by spadgett** [comment]
We were considering removing this header anyway since the project name is in the dropdown.
