### ISSUE TITLE
Cancelled builds with no build config have running icon in the UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4637]
This only happens when builds have no build config. We should look at putting the build details in a template to avoid duplicate code.

<img width="298" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/9825865/483f5b48-58a4-11e5-912a-7ae39ae07537.png">

/cc @jwforres

**Comment by spadgett** [comment]
@jwforres any chance your individual pages PR fixes this?

**Comment by jwforres** [comment]
Yes
