### ISSUE TITLE
Using origin/Vagrantfile cannot use s2i with builds from github.com

### ISSUE THREAD

**Issue by christian-posta** [openshift/origin#4638]
Using the 1.0.4 build of origin and the vagrantfile for associated build (https://github.com/openshift/origin/blob/v1.0.4/Vagrantfile).

Starting open shift with this script https://gist.github.com/christian-posta/b8f19497ee7de3b86aed/raw/867aa46ee5a258339045de40f4ff86a14200858b/hack.sh

When I try to do an s2i build (e.g., oc new-app jboss-eap6-openshift~https://github.com/christian-posta/openshift3mlbparks.git) I get the following

> [root@openshiftdev ~]# oc build-logs openshift3mlbparks-3
E0911 21:14:34.437122       1 git.go:127] fatal: unable to access 'https://github.com/christian-posta/openshift3mlbparks/': Could not resolve host: github.com; Unknown error
F0911 21:14:34.441615       1 builder.go:65] Build error: exit status 128

If I try using the builder image directly, I can reach github.com:

> [root@openshiftdev ~]# docker run -it --rm registry.access.redhat.com/jboss-eap-6/eap-openshift:6.4-239 bash
[jboss@b313eaa081e6 ~]$ curl -s -D - http://www.github.com -o /dev/null                                                                                            
HTTP/1.1 302 Found
Connection: close
Pragma: no-cache
cache-control: no-cache
Location: /

Any thoughts? An issue with the vagrant file? Or how I installed?

**Comment by christian-posta** [comment]
Do the s2i builds work for anyone using the vagrant image?

**Comment by bparees** [comment]
@christian-posta are you running the multiple minion or single minion vagrant environment?

can you run "oc new-app openshift/jenkins-1-centos7" and then oc rsh into the the pod and see if you can git clone from github there?

if not, can you dump the /etc/resolv.conf from that container?

**Comment by bparees** [comment]
closing based on age, feel free to reopen with requested information if this is still an issue.
