### ISSUE TITLE
"--param" option for `oc new-app ${image}` doesn't work

### ISSUE THREAD

**Issue by nak3** [openshift/origin#4644]
Env
---

~~~
$ openshift version
openshift v1.0.5-264-g11321c4
kubernetes v1.1.0-alpha.0-1605-g44c91b1
~~~

Issue
---
- Setting `--param` to `oc new-app ${image}` doesn't work. Please see reproduce steps.

Reproduce steps
---

step-1. Create mysqldb with `--param` option.

eg.
~~~
oc new-app openshift/mysql-55-centos7 --param=MYSQL_USER=user,MYSQL_PASSWORD=pass,MYSQL_DATABASE=testdb
~~~

or

~~~
oc new-app mysql --param=MYSQL_USER=user,MYSQL_PASSWORD=pass,MYSQL_DATABASE=testdb
~~~

step-2. See restarting the pod many times.

~~~
$ oc get pod
NAME                        READY     STATUS    RESTARTS   AGE
mysql-55-centos7-1-deploy   1/1       Running   0          6m
mysql-55-centos7-1-wd7d9    0/1       Running   16         6m
~~~

step-3. Check pod's log and it looks like parameters were not applied.

~~~
$ oc logs mysql-55-centos7-1-wd7d9
You must specify following environment variables:
  MYSQL_USER (regex: '^[a-zA-Z0-9_]+$')
  MYSQL_PASSWORD (regex: '^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$')
  MYSQL_DATABASE (regex: '^[a-zA-Z0-9_]+$')
Optional:
  MYSQL_ROOT_PASSWORD (regex: '^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$')
Settings:
  MYSQL_LOWER_CASE_TABLE_NAMES (default: 0)
  MYSQL_MAX_CONNECTIONS (default: 151)
  MYSQL_FT_MIN_WORD_LEN (default: 4)
  MYSQL_FT_MAX_WORD_LEN (default: 20)
  MYSQL_AIO (default: 1)
~~~

Additional Info
---
- Because of this issue, one of the examples in `oc new-app --help` doesn't work.

~~~
$ oc new-app --help
...

  // Use the public Docker Hub MySQL image to create an app. Generated artifacts will be labeled with db=mysql
  $ oc new-app mysql -l db=mysql
~~~

**Comment by nak3** [comment]
I understand this issue. In case that  we will create by `oc new-app`, I have to set by `--env` instead of `--param`. The command below worked well.

~~~
oc new-app mysql --env=MYSQL_USER=user,MYSQL_PASSWORD=pass,MYSQL_DATABASE=testdb
~~~

I think there should be documented. All examples of `oc new-app` is for template, and there are no mention about `--env` parameter.

**Comment by smarterclayton** [comment]
You don't even need `--env`, you can specify `oc new-app mysql MYSQL_USER=user MYSQL_PASSWORD=pass`. Agree --param is poorly doc'd.

**Comment by nak3** [comment]
You are right. `--env` was necessary. Then, when do we need to use `--env`?

~~~
$ oc new-app --help

  -e, --env=[]: Specify key value pairs of environment variables to set into each container.
~~~~

**Comment by smarterclayton** [comment]
Only if you want to.

On Mon, Sep 14, 2015 at 1:37 AM, Kenjiro Nakayama <notifications@github.com>
wrote:

> You are right. --env was necessary. Then, when do we need to use --env?
>
> $ oc new-app --help
>
>   -e, --env=[]: Specify key value pairs of environment variables to set into each container.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4644#issuecomment-139966014>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
i think this is resolved, @nak3 feel free to reopen if you think something still needs tweaking.

**Comment by nak3** [comment]
Thank you. Yes, it is no problem to close.
