### ISSUE TITLE
oc logs tries to use http instead of https

### ISSUE THREAD

**Issue by ibotty** [openshift/origin#4646]
using the docker image

    docker.io/openshift/origin:latest 2949335fd4b1

which corresponds to the following versions

    openshift v1.0.5-398-gcb4fa19
    kubernetes v1.1.0-alpha.0-1605-g44c91b1

running master and node on the same host using docker, I get the following error when trying to get logs.

```
> oc logs router-2-xlcm3
Error from server: Get http://aNode:10250/containerLogs/default/router-2-xlcm3/router: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

(i.e. it does not use https). I don't know where in my config I might have specified to not use tls.

Possibly unrelated, but I also get the following errors:

```
$ oc get componentstatus 
NAME                 STATUS      MESSAGE              ERROR
controller-manager   Unhealthy                        Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connection refused
scheduler            Unhealthy                        Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connection refused
```

(which makes sense, there is nothing listening on port 10251 and 10252. I guess that's because of 
da45616658a91dd5fb1eb3f942744fe9913c9d59 .)

**Comment by liggitt** [comment]
The componentstatus failure is unrelated (see https://github.com/openshift/origin/issues/3667)

How are you starting the master and node? To connect to nodes securely, you need to start the master from a config that provides TLS-related config (CA and/or client cert/key):
```
kubeletClientInfo:
  ca: ca.crt
  certFile: master.kubelet-client.crt
  keyFile: master.kubelet-client.key
  port: 10250
```

If you start an all-in-one, this gets set up for you automatically.

**Comment by ibotty** [comment]
yes, that did it. I forgot to include that part when merging with my external-kubernetes master-config.
