### ISSUE TITLE
Can't build from source (use of internal package not allowed)

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin#4648]
[root@23-25-149-225-static origin]# make clean build
rm -rf _output Godeps/_workspace/pkg
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
package github.com/openshift/origin/cmd/openshift
	imports github.com/openshift/origin/pkg/cmd/openshift
	imports github.com/openshift/origin/pkg/cmd/admin
	imports github.com/openshift/origin/pkg/cmd/admin/cert
	imports github.com/openshift/origin/pkg/cmd/server/admin
	imports github.com/openshift/origin/pkg/cmd/cli/describe
	imports github.com/gonum/graph/internal: use of internal package not allowed
package github.com/openshift/origin/cmd/openshift
	imports github.com/openshift/origin/pkg/cmd/openshift
	imports github.com/openshift/origin/pkg/cmd/experimental/diagnostics
	imports github.com/openshift/origin/pkg/diagnostics/host
	imports github.com/openshift/origin/pkg/cmd/server/api/validation
	imports k8s.io/kubernetes/cmd/kube-apiserver/app
	imports k8s.io/kubernetes/plugin/pkg/admission/serviceaccount
	imports k8s.io/kubernetes/pkg/kubelet
	imports k8s.io/kubernetes/pkg/kubelet/cadvisor
	imports github.com/google/cadvisor/http
	imports github.com/google/cadvisor/api
	imports github.com/google/cadvisor/manager
	imports github.com/google/cadvisor/utils/cloudinfo
	imports github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata
	imports google.golang.org/cloud/internal: use of internal package not allowed
make: *** [build] Error 1

**Comment by liggitt** [comment]
Probably a go1.5 issue (they changed package rules). Try building with 1.4.x

**Comment by deanpeterson** [comment]
My luck; my redhat subscription expired just this weekend and I do not have gcc installed and that causes an error while using 1.4.x.  I am not able to install anything it seems.  I will either have to wait until work on Monday when our office can renew or install CentOS on this machine to continue before then.  Thanks for the help!

**Comment by deanpeterson** [comment]
Switching to 1.4.2 worked.
