### ISSUE TITLE
system:admin can't login (master)

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin#4650]
I just pulled down the latest source and built the binaries from master.  Previously when I ./oc login with system:admin, it would not ask for a password and just log me in.  Now it asks for a password.  What is the default password?

**Comment by deanpeterson** [comment]
I can just login using ./oc login -u system:admin; when I just use ./oc login, it asks for both a username and password now.  Anyway, I'm past the problem.

**Comment by liggitt** [comment]
system:admin is a cert-based user, not username/password based. `oc login -u <username>` switched to that user if credentials already exist for them (which they did in your case)

**Comment by deanpeterson** [comment]
Ah, makes sense now, thanks!

**Comment by dexterac** [comment]
I tried `oc login -u system:admin -n default --config=.kube/config` and it still would ask me for a password
