### ISSUE TITLE
openshift router uses resolv.conf from host, so (possibly) no cluster dns

### ISSUE THREAD

**Issue by ibotty** [openshift/origin#4661]
My `--host-network=yes` deployed router does not use cluster dns, so it logs

```
pkg/router/controller/factory/factory.go:58: Failed to list *api.Route: Get https://openshift.default.svc.cluster.local:8443/oapi/v1/routes: dial tcp: lookup openshift.default.svc.cluster.local: no such host
```

``` sh
> kubectl exec router-4-2ciej cat /etc/resolv.conf
```

confirms that it's the hosts resolv.conf. On a busybox image, the right `resolv.conf` is used (prepended master nameserver and cluster search paths). 

I can of course work around it by enabling cluster dns on the hosts as well, but I prefer not to do that.

**Comment by smarterclayton** [comment]
We've discussed this but eventually the cluster DNS is going to resolve on hosts so that the docker daemon can resolve the registry service name.  What were your concerns with enabling cluster DNS on the hosts?

**Comment by smarterclayton** [comment]
@ncdc

**Comment by ibotty** [comment]
Some startup scripts were unnecessarily slow when using a not-yet-responding nameserver. I don't rely on DNS on startup anymore now though, so I revisited the decision to use cluster dns also on the host. Regarding the general design, I'd still like to keep the cluster dns separate because I like the clear separation between the openshift/kubernetes cluster and the host. I can totally understand the problem regarding registry dns resolution for the docker daemon. I don't know how that can be solved without it.

**Comment by ibotty** [comment]
And constructively: I did not see it mentioned in the deployment docs, that it's a requirement to enable cluster dns on the host as well. That's the only thing left of this bug report, I suppose.
