### ISSUE TITLE
OpenStack Swift support for docker-registry

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#4672]
To get OpenStack Swift support for the docker-registry we would need to update the deps to 2.1.1 since this was merged last July :

https://github.com/docker/distribution/pull/493

support for OpenStack Swift would allow for nice things like HA for on premise clouds

**Comment by ncdc** [comment]
Blocked by #3333

**Comment by pweil-** [comment]
@miminar is working to update the godeps in his pruning work https://github.com/openshift/origin/pull/5073
