### ISSUE TITLE
[post-rebase] Bump ldapserver to v1.0

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#4675]
https://github.com/vjeantet/ldapserver/releases/tag/v1.0

Then we can stop carrying https://github.com/openshift/origin/commit/de466c41217f13ce8837cdcb6942d3094dcfc779

@liggitt fyi

**Comment by liggitt** [comment]
Or you could just bump godep.json to 19fbc46ed12348d5122812c8303fb82e49b6c25d since my upstream already merged... I haven't had time to audit all the following commits, which I would want to
