### ISSUE TITLE
Rolling updater init can fail with resource conflicts updating deployment

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#4678]
The rolling updater initialization can sometimes fail to prepare the deployment for update due to a resource conflict updating the deployment resource. The code should use retries so that the deployment doesn't fail unnecessarily.

**Comment by ironcladlou** [comment]
cc @thoraxe - this addresses the conflict error you often see during deployments.

**Comment by thoraxe** [comment]
:+1:
