### ISSUE TITLE
Topology view doesn't filter when a filter is active

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#4681]
tested on Chrome 45 and IE 11

<img width="1102" alt="screen shot 2015-09-15 at 12 45 13 pm" src="https://cloud.githubusercontent.com/assets/1874151/9883362/b5f1885e-5ba7-11e5-8435-af149173908d.png">

**Comment by sg00dwin** [comment]
@jwforres topology filter issue

**Comment by jwforres** [comment]
@stefwalter

**Comment by stefwalter** [comment]
I'll try and look at this. Any hints on where the filtering magic happens in the code?

**Comment by liggitt** [comment]
Should be in the overview controller. It filters `$scope.unfilteredServices` and updates `$scope.services`, I think

**Comment by stefwalter** [comment]
[![Fixed behavior](http://img.youtube.com/vi/95I-3byMC8Q/0.jpg)](http://www.youtube.com/watch?v=95I-3byMC8Q)]
