### ISSUE TITLE
Go Vet failing on Travis

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4682]
Seeing result like the following:
```
hack/verify-govet.sh
pkg/generate/app/app_test.go:317: ExampleGenerateSimpleDockerApp refers to unknown identifier: GenerateSimpleDockerApp
```

No failure output from the script, and not reproducing this locally.

**Comment by stevekuznetsov** [comment]
This is caused by an update to `go vet`: https://github.com/golang/tools/commit/a25a8d567b492f9a659e1e1838cc093d5bf278a0

We need to ensure that Travis is using `git checkout` to grab the currently-supported version of tools used in the CI flow after installing them. @derekwaynecarr @bparees

**Comment by stevekuznetsov** [comment]
Also seeing 
```
pkg/cmd/cli/cmd/startbuild.go:393: arg &list.Items[i].Namespace for printf verb %s of wrong type: *string
```

**Comment by deads2k** [comment]
I'm getting something different on master: https://gist.github.com/deads2k/8f294071a13741f94dc6

**Comment by stevekuznetsov** [comment]
@deads2k Indeed, one your errors is:
```
pkg/generate/app/cmd/newapp_test.go:805: missing argument for Errorf("%s"): format reads arg 1, have only 0 args
```

The corresponding line is:
```
t.Errorf("%s: did not get any ports in service")
```

@deads2k Can you please post Go version and Go Tools version (get from `git log` inside of `$GOPATH/src/golang.org/x/tools/`)? 

@liggitt This does not seem deterministic.

**Comment by csrwng** [comment]
go version
```
go version go1.4.2 linux/amd64
```

go vet git commit:
```
c262de8 tools/cmd/vet: Sort checks list alphabetically.
```

origin head is at:
```
916b949 Merge pull request #4674 from mnagy/allow_ginkgo_focus
```

Output of hack/verify-govet.sh:
```
pkg/generate/app/app_test.go:317: ExampleGenerateSimpleDockerApp refers to unknown identifier: GenerateSimpleDockerApp
```

**Comment by ironcladlou** [comment]
go version go1.4.2 linux/amd64
tools: `1330b28 godoc: hide and block share functionality from specific countries`
origin: `916b949 Merge pull request #4674 from mnagy/allow_ginkgo_focus`
vet output: https://gist.githubusercontent.com/ironcladlou/ee9e956a57ce2dd98bf2/raw/25abf4049882e8b77763e523cfe85d2341bf456d/gistfile1.txt

**Comment by stevekuznetsov** [comment]
@ironcladlou could you please run `go get -u` on `go vet` so we could compare output on the latest `go vet` version?

**Comment by ironcladlou** [comment]
go version go1.4.2 linux/amd64
tools: c262de8 tools/cmd/vet: Sort checks list alphabetically.
origin: 916b949 Merge pull request #4674 from mnagy/allow_ginkgo_focus
vet output: https://gist.github.com/ironcladlou/ee9e956a57ce2dd98bf2#file-using-tools-c262de8

**Comment by stevekuznetsov** [comment]
Tried testing `go vet`:
```sh
$ docker run -it centos:latest bash
# yum install -y git wget 
# wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
# tar -C /usr/local/ -xzf go1.4.2.linux-amd64.tar.gz
# export PATH=$PATH:/usr/local/go
# mkdir go && export GOPATH=/root/go
# go get golang.org/x/tools/cmd/vet
# mkdir -p $GOPATH/src/github.com/openshift && cd $GOPATH/src/github.com/openshift && git clone https://github.com/openshift/origin.git
# ./origin/hack/verify-govet.sh
pkg/generate/app/app_test.go:317: ExampleGenerateSimpleDockerApp refers to unknown identifier: GenerateSimpleDockerApp
```
This is with `go version` `go1.4.2 linux/amd64`. `go vet` at `HEAD: commit c262de870b618eed648983aa994b03bc04641c72`. This is the output that @csrwng gets.

While this does not seem to return the same thing for each workstation, it *does* seem to be self-consistent on one workstation.

**Comment by stevekuznetsov** [comment]
Pushing these questions upstream...

**Comment by stevekuznetsov** [comment]
@deads2k Research indicates you are running an old version of `go vet`. Could you also please `go get -u golang.org/x/tools/cmd/vet` and re-run the script?

**Comment by stevekuznetsov** [comment]
@deads2k bump

**Comment by deads2k** [comment]
@stevekuznetsov We spoke in person on Friday.  Is is possible for you to pin the level of the `go vet` tooling and ruleset?  Doing that and manually updating every iteration or two is much more manageable than trying to deal with different results on developer machines.

**Comment by liggitt** [comment]
Version locked for vagrant/jenkins in https://github.com/openshift/vagrant-openshift/pull/322

@stevekuznetsov can you do the same in `hack/install-tools.sh` (though I think you need to add a build step after checking out the locked version of `go vet`)

**Comment by stevekuznetsov** [comment]
@liggitt I can do that, yes. Currently we are also getting no answers upstream for this. Unclear how to proceed.

**Comment by stevekuznetsov** [comment]
@deads2k Has the following output after upgrading to the latest 1.4.2 build and updating `go vet`: https://gist.github.com/deads2k/5e5703dadf49c5302dc2

Investigating the output of the `find` command now.

**Comment by stevekuznetsov** [comment]
No difference in output of `hack/util.sh::find_files` between different workstations that have differences in `go vet` output.

**Comment by ironcladlou** [comment]
@stevekuznetsov and I were talking and we realized that `hack/verify-govet.sh` isn't actually setting GOPATH internally. This means `go vet` will resolve dependencies from whatever random GOPATH happens to be set in the user environment.

I'd be curious to see what output everyone gets from this:

```
make clean build
GOPATH=$PWD/_output/local/go:$(godep path) hack/verify-govet.sh
```

Here's mine.

go version go1.4.2 linux/amd64
tools: c262de8 tools/cmd/vet: Sort checks list alphabetically.
origin: 8f33704 Merge pull request #4813 from kargakis/new-app-fix
vet output: https://gist.github.com/ironcladlou/ee9e956a57ce2dd98bf2#file-using-tools-c262de8-and-corrected-gopath

**Comment by liggitt** [comment]
I'm sure that doesn't help, but not for errors in origin source files, right?

**Comment by ironcladlou** [comment]
>I'm sure that doesn't help, but not for errors in origin source files, right?

Origin source would also be interpreted from GOPATH, instead of `_output/local/go` (the target of `hack/buid-go.sh`), which aren't necessarily the same.

**Comment by liggitt** [comment]
doesn't go vet work on source, not the output binaries?

**Comment by ironcladlou** [comment]
>doesn't go vet work on source, not the output binaries?

Yes, but it's still not guaranteed the origin source in your GOPATH is the same as the source copied to `_output/local/go` at the time of build. For example, if you ran `hack/build-go.sh` and then checked out a new branch of origin without re-building.

For this tool invocation to be repeatable, I think GOPATH has to be set (in addition to the tools/go version pinning).

**Comment by stevekuznetsov** [comment]
In order to test Godep `$GOPATH` settings, could @deads2k, @ironcladlou and @csrwng please run the following on a fresh master and stick the paste here:
```sh
$ go get -u golang.org/x/tools/cmd/vet
$ GOPATH=$GOPATH/src/github.com/Godeps/_workspace/:$GOPATH go tool vet pkg/ 2&>1 > output.txt
```
`go get -u` may need `sudo` privilege to run.

**Comment by ironcladlou** [comment]
I still say you need `$PWD/_output/local/go:$(godep path)` as I described in https://github.com/openshift/origin/issues/4682#issuecomment-144152245. Any new counterarguments?

**Comment by stevekuznetsov** [comment]
Yes, typo, that does add value. Good call.

**Comment by csrwng** [comment]
https://gist.github.com/csrwng/a9bf9f881de62e5e20ce

**Comment by stevekuznetsov** [comment]
Output: https://gist.github.com/stevekuznetsov/19169004e7d6dd2f8e31
HEAD: `b2e97700db09415052d60c02c9edf49bfaf506b3 Merge pull request #4663 from kargakis/rebase-kube`

**Comment by csrwng** [comment]
@stevekuznetsov same commit for me

**Comment by stevekuznetsov** [comment]
@csrwng Good news, other than some weird numbering issues, it looks like we converge: https://www.diffchecker.com/nxwaxrvg

**Comment by ironcladlou** [comment]
HEAD @ f95a0d554929cbd00fcc74749a1bb8bcd2154263 Merge pull request #4866 from kargakis/import-ethtool

https://gist.github.com/ironcladlou/ee9e956a57ce2dd98bf2#file-using-tools-c262de8-and-corrected-gopath

**Comment by stevekuznetsov** [comment]
@ironcladlou Also converged. I'll get the fix rolled out this morning.
