### ISSUE TITLE
bug in docker run of origin as of 1.0.6, docs wrong?

### ISSUE THREAD

**Issue by jmccormick2001** [openshift/origin#4690]
I'm trying the 1.0.6 version of Origin as a docker container

I'm seeing volume errors when trying to use emptyDir volumes.  This worked with 1.0.4.

I notice the docs suggest a different 'docker run' of origin that in 1.0.4.

Are the docs correct?  it seems several things are not mounted any longer.

I'm getting the following errors in the origin docker log:

E0915 21:29:37.301262       1 kubelet.go:1206] Unable to mount volumes for pod "docker-registry-1-deploy_default": exit status 32; skipping pod
E0915 21:29:37.305753       1 pod_workers.go:111] Error syncing pod ae94d295-5bef-11e5-895d-5404a613ba84, skipping: exit status 32
E0915 21:29:37.324990       1 kubelet.go:1206] Unable to mount volumes for pod "pg-standalone_pgproject": exit status 32; skipping pod
E0915 21:29:37.338749       1 pod_workers.go:111] Error syncing pod d1bd98ca-5bef-11e5-895d-5404a613ba84, skipping: exit status 32

is the 'oadm registry --create' no longer required as of 1.0.6?

thanks

**Comment by pweil-** [comment]
@jmccormick2001 - is this still an issue.  The latest and greatest for the registry is `oadm registry --config=admin.kubeconfig --credentials=openshift-registry.kubeconfig`.   If you are trying to set up persistent storage for the registry more information can be found here: https://docs.openshift.org/latest/install_config/install/docker_registry.html#storage-for-the-registry

**Comment by pweil-** [comment]
Please reopen if this is still an issue for you.  Please see the latest docs in the comment above.
