### ISSUE TITLE
should the BuildConfig metadata be extended to allow build configs to be linked to developer tools/web apps?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#4694]
This relates a little to #4693 but I figured I'd separate tool links and environments (as environments need at least 2 strings); we could get by with annotations for this issue - but it feels like nicer JSON/YAML might be a good idea.

Typically there are a number of web based developer tools for projects such as browsing the git source code, code reviews, Jenkins build/pipeline, issue tracker, web based editors, UI wizards/tools, chat room, team page, issue tracker, docker registry, nexus/artifactory repository, wiki/site/release notes, search engine etc.

e.g. here's an example of the current fabric8 console page showing the code, tools, environments & social stuff for each  BuildConfig. Don't worry too much about the page layout; it needs lots of UX work ;)

<img width="1740" alt="projectspage" src="https://cloud.githubusercontent.com/assets/30140/9899392/5b53cb78-5c51-11e5-9340-4d4cd2f6902f.png">

For now we've gone with annotations on BulidConfig; but given they are flat key-value pairs it feels a little bit of a hack. It feels like having links with human readable names & labels on them might be more flexible to let developers link all their various tools/reports together in one page thats easier to group/slice/dice/render.

**Comment by smarterclayton** [comment]
The answer is yes. :)  But annotations are the place to start.

**Comment by jstrachan** [comment]
@smarterclayton we've been using annotations for a while now as hack; hence the reason for this issue :)  as its kinda hard to define things like the multiple environments of a project in annotations without feeling really dirty. 

Is JSON inside an annotation value a bad thing to do these days if we're only targetting 3.1?

**Comment by smarterclayton** [comment]
We use JSON inside annotations ourselves :)

**Comment by jstrachan** [comment]
@smarterclayton awesome thanks!

Got an example anywhere of now to do it nicely in terms of escaping etc?

**Comment by smarterclayton** [comment]
In our case we serialize to json then set the annotation value to the
string.  Deployment configs encode themselves onto the replication
controller as an annotation, so any RC created by a DC should have an
example.

On Sep 25, 2015, at 11:31 AM, James Strachan <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> awesome thanks!

Got an example anywhere of now to do it nicely in terms of escaping etc?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4694#issuecomment-143252891>.

**Comment by bparees** [comment]
lowering to p3 given that this can be done in an annotation today.

**Comment by bparees** [comment]
Annotations seem like the right solution for this since first class api fields are less flexible.
