### ISSUE TITLE
Ability to import an Docker image from tar?

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#4695]
Is there an easy way for me to import an arbitrary Docker image I have available locally as a 'tar' file into OpenShift Docker Registry (and make it available for IS)?

Given that I have this IS created and Docker Registry running:

``` json
     {
        "kind": "ImageStream",
        "apiVersion": "v1",
        "metadata": {
           "name": "foo",
        },
        "spec": {
           "dockerImageRepository": "foo",
           "tags": [
             {
               "name": "latest"
             }
           ]
        }
     }
```

I want to do:

``` console
cat foo.tar | oc import-image foo -f -
```

@ncdc is this possible? (I've got this question from sale folks that are demoing on customer site....)

**Comment by mfojtik** [comment]
@bparees @ncdc maybe this is already possible but I'm not able to find any docs :/

**Comment by mfojtik** [comment]
@ncdc is the approach to login to registry and tag the local image to registry as :latest ? I think we should document that way of importing images somewhere.

**Comment by mfojtik** [comment]
@smarterclayton FYI

**Comment by ncdc** [comment]
You have to tag and push. Also, at least the way things are now, you
shouldn't set spec dockerImageRepository if you want to have the stream be
backed by the integrated registry.

**Comment by mfojtik** [comment]
@ncdc in that case, the DockerPullSpec has to match the IS name?

so REGISTRY_IP:PORT/namespace/foo:latest ?

**Comment by ncdc** [comment]
Yes, that's always been the case.

**Comment by mfojtik** [comment]
@ncdc I found that the IS is created automatically when you push the image to registry? Is that true?

**Comment by ncdc** [comment]
If you have the appropriate permissions, yes.

**Comment by mfojtik** [comment]
@ncdc that fixed it, but I still think we should have documented this somewhere. Do you know if we have some docs about "Importing Docker image to OpenShift" ? If not I can just add section describing how to do that (got another guy asking the same thing few days ago).

**Comment by soltysh** [comment]
There's a [Using Images section](https://docs.openshift.org/latest/using_images/overview.html) worth expanding with those usercases, imho.

**Comment by mpbravo** [comment]
This howto can be added to the documentation, to detail the necessary steps:
http://www.opensourcerers.org/importing-an-external-docker-image-into-red-hat-openshift-v3/

**Comment by pweil-** [comment]
https://docs.openshift.org/latest/dev_guide/managing_images.html#importing-tag-and-image-metadata

**Comment by soltysh** [comment]
@pweil- I don't think the link is a solution to the original request. It is about importing entire image into internal registry. Something like the following series of commands: 
```
docker load <the tar>
docker tag <the image> <internal registry/is:tag>
docker push <internal registry/is:tag>
```
Which will result in the image being available in the internal registry and IS created upon push. 
Importing just the metadata from tar doesn't make sense, unless the image is available in some repo, in which case regular `oc import-image` is fine.

**Comment by smarterclayton** [comment]
This is https://github.com/openshift/origin/pull/14470 mostly

**Comment by pweil-** [comment]
Upstreamed: https://trello.com/c/dUYS0Hb1
