### ISSUE TITLE
Cannot create image-streams/image-streams-centos7.json

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#4696]
I try to create an image stream
```
oc create -f \
    examples/image-streams/image-streams-centos7.json \
    -n openshift
```
But of course I get the following error. 
```
the path "examples/image-streams/image-streams-centos7.json" does not exist
```
So I do the following (as admin):
```
mkdir -p examples/image-streams
cd examples/image-streams
wget \
> https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-centos7.json
```
After that it's possible to do the create, but is it the real way you have to do this? It looks very devious

**Comment by rhcarvalho** [comment]
@lorenzvth7 where did you take the example from? Could you please provide me a link?

If you don't have the file locally, you can create the image streams pointing to a URL:
```
$ oc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-centos7.json -n openshift
```

BTW, you might ask for help using the users mailing-list:
https://lists.openshift.redhat.com/openshiftmm/listinfo/users

**Comment by bparees** [comment]
closing based on age, @lorenzvth7 feel free to reopen if you want to discuss further.
