### ISSUE TITLE
Container PostgreSQL is restarting frequently

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#4708]
My PostgreSQL container is restarting the whole time. There is an exclamation mark in the web console.
I did the following to create the container. I used a template.
```
[root@ip-10-0-0-97 examples]# mkdir -p db-templates
[root@ip-10-0-0-97 examples]# ls
db-templates  hello-openshift  image-streams  sample-app
[root@ip-10-0-0-97 examples]# cd db-templates/
[root@ip-10-0-0-97 db-templates]# ls
[root@ip-10-0-0-97 db-templates]# wget https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/postgresql-ephemeral-template.json     
--2015-09-17 11:33:19--  https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/postgresql-ephemeral-template.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.18.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.18.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4620 (4.5K) [text/plain]
Saving to: 'postgresql-ephemeral-template.json'
2015-09-17 11:33:19 (969 MB/s) - 'postgresql-ephemeral-template.json' saved [4620/4620]
[root@ip-10-0-0-97 openshift]# oc create -f \
>     examples/db-templates -n openshift
```
After the creation of my template (which appears in my console) I create the application.
```
[root@ip-10-0-0-97 openshift]# oc new-project testdb 
Now using project "testdb" on server "https://10.0.0.97:8443".   
[root@ip-10-0-0-97 openshift]# oc new-app -f examples/db-templates/postgresql-ephemeral-template.json 
services/postgresql
deploymentconfigs/postgresql
Service "postgresql" created at 172.30.186.55 with port mappings 5432.
Run 'oc status' to view your app.
[root@ip-10-0-0-97 openshift]# oc status
In project testdb on server https://10.0.0.97:8443

service/postgresql - 172.30.186.55:5432
  dc/postgresql deploys openshift/postgresql:latest 
    #1 deployed 15 minutes ago - 1 pod
```
The same issue occurs when I'm developing with the web console

When I try to check the logs of this pod:
```
[root@ip-10-0-0-97 openshift]# oc logs postgresql-1-0x9ew
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

**Comment by mfojtik** [comment]
@rhcarvalho fyi

**Comment by lorenzvth7** [comment]
@mfojtik don't you have an explanation? Thanks

**Comment by rhcarvalho** [comment]
@lorenzvth7 I could not reproduce that. I can instantiate the template, create a table, insert values, read them back.
BTW, this single line is enough to instantiate the template in the current project:

```
$ oc new-app examples/db-templates/postgresql-ephemeral-template.json
```

or, if you don't have the file locally, you can point to a URL:

```
$ oc new-app -f https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/postgresql-ephemeral-template.json
```

@lorenzvth7 could you please make sure you have the latest image?

**Comment by lorenzvth7** [comment]
Yes, The problem occurs for every database I've made. (mysql/postgresql, with template, without template)

**Comment by rhcarvalho** [comment]
Could you please run the commands below?

1\. Could you also check you have the same image id?

```
$ docker images | grep postgresql
docker.io/openshift/postgresql-92-centos7      latest              8d440e45b666
```

2\. I'm creating a docker container based on the PostgreSQL image, it starts normally, I can see the files created under  /var/lib/pgsql/data/. Do you get similar output?

```
$ docker run -d --name pg -e POSTGRESQL_USER=u -e POSTGRESQL_PASSWORD=pw -e POSTGRESQL_DATABASE=db openshift/postgresql-92-centos7
$ docker exec -it pg bash
bash-4.2$ ls -la /var/lib/pgsql/data/
total 104
drwx------. 15 postgres postgres  4096 Sep 12 21:49 .
drwxrwxrwx.  4 postgres postgres  4096 Sep 12 21:49 ..
-rw-------.  1 postgres postgres     4 Sep 12 21:49 PG_VERSION
drwx------.  6 postgres postgres  4096 Sep 12 21:49 base
drwx------.  2 postgres postgres  4096 Sep 12 21:50 global
drwx------.  2 postgres postgres  4096 Sep 12 21:49 pg_clog
-rw-------.  1 postgres postgres  4674 Sep 12 21:49 pg_hba.conf
-rw-------.  1 postgres postgres  1636 Sep 12 21:49 pg_ident.conf
drwx------.  2 postgres postgres  4096 Sep 12 21:49 pg_log
drwx------.  4 postgres postgres  4096 Sep 12 21:49 pg_multixact
drwx------.  2 postgres postgres  4096 Sep 12 21:49 pg_notify
drwx------.  2 postgres postgres  4096 Sep 12 21:49 pg_serial
drwx------.  2 postgres postgres  4096 Sep 12 21:49 pg_snapshots
drwx------.  2 postgres postgres  4096 Sep 12 21:50 pg_stat_tmp
drwx------.  2 postgres postgres  4096 Sep 12 21:49 pg_subtrans
drwx------.  2 postgres postgres  4096 Sep 12 21:49 pg_tblspc
drwx------.  2 postgres postgres  4096 Sep 12 21:49 pg_twophase
drwx------.  3 postgres postgres  4096 Sep 12 21:49 pg_xlog
-rw-------.  1 postgres postgres 19862 Sep 12 21:49 postgresql.conf
-rw-------.  1 postgres postgres    43 Sep 12 21:49 postmaster.opts
-rw-------.  1 postgres postgres    80 Sep 12 21:49 postmaster.pid
$ docker stop pg
$ docker rm pg
```

**Comment by lorenzvth7** [comment]
The first thing is the same. But now I see I have a pod running of the postgresql but no container.

**Comment by rhcarvalho** [comment]
@lorenzvth7 I suspect this might have to do with your other issue https://github.com/openshift/origin/issues/4676.
@ncdc could you have a look here? I suspect this might be related to running openshift as a docker container and missing selinux labels on volumes (in this case the volume that backs up /var/lib/pgsql).

**Comment by rhcarvalho** [comment]
@lorenzvth7 did you try the updated steps mentioned here https://github.com/openshift/origin/issues/4676#issuecomment-145042403? Does that solve your problem deploying the database images?

**Comment by lorenzvth7** [comment]
Not really, now I have the same issue when and I'm working in a multi-node environment. I've done the advanced installation so I'm not running OpenShift in a Dockercontainer. A DB is working when I'm using this template (https://github.com/openshift/origin/blob/master/examples/sample-app/README.md). But not when I'm creating an application directly from an image (oc new-app mysql). Same issue with oc new-app wordpress

**Comment by lorenzvth7** [comment]
I had to specify required environment variables (they're not automatically generated):
```oc new-app mysql -e MYSQL_USER=user,MYSQL_PASSWORD=pass,MYSQL_DATABASE=db```
