### ISSUE TITLE
No annotations are being added to cloned builds

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#4709]
Today cloned builds do not get the openshift.io/build.number annotation. Cloned builds should increase the sequence number for builds, and get the build.number annotation.

They should also get an openshift.io/build.clone-of that references which build this was cloned from.  Debatable whether this should be just the build number of what it was cloned from or if it should actually be the name of it. Depends on what we see it being used for.  If we go with name now it will give us more options later.

**Comment by jwforres** [comment]
@bparees

**Comment by liggitt** [comment]
Not sure about the sequence number.

**Comment by liggitt** [comment]
@csrwng

**Comment by jwforres** [comment]
@liggitt @smarterclayton says we are increasing sequence number on deployments when we clone, so we are inconsistent today.  What is your argument against increasing sequence number?

**Comment by csrwng** [comment]
@jwforres just so that I understand, if you have build-4 and you clone it, you expect build-5 ?

**Comment by jwforres** [comment]
Yes, that is consistent with other systems, like Jenkins

**Comment by csrwng** [comment]
I guess we've done it the way it is because you can readily tell from the name what build it came from, but if we're going to put that in an annotation and display it in the UI, I don't have any objection. @bparees ?

**Comment by smarterclayton** [comment]
Isn't changing the sequence number going to trigger a build?

**Comment by csrwng** [comment]
not today

**Comment by liggitt** [comment]
really? I thought grabbing a sequence number for a clone was going to require rearchitecting build allocations. "clone" of a deploy is really a rollback, right, which is different?

**Comment by csrwng** [comment]
I don't think it's any different than generating a new build from a build config, except that you're using another build as the source for your build object. So we'd need to make this function https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L540 behave more like https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L285

**Comment by csrwng** [comment]
@soltysh since you implemented the clone on generate, any thoughts?

**Comment by bparees** [comment]
might as well put the full build name in the clone annotation.

otherwise i'm fine with this as long as @soltysh doesn't have a technical reason why he went with appending a timestamp over bumping the sequence number.

**Comment by soltysh** [comment]
At the time I wanted to create subnumbers for cloned builds. That was
supposed to allow infinite clones from already existing clones.
Unfortunately I failed with that idea and went with timestamped
subnumbers.  I'm ok with bumping the overall build sequence.  I'll have a
closer look at that later today.

**Comment by soltysh** [comment]
There's a discussion on changing that behavior already happening in #3368

**Comment by csrwng** [comment]
Yup, moving to the sequential numbers would fix the bug brought up in that issue (builds not getting named correctly after seq > 9). I had coded a fix for that, but using sequential numbers is much better. Will work on a pull.

**Comment by soltysh** [comment]
Awesome thanks @csrwng !

**Comment by bparees** [comment]
@csrwng assigning to you since you said you would work on a pull, but i can take it if you didn't actually start anything yet.
