### ISSUE TITLE
Fix new-app unit tests to not require external network access

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#4713]
Currently new-app unit tests are cloning from Github. The dependency needs to be removed at least for unit tests.

**Comment by csrwng** [comment]
@smarterclayton

**Comment by ncdc** [comment]
See #3624

**Comment by smarterclayton** [comment]
Let me unify this with my Dockerfile changes for build.

On Sep 17, 2015, at 2:09 PM, Cesar Wong <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4713#issuecomment-141169614>.

**Comment by csrwng** [comment]
Fixed by https://github.com/openshift/origin/pull/7276
