### ISSUE TITLE
Missing required template parameter returns FieldInvalid error, not FieldRequired error

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4718]
Follow up from https://github.com/openshift/origin/pull/4641#issuecomment-140249395

That PR changed all errors resulting from a GenerateParameterValues error to a FieldInvalid error. Previously, a missing "required" parameter value generated a FieldRequired error, which was correct.

A client can infer things from a "FieldRequired" error. With a "FieldInvalid" error, all it can do is display the message from the API, and the error built in #4641 doesn't display well at all. In the case where a required value wasn't provided, we should use the more specific error code

cc @bparees

**Comment by bparees** [comment]
It didn't return  field required before either. 

It returned a field invalid which wrapped a field required error as the "value" of the invalid field. Which was definitely wrong.

**Comment by liggitt** [comment]
so I see. still, it should be a FieldRequired error now :)

**Comment by bparees** [comment]
sure.  just defending my commit from charges of regression. :)
