### ISSUE TITLE
Reconsider which objects we filter on the console overview

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#4722]
Today we only provide suggestions for the labels on the services and the filter only shows/hides blocks based on what services are visible.

This currently means things that aren't routed to by services never get filtered out.

The problem with providing label suggestions for all the resource types / filtering all the resource types is that causes weird behavior when some objects in a group have a label and others don't.

**Comment by jwforres** [comment]
cc @liggitt

**Comment by spadgett** [comment]
Closing as we've removed the label filter.
