### ISSUE TITLE
No option to create master config by oadm command

### ISSUE THREAD

**Issue by nak3** [openshift/origin#4733]
Even though oadm has `create-node-config`[1], there are no option to create master config by oadm.
I know it is possible to create by `openshfit start --write-config`, but it is better to add it as oadm's option. 
I need to create openshift master config for manual installation.

[1]
~~~
# oadm -h
  ...
  create-node-config                Create a configuration bundle for a node
~~~

**Comment by nak3** [comment]
@liggitt Since we close https://github.com/openshift/origin/pull/4760, we should close this issue?

**Comment by liggitt** [comment]
I think so, yes
