### ISSUE TITLE
Crash when starting build

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#4734]
on a latest installed origin (with ansible) : 

<pre>
[root@devstack ~]# oc version
oc v1.0.5-4-g3eee7d2-dirty
kubernetes v1.1.0-alpha.0-1605-g44c91b1
[root@devstack ~]#
</pre>

I am getting a crash when trying to start a build. Here is the log from systemd :

http://pastebin.com/ffxnpYzW

**Comment by chmouel** [comment]
I had by the way no reg deployed not sure if that's what cause the problem, nevertheless it prob shoudl not crash

**Comment by liggitt** [comment]
Sep 19 07:33:01 devstack.chmouel.com openshift-master[48369]: runtime.sigpanic()
Sep 19 07:33:01 devstack.chmouel.com openshift-master[48369]: /usr/lib/golang/src/runtime/sigpanic_unix.go:26 +0x274 fp=0xc20bbb9aa8 sp=0xc20bbb9a58
Sep 19 07:33:01 devstack.chmouel.com openshift-master[48369]: github.com/openshift/origin/pkg/build/generator.(*BuildGenerator).updateImageTriggers(0xc209fbff40, 0x7fa5fb41d8c8, 0xc20d033da0, 0xc20b861380, 0x0, 0x0, 0x0, 0x0)
Sep 19 07:33:01 devstack.chmouel.com openshift-master[48369]: /builddir/build/BUILD/openshift-git-5411.3eee7d2/_build/src/github.com/openshift/origin/pkg/build/generator/generator.go:237 +0xa21 fp=0xc20bbb9cb0 sp=0xc20bbb9aa8
Sep 19 07:33:01 devstack.chmouel.com openshift-master[48369]: github.com/openshift/origin/pkg/build/generator.(*BuildGenerator).Instantiate(0xc209fbff40, 0x7fa5fb41d8c8, 0xc20d033da0, 0xc20cec8e00, 0x7fa5fb4015f0, 0x0, 0x0)

**Comment by liggitt** [comment]
@bparees @csrwng

**Comment by liggitt** [comment]
https://github.com/openshift/origin/pull/4505 may have resolved it, but can @csrwng take a quick look to make sure there's no other case we can hit when we're missing a registry?

**Comment by bparees** [comment]
@liggitt by "missing a registry" you mean when there's no openshift registry, or do you mean when there's no From/To defined in the buildconfig?

**Comment by csrwng** [comment]
@liggitt I looked over that part of the code and at least for now can't see another place where we could run into this issue.

**Comment by liggitt** [comment]
Closing as resolved by #4505
