### ISSUE TITLE
test

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4745]
@smarterclayton fyi

**Comment by smarterclayton** [comment]
What is it email not?

On Sep 21, 2015, at 1:45 PM, OpenShift Bot <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> fyi

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4745#issuecomment-142056358>.

**Comment by smarterclayton** [comment]
Srsly you suck

On Sep 21, 2015, at 1:45 PM, OpenShift Bot <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> fyi

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4745#issuecomment-142056358>.

**Comment by smarterclayton** [comment]
@liggitt

**Comment by liggitt** [comment]
Before



On Sep 21, 2015, at 1:56 PM, Clayton Coleman <notifications@github.com>
wrote:


Inline


@liggitt <https://github.com/liggitt>


After

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4745#issuecomment-142060955>.

**Comment by smarterclayton** [comment]
On Monday, September 21, 2015, Jordan Liggitt <notifications@github.com>
wrote:

> Before
>
>
>
> On Sep 21, 2015, at 1:56 PM, Clayton Coleman <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
>
> Inline
>
>

Is the gmail client any better?

**Comment by deads2k** [comment]
> Is the gmail client any better?

That's readable.

Can you try to insert a comment


between the paragraphs

in this message?

**Comment by smarterclayton** [comment]
On Tuesday, September 22, 2015, David Eads <notifications@github.com> wrote:

> Is the gmail client any better?
>
> That's readable.
>
Yes



> Can you try to insert a comment
>
Yes

> between the paragraphs
>
No

> in this message?
>
The problem is I have to use this execrable excuse for a mail client.  I'd
rather chew nails.

**Comment by bparees** [comment]
this appears to have served it's purpose, closing.
