### ISSUE TITLE
Build Error: Could not find image: no such id:

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin#4759]
My template with multiple buildconfigs worked on a different computer also running openshift binary 1.0.6.  Now the same template is giving me the following error:

[root@mongodb openshift_1_6]# ./oc build-logs tradeservicebase-build-3 
Step 0 : FROM 172.30.227.97:5000/test/wildfly-jdk-8@sha256:5508b3ed1be2399e7623a4f362397c5b76d5a594cc3829025a33d253cc3ea768
 ---> 287b6a653101
Step 1 : USER root
F0922 18:55:46.979085       1 builder.go:54] Build error: could not find image: no such id: 4b24d9fcd6ce70770c9083efe7ccbab2fb95e2ea2142d56520df1ccd9ece6c5a
[root@mongodb openshift_1_6]# 

The image it is complaining about was successfully built and pushed to the repository as seen from its log:

dfly-jdk-8:latest image ...
I0922 18:43:38.106022       1 docker.go:118] Successfully pushed 172.30.227.97:5000/test/wildfly-jdk-8:latest

**Comment by deanpeterson** [comment]
I'm getting all kinds of these strange could not find image errors even though openshift says the image is there.  I went home and on my other computer I am able to get to the deployment phase but then I have events that show the following:

9:49:31 PM	
Pod
tradeservice-4-50ce3	
failed
Failed to create docker container with error: no such image (14 times in the last 2 minutes, 9 seconds)
9:49:31 PM	
Pod
tradeservice-4-50ce3	
pulled
Container image "172.30.90.140:5000/test/tradeservice@sha256:baaafd71a1e12ed676ce467e00bb23dce2024608f6128ef6eb9202d28d57d7ba" already present on machine


When I run the docker history command about the image I see a similar error to the one above:
docker history 172.30.90.140:5000/test/tradeservice@sha256:baaafd71a1e12ed676ce467e00bb23dce2024608f6128ef6eb9202d28d57d7ba
Error response from daemon: Error while getting parent image: could not find image: no such id: 59b8b878ca47e63e28a2b35c577ff0541e6f583036fe2c2c92ba2192ab94515a

**Comment by deanpeterson** [comment]
Am I doing something wrong in my template?  Does this somehow force Openshift to delete images before they can be used?

{
  "kind": "Template",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "trade-service",
    "creationTimestamp": null,
    "annotations": {
      "description": "no description"
    }
  },
  "objects": [
    {
      "kind": "Service",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "tradeservice",
        "creationTimestamp": null
      },
      "spec": {
        "ports": [
          {
            "name": "web",
            "protocol": "TCP",
            "port": 5432,
            "targetPort": 8080,
            "nodePort": 0
          }
        ],
        "selector": {
          "name": "tradeservice"
        },
        "portalIP": "",
        "type": "ClusterIP",
        "sessionAffinity": "None"
      },
      "status": {
        "loadBalancer": {}
      }
    },
    {
      "kind": "ImageStream",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "tradeservice",
        "creationTimestamp": null
      },
      "spec": {},
      "status": {
        "dockerImageRepository": ""
      }
    },
    {
      "kind": "ImageStream",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "tradeservicebase",
        "creationTimestamp": null
      },
      "spec": {},
      "status": {
        "dockerImageRepository": ""
      }
    },
    {
      "kind": "ImageStream",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "wildfly-jdk-8",
        "creationTimestamp": null
      },
      "spec": {
      },
      "status": {
        "dockerImageRepository": ""
      }
    },
    {
      "kind": "ImageStream",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "rhel",
        "creationTimestamp": null
      },
      "spec": {
        "dockerImageRepository": "registry.access.redhat.com/rhel"
      },
      "status": {
        "dockerImageRepository": ""
      }
    },
    {
      "kind": "BuildConfig",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "wildfly-jdk-8-build",
        "creationTimestamp": null,
        "labels": {
          "name": "wildfly-jdk-8-build"
        }
      },
      "spec": {
        "triggers": [
          {
            "type": "github",
            "github": {
              "secret": "secret101"
            }
          },
          {
            "type": "generic",
            "generic": {
              "secret": "secret101"
            }
          },
          {
            "type": "imageChange",
            "imageChange": {}
          },
          {
            "type": "ConfigChange"
          }
        ],
        "source": {
          "type": "Git",
          "git": {
            "uri": .....................blanked out
          }
        },
        "strategy": {
          "type": "Docker",
          "dockerStrategy": {
            "from": {
              "kind": "ImageStreamTag",
              "name": "rhel:latest"
            }
          }
        },
        "output": {
          "to": {
            "kind": "ImageStreamTag",
            "name": "wildfly-jdk-8:latest"
          }
        },
        "resources": {}
      },
      "status": {
        "lastVersion": 0
      }
    },
    {
      "kind": "BuildConfig",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "tradeservicebase-build",
        "creationTimestamp": null,
        "labels": {
          "name": "tradeservicebase-build"
        }
      },
      "spec": {
        "triggers": [
          {
            "type": "github",
            "github": {
              "secret": "secret101"
            }
          },
          {
            "type": "generic",
            "generic": {
              "secret": "secret101"
            }
          },
          {
            "type": "imageChange",
            "imageChange": {}
          },
          {
            "type": "ConfigChange"
          }
        ],
        "source": {
          "type": "Git",
          "git": {
            "uri": .....................blanked out
          }
        },
        "strategy": {
          "type": "Docker",
          "dockerStrategy": {
            "from": {
              "kind": "ImageStreamTag",
              "name": "wildfly-jdk-8:latest"
            }
          }
        },
        "output": {
          "to": {
            "kind": "ImageStreamTag",
            "name": "tradeservicebase:latest"
          }
        },
        "resources": {}
      },
      "status": {
        "lastVersion": 0
      }
    },
    {
      "kind": "BuildConfig",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "tradeservice-build",
        "creationTimestamp": null,
        "labels": {
          "name": "tradeservice-build"
        }
      },
      "spec": {
        "triggers": [
          {
            "type": "github",
            "github": {
              "secret": "secret101"
            }
          },
          {
            "type": "generic",
            "generic": {
              "secret": "secret101"
            }
          },
          {
            "type": "imageChange",
            "imageChange": {}
          },
          {
            "type": "ConfigChange"
          }
        ],
        "source": {
          "type": "Git",
          "git": {
            "uri": .....................blanked out
          }
        },
        "strategy": {
          "type": "Docker",
          "dockerStrategy": {
            "from": {
              "kind": "ImageStreamTag",
              "name": "tradeservicebase:latest"
            }
          }
        },
        "output": {
          "to": {
            "kind": "ImageStreamTag",
            "name": "tradeservice:latest"
          }
        },
        "resources": {}
      },
      "status": {
        "lastVersion": 0
      }
    },
    {
      "kind": "DeploymentConfig",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "tradeservice",
        "creationTimestamp": null
      },
      "spec": {
        "strategy": {
          "type": "Rolling",
          "rollingParams": {
            "updatePeriodSeconds": 1,
            "intervalSeconds": 1,
            "timeoutSeconds": 120
          },
          "resources": {}
        },
        "triggers": [
          {
            "type": "ImageChange",
            "imageChangeParams": {
              "automatic": true,
              "containerNames": [
                "wildfly-tradeservice"
              ],
              "from": {
                "kind": "ImageStreamTag",
                "name": "tradeservice:latest"
              },
              "lastTriggeredImage": ""
            }
          },
          {
            "type": "ConfigChange"
          }
        ],
        "replicas": 2,
        "selector": {
          "name": "tradeservice"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "tradeservice"
            }
          },
          "spec": {
            "containers": [
              {
                "name": "wildfly-tradeservice",
                "image": "tradeservice",
                "ports": [
                  {
                    "containerPort": 8080,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent",
                "capabilities": {},
                "securityContext": {
                  "capabilities": {},
                  "privileged": false
                }
              }
            ],
            "restartPolicy": "Always",
            "dnsPolicy": "ClusterFirst",
            "serviceAccount": ""
          }
        }
      },
      "status": {}
    }
  ],
  "parameters": [
  ],
  "labels": {
    "template": "trade-service-template"
  }
}

**Comment by deanpeterson** [comment]
I am still completely stuck on this issue.

**Comment by deanpeterson** [comment]
I deleted my project and started from scratch to see if me deleting buildconfigs and deploymentconfigs was the problem.  I am still getting this error:

Pull complete
Already exists
Digest: sha256:a143facad3b327c3e9bda5436bc8f34c9de599a96a2eb03ecf2d3e9797b009b0
Status: Downloaded newer image for 172.30.227.97:5000/test/tradeservicebase@sha256:a143facad3b327c3e9bda5436bc8f34c9de599a96a2eb03ecf2d3e9797b009b0
 ---> f113e2f3d948
Step 1 : USER root
F0923 17:07:26.541455       1 builder.go:54] Build error: could not find image: no such id: 77f9e9e28e31f7f4297231ba4883eae061573fad1f51a66ec9aa74982f197b4b

**Comment by deanpeterson** [comment]
docker inspect 172.30.227.97:5000/test/tradeservicebase@sha256:a143facad3b327c3e9bda5436bc8f34c9de599a96a2eb03ecf2d3e9797b009b0
[
{
    "Id": "f113e2f3d94897ad0017bf20926f3b202a559b78ce92da6eae70473542625159",
    "Parent": "683fd1160ba898ab53d64840e341a6aa7c23a02924483edb24444a5e7f430e07",
    "Comment": "",
    "Created": "2015-09-23T17:05:35.923448658Z",
    "Container": "ab1c7f00984fc6b775ba7e350f6b7e66df4754d8f2190e76c4cf5d4d692c7c49",
    "ContainerConfig": {
        "Hostname": "ca42e21568df",
        "Domainname": "",
        "User": "root",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "8080/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "container=docker",
            "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin",
            "WILDFLY_VERSION=8.2.0.Final",
            "HOME=/opt/jboss",
            "JBOSS_HOME=/opt/jboss/wildfly",
            "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk",
            "OPENSHIFT_BUILD_NAME=tradeservicebase-build-1",
            "OPENSHIFT_BUILD_NAMESPACE=test",
            "OPENSHIFT_BUILD_SOURCE=https://peterson.dean%40gmail.com:heman%40eternia18%40@enterprisewebservice.kilnhg.com/Code/EnterpriseWebService/Openshift-Docker-Builds/tradeservicebase.git"
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "#(nop) LABEL io.openshift.build.commit.author=root \u003croot@23-25-149-225-static.hfc.comcastbusiness.net\u003e io.openshift.build.commit.date=Mon Sep 21 23:16:08 2015 -0400 io.openshift.build.commit.id=4eedc24 io.openshift.build.commit.ref=master io.openshift.build.commit.message=changed filename io.openshift.build.source-location=https://peterson.dean%40gmail.com:heman%40eternia18%40@enterprisewebservice.kilnhg.com/Code/EnterpriseWebService/Openshift-Docker-Builds/tradeservicebase.git"
        ],
        "Image": "683fd1160ba898ab53d64840e341a6aa7c23a02924483edb24444a5e7f430e07",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "/opt/jboss",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": [],
        "Labels": {
            "Architecture": "x86_64",
            "Authoritative_Registry": "registry.access.redhat.com",
            "BZComponent": "rhel-server-docker",
            "Build_Host": "rcm-img02.build.eng.bos.redhat.com",
            "Name": "redhat/rhel7",
            "Release": "16",
            "Vendor": "Red Hat, Inc.",
            "Version": "7.1",
            "io.openshift.build.commit.author": "root \u003croot@23-25-149-225-static.hfc.comcastbusiness.net\u003e",
            "io.openshift.build.commit.date": "Mon Sep 21 23:16:08 2015 -0400",
            "io.openshift.build.commit.id": "4eedc24",
            "io.openshift.build.commit.message": "changed filename",
            "io.openshift.build.commit.ref": "master",
            "io.openshift.build.source-location": "https://peterson.dean%40gmail.com:heman%40eternia18%40@enterprisewebservice.kilnhg.com/Code/EnterpriseWebService/Openshift-Docker-Builds/tradeservicebase.git"
        }
    },
    "DockerVersion": "1.7.1",
    "Author": "",
    "Config": {
        "Hostname": "ca42e21568df",
        "Domainname": "",
        "User": "root",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "8080/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "container=docker",
            "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin",
            "WILDFLY_VERSION=8.2.0.Final",
            "HOME=/opt/jboss",
            "JBOSS_HOME=/opt/jboss/wildfly",
            "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk",
            "OPENSHIFT_BUILD_NAME=tradeservicebase-build-1",
            "OPENSHIFT_BUILD_NAMESPACE=test",
            "OPENSHIFT_BUILD_SOURCE=https://peterson.dean%40gmail.com:heman%40eternia18%40@enterprisewebservice.kilnhg.com/Code/EnterpriseWebService/Openshift-Docker-Builds/tradeservicebase.git"
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "echo"
        ],
        "Image": "683fd1160ba898ab53d64840e341a6aa7c23a02924483edb24444a5e7f430e07",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "/opt/jboss",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": [],
        "Labels": {
            "Architecture": "x86_64",
            "Authoritative_Registry": "registry.access.redhat.com",
            "BZComponent": "rhel-server-docker",
            "Build_Host": "rcm-img02.build.eng.bos.redhat.com",
            "Name": "redhat/rhel7",
            "Release": "16",
            "Vendor": "Red Hat, Inc.",
            "Version": "7.1",
            "io.openshift.build.commit.author": "root \u003croot@23-25-149-225-static.hfc.comcastbusiness.net\u003e",
            "io.openshift.build.commit.date": "Mon Sep 21 23:16:08 2015 -0400",
            "io.openshift.build.commit.id": "4eedc24",
            "io.openshift.build.commit.message": "changed filename",
            "io.openshift.build.commit.ref": "master",
            "io.openshift.build.source-location": "https://peterson.dean%40gmail.com:heman%40eternia18%40@enterprisewebservice.kilnhg.com/Code/EnterpriseWebService/Openshift-Docker-Builds/tradeservicebase.git"
        }
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Size": 0,
    "VirtualSize": 74354253
}
]

**Comment by deanpeterson** [comment]
docker inspect 172.30.227.97:5000/test/tradeservicebase@sha256:a143facad3b327c3e9bda5436bc8f34c9de599a96a2eb03ecf2d3e9797b009b0
[
{
    "Id": "f113e2f3d94897ad0017bf20926f3b202a559b78ce92da6eae70473542625159",
    "Parent": "683fd1160ba898ab53d64840e341a6aa7c23a02924483edb24444a5e7f430e07",
    "Comment": "",
    "Created": "2015-09-23T17:05:35.923448658Z",
    "Container": "ab1c7f00984fc6b775ba7e350f6b7e66df4754d8f2190e76c4cf5d4d692c7c49",
    "ContainerConfig": {
        "Hostname": "ca42e21568df",
        "Domainname": "",
        "User": "root",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "8080/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "container=docker",
            "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin",
            "WILDFLY_VERSION=8.2.0.Final",
            "HOME=/opt/jboss",
            "JBOSS_HOME=/opt/jboss/wildfly",
            "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk",
            "OPENSHIFT_BUILD_NAME=tradeservicebase-build-1",
            "OPENSHIFT_BUILD_NAMESPACE=test",
            "OPENSHIFT_BUILD_SOURCE=............blanked out
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "#(nop) LABEL io.openshift.build.commit.author=root \u003croot@23-25-149-225-static.hfc.comcastbusiness.net\u003e io.openshift.build.commit.date=Mon Sep 21 23:16:08 2015 -0400 io.openshift.build.commit.id=4eedc24 io.openshift.build.commit.ref=master io.openshift.build.commit.message=changed filename io.openshift.build.source-location=............blanked out
        ],
        "Image": "683fd1160ba898ab53d64840e341a6aa7c23a02924483edb24444a5e7f430e07",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "/opt/jboss",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": [],
        "Labels": {
            "Architecture": "x86_64",
            "Authoritative_Registry": "registry.access.redhat.com",
            "BZComponent": "rhel-server-docker",
            "Build_Host": "rcm-img02.build.eng.bos.redhat.com",
            "Name": "redhat/rhel7",
            "Release": "16",
            "Vendor": "Red Hat, Inc.",
            "Version": "7.1",
            "io.openshift.build.commit.author": "root \u003croot@23-25-149-225-static.hfc.comcastbusiness.net\u003e",
            "io.openshift.build.commit.date": "Mon Sep 21 23:16:08 2015 -0400",
            "io.openshift.build.commit.id": "4eedc24",
            "io.openshift.build.commit.message": "changed filename",
            "io.openshift.build.commit.ref": "master",
            "io.openshift.build.source-location": "https://peterson.dean%40gmail.com:heman%40eternia18%40@enterprisewebservice.kilnhg.com/Code/EnterpriseWebService/Openshift-Docker-Builds/tradeservicebase.git"
        }
    },
    "DockerVersion": "1.7.1",
    "Author": "",
    "Config": {
        "Hostname": "ca42e21568df",
        "Domainname": "",
        "User": "root",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "8080/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "container=docker",
            "PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin",
            "WILDFLY_VERSION=8.2.0.Final",
            "HOME=/opt/jboss",
            "JBOSS_HOME=/opt/jboss/wildfly",
            "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk",
            "OPENSHIFT_BUILD_NAME=tradeservicebase-build-1",
            "OPENSHIFT_BUILD_NAMESPACE=test",
            "OPENSHIFT_BUILD_SOURCE=............blanked out
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "echo"
        ],
        "Image": "683fd1160ba898ab53d64840e341a6aa7c23a02924483edb24444a5e7f430e07",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "/opt/jboss",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": [],
        "Labels": {
            "Architecture": "x86_64",
            "Authoritative_Registry": "registry.access.redhat.com",
            "BZComponent": "rhel-server-docker",
            "Build_Host": "rcm-img02.build.eng.bos.redhat.com",
            "Name": "redhat/rhel7",
            "Release": "16",
            "Vendor": "Red Hat, Inc.",
            "Version": "7.1",
            "io.openshift.build.commit.author": "root \u003croot@23-25-149-225-static.hfc.comcastbusiness.net\u003e",
            "io.openshift.build.commit.date": "Mon Sep 21 23:16:08 2015 -0400",
            "io.openshift.build.commit.id": "4eedc24",
            "io.openshift.build.commit.message": "changed filename",
            "io.openshift.build.commit.ref": "master",
            "io.openshift.build.source-location": .............blanked out
        }
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Size": 0,
    "VirtualSize": 74354253
}
]

**Comment by deanpeterson** [comment]
I am able to get around the no such id: errors by manually pulling images from the registry but I don't know why that fixes things.  My reward for getting to a point where it looks like pods are going to start is the event error:
failed
Failed to start with docker id 955be00289fe with error: API error (500): Cannot start container 955be00289feffc13c5c8f65c37339ca274de33db51891d7d9e192bc1f70d9e3: cannot join network of a non running container: 417b8c790d047ebeb11bcb83342eb774bdbd9fb1288d9b88d45a2a6806211754

*frustrated*

**Comment by csrwng** [comment]
@deanpeterson what's your storage back-end for docker? Are you running the all-in-one or a separate master/nodes environment?

**Comment by deanpeterson** [comment]
I use the all in one binary v1.0.6.  I am able to work around the no such id issues but it is annoying.  I have multiple layers buildconfigs to build up an image.  Each layer depends on the previous buildconfig.  After every buildconfig completes, I get a no such image/I'd error.  I have to log in to the Docker registry and manually pull the image that was just pushed successfully to the registry.  After that, when I rerun the build that just failed due to a no such id error, it finishes successfully.  I have to do that for every layer.

**Comment by csrwng** [comment]
@deanpeterson sounds like you need to update your builder images. In openshift 1.0.6 we fixed a bug that was causing the 'no such image' error because authentication was failing (docker changed the format of the build request authentication header after v1.6.2). It sounds like you got the right version to fix it though but your builder image (openshift/origin-docker-builder) may be old. Try pulling the latest version or building it locally with hack/build-images.sh, and to really make sure you are using the latest, start openshift with the --latest-images flag.

**Comment by deanpeterson** [comment]
Thanks, I will try that!  I am using the Docker strategy rather than STI.  Does the same advice still apply?

**Comment by csrwng** [comment]
Yes

**Comment by deanpeterson** [comment]
Unfortunately that does not seem to help.  Everything works fine until the third layer build.  Everything after that still requires me to manually pull the image from the previous layer, then re-run the build.

**Comment by csrwng** [comment]
Hmm, something else must be going on... just to double check though, what is the output of 
```
docker run openshift/origin-docker-builder:latest version
```

**Comment by deanpeterson** [comment]
docker run openshift/origin-docker-builder:latest version
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
openshift-docker-build v1.0.6-310-gf95a0d5
kubernetes v1.1.0-alpha.1-653-g86b4e77

**Comment by csrwng** [comment]
And what version of docker do you have?

**Comment by deanpeterson** [comment]
docker --version
Docker version 1.7.1, build 446ad9b/1.7.1

**Comment by csrwng** [comment]
It probably won't make much of a difference, but can you try updating your docker to the latest version available? (with yum/dnf update)

**Comment by csrwng** [comment]
@deanpeterson if possible, can you try using a builder image that outputs additional debug information when running the docker build? (cewong/origin-docker-builder:debug)

**Comment by csrwng** [comment]
@deanpeterson if you are still seeing this issue I would suggest an interactive debugging session. You can find me at #openshift-dev as cewong

**Comment by deanpeterson** [comment]
I have been away from Openshift for a while.  I have been waiting on v1.0.7 to be released hoping that might clear up some of my issues.  Any idea when that will be made available?

**Comment by csrwng** [comment]
@deanpeterson I don't know that there is a date for it. @smarterclayton ?

**Comment by smarterclayton** [comment]
We're waiting for #4992

**Comment by bparees** [comment]
1.0.7 is available now.  https://github.com/openshift/origin/releases/tag/untagged-36bb0928e24108ddbc92

**Comment by smarterclayton** [comment]
It is not - that's not published yet :)

**Comment by bparees** [comment]
oops, i should have paid more attention to that big red "DRAFT" label. my bad.

**Comment by bparees** [comment]
*now* it's available: https://github.com/openshift/origin/releases/tag/v1.1

**Comment by bparees** [comment]
closing based on age, please reopen if you are still having this issue with a current release.
