### ISSUE TITLE
Allow secrets to be injected into an s2i builder so application source code can use them

### ISSUE THREAD

**Issue by pat2man** [openshift/origin#4761]
Based on the conversation here: https://github.com/openshift/origin/pull/4146 it was decided that source builds will not be able to mount secrets. This makes it impossible to build applications that require private dependencies and have their authentication stored in a file.

For example, deploying apps using node.js with a private npm repository often involves editing an npmrc file. Example: https://www.jfrog.com/confluence/display/RTF/Npm+Repositories

Supporting the mounting of a $HOME/.npmrc as a secret would allow this style of private repository access. It should only be required during the build phase.

**Comment by bparees** [comment]
we are carrying this enhancement request on our trello backlog, closing this issue in deference to that: https://trello.com/c/m5bPxwh4/643-allow-to-consume-secrets-in-builds
