### ISSUE TITLE
Error pushing image to repository after successful build

### ISSUE THREAD

**Issue by fkirill** [openshift/origin#4763]
I set up local Vagrant env. Unfortunately, I cannot push image to the local integrated repository.

Here is the build config I use:

<pre><code>
.....
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: test3
    name: test3
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: test3:latest
    source:
      type: Git
      git:
        uri: http://192.168.1.254:3000/gogsadmin/test3.git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: java-maven-builder:latest
    triggers:
    - github:
        secret: x47Cn_v-jGF65Zp20wHU
      type: GitHub
    - generic:
        secret: MNRJYV6XYLC4C4CHwnZ_
      type: Generic
    - type: ConfigChange
    - type: ImageChange
.....
</code></pre>

Here is the build output
<pre><code>
[vagrant@openshiftdev ~]$ oc start-build test3 --follow=true --loglevel=5
test3-8
I0923 04:42:54.360157       1 sti.go:407] ---> Installing application source
I0923 04:42:54.369417       1 sti.go:407] ---> Building application from source
I0923 04:42:56.795482       1 sti.go:407] [INFO] Scanning for projects...
I0923 04:42:56.925352       1 sti.go:407] [INFO]                                                                         
I0923 04:42:56.952228       1 sti.go:407] [INFO] ------------------------------------------------------------------------
I0923 04:42:56.952426       1 sti.go:407] [INFO] Building test3 1.0.0-SNAPSHOT
I0923 04:42:56.952603       1 sti.go:407] [INFO] ------------------------------------------------------------------------
I0923 04:42:57.427607       1 sti.go:407] Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-maven-plugin/1.2.6.RELEASE/spring-boot-maven-plugin-1.2.6.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-maven-plugin/1.2.6.RELEASE/spring-boot-maven-plugin-1.2.6.RELEASE.pom (6 KB at 0.9 KB/sec)
I0923 04:43:03.305486       1 sti.go:407] Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-tools/1.2.6.RELEASE/spring-boot-tools-1.2.6.RELEASE.pom
.....
Downloaded: https://repo.maven.apache.org/maven2/com/google/guava/guava/11.0.2/guava-11.0.2.jar (1610 KB at 27.1 KB/sec)
I0923 04:50:37.179558       1 sti.go:407] [INFO] ------------------------------------------------------------------------
I0923 04:50:37.179643       1 sti.go:407] [INFO] BUILD SUCCESS
I0923 04:50:37.179760       1 sti.go:407] [INFO] ------------------------------------------------------------------------
I0923 04:50:37.179931       1 sti.go:407] [INFO] Total time: 07:40 min
I0923 04:50:37.180076       1 sti.go:407] [INFO] Finished at: 2015-09-23T04:50:37+00:00
I0923 04:50:37.276015       1 sti.go:407] [INFO] Final Memory: 22M/81M
I0923 04:50:37.276076       1 sti.go:407] [INFO] ------------------------------------------------------------------------
I0923 04:50:42.071600       1 sti.go:151] Pushing test/test3:latest image ...
F0923 04:50:51.348705       1 builder.go:54] Build error: Failed to push image: unauthorized: access to the requested resource is not authorized

</code></pre>

The user that started the build is 'test-admin' (NOT admin).
What's the right way to grant access to integrated repository from the build process?

Thank you

**Comment by soltysh** [comment]
Can you provide information about how did you setup your environment. OpenShift by default creates a handful of service accounts and roles for building and deploying (see [docs](https://docs.openshift.org/latest/dev_guide/service_accounts.html#default-service-accounts-and-roles)). It looks like your builder is missing the automatically generated token for accessing internal registry, or maybe you're using other docker registry?

**Comment by fkirill** [comment]
Well, I already teared down the environment, sorry for that. Anyway, it was integrated registry, according to official documentation (admin/deploying a registry).
I guess maybe I would figure it out, but the error message is... not informative. What I'm really missing is what is exactly the account name and what is exactly the resource that this account doesn't have access to.
In the current form it's almost impossible to reason about what's happening and what is really the problem. Is is the Pod? Or a Service? Or a replication controller? Or Image Stream? Is it my current account (output of oc whoami)? Or some other technical account? Or what?
What I would want to be output: 1) Was registry resolved based on search? 2) Where's the registry details (namespace/Pod or address/port)? 3) What's the authentication mechanism used? 4) Is authentication information present (y or n) 5) If account of a publisher is known, what is that account name (service:builder or something else) 6) what is being pushed (image name:label).
And probably a few words what could be a solution for this problem (like adding user to a builder group and ensuring this group is granted access to this registry object)

**Comment by soltysh** [comment]
I'll try to address your questions, so here it goes. The integrated registry's IP address is kept at a service (docker-registry) level, so far it's numerical, that's why you need to restart master if you recreate internal registry (see #1723). That IP address is used by the ImageStream controller responsible for managing all ImageStreams, including ImageStreamTags, ImageStreamImages, etc. Now we're coming to builds, as mentioned before, they are assigned `system:image-builder` role, which allows pushing images to any image stream in the project using the internal docker registry. Since all the builds are running with this role, you don't have to worry about your user role, as long as your user has access to IS you're pushing your build result to. The easiest you can do to verify if aforementioned builder role has appropriate privileges is to check its contents:
```
[vagrant@openshiftdev ~]$ oc describe serviceaccount builder
Name:		builder
Namespace:	test
Labels:		<none>

Image pull secrets:	builder-dockercfg-1v7oo

Mountable secrets: 	builder-token-cqbka
                   	builder-dockercfg-1v7oo

Tokens:            	builder-token-cqbka
                   	builder-token-hkhfo
```
The last two tokens are there by default (see [here](https://docs.openshift.org/latest/dev_guide/service_accounts.html#managing-service-account-credentials)) so you don't have to worry about accessing master API and internal registry from the builder. 

I hope that helped you understand at least some parts, if you have further questions, please let me know, I'll try to address them, if not and if you don't mind please close this issue, because I doesn't look like it's OpenShift error, but rather some configuration issue. If you hit the issue again you can always reopen it and provide more details that will help us identify the problem.

**Comment by fkirill** [comment]
Hey @soltysh, thank you very much for your sizeable response!!! While this is important to understand, my point was that it is impossible to troubleshoot the problem when it occurs without significantly more information in the log.
Let's see if I have time on a weekend, I'll probably prepare a push request to add all of this to logging. Maybe, as a result, people will have less questions in the future. I found the place in the source where it happens, so it shouldn't be a rocket science.

Thank you!

**Comment by soltysh** [comment]
Cool! Lemme know if you need help with it and don't forget to tag me in your PR.

**Comment by moink635** [comment]
Hi, i'm also facing same issue please let me know what is the best possible result for the issue to resolved ? this url consist of http://ur1.ca/nv65f

**Comment by fkirill** [comment]
Created pull request #4901

**Comment by bparees** [comment]
PR has been merged, thanks @fkirill !

**Comment by fkirill** [comment]
No worries!
