### ISSUE TITLE
OriginNamespaceLifecycle leaks available namespace name information

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4769]
I'm allowed to create a self localSAR against any given namespace, because I could gain the same information (authorized or unauthorized) by simply making the request.  When I make a self localSAR against a namespace that doesn't exist, I'm informed that the namespace doesn't exist instead of getting an authorized/unauthorized response.  This lets me hunt for namespace names that exist even if I'm not authorized to know this, since I get a valid SAR response for namespaces that I'm not allowed to see.

@derekwaynecarr

**Comment by derekwaynecarr** [comment]
Can you update with your latest findings?

**Comment by deads2k** [comment]
> Can you update with your latest findings?

This is the latest.  The correct admission chain is being used, but the implementation for `OriginNamespaceLifecycle` leaks information here: https://github.com/openshift/origin/blob/master/pkg/project/admission/lifecycle/admission.go#L94 when the SAR is allowed but the namespace is missing.
