### ISSUE TITLE
Extended tests can't resolve DNS names

### ISSUE THREAD

**Issue by mnagy** [openshift/origin#4770]
If I want to e.g. make an http request to a service from my extended test, I won't be able to reach it, because the host the tests are running on does not have its `/etc/resolv.conf` pointed to the SkyDNS that OpenShift is running. This can be quite frustrating and requires a workaround.

It would be nice to solve this somehow by pointing to the DNS server, or at least provide a helper utility function.

**Comment by mfojtik** [comment]
@mnagy what prevents you to point your host /etc/resolv.conf to itself (skydns) ?

**Comment by mnagy** [comment]
@mfojtik nothing, but AFAIK we do not do that in our vagrant environment, which means that such tests will only work on my machine, but will be broken when Jenkins is testing them.

**Comment by mfojtik** [comment]
@mnagy why you need to access the internal DNS from the host in extended test? Can't you just run it in Pod or container?

**Comment by mnagy** [comment]
@mfojtik technically you can, but it's hacky and you need to use `curl` and parse the output instead of simply using go's `net/http` library. I'm currently using that, and just get the endpoint IP address. Which is unnecessarily cumbersome as well.
