### ISSUE TITLE
kill_all_processes doesn't work on Mac

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4775]
Which means hack/test-cmd.sh doesn't work, which makes Clayton upset.

**Comment by mfojtik** [comment]
@smarterclayton @jhadvig is a poor guy without Mac. They are expensive in EU ;-)

**Comment by deads2k** [comment]
> They are expensive in EU

People who can afford macs are probably people who can afford to hire help to clean up their processes.  :)

@smarterclayton Which part of it is breaking?  I thought he added a check for sudoer rights.

**Comment by jhadvig** [comment]
@deads2k its there https://github.com/openshift/origin/blob/master/hack/util.sh#L390-L404

we should have iOS9 image for vagrant i guess :P

**Comment by jhadvig** [comment]
@smarterclayton do you get any kind of error ?

**Comment by smarterclayton** [comment]
ps `--ppid` doesn't exist on macs

**Comment by smarterclayton** [comment]
Also, yo should be able to run hack/test-cmd without root, which is what
the case is, so all the sudo gyrations aren't necessary.

**Comment by jhadvig** [comment]
@smarterclayton the hack/test-cmd.sh runs without root, which we do. The sudo is there mainly to start the OS server.

**Comment by smarterclayton** [comment]
kill_all_processes assumes you need to do the --ppid thing, which was only
because of root.

**Comment by bparees** [comment]
assigning to cesar because he's actually got a mac to test this with.

**Comment by mfojtik** [comment]
`ENEEDMAC`

**Comment by kargakis** [comment]
https://www.indiegogo.com/simple_campaigns/let-s-buy-a-mac-for-jakub/share#/
