### ISSUE TITLE
Error starting openshift on NFS mounted volume - etcdserver: open wal error: bad file descriptor

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#4778]
I'm starting OpenShift from current [master](https://github.com/openshift/origin/commit/7830fb9aa4f40c1d158540cb6143402c62a02800) and I'm getting this:

```
I0924 09:12:13.746756   14450 plugins.go:70] No cloud provider specified.
I0924 09:12:13.747008   14450 start_master.go:385] Starting master on 0.0.0.0:8443 (v1.0.6-141-g7830fb9)
I0924 09:12:13.747021   14450 start_master.go:386] Public master address is https://192.168.121.118:8443
I0924 09:12:13.747031   14450 start_master.go:390] Using images from "openshift/origin-<component>:v1.0.6"
E0924 09:12:13.747234   14450 reflector.go:180] pkg/admission/namespace/exists/admission.go:101: Failed to list *api.Namespace: Get https://192.168.121.118:8443/api/v1/namespaces: dial tcp 192.168.121.118:8443: connection refused
E0924 09:12:13.747600   14450 reflector.go:180] pkg/admission/serviceaccount/admission.go:101: Failed to list *api.ServiceAccount: Get https://192.168.121.118:8443/api/v1/serviceaccounts: dial tcp 192.168.121.118:8443: connection refused
E0924 09:12:13.747650   14450 reflector.go:180] pkg/admission/limitranger/admission.go:102: Failed to list *api.LimitRange: Get https://192.168.121.118:8443/api/v1/limitranges: dial tcp 192.168.121.118:8443: connection refused
E0924 09:12:13.747690   14450 reflector.go:180] pkg/admission/namespace/lifecycle/admission.go:107: Failed to list *api.Namespace: Get https://192.168.121.118:8443/api/v1/namespaces: dial tcp 192.168.121.118:8443: connection refused
E0924 09:12:13.747931   14450 reflector.go:180] pkg/security/admission/admission.go:59: Failed to list *api.SecurityContextConstraints: Get https://192.168.121.118:8443/api/v1/securitycontextconstraints: dial tcp 192.168.121.118:8443: connection refused
E0924 09:12:13.747995   14450 reflector.go:180] pkg/admission/resourcequota/admission.go:59: Failed to list *api.ResourceQuota: Get https://192.168.121.118:8443/api/v1/resourcequotas: dial tcp 192.168.121.118:8443: connection refused
E0924 09:12:13.750144   14450 reflector.go:180] pkg/admission/serviceaccount/admission.go:115: Failed to list *api.Secret: Get https://192.168.121.118:8443/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 192.168.121.118:8443: connection refused
2015-09-24 09:12:14.050795 I | etcdserver: name = openshift.local
2015-09-24 09:12:14.050830 I | etcdserver: data dir = openshift.local.etcd
2015-09-24 09:12:14.050839 I | etcdserver: member dir = openshift.local.etcd/member
2015-09-24 09:12:14.050844 I | etcdserver: heartbeat = 100ms
2015-09-24 09:12:14.050849 I | etcdserver: election = 1000ms
2015-09-24 09:12:14.050854 I | etcdserver: snapshot count = 0
2015-09-24 09:12:14.050864 I | etcdserver: advertise client URLs = https://192.168.121.118:4001
2015-09-24 09:12:14.051123 C | etcdserver: open wal error: bad file descriptor
```
Any ideas what might be wrong? It looks like I have some k8s leftovers, but I have no idea where, at least as of yet.

**Comment by soltysh** [comment]
I must add I'm running openshift using following [script](https://github.com/soltysh/origin-scripts/blob/master/os-init.sh) when I run OpenShift directly without redirecting logs to the file it suddenly worked, what's different is this line that is missing in previous execution:
```
Generated new key pair as openshift.local.config/master/serviceaccounts.public.key and openshift.local.config/master/serviceaccounts.private.key
```
Yet again, why? @liggitt any ideas, since this involves generating the initial keys. 
The worst thing now is that it works now every time without problems. I'll take a closer look into this.

**Comment by mfojtik** [comment]
@soltysh I saw this when etcd was writing files into NFS volume (or mounted directory).

**Comment by soltysh** [comment]
Maybe I need to rewrite my script to specify exact volume/config/etcd dirs, since I think having them unspecified might cause above errors, iow. it sometimes chooses directory that are mounted through NFS volume (here the origin dir into virt machine).

**Comment by mfojtik** [comment]
@soltysh @smarterclayton I think this is a etcd bug (and I reported it somewhere already)... but honestly, I don't think that somebody will use NFS volume as etcd storage for openshift ;-)

**Comment by soltysh** [comment]
I'm not saying someone will, and I'm definitely not planning to, just figured out that it's worth pointing, if somebody else will fall into this problem :wink: As I said, I need to be more explicit in how I start my OpenShift :smile:

**Comment by soltysh** [comment]
Yup, I think I've confirmed it's NFS issue, if you see following error you'll getting your etcd files to be placed inside NFS, which currently fails. I'm closing this issue for now. Hopefully this will help somebody else.

**Comment by smarterclayton** [comment]
Why wouldn't they support it?  NFS as a target for etcd is pretty valuable in some cases.

**Comment by soltysh** [comment]
I can't find the issue @mfojtik mentioned, either it's fixed in newer versions, or else. I'll give it a 2nd try and report to etcd if I'll be able to reproduce with latest master, or I'll search better for that issue.
