### ISSUE TITLE
Cannot watch on non-namespaced resources (project, node, namespace, etc) 

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#4779]
Ref: https://github.com/kubernetes/kubernetes/issues/14289

**Comment by jimmidyson** [comment]
e.g.

```
wscat -n -c "wss://localhost:8443/oapi/v1/projects?resourceVersion=0&watch=true&access_token=$(oc whoami --token)"

error: Error: unexpected server response (200)
```

Doesn't seem to want to do websocket upgrade.

**Comment by deads2k** [comment]
In addition to any kube problems with watching cluster scoped resources, `projects` doesn't support watch.  Casting through `watch.Interface` is pretty hard.  In addition, the permissions associated with listing projects are more complicated.  It would be difficult, but not impossible, to proxy the watch events and pass them through a filter.

@smarterclayton Care to prioritize?

**Comment by smarterclayton** [comment]
Uh... this is what watch.Filter is for?

**Comment by deads2k** [comment]
> Uh... this is what watch.Filter is for?

Be fair.  Didn't exist until a month ago.

**Comment by deads2k** [comment]
> Be fair. Didn't exist until a month ago.

Oh.. a year and a month.  oops...

**Comment by smarterclayton** [comment]
:)

**Comment by jwforres** [comment]
If you guys add watch on projects PLEASE tell me :+1:

**Comment by kargakis** [comment]
We support watching projects now (https://github.com/openshift/origin/pull/6828) and it seems that for the rest of the non-namespaced resources you need to use field selectors or a resourceVersion
