### ISSUE TITLE
[post-rebase] update swagger enough for --validate to work well

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#4785]
After the rebase we are going to carry a patch that disables --validate because of https://github.com/kubernetes/kubernetes/issues/13806. We need to make cli validation play well.

**Comment by kargakis** [comment]
@deads2k fyi

**Comment by liggitt** [comment]
not just because of the size, because it doesn't work well with List, etc

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/14726 is in progress.

**Comment by kargakis** [comment]
> kubernetes/kubernetes#14726 is in progress.

Merged.

**Comment by deads2k** [comment]
Things will improve once you have separate API groups for the resources.

**Comment by smarterclayton** [comment]
This should be fixable now.  With #10983 we are at parity with Kube, and caching should be there.  We should turn this into "turn validate on by default".

**Comment by liggitt** [comment]
Still have issues with raw JSON fields
