### ISSUE TITLE
web console should allow whitespace as a required parameter value

### ISSUE THREAD

**Issue by bparees** [openshift/origin#4788]
currently the cli allows you to provide "   " as a value for a required template parameter.

the web console does not.

the web console should pop up a warning and then allow the value.

@jwforres

**Comment by spadgett** [comment]
Should just need to set ng-trim to false on these fields.

**Comment by jwforres** [comment]
We also want to show a warning though if they do input whitespace

**Comment by spadgett** [comment]
@jwforres I can look at this when my create changes merge.
