### ISSUE TITLE
Web Console Doesn't Show Build Source Repo Dir, Branch

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4795]
When viewing a build from the web console, the URL given for the source repo doesn't get modulated with branch and/or subdirectory and is therefore less useful than expected. 
cc: @spadgett @jwforres

**Comment by jwforres** [comment]
Already fixed in https://github.com/openshift/origin/pull/4726

**Comment by jwforres** [comment]
![20150925_092129_](https://cloud.githubusercontent.com/assets/1467629/10101459/d8d960be-6366-11e5-8308-8f01a3363d7a.png)

**Comment by liggitt** [comment]
Should probably make the link take you to that branch/dir for github

On Fri, Sep 25, 2015 at 9:21 AM, Jessica Forrester <notifications@github.com

**Comment by jwforres** [comment]
I don't like things that look like URLs and then take me to a different path than what they are showing, and I want the values on this page to match what they are actually set to (sourceRepo just shows sourceRepo).   We could turn the v1.0.1 in to a link to the branch, and the context dir into a link to the branch+context dir ?

**Comment by liggitt** [comment]
Seems silly to have three links, two of which don't have much connection to
the actual source that is being used

On Fri, Sep 25, 2015 at 9:27 AM, Jessica Forrester <notifications@github.com

**Comment by stevekuznetsov** [comment]
@jwforres I would expect `<repo>/blob/<branch>/<path>` for the link, no?

**Comment by jwforres** [comment]
I didn't realize we are already converting ssh github urls to the web
version, so whatever.  I'm working on it now.
