### ISSUE TITLE
[post-rebase] Make more robust the way the Namespace controller gets experimental

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#4799]
Right now the namespace controller starts in experimental mode based on if the horizontal pod autoscaler is enabled (or the upstream deployments which we still dont have), something that is really weird. 

@deads2k @derekwaynecarr

**Comment by deads2k** [comment]
I think the `experimentalMode` should be removed and the controller should discover whether the experimental groups are available.  If they are, it should clean up those resources.

**Comment by derekwaynecarr** [comment]
@deads2k - I agree.

https://github.com/kubernetes/kubernetes/issues/14562

**Comment by deads2k** [comment]
This ended up fixed, correct?

**Comment by liggitt** [comment]
yes
