### ISSUE TITLE
Using origin container can't reach github.com

### ISSUE THREAD

**Issue by arilivigni** [openshift/origin#4800]
@mrunalp

When I try and run a build for a Jenkins Master or Slave template I get the following:

ruby-20-centos7-slave-3
E0925 14:11:54.998632       1 git.go:102] Clone failed: fatal: Unable to look up github.com (port 9418) (Name or service not known)
F0925 14:11:54.999117       1 builder.go:54] Build error: exit status 128

oc build-logs jenkins-master-1
F0925 14:13:55.723853       1 builder.go:54] Build error: dial tcp: lookup github.com: no such host

Michal fojtik told me to tag @mrunalp

Environment:

Container installed on a bare metal system.

Events from Openshift UI this was after another fresh try.:

1:35:01 PM	jenkins-master-1-build	Pod	killing	Killing with docker id e66e43c50172
1:34:42 PM	jenkins-master-1-build	Pod	created	Created with docker id 3a118395f248
1:34:42 PM	jenkins-master-1-build	Pod	started	Started with docker id 3a118395f248
1:34:41 PM	jenkins-master-1-build	Pod	pulled	Container image "openshift/origin-docker-builder:v1.0.6" already present on machine
1:34:32 PM	jenkins-master-1-build	Pod	started	Started with docker id e66e43c50172
1:34:32 PM	jenkins-master-1-build	Pod	failedSync	Error syncing pod, skipping: open /proc/4390/cgroup: no such file or directory
1:34:32 PM	jenkins-master-1-build	Pod	created	Created with docker id e66e43c50172
1:34:31 PM	jenkins	DeploymentConfig	failedCreate	Couldn't create initial deployment: DeploymentConfig "jenkins" is invalid: triggers[0].imageChange.tag: invalid value 'latest', Details: no image recorded for ci-test/jenkins-master:latest
1:34:31 PM	jenkins-master-1-build	Pod	scheduled	Successfully assigned jenkins-master-1-build to banshee.bos.redhat.com
1:34:31 PM	jenkins-master-1-build	Pod	pulled	Container image "openshift/origin-pod:v1.0.6" already present on machine
11:36:20 AM	ruby-20-centos7-slave-1-9608107964-build	Pod	killing	Killing with docker id b8926ad8259b
11:36:00 AM	ruby-20-centos7-slave-1-9608107964-build	Pod	created	Created with docker id 9856449f8f55
11:36:00 AM	ruby-20-centos7-slave-1-9608107964-build	Pod	started	Started with docker id 9856449f8f55
11:35:59 AM	ruby-20-centos7-slave-1-9608107964-build	Pod	pulled	Container image "openshift/origin-docker-builder:v1.0.6" already present on machine
11:35:50 AM	ruby-20-centos7-slave-1-9608107964-build	Pod	created	Created with docker id b8926ad8259b
11:35:50 AM	ruby-20-centos7-slave-1-9608107964-build	Pod	started	Started with docker id b8926ad8259b
11:35:50 AM	ruby-20-centos7-slave-1-9608107964-build	Pod	failedSync	Error syncing pod, skipping: open /proc/25523/cgroup: no such file or directory
11:35:49 AM	ruby-20-centos7-slave-1-9608107964-build	Pod	pulled	Container image "openshift/origin-pod:v1.0.6" already present on machine
11:35:49 AM	ruby-20-centos7-slave-1-9608107964-build	Pod	scheduled	Successfully assigned ruby-20-centos7-slave-1-9608107964-build to banshee.bos.redhat.com
11:35:21 AM	ruby-20-centos7-slave-1-build	Pod	killing	Killing with docker id 2619f56b5556

**Comment by bparees** [comment]
@arilivigni can you tell us about your environment?  how are you running openshift?  (vagrant?  direct on a host?  via a container?)

if you oc rsh into the jenkins master, does it have any external network connectivity?  can you show the contents of /etc/resolv.conf for that pod/container?

**Comment by arilivigni** [comment]
This issue can be closed it had to do with my version of Docker.  Once I
upgraded I got past the issue.

-== @ri ==-

**Comment by bparees** [comment]
thanks @arilivigni !
