### ISSUE TITLE
Create Reaper for Role

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4808]
Cleanup rolebindings when roles are removed.

@liggitt mine

**Comment by smarterclayton** [comment]
Hrm.... who removes roles, how often do they do it, and why do they remove them?

**Comment by deads2k** [comment]
> Hrm.... who removes roles, how often do they do it, and why do they remove them?

Testers do it and it messes with referential integrity.  I was going to start with just the project scoped roles, so the cost is relatively small.  I don't know of anyone else doing it offhand.

**Comment by smarterclayton** [comment]
Hrm... I can't say it's been something I think of as "top 10 things I'm
worried about wrt policy..." :)

On Oct 5, 2015, at 7:42 AM, David Eads <notifications@github.com> wrote:

Hrm.... who removes roles, how often do they do it, and why do they remove
them?

Testers do it and it messes with referential integrity. I was going to
start with just the project scoped roles, so the cost is relatively small.
I don't know of anyone else doing it offhand.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4808#issuecomment-145502665>.

**Comment by deads2k** [comment]
> Hrm... I can't say it's been something I think of as "top 10 things I'm
> worried about wrt policy..." :)

Wait, there's at least **ten** things wrong with policy?? :)
