### ISSUE TITLE
Passing invalid Dockerfile to oc new-app fails silently

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#4812]
Steps to reproduce:

```
$ cat bzzz/Dockerfile 
FROM busybox
NOT
$ oc new-app --code=bzzz --strategy=docker
Run 'oc status' to view your app.
```

Result: nothing was created.

Expected: an error message or, at least, not the line "Run 'oc status' to view your app."

-------------------------

I did a bit of investigation and found that:
1. [Parse](https://github.com/openshift/origin/blob/d197481becf383d47bdf526f7d290e169683c946/pkg/generate/dockerfile/parser.go#L35) returns an error `Invalid Dockerfile` that somehow is ignored along the way.
2. Even though [`result.List.Items`](https://github.com/openshift/origin/blob/d197481becf383d47bdf526f7d290e169683c946/pkg/cmd/cli/cmd/newapp.go#L201) is empty, we still print the message "Run 'oc status' to view your app."

**Comment by kargakis** [comment]
Can you rerun `oc new-app` with `--loglevel=1` and post the output?
