### ISSUE TITLE
openshift-master failed to start after reboot

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/origin#4818]
I did a clean installation with `openshift-ansible/byo` on a 3 nodes cluster. After the installation, I rebooted the master node and found `origin-master` service failed to start. The log says

	[centos@master ~]$ sudo systemctl status origin-master -ll
	origin-master.service - Origin Master Service
	   Loaded: loaded (/usr/lib/systemd/system/origin-master.service; enabled)
	   Active: failed (Result: exit-code) since Sun 2015-09-27 20:48:39 UTC; 6min ago
	     Docs: https://github.com/openshift/origin
	 Main PID: 818 (code=exited, status=255)
	   CGroup: /system.slice/origin-master.service

	Sep 27 20:48:37 master.novalocal origin-master[818]: [644.777407ms] [3.507µs] List filtered
	Sep 27 20:48:37 master.novalocal origin-master[818]: [644.779048ms] [1.641µs] END
	Sep 27 20:48:38 master.novalocal origin-master[818]: I0927 20:48:38.341473     818 trace.go:57] Trace "List *api.ServiceList" (started 2015-09-27 20:48:37.678742796 +0000 UTC):
	Sep 27 20:48:38 master.novalocal origin-master[818]: [2.248µs] [2.248µs] About to list directory
	Sep 27 20:48:38 master.novalocal origin-master[818]: [662.694178ms] [662.69193ms] List extracted
	Sep 27 20:48:38 master.novalocal origin-master[818]: [662.70097ms] [6.792µs] List filtered
	Sep 27 20:48:38 master.novalocal origin-master[818]: [662.702554ms] [1.584µs] END
	Sep 27 20:48:39 master.novalocal origin-master[818]: F0927 20:48:39.029842     818 flatsdn.go:25] SDN initialization failed: exit status 1
	Sep 27 20:48:39 master.novalocal systemd[1]: origin-master.service: main process exited, code=exited, status=255/n/a
	Sep 27 20:48:39 master.novalocal systemd[1]: Unit origin-master.service entered failed state.
	[centos@master ~]$

**Comment by nak3** [comment]
@xionglingfeng 
Could you please test to run `hostname -f` on your master host and how us the output?

The error came from here with returning `exit 1`.
https://github.com/openshift/origin/blob/v1.0.6/plugins/osdn/flatsdn/flatsdn.go#L23-L26

**Comment by xionglingfeng** [comment]
@nak3 , here's the output

	[centos@master ~]$ hostname -f
	hostname: Name or service not known
	[centos@master ~]$ hostname
	master
	[centos@master ~]$ cat /etc/hostname 
	master.novalocal
	[centos@master ~]$ 

This VM is on OpenStack and the hostname is automatically set. Any idea?

**Comment by nak3** [comment]
I have handled this issue before here https://github.com/openshift/origin/pull/1597, but it looks like it created again.
I will send the patch to fix it again.

As a workaround could you please try to set your IP and hostname in `/etc/hosts` like:

`192.168.133.2   ose3-master.example.com`

**Comment by xionglingfeng** [comment]
@nak3 Since I have a working DNS server in control, I removed all items other than `localhost` in `/etc/hosts`, add the search domain in `/etc/resolv.conf` and set my hostname to a FQDN manually with `user-data`

    #cloud-config
    hostname: xxx.example.com

Then it works.

It would be better if the dependency of `hostname` can be removed.

**Comment by nak3** [comment]
> It would be better if the dependency of hostname can be removed.

Yes. So, I think this patch to replace it with `uname -n` https://github.com/openshift/openshift-sdn/pull/169 will fix this issue.

**Comment by pravisankar** [comment]
Fix https://github.com/openshift/openshift-sdn/pull/169 already merged in origin.
