### ISSUE TITLE
How do I make a suite of extended tests that...

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4831]
1 .Startup openshift using non-default configuration parameters
1. Start running a series of testing infrastructure related builds, deployments, etc
1. Run a suite of ginkgo tests against the server set up in that configuration.

We handled this before by having different launch scripts.  Do I now
1. Create a fresh launch script.
1. Add a SKIP line to `core.sh` to exclude my suite
1. Run this how?

**Comment by mfojtik** [comment]
@deads2k 

1. Create `./test/extended/foo.sh`
2. Start OpenShift server there
3. Kick the builds from the script (oc start-build)
4. Run the ginkgo test suite (set focus on things you want to run)

In PR, you can run this by: [test][extended:foo] or [testextendedonly][extended:foo] or manually by running the script directly (`./test/extended/foo.sh`)

**Comment by deads2k** [comment]
Ok.  I think that suits.
