### ISSUE TITLE
openshift-master did not restart properly after reboot

### ISSUE THREAD

**Issue by readonly** [openshift/origin#4837]
We have a 2-host setup: host 1 is master + node, host 2 is node only. Currently we run 1.0.4, installed via openshift-ansible.

Sometimes there are hickups when rebooting one machine. While openshift + components are enabled as startup-services, sometimes the master just fails starting. Recently with the following `/var/log/message` (only relevant lines):

```
Sep 27 09:13:38 microsd6 openshift-master: I0927 09:13:38.298354    2115 start_master.go:308] Starting master on 0.0.0.0:8443 (v1.0.4-1-g85eea33)
Sep 27 09:13:38 microsd6 openshift-master: I0927 09:13:38.298509    2115 start_master.go:309] Public master address is https://microsd6.xx.xx.xx:8443
Sep 27 09:13:41 microsd6 openshift-master: I0927 09:13:41.946058    2115 run_components.go:169] Using default project node label selector: region=europe
Sep 27 09:13:44 microsd6 openshift-master: I0927 09:13:44.988765    2115 plugins.go:70] No cloud provider specified.
Sep 27 09:13:44 microsd6 openshift-master: I0927 09:13:44.989773    2115 master.go:290] Will report 10.18.209.20 as public IP address.
Sep 27 09:14:09 microsd6 openshift-master: F0927 09:14:09.948006    2115 controller.go:80] Unable to perform initial IP allocation check: unable to persist the updated service IP allocations: 501: All the given peers are not reachable (failed to propose on members [https://microsd6.xx.xx.xx:2379 https://microsd7.xx.xx.xx:2379] twice [last error: Unexpected HTTP status code]) [0]
Sep 27 09:14:09 microsd6 systemd: openshift-master.service: main process exited, code=exited, status=255/n/a
Sep 27 09:14:09 microsd6 systemd: Unit openshift-master.service entered failed state.
```

Googling for "Unable to perform intial IP allocation check" brings me to kubernetes pages, some suggest that maybe etcd is not running.

Since this happens only sometimes and restarting the service fixes it - are there maybe racing conditions during boot, and depending what services startup when the master works or not?

**Comment by brenton** [comment]
@readonly For clarification, can you tell me if you are using the Master's embedded etcd or are you running etcd in a separate process?  I'm assuming the latter if you are clustering etcd and installed via ansible.  I would assume this doesn't have anything to do with the Master but instead somehow the Master cannot reach etcd.  @sdodson, does that sound accurate to you?

**Comment by brenton** [comment]
@readonly, it would probably be helpful to know the version of etcd you are running as well.

**Comment by readonly** [comment]
It is an external, two-node etcd, setup via ansible hosts file as `[etcd]`, but we never specify a specific version. Actually they run on the same two machines as described above. The etcd running afterwards is 2.1.1.

So the setup is:
microsd6: openshift-master, openshift-node, etcd
microsd7: openshift-node, etcd

We use openshift-ansible commit ee97dd9be30d3d818cf4b8e86ace6e34ae5405ca for installing.

I can't say for sure if at the time the openshift-master failed to start there was the second etcd running on the other host, as this was a complete reboot of the VMware cluster that hosts both (virtual) machines.

**Comment by sdodson** [comment]
@readonly Yeah, your etcd cluster wasn't online. We can change the restart policy of the master to Restart=always so that it will continue attempting to start indefinitely. Update */usr/lib/systemd/system/openshift-master.service* to be like this

```
[Unit]
Description=OpenShift Master
Documentation=https://github.com/openshift/origin
After=network.target
After=etcd.service
Before=openshift-node.service
Before=openshift-sdn-node.service
Before=openshift-sdn-master.service
Requires=network.target

[Service]
Type=notify
EnvironmentFile=/etc/sysconfig/openshift-master
Environment=GOTRACEBACK=crash
ExecStart=/usr/bin/openshift start master --config=${CONFIG_FILE} $OPTIONS
LimitNOFILE=131072
LimitCORE=infinity
WorkingDirectory=/var/lib/openshift/
SyslogIdentifier=openshift-master
Restart=always

[Install]
WantedBy=multi-user.target
WantedBy=openshift-sdn-master.service
WantedBy=openshift-node.service
```

Then reload systemd `systemctl daemon-reload`

**Comment by readonly** [comment]
I tried a few reboots on both machines simultaneously, and so far it did not happen again. Since this does not happen fully reproducible, I can't say for sure it is fixed, but it's looking good. In case of troubles I'll reopen the issue again.
