### ISSUE TITLE
"ethtool": executable file not found in $PATH

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#4843]
Running the newest code in the vagrant dev vm, getting errors like this in the server logs:

I0929 14:16:15.915427   18952 hairpin.go:49] Unable to find pair interface, setting up all interfaces: exec: │
"ethtool": executable file not found in $PATH

Do we have a new dependency?

**Comment by rhcarvalho** [comment]
@kargakis FYI this is coming from kube

**Comment by kargakis** [comment]
This comes from the kubelet (https://github.com/kubernetes/kubernetes/pull/13628). Anybody more familiar in that area? @deads2k @pweil- @ncdc

**Comment by ncdc** [comment]
Sounds like pulling in ethtool is the way to go.

**Comment by kargakis** [comment]
@ncdc should we pull this into one of our images? If so, which one?

**Comment by ncdc** [comment]
If you're running OpenShift containerized, it'll need to go into the openshift/origin image. We'll also need to update the spec file for the openshift-node package to pull it in. And we'll probably want to update the Vagrant images as well.

cc @smarterclayton @sdodson @brenton @danmcp

**Comment by smarterclayton** [comment]
Pull it in to origin-base.

**Comment by sdodson** [comment]
Fixes in #4866 seem to account for everything except Vagrantfile.

**Comment by kargakis** [comment]
> Fixes in #4866 seem to account for everything except Vagrantfile.

Added in the Vagrant plugin: https://github.com/openshift/vagrant-openshift/pull/332

**Comment by danmcp** [comment]
@rhcarvalho @kargakis Anything left here

**Comment by rhcarvalho** [comment]
@danmcp, @kargakis's PR was not merged yet. When it merges it will close this issue.
