### ISSUE TITLE
"You are not a member of project" when creating a new project for a new user.

### ISSUE THREAD

**Issue by tiwillia** [openshift/origin#4870]
The following error is reported rarely when quickly logging in and creating a project for a new user:
```
  error: You are not a member of project "user499-project".
  You are not a member of any projects. You can request a project to be created with the 'new-project' command.
```

To reproduce, I did the following for loop, creating users and a single project for each user:
```
  for i in $(seq 1 1000); do
    oc login -u user$i -p "pass" --server=ec2-54-165-38-199.compute-1.amazonaws.com "--insecure-skip-tls-verify=true" --config=/tmp/user$i.kubeconfig;
    oc new-project user$i-project --display-name=user$i-project --description="test" --config=/tmp/user$i.kubeconfig;
    if [[ $? != 0 ]]; then
      echo "ERROR ENCOUNTERED at $(date)";
      break;
    fi;
  done
```

Below are the errors in the openshift log at that time:
```
  Sep 30 11:03:46 ip-172-18-2-171.ec2.internal openshift[2294]: E0930 11:03:46.538039    2294 serviceaccounts_controller.go:218] serviceaccounts "deployer" already exists
  Sep 30 11:03:46 ip-172-18-2-171.ec2.internal openshift[2294]: E0930 11:03:46.108042    2294 serviceaccounts_controller.go:218] serviceaccounts "deployer" already exists
  Sep 30 11:03:45 ip-172-18-2-171.ec2.internal openshift[2294]: http: TLS handshake error from 172.18.2.171:35607: remote error: bad certificate
  Sep 30 11:03:45 ip-172-18-2-171.ec2.internal openshift[2294]: http: TLS handshake error from 172.18.2.171:35604: remote error: bad certificate
  Sep 30 11:03:44 ip-172-18-2-171.ec2.internal openshift[2294]: http: TLS handshake error from 172.18.2.171:35601: remote error: bad certificate
  Sep 30 11:03:44 ip-172-18-2-171.ec2.internal openshift[2294]: E0930 11:03:44.707915    2294 serviceaccounts_controller.go:218] serviceaccounts "deployer" already exists
```

During scalability testing, after creating ~15,000 users & projects and ~45,000 deploymentConfigs & replicationControllers, this error is eventually hit with every new user & project created. The error does happen intermittently throughout the testing, before a large number of users exist on the system.

**Comment by deads2k** [comment]
I'm betting the project cache hasn't caught up with policy changes before the list project request makes it in.

@liggitt We could want for a couple seconds to see the project we expect, but if the cache gets slow enough, this will fail.

**Comment by liggitt** [comment]
why is new-project doing a `list projects` call? If the API call succeeds, we should just set the context to the new project... no need to list

**Comment by deads2k** [comment]
It just delegates to `oc project`.  There's a lot of weird handling of overlapping contexts.  We could ignore all those and duplicate create logic.

**Comment by liggitt** [comment]
or have an option to skip list validation and just do the `get` on the requested project, and set that to true when delegating from `new-project`
