### ISSUE TITLE
Token available in GUI 

### ISSUE THREAD

**Issue by Mangirdaz** [openshift/origin#4885]
I have bunch of automation with custom container "oc-client", which orchestrates all my deployments in my name/user. For this i need to pass my token as a parameter from GUI to container. It would be great if i could get field where i can copy it when i login to GUI. 

This would let personalized automation/deployments in full monitored environments.

**Comment by smarterclayton** [comment]
One challenge with the OAuth token is that it has an expiration that is relatively short.  If you want to guarantee the token can be used for orchestration, you can also create a service account token and grant it the required role on a project (or multiple projects).   That token lasts until you explicitly delete the secret.

@liggitt

**Comment by Mangirdaz** [comment]
I fully understand. But this is case where i want to create short time access.
. I have an image, with OC client inside, and assemble scripts does some automation by taking my bunch of template scripts in git and executing them on env using my token (passed via variables). This creates and destroys my test environments in a seconds. 

I want users to execute these things using their own accounts for tracing and governance. 

+Additionally service account creation capability should be available via GUI with exposed token.

Mangirdas

**Comment by liggitt** [comment]
cc @jwforres

**Comment by Mangirdaz** [comment]
Thanks :+1:

**Comment by jwforres** [comment]
See https://github.com/openshift/origin/pull/6783
