### ISSUE TITLE
test-cmd is too verbose

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4892]
On Travis we now see: `This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log.` This is not ideal and a pain, especially because all of the pretty-printing directives and formatting used for the terminal are not parsed correctly in the `.txt` file you download, so readability suffers.

A major component of this is `test-cmd`. I think it would be really nice to only enable full verbose output if:
* the user requests it via a flag
* the current suite (`admin`, `builds`, etc) fails, and then only the output for that suite should be shown

The normal output for a perfectly-working `test-cmd` without the verbose flag should look like:
```
validation: ok
apiserver: ok
apiserver(ready): ok
config files: ok
edit: ok
export: ok
resource-builder: ok
pods: ok
label: ok
services: ok
nodes: ok
routes: ok
expose: ok
...
```

@smarterclayton @liggitt thoughts?

**Comment by liggitt** [comment]
+100

**Comment by liggitt** [comment]
see test-integration.sh for an example of capturing output and displaying in failure cases, or dumping in verbose mode

**Comment by deads2k** [comment]
Didn't we try this one before and @smarterclayton shot it down with the claim that he caught bugs by watching output scroll by.

**Comment by stevekuznetsov** [comment]
@deads2k Yes. He can stick `-v` on his output to retain that functionality. I want to be able to see failures in Travis easily.

**Comment by smarterclayton** [comment]
Then Travis should be -q.  When you run it directly, we didn't used to cat
the logs, so you should see the failures directly.

On Oct 1, 2015, at 5:29 PM, Steve Kuznetsov <notifications@github.com>
wrote:

@deads2k <https://github.com/deads2k> Yes. He can stick -v on his output to
retain that functionality. I want to be able to see failures in Travis
easily.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4892#issuecomment-144763118>.

**Comment by liggitt** [comment]
@smarterclayton the test-integration.sh approach is better... you can see all output in realtime if you want, but the default only shows you failures

**Comment by smarterclayton** [comment]
It runs until it fails and prints output.  Logs on Travis being too long is
fine, I'm not particularly concerned with your shell scroll buffer if it
occasionally exposes ugly cli output.

On Oct 1, 2015, at 10:58 PM, Jordan Liggitt <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> the test-integration.sh
approach is better... you can see all output in realtime if you want, but
the default only shows you failures

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4892#issuecomment-144846357>.

**Comment by stevekuznetsov** [comment]
This has been fixed with `os::cmd` somewhat, however there are some offenders still.
