### ISSUE TITLE
"oc edit scc restricted" not working on Windows 7 with Notepad

### ISSUE THREAD

**Issue by myfear** [openshift/origin#4904]
The command opens the yml file in notepad but screws up the line-endings.
And I can't save the file because notepad warns about another process (I assume the cmd?) is holding a lock on the file.

**Comment by smarterclayton** [comment]
@fabianofranz we probably need to be closing the file handle (I bet we do a defer f.Close() instead of a direct), and line endings should be written based on OS type - we may have to convert line endings in the output YAML.

**Comment by fabianofranz** [comment]
Fixed by https://github.com/openshift/origin/pull/5300 and https://github.com/openshift/origin/pull/5306, @liggitt please close.
