### ISSUE TITLE
oc new-app --docker-image=<image> doesn't map pod port to service port

### ISSUE THREAD

**Issue by myfear** [openshift/origin#4905]
I can run a docker image via the command. And it creates a service. But the service port mapping is weird.

 none→172.30.75.14:8080→8080 (TCP)

So, the pod port doesn't get mapped to the service port. 

I ran 
oc expose service/name 

And the route was setup.

**Comment by smarterclayton** [comment]
Quick question - image had EXPOSE 8080, pod got 8080, service *didn't* get 8080?

**Comment by myfear** [comment]
Digging around a little more: I am playing with the all in one vm.
And it turns out, that the port 80 wasn't exposed from the openshift vagrant box to my host system.
After adding the port-forwarding rule, it works.

I was under the impression, that this is done under the hood. But probably can't be done at all.
