### ISSUE TITLE
Have to click "Try it" link twice if name field is empty on create page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4912]
The name field loses focus, which causes validation to occur. It prevents the "Try it" link from working.

**Comment by spadgett** [comment]
@jwforres please assign to me.

**Comment by spadgett** [comment]
The problem is that mouse down on the link blurs the field and the error message moves the link from under the cursor before mouse up.

**Comment by liggitt** [comment]
not sure I like showing an error just on focus, then blur... means tabbing through the interface leaves an error in place

**Comment by spadgett** [comment]
I could change it to only happen when the user types in the field. The fields have an asterisk indicating they're required, and the create button is disabled.

**Comment by liggitt** [comment]
+1 for erroring/warning once a value is entered, then removed

**Comment by spadgett** [comment]
I'd still like to avoid the invalid value errors flashing as you type. Let me look at it.
