### ISSUE TITLE
Allow advanced users to stop seeing the next steps page

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#4915]
Set a user pref in localStorage

**Comment by smarterclayton** [comment]
The text to hide it should be "I get it, I get it!  Geez"

**Comment by fabianofranz** [comment]
As a future enhancement we could try to be smarter about this - e.g. hide the `oc login` instructions if you ever logged in from `oc` already, etc.

**Comment by jwforres** [comment]
Need to consider what happens if they've chosen not to see the next steps page but the template they created has a post-processing message.

**Comment by jwforres** [comment]
I think now that we are showing generated parameters and template post processing messages on this page that it may be detrimental to allow people to permanently dismiss it.

@ajacobs21e thoughts?

**Comment by ajacobs21e** [comment]
yeah @jwforres without having another way to access that information this page should stay. However I would prefer if this information was accessible elsewhere and then the user had a way to get rid of this page.

**Comment by jwforres** [comment]
@ajacobs21e this information doesn't persist, it only exists right after we instantiate the template.  Do you mean that we should make it available at the top of the overview right after creation?

**Comment by smarterclayton** [comment]
There have been requests to make it easy to capture the template parameters
as a config map.  In the longer term.

On Mon, Nov 21, 2016 at 3:16 PM, Jessica Forrester <notifications@github.com

**Comment by ajacobs21e** [comment]
@jwforres The "command line tools" info could be part of the project settings and the "making code changes" could be within the build / other resource 's detail page.

**Comment by jwforres** [comment]
@ajacobs21e we have a command line help page today, I think it covers everything next steps covers and more.  Agreed we could probably move the making code changes to somewhere in the build page.

My main concern is what to do with the information that is the immediate result of the template being instantiated.  This includes the result of any parameters whose values were generated on the user's behalf, the user won't know the values unless we display them to them right then.  The other is the message that template author's provide to end users that appears after the template is instantiated.  This often includes things like information on how to log into your database.

**Comment by ajacobs21e** [comment]
ah ok @jwforres I don't see those messages since I don't have real code to deploy.

Would it be possible to show the message in those instances where there is relevant data but if it's the standard interstitial the user has the option to not show it?

**Comment by jwforres** [comment]
yeah that should be possible, we know whether that sort of info exists
before we navigate to the next steps page

**Comment by ajacobs21e** [comment]
is that a good compromise?
-make the basic info available elsewhere
-give user option to dismiss the generic message
-still show the page if there are parameters / template messages

**Comment by jwforres** [comment]
/close

These pages have almost all moved to the confirmation step in wizards now
