### ISSUE TITLE
Add suggestions to catalog filter keyword search

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4918]
We can use selectize or a similar widget to add a list of suggestions as you type like the label filter. Possibly remove the browse button.

@jwforres @tracyrankin

**Comment by jwforres** [comment]
yeah we should use selectize anywhere we plan to do typeaheads

**Comment by jwforres** [comment]
@spadgett i'm going to mark it 1.1.0 for now so it stays on the radar but this may be on the bubble of being too big of a change to get it in

**Comment by spadgett** [comment]
@jwforres There is an angular bootstrap typeahead widget, which is more angular-friendly and already a dependency. It'd probably look different than the label selector, though.

https://angular-ui.github.io/bootstrap/

**Comment by jwforres** [comment]
@spadgett so we used selectize for the label filter because it supported multi-select.  But if the bootstrap one is easier to use for simple typeaheads, maybe we just need to re-theme the dropdown for consistency?  either re-theme the label filter one to look like the bootstrap one or vice versa.

cc @sg00dwin

**Comment by spadgett** [comment]
Potential problem, the dropdown can obscure as-you-type search results.

<img width="583" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11121090/ea4b1f64-8921-11e5-918c-2353dcf18ba7.png">

**Comment by spadgett** [comment]
Maybe it isn't bad if we filter the suggestions to only those that match.

**Comment by spadgett** [comment]
<img width="661" alt="openshift_web_console" 
src="https://cloud.githubusercontent.com/assets/1167259/11121261/cf2462da-8922-11e5-8141-5b5060fa36e3.png">

**Comment by spadgett** [comment]
After filtering the suggestions... Would be nice if we can avoid covering the group heading.

<img width="602" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11121278/e3240a06-8922-11e5-9815-4493d32f9522.png">

<img width="661" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11121293/faaf0022-8922-11e5-813d-8a77a3201c2c.png">

**Comment by jwforres** [comment]
@spadgett still something you want to pick up later? or was the behavior too weird and we should close this?

**Comment by jwforres** [comment]
This doesn't make sense anymore with the catalog redesign
