### ISSUE TITLE
deployment annotations shows failed even if it succeeded.

### ISSUE THREAD

**Issue by rettori** [openshift/origin#4935]
After running the default java wildfly example, it deploys, but on the deployment annotations it shows as failed.
<img width="724" alt="screen shot 2015-10-04 at 3 58 16 pm" src="https://cloud.githubusercontent.com/assets/2352755/10269903/e7387680-6ab0-11e5-8569-35ce13119a33.png">
<img width="833" alt="screen shot 2015-10-04 at 3 58 47 pm" src="https://cloud.githubusercontent.com/assets/2352755/10269905/e94cb8aa-6ab0-11e5-9c35-ed684cc13f32.png">
The build
<img width="1028" alt="screen shot 2015-10-04 at 3 59 16 pm" src="https://cloud.githubusercontent.com/assets/2352755/10269907/eb00f2e2-6ab0-11e5-8b17-6aa68955d543.png">

**Comment by kargakis** [comment]
Fixed by https://github.com/openshift/origin/pull/4963
