### ISSUE TITLE
Certificate problem in builder container (Peer's Certificate has expired)

### ISSUE THREAD

**Issue by MacThrawn** [openshift/origin#4937]
We are trying to setup a BuildConfiguration and get the following failure in the builder container:

> I1005 07:23:42.712123       1 docker.go:203] Cloning source from https://github.com/openshift/origin.git
> E1005 07:23:42.903483       1 git.go:102] Clone failed: fatal: unable to access 'https://github.com/openshift/origin.git/': Peer's Certificate has expired.
> F1005 07:23:42.903537       1 builder.go:54] Build error: exit status 128

We are facing the same problem by using a private GIT repository, but for reproducability we setuped a Build that try to build an Origin image from the official GitHub repository. A GIT clone of this repository on our OpenShift nodes works fine.

Here is our BuildConfiguration:

> {
>   "kind": "BuildConfig",
>     "apiVersion": "v1",
>     "metadata": {
>       "name": "demo"
>     },
>   "spec": {
>     "source": {
>       "type": "Git",
>       "git": {
>         "uri": "https://github.com/openshift/origin.git"
>       },
>       "contextDir": "images/deployer"
>     },
>     "strategy": {
>       "type": "Docker",
>         "dockerStrategy": {
>         "nocache": true
>       }
>     }
>   }
> }

We are using the 1.0.6 release of OpenShift Origin.

**Comment by liggitt** [comment]
This sounds like an issue we saw where all URLs were resolving to the master from within pods. Obviously the master doesn't have a valid cert for github.com. Can you launch a pod, exec in, and see what IP `github.com` resolves to?

If it resolves to the master IP, this may be the cause and resolution:

> NetworkManager / dhcp is adding the host's domain name to the search
path. If your host's domain name matches the wildcard path then you'll
end up with these problems.
> 
> wildcard *.apps.example.com  and {master,nodeX}.example.com is safe
> 
> wildcard *.example.com and {master,nodeX}.example.com is not

**Comment by MacThrawn** [comment]
Yes this was the problem. The DnsDomain entry in the node configuration was example.com and the wildcard DNS entry in our company Dns Server was *.example.com and points to a node where we run our router. Changing the node configuration to a different DnsDomain fixed the problem. Thx.
