### ISSUE TITLE
new-app: partial match results should result in message displaying what was found

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#4944]
calling new-app with 'openshift/ruby-20-rhel75' when only 'openshift/ruby-20-rhel7' is available, currently proceeds  with the partial match without a warning. 

If all we can find is a partial match, we should return with a message saying what the match was to let you pick it explicitly.

**Comment by csrwng** [comment]
@bparees @smarterclayton

**Comment by smarterclayton** [comment]
Yes
