### ISSUE TITLE
Limit column widths in oc get build output

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#4950]
We need to:

1. Consider the `wide` flag to limit the output width to max 80 or 120 chars.
2. Limit the width of each column based on the total limit.

**Comment by php-coder** [comment]
The similar issue in k8s: https://github.com/kubernetes/kubernetes/issues/7843

**Comment by php-coder** [comment]
After reading k8s tickets/commits my understanding is that `-o wide` option was designed to being used in a slightly different way: it doesn't limit width of columns but show additional columns.

Quote from [kubectl convention](https://github.com/kubernetes/kubernetes/blob/a5a917603c21217deb166dccac0f6a65f3fb543a/docs/devel/kubectl-conventions.md#output-conventions):
>By default, get output should fit within about 80 columns
>
>    * Eventually we could perhaps auto-detect width
>    * -o wide may be used to display additional columns

For instance, `kubectl get pods -o wide` will output extra column with node name ([source](https://github.com/kubernetes/kubernetes/blob/a5a917603c21217deb166dccac0f6a65f3fb543a/pkg/kubectl/resource_printer.go#L597-L604)).

So, what will we do with this issue?

**Comment by bparees** [comment]
@rhcarvalho given your new implementation of get builds i don't think we need to do anything here, reopen if you disagree.

**Comment by rhcarvalho** [comment]
I agree.
