### ISSUE TITLE
sample-app: cleanup.sh script uses killall command that isn't installed in Vagrant image

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#4959]
I'm following the instruction and trying to create/run/delete the sample app. In chapter [Cleaning Up](https://github.com/openshift/origin/tree/master/examples/sample-app#cleaning-up) there is a `cleanup.sh` invocation:

```
[vagrant@openshiftdev sample-app]$ sudo ./cleanup.sh 
Killing openshift all-in-one server ...
./cleanup.sh: line 4: killall: command not found
Cleaning up openshift runtime files ...
Stopping all k8s docker containers on host ...
```

As you can see, this script uses `killall` command that isn't present on OS in Vagrant's VM.

Steps to reproduce:
1) `cd origin`
2) `vagrant up`
3) `vagrant ssh`
4) `cd /data/src/github.com/openshift/origin/examples/sample-app`
5) `sudo ./cleanup.sh`

I see the following ways to fix it:
- update instruction and add `dnf install -y psmisc` command invocation prior to running this script
- update provision script to install this package during OS bootstrap
- (may be) replace `killall` with `pkill` command

**Comment by mfojtik** [comment]
+1 for replacing killall with pkill

**Comment by kargakis** [comment]
:+1:

**Comment by kargakis** [comment]
We are using `pkill` elsewhere (11. in https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-on-virtual-machine-using-vagrant), @php-coder mind updating this too?

**Comment by php-coder** [comment]
@kargakis Should I update [here](https://github.com/openshift/origin/blob/master/docs/debugging-openshift.md#name-resolution-within-containers) too?

**Comment by php-coder** [comment]
I've submitted PR #4982

**Comment by danmcp** [comment]
@php-coder Anything else to fix here or can this be closed?  Note: if you reference the issue from the PR in the desc it will close the issue when the PR merges.

https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by php-coder** [comment]
@danmcp Yes, it's can be closed. Thanks for spotting this.
