### ISSUE TITLE
Use consistent names for extended tests ginkgo tests

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#4961]
Currently we have names like this (just few examples):

```
"images: mysql: ephemeral template"
"Creating from a template"
"Building "+c.repoName+" app from new-app"
"samplerepo: test the sample application repositories"
"samplerepo: images: parallel: test ruby images with rails-ex repo"
"samplerepo: images: parallel: test python images with django-ex repo"
"samplerepo: images: parallel: test nodejs images with nodejs-ex repo"
"samplerepo: images: parallel: test php images with cakephp-ex repo"
"samplerepo: images: parallel: test perl images with dancer-ex repo"
"images: mysql: replication"
"ldap: Authenticate using LDAP"
"default: STI build"
"Building from a template"
"builds: labels: Check S2I and Docker build image for proper Docker labels"
"S2I build from a template"
"Docker build from a template"
"builds: parallel: Dockerfile input"
"being created from new-app"
"builds: incremental: S2I incremental build with push and pull to authenticated registry"
"Building from a template"
"builds: forcepull: ForcePull from OpenShift induced builds (vs. s2i command)"
"builds: sti_env: STI build with .sti/environment file"
"Building from a template"
"builds: parallel: oc start-build"
"oc start-build --wait"
"cancelling build started by oc start-build --wait"
"Router"
"The HAProxy router"
"authentication: OpenLDAP build and deployment"
"Building and deploying an OpenLDAP server"
"networking: sanity"
"networking: isolation"
```

This is making it relatively hard to use when trying to specify the right `-focus`.

**Comment by mfojtik** [comment]
@stevekuznetsov @smarterclayton @liggitt @bparees FYI, we should make this consistent and useful so we can group things together in a smart way and also tell what those tests are doing ;-)

**Comment by stevekuznetsov** [comment]
I think it makes the most sense to prepend tags, and enforce that every test has at least one tag. 
```
[builds] [parallel] name of test
```

**Comment by mfojtik** [comment]
@stevekuznetsov this turns into how you want to run the tests from a PR... I think having to write `[test][extended:core([builds] [parallel])]` will be ugly...

**Comment by mfojtik** [comment]
"samplerepo: images: parallel: test ruby images with rails-ex repo"

can become: "The ruby images with the rails-ex samplerepo"... (similar to other test cases). Then if I run:

[test][extended:core(images samplerepo)] I can trigger all of them.

**Comment by bparees** [comment]
@mfojtik i don't like that.  I want to be able to look at a test case and easily pick out the keywords that the TC shares with other TCs so i can pick a focus.  hiding them in a sentence makes that hard.

**Comment by bparees** [comment]
@mfojtik I actually like the "tag: othertag: thirdtag: some TC description" pattern.

**Comment by bparees** [comment]
@mfojtik remember that you don't have to put the ":" in the github comment either, to get a match.

**Comment by mfojtik** [comment]
@bparees I was hoping that we can make the descriptions "human friendly" as well :-) it might be good exercise for us to think twice before naming tests

**Comment by bparees** [comment]
@mfojtik i think what i proposed is the best trade off of human readable descriptions but also easily parsed focus tag delineation.

**Comment by mfojtik** [comment]
@bparees my concern is that people will write something like "builds: images: ruby" instead of "The ruby image should work for builds"

**Comment by bparees** [comment]
@mfojtik if my choice is one of those two, i prefer the former.

obviously "builds: images: ruby: the ruby image should work for builds" would be preferred.

**Comment by mfojtik** [comment]
@bparees I think that is fair, but you will not have a way to force people to write these descriptions ;-) Other than yelling on them during code reviews ;-)

**Comment by bparees** [comment]
@mfojtik again...at least it's easy to grep all the TCs as you did and see what the valid tags are.  and see which TCs don't conform and fix them.

**Comment by stevekuznetsov** [comment]
We should also mandate that the name includes the directory it's in, so for instance the LDAP tests should have `authentication` as a tag.

**Comment by mfojtik** [comment]
authentication is a separate script like core

**Comment by bparees** [comment]
Why?

Ben Parees | OpenShift

**Comment by stevekuznetsov** [comment]
@bparees In our specific case, we need to do extensive set-up after the normal set-up to do less work in each test for LDAP. @mfojtik In the *normal* case, though, we'd want to have that directory be the first tag. Even in the `authentication` case all of the non-LDAP authentication extended tests won't be using `authentication.sh`, and we should actually change the name of that startup script to reflect that.

**Comment by bparees** [comment]
@stevekuznetsov that doesn't tell me why you need to mandate the directory be in the tags.  if you have a group of tests you want to frequently run together, they should have a common tag.  that doesn't mean "dir name" needs to be that tag.

also tests that are run from different scripts cannot be run together with this mechanism.  you have to pick the script and then pick the subset(focus) of tests that script would normally run.  (you can pick 2 scripts and a focus for each, but you can't pick 2 scripts, 2 focuses, and expect it all to get executed as a single script with a single openshift server).  So if you have a bunch of tests tagged "authentication" but some are run by core.sh and some are run by authentication.sh, you'd need to tag your PR as [test][extended:core(authentication),authentication]  (assuming you want to run all the tests in authentication.sh an some set of tests in core.sh).  And when those things are run, the openshift server is going to be started twice because core.sh will be run, and then authentication.sh will be run.

**Comment by smarterclayton** [comment]
The dir name should be the same as the primary tag in most cases.  There's
no point to having a directory named "authentication" and not a single
mention of "authentication" in the test name.

**Comment by bparees** [comment]
> The dir name should be the same as the primary tag in most cases.

in most cases, maybe.  needs to be a rule?  no.

**Comment by smarterclayton** [comment]
Yes.

**Comment by stevekuznetsov** [comment]
@bparees That's a good point. I think the original intent of gathering tests into folders was for functional buckets. If we continue to use that as the metric for grouping tests, it would then follow that all of the tests in a directory are in the same functional bucket and it would make sense to run the tests together.

We also very much would like to keep the `authentication.sh` script, however, and only have it apply to some specific tests. Right now that's just tests that require the OpenLDAP container to be runnning. I think a better approach to this problem, however, would be to create a before-test hook for all of these tests that can determine if it needs to run or not. Then it's still possible to ask for any test using `core.sh`. The cluster that's created doesn't get deleted when each test finishes, does it?

**Comment by smarterclayton** [comment]
Not that it has to be a rule.  Just that it has to clearly indicate the
things in it (the script has to be named the same as the dir, the tests in
the dir have to match the things we do, etc).

**Comment by mfojtik** [comment]
@smarterclayton @stevekuznetsov to summarize this (i'm going to open PR with initial tagging/renaming):

* Every test case should have the tag that matches the directory the test is located (./build -> [build])
* Additional tag is used when you want to group the test ([images][mysql])
* We should keep the amount of tags in single test description low
* Tests should have "good" descriptions that describes behavior of the tested code

**Comment by stevekuznetsov** [comment]
Good summary.

I still like the idea of having one `hack/test-extended.sh` like we have for every other test, and that script can determine what to call. I think having a common cluster setup in `test/extended/core.sh` and allowing the other tests (like `ldap_groups.sh`) to do a pre-test setup and a post-test teardown would be a good idea so there isn't as much churn on setting up / tearing down the server. This would have the side effect of being able to inspect the call tag in `hack/test-extended.sh` and determine if it's a tag that is meant to be passed to Ginkgo or if the tag means something like 'call `test/extended/ldap_groups.sh`', which might make the tagging that people have to do in a comment on the PR easier?

**Comment by smarterclayton** [comment]
Does this match what upstream is doing with their tags?  They've added a
bunch recently, where possible we should be consistent.  Otherwise,
excellent suggestions.

**Comment by bparees** [comment]
The reason we don't have a single hack/test-extended.sh is because the various extended tests want customized cluster configurations.  Trying to reuse a single cluster but reconfigure it for different test groups sounds painful.

Having a single test-extended.sh that calls all the other extended test scripts, passing through any focus it was given, would be ok, though it means that you're going to start/stop the cluster potentially w/o actually running any tests.

overall i'd like to just fix the tags on our tests for now.

**Comment by smarterclayton** [comment]
yeah, let's not refactor extended until we get it fixed to run in less than
an hour and split appropriately.

**Comment by marun** [comment]
Given that test/extended/networking.sh does entirely separate test setup/teardown (uses dind to simulate multinode) from test/extended/core.sh, I'm also not sure how cluster reuse would make sense for networking unless we're talking about a real (not test-managed) cluster.  I can see how a single entrypoint could be valuable though.
