### ISSUE TITLE
Options of binaries are handled via cobra repository which does not normalize options and thus deviates from the current k8s upsteam way

### ISSUE THREAD

**Issue by ingvagabund** [openshift/origin#4990]
All underscores in all options of k8s binaries were replaced with dashes. Origin is in sync with the change. However, there is a difference in definition and handling.

Pure k8s import pflag to handle options. All options are normalized (replacement of underscore with dash) before creation and parsing. So both variants (with or without dashes) are supported. 

Openshift uses cobra which does not normalize so only options with dashes are supported. Moreover, glog repository defines --log_dir option which when normalized is used in --log-dir form.

So when running k8s binaries built from o4n tree, --log-dir and all other options in underscore form are not recognized. Since the change is from Apr 24 2015, users with older version of kubernetes are still using the old form of options. This definitely breaks update path for new builds of k8s.

**Comment by ingvagabund** [comment]
@sdodson

**Comment by ingvagabund** [comment]
https://github.com/spf13/cobra/issues/165

**Comment by ingvagabund** [comment]
Fixed via https://github.com/ingvagabund/origin/commit/503b760e7d517ec1de61dc063238be338c78663e

**Comment by smarterclayton** [comment]
Is there a PR?

**Comment by smarterclayton** [comment]
Is it #5111?

**Comment by ingvagabund** [comment]
Yes, it is. This issue fixed.
