### ISSUE TITLE
Pods page requests pod in wrong namespace after switching projects

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4995]
I see this after viewing a pod in one project, switching project in using the dropdown, and navigating back to the pods page. After refreshing, the pod loads.

<img width="1430" alt="screen_shot_2015-10-07_at_12_56_11_pm" src="https://cloud.githubusercontent.com/assets/1167259/10344734/f54ee0d0-6cf2-11e5-9ca3-bad96dadf0ab.png">

/cc @jwforres

**Comment by jwforres** [comment]
Bugzilla duplicate for ref https://bugzilla.redhat.com/show_bug.cgi?id=1271989

**Comment by jwforres** [comment]
Closing since we have the bugzilla to track this
