### ISSUE TITLE
Dry-run reconcile-cluster-roles/reconcile-cluster-role-bindings in diagnostics

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4998]
Running these commands without `--confirm` allows you to see whether there are potentially missing roles or bindings. It could be helpful to surface that in diagnostics.

**Comment by deads2k** [comment]
> Running these commands without --confirm allows you to see whether there are potentially missing roles or bindings. It could be helpful to surface that in diagnostics.

I already added one for `ClusterRoles` a while back.

**Comment by deads2k** [comment]
@liggitt I think this is done.
