### ISSUE TITLE
Print etcd bundle version in openshift version

### ISSUE THREAD

**Issue by mmahut** [openshift/origin#5003]
Make sure we can print out etcd bundled version (or any other bundled software) in "openshift version".

**Comment by mfojtik** [comment]
have fix for this

**Comment by mfojtik** [comment]
@mmahut :christmas_tree:

**Comment by mmahut** [comment]
:santa:

**Comment by kargakis** [comment]
:beer:

**Comment by mmahut** [comment]
Issue is still open, as now we would like it to make more sysadmin-friendly. So, at least printing etcd and version number on one line.

**Comment by kargakis** [comment]
@mfojtik @smarterclayton maybe we could do something similar to what @liggitt is doing for Kerberos? https://github.com/liggitt/origin/blob/23b6abc6ef8cec44791c2dfd9d03932889023f85/pkg/version/version.go#L65-L71

**Comment by smarterclayton** [comment]
Version being displayed for the Openshift binary is fine.  Just not in oc,
and oadm is questionable.

On Oct 11, 2015, at 8:18 AM, Michail Kargakis <notifications@github.com>
wrote:

@mfojtik <https://github.com/mfojtik> @smarterclayton
<https://github.com/smarterclayton> maybe we could do something similar to
what @liggitt <https://github.com/liggitt> is doing for Kerberos?
https://github.com/liggitt/origin/blob/23b6abc6ef8cec44791c2dfd9d03932889023f85/pkg/version/version.go#L65-L71

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5003#issuecomment-147186914>.

**Comment by liggitt** [comment]
FYI, that was mostly for my own debugging so I could tell which impl was being included, but I probably would include that conditionally for `oc`

**Comment by mfojtik** [comment]
@mmahut this is now fixed in origin, you can close this issue.

**Comment by kargakis** [comment]
> @mmahut this is now fixed in origin, you can close this issue.

It would be closed automatically, if the PR (https://github.com/openshift/origin/pull/5118) was indeed merged:)
