### ISSUE TITLE
oc new-app kubernetes/guestbook fails

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#5004]
`oc new-app kubernetes/guestbook` fails with:
```
$ oc new-app kubernetes/guestbook
error: no image or template matched "kubernetes/guestbook", specify --allow-missing-images to use this image name.
```
After adding `--allow-missing-images` I got:
```
$ oc new-app --allow-missing-images kubernetes/guestbook
I1008 14:58:10.775163    5383 newapp.go:388] Image "kubernetes/guestbook" is a builder, so a repository will be expected unless you also specify --strategy=docker
W1008 14:58:10.775250    5383 pipeline.go:246] A service will not be generated for DeploymentConfig "guestbook" because no exposed ports were detected. Use 'oc expose dc "guestbook" --port=[port]' to create a service.
deploymentconfigs/guestbook
Run 'oc status' to view your app.
```
But after downloading the image with `docker pull` it worked smoothly without any problems. 

Additionally when using release 1.0.6 binary to do above against OSE 3.0.1 we fail with the first message as well. 

Maybe we should either provide so=me incompatible client versions warning.

@csrwng @marekjelen @bparees

**Comment by csrwng** [comment]
If you run new-app with --loglevel=8, it looks like the dockerhub registry returns a 404 when trying to get https://registry-1.docker.io/v2/kubernetes/guestbook/manifests/latest. @ncdc should we be falling back to the v1 api ?

**Comment by ncdc** [comment]
@csrwng could you please paste the output from log level 8?

**Comment by csrwng** [comment]
http://paste.fedoraproject.org/276421/44314481/

**Comment by ncdc** [comment]
@smarterclayton you had indicated in an email thread that you didn't want to fall back to v1 if the image doesn't exist in the v2 part of the Hub.... thoughts on this issue?

**Comment by smarterclayton** [comment]
I didn't.  I asked upstream to repush this image

On Oct 8, 2015, at 10:38 AM, Andy Goldstein <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> you had indicated in an
email thread that you didn't want to fall back to v1 if the image doesn't
exist in the v2 part of the Hub.... thoughts on this issue?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5004#issuecomment-146565864>.

**Comment by ncdc** [comment]
@smarterclayton so once the image has been repushed, close this issue?

**Comment by soltysh** [comment]
That only partially will resolve the issue. With above we're giving
terrible developer experience,  because you see the image in the repo when
searching through web UI but then `oc new-app` tells you it's not there.
Which sounds as if `oc` is broken, imho. If we don't want to reach to the
old part we should at least communicate that to a user or better provide a
fallback solution, eg. do `docker pull` first and then call `oc new-app`.
Or provide a fallback flag to use that old v1 api, which we don't want to
support but I don't get why @smarterclayton

**Comment by smarterclayton** [comment]
The right answer is to tell the user the latest tag doesn't exist and
suggest other tags.  We aren't going to patch the client to emulate
non-deterministic behavior just for the DockerHub.  There are lots of
reasons the DockerHub may get broken, I don't want there to be a precedent
that we design and support fallbacks that may in the future be incorrect
behavior, or cause other conflicts.

We already have code today to deal with the difference between a user
asking for bar/foo and bar/foo:latest - the former should indicate that
latest does not exist, but that multiple other matches are possible.
That's the right user friendly behavior.

On Oct 8, 2015, at 12:05 PM, Maciej Szulik <notifications@github.com> wrote:

That only partially will resolve the issue. With above we're giving
terrible developer experience, because you see the image in the repo when
searching through web UI but then `oc new-app` tells you it's not there.
Which sounds as if `oc` is broken, imho. If we don't want to reach to the
old part we should at least communicate that to a user or better provide a
fallback solution, eg. do `docker pull` first and then call `oc new-app`.
Or provide a fallback flag to use that old v1 api, which we don't want to
support but I don't get why @smarterclayton
On Oct 8, 2015 5:54 PM, "Andy Goldstein" <notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton> so once the image has
> been repushed, close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/5004#issuecomment-146587256>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5004#issuecomment-146593810>.

**Comment by ncdc** [comment]
I don't believe it's a question of whether or not you ask for bar/foo vs bar/foo:latest. In this case there is no v2 image data for the entire image repo. I looked at our dockerregistry client code, and as best I could tell, we don't do any fallback. So if you ask for bar/foo or bar/foo:latest, both will fail when talking v2.

**Comment by ncdc** [comment]
And there is no list of alternative tags we could present to the user:

```
$ curl -v -H "Authorization: Bearer $token" https://registry-1.docker.io/v2/kubernetes/guestbook/tags/list*   Trying 52.5.5.190...
* Connected to registry-1.docker.io (52.5.5.190) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.docker.io
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET /v2/kubernetes/guestbook/tags/list HTTP/1.1
> Host: registry-1.docker.io
> User-Agent: curl/7.43.0
> Accept: */*
> Authorization: Bearer [redacted]
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< Date: Thu, 08 Oct 2015 15:45:26 GMT
< Content-Length: 44
< Strict-Transport-Security: max-age=31536000
<
{"name":"kubernetes/guestbook","tags":null}
* Connection #0 to host registry-1.docker.io left intact
```

**Comment by smarterclayton** [comment]
That's not the case for other repositories, which at least have some.  For
those that have none, the null itself seems to imply something we can hang
a message off of.  You can also add a message that indicates the docker v2
hub may not have accurate data.  A v1 fallback prevents us from doing pull
by id, so I'd rather make people aware the hub is broken and how they can
fix it (possibly by allowing a cli user to bypass v2)

How long is this a relevant problem to end users?

On Oct 8, 2015, at 1:14 PM, Andy Goldstein <notifications@github.com> wrote:

And there is no list of alternative tags we could present to the user:

$ curl -v -H "Authorization: Bearer $token"
https://registry-1.docker.io/v2/kubernetes/guestbook/tags/list*
Trying 52.5.5.190...
* Connected to registry-1.docker.io (52.5.5.190) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.docker.io
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET /v2/kubernetes/guestbook/tags/list HTTP/1.1
> Host: registry-1.docker.io
> User-Agent: curl/7.43.0
> Accept: */*
> Authorization: Bearer [redacted]
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< Date: Thu, 08 Oct 2015 15:45:26 GMT
< Content-Length: 44
< Strict-Transport-Security: max-age=31536000
<
{"name":"kubernetes/guestbook","tags":null}
* Connection #0 to host registry-1.docker.io left intact

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5004#issuecomment-146627609>.

**Comment by ncdc** [comment]
It's a relevant problem as long as the Docker daemon still supports v1, right?

**Comment by soltysh** [comment]
The tag is not a problem there, that was the first thing I've checked if the latest tag is there and it was there! Imho, it's unacceptable we provide a user with totally wrong information about non-existent image when he sees one looking into the repo from web browser. On the other side stating we are expecting v2 image and the image requested is cannot be found v2 repo part of docker hub is somehow better than stating there's no such image at all.

**Comment by smarterclayton** [comment]
As long as people are pulling images that were last pushed during the
period of time where this was a problem.

On Oct 8, 2015, at 1:49 PM, Andy Goldstein <notifications@github.com> wrote:

It's a relevant problem as long as the Docker daemon still supports v1,
right?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5004#issuecomment-146636278>.

**Comment by ncdc** [comment]
It's a problem as long as the Hub still supports v1, and you're trying to access an image that was only ever pushed with v1, prior to Docker 1.6.

**Comment by soltysh** [comment]
Which means it will be a problem, at least for a while, that's why giving at least some piece of information would be beneficial.

**Comment by smarterclayton** [comment]
It's primarily a problem for consumers of stale (non automated build)
DockerHub images.  I can't imagine many of those.

On Oct 8, 2015, at 2:02 PM, Andy Goldstein <notifications@github.com> wrote:

It's a problem as long as the Hub still supports v1, and you're trying to
access an image that was only ever pushed with v1, prior to Docker 1.6.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5004#issuecomment-146639320>.

**Comment by soltysh** [comment]
I'll be playing the stubborn here, still we wanna be nice to them and at least inform them about the image being old and not supported, which will be better than returning not found.

**Comment by smarterclayton** [comment]
I'm not opposed to communicating what's going on, and we probably need the
escape hatch to v1 (not sure I want to add a flag for this everywhere, I
was checking whether there is a DockerHub domain name that doesn't expose
v2 but does expose v1).  But it has to be explicit to ignore what the repo
tells you.

On Oct 8, 2015, at 3:04 PM, Maciej Szulik <notifications@github.com> wrote:

I'll be playing the stubborn here, still we wanna be nice to them and at
least inform them about the image being old and not supported, which will
be better than returning not found.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5004#issuecomment-146656315>.

**Comment by soltysh** [comment]
:+1: I'll try to prepare a PR after I'm done with current sprint assignments.

**Comment by smarterclayton** [comment]
Fixed
