### ISSUE TITLE
Using two identityProviders with the same user creates duplicates.

### ISSUE THREAD

**Issue by readonly** [openshift/origin#5009]
OpenShift 1.0.6 / RHEL 7.1:

I have configured 2 `identityProviders` in the master's /master-config.yaml: first one ist htpasswd, second one is LDAP. For users that use those mutually exclusive, both work fine.

Now I have a user (`joe`, a project admin) that should be able to usually login via LDAP, but if the LDAP is down, should be able to login via htpasswd as fallback. Therefore he has 2 different passwords on htpasswd and on LDAP (in production the htpasswd-password would be a random string, handed out only on this rare occasion). However, if that user actually logs in the first time via the htpasswd-password, the login succeeds but the user is cloned as `joe2`. This new user now has no roles and is useless. Since `oc get users` has a column `IDENTITIES` (plural), I would have assumed that the same user can have different ones at the same time. The htpasswd was set via:

```
echo youllneverguess | htpasswd -i /etc/origin/origin-passwd joe
```

Is this a bug or are we misusing this mechanism?

**Comment by liggitt** [comment]
That is working as intended today. Identity providers are not expected to overlap usernames, and if they do, the second one in gets a unique username. 

https://trello.com/c/cSa9BKUL is open to allow choosing the behavior when multiple providers identify the same users. 

In the meantime, you can update an existing identity->user mapping yourself using the "update useridentitymapping" API to make the identities from both providers map to the same user.

**Comment by readonly** [comment]
Good enough, as we need that only as fallback for admins. Thanks.
