### ISSUE TITLE
The kubectl describe is missing describers for all Origin objects

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#501]

**Comment by ironcladlou** [comment]
This issue looks similar to https://github.com/openshift/origin/issues/517 and I think we have basic describers for all resources now, correct?

**Comment by smarterclayton** [comment]
Status of this issue?

**Comment by danmcp** [comment]
Closing due to age without prejudice.

**Comment by smarterclayton** [comment]
Fixed, we have describers

**Comment by liggitt** [comment]
am I the only one that found it ironic that this issue has <i>No description provided.</i>

**Comment by smarterclayton** [comment]
In an Alanis Morissette kind of way, yes.

**Comment by derekwaynecarr** [comment]
Leaving a comment to subscribe and check what describe project outputs tomorrow.

**Comment by smarterclayton** [comment]
Should probably complement status and the project settings page?

**Comment by derekwaynecarr** [comment]
Agreed.  Will hack something up tomorrow.
