### ISSUE TITLE
Authentication extended tests don't use core.sh

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#5013]
Authentication extended tests currently use `test/extended/authentication.sh` for set-up, but this makes it so that one cannot choose to run an arbitrary test from one starting point and, if more authentication tests are added that do not require that set-up, one would fail to run all authentication tests as they require different set-ups. We need to move that set-up into the `ginkgo` `BeforeEach` hook and guard the set-up work with a sanity check so we don't re-setup when we don't need to, *a la* Kube's e2e.

**Comment by deads2k** [comment]
@stevekuznetsov This is no longer needed.  Please close.

**Comment by stevekuznetsov** [comment]
I'd feel better if we had a unified way of creating and running extended tests, still.

**Comment by deads2k** [comment]
See https://github.com/openshift/origin/pull/5635
