### ISSUE TITLE
Runtime error on overview

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5020]
I believe this happens when replication controllers load before deployment configs.

/cc @jwforres 

```
Uncaught TypeError: Cannot read property 'hawkular-cassandra-1' of undefined
(anonymous function) @ overview.js:495
forEach @ angular.js:331
updateTopology @ overview.js:491
```

![screen shot 2015-10-08 at 4 56 17 pm](https://cloud.githubusercontent.com/assets/1167259/10379723/e3af6818-6ddd-11e5-8e01-8acfffdd5ecd.png)

**Comment by jwforres** [comment]
@stefwalter the stacktrace looks like its coming from updateTopology
