### ISSUE TITLE
Show warning if metrics and logging options aren't configured

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5038]
See https://github.com/openshift/origin/pull/4954#issuecomment-145885960

/cc @deads2k

**Comment by spadgett** [comment]
@deads2k Is your offer to take this one still good? :)

**Comment by deads2k** [comment]
> @deads2k Is your offer to take this one still good? :)

Yes, just haven't worked my way down to p2's yet.

**Comment by spadgett** [comment]
> Yes, just haven't worked my way down to p2's yet.

That doesn't sound good....
