### ISSUE TITLE
Web UI over view should have a link to build page to easily cancel, restart, view logs

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#5039]
The improvements from 3.0.1 to 3.0.2, saved me so many navigation clicks and steps since it allowed direct link to the build from the Overview page and ability to cancel it.

In the latest with origin it removed this shortcut, now I'm having to stumble around the Browse->build config->history/build and build pages to try to find the build, to do actions like the above.

I strongly recommend bringing the link back, as it made it so easy to jump into the build resources to work with them which is a very common case when initially bringing an application into OpenShift and also trying to troubleshoot existing apps with new build problems.

/cc @spadgett @jwforres

**Comment by jwforres** [comment]
@sspeiche I didn't think the running / cancelled / failed build that shows up underneath the service ever had a link in the message, the link to the build that was added was only in the pod template for a successful deployment.  But either way yes it is on the list to add a lot more links from the overview now that resources have their own pages.  I will link this issue into the story that is covering that.
