### ISSUE TITLE
oc new-app should specify the port in the route that is created

### ISSUE THREAD

**Issue by bparees** [openshift/origin#5040]
a route with no port will round robin across all ports in the service which is basically unexpected behavior.

new-app creates services with just one port but if another port is added to the service later, the route will start RRing across them and probably break.  

instead we need to explicitly define the port in the route, just like we do in the service.

**Comment by bparees** [comment]
@smarterclayton @csrwng fyi.

**Comment by csrwng** [comment]
@bparees new-app creates a service with multiple ports. But it doesn't create a route. If you can specify in the route which port you want to expose, I would say it doesn't have anything to do with new-app, but rather the expose command you use to create the route.

**Comment by bparees** [comment]
@csrwng the service it creates contains all the ports the image exposes, not just one of them?

**Comment by csrwng** [comment]
Yes, since https://github.com/openshift/origin/pull/3378

**Comment by bparees** [comment]
ok i guess i'm inclined to close this.  @smarterclayton any concerns?

**Comment by smarterclayton** [comment]
I think the current problem was the UI didn't expose all the ports now.

**Comment by smarterclayton** [comment]
And now expose needs to set RoutePort - @kargakis

**Comment by bparees** [comment]
closing.  sounds like we need a new issue for oc expose.
