### ISSUE TITLE
Node stats auth is too restrictive

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#5041]
Heapster gets metrics via `POST` to kubelet `/stats` endpoint. This requires `cluster-admin` role currently - can we change this to `cluster-reader` role as this is what we want to use metrics collection?

/cc @liggitt @mwringe @jcantrill

**Comment by liggitt** [comment]
that's an unfortunate semantic. you can add this to the cluster-reader role for your testing while I think how to handle that:
```
$ oc edit clusterrole cluster-reader
...

- resources:
  - nodes/stats
  verbs:
  - 'create'
```

**Comment by liggitt** [comment]
possible ways to handle this:
1. in policy (by allowing cluster-reader and node-reader to "get" and "create" on nodes/stats)
2. in kubelet authorization attributes builder (by assigning the "get" verb to all requests under /stats, even POSTs)

@deads2k, preference? I lean toward the first

**Comment by mwringe** [comment]
Ok, if I make that change for the role, I can now get metrics using cluster-reader instead of requiring cluster-admin

**Comment by liggitt** [comment]
the linked PR will update `cluster-reader` and `system:node-reader` roles to have that permission
