### ISSUE TITLE
Deployments page doesn't show replicas during rolling deployment

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5055]
1. Create an app (`oc new-app ...`)
2. Scale it to 5
3. Go to the deployments page (the current deployment is shown as "Running, 5 replicas")
4. Start a new deployment

You can see the new deployment start, and the replicas from the old deployment start to decrease, but you don't see a replica count for the new deployment until it has finished deploying and is in the running state.

It would be easier to see the rolling nature of the deployment if you saw replicas increasing during the deployment

**Comment by jwforres** [comment]
Fixing it with some other deployment changes I was making in #5016
