### ISSUE TITLE
System.getenv().get("HOSTNAME") doesn't contain pod hostname

### ISSUE THREAD

**Issue by myfear** [openshift/origin#5065]
I was under the impression,that the environment variable "HOSTNAME" contains the pod name. In fact,it contains something like this : swarm-sample-1-7mmd7 which looks more like the DC.

How can I find out about the pod name and isn't the above mentioned assumption correct?

**Comment by liggitt** [comment]
that actually looks like a pod name...
dc is probably `swarm-sample`
deployment number 1 is the rc `swarm-sample-1`
a pod created from that rc is `swarm-sample-1-7mmd7`

the container hostname is set to the first 63 chars of the pod name: https://github.com/kubernetes/kubernetes/blob/8e25b7c7bf616f688daa688a62f12ba3a675914b/pkg/kubelet/dockertools/manager.go#L671-L677

**Comment by myfear** [comment]
Got it. Thanks, sorry.
