### ISSUE TITLE
Post rebase issues

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#5068]
While working on the current rebase #5049 I found following issues:
* [ ] ~~upgrade `github.com/Sirupsen/logrus` in k8s to match origin version~~
* [ ] ~~upgrade `github.com/miekg/dns` in k8s to match origin version~~
* [ ] upgrade docs to mention `godep save -t` (this will preserve test files)
* [x] upgrade docs to mention having separate bump commits for shared libraries

**Comment by kargakis** [comment]
* start using `oc edit` from upstream
* cherry-pick flake fixes in upstream tests

**Comment by soltysh** [comment]
https://github.com/kubernetes/kubernetes/pull/12221 merged @mfojtik pretty please, make it happen

**Comment by mfojtik** [comment]
@soltysh on my todo list for today

**Comment by soltysh** [comment]
Fix problems that appeared in https://github.com/openshift/origin/issues/5068

**Comment by soltysh** [comment]
This is done, the k8s issues is moved to other upstream PR I'm taking care. Closing.
