### ISSUE TITLE
`BuildLogOptions` drifting from `PodLogOptions`

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5070]
`PodLogOptions` has more and better options than `BuildLogOptions`.  See https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1614.

I'd like to embed `PodLogOptions` into `BuildLogOptions` for congruence that will stay up to date with rebases as we simply copy fields through.  The alternative is to create a reflective unit test that requires matching fields so that we don't keep slipping.

@bparees @kargakis @csrwng

**Comment by kargakis** [comment]
> I'd like to embed PodLogOptions into BuildLogOptions

I was thinking about this yesterday. +1

**Comment by kargakis** [comment]
We need this for `DeploymentLogOptions` too

@deads2k this is the issue that needs to be fixed for your bugs in bugzilla

**Comment by kargakis** [comment]
oc logs pod --timestamps --tail 2 works fine

**Comment by kargakis** [comment]
> oc logs pod --timestamps --tail 2 works fine

Actually it works fine with https://github.com/openshift/origin/pull/5233. Not sure about master

**Comment by kargakis** [comment]
> Be sure to keep `Follow` backwards compatible.

@deads2k if we embed PodLogOptions, is there any problem?

**Comment by kargakis** [comment]
> @deads2k if we embed PodLogOptions and remove our own Follow field, is there any problem?

Hmmm, I think we are going to break `start-build -f` on older clients if we do this...

**Comment by deads2k** [comment]
> Hmmm, I think we are going to break start-build -f on older clients if we do this...

I don't think so if the deserialization can still interpret the old fields.  I think that 
```go
type BuildLogOptions struct{
    PodLogOptions // ick
    NoWait bool
}
```

Old clients will still put `follow` in the correct location in query params.

**Comment by kargakis** [comment]
Actually you are right, inlining PodLogOptions will preserve follow

**Comment by kargakis** [comment]
@deads2k this needs to be reprioritized
