### ISSUE TITLE
Jenkins jobs hanging after build

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5096]
Example:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/5705/console

Got to this step and waited an hour:
```
++ Creating openshift-origin-image-v1.0.6-537-g8a966ed-8a966ed-linux-amd64.tar.gz
hack/build-cross.sh took 334 seconds
```

**Comment by liggitt** [comment]
@danmcp

**Comment by liggitt** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/5706/console

**Comment by vbatts** [comment]
none of these links work. What are we looking at here?

**Comment by danmcp** [comment]
@vbatts They have rolled out of history.  You can recreate by running make on origin and it hangs sometimes.  It happens on people's laptops and on aws.  Probably 1 in ~30 on aws.

**Comment by vbatts** [comment]
alrighty.
I'm running through that now, and haven't seen it yet.

looping with
```bash
for i in {0..40}; do
  rm -rf _output/ Godeps/_workspace/pkg/
  echo TRY $i
  make GOFLAGS=-v
done
```

**Comment by vbatts** [comment]
I left this loop running over the weekend and did not hit a hang a single time.
My build is using `go version go1.5.1 linux/amd64`, would that make the difference?
I'll try go1.4.3.

**Comment by vbatts** [comment]
not seeing a hang with go1.4.3 either, though the build times are so much nicer. 
go1.5.1 `make` ~ 244 seconds
go1.4.3 `make` ~ 78 seconds

can I close this issue until it is an issue again?

**Comment by deads2k** [comment]
@liggitt have you seen this recently?  I'm inclined to close

**Comment by liggitt** [comment]
not recently, no

**Comment by deads2k** [comment]
closing due to age.
