### ISSUE TITLE
Can we remove Adobe Flash from web console?

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5115]
Since the flash is disabled by default in most newer browsers, it is ugly to go enable it for OpenShift console (it shows ugly button to do so). 

There is solution purely written in Javascript: http://zenorocha.github.io/clipboard.js

@jwforres @spadgett FYI

**Comment by liggitt** [comment]
> Since the flash is disabled by default in most newer browsers

citation needed

**Comment by mfojtik** [comment]
@liggitt at least my chrome has it disabled by default :-) (chrome-beta)

**Comment by mfojtik** [comment]
http://www.pcworld.com/article/2948115/browsers/mozilla-firefox-temporarily-blocks-flash-by-default.html
http://thenextweb.com/insider/2015/07/14/firefox-rings-the-death-knell-for-flash

**Comment by soltysh** [comment]
I have flash disabled by default everywhere (iow. FlashBlock plugin for Firefox), so I'm seeing play button in places where flash is used. I'd love to see us get rid of flash entirely as well.

**Comment by jwforres** [comment]
The JS only option referenced does not support Safari.  We could consider moving to the JS only option for other browsers, but would still have to fall back to flash for Safari.

**Comment by jwforres** [comment]
@liggitt i think the difference is not installed vs installed and disabled.

**Comment by jwforres** [comment]
Even if we decide not to include the JS plugin, we should fix it so you do not see the ugly play button when you have flash disabled, it should be have like when flash is uninstalled.

We don't want to see this:
![flash_disabled](https://cloud.githubusercontent.com/assets/1467629/10483774/1ea01bd2-724f-11e5-8ec3-8ce3abcdf1b5.png)

**Comment by zenorocha** [comment]
+1 for clipboard.js ;)

**Comment by kargakis** [comment]
> Can we remove Adobe Flash from web console?

yes, please

**Comment by jwforres** [comment]
zeroclipboard is actively working on using the HTML5 api by default and falling back to flash https://github.com/zeroclipboard/zeroclipboard/issues/171   so lets just pick up the new version of zeroclipboard once that's in so that we keep Safari support and so that we hopefully don't have to make a bunch of changes on our side.

**Comment by spadgett** [comment]
![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/11937355/ec3bf242-a7e1-11e5-9a12-63274e161e17.png)

**Comment by jwforres** [comment]
zeroclipboard has made no progress on their html5 support, we are going to switch to clipboard.js, both bootstrap 4 and patternfly are using it on their websites, we will just use the recommended fallback behavior for safari

**Comment by zenorocha** [comment]
:tada:
