### ISSUE TITLE
Reenable liveness probe in registry deployment config

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#5116]
Now that we're no longer trying to support the v1 registry, we should be able to reenable the liveness probe that `oadm registry` adds to the registry's DC:

https://github.com/openshift/origin/blob/3dd75654ae2cd6d4f762da95395d02ed496778a2/pkg/cmd/admin/registry/registry.go#L253-L265

@smarterclayton @mfojtik @miminar @pweil-

**Comment by pweil-** [comment]
:+1:

**Comment by ncdc** [comment]
I believe the upstream registry has updated their code so `GET /` should return a 200 instead of a 404. I'm not sure if that's in 2.0.1 (which we're based on) or 2.1.x. We should eventually be able to deprecate and remove our custom `/healthz` handler, but not right now.

**Comment by mfojtik** [comment]
+1

**Comment by miminar** [comment]
Blocked on #4339.

**Comment by miminar** [comment]
Resolved by #5404.

`GET /` is used now being used in liveness probe.

**Comment by miminar** [comment]
@pweil- please close this. #5404 got merged.
