### ISSUE TITLE
Filter events per object

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#5132]
I was going eariler today why my build failed in the web console, but since we don't have build logs yet I figured out I'll check event. Unfortunately we only present the entire list of events, sorted by time, but if you're interested in particular build, like I did, that was too much. I'd suggest adding per object filtering to that list. This could be achieved using field selector, similarly to how `Search` method is implemented in k8s `pkg/client/unversioned/events.go`.

@jwforres would that be feasible to add that?

**Comment by jwforres** [comment]
We plan on adding the events relevant to an item to the page for that
item.  So you would go to the build and could see its events.  Build logs
will definitely be in before that though.

For the events page, we will probably  eventually let you sort that table
by kind or resource name.

**Comment by soltysh** [comment]
That'll be perfect!

**Comment by jwforres** [comment]
closing since this is in trello https://trello.com/c/DRFgGKxF
