### ISSUE TITLE
Field selector logging in request.go was reintroduced during a refactor

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5133]
We had an upstream carry that hides the printout in client.Request when a non recognized field name is found, but it apparently was dropped (or upstream changed) to start showing again:

```
W1014 23:13:00.341564   32542 request.go:316] field selector: v1 - builds - name - centos-1: need to check if this is versioned correctly.
```

Code needs to be fixed (good) or message needs to be removed.

@csrwng @deads2k

**Comment by liggitt** [comment]
Related bug on my list to fix is that we don't register field selector conversions to many of our types: https://bugzilla.redhat.com/show_bug.cgi?id=1269256

**Comment by deads2k** [comment]
@smarterclayton can you give an example command to trigger this?

**Comment by smarterclayton** [comment]
It used to be describe of a resource in Origin - Jordan may have fixed this
though.

**Comment by smarterclayton** [comment]
We just fixed this again
