### ISSUE TITLE
openshift-sdn-ovs fails in newer origin

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#5152]
This is likely an openshift-sdn issue but i'm working from what's in origin code base so i'm filing it here.

Between 98b3c2967831a3a336cfc18c8eac055ea817e10a and e2170d962edd2bd285ecb05f1cef4fcfd9714f48 I'm unable to ping pod ips across the SDN. I've run the debug.sh and collected both a working and failing output. The only thing I've noticed is that there's a diff in the pod's routing tables, though there may be other issues my untrained eye has missed.

```
$ diff -u openshift-sdn-debug-works/nodes/ose3-master.example.com/pods/docker-registry-1-6jk36/routes openshift
-sdn-debug-fail/nodes/ose3-master.example.com/pods/docker-registry-1-6jk36/routes                                                      
--- openshift-sdn-debug-works/nodes/ose3-master.example.com/pods/docker-registry-1-6jk36/routes 2015-10-15 20:33:15.000000000 -0400
+++ openshift-sdn-debug-fail/nodes/ose3-master.example.com/pods/docker-registry-1-6jk36/routes  2015-10-15 17:05:41.000000000 -0400
@@ -1,5 +1,4 @@
-> nsenter -n -t 2786 ip route show
+> nsenter -n -t 2760 ip route show
 
 default via 10.1.1.1 dev eth0 
-10.1.0.0/16 dev eth0  proto kernel  scope link  src 10.1.1.2 
 10.1.1.0/24 dev eth0  proto kernel  scope link  src 10.1.1.2 
```

You can download both the failing and working output of openshift-sdn/hack/debug.sh from http://sdodson.fedorapeople.org/openshift-sdn-debug.tar.gz I've used meld to look for differences between the two.

CC: @danwinship @pravisankar since i've discussed the issue with both of you

**Comment by danwinship** [comment]
Thanks for the diff. That made it pretty easy to figure out where the bug had to be.

**Comment by pravisankar** [comment]
Fixed in https://github.com/openshift/openshift-sdn/pull/183
