### ISSUE TITLE
TestTriggers flake

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5161]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3645/console
--- FAIL: TestTriggers_imageChange-2 (5.89s)
	deploy_trigger_test.go:165: Waiting for image stream mapping to be reflected in the IS status...
	deploy_trigger_test.go:175: Still waiting for latest tag status on ImageStream test-image-stream
	deploy_trigger_test.go:172: ImageStream test-image-stream now has Status with tags: map[string]api.TagEventList{"latest":api.TagEventList{Items:[]api.TagEvent{api.TagEvent{Created:util.Time{Time:time.Time{sec:63580568103, nsec:0, loc:(*time.Location)(0x42caa60)}}, DockerImageReference:"registry:8080/openshift/test-image@sha256:00000000000000000000000000000001", Image:"sha256:00000000000000000000000000000001"}}}}
	deploy_trigger_test.go:188: Waiting for a new deployment config in response to ImageStream update
	deploy_trigger_test.go:201: expected config version 1, got 0

**Comment by ironcladlou** [comment]
Reproduced, I'll take care of it.

**Comment by ironcladlou** [comment]
My guess is this is fallout from #4941 which now updates the status field of the deploymentConfig. There may be other tests which make similar assumptions; I'll do a quick read to see if I notice anything.
