### ISSUE TITLE
Better output for kubectl describe

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#517]
The `$ openshift kubectl describe <type> <resource_id>` currently produces just basic output, but it should be more verbose and give users meaningful, detailed information about the resource.

This is the current implementation: https://github.com/openshift/origin/blob/master/pkg/cmd/kubectl/describer.go

Since you have access to the resource client interface, you can combine output from multiple resources together (for example, Deployment can display the ReplicationController details).
Adding new fields there is trivial, so I'm asking you, if you are a component/resource owner, please review the `Describer` for the resource you know and tell me (or make a PR ;-) if there is anything missing.

@ncdc @ironcladlou @csrwng @jwforres @smarterclayton @bparees

**Comment by ironcladlou** [comment]
I've been revamping the DeploymentConfig describer as part of the rollback CLI work for https://github.com/openshift/origin/pull/786. I plan to take it even further after this basic support is done. I'd be interested in comparing notes/ideas for other resources.

**Comment by danmcp** [comment]
Closing due to age without prejudice.

**Comment by smarterclayton** [comment]
@fabianofranz owns the remaining describer cleanup
