### ISSUE TITLE
Labels cut off at certain screen widths

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5181]
I'm not sure if this is intentional, but I'd prefer it to wrap if needed.

<img width="577" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/10564710/84c5c814-758b-11e5-9f5f-ce6c47ea2f3d.png">

/cc @jwforres

**Comment by liggitt** [comment]
That namespaced label is super long. @smarterclayton , I thought we had said long ago labels weren't namespaced

**Comment by smarterclayton** [comment]
They are now.  You mean whether we hide them visually?

On Oct 18, 2015, at 1:59 PM, Jordan Liggitt <notifications@github.com>
wrote:

That namespaced label is super long. @smarterclayton
<https://github.com/smarterclayton> , I thought we had said long ago labels
weren't namespaced

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5181#issuecomment-149035401>.

**Comment by jwforres** [comment]
I found this on Friday. I have a fix in my branch where I am working on the
table expansion. May just go ahead and get that fix in.

**Comment by jwforres** [comment]
#5201 allows wrapping between labels, @sg00dwin is going to look at truncating the key/value of a label as needed when we get down to the smallest mobile widths
