### ISSUE TITLE
oc edit should include godoc for fields

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5183]
`oc edit` could include godoc for each field displayed one a line that starts with `//` or some other value that we could easily strip during serialization.  I even know roughly what I need to do, but doing it without docs is just about impossible.

@smarterclayton

**Comment by smarterclayton** [comment]
This is prereqd on the yaml serialization work done by Solly and the
subsequent mapping of the underlying descriptors, but I agree.

On Oct 18, 2015, at 4:13 PM, David Eads <notifications@github.com> wrote:

oc edit could include godoc for each field displayed one a line that starts
with // or some other value that we could easily strip during
serialization. I even know roughly what I need to do, but doing it without
docs is just about impossible.

@smarterclayton <https://github.com/smarterclayton>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5183>.

**Comment by deads2k** [comment]
> This is prereqd on the yaml serialization work done by Solly and the
> subsequent mapping of the underlying descriptors, but I agree.

Is there a pull open for this serializer?  In `oc edit` I want to see doc for fields that are `omitempty` as well.  Otherwise its really hard to find fields like `ref` in the git source object.
