### ISSUE TITLE
oc status should show me average build time and standard deviation.

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5186]
When I'm running a build, sometimes it takes a long time.  I'd like to know how long it normally takes, so average time and a standard deviation would be nice.

@bparees (and a pony)

**Comment by bparees** [comment]
what, no mode or median?

you should setup your builds to be wrappered by a jenkins job, then you can get all that stuff for free :)

**Comment by deads2k** [comment]
> what, no mode or median?

I thought about it, but I decided that standard deviation was better known, better understood, and more useful.

Guess I'll have to watch a demo and see how easy it is wire up through jenkins.

**Comment by spadgett** [comment]
> what, no mode or median?

Is it weird that I kind of want this?

**Comment by bparees** [comment]
> Is it weird that I kind of want this?

also curve-fit+extrapolate to predict future build times?

provide first+second order derivatives of the duration curve?

**Comment by sspeiche** [comment]
I'd like to know trends as well, are builds getting slower? faster?

Predict when builds might fail might be good as well, such as it has been 7 days since last failure be on the look out

**Comment by sspeiche** [comment]
As I'm watching paint dry (long builds running), it would be good to split up the build times too: time request, time until build is running (time until the builder pod is fetched, scheduled and starts actually running), time build actually runs, time it takes to push the image. This would help devs and admins to clearly see where attention may be needed.

@spadgett It would be very handy, esp in Web UI, to show a timeline with different segments scaled to amount of time used and color coded per time of "work" per above. Deploy would have some similar timeline needs as well.

**Comment by bparees** [comment]
Created vs started (pod running) is already there,  though the calculation
isn't. Distinguishing build from push isn't technically possible (in any
reasonable way at least) with the current build implementation.

Ben Parees | OpenShift

**Comment by deads2k** [comment]
> Distinguishing build from push isn't technically possible (in any
> reasonable way at least) with the current build implementation.

Given the current builder, its knowledge of which build it is, the SA credentials it has, and cluster DNS, it possible to write a hook here: https://github.com/openshift/origin/blob/master/pkg/build/builder/docker.go#L93 that updates the `build/status` to indicate steps.  The policy rule wouldn't be hard.

**Comment by deads2k** [comment]
Not that this is a feature I considered while trying to figure out what was happening last Sunday....

**Comment by spadgett** [comment]
Related: #5826, builds trends in the web console

**Comment by bparees** [comment]
the console shows you build trends, i don't see us re-implementing this for the cli.
