### ISSUE TITLE
ServiceSpec validation stops on the first failure

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5187]
When validating a `ServiceSpec`, if you have multiple `ServicePorts` with errors, you only get the first error.  This makes it really annoying when you have bump through them over and over again.

**Comment by pweil-** [comment]
ServiceSpec ports are now iterated and aggregated: https://github.com/openshift/origin/blob/1fd827d38ba7132f22dfa928a7d5e7e7f72734a0/Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/validation.go#L1697-L1700
