### ISSUE TITLE
oc export should strip references to generated token and dockercfg secrets

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5189]
`oc export sa` doesn't remove the token and dockercfg secret references.  In most use-cases, those references won't be valid when the SA is re-created.  I think we should remove them on export and let people use `oc get` if they really want to keep them.

@smarterclayton is there some way to tag a field as "don't export by default"?

**Comment by smarterclayton** [comment]
Not yet but there should, just needs to be piped though swagger.  Would
like to see it get added for sure.

On Oct 18, 2015, at 5:39 PM, David Eads <notifications@github.com> wrote:

oc export sa doesn't remove the token and dockercfg secret references. In
most use-cases, those references won't be valid when the SA is re-created.
I think we should remove them on export and let people use oc get if they
really want to keep them.

@smarterclayton <https://github.com/smarterclayton> is there some way to
tag a field as "don't export by default"?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5189>.

**Comment by deads2k** [comment]
Opened https://trello.com/c/pqGl8CVe/546-api-types-should-be-able-to-express-do-not-export to cover the general problem.  I just extended the existing `!exact` mechanism for this.
