### ISSUE TITLE
builds of type dockerbuild should have locality preference

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5192]
Since docker builds are likely to re-use cached layers, it's a lot nicer to have the docker build prefer the same node that ran it last time.  It saves a lot of time.

@bparees

**Comment by bparees** [comment]
presumably we'd have to store the node the last build ran on, in the buildconfig.

we'd also have to weight this preference, probably with the lowest priority, vs other scheduling constraints/desires.

**Comment by smarterclayton** [comment]
This is prereq'd by custom schedulers and is not a near term item.

**Comment by smarterclayton** [comment]
I believe this is now implemented in the scheduler, although I dont know that we enable the predicate or that it works correctly for digests

**Comment by bparees** [comment]
what exactly has been implemented and what does the build system need to do to take advantage of it?

**Comment by deads2k** [comment]
> what exactly has been implemented and what does the build system need to do to take advantage of it?

The scheduler is now aware of all images that are already pulled on a node, but I didn't think that it understood the layers too and the base image probably isn't selective enough.  Did they add something else?

**Comment by bparees** [comment]
well and it's still going to have no idea about the s2i builder image (eg centos/ruby-22-centos7) we're going to ultimately launch on that node, which is what's really needed for builds to benefit.  It would only know whether openshift/origin-sti-builder is present.  Which is only half the battle.

**Comment by bparees** [comment]
So we'd need some way to annotate the pod with information about additional images we intend to use.  (the builder image, images we're going to use as source inputs, etc)

**Comment by smarterclayton** [comment]
Once we change to using pods to run our builds we would have more image
info available.

**Comment by bparees** [comment]
> Once we change to using pods to run our builds we would have more image info available.

sure, still won't handle the case where we have an add-on image as an input to the build though.  that's probably a less critical case though.

**Comment by smarterclayton** [comment]
It won't help incremental builds either.

**Comment by bparees** [comment]
@smarterclayton is this realistically worth keeping open?

**Comment by smarterclayton** [comment]
Probably not - we're not actively trying to reuse layers in the future (instead, we're trying to avoid layers).
