### ISSUE TITLE
cancel-build should take a buildconfig

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5193]
If I call `oc cancel-build` with a buildconfig that has a single running build, cancel it for me.

@bparees 
@kargakis  I think you're in this code at the moment.

**Comment by bparees** [comment]
No.

Maybe you ran it expecting to see usage information.  Or hit enter
prematurely.

Cancelling is pretty destructive, I don't like the idea of defaulting it.

Ben Parees | OpenShift

**Comment by deads2k** [comment]
So I run `oc start-build bc/foo`, then say "crap, forgot to push my code", then try `oc cancel-build bc/foo`, and I should not get the behavior I expect? That seems kind of crazy.

Not that that ever happened to me.  I'm asking for a friend...

**Comment by bparees** [comment]
1) `oc start-build` reports back the name of the build it created (oddly without any context around the name).  why wouldn't you use it?

2) `oc start-build bc/foo` isn't the syntax to start a build from a buildconfig, `oc start-build foo` is..  so your cancel-build parallel invocation isn't going to be as parallel as you'd like.

**Comment by deads2k** [comment]
The `start-build` input parsing bug will be fixed in https://github.com/openshift/origin/pull/4947, so congruence can easily be achieved.

I didn't use the output of the `oc start-build` command because that came out 12 minute ago in my buffer and is long since gone.

I'm still not seeing why its a bad thing to have congruent commands that behave as expected.  It would also handle the case of "I looked at `oc status` and I see one build running that I want to stop, but all I have is a buildconfig name".  For deployment configs, we said that a DC is what users created and cared about, let them manipulate deployments using the object that expressed their intent as a resource.  Are builds so different that the 90% case requires being familiar with the objects that I didn't create in addition to the one that I did?

**Comment by kargakis** [comment]
It seems valid to support this. `oc deploy config --cancel` will cancel the latest deployment for the given config, I don't see why we shouldn't do the same for buildconfigs.

**Comment by liggitt** [comment]
> Maybe you ran it expecting to see usage information. Or hit enter prematurely. 

The intent behind `cancel-build bc/foo` is pretty unambiguous... if that resolves to a single build, we should honor it, imo

**Comment by mfojtik** [comment]
@kargakis should we then also support this behavior for logs? `oc logs build-config-name` should give me logs from the last build?

**Comment by kargakis** [comment]
> @kargakis should we then also support this behavior for logs? oc logs build-config-name should give me logs from the last build?

`oc logs bc/build-config-name` already does that.

**Comment by mfojtik** [comment]
@kargakis very cool :-)

**Comment by soltysh** [comment]
> It seems valid to support this. oc deploy config --cancel will cancel the latest deployment for the given config, I don't see why we shouldn't do the same for buildconfigs.

With deployments you can have only one deployment active, builds are different, you can have multiple build active and as @liggitt mentioned this command will be ambiguous in that case.

**Comment by deads2k** [comment]
> With deployments you can have only one deployment active, builds are different, you can have multiple build active and as @liggitt mentioned this command will be ambiguous in that case.

That's an uncommon case that can be inspected before completing the call.  We can simply fail the command in that case.

**Comment by kargakis** [comment]
> That's an uncommon case that can be inspected before completing the call. We can simply fail the command in that case.

With something like "multiple builds are running in parallel".

**Comment by kargakis** [comment]
Thinking about it, if I was trying to cancel a bc I would expect to cancel all of its builds... No?

**Comment by soltysh** [comment]
Definitely not.

**Comment by kargakis** [comment]
Fixed by https://github.com/openshift/origin/pull/8509
