### ISSUE TITLE
oc logs needs to expose all arguments from upstream

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5197]
Needs to be functionally compatible.

**Comment by kargakis** [comment]
Being fixed in the rebase: https://github.com/deads2k/origin/commit/36cc605cc32d632dfea6a20a6a014742d636853b

**Comment by deads2k** [comment]
> Needs to be functionally compatible.

I made a test to force rebasers to consider it: https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/logs_test.go#L14.

**Comment by kargakis** [comment]
I am working on having the Kube flags by default in our logs. Unfortunately
the last refactroring we made upstream, doesn't allow this (or at least
doesn't allow it without duplicating the logic of Complete) but with some
changes our logs will be sound.

**Comment by deads2k** [comment]
> I am working on having the Kube flags by default in our logs. Unfortunately
> the last refactroring we made upstream, doesn't allow this (or at least
> doesn't allow it without duplicating the logic of Complete) but with some
> changes our logs will be sound.

Please wait until post-rebase.  I'm hoping to land it today.

**Comment by kargakis** [comment]
As it turns out I need the rebase in to test my changes because vagrant for
Kube is broken on master :/ (
https://github.com/kubernetes/kubernetes/issues/15692)

**Comment by kargakis** [comment]
This is fixed.

**Comment by deads2k** [comment]
> Needs to be functionally compatible.

@smarterclayton any particular concern or does the existing unit test and rebase satisfy?

**Comment by smarterclayton** [comment]
No this is fine.

On Oct 20, 2015, at 7:15 PM, David Eads <notifications@github.com> wrote:

Needs to be functionally compatible.

@smarterclayton <https://github.com/smarterclayton> any particular concern
or does the existing unit test and rebase satisfy?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5197#issuecomment-149728417>.

**Comment by deads2k** [comment]
Closing based on https://github.com/openshift/origin/issues/5197#issuecomment-149731877
