### ISSUE TITLE
Deployer needs to inline hook pod logs into container output

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5199]
Hook pods are incredibly hard to debug.

**Comment by ironcladlou** [comment]
I started working on this and found myself needing to plumb through a concrete k8s `*unversioned.Client` from the client command downward. The `clientcmd.Config.Clients()` function gives me interfaces. I could try and set up the concrete clients myself, but I wouldn't be doing the same thing `Clients()` does (which uses a private `bindEnv()` call before instantiating the clients).

Is there some other stable way to obtain a concrete client from a command entrypoint? Alternatively, is there a way to get to the log stream for a pod using just `client.Interface`? I couldn't find a way.

**Comment by ironcladlou** [comment]
Quick clarification: I only needed to plumb the concrete client down into various constructors, which is fine IMO. The library code that does the really useful stuff works with either the client interfaces or private interfaces.

**Comment by ironcladlou** [comment]
I figured out how to get a concrete client safely, at least. I'm going to roll with that for now.

**Comment by kargakis** [comment]
This is fixed now

**Comment by ironcladlou** [comment]
Woops, I botched the description of the linked PR so this didn't auto-close.
