### ISSUE TITLE
openshift azure docker deploy

### ISSUE THREAD

**Issue by pdaniel** [openshift/origin#5202]
Hello,

I deployed openshift on azure using docker. 

sudo docker run -d --name "origin" \
        --privileged --net=host \
        -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys:ro -v /var/lib/docker:/var/lib/docker:rw \
        -v /var/lib/openshift/openshift.local.volumes:/var/lib/openshift/openshift.local.volumes \
        openshift/origin start

The problem is that openshift chooses the internal azure ip not the external one. How can i tell openshift to use the external ip? The public ip of Azure?

Regards

**Comment by liggitt** [comment]
you can specify two addresses for openshift:
1. Pass `--master=https://ip-or-host:8443` to set the address that the master and nodes should use to contact the API (internal IP might be fine for this)
2. Pass --public-master=https://ip-or-host:8443` to set the address the CLI and web console should use to contact the API (external IP or host should be used for this)

**Comment by pdaniel-frk** [comment]
can i pass this parameters to docker? Or do i need to change something in the config files of openshift?

**Comment by smarterclayton** [comment]
You would just add these to the end of the docker command you pasted above.
