### ISSUE TITLE
Breadcrumbs do not collapse properly in web console

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#5213]
Attaching a few screenshots. 

tablet:
![screen shot 2015-10-19 at 3 57 19 pm](https://cloud.githubusercontent.com/assets/280512/10589590/211f4994-767a-11e5-94ad-80c81e1b9e49.png)

mobile:
![screen shot 2015-10-19 at 3 57 27 pm](https://cloud.githubusercontent.com/assets/280512/10589592/23119afe-767a-11e5-82fb-c6fd4c4593fc.png)

**Comment by spadgett** [comment]
Same as #5178

**Comment by benjaminapetersen** [comment]
closing the dup
