### ISSUE TITLE
Refactor server version negotiation and client cache to consolidate with upstream

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#5216]
Origin client/server version negotiation was introduced in #4992 to support v1beta3 removal. The code to handle negotiation and client caching is only very partially shared with upstream, and does some inefficient things with the config objects to work around the upstream code's lack of pluggability.

This PR is to track requirements for refactoring origin and/or kube in whatever ways necessary to remove duplication and efficiently share the client caching and negotiation logic with upstream.

**Comment by ironcladlou** [comment]
cc @liggitt @deads2k to provide any further insights into what needs done and to assess our risk is in continuing with the current implementation.

**Comment by liggitt** [comment]
Also, our factory.ClientConfig() returns a config negotiated against the kubernetes API. We use that in several commands (edit, env, export, etc), assuming the negotiated version will also work against the OpenShift API
