### ISSUE TITLE
"--config" option doesn't work for CLI

### ISSUE THREAD

**Issue by nak3** [openshift/origin#5218]
- env

~~~
$ oc version
oc v1.0.6-748-gd9fde09
kubernetes v1.2.0-alpha.1-1107-g4c8e6f4
~~~

- issue:

  - After I run openshift standalone mode, `--config` options doesn't work. `KUBECONFIG` environment valiable does work.
  - Please see below 

~~~
~$ export KUBECONFIG=""
~$ oc whoami
error: couldn't read version from server: Get http://172.17.8.101:8080/api: dial tcp 172.17.8.101:8080: no route to host
~$ oc whoami --config=/ssd/work/origin/openshift.local.config/master/admin.kubeconfig
error: couldn't read version from server: Get http://172.17.8.101:8080/api: dial tcp 172.17.8.101:8080: no route to host
~$ export KUBECONFIG=/ssd/work/origin/openshift.local.config/master/admin.kubeconfig
~$ oc whoami
system:admin

~$ oc options
...
      --config='': Path to the config file to use for CLI requests.
...
~~~

**Comment by nak3** [comment]
- My origin server's address is `10.64.217.111`:
~~~
~$ cat /ssd/work/origin/openshift.local.config/master/admin.kubeconfig |grep server
    server: https://10.64.217.111:8443
~~~
~~~
$ hostname -i
10.64.217.81
~~~

- I am not sure where `172.17.8.101` is from

~~~
$ nslookup 172.17.8.101
Server:		10.64.255.25
Address:	10.64.255.25#53

** server can't find 101.8.17.172.in-addr.arpa: NXDOMAIN
~~~

**Comment by soltysh** [comment]
@deads2k this might be post rebase issue, I fall into today as well.

**Comment by deads2k** [comment]
This got brought in with https://github.com/openshift/origin/pull/4992.  Looks like new-app and new-build access the factory before flags are bound here https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/newapp.go#L112-L114 and here https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/newbuild.go#L51-L53, which causes `defaultClient` here to get set to the raw values before flags are parse.

@csrwng I'll get you to review the fix.

**Comment by liggitt** [comment]
@ironcladlou that could explain the oddity we saw around --loglevel
