### ISSUE TITLE
Remove openshift/origin-haproxy-router-base

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5221]
No longer necessary.  We should only build one combined image in origin-haproxy-router. Can be post 1.1 if there are significant impacts to release management process (@sdodson?)

@ramr

**Comment by sdodson** [comment]
We don't ship origin-haproxy-router-base image for OSE. I just need to make sure to copy over the Dockerfile changes, fine with doing this before or after 1.1. Your choice.

**Comment by smarterclayton** [comment]
After

**Comment by DanyC97** [comment]
i guess this issue can be closed?

**Comment by pweil-** [comment]
haproxy is now built from `openshift/origin`
