### ISSUE TITLE
oc port-forward on Windows "socat not found"

### ISSUE THREAD

**Issue by myfear** [openshift/origin#5225]
D:\temp\test>oc port-forward  mysql-2-zjx6u 3306:3306
I1020 11:38:54.754799    8356 portforward.go:227] Forwarding from 127.0.0.1:3306 -> 3306
I1020 11:38:54.757299    8356 portforward.go:227] Forwarding from [::1]:3306 -> 3306
I1020 11:39:10.824839    8356 portforward.go:253] Handling connection for 3306
E1020 11:39:10.833340    8356 portforward.go:312] An error occurred forwarding 3306 -> 3306: Error forwarding port 3306 to pod mysql-2-zjx6u_myfe
ar, uid : Unable to do port forwarding: socat not found.

D:\temp\test>oc version
oc v1.0.6
kubernetes v1.1.0-alpha.0-1605-g44c91b1

Any idea what that means and how to prevent this? Was trying to access a mysql db.

**Comment by myfear** [comment]
vagrant ssh
sudo /bin/yum install socat

solves it. Maybe add socat to the all-in-on vm?

**Comment by danmcp** [comment]
socat should be there.  Maybe you have an old image?  Try running:

vagrant box remove fedora_inst

and vagrant up again.
