### ISSUE TITLE
Initial Deployment Fails From Template

### ISSUE THREAD

**Issue by myfear** [openshift/origin#5226]
I tried to use the https://github.com/openshift/origin/blob/master/examples/db-templates/mysql-persistent-template.json 

Imported it oc create -f mysql-persistent-template.json -n myfear
and added it via the admin console to my project.

The events log shows:

mysql	DeploymentConfig	failedCreate	Couldn't create initial deployment: DeploymentConfig "mysql" is invalid: triggers[0].imageChange.from: invalid value 'mysql', Details: imageStream "mysql" not found

If I issue a 

oc deploy mysql --latest -n myfear

the image get's pulled and the pod created.

Am I doing something wrong?

**Comment by mnagy** [comment]
@myfear you are missing an image stream with the MySQL image in the openshift namespace. Add it using:
```
oc create -n openshift -f https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json
```

**Comment by myfear** [comment]
Thank you. But as a user this leaves me wondering. If I trigger a deploy
from an instance manually, this gets pulled automatically.
If I try to instantiate from a template first time, I do have to create the
image stream myself first?

That does not make a lot of sense to me as a simple user.

M

**Comment by smarterclayton** [comment]
The installer will automatically create these image streams for you.  We don't create them by default because some administrators may choose not to expose them to end users, or have their own.

**Comment by soltysh** [comment]
Related to https://github.com/openshift/origin/issues/7663

**Comment by kargakis** [comment]
> Related to #7663

Nope, that's a different issue that started after https://github.com/openshift/origin/pull/7529

**Comment by bparees** [comment]
the templates have been fixed to use invalid image values (so they can't accidentally get deployed) and the deployment logic has been fixed to properly respect the ICT and ignore the initial image field value.
