### ISSUE TITLE
Feature Request: Certificate Management / Updating Certificates used internally by OpenShift

### ISSUE THREAD

**Issue by plakat** [openshift/origin#5229]
I may have overlooked an essential piece of documentation, but so far I was not able to resolve the question of what happens 1 year after the initial installation when the generated certificates expire.

I know that master and node certificates can be generated individually by using `oadm ca` subcommands, but that doesn't include certificates used to connect to etcd and between etcd instances (which can be generated using openssl commands of course) and does not move the master-/node-/CA-certificates to their respective locations.
Trying to isolate these parts in the `openshift-ansible` installation scripts was a rather pointless exercise as the communication with the external etcd introduced with the next version after I had tried that changed just too much.

My request is to streamline the regeneration of certificates used within the OpenShift infrastructure from a central point (would be best if that could even be done from another host that is not part of the OpenShift cluster). Certificates for the internal CA, master, nodes and etc. should all be handled by this.

The update should be possible with a running cluster of minimal downtime, but without the need to access individual nodes. Integration with `openshift-ansible` is important to us as well since we plan to dynamically add nodes to an existing cluster using Ansible. These new nodes should of course use the current CA certificate.

**Comment by liggitt** [comment]
@sdodson @detiber

**Comment by brenton** [comment]
The work on this will be tracked here: https://trello.com/c/NsT6f1HL/38-oo-install-support-for-redeploying-certificates.

**Comment by brenton** [comment]
Please see trello for updates.
