### ISSUE TITLE
make cherry-pick.sh foolproof

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5231]
It ought to be possible, if the referenced kube repo doesn't exist or isn't setup properly, to build a kube repo in a temp folder with the correct configuration for finding upstream pulls and create and use that.

@smarterclayton

**Comment by bparees** [comment]
@deads2k i assume this issue is wildly irrelevant/outtdated at this point

**Comment by deads2k** [comment]
> @deads2k i assume this issue is wildly irrelevant/outtdated at this point

We still use a crazy bash script that attempts to pick these things and that few people can make work.  I wish it wasn't so, but I got questions on this thing last week from someone. 

Might actually have been @ironcladlou
