### ISSUE TITLE
[post-rebase] make test/cmd/admin.sh "not present in output" tests check only the expected field

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5236]
We should explicitly test fields that we're messing with, not grep through the entire output.  This should be easier with json path support.

**Comment by stevekuznetsov** [comment]
@deads2k which tests should be updated?

**Comment by deads2k** [comment]
> @deads2k which tests should be updated?

Read through the `*_and[_not]_text` tests.  If you run with verbose on, you should be able to see what they're matching.  Most are probably specific fields.

**Comment by stevekuznetsov** [comment]
Should be mostly solved.

/close
