### ISSUE TITLE
[post-rebase] conversion generator is broken

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5238]
`UPSTREAM: <drop>: tweak generator to handle conversions in other packages` shouldn't be necessary with AssumePrivateConversions. Figure out why it's needed.

**Comment by sgallagher** [comment]
@deads2k Would you mind providing more information on this bug?

How would I go about spotting the failure?

**Comment by liggitt** [comment]
Revert the mentioned commit, then run update-generated-conversions

**Comment by sgallagher** [comment]
This looks to have already been resolved by commit 2b5119f25eb4183f8e13dbb1f2c2f13433e6a0c5

**Comment by liggitt** [comment]
agree
