### ISSUE TITLE
[post-rebase] Inspect or add policy objects for username and groupname fields.

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5239]
@liggitt  this one is mine.

**Comment by liggitt** [comment]
which fields are these?

**Comment by deads2k** [comment]
> which fields are these?

The old fields before subjects.  If the conversions are borked, it would be on those fields.

**Comment by deads2k** [comment]
Conversions working fine, so https://github.com/openshift/origin/pull/5143#issuecomment-149306626 isn't a problem.  Turns out that it is now possible to write a partial custom conversion that takes over after an auto-generated conversion has done its best.
