### ISSUE TITLE
oc <= 1.0.4 defaults to v1beta3

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5254]
Found when using older `oc` clients after removing v1beta3 from master

Clients 1.0.4 and earlier are defaulting to v1beta3
```
$ oc get projects --token=... --server=https://localhost:8443 --loglevel=8
I1020 13:42:02.326013   27447 debugging.go:98] GET https://localhost:8443/osapi/v1beta3/projects
I1020 13:42:02.326065   27447 debugging.go:105] Request Headers:
I1020 13:42:02.326073   27447 debugging.go:108]     User-Agent: oc/v1.0.4 (linux/amd64) openshift/757efd9
```

Working versions: 1.0.5+
Broken versions: 1.0.4 and below

Passing --api-version=v1 allows these clients to talk to a v1 server.

We should:
1. Document how to make older clients work with v1
2. Ensure current code is doing negotiate, not hard-coding v1

cc @mfojtik

**Comment by mfojtik** [comment]
so I was not crazy, thanks @liggitt !

**Comment by jwforres** [comment]
Purely a documentation issue, nothing else can be done for this.

**Comment by fabianofranz** [comment]
Adding documentation notes here: https://github.com/openshift/openshift-docs/pull/1134

**Comment by liggitt** [comment]
closed by docs in https://github.com/openshift/openshift-docs/pull/1134 and release notes in https://github.com/openshift/origin/releases/tag/v1.0.7
