### ISSUE TITLE
`oc export` doesn't honor commas in long-form names

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#5255]
Steps to reproduce:

``` sh
$ oadm groups new "a,b"
$ oc export "groups/a,b"
error: no resource "a" is defined for group ""
```

However, short-form names work:

``` sh
$ oadm groups new "a,b"
$ oc export group "a,b"
apiVersion: v1
kind: Group
metadata:
  creationTimestamp: null
  name: a,b
users: null
```

@deads2k

**Comment by liggitt** [comment]
that's resource builder generally. don't use commas in long form names? does `groups/a groups/b` work?

**Comment by deads2k** [comment]
> that's resource builder generally. don't use commas in long form names?

Piping produces short form names.

**Comment by deads2k** [comment]
> that's resource builder generally. don't use commas in long form names?

Err, piping produces resource specified names.  `oc get groups -o name | xargs oc export` as a for instance.

**Comment by stevekuznetsov** [comment]
This is new as of the rebase, FWIW

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/16061

**Comment by stevekuznetsov** [comment]
Moved upstream, closing this.

**Comment by liggitt** [comment]
It's ok to keep a tracker open here, especially if it impacts us

**Comment by juanvallejo** [comment]
No longer able to reproduce original issue in version:
```
oc v1.3.0-rc1+1b1722a-1610-dirty
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://10.13.137.149:8443
openshift v1.3.0-rc1+a38151f-1683-dirty
kubernetes v1.4.0+776c994
```

```
$ oadm groups new "a,b"
NAME      USERS
a,b

$ oc export "groups/a,b"
apiVersion: v1
kind: Group
metadata:
  creationTimestamp: null
  name: a,b
users: null
```

will take a look at [upstream](https://github.com/kubernetes/kubernetes/issues/16061) issue.
