### ISSUE TITLE
`oadm groups new` doesn't have verbose output

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#5256]
When creating a new group using `oadm groups new name` there should be output `Group "name" created`. 

@deads2k

**Comment by deads2k** [comment]
@danmcp assign to steve.

**Comment by danmcp** [comment]
@smarterclayton What should the replacement priority be?

**Comment by smarterclayton** [comment]
its p3

**Comment by stevekuznetsov** [comment]
@enj if this hasn't been fixed already
