### ISSUE TITLE
Unable to login as system:admin

### ISSUE THREAD

**Issue by joeswaminathan** [openshift/origin#5259]
I using the tag v1.0.6 on Fedora 22

When I tried to login I get the following error. (I looked at #4650, but unable to understand why it doesnt use the certificates for me)

[kumo@os-master master]$ oc login -u system:admin -n default
Server [https://localhost:8443]: 
2015-10-20 11:22:27.113009 I | http: TLS handshake error from 127.0.0.1:39396: remote error: bad certificate
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Authentication required for https://localhost:8443 (openshift)
Username: system:admin
Password: 

I looked at the documentation it says, certain users are created by default. But when I issue "oc config view" I don't see any users

[kumo@os-master master]$ oc config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []

**Comment by liggitt** [comment]
That user is the bootstrap cluster admin user, and is authenticated using a client certificate. Make sure you are using the admin.kubeconfig which already contains the system:admin credentials. `oc config view` should show a user stanza with the system admin credentials, in which case `oc login -u system:admin` just switches to use those credentials.

**Comment by deads2k** [comment]
> That user is the bootstrap cluster admin user, and is authenticated using a client certificate. Make sure you are using the admin.kubeconfig which already contains the system:admin credentials. oc config view should show a user stanza with the system admin credentials, in which case oc login -u system:admin just switches to use those credentials.

Rather than always using the `admin.kubeconfig`, you can simply login as yourself, but when you need cluster-admin rights, you can use `--config=path/to/admin.kubeconfig` as an arg to the command.

**Comment by joeswaminathan** [comment]
Thanks for the quick response. Could you please clarify what you mean by "Make sure you are using the admin.kubeconfig".   Where do I specify this

I do see admin.kubeconfig under <homedir>/openshift.local.config/master. And I did start openshift as 

    openshift start --master-config=<homedir>/openshift.local.config/master/master-config.yaml --node-config=<homedir>/openshift.local.config/node-os-master/node-config.yaml

**Comment by joeswaminathan** [comment]
@deads2k  Thanks that worked. 

    oc login -u system:admin -n default --config=<homedir>/openshift.local.config/master/admin.kubeconfig

**Comment by diatmpravin** [comment]
I was not able to find `master/admin.kubeconfig` file.  It's located in `/etc/origin/master/admin.kubeconfig`. 

- I have copied it to .kube 
cp /etc/origin/master/admin.kubeconfig /home/fedora/.kube/admin.kubeconfig

- Change permission to fedora
sudo chown fedora:fedora admin.kubeconfig

- Now I can login
oc login -u system:admin -n default --config=.kube/admin.kubeconfig

**Comment by rushins** [comment]
what is the default password for user "admin" on the webconsole .

**Comment by deads2k** [comment]
> what is the default password for user "admin" on the webconsole .

Using `openshift start`, any password will work for authentication, but the "admin" user won't have any powers (can't get/list/watch/create anything).  He can create a new project to work with though.

"admin" is different than "system:admin".  "system:admin" is a certificate identified user.

**Comment by dnepangue** [comment]
Sorry to bring this old thread but how to login in web console  with system:admin privilege? Should I create a user with cluster administrator access?

**Comment by jasonmacdonald** [comment]
Same question, how do I actually access the webconsole with admin privileges?

**Comment by dnepangue** [comment]
@jasonmacdonald If you can login to system:admin in the terminal, you can create a user and give it a cluster admin access.

**Comment by jasonmacdonald** [comment]
Yes, I eventually did just that. The instruction just lead me to believe that I would use the system:admin account to do that. Thanks!

**Comment by sureshpalemoni** [comment]
I have installed htpasswd, and created a user and mapped identity provider as well. Still I am unable to login to the console or through cli "oc login"

**Comment by developerworks** [comment]
If you just in test env, you could add `cluster-admin` role to user `developer` with this:

```
oc adm policy add-cluster-role-to-user cluster-admin developer
```

**Comment by wgui1** [comment]
in my local cluster launched by "oc cluster up", I can get KUBECONFIG from command 'docker inspect origin'
then you can run oc command with admin privilege
```
export KUBECONFIG=`docker inspect origin|grep KUBECONFIG|sed -e 's/.*KUBECONFIG=\(.*\)".*/\1/'`
oc get pod
NAME                            READY     STATUS      RESTARTS   AGE
docker-registry-1-np566         1/1       Running     0          43m
persistent-volume-setup-9zqfr   0/1       Completed   0          44m
router-1-54rjm                  1/1       Running     0          43m
```

**Comment by tdavison784** [comment]
@muheric I am also facing the same issue.. This is happening for me when I am trying to install openshift-origin36 following the guide in "_OpenShift In Action_" Appendix A.  The install appears to go fine and I am able to see the console and attempt to login then get an Error in the console. 

When trying to login with oc I get the following:

`[user@ocp-1 ~]$ oc login
Authentication required for https://ocp-master.nip.io:8443 (openshift)
Username: system
Password: 
Login successful.

Using "default".  You can switch projects with:

 'oc project <projectname>'
[duser@ocp-1 ~]$ oc whoami
Error from server (Forbidden): User "system" cannot get users at the cluster scope
`
Any one else seeing this issue?

**Comment by aisuhua** [comment]
> I was not able to find `master/admin.kubeconfig` file. It's located in `/etc/origin/master/admin.kubeconfig`.
> 
> * I have copied it to .kube
>   cp /etc/origin/master/admin.kubeconfig /home/fedora/.kube/admin.kubeconfig
> * Change permission to fedora
>   sudo chown fedora:fedora admin.kubeconfig
> * Now I can login
>   oc login -u system:admin -n default --config=.kube/admin.kubeconfig

That works for me!
