### ISSUE TITLE
Error not displayed for deleted project in UI after navigating tabs

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5261]
Steps to reproduce:

1) Open a project. I was on one of the browse pages.
2) oc delete project <name> on the command line.
3) Switch to the overview tab.

You can see an error message in the browser location bar, but it's not displayed to the user.

![screen shot 2015-10-20 at 2 50 07 pm](https://cloud.githubusercontent.com/assets/1167259/10617758/20caa522-773a-11e5-911e-15d027e87774.png)

**Comment by jwforres** [comment]
Cant reproduce, tried FF and Chrome. Maybe it was a particular browse page you were on? Or maybe it got fixed with all the changes that went in yesterday.  I see the error page:

![error_page](https://cloud.githubusercontent.com/assets/1467629/10640310/21a18f9e-77e2-11e5-8fb1-2b3bd01139fe.png)

**Comment by spadgett** [comment]
I can't reproduce either. Will reopen if I see it again.
