### ISSUE TITLE
Log links missing href attribute

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5262]
The "Raw" and "Open full view" links on the build logs page (and maybe pod logs?) are missing an `href` attribute. The cursor is a bar and not a pointer on hover and the links can't be focused using the keyboard.

/cc @benjaminapetersen @jwforres

**Comment by spadgett** [comment]
The reconnect link on the same page, too.

**Comment by benjaminapetersen** [comment]
I'll take this one, assign it to me, thanks!

**Comment by spadgett** [comment]
Noticed this for the go to start and go to end links as well.

**Comment by jwforres** [comment]
Fixed
