### ISSUE TITLE
Pod log spinner distracting

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5266]
The spinner that we display at the bottom for running pods never stops animating (because the pod is still running and the logs still streaming). It's fairly large and distracting. I suggest we hide it as soon as data starts filling in or use something a bit more subtle.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/10619709/2796b00c-7745-11e5-8ceb-062fdc2cf19f.png)

Related: the "connection closed" message at the bottom of the logs makes it sound like there was an error when the log is just finished. Maybe change it to "Log complete" if everything loaded successfully?

/cc @benjaminapetersen @sg00dwin @jwforres

**Comment by benjaminapetersen** [comment]
I'm thinking subtle is probably fine, but I don't think I'd remove.  On the build page it will eventually disappear because a build completes.   On the pod page data may continue indefinitely & isn't guaranteed to stream at a consistent rate.

**Comment by jwforres** [comment]
@liggitt suggested text that says when we last received a message from the server.  Could also use a more subtle indicator like http://fortawesome.github.io/Font-Awesome/icon/ellipsis-h/

**Comment by benjaminapetersen** [comment]
I like the ellipsis, much smaller, though I'd still like to see some sort of animation on it.  Text could be helpful as well, until we have timestamps in the stream.

**Comment by sg00dwin** [comment]
animated ellipsis
http://codepen.io/sg00dwin/full/yYpWYp/

**Comment by liggitt** [comment]
does it work in IE? ;-)

**Comment by benjaminapetersen** [comment]
Is cool, definitely like that as an alternative!
Do we care about the amount of css? looks like 100+ lines?

**Comment by sg00dwin** [comment]
Tested and it works on IE 10,11 and latest ios and android devices.

Yes it's around 100 lines when including cross browser prefixes for animation and keyframes.

**Comment by benjaminapetersen** [comment]
Nice!

**Comment by sg00dwin** [comment]
@benjaminapetersen I'm updating the _log-formatted.html while adding in the ellipsis loader.

**Comment by benjaminapetersen** [comment]
@sg00dwin, sounds good!
