### ISSUE TITLE
Show view log link for failed logs as well on overview

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5269]
Right now we only show the view log link for running builds. I think at least we should show it for failed builds.

/cc @jwforres @benjaminapetersen

**Comment by jwforres** [comment]
I would go ahead and do complete and failed

**Comment by benjaminapetersen** [comment]
I can pretty easily just move the link to `View Log` to the end of the line & you can use it no matter what the status.  Work?

**Comment by jwforres** [comment]
@benjaminapetersen when the build is in "New" I don't think there is a pod yet, not sure about "Pending" but I'm guessing same thing.  What happens on build logs if there is no pod.

**Comment by benjaminapetersen** [comment]
Good Q. I'll check into that.

**Comment by spadgett** [comment]
@jwforres @benjaminapetersen We might want to hide the logs tab when a pod is pending as well since there won't be a log yet.

<img width="506" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/10664903/214388aa-7895-11e5-8909-8af8682c1b26.png">

**Comment by jwforres** [comment]
stef did this for the terminal tab already, can probably reuse his helper
method

**Comment by benjaminapetersen** [comment]
I tend to think that if logs will exist, even if its a few seconds into the future, we should show the tab, but hide the tab for something that would never have logs.

**Comment by liggitt** [comment]
agree... I'd want to be able to switch to the logs tab, and when the pod entered running state, it would keep trying to connect and show me the logs

**Comment by liggitt** [comment]
mixing test into the indicator at the bottom could also be where we show status of the log-following operation:
"Waiting for pod to start..."
"Waiting for logs..."
"Logs through 5:03pm..."
"Showing logs through 5:03pm. Connection interrupted, [reconnect](#)"

**Comment by jwforres** [comment]
We should update the terminal tab to match this behavior  then.

**Comment by liggitt** [comment]
As long as we handle it well and make it clear to the user ("Waitong for the pod to start", etc)

**Comment by benjaminapetersen** [comment]
Yeah I like that, more user friendly status messages.

**Comment by jwforres** [comment]
Fixed
