### ISSUE TITLE
Builds should have more human-friendly names

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#528]
Currently builds triggered automatically gets a UUID style names. I would be nice if we can have more 'human friendly' names, like:

`<buildConfig.Name>-build-<number/Ref>`

**Comment by bparees** [comment]
https://trello.com/c/jaBsS4IZ/520-name-builds-sequentially

**Comment by soltysh** [comment]
@bparees the PR is merged, can you close this now, please.

**Comment by bparees** [comment]
yup, thanks!
