### ISSUE TITLE
Url encode filters when following chart link

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#5281]
When I click the scaling donut on the overview page, I expect to see the filters applied to the pods url encoded.

![screen shot 2015-10-21 at 9 55 48 am](https://cloud.githubusercontent.com/assets/280512/10638663/02c9ebbe-77da-11e5-9502-9865f5d028f7.png)

![screen shot 2015-10-21 at 9 55 55 am](https://cloud.githubusercontent.com/assets/280512/10638666/05e1a332-77da-11e5-8564-0231f4e71315.png)

But our url only indicates 'browse pods'.

**Comment by liggitt** [comment]
See prior conversation about tab navigation. Not sure I'd expect a history entry for each label add/remove. I don't object to the filter being bookmarkable, but I don't like the history clutter

**Comment by jwforres** [comment]
fixed
