### ISSUE TITLE
A couple of oc commands should switch to PATCH

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#5287]
`oc env`, `oc edit` (already switched upstream), and maybe `oc tag` are coming to my mind.

See:
https://github.com/kubernetes/kubernetes/issues/15333
https://github.com/kubernetes/kubernetes/pull/15651
https://github.com/kubernetes/kubernetes/pull/15597

**Comment by deads2k** [comment]
One thing to consider when deciding whether to switch to patch over replace: "is my change predicated on anything in the current state of the resource?".  Non-conflicting patches are applied unconditionally against `resourceVersion` of the object.  If your changes is predicated on anything in the current state, either continue to use update or fix patch to handle preconditions.

**Comment by liggitt** [comment]
`env` I could see... for `edit`, I would want to know if I was stomping, I think

**Comment by deads2k** [comment]
> env I could see... for edit, I would want to know if I was stomping, I think

Not if you're using `edit`.  It auto-generates the patch for you on conflicts, applies, and resends the `update`.
