### ISSUE TITLE
bash autocompletions are not packaged into our binaries

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#5290]
We should package our autocompletions into our releases. It would be nice if they were compiled into the binary and the binary would check for them in the user's home directory and place them if they're not found or outdated.

@sdodson

**Comment by sdodson** [comment]
If we're going with the suggestion in the description this is a hack/build-go.sh and golang fix un-related to the installer. I think this should be assigned to the UI/CLI team.

**Comment by danmcp** [comment]
@smarterclayton Please provide a replacement priority.

**Comment by sdodson** [comment]
@fabianofranz Any thoughts on bundling completions for users who download the client only?

**Comment by smarterclayton** [comment]
I assume we're just going to have an oc config autocomplete or something?

On Nov 21, 2015, at 6:00 PM, Scott Dodson <notifications@github.com> wrote:

@fabianofranz <https://github.com/fabianofranz> Any thoughts on bundling
completions for users who download the client only?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5290#issuecomment-158689029>.

**Comment by fabianofranz** [comment]
`oc login` could perform the check and update along with the config file handling, and we could have an explicit command to force it manually, `oc config complete` like @smarterclayton mentioned, for example.
@sdodson I agree this is for the UI team, @danmcp please reassign?

**Comment by liggitt** [comment]
not sure I want `login` to do that... config file is within it's set of responsibilities... autocomplete installation probably isn't

**Comment by smarterclayton** [comment]
Agree - being able to source an autocomplete file is probably all we should
do for now.

On Nov 23, 2015, at 10:01 AM, Jordan Liggitt <notifications@github.com>
wrote:

not sure I want login to do that... config file is within it's set of
responsibilities... autocomplete installation probably isn't

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5290#issuecomment-158960930>.

**Comment by fabianofranz** [comment]
Reopening, unless I missed it this was fixed in Kube is still pending a new Kube rebase into origin.

**Comment by stevekuznetsov** [comment]
Didn't realize Kube PRs could auto-close Origin issues...

**Comment by fabianofranz** [comment]
Fixed by https://github.com/openshift/origin/issues/9354
