### ISSUE TITLE
It should be possible to have no output for a build

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#5296]
Extracted from #4980.

We will likely need to introduce another command line option that cannot be used together with `--to`.

**Comment by rhcarvalho** [comment]
@smarterclayton I need more input here, so if I won't have time to finish this before my PTO we can hand it to somebody else.

What's the use case for this feature?

What's the workflow you imagined for this?

```
$ oc new-app <source> --no-build-output
$ oc new-build <source> --no-output
```

Should it be `--no-output` or `--no-build-output` or something else?

I imagine the effect of setting this flag to true would be to create a build config in which the spec.output.to is empty?

**Comment by rhcarvalho** [comment]
Getting my hands dirty to implement this.

1. @smarterclayton could you list at least one use case for this feature? When is it meant to be used?

2. Should we add this to both `oc new-app` and `new-build`?

3. What is the intended effect of setting the `--no-build-output` flag to true? I imagine it should set buildconfig.spec.output.to to the empty string.

**Comment by smarterclayton** [comment]
1. A user should be able to set a build up to see whether the build works
against the latest code, without having to push that build somewhere else
2. Only to new-build
3. It would set spec.output.to to nil.
