### ISSUE TITLE
Are there auto scaling in OpenShift v3 ? Because in kubernetes project they don't have finished the development of the auto-scaler yet.

### ISSUE THREAD

**Issue by medhedifour** [openshift/origin#5302]

**Comment by medhedifour** [comment]
Are there auto scaling in OpenShift v3 ? 
Because in kubernetes project they don't have finished the development of the auto-scaler yet.

**Comment by medhedifour** [comment]
@smarterclayton 
@deads2k

**Comment by smarterclayton** [comment]
OpenShift Origin 1.1 and OSE 3.1 will support the autoscaler.  The function is ready for use, and in OpenShift we'll provide a stable interface that will evolve with backwards compatibility.

**Comment by medhedifour** [comment]
@smarterclayton 
The auto-scaling functionality in openshift origin v3 is based on kubernetes or added by the openshift project ?
Until now we cannot test the auto-scaling in openshift origin v3 ?

**Comment by smarterclayton** [comment]
It will be based on the work done in Kubernetes.  OpenShift will ship a
productized metrics stack that includes long term metrics storage for
cluster resources.

**Comment by medhedifour** [comment]
So, OpenShift origin v3 will wait for until the auto scaler of kubernetes will be completed ?

**Comment by smarterclayton** [comment]
The autoscaler will be in the next point release within the next few weeks.

**Comment by medhedifour** [comment]
@smarterclayton
Thanks a lot
