### ISSUE TITLE
extended tests are useless

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5311]
I find myself annoyed by the sea of red that prevents me from easily knowing if buckets I care about are broken: https://ci.openshift.redhat.com/jenkins/job/origin_extended/.  I think that most of our problem is related to trying to run the upstream kube tests.  While a noble goal, it effectively means that we don't respect the results of any extended tests.

I'd like to use some reflective code (or ***&lt;shudder>*** bash) to inspect and locate the name of every upstream test, exclude them from `core.sh`, and include them in a `test/extended/kube.sh` that could be run separately, but wouldn't go into a normal run.  We could then start whitelisting reliable test and pick individual kube tests to fix up.

This would the extended runs become useful again.

@smarterclayton @bparees @mfojtik

**Comment by smarterclayton** [comment]
I'll offer an alternative version.

Why don't the e2e unit tests work against OpenShift, and why haven't we
fixed them?

**Comment by smarterclayton** [comment]
See https://github.com/openshift/origin/pull/5312

**Comment by deads2k** [comment]
> Why don't the e2e unit tests work against OpenShift, and why haven't we
> fixed them?

That approach requires that we make all of them work all at once.  I don't disagree that they *should* all work, but the reality of the situation is that they don't, we haven't devoted the effort to do it initially and maintain it through rebases, and because we're requiring it we've lost the utility of the tests we do have.

It's that loss of utility because of the demand for perfection that bothers me the most.  When we started and the buckets ran, there was interest.  Now that they don't run successfully, no one cares.

**Comment by smarterclayton** [comment]
Got one green https://ci.openshift.redhat.com/jenkins/job/origin_extended/200/

Next steps:

* Switch to the junit output and ensure that's recorded by origin_extended (so we can quickly identify failing tests)
* Parallelize
* Uncomment other tests once we know they are working (we need to fix the default image User ID problem for privileged accounts).

@bparees @mfojtik

**Comment by bparees** [comment]
Deflake several tests that are still being run.

Ben Parees | OpenShift

**Comment by deads2k** [comment]
@stevekuznetsov you were assessing different junit visualization plugins for jenkins.  I'm not particularly pleased with the one we have.  Is there a better one?

**Comment by stevekuznetsov** [comment]
There is really only one with widespread use, the built-in [jUnit Plugin](https://wiki.jenkins-ci.org/display/JENKINS/JUnit+Plugin).

**Comment by smarterclayton** [comment]
Define "not pleased with the one we have".  What features are missing?

**Comment by deads2k** [comment]
> Define "not pleased with the one we have".  What features are missing?

I can't seem to find the output sliced by test.  Say a table showing all tests color coded for percent of recent failures and columns for first seen, last successful run.  The closest I've seen shows things like "failing for 83 builds", when in fact it wasn't run for 83 builds.

**Comment by smarterclayton** [comment]
Hrm, I've seen that I think.   I don't remember how I got there though -
but it was pass fail over successive builds.

On Dec 17, 2015, at 3:40 PM, David Eads <notifications@github.com> wrote:

Define "not pleased with the one we have". What features are missing?

I can't seem to find the output sliced by test. Say a table showing all
tests color coded for percent of recent failures and columns for first
seen, last successful run. The closest I've seen shows things like "failing
for 83 builds", when in fact it wasn't run for 83 builds.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5311#issuecomment-165576249>.

**Comment by stevekuznetsov** [comment]
I think we are in a much better place re: including upstream extended tests today.
