### ISSUE TITLE
test-cmd newapp test flake

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#5318]
(from https://github.com/openshift/origin/pull/4909)
https://travis-ci.org/openshift/origin/jobs/86779877
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3718/consoleFull

```
...
W1022 08:29:46.635835   43665 pipeline.go:244] A service will not be generated for DeploymentConfig "php" because no exposed ports were detected. Use 'oc expose dc "php" --port=[port]' to create a service.
error: imageStream "php" already exists
DeploymentConfig "php" created
error: imageStream "mysql" already exists
DeploymentConfig "mysql" created
Service "mysql" created
!!! Error in test/cmd/newapp.sh:24
	'oc new-app php mysql -l no-source=php-mysql' exited with status 1
Call stack:
	1: test/cmd/newapp.sh:24 main(...)
Exiting with status 1
hack/../hack/util.sh: line 631: set: write error: Broken pipe
[FAIL] !!!!! Test Failed !!!!
```

Looks similar to https://github.com/openshift/origin/issues/4948, but refers to a different line/test case.

**Comment by smarterclayton** [comment]
It's possible that this is a result of a stale read on etcd - I added extra prereq checking and I still saw it, which makes me suspect that the earlier reads are not visible in the later reads.

**Comment by jwforres** [comment]
bumping priority, seeing this a lot today and its blocking up the merge queue

**Comment by bparees** [comment]
@smarterclayton can you elaborate?  we've got a tryuntil here that waits until an imagestream tag is available on the mysql imagestream, and then somehow when oc new-app runs after that check, it doesn't see the mysql imagestream and attempts to create one.

**Comment by bparees** [comment]
btw there is some potentially related imagestream flakiness i've been seeing here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6239/console
```
Error from server: imageStream "ruby" not found
Error from server: imageStream "nodejs" not found
Error from server: imageStream "postgresql" not found
Error from server: imageStream "mongodb" not found
Error from server: imageStream "wildfly" not found
imageStreamImage "sha256:" cannot be updated: multiple images match the prefix "sha256:": sha256:032dfadbc347bf54d2156ce706cd275ef94365e4eb2cdb7e4ba1dab21e2fdc0a, sha256:11387c846e51b3348e95bf56a4ba2b09deb64644075eaefed3433bdb1b795fd3
!!! Error in test/cmd/images.sh:68
	'oc describe "${imagename}"' exited with status 1
Call stack:
	1: test/cmd/images.sh:68 main(...)
Exiting with status 1
```

**Comment by smarterclayton** [comment]
i already pushed a fix for this.

**Comment by smarterclayton** [comment]
Fix was `tryuntil` didn't error if it reached the end and the condition wasn't true.  That meant that image imports (which got longer because of @soltysh's change to be able to granularly import) were going past 60 seconds and then still not being imported.

Bens problem.... I don't know what that is - that's probably new.

**Comment by bparees** [comment]
original issue fixed by https://github.com/openshift/origin/commit/fabe21c3a4ee7768261c43c25b1028f232b006fb#diff-b83ac5455d252fc0916d54924166ffa5

will chase the other one elsewhere.
