### ISSUE TITLE
Re-use edit command from upstream

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#5323]
We need to upstream some additional patches we have since `edit` was added to kubectl. Most important:

- [x] https://github.com/openshift/origin/pull/3086
- [x] https://github.com/openshift/origin/pull/5300
- [x] https://github.com/openshift/origin/pull/5306
- [ ] ...and then wrap it in oc.

UPSTREAM PRS:
https://github.com/kubernetes/kubernetes/pull/16160 (Windows fixes)
https://github.com/kubernetes/kubernetes/pull/17108 (needed for using our own env vars for specifying an editor)

**Comment by kargakis** [comment]
@smarterclayton @fabianofranz do you guys have any Kube PRs for your fixes?

**Comment by fabianofranz** [comment]
@kargakis I don't think any of the three have upstream PRs. But they are needed, otherwise there will be regressions.

**Comment by kargakis** [comment]
Upstream PR: https://github.com/kubernetes/kubernetes/pull/16160

**Comment by kargakis** [comment]
Upstream PR has lgtm and is going to be merged soon. I would suggest lowering this to P3 and letting it be picked up by the next rebase, otherwise we would have to carry a bunch of patches for no significant gain. @danmcp

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/17108 is in so we can override using our own env vars

**Comment by soltysh** [comment]
@kargakis since all required pieces are already upstream and the rebase lands are you going to work on it?

**Comment by kargakis** [comment]
@soltysh I will submit a PR tomorrow
