### ISSUE TITLE
newapp.go flake

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#5324]
I've noticed this failure earlier today in #5321, I'm pasting here only the necessary bit, all the rest is [here](https://travis-ci.org/openshift/origin/jobs/86793573):

```
I1022 10:09:33.156279   13463 newapp.go:560] Using "some/location.git" as the source for build
panic: test timed out after 1m0s
```

@csrwng fyi

**Comment by csrwng** [comment]
@soltysh yup, we have an issue open to remove external access from new-app unit tests -> https://github.com/openshift/origin/issues/4713

**Comment by soltysh** [comment]
Yeah, I've seen that, is that related with that? If so I can close it.

**Comment by csrwng** [comment]
Yes, it looks like the unit test simply timed out after waiting for network access.

**Comment by soltysh** [comment]
Fair deal.
