### ISSUE TITLE
Deploy config pulling from library/<image> not imagestream 

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#5327]
Using this template[1], deploy config from `image: helloapache` with a trigger from ImageStreamTag `helloapache:latest`[2]. Imagestream helloapache[3] has latest tag. When build completes and pushes image it does not trigger a deployment (unexpected). When deployment is started manually it fails trying to pull from docker hub `library/helloapache:latest` (also unexpected). Curiously, this template[4] works on the same environment.

Verbose logs here[5].

```
# oc version
oc v1.0.6-805-g3f0e8f6
kubernetes v1.2.0-alpha.1-1107-g4c8e6f4
```

[1] https://github.com/aweiteka/ose-build-pipeline/blob/master/ose-build-template.yaml
[2] deployconfig
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2015-10-22T11:45:19Z
  labels:
    app: helloapache
    template: automated-build
  name: helloapache
  namespace: build-demo
  resourceVersion: "381"
  selfLink: /oapi/v1/namespaces/build-demo/deploymentconfigs/helloapache
  uid: 5ef557e4-78b2-11e5-9c3b-54ee75102ab0
spec:
  replicas: 1
  selector:
    name: helloapache
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: helloapache
    spec:
      containers:
      - image: helloapache
        imagePullPolicy: IfNotPresent
        name: helloapache
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - helloapache
      from:
        kind: ImageStreamTag
        name: helloapache:latest
    type: imageChange
status:
  latestVersion: 1
```
[3]
```
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: 2015-10-22T11:45:19Z
    labels:
      app: helloapache
      template: automated-build
    name: helloapache
    namespace: build-demo
    resourceVersion: "371"
    selfLink: /oapi/v1/namespaces/build-demo/imagestreams/helloapache
    uid: 5ef57014-78b2-11e5-9c3b-54ee75102ab0
  spec: {}
  status:
    dockerImageRepository: 172.30.155.105:5000/build-demo/helloapache
    tags:
    - items:
      - created: 2015-10-22T11:48:11Z
        dockerImageReference: 172.30.155.105:5000/build-demo/helloapache@sha256:065ae90bc9c0b99318f3bf710c12e9c1a77ad8217e9f6d238485fe15fbc026c2
        image: sha256:065ae90bc9c0b99318f3bf710c12e9c1a77ad8217e9f6d238485fe15fbc026c2
      tag: latest
kind: List
metadata: {}
```
[4] https://github.com/mfojtik/jenkins-ci/blob/master/openshift/jenkins-master-ephemeral.json
[5] deploy ~11:49 https://s3.amazonaws.com/aweiteka.bucket/openshift_logs/ose.log

**Comment by ironcladlou** [comment]
Can you run through this scenario again with an origin server using `--loglevel=4`? I'd also be interested in seeing the output of `oc get event` after the build is complete and while you're waiting on the deployment. That will help us understand why the trigger isn't doing what is expected.

I do have an explanation for the behavior you see when trying a manual deployment: notice that the container your deploymentConfig is still using a docker pullspec which is literally `helloapache`. If you (or openshift) did a `docker pull helloapache`, the `library/` prefix would be added automatically, as would the `latest` tag.

Normally, the image trigger would detect your new image stream tag, and the deploymentConfig container image field would be updated to a full docker pullspec including your registry and a specific tag/image ID. The trigger isn't firing, so your initial image field value remains. A manual deployment simply advances the deploymentConfig's version to coerce a new deployment- the image field in the container isn't updated as part of that process.

**Comment by smarterclayton** [comment]
This is may be a bug in new-app (library being added to an image stream). I've squashed a few of them, but there's tricky handling in a few places that makes it hard to pin down all of them. @csrwng

**Comment by aweiteka** [comment]
> Can you run through this scenario again with an origin server using --loglevel=4? I'd also be interested in seeing the output of oc get event after the build is complete and while you're waiting on the deployment. That will help us understand why the trigger isn't doing what is expected.

New log captured[1] with `--loglevel=4`. Corresponding event list[2]

[1] https://s3.amazonaws.com/aweiteka.bucket/openshift_logs/build-deploy-29-10-2015.log
[2] http://fpaste.org/284895/13786114/

**Comment by goraxe** [comment]
Just as a 'me too' comment, I'm also seeing a similar issue where I have a BuildConfig, ImageStream, DeploymentConfig and I'm not seeing the trigger occur after a build and attempting a manual deploy results in failure due to attempting to pull library/<image>

**Comment by smarterclayton** [comment]
Can you paste your deployment config / build config / image stream yaml (oc
get dc/foo is/foo bc/foo -o yaml) ?

On Nov 20, 2015, at 7:05 PM, goraxe <notifications@github.com> wrote:

Just as a 'me too' comment, I'm also seeing a similar issue where I have a
BuildConfig, ImageStream, DeploymentConfig and I'm not seeing the trigger
occur after a build and attempting a manual deploy results in failure due
to attempting to pull library/

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5327#issuecomment-158563472>.

**Comment by goraxe** [comment]
This is the source yml file I have redacted the src uri cos ... reasons.  I have been trying to figure out if it was a typo or other syntax error for a little while could not see anything obvious, hence stumbling on this bug.  

---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
   name: "cwg-inventory"
spec:
    triggers:
        - type: "Generic"
          generic:
            secret: "build-it"
    source:
        type: "git"
        git:
            uri: "..."
        sourceSecret:
            name: stashsecret
    strategy:
        type: "Docker"
    output:
        to:
          kind: "ImageStreamTag"
          name: "cwg-inventory:latest"
---
kind: ImageStream
apiVersion: v1
metadata:
 name: cwg-inventory
---
kind: DeploymentConfig
apiVersion: v1
metadata:
 name: cwg-inventory
spec:
 replicas: 1
 selector:
  name: cwg-inventory
 template:
  metadata:
   labels:
    name: cwg-inventory
    env: dev
  spec:
    containers:
      - name: cwg-inventory
        image: cwg-inventory
    triggers:
     - type: ImageChange
       imageChangeParams:
         automatic: true
         containersNames:
          - cwg-inventory
         from:
            kind: ImageStreamTag
            name: cwg-inventory:latest
     - type: ConfigChange

**Comment by ironcladlou** [comment]
@goraxe Is that the entirety of your `cwg-inventory` ImageStream record? Your deploymentConfig references `cwg-inventory:latest` which has no corresponding tag entry in the ImageStream you listed.

**Comment by goraxe** [comment]
@ironcladlou yep that's it.  using this -> https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-dockerbuild.json as a guide neither or the imageStreams there have tags
