### ISSUE TITLE
Internal registry push loading bar

### ISSUE THREAD

**Issue by Mangirdaz** [openshift/origin#5328]
I want to see pushing to internal registry with loading bar:

-bash-4.2$ oc logs -f apaas-1-2708674907-build
Internal Error: pod is not in 'Running', 'Succeeded' or 'Failed' state - State: "Pending"
-bash-4.2$ oc logs -f apaas-1-2708674907-build
Already on 'master'
W1022 08:40:30.217551       1 docker.go:304] The 'io.s2i.scripts-url' label is deprecated. Use "io.openshift.s2i.scripts-url" instead.
W1022 08:40:30.236089       1 docker.go:304] The 'io.s2i.scripts-url' label is deprecated. Use "io.openshift.s2i.scripts-url" instead.
W1022 08:40:30.294958       1 docker.go:304] The 'io.s2i.scripts-url' label is deprecated. Use "io.openshift.s2i.scripts-url" instead.
I1022 08:40:31.313216       1 sti.go:407] Copying all WAR artifacts from /home/jboss/source/deployments directory into /opt/webserver/webapps for later deployment...
I1022 08:40:31.346271       1 sti.go:407] '/home/jboss/source/deployments/prime-face.war' -> '/opt/webserver/webapps/prime-face.war'
I1022 08:40:40.333435       1 sti.go:149] Using provided push secret for pushing 172.17.131.32:5000/mangis/apaas:latest image
I1022 08:40:40.333475       1 sti.go:151] Pushing 172.17.131.32:5000/mangis/apaas:latest image ...

My images (STI builders) are quite big and sometimes due some performance issues it hand up on push procedure. So status on push state would help to identify hanged builds.

**Comment by bparees** [comment]
You can enable build loglevel 5 if you want that output:
https://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs

Level 5 	- Produces everything mentioned on previous levels and additionally provides docker push messages.

**Comment by Mangirdaz** [comment]
Thanks, my bad :)
