### ISSUE TITLE
All CLI operations that touch etcd should use cmdutil.PrintSuccess

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#5332]
We need to unify the behavior of our commands, specifically:
- `openshift admin new-project`
- `openshift admin groups new`
- `openshift cli new-project`
- `openshift cli start-build`
- `openshift cli secrets new`
- `openshift cli secrets new-dockercfg`
- `openshift cli secrets new-basicauth`
- `openshift cli secrets new-sshauth`

Currently they all decide how to indicate success to the command line independently and this is frustrating and causes drift. We could think about unifying these methods to all use the upstream create flow as well.

@liggitt @deads2k

**Comment by deads2k** [comment]
As long as piping ability is maintained, then I'm fine with this.

**Comment by smarterclayton** [comment]
new-app and new-build should be updated to follow the upstream pattern, but
we still need to add -o name

**Comment by stevekuznetsov** [comment]
`new-app` and `new-build` conform to the pattern [here](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/newapp.go#L348)

**Comment by smarterclayton** [comment]
I think this is now fixed?

**Comment by stevekuznetsov** [comment]
I'm not sure either way, actually. Lots has changed since the pull wrss abandoned.

**Comment by kargakis** [comment]
pretty sure the deployment tooling doesn't use -o name

**Comment by smarterclayton** [comment]
Closing due to age.
