### ISSUE TITLE
Cannot create router

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#5342]
Using origin master, it looks like I am no longer able to create routers. 

The logs from the router pod:
>F1022 18:56:52.261536       1 deployer.go:64] request [&{Method:GET URL:https://192.168.122.1:8443/api/v1beta1/replicationControllers/myrouter-1?namespace=default Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[] Body:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:192.168.122.1:8443 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil>}] failed (403) 403 Forbidden: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot get replicationControllers at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "name": "myrouter-1",
    "kind": "replicationControllers"
  },
  "code": 403
}

I am following the steps outlined at https://docs.openshift.org/latest/install_config/install/deploy_router.html

`$ echo \
    '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"router"}}' \
    | oc create -f -`

`$ oc edit scc privileged`
& adding `system:serviceaccount:default:router` to the users section

`oadm router myrouter3 --credentials="$KUBECONFIG" --service-account=router`
where KUBECONFIG is openshift.local.config/master/admin.kubeconfig

After the router is created, it's pod shows as having an Error status and its log matches what is posted above
`oc get pods`
NAME                 READY     STATUS    RESTARTS   AGE
myrouter3-1-deploy   0/1       Error     0          51s

**Comment by liggitt** [comment]
The deployment is actually failing. Were there earlier logs in the deployer pod about not being able to read an API token? @pmorie @ncdc any magic troubleshooting steps for secret mounting to try?

**Comment by ncdc** [comment]
I'd check the selinux labels of the deploy pod's volumes. @mwringe how did you start openshift - from source, docker image, ...?

**Comment by mwringe** [comment]
@liggitt what I posted at the top of my first message is the entirely of the logs.

@ncdc I built and started OpenShift from source (master, git commit 767dc7dc42663aaf1b9e7e90f8e7279ab7acbf8a). Its running locally, not from within a docker container.

**Comment by liggitt** [comment]
what version of the deployer image are you using?

**Comment by liggitt** [comment]
whoa, must be a really really old one, it is using `v1beta1`:
```
F1022 18:56:52.261536 1 deployer.go:64] request [&{Method:GET URL:https://192.168.122.1:8443/api/v1beta1/replicationControllers/myrouter-1?namespace=default Proto:HTTP/1.1 ProtoMajor:1 
```

**Comment by ncdc** [comment]
whoa indeed. re-pull that image!

**Comment by mwringe** [comment]
Oops. yeah, its using openshift/origin-deployer:v0.3.2 from 8 months ago.

Should it not be pulling in a more recent version automatically? I wouldn't expect it force the user to manually pull in the docker image here. At least not with the default setup with no `images` specified when creating the router.

**Comment by liggitt** [comment]
yes, it should be using the latest tag (e.g. 1.0.6 currently)

**Comment by liggitt** [comment]
unless you invoked it with a custom --images arg

**Comment by mwringe** [comment]
Ok, something weird is going on with my setup.

Even with `oadm router myrouter --credentials="$KUBECONFIG" --service-account=router --images="openshift/origin-deployer:v1.0.6"` it is still using v0.3.2

**Comment by ncdc** [comment]
The `--images` flag you pass to `oadm router` affects what router image is used, not what deployer image is used.

It's what you pass to `openshift` that controls what deployer image is used. Try passing `--latest-images` to `openshift start`.

**Comment by ncdc** [comment]
Or if you don't pass `--latest-images`, what @liggitt said is right - it should be picking up the latest versioned images (1.0.6). If it's not... that's odd.

**Comment by ncdc** [comment]
@mwringe did you generate master & node configs, by any chance?

**Comment by liggitt** [comment]
deployer pod is determined by how you start the openshift server... what invocation are you using there?

**Comment by mwringe** [comment]
@ncdc yes, I genered my own master & node configs

I am going to shut down this instance of OpenShift and do another checkout in a separate directory, build, start and try again. Maybe there is something wrong with my setup

**Comment by ncdc** [comment]
@mwringe check your master config

**Comment by liggitt** [comment]
I'd expect to see this:
```
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
```

**Comment by mwringe** [comment]
From openshift.local.config/master/master-config.yaml

`imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false`

Where exactly is the version set?

**Comment by liggitt** [comment]
calculated at build time from closest git tag, I think. The first segment of `openshift version` will tell you what it would use for the version, I think

**Comment by mwringe** [comment]
The issue is how you calculate the version. I will open another issue for that.
