### ISSUE TITLE
OpenShift calculates the wrong version

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#5350]
OpenShift appears to calculate its version based on the git commit and comparing that to a tag. This assumes that the checkout you are using actually has those tags, which is not always the case.

It is easy to fork the repo and not always pull down all the tags from the original repository. This means that you can be running the latest OpenShift Origin code, while OpenShift origin thinks its actually running some older version.

This can cause issues and confusion when this version is used to download specific docker containers (eg https://github.com/openshift/origin/issues/5342). Especially when the code used to build both 

Is there not a better way to calculate the version which would be less prone to giving incorrect results?

**Comment by smarterclayton** [comment]
We could force you to fetch tags from origin during a build.  Checking in the version as a constant into code has an equally sized set of different problems.

**Comment by smarterclayton** [comment]
We're not going to change how this works.
