### ISSUE TITLE
myql replica extended test is failing

### ISSUE THREAD

**Issue by bparees** [openshift/origin#5352]
STEP: Destroying namespace "extended-test-mysql-replication-1-t5eev" for this suite.
• Failure [200.941 seconds]
images: mysql: replication [It] MySQL replication template https://raw.githubusercontent.com/openshift/mysql/master/5.5/examples/replica/mysql_replica.json 
/home/bparees/git/gocode/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/mysql_replica.go:151

  Expected error:
      <*errors.errorString | 0xc820147a30>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /home/bparees/git/gocode/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/mysql_replica.go:78

fail    images: mysql: replication MySQL replication template https://raw.githubusercontent.com/openshift/my ... (3m20.940651952s)

**Comment by bparees** [comment]
status update from martin:

**Comment by bparees** [comment]
closing for now as it hasn't recurred in the most recent runs.

**Comment by bparees** [comment]
this is still flaking even after i increased the timeout:
https://ci.openshift.redhat.com/jenkins/job/origin_extended/198/consoleFull

**Comment by smarterclayton** [comment]
Still failing - we had one (1!!!!) successful build.

**Comment by smarterclayton** [comment]
```
  to contain substring
      <string>: <span class="code" id="count-value">1</span>

  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/sample_repos.go:74
------------------------------
    fail    samplerepo: test the sample application repositories samplerepo: images: parallel: test nodejs image ... (1m44.26163139s)
```

is flaking again

**Comment by bparees** [comment]
flaked again here:
https://ci.openshift.redhat.com/jenkins/job/origin_extended/378/testReport/junit/%28root%29/Extended%20Core/images__mysql__replication_MySQL_replication_template_https___raw_githubusercontent_com_openshift_mysql_master_5_6_examples_replica_mysql_replica_json/

**Comment by mfojtik** [comment]
@mnagy bump

**Comment by smarterclayton** [comment]
I'm going to consider this effectively fixed unless someone knows otherwise.
