### ISSUE TITLE
OpenShift Origin V3 - 404 error when curling to influxdb service‏ 

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#5354]
I've installed and configured a OpenShift-Origin cluster on Centos7 using Docker and Kubernetes.

I'm enabling clustermetrics and followed the steps in the official tutorial: https://docs.openshift.org/latest/admin_guide/cluster_metrics.html
It all went fine and the pods are running.

```
NAME                  CLUSTER_IP       EXTERNAL_IP   PORT(S)              SELECTOR                                                   AGE
grafana               172.30.98.22     <none>        80/TCP               component=grafana,provider=fabric8                         56m
influxdb-monitoring   172.30.212.50    <none>        8086/TCP             component=influxdb-monitoring,provider=fabric8             1h
jenkins-1-centos7     172.30.208.176   <none>        8080/TCP,50000/TCP   app=jenkins-1-centos7,deploymentconfig=jenkins-1-centos7   1h
```
```
[root@ip-10-0-0-129 metrics]# oc get pods
NAME                        READY     STATUS    RESTARTS   AGE
grafana-rz42c               1/1       Running   0          23m
heapster-jd80m              1/1       Running   0          30m
influxdb-monitoring-i6l7n   1/1       Running   0          33m
```
```
[root@influxdb-monitoring-tzuri /]# /etc/init.d/influxdb start     
Setting ulimit -n 65536
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
```

I'm not very familiar with influxerdb.
I've created a route to the services. And it's possible to visit Grafana.
But I've a problem with influxdb. I get a 404. Even when I'm just curling to the service:
```
[root@ip-10-0-0-129 metrics]# curl 172.30.212.50:8086
404 page not found
```
There is also an error in Grafana (which uses influxdb):
```
influxDB Error: Couldn't find series: memory/usage_bytes_gauge
influxDB Error: Couldn't find series: memory/usage_bytes_cumulative
```

I'm able to access the influxdb container:
```
[root@influxdb-monitoring-i6l7n /]# influxdb -v
InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)
```
What could be the issue?

Logs of Heapster
```
E1023 12:57:06.983938       1 reflector.go:136] Failed to list *api.Namespace: Get https://kubernetes.default.svc/api/v1/namespaces: x509: certificate is valid for ec2-52-18-x-x.eu-west-1.compute.amazonaws.com, hostname, not kubernetes.default.svc
```
The ```oc logs name-of-pod``` returns nothing for the influxdb and grafana-pods
+ where do you have to install it? In the default project as admin, or just in a new project.

**Comment by jimmidyson** [comment]
Are you still having this problem? If so can you share `oc get rc` to see if you've created the necessary replication controllers? If you have & there are no corresponding pods being created then can you please check the output of `oc describe rc <rcName>` to see if there are clues in the rc events.
