### ISSUE TITLE
openshift/hello-openshift:latest does not work on older systems

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#5363]
On some platforms (eg, Fedora 21), the openshift/hello-openshift:latest image does not run:

    > docker run openshift/hello-openshift
    no such file or directory
    Error response from daemon: Cannot start container d830a0c9ac13e57e3765d8b3ab4089bad9137e00c7a98eec1457073c5cc057d8: [8] System error: no such file or directory

The journal doesn't tell much, even with "-D":

    docker[27514]: level=info msg="POST /v1.20/containers/5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0/start"
    docker[27514]: level=debug msg="activateDeviceIfNeeded(5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0)"
    docker[27514]: level=warning msg="exit status 1"
    docker[27514]: level=debug msg="attach: stdout: end"
    docker[27514]: level=debug msg="attach: stderr: end"
    docker[27514]: level=debug msg="[devmapper] UnmountDevice(hash=5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0)"
    docker[27514]: level=debug msg="[devmapper] Unmount(/var/lib/docker/devicemapper/mnt/5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0)"
    docker[27514]: level=debug msg="[devmapper] Unmount done"
    docker[27514]: level=debug msg="[devmapper] deactivateDevice(5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0)"
    docker[27514]: level=debug msg="[devmapper] removeDevice START(docker-253:1-786882-5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0)"
    docker[27514]: level=debug msg="[devmapper] removeDevice END(docker-253:1-786882-5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0)"
    docker[27514]: level=debug msg="[devmapper] deactivateDevice END(5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0)"
    docker[27514]: level=debug msg="[devmapper] UnmountDevice(hash=5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0) END"
    docker[27514]: level=debug msg="[devmapper] UnmountDevice(hash=5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0)"
    docker[27514]: level=debug msg="[devmapper] UnmountDevice(hash=5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0) END"
    docker[27514]: level=error msg="Error unmounting device 5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0: UnmountDevice: device not-mounted id 5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0"
    docker[27514]: level=error msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container 5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0: [8] System error: no such file or directory"
    docker[27514]: level=error msg="HTTP Error" err="Cannot start container 5c6b8abab42717bcabb0fdac30c96025eac3f4537517b04ad894e1129c2b49b0: [8] System error: no such file or directory" statusCode=404

openshift/hello-openshift:v1.0.6 works fine.

**Comment by ncdc** [comment]
Did we revert to not building it statically again? See #2579
