### ISSUE TITLE
Log layout problems in IE

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5370]
There is a newline after every line number

![ie10_-_win7__running_](https://cloud.githubusercontent.com/assets/1167259/10702938/a1af437a-799a-11e5-8166-bcbab5887bd9.png)

/cc @jwforres @benjaminapetersen @sg00dwin

**Comment by jwforres** [comment]
assigning to @benjaminapetersen for the moment, if we think its a CSS issue I an re-assign to @sg00dwin if needed

**Comment by spadgett** [comment]
I think this might be IE 10 only. I just tried on IE 11, and it looked OK.

**Comment by jwforres** [comment]
@sg00dwin this would probably be fixed by the template changes you were already making to take out those newlines
