### ISSUE TITLE
weird forbidden message when trying to access logs.

### ISSUE THREAD

**Issue by rettori** [openshift/origin#5373]
clicked view log, got error 403 message.
<img width="944" alt="1" src="https://cloud.githubusercontent.com/assets/2352755/10703510/93d89df6-799e-11e5-96be-d26d977dd70c.png">
<img width="913" alt="2" src="https://cloud.githubusercontent.com/assets/2352755/10703513/9591d50e-799e-11e5-91a3-bb87fbecb539.png">
changed url to include /console in the beginning and it worked.
<img width="690" alt="3" src="https://cloud.githubusercontent.com/assets/2352755/10703516/97903c7e-799e-11e5-876e-074584590e93.png">

**Comment by spadgett** [comment]
Same as #5264
