### ISSUE TITLE
You can submit new project form twice if you're fast enough

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5374]
We don't disable the create button on the new project form immediately since we navigate away from the page, but you can submit the form twice if you click quickly.

/cc @jwforres

**Comment by jwforres** [comment]
@spadgett assigning you for now but i'll add it to my mental list for ones I can potentially take from you

**Comment by benjaminapetersen** [comment]
I've been experiencing this lately.  Think my setup is a bit slow due to vagrant, but its pretty easy for me to double tap & get errors.
