### ISSUE TITLE
The log-scroll-top link switches to the affix position to early in the scroll

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#5375]
Link jumps to it's position:fixed outside of the log-viewer.

<img width="491" alt="affix-top-position" src="https://cloud.githubusercontent.com/assets/1874151/10704203/3aaf9220-79a3-11e5-99ae-b7924506d5bd.png">

**Comment by benjaminapetersen** [comment]
That should be easy to adjust here:

```html
    <div
      affix
      offset-top="285"
      offset-bottom="90">
```
The `offset-top` has probably just moved as we have added tabs or something.  The annoying thing about bootstrap-affix is that it'll have to be tinkered with whenever we adjust styles :neutral_face:
