### ISSUE TITLE
ImageStreamTags should allow edits to annotations

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5392]
```
$ oc annotate istag/test:v1.0.6 io.openshift.generate.job=true
Error from server: the server does not allow this method on the requested resource
```

Should allow me to set annotations.  We need to enable edit on ISTag that only mutates known fields (probably annotations, maybe one or two others).

**Comment by deads2k** [comment]
So to clarify, you want to be able to patch image stream tags that you can't create or update today that live as virtual objects underneath an imagestream with annotations stored as a separate map of maps in the is.spec?

**Comment by deads2k** [comment]
Actual the above was wrong, that would modify the annotations on the contained image, not the IST itself.  We'd have to create a parallel map of maps.

Also, why do we stomp existing annotations in the image when returning the value through an IST?

**Comment by smarterclayton** [comment]
I want edit istag to modify the annotations on the image stream tag
(because you can edit a stream), and they should overlay (not remove)
annotations coming from the underlying image.  The point of the annotation
on the ISTag is to override image annotations because they are shared.

**Comment by deads2k** [comment]
The istag doesn't have any annotations at all: https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestreamtag/rest.go#L91-L97 .  The is's tags are used to modify the image's tags: https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestreamtag/rest.go#L76-L83.

Do you want to modify the image tags, do we want to introduce a new field to track annotations for an istag, or should istags simply have the value from `stream.Spec.Tags[tag]`

**Comment by ncdc** [comment]
I would recommend having it modify `stream.spec.tags[tag].annotations`

**Comment by deads2k** [comment]
> I would recommend having it modify stream.spec.tags[tag].annotations

so an istag would start to get annotations filled in there?  Right now, an istag has no annotations

**Comment by ncdc** [comment]
You mean this? https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestreamtag/rest.go#L74-L84

**Comment by ncdc** [comment]
Which does what Clayton said he wanted:

> I want edit istag to modify the annotations on the image stream tag
(because you can edit a stream), and they should overlay (not remove)
annotations coming from the underlying image.

**Comment by deads2k** [comment]
> You mean this? https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestreamtag/rest.go#L74-L84

It doesn't.  That only adds them to the `image` contained inside the `istag`.  It updates `.image.metadata.annotations`, not `.metadata.annotations`.

**Comment by ncdc** [comment]
I'm pretty sure this is what @smarterclayton is asking for

**Comment by deads2k** [comment]
> I'm pretty sure this is what @smarterclayton is asking for

That would mean the `oc annotate` would be modifying a different field for `istags`.  It would mean that instead of annotate modifying annotations, it would be modifying a field that looks like annotation, but is in a different spot.  That wouldn't be what I would expect as a user.

`oc annotate` should modify the object such that `.metadata.annotations` gets changed.

**Comment by smarterclayton** [comment]
oc annotate should be modifying .metadata.annatotions.  For an istag, that
is a composite field that is stream tag annotations + image annotations.
On an edit, those should be set on the istag.

**Comment by ncdc** [comment]
The problem is that (as you already pointed out) `ImageStreamTag` is a virtual resource. There isn't anything to modify other than stream spec tag annotations or image annotations.

**Comment by deads2k** [comment]
> oc annotate should be modifying .metadata.annatotions.  For an istag, that
> is a composite field that is stream tag annotations + image annotations.

Ok, we don't do this currently, so that's a bug I can fix.

**Comment by ncdc** [comment]
@deads2k what bug are you referring to?

**Comment by smarterclayton** [comment]
If there is a quick fix I'd like it for 1.1 but if not we can live until
1.1.1

On Oct 26, 2015, at 11:31 AM, David Eads <notifications@github.com> wrote:

oc annotate should be modifying .metadata.annatotions. For an istag, that
is a composite field that is stream tag annotations + image annotations.

Ok, we don't do this currently, so that's a bug I can fix.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5392#issuecomment-151175589>.

**Comment by deads2k** [comment]
> @deads2k what bug are you referring to?

`istags` don't have any annotations.

**Comment by ncdc** [comment]
What are you going to do - merge the image and spec tag annotations into the virtual `ISTag`'s annotations?

**Comment by deads2k** [comment]
> What are you going to do - merge the image and spec tag annotations into the virtual ISTag's annotations?

I was just planning to represent the ones in the imagestream.spec.tags[foo] field.  That way its only the overrides.  That felt cleaner.

**Comment by smarterclayton** [comment]
Yes that's fine.
