### ISSUE TITLE
See whether "No <whatever> to show" messages look better outside of the tables

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#5412]
Today we show the tables with a message in them.  See whether it would look better to hide the table completely when there are none.  Should check what the patternfly recommendation is for this.

**Comment by spadgett** [comment]
Patternfly empty state for tables is on this page:

https://www.patternfly.org/patterns/table-view/

**Comment by benjaminapetersen** [comment]
@MDeMariaRH this is a good one to hit.  I'll create a new issue in origin-web-console & reference this.

**Comment by spadgett** [comment]
We should look at using the empty state styles we use elsewhere for this. One example:

https://github.com/openshift/origin-web-console/blob/a08db604494995962b9cc717c2d2d0703c43b865/app/views/browse/build-config.html#L78-L95

**Comment by spadgett** [comment]
See also https://www.patternfly.org/pattern-library/communication/empty-state/#_

(Although the styles we use predate the pattern, so they might be slightly different.)

**Comment by spadgett** [comment]
Closing in favor of https://github.com/openshift/origin-web-console/issues/109
