### ISSUE TITLE
Improve perf on build and dep config pages by only requesting builds/deps for that config

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#5413]
We should try using watch with the labelFilter query param set so that we only watch the relevant things.  Its unclear if watch behavior with a filter set would cause weird behavior around missing certain events, what happens when someone adds/removes the label we are filtering on?

**Comment by spadgett** [comment]
Tracked by https://trello.com/c/zxALvq4S ?

**Comment by jwforres** [comment]
yes
