### ISSUE TITLE
Can't get logs for a crashlooping pod

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#5417]
If my pod keeps crashing (in this case due to external dependency missing) it gets put into `CrashLoopBackOff` state. The problem then is that you can't get logs in that state so it's hard to figure out why it's crashing.

```
# oc get pods
NAME                          READY     STATUS             RESTARTS   AGE
logging-kibana-1-rsjx9        1/2       CrashLoopBackOff   15         3d
# oc logs logging-kibana-1-rsjx9 kibana
Error from server: Internal error occurred: Pod "logging-kibana-1-rsjx9" in namespace "logging" : pod is not in 'Running', 'Succeeded' or 'Failed' state - State: "Pending"
```

I think it would be better if `CrashLoopBackOff` state were counted the same as `Failed` for log access purposes.

**Comment by deads2k** [comment]
This changed at some point.  I'm on a much older build at home, but I can check crash looping logs.

**Comment by kargakis** [comment]
Is `docker logs` working?

**Comment by sosiouxme** [comment]
I should mention the context: This is from our latest internal OSE 3.1 build. So reasonably close to master.

Yes, docker logs works. Of course the ordinary user can only get to them via the API.

**Comment by kargakis** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/16507

**Comment by kargakis** [comment]
We need to cherry-pick https://github.com/kubernetes/kubernetes/pull/15799 for this
