### ISSUE TITLE
Our details pane help text mentions pods, but you cant select a pod from the overview anymore

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#5425]
![details_pod_text](https://cloud.githubusercontent.com/assets/1467629/10766167/8739ef76-7cac-11e5-990d-e5152a7172b9.png)

**Comment by jwforres** [comment]
@spadgett

**Comment by spadgett** [comment]
This text isn't meant to be a list of what you can click on, just helpful information for new users. Pods are so important I think we should still leave the description. Maybe we can separate the help text in some way.

You can also click on monopods :)

**Comment by jwforres** [comment]
Yeah i think its because it immediately follows the "Select an object to see more details" that it bothered me

**Comment by jwforres** [comment]
no one else has really complained about this and it is a good explanation
