### ISSUE TITLE
Error opening logs in UI for pod with two containers

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5428]
> WebSocket connection to 'wss://openshiftdev.local:8443/api/v1/namespaces/two/pods/doublecontainers/log?follow=true&access_token=m0wNOSFpF6khQ2fUh0Ezjlv2HcpD4Ww805l6Yg0dj78' failed: Error during WebSocket handshake: Unexpected response code: 400

No error is surfaced in the UI either, just "connection closed" in muted text below the logs.

![screen shot 2015-10-27 at 1 31 54 pm](https://cloud.githubusercontent.com/assets/1167259/10766767/60664040-7caf-11e5-8173-027557a51102.png)

/cc @benjaminapetersen @jwforres

**Comment by benjaminapetersen** [comment]
assign to me, ill take it

**Comment by spadgett** [comment]
@benjaminapetersen you can reproduce with

```
oc create -n <project-name> -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/pods/pod_with_two_containers.json 
```

**Comment by benjaminapetersen** [comment]
@spadgett thanks.  I'll ping QE on the Trello card to add tests for this use case as well.

**Comment by benjaminapetersen** [comment]
Fixed w/PR this morning.
