### ISSUE TITLE
Metrics and Terminal tabs handle multiple containers differently

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5429]
Metrics shows a dropdown to pick a container. Terminal opens a terminal to each container. I'm not sure how well that would scale if you had many containers. We should try to be consistent between these two tabs and Logs (in our fix for #5428).

/cc @jwforres @benjaminapetersen @stefwalter

**Comment by liggitt** [comment]
For multiple containers, we should prompt. This goes for logs, metrics, and terminal

**Comment by benjaminapetersen** [comment]
Agree.  & working on the fix for logs now.

**Comment by jwforres** [comment]
we now have a container selector for terminal
