### ISSUE TITLE
oc new-build warning is unclear when unable to find a Dockerfile

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin#5434]
Trying to create a buildconfig that uses a dockerfile
```
oc new-build https://github.com/openshift/origin-metrics.git --strategy=docker -o json 
error: No language matched the source repository
```
Should provide a warning that it cant find a dockerfile.  What might also be useful is if there was a flag which allowed the command to assume the file was there so I could go and edit it afterwards (e.g. because i cant use oc to define the context-dir)

**Comment by bparees** [comment]
will fix the error message, adding an "ignore errors" flag is a deeper exercise i'm not ready to get into.
