### ISSUE TITLE
Flake in prune images end to end

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5450]
```
W1027 20:42:11.397262   29972 cmd.go:200] -p POD is DEPRECATED and will be removed in a future version. Use exec POD instead.
!!! Error in hack/../test/end-to-end/core.sh:267
	'oadm prune images --keep-younger-than=0 --keep-tag-revisions=1 --confirm &>${LOG_DIR}/prune-images.log' exited with status 1
Call stack:
	1: hack/../test/end-to-end/core.sh:267 main(...)
Exiting with status 1
```

**Comment by deads2k** [comment]
As a starting point, can you figure out how to get logs from this thing?  Jenkins doesn't seem to be gathering artifacts on failure anymore.

**Comment by smarterclayton** [comment]
I think I've seen rsync errors at the end of runs - that might be a good place to look.

**Comment by miminar** [comment]
I guess I started reproducing too late. The oldest build jenkins remembers is 10 days old. I've checked all 199 failed builds from its available history and there's no such build failing with `oadm prune images`.

**Comment by miminar** [comment]
The good news is that the collection of logs works in recent builds.

**Comment by miminar** [comment]
Newest occurence in [test 7752](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7752/consoleFull).

**Comment by smarterclayton** [comment]
Just failed https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/test_pull_requests_origin_integration/281/console

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/295/console
