### ISSUE TITLE
Node selectors in namespaces break local manifest files

### ISSUE THREAD

**Issue by mrosic** [openshift/origin#5451]
If I edit the default namespace and give it a selector like this:
"oc edit ns/default"
metadata:
  annotations:
    openshift.io/node-selector: role=testing

then the fluentd-elasticsearch pod described in https://docs.openshift.org/latest/admin_guide/aggregate_logging.html won't start. 
"oc get po" won't show the pod at all.
"oc get po -w" will spam me with:
"fluentd-elasticsearch-mydomain.com   0/1       Pending   0         0s"

Everything in my setup is exactly as described in https://docs.openshift.org/latest/admin_guide/aggregate_logging.htm
But as soon as I add a node selector with "oc edit ns/default" the fluentd-pods refuse to start. If I remove the node selector from the namespace definition the pods start up and everthing is fine. 

It does not make any difference what node selector is used, any entry should be enough to show the described behavoir.

**Comment by liggitt** [comment]
Might be related to https://github.com/kubernetes/kubernetes/pull/15983 which we need to cherry-pick...

**Comment by smarterclayton** [comment]
cherry-picking merged commits is now much easier...
