### ISSUE TITLE
colorize log display in webui, command line

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#5453]
From @thoraxe : 
I don't know how easy or hard it is right now, but perhaps there is some kind
of web plugin that we can use to "colorize" the log. For blogs and showing code
you have things like GeSHi (http://qbnz.com/highlighter/) and I'm wondering if
maybe something like that would be able to be incorporated some day.

For OpenShift "go" messages we might want to have a syntax highlighting scheme,
and this might be usable in the system logs as well (journalctl)...

Spawned from https://bugzilla.redhat.com/show_bug.cgi?id=1275905

**Comment by jwforres** [comment]
cc @fabianofranz for the CLI part

**Comment by benjaminapetersen** [comment]
I spent some time looking into [Prism](http://prismjs.com/) and a couple others earlier on, before we decided on a simpler scheme.  Agree, colorized would be a good next step.

**Comment by jwforres** [comment]
Moving to trello https://trello.com/c/goZPKVEm

**Comment by pmourelle** [comment]
So... what happened to this after being moved to trello? I guess it wasn't continued as now I'm looking at an awful console :P 
![image](https://user-images.githubusercontent.com/844554/102522808-7ac4c800-4075-11eb-816f-978e48ca515d.png)
Is there any advance?
