### ISSUE TITLE
Pod with a pending state that is empty has 'log complete' message

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#5456]
<img width="420" alt="pod-pending" src="https://cloud.githubusercontent.com/assets/1874151/10792273/69b2f02c-7d62-11e5-89b0-82a90bec90c4.png">

**Comment by benjaminapetersen** [comment]
Per @liggitt comment on previous issue, "mixing text into the indicator at the bottom could also be where we show status of the log-following operation" :
"Waiting for pod to start..."
"Waiting for logs..."
"Logs through 5:03pm..."
"Showing logs through 5:03pm. Connection interrupted, reconnect"

**Comment by benjaminapetersen** [comment]
I think in "pending" state the pod doesn't actually exist yet, so the connection is immediately closed. Perhaps the status needs to be tested prior to making the connection to ensure this doesn't happen.

**Comment by benjaminapetersen** [comment]
(And I think this is a good opportunity to push the status stuff up into the directive)

**Comment by jwforres** [comment]
Fixed
