### ISSUE TITLE
webconsole and describe show different webhook hosts

### ISSUE THREAD

**Issue by bparees** [openshift/origin#5460]
with an ec2 instance, the webconsole is showing the public hostname and the describe command is showing the internal ip.  These should be the same.

**Comment by liggitt** [comment]
webhooks should always show external

**Comment by liggitt** [comment]
well, hrmm... I could see describe using whatever host it was currently talking to the server on

**Comment by jwforres** [comment]
weird to show both when different?

**Comment by bparees** [comment]
showing both feels more confusing for the user.

it seems like the public host (as defined in the master domain config) should always be a reasonable choice..       @liggitt are you thinking of a scenario where it wouldn't be?

**Comment by liggitt** [comment]
The public host certainly feels more reasonable for "webhooks". Trying to think of places you might run this where the public host wouldn't be resolveable... can't really think of any. Thing is, I'm pretty sure the CLI doesn't know the "public" hostname, only the hostname it is currently using to talk to the server.

**Comment by php-coder** [comment]
>Thing is, I'm pretty sure the CLI doesn't know the "public" hostname, only the hostname it is currently using to talk to the server.

Yes, this is why this ticket is still open -- I cannot find a way how to get the public host parameter on the client.

**Comment by bparees** [comment]
@liggitt do we need to add an api that lets the CLI ask the master what it's public hostname is?

**Comment by php-coder** [comment]
@liggitt I would be grateful if you find a minute and take a look at this issue. Thanks!

**Comment by bparees** [comment]
@deads2k @liggitt has anything progress on this front that would let us do a better job w/ oc describe?  I guess the issue is the client is building a url that points to the api server and it should be pointing to the public host of the api server but in some cases it instead uses the private ip (because the client is talking to the api server on the private ip? (logged in via that ip)?)

**Comment by liggitt** [comment]
not really... the client can only build the URL using the address for the server it knows about

**Comment by bparees** [comment]
closing as can't fix.
