### ISSUE TITLE
Test flake: missing built go-bindata

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#5461]
```
hack/test-assets.sh: line 29: Godeps/_workspace/bin/go-bindata: No such file or directory
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6295/console

Maybe go-bindata failed to compile? First time I have seen this happen.

**Comment by smarterclayton** [comment]
Possible.

**Comment by jwforres** [comment]
@smarterclayton This happened several times yesterday, has anyone update godeps recently our changed go versions?

The weird thing is that some of the asset PRs were able to merge OK

**Comment by smarterclayton** [comment]
Flaking all over the place in master now 

```
hack/test-assets.sh: line 29: Godeps/_workspace/bin/go-bindata: No such file or directory
Build step 'Execute shell' marked build as failure
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6416/console

**Comment by smarterclayton** [comment]
We really, really, really need to ensure install-assets.sh fails early

```
bower angular-animate#1.3.8                 resolved git://github.com/angular/bower-angular-animate.git#1.3.8
bower uri.js#1.14.1                          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/medialize/URI.js.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.130]: errno=Connection timed out

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection timed out
~
```

**Comment by smarterclayton** [comment]
@mfojtik you've been tagged as the perpetrator in the refactor of install-assets that results in it eating errors (78e5298e4e5e) - so you get the task of fixing it to fail correctly and exit out with 1, rather than 0.

**Comment by liggitt** [comment]
not sure... `cmd "false"` exits correctly... wonder if bower is eating an error code

**Comment by smarterclayton** [comment]
Does bower have a "tolerant" mode?

**Comment by liggitt** [comment]
the error is pulling down and extracting the hawtio/openshift-jvm file:
```
[install-assets] mkdir -p openshift-jvm
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
~
```

**Comment by liggitt** [comment]
pretty sure whatever is calling install-assets.sh isn't doing anything with non-zero return codes... the tar error above definitely exits the script with a non-zero return code

**Comment by smarterclayton** [comment]
I blame dan.

**Comment by jwforres** [comment]
i will check vagrant-openshift and see what it is doing

**Comment by jwforres** [comment]
Yep blame me (and dan cause he reviewed it),  vagrant openshift install-asset-base-dependencies stuff is missing a set -e, and a popd runs after hack/install-assets so it gets a zero return code

**Comment by jwforres** [comment]
https://github.com/openshift/vagrant-openshift/pull/349

**Comment by jwforres** [comment]
ok vagrant is updated on jenkins so we should fail fast now when install-assets bombs, so we should never hit this error now
