### ISSUE TITLE
Missing field selector conversions

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5462]
https://github.com/kubernetes/kubernetes/pull/15766 added field selectors for namespace to several objects, but did not add conversions for those field selectors to api/v1/conversion.go#AddFieldLabelConversionFunc.

I'm pretty sure that means the new selectors aren't usable. Please add those conversions, and add tests for using the selectors.

**Comment by miminar** [comment]
@liggitt What about `v1beta3`? I believe it should be added there as well, shouldn't it?

**Comment by liggitt** [comment]
yes, v1beta3... I actually meant to open this issue in the k8s repo, but we have work to do as well

**Comment by miminar** [comment]
Upstream fix [#16509](https://github.com/kubernetes/kubernetes/pull/16509) merged. Will be fixed in next rebase.

**Comment by liggitt** [comment]
by which we mean the next rebase

**Comment by liggitt** [comment]
Picked up in https://github.com/openshift/origin/pull/6947/
