### ISSUE TITLE
No error when fail to get build logs in UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5468]
For old builds, there is no error when we fail to get the build log. The web console displays an empty log.

/cc @jwforres @benjaminapetersen

**Comment by jwforres** [comment]
Second issue is a duplicate of https://github.com/openshift/origin/issues/5456

**Comment by benjaminapetersen** [comment]
@jwforres @spadgett I believe this one is done per the above merged PR.

**Comment by jwforres** [comment]
@benjaminapetersen nope its still an issue, the websocket isn't returning an error like it should and is allow the connection to be upgraded

**Comment by benjaminapetersen** [comment]
aaah. thats right. my bad.  was just looking at tpl and seeing changes already.
