### ISSUE TITLE
Bandwidth limit support.

### ISSUE THREAD

**Issue by caizixian** [openshift/origin#548]
Add bandwidth limit support can prevent one container use up all the out/in bandwidth.
Maybe statistics per container is also useful to show how much bandwidth a container used in every month(like Quota:500GB In:10GB Out:20GB Remain:470GB).

**Comment by pweil-** [comment]
Please see https://docs.openshift.org/latest/admin_guide/managing_pods.html#admin-guide-manage-pods-limit-bandwidth
