### ISSUE TITLE
Kube v1beta3 fuzzer tests are missing.

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5483]
At some point we lost the `v1beta3` fuzzer tests for the Kube types (see https://github.com/kargakis/origin/commit/cd6db54936bc56bfce151752d38d64dad0508f63#commitcomment-14046474).  We must have these and we need a run before we merge https://github.com/openshift/origin/pull/5169 which will disable them.

@pweil- @pmorie 
@kargakis There's only a few of us who've seen behind the curtain, can you take a look?

**Comment by kargakis** [comment]
Looking..

**Comment by deads2k** [comment]
`p0` per @liggitt and @smarterclayton

**Comment by pweil-** [comment]
@pmorie and I worked through the issue for his disabling last night.  That part should be ok now.
