### ISSUE TITLE
Attachable pod discovery should use a condition

### ISSUE THREAD

**Issue by fabianofranz** [openshift/origin#5484]
The `AttachablePodForObject` logic in the client factory (both origin and upstream) should use a condition in upstream `pkg/client/conditions.go` instead of infinite looping and waiting with `time.Sleep`.

Follow-up of https://github.com/openshift/origin/pull/5271

**Comment by fabianofranz** [comment]
@liggitt techdebt, I'd say P2 and assign to me.

**Comment by smarterclayton** [comment]
Also the message it prints really sucks for user experience - it should be a one time message printed to stderr at best, but I'm tempted to say it should output nothing (and just wait)
