### ISSUE TITLE
Overview tab: show that error occurred and provide quick access to logs

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#5487]
I'm trying to build new app and it's fails:

![failed-deployment](https://cloud.githubusercontent.com/assets/87088/10821298/f60f7d0c-7e51-11e5-87b3-4d73ce720188.png)

On overview I only see that I have 0 pods and that's all. No indication that error occurred, no useful links for logs. As a user I want to know at least that there is an error.

```
$ oc status
In project OpenShift 3 Sample (test) on server https://10.0.2.15:8443

service/database - 172.30.125.32:5434 -> 3306
  dc/database deploys docker.io/openshift/mysql-55-centos7:latest 
    #1 deployment failed 31 minutes ago

service/frontend - 172.30.83.190:5432 -> 8080
  dc/frontend deploys istag/origin-ruby-sample:latest <-
    builds https://github.com/openshift/ruby-hello-world.git with test/ruby-20-centos7:latest through bc/ruby-sample-build 
    #1 deployment failed 28 minutes ago
...
$ oc get pods
NAME                        READY     STATUS      RESTARTS   AGE
database-1-deploy           0/1       Error       0          31m
database-1-prehook          0/1       Completed   0          31m
frontend-1-deploy           0/1       Error       0          28m
ruby-sample-build-1-build   0/1       Completed   0          31m
```

**Comment by jwforres** [comment]
@spadgett we should probably indicate on the deployment if its a failed deployment

**Comment by spadgett** [comment]
#5856 adds deployment logs to the UI.

**Comment by spadgett** [comment]
@php-coder I've added a failed message to an overview. There's a link to the deployment, which now has a logs tab. OK to close this issue?

**Comment by php-coder** [comment]
@spadgett Thank you, now it looks more informative!

>There's a link to the deployment, which now has a logs tab.

Where is this link? `#10`? If I click on the `FAILED` will it open the logs?

>OK to close this issue?

Yes, I'm closing it.

Thanks!
