### ISSUE TITLE
One way attach to a pod (stdin only) doesn't close when stdin is EOF

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5507]
Prior to the last rebase, binary builds were closing normally when the output was completed streaming to the server.  Now, in master (1.0.7) I'm seeing the client exec call stay open even after EOF is read from stdin

Binary build flow:

1. Client connects to server, body is a tar stream
2. Server starts a pod, waits for it to be running
3. Server attaches to the pod with stdin only, provides request body as input
4. Binary is streamed from client to server, and server to pod.
5. Exec client keeps running until the pod terminates

This is not the expected behavior - are we ignoring EOF in the stream code now?

**Comment by smarterclayton** [comment]
p1 because i suspect this is a regression in exec

**Comment by liggitt** [comment]
@ncdc are all the upstream fixes in origin at this point?

**Comment by smarterclayton** [comment]
Repro:

    $ oc new-build openshift/ruby-20-centos7 --binary --name ruby
    $ oc start-build ruby --from-dir test/extended/fixtures/test-build-app/

Build hangs until the pod completes.  Prior to rebase (or very recently) it would terminate immediately.

**Comment by smarterclayton** [comment]
Do i need to specify an exec protocol?

**Comment by ncdc** [comment]
Bisect in progress...

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/origin_extended/220/ was
the last pass - it was f577df2 and it had binary builds in it

**Comment by ncdc** [comment]
v1.0.7 is good. working past that now

**Comment by ncdc** [comment]
Nevermind, 1.0.7 doesn't seem to work. Still trying to isolate the bad commit.

**Comment by ncdc** [comment]
I finally have a small isolated test I can run and reproduce the issue. Still digging.
