### ISSUE TITLE
Check default resync periods

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5509]
Several controllers have quite short resync periods:
```
		NodeSyncPeriod:                    10 * time.Second,
		ResourceQuotaSyncPeriod:           10 * time.Second,
		PVClaimBinderSyncPeriod:           10 * time.Second,
		HorizontalPodAutoscalerSyncPeriod: 30 * time.Second,
		DeploymentControllerSyncPeriod:    30 * time.Second,
```

@smarterclayton, did we need to lengthen any of these?

**Comment by smarterclayton** [comment]
Dear god yes.

**Comment by smarterclayton** [comment]
Maybe not node sync - that's something different.

**Comment by pweil-** [comment]
Already changed upstream in the defaults for CMServer:
```
ResourceQuotaSyncPeriod:           unversioned.Duration{5 * time.Minute},
PVClaimBinderSyncPeriod:           unversioned.Duration{10 * time.Minute},
```

Do we still want to change these?
```
HorizontalPodAutoscalerSyncPeriod: unversioned.Duration{30 * time.Second},
DeploymentControllerSyncPeriod:    unversioned.Duration{30 * time.Second},
```

**Comment by smarterclayton** [comment]
We don't use deployment controller yet, but HPA controls how fast scaling
is tested.  Do we need an upstream patch for those intervals or is that
checked into master?

**Comment by pweil-** [comment]
already in master as the default for `NewCMServer()` calls

**Comment by pweil-** [comment]
Nothing left to do here.  Closing.
