### ISSUE TITLE
Flake in deployment now

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5512]
```
[INFO] Streaming the logs from a deployment twice...
deploymentconfig "failing-dc" created

[FAIL] !!!!! Test Failed !!!!
```

https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3843/console

@kargakis @ironcladlou is this your changes?

**Comment by kargakis** [comment]
This is the negative test I added in #5393
