### ISSUE TITLE
Install Script

### ISSUE THREAD

**Issue by brettneese** [openshift/origin#5515]
Is there any particular reason that the install script has not been updated for Origin 3, and if there are plans to update it, what is the timeline on that? 

I'll be honest - it seems as easy at first but our team has had a heck of a time just getting this thing going, it's very confusing and there seem to be conflicting directions all around. I even subscribed to the trial just to get access to the install script for Enterprise 3 but we do not nor plan to have RHEL boxes.

**Comment by sdodson** [comment]
@brettneese Can you clarify which install script you're talking about? Unfortunately we have many installation methods.

The advanced installation method covered at the following link is the route I'd go for a production multi-host environment. It should work with origin and centos 7.1 just fine. Let me know if you find otherwise.

https://docs.openshift.org/latest/install_config/install/advanced_install.html

**Comment by brettneese** [comment]
This one. https://install.openshift.com/

**Comment by sdodson** [comment]
Ok, right now the quick installer only works for OSE and requires access to RHEL channels. If you don't plan to run RHEL If you want to deploy a multi host environment I suggest using the advanced installer for origin I linked to in my last comment.

If you're only interested in running origin on a single host you can use one of the methods described on this page https://docs.openshift.org/latest/getting_started/administrators.html

**Comment by brettneese** [comment]
Are there plans to update it, or are those going to be the installation methods going forward?

We've had a lot of trouble getting it running on our machines; can document in other specific issues if you'd like.

**Comment by sdodson** [comment]
install.openshift.com for v3 stuff is OSE v3 only with no immediate plans to fix it up for origin. However it's really just a wrapper around the advanced installer I've linked to above. If you run into problems installing origin using the advanced installer and origin please let us know. Probably best to file those as issues at https://github.com/openshift/openshift-ansible

**Comment by brettneese** [comment]
Got it. Thanks!
