### ISSUE TITLE
Cluster-reader cannot list PersistentVolumes

### ISSUE THREAD

**Issue by simon3z** [openshift/origin#5534]
It seems that at this time `cluster-reader` cannlot list all persistentvolumes in the cluster:

    HTTP status code 403, User "system:serviceaccount:default:manageiq" cannot list all persistentvolumes in the cluster

cc @deads2k (let me know if you need more info but it seems easy to reproduce at the moment)

**Comment by liggitt** [comment]
Did you grant that role cluster-wide?
```
oadm policy add-cluster-role-to-user cluster-reader system:serviceaccount:default:manageiq
```

If you only granted it within a namespace (`add-role-to-user`), it won't let you read resources outside of namespaces, like persistent volumes

**Comment by deads2k** [comment]
@liggitt its not present in here at all: https://github.com/openshift/origin/blob/master/pkg/authorization/api/types.go  Looks like a bug.
