### ISSUE TITLE
Need extended test for Jobs

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5538]
Most job controller functionality is tested upstream, but origin has more restrictive policies by default.  We should have an extended test show that a user with ordinary permissions can effectively use jobs and that the controller itself works with all defaults.

@soltysh I don't remember this going in, but let me know if this already exist and I'll close.

**Comment by soltysh** [comment]
Actually @sdminonne is working on it, will sync with him on Monday about the progress.

**Comment by deads2k** [comment]
Blocked on https://github.com/openshift/origin/pull/5580
