### ISSUE TITLE
Some log content doesn't wrap in Firefox

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5542]
This only happens with some logs. I'm guessing it's long, unbroken words, but I'm not positive.

![screen shot 2015-10-30 at 1 37 10 pm](https://cloud.githubusercontent.com/assets/1167259/10853199/5e41dce4-7f0b-11e5-9381-2f99f81dcff1.png)

/cc @jwforres This appears to be a previously existing bug, not caused by #5537.

**Comment by spadgett** [comment]
/cc @benjaminapetersen 

This isn't a problem in Chrome.

**Comment by jwforres** [comment]
we probably need to switch it from white-space: pre to white-space: pre-wrap

**Comment by spadgett** [comment]
Looks like it already is pre-wrap unfortunately.

**Comment by spadgett** [comment]
@sg00dwin Found a long, unbreakable word in the log. Let me know if you need help reproducing.

**Comment by spadgett** [comment]
This is fixed with Steve's changes.
