### ISSUE TITLE
NFS persistent storage from NetApp applicances

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/origin#5545]
There seems to be a bug when NFS exports are being used as PVs that come from NetApp appliances. Basically containers create files on the PV and everything they create ends up being owned by nobody.nobody regardless of the export having rw,no_root_squash as options. 
https://access.redhat.com/solutions/33455 - this describes the issue almost to the t
https://library.netapp.com/ecmdocs/ECMP1196993/html/GUID-24367A9F-E17B-4725-ADC1-02D86F56F78E.html - provides a possible solution to the problem.

I cannot test this until Monday when the NetApp admins are back at work, but will update this as soon as I have tested it. 

One thing that is coming to mind though is that the option allows numeric UIDs and the container UIDs are alpha-numeric, so I may or may not be still SOL.
@markturansky @pmorie

**Comment by bparees** [comment]
This behavior causes a particular problem for our postgres image because it expects to be the owner of files it creates.

**Comment by ebalsumgo** [comment]
I expect it will cause the same issue with anything that expects ownership (i think mongo has the same issue off the top of my head).

Also, if this does turn out to be a true fix, I would highly suggest adding a note to the documentation for persistent storage as it is bound to bite other NetApp users as well.

**Comment by ebalsumgo** [comment]
Something to note here. On NetApp the option above is per controller rather than per export, which means that your entire controller will allow the behavior described in the KB, this may or may not be a problem in some institutions. For example, in ours it is a problem :/

**Comment by swagiaal** [comment]
@ebalsumgo have you tried the solutions you mentioned ?

@bparees does Postgres expect to be the owner of files it creates or just have RW access to them ?

**Comment by ebalsumgo** [comment]
@swagiaal i have and its a non starter unfortunatley due to the fact that the option I metion in the netapp KB is only available when you export with AUTH_SYSTEM which requires a NIS server to be running... which in turn causes all sorts of other issues. So currently exploring what it would look like with using NetApp and NFSv3 with @pmorie and @rjhowe

**Comment by bparees** [comment]
> @bparees does Postgres expect to be the owner of files it creates or just have RW access to them ?

@swagiaal it requires ownership, unfortunately.

**Comment by swagiaal** [comment]
Hmm.. it does not seem like there is much we can do here other than provide a warning in the documentation as @ebalsumgo suggested. It seems like NetApp is forcing `all_squash` when there is no `AUTH_SYSTEM`.

**Comment by ebalsumgo** [comment]
This is the case if you want nfs v4, I am in the process of testing out nfs v3 on the netapp and will report how that goes


-B

-- Please excuse spelling and grammar errors, this has been sent from my iPhone/iPad

**Comment by swagiaal** [comment]
@ebalsumgo thanks.. I'll wait for your results

**Comment by ebalsumgo** [comment]
I just finally tested this with NFS v3 and it works like a charm

**Comment by swagiaal** [comment]
@ebalsumgo so how did you get it working ? Does NetApp allow you to disable all_squash without AUTH_SYSTEM with NFS v3 ?

**Comment by ebalsumgo** [comment]
@swagiaal yes, you can export without all_squash,rw the issues the NetApp has is when you mount the volumes NFSv4 vs NFSv3, when you are doing NFSv4 the only way to get OSE to work is to run the options from the original KB article I posted which requires that you switch to AUTH_SYSTEM, if you instead mount as NFSv3 everything works just peachy as v3 doesnt really care about id mapping and such.

**Comment by swagiaal** [comment]
@ebalsumgo I incorporated your findings into my docs PR https://github.com/openshift/openshift-docs/pull/1133. Thank you for the info!

**Comment by evenit** [comment]
Ain't there a limitation with SELinux ? In the documentation it is stated that NFSv4 is mandatory due to the fact that it implements SELinux labeling : https://docs.openshift.org/latest/install_config/persistent_storage/persistent_storage_nfs.html.

However it seems that extended attributes are also implemented in NFSv3 (http://lwn.net/Articles/392944/). Is that enough to get SELinux labeling working ?

**Comment by evenit** [comment]
@ebalsumgo How did you force NFSv3 ? Is there an attribute to set at the Persistent Volume level ? Or did you remove NFSv4 support on your filer ?

**Comment by evenit** [comment]
Ok, so I reproduced with NFSv3 and it works great. To answer my own questions:

 - Forcing NFSv3 is done by setting "Defaultvers=3" in /etc/nfsmount.conf
 - NFSv3 is able to label files through genfs rather than xattr

**Comment by ebalsumgo** [comment]
@evenit keep in mind there are all sorts of issues currently with the volumes getting recycled so you may have a bunch of unscrubbed and unusable, refer to: https://github.com/openshift/origin/pull/5792 and more importantly https://github.com/openshift/origin/pull/5847

**Comment by swagiaal** [comment]
This issue can now be closed... It does not look like I have permissions to close though.
