### ISSUE TITLE
json deserialization into int64 can fail using patch, UnstructuredJSONScheme, or json.Unmarshal

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5557]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6517/consoleText
```
E1030 21:17:44.127691   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:44.297969   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:44.468171   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:44.640398   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:44.844421   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:45.016131   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:45.186275   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:45.356693   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:45.531035   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:45.701843   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:45.872073   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:46.041894   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:46.211810   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:46.381676   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:46.551402   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:46.720659   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:46.891358   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:47.061610   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
E1030 21:17:47.232388   25818 errors.go:62] apiserver received an error that is not an unversioned.Status: json: cannot unmarshal number 1.00009e+09 into Go value of type int64
2015-10-30 21:17:47.240892 N | osutil: received terminated signal, shutting down...
```

**Comment by smarterclayton** [comment]
Might just be 15651

**Comment by smarterclayton** [comment]
Aka #5536

**Comment by danmcp** [comment]
@smarterclayton Please provide the text of the problem in this issue.

**Comment by smarterclayton** [comment]
Happened again https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6818/console

**Comment by pweil-** [comment]
@smarterclayton 

I can reproduce this locally using a template and the new-app command.  In my case it appears that when the processedTemplate is retrieved it is being sent back to the client as a floating point number which then cannot unmarshal.

"securityContext":{"supplementalGroups":[1.000030003e+09]}

template and request/response log: https://gist.github.com/pweil-/1cb8cf06e19f2cc0a102

I found this issue https://github.com/golang/go/issues/5562

cc @pmorie

**Comment by pweil-** [comment]
@liggitt - word on the street is you are a Marshal expert ^

**Comment by liggitt** [comment]
I am skilled in marshal arts... will take a look asap

**Comment by liggitt** [comment]
is this actually p2? if so, I'll take a look later

**Comment by pmorie** [comment]
@liggitt @pweil- Seems like this should be a p1 or p0 to me...

**Comment by pmorie** [comment]
Looks like `decoder.UseNumber()` is what we want:

http://play.golang.org/p/Zvcu2BMBJf

**Comment by smarterclayton** [comment]
p1 because it can wedge the server, unless we eliminate the possibility that it doesn't happen again.

**Comment by pmorie** [comment]
Actually, the problem is that the encoder is producing the wrong output.  From @pweil-'s gist, the response from the API server from a POST is wrong.

**Comment by liggitt** [comment]
I can recreate this in process template, might be related to RawExtension

**Comment by liggitt** [comment]
Issue is this line:
```
runtime.UnstructuredJSONScheme.Decode(obj.RawJSON)
```

which decodes all numbers as float64

**Comment by smarterclayton** [comment]
Go JSON doesn't understand int64, right?

**Comment by liggitt** [comment]
When deserializing to an unstructured map, it either puts all numbers into float64 (today's behavior), or you can set UseNumber() on the json decoder, which stores all numbers internally as strings, and by default breaks round tripping by outputting all numbers as quoted strings.

**Comment by pmorie** [comment]
The root issue is that the unstructured serialization doesn't have the type information to make the right serialization choices.  It's tough to imagine a good way to solve this, unless you basically look up the type information by picking through the template output (which might not even be an object).

**Comment by smarterclayton** [comment]
We can normalize all float64 into their compact representation (1e3 ->
1000)?  Or is the case here that we cannot?

On Nov 6, 2015, at 4:38 PM, Jordan Liggitt <notifications@github.com> wrote:

When deserializing to an unstructured map, it either puts all numbers into
float64 (today's behavior), or you can set UseNumber() on the json decoder,
which stores all numbers internally as strings, and by default breaks round
tripping by outputting all numbers as quoted strings.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5557#issuecomment-154549479>.

**Comment by liggitt** [comment]
Doing anything to all the number values requires walking the JSON tree. If I was going to do that, I'd rather deserialize losslessly (jsonDecoder.UseNumber()) and walk the tree converting to either int64 or float64 as appropriate

**Comment by smarterclayton** [comment]
If you deserialize with UseNumber don't you lose whether the original value
was string or number (which is the point of unstructured)?

On Nov 6, 2015, at 5:05 PM, Jordan Liggitt <notifications@github.com> wrote:

Doing anything to all the number values requires walking the JSON tree. If
I was going to do that, I'd rather deserialize losslessly
(jsonDecoder.UseNumber()) and walk the tree converting to either int64 or
float64 as appropriate

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5557#issuecomment-154556329>.

**Comment by liggitt** [comment]
no, strings are always strings in JSON, UseNumber turns unquoted numbers into json.Number

**Comment by smarterclayton** [comment]
Ok sorry.  Yes, that is better.

On Nov 6, 2015, at 5:10 PM, Jordan Liggitt <notifications@github.com> wrote:

no, strings are always strings in JSON, UseNumber turns unquoted numbers
into json.Number

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5557#issuecomment-154557635>.

**Comment by liggitt** [comment]
This impacts patch and unstructured
