### ISSUE TITLE
Namespace deletion taking substantially longer - possible flake

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5558]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6528/console

Was not seeing this prior to today, could be merge related to graceful deletion for legacy kubelets,  or just a general slowdown. @derekwaynecarr

**Comment by smarterclayton** [comment]
Could be specific to 5540, not sure

**Comment by soltysh** [comment]
Wasn't that fixed with https://github.com/openshift/origin/pull/5720 ?

**Comment by smarterclayton** [comment]
It's better, but still seeing

```
• Failure [216.231 seconds]
Namespaces [It] should delete fast enough (90 percent of 100 namespaces in 150 seconds) 
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/namespace.go:115

  Expected error:
      <*errors.errorString | 0xc20811f390>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/namespace.go:94
------------------------------
    fail    Namespaces should delete fast enough (90 percent of 100 namespaces in 150 seconds) (3m36.230781561s)
``` which needs triage

**Comment by smarterclayton** [comment]
This started being slow again

**Comment by derekwaynecarr** [comment]
Is it frequently failing?  Deletion of kube content should be fast, we could make the origin content faster by eliminating the origin namespace controller and just using the upstream one, but we wanted to do that post 1.2

**Comment by smarterclayton** [comment]
I've seen it fail a few times over the last X days. I may move it into the
serial tests.

**Comment by derekwaynecarr** [comment]
namespace deletion tests upstream are marked serial, do those not carry
downstream?

**Comment by smarterclayton** [comment]
It looks like they are passing again.  We can close this.
