### ISSUE TITLE
external registry ping flake on Jenkins

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#5559]
Error log [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6540/console):
```
--- FAIL: TestRegistryClientConnectPulpRegistry-2 (0.31s)
	dockerregistryclient_test.go:47: unable to retrieve image info: error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: read tcp 209.132.182.63:443: connection reset by peer
FAIL
```

**Comment by miminar** [comment]
This looks like network related. Do we want to ignore `connection reset by peer` or skip it if `https://registry.access.redhat.com/v2/` is unavailable/unresponsive?

Seems like a rare flake. I've found just one newer [occurrence](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6881/console).

**Comment by stevekuznetsov** [comment]
Seen again [here](https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4119/console):
```
--- FAIL: TestRegistryClientQuayIOImage-4 (10.00s)
    dockerregistryclient_test.go:132: unexpected error: error checking for V2 registry at https://quay.io/v2/: Get https://quay.io/v2/: net/http: TLS handshake timeout
FAIL
```
