### ISSUE TITLE
Information message icon different on pod logs and terminal tabs

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5562]
Minor issue of course, but we really should use the same icon on pages for the same resource at least... @jwforres @ajacobs21e Which icon is correct?

Logs:

<img width="695" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/10869227/cf3833a0-8076-11e5-8828-4278d80e00e2.png">

Terminal:

<img width="649" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/10869224/bf25095c-8076-11e5-9257-b8fff2ff00a4.png">

**Comment by ajacobs21e** [comment]
@spadgett logs - should be pficon-info

**Comment by ajacobs21e** [comment]
good catch, thanks Sam

On Sun, Nov 1, 2015 at 9:03 AM, Sam Padgett <notifications@github.com>
wrote:

> Minor issue of course, but we really should use the same icon on pages for
> the same resource at least... @jwforres <https://github.com/jwforres>
> @ajacobs21e <https://github.com/ajacobs21e> Which icon is correct?
>
> Logs:
>
> [image: openshift_web_console]
> <https://cloud.githubusercontent.com/assets/1167259/10869227/cf3833a0-8076-11e5-8828-4278d80e00e2.png>
>
> Terminal:
>
> [image: openshift_web_console]
> <https://cloud.githubusercontent.com/assets/1167259/10869224/bf25095c-8076-11e5-9257-b8fff2ff00a4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/5562>.
>



-- 

Allie Jacobs
UXD

calendar
<https://www.google.com/calendar/b/1/embed?src=ajacobs@redhat.com&ctz=America/New_York>
