### ISSUE TITLE
Origin 1.0.7 RPM broken for centos 7

### ISSUE THREAD

**Issue by arrawatia** [openshift/origin#5565]
The RPM build for 1.0.7 requires "docker-io > 1.8" but the latest docker binary has been renamed to docker-engine (https://docs.docker.com/installation/centos/). 

Is there a yum repo for centos that hosts "docker-io > 1.8" rpm ?

**Comment by sdodson** [comment]
For now we've patched the specfile to only require docker-io 1.6.2. Centos should get docker-1.8.2 in the coming weeks.

**Comment by arrawatia** [comment]
Great ! Thanks.

**Comment by arrawatia** [comment]
I tried the rpm build using tito. It failed, my steps are :

1. Install tito `yum install -y tito`
2. Change .tito/packages/origin from 0.0.1 to 1.0.7
3. Run `tito build --rpm`

The build fails with error
```
$ tito build --rpm --debug
Added lib dir to PYTHONPATH: /data/src/github.com/openshift/origin/.tito/lib
---- Builder class is None
Importing origin.builder.OriginBuilder
Using builder class: <class 'origin.builder.OriginBuilder'>
Building in temp dir: /tmp/tito/rpmbuild-originsk_Tbu
Getting latest package info from: /data/src/github.com/openshift/origin/.tito/packages/origin
Local tag SHA1: ac4234aa9bdd434c555150768c3e4b7b1a3898e9
Checking for tag [v1.0.7] in git repo [git://github.com/openshift/origin]
Remote tag SHA1: ac4234aa9bdd434c555150768c3e4b7b1a3898e9
Got package metadata: ['0.0.1', './']
Building package [v1.0.7]
Creating origin-1.0.7.tar.gz from git tag: 67bb2080164c3c1b13aafafd6f62857978c5fe6c...
git-archive fails if relative dir is not in git tree
Command: git archive --format=tar --prefix=origin-1.0.7/ 67bb2080164c3c1b13aafafd6f62857978c5fe6c: --output=/tmp/tito/rpmbuild-originsk_Tbu/SOURCES/origin-1.0.7.tar.initial > /dev/null

......

Status code: 0

Command output:

Looking for .spec in /tmp/tito/rpmbuild-originIjPnom/SOURCES/origin-1.0.7
Using file: origin.spec
Wrote: /tmp/tito/origin-1.0.7.tar.gz
rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-originIjPnom" --define "_sourcedir /tmp/tito/rpmbuild-originIjPnom/SOURCES" --define "_builddir /tmp/tito/rpmbuild-originIjPnom/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito" --define "ldflags -X github.com/openshift/origin/pkg/version.majorFromGit=1 -X github.com/openshift/origin/pkg/version.minorFromGit=0+ -X github.com/openshift/origin/pkg/version.versionFromGit=v1.0.7-dirty -X github.com/openshift/origin/pkg/version.commitFromGit=67bb208 -X k8s.io/kubernetes/pkg/version.gitCommit=4c8e6f4 -X k8s.io/kubernetes/pkg/version.gitVersion=v1.2.0-alpha.1-1107-g4c8e6f4" --define "commit 67bb2080164c3c1b13aafafd6f62857978c5fe6c"   --clean -ba /tmp/tito/rpmbuild-originIjPnom/SOURCES/origin-1.0.7/origin.spec
error: File /tmp/tito/rpmbuild-originIjPnom/SOURCES/origin-0.0.1.tar.gz: No such file or directory


ERROR: Error running command: rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-originIjPnom" --define "_sourcedir /tmp/tito/rpmbuild-originIjPnom/SOURCES" --define "_builddir /tmp/tito/rpmbuild-originIjPnom/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito" --define "ldflags -X github.com/openshift/origin/pkg/version.majorFromGit=1 -X github.com/openshift/origin/pkg/version.minorFromGit=0+ -X github.com/openshift/origin/pkg/version.versionFromGit=v1.0.7-dirty -X github.com/openshift/origin/pkg/version.commitFromGit=67bb208 -X k8s.io/kubernetes/pkg/version.gitCommit=4c8e6f4 -X k8s.io/kubernetes/pkg/version.gitVersion=v1.2.0-alpha.1-1107-g4c8e6f4" --define "commit 67bb2080164c3c1b13aafafd6f62857978c5fe6c"   --clean -ba /tmp/tito/rpmbuild-originIjPnom/SOURCES/origin-1.0.7/origin.spec
Cleaning up /tmp/tito/rpmbuild-originIjPnom
```

It seems that it looks into the `.tito/packages/origin` from the checked out version. If I just run the `rpm build` command it fails with some error about the go darwin and windows binary.

Can you please let me know what I am doing wrong ?

**Comment by sdodson** [comment]
> I tried the rpm build using tito. It failed, my steps are :
> 
>     Install tito yum install -y tito
>     Change .tito/packages/origin from 0.0.1 to 1.0.7
>     Run tito build --rpm

You should change the version in origin.spec to 1.0.7. not .tito/packages/origin. Does that improve things for you?

You should be able to just use the pre-built packages from this COPR though, I've built them for 1.0.7 with docker-requirement on 1.6.2
https://copr.fedoraproject.org/coprs/maxamillion/origin-next/repo/epel-7/maxamillion-origin-next-epel-7.repo

I don't know what's going on with the yum repo from dockerproject.org, it seems really odd that they'd rename their package without ensuring it's got Provides: docker to ensure backwards compatible upgrades. I'll see about filing an issue.

**Comment by arrawatia** [comment]
I am using your build and it works well. Thanks.

I tried to build the rpm and it didnot work for me. So, I was just curious about what was going wrong.

I could not get the build to work though even after changing the origin.spec. Do you use tito or just the rpmbuild command ? I get the same error if I use tito.

**Comment by sdodson** [comment]
You have to use tito as we need the custom builder to inject version
information into the rpmbuild environment. I can't get to it right now but
I'll try to setup a clean environment to test tito in to ensure it's not
inadvertently dependent on something in my local config.

Do you mind closing this particular issue out, if you still face problems
with tito build that's a separate problem.
