### ISSUE TITLE
logs --previous works currently only for pods...

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#5583]
...by printing the logs of the previous container for a pod if it existed. We could have it work for bcs and dcs and return the previous build or deployment before the latest. I know that @deads2k was positive on this happening. @smarterclayton any objections?

**Comment by kargakis** [comment]
Re deployments, should we return the latest-1 deployment or the previously failed?

**Comment by kargakis** [comment]
cc: @ironcladlou

**Comment by deads2k** [comment]
> Re deployments, should we return the latest-1 deployment or the previously failed?

I think I would expect latest-1

**Comment by ironcladlou** [comment]
I think latest-1 (regardless of phase) is most predictable/easy to explain.

**Comment by kargakis** [comment]
Should --previous work with --version? For example,
```
$ oc logs --version=2 --previous dc/database
```
should return the first deployment? Same question for builds/build configs @bparees

**Comment by ironcladlou** [comment]
>Should --previous work with --version? 

I think they should be mutually exclusive. Otherwise it's like some kind of weird expression language via flags.

**Comment by bparees** [comment]
> I think they should be mutually exclusive. Otherwise it's like some kind of weird expression language via flags.

+1, let's not go nuts here.

**Comment by liggitt** [comment]
agree, mututally exclusive

**Comment by smarterclayton** [comment]
Does oc logs DC/foo work?  I thought David convinced me that should be implemented to pull the active pod but it doesn't do anything for me

**Comment by kargakis** [comment]
Works fine on latest master

oc logs DC/foo will return the deployer logs including the prehook inlined

You are probably talking about https://github.com/openshift/origin/issues/4201

**Comment by kargakis** [comment]
One idea I was playing around with is to support #4201 w/o any additional flag in oc logs. Not sure if it would be confusing for the users.
```sh
# Deployment process is running
$ oc logs -f dc/foo # returns the deployers logs - already done
# Deployment finishes; subsequent calls to oc logs dc/foo return application logs
```

**Comment by smarterclayton** [comment]
What you described is what I wanted (and expected to happen).

**Comment by kargakis** [comment]
> What you described is what I wanted (and expected to happen).

Cool. Did we settle on returning the logs only for rcs with one pod? RCs with multiple pods? Return logs from the oldest pod?

**Comment by smarterclayton** [comment]
Oldest pod and a warning showing the newest.  Upstream proposed "-l" on
logs that would stream all pods logs, in which case we would do the same
for all the pods in the latest deployment.

On Thu, Jan 28, 2016 at 10:26 AM, Michail Kargakis <notifications@github.com

**Comment by smarterclayton** [comment]
A warning saying "more than one pod is in the deployment, showing pod foo"
