### ISSUE TITLE
Add --nowait/--timeout to logs

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#5584]
tbh I don't see any value in `--nowait` or why someone would use it but anyway since it is supported by `build-logs` and all of the machinery is in place, we should probably add it.

**Comment by smarterclayton** [comment]
NoWait exists because clients may very well not want to wait for logs to be available - if something hasn't started, the effective log output is nothing.

**Comment by kargakis** [comment]
How about making the default timeout configurable instead? --timeout=0 would equal to --nowait, plus I can now specify how much I want to wait (more or less than the default 10s we currently have for builds and deployments).

**Comment by smarterclayton** [comment]
Making it configurable isn't unreasonable, but waiting on the server side is generally bad and is only for naive clients.  It has to be upper bounded with something for admin control.
