### ISSUE TITLE
Authentication problem creating ImageStream from private docker registry.

### ISSUE THREAD

**Issue by xuant** [openshift/origin#5590]
While creating a ImageStream from a private docker registry, getting some error:
```
factory.go:49] error getting image tags for <image_repo>/<image_name>: unsupported authentication challenge from registry: Basic realm="Restricted"
```

It seems like current docker registry client only support "Bearer" challenge: https://github.com/openshift/origin/blob/master/pkg/dockerregistry/client.go#L343.

However, I am able to create pods from private docker registry (related issue https://github.com/openshift/origin/issues/5517), just wondering if Pod creation and `import-image` are using different Docker registry client? And what I need to do to make ImageStream creation work?

Software Versions:
```
$ openshift version
openshift v1.0.7-2-gd775557-dirty
kubernetes v1.2.0-alpha.1-1107-g4c8e6f4
etcd 2.1.2
$ docker version
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-115.el7.x86_64
Go version (client): go1.4.2
Git commit (client): 446ad9b/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-115.el7.x86_64
Go version (server): go1.4.2
Git commit (server): 446ad9b/1.7.1
OS/Arch (server): linux/amd64
```

**Comment by deads2k** [comment]
@soltysh Did  `import-image` against as secured registry make it in?

**Comment by soltysh** [comment]
@deads2k nope, I wasn't changing anything with security

**Comment by liggitt** [comment]
pulling images directly from a private repository works for a pod

importing tags and image info from a private repository to track in an image stream is not supported yet

**Comment by xuant** [comment]
@liggitt 
I see. Thanks for clarifying. Is there a plan to include this feature in the near future?

**Comment by JohnTheodore** [comment]
Does STI require image stream? meaning, you can't use STI and a private docker registry together?

**Comment by liggitt** [comment]
> I see. Thanks for clarifying. Is there a plan to include this feature in the near future?

It is in the feature backlog at https://trello.com/c/KEQ1oUOm/435-support-private-authentication-via-dockercfg-secrets-in-the-image-import-controller, but it hasn't been scheduled yet

> Does STI require image stream? meaning, you can't use STI and a private docker registry together?

@bparees can correct me if I'm wrong, but I think STI can use a builder image directly (not via an image stream) using something like this in the strategy:
```
"from": {
  "kind": "DockerImage",
  "name": "myrepo.io/myimage:mytag"
},
"pullSecret": {
  "kind": "Secret",
  "name": "mydockercfgsecret"
}
```

**Comment by bparees** [comment]
@liggitt is correct.  here's the official docs on the subject: https://docs.openshift.org/latest/dev_guide/builds.html#using-docker-credentials-for-pushing-and-pulling-images

**Comment by soltysh** [comment]
Since @bparees provided a workaround solution and we already have a card for importing images from private docker registries (https://trello.com/c/KEQ1oUOm/435-support-private-authentication-via-dockercfg-secrets-in-the-image-import-controller) I'd suggest closing this issue.

**Comment by xuant** [comment]
@bparees I modify the BuildConfig json according to [the doc](https://docs.openshift.org/latest/dev_guide/builds.html#using-docker-credentials-for-pushing-and-pulling-images) you mentioned, but still met with errors:
```
# oc logs test-bc-2-build
I1105 00:42:27.689078       1 sti.go:171] The value of ALLOWED_UIDS is [1-]
I1105 00:42:27.742453       1 docker.go:230] Pulling image <private_registry>/<namespace>/<builder_image>:latest
I1105 00:42:28.215415       1 sti.go:193] Creating a new S2I builder with build config: "Builder Image:\t\t<private_registry>/<namespace>/<builder_image>:latest\nSource:\t\t\tfile:///tmp/s2i-build112899923/upload/src#master\nOutput Image Tag:\t<private_registry>/horizon-s2i:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAME=test-bc-2,OPENSHIFT_BUILD_NAMESPACE=deploy-horizon,OPENSHIFT_BUILD_SOURCE=https://<private_git_repo>/xuant/horizon.git,OPENSHIFT_BUILD_REFERENCE=master\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nWorkdir:\t\t/tmp/s2i-build112899923\nDocker NetworkMode:\tcontainer:611f9af12d91553a97de119e548baaa9072da0c4e3ebdfa205d5443b01bd1fca\nDocker Endpoint:\tunix:///var/run/docker.sock\nDocker Pull Config:\t/var/run/secrets/openshift.io/pull/.dockercfg\nDocker Pull User:\tcpaas\n"
I1105 00:42:28.267195       1 docker.go:230] Pulling image <private_registry>/<namespace>/<builder_image>:latest
F1105 00:42:28.745312       1 builder.go:55] Build error: unable to get <private_registry>/<namespace>/<builder_image>:latest
```

The new S2I builder seemed to catch the right secret because I can see the username I used to create the .dockercfg file from the error msg.

These are the output of buildconfig and serviceaccout:
```
# oc get bc test-bc -o yaml
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
  creationTimestamp: XXXXXXXXXXXXXX
  name: test-bc
  namespace: deploy-horizon
  resourceVersion: "131198"
  selfLink: /oapi/v1/namespaces/deploy-horizon/buildconfigs/test-bc
  uid: xXxXxXxXxXXXXXXXXXXX
spec:
  output:
    pushSecret:
      name: cicd
    to:
      kind: DockerImage
      name: <private_registry>/horizon-s2i:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://<private_git_server>/xuant/horizon.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: <private_registry>/<namespace>/<builder_image>:latest
      pullSecret:
        name: cicd
    type: Source
  triggers: []
status:
  lastVersion: 2

# oc get sa builder -o yaml
apiVersion: v1
imagePullSecrets:
- name: builder-dockercfg-fnzj5
kind: ServiceAccount
metadata:
  creationTimestamp: XXXXXXXXXXXXXXXXXXXX
  name: builder
  namespace: deploy-horizon
  resourceVersion: "130672"
  selfLink: /api/v1/namespaces/deploy-horizon/serviceaccounts/builder
  uid: XXXXXXXXXXXXXXXXXXXXXXX
secrets:
- name: builder-token-87q7k
- name: builder-dockercfg-fnzj5
- name: cicd
```

**Comment by bparees** [comment]
@xuant before we go too deep, can you double check that your .dockercfg content is in fact correct (valid password that is able to pull from the registry in question)?

As you say, it would appear from the log that .dockercfg was located from your Secret and auth credentials from that file are being used.

you can also enable more verbose build logging which may shed some additional light:
https://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs

try log level 5.

**Comment by xuant** [comment]
@bparees Yeah, the log 5 helped. It turned out to be "insecure-registry" setting of docker that cause the problem. It works for version 1.0.7.

**Comment by bparees** [comment]
@xuant great, can this be closed?

**Comment by xuant** [comment]
@bparees I think so

**Comment by smarterclayton** [comment]
@sosiouxme more evidence we need a way for diagnostics to check for insecure registry (or for us to just fix the registry thing already with DNS names @ncdc @pweil- )
