### ISSUE TITLE
Hot-looping Kube controller can starve other consumers of the master config's KubeClient

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5593]
Scenario:
1. Enabled GC controller (watches pods)
2. Tried to delete a project with a pod in it
3. GC controller was hot looping, which used up the QPS count for the shared KubeClient
4. Namespace controller starved trying to delete something

We should consider isolating the QPS counters for certain important system controllers.

**Comment by ncdc** [comment]
@smarterclayton do you know if anything has been done to address this?

**Comment by smarterclayton** [comment]
Probably, but we need to retest it.
