### ISSUE TITLE
github.com timeouts on install-assets

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5604]
#5579, #5530, #5514

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6589/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6590/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6598/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6606/console

**Comment by liggitt** [comment]
@jwforres

**Comment by liggitt** [comment]
https://github.com/openshift/origin/pull/5601

**Comment by liggitt** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3909/console

**Comment by liggitt** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3897/console

**Comment by jwforres** [comment]
Should be significantly improved by https://github.com/openshift/origin/pull/5638

Will keep open until we see if need to bump up the number of retries.

**Comment by liggitt** [comment]
Fixed by https://github.com/openshift/origin/pull/5638
