### ISSUE TITLE
test-integration.sh times out starting etcd

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5605]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6588/console
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6587/console

```
ERROR: gave up waiting for http://127.0.0.1:44001/version
```

**Comment by liggitt** [comment]
#5579, #5531

**Comment by smarterclayton** [comment]
Not fixed - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6822/console and failed to log errors.

**Comment by liggitt** [comment]
https://ci.openshift.redhat.com/jenkins/job/devenv_ami/3146/console
```
Starting etcd...
ERROR: gave up waiting for http://127.0.0.1:44001/version
```

**Comment by smarterclayton** [comment]
Do we think is 100% related to the disk allocation issue?

**Comment by liggitt** [comment]
Not sure. We never tracked the healthz timeouts to disk issues, and I still see those occasionally even with the disk issue (maybe) worked around

**Comment by smarterclayton** [comment]
I'm wondering if we've fixed disk.  I've certainly seen etcd 500
errors.  Need to remind myself to look at the gathered iostats since
we go to all the effort to watch them.

**Comment by smarterclayton** [comment]
Fixed
