### ISSUE TITLE
Jenkins infrastructure flakes

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5627]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6683/console:
```
/data/src/github.com/openshift/origin/hack/../hack/util.sh: line 78: openshift: command not found
!!! Error in /data/src/github.com/openshift/origin/hack/../hack/util.sh:78
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6686/console:
```
remote: error: unable to create temporary file: File exists        
remote: fatal: failed to write object        
error: unpack failed: unpack-objects abnormal exit
To verifier:/data/src/github.com/openshift/origin-bare
 ! [remote rejected] master -> master (unpacker error)
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6687/console:
```
fatal: Unable to create '/data/src/github.com/openshift/origin-bare/refs/heads/master.lock': File exists.
```

@danmcp

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6830/

```
/data/src/github.com/openshift/origin ~
Commit ID: aeb5a45649595e4aa29c0f672edb26e133d2cca4
Previous Commit ID: aeb5a45649595e4aa29c0f672edb26e133d2cca4
Git Status: 
No update for origin, master
~
```

@danmcp didn't build the binaries

**Comment by smarterclayton** [comment]
And https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6824/

**Comment by liggitt** [comment]
#5272: https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3968/
```
fatal: '/data/src/github.com/openshift/source-to-image-bare' does not appear to be a git repository
fatal: Could not read from remote repository.
```

**Comment by danmcp** [comment]
Several of these are dups of https://github.com/openshift/origin/issues/6321 and https://github.com/openshift/origin/issues/1579

**Comment by danmcp** [comment]
The remaining issues could easily be a side effect of: https://github.com/openshift/vagrant-openshift/pull/381

Please reopen if you see any of them again.
