### ISSUE TITLE
docker socket file descriptor leak

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#5631]
Running lsof on an openshift node process shows an ever-increasing number of open unix sockets. strace shows:

    3248  socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 73
    3248  connect(73, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, 23 <unfinished ...>
    3248  write(73, "GET /version HTTP/1.1\r\nHost: unix.sock\r\nUser-Agent: go-dockerclient\r\nAccept-Encoding: gzip\r\n\r\n", 94 <unfinished ...>
    3234  read(73, "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nServer: Docker/1.8.1.fc21 (linux)\r\nDate: Tue, 03 Nov 2015 13:32:44 GMT\r\nContent-Length: 164\r\n\r\n{\"Version\":\"1.8.1.fc21\",\"ApiVersion\":\"1.20\",\"GitCommit\":\"32b8b25/1.8.1\",\"GoVersion\":\"go1.4.2\",\"Os\":\"linux\",\"Arch\":\"amd64\",\"KernelVersion\":\"3.17.4-301.fc21.x86_64\"}\n", 4096) = 308
    3234  read(73, 0xc8216dd000, 4096)      = -1 EAGAIN (Resource temporarily unavailable)

and then the file descriptor is never referred to again. Later the process is repeated with fd 74, 75, etc.

**Comment by ncdc** [comment]
AFAIK, the current version of go-dockerclient keeps the connection open so you can reuse it. If we're creating multiple go-dockerclient Clients, that could be the issue. See e.g. https://github.com/kubernetes/kubernetes/issues/15805#issuecomment-148963658

**Comment by aveshagarwal** [comment]
I am on f22 and running running latest origin code base with one master and one node on the same F22 VM. 

docker version is: docker-1.8.2-7.gitcb216be.fc22.x86_64

```
#ps -ef| grep openshift
root     22180  1600  2 11:11 pts/0    00:01:24 openshift start master --config=./openshift.local.config/master/master-config.yaml
root     22192  1771  3 11:12 pts/1    00:01:31 openshift start node --config=./openshift.local.config/node-192.168.122.217/node-config.yaml
```

```
# lsof -p 22192| grep unix
openshift 22192 root    3u     unix 0xffff880000e30380       0t0 342127 type=DGRAM
openshift 22192 root    6u     unix 0xffff880000e31500       0t0 342142 type=STREAM
openshift 22192 root    7u     unix 0xffff880000e30000       0t0 342147 type=STREAM
openshift 22192 root    8u     unix 0xffff880000e30e00       0t0 342153 type=STREAM
openshift 22192 root   38u     unix 0xffff880000e31c00       0t0 342319 type=STREAM
openshift 22192 root   41u     unix 0xffff88006809a700       0t0 342325 type=STREAM
```

I do not see increasing unix sockets,  could you (@danwinship )  provide more information?

**Comment by eparis** [comment]
@aveshagarwal do you have any pods running?  maybe just launch like 100 pods that don't do much/anything?

**Comment by aveshagarwal** [comment]
@eparis 100 pods?, let me try creating some pods depending upon how many my F22 VM can sustain.

**Comment by ncdc** [comment]
I would think just a few should be enough, it that's the path that causes
it.

**Comment by aveshagarwal** [comment]
I am going to create more pods, but based on logs that @danwinship seems to be running this issue on f21 with docker-1.8.1.fc21, whereas I am on F22 with  docker-1.8.2-7.gitcb216be.fc22.x86_64. Not sure if that might be causing the issue (wild guesses right now).

**Comment by danwinship** [comment]
OK I can't reproduce this now either... something merged in the last 24 hours must have fixed it

**Comment by ncdc** [comment]
When did the cadvisor bump merge?

**Comment by danwinship** [comment]
Yup, bisected to `c828337 UPSTREAM: 15612: Bump cadvisor`
(which actually landed on Monday, so I was probably testing against a slightly-old build yesterday morning)

**Comment by ncdc** [comment]
@danwinship thanks for bisecting & confirming
