### ISSUE TITLE
istag should have a `create`

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5637]
istags have get, list, update, and delete, but not a create.  That's an annoying inconsistency and it means that we've got client side operations trying to handle conflicts.

**Comment by soltysh** [comment]
Isn't `oc tag` for that, do you want to have a duplicate command?

**Comment by deads2k** [comment]
> Isn't oc tag for that, do you want to have a duplicate command?

`oc tag` works by modifying an image stream resource.  I'm fine with keeping an `oc tag` command, but I think its unreasonable to have all other clients figuring out how to navigate image streams and dealing with conflicts.

**Comment by soltysh** [comment]
That makes sense, :+1:

**Comment by soltysh** [comment]
You can assign that to me, already.

**Comment by kargakis** [comment]
Why is this [not allowed](https://github.com/openshift/origin/blob/83c0e6a7541843cb954ccc2a144fba4197ee8680/pkg/image/api/validation/validation.go#L163) so far? cc: @ncdc

**Comment by ncdc** [comment]
You POST an ImageStreamMapping if you want to associate an image with a tag. ISM was created prior to ISTag. Maybe we should deprecate ISM and move its logic to POST ISTag?

**Comment by ncdc** [comment]
cc @smarterclayton

**Comment by kargakis** [comment]
> Maybe we should deprecate ISM and move its logic to POST ISTag?

+1

**Comment by smarterclayton** [comment]
Let's hold off on this until I have import working and sorted.  I want to be sure what the API looks like for imports after my changes.

**Comment by smarterclayton** [comment]
ISM is a separate security endpoint.  ISM is allowed to create new images - IST is not (today).

**Comment by smarterclayton** [comment]
Closing due to age and the fact that we fixed it.
