### ISSUE TITLE
Cannot get logs from complete/failed pods after restarting the server

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#5640]
```
$ oc logs dc/failing-dc
failed to get status for pod "failing-dc-2-deploy" in namespace "test"
```

Is this expected? From digging into the kubelet code, it doesn't seem so
https://github.com/kubernetes/kubernetes/blob/17e36b02f48ac1d637fa218f036d05ba45261f9d/pkg/kubelet/kubelet.go#L2295-l2297

@smarterclayton @liggitt @deads2k

**Comment by smarterclayton** [comment]
It is not expected

**Comment by kargakis** [comment]
Note that it only happens with failed/complete pods.
