### ISSUE TITLE
Test flake in cmd when creating new app with mongodb

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5660]
```
See 'new-app' for examples.
error: component "mongo" had only a partial match of "mongodb" - if this is the value you want to use, specify it explicitly
!!! Error in test/cmd/newapp.sh:18
    '[ "$(oc new-app mongo -o yaml | grep library/mongo)" ]' exited with status 1
Call stack:
    1: test/cmd/newapp.sh:18 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:2
```

This is new

**Comment by smarterclayton** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6735/

**Comment by csrwng** [comment]
@smarterclayton this is a dependency on docker hub and it seems valid. Do we want to remove docker hub dependencies from test-cmd ? (@bparees)

**Comment by smarterclayton** [comment]
Why did this fail now but not before?

**Comment by csrwng** [comment]
My best guess is a slow response or timeout from docker hub

**Comment by bparees** [comment]
closing based on not having seen these sorts of issues lately. 

If dockerhub becomes a consistent source of flakes again, we'll have to revisit how to solve this, but given that the point of the test is to confirm new-app is finding the image on dockerhub, i have no idea what that solution would look like, other than just moving it into an extended(non-merge-blocking) test.

**Comment by smarterclayton** [comment]
This is going to get fixed by image import as well

**Comment by bparees** [comment]
how's that?
