### ISSUE TITLE
system:hpa-controller and system:job-controller roles do not exist at server start

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5668]
when starting from a previous version, these new roles do not exist at server start:
```
Nov 03 14:18:48 ose3-atomic.example.com docker[2033]: E1103 19:18:48.185260       1 ensure.go:85] Could not add [{ServiceAccount openshift-infra hpa-controller    }] subjects to the system:hpa-controller cluster role: Role "system:hpa-controller" not found
Nov 03 14:18:48 ose3-atomic.example.com docker[2033]: I1103 19:18:48.233378       1 ensure.go:87] Added [{ServiceAccount openshift-infra build-controller    }] subjects to the system:build-controller cluster role: <nil>
Nov 03 14:18:48 ose3-atomic.example.com docker[2033]: I1103 19:18:48.300393       1 ensure.go:87] Added [{ServiceAccount openshift-infra deployment-controller    }] subjects to the system:deployment-controller cluster role: <nil>
Nov 03 14:18:48 ose3-atomic.example.com docker[2033]: I1103 19:18:48.348309       1 ensure.go:87] Added [{ServiceAccount openshift-infra replication-controller    }] subjects to the system:replication-controller cluster role: <nil>
Nov 03 14:18:48 ose3-atomic.example.com docker[2033]: E1103 19:18:48.359039       1 ensure.go:85] Could not add [{ServiceAccount openshift-infra job-controller    }] subjects to the system:job-controller cluster role: Role "system:job-controller" not found
```

you can run reconcile-cluster-roles after starting, but reconcile-cluster-role-bindings does not handle granting to the openshift-infra service accounts

**Comment by liggitt** [comment]
cc @deads2k

**Comment by deads2k** [comment]
> you can run reconcile-cluster-roles after starting, but reconcile-cluster-role-bindings does not handle granting to the openshift-infra service accounts

Just to make sure we're on the page here. This is fixed by running `reconcile-cluster-roles` and restarting the master, right?  We're not ok with just doing that?

**Comment by liggitt** [comment]
correct, an upgrade, reconcile against running, then restart fixes it
this is mostly open to either improve what the ensure function does, or find a way to let an upgrade process reconcile things the infra namespace depends on

**Comment by sdodson** [comment]
@lliggitt those logs were a first start of the master btw.

**Comment by liggitt** [comment]
first start of the master with a clean etcd?

**Comment by sdodson** [comment]
> first start of the master with a clean etcd?

yeah clean etcd, but an outdated policy.json

**Comment by deads2k** [comment]
> first start of the master with a clean etcd?

clean etcd, but old `policy.json`.  We should stop making that file now that we have `reconcile`

**Comment by sdodson** [comment]
> clean etcd, but old policy.json. We should stop making that file now that we have reconcile

:heart:

**Comment by deads2k** [comment]
I think I'd like to fix this with a `force` option on binding creation.

**Comment by liggitt** [comment]
bind prospectively so a future reconcile-roles will make the bindings start working?

**Comment by deads2k** [comment]
> bind prospectively so a future reconcile-cluster-roles will make the bindings start working?

That error comes from storage that is specifically designed to stop that from happening (binding to a role that doesn't exist), hence the idea of a `force` passed to the API server

**Comment by deads2k** [comment]
https://github.com/openshift/origin/blob/master/pkg/authorization/registry/rolebinding/policybased/virtual_storage.go#L127

**Comment by liggitt** [comment]
seems... ok... don't see a good way to plumb it

**Comment by deads2k** [comment]
@danmcp 

This self-corrects with a master restart after reconciling roles.  No existing functionality breaks, new functionality is disabled by default.  We can't reasonably change the behavior to auto-provision without either changing the our contract on `system:*` roles or updating the REST API from kube all the way down.

**Comment by liggitt** [comment]
@sdodson is the master restarted after an upgrade + reconcile or do we need to document that?

**Comment by sdodson** [comment]
We update the package, restart, then reconcile. Let me know if there's a
better ordering.

**Comment by liggitt** [comment]
has to be post-restart to pick up new capabilities in the API for groups on role rules :-/

**Comment by liggitt** [comment]
is it too janky to restart, reconcile, then restart again?

**Comment by deads2k** [comment]
Why do we restart before reconciling?

**Comment by deads2k** [comment]
> Why do we restart before reconciling?

Actually, it would have to be 
 1. upgrade
 1. reconcile - this creates new roles, but the APIGroups field is dropped
 1. restart - this binds using the new role name
 1. reconcile - this completes the Roles for APIGroups

@sdodson This works assuming the second reconcile-cluster-roles does not run `--additive-only`.  If it does run `--additive-only`, you'll end up with access to resources that don't exist.

**Comment by sdodson** [comment]
@deads2k We restart before modifying things because, at least for other things like enabling hostports in the SCC the master was silently ignoring fields we were trying to set. I imagine the same would happen for policy.

**Comment by deads2k** [comment]
@sdodson if you're more comfortable with upgrade, restart, reconcile, restart, I'm fine with that.

**Comment by sdodson** [comment]
> @sdodson if you're more comfortable with upgrade, restart, reconcile, restart, I'm fine with that.

Yes, I think that's the best pattern. It also makes sure that the master starts up cleanly in the final state now rather than finding a latent issue a month later when the host is rebooted due to external influence.

**Comment by liggitt** [comment]
what's interesting is that in an HA scenario, running the reconcile after restart isn't guaranteed to hit the upgraded master, right?

**Comment by sdodson** [comment]
We upgrade all master packages, restart all masters. We upgrade all node packages, we restart all nodes. We run all data manipulation on the first master. We'd then need to restart all masters again, right?
