### ISSUE TITLE
e2e failing-dc... succeeded

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5680]
Test intended to fail... succeeded: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6864/consoleFull

```
deploymentconfig "failing-dc" created
++ Retrying until success or timeout: oc get rc/failing-dc-1
I1104 05:02:07.280361       1 deployer.go:196] Deploying test/failing-dc-1 for the first time (replicas: 2)
I1104 05:02:07.281298       1 recreate.go:113] Scaling test/failing-dc-1 to 1 before performing acceptance check
I1104 05:02:09.305880       1 recreate.go:118] Performing acceptance check of test/failing-dc-1
I1104 05:02:09.305976       1 lifecycle.go:290] Waiting 5 seconds for pods owned by deployment "test/failing-dc-1" to become ready (checking every 1 seconds; 0 pods previously accepted)
I1104 05:02:10.306301       1 lifecycle.go:311] All pods ready for test/failing-dc-1
I1104 05:02:10.306330       1 recreate.go:126] Scaling test/failing-dc-1 to 2
I1104 05:02:16.420398       1 recreate.go:144] Deployment failing-dc-1 successfully made active
[INFO] Waiting for command to finish: 'oc get rc/failing-dc-1 --template={{.metadata.annotations}} | grep openshift.io/deployment.phase:Failed'...
[ ERR] Gave up waiting for: 'oc get rc/failing-dc-1 --template={{.metadata.annotations}} | grep openshift.io/deployment.phase:Failed'

[FAIL] !!!!! Test Failed !!!!
```

**Comment by smarterclayton** [comment]
@ironcladlou / @kargakis

**Comment by liggitt** [comment]
up is down, left is right, and short is long

**Comment by ironcladlou** [comment]
Pretty sure that run predates my changes to the `failing-dc.yaml` fixture in #5305. Prior to my change I think it's possible for the failing spec to succeed sometimes. You can see here what I did to ensure that the fixture always fails:

https://github.com/openshift/origin/pull/5305/files#diff-34a9a2a55e04ac18d9641d2ea5fe3c2d

The original fixture assumed that "origin-ruby-sample" was not pullable. If "origin-ruby-sample" was pullable during the referenced Jenkins run, then the dc will actually end up deployed using the original fixture. Is that possible?

I'd probably close this one until the failure is observed in a test run that includes #5305.

**Comment by kargakis** [comment]
This is most probably fixed, can we close it until we see it again?

**Comment by smarterclayton** [comment]
This should always fail now with my changes to deployment
