### ISSUE TITLE
oc logs does not work with a space between a resource and its name

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#5685]
Here's the example:
```
[vagrant@openshiftdev ~]$ oc logs build django-example-1
error: expected a resource
```
Whereas with a slash it works perfectly fine:
```
[vagrant@openshiftdev ~]$ oc logs build/django-example-1
---> Copying application source ...
---> Installing dependencies ...
```
With all other commands we allow both, iow. with a slash or a space between resource and its name. I'd suspect logs work the same way.

@kargakis

**Comment by kargakis** [comment]
`logs` supports a second argument for legacy reasons (for specifying a container - has been superceded by -c). Until it is deprecated, I don't think we 'll be able to support this.

**Comment by kargakis** [comment]
Another thing is do we really want to continue supporting this type of syntax? 1) It isn't scriptable, 2) it adds a ton of complexity, especially in commands that support multiple resources as input, and 3) api groups (and namespaces?) are coming in the cli... These are easily solved by sticking them to the resource type so why have the name separate?

**Comment by deads2k** [comment]
> Another thing is do we really want to continue supporting this type of syntax? 1) It isn't scriptable, 2) it adds a ton of complexity, especially in commands that support multiple resources as input, and 3) api groups (and namespaces?) are coming in the cli... These are easily solved by sticking them to the resource type so why have the name separate?

I'm for removing it, but obviously that would be breaking.  I wouldn't mind an upstream issue to discuss it though.

**Comment by soltysh** [comment]
:+1: for the idea

**Comment by kargakis** [comment]
@soltysh since this is an upstream issue do you mind moving it there?

**Comment by soltysh** [comment]
Moved upstream https://github.com/kubernetes/kubernetes/issues/20265.
