### ISSUE TITLE
When click "rebuild' the console should take me to a new build

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5690]
@jwforres @spadgett 

if you click rebuild, you will get message that build was started, but you have to go manually into the new build page... would be great if the rebuild button take you to a newly created build ;-)

**Comment by jhadvig** [comment]
+1

**Comment by jwforres** [comment]
Will think about this one.  The

**Comment by jwforres** [comment]
Hit send too soon :)

From a use case perspective, why do you want to jump to the builds page?  Is it to see the logs?

**Comment by mfojtik** [comment]
@jwforres usually when I hit rebuild it is because something exploded and I want to kick a new build and yeah, watch the logs. I'm not interested to stay on the broken build page.

Another solution would be to provide a link in the notification message.... It is saying now something like "A build blabla has been started..." if there is a link to a new build, I can just click on that and I don't need to navigate via menu or nav bar.

**Comment by jhadvig** [comment]
Exactly, at least I see it on myself that displaying the logs is the next step after I trigger the build action. That is for both UI and CLI

**Comment by jwforres** [comment]
Ah i misread the original issue, this is on rebuild, i was thinking start
build.   Yeah I think at a minimum we should add a link to the new build in
the message that pops up.  Possibly a link directly to view the logs.

**Comment by jhadvig** [comment]
@jwforres please close this one.
