### ISSUE TITLE
Builds do not have an annotation for the name of their build pod

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#5692]
This means for things like logs the UI doesn't have the name of the pod when linking out to something like kibana.

**Comment by jwforres** [comment]
@bparees @csrwng

**Comment by jwforres** [comment]
cc @benjaminapetersen @spadgett

**Comment by bparees** [comment]
build pods have a label for the build they are associated with, can you not look up the build pod that way?

**Comment by spadgett** [comment]
@bparees we only have the build in this context, so it would be an extra request to get all the pods and check each one

**Comment by jwforres** [comment]
Exactly what @spadgett said.  A LOT of extra data for us to get one association that we really do need.

**Comment by jwforres** [comment]
Why do I feel like this is where you tell me you would have to do something horrible on the backend to make this happen.

**Comment by spadgett** [comment]
Can we filter the get by label? Even so, it would be an extra request when all we need is the name.

**Comment by jwforres** [comment]
Yes if it comes to that.  We in theory could still get multiple results
back because labels can be modified.

Even if this is fixed we still have to worry about someone deleting the
label and then would have to fallback gracefully.

**Comment by bparees** [comment]
No i don't think it's a ton of extra work, though it does mean updating the build after we create the pod which could have unforeseen consequences.  We might be able to just do it when we're updating the state of the build to "Running" anyway, that might be the lowest risk.

but the fact that we can't run an efficient indexed query to retrieve a single pod with a specific annotation from a known namespace is.......ridiculous.

**Comment by bparees** [comment]
and if we add this you're still going to have to fallback gracefully since no existing builds are going to have this information.
