### ISSUE TITLE
We should warn user when doing new-app with image that has USER instruction

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5693]
The default SCC now is restricted, so using Docker image from Hub that want to run as explicit USER will fail in most cases.
We should at least give users reasonable hint about this, something like:
```
This image use USER instruction but the current policy restrict this.
```

So users will be aware of this restriction and pointed to documentation/etc.

**Comment by mfojtik** [comment]
@csrwng @hferentschik

**Comment by mfojtik** [comment]
Technically, @csrwng said we should have access to the image metadata, we can read the `User` from there. One problem could be checking what SCC the server use. We don't want to show this when the SCC is set to runAsAny

**Comment by hferentschik** [comment]
+1, very important feature imo, especially when experimenting with images not massaged explicitly to run on OpenShift.

**Comment by csrwng** [comment]
We also don't want to warn on just any USER instruction. It has to be a USER instruction that is non-numeric or that falls outside of the range of the uid allowed by the SCC in place (however we determine that)

**Comment by jwforres** [comment]
We are talking about letting you run an arbitrary docker image from the console create flow as well.  So whatever approach you take here we should make sure it will work for the console.

For reference: https://trello.com/c/fonu3qc5

**Comment by maxandersen** [comment]
+1 for this; whatever we can do to aid users in becoming aware of the limits would be helpful.

**Comment by bparees** [comment]
new-app now warns you if the image declares "USER root"

I don't think we can do anything if the image declares any other user, because images have to declare a user (or default to root) so we'd be warning for every image if we did that.
