### ISSUE TITLE
CLI completions issues

### ISSUE THREAD

**Issue by fabianofranz** [openshift/origin#5695]
- `cmd.MarkFlagFilename` and siblings should also support persistent flags (note that it might require traversing the entire subcommands tree and marking the flag as filename in every command individually)
- ~~Long form of flags marked as filename doesn't autocomplete if the equals sign is present, e.g.: `--filename <tab>` completes, `--filename=<tab>` doesn't. Note that with equals is the version suggested when autocompleting flag names.~~
- ~~Short form of flags marked as filename also doesn't seem autocomplete, e.g.: `-f <tab>`.~~

**Comment by fabianofranz** [comment]
@eparis have you noticed these?

**Comment by eparis** [comment]
I've never dealt with filename flags which were persistent....

With = I thought worked at one time....

**Comment by eparis** [comment]
Completely random thought, maybe https://github.com/spf13/cobra/commit/2e6a42892123dda608922f8af8ce85c3bff19575 helps with the = completion thing...

**Comment by eparis** [comment]
since my version of init_completion is total crap by comparison...

**Comment by fabianofranz** [comment]
@eparis that fixes the completion thing, thanks.
OpenShift has some persistent filename flags, e.g. `--config`, `--client-certificate` and so on.

**Comment by fabianofranz** [comment]
Filename completions fix: https://github.com/openshift/origin/pull/5704

**Comment by fabianofranz** [comment]
Persistent flags completions fix: https://github.com/openshift/origin/pull/5714

**Comment by stevekuznetsov** [comment]
Is this the cause of `--config=` not completing correctly?

**Comment by fabianofranz** [comment]
@stevekuznetsov Yes, which will be fixed by https://github.com/openshift/origin/pull/5714.

**Comment by stevekuznetsov** [comment]
Great!
