### ISSUE TITLE
"Build" button too hard to find on build config page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5698]
I know where the button is and sometimes I have trouble finding it :) I think it's too small and it appears in a different place depending on window width. Seems like there should be a big, obvious "Start Build" button near the top.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/10944478/65b0f3e0-82e7-11e5-8d4d-64eed9b8679a.png)

/cc @jwforres @ajacobs21e

**Comment by jwforres** [comment]
Yeah we talked about in general we need to find a new home for major actions on these pages.  That includes Edit and Delete as well.  Although edit and delete could be pencil and trash can icons.

We should look into this as part of the story that is going to be updating the general theme of everything and removing the tile styles.
