### ISSUE TITLE
Deployments table hidden off screen on deployment config page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5701]
It's not obvious there's a table of deployments below the deployment config information. It's entirely off screen even at large window sizes and definitely on mobile because of all the deployment config settings.

![screen_shot_2015-11-04_at_11_46_12_am](https://cloud.githubusercontent.com/assets/1167259/10945009/e8bda52e-82e9-11e5-83fd-c8d3010ea566.png)

/cc @jwforres @ajacobs21e

**Comment by ajacobs21e** [comment]
switching to a 2 column layout (like Builds) will help

**Comment by jwforres** [comment]
It already is two column until you get to a certain screen width.  May want
to adjust the break point.

**Comment by jwforres** [comment]
Would like this to be addressed as part of https://trello.com/c/2rDfr6Ma
