### ISSUE TITLE
Some import tags never fail

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5711]
https://github.com/openshift/origin/pull/5546#issuecomment-153842544 can result in some image tags retrying forever until they exist.

Needs to be fixed for 3.1.1

**Comment by smarterclayton** [comment]
And be sure to add a test case for that.

**Comment by smarterclayton** [comment]
Too late for 3.1

**Comment by soltysh** [comment]
I've just checked it, I don't see any retries happening in the logs. The result of the import is:
```
[vagrant@openshiftdev origin]$ oc describe is/tester
Name:			tester
Created:		30 seconds ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=[the repository "ironcladlou/deploy-tester" was not found, tag "latest" has not been set on repository "kubernetes/guestbook"]
Docker Pull Spec:	172.30.157.37:5000/test/tester

Tag	Spec				Created	PullSpec	Image
latest	kubernetes/guestbook:latest		<not available>	<not available>
```

**Comment by soltysh** [comment]
@smarterclayton unless you're able to provide a reproducer can you please close this, pretty please. I don't want to show up in @danmcp's emails :wink:

**Comment by pweil-** [comment]
I also attempted to create the same IS in the comment and received

```
openshift.io/image.dockerRepositoryCheck=tag "latest" has not been set on repository "kubernetes/guestbook"
```

@smarterclayton are we reproducing it wrong?

**Comment by smarterclayton** [comment]
We may be ok.  Closing for now
