### ISSUE TITLE
please update documentation for overriding ext service subdomain

### ISSUE THREAD

**Issue by vnugent** [openshift/origin#5721]
From: Clayton Coleman 
That setting is only applied from the routers now, it has no effect.
We need to document that.

> In v3.0.2.0 I was able to set a subdomain name for external services in master-config.yaml
>
> In 3.0.2.903 I can't seem to get that to work.  My services are still resolved to the default, router.default.svc.cluster.local despite a different value is set in master-config.yaml.  Any idea?
>
```
# oc version
 oc v3.0.2.903-114-g2849767
 kubernetes v1.2.0-alpha.1-1107-g4c8e6f4
```

**Comment by pweil-** [comment]
Testing this out for routes works as expected

master-config.yaml
```
routingConfig:
  subdomain: custom.domain
```

route
```
[pweil@localhost paul_temp]$ cat route-nohost.json 
 {
      "kind": "Route",
      "apiVersion": "v1",
      "metadata": {
        "name": "route1"
      },
      "spec": {
        "to": {
          "kind": "Service",
          "name": "hello-pod"
        }
      }
}

[pweil@localhost paul_temp]$ oc get route
NAME      HOST/PORT                      PATH      SERVICE     LABELS    INSECURE POLICY   TLS TERMINATION
route1    route1-default.custom.domain             hello-pod   
```

**Comment by vnugent** [comment]
I apologize.  After making sure atomic-openshift-master service has been restarted couple times and deployed a new test project.  DNS is now working as expected.
