### ISSUE TITLE
[extended] KubeletManagedEtcHosts [It] should test kubelet managed /etc/hosts file

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5727]
```console
>>> testContext.KubeConfig: /tmp/openshift-extended-tests/core/openshift.local.config/master/admin.kubeconfig
• Failure [17.605 seconds]
KubeletManagedEtcHosts [It] should test kubelet managed /etc/hosts file 
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubelet_etc_hosts.go:54

  Nov  4 20:32:20.396: /etc/hosts file should be kubelet managed, but is not: "172.17.0.62\ttest-pod\n127.0.0.1\tlocalhost\n::1\tlocalhost ip6-localhost ip6-loopback\nfe00::0\tip6-localnet\nff00::0\tip6-mcastprefix\nff02::1\tip6-allnodes\nff02::2\tip6-allrouters\n"

  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubelet_etc_hosts.go:113
------------------------------
    fail    KubeletManagedEtcHosts should test kubelet managed /etc/hosts file (17.604986343s)
```

**Comment by mfojtik** [comment]
@smarterclayton FYI

**Comment by smarterclayton** [comment]
What Docker are you on?

**Comment by aveshagarwal** [comment]
I ran e2e test (KubeletManagedEtcHosts) with latest origin code  and it passed. I am on F22 and docker version is docker-1.8.2-7.gitcb216be.fc22.x86_64. Here are the steps I took:

Start master:

```
openshift start master --config=./openshift.local.config/master/master-config.yaml
```

Start node:

```
openshift start node --config=./openshift.local.config/node-192.168.122.253/node-config.yaml
```
I built e2e from kubernetes repo and ran as follows:

```
e2e.test --host="https://127.0.0.1:8443" --provider="local" --ginkgo.v=true -ginkgo.focus="KubeletManagedEtcHosts" --kubeconfig="/root/origin/openshift.local.config/master/admin.kubeconfig"
```

Here are the logs of passed test: http://fpaste.org/287818/68466101/

@mfojtik  Could you provide more information about the steps you ran and also about your environment?

**Comment by mfojtik** [comment]
This was from Jenkins origin extended.

**Comment by aveshagarwal** [comment]
@mfojtik Is it possible to get more verbose failure output (with --ginkgo.v=true)?

**Comment by aveshagarwal** [comment]
Can we close this as I dont see this failing now?:

=== RUN "Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubelet_etc_hosts.go":
>>> testContext.KubeConfig: /tmp/openshift-extended-tests/core/openshift.local.config/master/admin.kubeconfig
I0118 14:56:09.098061   29715 loader.go:241] Config loaded from file /tmp/openshift-extended-tests/core/openshift.local.config/master/admin.kubeconfig
I0118 14:56:11.108843   29715 loader.go:241] Config loaded from file /tmp/openshift-extended-tests/core/openshift.local.config/master/admin.kubeconfig
I0118 14:56:11.109646   29715 loader.go:241] Config loaded from file /tmp/openshift-extended-tests/core/openshift.local.config/master/admin.kubeconfig
    ok       KubeletManagedEtcHosts should test kubelet managed /etc/hosts file (19.558486375s)
