### ISSUE TITLE
[extended] [It] should build a django image and run it in a pod 

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5729]
```console
• Failure [134.097 seconds]
samplerepo: test the sample application repositories samplerepo: images: parallel: test python images with django-ex repo Building django app from new-app [It] should build a django image and run it in a pod 
/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/sample_repos.go:75

  Expected error:
      <*errors.errorString | 0xc2081380b0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/sample_repos.go:73
------------------------------
    fail    samplerepo: test the sample application repositories samplerepo: images: parallel: test python image ... (2m14.097461503s)
```

@bparees FYI

**Comment by mfojtik** [comment]
this is possible flake?

**Comment by bparees** [comment]
you tell me, does it fail every time?

can the django app be built+deployed outside of the test code?  Last time I hit an issue like this, the dancer repo had bit-rotted to the point where the app didn't work at all.  Is that what happened here?

**Comment by mfojtik** [comment]
@bparees i tried django last week and it was working, going to try now

**Comment by mfojtik** [comment]
@bparees this is a flake, django is working normally... will keep this open for some time to see if we hit this issue more often

**Comment by mfojtik** [comment]
@bparees I can't reproduce this anymore (locally or in jenkins). I think this must be some github flake or networking problem. Maybe we should build some retry mechanism into our images or in the S2I builder itself. (iow. when git clone fails, retry after few seconds).

**Comment by bparees** [comment]
@mfojtik did we have any logs from the application container when this failed?

**Comment by mfojtik** [comment]
@bparees I think that logs are gone by now, but I haven't seen any failures like this recently. Also based on this being a timeout, I assume that it failed to pull the image or something (so a dockerhub flake/internal registry pruned/etc?)

**Comment by bparees** [comment]
i don't think we want retry built into s2i (if anything we want less clone intelligence there, not more).

will close this as a potential github flake for now.
