### ISSUE TITLE
Recycling to work with new security UID:GID

### ISSUE THREAD

**Issue by markturansky** [openshift/origin#5739]
The default implementation of PV Recycling is broken with the new security functionality.

Pods write data with a UID that is not the same UID the recycler runs under, which gives a "permission denied" error.

The recycler should work under as many scenarios as possible within the context of the new security functionality.  Any limitations should be documented clearly.

**Comment by markturansky** [comment]
@pmorie @rootfs @childsb @swagiaal

**Comment by smarterclayton** [comment]
Needs triage for 3.1 - we are *very* close to the window.  Is documentation enough?

**Comment by markturansky** [comment]
Any solution we've come up with so far has resulted in an escalation of permissions for the recycler pod which shouldn't be handled lightly. Recycling would be limited to volumes that allow open access.

**Comment by pmorie** [comment]
@markturansky can you be more specific re: escalation?  Do you mean, the recycler container required additional capabilities, privileged, etc?

Last I heard, you and @rootfs were looking at writing a recycler that did a stat of the volume to determine which uid or gid the recycle had to run as, and then su'd to that id to recycle the volume -- did that not work out?

**Comment by markturansky** [comment]
The linked PR contains a fix.  A privileged container is required and the deployer image requires a few additional tools.

The new "hostmount" service account means users are forced to explicitly partake in this feature by enabling privileged containers in the SCC.

**Comment by rootfs** [comment]
The script has two parts: one to mount the nfs share via nfs v3, the other is sudo. The first part needs privilege escalation, the second part maybe doesn't need it.

Mounting through nfs v3 is to work around [nfs v4 acl](http://linux.die.net/man/5/nfs4_acl) restriction. If the nfs v4 server doesn't set delete permission, recycler won't be able to delete files/directories. The workaround is to mount it through nfs v3, which requires privileged container. 

It is also possible to document that nfs servers must only export the share through nfs v3.

**Comment by ncdc** [comment]
Wouldn't it be better to say "if you're using nfs v4, you must set the delete permission"?

**Comment by rootfs** [comment]
@ncdc yes, that's a good idea, or we suggest disabling nfs v4 acl.

**Comment by liggitt** [comment]
> Wouldn't it be better to say "if you're using nfs v4, you must set the delete permission"?

+1. Requiring delete permission makes a lot of sense (to me, anyway) if you want origin to recycle those volumes for you.

**Comment by danmcp** [comment]
Closing in favor of https://bugzilla.redhat.com/show_bug.cgi?id=1279335 and https://github.com/openshift/origin/pull/5792
