### ISSUE TITLE
Extension controllers should not be run when extensions/* APIs are disabled

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5747]
Config allows disabling the extensions/v1beta1 API. When disabled, the server should still start, but the HPA and Job controllers should not run.

An integration test similar to the one in https://github.com/openshift/origin/pull/5738/ should ensure the server starts normally, HPA and Job resources cannot be created, and namespace deletion succeeds normally.

**Comment by deads2k** [comment]
Wasn't @DirectXMan12 looking at this?

**Comment by liggitt** [comment]
Was mentioned in https://github.com/openshift/origin/pull/5738/files#r44077541 but I wanted to track it specifically.

**Comment by smarterclayton** [comment]
Is this still 1.1 target?

**Comment by liggitt** [comment]
yes

**Comment by liggitt** [comment]
fixed in #5738
