### ISSUE TITLE
Tighten spacing on pod logs page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5750]
The spacing of the content above the log is a bit odd. The fields have different margins. This could probably all fit on one or maybe two lines to give more room for the log.

![archive-button](https://cloud.githubusercontent.com/assets/1167259/10998358/a2e460d6-8462-11e5-98be-01b092b02c1f.png)

/cc @jwforres @sg00dwin @benjaminapetersen

**Comment by jwforres** [comment]
This is also related to the discussion of whether we move status to the area above the tabs.

**Comment by spadgett** [comment]
Fixed by #7669 and #8344.

**Comment by spadgett** [comment]
#7652 tracks adding status above tabs
