### ISSUE TITLE
SAR/RAR does not allow checking API group

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5751]

**Comment by liggitt** [comment]
cc @deads2k

**Comment by liggitt** [comment]
Only affects SAR/RAR checks, means API groups can't be checked remotely, but nothing requires that ability at the moment.

**Comment by smarterclayton** [comment]
Was this fixed?

**Comment by liggitt** [comment]
no, wip in https://github.com/openshift/origin/pull/5756
