### ISSUE TITLE
Diagnostics command doesn't find cluster-admin, won't run diagnostics

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5753]
```
$ openshift ex diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '../origin/openshift.local.config/master/admin.kubeconfig'
[Note] Failed creating client from config; client diagnostics will be limited to config testing
[Note] No cluster-admin client config found; skipping cluster diagnostics.

[Note] Running diagnostic: ConfigContexts[/10-1-2-2:8443/test]
       Description: Validate client config context is complete and has connectivity
```

The server was *not* running at the time - if that's necessary this would be lower priority, but as is this was very confusing.

**Comment by smarterclayton** [comment]
@deads2k

**Comment by smarterclayton** [comment]
If cluster diagnostics are broken in 3.1 that's an issue, if it's just user error we'll drop priority.

**Comment by deads2k** [comment]
Checked locally, its just a bad message.  Works ok when the server is up.

**Comment by smarterclayton** [comment]
Verified - dropping priority, we should definitely message this (I had no idea why).  Maybe we should check if the server is up and display a "server appears to be down, cannot perform further checks" or similar.

**Comment by sosiouxme** [comment]
If the client connection doesn't work then there's no way to tell you have cluster admin access. However you should get a notice from the client diagnostic that it couldn't reach the server:

```
[Note] Running diagnostic: ConfigContexts[default/172-18-13-95:8443/system:admin]
       Description: Validate client config context is complete and has connectivity
       
ERROR: [DCli0009 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:276]
       The current client config context is 'default/172-18-13-95:8443/system:admin':
       The server URL is 'https://172.18.13.95:8443'
       The user authentication is 'system:admin/172-18-13-95:8443'
       The current project is 'default'
       (*url.Error) Get https://172.18.13.95:8443/api: dial tcp 172.18.13.95:8443: connection refused
       
       This means that when we tried to connect to the master API server, we
       reached the host, but nothing accepted the port connection. This could
       mean that the master is stopped, or that a firewall or security policy
       is blocking access at that port.
       
       You will not be able to connect or do anything at all with this server
       until this server problem is resolved or you specify a corrected
       server address.
```

Are you not getting this? Or just saying that the message about cluster-admin should be clearer?

**Comment by smarterclayton** [comment]
The message led me to believe that diagnostics was broken, rather than the
condition you described was in play.  Either one being improved would
prevent that impression.

On Nov 10, 2015, at 8:14 AM, Luke Meyer <notifications@github.com> wrote:

If the client connection doesn't work then there's no way to tell you have
cluster admin access. However you should get a notice from the client
diagnostic that it couldn't reach the server:

[Note] Running diagnostic:
ConfigContexts[default/172-18-13-95:8443/system:admin]
       Description: Validate client config context is complete and has
connectivity

ERROR: [DCli0009 from diagnostic
ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:276]
       The current client config context is
'default/172-18-13-95:8443/system:admin':
       The server URL is 'https://172.18.13.95:8443'
       The user authentication is 'system:admin/172-18-13-95:8443'
       The current project is 'default'
       (*url.Error) Get https://172.18.13.95:8443/api: dial tcp
172.18.13.95:8443: connection refused

       This means that when we tried to connect to the master API server, we
       reached the host, but nothing accepted the port connection. This could
       mean that the master is stopped, or that a firewall or security policy
       is blocking access at that port.

       You will not be able to connect or do anything at all with this server
       until this server problem is resolved or you specify a corrected
       server address.

Are you not getting this? Or just saying that the message about
cluster-admin should be clearer?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5753#issuecomment-155468631>.

**Comment by sosiouxme** [comment]
So the existing messaging in this use case was like this:
```
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/openshift.local.config/master/admin.kubeconfig'
[Note] Failed creating client from config; client diagnostics will be limited to config testing
[Note] No cluster-admin client config found; skipping cluster diagnostics.
```

Saying "Failed" is presumably what makes this alarming. And then when you keep reading, you wonder "wait a minute... I'm not cluster-admin??"

All it's trying to get across is that since you don't have a working client, the diagnostics we can run are pretty restricted; don't be surprised at the brevity of the output. Let me know if the [updated wording](https://github.com/openshift/origin/pull/6512) does any better at giving the right impression:
```
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/openshift.local.config/master/admin.kubeconfig'
[Note] Could not configure a client connection, so client diagnostics are limited to config testing
[Note] Could not configure a client with cluster-admin permissions for the current server, so cluster diagnostics will be skipped
```

Of course the next diagnostic tries to connect to the server and explains verbosely what it means when it can't. But you need to read that far without thinking diagnostics is haywire.

**Comment by smarterclayton** [comment]
That's fine

**Comment by sosiouxme** [comment]
@smarterclayton PR is merged, could you close this?
