### ISSUE TITLE
API should send Date header so clients can handle clock skew for relative time calculations

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#5762]
if client's clock is behind by even a few seconds we could end up with negative relative time on the various clients

**Comment by jwforres** [comment]
@liggitt @smarterclayton as previously discussed

**Comment by smarterclayton** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/16976

**Comment by sttts** [comment]
Compare https://github.com/kubernetes/kubernetes/issues/16976#issuecomment-228010465: date header exists already?

**Comment by sttts** [comment]
https://github.com/kubernetes/kubernetes/issues/16976 is closed. I guess this one can be closed as well?
