### ISSUE TITLE
produce e2e.test as a build product with the ability to extend from upstream 

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#5765]
There exists a script under the repository https://github.com/openshift/origin/blob/master/hack/test-kube-e2e.sh which allow folks to run the upstream e2e.test binary against openshift.  What appears odd to me is why we don't produce it as a direct build product for both QE and Perf to use directly, or to modify with their own tests.  

Currently there exists separate tests, which can/should be rolled into an e2e.test binary which is a strict superset from upstream . 

/cc @pmorie @jeremyeder 

doc-ref: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md for questions, ping myself or @jayunit100

**Comment by pmorie** [comment]
@timothysc there's actually another way to do this as well: `test/extended/core.sh`

**Comment by jayunit100** [comment]
After taking a quick look... Im wondering, Is this simply because the e2e's are godeps as opposed to source files?

```
./Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/util.go:	// However, now Density test is producing ~26000 events and Load capacity test
./Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/density.go:var _ = Describe("Density", func() {
./Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/density.go:	type Density struct {
./Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/density.go:	densityTests := []Density{
```

If so, I guess the solution is to actually add the `test/e2e/` stuff into origin?

**Comment by timothysc** [comment]
@jayunit100 Some tests actually violate some suppositions made in openshift.  e.g. Density tries to wipe out * namespaces which will affect openshift.  

/cc @rrati @derekwaynecarr

**Comment by pmorie** [comment]
@jayunit100 We need to have a binary that references both the upstream e2e test package and packages with the origin extensions, similar to `test/e2e/e2e_test.go` in upstream.

**Comment by jeremyeder** [comment]
Is this working now?

**Comment by jayunit100** [comment]
Not yet, me and Paul will be syncing on it today, discussed it some during kubecon.. I'll update this thread with notes paul had

**Comment by timothysc** [comment]
@jeremyeder b/c of the P3 prio and most tests can run, we're not going to switch focus unless folks deem it a priority.  We have other large issues that are in flight upstream that we are working on atm.  Both storage enablement and backoffs.

**Comment by jayunit100** [comment]
Ive updated the fix to this in  the fresh PR #6541.

**Comment by marun** [comment]
What is the relationship of this issue to the origin extended test suite's execution of the kube e2e tests?  At least in the case of the networking extended tests, it is already possible to run any of the kube tests in addition to openshift-specific tests.  The test binary is currently only built by the test runner, but this could be fixed easily enough.

I wrote hack/test-kube-e2e.sh as a stop-gap because I didn't know enough at the time to run the vendored kube tests against openshift.  The openshift extended suite has since been updated to consume the vendored kube tests via test runners in test/extended.  For example, networking tests are run via [test/extended/networking.sh] (https://github.com/openshift/origin/blob/master/test/extended/networking.sh), the test binary it uses includes all the kube e2e tests as well as origin-specific tests, and the wrapper uses ginko.focus and ginkgo.skip to filter the kube tests to the desired subset.

**Comment by jayunit100** [comment]
the goal, for this issue, is an e2e build artifact which has parity with the upstream e2es, and which is packagable by openshift/extensible by openshift.

**Comment by liggitt** [comment]
The kube e2e's are not built in a way that easily allows composing them into a bigger out-of-package e2e suite. The first attempts at a composed e2e suite containing origin and kube e2e tests had to go to extraordinary lengths to get around cross-package test dependency restrictions. If a strong case can be made for a single e2e binary compositing kube e2e tests and origin e2e tests, we should make that case upstream, and do the work upstream to allow wrapping it (putting the e2e guts in a non _test file, and making the _test file a 3-line function we wouldn't mind duplicating to compose our own e2e suite binary).

If a strong case can't be made, we shouldn't contort build scripts to do it... they'll be too fragile and likely fail with the slightest change in the upstream e2e test package.

**Comment by jayunit100** [comment]
So, I see your point: but, We can make the hack less ugly, or change the hack impl, but probably shouldnt backpeddle a defined requirement based on the fact that it requires an ugly implementation ....
- I agree we should work with upstream to libraricize the E2Es.  Issue created here: #19461.  We will see what the feedback is.
- In the meanwhile... My Devils advocate response: this feature adds a critical validation asset for QE/QA which, although diminished by the fact that it carries a hack.. is still sufficiently important for us to keep around.

**Comment by timothysc** [comment]
cross-ref https://github.com/kubernetes/kubernetes/pull/19476

**Comment by jayunit100** [comment]
Thanks to everyone for the feedback on this.  
- The Upstream patch is pending.
- Next step: Add our own `e2e_test.go` wrapper into openshift, which uses the new e2e test lib in upstream.
- This requires tracking the next rebase.  

So lets keep this issue open until we get the rebase, at which point, we will add the _test file that uses the new lib.

**Comment by jayunit100** [comment]
Hi @liggitt :  Once the upstream patch merges, can we cherry pick it into openshift Godeps (or else, I could C/P the upstream file into test/e2e so we carry the patch until the rebase contains the libification patch ).

**Comment by liggitt** [comment]
there's a rebase in progress, and another will likely start as soon as it is delivered. We're holding non-critical Godep cherry-picks for the moment

**Comment by timothysc** [comment]
@jayunit100 please re-open and refresh once pending next rebase cycle.

**Comment by jayunit100** [comment]
ack will reopen pr that will assume libification  completed shortly

**Comment by jayunit100** [comment]
cc @smarterclayton had a question of how we would build and distribute this.  We can discuss in this thread the end goal of how the make target will get embedded into rpm specs and so on...

**Comment by timothysc** [comment]
Same locs as what is done for k8s in rhel-extras,  ill dig up the details
later.  But essentially the end goal would be unifying cluster conformance
tests.

**Comment by liggitt** [comment]
Is this complete?

**Comment by jayunit100** [comment]
Yeah we can close.
The kubedescribe annotation 
will allow filtering using k8s.io tags

**Comment by timothysc** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/22206
