### ISSUE TITLE
Deleted build not removed from builds table on build config page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5766]
We are watching builds and receiving the DELETE event in the web socket. The build is not removed from the table, however.

![screen shot 2015-11-06 at 2 57 11 pm](https://cloud.githubusercontent.com/assets/1167259/11007368/674e9228-8497-11e5-9590-e2abe13aa58e.png)

/cc @jwforres

**Comment by jwforres** [comment]
Ah yep we aren't resetting $scope.unfilteredBuilds to {}

**Comment by jwforres** [comment]
While fixing this should probably clean up the performance of this and not loop back over all the builds every time we get an event.  Should check DC page as well.
