### ISSUE TITLE
Deployer POD does not start if SCC restricted "runAsUser" is set to MustRunAsNonRoot 

### ISSUE THREAD

**Issue by MacThrawn** [openshift/origin#5769]
We configured our cluster to run restricted POD's with the MustRunAsNonRoot users. After this change the deployer POD doesn't start. The POD status is Pending. 

We think the problem is that the deployer POD has no USER set. The POD runs with the other modes because it runs as root if the mode is set to RunAsAny or as random user if the mode is set to MustRunAsRange. In MustRunAsNonRoot mode the deployer POD tries to run as root what is not allowed.

**Comment by smarterclayton** [comment]
@ironcladlou @pweil- the deployer pod image should probably set a non-root UID. @sdodson we may have to change the image in Origin.

**Comment by smarterclayton** [comment]
Triage for p1 candidate

**Comment by pweil-** [comment]
@ironcladlou - as discussed this morning, we should just add a USER directive to the deployer Dockerfile.

Also, please check the registry image which can run under the restricted SCC.  The router and builder pods requires access to an elevated SCC so this shouldn't be an immediate issue when someone changes the restricted SCC but let's open a follow up for the corner case of an elevated SCC with a NonRoot strategy.

**Comment by ironcladlou** [comment]
@pweil- 
>Also, please check the registry image which can run under the restricted SCC.

You're right- the registry will fail to deploy using `MustRunAsNonRoot` due to the lack of a `USER` directive.

**Comment by smarterclayton** [comment]
Is there an issue open for that?

On Nov 9, 2015, at 10:41 AM, Dan Mace <notifications@github.com> wrote:

@pweil- <https://github.com/pweil->

Also, please check the registry image which can run under the restricted
SCC.

You're right- the registry will fail to deploy using MustRunAsNonRoot due
to the lack of a USER directive.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5769#issuecomment-155150986>.

**Comment by ironcladlou** [comment]
@smarterclayton 
>>You're right- the registry will fail to deploy using MustRunAsNonRoot due to the lack of a USER directive.

>Is there an issue open for that?

See the linked #5803
