### ISSUE TITLE
Error updating deployment status to Pending

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#5773]
I'm following the setup instructions using Vagrant in the CONTRIBUTING.adoc and run into a snag where the deployment status on my registry does not update:
```
Events:
  FirstSeen	LastSeen	Count	From		SubobjectPath	Reason		Message
  ─────────	────────	─────	────		─────────────	──────		───────
  31m		31m		1	{deployer }			failedUpdate	Error updating deployment default/docker-registry-1 status to Pending
```

Following the document seems to work initially, but when I began to create projects & run builds I would get errors like this:

```
E1106 21:46:32.771910       1 dockerutil.go:74] push for image 172.30.53.88:5000/foo/origin-ruby-sample:latest failed, will retry in 5s seconds ...

1 builder.go:55] Build error: Failed to push image. Response from registry is: API error (500):  v1 ping attempt failed with error: Get http://172.30.53.88:5000/v1/_ping: read tcp 172.30.53.88:5000: connection reset by peer
```
@bparees have thoughts? @stevekuznetsov suggested I ping you on this one.

**Comment by bparees** [comment]
is your registry pod running?  (oc get pods -n default)?

what's in the logs for the registry deployment pod?

registry issues typically go to @pweil- and deployment issues also go to him or @ironcladlou 

build issues come to me, but only if you have a working registry :)

**Comment by stevekuznetsov** [comment]
@bparees No pods were running.
`oc logs` couldn't get from the deployer - it had died already.

**Comment by bparees** [comment]
oc logs should still be able to get logs from a dead pod.

**Comment by benjaminapetersen** [comment]
I see a server error when I try to get logs from the registry pod:

```
$ oc logs docker-registry-1-deploy
Error from server: Internal error occurred: failed to get status for pod "docker-registry-1-deploy" in namespace "default"
```

**Comment by benjaminapetersen** [comment]
I'm gonna try `vagrant box remove fedora_inst` and clean slate everything, just in case something old is causing issues.

**Comment by kargakis** [comment]
> I see a server error when I try to get logs from the registry pod:

Did you restarted the server at some point?

**Comment by benjaminapetersen** [comment]
I ran through the whole process at least 5 times friday, `vagrant destroy` all the way through the setup instructions, always ending in the same place.

**Comment by benjaminapetersen** [comment]
For reference, I ran into these issues while [working on a PR to update the contributing doc](https://github.com/openshift/origin/pull/4970).

**Comment by kargakis** [comment]
> I ran through the whole process at least 5 times friday, vagrant destroy all the way through the setup instructions, always ending in the same place.

Did you run `vagrant box remove fedora_inst` prior to get up and running with a new box?

ps. the following error is most probably https://github.com/openshift/origin/issues/5640 which is fixed upstream and soon will be in Origin too.
```
$ oc logs docker-registry-1-deploy
Error from server: Internal error occurred: failed to get status for pod "docker-registry-1-deploy" in namespace "default"
```

**Comment by benjaminapetersen** [comment]
@kargakis running that this morning... and getting more interesting results once i reach `make clean build`:  
```
[vagrant@localhost origin]$ make clean build
rm -rf _output Godeps/_workspace/pkg
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
# github.com/openshift/origin/cmd/openshift
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /bin/gcc: cannot allocate memory

!!! Error in hack/../hack/common.sh:131
	'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binaries[@]}"' exited with status 2
Call stack:
	1: hack/../hack/common.sh:131 os::build::build_binaries(...)
	2: hack/build-go.sh:15 main(...)
Exiting with status 1
!!! Error in hack/../hack/common.sh:115
	'( os::build::setup_env; local version_ldflags; version_ldflags=$(os::build::ldflags); os::build::export_targets "$@"; local platform; for platform in "${platforms[@]}";
do
    os::build::set_platform_envs "${platform}"; echo "++ Building go targets for ${platform}:" "${targets[@]}"; go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binaries[@]}"; os::build::unset_platform_envs "${platform}";
done )' exited with status 1
Call stack:
	1: hack/../hack/common.sh:115 os::build::build_binaries(...)
	2: hack/build-go.sh:15 main(...)
Exiting with status 1
Makefile:31: recipe for target 'build' failed
make: *** [build] Error 1
```
[Contributing.adoc](https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc) suggests `export OPENSHIFT_MEMORY=2096`.  I've also tried `export OPENSHIFT_MEMORY=3144` and `export OPENSHIFT_MEMORY=4192` to keep bumping memory but no change.

**Comment by kargakis** [comment]
@benjaminapetersen I am not sure about this error. Maybe try to compile on your host?

**Comment by pweil-** [comment]
did you do a `vagrant reload` or kill/restart after adjusting the mem?  I usually run with 4192 and have not had an issue compiling lately.

**Comment by benjaminapetersen** [comment]
@pweil- just did, and 4192 works. I'll update the contributing doc to this new val.

**Comment by benjaminapetersen** [comment]
@bparees @kargakis running `vagrant box remove fedora_inst` and ensuring latest image may be resolving everything in this issue.  I'm going to run through the whole process a couple more times & confirm.

**Comment by benjaminapetersen** [comment]
Confirmed, fixes issue.

I'll add a note under Vagrant #4 of the contributing file suggesting `vagrant box remove fedora_inst` if you have had a previous version setup & close this issue.

**Comment by kargakis** [comment]
@benjaminapetersen there is already a note in CONTRIBUTING regarding `vagrant remove box`, we may want to position it better though: https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-on-virtual-machine-using-vagrant (See tip below 11.)

**Comment by benjaminapetersen** [comment]
@kargakis yup, I ping you on the PR for review.

**Comment by naveenkumartangallapally** [comment]
hi  @pweil
I setup  my openshift origin environment using below 

root@cgdell72-Lenovo-B50-80:~# oc version
oc v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.1.33:8443
openshift v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4

after dashboard luanched succsessfully but my docker registry and router are  in pending state.

i am getting below error from logs:
root@cgdell72-Lenovo-B50-80:~# oc volume dc/docker-registry  --list
Flag --list has been deprecated, Volumes and volume mounts can be listed by providing a resource with no additional options.
Error from server (NotFound): deploymentconfigs "docker-registry" not found

**Comment by naveenkumartangallapally** [comment]
[https://192.168.1.33:8443/console/project/default/overview](url)

**Comment by naveenkumartangallapally** [comment]
hi bparees

**Comment by pweil-** [comment]
@naveenkumartangallapally this issue has been closed for over a year.  Please create a new issue if you need some help.  Thanks.

**Comment by naveenkumartangallapally** [comment]
hi pweil,

i created a new issue with 13711,kindly help on the issue.
