### ISSUE TITLE
Python 3 does not have proper virtualenv

### ISSUE THREAD

**Issue by avinassh** [openshift/origin#5780]
(I am not sure if this is the right place to report bugs of [openshift](https://openshift.redhat.com), if not please point me to where I should report it)

Whenever I create a new app with Python 3, the virtualenv does not have `activate_this.py` file. Usually it is located at 

```
/var/lib/openshift/<app_id>/python/virtenv/bin/activate_this.py
```

Even [docs](https://developers.openshift.com/en/python-getting-started.html#step3) also suggest same path, however there is no such file created. Infact, `bin` directory is not even present. Its actual location is

```
/var/lib/openshift/<app_id>/python/virtenv/venv/bin
```

`bin` should contain `activate_this.py`, but it does not have it.

To reproduce, create a new app with Python 3.3:

```
rhc create-app app-name python-3.3
```

ssh into app and look in `python` directory.

**Comment by smarterclayton** [comment]
Hi @avinassh, is this about OpenShift Origin M4 or earlier?  Or is it about OpenShift 3?  If the former, you can open the issue at https://github.com/openshift/origin-server

**Comment by avinassh** [comment]
I am not running my own instance of Openshift, I used https://www.openshift.com. Thats why I wanted to know where is the right place to report.

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin-server would be the right place.

**Comment by avinassh** [comment]
Thank you!
