### ISSUE TITLE
Make heapster namespace, scheme, port configurable

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5781]
https://github.com/openshift/origin/pull/5763 changed the HPA metrics client to use https to contact the heapster service, but the namespace, scheme, service name and port should all be configurable.

**Comment by liggitt** [comment]
cc @DirectXMan12

**Comment by smarterclayton** [comment]
@jcantrill @mwringe

**Comment by liggitt** [comment]
Notably, the current setup will only work if the heapster service is set up in the openshift-infra namespace, with a single, nameless port, and the heapster pods are set to use https

**Comment by pweil-** [comment]
Marking p2 for now since this is slated for the 1.1.1 milestone

**Comment by liggitt** [comment]
When we make it configurable, we also need to adjust the bootstrap policy, and/or document what permissions you have to grant the HPA service account to query the service

**Comment by jcantrill** [comment]
@mwringe I assume we should consider closing this issue as heapster is going out of favor for the metrics api server?

**Comment by mwringe** [comment]
I don't think this has been a high priority item since it was created and with Heapster being deprecated, I don't see the effort in making this change at all.

@liggitt Any reason to keep this open?

**Comment by liggitt** [comment]
if we expect it to stay the same until we move off heapster, no issue with closing this
