### ISSUE TITLE
Our builders, deployers, and the router need to stop using glog

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#5788]
sti code has already switched for >3 verbosity logs, the same thing should happen for our builders, deployers,and router.

sti changes:
https://github.com/openshift/source-to-image/pull/321
https://github.com/openshift/source-to-image/pull/323

Or else:
```
Installing sinatra (1.4.5)
Installing sinatra-activerecord (2.0.3)
Using bundler (1.3.5)
Your bundle is complete!
It was installed into ./bundle
---> Cleaning up unused ruby gems ...
I1109 11:11:57.220593       1 sti.go:213] Using provided push secret for pushing 172.30.104.214:5000/test/origin-ruby-sample:latest image
I1109 11:11:57.220704       1 sti.go:217] Pushing 172.30.104.214:5000/test/origin-ruby-sample:latest image ...
I1109 11:12:56.237943       1 sti.go:233] Successfully pushed 172.30.104.214:5000/test/origin-ruby-sample:latest
```

cc: @mfojtik @bparees

**Comment by mfojtik** [comment]
@kargakis +1 I think by default we should keep the logs glog free unless there is an error logged. Also we should do this in sync with s2i changes, so everything below V(3) will not get the glog prefix and everything else does.

**Comment by bparees** [comment]
@mfojtik you're not going to be able to do what you did in s2i because there are a ton of log statements you'd have to if/else.

**Comment by bparees** [comment]
i don't know why you guys hate useful logging information so much.

**Comment by mfojtik** [comment]
@bparees I don't hate the timestamps (they are useful) I just hate the sti.go:XYZ prefix which is not that useful for normal users and it is duplicated. The prefix also makes the log a little bit messy in the result for 'regular users'

**Comment by kargakis** [comment]
> i don't know why you guys hate useful logging information so much.

Well, because --timestamps ?

**Comment by bparees** [comment]
> Well, because --timestamps ?

doesn't give me filenames or line numbers.

**Comment by kargakis** [comment]
Why a user should care about these info? I see how filenames and line
numbers are useful for debugging but these are logs that end up in clients
and people won't really have any use for them anyway.

**Comment by bparees** [comment]
> Why a user should care about these info? I see how filenames and line numbers are useful for debugging but these are logs that end up in clients and people won't really have any use for them anyway.

because logs end up coming to us when things break and having to send the user back to recreate it so we can get the information is not a good experience.

**Comment by mfojtik** [comment]
@bparees we can always just grep the line of code, I assume as we go the numbers in logs might always reflect the reality

**Comment by kargakis** [comment]
I think this issue equally applies for the deployers, router, and the registry (we don't have any control over the registry logs though).

**Comment by smarterclayton** [comment]
The rough use case is "when I want debug logs, I ask for debug logs, otherwise, show me the info I need".  I don't think filename and warning level are for the normal case.  I think those are debug.  So someone has to ask for them.

**Comment by kargakis** [comment]
https://github.com/openshift/origin/pull/8787 updates our deployers

**Comment by kargakis** [comment]
https://github.com/openshift/origin/pull/8786 updates the builders

**Comment by kargakis** [comment]
We still need to update the router logs @pweil- @ramr

**Comment by smarterclayton** [comment]
Router can continue using glog.  It's infra, not user facing.  Same for
registry and keepalived.

On Jun 10, 2016, at 5:39 AM, Michail Kargakis <notifications@github.com>
wrote:

We still need to update the router logs @pweil- <https://github.com/pweil->
@ramr <https://github.com/ramr>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/5788#issuecomment-225139165>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p9Z0Z6L5YuO-b3PqxOGnzwIDKimkks5qKTDHgaJpZM4Geg4y>
.

**Comment by kargakis** [comment]
Then this issue can be closed.
