### ISSUE TITLE
Add support for github webhook "secret" field

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#5789]
Our current webhook secret has nothing to do with actual github webhook secret, which leads to many confusions among our users. We should make clear separation between the secret being part of the url and the one provided when configuring webhook. That topic was postponed when I initially implemented webhook but I think we should get back to the topic.

@bparees @mfojtik thoughts?

**Comment by bparees** [comment]
should be able to handle this in the github webhook documentation:
https://docs.openshift.org/latest/dev_guide/builds.html#webhook-triggers

**Comment by bparees** [comment]
to be clear, you have to leave the "secret" blank on the the github interface when setting up a webhook, right?  (or at best it doesn't matter what you put in that field)

**Comment by soltysh** [comment]
We should fix that in the docs (will work on a PR tomorrow). And just like you said it does not matter what you put in that field in gh, we don't check it, but I'll stick with leave it empty. Furthermore we've discussed back then we want to support that field, that's why I've opened this issue.

**Comment by bparees** [comment]
>  Furthermore we've discussed back then we want to support that field, that's why I've opened this issue.

ok can you reword this issue description so it is just about supporting the github "secret" value?   The docs change i think you can handle w/o an issue.

**Comment by bparees** [comment]
@soltysh i've created a trello card for the github secret support.

**Comment by bparees** [comment]
err, created it here: https://trello.com/c/ez141U00/753-support-github-s-secret-for-invoking-webhooks

**Comment by bparees** [comment]
closing this, @soltysh says he doesn't need an issue to remind him to update docs :)
