### ISSUE TITLE
HACKING.md: command for running unit tests with code coverage leads to unexpected result

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#5797]
Quote from [HACKING.md](https://github.com/openshift/origin/blob/769ca7a58178d1e6c914af2cdb0da407f5acabbc/HACKING.md#unit-tests):

> A line coverage report is run by default when testing a single package. To create a coverage report for all packages:
>
> $ OUTPUT_COVERAGE=true hack/test-go.sh pkg/build

When I run this command it creates directory `true` inside of current directory. I believe that we should update example, because it looks like `OUTPUT_COVERAGE` is a boolean parameter, but in fact it's a path to directory with report.

**Comment by mfojtik** [comment]
+1 @php-coder can you do a PR ?

**Comment by php-coder** [comment]
Fixed by PR #5801
