### ISSUE TITLE
Automatically follow log when log fills up screen

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#5799]
I've been building repeatedly and find myself waiting for the 'follow' link to appear so I can click it.  If on the log tab, I think it may be a better experience to auto follow (once the follow link appears also run the fn) and let the user opt out if they don't want this.

**Comment by spadgett** [comment]
I tried this, and it's jarring when you open the log and there is already more than a page of content. You jump straight to the middle with no context. Maybe if we make the follow link always visible so you don't have to wait? Or at least animate the initial scroll?

/cc @jwforres

**Comment by jwforres** [comment]
i would vote for make follow link appear right away over automatically following

**Comment by benjaminapetersen** [comment]
Is a good point, I can see how that would be jarring as well.  Always showing the link would probably work, though might be a little odd if the log is short.

**Comment by jwforres** [comment]
i'm leaning towards not doing anything here, i think either proposed change is going to behave a little weird.  pretty sure we are consistent with what travis does.  objections?

**Comment by benjaminapetersen** [comment]
I'm good with that!

**Comment by spadgett** [comment]
No objection.
