### ISSUE TITLE
Registry fails to deploy when using MustRunAsNonRoot strategy

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#5803]
The registry will fail to deploy (via `oadm registry`) when the restricted SCC `MustRunAsNonRoot` user strategy is used. This is because the registry image Dockerfile has no `USER` directive. The registry doesn't requrie a privileged container, so adding a `USER` directive for a non-root UID should be fine.

Depends on #5769 since the registry is implemented as a deployment.

**Comment by pweil-** [comment]
moved to 1.1.1 based on https://github.com/openshift/origin/pull/5805#discussion_r44430146
