### ISSUE TITLE
Invalid error messages when starting with an empty hostname

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#5809]
If you go to create the configuration with an empty hostname you will get an error message about `--node` missing:

`$ ./openshift start --write-config=openshift.local.config --hostname=`
>Wrote master config to: openshift.local.config/master/master-config.yaml
F1109 15:31:29.847067   26849 start_allinone.go:91] Server could not start: --node must be provided

If you add the `--node` option it will complain the `--node` is an unknown flag:

`$ ./openshift start --write-config=openshift.local.config --hostname= --node=test`
> Error: unknown flag: --node

Note that there is no `--node` option listed, there is a `--nodes` option though

**Comment by liggitt** [comment]
The validation and message come from the `openshift start node` command, where that option *is* `--node`

**Comment by liggitt** [comment]
Why are you trying to create the config with an empty node hostname?

**Comment by mwringe** [comment]
I wasn't exactly trying to set an empty hostname :) it was a configuration problem on my end. It was actually `--hostname=$HOSTNAME` but that environment variable was not set. 

This issue was opened to better handle the error message since its confusing
