### ISSUE TITLE
Master latency or hang on minion reboot/crash

### ISSUE THREAD

**Issue by akram** [openshift/origin#581]
Hi all,

I am facing an issue with the cluster setup: Here is the reproducer:
- Start a clustered installation (works on AWS or VirtualBox)
- Wait for the cluster to be up and running
- Connect to the master
- Perform a cli read operation: exemple openshift cli list pods
- The server replies quickly
- Shutdown a minion
   - Perform a cli read operation: exemple openshift cli list pods
   - The server takes a lon time to reply, up to minutes
- Reboot a minion
   - Perform a cli read operation: exemple openshift cli list pods
   - The server takes a long time to reply
   - Once the minion has rebooted, the server send his reply immediately

This issue may be linked to an etcd refresh or timeout. Can you help in investigating ?

**Comment by akram** [comment]
Hi @smarterclayton
unfortunately it does not. We have Kubernetes-0.7.0-dev now, and the issue remains.
Can you confirm that the upstream merge was done with the last head referenced by GoogleCloudPlatform/kubernetes#2951

**Comment by smarterclayton** [comment]
This should be fixed in the pending rebase - I have all of the changes from upstream and removed some of the quirky minion behavior.

**Comment by smarterclayton** [comment]
Fixed now.

**Comment by akram** [comment]
Thanks, this seem to be fixed in Beta1
