### ISSUE TITLE
Add kubernetes-native ingress system as a router option

### ISSUE THREAD

**Issue by paralin** [openshift/origin#5815]
Would be good to integrate the upstream Kubernetes ingress extension as a routing option.

**Comment by paralin** [comment]
How complex would this be to set up? I suppose a new type of "router" could be implemented that just manages Ingress objects in namespaces. I will investigate this in the coming few days.

**Comment by liggitt** [comment]
There is ongoing debate over whether the ingress object is at the right level of granularity. Until that is more resolved, we likely would not build on top of it.

**Comment by DanyC97** [comment]
@liggitt any info where that debate is held as i'd like to understand more about it?
