### ISSUE TITLE
GUI generate BuildConfig Environment variables not visible in Assemble

### ISSUE THREAD

**Issue by Mangirdaz** [openshift/origin#5817]
I want capability to abstract user from knowing what is inside the images. In example user sets variables in STI build: (via GUI, sti/environment or BuildConfig) OPENSHIFT_VERSION_JDK=default_7
And inside the Builder image i contains separate "alternatives" structure where i manage versions of resources (in this case JDK): 
default -> /usr/java/default
default_7 -> /usr/java/jdk1.7.x_xx
default_8 -> /usr/java/jdk1.8.x_xx
jdk1.7.x_xx -> /usr/java/jdk1.7.x_xx
jdk1.8.x_xx -> /usr/java/jdk1.8.x_xx

So i need to produce new Variable JAVA_HOME inside assemble phase and set it to default_7 -> /usr/java/jdk1.7.x_xx value. This can be easily achieved but this requires capability to create and set variables inside the STI process so they could be visible for the user, who start processes inside final STI image. 

This is needed to abstract resource and version management from user, so i could use same STI image for multiple Databases, JDK, version specific drivers. So it will be one Image per technology with capability to configure it on the fly with requires versions.

**Comment by mfojtik** [comment]
@Mangirdaz does creating custom `run` and `assemble` scripts solve this problem?

**Comment by Mangirdaz** [comment]
I cant produce in example JAVA_HOME variable in assemble and still be able to see in RUN with user who runs the container. I may missed something how to achieve it but i think environment variables cant be produced inside the container to be permanent (i can produce something in one scrip scope, but not store them in something like /etc/environment )

**Comment by Mangirdaz** [comment]
Long story short i want to be able to abstract users from knowing JAVA_HOME location (only one usecase) and just give "marker" default_7 and i will manage all the paths and JRE_HOME, JAVA_HOME, _RUNJAVA. etc. 

Same with databases. User provides ORACLE=11 and i know what i need to load particular 11.2.0.3 drivers to classpath, with modules. and when 11.2.0.4 becomes available i will just switch it inside base images. 

Some kind of abstract resource management.

**Comment by bparees** [comment]
@Mangirdaz if you set an environment variable on a BuildConfig, the variable is available to the assemble script and the run script, which can use that variable value to do whatever configuration they need to.

I'm not seeing how that's insufficient for you to implement what you want here?

If you want to have your assemble script itself define a new env variable, you can have it write a list of env variables to a file and have your run script read that list and define env variables from it.

**Comment by Mangirdaz** [comment]
File approach may work. I would really would like to see the variables produced inside assemble inside pod's description, but I can live without this.
But i still have some other doubt, but i think it may need to be reaised as separate story if my findings comes true: 

So I have set variable in GUI STI build TEST=mytest and set bunch of variables in .sti/environment in GIT. So using both ways (By GUI I mean STI where you provide GIT source code and chose builder image and you get window to configure your buildconfig)

in the run script I have lines:
```
#env test in run
echo $(env) >> /tmp/env.run.test
#create file for test env creation
echo "#!/bin/sh" >> /tmp/source.sh
echo "" >> /tmp/source.sh
echo "export FOO=boo" >> /tmp/source.sh
```
So the file (/tmp/env.run.test) content after STI does not have any variables set in GUI but have ones in .sti/environment file. So my variables is not available in assemble phase and I cant generate any configuration according those. I could do it in run, but this means i don't have stateless image. And i would like configuration to be generated in assemble.

p.s. If i source source.sh file i can see FOO variable.

**Comment by bparees** [comment]
> So the file (/tmp/env.run.test) content after STI does not have any variables set in GUI but have ones in .sti/environment file.

@PI-Victor this sounds like a bug if we're not ensuring both the BuildConfig env variable values and the .sti/environment file variables are available to the assemble script during the build.  Can you do some testing and see what the behavior is?

**Comment by Mangirdaz** [comment]
Renamed. If needed tommorow in will be able to provide more info how this occurs in our env.

**Comment by PI-Victor** [comment]
@bparees sure, i'll take a look  tomorrow and see what's going on.

**Comment by bparees** [comment]
@PI-Victor @Mangirdaz please see my update to the related bug(https://bugzilla.redhat.com/show_bug.cgi?id=1280216)... there is no way to set BuildConfig env variables via the GUI, the GUI only lets you set DeploymentConfig env variables.  The ability to set BuildConfig env variables would be a new feature.

**Comment by Mangirdaz** [comment]
Just a logical question. DeploymentConfig is used during deployment. And deployment happens is Assemble (application deployment). So this is crosses logic in my head :) 

But as you told, it should be possible as now it is limiting in possible use-cases.

**Comment by bparees** [comment]
@jwforres will let you decide what you want to do with this and the associated bug/RFE.

**Comment by Mangirdaz** [comment]
wups, miss-click. (cat on keyboard) :)

Thanks, will wait for answer.

**Comment by Mangirdaz** [comment]
@jwforres, can we expect this for Next year Q1 release for origin and OSE? as conscious for current upcoming one it will not make in :)

**Comment by jwforres** [comment]
@Mangirdaz https://github.com/openshift/origin/pull/5893

**Comment by jwforres** [comment]
@Mangirdaz to clarify, you are correct that it will not make 1.1.0 of origin
