### ISSUE TITLE
Check the usage of filepath.Join() in CLI

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5823]
See: https://github.com/openshift/source-to-image/issues/314

In some cases, the `filepath.Join()` is not doing what you would expect from it. In case you're constructing a path that will be used inside container (iow. a path to a script or command) and you run this on Windows, you will be surprised by the output of this function.

`filepath.Join("/usr/local/bin", "foo")` become `usrlocalbinfoo`.

We should sweep our CLI commands and decide if `filepath.Join()` is the right way or we should using `path.Join()`

**Comment by mfojtik** [comment]
@liggitt FYI

**Comment by jhadvig** [comment]
@danmcp please assign this issue to me. Thanks :)

**Comment by mfojtik** [comment]
@jhadvig bump, still interested at investigating this?
