### ISSUE TITLE
need postgresql extended tests

### ISSUE THREAD

**Issue by bparees** [openshift/origin#5841]
postgresql with EmptyDir storage got broken about a week ago but we only learned it today from QE testing.  We should have extended tests for postgres like we do for mysql.

Further more i'm not sure the existing mysql test is sufficient since it just looks for endpoints but doesn't actually confirm the pods is successfully running.  it's possible the postgres image would pass a test like that since it does start up briefly (possibly long enough to register an endpoint) before failing and getting restarted.

**Comment by mnagy** [comment]
@rhcarvalho requesting for help with MongoDB, I'll take care of MySQL and PostgreSQL

**Comment by rhcarvalho** [comment]
@bparees could you split this into 2 issues and assign me to the mongodb half?
When @mnagy's PR merges it can close the postgresql half.

**Comment by bparees** [comment]
@rhcarvalho done: https://github.com/openshift/origin/issues/5969

@pmorie also fyi.

**Comment by bparees** [comment]
@PI-Victor maybe you can help @mnagy with this also.

**Comment by mnagy** [comment]
Fixed by: https://github.com/openshift/origin/pull/5874
