### ISSUE TITLE
Need a simple client download

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#5842]
We need a download for just the client 'oc' for each release. This should be available for windows, mac, and linux. It should have nothing but the oc executable and it should not contain symlinks. The current download is confusing (relying on simlinks and such) and has a lot of pieces which are not documented in the download. 

We will also need this for the online dedicated beta's and for developers using a server installation of OpenShift.

**Comment by smarterclayton** [comment]
This is resolved in 1.1.0.1

**Comment by thesteve0** [comment]
Thanks!
