### ISSUE TITLE
We need to homogenize our TEMPDIR approach

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#5843]
Our current scripts in `hack` use quite a large number of temporary directories for storing things during swap, depositing artifacts, etc. This leads to a heterogeneous approach to [downloading artifacts](https://github.com/openshift/vagrant-openshift/blob/master/lib/vagrant-openshift/action/download_artifacts_origin.rb#L40-L42) for Jenkins, for example. Furthermore, many commands do not clean up after themselves. I think we should refactor our use of temporary directories to look something like the structure below, and ensure that all scripts depositing any files there clean up when they're done, with a flag exposed that stops clean-up if the developer wants to inspect the output.

When we do the switch, I think making all of the Origin scripts deposit to both places would be the first step, then `vagrant-openshift` could be updated to pull from the new spot, then Origin could be updated again to only deposit in the new area. This would ensure no "downtime" for test artifacts.

```
tmp
└── openshift
    ├── build
    ├── generate
    │   ├── completions
    │   ├── conversions
    │   ├── docs
    │   └── swaggerspec
    └── test
        ├── e2e
        ├── extended
        ├── go
        └── integration
```

/cc @bparees @danmcp @smarterclayton

**Comment by mfojtik** [comment]
+1

**Comment by deads2k** [comment]
> clean up when they're done, with a flag exposed that stops clean-up if the developer wants to inspect the output.

You shouldn't clean up when you're done.  You should cleanup on the next attempt to run.  Saving artifacts by default makes debugging a lot easier.

**Comment by stevekuznetsov** [comment]
What would the behavior be when a developer wants to turn off this feature, then?

**Comment by deads2k** [comment]
> What would the behavior be when a developer wants to turn off this feature, then?

And doesn't just want to wait for the next run to clear its directory and re-run?  `rm -rf`

**Comment by stevekuznetsov** [comment]
No, that's not what I meant. In the "clean up after yourself" mode, you can set a flag that says - hey, keep the output. In the "clean up before yourself" mode, if we expose that flag, what is the desired effect? Where do the files currently in that folder that will not be cleaned up be placed?

**Comment by deads2k** [comment]
"cleanup before yourself" is what we currently do.  There's no flag at all.  Artifacts are left in place until the next run, at which point they are deleted.

**Comment by stevekuznetsov** [comment]
That is not the case. `test-cmd` doesn't do cleanup (and my 50 tempdirs under `/tmp/openshift-cmd` can attest to that. The `generate` scripts clean up after themselves.

**Comment by smarterclayton** [comment]
Test-cmd should be more like e2e and extended - clean up at the beginning
of the run, leave it after.

On Nov 11, 2015, at 5:42 AM, Steve Kuznetsov <notifications@github.com>
wrote:

That is not the case. test-cmd doesn't do cleanup (and my 50 tempdirs under
/tmp/openshift-cmd can attest to that. The generate scripts clean up after
themselves.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5843#issuecomment-155787668>.
