### ISSUE TITLE
Use readiness probe initial delay for pod warning checks

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5845]
Currently, the web console warns about a pod if its containers take more than 5 minutes to become ready. We should check if the container has a readiness probe with an initial delay. We shouldn't warn about pods until after that initial delay has passed, possibly adding N minutes rather than hard-coding 5 minutes.

Related to #5793

/cc @jwforres @liggitt

**Comment by spadgett** [comment]
5 minutes might be on the short side as a default as well.

**Comment by jwforres** [comment]
agree 5 is a bit short for certain kinds of apps,  10 minutes maybe?
@bparees thoughts?

**Comment by bparees** [comment]
i like the proposal to base it on the readiness probe.  For apps that don't have a readiness probe, what is the web console using to declare a pod "ready"?

**Comment by jwforres** [comment]
the api always returns ready status for containers, i assume if there are
no probes then that is true as soon as the container is started

**Comment by bparees** [comment]
then it sounds like 5 minutes ought to be more than ample in the case that no readiness probe is defined.

and if there is a readiness probe+initial delay defined, then just waiting the initial delay should be appropriate, right?

**Comment by spadgett** [comment]
The 5 minutes includes time to pull the image if necessary, right?

**Comment by bparees** [comment]
hm.  good point.  so in the case of a readiness probe being defined, the "initial delay" (from a k8s perspective) probably only starts counting after the pod goes to "running".

so yes if you want to account for scheduling time+image pulling, you need some additional buffer.  10 minutes still sounds too high, but 5 minutes might be ok.

**Comment by jwforres** [comment]
discussed with @spadgett and this actually doesn't make sense because the warning only appears if its stuck in the Pending state.  By the time the readiness probe delay would be taken into account the pod is already in the Running but Not Ready state, so the warning will no longer appear.
