### ISSUE TITLE
oc status doesn't handle jobs

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5849]
`oc status` doesn't show me my jobs at all.

We might want to wait for API discovery so that we can properly determine whether or not to look before adding this.

**Comment by soltysh** [comment]
When API discovery is planned to land, next rebase?

**Comment by kargakis** [comment]
Lucky you @soltysh !! :)

**Comment by soltysh** [comment]
:stuck_out_tongue_winking_eye:

**Comment by pweil-** [comment]
@soltysh can this be closed?

**Comment by soltysh** [comment]
@pweil- nope, it's still the case.
