### ISSUE TITLE
Simplify README.md for sample-app

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#5850]
When I follow the instructions from the https://github.com/openshift/origin/tree/master/examples/sample-app I always have the similar issues:

- our binaries reside in `/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64` directory but it's not in `$PATH` and we should always specify the full path (but some commands still in a short form and you can't just copy&paste them)

- by default `$KUBECONFIG` points to `/openshift.local.config/master/admin.kubeconfig` that isn't readable by `vagrant` user. It leads to 1) explicitly specifying `--config=openshift.local.config/master/admin.kubeconfig` to a some comands 2) `oc login` fails and we need to unset the `$KUBECONFIG` environment variable manually

I suggest to solve all theses issues by adding two more commands to the beginning:
```
$ export PATH="$PATH:/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64"
$ export KUBECONFIG="$(pwd)/openshift.local.config/master/admin.kubeconfig"
```

I can create PR if needed.

**Comment by PI-Victor** [comment]
See https://github.com/openshift/origin/pull/5112

**Comment by bparees** [comment]
see also: https://github.com/openshift/origin/pull/4970

we should NOT be suggesting setting $KUBECONFIG, it's a bad pattern.  if you need admin credentials you should always use --config

**Comment by stevekuznetsov** [comment]
I don't think changing a user's `$PATH` is good form.

**Comment by bparees** [comment]
It's telling them to change it. If they care that much they can figure out their alternatives.. If we were doing it in a hidden shell script if be more concerned.

**Comment by stevekuznetsov** [comment]
Ah sorry I thought this was in a setup script. Showing a user how to do it is fine, sure. We'd need to do it relative to the working directory though, I'm not sure where the `/data/` path is from.

**Comment by PI-Victor** [comment]
the host GOPATH is mounted inside the virtual machine's /data/ path. i think the compromise would be to add to vagrant-openshift commands the export path and whatnot and let the user configure his own machine optionally with one command and update the docs here. if that doesn't work either, we can leave it as it is. however and i know i sound like a broken record, the images need to be updated to f22 :8ball:

**Comment by bparees** [comment]
Given that the sample app doc references the contributing doc for initial setup:

```
This example assumes you have successfully built the openshift binary executable (normally located under origin/_output/local/bin/linux/amd64, or the equivalent for your host platform/architecture), you have that and its symlink/copy oc in your PATH and root's, and Docker is installed and working. See https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc.
```

do we still need to do something here?

**Comment by PI-Victor** [comment]
from my perspective, i think it's ok. @php-coder PTAL and close if it's ok with you :)
