### ISSUE TITLE
Cluster reader cannot list all component statuses

### ISSUE THREAD

**Issue by simon3z** [openshift/origin#5865]
It seems that a cluster-reader user cannot list all component statuses:

    User "system:serviceaccount:default:manageiq" cannot list all componentstatuses in the cluster

This is on v1.0.8.

cc @deads2k

**Comment by liggitt** [comment]
Policy is the least of the issues preventing component status from functioning in origin. We should fix policy to include it at the same time we work through the architectural issues to enable it. Will handle as part of  https://github.com/openshift/origin/issues/3667
