### ISSUE TITLE
oc rollback --change-strategy is not working as expected.

### ISSUE THREAD

**Issue by Jooho** [openshift/origin#5867]
I tried to test "rollback" and I encounter it is not working as I expected.

From my understanding, if I give this option " --change-strategy=true", the original parameter of strategy in build should be changed but it does not work :

`# oc rollback jbosswebapp --to-version=2 -o json --change-strategy=true --dry-run

Result :
* Deployment Configure strategy "Rolling"    ==>  "--change-strategy=true"                  -> Rolling
                                                                       ==>  "--change-strategy=false(default)"  ->  Recreate  

* Deployment Configure strategy "Recreate"    ==>  "--change-strategy=true"                 -> Recreate
                                                                          ==>  "--change-strategy=false(default)"  ->  Recreate  

I am not sure this is expected behaviour or not but it looks a bug.

Thanks in advance.
Jooho Lee

**Comment by kargakis** [comment]
```
--change-strategy=false: Include the previous deployment's strategy in the rollback
```

Say, you have a deploymentConfig with version=4, strategy=Recreate and rollback to version=2. By default your rollbacked deployment will use strategy=Rolling (because that's the strategy we are defaulting to if none is specified). If you want to preserve Recreate, you will need to use --change-strategy=true. @ironcladlou can confirm.

**Comment by ironcladlou** [comment]
If `--change-strategy` is NOT specified, then the current strategy on the deploymentConfig is preserved. If `--change-strategy` is specified, the strategy on the deploymentConfig is replaced by the strategy that was in use at the time of the deployment specified by `--to-version`.

**Comment by kargakis** [comment]
This is working as expected
