### ISSUE TITLE
fedora vagrant image needs kernel-devel package

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#5869]
@danmcp the fedora 21 image that is used for the vagrant virtualbox provider needs the kernel-devel package installed by default so that the virtualbox guest additions compile properly. the problem is more obvious on f23.

GuestAdditions versions on your host (4.3.34) and guest (4.3.20) do not match.
The guest's platform is currently not supported, will try generic Linux method...
Copy iso file /usr/share/virtualbox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: /dev/loop2 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 4.3.34 - guest version is 4.3.20
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.34 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 4.3.20 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Building the VirtualBox Guest Additions kernel modules
Building the main Guest Additions module[FAILED]

After installing kernel-devel inside the machine:

GuestAdditions versions on your host (4.3.34) and guest (4.3.20) do not match.
The guest's platform is currently not supported, will try generic Linux method...
Copy iso file /usr/share/virtualbox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: /dev/loop2 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 4.3.34 - guest version is 4.3.20
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.34 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 4.3.34 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Building the VirtualBox Guest Additions kernel modules
Building the main Guest Additions module[  OK  ]
Building the shared folder support module[  OK  ]
Building the OpenGL support module[  OK  ]
Doing non-kernel setup of the Guest Additions[  OK  ]
Starting the VirtualBox Guest Additions [  OK  ]

**Comment by danmcp** [comment]
https://github.com/openshift/vagrant-openshift/blob/master/lib/vagrant-openshift/action/install_origin_base_dependencies.rb#L42
