### ISSUE TITLE
provide a REST API for invoking binary builds from inside existing large multi maven builds?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#5876]
folks in the Java community often have huge multi-maven builds which make many kinds of versioned binary artefact (jars / wars, source jars, javadoc jars etc) which result in possibly multiple docker images. A typical integration project generates many images for example which are usually inside the same git repository. 

Its possible to split the build up into a 'Java only' build making just Java artefacts; then try to generate multiple S2I images that download the jars/wars from the previous step and compose them into docker images. Its just fiddly and error prone splitting it up like that.

The simplest thing to migrate existing builds over to OpenShift would be from inside any maven module in a maven build, to be able to post a tarball of the jars/wars to add to a docker image with a Dockerfile containing the from image along with the required docker image name & version label to some OpenShift REST service. Then OpenShift can do all the docker stuff and push the image to whatever image streams & registries etc. 

Then to migrate the maven build its a simple case of adding a new maven goal or profile. This will greatly help folks migrate their existing maven builds to docker. 

What we've been looking at up to now is to have the maven build generate the tarball and upload it to nexus; so that we can then have N separate binary openshift builders take those tarballs and put them into docker images. It just feels like unnecessary extra plumbing; plus there's the additional cost of the push to nexus then download from nexus which further slows down the OpenShift build; it'd be faster to post it straight into the pod thats gonna make the docker image in one go really.

I guess you could consider this a REST API to invoke the binary builders? Underneath the covers it could be invoking a binary builder; its just we'd also post the tarball at the same time.

**Comment by bparees** [comment]
this is now possible w/ binary builds:
https://docs.openshift.org/latest/dev_guide/builds.html#binary-source

(you'll have to dig a little deeper to get the api for invoking it, but that's what the cli implementation is doing: post a binary to an endpoint that creates a build and streams the binary into it)
