### ISSUE TITLE
Additional image tiles on the create page should display their individual logo icon

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#5883]
We have most, if not all, logos for these in the icon-font set. Currently the generic cube icon is being used.

<img width="854" alt="missing-logos" src="https://cloud.githubusercontent.com/assets/1874151/11127790/fe45e306-8943-11e5-86de-72999e941602.png">

**Comment by spadgett** [comment]
@bparees Opinion on this? We need an `iconClass` annotation to show the icon.

**Comment by bparees** [comment]
i'm happy with that icon.  

but shouldn't the builder images still have a builder image icon?

**Comment by spadgett** [comment]
These are the images without the builder tag. The "real" builder images have icon for the technology because they have `iconClass` set.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/11153716/c03eed8a-8a08-11e5-9f12-c5c728ef6598.png)

**Comment by spadgett** [comment]
Looking at this, I'm not sure we're using the right generic icon, either.

/cc @jwforres

**Comment by jwforres** [comment]
Nope, should be pficon-image  https://www.patternfly.org/styles/icons/

**Comment by jwforres** [comment]
And we need to actually use the new pficon-build-image for the builders

**Comment by jwforres** [comment]
We have icons for all of those databases, are we not setting iconClass on the imagestreams for those

**Comment by sg00dwin** [comment]
@jwforres do we pursue this change or close issue?

**Comment by jwforres** [comment]
I'd like to figure out whats wrong, my guess is those imagestreams are not setting iconClass, @bparees ?

**Comment by bparees** [comment]
Looks like they are not:
https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L272

vs
https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L303

if you guys tell me the icon names i'll be happy to get the imagestreams updated.

do we have an icon for jenkins?  it's also missing the name.

**Comment by jwforres** [comment]
@sg00dwin can you let @bparees know which classes to use for these

On Wed, Feb 17, 2016 at 3:49 PM, Ben Parees <notifications@github.com>
wrote:

> Looks like they are not:
>
> https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L272
>
> vs
>
> https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json#L303
>
> if you guys tell me the icon names i'll be happy to get the imagestreams
> updated.
>
> do we have an icon for jenkins? it's also missing the name.
>

Yep we do.

**Comment by jwforres** [comment]
Nevermind @sg00dwin, i got him the class names

**Comment by bparees** [comment]
![screenshot at 2016-02-17 16 15 12](https://cloud.githubusercontent.com/assets/4974046/13125053/b7192e94-d591-11e5-903d-3657b308bd77.png)

couple weird things here:
1) "version" is shown for some ISTs but not others.
2) the last image box expands across the whole window.

**Comment by spadgett** [comment]
We hide version if it's the same as tag. Not crazy about how it looks when we show it.

**Comment by bparees** [comment]
>  Not crazy about how it looks when we show it.

me either

**Comment by sg00dwin** [comment]
what's the difference between

mongodb:2.6 and
mongodb:latest version 2.6

what about appending version # before :latest

mongodb:2.4
mongodb:2.6(latest)

**Comment by bparees** [comment]
There is no difference.  the IST named "latest" is basically a symlink to the IST named "2.6".

But the idea is that when 2.8 comes along, the admin updates the symlink and anyone using the "latest" IST gets upgraded while people who explicitly chose 2.6 stay on 2.6.

**Comment by jwforres** [comment]
But you are doing the annotations separately right? so latest is explicitly
setting a version tag? i feel like its a bit of a lie to show version when
the intention is that the version will change

**Comment by bparees** [comment]
@jwforres yes i'm explicitly setting it to reflect what the tag currently points to.  The idea being the admin ought to update that tag when they change what it symlinks to.

if i don't provide a version tag, then you'd have no idea what "latest" was when you were picking it, and that doesn't seem right.

**Comment by spadgett** [comment]
I was planning changing the version to small, muted text to the right of the tag.

**Comment by bparees** [comment]
(@jwforres but i agree w/ your point that it's not necessarily obvious to a user that "latest" might point to something else tomorrow and if they redeploy they'll be updated to that new version.  I don't have a good answer though.  not showing the version at all might be the best option but it's hard to imagine people picking that)

**Comment by spadgett** [comment]
Opinions on this change?

<img width="491" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13128106/7ceaa918-d5a1-11e5-84d9-9882537ff284.png">

**Comment by jwforres** [comment]
how will that do with a really long image name, i think some of the jboss
ones are long

**Comment by spadgett** [comment]
I opened #7415 for the tile spanning two columns.

**Comment by spadgett** [comment]
And #7421 for the weird-looking version.

**Comment by bparees** [comment]
@spadgett fyi this issue is going to get closed when i merge the updated imagestreams to fix the icons, so maybe move the discussion about how to display the Version to a different issue?

**Comment by spadgett** [comment]
@bparees yeah already done #7421
