### ISSUE TITLE
push-release.sh fails in devenv ami

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5889]
Seeing failures pushing release images in devenv ami builds like https://ci.openshift.redhat.com/jenkins/job/devenv_ami/2693/console

No output is given from the push release script

```
echo "Pushing release images"
set -e
pushd /data/src/github.com/openshift/origin
  OS_PUSH_BASE_IMAGES="" OS_PUSH_BASE_REGISTRY="docker.io/" hack/push-release.sh
popd
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!


echo "Pushing release images"
set -e
pushd /data/src/github.com/openshift/origin
  OS_PUSH_BASE_IMAGES="" OS_PUSH_BASE_REGISTRY="docker.io/" hack/push-release.sh
popd
```

**Comment by liggitt** [comment]
@danmcp

**Comment by bparees** [comment]
@liggitt what do you say to just adding a -x to push-release.sh for now so we can get some feedback on this?

**Comment by liggitt** [comment]
bumping priority, this is failing the devenv ami

**Comment by liggitt** [comment]
has failed every build since #2​68​2 Nov 12, 2015 2:31 AM

**Comment by bparees** [comment]
docker repos had not been created, have been now.  should work now.

**Comment by liggitt** [comment]
fixed, https://ci.openshift.redhat.com/jenkins/job/devenv_ami/2703/ passed
