### ISSUE TITLE
Incorrect root paths returned with new API groups (extensions)

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#5890]
Extensions path at `/apis/extensions/v1beta1` isn't present in returned root paths. This works upstream & is useful in determining what is enabled/disabled on the API server.

```
$ curl -k 'https://localhost:8443/'
{
  "paths": [
    "/api",
    "/api/v1",
    "/controllers",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/ready",
    "/oapi",
    "/oapi/v1",
    "/swaggerapi/"
  ]
}
```

**Comment by liggitt** [comment]
should be fixed, but I think doing a GET on `/api` and `/apis` is the official way to discover enabled groups and versions

**Comment by jimmidyson** [comment]
Ah OK thanks for that - that makes much more sense.

**Comment by iocanel** [comment]
shouldn't this get aligned with upstream anyway?

**Comment by liggitt** [comment]
> shouldn't this get aligned with upstream anyway?

yes, not closing it, just noting the more correct way to discover that info

**Comment by jimmidyson** [comment]
Think this is working properly now.
