### ISSUE TITLE
Project cache takes very long to update at high scale

### ISSUE THREAD

**Issue by tiwillia** [openshift/origin#5897]
With increasing numbers of resources in etcd on an openshift system, an issue is seen where after a user creates a project, the project cache takes too long to update. This originally resulted in an issue with the `oc new-project` command where the access validation check would fail due to the project cache not being up-to-date (issue #4870). This was resolved by skipping the access validation check after the project was created.

Eventually, at very high numbers of users and other resources in etcd, the project cache takes so long to update it will be very noticeable to a user. The scalability testing document I have put together shows specific numbers from tests where this project cache issues gets out of hand. Around 47,000 users & projects, and 140,000 deploymentConfigs & replicationControllers, the project cache will often take longer than 20 seconds to update.

If a user was to create a project and immediately afterwards process a template at this scale, they would see the below error, due to it appearing as though they do not have proper access to the project they just created:

```
 error processing the template "example-template": User "example-user" cannot create processedtemplates in project "example-project"
```

**Comment by deads2k** [comment]
That error suggests that the watch from etcd isn't populating the cache of roles and rolebindings in time for the next create.

It's really painful to wait for create cases.  We could add an additional check against the live etcd data before sending a deny.  With proper rate limiting (something like a max of 10 re-lookups that result in a deny per minute), that wouldn't be too bad performance-wise and it would keep the creates working.  If we did that, the project cache would still be behind, because RARs and SARs would still be behind.

**Comment by derekwaynecarr** [comment]
I guess it's not clear to me that we should look to fundamentally change the project cache, or if we should just look to optimize the other areas that may be starving resource (deployment configs / replication controllers / etc.)  Fundamentally, any solution is going to be blocked waiting for a WATCH response from etcd.

Some thoughts that come to mind:

1. we could store openshift resources in a separate etcd instance than kubernetes resources
2. we could store namespaces in a separate etcd instance than the rest

Questions:

1) How many total keys were in the etcd environment when this was encountered?  Can you break it down by resource type?  For example, were there 47k users and 47k projects?  Each project had ~3 deployment configs and ~3 replication controllers?  How many nodes were in the cluster to support this workload?  How many pods?
2) How active was the rate of new resource creation?
3) What was the etcd snapshot interval set to?  Was the rate of creation large enough in effect exceed the snapshot interval and basically force a thundering heard of re LIST/WATCH from all controllers?
4) I have to imagine scheduling got slow in general if project cache updates were taking 20s.  How useful was the rest of the system?  How long would it take a pod to schedule?
5) Was there a large number of events being written to the system that could have been clogging traffic?

Thanks
