### ISSUE TITLE
Consider upgrading Modernizr JS library

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#5909]
Hi,

On OpenShift Online, the following warning can be seen in the console (seems to appear for most pages in the webapp):

> 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

This comes from a modernizr.min.js file which has the following comment at the top:

> // Modernizr v1.7  www.modernizr.com

As the latest version of the [Modernizr JS library](https://modernizr.com/news) is 3.2.0, it seems likely that this warning has been fixed in subsequent versions. Would you consider updating the version of Modernizr in use?

I'm using Chrome 46.

Note: this may actually be an issue with origin-server instead; I don't know if you can move issues, but I'm happy to cancel this and open a new one in that repository if that works better.

Jonathan

**Comment by danmcp** [comment]
@jawnsy It's probably better to open this here instead:

https://github.com/openshift/origin-server/

**Comment by jawnsy** [comment]
Fair enough, I've opened https://github.com/openshift/origin-server/issues/6313
