### ISSUE TITLE
Builder is not updating submodules

### ISSUE THREAD

**Issue by paralin** [openshift/origin#5910]
To reproduce:

 - Create a git repository.
 - Add a submodule to it.
 - Deploy the repository using the Docker strategy (Dockerfile)
 - Update something in the submodule, git commit, git push
 - Add the update in the parent repository (git add -A git commit)
 - Push everything.
 - Trigger a build

The submodule will not be updated, while the parent repo is.

I think the solution is just to run `git submodule update --init` in the repository.

**Comment by paralin** [comment]
In particular this command should be run after another branch is checked out.

Currently I think it will clone master, the submodule will be at the version in master, then it checks out "branch" and doesn't update the submodule.

**Comment by mfojtik** [comment]
Is this S2I builder? S2I should fetch all submodules, it uses recursive
clone.

**Comment by paralin** [comment]
@mfojtik Yeah, it uses recursive clone, then it checks out another branch, and builds.

There needs to be a step in there:

 - Clone recursively
 - Check out branch
 - Update submodules
 - Build

**Comment by paralin** [comment]
At https://github.com/openshift/source-to-image/blob/master/pkg/scm/git/git.go#L417

There needs to be a new function called update, which executes

`git submodule update`

and then a call at pkg/build/builder/source.go that does that command after the checkout.

**Comment by liggitt** [comment]
Would it be better to do `-b <branch> --single-branch --recursive`? Not sure if that would both save clone cost for large repos and avoid updating submodules twice (once for the master clone and once after checking out a specific branch)

**Comment by paralin** [comment]
Updating a submodule is just checking out a specific commit. It doesn't take any extra time.

**Comment by liggitt** [comment]
Not necessarily... if the submodule definition has changed between master and the newly checked-out branch, a full clone of the submodule repo could be needed.

Consider the following:
1. Your `master` branch has submodules A and B defined
2. Your `buildme` branch has submodules B and C defined

Cloning `master` with `--recursive` is a wasted clone of submodule A, since we would immediately checkout out `buildme` and discard it. Additionally, `git submodule update` wouldn't init C... we'd need to `git submodule update --init` to pick that up...

I think we should do the following:
```
git clone <targetrepo>
git checkout <targetspec> (if targetspec is specified)
git submodule update --init --recursive
```

**Comment by paralin** [comment]
@liggitt That's probably a better option, yes. I can contribute the PRs towards that if you'd like.

**Comment by liggitt** [comment]
sure... might want to relocate this issue to the source-to-image repo. relevant code looks to be in https://github.com/openshift/source-to-image/blob/master/pkg/scm/git/git.go

**Comment by mfojtik** [comment]
@paralin lemme know if you are interested in fixing this in S2I, I can review and merge the fix. Thanks for reporting this!

**Comment by bparees** [comment]
fixed by https://github.com/openshift/origin/pull/5922
