### ISSUE TITLE
wildcard dns with dnsmasq 

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#5911]
I have OpenShift origin installed on instances of EC2 with OS: Centos7. I have one master and 2 nodes. I have a registry, router and routes to my applications. The pod and container of my router is running on my OpenShift-master. Till now I was accessing my applications by defining them in my /etc/hosts on my real computer (not on a server).
```
The IP's I will use in my examples:
IP of Master-server:  52.18.xx.xx
IP of Node-server(s): 52.19.xx.xx
IP of DNS-server: 52.17.xx.xx
```

For example (what I was doing till now):
```
exit the server
vi /etc/hosts (on real computer)
  52.18.xx.xx myapp.apps.example.com
```
That was working. But now I want to use a real DNS server. I need to use a new EC2-instance (52.17.xx.xx). I did the following installation + configuration:
```
yum install dnsmasq
vi /etc/dnsmasq.conf 
```
The only line I added was:
```
address=/apps.example.com/52.18.xx.xx (IP of OpenShift-server)
```
Than I configured ```/etc/resolv.conf``` and ```/etc/hosts```.
```
vi /etc/resolv.conf
; generated by /usr/sbin/dhclient-script
search apps.example.com
nameserver 8.8.8.8
```
and
```
vi /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
52.18.xx.xx ec2-52-18-x-x.eu-west-1.compute.amazonaws.com (hostname)
52.19.xx.xx ec2-52-19-x-x.eu-west-1.compute.amazonaws.com
52.19.xx.xx ec2-52-19-x-x.eu-west-1.compute.amazonaws.com
```
That was all the configuration I did for my DNS server. The only thing I thought I had to do was to change the ```/etc/resolv.conf``` on my OpenShift-master and nodes. That one looks like this:
```
cat /etc/resolv.conf 
; generated by /usr/sbin/dhclient-script
#search eu-west-1.compute.internal
#nameserver 10.0.0.x

search example.com
nameserver 52.17.xx.xx (IP of DNS-server)
```
After that change I have this issue:
```
oc login
Unable to connect to the server: dial tcp: lookup ip-10-0-0-xxx.eu-west-1.compute.internal: no such host
```

Some info:
```curl myapp.apps.example.com```

For my real PC and DNS Server:
```curl: (6) Could not resolve host: myapp.apps.example.com; Name or service not known```
For my OpenShift Server
```curl: (7) Failed connect to myapp.apps.example.com:80; Connection refused```

**Comment by wjiangjay** [comment]
```
oc login
Unable to connect to the server: dial tcp: lookup ip-10-0-0-xxx.eu-west-1.compute.internal: no such host
```

The error is related with ec2, since you change the dns server to the one which can not resolve *.eu-west-1.compute.internal.

And if you want use the external dns to do this, you need:
1. No changes for openshift 
2. Setup external dns server, and add the data to it for "apps.example.com"
3. Change the dns server for "curl" machine, not the ec2 instance
4. `curl myapp.apps.example.com`

**Comment by lorenzvth7** [comment]
@wjiangjay Thanks, okay I've deleted my configurations from OpenShift. The DNS-server has the same configuration as in my first post (is the ```address=/apps.example.com/52.18.xx.xx```, the IP of the openshift-server? 
I went into the bash of my real computer and edited its /etc/resolve.conf to the following:
```
#
# Mac OS X Notice
search example.com
nameserver 52.17.xx.xx
```

**Comment by wjiangjay** [comment]
@lorenzvth7 yes, and if you have some dns issue, you can check with dig:
`dig @52.17.xx.xx myapp.apps.example.com` to make sure dns server work well.

**Comment by lorenzvth7** [comment]
@wjiangjay It's even not possible to access the server:
```
; <<>> DiG 9.8.3-P1 <<>> @52.17.xx.xx dev.apps.example.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by lorenzvth7** [comment]
When I change this: 
```
vi /etc/dnsmasq.conf
address=/apps.example.com/52.17.xx.xx (IP of DNS-Server)
```
Then I get the following when I'm curling from my real PC (I changed the nameserver)
```
; <<>> DiG 9.8.3-P1 <<>> @52.17.xx.xx dev.apps.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57153
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dev.apps.example.com.		IN	A

;; ANSWER SECTION:
dev.apps.example.com.	0	IN	A	52.17.xx.xx

;; Query time: 26 msec
;; SERVER: 52.17.xx.xx#53(52.17.xx.xx)
;; WHEN: Mon Nov 16 10:30:17 2015
;; MSG SIZE  rcvd: 54

MacBook-Pro:~ lorenzvanthillo$ curl dev.apps.example.com
curl: (6) Could not resolve host: dev.apps.example.com
```

**Comment by wjiangjay** [comment]
@lorenzvth7 Obviously your macbook not use 52.17.xx.xx as the dns server

**Comment by lorenzvth7** [comment]
@wjiangjay 
Weird: my ```/etc/resolv.conf``` only contains: ```nameserver 52.17.xx.xx```
I changed ```vi /etc/dnsmasq.conf``` on my DNS-server back to ```address=/apps.example.com/52.18.xx.xx (IP of OpenShift-server)```. Because It seems clear I have to refer to your OpenShift server (that one serves the apps). But 'dig' is not possible after that change. Does it have to contain apps.example.com or example.com?

**Comment by wjiangjay** [comment]
@lorenzvth7 http://www.macinstruct.com/node/434

**Comment by lorenzvth7** [comment]
@wjiangjay I can apparently not change the dns nameserver on my real machine because I'm on a network which does not allow that. So now I want to curl from my dnsserver itself. Is that possible?
So a little overview:
OpenShift-server --> no configuration

DNS-server 

 ```/etc/dnsmasq.conf``` contains ```address=/apps.example.com/52.17.xx.xx``` (IP of OpenShift Master)

``` 
vi /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
52.18.xx.xx ec2-52-18-x-x.eu-west-1.compute.amazonaws.com (hostname)
52.19.xx.xx ec2-52-19-x-x.eu-west-1.compute.amazonaws.com
52.19.xx.xx ec2-52-19-x-x.eu-west-1.compute.amazonaws.com
```

```/etc/resolv.conf``` contains  
```
search apps.evolane.com 
nameserver 127.0.0.1
```
I'm not sure of the resolv.conf of my dns-server.

**Comment by wjiangjay** [comment]
@lorenzvth7 Or you can do this on the machine which you can change the dns server
