### ISSUE TITLE
Don't request logs in UI until pod, build, or deployment has started

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5920]
We try to fetch logs when a pod, build, or deployment is still in the New or Pending phases. This will always fail. We should wait until it has started running.

/cc @jwforres @benjaminapetersen

**Comment by benjaminapetersen** [comment]
Got it, a watch & a `_.once(function() { })` will prob take care of this.

**Comment by jwforres** [comment]
clean up the watch as part of what gets run by the _.once,  no need to keep firing something that isn't going to do anything,  also clean up the watch in the on destroy, in case it never gets fired.

**Comment by jwforres** [comment]
which actually in that case you wouldn't even need to call _.once

main point is, I don't want to have useless watches hanging around

**Comment by jwforres** [comment]
fixed

**Comment by spadgett** [comment]
Fixed by #6878
