### ISSUE TITLE
How to develop locally from version 1.1?

### ISSUE THREAD

**Issue by eddytruyen** [openshift/origin#5925]
I am new to using github, so appologies if I sent this question to the wrong website or forum of openshift

I think I have problems with getting the source of the lastest release of openshift 3, in particular I suspect I get the source of v1.0 and not version 1.1

I followed the instructions on https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-locally-on-your-host.

This page contained the following instruction for cloning the source:
git clone git://github.com/<forkid>/origin  # Replace <forkid> with the your github id

I suspect however this command clones an older version of openshift 3. II tried several commands from the Tryout example: https://docs.openshift.org/latest/getting_started/administrators.html#try-it-out, but these did not work:

* oc login -u system:admin responded by asking the password for user "system:admin"

* I then tried to login with user "system" and password "admin". This worked but I could not get access to project default

* the build of the node-js image failed because the push to the private docker registry failed because the IP of the private docker registry was not accessible. I found out this error was actually a closed issue: https://github.com/openshift/origin/issues/4676. I checked if my registry was running and it was

° In the openshift master terminal output, there was also a problem that a particular ethtool could not be found, but this is also a closed issue: https://github.com/openshift/origin/issues/4843

The last 2 problems reinforced my belief that I am actually still using version 1.0 and not 1.1.
So how can I clone the latest stable version of the source?

**Comment by jawnsy** [comment]
Hey,

Not an OpenShift maintainer or contributor, so take this suggestion with a grain of salt... I'll tell you what worked for me:

I cloned directly from upstream (e.g. `git clone https://github.com/openshift/origin.git`) and then built with that (actually I just did this to use `vagrant up` to provision a VM, then downloaded the [1.1 release via the Releases tab](https://github.com/openshift/origin/releases/tag/v1.1), which is precompiled).

The provided instructions are for people who want to contribute code back to OpenShift Origin, in which case you have to learn the Git workflow (fork repository, create topic branch, make changes, push branch to GitHub, open pull request to ask the Origin maintainers to merge your work back).

Jonathan

**Comment by eddytruyen** [comment]
Below you find some additional info on my problem

ping to IP of docker registry failed, but ping to endpoint worked:

[fedora@openshift-master amd64]$ oc login
Authentication required for https://localhost:8443 (openshift)
Username: test-admin
Password:
Login successful.

You don't have any projects. You can try to create a new project, by running

    $ oc new-project <projectname>

[fedora@openshift-master amd64]$ oc new-project test2
Now using project "test2" on server "https://localhost:8443".
[fedora@openshift-master amd64]$ oc describe service docker-registry --config       =openshift.local.config/master/admin.kubeconfig
Name:                   docker-registry
Namespace:              default
Labels:                 docker-registry=default
Selector:               docker-registry=default
Type:                   ClusterIP
IP:                     172.30.150.191
Port:                   5000-tcp        5000/TCP
Endpoints:              172.18.0.54:5000
Session Affinity:       ClientIP
No events.

[fedora@openshift-master amd64]$ ping 172.30.150.191
PING 172.30.150.191 (172.30.150.191) 56(84) bytes of data.
^C
--- 172.30.150.191 ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 6999ms

[fedora@openshift-master amd64]$ ping 172.18.0.54
PING 172.18.0.54 (172.18.0.54) 56(84) bytes of data.
64 bytes from 172.18.0.54: icmp_seq=1 ttl=64 time=0.264 ms
64 bytes from 172.18.0.54: icmp_seq=2 ttl=64 time=0.160 ms
64 bytes from 172.18.0.54: icmp_seq=3 ttl=64 time=0.080 ms
64 bytes from 172.18.0.54: icmp_seq=4 ttl=64 time=0.087 ms
64 bytes from 172.18.0.54: icmp_seq=5 ttl=64 time=0.088 ms
64 bytes from 172.18.0.54: icmp_seq=6 ttl=64 time=0.095 ms
64 bytes from 172.18.0.54: icmp_seq=7 ttl=64 time=0.089 ms
64 bytes from 172.18.0.54: icmp_seq=8 ttl=64 time=0.084 ms
^C
--- 172.18.0.54 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 6999ms
rtt min/avg/max/mdev = 0.080/0.118/0.264/0.060 ms
[fedora@openshift-master amd64]$

**Comment by PI-Victor** [comment]
@eddytruyen Heya, i see you already forked the project, what you want to do at this point is add the upstream branch to it so that you can fetch the latest changes. 
In your origin fork git repo, do this 
`git remote add upstream https://github.com/openshift/origin`
your fork is behind the upstream, personal forks don't track upstream changes so you have to fetch them in your git repo and push them to your fork manually.
your fork is at [v1.0.6](https://github.com/eddytruyen/origin/releases)
the upstream is at [v1.1](https://github.com/openshift/origin/tags)
you do that so:
in your master branch
`git fetch upstream`
`git fetch upstream --tags`
`git rebase upstream/master`
`git push origin` <-- push the latest changes after rebase to your fork
now let's create a new branch for whatever changes you want to make
`git branch eddytruyen/whatever_your_changing`
Now onto compiling:
in your origin repo do 
`make clean build` <-- always remember to compile on your host after any change, and not your vagrant machine, because vagrant is slower.
now we can start working with vagarant:
i hope you have virtualbox installed.
`vagrant up --provider=virtualbox`
if vagrant complains that it can't compile the virtualbox guest additions (usually happens in fedora 23) then after it fails, you can still do 
`vagrant ssh`
`sudo yum upgrade kernel-* -y` - update to the latest kernel, the f21 image has a few problems.
after it finishes updating, exit the vagrant machine. 
Install the vagrant-openshift plugin to help you provision the machine
`vagrant plugin install vagrant-openshift`
`Installing the 'vagrant-openshift' plugin. This can take a few minutes...`
`Installed the plugin 'vagrant-openshift (3.0.1)'!`
`vagrant install vagrant-vbguest` <- this will make sure you have the latest virtualbox guest additions installed in your vm
Now you can use the plugin to setup your vagrant machine:
`vagrant build-origin-base`
It will update the rest of the packages and install some additional ones as well, and re-setup a few things. It might take a while, but after this you'll have less problems.
after it's done: `vagrant reload`
Now the virtualbox guest addition module should compile and also mount your `$GOPATH/src/github.com/openshift/origin` repo inside your vagrant machine in `/data/src/github.com/openshift/origin`.
To make this run better, make sure you have your openshift binaries added to your $PATH in the vagrant machine. You can add this to /home/vagrant/.bashrc : `export PATH=$PATH:/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/`
After you do that, you can check the version of what you're running like this:
```
[vagrant@localhost ~]$ oc version  
oc v1.1-55-g2f302fd-dirty  
kubernetes v1.1.0-origin-1107-g4c8e6f4  
[vagrant@localhost ~]$ openshift version  
openshift v1.1-55-g2f302fd-dirty  
kubernetes v1.1.0-origin-1107-g4c8e6f4  
etcd 2.1.2
```
follow the tutorial in the CONTRIBUTING.md from there onward and tell me if you experience the same problem.

btw: do a chmod a+rw openshift.local.config/master/admin.kubeconfig
if you decide to do this locally without vagrant, then you need to install ethtool yourself, it's used by kubernetes.
let me know if you still have problems after the above commands.

**Comment by eddytruyen** [comment]
Thanks for the helpful info! I will try it asap. I can't use vagrant because I have installed openshift on an openstack instance. 
On this openstack instance paravirtualization is not possible. So virtualbox will not work correctly.

**Comment by eddytruyen** [comment]
After fetching 1.1 I still run into the same problem that I can't push an image to the private docker registry.

Here is some info: 

1) I  have installed openshift on fedora21 
                                  
2) I have added 2 options in etc/sysconfig/docker:
# /etc/sysconfig/docker
other_args="'--selinux-enabled --insecure-registry 172.30.0.0/16"

3) Results of oc describe registry:

Name:                   docker-registry
Namespace:              default
Labels:                 docker-registry=default
Selector:               docker-registry=default
Type:                   ClusterIP
IP:                     172.30.248.152
Port:                   5000-tcp        5000/TCP
Endpoints:              172.18.0.7:5000
Session Affinity:       ClientIP
No events.

4) Build log while pushing an image:
E1118 19:36:20.029539       1 util.go:85] npm info ok
I1118 19:37:00.135643       1 sti.go:213] Using provided push secret for pushing 172.30.248.152:5000/test2/nodejs-ex:latest image
I1118 19:37:00.135818       1 sti.go:217] Pushing 172.30.248.152:5000/test2/nodejs-ex:latest image ...
E1118 19:37:00.149791       1 dockerutil.go:74] push for image 172.30.248.152:5000/test2/nodejs-ex:latest failed, will retry in 5s seconds ...
E1118 19:37:05.156333       1 dockerutil.go:74] push for image 172.30.248.152:5000/test2/nodejs-ex:latest failed, will retry in 5s seconds ...
E1118 19:37:10.164817       1 dockerutil.go:74] push for image 172.30.248.152:5000/test2/nodejs-ex:latest failed, will retry in 5s seconds ...
E1118 19:37:15.208259       1 dockerutil.go:74] push for image 172.30.248.152:5000/test2/nodejs-ex:latest failed, will retry in 5s seconds ...
E1118 19:37:20.419475       1 dockerutil.go:74] push for image 172.30.248.152:5000/test2/nodejs-ex:latest failed, will retry in 5s seconds ...
E1118 19:37:25.429280       1 dockerutil.go:74] push for image 172.30.248.152:5000/test2/nodejs-ex:latest failed, will retry in 5s seconds ...
E1118 19:37:30.435466       1 dockerutil.go:74] push for image 172.30.248.152:5000/test2/nodejs-ex:latest failed, will retry in 5s seconds ...
I1118 19:37:35.435834       1 sti.go:222] Registry server Address:
I1118 19:37:35.435914       1 sti.go:223] Registry server User Name: serviceaccount
I1118 19:37:35.435934       1 sti.go:224] Registry server Email: serviceaccount@example.org
I1118 19:37:35.435951       1 sti.go:229] Registry server Password: <<non-empty>>
F1118 19:37:35.436027       1 builder.go:59] Build error: Failed to push image. Response from registry is: unable to ping registry endpoint https://172.30.248.152:5000/v0/
v2 ping attempt failed with error: Get https://172.30.248.152:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://172.30.248.152:5000/v1/_ping: tls: oversized record received with length 20527

**Comment by PI-Victor** [comment]
just a thought, did you try disabling the firewall?

**Comment by eddytruyen** [comment]
I think I did disable the firewall. I just did it again.
I also put SELinx into permissive mode and rebooted. 
Unfortunately, the problem remains.

**Comment by PI-Victor** [comment]
@eddytruyen what version of docker are you using? it seems you're not the only one that is reporting this issue. for what i understand this happens in docker 1.9 but is okay in docker 1.8.2.

**Comment by eddytruyen** [comment]
@PI-Victor I launched a clean and up-to-date Fedora 21 instance on openstack, I installed docker 1.8.2 and other prerequisites. I coudn't install and execute docker-storage-setup (as specified in Prerequsiites).

I download the binary v1;1 into home dir and deployed private registry using the following commands:

sudo chmod a+rw openshift.local.config/master/openshift-registry.kubeconfig
sudo chmod a+rw openshift.local.config/master/admin.kubeconfig
./oadm registry --create --credentials=openshift.local.config/master/openshift-registry.kubeconfig --config=openshift.local.config/master/admin.kubeconfig

Unfortunately, the ping to the IP address of the docker repository still failed. However, as before, the ping to the service endpoint IP of the docker repository worked.

I am considering switching to vagrant on local windows laptop for development and using the ansible installer for testing distributed deployment on openstack cloud.

Is there any other installation method available for on openstack. For example a HEAT template?

Best regards,

Eddy

**Comment by PI-Victor** [comment]
seems that we do have heat templates, give this a try: https://github.com/redhat-openstack/openshift-on-openstack
@rhcarvalho @mfojtik any of guys have a clue why the openshift registry upload would fail with that error above? i'm out of ideas. i was thinking bad user permissions or something, but it seems it's not that. 
selinux, insecure-registry and the firewall have been properly configure, so what else could it be?

**Comment by eddytruyen** [comment]
I asked some linux expert for input and he said that the linux kernel routing table did not include the 172.30.x.x. address but did include the 172.18.x.x. address. So pushing the image that IP address should resolve the issue?

Below you find the commands the linux expert executed

[fedora@openshiftmaster2 ~]$ ./oc describe service docker-registry --config=openshift.local.config/master/admin.kubeconfig
Name:                   docker-registry
Namespace:              default
Labels:                 docker-registry=default
Selector:               docker-registry=default
Type:                   ClusterIP
IP:                     172.30.121.208
Port:                   5000-tcp        5000/TCP
Endpoints:              172.18.0.5:5000
Session Affinity:       ClientIP
No events.

[root@openshiftmaster2 fedora]# ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.42.1  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:49ff:fe14:6c0d  prefixlen 64  scopeid 0x20<link>
        ether 02:42:49:14:6c:0d  txqueuelen 0  (Ethernet)
        RX packets 10311  bytes 995022 (971.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 15105  bytes 15633342 (14.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@openshiftmaster2 fedora]# iptables -L -v
Chain INPUT (policy ACCEPT 217K packets, 76M bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 
 7982 9614K DOCKER     all  --  any    docker0  anywhere             anywhere   
 7982 9614K ACCEPT     all  --  any    docker0  anywhere             anywhere             ctstate RELATED,ESTABLISHED
 4827  373K ACCEPT     all  --  docker0 !docker0  anywhere             anywhere 
    0     0 ACCEPT     all  --  docker0 docker0  anywhere             anywhere  

Chain OUTPUT (policy ACCEPT 222K packets, 81M bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination 
[root@openshiftmaster2 fedora]#

[root@openshiftmaster2 fedora]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.13.1     0.0.0.0         UG    0      0        0 eth0
172.17.13.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0

**Comment by PI-Victor** [comment]
no, i have exactly the same config as you. 172.30.x.x  isn't in my routing table either

**Comment by mfojtik** [comment]
v2 ping attempt failed with error: Get https://172.30.248.152:5000/v2/: tls: oversized record received with length 20527

this is interesting. @ncdc any ideas?

**Comment by ncdc** [comment]
That means it's either not listed as an insecure registry, or it's not being respected as insecure. Oversized tls record length errors like this mean it's trying to talk https to an http endpoint.

**Comment by eddytruyen** [comment]
Sorry for the delay.
It seems indeed that I was not able to set the insecure-registry option appropriately via systemd service configuration in fedora21.
I could push the image to the registry when manually starting the docker daemon with the insecure-registry option from the prompt

Thanks for the help!

**Comment by rhcarvalho** [comment]
Hi @eddytruyen! Hope you're now able to run your development environment alright. If that's really the case, could you please close this issue?

You can open new issues or reach us at IRC or `openshift-dev` mailing list any time. Thanks!
