### ISSUE TITLE
Improve web console handling of deployment scaling

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#5926]
With #5875, the deployment scaling subresource API should be used exclusively for scaling deployments. All scaling operations should flow through the scaling API and so target deploymentConfigs (DC) rather than replicationControllers (RC) owned by the DCs.

For any views which allow direct scaling of RCs, I think we'll want to disable direct scaling of those RCs if they are owned by a DC.

@openshift/ui-review

**Comment by liggitt** [comment]
>  disable direct scaling of those RCs if they are owned by a DC.

or switch to scaling the parent DC...
* how responsive is that? the number displayed is from the RC replicas setting, but scaling will manipulate the DC scale subresource, which (we hope) affects the RC replicas setting fast enough to not feel laggy to the user?
* what should the UI do when a deployment is in progress?
* is it possible to easily detect a deployment is in progress?

@spadgett @jwforres should probably switch to using the `/scale` subresource of either RC or DC, so the request content you build is the same no matter which resource you are operating on. Requires the UI data layer to be able to handle API groups :-/

**Comment by ironcladlou** [comment]
>or switch to scaling the parent DC...

That makes sense for the active deployment/RC, but not for any other inactive/older RC. Scaling up the latter will be weird and ineffectual (although you can technically still scale them like any other RC, the deployment controller will reconcile them later, likely undoing whatever it is you did.)

>how responsive is that? the number displayed is from the RC replicas setting, but scaling will manipulate the DC scale subresource, which (we hope) affects the RC replicas setting fast enough to not feel laggy to the user?

Should be in the ballpark of scaling the RC directly. Updating the replicas on the DC causes the deployment controllers to reconcile the RCs, so it should cascade quickly.

>what should the UI do when a deployment is in progress?

No special behavior necessary. If you scale the DC while a deployment is in progress, then after the deployment is completed, the resulting RCs will be reconciled with whatever the current DC replica count is. If there's divergence (e.g. the deployment process is moving the RC to 5 replicas and the user scales the DC down to 4 mid deployment), then the RC will eventually be scaled back down to 4 by the deployment controller during reconciliation.

>is it possible to easily detect a deployment is in progress?

You can look at the `openshift.io/deployment.phase` annotation on RCs owned by a deployment.
