### ISSUE TITLE
Too much information presented about image streams

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#5927]
Currently doing `oc describe` on an image stream will give us 3 pull specs, pointing to somehow different docker images:

```
$ oc describe is/python -n openshift
Name:           python
Created:        33 minutes ago
Labels:         <none>
Annotations:        openshift.io/image.dockerRepositoryCheck=2015-11-17T14:36:21Z
Docker Pull Spec:   172.30.248.198:5000/openshift/python

Tag Spec                    Created     PullSpec                                Image
2.7 centos/python-27-centos7:latest     33 minutes ago  docker.io/centos/python-27-centos7@sha256:...   
                                        33 minutes ago  centos/python-27-centos7:latest                     
3.3 openshift/python-33-centos7:latest  33 minutes ago  docker.io/openshift/python-33-centos7@sha256:...    
                                        33 minutes ago  openshift/python-33-centos7:latest                  
3.4 centos/python-34-centos7:latest     33 minutes ago  docker.io/centos/python-34-centos7@sha256:...   
                                        33 minutes ago  centos/python-34-centos7:latest                     
latest  3.3                             33 minutes ago  docker.io/openshift/python-33-centos7@sha256:...    
                                        33 minutes ago  openshift/python-33-centos7:latest                  
```

`Docker Pull Spec` comes from internal docker registry, `Spec` comes from tag's spec, `PullSpec` comes from tag's status. The outcome from today's CLI meeting is we should:
1. Change `Docker Pull Spec` into something like `Following` and present there `spec.dockerImageRepository` instead of `status.dockerImageRepository`.
2. Show only relevant information on tags, what could that be? Annotation, description, else? This will inevitably require extending our API to accommodate that information.

Additionally our `oc get` will return internal docker repo, which looking at what was proposed for `oc describe` should be removed as well, showing just the tags list.

```
$ oc get is/python -n openshift
NAME      DOCKER REPO                            TAGS                      UPDATED
python    172.30.248.198:5000/openshift/python   2.7,3.4,3.3 + 1 more...   41 minutes ago
```

The above changes will apply to web UI as well.

@jwforres @bparees @smarterclayton @ncdc @miminar

**Comment by smarterclayton** [comment]
Suggest "Imported From" instead of "Following" for now (following is a bit
more active).  I don't think we need to show the historical tags for each
(as we discussed on the call), just the most recent, and maybe another
column in the future (Previously Tagged) that shows only the time of the
older tag.

**Comment by bparees** [comment]
isn't `Docker Pull Spec:   172.30.248.198:5000/openshift/python` a push spec, not a pull spec and not an imported from?

**Comment by bparees** [comment]
nm, i see you are also going to change the information being presented.

So are we not going to present a push spec at all?

**Comment by miminar** [comment]
@bparees do pull spec and push spec differ in any way?

**Comment by bparees** [comment]
i think it's moot but i disagree, we routinely refer to them as push and pull specs, they specify a docker image to push/pull.  push url or push location sounds more generic, like it might just refer to the registry you're pushing to.

**Comment by soltysh** [comment]
@smarterclayton reverted my fix and suggested more discussion, let's continue it in here. Can you elaborate more about your decision, it looks like it's different than the one you've presented several months ago in this issue?

**Comment by smarterclayton** [comment]
Not sure where I said not to show the repository pull location?

**Comment by smarterclayton** [comment]
So we need to make our registry publicly available for lots of reasons -
end users want to access it outside the cluster, any image promotion
requires that, we want to use DNS for the name, and we want to make it
simple to use.  Once we do that, it becomes fairly important where the
"pull location" is for a given image.  We are also working on fixing the
external auth so it's easier to login from the docker client.

**Comment by soltysh** [comment]
Still the main issue was, that when we have an IS and people do docker pull against the presented pull spec they will get an error. Eg. our default IS in openshift namespace: 
```
$ oc get is -n openshift
NAME         DOCKER REPO                               TAGS                          UPDATED
jenkins      172.30.208.39:5000/openshift/jenkins      1,latest                      3 minutes ago
mariadb      172.30.208.39:5000/openshift/mariadb      10.1,latest                   3 minutes ago
...
```
None of the above `DOCKER REPO` addresses is pullable. Besides with multiple images that you can reference within single IS presenting this information is pointless. Again see our IS, each tag is pointing to a different external repo and only getting per tag information will give you reasonable data, although docker ref there is not pullable, again: 
```
$ oc get istag/django-ex:latest
NAME               DOCKER REF                                                                                                  UPDATED              IMAGENAME
django-ex:latest   172.30.208.39:5000/test/django-ex@sha256:f39a7ee286d0c922c3838f0449f3364ee18d007ebfbcea6f9cefbceeb47b6933   About a minute ago   sha256:f39a7ee286d0c922c3838f0449f3364ee18d007ebfbcea6f9cefbceeb47b6933
```

**Comment by smarterclayton** [comment]
You can't tell from a client whether they are pullable or not by observation.  And the goal is that they will be pullable.

**Comment by soltysh** [comment]
> You can't tell from a client whether they are pullable or not by observation. And the goal is that they will be pullable.

So you're saying all will be pullthrough by default, that's how I understand that with the current capabilities we have?

**Comment by smarterclayton** [comment]
I'm saying the value returned by that API should be pullable.

On Aug 11, 2016, at 3:03 PM, Maciej Szulik <notifications@github.com> wrote:

You can't tell from a client whether they are pullable or not by
observation. And the goal is that they will be pullable.

So you're saying all will be pullthrough by default, that's how I
understand that with the current capabilities we have?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/5927#issuecomment-239258845>,
or mute the thread

**Comment by soltysh** [comment]
According to this we should do following:
- check if `.spec.dockerImageRepository` is specified and if the image is actually in the registry, if not present the spec, if it is present status.
- if there's no `.spec.dockerImageRepository`, because tags are specified we should not present anything since pull spec might be different per tag (see our builder + DB image streams)

Does that sound right?

**Comment by smarterclayton** [comment]
Status.dockerimagerepository is always the "pull" location because of
import and pull through.

**Comment by soltysh** [comment]
I think with the current state of `oc describe is` we can safely close this issue as addressed.
