### ISSUE TITLE
python scl extended test failure

### ISSUE THREAD

**Issue by bparees** [openshift/origin#5928]
```
• Failure [307.790 seconds]
images: Usage and SCL enablement of the S2I images returning s2i usage when running the image [It] "ci.dev.openshift.redhat.com:5000/openshift/python-27-rhel7" should print the usage 
/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/scl.go:37

  Expected error:
      <*errors.errorString | 0xc20862a830>: {
          s: "gave up waiting for pod 'test-pod-5c79b9a6-8cdb-11e5-8e85-0e31aff596ad' to be 'success or failure' after 5m0s",
      }
      gave up waiting for pod 'test-pod-5c79b9a6-8cdb-11e5-8e85-0e31aff596ad' to be 'success or failure' after 5m0s
  not to have occurred

  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/util.go:1123
------------------------------
    fail    images: Usage and SCL enablement of the S2I images returning s2i usage when running the image "ci.de ... (5m7.790275206s)
```

https://ci.openshift.redhat.com/jenkins/job/origin_extended/303/consoleFull

**Comment by bparees** [comment]
(actually looks like this test might be failing for every image)

**Comment by mfojtik** [comment]
@bparees this is flake or permanent failure?

**Comment by mfojtik** [comment]
@bparees it seems like the test pod is stuck in `pending` state which might indicate the images are not pushed. Did we flushed the internal rhel7 registry?

**Comment by bparees** [comment]
@mfojtik don't know if the registry was flushed, you can check the push job to see if it ran recently, i got Dan to schedule the push job to run whenever the registry gets flushed.

and I think it was a flake, but not sure, i didn't go digging through the history of extended builds to see.

**Comment by mfojtik** [comment]
@bparees I went thought last 10 extended builds or so and I haven't seen this flake anymore, so I think we can close this (and raise priority to fix the mysql replication extended test that if failing pretty consistently).
