### ISSUE TITLE
concurrent build controller integration test flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#5937]
--- FAIL: TestConcurrentBuildControllers-2 (7.26s)
    buildcontroller_test.go:109: Error: received unexpected build status: New
FAIL

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7192/console

logs available:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7192/artifact/origin/artifacts/

**Comment by csrwng** [comment]
Fixed with #5967. @bparees pls close
