### ISSUE TITLE
Add `--build-loglevel` option for start-build

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5941]
Would be nice to have an option for `start-build` to change the default build loglevel without actually modifying the build config manually. To make this work we just need to set the `BUILD_LOGLEVEL` env to whatever user specifies as a value.

This will help extended tests as we can verify more things in build log output without defining that env var for each build config.

Should be relatively easy change, so if @smarterclayton or @liggitt approves this, sign me up for this @bparees

**Comment by kargakis** [comment]
Can't --loglevel already work for this?

**Comment by mfojtik** [comment]
@kargakis that will set verbosity for the `oc` command itself. IOW. i'm not interested to see HTTP requests when I want just more verbose logs
