### ISSUE TITLE
The httpProxy and httpsProxy settings does not work when source URI has git:// prefix

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5944]
@bparees I'm addressing this in https://github.com/openshift/origin/pull/5573

Basically, when you have git:// prefix GIT will just ignore the HTTPS/HTTP proxy settings. 
See: http://stackoverflow.com/questions/27856378/bower-cant-fetch-packages-through-proxy-git-is-working-fine

Update:

To fix this, we should validate the BuildConfig.Source and check the URI when the http(s)Proxy fields are set. If the URI starts with `git://` we should give user validation error.

**Comment by liggitt** [comment]
git:// shouldn't use httpProxy/httpsProxy... it's not http-based

**Comment by liggitt** [comment]
Further details at https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#The-Git-Protocol

> It uses the same data-transfer mechanism as the SSH protocol but without the encryption and authentication overhead.

I don't think this is an issue

**Comment by mfojtik** [comment]
@liggitt this is issue when you set the proxy. Or we should document to use only https:// when behind proxy?

**Comment by liggitt** [comment]
if `git clone git://...` doesn't make use of http_proxy/https_proxy envvars, we shouldn't make it do so in the container, imo

**Comment by mfojtik** [comment]
@liggitt the PR I have will first detect that you set HTTPS_PROXY up. If that is true and you have the git:// prefix in URL, I execute the git config command to translate it into https.

**Comment by liggitt** [comment]
You can't assume https is available... they may have surfaced the repo over https, but may not have

**Comment by mfojtik** [comment]
@liggitt so if you are behind proxy and just copy&paste the git:// url from github you will be broken until you change it to https:// 

I would rather try https than failing and telling user to manually switch to https.

**Comment by liggitt** [comment]
> I would rather try https than failing and telling user to manually switch to https.

That has the potential to break things that would otherwise work, and is doing things with http_proxy/https_proxy that git itself doesn't do, right? I don't want to go down that road.

**Comment by mfojtik** [comment]
@liggitt I'm not sure I agree here. The check (and clone) will fail anyway without this. If the HTTPS_PROXY is set and the URL starts with git:// the build just error out with connection refused (if you have no connection other than via proxy). It will succeed but will not wire through proxy (which might not be what you want).

Rewriting this to https (only when the proxy is set) is what >80% users will do IMHO. IF that fails because  GIT server is not exposing HTTPS, then it will fail with the same error as before (connection refused)

**Comment by liggitt** [comment]
>  If the HTTPS_PROXY is set and the URL starts with git:// the build just error out with connection refused (if you have no connection other than via proxy).

How does git expect you to proxy git:// urls? We should do that, not switch to https

**Comment by mfojtik** [comment]
@liggitt + we print that we are rewriting the URI to https:// into build logs so you will see what is going on.

**Comment by mfojtik** [comment]
@liggitt  https://gist.github.com/sit/49288 :-) this is what I found when I was googling it

**Comment by mfojtik** [comment]
@liggitt full article: http://www.emilsit.net/blog/archives/how-to-use-the-git-protocol-through-a-http-connect-proxy/ 

I think this is uglier than rewrite ;-)

**Comment by liggitt** [comment]
beautiful and incorrect is still incorrect :)

**Comment by mfojtik** [comment]
@liggitt it would be incorrect to do this without telling user what we do, but we do tell and it actually make the user experience better than spending hours googling and trying to get the git:// via `httpsProxy` field work to realize that git:// does not support them and you have to use `https://` (in most cases)

**Comment by mfojtik** [comment]
@liggitt how about this:

We won't allow you to create BC that has URI with git:// protocol and in the same time http(s)Proxy field set. It will be validation error. In that case we fix the case git:// might succeed but it is not wired via proxy.

**Comment by bparees** [comment]
Validation error (and documentation update) definitely sounds like a better way to go than rewriting user provided urls.

**Comment by liggitt** [comment]
I would be fine with validation preventing proxy settings with git:// URLs, or logging warnings/errors if http_proxy/https_proxy is used with a git:// URL, but attempting anyway

**Comment by mfojtik** [comment]
@liggitt I think warnings are tricky because they might not be spotted in the build logs. Also if we run the build with proxy + git:// protocol and that build actually succeeded, we are silently bypassing the proxy user set which might not be good.

**Comment by bparees** [comment]
@mfojtik +1, ignoring the proxy setting would be bad.  if it only works for https/http then let's enforce that in validation and update the docs.
