### ISSUE TITLE
oc autoscale

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#5947]
Upstream added an autoscale command that adds autoscaling for replication controllers and deployments. We may want to re-use it and make it work for dcs too. 

Should be as simple as bundle the command and do something similar to https://github.com/kubernetes/kubernetes/pull/17269

@ironcladlou @DirectXMan12 @smarterclayton @ncdc

**Comment by smarterclayton** [comment]
Does it support non-Kube resources yet?  :)

On Wed, Nov 18, 2015 at 11:01 AM, Michail Kargakis <notifications@github.com

**Comment by ncdc** [comment]
Not the last time I looked

**Comment by kargakis** [comment]
What should support non-Kube resources?

**Comment by kargakis** [comment]
I see that the hpa controller is working with scale subresources (and we have one for dcs). As for the command, that's what the factory is for.
