### ISSUE TITLE
Icons and connecting lines are not dark enough in network view

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#5952]
For the web console, the icons and the connecting lines are not dark enough making them hard to see. Particular standouts are the route icon, the deployment config, and the connecting lines. 

Please increase the contrast of these pieces with the diagram. 

![screenshot from 2015-11-18 09-47-06](https://cloud.githubusercontent.com/assets/1404099/11249056/7ab2d752-8dd9-11e5-9508-5d74c538cd8b.png)

**Comment by stefwalter** [comment]
To fix this, I'll be making the links both darker, and changing the dotted lines to dashes. An example (this screenshot is of the same component, albeit not in openshift).

![screenshot from 2015-11-23 11-49-33](https://cloud.githubusercontent.com/assets/795070/11334899/57f0a174-91d8-11e5-820a-795ab44fbda8.png)

**Comment by thesteve0** [comment]
Definitely easier to see in the screenshot. Let me know when you have a branch that has it and I will try to check it out myself on an actual install. Thanks for the quick response

**Comment by thesteve0** [comment]
Can you also darken up the route icon and the gear icon (not sure what that stands for)

**Comment by jwforres** [comment]
Your second screenshot is actually making me wonder if we should have a legend in the openshift console. But thats a separate issue :)

**Comment by stefwalter** [comment]
> Your second screenshot is actually making me wonder if we should have a legend in the openshift console. But thats a separate issue :)

Yes, the other users of the topology view have a legend that's visible when no node is selected. In openshift web console there is explanation on the left but missing the icons to turn it into a legend.
