### ISSUE TITLE
Deploying registry failed behind a http proxy

### ISSUE THREAD

**Issue by jkhelil** [openshift/origin#5960]
I have installed origin v3 on openstack. Our openstack infrastructure get to internet through a proxy (I a m on a entreprise context, security relies a lot in our context).
Deploying internal registry on openshift failed with theses messages even if I set the https and http proxy environment variable

[root@os-master ~]# openshift version
openshift v1.0.8-1-g8f1868d
kubernetes v1.1.0-origin-1107-g4c8e6f4
etcd 2.1.2

Nov 19 11:32:15 os-master.example.com origin-master[18549]: [1.539522571s] [1.253µs] END
Nov 19 11:32:32 os-master.example.com origin-master[18549]: E1119 11:32:32.103473   18549 factory.go:49] [error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout, error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout]
Nov 19 11:33:02 os-master.example.com origin-master[18549]: E1119 11:33:02.104126   18549 factory.go:49] error checking for V2 registry at https://registry-1.docker.io/v2/: Get https://registry-1.docker.io/v2/: dial tcp 54.209.97.165:443: i/o timeout
Nov 19 11:33:32 os-master.example.com origin-master[18549]: E1119 11:33:32.104759   18549 factory.go:49] error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout
Nov 19 11:34:32 os-master.example.com origin-master[18549]: E1119 11:34:32.106072   18549 factory.go:49] [error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout, error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout]
Nov 19 11:36:02 os-master.example.com origin-master[18549]: E1119 11:36:02.107873   18549 factory.go:49] [error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout, error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout, error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout]
Nov 19 11:36:32 os-master.example.com origin-master[18549]: E1119 11:36:32.108472   18549 factory.go:49] error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout
Nov 19 11:37:32 os-master.example.com origin-master[18549]: E1119 11:37:32.109539   18549 factory.go:49] [error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout, error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout]
Nov 19 11:38:02 os-master.example.com origin-master[18549]: E1119 11:38:02.110389   18549 factory.go:49] error checking for V2 registry at https://registry-1.docker.io/v2/: Get https://registry-1.docker.io/v2/: dial tcp 54.209.97.165:443: i/o timeout
Nov 19 11:38:32 os-master.example.com origin-master[18549]: E1119 11:38:32.111119   18549 factory.go:49] error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: dial tcp 209.132.182.63:443: i/o timeout

**Comment by urashidmalik** [comment]
Getting same error with ansible installer on Vagrant : opened https://github.com/openshift/openshift-ansible/issues/942

**Comment by jkhelil** [comment]
I find a workaround, to unlock users,, deploying the registry behind a proxy, it is possible to fix the proxy using the systemd env variables
create /etc/systemd/system/origin-node.service/http_proxy.conf
and add
[Service]
Environment="HTTP_PROXY=http://proxy.example.com:80/"

then
systemctl daemon-reload
systemctl show origin-node --property Environment
systemctl restart origin-node

Inspired by https://docs.docker.com/engine/articles/systemd/

**Comment by sdodson** [comment]
@jkhelil You should have an /etc/sysconfig/origin-node file already, if you add HTTP_PROXY="http://proxy.example.com:80/" there it will achieve the same.

See this for a somewhat comprehensive guide on configuring OpenShift for proxy use. If you find something that's not documented there please let us know.

https://docs.openshift.org/latest/install_config/http_proxies.html

**Comment by akram** [comment]
@jkhelil do you think the issue can be closed ?

**Comment by jkhelil** [comment]
Yep
