### ISSUE TITLE
include link to "more details" on details pane

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#5966]
I noticed that in the topology view there's no easy way to go directly to an object's page (eg: the pod overview page with the metrics, logs, etc. tabs).

When you select an item in either the overview or the topology view, some details are presented in the right-hand details pane. It would be nice if there was a link to "more details" that then took you to the details page for that particular item.

**Comment by spadgett** [comment]
We've removed this sidebar from the overview. We do have direct links to most resources from the overview now as well: services, DCs, RCs, BCs, builds, and pods.
