### ISSUE TITLE
Admin role is not allowing the head verb

### ISSUE THREAD

**Issue by simon3z** [openshift/origin#5973]
The `admin` role (and probably other), cannot use the `head` verb:

    curl -v -k -H 'Authorization: Bearer <token>' -X HEAD \
      https://<apiserver>:8443/api/v1/namespaces/<namespace>/pods/<pod>
    < HTTP/1.1 403 Forbidden
    < Cache-Control: no-store
    < Content-Type: application/json
    < Date: Thu, 19 Nov 2015 22:39:59 GMT
    < Content-Length: 384

This may not be particularly interesting for the kubernetes/openshift api but it applies also to the proxy, effectively preventing `admins` from using `head` on any rest-api served by pods and services.

cc @deads2k @liggitt

**Comment by deads2k** [comment]
I'm assuming this permission is leading to the `ClusterRole` here: https://github.com/simon3z/manageiq.org/blob/containers-docs/source/documentation/getting-started.html.md#service-accounts ?

**Comment by deads2k** [comment]
@liggitt You want to explicitly list the `head` verb or assume that our API works correctly and power to `get` implies power to `head`

**Comment by simon3z** [comment]
> I'm assuming this permission is leading to the ClusterRole here:

@deads2k correct (there should be a note in that doc to this Issue).

> @liggitt You want to explicitly list the head verb or assume that our API works correctly and power to get implies power to head

Adding `head` didn't work for me. Maybe I overlooked something (or maybe `head` is not expected as verb).

**Comment by liggitt** [comment]
@simon3z `head` method wasn't handled at all. https://github.com/openshift/origin/pull/5985/files#diff-d8a717a6f0dc0916348eea8de58caac5R505 maps it to "get" for API requests
