### ISSUE TITLE
Service page should link to routes page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5979]
We show the routes for the service, but we have no link to the route's page in the web console with additional route details.

<img width="706" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11300146/9fb07136-8f5a-11e5-952f-cf4b0fcf89d4.png">

/cc @jwforres

**Comment by jwforres** [comment]
@juanvallejo while we are working on the service page we could do something about this issue.

You could update the routes section to something like a table with the route names, hostnames, and whether the route is accepting traffic.  @spadgett thoughts?

**Comment by spadgett** [comment]
+1, we might make the routes table from `app/views/browse/routes.html` a directive like we did for `pods-table`. Then we could reuse it here.

@juanvallejo see

https://github.com/spadgett/origin-web-console/blob/master/app/views/directives/pods-table.html
https://github.com/spadgett/origin-web-console/blob/c6dbf16e5584671d4d8c84343e890c5f3a9327cf/app/scripts/directives/resources.js#L161-L171
https://github.com/spadgett/origin-web-console/blob/c6dbf16e5584671d4d8c84343e890c5f3a9327cf/app/views/browse/_replica-set-details.html#L179
