### ISSUE TITLE
`openshift ex diagnostics --help` should list available diagnostics

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5984]
Currently, you have to specify `-d InvalidValue` to be told what the valid values are

cc @sosiouxme @rjhowe

**Comment by sosiouxme** [comment]
The standard mechanism of putting possible values with the parameter seemed like a bad idea once the list of diagnostics gets long. They should probably be listed separately.

**Comment by liggitt** [comment]
Can be part of the long desc
