### ISSUE TITLE
oc rsync provides odd message for pod in pending state

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin#5986]
```
$ oc rsync lib/directives logging-kibana-8-ondvt:/opt/app-root/src/src/public/plugins/origin-kibana
WARNING: cannot use rsync: rsync not available in containerWARNING: cannot use tar: tar not available in containererror: tar not available in container
```
I would have expected some other message.

**Comment by dinhxuanvu** [comment]
Hi. I encounter the same issue even if the pod is in running state. I was simply using 'oc rsync' to copy some local files to the pod.

**Comment by dinhxuanvu** [comment]
Just a bit more details on this issue. I was using a Postgresql 9.2 image for the pod and somehow it looks like that image doesn't include rsync on it which causes this issue.

**Comment by oatmealraisin** [comment]
I believe https://github.com/openshift/origin/pull/9281 also fixes this.
#8505 is very similar.
