### ISSUE TITLE
Route path is shown in both hostname and path fields in UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5994]
If we have the path in the hostname, we can remove the path field below.

<img width="351" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11310375/309d605a-8f97-11e5-8233-849851ff9f41.png">

/cc @jwforres

**Comment by jwforres** [comment]
So this was intentional from the perspective that I wanted users to know
path is a separate configurable field.  Maybe the link next to hostname
should include the path in the href but not show it visually.

**Comment by spadgett** [comment]
It seems a little odd that the path is in a value labeled hostname. We're already hiding the protocol in the link text, so I'd vote for hiding the path, too.
