### ISSUE TITLE
Secure delete when recycling

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#6001]
We used to have 'shreding' of the files when recycling files of a PV : 

https://github.com/openshift/origin/commit/ac8cee50ce7dc55f44f03fe8d6bbcdc2afb8f08c#diff-cc1688e32a2e8c141eb5ef80bcabdfdfL30

but since this was changed to a binary, it now uses just a simple Remove : 

https://github.com/openshift/origin/commit/ac8cee50ce7dc55f44f03fe8d6bbcdc2afb8f08c#diff-eda26588662d12c1173c056f4541d14eR14

For some security requirements the recycling needs to be done securely with multiple zero pass like shred do : 

https://en.wikipedia.org/wiki/Shred_(Unix)

is there any chances to get this behaviour for the binary implementation?

**Comment by liggitt** [comment]
The shred documentation has a long list of filesystems and conditions in which it does not work as advertised. For many (most?) of the persistent volume types we support, writing zeros to a file would not actually overwrite the same data blocks on disk. @eparis, care to weigh in?

**Comment by liggitt** [comment]
cc @markturansky

**Comment by markturansky** [comment]
@chmouel for 3.2 we're planning the ability to configure many types of recyclers that match volumes by selector.  Is the ability to provide a custom recycler sufficient for you to shred files, etc.?

**Comment by chmouel** [comment]
@markturansky custom recycler would be awesome, would that be for 3.1.x ?

**Comment by markturansky** [comment]
@chmouel per our email conversation, we're looking to get #6110 into 3.1.1.

**Comment by chmouel** [comment]
thanks @markturansky

**Comment by pweil-** [comment]
closing due to age, upstream PR was merged
