### ISSUE TITLE
disable test-cmd.sh colors based on tty

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6013]
Piped and redirected output using the new commands is really hard to read because of the colors.  Add a flag to disable and try to detect if there's a tty.  Without one, don't do colors.

**Comment by stevekuznetsov** [comment]
Can you give an example of what is difficult or not difficult to read, specifically?

**Comment by deads2k** [comment]
```
Running  exit 0...
[1A[K[32m[1mSUCCESS: exit 0
(B[mThere was no output from the command.
There was no error output from the command.
Running  exit 10...
[1A[K[32m[1mSUCCESS: exit 10
(B[mThere was no output from the command.

```

**Comment by stevekuznetsov** [comment]
This occurs when you use one of the commands and redirect / pipe the output somewhere, right? I have a commit in https://github.com/openshift/origin/pull/6012 that changes the aliases to functions and does a TTY check. If that runs well on Jenkins I will break it out into a separate pull to fix this issue.
