### ISSUE TITLE
os::cmd::expect_* expands variables when it shouldn't

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6014]
Found while translating [this line](https://github.com/openshift/origin/blob/master/test/cmd/volumes.sh#L18) from:
```sh
$ [ "$(oc volume dc/test-deployment-config --add --name=vol1 --type=secret --secret-name='$ecret' -m /data 2>&1 | grep overwrite)" ]
```
to
```sh
$ os::cmd::expect_failure_and_text "oc volume dc/test-deployment-config --add --name=vol1 --type=secret --secret-name='$ecret' -m /data" 'overwrite'
```

This fails with `test/cmd/volumes.sh: line 19: ecret: unbound variable`.

The path of the command as it is routed through the helper methods is `"${cmd}"` in [`os::cmd::expect_failure_and_text`](https://github.com/openshift/origin/blob/master/hack/cmd_util.sh#L41), `"${cmd}"` in [`os::cmd::internal::expect_exit_code_run_grep`](https://github.com/openshift/origin/blob/master/hack/cmd_util.sh#L121) and `"${cmd}"` in [`os::cmd::internal::run_collecting_output`](https://github.com/openshift/origin/blob/master/hack/cmd_util.sh#L161). @Miciah @smarterclayton any thoughts on where this expansion is being done?

**Comment by Miciah** [comment]
In the first snippet, you have single-quotes `'$ecret'` inside the command for a command substitution `$()`.  In the second example, you have single-quotes `'$ecret'` inside a double-quoted string.  In a command, single-quotes quote; inside a double-quoted string, single-quotes are just literal single-quotes, so they don't prevent Bash from interpolating variables.

**Comment by stevekuznetsov** [comment]
On further thought I *think* this is working as expected, as `" ... '\$ecret' ... "` is actually passed into the first function as `" ... '$ecret' ... "`. The above issue can be solved by using single quotes `''` around the entire clause and *not* using quotes around `'$ecret'`. In this case, this is fine as the single quotes aren't necessary for the flag. However, in another case, they are:
```sh
$ oc describe secrets/dockercfg | grep "dockercfg:" | awk '{print $2}' > ${HOME}/dockerconfig
```

We need to find a way to make that idiomatic.

**Comment by stevekuznetsov** [comment]
More clearly, we need to quote the entire string `oc describe secrets/dockercfg | grep "dockercfg:" | awk '{print $2}' > ${HOME}/dockerconfig` but *also* need single quotes around the `awk` parameters *and* would like to not have to use `\$` to keep the var from being expanded.

**Comment by stevekuznetsov** [comment]
I'm not particularly happy with this solution, but `' ... '"'"' ... '` works.

**Comment by liggitt** [comment]
> The above issue can be solved by using single quotes '' around the entire clause and not using quotes around '$ecret'. In this case, this is fine as the single quotes aren't necessary for the flag.

I think unquoting `$ecret` would re-enable interpretation of it as an envvar again when the cmd is eval-ed

example 1:
level 1: `eval "echo '\$ecret' "`
level 2: `echo '$ecret'`
echo command sees: `$ecret` as the arg

example 2 (your proposal):
level 1: `eval 'echo $ecret'`
level 2: `echo $ecret`
echo command sees bash-substituted value of envvar `$ecret` as the arg

**Comment by stevekuznetsov** [comment]
I think this is resolved. If you want to pass things in that don't get expanded, escape the `$` with `\$` and call it a day. @deads2k @liggitt is there anything else we need to do for this?

**Comment by liggitt** [comment]
nope
