### ISSUE TITLE
Enhance the alerts service in the web console

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#6016]
Original discussion on [this PR](https://github.com/openshift/origin/pull/5953).

Creating an Alerts service would provide us another way to keep `$scope` out of our services but still update the UI with important events. Usage could be something like this:

``` javascript
// from DeploymentsService
retryFailedDeployment: function(deployment, context) {
      DataService.update{'replicationcontrollers', context, function() {
         // notify user of happy things
         alertService.publish({type: 'success', message: 'Yay!'})
      },
      function() {
         // notify user of sad things
         alertService.publish({type: 'error', message: 'Booo'})
      })
     // other requests below do the same thing...
}
```

Since alerts seem to be context oriented, we would have to update the alerts directive to use the alerts service to get its data, rather than directly passing from controllers.  The alerts service would need to watch `$routeChangeSuccess` events to clean out its cache, unless we want to allow some alerts to linger.  We may also have to deal with alerts generated from a resource after the user has navigated to a different page (no longer relevant to immediate context).

**Comment by jwforres** [comment]
We have one, it was added in the "let me delete anything" PR https://github.com/openshift/origin/blob/master/assets/app/scripts/services/alertMessage.js

You probably just need to rebase to pick it up.

If its missing something you need feel free to update it, just make sure it still works with Delete.  It specifically does not clear itself on refresh

**Comment by benjaminapetersen** [comment]
Ah, i see it.  But it doesn't look like the `<alerts>` directive is using it.  I'll have to dig in and see if the usage is similar enough/same & we can connect them up.

**Comment by benjaminapetersen** [comment]
Current usage looks like this:

```javascript
   // from controller deployments.js 
   // ---------------
    // get and clear any alerts
    AlertMessageService.getAlerts().forEach(function(alert) {
      $scope.alerts[alert.name] = alert.data;
    });
    AlertMessageService.clearAlerts();
```
Have to think about this, we could probably streamline further.

**Comment by spadgett** [comment]
This is fixed by NotificationService and toast messages (thanks @jeff-phillips-18)
