### ISSUE TITLE
Update breadcrumbs directive to provide defaults

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#6017]
The breadcrumbs directive can probably assess `$routeParams` on its own & generate sensible defaults in most contexts, allowing us to eliminate some more code in our controllers.  We could still allow `$scope.breadcrumbs` to be set if we wanted to provide an override option.

**Comment by benjaminapetersen** [comment]
@jwforres

**Comment by jwforres** [comment]
Hmm yeah some of the pages there are defaults that make sense, there are some that are more complex for builds and deployments because we use the build/deployment number in the breadcrumb and we only know that after we go and fetch the object.

**Comment by benjaminapetersen** [comment]
Feel free to assign me!

**Comment by jwforres** [comment]
We addressed a lot of these issues in a different way during 3.4, we could still consider whether the breadcrumb directive itself should read in the $routeParams and pass to the BreadcrumbsService to get the breadcrumbs if you don't pass a breadcrumbs object to the directive

**Comment by benjaminapetersen** [comment]
Yeah, was thinking it should default to figure out something sensible via `$routeParams`, unless passed something to override.

**Comment by jwforres** [comment]
talking with @spadgett we are going to close this, we have a service that has taken the logic out of the controllers which was the original goal.

**Comment by benjaminapetersen** [comment]
sounds good
