### ISSUE TITLE
TestCheckRemoteGit unit test pauses to ask for credentials on OS X with git 2.5.0

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#6026]
```
hack/test-go.sh pkg/build/builder -v -run "TestCheckRemoteGit"
=== RUN TestCheckRemoteGit
Username for 'http://127.0.0.1:56768':
Password for 'http://127.0.0.1:56768':
```

**Comment by csrwng** [comment]
@mfojtik

**Comment by mfojtik** [comment]
@csrwng I don't have a Mac around to reproduce this. It works fine on Linux. Would it make sense to opt-out this test when running on OSX?

**Comment by mfojtik** [comment]
@csrwng also according to internets, the "askpass" is different on OSX git for some reason...

**Comment by mfojtik** [comment]
got it :)

**Comment by mfojtik** [comment]
@csrwng i assume this was already fixed, correct?
