### ISSUE TITLE
test-integration doesn't use os::cmd::expect_success, but could

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6028]
@liggitt What do you think? The helper method in `test-integration` is actually what `os::cmd::expect_success` is based on. I think this would be a positive change because it would DRY out the code, as well as allowing for a single point of interaction with a jUnit-producing script that would allow the jUnit parser to use the same rules for `test-cmd` and `test-integration`. The only differences would be:
1. `test-integration` can skip tests
2. I may change `os::cmd::expect_success` to use the call-stack to identify the line calling the function instead of passing in a name, and `test-integration` is better off using the name convention. I implemented a pseudo-strategy pattern with "function pointers" in the internals of `os::cmd::expect*` for exit code comparisons, and could do so again for test identifier functions, but @deads2k rightfully pointed out that things are on fairly shaky ground in bash, passing strings around that just happen to refer to functions isn't the best. I can keep it all contained within `os::cmd::internal` namespace as before, but maybe that's too much of a hassle for DRYing out `test-integration`?

**Comment by deads2k** [comment]
I don't think this would be worth it for `test-integration`.  Those tests are already well structured, they're actually standard go tests.

**Comment by liggitt** [comment]
agree, I'd rather capture the output using standard go test parsing
