### ISSUE TITLE
oc login woes

### ISSUE THREAD

**Issue by stevef1uk** [openshift/origin#6039]
Hi,

Sorry newbie question, but after lots of Googling I can't solve this myself.

I have installed Origin V3 on a linux server (mint distribution) and all was ok. I then tried to install the fabric8 stuff and I couldn't get the console to work so I decided to start again. Now I find that whenever I try oc login I get the error:
'The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.'

I have tried using the --insecure-skip-tls-verify=false option which didn't work with the error:
'error: specifying a root certificates file with the insecure flag is not allowed'

I have tried setting the --certificate-authority='X', but I am not sure what X should be, I have tried pretty much everything in the ~/origin/openshift.local.config/master directory including the admin.crt file and still get the original error.

I have deleted all the files I can find on my filesystem that running openshift creates, but I think I must have missed something.

Any ideas?

Thanks

Steve

**Comment by liggitt** [comment]
The ca.crt in the master directory is what you need

**Comment by stevef1uk** [comment]
Yes, that was the first one I had tried, but no joy.

**Comment by stevef1uk** [comment]
This may be because the default password has changed from admin and that the error message is misleading me.
