### ISSUE TITLE
openshift cli help {update,replace,patch} not working

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6042]
Neither `openshift cli help update`, `replace`, or `patch` are giving the correct output. All error with:

```
error: unknown command "help replace"
See 'openshift cli -h' for help and examples.
```

**Comment by stevekuznetsov** [comment]
Once these are fixed, their tests in `test/cmd/help` need to be fixed and enabled.

**Comment by deads2k** [comment]
I think the intent here is to have `oc help update` be the same as `openshift cli help update`.

**Comment by fabianofranz** [comment]
Also here: https://github.com/openshift/origin/pull/5670/files#diff-a1889a7743ca6296d75affc270e527a9R108

**Comment by fabianofranz** [comment]
Seems like a regression because of recent Cobra changes, `help` is always being registered in the root command (so `openshift help cli update` works). I'll take a look at it.

**Comment by stevekuznetsov** [comment]
@openshift/sig-user-interface

**Comment by juanvallejo** [comment]
No longer applies, as `openshift cli` has been deprecated
