### ISSUE TITLE
Need ability to register a plug-in to clean up content in a namespace when a project is deleted

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#605]
In Origin, a ```Project``` resource is needed to declare a ```Namespace``` to hold content in Kubernetes and Origin.

If a ```Project``` is deleted, we need to ensure that all content in the reserved ```Namespace``` is removed.

We should enable components that store content to register a life-cycle plug-in that can be invoked by the project rest endpoint to delete related content prior to deleting the project.

```
interface ProjectLifecycle {
  // OnDelete is invoked when a project is deleted.  Components should delete content they manage
 // in the specified namespace.  An error should be returned if the delete could not succeed.
  func OnDelete(projectName, namespace string) error
}
```

```
func init() {
   projectplugins.Register("ImageRepostory", &imageRepositoryLifecycle)
}
```

**Comment by liggitt** [comment]
@smarterclayton what's the priority on this... deleting a project and having all the resources and permissions continue to chug along is... unexpected

**Comment by derekwaynecarr** [comment]
@liggitt - I spoke with upstream team and they are supportive of the ability to ask a Namespace to gracefully terminate and as part of that process it would delete all resources in that namespace.  Requires a NamespaceController to drive that process to observe when a Namespace has been asked to terminate, do the clean-up, and then do the final deletion.  The general statement from upstream was that every segment of the path should support deletion on the server side.  Meaning, you should be able to say all of the following:

1. delete pod x in namespace y
2. delete all pods in namespace y
3. delete namespace y

and the right thing should happen.

**Comment by derekwaynecarr** [comment]
My vote is we need to fix this before 1.0, and it's in a position that is easier to fix now than some other areas.

**Comment by smarterclayton** [comment]
It's definitely something valuable, but it doesn't block a lot of use cases right now.

**Comment by liggitt** [comment]
@derekwaynecarr doesn't cleanup happen now?

**Comment by derekwaynecarr** [comment]
Yup.  Closing issue.
