### ISSUE TITLE
Delete button larger on some pages than others

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6054]
We should try to be consistent with the size.

<img width="391" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11370804/5a0ef9b8-9293-11e5-9258-a873a00cda7d.png">

<img width="384" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11370817/606c2682-9293-11e5-9ef4-fb249104834e.png">

**Comment by jwforres** [comment]
no longer valid, delete button is now under the menu icon
