### ISSUE TITLE
`oadm ca` should generate serial.txt that is compatible with openssl

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6055]
OpenSSL requires the serial.txt to be "a text file containing the next serial number to use in hex"

`oadm ca` currently consumes and writes serial.txt as a text file with decimal numbers. Switching to hex would be a strict increase in serial number, so would not cause problems with existing certs, and would allow the serial text file to be used by openssl as well.

**Comment by liggitt** [comment]
cc @detiber @sosiouxme

**Comment by sosiouxme** [comment]
+1

**Comment by detiber** [comment]
@abutcher this is the CA serial issue I was discussing with you.
