### ISSUE TITLE
Kube rebase on a Mac doesn't pick up docker/pkg/units

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#606]
Due to https://github.com/tools/godep/issues/161

Not sure whether we want to fix this in rebase-kube or upstream, needs some thought.

**Comment by jzelinskie** [comment]
This is the specific library that caused me to create the aforementioned issue.

**Comment by smarterclayton** [comment]
Will track upstream

**Comment by jzelinskie** [comment]
If you want to know, we resolved this by simply using `GOOS=linux go get -d ./...` for `go get` on OSX.

**Comment by smarterclayton** [comment]
So simple :)
