### ISSUE TITLE
Cascading delete of deployment configs makes `oc replace --force` destructive

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6068]
`oc replace --force` does a delete/recreate. Since upstream handles cascading client-side, they can default `--cascade=false` during a force recreate and avoid deleting all dependent objects. However, since deployment configs cascade to deleting deployments server-side, replacing a deployment config removes all active deployments. This is not obvious (especially when `oc replace --help` shows `--cascade` defaulting to `false`)

cc @ironcladlou

**Comment by liggitt** [comment]
This came up when implementing similar server-side cascade deletion for build configs in https://github.com/openshift/origin/pull/5208

I like server-side cascade, I just want a way to opt out

**Comment by liggitt** [comment]
If the only time we'd want to opt-out is during a force replace, I could maybe see reworking that to do an unconditional update instead of a delete/recreate

**Comment by bparees** [comment]
Where/when do you want to make the decision to opt-out?  As discussed in #5208 one solution is to add a Cascade=false/true, but then that would depend on the client implement setting that properly before invoking the replace/force, and i'm sure that's not going to fly.

**Comment by bparees** [comment]
we could also ignore delete requests for 60s :)

**Comment by kargakis** [comment]
> However, since deployment configs cascade to deleting deployments server-side

Are you sure about this? I think we were cascading client-side: https://github.com/openshift/origin/tree/master/pkg/deploy/reaper

**Comment by kargakis** [comment]
Upstream the intention is to implement cascading to the server but I cannot find the issue/comment now.

**Comment by soltysh** [comment]
@kargakis I think you were looking for this: https://github.com/kubernetes/kubernetes/issues/1535#issuecomment-156185924

**Comment by kargakis** [comment]
yes, this is it : )

**Comment by ironcladlou** [comment]
Wanted to note that reparenting RCs with a new DC is theoretical/untested at the moment. Previous discussion in #3660.

**Comment by ironcladlou** [comment]
Agree with @kargakis, deploymentConfig delete handling is via the reaper package client-side.

**Comment by ironcladlou** [comment]
Seems like the initial issue description stems from a misunderstanding. The deploymentConfig delete handling is client side, and there's a Reaper implementation. If `--cascade=false`, the reaper isn't used, and so deployments deleted aren't cascaded. If `--cascade=true`, the reaper is used, and associated deployments are deleted.

Looks like this one can be closed?

**Comment by liggitt** [comment]
agreed
