### ISSUE TITLE
build always failed

### ISSUE THREAD

**Issue by pstinghua** [openshift/origin#6071]
```
I1125 01:21:16.387932       1 sti.go:163] The value of ALLOWED_UIDS is [1-]
2
I1125 01:21:16.444869       1 docker.go:230] Pulling image docker.io/openshift/wildfly-81-centos7@sha256:130d53fe32020f9aaa562c6ba426e0ca6f94c2303fa20e14ab53331a8a927f98
3
I1125 01:21:41.875812       1 sti.go:185] Creating a new S2I builder with build config: "Builder Name:\t\tWildFly 8.1\nBuilder Image:\t\tdocker.io/openshift/wildfly-81-centos7@sha256:130d53fe32020f9aaa562c6ba426e0ca6f94c2303fa20e14ab53331a8a927f98\nSource:\t\t\tfile:///tmp/s2i-build271744755/upload/src#master\nOutput Image Tag:\t172.30.53.167:5000/demo/jee:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAME=jee-1,OPENSHIFT_BUILD_NAMESPACE=demo,OPENSHIFT_BUILD_SOURCE=https://git.sanjiang.info/xieyuanliang/openshift-jee-sample.git,OPENSHIFT_BUILD_REFERENCE=master\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nWorkdir:\t\t/tmp/s2i-build271744755\nDocker NetworkMode:\tcontainer:95cf3c05b8fc45d00bb6c4b709a6916627a5fa169b527b970ec6cc060f6ac816\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
4
I1125 01:21:41.881208       1 docker.go:213] Image docker.io/openshift/wildfly-81-centos7@sha256:130d53fe32020f9aaa562c6ba426e0ca6f94c2303fa20e14ab53331a8a927f98 available locally
5
I1125 01:21:41.887235       1 sti.go:136] Preparing to build 172.30.53.167:5000/demo/jee:latest
6
I1125 01:22:03.325460       1 cleanup.go:23] Removing temporary directory /tmp/s2i-build271744755
7
I1125 01:22:03.325583       1 fs.go:99] Removing directory '/tmp/s2i-build271744755'
8
F1125 01:22:03.326307       1 builder.go:59] Build error: dial tcp 60.191.124.236:443: i/o timeout
```

**Comment by pstinghua** [comment]
Builder does not use local dns server

**Comment by soltysh** [comment]
Can you run your build with increased log level, see https://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs

**Comment by bdecoste** [comment]
Seeing the same thing in a clean 3.1 install. Logs with level 5 below:

[joe@ose3x-master ~]$ oc build-logs helloworld-1
Command "build-logs" is deprecated, use "logs" instead.
I1203 15:29:26.259804       1 builder.go:34] $BUILD env var is {"kind":"Build","apiVersion":"v1","metadata":{"name":"helloworld-1","namespace":"demo","selfLink":"/oapi/v1/namespaces/demo/builds/helloworld-1","uid":"8adaefd7-99fc-11e5-9b7d-5254004e0d51","resourceVersion":"16392","creationTimestamp":"2015-12-03T20:29:24Z","labels":{"application":"helloworld","buildconfig":"helloworld","openshift.io/build-config.name":"helloworld","template":"eap64-basic-s2i","xpaas":"1.2.0"},"annotations":{"openshift.io/build.number":"1"}},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"http://github.com/jboss-developer/jboss-eap-quickstarts","ref":"6.4.x"},"contextDir":"helloworld"},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"ose3x-master.example.com:5000/jboss-eap-6/eap64-openshift:1.2"},"env":[{"name":"BUILD_LOGLEVEL","value":"5"}],"forcePull":true}},"output":{"to":{"kind":"DockerImage","name":"172.30.42.226:5000/demo/helloworld:latest"},"pushSecret":{"name":"builder-dockercfg-raucb"}},"resources":{}},"status":{"phase":"Pending","outputDockerImageReference":"172.30.42.226:5000/demo/helloworld:latest","config":{"kind":"BuildConfig","namespace":"demo","name":"helloworld"}}}
 
I1203 15:29:26.280420       1 sti.go:163] The value of ALLOWED_UIDS is [1-]
I1203 15:29:26.280462       1 cfg.go:44] Locating docker auth for image ose3x-master.example.com:5000/jboss-eap-6/eap64-openshift:1.2 and type PULL_DOCKERCFG_PATH
I1203 15:29:26.280522       1 cfg.go:80] Using Docker authentication configuration in '/root/.docker/config.json'
I1203 15:29:26.280731       1 cfg.go:52] Problem accessing /root/.docker/config.json: stat /root/.docker/config.json: no such file or directory
I1203 15:29:26.280749       1 cfg.go:44] Locating docker auth for image 172.30.42.226:5000/demo/helloworld:latest and type PUSH_DOCKERCFG_PATH
I1203 15:29:26.280757       1 cfg.go:80] Using Docker authentication configuration in '/var/run/secrets/openshift.io/push/.dockercfg'
I1203 15:29:26.280896       1 cfg.go:66] Using serviceaccount user for Docker authentication for image 172.30.42.226:5000/demo/helloworld:latest
I1203 15:29:26.280925       1 docker.go:230] Pulling image ose3x-master.example.com:5000/jboss-eap-6/eap64-openshift:1.2
I1203 15:29:33.140985       1 sti.go:185] Creating a new S2I builder with build config: "Builder Name:\t\tJBoss EAP 6.4\nBuilder Image:\t\tose3x-master.example.com:5000/jboss-eap-6/eap64-openshift:1.2\nSource:\t\t\tfile:///tmp/s2i-build110728303/upload/src#6.4.x\nContext Directory:\thelloworld\nOutput Image Tag:\t172.30.42.226:5000/demo/helloworld:latest\nEnvironment:\t\tOPENSHIFT_BUILD_REFERENCE=6.4.x,BUILD_LOGLEVEL=5,OPENSHIFT_BUILD_NAME=helloworld-1,OPENSHIFT_BUILD_NAMESPACE=demo,OPENSHIFT_BUILD_SOURCE=http://github.com/jboss-developer/jboss-eap-quickstarts\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\t\x1b[1menabled\x1b[0m\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nWorkdir:\t\t/tmp/s2i-build110728303\nDocker NetworkMode:\tcontainer:bce13d92999df5c409675179564011e75aa0bdb77cc52efb194d9217166640ab\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I1203 15:29:33.141019       1 docker.go:230] Pulling image ose3x-master.example.com:5000/jboss-eap-6/eap64-openshift:1.2
I1203 15:29:40.286764       1 sti.go:191] Starting S2I build from demo/helloworld-1 BuildConfig ...
I1203 15:29:40.286783       1 sti.go:136] Preparing to build 172.30.42.226:5000/demo/helloworld:latest
I1203 15:29:56.288329       1 cleanup.go:23] Removing temporary directory /tmp/s2i-build110728303
I1203 15:29:56.288352       1 fs.go:99] Removing directory '/tmp/s2i-build110728303'
F1203 15:29:56.288538       1 builder.go:59] Build error: dial tcp: i/o timeout

**Comment by bparees** [comment]
dial tcp errors occur when we're attempting to clone the source from github, so it usually indicates a network configuration issue, often with the SDN, that is preventing containers from getting external access.

can you confirm/deny that your pods have external network access? (eg launch a db pod or jenkins pod and rsh in and see if it has external connectivity to github)

**Comment by PiotrKlimczak** [comment]
I have same issue with latest origin build with ansible on centos 7.1.
Answered to duplicated issue #5796.
In my i can curl from pods and can do git clone (with some strange result but still can).
See details in #5796.

So from my understanding it is not SDN related.

**Comment by bparees** [comment]
@PiotrKlimczak please share your buildconfig and build logs and any other information you can provide about the steps you took and the symptoms you observed.

**Comment by PiotrKlimczak** [comment]
Hi @bparees 
Thanks for answer. Unfortunately no build log as I had logging switched off. But has 0 errors.
Inventory file used attached.
[hosts.txt](https://github.com/openshift/origin/files/71181/hosts.txt)

What is still strange for me, are:
1. No skydns pod
2. It fails immediately, is it possible it is failing on non existing unix socket?

**Comment by bparees** [comment]
what about your buildconfig?  and you can turn logging on in the buildconfig:
https://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs

i'd prefer you start a new issue for this as i'm not convinced your config or symptoms match this issue.

**Comment by PiotrKlimczak** [comment]
Well sure I can create new issue, but I am thinking it is rather same issue:

My build log from openshift app seems to be exactly same as in topic:
I1223 19:34:29.152116       1 sti.go:163] The value of ALLOWED_UIDS is [1-]
2	I1223 19:34:29.155772       1 docker.go:213] Image docker.io/centos/perl-520-centos7@sha256:061a792de4eda7371d84e50975028bdba6b9d43769a081e66a89227274c90bf6 available locally
3	I1223 19:34:29.155854       1 sti.go:185] Creating a new S2I builder with build config: "Builder Name:\t\tApache 2.4 with mod_perl/5.20\nBuilder Image:\t\tdocker.io/centos/perl-520-centos7@sha256:061a792de4eda7371d84e50975028bdba6b9d43769a081e66a89227274c90bf6\nBuilder Image Version:\td783d80045a80ad784928f5e76e490ec7a7f0c4e\nBuilder Base Version:\t67415e3\nSource:\t\t\tfile:///tmp/s2i-build696714002/upload/src\nOutput Image Tag:\t172.30.10.84:5000/test/dancer-example:latest\nEnvironment:\t\tOPENSHIFT_BUILD_SOURCE=https://github.com/openshift/dancer-ex.git,OPENSHIFT_BUILD_NAME=dancer-example-3,OPENSHIFT_BUILD_NAMESPACE=test\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nWorkdir:\t\t/tmp/s2i-build696714002\nDocker NetworkMode:\tcontainer:647de1983fe50b6bd08673c9dac174d89a3a00b017210c6abd5f176d81875f22\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
4	I1223 19:34:29.157854       1 docker.go:213] Image docker.io/centos/perl-520-centos7@sha256:061a792de4eda7371d84e50975028bdba6b9d43769a081e66a89227274c90bf6 available locally
5	I1223 19:34:29.163438       1 sti.go:136] Preparing to build 172.30.10.84:5000/test/dancer-example:latest
6	I1223 19:34:45.164602       1 cleanup.go:23] Removing temporary directory /tmp/s2i-build696714002
7	I1223 19:34:45.164644       1 fs.go:99] Removing directory '/tmp/s2i-build696714002'
8	F1223 19:34:45.165242       1 builder.go:59] Build error: dial tcp: i/o timeout

**Comment by PiotrKlimczak** [comment]
I guess I misunderstood which build logs you want :), i thought you want logs for whole Openshift install.
But i guess you mean log for that example project. Let me increase logging level and will add log soon.

**Comment by PiotrKlimczak** [comment]
Build debug attached
[build_debug.txt](https://github.com/openshift/origin/files/71204/build_debug.txt)

Hope this is what you meant.
Was built with 
                    {
                        "name": "BUILD_LOGLEVEL",
                        "value": "5"
                    },

**Comment by PiotrKlimczak** [comment]
OK, so have no idea how, restarted service many times in web UI, on suddenly it started to work.
Was simply clicking rebuild, rebuild and suddenly succeed. That is disappointing, was in hope we will find the core of the issue.
I haven't made single change to environment/services/pods/etc! Was just clicking rebuild and suddenly worked.

Any idea?

**Comment by bparees** [comment]
@pstinghua are you still having issues?

@PiotrKlimczak is 172.30.0.1 in your host's /etc/resolv.conf?  is that the ip address of your master?

normally there should be something listening on port 53 on your master, and the /etc/resolv.conf for all pods should include the master ip as the primary DNS.

For additional debug i suggest you "oc run openshift/jenkins-1-centos7" and then "oc rsh" into the resulting pod.  From there you can attempt to perform git clone operations, dns lookups, and attempt to ping github. That will give you some insight into where things are failing.  You can also inspect the /etc/resolv.conf of the pod container.
