### ISSUE TITLE
Recycler fails on zfs

### ISSUE THREAD

**Issue by vilppuvuorinen** [openshift/origin#6080]
Volume root contains ```.zfs``` directory on a zpool managed zfs that cannot be deleted when scrubbing. Recycling manually is not a long term plan and custom recyclers are not exactly just around the corner (#6001).

Full error:
```
Scrub failed: /scrub/.zfs/shares (dr-xr-xr-x), calling walkFn: remove /scrub/.zfs/shares: errno 524
```

**Comment by liggitt** [comment]
That directory appears to have no write permissions enabled. That is one of several cases the currently recycler is not able to overcome (see description in https://github.com/openshift/origin/pull/5847)

cc @markturansky

**Comment by vilppuvuorinen** [comment]
To clarify, resources in the ```.zfs``` directory cannot and should not be modified by recycler. Volume containing only the ```.zfs``` dir is considered empty.

**Comment by markturansky** [comment]
@vilppuvuorinen we're looking to merge #6110 for our 3.1.1 release.  Your custom recycler is just around the corner ;)

**Comment by markturansky** [comment]
#6110 has been merged.  I think this issue is resolved.  a custom recycler can be made to scrub zfs volumes.

**Comment by markturansky** [comment]
This issue can be closed.  The ability to implement a recycler custom to any filesystem is merged and working.
