### ISSUE TITLE
Use terminationMessagePath to capture fatal recycler errors

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6087]
If the recycler pod fails, it is quickly deleted and no log is available. The recycle command should be able to take a path to write a termination message to, and write the final success or fatal error to that path.

**Comment by liggitt** [comment]
cc @ebalsumgo

**Comment by markturansky** [comment]
+1.  Debugging why a recycler pod fails requires looking at "docker ps -a" and finding the appropriate container for its logs.

**Comment by ebalsumgo** [comment]
yes this is currently biting me in the butt as I have two Failed PVs that I had to delete, but I have no idea as to why they failed :cry:

**Comment by markturansky** [comment]
Reassigning to @childsb
