### ISSUE TITLE
Sample-app tutorial - ruby-hello-world- build fix - RHEL 7

### ISSUE THREAD

**Issue by menren** [openshift/origin#609]
Hello,

While I am playing of openshift - ruby-hello-world tutorial, I encountered some bugs and I want to share solutions.

To be sure to avoid permission problem with Docker :
https://docs.docker.com/installation/ubuntulinux/#giving-non-root-access

After your docker-registry is on :
`openshift cli get services`

You should get :
`NAME                LABELS                                    SELECTOR            IP                  PORT`
`docker-registry     <none>                                    name=registrypod    172.30.17.50        5001`

Run you docker with this option (replace the adress by your docker-registry IP)
`--insecure-registry 172.30.17.50:5001`
You can stop docker daemon and run manually :
`sudo systemctl stop docker`
`docker -d --insecure-registry 172.30.17.50:5001 & > docker.log &`

**Comment by smarterclayton** [comment]
Ah yes, this needs to be documented.  And ideally you'd define --insecure-registry 172.0.0.0/24, because the IP of the service will be different in each run through.

@bparees we should update the README.md for the example to describe this.

**Comment by bparees** [comment]
PR here https://github.com/openshift/origin/pull/611
