### ISSUE TITLE
`oc process` does not fill in parameters given

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#6097]
```
$ oc process -f https://raw.githubusercontent.com/openshift/origin-aggregated-logging/v0.1/deployment/deployer.yaml  \
        -v PUBLIC_MASTER_URL=https://localhost:8443,KIBANA_HOSTNAME=kibana.example.com
error processing the template "logging-deployer-template": template "logging-deployer-template" is invalid: parameters: invalid value '{Name:KIBANA_HOSTNAME DisplayName: Description:External hostname where clients will reach kibana Value: Generate: From: Required:true}', Details: template.parameters[3]: parameter KIBANA_HOSTNAME is required and must be specified
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": []
}
```

If I switch the order of the parameters, then it switches to complaining about PUBLIC_MASTER_URL missing instead. It is as if parameters after the first are being dropped...

**Comment by sosiouxme** [comment]
Actually it is as if -v is no longer splitting on commas.

**Comment by sosiouxme** [comment]
I think this is related to #5746 which removed the StringList utils,which did magical splitting of strings on commas. That behavior wasn't carried over. @fabianofranz

**Comment by liggitt** [comment]
Not sure we want that behavior, actually… means you can't have a value containing a comma, right?

**Comment by liggitt** [comment]
pity that's what we document :-/
```
-v, --value='': Specify a list of key-value pairs (eg. -v FOO=BAR,BAR=FOO) to set/override parameter values
```

@fabianofranz, I don't like the comma-separated value parsing, but we may have to keep it. did you intend to drop it?

**Comment by liggitt** [comment]
and we should have at least one test for that format :-/

**Comment by sosiouxme** [comment]
I don't like comma-separated either but no idea if we want to break it to make it better.
https://trello.com/c/rbATqhY7/166-templating-alternatives-to-comma-separated-parameters is apropos

**Comment by liggitt** [comment]
Yeah, it is still generally supported. process was using the old string list slightly differently which is why the conversion broke it. Fixed in #6099

**Comment by fabianofranz** [comment]
@liggitt If it was removed by the `StringList` change, that was unintended. We have an issue to support multiple `-v` instead of commas, but I guess the commas will have to stay for some time for backwards compatibility.

**Comment by sosiouxme** [comment]
Confirming fixed, thanks.
