### ISSUE TITLE
WebUI should prompt a warning if scaling set to 0

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/origin#6098]
Basically due to lag in the UI and pods creation/deletion I managed to get myself in a situation where I wanted to have 1 pod running, but for a while had gone up to 3 and while clicking down to get back to 1 I arrived at 0 without any sort of "hey are you sure you want to set your replication to 0?" note from the system.

it seems like a good idea to have the UI warn a user if they try to go below 1 as a "just in case" scenario which is pretty easy to arrive it if say you dont read the text inside the Circle graphic of the pods but just look at the numbers (there is a substantial lag between cranking the numbers up and down, even though the central text does say what its end goal is)

cc @spadgett @jwforres, we discussed this at some length in IRC today.

**Comment by liggitt** [comment]
Yeah, the big number is what is actually running. That doesn't instantly change in response to scale events. The "lag" is actually likely in the replication controller reacting to the desired change in the rc replica count. 

Was the "scaling to X" text not noticeable enough? @jwforres/@spadgett, wonder if we can emphasize that more… I know we're space constrained, but maybe a background highlight/fade to call attention to it?

Agree that manually scaling to 0 merits a confirmation

**Comment by kargakis** [comment]
> Agree that manually scaling to 0 merits a confirmation

Maybe something we should also have in the cli - which means upstream changes?

**Comment by liggitt** [comment]
> Maybe something we should also have in the cli - which means upstream changes?

Nope :)
Typing "0, <enter>" is a lot harder to do accidentally than clicking twice instead of once. 
That would be the equivalent of hitting `<enter>` twice scaling you to 0

**Comment by ebalsumgo** [comment]
Yeah i am with @liggitt I dont think this is a CLI problem and more of a Web UI issue. it is just too easy to shoot yourself in the foot with the current up/down arrows and not noticing/reading the text (which is what I 100% did until I realized what I was doing and in my case was saved by the "lag")

**Comment by spadgett** [comment]
@liggitt or @jwforres please assign to me
