### ISSUE TITLE
Scheduler sending too many events when volume plugin is not found

### ISSUE THREAD

**Issue by gravis** [openshift/origin#6103]
Following #6070, and the discussion on the openshift-users mailing list, the scheduler will send many events when a volume plugin can't be found.

See: https://gist.github.com/gravis/6d28292afc9f51b6032a

The event `Could not recycle volume spec: Could not find recyclable volume plugin for spec: no volume plugin matched` is sent every 10s, which is probably too often.

This occurs with os 1.0.8

**Comment by childsb** [comment]
@markturansky

**Comment by markturansky** [comment]
It is every 10s only because that's what the default sync time was for the controller.

That time is now 10 minutes.

This particular error message is useful for debugging and shouldn't spam the log every 10 minutes.

**Comment by markturansky** [comment]
I checked the code and the 10m sync time did not yet get into Origin.  I will pull that upstream PR now.

**Comment by markturansky** [comment]
Linked PR increases sync time to 10m.

https://github.com/openshift/origin/pull/6157

**Comment by markturansky** [comment]
2nd PR to fix this:  https://github.com/kubernetes/kubernetes/pull/18083 (only attempt recycling once, don't spam the log)

**Comment by markturansky** [comment]
The sync period has been lengthened to 10 minutes (from 10 seconds) and will no longer spam the logs.  This is already merged into OpenShift.

This issue can be closed.
