### ISSUE TITLE
`oc env` should support `--overwrite` flag to overwrite values of specified key(s)

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#6106]
In upstream commands like oc label and oc annotate, user has to specify the --overwrite flag to redefine the value of specified key(s). We should be consistent and have the same behavior for the oc env command

**Comment by kargakis** [comment]
+1 for keeping them consistent.

**Comment by jhadvig** [comment]
Also wouldn't it make sense to have `env` cmd upstream ? 
@fabianofranz thoughts ?

**Comment by kargakis** [comment]
> Also wouldn't it make sense to have env cmd upstream ?
> @fabianofranz thoughts ?

Definitely.

**Comment by fabianofranz** [comment]
+1

**Comment by liggitt** [comment]
I like consistency, backwards compatibility on suddenly requiring --overwrite will be tough. Upstream would also need to use the common pattern of being able to apply it to origin types (bc, dc, etc)

**Comment by kargakis** [comment]
The flag is now supported
