### ISSUE TITLE
Docker secret not created/used correctly when docker-server property missing /v2 as part of url

### ISSUE THREAD

**Issue by ivanthelad** [openshift/origin#6107]
issue discovered when trying to get a openshift cluster to consume from registry in a another openshift cluster (DEV and qa-cloud)

To reproduce 
1)expose registry on DEV
Securing and exposing the DEV registry via a route. Does not need to be TLS
Implemented by following the steps outlined here to expose the DEV registry to the outside world
https://docs.openshift.com/enterprise/3.0/install_config/install/docker_registry.html#exposing-the-registry

2) Prepare Service account on DEV
Configure a Service account in DEV. This service account will be used by the QA environment. As documented here https://docs.openshift.com/enterprise/3.0/dev_guide/image_pull_secrets.html
Create a new service-account, qa-openshift-cloud, on DEV environment, for project in question
Create new secret for the service account, qa-openshift-cloud
Get the token of new secret.

3) Add secrete to "default" service account on the QA side.
Create a secret for the QA environment based on the .dockercfg file
oc secrets new-dockercfg <pull_secret_name> \  
  --docker-server=my.registry.corportate.com:80 --docker-username=<user_name> \  
  --docker-password=<password> --docker-email=<email>  
Add the secret to the default service account for your project on QA
oc secrets add serviceaccount/default secrets/pull-secret-new --for=pull

This secret resulted in the openshift not sending the the authenicated token to the DEV registry and therefor would fail.  We resolved this by add the v2 path the registry 

Adding v2 to --docker-server url fixes this 
oc secrets new-dockercfg <pull_secret_name> \  
  --docker-server=my.registry.corportate.com:80/v2 --docker-username=<user_name> \  
  --docker-password=<password> --docker-email=<email>

**Comment by liggitt** [comment]
are the two clusters using the same hostnames for the registry? can you try again, leaving out the /v2, and show the pod that failed to pull?
```
oc get pod <pod failing pull> -o json
```

and for each secret listed in the pod's imagePullSecrets list:
```
oc get secret <image pull secret> -o json
```

**Comment by liggitt** [comment]
@deads2k, anything you can think of other than path length and a conflicting hostname that could cause the dockercfg to be ignored?

**Comment by deads2k** [comment]
> @deads2k, anything you can think of other than path length and a conflicting hostname that could cause the dockercfg to be ignored?

No, one should cover the other.

**Comment by miminar** [comment]
I failed to reproduce. I can pull from secured, exposed OpenShift's registry from another cluster just fine with a secret:

    $ oc describe secret atomic-registry
    Name:           atomic-registry
    Namespace:      default
    Labels:         <none>
    Annotations:    <none>

    Type:   kubernetes.io/dockercfg

    Data
    ====
    .dockercfg:     {"atomic-registry.miminar.local":{"username":"joe","password":"sMD_5k2rH8_9dHsSLd6jmOh8XfvmsEM0bJLZoOivxxM","email":"any@email.addr","auth":"am9lOnNNRF81azJySDhfOWRIc1NMZDZqbU9oOFhmdm1zRU0wYkpMWm9PaXZ4eE0="}}

If I copy the json followin the `.dockercfg:` to `~/.docker/config.json` under `"auths"`, I can pull with `docker pull atomic-registry.miminar.local/joe1/image` also just fine. However, if I add `/v2` suffix, I can pull manually with Docker, but not from the second OpenShift cluster.

Could you please provide some relevant logs from the registry pod around the time the pull fails?

**Comment by liggitt** [comment]
@smarterclayton did your dockercfg keychain path munging fix this?

**Comment by smarterclayton** [comment]
I think so.

**Comment by bparees** [comment]
let's assume yes. closing.
