### ISSUE TITLE
DNS error when deploy app

### ISSUE THREAD

**Issue by pstinghua** [openshift/origin#6108]
we use windows dns server, the dns server is 193.0.0.1.

origin.sj.net -> 193.0.10.169

```
F1127 05:26:16.156052       1 deployer.go:65] couldn't get deployment default/gitlab-ce-1: Get https://origin.sj.net:8443/api/v1/namespaces/default/replicationcontrollers/gitlab-ce-1: dial tcp 60.191.124.236:8443: i/o timeout
```

**Comment by pstinghua** [comment]
could not reach internal dns

**Comment by wjiangjay** [comment]
Actually this not the DNS issue, 
the error is "tcp 60.191.124.236:8443: i/o timeout"

So 
1. you must ensure the mapping of origin.sj.net<--> 60.191.124.236 is correct
2. you must ensure the firewall does not prevent the package about 8443 port if dns mapping is correct

**Comment by danmcp** [comment]
Please reopen if you believe this is still an issue.
