### ISSUE TITLE
oc rsync requires you to log in, global options --token= --server= --user= seem to have no effect

### ISSUE THREAD

**Issue by adietish** [openshift/origin#6109]
The oc cmds that we're using so far can be fully configured (--server= --token= --user=) so that the login context that you're in ("oc login") doesnt matter. We currently port forward and stream logs in this way so that oc run within Eclipse wont affect the cmd-line and the inverse.
This isnt the case for "oc rsync" though. It will accept these (global) options but seems unaffected by them. "oc rsync" requires you to log in to some context before it'll work. If logged in the options seem not to have any effect.

**Comment by liggitt** [comment]
@csrwng
