### ISSUE TITLE
`oadm ca` should be able to generate a combined client and server cert

### ISSUE THREAD

**Issue by detiber** [openshift/origin#6114]
Currently we are having to manage a separate CA using openssl for etcd certs since etcd peer certs are required to be both client and server certs.

To avoid having to manage cert management with openssl in openshift-ansible only for the peer certs, it would be nice to generate all of the needed certs for deployment using `oadm ca`

**Comment by detiber** [comment]
cc @liggitt @abutcher

**Comment by detiber** [comment]
@timothysc @liggitt what are the chances of getting the oadm ca stuff upstream?  The upstream contrib/ansible stuff could benefit from it rather than using easyrsa3.

**Comment by timothysc** [comment]
@detiber Do you have the context for the whole change?  Rob was talking to me about the issue but he has more context then I do on the topic. 

/cc @eparis

**Comment by liggitt** [comment]
I wouldn't expect this command to go into the core repo upstream... too specialized. If this was actually going to be a general purpose tool, I'd decompose it into something like:

```
create-key-pair --public-key=... --private-key=...
create-csr --private-key=... --subject=... --subjectAltNames=...,...,...
sign-csr --csr=... --usage=[client,server,...] --valid-from=[now] --valid-for=[duration]
```

**Comment by eparis** [comment]
isn't @liggitt basically describing easyrsa ?

**Comment by liggitt** [comment]
Probably so

**Comment by detiber** [comment]
Yes, like easyrsa3, but instead of a tool that is pulled from a URL (and doesn't support combined server/client certs without a bit of hacking) this would be a tool more closely integrated with kube.

I think a closely integrated tool could allow us to more easily make managing cert lifecycle within a cluster, possibly even going as far as integrated csr generation by nodes which can then be signed and issued by a controller as part of the node registration and admission process.

That said, if there is no desire for managing cert tooling upstream, we could switch to using https://github.com/cloudflare/cfssl/ which is Go based and could more easily be integrated. Cfssl also happens to be the cert tooling recommended for etcd nowadays as well.

Whichever way we go, I'd like to have a standardized way to manage certificates for both Kube and OpenShift that can generate he certs we need for the entire cluster deployment for both test purposes as well as production purposes. It'd also be preferable to not have to hack the tooling to accomplish this and have it integrated or packaged so that we could use it for production OpenShift deployments.

**Comment by rrati** [comment]
I just went through the cert generation bit and cfssl bits recommended by etcd won't work on fedora, rhel, or centos because the tooling uses some libraries that have been removed from go for licensing concerns.  I took a quick stab at trying to comment out the deps, but wasn't successful at making cfssl work.  There are a number of bug reports about it upstream, but so far no solution other than to d/l stock go and use that.

**Comment by detiber** [comment]
@rrati that puts the nail in the coffin for cfssl.  We could still petition for the client-server patch to easyrsa3 and getting it packaged.

That said, easyrsa3 wouldn't be something that would work good as a solution that could be integrated into the node registration process.
