### ISSUE TITLE
couldn't access resources from cli

### ISSUE THREAD

**Issue by bilalyasar** [openshift/origin#6116]
I want to login open shift as cluster-admin, but couldn't succeed.

```
[ec2-user@ip-172-30-0-47 ~]$  oc login -u system:admin -n default --config=/home/ec2-user/openshift.local.config/master/admin.kubeconfig 
You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default (current)
  * deneme
  * openshift
  * openshift-infra
  * test

Using project "default".
[ec2-user@ip-172-30-0-47 ~]$ oc describe policyBindings :default
Error from server: User "system" cannot get policybindings in project "default"
```

i want to run this command:
`oc describe clusterPolicy default`

But couldn't login as cluster-admin, how can i login as cluster-admin?

**Comment by liggitt** [comment]
The first command pointed at a config file containing cluster admin credentials. The second command needs to point to the same config file (or the KUBECONFIG envvar should be pointed to that file, or that file should be copied to ~/.kube/config)

**Comment by bilalyasar** [comment]
thanks.

**Comment by bilalyasar** [comment]
@liggitt, now i create a pod.
Then i attach inside the docker container.

i want to use kube api:
` KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)`
`curl -sSk -H "Authorization: Bearer $KUBE_TOKEN"       https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces`

this gives me:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:serviceaccount:hz:default\" cannot list all namespaces in the cluster",
  "reason": "Forbidden",
  "details": {
    "kind": "namespaces"
  },
  "code": 403
}
```

How can i fix?

**Comment by liggitt** [comment]
Give that pod's service account that permission:
```
oadm policy add-cluster-role-to-user cluster-reader system:serviceaccount:hz:default
```

**Comment by bilalyasar** [comment]
@liggitt , thanks.

another question:
in docker, our application bind an interface which is not related with aws private address. So i want to bind ec2-private address without changing my code. Can i override docker start parameters like `net=host`?
