### ISSUE TITLE
new-app and new-build should only import the selected image

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6118]
Today we import the entire docker image repository when referenced, which for very large repos sucks.  We should selectively import it.

WARNING: Old servers don't selective import, so somehow the client needs to do something different when talking to 1.1 vs 1.0

**Comment by bparees** [comment]
@smarterclayton is this a proposed change to new-app/new-build (they should change how they define the ImageStreams they create) or  a change to the server side of how importing is done when an ImageStream is defined?

(or both...server side primarily, but client side to handle 1.0 servers that don't have the server side logic)?

**Comment by smarterclayton** [comment]
Client side only I think - client for newer servers needs to be able to set
spec.tag DockerImage, vs 1.0 which only allows spec.dockerImageRepository.
I don't know how to check though without a feature flag.

On Dec 1, 2015, at 11:02 AM, Ben Parees <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> is this a proposed
change to new-app/new-build (they should change how they define the
ImageStreams they create) or a change to the server side of how importing
is done when an ImageStream is defined?

(or both...server side primarily, but client side to handle 1.0 servers
that don't have the server side logic)?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/6118#issuecomment-161013549>.

**Comment by bparees** [comment]
we have a precedent with ConfigChangeTrigger where we try one thing and if it gets a validation error, we revert to the older behavior.

**Comment by smarterclayton** [comment]
We won't get a validation error - just nothing will happen.

On Dec 1, 2015, at 11:19 AM, Ben Parees <notifications@github.com> wrote:

we have a precedent with ConfigChangeTrigger where we try one thing and if
it gets a validation error, we revert to the older behavior.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/6118#issuecomment-161019240>.

**Comment by soltysh** [comment]
Instead of introducing feature flag we could check server version and act appropriately.

**Comment by bparees** [comment]
> Instead of introducing feature flag we could check server version and act appropriately. 

do we have a way to get that info now?  I thought we've hit this before and there's now way for a client to find out the server version.

**Comment by smarterclayton** [comment]
We don't do that, see other discussions on that topic.  Version numbers
don't work for lots of reasons.

On Dec 2, 2015, at 10:37 AM, Maciej Szulik <notifications@github.com> wrote:

Instead of introducing feature flag we could check server version and act
appropriately.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/6118#issuecomment-161336834>.

**Comment by bparees** [comment]
> I don't know how to check though without a feature flag.

what do you mean by a feature flag?  you mean that new-app needs to take an arg from the user that tells it what to do?  that's not really checking, that's just depending on the user to understand a subtle nuance of the server they are talking to.

presumably we'd default to the new syntax/definition, and provide a flag to fall back to the v1.0 syntax ("--import-all=true")

**Comment by smarterclayton** [comment]
Feature flag is something the API provides to say "I support this".  The
client negotiates versions with the server and also retrieves the flags.
Client code uses the flag to make decisions about what types of API objects
to send.

**Comment by smarterclayton** [comment]
This is now fixed with image import for new-app, new-build, and import-image.  Only the selected tag will be imported.
