### ISSUE TITLE
STIStrategy should require Image field

### ISSUE THREAD

**Issue by bparees** [openshift/origin#612]
currently the Image field on STIStrategy is optional, but there is no meaningful default for an STI build, so this should be a mandatory field with all appropriate validation.

https://github.com/openshift/origin/blob/master/pkg/build/api/v1beta1/types.go#L131
https://github.com/openshift/origin/blob/master/pkg/build/api/validation/validation.go#L96

**Comment by csrwng** [comment]
The Image field is required when STIStrategy is present, which is what I think we want
https://github.com/openshift/origin/blob/master/pkg/build/api/validation/validation.go#L119
The STIStrategy field in BuildStrategy needs to remain optional for the case when your strategy is not STIStrategy (https://github.com/openshift/origin/blob/master/pkg/build/api/v1beta1/types.go#L131)

**Comment by bparees** [comment]
hm, what i meant to link was this:
https://github.com/openshift/origin/blob/master/pkg/build/api/v1beta1/types.go#L187

you're right, i looked at the wrong validation logic, but shouldn't we remove "omitempty" from the json metadata for the field, since it can't be empty?

**Comment by csrwng** [comment]
Yup, we should

**Comment by soltysh** [comment]
We can't remove that `omitempty` from [v1beta1](https://github.com/openshift/origin/blob/master/pkg/build/api/v1beta1/types.go#L187), because the `Image` field was introduced after `v1beta1` was freezed. That can be done only in `v1beta2` where `BuilderImage` will be removed, still it does make sense to remove that in [internal structure](https://github.com/openshift/origin/blob/master/pkg/build/api/types.go#L183).

**Comment by bparees** [comment]
@soltysh it may be bending the rules a bit, but I wonder if we can remove it...because the fact is today if you create a config json with that value empty, it's going to fail anyway (ie the build won't work...and validation will fail) so i don't an huge issue w/ changing this in the api.  It won't break anyone who's not already broken.  Adding @smarterclayton for his opinion.

**Comment by smarterclayton** [comment]
Probably can't remove omitempty without an api version.  We shouldn't cheat.

**Comment by bparees** [comment]
blah.  fine, let's do it in v2.

**Comment by bparees** [comment]
image field is gone as of v1beta3.
