### ISSUE TITLE
Firefox 38 websocket problems

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6125]
User report from @jim-minter:

> I'm finding it takes about 50 seconds for the logs and terminal windows to render content for the first time when using Firefox 38.4.0 (RHEL 7 latest) on RHEL 7.
>
> This isn't a delay while the pod image is being pulled or anything, and it's completely reproducible by navigating away and returning.
>
> Opening the debugging window, it shows a long delay before the WSS connections are opened.  There are also various of the following types of errors shown (don't know if they're a red herring or not):
>
> Firefox can't establish a connection to the server at wss://openshift.example.com:8443/oapi/v1/namespaces/demo/buildconfigs?watch=true&resourceVersion=4781&access_token=.... scripts.js:163:0
>
> The connection to wss://openshift.example.com:8443/oapi/v1/namespaces/demo/buildconfigs?watch=true&resourceVersion=4781&access_token=... was interrupted while the page was loading. scripts.js:163:0
> 
> Where it says 'buildconfigs' above, I've seen errors for pretty much every OpenShift type - pods, routes, imagestreams, whatever.
>
> On Chrome on Fedora things work fine.  Interestingly with Firefox 42.0 on Fedora, things work fine, but I still get a few (fewer) messages like the above ones.
>
>  I think this is happening with most or all websockets requests, so on a RHEL 7 client the web interface generally doesn't appear to be updating at all in response to WATCH events.
>
> No proxies.

From another user:
> I may not be on any help, but I can replicate this problem on RHEL CSB7,
Firefox 38.4
> On the same Computer it works fine on Chrome Version 45.0.2454.85 (64-bit)

cc @jwforres

**Comment by jwforres** [comment]
Firefox 39 is also affected.  Was able to reproduce it on firefox 38/39 on windows 8.1 and OSX Yosemite as well.  The issue doesn't exist in Firefox 40+   It seems to only occur when navigating from one of our pages that had a lot of websockets open to another page.  The new websocket requests definitely get issued from the JS, we get back the websocket object, but the requests do not show up in the network tab, after some time all the queued requests flood through.  Still digging...

**Comment by liggitt** [comment]
Might be one of these changes in ff40:
https://bugzilla.mozilla.org/show_bug.cgi?id=1170645
https://bugzilla.mozilla.org/show_bug.cgi?id=1147990

**Comment by liggitt** [comment]
Looks like the API server isn't sending correct close notifications when closing web socket watches. Not sure if this affects firefox or not for client-initiated closes.

Possible fix in https://github.com/openshift/origin/pull/6261/files

**Comment by jwforres** [comment]
I can't reproduce the issue anymore while running with @liggitt's fix to the API server.

**Comment by jim-minter** [comment]
neither can I -- thanks @jwforres and @liggitt  :-)
