### ISSUE TITLE
UI should prompt if io.openshift.non-scalable

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6134]
We should disable the scaling controls or at least warn when the non-scalable label is set.

https://docs.openshift.org/latest/creating_images/metadata.html

**Comment by spadgett** [comment]
@jwforres please assign to me

**Comment by liggitt** [comment]
Does the UI have access to the label on the image?

**Comment by smarterclayton** [comment]
This is questionable - as in, it's not correct to disable scaling unless it's an annotation on the rc or DC itself, and even at that it is a suggestion at best.

**Comment by spadgett** [comment]
@smarterclayton Does it make sense then to add it as an annotation to the RC or DC for images with the label? I have a prompt already for scaling to 0 (#6098) that we could reuse. It feels weird that we put the arrows beside databases when you're just going to get yourself in trouble clicking them.

**Comment by spadgett** [comment]
> Does the UI have access to the label on the image?

It looks like it, but it's a bit of work to get.

**Comment by smarterclayton** [comment]
I would say someone who wants this should add the annotation to their DC
themselves - we could maybe carry it over in new-app, but that's a second
step.  I don't really want to fully lock out scaling though like that -
it's gotta be "this DC/RC has scale protection enabled - are you really
sure you want to scale up or down?"

**Comment by smarterclayton** [comment]
And maybe we gray out the scalers so they are harder to see.

**Comment by spadgett** [comment]
> I don't really want to fully lock out scaling though like that - it's gotta be "this DC/RC has scale protection enabled - are you really sure you want to scale up or down?"

Sure, not against making it a prompt.

> And maybe we gray out the scalers so they are harder to see.

We use a lighter gray when the control is truly disabled (for instance, the down arrow when already at 0).

**Comment by sferich888** [comment]
@spadgett do we have any idea when we might see this in Enterprise?

**Comment by spadgett** [comment]
Closing as this is tracked in Bugzilla.

https://bugzilla.redhat.com/show_bug.cgi?id=1284104
