### ISSUE TITLE
Output from `oc new-build -o json` should contain JSON only

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6136]
The alternative output formats to `oc new-app` and `oc new-build` should not print the descriptive information to stdout. With the extra output, one cannot redirect the output to a file and use it later without having to manually edit it.

Example:

```
$ oc new-build -D 'FROM centos:7' -o yaml > build.yaml
$ head build.yaml 
--> Found Docker image 0e23418 (6 weeks old) from Docker Hub for "centos:7"
    * An image stream will be created as "centos:7" that will track this image
    * A Docker build using a predefined Dockerfile will be created
      * The resulting image will be pushed to image stream "centos:latest"
      * Every time "centos:7" changes a new build will be triggered
apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
```

**Comment by rhcarvalho** [comment]
@bparees please assign this to me if you agree the behavior should be fixed.

**Comment by smarterclayton** [comment]
This should be fixed - we have dry-run messages  if the user wants to see messages.  This is high priority for 1.1.1
