### ISSUE TITLE
support passing secrets to oc new-app. 

### ISSUE THREAD

**Issue by ivanthelad** [openshift/origin#6140]
oc new-app is a great way to get a new-application /docker image up and running within seconds. It is unfortunately not usable when the target git repo is secured(involves point to a demo app and editing build configs instead). It should be possible to pass a secret to oc new-app to allow generation of a new application against a secured git repo
oc new-app $gitrepo --secret=mysecret --name=temp

**Comment by bparees** [comment]
covered in trello: 
https://trello.com/c/gXIlR9SH/765-oc-new-app-to-gather-git-creds
