### ISSUE TITLE
oc rsync should offer exclusion patterns

### ISSUE THREAD

**Issue by adietish** [openshift/origin#6143]
when using "oc rsync" to sync a directories we should be able to provide exclusion patterns. Typically if we're syncing code there's a .git folder in it that we dont want to sync to the server since it's useless and quite large, slowing down the turnaround

**Comment by fbricon** [comment]
Can we bump the priority for that item? It's required for our JBoss Tools integration.

**Comment by maxandersen** [comment]
We really need this to get more fine grained control over the copying and deletion - otherwise command line tools nor IDE tooling cannot reliably nor efficiently keep the local and remote systems in sync.

**Comment by csrwng** [comment]
I will work on putting together a PR for this today

**Comment by maxandersen** [comment]
I'm wondering if we should expose both include and exclude options ? then a tool or user can dependent on his project needs choose if easier for him to use either or ?

**Comment by adietish** [comment]
I'd argue that non-trivial sync usecases require a combination of inclusion and exclusion patterns. We should thus strive for both

**Comment by csrwng** [comment]
The approach that I'm taking is the one mentioned here #6115 - basically we'll allow you to pass a set of white-listed flags to the rsync command. I started working on this yesterday and hopefully will have a PR shortly.

**Comment by adietish** [comment]
@csrwng do you have any rough idea when this will be finished? We're getting closer Beta2, would appreciate a lot if we could count on this feature.

**Comment by csrwng** [comment]
@adietish I would expect soon... I submitted a new set of changes based on the approach agreed on in the PR discussion. They are pending review.

**Comment by adietish** [comment]
ok, cool. Looking forward to it :)
