### ISSUE TITLE
LDAP sync needs to re-use LDAP connections

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6144]
Currently we throw them away every time we run a query.

@liggitt @deads2k

**Comment by deads2k** [comment]
The proper fix to this would be a thread-safe connection pool at the ldap library level.  That's more work than I think we should do right now.

Improper fixes....  Try to not to make it ugly.  We have a cache for particular queries already right?   Like users.  We do bulk queries for most work.

I think I'm inclined to say that sync jobs can take a long time.

**Comment by stevekuznetsov** [comment]
We do our best to cache as much as we can. Even in the RFC2307 schema, where technically we *would* use one connection per group, in normal operation we *always* list groups first, and this brings all of the entries into our cache. I'd like to figure out how many connections we make in a run - how do we do this? What tool do I use?

**Comment by liggitt** [comment]
println inside the connection creation function? sync N groups with M members and see what happens?

**Comment by stevekuznetsov** [comment]
Some interesting results. [This line](https://github.com/openshift/origin/blob/master/pkg/auth/ldaputil/query.go#L191) is the one and only place we make connections to LDAP. Here are the amount of connections made, broken down by schema and where they occur - before any groups are marked as added or between groups being marked as added.

|                                                                                                                                                           | RFC2307 |                | AD      |                | Augmented AD |                | 
| --------------------------------------------------------------------------------------------------------------------------- | ------------ | ----------- | -------- | ----------- | -------------------  | ----------- |
| Test Name                                                                                                                                          | Before     | Between | Before | Between | Before               | Between |
| Sync all LDAP groups from LDAP server                                                                                           | 8              | 2             | 2         | 2             | 3                       | 4             |
| Sync subset of LDAP groups from LDAP server using whitelist file                                                    | 7              | 0            | 1         | 0              | 2                       | 0             |
| Sync subset of LDAP groups from LDAP server using literal whitelist                                                | 7              | 0            | 1         | 0              | 2                       | 0             |
| Sync subset of LDAP groups from LDAP server using union of literal whitelist and whitelist file        | 5              | 4            | 1         | 1              | 2                       | 2             |
| Sync subset of OpenShift groups from LDAP server using whitelist file                                             | 7              | 6            | 1         | 1              | 2                       | 1             |
| Sync subset of OpenShift groups from LDAP server using literal whitelist                                         | 7              | 6            | 1         | 1              | 2                       | 1             |
| Sync subset of OpenShift groups from LDAP server using union of literal whitelist and whitelist file | 7              | 9            | 1         | 3              | 2                       | 4             |
| Sync subset of LDAP groups from LDAP server using whitelist and blacklist file                               | 5              | 0            | 1         | 0              | 2                       | 0             |
| Sync subset of LDAP groups from LDAP server using blacklist                                                         | 6              | 0            | 2         | 0              | 3                       | 0             |
| Sync subset of OpenShift groups from LDAP server using whitelist and blacklist file                        | 8              | 8            | 2         | 3              | 3                       | 5             |
| Sync all LDAP groups from LDAP server using a user-defined mapping                                          | 7              | 2            | 2         | 2              | 2                       | 2             |
| Sync all LDAP groups from LDAP server using a partially user-defined mapping                             | 7              | 3             | 2         | 2             | 2                       | 3             |
| Sync based on OpenShift groups respecting OpenShift mappings                                                   | 7              | 10           | 2         | 5             | 2                       | 5             |
| Sync all LDAP groups from LDAP server using DN as attribute whenever possible                          | 8              | 4             | 2         | 2             | 3                       | 4             |

We seem to do a lot of set-up queries for RFC2307 schema syncs - that's not what I would have expected. The queries for the other schemas seem reasonable. For RFC2307, at least, this is pretty bad. What do we do? We do our best to cache, and I will continue looking into why RFC2307 doesn't seem to be caching as well as it should, but do we improve caching logic on our end, then work toward a fix at the `go-ldap` level?

**Comment by stevekuznetsov** [comment]
Here's a sample output to see what I mean re: before v. between:
```
[INFO] Running extended tests
[INFO] Testing schema: rfc2307
No resources found
	TEST: Sync all LDAP groups from LDAP server
CONNECTION CREATED
CONNECTION CREATED
CONNECTION CREATED
CONNECTION CREATED
CONNECTION CREATED
CONNECTION CREATED
CONNECTION CREATED
CONNECTION CREATED
group/group1
CONNECTION CREATED
CONNECTION CREATED
group/group2
CONNECTION CREATED
CONNECTION CREATED
group/group3
group "group1" deleted
group "group2" deleted
group "group3" deleted
	SUCCESS
```

**Comment by liggitt** [comment]
Not sure what you would expect go-ldap to do… they give us a connection, but we're not reusing it.

**Comment by stevekuznetsov** [comment]
I was referencing David's comment: 
> The proper fix to this would be a thread-safe connection pool at the ldap library level.

**Comment by deads2k** [comment]
> but do we improve caching logic on our end, then work toward a fix at the go-ldap level?

At some level, you need a `GetConnection` method that looks at a pool, sees which ones match your requirement, then chooses an existing one, or creates a new one for you.  It would sit above the current go-ldap implementation, but it would be useful addition.

It's also enough work that I don't see us doing that.

**Comment by stevekuznetsov** [comment]
We seem to have some serious issues with caching:
```
[INFO] Testing schema: rfc2307
No resources found
	TEST: Sync all LDAP groups from LDAP server
RFC2307: query for all group entries
RFC2307: query for single group entry "cn=group1,ou=groups,ou=rfc2307,dc=example,dc=com"
RFC2307: query for single user entry "cn=Person1,ou=people,ou=rfc2307,dc=example,dc=com"
RFC2307: query for single user entry "cn=Person2,ou=people,ou=rfc2307,dc=example,dc=com"
RFC2307: query for single user entry "cn=Person3,ou=people,ou=rfc2307,dc=example,dc=com"
RFC2307: query for single user entry "cn=Person4,ou=people,ou=rfc2307,dc=example,dc=com"
RFC2307: query for single user entry "cn=Person5,ou=people,ou=rfc2307,dc=example,dc=com"
RFC2307: query for single group entry "cn=group1,ou=groups,ou=rfc2307,dc=example,dc=com"
group/group1
RFC2307: query for single group entry "cn=group2,ou=groups,ou=rfc2307,dc=example,dc=com"
RFC2307: query for single group entry "cn=group2,ou=groups,ou=rfc2307,dc=example,dc=com"
group/group2
RFC2307: query for single group entry "cn=group3,ou=groups,ou=rfc2307,dc=example,dc=com"
RFC2307: query for single group entry "cn=group3,ou=groups,ou=rfc2307,dc=example,dc=com"
group/group3
group "group1" deleted
group "group2" deleted
group "group3" deleted
	SUCCESS
```

@deads2k my bandwidth is very limited for the next two weeks - if this is urgent, I think you may have to do it.

**Comment by liggitt** [comment]
I think p2 is appropriate... can wait until you have time

**Comment by stevekuznetsov** [comment]
Once I have this bug fixed, RFC2307 and Augmented AD will issue two requests to the server, and, under our current factoring, make two connections. AD will issue one request and make one connection.

Should I refactor to re-use the connection, or are two connections fine for sync? Do we at any point the future want to implement the connection pool either here or upstream?

**Comment by deads2k** [comment]
> Should I refactor to re-use the connection, or are two connections fine for sync? Do we at any point the future want to implement the connection pool either here or upstream?

Two connections are fine for sync.  I wouldn't worry about this further until we have an actual problem.

**Comment by liggitt** [comment]
agree
