### ISSUE TITLE
Images built from source should have the commit id as part of a tag

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#615]
When building images from source in Docker V2 registry, some element of the input should be reflected in the final image manifest (in a way that mutates the image manifest signature).  Ideally in a way that preserves idempotent builds (naively).

**Comment by smarterclayton** [comment]
@bparees where are we on this?

**Comment by bparees** [comment]
commit id should be showing up as a label in images built by us:
https://github.com/openshift/source-to-image/pull/255/files
https://github.com/openshift/origin/pull/4079/files

that should be sufficient to mutate the id, right?

```
"Labels": {
            "io.k8s.description": "Platform for building and running Ruby 2.0 ap
plications",
            "io.k8s.display-name": "172.30.77.77:5000/test/origin-ruby-sample:la
test",
            "io.openshift.build.commit.author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",
            "io.openshift.build.commit.date": "Wed Jul 29 14:28:21 2015 +0200",
            "io.openshift.build.commit.id": "65b3d6b",
            "io.openshift.build.commit.message": "Merge pull request #47 from voxik/patch-1",
            "io.openshift.build.commit.ref": "master",
            "io.openshift.build.image": "openshift/ruby-20-centos7@sha256:a94f8f5fad576b170023261c2e3112d8671437fc8a6ec63d2bfb3a5f6386de60",
            "io.openshift.build.source-location": "https://github.com/openshift/ruby-hello-world.git",
            "io.openshift.builder-base-version": "c7358a4",
            "io.openshift.builder-version": "a085e45",
            "io.openshift.expose-services": "8080:http",
            "io.openshift.s2i.scripts-url": "image:///usr/local/sti",
            "io.openshift.tags": "builder,ruby,ruby20",
            "io.s2i.scripts-url": "image:///usr/local/sti"
        },
```

**Comment by smarterclayton** [comment]
Yup that's enough.  Thanks.

Although... we should probably be using the full commit hash, not the short
one.  Can we get that changed?

On Sep 1, 2015, at 9:10 PM, Ben Parees <notifications@github.com> wrote:

commit id should be showing up as a label in images built by us:
https://github.com/openshift/source-to-image/pull/255/files
https://github.com/openshift/origin/pull/4079/files

that should be sufficient to mutate the id, right?

"Labels": {
            "io.k8s.description": "Platform for building and running Ruby 2.0 ap
plications",
            "io.k8s.display-name": "172.30.77.77:5000/test/origin-ruby-sample:la
test",
            "io.openshift.build.commit.author": "Jakub Hadvig
\u003cjhadvig@redhat.com\u003e",
            "io.openshift.build.commit.date": "Wed Jul 29 14:28:21 2015 +0200",
            "io.openshift.build.commit.id": "65b3d6b",
            "io.openshift.build.commit.message": "Merge pull request
#47 from voxik/patch-1",
            "io.openshift.build.commit.ref": "master",
            "io.openshift.build.image":
"openshift/ruby-20-centos7@sha256:a94f8f5fad576b170023261c2e3112d8671437fc8a6ec63d2bfb3a5f6386de60",
            "io.openshift.build.source-location":
"https://github.com/openshift/ruby-hello-world.git",
            "io.openshift.builder-base-version": "c7358a4",
            "io.openshift.builder-version": "a085e45",
            "io.openshift.expose-services": "8080:http",
            "io.openshift.s2i.scripts-url": "image:///usr/local/sti",
            "io.openshift.tags": "builder,ruby,ruby20",
            "io.s2i.scripts-url": "image:///usr/local/sti"
        },

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/615#issuecomment-136907520>.

**Comment by bparees** [comment]
> Although... we should probably be using the full commit hash, not the short one. Can we get that changed? 

@jhadvig can you take care of that and then we'll resolve this issue.

**Comment by bparees** [comment]
@jhadvig bump (low hanging fruit)

**Comment by jhadvig** [comment]
@bparees please we can close this one, since its fixed in s2i. We only need to update s2i in origin.

**Comment by bparees** [comment]
@jhadvig we can close this when the bump is done....
