### ISSUE TITLE
Tooltips can't be dismissed in mobile Safari

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6153]
When I press on a tooltip link in the web console create form, I can't dismiss the tooltip, and it covers form fields. Pressing elsewhere on the page or on the link again doesn't hide the tooltip. The only workaround I've found is press another link or button.

/cc @jwforres

**Comment by spadgett** [comment]
This is a known Boostrap issue.

**Comment by spadgett** [comment]
https://developer.mozilla.org/en-US/docs/Web/Events/click#Safari_Mobile

**Comment by jwforres** [comment]
Pretty sure we worked around this in v2 by doing this (making use of
touchstart event):
https://github.com/openshift/origin-server/blob/master/admin-console/app/views/admin_console/index/_welcome.html.haml#L62

**Comment by spadgett** [comment]
`touchstart` on the `body` element doesn't always fire in my testing. I'm guessing something is stopping event propagation.

How do you feel about this fix? It's a bit hacky, but seems to work well.

```
    // Workaround for tooltips and popovers not closing when the screen is
    // touched elsewhere. Specifically target iOS to avoid changing the cursor
    // on other devices like touch-enabled laptops.
    if (navigator.userAgent.match(/(iphone|ipad)/i)) {
      $('body').css('cursor', 'pointer');
    }
```

**Comment by liggitt** [comment]
?

**Comment by spadgett** [comment]
@liggitt See my link above for why it works

https://developer.mozilla.org/en-US/docs/Web/Events/click#Safari_Mobile

Not sure it's the best fix...

**Comment by jwforres** [comment]
@spadgett i prefer the version in this comment where the hack CSS is only added while the popup is visible https://github.com/twbs/bootstrap/issues/16028#issuecomment-236269114
