### ISSUE TITLE
build cancel test should be in e2e

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6154]
@jhadvig The `cancel-build` test found [here](https://github.com/openshift/origin/blob/master/test/cmd/builds.sh#L105-L110) requires that the node is running. In `test-cmd` we only start the master, not all-in-one. You should migrate this test to e2e and ensure it's working as expected there.

**Comment by deads2k** [comment]
There's actually an extended `test-cmd` for tests that require a node.

**Comment by kargakis** [comment]
@bparees still an issue?

**Comment by bparees** [comment]
doesn't seem like it.  not sure why the assertion was that the test requires a node since it seems to be passing w/o one.

in any case we have other cancel tests in e2e.
