### ISSUE TITLE
Unable to delete the replication controller objects

### ISSUE THREAD

**Issue by abhat** [openshift/origin#6156]
With the latest origin code, deletion of the replication controller objects created when deploying the ruby-hello-world sample app results in a timeout error:

```
[root@os-master ~]# oc delete all -l handle=my_app
buildconfig "ruby-sample-build" deleted
build "ruby-sample-build-1" deleted
imagestream "origin-ruby-sample" deleted
imagestream "ruby-22-centos7" deleted
I1201 17:10:04.467253    9282 reaper.go:67] Cannot delete ReplicationController test-project/database-1: timed out waiting for the condition
```

Origin commit hash:

commit e592c187437c64a7d118502917ad557d2bc806e7
Merge: 31888bc fb7f2e6
Author: OpenShift Bot <dmcphers+openshiftbot@redhat.com>
Date:   Tue Dec 1 10:30:21 2015 -0500

**Comment by ncdc** [comment]
I just tested with

```
oc v1.1-299-g415140e-dirty
kubernetes v1.1.0-origin-1107-g4c8e6f4
```

and could not reproduce. Could you try a few times and let me know if it happens again? If it does, having logs would be helpful. Thanks!

**Comment by kargakis** [comment]
The rc scaler tries [indefinitely](https://github.com/kubernetes/kubernetes/blob/e82277b86a15e4c259523f09e6947dd259f40834/pkg/kubectl/scale.go#L147-L149) to update the rc in case of update failures, maybe related.

@abhat what was the state and the size of test-project/database-1 prior to deletion?

**Comment by abhat** [comment]
Was able to delete the rcs after upgrading to: 
commit b6b40195542786eacc4
Merge: 4640d30 5493057
