### ISSUE TITLE
"Unable to delete old node" when using openstack provider

### ISSUE THREAD

**Issue by loshkovskyi** [openshift/origin#6159]
Hello,

I configured OpenShift to access my OpenStack infrastructure using the following guide: https://docs.openshift.org/latest/install_config/configuring_openstack.html

When I restart `origin-master` and `origin-node` as to the guide, all nodes are becoming `NotReady`:
```
oc version
oc v1.1
kubernetes v1.1.0-origin-1107-g4c8e6f4

oc get no
NAME                          LABELS                                                         STATUS                        AGE
vm-master-01.openshift.demo   kubernetes.io/hostname=10.30.5.4,region=primary,zone=default   NotReady,SchedulingDisabled   1d
vm-node-01.openshift.demo     kubernetes.io/hostname=10.30.5.5,region=primary,zone=default   NotReady                      1d
vm-node-02.openshift.demo     kubernetes.io/hostname=10.30.5.3,region=primary,zone=default   NotReady                      1d

oc describe no vm-node-01.openshift.demo
Name:			vm-node-01.openshift.demo
Labels:			kubernetes.io/hostname=10.30.5.5,region=primary,zone=default
Conditions:
  Type		Status		LastHeartbeatTime			LastTransitionTime			Reason			Message
  ────		──────		─────────────────			──────────────────			──────			───────
  Ready 	Unknown 	Wed, 02 Dec 2015 09:51:59 +0000 	Wed, 02 Dec 2015 09:52:44 +0000 	NodeStatusUnknown 	Kubelet stopped posting node status.
```
From the logs:
```
kubelet.go:2405] Recording NodeReady event message for node vm-node-01.openshift.demo
kubelet.go:928] Attempting to register node vm-node-01.openshift.demo
kubelet.go:951] Previously "vm-node-01.openshift.demo" had externalID "0d4d2c8d-5a58-484e-aa0f-d183f35a05d7"; now it is "10.30.5.5"; will delete and recreate.
kubelet.go:953] Unable to delete old node: User "system:node:vm-node-01.openshift.demo" cannot delete nodes at the cluster scope.
```
I'm trying to understand if the last line in the log: `Unable to delete old node` has something to do with nodes status.

Here is a part of my `/etc/origin/node/node-config.yaml`:
```
kind: NodeConfig
kubeletArguments:
  cloud-provider:
    - "openstack"
  cloud-config:
    - "/etc/cloud.conf"
masterKubeConfig: system:node:vm-master-01.openshift.demo.kubeconfig
```
Checking policies:
```
oadm policy who-can delete node
Namespace: default
Verb:      delete
Resource:  node

Users:  none

Groups: system:cluster-admins
        system:masters
```

When I check cluster policy with `oc describe clusterPolicy default`, I see that the user `system:node` can only `[create get list watch]` but not delete nodes.

Please advise if I need to adjust my cluster policies or it's indeed a bug.

**Comment by liggitt** [comment]
related to https://github.com/kubernetes/kubernetes/issues/17731

**Comment by liggitt** [comment]
A possible resolution is to delete the nodes as the cluster admin, and restart the nodes, letting them re-register themselves. There is debate about whether a node should have the ability to delete itself, or whether it should be able to update this ID in place.

**Comment by loshkovskyi** [comment]
Thank you, @liggitt, your resolution made the nodes to turn ready and I was able to create volumes. @brenton, I see that you was assigned on this issue, please feel free to close it if you don't plan any work on it (i.e. documentation update).

**Comment by brenton** [comment]
I definitely think the real fix is going to come from the work in Kubernetes.  I'm going to close this in favor of tracking the problem in our docs in the short term: https://github.com/openshift/openshift-docs/issues/1293.
