### ISSUE TITLE
'oc new-app -o wide' and 'oc new-build -o wide' errors out

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6165]
On one hand, `wide` is NOT a valid option for `--output` listed in `oc new-app --help`, just like `crazy`, however:

```
[vagrant@openshiftdev origin]$ oc new-app mongo -o wide
F1202 14:56:19.596227   21826 helpers.go:250] err accessing flag show-all for command new-app: flag accessed but not defined: show-all
[vagrant@openshiftdev origin]$ oc new-app mongo -o crazy
error: output format "crazy" not recognized
```

On the other hand, `wide` is a valid option listed in `oc new-build --help`, but:

```
[vagrant@openshiftdev origin]$ oc new-build -D "FROM centos:7" -o wide
error: error: unknown type &api.List{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ListMeta:unversioned.ListMeta{SelfLink:"", ResourceVersion:""}, Items:[]runtime.Object{(*api.ImageStream)(0xc2080f83c0), (*api.BuildConfig)(0xc208040680)}}
```

I believe that:
1. The output formats supported by `new-app` and `new-build` should be the same;
2. Passing an invalid output format should consistently show the same error message.

**Comment by rhcarvalho** [comment]
Trying to add some bits to help getting this fixed...

I found out that in `new-app` we're [not relying on a kube helper](https://github.com/openshift/origin/blob/415140eb8e28d986c5aac00342d7e9c2e68f500a/pkg/cmd/cli/cmd/newapp.go#L163-L169) to add in the output options, the reason being an option name conflict (`--template`).

In `new-build` we use the helper.

We may not use the helper but at least update the code in `newapp.go` to bring in the upstream changes to help messages, etc.

**Comment by PI-Victor** [comment]
i'm currently working on this

**Comment by PI-Victor** [comment]
@rhcarvalho i think it would save me some time if i could get an answer at this question rather than trying to figure it out for myself but what if we change the flag `--template` in new-app to `--with-template` or `--from-template`. adding a logic to get upstream message from the kubernetes helper and workaround this sounds kinda hackish. i'm thinking it has some implications on the other hand i'm also thinking this might pop up somewhere else in the future so... ?

**Comment by rhcarvalho** [comment]
That has implications with backward-compatibility.

**Comment by rhcarvalho** [comment]
At first, there are two easy fixes we can do, and leave one item as a follow-up:

1. Make `new-build -o wide` work and behave as `new-build -o ''`
2. Make `new-app -o wide` show the same error message as `new-app -o invalid`
3. The follow-up is to make `new-app` and `new-build` have the same output options. That is harder to do because of the conflicting flags with upstream.

**Comment by PI-Victor** [comment]
ok, thanks. i will do exactly that.

**Comment by PI-Victor** [comment]
what would fix this and the conflicting flag and pretty much everything else would be to override `cmd` flags in newapp, in other words, mutate the cmd returned [here](https://github.com/openshift/origin/blob/07228ff88079166d57501ef86106e5f66bf1f893/pkg/cmd/cli/cmd/newapp.go#L171) by removing the conflicting flags added by cmdutil.AddPrinterFlags and adding the `template` one that we have. This way it also pulls changes from kube upstream

**Comment by rhcarvalho** [comment]
Sounds like it could work. I see in cobra there's a way to remove a command from a parent command, but still haven't found how to remove a flag.

**Comment by kargakis** [comment]
A result from adding flags upstream supposed to work only for `kubectl get` :(
