### ISSUE TITLE
client scale against active but non-latest deployment erroneously scales the latest/failed deployment

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#6172]
1. Deploy version 1 (replicas=1) such that the deployment is complete/successful
2. Deploy version 2 (replicas=1) such that the deployment fails
3. `oc scale dc/config --replicas=2`

The result is deployment version 2 is scaled up, when the active deployment (version 1) should have been scaled. This is a long-standing client bug discovered during #5875.

**Comment by kargakis** [comment]
Btw #5875 is fixing this by targetting the deploymentconfig/scale endpoint.

**Comment by ironcladlou** [comment]
>Btw #5875 is fixing this by targetting the deploymentconfig/scale endpoint.

Very important to note that the fix does not retroactively apply to clients predating #5875.

**Comment by kargakis** [comment]
Fixed
