### ISSUE TITLE
Allow creating multiple routes in the create from image workflow

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#6174]
See original discussion https://github.com/openshift/origin/pull/5997#issuecomment-161405427

**Comment by jwforres** [comment]
cc @spadgett @ebalsumgo

**Comment by benjaminapetersen** [comment]
If we did this, I'd think we would want to go with a multiple page approach.

**Comment by jwforres** [comment]
@benjaminapetersen meaning this https://trello.com/c/IChnzwgW ?

**Comment by benjaminapetersen** [comment]
Yup, prob multiple routes & controllers.  Build up payload in localStorage then submit @ the end?  Something like that anyway.

**Comment by spadgett** [comment]
Will need to think about what that means for validation since we use ng-pattern, ng-required, etc. in a single form now.

**Comment by liggitt** [comment]
I'd rather make it easy to chain the create form. "Create" and "Create and add another" buttons, where one takes you back to the overview and one takes you to a form for creating a route for the same service.

**Comment by ebalsumgo** [comment]
+1 for @liggitt suggestion

**Comment by jwforres** [comment]
Re-visiting this. Supporting the creation of multiple routes from the create from image workflow is complicating an already complicated workflow.  We make it easy enough to create another route for a service.
