### ISSUE TITLE
Surface descriptions for builders / templates in the add to project page

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/origin#6175]
So I was scanning trough https://github.com/openshift/origin/pull/6120 and was brought back to something I mentioned to some of the UI guys last night at the MeetUp at the Tower. Currently the project creation page is not very clear to a new user. "jboss-webserver30-tomcat8-openshift:1.1" does not really tell me what I can do with that. There is a tooltip with more information about the specific thing I am looking at, but its tiny compared to the amount of white space available. In v2 land, things were a lot simpler as you simply picked a base language and then picked a DB or no DB. In v3 things get trickier as things you have available contain multiple technologies. I think using the white space thats currently kinda wasted to expand and contain at least some of the description of the template would greatly improve readability and confusion for new user, and heck, even seasoned ones

cc @jwforres @spadgett

**Comment by spadgett** [comment]
For reference, this is how it looks with the descriptions directly on the card. We'd probably want to adjust the icon position for long description or limit it to one or two lines. The description text could be improved.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/11544171/7080756a-990e-11e5-817b-bb943473e574.png)

How it is today:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/11544210/a050b340-990e-11e5-9fb8-9e5ca8a40b00.png)

/cc @bparees

**Comment by ebalsumgo** [comment]
Yeah even just a single sentence and then a ... that exands into the full text, just anything, to make it clearer as to what is going on. The second screenshot makes it closer to v2 for sure.

**Comment by bparees** [comment]
+1

**Comment by ebalsumgo** [comment]
@spadgett also i thought you guys added a legend with what the Stack icon meant in one of the recent pushes?

**Comment by spadgett** [comment]
> also i thought you guys added a legend with what the Stack icon meant in the push mentioned above?

Yeah, I have a pull request for that. It hasn't merged yet.

**Comment by spadgett** [comment]
Related to https://trello.com/c/xlQaSaxT
