### ISSUE TITLE
Fail if can't start DNS service during OpenShift start

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#6184]
OpenShift will continue to start and run if its DNS service was not able to start.

The only indication that something went wrong is a single line the logs.

This causes a bunch of issues for users since it appears that the system started properly, but things like service dns resolution will not function. Any deployments which rely on the dns service will fail since they can't connect to required endpoints, and this causes confusion and requires the admin to debug the deployment when really its the OpenShift system which is not functioning properly.

It would be better to quickly fail and alert the user that their dns service did not start.

**Comment by deads2k** [comment]
@smarterclayton I remember discussing this when DNS went in.  Comments?

**Comment by smarterclayton** [comment]
We can't without breaking simple Openshift start.  Start master and start master API are maybe candidates to fail.

**Comment by smarterclayton** [comment]
This has basically been resolved at this point.  DNS should always work, even if port 53 is taken.
