### ISSUE TITLE
Malformed link to image stream in Web Console

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#6190]
See the `From` column:
![frontend-bug](https://cloud.githubusercontent.com/assets/87088/11588486/5a7fca80-9a81-11e5-9c1d-4084f0f27724.png)

**Comment by php-coder** [comment]
@jwforres JFYI

**Comment by jwforres** [comment]
Fix for this has already gone in with https://github.com/openshift/origin/pull/6168
