### ISSUE TITLE
Web console osc-file-input directive: can't clear value when set

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6191]
Once setting a value for a file, you can change it, but can't clear the value. This is currently only used for keys and certificates for routes.

/cc @jwforres

**Comment by liggitt** [comment]
To be fair, that is consistent with the file input behavior. Not sure I care to spend a lot of time working around that

**Comment by spadgett** [comment]
Fixed by https://github.com/jwforres/origin/pull/57
