### ISSUE TITLE
continer-hints flag is added to bash autocomplete when it shouldn't

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6192]
Seen [here](https://github.com/openshift/origin/pull/5709#discussion_r46295417). The `--container-hints` flag is added to the output of `hack/udpdate-generated-completions.sh` when no configuration of the `cobra` command seems to require it. 

/cc @deads2k

**Comment by deads2k** [comment]
@fabianofranz I'm seeing this in the autocomplete for `openshift ex diagnostics` too, so it seems to be existing.
