### ISSUE TITLE
"No builds to show" message missing at mobile screen widths

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6194]
The "No builds to show" message on the browse builds page is missing from the table at mobile screen widths. This is likely a problem for all the browse tables. It displays fine at full width.

I think it's a little odd to show the text inside the table anyway.

/cc @jwforres @sg00dwin

**Comment by jwforres** [comment]
Yeah we have a separate issue to move the text out of the table. https://github.com/openshift/origin/issues/5412

Will leave this open till we decide whether we are leaving it in there or not.

**Comment by spadgett** [comment]
I'm wrong, it's there. I just missed it because I was expected it in a second row I guess.

<img width="576" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11599627/f729d6b4-9a95-11e5-8b5d-70143a26acb6.png">

Closing since we have #5412
