### ISSUE TITLE
Image stream changes

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#6196]
This is coming from [here](https://github.com/openshift/origin/pull/5932#issuecomment-160937214). I'm putting it here since I'd like to see a discussion to clarify @smarterclayton ideas.

> User indicates they desire polling

Do you want the user to specify interval for polling as well, or we'll know best? Will this be per IS or per tag? I'm thinking about introducing ImportStrategy/ImportPolicy that could handle those. 

> Poller is level driven (off status.tag probably)

What do you mean by that?

> User can disable polling / import consistently per tag

Import or not is already available per reference flag. It's a shame we're doing this now, we could have introduce the policy/strategy solution I'm talking about before, instead of introducing additional flag, unless that's fine with you.

> Errors are properly reported (in status?) for terminal state errors

Yeah, per tag status sounds really good. 

> The import controller is just a single iteration of poll.

I think that's clear.

> The user can continue to have a "poll once" which is distinct from "poll forever".

This could be covered by the strategy/policy. 

@miminar @ncdc fyi

**Comment by smarterclayton** [comment]
I'm thinking about some of this now, will respond later.

**Comment by soltysh** [comment]
I think all this will be covered by #6288 thus I'm closing this one.
