### ISSUE TITLE
Web console component centric organization refactor

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#6198]
From [this trello card](https://trello.com/c/mr3tfA9q/533-web-console-consider-adjusting-to-a-component-centric-organizational-approach), migrated to a github issue for discussion.

I'm offering this as a suggested enhancement based on some past successful experiences and these resources:
- [Angular team best practices for apps built at Google](https://docs.google.com/document/u/2/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub)
- [A comparison of angular app organizational approaches](http://cliffmeyers.com/blog/2013/4/21/code-organization-angularjs-javascript) (first resource introducing me to this idea in an Angular app)
- [yeoman/generator-angular: Issue #109](https://github.com/yeoman/generator-angular/issues/109) (a similar discussion w/examples)

Essentially I'd say this is the difference between a rails-esque and a django-esque approach to organization. I would assert it improves maintainability through organizing files by the work they do (ex. logging) rather than by similar type (ex. controllers). This essentially breaks the app down into micro-apps, making less obvious associations apparent & reducing noise while working on individual features.

@jwforres @spadgett, finally created this per our discussion a few weeks ago!

**Comment by jwforres** [comment]
Realistically I don't know when we could get to this refactor, its a lot of effort with not a lot of gain compared to all of the other tech debt we have.  If we don't think this is going to happen in the next year, we should close this.  Personally I don't see it happening.

**Comment by benjaminapetersen** [comment]
Agree, this is pretty old :)
