### ISSUE TITLE
Plain RC status shows as "Deployed" in web console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6200]
This might be working as intended, but it's odd to see status "Deployed" for a replication controller that is not a deployment.

<img width="574" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11599600/d3bbc124-9a95-11e5-8e09-36e443031dac.png">

**Comment by jwforres** [comment]
there really is no "status" for an RC, we could change the column to be "Replicas" and just say 0 / 1 or 1 / 1   or could leave it as Status and just drop the icon and the status text and only show the "1 replica"

**Comment by jwforres** [comment]
Also the same applies to the RC's individual page, we show a status even though there really isnt one
