### ISSUE TITLE
External Access using NodePort

### ISSUE THREAD

**Issue by monisha-bhattacharya** [openshift/origin#6214]
Hi Everyone,

I am trying Openshift v3 with a single master with a single node setup.
I installed the examples/sample-app for ruby hello openshift and the pods and service is up. When I try to  use NodePort or LoadBalancer options for enabling external access to this app's frontend, I keep getting as below :

[root@openshift-master~]# curl openshift-node.tidalsoft:31597
curl: (7) Failed connect to openshift-node.tidalsoft:31597; No route to host

[root@openshift-master~]# oc describe service frontend
Name:   frontend
Namespace:  test
Labels: template=application-template-stibuild
Selector:   name=frontend
Type:   NodePort
IP: 172.30.252.16
Port:   web 5432/TCP
NodePort:   web 31597/TCP
Endpoints:  10.1.0.10:8080,10.1.0.13:8080
Session Affinity:   None
No events.

when I check the rules on node :

[root@openshift-node~]# iptables -t nat -L | grep 31597
REDIRECT   tcp  --  anywhere             anywhere             /\* test/frontend:web _/ tcp dpt:31597 redir ports 39433
DNAT       tcp  --  anywhere             anywhere             /_ test/frontend:web */ tcp dpt:31597 to:10.88.102.48:39433

Hence I added rules to allow the redirect port 39433

[root@openshift-node~]# iptables -I OS_FIREWALL_ALLOW -p tcp -m tcp --dport 39433 -j ACCEPT

After adding this rule, external access starts working. I am now confused...is this something that's needed for external access or am I missing any config here?

Any suggestions will be great.﻿

**Comment by marun** [comment]
@monisha-bhattacharya It is necessary to explicitly allow ingress nodeport traffic on hosts where firewall rules deny non-local traffic by default (e.g. fedora/centos/rhel with iptables-services package installed).  I've submitted a PR to kubernetes (https://github.com/kubernetes/kubernetes/pull/18804) intended to correct this problem.  Until that PR lands in k8s and is cherry-picked to origin, the only way to allow non-local nodeport traffic in openshift is to add the explicit rules you talk about.

**Comment by marun** [comment]
@monisha-bhattacharya origin master has switched to the iptables proxy which should fix the problem you were experiencing.  The change will be reflected in the pending 3.1.1 release.
