### ISSUE TITLE
no output build extended test failure

### ISSUE THREAD

**Issue by bparees** [openshift/origin#6215]
seen here, appears to be recurring:
https://ci.openshift.redhat.com/jenkins/job/origin_extended/377

```
• Failure [107.721 seconds]
builds: no name specified for the output image building from templates [It] should create an image from "fixtures/test-docker-no-outputname.json" docker template without an output image reference defined 
/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_no_outputname.go:32

  Expected error:
      <*exec.ExitError | 0xc208910008>: {
          ProcessState: {
              pid: 21839,
              status: 256,
              rusage: {
                  Utime: {Sec: 0, Usec: 41882},
                  Stime: {Sec: 0, Usec: 7390},
                  Maxrss: 29556,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 4042,
                  Majflt: 0,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 0,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 434,
                  Nivcsw: 4,
              },
          },
      }
      exit status 1
  not to have occurred

  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_no_outputname.go:30
------------------------------
    fail    builds: no name specified for the output image building from templates should create an image from " ... (1m47.720967112s)
```

**Comment by PI-Victor** [comment]
@bparees i'll have a look. i'm guessing you were right about using --follow. i can add a retry on failure but it would probably slow down the testing.

**Comment by bparees** [comment]
it recurred, with your new logging here's the output:

```
Failure [401.941 seconds]
builds: no name specified for the output image building from templates [It] should create an image from "fixtures/test-docker-no-outputname.json" docker template without an output image reference defined 
/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_no_outputname.go:35

  Expected
      <string>: test-docker-1
      error getting logs: Timeout: timed out waiting for build test-docker-1 to start after 10s
  to contain substring
      <string>: Build does not have an Output defined, no output image was pushed to a registry.

  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_no_outputname.go:34
------------------------------
    fail    builds: no name specified for the output image building from templates should create an image from " ... (6m41.940949884s)
```

full build is here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7728/consoleFull

it's basically as i expected, the build didn't start soon enough so the command failed.

I think you should switch this to start the build, wait for completion/success, and then get the logs, as we do elsewhere.

@mfojtik maybe you can help.

**Comment by PI-Victor** [comment]
i understand, what puzzles me is why does this flake, and this for example https://github.com/openshift/origin/blob/master/test/extended/builds/start_build.go#L58 doesn't. I'm not sure what i'm doing different here. And of course there are others as well. Could it be the images from the fixtures?
If not does that mean we need to increase the timeout for --wait or --follow?
@mfojtik you definitely can help :-)

**Comment by bparees** [comment]
Could definitely be the image, if they use different ones, since the build
pod has to pull the image to get started.

Increasing the timeout would be nice but I think that's baked into k8s
somewhere.

Ben Parees | OpenShift

**Comment by mfojtik** [comment]
@bparees @PI-Victor I can check if I can increase (or expose) the timeout on `start-build`

**Comment by mfojtik** [comment]
@PI-Victor alternatively you can use `Watch` API to monitor when the Build is completed and get the logs afterwards as @bparees suggested. That will eliminate the timeout (you will still have to set some reasonable timeout for watch).

**Comment by soltysh** [comment]
Seen in #6230 https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7703/

**Comment by kargakis** [comment]
> 1) Expose the timeout as BuildLogOptions{}, so clients can increase it if they want to

+1 to making the timeout configurable. I want this in oc logs
https://github.com/openshift/origin/issues/5584#issuecomment-160951829

**Comment by PI-Victor** [comment]
@bparees: @mfojtik i got a notification that this is marked as a blocker bug, so i was wondering if we can close this now since this got fixed in https://github.com/openshift/origin/pull/6268 ?

**Comment by mfojtik** [comment]
haven't see this happening recently, @bparees ?

**Comment by bparees** [comment]
closing based on fix.  thanks for the diligence, @PI-Victor!
