### ISSUE TITLE
"Failed to pull image registry.example.com:5000/default/hello-openshift:latest" during creating the pod which pull the image from integrated docker-registry

### ISSUE THREAD

**Issue by thincal** [openshift/origin#6222]
I have already followed steps from https://docs.openshift.org/latest/install_config/install/docker_registry.html#securing-the-registry to setup TLS based authentication.

But when I push an image labled with registry.example.com:5000/openshift/hello-openshift, it will report the error:
**unauthorized: access to the requested resource is not authorized**

if I pull an existed image inregistry, such as: registry.example.com:5000/openshift/hello-example, it will report the error:
**Trying to pull repository registry.example.com:5000/openshift/hello-example ... not found
Error: image openshift/hello-example:latest not found**

After googling similar questions, it is said that the push/pull operation should be done after login the registry, and that is true in my side.

But my questions are:
1. since the authentication is already based on certification, which are already installed/configured, why still need login the registry ?
2. if creating a pod which will use the image such as: registry.example.com:5000/openshift/hello-example, the openshfit event will report the image not found error, since it is most likely the registry login won't be done by openshift before creating this pod. 

so I am feeling that the login registry might be not necessary,  and also I don't know why it doesn't work. Looking forward to get your help with these, many thanks !

**Comment by deads2k** [comment]
Push and pull authorization to the openshift docker registry is done using tokens.  A token is presented as the password for a `docker login`.  That token is then used by the openshift docker registry to ask the openshift API server whether the user is authorized to push or pull images.

A certificate can't be used, because the openshift docker registry could not use it to perform the access check.  Try doing an `oc login` and then `oc whoami -t` to get your token.

**Comment by thincal** [comment]
@deads2k thanks for your reply !

I can login the registry via. the token and the pull/push is working fine then.
But when creating the pod via. the ```oc create -f```, it will still report:

```
Failed to pull image "registry.example.com:5000/openshift/hello-openshift:latest": image pull failed for registry.example.com:5000/openshift/hello-openshift:latest, this may be because there are no credentials on this request. details: (Error: image openshift/hello-openshift:latest not found)
```

but this image can be pulled via. the docker pull "registry.example.com:5000/openshift/hello-openshift:latest after login the registry manually.
So I still don't understand inside the openshift, how will it pull the docker images correctly ?

**Comment by deads2k** [comment]
Which namespace are you creating the Pod in?  Do you have a gist of the logs for the registry pod/container?

You can also run `oc policy who-can get imagestreams/layers -n openshift --config=path/to/admin.kubeconfig` to see who has rights to pull images from the openshift namespace.

**Comment by thincal** [comment]
@deads2k, thanks for your info.

Now I am create the pod in default namespace, the image registry.example.com:5000/default/hello-openshift:latest is pushed to integrated registry already.

and create the pod based on this yaml file:
```
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "hello-pod",
    "namespace": "default",
    "labels": {
      "name": "hello-openshift"
    }
  },
  "spec": {
    "containers": [
      {
        "name": "hello-openshift",
        "image": "registry.example.com:5000/default/hello-openshift:latest",
        "ports": [
          {
            "containerPort": 8080,
            "protocol": "TCP"
          }
        ],
        "resources": {},
        "terminationMessagePath": "/dev/termination-log",
        "imagePullPolicy": "IfNotPresent",
        "capabilities": {},
        "securityContext": {
          "capabilities": {},
          "privileged": false
        }
      }
    ],
    "restartPolicy": "Always",
    "dnsPolicy": "ClusterFirst"
  }
}
```

But it will report bellow error from openshift:
```
Failed to pull image "registry.ceyes.os:5000/default/hello-openshift:latest": image pull failed for registry.ceyes.os:5000/default/hello-openshift:latest, this may be because there are no credentials on this request. details: (Error: image default/hello-openshift:latest not found)
```

The logs from the registry pod:
```
time="2015-12-12T09:09:53Z" level=debug msg="authorizing request" http.request.host="registry.example.com:5000" http.request.id=789df636-091f-4c73-99cf-c42e9afaf980 http.request.method=GET http.request.remoteaddr="10.1.0.1:41481" http.request.uri="/v2/" http.request.useragent="docker/1.8.2 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=ed54b7f1-23a4-47cf-9bd9-c7558a3d77b6 
time="2015-12-12T09:09:53Z" level=error msg="error authorizing context: authorization header with basic token required" http.request.host="registry.example.com:5000" http.request.id=789df636-091f-4c73-99cf-c42e9afaf980 http.request.method=GET http.request.remoteaddr="10.1.0.1:41481" http.request.uri="/v2/" http.request.useragent="docker/1.8.2 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" instance.id=ed54b7f1-23a4-47cf-9bd9-c7558a3d77b6 
time="2015-12-12T09:09:53Z" level=info msg="response completed" http.request.host="registry.example.com:5000" http.request.id=789df636-091f-4c73-99cf-c42e9afaf980 http.request.method=GET http.request.remoteaddr="10.1.0.1:41481" http.request.uri="/v2/" http.request.useragent="docker/1.8.2 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=5.316041ms http.response.status=401 http.response.written=114 instance.id=ed54b7f1-23a4-47cf-9bd9-c7558a3d77b6 
10.1.0.1 - - [12/Dec/2015:09:09:53 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.8.2 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64"
time="2015-12-12T09:09:53Z" level=info msg="response completed" http.request.host="registry.example.com:5000" http.request.id=a1d558b6-6336-4bd7-9a6b-48ecb048671d http.request.method=GET http.request.remoteaddr="10.1.0.1:41483" http.request.uri="/v1/repositories/default/hello-openshift/images" http.request.useragent="docker/1.8.2 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="text/plain; charset=utf-8" http.response.duration="220.782µs" http.response.status=404 http.response.written=19 instance.id=ed54b7f1-23a4-47cf-9bd9-c7558a3d77b6 
10.1.0.1 - - [12/Dec/2015:09:09:53 +0000] "GET /v1/repositories/default/hello-openshift/images HTTP/1.1" 404 19 "" "docker/1.8.2 go/go1.4.2 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64"
```

sudo oc policy who-can get imagestreams/layers -n default --config=/etc/origin/master/admin.kubeconfig
```
Namespace: default
Verb:      get
Resource:  imagestreams/layers

Users:  admin
        system:serviceaccount:default:builder

Groups: system:cluster-admins
        system:masters
        system:serviceaccounts:default
```

**Comment by thincal** [comment]
Based on above trace from registry pod, ```GET /v1/repositories/default/hello-openshift/images HTTP/1.1``` shows that it is trying to get the image from v1 registry, but actually it's v2. Is that the error ?

**Comment by thincal** [comment]
@deads2k after push the image to integrated registry, it also create a imagestream by running ```oc get is```
```
hello-openshift   172.30.117.244:5000/default/hello-openshift   latest    2 hours ago
```
but my pod.json file is referring the image as ```registry.example.com:5000/default/hello-openshift:latest```, so is this causing the pull failed error ?

**Comment by thincal** [comment]
It seems that this failure is caused by https://github.com/openshift/origin/issues/6283, if I am wrong, please correct me. thanks.

**Comment by deads2k** [comment]
> It seems that this failure is caused by #6283, if I am wrong, please correct me. thanks.

I think that's very likely.  

I think there is some value you can use that will get auto-substituted to the internal registry.  @bparees @ncdc is there such a value?

**Comment by ncdc** [comment]
Only if you're in the default project where the registry is deployed (the
service env var).

You're better off using a DeploymentConfig with an ImageChangeTrigger, as
that will do the resolution for you.

**Comment by thincal** [comment]
@ncdc actually I don't know what is the recommended way to push my local docker images to the openshift integrated registry, that I just manually run ```docker push``` but the image stream is always represented as <registry-ip>:5000.
Could you help detail more about using a DeploymentConfig/ImageChangeTrigger for my case ?

**Comment by bparees** [comment]
Since you have an imagestream defined now, you just need to reference it from your DeploymentConfig, you can see an example here:

https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json#L202-L215

https://github.com/openshift/origin/blob/master/examples/sample-app/application-template-stibuild.json#L234

**Comment by thincal** [comment]
@bparees I am trying to reference the imagestream directly following bellow steps.

The ```oc get is``` shows:
```
NAME              DOCKER REPO                                   TAGS      UPDATED
hello-openshift   172.30.117.244:5000/default/hello-openshift   latest    2 days ago
```

then I am creating the pod firstly by using a hello-pod.json file as bellow:
```
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "hello-pod",
    "namespace": "default",
    "labels": {
      "name": "hello-openshift"
    }
  },
  "spec": {
    "containers": [
      {
        "name": "hello-openshift",
        "image": "hello-openshift",
        "ports": [
          {
            "containerPort": 8080,
            "protocol": "TCP"
          }
        ],
        "resources": {},
        "terminationMessagePath": "/dev/termination-log",
        "imagePullPolicy": "IfNotPresent",
        "capabilities": {},
        "securityContext": {
          "capabilities": {},
          "privileged": false
        }
      }
    ],
    "restartPolicy": "Always",
    "dnsPolicy": "ClusterFirst"
  }
}
```

after run ```oc create -f hello-pod.json```, the openshift event shows:
```
Failed to pull image "hello-openshift": Error: image library/hello-openshift:latest not found
```

but if I change the image reference as:
```
  "spec": {
    "containers": [
      {
        "name": "hello-openshift",
        "image": "172.30.117.244:5000/default/hello-openshift",
        ...
      }
  }
```
it will be working.

So questions still:

1. what is the correct way to reference imagestream in my hello-pod.json file above ?
2. if referring the image from a registry, can I using ```registry.example.com/default/hello-openshift``` instead ?

Many thanks !

**Comment by bparees** [comment]
> what is the correct way to reference imagestream in my hello-pod.json file above ?

pods only take full docker pull specs for the image path.  they do not understand imagestreams, so there is no "correct" way to reference an imagestream from a pod.

> if referring the image from a registry, can I using registry.example.com/default/hello-openshift instead ?

if registry.example.com resolves to your docker registry route, yes you can probably do that (not 100% certain if the credentials will work correctly to allow the pull)

if you want to reference an image via an imagestream, you need to use a DeploymentConfig with an ImageChangeTrigger, per the example I cited earlier.  Which is really the right way to define things anyway, creating raw pods is not a best practice.

**Comment by liggitt** [comment]
The generated credentials for pods to pull from the internal registry won't work with anything other than the registry service IP today

**Comment by thincal** [comment]
ok, the raw pod might be not a best practice, but I need it be working anyway :)

@bparees the example you cited shows
```
          "spec": {
            "containers": [
              {
                "name": "ruby-helloworld",
                "image": "origin-ruby-sample",
                "ports": [
                  {
                    "containerPort": 8080,
                    "protocol": "TCP"
                  }
                ],
              }
              ...
          }
```
here the image is not with a full path, so where will be pulled from ?

**Comment by liggitt** [comment]
I think it will behave the same as `docker pull origin-ruby-sample` performed on the node.

**Comment by thincal** [comment]
Got it, so that example only shows how to react with the image stream change by the trigger, about how to creat the pod firstly it is still using the public registry

**Comment by bparees** [comment]
No pod will be created with that field value due to the existence of the
image change trigger.  It will be substituted from the value pointed to by
the image stream in the change trigger as part of the deployment process.

Ben Parees | OpenShift

**Comment by thincal** [comment]
@bparees thanks for your explanation, but what's the ```spec.containers.image``` field used for ?

**Comment by bparees** [comment]
mostly it'll be ignored, here's an explanation of the process from @ironcladlou, @ironcladlou if this is documented somewhere at this point can you point to the official docs?
```
 The first (initial) deployment will be generated by resolving images
against any image triggers present regardless of the automatic flag,
by design. The deploymentConfig users create with image triggers don't
usually initially contain valid pullspecs. We resolve them once to get
the deployment started with the latest tag values defined in the
triggers. From that point forward, new image values for the tags will
*only* be resolved/updated if:

1. The referenced ImageStream tags change AND automatic=true, or
2. A configChange trigger is present and something *in the
deploymentConfig template changes* [1]
```

So pretty much when you have an ICT and a ConfigChangeTrigger and the ICT is set to automatic, the "image" field gets overwritten by whatever the ICT points to, each time a deployment occurs.

If you don't have all those things, the image field may be used instead, depending on your exact scenario.

**Comment by thincal** [comment]
@bparees thanks for your excellent explanation :)

**Comment by thincal** [comment]
since this could be solved by using the ICT or using the ip in pull spec, it will be closed now. Thanks all for your help.
