### ISSUE TITLE
oc import-image cannot import image from insecure docker registry

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#6227]
When using oc import-image to import imagestream from a insecure docker registry, it will hang a very long time,and cannot import successfully, I think what we need to do is to add a option for this command like --insecure, and when create imagestream , if this option exists , and the openshift.io/insecureRepository=true automatically to the imagestream.

**Comment by wanghaoran1988** [comment]
@bparees Hi, ben , I add a PR for this issue, could you please help review, thanks.

**Comment by bparees** [comment]
This falls under @pweil's team.

**Comment by deads2k** [comment]
The long timeout is probably fixed by https://github.com/openshift/origin/pull/6418

**Comment by liggitt** [comment]
not sure... I left timeouts long for oc operations... my PR just addressed server-side clients

**Comment by deads2k** [comment]
> not sure... I left timeouts long for oc operations... my PR just addressed server-side clients

client side waits until the server side indicates success or failure.
