### ISSUE TITLE
Can not pull image from remote node

### ISSUE THREAD

**Issue by azywait** [openshift/origin#6228]
I have two nodes:
master (192.168.1.101) :     openshift master  +  openshift node1
worker (192.168.1.102) :     openshift node2

The master can schedule task to every node, but only the node1 (docker-registry on it) can success deploy. Pod can access each other in different node, as they are using Openvswitch technology! 

By using docker-registry: 
master node can docker login, pull and push images to the private registry
But worker node only can login,  pull and push operation will forever pending, there has no logs output.

The installed environment as follow:
docker : 1.9.1,
openshift :  v1.1

Is the remote node must use secure TLS? I only use '--insecure-registry'  when docker start.

**Comment by thincal** [comment]
you might could try the TLS by certification, https://docs.openshift.org/latest/install_config/install/docker_registry.html#securing-the-registry

**Comment by azywait** [comment]
I have tried my times as the https://docs.openshift.org/latest/install_config/install/docker_registry.html#securing-the-registry document, but, always failed.
![image](https://cloud.githubusercontent.com/assets/4987859/11659220/15cbf0ba-9e02-11e5-9434-d92c28e20813.png)
But I have store "ca.crt" in /etc/docker/ as the guide
Docker version: 1.9.1
Whether I missed some configuration?

**Comment by liggitt** [comment]
How did you create the certificate? If you are creating it for an IP, you need to include the IP address as a subjectAltName.

**Comment by azywait** [comment]
I create the certificate as the document:
![image](https://cloud.githubusercontent.com/assets/4987859/11708314/dc25bd6c-9f48-11e5-80d3-7173e1cff8cb.png)
I didn't deploy router, and I only want to use IP to secure the registry.
Can the "oadm ca create-server-cert" create  the certificate include the IP address as subjectAltName? 
 I am not very understanding of this.
Does I miss some documents on "https://docs.openshift.org" about how to include the IP address as subjectAltName?
I really appreciate your assistance.  :)

**Comment by liggitt** [comment]
That command will correctly create a serving certificate with IP SANs. The next thing to check is whether the registry is using the certificate you created correctly. Can you include the output of
```
openssl s_client -connect 172.30.135.64:5000 -showcerts
```

**Comment by azywait** [comment]
I restart the registry, so the service IP has changed, and it still can not work. But the output has changed.
master node(192.168.1.101): master + node1(include registry)

The registry info as follow:
![image](https://cloud.githubusercontent.com/assets/4987859/11734331/45677dda-9ff1-11e5-84b2-32d6f8b06cbd.png)

node1 can docker login, pull, push images, it use certificate connecting registry. The output of
"openssl s_client -connect 172.30.232.33:5000 -showcerts"
![image](https://cloud.githubusercontent.com/assets/4987859/11734372/b0c7ed58-9ff1-11e5-8712-e1082d33db70.png)
![image](https://cloud.githubusercontent.com/assets/4987859/11734391/d00d4eb0-9ff1-11e5-98cd-37f436159c15.png)

It seems to be working.

Now I want to add another node, which is node2
node2: 192.168.1.102

I create this node's configuration file as follow:

oadm create-node-config --node-dir=node2 \
--node=192.168.1.102 --hostnames=node2,192.168.1.102 \
--network-plugin='redhat/openshift-ovs-subnet' \
--master='https://192.168.1.101:8443' \
--config=/root/openshift.local.config/master/admin.kubeconfig

and start node2 on another machine, it workings, and I can list all nodes use system:admin user.

certificate file 'ca.crt' has been placed on "/etc/docker/certs.d" as follow:
![image](https://cloud.githubusercontent.com/assets/4987859/11734742/fe37c0e2-9ff4-11e5-9ad0-0e21786aa885.png)

When trying docker login from node2, it failed. the output as follow:
![image](https://cloud.githubusercontent.com/assets/4987859/11734568/88ab359e-9ff3-11e5-8cbe-42b74074fbb4.png)

Using "openssl s_client -connect 172.30.232.33:5000 -showcerts" check certificate, it also failed, and forever pending....
![image](https://cloud.githubusercontent.com/assets/4987859/11734601/d85a393c-9ff3-11e5-9cdf-e935a92110cb.png)

And the output of docker-registry as follow:
![image](https://cloud.githubusercontent.com/assets/4987859/11734682/8aa3e8e0-9ff4-11e5-8966-9e57e29b15c4.png)

I think I have a wrong configuration procedure about my openshift cluster.
I really appreciate your help.   :)

**Comment by liggitt** [comment]
Seems like it might be a networking issue from the new node.

**Comment by azywait** [comment]
They are all in a subnet, new node can connect the pod which on the node1.  I didn't use ansible to deploy the Openshift, So, what networking issue maybe caused this problem? What I seems like to be missed without using ansible?

**Comment by azywait** [comment]
Whether there has some document about how to deploy an openshift cluster without using ansible?

**Comment by azywait** [comment]
It works!! 
Installation without using Ansible must be will carefully, you will easily miss some options.
Thanks for your help!!

**Comment by Hawk79** [comment]
azywait - So what was the solution to this problem?
