### ISSUE TITLE
How to specify the version of router/deployer/registry etc. built-in components in openshift

### ISSUE THREAD

**Issue by thincal** [openshift/origin#6229]
I have installed the openshift by the ansible, but when deploy the router/registry etc. components, it will pull the latest version from docker.io, but sometimes the version is updating so frequently, so is there a way to specify the version of these components ? many thanks.

**Comment by deads2k** [comment]
You can pin it in the `master-config.yaml` `imageConfig.format` (https://docs.openshift.org/latest/install_config/master_node_configuration.html) or from the command line with the `--images` flag.

**Comment by deads2k** [comment]
@sdodson I suspect you have experience setting the exact format string.

**Comment by sdodson** [comment]
@thincal The router and registry are special cases as the `oadm` command builds a deployment config for them and they shouldn't update on their own unless you supply the `--latest-images` flag to the `oadm` command. When using the oadm command, if you want a specific version you can add `--images='openshift/origin-${component}:v1.0'` where 'v1.0' is whatever version of the image you want it to deploy.

Now, the deployer and other components that OpenShift automatically creates during normal operation use the values from your `master-config.yaml` and `node-config.yaml`. They both have a block like the following and they work the same way as the --images flag above, edit them to your liking and restart master and node services. Again, the default is not to use 'latest' so you'll end up with images that match the version of the master and node.

```
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
```

**Comment by thincal** [comment]
@sdodson thanks for your useful info. But it seems that there is no way to specify the version of openshift/origin-pod and openshift/origin-deployer when running oadm command ?

**Comment by liggitt** [comment]
`oadm` commands don't create origin-pod and origin-deployer images… those come from the master config as noted

**Comment by thincal** [comment]
@liggitt yes and thanks... but if I change the ```imageConfig.format``` in node/master config file, then how to apply this change ?
