### ISSUE TITLE
TestRegistryClientConnectPulpRegistry flake

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#6232]
I got this failure when running [test](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7680/console):

```console
--- FAIL: TestRegistryClientConnectPulpRegistry-4 (1.54s)
	dockerregistryclient_test.go:105: the image "6c3a84d798dc449313787502060b6d5b4694d7527d64a7c99ba199e3b2df834e" in repository "library/rhel" was not found and may have been deleted
FAIL
```

**Comment by miminar** [comment]
Should be resolved by #6335.

**Comment by miminar** [comment]
New registry client produces different error messages that are not retried:

```
I0829 11:54:47.081784   15770 client.go:323] Found registry v2 API at https://registry.access.redhat.com/v2/
I0829 11:54:47.566076   15770 client.go:573] unable to find tagged image at "https://registry.access.redhat.com/v2/library/rhel/manifests/latest", 404 map[Date:[Mon, 29 Aug 2016 15:54:47 GMT] Server:[Apache] Content-Length:[53] Content-Type:[application/json]]: {"errors": [{"code": "404", "message": "Not Found"}]}
--- FAIL: TestRegistryClientConnectPulpRegistry-4 (1.07s)
	dockerregistryclient_test.go:128: tag "latest" has not been set on repository "library/rhel"
FAIL
```
See job https://ci.dev.openshift.redhat.com/jenkins/job/test_pull_requests_ose/498/.
Re-opening.

**Comment by miminar** [comment]
The failing job reported was run for openshift/ose. Which lacks commit https://github.com/openshift/origin/commit/2787678ff59c1249958186c6e2e875bc16c5f8cb. Thanks to it, the flake won't happen in openshift/origin. I'm closing this once again. And I'll backport the commit to openshift/ose.
