### ISSUE TITLE
Extended tests: simplify code for working with MySQL/PostgreSQL

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#6235]
During my work on #5969 I did a bit refactoring and I found that `test/extended/util/db/mysql.go` and `test/extended/util/db/postgresql.go` could be refactored/improved even more:

1) The long statements like this:

``` go
    err = oc.Run("exec").Args(m.PodName, "-c", container, "--", "bash", "-c",
        fmt.Sprintf("mysql -h %s -u%s -p%s -e \"SELECT 1;\" %s",
            hostAddress, masterConf.Env["MYSQL_USER"], masterConf.Env["MYSQL_PASSWORD"],
            masterConf.Env["MYSQL_DATABASE"])).Execute()
```

could be rewritten to use `executeShellCommand()` (like I did for MongoDB).

2) As @rhcarvalho pointed me out in a comment for my PR, we don't need to parse environment of all pods to get the `MYSQL_USER`, `MYSQL_DATABASE`, `MYSQL_PASSWORD` values -- these values _already_ available as environment variables inside of our pod, so we just need to start using them (see example for MongoDB).

**Comment by php-coder** [comment]
3) we also could leverage `exutil.WaitForADeployment()`

**Comment by bparees** [comment]
trello'd https://trello.com/c/VLFCaHxT
