### ISSUE TITLE
Extended tests: add debugging tips/troubleshooting guide

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#6236]
During my work on #6197 there were a couple of obstacles that could be show-stopper for a newcomers. Especially when you're trying to debug tests. I would like to see a few words about possible problems and debugging technics in documentation/README/etc.

My cases:

1) Permission denied when you run tests inside of vagrant:

```
[vagrant@localhost extended]$ ./core.sh 
package github.com/davecgh/go-spew/spew: mkdir /data/src/github.com/davecgh/: permission denied
package github.com/docker/libcontainer/cgroups/fs: mkdir /data/src/github.com/docker/: permission denied
package github.com/docker/libcontainer/configs: cannot find package "github.com/docker/libcontainer/configs" in any of:
    /usr/lib/golang/src/github.com/docker/libcontainer/configs (from $GOROOT)
    /data/src/github.com/docker/libcontainer/configs (from $GOPATH)
package github.com/golang/glog: mkdir /data/src/github.com/golang/: permission denied
package github.com/juju/ratelimit: mkdir /data/src/github.com/juju/: permission denied
package github.com/pborman/uuid: mkdir /data/src/github.com/pborman/: permission denied
package github.com/prometheus/client_golang/prometheus: mkdir /data/src/github.com/prometheus/: permission denied
package github.com/spf13/pflag: mkdir /data/src/github.com/spf13/: permission denied
package github.com/google/gofuzz: mkdir /data/src/github.com/google/: permission denied
```

The problem: tests tries to run `go get` but they don't have permissions.

Workaround/fix from @rhcarvalho is to create file `.vagrant-openshift.json` (in the same dir as `Vagrantfile`):

``` json
{
  "sync_from": "~/git/src",
  "sync_to": "/data/src"
}
```

and reload the vagrant.

2) When you tried to debug tests you could have strange errors:

```
[vagrant@localhost origin]$ sh -x ./test/extended/core.sh 
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ go get -d k8s.io/kubernetes/pkg/util
+ export KUBE_REPO_ROOT=/home/vagrant/go:/data/src/k8s.io/kubernetes
+ KUBE_REPO_ROOT=/home/vagrant/go:/data/src/k8s.io/kubernetes
++ dirname ./test/extended/core.sh
+ OS_ROOT=./test/extended/../..
+ source ./test/extended/../../hack/util.sh
++ TIME_SEC=1000
++ TIME_MIN=60000
./test/extended/../../hack/util.sh: line 601: `os::build:wait_for_start': not a valid identifier
```

This is because tests uses `bash` and I run them with `sh`. So, don't use `sh -x`, only `bash -x` if you want to see what script is doing.

3) When you try to write something from integration tests to the console with `fmt.Printf()` it won't shown. You should use `fmt.Fprintf(g.GinkgoWriter, msg)` instead.

4) Hint from @mnagy: when test fails and you need to explore the state of the openshift and run some commands you could put sleep command inside of the the test and find in the scripts output string like this: `[INFO] To debug: export KUBECONFIG=/tmp/openshift-extended-tests/core/openshift.local.config/master/admin.kubeconfig` When you execute this command you will be able to use `oc` command as usual.

Probably, @PI-Victor and @mfojtik could provide other such tricks and possible problems.

**Comment by PI-Victor** [comment]
Rodolfo is right, you can add that json or you could modify the Vagrantfile and have it separate from the repo. My .json looks something like this:
```
  "sync_to": "/data/src",
  "sync_from": "/home/ipalade/projects/golang/src",
```
thus loading all of my Go libs.

I did modify that Vagrantfile on which my current vm is built and not the .json, however both would work. It sucks that it specifically loads only your openshift project when of course, you need the rest of the go libs as well.
As for your above problems i don't remember if i encountered them or not, the tests pretty much work for me right now.

**Comment by php-coder** [comment]
One more from @gabemontero :

><gmontero>: figured it out ... your GOPATH can only have a single directory in  it ... KUBE_REPO_ROOT is not set up properly if GOPATH has multiple directories ...

**Comment by gabemontero** [comment]
thx @php-coder

**Comment by rhcarvalho** [comment]
Run into a new problem:

```console
$ bash -x test/extended/core.sh 
--ginkgo.focus="mysql"                                       
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ go get -d k8s.io/kubernetes/pkg/util
# cd .; git clone https://go.googlesource.com/crypto /data/src/golang.org/x/crypto
Cloning into '/data/src/golang.org/x/crypto'...
fatal: unable to access 'https://go.googlesource.com/crypto/': Peer's Certificate has expired.
package github.com/docker/docker/pkg/mount
        imports github.com/docker/go-units
        imports github.com/pborman/uuid
        imports github.com/prometheus/client_golang/prometheus
        imports github.com/beorn7/perks/quantile
        imports github.com/golang/protobuf/proto
        imports github.com/prometheus/client_model/go
        imports github.com/prometheus/common/expfmt
        imports github.com/matttproud/golang_protobuf_extensions/pbutil
        imports github.com/prometheus/procfs
        imports github.com/spf13/pflag
        imports golang.org/x/crypto/ssh: exit status 128
```

**Comment by rhcarvalho** [comment]
`go get -d k8s.io/kubernetes/pkg/util` takes way too much time, even though I already have kubernetes checked out.

**Comment by rhcarvalho** [comment]
Turns out that I need to `git checkout master` in the kubernetes repo to fix the problem I mentioned above, that always happen when executing tests for a second time.

**Comment by php-coder** [comment]
>4) Hint from @mnagy: when test fails and you need to explore the state of the openshift and run some commands you could put sleep command inside of the the test and find in the scripts output string like this: [INFO] To debug: export KUBECONFIG=/tmp/openshift-extended-tests/core/openshift.local.config/master/admin.kubeconfig When you execute this command you will be able to use oc command as usual.

Also need to mention that after that each tests executed in separate temporary projects, so we also need to switch to appropriate project to see the pods: `oc get projects` && `oc project <name>` && `oc get pods`


And a new trick: after latest changes in testing framework, when you're changing the test it won't be recompiled automatically. To trigger this you should remove the test binary: `rm -fv _output/local/bin/linux/amd64/extended.test`

**Comment by php-coder** [comment]
>3) When you try to write something from integration tests to the console with fmt.Printf() it won't shown. You should use fmt.Fprintf(g.GinkgoWriter, msg) instead.

By default they are not shown too unless test fails. To show the output you need to pass `-ginkgo.v` parameter, like this: `./test/extended/core.sh --focus="mongodb replication" -ginkgo.v`

**Comment by PI-Victor** [comment]
@php-coder thanks man, good find. was always wondering how to write to that ginkgo interface to troubleshoot the tests. :+1:

**Comment by rhcarvalho** [comment]
@php-coder @PI-Victor that behavior is documented:

> ###Logging Output

> Ginkgo provides a globally available io.Writer called GinkgoWriter that you can write to. GinkgoWriter aggregates input while a test is running and only dumps it to stdout if the test fails. When running in verbose mode (ginkgo -v or go test -ginkgo.v) GinkgoWriter always immediately redirects its input to stdout.

> When a Ginkgo test suite is interrupted (via ^C) Ginkgo will emit any content written to the GinkgoWriter. This makes it easier to debug stuck tests. This is particularly useful when paired with --progress which instruct Ginkgo to emit notifications to the GinkgoWriter as it runs through your BeforeEaches, Its, AfterEaches, etc…

http://onsi.github.io/ginkgo/

**Comment by PI-Victor** [comment]
i read the docs a million times, i didn't know how to write to it.

**Comment by php-coder** [comment]
>> 4) Hint from @mnagy: when test fails and you need to explore the state of the openshift and run some commands you could put sleep command inside of the the test and find in the scripts output string like this: [INFO] To debug: export KUBECONFIG=/tmp/openshift-extended-tests/core/openshift.local.config/master/admin.kubeconfig When you execute this command you will be able to use oc command as usual.
>
>Also need to mention that after that each tests executed in separate temporary projects, so we also need to switch to appropriate project to see the pods: oc get projects && oc project <name> && oc get pods

Acutally this login you as a system user, that sometimes not what you want. Instead of doing ` export KUBECONFIG=/tmp/openshift-extended-tests/core/openshift.local.config/master/admin.kubeconfig` you can do `export KUBECONFIG=$PWD/extended-test-extended-build-gil97-b78tb-user.kubeconfig` where `extended-test-extended-build-gil97-b78tb` is the project name and also part of the filename that was created in the current directory.

**Comment by bparees** [comment]
@php-coder there's nothing devex specific about this, no reason you can't continue to own it.
