### ISSUE TITLE
web console: source link broken for build with a context directory

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#6244]
When displaying the list of builds, the link rendered for a build source contains "undefined" instead of a ref like "master" when there is a non-blank context directory in the build config.

**Comment by csrwng** [comment]
@spadgett @jwforres

**Comment by jwforres** [comment]
I can't recreate this, when i specify contextDir of `/views` for the nodejs-ex repo i'm getting a URL like `https://github.com/openshift/nodejs-ex/tree/master/views`

**Comment by jwforres** [comment]
ahhh its when ref is not set
