### ISSUE TITLE
Kibana: No results found 

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#6245]
I have installed and configured kibana, fluentd and elasticsearch on OpenShift Origin 3.1 using the official documentation.

Kibana seems to work and I can acces it in my webconsole. But I can't see logs.
Discover shows me: No results found 

I can see my projects on the left:
    myproject1.*
    myproject2.*
    myproject3.*

I also get sometimes this error:

```RuntimeException[com.floragunn.searchguard.tokeneval.MalformedConfigurationException: no bypass or execute filters at all]; nested: MalformedConfigurationException[no bypass or execute filters at all]; ```

Kibana doesn't have a log file so I really don't know how to debug this issue.

**Comment by jcantrill** [comment]
@lorenzvth7 Can you confirm the date range of logs you are trying to view is broad enough to include your logs?  The default in the upper right sometimes 'masks' logs.  @ewolinetz  Can you comment on the error?  @sosiouxme are timestamps normalized by fluentd such that the entries wont be masked if there is a mismatch?

**Comment by ewolinetz** [comment]
That error is produced by the search-guard plugin, and I would need to dive a bit deeper to understand why we're getting it (what is trying to communicate with Elasticsearch, and what it is trying to do).  It may be a misconfiguration of an ACL.

@lorenzvth7 if you look at your Elasticsearch logs, do you see any messages similar to the following - indicating that log indices were created:
```
[Halloween Jack] [myproject1.2015.12.09] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings [fluentd]
[Halloween Jack] [myproject1.2015.12.09] update_mapping [fluentd] (dynamic)
```

**Comment by lorenzvth7** [comment]
@ewolinetz 
The elastic-search pod is not running by default after the installation. You have to scale it up manually. That was the issue. Thanks
