### ISSUE TITLE
Routers creation failures depending on user kubeconfig

### ISSUE THREAD

**Issue by simon3z** [openshift/origin#6248]
It seems that creation of a router is somehow related to the current user kubeconfig project:

```
# oc project openshift-infra
# oadm router router \
  --credentials=/etc/origin/master/openshift-router.kubeconfig \
  --service-account=router
error: router could not be created; unable to validate service account,
       host ports are forbidden
# oadm router router \
  --credentials=/etc/origin/master/openshift-router.kubeconfig \
  --service-account=router \
  --host-network=false
error: router could not be created; unable to validate service account,
       host ports are forbidden

# oc project default
# oadm router router \
  --credentials=/etc/origin/master/openshift-router.kubeconfig \
  --service-account=router
(success)
```

Few notes:
1. I am not sure whether `oadm` should respect the user kubeconfig (especially in the project regard), more specifically, should the administrative commands (`oadm`) be influenced by the developer context (`oc`)?
2. Since we're specifying the `--credentials` it may make sense to take the context (project) from there
3. If none of the above then it should be at least possible to run `oadm router` (and possibly other as `registry`, etc.) specifying a project

cc @smarterclayton @deads2k

**Comment by liggitt** [comment]
`oadm router` should already take `-n default`

**Comment by liggitt** [comment]
Like all client-side creation commands, it uses the current project. This is working as designed.

**Comment by simon3z** [comment]
> oadm router should already take -n default

Either it is missing or undocumented.

**Comment by fabianofranz** [comment]
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1290128

**Comment by smarterclayton** [comment]
At a minimum, we should extend the message we print from the router
creation command to indicate the current namespace, and ask whether the
service account is expected in that namespace.

**Comment by smarterclayton** [comment]
Closing due to age, should be substantially better today.
