### ISSUE TITLE
Extended tests are not properly bypassing ginkgo.skip when focused

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6255]
Running --focus="HAProxy" does not trigger the test - you have to clear skip with SKIP="XXX" which is wrong.  It's possible we have something wrong with focus.

**Comment by mfojtik** [comment]
@smarterclayton didn't this change to "--ginkgo.focus=HAProxy" ?

**Comment by mfojtik** [comment]
@smarterclayton I just did

```console
[root@localhost origin]# ./test/extended/core.sh --ginkgo.focus="HAProxy"
```

and the HAProxy test case ran successfully.

**Comment by smarterclayton** [comment]
I didn't see
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7711/
work
correctly.

**Comment by mfojtik** [comment]
@smarterclayton 

```
Running TEST_REPORT_DIR=/tmp/openshift-extended-tests/junit/extended test/extended/core.sh --ginkgo.focus="haproxy"...
```

case sensitive?

**Comment by smarterclayton** [comment]
the descriptions have HAProxy in them.

**Comment by mfojtik** [comment]
@smarterclayton I don't see the build in jenkins anymore, can you give me an example of core.sh --ginkgo-focus="" I can use to reproduce this?

**Comment by smarterclayton** [comment]
I've forgotten everything about this.

**Comment by smarterclayton** [comment]
Still seeing this:

```
Finished TEST_REPORT_DIR=/tmp/openshift-extended-tests/junit/extended test/extended/core.sh --ginkgo.focus="test deployment"
```

in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/10050/consoleFull

**Comment by smarterclayton** [comment]
Was bad bash - ginkgo getting skip and focus will give skip priority.
