### ISSUE TITLE
using targetPort with a name in service definition doesn't seem to work via route

### ISSUE THREAD

**Issue by dustymabe** [openshift/origin#6265]
Using `targetPort` in the service definition to map to a named port in a pod definition doesn't seem to work. Everything looks like it works and the web interface even has `80/TCP → apacheport` in the display, but I can never establish a connection. If I instead use `targetPort : 8080` in openshift it works. Mapping to a name works in kubernetes-1.1.0-0.17.git388061f.fc23.x86_64 so I think I'm not doing something wrong, but I can't be sure. My target ose environment is 3.1.

Example Pod
```
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "labels": {
            "app": "helloapache"
        },
        "name": "helloapache"
    },
    "spec": {
        "containers": [
            {
                "image": "dustymabe/httpd:latest",
                "name": "helloapache",
                "ports": [
                    {
                        "name": "apacheport",
                        "containerPort": 8080,
                        "protocol": "TCP"
                    }
                ]
            }
        ]
    }
}
```

Example service
```
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "labels": {
            "name": "apacheservice"
        },
        "name": "apacheservice"
    },
    "spec": {
        "ports": [
            {
                "port": 80,
                "targetPort": "apacheport"
            }
        ],
        "selector": {
            "app": "helloapache"
        },
        "type": "LoadBalancer"
    }
}
```

**Comment by liggitt** [comment]
How are you attempting to establish the connection?

**Comment by dustymabe** [comment]
curl or firefox, neither work. I always get a 503 error

**Comment by liggitt** [comment]
What do the endpoints for the service look like?
```
oc get services -o json
oc get endpoints -o json
```

**Comment by liggitt** [comment]
and you are curling the service ip directly, not going through the API proxy, right?

**Comment by dustymabe** [comment]
I am curling the hostname associated with the route that is associated with  the service. 

route info
```
[root@f23 atomicapp (dusty-detect-openshift-provider *%)]# ./oc get route apacheservice -o json
{
    "kind": "Route",
    "apiVersion": "v1",
    "metadata": {
        "name": "apacheservice",
        "namespace": "proj1",
        "selfLink": "/oapi/v1/namespaces/proj1/routes/apacheservice",
        "uid": "fbc1e3a5-9f89-11e5-bbd9-0e2e65752393",
        "resourceVersion": "18394421",
        "creationTimestamp": "2015-12-10T22:04:28Z",
        "labels": {
            "name": "apacheservice"
        },
        "annotations": {
            "openshift.io/host.generated": "true"
        }
    },
    "spec": {
        "host": "apacheservice-proj1.e8ca.engint.openshiftapps.com",
        "to": {
            "kind": "Service",
            "name": "apacheservice"
        },
        "port": {
            "targetPort": "apacheport"
        }
    },
    "status": {}
}
```

service info
```
[root@f23 atomicapp (dusty-detect-openshift-provider *%)]# ./oc get service apacheservice -o json                                                                                                                                            
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "apacheservice",
        "namespace": "proj1",
        "selfLink": "/api/v1/namespaces/proj1/services/apacheservice",
        "uid": "e7264b46-9f89-11e5-bbd9-0e2e65752393",
        "resourceVersion": "18394205",
        "creationTimestamp": "2015-12-10T22:03:54Z",
        "labels": {
            "name": "apacheservice"
        }
    },
    "spec": {
        "ports": [
            {
                "protocol": "TCP",
                "port": 80,
                "targetPort": "apacheport",
                "nodePort": 31114
            }
        ],
        "selector": {
            "app": "helloapache"
        },
        "portalIP": "172.30.205.253",
        "clusterIP": "172.30.205.253",
        "type": "LoadBalancer",
        "sessionAffinity": "None"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

endpoints info
```
[root@f23 atomicapp (dusty-detect-openshift-provider *%)]# ./oc get endpoints apacheservice -o json                                                                                                                                          
{
    "kind": "Endpoints",
    "apiVersion": "v1",
    "metadata": {
        "name": "apacheservice",
        "namespace": "proj1",
        "selfLink": "/api/v1/namespaces/proj1/endpoints/apacheservice",
        "uid": "e72933e2-9f89-11e5-bbd9-0e2e65752393",
        "resourceVersion": "18394251",
        "creationTimestamp": "2015-12-10T22:03:54Z",
        "labels": {
            "name": "apacheservice"
        }
    },
    "subsets": [
        {
            "addresses": [
                {
                    "ip": "10.1.16.21",
                    "targetRef": {
                        "kind": "Pod",
                        "namespace": "proj1",
                        "name": "helloapache",
                        "uid": "e71e2b92-9f89-11e5-bbd9-0e2e65752393",
                        "resourceVersion": "18394250"
                    }
                }
            ],
            "ports": [
                {
                    "port": 8080,
                    "protocol": "TCP"
                }
            ]
        }
    ]
}
```

**Comment by dustymabe** [comment]
Note that the route was created using `./oc expose service apacheservice`

**Comment by kargakis** [comment]
The problem is that the route uses a named target port and the associated endpoint is not. https://github.com/openshift/origin/pull/5578 fixes this.

**Comment by kargakis** [comment]
In the meantime, @dustymabe can you try 
```
oc patch route/apacheservice -p '{"spec":{"port":{"targetPort":8080}}}'
``` 
and try to connect?

**Comment by dustymabe** [comment]
@kargakis that patch command works

**Comment by liggitt** [comment]
Does #5578 actually fix the issue with named ports, or just let you set a numeric target port on the route. Named ports are needed when you want services or routes to route to different port numbers on pods that are serving the same content. 

For that to work, the names of the ports need to make it into the endpoints somehow. Isn't that an upstream bug that needs fixing?

**Comment by kargakis** [comment]
I think that the problem is [this](https://github.com/kubernetes/kubernetes/blob/a8664f16bbcd0f9c393a9f97aa8e292dbc8a64d5/pkg/api/types.go#L1402-L1403). Which is an upstream bug, yes. In the meantime, making oc expose set a numeric target port (I dont think users generate routes manually any more) and beefing up oc status to report (even if we fix endpoints upstream, we probably still want the oc status changes) seems fine?

**Comment by liggitt** [comment]
It just seems like the route is picking up the name of the pod port, when that is not what will be surfaced in the endpoint. In this case, the route should have been using the endpoint port named "", right?

**Comment by kargakis** [comment]
> It just seems like the route is picking up the name of the pod port, when that is not what will be surfaced in the endpoint. In this case, the route should have been using the endpoint port named "", right?

I am not sure about that. Maybe @pweil- can weigh in

**Comment by pweil-** [comment]
Routes use endpoints and filter based on the endpoint name.

how endpoints are given to the router: https://github.com/openshift/origin/blob/master/plugins/router/template/plugin.go#L194-194
how the router filters them with a preferred port: 
https://github.com/openshift/origin/blob/master/plugins/router/template/router.go#L364-364
https://github.com/openshift/origin/blob/master/plugins/router/template/router.go#L148-148

cc @ramr

**Comment by liggitt** [comment]
Summary:
* if a route has a numeric targetPort, that matches the containerport number.
* if a route has a named targetPort, that matches the serviceport name (NOT the containerport name)

My preference would be to switch routes to use the serviceport names, so that changes to the service port mapping get picked up by the route automatically.

@kargakis @spadgett I think we should change `oc expose` and the UI route creation to set a route's targetPort to the name of the service port by default.

**Comment by liggitt** [comment]
https://gist.github.com/liggitt/4b71c07b8c69ab7eabbe is my scratchpad for investigating this

**Comment by dustymabe** [comment]
> My preference would be to switch routes to use the serviceport names, so that changes to the service port mapping get picked up by the route automatically.

+1

**Comment by kargakis** [comment]
> @kargakis @spadgett I think we should change oc expose and the UI route creation to set a route's targetPort to the name of the service port by default.

`oc expose` [already](https://github.com/kubernetes/kubernetes/blob/d3243b87789c3505fdb33134a2602acfadca357c/pkg/kubectl/cmd/expose.go#L158-L170) works [like](https://github.com/openshift/origin/blob/03ae3344f1722c3f42dace7516962d0ec8c58109/pkg/route/generator/generate.go#L85) that (the named or number port comes from the service). And that's the main reason behind observing this bug. 

From my understanding, routes bypass services and route directly to the endpoints. I think that what you are asking for is to change the way route ports work (oc expose doesn't have to do anything with such a change).

**Comment by liggitt** [comment]
> oc expose already works like that (the named or number port comes from the service)

Isn't `oc expose` using the serviceport's `targetPort`? That is what won't work for named target ports... `oc expose` should be setting the route's `targetPort` to the serviceport's name.

**Comment by liggitt** [comment]
The service port's name is what appears in the endpoint, not the container port's name.

**Comment by liggitt** [comment]
For example, after creating the resources in https://gist.github.com/liggitt/4b71c07b8c69ab7eabbe:

This will work, but will not pick up changes to the service definition if the service starts targeting a different port (I would expect the route to do `targetPort: "svcportname"`):
```
$ oc expose service named-6060-8080
route "named-6060-8080" exposed
$ oc get route named-6060-8080 -o yaml
apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: 2015-12-11T17:45:09Z
  name: named-6060-8080
  namespace: port-test
  resourceVersion: "2221"
  selfLink: /oapi/v1/namespaces/port-test/routes/named-6060-8080
  uid: ec5da7d0-a02e-11e5-bfed-3c970e4b7ffe
spec:
  host: named-6060-8080-port-test.router.default.svc.cluster.local
  port:
    targetPort: "8080"
  to:
    kind: Service
    name: named-6060-8080
status: {}
```

This will not work... I would expect the route to do `targetPort: "svcportname"`:
```
$ oc expose service named-6060-named
route "named-6060-named" exposed
$ oc get route named-6060-named -o yaml
apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: 2015-12-11T17:45:25Z
  name: named-6060-named
  namespace: port-test
  resourceVersion: "2224"
  selfLink: /oapi/v1/namespaces/port-test/routes/named-6060-named
  uid: f5e179d3-a02e-11e5-bfed-3c970e4b7ffe
spec:
  host: named-6060-named-port-test.router.default.svc.cluster.local
  port:
    targetPort: podportname
  to:
    kind: Service
    name: named-6060-named
status: {}
```

**Comment by kargakis** [comment]
> The service port's name is what appears in the endpoint, not the container port's name.

Right, now I see what you are saying. I will have a look on Monday, no more brainpower left.

**Comment by thincal** [comment]
- if a route has a numeric targetPort, that matches the containerport number.
- if a route has a named targetPort, that matches the serviceport name (NOT the containerport name)

but, if a route without the targetPort, which port will be matched if the service/pod with more than one port defined ? thanks.

**Comment by liggitt** [comment]
The route round-robins among all the service ports.

**Comment by thincal** [comment]
if there are more than one port could serve the request, which will be selected eventually ? just randomly ?

**Comment by liggitt** [comment]
It is effectively random, yes. That behavior is probably not what you want... in most cases, the route should target a specific port

**Comment by gWOLF3** [comment]
I can confirm that this is still an issue. The actual behavior does not match the expected, and doesn't make sense. If we define a targetPort: <name>, that should match to a containerPort name on the pod.

**Comment by k79e** [comment]
Yes. Same too. IDK why but I viewed the service port from container and find that it's can connect.
So it's not caused by connection problem of services.

**Comment by k79e** [comment]
> if a route has a numeric targetPort, that matches the containerport number.
> if a route has a named targetPort, that matches the serviceport name (NOT the containerport name)

But when create route from web console the number port selected is the service port.
e.g the page shows 80->1234 then route use 80 port of service.
