### ISSUE TITLE
Test flake in integration test suite

### ISSUE THREAD

**Issue by miminar** [openshift/origin#6270]
`TestAuthorizationSubjectAccessReview` yields:

     I1211 10:38:41.309103    8918 create_clientcert.go:52] Creating a client cert with: admin.CreateClientCertOptions{SignerCertOptions:(*admin.SignerCertOptions)(0xc2080fc240), CertFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.key", User:"system:openshift-registry", Groups:[]string{"system:registries"}, Overwrite:false, Output:(*os.File)(0xc208068010)} and &admin.SignerCertOptions{CertFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/ca.key", SerialFile:"/tmp/openshift-integration/openshift.local.config/master/ca.serial.txt", lock:sync.Mutex{state:0, sema:0x0}, ca:(*crypto.CA)(0xc208311140)}
    I1211 10:38:41.421921    8918 create_clientcert.go:70] Keeping existing client cert at /tmp/openshift-integration/openshift.local.config/master/openshift-registry.crt and key at /tmp/openshift-integration/openshift.local.config/master/openshift-registry.key
    I1211 10:38:41.421946    8918 create_kubeconfig.go:132] creating a .kubeconfig with: admin.CreateKubeConfigOptions{APIServerURL:"https://127.0.0.1:12000", PublicAPIServerURL:"https://127.0.0.1:12000", APIServerCAFile:"/tmp/openshift-integration/openshift.local.config/master/ca.crt", CertFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.crt", KeyFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.key", ContextNamespace:"default", KubeConfigFile:"/tmp/openshift-integration/openshift.local.config/master/openshift-registry.kubeconfig", Output:(*os.File)(0xc208068010)}
    I1211 10:38:41.534274    8918 create_kubeconfig.go:200] Generating 'system:openshift-registry/127-0-0-1:12000' API client config as /tmp/openshift-integration/openshift.local.config/master/openshift-registry.kubeconfig
    F1211 10:38:51.992474    8918 etcd.go:38] Unable delete key: 100: Key not found (/openshift.io) [1009]

Found at:

- [build 7748](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7748/console)
- [build 7590](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7590/console) 
- [build 7577](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7577/console)

**Comment by bparees** [comment]
seen again here:
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4307/console

**Comment by kargakis** [comment]
We already have an issue for that test: https://github.com/openshift/origin/issues/6065

If you spot a different flake for the same test just menion it in there.

**Comment by miminar** [comment]
@kargakis OK, will do.

Closing in favor of #6065.
