### ISSUE TITLE
Promote experimental commands into oadm

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6276]
Forgot to do this :)

Bunch of experimental commands are stable now.

**Comment by smarterclayton** [comment]
Has docs impact, we have to leave the old alias for one release

**Comment by deads2k** [comment]
I see `sync-groups` and `prune-groups`.  `openshift ex validate master-config` and `openshift ex validate node-config` would be good.  Do we want to claim `oadm validate *` for them?

**Comment by deads2k** [comment]
@stevekuznetsov the groups ones are pretty clear.  We already have `oadm groups` as a subcommand to drop them under.

**Comment by smarterclayton** [comment]
Other discussion point - moving everything in oadm into "oc cluster *"

**Comment by stevekuznetsov** [comment]
@deads2k We are changing the naming, then, are we? From `verb-noun` to just `verb`?

```
$ oadm groups sync
$ oadm groups prune
```
??

**Comment by deads2k** [comment]
> @deads2k We are changing the naming, then, are we? From verb-noun to just verb?

yeah, that makes sense.

**Comment by deads2k** [comment]
> Other discussion point - moving everything in oadm into "oc cluster *"

I like `oadm` better.  Why would we move it?

**Comment by smarterclayton** [comment]
oadm would be a symlink to oc admin or something so we could reduce to one
client binary.

**Comment by pweil-** [comment]
downgrade in priority based on convo with @stevekuznetsov

**Comment by smarterclayton** [comment]
Why?

**Comment by smarterclayton** [comment]
Need reasons

**Comment by stevekuznetsov** [comment]
@smarterclayton no migration/promotion of `openshift ex validate` commands needs to occur. We decided that `oadm validate` was not correct and that these commands should live as targets for `openshift ex diagnostics`. In parallel to my original build of `openshift ex validate`, `openshift ex diagnostics` maintainer @sosiouxme built node/master config validation targets for `openshift ex diagnostics`. Therefore, the only action to be taken is to add deprecation messages to `openshift ex validate` commands and point them to the correct invocation of `openshfit ex diagnostics`.

**Comment by smarterclayton** [comment]
What about all the other ex commands?

**Comment by stevekuznetsov** [comment]
@smarterclayton `openshift ex {sync,prune}-groups` was promoted already.

**Comment by smarterclayton** [comment]
And diagnostics?

**Comment by deads2k** [comment]
> And diagnostics?

Do you think that one is ready?

**Comment by stevekuznetsov** [comment]
As written by @deads2k [here](https://github.com/openshift/origin/issues/6276#issuecomment-164451302), `openshift diagnostics` was not listed as a command in need of promotion.

**Comment by deads2k** [comment]
As a for instance, I think the command arguments should be changed, dropping the `--diagnostics` flag.  (See https://github.com/openshift/origin/pull/6634).  I'm pretty sure I'm allowed to drop the flag in `openshift ex`, but not in `oadm`, right?

**Comment by smarterclayton** [comment]
Diagnostics should be moved out of experimental - as long as we think the arguments pattern is right.  If we still want to tweak arguments it can miss 3.1.1

**Comment by smarterclayton** [comment]
Yes,  we can wait for 1.2 to promote it.

On Jan 13, 2016, at 1:43 PM, David Eads <notifications@github.com> wrote:

As a for instance, I think the command arguments should be changed,
dropping the --diagnostics flag. (See #6634
<https://github.com/openshift/origin/pull/6634>). I'm pretty sure I'm
allowed to drop the flag in openshift ex, but not in oadm, right?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/6276#issuecomment-171393718>.

**Comment by smarterclayton** [comment]
This is p1, but all that is left is diagnostics.  Assigning to Luke.

**Comment by kargakis** [comment]
> This is p1, but all that is left is diagnostics. Assigning to Luke.

I still see a bunch of them under /experimental
https://github.com/openshift/origin/tree/master/pkg/cmd/experimental

**Comment by sosiouxme** [comment]
On Tue, Feb 23, 2016 at 12:34 PM, Michail Kargakis <notifications@github.com
> wrote:
>
> I still see a bunch of them under /experimental
> https://github.com/openshift/origin/tree/master/pkg/cmd/experimental
>

I think all will remain for backward compatibility, but most should
probably have deprecation notices and pointers to new location, and I don't
see that for anything but `validate` and (now) `diagnostics`. I can do that
if desired...

**Comment by sosiouxme** [comment]
https://github.com/openshift/origin/issues/7563 merged, is there more to do?

**Comment by deads2k** [comment]
> #7563 merged, is there more to do?

No.  `build-chain` is the only other likely candidate, but we're still talking about a graph API, so I don't see us wanting to promote it yet.

@smarterclayton I want to kill `openshift ex tokens validate-token` (replaced by `oc whoami`) and `openshift ex tokens request-token` (replaced by `oc login`).  Objections?
