### ISSUE TITLE
new-app fails on some official Docker images due to chown permissions

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6282]
We mount a volume at /data, but when the process tries to chown it, it fails.  Looks like the directory for data is root owned?

```
$ ls -al /data/src/github.com/openshift/origin/openshift.local.volumes/pods/131ee968-a095-11e5-8318-080027c5bfa9/containers/redis/5e4b5196bc15d1057f00152dcdfb0884fe514cc9decc2588860117f1a8f6b5e2
-rw-r--r--. 1 root root 0 Dec 12 05:58 /data/src/github.com/openshift/origin/openshift.local.volumes/pods/131ee968-a095-11e5-8318-080027c5bfa9/containers/redis/5e4b5196bc15d1057f00152dcdfb0884fe514cc9decc2588860117f1a8f6b5e2
```

even though the image is not started that way.  This is v1.1 - I thought we fixed this?

@pmorie @markturansky

**Comment by kargakis** [comment]
cc: @mnagy

**Comment by bparees** [comment]
image reports:
`chown: changing ownership of `.': Operation not permitted`

I forget how empty dir is supposed to work..I though it was 777 but possibly root owned, which would still preclude chown operations, so this might be working as designed, but will let @pmorie and @markturansky weigh in.

**Comment by markturansky** [comment]
@bparees the security implementation and its details is @pmorie and @swagiaal's domain.

AFAICT, it looks like 777 is used when the emptyDir is created but kubelet running as root would own the dir.  I don't see any chown in emptyDir to change that.

**Comment by smarterclayton** [comment]
Is there a reason why I would want it to be owned by root?  I would assume
it would be owned by FSGroup at a minimum.  What problems occur if it's not
root owned?

**Comment by pmorie** [comment]
@smarterclayton you're looking at the wrong dir -- that's the overall volumes dir for the pod -- what's inside that dir?

**Comment by smarterclayton** [comment]
I don't know, try this locally and tell me why it fails :)

**Comment by markturansky** [comment]
I don't have sufficient permissions to reassign this issue.  Please reassign to @pmorie or @swagiaal, as they are the security feature owners.

**Comment by smarterclayton** [comment]
MySQL and mongodb from the DockerHub are also broken in the same fashion.

**Comment by smarterclayton** [comment]
@bparees @pweil- @pmorie I'd like to have a strategy to get this resolved.  At this point, every default DockerHub image that uses volumes is broken on OpenShift v3.  That's untenable to me.

**Comment by bparees** [comment]
Seems like the logical behavior i'd expect as a user is:

Any dir i specified as a volume mount point in my podtemplate, should be owned by, and writable by, the pod user id. 

Are there storage systems or scenarios under which that is not a rational assumption, or where that behavior is not possible?

Naive questions that would apply to persistent volume behavior:
1) do all the containers in a pod share the same userid?  (would the above behavior allow all pods to write to a PV)
2) if a pod stops/starts/moves, do its containers keep the same userid?  (if the pod moves/restarts, can it still write to its PV?)
3) do all pods in a replica cluster share the same uid?  (can all pods in a cluster write to the PV, which is mounted to/shared between all of them?)

**Comment by smarterclayton** [comment]
1. Containers can have different uids, but if there is only one container
the behavior is obvious
2. Yes
3. Yes

**Comment by bparees** [comment]
(1) sounds like a problem.  doesn't it imply that if i have two containers in a pod, they can't both write to the PV (unless the PV has global write permissions set)?  That feels pretty restrictive.

**Comment by smarterclayton** [comment]
That's what FSGroup is for.

**Comment by bparees** [comment]
and just to followup on a side discussion @smarterclayton and I had...  having group permissions on a dir does not enable you to chown that dir, so if you need to be the user-owner of a directory (as postgres requires), having group permissions isn't sufficient.

(we work around this today by creating a directory that we *do* own, within the mounted directory, but most images don't do that)

**Comment by pmorie** [comment]
I spent a fair amount of time looking at this yesterday.  I think the issue with both redis and postgresql is that they require root to run.  Both do a chown as root and then su to the package-specific uid.  Will confirm these work and report back.

**Comment by smarterclayton** [comment]
And because the emptydir volume directory is mounted as root owned, they're
broken.  So how do we unbreak them.  Why would a volume not be owned by the
launching container user?

**Comment by pmorie** [comment]
I should have been more specific with my comments:

Both the redis and postgres Dockerhub image rely on being root _and_ the volume they use being root-owned so that:

1.  They can do a chown _as root_ on the volume to the ownership they want (postgresql:root or redis:redis)
2.  They both then su to the uid they expect to run as

This is really tricky to unwind because the images both effectively need:

1.  Root
2.  Some other UID

...and run as both of those as different times.  That being the case, is saying that you need to be able to use an SCC that allows your to run as root an acceptable story to unbreak users that are trying to use these images?

**Comment by smarterclayton** [comment]
So they don't chown to themselves, but to another user altogether?

**Comment by pmorie** [comment]
@smarterclayton Correct, see:

1.  https://github.com/docker-library/postgres/blob/2c72165e4f9dc66a61998111f69b5eba0b6b71f4/9.5/Dockerfile#L5
2.  https://github.com/docker-library/postgres/blob/2c72165e4f9dc66a61998111f69b5eba0b6b71f4/9.5/Dockerfile#L39
3.  https://github.com/docker-library/postgres/blob/2c72165e4f9dc66a61998111f69b5eba0b6b71f4/9.5/docker-entrypoint.sh#L12
4.  https://github.com/docker-library/postgres/blob/2c72165e4f9dc66a61998111f69b5eba0b6b71f4/9.5/docker-entrypoint.sh#L94

**Comment by smarterclayton** [comment]
So yes, safe w/ caps as the default removes this, but then the fallback is
ensuring people know this isn't running as root (even though it thinks it
will)

**Comment by pmorie** [comment]
@smarterclayton I wonder if we can provide some programmatic help for specific packages -- is it worth a whitelist to notify about?

**Comment by pmorie** [comment]
We could provide an SCC to enable that gives you the right settings for dockerhub images like this.

**Comment by pmorie** [comment]
I verified that `oc new-app redis` ran correctly when the service account for the project was granted use of the `anyuid` SCC.

**Comment by pmorie** [comment]
Also had success to `oc new-app postgres` on anyuid SCC

**Comment by jeffvance** [comment]
Does this issue turn into a doc issue? Or are there code changes needed?

**Comment by pmorie** [comment]
@jeffvance I think it mostly does; basically the TL;DR is that if you want to run images from dockerhub, the service account you use for them needs to be able to use the `anyuid` SCC.  I'll make a change to the docs to reflect this.

**Comment by smarterclayton** [comment]
oc status now reports crash looping pods and offers this as a suggestion (oadm policy add-scc-to-user anyuid -z ...).  I'm also going to consider adding liveness check for ports for things that don't obviously fail.

**Comment by smarterclayton** [comment]
I'm seeing other problems after that on `mysql` - haven't had time to dig
in, but still doesn't look like it's enough.

**Comment by smarterclayton** [comment]
So going back to the regular volume case, in debugging a larger set of images I'm continually frustrated that my containers (running as non-root) don't have writable empty dir volumes.  It's a level of control that I as a user would expect to have.

The case against empty dir owned by the container user came down to conflicts between containers (multiple containers, multiple users), but ultimately that's a 1-2% case.  If we had a flag for it, I'd have new-app and all our templates set it (because it reduces the friction in the images).  Which means that the correct default behavior would probably be to always set it, and have something sane happen in the case where no user can be determined (root).

**Comment by dothebart** [comment]
Hi, any progress on this? since if you run a database like https://github.com/arangodb/arangodb you definitely want to mount a volume into the container, and in most cases don't want to run its services as root - thus it has to have proper access rights.
