### ISSUE TITLE
Warning about restarting pod should show up next to DC in oc status

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6289]
The current "pod has restarted X times" warning isn't very useful in oc status.  It needs to be connected to the actual DC that it's under.

```
$ oc status -v
In project default on server https://10.1.2.2:8443

svc/docker-registry - 172.30.213.112:5000
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:v1.1 
    #1 deployed 11 minutes ago - 1 pod

svc/kubernetes - 172.30.0.1 ports 443, 53, 53

Warnings:
  * container "registry" in pod/docker-registry-1-d49us has restarted 53 times

To see more, use 'oc describe <resource>/<name>'.
You can use 'oc get all' to see a list of other objects.
```

should probably be

```
$ oc status -v
In project default on server https://10.1.2.2:8443

svc/docker-registry - 172.30.213.112:5000
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:v1.1 
    #1 deployed 11 minutes ago - 1 pod (warning: 53 restarts)

svc/kubernetes - 172.30.0.1 ports 443, 53, 53

Warnings:
  * container "registry" in pod/docker-registry-1-d49us has restarted 53 times

To see more, use 'oc describe <resource>/<name>'.
You can use 'oc get all' to see a list of other objects.
```

or even:

```
$ oc status
In project default on server https://10.1.2.2:8443

svc/docker-registry - 172.30.213.112:5000
  dc/docker-registry deploys docker.io/openshift/origin-docker-registry:v1.1 
    ! #1 deployed 11 minutes ago - 1 pod (warning: 53 restarts)

svc/kubernetes - 172.30.0.1 ports 443, 53, 53
```

**Comment by deads2k** [comment]
Now that we have markers and we have warnings, do we want to start colorizing or marking various parts of the status in yellow or something other indicator to make it clear that something is wrong with this resource?

@kargakis @jwforres @fabianofranz

**Comment by kargakis** [comment]
I think colorizing would be really helpful.

**Comment by smarterclayton** [comment]
No colors yet.

**Comment by fabianofranz** [comment]
> No colors yet.

Meaning we don't want colors yet? There is https://github.com/openshift/origin/issues/4183 as a P2.

**Comment by fabianofranz** [comment]
@deads2k do we have an indication (an attribute or something) in the parent nodes that specify there are problems in lower nodes of the tree? For example, do I know in a service that it has dc's with failed deployments (without traversing the tree)?

**Comment by deads2k** [comment]
> @deads2k do we have an indication (an attribute or something) in the parent nodes that specify there are problems in lower nodes of the tree? For example, do I know in a service that it has dc's with failed deployments (without traversing the tree)?

There are rollup objects in the `graphview` package, but we haven't used them to track state of lower level items yet.

**Comment by mfojtik** [comment]
I will look at this today
