### ISSUE TITLE
`test-go` should recursively test all packages under the specifed package

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6295]
When I specify a package as an argument to `hack/test-go.sh` I want to test *all* packages under whatever root path I just gave.

@deads2k @liggitt @smarterclayton do you think this is reasonable and/or expected behavior? If so I'll implement it.

**Comment by deads2k** [comment]
I don't want this.  It would make it harder for me to test just the package that I'm interested in looking at.  I'm ok with some sort of `pkg/foo/*` format, but I don't want to unconditionally find all subpackages.

**Comment by stevekuznetsov** [comment]
Fair enough. Could we use some sort of `-r` or `RECURSIVE=true` syntax to allow people to express when they want this functionality?

**Comment by deads2k** [comment]
Could you pipe their argument to find and use that to support  the star syntax?

**Comment by smarterclayton** [comment]
The format for testing all things under a package in Go is `pkg/foo/...`

**Comment by stevekuznetsov** [comment]
:+1: for `...`. That should be easy to do.

**Comment by deads2k** [comment]
> The format for testing all things under a package in Go is `pkg/foo/...`

I had no idea that was a thing.

**Comment by rhcarvalho** [comment]
Certainly shouldn't be recursive by default. The `...` syntax would be fine :+1:
