### ISSUE TITLE
Issue running docker one-liner

### ISSUE THREAD

**Issue by cdrage** [openshift/origin#6314]
While runnning:
```
[root@localhost ~]# docker run -d --name "origin" \
>         --privileged --pid=host --net=host \
>         -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw \
>         -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes \
>         openshift/origin start
```
On a brand-new CentOS (or CoreOS or Debian) box with just Docker integrated, for some-odd reason I get this when going to:

vps-ip:8443

![image](http://i.imgur.com/JMZdTQ8.png)

Sorry if this has already been taken care of, quite hard to Google the rror when all you see is random  characters, haha

**Comment by liggitt** [comment]
Probably want to add https://

**Comment by cdrage** [comment]
@liggitt damnit, you're right :( I swear a version before hand of openshift had auto-forwarding from http to https.

many thanks! :)
