### ISSUE TITLE
Increase test coverage in the cli

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#6316]
We should have unit tests for the [cli](https://github.com/openshift/origin/tree/master/pkg/cmd/cli/cmd) that would use fake clients and cover every possbile path. Bugs like https://github.com/openshift/origin/issues/6312 would have been found much sooner.

**Comment by mfojtik** [comment]
+1

**Comment by guilhermebr** [comment]
The coverage of cli is 9.9%, this issue is about reach 70%?
I'm starting with openshift and write tests is a good way to understand the project.
So I can do this issue.

**Comment by liggitt** [comment]
I don't think the existing coverage is well-measured... test-cmd.sh tests a ton of scenarios, and I don't think coverage is computed from that

**Comment by guilhermebr** [comment]
Sure this is only the coverage of unit tests in pkg/cmd/cli/cmd folder.
I will look at the tests inside of test-cmd.sh and try to put some of them as a go_test.
I say 70% of coverage just to know the acceptance criteria for this issue.

**Comment by dwinchell** [comment]
I would like to help with this. I am new to OpenShift and looking for ways to get involved.

**Comment by juanvallejo** [comment]
/remove-lifecycle stale

Hi @dwinchell thanks for wanting to help with this. 
You could get started by taking a look at a few of our "test-cmd" tests which live as shell scripts under `test/cmd` (you can run a specific test via `./hack/test-cmd.sh annotations`, for example). If you see a particular test that could be feasibly converted into a unit test, most command unit tests live under `pkg/oc/cli/cmd/`. Feel free to ping me if you have any questions

**Comment by dwinchell** [comment]
Great, thanks @juanvallejo. I will take a look.

I have another project in the works so it might be a week or so before I follow up, but I will do so!

**Comment by dwinchell** [comment]
Hey guys, sorry for the long silence on this. My day job needed some extra cycles after I volunteered.

I am looking at it now.

What does "/sig master" mean? Should I still be working on this?

Thanks!

**Comment by kargakis** [comment]
oc is owned by the master team and I am satisfying my inner librarian by
labeling this issue as such. Feel free to work on it though! I know
@soltysh will be happy about it :)

**Comment by dwinchell** [comment]
Ah, got it. Thanks :)

**Comment by dwinchell** [comment]
I just wanted to close the loop on this. Obviously I have not gotten a chance to do it. Sorry. 

I would love to contribute in general, but realistically I should say that I will not have the cycles in the near future.

Best

**Comment by soltysh** [comment]
@dwinchell you're always welcome, if you find some time :)
