### ISSUE TITLE
no-reply@rhcloud.com sending empty email 2 per min #bug

### ISSUE THREAD

**Issue by iamkdev** [openshift/origin#6334]
Please check whats wrong. I am getting empty emails from "no-reply@rhcloud.com" twice per min.

**Comment by mfojtik** [comment]
@iamkdev can you tell us more details? Do you run openshift v3 or this is openshift v2?

**Comment by iamkdev** [comment]
I guess it is v2 ( early adopters ). I am using openshift online free plane....
This is one of the app ....blog-iamkdev.rhcloud.com.
I think some issue there that's why it sending continuously...

**Comment by bparees** [comment]
what is the content of the emails?

**Comment by bparees** [comment]
(this issue should really be opened as a bugzilla bug against v2, the origin repo is for v3, not v2 issues)

**Comment by iamkdev** [comment]
Its an empty email. I forward one to rhcloud-security@redhat.com

**Comment by mfojtik** [comment]
@iamkdev and you don't have a "monit" cartridge installed by any chance?

**Comment by iamkdev** [comment]
No. Only phpMyAdmin 4.0 and Cron 1.4

**Comment by abhgupta** [comment]
@iamkdev filed a bug for the issue you have been facing --> https://bugzilla.redhat.com/show_bug.cgi?id=1313947

**Comment by abhgupta** [comment]
We have filed a bug for the issue --> https://bugzilla.redhat.com/show_bug.cgi?id=1313947

**Comment by tiwillia** [comment]
@iamkdev could you add yourself to the bugzilla? These emails are most likely coming from your app, as apps by default will send email from 'no-reply@rhcloud.com'. Would it be possible for you to temporarily stop your app and see if the emails persist?

We'd like to continue further discussion on this issue in the bugzilla, since this is the incorrect github repository.

**Comment by iamkdev** [comment]
Thanks, I am really happy with the respond that I got. I didn't expected this kind of respond for Free Plan. 
I closed this issue as I deleted the affected application( I do created that again ) and since then I am not receiving any email.

**Comment by abhgupta** [comment]
Sounds good - will close the bug as well. Feel free to re-open the bug with details if the issue resurfaces.
