### ISSUE TITLE
Flake in test/cmd/builds.sh: oc cancel-build build/ruby-sample-build-1

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6339]
seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7860 run from https://github.com/openshift/origin/pull/6330:
```
Running hack/../test/cmd/builds.sh:113: executing 'oc cancel-build build/ruby-sample-build-1' expecting any result and text 'A cancellation event was already triggered for the build ruby-sample-build-1.'; re-trying every 0.2s until completion or 60.000s...
FAILURE after 59.535s: hack/../test/cmd/builds.sh:113: executing 'oc cancel-build build/ruby-sample-build-1' expecting any result and text 'A cancellation event was already triggered for the build ruby-sample-build-1.'; re-trying every 0.2s until completion or 60.000s: the output content test failed
Standard output from the command:
A build can be cancelled only if it has new/pending/running status.
A build can be cancelled only if it has new/pending/running status.
A build can be cancelled only if it has new/pending/running status.
A build can be cancelled only if it has new/pending/running status.
A build can be cancelled only if it has new/pending/running status.
A build can be cancelled only if it has new/pending/running status.
```

**Comment by smarterclayton** [comment]
I thought we had a known flake here @bparees on cancelling builds too fast.

**Comment by bparees** [comment]
doesn't ring a bell, and the above code is retrying for 60s, so it seems like the build never got created or got created and immediately failed, making it non-cancellable.

oc cancel-build should probably dump the current state of the build as part of the error message, that would tell us more about why cancel is failing.

**Comment by smarterclayton** [comment]
The error message is also scarier than it should be.

**Comment by bparees** [comment]
> The error message is also scarier than it should be.

how so?

**Comment by smarterclayton** [comment]
"A build can be cancelled only if it has new/pending/running status." ->
"Build %s is complete and cannot be cancelled". Also, I'm not sure that's
an error - that a no-op (like deleting something that doesn't exist).

**Comment by liggitt** [comment]
was a race condition... if the cancellation was acted on quickly enough, the message would change to "must be in pending/running state"
