### ISSUE TITLE
Automate CONTRIBUTING vagrant steps and decouple cloud vs local-dev

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#6340]
Openshift dev tooling is pretty nice, Im going to propose a minor simplification.  Most of the bits are there, but there might be some redundancys.

i suggest.
- Move the top level vagrantfile to a `vagrant/cloud` directory,  specific to cloud deployment (ec2/openstack), and  comment it as such.
- We Make a 2nd vagrantfile for local development which handles the local steps, and put it in some obvious place (`vagrant/local`).  This file should obviate all the manual steps in `Develop on virtual machine using Vagrant`... so we can remove them from the doc and maintain them 'as code'.

Just some thoughts.  @danmcp  feedback?  Or maybe im overthinking it  and everything is ok as is :).

**Comment by danmcp** [comment]
@jayunit100 2 initial thoughts:

1) The current vagrantfile isn't really targeted at a cloud user (and the cloud user cases also largely fit into the local user use cases).  It's sort of the LCD between three groups:
  a) Someone getting started using OpenShift
  b) Generic starting point for running tests or demos
  c) Longer term development
2) I would be really worried about getting someone to test and maintain the two different files for each new change that comes in

So are you trying to make 1a) or 1b) better?
1a) should probably be solved longer term by the CDK
1b) is a big part of finding the LCD today as many people don't want too opinionated of a starting point.

What I would personally be most interested in seeing improved is whether we can make any of the initial setup steps incrementally easier or more obvious.

-Dan

**Comment by jayunit100** [comment]
(b) and (c) are the most important i think since openshift.com is there for (a).

I think I might be overthinking it.  lets keep working with the existing Vagrantfile. 
I have a PR on the way so that VBox deploys everything from zero, it also patches an issue that pops up w/ openstack plugin.

**Comment by jayunit100** [comment]
Closing in favor of https://github.com/openshift/origin/issues/6549
