### ISSUE TITLE
Service link on route page doesn't link to service

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6342]
This link is wrong. It links back to the route you're already looking at.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/11844275/df3f8702-a3db-11e5-8fc2-12d0e8a3dbe2.png)

@jwforres Please assign to me. I'm working in this code already.

**Comment by jwforres** [comment]
@spadgett also looks like a duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1291559
