### ISSUE TITLE
Replace fixed sleep with polling when attaching to a deployment

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#6344]
https://github.com/openshift/origin/blob/0d4de0b1801e8c58a28c8bcd9d12b5d0c46de1cb/pkg/cmd/util/clientcmd/factory.go#L327 uses a fixed sleep. We should switch to a (configurable?) interval and poll.

@deads2k @fabianofranz

**Comment by fabianofranz** [comment]
Yes. Maybe something like `wait.PollImmediate` and/or a piece in [pkg/client/unversioned/conditions.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/conditions.go). Replication controllers use something similar upstream, should also be fixed.

**Comment by kargakis** [comment]
Another thing I just noticed is that currently this will poll forever on a failed deployment, right? 
```go
var deployment *deployapi.DeploymentConfig
var err error
for deployment == nil || /* deployment is not Complete */ {
		// GET DC
		latestDeploymentName := deployutil.LatestDeploymentNameForConfig(t)
		deployment, err = kc.ReplicationControllers(t.Namespace).Get(latestDeploymentName)
		if err != nil {
		      if kerrors.IsNotFound(err) {
			     continue
		      }
		      return nil, err
		}
       // Look into annotations and break out when this deployment is in Complete state
       // Also ensure that rc.Spec.Replicas > 0
}
pods, err = kc.Pods(deployment.Namespace).List(labels.SelectorFromSet(t.Spec.Selector), fields.Everything())
if err != nil {
	return nil, err
}
```
And then add the polling mechanism we want.
