### ISSUE TITLE
oc new-app doesn't work with custom branch

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6345]
The help gives an example:

```console
$ oc new-app --help
...                                                  
  # Create an application from a remote repository using its beta4 branch  
  $ oc new-app https://github.com/openshift/ruby-hello-world#beta4         
...
```

But it doesn't work:

```console
$ oc new-app https://github.com/openshift/ruby-hello-world#beta4
error: no match for "https://github.com/openshift/ruby-hello-world#beta4", specify --allow-missing-images to use this image name.

The 'new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet
or is only on the local system.

See 'new-app' for examples.
```

And blindly following the advice of "--allow-missing-images" leads to even more confusion:

```console
$ oc new-app https://github.com/openshift/ruby-hello-world#beta4 --allow-missing-images                                                                                      
error: can't include "https://github.com/openshift/ruby-hello-world#beta4": can't include "https://github.com/openshift/ruby-hello-world#beta4": the docker pull spec "https://github.com/openshift/ruby-hello-world#beta4" must be two or three segments separated by slashes
```

**Comment by rhcarvalho** [comment]
cc @php-coder

**Comment by php-coder** [comment]
Should work if you explicitly specify the builder, like this:
```shell
oc new-app ruby~https://github.com/openshift/ruby-hello-world#beta4
```

**Comment by smarterclayton** [comment]
> $ oc new-app https://github.com/openshift/ruby-hello-world#beta4
> error: no match for "https://github.com/openshift/ruby-hello-world#beta4", specify --allow-missing-images to use this image name.

Is definitely a bug.

**Comment by bparees** [comment]
yeah it's clearly gone down the wrong path and is thinking the argument is an image name rather than a git repo.

**Comment by bparees** [comment]
since I assume this is a regression, marking p1.

**Comment by sudhaker** [comment]
I got this error when "git" package was missing from the system. Got resolved after git was installed.

**Comment by bparees** [comment]
the root issue in this case was that the # syntax was not being handled correctly.  the behavior when git is not installed may be a different problem, we should probably do a better job of warning you that we couldn't clone your repository for inspection, making all recommendations/operations dubious.

**Comment by smarterclayton** [comment]
I thought we had a warning at one point but I may be thinking about
the older generate command

**Comment by abdulrashidkhan05** [comment]
Issue while running from outside need to local terminal end... Run from Open Shift terminal, got this error while running from local terminal 
#################################################################################################
  2026-07-09   18:01.59   /home/admin  oc new-app https://github.com/openshift/ruby-hello-world#beta4
error: cloning repository "https://github.com/openshift/ruby-hello-world" to "C:\\Users\\admin\\AppData\\Roaming\\MobaXterm\\slash\\mx86_64b\\tmp\\gen3320801370" failed: fatal: Invalid path '/drives/c/Users/admin/AppData/Roaming/MobaXterm/home/C:/Users': No such file or directory
##################################################################################################

**Executed successfully while running direct from OpenShift Terminal**

  2026-07-10   04:38.47   /home/admin  oc logs -f buildconfig/ruby-hello-world

Cloning "https://github.com/openshift/ruby-hello-world.git" ...
        Commit: 394e0f7c0446d65d163ecae9cf5b559ad60de6dd (Merge pull request #63 from bparees/dropjenkins)
        Author: Ben Parees <bparees@users.noreply.github.com>
        Date:   Wed Nov 29 11:57:56 2017 -0500
Replaced Dockerfile FROM image centos/ruby-22-centos7
time="2026-07-09T23:00:15Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
I0709 23:00:15.829339       1 defaults.go:112] Defaulting to storage driver "overlay" with options [mountopt=metacopy=on].
Caching blobs under "/var/cache/blobs".

Pulling image centos/ruby-22-centos7@sha256:a18c8706118a5c4c9f1adf045024d2abf06ba632b5674b23421019ee4d3edcae ...
Resolving "centos/ruby-22-centos7" using unqualified-search registries (/var/run/configs/openshift.io/build-system/registries.conf)
Trying to pull registry.redhat.io/centos/ruby-22-centos7@sha256:a18c8706118a5c4c9f1adf045024d2abf06ba632b5674b23421019ee4d3edcae...
Trying to pull registry.access.redhat.com/centos/ruby-22-centos7@sha256:a18c8706118a5c4c9f1adf045024d2abf06ba632b5674b23421019ee4d3edcae...
Trying to pull quay.io/centos/ruby-22-centos7@sha256:a18c8706118a5c4c9f1adf045024d2abf06ba632b5674b23421019ee4d3edcae...
Trying to pull docker.io/centos/ruby-22-centos7@sha256:a18c8706118a5c4c9f1adf045024d2abf06ba632b5674b23421019ee4d3edcae...
Getting image source signatures
Copying blob sha256:a2c26223d84a4efc918e010f7de2b903c0aebc901b669be127e4d60ea5bb7f2b
Copying blob sha256:3198ba1a52956d97ff53912cfbd20cc333fef02bb0bf0dabf32659af1ea6d272
Copying blob sha256:f55f016bb97cae4fab16eefa5f65b85f3112ce9758614d3b308f4f55e280d9d3
Copying blob sha256:469cfcc7a4b3947a4fa549c68cf4f8570be53779725f0c19f3d33d1520b08db0
Copying blob sha256:e11c8e053fb5d1761f80fbfe7369765ecf2942fb2d975d3dd1d2792fcd8cabbd
Copying blob sha256:46db36153229f0c3ccba1a4e75169c8d20db2d17aa46c7cfd8877a0357a72e39
Copying blob sha256:296548fd899888385195c38cd1b5f3fa6443abe35c4169de2fdb104f70007afe
Copying blob sha256:d71b2d9b1cd31f28ce83322703f7ab706a35255bbcd419a3e95c2e895bd5f681
Copying blob sha256:a38d357764a3aa20c2241433436db6cc24ea898a7f3c0904d66ca2323f302123
Copying config sha256:e42d0dccf073123561d83ea8bbc9f0cc5e491cfd07130a464a416cdb99ced387
Writing manifest to image destination
Adding transient rw bind mount for /run/secrets/rhsm
STEP 1/13: FROM centos/ruby-22-centos7@sha256:a18c8706118a5c4c9f1adf045024d2abf06ba632b5674b23421019ee4d3edcae
STEP 2/13: USER default
--> 447252b605a4
STEP 3/13: EXPOSE 8080
--> db2f0cdff2a3
STEP 4/13: ENV RACK_ENV production
--> ba4440cec9f9
STEP 5/13: ENV RAILS_ENV production
--> 4939bb6b3e91
STEP 6/13: COPY . /opt/app-root/src/
--> 0cb2771e65da
STEP 7/13: RUN scl enable rh-ruby22 "bundle install"
Fetching source index from https://rubygems.org/
Installing rake 10.3.2
Installing i18n 0.6.11
Installing json 1.8.6
Installing minitest 5.4.2
Installing thread_safe 0.3.4
Installing tzinfo 1.2.2
Installing activesupport 4.1.7
Installing builder 3.2.2
Installing activemodel 4.1.7
Installing arel 5.0.1.20140414130214
Installing activerecord 4.1.7
Installing mysql2 0.3.16
Installing rack 1.5.2
Installing rack-protection 1.5.3
Installing tilt 1.4.1
Installing sinatra 1.4.5
Installing sinatra-activerecord 2.0.3
Using bundler 1.7.8
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
--> 16776227e00b
STEP 8/13: CMD ["scl","enable","rh-ruby22","./run.sh"]
--> 96152390f550
STEP 9/13: USER root
--> 3220bff7f8db
STEP 10/13: RUN chmod og+rw /opt/app-root/src/db
--> fc342787017d
STEP 11/13: USER default
--> 4dae4096a065
STEP 12/13: ENV "OPENSHIFT_BUILD_NAME"="ruby-hello-world-1" "OPENSHIFT_BUILD_NAMESPACE"="abdulrashidkhan05-dev" "OPENSHIFT_BUILD_SOURCE"="https://github.com/openshift/ruby-hello-world.git" "OPENSHIFT_BUILD_REFERENCE"="beta4" "OPENSHIFT_BUILD_COMMIT"="394e0f7c0446d65d163ecae9cf5b559ad60de6dd"
--> 1aa1e11e8ffc
STEP 13/13: LABEL "io.openshift.build.commit.author"="Ben Parees <bparees@users.noreply.github.com>" "io.openshift.build.commit.date"="Wed Nov 29 11:57:56 2017 -0500" "io.openshift.build.commit.id"="394e0f7c0446d65d163ecae9cf5b559ad60de6dd" "io.openshift.build.commit.message"="Merge pull request #63 from bparees/dropjenkins" "io.openshift.build.commit.ref"="beta4" "io.openshift.build.name"="ruby-hello-world-1" "io.openshift.build.namespace"="abdulrashidkhan05-dev" "io.openshift.build.source-location"="https://github.com/openshift/ruby-hello-world.git"
COMMIT temp.builder.openshift.io/abdulrashidkhan05-dev/ruby-hello-world-1:9501b5df
--> 14db3f5b31cd
Successfully tagged temp.builder.openshift.io/abdulrashidkhan05-dev/ruby-hello-world-1:9501b5df
14db3f5b31cde0da53153780ff0f0f22f3aa2e9a4907251991c5bc6ab02b587d

Pushing image image-registry.openshift-image-registry.svc:5000/abdulrashidkhan05-dev/ruby-hello-world:latest ...
Getting image source signatures
Copying blob sha256:a2c26223d84a4efc918e010f7de2b903c0aebc901b669be127e4d60ea5bb7f2b
Copying blob sha256:3198ba1a52956d97ff53912cfbd20cc333fef02bb0bf0dabf32659af1ea6d272
Copying blob sha256:46db36153229f0c3ccba1a4e75169c8d20db2d17aa46c7cfd8877a0357a72e39
Copying blob sha256:f55f016bb97cae4fab16eefa5f65b85f3112ce9758614d3b308f4f55e280d9d3
Copying blob sha256:469cfcc7a4b3947a4fa549c68cf4f8570be53779725f0c19f3d33d1520b08db0
Copying blob sha256:e11c8e053fb5d1761f80fbfe7369765ecf2942fb2d975d3dd1d2792fcd8cabbd
Copying blob sha256:296548fd899888385195c38cd1b5f3fa6443abe35c4169de2fdb104f70007afe
Copying blob sha256:d71b2d9b1cd31f28ce83322703f7ab706a35255bbcd419a3e95c2e895bd5f681
Copying blob sha256:a38d357764a3aa20c2241433436db6cc24ea898a7f3c0904d66ca2323f302123
Copying blob sha256:355097591b9011dfd3d3e0ff2b19af7208301b77a21da276986847d5d425e879
Copying blob sha256:7a953da2e04180ab17f579080ac8f5d63f3dc1c21f6a0bbceff8497c382d33af
Copying blob sha256:a6c960dda6734ca8d05253225559c875686247111b8d9ee60bcc2d154c500018
Copying config sha256:14db3f5b31cde0da53153780ff0f0f22f3aa2e9a4907251991c5bc6ab02b587d
Writing manifest to image destination
Successfully pushed image-registry.openshift-image-registry.svc:5000/abdulrashidkhan05-dev/ruby-hello-world@sha256:1c5ec49db00f5b92a32374f7f87cb3629767948fb37c47af5bc55ca8842f0ba8
Push successful
                                                                                                                                                             ✓

  2026-07-10   04:39.22   /home/admin 
