### ISSUE TITLE
Users should be aware that images that try to run as root might not work

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6348]
We need to display something informationally to end users in new-app and status that indicates that images that specify no user (USER unset) will run as root, and may not run if the administrator has a security issue.  In addition, crash looped pods should also indicate a set of common problems (or troubleshooting)

**Comment by smarterclayton** [comment]
Best option would be oc new-app spits out a message in the describe section about USER being empty.

**Comment by smarterclayton** [comment]
Warning could be "Image X expects to run as root, but your admin may not have granted permission to run as root".

**Comment by bparees** [comment]
does oc run do this?  should it?

**Comment by bparees** [comment]
Can you split the crash-loop issue off to a separate one?  it's not going to get fixed by the same person or probably even the same team.

**Comment by smarterclayton** [comment]
Someone can certainly tackle that separate, let's not close this until both are fixed.  This is the "someone needs to know that images might fail due to security" usability issue.

**Comment by bparees** [comment]
presumably we also want to error if they specify USER root.

**Comment by bparees** [comment]
and if they are referencing an imagestreamtag do we care, or only if they're directly picking a docker image?

**Comment by smarterclayton** [comment]
i think if we have the metadata, do the check and show the warning.  if we
don't have the image metadata, don't warn.

**Comment by bparees** [comment]
the new-app aspect of this is being addressed here: https://github.com/openshift/origin/pull/6414

assigning the rest of the issue (more debug suggestions in a crashloop backoff) to @pweil-

**Comment by pweil-** [comment]
TODO:

When status detects that the pod is in a crash loop state we should make suggestions such as the following common troubleshooting steps or common causes:

1.  use `oc logs --previous`
1.  tell the user if the pod is running as a non-root UID
1.  filesystem permissions not allowing edit on files when running as non-root (should use a volume)

**Comment by deads2k** [comment]
> filesystem permissions not allowing edit on files when running as non-root (should use a volume)

Is there a way to detect that this is actually the problem or would we simply write it out.  Is it really that common?

**Comment by smarterclayton** [comment]
It's the single most common failure mode on openshift today.

**Comment by smarterclayton** [comment]
Added part 1 of a fix in 6866

**Comment by smarterclayton** [comment]
Closing due to age, mostly addressed.
