### ISSUE TITLE
Pod deletion problem

### ISSUE THREAD

**Issue by marekjelen** [openshift/origin#636]
Hi,

I do deploy a docker registry for OpenShift by using the provided template in sample-app

```
cd $GOPATH/src/github.com/openshift/origin/examples/sample-app
openshift cli apply -f docker-registry-config.json
```

and then I want to clean it up, there does not seem to be a simple way to use (which would be a killer feature, btw)

```
openshift cli delete -f docker-registry-config.json
```

so I need to clean it up myself

```
openshift cli delete deploymentConfigs docker-registry
openshift cli delete services docker-registry
openshift cli delete pods -l name=registrypod
```

deploymentConfig and service gets deleted just fine, but the pod survives

```
[openshift@localhost ~]$ ./deinit.sh 
docker-registry
I0112 09:27:44.608255    3890 restclient.go:139] Waiting for completion of operation 242
26d1fa0d-9a3d-11e4-bafa-52540004b0e3
[openshift@localhost ~]$ openshift cli get services                                                                                                                                           
NAME                LABELS                                    SELECTOR            IP                  PORT
kubernetes          component=apiserver,provider=kubernetes   <none>              172.30.17.243       443
kubernetes-ro       component=apiserver,provider=kubernetes   <none>              172.30.17.169       80
[openshift@localhost ~]$ openshift cli get deploymentConfigs
NAME                TRIGGERS            LATEST VERSION
[openshift@localhost ~]$ openshift cli get pods
POD                                    CONTAINER(S)         IMAGE(S)                    HOST                LABELS                                                                           STATUS
44a021cb-9a3d-11e4-bafa-52540004b0e3   registry-container   openshift/docker-registry   localhost/          deployment=docker-registry-1,deploymentconfig=docker-registry,name=registrypod   Unknown
[openshift@localhost ~]$ ./deinit.sh 
I0112 09:30:48.632805    4402 restclient.go:139] Waiting for completion of operation 263
44a021cb-9a3d-11e4-bafa-52540004b0e3
[openshift@localhost ~]$ openshift cli get pods
POD                                    CONTAINER(S)         IMAGE(S)                    HOST                LABELS                                                                           STATUS
b5e1d5b7-9a3d-11e4-bafa-52540004b0e3   registry-container   openshift/docker-registry   localhost/          deployment=docker-registry-1,deploymentconfig=docker-registry,name=registrypod   Unknown
```

but the underlying container is gone

```
[openshift@localhost ~]$ docker ps
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS               NAMES
2be7a7f3f578        kubernetes/pause:go   "/pause"            11 minutes ago      Up 11 minutes                           k8s_net.ac688d01_b5e1d5b7-9a3d-11e4-bafa-52540004b0e3.default.etcd_b5e1d5b7-9a3d-11e4-bafa-52540004b0e3_4f40834d
```

Whatever I do, the pod seems to resurrect (you know, like Sylar). Is there a simple way destroy the pod?

Thanks

**Comment by mfojtik** [comment]
@marekjelen i'm looking into this

**Comment by mfojtik** [comment]
OK, so the problem here is that the deploymentConfig actually creates a replicationController:

```
[root@openshiftdev sample-app]# openshift cli get rc
CONTROLLER                             CONTAINER(S)         IMAGE(S)                    SELECTOR            REPLICAS
71d852f6-9a40-11e4-aed3-080027ce4245   registry-container   openshift/docker-registry   name=registrypod    1
```

In that case, if you remove the Pod the replication controller will start another one ;-) So to remove the Pod you have to remove the ReplicationController first.

I do agree that having a way to remove bulk of resources (maybe grouped by the Config label) would be awesome and I think that will be part of what @smarterclayton is doing with List resource.

**Comment by marekjelen** [comment]
@mfojtik thanks ... by removing the replication controller the pods get deleted as well. Thanks!

**Comment by smarterclayton** [comment]
Yeah, should merge upstream this week and then we'll backport

**Comment by smarterclayton** [comment]
This is fixed.

**Comment by deanpeterson** [comment]
I don't think this is fixed.  I am going through the sample application.  When I try to delete the database pod using ./oc delete <podname> it immediately starts another one once the pod I removed is gone.

**Comment by liggitt** [comment]
Did you delete the pod or the replication controller?

**Comment by deanpeterson** [comment]
I have done both.  I try ./oc delete rc <controller> and ./oc stop rc
<controller> and the controller keeps coming back.  I have also tried ./oc
delete pod <pod> and ./oc stop pod <pod> and it keeps coming back.

**Comment by deanpeterson** [comment]
I even deleted the service around the pod thinking that might do the trick.  Then I deleted the replication controller.  The ruby-helloworld-database will not go away.  It keeps coming back.

**Comment by mrosic** [comment]
@deanpeterson You've probably figured it out yourself by now but you need to do "oc get dc" and "oc delete dc" first before deleting anything else.

This is undocumented: "oc get" doesn't tell you that it can show info about deploymentconfigs (dc) and "oc delete" just throws an error messages without telling you the ressources that you can act upon with "oc delete".

This is terrible for people who are new to OpenShift and trying to learn it.

**Comment by smarterclayton** [comment]
This is because someone upstream took a shortcut and didn't properly
leverage our existing dynamic resource listing info.  I've opened
https://github.com/kubernetes/kubernetes/issues/15451 to fix this.  Until
then we'll carry a patch.

**Comment by smarterclayton** [comment]
Fixed in https://github.com/openshift/origin/pull/5063
