### ISSUE TITLE
Token starting with dash causes problems

### ISSUE THREAD

**Issue by prvak** [openshift/origin#6361]
Is there any particular reason why the token contains other than alphanumeric characters? Namely the dash "-". This can lead to hard to reproduce issues when the token is used as a parameter for some script and the dash appears at the beginning of the token.

```bash
oc whoami -t
-i34tN8Mrp9dVF9tkO0TCP2fbkYzZSkiC44iCw2Dp5I
```

Would it be possible to generate tokens using only alphanumeric characters?

**Comment by mfojtik** [comment]
@prvak can't you just quote the token string?

**Comment by deads2k** [comment]
@liggitt I thought that we our tokens were base64, which I thought only had `+/=` as special characters.

**Comment by prvak** [comment]
Well... just quoting the token does not help. There are other solutions (eg. using `-arg=token` instead of `-arg token`). But the way how to correctly pass an argument starting with '-' depends on the argument parser used in the script. Problem is that every developer has to know and think about it when he writes/uses the script and when he forgets it may still work for months before the problematic token is generated.

**Comment by liggitt** [comment]
We use url-safe base64 encoding (https://tools.ietf.org/html/rfc4648#section-5)

**Comment by deads2k** [comment]
> We use url-safe base64 encoding (https://tools.ietf.org/html/rfc4648#section-5)

Don't we already have our own token generator?  I think we ought to have it keep trying until it generates one without a leading `-`.

**Comment by liggitt** [comment]
we can skip the leading dash, though enabling unsafe quoting in scripts makes me slightly unhappy

**Comment by prvak** [comment]
> we can skip the leading dash, though enabling unsafe quoting in scripts makes me slightly unhappy

Maybe I am missing something but I do not see how avoiding leading dash would enable unsafe quoting. For example if the script would use `grep`:

```bash
grep "${TOKEN}" file.txt
```

It is correctly quoted and it works fine as long as the `$TOKEN` does not start with dash so you do not notice that there is something wrong until it may be too late. You would have to write every grep like this:

```bash
grep -- "${TOKEN}" file.txt
```

Another example could be a python script that uses `argparse` module for parsing commandline arguments:
```bash
dosomething.py --token "${TOKEN}"
```

Again it works fine unless the "$TOKEN" starts with dash. The `argparse` allows you to use '=' like this:

```bash
dosomething.py --token="${TOKEN}"
```

This way it works fine even with leading dash but again you need to remember to use the '=' every time and you do not notice that there is something wrong because when you test it it seems to work correctly even without the '='.

So there is always some way how to handle the argument with the leading dash but the developer needs to remember to write the script that way. And I know how easy it is to forget :)

**Comment by liggitt** [comment]
Right, those are examples of passing data to scripts in ambiguous ways, which isn't great.
