### ISSUE TITLE
Hairpin setup failed for pod 

### ISSUE THREAD

**Issue by hferentschik** [openshift/origin#6362]
I am running OpenShift all-in-one on a VirtualBox VM. The setup is per this repository https://github.com/redhat-developer-tooling/openshift-vagrant.

As part of the OpenShift provisioning a registry and router are created. When looking at the OpenShift logs via `docker logs`, I can see:

    W1217 08:19:51.892470   13937 manager.go:1892] Hairpin setup failed for pod "docker-registry-1-deploy_default": open /sys/devices/virtual/net/vethedbfa49/brport/hairpin_mode: read-only file system
    I1217 08:19:51.912012   13937 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
    W1217 08:19:52.089424   13937 manager.go:1892] Hairpin setup failed for pod "router-1-deploy_default": open /sys/devices/virtual/net/vethe4ac8f8/brport/hairpin_mode: read-only file system

and when I then create a nodejs example:

    W1217 08:22:44.249096   13937 manager.go:1892] Hairpin setup failed for pod "nodejs-example-1-build_nodejs": open /sys/devices/virtual/net/veth0845a35/brport/hairpin_mode: read-only file system

Not sure whether this is the cause for my problems, but sometimes the router and proxy don't seem to work/respond (even though the pods are running and there is no error in the logs of these pods).

**Comment by hferentschik** [comment]
Full log of the Openshift pods:

    $ docker logs dc87dc6abf8b
    time="2015-12-17T08:20:21-05:00" level=info msg="version=v2.0.0+unknown" 
    time="2015-12-17T08:20:21-05:00" level=info msg="redis not configured" instance.    id=b5d458e1-202b-4465-8fa9-6ce1ef5bb2d5 
    time="2015-12-17T08:20:21-05:00" level=info msg="using inmemory layerinfo cache" instance.    id=b5d458e1-202b-4465-8fa9-6ce1ef5bb2d5 
    time="2015-12-17T08:20:21-05:00" level=info msg="Using Origin Auth handler" 
    time="2015-12-17T08:20:21-05:00" level=info msg="Starting upload purge in 44m0s" instance.    id=b5d458e1-202b-4465-8fa9-6ce1ef5bb2d5 
    time="2015-12-17T08:20:21-05:00" level=info msg="listening on :5000, tls" instance.    id=b5d458e1-202b-4465-8fa9-6ce1ef5bb2d5 
    [vagrant@localhost ~]$ docker logs 631e96ade6fa
    I1217 08:19:40.819358   13937 plugins.go:71] No cloud provider specified.
    I1217 08:19:40.963438   13937 start_master.go:388] Starting master on 0.0.0.0:8443 (v3.1.0.3)
    I1217 08:19:40.963502   13937 start_master.go:389] Public master address is https://10.1.2.2:8443
    I1217 08:19:40.963520   13937 start_master.go:393] Using images from "openshift3/ose-<component>:v3.1    .0.3"
    2015-12-17 08:19:41.368327 I | etcdserver: name = openshift.local
    2015-12-17 08:19:41.368351 I | etcdserver: data dir = /var/lib/origin/openshift.local.etcd
    2015-12-17 08:19:41.368357 I | etcdserver: member dir = /var/lib/origin/openshift.local.etcd/member
    2015-12-17 08:19:41.368361 I | etcdserver: heartbeat = 100ms
    2015-12-17 08:19:41.368364 I | etcdserver: election = 1000ms
    2015-12-17 08:19:41.368367 I | etcdserver: snapshot count = 0
    2015-12-17 08:19:41.368376 I | etcdserver: advertise client URLs = https://10.0.2.15:4001
    2015-12-17 08:19:41.372546 I | etcdserver: restarting member abca2d8f0dd66377 in cluster     28cb2054c808baa3 at commit index 220
    2015-12-17 08:19:41.372620 I | raft: abca2d8f0dd66377 became follower at term 2
    2015-12-17 08:19:41.372634 I | raft: newRaft abca2d8f0dd66377 [peers: [], term: 2, commit: 220,     applied: 0, lastindex: 220, lastterm: 2]
    2015-12-17 08:19:41.372755 I | etcdserver: set snapshot count to default 10000
    2015-12-17 08:19:41.372779 I | etcdserver: starting server... [version: 2.1.2, cluster version:     to_be_decided]
    2015-12-17 08:19:41.373702 N | etcdserver: added local member abca2d8f0dd66377 [https://10.    0.2.15:7001] to cluster 28cb2054c808baa3
    2015-12-17 08:19:41.373771 N | etcdserver: set the initial cluster version to 2.1.0
    I1217 08:19:41.374131   13937 etcd.go:68] Started etcd at 10.0.2.15:4001
    I1217 08:19:41.400620   13937 run_components.go:183] Using default project node label selector: 
    2015-12-17 08:19:42.778764 I | raft: abca2d8f0dd66377 is starting a new election at term 2
    2015-12-17 08:19:42.778804 I | raft: abca2d8f0dd66377 became candidate at term 3
    2015-12-17 08:19:42.778847 I | raft: abca2d8f0dd66377 received vote from abca2d8f0dd66377 at term 3
    2015-12-17 08:19:42.778863 I | raft: abca2d8f0dd66377 became leader at term 3
    2015-12-17 08:19:42.778871 I | raft: raft.node: abca2d8f0dd66377 elected leader abca2d8f0dd66377 at     term 3
    2015-12-17 08:19:42.779480 I | etcdserver: published {Name:openshift.local ClientURLs:[https://10.    0.2.15:4001]} to cluster 28cb2054c808baa3
    W1217 08:19:42.789899   13937 controller.go:290] Resetting endpoints for master service "kubernetes"     to &{{ } {kubernetes  default  cbba2535-a4c0-11e5-b20b-525400d0cdc3 8 0 2015-12-17 08:19:26 -0500     EST <nil> <nil> map[] map[]} [{[{10.0.2.15 <nil>}] [] [{https 8443 TCP} {dns 53 UDP} {dns-tcp 53     TCP}]}]}
    I1217 08:19:43.045790   13937 master.go:232] Started Kubernetes API at 0.0.0.0:8443/api/v1
    I1217 08:19:43.045836   13937 master.go:232] Started Kubernetes API Extensions at 0.0.0.0:8443/apis/    extensions/v1beta1
    I1217 08:19:43.045840   13937 master.go:232] Started Origin API at 0.0.0.0:8443/oapi/v1
    I1217 08:19:43.045842   13937 master.go:232] Started OAuth2 API at 0.0.0.0:8443/oauth
    I1217 08:19:43.045845   13937 master.go:232] Started Login endpoint at 0.0.0.0:8443/login
    I1217 08:19:43.045847   13937 master.go:232] Started Web Console 0.0.0.0:8443/console/
    I1217 08:19:43.045850   13937 master.go:232] Started Swagger Schema API at 0.0.0.0:8443/swaggerapi/
    2015-12-17 08:19:45.009622 I | skydns: ready for queries on cluster.local. for tcp4://0.0.0.0:53 [    rcache 0]
    2015-12-17 08:19:45.009639 I | skydns: ready for queries on cluster.local. for udp4://0.0.0.0:53 [    rcache 0]
    I1217 08:19:45.148278   13937 run_components.go:178] DNS listening at 0.0.0.0:53
    I1217 08:19:45.155790   13937 start_master.go:519] Controllers starting (*)
    I1217 08:19:45.504384   13937 start_node.go:181] Starting a node connected to https://10.0.2.15:8443
    I1217 08:19:45.514929   13937 plugins.go:71] No cloud provider specified.
    I1217 08:19:45.514954   13937 start_node.go:281] Starting node localhost.localdomain (v3.1.0.3)
    E1217 08:19:45.643440   13937 serviceaccounts_controller.go:218] serviceaccounts "default" already     exists
    I1217 08:19:45.894236   13937 node.go:56] Connecting to Docker at unix:///var/run/docker.sock
    I1217 08:19:45.908373   13937 manager.go:128] cAdvisor running in container: "/system.slice/    docker-631e96ade6faa91fdda0dc29f478af0c7fca90998cc68eab9470d52c68aa1715.scope"
    I1217 08:19:46.240512   13937 fs.go:108] Filesystem partitions: map[/dev/mapper/    docker-253:0-267556-631e96ade6faa91fdda0dc29f478af0c7fca90998cc68eab9470d52c68aa1715:{mountpoint:/     major:253 minor:5 fsType: blockSize:0} /dev/mapper/VolGroup00-LogVol00:{mountpoint:/rootfs major:253     minor:0 fsType: blockSize:0} /dev/sda2:{mountpoint:/rootfs/boot major:8 minor:2 fsType: blockSize:0}     VolGroup00-docker--pool:{mountpoint: major:253 minor:3 fsType:devicemapper blockSize:1024}]
    I1217 08:19:46.294000   13937 machine.go:48] Couldn't collect info from any of the files in "/etc/    machine-id,/var/lib/dbus/machine-id"
    I1217 08:19:46.294189   13937 manager.go:163] Machine: {NumCores:2 CpuFrequency:2999998     MemoryCapacity:1041137664 MachineID: SystemUUID:EE7EA70B-905E-41DA-8FF5-820A1C002DC0     BootID:56a4d104-8b85-48a6-840a-4a9839dea6cd Filesystems:[{Device:/dev/mapper/    docker-253:0-267556-631e96ade6faa91fdda0dc29f478af0c7fca90998cc68eab9470d52c68aa1715     Capacity:107313364992} {Device:/dev/mapper/VolGroup00-LogVol00 Capacity:21003583488} {Device:/dev/    sda2 Capacity:198896640} {Device:VolGroup00-docker--pool Capacity:7818182656}]     DiskMap:map[253:3:{Name:dm-3 Major:253 Minor:3 Size:7818182656 Scheduler:none} 253:4:{Name:dm-4     Major:253 Minor:4 Size:7818182656 Scheduler:none} 253:5:{Name:dm-5 Major:253 Minor:5     Size:107374182400 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:42949672960 Scheduler:cfq}     253:0:{Name:dm-0 Major:253 Minor:0 Size:21474836480 Scheduler:none} 253:1:{Name:dm-1 Major:253     Minor:1 Size:1610612736 Scheduler:none} 253:2:{Name:dm-2 Major:253 Minor:2 Size:67108864     Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:52:54:00:d0:cd:c3 Speed:1000 Mtu:1500}     {Name:eth1 MacAddress:08:00:27:78:0b:5d Speed:1000 Mtu:1500}] Topology:[{Id:0 Memory:1073274880     Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction     Level:1} {Size:262144 Type:Unified Level:2} {Size:4194304 Type:Unified Level:3}]} {Id:1 Threads:[1]     Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144     Type:Unified Level:2} {Size:4194304 Type:Unified Level:3}]}] Caches:[]}] CloudProvider:Unknown     InstanceType:Unknown}
    I1217 08:19:46.309098   13937 manager.go:169] Version: {KernelVersion:3.10.0-327.el7.x86_64     ContainerOsVersion:Red Hat Enterprise Linux Server 7.1 (Maipo) DockerVersion:1.8.2 CadvisorVersion:     CadvisorRevision:}
    I1217 08:19:46.310468   13937 server.go:818] Watching apiserver
    I1217 08:19:46.490668   13937 node.go:249] Started Kubernetes Proxy on 0.0.0.0
    I1217 08:19:46.673311   13937 plugins.go:56] Registering credential provider: .dockercfg
    I1217 08:19:46.831040   13937 server.go:777] Started kubelet
    E1217 08:19:46.831176   13937 kubelet.go:812] Image garbage collection failed: unable to find data     for container /
    I1217 08:19:46.841439   13937 kubelet.go:833] Running in container "/kubelet"
    I1217 08:19:46.841551   13937 server.go:104] Starting to listen on 0.0.0.0:10250
    I1217 08:19:46.925062   13937 factory.go:194] System is using systemd
    I1217 08:19:47.157559   13937 factory.go:236] Registering Docker factory
    I1217 08:19:47.199496   13937 kubelet.go:944] Node localhost.localdomain was previously registered
    I1217 08:19:47.207042   13937 factory.go:93] Registering Raw factory
    I1217 08:19:47.268524   13937 nodecontroller.go:133] Sending events to api server.
    I1217 08:19:47.281397   13937 start_master.go:563] Started Kubernetes Controllers
    W1217 08:19:47.718304   13937 nodecontroller.go:572] Missing timestamp for Node localhost.    localdomain. Assuming now as a timestamp.
    I1217 08:19:47.735638   13937 event.go:216] Event(api.ObjectReference{Kind:"Node", Namespace:"",     Name:"localhost.localdomain", UID:"localhost.localdomain", APIVersion:"", ResourceVersion:"",     FieldPath:""}): reason: 'RegisteredNode' Node localhost.localdomain event: Registered Node localhost.    localdomain in NodeController
    I1217 08:19:47.785251   13937 manager.go:1006] Started watching for new ooms in manager
    I1217 08:19:47.901765   13937 oomparser.go:183] oomparser using systemd
    I1217 08:19:47.902671   13937 manager.go:250] Starting recovery of all containers
    I1217 08:19:48.275688   13937 manager.go:255] Recovery completed
    I1217 08:19:48.632160   13937 manager.go:118] Starting to sync pod status with apiserver
    I1217 08:19:48.632186   13937 kubelet.go:2056] Starting kubelet main sync loop.
    I1217 08:19:49.218280   13937 start_master.go:582] Started Origin Controllers
    W1217 08:19:51.892470   13937 manager.go:1892] Hairpin setup failed for pod "docker-registry-1-    deploy_default": open /sys/devices/virtual/net/vethedbfa49/brport/hairpin_mode: read-only file system
    I1217 08:19:51.912012   13937 provider.go:91] Refreshing cache for provider: *credentialprovider.    defaultDockerConfigProvider
    W1217 08:19:52.089424   13937 manager.go:1892] Hairpin setup failed for pod "router-1-    deploy_default": open /sys/devices/virtual/net/vethe4ac8f8/brport/hairpin_mode: read-only file system
    I1217 08:20:18.368697   13937 event.go:216] Event(api.ObjectReference{Kind:"ReplicationController",     Namespace:"default", Name:"docker-registry-1", UID:"d101e976-a4c0-11e5-b20b-525400d0cdc3",     APIVersion:"v1", ResourceVersion:"363", FieldPath:""}): reason: 'SuccessfulCreate' Created pod:     docker-registry-1-j7vku
    W1217 08:20:20.209803   13937 manager.go:1892] Hairpin setup failed for pod "docker-registry-1-    j7vku_default": open /sys/devices/virtual/net/vethc172aa1/brport/hairpin_mode: read-only file system
    I1217 08:20:34.266889   13937 event.go:216] Event(api.ObjectReference{Kind:"ReplicationController",     Namespace:"default", Name:"router-1", UID:"d10baa8b-a4c0-11e5-b20b-525400d0cdc3", APIVersion:"v1",     ResourceVersion:"407", FieldPath:""}): reason: 'SuccessfulCreate' Created pod: router-1-h8jsh
    W1217 08:20:34.351055   13937 kubelet.go:1690] Orphaned volume "d10d1ead-a4c0-11e5-b20b-525400d0cdc3/    deployer-token-bx7pf" found, tearing down volume
    W1217 08:21:08.646165   13937 kubelet.go:1690] Orphaned volume "d1255b13-a4c0-11e5-b20b-525400d0cdc3/    deployer-token-bx7pf" found, tearing down volume
    2015-12-17 08:22:16.023550 I | http: TLS handshake error from 10.1.2.1:57663: remote error: unknown     certificate authority
    W1217 08:22:44.249096   13937 manager.go:1892] Hairpin setup failed for pod "nodejs-example-1-    build_nodejs": open /sys/devices/virtual/net/veth0845a35/brport/hairpin_mode: read-only file system

**Comment by danwinship** [comment]
> Not sure whether this is the cause for my problems

It's not. The error is harmless. (It happens because of some code in kubernetes that assumes you are using a linux bridge rather than OVS.)

So, if you're having problems, you should explain better what they are, because they have nothing at all to do with this message.

**Comment by hferentschik** [comment]
> So, if you're having problems, you should explain better what they are, because they have nothing at all to do with this message.

I was having problems, but they were caused by something else and are resolved now.

> It's not. The error is harmless.

If it is an harmless error maybe this should be made clear (in the message or by documenting what this error means). Otherwise it might side track the search for an actual problem as in my case. If I am having problem with my setup and look at the logs and see something which tells me that "xyz failed", I will of course assume that this relates to me problem.

**Comment by danwinship** [comment]
Filed https://github.com/kubernetes/kubernetes/pull/19490 to get rid of the warning
