### ISSUE TITLE
Web Console confuses build configuration info

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6364]
![selection_008](https://cloud.githubusercontent.com/assets/88819/11872093/d6c5a748-a4d3-11e5-9a72-df8a6295235c.png)

In the example above, there is no builder image, and the source type is 'Git', but the information is displayed incorrectly.

Thanks @php-coder for noticing it.

**Comment by jwforres** [comment]
It's an issue with definition lists with empty values, we have seen it before.

**Comment by jwforres** [comment]
Assigned to @rhcarvalho since he already has a fix PR open
