### ISSUE TITLE
Extra border after clicking on "Toggle average line" in FF 41.0.2

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#6367]
@rhcarvalho said that Chrome doesn't show this border.

![origin-bug](https://cloud.githubusercontent.com/assets/87088/11872676/ec6785dc-a4d6-11e5-97f4-c09a31b4e3f6.png)

**Comment by jwforres** [comment]
its the focus outline, although the padding in between the outline and the content seems a bit wonky.

**Comment by spadgett** [comment]
> its the focus outline, although the padding in between the outline and the content seems a bit wonky.

There's no padding on the anchor element, and it looks like Firefox draws the outline a bit inside the content area.

I wouldn't want to remove the outline because then keyboard users wouldn't know the element is focused. We might be able to make it look a little better.

**Comment by jwforres** [comment]
On Mon, Feb 1, 2016 at 8:37 AM, Sam Padgett <notifications@github.com>
wrote:

> its the focus outline, although the padding in between the outline and the
> content seems a bit wonky.
>
> There's no padding on the anchor element, and it looks like Firefox draws
> the outline a bit inside the content area.
>
> I wouldn't want to remove the outline because then keyboard users wouldn't
> know the element is focused. We might be able to make it look a little
> better.
>
Agreed

**Comment by spadgett** [comment]
Similar issue after clicking our tabs (FF only).

<img width="969" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13095712/012b383e-d4e2-11e5-8402-53fcc57f0cf5.png">

**Comment by spadgett** [comment]
I'm not sure I want to do anything here because it might break accessibility for keyboard users. Even changing the outline style seems like a bad idea. @jwforres ?

**Comment by jwforres** [comment]
Outline is supposed to sit outside of padding and maybe margin, does adding
either of those help space things out? If this is Firefox not honoring
where outline is supposed to go then I would say we won't fix.

**Comment by spadgett** [comment]
> Outline is supposed to sit outside of padding and maybe margin, does adding
either of those help space things out? 

It will move the text so it's not flush with the right edge of the chart, unless we try a trick like padding and negative margin.

**Comment by jwforres** [comment]
Closing this since the fix would have to be hacky.
