### ISSUE TITLE
Missing iptables rules if the default gateway is not set

### ISSUE THREAD

**Issue by talset** [openshift/origin#6373]
We have seen an issue when trying to remove the default gateway (for debugging purpose) on the OpenShift master

We investigated and we identified that the issue was when the default gateway was missing the iptables rules would not show up.

Here is the details of what we did :
- check that there the  iptables rule (dnat for service ip)
- remove the default gateway
- restart openshift node & sdn
- check iptables
- dnat rules are missing

Fulll details are available here : https://paste.netwiki.fr/?9f7a16ec22edb6ea#XHVkqgp4BgKNdutPKr0dlayoDnMufCLI/uFMPISjoZo=

So the question is: why openshift-sdn need to have a default gateway to generate the iptables rules ?

Is it possible to run it without the default gateway ?

**Comment by marun** [comment]
@talset Can you please provide more detail as to the deployed configuration you are experiencing the problem with?  I don't seem to be able to replicate it against master.  I can see that you are using atomic openshift, and additional helpful details would include:

 - package version of atomic-openshift
 - version of atomic

**Comment by talset** [comment]
@marun  Yes sure, so :

2 masters / 2 nodes setuped

RHEL version
```
cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

OSE version
```
oc version
oc v3.1.0.4-16-g112fcc4
kubernetes v1.1.0-origin-1107-g4c8e6f4
```

Specific ansible config
```
openshift_master_cluster_method=native
```

I only tried on the master1 nodes.
