### ISSUE TITLE
Eliminate global project cache

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6375]
`pcache` and `GetProjectCache` should not be global state variables:  https://github.com/openshift/origin/blob/master/pkg/project/cache/cache.go#L24 and https://github.com/openshift/origin/blob/master/pkg/project/cache/cache.go#L77.

We don't want global variables around in general, but ones that are maintaining global state are particularly problematic.

@pravisankar fyi
@stevekuznetsov Can you tidy this up?

**Comment by pravisankar** [comment]
@deads2k 
project cache is used in few places and i don't think we want to spawn multiple reflectors/go routines to watch for the same resource. Yes, it is maintaining global state but we are only using for lookup (read only).

**Comment by deads2k** [comment]
> @deads2k 
> project cache is used in few places and i don't think we want to spawn multiple reflectors/go routines to watch for the same resource. Yes, it is maintaining global state but we are only using for lookup (read only).

I'd like to see it passed to those things that need it to make the dependency clear and simplify unit testing/mocking

**Comment by pravisankar** [comment]
This is fixed by https://github.com/openshift/origin/commit/2680b362f8d085a703a5344b8a8c70cf873e04b8
