### ISSUE TITLE
test flake in test/cmd/newapp.sh

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#6381]
Running hack/../test/cmd/newapp.sh:144: executing 'oc get imagestreamtags installable:file' expecting success; re-trying every 0.2s until completion or 60.000s...
    FAILURE after 59.988s: hack/../test/cmd/newapp.sh:144: executing 'oc get imagestreamtags installable:file' expecting success; re-trying every 0.2s until completion or 60.000s: the command returned the wrong error code
    There was no output from the command.
    Standard error from the command:
    Error from server: imageStreamTag "installable:file" not found
    Error from server: imageStreamTag "installable:file" not found
    Error from server: imageStreamTag "installable:file" not found
    ...

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7924/console

**Comment by rhcarvalho** [comment]
And also:

```
FAILURE after 59.871s: hack/../test/cmd/newapp.sh:21: executing 'oc get imagestreamtags mysql:latest' expecting success; re-trying every 0.2s until completion or 60.000s: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: imageStreamTag "mysql:latest" not found
Error from server: imageStreamTag "mysql:latest" not found
...
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7928/console

**Comment by knobunc** [comment]
Me too:
```
FAILURE after 59.400s: hack/../test/cmd/newapp.sh:21: executing 'oc get imagestreamtags mysql:latest' expecting success; re-trying every 0.2s until completion or 60.000s: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: imageStreamTag "mysql:latest" not found
```
 https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4398/consoleText

I've been hitting it for days :-(

**Comment by knobunc** [comment]
This is probably the same issue as https://github.com/openshift/origin/issues/6259

**Comment by danwinship** [comment]
I'd been seeing "mysql:latest" errors forever, but the "installable:file" one was new to me so I assumed it was different

**Comment by knobunc** [comment]
Based on @liggitt's analysis over on the other bug, it looks like it would affect any imageStreamTag... but I could well be wrong.

**Comment by liggitt** [comment]
same issue as #6259, closing as dupe
