### ISSUE TITLE
test/cmd/admin has hidden dependencies

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6382]
Running `test/cmd/admin.sh` by starting OpenShift, logging in as `system:admin` and creating a new project doesn't work. The test fails with this:
```
FAILURE after 0.058s: test/cmd/admin.sh:165: executing 'oc create -f test/extended/fixtures/roles/policy-roles.yaml' expecting success: the command returned the wrong error code
Standard output from the command:
role "basic-user" created
policybinding "cmd-admin:default" created
Standard error from the command:
Error from server: policy "default" not found
```

@smarterclayton wasn't the contract for `test/cmd/*.sh` buckets that you should be able to run them as `system:admin` in a new project?

**Comment by smarterclayton** [comment]
That was stated but it wasn't worth enforcing.  Admin is special.

**Comment by stevekuznetsov** [comment]
The README I'm writing for `test-cmd` will benefit from knowing that this isn't enforced and that some suites are special.

**Comment by akostadinov** [comment]
I see same when installing v3.1.1.11-9-g44fe9ba and running:
```
~/local/oc/3.1.1.11/oc policy add-role-to-user admin --role-namespace=8cuvn q4g4woys
```

I'm logged in as the user that requested the project, not system admin. Why does the error occur?
