### ISSUE TITLE
test-go flakes with many tests reaching timeout

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6384]
Many tests timeout in the same run as seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7912/consoleFull)

**Comment by liggitt** [comment]
panicing on timeout is not a problem (the process is getting terminated ungraciously)... timing out is the problem. Keep in mind the test that times out is not always the culprit... an earlier test could have taken way too long and used up the time)

**Comment by stevekuznetsov** [comment]
Right, I understand that. The description for this was poorly worded. I'll update.

**Comment by stevekuznetsov** [comment]
Although aren't `go test` timeouts per-test? 
```
$ go test -h
...
	-timeout t
	    If a test runs longer than t, panic.
	    The default is 10 minutes (10m).
```

**Comment by smarterclayton** [comment]
No longer actionable - known timeouts in units are anything that fetches from github or docker hub when those are slow.
