### ISSUE TITLE
Build controller keeps retrying builds after build configs are deleted

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6388]
Seen in logs from https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7941/artifact/origin/artifacts/cmd/ALg0/openshift.log

As the test progresses, old namespaces are deleted, but the build controller logs retry attempts to kick off builds for configs and namespaces that no longer exist:

seen 100+ times:

```
I1217 23:05:38.093475   31599 config_controller.go:20] Handling BuildConfig cmd-export/ruby-sample-build
I1217 23:05:38.093538   31599 config_controller.go:38] Running build for BuildConfig cmd-export/ruby-sample-build
E1217 23:05:38.095562   31599 config_controller.go:55] error instantiating Build from BuildConfig cmd-export/ruby-sample-build: BuildRequest "ruby-sample-build" is forbidden: namespace cmd-export does not exist
```

if the namespace doesn't exist, then the build config must not exist either, which means the controller is retrying a lot from an in-memory copy

**Comment by bparees** [comment]
Sounds like we need to add "namespace doesn't exist" to our set of fatal errors for which we do not retry in the retrycontroller.

@PI-Victor you were looking for things to do...

**Comment by bparees** [comment]
(currently we'll retry an event 60 times before giving up completely, unless a "fatal" error is returned from one of the attempts to handle it.)

**Comment by PI-Victor** [comment]
ok, working on it.
