### ISSUE TITLE
new pods getting created forever on a NodeSelectorMismatching  error

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#6390]
When playing around with the schedulers and getting a NodeSelectorMismatching  OpenShift would try to spin up forever some pods :

<pre>
chmouel@TheBatman:~$ oc get pod
NAME                      READY     STATUS                    RESTARTS   AGE
hello-openshift-1-0dxce   0/1       NodeSelectorMismatching   0          6s
hello-openshift-1-0nm6d   0/1       NodeSelectorMismatching   0          4s
hello-openshift-1-12em0   0/1       NodeSelectorMismatching   0          8s
[...]
chmouel@TheBatman:~$ oc get pod|wc -l
     103
chmouel@TheBatman:~$ oc get pod|wc -l
     112
chmouel@TheBatman:~$ oc get pod|wc -l
     329
chmouel@TheBatman:~$ oc get pod|wc -l
     633
</pre>

the template I am using here is [from the training](https://raw.githubusercontent.com/openshift/training/master/content/test-complete.json) repository

**Comment by ncdc** [comment]
See my description at https://bugzilla.redhat.com/show_bug.cgi?id=1334550#c11 for why this happens

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/43846
