### ISSUE TITLE
"unsupported volume type" when trying to mount a GlusterFS persistent volume claim

### ISSUE THREAD

**Issue by minhdoboi** [openshift/origin#6393]
We re trying to use a PVC with a GlusterFS PV. The PV is bound but the pod fail to mount the volume.

```
# oc get pv
NAME           LABELS    CAPACITY   ACCESSMODES   STATUS    CLAIM             REASON    AGE
gluster-pv01   <none>    2Gi        RWX           Bound     testvol/pvclaim             46s
# oc get pvc -n testvol
NAME      LABELS                       STATUS    VOLUME         CAPACITY   ACCESSMODES   AGE
pvclaim   template=persistent-volume   Bound     gluster-pv01   2Gi        RWX           36s
```

The event list contains:

```
11:53:59 AM	lwk25-1-shg1t	Pod	FailedMount	Unable to mount volumes for pod "lwk25-1-shg1t_testvol": unsupported volume type (7 times in the last minute)
11:53:59 AM	lwk25-1-shg1t	Pod	FailedSync	Error syncing pod, skipping: unsupported volume type (7 times in the last minute)
```

Our registry use a GlusterFS PV so the endpoints work well.
We tried the same with a NFS volume and it also worked.
Mounting manually a GlusterFS PV on the node, without claim, also worked.
Edit: Endpoint is in the default namespace, not in the pod namespace. It seems to work when endpoint is also created in pod namespace.

openshift v1.0.8-1-g8f1868d
kubernetes v1.1.0-origin-1107-g4c8e6f4
etcd 2.1.2
11:41
glusterfs 3.7.4

**Comment by minhdoboi** [comment]
with endpoint created for each project, it works fine.

**Comment by metal3d** [comment]
I can confirm. But... it's a pity to have to duplicate endpoints manually, each time, and I can't find a way to be able to let users to create project and ask me to add the endpoint definition manually.

I know that is a kubernetes problem, but is there a way to have a workaround on openshift:

- a user create project
- endpoint is automatically added

Or better:

A user create a project, then an "action" is performed => a configuration definition says "add this endpoint..."

The only way to be able to add enpoint is to create templates... and we've got so many project types...

**Comment by f-w** [comment]
Hi @metal3d , @minhdoboi : I received same error for glusterfs pv. By endpoint do you mean service *glusterfs-cluster-app*? If so, this per-project service is so easy to be deleted by using `oc delete all --all`. How do I restore the end point? In particular, does the cluster IP auto-assigned?
