### ISSUE TITLE
gonum/graph.Edges() is non-deterministic

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#6394]
When a graph G contains a set of edges, `G.Edges()` most of the time returns the set deterministically (the first edge starts from the root ie. the first node added in the graph, etc.) but that doesn't happen all the time. See https://github.com/openshift/origin/pull/6246#issuecomment-165752793

Currently there is no place in our graph code where we are based on the way `Edges()` returns edges, except [Fprint](https://github.com/openshift/origin/blob/4de5da70bd95794ebb188de7bb5600d1c48f50d9/pkg/api/graph/graph.go#L651) which 1) we don't use anywhere, 2) probably has another [bug](https://github.com/openshift/origin/blob/4de5da70bd95794ebb188de7bb5600d1c48f50d9/pkg/api/graph/graph.go#L653) (note that we always print the From node) too. 

cc: @deads2k

**Comment by deads2k** [comment]
There is no guarantee of ordering for edges.  Code that relies on ordering is improper.  If calling code needs ordering, it can choose the order it wants.

In the case of `Fprint` if ordering has value (and I accept that it might), enforce ordering there.  Since its dead, I'd just as soon see the method deleted.

**Comment by deads2k** [comment]
Ok, I see why it seems like there should be.  Bad API shape in the library we pulled in.  There's still no natural ordering.

**Comment by kargakis** [comment]
@deads2k so what do you want to do with this issue? Remove `Fprint`, godoc `Edges` explaining what's what, and close, or you have any graph api changes in mind?

**Comment by deads2k** [comment]
> @deads2k so what do you want to do with this issue? Remove Fprint, godoc Edges explaining what's what, and close, or you have any graph api changes in mind?

Remove Fprint and godoc the method explaining the lack of ordering.  Lacking a proper `Set`, I think that returning a `map` is even less clear.
