### ISSUE TITLE
test-cmd namespaces don't clean up correctly

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6398]
We see a lot of activity for objects that should have been deleted. In `test-cmd.sh` we delete the project that the test suite uses, but this doesn't clean up everything. A build from `test/cmd/admin` continues to be re-tried, deployment configs seem to pile up, *etc*.

@deads2k @liggitt @smarterclayton

**Comment by liggitt** [comment]
The namespaces are gone. The controllers retry loops are working off stale data.

**Comment by liggitt** [comment]
Dupe of https://github.com/openshift/origin/issues/6388
