### ISSUE TITLE
User testing suggestion: resource deletion from overview

### ISSUE THREAD

**Issue by ajacobs21e** [openshift/origin#6403]
Users were asked to delete an application during a usability test 12/1. I was looking to see where users first looked for this (currently missing) functionality. 3 of 4 users expected to find a delete app option within the details panel for the service on the overview page. I have mocked up two options for including service/app deletion on the overview page:

![delete - actions](https://cloud.githubusercontent.com/assets/6415742/11900853/3ab22360-a576-11e5-930d-af4d48d8ac0e.png)
Delete functionality could be located either under a "more actions" menu in the top right corner, which would be consistent with the browse pages, or as a button at the end of the details. 

After selecting the delete actions, users see a confirmation message:
![delete - confirmation](https://cloud.githubusercontent.com/assets/6415742/11900898/77a57916-a576-11e5-9350-621e46fcd4a0.png)

@jwforres @spadgett @sg00dwin @fabianofranz @jhadvig @benjaminapetersen @sspeiche

**Comment by jwforres** [comment]
yep we've actually talked about adding that recently, both delete and the raw editor, good to get user validation that its needed.

**Comment by jwforres** [comment]
@spadgett and i were thinking it would be the kebab dropdown at the top

**Comment by ajacobs21e** [comment]
@jwforres sounds good.

I updated the mockup. Let me know if there's more design work needed for this. 

![delete - actions](https://cloud.githubusercontent.com/assets/6415742/11901595/609cdd64-a57a-11e5-8e2d-0a72557d2f88.png)

**Comment by benjaminapetersen** [comment]
Only thing I would suggest is considering if we can swap to a trash-can icon if we only have one "delete" item under the menu.... menus with a single option are kinda funny :smile:  

Or just a "delete" text link, until we have enough actions to create a menu. I do like having the menu in place so it is obvious where future actions will go, helps enforce consistency.

**Comment by spadgett** [comment]
We should have at least "Edit (Raw)" for everything as well.

**Comment by benjaminapetersen** [comment]
Perfect, then we should be good!

**Comment by ajacobs21e** [comment]
Is there anything we need to test with this? Or are we all in agreement on this design?
![41](https://cloud.githubusercontent.com/assets/6415742/12180244/762d81f4-b549-11e5-9931-b61bff317ed0.png)

**Comment by spadgett** [comment]
@ajacobs21e The one thing I'm not sure of is the label we use for editing YAML, "Edit (Raw)". Will users will know what that means? Also we're adding an "Edit" menu item in places as well, so you have

```
...
-------------
|Edit       |
|Edit (Raw) |
|Delete     |
-------------
```

See https://github.com/openshift/origin/pull/6528#discussion_r48782598

/cc @jhadvig

**Comment by liggitt** [comment]
edit source, edit yaml, etc, would be clearer to me

**Comment by jhadvig** [comment]
`edit source` might be misleading, since the user wont be editing the 'source' but the 'configuration'

**Comment by ajacobs21e** [comment]
Whichever you think will make the most sense to users. Edit YAML or maybe
Edit config?

On Fri, Jan 8, 2016 at 1:19 PM, Jakub Hadvig <notifications@github.com>
wrote:

> edit source might be misleading, since the user wont be editing the
> 'source' but the 'configuration'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/6403#issuecomment-170079560>.
>



-- 

Allie Jacobs
UXD

calendar
<https://www.google.com/calendar/b/1/embed?src=ajacobs@redhat.com&ctz=America/New_York>

**Comment by jhadvig** [comment]
+1 for the 'Edit YAML'

**Comment by ajacobs21e** [comment]
Updates images with "Edit YAML" and showing the two options for showing the secondary menu. Patternfly's recommendation is to use an advanced (title tbd) dropdown button. 

![secondaryactions2_page_1](https://cloud.githubusercontent.com/assets/6415742/12923615/6f5d1bec-cf24-11e5-9d60-c9d89388d9a7.png)
![secondaryactions2_page_2](https://cloud.githubusercontent.com/assets/6415742/12923617/6f6c4bd0-cf24-11e5-952e-539847f472f2.png)
![secondaryactions2_page_3](https://cloud.githubusercontent.com/assets/6415742/12923618/6f6decf6-cf24-11e5-8226-0fbe5bf13b0d.png)
![secondaryactions2_page_4](https://cloud.githubusercontent.com/assets/6415742/12923616/6f6c616a-cf24-11e5-8032-bca5abfdf27d.png)
![secondaryactions2_page_5](https://cloud.githubusercontent.com/assets/6415742/12923619/6f6ed79c-cf24-11e5-955f-2dc4ec136cbe.png)

[Full wireframes](https://github.com/openshift/origin/files/123396/SecondaryActions.pdf)

**Comment by jwforres** [comment]
Since initial discussion seems settled on this, I'm moving to trello since its not a small enhancement https://trello.com/c/Q7oYZm63

**Comment by benjaminapetersen** [comment]
'Edit config' also could work.
