### ISSUE TITLE
oc get help for label selectors in inscrutible

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6424]
I forgot the format required an `=` and I got this helpful message.  

```
oc get all -l run:tmp
the provided selector "run:tmp" is not valid: unable to parse requirement: label key: invalid value 'run:tmp', Details: must match regex [[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* / ] [a-z0-9]([-a-z0-9]*[a-z0-9])?
```

Thanks guys, now I know how to use it.  How about a simplified explanation.  No one cares about the regex.

Probably need to fix this one upstream.

**Comment by kargakis** [comment]
Someone wanted to put that regexp in the help string for kubectl label........ :)
They sneaked it in an error as it turns out.
