### ISSUE TITLE
openshift-sdn godeps are wrong

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6428]
OpenShift-sdn is importing pkg/ and plugin/, neither of which are actual go packages.  It appears that openshift-sdn has never been properly godep imported (direct package imports, managed by godep save ./...).  This causes mild headaches every time we need to rebase / update a go package.

@ironcladlou @pweil- which ever person is working on rebase fixes should help @dcbw @danwinship @pravisankar get it sorted out.

**Comment by soltysh** [comment]
I'll take care of it once the rebase will be in.

**Comment by soltysh** [comment]
@smarterclayton can you close this one, I'll be bumping this godep once https://github.com/openshift/openshift-sdn/pull/253 gets merged.

**Comment by smarterclayton** [comment]
Is it fixed?

**Comment by smarterclayton** [comment]
Is the process on openshift-sdn side fixed so it doesn't happen again?

**Comment by soltysh** [comment]
I'll check when bumping sdn, I'm currently waiting for that PR be merged.

**Comment by danwinship** [comment]
no, nothing about the merge process has been changed yet. we want a sync post-253, but that doesn't fix this bug

**Comment by dcbw** [comment]
Can somebody enlighten me on how this is supposed to work?  eg, what specific sequence of 'go get' and godep commands do you use when you update a dependency for origin?  Bonus points if it's on Linux...

We certainly don't want to give anyone headaches.

**Comment by dcbw** [comment]
[dcbw@localhost origin (master)]$ GOPATH=/tmp/blah go get -u github.com/openshift/openshift-sdn/plugins/osdn/
<wait 10 minutes for all of github to download>
package k8s.io/kubernetes/pkg/api/v1beta3: cannot find package "k8s.io/kubernetes/pkg/api/v1beta3" in any of:
	/usr/lib/golang/src/k8s.io/kubernetes/pkg/api/v1beta3 (from $GOROOT)
	/tmp/blah/src/k8s.io/kubernetes/pkg/api/v1beta3 (from $GOPATH)

not really sure how to get past that one, since I think upstream Kube has already removed v1beta3, but origin still uses it.

**Comment by soltysh** [comment]
@smarterclayton assuming you have a clean godep restore the process it smooth. But as you know godep restore is not clean :-/ unless you've been doing rebase previously and have the env in place.
