### ISSUE TITLE
Move all commands that are not part of the product out of cmd/ and into tools/

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6430]
The `cmd` package was intended for our delivered CLIs, not supporting tooling.  `tools` seems to be in fairly wide use in the Go ecosystem - everything in cmd that is not shipped as part of the product should be moved into tools.

**Comment by stevekuznetsov** [comment]
@smarterclayton to be clear, you mean:
 * `cmd/genbashcomp`
 * `cmd/genconversion`
 * `cmd/gendeepcopy`
 * `cmd/gendocs`
 * `cmd/origin-version-change`
 * `cmd/rebasehelpers`
 * `cmd/recycle`

**Comment by smarterclayton** [comment]
recycle and version change belong in cmds

On Dec 22, 2015, at 9:41 AM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> to be clear, you mean:

   - cmd/genbashcomp
   - cmd/genconversion
   - cmd/gendeepcopy
   - cmd/gendocs
   - cmd/origin-version-change
   - cmd/rebasehelpers
   - cmd/recycle

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/6430#issuecomment-166631682>.

**Comment by stevekuznetsov** [comment]
I'll take this

**Comment by smarterclayton** [comment]
Resolved
