### ISSUE TITLE
splitting logs out

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#6448]
Looks like all the logs in openshift are combined.    This may be a feature, or just a convenience aspect of the fact that the binaries wrap things. 

Is anyone considering splitting them out?  I'd sort of vote that it might be a good idea.

**Comment by jayunit100** [comment]
Example: 

logs from controller, kubelet, apiserver, are all in the openshift log outputs:

`/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift start --loglevel=5 --public-master=localhost`

Results in (forwarded to openshift.log)
```
I1221 19:05:22.124629    2150 endpoints_controller.go:333] Pod is out of service: default/docker-registry-1-td5o5 
...
I1221 19:05:30.937483    2150 nodecontroller.go:607] Nodes ReadyCondition updated. Updating timestamp: {Capacity:map[memory:{Amount:4094885888.000 Format:BinarySI} pods:{Amount:40.000 Format:DecimalSI} cpu:{Amount:2.000 Format:DecimalSI}] Phase: Conditions:[{Type:Ready Stat
...
I1221 19:05:53.127124    2150 endpoints_controller.go:286] About to update endpoints for service k8petstore"
...
```

And these are all combined with logs from the kubelet (same file)
```
E1221 19:23:09.949561    2150 kubelet.go:1696] Could not tear down volume "81c768e1-a4d5-11e5-9666-080027c5bfa9/.deleting~917490307": rename /data/src/github.com/openshift/origin/openshift.local.volumes/pods/81c768e1-a4d5-11e5-9666-080027c5bfa9/volumes/kubernetes.io~secret/.deleting~917490307 /data/src/github.com/openshift/origin/openshift.local.volumes/pods/81c768e1-a4d5-11e5-9666-080027c5bfa9/volumes/kubernetes.io~secret/.deleting~504709898: file exists
```

and so on.

**Comment by liggitt** [comment]
Everything launched in a single process goes to a single log. If you are running the all-in-one, then everything (including the kubelet) will be in one log file. Normally, the master (API + controllers + scheduler) will be in one log, and each kubelet will have its own log file

**Comment by deads2k** [comment]
It looks like you've started the all-in-one.  That starts a kubelet, an api server, and controllers in a single process for easy development.

When installed on a production system, you'd normally have the kubelet, apiserver, and controllers in separate unit files.  That separates them and allows you to do things like `journalctl -u openshift-node`.

If you want to do it manually, you can start `openshift start node ...`, `openshift start master api` and `openshift start master controllers`

Does that help?

**Comment by jayunit100** [comment]
Ahhh.... Ok.  I think we can close this then. 

cc @marun
