### ISSUE TITLE
An option to start log streaming after starting a build manually

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#645]
I found myself repeating this over and over when testing Origin builds:

```
openshift cli start-build XYZ
openshift cli build-logs 123
```

I would be nice to have an option for `start-build` to wait till the container is started and then start streaming logs automatically:

```
openshift cli start-build XYZ --stream-log
```

**Comment by jhadvig** [comment]
+1

**Comment by kargakis** [comment]
I'll take a stab at this @bparees @mfojtik

**Comment by bparees** [comment]
we have a trello card for this.
https://trello.com/c/5Rr4IjMl/423-5-build-output-streamed-back-to-user-after-starting-build-build-beta3

**Comment by kargakis** [comment]
> we have a trello card for this.
> https://trello.com/c/5Rr4IjMl/423-5-build-output-streamed-back-to-user-after-starting-build-build-beta3

@bparees Then there are two Trello cards for this
https://trello.com/c/UM1HyjKY/490-5-make-buildlogs-more-sophisticated-build-future
Anyway, do I have to somehow register for this via Trello? Or wait until the next sprint? Or is it assigned to someone else?

**Comment by bparees** [comment]
@kargakis since you joined post-planning for this sprint and don't technically have a card, feel free to start working on this.  You need to join the trello board and then we can assign it to you (currently owned by @jhadvig but i don't think he'll mind).  Come friday we'll officially plan the card for next sprint so it gets doc+QE in that sprint.

**Comment by kargakis** [comment]
> @kargakis since you joined post-planning for this sprint and don't technically have a card, feel free to start working on this. You need to join the trello board and then we can assign it to you (currently owned by @jhadvig but i don't think he'll mind). Come friday we'll officially plan the card for next sprint so it gets doc+QE in that sprint.

Great, @jhadvig is cool and I think he prefers to maintain STI images. ;P

**Comment by bparees** [comment]
we will add MAINTAINER to his titles along with FIRE MARSHAL.

**Comment by jhadvig** [comment]
ack
@bparees also maybe a new instruction for Docker ? :P

**Comment by kargakis** [comment]
Track process here: https://github.com/openshift/origin/pull/1197
