### ISSUE TITLE
summary output from test-end-to-end makes everything green on Jenkins

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6452]
starts on this line:

```
Running "concurrent:server" (concurrent) task

    Running "copy:localConfig" (copy) task


    Done, without errors
```

It's annoying. I'll look into it.

**Comment by deads2k** [comment]
@liggitt I can't find the p99 label, you know where it is? :)

**Comment by liggitt** [comment]
don't we want everything green on jenkins? :)

**Comment by stevekuznetsov** [comment]
@deads2k I've got to do *some*thing while waiting on that jUnit review :)

**Comment by smarterclayton** [comment]
Closing due to age.
