### ISSUE TITLE
Improve volumes and mounts visuals on the web console

### ISSUE THREAD

**Issue by fabianofranz** [openshift/origin#6454]
Deployment config, deployment and pod pages display volume mounts information in both the "pod template" box and also in a dedicated "volumes" section. We should make it explicit that volumes are part of the pod template and visually expand the presentation so that  it's clear that pod -> {containers -> volume mounts, policies, volumes}.

Follow-up of https://github.com/openshift/origin/pull/6358

![07a8e886-a81f-11e5-9ec2-22822f116e11](https://cloud.githubusercontent.com/assets/158611/11947143/0cfe3658-a84a-11e5-819d-4334f9b412f8.png)

**Comment by fabianofranz** [comment]
@jwforres please tag and assign accordingly.

**Comment by jwforres** [comment]
@fabianofranz assigned to you for now but there is a larger discussion that I think needs to happen around these pages

cc @spadgett 

Specifically for the pod template, I'm wondering if its time to dump the dashed line visual, there are too many things now that could and probably should be in that box when on these browse pages.

**Comment by smarterclayton** [comment]
If you look at the structure of what we want to show here, it's:

This deployment config "deploys" this "pod template".  Details of how its deployed, distinct from what it deploys.

The how deserves more of an explanation - a description of the strategy, what the parameters mean, etc.  Which hooks are run.  This will vary across each type of controller (rc, PetSet, daemon set).  Also, the incomin triggers are very important for backreferencing what is deployed.

The what is the template - it's editable (except on pods), consistent (no reason to layout differently), and possibly quite complex (somewhere between 5 and 100s of settings).  So we need to leave space for it to grow unbounded.

**Comment by jwforres** [comment]
Moving to https://trello.com/c/YzU8RZjF
