### ISSUE TITLE
TestParseRepository error parsing git ssh URL

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6455]
https://ci.openshift.redhat.com/jenkins/job/devenv_ami/3014/console
```
--- FAIL: TestParseRepository (0.01s)
	git_test.go:115: git@[2001:db8::1]:repository.git: got ssh://git@[2001:db8::1]/repository.git, want {ssh  git [2001:db8::1] repository.git   }
	git_test.go:115: git@[2001:db8::1]:/repository.git: got ssh://git@[2001:db8::1]/repository.git, want {ssh  git [2001:db8::1] /repository.git   }
FAIL
coverage: 29.2% of statements
FAIL	github.com/openshift/origin/pkg/generate/git	0.065s
```

**Comment by liggitt** [comment]
seen again at https://ci.openshift.redhat.com/jenkins/job/devenv_ami/3068/console
```
--- FAIL: TestParseRepository (0.00s)
	git_test.go:115: git@[2001:db8::1]:repository.git: got ssh://git@[2001:db8::1]/repository.git, want {ssh  git [2001:db8::1] repository.git   }
	git_test.go:115: git@[2001:db8::1]:/repository.git: got ssh://git@[2001:db8::1]/repository.git, want {ssh  git [2001:db8::1] /repository.git   }
```
this doesn't seem like the sort of thing that should flake...

**Comment by liggitt** [comment]
@gabemontero, you were in this recently, can you take a look

**Comment by gabemontero** [comment]
@liggitt yep i'll take a look in the AM

**Comment by gabemontero** [comment]
it *may* be related to a correction @rhcarvalho made either here or elsewhere wrt struct comparisons

**Comment by rhcarvalho** [comment]
@gabemontero the recent related PR is #6399, but I don't think it is related as the change involved only `IsRemoteRepository`, while `ParseRepository` that is failing here depends solely on `url.Parse` and `s2igit.New().MungeNoProtocolURL`.

I've changed the error message when that test fail in #6534 so we can understand the problem better and solve it if it flakes again.

**Comment by gabemontero** [comment]
Thx for the response @rhcarvalho and yeah, I certainly wasn't convinced it was directly related - I just couldn't remember off the top of my head last night the precise details regarding your change.
One point (though to be clear, I'm not advocating reverting anything), but I'm curious if the field by field check I used to have would have experienced this flake.
Otherwise, I'm of course not seeing the "flake" locally, but do some runs with some debug added and then outline here the code paths which should be exercised for those 2 git@ with IPv6 entries.

**Comment by gabemontero** [comment]
Yep, the 2 git@[2001...] entries fall under the "url.Parse wets the bed for git clone specs" category.

The before and after results on the URL struct with %#v printing after calling `MungeNoProtocolURL` :
`ParseRepository git@[2001:db8::1]:/repository.git got &url.URL{Scheme:"", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"git@[2001:db8::1]:/repository.git", RawQuery:"", Fragment:""} from url.Parse, calling munge`

`ParseRespository git@[2001:db8::1]:/repository.git got &url.URL{Scheme:"ssh", Opaque:"", User:(*url.Userinfo)(0xc20803d740), Host:"[2001:db8::1]", Path:"/repository.git", RawQuery:"", Fragment:""} from munge`

`ParseRepository git@[2001:db8::1]:repository.git got &url.URL{Scheme:"", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"git@[2001:db8::1]:repository.git", RawQuery:"", Fragment:""} from url.Parse, calling munge`

`ParseRespository git@[2001:db8::1]:repository.git got &url.URL{Scheme:"ssh", Opaque:"", User:(*url.Userinfo)(0xc20803daa0), Host:"[2001:db8::1]", Path:"repository.git", RawQuery:"", Fragment:""} from munge`

The updated prints from @rhcarvalho should prove informative, but based on the existing prints, my best educated guess is either a) wrt the path, where there is some URL confusion with the needed ":" between the host and path and the preceding "/" (or lack there of) with `repository.git` ... if the error is in `s2igit.ParseSSH` I'm missing it on visual inspection or b) perhaps some issue with reflect.DeepEqual at certain go levels, where the flake if there happens to be any variability in which version of go is used when these automated tests run.

**Comment by rhcarvalho** [comment]
@gabemontero perhaps I pointed us to the wrong PR earlier. In #6402 I changed the tests from field-by-field comparison to use `reflect.DeepEqual`. Would like to see the output of a failed run now... I could not reproduce it with go1.4.2.

**Comment by gabemontero** [comment]
@rhcarvalho yep that is what I was referring to earlier ;-) 

fyi - my repro attempts were with go 1.4.2 as well

**Comment by gabemontero** [comment]
@liggitt @rhcarvalho  - any suggestions on how to monitor to see if the flake occurs again, other than pulling up the console logs for each failed job on the test / merge queues?

I tried ssh'ing into ci.openshift.redhat.com to do a recursive log scan, but don't have permission (or perhaps nobody is allowed to do this?)

thanks

**Comment by liggitt** [comment]
run the tests using go 1.5.2:
```
$ gvm use 1.5.2
$ hack/test-go.sh pkg/generate/git
--- FAIL: TestParseRepository (0.00s)
	git_test.go:115: git@[2001:db8::1]:/repository.git: got url.URL{Scheme:"ssh", Opaque:"", User:(*url.Userinfo)(0xc8200a3770), Host:"[2001:db8::1]", Path:"/repository.git", RawPath:"git@[2001:db8::1]:/repository.git", RawQuery:"", Fragment:""}, want url.URL{Scheme:"ssh", Opaque:"", User:(*url.Userinfo)(0xc8200a35c0), Host:"[2001:db8::1]", Path:"/repository.git", RawPath:"", RawQuery:"", Fragment:""}
	git_test.go:115: git@[2001:db8::1]:repository.git: got url.URL{Scheme:"ssh", Opaque:"", User:(*url.Userinfo)(0xc8200fe210), Host:"[2001:db8::1]", Path:"repository.git", RawPath:"git@[2001:db8::1]:repository.git", RawQuery:"", Fragment:""}, want url.URL{Scheme:"ssh", Opaque:"", User:(*url.Userinfo)(0xc8200a3590), Host:"[2001:db8::1]", Path:"repository.git", RawPath:"", RawQuery:"", Fragment:""}
FAIL
FAIL	github.com/openshift/origin/pkg/generate/git	0.012s
```

**Comment by gabemontero** [comment]
whoaaaa .... very cool tool; thx for the tip re: gvm !! repro'ed and working on fix; glad my speculation regarding go versions and DeepEqual proved relevant

**Comment by gabemontero** [comment]
Note: the `RawPath` field is a new addition to url.URL in golang 1.5.

Either I switch back to a comparison of the relevant common fields between 1.4 and 1.5 (which are the ones we correct with `MungeNoProtocolURL`), or I figure out how to do an #ifdef equivalent in go (where preliminary google searching is not turning up promising results)

**Comment by rhcarvalho** [comment]
@gabemontero I don't mind if you revert back to field by field comparison.
That with a comment is better than ifdefs or other manipulations just to have tests work for 1.4 and 1.5.
