### ISSUE TITLE
oadm registry port option

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#6482]
Currently the `oadm registry` command supports a `--port` option that allows you to set n ports or port pairs to be exposed on the container.  However, when this is specified it does not change the `config.yml` and it does not set a `REGISTRY_HTTP_ADDR` env var to override the config (~~which is not recommended by the docker docs anyway~~).  

This option seems useful for custom images that may be exposing different handlers on different ports.

1.  If ports are specified we should be overriding the config value
1.  If multiple ports are specified, should we choose the first specified port to use as the REGISTRY_HTTP_ADDR?  Another option would be to provide a different flag to specifically say which port the registry should listen on while still being able to expose multiple other ports.
1.  ~~Since env vars are not recommended by the docs should we manipulate config.yml?  I would say no.~~

@miminar @ncdc @smarterclayton 

BZ that brought this to my attention: https://bugzilla.redhat.com/show_bug.cgi?id=1293825

EDIT: on closer inspection of https://github.com/docker/distribution/blob/master/docs/configuration.md it is fine to override specific values, it just recommends not doing it for whole sections

**Comment by miminar** [comment]
I'd prefer option 2. Export the `REGISTRY_HTTP_ADDR` with container's port value of the first item in the `ports` argument. That and a bit of clarification in command's help.

**Comment by ncdc** [comment]
Option 2 sounds good
