### ISSUE TITLE
Web console: no way to view old builds for deleted build config

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6485]
There's no way to see anything other than the most recent build when a build config has been deleted. For instance, I can't get to build/ruby-ex-1, which does exist.

<img width="723" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11980791/65d1edde-a96b-11e5-973d-0b29d535940b.png">

@jwforres

**Comment by jwforres** [comment]
Yeah when this was originally designed you had the full build history accessible on this page by expanding the table but we took that out.

We could still link to the BC page and have that page still show something when there are builds but the BC itself is deleted.

**Comment by jwforres** [comment]
hmmm so this is actually a bigger problem when running under quota, you'd have no way to delete these builds from the UI and would be dependent on waiting for the reaper
