### ISSUE TITLE
No warning on browse build page when build config missing

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6486]
On the deployment page, we warn when the associated deployment config has been deleted. I don't see a warning on the build page when its build config has been deleted.

Also I noticed we don't show (or link to) the build config anywhere in the content, only in the breadcrumb.

/cc @jwforres

**Comment by jwforres** [comment]
We did link to the build config, should be in the configuration tab, or it use to be, did it get removed in all the shuffling?

**Comment by jwforres** [comment]
Are we generating the warning for the missing deployment config or is it that warning coming from the server?

**Comment by spadgett** [comment]
The web console checks and shows the warning for missing DC.

**Comment by spadgett** [comment]
Ah, the link is there. I guess I missed it:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12092773/1b6d3ecc-b2cd-11e5-9d88-febfa5921ffa.png)

It's inconsistent with the deployment page, though.

**Comment by spadgett** [comment]
We should add this after #6749 lands since it adds a watch for build configs.

**Comment by jhadvig** [comment]
@spadgett I've added the warning to both BC and Build browse page in https://github.com/openshift/origin/pull/6749

**Comment by jwforres** [comment]
I don't see a warning that the BC has been deleted on the build page, so i think this is still an issue.

**Comment by jwforres** [comment]
@jhadvig can you take a look at this and see why the warning isn't showing up now
