### ISSUE TITLE
Incorrect replication controller icon in topology view?

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6491]
@jwforres @stefwalter I'm guessing this icon is wrong?

<img width="868" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11984986/7104872a-a98e-11e5-8e1b-1b885249d971.png">

**Comment by liggitt** [comment]
looks right to me... a monolith, before which all pods bow, right?

**Comment by jwforres** [comment]
@stefwalter I suspect this happened in that last update you did to update a bunch of these SVGs

**Comment by jwforres** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1293780

**Comment by stefwalter** [comment]
This is: https://github.com/kubernetes-ui/topology-graph/pull/12
