### ISSUE TITLE
Deployments failing when OpenShift is reset

### ISSUE THREAD

**Issue by paralin** [openshift/origin#6497]
I'm running OpenShift under an existing Kubernetes production cluster as per the example in the kubernetes docs.

Our cluster scaled down and somehow the etcd setup got corrupted. I killed all of the etcd pods, reconfigured the rc to allow only one pod per host, and scaled it back up. 

This means OpenShift is basically reset - all of the namespaces are just namespaces, not projects (as far as I can see). 

When I try to make a deployment now, I get this error:

```
F1225 03:06:22.229921       1 deployer.go:65] couldn't get deployment default/docker-registry-5: User "system:serviceaccount:default:deployer" cannot get replicationcontrollers in project "default"
```

I tried:

 - Delete the service accounts
 - Delete *all* the secrets

These were regenerated. Same thing happens.

How can I get this to work again?

**Comment by liggitt** [comment]
There is an annotation on the default namespace that indicates the appropriate roles have been granted to the service accounts in that namespace. Deleting that annotation and restarting the API will readd the roles. 

More broadly, you might need to readd default roles to service accounts in all namespaces. Without knowing more about what got reset, it's hard for me to know what to recommend, but you can see the default roles that would be granted by viewing the default new project template (`oadm create-bootstrap-project-template -o yaml`)

**Comment by danmcp** [comment]
Please reopen if you have additional concerns.
