### ISSUE TITLE
containerized origin/node:v1.1(.0.1) crashes on fedora atomic host

### ISSUE THREAD

**Issue by ibotty** [openshift/origin#6499]
See the log on https://paste.fedoraproject.org/305163/64696145/

A similar error happens on v1.1.0.1.

**Comment by sdodson** [comment]
Hmm, that sounds like https://github.com/openshift/openshift-sdn/issues/222 can you try openshift/node:latest it should've been built since the fix was merged into origin

**Comment by ibotty** [comment]
Sorry, that was a very terse bug report. Yes, it does not happen on `:latest`. Can we have a `1.1.0.2` release with the fix please? I don't feel like running `:latest` master, and I don't feel I should mix and match.

**Comment by ibotty** [comment]
Fixed: current-release
