### ISSUE TITLE
feature request: key rolling for openshift-managed secrets

### ISSUE THREAD

**Issue by ibotty** [openshift/origin#6500]
I'd like a `oadm` sub command that can generate new and invalidate old keys (docker secrets, oauth tokens, etc). Ideally it should support selectors, so that e.g. some secrets don't get invalidated (those handed to users).

**Comment by deads2k** [comment]
Can you be a little more specific about exactly what you want to remove?

For instance, it is possible today to delete all the token secrets for a given service account and an cluster-admin has sufficient power to do that in all namespaces.  He could also control that delete via label selectors.  Likewise, a cluster-admin can delete arbitrary oauth tokens.

How would this be different than a targeted `oc delete -l`?

**Comment by ibotty** [comment]
Well, it would have a known place and being part of oadm would make it clear that it's best practice to rotate every other time. In a way, oadm prune also does things that can be done with oc delete (and a little oc get). If you disagree, I'd like to have at least some documentation please ;).

**Comment by deads2k** [comment]
> Well, it would have a known place and being part of oadm would make it clear that it's best practice to rotate every other time. In a way, oadm prune also does things that can be done with oc delete (and a little oc get). If you disagree, I'd like to have at least some documentation please ;).

The `oadm prune` commands require building a graph to determine all the different transitive dependencies amongst the various resources to fully determine both utilization and referenceability.  For instance, image pruning requires an inspection of every `PodSpec` contained inside of any given resource type for a proper reaping decision.

Invalidating keys does not require such an intensive transitive check: delete all secrets with the `kubernetes.io/service-account.uid` label would probably work fine for invalidation.

Are you looking for a different kind of functionality or just a different way to express it?
