### ISSUE TITLE
How to manage several volume manager in Openshift

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#6501]
Hi All, I would like to know if it is possible to have several volume manager in Openshift, for instance we are planning to use CEPH and GlusterFS, my questions are:

1) It is possible to have more than one volume manager ?

2) How to define a PersistentVolumeClaim for a specific volume manager for instance this claim only should select GLusterFS volumes, it is possible?

Many thanks.

**Comment by thincal** [comment]
About 1):
actually you could define several PersistentVolume based on different storage backend such as CEPH, GFS, or NFS etc.

About 2):
It seems the current pvc.spec mainly declare the storage capacity, which is used to select which pv. but what is the requirement to specify which kind of storage backend ?

**Comment by roldancer** [comment]
@thincal , that's the main question, how to specify at the PVC the kind of storage backend that the PVC must be associated with.
Any idea?

**Comment by roldancer** [comment]
The requirements could be shared storage like NFS/GluasterFS vs block device such as CEPH (RBD). Some applications like WebServers/Wordpress CMS in general terms fit perfectly on shared storage backend like NFS/GlusterFS but Databases fit better on block devices.

**Comment by deads2k** [comment]
@markturansky ptal

**Comment by markturansky** [comment]
@roldancer There is an upstream feature request (currently being worked) that will help you.

We're putting a PersistentVolumeSelector on PVClaim.  It will work similarly to a NodeSelector on Pod.  Essentially, the admin will label volumes and the user can add those labels as a selector to the claim.  The claim will only match a volume with the requisite labels.

You can use this approach to provide specific backends to users without actually exposing the user to the type of storage (they still won't know or care that it is ceph or gluster).

**Comment by roldancer** [comment]
Hi @markturansky , that sounds interesting, is there any RFE or specification available for that feature ?
I would like to read it.

Many thanks.

**Comment by markturansky** [comment]
No, just the agreed-upon idea that it would work like a pod's NodeSelector.  All selectors in the NodeSelector must match the labels on a node in order for a pod to be placed on that node.  That is the same approach being taken for PVSelector.  All selectors on claim must match the labels on the volume in order to bind.

**Comment by ivanthelad** [comment]
@roldancer 
I have a RFE for such a feature https://bugzilla.redhat.com/show_bug.cgi?id=1284994 
@markturansky isn't this the proposal for the feature your describe https://github.com/kubernetes/kubernetes/pull/17056

**Comment by markturansky** [comment]
@ivanthelad kind of.  The proposal in #17056 is going to become a little smaller.  The PVSelector in mentioned in there but is coming out as its own standalone feature.  It isn't necessary for provisioning, but it has been agreed upon that PVSelector is a Good Idea and we'll do it.  It's on our plate, currently.
