### ISSUE TITLE
`oc tag` should let me tag an image by pointing at a dc or bc

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6503]
I find myself wanting to tag a particular image associated with a given DC or BC. Something like `oc tag bc/foo tag`.  This would inspect the buildconfig, find the latest build, find its output, and using the same image stream point the new tag to the old output.  I could also deal with finding the source image hash via latest for istag.  I don't really want to care about which image or which image stream.  I only want to do it as an easy marker of what worked without having to remember which image stream is wired up.

Once `oc status` shows me build config destinations, this matters less.

@bparees @fabianofranz @jwforres

**Comment by bparees** [comment]
presumably you'd also want to  be able to run "oc tag build/somebuild sometag" while you're at it?

**Comment by deads2k** [comment]
> presumably you'd also want to be able to run "oc tag build/somebuild sometag" while you're at it?

Naturally.

**Comment by bparees** [comment]
guessing this would also be less important if we allowed you to specify multiple output tags for a given buildconfig (for which a separate issue exists).

**Comment by deads2k** [comment]
> guessing this would also be less important if we allowed you to specify multiple output tags for a given buildconfig (for which a separate issue exists).

Hard to say actually.  I've gotten myself in a bit of pickle.  My promotion flow failed to consider a case around transcoding which has apparently been busted for a couple micro versions.  The quest to find the working build is proving to be really annoying.

Is there an issue to allow annotating or tagging the output of a build based on information only available while performing the actual build?  In this case the version pulled down for installation.

**Comment by bparees** [comment]
The existing issue mentions tagging based on a commit id that it built, the
idea could be generalized, though not trivially.

Ben Parees | OpenShift

**Comment by bparees** [comment]
this has been ignored for 1.5 years, doesn't seem very important.
