### ISSUE TITLE
buildconfig should have a time-based trigger type

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6514]
I'd like to have my docker builds run nightly or weekly without having to set up manual cron jobs.

**Comment by deads2k** [comment]
@openshift/api-review since this would be an API change.

**Comment by smarterclayton** [comment]
Why would you want to do that?  Is it Tia void triggering and requiring that?

**Comment by smarterclayton** [comment]
To avoid triggering and / or requiring a parent to be imported.  Or is it to periodically grab all security updates?

**Comment by deads2k** [comment]
> To avoid triggering and / or requiring a parent to be imported. Or is it to periodically grab all security updates?

I have three cases that I'm dealing with now:
 1. periodic check for docker hub image updates (I haven't searched for an existing issue yet, but I'd expect it against images)
 1. periodic re-build to pick up updates for RPMs.  I don't know if or how to detect when there's been an actual update.
 1. product I'm `wget`-ing keeps a logical "latest" and I want to pick up its updates.

I've also worked on products that ran hourly builds instead of per-commit builds because it took a really long time to run builds, but that's not my current problem.

**Comment by smarterclayton** [comment]
Ok.  I think the periodic import will be solved by image streams that
poll (part of my import changes), but the rpm update is actually a
really good one.  Just sounds like another trigger on build configs.

**Comment by bparees** [comment]
Running a full build regardless of whether the rpm (or other external
dependency) doesn't seem ideal. The right way to solve this imho is (for
now) use Jenkins to poll for rpm changes and then trigger a build.

When you say the rpm use case is a good one, are you suggesting an rpm
specific trigger, or just using periodic builds to solve the use case?
Because I don't see a lot of people doing the latter (wasteful, as I said,
unless you use a custom assemble script or builder image to add checking
logic) but i'm not convinced we'd start adding first class support for rpm
changes (where do we stop once we start doing that?)

Ben Parees | OpenShift

**Comment by smarterclayton** [comment]
There is no generic way to poll for everything in the software
universe except for "run the build again".  Building out specific rpm
hooks (or apt hooks, or curl hooks) is a dead end in effort and
maintenance.   That said, it should be easy to set up a repeating
scheduled job to launch builds across the cluster inside of a
container, which somewhat reduces the need to implement it inside
builds.  Once scheduled jobs are implemented, of course.

**Comment by bparees** [comment]
I think i agree with all of that which basically means today you use Jenkins (and the openshift plugin) to schedule things, and in the future you can drop Jenkins when we have scheduled jobs natively. 

Neither of those would be a firs class time-based build trigger though.  (in particular the scheduled job would require a custom image that hit the build webhook or some similar mechanism) 

Just trying to clarify what we're saying we'd actually want to implement to solve this (valid) use case.

**Comment by smarterclayton** [comment]
The scheduled job would just call oc start-build.

In the short term, no, scheduled triggers are not high enough priority
that we would go do them over the other things we have in the queue.
They're a good design point though - a level driven build config with
a trigger that ensures there is a build for each time slice.  It's
just another type of trigger, and the use case is one we've missed
calling out before (but is important).

**Comment by bparees** [comment]
we have at least two other ways to do this today:  jenkins job that triggers your build, schedule job that invokes oc start-build. so i'm closing this because the value add to a user over those existing paths seems tiny relative to the effort to implement it.

**Comment by InfoSec812** [comment]
For anyone who finds this issue and is looking for how to configure this in an OpenShift Pipeline strategy BuildConfig, you can put the following snippet in your Jenkinsfile:

```
pipeline {
  triggers  { cron('H 4/* 0 0 1-5') }

  ...
}
```
