### ISSUE TITLE
Unable to create app from image of other repository

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#6516]
I've created my own Docker image (with my Origin Cluster 1). So I performed a s2i build on cluster1. The new generated image came into the openshift registry. Than I pushed that image from my cluster1 to my docker server with a private Docker Registry (which is using selfsigned certificates) . 
I've a Docker-server which has nothing to do with OpenShift. 

On my Origin1.1 Cluster 2 I pulled that image from my private Docker Registry. (So actually I've transported the image created in cluster1 to my cluster2. Not directly but with the help of a registry.
Now my image looks like this:

```
dockerregistry:5000/myimage
```
```dockerregistry``` is the name of my private Docker Registry.
Now I have that image on one of my nodes of my cluster2:

```
172.30.xx.xx:5000/test/test                                     latest              50c8347d0deb        5 hours ago         484.4 MB
172.30.xx.xx:5000/test/test                                     <none>              50c8347d0deb        5 hours ago         484.4 MB
dockerregistry:5000/myimage   latest              367745b886e6        5 days ago          484.4 MB
docker.io/centos/php-56-centos7                                   <none>              a32813b21232        8 days ago          484.4 MB
docker.io/openshift/origin-haproxy-router                         v1.1.0.1            e86406ba59f5        3 weeks ago         363.3 MB
```
Now I want to create a project with that image but that's not possible.
According the documentation it should work. What's going wrong?

```
oc new-project test
oc new-app dockerregistry:5000/myimage
error: no match for "dockerregistry:5000/myimage", specify --allow-missing-images to use this image name.

The 'new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet
or is only on the local system.
```

**Comment by lorenzvth7** [comment]
Update:
I'm able to run just a docker container by performing:
```
docker run -d dockerregistry/myimage
```

The container is running fine and it contains the right files.

**Comment by lorenzvth7** [comment]
```
docker pull dockerregistry:5000/myimage
oc new-project test
oc new-app dockerregistry:5000/myimage
```
Does not work --> error: no match for "dockerregistry:5000/myimage"

But a detour via the hub works
```
docker pull dockerregistry:5000/myimage
docker tag dockerregistry:5000/myimage dockerhubuser/myimage
docker push dockerhubuser/myimage
oc new-project test
oc new-app dockerhubuser/myimage
```
Does work --> Successfully pulled image "dockerhubuser/myimage

**Comment by lorenzvth7** [comment]
I also tried to make my own image locally and create an app from it:
```
oc new-app docker-whale
--> Found Docker image 7714ad3 (40 seconds old) from  for "docker-whale:latest" 
Failed to pull image "library/docker-whale:latest": Error: image library/docker-whale:latest not found 
```

**Comment by smarterclayton** [comment]
This looks like a regression in parsing on our end - what version of Docker are you running?

**Comment by lorenzvth7** [comment]
@smarterclayton 

```
docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Package Version: docker-1.8.2-7.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:        
 OS/Arch:      linux/amd64
```

**Comment by bparees** [comment]
if your registry requires authentication, then that is the problem. new-app cannot pull images from registries that require authentication (there is an existing issue for this), so as far as it's concerned the image does not exist in the registry.

**Comment by bparees** [comment]
To be clear, @csrwng's fix will make it so new-app can use an image that appears to only exist locally (because new-app can't access the registry).  It will proceed to define the expected openshift objects (deploymentconfig, etc) with a reference to that image.  If the nodes are also not able to pull the image, the deployment will ultimately still fail.  (however unlike new-app, nodes are able to pull images from secure registries)

**Comment by jgoldsmith613** [comment]
Why was this closed?  Is there another issue that fixes the issue of a secure remote registry with new-app?  I can't seem to find it

**Comment by bparees** [comment]
@jgoldsmith613 it was closed because we introduced the following behavior:

If new-app cannot locate the referenced image in a registry, it will still allow you to use that image, with a warning that things may not work correctly if the build environment also can't access the image.

Assuming the image exists locally (where you are running oc new-app) you should just see the warning and then the buildconfig will be created anyway and again, assuming your openshift cluster has permissions to access the image/registry, things will be fine.

If the image doesn't even exist locally, you will need to pass `--allow-missing-images`

**Comment by jgoldsmith613** [comment]
@bparees 

Even with the allow missing images flag It still returns with a 401 and does not make a dc.  (There is no source, just trying to create a pod from the image)
Running
oc new-app --insecure-registry --docker-image={image-location} --allow-missing-images

Same thing with --allow-missing-images=true

**Comment by bparees** [comment]
@jgoldsmith613 can you run with --loglevel=5 and provide the full output?

**Comment by lorenzvth7** [comment]
@jgoldsmith613 I assume you pushed your image in the openshift registry. At the moment I'm doing the following. I create an image-stream once. (like described [here](https://blog.openshift.com/remotely-push-pull-container-images-openshift/)). (create the image-stream). Then I'm able to push my image `https://registry-xxx/projname/imagename` and go inside my openshift project and just perform: `oc new-app projname/image:tag`
