### ISSUE TITLE
RFE: explain the scheduler decisions

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#6517]
The scheduler is very flexible with the way it decide to assign pods to a node. With the predicates and priorities mixed with the weighting system it could be hard to understand why the scheduler on a node or an another.

Currently the only log we have when the scheduler assign a node is the succinct : 

<pre>
 22s        22s     1   {scheduler }                                        Scheduled   Successfully assigned database-1-jv5vg to node1.openshift
</pre>

It would be nice it would add a why describing for example because of the nodeSelector or the matching of the labels for weights or PodFitsPorts, PodFitsResource etc..

**Comment by ingvagabund** [comment]
I can imagine this as dumping more information into the ``Pod.PodStatus.message`` field.

Still, none of the priority functions has to be the final arbiter. Even if you get a list of nodes, each node with a score, it is up to the ``selectHost`` [1] that chooses the final node. Other schedulers can have different arbiter. 

Maybe ``Choosing second highest score from PRIORITY``?

[1] https://github.com/kubernetes/kubernetes/blob/4387dcbdd5270fc4f4ab2440f2b460fa504c1049/plugin/pkg/scheduler/generic_scheduler.go#L127

**Comment by ingvagabund** [comment]
At the same time some schedulers does not have to use concept of predicates and priority functions. They can use completely different approach. With respect to the scheduler that is shipped with the Kubernetes, one could extend the message in the generated event [1]:

```Go
s.config.Recorder.Eventf(pod, api.EventTypeNormal, "Scheduled", "Successfully assigned %v to %v", pod.Name, dest)
```

Still, the scheduling algorithm implements ``ScheduleAlgorithm`` interface which currently does not allow to provide reason of the scheduling decision:

```Go
// ScheduleAlgorithm is an interface implemented by things that know how to schedule pods
// onto machines.
type ScheduleAlgorithm interface {
        Schedule(*api.Pod, NodeLister) (selectedMachine string, err error)
}
```

One could possibly extend the interface with ``Reason`` method that would return the reason why the last pod was scheduled on a given node. However, this will affect every scheduler that implements the interface. Which is not so bad if we want to provide more information about scheduler decisions. At least it will force other implementation to consider. At worst, the Reason can return an empty string.

[1] https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/scheduler.go#L152

**Comment by ingvagabund** [comment]
The current priority list does not allow you to get priority function's name. Though, it should not be hard to extend. Each priority function is part of the ``algorithm.PriorityConfig`` data type. Again, the data type is exported.

It does not make sense to report predicates as if a given node has been elected, all predicates holds. So it only make sense to report message like:

* "Selecting node with the second highest score 8 based on ServiceSpreadingPriority"
* "Selecting node with the second highest score 6 based on BalancedResourceAllocation"

So the final event could like like:

```
Successfully assigned database-1-jv5vg to node1.openshift. Selecting node with 2nd highest score 6 based on BalancedResourceAllocation.
```

@chmouel WDYT?

**Comment by chmouel** [comment]
I like it ! 👍 

it would be nice if there was a way to explain why the otherf filters wasn't chosen (i.e: no resources so PodFitsResources could not fil) but I guess that may be too overkill

thanks!

**Comment by ingvagabund** [comment]
https://github.com/kubernetes/kubernetes/issues/20064

**Comment by chmouel** [comment]
Great to see some traction upstream for this too

**Comment by ingvagabund** [comment]
Kubelet and DaemonSet controller (https://github.com/kubernetes/kubernetes/pull/29272) prints a list of reason why a given pod could not be scheduled on a given node. So we can see which predicates failed on which node. For Kubelet/DaemonSet it is ok as only one node is checked. In a case of the scheduler with hundreds/thousands of nodes it would be overkill, indeed.

One could print reasons for a node that is elected. Still, it can be a lot of characters at the end.

**Comment by ingvagabund** [comment]
Disadvantage of being too verbose/informative: https://github.com/kubernetes/kubernetes/issues/27189
