### ISSUE TITLE
godep save fail:  k8s.io/kubernetes/pkg/securitycontextconstraints not found

### ISSUE THREAD

**Issue by ruyanghao** [openshift/origin#6519]
1. go get github.com/openshift/origin
2. go get k8s.io/kubernetes
3. cd $GOPATH/src/github.com/openshift/origin
4. godep restore
5. cd $GOPATH/k8s.io/kubernetes
6. godep restore
7. cd $GOPATH/src/github.com/openshift/origin
8. godep save ./...
I get the below error:
godep: Package (k8s.io/kubernetes/pkg/securitycontextconstraints) not found

I checked the kuernetes, but I did not find the file ,
please help how can i fix it

**Comment by stevekuznetsov** [comment]
Why are you attempting to use `godep save`?

**Comment by deads2k** [comment]
@ironcladlou @pweil- @soltysh fyi

**Comment by deads2k** [comment]
Due to a couple different problems, our godeps do not restore/save cleanly.  We are looking at various options, but nothing in the super-near term.

What were you trying to do?  Perhaps we can help with an alternative approach.

**Comment by ruyanghao** [comment]
I clonded the kubernets project from github, and added some new code in kubernetes. Now I want to put the kubernets project into openshift, how can i do it ?

**Comment by soltysh** [comment]
As @deads2k already mentioned godeps do not work cleanly currently and we're working on improving this. The main reason for this we're keeping a bunch of legacy stuff which weren't upstream at the time (see `pkg/api/v1beta3`, `pkg/securitycontextconstraints`, to name a few). Have a look at our current rebase (#6320) for what we add on top of plain k8s to make this work. Having said all that, what is your goal, why are you trying to modify our internal k8s and not push your change upstream, which is the preferred way of doing this, see https://github.com/openshift/origin/commit/44d5579ed3d33e3f07439bcbb71f51fd8c908b99 for example, where we first push the change to k8s and if needed immediately in origin we do UPSTREAM commit, which will eventually be replaced upon next rebase.

**Comment by pweil-** [comment]
closing, we now use a forked version of the repo which contains the SCC dependencies.  That repo should be used when restoring as noted in https://github.com/openshift/origin/blob/master/HACKING.md#1-preparation
