### ISSUE TITLE
Bar charts with few builds look weird

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6535]
The bar charts when there are only one or two builds... aren't great.

One build:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12116616/181b583c-b389-11e5-997c-8f8bcfed6120.png)

Two builds:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12116674/95bc5110-b389-11e5-846b-7f91481e5917.png)

@smarterclayton @jwforres

**Comment by smarterclayton** [comment]
Some suggestions

- if you have 1 or 2 builds - don't bother showing the chart.
- left align the builds

**Comment by spadgett** [comment]
Experimenting with chart sizes so it's not always 100%. Centered doesn't seem too bad.

Left-aligned:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12145893/cdcb81d6-b45e-11e5-8613-2b7298d75c73.png)

Centered:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12145884/bebccae2-b45e-11e5-8bff-bce9938d21e1.png)

**Comment by spadgett** [comment]
How things look hiding the chart when only a few builds.

<img width="1029" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13090755/90eb88c4-d4c5-11e5-9f43-bc6c48e3408c.png">

**Comment by spadgett** [comment]
Full window for context.

![charts-centered](https://cloud.githubusercontent.com/assets/1167259/13093611/4d0c2c12-d4d4-11e5-9899-1bb3a3634f2b.png)

**Comment by smarterclayton** [comment]
Those poor builds - they look so lonesome.  Also, the random notches on
duration are bizarre.

**Comment by spadgett** [comment]
The chart looks great when there's data, but this is the first experience :(

**Comment by liggitt** [comment]
Hide the chart for fewer than N builds?

**Comment by spadgett** [comment]
Yeah, I'm leaning that way. Screenshot above: https://github.com/openshift/origin/issues/6535#issuecomment-184871748. Page looks a little empty, though.

**Comment by spadgett** [comment]
>  Also, the random notches on duration are bizarre.

c3 will generate nice tick values if you leave off a tick count, but there are more ticks than I want. Maybe it's still better.

<img width="1035" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13095627/33e5ea90-d4e1-11e5-9ba1-a91bd6cd8f7b.png">

**Comment by smarterclayton** [comment]
How about a small chart for less than N builds?  Like Jenkins?

On Feb 16, 2016, at 7:07 PM, Jordan Liggitt <notifications@github.com>
wrote:

Hide the chart for fewer than N builds?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/6535#issuecomment-184933625>.

**Comment by smarterclayton** [comment]
Can we do a half width summary section of the build config attributed
when we have < N builds?  And then hide that section when n is larger?

**Comment by spadgett** [comment]
This is how it looks on iOS with one build. Not crazy about the tab and view log link wrapping either.

<img width="432" alt="screen shot 2016-02-19 at 12 24 07 pm" src="https://cloud.githubusercontent.com/assets/1167259/13183221/cbf9faa0-d703-11e5-9a83-941f1fa6c98c.png">

**Comment by smarterclayton** [comment]
Is the graph useful at N<2?
