### ISSUE TITLE
Link CONTRIBUTING.adoc to the ansible, openstack, ec2, gce recipes.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#6549]
There is a great CONTRIBUTING.adoc guide, 

https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc

However, it doesn't talk about how to test openshift, 
1. from source. 
2. on a cluster.

There are also several projects for openshift plugins to vagrant, which aren't referenced from it. Lets link up the docs in:

https://github.com/openshift/vagrant-openshift

In CONTRIBUTING.adoc, so that we can unify the contribution / testing workflow for new devs.

**Comment by jayunit100** [comment]
oops, sorry for the autocorrect typo unusable ansible :)

**Comment by stevekuznetsov** [comment]
[`HACKING.md`](../blob/master/HACKING.md) outlines testing Origin from source. We should link to that document for explaining how to test. Might also want to explain what recipes are being run on Travis/Jenkins once they make a PR.

**Comment by jayunit100** [comment]
Thanks.  Obviously I'm not in position to do this, as Im new to OS.  maybe @stevekuznetsov you can or someone else we can poke :)

**Comment by stevekuznetsov** [comment]
@bparees can we come to consensus on what additions should be made to the doc? Should we link externally or replicate content internally to the doc?

**Comment by bparees** [comment]
linking is generally preferred.  replicated content gets out of sync.

**Comment by stevekuznetsov** [comment]
`HACKING.md` contents are:
 * building a release
 * running tests
 * installing Godep
 * fiddling with upstream commits
 * rebase instructions
 * troubleshooting
 * RPM packaging
 * swagger doc
 * performance debugging

`CONTRIBUTING.adoc` contents are:
 * download/install/develop workflow
 * networking tests
 * kube e2e tests
 * trello link
 * troubleshooting
 * irc links

What sections "belong" where? What is the purpose of `HACKING.md`? What is the purpose of `CONTRIBUTING.adoc`?

**Comment by stevekuznetsov** [comment]
My opinions:
If we want `CONTRIBUTING.adoc` to be a guide for a new dev, I think it should be short and sweet. It should contain:
 * download/install/develop
 * run tests
 * troubleshooting
 * irc/trello links

Each one of the above should be their own doc. In the install flow we can link to dind, the vagrant plugin, etc.

I don't particularly think `HACKING.md` should exist. We can have an "advanced README" for current devs with links to:
 * fiddling with upstream commits
 * rebasing
 * performance debugging
 * RPM packaging
 * swagger doc

**Comment by stevekuznetsov** [comment]
Alternatively, we could have `CONTRIBUTING.adoc` outline the (non-formal at the moment) process for:
 * claiming issues
 * making proposals
 * implementation

This would mirror documents like the [Golang doc](https://golang.org/doc/contribute.html).

**Comment by bparees** [comment]
I agree that Hacking and Contributing are overlapping and we should just have Contributing.

i'd just have an advanced section within contributing for the more complicated stuff.

**Comment by stevekuznetsov** [comment]
@jawnsy since you've been doing some work on the in-repo doc recently, FYI

**Comment by stevekuznetsov** [comment]
Not really a useful tracker, out of date.

/close
