### ISSUE TITLE
Evaluate E2E Tests in context of local build product.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#6551]
I will go through all the main tests (density, networking, volumes, and so on) as part of this issue, and create PRs separately to resolve them if necessary.

**Comment by jayunit100** [comment]
1. networking.go (intra-pod communication) Is failing.

`sudo _output/local/bin/linux/amd64/e2e.test --host="https://0.0.0.0:8443" --provider="local" --ginkgo.v=true --ginkgo.focus=Networking --kubeconfig=_output/local/bin/linux/amd64/master/openshift-master.kubeconfig --repo-root=./`

Can run kube e2e's from a local openshift artifact (see #6541 ).

In doing so, on a local cluster created via the CONTRIBUTING.adoc, I see that the base networking tests fail. I've pasted the results below - will dive deeper tomorrow. 

```
  /home/jay/Development/gopath/src/github.com/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework.go:62
STEP: Collecting events from namespace "e2e-tests-nettest-i522f".
Jan  5 18:52:09.221: INFO: event for nettest-osph6: {kubelet localhost.fios-router.home} Pulled: Container image "openshift/ori
gin-pod:v1.0.8" already present on machine
Jan  5 18:52:09.221: INFO: event for nettest-osph6: {kubelet localhost.fios-router.home} Created: Created with docker id 6c5677
298711
Jan  5 18:52:09.221: INFO: event for nettest-osph6: {kubelet localhost.fios-router.home} Started: Started with docker id 6c5677
298711
Jan  5 18:52:09.221: INFO: event for nettest-osph6: {kubelet localhost.fios-router.home} Pulled: Container image "gcr.io/google
_containers/nettest:1.6" already present on machine
Jan  5 18:52:09.221: INFO: event for nettest-osph6: {kubelet localhost.fios-router.home} Created: Created with docker id 92389d
c85593
Jan  5 18:52:09.221: INFO: event for nettest-osph6: {kubelet localhost.fios-router.home} Failed: Failed to start with docker id
 92389dc85593 with error: API error (404): Cannot start container 92389dc8559342d4018bb170bb89d27e5803496140c12665f44d17337b5d7
b19: [8] System error: no such file or directory

Jan  5 18:52:09.221: INFO: event for nettest-osph6: {kubelet localhost
```

cc @marun  @DirectXMan12  any thoughts?  I know you've played with the Networking tests on openshift.

**Comment by marun** [comment]
@jayunit100 Not sure of the specific error you're seeing, but the intra pod test requires that the api server have connectivity to pods (to make the status calls), which is only possible with openshift-sdn when running an sdn node on the master.  This can be enabled for vagrant or dind installs in master by setting OPENSHIFT_SDN_NODE_ON_MASTER=true, or by applying the following commit which always configures an sdn node on the master for openshift-sdn: https://github.com/marun/origin/commit/649c1c830f8f308b1273aedce19e305e54f384f0

**Comment by jayunit100** [comment]
Ah good point . I shouldn't even try the e2e on a local setup without the sdn enabled

**Comment by smarterclayton** [comment]
Closing due to age.
