### ISSUE TITLE
extended tests core.sh is broke

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#6553]
Unless OS_ROOT/hack/version.go is somehow dynamically generated and I missed running the step needed to generate it, it would appear that test/extended.core.sh is broken.

It references that file and bombs since it does not exists:

`stat /data/src/github.com/openshift/origin/hack/version.go: no such file or directory
!!! Error in test/extended/core.sh:34
	'k8s_version=$(go run ${OS_ROOT}/hack/version.go ${OS_ROOT}/Godeps/Godeps.json k8s.io/kubernetes/pkg/util)' exited with status 1
Call stack:
	1: test/extended/core.sh:34 main(...)
Exiting with status 1`

The commit that introduced the call to that file appears to be 03292503 from Nov 04.  If that file was subsequently removed, I don't know which commit did the remove.

**Comment by gabemontero** [comment]
@smarterclayton - hey, not sure what happened, but the `k8s_version=$(go run ${OS_ROOT}/hack/version.go ${OS_ROOT}/Godeps/Godeps.json k8s.io/kubernetes/pkg/util)` call `git blame` says you added to test/extended/core.sh is failing.

Is it possible somebody deleted/moved the version.go you are referencing?

**Comment by php-coder** [comment]
+1 :(

**Comment by bparees** [comment]
@stevekuznetsov you broke this with #6525

**Comment by gabemontero** [comment]
I'll experiment with changing hack/version.go to tools/godepversion/godepversion.go in core.sh when I get out of a meeting I'm in.

**Comment by stevekuznetsov** [comment]
@bparees ack

**Comment by aveshagarwal** [comment]
I am also running into this issue.

Running TEST_REPORT_DIR=/tmp/openshift-extended-tests/junit/extended test/extended/core.sh...
stat /data/src/github.com/openshift/origin/hack/version.go: no such file or directory
!!! Error in test/extended/core.sh:34
	'k8s_version=$(go run ${OS_ROOT}/hack/version.go ${OS_ROOT}/Godeps/Godeps.json k8s.io/kubernetes/pkg/util)' exited with status 1
Call stack:
	1: test/extended/core.sh:34 main(...)
Exiting with status 1
