### ISSUE TITLE
insecureEdgeTerminationPolicy: Allow does not get saved as normal user

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/origin#6555]
So I spoke with @pweil- about this. Seems there is a bug/weird config going on that prevents a regular user from adding insecureEdgeTerminationPolicy: Allow to their routes, in their own projects. As a normal user, I can go into my project oc edit route blah and add insecureEdgeTerminationPolicy: Allow, save, no errors are thrown, exit out of editor, then go right back into editing/viewing the route and the termination policy is gone. No error is shown in logs, nothing. If i then come into the project as system:admin and add the line and save the route, it works as expected without any problems.

Not too sure how to debug this.

**Comment by pweil-** [comment]
@kargakis - FYI - not sure if you ran into anything like this with the expose command work

**Comment by ramr** [comment]
@ebalsumgo that's odd. Does this happen for all routes or just this one?  
Can you try a simple test: 
```  
oc create -f https://raw.githubusercontent.com/ramr/nodejs-header-echo/master/openshift/edge-secured-allow-http-route.json  
oc get routes  
oc edit route  #   and change type from Allow to Redirect  and :wq  
oc get routes  
```
Does that work switching between Allow/Redirect? You should see the appropriately changed value in the oc get routes display (INSECURE column).

Also getting a dump of the etcd configuration might possibly give some clues. Do you mind running this
command on the master: 
`sudo curl -q -s -k --cert openshift.local.config/master/master.etcd-client.crt  --key openshift.local.config/master/master.etcd-client.key https://127.0.0.1:4001/v2/keys/?recursive=true >  /tmp/etcd.dump.json`

And attaching that output.

**Comment by ebalsumgo** [comment]
@ramr the route gets created but the insecure allow is not even present. when I go to edit the line is not there and when I try to add it as the same user that just created the route, that line just keeps getting discarded.

As far as etcd goes i am on OSE 3.1 and just did this:
root@osmaster0s:/etc/origin/master:
----> curl -q -s -k --cert master.etcd-client.crt --key master.etcd-client.key https://127.0.0.1:4001/v2/keys/?recursive=true
root@osmaster0s:/etc/origin/master:

And nothing got returned.

**Comment by deads2k** [comment]
Are you using the same `oc` for both your regular user and your system:admin?

**Comment by ramr** [comment]
@ebalsumgo hmm, ok - I tried it on origin (since this was filed as an origin issue).  Will try on OSE 3.1

Some questions before that though - what role does the user have in the project that you are trying to add the route to? Is the user an admin on the project?  The route resource is namespace scoped, so its possible the user is not an admin for the project? But its weird you can't see the field.
      These commands should give you more info. 
```
oc login -u $user -p $pass    #  replace user and pass.   
oc project $project
oc describe policyBindings  
```

A dump of the policyBindings may provide a clue.

@deads2k  -  you da man - quick and a mind-reader ... was just going to ping you and @liggitt  right now.

**Comment by ebalsumgo** [comment]
oc version was different (the user one was older) and that seems to have been the issue!

**Comment by ramr** [comment]
@ebalsumgo if this is no longer an issue, can you please close this. Thx
