### ISSUE TITLE
Decide whether the future E2Es should publish test/extended as single binary

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#6557]
Given that there is a need to package end2ends from upstream, we should decide and implement a consolidation of the packages for the other "extended" tests.  I think there are two parts to this.

- define the scoping for e2e vs extended tests.
- determine what binaries we actually want to publish for tests.  

cc @marun @smarterclayton @timothysc @pmorie

**Comment by bparees** [comment]
@ncdc assigning to your team since this sounds like upstream packaging, but i'm not totally clear on the request.

**Comment by ncdc** [comment]
@jayunit100 could you please expand on what you're asking here?

**Comment by jayunit100** [comment]
To be more concrete (sacrificing precision), it would be nice if we had a single artifact that can be used for E2E and integration testing which was minimally divergent from upstream.

**Comment by smarterclayton** [comment]
When you say single artifact you're looking for a distributable binary
that executes the full test suite against a cluster?

**Comment by jayunit100** [comment]
Oops, I missed this.

Yes.  One which ships and is usable/configurable by Quality Engineers and so on.  For example a binary that supports:

- I want to run Networking.go tests with a service density of 5 services per node
- I want to run the custom  open shift `oc ....` tests

**Comment by timothysc** [comment]
TAMs and SAs could use it for conformance verification as well.

**Comment by marun** [comment]
#8011 ensures a single test binary (extended.test) that includes both origin extended and kube e2e tests.

**Comment by timothysc** [comment]
@jayunit100 you can close this one out now.  It appears it's rolled and now in the rpms.

**Comment by jayunit100** [comment]
yup, thanks to everyone for the feedback on this goal ; closing -
