### ISSUE TITLE
add buildConfig status updates

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#6560]
An ask for this came out of https://github.com/openshift/origin/pull/5641 to have the `oc status` additions around missing image stream inputs into build configs into the status.details the API returns as well.

This would be analogous to what was done for deploymentConfigs (but then reverted for performance reasons), and will be re-added with https://github.com/openshift/origin/pull/5530.  I would think whatever approached is fleshed out of that work would serve as useful input into the work here.

**Comment by gabemontero** [comment]
@bparees going though my back log and am revisiting this one.  Ultimate goal I think is to either open a card for this or drop this idea (and close this issue out one way or the other). 

LMKWYT.

I'll consolidate the key details from the referenced issues, along with some code analysis from me:

0. It might be nice if the UI could easily display the warnings / errors generated by `oc status`, which neither has an api endpoint nor embeds the warning/errors in the API objects it examines.

1. With regard to builds, the analysis from `oc status` currently provides, within the context of a single namespace (key limitation for image stream analysis), determinations on:
- the existence of circular builds
- whether output image streams are misssing
- whether input image streams are missing
- whether input images stream tag/images are missing (and whether other BCs will produce those, and if so, whether they just have not been run or if their last build failed)

2.  There is not "status.details" type field in a build config ... builds were recently updated with messages and reasons (none of which include anything like the above `oc status` analyses_
- perhaps a similar reason/message structure could be applied to build configs?

3. Comparisons were made to deployment.  DeploymentConfig has both DeploymentDetails and DeploymentConditions.
- For DeploymentDetails.Message, it is only set in the instantiate endpoint Create
- For DeploymentConditions are updated by the controller as DCs move through its state machine.  Per some of the discussions of the referenced issues, there is a background loop (that leverages caching because of performance issues) that updates status; 
- none of the analyses from `oc status` for deployments correlates to the existing set of reason/messages the controller employs (status looks for lack of readiness probes, missing is and istags for dc ict's, missing pvc's or multi-node access to single-pod pvcs)

**Comment by bparees** [comment]
i'm happy to close this for now.  people defining buildconfigs that reference imagestreams that don't exist (and then not understanding why their BC is broken) is not a thing i've seen as a common issue.
