### ISSUE TITLE
oc new-app detection for Python

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#6562]
I initially flagged this issue under the ``sti-python`` as https://github.com/openshift/sti-python/issues/85 with the aim of getting comments from the maintainers of it, but no response as yet, so adding it here now.

The problem is that ``oc new-app`` when detecting if a Git repository under the Source strategy is a Python application, is not looking for the ``setup.py`` file, which would identify it as a Python application where package dependencies are listed in the ``setup.py`` file rather than a ``requirements.txt`` file.

For some reason it is looking for ``config.py`` when ``config.py`` has no significance that I know of in the Python world.

The ``assemble`` script in ``sti-python`` itself only treats ``requirements.txt`` and ``setup.py`` as significant and a trigger for package installation etc.

Perhaps someone looked at the Ruby detector and since it used ``config.ru`` wrongly though that Python should use ``config.py``. I can see no other reason why ``config.py`` would be used.

**Comment by rhcarvalho** [comment]
Totally agree with you @GrahamDumpleton. @bparees do we want to keep "config.py" there for backwards-compatibility? I'd just get rid of it since it indeed has no special meaning in a Python project.

**Comment by bparees** [comment]
@rhcarvalho i'm fine with getting rid of the config.py check.
