### ISSUE TITLE
Identical tags pushed to image registry result in different Images in registry

### ISSUE THREAD

**Issue by stefwalter** [openshift/origin#6564]
Identical docker tags pushed to the Openshift image registry result in different images being created in that registry. I would expect that a single image is created in the registry and referred to by the imagestream tags.

**Comment by stefwalter** [comment]
```
$ oc login
Authentication required for https://10.111.112.101:8443 (openshift)
Username: scruffy
Password: 
Login successful.
...
$ oc new-project zerog
...
Now using project "zerog" on server "https://10.111.112.101:8443".
$ sudo docker tag busybox:latest registry:5000/zerog/test:latest
$ sudo docker tag busybox:latest registry:5000/zerog/test:another
$ sudo docker images | grep zerog
registry:5000/zerog/test                     latest              fc0db02f3072        4 weeks ago         1.113 MB
registry:5000/zerog/test                     another             fc0db02f3072        4 weeks ago         1.113 MB
 .... Note that above tags are identical as far as docker is concerned ...
$ oc whoami -t
WY5r3aB5ew2CqZvEOJ-kb3qs54G6wegB37cGpOgaZDM
$ sudo docker login -p WY5r3aB5ew2CqZvEOJ-kb3qs54G6wegB37cGpOgaZDM -u unneeded -e unneeded registry:5000
Login Succeed
WARNING: login credentials saved in /root/.docker/config.json
$ sudo docker push registry:5000/zerog/test:latest
The push refers to a repository [registry:5000/zerog/test] (len: 1)
fc0db02f3072: Pushing 
fc0db02f3072: Pushed 
5c5fb281b01e: Preparing 
5c5fb281b01e: Pushed 
latest: digest: sha256:98842019ab49391fe6b419eb131211ceb1aa17a89f655b05e7305366fecea5f2 size: 3209
$ sudo docker push registry:5000/zerog/test
The push refers to a repository [registry:5000/zerog/test] (len: 2)
fc0db02f3072: Image already exists 
fc0db02f3072: Image already exists 
5c5fb281b01e: Image already exists 
another: digest: sha256:a7ca0c3e270a994cfdef0a1d77d8bd41d401135f2f9e02e0a3661cd026e81a77 size: 3210
$ oc get imagestreams
NAME      DOCKER REPO                   TAGS             UPDATED
test      172.30.87.3:5000/zerog/test   another,latest   45 seconds ago
$ oc get imagestreams --output=json
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "kind": "ImageStream",
            "apiVersion": "v1",
            "metadata": {
                "name": "test",
                "namespace": "zerog",
                "selfLink": "/oapi/v1/namespaces/zerog/imagestreams/test",
                "uid": "b1416e55-b52a-11e5-8871-5254009e00f1",
                "resourceVersion": "1180",
                "creationTimestamp": "2016-01-07T10:37:47Z",
                "annotations": {
                    "openshift.io/image.dockerRepositoryCheck": "2016-01-07T10:37:47Z"
                }
            },
            "spec": {},
            "status": {
                "dockerImageRepository": "172.30.87.3:5000/zerog/test",
                "tags": [
                    {
                        "tag": "another",
                        "items": [
                            {
                                "created": "2016-01-07T10:37:49Z",
                                "dockerImageReference": "172.30.87.3:5000/zerog/test@sha256:a7ca0c3e270a994cfdef0a1d77d8bd41d401135f2f9e02e0a3661cd026e81a77",
                                "image": "sha256:a7ca0c3e270a994cfdef0a1d77d8bd41d401135f2f9e02e0a3661cd026e81a77"
                            }
                        ]
                    },
                    {
                        "tag": "latest",
                        "items": [
                            {
                                "created": "2016-01-07T10:37:47Z",
                                "dockerImageReference": "172.30.87.3:5000/zerog/test@sha256:98842019ab49391fe6b419eb131211ceb1aa17a89f655b05e7305366fecea5f2",
                                "image": "sha256:98842019ab49391fe6b419eb131211ceb1aa17a89f655b05e7305366fecea5f2"
                            }
                        ]
                    }
                ]
            }
        }
    ]
}

**Comment by stefwalter** [comment]
$ oc version
oc v1.1-668-g705a7dc
kubernetes v1.1.0-origin-1107-g4c8e6f4

**Comment by ncdc** [comment]
This is not an OpenShift problem to solve. You will see this exact same behavior with any v2 registry because the tag is included in the image manifest. If you change the tag, you get a different sha256 identifier.

**Comment by stefwalter** [comment]
Interesting.

Using information available via the Openshift API, can one determine if two images are equivalent in all but their tag?

**Comment by ncdc** [comment]
You could probably take the raw manifests for both images, remove the tag, and recalculate the digests for them.

**Comment by ncdc** [comment]
I'm not sure offhand if the raw manifests contain varying timestamps anywhere, which would throw things off.

**Comment by soltysh** [comment]
My question is does end user care whether tge two image shas differ? I'm inclined to say no, but if so maybe we could provide some additional meta doing this, if possible...

**Comment by ncdc** [comment]
I agree. It all depends on how the information is presented to users. If they're shown a flat list of images (which I don't think we should do), then it would probably be nice to show one image instead of two. But if they're shown a list of image repositories, followed by a list of tags, this essentially becomes a non-issue.

**Comment by stefwalter** [comment]
Showing identical tags as equivalent is a very common way of presenting docker images. For example run this command on your machine:

```
$ sudo docker images
```

You should see images listed by tag next to each other with the indication that they are identical and have identical identifiers. For example:

```
docker.io/busybox                                                 buildroot-2014.02                                 8c2e06607696        8 months ago        2.43 MB
docker.io/busybox                                                 latest                                            8c2e06607696        8 months ago        2.43 MB
```

In addition we are working on an Image Registry UI which displays images like this, see the various tags, and how a user is able to add and remove tags from an image, reenforcing the concept of equivalency:

https://github.com/cockpit-project/cockpit-design/raw/master/kubernetes/images.png

This is the basic concept that any sort of visualization, graph of image relationships needs to rely on: the ability to tell when two images are identical. 

See @smarterclayton comment about "Some relationships suggested previously" here: https://trello.com/c/lwb08Css/237-3-atomic-atomic-registry-create-wireframes-for-docker-image-registry

**Comment by smarterclayton** [comment]
Partially mitigated in Docker 1.10 with the new "link" action.

**Comment by dmage** [comment]
When docker daemon (1.10+) pushes an image to a registry which doesn't support schema 2 manifests, it converts the schema 2 manifest into schema 1. And the converted manifest contains random data. So the result has always a different digest.

To mitigate this issue please enable schema 2 in the registry:
```
REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2=true
```
It is enabled by default in Origin 3.6.
