### ISSUE TITLE
image-puller can pull images, but he has no way to know the name

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6569]
We created the `system:image-puller` role to allow service accounts to pull images, but for that usage there was no reason to grant them the power to list all the available images.

When we attempt to use that role for humans, its presents a problem.  They can pull whatever image they want, but they have no power to actually list the images available to them.  I think its probably reasonable to expand the role to grant them the power to see the images themselves.

@liggitt @pweil- @ncdc @sub-mod

**Comment by ncdc** [comment]
@deads2k it's not particularly useful to be able to list images. You're better off going through the ImageStream, viewing its tags, and then retrieving the image you want.

**Comment by deads2k** [comment]
@ncdc same problem, they have no power to do it.  Maybe list power on istags?

**Comment by ncdc** [comment]
No objection to doing something like that, I just don't want to open up 'list images' as there will be hundreds/thousands/etc of images in the system, and there's no way to filter them unless you go through image streams.

**Comment by sub-mod** [comment]
Problem domain is Image registry UI
There can be multiple imagestreams under a project. If I assign a user only system:image-puller then I am hoping that this user can only pull images via pulling all imagestreams .
I could user "view" role But it has too many Resources .

**Comment by ncdc** [comment]
@sub-mod what do you need to be able to do in the UI w.r.t. images?

**Comment by sub-mod** [comment]
show all imagestreams and images

**Comment by ncdc** [comment]
Do you envision having a screen where you have a list of all images? I don't find that particularly useful... It makes more sense to me to show a list of image streams, and then within each image stream, a list of tags.

**Comment by sub-mod** [comment]
https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/kubernetes/projects.png
Have a look at the image where i assign Roles to Users.(they have view/edit/admin which dont map to openshift roles)

**Comment by ncdc** [comment]
? not sure what you're trying to show - could you explain in more detail?

**Comment by sub-mod** [comment]
Have a look at Sally user in the image , who has just Pull Role.  Which is assigned by project-admin / cluster-admin
when I login as Sally. I want to see all the images in the project .So that i can decide which images i am allowed to play with.

**Comment by ncdc** [comment]
You should be looking at image streams, not images. I just don't think it's useful to have a screen that is a list of all images.

**Comment by ncdc** [comment]
If you have a screen with a list of all images, it's going to look like this:

sha256:abcd1234
sha256:zzzzeeee
sha256:asdfasdf

But you can't actually refer to images just by their ID - you have to go through an image stream to pull an image. So you need to start with image streams, and then for each stream, show the list of tags and/or image IDs (SHAs).

**Comment by ncdc** [comment]
cc @pweil- @miminar @smarterclayton

**Comment by ncdc** [comment]
cc @soltysh

**Comment by smarterclayton** [comment]
I don't think image-puller should be able to list images, image streams, or even image stream tags.  I might buy an argument they could fetch an individual image stream tag by name, or maybe an image stream, but that's probably it.  If we need a role above puller but below image viewer, just granting 'get' but not 'list' is roughly equivalent to what's in Kube.

**Comment by deads2k** [comment]
I think this will be resolved by the new roles here https://github.com/openshift/origin/pull/6963 without modifying image-puller.

**Comment by sub-mod** [comment]
thanks @deads2k
