### ISSUE TITLE
`oc describe` typo on describing scheduler actions

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6586]
`scheduler` is written with an extra space at the end:

```
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath                           Reason          Message
  ─────────     ────────        ─────   ────                    ─────────────                           ──────          ───────
  37s           37s             1       {kubelet skuznets}      implicitly required container POD       Pulled          Container image "openshift/origin-pod:v1.1" already present on machine
  37s           37s             1       {scheduler }                                                    Scheduled       Successfully assigned welcome-php-1-build to skuznets
```

**Comment by matthyx** [comment]
This is not a typo, but comes from the EventSource (https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go) struct that doesn't have a Host set in the case of schedulers. So when they create the Event (same file) the Source gets a composition of Component + " " + Host, creating that extra space because Host is empty.
Not sure how to fix that, but I think this is just the JSON serialization to modify somehow.

**Comment by matthyx** [comment]
Should I take care of that? Please look at the proposed solution in my previous comment.
Thanks

**Comment by stevekuznetsov** [comment]
@matthyx I think it may make more sense to have two columns if we are describing two bits of data -- a `SOURCE COMPONENT` and `COMPONENT HOST` column, maybe?

**Comment by matthyx** [comment]
@stevekuznetsov good idea, I will implement that tomorrow. Is it better if I make a branch and commit to it in order to let other people see the progress and eventually try while we discuss the solutions? I think it will be more readable than putting diffs in this issue...

**Comment by stevekuznetsov** [comment]
Yes, and it seems like it's a k8s issue, so the pull request may be more appropriate there first. There is a CLI review group you can at-mention in k8s that would provide good feedback on the diff.

**Comment by matthyx** [comment]
Hi @stevekuznetsov, looks like this old issue was already on the same subject:
[printEvent Source to much more cleaner #13501](https://github.com/kubernetes/kubernetes/issues/13501)
I think I will dig this out and propose something there, do you agree?

**Comment by stevekuznetsov** [comment]
@matthyx yes, that sounds good -- the suggested approach in the other issue of `<component> on <host>` is also good. I agree, please make a pull request for upstream and we can get it into Origin with our rebase. Thanks for looking into this!

**Comment by matthyx** [comment]
@stevekuznetsov the pull request has been merged into Kubernetes 1.6-alpha. What should I do now for openshift/origin repo?

**Comment by stevekuznetsov** [comment]
@matthyx Awesome! If this were a show-stopping type bug fix, we would want to submit a PR to Origin with an `UPSTREAM` commit to bring it into our vendored k8s code. However, the more `UPSTREAM` commits we have, the more difficult each k8s rebase becomes, so we try to keep the `UPSTREAM`s to a minimum. I think in this case you can consider the job done and Origin will pick up the fix in our next rebase. Thanks!

**Comment by matthyx** [comment]
@stevekuznetsov ok, so are you closing this issue? Because it seems I cannot...

**Comment by stevekuznetsov** [comment]
@matthyx Can do!
