### ISSUE TITLE
test-cmd should call cleanup_openshift

### ISSUE THREAD

**Issue by bparees** [openshift/origin#6593]
test-end-to-end.sh calls cleanup_openshift at the end, which among other things, has the benefit of deleting large log files so they don't end up on jenkins:
https://github.com/openshift/origin/blob/master/hack/util.sh#L537
https://github.com/openshift/origin/blob/master/hack/util.sh#L493

test-cmd should do the same thing.  Unfortunately today test-cmd doesn't launch openshift in a standard way, apparently because it's trying to avoid requiring sudo (talk to @deads2k for more details).  So i'm not sure if adding a cleanup_openshift call is safe or not.  But it should be refactored so it can do this, if it can't today.

Also the actual log cleanup logic should be changed to truncate the log to 20megs, instead of deleting the log file entirely.  That way we still get some logging and if openshift went into some sort of hot loop that filled the log file, we should have some evidence of that.  (Even better, pull the last 20megs of the log file instead of the first 20megs).

@ncdc @jwforres @deads2k

**Comment by bparees** [comment]
@stevekuznetsov since you're becoming our test script guru, i'd appreciate if you could look into this.

**Comment by stevekuznetsov** [comment]
I noticed this today as well. There's a lot in store for these scripts. It's a real mess right now.

**Comment by stevekuznetsov** [comment]
@deads2k what is stopping us from using the extended startup script (`start_os_server`) for `test/cmd`, minus the node setup?

**Comment by deads2k** [comment]
> @deads2k what is stopping us from using the extended startup script (start_os_server) for test/cmd, minus the node setup?

Try using `start_os_master` similar to https://github.com/openshift/origin/blob/master/hack/update-generated-swagger-spec.sh#L43-L55

**Comment by smarterclayton** [comment]
Closing due to age.
