### ISSUE TITLE
How to do with the "docker --link" in openshift

### ISSUE THREAD

**Issue by thincal** [openshift/origin#6614]
For example, if the php container depends on another mysql container, traditionally in docker it could be running the mysql container firstly, then run the php container by `docker run --link`.

If I want to migrate them in openshift, what's the equivalent with the `docker --link` ? and how to ?

**Comment by bparees** [comment]
Services are the equivalent:
https://docs.openshift.org/latest/architecture/core_concepts/pods_and_services.html

I would also suggest you walk through this example: https://github.com/openshift/origin/tree/master/examples/sample-app

it uses a Template to define all the common objects in openshift, including using a Service to allow an Application to talk to a Database.

**Comment by thincal** [comment]
thanks and I will close this question.
