### ISSUE TITLE
Don't show "negative" date when the build in progress

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#6616]
![negative-date-bug](https://cloud.githubusercontent.com/assets/87088/12266516/df0d9b0c-b943-11e5-88ed-c5e7351227b6.png)

When build is pending I see the leading dash in `Started` row. I believe that we shouldn't show it.

cc @jwforres

**Comment by jwforres** [comment]
Yeah there shouldn't be anything in started in that case, definitely a bug
there
