### ISSUE TITLE
Running docker build is horribly insecure

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#662]
The following things need to happen to make docker build actually secure for end users.  Most of these need to be moved upstream, this is just an umbrella issue.  Most of the items below assume that the person invoking the build is running in a container, but is essentially a unix user

* It runs as root, and has full access to the system
  * docker build should be running in a user namespace where root inside the container != outside
* Installing packages requires root
  * In a container, root is effectively meaningless for most packages - it should be possible to yum install without having root, or to build container images that don't require root.  Filesystem permissions are mostly meaningless
* Docker build resource usage should be able to be accounted or constrained by the system
  * Ideally, the caller should specify the cgroup the build should run under (or should just run under the caller's cgroup)
* Running a docker build requires access to the docker socket, which means the container that runs a build must have access to the docker socket
  * The calls a container makes should be limited by the security context the container is running in
  * We probably want to install a whitelist filter between the container and the actual docker daemon that checks arguments.

**Comment by smarterclayton** [comment]
@rhatdan apologies for not tracking any of this earlier with you - been a crazy few months.  The first one is user namespaces, the second we discussed previously (yum install without root), the cgroups constriction on build seems like a reasonable feature we could get upstream, and the last one is something that would be more appropriate for kubernetes or openshift to deal with.

**Comment by bparees** [comment]
trello'd https://trello.com/c/qyxPOU7J/547-13-limit-sti-builder-privileges-build-future

**Comment by php-coder** [comment]
I see that this issue is closed and related trello card is archived. If it's not solved, maybe we should reopen the issue then?

**Comment by bparees** [comment]
It was archived in favor of other cards, specifically using Init containers.

**Comment by php-coder** [comment]
Which cards? Could you give me a link, please?

I found this issue in the comment (https://github.com/openshift/origin/blob/ae12b835cc0a6f76738d53bdd05375ccd109ec70/pkg/build/controller/strategy/sti.go#L81-L84) and looks like it's still not fixed.
