### ISSUE TITLE
Fully qualified Route is not shown in UI when a Route is create route.spec.host

### ISSUE THREAD

**Issue by sanjibbag** [openshift/origin#6621]
While creating a Route with route.spec.host the Openshift console doesn't show Fully qualified end point. For example when a host name is specified for a route as below then openshift console displays it as "etcd-test-discovery" instead of it's fully qualifies name which is ""etcd-test-discovery.router.default.svc.cluster.local"
```
{
    "kind": "Route",
    "apiVersion": "v1",
    "spec": {
        "host": "etcd-test-discovery",
        "to": {
            "kind": "Service",
            "name": "etcd-test-discovery"
        }
    }
}
```
This will be useful for user who may not know what is the default subdomain specified in master-config.yml.

**Comment by liggitt** [comment]
If you specify a `host` in the route.spec, that is the fully qualified host, so the console is displaying the correct value.

**Comment by sanjibbag** [comment]
Yes that is true. In that case route.spec.host has to be specified as "etcd-test-discovery.router.default.svc.cluster.local" by developers who are creating the template or route. In our organization we are creating generic templates for multiple projects and developers to reuse. Developers may not be aware of subdomain used by Openshift, more of that they do not need to be aware of it. Also, very first question that we get from our user is that what is the end point while using custom route.spec.host. So we believe it will be beneficial if fully qualified hostname is show in Openshift console.

**Comment by liggitt** [comment]
There is no facility today for a partially custom route host (custom prefxi + global suffix). Leaving route.spec.host empty will result in a generated, fully-qualified hostname (which the console would show correctly).

**Comment by sanjibbag** [comment]
Thanks. I have created a pull request to address this problem. I was working on a solution for this issue. The solution may not be a optimal solution. Please refer https://github.com/openshift/origin/pull/6622

**Comment by jwforres** [comment]
@liggitt with @smarterclayton's changes in https://github.com/openshift/origin/pull/6953 is there anything else the console needs to worry about here?

**Comment by liggitt** [comment]
I think the UI would need to change to use `route.status.ingress[n].host`

**Comment by jwforres** [comment]
We should really update to show the new info.  If a route has no status.ingress then the route is "Pending"  if it has status.ingress then it could have multiple, in which case we need to decide which one is the best one to show in the overview and in the routes table, on the route itself we should just show all of them.  An ingress can be admitted or not, if it is not admitted that needs to show up as a warning.
