### ISSUE TITLE
Metrics and logging origin images need to be folded into Origin release process

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6628]
We need to be tagging those images using the same internal process we use for regular images.

**Comment by jcantrill** [comment]
@smarterclayton merged into metrics and logging.  can this be closed?

**Comment by smarterclayton** [comment]
Yes but can you link to the open question about where the deployer pod belongs?

**Comment by jcantrill** [comment]
Adding link to @smarterclayton question regarding moving the deployer into origin; https://github.com/openshift/origin-aggregated-logging/pull/110#discussion_r58912486
