### ISSUE TITLE
Docker-registry example needs a way to reuse the same volume if loaded on the host twice

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#663]
Currently the example is reusing a host-dir for efficiency, but that requires permissions to be constant on the host.  It should be possible to have the docker registry running on the host attempt to reuse a volume by a secret name, and die if not.  This would be a "moderatelyPersistentVolume" that is still tied to the host, that would be cleaned up some period after being out of use.  Prototype this upstream, remove the need for example registry to be privileged.

**Comment by bgrant0607** [comment]
Why not just a volume in a pod? The registry should stay on the same node so long as the node doesn't disappear for more than 5 minutes, or if it were started using a file on the node.

**Comment by smarterclayton** [comment]
I think the use cases are more transient storage where reuse is valuable but not required.  Things like build caches, temporary work dirs, etc (where you verify the local cache matches your needs anyway).  In this case we were reusing a registry across runs of an end to end test and the reuse of the local volume was an optimization.  In our case it was a hard reference to a volume in a host dir, causing us to have to deal with selinux permissions.  

In the future id like to have a way to model a temporary build cache - one way would be a transient volume type (that in the future might hint to scheduling).  Another is a remote network device, which would work for this use case as well (a fake network device, maybe).

**Comment by danmcp** [comment]
@ncdc FYI

**Comment by ncdc** [comment]
@smarterclayton what was the SELinux issue - was each new pod getting a unique mcs label that didn't mesh with the label on the host dir?

**Comment by ncdc** [comment]
@smarterclayton also, are you looking for `osadm registry` to support some flags related to volumes and claims?

**Comment by smarterclayton** [comment]
For 3.0 no.

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by smarterclayton** [comment]
This is related GoogleCloudPlatform/kubernetes#598 and https://github.com/GoogleCloudPlatform/kubernetes/issues/7562#issuecomment-97967400

**Comment by thockin** [comment]
Yes.  I am not against the idea outright, but the lifetime management is fugly.  Why not run a per-node memcache-like thing that you could access through a virtual IP but it would always choose your local-node instance, and let the lifetime management, chargeback, etc be tied to that cache daemon rather than "the node".

**Comment by smarterclayton** [comment]
Covered by upstream sticky volumes, closing.
