### ISSUE TITLE
oc logs displays badly encoded output in windows (10) 

### ISSUE THREAD

**Issue by adietish** [openshift/origin#6631]
If I tail the logs of my nodejs example in windows

```
oc logs bc/nodejs-example
```

I get badly encoded outputs:

![oc-logs-bc-nodejs-example-windows](https://cloud.githubusercontent.com/assets/25126/12290371/b305367a-b9e1-11e5-8e61-2223ea615d00.png)

**Comment by adietish** [comment]
this was reported in https://issues.jboss.org/browse/JBIDE-21440 by @dgolovin

**Comment by matthyx** [comment]
Hi, this bug no longer exists. I did minishift start on linux with oc client running on Windows version 10.0.14393:
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://localhost:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994

I think we can close this issue.
![photo5852494202317940932](https://cloud.githubusercontent.com/assets/20683409/23072279/72a50b0a-f531-11e6-892d-0d1ba606de14.jpg)

**Comment by fabianofranz** [comment]
@matthyx thanks!
