### ISSUE TITLE
Web console "scaling to n..." message can be misleading

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6638]
We show a "scaling to..." message when rc.spec.replicas doesn't match the actual number of pods. Generally the message disappears when scaling completes. In some cases, actual replicas never match spec, however, and the message never goes away. For instance, scaling up might put the user over project quota. In these cases, the phrasing isn't appropriate.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12298750/a5c963dc-b9e1-11e5-836f-156b30a2e770.png)

/cc @jwforres

**Comment by liggitt** [comment]
not sure... if spec.replicas=2 and status.replicas=1, I'd say that is accurate... scaling could be blocked though, and it would be good if we could know that and surface that somehow

**Comment by spadgett** [comment]
We could at least warn if you're at or near quota on the overview, instead of only on the settings page. I'm sure there are other possible causes. It'd be good to surface events in the sidebar as well.

**Comment by jwforres** [comment]
we added the quota related warnings
