### ISSUE TITLE
How export a variable to all my pods?

### ISSUE THREAD

**Issue by Dtsr** [openshift/origin#6644]
I have a database url and would like to export this information to all my pods .

Is there any way to do this? perhaps through a service in the default project.

I read a bit about integrating external services , but I think is not the way

https://docs.openshift.com/enterprise/3.0/dev_guide/integrating_external_services.html

thanks

**Comment by bparees** [comment]
oc env will let you do this, eg:
```
# Update all containers in all replication controllers in the project to have ENV=prod
  $ oc env rc --all ENV=prod
```

**Comment by Dtsr** [comment]
Thanks ben

But this would solve the problem only until the next construction.

Is there any way to expose variables between applications ?

My idea is to create a service with several variables and expose these variables for all my pods.

Thanks

**Comment by bparees** [comment]
There's currently no way to do that.  What you want sounds loosely related to service linking as discussed in the service catalog proposal:  https://github.com/kubernetes/kubernetes/pull/17543/files#diff-06c8d9e12508ed6c6b573c85489f4b75R69

**Comment by Dtsr** [comment]
thanks @bparees
