### ISSUE TITLE
Web console: suppress quota warnings for ResourceQuota and LimitRange types

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6649]
The web console should suppress quota warnings for ResourceQuota and LimitRange types on the settings page. Reaching the quota limit for these types is not really a problem.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12307037/e7a946d6-ba0a-11e5-98e1-1478c7d6f6a0.png)

/cc @jwforres @derekwaynecarr

**Comment by jwforres** [comment]
showing resourcequotas and limitranges is a little silly to begin with, in a typical configuration only a cluster admin can even add those to a project

**Comment by derekwaynecarr** [comment]
I agree; we may end up with more than one, but I am not sure its worth displaying by default.
