### ISSUE TITLE
Our bash traps need a re-write

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6655]
We need to support having multiple traps for the same signal, which requires us to follow some conventions:
1. never use `exit` in a trap, instead use `return` - this ensures that traps that catch the signal after you get to run
2. always use utility functions to install traps so that you play nice with any other traps that exist

We'll also need utility functions to prepend or append traps to a signal.

**Comment by rhcarvalho** [comment]
I feel like (and fear) we're diving into more and more complex bash scripting. Wouldn't we be better served by Python or Ruby or Go, anything that would save us from falling into a trap?

**Comment by stevekuznetsov** [comment]
@rhcarvalho I don't think we have any reasonable alternatives.

**Comment by stevekuznetsov** [comment]
Not worth tackling this debt right now.

/close
