### ISSUE TITLE
Build revision extended test is failing

### ISSUE THREAD

**Issue by bparees** [openshift/origin#6664]
see:

https://ci.openshift.redhat.com/jenkins/job/origin_extended/485/testReport/junit/%28root%29/Extended%20Core/builds__parallel__build_revision_started_build_should_contain_source_revision_information/

**Comment by bparees** [comment]
has failed 8 times in a row, so probably not a flake.  haven't tried to run it on my own though.

**Comment by mfojtik** [comment]
@bparees I tried to run this test several times on my own and it always pass... There might be some race on how fast we update the Build() to get the Revision informations... @csrwng any clues?

**Comment by mfojtik** [comment]
@csrwng @bparees bump? is this still flaking?

**Comment by bparees** [comment]
not as far as i know.
