### ISSUE TITLE
BuildConfig env vars should support valueFrom syntax

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#6665]
Builds today use the k8s EnvVar struct definition which supports the ValueFrom field, so you could create a buildconfig / build object with ValueFrom defined, but the build controller will not do anything with that field.

**Comment by jwforres** [comment]
@csrwng @bparees

**Comment by bparees** [comment]
we should introduce our own EnvVar struct that just has key+value fields to avoid this confusion.

**Comment by liggitt** [comment]
... or... support the downward API for populating build envvars

**Comment by bparees** [comment]
@liggitt yeah we discussed and for the moment at least, rejected, that option based on complexity.

**Comment by liggitt** [comment]
in that case, I would use validation to block valueFrom for build envvars... hopefully we'd eventually support it

**Comment by bparees** [comment]
adding validation is a good call.

**Comment by bparees** [comment]
validation logic has been added but will leave the issue open to revisit supporting valueFrom correctly.

**Comment by bparees** [comment]
trello https://trello.com/c/lDxfG8GO
