### ISSUE TITLE
Running 'oc create-app' from command line results in "Server could not find the requested resource" 

### ISSUE THREAD

**Issue by brettneese** [openshift/origin#6666]
And no pods being created. 

I've tried a few docker images (including the defaults, so I know it's not related to how openshift handles docker security), a few of the s2i images, etc... sometimes it will even appear multiple times. The service gets created but nothing else happens. Not sure even how to go about diagnosing this, I looked at journalctl and the docker registry logs and didn't see anything terribly interesting.  .

Interestingly, I can launch things from the web console, but I need to launch some stuff not in the list. :-\
 
![image](https://cloud.githubusercontent.com/assets/504279/12338136/c595c942-bad3-11e5-88f4-e14f19a7832e.png)

![image](https://cloud.githubusercontent.com/assets/504279/12338220/45c0fab0-bad4-11e5-8aae-4e621709a793.png)

**Comment by liggitt** [comment]
What do you see if you add `--loglevel=8`?

**Comment by brettneese** [comment]
![image](https://cloud.githubusercontent.com/assets/504279/12338390/f294a214-bad4-11e5-9422-92f9ba47bb6f.png)

**Comment by liggitt** [comment]
Looks like you have an older version of the command-line client, running against a server that has v1beta3 disabled. Try adding `--api-version=v1`

**Comment by brettneese** [comment]
That worked. That sounds right, too, my version was from the roadshow a few months back.

How do I update the command line client?

**Comment by liggitt** [comment]
For the ose distribution, you can download from https://access.redhat.com/downloads/content/290

**Comment by brettneese** [comment]
What about origin? I know somewhere once logged in there was something about downloading it.

**Comment by brettneese** [comment]
Ah. Found it. https://github.com/openshift/origin/releases 

Closing this. Thanks for your help.
