### ISSUE TITLE
Local project image stream ignored, instead going to Docker Hub.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#6671]
Bringing this over from RH aos-devel based on @smarterclayton suggestion.

Short summary is that I am creating an image stream in project which shadows image stream in ``openshift`` namespace for S2I builders. In my case ``python``. When using ``oc new-app`` and relying on automatic language detection, it is getting confused in some way and is ignoring the image stream in the project for ``python`` and trying to go up to Docker Hub instead, even ignoring that there was a ``python`` image stream in ``openshift`` namespace.

I am seeing this on what I believe is a 3.1 cluster.

```
$ oc version
oc v1.1
kubernetes v1.1.0-origin-1107-g4c8e6f4
```

Details from list post below.

When using S2I (Source Strategy) and you say something like:

```
oc new-app https://github.com/GrahamDumpleton/wsgi-hello-world.git
```
then ``oc new-app`` will look at the contents of the Git repository and work out what language it is. In this case it contains a Python application.

Next ``oc new-app`` will, because it is Python, look for an image stream called ``python`` and the image in it tagged with ``latest`` to use as the S2I builder image. This would normally be picked up from the ``openshift`` namespace.

It then proceeds to apply the S2I builder image to the Git repository contents and we get a running container with service. We can then expose it and access it.

For various reasons I want to override what the default ``python`` S2I builder is, but don't want to loose the ability to simply point ``oc new-app`` at a Git repository and still allow it to perform the language detection.

To do this, lets build our S2I builder in OpenShift and simply label it as ``python``.

```
oc new-build https://github.com/openshift/sti-python.git --context-dir=2.7 --name=python
```

The result is:

```
$ oc describe is python
Name:                        python
Created:                About a minute ago
Labels:                        build=python
Annotations:                openshift.io/generated-by=OpenShiftNewBuild
                        openshift.io/image.dockerRepositoryCheck=2016-01-15T00:40:20Z
Docker Pull Spec:        172.30.137.21:5000/python-examples/python

Tag        Spec                Created                PullSpec                                                                                                                Image
latest        <pushed>        57 seconds ago        172.30.137.21:5000/python-examples/python@sha256:fa4d6a64eade603464ecc8ef20d786f6e0d8166d23f59cb60b6239bf6ae5cb23
```

With an image stream now local to our project called ``python``, we create our initial application afresh.

```
$ oc new-app https://github.com/GrahamDumpleton/wsgi-hello-world.git
--> Found Docker image 0237868 (29 hours old) from Docker Hub for "python"
    * An image stream will be created as "python:latest" that will track this image
    * The source repository appears to match: python
    * A source build using source code from https://github.com/GrahamDumpleton/wsgi-hello-world.git will be created
      * The resulting image will be pushed to image stream "wsgi-hello-world:latest"
      * Every time "python:latest" changes a new build will be triggered
    * This image will be deployed in deployment config "wsgi-hello-world"
    * The image does not expose any ports - if you want to load balance or send traffic to this component
      you will need to create a service with 'expose dc/wsgi-hello-world --port=[port]' later
--> Creating resources with label app=wsgi-hello-world ...
    error: imageStream "python" already exists
    ImageStream "wsgi-hello-world" created
    BuildConfig "wsgi-hello-world" created
    DeploymentConfig "wsgi-hello-world" created
```

This does and doesn't work because of a few issues.

Before I point out what seems to go wrong, I should point out that if I run:

```
oc expose dc wsgi-hello-world --port 8080
oc expose service wsgi-hello-world
```

then it does result in the web application being accessible, with the image for it being correctly built using the Docker image I expected it to use. That is, it used the Docker image referenced by the local image stream to the project called ``python``.

What did not work properly is the following.

1 - Even though there was a local image stream to the project called ``python``, it for some reason went off to Docker Hub to look for a Docker image called ``python`` instead. Even ignored ``python`` in ``openshift`` namespace.

```
   --> Found Docker image 0237868 (29 hours old) from Docker Hub for "python"
```
2 - It tried to create a local image stream called ``python`` corresponding to the Docker image it found on Docker hub. It couldn't do this as there already existed a local image stream in the project called ``python`` as I created that above.

```
    * An image stream will be created as "python:latest" that will track this image
    error: imageStream "python" already exists
```

3 - It looked at the Docker image called ``python`` it found on Docker Hub for what ports were exposed. It found none, so didn't create a service. This meant I had to first expose the dc and specify a port to create the service before could then create a route.

```
    * The image does not expose any ports - if you want to load balance or send traffic to this component
      you will need to create a service with 'expose dc/wsgi-hello-world --port=[port]' later
```

4 - Although it failed to replace the local ``python`` image stream with that from Docker Hub, it still used the local ``python`` image stream as the source for the S2I builder to use. I can't complain on this point though as this is what I wanted it to do.

So I got the result I wanted, but had to do an extra step of exposing the dc first.

What I would expect to happen is that when looking for a ``python`` image stream for the S2I builder, that when it sees it already has a local image stream to the project, that it uses the Docker image in it tagged with ``latest`` from the outset and not go off to Docker Hub and get confused.

This would be to me the most logical and most useful thing as it would allow users to override from their own project the default image streams for S2I builders in the ``openshift`` namespace and so allow them to use their own S2I builders with the automatic language detection.

Yes I know that I can use ``~`` or ``--image-stream`` option to ``oc new-app``, but want the automatic behaviour.

```
$ oc project
Using project "python-examples" on server "https://openshift-master.evgus.openshift3roadshow.com:443".

$ oc new-app python-examples/python~https://github.com/GrahamDumpleton/wsgi-hello-world.git
--> Found image 356b960 (15 minutes old) in image stream "python" under tag :latest for "python-examples/python"
    * A source build using source code from https://github.com/GrahamDumpleton/wsgi-hello-world.git will be created
      * The resulting image will be pushed to image stream "wsgi-hello-world:latest"
    * This image will be deployed in deployment config "wsgi-hello-world"
    * Port 8080/tcp will be load balanced by service "wsgi-hello-world"
--> Creating resources with label app=wsgi-hello-world ...
    ImageStream "wsgi-hello-world" created
    BuildConfig "wsgi-hello-world" created
    DeploymentConfig "wsgi-hello-world" created
    Service "wsgi-hello-world" created
--> Success
    Build scheduled for "wsgi-hello-world" - use the logs command to track its progress.
    Run 'oc status' to view your app.
```

Just to round things out, I note that the following don't work either.

If using ``~``, you cannot just use ``python`` and it must be qualified by the project name as above as otherwise it still goes off to Docker Hub.

```
$ oc new-app python~https://github.com/GrahamDumpleton/wsgi-hello-world.git
error: the resolved match "python" for component "python" cannot build source code - check whether this is the image you want to use, then use --strategy=source to build using source or --strategy=docker to treat this as a Docker base image and set up a layered Docker build
```

The ``--image-stream`` option doesn't require that though and works without being scoped.

```
$ oc new-app https://github.com/GrahamDumpleton/wsgi-hello-world.git --image-stream python
I0115 11:59:17.387305   35160 newapp.go:533] Using "https://github.com/GrahamDumpleton/wsgi-hello-world.git" as the source for build
--> Found image 356b960 (18 minutes old) in image stream "python" under tag :latest for "python"
    * The source repository appears to match: python
    * A source build using source code from https://github.com/GrahamDumpleton/wsgi-hello-world.git will be created
      * The resulting image will be pushed to image stream "wsgi-hello-world:latest"
    * This image will be deployed in deployment config "wsgi-hello-world"
    * Port 8080/tcp will be load balanced by service "wsgi-hello-world"
--> Creating resources with label app=wsgi-hello-world ...
    ImageStream "wsgi-hello-world" created
    BuildConfig "wsgi-hello-world" created
    DeploymentConfig "wsgi-hello-world" created
    Service "wsgi-hello-world" created
--> Success
    Build scheduled for "wsgi-hello-world" - use the logs command to track its progress.
    Run 'oc status' to view your app.
```

So ideally an unscoped image stream name used with ``~`` should work like ``--image-stream`` if there is an image stream with than name in the local project.

Finally, it doesn't work in the same ways if the image stream is actually just a tag reference to another image stream in the local project.

```
$ oc new-build https://github.com/openshift/sti-python.git --context-dir=2.7 --name=python-27-centos7
...

$ oc tag python-examples/python-27-centos7:latest python-examples/python:latest
...

$ oc new-app https://github.com/GrahamDumpleton/wsgi-hello-world.git
--> Found Docker image 0237868 (33 hours old) from Docker Hub for "python"
    * An image stream will be created as "python:latest" that will track this image
    * The source repository appears to match: python
    * A source build using source code from https://github.com/GrahamDumpleton/wsgi-hello-world.git will be created
      * The resulting image will be pushed to image stream "wsgi-hello-world:latest"
      * Every time "python:latest" changes a new build will be triggered
    * This image will be deployed in deployment config "wsgi-hello-world"
    * The image does not expose any ports - if you want to load balance or send traffic to this component
      you will need to create a service with 'expose dc/wsgi-hello-world --port=[port]' later
--> Creating resources with label app=wsgi-hello-world ...
    error: imageStream "python" already exists
    ImageStream "wsgi-hello-world" created
    BuildConfig "wsgi-hello-world" created
    DeploymentConfig "wsgi-hello-world" created
```

**Comment by smarterclayton** [comment]
Local image stream should always take priority over the hub.

**Comment by smarterclayton** [comment]
@bparees or @csrwng for triage

**Comment by bparees** [comment]
1) it's failing because we get multiple matches (the openshift python imagestream and the user's python imagestream) during imagestream searching, and as a result we ignore all the results from the imagestream searching and fallthrough to dockerhub searching.

basically ErrMultipleMatches isn't being handled properly.  I assume as soon as we get ErrMultpleMatches we should fail out and tell the user we need more information to proceed.

2) not the core issue here.

3) is a sympton of (1) (it found the wrong image, it's not going to find the right ports or create the right service)

4) I have no idea why it created the From reference as an ImageStreamTag reference instead of a DockerImage reference, probably something crossed up in how it found the imagestream(s) earlier but didn't use them.

**Comment by smarterclayton** [comment]
1 ErrMultipleMatches for exact matches should definitely stop processing, not continue to the next tier.

**Comment by GrahamDumpleton** [comment]
Why when you use the ``--image-stream`` option without providing a namespace does it appear not to error and instead does the right thing then? Surely in that case you would have multiple matches as well if it used same algorithm as when doing auto language selection or are using it with ``~``.

**Comment by bparees** [comment]
when you specify --imagestream the code doesn't use the "WeightedResolver" which is a "super-resolver" that attempts to resolve "python" as both an imagestream and a docker image. 

it's the WeightedResolver that has the mishandling of multiplematches and falls through to docker.

it would appear the straight resolver probably *also* has a bug in that it is not detecting multiplematches at all, it just uses the first match it found (the one in your project).

**Comment by bparees** [comment]
the code appears to use a FirstMatchResolver in that case.  I don't know why.  @smarterclayton ??
```
		input.Argument = fmt.Sprintf("--image-stream=%q", input.From)
		input.Searcher = c.imageStreamSearcher
		if c.imageStreamSearcher != nil {
			input.Resolver = app.FirstMatchResolver{Searcher: c.imageStreamSearcher}
		}
```

**Comment by GrahamDumpleton** [comment]
As a user I would expect there to be a precedence order of local project, openshift, registry. So for me it stopping when finding the one in the project is exactly what I would expect and want to happen, at least for the S2I builder case when using Source strategy. It allows me to override what is in the openshift namespace as far as S2I builders is concerned.

Because what S2I builder is used is hardwired in new-app and can't be changed by a user, having a precedence order is only way I can affect what image is used for S2I when wanting to have auto language detection still work.

Without that, it means then me with my third party provider hat on, can't make available image stream definitions for S2I builders that anyone can load up in a local project and then work without always having to name explicitly the image stream for the alternate builders.

**Comment by GrahamDumpleton** [comment]
BTW. Imagine what is going to happen if you don't use precedence.

So some user creates an S2I builder in their local project called ``intercal`` for that programming language.

They quite happily then use:

```
oc new-app intercal~https://....
```

Then at some point we think that having an ``intercal`` builder in the ``openshift`` namespace is a wonderful idea and it is added.

The next time the user runs that command, which has always worked, it now breaks because of the multiple matches resulting from it now also being in the ``openshift`` namespace. You would have one very confused user.

**Comment by bparees** [comment]
> As a user I would expect there to be a precedence order of local project, openshift, registry. So for me it stopping when finding the one in the project is exactly what I would expect and want to happen, at least for the S2I builder case when using Source strategy.

If there are multiple things that could have matched what you specified, I don't think it's ever appropriate to stop on the first one and not tell the use they shadowed another value.  You could pretty easily accidentally hide the openshift "python" imagestream with something that's not actually an s2i builder and I don't want to troubleshoot users who managed to create a "python" imagestream in their project that is not an s2i builder.

> Because what S2I builder is used is hardwired in new-app and can't be changed by a user, having a precedence order is only way I can affect what image is used for S2I when wanting to have auto language detection still work.

I think this speaks more to the challenges and dubious value of autodetection than a problem with the way it's been implemented here.  Imho autodetection makes for great demos.  Anyone who gets beyond "how do i run something in 5 seconds" is going to be explicit about how they want to build their application.

> The next time the user runs that command, which has always worked, it now breaks because of the multiple matches resulting from it now also being in the openshift namespace. You would have one very confused user.

only if our error message is not useful enough to explain what happened and what they need to do.

**Comment by bparees** [comment]
discussed w/ @smarterclayton, reducing to non-blocking p2.

**Comment by smarterclayton** [comment]
Agree with Graham on the precedence order - that's the initial design.
Next week we'll get something more correct in - it's just unfortunate
we caught this this late.
