### ISSUE TITLE
Avoid showing low level warnings in "oc status -v"

### ISSUE THREAD

**Issue by MrCoder** [openshift/origin#6673]
In the current implementation (`oc v1.1-772-gd288e40 kubernetes v1.1.0-origin-1107-g4c8e6f4`), `oc status -v` shows restarting of container as Warnings.

```
Warnings:
  * container "registry" in pod/docker-registry-1-cena8 has restarted 3 times
  * container "router" in pod/router-1-lv4vn has restarted 4 times
```

However, restarts could have happened due to restarting of docker service or by intention. There should be a way:
1. Either delete these warnings after review;
2. Or distinguish intentional restarts and accidents and only show the later.

For the second scenario, it is still better to have a way to reset that warnings after problem is solved.

Related SO question: http://stackoverflow.com/questions/34782962/can-i-delete-warnings-in-openshift-origin

**Comment by deads2k** [comment]
How about only detecting X restarts in the past Y minutes?  That would have them scrolling off the list eventually.

**Comment by liggitt** [comment]
I thought the restart count was rolling... maybe I'm wrong
