### ISSUE TITLE
On the keepalive dc, the environment OPENSHIFT_HA_USE_UNICAST do nothing

### ISSUE THREAD

**Issue by jkroepke** [openshift/origin#6674]
Hi,

currently we try to run multiple keepalived pod for different services in the same network segment.
Since every keepalived pods runs with the same vrrp id, we require the option OPENSHIFT_HA_USE_UNICAST = true

Is this feature enabled in the current version of openshift?

**Comment by jkroepke** [comment]
Hi!

I notice, OPENSHIFT_HA_USE_UNICAST require all host ip as comma seperated list. This feature coming in OpenShift 3.1.

**Comment by ikke-t** [comment]
wouldn't this do the same: https://github.com/openshift/origin/pull/6775 ?
It doesn't do UNICAST, but gives you option to alter the ID of keepalived VRRP. Then you don't need to know the IPs.

**Comment by jkroepke** [comment]
I think, the vrrp offset option is good enough.

Ilkka Tengvall <notifications@github.com> schrieb am Do., 10. März 2016,
10:20:
