### ISSUE TITLE
oc new-app with repo containing dockerfile does the wrong thing

### ISSUE THREAD

**Issue by bparees** [openshift/origin#6675]
if the repo contains a dockerfile, new-app is creating a Dockerfile input in the buildconfig (containing the content of the dockerfile from the repo), which means if the user updates their dockerfile in the repo and rebuilds, they won't get any changes since the dockerfile defined in the BC takes precedence.

**Comment by bparees** [comment]
@smarterclayton fyi

**Comment by rhcarvalho** [comment]
Introduced in #6615

**Comment by rhcarvalho** [comment]
I'm working on a fix.
