### ISSUE TITLE
flake on swagger generation - docker not found, connection refused

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6676]
flaking on Swagger generation [here](https://travis-ci.org/openshift/origin/jobs/102621596#L210):
```
/home/travis/gopath/src/github.com/openshift/origin/hack/../hack/util.sh: line 474: docker: command not found
[INFO] Dumping all resources to /tmp/openshift-swagger/logs/export_all.json
The connection to the server 127.0.0.1:38443 was refused - did you specify the right host or port?
```

**Comment by stevekuznetsov** [comment]
This only seems to occur on Travis

**Comment by stevekuznetsov** [comment]
@liggitt if Travis can't use Docker, we should just not verify Swagger spec on that platform, yes?

**Comment by liggitt** [comment]
we don't need docker to verify swagger spec...

**Comment by liggitt** [comment]
that's getting logged because the dump_container_logs func is doing docker things at process exit, and docker doesn't exist

**Comment by stevekuznetsov** [comment]
We need to start the server to verify the spec, and if something goes wrong, we want to clean up, for which our current code uses Docker. Should we amend the cleanup? If we fail the Travis image is killed anyway and there's not a good reason to clean up anymore.

**Comment by deads2k** [comment]
@stevekuznetsov if docker isn't available on travis, I feel pretty confident we didn't create any resources in docker.  You'd be able to skip those parts.

**Comment by smarterclayton** [comment]
Isn't this fixed now?
