### ISSUE TITLE
[Question] What's the advantage of V3 over Kubernetes?

### ISSUE THREAD

**Issue by resouer** [openshift/origin#669]
After played around with V3, I admit that it's much more convincing than OpenShift2. Personally speaking, v3 has a lot of common with Kuber (and it using kuber, of course), but as I'm also a user of Kubernetes, I'm confused about v3 outweight Kuber. Can anyone give me details about that?

**Comment by smarterclayton** [comment]
Sure - Kube is about low level primitives (today).  OpenShift integrates source, build, image promotion, and automated deployment, as well as driving routes (L7 routing, which may eventually go upstream), team and organization access control (including user synchronization to LDAP, quota, resource limits, accounting, billing), and administrative tools like templates, a console UI, administrative integration into things like Cockpit and higher level management tools.

OpenShift is about developer focused flows, and ops working together in teams or large groups, as well as trivial and easy setup.  We think of OpenShift as complementing Kubernetes, and as soon as we get the ACL sorts of issues sorted out, you should be able to run OpenShift on top of Kubernetes.

**Comment by resouer** [comment]
@smarterclayton Amazing. So actually OpenShift is trying to make Kuber works in a PaaS style, right. 

But I did not find any information about Console or Dashboard (even http://docs.openshift.org/latest/using_openshift/console.html#overview is blank). 

If it is possible , really hoping to see a more PaaS like guide/screenshot/video to lead me to the right way. I have walked thru the examples in the README, but I can't wait to play it like a real PaaS! ^^

BTW I'm running it with `docker run -d --name "openshift-origin" --net=host --privileged`

**Comment by blysik** [comment]
I had the same question.  We love OpenShift v2 to give our developers self-service deployments and a nice UI to handle many things.

How is that coming along in v3?  None of the articles I've read have mentioned anything about a console or dashboard.  (Unless I've missed it.)

**Comment by smarterclayton** [comment]
We do indeed have a console, which will get features added over time to let you visualize and manage your applications.

Jessica, can you add a sentence or two to the readme so folks know to look for it?

----- Original Message -----

**Comment by liggitt** [comment]
Closing since console docs and readme have been updated:

http://docs.openshift.org/latest/using_openshift/console.html#overview
https://github.com/openshift/origin/blob/master/README.md#management-console
