### ISSUE TITLE
Openshift 1.0.8-0.git.7227.8f1868d removed from maxamillion repository

### ISSUE THREAD

**Issue by usawa** [openshift/origin#6695]
Hi,

After an "unexpected" centos7 upgrade today (we forgot to disable maxamillion-origin-next-epel-7.repo), we accidentally upgraded to origin 1.1.0.1. But the rollback is not possible to 1.0.8 : packages were removed. 

Is it possible for you to get them back ?

Thank you.

**Comment by tdawson** [comment]
It looks like copr keeps only the latest builds.
If you want to grab any of the src.rpm's of any of the builds you can find them in the projects builds area.
https://copr.fedoraproject.org/coprs/maxamillion/origin-next/builds/
If you look at the 1.0.8 build page, you will see that the src.rpm came from here.
https://tdawson.fedorapeople.org/copr/openshift/origin-1.0.8-0.git.7227.8f1868d.el7.src.rpm
You should be able to rebuild the packages from the source rpm.

I will look into the feasibility of keeping the last of each major version (1.0.8, 1.1.x, 1.2.x ... etc)

**Comment by usawa** [comment]
Thank you for your answer. I rebuilt from the src.rpm and all went well. I also created a private yum repository to keep them.

**Comment by tdawson** [comment]
We are currently working on getting origin in Fedora, EPEL and CentOS.  Once it is there, there will be ways to grab past packages from Koji.  At that point we'll look at the feasability of repo's based on past stable rpms.  For now I'm going to close this issue.
