### ISSUE TITLE
Provide Linux on System Z (s390x) support

### ISSUE THREAD

**Issue by rposts** [openshift/origin#6699]
Hello,

I was able to build and test few Docker images on OpenShift Origin 3.  I understood OpenShift 3 required following:
1. Go
2. Docker
3. Kubernetes

IBM has recipes for building Go/Kubernetes and Docker distribution available on Linux on System Z.  Here are the links for appropriate components:
1. Go on Linux on System Z: https://github.com/linux-on-ibm-z/docs/wiki/Building-Go
2. There is a pull request on Kubernetes on Linux on System Z which is merged with master: https://github.com/kubernetes/kubernetes/pull/16662
3. Docker distribution: http://www.ibm.com/developerworks/linux/linux390/docker.html

Once I had merged Kubernetes changes with OpenShift's Kubernetes distribution I was able to build and run OpenShift 3.  In the process I had used base RHEL 7.1 images and created dependent OpenShift images from scripts provided (with some modifications).

I wonder if community is able to adapt Linux on System Z as one of the supported architecture now that supporting bits are in place?

Thanks.

**Comment by bparees** [comment]
@smarterclayton i assume this has upstream requirements.  also not sure where we'd want to prioritize it.

**Comment by bparees** [comment]
(wrong button)

**Comment by shawndwells** [comment]
Bump on this. Now that Docker has announced formal support for System z, where does OpenShift stand?

Ref: https://thenewstack.io/docker-enterprise-edition-expands-legacy-systems/
``
You could call this Docker’s coming out party for the enterprise. Earlier this year, the company released a consolidated Docker Enterprise Edition, gathering its corporate container technologies into a single platform and brand. Wednesday, **that platform was further updated to include Z System support**, policy management, and multitenancy, thus creating a cross-platform management system for enterprise applications.
``
