### ISSUE TITLE
Disable start build button when BC has certain annotation

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#6703]
See details on annotation change here: https://github.com/openshift/origin/pull/6185#issuecomment-172556695

**Comment by jwforres** [comment]
cc @spadgett

**Comment by jhadvig** [comment]
@jwforres could you assign the issue to me ? Will sync with @mnagy to track the bc reaper pr and once it lands will update the build trigger button logic

**Comment by jwforres** [comment]
Fixed
