### ISSUE TITLE
Re-pushing an tag into registry keeps old and new images in imagestream

### ISSUE THREAD

**Issue by stefwalter** [openshift/origin#6705]
When I change an image tag by rebuilding it on the command line, and use ```docker push``` to push it into the image registry ... the resulting image stream contains both the old and new images listed under the tag:

When using Origin as an image registry, this is not expected behavior.

```
{
    "kind": "ImageStream",
    "apiVersion": "v1",
    "metadata": {
        "name": "juggs",
        "namespace": "marmalade",
        "selfLink": "/oapi/v1/namespaces/marmalade/imagestreams/juggs",
        "uid": "84e3a672-b44e-11e5-a4da-5254009e00f1",
        "resourceVersion": "3120",
        "creationTimestamp": "2016-01-06T08:21:43Z",
        "annotations": {
            "openshift.io/image.dockerRepositoryCheck": "2016-01-06T08:21:43Z"
        }
    },
    "spec": {},
    "status": {
        "dockerImageRepository": "172.30.87.3:5000/marmalade/juggs",
        "tags": [
            {
                "tag": "2.11",
                "items": [
                    {
                        "created": "2016-01-06T08:21:43Z",
                        "dockerImageReference": "172.30.87.3:5000/marmalade/juggs@sha256:b074b7b7905895741f7425ab4e78b9df384aaa518258d2e81d9e904ecf6c9f0f",
                        "image": "sha256:b074b7b7905895741f7425ab4e78b9df384aaa518258d2e81d9e904ecf6c9f0f"
                    }
                ]
            },
            {
                "tag": "2.5",
                "items": [
                    {
                        "created": "2016-01-18T16:15:54Z",
                        "dockerImageReference": "172.30.87.3:5000/marmalade/juggs@sha256:2cdf3d40eeb384442fda3c26fd687cbee408b34472854f3b49d0a161d32a61be",
                        "image": "sha256:2cdf3d40eeb384442fda3c26fd687cbee408b34472854f3b49d0a161d32a61be"
                    },
                    {
                        "created": "2016-01-06T08:21:46Z",
                        "dockerImageReference": "172.30.87.3:5000/marmalade/juggs@sha256:d0329beccad118aa937e839d536d753ee612b67f8feb6adb519e7f5aa6e75fbe",
                        "image": "sha256:d0329beccad118aa937e839d536d753ee612b67f8feb6adb519e7f5aa6e75fbe"
                    }
                ]
            },
            {
                "tag": "latest",
                "items": [
                    {
                        "created": "2016-01-06T08:21:43Z",
                        "dockerImageReference": "172.30.87.3:5000/marmalade/juggs@sha256:0885eeaec4514820b2c879100425e9ea10beaf4412db7f67acfe53b4df2b9450",
                        "image": "sha256:0885eeaec4514820b2c879100425e9ea10beaf4412db7f67acfe53b4df2b9450"
                    }
                ]
            }
        ]
    }
}
```

CC @aweiteka @smarterclayton

**Comment by smarterclayton** [comment]
Not sure what you mean - the first "item" is newest, but the history is
maintained.  Can you describe what you expect to happen here and what you
pushed?

**Comment by stefwalter** [comment]
I would expect that pushing a tag replaces it and does not require further action to go and cleanup the state of things ... but I guess using Image Streams as Image Repositories means there's extra complexity like this for many tasks.

Not a bug, closing.

**Comment by smarterclayton** [comment]
It's also useful for a history - such as if you want to rollback to a
previous tag.

**Comment by stefwalter** [comment]
Right ... it's just worth noting that most "normal" tasks that you might want to accomplish with a registry are have unpredictable and unexpected behavior:

 * Task: Replace a tag -> Doesn't "actually" replace.
 * Task: Delete a tag -> Doesn't "actually" delete.

... and so on.

**Comment by smarterclayton** [comment]
Replace does update the tag - not sure what you mean?   A pull and the
rest of the system will never look at n-1 or treat that as the tag.

Delete tag should delete the status field if you operate on the tag directly:

    oc delete istag/foo:bar

should delete the tag in spec and status.  You immediately lose access
to those images.

That's the other reason that we remember tags - because it conveys
access to an image.  If you delete the reference and no one else in
the project references the image you *cant* pull that image by id (so
old deployments can't pull anymore).  Prune is the administrative
cleanup process that removes that history when it is no longer needed
for correctness (time + ref count).
