### ISSUE TITLE
Rename scripts that run tests for web console

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#6721]
Originally suggested in [this PR](https://github.com/openshift/origin/pull/6667#issuecomment-172903155).

Currently, to run tests for web console you would:

``` bash
hack/test-assets.sh
# followed by
cd assets
grunt test-integration --suite rest_api
```

We should rename `test-assets.sh` to something that shows it is for unit tests, then create an e2e script.  Potentially we could do something like this:

```
hack/test-assets-unit.sh
hack/test-assets-e2e.sh
hack/test-assets-integration.sh
hack/test-assets-all.sh 
```

**Comment by benjaminapetersen** [comment]
@jwforres @spadgett forgot to mention you back when this was made.  I can take this issue.  Any thoughts on the format welcome.

**Comment by jwforres** [comment]
this issue is pretty outdated at this point, especially now that we've got the Makefile and we just run most of our tests directly with grunt when running locally
