### ISSUE TITLE
Preserve log data for destroyed pod

### ISSUE THREAD

**Issue by mnaughto** [openshift/origin#6725]
Is there any way that things could be tweaked so that I can go into Browse->Pods->(frequently crashing pod)->Logs and view the latest log or a history of logs between restarts? This would make it easier to determine the cause of a problem. 

Right now, the only way to see the log of a crashing pod is to scale it to zero, scale it up, click on the pod count, click on the pod, and click on logs, all hopefully before it restarts again. 

Ideally, I'd be able to view either a history of failure logs or the most recent failure log, rather than getting the message saying "An error occurred loading the log."

Does this all make sense?

**Comment by deads2k** [comment]
Take a look at `oc logs -p`.  I think it does exactly what you want, "view logs for the previous instance of the container".

**Comment by mnaughto** [comment]
Got it. It'd be nice if that could make its way into the web interface at some point.

**Comment by deads2k** [comment]
> Got it. It'd be nice if that could make its way into the web interface at some point (I guess that's what I'm requesting here).

/cc @jwforres

**Comment by jwforres** [comment]
There is a k8s issue open related to this, the API needs to add a flag that will always return the logs for the latest container that was run / is running, the web console will update to always send that flag.

**Comment by benjaminapetersen** [comment]
@jwforres do you remember which issue? I took a stab at finding it to add a reference here but was not able to land on it.

**Comment by jwforres** [comment]
@benjaminapetersen i dont, @smarterclayton mentioned there was one, but not what it was

**Comment by smarterclayton** [comment]
Look under my issues in Kube with label usability

**Comment by mnaughto** [comment]
This is all I could find that seemed related: https://github.com/kubernetes/kubernetes/pull/13780

There's also this (linked to in that pull request): https://github.com/openshift/origin/pull/3943

**Comment by jwforres** [comment]
Maybe this? https://github.com/kubernetes/kubernetes/issues/15826

**Comment by jwforres** [comment]
according to @smarterclayton the fix is that the API server is going to return the latest available container log, whether that container has already died or is currently running. so we'll need that fix rebased from kube

**Comment by spadgett** [comment]
Looks like this is fixed after the last rebase.

![logs](https://cloud.githubusercontent.com/assets/1167259/13143125/b374aa06-d60f-11e5-8c0e-3ef6803dc775.png)
