### ISSUE TITLE
"Builder Image" tooltips wont disappear when clicking on the image tile with hovered icon

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#6732]
When hovering on the icon and clicking on the tile
![screenshot-12](https://cloud.githubusercontent.com/assets/1668218/12450232/a955d9a8-bf82-11e5-8b30-f12d86f8adad.png)
the tooltip wont disappear 
![screenshot-13](https://cloud.githubusercontent.com/assets/1668218/12450233/aab1449a-bf82-11e5-802d-0226ed98433f.png)
@jwforres @spadgett fyi

**Comment by spadgett** [comment]
Yeah, known issue :(

#6490

**Comment by jwforres** [comment]
Duplicate, closing
