### ISSUE TITLE
openshift receives wrong IP address on start

### ISSUE THREAD

**Issue by BSchwetzel** [openshift/origin#6733]
Upon starting the openshift-server on a Hetzner dedicated server it gets the wrong ip, leading to different problems. To provide an example:

The server has the IP address 111.222.255.154, but openshift sets its own IP as 111.222.255.129. This might have to do with Hetzner's network setup, where a server has to have a pointopoint (or "peer" in centos-speak?). This leads to the following output of "ip a":

inet 111.222.255.154 peer 111.222.255.129/32 brd 111.222.255.154 scope global eth0

As you can see the address openshift assigns to itself is the peer I'm required to have in my network config. So for me two questions arise: Where does openshift get its own IP and is there a workaround I can try to get it up and running? Setting the IP in the config files won't work because then it isn't included in the TLS cert, which I can't recreate when reading the config, or I've been doing it wrong (./openshift start --master-config=openshift.local.config/master/master-config.yaml --node-config=openshift.local.config/node-openshift/node-config.yaml --create-certs=true)?

Any help would be appreciated, thanks!

**Comment by deads2k** [comment]
Have you tried the `--master` and `--public-master` flags?  Also, you can create certificates separately by running `oadm ca ****` commands.

**Comment by BSchwetzel** [comment]
Thank you for your input. 

Recreating the certificates will start the server, but TLS handshake errors are present all over the log, which might have to do with me not knowing which certs need to be replaced. The specific error I get every few seconds:

`E0120 15:16:15.374013    2670 event.go:207] Unable to write event: 'Post https://111.222.255.154:8443/api/v1/namespaces/default/events: x509: certificate signed by unknown authority' (may retry after sleeping)`

I used `oadm create-master-certs`, `oadm ca create-signer-cert` and `oadm ca create-server-cert`for the etcd-cert. 

Using the `--master` and `--public-master` flags seems to affect most, but not all steps of execution, as the following will still be printed:

`I0120 15:20:56.659096    2837 master.go:401] Will report 111.222.255.129 as public IP address.`
`W0120 15:20:58.050370    2837 controller.go:290] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default  dd2d5378-bf80-11e5-80dd-901b0e8d69ed 8 0 2016-01-20 15:19:49 +0100 CET <nil> <nil> map[] map[]} [{[{111.222.255.129 <nil>}] [] [{https 8443 TCP} {dns 53 UDP} {dns-tcp 53 TCP}]}]}`

I seem to be able to use the web console nonetheless, but it just doesn't seem quite right..

**Comment by deads2k** [comment]
> Using the --master and --public-master flags seems to affect most, but not all steps of execution, as the following will still be printed:

Can you include your `master-config.yaml`, your openshift version, and your command for generating the config or starting openshift?  `--master` sets `kubernetesMasterConfig.masterIP` for me, which is respected as long as it isn't a loopback.

**Comment by BSchwetzel** [comment]
Oh, I see. I used the URL of the server in the form of `https://openshift.my.domain`, using the IP works. So the workaround seems fine, but still reading the wrong IP seems to be a bug (albeit of lower priority as a workaround exists), and seems to be caused by `SCOPE="peer 111.222.255.129"` in /etc/sysconfig/network-scripts/ifcfg-eth0. This seems to be the case in 1.1.0.1 and 1.1.1 at least, I haven't testet older releases. If this is expected behavior I'm curious to know the reasoning behind it :-)

Thank you very much for your help!

**Comment by deads2k** [comment]
Kube needs an address that other components can talk to it on.  If one isn't specified, they start searching through to find one used as a default route or whatever they can find.  This function for detail: https://github.com/kubernetes/kubernetes/blob/master/pkg/util/util.go#L376

**Comment by BSchwetzel** [comment]
I see that it is searching for an IP, which seems to call the function Addr() in Go itself: https://golang.org/src/net/interface.go

As my problem is not the search, but the choice of its result (being an IP that is not an IP of the server origin is running on). After using the script from https://github.com/kelseyhightower/go-examples/blob/master/network-interfaces.go I now think the bug may be in Go itself, as even this script returns the wrong IP address.. Which means this is no longer an Origin bug for me. Thank you for pointing me to the relevant code piece and therefore enabling me to understand where this behavior comes from!
