### ISSUE TITLE
Add ability to edit deployment configurations from web console

### ISSUE THREAD

**Issue by mnaughto** [openshift/origin#6744]
Unless I'm missing something, right now, it looks like you can *see* the deployment configuration, but that you can't do anything about it. It'd be nice if there were a place to edit those via the console.

**Comment by bparees** [comment]
Things are coming on the buildconfig front, less sure about deploymentconfigs.  @jwforres should be able to point to the relevant feature cards.

**Comment by jwforres** [comment]
so you can edit almost everything by using the "Edit (Raw)" which lets you modify the YAML. Its available in the little kebab menu on the top right of a page.

as far as the more user friendly editors, for build configs this is merging soon https://trello.com/c/Abzi81C2  but it doesn't let you modify _everything_ that's possible, we started with the most common use cases.  For deployment configs, today we let you modify scaling, soon we'll let you modify cpu/mem requests and limits on the containers (part of https://trello.com/c/23NdtCwN ).  Just added a card to provide an editor for deployment strategy/hooks https://trello.com/c/2rDfr6Ma

I'd be interested in knowing what you think you will want to edit frequently.  We are trying to hit important use cases first.

**Comment by jwforres** [comment]
cc @jhadvig @spadgett

**Comment by mnaughto** [comment]
Specifically, we're looking for an easier way of modifying environment variables for running applications. This isn't something that's going to happen *a lot*, but it should be doable after a project is created.

Not sure what "kebab" menu you're talking about, @jwforres. We might have a slightly older build running.

**Comment by jwforres** [comment]
@mnaughto
![kebab](https://cloud.githubusercontent.com/assets/1467629/12459862/e03641a0-bf7e-11e5-9da7-52946ad0e371.png)
![kebab-dropdown](https://cloud.githubusercontent.com/assets/1467629/12459863/e039eb3e-bf7e-11e5-98f2-f9a91fe7163f.png)
![yamleditor](https://cloud.githubusercontent.com/assets/1467629/12459889/07288868-bf7f-11e5-9424-0874b5d66967.png)

**Comment by jwforres** [comment]
So specifically for environment there is an in progress PR to show environment variables in their own tab everywhere that env vars are relevant:

https://github.com/openshift/origin/pull/6449

So in the future we would probably have a dedicated env var editor from that tab, maybe inline, having decided on the design yet.

But the YAML editor should get you what you need in the short term without having to leave the web console.

**Comment by mnaughto** [comment]
There's also this for build configurations, but not deployments (I don't think). https://github.com/openshift/origin/pull/6528. Has the YAML editor change made it into master yet?

**Comment by spadgett** [comment]
@mnaughto Yes, the YAML editor is in master.

**Comment by brettneese** [comment]
Hmm. We just deployed 3 days ago, using the Ansible installer. We definitely don't see any of this, and we should have the correct rights. 

Sorry if this is unrelated to the issue, but how do we update to the newest version of the web console? Just run the ansible installer again?

**Comment by jwforres** [comment]
if you are deploying origin, we just cut origin 1.1.1 two days ago, this is in 1.1.1

**Comment by jwforres** [comment]
@sdodson see question above about how to update to the latest version of the console using the ansible installer

**Comment by jhadvig** [comment]
@mnaughto the next OS release will also contain buildConfig form editor, in which you can update all type of sources (except the binary source), build environment variables, builder image, output image and triggers

**Comment by sdodson** [comment]
@brettneese 
@brettneese 

> Sorry if this is unrelated to the issue, but how do we update to the newest version of the web console? Just run the ansible installer again?

Running ansible again should work however it will overwrite any configuration file changes you've made since you installed the first time. To avoid that we have playbooks that perform targeted operations for each upgrade scenario, you'd want to run the v3_1_minor upgrade playbook (v3.1 OSE corresponds to Origin v1.1).

Make sure you have the latest openshift-ansible code base then run

`ansible-playbook playbooks/byo/openshift-cluster/upgrades/v3_1_minor/upgrade.yml`

The docs have yet to be updated for v1.1.1 but here's the general documentation.

**Comment by jwforres** [comment]
closing since we are tracking the deployment config editor story in trello
