### ISSUE TITLE
postGIS extensions unavailable in the postgresql image

### ISSUE THREAD

**Issue by ryanj** [openshift/origin#6745]
The postGIS extension is available for use with the build of postgresql in Openshift Online:

```
CREATE EXTENSION postgis;
```

It would be nice to have the same default set of extensions available for v3 users as well.

**Comment by bparees** [comment]
@ryanj in the meantime you can of course setup your own docker build in openshift that adds a layer to the openshift postgres image, and then deploy that instead of directly deploying the openshift postgres image.

**Comment by ryanj** [comment]
I've heard that postGIS extensions are available in the crunchdb pg image. Adding their imageStream to the template might provide another solution.

**Comment by mnagy** [comment]
@praiskup, I think this means we need to add postgis package to the SCL collection?

**Comment by praiskup** [comment]
@mnagy, right, we would have to add it there.  Note that that there is no progress yet on
this topic, there is fair amount of dependencies not available in RHEL.
https://bugzilla.redhat.com/show_bug.cgi?id=1300650

**Comment by mfojtik** [comment]
@bparees that will not work for online image right? unless you build it yourself locally/on hub and push it to up to online :-)

**Comment by bparees** [comment]
@mfojtik until online offers docker builds, correct.  doesn't strike me as a huge blocker.

**Comment by bparees** [comment]
@mfojtik and to be clear i'm just offering a temporary workaround, not saying "we would never do this because you can do it yourself"

**Comment by bparees** [comment]
@hhorak @eliskasl can you add postGIS extensions to the SCL packaging wishlist?

**Comment by hhorak** [comment]
It's already been tracked on the wishlist for some time (https://bugzilla.redhat.com/show_bug.cgi?id=1008506), not easy to do and beyond our resources right now..

**Comment by ryanj** [comment]
Thanks for the feedback. I was hoping that we could extend / add layers to our basic pg image.

I can tell people to use the CrunchyData team's image that provides PostGIS: https://github.com/CrunchyData/crunchy-postgres-container-94

**Comment by bparees** [comment]
@ryanj to be clear, you can do that, but we can't ship an image like that because we need the postGIS extension to come from an official SCL package, which doesn't exist yet.

**Comment by ryanj** [comment]
got it - don't use our image, we're blocked

**Comment by bparees** [comment]
reopening, we still do want to address this when an appropriate package is available that enables us to do so.

**Comment by manuelep** [comment]
I'd like to add a little contribution. I asked for help [commenting an issue of the crunchy-containers project](https://github.com/CrunchyData/crunchy-containers/issues/79).
Trying to apply what suggested ([here](https://github.com/manuelep/crunchy-containers/tree/postgis-test) you can find the edited source) I could create the image in my project but I had troubles during the creation of the container and logs were created.

**Comment by bparees** [comment]
moving this issue to the postgres image repo:
https://github.com/sclorg/postgresql-container/issues/225
