### ISSUE TITLE
Update web console tests to use page objects and improve markup by adding hooks for QE

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#6746]
Page objects are an abstraction layer.  Essentially turns this:

``` javascript
it('should delete a project', function() {
  h.goToPage('/project/' + project['name'] + '/settings');
  element(by.css(".action-button .fa-trash-o")).click();
  element(by.cssContainingText(".modal-dialog .btn", "Delete")).click();
  h.waitForPresence(".alert-success", "marked for deletion");
});
```

into one of these options:

``` javascript
// promise based. is a bit noisy:
it('should delete a project', function() {
settingsPage.visit()
.then(function() {
settingsPage.openMenu()
  .then(function() {
    settingsPage.deleteProject()
    .then(function() {
      settingsPage.confirmProjectDelete()
      .then(function() {
      settingsPage.expectSuccessfulDelete()
    });
  });
});
});
});

// though this may be even better & reduce more noise:
it('should delete a project', function() {
   settingsPage.visit();  // a page object should know how to visit itself
   settingsPage.openMenu(); 
   settingsPage.deleteProject();
   settingsPage.confirmProjectDelete();
   settingsPage.expectSuccessfulDelete();
});


// settingsPage is a separate file /test/page_objects/settings.js
// with functions like this:
exports.openMenu = function() {
    return element(by.css('.resource-actions-dropdown')).click();
};
```

in order to make tests more readable/maintainable by reducing the noise of the selector syntax.

In addition, we can use classes & mixins to abstract away some of these details & insulate ourselves from the frameworks we use:

``` html
<!-- lets reduce this: -->
<a class="fa fa-trash-o fa-fw">Delete</a>
<!-- into this -->
<a class="osc-delete">Delete</a>
```

and our SCSS/LESS can do:

``` scss
.osc-delete {
   // @mixin fa fa-trash-o fa-fw
}
```

Markup is smaller & more readable.  Classes have more meaning.  We can move from font-awesome if we want w/o redoing all our templates, breaking our tests & breaking QE tests.

**Comment by benjaminapetersen** [comment]
Perhaps this is better yet:
```javascript
// I tend to prefer the style with promises....
settingsPage.openMenu()
  .then(function() {
    settingsPage.deleteProject()
    .then(function() {
      settingsPage.confirmProjectDelete()
      .then(function() {
      settingsPage.expectSuccessfulDelete()
    });
  });
});
// though this may be the way to go & eliminate even more noise:
settingsPage.openMenu();
settingsPage.deteProject();
settingsPage.confirmProjectDelete();
settingsPage.expectSuccessfulDelete();

```

**Comment by spadgett** [comment]
Second option :)

**Comment by benjaminapetersen** [comment]
Yeah, I think so as well.  If we go to that I'll be happy with our tests.

**Comment by benjaminapetersen** [comment]
@jwforres as well for opinion.  I think above 2nd option might be the way to go.

**Comment by jwforres** [comment]
second is better for readibility, just for the sake of argument, what benefit would we get from using promises here

cc @jhadvig @fabianofranz @liggitt since we are proposing a new standard for how we write these tests moving forward

**Comment by benjaminapetersen** [comment]
Well, a lot of these actions are async.  Trusting a promise is better than a timeout in general, though I haven't dug into protractor enough to be extremely assertive yet.

**Comment by jhadvig** [comment]
+1 on the second approach

**Comment by spadgett** [comment]
> Well, a lot of these actions are async.

But they block.

> Trusting a promise is better than a timeout in general, though I haven't dug into protractor enough to be extremely assertive yet.

You have to have timeouts. No choice, right? Otherwise the test never fails if an expected element doesn't appear.

**Comment by fabianofranz** [comment]
Second option, but first option should work too. in most cases you should not need to handle the promise and `then` manually, but in some cases one promise needs the result of a previous one to work, so you need to guarantee the execution order with `then`.

>> Well, a lot of these actions are async.

> But they block.

Yeah. There is a queue and every browser interaction waits for all the previous ones before starting to execute.  

Some [good reference](http://spin.atomicobject.com/2014/12/17/asynchronous-testing-protractor-angular/).

**Comment by fabianofranz** [comment]
> You have to have timeouts. No choice, right? Otherwise the test never fails if an expected element doesn't appear.

One example I saw was the "Create" button when creating from image, that only enables when you fill the name and git repo. If the test fails filling the form, you have to have a timeout in the "create button enabled" check otherwise it will wait forever.

**Comment by benjaminapetersen** [comment]
Right, some are blocking.  If enough, we are prob good, or can use the promise syntax when necessary.

**Comment by jwforres** [comment]
The issue related to QE automation is covered by this bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1299865
