### ISSUE TITLE
Don't trust the hostname on any host

### ISSUE THREAD

**Issue by rrati** [openshift/origin#6747]
I'm attempting to install origin on 5 vms on an openstack cluster with neutron networking, which means I don't have dns of any kind.  I have set the following in my inventory file:

openshift_hostname="{{ ansible_default_ipv4.address}}"
openshift_public_hostname="{{ ansible_default_ipv4.address }}"
openshift_public_ip="{{ ansible_default_ipv4.address }}"

But the installation fails during master setup.  The configuration file has ips and no hostnames, but on startup there are failure messages related to sdn setup and a failure to lookup the hostname of the master:

Jan 20 15:20:23 <hostname>.novalocal origin-master[4658]: F0120 15:20:23.306653    4658 flatsdn.go:27] SDN initialization failed: lookup <hostname>.novalocal: no such host
Jan 20 15:20:23 <hostname>.novalocal origin-master[4658]: E0120 15:20:23.306587    4658 common.go:722] Failed to lookup IP address for node <hostname>.novalocal: lookup <hostname>.novalocal: no such host

**Comment by detiber** [comment]
In some cases (OpenStack deployments in particular), the hostname is not one that would be resolvable. We should allow for overriding the detected hostname and/or fall back to the IP if the hostname is not resolvable.

**Comment by timothysc** [comment]
If there is a work-a-round please denote that here. 

/cc @marun

**Comment by rrati** [comment]
The workaround I used was to set

openshift_set_hostname=true

But that has the consequence of preventing cloud integration afaik.  That was ok for my setup but I wouldn't say is a good workaround.

**Comment by marun** [comment]
Is the problem that the install is broken when using ip addresses for the the openshift_* values you list?  Or is the install using an incorrect address?

**Comment by rrati** [comment]
@marun something is broken in the master itself I think.  Everything in the config file is correct (ips, no hostnames), but the master is trying to use the hostname of the system it is running on instead of configured ips.
