### ISSUE TITLE
oc new-app is failing @ v 1.1.1

### ISSUE THREAD

**Issue by sudhaker** [openshift/origin#6751]
Single node setup as per http://sudhaker.com/10/install-the-latest-openshift-v3-on-centos-7-1

Everything was working as expected in 1.1 & 1.1.0.1; but breaks in 1.1.1; same result even whenI run it as 'system:admin'

[sudhaker@dell-16g-n5 ~]$ oc whoami
demo
[sudhaker@dell-16g-n5 ~]$ oc new-app https://github.com/sudhaker/my-node-app.git -l app=my-node-app
--> Found image 3ff2611 (7 days old) in image stream "nodejs in project openshift" under tag :0.10 for "nodejs"
    * The source repository appears to match: nodejs
    * A source build using source code from https://github.com/sudhaker/my-node-app.git will be created
      * The resulting image will be pushed to image stream "my-node-app:latest"
    * This image will be deployed in deployment config "my-node-app"
    * Port 8080/tcp will be load balanced by service "my-node-app"
--> Creating resources with label app=my-node-app ...
    ImageStream "my-node-app" created
    BuildConfig "my-node-app" created
    DeploymentConfig "my-node-app" created
    Service "my-node-app" created
--> Success
    Build scheduled for "my-node-app" - use the logs command to track its progress.
    Run 'oc status' to view your app.

---> Installing application source
---> Building your Node application from source
E0121 03:04:30.203154       1 util.go:91] npm info it worked if it ends with ok
E0121 03:04:30.320161       1 util.go:91] npm info using npm@1.4.28
E0121 03:04:30.320222       1 util.go:91] npm info using node@v0.10.40
E0121 03:04:30.709642       1 util.go:91] npm info preinstall my-node-app@0.0.1
E0121 03:04:30.721243       1 util.go:91] npm info build /opt/app-root/src
E0121 03:04:30.721871       1 util.go:91] npm info linkStuff my-node-app@0.0.1
E0121 03:04:30.723284       1 util.go:91] npm info install my-node-app@0.0.1
E0121 03:04:30.725980       1 util.go:91] npm info postinstall my-node-app@0.0.1
E0121 03:04:30.727763       1 util.go:91] npm info prepublish my-node-app@0.0.1
E0121 03:04:30.733290       1 util.go:91] npm info ok 
I0121 03:04:51.410650       1 sti.go:214] Using provided push secret for pushing 172.30.235.147:5000/demo/my-node-app:latest image
I0121 03:04:51.410691       1 sti.go:218] Pushing 172.30.235.147:5000/demo/my-node-app:latest image ...
I0121 03:04:51.701928       1 sti.go:223] Registry server Address: 
I0121 03:04:51.702019       1 sti.go:224] Registry server User Name: serviceaccount
I0121 03:04:51.702034       1 sti.go:225] Registry server Email: serviceaccount@example.org
I0121 03:04:51.702046       1 sti.go:230] Registry server Password: <<non-empty>>
F0121 03:04:51.702072 1 builder.go:185] Error: build error: Failed to push image. Response from registry is: Received unexpected HTTP status: 500 Internal Server Error

== 
[root@dell-16g-n5 openshift-origin-v1.1]# oc logs docker-registry-1-msfar

172.17.42.1 - - [21/Jan/2016:03:04:49 +0000] "GET /healthz HTTP/1.1" 200 0 "" "Go 1.1 package http"
time="2016-01-21T03:04:51.421707997Z" level=debug msg="authorizing request" go.version=go1.4.2 http.request.host="172.30.235.147:5000" http.request.id=48c6d8ad-a857-4e96-800f-7715c889492f http.request.method=GET http.request.remoteaddr="192.168.1.170:39309" http.request.uri="/v2/" http.request.useragent="docker/1.8.2-el7.centos go/go1.4.2 kernel/3.10.0-327.4.4.el7.x86_64 os/linux arch/amd64" instance.id=1cbb5e98-7e03-4b4a-8a36-a9c5c0bbf2d8
time="2016-01-21T03:04:51.421946377Z" level=error msg="error authorizing context: authorization header with basic token required" go.version=go1.4.2 http.request.host="172.30.235.147:5000" http.request.id=48c6d8ad-a857-4e96-800f-7715c889492f http.request.method=GET http.request.remoteaddr="192.168.1.170:39309" http.request.uri="/v2/" http.request.useragent="docker/1.8.2-el7.centos go/go1.4.2 kernel/3.10.0-327.4.4.el7.x86_64 os/linux arch/amd64" instance.id=1cbb5e98-7e03-4b4a-8a36-a9c5c0bbf2d8
192.168.1.170 - - [21/Jan/2016:03:04:51 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.8.2-el7.centos go/go1.4.2 kernel/3.10.0-327.4.4.el7.x86_64 os/linux arch/amd64"
time="2016-01-21T03:04:51.430174047Z" level=debug msg="authorizing request" go.version=go1.4.2 http.request.host="172.30.235.147:5000" http.request.id=eee3d504-1754-4e6a-a4c8-55459b5a0192 http.request.method=POST http.request.remoteaddr="192.168.1.170:39310" http.request.uri="/v2/demo/my-node-app/blobs/uploads/" http.request.useragent="docker/1.8.2-el7.centos go/go1.4.2 kernel/3.10.0-327.4.4.el7.x86_64 os/linux arch/amd64" instance.id=1cbb5e98-7e03-4b4a-8a36-a9c5c0bbf2d8 vars.name="demo/my-node-app"
time="2016-01-21T03:04:51.430552459Z" level=debug msg="Origin auth: checking for access to repository:demo/my-node-app:pull" go.version=go1.4.2 http.request.host="172.30.235.147:5000" http.request.id=eee3d504-1754-4e6a-a4c8-55459b5a0192 http.request.method=POST http.request.remoteaddr="192.168.1.170:39310" http.request.uri="/v2/demo/my-node-app/blobs/uploads/" http.request.useragent="docker/1.8.2-el7.centos go/go1.4.2 kernel/3.10.0-327.4.4.el7.x86_64 os/linux arch/amd64" instance.id=1cbb5e98-7e03-4b4a-8a36-a9c5c0bbf2d8 vars.name="demo/my-node-app"
time="2016-01-21T03:04:51.462290468Z" level=debug msg="Origin auth: checking for access to repository:demo/my-node-app:push" go.version=go1.4.2 http.request.host="172.30.235.147:5000" http.request.id=eee3d504-1754-4e6a-a4c8-55459b5a0192 http.request.method=POST http.request.remoteaddr="192.168.1.170:39310" http.request.uri="/v2/demo/my-node-app/blobs/uploads/" http.request.useragent="docker/1.8.2-el7.centos go/go1.4.2 kernel/3.10.0-327.4.4.el7.x86_64 os/linux arch/amd64" instance.id=1cbb5e98-7e03-4b4a-8a36-a9c5c0bbf2d8 vars.name="demo/my-node-app"
time="2016-01-21T03:04:51.700641213Z" level=debug msg="(*linkedBlobStore).Create" go.version=go1.4.2 http.request.host="172.30.235.147:5000" http.request.id=eee3d504-1754-4e6a-a4c8-55459b5a0192 http.request.method=POST http.request.remoteaddr="192.168.1.170:39310" http.request.uri="/v2/demo/my-node-app/blobs/uploads/" http.request.useragent="docker/1.8.2-el7.centos go/go1.4.2 kernel/3.10.0-327.4.4.el7.x86_64 os/linux arch/amd64" instance.id=1cbb5e98-7e03-4b4a-8a36-a9c5c0bbf2d8 vars.name="demo/my-node-app"
time="2016-01-21T03:04:51.700896825Z" level=debug msg="filesystem.PutContent(\"/docker/registry/v2/repositories/demo/my-node-app/_uploads/4be9afe4-c82a-4967-8a37-ea73e4bb694f/startedat\")" go.version=go1.4.2 http.request.host="172.30.235.147:5000" http.request.id=eee3d504-1754-4e6a-a4c8-55459b5a0192 http.request.method=POST http.request.remoteaddr="192.168.1.170:39310" http.request.uri="/v2/demo/my-node-app/blobs/uploads/" http.request.useragent="docker/1.8.2-el7.centos go/go1.4.2 kernel/3.10.0-327.4.4.el7.x86_64 os/linux arch/amd64" instance.id=1cbb5e98-7e03-4b4a-8a36-a9c5c0bbf2d8 trace.duration=91.67µs trace.file="/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=7381097e-4e86-4951-8392-ddd84edca265 trace.line=95 vars.name="demo/my-node-app"
time="2016-01-21T03:04:51.701123191Z" level=error msg="response completed with error" err.code=UNKNOWN err.detail="filesystem: mkdir /registry/docker: permission denied" err.message="unknown error" go.version=go1.4.2 http.request.host="172.30.235.147:5000" http.request.id=eee3d504-1754-4e6a-a4c8-55459b5a0192 http.request.method=POST http.request.remoteaddr="192.168.1.170:39310" http.request.uri="/v2/demo/my-node-app/blobs/uploads/" http.request.useragent="docker/1.8.2-el7.centos go/go1.4.2 kernel/3.10.0-327.4.4.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=274.520374ms http.response.status=500 http.response.written=156 instance.id=1cbb5e98-7e03-4b4a-8a36-a9c5c0bbf2d8 vars.name="demo/my-node-app"
192.168.1.170 - - [21/Jan/2016:03:04:51 +0000] "POST /v2/demo/my-node-app/blobs/uploads/ HTTP/1.1" 500 156 "" "docker/1.8.2-el7.centos go/go1.4.2 kernel/3.10.0-327.4.4.el7.x86_64 os/linux arch/amd64"
172.17.42.1 - - [21/Jan/2016:03:04:59 +0000] "GET /healthz HTTP/1.1" 200 0 "" "Go 1.1 package http"

**Comment by mfojtik** [comment]
The `filesystem: mkdir /registry/docker: permission denied" ` seems to be the cause here. @ncdc ?

**Comment by ncdc** [comment]
@sudhaker could you please provide the output from:

`ls -lZd /opt/openshift-registry`

**Comment by sudhaker** [comment]
SElinux is disabled (sorry Dan Walsh)

[root@dell-16g-n5 ~]# ls -lZd /opt/openshift-registry
drwxr-xr-x root root ?                                /opt/openshift-registry
[root@dell-16g-n5 ~]#

**Comment by sudhaker** [comment]
Same setup / same everything; but works in 1.1.0.1 & 1.1

**Comment by ncdc** [comment]
@sudhaker could you please gist/paste `oc get dc/docker-registry -o json`? Feel free to omit the certificate bits.

**Comment by ncdc** [comment]
In 1.1.1, the registry no longer runs as root. Your host dir is owned by root and non-root users can't write to it.

**Comment by ncdc** [comment]
@pweil- please assign as necessary

**Comment by sudhaker** [comment]
It makes sense; who should own the /opt/openshift-registry directory? My guess is user_id 1001 as I see in ps output. Please do the required update in documentation to reflect it.

[root@dell-16g-n5 openshift-origin-v1.1]# ps -fe | grep dockerregistry
1001      1405   946  0 10:30 ?        00:00:00 /dockerregistry /config.yml

My fix: chown -R 1001.1405 /opt/openshift-registry
