### ISSUE TITLE
Logs of a deployed pod not showing up in web console

### ISSUE THREAD

**Issue by myfear** [openshift/origin#6757]
Navigating to a deployment and switching over to the "Logs" tap does show a back box with a little text underneath:

"An error occurred loading the log. Reload"

oc get logs <pod> works.

Tested with "admin/admin" and the user having access to the logs via the oc command.

Anything I can attach here to make it easier to search for?

Thanks,
M

**Comment by deads2k** [comment]
@jwforres fyi

**Comment by jwforres** [comment]
@myfear what phase/status is the deployment in when you are trying to look at the logs?  Can you look in the network tab and see if it is failing to open the websocket connection?  Chrome's network tab deals with websockets better than firefox so i recommend debugging there.

**Comment by jwforres** [comment]
cc @spadgett

**Comment by myfear** [comment]
@jwforres status: deployed

Chrome console network log:

imagestreams (subscribe) Object {swarm-sample-discovery: Object}
builds (subscribe) Object {}
WebSocket connection to 'wss://localhost:8443/oapi/v1/namespaces/myfear/deploymentconfigs/swarm/log?…0485760&version=5&access_token=rY8UqUQo5fdoFYYK6Gklhrr2SW6gwKUcCSsZ5J9LAX4' failed: Error during WebSocket handshake: Unexpected response code: 204

**Comment by jwforres** [comment]
So this was a successful deployment, the pod for successful deployments is reaped very quickly, and then the logs are no longer available.  If you ran oc again right now, I expect you would not get any logs.

We know its a usability issue that can't be solved well until we have a passthrough API to the ELK stack.

cc @smarterclayton

**Comment by myfear** [comment]
Agree. I have to admit that I was actually looking for the running pod and not specifically the deployment pod. Even if I personally believe, that the usability issue here is huge.
Thanks for the clarification!

**Comment by jwforres** [comment]
That's really helpful feedback. @spadgett we probably need to do something better to guide users to the deployment's pods from the deployment page.  Also maybe when you go to the deployment log tab for the active deployment we should show an info box, something like "If you want to see the logs for the pods created by this deployment do xyz"

**Comment by spadgett** [comment]
Spoke with @jwforres. I'd like add a dropdown on the Logs tab so that you can see logs from any pod in the deployment in addition to the deployer pod. If we were getting the pod list, it would also help us show a better message when the deployer logs aren't available.

**Comment by smarterclayton** [comment]
I was looking at team city's layout today and I like some of what they do
on the logs page:

https://teamcity.mesosphere.io/viewLog.html?buildId=116812&buildTypeId=Oss_KubernetesMesos_5SmokeTestsDockerMesos&tab=buildResultsDiv

It has a solid feel to it

**Comment by spadgett** [comment]
The logs now show pod logs for an active deployment.

![deployment-logs](https://cloud.githubusercontent.com/assets/1167259/12990441/6bcd1ecc-d0d8-11e5-9665-ddac1afa2d12.png)

**Comment by jwforres** [comment]
So remaining issue is just that we don't link to the pods from the deployment today in case you wanted to get the logs from other pods in the deployment (since the API just takes the first one's logs).  So that will be the fix in https://github.com/openshift/origin/pull/7134

**Comment by spadgett** [comment]
I opened a separate issue for linking from deployment to pods. (It's not clear when #7134 will be merged.) Closing since the original deployment log issue is fixed.
