### ISSUE TITLE
Empty logs are not pruned on exit in Jenkins

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6761]
Empty logs like [this one](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/9072/artifact/origin/artifacts/test-end-to-end-docker/logs/sar_stderr.log) remain on Jenkins server after download.

**Comment by php-coder** [comment]
This link gives me 404, BTW.

**Comment by stevekuznetsov** [comment]
@php-coder Jenkins doesn't keep artifacts for too long.

**Comment by danmcp** [comment]
@stevekuznetsov What's the reasoning behind wanting to prune empty logs?

**Comment by stevekuznetsov** [comment]
@danmcp predates my involvement, @bparees  thoughts?

**Comment by bparees** [comment]
@stevekuznetsov i don't understand what you're saying.  they remain on the jenkins server after download from where/to where?

**Comment by stevekuznetsov** [comment]
[`delete_empty_logs`](https://github.com/openshift/origin/blob/master/hack/util.sh#L494-L498) is meant to remove empty logs from the local directories so that Jenkins can't download them. It's not quite working as expected. However, do you know what the impetus is for deleting these files in the first place?

**Comment by bparees** [comment]
@stevekuznetsov I think we were just trying to minimize the amount of junk to sift through when you're clicking through jenkins artifacts.

**Comment by stevekuznetsov** [comment]
We don't try to prune empty logs as their emptiness is valid info.
