### ISSUE TITLE
v2 gear to v3 pod conversion

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/origin#6769]
Hello,
In today's community meeting, I spoke with @smarterclayton about what, if anything, could be done in the form of tooling for ose/origin v2 gears that can then be converted to some form of usable template/pod in the v3 world. 

In my "napkin design" it seems like the process will follow something similar to:
1. take a gear backup.zip
2. break it down to discover components
3. If something is in the data dir create PVC (with default size, at some point allow for custom size to be requested)
4. If DB discovered create the appropriate template for the needed DB (inquire about persistence vs not, add another PVC with default sizing)
5. Separate out the code portion and allow user to plug in URL to their SC system (github, local gitlab, whatever) and push it out. Add to template with new source location
6. Go ahead and provision a project and create the services needed
7. attempt DB data import/tell user they have to import their DB data, here are some links on how to do that.

**Comment by smarterclayton** [comment]
There's another flow that could be described (in parallel, alongside?) which is the process to help validate your app works:

1. Given an app in the v2 API:
2. Identify cartridges and their current scaling status
3. Identify matching v3 images
4. Generate an app.json that reflects the structure as v3 deployment configs, including env var on the app, the source url, services, and legacy env vars
5. Try to create the new app.son against v3, verify that it starts
6. Run an export of the app and look at the data
7. Figure out which data is usefully persistent (ask questions of user?)
8. Setup and add PVCs, then use oc rsync to copy the exported data into the right directories (hard?)
9. Check app for health

Getting the data in and out of the pvc seems unnecessarily hard right now - if we had init containers this might be easier, if we had a "create PVC using this tar of data" that might also be useful.

**Comment by ebalsumgo** [comment]
I would say that using APIs would be the best way, my more manual description above was/is due to my lack of complete familiarity with using the APIs to accomplish some of these. Your way seems way smarter ;)

:+1:

**Comment by smarterclayton** [comment]
I don't think export in v2 grabs the json today - it would potentially be nice if it did, but that makes it harder.

**Comment by bparees** [comment]
we've got a v2 migration guide now: https://docs.openshift.org/latest/dev_guide/migrating_applications/index.html

@smarterclayton @danmcp is this automated tooling for migration still something we're interested in investing in?
