### ISSUE TITLE
Default vagrant boxes are still Fedora 21 (now unsupported)

### ISSUE THREAD

**Issue by marun** [openshift/origin#6771]
Kube has already updated to Fedora 23: https://github.com/kubernetes/kubernetes/pull/15998  Maybe origin can reuse those boxes instead of continuing to rely on origin-specific ones?

**Comment by mfojtik** [comment]
@danmcp @sdodson is there something that is preventing us from updating to f23?

**Comment by danmcp** [comment]
@mfojtik https://ci.openshift.redhat.com/jenkins/job/devenv_ami/3209/console

**Comment by danmcp** [comment]
@marun @mfojtik To be clear, the aws instances are updated already.  We can update the vagrant instances and they will be in a similar broken state.  I don't mind doing so if everyone is ok with that state.  The thought was the latest rebase should (or might) fix the error seen above with Kube.

**Comment by marun** [comment]
@danmcp I'll re-run the e2e tests against kube on F23 to be sure that these errors don't exhibit, but waiting for the rebase sounds like a good plan regardless.  Better to avoid debugging something that might already be fixed upstream.

**Comment by danmcp** [comment]
New fedora 23 images have been published.
