### ISSUE TITLE
Can no longer pull from private git repository

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin#6773]
I just upgraded to v1.1.1 and I am no longer able to access my private git repositories:

 builder.go:185] Error: build error: timeout while waiting for remote repository "https://username:password@enterprisewebservice.kilnhg.com/Code/EnterpriseWebService/Openshift-Docker-Builds/wildfly-jdk-8.git

**Comment by deanpeterson** [comment]
I rebooted my system and installed some updates and the issue seems to have cleared.

**Comment by msirovy** [comment]
Hi I updated my cluster yesterday and since that time I have same problem, I tried reboot all nodes, set ---dns=8.8.8.8 in docker but it's still don't work... I need fast fix, users in our company need it

**Comment by msirovy** [comment]
update:
I found mistake in nasible hosts file, it set ip 10.3.2.1 as masterIP: so the svc/kubernetes route 53 port to bad ip
