### ISSUE TITLE
where to get the prebuilt binary for the latest release ?

### ISSUE THREAD

**Issue by thincal** [openshift/origin#6776]
such as: https://github.com/openshift/origin/releases/download/v1.0.8/openshift-origin-v1.0.8-6a2b026-linux-amd64.tar.gz, how about the v1.1.1 ? how to know ? thanks.

**Comment by mfojtik** [comment]
@thincal you can find the latest release binaries here: https://github.com/openshift/origin/releases

**Comment by thincal** [comment]
yes, that is right. thanks.

**Comment by Jaware** [comment]
the tar.gz  does not contain the openshift binary,only the apiserver and kubectl
