### ISSUE TITLE
Merge fix for leaky kube-proxy sockets

### ISSUE THREAD

**Issue by tcastberg** [openshift/origin#6780]
We're seeing an issue that apparently has been fixed in kubernetes but does not appear to have landed in origin yet. It's causing massive issues for us and is preventing a project from going live.

We're seeing the problem described in these issues: https://github.com/kubernetes/kubernetes/issues/18354
https://github.com/kubernetes/kubernetes/issues/17641

These issues seem to have been fixed by this pull request:
https://github.com/kubernetes/kubernetes/pull/18524/commits

It does however not seem to have been merged into origin yet. Any chance we missed this or that it has an eta?

**Comment by liggitt** [comment]
Looks like that PR missed the rebase that is in progress, it'll get picked up in the one after that

**Comment by pweil-** [comment]
@deads2k - sending your way since you're doing the next rebase

**Comment by liggitt** [comment]
Fixed in https://github.com/openshift/origin/pull/6947/
