### ISSUE TITLE
Build gets stuck in pending when pushSecret used but no actual secret defined.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#6781]
Had created a build as follows:

1 - Create a JSON description of a new build. Something like:

```
    oc new-build https://github.com/GrahamDumpleton/mod_wsgi-docker.git --context-dir 2.7 --name mod-wsgi-docker --to-docker --dry-run -o json
```

 2 - Edit the generated JSON and change image output spec to:

```
        "output": {
            "to": {
                "kind": "DockerImage",
                "name": "index.docker.io/grahamdumpleton/mod-wsgi-docker-tests:latest"
            },
            "pushSecret": {
                "name": "xdockerhub"
            }
        },
```

That is, add a pushSecret.

Note that I have NOT created the actual secret.

3 - Load the JSON to create the build and trigger a build.

What will happen is that the build will stay in pending and not error.

The event stream will show errors about the secret not being found.

```
10m         9s         65        mod-wsgi-docker-14-build   Pod                                           FailedMount   {kubelet ip-172-18-1-76.us-west-1.compute.internal}   Unable to mount volumes for pod "mod-wsgi-docker-14-build_image-builds": secrets "xdockerhub" not found
10m         9s         65        mod-wsgi-docker-14-build   Pod                                           FailedSync    {kubelet ip-172-18-1-76.us-west-1.compute.internal}   Error syncing pod, skipping: secrets "xdockerhub" not found
```

but that does not actually cause the build to fail.

**Comment by GrahamDumpleton** [comment]
Should also add this could well be by design. If you create secret after the fact, the build will then continue. Or at least that is what appeared to happen.

Came across this as I somehow managed to delete the secret by accident although still listed against the service account for the builder. When added back the secret, it then started running.

**Comment by mfojtik** [comment]
@GrahamDumpleton this is indeed by design. The fact that the Secret does not exists does not mean a Build that reference it should not be created, because the Secret can be created afterwards.

What we should fix here is the message you get back in UI or in CLI telling you what we are waiting for. What does the `oc describe build` say? Does it mention it is waiting for pushSecret?

**Comment by GrahamDumpleton** [comment]
Sorry, forgot to go back and added the requested information.

```
$ oc describe build mod-wsgi-docker-1
Name:		mod-wsgi-docker-1
Created:	27 seconds ago
Labels:		build=mod-wsgi-docker,buildconfig=mod-wsgi-docker,openshift.io/build-config.name=mod-wsgi-docker
Annotations:	openshift.io/build.number=1
Build Config:	mod-wsgi-docker
Duration:	waiting for 27s
Build Pod:	mod-wsgi-docker-1-build
Strategy:	Docker
Source Type:	Git
URL:		https://github.com/GrahamDumpleton/mod_wsgi-docker.git
ContextDir:	2.7
From Image:	DockerImage library/debian@sha256:7f82488af7fe57134b058b925928b9ce3b96384229a566d5236bd09ec2f82ef5
Output to:	DockerImage index.docker.io/grahamdumpleton/mod-wsgi-docker-tests:latest
Push Secret:	xdockerhub
Status:		Pending
Events:
  FirstSeen	LastSeen	Count	From							SubobjectPath	Reason		Message
  ─────────	────────	─────	────							─────────────	──────		───────
  26s		26s		1	{scheduler }								Scheduled	Successfully assigned mod-wsgi-docker-1-build to ip-172-18-1-77.us-west-1.compute.internal
  26s		5s		4	{kubelet ip-172-18-1-77.us-west-1.compute.internal}			FailedMount	Unable to mount volumes for pod "mod-wsgi-docker-1-build_secrets": secrets "xdockerhub" not found
  26s		5s		4	{kubelet ip-172-18-1-77.us-west-1.compute.internal}			FailedSync	Error syncing pod, skipping: secrets "xdockerhub" not found
```

**Comment by mfojtik** [comment]
@GrahamDumpleton the event is there but I agree we should communicate this error in the UI. @jwforres @jhadvig ?

**Comment by jwforres** [comment]
@smarterclayton and I were discussing last week whether certain events should be pushed back to the objects as status conditions, the fact that this build is stuck in pending indefinitely because no secret exists seems like something I would expect to bubble up as a condition

**Comment by mfojtik** [comment]
@jwforres @smarterclayton with "condition" you mean the "Reason" field on Build? (iow. we set the reason to "PendingPullSecret" or something when the build needs secrets).

**Comment by smarterclayton** [comment]
Yes, Reason on build should be set.  And technically that reason should be
a condition, and evolve towards conditions.
