### ISSUE TITLE
ambiguous oc status deployment time

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#6782]
```
[vagrant@localhost sample-app]$ oc status
In project test on server https://localhost:8443

svc/database - 172.30.181.124:5434 -> 3306
  dc/database deploys docker.io/openshift/mysql-55-centos7:latest 
    #1 deployment running for 5 minutes - 1 pod

...

[vagrant@localhost sample-app]$ oc status
In project test on server https://localhost:8443

svc/database - 172.30.181.124:5434 -> 3306
  dc/database deploys docker.io/openshift/mysql-55-centos7:latest 
    #1 deployed 5 minutes ago - 1 pod

...
```

The deployment process has been running for 5 minutes and when it finishes, oc status reports that the database was deployed 5 minutes ago. Shouldn't we report the time the database was made available (now) instead of the time the deployment started (5 min ago)? @deads2k @ironcladlou

**Comment by ironcladlou** [comment]
Time deployment completed seems to make more sense to me...

**Comment by kargakis** [comment]
This is actually a bigger problem that has to do with any timestamps we show when describing deployments (oc status, oc deploy, etc). The deployment describers are always using the creation timestamp of the deployment alongside completion/failure info which is misleading. How about the deployer controller start annotating deployments everytime they reach a terminal phase (failed, complete)? We could use the same annotation for both eg `openshift.io/terminated-at` with a timestamp value. These would need to be cleaned up in case we retry the same deployment. @smarterclayton @ironcladlou thoughts?

**Comment by kargakis** [comment]
Or we could simply use a more generic annotation that would be recorded each time a deployment transitions to another phase. I think this would be ideal.

**Comment by kargakis** [comment]
Or we could use Conditions which are desired upstream too. I feel we need to finish https://github.com/kubernetes/kubernetes/pull/19343 first.

**Comment by kargakis** [comment]
Actually conditions on the dc wouldn't be enough:/ We would need conditions on the rc/rs

**Comment by smarterclayton** [comment]
Let's fix this in 19343 and understand what the outcome is, and also
suggest the recording of this in the upstream issue.

**Comment by kargakis** [comment]
Upstream, they don't actually have this issue since the deployment process starts as soon as the replica set is created whereas for deployment configs the deployment process starts as soon as the deployer pod is transitioned to Running. We could surface the deployer pod creation as a deployment condition but ultimately we need the info to exist as part of the replication controller.

**Comment by kargakis** [comment]
Now that we have RC conditions (coming with the next rebase) we could have this be a condition in the RC.

**Comment by mfojtik** [comment]
@kargakis we should also translate the conditions to human readable format in oc status

**Comment by kargakis** [comment]
@mfojtik this is the other issue where we need to know when a deployer pod started/finished for a deployment.
