### ISSUE TITLE
Storage Configs and Documentation

### ISSUE THREAD

**Issue by donnydavis** [openshift/origin#6785]
This may not be an actual issue with origin, however I followed the docker-storage-setup guidelines and each node has 80GB for /var

The issue comes with origin placing hundreds of core.$(random#) and filling up all the disk space. 
It does not seem to use the docker pool at all. This leads to errors like this

docker-registry-1-deploy   0/1       OutOfDisk   0          3s

**Comment by jwhonce** [comment]
@donnydavis What Host OS are you running? And where are the core files being written?

**Comment by donnydavis** [comment]
Centos 7.2
They are written to the /var/lib/docker dir

**Comment by donnydavis** [comment]
This issue can be closed. It was a garage cleanup related issue from an old release.
