### ISSUE TITLE
Enable secret update to manage secret lifecycle

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#6786]
When I deploy an application that has a secret (a configuration file, for example), I want to be able to update the secret payload. I would like to be instructed how to deploy that update as well. Example workflow:
1. create secret
   
   ```
   $ oc secret new mysecret config.yaml=/path/to/my/config.yaml
   ```
2. deploy application that mounts secret
3. update secret contents
   
   ```
   $ vi /path/to/my/config.yaml
   ```
4. update secret object
   
   ```
   $ oc secret update mysecret config.yaml=/path/to/my/config.yaml
   secret "mysecret" updated.
   To deploy the update, run "oc deploy <deploy_config> --latest" on any deployment config that references this secret.
   ```
5. User re-deploys per instruction
   
   ```
   oc deploy <deploy_config> --latest
   ```

**Comment by brianwcook** [comment]
This is really a pain. Currently if you need to update a secret, you have to delete and then recreate it.  This breaks the linkage of the secret to service accounts, breaks volume identifiers referencing the secret and generally wreaks havok on deployment configs.

**Comment by liggitt** [comment]
You should not have to delete/recreate a secret to update it. @pmorie, can you confirm?

**Comment by lbilger** [comment]
I found this ticket while searching for a way to update a secret without deleting and re-creating it (because I didn't want to lose the labels defined for the secret). If anyone is having the same problem, this workaround might help:
```oc patch secret mysecret -p '{"data": {"config.yaml": "'$(base64 /path/to/my/config.yaml)'"}}'```

Of course, having an ```oc secret update``` command would feel much cleaner because the user wouldn't have to know about the internal structure of the secret.

**Comment by aweiteka** [comment]
> Of course, having an oc secret update command would feel much cleaner because the user wouldn't have to know about the internal structure of the secret.

@lbilger thanks for validating the use case.

I confirmed there is no workaround outside of patch. For example, `oc secret new ...` does not allow one to overwrite an existing secret.

Options remain:
1. implement new verb `oc secret update ...` per this issue
1. implement "overwrite" flag `oc secret new* --overwrite ...` to allow overwriting a secret

@pmorie who should this issue be assigned to?

**Comment by ceagan** [comment]
I used the patch option suggested by @lbilger to get past this issue, but on my system, the base64 command automatically wraps lines, which resulted in the command giving the unhelpful message:

> error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'oc get resource/<resource_name>' instead of 'oc get resource resource/<resource_name>'

I was able to get past the issue by modifying the patch command given by adding `-w 0` to disable line wrapping as follows:

```
 oc patch secret mysecret -p '{"data": {"config.yaml": "'$(base64 -w 0 /path/to/my/config.yaml)'"}}'
```

**Comment by ThiefMaster** [comment]
How is this closed? The lack of a sane way to update secrets without going through the webinterface and manually base64 encoding it or messing with JSON/YAML on the CLI seems like a major annoyance / missing feature.

/reopen
