### ISSUE TITLE
Generate registry config.yml.sample during openshift start --write-config

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#6790]
As an admin I want to deploy a registry with a customized [configuration file](https://github.com/docker/distribution/blob/master/docs/configuration.md). It's important to ensure I'm starting with the correct initial file. I want to be able to generate a valid `config.yml.sample` file as a starting point, then put that file under version control and deploy via  the [secret config procedure](https://github.com/openshift/openshift-docs/pull/1468).

**Comment by smarterclayton** [comment]
Closing due to age.  Re-open if this is important enough.
