### ISSUE TITLE
Secret 'content' should not be viewable/retreiveable by openshift admins

### ISSUE THREAD

**Issue by ivanthelad** [openshift/origin#6793]
It should not be possible for a cluster admin to view the coded/decoded content of a project's secrets. for example openshift admin should not be able to decode a project's application database password. 

Another example where this is problematic is when a developer has configured their STI process to authenticate against git using their personal git credentials (often corporate login credentials ), a openshift admin can easily retrieve a user login details by decoding the base64 secret content

**Comment by liggitt** [comment]
There is a chicken and egg problem with this. In order for containers to *use* the secret data, one of the following has to happen:

1. the data is decrypted by the infrastructure before being injected into the container, in which case admins would have access to the decrypting keys
2. the data is injected into the container encrypted, and the container decrypts it, which can only happen if:
  1. the container has decrypting keys built in, which means admins can read them
  2. the container retrieves decrypting keys from somewhere, using some credentials built in to the container, which the admins could also read, use to retrieve, and decrypt

**Comment by liggitt** [comment]
Secrets just contain binary data... if you want to inject encrypted secrets and have your containers decode the data using one of the latter methods, you can already do that, but the system can't really help you with decrypting your data, while simultaneously ensuring that admins who are in control of the system can't decrypt your data

**Comment by smarterclayton** [comment]
We generally recommend not creating full openshift admin accounts - you can for instance create a cluster role that cannot retrieve secrets globally, and use that for most administrative actions.

**Comment by liggitt** [comment]
Closing this issue in favor of upstream issues about alternate secret storage mechanisms (https://github.com/kubernetes/kubernetes/issues/10439), and/or encrypting secrets at rest (https://github.com/kubernetes/kubernetes/issues/12742), but I still don't think those solve the issue of getting secret data into a container without any way of a cluster admin gaining access to it, either directly or transitively.
