### ISSUE TITLE
Reorganize build order on Jenkins to fail faster

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6799]
The ci flow takes about 67 minutes and does not actually run any tests until 42 minutes in.  We should probably run verify, then test-cmd in parallel with unit tests (to provide maximum CPU use and catch flakes in test-cmd), then do everything else.  Test integration could conceivably be done after, but it depends on the router image being built, and it's likely we want to add additional image based testing.

This should be a makefile step that is called by Jenkins

**Comment by smarterclayton** [comment]
I'd like tests to fail in 15 minutes or less.

**Comment by smarterclayton** [comment]
Alternatively we can split release, e2e, and integration into one ci job, and the others after that.

**Comment by smarterclayton** [comment]
Going to split the jenkins execution into multiple steps to avoid having to rewrite stuff.

**Comment by deads2k** [comment]
I've tried running things in parallel before.  The gain wasn't very significant, especially when compared against the effort to do it and the difficulty in chasing flakes.

I'd like to try to run two ec2 instances for tests.  One for building the images, e2e, and the few integration tests that require images.  Then another instance for unit tests, test-cmd, and test-integration.  That splits the overall job about in half in terms of time.

**Comment by smarterclayton** [comment]
This is the setup to enable that - we run certain tests first, and the job
is now structured to allow that cleanly.  The parallel has the benefit of
increasing the potential of flakes being flushed out in test-cmd so I
actually want to enable it if for no other reason than that.

**Comment by smarterclayton** [comment]
Complete with https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/9500/ - unit test, verify, or integration test failure should happen in <15 minutes from the time make is invoked (need to get other timings).
