### ISSUE TITLE
Some unit tests are very slow

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6801]
```
ok      github.com/openshift/origin/pkg/api 21.340s coverage: 77.9% of statements
ok      github.com/openshift/origin/pkg/build/builder   6.770s  coverage: 44.6% of statements
ok      github.com/openshift/origin/pkg/cmd/server/crypto   19.404s coverage: 10.3% of statements
ok      github.com/openshift/origin/pkg/cmd/server/admin    9.591s  coverage: 31.1% of statements
ok      github.com/openshift/origin/pkg/deploy/prune    11.039s coverage: 91.5% of statements
ok      github.com/openshift/origin/pkg/deploy/reaper   15.137s coverage: 72.2% of statements
ok      github.com/openshift/origin/pkg/generate/app/cmd    39.368s coverage: 62.4% of statements
ok      github.com/openshift/origin/plugins/router/f5   6.206s  coverage: 72.9% of statements
```

Are the worst offenders.  `pkg/api` gets a pass because it's fuzz testing roundtripping, the others are probably not stubbing enough logic (generate for instance is going out to github and dockerhub) and should either be stubbed or moved to integration tests.

The others may be waiting or sleeping.

@kargakis @derekwaynecarr @ironcladlou @deads2k @ramr @Miciah @csrwng as people who have touched those tests

**Comment by kargakis** [comment]
related: https://github.com/openshift/origin/issues/6176

**Comment by mfojtik** [comment]
`github.com/openshift/origin/pkg/generate/app/cmd    39.368s`

This is ~95s when I run this locally, which timeouts the unit tests. We already talked about this with @deads2k.

**Comment by deads2k** [comment]
It gets worth with race detection on (not sure if you have that on locally).  I was going to write a "special" list that got run with a longer default timeout to keep the queue happy.

@mfojtik and I had talked about moving the new-app stuff into test-integration to allow longer timeouts, but still make sure that our example repos still worked for each merge.

**Comment by kargakis** [comment]
new-app tests panic from time to time

http://pastebin.com/kBL9Btq6

**Comment by smarterclayton** [comment]
App/cmd does need to be split into two parts.

**Comment by deads2k** [comment]
@kargakis we have a rule for this: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/failure-cause-management/56a667f3e4b089752bb4314f/, but it could use some work to gather the package that timeed out and the description should point to this issue.

**Comment by kargakis** [comment]
> @kargakis we have a rule for this: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/failure-cause-management/56a667f3e4b089752bb4314f/, but it could use some work to gather the package that timeed out and the description should point to this issue.

updated with the panic log, name of the offending test, and the link to this issue

**Comment by smarterclayton** [comment]
Moved new-app slow tests to integration

**Comment by liggitt** [comment]
marking as flake because the slow ones sometimes timeout

**Comment by kargakis** [comment]
@stevekuznetsov passing to you if you have any time to look at it

**Comment by stevekuznetsov** [comment]
@smarterclayton it seems like running them in parallel with test-cmd has potentially led to some timeout-based tests being intentionally lengthened to work with the slowness with which we run them on Jenkins... unclear if your list above includes these or not

**Comment by smarterclayton** [comment]
If a unit test can't deal with 20-30 second pauses, it's going to flake
against either test-cmd or itself, just based on our experience.  It just
makes them more likely and thus easier to spot and fix.
