### ISSUE TITLE
[jenkins-plugin] where to get the access token for the openshift REST API ?

### ISSUE THREAD

**Issue by thincal** [openshift/origin#6807]
`GET /oapi/v1/buildconfigs` will report the error bellow:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot list all buildconfigs in the cluster",
  "reason": "Forbidden",
  "details": {
    "kind": "buildconfigs"
  },
  "code": 403
}
```
so that what's the way to get the access token and how to specify it in the openshift REST API ? thanks.

**Comment by deads2k** [comment]
`oc login` will get an access token an write it into your `~/.kube/config` file.  You can view it using `oc whoami -t`.

If you want to try to make the proper calls yourself, you can run `oc login --loglevel=8` to see all the traffic.  Basically, we just hit our oauth server.

**Comment by thincal** [comment]
actually my question is about the [jenkins-plugin] (https://github.com/openshift/jenkins-plugin), where it needs the auth token to interacting with OpenShift, I try to use the token got from `oc whoami -t`, it still report the Forbidden error as above, also the token from `oc whoami -t` would be expired at a short time.

**Comment by deads2k** [comment]
For long lived tokens, we'd suggest creating a service account and using a service account token to perform your actions.

`oc get sa/builder --template='{{range .secrets}}{{ .name }} {{end}}' | xargs -n 1 oc get secret --template='{{ if .data.token }}{{ .data.token }}{{end}}' | head -n 1 | base64 -d -` is a hint, but you may have to tweak it.

**Comment by thincal** [comment]
that can get the service account token successfully, but the `curl --header "Authorization: Bearer xxx" https://master1.example.com:8443/oapi/v1/builds` reports error:
```
Unauthorized
```

**Comment by deads2k** [comment]
You have to grant the service account powers just like you would grant them to a regular user.  Also, in case it wasn't clear, I would suggest creating a custom service account for this so that you can avoid having infrastructure components with power.

**Comment by thincal** [comment]
which kind of power needs to be granted ?

**Comment by liggitt** [comment]
What do you need Jenkins to be able to do? Is there an example job you are using? That would help knowing what role would be appropriate to grant to the Jenkins service account

**Comment by thincal** [comment]
From [jenkins-plugin](https://github.com/openshift/jenkins-plugin), it will run bellow `oc` commands:
```
oc start-build
oc scale
oc deploy
oc tag
oc create
```

**Comment by liggitt** [comment]
the simplest default role that would allow those is the "edit" role, so `oc policy add-role-to-user edit --serviceaccount=<your_service_account_name> -n <your namespace>`

**Comment by thincal** [comment]
I have already followed bellow steps, but still get the `Unauthorized` failure.

- create the sa
```
$ echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"jenkins"}}' \
    | oc create -n mytest -f -
```
- grant the edit role
```
$ oc policy add-role-to-user edit --serviceaccount=jenkins -n mytest
```
- get the token
```
$ oc get sa/jenkins --template='{{range .secrets}}{{ .name }} {{end}}' | xargs -n 1 oc get secret --template='{{ if .data.token }}{{ .data.token }}{{end}}' | head -n 1 | base64 -d -
```
- curl with REST API
```
$ curl --header "Authorization: Bearer xxx" https://master1.ceyes.os:8443/oapi/v1/builds
$ Unauthorized
```
Is there something wrong ?

**Comment by csrwng** [comment]
> $ curl --header "Authorization: Bearer xxx" https://master1.example.com:8443/oapi/v1/builds

You need to specify the namespace that you granted your service account acccess to:

```
 curl --header "Authorization: Bearer xxx" https://master1.example.com:8443/oapi/v1/namespaces/mytest/builds
```

**Comment by thincal** [comment]
thanks, but bellow will report same error also:
```curl --header "Authorization: Bearer xxx" https://master1.example.com:8443/oapi/v1```

**Comment by deads2k** [comment]
@thincal I suspect a problem with the actual token, likely caused by bash insanity not returning what I expect.  Let me explain the logic of those commands so you can manually retrieve your token.

 1. Get the names of all the mountable secrets assigned to a service account.
 1. Find the one that is the token secret. It's usually the first one, but it will have "token" in the name.
 1. Get that secret and pull the "token" key out of the "data" map.
 1. That key will be base64 encoded, so decode it.

**Comment by thincal** [comment]
@deads2k now the `https://master1.example.com:8443/oapi/v1` could return the results successfully now, but will be failed to get some kind of resources, such as: `users`, `buildconfigs/webhooks`, `deploymentconfigs`, `templates` etc., but ok with `projects`.

The example error as bellow:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:serviceaccount:mytest:jenkins\" cannot list all templates in the cluster",
  "reason": "Forbidden",
  "details": {
    "kind": "templates"
  },
  "code": 403
}
```

Also, if using this token in the openshift-jenkins plugin, it will report bellow error:
```
BUILD STEP:  OpenShiftScaler in perform for nodejs-ex wanting to get to replica count 0 on namespace mytest

OpenShiftScaler wait 180000
Auth - allowCertificate with incoming chain of len  2
Auth - allowCertificate returning true
Auth - allowCertificate with incoming chain of len  2
Auth - allowCertificate returning true
ERROR: Build step failed with exception
com.openshift.restclient.authorization.UnauthorizedException: Unauthorized to access resource. You can access the server using Basic authentication.
```
I think this service account don't have the access right with some resources, but I have already grant the admin role to this sa as bellow:
```
oc policy add-role-to-user admin --serviceaccount=jenkins -n mytest
```

so, what's your thought about it? thanks.

**Comment by deads2k** [comment]
The `admin` role is an admin with project level access, so it can't see `users`.  Its not intended to be used to access cluster-scoped resources.  `add-role-to-user` is about granting powers to a user in a project, `add-cluster-role-to-user` is about adding powers to a user across the entire cluster.

See https://docs.openshift.org/latest/admin_guide/manage_authorization_policy.html and https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html

**Comment by deads2k** [comment]
@stevekuznetsov a command to get a service account token would have helped here.

**Comment by deads2k** [comment]
> /cc @gabemontero you may have some insight here

@stevekuznetsov I explained the flow here: https://github.com/openshift/origin/issues/6807#issuecomment-175659174 . You could attach the command as `oc secrets sa-token <sa name>` to start with and you can move it during the review.

**Comment by gabemontero** [comment]
Yep, no additional insight from me based on the specific discussion flow from above. 

I am curious (in case we need to update the jenkins image/plugin/example docs with more cross-referencing, links, etc. to some of the auth related doc references noted above) - @thincal - did you look at the [V3 OpenShift Jenkins example](https://github.com/openshift/origin/blob/master/examples/jenkins/README.md) at all, and not what is described in the optional step 3 ?

**Comment by YannMoisan** [comment]
I've written a function to retrieve the token :
```
function ogt() { oc get secrets $(oc get sa/$1 -o json | jq -r ".secrets[].name" | grep token) -o json | jq -r ".data.token" | base64 -D - }
```

You can test the token returned with `oc login --token=`

And to avoid copy/paste issue, you can use on OSX `ogt jenkins | pbcopy` to put the token in the clipboard, so you just have to paste it in the jenkins interface.

But it could be useful to have an `oc token SA` command performing such a thing.

**Comment by liggitt** [comment]
FYI, work is in progress in https://github.com/openshift/origin/pull/6941 to create and get a service account token

**Comment by thincal** [comment]
@gabemontero yes after following the [step 3 in V3 OpenShift Jenkins example ](https://github.com/openshift/origin/blob/master/examples/jenkins/README.md), it works now. But should leave the token filed in Job as empty if using the string parameter.

Thanks again.

**Comment by gabemontero** [comment]
glad it worked out @thincal
