### ISSUE TITLE
remove /volumes from artifacts

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6814]
It's doubling the size of artifacts.zip and of dubious value.  

@stevekuznetsov see about removing it.

**Comment by stevekuznetsov** [comment]
found earliest introduction of `$VOLUME_DIR` here: https://github.com/openshift/origin/commit/dda38079b437c5100b8bb660e847e83c7e44cb41#commitcomment-15655692
If we aren't gaining anything from it, let's remove it

**Comment by deads2k** [comment]
> found earliest introduction of $VOLUME_DIR here: dda3807#commitcomment-15655692
> If we aren't gaining anything from it, let's remove it

The volumes are used as the point to make volumes for pods.  We have to have it and its in the correct location, I just want to exclude them from the downloaded artifacts.
