### ISSUE TITLE
cgroup values not set correctly on pods

### ISSUE THREAD

**Issue by bparees** [openshift/origin#6822]
I'm setting a quota on a pod and all the values are set correctly except the cpu quota.  I can tell this because i'm looking at the cgroup filesystem and using the values i read there to pass to a docker build operation and the docker build operation reveals what was read from the filesystem is not correct:

```
Step 5 : RUN echo -n QUOTA= && cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us
 ---> Running in 68e593b55faa
QUOTA=-1
```

running the exact same build a second time shows the value correctly:

```
Step 5 : RUN echo -n QUOTA= && cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us
 ---> Running in 40f3723a28ed
QUOTA=6000
```

all other cgroup values i'm setting are being picked up correctly (memory limit, cpu period, cpu shares).

it seems to consistently be the first build/pod launch that gets a "-1" value for cpu quota.

**Comment by bparees** [comment]
@derekwaynecarr fyi.  what we were looking at on thursday(?).

**Comment by bparees** [comment]
(in case it's not clear, what i am doing is running a pod with a quota, and within that pod we look at the cgroup files and use the values seen there to populate arguments to docker build.  So if things were working correctly, the container created by docker build should have the same cgroup limits as the pod).

**Comment by bparees** [comment]
(which means the pod doesn't have the right cgroup limits)

**Comment by mrunalp** [comment]
What version of docker is in use?

**Comment by bparees** [comment]
Docker version 1.9.1-fc23, build 110aed2-dirty


On Mon, Jan 25, 2016 at 1:22 PM, Mrunal Patel <notifications@github.com>
wrote:

> What version of docker is in use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/6822#issuecomment-174609888>.
>



-- 
Ben Parees | OpenShift

**Comment by derekwaynecarr** [comment]
@mrunalp - is it possible for cgroup values to get updated after the
container launched?  Do we guarantee that the scope has all its values
assigned before launching the container?

@bparees - in both scenarios, does the ouput of docker inspect differ?

**Comment by bparees** [comment]
@derekwaynecarr i haven't been in a position to grab all the data i'd like just yet.

**Comment by mrunalp** [comment]
The values should be set before the container process is executed.

**Comment by bparees** [comment]
The other error I sometimes see when trying to read the cgroups files from within the pod:
```
F0126 16:21:41.107495       1 builder.go:193] Error: build error: [8] System error: open /sys/fs/cgroup/memory/system.slice/docker-3fc663525fcb874a72dfdf3d467b1b722956a42ca2980c1c2f2dcda9164a6803.scope/memory.memsw.limit_in_bytes: no such file or directory
```

not sure if it's related or not.

**Comment by bparees** [comment]
@derekwaynecarr @mrunalp here's a gist of a docker inspect for a container that reported "-1" for the cpu quota in the cgroup filesystem:

https://gist.github.com/bparees/fcdca4908a623f1b8644

as you can see, the container itself reports the expected value of:
"CpuQuota": 6000,

but it appears not to have been translated into `/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us` correctly.

**Comment by bparees** [comment]
I also continue to get this error for any docker build I run where i set cgroup limits:
F0127 15:56:04.450206       1 builder.go:193] Error: build error: [8] System error: write /sys/fs/cgroup/memory/system.slice/docker-602214e32d18e30500cb7c5a2b0c1d388a6dac63a9a0ad75ad5af4cb11de7219.scope/memory.memsw.limit_in_bytes: invalid argument

**Comment by bparees** [comment]
I should note those two errors actually seem related.  When the quota value is wrong(-1) is when i seem to get that error.

**Comment by derekwaynecarr** [comment]
@bparees - so that confirms that the problem is not kubelet since docker has the right data.

CPU shares and Memory Limit are being assigned to the scope via systemd

https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L217
https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L212

CPU quota and period are not set via systemd
https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L243

but that TODO seems dated unless there is an old version of systemd that is being targeted.

**Comment by derekwaynecarr** [comment]
see `CPUQuota`: http://www.freedesktop.org/software/systemd/man/systemd.resource-control.html

@mrunalp - do we set `Delegate` on the unit we generate?

**Comment by mrunalp** [comment]
@derekwaynecarr This shouldn't be necessary. I suspect that when the failure occurs the process doesn't join the right cgroups. So, if possible, could you capture the /proc/pid/cgroup output from the container? 

There is one fix which could potentially apply here but would like to root cause using the cgroup output.

**Comment by mrunalp** [comment]
Also, the code that you pointed to in the previous comment is much newer than what we have in our 1.9 which is on the projectatomic/docker repo.

**Comment by bparees** [comment]
From what i can tell the error writing is coming from the "docker build" api invocation we perform....unfortunately i can't reproduce it by performing a manual "docker build --memory=100000000 --memory-swap=100000000 --cpu-quota=6000 --cpu-shares=61 --cpu-period=100000 ."

not sure what would be different between us using the go-dockerclient to kick off a docker build w/ those args, and manually running a docker build.

**Comment by derekwaynecarr** [comment]
@mrunalp - good to know, thanks!

**Comment by bparees** [comment]
@mrunalp i'm not likely to have an opportunity to gather that data.  Have you attempted to reproduce this on your own?  From what I can tell, pods launched with quota occasionally have no quota (i've only seen it on build pods because that's all i run, i haven't tried to reproduce it for a non-build pod).

build-pods are explicitly short lived, so i'm not likely to be able to get cgroup information.

**Comment by bparees** [comment]
i'm also having problems on our ec2 instances now:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/9597/console

` F0127 19:08:24.899563       1 builder.go:193] Error: failed to retrieve cgroup limits: open /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us: no such file or directory`

normally when the quota value is wrong, the file at least exists with a "-1" but it seems something else happens on our ec2 env.

**Comment by bparees** [comment]
I found the issue w/ the jenkins system... different cgroup paths are used between docker versions!

ec2:
```
Docker version 1.8.2-el7, build a01dc02/1.8.2

[ec2-user@ip-172-18-4-101 fixtures]$ docker run -it openshift/jenkins-1-centos7  cat /sys/fs/cgroup/cpuacct,cpu/cpu.cfs_quota_us
-1

[ec2-user@ip-172-18-4-101 fixtures]$ docker run -it openshift/jenkins-1-centos7 cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us
cat: /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us: No such file or directory
```

local machine:
```
Docker version 1.9.1-fc23, build 110aed2-dirty

$ docker run -it openshift/jenkins-1-centos7  cat /sys/fs/cgroup/cpuacct,cpu/cpu.cfs_quota_us
cat: /sys/fs/cgroup/cpuacct,cpu/cpu.cfs_quota_us: No such file or directory

$ docker run -it openshift/jenkins-1-centos7 cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us
-1
```

I can update my code to check both paths, but this seems crazy?

**Comment by derekwaynecarr** [comment]
That looks like a good argument for moving to unified hierarchy so you just have /sys/fs/cgroup/cpu, but that is a ways off.

**Comment by mrunalp** [comment]
Yes, this could possibly be a bug for these subsystems. (I will be slow in responding as I am on PTO).

**Comment by mrunalp** [comment]
Also one more thing to check is the path where the combined cpu and cpuacct subsystems are mounted . I think the path may be different.

**Comment by bparees** [comment]
@mrunalp sorry, what would those paths be?

**Comment by mrunalp** [comment]
The output of grep cgroup /proc/self/mountinfo

**Comment by bparees** [comment]
on a rhel system, uses "cpuacct,cpu":
```
/sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,cpuacct,cpu
```

on a fedora system uses "cpu,cpuacct":
```
/sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:12 - cgroup cgroup rw,cpu,cpuacct
```

from within a centos image run on a rhel system, uses "cpuacct,cpu"
```
/system.slice/docker-548fdee136ffbdbeeb09fad4a2863aaf1990848ef9f39a952219eaa736d22e83.scope /sys/fs/cgroup/cpuacct,cpu ro,nosuid,nodev,noexec,relatime master:11 - cgroup cgroup rw,cpuacct,cpu
```

from within a centos image run on a fedora system, uses "cpu,cpuacct":
```
/system.slice/docker-bfa37e449aa41146477ae36916edcb3c31bb7a94669a9c55f82920fdd013f10e.scope /sys/fs/cgroup/cpu,cpuacct ro,nosuid,nodev,noexec,relatime master:12 - cgroup cgroup rw,cpu,cpuacct
```

i've modified my code to handle both paths so it's not critical, but it doesn't seem right.

**Comment by mrunalp** [comment]
@bparees You can get by the ordering issue by using the symlinks that are created when subsystems are grouped together. That way your code shouldn't care about whether it is cpu,cpuacct or cpuacct,cpu
Just modify the code to use the path `/sys/fs/cgroup/cpu/cpu.cfs_quota_us`

```
[root@dhcp-16-185 testcap]# docker run --rm -it fedora:latest bash
[root@7a81e3aea0c4 /]# Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
[root@7a81e3aea0c4 /]# 
[root@7a81e3aea0c4 /]# ls -l /sys/fs/cgroup/
total 0
drwxr-xr-x. 2 root root  0 Feb 16 12:23 blkio
lrwxrwxrwx. 1 root root 11 Feb 16 12:23 cpu -> cpu,cpuacct
drwxr-xr-x. 2 root root  0 Feb 16 12:23 cpu,cpuacct
lrwxrwxrwx. 1 root root 11 Feb 16 12:23 cpuacct -> cpu,cpuacct
drwxr-xr-x. 2 root root  0 Feb 16 12:23 cpuset
drwxr-xr-x. 2 root root  0 Feb 16 12:23 devices
drwxr-xr-x. 2 root root  0 Feb 16 12:23 freezer
drwxr-xr-x. 2 root root  0 Feb 16 12:23 hugetlb
drwxr-xr-x. 2 root root  0 Feb 16 12:23 memory
lrwxrwxrwx. 1 root root 16 Feb 16 12:23 net_cls -> net_cls,net_prio
drwxr-xr-x. 2 root root  0 Feb 16 12:23 net_cls,net_prio
lrwxrwxrwx. 1 root root 16 Feb 16 12:23 net_prio -> net_cls,net_prio
drwxr-xr-x. 2 root root  0 Feb 16 12:23 perf_event
dr-xr-xr-x. 3 root root  0 Feb 16 11:47 pids
drwxr-xr-x. 2 root root  0 Feb 16 12:23 systemd
```

**Comment by mrunalp** [comment]
Also, I haven't been able to reproduce this using docker at all. Could you give me the steps to recreate your environment so I could try it out that way (including how to setup the build, etc) ?

**Comment by bparees** [comment]
@mrunalp not all systems appear to create those symlinks.  Anyway i've added logic to handle all the paths i've learned about so far.

My steps for recreating it are:
1) oc create -f test/extended/fixtures/test-docker-build-quota.json
2) oc start-build docker-build-quota --from-dir test/extended/fixtures/build-quota --follow

Note that you should expect the build to always fail (that's by design), but the build logs will dump the cgroup values and i frequently see:
```
MEMORY=209715200
MEMORYSWAP=209715200
QUOTA=-1
SHARES=61
PERIOD=100000
```

Though not reliably.  If you can't reproduce it, starting your openshift server from a clean base may help, it seems like once it stops happening it's harder to make it start happening again.

**Comment by bparees** [comment]
The build log also dumps this line, which is based on the values it read from the cgroup filesystem on the build-pod:
` Running build with cgroup limits: api.CGroupLimits{MemoryLimitBytes:209715200, CPUShares:61, CPUPeriod:100000, CPUQuota:6000, MemorySwap:209715200}`

(in this case the CPUQuota value in the builder pod was seen correctly as 6000, though the container spun up for the docker build got a value of -1.  Usually what I see is that even the builder pod container has a -1 value also)

**Comment by mrunalp** [comment]
@bparees,  I will give it a try with a those steps. Thanks!
The symlinks are created within the docker container irrespective of whether they are on the host.

**Comment by bparees** [comment]
> The symlinks are created within the docker container irrespective of whether they are on the host.

@mrunalp that is not true if the host is a Debian machine, at a minimum.  @csrwng ran into that.

**Comment by mrunalp** [comment]
@bparees I was able to reproduce it after trying it out on a different machine. Can you point me to the Dockerfile/code from where you are printing out cgroups values?

**Comment by mrunalp** [comment]
@bparees Never mind, I found out the file.

**Comment by mrunalp** [comment]
It only showed up once. I added some debugs and at 80+ runs and counting :/

**Comment by bparees** [comment]
it seemed to me it happened more frequently when i had just started openshift, but i could be making a false correlation.

**Comment by mrunalp** [comment]
@bparees I am trying again with a new vm to see if that helps.

**Comment by jwhonce** [comment]
Lowering priority given how hard this issue is to reproduce.

**Comment by paralin** [comment]
Issue #8074 might be relevant.

Also I get this error sometimes:

```
    state:
      terminated:
        containerID: docker://c9593e2be6605462291e7428451e5d53f0d92e65086c3513b45c760abd8ecb0d
        exitCode: -1
        finishedAt: 2016-03-17T16:53:05Z
        message: '[8] System error: The minimum allowed cpu-shares is 1024'
        reason: ContainerCannotRun
        startedAt: 2016-03-17T16:53:05Z
```

Error is: `[8] System error: The minimum allowed cpu-shares is 1024`

This is on a build, I can't find any notation on the pod about requests or limits so I'm confused where this is coming from.

**Comment by mrunalp** [comment]
https://github.com/projectatomic/docker/pull/71 is a possible fix for this.

**Comment by ncdc** [comment]
@mrunalp @derekwaynecarr @smarterclayton can we close this - I think all the fixes are in place now?

**Comment by bparees** [comment]
sounds reasonable to me, we have tests that fail when this doesn't work right and no one has reported that flake recently (The flake issues have been closed).

**Comment by mrunalp** [comment]
Sounds good to me.
