### ISSUE TITLE
improve UI to show cpu and memory utilization for all replicas

### ISSUE THREAD

**Issue by ivanthelad** [openshift/origin#6826]
Currently its only possible to view the memory and  cpu usage for a pod. When a deployment consist of multiple replicas then it would be helpful to be able to see all pod replica's cpu/memory usage in one aggregate graph.with individual usage perhaps as a overlay graph

**Comment by spadgett** [comment]
@jwforres is this covered by https://trello.com/c/MWGqYyzj ?

**Comment by jwforres** [comment]
yes, closing since its tracked in trello
