### ISSUE TITLE
openshift cli get is not sorting the list

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#683]
The result of `openshift cli get <something>' is not sorted, so if you repeat this command, the list items are shuffling ;-)

**Comment by soltysh** [comment]
It should go upstream IMHO, especially since they've sorted it for event already, see https://github.com/GoogleCloudPlatform/kubernetes/issues/2948.

**Comment by smarterclayton** [comment]
Should be fixed now, please verify.
