### ISSUE TITLE
how to create the oauthaccesstoken via. oc comment ?

### ISSUE THREAD

**Issue by thincal** [openshift/origin#6832]
Is that possible to create a `oauthaccesstoken` unexpired forever by myself ?

**Comment by thincal** [comment]
I just get an example yaml file for the `oauthaccesstoken` by `oc get oauthaccesstoken xxx -o yaml`:
```
apiVersion: v1
clientName: openshift-challenging-client
expiresIn: 86400
kind: OAuthAccessToken
metadata:
  creationTimestamp: 2016-01-26T02:49:47Z
  deletionTimestamp: 2016-01-27T02:49:47Z
  name: 8871xbJZBBbAuKzE6qTJ4AjW34TSBn9IdvUD_T5cYDE
  resourceVersion: "1667413"
  uid: 76509be7-c3d7-11e5-9ce7-8cdcd44e7380
redirectURI: https://master1.ceyes.os:8443/oauth/token/implicit
userName: admin
userUID: f97783dd-9d90-11e5-8817-8cdcd44e7386
```
so that I can change the `expiresIn`, but which value is about unexpired ? thanks.

**Comment by liggitt** [comment]
You cannot create oauth tokens that do not expire. Also, only very highly privileged users have the ability to create oauth tokens, not normal users. If you are looking for a way to have an API token that does not expire, I suggest using a service account token. See https://docs.openshift.org/latest/dev_guide/service_accounts.html for more info.
