### ISSUE TITLE
Plan for cross-repo Docker mounting in the registry

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6841]
Now that cross-repo mounting has landed in docker/distribution and the engine, we should plan for what we need to do to support it.  I think it's as simple as a test read on the other repo, in which case the performance win should be massive as long as the docker daemon is properly associating the image we pulled with a credential for push.

**Comment by miminar** [comment]
A rebase to distribution [v.2.3](https://github.com/docker/distribution/wiki/distribution-1.10-Project-Page) (ETA is 02/04/2016) seems the only work needed to me.
The test read is already done in the engine. I share your worries about associating and selecting the right credentiels by Docker.
