### ISSUE TITLE
[question] About the docker build strategy

### ISSUE THREAD

**Issue by thincal** [openshift/origin#6842]
There is one [example](https://github.com/openshift/origin/blob/master/test/extended/fixtures/test-docker-build.json) about the docker-build as bellow:
```
  "spec":{
    "triggers":[],
    "source":{
      "type":"Git",
      "git":{
        "uri":"https://github.com/openshift/origin"
      },
      "contextDir":"test/extended/fixtures/test-build-app"
    },
    "strategy":{
      "type":"Docker",
      "dockerStrategy":{
        "from":{
          "kind":"DockerImage",
          "name":"centos/ruby-22-centos7"
        }
      }
    },
```

My understanding about the docker build strategy is that it is running `docker build` with the dockerfile from the repo specified by the `spec.source`, but what's the usage about the `spec.strategy.dockerStrategy` ? thanks.

**Comment by thincal** [comment]
also question about the `spec.strategy.customstrategy` in the custom build type, thanks.

**Comment by mfojtik** [comment]
@thincal we replace the `FROM` line in Dockerfile with the resolved image pull reference (which allows to reference ImageStream here).

**Comment by thincal** [comment]
Thanks for info.

Do you mean that the `spec.strategy.dockerStrategy.from.name` will override the `FROM` line in Dockerfile from the repo?

**Comment by mfojtik** [comment]
@thincal yes, it will resolve

**Comment by thincal** [comment]
Thanks
