### ISSUE TITLE
Web console raw edit errors can extend offscreen

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6845]
If there are too many errors, the top of the modal is no longer visible.

<img width="676" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/12615993/dedee534-c4d6-11e5-9643-7c2d0dbbaf1e.png">

/cc @jwforres

**Comment by jwforres** [comment]
well thats not good, are we setting a specific height, i thought the height was responsive?  just need to call resize or something?

**Comment by spadgett** [comment]
It's responsive, but calculated before the error message is displayed.

**Comment by spadgett** [comment]
Starting to wonder if the editor should be a separate page instead of a modal.

**Comment by jwforres** [comment]
it would give you more screen real estate to view the YAML

**Comment by spadgett** [comment]
Yeah, we have some long lines in our YAML. Also it'd be consistent with the build config editor.

**Comment by spadgett** [comment]
Quick experiment:

![screen shot 2016-01-29 at 1 49 09 pm](https://cloud.githubusercontent.com/assets/1167259/12684926/57e7e5d4-c68f-11e5-9baa-5e709601a35f.png)

**Comment by jwforres** [comment]
gray header seems to big, transition from gray to editing area, and then
editing area back to gray, needs some shadowing

**Comment by benjaminapetersen** [comment]
+1 to new page & space.
