### ISSUE TITLE
`os::text::clear_last_line` doesn't clear full line when line is wrapped

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6846]
When a line is longer than the terminal width and is wrapped, each part of the line is considered a line, so the function doesn't clear the entirety of the line.

@deads2k I think this might be a P1

**Comment by deads2k** [comment]
> @deads2k I think this might be a P1

It was a function I didn't want to begin with.  Why would I care now?  This just affects display in a terminal of a testing, not the end result right?  P3 at best unless it makes the output impossible to decode (unlikely)

**Comment by stevekuznetsov** [comment]
After further investigation it seems like this is impossible to fix.
