### ISSUE TITLE
cluster-reader no longer has cluster read permissions

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#6847]
A user with cluster-reader permissions no longer has the ability to read information from the cluster.

steps to reproduce:
1) `oadm policy add-cluster-role-to-user cluster-reader test`
2) verify that user `test` is not in the list of users able to view all pods `oadm policy who-can view pods --all-namespaces`

cluster admins still have this ability, if you run `oadm policy add-cluster-role-to-user cluster-admin test`
then the `test` user will appear under the list of users able to view all pods across namespaces

**Comment by liggitt** [comment]
Are your role definitions up to date? Does this indicate anything needs updating:
```
oadm policy reconcile-cluster-roles
```

**Comment by liggitt** [comment]
oh... "view" isn't a verb. You want "get" "pods". cluster-admin works because they can do any verb

**Comment by liggitt** [comment]
```
$ oadm policy add-cluster-role-to-user cluster-reader test

$ oadm policy who-can get pods --all-namespaces
Namespace: <all>
Verb:      get
Resource:  pods

Users:  system:serviceaccount:openshift-infra:build-controller
        system:serviceaccount:openshift-infra:deployment-controller
        system:serviceaccount:openshift-infra:pv-recycler-controller
        test

Groups: system:cluster-admins
        system:cluster-readers
        system:masters
        system:nodes
```
