### ISSUE TITLE
Generate ugorji codecs for origin types

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6848]
The generated codecs for k8s types were dropped in https://github.com/openshift/origin/pull/6320, because it caused serialization problems for our origin types (which didn't implement `CodecEncodeSelf`) to inline k8s types that did (like TypeMeta),

Reasons to generate them:
- same performance benefits as upstream
- ~~let us drop the `<carry>` commit that removes the generates codecs from upstream types~~ we would still drop upstream and regenerate

Blockers:
- Makes binaries 15MB bigger
- Adds 10-15 minutes to our build/test time for verifying codec generation
- ~~Makes any API change automatically get a 20k line conflicting diff~~ fixed in https://github.com/ugorji/go/pull/137 / https://github.com/kubernetes/kubernetes/pull/20770
- We have to regenerate codecs for k8s types as well for our carried types and fields
- Given ^, we need much more test coverage on k8s type serialization and round tripping
- Generated codecs do not have good tests for deserialization edge cases (e.g. until a month ago, they treated nil and [] identically)

Setting initial priority to p1 to triage performance impact of not having these

WIP generation script in https://github.com/liggitt/origin/commits/codec_gen

**Comment by deads2k** [comment]
@stevekuznetsov fyi

**Comment by liggitt** [comment]
The downsides are significant:
* Makes binaries 15MB bigger
* Adds 10-15 minutes to our build/test time for verifying codec generation
* Makes any API change automatically get a 20k line conflicting diff
* Means we need to figure out codecgen of k8s codecs for our carried types and fields

**Comment by stevekuznetsov** [comment]
The diff is something I can work on if we decide we are going in this direction.

**Comment by liggitt** [comment]
I'd like the var name allocation made function-local in ugorji generally… if only for upstream

**Comment by liggitt** [comment]
Fix for the massive diffs proposed at https://github.com/ugorji/go/pull/137 and https://github.com/kubernetes/kubernetes/pull/20770

**Comment by liggitt** [comment]
don't plan to do this. we'll drop ugorji upstream as soon as we can prove it doesn't impact performance noticeably when all the control plane components are using protobuf
