### ISSUE TITLE
Change SCC int/int64 types

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6850]
Because of issues with int overflow, upstream has changed int->int32, and squashed int64 to int32 in conversion. SCC types need to be updated to match this.

**Comment by mfojtik** [comment]
@pweil- @liggitt is this still valid? (this issue is now +6months old)

**Comment by pweil-** [comment]
need to make sure that the strategies that have options of int64 datatype are being squashed in conversion.  I don't think there are any ints left

**Comment by mfojtik** [comment]
@php-coder can you do a quick sweep to make sure that all strategies use int64 now? (they should, just need confirmation)
