### ISSUE TITLE
Webconsole redirect make it unsuitable for ssh tunnel

### ISSUE THREAD

**Issue by mscherer** [openshift/origin#6855]
I decided to give a try to openshift on a atomic VM. I did start it at home, using the docker image, and it started fine. Then, as i was not in my LAN, I did used a ssh tunnel from my laptop to the atomic system on the port 8443. 

And then, I started my browser, pointed to https://127.0.0.1:8443/ I found that / is redirected to https://192.168.122.134:8443/console/ (which is not a routable IP).

While there is --public-master, this will then redirect all regular clients as well. One work around is to be creative with /etc/hosts and that setting, but that's a kludge. 

While i would suggest to not do a absolute redirect, I also guess I am missing something important for that.

**Comment by liggitt** [comment]
The web console can be served from a different host and port than the API (where the OAuth flow occurs), so it can't assume a relative redirect would work. In general, the console needs a reachable address for the API server (not just for login). Setting public-master to a reachable address is a requirement for the web console.

**Comment by liggitt** [comment]
For your setup, the best options might be to set public master to https://127.0.0.1:8443 and port forward, or set it to a domain and do etc host aliasing as you noted

**Comment by mscherer** [comment]
Sure, but in the case of the all in one server (which is is the one provided by the docker image), it is not the case, everything run at the same place. So the server can be smart in this case and do a relative redirect.

**Comment by liggitt** [comment]
OAuth flows require an absolute redirect_uri to return the API token to the console after a login. You really need public-master to point to an accessible URL for the master

**Comment by mscherer** [comment]
Since the oauth flow is done in JS on the browser side (from what I was able to understand), the problem then become not that the redirect is absolute but that the URL that is used is incorrect. Since the console is in JS and the information seems to come from /console/config.js, what about using window.localtion instead of getting the data from the server ?
(ie, the setting window.OPENSHIFT_CONFIG.auth.oauth_redirect_base )

And if config.js need to a pure json file for use by more than the web console, getting the default updated could be done later in the page (in a place where we do not have the json constraint)

**Comment by liggitt** [comment]
The OAuth redirect uri has to match an allowed absolute redirect uri registered server side. It cannot be calculated dynamically against an arbitrary hostname

**Comment by Anandanr** [comment]
Hi, When I trying to add public master like follows, no success. any clue.
root@apachestratos-1a:~# docker run -d --name "origin"         --privileged --pid=host --net=host     --public=master=https://10.10.103.246:8443  -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw         -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes         openshift/origin start
flag provided but not defined: --public
See 'docker run --help'.
root@apachestratos-1a:~#

**Comment by jwforres** [comment]
You have --public=master=https://10.10.103.246:8443
should be --public-master=https://10.10.103.246:8443
first = needed to be a -

**Comment by Anandanr** [comment]
Thanks but no success: see the out put below:

flag provided but not defined: --public-master
See 'docker run --help'.
root@apachestratos-1a:~#

**Comment by jwforres** [comment]
--public-master is not a docker run argument, it's an argument to the
openshift start command

**Comment by Anandanr** [comment]
Thanks for your help, this solved my problem,, see the command I used:
 docker run -d --name "origin" -p  --privileged --pid=host --net=host -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw  -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes   openshift/origin start  --public-master=https://10.10.103.246:8443
