### ISSUE TITLE
Pods stuck in 'Pending' when volumes or secrets fail to be mounted (expected an error)

### ISSUE THREAD

**Issue by ryanj** [openshift/origin#6859]
I used to include volume mount information in my application templates (since similar information is included in the mongodb-emphemeral template). 

I recently had to remove those sections from the spec because the associated pods were getting stuck in a Pending state: https://github.com/ryanj/restify-mongodb-parks/commit/96fb14781017ea0b8daa142f55afe25c4136b64a

Should we return an error when declared volumes or secrets fail to be mounted?

**Comment by ryanj** [comment]
Related: https://github.com/openshift/origin/issues/6781

**Comment by liggitt** [comment]
return an error at pod create time? or when the pod is scheduled and the kubelet tries to run it?

**Comment by ryanj** [comment]
I'm not sure. I think the kublet might be stuck waiting for the (misconfigured?) volume to become available.

If we can detect a clear misconfiguration, it would be nice to error back early.  If we're waiting for something specific, then I'd like to know why we're 'Pending' and not 'Running'.

**Comment by ryanj** [comment]
The only relevant info from `oc describe dc` was: 

    Pods Status:	0 Running / 1 Waiting / 0 Succeeded / 0 Failed

**Comment by ryanj** [comment]
@liggitt Ah crap, suddenly I can no longer reproduce this issue.  

It's a bit of an edge case, anyway. Feel free to close if it doesn't sound like a big enough ux win.

**Comment by liggitt** [comment]
We wouldn't do cross object lookups to validate a pod on submission. If you see it again, check if there are events or details in the pod status. If there is and we're not bubbling it up well, that could be improved.

**Comment by ryanj** [comment]
ok, I'll reopen and add some additional detail if I see it again. Thanks
