### ISSUE TITLE
a bug in all-sti that ImportError: No module named urllib.parse

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#6867]
hi,
when i use sti-base[1],sti-nodejs[2],that have error when i use like this:
`$ git clone https://github.com/openshift/sti-base.git
$ cd sti-base
$ make build`
![build-1](https://cloud.githubusercontent.com/assets/12937669/12638793/e2138214-c5da-11e5-99f5-45fe9acb99b1.jpg)

The urlparse module is renamed to urllib.parse in Python 3
Tue name is urlparse module for Python 2.7

who can i do for this，thanks！

[1].https://github.com/openshift/sti-base
[2].https://github.com/openshift/sti-node

**Comment by wenskys** [comment]
also error in sti-wildfly
https://github.com/openshift/sti-wildfly
![build-2](https://cloud.githubusercontent.com/assets/12937669/12639152/7415a7f8-c5dd-11e5-9838-d9c90966865a.jpg)

**Comment by bparees** [comment]
this issue is coming from the docker-scripts package (https://github.com/goldmann/docker-scripts) maintained by @goldmann

suggest you open an issue there.

**Comment by bparees** [comment]
in the meantime if you set SKIP_SQUASH=1 as a env var, you should be able to work around this problem.
