### ISSUE TITLE
pvc status could use more details

### ISSUE THREAD

**Issue by jmccormick2001** [openshift/origin#6875]
would be great if when you do 'oc get pvc' that the status shows more detailed information.  For example, I recently spent time debugging why my pvc was forever in 'Pending' status.  Fortunately I found in the logs (loglevel=5) the messages:

I0128 08:56:21.501128    6929 persistentvolume_claim_binder_controller.go:196] Synchronizing PersistentVolume[pv0001], current phase: Available
I0128 08:56:21.518409    6929 persistentvolume_claim_binder_controller.go:326] Synchronizing PersistentVolumeClaim[backupsclaim1]
I0128 08:56:21.518442    6929 persistentvolume_claim_binder_controller.go:337] A volume match does not exist for persistent claim: backupsclaim1

This led me to Google search on 'volume match persistent_claim' and found where someone else had this exact error and pointed out that maybe the AccessModes were not matching between the
PV and PVC, that was my exact error.

I suspect others will have all sorts of errors like this, would be great if you could add more detailed status or logging to indicate the reason a PVC is in 'Pending' status, perhaps 'Pending - no match on access mode', or similar.

**Comment by smarterclayton** [comment]
oc status should also be changed to provide suggestions for any claim that has existed for more than X time and isn't bound.

**Comment by erinboyd** [comment]
@smarterclayton my team will be taking this one
