### ISSUE TITLE
Add "comments" API for imagestreams and other objects

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#6876]
Providing an interface for users to comment on imagestreams would be very useful. See [Docker Hub example](https://hub.docker.com/r/_/centos/). I would expect by default authenticated users to be able to view comments; project admins to create/delete comments.

**Comment by mfojtik** [comment]
you can add annotations

**Comment by aweiteka** [comment]
Annotations might work, especially for a lean implementation and single comments. Managing a comment thread would be a bit hacky and would require an annotation convention. Example:

```
$ oc annotate is/centos comment-123456="latest stable from upstream"
$ oc annotate is/centos comment-123456_author="admin"
$ oc annotate is/centos comment-123456_datetime="`date`"
$ oc annotate is/centos comment-123457="This is working for me"
$ oc annotate is/centos comment-123457_author="aweiteka"
$ oc annotate is/centos comment-123457_datetime="`date`"
$ oc get is centos -o yaml
...
metadata:
  annotations:
    comment-123456: latest stable from upstream
    comment-123456_author: admin
    comment-123456_datetime: Thu Jan 28 16:36:25 UTC 2016
    comment-123457: This is working for me
    comment-123457_author: aweiteka
    comment-123457_datetime: Thu Jan 28 16:37:48 UTC 2016
    openshift.io/image.dockerRepositoryCheck: 2016-01-28T16:16:55Z
...
```

**Comment by liggitt** [comment]
-1 for shoehorning a social API into annotations
I would not expect to be able to have comment threads on images/imagestreams in the short term

**Comment by fatherlinux** [comment]
So, no idea what's right from an engineering perspective, but this would be extremely useful from a user's perspective. The composable nature of Docker images make them very different than ISOs. I think the desire is there with AWS/OpenStack images, but it becomes very obvious with Docker images [1].

Not sure where to capture these, so going to document here. As a service designer, or core builder or container image builder, I would like to have the following items to determine if a competent (like a Docker image) is viable for my projects:

1. Engineering paradigm (e.g. release notes)
2. Support lifecycle (when will this image no longer be good)
3. How to use this image
4. Documentation URL for this image
5. The ability to easily dial for help (e.g. comments)
6. Security information (errata (what has been patched, what has not), compromise count (perhaps SEIMs may add this))
7. Temporal information (average start time (yes this is currently a pipe dream), revocation date, availability date)
8. Compatibility information (can this container image be upgraded in place will it change the schema of data mounted into it in a non-backwards compatible way. e.g. am I stuck if I roll forwards)

[1]: http://crunchtools.com/core-builds-service/

**Comment by liggitt** [comment]
with the possible exception of "The ability to easily dial for help (e.g. comments)", wouldn't you want those available in the docker image data more than the openshift/k8s API data?

**Comment by fatherlinux** [comment]
@liggitt, Yeah, I think you are correct. Actually, I just realized this was for the API, and not image labels. Actually, I would even be fine with all of it living in image labels and just being consumed by the registry. Again, I am not deep enough in the architecture to make an intelligent opinion, I just wanted to throw the end user story out there ;-)

**Comment by aweiteka** [comment]
> Engineering paradigm (e.g. release notes)
> Support lifecycle (when will this image no longer be good)
> How to use this image
> Documentation URL for this image
> The ability to easily dial for help (e.g. comments)
> Security information (errata (what has been patched, what has not), compromise count (perhaps SEIMs may add this))
> Temporal information (average start time (yes this is currently a pipe dream), revocation date, availability date)
> Compatibility information (can this container image be upgraded in place will it change the schema of data mounted into it in a non-backwards compatible way. e.g. am I stuck if I roll forwards)

@fatherlinux let's review the current label standards[1] and add anything lacking there. They can be visualized per this work[2]

[1] https://github.com/projectatomic/ContainerApplicationGenericLabels 
[2] https://trello.com/c/Xi0A0lxU/238-5-code-web-views-for-docker-image-registry-wireframes-docs-atomic-registry

**Comment by liggitt** [comment]
Closing this in favor using annotations for simple admin comments, and using docker labels for image-related metadata. I don't see a general comments API as being in scope.

Additionally, the current API design is not well suited to the things you need from a comments API - sorting/paging/filtering/"since" function, etc. I want those things generally, but I would REALLY want them for a comments API.

Since this doesn't seem like core function, and would be complex to add, I think we should close this.
