### ISSUE TITLE
Unify API version negotiation with upstream

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6880]
Refactor version negotiation so we can share common code with upstream

**Comment by sgallagher** [comment]
@liggitt 
I assume this issue is talking about pkg/cmd/util/clientcmd/negotiate.go but I'm not sure precisely what needs to be unified (or where) with upstream code. Could you offer a pointer or two?

**Comment by liggitt** [comment]
Yeah, looking at unifying what was added in https://github.com/openshift/origin/pull/6320/commits/6b7f6f9cb0bf4eab4f1214ed4d143d47f0360598

The main issue is that upstream makes assumptions about where version information lives (they hardcode `/api`, origin types are under `/oapi`)
