### ISSUE TITLE
Rebase checklist

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6881]
Extracted from https://github.com/openshift/origin/pull/6320

- remove pkg/api/latest package
- check the parseRuntimeConfig impl upstream to make sure we're still building the right magic container in getAPIGroupVersionOverrides
- Pick up kubernetes/kubernetes#19970 (or similar) for namespaced objects
- k8s has a slightly newer version of etcd (2.2.2+git), decide whether or not to pick it up

**Comment by timothysc** [comment]
- cache resizing https://github.com/kubernetes/kubernetes/pull/19783
- kubecontainer.Cache https://github.com/kubernetes/kubernetes/pull/19850

**Comment by liggitt** [comment]
Rebase has already started. Add trackers for PRs in progress to the 3.2 issue

**Comment by kargakis** [comment]
Doesn't seem like there is anything else tbd here
