### ISSUE TITLE
We should show the builder image version in build log

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#6894]
That will help debugging problems with "old" builder images and improve QE reports. It could be V(2) or higher.

**Comment by PI-Victor** [comment]
@mfojtik are these two issues related ? https://github.com/openshift/origin/issues/4570

when you say builder-image, do you mean docker/s2i or do you mean builder images like sti-python, etc. right now we are displaying in the build log something like:

```
I0223 19:49:48.518787       1 builder.go:57] Master version "v1.1.3-192-g112b3cb", Builder versions "v1.1.3-192-g112b3cb"
```

**Comment by bparees** [comment]
yeah i added that recently at @csrwng's request as part of another PR, this can be closed (i'm going to fix the "versions" typo though)

**Comment by PI-Victor** [comment]
@bparees thanks, wanted to ask that but in the back of my mind i was assuming that there might be multiple versions for some reason and it's not a typo :-)
