### ISSUE TITLE
Web console: Build log never begins streaming when phase changes to running

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6897]
The log content never appears, only the loading ellipsis.

![screen shot 2016-01-29 at 8 13 58 am](https://cloud.githubusercontent.com/assets/1167259/12676443/4d1d780a-c660-11e5-9276-176f08e5d13d.png)

See also #6878

@benjaminapetersen

**Comment by benjaminapetersen** [comment]
So for a build, the log content does not appear when the status changes from 'Pending' to 'Running'.  Correct?

**Comment by spadgett** [comment]
Exactly. Haven't tested pods or deployments.

**Comment by jwforres** [comment]
I reproduced this even with a running pod, the issue seems to be when coming directly into the logs tab when the tabs=log query param is set

**Comment by jwforres** [comment]
P1 because all of our links that take a user directly to a build log are now broken.

**Comment by benjaminapetersen** [comment]
Hmm, yup thats it.  Normally it works as expected, but the `?tab=logs` query param breaks it.
