### ISSUE TITLE
Build i/o timeout

### ISSUE THREAD

**Issue by charliemaiors** [openshift/origin#6899]
Hi,

today out of the blue openshift after 20 seconds from the beginning of the build gives me this error (for a test application that previously work):

``` bash
I0129 14:47:20.689712       1 builder.go:34] $BUILD env var is {"kind":"Build","apiVersion":"v1","metadata":{"name":"test-app-bc-1","namespace":"test","selfLink":"/oapi/v1/namespaces/test/builds/test-app-bc-1","uid":"2e1a7f82-c697-11e5-949e-001a648f9cf6","resourceVersion":"427662","creationTimestamp":"2016-01-29T14:47:12Z","labels":{"buildconfig":"test-app-bc","openshift.io/build-config.name":"test-app-bc"},"annotations":{"openshift.io/build.number":"1"}},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"mygitrepo"}},"strategy":{"type":"Docker","dockerStrategy":{"env":[{"name":"BUILD_LOGLEVEL","value":"5"},...]}},"output":{"to":{"kind":"DockerImage","name":"172.30.86.6:5000/test/test-app:latest"},"pushSecret":{"name":"builder-dockercfg-oamo1"}},"resources":{}},"status":{"phase":"Pending","outputDockerImageReference":"172.30.86.6:5000/test/test-app:latest","config":{"kind":"BuildConfig","namespace":"test","name":"test-app-bc"}}}

F0129 14:47:36.783103 1 builder.go:59] Build error: dial tcp: i/o timeout 
```

What I've to do? Could be the same issue of the previous SDN bugfix?

**Comment by bparees** [comment]
That error generally means we couldn't git clone your source which usually means the pods don't have external network access.

1) can you get verbose logs?  https://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs
2) can you run another pod (eg "oc new-app openshift/jenkins-1-centos7") and then oc rsh into the pod and check if you can perform a git clone from within it?  (that image has git installed).  If you can't, do some other investigation like checking if DNS resolves, and whether you can ping external addresses, etc.

**Comment by charliemaiors** [comment]
1) I've used the BUILD_LOGLEVEL 5 to get that log, it fails in less then 20 seconds;
2) Using the jenkins pod I can't clone anything because I don't have sufficient permissions on the fs (I cannot also create a directory), I've tried to ping google DNS but I don't have permissions also for that. I've tried to ping google.com and the pod says ```bash bash-4.2$ ping google.com    
ping: unknown host google.com ``` I've to update my installation to version 1.1.1?

**Comment by bparees** [comment]
that you're unable to resolve google.com certainly points to a DNS configuration issue.

what is the /etc/resolv.conf in the container?

**Comment by charliemaiors** [comment]
```bash
nameserver ip-of-my-server
nameserver 8.8.8.8
search test.svc.cluster.local svc.cluster.local cluster.local local
options ndots:5
```

**Comment by coreydaley** [comment]
@charliemaiors closing due to age and inactivity, please re-open or create a new issue if you are still experiencing this issue with an up-to-date version of origin
