### ISSUE TITLE
Path-based routing does not work as expected

### ISSUE THREAD

**Issue by whitlockjc** [openshift/origin#6914]
When creating a route for a service in Origin, I'm seeing behavior that is unexpected.  Before calling it a bug, I figured I would get your opinions by describing what I'm seeing and what I expect.  If we agree it's a bug, I'd be happy to submit a PR.  Here goes...

Let's say I've got a REST API being deployed as a service on Origin.  When I create a new route, I give it a path of `/my-api`.  When I access my REST API using `/my-api/endpoint1`, my application sees a request for `/my-api/endpoint1` and the result is a `404`.  The reason for this is my application is written to handle the `/endpoint1` path, not `/my-api/endpoint1`.

As an application author, I would not expect that the base path used for routing to be seen by my container.  What I would expect is that a request for `/my-api/endpoint1` to be seen as `/endpoint1` at the service/pod/container level.

I originally ran into this while going through the quick start guide.  When I deployed the nodejs-ex project, I wanted to use path-based routing so that I didn't need to update my `/etc/hosts` file again.  To my surprise, the application didn't work with path-based routing but worked fine with host-based routing.  Ironically, within an hour a colleague of mine ran into the exact same problem but with a simple Ruby on Rails container he was testing.  _(Here is a little more detail on the exact scenario I ran into: https://github.com/openshift/nodejs-ex/issues/31)_

With all of this being said, am I wrong in my expectation?

**Comment by liggitt** [comment]
It working as designed. Subcontext path-rewriting would be an additional transformation step in the routing layer, but isn't intended to be done today. There are definitely use cases for it, but it's a new feature, not a bug.

**Comment by whitlockjc** [comment]
Is this design decision up for debate, or would a PR be interesting to you?  This is a very common API management feature, the ability to host APIs at a specific path but the logic behind the path is unaware of the base path.  As an API provider, I might use path-based routing for numerous reasons but the application behind the path should only know about the paths relative to the base path used for routing.  Thoughts?

**Comment by liggitt** [comment]
> the application behind the path should only know about the paths relative to the base path used for routing

What you're describing requires a rewriting proxy, which is more than just a router. There are use cases both ways, some where the application needs to know the full path, and some where you want it to be ignorant that it is under a subpath. Applying path-rewriting proxy behavior would need to be opt-in... not everyone wants the router messing with their requests and responses to that degree. Not disagreeing that it's a useful feature, but it would need to be implemented in a way that still allowed for the existing behavior. Thoughts or PRs are welcome!

**Comment by whitlockjc** [comment]
Ah, that makes sense.  Speaking of a PR...what about just making this a configurable setting for the route?  I'd be happy to do the work if we can agree on an implementation...even if only at a high level.

**Comment by dbalakirev** [comment]
I wonder if there is a good example to resolve this problem that @whitlockjc describes. I created a CouchDB example project. If I configer the route for '/' then I could access my futon gui as:
`http://myoriginserver.com`
But I would like to access couchdb futon gui via:
`http://myoriginserver.com/couchdb`
essentially using path-based routing to access different applications I'd deploy.

**Comment by whitlockjc** [comment]
After writing my own ingress controller for k8s, I can see how this isn't a simple _"Yeah...let's do this"_ scenario.  But I do think that it should be supported.  The issue is that you get to the point where you need to do URL rewriting at the ingress controller level.  It's not impossible but it adds two things:

* Complexity at the ingress controller level
* Extra configuration at the k8s kind level

I'd love to help out if it's something we want to pair on.

**Comment by elyscape** [comment]
To deal with situations like this (and others), I made a modified router with support for regular expressions in the paths. The GitHub repo is at elyscape/origin-router-regexp and it's on the Docker Hub as [elyscape/origin-haproxy-router-regexp](https://hub.docker.com/r/elyscape/origin-haproxy-router-regexp/).

**Comment by codependent** [comment]
I'm facing the same problem. It would be great that this was addressed at some point. So far I had been working with Kubernetes and Traefik ingress solved it (traefik.frontend.rule.type: PathPrefixStrip): https://docs.traefik.io/user-guide/kubernetes/#path-based-routing

**Comment by ErikLundJensen** [comment]
Why don't you use the logical DNS name for this? For example:

http://mycouchdb.myoriginserver.com

Thereby you don't get into issues like path rewrite. You could even add version and namespace/project name to your logical DNS name:
http://mycouchdb-v2-myproject.myoriginserver.com

I do think that this feature is one of the most important of OpenShift/Kubernetes.

**Comment by marouim** [comment]
/reopen

Here is my use case: 
Front-end application running in a POD. 
Back-end running in a différent POD.

Route are:
myapp.example.com/  -->  Front-end
myapp.example.com/api --> Back-end

I would like to be able to rewrite the path and remove the "/api" portion, so the Backend would not see this path. Otherwise, I have to tell evey backend developer to add a "/api" or something else prefix to their application. 

Just like proxyTable in webpack: 

proxyTable: {
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        },
      }

Thanks for your help !

**Comment by Gerrit-K** [comment]
@ErikLundJensen there are several reasons, some of which are:
* You don't want to pay for a second domain
* You are not authorized to create subdomains
* You don't want to hassle with CORS errors

The example @marouim gave is in fact a common configuration.

@eparis since this issue is assigned to you, could you please give a statement whether this is possible by now and - if not - reopen this issue?
