### ISSUE TITLE
UI not reflecting correct deployment

### ISSUE THREAD

**Issue by rettori** [openshift/origin#6919]
deployment # 4 
build  # 1 
<img width="1007" alt="screen shot 2016-01-30 at 12 57 12 pm" src="https://cloud.githubusercontent.com/assets/2352755/12697436/5550bf90-c751-11e5-9d99-37aa405e9df0.png">

This also happens on the deployments tab.

**Comment by liggitt** [comment]
If you reload the overview page, does it still show the wrong deployment? Can you capture the deployment configs, replication controllers, pods, build configs and builds in the namespace that the point when this happens? (`oc get bc,builds,dc,rc,pods -o yaml > data.yaml`)

**Comment by liggitt** [comment]
Also image streams in the namespace as yaml

**Comment by rettori** [comment]
here.
[data.yaml.zip](https://github.com/openshift/origin/files/112277/data.yaml.zip)

**Comment by jwforres** [comment]
@rettori if you haven't touched anything in the namespace yet, can you look for an XHR request that has /imagestreamimages/ in the path, I want to see which URL is being requested and what its returning.  Based on what i'm seeing it should have been asking for sha f3d0727a6937cf88bf874bf73a840777f33c707a516707abc7af20f69689f748

but the data showing up is for sha c8e106ec70dd58989c8d7b37c4ab573faaf035db32a0a8a7f924726725147f1e

**Comment by jwforres** [comment]
as suspected the request was made to get the imagestreamimage with the f3d07 sha, but the API returned the data for the first image that was pushed to the 'latest' tag

**Comment by smarterclayton** [comment]
.... this looks impossible.

On Mon, Feb 1, 2016 at 12:56 PM, Jessica Forrester <notifications@github.com

**Comment by smarterclayton** [comment]
Can you paste both image stream tag and image stream json?
