### ISSUE TITLE
Rename hack/test-cmd_util.sh to something that doesn't ruin my autocomplete-fu

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6921]
There can only be one `hack/test-c<TAB>`.

**Comment by stevekuznetsov** [comment]
It's in the trap PR. How do you feel about reviewing it? :)

**Comment by smarterclayton** [comment]
Sounds like a lot of work ...

**Comment by stevekuznetsov** [comment]
I guess that depends on how much you enjoy auto-complete :)

Speaking of which... @deads2k enjoys making branches starting with `ma...` and I've got him as a remote... you can see where this is going.

**Comment by smarterclayton** [comment]
Trolling people through GitHub remotes is a new one - I like it.
