### ISSUE TITLE
The internal representation of image streams should not include the registry service IP

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#6924]
We need to take steps to isolate data stored in etcd from taking direct references to the IP / name of the integrated Docker registry.  This will allow users to more easily switch between them post-deployment.  Also, when tagging images from one stream to another, we should update references to images so that the value in status corresponds to the current stream, not to the originating stream.  We should prepare for the eventual migration of registry names on the command line as part of the general work to support migration and upgrade of the cluster by integrating a "registry name migrator".  And we should recognize the user of internal / external image reference names more accurately in various parts of the API stack.

**Comment by mfojtik** [comment]
To recreate:

```console
$ oc new-project prod
$ oc new-project stage

$ oc create -f https://gist.githubusercontent.com/mfojtik/e293038789c8903cae51/raw/321a45fd23b189a5ae8b24a050f36bd7509c2b35/gistfile1.txt

$ oc start-build sample-app --follow --wait
$ oc tag stage/sample-app:latest stage/sample-app:stable

$ oc project prod
$ oc create -f https://gist.githubusercontent.com/mfojtik/085d4fd33cba82b51fc8/raw/0a5b644fc5586fe2e5f4ea1045dd987f4538988c/gistfile1.txt
$ oc tag stage/sample-app:stable prod/sample-app:latest
```

Now, what you see is this:

```console
$ oc get istag sample-app:latest -n prod
NAME                DOCKER REF                                                                                                     UPDATED          IMAGENAME
sample-app:latest   172.30.167.193:5000/stage/sample-app@sha256:285e07071237b99e1e59e20ca18ad71c56f5abf32b7119826b7da2ee6ba2af64   20 minutes ago   sha256:285e07071237b99e1e59e20ca18ad71c56f5abf32b7119826b7da2ee6ba2af64
```

The DOCKER REF here should be "prod/sample-app". This is then propagated up to Deployment where you will see "stage/sample-app" instead of "prod/".

**Comment by ncdc** [comment]
I'm curious what you're thinking of doing so that we know the `dockerImageReference` is for the integrated registry vs an external one?

**Comment by smarterclayton** [comment]
At a minimum, does it match the current value for the registry.  Migration
/ fixup probably is going to require the admin to say "I want to map
registry X to registry Y" - i.e. "registry.access.redhat.com" to "
registry1.access.redhat.com" or something.  That's actually generally
useful, now that I think about it.  It's something an admin needs to do
anyway.

**Comment by ncdc** [comment]
I'm thinking longer term, you'll have 2 `status.tags` entries: 1 for an image in the integrated registry, 1 for an external registry. Do you add a `bool` to the struct to indicate that `foo/bar@sha256:123` is for the integrated registry?

Oh wait, we already know if the image is managed by the integrated registry - we have an annotation for it. Could we key off of that somehow, and just ignore whatever registry value is in the pull spec, replacing it with what we know the registry to be?

**Comment by smarterclayton** [comment]
Why do we need two?  Why do we even need to record it?  If you have tagged
the image into our stream, and it points to the current registry, we can
rewrite it ourselves.  If you gave us that reference (in status) we still
own it.

**Comment by ncdc** [comment]
I was in a hurry to type my previous comment and it didn't come out the way I intended.

Let's imagine you have an ImageStream and you want to have 1 tag point to an image in the integrated registry and another tag point to an external image. What would you expect to have as values for dockerImageReference in both cases?

> We need to take steps to isolate data stored in etcd from taking direct references to the IP / name of the integrated Docker registry

I interpreted this as "we should not store the IP/name of the registry in our pull specs". Is that a correct interpretation?

**Comment by smarterclayton** [comment]
Yes, that is correct.  Integrated images should be returned to clients as
<PUBLIC_REGISTRY_DNS_NAME>/foo/bar@id.  External tags should be either
<PUBLIC_REGISTRY_DNS_NAME>/foo/bar@id if pull through is enabled, or
otherregistry/bar/baz.

**Comment by soltysh** [comment]
What we show if there's no public dns name?

**Comment by smarterclayton** [comment]
The service DNS name.

**Comment by smarterclayton** [comment]
Or the service IP - there are downsides to both.

**Comment by xiaoping378** [comment]
@smarterclayton 
now, how can i enable the style ``<PUBLIC_REGISTRY_DNS_NAME>/foo/bar@id`` in filed dockerImageReference ?

**Comment by mfojtik** [comment]
There is now trello card tracking this: https://trello.com/c/BRPwto2S/896-use-service-dns-for-the-internal-registry-instead-of-ip-address

**Comment by soltysh** [comment]
@legionus @miminar I'm assigning this to you since you guys will be working on the linked card. You can probably close this when the card's PR gets merged.

**Comment by kargakis** [comment]
Closing in favor of the trello card
