### ISSUE TITLE
Hamburger menu not working for chromeless logs

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6957]
The hamburger menu doesn't open for chromeless logs at mobile screen widths.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12748649/a31a4ea6-c979-11e5-8bf3-642263f9d34e.png)

/cc @sg00dwin @jwforres

**Comment by spadgett** [comment]
Related to #6663

**Comment by benjaminapetersen** [comment]
Fix coming with [this PR](https://github.com/openshift/origin/pull/6965)
