### ISSUE TITLE
how should we create/use namespaces from the REST API when creating pods/services/RCs?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#697]
so we have a nice [Arquillian based integration testing framework](http://fabric8.io/v2/testing.html) in [fabric8](http://fabric8.io/) for running Kubernetes/OpenShift integration tests in a JUnit test (here's [an example JUnit test](https://github.com/fabric8io/fabric8/blob/master/itests/src/test/java/io/fabric8/itests/BrokerProducerConsumerIT.java#L58)  with [assertions on JMX metrics](https://github.com/fabric8io/fabric8/blob/master/itests/src/test/java/io/fabric8/itests/BrokerProducerConsumerIT.java#L74)).

Its working nicely; however really we'd like to use a separate namespace for each test case; so that each test can use services and RCs with specific IDs that can be referred to by the test case without clashing with other test cases folks are running at the same time on the same environment.

The alternative would be to remove all IDs from pods/services/controllers and just use labels (but then without IDs service wiring gets hard fast, we'd no longer be able to use environment variables etc).

So we figured using namespaces was easier; so that within different namespaces, services could use a specific ID without clashing etc.

So far we've not figured out the magic required to create/use different namespaces using the REST API. Is it even possible or is there some cunning secret way to do it ? :)

Any help greatly appreciated.

**Comment by smarterclayton** [comment]
?namespace=blah on a call.  Derek is planning on making namespaces real objects, but we still would like the create on demand model.  Namespaces are "created" as needed right now

**Comment by jstrachan** [comment]
whoah - it works! Am sure I tried that a month or so ago and it didn't work. Awesome thanks!
