### ISSUE TITLE
Mount text can overflow pod template box

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6972]
![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12758597/0fab1e84-c9ab-11e5-99ed-6b29870b59af.png)

/cc @jwforres @sg00dwin

**Comment by jwforres** [comment]
think i'd prefer to force it to wrap than hide the overflow, @spadgett opinion?

**Comment by spadgett** [comment]
+1, I think I agree about force wrapping. Even if we set a title attribute, you wouldn't be able to see the full path on mobile.
