### ISSUE TITLE
Kebab dropdown menu easy to miss on some pages

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6973]
It's easier to miss the kebab on some pages now that we've moved away from the tile style. This is particularly true of pages that don't have primary actions.

Here is an example where the menu is far from the rest of the content:

![screen shot 2016-02-02 at 12 50 25 pm](https://cloud.githubusercontent.com/assets/1167259/12758735/c7805ede-c9ab-11e5-9955-210bf97892b2.png)

/cc @jwforres @sg00dwin @ajacobs21e

**Comment by ajacobs21e** [comment]
@spadgett The recommendation from patternfly is to change this to a button labeled something like "advanced" if there is no primary action button (start build, etc). 

If there is a primary action button we'll have to see if it's better to still keep these secondary actions (edit, delete, etc) in an "advanced" dropdown button or to use the kebab.

**Comment by ajacobs21e** [comment]
Mockups showing the two options for showing the secondary menu. Patternfly's recommendation is to use an advanced (title tbd) dropdown button. 

![secondaryactions2_page_1](https://cloud.githubusercontent.com/assets/6415742/12923615/6f5d1bec-cf24-11e5-9d60-c9d89388d9a7.png)
![secondaryactions2_page_2](https://cloud.githubusercontent.com/assets/6415742/12923617/6f6c4bd0-cf24-11e5-952e-539847f472f2.png)
![secondaryactions2_page_3](https://cloud.githubusercontent.com/assets/6415742/12923618/6f6decf6-cf24-11e5-8226-0fbe5bf13b0d.png)
![secondaryactions2_page_4](https://cloud.githubusercontent.com/assets/6415742/12923616/6f6c616a-cf24-11e5-8032-bca5abfdf27d.png)
![secondaryactions2_page_5](https://cloud.githubusercontent.com/assets/6415742/12923619/6f6ed79c-cf24-11e5-955f-2dc4ec136cbe.png)

[Full wireframes](https://github.com/openshift/origin/files/123396/SecondaryActions.pdf)

**Comment by spadgett** [comment]
Would "Advanced" change to the kebab for mobile?

Some of the actions like "Delete" aren't really advanced. "Actions" maybe?

Some of the problem is positioning. In the original screenshot, having an "Advanced" button on the far right would make it easier to see, but it'd still look odd way off to the right. Adding tabs to the page for events might help.

**Comment by ajacobs21e** [comment]
@spadgett Is this how the buttons look now at mobile?
![mobilebuttons](https://cloud.githubusercontent.com/assets/6415742/13053177/15a18032-d3d1-11e5-8757-eb710718e762.png)

"Actions" is good with me. I don't see any guidance on patternfly. 

What do you mean by "adding tabs tot he page for events"?

Will we show more labels as the browser window gets wider? 
[actionbutton.pdf](https://github.com/openshift/origin/files/131079/actionbutton.pdf)

**Comment by spadgett** [comment]
>  Is this how the buttons look now at mobile?

At mobile primary and secondary actions all collapse into the dropdown. Right now it's a kebab.

<img width="432" alt="screen shot 2016-02-15 at 12 12 50 pm" src="https://cloud.githubusercontent.com/assets/1167259/13055458/760fc288-d3dd-11e5-9f0b-c0d5b3bc14de.png">

> What do you mean by "adding tabs tot he page for events"?

We're adding a new tab to the service page I pasted in the original issue description. See #7164.

> Will we show more labels as the browser window gets wider?

I don't think we do currently.

**Comment by spadgett** [comment]
For what it's worth, I like the kebab for mobile. I believe it follows the Patternfly recommendation as well. The problem is really wide pages where the kebab is far away from the content.

**Comment by ajacobs21e** [comment]
@spadgett PatternFly recommends the kebab for more actions when there's a primary action. The [design pattern](https://docs.google.com/a/redhat.com/document/d/1zDF8JoT9oDBr__KGS4uBE5X9VkMfxlFG5tPqSc1P6UU/edit?usp=sharing) has been updated to explicitly say without a primary action a dropdown button should be used. 

I talked with @rhamilto and we're recommending this design:
![dropdown_page_1](https://cloud.githubusercontent.com/assets/6415742/13061129/d433e148-d403-11e5-82b8-0d6ef4c976b6.png)
![dropdown_page_2](https://cloud.githubusercontent.com/assets/6415742/13061128/d43346f2-d403-11e5-8930-4005e20eeed5.png)
![dropdown_page_3](https://cloud.githubusercontent.com/assets/6415742/13061130/d433e0d0-d403-11e5-8990-6489ed673683.png)
![mobilesecondary](https://cloud.githubusercontent.com/assets/6415742/13060856/76927d8e-d402-11e5-905d-74178dfc6d08.png)
![mobilekebab](https://cloud.githubusercontent.com/assets/6415742/13060855/768c7af6-d402-11e5-942a-bad85220edbf.png)

Collapsing the primary action into the kebab doesn't follow patternfly and will also make the primary action less discoverable.

**Comment by spadgett** [comment]
@ajacobs21e The document you linked has collapsing buttons into the menu as an example under "2. More Actions"

> As a window gets smaller, primary actions can be moved into the more actions menu in order to conserve space.

**Comment by thesteve0** [comment]
I really dislike the kebob on the right side of the page for things like edit and delete. I think a small icon with a trash can and a pencil right next to the title would be best. This is where I am looking to carry out actions on the item. I do delete and edit quite frequently.

**Comment by ajacobs21e** [comment]
@thesteve0 are you doing "edit' or "edit YAML" frequently?

@spadgett you're totally right - I should have read through the whole doc to see what the latest version was before linking to it. That pattern is still under development and it looks like the confusion came from what's being discussed vs what's been written down at this point. Robb and I are going to chat with the designer working on that pattern to make sure we're all on the same page. I don't want to change something in OpenShift and then later PatternFly does the opposite thing. So for now no change at mobile until I can get more info. Sorry for the confusion!

**Comment by spadgett** [comment]
We talk about a max-width on some of these pages. Some fill the space and look OK, but a few look silly.

<img width="1432" alt="screen shot 2016-02-17 at 7 12 57 pm" src="https://cloud.githubusercontent.com/assets/1167259/13129396/b6164ca2-d5aa-11e5-9bb9-40a139385974.png">

**Comment by thesteve0** [comment]
Well I think edit is relatively new. If I were guessing, once we have edit
forms for each item then I will probably edit most often and edit YAML will
be the "advanced" use case
