### ISSUE TITLE
Unnecessary scrollbars on a couple pages

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6975]
Topology view:

![openshift_web_console_and__urgent__second_reminder___rh_20161018us__request_for_invention_disclosure_interview__ls_05220_2010__l2010__--_privileged_and_confidential_-_spadgett_redhat_com_-_red_hat_mail](https://cloud.githubusercontent.com/assets/1167259/12761546/633df5ae-c9b9-11e5-95eb-1cc2329d320d.png)

Browse build config:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12761552/6aec8b62-c9b9-11e5-8778-090444bd729d.png)

/cc @jwforres

**Comment by sg00dwin** [comment]
I'm looking into this...

**Comment by sg00dwin** [comment]
PR that corrects the topology view issue
https://github.com/openshift/origin/pull/7397

**Comment by spadgett** [comment]
Builds bar chart fixed in #7364.

Closing since both problems are fixed.
