### ISSUE TITLE
Refactor 'deploy' code to be server-side for reuse by all clients

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin#6980]
JBossTools is looking to add 'redeploy' functionality to the IDE which requires a java client side impl that essentially duplicates: https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/deploy.go#L208

Would like to start making this and other cli logic to a server endpoint.

**Comment by bparees** [comment]
@openshift/api-review is there any chance of this being accepted?

**Comment by smarterclayton** [comment]
Triggering a deploy?  Yes - except that we're going to want to do it based on the integration with the upstream deployment API and controllers.

**Comment by smarterclayton** [comment]
They want an imperative API?  Can we describe exactly the action they'd want to take?

**Comment by jcantrill** [comment]
@smarterclayton Not sure what you are asking here but an api that would provide:

`oc deploy DEPLOYMENTCONFIG [--latest|--retry|--cancel|--enable-triggers]`

I would expect to be able to make a REST call with something like:

`https://localhost:8443/oapi/v1/mynamespace/deploymentconfig/foo/deploy?version=latest`
or maybe:
`https://localhost:8443/oapi/v1/mynamespace/deploymentconfig/foo/deploy?cancel=true`

and its logic is the same as our CLI and provides the same outcome

**Comment by kargakis** [comment]
--latest runs on the server now, --retry and --cancel need to be discussed upstream as part of the more general discussion around custom deployments. --enable-triggers won't end up in the server anytime soon (although I am entertaining the idea of a Trigger as a TPR but that won't happen anytime soon too).
