### ISSUE TITLE
Web console: Log keeps following on manual scroll

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6985]
Previously, if you scrolled the window manually, the web console stopped following the log. It no longer does this.

/cc @jwforres @benjaminapetersen @sg00dwin

**Comment by benjaminapetersen** [comment]
Yup, the handler is on window only, so it works for mobile but otherwise the function doesn't run since we now have the div/window swap.  Updating.

**Comment by benjaminapetersen** [comment]
Planning on addressing this as well in [this PR](https://github.com/openshift/origin/pull/6965)
