### ISSUE TITLE
Hostsubnets not created after installation - problem with hardcoded network variables in Openstack integration

### ISSUE THREAD

**Issue by AlbertoPeon** [openshift/origin#6989]
We are seeing problems with the OpenStack integration. In a nutshell, the network variables contains hardcoded settings that doesn't fit all installations (including ours). More details in https://github.com/openshift/openshift-ansible/issues/1261.

This issue appears to be solved in upstream Kubernetes https://github.com/kubernetes/kubernetes/pull/18829, so I guess it's just a matter of time before it comes to Origin :)

Do you have an estimation of when it will happen? I'm happy to help to make as soon as possible.

Thanks,
Alberto

**Comment by eparis** [comment]
Did you link to the correct openshift issue? That doesn't seem related...

**Comment by AlbertoPeon** [comment]
No, I did not :)

This is the right one - https://github.com/openshift/openshift-ansible/issues/1261
I've also edited the original post.

**Comment by AlbertoPeon** [comment]
This issue is not present anymore on 1.1.4
