### ISSUE TITLE
delete-link, edit-link mix up kind and resource

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6990]
Applies to all pages, but one example:

Edit link has `kind="services"`, etc. Kind should be upper-case, match the value in the API object (`kind: "Service"`, etc), and be transformed using `kindToResource` before passing to the data service.

Delete link has `resource-type="service"`, which then has an 's' appended to it (`DataService.delete(resourceType + 's', resourceName, context)`). Should probably be using `kind=Service` and `kindToResource` as well.

**Comment by spadgett** [comment]
The `log-viewer` directive does this as well.

**Comment by jwforres** [comment]
hasn't bit us yet but only a matter of time

**Comment by liggitt** [comment]
especially with the `+'s'` bit... anything that ends in `s` or `y` would be wrong

**Comment by benjaminapetersen** [comment]
So summarized, we need to update all instances of the following directives:
- [ ] delete-link
- [ ] edit-link
- [ ] log-viewer

Have we blurred this anywhere else?

**Comment by benjaminapetersen** [comment]
Was looking into this one, but touches a lot of files (pages, modals, etc).  Feels risky at this point.

**Comment by spadgett** [comment]
Need to update the `humanizeResourceType` filter as well (filters/resources.js).
