### ISSUE TITLE
Improve new-app output when processing invalid template JSON

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6991]
Today, if a template contains invalid JSON (perhaps because of a typo), `oc new-app` outputs the error followed by a verbose message about how new-app works:

``` console
$ echo "{broken:}" > template.json
$ oc new-app template.json 
error: unable to load template file "template.json": invalid character 'b' looking for beginning of object key string
error: no match for "template.json"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
```

Unless you know what you're looking for, it is very easy to miss the error message when confronted with 10+ lines of text.
## Proposal

The output should contain only the parsing error, or at least have it as the last bit of information (which is closer to the cursor and more likely to be seen).

``` console
$ echo "{broken:}" > template.json
$ oc new-app template.json 
error: unable to load template file "template.json": invalid character 'b' looking for beginning of object key string
```
## Implementation

To make the proposal possible, we need to make the new-app template file resolver have top weight, which means a local file will _always_ take precedence over any image from anywhere, but only when the search term matches a local file or URL with the `.yaml`, `.yml` or `.json` extension.

IOW, `"php.json"` can be weighted above everything else, `"php"` can't.

---

From https://github.com/openshift/origin/pull/6670#discussion_r51588896

**Comment by rhcarvalho** [comment]
@bparees @smarterclayton FYI

**Comment by smarterclayton** [comment]
So basically fork TemplateFileResolver to be separate, make sure it doesn't hit the server, and have it require certain extension types.  Makes sense to me.  Bonus points if we print out the line number the error happened on for both JSON and YAML

**Comment by bparees** [comment]
Sounds ok to me, but is the error handling framework setup to be able to stop searching after an error from TemplateFileResolver, even if it comes first?  I thought we're aggregating all the errors from all the resolvers now.

and not printing the "no matches" message is also going to go against the new error handling model.  After @smarterclayton just made it sane, i'm a little reluctant to reintroduce special casing, so this needs to be done in a generic way.

**Comment by smarterclayton** [comment]
We could conceivably have generic errors in a full weight group stop
processing.  If we put templatefileresolver first, and it unambiguously
could say "i found something and it is broken", then we could at least know
to stop traversing to lower weight groups.

**Comment by bparees** [comment]
yes that's the sort of generic solution i was thinking of...  a class of error that results in stopping and not processing additional resolvers.

**Comment by rhcarvalho** [comment]
I remember seeing maybe under docs/ or proposals/ some old design notes
about new-app.
Just throwing the question out in the wild to avoid spending too much time
trying to learn the current implementation without help, do we have any
explanation somewhere about how searchers and resolvers and the error flow
should work?

**Comment by bparees** [comment]
@rhcarvalho unfortunately i think your best hope is the code.

**Comment by bparees** [comment]
converted to trello https://trello.com/c/6SplXFKk
