### ISSUE TITLE
Topographic view is missing legend

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#6997]
Topographic view in the web console is missing legend for the resource icons. @thesteve0 @stefwalter

**Comment by jwforres** [comment]
Someone else brought this up this morning, we should really add it somewhere, we already have descriptions in the details sidebar, we could just add icons next to those.

**Comment by jhadvig** [comment]
You mean into the sidebar or next to it ?

**Comment by jwforres** [comment]
into the sidebar

**Comment by jwforres** [comment]
although would need to see how it looked

**Comment by benjaminapetersen** [comment]
Quick and dirty, thinking something like this?

![topography_legend](https://cloud.githubusercontent.com/assets/280512/13265565/93a097b8-da41-11e5-869c-36c162b42160.png)

**Comment by jwforres** [comment]
hmm, so the problem with doing it in the sidebar is that as soon as you
click on an item, you lose the legend

**Comment by liggitt** [comment]
Once you select one, don't you have the type in the details pane anyway? Is it possible to deselect something and get back to the legend?

**Comment by jwforres** [comment]
No you can't de-select, we've had an issue open for that for awhile.  If we
fixed that, this would be fine.

**Comment by stefwalter** [comment]
> No you can't de-select, we've had an issue open for that for awhile.  If we
fixed that, this would be fine.

You can deselect. Just click on none of the items.

**Comment by jhadvig** [comment]
Maybe put the under the filter ? So its still visible. And just put to each icon the name - pod, deployment, rc, ...

**Comment by spadgett** [comment]
Or along the bottom like the screenshot here: https://github.com/kubernetes-ui/topology-graph

**Comment by jhadvig** [comment]
@spadgett +1

**Comment by benjaminapetersen** [comment]
I'm good with it on the bottom as long as it is relatively easy to find.  Across the top could work as well.

**Comment by jwforres** [comment]
actually im going to close this, having a legend is a requirement as part of this card https://trello.com/c/6s7TGjr3
