### ISSUE TITLE
`hack/test-cmd.sh` fails when bad regex is given 

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#7004]
For example:
```
$ hack/test-cmd.sh sdfkjsdf
!!! Error in hack/test-cmd.sh:57
	'tests=($(find_tests ${1:-.*}))' exited with status 1
Call stack:
	1: hack/test-cmd.sh:57 main(...)
Exiting with status 1
```

If the API we have is "give us a regex and we run any matching buckets" this type of input should result in no buckets being run, but not this failure.

**Comment by stevekuznetsov** [comment]
@enj the above is why you don't reference issues in commit messages :)

**Comment by enj** [comment]
@stevekuznetsov I prefer the message spam vs. having no idea why a commit happened :smile:

**Comment by liggitt** [comment]
> @stevekuznetsov I prefer the message spam vs. having no idea why a commit happened 😄

You may be the only one, and it'll only get worse as more people update their own master branches. Also, that's a false choice, there's better ways to indicate why a commit happened.
