### ISSUE TITLE
Several issues with show annotations link in browse pages

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#7005]
When it shows up right before a table there is no margin now that the tiles are gone.

![show_annotations](https://cloud.githubusercontent.com/assets/1467629/12789788/485b29be-ca6d-11e5-8e9e-92a70cf6b6ae.png)

Deployment config is completely missing annotations.

Build config has it under the Configuration tab which is not the first tab, are annotations really configuration?

**Comment by jwforres** [comment]
@spadgett fyi

**Comment by spadgett** [comment]
No bottom margin when it's the last thing on the page as well.

![openshift_web_console_and_openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12790822/338c1a98-ca72-11e5-9271-e5e4b71ff769.png)

**Comment by jwforres** [comment]
@ajacobs21e before the re-design this link was always hanging out at the bottom of the white tile area, so it was visually separated from the table beneath the tile.  now that we don't have the tile it feels strange in its current location.  We don't feel like its worthy of its own tab, because annotations are not really intended for end users (we try to push labels for end users to use) but it is possible for them to modify annotations from the CLI or from the console's raw editor... so it still needs a home *somewhere* on the browse pages.  For reference, clicking show annotations makes a big table visible.

**Comment by ajacobs21e** [comment]
@jwforres What do you think about how the link is presented in these wireframes? https://drive.google.com/open?id=0BxppHkjprXoJSk5yWHpVODk4b00

**Comment by ajacobs21e** [comment]
Another option is to put the link in the advanced dropdown menu:
<img width="816" alt="screen shot 2016-02-14 at 3 46 53 pm" src="https://cloud.githubusercontent.com/assets/6415742/13036348/1ad620c4-d333-11e5-9cda-f9a6acf04b34.png">

**Comment by jwforres** [comment]
Yeah i think for now we will just be adding some padding beneath the Show annotations link so its not sitting right next to the table, which is what was in your wireframes.

View Annotations in the Actions menu feels a little weird

**Comment by benjaminapetersen** [comment]
> Build config has it under the Configuration tab which is not the first tab, are annotations really configuration?

Good Q here. 
- Deployments have Configuration under Details tab
- Builds have a Configuration tab that is pretty similar to the Deployment Details tab
- Builds have a Summary tab that is quite similar to the Deployments Details tab
- Should the Environment tab consistently be the 2nd tab?

I think we can sort out the Details, Summary & Configuration tabs, possibly eliminate one, then put annotations under what makes sense.  The Build chart is the key difference on these pages, but we could tweak the Deployments page to improve consistency.

I tend to think "Summary" is the better tab name, implying "the big picture".  "Details" is kind of a catch all word, but we can sort the details under the specific tabs.

Side-by-side screenshot for reference:

![screen shot 2016-02-18 at 3 03 57 pm](https://cloud.githubusercontent.com/assets/280512/13156546/ffae96c0-d650-11e5-82a8-777d7fde4283.png)

**Comment by benjaminapetersen** [comment]
I think this tab set makes sense to me:

- Summary
    - Build config will have the chart + list of builds
    - Deployment config page will have just the list of deployments since we have no chart right now.
- Details
    - Rename "configuration" since this tab also has a sub-heading of "configuration" which is redundant.
- Environment
    - Both have this tab
- Events
    - Only deployments has this tab

Then I can add the annotations directive under the Summary tab above the list of builds/deployments. 

Thoughts?

**Comment by benjaminapetersen** [comment]
Ok, moved the tab stuff to a separate issue.  On this issue will open a PR to address the following:
- [x] padding around `<annotations>` directive
- [ ] missing `<annotations>` directive on deploymentConfig page

**Comment by benjaminapetersen** [comment]
So deploymentConfig actually already has the annotations directive:

![screen shot 2016-02-18 at 4 56 34 pm](https://cloud.githubusercontent.com/assets/280512/13159625/d3c8b972-d660-11e5-86c7-9d89fc3e7fad.png)

Though my deploymentConfig object had no annotations & I had to fake it out to get the annotations directive to appear.  The directive is on all the build, buildConfig, deployment, deploymentConfig, & pod pages.

**Comment by jwforres** [comment]
Ahh right we hide when there aren't any.

**Comment by benjaminapetersen** [comment]
Aha!  We are tricky.  :smile:

Made this a pretty easy fix.

**Comment by benjaminapetersen** [comment]
I could add a "no annotations" message if there are none, rather than
showing nothing. Thoughts?

**Comment by spadgett** [comment]
#7442 is merged, which fixes the layout problem, and we have #7440 to track the tabs.

**Comment by ajacobs21e** [comment]
@benjaminapetersen would the user that is looking for annotations know ahead of time whether or not there are annotations or not?

**Comment by spadgett** [comment]
@ajacobs21e Not necessarily. I think we should probably say "No annotations" if there are none.

**Comment by benjaminapetersen** [comment]
Agree, I can open a new issue for that & get it done quick.  Won't take much.
