### ISSUE TITLE
After logging in using a serviceaccount token, logout is impossible

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#7011]
Example:

``` sh
$ oc new-project my-project
Now using project "my-project" on server "https://10.13.137.174:8443".
$ oc sa new my-sa
serviceaccount/my-sa
$ oc login --token="$( oc sa get-token my-sa )"
Logged into "https://10.13.137.174:8443" as "system:serviceaccount:my-project:my-sa" using the token provided.
$ oc logout
Error from server: oauthaccesstokens "<snip>" not found
$ oc whoami
system:serviceaccount:my-project:my-sa
```

@deads2k @liggitt

**Comment by deads2k** [comment]
Ok, you can't delete it and we should let you know, but logout should update the local kubeconfig.

Also, I think examples should use `oc get user/~ --token=<>`

**Comment by stevekuznetsov** [comment]
Updated tests to use `oc get user/~`. 

You're saying that the error we see is from [this](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/logout.go#L125) attempted `Delete`? Should we try to ascertain when we are and are not supposed to be deleting the token?

**Comment by deads2k** [comment]
> You're saying that the error we see is from this attempted Delete? Should we try to ascertain when we are and are not supposed to be deleting the token?

Tokens are opaque.

**Comment by liggitt** [comment]
opened https://bugzilla.redhat.com/show_bug.cgi?id=1422252
