### ISSUE TITLE
Create from image page changes background color at bottom

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7016]
This page has a gray background, but the bottom of the page is white. There is quite a lot of bottom padding here, too.

To reproduce

1. Click add to project
1. Pick a builder image
1. Click the advanced options link

I believe this only happens at mobile widths.

![openshift_web_console_and__origin__force_mount_path_to_word_break_so_it_works_at_mobile___7009__-_spadgett_redhat_com_-_red_hat_mail](https://cloud.githubusercontent.com/assets/1167259/12798308/b143da6a-ca96-11e5-98e6-ceb3b798ce93.png)

/cc @jwforres @sg00dwin

**Comment by spadgett** [comment]
Happens on the create route page as well.

<img width="787" alt="openshift_web_console_and_mozilla_firefox_start_page" src="https://cloud.githubusercontent.com/assets/1167259/12821667/50b7b7a6-cb32-11e5-8218-7ffea240f9ef.png">

**Comment by sg00dwin** [comment]
I'm currently looking into this...

**Comment by spadgett** [comment]
Fixed by #7349
