### ISSUE TITLE
Latest 'oc' breaks headless services

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#7017]
The latest oc command breaks headless services, while older oc commands can still create headless services without issue (eg `portalIp: None`)

**Note**: the following example is running on the exact same OpenShift instance (built from master), the only difference is the `oc` command used.

With the latest version:
```
$ oc version
oc v1.1.1-389-gbe9c564
kubernetes v1.2.0-alpha.4-851-g4a65fa1
$ oc process -f testrc.yaml | oc create -f -
$ oc get -o yaml service test
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-02-03T22:09:17Z
  labels:
    name: test
  name: test
  namespace: test-1454535557
  resourceVersion: "4468"
  selfLink: /api/v1/namespaces/test-1454535557/services/test
  uid: c45b5139-cac2-11e5-8398-3c970e88a56f
spec:
  clusterIP: 172.30.58.20
  portalIP: 172.30.58.20
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```

With an older version:
````
$ oc version
oc v3.1.0.4-5-gebe80f5
kubernetes v1.1.0-origin-1107-g4c8e6f4
$ oc process -f testrc.yaml | oc create -f -
$oc get -o yaml service test
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-02-03T22:04:13Z
  labels:
    name: test
  name: test
  namespace: test-1454535557
  resourceVersion: "4415"
  selfLink: /api/v1/namespaces/test-1454535557/services/test
  uid: 0f74b989-cac2-11e5-8398-3c970e88a56f
spec:
  clusterIP: None
  portalIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
````

**Note**: There are also more recent changes where the yaml/json for the service needs to be modified with the latest `oc` while it it still acceptable to use with the older version.
[testrc_yaml.txt](https://github.com/openshift/origin/files/116499/testrc_yaml.txt)

**Comment by liggitt** [comment]
likely happened at the last rebase boundary

**Comment by smarterclayton** [comment]
You have a typo in tester_yaml.txt - should be `portalIP`, not `portalIp`

**Comment by smarterclayton** [comment]
Not sure how this ever worked.

**Comment by liggitt** [comment]
ugorji is stricter about case when ummarshaling, that could be it

**Comment by liggitt** [comment]
The other changes I know of were typos like "Kind" and "Name" working previously, and now needing to be "name" and "kind". Are there changes other than case-sensitivity that you've noticed?

**Comment by mwringe** [comment]
Is there any way to have the oc command check things like this and output an error message? I suspect this may cause a lot of issues when people update to a newer version and the system now starts to silently ignore certain options.

**Comment by liggitt** [comment]
Not a good way, no.

**Comment by liggitt** [comment]
To be clear, all doc and all API returned objects had the correct attribute names. It was really a bug that incorrect case was accepted.

**Comment by pweil-** [comment]
@liggitt - is there anything we can do here then?  It sounds like there isn't.  Maybe this warrants a note in the upgrade.MD?

**Comment by liggitt** [comment]
Correct, just doc

**Comment by smarterclayton** [comment]
Please make sure it makes it into the release notes and I'll add it to the
1.1.2 release notes.
