### ISSUE TITLE
Need SCC for hostnetwork for router to use

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7021]
We shouldn't be reusing the other ones.

**Comment by adelton** [comment]
@smarterclayton, could you please elaborate. There is `hostnetwork` SCC there, added via https://github.com/openshift/origin/pull/7485 for https://github.com/openshift/origin/issues/7249. Is there anything else needed or can this issue be closed?

**Comment by adelton** [comment]
@pweil-, is there anything that is needed or can this issue be closed?

**Comment by pweil-** [comment]
I think we're good here unless someone has a reason we shouldn't use `hostnetwork` and prefer a `router` SCC.  I don't think that's a requirement at this point.
