### ISSUE TITLE
Cherry-pick validation on non-namespaced resources

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7022]
https://github.com/kubernetes/kubernetes/pull/16146 fixes it, but we have reports its clogging logs and blocking events.  But if we have to cherry-pick an upstream before the rebase... @deads2k your call but I think I'm just going to cut 1.1.2 without this.

**Comment by deads2k** [comment]
The pick wasn't perfectly clean, but lets see if #7027 resolves our problem.
