### ISSUE TITLE
Feature request: --logfile for origin master/node

### ISSUE THREAD

**Issue by mrosic** [openshift/origin#7026]
We would like to be able to write the logs into a separate log file and not into /var/log/messages. 
This would enable us to have detailed logging (for example log level 4) without completely spamming /var/log/messages and systemd-journald

At the moment the only way seems to be to create an rsyslog filter which is not a nice solution since that puts even more load on rsyslogd.

**Comment by brenton** [comment]
I don't think this will be prioritized.  Our focus is on improving systemd support.
