### ISSUE TITLE
Web console: Image stream tags table has no empty message

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7030]
When there are no tags for an image stream, the table is empty with no message.

<img width="712" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/12821817/1edbef76-cb33-11e5-904b-7a3c5b3ef1ba.png">

/cc @jwforres

**Comment by jwforres** [comment]
yep i already have a fix for this in my loading messages PR actually.
