### ISSUE TITLE
Namespace/Project leftovers

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#7032]
For some time we have known namespaces leaves a directory structure under a resource objects it creates.  In openshift this is 1:1 with projects.  So as projects come and go there is a lot of leftover directories in etcd.  O(10^3)   

We'll run a quick experiment to determine the space consumed by leftovers. 

/cc @abhgupta @derekwaynecarr @jeremyeder

**Comment by derekwaynecarr** [comment]
The etcd leftover is a one directory per namespaced kind that existed in the namespace.

**Comment by timothysc** [comment]
A simple risk mitigation could be a cron util to periodically cleanup.

**Comment by abhgupta** [comment]
I have asked @jawnsy to run the quick experiment to assess the extent of the issue from a etcd memory perspective.

**Comment by jawnsy** [comment]
I did a test with @tiwillia and it seems that the difference in memory usage is about 10MB for 1,000 users. Our test was simplistic so may not be realistic of a true usage scenario.

OpenShift not running:

````
              total        used        free      shared  buff/cache   available
Mem:          31757         583       29521         304        1653       30548
Swap:             0           0           0
````

OpenShift started up, after 1,000 projects were created and deleted. There is some leftover folders in etcd at this point.

````
              total        used        free      shared  buff/cache   available
Mem:          31757         699       29404         304        1653       30431
Swap:             0           0           0
````

Cleared etcd directory, this is the baseline for an empty system:

````
              total        used        free      shared  buff/cache   available
Mem:          31757         678       29783         304        1295       30454
Swap:             0           0           0
````

I'm working on a script to prune these empty directories.

**Comment by abhgupta** [comment]
@jawnsy The next step for us would be to come up with some command that we can execute to clear off these directories. This command (REST API call, CLI, curl, whatever makes sense) could be invoked by @ironcladlou as part of his reconciler. Please sync up with him on what sort of a command would make the most sense for him.

**Comment by abhgupta** [comment]
I realize that we will need a more generic solution for the mid/long term, but just wanted to capture the workarounds for the immediate term.

**Comment by abhgupta** [comment]
@jawnsy can you mention the updated test results (based on modifications in monitoring mentioned by @derekwaynecarr) for memory consumption?

**Comment by jawnsy** [comment]
Updated figures using @derekwaynecarr's [awesome scripts](https://github.com/derekwaynecarr/etcd-test), slightly modified to produce empty directories.

Number of empty directories | Size (kB)
------------------------------------|-------------
0 | 12660
100000 | 213152
200000 | 356460
300000 | 638100
300000 | 254992

**Comment by abhgupta** [comment]
Just for some context:
```
Average directories per user: 20
Number of users per 100,000 directories: 5000
```

**Comment by derekwaynecarr** [comment]
There is an upstream add-on pod that you can run and point at etcd that deletes empty directories from upstream:  https://github.com/kubernetes/kubernetes/pull/30319

I do not anticipate any actual code going into the main-line code path, but will leave it up to @abhgupta to evaluate using the referenced script.

**Comment by timothysc** [comment]
We plan on nuking this for 1.5 now that etcd3 is incorporated.

**Comment by derekwaynecarr** [comment]
@timothysc - that too, the issue does not impact etcd3
