### ISSUE TITLE
`oc status` should identify objects with namespace, kind, and name

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#7033]
For instance, when a build can't start because of a missing image stream, I should know that _a)_ and image stream is missing, _b)_ what that image stream's name is (and the tag), _c)_ it's namespace. Currently we lack the namespace info.

/cc @bparees

**Comment by liggitt** [comment]
The namespace should only be included if it's different than the current one, to avoid unnecessary clutter

**Comment by fabianofranz** [comment]
cc @deads2k

**Comment by kargakis** [comment]
Agreed with @liggitt 

Note that we are filtering cross-namespace links on purpose at the moment but we should change it at some point (I would like oc status by default to inform me about involved objects in adjacent namespaces). We shouldn't show any involved markers from other namespaces though I think

**Comment by stevekuznetsov** [comment]
@juanvallejo did you work on this?

**Comment by juanvallejo** [comment]
@stevekuznetsov I have not worked on this, but have a [similar bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1258354) where a user can enter an invalid value for `oc run ... --image` and not be aware of any `ImagePullBackOff` errors until they look at `oc get all` or `oc get pods`
