### ISSUE TITLE
Project select 'display name' flickers if their are multiple projects, when switching views.

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#7035]
Initially the project  'name' is shown and switches to a 'display name' if it exists.

**Comment by spadgett** [comment]
As an optimization, we should the project name before the project response comes back. This causes flicker if there's a display name the select switches to.

We might need to some project data like display name to avoid the flicker.

**Comment by benjaminapetersen** [comment]
Might need to...?  Betting that comment was to cache the display names?

**Comment by spadgett** [comment]
Yeah, might need to cache.
