### ISSUE TITLE
 Convert table list views to the new patternfly item list view design

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#7036]
Patternfly list markup and styles
http://rawgit.com/patternfly/patternfly/master/tests/list-view.html

**Comment by rhamilto** [comment]
One thing that has come up in discussion with @ajacobs21e while reviewing the existing tables is that data lists lack column headers, so using them as a wholesale replacement for tables doesn't necessarily make the most sense as most of OpenShift's tables need column headers.  That said, we've discussed finding a middle ground that incorporates the styling of data lists but maintains the column headers.  We need to follow up with the PatternFly team to discuss.

**Comment by jwforres** [comment]
Closing this issue, its a fairly significant effort for us to go do, it will be done as a story if we decide to ever do it.
