### ISSUE TITLE
IE11 in Intranet/Compatibility Mode is Served JSON Instead of HTML

### ISSUE THREAD

**Issue by cpitman** [openshift/origin#7038]
IE11, by default, serves any "intranet" sites using it's compatibility mode. This changes the `Accept` header sent in a request to `application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, ​/`. When this happens, openshift responds back with json instead of html. 

The workaround is to disable compatibility mode for intranet sites, but this will not work for users who have *other* intranet sites that require compatibility mode.

Can Openshift detect these accept headers, and then respond back with HTML?

**Comment by liggitt** [comment]
IE is saying it doesn't accept html?

**Comment by cpitman** [comment]
That above header is exactly what I get (according to the developer tools) when I force it into compatibility mode, and it matches symptoms we've had at two sites now where openshift was deployed on an intranet and users couldn't hit the console with IE.

**Comment by liggitt** [comment]
That's… unbelievable :(

**Comment by liggitt** [comment]
@jwforres the least awful things I can think of:
1. additionally display html instead of json if the user-agent looks like a browser (starts with "Mozilla/" or something)
2. flip the condition and only display json if the Accept header specifically asks for it

**Comment by jwforres** [comment]
@smarterclayton do you have an opinion here, since you chose the original conditions for when we would return json vs redirect to the console

**Comment by smarterclayton** [comment]
It says it accepts `/`, or `*/*`?

**Comment by smarterclayton** [comment]
I would put a specific conditional in for "if you didn't ask for HTML, didn't ask for JSON, but did ask for application/msword and your user agent looks like Mozilla then also send you to HTML"

**Comment by jwforres** [comment]
Complete with snarky comments in the code for why we are doing it...

**Comment by cpitman** [comment]
I'm pretty sure it says it accepts `/`, that should be a straight copy/paste from the dev tools. When not in compatibility mode it explicitly says it supports '*/*'.

If it would help I can repeat and get a dump of all the headers in the request.

**Comment by smarterclayton** [comment]
The idea of returning a powerpoint deck describing the values of openshift
is going to haunt me for a long time.

On Fri, Feb 5, 2016 at 10:16 AM, Jessica Forrester <notifications@github.com

**Comment by jwforres** [comment]
Tested on an instance that doesn't have the other ms apps installed, the accept header it sends is only `*/*` but the user agent does contain Mozilla

**Comment by liggitt** [comment]
according to microsoft docs, the user agent string always starts with Mozilla, both in compatibility mode and standards mode:
https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us/library/bg182625%28v=vs.85%29.aspx#uaString
https://msdn.microsoft.com/en-us/library/ms537503%28v=vs.85%29.aspx#UnderstandUA
