### ISSUE TITLE
Daemonset doesn't default selector correctly

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#7041]
As documented at https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L412-L415, selector should default to template labels. This isn't working in origin master as daemonsets conversions are missing & hence no defaulting funcs are run. I think this is fixed in kubernetes/kubernetes@bd3b476b, had a go at cherry-picking this in but a lot of other changes to files that may/may not be required & I'm not 100% sure which are/aren't required.

As discussed with @pweil- & @smarterclayton on IRC.

**Comment by pweil-** [comment]
changes were picked up in the rebase that just landed.  I'll give this a test to make sure that the labels are defaulting now.

**Comment by pweil-** [comment]
Tested on master by creating a DS with no selector label and labels on the pod template.  Confirmed that the selector on the DS was defaulted to 

```
"selector": {
            "matchLabels": {
                "name": "hello-daemonset"
            }
        },
```
