### ISSUE TITLE
switch to previous project

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7044]
Add a command to oc in order to switch quickly to a previous project, in the spirit of commands like `cd -` or `git checkout -`.

I would suggest `oc project -`.

**Comment by liggitt** [comment]
Not sure I want to keep track of multiple levels of project state required to know the previous project

**Comment by YannMoisan** [comment]
It is in the ~/.kube/config file, isn't it ?

**Comment by liggitt** [comment]
all projects visited are, not a record of which was previous
