### ISSUE TITLE
small improvements for oc deploy

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7045]
- for a project with only one dc, the dc could be optional for command `oc deploy`
- after `oc deploy <dc> --latest`, we could suggest to run `oc logs dc/<dc>` to get information on the deployment.

**Comment by kargakis** [comment]
> after oc deploy <dc> --latest, we could suggest to run oc logs dc/<dc> to get information on the deployment.

@smarterclayton you mentioned something about `oc deploy --follow`. Do we want that?

**Comment by smarterclayton** [comment]
Kind of.  If it's easy (basically what oc dc/logs -f does but only on the
deploy that we just kicked off)

**Comment by smarterclayton** [comment]
Also, we can't fail due to a timeout error - it literally has to run
forever.

**Comment by kargakis** [comment]
> Also, we can't fail due to a timeout error - it literally has to run forever.

Timeout needs to be configurable for oc logs (see https://github.com/openshift/origin/issues/5584#issuecomment-160951829).

**Comment by kargakis** [comment]
> for a project with only one dc, the dc could be optional for command oc deploy

@smarterclayton what do you think about this?

**Comment by smarterclayton** [comment]
I'd prefer not, I want to reserve that for implicit git repository
arguments (or until we close on that).  That would be a step that
connects a Git repo locally to a bc and DC - a few commands would then
fall back to that if no args provided.
