### ISSUE TITLE
label deletion of all namespaces (openshift & openshift-infra) - cluster inoperable restart required. 

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#7048]
So I was automating some project deletion tests and I fat fingered my cluster to inoperable, where the only recovery was master restart.  

```
oc label --overwrite namespace --all purpose=testing
oc delete projects -l purpose=testing
```

Once that was done, further tests appeared as if they were executing, but on inspection, 0 pods were running. 

In hindsight it was silly, but it doesn't appear that the openshift and openshift-infra namespaces auto recover like 'default'. 

xref: #3274

/cc @jeremyeder

**Comment by liggitt** [comment]
correct.

**Comment by timothysc** [comment]
I guess the point is, system services/namespaces etc should be recoverable from operator error.

**Comment by liggitt** [comment]
same issue as #3274
