### ISSUE TITLE
access .git during the build

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7050]
When I build from a Git Repository Source, the `.git` folder is not available.

But my build process need it to generate some info at build time, using command like `git describe`.

The main use case is to retrieve the commit id.

**Comment by rhcarvalho** [comment]
@YannMoisan what build strategy are you using?

**Comment by YannMoisan** [comment]
@rhcarvalho docker

**Comment by rhcarvalho** [comment]
@YannMoisan one of the last steps of the build will insert in the image some metadata:

```
Step 12 : ENV "OPENSHIFT_BUILD_NAME" "ruby-sample-build-2" "OPENSHIFT_BUILD_NAMESPACE" "demo" "OPENSHIFT_BUILD_SOURCE" "git://github.com/openshift/ruby-hello-world.git" "OPENSHIFT_BUILD_COMMIT" "00cadc392d39d5ef9117cbc8a31db0889eedd442"
```

This includes the `OPENSHIFT_BUILD_COMMIT`, does that help you in your use case?
If not, please tell us more about what you're trying to achieve.

The example above is the result of:

```console
$ oc new-app https://raw.githubusercontent.com/openshift/origin/master/examples/sample-app/application-template-dockerbuild.json
$ oc logs -f bc/ruby-sample-build
```

**Comment by YannMoisan** [comment]
Unfortunately, I need this information at the beginning of the build. My build (sbt) uses a plugin [sbt-git](https://github.com/sbt/sbt-git) that run git commands.

This extra step can be the starting point of a workaround.

**Comment by rhcarvalho** [comment]
@YannMoisan for the time being, one workaround would be to `git clone` you repository (again) as part of the build.
Add to your Dockerfile a line that clones the repo and builds from there.

A more elaborate workaround would be to use a Custom Builder image. Here's an example of one that does a Docker build:
https://github.com/openshift/origin/blob/master/images/builder/docker/custom-docker-builder/build.sh

I've discussed a longer term solution with other developers, and we're looking for a better solution. You can track progress via https://trello.com/c/C1gwxci3/856-include-git-repository-during-build.

AFAICT one of the reasons we originally opted for not including the `.git` directory in the build context (for Docker and S2I strategies) was to keep the image size under control. However, for Docker builds it really makes no difference as to final image size whether `.git` was in the context or not.
We might change Docker strategy builds to include it in the future.

**Comment by rhcarvalho** [comment]
BTW, please let me know how would the workarounds work for you.

**Comment by rhcarvalho** [comment]
Closing due to age. Improvements can be tracked in Trello: https://trello.com/c/C1gwxci3/856-include-git-repository-during-build

**Comment by dustymabe** [comment]
Hit this over the weekend - would like access to the .git directory so I can use that information during by docker strategy build.

**Comment by dsutherland1492** [comment]
I'm having this same issue, was a fix ever created for this?

**Comment by bparees** [comment]
I believe we are still stripping the .git folder out automatically currently.  There was some discussion about introducing an api to allow overriding of this behavior, or controlling the filtering in general, but i don't think it went anywhere.  @adambkaplan may be able to dig up the RFE from our backlog (unfortunately our backlog is in jira which is not yet public..hopefully soon).

**Comment by adambkaplan** [comment]
@dustymabe we have the RFE in JIRA - https://jira.coreos.com/browse/DEVEXP-69

This was imported from Trello from here, and hasn't changed since. For folks who can't access our JIRA, link to archived Trello card: https://trello.com/c/C1gwxci3
