### ISSUE TITLE
NAME should be optional with oc get isimage

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7058]
The command `oc get isimage` doesn't work if you don't specified a `NAME`.

In order to be consistent with other commands and the doc, the name should be optional.

**Comment by deads2k** [comment]
@smarterclayton how do you feel about the fanout?

**Comment by smarterclayton** [comment]
I want to do this, but I want to fix up imagestreamtags to solve the other problems it has first.  Agree this should be next.

**Comment by bparees** [comment]
trello'd https://trello.com/c/ZaluQBiF
