### ISSUE TITLE
false negative warnings

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7060]
`oc status -v` displays this warning :

```
rc/xxx is attempting to mount a secret secret/production-secret disallowed by sa/default
```

Regarding a change in [1.0.5.](https://github.com/openshift/origin/releases/tag/v1.0.5) related to security, the service account configuration is not required anymore.

**Comment by liggitt** [comment]
Fixed in https://github.com/openshift/origin/pull/6735
