### ISSUE TITLE
Horizontal Pod Autoscaler REST API

### ISSUE THREAD

**Issue by charliemaiors** [openshift/origin#7061]
Hi,

is possible to instantiate a Horizontal Pod autoscaler from the Openshift Origin REST API (Openshift Version 1.1.1.1)? If is possible which is the path to perform the request? on /api/v1beta1/namespace/<namespace>/horizontalpodautoscalers/ the user who own the <namespace> can't list (I've tried with a GET) this kind of objects.

**Comment by liggitt** [comment]
`/apis/extensions/v1beta1/namespaces/<foo>/horizontalpodautoscalers`

**Comment by liggitt** [comment]
HPA objects are in a new API group - extensions

**Comment by charliemaiors** [comment]
Can you please link the documentation to that object?

**Comment by kargakis** [comment]
https://docs.openshift.org/latest/dev_guide/pod_autoscaling.html
https://github.com/kubernetes/kubernetes/blob/175d0c57f2387774477ad581d14835f4a9d1a456/docs/design/horizontal-pod-autoscaler.md#horizontal-pod-autoscaling

**Comment by charliemaiors** [comment]
if I define a number of replicas in deploymentconfig, could I set that number as maximum replicas number in hpa and set the minimum number to 1?

**Comment by kargakis** [comment]
Whatever is the initial size of your deployment config, will be autoscaled based on the range you will provide with min-max.

**Comment by charliemaiors** [comment]
Perfect thank you

**Comment by kargakis** [comment]
Also note that `oc autoscale` in the command line tool is coming very soon.
https://github.com/openshift/origin/pull/6861
You will be able to setup an hpa just by pointing the dc you want autoscaled to `oc autoscale`:
```
$ oc autoscale dc/foo --min=2 --max=10
```
