### ISSUE TITLE
Projects dropdown doesn't update immediately after editing project display name

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7067]
The selected project name in the projects dropdown doesn't update when saving display name edits on the settings page. (It will update when leaving the settings page, however.)

/cc @jwforres @benjaminapetersen

**Comment by benjaminapetersen** [comment]
This looks like a job for a nice simple pub-sub module!  
([suggested in this PR](https://github.com/openshift/origin/pull/6187))

**Comment by benjaminapetersen** [comment]
A fairly simple fix for this would just use angular's `$scope/$rootScope` with `$emit`.  I'd rather we discuss & ensure we are happy with an eventing pattern before taking care of that with a one-off.  Thoughts?

**Comment by benjaminapetersen** [comment]
Was looking at this a bit more.  Currently, I think `project.edit` is the only "event" that updates other DOM nodes on a page, though I anticipate there will be more opportunities for this as we go along.

**Comment by spadgett** [comment]
Probably the reason we've only needed it here so far is you can't watch projects. Other resources we get websocket updates from the server.

**Comment by benjaminapetersen** [comment]
Yeah that makes sense. So perhaps just a `$rootScope.$emit` event is sufficient.

**Comment by spadgett** [comment]
I think for now it makes sense, and if we find ourselves doing in more than a couple places, we should look at a more complete pub/sub solution.
