### ISSUE TITLE
command to display a direct link to REST API

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7070]
I'd appreciate to have a command that for a given type, display or open a direct link to the corresponding section in the REST API.

The command might be `oc help bc` or enrich existing `oc types` to add a direct link to https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-buildconfig

**Comment by danmcp** [comment]
@jwforres FYI

**Comment by liggitt** [comment]
CLI probably shouldn't have direct knowledge of deep-links to external websites (which differ by product and version). There are commands like `oc explain <type>` that are intended to provide information about types. Currently, that only works for k8s types. https://github.com/openshift/origin/issues/7125 opened to make it work for origin types as well.

You'll note that the k8s descriptions do contain links to external doc, but those are based on links in the godoc comments, which requires scripts to rewrite comments and links for stable releases.
