### ISSUE TITLE
Support pending logs

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#7074]
Right now if you try and get logs for a pod which is pending you will get the following error:

```
$ oc logs ${POD}
Pod ${POD} in namespace ${NAMESPACE} : pod is not in 'Running', 'Succeeded' or 'Failed' state - State: "Pending"
```

Pods in a pending state can and do provide logs, they can be retrieved using `docker log` just not `oc logs` or visible in the console. This is especially the case when dealing with containers which use postStart hooks. 

It would be nice to be able to use the oc tools and console to view these logs instead of relying on the docker commands.

**Comment by mwringe** [comment]
This was marked as being fixed by @smarterclayton but I can still reproduce with origin v1.1.3
[https://bugzilla.redhat.com/show_bug.cgi?id=1294067#c28]

**Comment by smarterclayton** [comment]
Reproduce how?

**Comment by mwringe** [comment]
The easiest way to reproduce would be to add a postStart lifecycle hook to a container which just waits in an infinite loop. This will cause the pod to enter a permanent 'pending' state.

From here, try and access the logs via `oc logs` and notice that it will give an error message saying that it can't get logs for a pod in a `pending` state.

Also try and access via `docker logs` and notice that the logs are available.

If docker has access to these logs, the oc commands should as well

**Comment by smarterclayton** [comment]
Can you paste the docker inspect result of the container?  Is this the
first execution?

On Feb 23, 2016, at 5:49 PM, Matthew Wringe <notifications@github.com>
wrote:

The easiest way to reproduce would be to add a postStart lifecycle hook to
a container which just waits in an infinite loop. This will cause the pod
to enter a permanent 'pending' state.

From here, try and access the logs via oc logs and notice that it will give
an error message saying that it can't get logs for a pod in a pending state.

Also try and access via docker logs and notice that the logs are available.

If docker has access to these logs, the oc commands should as well

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/7074#issuecomment-187949819>.

**Comment by mwringe** [comment]
@smarterclayton I have a nice easy test case here which deploys the ruby-hello-world container with a postStart script which keep the pod in a `pending` state until 30 seconds after it has been deployed. You can use this to easily see the issue with `oc logs`

Steps to reproduce:
- deploy test.yaml https://gist.github.com/mwringe/8601d20d78b408612045
- run 'oc logs' on the pod which is created. Note that it produces the following error `Pod "pending-log-test" in namespace "default" : pod is not in 'Running', 'Succeeded' or 'Failed' state - State: "Pending"`
- run `docker log` on the pod and notice that it prints out the logs for this pod
- wait 30 seconds (the postStart script ends after 30 seconds) and try 'oc logs' again, now we can get the logs for the pod

Expected results
- running 'oc logs' on this container should output the same logs that 'docker logs' outputs even if it is in the `pending` state.

**Comment by smarterclayton** [comment]
Please open an issue upstream and assign it to me.

**Comment by jcantrill** [comment]
@mwringe  did you ever open an upstream issue?  can you link it in here and close this one?

**Comment by mwringe** [comment]
ah, nope, I forgot about this issue :/ I don't even know if its still a problem or not
