### ISSUE TITLE
Exercise pod/build logs in UI e2e test

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#7075]
Would be good to add an e2e test in the UI to prevent breakage of the log viewing feature

c.f. https://github.com/openshift/origin/pull/7073

**Comment by benjaminapetersen** [comment]
Yeah, we have been talking about this.  
- Pro: its a fussy component, would be good to catch breakage.  
- Con: might be flaky... :frown:

I'm hoping to work on this once the [PR cleaning up the current e2e tests](https://github.com/openshift/origin/pull/7124) lands.

Feel free to assign me.

@spadgett @jwforres
