### ISSUE TITLE
Get logs from lifecycle scripts

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#7076]
It would be nice to be able to fetch the logs from lifecycle scripts (postStart, preStop, liveness probes, etc).

**Comment by marun** [comment]
This would be very useful.  I'm not sure this capability exists upstream, though (as per https://github.com/kubernetes/kubernetes/issues/16412).

**Comment by mwringe** [comment]
The liveness probes log their messages under events I believe. I am not sure about the postStart/preStop ones though. I moved the metrics components away from using postStart to using liveness probes since it seems to function a bit better overall in terms of what you can see in the console.

**Comment by kargakis** [comment]
@mwringe mind moving this issue upstream?

**Comment by mwringe** [comment]
I believe its being tracked upsteam with https://github.com/kubernetes/kubernetes/issues/16412

**Comment by kargakis** [comment]
Hook failures got their own events now with https://github.com/kubernetes/kubernetes/pull/25681

**Comment by kargakis** [comment]
Separate issue for logs: https://github.com/kubernetes/kubernetes/issues/25766
