### ISSUE TITLE
Display docker image information in the console

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#7077]
It would be nice to be able to display in the console information about a docker image being run in a pod (similar to what we would get back from `docker inspect`).

This would make it easier to users to find information about the image itself (labels, author, etc).

**Comment by mfojtik** [comment]
@mwringe I think this makes sense. We should probably display also the size of the image in console. Dunno if we can get that information from the IST. @ncdc ?

**Comment by mfojtik** [comment]
@jwforres FYI

**Comment by jwforres** [comment]
i know not everything was available before but @smarterclayton just did a bunch of updates to the api

**Comment by smarterclayton** [comment]
Layers and size are the new additions.

**Comment by spadgett** [comment]
We're displaying size now on the overview, although not on the browse image streams page:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/14886730/57d2ae94-0d20-11e6-803c-2f18a23b0748.png)

**Comment by jwforres** [comment]
yeah dont want to waste time updating the image streams page since we
should be bringing in stef's stuff to replace it

**Comment by mwringe** [comment]
Size is nice to have, but there is a lot more information from 'docker inspect' that we could be showing here. Eg labels, environment variables, ports, etc

**Comment by aboe026** [comment]
I'm looking for a way to get docker image labels from docker images imported into openshift. Sounds like this is what i need - a way to retrieve the same info from `docker inspect` with an oc command

**Comment by smarterclayton** [comment]
The oc command for that is "oc get imagestreamtags/foo:bar" or "oc describe
imagestreamtags/foo:bar"

**Comment by jwforres** [comment]
the new imagestream tag page improves this https://github.com/openshift/origin-web-console/pull/235

**Comment by jwforres** [comment]
I don't see us doing anything for images that are not part of an image stream.  Spamming the image import API just to get additional info about images that aren't coming from image streams seems like a bad idea.  @smarterclayton @mfojtik  ?

**Comment by mwringe** [comment]
@jwforres a lot of the containers we ship don't have image streams associated with them, so this wont be useful to determine something from say our metric containers.

**Comment by mfojtik** [comment]
@jwforres we are even going to move the imported manifests back to registry container to not pollute the etc.

**Comment by smarterclayton** [comment]
It might be useful to make it something you could look up.  But agree
it's not appropriate to be doing it on casual view.

**Comment by jwforres** [comment]
Moving this request to Trello https://trello.com/c/p2XoTIor
