### ISSUE TITLE
buildname could be optional in oc logs build

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7079]
When buildname is not specified, `oc logs build` could display the logs of the last build.

A workaround is possible with the following alias

```
alias olb="oc logs build/$(oc get build -o json | jq -r '[.items[].metadata.name]|reverse|.[0]')"
```

**Comment by liggitt** [comment]
`oc logs build` is ambiguous. It could be asking for logs for a pod named build

**Comment by YannMoisan** [comment]
What about `oc logs-build` or `oc logs build/` ?

**Comment by liggitt** [comment]
I think at least the name of the build should be required
