### ISSUE TITLE
Unable to save changes with oc edit

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7085]
On latest master I run this:

```console
[root@localhost rails-ex]# oc edit bc/rails-postgresql-example -o json
```

After I add `incremental: true` to strategy, I get this error:

```
A copy of your changes has been stored to "/tmp/kubectl-edit-7nm06.json"
error: no kind "BuildConfig" is registered for version "pre012"
```

@kargakis (rebase issue?)

**Comment by mfojtik** [comment]
Also if I omit the `-o json` option and get yaml in VIM, after saving I get:

```console
A copy of your changes has been stored to "/tmp/kubectl-edit-65hc1.yaml"
error: no kind "BuildConfig" is registered for version "1.0"
```

**Comment by mfojtik** [comment]
And another one ;-)

```
error: apiVersion should not be changed
A copy of your changes has been stored to "/tmp/kubectl-edit-7fkwb.yaml"
```

(note that I do not update the apiVersion, just add incremental to strategy).

**Comment by mfojtik** [comment]
Should be fixed in upstream, feel free to close this issue when this gets merged to origin

https://github.com/kubernetes/kubernetes/pull/20481

**Comment by mfojtik** [comment]
cc @deads2k @smarterclayton seems like something that broken after rebase.

**Comment by deads2k** [comment]
> cc @deads2k @smarterclayton seems like something that broken after rebase.

I'll take a look.  Can you include the output of what you have in `edit` and also note whether you can do an `oc update` with it?

**Comment by dgoodwin** [comment]
Hitting this one too with oc edit scc/restricted, change a field (not apiVersion), and the result is: "error: apiVersion should not be changed"

**Comment by kargakis** [comment]
@dgoodwin @mfojtik syntax errors are not retried by `kubectl`. This is fixed in https://github.com/openshift/origin/pull/6959
