### ISSUE TITLE
Vendored Kube SHA1 is not in any branch upstream

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#7086]
I've been trying to checkout kubernetes at 9da202e242d8ceedb549332fb31bf1a933a6c6b6 (current ref in Godeps.json), and cannot find the ref.

https://github.com/kubernetes/kubernetes/commit/9da202e242d8ceedb549332fb31bf1a933a6c6b6 hints that this commit is not part of any branch.

The fact that we cannot checkout that ref will prevent us from running extended tests (#6583).

**Comment by rhcarvalho** [comment]
@smarterclayton @deads2k @liggitt FYI

**Comment by liggitt** [comment]
Add the openshift/kubernetes repo as a remote and fetch it. That's where the sha lives

**Comment by rhcarvalho** [comment]
Did we do this before? Extended tests will do a `go get -d k8s.io/kubernetes` and that will not add the remote automatically. Hopefully I can fix the extended tests as part of #7065.

**Comment by rhcarvalho** [comment]
@liggitt looking at https://github.com/openshift/kubernetes/commit/9da202e242d8ceedb549332fb31bf1a933a6c6b6 , that commit is also not in any branch.

Even after adding the remote, I cannot `git checkout` that ref.

What exactly the ref in Godeps.json point at?

```
			"Comment": "v1.2.0-alpha.6-677-g3ba6092",
			"Rev": "9da202e242d8ceedb549332fb31bf1a933a6c6b6"
```

**Comment by liggitt** [comment]
The commit is at https://github.com/openshift/kubernetes/commit/9da202e242d8ceedb549332fb31bf1a933a6c6b6

Add the remote and fetch all.
@deads2k, should probably update the stable branch to point at the commit we godep-ed

**Comment by rhcarvalho** [comment]
No luck :(

```
✔ ~/openshift/src/k8s.io/kubernetes [master|✔] 
17:11 $ git remote -v
openshift       git@github.com:openshift/kubernetes.git (fetch)
openshift       git@github.com:openshift/kubernetes.git (push)
origin  git@github.com:rhcarvalho/kubernetes.git (fetch)
origin  git@github.com:rhcarvalho/kubernetes.git (push)
upstream        https://github.com/kubernetes/kubernetes.git (fetch)
upstream        https://github.com/kubernetes/kubernetes.git (push)
✔ ~/openshift/src/k8s.io/kubernetes [master|✔] 
17:11 $ git fetch --all
Fetching upstream
Fetching origin
Fetching openshift
✔ ~/openshift/src/k8s.io/kubernetes [master|✔] 
17:11 $ git checkout 9da202e242d8ceedb549332fb31bf1a933a6c6b6
fatal: reference is not a tree: 9da202e242d8ceedb549332fb31bf1a933a6c6b6
✘-128 ~/openshift/src/k8s.io/kubernetes [master|✔] 
17:11 $ 
```

**Comment by rhcarvalho** [comment]
According to GitHub's [help](https://help.github.com/articles/commit-exists-on-github-but-not-in-my-local-clone/), we might need to wait until the commit is pushed to some branch/tag by someone who has the commit locally.

**Comment by liggitt** [comment]
Can you not do `git fetch openshift 9da202e242d8ceedb549332fb31bf1a933a6c6b6`?

Agree we want it in a branch

**Comment by rhcarvalho** [comment]
I had tried that as well, and also other ways to fetch it from GitHub, no success.

**Comment by liggitt** [comment]
Created a branch from that commit https://github.com/openshift/kubernetes/tree/stable-9da202e so you can proceed. Will talk with @deads2k and @smarterclayton about how we want to handle tagging commit levels used in rebases.

**Comment by smarterclayton** [comment]
I'm just going to give it a real tag - unfortunately I forgot to tell David about that for this rebase so ill do the fix up and then add it to the docs
