### ISSUE TITLE
Horrifying error on edit

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7090]
```
$ oc edit frontend-route
error: no kind {  frontend-route} has been defined; known resources: map[{ v1 identities}:{ v1 identity} { v1 identitylists}:{ v1 identitylist} { v1beta3 identities}:{ v1beta3 identity} { v1beta3 identitylists}:{ v1beta3 identitylist} { v1 groups}:{ v1 group} { v1 grouplists}:{ v1 grouplist} { v1 userlists}:{ v1 userlist} { v1beta3 groups}:{ v1beta3 group} { v1beta3 useridentitymappings}:{ v1beta3 useridentitymapping} { v1 useridentitymappings}:{ v1 useridentitymapping} { v1 users}:{ v1 user} { v1beta3 users}:{ v1beta3 user} { v1beta3 grouplists}:{ v1beta3 grouplist} { v1beta3 userlists}:{ v1beta3 userlist}]
```

Probably not what we want to show to users.

**Comment by kargakis** [comment]
This is not a problem with edit but with the underlying restmapper
https://github.com/kubernetes/kubernetes/blob/1f113d6a383e343803dedbaf45d0cfc34d02eb82/pkg/api/meta/restmapper.go#L304

**Comment by liggitt** [comment]
Does the same error surface with `oc get foo`?

Also,  I would expect to see more kinds registered in the rest mapper. @deads2k Does this mean that all lookups are chained through several rest mappers, one for each API package?

**Comment by deads2k** [comment]
Yeah that's awful.  We need more information for a user to debug this.  Perhaps we could include the full mapping to and from kinds, plural and singular resources, case and non-case sensitive, priorities, shortcuts, and expansions.   I'll work on it on Monday.  :)

@liggitt its the "fix union RESTMapper" in this issue: https://github.com/openshift/origin/issues/6906.  Once we have that, we'll get a complete listing.  The full union RESTMapper is a chained structure with one link per logical group.

**Comment by smarterclayton** [comment]
Thanks for running this down... It's little stuff like this that make
the difference in the end.
