### ISSUE TITLE
Update CPU and memory icons in web console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7095]
Patternfly now has icons for CPU and memory.

https://www.patternfly.org/styles/icons/

/cc @jwforres

**Comment by jwforres** [comment]
oh nice, we really need to deal with that one issue in the tolopogy view so we can pick up a new patternfly version, also i'd like to do the bump to 3.x at the same time.

**Comment by spadgett** [comment]
Depends on #6815.

**Comment by jwforres** [comment]
@spadgett didn't you look at updating them and we decided the icons didn't display well at small sizes?

**Comment by spadgett** [comment]
> didn't you look at updating them and we decided the icons didn't display well at small sizes?

That's right.
