### ISSUE TITLE
kubectl e2e "should support exec through an HTTP proxy" can't run on Origin

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7097]
Tries to build a static kubectl binary, which we don't support today.

Spawned by #7094

**Comment by liggitt** [comment]
That should be opened upstream... that's insane for a test script to do, especially one that we want to run for conformance checking. cc @timothysc

**Comment by ncdc** [comment]
Jordan, we went through several involved discussions about how to test
this. The static build was the best option we could come up with. I'll link
the relevant discussions when I'm back at my desk.

**Comment by ncdc** [comment]
@liggitt see https://github.com/kubernetes/kubernetes/pull/11694 and the various issues and PRs linked to it

**Comment by ncdc** [comment]
This was fixed by https://github.com/kubernetes/kubernetes/pull/25776. Will come in a future rebase.

**Comment by ncdc** [comment]
I tested this locally and the test passed. #10641 enables the test.
