### ISSUE TITLE
TLS doesn't work for me

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#710]
curl calls (yes, the output is one blank line)

```
$ curl localhost:8443

$ curl localhost:8443/osapi

$ curl localhost:8443/osapi/v1beta1/

$ curl localhost:8443/osapi/v1beta1/builds
```

Logs

```
Jan 22 04:23:04 . openshift[707]: 2015/01/22 04:23:04 http: TLS handshake error from [::1]:54581: tls: first record does not look like a TLS handshake
Jan 22 04:23:09 . openshift[707]: 2015/01/22 04:23:09 http: TLS handshake error from [::1]:54582: tls: first record does not look like a TLS handshake
Jan 22 04:23:42 . openshift[707]: 2015/01/22 04:23:42 http: TLS handshake error from [::1]:54585: tls: first record does not look like a TLS handshake
Jan 22 04:23:58 . openshift[707]: 2015/01/22 04:23:58 http: TLS handshake error from [::1]:54586: tls: first record does not look like a TLS handshake
```

rhel 7
git master: https://github.com/openshift/origin/commit/ed60f9fa6925f8f442f8bf36ba4279803349853c

**Comment by brenton** [comment]
Hi Tomas,  See http://lists.openshift.redhat.com/openshift-archives/dev/2015-January/msg00057.html

TLS was just turned on by default yesterday.  When you run curl localhost:8443 you are trying to make an non-TLS request to a secure socket.

**Comment by TomasTomecek** [comment]
You are right! I feel so silly now!

Well... On the other hand, wouldn't it make sense to respond with redirect to `https` once client requests plain `http`?

**Comment by brenton** [comment]
If the TLS handshake failed the request never makes it to the HTTP layer where a redirect would need to happen.

**Comment by brenton** [comment]
Closing this unless there are further questions.
