### ISSUE TITLE
Extended test "openshift postgresql replication" does not work remotely

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7102]
```
• Failure [27.311 seconds]
[images][postgresql] openshift postgresql replication
/Users/clayton/projects/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/postgresql_replica.go:38
  postgresql replication works for registry.access.redhat.com/rhscl/postgresql-94-rhel7 [It]
  /Users/clayton/projects/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/postgresql_replica.go:36

  Expected error:
      <*exec.Error | 0xc82055cbe0>: {
          Name: "chcon",
          Err: {
              s: "executable file not found in $PATH",
          },
      }
      exec: "chcon": executable file not found in $PATH
  not to have occurred

  /Users/clayton/projects/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/postgresql_replica.go:73
--------------------
```

Extended tests should not assume they are on the same host - they need to be using a container to do these manipulations.  Blocks running e2e against a remote cluster.

Spawned from #7094

**Comment by bparees** [comment]
how can they use a container to manipulate the host paths to provide PVs?  launch privileged containers as root with the host filesystem mounted into them?  

The right solution to this imho is an extended test cluster environment that provides out of the box PVs so tests don't have to do this stuff.

And as with the other issue, if we can't assume a single-node cluster, other things are going to fall apart too, so we should discuss that now if it's not a safe assumption anymore.

**Comment by smarterclayton** [comment]
Basically, e2e tests need to be run from the outside.  You can add
abstractions for ssh, or rely on pod exec, but tests that run from the
inside and make those assumptions can't be part of anything that tests
multinode (and we need tests that verify that builds on multinode
clusters work).  I didn't see anything in the testing that couldn't be
worked around - almost everything could be verified another way.

If the test is not useful in a remote way, split out the part that is
into its own test.

**Comment by bparees** [comment]
per discussion with @smarterclayton going to mark this test as LocalNode, reducing severity, but we will want to revisit/fix this behavior at some point.

**Comment by bparees** [comment]
@smarterclayton I still think the right solution here is for the extended test cluster to provide PVs, especially now that this setuphostpathvolumes is causing us other issues:
https://github.com/openshift/origin/issues/14972

I would think other extended tests would have a need for PVs anyway.  Do we have other extended tests that are leveraging/testing PVs today and doing it in a different way?

**Comment by smarterclayton** [comment]
We do - those tests are mostly run on GCE

**Comment by bparees** [comment]
@smarterclayton can you point us to a pattern we can copy for this job?  (how are those tests setting up PVs)

**Comment by bparees** [comment]
when you get time (probably after this sprint), it'd be good to adapt your NFS PV approach to fix this test too.

**Comment by bparees** [comment]
(NFS approach here: https://github.com/openshift/origin/pull/18708)

**Comment by coreydaley** [comment]
Once #18708 gets merged I should be able to knock this out, along with the other couple of database tests that use persistent volumes.
