### ISSUE TITLE
Persistentvolumeclaims "same-name" already exists

### ISSUE THREAD

**Issue by alejandronb** [openshift/origin#7104]
Hi,

I expose my case:

I create a NFS Persistent Volume and I launch the 'mysql-persistent-template'.

Is there any way to launch an application named "Gandalf" from mysql-persistent-template, delete this application, and launch again the same application with the same name "Gandalf" for using the previously created PVC named "Gandalf"?

I don't want to delete the PVC, but if I don't delete the PVC, when I launch the template mysql-persistent-template again with the same name to use the same volume, this error appears:

<pre>Cannot create persistentvolumeclaims. persistentvolumeclaims "Gandalf" already exists.</pre>

I link my case:
[https://lists.openshift.redhat.com/openshift-archives/users/2016-February/msg00000.html](https://lists.openshift.redhat.com/openshift-archives/users/2016-February/msg00000.html)

**Comment by childsb** [comment]
You do not need to re-create the claim.   I would have have to see the mysql-persistent-template, but i suspect you're creating a PVC in there. 

I tend to separate the 3 items into different markup files.  One for the PV, one for the PVC, then one for the application that targets the PVC.  Then its easy to delete the application, and recreate.

**Comment by alejandronb** [comment]
Ok, I understand the best way to do this is to create the PV and PVC in different templates. Then, I create the application template. This template have the information to mount the previously created PVC.
