### ISSUE TITLE
kubelet "container runtime sanity check failed" logs

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#7105]
I am seeing the following logs repeatedly in the latest master
```
E0208 10:24:22.945029    1362 kubelet.go:2590] Container runtime sanity check failed: docker: failed to parse docker server version "1.8.1.fc21": strconv.ParseInt: parsing "1.fc21": invalid syntax
E0208 10:24:27.945980    1362 manager.go:1017] docker: failed to parse docker server version "1.8.1.fc21": strconv.ParseInt: parsing "1.fc21": invalid syntax
```

**Comment by rhcarvalho** [comment]
I'm seeing the same, and after some time I see an extra line:

```
E0208 12:20:14.282148   18252 manager.go:1017] docker: failed to parse docker server version "1.8.2.fc21": strconv.ParseInt: parsing "2.fc21": invalid syntax
E0208 12:20:14.282530   18252 kubelet.go:2590] Container runtime sanity check failed: docker: failed to parse docker server version "1.8.2.fc21": strconv.ParseInt: parsing "2.fc21": invalid syntax
I0208 12:20:18.140582   18252 kubelet.go:2277] skipping pod synchronization - [container runtime is down]
```

At that point builds won't start until I restart the server.

**Comment by rhcarvalho** [comment]
The problem seems to be that https://github.com/coreos/go-semver/ doesn't handle `x.x.x.fcXX` format used by Fedora.

**Comment by rhcarvalho** [comment]
There's a PR upstream (https://github.com/coreos/go-semver/pull/11) to fix that problem, but it might take time until it lands. I guess we'll need need a patch in OpenShift for the time being, working on it.

**Comment by deads2k** [comment]
@eparis has recommended we don't bother with that level.  Upgrade your docker version.

**Comment by deads2k** [comment]
See comments here: https://github.com/kubernetes/kubernetes/pull/20705

**Comment by rhcarvalho** [comment]
Our vagrant VirtualBox image uses Fedora 21... what'd be the recommended solution?  /cc @danmcp

**Comment by rhcarvalho** [comment]
> Upgrade your docker version.

Hmm in the case of those of us using vagrant+VirtualBox, it's more like "upgrade the VM's distro". The latest Docker version for Fedora 21 is 1.8.2.fc21.

**Comment by danmcp** [comment]
@rhcarvalho It's Fedora 23.

**Comment by kargakis** [comment]
@rhcarvalho our vagrantfile is update to use fedora23. I just did
```sh
$ vagrant box remove fedora_inst
# remove also the machine from virtualbox
$ vagrant up
$ vagrant ssh
$ cat /etc/redhat-release 
Fedora release 23 (Twenty Three)
```

**Comment by kargakis** [comment]
We also use docker 1.9.1 in the latest image so I am going to close this issue.
