### ISSUE TITLE
hack/cherry-pick.sh fails with "9da202e can not be resolved as commit".

### ISSUE THREAD

**Issue by jsafrane** [openshift/origin#7106]
Following https://github.com/openshift/origin/blob/master/HACKING.md#cherry-picking-an-upstream-commit-into-origin, this does not work:

```sh
$ hack/cherry-pick.sh 19600

++ pr/19600 appears to have merged at fc2929ed05a8500b7ea5b990b843fa1543b7efb3
++ Generating patch for 5914deeac82e5ad5d288517aa0aaaee5aa5b381e..e90de3f9855b68ffe4dbbbbd98484c2a3ec0e113 onto 9da202e ...
fatal: Cannot update paths and switch to branch 'last_upstream_branch' at the same time.
Did you intend to checkout '9da202e' which can not be resolved as commit?
```

`9da202e` comes from

```
go run /home/jsafrane/project/go/src/github.com/openshift/origin/tools/godepversion/godepversion.go /home/jsafrane/project/go/src/github.com/openshift/origin/Godeps/Godeps.json k8s.io/kubernetes/pkg/api
```

There is no commit `9da202e` in Kubernetes upstream.

**Comment by liggitt** [comment]
Need to add the openshift/kubernetes repo as a remote to your kubernetes and fetch it. The vendored sha includes our carries.

**Comment by jsafrane** [comment]
> add the openshift/kubernetes repo as a remote to your kubernetes and fetch it

This is not documented anywhere, I filled PR #7115.
