### ISSUE TITLE
Unable to connection from a 'master' to minions when using OPENSHIFT_DEV_CLUSTER

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#711]
How to reproduce:

1. export OPENSHIFT_DEV_CLUSTER=1
2. vagrant up
3. vagrant ssh master
4. ping openshift-minion-1
....
4 packets transmitted, 0 received, 100% packet loss, time 3000ms

This is the same for openshift-minion-2. This seems to be random (after several vagrant halt/up, it sometimes works...)

We tracked it down into host NetworkManager, where the NetworkManager sees the VirtualBox devices and tries to manage them. If I add following into /etc/NetworkManager/NetworkManager.conf:

```
[keyfile]
unmanaged-devices=mac:0a:00:27:00:00:00;mac:0a:00:27:00:00:01;mac:0a:00:27:00:00:02;mac:0a:00:27:00:00:03;mac:0a:00:27:00:00:04
```

where the MAC addresses are addresses of vboxnet# interfaces and I systemctl restart NetworkManager then the problem seems to go away and I can connect between minions and also from master to minions.

After running `nmcli d` I see all vboxnet# devices as 'unmanaged'.

We should either update our Vagrant instructions to include this or fix the VirtualBox RPM to automatically update/install the config file with unmanaged-devices list.

@rajatchopra @mrunalp ^^

**Comment by mfojtik** [comment]
Related: https://bugzilla.gnome.org/show_bug.cgi?id=731014

**Comment by mrunalp** [comment]
@mfojtik Thanks for chasing this down. What host OS are you on Fedora 20 or 21 or centos/RHEL?

**Comment by mfojtik** [comment]
@mrunalp I am on Arch Linux with networkmanager @goldmann is on Fedora 21. The fix I suggested worked on both.

**Comment by mrunalp** [comment]
@mfojtik okay, cool. I will work on a fix. Might be document or some script. The problem I see is that the config file isn't probably in the same place for all distros so might have to resort to Dbus.

**Comment by goldmann** [comment]
@mrunalp I guess [documenting this here](https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc) + an example would be fine since this is an [upstream bug](https://bugzilla.gnome.org/show_bug.cgi?id=731014).

**Comment by mrunalp** [comment]
@goldmann Sounds good to me.
