### ISSUE TITLE
Create fuzzer tests for configapi scheme

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#7116]
The config api we use now has some pretty significant custom conversion code.  We need fuzzer tests for the roundtripping.

**Comment by liggitt** [comment]
most of the complexity is in defaulting, right, so round-trip would add stuff, not match 100%

**Comment by deads2k** [comment]
Fuzzing fills all the fields, so defaulting rules should never apply.  Defaulting rules would need targeted tests.
