### ISSUE TITLE
field.Required now allows details.  sweep for usage and proper messages

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#7118]
We use this method extensively in various validation methods.

@pweil- This could be a "getting to know our API" task.

**Comment by sgallagher** [comment]
@deads2k Would you mind providing slightly more detail on the requested task?

I assume what we're talking about is reviewing the 242 (thanks, git-grep!) uses of field.Required and adding extra data about "why" a particular error is thrown, but it's not entirely clear from the bug description.

**Comment by deads2k** [comment]
> I assume what we're talking about is reviewing the 242 (thanks, git-grep!) uses of field.Required and adding extra data about "why" a particular error is thrown, but it's not entirely clear from the bug description.

Yes, that's correct.  I haven't looked through upstream usages to see what sort of descriptions they are adding, but on our side I'd like to see us indicate a reason if a field is required because of the value of a different field.  Otherwise, knowing its a required error is sufficient.

**Comment by sgallagher** [comment]
@deads2k OK, so I should ignore the cases where we are just checking for simple presence?

**Comment by deads2k** [comment]
> @deads2k OK, so I should ignore the cases where we are just checking for simple presence?

Right, there's no value in repeating ourselves.

**Comment by bparees** [comment]
@deads2k @mfojtik I assume this really needs to be broken down into separate issues for each api resource that isn't doing this correctly today.
