### ISSUE TITLE
Get all update-generated, verify-, and test scripts working in the kube fork

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#7120]
@pweil- This is something we want, but this is probably something the CI team is better suited to do.

**Comment by brenton** [comment]
@deads2k, can you tell me a little more about this request?  To date the CI team is mostly @arilivigni and he focuses on the CI infrastructure primarily.  Is this issue "I just performed a rebase and now tests don't work" or "I need a way to run the rebased tests in CI"?

**Comment by deads2k** [comment]
@brenton Sorry, CI as in "Cluster Infrastructure", @ncdc @derekwaynecarr @eparis and company.

**Comment by pweil-** [comment]
my misunderstanding, I read it as continuous integration

**Comment by ncdc** [comment]
This is done
