### ISSUE TITLE
transitive bump checker improvements

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#7121]
The rebase brought in a new transitive dependency tool, but its not very sophisticated.  See `hack/rebase-describe-bumps.sh`.  It should be improved to handle:
- [ ] multiple sorts on output, including "openshfit deps that are newer" and "kube deps that are newer"
- [ ] it should force the godeps that we're keeping to the correct level.  Something like 

``` bash
cd $GOPATH/src/<godep name>
git checkout master
git checkout -b openshift-level
git reset --hard <openshift-level>
```
- [ ] look for `UPSTREAM` commits for godeps that look like they've changed.
- [ ] special-case cadvisor to always take the kube level
- [ ] make the check less transitive.  We only need separate bumps for dependencies that openshift code directly imports.  The rest will just end up being noise.

**Comment by liggitt** [comment]
@deads2k would you want special handling of the k8s repo? I'd like something to validate the remotes (origin/upstream/openshift) and make sure openshift is fetched...

**Comment by deads2k** [comment]
> @deads2k would you want special handling of the k8s repo? I'd like something to validate the remotes (origin/upstream/openshift) and make sure openshift is fetched...

I'm fine with that.
