### ISSUE TITLE
Web console scaling not working on latest deployment page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7131]
Updating the replicas doesn't result in the deployment being scaled.

![openshift_web_console_and__deployment-details_html____go_src_github_com_openshift_origin_assets_app_views_browse__-_vim](https://cloud.githubusercontent.com/assets/1167259/12895508/d81acc66-ce6a-11e5-9e60-f10856435383.png)

**Comment by liggitt** [comment]
does that just edit the dc spec replicas?
@ironcladlou can you confirm the intended behavior here?

**Comment by spadgett** [comment]
@liggitt All scaling for me is broken including `oc scale`. Testing now whether it's only a problem in my environment.

**Comment by ironcladlou** [comment]
Edits to rc.spec.replicas for an rc managed by a deploymentConfig will always be reverted eventually to match the dc. Scaling should occur via updates to dc.spec.replicas.

Old CLI clients might still manipulate the RC directly which we have some backwards compatibility for... if you found a case where an old `oc` binary isn't scaling right, please let me know so I can confirm whether that's expected or not.

**Comment by spadgett** [comment]
@ironcladlou web console always scales the DC when there is one. There must be something wrong in my environment unless scaling is broken.

**Comment by spadgett** [comment]
I can no longer reproduce after updating my environment. Closing.
