### ISSUE TITLE
Error using a sa credential inside a container

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7139]
I try to use a service account credential inside a container, as explained in the [documentation](https://docs.openshift.org/latest/dev_guide/service_accounts.html#using-a-service-account-s-credentials-inside-a-container)

Here is how I retrieve the token

```
  TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
```

Here is the error on the command `oc get istag`
```
Error from server: User "system:serviceaccount:xxx:builder" cannot get imagestreamtags in project "xxx"
```

**Comment by liggitt** [comment]
By default, service accounts have extremely limited permissions. If you want them to have more permissions in your namespace, add the roles you want with `oc policy add-role-to-user <role> -z service-account-name` or `oc policy add-role-to-group <role> system:serviceaccounts:<namespace-name>`

**Comment by YannMoisan** [comment]
Thanks a lot.
Here is the fix if anyone else has the same issue `oc policy add-role-to-user edit system:serviceaccount:xxx:builder -n xxx`

**Comment by YannMoisan** [comment]
BTW, I was surprised that, by default, builder can push image to _imagestream_ but can't push tag to _imagestreamtag_
