### ISSUE TITLE
Utility tool to output tokens

### ISSUE THREAD

**Issue by simon3z** [openshift/origin#7141]
Currently to fetch accounts token we have complex bash tricks:

    $ oc get -n management-infra sa/management-admin --template='{{range .secrets}}{{printf "%s\n" .name}}{{end}}'
    management-admin-token-32f97
    management-admin-dockercfg-fvkso

    $ oc get -n management-infra secrets management-admin-token-32f97 --template='{{.data.token}}' | base64 -d
    eyJhbGciOiJSUzI1NiIsInR5cC...

We are looking forward to have a more automated way to fetch the tokens.

cc @smarterclayton @deads2k

**Comment by deads2k** [comment]
@simon3z see https://github.com/openshift/origin/pull/6941.  I didn't forget about you. :)

**Comment by simon3z** [comment]
Thanks @deads2k ! @enoodle when you have some time can you give a try to what's implemented in #6941
