### ISSUE TITLE
integers in versioned objects

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#7142]
We need to use int64 or int32 for integers in versioned objects.

Related: https://github.com/openshift/origin/issues/6850

@smarterclayton @deads2k @liggitt

**Comment by smarterclayton** [comment]
Yeah, can be post 1.2

**Comment by mfojtik** [comment]
(i'm doing this as part of the rebase)

**Comment by mfojtik** [comment]
Rebase landed, we should be converted by now.

**Comment by kargakis** [comment]
@smarterclayton is this done?

**Comment by mfojtik** [comment]
@kargakis https://github.com/openshift/origin/pull/9366

**Comment by mfojtik** [comment]
@smarterclayton feel free to close this.
