### ISSUE TITLE
ImageStreamTags list contains no resource version

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#7156]
```
$ oc get imagestreamtags --loglevel=8
I0209 11:05:45.145298   37670 loader.go:242] Config loaded from file /Users/jliggitt/go/src/github.com/openshift/origin/openshift.local.config/master/admin.kubeconfig
I0209 11:05:45.146080   37670 loader.go:242] Config loaded from file /Users/jliggitt/go/src/github.com/openshift/origin/openshift.local.config/master/admin.kubeconfig
I0209 11:05:45.259438   37670 round_trippers.go:264] GET https://10.192.211.59:8443/oapi
I0209 11:05:45.259455   37670 round_trippers.go:271] Request Headers:
I0209 11:05:45.259459   37670 round_trippers.go:274]     User-Agent: oc/v1.1.2 (darwin/amd64) openshift/681db94
I0209 11:05:45.278473   37670 round_trippers.go:289] Response Status: 200 OK in 18 milliseconds
I0209 11:05:45.278490   37670 round_trippers.go:292] Response Headers:
I0209 11:05:45.278504   37670 round_trippers.go:295]     Cache-Control: no-store
I0209 11:05:45.278507   37670 round_trippers.go:295]     Content-Type: application/json
I0209 11:05:45.278520   37670 round_trippers.go:295]     Date: Tue, 09 Feb 2016 16:05:45 GMT
I0209 11:05:45.278523   37670 round_trippers.go:295]     Content-Length: 59
I0209 11:05:45.278553   37670 request.go:878] Response Body: {"kind":"APIVersions","apiVersion":"v1","versions":["v1"]}
I0209 11:05:45.279429   37670 loader.go:242] Config loaded from file /Users/jliggitt/go/src/github.com/openshift/origin/openshift.local.config/master/admin.kubeconfig
I0209 11:05:45.280065   37670 loader.go:242] Config loaded from file /Users/jliggitt/go/src/github.com/openshift/origin/openshift.local.config/master/admin.kubeconfig
I0209 11:05:45.280920   37670 round_trippers.go:264] GET https://10.192.211.59:8443/oapi/v1/namespaces/default/imagestreamtags
I0209 11:05:45.280930   37670 round_trippers.go:271] Request Headers:
I0209 11:05:45.280933   37670 round_trippers.go:274]     User-Agent: oc/v1.1.2 (darwin/amd64) openshift/681db94
I0209 11:05:45.282090   37670 round_trippers.go:289] Response Status: 200 OK in 1 milliseconds
I0209 11:05:45.282103   37670 round_trippers.go:292] Response Headers:
I0209 11:05:45.282116   37670 round_trippers.go:295]     Content-Length: 129
I0209 11:05:45.282120   37670 round_trippers.go:295]     Cache-Control: no-store
I0209 11:05:45.282122   37670 round_trippers.go:295]     Content-Type: application/json
I0209 11:05:45.282125   37670 round_trippers.go:295]     Date: Tue, 09 Feb 2016 16:05:45 GMT
I0209 11:05:45.282146   37670 request.go:878] Response Body: {"kind":"ImageStreamTagList","apiVersion":"v1","metadata":{"selfLink":"/oapi/v1/namespaces/default/imagestreamtags"},"items":[]}
```

**Comment by liggitt** [comment]
Also projects

**Comment by deads2k** [comment]
Choosing a resource version for a virtual list requires inspecting the (theoretically) opaque resourceVersion of its items.  That breaks the intended abstraction.

**Comment by liggitt** [comment]
I thought the list resource version came from the resource version of the server, not a particular child

**Comment by deads2k** [comment]
> I thought the list resource version came from the resource version of the server, not a particular child

On a virtual resource that has no etcd storage and is the combination of two different sets of resources, which resource version would you use?

**Comment by liggitt** [comment]
I would expect a resourceVersion on any resource that supports watch. If imageStreamTags and projects don't, then I'm not as concerned

**Comment by jcantrill** [comment]
@liggitt Are you implying we should not watch on ImageStreamTags?

**Comment by liggitt** [comment]
They don't support watch, so no

**Comment by deads2k** [comment]
Is there anything to do here?

**Comment by liggitt** [comment]
still feels like we should include *something* in the resourceVersion, even a "0" or something

**Comment by deads2k** [comment]
> still feels like we should include something in the resourceVersion, even a "0" or something, and at the point we implement watch, update that to match what watch understands

Deceptive information is better than no information?  Zero only has special meaning because you've interpreted that opaque string.

**Comment by liggitt** [comment]
I'm thinking of clients that will crash if they get a nil resourceVersion attribute, even if they never use it

**Comment by deads2k** [comment]
> I'm thinking of clients that will crash if they get a nil resourceVersion attribute, even if they never use it

Would you be happy or sad if I gave you a fake git commit hash for something?  I'd be angry.

**Comment by liggitt** [comment]
Clients should be able to be written based on https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#lists-and-simple-kinds which says lists should have this field. I'd prefer "0" to nil

**Comment by deads2k** [comment]
Do we disagree on the meaning of `SHOULD`?  I would claim that this is exactly the kind of "valid reasons" that the rfc specifies.
