### ISSUE TITLE
Ability to restrict login based or orgs/domains with OAuth providers

### ISSUE THREAD

**Issue by abhgupta** [openshift/origin#7157]
With Github or Google configured as the identity providers, we should be able to restrict the the set of users who can login to OpenShift. We can do this for Github using organizations and for Google using domains. 

For Github, we should to be able to specify multiple organizations in the provider configuration. A check needs to be made to ensure that the Github user is part of at least one of the allowed organizations. If not, the user is provided an authentication failure message. 

The immediate use case is for OpenShift Dedicated customers to be able to better control access to their clusters.

**Comment by abhgupta** [comment]
@liggitt @sspeiche

**Comment by sspeiche** [comment]
Agree, on the GitHub side. I've wondered how useful it was without restricting to orgs.  Google we already have the ability to restricted based on hostedDomain.
