### ISSUE TITLE
Web console: "Name" table header visible with no content on mobile

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7163]
See screenshot. We should only display "No builds to show."

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12925849/6de119ee-cf2e-11e5-9c77-4ebd9b2dc156.png)

/cc @jwforres @sg00dwin @rhamilto

**Comment by jwforres** [comment]
is this all of our tables or is this just on builds

**Comment by spadgett** [comment]
Build and deployments. Others don't have it. PVC looks like this:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12926131/efb48d60-cf2f-11e5-8dfe-88c5242e3318.png)

**Comment by rhamilto** [comment]
I'll fix this one, but I'm unable to assign it to myself.
