### ISSUE TITLE
Link in "about" only goes to latest client tools

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#7171]
The link in the about page on the console only goes to the latest tools. Are we sure that this won't cause breaking changes. I would prefer that we either
a) include the binaries in the distro and link to those files
b) just point to the releases page and tell them to get the one that matches the version they are running. 

I am not sure how to handle this for OSE but that seems best for origin.

**Comment by liggitt** [comment]
I think latest is better. The value is overrideable for ose

**Comment by thesteve0** [comment]
But what if their version is not latest?

**Comment by liggitt** [comment]
That's why oc work to remain compatible with older servers

**Comment by jwforres** [comment]
As @liggitt mentioned oc tries to be backward compatible as a client.  "Latest" is right for what is checked into origin.  Enterprise can either be overridden to lock to where the versions for that release are hosted, to point to a generic location where all the releases are located, or could completely hide the oc download section by default.  Any running OS server is able to customize the links to their hearts content, which is what we will do for Online:  https://github.com/openshift/origin/pull/7169/files#diff-6bf4113e7990a30aba01883335c5998cR9

**Comment by thesteve0** [comment]
Tries being the operative word. How often do we actually test. Feels like
we are setting up for a bad experience here.
