### ISSUE TITLE
Review deletecollection changes for origin

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#7172]
Added upstream in https://github.com/kubernetes/kubernetes/pull/18290/files#diff-7cf62556f9392a93c45627f77bff3229R450
- [x] Upstream change to add a new verb (`deletecollection`) - #7209
- [x] Bootstrap policy changes for new verb - #7209
- [ ] REST handler changes to support DeleteCollection (things that inline generic etcd get it for free)
- [ ] namespace controller changes to use DeleteCollection

cc @deads2k

**Comment by deads2k** [comment]
Looks like it will be an additional verb upstream in the query handler and then changes to policy.  You want it or shall I?

**Comment by liggitt** [comment]
Actually, I don't see a new verb upstream in `GetRequestInfo`... I think it just looks like a delete without a resource name

**Comment by deads2k** [comment]
I glanced and saw this: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/api_installer.go#L598, which looks like a new verb, but I haven't drilled into it.

**Comment by deads2k** [comment]
Ah, I see.  Virtual verb wired into the same action on the route.  Awesome.  I don't know that I care about restricting it separately.

**Comment by liggitt** [comment]
policy changes are complete, lowering priority for remaining items
