### ISSUE TITLE
Suppress the docker image pulling progress bar in build logs

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7176]
``` console
Step 0 : FROM openshift/nodejs-010-centos7@sha256:83111d8b98f0808e1f8770242e284730689eb7c17769da16436f2087f379c109
3   Trying to pull repository docker.io/openshift/nodejs-010-centos7 ... Pulling from openshift/nodejs-010-centos7
4   Pulling fs layer
5   Already exists
6   Already exists
7   Already exists
8   Already exists
9   Already exists
10  Downloading [>                                                  ] 524.7 kB/54.75 MB
Downloading
11  Downloading [>                                                  ] 1.055 MB/54.75 MB
Downloading
12  Downloading [=>                                                 ] 1.595 MB/54.75 MB
Downloading
```

This looks pretty ugly, we should probably just print the message that we are downloading the image and report success/failure.

**Comment by bparees** [comment]
that's not coming from us, it's coming from the docker build process right?  So filtering it is possible but trying to then report success/failure is going to be error prone at best.

(ie we are not the ones pulling the image in this case, docker build is)

**Comment by mfojtik** [comment]
@bparees I think what we can do is to suppress the output of docker build, check for the failure and if that happens flush that out to build log. The problem is that when you pulling multi-layer image, this floods the screen in webconsole so you have to always scroll down... Also the log streamer is not doing great job on rendering the progress bars, so each update is a new line...

**Comment by mfojtik** [comment]
![screen shot 2016-02-22 at 10 39 35](https://cloud.githubusercontent.com/assets/44136/13214549/a3633576-d950-11e5-846b-63ee7b88c7e2.png)

FYI, this is what I'm talking about ;-)

**Comment by mfojtik** [comment]
@bparees @smarterclayton as @rhcarvalho pointed out today, this might be fixed if we set the TERM correctly in web console.

**Comment by smarterclayton** [comment]
Which would be nice

**Comment by mfojtik** [comment]
@smarterclayton unfortunately does not fix the problem :-/ (tested by setting the TERM env in build config)

**Comment by mfojtik** [comment]
@csrwng I think you fixed this a long time ago :-) Closing.

**Comment by wanghaoran1988** [comment]
Fixed by https://github.com/openshift/origin/pull/10873
