### ISSUE TITLE
system:admin login asks for pass and ContainerManager Failed to ensure state of "/docker-daemon"

### ISSUE THREAD

**Issue by gemoya** [openshift/origin#7177]
Hi,

I build a docker image from github Dockerfile of Openshift Origin.
when I try to login as system:admin with

`[root@localhost origin]# oc login -u system:admin
Authentication required for https://localhost:8443 (openshift)
Username: system:admin
Password:
error: username system:admin is invalid for basic auth`

origin asks for user password but system:admin is with credentials.
Also I tried with flags: --certificate-authority=/path/to/cert.crt but still asking for a password..

docker logs:

`W0210 11:57:33.038079    5223 container_manager_linux.go:272] [ContainerManager] Failed to ensure state of "/docker-daemon": [failed to move PID 5294 (in "/") to "/docker-daemon", failed to move PID 5017 (in "/system.slice/docker.service") to "/docker-daemon"]
2016-02-10 11:57:33.600988 I | http: TLS handshake error from 127.0.0.1:52055: remote error: bad certificate`

Some ideas?

Greetings!

**Comment by liggitt** [comment]
From email list:

> system:admin can only log in with certificate authentication.  If you have the original admin.kubeconfig file, it will have those certs in it and -u would switch to using them.  In your case, your kubeconfig file probably doesn't have that info.  Look for your original admin.kubeconfig file.

**Comment by sudhaker** [comment]
Enjoy!

=== setup (public network) ===
cat > /etc/systemd/system/openshift.service << 'EOF'
[Unit]
Description=Openshift Demo Cluster
After=docker.service
Requires=docker.service
 
[Service]
Type=oneshot
RemainAfterExit=yes
Environment="MY_OPENSHIFT=/opt/openshift"
ExecStart=/opt/openshift/bin/oc cluster up \
--public-hostname=${HOSTNAME} \
--host-data-dir=${MY_OPENSHIFT}/data \
--host-config-dir=${MY_OPENSHIFT}/config \
--host-volumes-dir=${MY_OPENSHIFT}/volumes \
--host-pv-dir=${MY_OPENSHIFT}/pv \
--use-existing-config=true
ExecStop=/opt/openshift/bin/oc cluster down

[Install]
WantedBy=multi-user.target

EOF

systemctl daemon-reload
systemctl enable openshift.service
systemctl start openshift.service

=== setup (internal; air gapped  network) ===
cat > /etc/systemd/system/openshift.service << 'EOF'
[Unit]
Description=Openshift Demo Cluster
After=docker.service
Requires=docker.service
 
[Service]
Type=oneshot
RemainAfterExit=yes
Environment="MY_OPENSHIFT=/opt/openshift"
Environment="MY_REGISTRY=registry_server:5000"
ExecStart=/opt/openshift/bin/oc cluster up \
--public-hostname=${HOSTNAME} \
--image=${MY_REGISTRY}/openshift/origin \
--host-data-dir=${MY_OPENSHIFT}/data \
--host-config-dir=${MY_OPENSHIFT}/config \
--host-volumes-dir=${MY_OPENSHIFT}/volumes \
--host-pv-dir=${MY_OPENSHIFT}/pv \
--use-existing-config=true
ExecStop=/opt/openshift/bin/oc cluster down

[Install]
WantedBy=multi-user.target

EOF

systemctl daemon-reload
systemctl enable openshift.service
systemctl start openshift.service
