### ISSUE TITLE
Random thoughts while I'm using the CLI to do what hack/test-end-to-end.sh does

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#718]
* Setting up a registry should be some sort of automatic step - one command
* Need to be able to easily delete everything that comes out of a template
  * that includes pods, which means delete of RC doesn't quite do what we want
* passing complex args to process should be different - support A=B type syntax, also potentially let you get env from a file
* Still need secrets, but once we have secrets we'll still need to create them in a template
  * Remove need for some secrets like CA/CERT etc by having them be part of default deployment
* Create of something that already exists
* Stop printing the object we sent when an error happens
* Errors are ugly
* Pod putting host at the end of the pod name sucks because it's harder to cut and paste
* Better pod names for build, deploy (make unique with shorter names)
* still too hard to get CA stuff on the CLI - make need some sort of helper
* osc get all (or even a shortcut for all)

**Comment by smarterclayton** [comment]
@bparees re: dev experience - feel free to add your hate here

**Comment by mfojtik** [comment]
* A lot of complains about `Pending` state during JBoss sessions. We should display events when you do cli describe to get more detailed informations about what is going on.

**Comment by bparees** [comment]
"Need to be able to easily delete everything that comes out of a template "  - you can do this today, we create a unique label for everything when we process the template, so everything created from a template has a common label that you can delete by.

**Comment by bparees** [comment]
Most of my hate is directed at the https requirements/flags (having to provide the cert on the cli.  I assume this will go away w/ david's feature to allow you to store config, but it's still a pain for our iterative dev model where we create a new cert everytime and store it in a random directory)

**Comment by derekwaynecarr** [comment]
Re: cert stuff - I agree with Ben and would like some Dev tool bash scripts that just supply all these args to each common Dev tool - curl, etc. this is if I understand the original note from Jordan correctly.

**Comment by csrwng** [comment]
> "Need to be able to easily delete everything that comes out of a template " - you can do this today, we create a unique label for everything when we process the template, so everything created from a template has a common label that you can delete by.
In addition to the resources in the template it would also be nice that resources generated by those resources also get the same identifying label. For example, the pods we create to run a build or a deployment. That way if you remove everything with the template's label, you get to the state that you were before you applied.

**Comment by mfojtik** [comment]
@csrwng I was also thinking about being able to specify the label you want give to all resources you are creating:

```
$ openshift cli create -f app_config.json --set-label="foo=bar"
```

**Comment by csrwng** [comment]
@mfojtik +1

**Comment by mfojtik** [comment]
Another thing... this is pretty ugly if you don't have full screen terminal:

```
[root@openshiftdev origin]# osc get pods
POD                                               CONTAINER(S)         IMAGE(S)                    HOST                  LABELS                                                                                                             STATUS
01384e23-a306-11e4-816f-080027ce4245/172.17.0.3   registry-container   openshift/docker-registry   openshiftdev.local/   deployment=docker-registry-1,deploymentconfig=docker-registry,name=registrypod,template=docker-registry-template   Running

```

**Comment by bparees** [comment]
@mfojtik +1 but i think that's in part these bullets from clayton:
Pod putting host at the end of the pod name sucks because it's harder to cut and paste
Better pod names for build, deploy (make unique with shorter names)

**Comment by smarterclayton** [comment]
We were not capturing events, and now we are.  Should see them now.

**Comment by smarterclayton** [comment]
It's still rough around the edges, because you have to specify the types you want deleted.  Also, it'll leave pods behind.

**Comment by smarterclayton** [comment]
Yeah, this.  The template author *can* do it, but it's not obvious.

**Comment by danmcp** [comment]
Anything left to do here?

**Comment by smarterclayton** [comment]
This is pretty close to all done.
