### ISSUE TITLE
Our deployment controllers need to stop using special cased interfaces

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#7190]
After digging a lot around our deployment controllers I have fully sympathized with @deads2k's request for this. Let the world know

cc: @ironcladlou

**Comment by deads2k** [comment]
> Let the world know

:)

I'm pretty sure that last we left it @ironcladlou was ok with passing namespacers through instead, but we weren't going to rewrite until we needed to touch them signficantly again.

**Comment by kargakis** [comment]
I once started reworking them but the bulk of the work is in the tests, they are massive... and I quit..

**Comment by ironcladlou** [comment]
I've been using the fake clients for all new code. No objection to refactoring as you come across stuff...

**Comment by kargakis** [comment]
@danmcp I think this is at most P3
