### ISSUE TITLE
consolidate error handling in ldap sync to single error handler approach

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#7191]
Once the error handler in https://github.com/openshift/origin/pull/6834 is in, we should refactor the other error handling features of our LDAP sync to use it, so that we can ensure that any errors that bubble to the top of the sync job are errors we should be failing on, and so that we ensure that we are logging any errors we do not consider fatal.

/cc @liggitt

**Comment by deads2k** [comment]
This kind of consistency isn't a priority.  Most errors are just plain errors.  Having been down this path, wrapping every kind of error in a handler is not generally worth the effort.  You're better off targeting a few spots with the same interface.

See our limited usage `util.HandleError` as an example.  Most errors just fail, a few are special snowflakes.

**Comment by stevekuznetsov** [comment]
Not debt that is worth tackling.

/close
