### ISSUE TITLE
master.server.crt in multi master setup does not contain expected CN

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/origin#7196]
I dont think this is a problem but did notice it while researching and tackling a different issue. The master.server.crt contains the CN of one of my masters as an IP rather than what I would have expected and have my lb hostname or at the very least my public_hostname. The SAN contains... well everything including the lb and both masters hostnames and their IPs.

Either way, not sure that it is explicitly a problem, just seems like "not the right thing"

**Comment by liggitt** [comment]
can you move this issue to the openshift-ansible repo? I think the CN is the first hostname passed to the create-master-certs command, which is up to the ansible scripts

**Comment by ebalsumgo** [comment]
Yep. Will do
