### ISSUE TITLE
Border on .ace_editor within .modal looks janky

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin#7201]
Currently, .ace_editor is set to have a border around it per https://github.com/openshift/origin/blob/master/assets/app/styles/_core.less#L900.  When put inside a .modal, this border looks a bit janky.

![screen shot 2016-02-10 at 2 33 45 pm](https://cloud.githubusercontent.com/assets/895728/12959250/a9a5b5e0-d003-11e5-8701-d3f0ccdff90e.PNG)

I propose we remove the border any time an .ace_editor is within a .modal.

![screen shot 2016-02-10 at 2 34 03 pm](https://cloud.githubusercontent.com/assets/895728/12959279/c063396a-d003-11e5-8a2a-3a86b8a171a0.PNG)

**Comment by rhamilto** [comment]
Proposed fix:  https://github.com/openshift/origin/compare/master...rhamilto:ace-editor-modal?expand=1

**Comment by jwforres** [comment]
@rhamilto yes, open the PR
