### ISSUE TITLE
No validation on create / update that the route's service is within the same namespace

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#7204]
The logic under the covers is making the assumption that the service referenced in the To field is in the namespace, but nothing in the validation actually prevents you from posting an object that points to another namespace.  The service lookup happens against the route's namespace no matter what you specify.

**Comment by jwforres** [comment]
cc @liggitt

**Comment by liggitt** [comment]
both f5 and template routers ignore the service ref namespace. @smarterclayton should we change this to a localobjectreference (possibly orphaning data in etcd) or change defaulting/validation to allow namespace but default it to the current namespace and prohibit cross-namespace routes (for now)?

**Comment by smarterclayton** [comment]
I don't think we'll ever support cross namespace routes.  Do we need
to change something here other than document it is ignored?  Not
returning a field anymore is not backwards compatible.

**Comment by liggitt** [comment]
it's omitempty, so unless someone put a value in it, we've never returned it

**Comment by smarterclayton** [comment]
Ok, then let's drop it silently and hope no one is using it to store secrets.
