### ISSUE TITLE
oc rsh showing stdin errors

### ISSUE THREAD

**Issue by cjryan** [openshift/origin#7208]
When running any 'oc rsh' command, the following error is observed. The command will execute successfully, despite the error. 
```
 oc rsh  --config=<kubeconfig> doublecontainers
 E0210 21:42:53.742942   10166 v2.go:116] read /dev/stdin: resource temporarily unavailable

oc rsh  --config=<kubeconfig>  doublecontainers ls
E0210 21:42:59.816479   10192 v2.go:116] read /dev/stdin: resource temporarily unavailable
      bin
      dev
      etc
      hello-openshift
```
The current setup is:
      oc version
      oc v3.1.1.6
      kubernetes v1.1.0-origin-1107-g4c8e6f4

To setup the testing environment, create a pod in a project using this json file:
https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/pods/pod_with_two_containers.json

**Comment by ncdc** [comment]
On what OS are you running `oc rsh`?

**Comment by cjryan** [comment]
Sorry, it's Fedora 23, 4.3.3-300.fc23.x86_64

**Comment by ncdc** [comment]
This works for me on Fedora 23 from commit 4d1c1ba. Did you run out of available file descriptors, perhaps? (ulimit -n)

**Comment by akostadinov** [comment]
@cjryan, are you running `oc rsh` manually or through script? Perhaps stdin is closed.

**Comment by cjryan** [comment]
@akostadinov @ncdc This was an issue with how I was testing; this is not an oc rsh issue as far as I can tell. Thanks!
