### ISSUE TITLE
Easy Github Webhook Configuration

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7217]
When I create a new BC with a GitHub trigger, I'd like to have a message :

Don't forget to add this webhook URL : https://<server>.axaxx.nu:8443/oapi/v1/namespaces/foo/buildconfigs/foo/webhooks/mkjakrkp/github by going to : https://github.com/foo/bar/settings/hooks/new

Given the Git URI, it should be possible to determine the new hook URL.

**Comment by mfojtik** [comment]
@YannMoisan it is possible to add that message to `oc new-build` and `oc new-app`, but not to generic create BC. Also it might be possible to show this in web console @jwforres ?

**Comment by jwforres** [comment]
@YannMoisan unrelated issue but i see your webhook URL has a double slash in it, do you remember where you copied it from?

**Comment by jwforres** [comment]
In the console after you create a new app from builder + source, the Next Steps page has a section that tells you to set up your webhooks and links to our docs.  I hesitate to put more github specific URL building into the code, if GitHub goes and changes their URL patterns for their web UI in the future we would have to patch a lot of old releases with the new URL pattern.

**Comment by liggitt** [comment]
Agree, the fewer deep links to sites outside our control, the better

**Comment by YannMoisan** [comment]
@jwforres 

I create my project with the CLI. So adding that message to `oc new-app` is perfect. 

Otherwise, don't worry about the double slash, it's result for a manual change.

**Comment by YannMoisan** [comment]
@liggitt I understand your point

In the case of GitHub :
- OpenShift provides an explicit GitHub hook and I guess that the code depends on the payload returns by GH.
- Some concurrent PaaS provides a seamless integration with GH. so it's becoming a de-facto standard.

**Comment by liggitt** [comment]
I'm referring to the URL on the github website where you set up the web hooks (https://github.com/foo/bar/settings/hooks/new). That's not part of any API, or something we can depend on not changing.

**Comment by YannMoisan** [comment]
[Creating a Web Hook](https://developer.github.com/webhooks/creating/) by calling the GH API or providing the curl command is also an option.

**Comment by liggitt** [comment]
Sure, but that requires an active github oauth access token, which the OpenShift web console or CLI will not have

**Comment by YannMoisan** [comment]
For the web console, it could be an integration like the one on Docker Hub.
For the cli, it could be an optional param `gh-token`. If provided, `oc`
configure the webhook automatically.
wdyt ?

**Comment by liggitt** [comment]
the web console can't make cross-domain API requests unless explicitly allowed by the remote site because of cross-origin request limitations in browsers.

For the CLI, I'm not sure... is it easier to create a token on github.com and bring it to the OpenShift CLI or to take the webhook URL from OpenShift to github?

**Comment by jwforres** [comment]
This is already being tracked in trello https://trello.com/c/Ee0tlHwo
