### ISSUE TITLE
Automated publishing of origin/master rpms to copr repos.

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#7219]
Currently there are about 1/2 dozen folks who are hand building rpms and custom configuring repos for deploys for clusters against origin/master for performance evaluation and testing.   (rpms) are the most trusted+tested mechanism to deploy using the installer.  

Everyone agrees this should be automated and we should just properly version the .rpms and point our installers at a maintained copr repo by the org. 

/cc @jayunit100 @jeremyeder @brenton @detiber @sdodson

**Comment by jeremyeder** [comment]
This will save millions of kittens.

**Comment by jeremyeder** [comment]
@maxamillion

**Comment by timothysc** [comment]
xref: 6891 - as version-collide-itis-osis

**Comment by brenton** [comment]
@tdawson is working to have Origin built in CentOS which would make an RPM-based distribution easier to consume.  @smarterclayton, would you be OK with bumping the origin.spec whenever new releases are made?

I'm sure in the meantime we could keep the copr up to date until CentOS builds are available.

**Comment by sdodson** [comment]
> Everyone agrees this should be automated and we should just properly version the .rpms and point our installers at a maintained copr repo by the org.

This wasn't the case when we originally added the spec file, much to my dismay. So it's news to me that there's wide agreement on this.

**Comment by rrati** [comment]
I think there will always been a need to be able to install newer rpms than whatever the latest ones in a copr or other repo.  Whichever path we go down we should provide a means to disable installing our repo so a custom repo can be provided in the inventory file.

**Comment by brenton** [comment]
There's also the issue of building the Origin images from the RPMs.  We would love to upstream all the things we do buildwise for OSE but, to @sdodson's point, months ago there was disagreement on whether it was appropriate for Origin or not.  I think now that CentOS is a target for Origin we should be able to move forward with providing an accurate specfile and Dockerfiles and build script for locally building everything from source and yielding images built from RPMs.

**Comment by jayunit100** [comment]
+1000 we need to 
- test from source 
- on a cluster 
- from head
- reproducibly
- using identical deployment that is used in prod

This means we need

- hosted
- accessible from outside a vpn
- up to date 

 in order to accomplish most of the stuff that we care about with confidence

**Comment by brenton** [comment]
@jayunit100, @arilivigni is working on updates to vagrant-openshift that would handle what you need.  Namely, you run a command to build RPMs from source.  It yields a local yum repo that is then used when you run the vagrant command to build all the images.  What we're missing is to finish that plugin update and then push the Dockerfiles/spec changes to Origin.

**Comment by brenton** [comment]
@smarterclayton, I'm pretty sure we can do what I'm describing without complicating the lives for people who prefer the current non-rpm dev workflow.  Are you OK with pushing specfile updates and the Dockerfiles to Origin?  We'd push the vagrant-openshift plugin updates at the same time along with docs on why someone might want to use the RPMs.

**Comment by smarterclayton** [comment]
I'm not opposed to the updates, but they'll need to go through review and
we can sort out technical issues there.

**Comment by usawa** [comment]
Hi,

A few minutes ago, I opened this issue : https://github.com/openshift/origin/issues/7268

but this one seems very close, thanks to @timothysc (for this issue and your answer to my email). I totally agree with your proposal. Anyway, how to rebuild "old" releases that were removed from maxamillion copr repository ?

**Comment by brenton** [comment]
@sdodson, do you know if this is mostly satisfied by the content Troy is pushing to CentOS?

**Comment by sdodson** [comment]
I think so, however I don't think that process is automated.

**Comment by tdawson** [comment]
The CentOS process is *not* automated.
We are still manually creating the rpm's.  We're also still working on the testing.  The testing is closer than the automated building though.

**Comment by stevekuznetsov** [comment]
We've got a pretty solid stream for RPMs going to the CentOS PaaS SIG repos today. This is finished.
