### ISSUE TITLE
Add subject whitelist to PodNodeConstraints plugin

### ISSUE THREAD

**Issue by dobbymoodge** [openshift/origin#7225]
https://github.com/openshift/origin/pull/6979/

In the near future, I'd like to add a whitelist to the types for this plugin so that users (e.g. cluster-admin) can specify nodeName/nodeSelector when it is prohibited by policy for all other users.

@wshearn @twiest @deads2k

**Comment by deads2k** [comment]
@wshearn  @twiest Is this a feature you'd find useful?  If you don't have it, you'd have to create a separate project that pins pods to particular node every time you needed to run a pod on that node.

/cc @csrwng

**Comment by smarterclayton** [comment]
I don't want us hardcoding a list of users in config.  I might buy a group.

**Comment by deads2k** [comment]
> I don't want us hardcoding a list of users in config. I might buy a group.

Using `Subjects` would keep us consistent with policy, allow groups as a best practice, but does not preclude users.

**Comment by smarterclayton** [comment]
Fine with that.

**Comment by twiest** [comment]
@deads2k The only thing we really need is a "run on every single node."

If this helps with that, then yeah, it'd be useful.

**Comment by deads2k** [comment]
> @deads2k The only thing we really need is a "run on every single node."
> 
> If this helps with that, then yeah, it'd be useful.

Nope, "run on every single node" is a daemon set which hopefully still works.

**Comment by liggitt** [comment]
does daemonset use bindings to assign to nodes, or direct nodeName assignment?

**Comment by liggitt** [comment]
looks like daemonsets use direct assignment (https://github.com/openshift/origin/blob/0c73141d361dfca8ea626e0083e2eb210d63dac0/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/controller_utils.go#L319), so preventing node names in the admission controller breaks them

**Comment by deads2k** [comment]
@dobbymoodge Add a test for your pull.

**Comment by dobbymoodge** [comment]
@deads2k will do tomorrow

**Comment by dobbymoodge** [comment]
This issue is no longer relevant, so closing.
