### ISSUE TITLE
[POST_REBASE] numeric ordering of `oc get pods` output

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7229]
It will be nice to have a numerically ordered output for `oc get pods` :

Here is the current output :

```
foobar-1-build
foobar-10-build
foobar-2-build
foobar-3-build
```

**Comment by ravisantoshgudimetla** [comment]
@fabianofranz : I will pick this up and let you know, if I need some  help.

**Comment by fabianofranz** [comment]
@ravisantoshgudimetla sounds good, tks!

**Comment by matthyx** [comment]
@ravisantoshgudimetla will you be using an external library for natural sorting? There are several out there... Also, I think if you use that kind of sort, it could be generalized in all sorted outputs, not only in "oc get pods". Tks!

**Comment by matthyx** [comment]
I have created a pull request for that directly in kubernetes:
https://github.com/kubernetes/kubernetes/pull/40746

**Comment by matthyx** [comment]
Do you know how I can make people look at my PR in kubernetes? My first issue was a breeze because it had a duplicate there as well, but now nobody seems interested in having natural sorting...

**Comment by matthyx** [comment]
@fabianofranz  my PR has finally been merged. You can close this issue.

**Comment by fabianofranz** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/40746, waiting for the next Kube rebase.
