### ISSUE TITLE
Text-only pages should have a white background instead of a gray one?

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin#7230]
Should pages like 

![next-steps-gray](https://cloud.githubusercontent.com/assets/895728/12986345/c4605900-d0c4-11e5-8310-d4190e96560e.png)

use a white (or lighter) background instead to improve the legibility of the text and overall appearance of the page?

![next-steps-white](https://cloud.githubusercontent.com/assets/895728/12986361/dc2a6c38-d0c4-11e5-9afb-62c52ad8a3b7.png)

cc:  @jwforres, @spadgett, @benjaminapetersen, @sg00dwin

**Comment by jwforres** [comment]
cc @ajacobs21e

**Comment by luciddreamz** [comment]
+1

**Comment by benjaminapetersen** [comment]
Fits the new theme better, though something about the grey background makes the page feel a bit more structured to me.  Not sure why...

**Comment by ajacobs21e** [comment]
@rhamilto a status type page like this looks like empty state to me https://www.patternfly.org/patterns/empty-state/

which also uses the grey background

**Comment by luciddreamz** [comment]
I think the improved structure above is (at least partially) an illusion created by the white background the images are pasted on.

Here they are with a browser window framing them:

![console_gray](https://cloud.githubusercontent.com/assets/928421/12987752/87d519b0-d0cb-11e5-807a-6076ab35dc54.png)

![console_white](https://cloud.githubusercontent.com/assets/928421/12987757/8db08ffe-d0cb-11e5-9ba5-491a4fdd261a.png)

**Comment by benjaminapetersen** [comment]
Fair enough on the browser window frame, I can roll with that.

Per @ajacobs21e, I tend to agree. I'd rather "Go to overview" be a main action button like in the [empty state page](https://www.patternfly.org/patterns/empty-state/).

**Comment by rhamilto** [comment]
> @rhamilto a status type page like this looks like empty state to me https://www.patternfly.org/patterns/empty-state/
>
> which also uses the grey background

Where they differ is empty state is a gray box put on a white background, which plays in to the comments about "structure" by @luciddreamz.

**Comment by ajacobs21e** [comment]
@rhamilto I didn't realize empty state was a grey box on white background. That's good feedback to give to Leslie - showing the patterns in context & with a browser window frame like Jacob posted would help a lot. 

@benjaminapetersen something like this?
[NextSteps.pdf](https://github.com/openshift/origin/files/128633/NextSteps.pdf)

**Comment by benjaminapetersen** [comment]
Yup!

**Comment by rhamilto** [comment]
Now that the next steps page only briefly displays before redirecting to the overview, I'm inclined to think this is less of an issue now and am closing the issue.
