### ISSUE TITLE
admission attribute comparison must take into account group

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#7231]
Admission attributes recently became group aware, so https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/admission/interfaces.go#L35 and https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/admission/interfaces.go#L45 return partially qualified types.

We need to sweep every call to those methods and make sure that any comparison is also group aware and restricting.  Already found one bug as a for instance: https://github.com/openshift/origin/blob/master/pkg/security/admission/admission.go#L98 .

@legionus Want to take a shot?  gooracle or vscode would be very useful for tracking these down.

**Comment by legionus** [comment]
I'll try!

**Comment by legionus** [comment]
Maybe I something did not understand, but I didn't find any more comparisons.

**Comment by deads2k** [comment]
> Maybe I something did not understand, but I didn't find any more comparisons.

I didn't check any further.  Saw one, so we needed to check them.  Now we'll enforce through reviews.
