### ISSUE TITLE
Recycler pod is failing

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/origin#7235]
I have a number of PVs loaded up and I just released one of them and it ended up in Failed state with the following error:
----> oc describe pv pv0f32cf87
Name:		pv0f32cf87
Labels:		size=2Gi,type=localnfs
Status:		Failed
Claim:		openshift-infra/metrics-cassandra-1
Reclaim Policy:	Recycle
Access Modes:	RWO,RWX
Capacity:	2Gi
Message:	Recycling error: Unexpected error creating recycler pod:  Pod "pv-recycler-hostpath-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.containers[0].securityContext.securityContext.runAsUser: invalid value '0', Details: UID on container pv-recycler does not match required range.  Found 0, required min: 1000000000 max: 1000009999 provider restricted: .spec.containers[0].securityContext.VolumeMounts: invalid value 'vol', Details: Host Volumes are not allowed to be used]

The PV is UserPath based and is loaded up in a NFS volume shared between all my nodes

**Comment by ebalsumgo** [comment]
I am trying to dig through my masters (i have 2) logs to see if they have anything more than that.

**Comment by ebalsumgo** [comment]
This is what the template we use to generate the PVs that we use look like:
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{PVNAME}"
  labels:
    type: localnfs
    size: {XGI}
spec:
  capacity:
    storage: {XGI}
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/{PVROOT}/{PVNAME}/"
  persistentVolumeReclaimPolicy: Recycle

The path is a group of NFS volumes which are mounted on all my masters/nodes and all masters/nodes have access to

**Comment by liggitt** [comment]
Dupe of https://github.com/openshift/origin/issues/6883 and https://bugzilla.redhat.com/show_bug.cgi?id=1293805 I think

Fixed in https://github.com/openshift/origin/pull/6884

**Comment by ebalsumgo** [comment]
That does seem to be quite the exact same issue. I will run the suggested SCC changes and see what happens.

**Comment by ebalsumgo** [comment]
I just ran through the @rjhowe instructions and things seem to be better. I am gonna close the issue
