### ISSUE TITLE
Web console: make live reload optional

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#7236]
With the last fix enabling live reload I realize that I occasionally like to compare changes across a couple tabs, but this is no longer possible. I'd like to update `hack/serve-local-assets.sh` and `Gruntfile.js` to make live-reload optional.  

Its been a while so I'll have to lookup how you pass args to grunt tasks but I'm thinking something along the lines of:

```
// make separate tasks?
grunt serve
grunt serve-live 
grunt serve --live_reload

// arg to the script?
hack/serve-local-assets.sh live-reload

// etc.
```

@jwforres @spadgett @sg00dwin @rhamilto thoughts?

**Comment by jwforres** [comment]
+1 should do something, will think about the options tmrw
