### ISSUE TITLE
Support for deletion of all projects starting with

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7237]
I use one project by environment, so I have

```
foobar-int
foobar-preprod
foobar-prod
```

I search a way to delete them all, e.g. a command like `oc delete project "foobar*"`.

My current workaround is `oc get project -o json | jq '.items[].metadata.name' | grep foobar | xargs oc delete project`

**Comment by liggitt** [comment]
Could you label the projects, and use a label selector to delete them?

**Comment by YannMoisan** [comment]
@liggitt How can I label the projects ?

`oc new-project` doesn't seem to support `-l`

**Comment by liggitt** [comment]
Yeah, labels would have to be on the underlying namespaces :-/

The resource builder bits (the part that turns arguments to `oc {create|get|delete|update} ...` into a specific list of resources are unlikely to support globbing 

Cross-project-but-not-all-projects actions aren't supported at all by the API. I'm not sure what the best way to deal with those would be

**Comment by vbehar** [comment]
how about supporting `oc delete project p1,p2` and then we could hack the completion (https://github.com/chmouel/oh-my-zsh-openshift ;-) to expand `oc delete project p*` to `oc delete project p1,p2` ?

**Comment by deads2k** [comment]
> how about supporting oc delete project p1,p2

It supports `oc delete project p1 p2` already.  Will that do?

**Comment by vbehar** [comment]
oh yes, I mixed up the syntax! Yes, I think we can do something with the completion, it should be enough for our use case. Thanks

**Comment by smarterclayton** [comment]
`oc get projects -o name | grep -E '^foobar' | xargs oc delete` is what I use today

**Comment by sethgagnon** [comment]
Did anyone get a script working for this? I tried the following command from a bash terminal:
oc get projects -o name | grep -E '^seth' | xargs oc delete project

but I get the following error:
$ oc get projects -o name | grep -E '^seth' | xargs oc delete project
error: resource(s) were provided, but no name, label selector, or --all flag specified

**Comment by liggitt** [comment]
probably need `xargs -n1 ...`

**Comment by sethgagnon** [comment]
Can anyone provide a little help on this? Greatly appreciated!
