### ISSUE TITLE
e2e tests should do a sanity check before pushing artifacts to jenkins

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#724]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_openshift3/792/artifact/origin/artifacts/e2e/logs/

Note the size of openshift.log.....

**Comment by smarterclayton** [comment]
Ben can you find a victim for this?

**Comment by smarterclayton** [comment]
@danmcp we probably need to clean jenkins up too.

**Comment by bparees** [comment]
https://github.com/openshift/origin/pull/726

**Comment by smarterclayton** [comment]
Fixed
