### ISSUE TITLE
No filter on build config or deployment config page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7240]
No filter on these pages even though they have tables that can be filtered.

<img width="812" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/12996406/7fb35a30-d0fd-11e5-9b9c-7453af11db2a.png">

/cc @jwforres @sg00dwin

**Comment by jwforres** [comment]
@ajacobs21e where would you expect the patternfly table toolbar to go on a page like this, where the table is beneath othe content. The table only appears on the first Summary tab.

**Comment by spadgett** [comment]
@ajacobs21e Note on this page, the filter affects the chart. The deployment config page is a bit different.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13010838/f6f69caa-d171-11e5-87dc-c9ffdd378fad.png)

**Comment by spadgett** [comment]
Marking a P2 bug since this is a regression.

**Comment by ajacobs21e** [comment]
I am working on this

**Comment by jwforres** [comment]
QE opened a bug as well https://bugzilla.redhat.com/show_bug.cgi?id=1309557
this needs to be fixed for 1.2

**Comment by ajacobs21e** [comment]
![embeddeddatalist](https://cloud.githubusercontent.com/assets/6415742/13154725/64660f8e-d648-11e5-9e4f-cea58fae7400.png)
This is the design solution I worked on with the UXD / PatternFly visual design team. It brings the data list filter toolbar to the list when it's one embedded element of the page. Currently the only example is when the data list is the only page element.

**Comment by ajacobs21e** [comment]
the short term fix though would be to add the filter row to the table
![screen shot 2016-02-18 at 2 11 18 pm](https://cloud.githubusercontent.com/assets/6415742/13154996/9cfb5448-d649-11e5-804a-1e5f7acf20c6.png)

https://www.patternfly.org/patterns/table-view/
