### ISSUE TITLE
Proxy API not functioning when master is not also a node

### ISSUE THREAD

**Issue by SillyMoo** [openshift/origin#7253]
When the master is not also a node then the API:

```
https://${KUBERNETES_MASTER}/api/v1/proxy/namespaces/{namespace}/services/{service}/...
```

Does not function, timing out with errors such as

```
curl -k -H "Authorization: Bearer JbMAKFt3dfsDaQ46uZy6B6SIThrftTcirVbcY-IXPZg" https://10.245.2.2:8443/api/v1/proxy/namespaces/openshift-infra/services/https:heapster:/validate
```

Steps to reproduce:
Configure using openshift-ansible a system with one master and one or more nodes (not the master must not be a node), using the openshift-sdn. Install openshift-metrics (heapster only is fine) as described at: https://github.com/openshift/origin-metrics. Then try and connect to the API as described in the curl above.

Workaround:
If you make the master be a (non-schedulable) node then the proxying works, suggesting this is an openshift-sdn configuration related issue.

**Comment by mwringe** [comment]
@SillyMoo with the new Heapster version I don't believe there is a validate endpoint anymore.

Can you try the `/api/v1/model/metrics` endpoint? That should return something
````
curl --insecure -H "Authorization: Bearer `oc whoami -t`" -X GET https://${HOST}:8443/api/v1/proxy/namespaces/openshift-infra/services/https:heapster:/api/v1/model/metrics
````

**Comment by SillyMoo** [comment]
@mwringe Same problem I'm afraid. 30s of nothing and then:

Error: 'dial tcp 10.1.0.2:8082: i/o timeout'
Trying to reach: 'https://10.1.0.2:8082/api/v1/model/metrics'

This does not happen when the master is also a node.

**Comment by DirectXMan12** [comment]
I think this is a quirk of the openshift-sdn behavior (which is why, IIRC, we specify in the docs that you should list the master as an unschedulable node).

someone from @openshift/networking can probably confirm that.

**Comment by DirectXMan12** [comment]
(basically, IIRC, in order to talk to the node IPs, the master has to be part of the SDN)

**Comment by knobunc** [comment]
https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/sdn.html#sdn-design-on-masters

"Note that OpenShift SDN on a master does not configure the local (master) host to have access to any cluster network. Consequently, a master host does not have access to containers via the cluster network, unless it is also running as a node."

That also means that you won't be able to reach the service IP addresses unless you are running node software on the masters.  (Just mark the node as unschedulable if you don't want to run pods there)

**Comment by SillyMoo** [comment]
Ah thanks @knobunc, I think I missed that bit, or it wasn't in the docs when I started with openshift. Please feel free to close this issue.
