### ISSUE TITLE
Firefox unresponsive with large number of builds ~400

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#7255]
Running OSE 3.1.1 on stage cluster

Project: sspeiche-nodejs
To reproduce, I just logged in and when to overview page. Then got this error.

```
➜  ~  oc get build | wc -l
     493
```

![screen shot 2016-02-12 at 8 32 59 am](https://cloud.githubusercontent.com/assets/727196/13008275/5ddd9130-d163-11e5-974c-54cc2282b29e.png)

/cc @spadgett

**Comment by jwforres** [comment]
My initial suspicion would be something in the code that associates builds
to images to dep config triggers.

**Comment by liggitt** [comment]
This probably isn't limited to builds... 500 of anything isn't going to be stellar, especially with no paging or filtering in the API. Not sure I'd consider this a p1

**Comment by spadgett** [comment]
68% of overview CPU usage is in `DeploymentsService.getActiveDeployment`.

**Comment by jwforres** [comment]
ahh all these builds also triggered deployments, ok.  seems like there is
probably *something* we can fix there

**Comment by spadgett** [comment]
`getActiveDeployment` has to sort the list to find the most recent successful deployment, which is where the time is spent. It's called on any pod, rc, or service update in overview.js.
