### ISSUE TITLE
registry : Liveness probe failed with TLS

### ISSUE THREAD

**Issue by jfcoz** [openshift/origin#7257]
I've follow this documentation to upgrade registry in https :

https://docs.openshift.com/enterprise/3.0/install_config/install/docker_registry.html#securing-the-registry

Since that the registry is always restarting due to :+1: 
`Unhealthy 	Liveness probe failed: Get http://10.1.1.5:5000/healthz: malformed HTTP response "\x15\x03\x01\x00\x02\x02" (24 times in the last 3 minutes, 50 seconds) `

How can I upgrade liveness probe to https ?

Thank

**Comment by liggitt** [comment]
Docs are on https://docs.openshift.org/latest/install_config/install/docker_registry.html#securing-the-registry but haven't propagated to the enterprise doc yet:
```
Update the scheme used for the registry’s liveness probe from HTTP to HTTPS:
$ oc get dc/docker-registry -o yaml \
    | sed -e 's/scheme: HTTP/scheme: HTTPS/g' \
    | oc replace -f -
```

**Comment by liggitt** [comment]
Or use patch:
```
oc patch dc/docker-registry --api-version=v1 -p '{
  "spec": {
    "template": {
      "spec": {
        "containers":[{
          "name":"registry",
          "livenessProbe": {"httpGet": {"scheme":"HTTPS"}},
          "readinessProbe":{"httpGet": {"scheme":"HTTPS"}}
        }]
      }
    }
  }
}'
```

**Comment by jfcoz** [comment]
It works, thanks !
