### ISSUE TITLE
Overview page does not reflect correct Build # that is deployed

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/origin#7264]
I just noticed this, but the build # is not correct on the overview page vs what the actual latest build that should be running/is running, is. This is in OSE 3.1.1
![overview](https://cloud.githubusercontent.com/assets/5804477/13017020/2742eeb8-d190-11e5-9d99-da8240fb7ee4.png)
![builds](https://cloud.githubusercontent.com/assets/5804477/13017024/2db7d1f0-d190-11e5-974c-aed2e21b2a32.png)
![builds2](https://cloud.githubusercontent.com/assets/5804477/13017025/2ff7ba16-d190-11e5-88b4-992456cbd95d.png)

**Comment by spadgett** [comment]
Does this command show the right build?

```
$ oc describe istag/lab1:latest | grep OPENSHIFT_BUILD
```

**Comment by spadgett** [comment]
And does the `oc describe istag/lab1:latest` name have `sha256:89d171a`...?

**Comment by liggitt** [comment]
is this the imagestreamtag API issue that got fixed?

**Comment by ebalsumgo** [comment]
----> oc describe istag/lab1:latest | grep OPENSHIFT_BUILD
Environment:	OPENSHIFT_BUILD_NAME=lab1-6

Name:		sha256:a61ca1ed952....

**Comment by spadgett** [comment]
The web console believes you have a different image deployed. `oc describe rc lab1-9` should show a hash other than `sha256:a61ca1e`

What triggers are set with `oc describe dc lab1`?

**Comment by ebalsumgo** [comment]
----> oc describe dc lab1
Name:		lab1
Created:	2 days ago
Labels:		app=lab1
Annotations:	openshift.io/generated-by=OpenShiftWebConsole
Latest Version:	9
Triggers:	Image(lab1@latest, auto=true), Config
Strategy:	Rolling
Template:
  Selector:	deploymentconfig=lab1
  Replicas:	1
  Containers:
  NAME	IMAGE													ENV
  lab1	172.30.17.65:5000/sbr/lab1@sha256:a61ca1ed952df11d79a65b4d4170c8a0af09b08a0890dcd558d10b2bb2d08c51	MYSQL_DATABASE=sampledb,MYSQL_PASSWORD=u24vbTBjsscMB6fb,MYSQL_USER=user1ED
Deployment #9 (latest):
	Name:		lab1-9
	Created:	2 days ago
	Status:		Complete
	Replicas:	1 current / 1 desired
	Selector:	deployment=lab1-9,deploymentconfig=lab1
	Labels:		app=lab1,openshift.io/deployment-config.name=lab1
	Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Deployment #4:
	Created:	2 days ago
	Status:		Complete
	Replicas:	0 current / 0 desired
No events.

**Comment by ebalsumgo** [comment]
It is for sure running the latest build because the code changes I am making are getting pushed out

**Comment by spadgett** [comment]
Sorry to ask for all these commands. Still tracking this down...

One more:

```
oc get rc lab1-9 -o jsonpath="{.spec.template.spec.containers[0].image}"
```

This is how the web console finds the image hash shown in the dotted-line pod template. If that doesn't match `89d171a`, it would explain the problem.

**Comment by ebalsumgo** [comment]
----> oc get rc lab1-9 -o jsonpath="{.spec.template.spec.containers[0].image}"
172.30.17.65:5000/sbr/lab1@sha256:a61ca1ed952df11d79a65b4d4170c8a0af09b08a0890dcd558d10b2bb2d08c51

**Comment by jwforres** [comment]
This was fixed in https://github.com/openshift/origin/pull/6945  it was an API issue.  Believe this was added as a hotfix for the 3.1.1.x branch but you can confirm with @smarterclayton

**Comment by smarterclayton** [comment]
Yes
