### ISSUE TITLE
Deployment violates guarantees when a new deployment is started in the middle

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7270]
Scenario: 

* set up the router with scale 2 (disable host ports and host network, use a service)
* start a load benchmark against the service
* edit the deployment to have something that blocks two pods being brought up (host ports)
* deployment starts, scales down to 1, waits for the second pod which can't happen because of host ports
* edit the deployment to fix the blocking behavior
* new deployment starts and scales down to 0, then back up to 1

This should *never* happen - the deployment should be set back to 2, then the next deployment should scale it down.

This is a very serious issue because it violates the guarantees the deployment is supposed to provide.

**Comment by smarterclayton** [comment]
we probably need to verify the order of events - whether it's a race between the controllers, or just a logical gap because the new deployment is halfway through.  Might be a bug with the deployment scale annotations as well.

**Comment by kargakis** [comment]
maxSurge == 0, maxUnavailable == 1? I am surprised that the rolling updater didn't scale up first.

**Comment by kargakis** [comment]
Using my latest changes in the rolling updater
```sh
# Server returns:
# E0216 11:50:15.577455    4942 factory.go:340] Error scheduling default router-1-9wyod: pod (router-1-9wyod) failed to fit in any node
# fit failure on node (localhost.localdomain): PodFitsHostPorts
# ; retrying
[vagrant@localhost sample-app]$ oc get pods
NAME                      READY     STATUS    RESTARTS   AGE
docker-registry-2-0wfjy   1/1       Running   0          3m
router-1-9wyod            0/1       Pending   0          9s
router-1-at75y            1/1       Running   0          1m
# edit hostPorts out
[vagrant@localhost sample-app]$ oc edit dc/router
deploymentconfig "router" edited

# Rolling update never falls to zero
[vagrant@localhost sample-app]$ oc logs -f dc/router
I0216 11:51:51.842807       1 deployer.go:201] Deploying from default/router-1 to default/router-2 (replicas: 2)
I0216 11:51:52.896709       1 rolling.go:228] RollingUpdater: Continuing update with existing controller router-2.
I0216 11:51:52.931932       1 rolling.go:228] RollingUpdater: Scaling up router-2 from 0 to 2, scaling down router-1 from 2 to 0 (keep 1 pods available, don't exceed 2 pods)
I0216 11:51:54.944867       1 rolling.go:228] RollingUpdater: Scaling router-1 down to 1
I0216 11:51:56.992648       1 rolling.go:228] RollingUpdater: Scaling router-2 up to 1
I0216 11:52:19.221601       1 rolling.go:228] RollingUpdater: Scaling router-1 down to 0
I0216 11:52:21.327165       1 rolling.go:228] RollingUpdater: Scaling router-2 up to 2

# now probes are failing
[vagrant@localhost sample-app]$ oc get pods
NAME                      READY     STATUS    RESTARTS   AGE
docker-registry-2-0wfjy   1/1       Running   0          6m
router-2-qqjkk            0/1       Running   2          1m
router-2-xp0l4            0/1       Running   1          50s
```
I don't see the unhealthy pods going down though, still need to fix that.
