### ISSUE TITLE
Invalid liveness and readiness check completely blocks deployments:

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7271]
Scenario:

* start two router pods with host network off that have liveness and readiness checks pointing to localhost , which then never become ready and periodically fail (because the readiness check never succeeds)
* edit the deployment so the readiness and liveness checks are correct (remove localhost)

Expect deployment to run.  Instead, deployment wedges forever (because old pods aren't ready?)

```
$ oc get pods
NAME              READY     STATUS    RESTARTS   AGE
router-8-cljzi    0/1       Running   53         8h
router-8-jokg4    0/1       Running   32         8h
router-9-deploy   1/1       Running   0          8h
```

```
$ oc logs dc/router -f
I0212 14:31:53.419613       1 deployer.go:193] Deploying from default/router-8 to default/router-9 (replicas: 2)
I0212 14:31:54.466269       1 rolling.go:232] RollingUpdater: Continuing update with existing controller router-9.
I0212 14:31:54.484749       1 rolling.go:232] RollingUpdater: Scaling up router-9 from 0 to 2, scaling down router-8 from 2 to 0 (keep 1 pods available, don't exceed 2 pods)
```

Pod state
[pods.txt](https://github.com/openshift/origin/files/128848/pods.txt)

**Comment by kargakis** [comment]
I think this is because the upstream rolling updater doesn't care if new pods are ready. It should probably wait for every scale up to become ready, otherwise the scale up should be considered as a failure.

**Comment by kargakis** [comment]
This got me thinking if we should move away from the kubectl rolling updater. Upstream deployments don't use it and apart from `kubectl rolling-update` which is now superceded by Deployments, we are the only users of it. Any thoughts @ironcladlou ?

**Comment by kargakis** [comment]
Or instead of touching the rolling updater we could check for readiness once a deployment is marked as complete and if ready doesn't match desired, then fail the deployment?

**Comment by smarterclayton** [comment]
As discussed on IRC, if we the deployment process is blocked because we
can't surge (because the old pods exist), can't scale up (because that
would create more new pods than asked for), we have to delete old-unready
pods first, then old ready pods.  The algo always has to make progress.

**Comment by smarterclayton** [comment]
This is probably the same issue, but:

```
mysql-2-deploy            0/1       DeadlineExceeded   0          2h
mysql-3-deploy            0/1       DeadlineExceeded   0          2h
mysql-4-deploy            0/1       DeadlineExceeded   0          2h
mysql-5-00zr8             0/1       CrashLoopBackOff   20         2h
mysql-6-deploy            0/1       DeadlineExceeded   0          1h
mysql-7-deploy            1/1       Running            0          1h
mysql-7-ptq0x             0/1       CrashLoopBackOff   1          1h
```

I would not expect mysql-5 to still be around.
