### ISSUE TITLE
Deployment that is scaled to 1, but has a recent failed deployment, is not scaled up until next resync

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7272]
Had a deployment 9 (failed), 8 (successful), and 7 (failed).  Deleting the deployment 8 did not result in deployment 6 (successful) getting scaled up to 1 until the next resync loop.

It's good that the rsync loop caught it.  We should figure out why deleting the RC did not trigger the right logic.

[rc.txt](https://github.com/openshift/origin/files/128853/rc.txt)

**Comment by kargakis** [comment]
You deleted the controller manually? Why? Is this a wrong way of expressing that you wanted to rollback? I always thought that users shouldn't touch dc-owned rcs.

**Comment by smarterclayton** [comment]
I deleted the controller manually because everything was hosed (because of other issues #7270).  That's a reasonable reaction for an admin - they are trying to "fix" the problem we created, so they're going to do things that occur to them (like delete the offending "bad" rc).  We have to react to the system and do the right thing where we can.

**Comment by kargakis** [comment]
@smarterclayton got any idea if controllerRef should help here? Do you know if deleting childs is going to trigger watches for parents somehow? That would be ideal.

**Comment by smarterclayton** [comment]
Deleting children would not trigger watches for parents.

**Comment by kargakis** [comment]
The upstream controller [identifies updates on children (replicasets) and requeues the parent (deployment)](https://github.com/kubernetes/kubernetes/blob/62a8394eb491e82e5445e36542907608bf7b95f3/pkg/controller/deployment/deployment_controller.go#L242-L265). Doing that would solve this issue. We need to transition to using caches in the deployment controllers (right now we don't really use them).

**Comment by kargakis** [comment]
Just tested this scenario with #9002. The deployment was immediately rolled back.
```
[vagrant@localhost sample-app]$ oc get rc
NAME         DESIRED   CURRENT   AGE
database-2   0         0         13m
database-3   0         0         4m
database-4   0         0         3m
database-5   1         1         2m
database-6   0         0         1m
[vagrant@localhost sample-app]$ oc delete rc/database-5
replicationcontroller "database-5" deleted
[vagrant@localhost sample-app]$ oc get rc
NAME         DESIRED   CURRENT   AGE
database-2   0         0         14m
database-3   1         1         4m
database-4   0         0         3m
database-6   0         0         1m
```

**Comment by kargakis** [comment]
```
svc/database - 172.30.194.67:5434 -> 3306
  dc/database deploys docker.io/openshift/mysql-55-centos7:latest 
    deployment #6 failed 4 minutes ago
    deployment #4 failed 7 minutes ago
    deployment #3 deployed 7 minutes ago - 1 pod
  pod/database-5-eelw0 runs openshift/mysql-55-centos7:latest
```
