### ISSUE TITLE
Using setcap duplicates binary to the higher layer in image

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7289]
openshift/origin uses setcap net_bind_service, which causes a copy of the openshift binary from its previous layer (the COPY/ADD) into the RUN layer, duplicating a 120M binary.

This sucks.

@mrunalp I had naively assumed that setcap would not copy up, but looks like that's not accurate?  Possible bug in docker or just the way the FS works?

**Comment by mrunalp** [comment]
@smarterclayton Unfortunately this is just how the fs works i.e. changing the attribute results in copy up.  @rhvgoyal Do you think we can do anything here?

**Comment by mrunalp** [comment]
@smarterclayton If we build the openshift binary in Docker and then setcap in the same RUN command then we could avoid the copy. I can't think of anything if we do a ADD/COPY.

**Comment by mrunalp** [comment]
Thinking about this more maybe something like cp -a semantics for COPY/ADD might work. Not sure what issues could crop up there or whether copying into devicemapper layers could lose attributes. @rhvgoyal WDYT?

**Comment by rhvgoyal** [comment]
setcap, calls setxattr(security.capability). So this basically changes xattr of file. And this in turn changed the file, so copy up will happen. I am not sure how one can avoid it.

**Comment by mrunalp** [comment]
@rhvgoyal What if docker COPY were to do the equivalent of cp -a? That way we don't need to call the setcap in RUN and could avoid the copy up. However, the only concern is how well attributes work across different filesystem drivers when copied.

**Comment by mrunalp** [comment]
cp option --preserve=all to be more specific (which is included when -a is specified)

**Comment by rhvgoyal** [comment]
@mrunalp I assumed that COPY/ADD retain the existing xattrs of file. That's not the case? So is that the reason that openshift has to first do ADD/COPY and then do "RUN setcap"?

If yes, retaining xattrs seems reasonable. If not default, atleast an option to COPY/ADD to retain attrs should help.

**Comment by mrunalp** [comment]
@rhvgoyal Yes, atleast with the devicemapper driver, the file capabilities are lost. If we modify docker to retain those, then we can avoid this. Also, it will be a nice addition IMO.

**Comment by rhvgoyal** [comment]
@mrunalp, devicemapper does not know about xattrs or capabilities etc. It is filesystem layer. So I am not sure what's the connection between devicemapper and xattrs.

**Comment by rhatdan** [comment]
File Capabilities would be good, but you probably want to avoid XAttrs.

**Comment by mrunalp** [comment]
@rhatdan yeah, just copying the file capabilities should be fine. 

@rhvgoyal What I meant was that I am using the docker devicemapper backend (with ext4). So, devicemapper doesn't really care as long as underlying fs supports copying of capabilities for this use case. I am trying to guage if there will be any arguments against adding this to docker because it won't work with a particular graph driver.

**Comment by rhvgoyal** [comment]
@mrunalp, I think there will be resistance if all the storage backends don't support it. Becaues then outcome of built image will be unpredictable and that's not what user want. So to make it predictable they will end up using "setcap" anyway, and that undoes any benefit of copying file capabilities.

**Comment by rhatdan** [comment]
I would suspect this would work on all graphdrivers unless the graphdriver had a file system which did not support File Caps.  Almost all do now.

**Comment by mrunalp** [comment]
I have opened https://github.com/docker/docker/issues/20435 upstream.

**Comment by mrunalp** [comment]
We have an elegant solution now with ambient capabilities that were merged into Linux kernel 4.3 and just enabled in runc. There is no need set file caps anymore with that.

**Comment by mrunalp** [comment]
We do need a backport of ambient capabilities to RHEL though. I will follow up on that.

**Comment by mrunalp** [comment]
RHEL 7.3 has support for ambient capabilities so we are good :)

**Comment by smarterclayton** [comment]
Sweet.  Will mark this closed when that lands.  Anything we need to
configure via ansible / Kube to give all containers bind to all ports?

On Sep 29, 2016, at 6:40 PM, Mrunal Patel <notifications@github.com> wrote:

RHEL 7.3 has support for ambient capabilities so we are good :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/7289#issuecomment-250612676>,
or mute the thread

**Comment by mrunalp** [comment]
@smarterclayton We would just need to ensure that the capabilities granted to the containers include net_bind_service (docker default) using and that's it. Even if you run container as non-root, the container process would get that capability without having to setcap the container binary.
