### ISSUE TITLE
Pods created by deployments should be correlated via annotations

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#729]
Pods created by deployments (replicationControllers) should be correlated by annotations (replicationController name, deploymentConfig name, and deployment version). This isn't currently possible because the upstream ReplicationController code doesn't transfer annotations from the PodTemplateSpec onto Pods it creates- it only transfers labels.

**Comment by ironcladlou** [comment]
@smarterclayton please assign this one to me.

**Comment by ironcladlou** [comment]
cc @jcantrill

**Comment by smarterclayton** [comment]
Is there an upstream issue created to track this?

**Comment by ironcladlou** [comment]
Not yet, will discuss further today to make progress.

**Comment by ironcladlou** [comment]
@smarterclayton Trying to get my head back into this one: I seem to recall thinking that switching to k8s v1beta3 fixes this. True? If so, when will we be switching to use that internally? If it doesn't fix it or if it does but we won't be switching for a while, I'll have to come up with a fix for the old API versions.

**Comment by ironcladlou** [comment]
@smarterclayton Talked to @derekwaynecarr and decided beta3 is too far out. I'll have to address this sooner.

**Comment by ironcladlou** [comment]
This issue depends on https://github.com/GoogleCloudPlatform/kubernetes/pull/4025

**Comment by ironcladlou** [comment]
@smarterclayton this one can be moved into the 0.3.0 (beta1) milestone.
