### ISSUE TITLE
Add rollout to oc

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#7303]
kubectl now has a `rollout` command.  For now it has been ignored in our test.  When we do the work to reach parity with upstream deployments it will need added to the `oc` command.

See https://github.com/pweil-/origin/commit/3bde48eb8a0d96c28671f5aecb13e74dc83451ea#commitcomment-16098541

https://github.com/openshift/origin/pull/7269

@kargakis

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/6896

**Comment by pweil-** [comment]
thanks, closing as dupe
