### ISSUE TITLE
Fix Gluster and Ceph tests.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#7311]
```
 Extended Core.Volumes [Feature:Volumes] GlusterFS should be mountable  6 min 1 sec 1
 Extended Core.Volumes [Feature:Volumes] iSCSI should be mountable  5 min 50 sec    1
 Extended Core.Volumes [Feature:Volumes] Ceph RBD should be mountable   5 min 45 sec    1
```
#6882

for @childsb and @wattsteve @rootfs

**Comment by jsafrane** [comment]
@jayunit100, do you have any logs from the test? Especially all kubelet logs would be very helpful. And, is there a way how to see on which machines the test run? OpenShift/Kubernetes need client utilities installed on all nodes in the cluster (mount.nfs, iscsiadm, ceph, ...).

**Comment by jayunit100** [comment]
@rootfs may have some.  i think these fail by default if you dont have privileged containers

**Comment by copejon** [comment]
@jayunit100 Do you remember how to reproduce this?  I'd like to dig into it but only just getting familiar w/ testing in origin

**Comment by jayunit100** [comment]
hmmm this is sufficiently old that we should close itt

**Comment by jayunit100** [comment]
@copejon 

- test/extended: that wraps upstreams test/e2e suite, so look in vendor/src/k8s.io/kubernetes ... in order to see how the tests run , 

extended.test is the equivalent binary to upstream e2e.test
