### ISSUE TITLE
[RFE] hello-openshift log access to stdout

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#7314]
Currently hello-openshift does return something, but it doesn't log anything to stdout. It would be nice if it logged access in some way.

**Comment by bparees** [comment]
it logs accesses:
```
10.192.212.175 - - [16/Feb/2016 18:41:03] "GET / HTTP/1.1" 200 3428 0.0221
10.192.212.175 - - [16/Feb/2016 18:41:03] "GET /favicon.ico HTTP/1.1" 404 18 0.0007
10.192.212.175 - - [16/Feb/2016 18:41:03] "GET /favicon.ico HTTP/1.1" 404 18 0.0003
10.192.212.175 - - [16/Feb/2016 18:41:26] "POST /keys/a HTTP/1.1" 200 11 0.0196
```

is that not what you want?

(that's not the app doing it, it's the framework, but regardless)

**Comment by thoraxe** [comment]
"hello-openshift" is a docker container built from golang.

ruby-hello-world is a ruby application.

This RFE refers to the former (the Go lang Docker image), and not the latter (the ruby app).

**Comment by bparees** [comment]
whoops, sorry about that, my bad.

**Comment by thoraxe** [comment]
Sok!
