### ISSUE TITLE
limit/request overrides can make for frustrating user exp

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#7316]
Once https://github.com/openshift/origin/pull/6901 merges and the plugin is configured, there is the possibility it will prevent a user creating pods when e.g. their project has a min memory limit of 128Mi, they specify a container memory limit that's 128Mi, and the ratio is 50% overriding request to 64Mi which is then rejected. It would be better to floor overridden limits at min to prevent this kind of situation. However I am holding off doing that until we have a clean way to share the cache of `LimitRange` objects that the `LimitRanger` plugin uses - we already have two instances, each with a watch on the API, and adding another one just for this purpose may be one too many. However we can do that if it's considered a priority. Frankly, most users won't be too aware of it.

**Comment by sosiouxme** [comment]
https://github.com/kubernetes/kubernetes/issues/21077 is to track upstream.

**Comment by smarterclayton** [comment]
P1 cause this is usability and we're going to break everyone.

**Comment by sosiouxme** [comment]
@smarterclayton any opinion on whether you prefer:

1. the immediate fix that requires another limits watch cache
2. a LimitRanger patch we carry making it possible to reuse its cache
3. upstream action to make this a sharable resource
4. something else...

**Comment by deads2k** [comment]
5. Floor in the config file and ops is careful to keep it in sync with the defaults.

**Comment by sosiouxme** [comment]
ha, that does seem a lot simpler.

**Comment by sosiouxme** [comment]
@abhgupta considers this a feature and doesn't think we should provide floors (although the user experience does need improvement).

**Comment by abhgupta** [comment]
@sosiouxme this is a "workaround" for the fact that we don't have a min-limit attribute in the limit range.

**Comment by smarterclayton** [comment]
Is there a card / issue for that?

**Comment by abhgupta** [comment]
@danmcp @derekwaynecarr Did we create a card for adding a min-limit attribute to the limit range?

**Comment by sosiouxme** [comment]
FWIW I just finished the code that provides a floor (and the settings are optional). I can keep that in my back pocket.

**Comment by danmcp** [comment]
@abhgupta I did not.  Please do.

**Comment by sosiouxme** [comment]
@abhgupta said there was talk of having different limits for limits and requests, I assume this is what he meant by min-limit. A quick search for cards and k8s issues didn't turn up anything upstream but I could have just missed it. @derekwaynecarr do you know of anything?

This is marked P1 but if we're planning a better fix based on upstream changes then I'm guessing it will be punted.

**Comment by abhgupta** [comment]
@sosiouxme @derekwaynecarr Here is the card that I just created: https://trello.com/c/jOTw73aD
