### ISSUE TITLE
Enable LDAP group sync to take advantage of extensible matches

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#7320]
One specific extended match that might be useful is the `memberOf:` match that flattens nested groups for MS AD servers.

Thoughts:
- this would only be useful for MS AD servers
- our current approach for AD-style schema is not compatible with this as we create groups from user queries and cache users
- would not require new config, can reuse `LDAPQuery` and pair it with an `ExtensibleMatchFilterBase` that allows for the type of `(%s=%s)` filter construction we have with `LDAPQueryOnAttribute`

/cc @deads2k @liggitt

**Comment by liggitt** [comment]
flattening AD groups would require inverting our sync... selecting groups first (by query or by whitelist), then doing `memberOf:...:=<group-uid>` queries

**Comment by stevekuznetsov** [comment]
@enj we did this, right?

**Comment by enj** [comment]
@stevekuznetsov yeah, the process to use nested AD groups is documented at https://docs.openshift.org/latest/install_config/syncing_groups_with_ldap.html#sync-ldap-nested-example
