### ISSUE TITLE
Can't get logs from replication controller

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7329]
```
$ oc logs rc/mysql-9
error: cannot get the logs from /__internal, Kind=ReplicationController
```

**Comment by deads2k** [comment]
@smarterclayton did this ever work?  I don't see the code in the factory to do it.  Looks like they did something for attach, but not for logs.

You just want logs for the first pod?

**Comment by smarterclayton** [comment]
I don't know if it ever worked, but I expected it to work.

**Comment by deads2k** [comment]
Opened https://github.com/openshift/origin/pull/7359 and https://github.com/kubernetes/kubernetes/pull/21335.
