### ISSUE TITLE
openshift won't spawn build pod due to etcd

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#733]
I've submitted build directly via API (can post the json if needed). Build pod wasn't created, build-logs said that there is no such pod.

Here is what I found in logs:
```
config.go:271] Pod 1 (build-numpy-2015-01-23T17-12-48-699124) from etcd failed validation, ignoring: [name: invalid value 'build-numpy-2015-01-23T17-12-48-699124']
```
What's wrong with that value?

**Comment by ncdc** [comment]
It has to be a DNS subdomain as specified in RFC 1123

**Comment by ncdc** [comment]
Although the code in Kubernetes doesn't appear to allow dashes

**Comment by TomasTomecek** [comment]
I went through the RFC briefly and haven't found the specification. Could you, please, be more specific?

**Comment by ncdc** [comment]
It's possible I was looking at the wrong validation code. We probably need to track down the exact bit that's throwing the error.

**Comment by smarterclayton** [comment]
It's case - we updated the validation today to match what upstream does (names are lowercase).  The easy change is to lowercase your name - we could relax that requirement but there's some discussion about whether that's going to cause problems in other areas (services have to be lowercase so you can't collide env vars)

**Comment by smarterclayton** [comment]
Leaving this open to cover expanding the validation range for builds again.  I think I have agreement upstream, but since these are converted to pods there's some risk in us accepting more range than what we create.

**Comment by TomasTomecek** [comment]
Would be great if you could update docs with regex used for validation.

**Comment by smarterclayton** [comment]
Upstream now returns verbose messages, we will gradually improve what is returned by the api doc.

----- Original Message -----

**Comment by smarterclayton** [comment]
Validation errors now returns the appropriate limits.
