### ISSUE TITLE
RFE: automated way to disable automatic triggers on a DC

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#7335]
Looking for the reverse of `oc deploy --enable-triggers`.

The use case is to allow a user to temporarily disable automatic triggers (e.g. if the upstream ImageStream is changing a lot), then re-enable triggers subsequently (with `oc deploy --enable-triggers`, which of course already exists).

AFAICS it is at least not straightforward to construct a pipeline using `oc patch` to do this, hence it would be useful to be able to do through the CLI as a starting point.

**Comment by kargakis** [comment]
Is `oc set triggers dc/name --manual` doing what you want?

**Comment by jim-minter** [comment]
It looks good to me; I'll ask my customer who mentioned it what they think as well.
@smarterclayton some minor nits: `oc set triggers` as a mechanism to *view* seems a bit clumsy (I'm objecting to the use of the word set in this context), and it would be nice also to support flags like `--all`.

**Comment by kargakis** [comment]
Another way to achieve disabling triggers will be `oc rollout pause` and `oc rollout resume`... Related issue: https://github.com/openshift/origin/issues/6896

**Comment by smarterclayton** [comment]
> @smarterclayton some minor nits: oc set triggers as a mechanism to view seems a bit clumsy (I'm objecting to the use of the word set in this context), and it would be nice be able to show triggers for all DCs from the command line (e.g. oc set triggers on its own would work).

I agree, but at the same time, it's the only place where we have a "trigger focused view".  And it's the only place we have that would unify triggers across bc / dc.

For all, `oc set triggers dc --all` should show you all triggers on all dcs.

**Comment by smarterclayton** [comment]
Agree rollout pause and resume will get hooked into triggers.

**Comment by smarterclayton** [comment]
And we'll probably add more triggers to more objects, like daemon sets and scheduled jobs.

**Comment by kargakis** [comment]
@smarterclayton note that `kubectl rollout pause` will halt deployments in the middle of a rollout because the upstream controller (where the strategy is backed into) will ignore paused deployments.

**Comment by smarterclayton** [comment]
I like pause.  We just need to upgrade deployment config to have all the
same benefits.  I'll want to pause a recreate deployment.

**Comment by jim-minter** [comment]
@kargakis fyi the customer response was that they thought it looked good too.

**Comment by kargakis** [comment]
@jim-minter that's cool! Please close this issue, if there isn't anything else here to be done.
