### ISSUE TITLE
Add the possibility to copy the image when tagging an image in an other project

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7338]
Here is the context : we use a project by environment and we use tag to manually promote images.

```
foobar-int
foobar-preprod
foobar-prod
```

When we tag an image into an IS of an other project, the image is not copied in the target IS, it's just a reference. 

Here is the command that I used in project `foobar-int`

```
oc tag foobar:latest foobar-prod/foobar:prod -n foobar-prod
```

```
$ oc get istag -n foobar-prod 
NAME        DOCKER REF 
foobar:test   172.30.63.79:5000/foobar-int/foobar@sha256:…
```

It could be useful to add an option to perform a copy (for example, in case of deletion of the original IS). In the Openshift docker registry, the image could also be in its own namespace.

**Comment by smarterclayton** [comment]
This has been implemented  by default.
