### ISSUE TITLE
drift between types and versioned types doc is unchecked

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#7341]
Once we start generating swagger doc from Godoc on versioned types, it seems like it would be a good idea to check in our CI pipe that the Godoc for `whatever/pkg/api/types.go` and `whatever/pkg/api/v1/types.go` doesn't differ.

@smarterclayton thoughts?

**Comment by deads2k** [comment]
No.  The types aren't necessarily the same (maps versus slices as a for instance), so the godoc won't match.  The hubbed version doesn't necessarily match the spokes.

**Comment by smarterclayton** [comment]
And we only really generate doc for the spokes.  Hub is more for
developers, and hub not matching at least one spoke is really just a
measure of tech debt.

**Comment by danmcp** [comment]
Please reopen if this is still an issue.
