### ISSUE TITLE
oc import-image does not import all tags from DockerHub

### ISSUE THREAD

**Issue by rassie** [openshift/origin#7346]
Given is the following ImageStream:

```
{
    "kind": "ImageStream",
    "apiVersion": "v1",
    "metadata": {
        "name": "redis-official",
        "namespace": "openshift",
        "creationTimestamp": null
    },
    "spec": {
        "dockerImageRepository": "redis"
    }
}
```
Actually importing the tags produces the following output:

```
$ oc import-image redis-official -n openshift
Waiting for the import to complete, CTRL+C to stop waiting.
The import completed successfully.

Name:			redis-official
Created:		5 hours ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2016-02-16T15:38:19Z
Docker Pull Spec:	172.30.159.96:5000/openshift/redis-official

Tag	Spec		Created		PullSpec									Image
2	redis:2		5 hours ago	redis@sha256:51f71e065c1cd35e1c6574ec89bd237408ce87f31b6fde8bf16f5ad1fc8528bf	
2.8	redis:2.8	5 hours ago	redis@sha256:9734e5cc06a09ee9a4cae586078a1bf11a526d196153c9c837233c273157509c	
3.0.0	redis:3.0.0	5 hours ago	redis@sha256:06ce8790b8f63ad1ee9eec1aec5513c34331a350f66a370572405cb15508ecdc	
latest	redis:latest	5 hours ago	redis@sha256:de86bd14ab69c9b707fe5f3213f6e3c6f543df28bc05ae6cef7b61f2b12be343	

```
However, according to the [Redis' Dockerhub page](https://hub.docker.com/_/redis/), there are at least several more interesting and important tags like `3.0.7`and `3-alpine`. I would have expected OpenShift to proxy all tags from DockerHub.

This happens on OpenShift Origin v1.1.2.

**Comment by soltysh** [comment]
With recent changes to the importer mechanism there's a `maxImagesBulkImportedPerRepository`, which [by default is 5](https://github.com/openshift/origin/blob/master/pkg/cmd/server/api/v1/types.go#L208-L211). Modify `master-config.yaml`'s `.imagePolicyConfig.maxImagesBulkImportedPerRepository` to desired value or -1 for no limit. Once verified - please close this issue.

**Comment by rassie** [comment]
Thanks, this does indeed work. Closing.
