### ISSUE TITLE
copy-kube-artifacts rsync not working

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#7356]
Found during the latest rebase (https://github.com/openshift/origin/pull/7269).  I was not able to add items to the rsync list and have them copied over appropriately.  Also, some of the existing items is the search list were not being copied (ex. the api json files).

To get it to work I needed to revert and also do some manual copying.

Items I tried to add:

```
cmd/libs/***
third_party/golang/***
```

Also tested by @pmorie

**Comment by soltysh** [comment]
Failures are here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/11003/console
