### ISSUE TITLE
Remove symbolic fixture links for builds

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7367]
They screw up command line utilities and don't need to be checked into git.  Instead, create them in the test case and then clean them up.

`pkg/cmd/cli/secrets/bsFixtures/dir/symbolic`

**Comment by bparees** [comment]
that's not a build thing.  it's for secret creation.  git history shows @deads2k created the link, he can rework it.

**Comment by deads2k** [comment]
No refactor goes unpunished.

**Comment by deads2k** [comment]
Of course the tests in that package were borked when I moved them.  sigh.

**Comment by deads2k** [comment]
Out of curiosity, which weird levels of which command line utilities break on this?  It's been here since sally wrote it ages ago, just surprised that a new utility can't handle it.

**Comment by smarterclayton** [comment]
Things like find and source code scanning typically crash and die on
recursive loops (or print ugly errors).  Grep actually chokes on a lot of
them.
