### ISSUE TITLE
Web console support for configuring build unit tests 

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7372]
See #6758 and https://github.com/openshift/openshift-docs/pull/1448. We should be able to reuse a command builder for health checks, #7312.

From @rhcarvalho:

> apart from the docs link above, also please look at the screenshots in the original issue description. We want to make sure it's easy to specify and edit the command to be run, and that the working directory is clear. In case of using the script form, we should also make clear that it will be run using /bin/sh -c (so no Bash-only syntax, and the image needs to have the /bin/sh binary).

/cc @jwforres

**Comment by jwforres** [comment]
Moved to trello https://trello.com/c/QjbwH2D6
