### ISSUE TITLE
Create flag type for comma-delimited and/or equal-sign-based flags

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#7376]
Currently commands like `oc secrets new`, `oc new-app`, `oc process`, _etc_, do home-brewed logic for parsing flags that are either comma-delimited lists or `key=value` pairs, or both. We should just make a new flag type _a la_ the address flag type and consolidate that logic.

**Comment by deads2k** [comment]
Comma delimited lists are string slice params.

**Comment by bparees** [comment]
we've lived this long (and actually removed most of our support for comma separated values to args) so this can probably be closed, but will let the team that owns the CLI decide.

**Comment by stevekuznetsov** [comment]
@openshift/sig-user-interface
