### ISSUE TITLE
LDAP sync dry-run should output some diff-based information

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#7380]
The current implementation of the LDAP group sync - dump everything to JSON then stdout - is not very useful. LDAP group sync only changes membership information, so it would be cool to see some output with a member diff per-group instead.

/cc @deads2k @liggitt

**Comment by deads2k** [comment]
I know, you could build a patch! :)

I think I'd rather use a different program to show me the diff.  That seems more generally useful.

**Comment by stevekuznetsov** [comment]
What do you propose to integrate with? We have the diffs from `go-spew` we could use, which is what I would have considered.

**Comment by deads2k** [comment]
Well... diff comes to mind.

A dry run needs to produce an object that I can use to create or update my existing entries.  Any outcome that does not produce that isn't valuable.  The "diff" case is at best a manual sanity check, but it has no actual utility after the fact.  Checking into source control is pointless and playing via a script is impossible.

**Comment by stevekuznetsov** [comment]
I am considering the case where humans are using this script, not machines. Why does a human want something they can pipe into something else? The way the user is going to 'create or update my existing entries' is by turning off the dry-run flag, and we should **not** be suggesting they do anything else.

**Comment by deads2k** [comment]
Control.  Both automatic and manual change control policies will require using dry-run.  I expect dry-run, save the new groups, apply the changes to be a common case, perhaps even as common as doing it automatically.  Relatively few shops running ldap are comfortable allowing a machine process to change things related to authentication and authorization without trackability.

Diff should be a separate step.

**Comment by stevekuznetsov** [comment]
Shouldn't `-o yaml` or whatever make the output machine-readable? Why shouldn't the output of our dry run be human-readable by default?

**Comment by deads2k** [comment]
We want default output to be the common output case and that is an API object that matches all other dry-run output from out commands and is useable in the normal path of "what's going to change, save this so I can track it, apply changes".

Having different output may be interesting, but ultimately this command shouldn't be special.  A standard command to diff API object has general utility and is more in keeping.

**Comment by stevekuznetsov** [comment]
Point understood
