### ISSUE TITLE
docs for anyuid

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#7384]
Can we generate info about Security contexts into the docs somehow ? #7098 

```
	SecurityContextConstraintPrivileged     = "privileged"
	SecurityContextConstraintRestricted     = "restricted"
	SecurityContextConstraintNonRoot     = "nonroot"
	SecurityContextConstraintHostMountAndAnyUID     = "hostmount-anyuid"
	SecurityContextConstraintHostNS     = "hostaccess"
	SecurityContextConstraintsAnyUID     = "anyuid"
```
into the docs or somewhere else that is googlable/indexable/searchable ... ? 

Looks like users/installers need to be aware of these to setup OS idiomatically for some things, such as `kubectl` to work properly based (i.e. 

@pmorie @smarterclayton @timothysc

**Comment by smarterclayton** [comment]
I believe there is a docs issue already open to improve SCC   Security
instructions aren't framed in a way that educates admins about tradeoffs
   <https://github.com/openshift/openshift-docs/issues/759>

**Comment by jayunit100** [comment]
closing as dupe
