### ISSUE TITLE
When navigating to a cancelled build the console shows c3 errors

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#7385]
![screen shot 2016-02-17 at 11 45 45 am](https://cloud.githubusercontent.com/assets/280512/13116977/13b20aac-d56c-11e5-9344-423eb83c692b.png)

@jwforres @spadgett

**Comment by spadgett** [comment]
Yeah, Chrome removed an API c3 was using :-/

Fixed by #7373
