### ISSUE TITLE
Remove icons from actions dropdown

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7387]
As the actions menu grows, we're having trouble finding unique icons. Particularly when resources have more than one kind of edit action. Some examples:

Build Config:

<img width="221" alt="screen shot 2016-02-17 at 12 30 03 pm" src="https://cloud.githubusercontent.com/assets/1167259/13118465/454c21b4-d572-11e5-8978-d31753b11a80.png">

Deployment Config:

<img width="223" alt="screen shot 2016-02-17 at 12 30 24 pm" src="https://cloud.githubusercontent.com/assets/1167259/13118470/4e339bfe-d572-11e5-824b-f76bec8592a2.png">

Recommendation from @ajacobs21e is to remove the icons from the actions menu.

/cc @jwforres @rhamilto

**Comment by spadgett** [comment]
@jwforres any objections to the change?

**Comment by ajacobs21e** [comment]
Thanks for opening this Sam

**Comment by jwforres** [comment]
no objections here
