### ISSUE TITLE
test-cmd.sh should test key functionality from upstream

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#739]
Currently the origin repo is in a state where a viable resize command isn't available.  The test-cmd.sh script should have caught this; it should be extended to ensure that key features in the upstream CLI are available via the OpenShift cli.

**Comment by smarterclayton** [comment]
In the future, when we do rebases, we should make sure we add tests for new function (like CLI commands) to at least do basic sanity.  We should also brief QA

**Comment by smarterclayton** [comment]
With #825 we should figure out how to run a variant of upstream test-cmd (or the equivalent tests).

**Comment by pmorie** [comment]
@smarterclayton I think we will have to curate our own cases for this.  In the situation that prompted creating this issue, I don't think running upstream's test-cmd against our binary would have been sufficient to catch the resize thing.

**Comment by kargakis** [comment]
If resize was the problem, this can close now as you can use osc resize.

**Comment by kargakis** [comment]
And of course it's [tested](https://github.com/openshift/origin/blob/1d7cfce4f3b48d78e00ffe306a7de864761b07ea/hack/test-cmd.sh#L437-L446) in test-cmd.sh

**Comment by stevekuznetsov** [comment]
While I am reworking`test-cmd` should I worry about this? @smarterclayton

**Comment by smarterclayton** [comment]
Not right now

**Comment by smarterclayton** [comment]
This is no longer a significant issue
