### ISSUE TITLE
docker-in-docker deploy broken by build-go.sh changes

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#7390]
`./hack/dind-cluster.sh start` in a dind vagrant image now fails.

It seems like build-go.sh can now only succeed if it's invoked from within a path that looks like a go root (ie, /something/src/github.com/openshift/origin), so having the origin checkout mounted at /data and trying to build from there fails.

@marun @smarterclayton

**Comment by smarterclayton** [comment]
In general, if people need hacks to work outside a regular GOPATH (like
#7381) I'll merge them, but they won't be the default behavior in our tools.

**Comment by marun** [comment]
I'm not sure why a 'regular' GOPATH makes any sense for a project that manages its own dependencies via godep, but I guess we're stuck replicating this pattern so long as we're following in kube's footsteps.

**Comment by marun** [comment]
In any case, this breaks a vm-based devcluster as well.  I'm working on a fix.

**Comment by smarterclayton** [comment]
We encourage regular GOPATH because that's how Go works.  If Go didn't
encourage the pattern, we wouldn't do it.  Because it does, we're following
the community's structure, instead of inventing new things.

**Comment by marun** [comment]
I get it, the goal is consistency.  But I don't think golang has anything definitive to say about how to manage dependencies for a project like openshift (at least not yet), and I'm not sure being consistent for its own sake buys anything.

**Comment by smarterclayton** [comment]
The go lang tooling ecosystem expects GOPATH and the set of directories.
We don't create arbitrary distinctions, especially when we don't need to.
 build-go.sh works fine using one build root and the Godeps path, and
specific exceptions for convenience can be considered but must be justified.

**Comment by marun** [comment]
@danmcp I think this can be closed, but I don't have permission to do so.
