### ISSUE TITLE
SELinux problems with volumes when running as a Docker container

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#741]
Running OpenShift as a docker (1.4.1) container on fc21 with:

````
docker run -d --name=openshift -v /var/run/docker.sock:/var/run/docker.sock --privileged --net=host openshift/origin:latest start
````

Even without mounting any volume, the container uses `/var/lib/openshift` on the host (not quite sure how it does that, but hey!) for managed volumes.

Since the latest RPM upgrade (`docker-io-1.4.1-5`) anything using an kubernetes volume fails to start up unless I run on the host:

````
chcon -Rt svirt_sandbox_file_t /var/lib/openshift/openshift.local.volumes/
````

Is there another way to work around this?

**Comment by smarterclayton** [comment]
We should add this to the documentation - we're creating the dir, but a chcon is still necessary.  I'm a bit leery of the master chcon'ing automatically on start, but maybe there's something we can do only on create.

**Comment by jimmidyson** [comment]
I think it would be worth having the master chcon'ing on create, simply for ease of use. Understandable not to want to chcon on each startup, but on create should be fine & it's pretty much unusable without this tbh.

**Comment by smarterclayton** [comment]
Yeah, just need to detect whether chcon is available which is always a pain.

**Comment by ncdc** [comment]
FYI I did this for STI a long time back (back when we were calling chcon) to check if SELinux is enabled and if chcon is available: https://github.com/openshift/geard/blob/24fcfed2beb2686f284822b308ef91c9834cb620/sti/selinux.go

**Comment by ncdc** [comment]
@smarterclayton do you want me to port that code over?

**Comment by ncdc** [comment]
Something like this: https://gist.github.com/ncdc/9899169badda1792c229

**Comment by smarterclayton** [comment]
Yeah, but chcon missing is ignored for other os (log at v(2))

**Comment by ncdc** [comment]
PR for fix: #857

**Comment by jimmidyson** [comment]
@smarterclayton @ncdc The PR doesn't seem to have helped at all. Running openshift/origin:latest, built 2 days ago.

```
$ ls -lRZ /var/lib/openshift/
/var/lib/openshift/:
drwxr-xr-x. root root system_u:object_r:docker_var_lib_t:s0 openshift.local.volumes

/var/lib/openshift/openshift.local.volumes:
drwxr-xr-x. root root system_u:object_r:docker_var_lib_t:s0 pods

/var/lib/openshift/openshift.local.volumes/pods:
drwxr-xr-x. root root system_u:object_r:docker_var_lib_t:s0 3d3fbe1d-b042-11e4-b30d-54ee7527188d

/var/lib/openshift/openshift.local.volumes/pods/3d3fbe1d-b042-11e4-b30d-54ee7527188d:
drwxr-xr-x. root root system_u:object_r:docker_var_lib_t:s0 volumes

/var/lib/openshift/openshift.local.volumes/pods/3d3fbe1d-b042-11e4-b30d-54ee7527188d/volumes:
drwxr-xr-x. root root system_u:object_r:docker_var_lib_t:s0 kubernetes.io~empty-dir

/var/lib/openshift/openshift.local.volumes/pods/3d3fbe1d-b042-11e4-b30d-54ee7527188d/volumes/kubernetes.io~empty-dir:
drwxr-xr-x. root root system_u:object_r:docker_var_lib_t:s0 es-persistent-storage

/var/lib/openshift/openshift.local.volumes/pods/3d3fbe1d-b042-11e4-b30d-54ee7527188d/volumes/kubernetes.io~empty-dir/es-persistent-storage:
```

**Comment by smarterclayton** [comment]
We're those directories new when the daemon started up?  If chcon failed there should be a warning in the startup logs.

**Comment by jimmidyson** [comment]
So I deleted /var/lib/openshift on the host & started a new Docker container for openshift - so yeah directory was created. I checked the logs & there was nothing in there about failing to run chcon which is a bit weird...

**Comment by ncdc** [comment]
I just saw this AVC denial:

```
type=AVC msg=audit(1423492102.530:1161): avc:  denied  { relabelfrom } for  pid=8313 comm="chcon" name="openshift.local.volumes" dev="dm-5" ino=137885 scontext=system_u:system_r:docker_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=1
```

**Comment by ncdc** [comment]
Because we're bind mounting the host's Docker socket into the origin container, any Docker operation that uses a volume will result in the volume coming from the host. But if you don't bind mount /var/lib/openshift from the host into the origin container, you'll end up with most of the /var/lib/openshift content coming from the container (e.g. the generated certificates) but pod volumes coming from the host. So an attempt to chcon would run against /var/lib/openshift/openshift.local.volumes in the container, when it should be running against the host's directory... right?

**Comment by jimmidyson** [comment]
@ncdc Yes! I bind mounted /var/lib/openshift & all works perfectly. Thanks!
