### ISSUE TITLE
openshift origin cartridge phpmyadmin

### ISSUE THREAD

**Issue by luispimenta** [openshift/origin#7411]
I'm installing OpenShift origin m4, I create a normal web application, but when I add the phpmyadmin cartridge, it creates the _phpmyadmin.conf file inside the folder /etc/httpd/conf.d/openshift/ID_APP/ with an invalid line .

`ProxyPass / phpmyadmin http://127.10.75.3:8080/phpmyadmin/ retry = 0`
`ProxyPassReverse / phpmyadmin http://127.10.75.3:8080/phpmyadmin/`
`ProxyPassReverse / phpmyadmin http://teste-red4sis.apps.red4sis.in/`

which was to be only:

`ProxyPass / phpmyadmin http://127.10.75.3:8080/phpmyadmin/ retry = 0`
`ProxyPassReverse / phpmyadmin http://127.10.75.3:8080/phpmyadmin/`

Thus I can not access the application, because when I enter the url, is redirecting to phpmyadmin.

Does anyone know how to fix this?

thank you

**Comment by dinhxuanvu** [comment]
The issue you mentioned above is related to OpenShift V2 (M4) while this repo is for Openshift V3. I saw you posted the same issue on origin-server which is where it should be. Please close this one if you can.
Thanks.
