### ISSUE TITLE
Editing build configuration should submit the form on enter

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7413]
Would be nice to handle "enter" when editing the form, so I don't have to submit the form by mouse ;-)
Not high priority.

EDIT: This actually applies to all forms (creating from template for example..)

**Comment by mfojtik** [comment]
@jhadvig FYI

**Comment by jhadvig** [comment]
@mfojtik on it
@spadgett is this something we want ? ..just checking to be sure

**Comment by liggitt** [comment]
yes, `<enter>` submitting forms is an accessibility standard we don't want to break

**Comment by spadgett** [comment]
+1

**Comment by spadgett** [comment]
We do want to be careful in a few places. Adding env variables should probably just add the value and not submit the entire form.

**Comment by jhadvig** [comment]
@spadgett +1 ..the same for the sourcePath->destDir for the imageSource

**Comment by jhadvig** [comment]
@mfojtik we can close this issue since https://github.com/openshift/origin/pull/7525 has been merged :)

**Comment by mfojtik** [comment]
@jhadvig thanks!
