### ISSUE TITLE
Crashing container appears to be running on the web console logs page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7414]
We show the pod status on the pod log page, but not container state. When a container is crashing, it looks like it's running because under the container name we show "Status: Running." (In the screenshot below, the container is stopped due to a crash loop.)

![logs](https://cloud.githubusercontent.com/assets/1167259/13143156/01569162-d610-11e5-8abf-c64e55de9737.png)

/cc @jwforres @benjaminapetersen

**Comment by jwforres** [comment]
elsewhere we show this status as "Not Ready"

**Comment by spadgett** [comment]
We might add icons for the container states to draw your eye to abnormal states.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13146569/689ee874-d624-11e5-9d45-80574201cad0.png)

**Comment by benjaminapetersen** [comment]
Leaving a few discussion notes from this morning for feedback:

- Bootstrap `.danger`, etc classes could be used on text to help draw your eye to what is going on. 
- The icon up next to the container name doesn't seem to be sufficient.  
- In the log viewer, "status" is really `status.phase` (which is correct in the details tab).  
- I like the idea that either above the tabs or right below (consistently on each tab) would be pod & container status information collected together & sufficient to know what is going on.  
- We need to handle container pickers as well, when there are multiple.
- Sam mentioned there is a relationship between template & container that would be good to indicate more clearly.  I agree.  That could probably be a separate issue but I wanted to jot it down here.

**Comment by spadgett** [comment]
Related to #6584

**Comment by spadgett** [comment]
The misleading status message was removed in #7363, and we show better pod status in #7434.

We might come back to this as an enhancement later to show the pod status somewhere above the tabs, but the original usability problem is fixed.
