### ISSUE TITLE
Builder / template version looks odd in web console catalog when displayed

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7421]
When the builder image tag doesn't match the version, we show the version. It looks out of place, though, and it's confusing when it shows up for some tiles and not others. It also interrupts the layout because it changes the tile height.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13148103/d8836962-d629-11e5-9b6b-fc73f82bbb29.png)

We have a similar issue when the image and template is in a namespace other than openshift. We show the namespace like version above.

Working as intended, but calling this a usability bug.

/cc @jwforres @bparees @sspeiche @sg00dwin

**Comment by spadgett** [comment]
Some options. I believe the mockups from @ajacobs21e have something like (1) below. I didn't prefix with "v." because it's not always a number.

1)
<img width="566" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13920315/c39fb112-ef48-11e5-8f67-a3022aee2731.png">

2)
<img width="566" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13920325/d2f67100-ef48-11e5-8dc3-0a769783bb70.png">

3)
<img width="565" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13920336/d91a090c-ef48-11e5-804d-a91502503b89.png">

4)
<img width="567" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13920339/dfe6e7b4-ef48-11e5-8e78-c26b14b354b6.png">

5)
<img width="574" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13920347/ec4747ce-ef48-11e5-8e8c-23fc8b3c5b98.png">

6)
<img width="571" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13920350/f191bf66-ef48-11e5-8597-2b6819d0a68b.png">

/cc @rhamilto for input also.

**Comment by jwforres** [comment]
hmm i don't like 3 or 5, i cant decide about 6.  these are templates, how does this look on a builder that may have both a tag and a version?

**Comment by jwforres** [comment]
for the namespace issue, maybe we need to be prefixing the name with the namespace, i just worry about that getting long :-\

**Comment by jwforres** [comment]
we also seem to have an issue with people NOT understanding the difference between the templates and the builders, the icons + legend don't seem to be enough... :-\  but thats a discussion for another issue i guess

**Comment by rhamilto** [comment]
I think keeping the details close to the name is important since scan-ability is important when distinguishing one option from another; therefore, I favor option 4.  Option 5 is ok.  Option 6 is sort of confusing because we use uppercasing to mean "tags" in this context.

**Comment by sspeiche** [comment]
I'm not even sure the version needs to be on the overview, seems like it could be a detail after they select it or popup text. A big fix would be to use a better name, though that is a different issue I guess.

**Comment by spadgett** [comment]
> I'm not even sure the version needs to be on the overview, seems like it could be a detail after they select it or popup text. A big fix would be to use a better name, though that is a different issue I guess.

Do we ever have different version so the same template in the catalog? It might not be possible to tell them apart. (I think I saw this.)

**Comment by ajacobs21e** [comment]
2&3 look like the number is associated with the icon and 6 uses the same font as the tags so they're out. 
I prefer 4 over 5 to make it less wordy.

A benefit of 1 is that the version is always in the same place regardless of name length although Robb has a good point about keeping the version with the name.

If this is the latest would there be no version number? or would we include both? I had included both but I don't know if a user cares what version number something is if they are just looking for the newest.

**Comment by jwforres** [comment]
@bparees ?

**Comment by jwforres** [comment]
i know its possible in theory, the question is whether you would want to

**Comment by sspeiche** [comment]
Showing the version is just extra text and seems like covering the <10% case. Perhaps if there are more than one with the same name/id, show the versions then?

**Comment by jwforres** [comment]
FYI the updated templates were supposed to be dropping version from the
"latest" tags, unless that has changed again @bparees ?

**Comment by bparees** [comment]
I like (1) the best personally

I do think we want versions on there, only showing verisons when there are conflicts bothers my consistency sensibilities and i don't think the version number is that intrusive.

we did remove the version from the "latest" tags for imagestreams.

**Comment by sg00dwin** [comment]
I prefer keeping the version near the name, as well. Either 4 or 5.

**Comment by ajacobs21e** [comment]
Another benefit of 4 is that we have more space on the right side if we need to add anything else to this card.

**Comment by rhamilto** [comment]
In reviewing the existing [tile-image](https://github.com/openshift/origin/blob/master/assets/app/views/catalog/_image.html#L10-L22) and [tile-template](https://github.com/openshift/origin/blob/master/assets/app/views/catalog/_template.html#L8-L20) templates, I notice that in addition to "Version", "Provider" and "Namespace" also optionally display in the same way as "Version".  Whatever we decide, we need to come up with a solution that can accommodate anywhere from 0-3 of these additional items.

**Comment by jwforres** [comment]
@rhamilto was this fixed by the catalog updates?

**Comment by rhamilto** [comment]
> @rhamilto was this fixed by the catalog updates?

Yep.

![screen shot 2016-11-08 at 1 47 01 pm](https://cloud.githubusercontent.com/assets/895728/20112316/e985b28c-a5b9-11e6-9b39-5b0f682ef3fc.PNG)
