### ISSUE TITLE
ssh to pod failed

### ISSUE THREAD

**Issue by catherinesword** [openshift/origin#7422]
I have a 5-node (including master itself) OpenShift cluster running normally in AWS, and I've used it for long time so I'm sure ssh to pod worked before. However I didn't change anything except normal create/delete pod/service, when I created new pods and tried to connect to them via ssh, connections were always refused. 
I'm sure in the pod description file port 22 is open, I'm using the same image/pod.json before, and I have it tested in docker environment and ssh works as well. Can anybody give me some hints what happened to the cluster? Thank you!

update: I did try "telnet pod-ip 22" and connection refused. I can ping the pod, so it is running. Also on the node I can ssh to any other nodes without problems.

**Comment by pweil-** [comment]
@catherinesword - are there any errors in the pod logs about starting the ssh daemon?  If the pod is running under a restrictive `SecurityContextConstraint` then perhaps it was prevented from binding to the low port as a non-root user without `CAP_NET_BIND_SERVICE`.  You can see which SCC the pod validated against with `oc get <pod> -o json | grep scc`

You may need to run this pod with elevated privileges so that it may run with UID 0 or bind to a higher level port.  This document details how to add a user to an SCC that would allow it to run with any UID:  https://docs.openshift.org/latest/admin_guide/manage_scc.html

**Comment by catherinesword** [comment]
@pweil-  Thank you very much for your reply! I had a look at pod SCC and it says "anyuid", I logged in as "system:admin". So should I add this user to any of the SCCs? Now I have anyuid, hostaccess, hostmount-anyuid, nonroot, privileged and restricted.

**Comment by pweil-** [comment]
anyuid should be fine.  Are you getting any errors in the pod logs?

**Comment by catherinesword** [comment]
@pweil- I'm not sure how to check the pod logs..

**Comment by pweil-** [comment]
you may use `oc logs` to view pod logs, optionally with `-c` for a specific container

**Comment by catherinesword** [comment]
@pweil- Thank you! yes I see an error, saying "sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Operation not permitted". I have a sudo command in Dockerfile to restart sshd inside the container.

**Comment by mfojtik** [comment]
@catherinesword sudo is not allowed in openshift

**Comment by catherinesword** [comment]
@mfojtik you mean no sudo inside containers? But I was using the same image before, and ssh connection was fine, so I guess "sudo service ssh restart" worked..

**Comment by pweil-** [comment]
@catherinesword can you paste the output of `oc get scc anyuid -o json` for me?

**Comment by catherinesword** [comment]
@pweil- it looks like this:
```
{
    "kind": "SecurityContextConstraints",
    "apiVersion": "v1",
    "metadata": {
        "name": "anyuid",
        "selfLink": "/api/v1/securitycontextconstraints/anyuid",
        "uid": "779fc8ef-d1d3-11e5-adec-0ecafdf0bd1f",
        "resourceVersion": "72",
        "creationTimestamp": "2016-02-12T21:56:27Z",
        "annotations": {
            "kubernetes.io/description": "anyuid provides all features of the restricted SCC but allows users to run with any UID and any GID.  This is the default SCC for authenticated users."
        }
    },
    "priority": 10,
    "allowPrivilegedContainer": false,
    "defaultAddCapabilities": null,
    "requiredDropCapabilities": [
        "KILL",
        "MKNOD",
        "SYS_CHROOT",
        "SETUID",
        "SETGID"
    ],
    "allowedCapabilities": null,
    "allowHostDirVolumePlugin": false,
    "allowHostNetwork": false,
    "allowHostPorts": false,
    "allowHostPID": false,
    "allowHostIPC": false,
    "seLinuxContext": {
        "type": "MustRunAs"
    },
    "runAsUser": {
        "type": "RunAsAny"
    },
    "supplementalGroups": {
        "type": "RunAsAny"
    },
    "fsGroup": {
        "type": "RunAsAny"
    },
    "groups": [
        "system:cluster-admins"
    ]
}
```

**Comment by pweil-** [comment]
@catherinesword  looks like you're running on master.  There was a recent fix to that SCC so that it wouldn't force you to drop `setuid` and `setgid` which is probably what is causing your sudo to fail.  https://github.com/openshift/origin/pull/7247

You should be able to pull latest and give it a try

**Comment by catherinesword** [comment]
@pweil- some updates: I created a user and assigned it sudo, to try restart sshd without sudo, from pod logs it seems to work "Restarting OpenBSD Secure Shell server: sshd.", but connection still failed: "Read from socket failed: Connection reset by peer"

**Comment by pweil-** [comment]
@catherinesword are you still having issues with this or did 7247 resolve this?

**Comment by catherinesword** [comment]
@pweil- not anymore, this issue can be closed. Thank you!

**Comment by pweil-** [comment]
thanks for the update!
