### ISSUE TITLE
test-cmd new-app image stream import flake

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#7429]
`hack/../test/cmd/newapp.sh:104: executing 'oc get imagestreamtags wildfly:10.0' expecting success; re-trying every 0.2s until completion or 60.000s: the command timed out`

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/11250/consoleText

**Comment by soltysh** [comment]
I've hit that one locally yesterday, it was cause by networking problems on my local machine. After a while it just started to work normally.

**Comment by liggitt** [comment]
flake in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/2/console on https://github.com/openshift/origin/pull/8443

**Comment by smarterclayton** [comment]
Going to add debugging - if I can find a run of it.

**Comment by smarterclayton** [comment]
Fix in https://github.com/openshift/origin/pull/8558

**Comment by soltysh** [comment]
I'm reopening since we're reverting changes from #8558, @smarterclayton please link this issue in your new PR.
