### ISSUE TITLE
Use binary builds for extended tests that fetch origin repo

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7430]
We carry some extended tests that fetch the origin repo (jenkins/kubernetes is one of those). We should investigate to switch to binary builds to make that tests faster and not re-clone origin several times.

**Comment by mfojtik** [comment]
@bparees fyi.

**Comment by bparees** [comment]
some of those tests can switch to other repos too, like ruby-hello-world, depending what content they need.

**Comment by mmilata** [comment]
@mfojtik @bparees Any clue how to identify such tests?

**Comment by mfojtik** [comment]
@mmilata i would start looking at build extended tests and searching for build config fixtures that points to origin repository (jenkins might also be a candidate). Then make the BuildConfig to do a binary build (pack and send the repo from local directory instead of cloning it).

**Comment by mmilata** [comment]
There seems to be only a couple of tests which clone origin. More tests are using github.com/openshift/ruby-hello-world.git (~300KB full clone, ~100KB shallow clone), do we want to use binary builds for these too?

**Comment by bparees** [comment]
no, just origin.

**Comment by mmilata** [comment]
The openshift/origin repo doesn't seem to be used often - PR #11392 fixes two instances I've been able to find in test/extended/builds. The test in `test/extended/builds/labels.go` still clones openshift/origin because it checks image labels based on git (and cannot use ruby-hello-world because it tests for `io.openshift.build.source-context-dir` label).

Test in `test/extended/jenkins/kubernetes_plugin.go` which is mentioned in this ticket seems to be broken.

Any other ideas where to look?

**Comment by bparees** [comment]
@jupierce and @gabemontero are working on kubernetes_plugin.go, so we still want that one changed to use a binary build if possible.

I don't follow your point about the labels.go test.  We can pick another repo and set a context dir.  we might even be able to just use ruby-hello-world and set the context dir to "."

**Comment by mmilata** [comment]
@bparees setting context dir to "." did not generate the label either. I'll look for some other repo we can use.

**Comment by bparees** [comment]
@mmilata also we don't actually run the resulting image, so you can specify a context dir that doesn't result in a useable image when built.  just put some comments in the test case explaining that, if you go that path.

**Comment by mmilata** [comment]
@bparees updated the PR to use sclorg/s2i-ruby-container when testing labels.go. Not sure if the bandwith we save by not cloning origin is not less than what is needed to pull base images (openshift/base-centos7, centos/ruby-23-centos7).

I'm going to look at the jenkins test now.

**Comment by bparees** [comment]
pulling images is a cost we almost certainly are already paying and will benefit from caching, so it should be better than (re)-cloning origin.

**Comment by mmilata** [comment]
Updated the jenkins test to not clone origin - @bparees or @mfojtik PTAL at #11392.
