### ISSUE TITLE
User reported issue that router stats port health check was authenticated

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7432]
That is not expected, if this is the case our router is broken.

**Comment by smarterclayton** [comment]
@eparis for routing on the networking team

**Comment by marun** [comment]
@smarterclayton I'm assuming the check in question was for ``http://localhost:1936/healthz``?  I did see a problem on a vm dev cluster deployment related to localhost being defined in /etc/hosts only for the ipv6 local address and so not resolving to 127.0.0.1.  Once that was fixed the url was accessible and the router no longer restarted endlessly.  Does this sound like the problem in question?

**Comment by smarterclayton** [comment]
I could see that happening - something we should potentially do a check for
in ansible (if localhost doesn't resolve to 127.0.0.1 on a host, it's
broken).

**Comment by marun** [comment]
A further update here...  A request to http://[service ip]:1936/ will fail with 401 Unauthorized, but http://[service ip]:1936/healthz will return correctly.  

@smarterclayton Do you know if the user was requesting the /healthz path or /?

**Comment by smarterclayton** [comment]
I don't.  If we are good and have a test validating this there should be no
reason to leave this open (unless they are running an old DC with a new
image)

**Comment by marun** [comment]
We have extended and integration tests that rely on unauthenticated access to the haproxy health check, so I'd vote for closing the issue.

**Comment by smarterclayton** [comment]
Let me try an older DC with a new image, first.

**Comment by marun** [comment]
@smarterclayton How did the test go?

**Comment by smarterclayton** [comment]
Who knows - I think we can close this now.
