### ISSUE TITLE
Web console: empty state messages have excessive padding

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#7435]
Discussion began in [this PR](https://github.com/openshift/origin/pull/7363)

Screenshot for reference:

![log_404_cancelled](https://cloud.githubusercontent.com/assets/280512/13157316/35e6a558-d655-11e5-8af9-c88852a3fd6c.png)

The `.empty-state` class has a top margin of 150px.  It is used in a few places.

**Comment by spadgett** [comment]
I think it's OK for things like the empty project page, but pages that have tabs are an issue. Particularly build config.

**Comment by benjaminapetersen** [comment]
Yeah, prob just need some utility classes with a little more granular control.

**Comment by spadgett** [comment]
We have an `empty-state-full-page` class set already that we didn't have styles for. I'll use that.

**Comment by benjaminapetersen** [comment]
That sounds good.  

Thinking generally, we have `.gutter-top, .gutter-bottom, .gutter-top-bottom` in `_core.less`.  I could see something like `.gutter-sm, .gutter-md, .gutter-lg, .gutter-jumbo` if we wanted to ensure consistency across a variety of components. 

@sg00dwin for thoughts.  Prob not important immediately on this issue.
