### ISSUE TITLE
Web console: make tabs consistent across pages

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#7440]
Originally discussed in [this issue](https://github.com/openshift/origin/issues/7005), but breaking out into a separate item.

Summary of discussion:

> Build config has it under the Configuration tab which is not the first tab, are annotations really configuration?

Good Q here. 
- Deployments have Configuration under Details tab
- Builds have a Configuration tab that is pretty similar to the Deployment Details tab
- Builds have a Summary tab that is quite similar to the Deployments Details tab
- Should the Environment tab consistently be the 2nd tab?

I think we can sort out the Details, Summary & Configuration tabs, possibly eliminate one, then put annotations under what makes sense.  The Build chart is the key difference on these pages, but we could tweak the Deployments page to improve consistency.

I tend to think "Summary" is the better tab name, implying "the big picture".  "Details" is kind of a catch all word, but we can sort the details under the specific tabs.

Side-by-side screenshot for reference:

![screen shot 2016-02-18 at 3 03 57 pm](https://cloud.githubusercontent.com/assets/280512/13156546/ffae96c0-d650-11e5-82a8-777d7fde4283.png)

Suggested fixes:

I think this tab set makes sense to me:
- Summary
  - Build config will have the chart + list of builds
  - Deployment config page will have just the list of deployments since we have no chart right now.
- Details
  - Rename "configuration" since this tab also has a sub-heading of "configuration" which is redundant.
- Environment
  - Both have this tab
- Events
  - Only deployments has this tab

Then I can add the annotations directive under the Summary tab above the list of builds/deployments. 

Thoughts?

@spadgett @jwforres

**Comment by benjaminapetersen** [comment]
I can take this one.   I'll prob wait a bit until we are good to merge again since it will touch a bunch of templates & likely create merge conflicts.

**Comment by ajacobs21e** [comment]
@benjaminapetersen I think that tab organization makes sense

**Comment by spadgett** [comment]
Closing as we have an issue in origin-web-console now.

https://github.com/openshift/origin-web-console/issues/880
