### ISSUE TITLE
Reencrypt route failed to find destinationCACert file

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#7444]
Reencrypt routes do not currently use the default router certificates. If a reencrypt route is created without the `key` and `certifcate` values any clients trying to connect to that endpoint will fail and the following fatal error will logged in the router logs:

````
+ /usr/sbin/haproxy -f /var/lib/haproxy/conf/haproxy.config -p /var/lib/haproxy/run/haproxy.pid -sf 456
[ALERT] 048/220210 (486) : Proxy 'be_secure_test-1455819349_hawkular-metrics-reencrypt', server '172.17.0.2:8443' [/var/lib/haproxy/conf/haproxy.config:257] unable to load CA file '/var/lib/containers/router/cacerts/test-1455819349_hawkular-metrics-reencrypt.pem'.
[ALERT] 048/220210 (486) : Fatal errors found in configuration.
E0218 22:18:26.459447       1 controller.go:84] error reloading router: exit status 1
````

If the `key` and `certificate` values are added, then the route will function as expected.

The follow example works:
[route-works.txt](https://github.com/openshift/origin/files/137054/route-works.txt)

The follow example does not work. Note that this should use the routers certificate if not specified and should be a valid configuration:
[route-fails.txt](https://github.com/openshift/origin/files/137055/route-fails.txt)

**Comment by pweil-** [comment]
this error is indicating that it couldn't find the CA cert which corresponds to `destinationCaCertificate` for the reencrypt route which is separate than using the default certificates for the initial termination.  This makes me think it didn't write the file correctly or something else happened, not that it was unhappy using default certs on the reencrypt route.  Updating the title

**Comment by knobunc** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1316698 is the same issue

**Comment by knobunc** [comment]
The PR to fix this has been merged:
  https://github.com/openshift/origin/pull/8003
