### ISSUE TITLE
pkg/build/util/getStrategyImageChangeTrigger incorrect?

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7450]
This method doesn't appear to take into account that there are multiple image sources possible now.

```
// getStrategyImageChangeTrigger returns the ImageChangeTrigger that corresponds to the BuildConfig's strategy
func getStrategyImageChangeTrigger(bc *buildapi.BuildConfig) *buildapi.ImageChangeTrigger {
	for _, trigger := range bc.Spec.Triggers {
		if trigger.Type == buildapi.ImageChangeBuildTriggerType && trigger.ImageChange.From == nil {
			return trigger.ImageChange
		}
	}
	return nil
}
```

@csrwng @bparees

**Comment by bparees** [comment]
Actually that's exactly what this method is for.  It's finding the "default" ICT (if any), which is the ICT that doesn't explicitly specify what imagestreamtag it triggers off of, because it triggers off the imagestreamtag that the Strategy references.

**Comment by bparees** [comment]
https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L425-L448

**Comment by bparees** [comment]
ok on further analysis i think what you're saying is that this:
https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L428-L440

should consider the possibility that what triggered the build was an ICT associated with one of the image sources, and that if so, we should use the ICT's lastimagetriggerid as the imagesource, instead of re-resolving the image source.

**Comment by smarterclayton** [comment]
Yes.

**Comment by bparees** [comment]
marking p3.  The likelihood that we resolve a different imageid than the one that triggered the build is exceedingly low.  you'd have to be rapidly and continuously pushing images.

**Comment by bparees** [comment]
(and if you did push two images in a row like that, we'd end up building twice anyway, so the end result will be the same...the last build is going to have been built with the latest imageid).  Either we'd do two builds using the same imageid, or build1 with imageid1 and build2 with imageid2.

Of course w/ our current concurrency issues, build1's output could be what ends up in the registry, but that's unrelated to this issue.  (if anything, that problem gets worse if we fix this issue)

**Comment by smarterclayton** [comment]
Saying that we have no way of predicting what is going to be built is not inspiring confidence in our build system as a practical target for doing origin builds.

**Comment by bparees** [comment]
I don't think that's an accurate representation of what I said.  I can predict with very high confidence what is going to be built for any given build, and I can guarantee what will eventually be built in the worst case.

**Comment by smarterclayton** [comment]
But isn't that going to give me the *wrong* image?  What if I have no trigger for the image source, or no trigger for the strategy?  It didn't look to me like we re-resolved, instead it looked like we used the wrong from.

**Comment by smarterclayton** [comment]
If that's not accurate then I agree it's p3

**Comment by bparees** [comment]
>  What if I have no trigger for the image source, or no trigger for the strategy? It didn't look to me like we re-resolved, instead it looked like we used the wrong from.

imagesource refs always get resolved by this logic when we are constructing the build:
https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L428-L440

The getStrategyImageChangeTrigger has no bearing on that flow.  But regardless i have, hopefully, fixed the issue now.
