### ISSUE TITLE
Regression: router is error when i update it for 1.1.3

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#7452]
hi,
when i change the route images to 1.1.3.it is error,the error log as:
User "system:openshift-router" cannot update routes/status in project "default"
![router-error](https://cloud.githubusercontent.com/assets/12937669/13169902/7b6002a4-d723-11e5-831a-4eef832b8793.jpg)
but when i use openshift/origin-haproxy-router:v1.1.1.1 or openshift/origin-haproxy-router:v1.1.2 that will be ok.
![router-ok](https://cloud.githubusercontent.com/assets/12937669/13169910/88e233b6-d723-11e5-886f-88e2d7887018.jpg)
I update the route form 1.0.x to 1.1.x/1.1.2 that also is ok。
hown can i do for the 1.1.3?
thank!

**Comment by mfojtik** [comment]
@wenskys you have to run `oadm policy reconcile-cluster-roles --confirm` to fix this problem

**Comment by mfojtik** [comment]
@smarterclayton probably worth to include this command in the release text ;-) (i got broken by upgrading from 1.1.2 to 1.1.3)

**Comment by smarterclayton** [comment]
We need to probably fail gracefully if we don't have permission.  That's the bug and has to be fixed.

**Comment by smarterclayton** [comment]
Fixed in #7472, will push a new image when it merges.

**Comment by wenskys** [comment]
Thank you for your help，waiting for your good news.

**Comment by smarterclayton** [comment]
Updated image has been pushed
