### ISSUE TITLE
Evaluate Parity of e2e build product , adopt test/e2e/e2e.go if possible/necessary.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#7454]
From https://github.com/openshift/origin/pull/7049 .

recap
- about a month or so ago we decided we wanted kube e2e in openshift releases
- since then, two efforts at there were underway.
- one effort lead to a library in upstream kube that could be reused.  This was @liggitt s idea originally.
- meanwhile, in parallel, improvements to extended tests were underway, including complete packaging of the upstream e2e with another wrapper similar to the e2e.go library, curated in openshift. 
- now we should converge the first efforts libification of  `test/e2e/e2e.go` with what we have in openshift, 

in particular... next steps for extended tests (which are located in `test/extended/util/test.go`)
- make sure all upstream args are all supported.
- make sure no dupe between test/extended/util/test.go vs upstream e2e.go.
- make sure strict superset, document it as such, so that the "supersettiness" of extended tests never goes away.  

I can look into this today and put a patch if one is needed.

**Comment by jayunit100** [comment]
cc @timothysc @liggitt @smarterclayton

**Comment by smarterclayton** [comment]
Closing due to age.
