### ISSUE TITLE
Can't see full label value creating from template on iOS

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7462]
The label value is truncated, and I can't see the full value.

![screen shot 2016-02-19 at 11 57 49 am](https://cloud.githubusercontent.com/assets/1167259/13182576/6c9aae36-d700-11e5-95ec-0d49117cd212.png)

**Comment by benjaminapetersen** [comment]
Hmm. And these can get rather long. 
We could swap some CSS:
```sass
// take off the .truncate class which does this:
text-overflow: ellipsis;
white-space: wrap;
// and add a .break-word class that would do this:
word-break: break-all;
```
then we can get this:
![screen shot 2016-02-23 at 10 16 03 am](https://cloud.githubusercontent.com/assets/280512/13255922/7a8ed0bc-da16-11e5-888b-c75036b3424d.png)

Still looks a little odd, but is usable.

**Comment by benjaminapetersen** [comment]
If we are good with that change I can PR it.

**Comment by spadgett** [comment]
I feel like it would be better to stack both the inputs and the values at mobile rather than showing them side-by-side.

**Comment by benjaminapetersen** [comment]
I imagine this happens on Android as well.

**Comment by benjaminapetersen** [comment]
I'm guessing we would have to stack + drop the truncate as well.
We could stack them, and the form like you mentioned on the prev PR for osc-key-values.  

Should we also add new values to the top of the list then?  Every time you "add" puts the new entries at the bottom.  If everything is stacked on mobile, I could see that being a bit annoying if you had to scroll up and down to see additions.

**Comment by benjaminapetersen** [comment]
Btw, I can take this one since I did the last layout update.

**Comment by jwforres** [comment]
this was resolved when we switched to the KVE
