### ISSUE TITLE
build failures on master 

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#7463]
As this today when building origin/master I get strange dep issues causing failed builds: 

https://paste.fedoraproject.org/325876/55901396/

**Comment by jayunit100** [comment]
building Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubectl.go is failing for me 
```
hack/build-go.sh test/extended/extended.test
++ Building go targets for linux/amd64: test/extended/extended.test
# k8s.io/kubernetes/test/e2e
Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubectl.go:460: assignment count mismatch: 2 = 3
```

**Comment by liggitt** [comment]
@jayunit100 your issue is fixed in https://github.com/openshift/origin/pull/7455, repull from master
@timothysc you might be hitting http://lists.openshift.redhat.com/openshift-archives/dev/2016-February/msg00084.html

**Comment by timothysc** [comment]
wiping $GOPATH/pkg/* fixes ...
