### ISSUE TITLE
Route extends outside box on overview page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7473]
Regression (previous issue #5285 and fix #5440).

<img width="432" alt="screen shot 2016-02-19 at 1 35 22 pm" src="https://cloud.githubusercontent.com/assets/1167259/13185173/b7a28324-d70d-11e5-91ae-a538abd6d24f.png">

/cc @jwforres @sg00dwin @rhamilto

**Comment by rhamilto** [comment]
My bad.  I fix.

**Comment by rhamilto** [comment]
@spadgett, is this possibly a caching issue?  I'm unable to reproduce.

<img width="381" alt="screen shot 2016-02-19 at 4 24 50 pm" src="https://cloud.githubusercontent.com/assets/895728/13189432/6291dbb0-d725-11e5-8610-45d14dcacc37.PNG">

**Comment by spadgett** [comment]
Disabled caches. Still seeing it. I think I have your change because of the smaller metadata font size.

<img width="487" alt="screen shot 2016-02-19 at 4 35 43 pm" src="https://cloud.githubusercontent.com/assets/1167259/13189701/e48bb522-d726-11e5-9f2a-bcc799a72328.png">

**Comment by spadgett** [comment]
Adding `width: 100%;` to the `.component` div fixes it.

![iphone_6s_-_iphone_6s___ios_9_2__13c75_](https://cloud.githubusercontent.com/assets/1167259/13189934/5358e226-d728-11e5-9c42-e57efdba0649.png)

**Comment by rhamilto** [comment]
GRRR.  I can't get my environment functioning.  Mind fixing this, @spadgett?

**Comment by rhamilto** [comment]
Nevermind, @spadgett.  I think I got my enviro back.

**Comment by spadgett** [comment]
Fixed by #7487
