### ISSUE TITLE
Follow log link not showing up on initial page load

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7478]
It appears only after I resize the page. Seen in Firefox and Chrome.

![screen shot 2016-02-19 at 3 40 23 pm](https://cloud.githubusercontent.com/assets/1167259/13188380/33b33538-d71f-11e5-9207-73ddc1fa40bd.png)

/cc @jwforres

**Comment by jwforres** [comment]
Yep i just recreated this myself a few mins ago @benjaminapetersen

**Comment by spadgett** [comment]
It's calling `updateScrollLinksVisibility` once before content is added the the DOM, then not calling it again until there's a new log message or resize.

**Comment by benjaminapetersen** [comment]
- [ ] Updating this with a `$interval()` at `1000` as well as using the onResize.  That should be sufficient, will destroy the `$interval` in `$scope.$on('$destroy')`.  

- [ ] Also adding an ellipsis to indicate something will happen when the logs have not yet been given permission to run (pending pod, etc):

![screen shot 2016-02-22 at 9 38 22 am](https://cloud.githubusercontent.com/assets/280512/13221290/b1204b84-d948-11e5-9ab0-44f4c6828651.png)

**Comment by spadgett** [comment]
I don't think the $interval should be necessary. We know when we append content to the log and already check on resize. Need to understand why the update doesn't work when we first set log content.

**Comment by benjaminapetersen** [comment]
Yeah thats what I'm not sure about.  The `$interval` works, but seems like it shouldn't be needed.  Tinkering a bit more to see why its missing that first tick.
