### ISSUE TITLE
Template label disallows parameter

### ISSUE THREAD

**Issue by f-w** [openshift/origin#7483]
I can use parameter in labels defined in objects, but not at template/labels level. I got following error when uploading the template using `oc create`:

```
labels: invalid value '${APPLICATION_NAME}', Details: must have at most 63 characters, matching regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?: e.g. "MyValue" or ""
```

It would be nice to allow labels here.

**Comment by liggitt** [comment]
when you process a template in order to substitute parameter values, you get back a list of objects, not the template object itself, so you would never see a value substituted into a template label
