### ISSUE TITLE
oc start-build from binary source timed out

### ISSUE THREAD

**Issue by f-w** [openshift/origin#7489]
Hi, I created a template based on default `nodejs-mongodb-example` except replacing source of BuildConfig with:

```
      "spec": {
        "source": {
          "type": "Binary",
          "binary": {
            "asFile": "webapp.tar"
          },
          "contextDir": "${CONTEXT_DIR}"
        },

```

When I start build from CLI, I got time out error:

```
$ oc start-build nodejs-mongodb-binary-src --from-dir=xxx
WARNING: Specifying environment variables with binary builds is not supported.
Uploading "xxx" at commit "HEAD" as binary input for the build ...
Uploading directory "xxx" as binary input for the build ...
Error from server: Timeout: timed out waiting for build nodejs-mongodb-binary-src-3 to start after 1m0s
```

The folder `xxx` is small (<1MB) so timeout shouldn't be caused by tar. Any clue where the problem might happen?

Thanks

**Comment by smarterclayton** [comment]
The server only waits 1m for the base image to start.  I think that we probably need to increase the timeout, or put it under the client's control.

**Comment by f-w** [comment]
Thanks for looking into it. The small project I am trying to build is [bca-api](https://github.com/BCDevExchange/bca-api). The template is available [here](https://github.com/BCDevOps/templates/blob/master/nodejs-mongodb-binary-src.json).
