### ISSUE TITLE
Services should be grouped together in oc status when they apply to the same DC

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7503]
Services that both select the same DC should be listed on subsequent lines, with the DC being under, i.e.:
1. Service 1 selects foo=bar
2. Service 2 selects foo=bar
3. DC exposes foo=bar

Output should be

```
svc/1
svc/2
  dc ...
```

**Comment by smarterclayton** [comment]
This should be done after #7502 (which is more important for 1.2)

**Comment by deads2k** [comment]
Not quite what we want.  That is only reasonable if they expose **exactly** the same dc/rc/pods (there's a named edge type that you're looking for matches on).  If any of them expose something "extra" they can't be combined.

It is also reasonable (more reasonable in fact) to collapse services with the same selector.

**Comment by smarterclayton** [comment]
Yeah, I meant selector (as demonstrated by my example).
