### ISSUE TITLE
About the save-artifacts in s2i scripts

### ISSUE THREAD

**Issue by thincal** [openshift/origin#7505]
It is said that the save-artifacts will `gather all the dependencies into a tar file and streamed to the standard output.`, then the assemble will restore the build artifacts. But I don't understand that:

where is the tar file saved to and so that the assemble can restore it from ?

Is there any complete example for this ?

**Comment by thincal** [comment]
And I follow the [example](https://github.com/openshift/source-to-image/blob/master/examples/nginx-app/save-artifacts) to create a save-artifacts script, but it seems that it is not invoked during the build (assemble/run is invoked normally), so that is there some additional setting for that ?

**Comment by mfojtik** [comment]
@thincal the tar gets extracted into the source location (I believe it is workdir), so when we then run assemble, the previous build artifacts are already there (`./vendor` in rubygems for example). In OpenShift you need to enable this behavior by setting `incremental: true` in build config. More info: https://github.com/openshift/source-to-image#incremental-builds

**Comment by danmcp** [comment]
Feel free to reopen if you feel this issue hasn't been resolved.
