### ISSUE TITLE
genbashcomp order is not stable to movement within command group

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7510]
It appears that genbashcomp is ordered by the order the command was added to the parent command, not by a stable ordering.  We should have it be in a stable order (alphabetical under a command) when generated to avoid big diffs.

**Comment by smarterclayton** [comment]
@fabianofranz @nak3 fyi, might be an upstream issue as well.

**Comment by nak3** [comment]
@fabianofranz You are working on this? (I thought so, since you were assigned. sorry I'm not familiar with the workflow...)
This can solve in the same manner as https://github.com/kubernetes/kubernetes/pull/23801

**Comment by nak3** [comment]
And it will solve https://github.com/openshift/origin/issues/5290 as well.

**Comment by fabianofranz** [comment]
@nak3 not currently working on this.
