### ISSUE TITLE
oc rsh should use "/bin/sh -i" not /bin/bash

### ISSUE THREAD

**Issue by bparees** [openshift/origin#7514]
the "-i" is needed so SCL enablement of our s2i images works correctly, but it makes sense anyway that the rsh shell be launched as interactive.

using /bin/bash is problematic since not all images include /bin/bash.

**Comment by bparees** [comment]
@smarterclayton fyi

**Comment by bparees** [comment]
@ncdc starting w/ you because you're the only person i know was involved in rsh, but please reassign to a better candidate as needed.

**Comment by mfojtik** [comment]
@bparees I can take a look today
