### ISSUE TITLE
Pods should not scheduled to unhealthy node

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#7515]
Currently when a node have some problems like:
1. docker pool is full 
2. continue high cpu usage
...
Which will block the kubelet process to start container on the host,  the scheduler will still schedule the pods to the "unhealthy" node, that will make the pod keeps pending ....
We should have a way to check the node have enough ability to start the container on the node before schedule the pod .

**Comment by wanghaoran1988** [comment]
@ncdc I think this [card](https://trello.com/c/Z0WlNSs3/182-8-kubelet-health-monitoring) will deal with this , right ?

**Comment by ncdc** [comment]
Origin 1.2 will avoid scheduling to nodes that are OutOfDisk (e.g. Docker pull is at capacity).

This [card](https://trello.com/c/PHrRxLjS/257-3-r-d-qos-kubelet-eviction-policy-when-a-node-is-running-low-on-compute-resources-node-reliability) isn't exactly your item 2, but it does address a related concern.

I'd like to close this issue in favor of the Trello cards. Any objections?

**Comment by wanghaoran1988** [comment]
@ncdc fell free to close, thanks, will track the card instead.
