### ISSUE TITLE
Events table should link to resource

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7523]
Now that we have browse pages for these resources, the events table should link there. Might be tricky for builds and deployments since we need to know the config.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13222277/39d63b9c-d94d-11e5-899b-2b8c13b4ccc4.png)

/cc @jwforres

**Comment by jwforres** [comment]
Builds has a decent fallback page when you don't know the config.
Deployments is trickier since we make assumptions about it being a vanilla
replication controller.

**Comment by spadgett** [comment]
> Deployments is trickier since we make assumptions about it being a vanilla replication controller.

I want to fix that to use the same view. Vanilla RCs and deployments both have tabs now, so shouldn't be too hard.
