### ISSUE TITLE
Missing status icon for ContainerCreating in web console

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7532]
We might default to no icon for unrecognized values.

![screen shot 2016-02-22 at 2 54 22 pm](https://cloud.githubusercontent.com/assets/1167259/13230651/373610a2-d974-11e5-9f60-984ab86181a5.png)

/cc @jwforres

**Comment by jwforres** [comment]
@spadgett how often does this show up? should we go ahead and put a fix in for this?

**Comment by spadgett** [comment]
I've only seen it once. I was going to add this one and remove the ? for unrecognized statuses.
