### ISSUE TITLE
Web console: logs don't load when pod moves from pending to running

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7533]
When I open the log tab when the pod is pending, the logs don't start streaming when the pod starts running. I need to refresh the page or navigate away and back.

/cc @jwforres @benjaminapetersen

**Comment by benjaminapetersen** [comment]
I was seeing this as well.  Looking at it.

**Comment by benjaminapetersen** [comment]
Ah, on this page the var for letting the log run is in the GET, not the WATCH. Will fix.
