### ISSUE TITLE
du: invalid zero-length file name

### ISSUE THREAD

**Issue by eparis** [openshift/origin#7537]
atomic-openshift-3.1.1.904-1.git.0.c2ef7e0.el7.x86_64

This error comes from: `Godeps/_workspace/src/github.com/google/cadvisor/fs/fs.go`

```
Feb 22 15:32:15 node2 atomic-openshift-node[38241]: I0222 15:32:15.743753   38241 fsHandler.go:96] failed to collect filesystem stats - du command failed on  with output du: invalid zero-length file name
Feb 22 15:32:15 node2 atomic-openshift-node[38241]: - exit status 1
Feb 22 15:33:08 node2 atomic-openshift-node[38241]: I0222 15:33:08.841570   38241 fsHandler.go:96] failed to collect filesystem stats - du command failed on  with output du: invalid zero-length file name
Feb 22 15:33:08 node2 atomic-openshift-node[38241]: - exit status 1
Feb 22 15:33:15 node2 atomic-openshift-node[38241]: I0222 15:33:15.749696   38241 fsHandler.go:96] failed to collect filesystem stats - du command failed on  with output du: invalid zero-length file name
Feb 22 15:33:15 node2 atomic-openshift-node[38241]: - exit status 1
Feb 22 15:34:08 node2 atomic-openshift-node[38241]: I0222 15:34:08.847701   38241 fsHandler.go:96] failed to collect filesystem stats - du command failed on  with output du: invalid zero-length file name
Feb 22 15:34:08 node2 atomic-openshift-node[38241]: - exit status 1
Feb 22 15:34:15 node2 atomic-openshift-node[38241]: I0222 15:34:15.755409   38241 fsHandler.go:96] failed to collect filesystem stats - du command failed on  with output du: invalid zero-length file name
Feb 22 15:34:15 node2 atomic-openshift-node[38241]: - exit status 1
```

```
allowDisabledDocker: false
apiVersion: v1
dnsDomain: cluster.local
dockerConfig:
  execHandlerName: ""
iptablesSyncPeriod: "5s"
imageConfig:
  format: openshift3/ose-${component}:${version}
  latest: false
kind: NodeConfig
kubeletArguments: 
masterKubeConfig: system:node:10.12.7.173.kubeconfig
networkPluginName: redhat/openshift-ovs-multitenant
# networkConfig struct introduced in origin 1.0.6 and OSE 3.0.2 which
# deprecates networkPluginName above. The two should match.
networkConfig:
   mtu: 1450
   networkPluginName: redhat/openshift-ovs-multitenant
nodeName: 10.12.7.173
podManifestConfig:
servingInfo:
  bindAddress: 0.0.0.0:10250
  certFile: server.crt
  clientCA: ca.crt
  keyFile: server.key
volumeDirectory: /var/lib/origin/openshift.local.volumes
proxyArguments:
  proxy-mode:
     - iptables
```

**Comment by eparis** [comment]
I don't see any particular failures, just log spam.

**Comment by mwringe** [comment]
@danmcp the cadvisor integration with OpenShift is not something I am familiar with and doesn't really fall under the control of what we are doing with origin-metrics. Would there not be someone else more appropriate to take on this issue?

**Comment by ncdc** [comment]
I think this is because of https://github.com/google/cadvisor/pull/1035

**Comment by ncdc** [comment]
Possibly fixed by https://github.com/google/cadvisor/pull/1097

**Comment by ncdc** [comment]
Nope, not fixed by 1097. Will probably need a new patch.

**Comment by ncdc** [comment]
Will be fixed by https://github.com/google/cadvisor/pull/1122

**Comment by ncdc** [comment]
This is log spam, but harmless. It looks like the upstream fix is going to be in cadvisor 0.22.0 which hasn't been released yet. I'm not sure if kube 1.2 would bump up to that version this late in the release process. I've asked Vish and Tim St. Clair and hope to hear something back today. If this doesn't end up making it into kube 1.2, would we want to cherry pick the fix into our cadvisor Godep in origin?

@pweil- @smarterclayton

**Comment by pweil-** [comment]
If it's harmless and isn't picked up I'd lean towards not carrying a patch on another dependency and just release noting it.  I can't say there isn't precedent though.

**Comment by smarterclayton** [comment]
Is it enough log spam it confuses customers?

**Comment by ncdc** [comment]
It will show up at least once a minute by default.

**Comment by smarterclayton** [comment]
Small carries like this we've usually done for this reason.

**Comment by ncdc** [comment]
I'm ok with a carry like this given we would expect to drop it once we get a newer version of cadvisor

**Comment by pweil-** [comment]
then Carry On (my wayward son) .... sorry, it's Friday

**Comment by ncdc** [comment]
This will be pulled in via the next Kube rebase

**Comment by ncdc** [comment]
This is in now, closing.
