### ISSUE TITLE
Web console runtime exception getting route warnings

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7540]
Happens on the overview. /cc @jwforres 

![screen shot 2016-02-22 at 4 11 24 pm](https://cloud.githubusercontent.com/assets/1167259/13232904/1ceacf3e-d97f-11e5-869c-100113dd647d.png)

**Comment by benjaminapetersen** [comment]
This could probably use `_.get(route, 'spec.to.kind') `, though it may be simpler just to:
```javascript
if(!route) {
    return;
}
```
I can take care of this quick.

**Comment by benjaminapetersen** [comment]
Ah, looks like you got a PR, nevermind :)
