### ISSUE TITLE
All ports seem to be blocked after ansible install

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin#7546]
Description of problem:
I performed an ansible install of openshift origin.  If I am on the local machine, I can bring up openshift in the browser.  However, on any external machine, I am no longer able to access anything on the openshift master.  I am unable to ssh, or visit the openshift web console in a browser.  I checked iptables and all of the necessary ports are open.  I even stopped it.  Firewalld is also not running.  I was able to ssh prior to the ansible install but something during that install blocked all external traffic.  How do I open things back up?  When I uninstall openshift using the same playbook the network is restored.

```
ip addr list:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether bc:5f:f4:ca:49:a7 brd ff:ff:ff:ff:ff:ff
    inet 23.25.149.227/29 brd 23.25.149.231 scope global enp1s0f0
       valid_lft forever preferred_lft forever
    inet6 2601:446:1:a00::dd14/128 scope global dynamic 
       valid_lft 603499sec preferred_lft 603499sec
    inet6 2601:446:1:a00:be5f:f4ff:feca:49a7/64 scope global noprefixroute dynamic 
       valid_lft 183782sec preferred_lft 183782sec
    inet6 fe80::be5f:f4ff:feca:49a7/64 scope link 
       valid_lft forever preferred_lft forever
3: enp1s0f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN qlen 1000
    link/ether bc:5f:f4:cb:a2:2b brd ff:ff:ff:ff:ff:ff
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 52:54:00:3f:16:1b brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master virbr0 state DOWN qlen 500
    link/ether 52:54:00:3f:16:1b brd ff:ff:ff:ff:ff:ff
7: lbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP 
    link/ether ea:60:65:20:6e:57 brd ff:ff:ff:ff:ff:ff
    inet 10.1.0.1/24 scope global lbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::b85d:61ff:fecc:39c3/64 scope link 
       valid_lft forever preferred_lft forever
8: vovsbr@vlinuxbr: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast master ovs-system state UP 
    link/ether f2:b2:07:13:20:8a brd ff:ff:ff:ff:ff:ff
    inet6 fe80::f0b2:7ff:fe13:208a/64 scope link 
       valid_lft forever preferred_lft forever
9: vlinuxbr@vovsbr: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast master lbr0 state UP 
    link/ether ea:60:65:20:6e:57 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::e860:65ff:fe20:6e57/64 scope link 
       valid_lft forever preferred_lft forever
10: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN 
    link/ether 7e:03:7e:f5:fa:7d brd ff:ff:ff:ff:ff:ff
11: br0: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN 
    link/ether 46:00:d8:3a:da:47 brd ff:ff:ff:ff:ff:ff
12: tun0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether ba:cb:ea:b4:fd:84 brd ff:ff:ff:ff:ff:ff
    inet 10.1.0.1/24 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::b8cb:eaff:feb4:fd84/64 scope link 
       valid_lft forever preferred_lft forever

ip route
default via 23.25.149.230 dev enp1s0f0  proto static  metric 100 
10.1.0.0/16 dev tun0  proto kernel  scope link 
23.25.149.224/29 dev enp1s0f0  proto kernel  scope link  src 23.25.149.227  metric 100 
172.30.0.0/16 dev tun0  scope link 
192.168.122.0/24 dev virbr0  proto kernel  scope link  src 192.168.122.1 
```

**Comment by deanpeterson** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
@sdodson @dcbw @danwinship does this sound familiar?

**Comment by danwinship** [comment]
What exactly does "iptables-save" show?

**Comment by deanpeterson** [comment]
Here is the output, but I want to mention; even if I turn iptables off, the machine is still unreachable

`iptables-save
# Generated by iptables-save v1.4.21 on Tue Feb 23 09:10:41 2016
*mangle
:PREROUTING ACCEPT [7069509:1043884221]
:INPUT ACCEPT [7057378:1041548716]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [7114768:954198837]
:POSTROUTING ACCEPT [7114844:954213437]
-A POSTROUTING -o virbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
-A POSTROUTING -o virbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
-A POSTROUTING -o virbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
COMMIT
# Completed on Tue Feb 23 09:10:41 2016
# Generated by iptables-save v1.4.21 on Tue Feb 23 09:10:41 2016
*nat
:PREROUTING ACCEPT [6:1072]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [54:3506]
:POSTROUTING ACCEPT [54:3506]
:DOCKER - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-SEP-6EENMJPKGRCFLJBI - [0:0]
:KUBE-SEP-BTVMZNNKO5QJGB6B - [0:0]
:KUBE-SEP-LLQGWT7B44UOUHGP - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-3VQ6B3MLH7E2SZT4 - [0:0]
:KUBE-SVC-BA6I5HTZKAAAJT56 - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 192.168.122.0/24 -d 224.0.0.0/24 -j RETURN
-A POSTROUTING -s 192.168.122.0/24 -d 255.255.255.255/32 -j RETURN
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p udp -j MASQUERADE --to-ports 1024-65535
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -j MASQUERADE
-A POSTROUTING -s 192.168.122.0/24 -d 224.0.0.0/24 -j RETURN
-A POSTROUTING -s 192.168.122.0/24 -d 255.255.255.255/32 -j RETURN
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p udp -j MASQUERADE --to-ports 1024-65535
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -j MASQUERADE
-A POSTROUTING -s 10.1.0.0/24 ! -o lbr0 -j MASQUERADE
-A POSTROUTING -s 10.1.0.0/16 ! -d 10.1.0.0/16 -j MASQUERADE
-A POSTROUTING -s 192.168.122.0/24 -d 224.0.0.0/24 -j RETURN
-A POSTROUTING -s 192.168.122.0/24 -d 255.255.255.255/32 -j RETURN
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p udp -j MASQUERADE --to-ports 1024-65535
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -j MASQUERADE
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4d415351 -j MASQUERADE
-A KUBE-SEP-6EENMJPKGRCFLJBI -s 23.25.149.227/32 -m comment --comment "default/kubernetes:https" -j MARK --set-xmark 0x4d415351/0xffffffff
-A KUBE-SEP-6EENMJPKGRCFLJBI -p tcp -m comment --comment "default/kubernetes:https" -m tcp -j DNAT --to-destination 23.25.149.227:8443
-A KUBE-SEP-BTVMZNNKO5QJGB6B -s 23.25.149.227/32 -m comment --comment "default/kubernetes:dns" -j MARK --set-xmark 0x4d415351/0xffffffff
-A KUBE-SEP-BTVMZNNKO5QJGB6B -p udp -m comment --comment "default/kubernetes:dns" -m udp -j DNAT --to-destination 23.25.149.227:53
-A KUBE-SEP-LLQGWT7B44UOUHGP -s 23.25.149.227/32 -m comment --comment "default/kubernetes:dns-tcp" -j MARK --set-xmark 0x4d415351/0xffffffff
-A KUBE-SEP-LLQGWT7B44UOUHGP -p tcp -m comment --comment "default/kubernetes:dns-tcp" -m tcp -j DNAT --to-destination 23.25.149.227:53
-A KUBE-SERVICES -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES -d 172.30.0.1/32 -p udp -m comment --comment "default/kubernetes:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-3VQ6B3MLH7E2SZT4
-A KUBE-SERVICES -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-BA6I5HTZKAAAJT56
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-3VQ6B3MLH7E2SZT4 -m comment --comment "default/kubernetes:dns" -j KUBE-SEP-BTVMZNNKO5QJGB6B
-A KUBE-SVC-BA6I5HTZKAAAJT56 -m comment --comment "default/kubernetes:dns-tcp" -j KUBE-SEP-LLQGWT7B44UOUHGP
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-6EENMJPKGRCFLJBI
COMMIT
# Completed on Tue Feb 23 09:10:41 2016
# Generated by iptables-save v1.4.21 on Tue Feb 23 09:10:41 2016
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [6909336:864539191]
:DOCKER - [0:0]
:OS_FIREWALL_ALLOW - [0:0]
-A INPUT -i virbr0 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i virbr0 -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -i virbr0 -p udp -m udp --dport 67 -j ACCEPT
-A INPUT -i virbr0 -p tcp -m tcp --dport 67 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8443 -j ACCEPT
-A INPUT -i virbr0 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i virbr0 -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -i virbr0 -p udp -m udp --dport 67 -j ACCEPT
-A INPUT -i virbr0 -p tcp -m tcp --dport 67 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -i tun0 -m comment --comment "traffic from docker for internet" -j ACCEPT
-A INPUT -p udp -m multiport --dports 4789 -m comment --comment "001 vxlan incoming" -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j OS_FIREWALL_ALLOW
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A INPUT -p tcp -m tcp --dport 8443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A FORWARD -d 192.168.122.0/24 -o virbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 192.168.122.0/24 -i virbr0 -j ACCEPT
-A FORWARD -i virbr0 -o virbr0 -j ACCEPT
-A FORWARD -o virbr0 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -i virbr0 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -d 192.168.122.0/24 -o virbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 192.168.122.0/24 -i virbr0 -j ACCEPT
-A FORWARD -i virbr0 -o virbr0 -j ACCEPT
-A FORWARD -o virbr0 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -i virbr0 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -o lbr0 -j DOCKER
-A FORWARD -o lbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lbr0 ! -o lbr0 -j ACCEPT
-A FORWARD -i lbr0 -o lbr0 -j ACCEPT
-A FORWARD -s 10.1.0.0/16 -j ACCEPT
-A FORWARD -d 10.1.0.0/16 -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A OUTPUT -o virbr0 -p udp -m udp --dport 68 -j ACCEPT
-A OUTPUT -o virbr0 -p udp -m udp --dport 68 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 8080 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 8443 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 4001 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 8443 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 8444 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 53 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 53 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24224 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 24224 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 2224 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 5404 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 5405 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9090 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 10250 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 10255 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 10255 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 4789 -j ACCEPT
COMMIT
`

**Comment by danwinship** [comment]
> but I want to mention; even if I turn iptables off, the machine is still unreachable

Does "iptables-save" show an empty rule set after you do whatever you're doing to turn iptables off?

**Comment by sdodson** [comment]
Can you try isolating whether it's the installer or node? I think we could achieve this by running the installer to get to a point where you cannot ssh in, mask the node service, reboot, and attempt to ssh in. If that works then unmask the node, start it, and try to ssh in, does it fail? Be sure not to run `iptables-save` at any point by hand.

To mask the node service 
`systemctl mask origin-node ; reboot` 
Then after SSH'ing back in
`systemctl unmask origin-node ; systemctl start origin-node`

**Comment by deanpeterson** [comment]
Unfortunately the machine is at home.  I had to go into the office today and will try this when I get home, thanks.

**Comment by deanpeterson** [comment]
Wait, I'm not sure what you mean.  I run the ansible playbook to install the master and node on the same machine.  It just runs and doesn't ask for input.

**Comment by sdodson** [comment]
Both the installer and the node create iptables rules. If we mask the node so it doesn't start and reboot then only the rules created by the installer would be in place. If you're not locked out after rebooting we know that it's a problem with the rules that the node service creates when it starts.

**Comment by deanpeterson** [comment]
I ran "systemctl mask origin-node ; reboot".  When the machine rebooted I was able to reach the machine again.  When I ran "systemctl unmask origin-node ; systemctl start origin-node" the machine was immediately inaccessible again.

**Comment by sdodson** [comment]
Great thanks @deanpeterson.
@danwinship sounds like the node is populating some rules that don't work for his config.

**Comment by danwinship** [comment]
I don't think it's iptables. The rule dump above looks like it ought to be letting through all traffic to port 22.

Is there some sort of IP addressing conflict? Does the machine you're trying to connect from (or some router in between) have an address in the 10.1.0.0/16 or 172.30.0.0/16 range?

**Comment by deanpeterson** [comment]
Yes, actually it is in the 10.1.0.0/16 range.

**Comment by deanpeterson** [comment]
That is what it was.  I tried accessing it on a machine outside the 10.1.0.0/16 network and I can.

**Comment by sdodson** [comment]
@deanpeterson you can set the osm_cluster_network_cidr ansible variable to adjust the SDN network so that it doesn't conflict with anything in your environment, like this: 

`osm_cluster_network_cidr=192.168.0.0/16`

This must be set during initial installation and cannot be changed afterwards.

**Comment by deanpeterson** [comment]
Unfortunately I get this error when I add teh osm_cluset_network_cidr value:

failed: [23.25.149.227] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:00.267628", "end": "2016-02-24 23:20:41.879683", "failed": true, "failed_when_result": true, "rc": 1, "start": "2016-02-24 23:20:41.612055", "stdout_lines": [], "warnings": []}
stderr: unable to connect to a server to handle "imagestreamlists": Get 23.25.149.227:8443/oapi: dial tcp 23.25.149.227:8443: connection refused

FATAL: all hosts have already failed -- aborting

**Comment by sdodson** [comment]
Your master isn't running for some reason, can you look at into why it's
not running?

**Comment by deanpeterson** [comment]
Well, when I add the osm_cluster_network_cidr value I get the error.  When I remove it and try again, everything starts up.  It does not like the osm_cluster_network_cidr property for some reason.

**Comment by sdodson** [comment]
You must completely reset your environment whenever you change
osm_cluster_network_cidr. That's what I meant by you may only set this
prior to initial installation.

From
https://docs.openshift.org/latest/install_config/configuring_sdn.html#configuring-the-pod-network-on-masters
```
Note that the *serviceNetworkCIDR* and *hostSubnetLength* values cannot be
changed after the cluster is first created, and *clusterNetworkCIDR* can
only be changed to be a larger network that still contains the original
network. e.g., given the default value of *10.1.0.0/16 <http://10.1.0.0/16>*,
you could change it to *10.0.0.0/15 <http://10.0.0.0/15>* (i.e. *10.0.0.0/16
<http://10.0.0.0/16>* plus *10.1.0.0/16 <http://10.1.0.0/16>*) but not
to *10.2.0.0/16
<http://10.2.0.0/16>* (since that does not overlap the original value).
```

**Comment by deanpeterson** [comment]
That's what I did.  I used the ansible uninstaller to completely remove everything.  I added the property to /etc/ansible/hosts under the os3vars section then ran the ansible installer again.  I get the error during the ansible installation process.

**Comment by sdodson** [comment]
Ok, can you post the master's logs? We need to know why it's failing to start.

**Comment by deanpeterson** [comment]
I have looked for the master's logs.  Installing with ansible, it is not clear where those might be.  Under /etc/origin there is a single "master" folder but that only contains configuration information, no logs.  Since the ansible install is not successful, there is no node folder.  

There is an ansible log under /var/log/ansible.log but that contains no useful information.

**Comment by deanpeterson** [comment]
It looks like this is the problem: SDN initialization failed: Error: Host network with IP: 192.168.122.0 conflicts with cluster network: 192.168.0.0/16

**Comment by deanpeterson** [comment]
I switched to a different subnet (per @sdodson suggestion on irc) and it works now.
