### ISSUE TITLE
Pull builder image while downloading source code

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7548]
In case you have a big source code repository (like origin...) and fresh installation of OpenShift, what will happen when you kick the build is:

1) We clone the sources (which might take some time for big repos)
2) We kick the S2I build
3) S2I will pull the builder image

In this case, you wait at 1) and then wait at 3). If we can start pulling the image while we downloading the source code, it can result in faster build :-)

To make it so, we will need:

When build start, we start pulling the builder image (for both docker and s2i strategies) and in parallel we start cloning the source code. When the cloning finishes, we can execute the build where the s2i or docker will tell you something like "image pulled by another client", but the time you will wait will be shorter because we started pulling before we started cloning source. For big repos, this means no waiting for pulling the image, for small repos it will be just minor speed improvement.

**Comment by mfojtik** [comment]
@smarterclayton what do you think?

**Comment by smarterclayton** [comment]
Yes, good idea.

**Comment by mfojtik** [comment]
Trelloed: https://trello.com/b/wqe9UaaZ/developer-experience
