### ISSUE TITLE
[Feature request] Image pull progress bar

### ISSUE THREAD

**Issue by donovanmuller** [openshift/origin#7550]
Apologies if this has come up before (tried searching through issues but found nothing similar) but it would be great to have a progress bar/percentage indicator when pulling images.

Trying to pull images over a corporate proxy can be rather slow and it would be a great help to display the Docker image pull progress on the UI. Currently, there is no way I know of checking how far the image pull is and can be rather frustrating with large images.

I realise this is something that Docker itself would have to expose (something like [this](https://github.com/docker/docker/issues/10894#issuecomment-130979420)).

**Comment by mfojtik** [comment]
@donovanmuller it is not merged to docker afaik :-(

**Comment by mfojtik** [comment]
but agree, displaying the progress would be nice to have for S2I. I think for docker build strategy, the docker build will display "some" progress (but not great due to broken terminal).

**Comment by donovanmuller** [comment]
@mfojtik Yup, this issue will probably only be relevant once the Docker bits are in place. Just logged it for  future reference.

**Comment by mfojtik** [comment]
@bparees is this fixed now when we have progress reporting thanks to @csrwng or we still want to add the HTML progress bar to the console ( @jwforres )?

**Comment by csrwng** [comment]
@mfojtik it'd be great to show it in the console... but the mechanics of it is a little complicated. The build process would have to report back to the master on progress which then would need to report back to the console. 

One idea would be to do this through events. The progress writer used in the builder could post a new event each time it writes progress. The console could then watch for events and show a graphic display based on data in the event.
