### ISSUE TITLE
Validate calls to API using swagger API in oc client

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7552]
If you try to use `oc new-build --buld-secret` against "old" master (or master that does not implement "secrets" in build), the command will succeed, but the "secrets" are not created (because we allow redundant JSON data during create and simply drop them).

It would be nice to tell users that they use newer client against older master and they are trying to use the feature that is not backed up in API , something like:

```
$ oc new-build --build-secret foo:bar
The "secrets" field is not supported in this version of OpenShift
```

To do that, we can query the swagger spec from the master you are trying to create the new build on and validate if the "secrets" field is there.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1310616

@smarterclayton @csrwng FYI

**Comment by smarterclayton** [comment]
We'd want to do very selective checks.  Agree that something better here is
a good idea (I think this is a dupe / similar to a couple of other issues,
can you search and xlink them?)

**Comment by xingxingxia** [comment]
Similar issues I know:
https://bugzilla.redhat.com/show_bug.cgi?id=1267454
https://bugzilla.redhat.com/show_bug.cgi?id=1277038
oc edit/replace is similar too.
