### ISSUE TITLE
Web console: repeated event message oddly specific, relative time doesn't update

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7556]
The message is very specific: "in the last 20 minutes and 23 seconds." We could just say "in the last 20 minutes." Since the value never updates, it can be very out of date when I leave the page open for a while. We should update the relative time using a rounded value so it's not constantly changing, or just say "5 times since &lt;whenever&gt;."

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13254538/accd4858-da0f-11e5-85fd-76d20bc31e36.png)

/cc @jwforres

**Comment by benjaminapetersen** [comment]
"5 times since <whenever>." makes sense, avoids stale information.

**Comment by jwforres** [comment]
personally i'd prefer to see  "5 times in the last 20 minutes", the problem
here is just because its using the duration filter (which does two levels
of precision) instead of using relative-timestamp (which just does one).

**Comment by benjaminapetersen** [comment]
There is an [angular-moment](https://github.com/urish/angular-moment) package that has a directive & a bunch of filters, if we want a few more w/o having to write them up ourselves.

**Comment by jwforres** [comment]
nice, go ahead an open a P3 tech-debt issue for us to switch to using that

**Comment by spadgett** [comment]
The message looks wrong.

```
<span class="text-muted small" ng-if="event.count > 1">
    ({{event.count}} times in the last
      {{event.firstTimestamp | duration:event.lastTimestamp:true}})
</span>
```

It's showing the time between the first and last event, but it says "in the last," which implies from the current time.

**Comment by spadgett** [comment]
Switching to the `duration-until-now`directive causes the timestamps to update, but it's weird to see the seconds tick in the table. We'd want less specific durations if we do that.

**Comment by jwforres** [comment]
Easy enough to add a precision option

**Comment by spadgett** [comment]
It's a bit tricky because of the interval we have in app.js to update it.

**Comment by spadgett** [comment]
I have something working.

<img width="703" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13288168/b7f96526-dad8-11e5-913f-b2a292a597a5.png">

**Comment by jwforres** [comment]
:+1:

**Comment by benjaminapetersen** [comment]
307 times in the last hour.  Is kinda busy, eh? :smile:

**Comment by spadgett** [comment]
:)

I'm glad we're debouncing in #7448. There's flicker on event updates in this project.
