### ISSUE TITLE
App unavailable during rolling upgrade

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#7562]
I've got an app which has a readiness probe defined.  The DC does not define an explicit deployment strategy and the number of pods is scaled to 1.

When I do a new build and automatic deploy, the UI suggests that deployment 2's pod comes up in parallel with deployment 1's pod.  However deployment 1's pod disappears before the readiness probe on deployment 2's pod returns successfully.  This means that I get a 503 from the route between deployments.

If I scale the DC to 2 pods and repeat the same test, I get away without any 503s, but there is a period during which one pod from deployment 1 has already been deleted *before* the first pod from deployment 2 has passed its readiness check.

If a user scales a DC to N pods, surely the expectation should be that OSE should be providing N working pods at all times if it can, regardless of things like ongoing rolling update.  Perhaps it might be necessary for the user's load or resiliency requirements.  Surely it's a bug to be deleting an old pod before the new pod readiness is good?

**Comment by jim-minter** [comment]
App YAML at https://github.com/jim-minter/ose3-demos/blob/21ffa5160a84fb894942ed1f58778ea6b00a2b9d/git/monster/openshift/ticket-monster-template.yaml

**Comment by jim-minter** [comment]
So I think the issue is not down to any problems around readiness probe logic, but instead that with one pod, and with OpenShift's maxUnavailable default of 25%, Kubernetes' logic permits a state in rolling upgrade during which no pods are available (note use of math.Ceil in extractMaxValue in Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/rolling_updater.go).

    [root@openshift ~]# docker logs e2ef3ddfadae
    I0222 10:51:44.050481       1 deployer.go:198] Deploying from demo/monster-1 to demo/monster-2 (replicas: 1)
    I0222 10:51:45.086358       1 rolling.go:232] RollingUpdater: Continuing update with existing controller monster-2.
    I0222 10:51:45.102831       1 rolling.go:232] RollingUpdater: Scaling up monster-2 from 0 to 1, scaling down monster-1 from 1 to 0 (keep 0 pods available, don't exceed 2 pods)


^^^

    I0222 10:51:45.102845       1 rolling.go:232] RollingUpdater: Scaling monster-2 up to 1
    I0222 10:51:49.188030       1 rolling.go:232] RollingUpdater: Scaling monster-1 down to 0


I've verified that manually setting maxUnavailable to 0 works around the situation for me.  However, IMO, it's a problem that our product defaults break the user's expectation of number of replicas live during rolling upgrade (this is the case both for the 1-pod and >1-pod case, due to this issue).

**Comment by smarterclayton** [comment]
It should not be possible to go to zero unless you have 100% unavailable. @kargakis @ironcladlou

**Comment by kargakis** [comment]
@smarterclayton agreed but what if maxSurge is zero? The old pod will never come down because unavailable isn't 100% and the new pod will never come up because surge is already capped by the old pod... Wrong configuration by the user?:)

**Comment by smarterclayton** [comment]
MaxSurge zero with N=1 is meaningless.  MaxSurge with N=2 can always take
down 1 pod, but wedges if the new pod comes up.  Basically when
MaxAvailability > 0% if new pods never come up then the deployment should
timeout and error.

**Comment by kargakis** [comment]
As discussed upstream, the right fix for this is to use math.Floor for maxUnavailable and preserve math.Ceil for maxSurge. I will update the upstream patch tomorrow.
