### ISSUE TITLE
Be nice to admins trying to prune images as `system:admin`

### ISSUE THREAD

**Issue by miminar** [openshift/origin#7564]
Running

```
oadm prune images 
```

as a `system:admin` results in error:

```
F0223 18:01:32.532893   21211 helpers.go:107] error: You must use a client config with a token
```

which is not much helpful and we have been asked several times

> how do I create a client config with a token?

Let's make the error more helpful with an advice, how to create such a client config. Or let's enhance help message and point the admin there.

**Comment by deads2k** [comment]
Once we get https://github.com/openshift/origin/pull/6941, it will be possible to easily get an SA token and I'm not adverse to creating such a service account in our infra namespace.  @liggitt arguments against?

Also, weren't we going to bundle the logic into a controller?  Are we waiting for scheduled jobs instead?

**Comment by miminar** [comment]
We're going to move the logic into the registry itself. `oadm prune images` will then just modify etcd and registry will clean itself up periodically. With that, client config with a token won't be necessary indeed.

**Comment by ironcladlou** [comment]
@miminar 
>We're going to move the logic into the registry itself. oadm prune images will then just modify etcd and registry will clean itself up periodically. With that, client config with a token won't be necessary indeed.
Link to an issue or Trello card for this?

**Comment by pweil-** [comment]
https://trello.com/c/3ZmBKDZZ/437-8-refactor-registry-layer-and-signature-pruning
