### ISSUE TITLE
F5 BigIP router crash loops when routing policies already exists

### ISSUE THREAD

**Issue by crak-github** [openshift/origin#7566]
Hi,
I've been looking to setup an f5 router in our dev origin cluster.
our f5 bigip version and build: 

> version 11.5.2 Build 0.0.141 Final

everything gets build and deployed correctly: all the nodes, pools and policy gets created correctly. The main issue here is that if the routing policies are already created when the router is started(or restarted), oc status tells me the pod crash loops. That would also happen if i decide to redeploy the router or spawn a new one, here it the log:

> error: Encountered an error on POST request to URL https://qcdvshosr02.dev.lan/mgmt/tm/ltm/virtual/os_10.1.8.9_http/policies: HTTP code: 409; error from F5: 01020066:3: The requested virtual server policy (/Common/os_10.1.8.9_http /Common/openshift_insecure_routes) already exists in partition Common.

*os_10.1.8.9_http being my http virtual server.

it complains until i go in each vs to remove the policy(because of the way f5 works it won't simply let me delete a policy while it's mentionned somewhere), delete the 2 routes policies, and then have the f5 router create them again, then the pod works as expected. though if i spawn a new build of the router, the new pod crash loops with the same error.

I've followed the docs on how to deploy the f5 router, is there something am missing ?

Should i provide any other details ?
Cheers,

**Comment by Miciah** [comment]
[The code that adds the policy to the vserver](https://github.com/openshift/origin/blob/f9289e1eb30ec3f75bf744104ce9898438932e44/plugins/router/f5/f5.go#L520-L561) first checks to make sure that the policy is not already there.  It appears that that check is not working.  I suspect that your F5 BIG-IP host is prepending the partition name "/Common" to the policy names whereas the F5 BIG-IP hosts that we developed and tested against did not do so.

@crak-github, is there any additional output in the log, such as, "Checking whether vserver os_10.1.8.9_http has policy openshift_insecure_routes" or, "Adding policy openshift_insecure_routes to vserver os_10.1.8.9_http..."?

Could you provide the output of `curl -k -u username:password https://qcdvshosr02.dev.lan/mgmt/tm/ltm/virtual/os_10.1.8.9_http/policies` (with the appropriate username and password substituted)?

In particular, I am curious about the value for the `name` field of the entry for your vserver.  You can pipe the output of the `curl` command through `python -m json.tool` for readability, or pipe it through `jq '.items[] | .name' ` to pull out just the `name` values using [the jq tool](http://stedolan.github.io/jq/) if you don't want to provide the full output.

**Comment by crak-github** [comment]
here is the output of the curl command:
```
{
    "kind": "tm:ltm:virtual:policies:policiescollectionstate",
    "policiesReference": {
        "isSubcollection": true,
        "items": [
            {
                "fullPath": "/Common/openshift_insecure_routes",
                "generation": 1512,
                "kind": "tm:ltm:virtual:policies:policiesstate",
                "name": "openshift_insecure_routes",
                "partition": "Common",
                "selfLink": "https://localhost/mgmt/tm/ltm/virtual/os_10.1.8.9_http/policies/~Common~openshift_insecure_
r
outes?ver=11.5.2"
            }
        ],
        "link": "https://localhost/mgmt/tm/ltm/virtual/os_10.1.8.9_http/policies?ver=11.5.2"
    },
    "selfLink": "https://localhost/mgmt/tm/ltm/virtual/os_10.1.8.9_http/policies?ver=11.5.2"
}
```

as for the log output of the container, i don't seem to have any such entries.

**Comment by Miciah** [comment]
Thanks! The structure of the JSON data returned by the F5 iControl REST API endpoint appears to have changed between F5 BIG-IP 11.5 and 11.6.  I see the following:

```json
{
    "items": [
        {
            "fullPath": "/Common/openshift_insecure_routes",
            "generation": 1178,
            "kind": "tm:ltm:virtual:policies:policiesstate",
            "name": "openshift_insecure_routes",
            "partition": "Common",
            "selfLink": "https://localhost/mgmt/tm/ltm/virtual/ose-vserver/policies/~Common~openshift_insecure_routes?ver=11.6.0"
        }
    ],
    "kind": "tm:ltm:virtual:policies:policiescollectionstate",
    "selfLink": "https://localhost/mgmt/tm/ltm/virtual/ose-vserver/policies?ver=11.6.0"
}
```

Note that `items` is at the top level rather than being subordinated under `policiesReference`.

My preference would be to leave the code that checks whether the policy is already associated with the vserver as is so it expects the newer structure, which means it will return false negatives on F5 BIG-IP 11.5, but to change the code that POSTs the policy to the vserver to log a warning and proceed if it gets an HTTP 409 response.  This will provide some compatibility with the older F5 iControl REST API whilst avoiding the burden of anticipating and parsing any one of multiple possible response formats.

We may want to log and tolerate HTTP 409 responses anywhere else we check for the existence of some resource and POST it if it does not already exist.

We could even remove the check, always POST the policy to the vserver, and just treat a 409 the same as a 2xx response, but I prefer to be more proper and check for the thing before trying to POST it.

@ramr, @rajatchopra, what are your thoughts? I can make a PR for the above if it sounds good to you.

**Comment by ramr** [comment]
@Miciah  sounds okay vis-a-vis tolerating conflicts/409s for resource POSTs. At least that should get @crak-github unblocked. That said though, am a lil' wary could there be potentially other failure paths with v11.5 iControl REST API that we don't know of [different outputs]. 

Aside: For partition paths, that error might well be valid - if you previously configured it in a different partition. But that's a smaller side issue though.

**Comment by crak-github** [comment]
after reading the comments in the pr, I've opened a ticket with f5 to ask them about the maturity of their api as we are thinking about putting this in production at one point.
parts of their answer:

> "I want to make sure and address the point of the maturity of the API in version 11.5.2, where it was an "Early Access" feature that later became an officially recognized release in 11.6.0. This is why there are not as many in-depth sources of documentation for 11.5.x, and why there are changes in the calls from the testing releases in 11.5.x to the first full release in 11.6.0."

seems like supporting the 11.5.x release might be a hassle indeed.

knowing this, i've upgraded our dev f5 to 11.6, which fixed the issue.

**Comment by rajatchopra** [comment]
Close issue based on [comment](https://github.com/openshift/origin/issues/7566#issuecomment-198499935). Release 11.6 fixes the issue.
