### ISSUE TITLE
Revise README.md for clarity

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#7568]
Hi,

The README is one of the first experiences that new users have with OpenShift, especially since GitHub renders it nicely when viewing the main repository page. Unfortunately, I think that there are a lot of meaningless buzzwords in the file, which make the project less approachable and harder for new users to understand.

Here are some quick examples illustrating this...

> This is the source repository for OpenShift Origin, based on top of Docker containers and the Kubernetes container cluster manager. Origin is a distribution of Kubernetes optimized for enterprise application development and deployment, used by OpenShift 3 and Atomic Enterprise.

The second sentence is more useful than the first, so the sentence order seems better reversed. Being based on Kubernetes and Docker, it may be worth mentioning that users can leverage the features of both, along with the additional capabilities that Origin adds on top.

> Build web-scale applications with integrated service discovery, DNS, load balancing, failover, health checking, persistent storage, and fast scaling

"web-scale" makes me roll my eyes. It's completely meaningless. Also, would it be useful to mention High Availability?

The "Features" list should be clearer about why an application developer or system operator would find OpenShift useful - maybe even dividing the list of features into two sets.

> - For a quick install of Origin, see the Getting Started Install guide.
> - For an advanced installation using Ansible, follow the Advanced Installation guide
> - To build and run from source, see CONTRIBUTING.adoc

When would someone choose Quick Install vs Ansible install? I'd suggest that the former is only useful to try it out quickly, whereas the Ansible method is recommended for production deployments.

I realize these tweaks are pretty minor in the grand scheme of things. I just had the thought while reading the readme so thought I'd file an issue. I'd be happy to submit pull requests for revised text.

**Comment by smarterclayton** [comment]
Please do
