### ISSUE TITLE
[e2e] extended-tests-output-dir : dead flag ?

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#7573]
Looks like the `--extended-tests-output-dir` flag (which is implemented using  flag, rather than pflag), is not honored in e2es.  We will need to remove it or migrate it to pflag .  

The reason (i think) is because **pflag** is **also** being used in **the same package**.

```
import (
    rflag "flag"
    ...
    flag "github.com/spf13/pflag"
```

so, the result of adding this option ==>  errors that its an invalid option: 

```
[root@ip-172-18-4-118 kubernetes]#./extended.test --ginkgo.focus="should support exec through an HTTP proxy" -extended-tests-output-dir="blah" 2>&1 | grep not
flag provided but not defined: -extended-tests-output-dir
        If set, ginkgo will only run specs that do not match this regular expression.
[root@ip-172-18-4-118 kubernetes]#./extended.test --ginkgo.focus="should support exec through an HTTP proxy" --extended-tests-output-dir="blah" 2>&1 | grep not
flag provided but not defined: -extended-tests-output-dir
```

And indeed its being packaged into the binary:

```
[root@ip-172-18-4-118 kubernetes]# grep extended-tests-output ./extended.test
Binary file ./extended.test matches
```
- I dont think you can use flags and pflags together.  
- Since upstream is using "flag", i guess we would have to use "flag" as well.  Two directions we can go
- migrate upstream e2e's to use pflag (thats probably ideal)
- migrate downstream to use flag (faster, but suboptimal)

i know this is minutia but just wanted to get all the info up in case feedback b4 i craft  a PR.  

_if no opinions i would PRobably will go with the upstream approach since eventually it will move to pflag anyway (i assume)...._

cc @smarterclayton @timothysc

**Comment by jayunit100** [comment]
Also, I grepped around: `--extended-tests-output-dir` isnt actually being used in the source from what i can tell.  So I assume nobody has caught this for that reason.  
- Another option is we could delete it if its not being used at all. the upstream runner proposed in #7474  could just be used, and the output-dir option could provide the same functionality.

**Comment by smarterclayton** [comment]
Check https://github.com/openshift/vagrant-openshift first.

**Comment by jayunit100** [comment]
dont see it there either?
```
➜  vagrant-openshift git:(master) git log | head
commit 7c49875bca96fbbde3a20c57035c1eb27141b322
Merge: b032247 e4d4497
Author: Brenton Leanhardt <bleanhar@redhat.com>
Date:   Tue Feb 23 15:30:48 2016 -0500
```
and  for 
```
grep -r extended-test ./ | grep out
```

**Comment by jayunit100** [comment]
... any preference for flags?   would prefer to reach consensus on the impl before PR as the PR is probably trivial...

**Comment by smarterclayton** [comment]
@danmcp do you remember if we needed the extended output dir for anything?

**Comment by danmcp** [comment]
@smarterclayton Doesn't ring a bell.

**Comment by jayunit100** [comment]
sounds like delete is best thing for now.  reimpl later.  ?

**Comment by smarterclayton** [comment]
Yes, you can remove.

**Comment by smarterclayton** [comment]
Closing due to age.
