### ISSUE TITLE
Show labels on tagged image

### ISSUE THREAD

**Issue by danni** [openshift/origin#7577]
I've tagged images from one project to another to do a production release, but the Overview doesn't show the LABELs for these tagged images. It would be nice to know what Git commit I'm running in prod directly from the overview.

**Comment by jwforres** [comment]
it is unlikely we would add LABELS information to the overview, however if you are using imagestreams then the new image stream tag page added in 1.3 origin / 3.3 OCP shows the LABELS for that tag.
