### ISSUE TITLE
Binary releases are unsigned

### ISSUE THREAD

**Issue by nullterminated** [openshift/origin#7578]
https://docs.openshift.org/latest/getting_started/administrators.html

TL;DR

Method 2: Download unsigned binary. Execute unsigned binary with sudo. 

![:/](http://sd.keepcalm-o-matic.co.uk/i/mckayla-maroney-not-impressed.png)

Linux Mint just happened. XCodeGhost happened not long ago. If there's no RPM, please add GPG signatures on the binaries or on checksums of the binaries. 

Thank you. Looking forward to building out a openshift/fabric8 cluster :)

**Comment by smarterclayton** [comment]
We recommend today if you are concerned with binary downloads to use the Ansible install with either the OSE release (through the RHEL channels) or use the CentOS RPMs.  We can add checksums to the binary downloads.

**Comment by nullterminated** [comment]
Hi smarterclayton. Thanks for the quick reply! I didn't see RPMs anywhere in the docs. I'd prefer RPM as it would keep software up to date for me. [This looks related](http://mirror.openshift.com/pub/origin-server/release/), but I don't see any instructions on how to make use of it. 

Do you know where I would find instructions to use the CentOS RPMs?

**Comment by nullterminated** [comment]
I think I found it.

https://docs.openshift.org/latest/install_config/install/advanced_install.html

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/pull/7597 will add a CHECKSUM to 1.1.4 that we will publish on github.  Use the RPMs if you want a signed release.
