### ISSUE TITLE
private image import does not work when secret from .docker/config.json

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#7580]
While working with #7555 I found out that the server matching isn't picking up secret when uploaded with:
```
oc secrets new mysecret .dockerconfigjson=$HOME/.docker/config.json
```
The server value in this file is: `docker.io` but either `auth.docker.io/token` or `index.docker.io/v1` are being searched for. If secret is created manually with server pointing to one of the aforementioned URLs it's working correctly.

@smarterclayton fyi
I hope to start working on it as soon as other blocker bugs are fixed. 
@pweil- mind marking this as P1, yet another one ;)

**Comment by smarterclayton** [comment]
This is already fixed and merged upstream and is in the 3.2 cherrypick list.

**Comment by soltysh** [comment]
@smarterclayton who is in charge of that cherrypick list iow. are you already handling this or should I cherrypick it?

**Comment by smarterclayton** [comment]
We're going to wait until the next rebase at this point.

**Comment by pweil-** [comment]
@soltysh - this should be ready for re-testing and closing now that the rebase has landed.

**Comment by soltysh** [comment]
@pweil- not quite, see the linked PR. There's a problem with f23 docker, which creates `docker.io` as auth endpoint instead of `https://index.docker.io`. From what @smarterclayton and @liggitt mentioned I need to fix this also on the pull side, currently working on it. But the linked PR is ready for review.

**Comment by soltysh** [comment]
The upstream is already fixed [here](https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/credentialprovider/keyring.go#L130), once linked PR is merged this will be closed as well.
