### ISSUE TITLE
oc debug follow up

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7592]
- Allow user to port forward at the same time to the new pod
- Solve the problem of users being able to create pods that they can't exec into (or at least warn better)
- Use images to lookup the entrypoint (currently it's ugly to look up an arbitrary image on OpenShift and get metadata)

**Comment by deads2k** [comment]
Create an env var with the original command. That way I can try it over and over while I'm debugging.

**Comment by deads2k** [comment]
I'd really like this command to do a priority order search for locating "a thing with a podspec with the name foo". This is an uncommon command and when I use it I really want it to "just work". Given the weight of what its going to be doing afterwards, running a series of GETs to find a pod or rc or dc seems like it would be a nice feature.
