### ISSUE TITLE
Add "node" to Pods list in console

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7600]
It would be really cool to have "Node" column in the pods list:

<img width="1120" alt="screen shot 2016-02-24 at 21 19 33" src="https://cloud.githubusercontent.com/assets/44136/13299644/5560f384-db3c-11e5-9389-d82dd6042e36.png">

I have three nodes, might help understand where these pods run :-) (improves demos, etc. ;-)

**Comment by mfojtik** [comment]
@spadgett @jhadvig what do you think?

I'm happy with just IP or shortened node name (or the name of the node pops up in tooltip).

**Comment by deads2k** [comment]
Why should an average user care about which node his pod is on?  I could see checking pods backing a service to check if it is HA, but for general display I don't see it mattering.  Nodes are fungible.

**Comment by mfojtik** [comment]
@deads2k as a user of openshift with 3 nodes, I want to see how the pods are spread across my nodes and if the nodes are utilized.
As evangelist of openshift, I want to show that the app pods are distributed in multiple nodes. Right now, in the console, the only place where we show the node the Pod is placed is the Pod details :-)

Also for example, if one node has problem with scheduling pods, displaying the "node" column will help identify this without inspecting anything.... IOW. no pods running on node 3.

**Comment by mfojtik** [comment]
@deads2k and pod details sux, because I have to go pod by pod :-)

**Comment by deads2k** [comment]
As a user working in a managed system (online, dedicated, customer data center), I shouldn't care which nodes exist or which I'm scheduled to.

If you care about distribution, why not show an HA marker on a service?  That seems to fulfill the intent without exposing unnecessary detail.

**Comment by jhadvig** [comment]
We already discussed this with @jwforres and @spadgett and the conclusion was that we wont add the `Node` column there since regular user shouldn't care which kinda make sense. On the other hand would be handy if you are cluster-admin, I give you that.

**Comment by mfojtik** [comment]
@deads2k I think the online case make sense (I don't really care where the pod runs). If you have small deployment with 3-5 nodes and you're paying for them, it is nice to know where each pod run... But I guess this will be available once we add "admin" views to console.
