### ISSUE TITLE
When viewing Pod details in console show "next pod" link

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7601]
When you click on the circle with Pods in overview page, the list of Pods appears. You then pick one and get details. Then you realized this is not the pod you were looking for... Then you need to go back and remember which pod you selected...

It would be nice to show "Next Pod" or "Previous Pod" when displaying details of the Pod which belongs to a RC (or DC).

**Comment by mfojtik** [comment]
@spadgett does it make sense? ;-) I found myself going between pod details and pod list when searching for the pod with "logs" ;-) Or for the Pod placed in particular node...

**Comment by jwforres** [comment]
This is a significant enhancement request because of how things are structured, and needs to get UX input, moving this into trello https://trello.com/c/w8Y2ZmoA
