### ISSUE TITLE
[Question] how to expose a range of ports for the container in OpenShift

### ISSUE THREAD

**Issue by thincal** [openshift/origin#7609]
Docker command can do `docker run -it -p 5000-6000:5000-6000/tcp`, but how to do it in OpenShift ? thanks.

**Comment by bparees** [comment]
I don't think we offer a way to expose a range of ports in openshift.  @ncdc @smarterclayton ?

**Comment by smarterclayton** [comment]
Quick question - what do you need the range of ports *for*?  OpenShift gives each container an IP, you can listen on any port you want.  The load balancers deal with single or multiple ports (but not ranges) because they balance equally across pods.

**Comment by thincal** [comment]
If you want I can tee the story in details, that a Kurento Media Server (KMS) running as a container inside the OpenShift, but this KMS needs to open port for every single client communication, so that the KMS container should expose several ports.

**Comment by ncdc** [comment]
@thincal how do clients of KMS know what port to connect to if KMS has a range? Or do the clients simply all connect to a single port such as 8888?

**Comment by knobunc** [comment]
@thincal Do you need to expose them with a service?  The pods can open any ports... there's no filtering of the raw pod traffic.

**Comment by thincal** [comment]
@ncdc there is another signal server to get the connection info with the KMS.

@knobunc yes it is needed, but I will try to create the service and route on demand via. the open shift REST API only when client wants to setup the real connection with KMS. And do you mean that it is not needed to expose the KMS container ?

Thanks!

**Comment by knobunc** [comment]
@thincal  Will you please walk me through how the client determines what server and port to connect to (when OpenShift is not involved).

**Comment by thincal** [comment]
@knobunc there are three parts involved:
```
client <---(ws)---> signalling server <----(ws)----> KMS

Note: ws means websocket
```
basically the signalling server and KMS can be access with each other directly, but all (including client) parts might be behind the NAT or firewall, so that the ICE server will be used to let the client and KMS can be reached.

Firstly, the signalling server will open the port 8080 to provide the signalling server externally, then:
- KMS get its ICE candidate (ICE server IP + assigned port) from ICE server
- send this ICE candidate to signalling server
- signalling server send the ICE candidate of KMS to client through the websocket

so that this ICE candidate will be added into the peer connection, then this peer connection will be setup and be used to connect with KMS.

Here, the key part is the ICE candidate, it is a public IP and port mapped with the internal IP and port of KMS finally, and KMS will assign different port for different client. KMS requires that ALL range of UDP port should be opened.

So that if deploy the KMS with a docker, it needs to do like this in Dockerfile:
```
EXPOSE 0-65535/udp
```

But if let the KMS be deployed inside the OpenShift, what to do with this? Many thanks.

**Comment by knobunc** [comment]
Are the KMS clients inside the cluster, or outside?

There is no restriction on what ports the KMS can open.  If you do not list the ports, machines in the cluster can still connect to them (however they must be in the same project if you are using multi-tenant isolation).  It is obviously recommended to list the ports you expect to listen on, but today, that is just really descriptive.

HOWEVER, if you expect the client to be able to connect to the KMS from outside the cluster then you have a problem.  My best suggestion is to make a custom router that can coordinate with the signaling server to set up per-client paths in.

A quick search for kurento and firewall suggests that you set up a STUN server somewhere:
  https://groups.google.com/forum/#!topic/kurento/j4z0k1lfqPg

**Comment by thincal** [comment]
KMS client is possible coming from outside the cluster, for example an Android application client running in a device.

>  If you do not list the ports, machines in the cluster can still connect to them
could you help kindly detail why is it possible?

And, your suggestion about making a custom router, how to setup this router in OpenShift ? and how to work with the signaling server ?

About the STUN server yes one of the possible solution is setup own server in a public cloud such as AWS etc. but the public STUN server also can be used.

**Comment by knobunc** [comment]
It is possible by not listing the ports, but having the process inside listen on that port number and connecting to it from elsewhere in the cluster.

As to making a custom router... you would have to write one.  You could use the template router as a base, but it sounds like you would need to customize it heavily (in go).

The problem that I have is that by running something like this you are really allowing lots of external traffic into your cluster.  And how you determine what backing pod to route the traffic to when it hits the edge is a hairy question.

What scale are you looking at doing this at?

**Comment by thincal** [comment]
> What scale are you looking at doing this at?

Let us assuming the 10K viewer online at the same.

About how to determine the backing KMS pod to serve, I think there should be a LB to handle this.
From the official doc, will the [Routing from Edge Load Balancers](https://docs.openshift.org/latest/install_config/routing_from_edge_lb.html) help with it ?

**Comment by knobunc** [comment]
So, I read a bit about the KMS architecture and it looks like you have a few choices:
1) Run a TURN server with hostNetwork privileges on your publicly accessible nodes, then the connections will be proxied in through the TURN server
2) If you don't want to use a hostNetwork privilege, you could use a nodePort with a service to get traffic in to the TURN server pod.  BUT you could only have a single TURN server if you were using UDP... If you ran multiple, you could not predict what traffic will end up on which pod.  But if you used TCP for the TURN transport, then you could have multiple TURN pods.
3) Or, if you don't want to have the cost of the userspace proxy hop of the TURN server, you could give your KMS pods hostNetworking privilege and then they would bind directly to the node network and be visible externally (if you set your firewall up to allow it)

**Comment by thincal** [comment]
One question:
if running the TURN server in public network, and the KMS in a pod normally inside the OpenShift.

so after KMS gets its public IP/port in TURN server, is that possible to reach this KMS outside by using this public IP/port ? since that this KMS container is using the cluster IP, is that possible to be reached without the router ?

**Comment by knobunc** [comment]
In this setup you would be running the TURN server in the place of the router.  So it needs to sit on an externally reachable IP address but have access to the cluster networking.

So, you can either give the TURN pods hostNetworking privilege and then they will have access to the network interface on the host node; or if you can set it up to use TCP from outside the cluster (if the clients support that) then you can use a nodePort with a service to get traffic to the TURN pods.

**Comment by thincal** [comment]
> running the TURN server in the place of the router.

do you mean that this TURN server should be deployed inside the OpenShift ? so that it can access the KMS pod in the OpenShift cluster networking ?

> you can either give the TURN pods hostNetworking privilege and then they will have access to the network interface on the host node

1. how to give the hostNetworking privilege for TURN pods ?
2. just double check that, without any port exposing from PODs/Container to host, for an allocated ICE candidate (TURN server host IP:port) it can be reachable from the place where inside the LAN but outside the cluster ? right ?
3. if the TURN server should be deployed inside the OpenShift, then this TURN server should be provided as a service/route for public accessing, but how to construct the related route ? and since the port is allocated randomly by TURN, how to route the request not with the 80/443 port by OpenShift router?

Or it could be another specific question:
**How to deploy a HA TURN server inside the OpenShift ?**

**Comment by knobunc** [comment]
@thincal Sorry, is this still a concern?

**Comment by alexgalkin** [comment]
The issue was closed without confirming any solution. Was anyone able to properly configure Kurento on openshift?

**Comment by nkt** [comment]
any updates?
