### ISSUE TITLE
router is not use in Multiple Masters

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#7611]
hi
    i deploy the Multiple Masters with openshift-ansible[1],and it look good for build.
    when i login,i find the router is error which haven't error-log in /var/log/messages,and describe dc/rc have nothing mesages,also it can't delete rc use oc delete rc router-1.
     who can i do for it?
     Please forgive my poor English.
     thanks.
   
![error-1](https://cloud.githubusercontent.com/assets/12937669/13315654/0115f620-dbe7-11e5-965f-0d1045f01df2.jpg)
![error-2](https://cloud.githubusercontent.com/assets/12937669/13315662/0ec697a2-dbe7-11e5-83fd-86579d928145.jpg)
![error-3](https://cloud.githubusercontent.com/assets/12937669/13315664/132599ce-dbe7-11e5-851c-82b1cb41e5bd.jpg)
![error-4](https://cloud.githubusercontent.com/assets/12937669/13315675/2a1b5268-dbe7-11e5-8b93-72329933d7cd.jpg)

[1]https://docs.openshift.org/latest/install_config/install/advanced_install.html#multiple-masters

**Comment by wenskys** [comment]
Who can help us deal with this problem? 
thanks

**Comment by ramr** [comment]
@wenskys  what does running `oc describe pod <router-pod-name>` (you can get the router pod name from `oc get pods`) say? That might provide more clues.

**Comment by wenskys** [comment]
@ramr nothing,the pod can't be up,and the rc is always 0 when i use "oc scale --replicas=1 replicationcontrollers router-1"
may be i can try again for the new release.

**Comment by wenskys** [comment]
@ramr The new version was successful,and the route is runing.may have been repaired in new. 
At the new test ,i find a bug for "ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml" when install origin*,i will try again.
if it is a bug,i will report for you.
thanks.
