### ISSUE TITLE
MethodNotAllowed with Generic web hook

### ISSUE THREAD

**Issue by theone4ever** [openshift/origin#7614]
Hi all,

I am testing generic web hook to trigger a build in openshift, the HTTP response i got is like below. I guess this is some permission or role authorization issue. Any idea how to relax the security policy to enable any web client can trigger a build by call this web hook url? Thank you in advance

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server does not allow this method on the requested resource",
  "reason": "MethodNotAllowed",
  "details": {},
  "code": 405
}

**Comment by liggitt** [comment]
That is not a security issue, you are not using the correct HTTP verb. Double check that you are using the POST verb.

**Comment by theone4ever** [comment]
Yep, just realized that HTTP post is required. Thx for quick response. Close the issue now!

**Comment by shopatlemo** [comment]
you have to put a "/" at the end.  If you don't do that, this error will cause.  here is the example the last slash after github-webhook
http://2bea0e50.ngrok.io/github-webhook/
