### ISSUE TITLE
ImagestreamTag creation fails in OpenShift Enterprise cluster behind HTTP/HTTPS proxy

### ISSUE THREAD

**Issue by Tebro** [openshift/origin#7615]
Tag: @soltysh 

So I installed OpenShift Enterprise 3.1 on RHEL Atomic hosts in AWS. 

All of the etcd, master, and node hosts have no public IP address, and they access the internet via a squid proxy. The install completes, I setup the basic router and internal registry and all seems fine.

However, when uploading [this template](https://github.com/Tebro/FileStore/blob/master/openshift/template.json), and trying to start it fails to build. With the following error being given: `An error occurred while starting the build.imageStreamTag "java-gradle-sti:latest" not found`

The logs for openshift-master-controllers get filled with these entries:

```
config_controller.go:55] error instantiating Build from BuildConfig test/filestore: imageStreamTag "java-gradle-sti:latest" not found
iowatcher.go:102] Unexpected EOF during watch stream event decoding: unexpected EOF
```

And the logs for openshift-master-api has these:

```
config_controller.go:55] error instantiating Build from BuildConfig test/filestore: imageStreamTag "java-gradle-sti:latest" not found
iowatcher.go:102] Unexpected EOF during watch stream event decoding: unexpected EOF
reflector.go:224] pkg/project/cache/cache.go:102: watch of *api.Namespace ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2354/2280]) [3353]
```

**Comment by soltysh** [comment]
From my quick testing I can confirm having problems accessing docker registry behind proxy. Working on it...

**Comment by soltysh** [comment]
Just checked this with latest master works perfectly ok. My problem was that when running openshift with sudo my env got lost. I had to update my sudoers file so that `http_proxy`, `https_proxy` and `no_proxy` settings are passed when doing sudo (there are other options as well), just fyi.

**Comment by Tebro** [comment]
This is the result of `openshift version` on a master:

```
openshift v3.1.1.6-21-gcd70c35
kubernetes v1.1.0-origin-1107-g4c8e6f4
etcd 2.1.2
```

**Comment by soltysh** [comment]
@Tebro that's confirmed, you're using a version of openshift which uses the old import mechanism, which unfortunately didn't work well with proxies. Is there a change you update to something newer?

**Comment by Tebro** [comment]
@soltysh Umh, this is the latest version of OpenShift Enterprise as far as I know, or is there a way to get something newer, that is supported?

**Comment by soltysh** [comment]
@tdawson what is the latest official version of ose?

**Comment by tdawson** [comment]
Sorry for the delay.  As of right now this is the latest

Image: openshift3/ose:v3.1.1.6-14
rpm: atomic-openshift-3.1.1.6-4.git.21.cd70c35.el7aos.x86_64
version:
openshift v3.1.1.6-21-gcd70c35
kubernetes v1.1.0-origin-1107-g4c8e6f4
etcd 2.1.2

**Comment by soltysh** [comment]
@Tebro I guess in that case you'll have to wait for the 3.2 release we're currently working on getting finished. Sorry for that.

**Comment by soltysh** [comment]
@Tebro can we close this issue with this information?

**Comment by Tebro** [comment]
@soltysh yes, go ahead. We have to go back to the drawing table.
