### ISSUE TITLE
Extended jenkins job test failing

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7619]
Extended Core.[jenkins] schedule jobs on pod slaves use of jenkins with kubernetes plugin by creating slave from existing builder and adding it to Jenkins master 

https://ci.openshift.redhat.com/jenkins/job/origin_extended/678/testReport/junit/(root)/Extended%20Core/_jenkins__schedule_jobs_on_pod_slaves_use_of_jenkins_with_kubernetes_plugin_by_creating_slave_from_existing_builder_and_adding_it_to_Jenkins_master/

**Comment by soltysh** [comment]
Seen in: https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/83/consoleFull

**Comment by soltysh** [comment]
I haven't seen this happening for quite a while. And my PR simplifying tests got merged already. If seen, please re-open.
