### ISSUE TITLE
Flake in integration tests: etcd member has no leader

### ISSUE THREAD

**Issue by miminar** [openshift/origin#7624]
failed  TestTemplateTransformationFromConfig
    ...
    I0225 08:52:21.032446   15650 object.go:59] Unknown field type 'int64': <int64 Value>
    I0225 08:52:21.032608   15650 object.go:59] Unknown field type 'int64': <int64 Value>
    I0225 08:52:21.032620   15650 object.go:59] Unknown field type 'int64': <int64 Value>
    I0225 08:52:21.032635   15650 object.go:59] Unknown field type 'bool': <bool Value>
    I0225 08:52:21.032648   15650 object.go:59] Unknown field type 'int64': <int64 Value>
    I0225 08:52:21.032659   15650 object.go:59] Unknown field type 'int64': <int64 Value>
    E0225 08:52:21.041606   15650 errors.go:63] apiserver received an error that is not an unversioned.Status: error #0: client: etcd member http://127.0.0.1:38705 has no leader
    F0225 08:52:21.041893   15650 run_components.go:422] Unable to initialize namespaces: unable to persist the updated namespace UID allocations: error #0: client: etcd member http://127.0.0.1:38705 has no leader
    E0225 08:52:21.047374   15650 errors.go:63] apiserver received an error that is not an unversioned.Status: error #0: client: etcd member http://127.0.0.1:38705 has no leader
    E0225 08:52:21.047660   15650 tokens_controller.go:162] error #0: client: etcd member http://127.0.0.1:38705 has no leader

Happend in #7128 ([job 11819](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/11819/console)).

May be related to #7243 (extended tests).

**Comment by smarterclayton** [comment]
This is the same as the linked.
