### ISSUE TITLE
Http PATCH with '/' in key

### ISSUE THREAD

**Issue by Meems33** [openshift/origin#7629]
The REST json patch method(s) do not allow ~0 and ~1 escape characters for '~' and '/' respectively. (http://jsonpatch.com/)

Example (/oapi/v1/namespaces/project/imagestreams/image):

```
// json
{ 
  "metadata": {
    "annotations": {
      "openshift.io/image.dockerRepositoryCheck": "2016-02-25T16:38:43Z"
    }
  }
}

// patch operation
[ { "op": "add", "path": "/metadata/annotations/foo~1bar", "value": "val" } ]"
```

results in a validation error:

>       {
>        "reason": "FieldValueInvalid",
>        "message": "invalid value 'foo~1bar', Details: must be a qualified name (at most 63 characters, matching regex ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]), with an optional DNS subdomain prefix (at most 253 characters, matching regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*) and slash (/): e.g. \"MyName\" or \"example.com/MyName\"",
>        "field": "metadata.annotations"
>      }

The expected result would be to add a key of "foo/bar" to "/metadata/annotations":
```
{ 
  "metadata": {
    "annotations": {
      "foo/bar": "val",
      "openshift.io/image.dockerRepositoryCheck": "2016-02-25T16:38:43Z"
    }
  }
}
```

Deletes seem to fail silently. Example:
`[ { "op": "remove", "path": "/metadata/annotations/openshift.io~1image.dockerRepositoryCheck" } ]`
(See https://github.com/openshift/origin/issues/7226)

I suspect other operations have the same problem.

**Comment by alexcern** [comment]
Hello

We are also affected by this problem. It is not possible to use PATCH with key names containing '/'

**Comment by AlbertoPeon** [comment]
Hi,

Is there any progress with this? I'm also affected.

**Comment by alexcern** [comment]
BTW we can also reproduce the problem with the CLI:

`oc patch dc/ruby-hello-world -p '[{"op": "add", "path": "/metadata/annotations/foo~1bar", "value": "val"}]' --type=json`

This results in error:
```
* metadata.annotations: Invalid value: "foo~1bar": must be a qualified name (at most 63 characters, matching regex ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]), with an optional DNS subdomain prefix (at most 253 characters, matching regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*) and slash (/): e.g. "MyName" or "example.com/MyName"
* metadata.annotations: Invalid value: "foo~1bar": must be a qualified name (at most 63 characters, matching regex ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]), with an optional DNS subdomain prefix (at most 253 characters, matching regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*) and slash (/): e.g. "MyName" or "example.com/MyName"
* metadata.annotations: Invalid value: "foo~1bar": must be a qualified name (at most 63 characters, matching regex ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]), with an optional DNS subdomain prefix (at most 253 characters, matching regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*) and slash (/): e.g. "MyName" or "example.com/MyName"
```
Expected result is that an annotation `foo/bar` gets added to the object

**Comment by liggitt** [comment]
Upstream issue at evanphx/json-patch#23, potential fix at https://github.com/evanphx/json-patch/pull/27/

**Comment by jimmidyson** [comment]
This also needs to be upstreamed into Kubernetes - raised https://github.com/kubernetes/kubernetes/issues/26890

**Comment by jimmidyson** [comment]
I've raised a PR to bump relevant godep in kubernetes - I guess I should also submit a PR to Origin to do the same bump so we can pick this up before the next rebase?

**Comment by liggitt** [comment]
a matching PR in origin would be good, shouldn't conflict with the rebase in progress (other than godeps.json, which wouldn't be a big deal to resolve either way)

**Comment by jimmidyson** [comment]
Sorry - do you mean PR to openshift/origin or openshift/kubernetes or both? Not sure of the vendoring process I'm afraid.

**Comment by liggitt** [comment]
transitive godeps like this that can be bumped cleanly (no API changes) can be brought in with an openshift/origin PR, as long as there's a matching PR to bump kubernetes/kubernetes to the same level

**Comment by jimmidyson** [comment]
OK thanks.
