### ISSUE TITLE
Annotate Origin on origin tests

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#7631]
Running the latest e2es from source, it appears : 

- `KUBECONFIG=/etc/origin/master/admin.kubeconfig ./extended.test --ginkgo.skip="[Kubernetes]"` 
- `KUBECONFIG=/etc/origin/master/admin.kubeconfig ./extended.test --ginkgo.skip="[Origin]"` 

...have identical complete skip profiles, somehow.

I could be missing something but maybe we should just **directly annotate the 100 or so OpenShift tests** with `[OpenshiftE2E]` so that skip/focus/dryRun work naturally ?

@smarterclayton @liggitt @timothysc

**Comment by smarterclayton** [comment]
Do we need to?  Not sure what the benefit is, unless upstream also does
that.

**Comment by jayunit100** [comment]
Well, the concrete "bug" here is that "Kubernetes" or "Origin" ginkgo skip tags result in the exact same thing: 0 tests being run.   The fix I'm suggesting would fix that I believe while also making it so that we didn't need to scan the file name for filtering

**Comment by smarterclayton** [comment]
Running --ginkgo.skip='\[Origin\]' works for me - can you describe what
you're seeing?

**Comment by jayunit100** [comment]
I could be missing something or maybe something is wonky with my build, I can retest.... But the requirement in suggesting is that "--ginkgo.skip=[Origin] " should "just work" for users trying to test kubernetes functionality ?

**Comment by smarterclayton** [comment]
You have to escape any square brackets you pass to ginkgo, because ginkgo
treats them as regexes.

**Comment by jayunit100** [comment]
Ack re escape chars, 
Hmm ok I wonder if Origin without brackets should work ...

**Comment by jayunit100** [comment]
Ok, tried with the escaped filters, the dryRun and focus and skip all seem to still be kludgey...

- i think its because the real filtering is happening inside of `BeforeEach`....

```
[root@ip-172-18-9-65 kubernetes]#  KUBECONFIG=/etc/origin/master/admin.kubeconfig ./extended.test --ginkgo.focus='\[Origin\]' --ginkgo.dryRun=true 2>&1 | grep run
Will run 0 of 326 specs
[root@ip-172-18-9-65 kubernetes]#   KUBECONFIG=/etc/origin/master/admin.kubeconfig ./extended.test --ginkgo.skip='\[Origin\]' --ginkgo.dryRun=true 2>&1 | grep run
Will run 326 of 326 specs
[root@ip-172-18-9-65 kubernetes]#  KUBECONFIG=/etc/origin/master/admin.kubeconfig ./extended.test --ginkgo.skip='\[Kubernetes\]' --ginkgo.dryRun=true 2>&1 | grep run
Will run 326 of 326 specs
[root@ip-172-18-9-65 kubernetes]#  KUBECONFIG=/etc/origin/master/admin.kubeconfig ./extended.test --ginkgo.focus='\[Kubernetes\]' --ginkgo.dryRun=true 2>&1 | grep run
Will run 0 of 326 specs
```

**Comment by smarterclayton** [comment]
You can't focus on those, you can only skip.  You'd have to create a
separate flag and then check in beforeeach.

**Comment by jayunit100** [comment]
Skip seems funny to... 

```
 --ginkgo.skip='\[Origin\]' --ginkgo.dryRun=true 2>&1 | grep run
Will run 326 of 326 specs
 --ginkgo.skip='\[Kubernetes\]' --ginkgo.dryRun=true 2>&1 | grep run
Will run 326 of 326 specs
```

**Comment by smarterclayton** [comment]
It doesn't report them up front as skips.  It skips them during
execution like AWS or GCE tests.

**Comment by jayunit100** [comment]
yup, because of the BeforeEach.
And my point is that I think it would be more "correct" if it *did*, even though this is a good workaround.

**Comment by jayunit100** [comment]
i.e. the original point is that skip/focus/dryRun should work intuitively, i kinda think.

**Comment by smarterclayton** [comment]
We should fix this in ginkgo - allow tests to be skipped by package
path (they only allow it when you give them a list of paths to
compile, vs the binary we compile up front).

**Comment by smarterclayton** [comment]
I'm not very interested in just running Kube tests in this suite, so
I'm not really interested in labeling all of the Kube tests Kube or
origin tests origin and then having to maintain that.  The conformance
test for origin is Kube tests + origin tests, not a subset based on a
label.  If the use case of "just running upstream tests" is only for
internal use manual labeling isn't really worth it.

**Comment by jayunit100** [comment]
hmmm, ok.  so i think we may need to revisit the conclusion for #7049 , then...

- If upstream supports focus, skip, dryRun for all of its tests, and we don't, then we are by definition not a superset of the upstream testing suite.

- however, we decided in #7049 that we wanted to package `extended.test` as a superset of upstream functionality.

**Comment by timothysc** [comment]
> The conformance test for origin is Kube tests + origin tests, not a subset based on a label

Upstream has been explicitly labeling [Conformance], and it seems logical to extend that convention.  As this is what they will publish to users (ginkgo.focus="Conformance").  Outside of that scope, I don't think labeling every test is very fruitful either.

**Comment by smarterclayton** [comment]
We will have origin conformance tests.  I don't think we would pick
another label.  We would run conformance by default for customers, and
not distinguish between Kube and origin.  Maybe I don't understand
what specifically you guys need.

**Comment by jayunit100** [comment]
- maybe a breif discussion offline tomorrow will help us converge;  goal= fulfill the stated requirement " upstream tests being packaged with each build. " 
- and i guess defining that unambiguously is proving to be a little tricky :)

**Comment by timothysc** [comment]
So I chatted with Jay about this earlier today, and I tend to agree there needs to be some level of separation.  Running even a subset of the tests on a cluster of several hundred nodes takes literally 1/2 a day.  

It seems pretty trivial to add a prefix either on upstream,downstream, or both, such that we can use ```skip``` or ```focus``` properly for any combination of tests.

**Comment by smarterclayton** [comment]
Yeah, that's what the synthetic skips do today.  Unless there's a
really good reason, I'd prefer to use the existing mechanism for
enabling skip.  If you have a long skip list, adding either group
isn't hard.  If you want to focus and skip, it'll do the right thing
today.

**Comment by jayunit100** [comment]
x-ref: am hacking around on the ginkgo code base to see how this works ; https://github.com/onsi/ginkgo/issues/226, something might pan out we will see.

**Comment by jayunit100** [comment]
Created alternative here  #7683 , just a  one liner that enables all the pretest treewalking filters on test name.
