### ISSUE TITLE
diagnostics should attempt exec, proxy, and logs

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#7637]
Proxy configuration problem from masters to services or pods seem to be common.  We can detect common failures by creating a "test" pod that we attempt to exec, proxy, and get logs from.  If those things fail, they deserve a warning or maybe an error.

If we see those failure in combination with proxy settings in a unit file that should be called out separately.

@sosiouxme @brenton

**Comment by sosiouxme** [comment]
On Thu, Feb 25, 2016 at 2:56 PM, David Eads <notifications@github.com>
wrote:

> We can detect common failures by creating a "test" pod that we attempt to
> exec, proxy, and get logs from. If those things fail, they deserve a
> warning or maybe an error.
>

Sounds like a variation on the current DiagnosticPod, which is a little
naive at this point about reasons why logs might not be available.

BTW by "proxy" did you mean "port-forward"?

**Comment by deads2k** [comment]
> BTW by "proxy" did you mean "port-forward"?

No, but checking that would be good too.  `proxy` is a subresource on a pod that allows the master to proxy a connection to a particular pod on your behalf.

Keep in mind that these tests must be run from a client, to a master, to a pod.  I guess you could go pod to master to pod, but that adds needless complication.

**Comment by sosiouxme** [comment]
/remove-lifecycle stale
this remains relevant. probably can add into AppCreate or NetworkCheck.
