### ISSUE TITLE
s3_registry storage (how to)

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin#7642]
I am trying to use s3 as my registry storage.  It looks like there is an ansible playbook to set things up.  What do I use as my clusterid?  How do I find that?  Is there a tutorial how to get the s3_registry ansible playbook working?  @dak1n1

**Comment by deanpeterson** [comment]
Do I need to add something to my /etc/ansible/hosts file under [ tag_clusterid_{{ clusterid }}:&tag_host-type_openshift-master]?  I am trying a number of things but it is not clear given my knowledge of Ansible how to get the s3 registry playbook to work.

**Comment by brenton** [comment]
If you are simply trying out this feature I wouldn't necessarily use ansible for this if you aren't familiar with it.  See these docs on how to override the registry configuration:

https://docs.openshift.com/enterprise/3.1/install_config/install/docker_registry.html#advanced-overriding-the-registry-configuration

From there it's just a standard registry configuration file.  You can see https://docs.docker.com/registry/configuration/ for all the possible values you can pass in.  This appears to be the configuration we use in openshift-ansible: https://github.com/openshift/openshift-ansible/blob/master/playbooks/adhoc/s3_registry/s3_registry.j2

**Comment by deanpeterson** [comment]
Ok, thanks.  I appreciate the info.  I will mention; I did use ansible to install openshift and that was relatively easy.  I was hoping it would be that easy to use this playbook as well.  For now, I will take the approach you suggest until I can figure out how to automate the process with ansible.

**Comment by brenton** [comment]
@deanpeterson, Today there are parts of openshift-ansible that make it in to the OpenShift Enterprise.  Those parts get a lot more testing and documentation.  There are other parts that are largely R&D efforts or community contributed.  The s3_registry playbook is an example of an R&D effort unfortunately which is one reason we don't have official documentation for it yet. :/
