### ISSUE TITLE
oc rsync fails when use with tar strategy to pod running as root

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#7650]
If try and use ``oc rsync`` to pod running as root due to allowing image to run as any user, then get errors like:

```
$ oc rsync . nginx-12-6lfbo:/usr/share/nginx/html/ --strategy tar
Nginx.HTTP.Server.pdf
tar: Nginx.HTTP.Server.pdf: Cannot change ownership to uid 501, gid 0: Operation not permitted
tar: Exiting with failure status due to previous errors
error: error extracting tar at destination directory: error executing remote command: Error executing command in container: Error executing in Docker Container: 2
```

The problem is that when tar is run as root in the container to unpack the archive, it is trying to restore users based on symbolic names. The users in the archive sent across don't exist in the target.

What it should do is use the ``-o`` option to tar to say to use the user that tar runs as in the container for file ownership when unpacking. Thus something equivalent to:

```
$ tar cvf - . | oc rsh nginx-12-6lfbo tar xovfC - /usr/share/nginx/html
a .
a ./Nginx.HTTP.Server.pdf./
./._Nginx.HTTP.Server.pdf
./Nginx.HTTP.Server.pdf
```

**Comment by bparees** [comment]
@GrahamDumpleton did you try the --no-perms flag on oc rsync?

**Comment by GrahamDumpleton** [comment]
I did, but from memory it complained that only applies when using rsync strategy and not tar strategy. It also isn't permissions which is the issue but file ownership.

**Comment by csrwng** [comment]
Yup, we need to fix this in the tar invocation on the container side.

**Comment by csrwng** [comment]
@GrahamDumpleton @bparees I am not able to reproduce this locally. However, I do see from online posts [1], [2] that it does happen. I'm wondering whether it's only file of a certain size or a particular version of tar that cause it.

[1] - https://www.krenger.ch/blog/linux-tar-cannot-change-ownership-to-permission-denied/
[2] - http://www.zyxware.com/articles/2713/untar-without-running-into-cannot-change-ownership-to-uid-nnn-gid-nnn-disk-quota-exceeded-on-whmcpanel-vps-account

**Comment by GrahamDumpleton** [comment]
I am using Debian base image, not CentOS. Maybe that has something to do with it.

**Comment by csrwng** [comment]
I tried with the nginx that's on Dockerhub which I guess is debian based. I was able to rsync files owned by the local user with no problem.

**Comment by GrahamDumpleton** [comment]
And definitely running the container as root? Normally OpenShift would run it as arbitrary user. I am using all-in-one VM which allows it to run as any user, so would be running as root. But then if wasn't running as root you likely wouldn't even have been able to write files.

I will check again later if have time and see if can see anything else that helps.

**Comment by csrwng** [comment]
yup, the nginx image from dockerhub won't start up if not running as root. I'll keep looking to see if there's something I'm doing differently.
