### ISSUE TITLE
[Question] About how to include an external load balancer  in OpenShift

### ISSUE THREAD

**Issue by thincal** [openshift/origin#7651]
[Official OpenShift doc](https://docs.openshift.org/latest/install_config/routing_from_edge_lb.html#including-lb-in-sdn) said that it can include a LB in OpenShift SDN, but doesn't tell the steps.
Is there any more info could be detailed ? many thanks.

**Comment by thincal** [comment]
@eparis thanks for your attention with this question, could you give some help if possible? Thanks!

**Comment by rajatchopra** [comment]
Is this what you are looking for? 
https://docs.openshift.org/latest/install_config/routing_from_edge_lb.html

**Comment by rajatchopra** [comment]
Are you looking for this?
https://docs.openshift.org/latest/install_config/install/deploy_router.html
The term router and load balancer are used interchangeably in the docs (needs correction possibly).

**Comment by thincal** [comment]
yes this is deploying the integrated router, but what is the way to setup another LB in openshift?

**Comment by rajatchopra** [comment]
We have integrations with F5 and haproxy like you have found,  which other do you want to run? 

The integration with SDN will have to be done specifically for that load balancer. We do not have any documentation for a generic load balancer other than the suggestion that it should preferably run as a pod within the cluster.

Importantly, each load balancer will have to write its own logic to update itself with newer routes/endpoints. The API to watch routes/services/endpoints is common and can be found here:
https://docs.openshift.org/latest/rest_api/openshift_v1.html#list-or-watch-objects-of-kind-route

**Comment by thincal** [comment]
@rajatchopra my real requirement might help tell the question more precisely. Since now the origin can only accept the 80/443 traffic from external, but actually there are some other ports needs to be accepted in some cases, it seems that it could deploy another LB which accept traffic outside from OpenShift then route to pods inside the OpenShift.

The [doc](https://docs.openshift.org/latest/install_config/routing_from_edge_lb.html) said that the HAProxy router could be used, but which is configured to use by OpenShift platform, is it feasible to be used by above case? are there any additional steps?

Also if I want to use the ngix docker as the LB, what to do with OpenShift ?

Many thanks for your help.

**Comment by thincal** [comment]
@rajatchopra @eparis could you help with the detailed steps? since that is not told clearly in the official doc, thanks again.

**Comment by rajatchopra** [comment]
We probably need a good document on this. But broadly the steps will be on these lines:

1. Select a node to run the lb, and label the node
2. Launch your lb as a pod (using the label) with host network or run it as a process
3. Run a lb-config pod which has credentials to access apiserver/master. This config pod should have custom code that can read routes/services/endpoints and can configure/reload the lb process/pod
4. Finally mark the node unschedulable so that other pods do not land up on this 'infra' node
