### ISSUE TITLE
Web console: pull status (phase) out of under tabs & put it above

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#7652]
This will touch a number of page templates, so breaking it out as a separate issue per [a comment on this PR](https://github.com/openshift/origin/pull/7640).

@spadgett @jwforres @sg00dwin @rhamilto @ajacobs21e 
tagging everyone who may be interested

**Comment by spadgett** [comment]
@sspeiche

**Comment by sspeiche** [comment]
+1 for doing this. I often am looking for status or which sub-panel it is on.

**Comment by smarterclayton** [comment]
Closing due to age.
