### ISSUE TITLE
Initial deployment never occurs with both configChange and imageChange(auto=false) triggers

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#7663]
I believe @bparees and @pmorie have uncovered a flaw in https://github.com/openshift/origin/pull/7529. Given a deploymentConfig with both a configChange trigger and an imageChange(automatic=false) trigger, initial deployment will never occur, because:

1. The imageChange trigger ignores due to automatic=false
2. The configChange trigger ignores because it wants to defer to the imageChange trigger (based on the generator saying "there's an image change" due to the initial deploymentConfig.spec.template.spec.container[].image value differing from the latest referenced imageStreamTag value)

This is a regression from previous behavior where there would normally be an initial deployment. Perhaps the configChange trigger race check should only apply for versions >0.

**Comment by ironcladlou** [comment]
cc @kargakis @smarterclayton

**Comment by bparees** [comment]
to give full credit, @gabemontero actually hit it first :)

**Comment by bparees** [comment]
i'm marking p1 for now because this breaks a number of our example templates, but if we need a workaround we can change the templates instead of fixing this.

**Comment by smarterclayton** [comment]
We have to fix this, workaround in templates is just a bad idea.

**Comment by pmorie** [comment]
I think there is at least one other bug that I hit, will open issue

**Comment by kargakis** [comment]
> Perhaps the configChange trigger race check should only apply for versions >0.

How about checking ICT.automatic for the DC? If true, ignore since it's racing the IC controller, if false, continue processing?

**Comment by mfojtik** [comment]
@smarterclayton @bparees maybe we should bump the prio of this to P0 as our templates are currently broken with this (I guess).

**Comment by smarterclayton** [comment]
Not fixed for DCs with multiple image change triggers
