### ISSUE TITLE
Web Console - deleting PVCs does not remove them from DCs

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#7666]
I can delete PVCs from the Storage screen but they still show up as PVCs on the Deployment config. If I click on it in the DC it goes to a page which says it can't find the resource (which is true). Not sure if this is actually a problem with cascading the deletes OR if this is something for the web ui to handle more gracefully

**Comment by liggitt** [comment]
pretty sure that page is showing you pvc references in the dc pod template (which still exist).

**Comment by thesteve0** [comment]
Yeah but that is very confusing to me as a developer. I agree it may not be the Web consoles "fault" please feel free to reassign or retitle as needed. I just wanted to capture this somewhere

**Comment by thesteve0** [comment]
@jwforres I am pretty sure this should be "reassigned" lower in the stack

**Comment by thesteve0** [comment]
What is happening with this
