### ISSUE TITLE
List deployments pods

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#7685]
Would be handy to have a  "Pods" tab at specific Deployment that would list all the pods that belong to  that deployment.
@spadgett @jwforres thoughts ?

**Comment by mfojtik** [comment]
+1

**Comment by spadgett** [comment]
Related to #7426.

I have an open PR (#7134) that adds the pods donut to the deployment page, which links to a filtered pod list. It might make sense to just have a table of pods, though. It would be consistent with build config and deployment config pages that have tables of builds and deployments.

**Comment by jhadvig** [comment]
@spadgett the pods donut looks great. Yeah wasnt sure

**Comment by jhadvig** [comment]
@spadgett the pods donut looks great. Wasnt sure if we wanna have a tab for the pod list with a watcher that will watch only if user goes to that tab, or we wanna have similar pattern to dc and bc pages.

**Comment by spadgett** [comment]
Yeah, to add the donut, I needed a pod watch. So it's no more work to use a table instead or have both.

In the DC and BC pages, we have the table on the first tab. I can't decide if we'd want that here or a separate tab.

**Comment by jhadvig** [comment]
well if we have the list in a separate tab, then we wont be consistent with the pages like DC/BC. On the other hand I like the idea of having it in a separate tab since the pods donut is in the "Details" tab and would be purely informational. Also on mobile you would have to scroll to the bottom just to see the pods, which would be solved by the tab. Maybe (and just maybe) we could do the same for the DC/BC views, I mean to put their instances to a tabs. On the other hand I guess we dont wanna end up with a endless tab field  :interrobang:

**Comment by spadgett** [comment]
We're getting a little tab happy in places :)

We have an issue to look at tabs across resources including those tables (#7440).

**Comment by spadgett** [comment]
Fixed by https://github.com/openshift/origin-web-console/pull/183
