### ISSUE TITLE
Kubernetes leave a lot of /pause containers running

### ISSUE THREAD

**Issue by TomasTomecek** [openshift/origin#769]
After firing ~20 builds, there is same amount of running containers with '/pause' command:
```
32c3b5ef1f00        kubernetes/pause:go   "/pause"               25 seconds ago      Up 21 seconds                               k8s_net.dbcb7509_build-httpd-20150128-144611961228.default.etcd_01170c55-a6f4-11e4-9ebc-fa163ed7ae77_d390d752
```
I'm not sure what's the purpose of this container but I feel like they are slowing my system. (e.g. I did `docker ps -a` and that command got stuck, I had to restart docker daemon)

EDIT: important point may be, that my builds finished while those /pause containers were still running

**Comment by TomasTomecek** [comment]
@smarterclayton 
Any idea?

**Comment by csrwng** [comment]
@TomasTomecek The pause containers are started by Kubernetes to handle networking for a pod (in this case it's the build pod). We are currently not cleaning these up, but they should be cleaned up by a controller in the OpenShift master eventually.

**Comment by smarterclayton** [comment]
We're currently not cleaning up build pods?  I thought we were.

----- Original Message -----

**Comment by TomasTomecek** [comment]
@csrwng any idea then why k8s don't purge those pause containers even though the build has finished. Will retry on Monday with master (this issue is somewhere around latest beta release)

**Comment by csrwng** [comment]
@TomasTomecek because the pod for the build still exists. Kubernetes doesn't know about builds, just pods. Even though the pod completed, if it still exists as a resource in etcd, Kubernetes won't delete the associated containers for it.

**Comment by smarterclayton** [comment]
We should get something upstream to garbage collect pods that are in complete status after a minimum interval has passed.

**Comment by TomasTomecek** [comment]
Thanks guys! Will test as soon as something lands to git.

**Comment by TomasTomecek** [comment]
Just created a simple python script for removing old pods, because this is starting to be a real issue for me (my VM chokes after having ~30 active pods -- networking collapses after having so many network interfaces).

Could you please give me a simple howto regarding go code organization (e.g. "create a clean function for this struct and put it to module X and call it from module Y") so I can send a PR?

**Comment by smarterclayton** [comment]
Succeeded pods should be stopped.  That's probably just a generic bug.  Can you describe the scenario here and I'll create an upstream issue to track it?

----- Original Message -----

**Comment by brenton** [comment]
I just want to mention that I've seen this quite a bit too with the infrastructure pods.  I run lots of builds and when I'm down there are dozens of them still running, leftover from previous builds.

**Comment by TomasTomecek** [comment]
1. create build via API
2. build starts
3. build succeeds
4. container `/pod` is still running

openshift v0.3

**Comment by smarterclayton** [comment]
Opened this as https://github.com/GoogleCloudPlatform/kubernetes/issues/4731

**Comment by smarterclayton** [comment]
Fixed upstream and now in our codebase
