### ISSUE TITLE
Web console: bump lodash to v4.x.x

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#7692]
Current lodash is `4.5.1`, we are running `3.2.0`.  I bumped us to the latest `3.x.x` recently but a jump to `4.x.x` will require some updates as there are breaking changes.  I've run into a couple situations where it would be nice to be current, but nothing too pressing yet.

@jwforres @spadgett

**Comment by spadgett** [comment]
@jwforres Should we think about bumping any other dependencies post 1.2 like Angular? At least to the latest 1.3.x? We're on 1.3.8. They're up to 1.5.0, but there's also 1.3.20

**Comment by spadgett** [comment]
Need to check what dependency is bringing in lodash and what version it requires.

**Comment by jwforres** [comment]
Yeah I agree @spadgett we should probably look into bumping our deps in general.  We need to bump patternfly first, and then look at bumping hawtio ( @gashcrumb ).  Those two will probably limit what we can / can't update.

**Comment by gashcrumb** [comment]
@jwforres yep, going to lodash 4.x will definitely take some migration on the hawtio side, but doable.

**Comment by jwforres** [comment]
@gashcrumb do you know if there are any plans to do update lodash in hawtio in the next 6 months?

**Comment by gashcrumb** [comment]
@jwforres I wonder if maybe it'd be better to just pull the lodash dep out of hawtio-core-navigation instead, which I think would allow you to use a newer version easily enough.

**Comment by spadgett** [comment]
angular-patternfly depends on lodash 3.x

**Comment by jwforres** [comment]
@gashcrumb ah we are just depending on hawtio-core now, so if nav was pulling it in then i think the issue at this point would be angular-patternfly

**Comment by jwforres** [comment]
opened https://github.com/patternfly/angular-patternfly/issues/346

**Comment by benjaminapetersen** [comment]
Lodash has a [noConflict](https://lodash.com/docs/4.17.2#noConflict) like jQuery that might allow us to load up the latest while we wait on dependencies (is only 4kB gzipped, don't think we have to worry much about file size for this one).

**Comment by spadgett** [comment]
This is done in https://github.com/openshift/origin-web-console/pull/1838
