### ISSUE TITLE
Web console: Log lines number are not selected, but still copied

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7693]
When I select text in a log, the lines numbers are not selected. Copying and pasting still includes the line numbers, however.

/cc @jwforres

**Comment by jwforres** [comment]
Wow that's annoying... what's the point in having the text not selected if it still copies it... is it every browser?

**Comment by spadgett** [comment]
Firefox is OK. Chrome and Safari copy the line number. Haven't checked IE.

**Comment by spadgett** [comment]
https://bugs.webkit.org/show_bug.cgi?id=80159

**Comment by jwforres** [comment]
Given how long that bug has been opened, and that they don't seem to
care... I'm leaning towards taking off the user-select CSS, it's great that
it works in firefox, but I think its worse that its misleading in
chrome/safari.

**Comment by spadgett** [comment]
I can't find a workaround.

We could leave the -moz prefixed version and remove the -webkit one.

**Comment by jwforres** [comment]
If we do that, leave a comment in the code referencing the webkit bug

**Comment by spadgett** [comment]
I have a real fix.

**Comment by spadgett** [comment]
I have a real fix for Chrome.

It doesn't work for IE. `-ms-user-select: none;` also isn't working in IE, so it's no worse.

https://msdn.microsoft.com/en-us/library/hh781492(v=vs.85).aspx

> none -- Blocks selection from starting on that element. **It will not block an existing selection from entering the element.**

**Comment by jwforres** [comment]
ok sounds good
