### ISSUE TITLE
oc import from insecure registry

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#7710]
I try to create an image stream for an image from an insecure registry. This registry is using self-signed certificates and authentication.

I'm on Origin:
```
oc v1.1.3
kubernetes v1.2.0-origin
```

I'm able to pull an image from this registry by copying the ca.crt in /etc/docker/certs/ec2-xxx:5000/ca.crt and by adding the right username + password:

```
docker login ec2-xxx:5000
Username (the_username): 
WARNING: login credentials saved in /home/centos/.docker/config.json
Login Succeeded
```

I'm able to pull an image from the registry.
But than I want to create an image stream. Herefor I have to create a secret:
```
oc secrets new-dockercfg mysecret --docker-server=ec2-xxx:5000 --docker-username=the_username --docker-password=the_password --docker-email=any@mail.com
```
After creating the secret I try to create my image stream. But I don't see how to connect the secret and the image stream:

```oc import-image --insecure ec2-xxx:5000/test/image:24 --confirm```

But this failed:
```
lastTransitionTime: 2016-03-01T10:40:48Z
      message: you may not have access to the Docker image "ec2-xxx/test/image:24"
      reason: Unauthorized
      status: "False"
```

The documentation is not very clear [here](https://docs.openshift.org/latest/architecture/core_concepts/builds_and_image_streams.html): importing-image-from-private-registries
_Once the secret is configured proceed with creating new Image Stream or using oc import-image command. During the import process OpenShift will pick up the secrets and provide to the remote party._

[Here](https://docs.openshift.com/enterprise/3.0/dev_guide/image_pull_secrets.html) I saw the secret being added to the service account. But it's only described in the part about pulling from a secure registry. I also tried it but it failed:

```
oc secrets new-dockercfg mysecret --docker-server=ec2-xxx:5000 --docker-username=the_username --docker-password=the_password --docker-email=any@mail.com
```
```
oc secrets add serviceaccount/default secrets/mysecret--for=pull
oc secrets add serviceaccount/builder secrets/mysecret
```
```oc import-image --insecure ec2-xxx:5000/test/image:24 --confirm```

still:
```
lastTransitionTime: 2016-03-01T10:40:48Z
      message: you may not have access to the Docker image "ec2-xxx/test/image:24"
      reason: Unauthorized
      status: "False"
```

**Comment by lorenzvth7** [comment]
@soltysh I saw the issue here: https://lists.openshift.redhat.com/openshift-archives/users/2016-February/msg00426.html

**Comment by soltysh** [comment]
@lorenzvth7 when looking for secret we try to identify server by the auth endpoint (see [here](https://github.com/openshift/origin/blob/b2699626b471ccaecb1f6cb0019fd08308cf2f3d/pkg/image/importer/credentials.go#L127) how we fallback to check if v1 docker hub wasn't requested). The best you can do to match the server is to increase the loglevel when running import and look for following log message: `Unable to find a secret to match` from [here](https://github.com/openshift/origin/blob/b2699626b471ccaecb1f6cb0019fd08308cf2f3d/pkg/image/importer/credentials.go#L131). This should give you the host+path value you should use for your docker-server flag.

**Comment by lorenzvth7** [comment]
@soltysh I tried to perform my import with loglevel 5:
```
oc import-image --insecure ec2-xxx:5000/test/image:24 --confirm --loglevel=5
I0301 17:30:48.383571   19973 loader.go:242] Config loaded from file /home/centos/.kube/config
I0301 17:30:48.384074   19973 loader.go:242] Config loaded from file /home/centos/.kube/config
I0301 17:30:48.384689   19973 loader.go:242] Config loaded from file /home/centos/.kube/config
I0301 17:30:48.385145   19973 loader.go:242] Config loaded from file /home/centos/.kube/config
I0301 17:30:48.408210   19973 loader.go:242] Config loaded from file /home/centos/.kube/config
I0301 17:30:48.408757   19973 loader.go:242] Config loaded from file /home/centos/.kube/config
The import completed successfully.

Name:			image
Created:		3 minutes ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2016-03-01T17:30:49Z
Docker Pull Spec:	172.30.85.11:5000/test/image

Tag	Spec										Created			PullSpec	Image
83	ec2-xxx:5000/test/image:24 Less than a second ago			import failed: you may not have access to the Docker image "ec2-xx-...

  ! tag is insecure and can be imported over HTTP or self-signed HTTPS
```

**Comment by lorenzvth7** [comment]
@soltysh 
The logs (level 5) showed me:
```
Unable to find a secret to match https://ec2-xxx:5000/v2/test/image/manifests/83 (ec2-xxx:5000/v2/test/image/manifests/83)
I0302 07:41:05.054381   37500 importer.go:430] unable to access tag "83" for repository &importer.importRepository{Ref:api.DockerImageReference{Registry:"ec2-xxx:5000", Namespace:"test", Name:"image", Tag:"83", ID:""}, Registry:(*url.URL)(0xc20c2ab480), Name:"test/image", Insecure:true, Tags:[]importer.importTag{importer.importTag{Name:"83", Image:(*api.Image)(nil), Err:error(nil)}}, Digests:[]importer.importDigest(nil), MaximumTags:0, AdditionalTags:[]string(nil), Err:error(nil)}: &url.Error{Op:"Get", URL:"https://ec2-xxx:5000/v2/test/image/manifests/83", Err:(*errors.errorString)(0xc20c2a3410)}
```
It's still not very clear for me what the logs try to tell me

**Comment by lorenzvth7** [comment]
@soltysh 
Okay I've created my secret with `--docker-server=https://ec2-xxx:5000`. Now I've 
Using project "test2".
```

$ oc describe is image
Name:			image
Created:		12 minutes ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2016-03-02T07:59:00Z
Docker Pull Spec:	172.30.xx.xx:5000/PROJECT/image

Tag	Spec											Created		PullSpec											Image
83	ec2-xxx:5000/test/image:83 !	12 minutes ago	ec2-xxx:5000/test/image@sha256:03d4c5090dd06a...	<same>

  ! tag is insecure and can be imported over HTTP or self-signed HTTPS
```

So the image stream seems to be important fine. But when I try to create an app from that image stream (on another node than I've pulled the image) it goes wrong again:
`Back-off pulling image "ec2-xxx:5000/test/image@sha256:03d4....`

`I added: other_args="--insecure-registry ec2-xxx:5000"` to my `/etc/sysconfig/docker` and performed a restart but didn't help

**Comment by lorenzvth7** [comment]
`INSECURE_REGISTRY='--insecure-registry ec2-xxx:5000'` did the job.
