### ISSUE TITLE
Regression: new-build / new-app input output cycle detection

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#7718]
```console
$ oc new-app -f test/extended/fixtures/incremental-auth-build.json 
--> Deploying template push-pull-builder for "test/extended/fixtures/incremental-auth-build.json"
error: output image of "demo/internal-image:latest" must be different than input, set a different tag with --to
```

Problems:
- The message is bad: `oc new-app` doesn't have (and shouldn't have) a `--to` flag, only `oc new-build`.
- The input and output images are not the same:

  ```json
          "sourceStrategy": {
            "from": {
              "kind": "DockerImage",
              "name": "centos/ruby-22-centos7:latest"
            }
          }
```
  ```json
        "output": {
          "to": {
            "kind": "ImageStreamTag",
            "name": "internal-image:latest"
          }
        },
```

- The behavior is off: `oc new-app -f template.json` should print a warning and proceed, just like `oc new-build` when it detects circular input/output with an explicit `--to` flag.

Introduced in #7321.

**Comment by rhcarvalho** [comment]
Another problem is that `oc new-app -f template.json` should not produce an error when it detects circular input/ouput in the template, but instead just print a warning.
At least that was the intended behavior for `oc new-build` when the output is explicitly set to cause a build loop.

**Comment by bparees** [comment]
@rhcarvalho +1 :(

**Comment by rhcarvalho** [comment]
We'll need more thorough tests around that. Should cover all IS x DI combinations, and new-app x new-build. new-app should never throw an error and stop, because users have no way to fix the problem (perhaps only through --name), but I think new-app was less prone to producing the build loop, that's one of the reasons not to have --to in new-app.

**Comment by bparees** [comment]
I wonder why the cycle detection logic thinks those two are the same...  must have to do with what the output imagestream is resolving to, but that is strange.

**Comment by bparees** [comment]
(made this P1 due to the potential to prevent users from deploying valid templates)

**Comment by rhcarvalho** [comment]
@bparees we'll need to distinguish not only an explicit flag `--to` in `oc new-build`, but also if we're dealing with new-build or new-app (only new-app can instantiate objects from a template):

- Users of `oc new-app` should always get at most a warning.
- Users of `oc new-build` should get a warning if `--to` is non-empty, or an error otherwise.

Sounds reasonable?

**Comment by bparees** [comment]
@rhcarvalho +1

**Comment by rhcarvalho** [comment]
Ensure these extended tests will be correct as well:

https://github.com/openshift/origin/blob/master/test/extended/builds/dockerfile.go#L37
https://github.com/openshift/origin/blob/master/test/extended/builds/dockerfile.go#L60
