### ISSUE TITLE
Networking smoke test for process-of-elimination e2e diagnostics.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#7719]
Upstream kube has a networking smoke test that confirms that the networks can send packets to one another through service endpoints.  We all know it well, the `intra-pod communication`  test.  And its a great smoke test for k8s clusters, especially small ones.

This test doesnt work on openshift, and we need another test which does something similar, so that we can have a processes of isolation for debugging other e2e's which integrate multiple features (mounts, networks, security, etc).

**Comment by jayunit100** [comment]
cc @timothysc @pmorie @marun running 'Networking' as the filter only runs:

-  should provide Internet connection for containers [Conformance]
-  should provide unchanging, static URL paths for kubernetes api services [Conformance]
- should function for intra-pod communication [Conformance]

Problem with these tests:

The third test gives us this info but it is overtesting - the tokens mounted into the service endpoints, the requirement that EVERY node on the cluster talks to every other node, and so on.  And its now a little flakey upstream esp on large clusters due to hardcoded timeouts... (and the first two don't tell us quite enough).

Proposal:  

Specifically, we need a test, which filters under 'Networking', which
- spins 2 pods (i.e. a client server is fine)
- confirms that they can send data to each other 
- is minimally coupled to other things (i.e. guesbook is great but it requires  external yamls etc, we can probably do a nginx or python one liner SimpleHTTP server to confirm basic connectivity).

**Comment by jayunit100** [comment]
@bbennett  we could be automating whats in https://docs.openshift.com/enterprise/3.1/admin_guide/sdn_troubleshooting.html for this, just make sure that real data is being provided through a fake webserver on one of the service endpoints.

**Comment by marun** [comment]
@jayunit100 We already have something similar to what you are proposing:

https://github.com/openshift/origin/blob/master/test/extended/networking/sanity.go#L16
https://github.com/openshift/origin/blob/master/test/extended/networking/sanity.go#L34

These tests have recently been merged upstream, which will replace our downstream tests:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/networking.go#L218

We also have the similar tests that validate multitenant isolation:

https://github.com/openshift/origin/blob/master/test/extended/networking/isolation.go

I think these tests cover requirements 1, 2, and 4 of your proposal.  I'm not sure about 3, though.  What do you think?

**Comment by marun** [comment]
@jayunit100 Also, #7701 contains a fix for the intra-pod test so that it will work on dind.  I'll rework it so that we can merge support for intra-pod working against non-dind openshift in advance of docker 1.10 landing.

**Comment by jayunit100** [comment]
@marun  the `[networking]` test looks good , and if the pod to pod tests cover this, then I think just updating the tag is sufficient.

**Comment by marun** [comment]
@jayunit100 I'm not sure the tag should be modified.  @smarterclayton?

My tactic has been to skip the first character:

https://github.com/openshift/origin/blob/master/test/extended/networking.sh#L28

**Comment by marun** [comment]
@jayunit100 How are you executing the tests if not with test/extended/networking.sh?   It supports testing arbitrary clusters: https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#running-networking-tests-against-any-cluster

**Comment by jayunit100** [comment]
lets not break  the convention ... i guess all origin ginkgo tags are lower case, 

if so that makes sense to keep it that way and fix the `[Slow]` tag to be `[slow]`.

then `ginkgo.focus=[Networking]|[networking] should work`

**Comment by jayunit100** [comment]
I'll close this for now - I think the lower case networking smokes solve my issue, and once we have upstream tests working for intra-pod, we wont need anything else.
thanks @marun !
