### ISSUE TITLE
oc status HPA enhancements

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#7722]
Forked from https://github.com/openshift/origin/pull/7678#issuecomment-190791407

- [ ] Warn about missing cpu requests against HPAs
- [ ] Warn about multiple HPAs assigned to the same resource

cc: @DirectXMan12 @deads2k

**Comment by deads2k** [comment]
@kargakis if you won't have time for this, we can see what @stevekuznetsov can do with it.

**Comment by kargakis** [comment]
If @stevekuznetsov has bandwidth, he can definitely take a stab at it.

**Comment by stevekuznetsov** [comment]
@deads2k should both of these be warnings or errors?

**Comment by kargakis** [comment]
I think the first should be an error and the second a warning
