### ISSUE TITLE
Web console: Status icon for pod needs to communicate both positive & negative termination

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#7726]
On a pod page a terminated pod's status icon can be a red x, which implies something went wrong.  However, if the exit reason is "completed" then the pod successfully completed it's task (ex: build) and was terminated.  The color can be misleading.
See screenshot:

![screen shot 2016-03-01 at 2 50 46 pm](https://cloud.githubusercontent.com/assets/280512/13439776/0e7a8e3c-dfbd-11e5-80ef-8b2a5d4ebba2.png)

Originated from discussion on [this PR](https://github.com/openshift/origin/pull/7669#issuecomment-190901003)

@spadgett @jwforres

**Comment by spadgett** [comment]
It looks like since we've switched from pod status to reason code in the pods table, it actually shows up as a green check mark and "Completed." Maybe we can do something similar for logs.

Easiest might be to show the reason and fall back to terminated if no reason. Then we're consistent with browse pods and CLI `oc get pods`.

**Comment by spadgett** [comment]
So I think the answer is to use reason when we can and change the icon to a more neutral color. (I'm not sure what we can use other than X, maybe a check mark.)

@benjaminapetersen can you update the logs PR to use reason in place of state if available?

**Comment by benjaminapetersen** [comment]
Gonna tack on another thought to consistency w/icons.  In the first screenshot, we have the `x` next to the container "Terminated", but on the details panel the container doesn't get an icon, only the pod:

![screen shot 2016-03-02 at 10 55 34 am](https://cloud.githubusercontent.com/assets/280512/13465861/70d9353a-e065-11e5-82b6-15d8dc91bea6.png)

So for containers, we should probably consistently use/not use icons.

**Comment by benjaminapetersen** [comment]
@spadgett yup, I'll add that as a todo.

**Comment by spadgett** [comment]
Yeah, I had meant to go update the pod details tab for better container statuses. We should show the state message if available and a status-icon for reason.

**Comment by benjaminapetersen** [comment]
PR accommodates both of these:

![screen shot 2016-03-02 at 2 51 16 pm](https://cloud.githubusercontent.com/assets/280512/13473371/163ae03e-e087-11e5-9d35-be31a00e6d57.png)

vs

![screen shot 2016-03-02 at 2 50 50 pm](https://cloud.githubusercontent.com/assets/280512/13473384/29bdb618-e087-11e5-9518-111c927f24e4.png)

**Comment by benjaminapetersen** [comment]
Udpated to show either container exit reason or container status key, but not both.  So will now look like:
![screen shot 2016-03-02 at 3 16 25 pm](https://cloud.githubusercontent.com/assets/280512/13473981/ed445108-e089-11e5-811b-a387de08116b.png)
