### ISSUE TITLE
Web console: clarify deployment logs

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#7727]
Currently we are swallowing some important details about deployment logs.  Given:
- Deploy 1
- Deploy 2 (in progress)
- Deploy 2

Deploy 2 (in progress) is really logs from the deployer pod, which is an openshift pod.  Once this is done the actual deployed pod for Deploy 2 is a pod running some component of your app.  

We need to clearly communicate "deployer pod running" vs "deployer complete, reload to get logs from your deployed pod" and give a user the ability to reload the logs to get the new logs from their running pod.

@jwforres @spadgett

**Comment by spadgett** [comment]
Agree, we need to tell users if the log is from the deployment or from their running app.

**Comment by benjaminapetersen** [comment]
And if I remember right from prev convo, if `{{deployment | deploymentStatus}} !== 'Deployed'` on page load, then this is the deployer.

**Comment by benjaminapetersen** [comment]
So even if we add a "Reload now...." message to refresh & get logs from the deployed pod, I'm not sure it is sufficient to clarify the ambiguity.  

![screen shot 2016-03-02 at 5 00 58 pm](https://cloud.githubusercontent.com/assets/280512/13477001/608d5c14-e098-11e5-9cba-1d9a3a3ca54b.png)

Thinking about possibilities.  We could automatically load the new logs (perhaps after a few seconds delay), but keep the deployer logs stashed & give the user an opportunity to swap back.  It seems like we have the assumption that if everything went well, you don't need the deployer logs once deployed (as there is no way to explicitly ask for them, as far as i understand).
