### ISSUE TITLE
Excessive output when multiple images returned for new-app on big repository.

### ISSUE THREAD

**Issue by miminar** [openshift/origin#7729]
Running hack/../test/cmd/builds.sh:52: executing 'oc new-build -D $'FROM openshift/origin:v1.1\nENV ok=1' --to origin-test:v1.1' expecting success...
    FAILURE after 2.031s: hack/../test/cmd/builds.sh:52: executing 'oc new-build -D $'FROM openshift/origin:v1.1\nENV ok=1' --to origin-test:v1.1' expecting success: the command returned the wrong error code
    There was no output from the command.
    Standard error from the command:
    error: multiple images or templates matched "openshift/origin:v1.1": 27

    The argument "openshift/origin:v1.1" could apply to the following Docker images or OpenShift image streams:

    * Docker image "openshift/origin:latest", 8cc5ae7, from local
      Use --docker-image="openshift/origin:latest" to specify this image or template

    * Docker image "openshift/origin:7ba70f0", 8cc5ae7, from local
      Use --docker-image="openshift/origin:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-sti-builder:latest", 3a9762e, from local
      Use --docker-image="openshift/origin-sti-builder:latest" to specify this image or template

    * Docker image "openshift/origin-gitserver:7ba70f0", 472e009, from local
      Use --docker-image="openshift/origin-gitserver:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-gitserver:latest", 472e009, from local
      Use --docker-image="openshift/origin-gitserver:latest" to specify this image or template

    * Docker image "openshift/origin-docker-builder:7ba70f0", cd107aa, from local
      Use --docker-image="openshift/origin-docker-builder:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-docker-builder:latest", cd107aa, from local
      Use --docker-image="openshift/origin-docker-builder:latest" to specify this image or template

    * Docker image "openshift/origin-recycler:7ba70f0", 828e007, from local
      Use --docker-image="openshift/origin-recycler:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-recycler:latest", 828e007, from local
      Use --docker-image="openshift/origin-recycler:latest" to specify this image or template

    * Docker image "openshift/origin-deployer:7ba70f0", 5cd5a66, from local
      Use --docker-image="openshift/origin-deployer:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-docker-registry:7ba70f0", f821f3b, from local, 38.658mb
      Use --docker-image="openshift/origin-docker-registry:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-keepalived-ipfailover:7ba70f0", 5b68f13, from local
      Use --docker-image="openshift/origin-keepalived-ipfailover:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-haproxy-router:7ba70f0", 8391e00, from local
      Use --docker-image="openshift/origin-haproxy-router:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-haproxy-router:latest", 8391e00, from local
      Use --docker-image="openshift/origin-haproxy-router:latest" to specify this image or template

    * Docker image "openshift/origin-pod:7ba70f0", df56d4e, from local
      Use --docker-image="openshift/origin-pod:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-pod:latest", df56d4e, from local
      Use --docker-image="openshift/origin-pod:latest" to specify this image or template

    * Docker image "openshift/origin-release:latest", 12a65c5, from local
      Use --docker-image="openshift/origin-release:latest" to specify this image or template

    * Docker image "openshift/origin-haproxy-router-base:latest", 71e799e, from local
      Use --docker-image="openshift/origin-haproxy-router-base:latest" to specify this image or template

    * Docker image "openshift/origin-base:latest", abb5237, from local, 70.131mb
      Use --docker-image="openshift/origin-base:latest" to specify this image or template

    * Docker image "openshift/origin-custom-docker-builder:latest", d7128e9, from local
      Use --docker-image="openshift/origin-custom-docker-builder:latest" to specify this image or template

    * Docker image "openshift/origin-custom-docker-builder:7ba70f0", d7128e9, from local
      Use --docker-image="openshift/origin-custom-docker-builder:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-deployer:latest", 5cd5a66, from local
      Use --docker-image="openshift/origin-deployer:latest" to specify this image or template

    * Docker image "openshift/origin-f5-router:latest", f24facb, from local
      Use --docker-image="openshift/origin-f5-router:latest" to specify this image or template

    * Docker image "openshift/origin-docker-registry:latest", f821f3b, from local, 38.658mb
      Use --docker-image="openshift/origin-docker-registry:latest" to specify this image or template

    * Docker image "openshift/origin-f5-router:7ba70f0", f24facb, from local
      Use --docker-image="openshift/origin-f5-router:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-keepalived-ipfailover:latest", 5b68f13, from local
      Use --docker-image="openshift/origin-keepalived-ipfailover:latest" to specify this image or template

    * Docker image "openshift/origin-sti-builder:7ba70f0", 3a9762e, from local
      Use --docker-image="openshift/origin-sti-builder:7ba70f0" to specify this image or template

Happened in #7128 (job [12095](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12095/console)).

**Comment by bparees** [comment]
this would imply a dockerhub flake since the image wasn't found on dockerhub when we asked.

either that or the imagestream pull through logic which new-app uses to try to find the image on dockerhub.

**Comment by smarterclayton** [comment]
This is a bug in new-app - if we have a tag specified on image name we are being specific and should *not* be searching for partial matches on repository name.

**Comment by bparees** [comment]
hm. I don't think i agree.  Obviously if there's an exact match, it's moot, we'll use the exact match, but if there's not, why wouldn't we be trying to help the user find matches in case of a typo?

@csrwng i think this has bearing on the behavior we just settled on for imagestreams.

**Comment by smarterclayton** [comment]
Ok, maybe I'm most concerned with the number of suggestions shown then, rather than them being there at all.  By the time I get to the end of the list it looks like a bug.  At some point, we should probably be showing a max N (or reasonable max N) and then telling the user to use -S to see the full list.  The levenshtein distance I would expect to be a component of match score.  As a user, I'm pretty sure I didn't accidentally fat finger not typing -keepalived-ipfailover.  Has to be some reasonable bound.  So we can change the bug into that.

**Comment by smarterclayton** [comment]
This is effectively fixed by #8558, so changing the title.
