### ISSUE TITLE
Web console: many pod warnings should be errors

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7733]
Many pod warnings are clear errors (crashing containers, image pull errors, etc.), and we have container status reasons that tell us exactly what is wrong (CrashLoopBackOff). We should show these as pod errors rather than warnings.

We have red available to us in the pod donut if we want since we don't show failed pods on the overview.

/cc @jwforres @liggitt @smarterclayton

**Comment by jawnsy** [comment]
@spadgett Is this something I can take on?
