### ISSUE TITLE
503 service unavailable

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin#7746]
I have successfully started the ha proxy router.  I have many happy pods running, yet all my routes take me to a 503 service unavailable error page.  I updated my resolv.conf file to have my master ip as nameserver; I've never had this problem on previous versions.  I installed openshift origin 1.1.3 with ansible; everything seems to be running smoothly like before but I just get 503 service unavailable errors trying to visit any route.

This is as close to having openshift origin set up perfectly as I have gotten.  My builds work great, container deployments always work now.  I thought I was finally going to have a smooth running Openshift; I just need to get past this last router issue.  It makes little sense.  I have set up a router many times before and never had this issue.  I've had issues with other parts of the system but never the router. 

I have looked at the journalctl logs for the master and node; everything looks fine.  The log for the router pod simply says: "Router is including routes in all namespaces".  The container logs of all of my services all look normal; they are all running fine.

Is there a better way to debug the router?

**Comment by kargakis** [comment]
I was hitting this as well and it turned out that it's a router service account permission issue. 
For those not following the users list, make sure that the router service account has the following permissions:
```
oadm policy add-scc-to-user privileged -z router
oadm policy add-scc-to-user hostnetwork -z router
oadm policy add-cluster-role-to-user system:router system:serviceaccount:default:router
```
The last command is redundant in the case the router was created w/o `--credentials`.

@deanpeterson is everything ok for you? If so, please close this issue.

**Comment by deanpeterson** [comment]
Yes,  that was my issue as well.  Yes, I am working now.
