### ISSUE TITLE
Using "Retry" policy for deployment lifecycle hook

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7754]
I was trying to use the "Retry" policy for database migration while working on the cakephp example. In this example, the pre-deployment hook is set to migrate the database. In some situation the database might not be ready yet, so I want to retry instead of "Abort".
The problem with "Retry" is that we will retry forever (the Pod will just keep retrying even thought I started another deployment).

I tried to add `maxRestarts` field to ExecNewPod in lifecycle hook and set it to maximum number of restarts after which we treat the deployment as "failed" and update the lifecycle pod with restart never.

The problem with that is that "deployer" SA does not have permissions to update pods (just view I guess).

Is there another way how to limit the number of retries? Or it is OK to keep retrying forever?

@ironcladlou @smarterclayton ?

**Comment by smarterclayton** [comment]
Why do you need to update the pod?  You can set restart on failure
(exit code 0) and then watch retry count.

**Comment by mfojtik** [comment]
@smarterclayton yes, but in that case the pod will retry forever, right? IOW. I start deployment, the pre-hook fails because it can't talk to DB, so it restarts... and will keep restarting till the DB is "ready". In case the DB will never be ready, it will keep restarting forever (or the interval will start increasing). What I want is that after N retries, the deployment is considered as "failed" and the pre-lifecycle pod is stopped.

**Comment by smarterclayton** [comment]
There is Restart=OnFailure.  You watch for counts and do an approximate.

**Comment by mfojtik** [comment]
@smarterclayton that is the default when you set the lifecycle-hook policy to "Retry". If the failure is permanent (iow. db not available) it will retry forever. I think it should not and it should fail the deployment after some time. But it might be correct based on k8s patterns ....

**Comment by smarterclayton** [comment]
Yes, I'm saying if you want max count you need to watch the pod for
restarts > max restarts and then fail the hook pod

**Comment by mfojtik** [comment]
@smarterclayton how I can fail the hook pod from the deployer pod if I have just view access?

**Comment by smarterclayton** [comment]
Two ways - have the cleanup controller enforce it, or give a deployer access to delete pods.  A deployer can already create pods.

**Comment by mfojtik** [comment]
(closed as we are going to use the deployment timeout instead of having two sets of timeouts)
