### ISSUE TITLE
Creating service on port 80 disables HA Proxy routing

### ISSUE THREAD

**Issue by david-strejc** [openshift/origin#7762]
When I create service on port 80 it pass without any warning and disables routing into HA Proxy pod by reconfiguring iptables.

**Comment by marun** [comment]
@david-strejc I would like to try to reproduce the problem you are experiencing, but require more detail.  Including configuration where applicable, please provide:

- the steps taken to create the router
- the steps taken to create the service
- relevant output of iptables on the node(s) involved
- the steps taken to verify connectivity

**Comment by sosiouxme** [comment]
Reopen if there is further information to reproduce.
