### ISSUE TITLE
godep restore doesn't work on clean GOPATH

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#7764]
Trying to bump our vendored copy of `source-to-image`, @kargakis instructed me to do `godep restore` followed by a `godep update ...`, however: 

```bash
$ mkdir -p /tmp/gopath/src
$ GOPATH=/tmp/gopath/src godep restore
# cd /tmp/gopath/src/src/k8s.io/kubernetes; git checkout bc4550d9e93d04e391b9e33fc85a679a0ca879e9
fatal: reference is not a tree: bc4550d9e93d04e391b9e33fc85a679a0ca879e9
godep: error downloading dep (k8s.io/kubernetes/cmd/kube-apiserver/app): exit status 128
godep: Error downloading some deps. Aborting restore and check.
```

@pweil- FYI

**Comment by liggitt** [comment]
You need to add the openshift/kubernetes repo as a remote and fetch it in order to godep restore.

https://github.com/openshift/origin/blob/master/HACKING.md#installing-godep
```
You must also have the Kubernetes repository checked out in your GOPATH (visible as ../../../k8s.io/kubernetes), with openshift/kubernetes as a remote and fetched:

$ pushd $GOPATH/src/k8s.io/kubernetes
$ git remote add openshift https://github.com/openshift/kubernetes.git
$ git fetch openshift
$ popd
```

**Comment by pweil-** [comment]
As @liggitt mentioned, it won't work on a clean gopath, you'll have to get the k8s dep and add/fetch the remote.

After that it will restore but the openshift-sdn dep will complain when it tries to compile.  It is importing two directories that don't exist in the fork or upstream yet, only as patches we're carrying to the GoDep (`util/term` and `util/homedir`)

**Comment by rhcarvalho** [comment]
@pweil- how to get it to work then?

**Comment by pweil-** [comment]
@rhcarvalho the sources were restored for me, it just complained about the package.   Normally, during a rebase we'll move the fork up to a level that includes all of the upstream patches so this wouldn't be an issue.  

cc @deads2k - maybe we should bump the fork commit again and bring it up to the origin level

**Comment by rhcarvalho** [comment]
Now I'm getting:

```console
$ godep restore
godep: Dep (github.com/google/cadvisor/api) restored, but was unable to load it with error:
        Package (github.com/seccomp/libseccomp-golang) not found
godep: Dep (github.com/google/cadvisor/http) restored, but was unable to load it with error:
        Package (github.com/seccomp/libseccomp-golang) not found
godep: Dep (github.com/google/cadvisor/manager) restored, but was unable to load it with error:
        Package (github.com/seccomp/libseccomp-golang) not found
godep: Dep (github.com/google/cadvisor/pages) restored, but was unable to load it with error:
        Package (github.com/seccomp/libseccomp-golang) not found
godep: Dep (github.com/google/cadvisor/validate) restored, but was unable to load it with error:
        Package (github.com/seccomp/libseccomp-golang) not found
godep: Dep (github.com/opencontainers/runc/libcontainer) restored, but was unable to load it with error:
        Package (github.com/seccomp/libseccomp-golang) not found
godep: Dep (github.com/openshift/openshift-sdn/pkg/cmd/admin/network) restored, but was unable to load it with error:
        Package (k8s.io/kubernetes/pkg/util/term) not found
godep: Dep (k8s.io/kubernetes/cmd/kubelet/app) restored, but was unable to load it with error:
        Package (github.com/seccomp/libseccomp-golang) not found
godep: Dep (k8s.io/kubernetes/pkg/kubelet) restored, but was unable to load it with error:
        Package (github.com/seccomp/libseccomp-golang) not found
godep: Dep (k8s.io/kubernetes/test/e2e) restored, but was unable to load it with error:
        Package (github.com/seccomp/libseccomp-golang) not found
godep: Error checking some deps.
$ godep update github.com/openshift/source-to-image/...
godep: Package (github.com/seccomp/libseccomp-golang) not found
```

:-(

**Comment by pweil-** [comment]
hmm, I didn't see that with mine.  Here is exactly what I did:  https://gist.github.com/pweil-/0e9d872a0035499e5a52

**Comment by rhcarvalho** [comment]
I started all over, and get the same problem as above.

I wrote a script that can reproduce the problem:
https://gist.github.com/rhcarvalho/588511322f5cef5371de

It clones origin and kube in a clean GOPATH, adds the openshift remote as described in HACKING.md, and fails to run `godep restore`.

@pweil- could you try to reproduce it? Am I missing something obvious?

**Comment by kargakis** [comment]
@rhcarvalho try to go get those missing packages and rerun godep restore

**Comment by kargakis** [comment]
Actually it's just github.com/seccomp/libseccomp-golang

**Comment by kargakis** [comment]
oh, you are cloning origin instead of go getting it, can you try that?

**Comment by rhcarvalho** [comment]
On the same terminal session where I ran the script yesterday:

```console
$ go get github.com/seccomp/libseccomp-golang
# github.com/seccomp/libseccomp-golang
/tmp/gopath/src/github.com/seccomp/libseccomp-golang/seccomp.go:25:22: fatal error: seccomp.h: No such file or directory
 // #include <seccomp.h>
                      ^
compilation terminated.
```

Am I missing some system package do get that header file?

I doubt `go get` will work better, because we use the import path `k8s.io/kubernetes` but the code we depend on is not there, but I'm giving it a shot anyway...

I replaced the `git clone` steps with `go get`:

```bash
...
# git clone https://github.com/openshift/origin
go get -v github.com/openshift/origin/...

...
# git clone https://github.com/kubernetes/kubernetes
go get -v github.com/kubernetes/kubernetes/...
...
```

**Comment by rhcarvalho** [comment]
BTW -- can I still use Go 1.4, or we require 1.5/1.6?

**Comment by rhcarvalho** [comment]
I updated the gist, as I expected `go get -v github.com/openshift/origin/...` doesn't work out-of-the-box either:

https://gist.github.com/rhcarvalho/588511322f5cef5371de#file-openshift-go-get-godep-restore-log

I have tried it without the script yesterday, what I can try again is to clone first, and `go get` after the extra remote for kube has been added -- and checking out the branch we vendor. Updating my script again.

**Comment by rhcarvalho** [comment]
I cannot `go get` our fork of kube:

```console
$ cd /tmp/gopath/src/k8s.io
$ git clone https://github.com/kubernetes/kubernetes
$ cd /tmp/gopath/src/k8s.io/kubernetes
$ git remote add openshift https://github.com/openshift/kubernetes
$ git fetch openshift
$ git checkout bc4550d9e93d04e391b9e33fc85a679a0ca879e9
$ go get -v github.com/kubernetes/kubernetes/...
/tmp/gopath/src/k8s.io/kubernetes/plugin/pkg/admission/initialresources/influxdb.go:24:2: code in directory /tmp/gopath/src/github.com/influxdb/influxdb/client expects import "github.com/influxdata/influxdb/client"
```

**Comment by rhcarvalho** [comment]
I really need reproducible steps to update `source-to-image` and fix https://github.com/openshift/origin/issues/7708 (P1).

My last attempt:

Script: https://gist.github.com/rhcarvalho/588511322f5cef5371de#file-openshift-go-get-godep-restore-sh
Console output: https://gist.github.com/rhcarvalho/588511322f5cef5371de#file-openshift-go-get-godep-restore-log

**Comment by pweil-** [comment]
@rhcarvalho please take a glance at https://github.com/openshift/origin/pull/7800
