### ISSUE TITLE
Compute resource units not explained in UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7768]
We use units like millicores and MiB in the UI, but we don't explain what they mean. These are not common like MB, GB, etc., and probably aren't familiar to most users.

/cc @jwforres @thesteve0 @derekwaynecarr

**Comment by thesteve0** [comment]
As a developer I always hated the AWS units of a xeon blah blah blah - wtf
does that mean to me. It is all magical units

**Comment by derekwaynecarr** [comment]
https://groups.google.com/forum/#!topic/artifactory-core/fsqu5p8WTCo

It looks like everyone is lying to their users...
