### ISSUE TITLE
Routes table header missing right border

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7769]
<img width="718" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13506497/6fced856-e14c-11e5-844e-d5bc7667ddf3.png">

Also the Create Route button no longer aligns with the right edge of the table. (Could be related to #7736.)

/cc @jwforres @sg00dwin @rhamilto

**Comment by rhamilto** [comment]
I've fixed this same bug in other contexts, so I'll fix it also here.
