### ISSUE TITLE
Extended networking job is failing due to junit processing error

### ISSUE THREAD

**Issue by marun** [openshift/origin#7773]
An otherwise successful invocation of [testonlyextended][extended:networking] on #7261 failed due to the following error:

``ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?``

Full log: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12190/consoleFull

I'm assuming that the expectations of the junit processor have changed but the extended tests were not updated to reflect the change.

**Comment by stevekuznetsov** [comment]
@danmcp what's the best plan for this? I'll disable the jUnit for now.

**Comment by danmcp** [comment]
@stevekuznetsov I don't know what you have done well enough to know.  If the issue is just that some tests will never output a junit report, I would be fine putting a dummy file in place at the end of the tests if a file doesn't already exist.

**Comment by stevekuznetsov** [comment]
Yeah, that's the issue. I'll do a trial run to see if a blank file makes the plugin happy

**Comment by marun** [comment]
@stevekuznetsov While it would be good to not fail the job because of junit processing, the failing job in question was outputting junit files as usual:

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12190/artifact/origin/artifacts/extended-tests/junit/extended/

**Comment by stevekuznetsov** [comment]
Yeah, that jUnit artifact isn't the one that the publish job was looking for, incidentally. 

@danmcp if that plugin is going to require that every single jUnit file we specify exists, this is going to be a PITA - if we fail early and don't get to `test-cmd`, for instance, the jUnit file for `test-cmd` won't exist but that for `test-go` might. I'll look into placing dummy files down.

**Comment by danmcp** [comment]
@stevekuznetsov I don't think you care if the files exist if you already failed.  But because you don't know what tests have ran with testonlyextended, I think the problem is the same of you have to create all the files you are looking for if they don't exist.

**Comment by danmcp** [comment]
@stevekuznetsov Unless it doesn't process any of the results if all of them aren't there.  Guessing maybe that's the case.  In which case you can't just do this at the end of the shell.  I think a post build step will work though.

**Comment by stevekuznetsov** [comment]
This *is* a post-build step, from the Jenkins jUnit plugin. Honestly I'd expect the plugin to publish whatever it can from the list of provided files, not to fail if any are missing.

**Comment by danmcp** [comment]
@stevekuznetsov I am saying a post build step which is a new shell to create the missing files.

**Comment by stevekuznetsov** [comment]
@danmcp understood.

**Comment by marun** [comment]
cc: @openshift/networking

**Comment by stevekuznetsov** [comment]
This should have been resolved. The publishing step is turned off for now.

**Comment by marun** [comment]
@stevekuznetsov When did the change take effect?  I noticed that the post-merge networking job failed due to this problem this morning: 

https://ci.openshift.redhat.com/jenkins/job/networking_extended/610/

**Comment by stevekuznetsov** [comment]
That seems to be an independent issue, the publish steps for
extended-networking and test-pull-reqests-origin are independent. It
warrants a new issue. I'll look into that as well.

**Comment by stevekuznetsov** [comment]
`networking_extended` is publishing OK now.

**Comment by stevekuznetsov** [comment]
@danmcp this can be closed, yes?
