### ISSUE TITLE
Remove description tags from the api

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#7786]
Now that we generate our descriptions from godoc, we should remove description tags.

@smarterclayton @mfojtik @liggitt @deads2k @stevekuznetsov

**Comment by deads2k** [comment]
As part of this work, we should write a reflective test to make sure we don't miss any.  We already have similar tests for watching our API.

**Comment by mfojtik** [comment]
@deads2k you mean test that check if there is no description left? I can use my find/sed script.

**Comment by deads2k** [comment]
> @deads2k you mean test that check if there is no description left? I can use my find/sed script.

I'd much prefer a more structured test like: https://github.com/openshift/origin/blob/master/pkg/api/latest/tags_test.go#L17 in reverse.

**Comment by stevekuznetsov** [comment]
Yep, this is planned as you suggest @deads2k

**Comment by smarterclayton** [comment]
I'd be in support of making sure all the tests have descriptions, but
not of one that checks that people don't set the description tag.  I
assume you're talking about the former.

**Comment by deads2k** [comment]
> I'd be in support of making sure all the tests have descriptions, but
> not of one that checks that people don't set the description tag.  I
> assume you're talking about the former.

I was figuring on both.  Why shouldn't we keep things tidy?

**Comment by smarterclayton** [comment]
It's not worth the effort to write the test and maintain it to check for
something that we can catch by casual periodic observation or code review.
  I'd rather all of the time the people on this PR have invested in
discussing it be spent *actually* improving our descriptions (which suck,
are user facing, are really important doc) than figuring out ways to ensure
we have sucky descriptions :)

**Comment by stevekuznetsov** [comment]
@smarterclayton isn't the work already basically done in the test David mentioned? It's pretty painless to implement it.

**Comment by smarterclayton** [comment]
My point is that we spend a lot of time checking things, which is
good, except when the thing we're checking isn't good enough to be
worth checking yet.  We have to be careful to balance "good code
quality" with "don't worry about splinters when there is iron rebar
poking through your arm".

**Comment by stevekuznetsov** [comment]
Point taken. Now that we've marked Godoc as user-facing, we should create a series of issues for code owners to update their Godoc, yes? This sort of thing almost happened in August, and I'll repeat what I said then: sure, I - or someone else for that matter - could run through the API and do it all, but for the sake of the users and the doc, it would be better for owners of the code to do it themselves so the more nuanced and difficult descriptions get done well. It'll get done much faster that way, as well.

**Comment by deads2k** [comment]
Changing `==` to `!=` here: https://github.com/openshift/origin/blob/master/pkg/api/latest/tags_test.go#L53 is hardly onerous.  He changes that or deletes the test to get it to pass.

**Comment by smarterclayton** [comment]
Yes, teams are responsible for their doc.  Opening nag issues to areas
addresses the human part of this particular issue.

**Comment by smarterclayton** [comment]
I'm just making a larger point, which is the time we spend on these
things is precious and we all need to be self critical in how we
apportion the time we spend in the non-user facing areas of the code.
We can have the best codebase in the world and if no one gets value
from our API doc its wasted time.
