### ISSUE TITLE
hack/test-go shows build errors in tmpdir instead of the source tree

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#7798]
For example:

```
/tmp/go-build179154832/github.com/openshift/origin/pkg/api/kubegraph/analysis/_test/_obj_test/hpa.go:26: invalid type assertion: ...
```

@smarterclayton thoughts on why?

**Comment by smarterclayton** [comment]
Just noticed this starting to happen.  No idea why, but I think it's
also correlated with a performance regression in our test-go speed
(what was 2s became 15s).  I did a quick audit of most recent changes
but didn't try bisection.  Can you try bisecting the changes to hack/*
and see which commit may have affected it?

Could also be a code change, but I would not expect that.  Might be
better to walk back until you can find it be fast on go 1.4 and then
bisect it from there.

**Comment by stevekuznetsov** [comment]
`test-go` speed seems unchanged for me on `go1.5.3`. I'll look into this.
