### ISSUE TITLE
Should there be a virtual service for the Openshift master?

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#780]
It occurred to me today looking at @pweil-'s work on the F5 router that we have to specially pass the URL of the OpenShift master to the router pod.  If we had a virtual service for the OpenShift master like `kubernetes-{,ro}` the router pod would be able to discover it via the normal env linking mechanism, and later, via DNS or whatever discovery is in fashion.

Thoughts? @liggitt @csrwng @smarterclayton @ironcladlou @pweil- @abhgupta

**Comment by liggitt** [comment]
that would be awesome as long as we have all the bits that go along with it (scheme: http or https), trusted certs (for https), and a way to make sure the trusted certs are valid for the IP/DNS the service is listed as (the master's cert won't be valid for some randomly assigned service IP...).

**Comment by liggitt** [comment]
a lot of this has surfaced in the upstream services reorg discussion

**Comment by pweil-** [comment]
Yeah, I think this would be handy in general, for infrastructure components specifically.  We'd want to make sure access is restricted but namespace privs should be taking care of that for us.

**Comment by pmorie** [comment]
@liggitt Those are good points, won't this be the same as for the kube master service eventually?

**Comment by smarterclayton** [comment]
Someone would need to work upstream to make the publish function usable by us.

**Comment by smarterclayton** [comment]
But yes, this is on the the list for 3.0.

**Comment by derekwaynecarr** [comment]
@smarterclayton - what is needed to make it usable by us?  If you have some thoughts I can make the change as part of my work creating the default namespace

**Comment by smarterclayton** [comment]
Expose publish in pkg/master in a way that allows someone to define a maintained service.  Basically a "NewServicePublisher" that takes a function to define endpoints and one to define the service if it needs to be created.

**Comment by derekwaynecarr** [comment]
Will pull something together monday.

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/pull/1510 exposes openshift.default.local via DNS but does not create an extra service.
