### ISSUE TITLE
Multi-tenant SDN adds a pod cache to all nodes which is O(pods) and also exceeds allowed info

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7801]
It looks like the primary use is a cache of pod ip to namespace in the filter.  This should not be necessary - we should guard this from the master with admission control, not at the nodes.  With that removed it looks like we have no need for the filter.  

@dcbw @knobunc I won't block 3.2 on this but this prevents us from properly defending the nodes against the possibility of compromise (since this filter can see all pods).  I'd like this prioritized as tech debt post 3.2.  It's also bad from performance perspective.  I'd also like an audit from someone on platform management for everything osdn needs on the node.

**Comment by smarterclayton** [comment]
At minimum the node cannot access all pods, and any enforcement should be moved to the master via admission.

**Comment by smarterclayton** [comment]
@pweil- if you can coordinate with Ben on a post 3.2 audit.

**Comment by smarterclayton** [comment]
Also, multi tenant SDN is watching services, and fetching the local pods.  So basically we have double the traffic of the kubelet.

**Comment by smarterclayton** [comment]
Digging in a bit more, I'm surprised to see that the multi tenant plugin needs access to all pods for a reason other than the filtering rules?

**Comment by smarterclayton** [comment]
@jeremyeder @timothysc are your cluster performance tests including multi-tenant SDN or just regular SDN?

**Comment by jeremyeder** [comment]
always multi-tenant from my side.

**Comment by timothysc** [comment]
same.

**Comment by danwinship** [comment]
> Digging in a bit more, I'm surprised to see that the multi tenant plugin needs access to all pods for a reason other than the filtering rules?

No, it shouldn't. There's a function that will theoretically get a list of all the pods on any given host, but it's only ever used to get the list of pods on the local host.

**Comment by smarterclayton** [comment]
Ok, all I see is createAndRunEventQueue("Pod") which fetches all pods, and
then the use of namespaceOfPodIP in filter.  It would be good to
discriminate in the Registry which methods are called on client and on
server so it's easier to audit.

**Comment by danwinship** [comment]
This was fixed by #9982. (Forgot this issue existed.)
