### ISSUE TITLE
Build strategy Docker: "noCache" working, "nocache" not working

### ISSUE THREAD

**Issue by livelace** [openshift/origin#7817]
Overall documentation contain "nocache" as example, but it not working in real. 

If I import (oc create -f build.yaml):

" strategy:
    type: "Docker"
    dockerStrategy:
      nocache: true
      forcePull: true"

Than I get (oc get -o yaml bc build):

" strategy:
    dockerStrategy:
      forcePull: true
    type: Docker"

**Comment by bparees** [comment]
docs have been fixed, thanks!
