### ISSUE TITLE
Extended tests not including JUnit results

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7818]
```
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
```

https://ci.openshift.redhat.com/jenkins/job/origin_extended/707/console

Looks like it broke in the last few days.  @danmcp did we change directories?

**Comment by stevekuznetsov** [comment]
fixed: https://ci.openshift.redhat.com/jenkins/job/origin_extended/709/testReport/

**Comment by stevekuznetsov** [comment]
@smarterclayton @danmcp unless this persists, we can close this issue, yes?
