### ISSUE TITLE
f5 plugin hardcodes admin user name

### ISSUE THREAD

**Issue by akram** [openshift/origin#7821]
Hi,

the admin user is hardcoded in the plugin:
https://github.com/openshift/origin/blob/master/pkg/router/f5/f5.go#L1517

For security reasons, it may be required to use another user (with restricted privileges) to configure the f5.
https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/tmos-concepts-11-4-0/10.html

Having to support these use cases may lead to errors that we do not handle in the current implementation.

**Comment by knobunc** [comment]
This is a duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1315157
