### ISSUE TITLE
Push of image failed "no basic auth credentials"

### ISSUE THREAD

**Issue by david-strejc** [openshift/origin#7825]
I've been told to open new issue for failing push of image into Docker Registry. (I don't know if it is duplicit with: https://github.com/openshift/origin/issues/4518 or not)
- my first build of my template passed in namespace1
- my second build of the same template failed in namespace2 (I was still logged in as same user)
- my third build inside namespace3 failed - both of them failed with:
- Error: build error: Failed to push image. Response from registry is:

`Post http://172.30.106.181:5000/v2/smith/redmine/blobs/uploads/: no basic auth credentials`

I am using same template for deployments.

Edit: I've tried fourth build and it passed - same template nothing modified.

Five bare metal servers in cluster deployed with openshift-ansible.

**Comment by david-strejc** [comment]
Should I provide some more info? This is in my opinion serious case.

**Comment by miminar** [comment]
@david-strejc `oc version` and the version of registry image would be helpful. Thanks!

But it seems to me you're hitting #4518. If the first build in a new namespace fails, does the second always succeed?

**Comment by paralin** [comment]
Same thing happening here, tbh not sure if it's the same as the other issue

**Comment by jhaohai** [comment]
Same thing for me.
Each time I start a new build it will failed to push the image with "no basic auth credentials".
However if I trigger this build second time it will success.
And it seems that it happens only if the image is too large.

**Comment by debianmaster** [comment]
same issue for me
`Build error: Failed to push image. Response from registry is: Post http://172.30.27.88:5000/v2/dev/we/blobs/uploads/: no basic auth credentials
`

very frustrating

**Comment by bparees** [comment]
There were issues at some point with service account credentials not being created properly when projects were created.  This would result in the builder service account not having a credential to use when pushing images.  I am going to assume that's what these users faced (to all of you, I apologize that no one followed up on your issue in a timely fashion), so I am going to close this, but if someone has a current environment where this is still a problem we can investigate it.
