### ISSUE TITLE
Duplicit route whithout warning confuses developers

### ISSUE THREAD

**Issue by david-strejc** [openshift/origin#7826]
I've created two projects P1 and P2. In second project I've created same route (same URL) as in P1. This passed without warning.

Then I was confused by Open Shift not rebuilding my P2 project - but everything was OK according to logs. 

I've found that I got same URL for P1 and P2. 

Maybe this is just theoretical but when I will be the "bad guy" I can allocate many URLs (which I don't own) and block real owners of those domains to deploy their apps.

I don't know if this should be in Open Shift internal mechanisms - to check if I am real owner of domain I've specified, but there should be definitely "Warning" about duplicate URL usage. (I can imagine having this warning on main page of namespace deployment - "Warning you are using duplicate URL in your project route"

**Comment by liggitt** [comment]
The router honors the oldest route to request a URL. Whether a route was honored or not is reported back in the route status, and surfaced in the UI (as of https://github.com/openshift/origin/pull/7725)

**Comment by knobunc** [comment]
The ability to have one route mask another is desirable to allow seamless cut-over from one to the other.  Add the second route, and then remove the first when ready to cut.  Without that, there would be a gap.

As to whether someone has permission to create a router for a particular domain, I think that is a policy question that would need to be handled on an installation by installation basis using an admission controller:
* https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/authorization.html#admission
* https://docs.openshift.org/latest/install_config/configuring_admission_control.html

**Comment by spadgett** [comment]
Here's what the warning looks like in the UI:

![screen shot 2016-03-07 at 10 32 47 am](https://cloud.githubusercontent.com/assets/1167259/13574047/688310f6-e450-11e5-9d0d-369e680d6416.png)
