### ISSUE TITLE
test/cmd/policy.sh flake

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#7831]
Seen in https://github.com/openshift/origin/pull/7713

```
SUCCESS after 0.185s: hack/../test/cmd/policy.sh:49: executing 'oc login -u alternate-cluster-admin-user -p anything --config=/tmp/tmp.xAvS7G7kVWpolicy/tempconfig' expecting success
Running hack/../test/cmd/policy.sh:55: executing 'oc replace --config=/tmp/tmp.xAvS7G7kVWpolicy/tempconfig clusterrole/alternate-cluster-admin -f /tmp/tmp.xAvS7G7kVWpolicy/alternate_cluster_admin.yaml' expecting success...
FAILURE after 0.084s: hack/../test/cmd/policy.sh:55: executing 'oc replace --config=/tmp/tmp.xAvS7G7kVWpolicy/tempconfig clusterrole/alternate-cluster-admin -f /tmp/tmp.xAvS7G7kVWpolicy/alternate_cluster_admin.yaml' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: error when replacing "/tmp/tmp.xAvS7G7kVWpolicy/alternate_cluster_admin.yaml": User "alternate-cluster-admin-user" cannot update clusterroles at the cluster scope
```

Full logs: https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5212/console

**Comment by deads2k** [comment]
@liggitt figures.  I'll add the `who-can` updates to the list.

**Comment by deads2k** [comment]
p2, unless it becomes more prevalent.  

@rhcarvalho can you add the indicator to the failure causes so we can keep track of frequency?

**Comment by rhcarvalho** [comment]
> @rhcarvalho can you add the indicator to the failure causes so we can keep track of frequency?

@deads2k sorry I don't understand, could you please clarify?

**Comment by deads2k** [comment]
We have failure cause analysis turned on for jenkins, so you can describe a regex that matches when certain kinds of failures happen here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/failure-cause-management/ .  By doing that the jenkins status page will show the flake and you can link to this issue.

It also tallies up the number of failures for that cause, so we know which flakes are the worst.

**Comment by rhcarvalho** [comment]
@deads2k thank you. I've added an entry there.
