### ISSUE TITLE
empty config file is reported as no config file `

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#7834]
empty config file...
```
[root@localhost vagrant]# cat /openshift.local.config/master/admin.kubeconfig
[root@localhost vagrant]# oc get nodes --config=/openshift.local.config/master/admin.kubeconfig
error: No configuration file found, please login or point to an existing file:
```
sais no config file
```
error: No configuration file found, please login or point to an existing file:
  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
```

**Comment by liggitt** [comment]
that is working as designed. the alternative is a more confusing error saying "default cluster is not defined".

**Comment by jayunit100** [comment]
s `error: No configuration file found, please login or point to an existing file:` to error: `No configuration DATA found, please login or point to an existing file:`

**Comment by dhan2vijay** [comment]
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
getting this issue can one solve this please

**Comment by Akaronte** [comment]
downgrade docker to 1.13.1

yum install -y  wget git zile nano net-tools docker-1.13.1\
                                bind-utils iptables-services \
                                bridge-utils bash-completion \
                                kexec-tools sos psacct openssl-devel \
                                httpd-tools NetworkManager ntp\
                                python-cryptography python2-pip python-devel  python-passlib \
                                java-1.8.0-openjdk-headless "@Development Tools"

**Comment by lokeshdevops7023** [comment]
hello all, i tried to install the openshift cluster in aws using ocp , in dashboard it shows cluster is ready but am not able to get oc get nodes , and am not able to access the end-url as well , please help me
![Screenshot from 2021-12-06 15-16-03](https://user-images.githubusercontent.com/83347399/144824503-84d0310c-301c-4c38-84e8-62a8587fa906.png)
![Screenshot from 2021-12-06 15-16-12](https://user-images.githubusercontent.com/83347399/144824511-b10dbc15-b35c-429c-af56-0041677c3a47.png)
![Screenshot from 2021-12-06 15-16-18](https://user-images.githubusercontent.com/83347399/144824515-c886393d-ca25-4bd8-b1da-5cca6977f729.png)
