### ISSUE TITLE
Question regarding on could not resolve host

### ISSUE THREAD

**Issue by enlinxu** [openshift/origin#7840]
Hi,
I built the openshift on top of my Ubuntu VM. But when I tried to build a simple ruby hello-world, I keep getting. F0307 18:18:50.810159 1 builder.go:204] Error: build error: fatal: unable to access 'https://github.com/openshift/ruby-hello-world.git/': Could not resolve host: github.com; Unknown error

I tried restart my docker but still it doesn't work during rebuild. What did I miss?

Thanks a lot in advance.

**Comment by jawnsy** [comment]
Maybe a silly question, but have you verified that you can do a "git clone" from that repository directly on the node? This sounds like an external DNS issue of some sort, so we should first verify that it's not something obvious.

**Comment by enlinxu** [comment]
Hi Jawnsy,
Yes, I can do git clone from the node. Basically I am deploying openshift origin on my Ubuntu VM, and I deployed it by git clone from git repo, and build the binary.

**Comment by jawnsy** [comment]
Can you run these commands and share the output?

```
$ ping github.com
$ nslookup github.com
$ git clone https://github.com/openshift/ruby-hello-world.git/
```

Also do the same commands from within a Docker container, by using:

```
$ docker run --rm -it openshift/base-centos7 /bin/bash
```

to get a shell. This will help us rule out whether there may be network problems from inside the Docker infrastructure. This could happen if there's a problem with the iptables rules or bridge configuration (docker0.)

Are you building with `oc new-app` or using the `s2i` command?

**Comment by jawnsy** [comment]
There hasn't been any activity on this for awhile. @enlinxu, has your problem been resolved? If not, please post the information requested in the previous comment so that we can proceed.

**Comment by enlinxu** [comment]
@jawnsy sorry about that. I restarted the openshift and the problem doesn't happen any more. I will close the issue. Thanks for the help!

**Comment by wenchma** [comment]
@enlinxu restart can fix the issue, 👍
