### ISSUE TITLE
Deploy openshift with Kubernetes cluster

### ISSUE THREAD

**Issue by enlinxu** [openshift/origin#7841]
Openshift origin comes with Kubernetes. I have built a Kubernetes cluster on top of Rhel vms following https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/getting-started-with-containers/chapter-3-creating-a-kubernetes-cluster-to-run-docker-formatted-container-images . But if I want to install openshit origin with a kubernetes cluster, shall I just follow https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/getting-started-with-containers/chapter-3-creating-a-kubernetes-cluster-to-run-docker-formatted-container-images to install the nodes only, assuming that the Kubernetes master is already running after the binary built from Openshift.

**Comment by paralin** [comment]
@enlinxu See http://github.com/paralin/openshift-under-kubernetes

You can just deploy it on top of kube
