### ISSUE TITLE
hello-openshift example should build binary as part of docker build file

### ISSUE THREAD

**Issue by sferich888** [openshift/origin#7846]
If you run the following and try and build the example hello-openshift example, you get an error, because the binary has to be built and checked into the repository. 

```
# oc new-app https://github.com/openshift/origin --context-dir=examples/hello-openshift/ 
```

You end up with errors like: 

```
# oc logs origin-1-build
W0307 22:29:34.294887       1 builder.go:55] Master version "v1.1.3-317-g2de63e3" does not match Builder image version "v1.1.3"
I0307 22:29:34.295734       1 source.go:197] Downloading "https://github.com/openshift/origin" ...
Step 0 : FROM scratch
 ---> 
Step 1 : MAINTAINER Jessica Forrester <jforrest@redhat.com>
 ---> Using cache
 ---> 27f75fd21e45
Step 2 : ADD bin/hello-openshift /hello-openshift
F0307 22:30:55.489347       1 builder.go:204] Error: build error: bin/hello-openshift: no such file or directory
```

However adding go binaries, so that builds can be done in this image may be a problem as, this image is abased on [scratch](https://github.com/docker-library/hello-world)

**Comment by jawnsy** [comment]
This sounds like something relatively simple that I could take on. @danmcp can you assign this to me?

**Comment by sferich888** [comment]
There are other samples that have the same issue and it might just be a matter of choosing a different base image.

**Comment by csrwng** [comment]
@jawnsy @sferich888 At some point, I created an example in extended tests to build the hello-openshift image. Unfortunately, as you discovered, this can't yet be done in a single step. The way that s2i builds currently work is that the s2ibuilder image along with built artifacts are committed to a new image. However, for hello-openshift, we don't want the golang compiler, along with other tools to be included in the final image. We only want a single binary to be in the image.

You can accomplish this with the build definitions here:
https://github.com/openshift/origin/blob/bb7ce11420f862d807207b0ff4eff7664627b0f6/test/extended/fixtures/test-build-hello-openshift.yaml

There are 3 build configurations in that file:
1. hello-builder (docker): Builds the s2i builder to be used to compile the go binary (it's simple additions to the origin-release image that already includes all golang tools). I'm sure this can be done more generically to build other go binaries, but this is just one example.
2. hello-openshift-binary (s2i): Builds the hello-world binary
3. hello-openshift (docker): Builds the final image with the Dockerfile

**Comment by csrwng** [comment]
The source for the hello-builder can be found here:
https://github.com/openshift/origin/tree/master/test/extended/fixtures/hello-builder

**Comment by sferich888** [comment]
Should we just re-build this example with https://github.com/openshift-s2i/s2i-go not that its available?

**Comment by jawnsy** [comment]
@sferich888 The s2i-go image keeps the build toolchain around in the resulting image. Quoting @csrwng:

> for hello-openshift, we don't want the golang compiler, along with other tools to be included in the final image. We only want a single binary to be in the image.

So unfortunately just rebuilding with s2i-go is insufficient today. :(
