### ISSUE TITLE
Should not link to full view of log that's not available

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7848]
<img width="720" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13589167/d8993034-e4a3-11e5-9016-da783459155b.png">

/cc @benjaminapetersen @jwforres

**Comment by jawnsy** [comment]
Is this an easy bug that I could help with? I've done some JS before but would need to learn how to build our assets, which is something I'd like to learn at some point anyway :)

**Comment by benjaminapetersen** [comment]
@jawnsy this is probably a pretty simple fix.  Ping me on IRC, can help you get setup if you are really interested in helping out!

**Comment by spadgett** [comment]
Remove the "Log from..." message as well when there's no log?

**Comment by benjaminapetersen** [comment]
Yeah, we should just `ng-if` hide all that as well.

**Comment by jawnsy** [comment]
Added a simple ng-if for the link text. I still have to hunt down the "Log from" message and fix that, and I will need to test it.

@spadgett @benjaminapetersen Do you have instructions to reproduce this condition? I guess I just need to run a build, which I haven't done yet (so far I've only created from a template, but it wasn't triggered by any build.) Is there a simple example that I could run `oc new-app` from?

**Comment by spadgett** [comment]
@jawnsy Easiest way is to run a build, and then delete the build pod manually. When you look at the build log in the web console, you'll see the log not available error. If you have an old build, you might not need to delete the pod, just open the log.

**Comment by jawnsy** [comment]
It took me longer than I'd care to admit to realize that you can check ng-if state from a child element of the `log-viewer` element. Anyway, this seems to work when testing locally - I reproduced the empty log situation by deleting the build pod manually (using `oc get pods` and `oc delete pod`.)

I tested on Chrome Beta, haven't tried other browsers but I don't imagine that I'd need to in this case.

@spadgett Can you please review?

**Comment by jawnsy** [comment]
Ah, nevermind. Got too excited. This also breaks the case where logs actually are present.

Has logs, "Open in viewer" link appears, but "Log from" information is missing:

![screenshot from 2016-03-09 14-54-38](https://cloud.githubusercontent.com/assets/52710/13653528/1985695a-e607-11e5-9d3e-d558d415f973.png)

No logs, so link is suppressed and "Log from" information is removed:

![screenshot from 2016-03-09 14-53-45](https://cloud.githubusercontent.com/assets/52710/13653532/1d4e9d7c-e607-11e5-8f48-e301dc859b79.png)

**Comment by spadgett** [comment]
@jawnsy I'm not sure what to recommend other than moving the timestamps back into the directive so it can hide them. We just pulled those out, though :(

@benjaminapetersen Any ideas?

**Comment by benjaminapetersen** [comment]
Ah, hmm.... thinking....

**Comment by jawnsy** [comment]
@benjaminapetersen Thoughts? Should I do what @spadgett suggested and just move the timestamps back into the directive? Is there another, better, way to do this? It seems unfortunate to undo recent changes, but I can't think of any better solution.

cc @jwforres

**Comment by benjaminapetersen** [comment]
Yeah, the problem there is that they are semi-unique now.  Build, Pod, Deployment all have a slightly different handling of the presentation.  If we back step to something generic we can share that may work, but I think we lose the clarity we were striving for here.  

I suppose adding an attribute to the directive `<log-viewer has-logs="{{hasLogs}}">` and letting the directive publish out to that attribute so we can use it to show/hide other things in the template may work, so long as it is two-way bound.
