### ISSUE TITLE
Kibana fatal error : : NetworkError: A network error occurred. (:0)

### ISSUE THREAD

**Issue by jfcoz** [openshift/origin#7850]
Hello

I've installed openshift with ES/Kibana ...

oc version :
oc v1.1.3
kubernetes v1.2.0-origin

When I expand a document in Kibana, I'm always redirected to an error page : 

```
Oops!

Looks like something went wrong. Refreshing may do the trick.

or clear your session
Fatal Error
: NetworkError: A network error occurred. (:0)

Error: : NetworkError: A network error occurred. (:0)
window.onerror@https://kibana.xxxx/index.js?_b=7562:46032:24

Fatal Error
Error: : NetworkError: A network error occurred. (:0) (https://kibana.xxxx/index.js?_b=7562:46032)

Error: Error: : NetworkError: A network error occurred. (:0) (https://kibana.xxxx/index.js?_b=7562:46032)
window.onerror@https://kibana.xxx/index.js?_b=7562:46032:24
```

On the log of the kibana pod I get : 

`{"name":"Kibana","hostname":"logging-kibana-1-03m6b","pid":8,"level":30,"req":{"method":"GET","url":"/worker-json.js","headers":{"if-none-match":"W/\"11bf8-873763449\"","if-modified-since":"Tue, 08 Sep 2015 20:12:30 GMT","connection":"close","cookie":"openshift-auth-proxy-session=xAcHMQcX9Rgldj-bo_72Fg.wv7T8CsVQ2A42UOpZDagWqgbi1CUzHNX8yX_x5Df9hBM_Y2lzA8OZJIA_Hv0y3yVCutAjRWgrZagtMXD4OCq63rgsKG3bk4q-vVi_DaxmPqAnfVzU-dqGxYjxnZKTfI6A13Fi2Hby4ohD1cVfK9OpzwAy-DtPghyYZPaBMnDbOTMCUX7_IyV4nG6Dq-YCJTn.1457421875593.3600000.SJhW3XJHgLH9bNdpstjp8AJyAuS-vHBP72-O2BVmqtw","referer":"https://kibana.xxxx/","dnt":"1","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.5","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0 Iceweasel/43.0.4","host":"kibana.xxxx","x-proxy-remote-user":"xxx","authorization":"Bearer xxxxx"},"remoteAddress":"127.0.0.1","remotePort":47836},"res":{"statusCode":304,"responseTime":0,"contentLength":0},"msg":"GET /worker-json.js 304 - 0ms","time":"2016-03-08T08:14:45.028Z","v":0}`

Have you got an idea to correct this ?

Thanks

**Comment by jfcoz** [comment]
Update : it fails with Firefox (latest stable).
Works OK with Vivaldi/Chrome/IE

**Comment by jcantrill** [comment]
@jfcoz Can you provide steps on how you produced this error.  We have some changes that are forthcoming which it would be nice to figure out if this issue would be resolved by them

**Comment by jfcoz** [comment]
@jcantrill , It's just a fresh install with this documentation : https://docs.openshift.org/latest/install_config/aggregate_logging.html (already re-installed two days ago).

Then on the discover tab, when searching *, I get a correct document list. But when I click the expand button (right arrow) on front of the document, the detail table appears for a few ms and then redirect to the error page.

**Comment by ewolinetz** [comment]
@jcantrill I was able to recreate this even with our origin code, but only with Firefox.

This is the error displayed on the Kibana page:

Error: Error: Script file not found: worker-json.js (:0)
window.onerror@https://kibana.example.com/index.js?_b=7562:46032:24

**Comment by jcantrill** [comment]
@jfcoz can you confirm if you are still experiencing this problem?
