### ISSUE TITLE
support using rkt and runC

### ISSUE THREAD

**Issue by ibotty** [openshift/origin#7851]
It would be great to support running rkt and runC containers. That includes integration into the docker registry etc.

**Comment by rhatdan** [comment]
We are experimenting with rkt and runc currently.  I know CoreOS is working to get rkt to work with k8s, which is critical.

**Comment by phemmer** [comment]
Now that kubernetes supports rkt, is there any update on this? If we use openshift origin on top of a [bring-your-own-kubernetes](https://github.com/kubernetes/kubernetes/tree/master/examples/openshift-origin) backed by rkt, will it work?

**Comment by ediri** [comment]
yepp, could be interesting to know

**Comment by nico2610** [comment]
I'm also interested

**Comment by Shashwatsh** [comment]
+1

**Comment by rhatdan** [comment]
I think at this point, people should look at CRI-O which is a Docker replacement for container workloads, supports runc as well as Kata Containers.  It is fairly easy to swap out other OCI compliant runtimes as well.
