### ISSUE TITLE
Should control user create "NodePort" service

### ISSUE THREAD

**Issue by mdshuai** [openshift/origin#7852]
Now scc and policy can't control user create "NodePort" service. Create a "NodePort" service will open a port on all the node.
Should control user do this and only admin create this type service.

**Comment by mdshuai** [comment]
@ncdc

**Comment by liggitt** [comment]
SCC is only for pods. Policy is only for object-level control, not field-level. This is one more example of field-level authorization we need.

**Comment by smarterclayton** [comment]
You should be able to disable this totally by setting the node port range to the empty string (or 0).  Agree that we want finer grained control and it is related tonpolicyc

**Comment by mdshuai** [comment]
field-level authorization SGTM

**Comment by liggitt** [comment]
> field-level authorization SGTM

Yes… it's not for lack of wanting that we don't have it :)
