### ISSUE TITLE
Adopt PostCSS autoprefixer

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7853]
See conversation in #7559.

https://github.com/postcss/postcss
https://github.com/nDmitry/grunt-postcss

/cc @jwforres @benjaminapetersen @sg00dwin @rhamilto

**Comment by jwforres** [comment]
Is there still an interest in adopting PostCSS autoprefixer?  Anybody want to own this?

**Comment by benjaminapetersen** [comment]
I think we could close this and open a new one in origin-web-console, might take some new research to see where things are at this point?

**Comment by jwforres** [comment]
i disagree with moving issues over just for the sake of moving them :)  let's just resolve these one way or another and get them closed.

**Comment by benjaminapetersen** [comment]
Both of the links still look active & maintained  https://github.com/postcss/postcss  https://github.com/nDmitry/grunt-postcss

**Comment by benjaminapetersen** [comment]
Yeah, I don't think we want to go through the trouble of adopting `postcss` unless we are getting more than `autoprefixer` for it.  Seems like a big investment.  `grunt-autoprefixer` is deprecated, but build passes, etc.  We may want to reconsider some day in the future, but for now, I'd say we close this.
