### ISSUE TITLE
console does not mention development lifecycle features like hot deploy and rsync

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#7856]
Users coming in from the web console would have no idea that we have support for hot deploy or rsync today.  At a minimum we should probably mention these features from the Next Steps page.  We should consider whether we need to tag / label an image as supporting hot deploy so that we can notify you when looking at a deployment that you can do hot deploy to develop.

**Comment by jwforres** [comment]
cc @bparees @spadgett

**Comment by bparees** [comment]
would we label the image or annotate/tag the imagestream?  I assume the latter, though I hate the disconnect (when are getting labels on images created as annotations on imagestreamtags again?)

**Comment by jwforres** [comment]
I hate the disconnect in this case as well, I'd prefer the image itself be
able to say that it supports hotdeploy.

On Tue, Mar 8, 2016 at 11:57 AM, Ben Parees <notifications@github.com>
wrote:

> would we label the image or annotate/tag the imagestream? I assume the
> latter, though I hate the disconnect (when are getting labels on images
> created as annotations on imagestreamtags again?)
>
@smarterclayton ?

**Comment by smarterclayton** [comment]
I really think images should say they support hot deploy.

**Comment by bparees** [comment]
that's fine, but we still have to put it on the imagestream also until/unless we are turning image labels into imagestreamtag annotations.  unless you're suggesting the console go interrogate the image associated w/ the imagestream (in which case i'm pretty sure @jwforres is headed your way w/ something sharp)

**Comment by smarterclayton** [comment]
Ultimately Image stream tags are supposed to be a stopgap, not a solution.

**Comment by jwforres** [comment]
@bparees bumping this discussion.  So today we already fetch the ImageStreamTag in order to get the Env information for the image, so as long as the proposed data is available from the image metadata on ImageStreamTag then I think we could do this today.

Anything stopping us from going ahead and labeling images that support hot deploy?

**Comment by bparees** [comment]
@jwforres nothing other than picking the annotation(?) name/value we'll use to indicate it.

**Comment by jwforres** [comment]
openshift.io/hot-deploy-enabled  ?

**Comment by bparees** [comment]
hot-deploy-supported?

**Comment by bparees** [comment]
(enabled depends on the configuration of the pod.  supported depends on the capabilities of the image, so if it's an annotation on the imagestreamtag, i think supported is the right term)

**Comment by jwforres** [comment]
Works for me

**Comment by jwforres** [comment]
based on discussion with @bparees last week it sounds like this information is not going to be that useful, even if the image is capable of doing hot deploy, if things are not configured correctly then it may not actually work.  will link to this issue from the "enable hot deploy" story, and closing this

**Comment by jwforres** [comment]
https://trello.com/c/NZwR9Mpu
