### ISSUE TITLE
Openshift CLI should warn users when they are running a different version client than the server

### ISSUE THREAD

**Issue by brentos** [openshift/origin#7862]
It would be nice if the Openshift CLI gave a warning when the client/server versions don't match up. When there is a mismatch, strange behavior can be experienced and it is not always clear what the problem is.

**Comment by jawnsy** [comment]
Related: [Bug 1306590 - [RFE] Optionally reject connection from older client versions [NEEDINFO]](https://bugzilla.redhat.com/show_bug.cgi?id=1306590)

**Comment by jawnsy** [comment]
Also copying @fabianofranz's comment from the Bugzilla entry:

> There is a workaround that works today and allows you to reject commands if client and server don't match to the *exact* same version.
>
> Use the global "--match-server-version" flag, and alias the "oc" command to make sure it is *always* executed with that flag. For example:
>
> alias oc="/path/to/oc --match-server-version"

**Comment by danmcp** [comment]
Closing in favor of the bug.
