### ISSUE TITLE
Name, Value fields on the create form are not truncating properly and expanding to the right in Firefox on Mac and Windows

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#7870]
The name/value fields under Build Config., Deployment Config., and Labels will expand beyond their grid container with have long values.

<img width="257" alt="screen shot 2016-03-08 at 2 56 38 pm" src="https://cloud.githubusercontent.com/assets/1874151/13615296/a2a2c220-e542-11e5-9b19-cd342cd034b3.png">
<img width="1025" alt="screen shot 2016-03-08 at 3 33 02 pm" src="https://cloud.githubusercontent.com/assets/1874151/13615386/19940b14-e543-11e5-8aa0-8449d2691a8f.png">
<img width="739" alt="screen shot 2016-03-08 at 2 58 54 pm" src="https://cloud.githubusercontent.com/assets/1874151/13615294/a2a0c4e8-e542-11e5-8376-bee1e4a88984.png">

**Comment by sg00dwin** [comment]
After dissecting the markup and flex rules associated with the areas that should be truncated, then moving up the markup structure, I've learned the problem is associated with the way Firefox assigns width to the ```fieldset```. In order to enable responsive like behaviors twbs recommends making ```fieldsets {display:table-cell}```. 

1) Firefox and fieldsets
http://getbootstrap.com/css/#tables-responsive

**Comment by jawnsy** [comment]
Thanks @sg00dwin, I was looking at this too and was able to reproduce your problem, but was scratching my head as to how to fix it.

Does this mean we just need to add this:

```
@-moz-document url-prefix() {
  fieldset { display: table-cell; }
}
```

to our CSS somewhere?

**Comment by jawnsy** [comment]
I can confirm that `display: table-cell` fixes it (when I add it via the Inspector), I'll open a PR with that change.
