### ISSUE TITLE
Possible to clean /var/lib/origin/openshift.local.volumes?

### ISSUE THREAD

**Issue by donovanmuller** [openshift/origin#7878]
My `/var/lib/origin/openshift.local.volumes` is taking up a large amount of space and the volume that it is mounted on is running low on space.

Is it safe to remove items under `/var/lib/origin/openshift.local.volumes` or is there another suggestion on how to reclaim some space?

**Comment by donovanmuller** [comment]
Sorry to be a pain but this is becoming an issue.
I was forced to remove everything under `/var/lib/origin/openshift.local.volumes/pods` because of 100% usage and things seemed to recover fine, although there were some funnies but might have been unrelated. I might have to do this again very soon and will feedback on how it goes.

Just out of interest, what info is actually kept in this directory (would help if we could delete or not)?

**Comment by donovanmuller** [comment]
Further on this, I have a few Gluster volumes, one of which is home to the OpenShift internal registry volume. Checking for the top 10 largest directories in `/var` brings back the following:

![screen shot 2016-04-23 at 2 37 45 pm](https://cloud.githubusercontent.com/assets/1175891/14761440/fc0e2d34-0961-11e6-998f-c7876521cdad.png)

So looks like `/var/lib/origin/openshift.local.volumes/pods/bef2ac82-e106-11e5-9be9-4439c455fd51/volumes/kubernetes.io~glusterfs/registry` is taking the same space as the actual Gluster volume:

![screen shot 2016-04-23 at 2 41 58 pm](https://cloud.githubusercontent.com/assets/1175891/14761446/25a0fb04-0962-11e6-9237-5ba68af5e23d.png)

and

![screen shot 2016-04-23 at 2 46 51 pm](https://cloud.githubusercontent.com/assets/1175891/14761449/4dff2788-0962-11e6-8331-4d4f970edb6b.png)

This doesn't seem correct? Based on the above it looks like the there is double the space being used for the same Gluster volume.

Any ideas on this and the original question (as this is actually the main issue then...)

**Comment by subodhp** [comment]
Even I am facing the same issue. No concrete solution yet. Kubernetes has some implementation for XFS Quota in its Go Scripts.

**Comment by fushilong** [comment]
I am encountering this issue too,could anyone please give a suggestion on this?

**Comment by DanyC97** [comment]
what is not clear to me is if `/var/lib/origin/openshift.local.volumes` is being part of the `devicemapper` storage driver or not.

If not then why not ? If yes then it should be easier w.r.t extending the lvm.
