### ISSUE TITLE
No dockerImageManifest in ImageStreamImages

### ISSUE THREAD

**Issue by stefwalter** [openshift/origin#7880]
When loading images via `/oapi/v1/images` there is a `dockerImageManifest` present in the JSON result. When loading the same image via `http://localhost:8001/oapi/v1/namespaces/<ns>/imagestreamimages/<name>@sha256:<hash>` then the dockerImageManifest is not present.

**Comment by stefwalter** [comment]
```
oc v1.1.3-380-g2eb8022
kubernetes v1.2.0-alpha.7-703-gbc4550d
```

**Comment by stefwalter** [comment]
I couldn't figure out where ImageStreamImage is generated using ```git grep``` any tips?

**Comment by kargakis** [comment]
cc: @miminar @smarterclayton @ncdc

**Comment by miminar** [comment]
See https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestreamimage/rest.go#L84 in commit https://github.com/openshift/origin/commit/730f1f52a33feb979e5996fb52aae1f6ba2293a9 . I'm not sure why. @smarterclayton would know the best.

**Comment by ncdc** [comment]
`dockerImageManifest` is the raw JSON of the actual Docker image manifest, and (at least up until now), it's only populated when you retrieve /images because that's needed for the registry to serve up manifests. Do you have a need for the raw JSON when retrieving an ImageStreamImage?

**Comment by stefwalter** [comment]
> Do you have a need for the raw JSON when retrieving an ImageStreamImage?

Yes that would allow us to implement the designs for an image registry pased on openshift. One of the things we do is render a graph of the various image layers, and what each image layer represents. For this, the dockerImageManifest is important.

In additon, since Images cannot be accessed by most users, having dockerImageManifest in ImageStreamImage is important.

**Comment by liggitt** [comment]
those embedded raw JSON API types are pretty bad to maintain... not excited about spreading their use :-/

**Comment by ncdc** [comment]
I think it'd make more sense to extend the go types to include layer information. Yes it's some more data duplication, but that's better than passing around the raw JSON. That's only there because we have to be able to serve up the manifest unmodified (including preserving whitespace), and it's the safest way to make sure we can do that.

**Comment by stefwalter** [comment]
The following information is what I would consider interesting:

 * The layer digest
 * The size of the layer
 * Description of what changed in the layer (eg: the DockerFile line for Docker image layers)
 * Creation date of the layer
 * Layer Signatures

There's probably more, but just suffice it to say that the current dockerImageLayers omits several interesting pieces of info.

**Comment by miminar** [comment]
> There's probably more, but just suffice it to say that the current dockerImageLayers omits several interesting pieces of info.

@stefwalter and it will be even worse. With manifest [schema v2](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#image-manifest-field-descriptions) (which we will sooner or later) implement you'll see just the first two of the mentioned.

**Comment by smarterclayton** [comment]
Short term, which calls do you need this info on?  The reason we don't
return it is size of calls and the escaping of schema control.

Date on layers is reasonable (for whatever that means).  I hate
signatures and want them to die.  Description is generic but what
docker gives us isn't very good.

**Comment by stefwalter** [comment]
> Short term, which calls do you need this info on?  

Broadly speaking: It needs to be viewable at a project level, by both users in the role of project admin and project viewer.

I imagined It would be included in ImageStreamImage, since other parts of Image are available there. But if there is another better location for retrieving this info at a project level, open to adjusting to that.

Here's an example of a view that uses this info. There are a couple others that use the info from the first layer as a fallback when Origin hasn't populated it elsewhere in the image data. But I imagine we can deal with those separately.

![screenshot from 2016-03-10 07-29-40](https://cloud.githubusercontent.com/assets/795070/13661458/219d150c-e693-11e5-9b42-50977ef63c5b.png)

> Date on layers is reasonable (for whatever that means).  I hate
signatures and want them to die.  

Agree with the sentiment on image signatures. So more broadly the questions we want to answer are: "Who did this image or layer come from? Who signed off on it?"

> Description is generic but what docker gives us isn't very good.

Right. So again more broadly, the description is something that helps answer the user question: "Why is this layer here? What does it contain and do?" This is especially interesting in the future when we show a layer shared between images.

**Comment by stefwalter** [comment]
Opened the obvious pull request #7956 (thanks @minimar) but not attached to it. I'd be happy if it was replaced with a better fix, either before or after merging.

**Comment by smarterclayton** [comment]
Trying to peer into the crystal ball.

1. We won't be only supporting Docker images.
2. We want to support historical browsing of layered images (where
possible) but not all future images will be layered (i.e. image A has
parent image A', vs just being a whole cloth image)
3. We want to have detached signatures (API call X allows ui to assert
image is valid), but docker has it innately.  Suggestion - it be a
subordinate API on images
4. Manifests are massive and make list calls die.  Options - never show
manifests, only show manifests on GET, make manifests be an optional
inclusion (needs upstream API concordance), introduce a new API endpoint,
or surface manifest data in different ways

Kind of suggests we should transform the simple data into image API calls
(provide abstraction), have a way to fetch individual manifests, have
signatures be a new subresource.  Agree / disagree?

Do you ever fetch it in a list?

**Comment by stefwalter** [comment]
> Kind of suggests we should transform the simple data into image API calls (provide abstraction), have a way to fetch individual manifests, have signatures be a new subresource.  Agree / disagree?

Yup, makes sense.

> Do you ever fetch it in a list?

Currently there's no way to list images for users that don't have global read access to the cluster. Would be ideal to be able to fetch images, layers, signatures in a list for a single project.

**Comment by smarterclayton** [comment]
GET /imagestreamimages doesn't work?

**Comment by kargakis** [comment]
> GET /imagestreamimages doesn't work?

Nope

**Comment by smarterclayton** [comment]
I suppose we can fix that with a list that includes manifests as well
(or side by side).  We can also support field select if necessary on
image stream for Jessica's "get all images on this image stream" need.
