### ISSUE TITLE
Connector icon between service and deployment-block is clipped 

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#7887]
<img width="781" alt="screen shot 2016-03-09 at 9 59 45 am" src="https://cloud.githubusercontent.com/assets/1874151/13639394/8b0591dc-e5de-11e5-81e9-c91ef3a03938.png">

**Comment by sg00dwin** [comment]
Caused by addition of ```overflow:hidden``` to .deployment-block
https://github.com/openshift/origin/blob/master/assets/app/styles/_components.less#L144

@spadgett is this is needed?

**Comment by spadgett** [comment]
@sg00dwin It's there to prevent a long replication controller or deployment name from overflowing the box, but obviously causes other problems :(

**Comment by spadgett** [comment]
@sg00dwin This is what it's guarding against, but we might not need it. Or possibly we can move the style to a child element.

I'll check what the longest name is.

<img width="203" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13640613/5d5a40b6-e5e3-11e5-86b1-6d01a68b44b2.png">

**Comment by spadgett** [comment]
Replication controller name can be 253 characters.
