### ISSUE TITLE
cluster-reader should be able to GET from the api proxy

### ISSUE THREAD

**Issue by mwringe** [openshift/origin#7894]
A user with cluster-reader permissions should be able to perform GET requests against the api proxy.

A user with cluster-reader permissions should be able to perform the following command:

curl --insecure -H "Authorization: Bearer `oc whoami -t`" -X GET https://localhost:8443/api/v1/proxy/namespaces/openshift-infra/services/https:heapster:/

**Comment by liggitt** [comment]
Root proxy is not partitioned by verb, and GET on proxy cannot be guaranteed to be non escalating
