### ISSUE TITLE
UXP: Add Validated SCC to 'oc describe <pod>'

### ISSUE THREAD

**Issue by screeley44** [openshift/origin#7901]
Add ability to see which SCC the pod was validated against when using 'oc describe pod mypod'.  Better user experience as user doesn't have to search for it in the -o yaml

```
[root@k8dev nfs_error]# oc describe pod bb-host-pod1
Name:			        bb-host-pod1
Namespace:		        default
Validated SCC Policy:	hostmount-anyuid     <--- added this to the describe
Image(s):		        busybox
...
```

one liner from what I can tell by adding in pkg/security import for allocator:
```
fmt.Fprintf(out, "Validated SCC Policy:\t%s\n", pod.Annotations[allocator.ValidatedSCCAnnotation])
```

@smarterclayton @erinboyd @jeffvance  - thoughts?

**Comment by jeffvance** [comment]
@screeley44 this seems simple enough to go directly to a PR. I have not had a chance to look at the code, but I suspect you can leverage the scc display from `oc export pod` annotations output.

**Comment by smarterclayton** [comment]
@kargakis since this is a change to the CLI
