### ISSUE TITLE
UXP: Confusing or Unclear errors in 'oc describe' when mounting volumes - bubble up useful errors as events to be displayed

### ISSUE THREAD

**Issue by screeley44** [openshift/origin#7902]
As an example, if I'm submitting a pod with PV/PVC for GlusterFS and the endpoints are missing - a generic error is received:  Error syncing pod, skipping: unsupported volume type

this error is misleading and the user is then left wondering/searching for the real cause, even something simple like in this case that the endpoints for the gluster cluster is missing or gone.  I would like to add an event that shows up in the 'oc describe' where many users first go to analyze errors when something goes wrong.  in most cases there is an error generated in the log with the real cause, but it's not surfaced easily to the user.

Example output from 'oc describe' would look like this for this particular example:

```
Events:
  FirstSeen LastSeen    Count   From            SubobjectPath   Type        Reason      Message
  --------- --------    -----   ----            -------------   --------    ------      -------
  12s       12s     1   {scheduler }                Normal      Scheduled   Successfully assigned bb-gluster-pod2 to k8dev.rhs
  12s       2s      2   {kubelet k8dev.rhs}         Warning     FailedMount Unable to mount volumes for pod "bb-gluster-pod2_default(a040fca7-e189-11e5-b936-52540092b5fb)": endpoints "glusterfs-cluster" not found
```

This would be accomplished by added useful error messages in the endpoint types (glusterfs.go, nfs.go, etc...) when needed and then setting them as an event using the kubelet event recorder like so:

```
kl.recorder.Eventf(ref, api.EventTypeWarning, kubecontainer.FailedMountVolume, "Unable to mount volumes for pod %q: %v", format.Pod(pod), err)
```

@smarterclayton @erinboyd @jeffvance - thoughts?

**Comment by screeley44** [comment]
Created an issue upstream:  https://github.com/kubernetes/kubernetes/issues/22992

**Comment by screeley44** [comment]
Created upstream k8 PR:  https://github.com/kubernetes/kubernetes/pull/23122

**Comment by kargakis** [comment]
Seems fixed now
