### ISSUE TITLE
Confirm "all green" on extended tests

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#7903]
After the next rebase  we will want to hunt down the extended.test results and confirm 100% green.

Follow up issue to #6882 .

Please assign to me...

UPDATE

Here are the currently failing tests as (_April_)

```
    Extended Core.Services should serve a basic endpoint from pods [Conformance]
    Extended Core.EmptyDir volumes should support (non-root,0666,tmpfs) [Conformance]
    Extended Core.Kubectl client Kubectl label should update the label on a resource [Conformance]
    Extended Core.EmptyDir wrapper volumes should becomes running
```

**Comment by deads2k** [comment]
@liggitt guess you should at least try a run on the rebase before merging.

@jayunit100 have you considered creating two special kube buckets.  One of a set of whitelisted, known good e2e tests and one of the a blacklisted set of known bad.  We *might* block the rebase on a whitelisted failure.  Then the blacklisted set would give you pass/fail information on the new tests that came in on the rebase.

**Comment by jayunit100** [comment]
@deads2k Yup, so, everything that passes extended test filtering is a white feature, so that is the bucket...
 The skipped tests I guess in your analogy are "bad ones".

It used to be the case that many tests failed for unknown reasons, now we have a good understanding of most failures, so the amount of unknown unknowns is quite small (was around 20, now under 5).

**Comment by jayunit100** [comment]
can we reassign to @sgallagher  , as he is working on this now.....   @sgallagher 
- i can help on the e2e side of things 
- im not quite sure how to replicate a openshift cluster for testing this.

**Comment by smarterclayton** [comment]
Closing due to age.
