### ISSUE TITLE
Router: default cert for edge route not being used

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#7904]
I am creating a router with 
```
oadm router --default-cert=router.pem --credentials=${KUBECONFIG} --service-account=router
```

When I create an edge route to a service and I hit that route, the certificate I'm getting back is not the one I created the router with.

Looking into the router pod, the certificate I gave it on create is at: 
```
/etc/pki/tls/private/tls.crt
```

but the certificate I'm getting back when hitting the route looks like the one at:
```
/var/lib/haproxy/conf/default_pub_keys.pem
```

This is causing the gitserver extended test to fail because git comes back with a 'certificate expired' error.

**Comment by csrwng** [comment]
@smarterclayton @liggitt

**Comment by smarterclayton** [comment]
@ramr @knobunc

**Comment by ramr** [comment]
@smarterclayton  I think was broken with the secrets changes. I will look at it. 

Meanwhile @csrwng  can you run the router option with  `--secrets-as-env=true`  and see if that gets you going.

**Comment by smarterclayton** [comment]
The path changed in the image - it's possible that one of them was dropped.

**Comment by ramr** [comment]
yeah, I think the defaultCertificatePath is not set. Did make the fix - testing it right now.
