### ISSUE TITLE
new-app: should not complain about circular image-stream reference if not generating objects itself

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#7906]
When creating a list of objects with ```new-app -f incremental-auth-build.json```
using this file:
https://github.com/openshift/origin/blob/master/test/extended/fixtures/incremental-auth-build.json

new-app should not complain about a circular image reference:
1) because the build will not loop indefinitely... there's no triggers to do that
2) because you are creating from a list of objects and new-app is not generating them... presumably you know what you're doing.

**Comment by csrwng** [comment]
@bparees

**Comment by bparees** [comment]
@rhcarvalho I think you're working on something related to this and have an issue for it?

**Comment by rhcarvalho** [comment]
This is a dupe of https://github.com/openshift/origin/issues/7718

**Comment by bparees** [comment]
thanks @rhcarvalho
