### ISSUE TITLE
Attach storage link too close to deployments table

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7909]
Browse deployment config page:

<img width="710" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13648837/ced122da-e608-11e5-80e9-bd8e6f945693.png">

**Comment by jawnsy** [comment]
Looks like a job for the new guy! (me)

I'll work on this. I guess we just need to add a margin-bottom to the "Attach storage" class or a margin-top to the table? Not sure what the preferred conventions are here.

**Comment by jawnsy** [comment]
I can reproduce this, but interestingly, it only seems to be a problem when _only_ the "Attach storage" link is available:

![screenshot from 2016-03-09 15-08-18](https://cloud.githubusercontent.com/assets/52710/13653878/05bb0db0-e609-11e5-966b-88aa7868cf85.png)

If there are two links then it renders fine (or, well, at least it looks a bit better -- IMO this feels like it leaves _too_ much space):

![screenshot from 2016-03-09 15-09-01](https://cloud.githubusercontent.com/assets/52710/13653888/113ebe16-e609-11e5-89a2-9339698ee523.png)

**Comment by spadgett** [comment]
@rhamilto I think you already have a fix in #7937?

**Comment by rhamilto** [comment]
@spadgett, yep.  #7937 should fix this one.
