### ISSUE TITLE
Can't read selected log text in Firefox

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7916]
<img width="854" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13652177/ba69891c-e618-11e5-8ad7-2b90ed6062cc.png">

I believe it's possible to change the selected text styles in CSS. Not a problem in Chrome.

/cc @jwforres @sg00dwin

**Comment by jawnsy** [comment]
It looks readable to me, though I don't know if the contrast ratio is sufficient to pass WCAG guidelines. I think I've used this tool in the past to test this: [Colour Contrast Tester](https://www.paciellogroup.com/resources/contrastanalyser/) and there are similar checks we could run (e.g. using Chrome's Accessibility Developer Tools)

It looks like both browsers are using a default highlighting color. We should be able to change it using `::selection`: [Overriding The Default Text Selection Color With CSS - CSS Tricks](https://css-tricks.com/overriding-the-default-text-selection-color-with-css/)

![screenshot from 2016-03-09 14-39-41](https://cloud.githubusercontent.com/assets/52710/13653202/1195d038-e605-11e5-92a3-7c336c5a9792.png)

**Comment by spadgett** [comment]
@jawnsy Was your screenshot from Chrome? Because that's much more legible than what I see in Firefox.

**Comment by jawnsy** [comment]
@spadgett Screenshot from Firefox (actually Iceweasel 44.0.2 ... sorry, I run Debian :blush:)

I wonder if this depends on a default system highlight color defined somewhere? If so, it might make more sense to apply the same selection style to Chrome (and other browsers) as well.
