### ISSUE TITLE
cgroup.procs error in devenv_ami

### ISSUE THREAD

**Issue by danmcp** [openshift/origin#7927]
We are getting this a lot in devenvs:

[8] System error: open /sys/fs/cgroup/devices/system.slice/docker-fc2e8c0bfdef0d585ed13e784ccc1024ec33f4f01e3c4c992ea15b38abca58b7.scope/cgroup.procs: no such file or directory
!!! Error in hack/build-images.sh:91
	'docker build -t $1:latest $2' exited with status 1
Call stack:
	1: hack/build-images.sh:91 image(...)
	2: hack/build-images.sh:104 main(...)

Ex: https://ci.openshift.redhat.com/jenkins/job/devenv_ami/3679/console

This may be similar or a dup of:

https://github.com/openshift/origin/issues/7616

**Comment by mrunalp** [comment]
This may not get fixed by https://github.com/projectatomic/docker/pull/71 (which is for #7616). I am looking into this one.

**Comment by mrunalp** [comment]
Created https://bugzilla.redhat.com/show_bug.cgi?id=1317059 to get help from systemd devs.

**Comment by smarterclayton** [comment]
@rhatdan @mrunalp I think at this point this is a 3.2 blocker - are we getting the appropriate attention from the other side?

**Comment by mrunalp** [comment]
@smarterclayton We have got some responses. I will try it out. As a backup plan I can backport some PRs and we can use the cgroupfs driver.

**Comment by rhatdan** [comment]
Right worse case we just use cgroupfs driver.  @smarterclayton you can probably test that by just changing the /etc/sysconfig/docker

**Comment by mrunalp** [comment]
Setting this option will use the cgroupfs driver
```
--exec-opt=native.cgroupdriver=cgroupfs
```

**Comment by mrunalp** [comment]
I have created this PR per the feedback we got on systemd-devel list. https://github.com/projectatomic/docker/pull/76 We need to build a new RPM and test it out.

**Comment by smarterclayton** [comment]
```
F0322 02:09:45.188964       1 builder.go:204] Error: build error: API error (500): Cannot start container 2a7da6dc87c1d24fed96b687a89b9121308cbce1e984ac0cc2508ecc6b6a4646: [8] System error: write /sys/fs/cgroup/memory/system.slice/docker-2a7da6dc87c1d24fed96b687a89b9121308cbce1e984ac0cc2508ecc6b6a4646.scope/memory.limit_in_bytes: invalid argument
```

Same problem or new one?

**Comment by smarterclayton** [comment]
@bparees this is failing all PRs and builds (or almost all of them).  Is this something net new that may have been added by you?

**Comment by smarterclayton** [comment]
```
  2h	2h	1	{kubelet openshiftdev.local}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "deployment" with RunContainerError: "runContainer: API error (500): Cannot start container fbe9e90c1d1e910fbc4ca978226f6556d0e495299be1d31583e4eec7e6eb4907: [8] System error: The minimum allowed cpu-shares is 1024\n"
```

```
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   7206621
 Built:        Mon Jan 25 20:52:22 UTC 2016
 OS/Arch:      linux/amd64
```

Is this the cpu-shares bug in docker @derekwaynecarr ?

**Comment by mrunalp** [comment]
Is docker updated to 1.9.1-23?

**Comment by bparees** [comment]
@smarterclayton the error in build-images is not related to anything i've done.

this failure is one we've had an open [issue](https://github.com/openshift/origin/issues/7549) on for a while now:
`F0322 02:09:45.188964       1 builder.go:204] Error: build error: API error (500): Cannot start container 2a7da6dc87c1d24fed96b687a89b9121308cbce1e984ac0cc2508ecc6b6a4646: [8] System error: write /sys/fs/cgroup/memory/system.slice/docker-2a7da6dc87c1d24fed96b687a89b9121308cbce1e984ac0cc2508ecc6b6a4646.scope/memory.limit_in_bytes: invalid argument`

**Comment by mrunalp** [comment]
Can we close this issue if we aren't seeing this in the new docker rpm?

**Comment by smarterclayton** [comment]
Going to close this once the v1.1.5 builds are out

**Comment by mrunalp** [comment]
@smarterclayton Thanks!

**Comment by mrunalp** [comment]
Can we close this now since 1.1.5 is out?
