### ISSUE TITLE
Long, unbroken words don't wrap in pod template

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7932]
![screen shot 2016-03-10 at 2 32 40 pm](https://cloud.githubusercontent.com/assets/1167259/13681822/2164b5ec-e6cd-11e5-9c2b-0c94232759d9.png)

/cc @jwforres @sg00dwin @rhamilto

**Comment by spadgett** [comment]
![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13704500/4ae56996-e76a-11e5-96c7-c1796d91093a.png)

**Comment by rhamilto** [comment]
Since I've already been tinkering with pod templates, I'll take this one.
