### ISSUE TITLE
deployment doesn't start automatically from deployment config

### ISSUE THREAD

**Issue by Yashu5** [openshift/origin#7942]
## Version
oc v1.1.0.1
kubernetes v1.1.0-origin-1107-g4c8e6f4

I have created a deployment config taking reference from some example. Here whenever I create my app using this, it doesn't start  deployment automatically. Each time I need to click on "deploy"  button on console to deploy my app. Below is the deployment config definition I am using:

 
{
    "kind": "DeploymentConfig",
    "apiVersion": "v1",
    "metadata": {
        "name": "spring-petclinic",
        "creationTimestamp": null,
        "labels": {
            "app": "spring-petclinic"
        },
        "annotations": {
            "openshift.io/generated-by": "OpenShiftNewApp"
        }
    },
    "spec": {
        "strategy": {
            "type": "Rolling",
            "rollingParams": {
                "updatePeriodSeconds": 1,
                "intervalSeconds": 1,
                "timeoutSeconds": 600,
                "maxUnavailable": "25%",
                "maxSurge": "25%"
            },
            "resources": {}
        },
        "triggers": [
            {
                "type": "ConfigChange"
            }
        ],
        "replicas": 1,
        "selector": {
            "app": "spring-petclinic",
            "deploymentconfig": "spring-petclinic"
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "app": "spring-petclinic",
                    "deploymentconfig": "spring-petclinic"
                },
                "annotations": {
                    "openshift.io/generated-by": "OpenShiftNewApp"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "spring-petclinic",
                        "image": "test/spring-petclinic",
                        "resources": {},
                        "terminationMessagePath": "/dev/termination-log",
                        "imagePullPolicy": "Always"
                    }
                ],
                "restartPolicy": "Always",
                "terminationGracePeriodSeconds": 30,
                "dnsPolicy": "ClusterFirst",
                "securityContext": {}
            }
        }
    },
    "status": {}
}

any help, why it doesn't start automatically?

**Comment by kargakis** [comment]
Note that a bunch of deployment related bugs have been fixed ever since 1.1.0.1. Not sure why you can't automatically start with a ConfigChange, we had a similar regression but it was much later (not between versions) and related to having both a ConfigChange and an ImageChange trigger (automatic set to false). I am able to run the initial deployment for your dc on latest master.
```
[vagrant@localhost sample-app]$ oc version
oc v1.1.3-554-g808619c-dirty
kubernetes v1.2.0-alpha.7-703-gbc4550d
[vagrant@localhost sample-app]$ oc create -f dep.json 
deploymentconfig "spring-petclinic" created
[vagrant@localhost sample-app]$ oc get pods
NAME                        READY     STATUS              RESTARTS   AGE
spring-petclinic-1-04ilx    0/1       ContainerCreating   0          2s
spring-petclinic-1-deploy   1/1       Running             0          5s
[vagrant@localhost sample-app]$ oc logs -f dc/spring-petclinic
I0311 11:01:49.754611       1 deployer.go:199] Deploying new/spring-petclinic-1 for the first time (replicas: 1)
I0311 11:01:49.827453       1 recreate.go:126] Scaling new/spring-petclinic-1 to 1 before performing acceptance check
I0311 11:01:51.883519       1 recreate.go:131] Performing acceptance check of new/spring-petclinic-1
```
A couple of questions: I was able to deploy your app with `oc new-app openshift/wildfly-100-centos7~https://github.com/Yashu5/spring-petclinic`. How did you run `oc new-app` with your code? Did you edit your dc after it was generated and what was the original version of it? When running the dc you posted, OpenShift will try to download the "test/spring-petclinic" image from dockerhub, see that it doesn't exist and result in an ImagePullBackOff error. How are you able to deploy even manually with this config?

**Comment by Yashu5** [comment]
@kargakis : thanks for having look , may be I will try this in new version. :) deployment gets started fine for other apps except this one. Yes I had to modify dc to take test/spring-petclinic image. It pulls  image fine.

**Comment by Yashu5** [comment]
Hi @kargakis thanks for having a look , may be I will try this in new version. Deployment gets started fine for other apps except this. Yes I had to modify dc to take test/spring-petclinic image. It pull image fine and deploys application fine but only after clicking on deploy button on console. Thanks again :)
