### ISSUE TITLE
Clicking pod donut for one pod should take you straight to that pod

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7947]
Right now it takes you to a pods table with one row.

**Comment by jwforres** [comment]
what if there is only currently 1 pod but its in the process of scaling up, would you still want to go straight to the pod, or to the list of pods where the other pods are going to show up once created?

**Comment by spadgett** [comment]
Hm, can't decide. It might never scale, for instance, if you're out of quota.

**Comment by jwforres** [comment]
@rhamilto take a look at navigate.js toPodsForDeployment
