### ISSUE TITLE
Web console: Jolokia link display is broken

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#7948]
Working on fixing this in my extensions PR, but here's a screenshot:

![screen shot 2016-03-11 at 10 26 44 am](https://cloud.githubusercontent.com/assets/280512/13706656/fc41fb92-e773-11e5-9cad-fc08838cc088.png)

- Im assuming the icon / text should align with items above.
- Is "Connect" clear enough?  

@jwforres @sg00dwin

**Comment by benjaminapetersen** [comment]
@gashcrumb I believe you are the guy to ping about this, can we swap to "Connect to JVM" or something a bit more descriptive?

**Comment by gashcrumb** [comment]
Yeah, for sure!  'Connect to JMX' would probably be the most accurate, but 'Connect to JVM' would work as well.  And +1 for it lining up for sure.

Actually, maybe 'Open Java Console' would be better?  It'd avoid any acronyms then :-)

**Comment by jwforres** [comment]
@ajacobs21e thoughts?

**Comment by benjaminapetersen** [comment]
Yeah, agree. Saying 'JVM' even sees weird, but 'Java Console' I think I'd feel confident clicking that and knowing what I'm getting into.

**Comment by ajacobs21e** [comment]
@jwforres Whatever text is most accurate is best - either open java console or connect to java console. And yes to aligning it with the other icons.

**Comment by jwforres** [comment]
Fixed
