### ISSUE TITLE
hack/test-end-to-end.sh removes ALL containers

### ISSUE THREAD

**Issue by wyaeld** [openshift/origin#795]
Bit of a nasty surprise to find the test script stops & removes every single container on my system, including everything I had running related to other projects, various data containers, etc.

A reasonable person would expect that test scripts only tear down the artifacts they create.

**Comment by smarterclayton** [comment]
@bparees @jcantrill can one of you guys take this?  Agree this is bad behavior.

**Comment by bparees** [comment]
yeah, I can take it. But i'm not really sure how to track containers launched by k8s so we can clean them up in the event k8s barfs,  short of doing a docker ps compare before/after (which is subject to race conditions) 

Any simple idea you had in mind?

**Comment by smarterclayton** [comment]
They should all have a common prefix of k8s- I believe

**Comment by bparees** [comment]
Yeah that looks like it'll work, thanks.  PR for this: https://github.com/openshift/origin/pull/821

**Comment by bparees** [comment]
@wyaeld Should be fixed now, please take a look and close the issue if you're satisfied w/ the fix.  Thanks for pointing this out!

**Comment by wyaeld** [comment]
Looks fixed, thanks all.
