### ISSUE TITLE
oc status should warn about hpas on test deployments

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#7957]
Test deployments are always scaled down to zero pods so there is no reason to autoscale them. @deads2k please assign.

Depends on https://github.com/openshift/origin/pull/7799

**Comment by deads2k** [comment]
What's a test deployment?  Something in the upstream deployments?

**Comment by kargakis** [comment]
> What's a test deployment? Something in the upstream deployments?

Nope, a field in the spec recently added in DCs by @smarterclayton noting that we just want to test a deployment and once it finishes, scale down to zero. Since test dcs are always (except during a deployment) scaled down to zero, does it make sense to have autoscalers set up on them? HPAs currently work based on getting cpu utilization from the pods, but if there are no pods then does it make sense to have autoscaling? I would like to warn about it.

**Comment by smarterclayton** [comment]
Deployments can run for a very long time.  HPA supports equally, it
doesn't deserve a warning.

**Comment by kargakis** [comment]
Even if deployments can run for a very long time (got to be a huge one), we still can't scale them either manually or automatically due to the nature of the deployer (set desired count).

**Comment by smarterclayton** [comment]
Which is really just a limitation of the current deployer, not a
fundamental obstacle to the right solution.

**Comment by kargakis** [comment]
Agreed but until the deployer is fixed (plus implement proportional scaling which makes more sense than always scaling the latest during deployments), having an autoscaler on a test DC is essentially useless now. We can have the warning and remove it once we fix everything else.

**Comment by smarterclayton** [comment]
It's such a vanishingly small percentage of users affected I don't
think it's worth it.  Also, it's not a warning - it's a "this may not
actually work like you expect".  We don't warn for bugs.

Let's focus on fixing actual warnings in status first - there's only
so much space to show warnings.
