### ISSUE TITLE
Affixed "Follow" link no flush with right edge of log in Firefox

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7963]
It jumps to the left a bit when you scroll from the top of the page. This is not a problem in Chrome.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13712713/2d78f84a-e793-11e5-8509-2732d3af0869.png)

/cc @jwforres @benjaminapetersen

**Comment by benjaminapetersen** [comment]
Neat.  browser specific styles for the win!!! :grimacing: (erm, firefox?)

**Comment by jwforres** [comment]
lets try and fix this for 1.2 if its not too scary of a change

**Comment by benjaminapetersen** [comment]
Should be able to hit it.  There is a mozilla specific hack ~
```css
@-moz-document url-prefix() { 
  .selector {
     /* style... */
  }
}
```
Not a huge fan of browser hacks, but will prob do the trick.
@sg00dwin @rhamilto you guys know of other clever ways to target FF?

**Comment by sg00dwin** [comment]
I'm looking to see why it's position is different between the two.

**Comment by spadgett** [comment]
I'd like to understand why. Is it trying to accommodate the width of the scrollbar? We should check if it's OS X only.

**Comment by rhamilto** [comment]
> I'd like to understand why. Is it trying to accommodate the width of the scrollbar? We should check if it's OS X only.

:100:

**Comment by jwforres** [comment]
Linux firefox, different behavior than OS X

![20160318_110026_](https://cloud.githubusercontent.com/assets/1467629/13882052/223b6848-ecfa-11e5-832f-d5dc72171209.png)

**Comment by benjaminapetersen** [comment]
Oh good grief. Wasn't that kind of junk supposed to die with IE?!  :angry:

**Comment by benjaminapetersen** [comment]
So this is one of a few probs with the follow:
- [ ] Firefox jumps around
- [ ] Affix top is set with `follow-affix-top="390"`, but we add/remove content above the log area, which throws this off semi-frequently.  Prob needs to be programmatically set.
- [ ] Swapping affix target from window / `#scrollable-content` based on browser resize is jittery

Dunno if more bandaids is good or bad.  Poking around the options... :confused:

**Comment by benjaminapetersen** [comment]
Looking at the [boostrap affix plugin](https://github.com/twbs/bootstrap/blob/master/js/affix.js) and trying to decide if we would be better off dropping it so we can do the affix manually.  Is not a trivial amount of code, though...

**Comment by rhamilto** [comment]
Bootstrap 4 will drop the affix plugin in favor of HTML5 and polyfill.  See http://v4-alpha.getbootstrap.com/migration/#components
