### ISSUE TITLE
Use internal DNS for internal communications.

### ISSUE THREAD

**Issue by paralin** [openshift/origin#7972]
Currently the OpenShift config creation setup generates files like `openshift-registry.kubeconfig` with absolute IP addresses such as `https://10.0.62.64:8443` for the cluster server field. 

This might apply only to deploying on Kubernetes.

Would it not be better to generate something like `https://openshift.openshift-origin.svc.cluster.local:8443/` for this field? Seems more reliable.

**Comment by paralin** [comment]
@derekwaynecarr

**Comment by liggitt** [comment]
The two credentials generated for use inside pods (registry and router) are actually being replaced with service account credentials, so those files will go away after a deprecation period

**Comment by paralin** [comment]
@liggitt Nice, that seems better. However, is the internal communication still absolute IP based?

**Comment by liggitt** [comment]
it uses the service IP today, which is guaranteed reachable from inside the pod, but it will likely switch to dns names eventually

**Comment by paralin** [comment]
Is it still env variable driven? I'd like to make a deploy under Kube use kube best practices as much as possible (dns)
