### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by geoHeil** [openshift/origin#7977]
## Version

```
oc v1.1.3
kubernetes v1.2.0-origin
```
## Description

I try to execute: 

```
sudo docker run -d --name "origin" \
        --privileged --pid=host --net=host \
        -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw \
        -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes \
        openshift/origin
```

to run open shift origin in a docker container. 

The signal to start the container is sent to the docker daemon. However the container is not started as can be verified in syslog:

```
[ 1816.265477] aufs au_opts_verify:1597:docker[2010]: dirperm1 breaks the protection by the permission bits on the lower branch
```
## Steps To Reproduce
1. Execute the docker run command
2. Check syslog
## Current Result

The container is not started.
## Expected Result

The container should be started successfully.
## Additional Information

Other containers can be run successfully on this system.

A `docker info`returns:

```
docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 19
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-30-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: testCluster
```

and the os is ubuntu 15:10, latest updates are installed.

**Comment by mfojtik** [comment]
@geoHeil there is related issue opened for docker: https://github.com/docker/docker/issues/12701#issuecomment-96907107

it appears to have something to do with iptables. can you please check the docker logs and look for the iptables command?

**Comment by geoHeil** [comment]
Unfortunately `docker.logs` are empty. I could only find the error above in syslog. A `iptables -N DOCKER` results in:
`iptables: Chain already exists.`

**Comment by geoHeil** [comment]
Confirmed this issue on a fresh Ubuntu 14:04

**Comment by mrunalp** [comment]
This looks like a bug in the debian/ubuntu kernel. See https://github.com/docker/docker/issues/21081

**Comment by pweil-** [comment]
closing due to age
