### ISSUE TITLE
Mounting glusterfs with containerized openshift on docker 1.8 does not work

### ISSUE THREAD

**Issue by ibotty** [openshift/origin#7978]
## Version
oc v1.1.3-1-gc11b335-dirty
kubernetes v1.2.0-origin
(dirty because of some additional files)

## Description

Mounting glusterfs either directly via volumes or indirectly via persistent volume claims fails with (when directly using a volume):

    Error syncing pod, skipping: can't use volume plugins for registry-storage: no volume plugin matched

or (in case of pvc/pv):

    Error syncing pod, skipping: unsupported volume type

Mounting on the host works without any problems, `oc get endpoints glusterfs` returns the right gluster endpoints.

Logs of `origin-node` and `docker` don't show anything else.

Kind-of expected, I cannot mount the volume in the `origin-node` container on the node, and (because it's docker 1.8) a `chroot /rootfs mount -t glusterfs ...` does not make it visible on the host.

If I can supply any additional information, pls ask.

**Comment by sdodson** [comment]
@childsb For some reason I thought all these components only required the packages be installed on the host because they used nsenter?

**Comment by sdodson** [comment]
#8057 is tangentially related. I think if we're going to have to add drivers for all the filesystems we support then we should probably only do that in the node image and consider `openshift/origin` as a simple all-in-one no sdn, no filesystem drivers image. Otherwise we're going to bloat it and all downstream images considerably.  `openshift/node` is already pretty fat because it's got components for openvswitch sdn.

**Comment by smarterclayton** [comment]
Origin is definitely all-on-one.

**Comment by humblec** [comment]
I am not sure whether I got the exact context. however I would like to point that, if we are trying to mount a gluster volume directly inside the pod/container using FUSE mount, we need 'CAP_SYS_ADMIN' privilege inside the container.  Also we need glusterfs client ( glusterfs-fuse ..etc) packages installed  in the container. If we are using gluster plugin of kubernetes , it should be able to mount the volume inside the node/host then bindmount it as a volume inside the container.

**Comment by ibotty** [comment]
I am not trying to mount gluster inside a pod. I try to use gluster as a volume for a pod. So origin should mount gluster and provide it to the pod's containers.

**Comment by ibotty** [comment]
Well, it works now with docker image openshift/node:v1.1.6. It does not include gluster packages, so whatever it was, it's working now.
