### ISSUE TITLE
containers with status=exited are not cleanned

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/origin#7979]
## Version
[root@master origin]# oc version
oc v1.1.3-553-g19dbf2a
kubernetes v1.2.0-alpha.7-703-gbc4550d

## Description
on compute node, exited containers are expected to be deleted to reduce space waste. But OpenShift did not do the cleaning automatically.

## Steps To Reproduce

1. In Browser -> Builds, choose one build configuration
2. Click on Start build, or rebuild
3. Run `docker ps -af status=exited`

## Current Result
	-bash-4.2$ sudo docker ps -af status=exited
	CONTAINER ID        IMAGE                                                                                                    COMMAND                  CREATED             STATUS                     PORTS               NAMES
	a5ce42906362        openshift/origin-deployer:v1.1.3                                                                         "/usr/bin/openshift-d"   4 minutes ago       Exited (0) 4 minutes ago                       k8s_deployment.f07d2c74_wiki-15-deploy_test_dd361284-e956-11e5-b1ea-fa163eb71bce_616069c7
	2854c2754789        openshift/origin-pod:v1.1.3                                                                              "/pod"                   4 minutes ago       Exited (0) 4 minutes ago                       k8s_POD.4c98dca0_wiki-15-deploy_test_dd361284-e956-11e5-b1ea-fa163eb71bce_67f470ff
	fba28aff0f94        172.30.171.98:5000/test/wiki@sha256:9688560f5edd14885b1ca159051b841321474b1a10689e5c9ce412ac90426cb6   "container-entrypoint"   11 hours ago        Exited (0) 4 minutes ago                       k8s_wiki.423a79e6_wiki-14-ixsab_test_e38435b0-e8f4-11e5-b1ea-fa163eb71bce_e352d7d6
	c1d7fb396dee        openshift/origin-pod:v1.1.3                                                                              "/pod"                   11 hours ago        Exited (0) 4 minutes ago                       k8s_POD.4c0fdc4_wiki-14-ixsab_test_e38435b0-e8f4-11e5-b1ea-fa163eb71bce_1bc9d268
	1f15086f0610        openshift/origin-deployer:v1.1.3                                                                         "/usr/bin/openshift-d"   11 hours ago        Exited (0) 11 hours ago                        k8s_deployment.ec9d2c73_wiki-14-deploy_test_e02c3345-e8f4-11e5-b1ea-fa163eb71bce_f02dfe1d
	a4f72549e4c6        openshift/origin-pod:v1.1.3                                                                              "/pod"                   11 hours ago        Exited (0) 11 hours ago                        k8s_POD.4c98dca0_wiki-14-deploy_test_e02c3345-e8f4-11e5-b1ea-fa163eb71bce_67f4c670
	daa5be24a0b6        openshift/origin-sti-builder:v1.1.3                                                                      "/usr/bin/openshift-s"   11 hours ago        Exited (0) 11 hours ago                        k8s_sti-build.b4ae0f62_wiki-14-build_test_a9be8727-e8f4-11e5-b1ea-fa163eb71bce_84759caf
	11295feac12e        openshift/origin-pod:v1.1.3                                                                              "/pod"                   11 hours ago        Exited (0) 11 hours ago                        k8s_POD.4c98dca0_wiki-14-build_test_a9be8727-e8f4-11e5-b1ea-fa163eb71bce_a350f5d7
	40fbd5cbff95        172.30.171.98:5000/test/wiki@sha256:a33b89739d187ea38119ce8aa4cafaed1f46ce0231c8da787bef96ebe8e360f9   "container-entrypoint"   11 hours ago        Exited (0) 11 hours ago                        k8s_wiki.be847c0e_wiki-13-qxut7_test_26f99c23-e8f3-11e5-b1ea-fa163eb71bce_7b4d7089
	968ef8cb8464        openshift/origin-pod:v1.1.3                                                                              "/pod"                   11 hours ago        Exited (0) 11 hours ago                        k8s_POD.4c0fdc4_wiki-13-qxut7_test_26f99c23-e8f3-11e5-b1ea-fa163eb71bce_c4536572
	-bash-4.2$ 

## Expected Result
Empty output

**Comment by mfojtik** [comment]
@xionglingfeng have you tried to run `oadm prune builds` ? I dunno if OpenShift prune exited containers automatically. @kargakis do you know?

**Comment by xionglingfeng** [comment]
@mfojtik No it doesn't. It only deleted old builds, but not containers. I think it is a fundamental function to clean used containers automatically for production environment, because the compute node do have infinite disk space :-)
Also, old build images are stored in docker registry and not cleaned. This may be reasonable because it is a good feature to save old builds for rollback, but I also think it is better to have a function removing these images.

**Comment by kargakis** [comment]
`oadm prune` is for OpenShift resources. For cleaning up dead containers you most probably need image gc enabled in the kubelet: https://docs.openshift.org/latest/admin_guide/garbage_collection.html

**Comment by kargakis** [comment]
@xionglingfeng did you try the kubelet garbage collection?

**Comment by bparees** [comment]
closing per @kargakis request
