### ISSUE TITLE
Cannot fetch from a self-signed HTTPS git repository

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/origin#7982]
## Version
oc v1.1.3-553-g19dbf2a
kubernetes v1.2.0-alpha.7-703-gbc4550d

## Description
it is impossible to create a service (e.g. PHP 5.6) with a HTTPS-based self-signed git repository.

## Steps To Reproduce
1. Create a service, such as PHP 5.6
2. Use a HTTPS with self-signed certificate as git source

## Current Result
Build failed with

    F0314 04:14:47.738178 1 builder.go:204] Error: build error: fatal: unable to access 'https://example.com/test.git': Peer's Certificate issuer is not recognized. 

## Expected Result
Build processed with latest source code

**Comment by bparees** [comment]
You need to supply a .gitconfig secret which configures git to allow self-signed certs, please see this documentation:
https://docs.openshift.org/latest/dev_guide/builds.html#other-authentication

**Comment by xionglingfeng** [comment]
I followed that document and added certificate with its CA certificates to the secret, and added that secret to builder account. However, it still not work :-(
Anything I missing here?

**Comment by bparees** [comment]
You need to follow the instructions to include a gitconfig that disables ssl verification.  See this section:
`SSH Key Based Authentication requires a private SSH key. A .gitconfig file can also be attached.`

and the example starting w/ this text:
`Please note that SSL verification can be turned off, if sslVerify=false is set for the http section in your .gitconfig file:`

**Comment by xionglingfeng** [comment]
Can I add the certificate instead of completely disable SSL verification? I think it will be safer to add the required certificates rather than disable it.
Also, it seems adding .gitconfig is a pre-build setting. How to make it system wide?

**Comment by bparees** [comment]
if you're using a self-signed cert, there is nothing to verify it against, hence the need to disable ssl verification.

there is no way to set the .gitconfig at a system-wide level today, unfortunately.  it must be done for each buildconfig.

**Comment by xionglingfeng** [comment]
@bparees What about the certificate signed by a private CA? Can we add trust of the private CA?

**Comment by bparees** [comment]
I don't believe we have a way do to that because the certs are part of the openshift/origin-sti-builder (or openshift/origin-docker-builder) image which is performing the git clone, but adding @csrwng and @liggitt in case they are aware of a way to inject additional certs for git to trust.  It does seem like a problematic limitation.

**Comment by liggitt** [comment]
if you can provide a custom .gitconfig file, I think you can specify a CA file per repo in that

see http://stackoverflow.com/questions/23807313/adding-self-signed-ssl-certificate-without-disabling-authority-signed-ones/23807432#23807432

**Comment by liggitt** [comment]
@csrwng if you include a .gitconfig and ca bundle in a secret, will both files be laid down together in order to do the clone?

**Comment by csrwng** [comment]
@liggitt yes, and actually if you have a ca bundle in your secret, we should use it.

**Comment by csrwng** [comment]
@bparees just adding the ca.crt to the secret should have worked. If it's not working, then we need to find out why.

**Comment by csrwng** [comment]
Actually @xionglingfeng I don't think you mentioned that you referenced the secret from your build config. You also need to do that: https://docs.openshift.org/latest/dev_guide/builds.html#using-private-repositories-for-builds (step 3)

**Comment by xionglingfeng** [comment]
@csrwng  @liggitt I think I already followed the document. Here's the command I run:

    [root@master origin]# oc secret new s2i-certs ca.crt=ca.crt 
    secret/s2i-certs
    [root@master origin]# oc secrets add serviceaccount/builder secrets/s2i-certs
    [root@master origin]# 

And I changed the build configuration YAML file, added

    sourceSecret:
          name: "s2i-certs"

under `spec/source/git`.

It still not work, saying

    W0325 03:08:11.017307       1 builder.go:55] Master version "v1.1.3-553-g19dbf2a" does not match Builder image version "v1.1.3"
    I0325 03:08:11.043469       1 source.go:197] Downloading "https://xxx/xxx/xxx.git" ...
    F0325 03:08:11.756850       1 builder.go:204] Error: build error: fatal: unable to access 'https://xxx/xxx/xxx/': Peer's Certificate issuer is not recognized.
    End of log 

Based on @liggitt 's comments, it seems a .gitconfig file is required to set `sslCAInfo`? But there is the ca.crt file located?

**Comment by bparees** [comment]
the ca.crt is supposed to be automatically mounted into the container and your .gitconfig is supposed to be automatically generated/updated to reference it.

@xionglingfeng can you provide level 5 debug logs for your build:
https://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs

also please provide the output of "oc get bc your_buildconfig_name -o json"

**Comment by liggitt** [comment]
The ca is auto mounted in as part of the service account secret. It doesn't get added to git config automatically. You have to reference the service account secret as your build secret for that to happen

**Comment by bparees** [comment]
@liggitt that's what i meant...  sourceSecret is being specified in this case.

**Comment by bparees** [comment]
closing pending logs/output requested in my previous comment.  will reopen if provided.
