### ISSUE TITLE
Proposed: registry-cluster-admin role

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#7987]
With the registry-admin and registry-viewer roles I think we also need a "registry cluster admin" role to expose an appropriate set of permission to manage a registry at the cluster level. Otherwise they're left with cluster-admin which exposes a lot of unnecessary resources, or a custom role which is difficult to create.

cc @deads2k

**Comment by deads2k** [comment]
What would you like the `registry-cluster-admin` to do?  It's true that a `cluster-admin` has a lot of power, but it seems like you'd want about the same power for your `registry-cluster-admin` right?

**Comment by aweiteka** [comment]
Clearly the registry admin needs to do a lot of cluster-level management: the registry (pods, including the nodes it runs on), users, policies, images, etc.

What they *don't* need to do:

- builds
- SDN(?)
- deployments and management of resources that aren't in the project that the registry users ("default").

Would it be better to do some work with project scoping? For example, limit certain actions to the default project, disable openshift-infra project, etc? I'm not sure what that might look like but I see there are some roleBinding references to specific projects like openshift-infra.

**Comment by aweiteka** [comment]
There isn't a clear use case defined. Closing.
