### ISSUE TITLE
Different versions of Go in Vagrant vs. host system

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#799]
This is not really an issue but more like a workaround for those of you who ran OS that already got Go 1.4  OR you run system other than Fedora and you suffer from the compilation time inside the VirtualBox machines (and you don't have 8 free CPU cores to assign to VirtualBox). So here is what I did.

1) I know that ./hack/build-go.sh on my host system (Arch/Go1.4) takes ~5seconds but in Vagrant (2 CPU cores, F20) it takes ~40s.

So the solution is to build the OpenShift on my host machine, where the Go build can take more CPU cores and be fast but also provide the Go 1.3 binaries that I can run in Fedora VM. So let's use Docker:

Dockerfile:
```
FROM fedora:20
RUN yum install -y curl git golang make which && yum clean all
VOLUME /go
ENV GOPATH /go
ENV PATH $PATH:$GOPATH/bin
ADD build.sh /tmp/build.sh
ENTRYPOINT ["/tmp/build.sh"]
```

build.sh:
```
#!/bin/bash -ex
echo "#!/bin/bash -ex
./hack/build-go.sh && chmod -R go+rw {Godeps/_workspace/pkg,_output}
" > /tmp/build_run.sh && chmod +x /tmp/build_run.sh
cd ${GOPATH}/src/${1} && exec /tmp/build_run.sh
```

Then: `docker build -t openshift-builder .`

Now I can run this command on my host machine to build OpenShift:

`docker run --rm -v $GOPATH:/go openshift-builder github.com/openshift/origin`

This will execute the build inside the F20 container so the binaries/.a files are compatible with F20 system libs and Go 1.3, so I can just run them straight away inside my Vagrant box.

**Comment by mfojtik** [comment]
To prove this improves the compilation time, here are some benchmarks.

On my host system:
```
$ make clean
$ time docker run --rm -v $GOPATH:/go openshift-builder github.com/openshift/origin
real	0m11.740s
user	0m0.007s
sys	0m0.013s
$ time docker run --rm -v $GOPATH:/go openshift-builder github.com/openshift/origin
real	0m2.762s
user	0m0.023s
sys	0m0.000s
```

Inside Vagrant:
```
$ make clean
$ time ./hack/build-go.sh
real	0m40.621s
user	0m24.075s
sys	0m23.789s
$ time ./hack/build-go.sh
real	0m21.111s
user	0m1.555s
sys	0m14.007s

```

**Comment by smarterclayton** [comment]
Why not add this functionality to the release image?
