### ISSUE TITLE
Separate Compile and Run Steps for Test-Go

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#7990]
Piping all of our test output through the jUnit tool into XML has uncovered a case that jUnit was not meant to handle: compilation errors.

jUnit XML schema does not have a way to show that a test or suite failed to compile. jUnit XML schema doesn't even have a way to show that a suite failed - only tests can have a failure field. Creating a synthetic test for compilation and marking it as failed seems very hack-y to me. A simpler and more principled approach would be to split the compilation and run steps in `hack/test-go.sh`. Currently we just invoke `go test ${flags} ${package}`, which compiles and runs the test. Instead, we could invoke:

```
go test -c ${package}
$[package}.test ${prefixed-flags}
```

We'd need to prefix all flags to `go test` with `test.`, but other than that this should be simple, as it is actually what `go test` is doing internally anyway. This would allow us to catch and yell about compilation errors as necessary.

We already make this distinction with all other tests (integration, cmd, _etc_), anyway.

@deads2k @smarterclayton @bparees  thoughts?

**Comment by stevekuznetsov** [comment]
One downside of this is that `go test -c` can only be called for one package, so we'd need to handle `./...` expansion ourselves again.

**Comment by smarterclayton** [comment]
If you're testing normally, go test is probably just as good as hack/test-go.sh.  If you want junit, doing something special to catch compilation is fine.  We already have to run individual packages for coverage, so junit running individual compiles is probably ok.

**Comment by smarterclayton** [comment]
Problem is, it's going to be really really slow.

**Comment by stevekuznetsov** [comment]
Why would it be slower than the normal route? I was under the impression that `go test` does the same two steps?

**Comment by smarterclayton** [comment]
It would be slower because you can't pass multiple packages at the same
time, so it can't necessarily build multiple packages from the same half
loaded data - instead, it has to reload all of them each time the process
is run.  So you pay the cost to bring most packages into memory each time.

**Comment by stevekuznetsov** [comment]
Unimportant.
