### ISSUE TITLE
web console api discovery proposal

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#7998]
This is an early proposal for doing API discovery in the web console.  The goal is to move away from a dynamically generated config.js

1. Get k8s api versions - request /api
  1. Pre-fetch preferred console version (v1) - request /api/v1 - if this version doesn't exist, fallback to fetching the server's preferred version?
  2. Other versions:
    1. Will be fetched on demand, e.g. creating things in a template that references another version, or should we just let it try and fail if that resource cant be created using that version?
    2. OR will be fetched in the background but won't block initial load
2. Get os api versions - request /oapi
  1. Pre-fetch preferred console version (v1) - request /oapi/v1 - if this version doesn't exist, fallback to fetching the server's preferred version?
  2. Other versions
    1. Will be fetched on demand, e.g. creating things in a template that references another version, or should we just let it try and fail if that resource cant be created using that version?
    2. OR will be fetched in the background but won't block initial load
3. Get groups - request /apis - should not block loading initial resources UNTIL os and k8s resources are moved underneath groups and the legacy endpoints are dropped
  1. Pre-fetch what the api returns as the preferred version for each group
  2. Other versions
    1. Will be fetched on demand
    2. OR will be fetched in the background

Additional notes:

* API details that have been discovered will be cached based on the version info returned from /version and /oversion (new api endpoint being proposed)
  * Cache will be busted if the version doesn't match, we could independently bust the k8s part of the cache from the os cache if we want to
  * Cache will be in localStorage
* 1.1, 2.1, and 3.1 must complete (or a cached version must exist) before we can load other content in the UI
  * we could just wait for the missing type to appear and then send the initiated data request
* If a template tries to create something in a group/version/resource that we do not know about, it is still possible that it is valid
  * This is because group/version/resources can be added by configuration changes, so the cache on version is not necessarily sufficient
  * If we see one we don't know we can attempt the request anyway, if it succeeds, update the cache to include it
  * OR if the cached version exists, we could still run the api discovery in the background to update the cache, this just wouldn't block initial page load

**Comment by jwforres** [comment]
cc @liggitt @deads2k @spadgett   poke holes in this

**Comment by deads2k** [comment]
> Pre-fetch what the api returns as the preferred version for each group

Why do you care about these until you need to use them?  It seems like there could be several API groups you don't care about ever.  For instance, if you don't deal with `batch`, why retrieve `batch/v1`?

**Comment by deads2k** [comment]
> API details that have been discovered will be cached based on the version info returned from /version and /oversion

These sort-of work, but if we start exposing the ability to enable/disable specific resources (the feature already exists upstream), then this won't work well.  For instance, what if they decide to expose `jobs.v1.batch` at a later time.  How bad is it to simply refresh the cache very X minutes or in background every re-login or something?

**Comment by jwforres** [comment]
The alternative is "maintain a list of groups I care about" in the console

**Comment by deads2k** [comment]
> The alternative is "maintain a list of groups I care about" in the console

That seems pretty reasonable for the `GET` cases where you're deciding what information to display.  That way you'd know whether you were going to show `jobs.batch` or whatever new thing we make next release.

**Comment by jwforres** [comment]
Login won't work, expect some environments to have very long access token
life.  Every X minutes seems like needless churn against the server.  I
thought I put another option in there somewhere in the notes that said the
alternative is to always refresh it in the background on a page load
(navigating around the UI does not cause page load).

**Comment by deads2k** [comment]
> I
> thought I put another option in there somewhere in the notes that said the
> alternative is to always refresh it in the background on a page load

You had on a section that specifically dealt with creating resources.  Since you also have read-only cases for deciding whether to show categories on the left, that's insufficient for a "late enablement" case.

**Comment by jwforres** [comment]
On Mon, Mar 14, 2016 at 1:33 PM, David Eads <notifications@github.com>
wrote:

> I
> thought I put another option in there somewhere in the notes that said the
> alternative is to always refresh it in the background on a page load
>
> You had on a section that specifically dealt with creating resources.
> Since you also have read-only cases for deciding whether to show categories
> on the left, that's insufficient for a "late enablement" case.
>
I don't think we have this problem today.  We don't "decide" whether to
show things on the left.

Now down the road, maybe, if say we wanted to allow to you point a given
console client against multiple servers

cc @smarterclayton

**Comment by jwforres** [comment]
discussed with @spadgett and @deads2k and based on the introduction of the Other Resources page, we will not want a long term version based cache because we will want to know all the available resources including the third party ones that show up dynamically.  The new proposal is simplified down to just doing api discovery on page load and caching until the next page load (browser refresh).   So navigating around the console will use the cached info.

@liggitt and @smarterclayton speak up soon if you disagree, otherwise i'm going to start implementing

**Comment by smarterclayton** [comment]
SGTM

On Tue, Mar 29, 2016 at 3:20 PM, Jessica Forrester <notifications@github.com

**Comment by spadgett** [comment]
Implemented by https://github.com/jwforres/origin/pull/38
