### ISSUE TITLE
Extended tests: consider running with --latest-images

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#8002]
To simplify debugging/developing extended tests I suggest to add ability to run OpenShift with `--latest-images` option. Possible ways could be the following:

```console
$ ./test/extended/core.sh --with-latest-images
```
or
```console
$ export USE_LATEST_IMAGES=yes
$ ./test/extended/core.sh
```

##### Version
openshift v1.1.3-649-ga81b41f

##### Steps To Reproduce
`./test/extended/core.sh`

##### Current Result
OpenShift is running without `--latest-images` option.

##### Expected Result
OpenShift is running with `--latest-images` option.

**Comment by stevekuznetsov** [comment]
@bparees was saying stale images could cause lots of weirdness - should this be the default setting?

**Comment by bparees** [comment]
@stevekuznetsov ironically, --latest-images is *more* likely to result in you running w/ stale images.

--latest-images says "just use whatever i have locally" whereas w/o that, openshift will attempt to pull an image that matches the commit level of your binary.

so it's quite easy to end up w/ a local image that's actually older than the commit level of your binary, and in that case, --latest-images gets you stale content.

so no i don't think this should be the default.

also when we're running tests, we want to ensure the images we're running them with are aligned to the code level we're trying to test, which again rules out using --latest-images unless you know what you're doing.

**Comment by stevekuznetsov** [comment]
Ah, that's definitely a counter-intuitive name, but perhaps its too late to change it.

@php-coder what are the use-cases for this setting, taking @bparees feedback into account? Running regression or compatibility tests?

**Comment by liggitt** [comment]
It runs using the images tagged "latest" without doing a force pull. The counterintuition runs deep into docker with that.

**Comment by php-coder** [comment]
>@php-coder what are the use-cases for this setting, taking @bparees feedback into account?

Use case: I'm writing test for MongoDB and I found a bug. I'm fixing MongoDB image and I need to run test again and prove that I really fixed this bug.

**Comment by stevekuznetsov** [comment]
I see. Flag coming your way. It won't apply to `test-cmd` at the moment as that test does not use the same startup framework.

**Comment by bparees** [comment]
--latest-images has no impact on which mongodb image you use, it only affects infrastructure images.

**Comment by php-coder** [comment]
> `--latest-images` has no impact on which mongodb image you use, it only affects infrastructure images.

Ah, yes... But anyway it could be useful for testing builder images, right?

**Comment by bparees** [comment]
> Ah, yes... But anyway it could be useful for testing builder images, right?

yes
