### ISSUE TITLE
Show all templates a user can list (in the web UI)

### ISSUE THREAD

**Issue by vbehar** [openshift/origin#8014]
this is the second issue from #3563 : in the Web UI, when a user wants to create a new application, he should see all the templates from all the projects he has access to - instead of just the templates from the shared `openshift` project and the current project.

Our use case is to allow people to share templates between them, without the need to give them write access to the shared `openshift` project. We would like devs to just create a new project (or use an existing one), create some templates, and manage themselves who can access them.

In the Web UI, when listing the templates available, it would be nice to see them in the following order:
- the templates from the current project
- the official templates from the `openshift` project
- all the other templates (from the other projects)

**Comment by liggitt** [comment]
There's too much fan out to fetch from all projects (it's one API request per project). It might be good to have a way to specify a particular one.

**Comment by jwforres** [comment]
cc @spadgett @jhadvig

**Comment by jhadvig** [comment]
I can imagine there to be a selectbox with all the available users projects, from which he can pick and only those template will be listed. On the other hand dont know how it will fit into our current design of the 'create' page

**Comment by vbehar** [comment]
if it's too much requests to do, we could indeed have a specific "shared" project (not the `openshift` one), to which we would give everyone write access, so that they can share their templates.

But I think it would be better to really list the templates from all available projects. I think this page is not used so often, so it's not a real issue if it does a lot of requests. And we could load the templates asynchronously, just stating with the ones from the current project and from the `openshift` project, and perhaps loading the others on-demand ?

**Comment by jorgemoralespou** [comment]
The problem would be if you have templates in multiple projects, which one is shown, and which would be the instantiation order?
Right now, when new-app it looks for a template in your project and then in openshift namespace. What would happen if the same template is also in project A and project B. Which would need to be instantiated?

**Comment by vbehar** [comment]
maybe we could use the namespace as a prefix, like `project/template` ?
and if there is no prefix, keep the current behaviour.

**Comment by jhadvig** [comment]
@jorgemoralespou good point. @vbehar I would rather avoid displaying all the templates, could get messy, even with prefix.
We need some mechanism to fetch only templates from a single project, similar to to one I've suggested in my previous comment. 
Anyway we will (most probably) incorporate this into our new design that @ajacobs21e is working on ATM.

**Comment by liggitt** [comment]
> I think this page is not used so often, so it's not a real issue if it does a lot of requests

Unbounded fan out is always an issue. I could see an option to browse from another project (didn't we do something similar with image stream selection when editing a build config?)

**Comment by jhadvig** [comment]
@liggitt yep, that's what I'm kinda referring to

**Comment by vbehar** [comment]
@bparees please help me here ;-) in #3563 you wrote

> web console should present the user with all templates in all projects they can view, not just the current project and openshift project.

**Comment by bparees** [comment]
@vbehar @jhadvig I liked the suggestion of a drop-down that lets you select from any of the projects you can view, and then show you the templates from that project (and the openshift project).  That seems like the simplest win here.

Though I think @liggitt is going to tell me that even figuring out which projects you can view is hard.

**Comment by vbehar** [comment]
ok, we could do that in 2 steps: first select the project, then the template.

isn't "figuring out which projects you can view" the same as what is done for "oc get projects" ?

**Comment by liggitt** [comment]
UI already has the list of projects you can view (we show it in the drop down)

**Comment by ajacobs21e** [comment]
> (didn't we do something similar with image stream selection when editing a build config?)
@liggitt @jhadvig Can one of you show me what this looks like please?

**Comment by jorgemoralespou** [comment]
@liggitt Even you can view a project,  acces to view templates resource can not be restricted as well? I find a lot of checks needed for the value. 
What would be the real use case? I haven't been anybody asking this before.

**Comment by jorgemoralespou** [comment]
Having read the originating issue, actually kind of make sense. I would have a way to reference which project I want to look for templates although from a usability perspective is not nice.

**Comment by liggitt** [comment]
> Even you can view a project, acces to view templates resource can not be restricted as well?

Sure, we'd have to handle that as well... select a project (from the list available to you), and if we get rejected listing templates in that project, tell you

**Comment by jhadvig** [comment]
@ajacobs21e 
![image4144](https://cloud.githubusercontent.com/assets/1668218/13824400/25770bea-ebae-11e5-8a49-aee79161e68e.png)

**Comment by ajacobs21e** [comment]
Thanks @jhadvig !

**Comment by jwforres** [comment]
Moving this to trello https://trello.com/c/NFhQawHD
