### ISSUE TITLE
oc status should handle multiple bcs pointing to the same tag

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8022]
Assumes there is only one bc per tag currently. @deads2k @stevekuznetsov @bparees @gabemontero

**Comment by gabemontero** [comment]
Will tackle after https://github.com/openshift/origin/pull/8017 merges, as this issue is a follow up for a new method added with that PR.

**Comment by kargakis** [comment]
Not really new, I just made it public and moved it to a more common place. This isn't a high priority but it would be good to have it eventually.
