### ISSUE TITLE
Misplaced log output "Generating node credentials ..."

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8023]
```
I0315 02:52:03.578404   28678 start_master.go:524] Controllers starting (*)
Generating node credentials ...
I0315 02:52:04.917824   28678 nodecontroller.go:141] Sending events to api server.
```

Should not be writing that middle line to server output.

**Comment by smarterclayton** [comment]
Same problem for 

```
$ sudo openshift start --master=10.1.2.2
Generated new key pair as openshift.local.config/master/serviceaccounts.public.key and openshift.local.config/master/serviceaccounts.private.key
```

These should probably be suppressed or put into glog.

**Comment by deads2k** [comment]
@stevekuznetsov that's probably coming from a delegated command that we DO want that output for.  You should be able to capture the output and direct it differently for the delegation cases.

**Comment by deads2k** [comment]
> @stevekuznetsov that's probably coming from a delegated command that we DO want that output for. You should be able to capture the output and direct it differently for the delegation cases.

Or more cleanly, create a wrapper on the out stream.
