### ISSUE TITLE
Extended Core.ServiceAccounts should ensure a single API token exists - failure

### ISSUE THREAD

**Issue by bparees** [openshift/origin#8029]
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/service_accounts.go:152
Expected error:
    <*errors.errorString | 0xc208b83290>: {
        s: "default service account has too many secret references: []api.ObjectReference{api.ObjectReference{Kind:\"\", Namespace:\"\", Name:\"default-token-urnz3\", UID:\"\", APIVersion:\"\", ResourceVersion:\"\", FieldPath:\"\"}, api.ObjectReference{Kind:\"\", Namespace:\"\", Name:\"default-dockercfg-op5ys\", UID:\"\", APIVersion:\"\", ResourceVersion:\"\", FieldPath:\"\"}}",
    }
    default service account has too many secret references: []api.ObjectReference{api.ObjectReference{Kind:"", Namespace:"", Name:"default-token-urnz3", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}, api.ObjectReference{Kind:"", Namespace:"", Name:"default-dockercfg-op5ys", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}}
not to have occurred

**Comment by bparees** [comment]
@deads2k can we move this test to the jail bucket?  it's one of the last ones preventing us from getting a clean extended test run.

**Comment by liggitt** [comment]
no, fixed in the rebase, hopefully landing tomorrow

**Comment by bparees** [comment]
even better.
