### ISSUE TITLE
a import error in openshift-ansible when use ansible-playbook

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#8037]
Version：The latest version(may be more than tree)
Environment：1master+N nodes[1] / 3master+3etcd+3node+1lb[2]
also i have build a DNS server.

At the old releases,when i run[3],that will begin to install automatically and will be ok.but the new which have some bugs in the latest version(i try 2~3 releases,may be more than it)
![bug-1](https://cloud.githubusercontent.com/assets/12937669/13803486/ed58209c-eb7f-11e5-989c-b245e65a7f8b.png)
when i running,i found the install can't be use for the new releases.
I have to run "ansible all -a "yum -y install origin*"" that it will be ok for the environment.
![bug-2](https://cloud.githubusercontent.com/assets/12937669/13803511/26526f88-eb80-11e5-8d27-32e990d3fbc6.png)
As usual,i tested several times to install and uninstall,prompt unload error ,but the origin is normal unloading when i run [4] (in Single and Multiple).
![bug-4](https://cloud.githubusercontent.com/assets/12937669/13803603/d7f3d24a-eb80-11e5-8a71-13515f62c895.png)
the last,when i remove the rpm,i try to install again,it is error for run [3]
![bug-6](https://cloud.githubusercontent.com/assets/12937669/13803672/83e53a44-eb81-11e5-9d6c-96cbb90833bf.png)
that i must run  `"ansible nodes -a "yum -y install origin* etcd"`,and run `"ansible lb -a "yum -y install haproxy"` ,that the openshift-ansible install can be ok.
If they don't,alway error to build the openshift origin.
![bug-3](https://cloud.githubusercontent.com/assets/12937669/13803726/e496963a-eb81-11e5-93be-4e84be52a8f2.jpg)
Is this bug?

[1] https://docs.openshift.org/latest/install_config/install/advanced_install.html#single-master
[2] https://docs.openshift.org/latest/install_config/install/advanced_install.html#multiple-masters
[3] ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
[4] ansible-playbook ~/openshift-ansible/playbooks/adhoc/uninstall.yml

**Comment by wenskys** [comment]
i found that is a bug for “ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml” in the new release yesterday，that the multiple can't be install,but today it isn't repeat,May be repaired.
![bug-6](https://cloud.githubusercontent.com/assets/12937669/13803848/ff67910c-eb82-11e5-8aa1-31393e659c92.png)

**Comment by sdodson** [comment]
@wenskys I believe you may be hitting a bug with yum and ansible which leads to it silently ignoring our requests to install packages. We've researched it a bit in https://github.com/openshift/openshift-ansible/issues/1138 but can you run `yum upgrade yum\*` on all your hosts before trying again?

Can you run `journalctl -lu origin-master-api.service` on the hosts where the master api has failed to start and post anything that's indicating problems?

**Comment by wenskys** [comment]
@sdodson thanks for your help,I will try again and runing `yum upgrade yum\*`.
The master api has enable to start,but today it isn't repeat,i will try again too.

**Comment by wenskys** [comment]
@sdodson yes,you are right.this is a bug for yum,now it is working.thanks a lot.
The master api has enable to start,it isn't repeat.
May be `yum upgrade yum\*` can be run in openshift-ansible or in openshift-docs?

**Comment by sdodson** [comment]
Thanks, yeah we're considering that.

**Comment by sdodson** [comment]
If you don't mind, close the issue unless you're still having problems.

**Comment by wenskys** [comment]
ok,Thanks again
