### ISSUE TITLE
confirmation before project deletion

### ISSUE THREAD

**Issue by vbehar** [openshift/origin#8038]
Hi,

how do you feel about confirmation before deleting a project ?

It would be cool to be able to "protect" a project (or any other resource, btw), so that deletion requires a confirmation (at least from the `oc` CLI). Something like what is done by github for protected branches. It could use a specific label that would be check prior to deletion.

what do you think ?

**Comment by kargakis** [comment]
Related issue: https://github.com/openshift/origin/issues/4141

**Comment by vbehar** [comment]
yes thanks, the upstream PR is https://github.com/kubernetes/kubernetes/pull/17740
