### ISSUE TITLE
TestTryOrdering fail

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8039]
```
--- FAIL: TestTryOrdering (0.00s)
	rate_limited_queue_test.go:179: order was wrong: [first third second]
FAIL
coverage: 57.9% of statements
FAIL	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/node	0.338s
```

**Comment by soltysh** [comment]
Shouldn't that be upstream, since it's k8s test? Or are you suspecting origin has some influence on this?

**Comment by kargakis** [comment]
Saw this prior to the rebase and there has been a change to the test ever since so I am going to close this issue until we see it again.

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13102/consoleFull
Back again:/

**Comment by soltysh** [comment]
And here: https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5380/consoleFull

**Comment by pweil-** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5472/consoleFull#187129622756bf4006e4b05b79524e5923

**Comment by soltysh** [comment]
It's being addressed in https://github.com/kubernetes/kubernetes/pull/24382

**Comment by kargakis** [comment]
@mfojtik the rebase fixes this, fyi

**Comment by mfojtik** [comment]
@kargakis @soltysh closing (rebase should fix this). Reopen if this happens again.
