### ISSUE TITLE
Env var editor should allow re-ordering of env vars

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#8048]
Today you can only remove and append

**Comment by spadgett** [comment]
@rhamilto and @benjaminapetersen have already started looking at this.

**Comment by benjaminapetersen** [comment]
Have a [branch here](https://github.com/rhamilto/origin-web-console/tree/angular-key-value-editor) soon to be a PR.

**Comment by rhamilto** [comment]
Partially completed by https://github.com/openshift/origin-web-console/commit/8343c78f00cd2c80e8ce5b217216376051de959f.  @benjaminapetersen is working on the remaining instance of BC edit.

**Comment by spadgett** [comment]
This is now fixed.
