### ISSUE TITLE
Image stream tag table cut off at narrow widths

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8052]
On page load:

![screen shot 2016-03-16 at 11 57 47 am](https://cloud.githubusercontent.com/assets/1167259/13819000/652bee9e-eb6e-11e5-8d2e-a17a06014853.png)

After scrolling right:

![screen shot 2016-03-16 at 11 58 41 am](https://cloud.githubusercontent.com/assets/1167259/13819010/746cea20-eb6e-11e5-9024-026cebe77fb1.png)

@jwforres

**Comment by jwforres** [comment]
Does it just need break-word?

@rhamilto or @sg00dwin one of you have time to look at it?

**Comment by rhamilto** [comment]
@jwforres, @sg00dwin, I'll take a look.
