### ISSUE TITLE
oadm registry should recreate the dc if the service exists

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8055]
Should check if the ports and the selector match and let me have that brand new dc created. Works for the other way around (creates justs a new service in the presence of a dc).

@miminar @soltysh @smarterclayton

**Comment by miminar** [comment]
:+1:

**Comment by smarterclayton** [comment]
oadm registry -o yaml | oc apply -f -

**Comment by kargakis** [comment]
> oadm registry -o yaml | oc apply -f -

Good enough for now.
