### ISSUE TITLE
output of docker push while pushing via our builder

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8058]
While playing around with our registry and S3, it occured to me that I have no info of what is happening when the builder is trying to push to the integrated registry. Especially with external storage it can take some time to push.
```
I0316 19:05:13.926016       1 sti.go:254] Pushing 172.30.77.73:5000/testtest/origin-ruby-sample:latest image ...
F0316 19:07:13.938493       1 builder.go:204] Error: build error: Failed to push image. Response from registry is: Put http://172.30.77.73:5000/v1/repositories/testtest/origin-ruby-sample/: dial tcp 172.30.77.73:5000: i/o timeout
```
Nevermind about the error, I had recreated the registry service.

It would be more intuitive to show the output from docker.

cc: @bparees @mfojtik

**Comment by bparees** [comment]
https://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs



Available log levels for Source builds are as follows:
Level 0 	
Produces output from containers running the assemble script and all encountered errors. This is the default.
Level 1 	
Produces basic information about the executed process.
Level 2 	
Produces very detailed information about the executed process.
Level 3 	
Produces very detailed information about the executed process, and a listing of the archive contents.
Level 4 	
Currently produces the same information as level 3.
Level 5 	
**Produces everything mentioned on previous levels and additionally provides docker push messages.**

**Comment by kargakis** [comment]
I see. Since this an env var, I would like to have it defaulting to 5 for all of my builds w/o the need to specify it for each bc. Is that possible?

**Comment by bparees** [comment]
1) if you launch openshift w/ level 5 logging, builds will pick up that log level by default.
2) https://docs.openshift.org/latest/admin_guide/build_defaults_overrides.html#setting-build-defaults

**Comment by kargakis** [comment]
cool, thanks!
