### ISSUE TITLE
Fix slow etcd unit tests

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#8063]
Upstream switch to TLS-enabled etcd in unit tests slows down some packages enormously

github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/storage/etcd    45.833s coverage: 70.2% of statements

github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/generic/etcd   28.310s coverage: 57.5% of statements

Unit test timeout was lengthened from 60s to 120s in the rebase (https://github.com/openshift/origin/pull/7975) to accomodate this

Probably need to switch these back to http (see https://github.com/kubernetes/kubernetes/pull/22919) and be more targeted with TLS-enabled unit testing

**Comment by mfojtik** [comment]
@liggitt is this still an issue? we pickup other rebase and we are close to etcd3.

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/22919
