### ISSUE TITLE
Better error message when JavaScript is disabled

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#8076]
The OpenShift Web Console requires JavaScript to function. If JavaScript is disabled, a message appears that states simply:

![screenshot from 2016-03-16 15-44-17](https://cloud.githubusercontent.com/assets/52710/13831056/16a2fde2-eb8e-11e5-89e1-7e4ca19b803b.png)

However, it does not explain how to do this, why it is needed, or provide alternate options (i.e. just using the command-line interface instead.)  Considering that are users are most likely developers, and that the default behaviour for most browsers is to enable JavaScript, the existing screen is probably sufficient, so I think this a fairly minor issue (maybe even a non-issue.)

Personally, I think using text like the following might be nice:

> The OpenShift web console requires JavaScript to provide a rich interactive experience.  Please [enable JavaScript](http://enable-javascript.com/) to continue.  If you do not wish to enable JavaScript or are unable to do so, you may use the [Command-Line Tools](https://docs.openshift.org/latest/cli_reference/get_started_cli.html) to manage your projects and applications instead.

I don't know how good http://enable-javascript.com is, but one of the authors is Google's Paul Irish, so it seems legit to me.

cc @jwforres

**Comment by jwforres** [comment]
I wouldn't add the CLI link even if it was just a doc link because it would be hard coded in index.HTML and have to be modified for every release and we claim support for fully customizable doc links now.

**Comment by jawnsy** [comment]
Chrome Beta (50.0.2661.37) on Linux:

![screenshot from 2016-03-22 15-27-17](https://cloud.githubusercontent.com/assets/52710/13969981/2ada1976-f043-11e5-87ad-558f65734222.png)

Firefox (44.0.2) on Linux:

![screenshot from 2016-03-22 15-29-11](https://cloud.githubusercontent.com/assets/52710/13969994/39f7d038-f043-11e5-97b7-3a0d40023b20.png)
