### ISSUE TITLE
1.1.4 Installation broken

### ISSUE THREAD

**Issue by sureddy** [openshift/origin#8077]
Installation of  Openshift Origin 1.1.4 Installation on CentOS 7 is failing consistently with the following error messages. 
 
<pre>
TASK: [openshift_node | Start and enable node] ********************************
failed: [xx.x.xxx.120] => {"failed": true}
msg: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.

failed: [xx.x.xxx.121] => {"failed": true}
msg: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.

failed: [xx.x.xxx.123] => {"failed": true}
msg: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.

failed: [xx.x.xxx.122] => {"failed": true}
msg: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.

FATAL: all hosts have already failed -- aborting

</pre>
##### version
<pre>[centos@jibo-3 ~]$ oc version
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75

[centos@jibo-3 ~]$ openshift version
openshift v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75
etcd 2.2.5
</pre>

##### Steps To Reproduce
1. setup your hosts files ( ansible inventory file) 
2. ansible-playbook -i hosts openshift-ansible/playbooks/byo/config.yml

#### systemctl log messages
<pre>
[centos@jibo-3 ~]$ systemctl status origin-node
● origin-node.service - Origin Node
   Loaded: loaded (/usr/lib/systemd/system/origin-node.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2016-03-16 22:50:10 UTC; 11s ago
     Docs: https://github.com/openshift/origin
  Process: 15771 ExecStart=/usr/bin/openshift start node --config=${CONFIG_FILE} $OPTIONS (code=exited, status=255)
 Main PID: 15771 (code=exited, status=255)

Mar 16 22:50:10 jibo-3 systemd[1]: Failed to start Origin Node.
Mar 16 22:50:10 jibo-3 systemd[1]: Unit origin-node.service entered failed state.
Mar 16 22:50:10 jibo-3 systemd[1]: origin-node.service failed.
Mar 16 22:50:10 jibo-3 systemd[1]: origin-node.service holdoff time over, scheduling restart.
Mar 16 22:50:10 jibo-3 systemd[1]: start request repeated too quickly for origin-node.service
Mar 16 22:50:10 jibo-3 systemd[1]: Failed to start Origin Node.
Mar 16 22:50:10 jibo-3 systemd[1]: Unit origin-node.service entered failed state.
Mar 16 22:50:10 jibo-3 systemd[1]: origin-node.service failed.
</pre>
#### Output the JOURNALCTL 
<pre>
ar 16 22:52:53 jibo-3 systemd[1]: Starting Origin Node...
-- Subject: Unit origin-node.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit origin-node.service has begun starting up.
Mar 16 22:52:53 jibo-3 origin-node[18148]: I0316 22:52:53.470908   18148 plugins.go:71] No cloud provider specified.
Mar 16 22:52:53 jibo-3 origin-node[18148]: I0316 22:52:53.470993   18148 common.go:77] Self IP: 13.7.194.121.
Mar 16 22:52:53 jibo-3 origin-node[18148]: I0316 22:52:53.471015   18148 start_node.go:288] Starting node 13.7.194.121 (v1.1.4)
Mar 16 22:52:53 jibo-3 origin-node[18148]: I0316 22:52:53.472392   18148 start_node.go:297] Connecting to API server https://13.7.194.120
Mar 16 22:52:53 jibo-3 forward-journal[14725]: time="2016-03-16T22:52:53.474709882Z" level=info msg="{Action=_ping, LoginUID=4294967295, PID=18148}"
Mar 16 22:52:53 jibo-3 origin-node[18148]: I0316 22:52:53.475045   18148 node.go:125] Connecting to Docker at unix:///var/run/docker.sock
Mar 16 22:52:53 jibo-3 origin-node[18148]: I0316 22:52:53.536840   18148 manager.go:131] cAdvisor running in container: "/"
Mar 16 22:52:53 jibo-3 origin-node[18148]: E0316 22:52:53.584427   18148 controller.go:146] Failed to configure docker networking: exec: "openshift-sdn-docker-setup.sh": executable file not found in $PATH
Mar 16 22:52:53 jibo-3 origin-node[18148]: F0316 22:52:53.587858   18148 node.go:258] error: SDN node startup failed: Failed to start plugin: exec: "openshift-sdn-docker-setup.sh": executable file not found in $PATH
Mar 16 22:52:53 jibo-3 systemd[1]: origin-node.service: main process exited, code=exited, status=255/n/a
Mar 16 22:52:53 jibo-3 systemd[1]: Failed to start Origin Node.
-- Subject: Unit origin-node.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit origin-node.service has failed.
--
-- The result is failed.
Mar 16 22:52:53 jibo-3 systemd[1]: Unit origin-node.service entered failed state.
Mar 16 22:52:53 jibo-3 systemd[1]: origin-node.service failed.
Mar 16 22:52:53 jibo-3 systemd[1]: origin-node.service holdoff time over, scheduling restart.
Mar 16 22:52:53 jibo-3 systemd[1]: start request repeated too quickly for origin-node.service
Mar 16 22:52:53 jibo-3 systemd[1]: Failed to start Origin Node.
-- Subject: Unit origin-node.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit origin-node.service has failed.
--
-- The result is failed.
Mar 16 22:52:53 jibo-3 systemd[1]: Unit origin-node.service entered failed state.
Mar 16 22:52:53 jibo-3 systemd[1]: origin-node.service failed.
</pre>

Any one seeing the similar problem? i am using the latest version of openshift-ansible playbooks. I tried this multiple times on different servers. In all cases it failed with the same error messages.

**Comment by pat2man** [comment]
Installing the `origin-sdn-ovs` package fixed that for me.

**Comment by sureddy** [comment]
@pat2man installing that package did the magic. isn't this supposed to be installed from RPMS?

**Comment by brenton** [comment]
openshift-sdn-ovs isn't a hard dependency.  I would suspect there's a bug in the playbook.  @sureddy, could you move this over to the https://github.com/openshift/openshift-ansible repo?
