### ISSUE TITLE
privileged parameter is not taken into account for DeploymentConfig 

### ISSUE THREAD

**Issue by akram** [openshift/origin#8084]
privileged parameter is not taken into account for DeploymentConfig

##### Version
oc v1.1.3-645-gf78f941
kubernetes v1.2.0-origin-41-g91d3e75

##### Steps To Reproduce
https://gist.github.com/akram/a2c9f633dd56e20c002e
1 - Use a DeploymentConfig with "privileged: true" in securityContext.
2 - Import the deploymentConfig : oc create -f dc.yaml 
3 - edit the dc again:  oc edit dc my-dc
##### Current Result
The privileged attribute is not saved/taken into account.
##### Expected Result
The privileged attribute should have remained.

**Comment by deads2k** [comment]
privileged is a attribute on the security context for a container, not on a podspec.

**Comment by deads2k** [comment]
https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1/types.go#L1495 versus https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1/types.go#L1126 .  It is confusing.

**Comment by akram** [comment]
@deads2k thanks, that was it indeed
closing the issue
