### ISSUE TITLE
Build logs under Kubernetes don't work, while regular pod logs are fine

### ISSUE THREAD

**Issue by paralin** [openshift/origin#8093]
Running OpenShift under kubernetes.

Logs for regular pods under Replication Controllers work fine, but I get the "logs not available" message for currently running builds.

The logs for OpenShift indicate a certificate error:

```
E0317 15:40:13.541856       1 errors.go:63] apiserver received an error that is not an unversioned.Status: Get https://ip-172-20-0-179.us-west-2.compute.internal:10250/containerLogs/test/docker-node-hello-1-build/docker-build?follow=true&limitBytes=10485760&tailLines=1000: x509: certificate signed by unknown authority
```

This doesn't make much sense, though, as the logs work perfectly fine for the pods. Is this another case of OpenShift using the Kubernetes API to access logs for one thing, but then directly contacting kubelet for logs in an almost identical situation?

I think obviously there's some misconfiguration in the kubelet certificate here. I'm not sure which certificate is incorrect here, both in the configuration and in where I find this particular cert. At the same time, it doesn't make much sense that two near identical components would work differently like this.

**Comment by liggitt** [comment]
Looks like the build log rest handler assumes it has a transport that is valid to talk to the node: https://github.com/openshift/origin/blob/master/pkg/build/registry/buildlog/rest.go#L121

**Comment by liggitt** [comment]
you need to make sure the info in `kubeletClientInfo` in the master config is valid for the remote nodes (ca, client cert/key, and port)

**Comment by paralin** [comment]
@liggitt They are defined as "ca.crt", "master.kubelet-client.crt", "master.kubelet-client.key"

Maybe these are wrong? Where do they come from when I do `openshift start master --write-config` in the setup process? Where should they come from? I don't suppose there's any way to get this info via API operations (running pods and checking output)?

**Comment by paralin** [comment]
This works fine if you leave the `ca` field empty.

Fixed: `https://github.com/paralin/openshift-under-kubernetes/commit/3b49b8cb7f5f01ee7fa680eab20814eb9fdaf37d`

**Comment by paralin** [comment]
Okay fixed I suppose

**Comment by liggitt** [comment]
Only because that makes the master stop verifying the TLS connection to the node. The nodes also may not even be verifying the client cert presented by the master.

**Comment by paralin** [comment]
@liggitt I don't know where the CA for the kubelets comes from - It's something I'll look into at a later point. If it's a tiny bit insecure right now I'd prefer that to the logs not working at all.

**Comment by liggitt** [comment]
Right. You'd have to check how the kube API server is being invoked. It is likely doing the same thing (not verifying the kubelet and not authenticating to the kubelet)

**Comment by paralin** [comment]
@liggit I dug around earlier in the kubelets and found a .crt and .key for the kubelet but no .ca. So not sure. Will look again once I fix all these random build and registry errors.

**Comment by liggitt** [comment]
crt and key are likely self-signed serving certs (the default, I think), which would mean there is no single CA you could trust that would cover all nodes.

**Comment by paralin** [comment]
So there's no reason to set “ca” then?

On Fri, Mar 18, 2016 at 1:15 AM Jordan Liggitt <notifications@github.com> wrote:
crt and key are likely self-signed serving certs (the default, I think), which
would mean there is no single CA you could trust that would cover all nodes.

**Comment by liggitt** [comment]
If you gathered all the self signed certs (which *may* be CAs themselves… I can't remember), you could make a cert bundle you could specify as the CA. That would let you verify you were talking to one of those nodes, at least. Depends how much you care about the master->kubelet connection being secure.
