### ISSUE TITLE
Should not be able to edit a PVC that has been bound to a PV

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#8106]
In the web console I shouldn't be able to edit a PVC once it has been bound.  The api server has added validation that prevents the spec from being modified once it is bound so it will throw an error, so we should remove the action completely on bound PVCs.

**Comment by jwforres** [comment]
@fabianofranz @spadgett

**Comment by jwforres** [comment]
cc @markturansky

**Comment by markturansky** [comment]
PVCs are "Bound" when `pvc.Spec.VolumeName != ""`
