### ISSUE TITLE
Release image won't build because Go removed the tools package

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8113]
openshift/release will no longer build.

```
Step 5 : RUN mkdir $TMPDIR &&     go get golang.org/x/tools/cmd/cover github.com/tools/godep github.com/golang/lint/golint
 ---> Running in f3a4fa2464b8
[91mpackage golang.org/x/tools/cmd/cover
	imports github.com/tools/godep
	imports github.com/golang/lint/golint
	imports go/types: unrecognized import path "go/types"
[0mRemoving intermediate container f3a4fa2464b8
The command '/bin/sh -c mkdir $TMPDIR &&     go get golang.org/x/tools/cmd/cover github.com/tools/godep github.com/golang/lint/golint' returned a non-zero code: 1
```

**Comment by smarterclayton** [comment]
https://groups.google.com/forum/#!searchin/golang-dev/tools/golang-dev/B-mS3yEKXRU/6pG121STCAAJ

**Comment by smarterclayton** [comment]
Going to move origin to 1.6 golang

On Mar 18, 2016, at 7:40 AM, Dan McPherson <notifications@github.com> wrote:

Assigned #8113 <https://github.com/openshift/origin/issues/8113> to
@smarterclayton <https://github.com/smarterclayton>.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/8113#event-594747219>

**Comment by rhcarvalho** [comment]
> Going to move origin to 1.6 golang

We need to update the format we use when passing `ldflags` to use the `-X=...` syntax :)

(there will be warnings about that when building with Go 1.6)

**Comment by smarterclayton** [comment]
Just warnings though, not errors.

**Comment by liggitt** [comment]
does rhel have 1.6?

**Comment by smarterclayton** [comment]
Doesn't matter, they don't use our build scripts exactly.

**Comment by stevekuznetsov** [comment]
Have you determined if `go fmt` changed? I'm almost certain changes to `go vet` made it in to 1.6 as well.

**Comment by eparis** [comment]
RHEL will have 1.6 as soon as we want it to. The only reason it doesn't is because OpenShift asked them to wait...

**Comment by smarterclayton** [comment]
We don't run go vet and fmt yet on 1.6.

As soon as we cut 3.2 it's probably time to move over.  It's going to be
expensive to maintain 1.4 tooling now.  We should kick off the discussion.
