### ISSUE TITLE
support ServiceAccountRoleRequest so that apps can create a ServiceAccount and describe the roles they would like to be given by an operator

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#8118]
when running NetflixOSS type stuff inside Kubernetes [like](https://github.com/fabric8io/kubeflix) [this](https://blog.fabric8.io/kubeflix-kubernetes-integration-with-netflix-69f76d27ef91#.s24wa92xs), we need to support client side discovery of pods and for the Hystrix dashboard via Turbine, we need to discover pods to collect the circuit breaker metrics.  

Both require permissions to get pods. Also both templates in a CI / CD environment can be run in any project.

So we create a ServiceAccount as part of the OpenShift templates. If the user tries to run these templates in some namespace then the microservices using client side discovery and the Turbine server fail until an operator adds the right roles to the ServiceAccounts.

I don't see a way right now to describe the roles the ServiceAccount's need; so that when someone tries to instantiate an OpenShift template in a namespace, it gives the end user (or sysadmin) the chance to choose to enable the roles.

It'd be nice to even limit being able to instantiate OpenShift templates until the ServiceAccountRoleRequest is satisfied. e.g. without being able to see pods, the client side discovery is gonna fail badly - so there's no point the user trying to run the app until some sysadmin has granted the necessary roles.

So it feels like we need to specify required roles for ServiceAccounts in an OpenShift template; then those roles can be requested of a sysadmin; when the roles have been granted, the user can then run the app.

I wonder did you have some other mechanism in mind? I'm reminded of something Clayton said a little while back about having ProjectRequest to request a project; then someone else can grant it. It feels like we need a similar thing; that an OpenShift template can create the ServiceAccounts it needs and request the roles it needs for those SAs (but not actually get them unless some user / sysadmin approves)

**Comment by deads2k** [comment]
Someone requesting a project is never going to be able to request that his service account be granted rights across the entire cluster.

Granting rights within a namespace is possible, but not pretty. You can create a `RoleBinding` object inside of your template that binds the `ClusterRole` to the `ServiceAccount` in the namespace.

@smarterclayton request for a `binding` subresource on `roles`.

**Comment by jstrachan** [comment]
@deads2k BTW I'm not asking for 'across the cluster' - I'm simply asking that we can describe the required roles in the current project/namespace for a ServiceAccount inside an OpenShift template. 

I didn't know we could add a RoleBinding though; lemme see about using that. Should a developer in a project be able to just run stuff that has RoleBinding objects & they get applied? I figured roles were something a sysadmin type person needs to grant? 

BTW there are quite a few microservices we need to run on top of OpenShift which just requires reading Pods & RCs only (e.g. [kubeflix](https://github.com/fabric8io/kubeflix) for Ribbon & Turbine discovery or [kansible](https://github.com/fabric8io/kansible). I wonder if we should have a default SA for reading pods/RCs as its such a common thing?

**Comment by deads2k** [comment]
> Should a developer in a project be able to just run stuff that has RoleBinding objects & they get applied? I figured roles were something a sysadmin type person needs to grant?

A project admin has the power to manager permissions in his project.  An editor does not.



> I wonder if we should have a default SA for reading pods/RCs as its such a common thing?

I don't think that we should do that by default.  It is possible for a cluster-admin to choose to do that by creating a project template that sets that up.

**Comment by jstrachan** [comment]
@deads2k so given the person trying to run an app from a template might not be project admin, it sounds like we need some kind of RoleBindingRequest or something that can be ran by anyone in the project; which then the project admin person gets to approve/deny? We can then figure out a UX around it to make it easy for developers to run tools (e.g. hystrix dashboard) and their project admin can then allow roles on ServiceAccounts so things can work

**Comment by deads2k** [comment]
> it sounds like we need some kind of RoleBindingRequest

I'm not opposed to a request/approval flow.  Could you describe your use-case and maybe an example API in a card on our board: https://trello.com/b/M0rP0aLj/platform-management ?

**Comment by smarterclayton** [comment]
Why not use DNS?

**Comment by smarterclayton** [comment]
Alternatively, we've had requests to open up endpoints so that all service accounts can access them by default.  We would not open up pods by default, definitely too dangerous.

**Comment by jimmidyson** [comment]
See @jstrachan - told you DNS was the answer to everything.

@smarterclayton Are there SRV records for normal (non-headless) service endpoints now? Seem to remember they weren't available. The one drawback of this approach is speed of updates, noticing an endpoint has come/gone that the watch endpoints API gives you.

**Comment by jstrachan** [comment]
@jimmidyson  :)

Not being able to use kubernetes watches is a bit of a drag with DNS for client side load balancing and discovery.

**Comment by smarterclayton** [comment]
Use the ".endpoints." DNS address.

I think EAP already requested that regular service accounts have read
access to endpoints.  It's not unreasonable to me.

**Comment by jstrachan** [comment]
@smarterclayton letting SA's see endpoints by default sounds a great idea. We definitely should do that as endpoint discovery is extremely common.

However there's still loads of apps folks are gonna build that need other resources & roles. Here's a few off the top of my head that we've built in the last year:

* jenkins - needs to create pods, watch/edit BuildConfigs and Builds
* hubot-notifier - needs to watch pods / RCs to notify chat services of changes to the system (based on rules/filters etc)
* kansible - needs to watch/modify the RC which started it (could use ConfigMap instead or ThirdPartyResource one day if that works)
* apiman - watches services come and go to bridge them into the apiman subsystem; needs to look at the annotations on services 
* kubeflix turbine - watches pods which have hystrix inside. Technically we could force all developers to make a headless service for all of their pods that have hystrix inside (whether it has a need for a service or not) just so that turbine could find it; but finding pods is simpler for developers of microservices so we'd rather go that route
* fabric8 messaging - watches pods of brokers start (again could use headless services & endpoints for that part) but also needs to scale the RC for the brokers up and down for Messaging as a Service

All of the above work OOTB on kubernetes; they are hard to install on OpenShift by default - unless we assume every developer is a project admin and we include the RoleBindings inside OpenShift templates due to roles needing to be added to SAs - but that feels a bit wrong to me really.

The problem is the kubernetes REST API is so awesome; has watches and is really damn useful for building microservices.

Maybe we need to add a default annotation to SA's for "this is the command line that your project admin has to run after you've ran the template and its failing for security reasons - to make things work". Then we can try in the UI give a hint at what developers have to email their project admin folks with the CLI they need to type in for them? That doesn't sound a great UX though ;).

Annotating SAs is a option though; at least then we can build some kind of tooling to let developers know why apps don't work on OpenShift
