### ISSUE TITLE
Upgrading from 1.1.3 and docker from 1.8 to 1.9 with yum update breaks everything

### ISSUE THREAD

**Issue by david-strejc** [openshift/origin#8122]
I've did just yum update and updated Open Shift v 1.1.3 to 1.1.4

After upgrade my containers won't start. So I've cleaned up everything - docker processes docker images and I've restarted origin-node and origin-master services.

Now I got following error:

Error: build error: timeout while waiting for remote repository
##### Version

1.1.4 (upgrade)
##### Steps To Reproduce
1. Upgrade from 1.1.3 to 1.1.4
2. Upgrade docker from 1.8 to 1.9 (yum update)
##### Current Result

Error: build error: timeout while waiting for remote repository.
##### Expected Result

Image is build and pushed into docker registry.

**Comment by david-strejc** [comment]
Update:

I've rebooted master and now git pull is passing.

**Comment by dragon9783** [comment]
Upgrade openshift origin need reboot ? I run a small containerized cluster , also need to reboot master after upgrade.

**Comment by smarterclayton** [comment]
Closing due to age.
