### ISSUE TITLE
oc new-app --insecure-registry on OpenShift Registry

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#8123]
I have to use the --insecure-registry tag to use an image stream stored in my OpenShift Registry 
##### Version

```
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75
```
##### Steps To Reproduce
1. Secured + persists the OpenShift Docker Registry
2. I'm able to login into the registry and push my image. My image is there.
3. I try to create a `new-app` by using the provided image-stream
##### Current Result

```
oc new-app 172.30.xx.xx:5000/test/image:2
error: can't look up Docker image "172.30.xx.xx:5000/test/image:2": Internal error occurred: Get https://172.30.xx.xx:5000/v2/: x509: certificate signed by unknown authority
error: no match for "172.30.xx.xx:5000/test/image:2"
```
##### Expected Result

I become the expected result by adding `--insecure-registry`

```
oc new-app --insecure-registry 172.30.xx.xx:5000/test/image:2
--> app is build
```
##### Additional Information

Everything seems to work fine for my registry. I'm able to push and pull images manually after authenticating in the registry. When I change the ca.crt it gives the expected error. 
I'm also able to push images after creating a s2i app in the webconsole.

```
oc logs docker-registry-6-wo7bt | grep tls
time="2016-03-17T09:54:51.489099298Z" level=info msg="listening on :5000, tls" go.version=go1.4.2 instance.id=82e5d7a4-a56b-4677-b6fc-4031b9f4f97f 
```

other logs:

```
10.1.0.1 - - [18/Mar/2016:14:37:39 +0000] "GET /healthz HTTP/1.1" 200 0 "" "Go 1.1 package http"
10.1.0.1 - - [18/Mar/2016:14:37:49 +0000] "GET /healthz HTTP/1.1" 200 0 "" "Go 1.1 package http"
..
```

example 8: https://docs.openshift.org/latest/dev_guide/new_app.html#specifying-an-image

**Comment by deads2k** [comment]
@soltysh We trust the certs in the docker trusted certs, right?

**Comment by lorenzvth7** [comment]
@deads2k I already had this issue once with a normal docker registry (not openshift) and I secured it with selfsigned certs and than it was normal to use --insecure-registry. This was told me by @smarterclayton . But I would assume this isn't necessary on the OpenShift Registry itself.

**Comment by soltysh** [comment]
@deads2k unfortunately we don't look into the certs we us, iow. the ca.crt. we issue. This means you need to pass `--insecure-registry` when importing images from our internal registry.

**Comment by soltysh** [comment]
For one you might not have the ca.crt on the host (when invoking `oc new-app`, image import is a bit different, but also requires to pass insecure annotation/flag).

**Comment by smarterclayton** [comment]
Why don't we look into our certs?

**Comment by smarterclayton** [comment]
Image pull secrets should grab the internal registry secrets.

**Comment by lorenzvth7** [comment]
@soltysh @smarterclayton  So I have to use the --insecure flag/tag and it will also be like that in future versions?

**Comment by soltysh** [comment]
@lorenzvth7 for now - yes, future versions will have the fix mentioned by @smarterclayton.

**Comment by lorenzvth7** [comment]
@soltysh Okay thanks. This issue can be closed.

**Comment by soltysh** [comment]
@pweil- mind re-opening this issue and assigning it to me. I'm planning to work on a fix @smarterclayton mentioned.
