### ISSUE TITLE
External kubernetes: Basic API endpoints are 404

### ISSUE THREAD

**Issue by paralin** [openshift/origin#8124]
Attempting to hit /apis and /versions and a few other endpoints that `kubectl` hits in literally every operation return 404s.

Do I need to enable them in the config file? I tried adding -versions and -apis to the API versions entries at the beginning of master-config and that didn't do it.

**Comment by paralin** [comment]
This is under kubernetes @ncdc @liggitt

**Comment by deads2k** [comment]
I'm betting its our proxy.  `/apis` didn't exist when we configured it.  this could end up being interesting.

**Comment by liggitt** [comment]
Opened https://github.com/openshift/origin/pull/8125 for now

**Comment by deads2k** [comment]
@paralin Did you typo `/version`?  You say others, which ones in particular?

**Comment by paralin** [comment]
I typo'd version, yeah. You can check what is needed by doing `kubectl --v=8 create -f .` in most of the examples. Kubectl for some reason hits a lot of endpoints before doing anything.

The only ones it checked before failing out were `apis` and `version`.

**Comment by paralin** [comment]
@deads2k @liggitt I have found also that `/swaggerapi/api/v1` 440s

**Comment by liggitt** [comment]
If anything tries to traverse from /swaggerapi/, that root doc wouldn't include /api and /apis. Combining swagger docs isn't something I'm sure we want to do

**Comment by paralin** [comment]
@liggitt Is there some kind of short term solution to fixing this?

**Comment by liggitt** [comment]
external kubernetes mode has been removed. In the future, API aggregation and external initialization will allow OpenShift APIs to be surfaced and consumed by normal kubectl clients.
