### ISSUE TITLE
Router unique_host.go admission check is not stable when creations are in the same second

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8132]
`pkg/router/unique_host.go` uses timestamp from the server to determine which route gets in, but the timestamp precision on Creation is at the second.  So two routes with the same host in the same second could have equivalent values, and thus depending on the order of the controller relist in the router could admit them in different orders.

We need to check for timestamp equal, then do a secondary comparison on something like UID.

**Comment by smarterclayton** [comment]
Can slip 1.2

**Comment by marun** [comment]
@danmcp I think this can be closed.
