### ISSUE TITLE
etcd Data Dir Missing From Integration Test Artifacts

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8135]
Currently 2/5 of the total size of our test artifacts on Jenkins is the etcd data dir / data binary store for `test-cmd`. None exists for `test-integration`. If we're doing a full export to JSON of all of the objects we have in etcd, do we need the data binary? If we need the binary, do we need it for `test-integration`?

/cc @deads2k @danmcp

**Comment by deads2k** [comment]
I don't care about the binary store.

**Comment by danmcp** [comment]
@stevekuznetsov No opinion.  Did you check who added it in the first place?

**Comment by stevekuznetsov** [comment]
@ironcladlou I believe you added this directory in #114: https://github.com/openshift/origin/commit/3a866bb86e93a2ab620bd0d368bab18b3277217f#diff-e2c8544666bb21f92286b190d5c8cb9aR27

Do you remember why you added this directory? Does etcd need to have a data directory specified for startup? What is the benefit of keeping the binary store around?

**Comment by ironcladlou** [comment]
I don't have any reason to keep the data dir in test runs as long as there's a JSON dump.
