### ISSUE TITLE
The project " + context.projectName + " does not exist

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#8137]
When I'm opening page for non-existing project I see parts of the code.

##### Version
openshift v1.1.3-649-ga81b41f

##### Steps To Reproduce
1. In the UI console try to open non-existing project

##### Current Result
![error](https://cloud.githubusercontent.com/assets/87088/13888136/0e107264-ed40-11e5-99e9-396a422665e5.png)

##### Expected Result
Message shouldn't contain non-parsed parts of the code.

**Comment by php-coder** [comment]
cc @jwforres

**Comment by liggitt** [comment]
fixed in https://github.com/openshift/origin/pull/8032/files
