### ISSUE TITLE
Hint for long executing pod is showing forever

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#8138]
##### Version
openshift v1.1.3-649-ga81b41f

##### Steps To Reproduce
1. Create new app
2. Open tab with list of the pods
3. When open of the pods will be executing too long you will see the sign with exclamation mark near pod's name.
4. Move mouse to this sign to see the hint

##### Current Result
![error2](https://cloud.githubusercontent.com/assets/87088/13888204/6b2027b0-ed40-11e5-980d-67618e798539.png)
![error3](https://cloud.githubusercontent.com/assets/87088/13888205/6c583f14-ed40-11e5-9590-85ca87b3e74a.png)

**Comment by php-coder** [comment]
cc @jwforres

**Comment by jwforres** [comment]
cc @spadgett @sg00dwin unlikely its related but since you guys recently had changes to the tooltips.  this would apply to any pod warning

**Comment by jwforres** [comment]
@php-coder if you click somewhere on the screen does it go away, you aren't by any chance on a tablet, phone, or other touch screen device are you?

**Comment by php-coder** [comment]
>if you click somewhere on the screen does it go away

No, it doesn't. On the second screenshot you can see that I even can open menu and tooltip is still here.

>you aren't by any chance on a tablet, phone, or other touch screen device are you?

No, it's on desktop, in Firefox.

**Comment by spadgett** [comment]
See also #6490 and #6153

@php-coder The tooltip style looks strange. I don't see the warning icon, and the text is selected. Did you select the text to copy it?

**Comment by php-coder** [comment]
@spadgett Look the same as #6490.

>I don't see the warning icon, and the text is selected.

Warning icon probably disappeared.

>Did you select the text to copy it?

Do be honest I don't remember, probably I could do this unintentionally.

**Comment by jwforres** [comment]
i wonder if maybe the pod warning went away while the tooltip was open? and
it broke the bootstrap JS bits that should have closed it?

maybe it needs an on destroy in the toggle directive, although it would be
weird for the tooltip to disappear while you were trying to read it...

**Comment by spadgett** [comment]
> i wonder if maybe the pod warning went away while the tooltip was open? and
it broke the bootstrap JS bits that should have closed it?

I'm almost certain this is it. It happened to me once, and the tooltip is not dismissed.

**Comment by jwforres** [comment]
we fixed this a several weeks ago, was a problem with all of our tooltips
