### ISSUE TITLE
Plans to implement a ConfigMap web UI?

### ISSUE THREAD

**Issue by paralin** [openshift/origin#8153]
Presently there is no UI for actually editing secrets (as far as I know). This is somewhat understandable as previously they were base64 encoded and really should be edited by the CLI anyway. But with the introduction of the ConfigMap object upstream, it seems that now is a good opportunity to introduce a UI to edit these config maps on the fly in the browser.

I know that [this roadmap issue](https://trello.com/c/ypSJ5FN5/721-3-complete-rails-config-database-yml-based-on-available-data) exists to make it easier to make a "Database.yml". I think the answer to this, as defined by Kubernetes, is to make a ConfigMap and map it to a file using a mount. 

You would need to be able to edit the K/V on the configmap and potentially detect what language a field is in (if it's yaml for instance) to make editing yaml configs a bit easier.

Thoughts?

**Comment by liggitt** [comment]
There is ongoing work to show, and eventually allow creating/editing new resources. @jwforres might already have a trello card tracking priority and progress of something like this

**Comment by jwforres** [comment]
So in the short term we are looking at a more generic way to list other resources in your namespace, think secrets, config maps, HPAs, the list goes on.  And from that list you'd at least get access to the raw editor (Edit YAML) and Delete actions.  That is this story https://trello.com/c/ZTDAi1DM 

The other short term feature that will help is the ability to create anything from raw json or yaml that you upload / drag and drop / paste in.  That would let you create new config maps from the console without having to drop to the CLI.  That is https://trello.com/c/lJEjZWgG (the story name says "template" but the work was expanded to anything you would use with either `oc process` or `oc create -f` )

The short term solutions are not ideal create/edit/view experiences, but will let us keep up with providing minimal access to features the API and CLI expose.  The individual GUI editors are prioritized based on usage / number of people asking for them.  The story for service accounts, secrets, and config maps is here https://trello.com/c/qu8SVDfx  but will probably be split out into smaller chunks of work.
