### ISSUE TITLE
Daemonset need create pod on a group of nodes

### ISSUE THREAD

**Issue by mdshuai** [openshift/origin#8154]
##### Description of the issue
In recent online test, Every project has default nodeSelector in master-config.yaml.  there is actually nine nodes, but only four is provided normal user schedule pod, the others is remained for infra project. In this case, user don't know the actual nodes, when create a daemonset should only create pod on a group of nodes which provided for normal user not every node

##### Steps To Reproduce
1. Create a daemonset and check the pod
```
[root@dhcp-128-7 dma]# oc get pod
NAME                    READY     STATUS                    RESTARTS   AGE
hello-daemonset-1vx1q   1/1       Running                   0          9m
hello-daemonset-21u6y   0/1       NodeSelectorMismatching   0          9m
hello-daemonset-gdilc   0/1       NodeSelectorMismatching   0          9m
hello-daemonset-gp257   1/1       Running                   0          9m
hello-daemonset-i87ra   1/1       Running                   0          9m
hello-daemonset-tr4pm   0/1       NodeSelectorMismatching   0          9m
hello-daemonset-xqc4i   0/1       NodeSelectorMismatching   0          9m
hello-daemonset-y32ql   1/1       Running                   0          9m
hello-daemonset-yh04w   0/1       NodeSelectorMismatching   0          9m
```
##### Current Result
1. Some pod is never running because NodeSelectorMismatching, those node is used for other purpose or other project.

##### Expected Result
1. Schedule pod on a group of node not all nodes.

##### Additional Information

**Comment by deads2k** [comment]
@liggitt you still have the code to fix this or do we want to leave it like this? (I still don't).

**Comment by liggitt** [comment]
options are:

1. extend the project node selector admission plugin to denormalize project node selector into DaemonSet object on create/update (just like pods)
  * pro: anything looking solely at the daemonset can understand what the daemonset is selecting
  * pro: it's not possible to create/update a DaemonSet to conflict with the project's nodeSelector (at create/update time)
2. extend the DaemonSetController to be project-node-selector-aware
  * pro: daemonsets never drift from the project nodeSelector if the project changes

**Comment by deads2k** [comment]
* con for 1: you either continue to denomalize the selector on project-node-selector updates or it will drift.  Updating someone's resource to mean something different seems wrong.

**Comment by liggitt** [comment]
I also don't like unioning the DS nodeSelector with a hidden selector

**Comment by liggitt** [comment]
(all the pros for each are cons for the other... just listed pros)

**Comment by liggitt** [comment]
daemonsets create pods with a higher priority than replication controllers or jobs. they are primarily designed to allow cluster admins to run something on every node. https://github.com/openshift/origin/pull/8242 will remove the ability of a normal project admin or editor to create daemonsets. Cluster admins are more likely to create them in projects with no nodeselector restrictions.

**Comment by liggitt** [comment]
Closing, daemonsets are oriented toward cluster admins, who would be able to adjust the project's nodeselector as desired, or set the daemonset's nodeselector to match restrictions.
