### ISSUE TITLE
[feature request]As a cluster-admin I want monitor node stat

### ISSUE THREAD

**Issue by mdshuai** [openshift/origin#8155]
#### Description of the issue
As a cluster-admin I want to monitor all node stat info in webconsole and display node resource usage percent. Some user think this import for them. Before some node become crash, they want get warning etc. Is there any plan to do this?

thanks so much.

**Comment by liggitt** [comment]
The openshift web console is geared toward users that are limited to specific namespaces, and don't have visibility to cluster level resources. 

cc @jwforres

**Comment by jwforres** [comment]
Please take a look at the ManageIQ project http://manageiq.org/  which is the cluster administration project.  As @liggitt mentioned the openshift console is geared towards end users working within a project (namespace) scope.
