### ISSUE TITLE
Filter add button can overlap overview toggle bottoms with long filter values

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8156]
<img width="467" alt="screen shot 2016-03-19 at 9 48 38 pm" src="https://cloud.githubusercontent.com/assets/1167259/13904798/94b7b29e-ee82-11e5-9aaf-f2d9b8f01315.png">

/cc @jwforres @sg00dwin

**Comment by sg00dwin** [comment]
I'll look at this

**Comment by jwforres** [comment]
FYI moving this out of 1.2.0 into 1.2.x, not high enough priority for 1.2.0 at this point
