### ISSUE TITLE
Extended tests fail because Docker daemon is stopped

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8159]
https://ci.openshift.redhat.com/jenkins/job/origin_extended/736/console

```
I0319 00:51:15.057795    4116 start_node.go:288] Starting node 172.18.7.46 (v1.1.4-107-g79552fd)
I0319 00:51:15.059453    4116 start_node.go:297] Connecting to API server https://172.18.7.46:8443
F0319 00:51:15.062641    4116 node.go:158] error: No Docker socket found at /var/run/docker.sock. Have you started the Docker daemon?
```

**Comment by smarterclayton** [comment]
The docker daemon should not be stopping - we may need to grab the docker daemon logs

**Comment by deads2k** [comment]
@stevekuznetsov You've spent a lot of time with Jenkins.  Can you set it up to gather the docker daemon logs if openshift fails to start with "No Docker socket found at"?  That would give us something to work with.

**Comment by stevekuznetsov** [comment]
Will do

**Comment by deads2k** [comment]
@stevekuznetsov opened https://github.com/openshift/origin/pull/8168 to gather the docker daemon logs.  When it happens again we'll have more info.

**Comment by stevekuznetsov** [comment]
We can kick the LDAP Extended job to force it if we'd like - it takes ~10min to finish and less to fail

**Comment by pweil-** [comment]
haven't seen this in a while.  Lowering priority since we will not block on it and are just waiting to gather more info.

**Comment by deads2k** [comment]
no one has bumped this in five months, closing.
