### ISSUE TITLE
Overlapping text on settings page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8162]
I think we should probably stack at mobile. I also noticed the columns/margins were different sizes at wider widths than the browse pages since we use flexbox here now rather than a `dl`.

<img width="487" alt="screen shot 2016-03-21 at 7 09 15 am" src="https://cloud.githubusercontent.com/assets/1167259/13916907/e16975bc-ef33-11e5-9143-d89839d0dd0c.png">
<img width="487" alt="screen shot 2016-03-21 at 7 09 21 am" src="https://cloud.githubusercontent.com/assets/1167259/13916908/e169c54e-ef33-11e5-9c8a-b11177972c10.png">

/cc @jwforres @benjaminapetersen

**Comment by jwforres** [comment]
fix merged
