### ISSUE TITLE
Can not rsh into existing pod

### ISSUE THREAD

**Issue by marekjelen** [openshift/origin#8172]
There is my docker registry pod
```
$ oc get pods -n default

docker-registry-1-ed4bk   1/1       Running   3          7d
```

and it's container exists
```
$ docker ps

8c2d8953b26b        openshift/origin-docker-registry:v1.1.3   "/bin/sh -c 'DOCKER_R"   About a minute ago   Up About a minute                       k8s_registry.20a7a7d2_docker-registry-1-ed4bk_default_fd7b542a-e9c4-11e5-81d3-0008a209b4dd_ae7c218e
```

when I try to rsh into the pod, I get an error, that the pod does not exist
```
$ oc rsh docker-registry-1-ed4bk -n default

Error from server: pods "docker-registry-1-ed4bk" not found
```

but can access the container

```
$ docker exec -it 8c2d8953b26b /bin/sh

sh-4.2$
```

##### Version
openshift v1.1.3
kubernetes v1.2.0-origin
etcd 2.2.2+git

oc v1.1.3
kubernetes v1.2.0-origin

##### Steps To Reproduce

as described above

##### Current Result

can not rsh into existing pod

##### Expected Result

should be able to rsh into existing pod

**Comment by liggitt** [comment]
command args have to come before the pod name... args after that are passed to the pod.

```
oc rsh -n default docker-registry-1-ed4bk
```

**Comment by marekjelen** [comment]
yep, that's it :+1:
