### ISSUE TITLE
Nodes don't automatically rejoin cluster

### ISSUE THREAD

**Issue by jeremyeder** [openshift/origin#8190]
I rebooted a master and 2 nodes at roughly the same time.  The nodes happened to boot up faster (different hardware).  The master eventually came up (perhaps 1 minute after the nodes?).

However the nodes are in NotReady status.  Looking at the logs for atomic-openshift-node service on one of the nodes, I see that the node tried to register with the master and couldn't reach it.

Due to the Restart=always setting in the atomic-openshift-node unitfile, systemd restarted the service 5 times, and each could not connect.  Those 5 retries took a total of 5 seconds.  5 seconds is less than the reboot difference in this hardware, so the nodes did not rejoin.

After the master is up, simply restarting atomic-openshift-node allows them to join the cluster and become Ready.

I realize that there should be
- multiple masters
- sequenced/controlled cluster restart, reboot the master, wait for it to come back, then evac nodes and reboot them.

But, I think the systemd Restart=always is not enough to heal the cluster after such a situation where the single master goes down or reboots.

I wonder if when the master comes up, it should go out and notify all nodes that it's back and signal them to rejoin? (maybe only makes sense in a single master environment).

**Comment by jawnsy** [comment]
Maybe a naïve question, but why wouldn't we just retry indefinitely, with an appropriate backoff and limit? For example, retry the connection at 5 seconds, 10 seconds, 20 seconds, 40 seconds, 80 seconds, 160 seconds, then every 5 minute interval thereafter? Surely one connection attempt every 5 minutes isn't a big deal, and it's better than the alternative (requiring an admin to ssh into the node and restart the service.)

Having the master solicit the nodes is also a good option, but doesn't seem necessary if we retry forever.

It's easy to think of other (possibly contrived) scenarios where you have multiple masters, but they're all in one data center or one rack and all become unreachable to some portion of the available nodes. One would expect that the nodes would eventually re-establish a connection to the master.

Also, why does the service die if a connection can't be established -- i.e. why are we relying on systemd to restart the service, rather than having some sort of internal retry policy? (the node agent is a daemon, right? so it should be a background process capable of retrying connections according to some configured interval)

**Comment by pweil-** [comment]
@jeremyeder I'm curious as to why your systemd unit failed just because it could not connect to the master.  The kubelet should be able to handle an unreachable master without failing.  To verify I used the multi-node vagrant environment and stopped the `openshift-master` service while monitoring the `openshift-node` service on minion-1.  It didn't die, but failed to update node status as expected.  

I also stopped the `openshift-node` service, waited for the master to show a not ready state and then restarted it to ensure it updated correctly to ready.  I think the issue here is that your service dies for some reason.  Any more info you can provide around that?

@jawnsy node status syncs from the kubelet will retry indefinitely.  The retry interval is configurable but should be defaulting to every 10 seconds IIRC.  For each node sync the kubelet will attempt to send the update with a retry count before declaring that particular attempt a failure.

**Comment by liggitt** [comment]
Stopping a master while a node is running is different than trying to bring up a node when a master is missing.

**Comment by pweil-** [comment]
> Stopping a master while a node is running is different than trying to bring up a node when a master is missing.

Yes, you're right.  You can fail the service that way but if the unit is set to always restart and the master comes back I'm not sure why it would stay in a failed state.  I see it continue normally once the master returns.  Granted, that node is down until it can successfully start (mine got an error starting the SDN as the hard failure when stopping node + master then starting node)

**Comment by jeremyeder** [comment]
@pweil- I believe Restart=always can't handle this situation because the connection fails (at the TCP level) as system unreachable, which is different to systemd than reachable, but the port is closed.

**Comment by jeremyeder** [comment]
It says in a failed state because the retry limit was reached. I guess that limit is 5?

**Comment by pweil-** [comment]
> @pweil- I believe Restart=always can't handle this situation because the connection fails (at the TCP level) as system unreachable, which is different to systemd than reachable, but the port is closed.

Hmm, I even suspended the master machine while the node was in a failed state and it seemed to keep retrying.  I'll try and see if there is a setting that would limit the `restart=always`.  Once I resumed the master machine and `openshift-master` AND the next retry from systemd came along for `openshift-node` carried on.

**Comment by pweil-** [comment]
@jeremyeder - looks like `RestartPreventExitStatus` would be the only thing that would prevent the `Restart` policy from taking affect but that wouldn't explain quitting after 5 attempts

**Comment by pweil-** [comment]
ah, maybe this

```
 StartLimitInterval=, StartLimitBurst=
           Configure service start rate limiting. By default, services which are started more than 5 times within 10 seconds are not permitted to start any more times until the 10 second
           interval ends. With these two options, this rate limiting may be modified. Use StartLimitInterval= to configure the checking interval (defaults to DefaultStartLimitInterval= in
           manager configuration file, set to 0 to disable any kind of rate limiting). Use StartLimitBurst= to configure how many starts per interval are allowed (defaults to
           DefaultStartLimitBurst= in manager configuration file). These configuration options are particularly useful in conjunction with Restart=; however, they apply to all kinds of starts
           (including manual), not just those triggered by the Restart= logic. Note that units which are configured for Restart= and which reach the start limit are not attempted to be
           restarted anymore; however, they may still be restarted manually at a later point, from which point on, the restart logic is again activated. Note that systemctl reset-failed will
           cause the restart rate counter for a service to be flushed, which is useful if the administrator wants to manually start a service and the start limit interferes with that.

       StartLimitAction=
           Configure the action to take if the rate limit configured with StartLimitInterval= and StartLimitBurst= is hit. Takes one of none, reboot, reboot-force, reboot-immediate, poweroff,
           poweroff-force or poweroff-immediate. If none is set, hitting the rate limit will trigger no action besides that the start will not be permitted.  reboot causes a reboot following
           the normal shutdown procedure (i.e. equivalent to systemctl reboot).  reboot-force causes a forced reboot which will terminate all processes forcibly but should cause no dirty file
           systems on reboot (i.e. equivalent to systemctl reboot -f) and reboot-immediate causes immediate execution of the reboot(2) system call, which might result in data loss. Similar,
           poweroff, poweroff-force, poweroff-immediate have the effect of powering down the system with similar semantics. Defaults to none.
```

**Comment by pweil-** [comment]
@jeremyeder can you try configuring `RestartSec` such that rate limiting isn't triggered?  Here is the unit file that my node was using

```
[Unit]
Description=OpenShift Node
Requires=network.target
After=docker.target network.target

[Service]
Environment=
ExecStart=/usr/bin/openshift start node --loglevel=5 --config=/data/src/github.com/openshift/origin/openshift.local.config/node-openshift-node-1/node-config.yaml
WorkingDirectory=/
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target
```

**Comment by pweil-** [comment]
@jeremyeder - any luck with new configuration or additional details?

**Comment by jeremyeder** [comment]
I haven't seen this occur again with the new config.  Have rebooted several
times.  I'll revert the config and try rebooting a few more times.

On Wed, Mar 30, 2016 at 8:33 AM, Paul Weil <notifications@github.com> wrote:

> @jeremyeder <https://github.com/jeremyeder> - any luck with new
> configuration or additional details?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/8190#issuecomment-203408821>
>



-- 

-- Jeremy Eder

**Comment by jeremyeder** [comment]
It happened again on the first try after reverting your suggestion.

On Wed, Mar 30, 2016 at 9:33 AM, Jeremy Eder <jeder@redhat.com> wrote:

> I haven't seen this occur again with the new config.  Have rebooted
> several times.  I'll revert the config and try rebooting a few more times.
>
> On Wed, Mar 30, 2016 at 8:33 AM, Paul Weil <notifications@github.com>
> wrote:
>
>> @jeremyeder <https://github.com/jeremyeder> - any luck with new
>> configuration or additional details?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/issues/8190#issuecomment-203408821>
>>
>
>
>
> --
>
> -- Jeremy Eder
>



-- 

-- Jeremy Eder

**Comment by pweil-** [comment]
@jeremyeder - ok, if the suggested changes fixed the issue the next question is how did you install?  @brenton - is this perhaps something we need to update in the installer somewhere?

**Comment by jeremyeder** [comment]
openshift-ansible byo playbooks.

On Wed, Mar 30, 2016 at 3:45 PM, Paul Weil <notifications@github.com> wrote:

> @jeremyeder <https://github.com/jeremyeder> - ok, if the suggested
> changes fixed the issue the next question is how did you install? @brenton
> <https://github.com/brenton> - is this perhaps something we need to
> update in the installer somewhere?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/8190#issuecomment-203603689>
>



-- 

-- Jeremy Eder

**Comment by pweil-** [comment]
@jeremyeder - just for completeness here...the rate limiting descriptions don't say they'll never restart the service, just that they'll prevent it from restarting within the specified interval after it hits the burst max.  Before we close this up:

1.  does your systemd have any rate limit setting specified either in the unit file or in the manager configuration file?
1.  when you hit the failure were you able to wait out the rate limit duration and see it eventually restart again or was it just hosed?

If you can see it restart after the interval passes I think we can just close this.  If it is never restarting I think we should lower the priority of this and try to identify exactly what is causing systemd to stop trying.

**Comment by jeremyeder** [comment]
This is a regular openshift-ansible installation...as far as unit files or configuration...nothing unique.

When the problem occurs, the nodes never rejoin. I've waited at least overnight.  That was the point where I filed this issue.  It restarts 5 times in rapid succession, then never retries again.

I fail to see what's unique about my setup where folks don't encounter this.  Perhaps I am the only one using 3.2 on bare metal?  Will ask around more internally.

**Comment by sdodson** [comment]
> @jeremyeder - just for completeness here...the rate limiting descriptions don't say they'll never restart the service, just that they'll prevent it from restarting within the specified interval after it hits the burst max.

I think this is what you're hitting, which was totally un-expected by me. From the StartLimitInterval section
```
Note that units which are configured for Restart= and which reach the start limit are not attempted to be restarted anymore; however, they may still be restarted manually at a later point, from which point on, the restart logic is again activated.
```
