### ISSUE TITLE
Hamburger menu doesn't work on error page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8198]
Clicking the menu does nothing:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13964049/561f858a-f03e-11e5-864c-b40e21cabc44.png)

/cc @jwforres @sg00dwin

**Comment by jwforres** [comment]
is this really only the error page? or any page that uses `<default-header>` ?

**Comment by spadgett** [comment]
@jwforres Only the error page I think.

**Comment by jwforres** [comment]
weird...
