### ISSUE TITLE
management console invalid kubernetes URL with external kubernetes

### ISSUE THREAD

**Issue by phemmer** [openshift/origin#820]
When using an external kubernetes (`openshift start --kubernetes=...`), the management console instructs the browser to contact kubernetes with invalid URLs. See the errors in the below screenshot.

Started as:
```
docker run \
  -d \
  --privileged \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --net=host \
 openshift/origin \
  start master \
  --kubernetes=http://localhost:8080 \
  --etcd=localhost
```

![image](https://cloud.githubusercontent.com/assets/1826947/5991258/cd44d3b2-a9af-11e4-9213-12c4718ee462.png)

So the javascript is telling the browser to use https, when kubernetes is running over http.
It also appears to be instructing the browser to use the hostname passed in `--kubernetes` when starting openshift. This may not be the appropriate address, as in this case, it's localhost, but from my browser's perspective, it shouldn't be localhost.

----

The solution to this might be the same as the solution to #813. If a kubernetes proxy is added, the browser can be instructed to contact openshift for everything. Since the openshift daemon handles both the management console, and the API, determining the address the browser needs to use becomes easy.

**Comment by smarterclayton** [comment]
@jwforres as we discussed today, I believe the solution is going to be the proxy.  Agree?

**Comment by phemmer** [comment]
One thing I noticed when I was running the simple proxy I mentioned on #813 is that websockets don't appear to work right. After sitting on the page for a while (5-10 min, cant recall exact time), the browser starts trying to get a websocket connection over and over. I haven't tried the code in #839, but the core of it basically identical, so it might suffer the same issue.

**Comment by smarterclayton** [comment]
All connections are terminated after 5 min - it's possible this is the corrupted http connection in the pool issue (we've hit it elsewhere).  If you get trace info let me know

**Comment by phemmer** [comment]
It looks like the reverse proxy is stripping the websocket headers (stuck a tcpdump between openshift & kubernetes), so kubernetes is receiving a plain http request, and is responding with 200.

![image](https://cloud.githubusercontent.com/assets/1826947/6015071/018f20d4-ab3e-11e4-8f9f-a329ad2d0e8c.png)

**Comment by jwforres** [comment]
@phemmer you need to also specify --public-kubernetes during openshift start if you expect the mgmt console to communicate with the kubernetes API on a different host than you specified for --kubernetes

**Comment by phemmer** [comment]
@jwforres does that mean you're against a proxy?

**Comment by jwforres** [comment]
No, just saying there is already a parameter in place to let you specify what the public-kubernetes URL should be and the web console will honor whatever its set to.  You may still need the proxy for auth reasons.

**Comment by smarterclayton** [comment]
I think with the proxy we won't need public-kubernetes anymore.  However, we'll leave it in until someone comes up with a reason not to have it.

----- Original Message -----

**Comment by smarterclayton** [comment]
@phemmer so basically the proxy needs to do upgrades?  @ncdc i knew we'd need it.

**Comment by ncdc** [comment]
@smarterclayton good thing I have that working in my PR :smiley:

**Comment by smarterclayton** [comment]
@ncdc breaking your upgrader out in a way we can consume it here would be good.

**Comment by ncdc** [comment]
@smarterclayton which is higher priority, https://github.com/GoogleCloudPlatform/kubernetes/pull/3763 completed with test cases etc, or a separate upstream PR just for the proxy upgrades?

**Comment by smarterclayton** [comment]
#924 should have resolved the websocket thing.

**Comment by smarterclayton** [comment]
Assigning to Derek since he's going to own making sure this keeps working, any bugs that need to be squashed will be 0.4.0 track

**Comment by smarterclayton** [comment]
Marking as provisionally fixed, reopen if you hit anything.
