### ISSUE TITLE
[Question] what's the way to specify the version of OpenShift in ansible

### ISSUE THREAD

**Issue by thincal** [openshift/origin#8205]
Is there any way to specify the version of OpenShift in ansible ? thanks.

**Comment by thincal** [comment]
#6229 is to modify the master-config.yaml after done ansible, but is there a way to specify it in the playbook scripts ?

**Comment by brenton** [comment]
Hi @thincal, you can set `openshift_pkg_version` as mentioned here: https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example#L182

**Comment by thincal** [comment]
@brenton thanks, it seems that this is only for debugging ?

also is that possible to specify where to pull the image during installing the OpenShift via. ansible ?
such as pulling from my private registry, for example: my.registry.com:5000/openshift/origin-pod:v1.1.4.

Since that you know the official registry is very slow in China, this way will speed up the OpenShift deployment.

Thanks again.

**Comment by brenton** [comment]
@thincal, `openshift_pkg_version` is not only for debugging.  You could say it's a slightly advanced feature but it's definitely supported.  As for you used 3rd party registries see: https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example#L66

**Comment by thincal** [comment]
that is cool，many thanks
