### ISSUE TITLE
Ran out of inotify watches when running many pods

### ISSUE THREAD

**Issue by jeremyeder** [openshift/origin#8209]
```
# sysctl -a|grep inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 8192
```

Mar 22 14:28:46 dell-r730-02.perf.lab.eng.rdu.redhat.com atomic-openshift-node[28414]: W0322 14:28:46.746575   28414 handler.go:562] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/system.slice/docker-2c7d28e2ae64bb12ded19fdc8edf1562d12e31451db9dd64b46c06e82dcafd56.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-2c7d28e2ae64bb12ded19fdc8edf1562d12e31451db9dd64b46c06e82dcafd56.scope: no space left on device

**Comment by brenton** [comment]
@jeremyeder, can you provide a little more context as to your recommendation?  Are these settings something that should be generally increased or do we need to provide knobs in the playbooks to tune these per environment?

**Comment by jeremyeder** [comment]
I hit this around 800 pods, higher than our supported limits.  We could document this if you like, or perhaps carry "inotify.max_user_watches = 65536" in the atomic-openshift-* tuned profiles.

**Comment by brenton** [comment]
I like the idea of putting it in the tuned profiles, though I'm worried that won't work for Atomic Host.  Documentation or having ansible do it might be the only option there.

**Comment by jeremyeder** [comment]
nah we're shipping profiles for atomic host, too. we can fix it in both
places.

On Mon, Mar 28, 2016 at 3:57 PM, Brenton Leanhardt <notifications@github.com
> wrote:

> I like the idea of putting it in the tuned profiles, though I'm worried
> that won't work for Atomic Host. Documentation or having ansible do it
> might be the only option there.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/8209#issuecomment-202558711>
>



-- 

-- Jeremy Eder

**Comment by brenton** [comment]
That works for me.  Are the atomic host tuned profiles based on https://github.com/openshift/origin/tree/master/contrib/tuned or would we work through another team to make the change?

**Comment by brenton** [comment]
Gently bumping this. @jeremyeder

**Comment by jeremyeder** [comment]
I totally forgot that you're carrying the openshift tuned profiles in origin.  Anyway, the atomic profiles are part of RHEL tuned package:  https://git.fedorahosted.org/cgit/tuned.git/tree/profiles Changes go through bugzilla.

https://bugzilla.redhat.com/show_bug.cgi?id=1322001

I sent a PR for the same change in Origin:  https://github.com/openshift/origin/issues/8276
