### ISSUE TITLE
Support for the '--exclude-from' options in 'oc rsync'

### ISSUE THREAD

**Issue by xcoulon** [openshift/origin#8223]
This is a follow-up on https://github.com/openshift/origin/pull/6351
The `oc rsync` command offers an `--exclude` option to exclude a single file/directory (or pattern), but the user can pass a single occurrence of the option. When multiple files/directories need to be excluded, the underlying `rsync` command offers the `--exclude-from=FILE` option, but this latter does not seem to be exposed in `oc rsync`. 
##### Version

oc v1.1.1.1
kubernetes v1.1.0-origin-1107-g4c8e6f4
##### Steps To Reproduce
1. Have a pod running with a NodeJS application for example
2. Attempt to run the `oc rsync` with the `--exclude-from=FILE` option.
   Eg:

> /usr/local/bin/oc rsync --user=openshift-dev --token=RpJmcQbWzYJzPQ1oK6fwVQ2hNg26mhrLk-78l0DpaIY --server=https://10.1.2.2:8443 --insecure-skip-tls-verify=true --exclude-from='/tmp/rsync-exclude'  nodejs-example-1-uewf5:/opt/app-root/src/ -n sample .
##### Current Result

> Error: unknown flag: --exclude-from

**Comment by csrwng** [comment]
We still need a solution to pass flags to the rsync command. However, #10245 doesn't seem to be the right approach. Maybe we can simply pass unrecognized flags through to rsync.

**Comment by jim-minter** [comment]
@xcoulon fyi, since you opened this issue, it is now possible to specify --include and --exclude multiple times on the oc command line (b3d5f9f53b847754c259191d87e69023f492a9b3).

@csrwng @bparees @smarterclayton @liggitt: AFAICS:
- allowing arbitrary flags for rsync after a '--' was turned down in #10245.
- we avoided adding --rsync-args= and its inevitable state machine or terrifying regexp in #6351.

how do you want to proceed?
1) implement --exclude-from= and --include-from= as first class citizens in oc?
2) revisit one of the options above
3) do nothing (maybe provide instructions for advanced users to use rsync --rsh= or whatever)
4) something else?

**Comment by bparees** [comment]
i vote for (1) or (3).

**Comment by jim-minter** [comment]
@bparees if you fancy narrowing that down, I'll get to work on it (or not).

**Comment by bparees** [comment]
@jim-minter i was hoping there would be other votes :)

given that this hasn't gotten any other requests, i'm inclined towards (3).  @xcoulon given that you can specify --exclude multiple times, is introducing an --exclude-from flag still critical for you?

**Comment by jim-minter** [comment]
Documented ability to use `rsync` as an alternative to `oc rsync` at https://github.com/openshift/openshift-docs/pull/3339 , closing.

**Comment by riverofjanuary** [comment]
> [@jim-minter](https://github.com/jim-minter) i was hoping there would be other votes :)
> 
> given that this hasn't gotten any other requests, i'm inclined towards (3). [@xcoulon](https://github.com/xcoulon) given that you can specify --exclude multiple times, is introducing an --exclude-from flag still critical for you?

hi there, i am VERY late to this conversation but am a developer who only recently has had their first interaction with the OC command line and specifically oc rsync. i am not seeing --exclude-from available when i run oc rsync --help; does this mean that (3) (do nothing) was the course of action, or is the instance at my client's install not have that exposed?

here's what i get when i run a valid rsync --exclude-from 'rsync-exclude.txt' command:

```
error: unknown flag: --exclude-from
See 'oc rsync --help' for usage.
```

**Comment by jim-minter** [comment]
Hi @riverofjanuary, yep, I don't think any further changes were made to `oc` in this area, but I documented that (at the time at least) you can use standard rsync as follows to get all of its command line option goodness: `rsync --rsh='oc rsh' --exclude-from=FILE SRC POD:DEST`

I don't know if that still works though (hopefully it does though!)

**Comment by riverofjanuary** [comment]
hi Jim thanks for the quick answer. I did see that in the documentation but I'm getting stdin/out errors while attempting this, so I'm unable to actually use it sadly, so I'm pulling in a ton of cruft I don't need in my project, arggg...
