### ISSUE TITLE
Update `oc status` analysis APIs to not require command names

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8226]
We should update:
- `kubeanalysis.FindRestartingPods`
- `deployanalysis.FindDeploymentConfigReadinessWarnings`

To assume the command names, _etc_, instead of requiring the pass-through.

/cc @kargakis @deads2k

**Comment by deads2k** [comment]
Or choose to go the other way and update the route markers.  Creating the patch command and only plumbing through half is weird.

**Comment by stevekuznetsov** [comment]
Not tech debt worth tackling right now.

/close
