### ISSUE TITLE
Update `oc status` Nodes to not Embed Objects

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8227]
We should (??) refactor our node structs in order to not embed the objecty they encompass, so that the `Object()` methods are obsolete.

Potential downside: `node.Name` won't work anymore, but I think that's OK as it will be clearer.

/cc @kargakis @deads2k

**Comment by deads2k** [comment]
I don't like anonymously included structs.

**Comment by stevekuznetsov** [comment]
Not tech debt worth tackling at this point.

/close
