### ISSUE TITLE
update the sample-app template using emptyDir volume

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#8236]
[provide a description of the issue]
we should add volume declaration using emptyDir for the templates under https://github.com/openshift/origin/tree/master/examples/sample-app, currently we have feature not alow the user to using docker volume directly 
##### Version
[provide output of the `openshift version` or `oc version` command]

##### Steps To Reproduce
1. Disable using docker volume
2. Create app using the template under https://github.com/openshift/origin/tree/master/examples/sample-app
3. check the pod status
##### Current Result
db pod cannot startup
##### Expected Result
db pod should startup successfully

**Comment by wzheng1** [comment]
Above issue is due to this bug https://bugzilla.redhat.com/show_bug.cgi?id=1318542, there is no volume for the sample templates. So if Online user wanna to use sample templates, it will be failed.
