### ISSUE TITLE
Trouble creating pods source 2 image

### ISSUE THREAD

**Issue by zmhassan** [openshift/origin#8254]
I'm finding that when ever I create a new application even if I try the quickstarts it fails. It will start the build then eventually fail.

##### Version
[provide output of the `openshift version` or `oc version` command]
Openshift Origin version 3.1 (latest)
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75

##### Steps To Reproduce
login to the webconsole: https://hostname:8443/console.
click create new project
click nodejs-mongodb-example

##### Current Result
build always fails

##### Expected Result
Build should have succeeded but its not working for me.

##### Additional Information
I ran $ oc get all -o json output is attached below:
[origin-diagnostic.txt](https://github.com/openshift/origin/files/190781/origin-diagnostic.txt)

**Comment by bparees** [comment]
Do you have logs from the build?

**Comment by zmhassan** [comment]
I've opened a separate issue since I got passed the cgroup problem:
https://github.com/openshift/openshift-sdn/issues/275

Now its a network issue.

**Comment by bparees** [comment]
ok, closing this.
