### ISSUE TITLE
Deployment rollback mismatch

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8256]
Everytime there is a manual rolliback (oc rollback), we register a new deployment version and everyone is happy. On failed deployments, we just scale up the latest complete. The erroneous configuration though continues to exist as part of the deployment config and there is a mismatch between the active deployment and the dc template. Shouldn't we update the dc to the latest complete deployment template, and have it run a new deployment every time? In this way, the latest deployment will always be the active deployment and I think we will be able to remove all the hacks we do in the deploymentconfig controller for backwards compatibility.

cc: @smarterclayton @ironcladlou

**Comment by kargakis** [comment]
> The erroneous configuration though continues to exist as part of the deployment config and there is a mismatch between the active deployment and the dc template. 

Depending on the pov, this means that `oc deploy --latest` on deployments rolled back by the controller is broken. I expect that --latest is a redeployment of what I am already running, but it can also mean the current configuration which is different in this case.

**Comment by smarterclayton** [comment]
We cannot update the DC on failure - that's the users reposibility

**Comment by smarterclayton** [comment]
We can't overwrite user intent except on something like rollback.

**Comment by kargakis** [comment]
I see - it will be interesting moving this upstream.
