### ISSUE TITLE
Extra space in header at mobile for extension point

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8262]
1.3 only.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/14083285/cb3e87c8-f4e2-11e5-84e4-1737e28512bf.png)

/cc @jwforres @sg00dwin @benjaminapetersen

**Comment by benjaminapetersen** [comment]
Hmm. Initial thought is that the extension point needs to publish out the # of extension items rendered via an attribute so that we can `ng-show` the parent node. Something like:

```html
    <div 
      row
      ng-show="count"
      extension-point
      extension-name="nav-system-status-mobile"
      extension-types="dom"
      extension-count="count"
      class="navbar-flex-btn"></div>
```
Or, perhaps better is just to use CSS:

```sass
// hide it if it has no children?
.sometimes-hidden:empty {
  display: none;
}
```
@sg00dwin preference?

**Comment by sg00dwin** [comment]
@benjaminapetersen if when navbar-flex-btn has no children it is devoid of whitespace then the css option should work. But it might be better to use ng-show to ensure it hides.

**Comment by spadgett** [comment]
My only hesitation with the CSS solution is if someone adds a newline or any whitespace to the extension div in the markup, it will show up. For instance, this would still appear even with the `:empty` rule.

```html
<div 
      row
      class="sometimes-hidden"
      ng-show="count"
      extension-point
      extension-name="nav-system-status-mobile"
      extension-types="dom"
      extension-count="count"
      class="navbar-flex-btn">
</div>
```

**Comment by spadgett** [comment]
I'm looking at https://developer.mozilla.org/en-US/docs/Web/CSS/:empty. Maybe it happens only if there's a comment, though.

**Comment by benjaminapetersen** [comment]
Hmm.  Yeah, I'd love the more elegant css solution, seems theoretically the right fix, but I think it won't work well enough.  I'll look at adding `extension-count` or something like that to the `extension-point` directive so we can `ng-show`, `ng-hide` or `ng-class` based on the value of that attribute.

**Comment by spadgett** [comment]
I'm fine with `:empty`. I wish we could set it in the directive somehow, but I don't think it would work without `replace: true`.

**Comment by benjaminapetersen** [comment]
Looking at [the extension registry plugin](https://github.com/openshift/angular-extension-registry/blob/master/src/directives/extension-point.js#L35). There may be a simple fix:

```javascript
// 
 .then(function(items) {
   // this runs when the directive loads & whenever data for the extension changes:
   $elem.html('');   // update this to  $elem.empty();
   each(items, function(item) {
```
`$elem.html('')` and `$elem.emtpy()` are pretty similar, I'm digging to see if that update is necessary.  Either way, I think the directive itself will initially clean itself out of extra whitespace, text, etc.

**Comment by benjaminapetersen** [comment]
@sg00dwin the scollbars fix recently may have caused an issue with the online extension, I'm finding the icon overlapping:

![screen shot 2016-03-29 at 2 52 46 pm](https://cloud.githubusercontent.com/assets/280512/14119814/fbeb4aec-f5bd-11e5-9d65-c7a70b4ee0c5.png)

**Comment by sg00dwin** [comment]
@benjaminapetersen hrm... I'd need to see the markup to figure out what the culprit is.

**Comment by spadgett** [comment]
Created #8290 for the scrollbar problem in case we want to address for 1.2. Let me know if it's 1.3 only.

**Comment by spadgett** [comment]
When the extension is installed, is that empty space always there on mobile? Or does it only show up when there is an incident?

**Comment by benjaminapetersen** [comment]
I believe the space should only show if *any* extension renders into it, currently we ourselves are only using it for the incident icon.

**Comment by spadgett** [comment]
I'm still not sure if it will show up :) Looks like we return a element with `style: none;` in online-extensions.js when there are no incidents.

**Comment by benjaminapetersen** [comment]
Potential separate issue to open ~ Should the system-status call poll?  Or are we good with it running once only?

**Comment by jwforres** [comment]
i'd rather only call out to that once, there is a permanent link for system
status in the help

**Comment by spadgett** [comment]
Fixed by https://github.com/jwforres/origin/pull/49
