### ISSUE TITLE
Web console: runtime errors that appear only when built

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#8264]
1.3 only.

Check the screenshot, I ran into these only when I rebuilt & accessed via `https://localhost:8443/console/`.  I'm guessing it is an ordering issue after minification, but would need to dig around more to see.

![screen shot 2016-03-28 at 1 58 33 pm](https://cloud.githubusercontent.com/assets/280512/14085344/4ab8711c-f4ed-11e5-85cf-4ec83d6014a4.png)

@jwforres @spadgett

**Comment by spadgett** [comment]
No longer a problem. I believe it was fixed by https://github.com/jwforres/origin/pull/27
