### ISSUE TITLE
allow custom service proxy container implementations to be configured/specified on a service 

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#828]
the [kubernetes service model](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md) is awesome. However it'd be very handy to be able to configure on a per service basis the container image to be used to implement the load balancing and proxying.

e.g. a container image could implement a custom proxying or load balancing algorithm; implementing a master election or sharding algorithm.

We could then configure to the container image/config in the service JSON when we create the service.

Then for each container using a specific service, when the ip tables rules kick in on the local node, the kubelet (or whatever) would create a local custom proxy container to listen on the service port to perform the actual load balancing.

So its a case of either the service being configured to opt out of the generic service proxy; or for the service-proxy to delegate to a secondary local container to do the discovery/load balancing.

A few different use cases for this kind of thing are:
- implementing [Hystrix](https://github.com/Netflix/Hystrix) style features for HTTP services (metrics, logging, caching, fallback services, custom retry handling etc)
- ActiveMQ gateway destination sharding (allowing different brokers to deal with different queue/topic shards without having to double-hop from node -> gateway node -> broker)
- custom load balancing strategies

**Comment by jstrachan** [comment]
Incidentally folks could obviously work around this by either 

* adding the 'custom service proxy container' inside a Pod and not using the underlying Service directly
* write another service for the 'custom proxy' which then delegates to the original service; then there's 2 services in kubernetes.

Both of those options would work fine today. However in terms of making things easy to develop and understand, configuring the custom service proxy inside the Service itself seems the cleanest and most elegant thing to do. The service then wraps up the proxy logic into a simple atomic unit and it also avoids folks accidentally talking direct to the underlying service. 

Also if the custom service proxy was implementing custom validation, security or rate limiting inside the proxy - then it'd be ideal to avoid it being possible to bypass the proxy and access the underlying service directly.

Finally another interesting idea; using a custom service proxy could be a nice way to add external services into kubernetes. e.g. accessing some third party service not hosted inside kubernetes but which could have custom security, discovery mechanisms, rate limiting and whatnot; the custom service proxy could wrap up all that logic. Then from developers; each pod just accesses all services, internal or external, in the same way - as kubernetes services.

**Comment by Morriz** [comment]
Is this still being watched? Would love to see such features end up in kubernetes, abstracting away such a possible in-pod proxy container proxy, so it would just expose new configuration on a service.

**Comment by jstrachan** [comment]
BTW I raised an issue upstream in kubernetes around how to easily enable an in-pod container proxy:
https://github.com/kubernetes/kubernetes/issues/25961

as thats one of the biggest gaps so far.

From what I've seen so far Envoy looks a really good possible implementation of the in-pod container proxy: https://lyft.github.io/envoy/
