### ISSUE TITLE
`oadm registry --credentials` drops service account name

### ISSUE THREAD

**Issue by gt-tech** [openshift/origin#8285]
I have followed instructions from here - 

https://docs.openshift.org/latest/install_config/install/advanced_install.html#running-the-advanced-installation for openshift installation where I have 2 nodes and master is one of those 2 nodes.

I am attempting to start a docker registry using command -

sudo oadm registry --service-account=registry --config=/etc/origin/master/admin.kubeconfig --credentials=/etc/origin/master/openshift-registry.kubeconfig --mount-host=/var/openshift-docker-registry-storage

/var/openshift-docker-registry-storage has 777 permissions and I have also tried making 1001 owner of it.

I have also disabled SELinux completely to rule if it's playing up.

"registry" service account is allowed to run privileged containers by executing command 
oadm policy add-scc-to-user privileged registry and this was done before oadm registry .... command was executed.

Docker registry always failed to start with error that's described here -
https://bugzilla.redhat.com/show_bug.cgi?id=1238954

##### Version
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75

##### Steps To Reproduce
1. Creating docker registry by following steps from here using --mount-host https://docs.openshift.org/latest/install_config/install/docker_registry.html#deploy-registry

##### Current Result
registry POD times out stating unable to scale and timedout on condition 

##### Expected Result
registry POD should startup successfully.

**Comment by liggitt** [comment]
The `add-scc-to-user` command should specify the service account's user name. Fixed the docs in https://github.com/openshift/openshift-docs/pull/1840, but the correct command should be 
```
oadm policy add-scc-to-user privileged system:serviceaccount:default:registry
```

**Comment by gt-tech** [comment]
thanks, i corrected the command and dropped current objects and recreated the registry, still same error

```
I0330 03:45:22.273730       1 deployer.go:199] Deploying default/docker-registry-1 for the first time (replicas: 1)
I0330 03:45:22.281882       1 recreate.go:126] Scaling default/docker-registry-1 to 1 before performing acceptance check
F0330 03:47:23.315526       1 deployer.go:69] couldn't scale default/docker-registry-1 to 1: timed out waiting for the condition


```

**Comment by gt-tech** [comment]
`oc edit scc privileged` output is
```
users:
- system:serviceaccount:openshift-infra:build-controller
- system:serviceaccount:management-infra:management-admin
- system:serviceaccount:management-infra:inspector-admin
- system:serviceaccount:default:router
- system:serviceaccount:default:registry

```

**Comment by sudhaker** [comment]
I'm able to re-produce this on 1.1.5 as well. Error goes away if I don't specify _**--mount-host=/opt/openshift-registry**_

> oadm registry --credentials=$OPENSHIFT/openshift.local.config/master/openshift-registry.kubeconfig --service-account=registry --mount-host=/opt/openshift-registry

E0330 01:45:42.492379    1583 replication_controller.go:442] unable to create pods: pods "docker-registry-1-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
I0330 01:45:42.493173    1583 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"docker-registry-1", UID:"78952836-f63a-11e5-ba8d-000c295d9a6d", APIVersion:"v1", ResourceVersion:"403", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "docker-registry-1-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]

**Comment by liggitt** [comment]
can you make sure you are creating the registry in the default namespace (add `-n default` to the `oadm registry` command)

**Comment by sudhaker** [comment]
I could see in the web-console that registry creation happened in "default" namespace.

Here are the steps that I followed from scratch - http://sudhaker.com/10/install-the-latest-openshift-v3-on-centos-7-1

**Comment by liggitt** [comment]
can you provide the output of these commands:
```
oc get scc -o yaml
oc get dc,rc -o yaml -n default
```

**Comment by sudhaker** [comment]
[scc-yml.txt](https://github.com/openshift/origin/files/195541/scc-yml.txt)
[dc-rc-yml.txt](https://github.com/openshift/origin/files/195542/dc-rc-yml.txt)

**Comment by liggitt** [comment]
looks like passing `--credentials` prevents `serviceAccount` from being set in the DC, which is a bug. You don't actually need to pass `--credentials` any more, the service account can be used for everything.

I'll get in a fix for the serviceAccount missing from the dc, but you can simply remove `--credentials` to get it working again

**Comment by gt-tech** [comment]
that made it work for me ... thanks!

**Comment by liggitt** [comment]
glad it worked, I'll leave this open to track the issue until #8296 merges

**Comment by sudhaker** [comment]
Awesome! Even 'oadm router' doesn't need credentials anymore.

**Comment by gt-tech** [comment]
Having a problem that I am sure is with syntax of how i am trying to create service account and then configuring it to have right to run privileged containers.

In nut-shell when I run below command, docker registry comes up just fine (i am using "registry" account that gets created with default ansible install scripts and have the right privileges

`oadm registry --service-account=registry --config=/etc/origin/master/admin.kubeconfig --mount-host=/var/openshift-docker-registry-storage --selector="custom_id=node1"
`

But when I try to create a separate account by using following commands - I still get timed out error, not sure what's wrong with syntax of first 2 commands or is it something else -

```
echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"gt-registry"}}' | oc create -n default -f -

oadm policy add-scc-to-user privileged system:serviceaccount:default:gt-registry

oadm registry --service-account=gt-registry --config=/etc/origin/master/admin.kubeconfig --mount-host=/var/openshift-docker-registry-storage --selector="custom_id=node1"
```

**Comment by liggitt** [comment]
you don't need to create the service account yourself any more... `oadm registry` will do that for you if you aren't providing `--credentials`

make sure you are creating the registry in the default namespace

does `oc status -n default` or `oc describe dc registry` show any details about the failed deployment?

**Comment by gt-tech** [comment]
[dc.txt](https://github.com/openshift/origin/files/201022/dc.txt)
[service.txt](https://github.com/openshift/origin/files/201023/service.txt)

For now I am using the "registry" account that `oadm registry` creates on it's own when invoked as you said without `--credentials` and it seems to be working fine!
