### ISSUE TITLE
Scrollbar overlaps system status icon on mobile (online extension)

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8290]
![screen shot 2016-03-29 at 2 52 46 pm](https://cloud.githubusercontent.com/assets/280512/14119814/fbeb4aec-f5bd-11e5-9d65-c7a70b4ee0c5.png)

See https://github.com/openshift/origin/issues/8262#issuecomment-203048698

/cc @benjaminapetersen @jwforres @sg00dwin

**Comment by benjaminapetersen** [comment]
I believe I have this solved via some tinkering with #8262 and will fix both when I push the PR shortly.

**Comment by spadgett** [comment]
@benjaminapetersen Do you know if it's a problem in 1.2 or 1.3 only?

**Comment by benjaminapetersen** [comment]
@spadgett is really neither, can disregard.  I created it while trying a few different fixes for #8262.  Realized when rolling back one of my potential fixes it was resolved.
