### ISSUE TITLE
make generated kubeconfig files read-only

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#8291]
The generated kubeconfig files should be read-only.  It will prevent problems like: "I logged in and now my system:admin kubeconfig file is broken!".  It will stop anyone from using that file to switch projects, but I think I'm willing to sacrifice that ability to prevent accidents.

@liggitt are you against?
@legionus do you have bandwidth to take this?  We generate several kubeconfig files during `openshift start` down under `openshift.local.config/master/`

**Comment by liggitt** [comment]
> @liggitt are you against?

not strongly... I'd want to make sure `oc login` fails in a comprehensible way when the kubeconfig is not writeable

**Comment by legionus** [comment]
> @legionus do you have bandwidth to take this? 
I need to fix #7792 first.

**Comment by legionus** [comment]
> I'd want to make sure oc login fails in a comprehensible way when the kubeconfig is not writeable

right now it falls:
```
$ oc whoami 
system:admin

$ oc project
Using project "default" on server "https://10.34.129.157:8443".

$ oc login 
Authentication required for https://10.34.129.157:8443 (openshift)
Username: tmp
Password: 
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * openshift (current)
  * tmp

Using project "openshift".
error: open /home/legion/go/src/github.com/openshift/origin/openshift.local.config/master/admin.kubeconfig: permission denied

$ oc whoami 
system:admin

$ oc project
Using project "default" on server "https://10.34.129.157:8443".
```

**Comment by deads2k** [comment]
> right now it falls:

Failing is fine, but we probably want it to fail early instead of late with a pretty message that explains what's wrong.

If we find `system:admin` as the user, we should probably warn them against simply changing file permissions and suggest something like setting the `KUBECONFIG` env var or asking if they've accidentally signed in as root.

**Comment by legionus** [comment]
That is the message fits?
```
$ oc login -u tmp
Config file is not writable. Please do not change the permissions on the system configuration files. Use KUBECONFIG to set writable file.
```
We can't check user  for `system:admin` because we don't have config file at early stage.

**Comment by liggitt** [comment]
I'd prefer something like this:
```
The kubeconfig file /path/to/file is not writable.
Specify a writeable path with --config or by setting $KUBECONFIG.
```

**Comment by legionus** [comment]
@bparees ping

**Comment by bparees** [comment]
round and round it goes, where it stops, nobody knows!  but this isn't @legionus' area anymore, so sending back to the master team.
