### ISSUE TITLE
test/cmd/triggers.sh:40: error: buildconfigs "ruby-hello-world" cannot be updated

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#8303]
Flake seen in https://github.com/openshift/origin/pull/8286
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/13773/console
```
FAILURE after 0.129s: test/cmd/triggers.sh:40: executing 'oc set triggers bc/ruby-hello-world --remove-all' expecting success and text 'updated': the command returned the wrong error code
There was no output from the command.
Standard error from the command:
error: buildconfigs "ruby-hello-world" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
```

`set triggers` is already using patch...

**Comment by bparees** [comment]
guessing this means there was a build running and the running build updated the BC(eg to set an imageid or a lastVersion value) right while this set was happening.

**Comment by liggitt** [comment]
That command is already using patch, so it would have to conflict 5 times to fail. Do we expect to be updating that many times that rapidly?

**Comment by bparees** [comment]
i don't think so...

**Comment by bparees** [comment]
you're saying patch re-gets and retries the patch operation 5 times when it hits conflicts?

**Comment by liggitt** [comment]
Yes

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L551

**Comment by smarterclayton** [comment]
@liggitt did we fix this or change in any way?

**Comment by liggitt** [comment]
not that I know of

**Comment by bparees** [comment]
no one else has reported this since it was opened at the end of march, closing based on unfounded optimism that the problem has gone away.
