### ISSUE TITLE
Issues from using object schemas to validate range of OpenShift configurations.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#8310]
Bringing this across from aos-devel.

In doing experimentation with object schemas at:
- https://github.com/openshift/origin/tree/master/api/swagger-spec

I have found that when using the schemas to validate some available configuration files that work fine with OpenShift when loaded using `oc create`, that the schema flags them as invalid. This is because the schema is indicating various fields are required, when in practice that doesn't seem to be the case.

The list of fields in the schema marked as required, but that appear do not actually appear to be required, are:
- v1.BuildConfig - status
- v1.BuildSource - secrets
- v1.DeploymentConfig - status
- v1.DeploymentConfigSpec - test, strategy
- v1.ImageStream - spec
- v1.Route - status
- v1.RouteSpec - host
- v1.TagReference - annotations, generation

When validating templates in `openshift` namespace that come with the Origin all-in-one VM, the following fields occur which are not actually in the schema for the specific configuration type.
- v1.Container - capabilities # appears in at least `datagrid65-basic` template
- v1.Route - id # appears in `jenkins-ephemeral` and others

There also appear to be some poorly defined type structures.

One example of this is PersistentVolumeAccessMode:

```
   "v1.PersistentVolumeAccessMode": {
    "id": "v1.PersistentVolumeAccessMode",
    "properties": {}
   },
```

This is referenced in PersistentVolumeClaimSpec as:

```
     "accessModes": {
      "type": "array",
      "items": {
       "$ref": "v1.PersistentVolumeAccessMode"
      },
```

You don't ultimately have any type information here and anything trying to programmatically use the schemas is going to have an issue with this unless you make an assumption that a definition with no properties is in fact a literal, although you aren't going to know what the type is.

In this case it should perhaps be:

```
     "accessModes": {
      "type": "array",
      "items": {
       "type": "string"
      },
```

which matches actual usage such as:

```
            "accessModes": [
              "ReadWriteOnce"
            ],
```

List of these have found is:
- v1.Capabilities - drop
- v1.PersistentVolumeClaimSpec - accessModes

@smarterclayton indicated on aos-devel that issues stem form Swagger 1.2 and that 2.0 when used may help, but with required flags right now not necessarily being trustable. Asked that any suspected issues be logged as issue for now for dealing with later.

**Comment by GrahamDumpleton** [comment]
More fields marked as required which likely aren't:

* v1.RouteTargetReference - weight

**Comment by smarterclayton** [comment]
Weight is required, but it is defaulted.

**Comment by GrahamDumpleton** [comment]
Which is what I mean. As far as validating what a client sends, it doesn't need to be there because is given default value. If the swagger schema is saying what is required from the perspective of the server and not the client, then that is a pain, as validating client still needs to pass stuff that isn't necessary as the server would fill it in.

**Comment by smarterclayton** [comment]
Yeah, they should be tagged omitempty

**Comment by smarterclayton** [comment]
For the fields we can't mark omit empty (because of swagger).  I'm going to track this in the near term with https://github.com/kubernetes/kubernetes/issues/25460

**Comment by GrahamDumpleton** [comment]
Going to close this since things moved to new swagger version. Will create new issue if when validating later still find issues.
