### ISSUE TITLE
HowTime Zone

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#8311]
Hi,
I have a question when i use openshift(s2i),i make the Time Zone to Asia/Shanghai.but the log time always is the default time zone，how can i do for this?
![quester](https://cloud.githubusercontent.com/assets/12937669/14172095/f40e5614-f768-11e5-8eb5-b191bff1eb3c.jpg)
![quester-2](https://cloud.githubusercontent.com/assets/12937669/14172117/0fbbd206-f769-11e5-8974-52d03c7ef960.jpg)
if i want all the images of openshift(such as registry\metric\logging\s2i) is use Asia/Shanghai,can  we achieve in openshift?
thanks!

**Comment by bparees** [comment]
I'm guessing that's coming from the image's locale configuration, you could try setting the TZ env variables on the deployment config for the component in question and re-deploying it, depending whether the runtime for the given image respects that env variable, you might get what you want.

It would be nice if that variable were set by default based on the host values.

**Comment by wenskys** [comment]
thanks，i use "-Duser.timezone=GMT+08" in tomcat，and it is ok.
