### ISSUE TITLE
improve displayed error for oadm create-node-config

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#8312]
If you try to create a new node-config and specify manually the paths to your certificates (with no $CURL_CA_BUNDLE) the command will fail with a useless error.

```
[vagrant@origindevel ~]$ oadm create-node-config \
--signer-serial=/opt/openshift.local.config/master/ca.serial.txt \
--signer-key=/opt/openshift.local.config/master/ca.key \
--signer-cert=/opt/openshift.local.config/master/ca.crt \
--certificate-authority=/opt/openshift.local.config/master/ca.crt \
--node-dir=/opt/openshift.local.config/node-origin.thecodeflavour.org/  \ --hostnames=origin.thecodeflavour.org,127.0.0.1  \
--node=origin.thecodeflavour.org 
Generating node credentials ...
error: open openshift.local.config/master/ca.crt: no such file or directory
```

The above fails because i didn't specify the `--node-client-certificate-authority` flag, but it should let me know that instead of just telling me it couldn't open a file.

i'm also not sure if it's good for oadm to assume i'm issuing the command from the same directory where i have my openshift.local.config folder. Whenever i don't specify any of the flags above, such as `--signer-serial` `--signer-key`, etc. oadm will look in `$(pwd)/openshift.local.config/master/` for the certificates.

**Comment by Miciah** [comment]
Looks like https://bugzilla.redhat.com/show_bug.cgi?id=1259913

**Comment by PI-Victor** [comment]
closing this in favor of https://github.com/openshift/origin/issues/9519
