### ISSUE TITLE
support secured registries when importing-images with "oc import-image"

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#8314]
If I want to import an image with "oc import-image" but the image is secured I can not provide credentials in any way.

##### Version
oc v1.1.4-320-g847f337

**Comment by pweil-** [comment]
@jorgemoralespou using secrets for image import is new to 1.2.  [If you set up the secret](https://docs.openshift.org/latest/architecture/core_concepts/builds_and_image_streams.html#private-registries) it should work with the import-image command.

**Comment by jorgemoralespou** [comment]
@pweil- 

So let me understand it better.
If I do an "oc image-import IS --confirm" which will pull down the image and create the IS, it will work if I create a dockercfg secret for that server in current namespace? If that's the case, then I'm happy.

Cheers,

**Comment by pweil-** [comment]
Yes, you should be able to set up the secret then proceed to run an import-image command.  OpenShift will then look for pull secrets in the namespace and attempt to use them to authenticate to the registry.
