### ISSUE TITLE
Precalculate replicas for a new deployment

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8315]
The deploymentconfig controller is currently minting zero-replica deployments which are:
1. Handed to the deployment controller. The deployment controller will create a deployer pod for each new deployment.
2. The deployer will get the new deployment and eventually scale it up.

This flow can be optimized. The deployment config controller can consolidate all old replicas and create a new deployment with (dc.Spec.Replicas+maxSurge-oldReplicas) replicas. Actually this already happens in the upstream controller. Then we can 1) stop delegating to the recreate strategy for every first rolling deployment and 2) I  think hacks like [this](https://github.com/openshift/origin/blob/799d2a44f59d6ebe80a4ee09f06c13cde180fef1/pkg/deploy/strategy/rolling/rolling.go#L188-L195) are already unnecessary, will become more obsolete after this issue gets fixed.

cc: @ironcladlou @smarterclayton

**Comment by ironcladlou** [comment]
Would that break pre-hooks?

**Comment by kargakis** [comment]
> Would that break pre-hooks?

Hm, right. Would it be a killer if the deployer listed all pods for a DC, did what I am proposing here, and scaled up the deployment before handing it to the rolling updater?

ps. adding hooks upstream is bound to be interesting

**Comment by smarterclayton** [comment]
If pre-hooks are set they have to work.  If you don't have pre-hook, then
we should fall into this.

Ultimately, we want hooks to alter both flows, not just ours.

**Comment by kargakis** [comment]
This also breaks canary deployments. I think we will need to remove it from upstream eventually.
