### ISSUE TITLE
Calico-CNI integration with OpenShift failed

### ISSUE THREAD

**Issue by xuant** [openshift/origin#8321]
I was able to deploy Kubernetes on CentOS 7 with Calico-CNI plugin.
What you need to do to make Calico-CNI plugin work for Kubernetes is to:
a) set up the calico network
b) put Calico-CNI plugins, `calico` and `calico-ipam` (both executables) into `/opt/cni/bin`
c) create a file `/opt/cni/net.d/10-calico.conf` with the following content:
```
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_authority": "<KUBERNETES_MASTER>:6666",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    }
}
```
d) start kubelet with the following content with command flag `--network-plugin` and `--network-plugin-dir`:
```
/usr/bin/kubelet \
--address=0.0.0.0 \
--allow-privileged=true \
--cluster-dns=10.100.0.10 \
--cluster-domain=cluster.local \
--config=/etc/kubernetes/manifests \
--hostname-override=${DEFAULT_IPV4} \
--api-servers=https://${KUBERNETES_MASTER}:443 \
--kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
--tls-private-key-file=/etc/kubernetes/ssl/worker-key.pem \
--tls-cert-file=/etc/kubernetes/ssl/worker.pem \
--logtostderr=true \
--network-plugin=cni \
--network-plugin-dir=/etc/cni/net.d
Restart=always
RestartSec=10
```

For OpenShift, I pretty much did the same thing. I put `calico` and `calico-ipam` in `/opt/cni/bin/`. But OpenShift does not provide `--network-plugin-dir` so I put the `10-calico.conf` in `/usr/libexec/kubernetes/kubelet-plugins/net/exec/` according to https://github.com/openshift/openshift-sdn/blob/master/ISOLATION.md#openshift-sdn-kubernetes-plugin. ` /usr/libexec/kubernetes/kubelet-plugins/net/exec/` is also the default value for `--network-plugin-dir` in Kubernetes.

Good thing is running `oc get nodes` show me `Ready` for all nodes. Bad thing is a pod will never spin up. 

What is the step that I did wrong or did I miss any step?

##### Version
```
$ oc version
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75
```

**Comment by rajatchopra** [comment]
You must have done it, but just making sure.. you called openshift on the node with --network-plugin=cni, right?
Also, grab the logs from openshift-node please.

**Comment by xuant** [comment]
@rajatchopra 
Yeah, I used --network-plugin=cni.
While I run nginx using `oc run`, the deployer always fail.
```
F0405 22:37:19.884069       1 deployer.go:70] couldn't get deployment default/mynginx-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/mynginx-1: dial tcp 172.30.0.1:443: i/o timeout
```


With log of the node:
```
Apr 05 22:36:49 os-b6901 origin-node[39119]: E0405 22:36:49.217705   39119 manager.go:309] NetworkPlugin cni failed on the status hook for pod 'mynginx-1-deploy' - invalid CIDR address: Device "eth0" does not exist.
Apr 05 22:31:24 os-b6901 origin-node[39119]: W0405 22:31:24.051903   39119 kubelet.go:1995] Orphaned volume "6baaeab4-fb75-11e5-96a6-0288e417a3e1/deployer-token-hqlcq" found, tearing down volume
Apr 05 22:31:24 os-b6901 origin-node[39119]: W0405 22:31:24.046893   39119 kubelet.go:1995] Orphaned volume "69f5cc09-fb7c-11e5-96a6-0288e417a3e1/deployer-token-hqlcq" found, tearing down volume
Apr 05 22:31:22 os-b6901 origin-node[39119]: W0405 22:31:22.833579   39119 manager.go:408] Failed to update status for pod "_()": pods "mynginx-1-deploy" not found
Apr 05 22:30:48 os-b6901 origin-node[39119]: E0405 22:30:48.502132   39119 manager.go:309] NetworkPlugin cni failed on the status hook for pod 'mytomcat-1-deploy' - invalid CIDR address: Device "eth0" does not exist.
```

Do I need to configure CIDR also in node-config.yaml or somewhere? (For kubernetes, I don't remember doing this.) Here are the network config in master-config.yaml and node-config.yaml:
```
$ cat master-config.yaml
...
networkConfig:
  clusterNetworkCIDR: 10.128.0.0/14
  externalIPNetworkCIDRs: null
  hostSubnetLength: 9
  networkPluginName: ""
  serviceNetworkCIDR: 172.30.0.0/16
...

// Node is on a different machine

$ cat node-config.yaml
...
networkConfig:
  mtu: 1450
  networkPluginName: cni
...
```

**Comment by rajatchopra** [comment]
The cni plugin asks docker runtime to get the IP address of the pod (through the status call). And that seems to be returning something spurious. Does your CNI plugin get called with the ADD command? Try running openshift with loglevel 5 or something and you will see messages from this portion of the code: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/cni/cni.go#L163


Meanwhile, CIDR options on master config are useless if the networkPluginName is cni, so ignore that.

**Comment by xuant** [comment]
@rajatchopra 
I got this with loglevel=5:
```
cni.go:182] About to run with conf.Network.Type=calico, c.Path=[/opt/cni/bin /opt/calico/bin]
```

**Comment by rajatchopra** [comment]
Right, so the failure is with the status call. Looks like the 'ADD' call really did not construct the 'eth0' interface. Debug the ADD call to the cni script, possibly?

**Comment by xuant** [comment]
@rajatchopra how to debug that?

**Comment by rajatchopra** [comment]
I meant to debug the executable 'calico' and 'calico-ipam'. Do they end up creating the correct interface on the container? If its a python/shell script then add some debug statements and echo stuff into a a temp file maybe.

And the message you see in logs is from the 'DEL' call, do you see it getting called for 'ADD'?

**Comment by xuant** [comment]
@rajatchopra 
I just started working on network plugin but yeah I'll try to write some test for the scripts.

I noticed that for the working Kubernetes cluster, I can create a running pod but still noticed the error `manager.go:309] NetworkPlugin cni failed on the status hook for pod 'mytomcat-b5qco' - invalid CIDR address: Device "eth0" does not exist.`. Is it something I should be aware of?

**Comment by rajatchopra** [comment]
Can you see the pod's IP address through kubectl in the kubernetes setup? If not its a problem.
You can also see the insides of the pod possibly and see if everything is correctly configured. Get the pid of the infra container and use 'nsenter' to see if kube api server is reachable.

**Comment by xuant** [comment]
@rajatchopra 

Yeah, I can see IP addresses using kubectl in the working Kubernetes cluster and also using oc in the not-working OpenShift cluster.

I tried `docker run -it centos /bin/bash` on both the working and not-working cluster nodes. I was able to connect to the api-services on both cluster.

However, on the not-working OpenShift cluster, during the 30sec running time of the deployer, I tried executing `curl` against the apiserver and I DID get a timeout, which means the deployer didn't catch the network. I think that's also the reason why I got `couldn't get deployment default/mynginx-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/mynginx-1: dial tcp 172.30.0.1:443: i/o timeout`.

Any idea why a normal docker container can connect to the apiserver but the deployer cannot?

**Comment by xuant** [comment]
I tried deploying a pod from a json file using `oc create -f mysql.json`, the pod was able to run. It seems that the problem is from the deployer of OpenShift.

**Comment by rajatchopra** [comment]
The deployer pod is not any special one with respect to the network. Try reaching out to the internet from the deployer pod? ping google.com or something.

Also, when you do 'docker run -it centos /bin/bash' you are not using the calico plugin apparently. Its not a pod. From the mysql pod, can you reach the apiserver?

**Comment by xuant** [comment]
@rajatchopra 
No, it cannot reach the api-server :(
Even for the Kubernetes cluster, the running pod cannot reach the apiserver. So there must be something wrong with the way I deploy the cluster.
I'm following this tutorial: http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/
I used Centos7 instead of Ubuntu15.04 since they both use systemd. Another difference is that I deploy these things on cloud instead of bare metal. Could this be the problem?

**Comment by rajatchopra** [comment]
I think it's a calico networking thing then. It uses bgp to set up the network, which will not with on a public cloud. But I will leave that diagnosis to calico folks.

**Comment by dragon9783** [comment]
Focusing

**Comment by xuant** [comment]
Explicitly setting --ipip and --nat-outgoing solved my problem.

**Comment by dragon9783** [comment]
@xuant could you tell me how to configure openshift node service with calico network plugin details , following  your steps, i got error when origin node start. Related Issues: https://github.com/openshift/openshift-sdn/issues/298, thanks

**Comment by xuant** [comment]
@dragon9783 
You need to add the network config:
```
create a file /opt/cni/net.d/10-calico.conf with the following content:

{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_authority": "<CALICO_ETCD_LOCATION>:6666",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    }
}
```
And replace <CALICO_ETCD_LOCATION>.

**Comment by dragon9783** [comment]
Thanks very much, i will try later.

**Comment by zhanglianx111** [comment]
good thing
