### ISSUE TITLE
Web console does not assign `app` label for templates

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8325]
`oc new-app` assigns an `app` label when deploying a template, but the web console does not.

@fabianofranz do you know how new-app chooses the app label value?

**Comment by jwforres** [comment]
cc @csrwng @bparees

**Comment by bparees** [comment]
https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/newapp.go#L244-L246

that's where it gets set.

there's some crazy magic, the starting point is if the user provided a "--name" argument to new-app, that name is used.  otherwise the system tries to determine a name here:

https://github.com/openshift/origin/blob/master/pkg/generate/app/cmd/newapp.go#L620-L642

the net of which is, in the name appears to ultimately come from the buildconfig's name, at least for the template i was playing with.  and if it has multiple buildconfigs?  good luck :)

**Comment by GrahamDumpleton** [comment]
The result of this in 1.3 is worse than what existed before and is still somewhat inconsistent with how ``oc new-app`` works for templates when ``--name`` argument is used. By using the template name for ``app``, and having it override what a template may have already wanted to set the ``app`` label to itself, you end up with a situation where someone doing ``oc delete all --selector app=template-name`` can blow away more than the one application they wanted to. The point of raising this was to have ``app`` set when templates used from web console, but for it to somehow use a name specific to that build or deployment, not a value that is shared by everything created from the template, that is what the ``template`` label is for. This should be reverted as no better than having no ``app`` label. 👎

**Comment by bparees** [comment]
New-app puts the app label on every object it creates, regardless of
whether that object came from a template or another flow.

The exception is that if any object new-app is about to create already has
the app label, no app label is added to anything.

The exception to that exception is if the user explicitly requested the app
label with a particular value (via the new-app client, not as part of the
template definition), the app label (with the user provided value) will be
applied to every object (overwriting any value that might already be
present)

The flow is:

1) new app processes the template, getting back a list of objects. Those
objects will have any label the template defined
2) check if any of the objects have an app label, if not, set the auto
generated app label on every object.   If so do not set it on any.
3) set the user provided labels on every object, overwriting label keys
that already exist. This may include a user provided app label.

I'm pretty sure that's the logic the console is intending to replicate.

Ben Parees | OpenShift

**Comment by GrahamDumpleton** [comment]
Does that description line up with this:

```
$ cat example.json
{
    "kind": "Template",
    "apiVersion": "v1",
    "metadata": {
        "name": "example-template"
    },
    "objects": [
        {
            "kind": "ImageStream",
            "apiVersion": "v1",
            "metadata": {
                "name": "is1",
                "labels": {
                    "app": "original-value",
                    "mylabel": "is"
                }
            }
        },
        {
            "kind": "ImageStream",
            "apiVersion": "v1",
            "metadata": {
                "name": "is2",
                "labels": {
                    "mylabel": "is"
                }
            }
        }
    ]
}

$ oc new-app --file=example.json  --dry-run -o json
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "kind": "ImageStream",
            "apiVersion": "v1",
            "metadata": {
                "name": "is1",
                "creationTimestamp": null,
                "labels": {
                    "app": "example-template",
                    "mylabel": "is"
                },
                "annotations": {
                    "openshift.io/generated-by": "OpenShiftNewApp"
                }
            },
            "spec": {},
            "status": {
                "dockerImageRepository": ""
            }
        },
        {
            "kind": "ImageStream",
            "apiVersion": "v1",
            "metadata": {
                "name": "is2",
                "creationTimestamp": null,
                "labels": {
                    "app": "example-template",
                    "mylabel": "is"
                },
                "annotations": {
                    "openshift.io/generated-by": "OpenShiftNewApp"
                }
            },
            "spec": {},
            "status": {
                "dockerImageRepository": ""
            }
        }
    ]
}
```

You state:

> The exception is that if any object new-app is about to create already has the app label, no app label is added to anything.

Based on that, then in ``is1``, it should keep the value ``original-value``.

Depends now on whether was actually fixed as suggested in:

* https://github.com/openshift/origin/issues/10782#issuecomment-250762652

which means you description is valid for 1.4, but not 1.3.

**Comment by bparees** [comment]
i'm discussing the current behavior of origin.

**Comment by GrahamDumpleton** [comment]
What is current? As a user I regard Origin 1.3/OCP 3.3 as current.

Or are you talking about Origin 1.4 alpha 0, or unreleased version in master of repo?

**Comment by bparees** [comment]
i'm talking about master. not sure if we've cut a release since the changes went in or not.

**Comment by liggitt** [comment]
1.3.0 was cut on 9/15, new-app label changes went into master on 9/28.
