### ISSUE TITLE
oc export does not work for image streams

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#8327]
If you export ImageStream having Spec.DockerImageRepository all of its tags are striped and not exported!
I probably found the line causing this 181: https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/exporter.go
IMHO you should copy tags from spec and status as well.
##### Version

oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75
##### Steps To Reproduce
1. oc new-project original-project
2. oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-hello-world.git
3. oc new-project import
4. oc export is,bc -o yaml -n original-project | oc create -f - -n import
5. oc start-build ruby-hello-world -n import
##### Current Result

Error from server: imageStreamTag "ruby-22-centos7:latest" not found
##### Expected Result

No error

**Comment by liggitt** [comment]
Status won't be respected in import, so it's not appropriate to include in export

**Comment by tnozicka** [comment]
@liggitt  you could merge tags from status with spec a write the hole thing into spec

**Comment by tnozicka** [comment]
btw. by accident @kadel found out that if you remove annotations from ImageStream definitions

1. oc new-project original-project
2. oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-hello-world.git
3. oc new-project import
4. oc export bc -o yaml -n original-project | oc create -f - -n import
5. oc export is ruby-hello-world -o yaml -n original-project | oc create -f - -n import
6. oc export is ruby-22-centos7 -o yaml -n original-project | sed '/annotations/,+2d' | oc create -f - -n import
7. oc start-build ruby-hello-world -n import

Now it works with pull on demand. But the tags are still not exported, just recreated.

**Comment by kadel** [comment]
@tnozicka  filed issue against origin related to this https://github.com/openshift/origin/issues/8327

**Comment by smarterclayton** [comment]
We need to figure out whether we want to preserve spec tags or make them exact (or do both).  I.e. if you're a user exporting an app, do you want to export the flow (where the images come from) or the EXACT images.

**Comment by miminar** [comment]
To preserve the is as is, we already have the `oc get is/name` and `oc export --raw is/name`. To make the exported image stream usable, we could:

1. remove [DockerImageRepositoryCheckAnnotation](https://github.com/miminar/origin/blob/registry-quota-refactor/pkg/image/api/types.go#L23) from annotations
2. make `ImageStreamImage` references in the spec for all the built images stored in status; I'm reluctant to do it by default though; `ImageStreamImage` reference is usable only if the import happens in the same cluster; otherwise `DockerImage` would have to be employed; this calls for some distinction flag like `--for-cluster-import` or `--for=<local|remote>`

**Comment by smarterclayton** [comment]
We are probably going to move to a model where all clusters have a
public registry name, so images are available outside.  By doing so
we'd at least guarantee the content is accessible.  We could
potentially decide how to handle each tag based on its source.
External images get turned from tags to digests.  ImageStreamTags get
turned into imagestreamimages.

**Comment by bparees** [comment]
part of https://trello.com/c/wGB9TRJS
/close
