### ISSUE TITLE
oadm router should let me specify --requests and --limits

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#8328]
The `oadm router` command should promote users specifying --requests and --limits for cpu and memory as it is a piece of critical infrastructure that should not run with best effort quality of service on nodes.

The system should warn users that running a router with no requests and limits is bad practice in production.

Documentation should emphasize that this is bad practice.

/cc @pweil- @ncdc @eparis @smarterclayton

**Comment by eparis** [comment]
Should the same be true of the registry?  @detiber does the installer set limits/requests or allow them to be set?

**Comment by pweil-** [comment]
> Should the same be true of the registry

Yes https://github.com/openshift/origin/issues/8329

**Comment by detiber** [comment]
@eparis it does not currently, once the command line support for this lands, we can add the ability to set it (for versions of Origin/OSE that support the flags)

**Comment by pweil-** [comment]
request/limit is now included as a default part of the object that is generated by the command.  Being able to set it during creation would still be a good enhancment

**Comment by smarterclayton** [comment]
I think we said that if you need this you can pipe

**Comment by pweil-** [comment]
> I think we said that if you need this you can pipe

sgtm
