### ISSUE TITLE
oadm registry should let me specify requests and limits

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/origin#8329]
The registry is a critical piece of infrastructure and should not run as best effort quality of service by default.  The command should let users specify requests and limits similar to the run command.  It should warn users that running registries without specifying requests and limits in a production environment is not recommended.  Documentation should make it clear that requests and limits should be set for this component.

This came to my attention when I was debugging the wedged pods in terminating problem as it appears to be caused by failure to pull images from a registry.

/cc @ncdc @eparis @smarterclayton @liggitt @pweil-

**Comment by derekwaynecarr** [comment]
@pweil- Can we ensure documentation is covered for this issue as a p1?

**Comment by derekwaynecarr** [comment]
Its not a performance issue as much as a system reliability issue in my view.

**Comment by derekwaynecarr** [comment]
Related: https://github.com/openshift/origin/issues/8176

It appears kubelet + docker can get in a bad state if it finds that requests to a registry timeout, so reliable registry deployment should be a high priority in my opinion.  (while we fix the kubelet problem of course)

**Comment by pweil-** [comment]
> Can we ensure documentation is covered for this issue as a p1?

yes

**Comment by smarterclayton** [comment]
I would prefer this just be a CLI command that can change the limits on any
DC, not just the router / registry.  oc set limits dc/foo ....

**Comment by kargakis** [comment]
oc set limits and a warning for oc status

**Comment by smarterclayton** [comment]
Yeah, the "you aren't defining a request/limit" really seems like a general warning, nothing to do with this specifically.

Like readiness, we would add warning and cli command together so the warning is actionable.

**Comment by kargakis** [comment]
@eparis assigning to @JacobTanenbaum for the set limits command

**Comment by pweil-** [comment]
request/limit is now included as a default part of the object that is generated by the command.  Being able to set it during creation would still be a good enhancment

**Comment by smarterclayton** [comment]
This is probably not going to be something we do in oadm registry which is
going to go away.

On Fri, Feb 23, 2018 at 4:25 AM, Michalis Kargakis <notifications@github.com

**Comment by bparees** [comment]
/close

Ben Parees | OpenShift
