### ISSUE TITLE
Error while promoting applications, using tagged image

### ISSUE THREAD

**Issue by prachitiple** [openshift/origin#8342]
Here is the context : I created two projects, namely i)development & ii)testing 
two users were assigned to both projects,

In project development, user "dev1" is having "edit role" and user "test1" is having "view role".
In project testing, user "test1" is having "edit role".

Here is the command that I used to give system:image-puller access to systemaccounts of testing project on development namespace,

oc policy add-role-to-group system:image-puller system:serviceaccounts:testing -n development.

Now, I created application in development project, by user "dev1", then I tagged the image in imagestream with promote tag.

Command used : oc tag --source=imagestreamtag 172.45.121.213:1234/development/ruby-hello-world@sha256:003342d6c5ae2cce5eea85c30d5f33ffd4000cab38b397e7d3aedc788009499d:latest  development/ruby-hello-world:promote

output shown using oc describe is - 

Tag     : latest
Spec    : "pushed" 	
Created : 40 minutes ago        
PullSpec: 172.45.121.213:1234/development/ruby-hello-world:sha256:00734ab38b397e7d3aedccce5eea85c30d5f33ffd4002d6c5ae20c788009499d  		

          
Tag     : promote
Spec    : 172.45.121.213:1234/development/ruby-hello-world:sha256:00734ab38b397e7d3aedccce5eea85c30d5f33ffd4002d6c5ae20c788009499d  		
Created :         
PullSpec: "not available"
Image   : "not available"

Issue 1 : PullSpec is "**not available**", for promote tag
Issue 2 : Latest image having promote tag, showing status as **unresolved** in web-console.
Issue 3 : If I create a new application using promoted image 'development/ruby-hello-world:promote' in testing project using test1 user, 
command used: oc new-app development/ruby-hello-world:promote

Then I get following error :
error: component "development/ruby-hello-world:promote" had only a partial match of "ruby-hello-world" - if this is the value you want to use, specify it explicitly.

**Comment by pweil-** [comment]
@prachitiple - please try tagging your image with `oc tag <is name>:latest <is-name>:promote` and check the tag/spec/image which should then show the correct spec and image.  Here is an example of a cross-namespace referenced image in new-app:

```
[vagrant@localhost origin]$ oadm new-project development --admin="devadmin"
Created project development
[vagrant@localhost origin]$ oadm new-project prod --admin="prodadmin"
Created project prod


[vagrant@localhost origin]$ oc login -u devadmin -p "test"
[vagrant@localhost origin]$ oc project
Using project "development" on server "https://10.0.2.15:8443".
[vagrant@localhost origin]$ oc policy add-role-to-user view prodadmin
[vagrant@localhost origin]$ oc create -f examples/sample-app/application-template-stibuild.json 
template "ruby-helloworld-sample" created
[vagrant@localhost origin]$ oc new-app ruby-helloworld-sample
[vagrant@localhost origin]$ oc tag origin-ruby-sample:latest origin-ruby-sample:promote


Tag	Spec						Created			PullSpec									Image
latest	<pushed>					8 minutes ago		172.30.191.22:5000/development/origin-ruby-sample@sha256:eb8d08ca7c5ec2...	<same>
promote	origin-ruby-sample@sha256:eb8d08ca7c5ec2...	About a minute ago	172.30.191.22:5000/development/origin-ruby-sample@sha256:eb8d08ca7c5ec2...	<same>


[vagrant@localhost origin]$ oc login -u prodadmin -p test
[vagrant@localhost origin]$ oc project
Using project "prod" on server "https://10.0.2.15:8443".
[vagrant@localhost origin]$ oc new-app development/origin-ruby-sample:promote
--> Found image 8366020 (13 minutes old) in image stream "origin-ruby-sample" in project "development" under tag "promote" for "development/origin-ruby-sample:promote"

    development/ruby-sample-build-1:e394e1fb 
    ---------------------------------------- 
    Platform for building and running Ruby 2.2 applications

    Tags: builder, ruby, ruby22

    * This image will be deployed in deployment config "origin-ruby-sample"
    * Port 8080/tcp will be load balanced by service "origin-ruby-sample"
      * Other containers can access this service through the hostname "origin-ruby-sample"

--> Creating resources with label app=origin-ruby-sample ...
    deploymentconfig "origin-ruby-sample" created
    service "origin-ruby-sample" created
--> Success
    Run 'oc status' to view your app.

[vagrant@localhost origin]$ oc get pods
NAME                         READY     STATUS    RESTARTS   AGE
origin-ruby-sample-1-rzfjx   1/1       Running   0          23s
```

**Comment by prachitiple** [comment]
Thanks... for your solution. It resolved issue.
