### ISSUE TITLE
API docs wrong for BuildConfig instantiate

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#8345]
Docs at https://docs.openshift.org/latest/rest_api/openshift_v1.html#create-instantiate-of-a-buildrequest say the response is a `v1.BuildRequest`, whereas it really is a `v1.Build`.

**Comment by bparees** [comment]
@smarterclayton how do we fix the generated swagger doc?  not clear to me how it's determining the return type.

this doc is also wrong:
https://docs.openshift.org/latest/rest_api/openshift_v1.html#create-a-template

guessing that swagger just assumes POST operations are creates that return the type you posted.

**Comment by smarterclayton** [comment]
We'd have to fix api registration in Kube and have additional info defined
on the Storage classes (of which there are a few examples).

**Comment by bparees** [comment]
@smarterclayton is there an upstream issue for this?

**Comment by smarterclayton** [comment]
Not today

**Comment by php-coder** [comment]
Any news on that?

I've just found it because https://docs.openshift.org/latest/rest_api/kubernetes_v1.html is talking about SCC (but it shouldn't) while https://docs.openshift.org/latest/rest_api/openshift_v1.html misses SCC stuff.

**Comment by bparees** [comment]
@jim-minter in your recent exploration of the api doc did you turn up anything that has changed on this?

**Comment by jim-minter** [comment]
@bparees https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/rest/rest.go#L310-L320 almost does the trick; will work on it.
