### ISSUE TITLE
There should be an extended test for the router

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8347]
It (or they) should validate the following as a conformance test on a router (black box):
1. The router serves the different types of realistic routes (edge, reencrypt, passthrough)
2. The router handles redirection on the different types
3. The router serves pods correctly under services
4. Adding/removing pods under the service results in the router serving those pods
5. Paths are properly handled
6. Connections are not arbitrarily dropped
7. Other specific features that are relevant in black box config

Would expect this to be client focused (changing API), can assume the router is installed.

@marun as discussed on IRC

**Comment by knobunc** [comment]
@weliang1 can you work with @marun to work out how to address this.  We want something for 3.3 and it won't be everything above, but I would like to have a more complete solution for 3.4.

**Comment by weliang1** [comment]
@knobunc,  sure, I will work with @marun on it.
