### ISSUE TITLE
Support pull by short ID

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8354]
ImageStreamImage supports short hash lookups `oc get isimage/foo@9ab35f`.  In the registry, because 8ab35f doesn't parse as a real Digest, the registry falls back to GetByTag.  GetByTag checks ImageStreamTag, but if the tag doesn't exist we can fall back to doing an API call to ImageStreamImage.  However, since the daemon is fetching by digest it expects the response to match that digest, which fails.

We could support image ID lookup by the short hash as a tag (since technically Docker doesn't distinguish), which would be convenient but look weird.  We could also have a 'oc resolve-image ...' that returns the docker pull spec.

**Comment by dmage** [comment]
```
$ docker pull 172.30.1.1:5000/isimage/foo@9ab35f
invalid reference format
```

This format check happens on the client side and we can't change this.
