### ISSUE TITLE
Insecure/default non-tls docker registry results in oversized TLS record

### ISSUE THREAD

**Issue by paralin** [openshift/origin#8361]
With the default documentation for deploying a registry, a non-tls registry is deployed.

This results in:

```
I0405 17:06:16.662680       1 docker.go:118] Pushing image 10.0.68.200:5000/dev-1/api-gateway:latest ...
E0405 17:06:16.669145       1 dockerutil.go:85] push for image 10.0.68.200:5000/dev-1/api-gateway:latest failed, will retry in 5s ...
E0405 17:06:21.676013       1 dockerutil.go:85] push for image 10.0.68.200:5000/dev-1/api-gateway:latest failed, will retry in 5s ...
E0405 17:06:26.683121       1 dockerutil.go:85] push for image 10.0.68.200:5000/dev-1/api-gateway:latest failed, will retry in 5s ...
E0405 17:06:31.690050       1 dockerutil.go:85] push for image 10.0.68.200:5000/dev-1/api-gateway:latest failed, will retry in 5s ...
E0405 17:06:36.697222       1 dockerutil.go:85] push for image 10.0.68.200:5000/dev-1/api-gateway:latest failed, will retry in 5s ...
E0405 17:06:41.704412       1 dockerutil.go:85] push for image 10.0.68.200:5000/dev-1/api-gateway:latest failed, will retry in 5s ...
E0405 17:06:46.711562       1 dockerutil.go:85] push for image 10.0.68.200:5000/dev-1/api-gateway:latest failed, will retry in 5s ...
F0405 17:06:51.711774       1 builder.go:204] Error: build error: Failed to push image: unable to ping registry endpoint https://10.0.68.200:5000/v0/
v2 ping attempt failed with error: Get https://10.0.68.200:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://10.0.68.200:5000/v1/_ping: tls: oversized record received with length 20527
```

It's attempting to use https for the registry when the registry is configured without https. Is there a way to force the builder to use http rather than https?

**Comment by paralin** [comment]
And now that I enabled tls I get unknown authority :(

**Comment by liggitt** [comment]
If you are using non-tls (or TLS without providing the CA to docker), you need to set `--insecure-registry` for the registry in your `/etc/sysconfig/docker` file

**Comment by paralin** [comment]
Odd, I have insecure enabled and somehow that never got persisted into my docker options...

**Comment by liggitt** [comment]
> insecure enabled

enabled where?

**Comment by paralin** [comment]
@liggitt It's a aws kube-up problem, the insecure option just never made it to the sysconfig. I'm figuring out what happened now.

**Comment by paralin** [comment]
@liggitt I've fixed my cluster problems and now the docker opts are as such:

`-s aufs --insecure-registry 10.0.0.0/8  --bridge=cbr0 --iptables=false --ip-masq=false --log-level=warn`

It's still trying to push to `https` even though the registry is NOT tls-enabled.

How can I make the builder use http instead?

**Comment by paralin** [comment]
Never mind, it turns out on that one specific instance for some reason the old docker opts were still set... 

Fixed now, thanks.
