### ISSUE TITLE
Error: build error: unable to get metadata for registry.access.redhat.com

### ISSUE THREAD

**Issue by mgbarbero** [openshift/origin#8372]
Hi guys, when I try a new build from any builder image or template from registry.access.redhat.com it fails with the following error.

I0406 08:10:54.219361       1 sti.go:173] The value of ALLOWED_UIDS is []
I0406 08:10:54.255142       1 sti.go:195] Creating a new S2I builder with build config: "Builder Image:\t\tregistry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2\nSource:\t\t\tfile:///tmp/s2i-build900718867/upload/src#6.4.x\nContext Directory:\tkitchensink\nOutput Image Tag:\t172.30.18.92:5000/mariano/tigo8888:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAME=tigo8888-1,OPENSHIFT_BUILD_NAMESPACE=mariano,OPENSHIFT_BUILD_SOURCE=https://github.com/jboss-developer/jboss-eap-quickstarts.git,OPENSHIFT_BUILD_REFERENCE=6.4.x\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nBuilder Pull Policy:\tif-not-present\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nWorkdir:\t\t/tmp/s2i-build900718867\nDocker NetworkMode:\tcontainer:9a5916f0e9b8d672b8450419e9a74e4eca94d5f2f1f98c079b3772d99a313652\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
F0406 08:10:54.255634 1 builder.go:185] **Error: build error: unable to get metadata for registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2**

##### Version
oc v3.1.1.6-33-g81eabcc
kubernetes v1.1.0-origin-1107-g4c8e6f4

##### Steps To Reproduce
Add to project jboss-eap64-openshift:1.2

Any help will be very appreciated, thanks !

**Comment by bparees** [comment]
are you able to `docker inspect registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2` on the cluster node that is performing the build?

**Comment by bparees** [comment]
it might also help if you provided level 5 build logs.

**Comment by mgbarbero** [comment]
Hi bparees ! Thank you for your reply.

Yes, docker inspect registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2 works as expected in all nodes.

Here is my build log, level 5, as you can see is a permission deny issue. I'm running an insecure internal docker registry.

I'm running as root.

Thank you for all your help.

I0408 16:35:08.542047       1 builder.go:41] $BUILD env var is {"kind":"Build","apiVersion":"v1","metadata":{"name":"eap-app4444-5","namespace":"mariano","selfLink":"/oapi/v1/namespaces/mariano/builds/eap-app4444-5","uid":"605f94bc-fdc9-11e5-ab9f-001a4a565f0c","resourceVersion":"351011","creationTimestamp":"2016-04-08T20:35:05Z","labels":{"application":"eap-app4444","buildconfig":"eap-app4444","openshift.io/build-config.name":"eap-app4444","template":"eap64-https-s2i","xpaas":"1.2.0"},"annotations":{"openshift.io/build.number":"5"}},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/jboss-developer/jboss-eap-quickstarts","ref":"6.4.x"},"contextDir":"kitchensink"},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2"},"env":[{"name":"BUILD_LOGLEVEL","value":"5"}],"forcePull":true}},"output":{"to":{"kind":"DockerImage","name":"172.30.18.92:5000/mariano/eap-app4444:latest"},"pushSecret":{"name":"builder-dockercfg-8zmon"}},"resources":{}},"status":{"phase":"New","outputDockerImageReference":"172.30.18.92:5000/mariano/eap-app4444:latest","config":{"kind":"BuildConfig","namespace":"mariano","name":"eap-app4444"}}}

I0408 16:35:08.567817       1 sti.go:163] With force pull true, setting policies to always
I0408 16:35:08.567848       1 sti.go:173] The value of ALLOWED_UIDS is []
I0408 16:35:08.567867       1 cfg.go:45] Locating docker auth for image registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2 and type PULL_DOCKERCFG_PATH
I0408 16:35:08.567943       1 cfg.go:81] Using Docker authentication configuration in ''
I0408 16:35:08.567965       1 cfg.go:53] Problem accessing : stat : no such file or directory
I0408 16:35:08.567979       1 cfg.go:45] Locating docker auth for image 172.30.18.92:5000/mariano/eap-app4444:latest and type PUSH_DOCKERCFG_PATH
I0408 16:35:08.567987       1 cfg.go:81] Using Docker authentication configuration in '/var/run/secrets/openshift.io/push/.dockercfg'
I0408 16:35:08.568234       1 cfg.go:67] Using serviceaccount user for Docker authentication for image 172.30.18.92:5000/mariano/eap-app4444:latest
I0408 16:35:08.568284       1 docker.go:242] Pulling Docker image registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2 ...
I0408 16:35:08.568437       1 docker.go:245] An error was received from the PullImage call: dial unix /var/run/docker.sock: permission denied
I0408 16:35:08.568645       1 docker.go:233] error inspecting image registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2: Get http://unix.sock/images/registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2/json: dial unix /var/run/docker.sock: permission denied
I0408 16:35:08.568832       1 sti.go:195] Creating a new S2I builder with build config: "Builder Image:\t\tregistry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2\nSource:\t\t\tfile:///tmp/s2i-build732292347/upload/src#6.4.x\nContext Directory:\tkitchensink\nOutput Image Tag:\t172.30.18.92:5000/mariano/eap-app4444:latest\nEnvironment:\t\tBUILD_LOGLEVEL=5,OPENSHIFT_BUILD_NAME=eap-app4444-5,OPENSHIFT_BUILD_NAMESPACE=mariano,OPENSHIFT_BUILD_SOURCE=https://github.com/jboss-developer/jboss-eap-quickstarts,OPENSHIFT_BUILD_REFERENCE=6.4.x\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nBuilder Pull Policy:\talways\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nWorkdir:\t\t/tmp/s2i-build732292347\nDocker NetworkMode:\tcontainer:52aa2a79b6a1e83c7c56e1deb834f04b24471f4e8b70aa73ec5e4762ebcc503a\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I0408 16:35:08.568879       1 docker.go:242] Pulling Docker image registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2 ...
I0408 16:35:08.568949       1 docker.go:245] An error was received from the PullImage call: dial unix /var/run/docker.sock: permission denied
I0408 16:35:08.569061       1 docker.go:233] error inspecting image registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2: Get http://unix.sock/images/registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2/json: dial unix /var/run/docker.sock: permission denied
F0408 16:35:08.569173       1 builder.go:185] Error: build error: unable to get metadata for registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.2
[root@rhoscl02 registry]#

**Comment by bparees** [comment]
what are the permissions on /var/run/docker.sock ?

**Comment by mgbarbero** [comment]
[root@rhoscl02 registry]# ls -l /var/run/docker.sock
srw-rw----. 1 root root 0 Mar 31 17:37 /var/run/docker.sock

**Comment by mgbarbero** [comment]
After run chmod -R 777 /var/run/docker.sock the issue is solved !! But now I have the same error reported in #8374 
Thank you @bparees

**Comment by bparees** [comment]
yw
