### ISSUE TITLE
Extended tests: focus runs all the tests when pattern contains square brackets

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#8379]
I was unable to run only small amount of extended tests with focus, it always tried to run all of them:

``` console
$ ./test/extended/core.sh --focus="[images][mongodb]" -ginkgo.dryRun
...
Will run 383 of 383 specs

•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 383 of 383 Specs in 0.006 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
```

But it works when I'm escaping square brackets:

``` console
$ ./test/extended/core.sh --focus="\[images\]\[mongodb\]" -ginkgo.dryRun
...
Will run 2 of 383 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSS•S
Ran 2 of 383 Specs in 0.017 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 381 Skipped PASS
```
##### Version

Commit: e74de6956eea0df8bf668b7eba47c361c74d5e2f
##### Steps To Reproduce

`./test/extended/core.sh --focus="[images][mongodb]"`
##### Current Result

It always runs all tests.
##### Expected Result

Should run only MongoDB tests.

**Comment by mfojtik** [comment]
@php-coder still an issue? I can see that we are quoting the focus parameter in jenkins

**Comment by mfojtik** [comment]
@php-coder perhaps it does not work because ginkgo expect 'regular expression' ?

**Comment by php-coder** [comment]
After I've found that it works after quoting I started to use this forms. I don't know is it "works as expected" or it's a "workaround". For me it was unexpected behavior.

**Comment by mfojtik** [comment]
@php-coder since the focus should support regexp, I think it is OK to assume you have to escape '['.
But since we use that as 'tags' maybe we should automatically escape that in the vagrant plugin.

@danmcp wdyt?

**Comment by danmcp** [comment]
@mfojtik The issue seems like it's in core.sh in this case.   I would think you want to be able to call core.sh without any escaping at all right?

**Comment by mfojtik** [comment]
@danmcp the --focus accepts a 'regexp' string, so '[' have to be escaped to make it work. However, nobody know about that and people use '[builds]' etc. and think it will work. What I'm thinking about is to escape only '[' and ']' because we use it as 'tags' in extended tests descriptions. 

Yeah, the escaping will need to happen in core.sh.

**Comment by stevekuznetsov** [comment]
`--ginkgo.focus` is a regex. We just pass it through.
