### ISSUE TITLE
Deployment trigger details is missing image name

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#838]
sample of the current encodedDeploymentConfig, where causes[0].imageTrigger only contains tag, no reference to the image name:

"encodedDeploymentConfig": "{\"kind\":\"DeploymentConfig\",\"apiVersion\":\"v1beta1\",\"metadata\":{\"name\":\"database\",\"namespace\":\"test\",\"selfLink\":\"/osapi/v1beta1/deploymentConfigs/database\",\"uid\":\"ccaee025-ab05-11e4-bb4c-54ee75107c12\",\"resourceVersion\":\"51\",\"creationTimestamp\":\"2015-02-02T13:03:32-05:00\",\"labels\":{\"template\":\"ruby-helloworld-sample\"}},\"triggers\":[{\"type\":\"ConfigChange\"}],\"template\":{\"strategy\":{\"type\":\"Recreate\"},\"controllerTemplate\":{\"replicas\":1,\"replicaSelector\":{\"name\":\"database\"},\"podTemplate\":{\"desiredState\":{\"manifest\":{\"version\":\"v1beta2\",\"id\":\"\",\"volumes\":null,\"containers\":[{\"name\":\"ruby-helloworld-database\",\"image\":\"mysql\",\"ports\":[{\"containerPort\":3306,\"protocol\":\"TCP\"}],\"env\":[{\"name\":\"MYSQL_ROOT_PASSWORD\",\"key\":\"MYSQL_ROOT_PASSWORD\",\"value\":\"rQHfVnTo\"},{\"name\":\"MYSQL_DATABASE\",\"key\":\"MYSQL_DATABASE\",\"value\":\"root\"}],\"imagePullPolicy\":\"PullIfNotPresent\",\"capabilities\":{}}],\"restartPolicy\":{\"always\":{}},\"dnsPolicy\":\"ClusterFirst\"}},\"labels\":{\"name\":\"database\",\"template\":\"ruby-helloworld-sample\"}}}},\"latestVersion\":1,\"details\":{\"causes\":[{\"type\":\"ConfigChange\"}]}}",

**Comment by ironcladlou** [comment]
@smarterclayton I'll take this one, too.

**Comment by ironcladlou** [comment]
@jwforres I just got back to this and realized that in the example you provided, there's no image change cause, only a `ConfigChange`. So, image trigger details would be unexpected. How'd you set up this test?

**Comment by ironcladlou** [comment]
@jwforres nevermind, I found some examples of the bug from etcd dumps for the e2e test in Jenkins.

**Comment by pmorie** [comment]
The incorrect behavior is that the `From` field of the image change trigger wasn't being considered while the triggers were matched against the deployment config.

**Comment by ironcladlou** [comment]
Resolved by #858
