### ISSUE TITLE
Image source's sourcePath doesn't allow for wildcard copy

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#8383]
I want to copy all the contents of a directory in a source image into my destination image, but it's not possible

##### Version
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75

##### Steps To Reproduce
1. Create an image with files and dirs in /files

````
$ ls ./files
Dockerfile  
apply*
config/
```` 

````
FROM scratch
COPY apply /files/config
COPY config/ /files/config

CMD ["/bin/sh"]
````

2. Use it as source image in BC to get the files
````
        ....
        "source": {
          "type": "Git",
          "git": {
            "uri": "https://github.com/bparees/openshift-jee-sample.git",
            "ref": "master"
          },
          "images": [
            {
              "from": {
                "kind": "ImageStreamTag",
                "name": "addons:latest"
              },
              "paths": [
                {
                  "destinationDir": "addon/",
                  "sourcePath": "/files/"
                }
              ]
            }
          ]
        },
       ...
````
##### Current Result
I have in the image:
````
/opt/app-root/src/addon/files/apply
/opt/app-root/src/addon/files/config/...
````

##### Expected Result
I would expect to have:
````
/opt/app-root/src/addon/apply
/opt/app-root/src/addon/config/...
````

##### Additional Information
I've tried with "sourcePath": "/files/*"
Only option I see is to include 2 paths, but this is unmanageable as the number of files can be big. I want to be able to copy everything in sourcePath into destinationPath.

**Comment by bparees** [comment]
so you want to copy the content of the directory w/o actually copying the directory itself?

**Comment by jorgemoralespou** [comment]
Yup. Doesn't make sense? I would expect to be able to copy the directory or it's contents. Like with Docker ADD or COPY.

**Comment by bparees** [comment]
makes sense.

**Comment by bparees** [comment]
looks like you just need to use /. instead of /*:

this is the api we use to do the copy out of the source image:
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.20/#get-an-archive-of-a-filesystem-resource-in-a-container

```If path ends in /. then this indicates that only the contents of the path directory should be copied.```

let me know if that works for you.

**Comment by jorgemoralespou** [comment]
Ben, 
That's the first thing that I tried as can be seen in the description of the issue and it's not working, hence I opened the issue.

**Comment by bparees** [comment]
i don't see where you say you tried "/.", you said you tried "/*".

I tried "/." before replying last night and it worked for me.

**Comment by jorgemoralespou** [comment]
@bparees Ahh, I didn't noticed the dot at the end. WIll try, although to me doesn't look consistent, and definitely if that's the case there's a need for documentation :-D

**Comment by bparees** [comment]
yes a doc update will be in order, but hopefully it works for you so you can make progress at least.

**Comment by bparees** [comment]
doc pull: https://github.com/openshift/openshift-docs/pull/1879

**Comment by bparees** [comment]
/. syntax documented.
