### ISSUE TITLE
openshift-ansible build error in install docker

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#8385]
Version：oepnshift-origin-1.1.6
Environment：The new system did not install anything
                        3master+3etcd+3node+1lb[1]+DNS

Hi,
In the old releases,i run shell[2] to install origin ,that will begin to install automatically and will be ok(it had a bug for yum that we use `yum -y upgrade yum\*`[3]).
In the new release,i find a bug when run shell
![bug-1](https://cloud.githubusercontent.com/assets/12937669/14322077/2e8677a6-fc4e-11e5-84f4-afd85d0b06b1.png)
I guess it would be a bug for yum,so i use `ansible all -m shell -a "yum -y upgrade yum\*"`,but there is no effective.
with this bug,i use `ansible  all -m shell -a "yum -y install docker"` to install docker-1.9.1,but it always error for build(tried many times ).
![new-bug-in1 6-4](https://cloud.githubusercontent.com/assets/12937669/14322381/46cf792e-fc4f-11e5-9501-f6e2c8278f47.png)
![new-bug-in1 6-5](https://cloud.githubusercontent.com/assets/12937669/14322380/4654637e-fc4f-11e5-8151-6910b5636954.png)
![new-bug-in1 6-3](https://cloud.githubusercontent.com/assets/12937669/14322446/8d99a8b6-fc4f-11e5-9dc1-601b4849b14d.png)

In the final,i use `ansible  all -m shell -a "yum -y install docker-1.8.2 docker-selinux-1.8.2` and use shell[2] to build it(docker will be update to 1.9.1),it is ok.
![new-ok-1](https://cloud.githubusercontent.com/assets/12937669/14322834/cce7dc44-fc50-11e5-9402-fff15129641f.png)
Is it a bug for the new release?
thanks.

[1] https://docs.openshift.org/latest/install_config/install/advanced_install.html#multiple-masters
[2] shell: ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
[3] https://github.com/openshift/origin/issues/8037

**Comment by brenton** [comment]
@wenskys, I was just able to install Origin 1.1.6 successfully.  Here's what I used:

```
[root@ip-172-18-8-89 ~]# rpm -qa | grep openshift | sort
atomic-openshift-utils-3.0.74-1.git.6.a3be3eb.el7.noarch
openshift-ansible-3.0.74-1.git.6.a3be3eb.el7.noarch
openshift-ansible-bin-3.0.74-1.git.6.a3be3eb.el7.noarch
openshift-ansible-docs-3.0.74-1.git.6.a3be3eb.el7.noarch
openshift-ansible-filter-plugins-3.0.74-1.git.6.a3be3eb.el7.noarch
openshift-ansible-inventory-3.0.74-1.git.6.a3be3eb.el7.noarch
openshift-ansible-inventory-aws-3.0.74-1.git.6.a3be3eb.el7.noarch
openshift-ansible-inventory-gce-3.0.74-1.git.6.a3be3eb.el7.noarch
openshift-ansible-lookup-plugins-3.0.74-1.git.6.a3be3eb.el7.noarch
openshift-ansible-playbooks-3.0.74-1.git.6.a3be3eb.el7.noarch
openshift-ansible-roles-3.0.74-1.git.6.a3be3eb.el7.noarch
[root@ip-172-18-8-89 ~]# 
[root@ip-172-18-8-89 ~]# 
[root@ip-172-18-8-89 ~]# rpm -qa | grep origin | sort
docker-1.9.1-25.1.origin.el7.centos.x86_64
docker-forward-journald-1.9.1-25.1.origin.el7.centos.x86_64
docker-selinux-1.9.1-25.1.origin.el7.centos.x86_64
origin-1.1.6-1.git.9999.9c5694f.el7.x86_64
origin-clients-1.1.6-1.git.9999.9c5694f.el7.x86_64
origin-master-1.1.6-1.git.9999.9c5694f.el7.x86_64
origin-node-1.1.6-1.git.9999.9c5694f.el7.x86_64
origin-sdn-ovs-1.1.6-1.git.9999.9c5694f.el7.x86_64
tuned-profiles-origin-node-1.1.6-1.git.9999.9c5694f.el7.x86_64
```

I built the latest openshift-ansible from source: https://github.com/openshift/openshift-ansible.  If that's an option for you it would be helpful for us to try it.

I suspect you may be hitting https://bugzilla.redhat.com/show_bug.cgi?id=1324728 which is a recent bug that happened in pre-release builds of OpenShift Enterprise.  We should have it fixed shortly and I'll make sure we release a centos package.

**Comment by wenskys** [comment]
@brenton Thanks for your help,I think this is a bug in a new create.
I update my openshift-origin from 1.1.4 to 1.1.6,and update docker to 1.9.1.25,and it is ok and useful.
