### ISSUE TITLE
Updated an existing BC has unexpected result when "oc start-build is run" 

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#8386]
I have created a BuildConfig (example-bc) and created some builds "example-bc-1,example-bc-2".
If I replace/update my bc, as I've found an error in it, through "oc replace -f example-bc.json", if I trigger a new build using command line gives me an error for the number of previous builds done:

````
$oc get builds
NAME               TYPE      FROM          STATUS     STARTED             DURATION
example-bc-1    Source    Git@5df41f9   Complete   About an hour ago   57s
example-bc-2    Source    Git@5df41f9   Complete   About an hour ago   1m3s

$oc start-build example-bc
Error from server: builds "example-bc-1" already exists
$oc start-build example-bc
Error from server: builds "example-bc-2" already exists
$oc start-build example-bc --follow
example-bc-3
W0406 15:05:26.520485       1 builder.go:55] Master version "v1.1.6" does not match Builder image version "v1.1.6-12-ge74de69"
````

**Comment by jorgemoralespou** [comment]
I've just realised an error while replacing the resource

````
Error from server: DeploymentConfig "example-bc" is invalid: status.latestVersion: Invalid value: 0: latestVersion cannot be decremented
````

**Comment by liggitt** [comment]
updates to a deployment config should not touch the object's status... cc @ironcladlou

**Comment by ironcladlou** [comment]
cc @kargakis

**Comment by kargakis** [comment]
> updates to a deployment config should not touch the object's status... cc @ironcladlou

Fixed in https://github.com/openshift/origin/pull/7149

**Comment by kargakis** [comment]
I think there are two separate issues reported here. Can we split them and assign the first one to someone from the devexp team?

**Comment by kargakis** [comment]
Actually, there is https://github.com/openshift/origin/issues/6465 for the status updates for dcs. @bparees mind taking over the present issue which is related to buids?

**Comment by bparees** [comment]
use `apply`, not `replace`.  replace is going to reset the build sequence number so yes, you'll get collisions..  not a whole lot we can do about that, but we do have a card for it:
https://trello.com/c/2pgcGpn7/698-3-handle-build-naming-collisions
