### ISSUE TITLE
Pod request values can have mB unit when set as percentage of limit

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8391]
See memory usage below. Values like this also appear in the pod template for memory request. It looks like we're using mB to avoid losing precision when calculating request as a percentage of limit.

![image](https://cloud.githubusercontent.com/assets/1167259/14330863/7ff9d530-fc10-11e5-89d4-ccb8161f65f7.png)

/cc @sspeiche @sosiouxme @jwforres @derekwaynecarr

**Comment by spadgett** [comment]
<img width="629" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/14336840/2d053998-fc36-11e5-9063-eb9c229f8bf0.png">

<img width="537" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/14336889/8ed5d97a-fc36-11e5-8b2d-4bb269c679be.png">

**Comment by derekwaynecarr** [comment]
It looks to me that we are not preserving format somewhere.

**Comment by derekwaynecarr** [comment]
A few options:

1) upstream could fail validation for any fractional request of memory
2) cluster overcommit admission controller can round up fractional values

I am pursuing 2 since I think 1 may impact backwards compatibility.

**Comment by derekwaynecarr** [comment]
Another thing:

the current code allows for cpu precision below a millicore.  for example, 0.5m or 100.5m, we should also round those up.

**Comment by jwforres** [comment]
so derek's fix will get rid of the fact that there are mB but we will still
end up with B as the unit so...
@spadgett I discussed briefly with @smarterclayton and I do think we want
to humanize the values when we display them like you did with image size,
one decimal place of precision

**Comment by derekwaynecarr** [comment]
@danmcp can this be labeled p1 since we are actually storing invalid data (i.e. a fractional byte, and a fractional millicore)
