### ISSUE TITLE
kubernetes defaults not held downstream.

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#8392]
Per conversation with @smarterclayton & @liggitt , defaults from upstream appear to have not taken hold downstream e.g. 

--watch-cache=true

##### Version
[oc v3.2.0.9]

/cc @jeremyeder @mattf

**Comment by timothysc** [comment]
@liggitt could we get a list of what defaults have not been applied.

**Comment by liggitt** [comment]
looks like `--watch-cache` and `--delete-collection-workers` were the only relevant ones that origin was defaulting to something different on

#8395 will enable watch cache for etcd for kubernetes types. work is required to enable caching for origin types

**Comment by derekwaynecarr** [comment]
@liggitt - what is the plan on --delete-collection-works?

**Comment by liggitt** [comment]
The default is actually 1, which is what we were using.

**Comment by timothysc** [comment]
@derekwaynecarr I still believe delete-collection-workers is kind of a hack.  We'll have to re-re-re-address the delete semantics once etcd3 lands.

**Comment by timothysc** [comment]
Closing as https://github.com/openshift/origin/pull/8395 fixes this.

**Comment by liggitt** [comment]
> Closing as #8395 fixes this. 

actually close?
