### ISSUE TITLE
build app  show error

### ISSUE THREAD

**Issue by zhwenh** [openshift/origin#8415]
Version  1.1.6
oc get svc
NAME              CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
docker-registry   **172.30.250.156**   <none>        5000/TCP                  18h
kubernetes        172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     1d
router            172.30.187.69    <none>        80/TCP,443/TCP,1936/TCP   1d
##### Current Result

build app  show error：
I0413 04:11:56.137077       1 sti.go:267] Using provided push secret for pushing 172.30.213.130:5000/demo/django-example:latest image
I0413 04:11:56.137167       1 sti.go:271] Pushing 172.30.213.130:5000/demo/django-example:latest image ...
I0413 04:12:26.154445       1 sti.go:276] Registry server Address: 
I0413 04:12:26.154505       1 sti.go:277] Registry server User Name: serviceaccount
I0413 04:12:26.154517       1 sti.go:278] Registry server Email: serviceaccount@example.org
I0413 04:12:26.154525       1 sti.go:283] Registry server Password: <<non-empty>>
F0413 04:12:26.154536       1 builder.go:204] Error: build error: Failed to push image. Response from registry is: Error parsing HTTP response: unexpected end of JSON input: ""

**Comment by nak3** [comment]
It is not same issue with https://github.com/openshift/origin/issues/8010 ?
Could you please check registry log by `oc logs <REGISTERY_POD>` and you cannot see  `tcp: lookup <MASTER_HOST>: no such host`?

**Comment by pweil-** [comment]
closing due to lack of response
