### ISSUE TITLE
[RFE] Share image stream cache

### ISSUE THREAD

**Issue by miminar** [openshift/origin#8419]
Create a shared imageStreamCache for image streams similar to [projectCache](https://github.com/openshift/origin/blob/388478c40e751c4295dcb9a44dd69e5ac65d0e3b/pkg/project/cache/cache.go#L17) for projects. Share it amongst resource quota controller, origin quota admission plugin, image import controller, image change controller and possible other controllers and thus improve performance and reduce memory usage.

**Comment by kargakis** [comment]
cc: @deads2k

**Comment by soltysh** [comment]
Dupe of https://github.com/openshift/origin/issues/8229

**Comment by deads2k** [comment]
> Dupe of #8229

Yeah, clayton's instrumenting will catch it as we try to squash them.

**Comment by kargakis** [comment]
Note that we already have a shared image stream cache (used by the deployment controllers) - it just needs to be used by the rest of the controllers
