### ISSUE TITLE
Alerts that are dismissible should be closed by clicking anywhere within the alert

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin#8423]
When an dismissible alert message (that is informational only) is displayed, it's unnecessarily annoying to require the user to click only the "x" to close the message. 

I better experience would be to enable the user to quickly close the alert if clicked anywhere within it's boundary.

**Comment by jwforres** [comment]
Hmm have to be careful here, this affects the usability of links in the alerts. If they click slightly off the link they close the alert instead of performing the action they were trying to do.

**Comment by liggitt** [comment]
agree, showing an "X" but making everything clickable is weird

**Comment by sg00dwin** [comment]
Yes, by 'informational only' I meant it didn't contain links within the message. Originally thought our alerts were all ones that didn't have links, but I just hit one that did. And I assume we couldn't differentiate between ones with and without. So closing this.
