### ISSUE TITLE
We need an easy way to gracefully migrate pods from one node to another

### ISSUE THREAD

**Issue by mrosic** [openshift/origin#8424]
`oadm manage-node xyz --evacuate` immediately kills all pods and will make your services go offline if they are backed by only one pod.
##### Version

1.1.4
##### Steps To Reproduce
1. oadm manage-node xyz --schedulable=false
2. oadm manage-node xyz --evacuate
##### Current Result

All pods are immediately terminated.
The current workaround is tedious: Scale DCs to two replicas, mark old node as unschedulable, delete pods from old node, scale DCs to one replica.
##### Expected Result

New pods are created on a different node first and only after the readiness checks have succeeded will a pod be terminated on the node that is being evacuated.

**Comment by pweil-** [comment]
This is not specific to evacuate and rather an issue of redundancy during **any** node failure that causes pods to terminate.  Running multiple pods in a service is the right solution here.
