### ISSUE TITLE
Investigate deployers deletion when cancelling deployments

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8439]
Currently when we cancel a running deployment, we set ActiveDeadlineSeconds to its deployers so that they will fail and subsequently transition the deployment phase to Failed. We should investigate deleting those deployers.

cc: @smarterclayton @ironcladlou @pweil-

**Comment by kargakis** [comment]
A pretty simple fix would be to retain the current behavior of cancelling by setting ADS when New or Running, and cleanup when Complete (already happens) or Failed + Cancelled.

**Comment by soltysh** [comment]
Isn't migration to upstream deployment going to solve the problem of the deployer? IIRC they're not using any. On the other hand, deployer was created to allow creating users one by themselves, isn't this going to be backward compatibility issue?

**Comment by kargakis** [comment]
> Isn't migration to upstream deployment going to solve the problem of the deployer? IIRC they're not using any. 

I think deployers will be always needed for running custom strategies. Also, until we get full feature parity, we will defer to our controller for feaures supported only by us.

> On the other hand, deployer was created to allow creating users one by themselves, isn't this going to be backward compatibility issue?

This issue is about cleaning up deployers on cancelled deployments. I don't see any backwards compatibility implications but maybe I am missing something. Why do you think so?

**Comment by soltysh** [comment]
> This issue is about cleaning up deployers on cancelled deployments. I don't see any backwards compatibility implications but maybe I am missing something. Why do you think so?

I misunderstood your 'total removal' as entirely removing them ;)

**Comment by kargakis** [comment]
reworded

**Comment by ironcladlou** [comment]
I think it's arguable that cancelled deployers should be deleted, but I guess it's possible a user notices something's wrong and hits the cancel button so they can go inspect the pods immediately. 

This is UX guesswork, so I'm not sure there's a right answer. Where's the use case coming from?

**Comment by kargakis** [comment]
By "the pods" I assume you mean the deployers since the new application pods will be scaled down. Won't the deployment fail either way if something wrong is noticed by the process?

**Comment by smarterclayton** [comment]
Does a user *need* the deployer pod if the deployment is cancelled?  We
used to *require* the pod to have logs, but in theory we have a solution
for that.  We have a card in plat-man to have logs for deployments / builds
/ pods that have been deleted be fetched from the logging service.  Would
that be sufficient that cancel deleting the deployer pod would be
sufficient?

**Comment by kargakis** [comment]
Yeah, I don't think the deployer is any useful in case of a cancellation. I would say we could go ahead and remove deployers before we bring the logging service into play but they (deployer pods) would definitely be obsolete post-deployment in case of such an addition (fetch logs from deleted pods)
