### ISSUE TITLE
Flake in extended test suite (should scale a replication contoller)

### ISSUE THREAD

**Issue by miminar** [openshift/origin#8441]
• Failure [321.361 seconds]
    Kubectl client
    /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubectl.go:1146
      Update Demo
      /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubectl.go:161
        should scale a replication controller [Conformance] [It]
        /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubectl.go:150

        Apr  9 14:02:20.888: Timed out after 300 seconds waiting for name=update-demo pods to reach valid state

        /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/util.go:1469

Happened in #8195 ([job#66](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/66/consoleFull)).

**Comment by smarterclayton** [comment]
Likely fixed by #8412

**Comment by smarterclayton** [comment]
Was not fixed by #8412, the container is in crash loop backoff. Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/79/console as well

@ncdc @derekwaynecarr @kargakis

**Comment by smarterclayton** [comment]
PLEG says "ContainerDied"

**Comment by ncdc** [comment]
I can't find anything more in the logs captured by Jenkins. The docker.log starts too late - why is it not the full log?

**Comment by smarterclayton** [comment]
Just because we didn't know how much output it would generate.

**Comment by ncdc** [comment]
Because we run tests in parallel, each test's namespace needs to be added to the various SCCs to ensure upstream e2es can pass against OpenShift's security model. It looks like that code was resulting in each namespace stomping on the other namespaces such that only a single e2e namespace at a time was ever a member of the various SCCs.

#8465 should fix this issue.
