### ISSUE TITLE
Vagrant fails: Timeout waiting for sdn node to register with the master

### ISSUE THREAD

**Issue by alban** [openshift/origin#8442]
The Vagrant file fails. The error message is:

> Timeout waiting for sdn node to register with the master
##### Version

openshift/origin from git master: 561e4fa7cd56c2f23780da730dd2e7de6f451e80
Fedora 23
Vagrant 1.8.1
##### Steps To Reproduce
1. Git-clone the repository https://github.com/openshift/origin
2. Build: `make clean build`
3. Fix NFS in Vagrant (see [vagrant-nfs](https://developer.fedoraproject.org/tools/vagrant/vagrant-nfs.html))
4. Become root with `sudo -s`
5. Export variables as explained in the [openShiftVagrant.html guide](http://fabric8.io/guide/openShiftVagrant.html): `export OPENSHIFT_NUM_MINIONS=1 ; export OPENSHIFT_DEV_CLUSTER=true`
6. `vagrant up` 
##### Current Result

`vagrant up` fails with the error message:

> [ERROR] Timeout waiting for sdn node to register with the master

Full logs:
https://gist.github.com/alban/9f1353bc29a8b934035c87bcc9bd51e6
##### Expected Result

`vagrant up` works.

**Comment by luebken** [comment]
I'm running into the same issue on a local setup on a Mac.

Full logs:
https://gist.github.com/luebken/e46e7e4c7cffcee52dcfabeaec50c7ea

**Comment by knobunc** [comment]
Sorry for the delay.  Is this still happening?

**Comment by pweil-** [comment]
closing due to no response
