### ISSUE TITLE
Create cccp.yaml files for the dockerfiles in the images directory.

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/origin#8451]
We need to add cccp.yaml to the images in the images directory so that the CentOS Community Container Pipeline can access and build the docker images present there.

**Comment by mohammedzee1000** [comment]
I am currently testing if the builds are successful against my fork https://github.com/mohammedzee1000/origin

**Comment by bparees** [comment]
@mohammedzee1000 can you tell us more about the CCCP and why we need configuration for it here?

**Comment by mohammedzee1000** [comment]
CentOS Community Container Pipeline is a project being built as a part of the Red hat Developer Program and Project Atomic. 

It is slated to provide end -to-end container building, testing, delivery and maintenance (CI/CD) from pulling the artifacts, including the dockerfile from a git repository, building the image, running the test cases against it and delivering it to container registries, including a currently being setup centos public registry. 

After delivery, the images will also be maintained ie automatically rebuilt whenever the repository is changed or if any rpms/packages in the built containers are modified/updated.

**Comment by bparees** [comment]
@mohammedzee1000 I think you're going to find you need more than cccp.yml since the dockerfiles in those directories require the entire origin repo be built first to provide the static go binaries that are added to the images by the dockerfiles.

**Comment by mohammedzee1000** [comment]
@bparees 

Is this true for the folders in the images directory as well?
Are you referring to building go files in the repository?

**Comment by bparees** [comment]
> Is this true for the folders in the images directory as well?
> Are you referring to building go files in the repository?

at least some, if not all, of the folders within the images directory contain Dockerfiles that reference go binaries that need to be built out of the origin repository via hack/build-release.sh

**Comment by mohammedzee1000** [comment]
Ok, so i basically need to run hack/build-release.sh before building the images right?

**Comment by bparees** [comment]
yup.

**Comment by bamachrn** [comment]
@bparees is hack/build-release.sh included in Dockerfile, as a step? so that it gets included while building the Dockerfile. Or you run the script manually first then build the docker file?

**Comment by smarterclayton** [comment]
hack/build-release.sh launches the build-cross.sh binary inside a container
that contains our execution environment.  You can run hack/build-cross.sh
from a Linux environment that has access to Windows and Mac OS X Go
cross-compile environments (or disable them with a flag).

The assumption with all image builds is that you have access to the release
zip (hack/build-images.sh)

On Mon, Apr 11, 2016 at 10:57 AM, Bamacharan Kundu <notifications@github.com

**Comment by mohammedzee1000** [comment]
Hi,

We have worked this out with @tdawson from CentOS PaaS sig. @tdawson created docker files with make use of rpms from the CentOS PaaS sig and I am moving to include the same here.

**Comment by tdawson** [comment]
This was done with  pull request #9864
