### ISSUE TITLE
oc import-image doesn't take insecure annotation into consideration when importing

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#8452]
Spawned from #8440.

I create a repository an IS (like the one in #8440) that requires insecure flag, but I don't put it into yaml definition. After creating the IS the import will fail. 
I edit the IS adding `openshift.io/image.insecureRepository="true"` and re-import image with `oc import-image` and the import again fails. But if I add `--inscure` flag to `oc import-image` the import succeeds. Import should take the annotation into consideration.

##### Version
oc v1.1.6-48-g561e4fa
kubernetes v1.2.0-36-g4a3f9c5

@pweil- working on it

**Comment by pweil-** [comment]
@soltysh @smarterclayton - this seems like it should at least make a patch release if not approved for 3.2.  

@soltysh if this is not in 3.2 it probably should be documented as a known issue since it seems like this could be a common use case

**Comment by smarterclayton** [comment]
Would this break a normal admin upgrade / maintenance scenario?  If so it's effectively a regression.

**Comment by soltysh** [comment]
@smarterclayton it might be a regression, since the old import mechanism relied solely on the insecure annotation. The new introduces new, per-tag ImportPolicy, which handles that for us.

**Comment by smarterclayton** [comment]
If it's a regression to an admin update path (@brenton @detiber for opinion) then this is a p0 (or at least, a very spicy p1)

**Comment by brenton** [comment]
Upgrades have other problems that prevent using authenticated registries with our playbooks for now so I don't consider this a blocker for upgrade.

**Comment by smarterclayton** [comment]
I'm referring to this breaking old upgrade paths (i.e. import-image would
now fail on repos that were HTTP).
