### ISSUE TITLE
Update build config name annotation on builds when renaming build config

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#8463]
We should update the build config name annotation when renaming the BC, so we don't loose the reference to BC the builds were started from.

This might affect removing the builds when removing the build config. It might also break serial builds when we can't check what scheduling policy the BC associated with build has.

**Comment by mfojtik** [comment]
@bparees FYI.

**Comment by mfojtik** [comment]
@mnagy we discussed with @bparees that we might switch to a first-class field for a reference to build config instead of an annotation.

**Comment by deads2k** [comment]
How are you going to implement a rename?  A delete and another create probably won't do what you want, since that requires different permissions than an update, must re-run the admission chain, will produce an object with a different UID, and will lose all status information.

**Comment by bparees** [comment]
@deads2k @smarterclayton do we have any rules on updating metadata.name today?

**Comment by deads2k** [comment]
> @deads2k @smarterclayton do we have any rules on updating metadata.name today?

It's disallowed and there's no way to do it.  Deleting and recreating doesn't do the same thing (see my comment above).

**Comment by mfojtik** [comment]
@deads2k so we should forbid renaming existing BC? dunno if that is implemented today.

**Comment by bparees** [comment]
@mfojtik sounds like it's already forbidden.

**Comment by liggitt** [comment]
no object can be renamed today, only deleted and a similar object with a different name created

**Comment by deads2k** [comment]
> @deads2k so we should forbid renaming existing BC? dunno if that is implemented today.

Yes, and it is by the `ValidateObjectMetaUpdate` call in `ValidateBuildConfigUpdate`

**Comment by mfojtik** [comment]
```
[root@localhost vagrant]# oc edit bc/ruby
error: metadata.name should not be changed
```

you're right.

**Comment by mfojtik** [comment]
@deads2k thanks, /me stop panics :-) closing this as no-issue then.

**Comment by deads2k** [comment]
> you're right.

That's actually a different path that gets blocked client-side, but you're still good and we have a test to enforce it: `TestObjectMetaUpdate`
