### ISSUE TITLE
rebase issues

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#8464]
scratchpad for me to keep track of problems as I go.

**Comment by timothysc** [comment]
on 1.3 rebase, we will need to change the defaults that upstream sets for the kubelets.

--pods-per-core=10 
--max-pods=255
xref: https://github.com/kubernetes/kubernetes/pull/25813

We will have benchmark automation in place shortly. 

/cc @rrati @jeremyeder

**Comment by deads2k** [comment]
@mfojtik I think this now yours.

**Comment by jeremyeder** [comment]
Awesome!  Oh, wasn't the max 254?  (openshift-sdn starts handing out IPs at x.x.x.2 within the per-node network segment).

**Comment by timothysc** [comment]
Max on 3.2 is currently 510

**Comment by jeremyeder** [comment]
@mpbarrett

**Comment by timothysc** [comment]
So setting these defaults fell through the cracks.
