### ISSUE TITLE
enable etcd watch cache for origin types

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#8469]
Prevent all watch API calls on origin types from hitting etcd

Requires plumbing storage decorators through all the origin REST handlers

related to https://github.com/openshift/origin/pull/8395

**Comment by danmcp** [comment]
Corresponding Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1333932

**Comment by liggitt** [comment]
fixed by https://github.com/openshift/origin/pull/9057
