### ISSUE TITLE
oc rsh gives inappropriate error

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8472]
Start a restart=Never pod

```
$ oc run --restart=Never dnstest --image=gcr.io/google_containers/dnsutils:e2e -- /bin/sleep 1
# wait 2 seconds
$ oc rsh dnstest
error: unable to upgrade connection: pod does not exist
```

Message should be more accurate - `pod is no longer running`, or even better, a server defined error.  Not sure if this is a problem with rsh, exec, or the kubelet.

**Comment by ncdc** [comment]
This sounds like an rsh issue

**Comment by sttts** [comment]
The error message `pod does not exist` is probably from here: https://github.com/sttts/kubernetes/blob/6224f44717effa17914fac41f13a4f2be7b5c21b/pkg/kubelet/server/server.go#L569-L569

**Comment by smarterclayton** [comment]
This should now be translated into a correct errors.IsNotFound warning on
the client, so we should be able to detect pod not found and give a better
message.

**Comment by sttts** [comment]
The error message from the kubelet is actually not too wrong. I doesn't see a local pod because it terminated. Compare https://github.com/kubernetes/kubernetes/issues/27359, that's the better fix IMO, and inline with kubectl-attach.
