### ISSUE TITLE
oc import-image should inform users about the imported changes

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#8485]
Currently running `oc import-images` returns the description of the image stream. This description isn't helpful as it should inform user what has changed (in case of re-import) or provide more details in case of new IS. See [this comment](https://github.com/openshift/origin/issues/8457#issuecomment-209077542) for more info.

**Comment by soltysh** [comment]
@pweil- mind assigning this one to me?

**Comment by pweil-** [comment]
@soltysh there has also been a request to have a `--dry-run` ability.  Want to make it part of this?

**Comment by soltysh** [comment]
@pweil- prefer a separate one, created: https://github.com/openshift/origin/issues/8486

**Comment by soltysh** [comment]
This was fixed in #10847.
