### ISSUE TITLE
oc import-image add --dry-run

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#8486]
We need `--dry-run` in the `oc import-image` which will present how the image stream will look like but without actual import happening.

**Comment by soltysh** [comment]
@smarterclayton are there any other requirements for the '--dry-run' other
than showing what the IS will look like?

**Comment by bparees** [comment]
oc import-image --dry-run exists now.

not sure it does quite what @soltysh had in mind, but it does show information about the image being imported.

**Comment by soltysh** [comment]
@bparees you present the information during the process, the idea was to create a dummy IS to show the user how the IS will look like. But since the entire process is happening on the server it'd be a speculative show. So I'm fine with this being closed.
