### ISSUE TITLE
Suggestions on OSE Secrets documentation

### ISSUE THREAD

**Issue by thescouser89** [openshift/origin#8496]
The OSE secrets documentation (found [here](https://docs.openshift.com/enterprise/3.0/dev_guide/secrets.html)) does not mention that the value of the secrets have to be base64 encoded.

Another suggestion would be to also say that we can mount those secrets in the deployment config, instead of just showing an example of mounting it into a pod.

**Comment by stevekuznetsov** [comment]
@thescouser89 You may want to duplicate/move this issue to the tracker for [openshift-docs](https://github.com/openshift/openshift-docs)
/cc @deads2k

**Comment by thescouser89** [comment]
Done! https://github.com/openshift/openshift-docs/issues/1895

Closing it.
