### ISSUE TITLE
Provide a way to distinguish hook pods from other deployer pods

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#8498]
All deployer pods (the strategy pod and hook pods) are assigned an `openshift.io/deployer-pod-for.name` label so they can be identified as deployers. However, it's also useful to further identify these pods by their specific role. For example, a label like `openshift.io/deployer-pod.type=strategy` or `openshift.io/deployer-pod.type=pre-hook`.

**Comment by smarterclayton** [comment]
Or annotation in this case.  The hook type will be per strategy, so we should keep in mind that we have to reserve space for the strategy to define its own annotations.

**Comment by legionus** [comment]
@ironcladlou What is the use case for this? Are you going to filter by `openshift.io/deployer-pod.type` or you just want to add an annotation to deployer pod ?

**Comment by kargakis** [comment]
Do we want to filter even between hooks? (pre, mid, post)

**Comment by pweil-** [comment]
> Do we want to filter even between hooks? (pre, mid, post)

seems helpful

**Comment by smarterclayton** [comment]
A naive client, looking at the pods, should know what they are for.  The
closer we can get to the api structures and concepts, the better (i.e. a
simple strategy-hook-type field is enough)

**Comment by kargakis** [comment]
Talked with @legionus and it sounds reasonable to both of us now
