### ISSUE TITLE
Hook pods are not terminated by the deployment controller when a deployment is cancelled or aborted

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8500]
I would expect that we would preserve the invariant that all hook pods have terminated (are in failed/succeeded/deleted) before we launch a new deployer pod, but that appears that is not the case today.  What would we have to change to guarantee that?

@ironcladlou @kargakis

**Comment by pweil-** [comment]
This isn't a regression.  Can we make this a p2 for 3.2?

**Comment by kargakis** [comment]
The deployment controller can try to identify any preexisting deployers for the config of the deployment (before creating the new deployer) and delete if it finds any.

**Comment by smarterclayton** [comment]
Yes post 1.2
