### ISSUE TITLE
Add ability to orchestrate multiple (depending) deployments

### ISSUE THREAD

**Issue by livelace** [openshift/origin#8507]
Main discussion - https://github.com/openshift/jenkins-plugin/issues/33

@ironcladlou

If your concern is the updater scaling up without regards to pod readiness, we'll need to take the discussion to origin/kubernetes, because the rolling updater progresses scale-ups based on replica count of the RC which doesn't take readiness into account.

**Comment by kargakis** [comment]
@smarterclayton I remember you were saying the rolling updater shouldn't care about readiness when scaling up.

**Comment by smarterclayton** [comment]
Growth should not be readiness limited.  Deployments must satisfy their readiness criteria to succeed and ensure that failed deployments are recognized

**Comment by bparees** [comment]
the fundamental issue in my mind is that the replication controller is reporting an active count of 1 despite the fact that the only pod that exists is in a FAILED state.

**Comment by livelace** [comment]
Hello. Any news about this ?

**Comment by kargakis** [comment]
Not really. Unless somebody else wants to take a stab at it (which will first require discussion upstream) I am not going to get at this for some time (most probably not before 1.3)

**Comment by kargakis** [comment]
The gist of what @livelace wants here is that failed container hooks should fail deployments.

**Comment by kargakis** [comment]
> The gist of what @livelace wants here is that failed container hooks should fail deployments.

Actually this already happens with a postStart hook that fails

**Comment by kargakis** [comment]
@GrahamDumpleton also had a request about orchestrating multiple depending deployments

**Comment by livelace** [comment]
It's great :)

**Comment by kargakis** [comment]
AppController seems like it's trying to solve a problem related to this issue:

https://www.youtube.com/watch?v=BXRToNV4Rdw
https://github.com/kubernetes/kubernetes/issues/29453
https://github.com/Mirantis/k8s-AppController

**Comment by smarterclayton** [comment]
We need to see a concrete proposal before we get too excited - they're
not doing a good job of following the Kube process yet, so it's hard
to say how it will fall out.

**Comment by livelace** [comment]
I glad these mechanism are appearing. On video was asked interesting question about conditions between namespaces.

**Comment by kargakis** [comment]
> We need to see a concrete proposal before we get too excited - they're not doing a good job of following the Kube process yet, so it's hard to say how it will fall out.

Having dependecies as third-party object is a nice idea. Maybe something we can think about more when we introduce a graph API? cc: @deads2k

**Comment by deads2k** [comment]
> Having dependecies as third-party object is a nice idea. Maybe something we can think about more when we introduce a graph API? cc: @deads2k

Depends on how tightly you want to control ACLs.  Assuming you want the correct data and you can't leak information, you cannot pre-compute all possible dependency graphs to show to a user.  Inside a project its probably possible, but since projects in openshift depend on external projects for things like images and builds, an editor in project A does not have the same access another editor in A that also has access to B.  They should get different graphs.

Precomputation is an interesting though for a few common cases, but stitching would still be required.

**Comment by kargakis** [comment]
Closing in favor of https://trello.com/c/3WmAlsu8/509-ability-to-chain-deployments-evg
