### ISSUE TITLE
Compatibility with docker-engine RPMs

### ISSUE THREAD

**Issue by hrobertson** [openshift/origin#8508]
It would be desirable to have the flexibility to use the latest `docker-engine` RPMs with Origin.

The origin RPM spec requires `docker-io`.
The [RPMs published by Docker](https://github.com/docker/docker/tree/master/hack/make/.build-rpm) provide `docker-engine`, and conflict with `docker` and `docker-io`

[Boolean dependencies](https://fedoraproject.org/wiki/Packaging:Guidelines#Rich.2FBoolean_dependencies) do not work for `Requires:` or `Recommends:` 

What can be done to resolve this?

Discussed with @sdodson on IRC.

**Comment by sahlex** [comment]
vote++

**Comment by brenton** [comment]
We already support a number of container runtimes and we aren't currently planning support for Docker rpms.
