### ISSUE TITLE
Enabling the Start Build button

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#8510]
There is going to be change in the way in what order the builds will get fired(parallel vs. serial), where serial will be default. In that case it doesn't make sense to disable the `Start Build` button when launching a build or have a running build.
In case of parallel build order it does make sense to have it disabled, although not necessarily. 
Based on  https://github.com/openshift/origin/pull/8453 PR
@jwforres @spadgett

**Comment by jwforres** [comment]
If they are choosing to have parallel builds then that implies their builds can run in parallel and we probably shouldn't disable it.

**Comment by mfojtik** [comment]
@jwforres is the logic here that the button is disabled until the build completes? that kinda mimic the serial builds in a creepy way in web console... I can still go to `oc` and start 10 parallel builds.

I think the main reason that disabling existed is to prevent users fat-fingering that button and accidentally starting more builds that they wanted. Maybe that can be solved by disabling the button for 1s after user clicked on it... I doubt there is a person on this planet that has double-click interval set to more than 1s :)

**Comment by jwforres** [comment]
On Thu, Apr 14, 2016 at 9:24 AM, Michal Fojtik <notifications@github.com>
wrote:

> @jwforres <https://github.com/jwforres> is the logic here that the button
> is disabled until the build completes? that kinda mimic the serial builds
> in a creepy way in web console...
>
Exactly why I want to remove it :)  we were doing it because we knew there
were issues with the docker push (at the time we did it) if people launched
multiple builds at once.


> I can still go to oc and start 10 parallel builds.
>
> I think the main reason that disabling existed is to prevent users
> fat-fingering that button and accidentally starting more builds that they
> wanted. Maybe that can be solved by disabling the button for 1s after user
> clicked on it... I doubt there is a person on this planet that has
> double-click interval set to more than 1s :)
>
What we should do is disable it until the request to create the build comes
back, at which point it pops up the success (or failure) message at the top
of the page.

**Comment by jwforres** [comment]
fixed
