### ISSUE TITLE
Websocket watch against openshift resources that dont support watch is behaving like a list

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#8518]
Open a websocket watch against a resource like rolebindings and it will attempt to return a 200 with the JSON list response.  This confuses browsers that aren't expecting to see a 200 on a websocket upgrade request.

Arguably this should throw something like a 405 method not allowed instead.  Although it feels wrong to reuse 405 for that.

cc @deads2k @liggitt

**Comment by liggitt** [comment]
Happened when Watch collapsed to List with `watch:true` in ListOptions. Custom List impls that don't support watch have to explicitly check if `options.watch==true` and fail.

**Comment by benjaminapetersen** [comment]
Being able to watch resources like `rolebindings` would be useful. Is updating to `405 method not allowed` preferred to supporting the watch?

**Comment by liggitt** [comment]
performant watch is not possible on that resource at the moment, since it is a virtual projection of the resources contained within the policybindings object. (the same goes for roles within policy, clusterroles within clusterpolicy, and clusterrolebindings within clusterpolicybindings)

**Comment by benjaminapetersen** [comment]
Ok that makes sense.  Thx!

**Comment by benjaminapetersen** [comment]
We have since updated the console to `rbac`, so for us I think this issue has gone away. Perhaps we can close it?

@enj thoughts?

**Comment by jwforres** [comment]
if this only affected the RBAC related APIs sure, but if we had any other virtual resources impacted by this we should keep it open until those also move upstream or the issue is fixed

/remove-lifecycle stale

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/commit/da8ae29620811f3dc058e0e665d402a208a1fe6c in 3.7

/close
