### ISSUE TITLE
Build error is not communicated to the user when ImageStream is missing

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#8523]
When creating an application from a template, the build fails silently if the referenced ImageStream does not exist. From the user's perspective there are no errors and at the same time no pods or builds get created:
```
$ oc get pods
$ oc get builds
$ oc get events
```

All the above return empty result. The error is only visible on the master node through _journalctl_:
```
$ sudo journalctl | grep employee-app
Apr 15 09:32:01 rhel-cdk sh[18153]: E0415 09:32:01.650542   18313 config_controller.go:55] error instantiating Build from BuildConfig eap7/employee-app: imageStream "jboss-eap70-openshift" not found

```

##### Version
oc v3.1.0.4-16-g112fcc4
kubernetes v1.1.0-origin-1107-g4c8e6f4
openshift v3.1.0.4-16-g112fcc4
etcd 2.1.2

##### Steps To Reproduce

$ oc new-project eap7
$ oc create -f https://raw.githubusercontent.com/siamaksade/wildfly-swarm-hystrix-example/eap7/eap7-microservices-example.yaml
$ oc new-app eap7-microservices-example

##### Current Result
Build fails silently and no errors are communicated to the user.

##### Expected Result
The user needs to be notified (through events?) that build is failing due to missing Image Stream.

**Comment by bparees** [comment]
if you run oc start-build you'll get the error that the imagestream is missing
also oc status -v will show you that the imagestream is missing.

we can consider adding an event to the buildconfig.

**Comment by mmilata** [comment]
FYI `oc status -v` doesn't actually show that the imagestream is missing, this is what I get: https://gist.github.com/mmilata/99820147a40dd646e2af593a0fa0f492

**Comment by bparees** [comment]
@mmilata hm.  it should.  that should be fixed as part of fixing this.  you can talk to @gabemontero as he's done a lot of improvements to oc status (he may also know if it used to warn you in this case or why it doesn't)

**Comment by gabemontero** [comment]
I tried:
```
$ oc create -f https://raw.githubusercontent.com/siamaksade/wildfly-swarm-hystrix-example/eap7/eap7-microservices-example.yaml
$ oc new-app eap7-microservices-example
```
and I am not sure what are the missing ImageStreams.  When I run `oc get is`, I see a bunch of ImageStreams were added to my project:

```
$ oc get is
NAME                   DOCKER REPO                                   TAGS      UPDATED
employee-app           172.30.79.35:5000/test/employee-app                     
hystrix-dashboard      172.30.79.35:5000/test/hystrix-dashboard                
payroll-app            172.30.79.35:5000/test/payroll-app                      
turbine                172.30.79.35:5000/test/turbine
```

There is code in oc status to check for missing image streams:  https://github.com/openshift/origin/blob/master/pkg/build/graph/analysis/bc.go#L85-L130

Running both standalone and in the debugger, I see the same thing as what was posted in the gist here:  https://gist.github.com/mmilata/99820147a40dd646e2af593a0fa0f492#file-gistfile1-txt-L32-L39

The image stream exists, but the needed images themselves are missing.

**Comment by bparees** [comment]
@gabemontero the scenario in question is:  create a buildconfig that contains a from reference to a non-existent imagestream.

if you try to "oc start-build" that BC, you'll get an error that the imagestream does not exist.
but if you run oc status, it does not give you any warning.

the errors you highlighted are for imagestreams associated with the DC, not the BC.

**Comment by bparees** [comment]
i'm not sure what i did earlier but here's a proper recreate that does show @gabemontero is correct that the input imagestream missing warning exists in oc status:

```
sample-app (master)$ oc start-build ruby-sample-build
Error from server: Internal error occurred: imagestreams "ruby-22-centos7" not found
```

```
sample-app (master)$ oc status -v
In project p1 on server https://localhost:8443

bc/ruby-sample-build source builds https://github.com/openshift/ruby-hello-world.git on istag/ruby-22-centos7:latest
  -> istag/origin-ruby-sample:latest
  not built yet

Errors:
  * bc/ruby-sample-build is pushing to istag/origin-ruby-sample:latest, but the image stream for that tag does not exist.
Warnings:
  * bc/ruby-sample-build builds from istag/ruby-22-centos7:latest, but the image stream tag does not exist.
    try: istag/ruby-22-centos7:latest needs to be imported.
  * istag/origin-ruby-sample:latest needs to be imported or created by a build.
    try: oc start-build ruby-sample-build

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```

**Comment by bparees** [comment]
@gabemontero the warning does not appear when the non-existent imagestream reference is outside the project, from what i can tell:

```
$ oc status -v
In project p1 on server https://localhost:8443

bc/ruby-sample-build source builds https://github.com/openshift/ruby-hello-world.git on openshift/ruby-22-centos7:latest
  not built yet

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```

```
$ oc describe bc ruby-sample-build
Name:		ruby-sample-build
Namespace:	p1
Created:	5 minutes ago
Labels:		app=ruby-helloworld-sample
		name=ruby-sample-build
		template=application-template-stibuild
Annotations:	openshift.io/generated-by=OpenShiftNewApp
Latest Version:	2

Strategy:		Source
URL:			https://github.com/openshift/ruby-hello-world.git
From Image:		ImageStreamTag openshift/ruby-22-centos7:latest
```

so there's still some things that need to be sorted out here.

also this message should report the namespace of the imagestream (for my BC, the reference is to the "openshift" namespace, but there's no evidence of that in the error)
```
$ oc start-build ruby-sample-build
Error from server: Internal error occurred: imagestreams "ruby-22-centos7" not found
```

**Comment by gabemontero** [comment]
From my experience I'm not sure that oc status deals with cross project
concerns.  We'd have to pull in
to status originators/experts there.  If correct that correlates to your
message concern as well.

**Comment by bparees** [comment]
To summarize:

1) we need to fix the oc start-build error so it reports the namespace of the missing imagestream
2) we need to fix oc status -v so it reports missing imagestreams when the imagestream references are to imagestreams that are in another namespace (it appears to only warn for unresolveable references to the current namespace today)
3) we need to fix the original issue that was reported that the buildconfig gives no indication of why the build is stuck, in the case that a build does get created (eg by a trigger).  Though first i'd like to understand how that build is even getting created successfully since the instantiate endpoint should have gotten an error.

(was writing this as @gabemontero's comment came in, so we can discuss (2) with @kargakis, but (1) is still a problem and i think i've argued about whether oc status should be cross cutting or not before, it seems silly for it not to be, for something like this)

**Comment by bparees** [comment]
the oc start-build message looks to be a direct pass-thru of a notfound error coming back from the get imagestream api call, so the change might require an upstream change to that error message:
https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L586-L592

**Comment by kargakis** [comment]
We have disabled cross-namespace warnings because they get complicated with
respect to permissions: https://github.com/openshift/origin/pull/7216

**Comment by mmilata** [comment]
@bparees I've updated #10868 to include namespace in the error message (1). The commit also makes BuildConfig emit an event whenever this happens (3). I haven't managed to make the BuildConfig create a failing build, any suggestion how is that possible?

Not sure what to do about 2).

**Comment by bparees** [comment]
@mmilata i think the answer for (2) is "nothing" for now, if oc status is drawing a line in the sand about going cross-namespace, but it's unfortunate since cross-namespace imagestream references are a pretty common thing to do.
