### ISSUE TITLE
Watch projects on the project list in the console

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#8524]
Add watcher that will watch for updates in the list of projects on the root page, since ATM the page has to be refreshed to get the update.
@jwforres thoughts ?

**Comment by jwforres** [comment]
@jhadvig projects don't support watch, at one point @deads2k was looking at implementing it, not sure where that ended up...

**Comment by deads2k** [comment]
https://github.com/openshift/origin/pull/6828  Its on my "day or so from completion, but no one wants it as badly as other things" list.

**Comment by spadgett** [comment]
This has been implemented.
