### ISSUE TITLE
Docker Hub description for origin-deployer has dead links.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#8533]
On the page:

* https://hub.docker.com/r/openshift/origin-deployer/

on Docker Hub, the description for origin-deployer image has a link to GitHub for the image of:

* https://github.com/openshift/origin/blob/master/images/deploy/customimage

This doesn't work.

Perhaps should be:

* https://github.com/openshift/origin/tree/master/images/deployer

**Comment by danmcp** [comment]
Fixed.
