### ISSUE TITLE
Enabling WebHooks from web console doesn't add Generic WebHook.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#8536]
On 1.1.6 in all in one VM, if you create a build configuration via a template in web console and you do not include triggers for WebHooks in templates, then none is included as expected.

If you now go into the Edit page of the build configuration through the web console and select:

* Enable the webhook build trigger

then that only adds a GitHub WebHook and does not add or provide a way of adding a Generic WebHook.

The only way to add a Generic WebHook through the web console is to edit the YAML and add in appropriate triggers section manually.

It would be nice if the web console interface supported a simple way of adding a Generic WebHook as it does for GitHub WebHook.

For background, although Generic WebHooks possibly are very little used and that may be why isn't done by default, I will be releasing example OpenShift project for deploying Kallithea SCM and since it doesn't by default provide WebHook support builtin, I have implemented an extension for Kallithea for OpenShift Generic WebHook. As far as SCM solution goes, lot easier to deploy locally than GitLab as can be done as one click template and builds stuff using S2I.

**Comment by jwforres** [comment]
This just seems like a bug, we set up both from the initial create flow.

**Comment by jwforres** [comment]
this was fixed
