### ISSUE TITLE
Retrieve build metadata (image labels) from downwards API

### ISSUE THREAD

**Issue by danni** [openshift/origin#8537]
It would be useful to get the build metadata (as shown on the overview) in the downward API for a pod, so that it can be included in error and performance reports.

**Comment by bparees** [comment]
@danni so you want to be able to create a pod who's definition includes references to fields/metadata from an existing Build object in your namespace?

**Comment by danni** [comment]
The metadata the overview shows, those docker image LABELs. Maybe the image
LABELs could be written into the annotation.

The sort of things I'm looking to record in our monitoring is what build an
error/performance issue is associated with. Also the SCM labels would be
useful so I don't need to have Git in my container to retrieve them.

**Comment by bparees** [comment]
@mfojtik i think this is your area.  Sounds like the idea is to make the docker image labels available as annotations on the imagestreamtag, i think?  Not sure if it's worth it since all that metadata should be available on the imagestreamimage object already, though.

**Comment by mfojtik** [comment]
@bparees i guess this depends on https://trello.com/c/RPTugJoZ/515-5-registry-import-docker-labels-as-annotations

**Comment by bparees** [comment]
@danni I think i'm still ultimately unclear on what you're looking for here.  Can you share a screenshot showing the bits of information you see in the console for which you want to have a mechanism to put that information onto a pod?
