### ISSUE TITLE
Pacemaker to Native : Kubernetes endpoints are not updated when a master is down

### ISSUE THREAD

**Issue by augabet** [openshift/origin#8542]
We switched our **two masters from Pacemaker to Native**, running the ansible playbook, and following [the documentation](https://docs.openshift.org/latest/install_config/upgrading/pacemaker_to_native_ha.html).

When we are stopping **one of both** masters, the **kubernetes endpoint still references both masters**, making deploy **failing one in two requests**. The masterCount in the master-config.cfg is set to 2.
##### Version

Openshift version : oc v1.1.6
##### Steps To Reproduce
1. Upgrade your 2 masters from Pacemaker to native
2. `dig @172.30.0.1 kubernetes.default.svc.cluster.local` should work every time
3. switch off one of both masters
4. `dig @172.30.0.1 kubernetes.default.svc.cluster.local` should work one of two requests
##### Current Result

```
[root@master1-ci ~]# oc get ep kubernetes -n default -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2016-04-14T08:16:16Z
  name: kubernetes
  namespace: default
  resourceVersion: "4092"
  selfLink: /api/v1/namespaces/default/endpoints/kubernetes
  uid: 28c4ecdf-0219-11e6-a0ec-005056bd6f0e
subsets:
- addresses:
  - ip: 192.168.0.121
  - ip: 192.168.0.122
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns
    port: 53
    protocol: UDP
  - name: https
    port: 8443
    protocol: TCP
```
##### Expected Result

The endpoints should be updated when one of the two master is down, OR the pods should try to reach the kubernetes API more than once.

**Comment by brenton** [comment]
@abutcher, @sdodson The upcoming DNS work that's landing should address this, right?

**Comment by sdodson** [comment]
The dnsmasq work i'm doing relies on the kubernetes service ip being available to answer skydns queries. I guess we could switch that work to use either the master IP or the master VIP instead. As long as haproxy does the right thing that'd help. However I'm not sure that we can expect everyone to have 8053 open on their master VIP, we'd have to ammend our documentation.

Here's the bug that deals with failed API servers not properly updating endpoints https://bugzilla.redhat.com/show_bug.cgi?id=1300028

@DirectXMan12 @ncdc any opinion on whether we should utilize skydns via a cluster vip rather than kubernetes svc ip based on the work in the bug above?

**Comment by abutcher** [comment]
Upstream PR from the bug: https://github.com/kubernetes/kubernetes/pull/20975

**Comment by ncdc** [comment]
@sdodson "cluster vip" meaning what specifically here? cc @smarterclayton 

Assuming the solution in pr 20975 for bz 1300028  is sufficient, I would like to close this so we don't have 2 places tracking the same bug.

**Comment by sdodson** [comment]
> @sdodson "cluster vip" meaning what specifically here? cc @smarterclayton

The hostname of the load balancer in front of our api-servers. +1 to just fixing kube svc endpoint

**Comment by augabet** [comment]
Thank you all. We will use Pacemaker waiting the K8S PR then. What do you think about a warning in the Openshift Origin documentation ?

**Comment by barkbay** [comment]
Pacemaker is no more an option in Origin 1.2 : https://github.com/openshift/openshift-ansible/commit/039dda58b3cd9b34abccf1f8f46eb825c1d45545

If I understand correctly without https://github.com/kubernetes/kubernetes/pull/20975 there will be no way to have a reliable H.A. deployment

**Comment by abutcher** [comment]
@augabet +1 for a warning.

@barkbay That is correct. Without kubernetes/kubernetes#20975, the dns endpoint would need to be balanced/maintained externally.
