### ISSUE TITLE
Contributing doc for using vagrant as dev environment fails on fedora 23

### ISSUE THREAD

**Issue by crobby** [openshift/origin#8554]
When following https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-on-virtual-machine-using-vagrant on a fresh fedora 23 machine, things seem to work until I attempt to access https://localhost:8443, I only see the following error.

> 
> The connection to localhost:8443 was interrupted while the page was loading.
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.

##### Version
openshift v1.1.6-46-g9eaae7c-dirty
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

##### Steps To Reproduce
1. Follow the guide at https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-on-virtual-machine-using-vagrant 

It should be noted that I had to open up some firewall rules to get the nfs mounts to work.  Perhaps the guide could mention that as well.  

##### Current Result
https://localhost:8443 only shows an error

##### Expected Result
https://localhost:8443 shows the openshift web console

##### Additional Information
This is happening to me on a fresh fedora 23 workstation environment.  I'm guessing that network or firewall seems the likely suspect, but I'm too new to origin to know for sure.

**Comment by liggitt** [comment]
accessing an https server using self-signed certificates will show that prompt

**Comment by crobby** [comment]
I do not get an option to bypass/accept it like I do on other sites with
self-signed certs.  I see similar behavior on both firefox and chrome.


The Firefox error looks like this:
Secure Connection Failed

The connection to localhost:8443 was interrupted while the page was loading.

    The page you are trying to view cannot be shown because the
authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…


The Chrome error looks like this:
This site can’t be reached

*localhost* unexpectedly closed the connection.

Try:

   - Reloading the page
   - Checking the connection
   - Checking the proxy and the firewall

**Comment by liggitt** [comment]
What details are under the "learn more" link?

**Comment by crobby** [comment]
It is a link to:
https://support.mozilla.org/en-US/kb/what-does-your-connection-is-not-secure-mean

**Comment by liggitt** [comment]
Are you accessing the console with either the --master or --public-master address (or the detected master IP if you aren't providing either of those?)

**Comment by crobby** [comment]
Per the guide, I'm using `sudo `which openshift` start
--public-master=localhost &> openshift.log`

Netstat on my host shows:
netstat -anp | grep 8443
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:8443          0.0.0.0:*
LISTEN      12561/ssh
tcp6       0      0 ::1:8443                :::*
LISTEN      12561/ssh

In my vagrant host, openshift.log shows...
W0418 22:01:00.750058   29346 start_master.go:270]
assetConfig.loggingPublicURL: Invalid value: "": required to view
aggregated container logs in the console
W0418 22:01:00.750098   29346 start_master.go:270]
assetConfig.metricsPublicURL: Invalid value: "": required to view cluster
metrics in the console
I0418 22:01:00.757048   29346 plugins.go:71] No cloud provider specified.
I0418 22:01:00.758923   29346 genericapiserver.go:81] Adding storage
destination for group
I0418 22:01:00.758956   29346 genericapiserver.go:81] Adding storage
destination for group extensions
I0418 22:01:00.758968   29346 start_master.go:383] Starting master on
0.0.0.0:8443 (v1.1.6-46-g9eaae7c-dirty)
I0418 22:01:00.758971   29346 start_master.go:384] Public master address is
https://localhost:8443
I0418 22:01:00.758978   29346 start_master.go:388] Using images from
"openshift/origin-<component>:v1.1.6"

**Comment by crobby** [comment]
Ok, maybe on to "something".  On my vagrant box, whenever I try to connect
via my browser to https://localhost:8443, my journalctl -f gives me the
following line:

Apr 18 22:09:53 localhost.localdomain sshd[2042]: error: connect_to
192.168.121.215 port 8443: failed.  For what it's worth 192.168.121.215 is
the IP address of the vagrant box.

Seems to point to a potential network/firewall issue or maybe the openshift
master isn't up and running somehow?

**Comment by crobby** [comment]
Also noteworthy perhaps, on my vagrant machine, netstat is not showing port
8443, so it makes sense that nothing could  connect to that port.

**Comment by crobby** [comment]
Ok...I tried these same steps on an Ubuntu 15 machine and I got an instance up and running.  When I ran the openshfit start command there [where it worked], I got the following in openshift.log

Generated new key pair as openshift.local.config/master/serviceaccounts.public.key and openshift.local.config/master/serviceaccounts.private.key
W0419 15:23:24.017173   22886 start_master.go:270] assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
W0419 15:23:24.018079   22886 start_master.go:270] assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console
I0419 15:23:24.065009   22886 plugins.go:71] No cloud provider specified.
I0419 15:23:24.069424   22886 genericapiserver.go:81] Adding storage destination for group 
I0419 15:23:24.069550   22886 genericapiserver.go:81] Adding storage destination for group extensions
I0419 15:23:24.069879   22886 start_master.go:383] Starting master on 0.0.0.0:8443 (v1.1.6-46-g9eaae7c)
I0419 15:23:24.069949   22886 start_master.go:384] Public master address is https://localhost:8443
I0419 15:23:24.070260   22886 start_master.go:388] Using images from "openshift/origin-<component>:v1.1.6"
I0419 15:23:24.119537   22886 run.go:61] Started etcd at 10.0.2.15:4001
I0419 15:23:24.151452   22886 run_components.go:204] Using default project node label selector: 
W0419 15:23:24.441242   22886 controller.go:262] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[]} [{[{10.0.2.15 <nil>}] [] [{https 8443 TCP} {dns 53 UDP} {dns-tcp 53 TCP}]}]}
I0419 15:23:24.675296   22886 master.go:262] Started Kubernetes API at 0.0.0.0:8443/api/v1
I0419 15:23:24.675544   22886 master.go:262] Started Kubernetes API Extensions at 0.0.0.0:8443/apis/extensions/v1beta1
I0419 15:23:24.675815   22886 master.go:262] Started Origin API at 0.0.0.0:8443/oapi/v1
I0419 15:23:24.676054   22886 master.go:262] Started OAuth2 API at 0.0.0.0:8443/oauth
I0419 15:23:24.676454   22886 master.go:262] Started Web Console 0.0.0.0:8443/console/
I0419 15:23:24.676741   22886 master.go:262] Started Swagger Schema API at 0.0.0.0:8443/swaggerapi/
I0419 15:23:24.819084   22886 ensure.go:219] No cluster policy found.  Creating bootstrap policy based on: openshift.local.config/master/policy.json


On my broken (Fedora 23) setup, I see the following in openshift.log

W0419 15:28:35.227829   24017 start_master.go:270] assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
W0419 15:28:35.227881   24017 start_master.go:270] assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console
I0419 15:28:35.234585   24017 plugins.go:71] No cloud provider specified.
I0419 15:28:35.236482   24017 genericapiserver.go:81] Adding storage destination for group 
I0419 15:28:35.236499   24017 genericapiserver.go:81] Adding storage destination for group extensions
I0419 15:28:35.236511   24017 start_master.go:383] Starting master on 0.0.0.0:8443 (v1.1.6-46-g9eaae7c-dirty)
I0419 15:28:35.236520   24017 start_master.go:384] Public master address is https://localhost:8443
I0419 15:28:35.236528   24017 start_master.go:388] Using images from "openshift/origin-<component>:v1.1.6"

...and that's it.  It doesn't seem to move on to start etcd, kubernetes, origin, oauth, web console, swagger.  I'm not seeing any errors reported anywhere, but it does seem to indicate that those services are not being started for me.

**Comment by crobby** [comment]
Ok, somehow, this is working for me now.  I might have been issuing the start openshift command from the wrong directory, that's the only thing I can think of, which I wouldn't think would make the difference, but it certainly did in my case.  I'm happy to close this.
