### ISSUE TITLE
Integrated sky dns can't resolve service short hostname in pod

### ISSUE THREAD

**Issue by dragon9783** [openshift/origin#8556]
[Description]
Integrated sky dns can't resolve service short hostname in pod

##### Version
Openshift 1.1.6

##### Steps To Reproduce
1.  oc get service
2.  oc rsh pod-name
3. ping service-name (short hostname), can't resolve 
4. ping service-name.project-name.svc.cluster.local, resolve correct ipaddress  

##### Current Result
can't resolve with service short hostname 
##### Expected Result
resolve success 
##### Additional Information
/etc/resolve.conf in pod have correct config, search domain have project-name.svc.cluster.local svc.cluster.local

Anyone have idea on this, thanks

**Comment by jimmidyson** [comment]
This can be to do with the base image you're using. One example is if you're using Alpine Linux as a base image this has different semantics in how it tries to resolve addresses, e.g. only uses DNS search domains in alpine:edge IIRC.

**Comment by smarterclayton** [comment]
We have a fix for this in https://github.com/openshift/origin/pull/8474 where we switch to recursive by default

**Comment by dragon9783** [comment]
Thanks for your response
