### ISSUE TITLE
oc status take on host ports and deployments

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8559]
> Also, remind me to check to see if there's any sane way to indicate that a dc is doomed if it tries to scale up before scale down with a single node and a host port. @kargakis. oc status can't do it since users don't know about nodes.

and 

> Apart from simple scaling (which in terms of oc status would be a warning), another warning (or maybe error since it blocks deployments) would be a set maxSurge and no unavailability when nodes/pods (with host ports) == 1. Supposing we add such warnings.

@deads2k forked from https://github.com/openshift/origin/issues/8338 which is a different issue.

**Comment by deads2k** [comment]
@smarterclayton would be possible with a server-side graph API.
