### ISSUE TITLE
X509v3 Subject Alternative Name:

### ISSUE THREAD

**Issue by hingstarne** [openshift/origin#856]
Hi all,

when i inspect the master certificate i miss the fqdn of the master that is used in the cluster.
For inspection i use
<code>
openssl x509 -text -noout -in ./openshift.local.certificates/master/cert.crt
</code>

And the result is just giving me all the ip addresses of my system.

In the logs of a minion this leads to a quite self explaining error message

<code>
reflector.go:85] Failed to list *api.Service: Get https://host.example.com:8443/api/v1beta1/services: x509: certificate is valid for 127.0.0.1, xx.xxx.xxx.xxx, 172.17.42.1, localhost, not host.example.com
</code>

The version i use is

<code>
openshift version
openshift v0.2.1-152-gb24e846fee035a
kubernetes v0.9.0-391-ge335e2d
</code>

**Comment by smarterclayton** [comment]
If you set `--public-master` when the cert is generated, the cert should be available.  Is that the case?

**Comment by hingstarne** [comment]
Thank you @smarterclayton .
This seams to work, but i assume this should be default behaviour because most of the user would prefer dns entries over ip adresses.

**Comment by smarterclayton** [comment]
If you specify public-master - many of those other addresses should be removed (but aren't today).
