### ISSUE TITLE
`oc new-app -p` is inconsistent with `oc process -v`

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#8577]
`oc new-app` and `oc process` use a different flag name for the same concept of supplying template parameters. Since they both do the same thing with templates, this should be consistent.
##### Version

oc v1.1.6-88-gbaf4504
kubernetes v1.2.0-36-g4a3f9c5
##### Steps To Reproduce
1. `oc new-app -h |& grep pairs`
2. `oc process -h |& grep pairs`
##### Current Result

```
$ oc new-app -h |& grep pairs
  -e, --env=[]: Specify key value pairs of environment variables to set into each container.
  -p, --param=[]: Specify a list of key value pairs (e.g., -p FOO=BAR,BAR=FOO) to set/override parameter values in the template.
$ oc process -h |& grep pairs                                                                                                                                                       
  -v, --value=[]: Specify a list of key-value pairs (eg. -v FOO=BAR,BAR=FOO) to set/override parameter values
```
##### Expected Result

```
$ oc new-app -h |& grep pairs
  -e, --env=[]: Specify key value pairs of environment variables to set into each container.
  -v, --value=[]: Specify a list of key value pairs (e.g., -p FOO=BAR,BAR=FOO) to set/override parameter values in the template.
```

(I suggest deprecating -p and using -v as `oc process` was around first)

**Comment by sosiouxme** [comment]
@csrwng your opinion welcome...

**Comment by csrwng** [comment]
@sosiouxme I would tend to favor -p just because -v means verbose in a lot of other commands, and they are template 'parameters' (https://github.com/openshift/origin/blob/master/pkg/template/api/types.go#L16). But I agree that either way, we should make them consistent.

**Comment by sosiouxme** [comment]
Yeah it's fine with me either way.
