### ISSUE TITLE
Cannot push to registry based on dns

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#8581]
Builds cannot push to the registry when OPENSHIFT_DEFAULT_REGISTRY=docker-registry.default.svc.cluster.local because they at least lack secrets, possibly other things. I wasn't able to follow all the technical details, but for some reason secrets aren't generated when using dns name.

There may be other issues too. @liggitt and @csrwng mentioned these as being related
https://github.com/openshift/origin/issues/6924
https://github.com/openshift/origin/issues/1723
https://github.com/openshift/origin/issues/6283
https://github.com/openshift/origin/pull/6385

##### Version
oc v3.2.0.18 (basically origin master)
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. Provision Origin 1.2 / OSE 3.2 environment with node dnsmasq
2. Add OPENSHIFT_DEFAULT_REGISTRY=docker-registry.default.svc.cluster.local to /etc/sysconfig/origin-master restart if necessary
3. Provision registry.
3. Run an S2I build

##### Current Result
```
I0420 17:46:43.881001       1 sti.go:269] No push secret provided
I0420 17:46:43.881014       1 sti.go:271] Pushing docker-registry.default.svc.cluster.local:5000/test/cakephp-example:latest image ...
F0420 17:46:43.910780 1 builder.go:204] Error: build error: Failed to push image. Response from registry is: Post http://docker-registry.default.svc.cluster.local:5000/v2/test/cakephp-example/blobs/uploads/: no basic auth credentials
```

##### Expected Result
success

##### Additional Information
oadm diagnostics yields this too
```
ERROR: [DClu1019 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:319]
       Diagnostics created a test ImageStream and compared the registry IP
       it received to the registry IP available via the docker-registry service.
       
       docker-registry      : 172.30.159.1:5000
       ImageStream registry : docker-registry.default.svc.cluster.local:5000
       
       They do not match, which probably means that an administrator re-created
       the docker-registry service but the master has cached the old service
       IP address. Builds or deployments that use ImageStreams with the wrong
       docker-registry IP will fail under this condition.
       
       To resolve this issue, restarting the master (to clear the cache) should
       be sufficient. Existing ImageStreams may need to be re-created.
```

**Comment by liggitt** [comment]
the dockercfg format is keyed by server, and the generated secrets for the internal registry only include the registry service IP, not the internal hostname(s) or any hosts for routes pointing at the registry service. @deads2k had https://github.com/openshift/origin/pull/6385 in progress as a first refactor to begin allowing using the generated dockercfg secrets to automatically match the dns names

**Comment by sdodson** [comment]
@pweil- is this something we'll try to have in 3.2.1?

**Comment by pweil-** [comment]
> is this something we'll try to have in 3.2.1

No.  If we can get #6385 in then this is more likely to be a 3.3.X item based on the current workload.

**Comment by sferich888** [comment]
@sdodson https://github.com/openshift/origin/pull/9306 the pr that supersedes #6385 is done and complete. Do we have a blocker to merging this?

**Comment by sdodson** [comment]
@sferich888 I don't know. I'd look to the origin team to close this once they've verified that the registry can be pushed to via DNS.

**Comment by deads2k** [comment]
> @sferich888 I don't know. I'd look to the origin team to close this once they've verified that the registry can be pushed to via DNS.

Secrets are now created with DNS names.

**Comment by sdodson** [comment]
@csrwng Do you mind verifying that we can now push to the registry via DNS?

**Comment by deads2k** [comment]
We end at `.svc` so that we don't have to regenerate on suffix changes.

**Comment by csrwng** [comment]
@sdodson Yes, I can confirm that a bc with an output image like: `docker-registry.default.svc:5000/develop/simple-ruby:latest` will work

Note that other host names that you could use to point to the registry such as `docker-registry.default` or `docker-registry.default.svc.cluster.local` will not work. It has to end in `svc` as @deads2k points out above.

The other thing is that your node needs to point to the cluster dns server and also have 'cluster.local' as a search suffix.

**Comment by sdodson** [comment]
> Note that other host names that you could use to point to the registry such as docker-registry.default or docker-registry.default.svc.cluster.local will not work. It has to end in svc as @deads2k points out above.

Can we re-consider this limitation? This means we'd have to add cluster.local to the search path on the host in order for this to work and I don't think that we should do that. I can understand the desire to avoid suffix changes but is that something we generally try to accommodate? I imagine most of the cluster will break on suffix changes.

**Comment by deads2k** [comment]
> Can we re-consider this limitation? This means we'd have to add cluster.local to the search path on the host in order for this to work and I don't think that we should do that. I can understand the desire to avoid suffix changes but is that something we generally try to accommodate? I imagine most of the cluster will break on suffix changes.

@mfojtik

**Comment by wanghaoran1988** [comment]
@mfojtik bump, will we have updates about the limitation ?

**Comment by mfojtik** [comment]
@deads2k do we want to read the suffix from the master-config or is there a way to get it?

**Comment by mfojtik** [comment]
@deads2k the only place I see this set is:

```
pkg/cmd/server/start/node_args.go
122:		ClusterDomain: cmdutil.Env("OPENSHIFT_DNS_DOMAIN", "cluster.local"),
```

I wonder if we can use the same to set the suffix in dockercfg controller.

**Comment by mfojtik** [comment]
@wanghaoran1988 with https://github.com/openshift/origin/issues/12244 and https://github.com/openshift/origin/pull/11391 merge it will be possible to expose the Docker Registry via Route and then set the OPENSHIFT_DEFAULT_REGISTRY to that Route host. So basically it will be possible to use any custom DNS for registry and the builds should work fine.

**Comment by sdodson** [comment]
We're ok with pushing a bunch of internal only traffic needlessly through the router?

**Comment by mfojtik** [comment]
you can setup ssl route right?

-- 
Michal Fojtik

**Comment by wanghaoran1988** [comment]
@mfojtik Thanks, this will only work for insecure registry, right ?

**Comment by mfojtik** [comment]
@wanghaoran1988 should work for both (if there is TLS, the credentials will get :433 suffix)
