### ISSUE TITLE
Builder panics if Dockerfile missing

### ISSUE THREAD

**Issue by phemmer** [openshift/origin#859]
[`docker.go` line 143 & 144](https://github.com/openshift/origin/blob/08ec9c1d558bb173720a654a304e3cae224d8416/pkg/build/builder/docker.go#L143-L144) isn't checking `err` (Bad @bparees :-P)
Causes a panic if the repo has no `Dockerfile` in it.

**Comment by phemmer** [comment]
I can easily create a quick fix PR if desired. But if a test is needed, it won't be til tomorrow.

**Comment by bparees** [comment]
https://github.com/openshift/origin/pull/860

**Comment by bparees** [comment]
Thanks for the keen eye.

**Comment by ironcladlou** [comment]
This should be closed by #860.
