### ISSUE TITLE
null refernce in case docker manifest does not contain "signatures" section

### ISSUE THREAD

**Issue by smil2k** [openshift/origin#8593]
I've tried to import-image an imagestream which is connected to a nexus3 docker repo.

##### Version
oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. oc image-import 
2. exception comes

##### Current Result

[stacktrace on the server](https://github.com/openshift/origin/files/230844/stacktrace.txt)
[manifest file](https://github.com/openshift/origin/files/230847/latest.json.txt)

##### Expected Result

I think the error "missing singer key" might be ok as a problem where we bail out, but a null deference stacktrace should be fixed. I did not yet understood why the signatures part was not added in the repo.

**Comment by smarterclayton** [comment]
@miminar @legionus

**Comment by miminar** [comment]
Fixed by #8599.
