### ISSUE TITLE
No easy way to create or build json templates 

### ISSUE THREAD

**Issue by alberttwong** [openshift/origin#8595]
So I am building an aspnet template for OpenShift.   How I went about it was create a working project and then export those settings out to create a template that others can use.   This didn't work out that well.  
##### Version

OSE 3.1
##### Steps To Reproduce
1. [step 1]
2. [step 2]
##### Additional Information

 I think I have everything right but it won't show up in the web console.  Tried to login with several different users.

[openshift@ip-172-18-0-127 ~]$ oc create -n openshift -f https://raw.githubusercontent.com/alberttwong/s2i-aspnet/json/aspnet-app.json
imagestream "aspnet-app" created
buildconfig "aspnet-app" created
deploymentconfig "aspnet-app" created
service "aspnet-app" created

I don't know why.. it's in the correct namespace.   Login as "admin".  Maybe I need more odm permissions?

---

I created the json file through "oc new-app s2i-aspnet~https://github.com/openshift-s2i/s2i-aspnet --context-dir=source --name=aspnet-app -o json > aspnet-app.json"

I think I'm supposed to use "oc export all --as-template=image-stream.json -o json > image-stream.json".  I"ll try to load this json to see what happens. 

---

didn't work on either json.  Seems like I might have to manually create it.

**Comment by alberttwong** [comment]
https://docs.openshift.com/enterprise/3.0/dev_guide/templates.html#export-as-template says it'll work but it doesn't.

**Comment by bparees** [comment]
what do you mean by it doesn't work?

I ran your command to create some objects (note that i did not specify the openshift namespace though, i created them in my user's personal project):
```
$ oc create -n openshift -f https://raw.githubusercontent.com/alberttwong/s2i-aspnet/json/aspnet-app.json
```

and then i exported it as a template via:
```
$ oc export all --as-template=foo.json -o json > mytemplate.json"
```

and mytemplate.json contains a valid openshift template in json format.

near as i can tell the only broken aspect is that "--as-template" claims that you specify it with a filename and it will write to that file, but it appears to ignore the filename argument and instead simply outputs to stdout.  <--- @smarterclayton any idea if that was an intentional change or something got broken?

**Comment by smarterclayton** [comment]
--as-template takes the name of the template to generate - it should not be
generating to a file.  That's why we have redirection and pipes.  Maybe bad
docs.

**Comment by alberttwong** [comment]
PR for the oc export command.   https://github.com/openshift/openshift-docs/pull/1939

**Comment by alberttwong** [comment]
@bparees 

>>what do you mean by it doesn't work?

What I mean is the user story - As an OSE admin, I want to build and deploy a (aspnet) s2i image and make it available to all users in the OSE web console.  My assumption was that if I build the image and it deploys to my project, I should be easily be able to export the known, working config and then just put it in the -n openshift namespace and the s2i should be available to all users via the web console.   It doesn't seem that way.  the export seems to be very project specific and not reusable at all (i imported int various ways and it doesn't show up for all users).   This conflicts with the the title of the section "export as template" (https://docs.openshift.com/enterprise/3.0/dev_guide/templates.html#export-as-template) or at least what I think it means.

**Comment by bparees** [comment]
once you've got the template file (by running oc export --as-template), you can run:

oc create -f mytemplate.json -n openshift

that will make the template available to anyone who can view the openshift namespace (which should be all users, normally).  Did you do that and users could not see/access the template?

**Comment by alberttwong** [comment]
yes.  didnt work

**Comment by bparees** [comment]
can you be more explicit?  What didn't work?  did the oc create command return an error?  If so what error?

if it didn't return an error, can any user (admin?) see the template?  what does "oc get templates -n openshift" show when run as cluster admin?

Here is what happens when i run your scenario:

switch to a clean project
```
$ oc new-project p4
Now using project "p4" on server "https://10.192.214.122:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    $ oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-hello-world.git

to build a new hello-world application in Ruby.
```

create objects in my p4 project
```
sample-app (cicd)$ oc create -f https://raw.githubusercontent.com/alberttwong/s2i-aspnet/json/aspnet-app.json
imagestream "aspnet-app" created
buildconfig "aspnet-app" created
deploymentconfig "aspnet-app" created
service "aspnet-app" created
```

export the objects as a template
```
sample-app (cicd)$ oc export all --as-template=foo -o json > mytemplate.json
```

install the template in the openshift namespace
```
sample-app (cicd)$ oc create -f mytemplate.json -n openshift
template "foo" created
```

verify the template exists in the openshift namespace
```
sample-app (cicd)$ oc get templates -n openshift
NAME                       DESCRIPTION                                                                        PARAMETERS     OBJECTS
foo                                                                                                      0 (all set)    4
```

login as a non-cluster admin user
```
$ oc login
Authentication required for https://10.192.214.122:8443 (openshift)
Username: user1
Password: 
Login successful.

You don't have any projects. You can try to create a new project, by running

    $ oc new-project <projectname>
```

confirm the non-cluster admin user can see the new template:
```
sample-app (cicd)$ oc get templates -n openshift
NAME                       DESCRIPTION                                                                        PARAMETERS     OBJECTS
foo                                                                                                      0 (all set)    4
```

**Comment by bparees** [comment]
closing due to lack of information about what is not working.
