### ISSUE TITLE
Unexpected builds when pushing on Git repo

### ISSUE THREAD

**Issue by Cicatrice** [openshift/origin#8600]
I configured OpenShift to automatically build a service when a push request is send to a git repo using webhooks provided. But when I push on a branch, all the build processes run, even if there is no modification pushed on their branch.

##### Version
openshift v1.1.6-48-g561e4fa
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

##### Steps To Reproduce
1. Add the builds in the attached zip file
[openshift-build-yaml.zip](https://github.com/openshift/origin/files/231735/openshift-build-yaml.zip). Each build is linked to one branch.
2. Push a modification on the target git repo (`dev` or `prod`)
i.e. if I push only on `prod` branch.

##### Current Result
Both build processes run, even when there is no modification pushed on the related branch.

##### Expected Result
Only `prod` build should be running.

**Comment by soltysh** [comment]
The [1st comment](http://stackoverflow.com/a/36793088/606583) is also relevant to the bug, since the user tried `refs/heads/dev`:

Thanks for your comment. I tried using format ref/heads/dev, but I get the following error in log Error: build error: error: pathspec 'refs/heads/dev' did not match any file(s) known to git.. By the way, build has run also on prod and master env. I will try to open a bugrequest on GitHub

**Comment by Cicatrice** [comment]
@soltysh thanks, I actually wrote this comment few minutes ago :)

**Comment by bparees** [comment]
pretty sure we have logic in place that's supposed to check if the commit in question was for the branch the buildconfig is referencing.  will have to see if it's gotten broken or this is a scenario it doesn't cover.

**Comment by bparees** [comment]
we trim "refs/head" from the github event:
https://github.com/openshift/origin/blob/master/pkg/build/webhook/webhook.go#L16-L24

so using "dev" as your ref in your buildconfig is correct.

so we need to actually see what ref the github event had in it to understand why we're matching when we should not.

**Comment by Cicatrice** [comment]
Actually, I am using generic webhook, with [gogs](https://github.com/gogits/gogs), and the json webhook payload looks like : 
```json
{
  "secret": "",
  "ref": "refs/heads/dev",
  "before": "0000000000000000000000000000000000000000",
  "after": "bd8c55af53b848f188de99c674fa01969ea918ba",
  "compare_url": "http://git-labs.apps.10.2.2.2.xip.io/",
  "commits": "[...]"
}
```

As seen, ref is refering about `dev`.

**Comment by bparees** [comment]
the generic webhook won't parse the git information in that format.

I believe the gogs payload matches the github payload, so you just need to add a github trigger to your BC and setup gogs to hit that webhook instead of generic.

**Comment by Cicatrice** [comment]
I updated the webhooks on GOGS, and indeed, it will trigger only the related branch.

Many thanks for your help.

**Comment by bparees** [comment]
excellent!
