### ISSUE TITLE
oc volume should support configmaps

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#8616]
We have oc create configmap but no support for actually adding a configMap as a volume.

##### Version
v1.2-rc1

##### Steps To Reproduce
1. oc volume -h

##### Current Result
  -t, --type='': Type of the volume source for add operation. Supported options: emptyDir, hostPath, secret, persistentVolumeClaim

##### Expected Result
  -t, --type='': Type of the volume source for add operation. Supported options: emptyDir, hostPath, secret, configMap, persistentVolumeClaim

**Comment by tomdearman** [comment]
Can you tell me if this would also affect using configMap:... in a volumes: of a DeploymentConfig as I cant get this to work.  Says it is an emptyDir

**Comment by pmorie** [comment]
@tomdearman i would need to see your deployment descriptor, but the lack of this feature re: `oc volume` should not affect whether you can use configmaps in a deployment.

**Comment by tomdearman** [comment]
Thanks for the reply.  I have just tried the redis example and get the same.  I am running the vagrant steve0 setup.  I have run the following:

oc create configmap example-redis-config --from-file=redis.conf

oc create -f redis-pod.yaml


Regis does not start up and when I get the logs it has the following:

Toms-iMac:originopenshift tomdearman$ oc logs redis
[9] 04 May 16:35:19.190 # Fatal error, can't open config file '/redis-master/redis.conf'

**Comment by pmorie** [comment]
Can I see your redis-pod.yaml @tomdearman

**Comment by tomdearman** [comment]
Was it not attached, should have been. Will resend when I am in front of a
computer.

**Comment by tomdearman** [comment]
@pmorie here is the file, not sure if it comes through via email attachment.  thanks.
[redis-pod.txt](https://github.com/openshift/origin/files/249563/redis-pod.txt)

**Comment by sosiouxme** [comment]
addressed by https://github.com/openshift/origin/pull/8720
