### ISSUE TITLE
Simplify example with 'start-build'

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#862]
Example does 

> Trigger an initial build of your application

> If you setup the GitHub webhook, push a change to app.rb in your ruby sample repository from step 10.
Otherwise you can simulate the webhook invocation by running:

> $ curl -X POST https://localhost:8443/osapi/v1beta1/buildConfigHooks/ruby-sample-build/secret101/generic?namespace=test

We can simplify that with `osc start-build ruby-sample-build`

**Comment by bparees** [comment]
fixing in https://github.com/openshift/origin/pull/873

**Comment by bparees** [comment]
fixed.
