### ISSUE TITLE
enable third party resources

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#8622]
@liggitt wants API changes first to make them non-namespaced and we probably need a full cached discovery client to avoid tons of round trips.

**Comment by deads2k** [comment]
@smarterclayton do you want this before 1.3?

**Comment by smarterclayton** [comment]
I think 1.3 will probably promote them to stable.

**Comment by liggitt** [comment]
We'll want these before enabling:
https://github.com/kubernetes/kubernetes/pull/25006
https://github.com/kubernetes/kubernetes/pull/25007

**Comment by liggitt** [comment]
still not stable or functionally complete in 1.3, moving out of milestone

**Comment by ibotty** [comment]
Is this going to be in 1.4? Many kube-addons already use it and thus can't be used by openshift.

**Comment by liggitt** [comment]
No, it is still not stable or functionally complete. There are upstream issues tracking remaining work, but progress has slowed.

**Comment by deads2k** [comment]
> Is this going to be in 1.4? Many kube-addons already use it and thus can't be used by openshift.

See https://github.com/kubernetes/features/issues/95 for a list of known failures.  Many are quite severe.

**Comment by jimmidyson** [comment]
While I understand & agree with the reasons for not making TPRs a default enabled, supported resource, it would be great to be able to enable it if a user decides they want to accept the potential drawbacks & risks. Is it just auth that prevents TPRs being used with OpenShift right now? `cluster-admins` can manage TPRs & their data right now I think?

**Comment by ibotty** [comment]
At least on Origin 1.3, third party resources definitions can be added, but no third party resource can be added.

**Comment by jimmidyson** [comment]
@ibotty Not sure - was trying to with 1.41.5 & seems to work OK (albeit as cluster-admin) though.

**Comment by liggitt** [comment]
They are not intended to be enabled in OpenShift yet. The upstream issues are severe enough that we can't support using them. Resolving those issues is likely to require storage and API server changes that will prevent migration of existing data.

**Comment by kargakis** [comment]
We have CRDs now so I guess this is done.
