### ISSUE TITLE
ELB service loadbalancer controller is not enabled in Origin

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8626]
Prevents services of type LoadBalancer from being used.

**Comment by smarterclayton** [comment]
@ncdc since I know you had discussions about it.

**Comment by ncdc** [comment]
@smarterclayton yeah, it hasn't been enabled in Origin yet

**Comment by anthonyrisinger** [comment]
The use case driving this is supporting wildcard DNS. Is there a better way now, or better path forward to achieve this end?

**Comment by smarterclayton** [comment]
This will be enabled in 1.3.0-alpha.1.

This is likely the easiest way to accomplish wildcard DNS - is this "on demand", or you only need one of them?

**Comment by anthonyrisinger** [comment]
In this case only one particular app needed it, so IIUC, a NodePort-based app + manually creating an ELB is sufficient. There are however a few apps in the pipeline that will also want this feature.

It's not the end of the world if we have to involve the Operations team for such things for now, but it would be nice if developers could make use of it on their own, as necessary.

Even better would be direct support of wildcards by the router! :-) We had one developer attempt to implement a custom router handing this, which I believe worked, but OpenShift would not accept the `*` character as a valid route.

**Comment by smarterclayton** [comment]
That's a very reasonable request - we just haven't had anyone ask it
before.  We'd have to guard against overlap somehow (shouldn't let you
claim a name below someone else's name)
