### ISSUE TITLE
Web console API discovery can be slow

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8638]
1.3 only. Sometimes API discovery can take 5 seconds, which makes the console feel slow. While waiting, all you see is a blank page.

This could be environmental, but I've seen it often enough that I think we should investigate.

<img width="609" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/14834970/47e885d6-0bd5-11e6-9100-2f9ac54fe5ea.png">

/cc @jwforres @liggitt

**Comment by jwforres** [comment]
Hmm that is concerning, the API shouldn't take that long to respond.  I
haven't noticed that in my env but my api server is a couple weeks old, how
recent is yours?

**Comment by spadgett** [comment]
Running the jenkins pipeline branch, so I'm not sure :/

It could be my environment if no one else sees it.

**Comment by jwforres** [comment]
@spadgett have you noticed this recently?

**Comment by spadgett** [comment]
Occasionally. I think we should add a "Loading..." message just in case because the page is totally blank if discovery is slow.
