### ISSUE TITLE
Misleading oc projects command

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#8645]
When executing `$ oc projects` (common mistake/command I can see on workshops), you will get:

```
Using project "blabla" on server "https://alpha.mifo.sk:8443".
```

I think we should either list the projects (because the "projects" is plural and I expect to see my projects) or print the usage with suggestion to run `$ oc get projects` instead.

**Comment by mfojtik** [comment]
@fabianofranz @kargakis FYI

**Comment by kargakis** [comment]
cc: @deads2k @liggitt

**Comment by deads2k** [comment]
I don't think `oc project` and `oc projects` should be different, so I'd keep them as the same command.

For small numbers of projects, that's very useful.  For large numbers of projects in a kubeconfig file, it can be difficult to display, but there is a spot to note utilization (`runtime.Object`) if we really wanted to.  For large numbers of projects server-side you're in a pickle.  That could be a very long list for a cluster-admin.

**Comment by mfojtik** [comment]
@deads2k does `oc projects` returning the currently set project sounds good to you? to me the plural indicate I want list of my projects... Also I saw users on workshops doing the same mistake... 

For a long list, the `oc project` will always give you the current project and for `projects` can we trim the list and suggest user to use `oc get projects`? (or my other suggestion, on `oc projects` suggest to run `oc get projects`.

**Comment by jorgemoralespou** [comment]
Whatever implementation end up here, oc projects should show from the list which one you're using currently.
