### ISSUE TITLE
RSA verification error against host kubernetes

### ISSUE THREAD

**Issue by paralin** [openshift/origin#8646]
Running under Kubernetes.

This is happening again any idea where I should begin in terms of fixing this? Diagnostics shows no errors.

**Comment by paralin** [comment]
It's basically this: https://github.com/asiainfoLDP/datafoundry-troubleshooting/issues/21

```
I0427 12:36:22.548081       1 factory.go:470] Failed to find any pods due to error the server has asked for the client to provide credentials (get pods)
I0427 12:36:22.656029       1 jwt.go:147] Signature error (key 0): crypto/rsa: verification error
I0427 12:36:23.548523       1 jwt.go:147] Signature error (key 0): crypto/rsa: verification error
I0427 12:36:23.548767       1 jwt.go:147] Signature error (key 0): crypto/rsa: verification error
```

If, from within the openshift pod, I attempt to use the external-master.kubeconfig using kubectl it works fine for every operation I can think of. Any ideas?

**Comment by liggitt** [comment]
looks like a mismatch in service account tokens between openshift and kube. are you configuring openshift to let kube handle creating the tokens (serviceAccountConfig.privateKeyFile should be empty) and giving openshift the correct public key to verify the tokens (serviceAccountConfig.publicKeyFiles should contain the key from kube)? if you ever had those misconfigured, you could also have invalid service account tokens in etcd. right now, those have to be removed manually (and are re-generated automatically)

**Comment by paralin** [comment]
@liggitt I cleared the /srv/kubernetes dir on the kube master, restarted it, grabbed the server.key from there, rebuilt the entire openshift deploy, unset the flag on default for service account setup=true, deleted all the service accounts so they would be re-created, and I'm still getting the error.

The annoying thing is that it seems to be able to interface with the kube master just fine:

```
I0427 16:59:29.486189       1 factory.go:584] No build pod found for build dev-1/activities-5, sending delete event for build pod
I0427 16:59:29.486437       1 controller.go:304] Handling deletion of build pod dev-1/activities-5-build
I0427 16:59:30.217979       1 jwt.go:147] Signature error (key 0): crypto/rsa: verification error
I0427 16:59:30.222102       1 jwt.go:147] Signature error (key 0): crypto/rsa: verification error
I0427 16:59:30.264874       1 factory.go:470] Failed to find any pods due to error the server has asked for the client to provide credentials (get pods)
```

Any ideas?

**Comment by paralin** [comment]
You mentioned removing service account tokens, how do I do that? Do you mean from OpenShift or Kube etcd?

**Comment by liggitt** [comment]
> I cleared the /srv/kubernetes dir on the kube master, restarted it, grabbed the server.key from there

Does that mean you restarted kubernetes against an existing etcd with a newly generated service account key? If so, that's the issue.

> You mentioned removing service account tokens, how do I do that? Do you mean from OpenShift or Kube etcd?

They're kube objects, so they should be in kube etcd. Remove the service account tokens by deleting the secrets containing them (`kubectl delete secret <name>`)

**Comment by paralin** [comment]
@liggitt Yeah, I basically manually combed through our cluster setup to change the pod CIDR on AWS since it was colliding with some other things we need to access. It was NOT a fun process. Anyway I will try deleting all of those secrets now.

**Comment by paralin** [comment]
@liggitt I deleted all the secrets in the openshift namespace and most of the others, but I'm still getting the same error. Any other ideas? Should I restart the kube api server?

**Comment by paralin** [comment]
Okay, I fixed it with this:

```
#!/bin/bash

for each in $(kubectl get ns -o jsonpath="{.items[*].metadata.name}");
do
  kubectl --namespace=$each delete serviceaccount builder default deployer
  kubectl --namespace=$each get secret | grep kubernetes.io | awk '{print $1}' | xargs kubectl --namespace=$each delete secret
done
```

Thanks!
