### ISSUE TITLE
extended test flake on namespace set up

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#8651]
Synopsis located here: https://ci.openshift.redhat.com/jenkins/failure-cause-management/5720d0c7e4b034b3320088d1/

First seen as part of merging this PR:  https://github.com/openshift/origin/pull/8219

with this test run:  https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/472/console

**Comment by danmcp** [comment]
Closing since no one has reported this in a long time.
