### ISSUE TITLE
Applications+projects are not able to build if project is very new

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#8660]
Apps that are created in projects that are very newly created (30~ seconds) do not get the service account added? If the user waits 1+ minute this issue does not happen.

Error message:
Failed to create build pod: pods "asd-1-build" is forbidden: no API token found for service account test/builder, retry after the token is automatically created and added to the service account.

##### Version
1.2.0-rc2

##### Steps To Reproduce
1. Create new project
2. Create a new application within 30~ seconds

##### Current Result
The application is not able to build and will eventually fail. It doesn't retry.

##### Expected Result
The application should build successfully.

**Comment by liggitt** [comment]
How many projects exist in total? Is there quota set up on serviceaccounts or secrets on new projects by default? What sort of CPU load is the master API server under?

**Comment by andrewklau** [comment]
No previously projects exist for this test, there is a quota set in the default project template. The CPU load on the master is very low.

**Comment by liggitt** [comment]
Are service accounts or secrets quotaed?

**Comment by andrewklau** [comment]
spec:
    hard:
      [...]
      services: 10
      secrets: 20

**Comment by liggitt** [comment]
Secret quota is the issue. https://bugzilla.redhat.com/show_bug.cgi?id=1324179 Is open to track the issue. The fix is for the token controller to retry token creation more quickly on failures. That work is in progress in https://github.com/openshift/origin/pull/8355

**Comment by andrewklau** [comment]
Awesome
