### ISSUE TITLE
Changing the ClusterIP of the docker-registry service

### ISSUE THREAD

**Issue by paralin** [openshift/origin#8661]
I've changed the cluster IP for the docker-registry service, and all my ImageStreams seem to have updated properly. But the DeploymentConfigs are still set to the old IP address, and when I trigger a new deploy, it doesn't use the new cluster IP address.

Is there some way to fix this other than restarting all the builds? I've also tried editing the deployment configs but the image IP address doesn't seem to update properly.

**Comment by liggitt** [comment]
Changing the IP currently requires a master restart (https://github.com/openshift/origin/issues/1723 was opened for it, but closed as wontfix). Things that reference the IP explicitly would need redeploying (issue to move to DNS based references: https://github.com/openshift/origin/issues/6924 and https://github.com/openshift/origin/issues/8581, among others)

**Comment by paralin** [comment]
@liggitt Fixed it by re-triggering all the builds as per the issues you linked. It could be useful to have an oadm command to reconcile the registry IP address, and also to use DNS for the registry (but this is something already in progress of course).
