### ISSUE TITLE
Why is there no oc get env?

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#8665]
There is an oc set env but there is no oc get env

All I want is to get the env variables set on an object like the DC - not have to read through a big long JSON or YAML file. Please fix ASAP. I know there is an oc set env --list but that is non intuitive and wrong.

Thanks!

**Comment by kargakis** [comment]
cc: @fabianofranz @smarterclayton

**Comment by liggitt** [comment]
`get` is the generic command that works against resource types... it's not available for this use

`oc env --list` works, but is marked deprecrated. I agree, putting read-only and remove actions under `set` is weird.

**Comment by thesteve0** [comment]
Well then get rid of set also or at least change it to something like
set-env. By using set, I the developer, assume I can use set, get, delete
syntax.

**Comment by smarterclayton** [comment]
We needed a generic verb to gather related nouns under.  The kind of
"set" you are describing is "update" or "apply".  The other purpose of
set is to bring things together that are discoverable (there are far
too many things to set).

get has defined semantics already that we cannot change - I think
supporting get env might be possible in the future, but not there
today.

**Comment by thesteve0** [comment]
But the command is already _oc get env_, which is why I am confused. I am
saying to drop the get since it is used incorrectly here because env is not
an OpenShift or Kube resource.

**Comment by kargakis** [comment]
@fabianofranz how about having all `--list` flags into an `oc list` or `oc show` command (`oc list env`, `oc list labels`, `oc list annotations`) and `--remove` flags into an `oc unset` command?

**Comment by kargakis** [comment]
And add deprecation warnings for `oc set env --list`, `oc set volume --list`, and `oc set volume --remove`

**Comment by smarterclayton** [comment]
I would not be in favor of making a generic list command yet - that's a
much bigger decision and has lots of design implications.

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/29679
