### ISSUE TITLE
Docker integration tests failing

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#867]
```
Server message: accept tcp [::]:8443: use of closed network connection--- FAIL: TestRouter (25.51 seconds)
	router_test.go:162: TC non-secure failed! Response body <html><bod did not match expected Hello Pod!
	router_test.go:162: TC edge termination failed! Response body <html><bod did not match expected Hello Pod!
	router_test.go:162: TC passthrough termination failed! Response body <html><body><h1>5 did not match expected Hello Pod Secure!
```

**Comment by smarterclayton** [comment]
I don't think these ever got added to vagrant (we should be calling make test, but aren't yet).

**Comment by pweil-** [comment]
@smarterclayton - where/how. was this seen?  A quick local test on master shows that they're running fine in my local env.  The server message prior to the failures seems to indicate the test http server was stopped and the router was returning a 503, so finding the cause of that seems to be what I need to look at.

```
[vagrant@openshiftdev origin]$ hack/test-integration-docker.sh 
etcd: {"action":"get","node":{"key":"/","dir":true}}

Docker integration test cases ...

ok  	github.com/openshift/origin/test/integration	24.093s

Complete
```

**Comment by pweil-** [comment]
never mind, think I found it.

**Comment by pweil-** [comment]
actually, if the router was returning a 503 then it wasn't the pull item.  I can't reproduce this.  PR to do a pull if not present (so it works on a fresh vagrant up) and a PR to convert the vagrant plugin to use make are in.

**Comment by pweil-** [comment]
@smarterclayton I think this can be closed or remarked beta2 since they script seems to run fine and we're waiting on beta2 for the plugin/makefile merge

**Comment by smarterclayton** [comment]
Closing as it can't be reproduced anymore.
