### ISSUE TITLE
oc new-build/new-app show imagestream already exists when create a build/app using same builder image but different tag

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#8680]
[provide a description of the issue]
I want to use oc new-build create two bc , first one using the builder image tag latest , second using same image different tag like <image>:tag2,  the new-build/new-app command will failed the second time.
##### Version

[provide output of the `openshift version` or `oc version` command]
openshift v1.3.0-alpha.0-97-g12c24f1
kubernetes v1.3.0-alpha.1-331-g0522e63
etcd 2.3.0
##### Steps To Reproduce
1. [step 1]
   oc new-build uptoknow/ruby-20-centos:latest~https://github.com/openshift/ruby-hello-world
2. [step 2]
   oc new-build uptoknow/ruby-20-centos:user1001~https://github.com/openshift/ruby-hello-world --name=rubyuser1001
   ##### Current Result
   --> Creating resources with label app=rubyuser1001 ...
   error: imagestreams "ruby-20-centos7" already exists
##### Expected Result

ruby-20-centos7 imagestream is really exits after step 1, but after step2 , we should update the ruby-20-centos7 imagestream to import the new tag instead of the "already exists" error.
##### Additional Information

[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by jupierce** [comment]
new-build (and new-app) generally do not modify existing resources -- instead reporting an error. To accomplish the use case you describe, @csrwng suggested using new-build to generate json (or yaml) output and piping it to oc apply to merge the desired changes.

For example:
```
oc new-build docker.io/jupierce/nodejs-010-centos7~https://github.com/openshift/nodejs-ex.git

oc new-build -o yaml docker.io/jupierce/nodejs-010-centos7:notlatest~https://github.com/openshift/nodejs-ex.git --name=notlatest | oc apply -f -
```

Any more thoughts @bparees ?

**Comment by bparees** [comment]
nope, thanks @jupierce

**Comment by dgoo2308** [comment]
@jupierce following the above instruction, e.g. :

    oc new-build --to="is-oc-runner:latest" --strategy=docker --binary=true --name="bc-oc-runner" -o yaml | oc apply -f -

I get a warning:

    Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
    imagestream "is-oc-runner" configured
    Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
    buildconfig "bc-oc-runner" configured


I understand that `kubectl` is reported in the warning is solved, but how to get rid of the warning?

**Comment by jupierce** [comment]
@dgoo2308 I believe if you create your initial resources with `.... | oc create --save-config  -f - `, you will not see this error.
