### ISSUE TITLE
Remove shared dependency from deployment trigger controllers

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8696]
The image change and config change controllers are using the same generator to update deploymentconfigs. This has lead in problems like races and holes in our registry. We should remove the generator and push related bits to the related controllers.

cc: @ironcladlou @liggitt

**Comment by kargakis** [comment]
Actually the image change controller would still need to update both the spec and status of a dc. I really cannot see how can we avoid the hole in the registry once we split the calls to spec and status. Either that or we could have the image change controller update the spec and status separately.:/

**Comment by liggitt** [comment]
I would expect the image change controller to just update the spec (change images, record desire to have another deployment) and the config change controller would act on that, trigger the deployment, and update status

**Comment by kargakis** [comment]
If we implement pausing right then we may not need the config change controller anymore. I would expect only one client of deploymentconfig/status - the main dc controller
