### ISSUE TITLE
Unable to use Kubernetes API in OpenShift

### ISSUE THREAD

**Issue by DarkSkull91** [openshift/origin#8698]
I'm trying to use Kubernetes API when I start OpenShift but I can't, I used the latest version of OpenShift Origin.
I wrote this simple program in Go:

```
package main

import (
  "fmt"
  client "k8s.io/kubernetes/pkg/client/unversioned"
  rest "k8s.io/kubernetes/pkg/client/restclient"
  "k8s.io/kubernetes/pkg/api"
)


func main() {
	config := &rest.Config{
	  Host:     "https://localhost:8443",
	  Username: "admin",
	  Password: "password",
	  Insecure: true,
	}
	client, err := client.New(config)
	if err != nil {
	  // handle error
	  fmt.Println(err)
	}
	namespaces, err := client.Namespaces().List(api.ListOptions{})
	if err != nil {		
		// handle error
		fmt.Println("Error: ", err)
	} else {
		fmt.Println(namespaces)
	}
}
```
But when I run this code, I got this error:

`Error:  User "system:anonymous" cannot list all namespaces in the cluster`

I'm sure that OpenShift is well-configured because if I type:
`oc get nodes`
shell shows me:
```
NAME                        STATUS     AGE
openshift-minion1-centos7   Ready      6d
openshift-minion2-centos7   Ready      8d
openshift-minion3-centos7   NotReady   5d
openshift-minion4-centos7   NotReady   5d
openshift-minion5-centos7   NotReady   5d

```
Did I miss some configuration?

**Comment by liggitt** [comment]
Openshift does not support basic auth against the API. You need to obtain a bearer token from the OAuth endpoint (see the output of `oc login -u admin -p password` to see the network calls to accomplish that) or specify a client certificate/key (like the admin client cert/key generated at startup).

**Comment by DarkSkull91** [comment]
With the bearer code, I got this error:
`Error:  User "admin" cannot list all namespaces in the cluster`

**Comment by liggitt** [comment]
Great, you're through the authentication layer :)

If you want the "admin" user to have permissions, you need to grant them from a user that has those permissions. Typically that's the cluster admin "system:admin" user.

Try this:

```
oc whoami
oc policy add-cluster-role-to-user cluster-admin admin
```

**Comment by DarkSkull91** [comment]
Thank you very much @liggitt :+1: but the right command that I use is 
`oadm policy add-cluster-role-to-user cluster-admin admin`
because with your command I got:
`error: unknown command "add-cluster-role-to-user cluster-admin admin"`
Anyway, thank you again you give me a valid hint :)
