### ISSUE TITLE
Service external IP and Router 

### ISSUE THREAD

**Issue by catherinesword** [openshift/origin#8700]
[provide a description of the issue]
Earlier in February I tried to assign externalIP to service and it worked, recently when I tried again I noticed that it was disabled already. So I'm wondering if still possible for a service to have an external IP or it is forbidden..

Also I noticed that with my new OpenShift instance on AWS, the router is by default installed. I've tried to use it, but somehow I got confused.. After deployed a service (with port 80 open, say, a jetty service), looks like this:
```
[centos@ip-172-xx-x-x example]$ oc get service
NAME            CLUSTER-IP     EXTERNAL-IP   PORT(S)                   AGE
jetty-service   172.30.1.132   <none>        80/TCP                                1m
kubernetes      172.30.1.1     <none>        443/TCP,53/UDP,53/TCP     1h
router          172.30.1.204     <none>        80/TCP,443/TCP,1936/TCP   45m
```
I exposed it by 
```
oc expose service jetty-service -l name=jetty-service
```
Then I can see the route
```
NAME            HOST/PORT                                                PATH      SERVICE               TERMINATION   LABELS
jetty-service   jetty-service-default.router.default.svc.cluster.local             jetty-service:jetty                 name=jetty-service
```
I wonder if the HOST ```jetty-service-default.router.default.svc.cluster.local``` is correct, because I expected something more "external".. 
If yes, does it work for external access? If not, how to configure it to expose the service properly? 

Thank you!

##### Version
[provide output of the `openshift version` or `oc version` command]
openshift version
```
openshift v1.2.0-rc1
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5
```

##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]
oadm diagnostics shows 2 warnings:
```
Info:  Checking journalctl logs for 'origin-master' service
Info:  Checking journalctl logs for 'origin-node' service

WARN:  [DS2005 from diagnostic AnalyzeLogs@openshift/origin/pkg/diagnostics/systemd/analyze_logs.go:120]
       Found 'origin-node' journald log message:
         W0501 22:37:16.894912    2081 subnets.go:110] Could not find an allocated subnet for node: ip-172-30-3-212.ec2.internal, Waiting...
       
       This warning occurs when the node is trying to request the
       SDN subnet it should be configured with according to the master,
       but either can't connect to it or has not yet been assigned a subnet.
       
       This can occur before the master becomes fully available and defines a
       record for the node to use; the node will wait until that occurs,
       so the presence of this message in the node log isn't necessarily a
       problem as long as the SDN is actually working, but this message may
       help indicate the problem if it is not working.
       
       If the master is available and this log message persists, then it may
       be a sign of a different misconfiguration. Check the master's URL in
       the node kubeconfig.
        * Is the protocol http? It should be https.
        * Can you reach the address and port from the node using curl -k?
```
```
Info:  Found a master config file: /etc/origin/master/master-config.yaml

WARN:  [DH0005 from diagnostic MasterConfigCheck@openshift/origin/pkg/diagnostics/host/check_master_config.go:58]
       Validation of master config file '/etc/origin/master/master-config.yaml' warned:
       assetConfig.loggingPublicURL: Invalid value: "": required to view aggregated container logs in the console
       assetConfig.metricsPublicURL: Invalid value: "": required to view cluster metrics in the console
```

**Comment by catherinesword** [comment]
..now it seems I solved the problem: I created route manually, and corrected the host name, also used path, and it works..
So I close the issue.

**Comment by catherinesword** [comment]
Just I'm still not sure about the external IP issue.. Could any one give me some hints? Thanks!

**Comment by catherinesword** [comment]
Another issue with route: 
When I tried the "hello openshift" pod-service-route, I used path ```"path": "/hello"``` and it worked fine. However if I do the same for the jetty service ```"path": "/jetty"``` then 404 not found, only if I use the public DNS of the AWS instance as the host name it works, on port 80. 
What is the difference of these two cases? I wonder if I missed something..

Also if I want to deploy multiple (same) jetty services, is using path the only way to isolate them? 

Your help is highly appreciated.

**Comment by knobunc** [comment]
I'm confused by where you are stuck at the moment.  Can you give the URL you are trying to hit, and the output from oc get routes.

You need to set DNS up outside the cluster so that it resolves the hostnames for all of your routes to the cluster.  If you give a subdomain to the cluster, and point DNS for that subdomain at the cluster DNS, then it will be able to resolve the names just by creating them as routes.  This blog post is helpful:
 http://developers.redhat.com/blog/2015/11/19/dns-your-openshift-v3-cluster/

You may also need to change your configuration so the right wildcard domain is used.  Your first post had the hostname as:
  jetty-service-default.router.default.svc.cluster.local

Which is the default of service-name '-' project-name and then the default subdomain of ".default.svc.cluster.local".

**Comment by catherinesword** [comment]
@knobunc  Thank you for your reply! Here's the output from oc get routes
```
NAME                    HOST/PORT                                 PATH      SERVICE                   TERMINATION   LABELS
hello-openshift-route   ec2-52-3-246-99.compute-1.amazonaws.com   /hello    hello-openshift-service                 
jetty-route             ec2-52-3-246-99.compute-1.amazonaws.com             jetty-service   
```
The hello-openshift-route works fine, I can access it with ```ec2-52-3-246-99.compute-1.amazonaws.com/hello```, but for the jetty-route, only works without path. 

I'll have a look at DNS setup and subdomain config, thanks!

**Comment by catherinesword** [comment]
@knobunc I've solved the problem with path, thank you for your help, this issue can be closed.

**Comment by knobunc** [comment]
Thanks @catherinesword

**Comment by yanusocial** [comment]
Sorry but I have the same issue.
`[root@ip-172-31-10-155 ~]# oc get pods --all-namespaces --selector=router --template='{{range .items}}HostIP: {{.status.hostIP}}   PodIP: {{.status.podIP}}{{end}}{{"\n"}}'
HostIP: 172.31.10.155   PodIP: 10.1.0.3  Host IP: 172.31.10.156   PodIP: 10.1.1.3`
But I can't the router takes external ip address for the ami.
I had deployed Origin with this environment variables:
openshift_public_hostname=ec2-52-xxx-xxx-140.eu-west-1.compute.amazonaws.com openshift_public_ip=52.xxx.xxx.140

Can you help me?

Thank you!

**Comment by dio** [comment]
@husseinharake did you fix your problem yet? I experienced the same with you.
