### ISSUE TITLE
Flake in TestSAAsOAuthClient

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8701]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/586/console

```
--- FAIL: TestEnforcingServiceAccount-2 (8.94s)
	service_account_test.go:381: unexpected error: Operation cannot be fulfilled on serviceaccounts "deployer": the object has been modified; please apply your changes to the latest version and try again
FAIL
```

**Comment by smarterclayton** [comment]
Just saw this again. https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/1650/consoleFull#-72071612056bf4006e4b05b79524e5923

**Comment by bparees** [comment]
similar flake here:
```
--- FAIL: TestSAAsOAuthClient (17.47s)
	sa_oauthclient_test.go:92: unexpected err: Operation cannot be fulfilled on serviceaccounts "default": the object has been modified; please apply your changes to the latest version and try again
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3325/console

**Comment by liggitt** [comment]
that actually looks like an error in retry logic

**Comment by bparees** [comment]
or an unanticipated race

**Comment by liggitt** [comment]
no, the retry is wrong... in conflict cases, the object gets overwritten and could never succeed on subsequent retries

**Comment by liggitt** [comment]
TestEnforcingServiceAccount flake was fixed in https://github.com/openshift/origin/pull/9250

**Comment by kargakis** [comment]
Once again: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3304/consoleFull
