### ISSUE TITLE
Feature request: Upgrade the internal registry to version 2.4.0 in order to get GC for registry layer blobs

### ISSUE THREAD

**Issue by mrosic** [openshift/origin#8705]
Hello,

I am very eager to see OpenShift switch to Docker Registry 2.4.0 because this release finally provides a garbage collection for registry layer blobs:
https://github.com/docker/distribution/releases/tag/v2.4.0

Due to historical reasons we have lots of unreferenced registry layer blobs and it would be a big relief to see those gone.

**Comment by pweil-** [comment]
R&D currently in progress with trello card https://trello.com/c/OYpmTIHl/644-8-r-d-support-for-docker-registry-2-4

**Comment by dmage** [comment]
Our current version is based on Distribution v2.6.2. Unreferenced layer blobs can be removed by [hard pruning](https://docs.openshift.org/latest/admin_guide/pruning_resources.html#hard-pruning-registry).
