### ISSUE TITLE
registry-admin role cannot delete projects

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#8714]
registry-admin role should be able to delete projects.

##### Version
oc v1.3.0-alpha.0-56-gd9c6483
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Steps To Reproduce
1. oc whoami -> bob
1. oc new-project test-project
1. oc policy add-role-to-user registry-admin bob
1. oc policy remove-role-from-user admin bob
1. oc delete project test-proj

##### Current Result
Error from server: User "bob" cannot delete projects in project "test-proj"

##### Expected Result
project "test-proj" deleted

**Comment by aweiteka** [comment]
PR introducing registry-admin role: https://github.com/openshift/origin/pull/6963

cc @sub-mod

**Comment by deads2k** [comment]
opened https://github.com/openshift/origin/pull/8716
