### ISSUE TITLE
recycler pods fails on NFS with undeletable .snapshot folders

### ISSUE THREAD

**Issue by tcastberg** [openshift/origin#8721]
We're seeing PVs being failing when they are released because they are served from a netapp with snapshot enabled. This means every single folder has a .snapshot folder in it. When you delete a folder in a pv there is no issue, but the .snapshot folder in the root of the pv with all its subdirectories and files is not possible to delete.
##### Version
# oc version

oc v1.1.1.1
kubernetes v1.1.0-origin-1107-g4c8e6f4
##### Steps To Reproduce

Create PV on netapp with .snapshot
Create claim for PV
Release claim
##### Current Result

oc describe pv XXX
Status:     Failed
Message:    Recycling error: Pod failed, pod.Status.Message unknown.
##### Expected Result

Possible one should be able to exclude files/directories from deletion?
##### Additional Information

Log from recycler pod:
# docker logs e886bb5fa08e

Scrub failed: /scrub/.snapshot/nfs_daily.2016-04-30_0015 (dgrwxrwxrwx), reading dir names as 0: open /scrub/.snapshot/nfs_daily.2016-04-30_0015: permission denied

**Comment by tcastberg** [comment]
This issue seems further compounded by receiving the same PV (even though it is marked as failed) when you create the same claim again.

**Comment by cpitman** [comment]
Would you really want to recycle a volume that has snapshots? Could this allow the next owner of the volume access to the previous pod's data?

**Comment by tcastberg** [comment]
Not really, however until we can get these hidden or turned of the PV's fail. I would imagine that there might also be other reasons why you would want to exclude certain files from removal regardless.
