### ISSUE TITLE
Race condition between pod deletion and service endpoint updating?

### ISSUE THREAD

**Issue by jwendell** [openshift/origin#8728]
Here's what I'm doing:
1) Deploy an app with 2 or more replicas
2) Make tons of HTTP requests to that app (via service's IP) and make sure somehow they are reaching the same pod (by setting service's SessionAffinity to ClientIP, for example), with a small interval between requests (1s, or 0.5s)
3) In another terminal, kill (oc delete) the pod which is serving the requests

- Depending on the interval between requests in step 2, we could see one request failing before subsequent requests get redirected to other free, alive pod.

I think that, for deletion, the service endpoint should be updated first. Then the pod should be marked for deletion and be killed.

It's also reproducible in Origin master as of today:
$ oc version
oc v1.3.0-alpha.0-269-g3ab985a
kubernetes v1.3.0-alpha.1-331-g0522e63

**Comment by ncdc** [comment]
That would be a huge undertaking to change this behavior. I'm not sure how feasible it is. cc @smarterclayton @knobunc @eparis

**Comment by smarterclayton** [comment]
Set a longer grace period in your pod and have a prestop that waits until you stop accepting traffic.  Applications really have to be involved with load balancers to avoid dropping connections.  When you go into terminating state as a pod you get removed from endpoints - if your pod controls that gap more effectively you can reduce the impact.

**Comment by ncdc** [comment]
@jwendell were you able to try out Clayton's suggestions?

**Comment by jwendell** [comment]
Not yet, let's close this for now.... Thanks anyway for your responses!
