### ISSUE TITLE
Exec readiness check failed with inappropriate ioctl

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8740]
Readiness check failed for mongodb, not sure if this is a mongodb issue or a Kube issue.

```
AAA-BBB   34m       16m       107       mongodb-4-iqlkz    Pod       spec.containers{mongodb}      Warning   Unhealthy   {kubelet ip-XXXX}   Readiness probe failed: sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
sh: mongostat: command not found
```

@ncdc this is exec, but it might be @bparees / @mfojtik something specific to the mongo readiness check.

**Comment by ncdc** [comment]
@smarterclayton does your pod deploy with tty=true for that container?

**Comment by ncdc** [comment]
And what does the probe look like?

**Comment by bparees** [comment]
@ncdc the readiness check should be this:
https://github.com/openshift/origin/blob/master/examples/db-templates/mongodb-ephemeral-template.json#L95-L100

**Comment by smarterclayton** [comment]
@sspeiche did you have this set as an exec task previously?

**Comment by ncdc** [comment]
@bparees why do you have the `-i` flag?

**Comment by bparees** [comment]
@ncdc needed to get our scl enable magic to work, i believe.  but @mfojtik wrote the probe.

**Comment by bparees** [comment]
@ncdc @smarterclayton i should note that whatever @smarterclayton hit, it would seem to be a flake, because other people have deployed this template successfully.

**Comment by bparees** [comment]
it's also possible that @smarterclayton's request landed on a node that has an old version of the mongo image and that's somehow causing the problem?

**Comment by sspeiche** [comment]
@smarterclayton I didn't so anything but use the plain vanilla quick-start db that was loaded from https://github.com/openshift/origin/blob/master/examples/db-templates/mongodb-ephemeral-template.json So I didn't make any change to this locally.

**Comment by mfojtik** [comment]
@bparees @smarterclayton https://github.com/openshift/mongodb/pull/138#discussion_r55998685

mongostat is not part of the mongo collection, can you change it to `mongo --eval "quit()"` ?

**Comment by mfojtik** [comment]
(and I will change that in the template asap)
