### ISSUE TITLE
log err:level=error msg="Failed to get pwuid struct: user: unknown userid 4294967295

### ISSUE THREAD

**Issue by lifei825** [openshift/origin#8749]
[provide a description of the issue]
As long as the operation of origin-node.service has been an error: level = error MSG = "Failed to get pwuid struct: user: unknown userid 4294967295
##### Version
[provide output of the `openshift version` or `oc version` command]
origin-node-1.1.6 && origin-node-1.2
##### Steps To Reproduce
1. [step 1]
systemctl start  origin-node.service
2. [step 2]
tailf /var/log/messages
##### Current Result
May  5 11:39:36 h-mxyt5ybq journal: time="2016-05-05T11:39:36.767176350+08:00" level=error msg="Failed to get pwuid struct: user: unknown userid 4294967295"
May  5 11:39:37 h-mxyt5ybq journal: time="2016-05-05T11:39:37.469047604+08:00" level=error msg="Failed to get pwuid struct: user: unknown userid 4294967295"
May  5 11:39:37 h-mxyt5ybq journal: time="2016-05-05T11:39:37.469603614+08:00" level=error msg="Failed to get pwuid struct: user: unknown userid 4294967295"
May  5 11:39:37 h-mxyt5ybq journal: time="2016-05-05T11:39:37.768161227+08:00" level=error msg="Failed to get pwuid struct: user: unknown userid 4294967295"
May  5 11:39:38 h-mxyt5ybq dnsmasq[15435]: Maximum number of concurrent DNS queries reached (max: 150)
May  5 11:39:38 h-mxyt5ybq journal: time="2016-05-05T11:39:38.769246642+08:00" level=error msg="Failed to get pwuid struct: user: unknown userid 4294967295"
May  5 11:39:39 h-mxyt5ybq journal: time="2016-05-05T11:39:39.468964908+08:00" level=error msg="Failed to get pwuid struct: user: unknown userid 4294967295"
May  5 11:39:39 h-mxyt5ybq journal: time="2016-05-05T11:39:39.469483016+08:00" level=error msg="Failed to get pwuid struct: user: unknown userid 4294967295"
May  5 11:39:39 h-mxyt5ybq journal: time="2016-05-05T11:39:39.662053566+08:00" level=error msg="Failed to get pwuid struct: user: unknown userid 4294967295"
##### Additional Information
plaese help ths!
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by liggitt** [comment]
@sdodson this look familiar to you?

**Comment by sdodson** [comment]
No I've never seen this. Assuming you have /etc/NetworkManager/dispatcher.d/99-origin-dns.sh can you make it non executable and reboot then see if the problems still happen?

```
chmod -x /etc/NetworkManager/dispatcher.d/99-origin-dns.sh
sed -i '/dnsIP:.*/d' /etc/origin/node/node-config.yaml
reboot
```

**Comment by lifei825** [comment]
Thank you very much! Already good

**Comment by sdodson** [comment]
@lifei825 disabling dnsmasq made the problems go away?

**Comment by lifei825** [comment]
Yes, do that  ： sed -i '/dnsIP:.*/d' /etc/origin/node/node-config.yaml  && reboot

**Comment by liggitt** [comment]
@sdodson anything actionable for us here?

**Comment by sdodson** [comment]
@liggitt I don't think so.

**Comment by sdodson** [comment]
This is a docker-1.9.1 bug, possibly rhel/centos specific, https://bugzilla.redhat.com/show_bug.cgi?id=1335635

**Comment by lifei825** [comment]
Excuse me, does this make a difference to the service

**Comment by sdodson** [comment]
> Excuse me, does this make a difference to the service

We don't believe so. If you find out that it's causing problems please let us know what sort of problems (aside from log spam) it's causing.
