### ISSUE TITLE
Default buttons stay focus after click

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#8756]
When clicking on the `Start build` or any other button that has `btn btn-default` classes they stay focused until additional mouse click is done.
Screen from how it looks after the button is clicked:
![screenshot-5](https://cloud.githubusercontent.com/assets/1668218/15045429/b904a428-12da-11e6-8799-42e7d67222e1.png)

Would be good if we align on the proper behavior we want.

@spadgett commented that we shouldn't try to remove focus unless we have a good reason because it can hurt keyboard accessibility.

@jwforres @sg00dwin @rhamilto @benjaminapetersen thoughts ?

**Comment by spadgett** [comment]
@jhadvig do you not like how the outline looks or is there another concern?

**Comment by rhamilto** [comment]
I can't seem to reproduce this in Chrome for OS X (via mouse or keyboard navigation).  The button gets unfocused and disabled.

![screen shot 2016-05-05 at 11 12 51 am](https://cloud.githubusercontent.com/assets/895728/15047358/9793bc48-12b2-11e6-9d99-50052948d70f.PNG)

**Comment by jhadvig** [comment]
@rhamilto sorry you will see it when https://github.com/openshift/origin/pull/8722 lands or if you remove https://github.com/openshift/origin/blob/master/assets/app/views/browse/build-config.html#L24 line 

@spadgett well I dont like the fact that after you press the button, it looks like it stays pressed.

**Comment by jwforres** [comment]
On Thu, May 5, 2016 at 11:21 AM, Jakub Hadvig <notifications@github.com>
wrote:

> @rhamilto <https://github.com/rhamilto> sorry you will see it when #8722
> <https://github.com/openshift/origin/pull/8722> lands or if you remove
> https://github.com/openshift/origin/blob/master/assets/app/views/browse/build-config.html#L24
> line
>
> @spadgett <https://github.com/spadgett> well I dont like the fact that
> after you press the button, it looks like it stays pressed.
>

this sounds like a problem with focus vs active ?

**Comment by jwforres** [comment]
We shouldn't remove focus for accessibility reasons, and the .btn:focus styles are from core bootstrap.  What I am seeing is the button continues to have an outline around it but does not look pressed, which is correct, it is focused but not active.
