### ISSUE TITLE
Question: Is there a way to pass "secret" when using oc-cli

### ISSUE THREAD

**Issue by gt-tech** [openshift/origin#8768]
I am looking for some info around ability to pass a "secret" to OC CLI command line command "new-app"

https://docs.openshift.org/latest/dev_guide/builds.html#using-private-repositories-for-builds
Above link provides information on how this can be done using JSON/YAML based build-configurations, is there a similar way with which it can be passed thru CLI new-app command? 

Our source code GIT repository is private and requires a username/password

**Comment by bparees** [comment]
There's no way to do it currently via the new-app CLI, you have to update the buildconfig after it's created (eg via oc edit), or have new-app generate json/yaml, edit the json, and then create the buildconfig from the json/yaml.

we've got this feature request in our backlog:
https://trello.com/c/gXIlR9SH/765-5-oc-new-app-to-gather-git-creds-evg
