### ISSUE TITLE
configurable git clone timeout

### ISSUE THREAD

**Issue by bparees** [openshift/origin#8772]
the build process does a git ls-remote to check if a repo is accessible.  the timeout is hardcoded at 16s.  Slow dns or other network issues can cause that call to fail.

1) the timeout should be configurable
2) we should print a clearer message when it happens

@knobunc fyi.  I don't think we want to warn but still wait 1-2 minutes because the point of the test is to fail fast if the repo is inaccessible, such as might happen if you put a bad hostname or IP in.

**Comment by mfojtik** [comment]
+1 already experienced this on my poor home internet ;-)

**Comment by knobunc** [comment]
Thanks @bparees

**Comment by Mangirdaz** [comment]
Thanks! This one becoming pain for us too :)

**Comment by Mangirdaz** [comment]
Do we have bugzilla for this one? Any workaround how we can configure timeout?

**Comment by bparees** [comment]
@Mangirdaz no bugzilla, this is our tracker for it and no,unfortunately there is no workaround currently that i can think of.

**Comment by Mangirdaz** [comment]
@bparees Thanks. I assume its hard-coded somewhere in Builder image. Would it be possible to overlay one more Docker layer on top of RH image for this and just sed s/old/new/ for bigger value? 
We import All images to internal registry, and pull them from it.

**Comment by bparees** [comment]
so this logic resides in the openshift/origin-sti-builder and openshift/origin-docker-builder images.  by default, openshift attempts to pull those images using a tag that matches the commit level of the openshift master.  if you specify --latest-images then instead it will use whatever version of those images exists locally.  So you'd have to:

1) build new versions of those images with the changed timeout (it's in code, so just layering a change wouldn't really work)
2) make sure the new image existed on all your openshift nodes
3) launch your master with --latest-images

so...doable, but not trivial.

**Comment by Mangirdaz** [comment]
Thanks! 
Will raise this one internally and try to get priority on this. When we could expect this to see implemented? This would help us to plan.

**Comment by bparees** [comment]
it shouldn't be too difficult, i'd hope we can get to it in the next few weeks.

**Comment by bparees** [comment]
@csrwng did you ever land the fix for this?

**Comment by bparees** [comment]
fixed by https://github.com/openshift/origin/pull/9124

**Comment by livelace** [comment]
Any news ? :)

**Comment by knobunc** [comment]
@livelace What do you mean?  The issue is marked as resolved by #9124.  Did that not fix it for you?

**Comment by livelace** [comment]
@knobunc 

Sorry, I lost discussion thread. I thought, that timeout setting will be added in build configuration ?

**Comment by livelace** [comment]
Like these settings - https://docs.openshift.org/latest/dev_guide/builds.html#source-code

**Comment by bparees** [comment]
no we decided to implement this by just doing an exponential retry backoff over a longer period of time, but it should still solve your problem (and you don't have to make any config changes).

**Comment by Mangirdaz** [comment]
Works for me :D

**Comment by livelace** [comment]
@bparees Ok, thanks. I will try to change images on build server.
