### ISSUE TITLE
Crash with new-app

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#8777]
##### Version
oc v1.1.3-40-g678463c-dirty
kubernetes v1.2.0-alpha.7-703-gbc4550d

##### Steps To Reproduce
1. oc new-app xxxxxxxxx

##### Current Result
```
panic: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x83e41a]

goroutine 1 [running]:
github.com/fsouza/go-dockerclient.(*Client).do(0x0, 0x17fd1b8, 0x3, 0x180f890, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x83e41a]
```

##### Expected Result

image or template not found or something

##### Additional Information

full backtrace here : 

-$ oc new-app xxxxxxxxxx
http://sprunge.us/YWIe

**Comment by mfojtik** [comment]
@chmouel can you please give me full oc command? Are you pointing it to a non-existing image?

**Comment by mfojtik** [comment]
@csrwng I can't see any obvious reason why this will fail like this in the current master

**Comment by chmouel** [comment]
Yes here with the full command : 

-$ oc new-app foo/bar

<img width="1146" alt="2016-05-09__13-37-58-20413" src="https://cloud.githubusercontent.com/assets/98980/15111994/57da0a62-15eb-11e6-87f2-477dab1b6d7b.png">

**Comment by csrwng** [comment]
@chmouel @mfojtik This was fixed with this PR:
https://github.com/openshift/origin/pull/7433

The commit (678463c) that @chmouel is currently running does not have this fix.

**Comment by chmouel** [comment]
Right, I believe it was a old binary I have just recompiled everything and this works fine, thanks!
