### ISSUE TITLE
sample-app instructions are too much

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#8784]
The sample-app in the examples dir of the repo has instructions on how to install and run OpenShift. This should not be in these instructions but should instead point to other instructions.

This would help make the instructions more readable.

As a supplemental request I would love if we could change the readme to assume that the user is using the vagrant all-in-one https://www.openshift.org/vm

It is fine to also say "Hey evangelists, why don't you take over the readme and submit a pull request"

Thanks

**Comment by mfojtik** [comment]
Hey evangelists, why don't you take over the readme and submit a pull request? :-)

**Comment by bparees** [comment]
@mfojtik +1 :)

**Comment by thesteve0** [comment]
This got buried in my email - is there a way to get an issue to remind me in github or something so I don't keep forgetting it?

**Comment by bparees** [comment]
dunno about reminders, but there is github.com/issues to show you issues assigned to you (have to click the assigned tab)
