### ISSUE TITLE
registry-editor &  registry-viewer role should be able to list rolebindings in project. 

### ISSUE THREAD

**Issue by sub-mod** [openshift/origin#8791]
registry-editor &  registry-viewer role should be able to list rolebindings in project. For which it should be able to create localresourceaccessreviews in project

##### Version
oc v1.3.0-alpha.0-56-gd9c6483
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Steps To Reproduce
1. oc whoami -> bob
2. oc new-project test-project
3. oc policy add-role-to-user registry-admin bob
4. oc create -f rolebinding.json
(make a new user bill registry-editor on project test-project)
5. oc whoami -> bill
6. oc get project ->  test-project
7. oc get rolebindings

##### Current Result
User "bill" cannot list rolebindings in project "aaa"
##### Additional Information
This feature is needed to show that user bill has only registry-editor capabilities in the registry UI.

**Comment by sub-mod** [comment]
PR introducing registry-admin role: #6963
@aweiteka @stefwalter @deads2k

**Comment by deads2k** [comment]
I don't think that we're likely to allow that since it provides information about other users and it doesn't actually give you information about what you can do (that role can be anything).

We did put in a new endpoint that actually tells you what you can do though.  See https://github.com/openshift/origin/pull/8675.  I think that would give you the information you need for the current user.

**Comment by sub-mod** [comment]
@deads2k  is there a oc command for that ?

**Comment by deads2k** [comment]
> @deads2k is there a oc command for that ?

There will be.  I made one, but its likely to move before we tag the next level.

**Comment by sub-mod** [comment]
can I make a curl request on the latest origin code ?
like this ?
curl -k -H "Authorization: Bearer $(oc whoami -t)" -d@/home/spiderman/json_files/SelfSubjectRulesReview.json  https://192.168.122.1:8443/oapi/v1/namespaces/aaa/selfsubjectrulesreviews

**Comment by deads2k** [comment]
@sub-mod yes, its a POST.  See the sample content here: https://github.com/openshift/origin/pull/8675#issuecomment-216238504 

It's a POST because we are reasonably likely to add options at some point in time and to remain consistent with other code, those options come in as part of an API object.

There is a command `oc policy what-can-i-do`, but as I mentioned, we're unhappy with the name, so its likely to move in the short term.  Maybe something like `oc policy can-i [verb] [resource] [name] [--list]`, but that's not fixed

**Comment by sub-mod** [comment]
@deads2k not sure why it is failing https://paste.fedoraproject.org/364248/98913146/
Can i make this request as a projectadmin ?

**Comment by deads2k** [comment]
> @deads2k not sure why it is failing https://paste.fedoraproject.org/364248/98913146/
> Can i make this request as a projectadmin ?

yes, any user can do it.

```bash
[deads@deads-dev-01 origin]$ oc login -u deads -p asdf localhost
Login successful.

You don't have any projects. You can try to create a new project, by running

    $ oc new-project <projectname>

[deads@deads-dev-01 origin]$ oc new-project foo
Now using project "foo" on server "https://localhost:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    $ oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.
[deads@deads-dev-01 origin]$ oc policy what-can-i-do
Verbs                                                          Non-Resource URLs   Extension   Resource Names   API Groups      Resources
[create delete deletecollection get list patch update watch]   []                              []               []              [configmaps endpoints persistentvolumeclaims pods pods/attach pods/exec pods/log pods/portforward pods/proxy replicationcontrollers replicationcontrollers/scale secrets serviceaccounts services services/proxy]
[impersonate]                                                  []                              []               []              [serviceaccounts]
[create delete deletecollection get list patch update watch]   []                              []               []              [buildconfigs buildconfigs/instantiate buildconfigs/instantiatebinary buildconfigs/webhooks buildlogs builds builds/clone builds/log deploymentconfigrollbacks deploymentconfigs deploymentconfigs/log deploymentconfigs/scale generatedeploymentconfigs imagestreamimages imagestreamimports imagestreammappings imagestreams imagestreams/secrets imagestreamtags localresourceaccessreviews localsubjectaccessreviews processedtemplates projects resourceaccessreviews rolebindings roles routes subjectaccessreviews templateconfigs templates]
[create delete deletecollection get list patch update watch]   []                              []               [autoscaling]   [horizontalpodautoscalers]
[create delete deletecollection get list patch update watch]   []                              []               [batch]         [jobs]
[create delete deletecollection get list patch update watch]   []                              []               [extensions]    [horizontalpodautoscalers jobs replicationcontrollers/scale]
[get list watch]                                               []                              []               [extensions]    [daemonsets]
[get list watch]                                               []                              []               []              [bindings configmaps endpoints events imagestreams/status limitranges minions namespaces namespaces/status nodes persistentvolumeclaims persistentvolumes pods pods/log pods/status policies policybindings replicationcontrollers replicationcontrollers/status resourcequotas resourcequotas/status resourcequotausages routes/status securitycontextconstraints serviceaccounts services]
[get update]                                                   []                              []               []              [imagestreams/layers]
[update]                                                       []                              []               []              [routes/status]

```
