### ISSUE TITLE
oc start-build output

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8797]
Should be similar to `oc deploy --latest`. Actually for start-build, we should use cmdutil.PrintSuccess for the new build message and then hint to oc logs if --follow wasn't specified.

cc: @bparees @mnagy

**Comment by bparees** [comment]
since @mnagy is going to be in this code for his card this sprint anyway, assigning to him.

**Comment by jupierce** [comment]
@bparees  Many of the extended build test cases assume that the only output from start-build will be the new build name. I would expect a change here to have a ripple effect through those tests and any other systems reliant on the existing behavior. 

> # oc start-build test
> test-1

> # oc deploy dctest --latest
> Started deployment #2
> Use 'oc logs -f dc/deployment-simple' to track its progress.

If you are OK to proceed, what would be the best programmatic method by which to determine the build name? I don't like the idea of parsing human readable command output (i.e. finding "Started build #2" and assuming that meant a build name of <buildconfig>-2). Perhaps a start-build switch which output json describing the build?

# oc start-build test --detail
....human readable...
{ "build" : "test-2"  , .... }

**Comment by bparees** [comment]
@jupierce good point.  @smarterclayton would this change constitute an api change, since today the start-build output is easily used by scripts that customers may have written and those would be broken by a change like this?

i don't really want to introduce a flag, seems overly complicated/not likely to get used, so i think it really comes down to whether we want to fundamentally change the output form provided by start-build, or accept that it's an api now and we need to stick with it.

**Comment by kargakis** [comment]
Most commands support `-o name` for returning what `oc start-build` currently returns (plus the resource type) by default.
```
$ oc start-build foo -o name
build/foo-1
```

**Comment by bparees** [comment]
ironically oc deploy does not appear to be one of those commands.

**Comment by bparees** [comment]
in any case it's still a change that would potentially break existing user scripts, so we need to consider that.

**Comment by kargakis** [comment]
> ironically oc deploy does not appear to be one of those commands.

Yes, I am not concerned about it because we are moving `oc deploy` to `oc rollout` and that should support it.

**Comment by jupierce** [comment]
Looks like -o is what I was looking for. Same concerns on the ripple effect, but ultimately I think it would be a good thing for users to rely on a documented behavior instead of the existing method.

**Comment by jupierce** [comment]
It also appears this was on @smarterclayton 's roadmap: https://github.com/openshift/origin/blob/1ee2710c6182ff2acfd590fd1cbb9e99ef562171/pkg/cmd/cli/cmd/startbuild.go#L287-L288

**Comment by jupierce** [comment]
@smarterclayton this went cold when you were busy at Summit. Can you take a look and weigh in?
