### ISSUE TITLE
TestNewAppRunBuilds-4 failure

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8802]
```
--- FAIL: TestNewAppRunBuilds-4 (12.35s)
	newapp_test.go:1197: successful build from dockerfile with custom name: unexpected error: no match for "openshift/origin-base"
FAIL
```
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5851/consoleFull#127309647156c25e74e4b05b79524e5d56

**Comment by csrwng** [comment]
This failure seems to have had the same underlying cause as https://github.com/openshift/origin/issues/8444
and should be mitigated by 
https://github.com/openshift/origin/pull/8574

Please reopen if seen again.
