### ISSUE TITLE
Upgrade QoS tier for the registry

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8820]
Similar to what was done for the router in https://github.com/openshift/origin/pull/8495

@miminar @legionus @soltysh

**Comment by legionus** [comment]
Now we can't change limits after they have been set for the container. We can't be sure that the limit is reached. In this case, the user will not be able to increase it.

@derekwaynecarr Do you have any plans to make the limits modifiable ?

**Comment by soltysh** [comment]
@legionus not quite true. Since you're setting this at a PodTemplate level of a DeploymentConfig. All is required in that case is a re-deployment of a registry to update to new values. Having reasonable startup values is valuable here.

**Comment by legionus** [comment]
@soltysh What happened if your registry don't have persistent storage (no s3, no swift) and you've reached the limit? It seems to me a bad idea to fix the limit by re-deployment.

I can not calculate the upper limit. It depends on the load.

**Comment by kargakis** [comment]
I am not sure if anyone is going to run a registry w/o persistent storage.
I think I like Maciej's proposal of updating the DeploymentConfig if the
limit is hit.

**Comment by soltysh** [comment]
> @soltysh What happened if your registry don't have persistent storage (no s3, no swift) and you've reached the limit? It seems to me a bad idea to fix the limit by re-deployment.

But the referenced PR sets just CPU and memory, so storage does not count here. We can discuss the average load with operations, for example. Besides every admin will be always able to change it at any moment.
