### ISSUE TITLE
forbidden exec/rsh error is unclear

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#8823]
When a user tries to exec/attach/rsh into a pod that is forbidden because of SCC restrictions, the error is very unclear about why it is not working:

```
[18:38:36] INFO> Shell Commands: oc exec ruby-sample-build-2-build -n 5-bs1  -- env
      Error from server: pods "ruby-sample-build-2-build" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```

The error should explain that they cannot exec/attach/rsh into a pod that they could not have created, or something more usable.

/cc @cjryan @bparees

**Comment by php-coder** [comment]
This has been fixed by https://github.com/openshift/origin/pull/11549
