### ISSUE TITLE
Can't enable GCS storage for registry, Kube needs a version bump

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8826]
In order to enable GCS storage for the docker registry, we need Kube to bump to at least 9bf6e6e569ff057f75d9604a46c52928f17d2b54 of google.golang.org/api/googleapi (to match what docker distribution is using).  That'll probably involve a full regression test on GCE, because the cloud provider also uses that API.  Then we'll need to set it up so that the docker registry is built with include_gcs tags (and probably a few others).

**Comment by smarterclayton** [comment]
@pweil- @miminar @ncdc 

I had started enabling this, and then realized we were blocked by the Kube version.  Other more extreme options involve having a separate vendor directory for docker distribution, which is possible but could get ugly.  Either way, we are blocked on enabling GCS until we can sort this out.

**Comment by mfojtik** [comment]
@smarterclayton we are getting there... https://github.com/openshift/kubernetes/pull/19

**Comment by smarterclayton** [comment]
Rebase isn't what needs bumped - Kube itself is too far behind.

**Comment by pweil-** [comment]
@smarterclayton is this an immediate issue if we use a GCE PD rather than trying to configure the registry to use the GCS driver?  It appears there is an add on that does that: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry

**Comment by smarterclayton** [comment]
We wouldn't be able to scale to multiple registries.

**Comment by pweil-** [comment]
couldn't you mount it as nfs type and share it between them?  Though we already have NFS issues anyway...

**Comment by smarterclayton** [comment]
We don't want to use NFS for registry.

On May 20, 2016, at 3:43 PM, Paul Weil <notifications@github.com> wrote:

couldn't you mount it as nfs type and share it between them? Though we
already have NFS issues anyway...

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/8826#issuecomment-220700794>

**Comment by tracyrankin** [comment]
@smarterclayton can we close this now that this PR is merged?
https://github.com/openshift/origin/pull/9211

**Comment by smarterclayton** [comment]
Yes
