### ISSUE TITLE
extended test fake: Kubectl logs should be able to retrieve and filter logs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8829]
```
Extended.[k8s.io] Kubectl client [k8s.io] Kubectl logs should be able to retrieve and filter logs [Conformance]

/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubectl.go:842
Expected
    <int>: 0
to equal
    <int>: 1
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/927/testReport/junit/(root)/Extended/_k8s_io__Kubectl_client__k8s_io__Kubectl_logs_should_be_able_to_retrieve_and_filter_logs__Conformance_/

**Comment by smarterclayton** [comment]
@pweil- as well, this has suddenly started happening much more frequently.  Not sure what the cause is.

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/928/

**Comment by smarterclayton** [comment]
@ncdc just gave it to you to have someone's name next to it - punt it down the chain as needed.

**Comment by liggitt** [comment]
seen upstream at https://github.com/kubernetes/kubernetes/issues/25426

**Comment by ncdc** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/25598

**Comment by aveshagarwal** [comment]
I just checked that the changes in https://github.com/kubernetes/kubernetes/pull/25598 are already in origin now (except removal of the comment // TODO: trimspace should be unnecessary after switching to use kubectl binary directly in util.go). Can we close it now?
