### ISSUE TITLE
OpenShift with Keycloak as OpenId provider, using `oc login --token` is not intuitive and fails with: The token provided is invalid or expired

### ISSUE THREAD

**Issue by donovanmuller** [openshift/origin#8832]
Following the basics from [this guide](http://blog.keycloak.org/2015/06/openshift-ui-console-authentication.html) to integrate Keycloak as an identity provider, then, after [getting an access token](http://blog.keycloak.org/2015/10/getting-started-with-keycloak-securing.html) and using that token to login with `oc login --token=...` fails with `error: The token provided is invalid or expired.`

##### Version
oc v1.2.0-rc1
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1: Get the access token from Keycloak:

```
$ TOKEN=`curl -s -X POST https://keycloak/realms/openshift/protocol/openid-connect/token  -H "Content-Type: application/x-www-form-urlencoded" -d 'username=xxx' -d 'password=xxx' -d 'grant_type=password' -d 'client_id=openshift' -d 'client_secret=xxx' | jq -r '.access_token'`
```

2: Check the token:

```
$ echo $TOKEN
eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI3YTliZmI0Yy01YTQxLTRjYWMtYjI1Ny1mMmYzZDI3YTZlYmMiLCJleHAiOjE0NjI5Njg0MDgsIm5iZiI6MCwiaWF0IjoxNDYyOTUwNDA4LCJpc3MiOiJodHRwczovL2tleWNsb2FrLmJpc29uLnBpLmIvcmVhbG1zL29wZW5zaGlmdCIsImF1ZCI6Im9wZW5zaGlmdCIsInN1YiI6Ijk3ZjI3MTYyLTMxYTQtNGVkOS1hZDM2LTM4OTdhMjBhZmRlMiIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9wZW5zaGlmdCIsInNlc3Npb25fc3RhdGUiOiIyOWeghebhdfgnmYjEzOC1iYTE4LTQ0MmQtOGYxNS1hMmZjNGU1YzhlZTkiLCJjbGllbnRfc2Vzc2lvbiI6IjQ1ODEzYWU3LWJjMTItNGZlZC1hOWIwLTBjZTQ0MzQ2MDczMSIsImFsbG93ZWQtb3JpZ2lucyI6W10sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Idfsdgdmlldy1wcm9maWxlIl19fSwibmFtZSI6IkJJU09OIENJL0NEIiwicHJlZmVycmVkXdfgdfhgewhbaXZlbl9uYW1lIjoiQklTT04iLCJmYW1pbHlfbmFtZSI6IkNJL0NEIiwiZW1haWwiOiJiaXNvbkBhYnNhLmNvLnphIn0.SupkC7W1oXwqqi513dVByJmSCuglsyHDVhO9REO0BFjLEA1sl7ZSXwDbEx4lVnJVMfpjWbjl9gMe4_7bH1OTPNLMnHPnE1gQILd3tKD0XGbCIkuHEogxp9ZP-QwCJPjjc5fBAuDohlaAUYES6jdC36xhPIwlHFnsBg1Dy88i1aHWPjGu8IZjeRY35jloY23gCFJt6I9FvKtZf2G7XXHmgH2qydA5D5QuMA2ngVlUbbYcl3cHZp8o34f-mGPhMoxruWwdbnfjoda73cHBVQAdodITf1pK9HqZsPFXUgk1CIVlxz2HaqK5oLHAneMJF9wuYYhYxE-2ngz4V3shgCq4WQ
```

NOTE: the above token is intentionally invalid (i.e. if you copy/paste it into [jwt.io](http://jwt.io) it will be invalid) for privacy reasons.

3: Validate token:

![screen shot 2016-05-11 at 9 10 59 am](https://cloud.githubusercontent.com/assets/1175891/15172814/90b1a322-1758-11e6-8ca2-6518474025f9.png)

4: Use the token:

```
$ oc login --insecure-skip-tls-verify=true https://master:8443 --token=$TOKEN
error: The token provided is invalid or expired.
```

##### Current Result

```
$ oc login --insecure-skip-tls-verify=true https://master:8443 --token=$TOKEN
error: The token provided is invalid or expired.
```

##### Expected Result

Using token (access token) returned from Keycloak:

```
$ oc login --token=$TOKEN server=https://master:8443
Logged into "https://master:8443" as "xxx" using the token provided.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default (current)
  * ...

Using project "default".
```

I would expect to use the access token retrieved from the JWT token from Keycloak to login with `oc`.
Also, why is the token returned via https://master:8443/oauth/token/request so much shorter than the access token from Keycloak?
 
##### Additional Information

Using the suggested way of getting an API token (https://master:8443/oauth/token/request) which then redirects to Keycloak for authentication, gives you a token of: `oHKg-brdCDr9nYECWRNwfq1crCylaV5M89KfqrhxeaQ`

![screen shot 2016-05-11 at 9 20 15 am](https://cloud.githubusercontent.com/assets/1175891/15172986/9b6ba9c4-1759-11e6-8d8e-3d38d3032112.png)

```
$ oc login --token=oHKg-brdCDr9nYECWRNwfq1crCylaV5M89KfqrhxeaQ --server=https://master:8443
Logged into "https://master:8443" as "xxx" using the token provided.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default (current)
  * ...

Using project "default".
```

This is obviously much shorter than the access token retrieved from Keycloak.
Also, if you use a token from a service account, it works:

```
$ oc sa get-token xxx --namespace=xxx
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJiaXNvbi1jaSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJiaXNvbi1hcHAtc2VydmljZS10b2tlbi1scDN6YSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJiaXNvbi1hcHAtc2VydmljZSIsIwerewrZmQ1MSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpiaXNvbi1jaTpiaXNvbi1hcHAtc2VydmljZSJ9.MSUm3o_Q3gNsUY5SSADfwQN3b12xav-EPSUIcrhgwwPumQrGUzHhMJPlqqHvm1iZr_bIQqOaei9bQjM4izSmOPNG-AkGICPWCOnm22KuIWJa8znaFJgb120gRWNkezCl6uojF0yuv4pdXlqw3Yi4-37I_F4Inqh_UyYuSgvT62J2RRrq2UBQGpNOUnH9kU6x6rxkyfF3f-1EHb4j_5s1CQNzN7PX5CrvQnksqYgXT3HkUvcCEpxqel0o2zLnn5wZnvQFNR_Vo49Lk327oxXBK5Bd8ZVCFuvcz8mKrH_1d8F_Fsuz8VWoRe8hgfLAnRVbj3Lvp1E1gRfwhrqIKTnzAQ
$ oc login --token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJiaXNvbi1jaSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJiaXNvbi1hcHAtc2VydmljZS10b2tlbi1scDN6YSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJiaXNvbi1hcHAtc2VydmljZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjY0NmUwYjNlLTBkZTEtMTFlNi1hNWRhLTQ0MzljNDU1ZmQ1MSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpiaXNvbi1jaTpiaXNvbi1hcHAtc2VydmljZSJ9.MSUm3o_Q3gNsUY5SSADfwQN3b12xav-EPSUIcrhgwwPumQrGUzHhMJPlqqHvm1iZr_bIQqOaei9bQjM4izSmOPNG-bsdhsagfah-37I_F4Inqh_UyYuSgvT62J2RRrq2UBQGpNOUnH9kU6x6rxkyfF3f-1EHb4j_5s1CQNzN7PX5CrvQnksqYgXT3HkUvcCEpxqel0o2zLnn5wZnvQFNR_Vo49Lk327oxXBK5Bd8ZVCFuvcz8mKrH_1d8F_Fsuz8VWoRe8hgfLAnRVbj3Lvp1E1gRfwhrqIKTnzAQ --server=https://master:8443
Logged into "https://master:8443" as "system:serviceaccount:xxx:xxx" using the token provided.

You don't have any projects. You can try to create a new project, by running

    $ oc new-project <projectname>

$
```

![screen shot 2016-05-11 at 9 31 23 am](https://cloud.githubusercontent.com/assets/1175891/15173219/32b097b2-175b-11e6-9635-01444d5fc3b3.png)

**Comment by liggitt** [comment]
`oc login --token=...` simply sets the given token as the API token to use. That token is required to be a token minted and recognized by the API server, not a third party token. 

The generated API tokens are not JWTs

**Comment by donovanmuller** [comment]
@liggitt The service account token is though. So why does that work?

**Comment by liggitt** [comment]
Because they are created and recognized by the API.

**Comment by liggitt** [comment]
Also, https://github.com/openshift/origin/pull/8732 recently added support for password grant types, so you could use `oc login` directly without doing the web flow token dance

**Comment by donovanmuller** [comment]
Ok, is there any chance of adding this to the docs? 

Currently it isn't explicitly mentioned that access tokens returned from identity providers other than API server itself are not recognised. The assumption would be (at least by me) that the tokens would be recognised, as it's the same OpenID Connect flow to authenticate the web console for instance.

**Comment by donovanmuller** [comment]
Awesome (#8732), that will help allot.

**Comment by liggitt** [comment]
The auth overview at https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#api-authentication discusses the API OAuth token mechanism, though clarifying suggestions are welcome (probably as issues or pulls against the openshift-docs repo)

**Comment by johanbaron-axa** [comment]
Hello:

In this part:

_Additional Information
Using the suggested way of getting an API token_

Can you share how did you get the token.

Thanks
