### ISSUE TITLE
pod failed to run if not created by system:admin

### ISSUE THREAD

**Issue by catherinesword** [openshift/origin#8837]
[provide a description of the issue]
When I use oc on my local machine, login as a password based user, the pod I created always failed as it cannot start container. I've no idea how to login as system:admin on my local machine, so I did it on the AWS instance where master is running. If I create pod as system:admin, it works perfectly.

I added cluster-admin role to my username, but the problem is still there.

Update: Now I doubt it is the problem of my docker image, since I can create hello-openshift pod without problem as a regular user. In my docker image, I use a jetty:latest as base, don't know if this have some effects.
Or would it be the problem of scc? 

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v1.2.0-rc2
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. [step 1]

On the local machine, login as a password based user, get the project.
```oc create -f test.json``` can create a pod, but it soon fails to start container.

2. [step 2]

ssh to the AWS instance where master is running, login ```oc login -u system:admin``` and ```oc create -f test.json```, the pod is properly created and running without any problem.

##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
ERROR: [DCli0014 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context 'test/ip-172-30-2-63-ec2-internal:8443/admin':
       The server URL is 'https://ip-172-30-2-63.ec2.internal:8443'
       The user authentication is 'admin/ip-172-30-2-63-ec2-internal:8443'
       The current project is 'test'
       (*errors.StatusError) the server has asked for the client to provide credentials
       
       This means that when we tried to make a request to the master API
       server, the request required credentials that were not presented. This
       can happen with an expired or invalid authentication token. Try logging
       in with this user again.

[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by pweil-** [comment]
@catherinesword a couple questions

1.  are you seeing events that indicate errors?
2.  what do the pod logs say when you create as a normal user (many times this will tell you that the pod is trying to do something that has been restricted - like a sudo operation when running as a normal user)

It is likely that your pod is expecting to run as root which is not recommended. When you log in as the `system:admin` user you get access to the `anyuid` scc which will allow you to run as root.  If this is the case you may need to grant access to the `anyuid` scc to your non-admin user to run this container correctly via `oadm policy add-user-to-scc`

**Comment by pweil-** [comment]
closing due to no response.  Please reopen if necessary.
