### ISSUE TITLE
CLI to watch for pod termination and exit

### ISSUE THREAD

**Issue by jmccormick2001** [openshift/origin#8839]
would be great to have a CLI 'oc get pod' option that works with --watch or -watch-only
that would let the command exit when the pod completely terminates.  Currently 
the 'oc get pod --watch' command seems to hang even after the pod terminates.

Would be great to have an option like '--exit-on-term' or similar that when specified would
let the command exit successfully when the pod does actually terminate.  This would let
script writers better check for a pod being terminated.
##### Version

oc v3.1.1.6-33-g81eabcc
kubernetes v1.1.0-origin-1107-g4c8e6f4
##### Steps To Reproduce
1. oc get pod some-pod --watch=true
2. oc get pod some-pd --watch-only=true
##### Current Result

the command continues to hang after the pod has terminated
##### Expected Result

with the new command line option, the command would exit with rc=0 after
the pod has terminated completely

**Comment by deads2k** [comment]
@smarterclayton `oc sync`?

**Comment by smarterclayton** [comment]
Yeah

**Comment by smarterclayton** [comment]
Actually, this is more "wait"
