### ISSUE TITLE
regression on ImageChange build triggers

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#8842]
Creating a build config with an `ImageChange` trigger now seems to (incorrectly) require an `imageChange` attribute. According to https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-imagechangetrigger there are no required attrs.

This feels like user error but I'm not seeing how.

##### Version

$ oc version
oc v1.3.0-alpha.0-456-g51f22e6
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Steps To Reproduce

1. oc new-app https://raw.githubusercontent.com/openshift/origin-apiman/d01f994dd01a639672225bda40a43fd30be9df67/hack/dev-builds.yaml

##### Current Result

```
[...]
    error: BuildConfig "apiman-deployer" is invalid: spec.triggers[1].imageChange: Required value
    error: BuildConfig "apiman-elasticsearch" is invalid: spec.triggers[1].imageChange: Required value
    buildconfig "apiman-curator" created
    buildconfig "apiman-builder" created
    error: BuildConfig "apiman-console" is invalid: spec.triggers[1].imageChange: Required value
    error: BuildConfig "apiman-gateway" is invalid: spec.triggers[1].imageChange: Required value
--> Failed
```

##### Expected Result
BCs created.

**Comment by gabemontero** [comment]
I believe I fixed this with https://github.com/openshift/origin/commit/931953a7673695606ff730b2d53b3cad230b2fd6

**Comment by sosiouxme** [comment]
Confirmed, this is fixed with latest master. Thanks!

**Comment by gabemontero** [comment]
YW man
