### ISSUE TITLE
Expose registry config as a configmap

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8851]
`oadm registry` should create it by default.

Very nice to have: https://github.com/kubernetes/kubernetes/issues/22368
[Using ConfigMap](http://kubernetes.io/docs/user-guide/configmap/)

cc: @miminar @legionus @soltysh

**Comment by legionus** [comment]
One big question is how to store passwords, which can be in the config of `docker/distribution`. For example [S3](https://docs.docker.com/registry/storage-drivers/s3/#/parameters) or [Swift](https://docs.docker.com/registry/storage-drivers/swift/).

**Comment by kargakis** [comment]
I think we want to continue using `Secrets` cc: @smarterclayton

**Comment by legionus** [comment]
Then close it.

**Comment by smarterclayton** [comment]
Yeah, any config that has a secret in it should be in Secrets, not ConfigMap.
