### ISSUE TITLE
Where is the web console page source, has been deployed on the server

### ISSUE THREAD

**Issue by lifei825** [openshift/origin#8855]
Excuse me,I can't find the openshift js file，Use the find search all path can not find。Can you tell me why！thank you

**Comment by jwforres** [comment]
if you are asking about where it is on a running openshift server, then its embedded in the openshift binary.  Why do you need to get to the JS files?

**Comment by lifei825** [comment]
Thank you very much!I want to add some functionality

**Comment by jwforres** [comment]
please take a look at the docs for adding custom js and css
https://docs.openshift.org/latest/install_config/web_console_customization.html#loading-custom-scripts-and-stylesheets
