### ISSUE TITLE
getsockopt: no route to host

### ISSUE THREAD

**Issue by bkmagnetron** [openshift/origin#8857]
Facing issue with docker registry (Endpoints none)

`# oc describe service docker-registry --config=openshift.local.config/master/admin.kubeconfig`

```
Name:			docker-registry
Namespace:		default
Labels:			docker-registry=default
Selector:		docker-registry=default
Type:			ClusterIP
IP:			172.30.196.160
Port:			5000-tcp	5000/TCP
Endpoints:		<none>
Session Affinity:	ClientIP
```

`# docker logs [container id]`
```
F0512 11:22:46.115454       1 deployer.go:70] couldn't get deployment default/docker-registry-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/docker-registry-1: dial tcp 172.30.0.1:443: getsockopt: no route to host
```

##### Version
CentOS 7
Docker version 1.11.1, build 5604cbe
OpenShift Origin v1.2.0-rc2

##### Steps To Reproduce
Download [link](https://github.com/openshift/origin/releases/download/v1.2.0-rc2/openshift-origin-server-v1.2.0-rc2-642f0af-linux-64bit.tar.gz)
```
# openshift start &> openshift.log &
# sudo chmod a+rwX openshift.local.config/master/admin.kubeconfig
# export CURL_CA_BUNDLE=`pwd`/openshift.local.config/master/ca.crt
# sudo chmod a+rwX openshift.local.config/master/admin.kubeconfig
# oadm registry -n default --config=openshift.local.config/master/admin.kubeconfig
```

**Comment by pweil-** [comment]
@bkmagnetron this looks like it is encountering an error connecting back to the master which may indicate networking issues.  Is the master url available from the node?  What networking setup did you use for this installation?

**Comment by bkmagnetron** [comment]
Fixed it by running the below command in non super user mode
`oadm registry -n default --config=openshift.local.config/master/admin.kubeconfig`

But still I have issues when deploying apps. So, I'll be opening issue thread for that.
