### ISSUE TITLE
Build Release Error

### ISSUE THREAD

**Issue by nichochen** [openshift/origin#8861]
[provide a description of the issue]
Hit into error while running build-release.sh on Fedora 23 amd64

##### Version
Latest source code from openshift/origin
go version go1.5.4 linux/amd64

##### Steps To Reproduce
1. Git clone the latest source code from master
2. cd hack
3. ./build-release.sh

##### Current Result
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
++ Building go targets for darwin/amd64: cmd/openshift cmd/oc
++ Building go targets for windows/amd64: cmd/openshift cmd/oc
Godeps/_workspace/src/github.com/docker/go-connections/sockets/sockets_windows.go:7:2: cannot find package "github.com/Microsoft/go-winio" in any of:
	/usr/local/go/src/github.com/Microsoft/go-winio (from $GOROOT)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/Microsoft/go-winio (from $GOPATH)
	/go/src/github.com/Microsoft/go-winio
!!! Error in hack/../hack/common.sh:301
	'GOOS=${platform%/*} GOARCH=${platform##*/} go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]}"' exited with status 1
Call stack:
	1: hack/../hack/common.sh:301 os::build::build_binaries(...)
	2: hack/build-cross.sh:28 main(...)
Exiting with status 1
!!! Error in hack/../hack/common.sh:253
	'os::build::build_binaries "${OS_CROSS_COMPILE_TARGETS[@]}"' exited with status 1
Call stack:
	1: hack/../hack/common.sh:253 os::build::build_binaries(...)
	2: hack/build-cross.sh:28 main(...)
Exiting with status 1
!!! Error in ./build-release.sh:45
	'docker run -e "OS_ONLY_BUILD_PLATFORMS=${OS_ONLY_BUILD_PLATFORMS-}" -i --cidfile="${context}/cid" openshift/origin-release' exited with status 0 1
Call stack:
	1: ./build-release.sh:45 main(...)
##### Expected Result
Binary build finished without error.

**Comment by sdodson** [comment]
Fixed by https://github.com/openshift/origin/pull/9016
