### ISSUE TITLE
TestAlreadyExistingSecretControllerFlow failure

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8865]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/853/consoleFull#29806813256bf4006e4b05b79524e5923
```
--- FAIL: TestAlreadyExistingSecretControllerFlow (15.22s)
	controller_test.go:175: waiting to reach syncHandler
	controller_test.go:179: failed to call into syncService
```
@deads2k

**Comment by deads2k** [comment]
Added an indication on it.  I saw it once during a [test] run, but I haven't seen it in a [merge] run.  I wonder if its just contention and I need a less aggressive timeout.
