### ISSUE TITLE
Logging on individual nodes, or at scale, criples nodes either by (1) docker daemon die or (2) OutOfDisk.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#8868]
**problem**

We have an upstream logging test : https://github.com/kubernetes/kubernetes/pull/24536 , which we can run with an option to multiply 1kb/sec of logging per node.  When running this test over and over again, a cluster comes to a standstill.  

- if you're lucky, your machine survives for a while and eventually dies  once disks fill up for containers.  So, we need to stop this from happening (somehow)
- if you're unlucky, the entire docker daemon will continuously crash really fast ..  - depending on the way you're logging (i.e. if you have no breaks in your logging) - see the docker issue below in tims comment.

**solution**

The solution here is two fold
- you need a docker version where the daemon is robust to continous logging.  But at the same time
- you need a docker configuration where you're logs that fill disk eventually delete.  

Unless both of these are provided, logging at scale will bring down any your nodes.

**thoughts**

Its not clear wether openshift, or maybe one of the openshift ecosystem tools, should handle and prune the amount of data created by docker -- but possibly at least openshift should issue some warnings or maybe even could start failing pods immediately when a certain number of Nodes reach `OutOfDisk` state.

##### Version
```
oc v3.2.0.16
kubernetes v1.2.0-36-g4a3f9c5

 docker-1.9.1-28.el7.x86_
```

##### Steps To Reproduce
1. Run the Logging test from the above pull request (or any noisy container, you can just do `busy box /bin/sh -c while true ; do  echo 12345123123123 ; done` in a replication controller, or use the e2e artifact from above and focus on the logging soak test, via --ginkgo.focus="logging 1KB every"`
2. Continually try to spin up a pod on the cluster.

##### Current Result

  Eventually, no pods will spin up, or pod running will get very slow, because kubelets will have no free disk/resource to spin containers.  Networking, ssh, and other similar basic resources start to die when this happen as well, obviously.

##### Expected Result

Cluster will continue working, logs might flow into aggreagated logging services (Elasticsearch), but the nodes themselves will still remain available.  

This could be more of a docker issue than anything else?

**Comment by jayunit100** [comment]
cc @timothysc  @jeremyeder  @ekuric @rflorenc

**Comment by timothysc** [comment]
We should probably log this against the installer, as it's a configuration issue. 

/cc @detiber

**Comment by timothysc** [comment]
+1 this too: https://github.com/docker/docker/issues/18057

**Comment by ncdc** [comment]
@timothysc I know we've had a lot of separate threads about logging and resource exhaustion. Is it still appropriate to keep this one open?

**Comment by jayunit100** [comment]
It might be good to keep it  open until the Logging Soak test which is pending upstream is enabled as part of the openshift e2es?  If we saw this happen once , it's possible it can regress.... Tim should probably make the final decision but thought I'd chime in :).

**Comment by timothysc** [comment]
We can always reopen when needed.
