### ISSUE TITLE
No way to programmatically associate pipeline build to deployment

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8877]
Issue uncovered by @fabianofranz. Opening here to track.

We want to show what build triggered what deployment in the web console. Today we look at the output image and match it to the deployment config image change trigger and container image. This doesn't work with Jenkins pipeline build strategies since there is no output image in the build config. We need a way to link the build to a deployment config and deployment.

@bparees @jwforres @smarterclayton

**Comment by bparees** [comment]
arguably we should have this for the normal "buildconfig output triggers a deploymentconfig" linkage too, the fact that the console is basically discovering the association by looking at the BC output and the DC imagechangetriggers seems less than ideal.

**Comment by bparees** [comment]
from our email thread:
gabe:

> So we discussed this on the DevExp architecture call this AM with Clayton.  A very high level summary:
- There are a broader set of similar (but with enough differences) scenarios that warrant a more comprehensive solution; that said, we can make smaller / tactical additions to facilitate the effort here
- Clayton would prefer a first class field on the deployment vs. an annotation; it would be similar to additions to the Build Victor has in progress which are close to merging; minimally the OpenShift Pipeline Plugin would make sure this field is set for Deployments it generates via starting an OpenShift build, explicit start deployment, or image tagging
- There is also some in progress work with consolidating deployments upstream that we'll need to coordinate with

me:
​> we also discussed that there is a need to have more metadata in the images themselves, so that while looking at a deployment and seeing what image it's running, you can see where the image came from.
> but for the console use case, metadata on the deployment itself, placed there by the pipeline job that triggered the deployment, is the most immediate path forward.  So the openshift plugin step that can "trigger a deployment" should be updated to add metadata to the created deployment, indicating the jenkins job that created it.  That info would be added to the first class fields gabe mentioned.

**Comment by bparees** [comment]
@gabemontero this probably needs to turn into a card, but it'll be high priority (probably what you'll be working on next sprint)

**Comment by kargakis** [comment]
@smarterclayton how are we supposed to persist fields not found upstream in order to round-trip? Why does this really need to be a first-class field when we will serialize it as an annotation anyway?

**Comment by kargakis** [comment]
> @smarterclayton how are we supposed to persist fields not found upstream in order to round-trip? Why does this really need to be a first-class field when we will serialize it as an annotation anyway?

Or is this supposed to be a field in the image change trigger which we are going to serialize anyway?

**Comment by kargakis** [comment]
Oh, I see. What is needed here from the deployment side is a status cause, right?

**Comment by spadgett** [comment]
Two quick comments now that I've started web console implementation:

- The link between pipeline build and deployment needs to be set as the deployment *begins* for the transitions to look correct for in progress deployments.
- We also need a link between either build config or build to deployment config. This will let us show pipelines that haven't yet started a deployment.

**Comment by kargakis** [comment]
> The link between pipeline build and deployment needs to be set as the deployment begins for the transitions to look correct for in progress deployments.

The config and image controllers already set causes directly to status as they kick deployments. I have been moving status updates to the config change controller. Deployments should not be kicked automatically anyway if there is no config change trigger. Eventually a config change trigger is bad naming for what we want config change triggers to do (which is pausing)

cc: @ironcladlou @smarterclayton

**Comment by gabemontero** [comment]
@bparees created [this trello card](https://trello.com/c/GkBJsZxf/935-programmatically-associate-pipeline-build-to-deployment)

I left it in the New category for now; I'll defer to you about accelerating it through the stages if you want it scheduled for next sprint as you mentioned in https://github.com/openshift/origin/issues/8877#issuecomment-219476556).

**Comment by bparees** [comment]
thanks @gabemontero

**Comment by bparees** [comment]
@spadgett this card is complete https://trello.com/c/GkBJsZxf/935-8-programmatically-associate-pipeline-build-to-deployment so i think we've given you want you need, can this be closed?

**Comment by spadgett** [comment]
Yes thanks @bparees
