### ISSUE TITLE
CLI link for jsonpath help out of date

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8880]
Running `oc get -h` shows this:

>   -o, --output='': Output format. One of: json|yaml|wide|name|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=... See golang template [http://golang.org/pkg/text/template/#pkg-overview] and jsonpath template [http://releases.k8s.io/HEAD/docs/user-guide/jsonpath.md]

The link for jsonpath.md is out of date. It takes you through two redirects before coming to the latest doc here: http://kubernetes.io/docs/user-guide/jsonpath/

/cc @fabianofranz

**Comment by ripcurld00d** [comment]
Please be advised, that https://github.com/kubernetes/kubernetes/pull/26539 needed to be merged to fix this completely.
