### ISSUE TITLE
DNS Problems in local Openshift origin environment

### ISSUE THREAD

**Issue by gt-tech** [openshift/origin#8886]
After following instructions mentioned here - http://developers.redhat.com/blog/2015/11/19/dns-your-openshift-v3-cluster/, my source-to-image builder pods are unable to get to my intranet code repository which were working until i made the changes as mentioned in previous link, the reason I had to make those changes was because my services weren't able to discover each other otherise.

##### Version
oc v1.2.0-rc1
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. Install Openshift Origin using default ansible playbook
2. Make changes http://developers.redhat.com/blog/2015/11/19/dns-your-openshift-v3-cluster/

Ensure that kubernetes.default.svc.cluster.local is resolvable by using "dig" command using -p 8053 or without any explicit port (implying hittin default port 53 where dnsmasq is running) which means local DNS server at 53 is smart enough to resolve kubernetes services as well as general internet names.

But when the PODs are created, there port 53 is mapped to 8053 port on host which means any DNS query from within POD will hit SkyDNS? (openshift DNS) which isn't capable to resolve anything outside what's in etcd.

##### Current Result
Name resolution outside etcd failing from inside POD

##### Expected Result
Ideally there should be a way for POD to resolve both internal openshift created objects/services as well ability to resolve names from external DNS server running on master/host.

##### Additional Information
Is there something missing in instructions or ansible configurations to make this happen?

**Comment by gt-tech** [comment]
For more information, the resolv.conf in the container that's running the s2i build (oc exec didn't allow me to get into this it, with build containers being privilged containers, so i used docker exec to get to the content of the while)

docker exec -it 703551e165f5 cat /etc/resolv.conf
```
search dev.svc.cluster.local svc.cluster.local cluster.local
nameserver 172.30.0.1
nameserver 127.0.0.1
options ndots:5
```

**Comment by gt-tech** [comment]
turned out to be an iptables problem, after updating firewall rules in iptables issue was resolved!

**Comment by agvikashsagar** [comment]
@gt-tech kindly let me know what was the problem with iptables, I am hitting with same issue now. Openshift created route hostname is not reachable outside the cluster.
