### ISSUE TITLE
Rolling deployment support for mid hooks

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8887]
Similar to https://github.com/openshift/origin/issues/2639

> I want to move this to Rolling as well, so that someone can run a hook as soon as the first pod passes the readiness hook. Need to circle back.

@smarterclayton @ironcladlou

**Comment by azenk** [comment]
I think this is the functionality that I would need to avoid using a custom deployment strategy.  What I'm after is a way to check overall cluster health after each scale down event, but before scale up.  For example, when doing a rolling elasticsearch deploy, I'd like to make sure that the cluster is green (all shards on old node replicated again) before starting the next scale up/down cycle.  Would this hook address that?

**Comment by smarterclayton** [comment]
Today that would have to be a custom deployment.  I think the more we have talked about this we prefer to empower custom deployments.

**Comment by kargakis** [comment]
> Today that would have to be a custom deployment. I think the more we have talked about this we prefer to empower custom deployments.

Agreed. I think there is a lot of value in making sure our core controllers are customizable and can work well with external tooling vs having everything baked in.

**Comment by kargakis** [comment]
@tnozicka assigning to you since you'll be working on the policy template that covers this issue.
