### ISSUE TITLE
sti builds can saturate disk iops

### ISSUE THREAD

**Issue by ofthecurerh** [openshift/origin#8894]
I'm trying to load a single node up with the quickstart apps and am running into issues getting every app into a running state. On the smaller app numbers (10 to 20) the build a deploy pods successfully run and the app pod is started with its corresponding database pod. When trying to run a larger number (38), most of the apps end up in a failed state with either the build or one of the deploy pods failing.
##### Version

oc v3.2.0.20
kubernetes v1.2.0-36-g4a3f9c5
##### Steps To Reproduce

Tool I'm using to populate the node with apps: https://github.com/ofthecurerh/svt/tree/master-vert/openshift_scalability

Quickstart app templates: https://github.com/ofthecurerh/svt/tree/master-vert/openshift_scalability/content/quickstart

To run:

``` shell
$ cd path/to/repo/svt/openshift_scalability
$ git checkout master-vert
$ python cluster-loader.py -f config/master-vert.yaml
```
##### Current Result

These are the stats from my latest attempt:
- 31 out of 38 apps are in a failed state
- 4 out of 38 builds failed
- 36 of 76 deploy pods failed
##### Expected Result

Something greater than a 20% success rate
##### Additional Information

Example failed build log: https://paste.fedoraproject.org/367238/
Example failed deploy log: https://paste.fedoraproject.org/367239/

@jeremyeder 
@ncdc

**Comment by pweil-** [comment]
@ofthecurerh - the deploy log looks like it waited for the pods to become ready but it never happened.  Do you have failed pods from that deployment?  Their logs may give more information about why they were not started successfully. 

The build log looks similar to https://github.com/openshift/origin/issues/4518.  Does  second build of the same app work for you?

**Comment by ofthecurerh** [comment]
@pweil- I'm starting to suspect this is a networking issue. When I tried this on a single node (master and node), I was getting up to 300Gbit/s on loopback and when I tried it on two nodes (one master, one node), the master reported that the pods were evicted and the node was unreachable until I restarted it.

**Comment by pweil-** [comment]
@ofthecurerh thanks for the update.  I'll assign this to networking to help out (or you can close it if you have it worked out) but feel free to reassign back if it doesn't turn out to be a networking issue.

**Comment by jeremyeder** [comment]
@abhgupta tells me there's a story to address build parallelism.

**Comment by timothysc** [comment]
Also anti-affinity is in upstream now so we can prevent build co-location.

**Comment by ofthecurerh** [comment]
@knobunc @pweil- I was finally able to gather enough data to figure out where the problem is. This ended up being a disk issue not a networking one. The system was able to do enough concurrent sti builds to saturate the disk iops. This prevented the node from communicating with the master and its pods were evicted.

**Comment by mffiedler** [comment]
@ofthecurerh: Which disk was causing problems - the thinp devicemapper disk?  In my tests, gp2 volumes used for devicemapper very quickly hit the IOPS cliff when running lots of builds - I had to use IOPS provisioned io1 disks for thinp to be able to test builds for any period of time.

**Comment by ofthecurerh** [comment]
@mffiedler yeah this is on the thinp disk. My assumption was that I would have to use a faster disk, but I'm not sure if its reasonable for the user to know this.

**Comment by timothysc** [comment]
Anti-affinity should decrease the frequency.   However, we still have a problem around local disk usage and QoS.  We have no mechanism by which to limit IOPs that has been vetted.  Many moons ago when I tried using cgroup iop limits it was fraught with issues, but that was a long time ago...

**Comment by derekwaynecarr** [comment]
In the future, we would like to use `blkio` , but we do not have a design in mind for how to achieve this yet.  The initial use case was around logs, but yes, builds hit same issues.

**Comment by timothysc** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/27000
