### ISSUE TITLE
Running `oc status` with no projects shouldn't return error

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#8899]
When running `oc status` without any project created, I get back:

```
Error from server: User "test" cannot get projects in project "default"
```

but instead we should return none-error message similar(or the same) the the one from `oc login` when no projects are created:

```
You don't have any projects. You can try to create a new project, by running

    $ oc new-project <projectname>

```

@fabianofranz @jwforres @spadgett thoughts ?

**Comment by jwforres** [comment]
cc @deads2k

**Comment by fabianofranz** [comment]
I think this applies to pretty much every command - if you try to for example `oc get pods` without any project, it will fallback to the `default` namespace.

**Comment by juanvallejo** [comment]
This was fixed (at least for `oc status` [here](https://github.com/openshift/origin/pull/12328) and [here](https://github.com/openshift/origin/pull/12668))
