### ISSUE TITLE
oci runtime error: exec failed:

### ISSUE THREAD

**Issue by bkmagnetron** [openshift/origin#8901]
I'm trying to install all in one OpenShift Origin Server, initially I had issue with [docker registry](https://github.com/openshift/origin/issues/8857) but I solved it later. Now I'm trying to deploy [hello-openshift](https://github.com/openshift/origin/tree/master/examples/hello-openshift) app. 
Following is the error that I'm getting in the terminal of hello-openshift's container:
```
rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"/bin/sh\": s
tat /bin/sh: no such file or directory"Error executing command in container: Err
or executing in Docker Container: 126                                           
disconnected   
```
##### Version
CentOS 7
Docker version 1.11.1, build 5604cbe
OpenShift Origin v1.2.0-rc2

##### Steps To Reproduce
Download [link](https://github.com/openshift/origin/releases/download/v1.2.0-rc2/openshift-origin-server-v1.2.0-rc2-642f0af-linux-64bit.tar.gz)
```
# openshift start &> openshift.log &
# sudo chmod a+rwX openshift.local.config/master/admin.kubeconfig
# export CURL_CA_BUNDLE=`pwd`/openshift.local.config/master/ca.crt
# sudo chmod a+rwX openshift.local.config/master/admin.kubeconfig
$ oadm registry -n default --config=openshift.local.config/master/admin.kubeconfig
```

```
$ oc create -f examples/hello-openshift/hello-pod.json
$ oc get pod hello-openshift -o yaml |grep podIP
  podIP: 172.17.0.2
# docker exec -it [container-id] bash
rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"bash\": executable file not found in $PATH"
```

**Comment by bkmagnetron** [comment]
Seems like the container really don't have the file that I'm looking for.

**Comment by gunsluo** [comment]
i has same problem.

**Comment by jkirkby91** [comment]
Have you got bash in your $PATH?

**Comment by suhaschikkanna** [comment]
Seems like you do not have bash shell. Trying the following should log you inside the container but remember if you have any bash specific shell script it will not be executed, as far as I know. 

"docker exec -it [container-id] sh"
