### ISSUE TITLE
consistent build extended test  failure

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#8903]
@bparees FYI

The extended test "starting a build using CLI override environment should allow to change build log level"  [located here](https://github.com/openshift/origin/blob/master/test/extended/builds/start.go#L75-L87) started to consistently fail between [job 162](https://ci.openshift.redhat.com/jenkins/job/origin_extended_build_tests/162/)  and [job 163](https://ci.openshift.redhat.com/jenkins/job/origin_extended_build_tests/163/).

I'm having a little trouble figuring out what commit levels those two jobs ran against, but just looking at day of sort of timings, its possible that https://github.com/openshift/origin/pull/8786 may have had something to do with this.

**Comment by bparees** [comment]
yeah it's almost certainly due to that PR.  TC probably needs to be updated.

**Comment by gabemontero** [comment]
@smarterclayton you made s2i changes in this area as well, correct?

I'm still seeing this extended test fail with the changes from https://github.com/openshift/origin/issues/8924
and suspect it is because we need the s2i changes as well.

I have pinged @bparees on IRC about the s2i bump.

**Comment by gabemontero** [comment]
For reference, [the failure](https://ci.openshift.redhat.com/jenkins/job/origin_extended_build_tests/210/console)

And I just confirmed with @bparees that the last s2i bump in origin was 5/14, but @smarterclayton change in https://github.com/openshift/source-to-image/commit/a12e1149de8da5e9f91c2cd9713b70732c68aeeb dropped on 5/18.

Leaving this open to track the next s2i bump.
