### ISSUE TITLE
Infinite loop when deleting rc

### ISSUE THREAD

**Issue by kwoodson** [openshift/origin#8909]
I am attempting to clean up a project's replication controllers.  I ran oc delete rc/heapster and the command never returns.

I ran loglevel=8 on the same command and it appears that the api queries for the rc and continues to do so forever.
I0517 18:25:50.120123   59602 round_trippers.go:264] GET https://internal.api.opstest.openshift.com/api/v1/namespaces/openshift-infra/replicationcontrollers/heapster
I0517 18:25:50.120159   59602 round_trippers.go:271] Request Headers:
I0517 18:25:50.120183   59602 round_trippers.go:274]     Accept: application/json, */*
I0517 18:25:50.120191   59602 round_trippers.go:274]     User-Agent: oc/v1.2.0 (linux/amd64) kubernetes/6c60128
I0517 18:25:50.123749   59602 round_trippers.go:289] Response Status: 200 OK in 3 milliseconds
I0517 18:25:50.123766   59602 round_trippers.go:292] Response Headers:
I0517 18:25:50.123771   59602 round_trippers.go:295]     Cache-Control: no-store
I0517 18:25:50.123775   59602 round_trippers.go:295]     Content-Type: application/json
I0517 18:25:50.123779   59602 round_trippers.go:295]     Date: Tue, 17 May 2016 18:25:50 GMT
I0517 18:25:50.123822   59602 request.go:870] Response Body:  <redacted>
I0517 18:25:51.120139   59602 round_trippers.go:264] GET https://internal.api.opstest.openshift.com/api/v1/namespaces/openshift-infra/replicationcontrollers/heapster
I0517 18:25:51.120178   59602 round_trippers.go:271] Request Headers:
I0517 18:25:51.120200   59602 round_trippers.go:274]     Accept: application/json, */*
I0517 18:25:51.120208   59602 round_trippers.go:274]     User-Agent: oc/v1.2.0 (linux/amd64) kubernetes/6c60128
I0517 18:25:51.123893   59602 round_trippers.go:289] Response Status: 200 OK in 3 milliseconds
I0517 18:25:51.123910   59602 round_trippers.go:292] Response Headers:
I0517 18:25:51.123915   59602 round_trippers.go:295]     Date: Tue, 17 May 2016 18:25:51 GMT
I0517 18:25:51.123919   59602 round_trippers.go:295]     Cache-Control: no-store
I0517 18:25:51.123923   59602 round_trippers.go:295]     Content-Type: application/json
I0517 18:25:51.123966   59602 request.go:870] Response Body: <redacted>
I0517 18:25:52.120212   59602 round_trippers.go:271] Request Headers:
I0517 18:25:52.120219   59602 round_trippers.go:274]     Accept: application/json, */*
I0517 18:25:52.120226   59602 round_trippers.go:274]     User-Agent: oc/v1.2.0 (linux/amd64) kubernetes/6c60128
I0517 18:25:52.123621   59602 round_trippers.go:289] Response Status: 200 OK in 3 milliseconds
I0517 18:25:52.123642   59602 round_trippers.go:292] Response Headers:
I0517 18:25:52.123647   59602 round_trippers.go:295]     Cache-Control: no-store
I0517 18:25:52.123651   59602 round_trippers.go:295]     Content-Type: application/json
I0517 18:25:52.123655   59602 round_trippers.go:295]     Date: Tue, 17 May 2016 18:25:52 GMT
I0517 18:25:52.123720   59602 request.go:870] Response Body:  <redacted>
I0517 18:25:53.120131   59602 round_trippers.go:264] GET https://internal.api.opstest.openshift.com/api/v1/namespaces/openshift-infra/replicationcontrollers/heapster
I0517 18:25:53.120169   59602 round_trippers.go:271] Request Headers:
I0517 18:25:53.120202   59602 round_trippers.go:274]     Accept: application/json, */*
I0517 18:25:53.120211   59602 round_trippers.go:274]     User-Agent: oc/v1.2.0 (linux/amd64) kubernetes/6c60128
I0517 18:25:53.124026   59602 round_trippers.go:289] Response Status: 200 OK in 3 milliseconds
I0517 18:25:53.124060   59602 round_trippers.go:292] Response Headers:
I0517 18:25:53.124070   59602 round_trippers.go:295]     Cache-Control: no-store
I0517 18:25:53.124080   59602 round_trippers.go:295]     Content-Type: application/json
I0517 18:25:53.124088   59602 round_trippers.go:295]     Date: Tue, 17 May 2016 18:25:53 GMT
I0517 18:25:53.124170   59602 request.go:870] Response Body: <redacted>
I0517 18:25:54.120110   59602 round_trippers.go:264] GET https://internal.api.opstest.openshift.com/api/v1/namespaces/openshift-infra/replicationcontrollers/heapster
I0517 18:25:54.120148   59602 round_trippers.go:271] Request Headers:
I0517 18:25:54.120156   59602 round_trippers.go:274]     Accept: application/json, */*
I0517 18:25:54.120163   59602 round_trippers.go:274]     User-Agent: oc/v1.2.0 (linux/amd64) kubernetes/6c60128
I0517 18:25:54.123765   59602 round_trippers.go:289] Response Status: 200 OK in 3 milliseconds
I0517 18:25:54.123782   59602 round_trippers.go:292] Response Headers:
I0517 18:25:54.123787   59602 round_trippers.go:295]     Cache-Control: no-store
I0517 18:25:54.123791   59602 round_trippers.go:295]     Content-Type: application/json
I0517 18:25:54.123795   59602 round_trippers.go:295]     Date: Tue, 17 May 2016 18:25:54 GMT
I0517 18:25:54.123846   59602 request.go:870] Response Body:  <redacted>
##### Version
oc version
oc v3.2.0.41
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
I run a simple reset script that seems to work to clean out a project:
oc --config=$kube delete service --all -nopenshift-infra && \
oc --config=$kube delete dc --all -nopenshift-infra && \
oc --config=$kube delete pods --all -nopenshift-infra && \
oc --config=$kube delete pvc --all -nopenshift-infra && \
oc --config=$kube delete templates --all -nopenshift-infra && \
oc --config=$kube delete oauthclients --all -nopenshift-infra && \
oc --config=$kube delete routes --all -nopenshift-infra && \
oc --config=$kube delete imagestreams --all -nopenshift-infra
oc --config=$kube delete secrets --all -nopenshift-infra
oc --config=$kube delete replicationcontrollers --all -nopenshift-infra

##### Current Result
The oc delete command runs forever.
##### Expected Result
I would expect the command to terminate and remove the desired rc.

**Comment by kwoodson** [comment]
I noticed that there were 2-3 projects that were in a terminating state.  I restarted the atomic-openshift-master-controllers and atomic-openshift-master-api and then this problem went away.

**Comment by deads2k** [comment]
@kwoodson the delete command first attempts to scale down the RC and then polls the RC to see when it's status indicates that it has zero pods remaining.  It never finishing suggests that the RC wasn't scaling down.

If you see this again can you watch your pods and see what they're doing?  An `oc describe rc/heapster` may be instructive too, since it will show us events from the controller.
