### ISSUE TITLE
how can use private network with openshift 

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#8916]
Hi,
I have some question for create a private network.
we use openshift as a dev/test environment，some times we need to local test and adjustment with openshift environment.

This means that the local network to access to the address of the pod(only use pod ip and port,such as a web service that  not 80 and 443 and service ip.)
route can be use in our environment，but now is failure.
```
windows
route add  10.1.3.0 mask 255.255.255.0  192.168.2.1
route add  10.1.4.0 mask 255.255.255.0  192.168.2.2

linux
route add -net 10.1.3.0 netmask 255.255.255.0 gw 192.168.2.1
route add -net 10.1.4.0 netmask 255.255.255.0 gw 192.168.2.2
```
now we can test in some web-service with openshift,how can we use a  private network with openshift in windows、mac and linux？thanks.

by the way,I also use a openstack to build a node with my physical machine，and all physical machine can be access to each other,but the node(openstack vm,use a 10.40.0.x ip)  can't access to any nodes.

**Comment by knobunc** [comment]
Normally there is no outside access to the openshift SDN network.  You should set up routes or use service nodeports to get traffic in to the services you are interested in.

**Comment by wenskys** [comment]
thanks for your answer.
Sometimes developers to access the site,route and service nodeports can meet the needs of most.
some opensouce project such as dubbo,they record the ip of the pod and feedback to development，so we unable to debug before updating to openshift .
if we need this,in addition to the `route add`, there are other ways to implement it?
thanks again.

**Comment by knobunc** [comment]
Allowing direct external access to the pod or service network isn't officially supported.  But if you really want to pursue it, it is technically possible, and the approach you took above is certainly the right direction.  There are two big issues, one is that the firewall will block the traffic by default.  So you will have to adjust the rules to allow external traffic to talk to the internal IPs.  The other problem is that if you have multiple nodes, things will only work for pods on the gateway node.  If you have more than one node, the traffic into the pod may follow one path and the return traffic may follow a different one.

If you want to investigate this further, I think you need to need to run tcpdump on the gateway to see where the traffic goes.

**Comment by wenskys** [comment]
I think we can put the debugging in openshift such as agile development, although will also increase the burden of development engineer.
Thank you very much for your advice, I will further from a security perspective with you advice.

**Comment by knobunc** [comment]
You should only need to debug this once.  It's not something that all developers will need to do.
