### ISSUE TITLE
Can't cancel Jenkins strategy build

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8931]
Nothing appears to happen when I cancel a running Jenkins strategy build from the web console. The build keeps running. (To cancel the build, the web console makes a PUT request on the build with status `"cancelled": true`)

/cc @bparees @jimmidyson @jwforres

**Comment by bparees** [comment]
I think this is an issue w/ the sync plugin, can you open it there?  the sync plugin should recognize the build object was marked cancelled and do the right thing, like it does when it sees a new build object.

**Comment by spadgett** [comment]
Opened against the sync plugin.
