### ISSUE TITLE
Atomic registry quickstart registry new project templates not created and applied.

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/origin#8936]
In the atomic registry quickstart, the registry new project templates dont get created and applied in run.sh, with users essentially creating standard openshift projects instead of registry projects. 

The commands are (in run.sh) :

    $CMD oc create -f /etc/origin/registry/registry-newproject-template-shared.json

    $CMD oc create -f /etc/origin/registry/registry-newproject-template-unshared.json

    sed -i 's/  projectRequestTemplate:.*$/  projectRequestTemplate: "default\/registry-newproject-template-shared"/' /etc/origin/master/master-config.yaml

First off the sed command fails to set the value of projectRequestTemplate, and when value is manually set, error pops up when creating project that the template was not found.

##### Version
oc v1.3.0-alpha.0-588-g665eb4b
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Steps To Reproduce
1. sudo atomic install projectatomic/atomic-registry-quickstart [DNorIP]
2. sudo atomic run projectatomic/atomic-registry-quickstart [DNorIP]
3. Check the master config file at projectRequestTemplate
4. Manually set the value of projectRequestTemplate to 'default/registry-newproject-template-shared'
5. Restart origin container and try to create project, either through web interface or console.

##### Current Result
Expected change from sed command not present, so user essentially creating standard openshift project. When value manually set, it says template not found.

##### Expected Result
User should be creating projects based on the registry-newproject-template-shared template.

**Comment by danmcp** [comment]
@aweiteka FYI

**Comment by mohammedzee1000** [comment]
Also, i exec'ed into the origin container, copied over the template json and created the template there. After that i noticed that the project was getting created but the requestor was not the admin by default so when i tried to view the project, i got a host of errors and had to modify the policy manually to make the requesting user, the admin.

It should happen if you try to repeat the process on the existing atomic registry quickstart.

**Comment by aweiteka** [comment]
I'm not able to reproduce this issue (although there was an unrelated issue I observed yesterday). I have build a new quickstart image with these fixes #8942.

We need to do better with versioning the quickstart. Until then could you uninstall the failing deployment, pull the latest quickstart and try install/run again?

**Comment by mohammedzee1000** [comment]
Ok i will do that and get back.

**Comment by mohammedzee1000** [comment]
Its seems that your new update has fixed one part of the problem. 

However, projects created using the template dont seem to give admin writes on to project to the creator of the project by default like it happens when the template wasn't being used. He needs to explicitly be assigned admin role on the project before he can do anything in there. 

If this is not done, and the creator opens the project he created, then this is how the screen looks [like](http://pasteboard.co/13AIWKA3.png).

Also, it would be a good idea to allow the admin to setup unauthenticated/anonymous users to be able to pull from all projects on the registry (world readable projects), if he so chooses. It does'nt have to be a default, but it should be doable, maybe by a single command..

**Comment by aweiteka** [comment]
The screenshot is hitting the openshift web console. This is not the primary interface for the standalone registry deployment. Have you tried using the cockpit ui at port 443? That should set up the correct user experience for managing the registry.

**Comment by mohammedzee1000** [comment]
Hi,
  I tried hitting the port 443 interface and while it opened, it gave an error

Hit :  https://localhost:443

Redirect to : 
https://localhost.localdomain:8443/oauth/authorize?client_id=cockpit-oauth-client&response_type=token&redirect_uri=https%3A%2F%2Flocalhost%2F

Message on screen : 

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."}

**Comment by aweiteka** [comment]
@mohammedzee1000 it doesn't seem like the installer completed successfully. Are you sure you followed these[1] instructions? 

The error you're seeing is due to the oauthclient not accepting the auth redirect. The registry-console template[2] should have created the oauthclient. You should see something like this (note the "redirectURIs":

```
# oc get oauthclients
NAME                           SECRET                                                                 WWW-CHALLENGE   REDIRECT URIS
cockpit-oauth-client           user...           FALSE           https://<IPorHOSTNAME>
openshift-browser-client       4adfc386-c9e5-4e09-8303-9c4b97cd53b8                                   FALSE           https://<IPorHOSTNAME>:8443/oauth/token/display
openshift-challenging-client   cfc4b684-2c9e-4d09-ba7a-a302500e6670                                   TRUE            https://<IPorHOSTNAME>:8443/oauth/token/implicit
openshift-web-console          3eb779bf-8748-4e49-a57f-6f5c4247473f                                   FALSE           https://<IPorHOSTNAME>:8443/console/,http://localhost:9000,https://localhost:9000
# oc get oauthclient cockpit-oauth-client -o yaml
allowAnyScope: true
apiVersion: v1
kind: OAuthClient
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2016-05-19T14:02:28Z
  labels:
    createdBy: registry-console-template
  name: cockpit-oauth-client
  resourceVersion: "331"
  selfLink: /oapi/v1/oauthclients/cockpit-oauth-client
  uid: 52b0bc0b-1dca-11e6-9011-fa163e4ce37b
redirectURIs:
- https://<IPorHOSTNAME>
secret: user...
```
You could edit the oauthclient directly but it might be good to confirm the install succeeded.

[1] http://docs.projectatomic.io/registry/latest/registry_quickstart/administrators/index.html#deploy-the-registry
[2] https://github.com/openshift/origin/blob/master/examples/atomic-registry/registry-console-template.yaml#L118

**Comment by mohammedzee1000** [comment]
I setup a fresh vagrant box and tried this and it seems to have been fixed. If i find any other issue i as i continue my experimentation, I will definitely report it.

**Comment by mohammedzee1000** [comment]
I might have hit another roadblock. I am resetting it to verify this but it seems that tokens generated by openshift seem to be unable to log me in correctly using docker login 

CMD : 

$ docker login -u defaultuser -p `curl -k -L -D - -u defaultuser:root@123 -H 'X-CSRF-Token: 1'  'https://localhost:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client' 2>&1 | grep -oP "access_token=\K[^&]*"` localhost:5000

Login success

$ docker push localhost:5000/test/testbox
 
The push refers to a repository [localhost:5000/test/testbox] (len: 1)
65e4158d9625: Image push failed 
Head http://localhost:5000/v2/test/testbox/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4: no basic auth credentials
