### ISSUE TITLE
image import did not get the correct tags

### ISSUE THREAD

**Issue by kwoodson** [openshift/origin#8948]
While deploying the logging-deployer template today we noticed through some debug that the image stream tags were not getting the right version.  We saw 3.2 but not the 3.2.0 that was referenced in the deploymentconfig.

On another cluster that deployed successfully with the same automation we saw the imagestreamtags for 3.2.0.

There must be some discrepancy between how import-image works.

##### Version
oc v3.2.0.44
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. Follow the logging deployment information here:
https://docs.openshift.com/enterprise/3.2/install_config/aggregate_logging.html

This is somewhat reproduce-able.  On some clusters this deployed without any problems and on the recent cluster it did not deploy correctly.  

##### Current Result
We should see the following imagestreamtags:
logging-fluentd   registry.access.redhat.com/openshift3/logging-fluentd   latest,v3.2   16 minutes ago

##### Expected Result
Notice the image stream tags: 3.2 and 3.2.0.
logging-fluentd         registry.access.redhat.com/openshift3/logging-fluentd         3.1.1,3.1.1-10,3.2,3.2.0 

##### Additional Information
The work around for this was to use image import to pull the exact images that the deployment configs were referencing:
oca import-image logging-auth-proxy:3.2.0 -nlogging
oca import-image logging-elasticsearch:3.2.0 -nlogging
oca import-image logging-fluentd:3.2.0 -nlogging
oca import-image logging-kibana:3.2.0 -nlogging

**Comment by sosiouxme** [comment]
This is related to https://github.com/openshift/origin/issues/8951 and https://github.com/openshift/origin/issues/8952 which I see as the origin-related issues to be solved. I'll take this as an issue for documenting how to work around the limitations.

**Comment by sosiouxme** [comment]
I'm actually going to convert this into an enterprise bug https://bugzilla.redhat.com/show_bug.cgi?id=1338965

@kwoodson Note that the following does what you want for now, but won't always:

    oca import-image logging-auth-proxy:3.2.0

This actually imports "latest" as if it were tagged "3.2.0" - which currently it is, but it won't be forever. The more correct workaround is noted in the bug.
