### ISSUE TITLE
oc import-image --all doesn't import all

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#8952]
If you ask for --all tags, you kind of expect to get all of them, not some random subset. If there's some performance reason for limiting them, then there should be an alternative flag that does what the user expects like --recent.

##### Version

```
$ oc version
oc v1.3.0-alpha.0-510-gb7275b5
kubernetes v1.3.0-alpha.1-331-g0522e63
```

##### Steps To Reproduce

1. `oc import-image logging-fluentd --from registry.access.redhat.com/openshift3/logging-fluentd --all --confirm`

##### Current Result

```
The import completed successfully.

Name:                   logging-fluentd
Created:                6 minutes ago
Labels:                 <none>
Annotations:            openshift.io/image.dockerRepositoryCheck=2016-05-19T03:31:45Z
Docker Pull Spec:       172.30.26.232:5000/logging/logging-fluentd


Tag     Spec                                                            Created                 PullSpec        Image
latest  registry.access.redhat.com/openshift3/logging-fluentd:latest    Less than a second ago  <same>          e1a07eb99c004aa2b244305171ebc3970b2e2c4a89864fb97a528ca17f69a72a
v3.2    registry.access.redhat.com/openshift3/logging-fluentd:v3.2      Less than a second ago  <same>          e1a07eb99c004aa2b244305171ebc3970b2e2c4a89864fb97a528ca17f69a72a
v3.1    registry.access.redhat.com/openshift3/logging-fluentd:v3.1      Less than a second ago  <same>          6c2cc79545d4b30b5d4f45756f1a06223ee3bfb4d2f3ba5b665d484c8dce60b1
3.2.0-8 registry.access.redhat.com/openshift3/logging-fluentd:3.2.0-8   Less than a second ago  <same>          e1a07eb99c004aa2b244305171ebc3970b2e2c4a89864fb97a528ca17f69a72a


info: The remote repository contained 10 additional tags which were not imported: 3.2.0-6, 3.1.1, 3.1.1-11, 3.1.1-10, 3.1.1-8, 3.1.1-6, 3.1.1-5, v3.1, 3.1.0-6, 3.1.0-1
```

##### Expected Result

Well, first I would expect *all* of the tags to be imported.

Second, tag `3.2.0` doesn't appear to be in the list at all, though it's definitely in the registry (is same as v3.2).

##### Additional

Could there be an annotation on imagestreams to accomplish the same thing at auto-import time?

If you have a DC trigger based on the `3.2.0` tag but only the `v3.2` tag is imported, then your DC doesn't deploy. So this has significant consequences for logging where exactly that is happening now.

**Comment by wanghaoran1988** [comment]
There is an config option in master config : maxImagesBulkImportedPerRepository, default value is 5 , maybe we can increase this number

**Comment by soltysh** [comment]
Note to myself, make sure when this is fixed to verify if insecure annotation is properly applied to all tags (see https://github.com/openshift/origin/issues/8965).
