### ISSUE TITLE
Is the Oauth Token Role used by OpenShift ?

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#8957]
I have installed and configured Openshiftv 1.3.0-alpha.0-581-gcf6465c with Keycloak 1.9.2.Final as identity provider

I can log to the openshift server with the user admin or default created within the Openshift Realm of Keycloak

```
 ./oc login https://192.168.99.100:8443 -u admin -p admin
Login successful.
You don't have any projects. You can try to create a new project, by running
$ oc new-project <projectname>

```

But the user doesn't belong to the cluster-admin role even if it has been added to keycloak realm and passed within the OpenID Token

![screenshot 2016-05-20 15 16 56](https://cloud.githubusercontent.com/assets/463790/15428926/7e7914fe-1e9e-11e6-8c52-a3e7a025a690.png)

 ```
./oc project default
error: You are not a member of project "default".
You are not a member of any projects. You can request a project to be created with the 'new-project' command.

./oc new-project default
Error from server: project "default" already exists

./oc describe clusterPolicy default
Error from server: User "admin" cannot get clusterpolicies at the cluster `scope`
```

Questions :
- Is the role passed within the OpenID Token used ?
- How can we add for a user the `cluster-admin` role as we can't connect to the platform using user 'system:admin' - error: username system:admin is invalid for basic auth ?

**Comment by liggitt** [comment]
> Is the role passed within the OpenID Token used ?

No, group and role information is not consumed from the OpenID provider, only user identity info.

> How can we add for a user the cluster-admin role as we can't connect to the platform using user 'system:admin' - error: username system:admin is invalid for basic auth ?

Use the generated system:admin credentials contained in the admin.kubeconfig file to grant cluster-admin roles to other login users:

```
oadm policy add-cluster-role-to-user cluster-admin my-login-user --config=/path/to/admin.kubeconfig
```

**Comment by liggitt** [comment]
Also, if I understand correctly, Keycloak passes roles in the access_token, not in the id_token. The access_token is supposed to be opaque to the service provider (openshift), so even once the ability to pull group info from an identity provider is added (see https://trello.com/c/8olzeZH3), that would be done from the id_token or user info claims, not the access_token.

**Comment by cmoulliard** [comment]
We will review this problem with Keycloak. Thx.
