### ISSUE TITLE
[extended.test] Eliminate Synthetic skips

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#8962]
problem:

we have some synthetic skip logic which is working in openshift but which relies on some just-in-time logic that subverts ginkgo's metadata handling.

solution: 

weve done the upstream work necessary now to avoid needing this, so lets leverage the new `k8s.io` tags and the `--ginkgoScansFilePath` option when necessary to add namespace filtering to tests.

cc @timothysc @smarterclayton @liggitt

**Comment by mfojtik** [comment]
@jayunit100 I believe this should land with a new rebase (I bumped ginkgo there).

**Comment by stevekuznetsov** [comment]
@mfojtik should this remain open?
