### ISSUE TITLE
oc import-image --all does not work

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#8969]
This came from discussion in https://github.com/openshift/origin/issues/8965. With current implementation flag `--all` when passed to `oc import-image` doesn't import all tags.

@sdodson fyi

**Comment by soltysh** [comment]
Note to myself, make sure when this is fixed to verify if insecure annotation is properly applied to all tags.

**Comment by sosiouxme** [comment]
Dupe of https://github.com/openshift/origin/issues/8952 ?

**Comment by soltysh** [comment]
Yup.
