### ISSUE TITLE
Version checking in the deployer

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8972]
Forked from https://github.com/openshift/origin/issues/8403#issuecomment-208856322
>  The common deployer logic which detects the "from" deployment and "old" deployments has a problem: it considers the latest of all completed deployments not equal to the target (router-1 in this case) to be the "from" and everything else to be "old". So if router-2 is completed before router-1-deploy is scheduled and router-1-deploy gets an opportunity to execute, router-2 is considered "from". I think version checking here will correct it.

The deployer should make sure it always deploys the latest version.

cc: @ironcladlou @mfojtik @smarterclayton

**Comment by mfojtik** [comment]
@kargakis so you want this to look similar to what "serial killer" build policy is? IOW. if there is an already deployment running and you start a new deployment, the previous "pending" deployment is automatically cancelled and will never have a chance to succeed?

**Comment by kargakis** [comment]
> @kargakis so you want this to look similar to what "serial killer" build policy is? IOW. if there is an already deployment running and you start a new deployment, the previous "pending" deployment is automatically cancelled and will never have a chance to succeed?

This already happens in the deployment config controller. The deployer logic is not checking for versions so you can end up rolling from version 2 to version 1.
