### ISSUE TITLE
Tool to generate the Openshift Master YAML Config File

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#8977]
Is it the only way that we have to generate the Openshift Master yaml config file (https://docs.openshift.com/enterprise/3.2/install_config/master_node_configuration.html#creating-new-configuration-files) or a command line tool also exist to generate it based on our parameters ?

**Comment by liggitt** [comment]
That is the only command that generates it. All the parameters supported by `openshift start [master | node]` affect the config written by `--write-config`, so you can set up some general options that way, but for detailed config, you would need to modify the config files.

The ansible installer (see https://github.com/openshift/openshift-ansible and https://docs.openshift.org/latest/install_config/install/advanced_install.html) will set up a config as part of installation, and supports more config options.

**Comment by cmoulliard** [comment]
Do you think that what is proposed is enough ? To use what you suggest, it is required to add a new tool (Ansible) within the process to setup an OpenShift platform...
The documentation to install Openshift with Ansible and Vagrant is not really elaborated. There are no instructions to setup Openshift with a Master + Node within the same VM, using Virtualbox, explaining how to setup Ansible to pass the parameters required to configure Openshift as described here (https://docs.openshift.org/latest/install_config/install/advanced_install.html)
