### ISSUE TITLE
Jenkins slave Dockerfile example fails to build

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#8980]
The example Dockerfile for Jenkins slave assumes the base image is CentOS and doesn't run on OpenShift Enterprise:
https://github.com/openshift/origin/blob/master/examples/jenkins-master/slave/Dockerfile#L6

centosplus and epel-release don't exist on rhel based images. Either two separate dockerfiles should be created for rhel and centos or Dockerfile should conditionally install appropriate packages based on the base image.

**Comment by mfojtik** [comment]
@siamaksade i'm not sure if I will get time to fix this, @bparees ?

**Comment by bparees** [comment]
this is an example and not a product feature. lowering priority.

**Comment by siamaksade** [comment]
It has rather high priority considering this example is the only documentation provided on how to use the slave pod feature on OpenShift 3.2. If this doesn't work, there is no other way for users to figure how to use this.

Official docs also send the user to this example.

**Comment by bparees** [comment]
> It has rather high priority considering this example is the only documentation provided on how to use the slave pod feature on OpenShift 3.2

it's not an OSE3.2 feature.  It's a tutorial/example.  We do not officially support or maintain the kubernetes plugin which enables launching slave pods on openshift.

**Comment by siamaksade** [comment]
Here is a modified version of the Dockerfile for RHEL which works on OpenShift Enterprise:
https://github.com/siamaksade/jenkins-s2i-example/blob/master/slave/Dockerfile

**Comment by bparees** [comment]
@gabemontero please use this issue to clean up the master-slave example.  I'd like to get rid of all the aspects of that example that deal w/ turning standard images into slave images and just make it a simple example that uses our existing maven or nodejs slave image, and mentions "if you need a different slave image, extend our slave-base image"

**Comment by gabemontero** [comment]
@bparees a couple of quick thoughts:

1) We could switch the master-slave README to some minor instructions to explain how to update the existing `OpenShift Sample` job to run on the nodejs slave by checking `Restrict where this project can be run` and then specifying the Label `nodejs`; then delete all the other content - the templates, sample jobs, etc.  I just ran through the scenario manually and it works like a charm.

2) Update the base `OpenShift Sample` job to add this restriction and just update the README for that job to highlight the slave image nuances (including the callout on how to extend slave-base image), and just nuke the entire `master-slave` subdir in the origin repo.  Updating the existing sample job would also be trivial, but perhaps having both a master only and master slave permutation is more desirable.

Thoughts?

**Comment by bparees** [comment]
I think i like (1) best, because i'd like to keep the default sample job as simple as possible (at least in part because it's used by some of our tests too, so making it depend on slave pods makes it more fragile).

But doing that means we still haven't explained to users how to create their own slave images.  Perhaps the right solution for that is to add a tutorial section to the official product documentation.  "Using slave images with jenkins" which would include a section on creating your own slave images.

So (1) + official doc about slave image usage/creation.
