### ISSUE TITLE
oc project cannot recognize invalid contexts

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#8981]
When trying to switch to a context that doesn't exist:

```
$ oc project test/10-0-2-15:8443/tes
error: invalid resource name "test/10-0-2-15:8443/tes": name may not contain "/"
```

`oc project NAME` tries to find the context from a map (kubeconfig) and if it doesn't exist there then (if `NAME` is a context and not a project name) the project client will think it is a resource name.

@fabianofranz @deads2k

**Comment by deads2k** [comment]
> the project client will think it is a resource name.

Yeah, it tries to use it as a project name.
