### ISSUE TITLE
mount.nfs: requested NFS version or transport protocol is not supported

### ISSUE THREAD

**Issue by bkmagnetron** [openshift/origin#8982]
##### Version
centos-release-7-2.1511.el7.centos.2.10.x86_64
openshift v1.2.0-rc2
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5
oc v1.2.0-rc2

##### Steps To Reproduce
Everything I did
```
$ sudo service firewalld stop
$ sudo nano /etc/sysconfig/docker
OPTIONS='--selinux-enabled --dns 10.28.27.250 --dns 10.28.27.251'
INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'
$ sudo service start docker
$ sudo openshift start &> openshift.log &

$ oc whoami show
system:admin
$ export CURL_CA_BUNDLE=`pwd`/openshift.local.config/master/ca.crt
$ sudo chmod a+rwX openshift.local.config/master/admin.kubeconfig
$ oadm registry -n default --config=openshift.local.config/master/admin.kubeconfig
$ oadm policy add-scc-to-user hostnetwork -z router
$ oadm router --service-account=router

$ sudo mkdir -p /home/data/pv0001
$ sudo mkdir -p /home/data/pv0002
$ sudo chmod -R 777 /home/data/
$ sudo nano /etc/exports
/home/data/pv0001 *(rw,sync)
/home/data/pv0002 *(rw,sync)
$ sudo exportfs -a
$ sudo setsebool -P virt_use_nfs 1
$ oc create -f examples/wordpress/nfs/pv-1.yaml
$ oc create -f examples/wordpress/nfs/pv-2.yaml
$ oc get pv
... STATUS Available ...

$ oc whoami show
admin
$ oc create -f examples/wordpress/pvc-wp.yaml 
$ oc create -f examples/wordpress/pvc-mysql.yaml
$ oc get pvc
... STATUS Bound ...
$ oc create -f examples/wordpress/pod-mysql.yaml
$ oc create -f examples/wordpress/service-mysql.yaml 
$ oc create -f examples/wordpress/pod-wordpress.yaml 
$ oc create -f examples/wordpress/service-wp.yaml 
$ oc get svc
NAME       CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
database   172.30.243.252   <none>        5434/TCP   5h
frontend   172.30.81.142    <none>        5432/TCP   5h
```
##### Current Result
Events log
```
5:51:36 PM	wordpress	Pod	Warning	Failed sync 	Error syncing pod, skipping: Mount failed: exit status 32 Mounting arguments: 10.28.27.36:/home/data/pv0001 /home/balas/_my/openshift-origin-server-v1.2.0-rc2/openshift.local.volumes/pods/f6c22f3a-20da-11e6-b729-408d5c676116/volumes/kubernetes.io~nfs/pv0001 nfs [] Output: mount.nfs: requested NFS version or transport protocol is not supported
194 times in the last 42 minutes
5:51:24 PM	mysql	Pod	Warning	Failed mount 	Unable to mount volumes for pod "mysql_wordpress(e8923d2d-20da-11e6-b729-408d5c676116)": Mount failed: exit status 32 Mounting arguments: 10.28.27.36:/home/data/pv0002 /home/balas/_my/openshift-origin-server-v1.2.0-rc2/openshift.local.volumes/pods/e8923d2d-20da-11e6-b729-408d5c676116/volumes/kubernetes.io~nfs/pv0002 nfs [] Output: mount.nfs: requested NFS version or transport protocol is not supported
```

**Comment by bkmagnetron** [comment]
I'm still having this issue even after installing fedora 23. Just a note that I have deployed origin/examples/sample-app and origin/examples/django-ex with python34 both are working fine.
Following image show the all the error logs shown in cockpit:
![cockpit](https://cloud.githubusercontent.com/assets/4893873/15601884/f86746e8-23bf-11e6-8eb4-4fc218f097ad.png)

**Comment by bkmagnetron** [comment]
This issue exists in 

openshift v1.3.0-alpha.1
kubernetes v1.3.0-alpha.1-331-g0522e63
etcd 2.3.0

**Comment by bkmagnetron** [comment]
This error is because of not starting nfs service
```systemctl start nfs```
Solved this issue but leads to a different one, will be creating a separate one for that.

**Comment by praveenkumar** [comment]
@bkmagnetron If you try lastest ADB ( https://github.com/projectatomic/adb-atomic-developer-bundle#how-do-i-install-and-run-the-adb ) then persistent volume are available by default.

**Comment by bkmagnetron** [comment]
@praveenkumar whats the difference between OpenShift Origin All-in-one-virtual-machine and [adb centos-openshift-setup](https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/centos/centos-openshift-setup).

**Comment by praveenkumar** [comment]
@bkmagnetron Not much difference, using ADB you can run any version of openshift just need to specify image tag in Vagrant file. With all in one everything is cached so box size will be in GBs

**Comment by chadfurman** [comment]
I get this with VirtualBox / Vagrant.  Basically, make sure nfs-kernel-server is installed, make sure it's enabled / started (`systemctl enable nfsserver && systemctl start nfsserver && systemctl status nfsserver`)

If you get errors like "Duplicate entry in exportfs" or whatever, check your `/etc/exports` folder
