### ISSUE TITLE
Add an option to the oc client to generate the master-config file

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#8996]
The oc client doesn't provide an option to generate the Master Config YAML file. So, I suggest to enhance the existing tool to generate such config 

```
- Generate the default master config file 

oc create-master-config 

- Generate the Master Config file according to a specific OpenShift Version

oc create-master-config -v openshift_version

- Pass parameters to override/change using a YAML file

oc create-master-config -c config_params.yaml

Remark : The config file allows to override keys as described here: https://docs.openshift.com/enterprise/3.2/install_config/install/advanced_install.html#configuring-ansible) 

```

**Comment by liggitt** [comment]
> - Generate the default master config file 
> oc create-master-config 

It's far more than just the config file, it's all the supporting files as well. To do that, you need all the options passed to `openshift start master`. I don't think it's a great idea to maintain and test all of those in two places.

> - Generate the Master Config file according to a specific OpenShift Version
> oc create-master-config -v openshift_version

Same issue.

> - Pass parameters to override/change using a YAML file
> oc create-master-config -c config_params.yaml
> Remark : The config file allows to override keys as described here: https://docs.openshift.com/enterprise/3.2/install_config/install/advanced_install.html#configuring-ansible) 

I don't think we should try to maintain config-modifying tools in multiple places.

I could maybe see a CLI utility that modifies a stanza of the master config file based on a patch specified on the command line or in a file, but that is a much more targeted change, and doesn't seem to be what this is asking for

**Comment by liggitt** [comment]
other similar requests:

https://github.com/openshift/origin/issues/4733
https://github.com/openshift/origin/pull/4760

**Comment by cmoulliard** [comment]
The solution proposed relies on Ansible and has nothing todo with the oc client. So, I don't see why you claim that we have to maintain tools in multiple places. Are you sure that many end users will use ansible. That will add an additional layer top of the tools already required to setup Openshift using Vagrant

**Comment by liggitt** [comment]
> I don't see why you claim that we have to maintain tools in multiple places

Every option added to the ansible config file would require changing code in two places to support it.

**Comment by smarterclayton** [comment]
Closing due to age.
