### ISSUE TITLE
Regression: oc policy add-role-to-group registry-viewer now says "Attempt to grant extra privileges"

### ISSUE THREAD

**Issue by stefwalter** [openshift/origin#9000]
A user who created and is admin of a project can no longer "add-role-to-group" on that project. This functionality is/was used by the Atomic Registry.

##### Version

```
openshift v1.3.0-alpha.0-613-g3c29434
kubernetes v1.3.0-alpha.1-331-g0522e63
etcd 2.3.0
```

##### Steps To Reproduce
```
$ printf "scruffy\r\nscruffy\r\n" | oc login
...
$ oc new-project zerog
...
$ oc policy add-role-to-group registry-viewer system:authenticated -n zerog
```

##### Current Result

```
error: You must be logged in to the server (attempt to grant extra privileges: [
... massive output ...
```

##### Expected Result

Success. No output.

##### Additional Information

Used to work with the following openshift version:

```
openshift v1.1.6-48-g561e4fa
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5
```

**Comment by liggitt** [comment]
What role does that user have and what role are they trying to grant? The role being granted has more permissions than the role they have, apparently

**Comment by stefwalter** [comment]
![screenshot from 2016-05-24 15-48-37](https://cloud.githubusercontent.com/assets/795070/15506227/1fb9649c-21c7-11e6-99b1-d81a87c0c2da.png)

**Comment by stefwalter** [comment]
@aweiteka FYI

**Comment by stefwalter** [comment]
The logged in user has this role:

```
$ oc get rolebindings admin --output=json
{
    "kind": "RoleBinding",
    "apiVersion": "v1",
    "metadata": {
        "name": "admin",
        "namespace": "zerog",
        "selfLink": "/oapi/v1/namespaces/zerog/rolebindings/admin",
        "uid": "783abb47-21b6-11e6-8c1a-5254009e00f1",
        "resourceVersion": "1154",
        "creationTimestamp": "2016-05-24T13:50:26Z"
    },
    "userNames": [
        "scruffy"
    ],
    "groupNames": null,
    "subjects": [
        {
            "kind": "User",
            "name": "scruffy"
        }
    ],
    "roleRef": {
        "name": "admin"
    }
}
```

The role this user is trying to grant is the stock 'registry-viewer' role that comes with openshift since c205eac60bf392753e2846d59e7c65deba2cd782

**Comment by liggitt** [comment]
@deads2k is this related to the empty scopes array in the userinfo?

**Comment by deads2k** [comment]
> @deads2k is this related to the empty scopes array in the userinfo?

I doubt it.  My money is on empty group array versus `""`.

**Comment by deads2k** [comment]
Yep, confirmed.  I thought we covered that in defaulting, but we may have done it during authorization itself to keep the object accurate.  In fact, that sounds exactly like something I'd do: don't lose the data on round trip.
