### ISSUE TITLE
oc delete job does not work

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#9019]
I can't remove a job using `oc`:

```
$ oc delete job/pi
Error from server: jobs.extensions "pi" not found
```

I've also tried:
```
$ oc delete job.batch/pi
Error from server: jobs.extensions "pi" not found
```

**Comment by soltysh** [comment]
I might want to wait with this until after the rebase, especially that I'm dealing with similar problems over there. It might get fixed there. 
Other than that, we need integration tests that will verify this is working as expected!

**Comment by soltysh** [comment]
Not a bug, but user mistake :cry:

**Comment by kargakis** [comment]
:wine_glass:

**Comment by soltysh** [comment]
@kargakis yeah too much I guess :wink:
