### ISSUE TITLE
STI build fails mysteriously

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#902]
```
$ osc build-logs 587a9b69-acf2-11e4-9c33-080027ce4245
2015-02-05T04:49:27.320631348Z Cloning into '/tmp/sti947872734/upload/src'...
2015-02-05T04:49:32.802087241Z 2015/02/05 04:49:32 Build error: unexpected end of JSON input
```

```
  apiVersion: v1beta1
  kind: Build
  metadata:
    creationTimestamp: 2015-02-04T23:49:19-05:00
    labels:
      buildconfig: sinatra-app-example
    name: 587a9b69-acf2-11e4-9c33-080027ce4245
    namespace: default
    resourceVersion: "76"
    selfLink: /osapi/v1beta1/builds/587a9b69-acf2-11e4-9c33-080027ce4245?namespace=default
    uid: 587a9c1d-acf2-11e4-9c33-080027ce4245
  parameters:
    output:
      to:
        kind: ImageRepository
        name: sinatra-app-example
    source:
      git:
        uri: git://github.com/mfojtik/sinatra-app-example
      type: Git
    strategy:
      stiStrategy:
        builderImage: openshift/ruby-20-centos:latest
        image: openshift/ruby-20-centos:latest
      type: STI
  podName: build-587a9b69-acf2-11e4-9c33-080027ce4245
  status: Failed
```

**Comment by smarterclayton** [comment]
Need a better error than that.

**Comment by smarterclayton** [comment]
Tentative for 0.3.0

**Comment by csrwng** [comment]
Looking into it

**Comment by csrwng** [comment]
So far I haven't been able to reproduce this. There's only 2 places in STI where we handle JSON and that's in restoring a config and posting a callback. Neither of which are likely in this case. The other place where this could be happening is in making a call out to Docker and Docker is returning this error.

**Comment by smarterclayton** [comment]
So when you try with the posted build config it doesn't work?  Let me refresh my sti-builder

----- Original Message -----

**Comment by csrwng** [comment]
Yes I tried building that buildConfig and it succeeds for me

**Comment by smarterclayton** [comment]
`osc new-app openshift/ruby-20-centos~git@github.com/mfojtik/sinatra-app-example`

**Comment by csrwng** [comment]
So the build worked for me both in boot2docker and a newly created Vagrant image (from the origin repository's Vagrantfile). In the Vagrant image, I ran ```yum update``` and set SELinux to enforcing.

**Comment by csrwng** [comment]
@smarterclayton - PR is here: https://github.com/openshift/origin/pull/938
