### ISSUE TITLE
Issue with version of openshift docker?

### ISSUE THREAD

**Issue by jameswilkins** [openshift/origin#9020]
Hi,

We're using the version of docker from the RPM Repos @ https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/epel-7-x86_64/ alongside Openshift.

Version: 1.9.1-25.1.origin.el7.centos

When using this version of docker, we are unable to access private repositories on dockerhub.

If we remove out this version, and replace with a newer version of docker (either from CentOS Extras and/or directly from Docker) - authentication works as expected.

Do we need to stay pinned to the version of Docker in the openshift RPM repo (on the above repo) or can we up to a later version of Docker to resolve this issue (1.10?)

##### Version
docker-selinux-1.9.1-25.1.origin.el7.centos.x86_64
docker-1.9.1-25.1.origin.el7.centos.x86_64
docker-forward-journald-1.9.1-25.1.origin.el7.centos.x86_64

oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1.  docker login (authenticate to dockerhub)
2.  docker pull image (marked as private)

##### Current Result
Error: image foo/bar:latest not found
##### Expected Result
Image pulls

**Comment by miminar** [comment]
@jameswilkins due to inactivity, I'm closing this now. Feel free to re-open if the problem persist.
