### ISSUE TITLE
Wrong Content-Type for config.js

### ISSUE THREAD

**Issue by ALRubinger** [openshift/origin#9033]
Got error during testing from HtmlUnit:

```
WARNING: Expected content type of 'application/javascript' or 'application/ecmascript' for remotely loaded JavaScript element at 'https://10.1.2.2:8443/console/project/jboss-eap-quickstarts/overview/config.js', but got 'text/html'.
```

##### Version
`latest` from Docker Hub (`upstream/master`)

##### Steps To Reproduce
```
$ curl --head https://10.1.2.2:8443/console/project/jboss-eap-quickstarts/overview/config.js --insecure
```

Note your host and project name will vary.

##### Current Result
```
HTTP/1.1 200 OK
Cache-Control: public, max-age=0, must-revalidate
Etag: W/"940dcf2_"
Vary: Accept-Encoding
Date: Wed, 25 May 2016 21:44:31 GMT
Content-Length: 1862
Content-Type: text/html; charset=utf-8
```

##### Expected Result
```
...
Content-Type: application/javascript; charset=utf-8
```

##### Additional Information

Blocking frontend testing of the Catapult application

**Comment by liggitt** [comment]
I think the tool is not using the base element correctly. It should be set to the root context where the config.js is actually served from

**Comment by ALRubinger** [comment]
@liggitt Thanks, but then how do we explain the Content-Type shown in the response headers by curl?

**Comment by ALRubinger** [comment]
Did some more digging.  Seems the actual `config.js` is located at `https://10.1.2.2:8443/console/config.js` and a request to `https://10.1.2.2:8443/console/project/default/overview/config.js` will result in:

```
$ curl --insecure --head https://10.1.2.2:8443/console/project/default/overview/config.js
HTTP/1.1 200 OK
Cache-Control: public, max-age=0, must-revalidate
Etag: W/"940dcf2_"
Vary: Accept-Encoding
Date: Thu, 26 May 2016 04:52:08 GMT
Content-Length: 1862
Content-Type: text/html; charset=utf-8
```
Eventually this redirects to: `https://10.1.2.2:8443/console/`, though I can't yet tell through what mechanism (it's not a 303, as shown above).  What I'm wondering is if HtmlUnit is honoring the `<base href="/console/">` line: why is it even trying to request `config.js` from `console/project/default/overview/` in the first place?

Going to keep at it from my end; OpenShift team, please don't spend cycles on this until I can get some better info.

**Comment by ALRubinger** [comment]
Closing.  This is an issue with the base URL not being honored by HtmlUnit in older versions; was fixed in:

  https://sourceforge.net/p/htmlunit/mailman/message/34373875/

The `curl` calls were additionally misleading because they were not returning 404s (script not found as requested) or even 303s (as it later issued some redirect through another form?).

**Comment by liggitt** [comment]
Any unrecognized URL returns the main index.html file. This is needed to allow HTML5 mode in the web console angular app to work correctly

**Comment by ALRubinger** [comment]
Sure, but does it have to return a 200 status as if nothing's wrong with the original request? :)

TBH I'm not too versed in Angular but that's super weird behaviour, no?

**Comment by liggitt** [comment]
Yeah, it does :-/

The server is just sending static files. The routing logic is in the JavaScript, so any URL under the web console context root could be valid (as far as the server knows), so it either returns the actual static file at that location or the index.html
