### ISSUE TITLE
openshift  should use docker config file when do build

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#9036]
when doing build with image private registry, we should mount the ~/.docker/config.json as a volume to enable pull the builder image, currently when the infra image like sti-builder and deployer can work well with private image after we docker login on the minion, which mean kubelet will use this to pull the image , for openshift build, we should also support this I think.

**Comment by bparees** [comment]
sorory @wanghaoran1988 i'm struggling to understand your scenario here.

You want the node hosts' ~/.docker/config.json mounted as a volume into build pods so that user builds (s2i, docker) have access to the hosts' ~/.docker/config.json file?

**Comment by wanghaoran1988** [comment]
@bparees yes, we should mounted this as a image pull secret to pull the private image , so we will have a same behavior as the openshift node does: after docker login on the host , we can pull all the image no matter it's infra image or builder image.

**Comment by bparees** [comment]
We're not going to expose the node host filesystem to builds, that would be a significant security risk.  The right way to do this is to create an explicit secret in your project with the dockercfg and use it.

**Comment by bparees** [comment]
after discussion on irc apparently this is in fact something the kubelet supports (accessing the dockercfg of the user running the kubelet so it would make sense for build pull logic to mirror that behavior.
http://kubernetes.io/docs/user-guide/images/#configuring-nodes-to-authenticate-to-a-private-repository

**Comment by wanghaoran1988** [comment]
@bparees Do you have any plan about this issue ?

**Comment by bparees** [comment]
@wanghaoran1988 it's on our backlog, we acknowledge we want to do something about it, but we don't have an immediate plan to fix it, no.

**Comment by bparees** [comment]
trello'd: https://trello.com/c/uZO1CAOS
