### ISSUE TITLE
Image-stream scheduler problem

### ISSUE THREAD

**Issue by Neonell** [openshift/origin#9037]
I saw a little problem with image-stream and the import-policy. When we update or create an image-stream with the import-policy set to scheduled: true the pull request to the external docker repository are never made until a second image-stream object pointing on the same repository is created.
##### Version

oc v1.3.0-alpha.0-674-gc12d753
kubernetes v1.3.0-alpha.1-331-g0522e63
##### Steps To Reproduce
1. oc new-app docker.io/repo/myapp -o json > myapp.json
2. edit myapp.json add into import-policy section: scheduled: true
3. oc create -f myapp.json
##### Current Result

The image-stream download the latest image in the docker repository. oc describe is show that the 
image-stream is scheduled for periodical import. But when a new image is uploaded in the docker repository the image-stream is never updated.
##### Expected Result

The image-stream is automatically updated when a new image version is uploaded in the docker repository.
##### Additional Information

Then I created a new image-stream based on the same image with: 
oc import-image myImageStream --from=docker.io/repo/myapp --confirm

Now both of my image-stream are automatically updated when a new image version is uploaded in the docker repository. If I delete the second one (myImageStream) the first one will still work correctly.

**Comment by propyless** [comment]
Hello,

Is there any work being done for this issue? I am experiencing the same as describe above by OP.

**Comment by soltysh** [comment]
Sorry, I haven't got a time to get to this one, yet. But help is more than welcome :)

**Comment by propyless** [comment]
So,

I actually was able to resolve this issue on my own.

By default at least in openshift enterprise version you need to set the imagepolicyconfig (documented here: https://godoc.org/github.com/openshift/origin/pkg/cmd/server/api#ImagePolicyConfig)
but not in the openshift documentation which I have not found. The default is that the period pull is **OFF**. (Which is also not documented, I'm currently writing a PR for it anyway.)

So the option to configure this is in the master config. you can configure it via ansible.
https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example#L69-L70

Once this was enabled in the master config, it pulls the docker images periodically, as expected...

**Comment by soltysh** [comment]
That will be awesome. Thank you!

**Comment by mfojtik** [comment]
The issue seems to be resolved, closing this.
