### ISSUE TITLE
Impersonnate does not work

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#9050]
I try to impersonate but I get an error.

```
[vagrant@origin ~]$ oc get nodes --as system:admin
error: failed to negotiate an api version; server supports: map[], client supports: map[v1:{} v1beta3:{} authorization.k8s.io/v1beta1:{} autoscaling/v1:{} extensions/v1beta1:{} batch/v1:{} componentconfig/v1alpha1:{} metrics/v1alpha1:{}]
```

I have built this release with all-in-one process, so something might be wrong/required with configuration. 
I have tried also with same release from release pages in github with same result, but same configuration on master server.
##### Version

[vagrant@origin ~]$ oc version
oc v1.3.0-alpha.1
kubernetes v1.3.0-alpha.1-331-g0522e63

**Comment by deads2k** [comment]
> I have built this release with all-in-one process, so something might be wrong/required with configuration. 
> I have tried also with same release from release pages in github with same result, but same configuration on master server.

I suspect that you don't have rights to impersonate `system:admin`.  Have you added yourself to `sudoer`?  Try using `--loglevel=8` to get more information.

I'll see if I can fix-up the error message from version negotiation.

**Comment by jorgemoralespou** [comment]
Seem that's the issue.

````
I0526 21:24:32.448917   13191 request.go:870] Response Body: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"dev\" cannot \"impersonate\" \"systemusers\" with name \"system:admin\" in project \"\"",
  "reason": "Forbidden",
  "details": {
    "name": "system:admin",
    "kind": "systemusers"
  },
  "code": 403
}
````

I was following instruction sin release-notes which doesn't say anything about sudoer, or event how to do that, or points to doc.

Adding to sudoers, does the trick. 
Message is no descriptive :-D

````
[vagrant@origin ~]$ oc login -u admin -p admin
[vagrant@origin ~]$ oc adm policy add-cluster-role-to-user sudoer dev
[vagrant@origin ~]$ oc login -u dev -p dev
[vagrant@origin ~]$ oc get nodes --as system:admin
NAME      STATUS    AGE
origin    Ready     5h
````

**Comment by php-coder** [comment]
@deads2k What should be fixed here? Current error message is

```console
$ oc get nodes --as system:admin
No resources found.
Error from server: User "developer" cannot "impersonate" "systemusers" with name "system:admin" in project ""
```

**Comment by jorgemoralespou** [comment]
I would say that this is fixed.

**Comment by php-coder** [comment]
Yes. The only thing that I see here is that project name is empty in the message.
