### ISSUE TITLE
what-can-i-do cli option not available

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#9051]
[vagrant@origin ~]$ oc version
oc v1.3.0-alpha.1
kubernetes v1.3.0-alpha.1-331-g0522e63

[vagrant@origin ~]$ oc policy what-can-i-do
error: unknown command "what-can-i-do"
See 'oc policy -h' for help and examples.

**Comment by kargakis** [comment]
Was renamed recently to can-i

@deads2k we should print a suggestion for people trying to run what-can-i-do

**Comment by jorgemoralespou** [comment]
And maybe also fix the release notes?

**Comment by jorgemoralespou** [comment]
**oc policy can-i --list** seems to do what is expected.

**Comment by deads2k** [comment]
> And maybe also fix the release notes?

I didn't think we ever tagged a release that published the old name?  Only people working against HEAD ever saw it, right?

**Comment by jorgemoralespou** [comment]
Release 1.3.0.alpha.1 (https://github.com/openshift/origin/releases)

Find what-can-i-do
````
add what-can-i-do endpoint #8675
````

**Comment by deads2k** [comment]
> Find what-can-i-do

Updated the pull description to show the new command name.  I didn't find a direct command name in the release notes.

**Comment by deads2k** [comment]
@juanvallejo @fabianofranz there was a limitation for suggestions that I hit in https://github.com/openshift/origin/pull/9055.  Should be fixed so we can add suggestions later.
