### ISSUE TITLE
oc scale not taking effect inmediatelly and not shown in console

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#9053]
I have done this in command line:
`````
[vagrant@origin ~]$ oc new-app kubernetes/guestbook
--> Found Docker image 4305190 (19 months old) from Docker Hub for "kubernetes/guestbook"

    * An image stream will be created as "guestbook:latest" that will track this image
    * This image will be deployed in deployment config "guestbook"
    * Port 3000/tcp will be load balanced by service "guestbook"
      * Other containers can access this service through the hostname "guestbook"
    * WARNING: Image "kubernetes/guestbook" runs as the 'root' user which may not be permitted by your cluster administrator

--> Creating resources with label app=guestbook ...
    imagestream "guestbook" created
    deploymentconfig "guestbook" created
    service "guestbook" created
--> Success
    Run 'oc status' to view your app.
````
In the UI I see this:
![image](https://cloud.githubusercontent.com/assets/78350/15604759/5a21f1fc-2402-11e6-8a41-a470f72370e0.png)

Inmediately I do a scaling:
`````
[vagrant@origin ~]$ oc scale kubernetes/guestbook --replicas=10
the server doesn't have a resource type "kubernetes"
[vagrant@origin ~]$ oc scale dc/guestbook --replicas=10
deploymentconfig "guestbook" scaled
[vagrant@origin ~]$ oc get dc
NAME        REVISION   REPLICAS   TRIGGERED BY
guestbook   1          10         config,image(guestbook:latest)
[vagrant@origin ~]$ oc get pods --no-headers | wc -l
1
````
I can see that now there¡s 10 pods requested, but still 1 pod.

**UI Does not reflect this. THIS IS THE ERROR/ISSUE**

In the UI I see this:
![image](https://cloud.githubusercontent.com/assets/78350/15604759/5a21f1fc-2402-11e6-8a41-a470f72370e0.png)

Then after 2 minutes (or so, state consolidation):
I see the console updated:
![image](https://cloud.githubusercontent.com/assets/78350/15604811/897a4670-2402-11e6-99a2-cccbfa4d227b.png)

````
[vagrant@origin ~]$ oc get pods --no-headers | wc -l
10
````

If I scale now to 20 from CLI:
`````
[vagrant@origin ~]$ oc scale dc/guestbook --replicas=20
deploymentconfig "guestbook" scaled
[vagrant@origin ~]$ oc get dc
NAME        REVISION   REPLICAS   TRIGGERED BY
guestbook   1          20         config,image(guestbook:latest)
[vagrant@origin ~]$ oc get pods --no-headers | wc -l
20
`````

I see immediate change in console.


![image](https://cloud.githubusercontent.com/assets/78350/15604674/ea5916ac-2401-11e6-9d1a-2e2801297750.png)

**Comment by jorgemoralespou** [comment]
Moved as issue in origin-web-console. https://github.com/openshift/origin-web-console/issues/45

**Comment by kargakis** [comment]
This is not a console issue. Are yoy scaling up before the deployment completes?

**Comment by jorgemoralespou** [comment]
Yes, I'm scaling before the deployment completes. But as you can see, the DC reflects the scaled value, but console does not. Maybe not sending events to console, but when I scale after deployment, console instantly sees the new value. I'd guess that the console is not watching for events until deployment has finished.
But you know better.
@spadgett Is working on the issue in the console

**Comment by kargakis** [comment]
> Yes, I'm scaling before the deployment completes. But as you can see, the DC reflects the scaled value, but console does not. Maybe not sending events to console, but when I scale after deployment, console instantly sees the new value. I'd guess that the console is not watching for events until deployment has finished.

I guess this is your initial deployment. When you scale the deploymentconfig before the deployment finishes, the deploymentconfig will store the new value, and the dc controller will try to scale up the latest complete replication controller. Since there is none (even if there was one), the deployment process will always scale to the desired replicas with which it started the deployment. So you have something like this:

```sh
$ oc new-app ...
# dc.spec.replicas = 1 --> desired replicas = 1 --> deployment process will finish with 1 --> rc.spec.replicas = 1
$ oc scale dc --replicas=10 # before the deployment process exits
# dc.spec.replicas = 10, rc.spec.replicas =1
```
Deployment finishes and after at most 2 minutes (resync interval of the dc controller), the dc will be reconciled, and the rc will be actually scaled up. https://github.com/openshift/origin/pull/9002 fixes this. Every time a deployment completes (the rc is marked as complete), the dc controller will notice it and reconcile the related dc on the spot, so you should be able to notice your 10 pods as soon as the deployment is complete.

cc: @ironcladlou
