### ISSUE TITLE
[RFE] Remove PVC references from DC when PVC is removed from the UI

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9059]
Original issue: https://bugzilla.redhat.com/show_bug.cgi?id=1337696

> After adding a volume and making a claim and then removing the claim from the webui the claim is not actually remove from the Deployment config.

As @ironcladlou already noted in Bugzilla, this extends to any kind of reference on a deploymentconfig. Do we want to do anything about it?

@ironcladlou @smarterclayton @liggitt @deads2k @mfojtik @gshipley

**Comment by deads2k** [comment]
It's an ordering problem.  Given a DC with an invalid PVC reference, can we tell the difference between a PVC that was deleted and PVC that was never created?  If the reference held a UID, I guess we'd know, but us removing invalid references will make it harder to build objects in arbitrary orders and edit "bad" resources into a good state.

I think I'd rather be told about dangling references and given an easy way to fix them.

**Comment by smarterclayton** [comment]
Web UI should definitely remove claim if user wants to remove it.  Only the UI / client should do this though, not the API.

**Comment by kargakis** [comment]
> Web UI should definitely remove claim if user wants to remove it. Only the UI / client should do this though, not the API.

cc: @spadgett

**Comment by kargakis** [comment]
For the cli part, we are going to warn in `oc status` for the missing pvc in https://github.com/openshift/origin/pull/9084. I would go ahead and create a reaper for pvc that would remove any dangling references from deployment configs but I am not sure I like it.

Assigning to the UI team for the console part.

**Comment by smarterclayton** [comment]
The reaper is interesting, because the proposed garbage collection /
finalizer can't handle fields within an object.

**Comment by kargakis** [comment]
Moved in the console repo: https://github.com/openshift/origin-web-console/issues/489
