### ISSUE TITLE
Build log shows a glog.Fatalf

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9071]
We should not be using Fatalf at log level <= 2.

```
F0528 13:16:09.021918       1 helpers.go:108] error: build error: The command '/bin/sh -c bundle install --path /app/heroku/ruby/bundle --jobs 4' returned a non-zero code: 18
```

**Comment by coreydaley** [comment]
Running `grep -r "Fatalf" * | grep helpers.go` does not produce any results, it looks like this has been resolved.  Also checked in the source-to-image repo for good measure.
