### ISSUE TITLE
failed to access routes with passthrough or re-encryption type 

### ISSUE THREAD

**Issue by tj13** [openshift/origin#9073]
after installation of cluster metrics and central log stack succesfully, but failed to access them.

##### Version
$ oc version
oc v1.2.0-rc1
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
already deployed these components following the guides
https://docs.openshift.org/latest/install_config/aggregate_logging.html
https://docs.openshift.org/latest/install_config/cluster_metrics.html
$ oc get pods
NAME                         READY     STATUS      RESTARTS   AGE
hawkular-cassandra-1-edqck   1/1       Running     0          1d
hawkular-metrics-hxdqe       1/1       Running     0          1d
heapster-2r999               1/1       Running     0          1d
metrics-deployer-nck1v       0/1       Completed   0          1d
openshift-cockpit-1-qlqgt    1/1       Running     0          1d
]$ oc get route
NAME               HOST/PORT                             PATH      SERVICE            TERMINATION   LABELS
hawkular-metrics   hawkular-metrics.apps.sit.caijj.net             hawkular-metrics   passthrough   metrics-infra=support
##### Current Result
failed to access the route
$ curl -ikv https://hawkular-metrics.apps.sit.caijj.net:443/hawkular/metrics/status
* About to connect() to hawkular-metrics.apps.sit.caijj.net port 443 (#0)
*   Trying 172.0.24.236...
* Connected to hawkular-metrics.apps.sit.caijj.net (172.0.24.236) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb

##### Expected Result
acess the route succesfully.

##### Additional Information
telneted the POD, service, route successfully, curled only successfully when on the node where POD located.
 $ oc get service
NAME                       CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
hawkular-cassandra         172.30.178.92    <none>        9042/TCP,9160/TCP,7000/TCP,7001/TCP   1d
hawkular-cassandra-nodes   None             <none>        9042/TCP,9160/TCP,7000/TCP,7001/TCP   1d
hawkular-metrics           172.30.131.117   <none>        443/TCP                               1d
heapster                   172.30.4.148     <none>        80/TCP                                1d
openshift-cockpit          172.30.121.39    <none>        9000/TCP                              1d
$ oc get endpoints
NAME                       ENDPOINTS                                               AGE
hawkular-cassandra         10.1.0.6:7000,10.1.0.6:9042,10.1.0.6:7001 + 1 more...   1d
hawkular-cassandra-nodes   10.1.0.6:7000,10.1.0.6:9042,10.1.0.6:7001 + 1 more...   1d
hawkular-metrics           10.1.0.7:8443                                           1d
heapster                   10.1.0.10:8082                                          1d
openshift-cockpit          10.1.0.2:9090

$ echo '^]' | telnet hawkular-metrics.apps.sit.caijj.net 443
Trying 172.0.24.236...
Connected to hawkular-metrics.apps.sit.caijj.net.
Escape character is '^]'.
Connection closed by foreign host.
$ echo '^]' | telnet 172.30.131.117 443
Trying 172.30.131.117...
Connected to 172.30.131.117.
Escape character is '^]'.
Connection closed by foreign host.
$ echo '^]' | telnet 10.1.0.7 8443
Trying 10.1.0.7...
Connected to 10.1.0.7.
Escape character is '^]'.
Connection closed by foreign host.

[oadm_diagnostics_log.txt](https://github.com/openshift/origin/files/292569/oadm_diagnostics_log.txt)

**Comment by mwringe** [comment]
Can you create and access routes for other services? Are you sure your router is properly installed and  configured? The out of the box installation with the passthrough route should work, since it doesn't I would look at your router as the root cause.

Things you may want to check:
- can you access the service ip address directly? get https://${HAWKULAR_METRICS_SERVICE_IP_ADDRESS}
- can you access the endpoint using the router ip address? eg
`curl -k --resolve ${HAWKULAR_METRICS_HOSTNAME}:${ROUTER_IP} https://${HAWKULAR_METRICS_HOSTNAME}`

Github also allows your to upload files, this makes adding large amounts of content easier and makes the issue much more easier to follow. The quicker it is to read and understand an issue the easier it is for us to determine the root cause.

**Comment by sosiouxme** [comment]
Since you do have a router, I would add that it sounds like either the router isn't routing (check the pod logs, it's possible to break the config in some way) or that the SDN is not functioning between the router and the backend, in which case this may be of some assistance: https://docs.openshift.org/latest/admin_guide/sdn_troubleshooting.html

**Comment by tj13** [comment]
@mwringe thanks for you reply, and sorry for the inconvenience of the large log message.
i have one route for http service in another project, and the route works fine. 
all the access to the metrics are hung at * Initializing NSS with certpath: sql:/etc/pki/nssdb.

i've attach the full log message in the attachment, including the whole procedure of enabling cluster metrics and the verification of available route in another project
[log.txt](https://github.com/openshift/origin/files/292545/log.txt)

**Comment by tj13** [comment]
@sosiouxme  haproxy router log as below when accessing route(https://hawkular-metrics.apps.sit.caijj.net/):
[tanjun@centosdev02 ~]$ sudo docker logs --tail=100 -f 521576ef053c
I0601 03:02:04.937123       1 router.go:161] Router is including routes in all namespaces
I0601 03:02:05.213300       1 router.go:310] Router reloaded:
 - Checking HAProxy /healthz on port 1936 ...
 - HAProxy port 1936 health check ok : 0 retry attempt(s).
I0601 03:02:10.006635       1 router.go:310] Router reloaded:
 - Checking HAProxy /healthz on port 1936 ...
 - HAProxy port 1936 health check ok : 0 retry attempt(s).
I0601 03:02:14.950101       1 router.go:310] Router reloaded:
 - Checking HAProxy /healthz on port 1936 ...
 - HAProxy port 1936 health check ok : 0 retry attempt(s).
I0601 03:02:22.068743       1 router.go:310] Router reloaded:
 - Checking HAProxy /healthz on port 1936 ...
 - HAProxy port 1936 health check ok : 0 retry attempt(s).
I0601 03:04:36.049228       1 router.go:310] Router reloaded:
 - Checking HAProxy /healthz on port 1936 ...
 - HAProxy port 1936 health check ok : 0 retry attempt(s).

**Comment by mwringe** [comment]
The deployer is exiting in an error state, what is the error message in the logs?

Accessing it via the pod ip should really work, I don't know why it isn't. Do you have any firewall rules setup where you cannot access that ip address or that port? Can you try performing that curl by 'exec'ing into the Heapster pod?

**Comment by tj13** [comment]
@mwringe 

1. log file for deployer

1. Log file for deployer

[tanjun@centosdev01 ~]$ oc get pods
NAME                         READY     STATUS    RESTARTS   AGE
hawkular-cassandra-1-a2bg5   1/1       Running   1          23h
hawkular-metrics-qloxw       1/1       Running   1          23h
heapster-ivrmc               1/1       Running   2          23h
metrics-deployer-lzlfp       0/1       Error     0          23h
[tanjun@centosdev01 ~]$ oc logs -f metrics-deployer-lzlfp
  * * * * 
Will retry in 5 seconds.
========================
--- validate_deployment_artifacts ---
======== ERROR =========
validate_deployment_artifacts: 
scripts/validate.sh: line 273: line[3]: unbound variable
Pod hawkular-metrics-69zye from ReplicationController hawkular-metrics is running but not marked ready.
This is most often due to either startup latency or crashing for lack of other services.
It should resolve over time; if not, check the pod logs to see what is going wrong.
  * * * * 
========================
--- validate_deployed_project ---

2. access from Heapster POD to hawkular-metrics POD is successfully.

[tanjun@centosdev01 ~]$ oc get endpoints
NAME                       ENDPOINTS                                               AGE
hawkular-cassandra         10.1.0.2:7000,10.1.0.2:9042,10.1.0.2:7001 + 1 more...   23h
hawkular-cassandra-nodes   10.1.0.2:7000,10.1.0.2:9042,10.1.0.2:7001 + 1 more...   23h
hawkular-metrics           10.1.0.5:8443                                           23h
heapster                   10.1.0.3:8082                                           23h
[tanjun@centosdev01 ~]$ oc exec -it heapster-ivrmc /bin/bash
bash-4.2$ curl -ivk https://10.1.0.5:8443/hawkular/metrics/status
* About to connect() to 10.1.0.5 port 8443 (#0)
*   Trying 10.1.0.5...
* Connected to 10.1.0.5 (10.1.0.5) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=hawkular-metrics
* 	start date: Jun 01 01:57:01 2016 GMT
* 	expire date: Jun 01 01:57:02 2018 GMT
* 	common name: hawkular-metrics
* 	issuer: CN=metrics-signer@1464746221
> GET /hawkular/metrics/status HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.1.0.5:8443
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Connection: keep-alive
Connection: keep-alive
< X-Powered-By: Undertow/1
X-Powered-By: Undertow/1
< Server: WildFly/10
Server: WildFly/10
< Content-Type: application/json
Content-Type: application/json
< Content-Length: 133
Content-Length: 133
< Date: Thu, 02 Jun 2016 01:43:09 GMT
Date: Thu, 02 Jun 2016 01:43:09 GMT

< 
* Connection #0 to host 10.1.0.5 left intact
{"MetricsService":"**STARTED**","Implementation-Version":"0.15.0.Final","Built-From-Git-SHA1":"6731208d7eacbf3ffd102c21943214a51384f390"}bash-4.2$

**Comment by sosiouxme** [comment]
Sounds like the validations are indicating hawkular-metrics couldn't talk to cassandra. This really sounds like an SDN issue (most likely a port blocked one way or another) - https://docs.openshift.org/latest/admin_guide/sdn_troubleshooting.html

**Comment by tj13** [comment]
@sosiouxme
 is the deployment failed? 
also following message is streaming on heapster POD like below:
...
W0602 06:57:35.092307       1 node_aggregator.go:44] Failed to find node: node:centosdev02.sit.caijj.net
W0602 06:57:35.092322       1 node_aggregator.go:44] Failed to find node: node:centosdev02.sit.caijj.net
W0602 06:57:35.092325       1 node_aggregator.go:44] Failed to find node: node:centosdev01.sit.caijj.net
W0602 06:57:35.092329       1 node_aggregator.go:44] Failed to find node: node:centosdev02.sit.caijj.net
W0602 06:57:35.092332       1 node_aggregator.go:44] Failed to find node: node:centosdev02.sit.caijj.net
W0602 06:57:35.092335       1 node_aggregator.go:44] Failed to find node: node:centosdev02.sit.caijj.net
W0602 06:57:35.092341       1 node_aggregator.go:44] Failed to find node: node:centosdev02.sit.caijj.net
I0602 06:57:45.000236       1 manager.go:79] Scraping metrics start: 2016-06-02 06:57:30 +0000 UTC, end: 2016-06-02 06:57:40 +0000 UTC
I0602 06:57:45.065007       1 manager.go:152] ScrapeMetrics: time
...

the attachments are the  troubleshooting log per your recommendation and the iptables rules of the whole cluster machines.
[centosdev01_iptables.txt](https://github.com/openshift/origin/files/295111/centosdev01_iptables.txt)
[centosdev02_iptables.txt](https://github.com/openshift/origin/files/295113/centosdev02_iptables.txt)
[centosdev03_iptables.txt](https://github.com/openshift/origin/files/295115/centosdev03_iptables.txt)

///
Reading the Logs
Run: journalctl -u origin-node.service --boot | less

Look for the Output of setup script: line. Everything starting with '+' below that are the script steps. Look through that for obvious errors.

Following the script you should see lines with Output of adding table=0. Those are the OVS rules, and there should be no errors.
///

this check is failed, i can not find such thing in the log messages.

**Comment by tj13** [comment]
issue is resolved after changing the MTU size from 9001 to 1450. the whole environment run on AWS, default MTU is 9001.
