### ISSUE TITLE
missing package/code documentation

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#9074]
Our code/package documentation coverage is bad and we should feel bad. 
But for starters we could work on adding a doc.go to all the packages that we have in OpenShift. It doesn't have to be at great details (at least not for now). We currently are doing this to some extent but there are a lot of things missing. Whilst OpenShift grew, we've fallen more and more behind on introducing quality to what we work on.
I will introduce a series of PRs to fix this issue, but i'm more than certain i can't do it alone so any help would be greatly appreciated.
@smarterclayton @bparees @mfojtik @rhcarvalho @soltysh @kargakis - thoughts/help?

here's how our godocs look, sorry for the long screenshot but i thought it be necessary to make a point:
![origin - the go programming language](https://cloud.githubusercontent.com/assets/6294120/15628921/72f22190-250e-11e6-834e-432da3b2aeb5.png)

**Comment by mfojtik** [comment]
Agree, we should make the godoc more clean and provide package descriptions, but I don't think it is a high priority for now. Maybe we should update the travis bot to check that when a new package is added it will verify that it contains the documentation header.

**Comment by kargakis** [comment]
Good documentation is always welcome. I used to try keep our codebase documented using golint and sweeping through it but ultimately its up to the individual component maintainers to keep it up.

**Comment by bparees** [comment]
+1 on "this is not a priority"  (would that be a -1?)

**Comment by soltysh** [comment]
It actually one of those nice getting started issues.

**Comment by PI-Victor** [comment]
i didn't think about it as a priority, but rather a long-term commitment that we can solve incrementally.
for example, whenever you fix a bug or introduce a new feature and you notice that there's a missing doc.go in the package that you are working on, then you can add it. 
i think as a separate commit aside from what you are doing, and not squashed in.
on the other hand it's fine if no one has the time, at least for devex i'll ask what packages do and fix this, but i can't do it for the other parts that we don't manage, unless i get some help, hence me trying getting more people involved. :)

**Comment by bparees** [comment]
Sure, asking people to think about it as they are touching packages makes
sense.

Ben Parees | OpenShift
