### ISSUE TITLE
The HAProxy router should serve the correct routes when scoped to a single namespace and label set

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9076]
```
• Failure [391.130 seconds]
[networking][router] openshift routers
/data/src/github.com/openshift/origin/test/extended/router/scoped.go:133
  The HAProxy router
  /data/src/github.com/openshift/origin/test/extended/router/scoped.go:132
    should serve the correct routes when scoped to a single namespace and label set [It]
    /data/src/github.com/openshift/origin/test/extended/router/scoped.go:73

    Expected error:
        <*errors.errorString | 0xc820011e40>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    not to have occurred

    /data/src/github.com/openshift/origin/test/extended/router/scoped.go:48
------------------------------
DNS 
  should answer endpoint and wildcard queries for the cluster [Conformance]
  /data/src/github.com/openshift/origin/test/extended/dns/dns.go:290
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/1376/consoleFull

**Comment by smarterclayton** [comment]
Suspect this is the secrets issue.

**Comment by smarterclayton** [comment]
Nm, was pre rebase.

**Comment by danmcp** [comment]
Closing since no one has reported this in a long time.

**Comment by danwinship** [comment]
just saw it again, https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8230/consoleFull

**Comment by fabianofranz** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8482/

**Comment by knobunc** [comment]
Based on the logs, we are taking > 2m to pull images and start the pods before things are torn down.

This seems to be https://github.com/openshift/origin/issues/11016

**Comment by bparees** [comment]
still happening: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/9556/

**Comment by bparees** [comment]
guess this was duped to #11016, sorry.
