### ISSUE TITLE
openshift/origin-keepalived-ipfailover is broken after v1.3.0-alpha.0 (regression)

### ISSUE THREAD

**Issue by gravis** [openshift/origin#9077]
```
$ docker run -it --rm openshift/origin-keepalived-ipfailover:v1.3.0-alpha.1
docker: Error response from daemon: Container command '/var/lib/origin/ipfailover/keepalived/monitor.sh' not found or does not exist..
```

##### Version
images `openshift/origin-keepalived-ipfailover:v1.3.0-alpha.1` and `openshift/origin-keepalived-ipfailover:latest` are impacted

##### Steps To Reproduce
1. Deploy a new cluster with the ansible recipe
2. OR run directly the image as above

##### Current Result

```
$ docker run -it --rm openshift/origin-keepalived-ipfailover:v1.3.0-alpha.1
docker: Error response from daemon: Container command '/var/lib/origin/ipfailover/keepalived/monitor.sh' not found or does not exist..
```
##### Expected Result

```
Initializing ipvs 2.6
Keepalived_healthcheckers[2214]: Initializing ipvs 2.6
IPVS: Can't initialize ipvs: Permission denied (you must be root)
Keepalived_healthcheckers[2214]: IPVS: Can't initialize ipvs: Permission denied (you must be root)
Healthcheck child process(2214) died: Respawning
Keepalived[60]: Healthcheck child process(2214) died: Respawning
[...]
```

##### Additional Information

It's working fine until `v1.3.0-alpha.0`

**Comment by smarterclayton** [comment]
Thanks, looks like it is a result of the image simplification changes.  @ramr I'll sync up with you on a fix

**Comment by smarterclayton** [comment]
Will push the new image later today.

**Comment by knobunc** [comment]
@smarterclayton Did the new openshift/origin-keepalived-ipfailover image resolve the issue?

**Comment by smarterclayton** [comment]
I have no reports it didn't

**Comment by knobunc** [comment]
Thanks @smarterclayton
