### ISSUE TITLE
`oc create configmap` needs short forms of --from-literal and --from-file

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#9078]
If you want to make a configmap with more than two or three entries, then typing these full options (which will be required on every configmap) is pretty annoying and error-prone. They should have short forms e.g. "-l" and "-f".

I am planning to use configmaps as inputs to deployers instead of template parameters. This will be pretty painful with two dozen or so potential options.

**Comment by deads2k** [comment]
Don't re-use `-f`.  That means "from file" or "resource/name tuples from file".

**Comment by sosiouxme** [comment]
I still think it's a good idea but it doesn't appear to be of adequate concern to anyone else.
