### ISSUE TITLE
Get rid of the `oc set <thing> --remove` pattern in favor of a new `oc unset` command

### ISSUE THREAD

**Issue by fabianofranz** [openshift/origin#9087]
Several `oc set <thing>` commands are using the `--remove` flag to unset stuff. That's counter-intuitive, "set remove" is not good in terms of command fluidity. 

We should have an `oc unset <thing>` set of commands using the same nouns under `set` and deprecate the `--remove` flags.

**Comment by fabianofranz** [comment]
@openshift/ui-review

**Comment by fabianofranz** [comment]
TODO list here which `set` commands have to be adjusted.

**Comment by smarterclayton** [comment]
We can't just remove it without offering an alternative, we can't just introduce a new alternative without closing on this upstream (because this is a larger design issue), and that's not going to happen in 1.3.  So putting this as a p1 is probably too high.

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/39775
