### ISSUE TITLE
TestTimedCommandTimeout flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9089]
```
In suite "github.com/openshift/origin/pkg/generate/git", test case "TestTimedCommandTimeout" failed:
=== RUN   TestTimedCommandTimeout
--- FAIL: TestTimedCommandTimeout (0.04s)
	repository_test.go:133: expected command to have timed out, but it didn't
FAIL
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/1268/consoleFull

**Comment by stevekuznetsov** [comment]
@deads2k how long do you think the timeouts in this test should be too not flake on the Jenkins boxes? In retrospect I shouldn't have set them quite so low

**Comment by deads2k** [comment]
> @deads2k how long do you think the timeouts in this test should be too not flake on the Jenkins boxes? In retrospect I shouldn't have set them quite so low

45 seconds.

**Comment by smarterclayton** [comment]
Let's get a fix for this merged asap - seeing this on a lot of runs.

**Comment by deads2k** [comment]
in the queue.
