### ISSUE TITLE
Override AWS nodeName with local hostname

### ISSUE THREAD

**Issue by danni** [openshift/origin#9092]
When you run Openshift with cloud-config=aws, your nodeNames must match the AWS metadata service. This makes for reading the node name throughout Openshift a pain if you haven't memorised the IPs. If the node name itself can't be changed (which seems to be a limitation of Kubernetes).

i.e. overriding nodeName in the config:

```
May 31 12:48:27 master3.openshift.sqw.im origin-node[14005]: E0531 12:48:27.628640   14050 kubelet.go:1131] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
```

it would be good to be able to set some sort of display name that could be used through Openshift.

**Comment by danni** [comment]
I appreciate the Kubernetes error is discussed at length in https://github.com/kubernetes/kubernetes/issues/11543

**Comment by ncdc** [comment]
This is covered by https://bugzilla.redhat.com/show_bug.cgi?id=1318230 and https://trello.com/c/dyHpMQw9/335-as-a-user-i-want-to-the-installer-to-configure-for-the-openstack-cloudprovider-without-having-to-manually-edit-the-node-configs (which needs to be updated to handle all cloud providers and not just OpenStack).
