### ISSUE TITLE
osc namespace fails

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#914]
On our RHEL 7 AMI with 1b21883c9c1f08c64221ec5e0b7ffa2b7e6951a3

    # osc create -f project.json 
    national-parks
    # osc namespace national-parks
    Set current namespace to national-parks
    F0205 09:48:41.933715    5349 namespace.go:57] open : no such file or directory

You can edit `~/.kubernetes_ns` manually to change current namespace, but `osc namespace` just fails. Not sure if this is because of something special about root homedir or something else.

**Comment by sosiouxme** [comment]
Error is at https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/namespace.go#L55 (for either use case, read or set, an error is returned) and doesn't seem to be affected by which user is running the command or whether selinux is enabled.

**Comment by sosiouxme** [comment]
Latest word is that "osc namespace" is going away, to be experimentally replaced by "openshift ex config".

So, it should go away instead of breaking.

**Comment by smarterclayton** [comment]
@fabianofranz will resolve this with the switch projects command.

**Comment by smarterclayton** [comment]
Removed namespace
