### ISSUE TITLE
Update imagestreams for SCL 2.2

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#9140]
Update image stream definitions in https://github.com/openshift/origin/tree/master/examples/image-streams to include updated images from SCL 2.2 release 

New additions include: MariaDB 10.1, MongoDB 3.2 and PostgreSQL 9.5, Node.js v4.4, Python 3.5, Ruby 2.3 and Rails 4.2

Listed with full names here: https://access.redhat.com/articles/1752723

**Comment by tracyrankin** [comment]
@sspeiche @bparees could we/should we make these available for 3.2.1 as well?

**Comment by danmcp** [comment]
@sspeiche Shouldn't this be handled as a card?

**Comment by bparees** [comment]
just adding them is easy enough, but if we need to send the images through QE before we add them, we need a card for each to make that happen.  Probably need to talk to SCL and see whether they've gotten openshift QE to test these images already.

**Comment by danmcp** [comment]
https://trello.com/c/8qt2hCOE/945-update-imagestreams-for-scl-2-2
