### ISSUE TITLE
Provide a webhook trigger for deployment config

### ISSUE THREAD

**Issue by thescouser89** [openshift/origin#9145]
Build Config has the ability to trigger new builds using a [webhook](https://docs.openshift.com/enterprise/3.1/dev_guide/builds.html#webhook-triggers)

It would be nice to have it for deployment configurations as well. Deployment configurations only provide configuration change and image change triggers.

**Comment by kargakis** [comment]
Dupe of https://github.com/openshift/origin/issues/3659
