### ISSUE TITLE
Provide an option to redeploy deployment when config map used changes

### ISSUE THREAD

**Issue by thescouser89** [openshift/origin#9146]
My desired setup:
1. Have build config build the source code of my webapp
2. Have deployment config inject the configurations to my pod via a config map

The reason for this setup is that when I only need to change my configuration, I only have to change my config map, then redeploy the pod. The alternative would be to use the build config to build both source code and have the configurations in it, which makes changing configuration only a hassle as it also need to build the source code again.
1. Every time I change the config map, I'd like Openshift to provide an option to trigger a redeploy in all the pods/deployment configurations that use the config map (and mount it as a volume/used for env variables) so that the server running inside the pod can be restarted to use the new configurations. The alternative right now would be to manually execute

```
oc deploy <dc>
```

to force the app to restart and use the new configurations.
##### Version

oc v3.2.0.44
kubernetes v1.2.0-36-g4a3f9c5

**Comment by kargakis** [comment]
Upstream issue: https://github.com/kubernetes/kubernetes/issues/22368

**Comment by AlbertoPeon** [comment]
I vote for this as well. It would be awesome to have this for both ConfigMaps and secrets.

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/22368
