### ISSUE TITLE
`atomic-openshift-installer uninstall` attempts to uninstall docker in master_lb

### ISSUE THREAD

**Issue by relaxdiego** [openshift/origin#9149]
When uninstalling an HA OpenShift cluster using `atomic-openshift-installer uninstall`, it also attempts to uninstall docker from the master cluster LB which fails because docker was never installed and doesn't need to be installed.

##### Version
failed: [10.0.3.10] => {"failed": true}
msg: Failed to stop docker.service: Unit docker.service not loaded.
Failed to start docker.service: Unit docker.service failed to load: No such file or directory.

##### Steps To Reproduce
1. Install an HA OpenShift cluster using `atomic-openshift-installer install`. Make sure the LB is its own machine.
2. Uninstall using `atomic-openshift-installer uninstall`

##### Current Result
A failure occurs when attempting to uninstall the LB.

##### Expected Result
The uninstaller should complete successfully.

**Comment by detiber** [comment]
@sdodson ptal

**Comment by sdodson** [comment]
This is https://github.com/openshift/origin/issues/9149

**Comment by sdodson** [comment]
Fixed in https://github.com/openshift/openshift-ansible/pull/1984 closing this.
