### ISSUE TITLE
Flake in TestKubeAdmissionControllerUsage

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9169]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/1521/testReport/junit/github/com_openshift_origin_pkg_cmd_server_start/TestKubeAdmissionControllerUsage/

**Comment by smarterclayton** [comment]
@deads2k is this a new test?

**Comment by deads2k** [comment]
Not a flake, an oversight.
