### ISSUE TITLE
provide a simple REST API to find the public IP / DNS / route of a service

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#917]
right now a service has a private portalIP and could have publicIPs; then it could have routes and could have DNS entries and other things. So its not totally trivial for a client to grok the public address.

It'd be nice if there was an easy REST API to be able to find the IP / host name(s) that should be used for a service given its name.  Similar to the endpoints addresses REST API; but to find the public addresses (rather than endpoints implementing a service).

Something like *\* GET /api/v1beta4/services/{name}/public**

```
{
  "kind": "PublicServiceAddressList",
   ...
  "items:" [
    {
       "address": "hostOrIPAddress",
       "port": 1234
    },
    {
       "address": "hostOrIPAddress",
       "port": 1234
    }
  ]
}
```

Either that or we should include this metadata inside the service JSON?

**Comment by bparees** [comment]
@pweil- @abhgupta can one of you take a look at this request?

**Comment by pweil-** [comment]
@jstrachan - agree, the info is scattered between multiple objects at the moment and makes it difficult to grok.  

There is currently an upstream issue that proposes a reorg of services for v1beta3 that includes route specs, dns specs, portals, and more.  https://github.com/GoogleCloudPlatform/kubernetes/issues/2585#issuecomment-70044693  

With that implementation, I think doing a GET on the service itself might be enough to give you all the info you're looking for.

**Comment by danmcp** [comment]
cc @smarterclayton
