### ISSUE TITLE
"make GOFLAGS=-v" won't output compile information

### ISSUE THREAD

**Issue by tangfx** [openshift/origin#9171]
fix Makefile:

-export GOFLAGS
+OS_GOFLAGS=$(GOFLAGS)
+export OS_GOFLAGS

**Comment by stevekuznetsov** [comment]
@smarterclayton perhaps you can enlighten me on our strategy for the `make` targets, but I don't really understand this. I think there's just drift between the actual usage and the `Makefile` doc.

```sh
$ OS_GOFLAGS='-v' make build
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
k8s.io/kubernetes/pkg/labels
gopkg.in/yaml.v2
github.com/opencontainers/runc/libcontainer/system
github.com/blang/semver
github.com/docker/docker/pkg/tarsum
github.com/Sirupsen/logrus
github.com/ugorji/go/codec
github.com/emicklei/go-restful
github.com/dgrijalva/jwt-go
k8s.io/kubernetes/pkg/api/unversioned
...
```

This works fine, and requires no delegation of the envars by `make`. Why don't we want to use this, simply?

**Comment by stevekuznetsov** [comment]
@smarterclayton I don't understand what you mean.

The current behavior is *not* to honor `$GOFLAGS`:
```
$ GOFLAGS='-v' make build
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
++ Placing binaries
hack/build-go.sh took 161 seconds
```

**Comment by stevekuznetsov** [comment]
Ah, sorry, by `'this'` you meant my suggestion -- we should *not* forward `$GOFLAGS` to `$OS_GOFLAGS`. In that case, I think this is working as intended.
