### ISSUE TITLE
if project already exists, post ProjectRequest will return unversioned.Status

### ISSUE THREAD

**Issue by tangfx** [openshift/origin#9172]
I am using `restclient.Config` to call server like `oc new-project`, if this project is already exists, the returned object is `unversioned.Status`

##### Version
`openshift version`

openshift v1.3.0-alpha.0-110-g3db0fc4

kubernetes v1.3.0-alpha.1-331-g0522e63

etcd 2.3.0
##### Steps To Reproduce
1. run [test code](github.com/tangfeixiong/go-to-cloud-1/pkg/openshift/client/tcprojectrequest)
2. run again

##### Current Result
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"project \"gogogo\" already exists","reason":"AlreadyExists","details":{"name":"gogogo","kind":"project"},"code":409}

##### Expected Result
according `github.com/openshift/origin/pkg/client/projectrequests.go`:

    type ProjectRequestInterface interface {
        Create(p *projectapi.ProjectRequest) (*projectapi.Project, error)
    }

**Comment by liggitt** [comment]
Status errors like that are working as designed for conflicts, not found, unauthorized and forbidden errors
