### ISSUE TITLE
replication / slave issues with "openshift/postgresql-92-centos7"

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#9188]
@bparees FYI

Even after my workarounds for the openshift namespace image streams getting deleted, both on jenkins and my local system, I see that the slave pods are never deployed with "openshift/postgresql-92-centos7".  The other 3 versions used in postgresql_replica.go seem to work consistently.

I'm hoping we can delegate the fun a little bit here, and have perhaps someone else on the team drive this one while I move on to the remaining items wrt extended tests.

**Comment by bparees** [comment]
@gabemontero do you have enough data on this that it makes sense to have the platform management team (deployments) investigate?

**Comment by gabemontero** [comment]
@bparees the only thing of any potential relevance I've seen in the data so far is:

```
Jun  6 18:53:23.677: INFO: At 2016-06-06 18:50:03 -0400 EDT - event for postgresql-slave-1-dfkdz: {kubelet 172.18.0.93} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "postgresql-slave" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=postgresql-slave pod=postgresql-slave-1-dfkdz_extended-test-postgresql-replication-0-t3i78-xjapr(c7e953e6-2c38-11e6-94c5-0e334cee71c9)"
```

And then in the associated master log, there are some corresponding "container inspect" logs that denote the postgresql slave exited with RC of 1.

**Comment by bparees** [comment]
ok that definitely sounds like an image problem and not a deploy problem.  do we have logs from the container/pod itself?

**Comment by gabemontero** [comment]
No, and they have been very hard to obtain.  Pods seem to get deleted
before I can dump them with `oc logs`.  My thought was that someone more
experienced with this postgresql scenario could try and reproduce this
manually.

**Comment by gabemontero** [comment]
Finally got a log dump of the postgresql-slave pod to work (dumping earlier postgresql-helper pods were hanging for some weird reason).

Here is what was present:

```
Jun  7 15:39:41.247: INFO: Running 'oc logs --namespace=extended-test-postgresql-replication-0-yf9e4-ein6i --config=/tmp/extended-test-postgresql-replication-0-yf9e4-ein6i-user.kubeconfig -f pod/postgresql-slave-1-9rpkw'


  logs for pod postgresql-slave-1-9rpkw : /usr/share/container-scripts/postgresql/common.sh: line 9: MEMORY_LIMIT_IN_BYTES: unbound variable

```
And that is it.
Unless this is a known red herring that I'm unfamiliar with, my guess is this bash error nukes the startup.

**Comment by gabemontero** [comment]
Now that I'm past the `oc logs` hang, I'm now seeing a postgresql-slave container log that has the exact same single line of contents.

The postgresql master and helper have larger, typical looking logs with startup type activity.

I'm a little more certain that this unbound variable is what is blowing up the slave.
