### ISSUE TITLE
DNS [It] should answer endpoint and wildcard queries for the cluster [Conformance] failure

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9192]
```
• Failure [309.561 seconds]
DNS
/data/src/github.com/openshift/origin/test/extended/dns/dns.go:291
  should answer endpoint and wildcard queries for the cluster [Conformance] [It]
  /data/src/github.com/openshift/origin/test/extended/dns/dns.go:290

  Expected
      <*errors.errorString | 0xc820ab17e0>: {
          s: "gave up waiting for pod 'dns-test-acf11237-2c93-11e6-baa3-0e0a2704d145' to be 'running' after 5m0s",
      }
  to be nil

  /data/src/github.com/openshift/origin/test/extended/dns/dns.go:138
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/1712/consoleFull

**Comment by soltysh** [comment]
I've seen something similar, iow. stuck waiting for a pod, but in different area:
```
[k8s.io] ConfigMap
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework.go:420
  updates should be reflected in volume [Conformance] [It]
  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/configmap.go:152

  Expected error:
      <*errors.errorString | 0xc82020baf0>: {
          s: "gave up waiting for pod 'pod-configmaps-ee154689-2cc6-11e6-a7e2-0e084c56b491' to be 'running' after 5m0s",
      }
      gave up waiting for pod 'pod-configmaps-ee154689-2cc6-11e6-a7e2-0e084c56b491' to be 'running' after 5m0s
  not to have occurred

  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/configmap.go:136
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/1726/consoleFull

**Comment by bparees** [comment]
recurred here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2573/consoleFull

**Comment by smarterclayton** [comment]
This is because the pod runs to completion before the e2e test looks at it,
which is a bug in the test logic.  It should tolerate the pod having run to
completion when it starts to watch.  Probably occurs anywhere else we do
the watch based tracking.

**Comment by soltysh** [comment]
Upstream is using `Get`/`List` in majority of `waitFor*` methods. See [util.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go)

**Comment by smarterclayton** [comment]
We need to fix that.  It's a bad pattern and adds to the time tests take.

**Comment by soltysh** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/28212 to address that. I'll cherry-pick it once it's approved upstream.

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3193/consoleFull

**Comment by smarterclayton** [comment]
Putting a fix in now for the last part into Origin.  It adds "PodSucceeded" as a watch condition (which should be moved upstream) but is correct.
