### ISSUE TITLE
403 forbidden - configure serviceaccount

### ISSUE THREAD

**Issue by ltagliamonte** [openshift/origin#9205]
Hello,
i'm trying to deploy a daemonset that needs to fetch the k8s api, I configured the container to use the barer token, but i'm getting 403:
```
2016-06-07 06:59:40.033, 26804, Error, 06-07 18:59:40.032969 K8s: An error occurred while trying to retrieve data for nodes: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:serviceaccount:myproject:default\" cannot list all nodes in the cluster",
  "reason": "Forbidden",
  "details": {
    "kind": "nodes"
  },
  "code": 403
}
```  
i tried with `oc policy add-role-to-group` and `oc policy add-role-to-user`, but i had no luck, can someone please help me?

**Comment by liggitt** [comment]
To grant cluster-wide access or access to unnamespaced objects (like nodes), you have to add the role at the cluster level using `oadm policy add-cluster-role-to-user cluster-reader system:serviceaccount:myproject:default`
