### ISSUE TITLE
Command Failed 'oc get -n test builds | grep -i running'

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9217]
```
[FAIL] Returning early. Command Failed 'oc get -n test builds | grep -i running'
!!! Error in hack/../hack/../test/end-to-end/../../hack/util.sh:294
	'return 1' exited with status 1
Call stack:
	1: hack/../hack/../test/end-to-end/../../hack/util.sh:294 os::build:wait_for_start(...)
	2: hack/../hack/../test/end-to-end/core.sh:232 main(...)
Exiting with status 1
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/1648/consoleFull

**Comment by bparees** [comment]
failed pulling the image:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/1648/artifact/origin/artifacts/test-end-to-end-docker/logs/container-ruby-sample-build-1-build-sti-build.log

dupe of https://github.com/openshift/origin/issues/8596
