### ISSUE TITLE
Disabled test/integration/newapp_test.go (post-rebase)

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#9219]
The test was (will be) disabled after the rebase lands. The reason is the switch to `docker-engine-api` library instead of fsouza go-dockerclient. It will require significant refactoring.

**Comment by mfojtik** [comment]
@csrwng just a future placeholder :-)

**Comment by bparees** [comment]
@mfojtik given that fsouza/go-dockerclient is still available as a godep, does this test actually have to be disabled?

**Comment by mfojtik** [comment]
@bparees it is,  but the test use the methods that I haven't mocked when I created wrapper. The test required heavy refactoring and @csrwng agreed we will do that post-rebase.

**Comment by mfojtik** [comment]
@bparees example of failures:

```console
# github.com/openshift/origin/test/integration
../../../../test/integration/newapp_test.go:470: cannot use []"github.com/fsouza/go-dockerclient".APIImages literal (type []"github.com/fsouza/go-dockerclient".APIImages) as type []"github.com/docker/engine-api/types".Image in field value
../../../../test/integration/newapp_test.go:471: cannot use dockerBuilderImage() (type *"github.com/fsouza/go-dockerclient".Image) as type *"github.com/docker/engine-api/types".ImageInspect in field value
```

(means we need convertor from fsouza Image to engine ImageInspect or rewrite the new-app to use the engine types.
