### ISSUE TITLE
Push to registry "User system:serviceaccount:default:registry cannot list limitranges in project"

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#9231]
When pushing to registry returns 500 error. Registry log:
"User system:serviceaccount:default:registry cannot list limitranges in project"

##### Version
openshift v1.3.0-alpha.1-178-gc5bd429

##### Steps To Reproduce
1. deploy registry
2. Create project
3. tag and push image to registry

##### Current Result
Received unexpected HTTP status: 500 Internal Server Error

##### Expected Result
Success

##### Additional Information
Registry log: http://paste.fedoraproject.org/376341/14654135/

**Comment by liggitt** [comment]
A few questions:
* Did you enable quota on the registry?
* How did you create the registry and `registry` service account?
* Did you grant the service account the `system:registry` role cluster-wide?
* Are your role definitions up-to-date (what does `oadm policy reconcile-cluster-roles -o name` show)?

**Comment by aweiteka** [comment]
It looks like the clusterrolebinding "registry-registry-role" was not created. This was a misconfiguration due to human error. Running `oadm registry` works fine.
