### ISSUE TITLE
Support PROXY protocol in router

### ISSUE THREAD

**Issue by anthonyrisinger** [openshift/origin#9233]
We run the default router with 3 replicas behind an ELB. This allows delegating IP failover and top-level load balancing to AWS, while still allowing the OpenShift routers to terminate TLS and properly set X-Forwarded-* headers (otherwise the IP is the ELB, not the client).

Doing so currently requires two hacks in the router's environment:

```bash
ROUTER_SERVICE_HTTP_PORT='80 accept-proxy'
ROUTER_SERVICE_HTTPS_PORT='443 accept-proxy'
```

It was suggested in IRC that one or both of these might be appropriate:

```bash
ROUTER_PROXY_PROTOCOL
ROUTER_BIND_OPTIONS='accept-proxy'
```

Thoughts?

**Comment by elyscape** [comment]
It should be noted that, in order for this to work, the ELB should be set up using TCP listeners and backends on ports 80 and 443, and PROXY protocol support needs to be enabled [on the command line](https://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html).

**Comment by danmcp** [comment]
Closing in favor of:

https://bugzilla.redhat.com/show_bug.cgi?id=1334313
and
https://trello.com/c/uFtX1d5l
