### ISSUE TITLE
Implement Object and ObjectMetaAccessor for types missing them

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9249]
In order to get rid of our favorite nag message:
```
I0526 12:04:45.033382   30393 meta.go:46] Calling Accessor on non-internal object: <type>
```

We need to implement `Object` and `ObjectMetaAccessor` for:

### OpenShift types
 - [ ] `*api.BuildConfigList`
 - [ ] `*api.BuildList`
 - [ ] `*api.ClusterNetworkList`
 - [ ] `*api.ClusterPolicyBindingList`
 - [ ] `*api.ClusterPolicyList`
 - [ ] `*api.DeploymentConfigList`
 - [ ] `*api.GroupList`
 - [ ] `*api.HostSubnetList`
 - [ ] `*api.IdentityList`
 - [ ] `*api.ImageList`
 - [ ] `*api.ImageStreamList`
 - [ ] `*api.ImageStreamTagList`
 - [ ] `*api.NamespaceList`
 - [ ] `*api.NetNamespaceList`
 - [ ] `*api.OAuthAccessTokenList`
 - [ ] `*api.OAuthAuthorizeTokenList`
 - [ ] `*api.OAuthClientAuthorizationList`
 - [ ] `*api.OAuthClientList`
 - [ ] `*api.PolicyBindingList`
 - [ ] `*api.PolicyList`
 - [ ] `*api.ProjectList`
 - [ ] `*api.RoleBindingList`
 - [ ] `*api.RoleList`
 - [ ] `*api.SubjectAccessReviewResponse`
 - [ ] `*api.TemplateList`
 - [ ] `*api.UserList`

### Kubernetes types
 - [ ] `*api.ConfigMapList`
 - [ ] `*api.EndpointsList`
 - [ ] `*api.EventList`
 - [ ] `*api.LimitRangeList`
 - [ ] `*api.List`
 - [ ] `*api.NodeList`
 - [ ] `*api.PersistentVolumeClaimList`
 - [ ] `*api.PersistentVolumeList`
 - [ ] `*api.PodList`
 - [ ] `*api.PodTemplateList`
 - [ ] `*api.ReplicationControllerList`
 - [ ] `*api.ResourceQuotaList`
 - [ ] `*api.RouteList`
 - [ ] `*api.SecretList`
 - [ ] `*api.SecurityContextConstraintsList`
 - [ ] `*api.ServiceAccountList`
 - [ ] `*api.ServiceList`
 - [ ] `cache.Deltas`
 - [ ] `*extensions.DaemonSetList`
 - [ ] `*extensions.DeploymentList`
 - [ ] `*extensions.HorizontalPodAutoscalerList`
 - [ ] `*extensions.IngressList`
 - [ ] `*extensions.JobList`
 - [ ] `*extensions.PodSecurityPolicyList`
 - [ ] `*extensions.ReplicaSetList`
 - [ ] `*extensions.ThirdPartyResourceList`
 - [ ] `*rest.ConnectRequest`
 - [ ] `*rest.LocationStreamer`
 - [ ] `*runtime.Unstructured`
 - [ ] `*unversioned.Status`

/cc @liggitt

**Comment by stevekuznetsov** [comment]
Follow-up to https://github.com/openshift/origin/issues/9249

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/pull/26964

**Comment by stevekuznetsov** [comment]
Will be fixed by bringing in https://github.com/kubernetes/kubernetes/pull/27168
