### ISSUE TITLE
Confusing highlight color

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#9253]
Hovering over a pod in _not ready_ state (lighter color, left side of the circle) changes the color of the _running_ pod (darker color, right side) to a tone that is the same or too similar to the _not ready_ pod.

![selection_034](https://cloud.githubusercontent.com/assets/88819/15933075/8fa22dae-2e5e-11e6-9cc3-5fac1a80394b.png)

![selection_036](https://cloud.githubusercontent.com/assets/88819/15933085/95fb838a-2e5e-11e6-8bd5-e4d3e06e0c6c.png)

The color choice is confusing, specially after I noticed that when all pods are _running_, the color doesn't seem to change on hover:

![selection_035](https://cloud.githubusercontent.com/assets/88819/15933194/193aaee2-2e5f-11e6-861e-e124583846cf.png)
##### Version

```
$ openshift version
openshift v1.3.0-alpha.1-29-gc776209-dirty
kubernetes v1.3.0-alpha.1-331-g0522e63
etcd 2.3.0
$ oc version
oc v1.3.0-alpha.0-589-g9f0daf8-dirty
kubernetes v1.3.0-alpha.1-331-g0522e63
```
##### Steps To Reproduce
1. Deploy some image that takes some time to be in _ready_ state. This can be accomplished adding a readinessProbe with an initial delay.
2. Scale up
3. Hover over the pod pie chart in the overview tab
##### Current Result

Hovering over a _not ready_ pod changes the color of the rest of the pie chart, making the color of the _running_ pod lighter, much similar to _no ready_.
##### Expected Result

There should be no color change on hover, just like no color changes when all pods are _running_, or at least the colors shouldn't be so similar.

**Comment by jwforres** [comment]
Yeah that definitely wasn't intentional, the hover states are being done automatically by c3 by lightening whatever color the arc is by some set amount. @spadgett we may need to either tweak the Not Ready color or look at adjusting how much it fades the non-focused arcs.
