### ISSUE TITLE
fix up Endpoint filtering for multitenant isolation

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#9255]
(This has been discussed in passing in various PRs but never had its own PR/issue...)

To ensure multitenant isolation, we have to ensure that all of a service's endpoints point to pods in the same namespace as the service itself. (This is because traffic coming out of the service proxy [kube-proxy / iptables rules] will at least in some cases have lost its original source IP address, so we have no way to verify that isolation is occurring properly at that point, so we have to set things up so that we already know that if the traffic was isolated correctly going into the service, then it is still isolated correctly coming out.)

Currently we do this by filtering the list of endpoints before they get passed to the kube-proxy code (to make sure that malicious users haven't manually created Endpoint objects pointing to other users' pods), but this has various problems, such as the fact that it requires each node to keep a full IP-address-to-namespace mapping table for the entire cluster.

It seems to me like there's no good reason to allow users to manually create Endpoint objects with destination IPs inside the cluster IP space: the whole point of services is to abstract around the fact that pod IPs are not stable, so creating a service with a manually-specified pod IP is silly.

If we decide we don't need to let users manually create Endpoints with cluster-internal destination IPs, then we can solve our problem by adding admission control or whatever on Endpoints so that only kubernetes itself can create Endpoints pointing into the cluster IP space, and then we can drop the endpoint filtering code. (Though we have to re-validate all endpoints at startup time if ClusterNetworkCIDR changes.)

(If we do need to let users manually create Endpoints with cluster-internal IPs, then we have to continue doing the filtering at iptables-rule-creation time rather than at Endpoint-admission time, because the IP-to-namespace mapping isn't stable and an Endpoint that is valid when it is created can suddenly become invalid later after the pod it pointed to exits and its IP is reused. In this case maybe we could just do the filtering on the master rather than on every node, and have kube-proxy fetch endpoints from a virtual "FilteredEndpoints" API rather than looking at the full list of Endpoints.)

@smarterclayton @openshift/networking

**Comment by danwinship** [comment]
> I would recommend we go a bit further than just cluster network and service network, because I suspect that there will be other IP blocks that may be accessible to nodes but not to pods.

But presumably they'd want to block direct connections to those IPs too, not just indirect-via-service connections. So that's more like https://github.com/openshift/openshift-sdn/pull/319 / https://github.com/openshift/origin/pull/9227. (Which currently doesn't deal with services/endpoints. Doh.)

> If we add referential services (DNS resolution of a name to endpoint IPs) we'd have to figure out how to control that as well

Ugh. Hm. Maybe the answer is really that we need to figure out a way to preserve the source VNID when going through the service proxy, so that we can then reliably filter the traffic by namespace on pod ingress.

**Comment by danwinship** [comment]
OK, if we require new-enough iptables/kernel stuff (which RHEL has had since 7.0), we can make kubernetes use connlabel rather than fwmark for its internal marking of packets that need to be NATted. That then frees up the 32-bit fwmark to be used to track the VNID; we can set it from OVS (as `pkt_mark`) before passing the data to iptables, and then read it back when the connection comes back in (and if using the userspace proxy, it can copy it from the incoming to the outgoing connection via the `SO_MARK` sockopt). Then we don't need to worry about any sort of Endpoint filtering, because the source VNID would be preserved all the way to the final destination in all situations, and then the ordinary isolation rules will handle it.

(This would also solve the egress firewall problem because if iptables has access to the VNID via fwmark then we can just do the firewall rules in iptables rather than OVS.)

**Comment by dcbw** [comment]
@danwinship that sounds like a novel solution actually.  Not sure we can do that upstream though, since tons of people (including GCE) are still running on really old 3.16 Ubuntu kernels.  But maybe we could make it an upstream option in the kube iptables stuff.

**Comment by danwinship** [comment]
It would be easy to make it so that we preserved the mark through the proxy codepaths if you have new-enough kernel/iptables/whatever, and not if you don't. And then just say openshift-sdn isn't supported on older systems. (I don't know exactly what is and isn't supported yet. The iptables-extensions man page just says that you need libnetfilter_conntrack 1.0.4 or later.)

**Comment by danwinship** [comment]
> we can make kubernetes use connlabel rather than fwmark for its internal marking of packets that need to be NATted. That then frees up the 32-bit fwmark to be used to track the VNID

OK, actually kubernetes used to use the whole mark, but it only uses 1 bit of it now, and VNIDs are only 24 bits, so we can share the fwmark between kubernetes and openshift-sdn and not need to add any connlabel code. (There's a config option to set which bit kubernetes uses. We just need to override the default value, and require that it be >= 24 when using openshift-sdn.)

> we can set it from OVS (as pkt_mark) before passing the data to iptables, and then read it back when the connection comes back in

This appears to work!

> (and if using the userspace proxy, it can copy it from the incoming to the outgoing connection via the SO_MARK sockopt).

Unfortunately, this will be a bit trickier: `net.Dial()` doesn't give you any way to set sockopts on the socket until after connecting, but we won't be able to establish the connection without setting the right mark value on the SYN. So we'd have to rewrite the userspace proxy code to do the connection with raw sockets API via the syscall package. Though given that we only have to support Linux, and only have to support a limited amount of functionality, this wouldn't be awful. Though upstream might not want the change since kubernetes itself wouldn't be making use of the feature that it adds. (Though it's possible other network plugins could benefit from this as well...)

(Redoing the userspace proxy with syscalls and fds also ties into the idea of porting it to use zero-copy I/O (https://trello.com/c/L4nqD8cl), though that only requires using syscalls and fds *after* connecting, so it doesn't give us an upstreamable excuse for the rest of the syscalls.)

**Comment by smarterclayton** [comment]
So realistically for the 1.3 timeframe do we understand enough of the
implementation on the node side that we can guarantee we can deliver?  If
not, I'd want to do both approaches to ensure we land with something.
Certainly the node side is the correct long term solution, but you guys
will have to help me understand whether it's understood enough to commit to.

**Comment by danwinship** [comment]
OK, my idea for using `SO_MARK` to preserve the VNID through the userspace proxy doesn't work, because `SO_MARK` is actually write-only. There doesn't seem to be any way to discover the fwmark value on incoming traffic from userspace, nor do there seem to be any other spare bits we could use for this (at least under IPv4). So that plan is dead for now at least.

So we're back to the admission control approach, although I still have to figure out how to solve the service endpoints vs egress firewall problem too.
