### ISSUE TITLE
Deployment Hook Status Reporting

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#9260]
We need a convenient way to see if a hook is running for a deployment and which hook it is.  Right now you can see if a pod exists with the deployment name and the suffix but that is not a great way to find out the deployment status.

Since the hook go through an executor maybe we could update status for the deployment there.  We should also consider emitting an event.

@kargakis @jwforres @ironcladlou @mfojtik

**Comment by kargakis** [comment]
Events on the hook executor is a good idea. I have also been thinking about having not only the hooks but also the deployer to have the dc status updated. We will probably need to do it either in https://github.com/openshift/origin/pull/6233 or as a follow-up.

**Comment by kargakis** [comment]
> but also the deployer to have the dc status updated

Actually this won't be needed with https://github.com/openshift/origin/pull/9002
* Deployer pod updates deployment
* DC controller notices deployment update, resyncs parent config
* Profit

**Comment by mfojtik** [comment]
@kargakis do we still think the event is a good idea? I can add one there.

**Comment by mfojtik** [comment]
actually, the hook executor is running independently from the controller, so I don't think we can emit events here.

**Comment by kargakis** [comment]
Yes, events on the hook executor are fine. Not sure if we can enhance the config status to reflect running hooks but that's something we should do upstream first.

**Comment by mfojtik** [comment]
@kargakis I think events are fine, not sure if we need to update the status, if you want to know when the hooks run, you can just watch the events.

**Comment by kargakis** [comment]
@mfojtik for now yes. Updating the status is an API change that we may want to consider after we move hooks upstream.
