### ISSUE TITLE
A binary build should not be triggered if no binary input is passed with the possible flags

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#9261]
I have created a binary build and started a build without any flag:

````
oc new-project binary-build
oc new-build --image-stream=wildfly --binary=true --name=myapp
oc start-build bc/myapp
````

The build stays active forever waiting to receive source from STDIN.

````
The value of ALLOWED_UIDS is [1-]
The value of DROP_CAPS is [KILL,MKNOD,SETGID,SETUID,SYS_CHROOT]
I0609 20:55:58.429763       1 docker.go:355] Image "openshift/wildfly-100-centos7@sha256:32ab41e7821ccf1e769f1bdea771e8f5b86d7fde83cce9015fde32b773577b04" not available locally, pulling ...
Creating a new S2I builder with build config: "Builder Name:\t\t\tWildFly 10.0.0.Final\nBuilder Image:\t\t\topenshift/wildfly-100-centos7@sha256:32ab41e7821ccf1e769f1bdea771e8f5b86d7fde83cce9015fde32b773577b04\nBuilder Image Version:\t\t3caa958\nBuilder Base Version:\t\t6158a36\nSource:\t\t\t\tfile:///tmp/s2i-build122254063/upload/src\nOutput Image Tag:\t\tbinary-build/myapp-1:010d881c\nEnvironment:\t\t\tOPENSHIFT_BUILD_NAME=myapp-1,OPENSHIFT_BUILD_NAMESPACE=binary-build\nIncremental Build:\t\tdisabled\nRemove Old Build:\t\tdisabled\nBuilder Pull Policy:\t\tif-not-present\nPrevious Image Pull Policy:\talways\nQuiet:\t\t\t\tdisabled\nLayered Build:\t\t\tdisabled\nWorkdir:\t\t\t/tmp/s2i-build122254063\nDocker NetworkMode:\t\tcontainer:ba2ccea7dcbcb262c81cc2288136ff4a1f8138c948065776c34f41c7d7c6be16\nDocker Endpoint:\t\tunix:///var/run/docker.sock\n"
Receiving source from STDIN as archive ...
````
##### Version
$ oc version
oc v1.3.0-alpha.1
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Expected Result
Error message saying that the build is binary, and a binary should be provided by any of the possible flags. (--from-file, --from-dir, --from-repo)

**Comment by helio-frota** [comment]
Hi folks, I'm not sure if it is related but the build is running here to 55+ minutes.

```
mkdir foo
cd foo 
npm init
touch index.js
echo "console.log('foo');" > index.js
oc new-app .
```

```
--> Found image a1ef33b (3 weeks old) in image stream "nodejs" in project "openshift" under tag "0.10" for "nodejs"

    Node.js 0.10 
    ------------ 
    Platform for building and running Node.js 0.10 applications

    Tags: builder, nodejs, nodejs010

    * The source repository appears to match: nodejs
    * A source build using binary input will be created
      * The resulting image will be pushed to image stream "nodejs:latest"
    * This image will be deployed in deployment config "nodejs"
    * Port 8080/tcp will be load balanced by service "nodejs"
      * Other containers can access this service through the hostname "nodejs"

--> Creating resources with label app=nodejs ...
    imagestream "nodejs" created
    buildconfig "nodejs" created
    deploymentconfig "nodejs" created
    service "nodejs" created
--> Success
    Use 'oc start-build nodejs' to start a build.
    Run 'oc status' to view your app.
```

```
oc start-build nodejs
```

The log is showing :

```
I0630 17:42:05.893254 1 docker.go:351] Image "registry.access.redhat.com/openshift3/nodejs-010-rhel7:latest" not available locally, pulling ...
I0630 17:49:33.618577 1 source.go:180] Receiving source from STDIN as archive ...
```

still running for one hour, 37 seconds

**Comment by bparees** [comment]
@helio-frota can you share your buildconfig json definition?

**Comment by bparees** [comment]
and is "." that you ran new-app against a git repo?  and does it have a remote setup?

**Comment by jorgemoralespou** [comment]
I think the problem is expecting binary input provided but as no flag was
specified the build is waiting the binary content to be streamed into the
builder but that will never happen. This is the dame reason why I opened
the issue.
El 30 jun. 2016 8:57 PM, "Ben Parees" <notifications@github.com> escribió:

and is "." that you ran new-app against a git repo? and does it have a
remote setup?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9261#issuecomment-229848460>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAEyDhWAnjqhI9N2t-L0z6-ZLHcY-2KXks5qRJAMgaJpZM4IyZms>
.

**Comment by bparees** [comment]
yes @jorgemoralespou i agree, but i wanted to see the buildconfig in question to confirm that.

**Comment by helio-frota** [comment]
@bparees hi

the generated config :

```
apiVersion: v1
kind: BuildConfig
metadata:
  name: nodejs
  namespace: bgold
  selfLink: /oapi/v1/namespaces/bgold/buildconfigs/nodejs
  uid: 84e9ec6b-3f87-11e6-be82-525400edfb27
  resourceVersion: '7887'
  creationTimestamp: '2016-07-01T12:29:56Z'
  labels:
    app: nodejs
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: qFaYet_HcXF6IE82EVgt
    -
      type: Generic
      generic:
        secret: LjoK0jS9P2QFg6yGON3Y
  source:
    type: Binary
    binary: {  }
    secrets: []
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:0.10'
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs:latest'
  resources: {  }
  postCommit: {  }
status:
  lastVersion: 1
```

the "." is just a new created directory with index.js and package.json but have no git initialized.

**Comment by bparees** [comment]
yeah so this is the same issue.  you are configured to run a binary build, but you did not invoke oc start-build with a "--from-XXX" argument, which is needed to provide the binary content.

we will fix this issue by returning an error when users do this.

**Comment by helio-frota** [comment]
@bparees thanks ! this will help.

![c](https://cloud.githubusercontent.com/assets/6443576/16522901/dd4a562a-3f76-11e6-8f0c-a056f378dbd2.png)

I'm following this documentation: https://docs.openshift.org/latest/dev_guide/new_app.html

**Comment by bparees** [comment]
@helio-frota the key bit of data from that example is: "To Create an Application Using the Git Repository at the Current Directory:"

since you don't have a git repository, new-app defaulted to using a binary build instead, which is where your troubles started.  We need to also make the new-app output clearer that hat you need to run the build is "oc start-build --from-dir=." not just "oc start-build"

**Comment by helio-frota** [comment]
@bparees great, thanks.

**Comment by jorgemoralespou** [comment]
@benparees I think it would be useful if in the output from new-app there
was an indication of the type of the buildconfig created.

And then when it says " Use oc start-build nodejs" would say something like
"oc start-build nodejs --from-dir=."

As I guess the bigger problem is the instructions we're giving are wrong.

@helio-frota <https://github.com/helio-frota> the key bit of data from that
example is: "To Create an Application Using the Git Repository at the
Current Directory:"

since you don't have a git repository, new-app defaulted to using a binary
build instead, which is where your troubles started. We need to also make
the new-app output clearer that hat you need to run the build is "oc
start-build --from-dir=." not just "oc start-build"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9261#issuecomment-229948469>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAEyDqYEwqAeP1qaGONBtU-2kNhxTiW7ks5qRRgXgaJpZM4IyZms>
.

**Comment by bparees** [comment]
> @benparees I think it would be useful if in the output from new-app there was an indication of the type of the buildconfig created.

there is.  ` * A Docker build using binary input will be created` and `* A source build using binary input will be created`

> And then when it says " Use oc start-build nodejs" would say something like "oc start-build nodejs --from-dir=."

it does for docker build, for some reason it does not for source build and i will be fixing that as part of this:

```
* A Docker build using binary input will be created
      * The resulting image will be pushed to image stream "centos:latest"
      * Use 'start-build --from-dir=DIR' to trigger a new build
```

**Comment by jorgemoralespou** [comment]
@bparees yep and still you asked for the buildconfig to confirm 😉

**Comment by bparees** [comment]
@jorgemoralespou i didn't read the new-app output closely enough or i would not have.

**Comment by bparees** [comment]
@jorgemoralespou what part of:
```
We need to also make the new-app output clearer that hat you need to run the build is "oc start-build --from-dir=." not just "oc start-build"
```
is leaving you still unsatisfied with my responses on this issue that we are still discussing it?

**Comment by jorgemoralespou** [comment]
@bparees not arguing or discussing. This time I'm satisfied.

**Comment by bparees** [comment]
note that because we actually allow source-strategy and custom-strategy builds to be run with no source inputs (because they can provide their own inputs, eg an assemble script that downloads source), the fix for this will NOT report an error if you run "oc start-build mybinarysourcestrategybuild", it will kick off a build, however that build will fail quickly if the assemble script can't tolerate the lack of provided source code.  that is up to the builder image.

for docker-type builds, the user will immediately be informed they have made an invalid request.

but regardless the builds will no longer hang indefinitely.
