### ISSUE TITLE
Origin-node unable to tear down Orphaned Volumes with 'device or resource busy' when attempting rename

### ISSUE THREAD

**Issue by jameswilkins** [openshift/origin#9268]
Origin-node unable to tear down Orphaned volumes with 'device or resource busy' when attempting rename

Jun 10 09:38:00 master02 origin-node: W0610 09:38:00.996811 49602 kubelet.go:2001] Orphaned volume "4ad107b1-2e4a-11e6-af02-001dd8f01d98/deployer-token-zg6fl" found, tearing down volume
Jun 10 09:38:01 master02 origin-node: E0610 09:38:01.004894 49602 kubelet.go:2012] Could not tear down volume "4ad107b1-2e4a-11e6-af02-001dd8f01d98/deployer-token-zg6fl": rename /var/lib/origin/openshift.local.volumes/pods/4ad107b1-2e4a-11e6-af02-001dd8f01d98/volumes/kubernetes.io~secret/deployer-token-zg6fl /var/lib/origin/openshift.local.volumes/pods/4ad107b1-2e4a-11e6-af02-001dd8f01d98/volumes/kubernetes.io~secret/wrapped_deployer-token-zg6fl.deleting~884469099: device or resource busy
Jun 10 09:38:01 master02 origin-node: W0610 09:38:01.004932 49602 kubelet.go:2001] Orphaned volume "e7718fde-2e43-11e6-af02-001dd8f01d98/server-certificate" found, tearing down volume
Jun 10 09:38:01 master02 origin-node: E0610 09:38:01.013363 49602 kubelet.go:2012] Could not tear down volume "e7718fde-2e43-11e6-af02-001dd8f01d98/server-certificate": rename /var/lib/origin/openshift.local.volumes/pods/e7718fde-2e43-11e6-af02-001dd8f01d98/volumes/kubernetes.io~secret/server-certificate /var/lib/origin/openshift.local.volumes/pods/e7718fde-2e43-11e6-af02-001dd8f01d98/volumes/kubernetes.io~secret/wrapped_server-certificate.deleting~015162830: device or resource busy
Jun 10 09:38:01 master02 origin-node: W0610 09:38:01.013402 49602 kubelet.go:2001] Orphaned volume "f3c53792-2edc-11e6-ae12-001dd8f01d98/wrapped_deployer-token-yorff.deleting~663380775" found, tearing down volume
Jun 10 09:38:01 master02 origin-node: W0610 09:38:01.018617 49602 mount.go:99] could not determine device for path: "/var/lib/origin/openshift.local.volumes/pods/f3c53792-2edc-11e6-ae12-001dd8f01d98/volumes/kubernetes.io~secret/wrapped_deployer-token-yorff.deleting~663380775"
##### Version

openshift v1.3.0-alpha.1
kubernetes v1.3.0-alpha.1-331-g0522e63
etcd 2.3.0
##### Steps To Reproduce

Cluster deployed via openshift-ansible with containizered=true
Deploy registry/router and test/sample app
Delete sample app
Warnings/Errors seen as per above in log
##### Current Result

Orphaned volume is not cleaned up due to failed rename
##### Expected Result

Orphaned volume is cleaned up
##### Additional Information

I've found this issue logged against Kubernetes which may be related? https://github.com/kubernetes/kubernetes/issues/22911

Lower down it's mentioned with ref to the rename failing due to fixing a bug in isLikleyNotMountPoint when attempting rename

**Comment by jameswilkins** [comment]
Little bit more information if it helps as we're still struggling with this one.

I updated one of the node to latest for origin-node and we're still seeing the issue (containrised model)

If i grab the rename its trying to do

[root@node01 /]# mv /var/lib/origin/openshift.local.volumes/pods/72942c0e-3783-11e6-b29a-001dd8f01d93/volumes/kubernetes.io~secret/dockercfg /var/lib/origin/openshift.local.volumes/pods/72942c0e-3783-11e6-b29a-001dd8f01d93/volumes/kubernetes.io~secret/wrapped_dockercfg.deleting~938505827

mv: cannot move ‘/var/lib/origin/openshift.local.volumes/pods/72942c0e-3783-11e6-b29a-001dd8f01d93/volumes/kubernetes.io~secret/dockercfg’ to ‘/var/lib/origin/openshift.local.volumes/pods/72942c0e-3783-11e6-b29a-001dd8f01d93/volumes/kubernetes.io~secret/wrapped_dockercfg.deleting~938505827’: **Device or resource busy**

**Comment by ingvagabund** [comment]
@jameswilkins thanks for additional info

**Comment by xiaoping378** [comment]
My workaround
```
mount | grep openshift | awk '{print $3}' | sudo xargs umount
```
