### ISSUE TITLE
base_ami failing due to `oc ex dockerbuild` image name regex failures

### ISSUE THREAD

**Issue by danmcp** [openshift/origin#9269]
https://ci.openshift.redhat.com/jenkins/job/base_ami/1990/console
```
Stdout from the command:

Building base images...
/data/src/github.com/openshift/origin ~
++ Building go targets for linux/amd64: cmd/oc
++ Placing binaries
/data/src/github.com/openshift/origin/hack/build-go.sh took 124 seconds


Stderr from the command:

--> Image centos:centos7 was not found, pulling ...
error: API error (500): repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
!!! Error in hack/build-base-images.sh:28
	'"${oc}" ex dockerbuild $2 $1' exited with status 1
Call stack:
	1: hack/build-base-images.sh:28 build(...)
	2: hack/build-base-images.sh:32 main(...)
Exiting with status 1
Build step 'Execute shell' marked build as failure
```

**Comment by smarterclayton** [comment]
Hrm, thought we solved this.

**Comment by danmcp** [comment]
https://ci.openshift.redhat.com/jenkins/job/base_ami/2023/console

**Comment by danmcp** [comment]
https://ci.openshift.redhat.com/jenkins/job/devenv_ami/4598/console

**Comment by danmcp** [comment]
@jwforres @stevekuznetsov This appears to be totally blocking pushing images.

**Comment by stevekuznetsov** [comment]
@smarterclayton do you have bandwidth to look at this today?

**Comment by smarterclayton** [comment]
Can you print out the arguments to oc ex dockerbuild and turn on loglevel=5?

**Comment by stevekuznetsov** [comment]
Is there a simple way to do that from inside the command or are we going to have to do that for every call in our scripts?

**Comment by danmcp** [comment]
Just got this one this morning: https://ci.openshift.redhat.com/jenkins/job/devenv_ami/4660/console

**Comment by smarterclayton** [comment]
That's a different bug.

**Comment by danmcp** [comment]
@smarterclayton I can open a new issue then.  Who should be the owner?

**Comment by smarterclayton** [comment]
Definitely not the scratch issue.

**Comment by stevekuznetsov** [comment]
@smarterclayton I'm seeing this in the log:
```
Building base images...
/data/src/github.com/openshift/origin ~
--> Image centos:centos7 was not found, pulling ...
error: API error (500): repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
[ERROR] PID 2624: hack/build-base-images.sh:27: `'/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc' ex dockerbuild /data/src/github.com/openshift/origin/images/base openshift/origin-base` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/build-base-images.sh:27: `'/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc' ex dockerbuild /data/src/github.com/openshift/origin/images/base openshift/origin-base`
[INFO] 		  2: hack/build-base-images.sh:31: build
[INFO]   Exiting with code 1.
```
 Why is that a different issue than this one? The failure cause for this one picks it up.

**Comment by smarterclayton** [comment]
No it's fine - it's same symptom (so title is correct), just different
place it's failing

**Comment by smarterclayton** [comment]
Docker 1.9 has different PullImage semantics in the API - it looks like a
call that works in Docker 1.10 fails in 1.9 and vice versa.  Good to know...
