### ISSUE TITLE
mysql_replica.go extended test broken (consistently, not flake)

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#9274]
With both local runs and on the jenkins origin_extended_image_tests job, the tests in mysql_replica.go are failing to deploy both the mysql_master and mysql_slave pods.

For each, you'll see these events during failure processing:

`Jun 10 05:44:01.398: INFO: At 2016-06-10 05:41:20 -0400 EDT - event for mysql-master-1-6dnsu: {default-scheduler } FailedScheduling: PersistentVolumeClaim is not bound: "mysql-master"`

`Jun 10 05:44:01.398: INFO: At 2016-06-10 05:41:22 -0400 EDT - event for mysql-slave-1-0alpl: {default-scheduler } FailedScheduling: PersistentVolumeClaim is not bound: "mysql-slave"`

Later on, the mysql-helper will fail the readiness probe with that benign ioctl message we've seen, but I now believe based on some dumping of the pod logs that the helper is continually trying to connect to the master (`oc logs` though from the extended tests hangs as the helper thrashes, and you have to send the extended test a signal to get the helper pod log output).

`oc log` of the master/slave pods returned nothing.  However, some dumping of the json of those pod API objects periodically while this was going on, the json showed that those Pods stayed in Pending state.  Given the `FailedScheduling` events that ultimately occur, that would seem to make sense.

So it would *appear* at least that the PVC not bound item and the failure to schedule is the root cause, but of course I'll ultimately defer to those more knowledgeable about our mysql stuff.

@bparees @mnagy FYI

**Comment by bparees** [comment]
PVC not bound definitely seems bad.  @mnagy is definitely the resident guru on this test though, so assigning to him to dig into it.

**Comment by bparees** [comment]
looks like this was fixed by https://github.com/openshift/origin/pull/9458

**Comment by mnagy** [comment]
Yes, that was it, sorry, I forgot to link the issue in the PR.
