### ISSUE TITLE
OpenShift: Could not transfer artifact or g.flywaydb:flyway-core:jar:4.0.2 from/to nexus

### ISSUE THREAD

**Issue by instantiationexception** [openshift/origin#9287]
I had new Java application on OpenShift (**which worked**) but wanted to upgrade gear to Small.highcpu. Because it was new application I removed it and created new and force pushed code to new application repo. During building I get an error:

    remote: Downloading: http://mirror.ops.rhcloud.com/nexus/content/groups/public/o
    rg/webjars/normalize.css/3.0.2/normalize.css-3.0.2.jar
    remote: Downloaded: http://mirror.ops.rhcloud.com/nexus/content/groups/public/co
    m/google/guava/guava/19.0/guava-19.0.jar (2255 KB at 4976.6 KB/sec)
    remote: Downloaded: http://mirror.ops.rhcloud.com/nexus/content/groups/public/or
    g/webjars/normalize.css/3.0.2/normalize.css-3.0.2.jar (6 KB at 269.6 KB/sec)
    remote: Downloaded: http://mirror.ops.rhcloud.com/nexus/content/groups/public/or
    g/hibernate/hibernate-core/4.3.7.Final/hibernate-core-4.3.7.Final.jar (5146 KB a
    t 4506.0 KB/sec)
    remote: Downloaded: http://mirror.ops.rhcloud.com/nexus/content/groups/public/or
    g/apache/derby/derby/10.11.1.1/derby-10.11.1.1.jar (3031 KB at 8146.2 KB/sec)
    remote: [INFO] -----------------------------------------------------------------
    -------
    remote: [INFO] BUILD FAILURE
    remote: [INFO] -----------------------------------------------------------------
    -------
    remote: [INFO] Total time: 1:06.232s
    remote: [INFO] Finished at: Sat Jun 11 16:21:58 EDT 2016
    remote: [INFO] Final Memory: 8M/161M
    remote: [INFO] -----------------------------------------------------------------
    -------
    remote: [ERROR] Failed to execute goal on project quloo: Could not resolve depen
    dencies for project quloo:quloo:war:1.0-SNAPSHOT: Could not transfer artifact or
    g.flywaydb:flyway-core:jar:4.0.2 from/to nexus (http://mirror.ops.rhcloud.com/ne
    xus/content/groups/public): Failed to transfer file: http://mirror.ops.rhcloud.c
    om/nexus/content/groups/public/org/flywaydb/flyway-core/4.0.2/flyway-core-4.0.2.
    jar. Return code is: 504, ReasonPhrase:GATEWAY_TIMEOUT. -> [Help 1]
    remote: [ERROR]
    remote: [ERROR] To see the full stack trace of the errors, re-run Maven with the
     -e switch.
    remote: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    remote: [ERROR]
    remote: [ERROR] For more information about the errors and possible solutions, pl
    ease read the following articles:
    remote: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/Depend
    encyResolutionException
    remote: An error occurred executing 'gear postreceive' (exit code: 1)
    remote: Error message: CLIENT_ERROR: Failed to execute: 'control build' for /var
    /lib/openshift/575c70b72d527184f200000a/wildfly
    remote:
    remote: For more details about the problem, try running the command again with t
    he '--trace' option.
    To ssh://575c70b72d527184f200000a@qulooprod-acepl.rhcloud.com/~/git/qulooprod.gi
    t/
     + 5d1847c...ec631e2 master -> master (forced update)

I created new app many times and pushed code but still get this error.
Is it temporary OpenShift issue or I have an error in my app?

##### Version
openshift version 2 origin

##### Steps To Reproduce
Create application with this pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>quloo</groupId>
    <artifactId>quloo</artifactId>
    <packaging>war</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>quloo</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.wildfly.bom</groupId>
                <artifactId>jboss-javaee-7.0-with-hibernate</artifactId>
                <version>8.2.1.Final</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <version>5.3</version>
        </dependency>
        <dependency>
            <groupId>org.omnifaces</groupId>
            <artifactId>omnifaces</artifactId>
            <version>2.3</version>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-entitymanager</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-jpamodelgen</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>4.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.rjeschke</groupId>
            <artifactId>txtmark</artifactId>
            <version>0.13</version>
        </dependency>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>0.7</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-library</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>1.10.19</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.el</artifactId>
            <version>3.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.derby</groupId>
            <artifactId>derby</artifactId>
            <version>10.11.1.1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>normalize.css</artifactId>
            <version>3.0.2</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <!-- When built in OpenShift the 'openshift' profile will be used when invoking mvn. -->
            <!-- Use this profile for any OpenShift specific customization your app will need. -->
            <!-- By default that is to put the resulting archive into the 'deployments' folder. -->
            <!-- http://maven.apache.org/guides/mini/guide-building-for-different-environments.html -->
            <id>openshift</id>
            <build>
                <finalName>quloo</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-war-plugin</artifactId>
                        <version>2.3</version>
                        <configuration>
                            <failOnMissingWebXml>false</failOnMissingWebXml>
                            <outputDirectory>deployments</outputDirectory>
                            <warName>ROOT</warName>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>

```
##### Current Result
Project doesn't deploy.

##### Expected Result
Project  should deploy.

##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by danmcp** [comment]
Please open this as a bug here:

https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Online

Sorry for the inconvenience.
