### ISSUE TITLE
clusterrolebindings/system:registrys

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9288]
Really?

**Comment by smarterclayton** [comment]
Also: clusterrolebindings/registry-registry-role

**Comment by deads2k** [comment]
> Also: clusterrolebindings/registry-registry-role

I'm not seeing that one.

Also, why don't we have a pluralization library?

**Comment by liggitt** [comment]
>> Also: clusterrolebindings/registry-registry-role
>
> I'm not seeing that one.

https://github.com/openshift/origin/blame/master/pkg/cmd/admin/registry/registry.go#L372
