### ISSUE TITLE
ClusterPolicy updates are not idempotent due to lastModification

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9290]
The presence of the lastModified value on a ClusterPolicy and ClusterPolicyBinding prevents non-mutating writes from being suppressed, thus leading to higher than necessary event propagation in the cluster and prevents migrations from being communicated correctly as being idempotent.

The mutation logic should check the difference between old and new before incrementing the modification timestamp.

Putting P1 for triage right now because every storage migration results in a mutation.

**Comment by deads2k** [comment]
You were the only one who wanted it, can I remove it?

**Comment by smarterclayton** [comment]
If we haven't been asked for it it's fine to remove.  Dropping is cheaper
and we may want to readd with kube in general.

**Comment by deads2k** [comment]
We may still fail to get idempotent updates due to backing the policy object by a map.

These are rarely updated objects, are they really p1s?

**Comment by smarterclayton** [comment]
Migration updates them, and EVERY single one is listed as modified, which
means that an admin runs a migration and every time it says it's changed.
So yes.

**Comment by smarterclayton** [comment]
If map order is unstable we'll look at that afterwards.  Ugorji has a
stable order, but I don't know if the default JSON does.

**Comment by smarterclayton** [comment]
lowering priority
