### ISSUE TITLE
Deployment controller need not relist

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9292]
Both the deployer pod and deployment controllers need to respond only in watch events and once deployments and deployer pods are transitioned to terminal states there is no need to resync again.

@smarterclayton @ironcladlou @mfojtik

**Comment by kargakis** [comment]
Or at least they should have a much higher resynv interval

**Comment by smarterclayton** [comment]
Yeah, we've fixed all the known "lost update" problems now?

**Comment by kargakis** [comment]
> all the known "lost update" problems

Are these "lost updates" on the replication controller? If we move to a single point of updates (deployment controller) instead of two (deployment controller, deployer pod controller) we can retry updates.

**Comment by smarterclayton** [comment]
Effectively yes.  Is that slated for 1.3?

**Comment by kargakis** [comment]
Nah, more like 1.4.

**Comment by kargakis** [comment]
@mfojtik for 1.3 we removed the deployer pod controller, for 1.3.1 we want to add the retry mechanism you added in the deploymentconfig controller here as well and bump the resync interval of the deployment controller to something higher.

**Comment by mfojtik** [comment]
@kargakis still an issue?

**Comment by kargakis** [comment]
Yes
