### ISSUE TITLE
Adding context to a build web-ui does not expand the fold

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#9297]
When going through the jboss-webserver30-tomcat8-openshift "add to project" the try it link suggests a git URL. WHen you click it, it adds the git url to the box and it adds the context down below. The problem is that the user has no way of seeing that something was actually added below. 
##### Version

Tested this on Online preview. 
##### Steps To Reproduce
1. Add jboss-webserver30-tomcat8-openshift to a project
2. Click the try it link
##### Current Result

It adds the context in the advanced options but the user never sees that it happened
##### Expected Result

Advanced results should open so I can see that the field was filled in.

What I got

http://i.imgur.com/yNkmd6A.png

What I want

http://i.imgur.com/aIfGSoE.png

**Comment by sspeiche** [comment]
I'd agree that the other values should be made more obvious. I'm not sure if expanding the full advanced options is necessarily the right fix, be good to hear others opinion.

**Comment by spadgett** [comment]
In the wizard prototype for https://trello.com/c/IChnzwgW, we had a separate page for source options and wouldn't have to expand the entire advanced section.
