### ISSUE TITLE
Move `oc deploy` in `oc rollout`

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9298]
https://github.com/openshift/origin/pull/8927 adds support for `rollout`, the command used by Kubernetes to manage deployments. We need to move bits from `oc deploy` in rollout subcommands.

`oc deploy --latest` to `oc rollout again`
`oc deploy --latest` (as it should work) to `oc rollout latest`

If anybody can come up with more appropriate names, please do so.

Before we add those, I am going to create an /instantiate endpoint that can be used by both `oc deploy --latest` and the rollout subcommands (and every other client for that matter). Not sure if there is any benefit in waiting for this to be added upstream, it seems that pros outweight cons at this point for having it.

I still need to think about the rest. Both `oc deploy --cancel` and `oc deploy --retry` are OpenShift-specific at this point and we still need to add perm-failed (https://github.com/kubernetes/kubernetes/issues/14519) upstream and then get back to those. `--enable-triggers` is OS-specific atm but will work for both too.

@fabianofranz @ironcladlou @mfojtik @smarterclayton

**Comment by kargakis** [comment]
Last pieces left here:

* deploy --cancel to `rollout cancel` - https://github.com/openshift/origin/pull/10731
* `deploy --retry` to `rollout retry` (@mfojtik do you want this or should I open a PR for retry?)

**Comment by mfojtik** [comment]
@kargakis i will do it.
