### ISSUE TITLE
[oc start-build] numbers builds incorrectly which results in error while creating them

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#9301]
`oc start-build` numbers builds incorrectly which results in error while creating them. It happens only if you use different machines for calling `oc start-build`.

Jenkins:
```
[test2] Running shell script
+ ./oc get builds
NAME           TYPE      FROM      STATUS     STARTED       DURATION
helloworld-1   Source    Binary    Complete   2 hours ago   5m23s
+ ./oc start-build helloworld --from-dir=../artifacts/ --follow
Uploading "../artifacts" at commit "HEAD" as binary input for the build ...
Uploading directory "../artifacts" as binary input for the build ...
Error from server: builds "helloworld-1" already exists
```

I have tried it manually 2 times by running `oc start-build helloworld` and run Jenkins again:
```
[test2] Running shell script
+ ./oc get builds
NAME           TYPE      FROM      STATUS     STARTED         DURATION
helloworld-1   Source    Binary    Complete   2 hours ago     5m23s
helloworld-2   Source    Binary    Running    3 minutes ago   3m8s
helloworld-3   Source    Binary    New                        
+ ./oc start-build helloworld --from-dir=../artifacts/ --follow
Uploading "../artifacts" at commit "HEAD" as binary input for the build ...
Uploading directory "../artifacts" as binary input for the build ...
Error from server: builds "helloworld-1" already exists
```

Every jenkins run uses a new machine (pod).

##### Version
I have tried running both `v1.2.0-2e62fab` and `v1.3.0-alpha.1`.
On the host:
```bash
$ oc version
oc v1.3.0-alpha.1-259-g8cd1645
kubernetes v1.3.0-alpha.1-331-g0522e63
```
##### Steps To Reproduce
Hard. Needs multiple machines to manifest.

##### Current Result
```
Error from server: builds "helloworld-1" already exists
```
##### Expected Result
Works. (Always creates deployment with build number +1 to latest.)

**Comment by bparees** [comment]
what do you mean by "jenkins"?  where is jenkins in this scenario?

what is your shell script doing?

start-build does not behave the way you are describing, so there's more to this picture.

@csrwng @gabemontero since i'm likely to be unavailable as this progresses, please keep an eye on it and help @tnozicka

**Comment by bparees** [comment]
Are you updating the buildconfig object?  the buildconfig object stores the build count, so if you are updating it, you're resetting that value.  I seem to recall from some discussions with @detiber and @knrc that you might be creating new buildconfig objects for each build.

**Comment by tnozicka** [comment]
> what do you mean by "jenkins"? where is jenkins in this scenario?

Sorry, It was just my set up in which the error manifested and the logs were from Jenkins. I did not meant to imply that it's fault.

> Are you updating the buildconfig object?

@bparees Yes, I am and I did not think there would be a counter in it. Thanks, you most probably found the real issue!

I am doing this with every pipeline build (cycle):
```bash
./oc process -f https://github.com/tnozicka/openshift-templates/raw/master/binary-build-template.yaml -v "APP_NAME=helloworld,BUILDER_IMAGE=registry.access.redhat.com/jboss-eap-7/eap70-openshift,OUTPUT_IMAGESTREAM_TAG=build" | ./oc apply -f -
./oc start-build helloworld --from-dir=../artifacts/ --follow
```

Although I would expect it to work this way.

**Comment by bparees** [comment]
Yeah so you're reverting the build sequence number each time you do that.
Take the sequence number (lastVersion I think) out of your buildconfig in
the template and then hopefully apply will just preserve the existing
value. You might need to use "patch" instead of apply, I can't remember the
nuances right now (on my phone, can't check).

Ben Parees | OpenShift

**Comment by tnozicka** [comment]
@bparees ok, I will try that as an workaround, but I still believe this is a bug. As a user I don't really care about how the counter is implemented and when I run `oc start-build` on a valid BC, I expect it to work.

So here are some options on top of my mind right now:
 1. Delete corresponding builds when deleting BC
 2. When running `oc start-build` skip the build with colliding numbers and start with the first one available
 3. Name builds with some unique ID wrt BC so this collisions does not happen at all

**Comment by tnozicka** [comment]
Btw. similar case: you have DC and 2 deployments. After you do `oc apply` on DeploymentConfig it will deploy `#3` not `#1`, so the concept already works somewhere although the implementation surely differs.

**Comment by bparees** [comment]
well it's not a valid BC because it's a BC that's reusing a version number.  like i said, if the BC you were applying didn't set the build counter, it would probably be fine.  did you try that?

and we do have logic that deletes all builds when you delete a BC, but you aren't deleting the BC, you're updating it.

we do have trello cards in our backlog for better handling build number collisions.

**Comment by tnozicka** [comment]
So I have been looking into that closer. The value is in status and I just want to point out that I am not setting it in my BC. It is called {{.status.lastVersion}}

Looking into the same thing in DC, there is {{.status.observedGeneration}} but apply works there!

I have a workaround, but it is quite ugly:
```bash
export lastBuildVersion=$(oc get bc jenkinsfile-helloworld -o template --template"{.status.lastVersion}}" 2>/dev/null || true) && \
oc apply -f <somefile> && \
if [[ "${lastBuildVersion}" =~ ^[0-9]+$ ]]; then 
    oc patch bc jenkinsfile-helloworld -p "{\\"status\\":{\\"lastVersion\\":${lastBuildVersion}}}"; 
fi
```
(I know there is a race condition in case BC would have ConfigChange trigger.)

And I believe it is a valid BC. It is not reusing version number because it is not specified in the BC file, from which it gets applied.

**Comment by kargakis** [comment]
> So I have been looking into that closer. The value is in status and I just want to point out that I am not setting it in my BC. It is called {{.status.lastVersion}}
> 
> Looking into the same thing in DC, there is {{.status.observedGeneration}} but apply works there!

The respective value in DC is {{.status.latestVersion}}

@bparees seems like buildconfigs should have a separate call for updating status, thus disabling status updates from oc

**Comment by bparees** [comment]
@tnozicka the other workaround would be to delete the BC before creating the new one.  Deleting a BC will delete all associated builds, thus resetting the build count to 0.

@kargakis i'll need to chat w/ you more about your suggestion, i don't know enough about how patch works but i take it it's somehow related to what patch is doing.

**Comment by csrwng** [comment]
@kargakis @bparees we have an issue open for that https://github.com/openshift/origin/issues/6886

**Comment by bparees** [comment]
@csrwng i still need to understand why a patch against a BC is resetting the lastVersion field on the status object...doesn't seem intuitive to me that status would be touched in that scenario.

**Comment by kargakis** [comment]
@bparees it doesn't have to do with how patch works, it has to do with what you allow to be updated in your rest strategy. Right now, in the bc rest strategy you allow both spec and status updates. What you need is to identify which components update LastVersion[1] (I think this happens only in the /instantiate and /clone endpoints but I may be wrong as I am not familiar with all the build codebase), ensure those can update both spec and status ([happens](https://github.com/openshift/origin/blob/master/pkg/build/registry/buildclone/strategy.go) [currently](https://github.com/openshift/origin/blob/master/pkg/build/registry/buildconfiginstantiate/strategy.go)) and disallow status updates in the normal [update path](https://github.com/openshift/origin/blob/604ae179d78568dea1512e0b60fdf2b1d58b1ff1/pkg/build/registry/buildconfig/strategy.go#L50-L53). For the sake of completeness, you should have a /status endpoint.

[1] Only because for buildconfigs status=lastVersion currently

**Comment by bparees** [comment]
What I still don't understand is if the update path can modify the field in
question, and the existing value is correct, and the patch is not supplying
a value for that field, why is it getting changed? I assume it must mean
lastVersion is not a pointer and thus defaults to zero in the supplied
patch argument.

Ben Parees | OpenShift

**Comment by bparees** [comment]
@tnozicka were you able to work around this by deleting the old BC before creating the new one (so the old builds get deleted)?

**Comment by tnozicka** [comment]
@bparees Yes, I went with that workaround at the end and it works. It was much simpler that re-setting the lastVersion which had also potential race condition. Sadly this way we lose build history, but that is something we can live with until this is fixed.

Btw. this issue of re-writing values with apply that user did not specify seem to be generic problem in OpenShift. I have run into it e.g. https://github.com/openshift/origin/issues/9417 but it was fixed with one if. To me this sound like (de)serialization / API design issue when you don't use 3 state logic (set, empty value like "", unset) but only 2 state (set, empty). But I know both have it's upsides and downsides.

**Comment by bparees** [comment]
thanks for the reference, i'll see if we can do something similar here.


On Tue, Jun 21, 2016 at 4:13 AM, Tomáš Nožička <notifications@github.com>
wrote:

> @bparees <https://github.com/bparees> Yes, I went with that workaround at
> the end and it works. It was much simpler that re-setting the lastVersion
> which had also potential race condition. Sadly this way we lose build
> history, but that is something we can live with until this is fixed.
>
> Btw. this issue of re-writing values with apply that user did not specify
> seem to be generic problem in OpenShift. I have run into it e.g. #9417
> <https://github.com/openshift/origin/issues/9417> but it was fixed with
> one if. To me this sound like (de)serialization / API design issue when you
> don't use 3 state logic (set, empty value like "", unset) but only 2 state
> (set, empty). But I know both have it's upsides and downsides.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/origin/issues/9301#issuecomment-227370973>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEvl3vLJ_w_OtMRqgVopX-WYVNNsLwHiks5qN509gaJpZM4I0XjL>
> .
>



-- 
Ben Parees | OpenShift
