### ISSUE TITLE
DIND fails to deploy cluster due to `findutils` not being installed

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9303]
Failures beginning with 
```
Provisioning nettest-master
/data/src/github.com/openshift/origin/hack/lib/init.sh: line 13: find: command not found
[INFO] Saving cluster configuration
cp: cannot stat ‘/tmp/openshift/test-extended/networking/subnet/openshift.local.config/*’: No such file or directory
[ERROR] Failed to deploy cluster for plugin: {subnet}
```

As seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/1173/consoleFull) and described at https://github.com/openshift/origin/pull/8853#issuecomment-225636708:

>  dind provisioning is failing due to findutils not being installed in the dind image. findutils might be installed by default on a fedora/centos/rhel vm or baremetal install, but dind is based on the f23 docker image and findutils needs to be explicitly installed here: https://github.com/openshift/origin/blob/master/images/dind/Dockerfile#L23

We must find a way to be less dependent on the f23 Docker image (do we consume `:latest` right now?) as it seems to be a cause of unnecessary instability for our tests.

/cc @marun @danwinship

**Comment by stevekuznetsov** [comment]
Sorry, misunderstood this -- thought it was pre-existing to my PR.

**Comment by liggitt** [comment]
problem detection is linking to this issue in failing test jobs

seeing this log:
```
Waiting for 3 nodes to report readiness
............................................................
[ERROR] Timeout waiting for 3 nodes to report readiness
[ERROR] PID 30745: hack/dind-cluster.sh:45: `return 1` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/dind-cluster.sh:45: `return 1`
[INFO] 		  2: hack/dind-cluster.sh:114: wait-for-cluster
[INFO] 		  3: hack/dind-cluster.sh:344: start
[INFO]   Exiting with code 1.
[INFO] Saving cluster configuration
cp: cannot open ‘/tmp/openshift/test-extended/networking/multitenant/openshift.local.config/node.kubeconfig’ for reading: Permission denied
cp: cannot open ‘/tmp/openshift/test-extended/networking/multitenant/openshift.local.config/server.key’ for reading: Permission denied
[ERROR] Failed to deploy cluster for plugin: {multitenant}
```
