### ISSUE TITLE
403 during discovery doesn't fall back to compiled RESTMapping and versions

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#9307]
```bash
oc login -u deads -p asdf
oc new-project foo
oc get pods --as bob --loglevel=8
```

gives back
```
F0613 16:12:32.882425    8733 helpers.go:108] error: failed to negotiate an api version; server supports: map[], client supports: map[v1:{} v1beta3:{} extensions/v1beta1:{} metrics/v1alpha1:{} componentconfig/v1alpha1:{} batch/v1:{} autoscaling/v1:{} authorization.k8s.io/v1beta1:{}]
```

you should get past that and end up with something like this:
```
F0613 16:13:36.382602    8750 helpers.go:108] Error from server: User "bob" cannot list pods in project "default"
```

**Comment by liggitt** [comment]
the fundamental issue is legitimate (continuing with known info in discovery error cases), but if they're getting a 403 for using `--as`, I'd actually expect an impersonation error, not a list pods error

**Comment by deads2k** [comment]
> getting a 403 for using --as, I'd actually expect an impersonation error, not a list pods error

"Something like" as in "readable message that indicates a forbidden".  The message is about like this:
`User "deads" cannot "impersonate" "users" with name "bob" in project ""`.  I don't exactly what will come out, but it should be obvious that you've made progress.
