### ISSUE TITLE
test/end-to-end/core:183: `oc status` output fragmented across `oc run --attach`

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9309]
Seeing this in AWS-based image. 

```
$ oc run cli-with-token --attach --image=openshift/origin:${TAG} --restart=Never -- cli status --loglevel=4 > ${LOG_DIR}/cli-with-token.log 2>&1
...
Jun 13 15:59:11 Running test/end-to-end/core.sh:183: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token.log'' expecting success and text 'In project test'...
Jun 13 15:59:11 FAILURE after 0.010s: test/end-to-end/core.sh:183: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token.log'' expecting success and text 'In project test': the output content test failed
Jun 13 15:59:11 Standard output from the command:
Jun 13 15:59:11 Waiting for pod test/cli-with-token to be running, status is Pending, pod ready: false
Jun 13 15:59:11 I0613 19:59:08.888906       1 factory.go:129] Using in-cluster configuration
Jun 13 15:59:11 I0613 19:59:08.916543       1 factory.go:129] Using in-cluster configuration
Jun 13 15:59:11 I0613 19:59:08.918458       1 factory.go:129] Using in-cluster configuration
Jun 13 15:59:11 pod/cli-with-token runs openshift/origin:4148579
Jun 13 15:59:11 2 warnings identified, use 'oc status -v' to see details.
Jun 13 15:59:11 
Jun 13 15:59:11 There was no error output from the command.
```

We see some of the output from `oc status` ... but not all of it?

@deads2k @ncdc thoughts?

**Comment by mfojtik** [comment]
This seems to be more like a CLI issue. @kargakis can you look this up? If it turns to be CLI and not platform specific, please re-assign to @fabianofranz

**Comment by stevekuznetsov** [comment]
I'm not sure if it's CLI -- I guess it's possible there are cases where `oc status` doesn't print everything it needs to, but perhaps it's an `oc run --attach` problem

**Comment by stevekuznetsov** [comment]
Confirm I've seen this more than once, same log.

**Comment by smarterclayton** [comment]
Before or after rebase?  Looks like before.

**Comment by mfojtik** [comment]
@smarterclayton i don't think this is related to the other attach flake... but rebase could make this worse. any suggestion who would be the best candidate to look it up?

**Comment by ncdc** [comment]
I was seeing this before the rebase, using go-dockerclient.

**Comment by liggitt** [comment]
@ncdc output of attach still being seen as truncated at times. is there a known race between a process exiting and the output being sent?

**Comment by ncdc** [comment]
It is known, yes. I don't know why it's happening.

**Comment by kargakis** [comment]
@stevekuznetsov is this related to https://github.com/openshift/origin/issues/9371?

**Comment by stevekuznetsov** [comment]
@kargakis not that I can tell, no. In this case output is missing and it is missing from the command

**Comment by kargakis** [comment]
The test has been refactored ever since - can we close this?

**Comment by stevekuznetsov** [comment]
I'm not seeing any refactors [here](https://github.com/openshift/origin/blob/master/test/end-to-end/core.sh#L222-L231), what do you mean?

**Comment by kargakis** [comment]
ugh, nvmd

**Comment by liggitt** [comment]
we commented out the test. https://github.com/openshift/origin/issues/11240 is open it re-enable it. @ncdc, did we pick up that vendored fix yet?

**Comment by ncdc** [comment]
@liggitt no, and I imagine it will be a while. Kube has to switch from using the now-deprecated docker/engine-api back to docker/docker, and then Origin will have to pick up the change as well.

**Comment by liggitt** [comment]
Do we consider logs to be critical enough function that we need to do extraordinary things to fix this before we release?

**Comment by smarterclayton** [comment]
If logs aren't reliable you can't script with them.  They were previously
scriptable, so that's a problem.

**Comment by stevekuznetsov** [comment]
Looks like a manifestation of our favorite `journald` bug

/close
