### ISSUE TITLE
Error syncing pod, skipping: failed to "StartContainer" for "POD" with ImagePullBackOff: "Back-off pulling image \"openshift/origin-pod:v1.2.0-1-g7386b49\""

### ISSUE THREAD

**Issue by lifei825** [openshift/origin#9315]
## Why are there -1-g7386b49

openshift-ansible version:\* master d3a69bb Merge pull request #2020 from dgoodwin/docker-upgrade-services
openshift version:origin 1.2.0
yum : CentOS-OpenShift-Origin.repo

**Comment by lifei825** [comment]
docker version:1.9.1

**Comment by lvthillo** [comment]
same issue (I'm using my own repository but it contains the same images as in the openshift registry on docker hub). But the tag v1.2.0-1-g7386b49 does not exist.

**Comment by dgoodwin** [comment]
I believe this is related to the assumptions we make about reading the version from "openshift version" and then assuming it is a valid image tag. I'm going to try to handle this with the release/version refactor in https://github.com/openshift/openshift-ansible/pull/1945

**Comment by lvthillo** [comment]
@dgoodwin So as I understand it will be possible to define the version of Origin in you playbook?
Any idea when this future will be implemented?

**Comment by dgoodwin** [comment]
@lvthillo not too far off, I've got most of it done just trying to wrap up and hitting issues with origin's versioning I'll be working on. I'd say within the next week or so.

**Comment by lifei825** [comment]
Found that this version is the most stable relatively new openshift-ansible-3.0.96-1.tar.gz

**Comment by priyanka5** [comment]
@lifei825 could you please give the link to download this?

**Comment by lvthillo** [comment]
@priyanka5 Same happens if you perform `git clone https://github.com/openshift/openshift-ansible` and install

**Comment by priyanka5** [comment]
@lvthillo thanks , how to check if this this only openshift-ansible-3.0.96-1.tar.gz

**Comment by lifei825** [comment]
https://github.com/openshift/openshift-ansible/archive/openshift-ansible-3.0.96-1.tar.gz

**Comment by xelfe** [comment]
Theres a quick workaround ? Or any way to dowgrade ? I need to retrieve some stuff on my pods

**Comment by gabrielscheffer** [comment]
@xelfe Hello mate, try [this workaround](https://github.com/openshift/openshift-ansible/issues/2045#issuecomment-227715124).
