### ISSUE TITLE
Dash in project name causes 'oc status -o dot' to produce invalid output.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#9317]
When running:

```
oc status -o dot
```

if the project name has a dash in it, the generated dot graph is invalid.

This is because it will start with:

```
digraph python-demos {
```

and looks like can't have dash in name of digraph.

Remove the dash and it works.

**Comment by kargakis** [comment]
@deads2k the only special character supported in DOT is the underscore: http://www.graphviz.org/doc/info/lang.html. We should turn dashes (and any other special character we allow on resource names) to underscores.

**Comment by deads2k** [comment]
> @deads2k the only special character supported in DOT is the underscore: http://www.graphviz.org/doc/info/lang.html. We should turn dashes (and any other special character we allow on resource names) to underscores.

@enj or @juanvallejo who wants it?
