### ISSUE TITLE
Replace fsouza/go-dockerclient with docker/engine-api

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#9320]
Kubernetes already moved to use the docker/engine-api, we should follow that as well. The rebase will have wrapper that allow us to transition to new Docker client without breaking stuff. 

We will also need to switch S2I to use engine-api.

**Comment by mfojtik** [comment]
@bparees is this something devexp will want to own? I think builds is the biggest user of go-dockerclient.

**Comment by liggitt** [comment]
Related items from rebase:
* engine-api supports token auth as well
* re-enable new-app integration test
* remove wrapper holding go-dockerclient and engine-api objects
* fix DOCKER_HOST env workaround on OS X

**Comment by bparees** [comment]
i guess we can drive it. don't hold your breath :)

**Comment by gabemontero** [comment]
Per confirmation with @bparees, closing this out in favor of [this trello card](https://trello.com/c/cWe43zdJ/1007-replace-fsouza-go-dockerclient-with-docker-engine-api-and-k8s-wrapper-around-engine-api)
