### ISSUE TITLE
Template cannot fill keys with parameters

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#9321]
When filling in a template it is helpful to be able to vary the keys, e.g. for label names or annotation names. But you can't; only values appear to get substitutions from template parameters.

##### Version
oc v1.3.0-alpha.1-189-gde2a8bc-dirty
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Steps To Reproduce
1. Create a template like the following:

          apiVersion: "v1"
          kind: "Template"
          parameters:
          -
            description: "Annotation name to enable dynamic provisioning for the PVC, if available"
            name: DYNAMIC
            value: dynamic-provisioning-disabled
          metadata:
            name: logging-pvc-template
            annotations:
              description: "Template for deploying logging support entities: persistentvolumeclaims."
              tags: "infrastructure"
            labels:
              logging-infra: support
          labels:
            logging-infra: support
            provider: openshift
            component: support
          objects:
          -
            apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: foo
              annotations:
                "volume.alpha.kubernetes.io/${DYNAMIC}": "dynamic"
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: "1"
2. Invoke it e.g.:

    $ oc process -f /tmp/template.yaml -v DYNAMIC=foo | grep dynamic

##### Current Result
                    "volume.alpha.kubernetes.io/${DYNAMIC}": "dynamic"

##### Expected Result
                    "volume.alpha.kubernetes.io/foo": "dynamic"

**Comment by liggitt** [comment]
I know we're trying to limit feature additions to templates to ease transitioning to eventual upstream templating... @bparees, this seem likely or not?

**Comment by deads2k** [comment]
Opened https://github.com/openshift/origin/pull/9324 so we can argue about whether we want it, not about whether or not it will be hard.

**Comment by bparees** [comment]
it seems reasonable to me.

**Comment by sosiouxme** [comment]
thanks!
