### ISSUE TITLE
Follow up to look at the anti-affinity scheduler feature

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#9323]
See if there are other aspects we should be concerned about for multi-tenant.

```
// LimitPodHardAntiAffinityTopology admission controller rejects any pod
// that specifies "hard" (RequiredDuringScheduling) anti-affinity
// with a TopologyKey other than unversioned.LabelHostname.
// Because anti-affinity is symmetric, without this admission controller,
// a user could maliciously or accidentally specify that their pod (once it has scheduled)
// should block other pods from scheduling into the same zone or some other large topology,
// essentially DoSing the cluster.
// In the future we will address this problem more fully by using quota and priority,
// but for now this admission controller provides a simple protection,
// on the assumption that the only legitimate use of hard pod anti-affinity
// is to exclude other pods from the same node.
```

**Comment by liggitt** [comment]
marking as p1 until we determine whether or not there are multi-tenant implications

**Comment by mfojtik** [comment]
@liggitt can you think of a person who can determine the multi-tenant implication of this? I think this admission plugin is enabled right now.

**Comment by liggitt** [comment]
on our side, @smarterclayton, @abhgupta, and @derekwaynecarr have poked at bits of the scheduler, but I don't know if anyone knows this new anti-affinity TopologyKey implications in depth

**Comment by mfojtik** [comment]
@liggitt after conversation with @smarterclayton 2 weeks ago, I think it is safe to bump this to P2 for now. Any objections?

**Comment by smarterclayton** [comment]
None.
