### ISSUE TITLE
oc get --help should mention "oc get" to list available resources

### ISSUE THREAD

**Issue by oatmealraisin** [openshift/origin#9326]
Right now the ```oc get --help``` command does not provide enough information about possible resources.  You can get a full list of resources from ```oc get```, but this isn't mentioned in the ```--help``` page.

##### Version
oc v1.3.0-alpha.1-285-g09a2910
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Current Result
```
[vagrant@localhost ~]$ oc get --help
Display one or many resources

Possible resources include builds, buildConfigs, services, pods, etc.
Some resources may omit advanced details that you can see with '-o wide'.
If you want an even more detailed view, use 'oc describe'.

Usage:
  oc get [(-o|--output=)json|yaml|wide|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...] (TYPE [NAME | -l label] | TYPE/NAME ...) [flags] [options]
```

##### Expected Result
```
[vagrant@localhost ~]$ oc get --help
Display one or many resources

Possible resources include builds, buildConfigs, services, pods, etc.
Use "oc get" for a full list of possible resources
Some resources may omit advanced details that you can see with '-o wide'.
If you want an even more detailed view, use 'oc describe'.

Usage:
  oc get [(-o|--output=)json|yaml|wide|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...] (TYPE [NAME | -l label] | TYPE/NAME ...) [flags] [options]
```
or something similar

@juanvallejo

**Comment by deads2k** [comment]
@juanvallejo assigned to me as a request for help trying to figure out how?

**Comment by juanvallejo** [comment]
@deads2k Ah just want your feedback whether or not the issue should be pursued

**Comment by deads2k** [comment]
> @deads2k Ah just want your feedback whether or not the issue should be pursued

There are *lots* of possible resources, I don't think we want to suggest all of them.  Updating `oc describe` to actually pull a dynamic list from the server seems pretty reasonable, but I don't think this is a high priority problem unless @fabianofranz really wants it.

**Comment by fabianofranz** [comment]
@deads2k Actually I understand what's being suggested here is to add the following line to the help of  `oc get` so that users know where to go to list what's supported by `get`:

```
Use "oc get" for a full list of possible resources
```

Makes sense to me and quite simple to do.

**Comment by deads2k** [comment]
> Makes sense to me and quite simple to do.

I count 107 resources listed in discovery so far, just oapi, api, and extensions, not counting additional groups.  Are you sure you want to list them all in help for `oc get`?  How would we try to organize them to keep it from scrolling several pages?

**Comment by fabianofranz** [comment]
@deads2k We are talking different things. What I mean and understand is the proposal of this issue, is just to add the following phrase to `oc get --help`: "Use "oc get" for a full list of possible resources".  :)

**Comment by liggitt** [comment]
`oc get` doesn't return a full list of possible resources today, does it? It returns a list of 20-30...

**Comment by fabianofranz** [comment]
@liggitt yes - limited to what's important to the average user of `oc`.

**Comment by deads2k** [comment]
> @deads2k We are talking different things. What I mean and understand is the proposal of this issue, is just to add the following phrase to oc get --help: "Use "oc get" for a full list of possible resources

I'm pretty sure that's what `oc describe` is intended to do, isn't it?

**Comment by oatmealraisin** [comment]
@deads2k You mean ```oc describe get```?

**Comment by deads2k** [comment]
> @deads2k You mean oc describe get?

`oc describe`
