### ISSUE TITLE
Add Conditions alongside Phases

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9339]
In a similar fashion to https://github.com/kubernetes/kubernetes/issues/14181

Our build and deployment config API should[1] transition from Phases to Conditions
Deployment related changes are tracked in https://trello.com/c/OIggCmzo/699-5-deployments-downstream-conditions so I am handing this issue to @bparees 

[1] Is it something we want to do? I would say that we should follow upstream conventions and furthermore Conditions seem to be more than a simple convention.

@openshift/api-review

**Comment by kargakis** [comment]
Also another thing I realized while reviewing https://github.com/openshift/origin/pull/9308 even though I had written than [part of code](https://github.com/openshift/origin/blob/6ab98bc15240c74fc921379e1d7c50f1388b51ef/pkg/build/graph/analysis/bc.go#L195-L205) before: why do we separate Failed from Error and Cancelled for builds? Upstream pod conditions seem to use different kinds of Reasons (CrashLoopBack, ImagePullLoopBack, Error, DeadlineExceeded, etc.) for a Failed condition. Is it sensible to do the same thing for builds?

**Comment by bparees** [comment]
We wanted to preserve "failed" for indicating an actual build failure (eg compile error) as compared with error (infrastructure problems) or canceled (user choice).

could it be done with reasons?  it could.  but that means requiring the user look at an additional field and makes filtering/sorting harder.

**Comment by kargakis** [comment]
I don't think the user would need to do anything different than today if we correctly surfaced the reasons on the output of`get` and `describe`. Same story with pods today, when you do `oc get pods` and have a CrashLooping pod you will not see Running (phase) but CrashLooping in the STATUS column.

**Comment by bparees** [comment]
Reasons do not tend to be as tightly enumerated as Phase, they are more freeform and likely to have new ones added.  So again, sorting/filtering is harder (both for users, and for the UI components).

**Comment by smarterclayton** [comment]
I think we want to add conditions. But existing phases can't change
(we can't add to them either).  So we should focus on adding
conditions that convey info we need.

**Comment by smarterclayton** [comment]
All error conditions should have well defined reasons and those
reasons should be on conditions.  We should not add fields to status
that belong on conditions (in general).

**Comment by bparees** [comment]
Can someone summarize, or point me to a summary definition and intended usage for:

* Phase
* Condition
* Reason

?

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md

**Comment by deads2k** [comment]
> Can someone summarize, or point me to a summary definition and intended usage for:

1. Phase: State of the object.  Only one per resource allowed.  Interpreting the phase requires understanding of the state machine.
1. Condition: State of an individual aspect of the resource.  Multiple allowed per resource. Every condition can be true, false, or unknown.  
1. Reason: One word explanation of why the condition is true, false, or unknown.  "APIServerUnreachable"
1. Message: Long, human readable description of why the condition is true, false, or unknown.  "API server unreachable due to: no route to host"

**Comment by bparees** [comment]
If Phase is being replaced by Condition, but we now have multiple conditions at a time, that does not seem to lend itself to the current "oc get" output format with a single row per resource and single column per field being reported.  Has someone address how conditions should be reported in that format?

**Comment by deads2k** [comment]
> Has someone address how conditions should be reported in that format?

So far?  Just a column that has the `[Not]Condition.Type` in a comma delimited list.

**Comment by smarterclayton** [comment]
Phase is not being replaced by condition.  No new phases should be added to
any new objects, conditions do that job better and safer.  Pods summarize
conditions in their describer.  See the pod output for more.

**Comment by bparees** [comment]
"Some resources in the v1 API contain fields called phase, and associated message, reason, and other status fields. The pattern of using phase is deprecated. Newer API types should use conditions instead."

certainly sounds like phase is being replaced by condition (that doesn't mean we're changing existing usage, but going forward it is taking the place of where phase was used previously).

**Comment by bparees** [comment]
> So far? Just a column that has the [Not]Condition.Type in a comma delimited list.

that seems problematic for any constrained width console.  we already struggle to keep the get output to 80 chars.

**Comment by smarterclayton** [comment]
They are actually consolidated.  In practice they don't matter as much.

**Comment by kargakis** [comment]
> If Phase is being replaced by Condition, but we now have multiple conditions at a time, that does not seem to lend itself to the current "oc get" output format with a single row per resource and single column per field being reported. Has someone address how conditions should be reported in that format?

The latest condition. Conditions also have timestamps.

**Comment by kargakis** [comment]
Move to Trello: https://trello.com/c/NVTCdbKe/1045-conditions-for-builds

cc: @mfojtik
