### ISSUE TITLE
Generate man pages like upstream Kube

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9348]
Ref https://github.com/kubernetes/kubernetes/blob/dae5ac482861382e18b1e7b2943b1b7f333c6a2a/cmd/genman/gen_kubectl_man.go

@eparis @fabianofranz something we should think about doing.

**Comment by fabianofranz** [comment]
+1

**Comment by smarterclayton** [comment]
@juanvallejo see my comment on #9448 but this is not correctly generating man pages for options that are not actually included in our CLI tools, but are registered to the os flags.

**Comment by juanvallejo** [comment]
Should this issue be closed?

**Comment by fabianofranz** [comment]
@smarterclayton there are still a couple places to fix, WIP in https://github.com/openshift/origin/pull/9743.

**Comment by fabianofranz** [comment]
oops I meant @juanvallejo ^  :)
