### ISSUE TITLE
Add fuzzer for RateLimiter in clientcmd_test

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#9356]
We need to fuzz the RateLimiter in clientcmd_test (TestAnonymousConfig ) to see if the config is serialized properly. See: 

https://github.com/openshift/origin/pull/8856/commits/53d9db2bbcb49113d48ad7f5b2028b98d66e1e10#diff-9b042190d0f0f247ba56f50b7499a7d4R25

**Comment by mfojtik** [comment]
@deads2k @liggitt opened to track this. I will fix this tomorrow.

**Comment by mfojtik** [comment]
@deads2k can you remind me why we need this? The `RateLimiter` is just an interface and it does not have any public variables we can fuzz AFAIK. I can implement RateLimiter that does (and also include all the functions), but I can't see a reason why.

**Comment by deads2k** [comment]
We need to be sure that `AnonymousClientConfig` is faithfully passing fields.  Right now, there's no proof that it is preserving the `RateLimiter`.  In fact, that appears to be broken now.

**Comment by mfojtik** [comment]
@deads2k k, I will create fake one and see if it is passing or not. thanks

**Comment by mfojtik** [comment]
@deads2k this was merged, closing.
