### ISSUE TITLE
SelfSubjectRulesReview request from a user with a cluster-admin role

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#9358]
Encountered a strange thing, where when sending the `SelfSubjectRulesReview` request from the web-console. Response for a non-clusterAdmin user will have an array of rules but for a  user which is clusterAdmin I'm get back a empty rules array.
The way I've created the cluster admin user was:
`oadm policy add-cluster-role-to-user cluster-admin admin --config=openshift.local.config/master/admin.kubeconfig`

**Comment by liggitt** [comment]
guessing that cluster-scoped permissions don't appear in `*SubjectRulesReview` responses... they probably should

**Comment by jhadvig** [comment]
@deads2k :+1:
