### ISSUE TITLE
Check sup groups in PV beta feature

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#9361]
See https://github.com/kubernetes/kubernetes/issues/27197.

At a minimum we'll need to do a policy check to ensure the groups are allowed (build already does something similar for UID access).

**Comment by mfojtik** [comment]
@pweil- can you guide me what exactly need to be done here? The original kube issue mention "At a minimum we'll need to do a policy check to ensure the groups are allowed (build already does something similar for UID access)."

**Comment by mfojtik** [comment]
@pweil- builds have `AllowedUIDs` (https://github.com/openshift/origin/blob/master/pkg/build/api/types.go#L33)

**Comment by mfojtik** [comment]
@pmorie do we need to pick https://github.com/kubernetes/kubernetes/pull/27639 ?

**Comment by pweil-** [comment]
@mfojtik - it looks like the PR to remove the mutation may be enough for now.  I think we should circle back with @pmorie on this when he returns

**Comment by mfojtik** [comment]
@pmorie bump :)

**Comment by pweil-** [comment]
I think we are safe here now.  The Kubelet is now calling `GetMountedVolumesForPod` rather than `GetVolumesForPodAndAppendSupplementalGroups` and passes a nil pod so it cannot be mutating the pod's supplemental groups.

```
func (vm *volumeManager) GetMountedVolumesForPod(
	podName types.UniquePodName) container.VolumeMap {
	return vm.getVolumesForPodHelper(podName, nil /* pod */)
}
``

`kubelet.go` calls `GetMountedVolumesForPod`  which calls into `getVolumesForPodHelper`.  `getVolumesForPodHelper` is appending supplemental groups to the

**Comment by pweil-** [comment]
@smarterclayton Moving this to a p2 since it is no longer a blocker.  I do not want to close it yet, we need to ensure that it gets the correct implementation upstream so a follow up check in 3.4 would be good.

(FYI @liggitt since this is security related)

**Comment by pweil-** [comment]
aaaand, back to P1.  We have https://github.com/kubernetes/kubernetes/pull/29961 on the pick list and this is adding supplemental groups to pods based on an annotation on a volume.  So we once again need to ensure that the sup groups are allowed

**Comment by pweil-** [comment]
see https://github.com/openshift/origin/pull/10167#issuecomment-237684106 - maybe no work :smile:

**Comment by liggitt** [comment]
I think @smarterclayton and I reached agreement on not having SCC/PSP participate in gids assigned transitively via a PVC->PV mount. I think that means no work here? (the cherry-pick of the feature is still covered in https://github.com/openshift/origin/issues/9790)

**Comment by pweil-** [comment]
agree.  Closing
