### ISSUE TITLE
Question about --security-opt=no-new-privileges

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#9363]
Hi All, I would like to know if it possible to configure this "docker run" parameter in OpenShift --security-opt=no-new-privileges, any idea ?

Many thanks.

**Comment by liggitt** [comment]
That's not surfaced as an option in the pod spec, but fine grained control over add/drop capabilities is available under the pod security context. Since the kubelet launches containers, and runs as root, I'm not sure a generic "no new privileged" option makes sense on a pod spec
