### ISSUE TITLE
should avoid burst in haproxy reload

### ISSUE THREAD

**Issue by adohe** [openshift/origin#9367]
Currently, we use token bucket to control reload rate limit in router, I think this way can cause frequent reload in  a short period some times, like reload 3 times in five seconds. I really think backoff is more appropriate here. @smarterclayton wdyt?

**Comment by smarterclayton** [comment]
Yeah makes sense - Ideally reload rate is inversely proportional to time
spent doing a reload and the CPU used during that process, but agree bucket
is not optimal.
