### ISSUE TITLE
Failed connect to copr.fedorainfracloud.org:443; Connection refused

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9379]
Seen [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2164/consoleFull):

```
curl: (7) Failed connect to copr.fedorainfracloud.org:443; Connection refused
```

**Comment by stevekuznetsov** [comment]
Technically just a `curl` failure ...

**Comment by mfojtik** [comment]
@stevekuznetsov it seems like DNS failure to me...

**Comment by stevekuznetsov** [comment]
@sdodson since you're knowledgeable... How would I go about debugging this on an affected machine?

**Comment by sdodson** [comment]
Unless it's a persistent issue I'm not sure there's much to debug short of
us mirroring that repo locally so we're not prone to failures of The
Internet.

**Comment by stevekuznetsov** [comment]
@spadgett seems like you hit this at home -- sounds like it's an intermittent DNS failure from above
