### ISSUE TITLE
oc cluster up; oc cluster down; oc cluster up sequence produces stale config in /tmp

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#9385]
Run `oc cluster up; oc cluster down; oc cluster up` and you should see in `/tmp` openshift config and master subdirs from both `up` invocations.

I also *think* I saw two sets of subdirs in /tmp if I put a `rm -rf /tmp/master*` and `rm -rf /tmp/openshift*` prior to the last `oc cluster up`, but it was late at night ... perhaps I misread something.

@csrwng FYI

**Comment by csrwng** [comment]
@bparees
