### ISSUE TITLE
kubectl and oc built with Origin fail against a Kube server because of missing `/oapi`

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9391]
Discovery... does not discover.

**Comment by deads2k** [comment]
Well, that could be better.

**Comment by smarterclayton** [comment]
It looks like we guard but it's still failing.  Haven't dug.


On Jun 17, 2016, at 7:45 AM, David Eads <notifications@github.com> wrote:

Well, that could be better.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9391#issuecomment-226749044>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_pyRcMIC-5g54npQ43FO_oW0hvbl5ks5qMojzgaJpZM4I34Il>
.
