### ISSUE TITLE
Registry pull-through adds ~1s to each layer push because we check the remote registry

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9394]
When pushing an image layer we've never seen before to the registry, if pull-through is enabled and there is at least one remote image in the image stream (candidate for pull-through) we search all the images for a matching layer, even though this is going to be a push.  That adds a substantial amount of time to the check.

Since the daemon invokes `HEAD /blobs` prior to the registry, we have no choice but to scan the upstream.  However, we only need to scan the upstream if we have a digest that might possibly refer to that upstream as an image layer.  Also, the logic for push and pull is slightly different - a daemon checks layers on push _before_ checking the digest, whereas on pull the daemon always has to check for the digest first.  I don't think we can rely on that (because no guarantee the daemon talks to one registry server) but it might be useful later.

When doing a stat of blob X in a repository Y, the logic should be:
1. Check the local blob store for X
2. Check the API server for images tagged into Y that have digest X - if found, check that upstream
3. Fallback to current logic.

Currently 2 is hard to do efficiently from the registry (we might have to fetch a very large number of images).  As we have discussed in other PRs, we want a fast index on "images that have layer X", and in this case it is the intersection of that query and "images tagged into Y".  Slow indices might cause problems (daemon asks for X before index has had time to process it) so we'll need to think through the implications.

Does the daemon set any headers on HEAD before push?

**Comment by smarterclayton** [comment]
@miminar @legionus

**Comment by smarterclayton** [comment]
Another option - denormalize all reachable image layers at tag time into the image stream.  Layers will be roughly 5-20x per tag, and will often be duplicated, so practical count might be 5-10x tags.  Then the stat check becomes O(1).

**Comment by miminar** [comment]
> Does the daemon set any headers on HEAD before push?

No, but the `HEAD` doesn't occur during a pull. During the pull there are only `GET` requests. But the `Stat()` call happens nevertheless for both pull and push. We could check `ctx.Value("http.request.method")` in the `Stat()` call to determine whether the client pulls (`GET`) or does something else (`HEAD`). The latter means a high probability of push going on.

> Another option - denormalize all reachable image layers at tag time into the image stream. Layers will be roughly 5-20x per tag, and will often be duplicated, so practical count might be 5-10x tags. Then the stat check becomes O(1).

This will be useful in image pruning as well (although it means pruning the table also). Although, I wonder how will we deal with images already tagged in older cluster version. Treat the table as a persistent cache where miss means - fetch the images and update the table?

> When doing a stat of blob X in a repository Y, the logic should be:

>   1. Check the local blob store for X
>   2. Check the API server for images tagged into Y that have digest X - if found, check that upstream
>   3. Fallback to current logic.

This is what we should to do either right? Even with the mapping table in IS in place. I don't see a value in doing the fallback though. Can you give an example where the fallback is necessary?

**Comment by smarterclayton** [comment]
On Jun 17, 2016, at 5:16 AM, Michal Minar <notifications@github.com> wrote:

Does the daemon set any headers on HEAD before push?

No, but the HEAD doesn't occur during a pull. During the pull there are
only GET requests. But the Stat() call happens nevertheless for both pull
and push. We could check ctx.Value("http.request.method") in the Stat()
call to determine whether the client pulls (GET) or does something else (
HEAD). The latter means a high probability of push going on.


I'm thinking about the "block pushes of certain image" use cases as well.
We could make HEAD fast always (local) while GET/PUT can do the more
expensive test and fail if necessary.  It might be too clever though - I
don't like breaking HTTP semantics unless we have to.

Actually... Thinking more about this... What info does Stat return on
head?  Size and content type?  Anything else?  Might be less of an issue.


Another option - denormalize all reachable image layers at tag time into
the image stream. Layers will be roughly 5-20x per tag, and will often be
duplicated, so practical count might be 5-10x tags. Then the stat check
becomes O(1).

This will be useful in image pruning as well (although it means pruning the
table also). Although, I wonder how will we deal with images already tagged
in older cluster version. Treat the table as a persistent cache where miss
means - fetch the images and update the table?


Maybe.  Another option is to make pullthrough a feature you enable per
image stream or per tag (via importPolicy) which means we can only denorm
certain layers.  Although the point about pruning is nice, didn't think
about this.  We should brainstorm more on this.


When doing a stat of blob X in a repository Y, the logic should be:

   1. Check the local blob store for X
   2. Check the API server for images tagged into Y that have digest X - if
   found, check that upstream
   3. Fallback to current logic.

This is what we should to do either right? Even with the mapping table in
IS in place. I don't see a value in doing the fallback though. Can you give
an example where the fallback is necessary?


Sorry, 2 would be a new type of check, while 3 would be the existing code.
  Agree it might become redundant.


—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9394#issuecomment-226721217>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p6fka9nqGt5q2OYlCupqT3315mOpks5qMmXygaJpZM4I4BFl>
.
