### ISSUE TITLE
openshift and flocker

### ISSUE THREAD

**Issue by ghost** [openshift/origin#9398]
#### Feature request

Kubernetes support flocker as a persistent volume type

http://kubernetes.io/docs/user-guide/volumes/#flocker

it would be nice to have this type also in openshift.

This would be enhance the openshift pv type to this back-ends.

https://clusterhq.com/flocker/introduction/#storage-options
##### Version

all versions

**Comment by eparis** [comment]
@childsb

**Comment by kevprice83** [comment]
Any plans to support this in the near future?
