### ISSUE TITLE
Move CONTRIBUTING.adoc to a series of getting-started guides.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#9406]
_Problem_
- The simplest way to setup openshift from source is DIND... however, its at the bottom of the CONTRIBUTING.adoc.  
- The running tests section is at the bottom of the doc, so anyone wanting to run tests and setup a cluster has to read the top of the doc, and then skip to the bottom.  Its not clear where dev instructions begin and test instructions begin.
- Some mechanisms (like vagrant-dind) can be done super easily, and are unfortunately buried in the same text as the complex local dev setup instructions.

_Solution_

The common solution to all of this: Separate the dev workflows into separate files, like this:

I'd suggest something like

```
- contributing
   - local.md
   - dind.md
   - vagrant-dind.md
   - openshift-ansible.md
   - running-tests.md
```

... 
@marun sounds ok to you?  This would make it super easy to add new wacky testing scenarios (i.e. ec2, openstack-vagrant, whatever) without making the existing instructions increasingly complex.

**Comment by danmcp** [comment]
One potential problem with this approach is anything shared between the different docs after the beginning will be copied into each sub document.

@openshift/team-project-committers Thoughts?

**Comment by smarterclayton** [comment]
I don't know anyone who uses DinD other than the networking team.   I would not advocate making it the default way to develop OpenShift - since it doesn't match the default way people work.

**Comment by bparees** [comment]
-1 to making DIND the primary dev approach.  but +1 to breaking out "how to get a cluster up and running"(And providing instructions for all the different ways) from other dev activities.

**Comment by jayunit100** [comment]
Ok, removed lines that indicate DIND as default

**Comment by pweil-** [comment]
IMO we should promote the vagrant plugin a bit more, getting a dev environment is as easy as `vagrant up`.  We include all the recommended versions of required software and starting with multiple minions simply setting some env vars.

**Comment by jayunit100** [comment]
Agree that we should have one of these md files be the "official" way for testing - and  That can be added in The new contributing doc in a follow on pr

**Comment by smarterclayton** [comment]
We're using asciidoc for our contributing docs so that it's easily portable to our other doc areas down the road.

**Comment by jayunit100** [comment]
Yeah I meant adoc, the pr above is adoc

**Comment by bparees** [comment]
the contributing guide now provides separate instructions for developing using a local cluster and a DIND cluster.

the hacking guide covers running tests:
https://github.com/openshift/origin/blob/master/HACKING.md
