### ISSUE TITLE
Utilize generated completions and man pages during rpm build process.

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#9407]
Followup to #9354 is that the binaries themselves will be capable of generating completion. We should do away with contrib/completions while still ensuring that completions are installed when installing the rpms. We could do this by generation the completions at compile time when building RPMs.

**Comment by sdodson** [comment]
See also #9448

**Comment by tdawson** [comment]
Do we want to do *all* the binaries for bash autocompletion or just some?
I figured we do them all for man pages, but didn't know for automcompletion.

**Comment by kargakis** [comment]
I think we already do that now

/close
