### ISSUE TITLE
Describe buildconfig from CLI has incorrect URLs for webhooks

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin#941]
Started an all-in-one server, created the sample-app/application-template-stibuild.json, and then described the buildconfig, the webooks dont identify the right ports or protocol

[vagrant@openshiftdev sample-app]$ osc  --kubeconfig=../../openshift.local.certificates/admin/.kubeconfig describe buildconfig ruby-sample-build
Name:				ruby-sample-build
Annotations:			<none>
Created:			2015-02-06 18:41:34 +0000 UTC
Strategy:			STI
Builder Image:			openshift/ruby-20-centos
Source Type:			Git
URL:				git://github.com/openshift/ruby-hello-world.git
Output to:			origin-ruby-sample
Output Spec:			<none>
Webhook Github:			localhost/osapi/v1beta1/buildConfigHooks/ruby-sample-build/secret101/github
Webhook Generic:		localhost/osapi/v1beta1/buildConfigHooks/ruby-sample-build/secret101/generic
Image Repository Trigger:	ruby-20-centos
- Tag:				latest
- Image:			openshift/ruby-20-centos
- LastTriggeredImageID:		<none>

**Comment by soltysh** [comment]
@jcantrill this is fixed already, can you close this, or is there something left there?
