### ISSUE TITLE
Failure executing 'oadm registry -o yaml --credentials=/tmp/openshift/test-cmd//openshift.local.home/.kube/non-default-config'

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#9410]
https://github.com/openshift/origin/pull/9354
Jenkins test fails when executing `oadm registry -o yaml --credentials=/tmp/openshift/test-cmd//openshift.local.home/.kube/non-default-config`, expecting text, but receiving no output.

##### Version
oc v1.3.0-alpha.0-1100-gaf02c04-dirty
kubernetes v1.3.0-alpha.3-599-g2746284

##### Steps To Reproduce
[test]

##### Current Result
FAILURE after 0.276s: test/cmd/admin.sh:309: executing 'oadm registry -o yaml --credentials=/tmp/openshift/test-cmd//openshift.local.home/.kube/non-default-config' expecting success and text

**Comment by mfojtik** [comment]
@enj can you check this ?

**Comment by juanvallejo** [comment]
test seems to be passing now, seems to fail once in a while

**Comment by enj** [comment]
I am also unable to reproduce this @mfojtik

**Comment by mfojtik** [comment]
@juanvallejo still seeing this failing? or you are ok with closing this?

**Comment by juanvallejo** [comment]
@mfojtik I have not seen this issue pop up lately, it should be okay to close, thanks!
