### ISSUE TITLE
Build push failure does not fail build

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9420]
```
oc cluster up
oc new-project foo
oc new-app cakephp-mysql-example
oc logs -f bc/cakephp-mysql-example
```

I'm seeing builds succeed even though the registry was down while the push was happening, resulting in push failure.  That should not be happening.  I'm also seeing builds succeed even when the registry fails the pull.  I'm also not seeing a clear failure output (did we lose a flush somewhere)?

This is with latest images.

**Comment by smarterclayton** [comment]
Docker 1.10 latest.  If this turns out to be a real issue we need to get an e2e/extended test that demonstrates a failure to push causes build to fail.

**Comment by smarterclayton** [comment]
`oc cluster up` doesn't currently wait for the registry to be ready, but we should expect this scenario to work every single time.  That means either push retries in builds need to be longer when the server returns connection refused, or we need to gate somewhere in cluster up.  If we gate in cluster up that's going to make cluster up *painfully* slow.

**Comment by smarterclayton** [comment]
I don't know whether this is retry loop or not, but this certainly is pushing me back to wanting at least some retry loop for these cases, and some better output.

**Comment by danmcp** [comment]
Dup of https://github.com/openshift/origin/issues/9343 ?

**Comment by bparees** [comment]
> oc cluster up doesn't currently wait for the registry to be ready, but we should expect this scenario to work every single time. That means either push retries in builds need to be longer when the server returns connection refused, or we need to gate somewhere in cluster up. 

where is this part coming from?  assuming we fix the issue where the build is not detecting the push failure, is the existing retry logic not sufficient?  (I forget exactly which push errors we retry and how long we retry for).

**Comment by smarterclayton** [comment]
I think this is effectively a dupe, as long as our retry is enough.  I
don't have a good number but it could be a while before the registry image
pulls in some cases.  We need to test for this really.
