### ISSUE TITLE
Readiness checks have terrible latency

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9424]
The retry loop on readiness checks leads to interminable waits, and a lot of sitting around waiting for things to actually work.  We need to figure out how to effective keep the latency for readiness < 10s from the time of actual ready.  Right now, it can take minutes.  Since this blocks deployments, it makes deployments look flaky and slow.

It's likely we can afford to be more aggressive on the kubelet end on this.  @ncdc @derekwaynecarr @kargakis - let's see if we can identify whether this is actually an issue and what we can do to make it better.  It makes the origin initial app experience... well... sucky.

**Comment by smarterclayton** [comment]
Alternatively, if it's our apps that are the problem (due to the parameters we are using) we need to fix them.  @bparees 

Scenario:

```
oc cluster up
oc new-project foo
oc new-app cakephp-mysql-example
# takes 4-5 **minutes** for this to stabilize
```

It took 8 minutes on one run for cakephp to respond to readiness.  Something is seriously broken.

**Comment by bparees** [comment]
what's the time like on a re-deploy or delete the pod?  (trying to remove the build/push time from your equation).

also what is the readiness retry interval?

**Comment by smarterclayton** [comment]
the build takes about 30 seconds.  Once it's there the hook pod restarts 2-3 times, but is usually done within 20 seconds.  At that point it takes anywhere from 1-6 minutes for the pod to be ready, restarting multiple times in the process.

**Comment by smarterclayton** [comment]
You can easily reproduce this by running the steps above (this is with everything precached that can be precached)

**Comment by bparees** [comment]
so do we just need to bump the initialdelay on our liveness check?  that's probably what's killing the pod.

**Comment by bparees** [comment]
(it's currently 30s)

**Comment by bparees** [comment]
i'm in a hotel w/ horrible wifi so recreating is a dubious proposition at the moment.

**Comment by smarterclayton** [comment]
Not sure - I'll need to try again on monday.

**Comment by derekwaynecarr** [comment]
I cant get this scenario to work at all right now.

```shell
$ oc cluster up
$ oc new-app cakephp-mysql-example
$ oc logs -f bc/cakephp-mysql-example
warning: OpenShift server version "v1.3.0-alpha.1-439-g604ae17" differs
from this image "v1.3.0-alpha.1-491-ge5ff67e"
The value of ALLOWED_UIDS is [1-]
The value of DROP_CAPS is [KILL,MKNOD,SETGID,SETUID,SYS_CHROOT]
Creating a new S2I builder with build config: "Builder Name:\t\t\tApache
2.4 with PHP 5.6\nBuilder
Image:\t\t\tcentos/php-56-centos7@sha256:37448699591a3fa0f8e6ca24df890501aa46f0fce58dd6340177f5b43f5d3593\nBuilder
Image Version:\t\t186a9c8caca0ef9eec4125247979876bf2c937b4\nBuilder Base
Version:\t\te178f1c\nSource:\t\t\t\tfile:///tmp/s2i-build336855641/upload/src\nOutput
Image
Tag:\t\tmyproject/cakephp-mysql-example-1:1d5f8c8f\nEnvironment:\t\t\tOPENSHIFT_BUILD_NAME=cakephp-mysql-example-1,OPENSHIFT_BUILD_NAMESPACE=myproject,OPENSHIFT_BUILD_SOURCE=
https://github.com/openshift/cakephp-ex.git\nIncremental
Build:\t\tdisabled\nRemove Old Build:\t\tdisabled\nBuilder Pull
Policy:\t\tif-not-present\nPrevious Image Pull
Policy:\talways\nQuiet:\t\t\t\tdisabled\nLayered
Build:\t\t\tdisabled\nWorkdir:\t\t\t/tmp/s2i-build336855641\nDocker
NetworkMode:\t\tcontainer:6898cc138187b471b31bc066d5426a1684296199e49a714152c99219bda60d25\nDocker
Endpoint:\t\tunix:///var/run/docker.sock\n"
Downloading "https://github.com/openshift/cakephp-ex.git" ...
error: build error: fatal: unable to access '
https://github.com/openshift/cakephp-ex.git/': Could not resolve host:
github.com; Unknown error
```

@cewong

**Comment by ncdc** [comment]
I'm consistently seeing builds and deployments of cakephp-mysql-example take about 10 seconds each. Is this still an issue?

**Comment by eparis** [comment]
closing due to lack of response.
