### ISSUE TITLE
Update custom errors for deployment controllers to embed actual errors

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9434]
@deads2k @mfojtik

**Comment by matthyx** [comment]
@mfojtik looks like you are assigned to almost all tickets with help-wanted tag...
Please tell me which ones are still valid and their priority, cheers.

**Comment by mfojtik** [comment]
@matthyx this is valid one, it has low priority but would be nice to have :-)

**Comment by matthyx** [comment]
Ok, consider me working on it...

**Comment by matthyx** [comment]
Ok, so just to make sure we're talking about the same thing here, I have to modify these error types:
pkg/deploy/controller/deployment/controller.go:24:type fatalError string
pkg/deploy/controller/deployment/controller.go:29:type actionableError string
pkg/deploy/controller/deploymentconfig/controller.go:28:type fatalError string
pkg/project/controller/controller.go:22:type fatalError string

I couldn't find any other one, @kargakis @mfojtik can you confirm?

**Comment by matthyx** [comment]
I have made an example https://github.com/matthyx/origin/commit/1482476a6f55813a6ae1c0a74567407192a1bc77, can you tell me if that's what you thought?

**Comment by matthyx** [comment]
@mfojtik would you have some time to check my example? I am trying to get some insights from @janetkuo from Kubernetes on a similar topic.

**Comment by mfojtik** [comment]
@matthyx the idea sounds good to me, dropped few comments in your example :)

**Comment by matthyx** [comment]
@mfojtik I have now included the error inside the struct, let me know of you like it:
https://github.com/matthyx/origin/commit/8996fa58a6986f28175a8e03037a1695bcb8cac8
