### ISSUE TITLE
Extended.[k8s.io] Kubectl client [k8s.io] Kubectl expose should create services for rc [Conformance]

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#9444]
Test flake: kubectl expose test fails while waiting for redis container
##### Version

v1.3.0-alpha.1-380-g4965f56
##### Steps To Reproduce
1. Run extended tests core
##### Current Result

Extended test failure:

```
• Failure [111.412 seconds]
[k8s.io] Kubectl client
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework/framework.go:505
  [k8s.io] Kubectl expose
  /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework/framework.go:505
    should create services for rc [Conformance] [It]
    /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubectl.go:798

    Jun 20 15:08:44.916: No pods matched the filter.
```
##### Expected Result

Test passes
##### Additional Information

Times out waiting for redis RC:

```
STEP: creating Redis RC
Jun 20 15:07:14.515: INFO: namespace e2e-tests-kubectl-h1cxa
Jun 20 15:07:14.515: INFO: Running '/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl --server=https://172.18.14.213:8443 --kubeconfig=/tmp/openshift/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig create -f /data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/testing-manifests/kubectl/redis-master-controller.json --namespace=e2e-tests-kubectl-h1cxa'
Jun 20 15:07:14.902: INFO: stderr: ""
Jun 20 15:07:14.902: INFO: stdout: "replicationcontroller \"redis-master\" created\n"
STEP: Waiting for Redis master to start.
Jun 20 15:07:15.968: INFO: Selector matched 1 pods for map[app:redis]
Jun 20 15:07:15.968: INFO: Found 0 / 1
Jun 20 15:08:38.908: INFO: Selector matched 1 pods for map[app:redis]
Jun 20 15:08:38.908: INFO: Found 0 / 1
Jun 20 15:08:39.942: INFO: Selector matched 1 pods for map[app:redis]
Jun 20 15:08:39.942: INFO: Found 0 / 1
Jun 20 15:08:40.905: INFO: Selector matched 1 pods for map[app:redis]
Jun 20 15:08:40.905: INFO: Found 0 / 1
Jun 20 15:08:41.905: INFO: Selector matched 1 pods for map[app:redis]
...
Jun 20 15:08:41.905: INFO: Found 0 / 1
Jun 20 15:08:42.905: INFO: Selector matched 1 pods for map[app:redis]
Jun 20 15:08:42.905: INFO: Found 0 / 1
Jun 20 15:08:43.905: INFO: Selector matched 1 pods for map[app:redis]
Jun 20 15:08:43.905: INFO: Found 0 / 1
Jun 20 15:08:44.905: INFO: Selector matched 1 pods for map[app:redis]
Jun 20 15:08:44.905: INFO: Found 0 / 1
Jun 20 15:08:44.910: INFO: Selector matched 1 pods for map[app:redis]
Jun 20 15:08:44.910: INFO: Found 0 / 1
Jun 20 15:08:44.910: INFO: WaitFor completed with timeout 1m30s.  Pods found = 0 out of 1
Jun 20 15:08:44.916: INFO: Selector matched 1 pods for map[app:redis]
Jun 20 15:08:44.916: INFO: No pods matched the filter.
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2306/

**Comment by ncdc** [comment]
The openshift log was truncated at 20MB and doesn't contain anything related to the failing test case. The Jenkins console has this as the last event related to the pod:

```
Jun 20 15:08:44.921: INFO: At {2016-06-20 15:07:35 -0400 EDT} - event for redis-master-h8d1a: {kubelet 172.18.14.213} Pulling: pulling image "gcr.io/google_containers/redis:e2e"
```

I'm guessing this is a gcr.io flake but without logs, I can't say for sure. Please reopen if this happens again, and maybe we'll have more useful logs.

**Comment by kargakis** [comment]
Once again: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2548/consoleFull

**Comment by ncdc** [comment]
This is what I suspected - pulling the image is just taking too long.

```
Jun 24 05:02:01.070: INFO: stdout: "replicationcontroller \"redis-master\" created\n"
STEP: Waiting for Redis master to start.
[...]
Jun 24 05:03:31.077: INFO: WaitFor completed with timeout 1m30s.  Pods found = 0 out of 1
```

```
Jun 24 05:03:31.084: INFO: At {2016-06-24 05:02:01 -0400 EDT} - event for redis-master: {replication-controller } SuccessfulCreate: Created pod: redis-master-ukphz
Jun 24 05:03:31.084: INFO: At {2016-06-24 05:02:01 -0400 EDT} - event for redis-master-ukphz: {default-scheduler } Scheduled: Successfully assigned redis-master-ukphz to 172.18.12.236
Jun 24 05:03:31.084: INFO: At {2016-06-24 05:02:16 -0400 EDT} - event for redis-master-ukphz: {kubelet 172.18.12.236} Pulling: pulling image "gcr.io/google_containers/redis:e2e"
Jun 24 05:03:31.084: INFO: At {2016-06-24 05:03:29 -0400 EDT} - event for redis-master-ukphz: {kubelet 172.18.12.236} Pulled: Successfully pulled image "gcr.io/google_containers/redis:e2e"
Jun 24 05:03:31.084: INFO: At {2016-06-24 05:03:30 -0400 EDT} - event for redis-master-ukphz: {kubelet 172.18.12.236} Created: Created container with docker id 707e37a9807e
Jun 24 05:03:31.085: INFO: At {2016-06-24 05:03:30 -0400 EDT} - event for redis-master-ukphz: {kubelet 172.18.12.236} Started: Started container with docker id 707e37a9807e
```

Upstream has taken to pre-pulling all the images used in tests to avoid situations like this.

**Comment by ncdc** [comment]
See https://github.com/kubernetes/kubernetes/blob/ee7ca66dbad52b453bede0da5d1f8b10f972c360/cluster/saltbase/salt/e2e-image-puller/e2e-image-puller.manifest

Looks like that is installed via salt. We could modify our test scripts to do something similar.

Also see e.g. https://github.com/kubernetes/kubernetes/blob/dd4dae4a57129c40d4496ca6ad37ee3a4fa045fa/test/e2e/e2e.go#L128

**Comment by ncdc** [comment]
@derekwaynecarr do you think we should just try to run the upstream image puller manifest in origin's e2e test?

**Comment by derekwaynecarr** [comment]
:+1: on pre-pulling e2e images

**Comment by ncdc** [comment]
Ok, we can't reuse the upstream e2e-image-puller pod as is, at least not on Fedora 24, because our /usr/bin/docker is dynamically linked, and trying to run it bind-mounted into a busybox container results in unresolved shared libraries. I modified the manifest to use fedora:24 and everything is pulling as it should be. We just need to decide how we want to approach this. I assume we don't have the e2e-image-puller.manifest file available by default, so maybe we'll need to download it, run sed to change the image, and then create it.

It's also pulling the images serially, which might not be optimal from a timing perspective. It took about 6.5 minutes on my 50Mbps FIOS connection.

**Comment by ncdc** [comment]
It also looks like it's over 5GB of image data

**Comment by bparees** [comment]
hit again here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2775/consoleFull

**Comment by ncdc** [comment]
We have a wip pr to pre pull

**Comment by mfojtik** [comment]
and again here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2793/

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2794/consoleFull

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2789/consoleFull

**Comment by ncdc** [comment]
No need to keep linking 😄

**Comment by bparees** [comment]
@ncdc sorry for the spam, i forgot this one was actually understood/being fixed. :)

**Comment by bparees** [comment]
> We have a wip pr to pre pull

is that wip PR linked to this issue anywhere?  or it's still upstream?

**Comment by ncdc** [comment]
#9622

**Comment by bparees** [comment]
@ncdc thanks. i took the liberty of updating that PR to indicated it'll fix this issue.
