### ISSUE TITLE
Travis build fails to find k8s dep "k8s.io/kubernetes/cmd/genutils"

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#9449]
https://travis-ci.org/openshift/origin/jobs/139049154
https://github.com/openshift/origin/pull/9448

##### Version
oc v1.3.0-alpha.0-1132-gbc32091-dirty
kubernetes v1.3.0-alpha.3-599-g2746284

##### Steps To Reproduce
[test]

##### Current Result
```
_output/local/go/src/github.com/openshift/origin/tools/genman/gen_oadm_man.go:25:2: cannot find package "k8s.io/kubernetes/cmd/genutils" in any of:

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/k8s.io/kubernetes/cmd/genutils (from $GOROOT)

	/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/k8s.io/kubernetes/cmd/genutils (from $GOPATH)

	/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/cmd/genutils
```

**Comment by stevekuznetsov** [comment]
@juanvallejo any reason you closed this? dupe of https://github.com/openshift/origin/issues/9286 but a real problem

**Comment by stevekuznetsov** [comment]
tracking issue here: https://github.com/openshift/origin/issues/9457

**Comment by juanvallejo** [comment]
@stevekuznetsov Managed to solve this particular one by including a copy of the "genutils" directory. Apparently we don't have those files yet in our copy of k8s.
