### ISSUE TITLE
pushing to internal registry stops after some time with "authentication required" message

### ISSUE THREAD

**Issue by sahlex** [openshift/origin#9455]
I installed openshift origin v1.3.0-alpha.1 (both master and node ion one machine) and managed to install the internal registry. I created a non-system user and obtained the access token which I used to login from my local repository on a second machine. I used the instructions from https://docs.openshift.org/latest/install_config/install/docker_registry.html#access to assign appropriate access right. Docker login from the remote machine works fine.

Now, when I tag a local image and try to push it it looks like this:

`The push refers to a repository [registry.brodosmit.de:80/brodos/pmc]`
`5f70bf18a086: Pushing 1.024 kB`
`1ed342982bfd: Pushing 2.048 kB`
`f20d253b1c4f: Pushing [==================================================>] 91.66 MB/91.66 MB`
`600d188506b4: Pushing [==================================================>] 80.93 MB`
`c92b7e64e5f6: Pushing [==================================================>] 14.85 kB`
`89825acba507: Pushing 3.072 kB`
`f4113225686b: Pushing [>                                                  ] 526.3 kB/364.9 MB`
`b5f9bc09e70a: Pushing  2.56 kB`
`075921ca92ab: Pushing [>                                                  ] 531.5 kB/364.9 MB`
`88ab5788f9af: Pushing [==================================================>] 181.3 MB`
`0ce92edbc831: Pushing [==================================================>]  2.56 kB`
`d60911b06cc3: Waiting`
`131aa8eebad9: Waiting`
`93479390f9b6: Waiting`
`4117d5d6f28e: Waiting`
`d59984677df0: Waiting`
`191bb5252d53: Waiting`
`499002ed61c6: Waiting`
`eb5e3e1e7351: Waiting`
`unauthorized: authentication required`

##### Version
oc v1.3.0-alpha.1
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Current Result
Push command stops with error after successfully pushing some parts of the image.

##### Expected Result
Push command should complete successfully after having pushed all image parts.

##### Additional Information
[diagnostics.txt](https://github.com/openshift/origin/files/325262/diagnostics.txt)
[oc_getAll.txt](https://github.com/openshift/origin/files/325268/oc_getAll.txt)

**Comment by mfojtik** [comment]
@miminar PTAL as well

**Comment by miminar** [comment]
Can you please provide also logs from docker registry (`oc logs dc/docker-registry`) from the time of failed push.

It seems quota enforcement related to me (#9400). If I'm right you'll probably need to reconcile cluster roles `oadm policy reconcile-cluster-roles --help`, `oadm policy reconcile-cluster-role-bindings --help`. Or you'll have to update to v1.3.0-alpha.2 and disable quota enforcement in registry's deployment config.

**Comment by sahlex** [comment]
Please find attached the logs...
[registry_output.txt](https://github.com/openshift/origin/files/327500/registry_output.txt)

**Comment by miminar** [comment]
Thanks @sahlex, this looks important. Bumping priority.

**Comment by legionus** [comment]
@sahlex We recently upgraded the docker-registry upto 2.4. There were a lot of changes.
Can you try to reproduce this on master ?

**Comment by legionus** [comment]
Reopen this issue if I can reproduce this bug on top of origin.
