### ISSUE TITLE
Script to build individual images

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9463]
As per various discussions and a recent thread in the mailing list, it's pretty obvious that there is a clear need for a tool/script that will build individual images being part of the origin repo. 

There are a couple of different solutions already existing, we should pick one and integrate it.

@stevekuznetsov @smarterclayton @danmcp @rhcarvalho @ironcladlou @csrwng et al

**Comment by smarterclayton** [comment]
Are these production images or "fake" images?  If they're production images, how will you decide whether to rebuild the parent layers?

**Comment by kargakis** [comment]
@smarterclayton this is merely for a better development workflow. Currently I am using a script built by @rhcarvalho, you are probably using your own script, others are using different tools. While using different tools is totally fine, it can be cumbersome for newcomers to figure out what they need to do in order to avoid rebuilding all the images with `make release` just for a change in the builder, deployer, docker registry, etc.

**Comment by stevekuznetsov** [comment]
Some of the scripts I noticed in that e-mail thread simply replace the `oc` binary, etc, in the image -- what API are we looking at here?

**Comment by smarterclayton** [comment]
Do you expect to get incremental compilation and incremental build?

**Comment by kargakis** [comment]
All I care about in the first iteration of this is to avoid `make release` for building a single image.

**Comment by mfojtik** [comment]
@smarterclayton the problem that some of the scripts I saw was addressing is simply inject the `openshift` binary you just built to existing images so you can test/develop things like deployer, builder, etc.

**Comment by mfojtik** [comment]
@smarterclayton this also might be useful when using `oc cluster up` for development (I built openshift binary and I can now upload it to `openshift/origin` image).

**Comment by rhcarvalho** [comment]
FWIW, here's an old branch with a WIP to integrate the scripts I've been using into origin:
https://github.com/rhcarvalho/origin/commits/dev-rebuild-builder-images
Anybody working on the tool feel free to steal from it.

The original code I'm using is in:
https://github.com/rhcarvalho/openshift-devtools/tree/master/extras

**Comment by stevekuznetsov** [comment]
@mfojtik to confirm the two wants here are:
 - ability to build one image at a time
 - ability to "re-build" any image by updating `oc/openshift/oadm` binary in the image

Are these orthogonal in your mind? Or are you *not* looking for a means by which to build a specific image from scratch?

How do you want to handle dependent images?

**Comment by stevekuznetsov** [comment]
Or, maybe this is a better question:

What's missing from @rhcarvalho's implementation?

**Comment by stevekuznetsov** [comment]
Also addressed by #13444

**Comment by kargakis** [comment]
https://github.com/openshift/origin/blob/master/hack/build-local-images.py
