### ISSUE TITLE
[builds][Conformance] build without output image

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9490]
```
• Failure [39.765 seconds]
[builds][Conformance] build without output image
/data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:49
  building from templates
  /data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:48
    should create an image from "/data/src/github.com/openshift/origin/test/extended/testdata/test-s2i-no-outputname.json" S2i template without an output image reference defined [It]
    /data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:47

    Expected error:
        <*exec.ExitError | 0xc8206a47a0>: {
            ProcessState: {
                pid: 25612,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 113776},
                    Stime: {Sec: 0, Usec: 19652},
                    Maxrss: 25448,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 6455,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 2150,
                    Nivcsw: 22,
                },
            },
            Stderr: nil,
        }
        exit status 1
    not to have occurred

    /data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:45
```

@stevekuznetsov known flake?

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2426/consoleFull

**Comment by smarterclayton** [comment]
@bparees didn't we fix these flakes?

**Comment by bparees** [comment]
@smarterclayton this looks different, looks like docker daemon wackiness.  from the build log:


I0622 13:45:23.317312       1 glog.go:50] Removing container 
"20aa7dc686459824a457d6cb01e1e84cce2365ab76912178ff0927c7efa45043" ...
warning: Failed to remove container "20aa7dc686459824a457d6cb01e1e84cce2365ab76912178ff0927c7efa45043": API error (500): Driver devicemapper failed to remove root filesystem 20aa7dc686459824a457d6cb01e1e84cce2365ab76912178ff0927c7efa45043: mount still active
I0622 13:45:23.390875       1 cleanup.go:31] Removing temporary directory /tmp/s2i-build031277940
I0622 13:45:23.390901       1 fs.go:156] Removing directory '/tmp/s2i-build031277940'
F0622 13:45:23.399964       1 helpers.go:107] error: build error: building extended-test-build-no-outputname-yeaf0-xyuep/test-sti-1:72737d39 failed when committing the image due to error: No such container: 20aa7dc686459824a457d6cb01e1e84cce2365ab76912178ff0927c7efa45043
error: The build extended-test-build-no-outputname-yeaf0-xyuep/test-sti-1 status is "Failed"

**Comment by stevekuznetsov** [comment]
@kargakis new flake? Have you added a Jenkins Failure Cause Management entry?

**Comment by stevekuznetsov** [comment]
Devicemapper issues... @runcom @rhvgoyal maybe you will be able to shed some light on it?

**Comment by bparees** [comment]
per my comment above, this is a docker daemon problem

**Comment by bparees** [comment]
recurred:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2849/consoleFull

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3764/consoleFull

**Comment by stevekuznetsov** [comment]
@runcom @rhvgoyal any thoughts on this one?

**Comment by bparees** [comment]
@jwhonce should this be duped to https://github.com/openshift/origin/issues/9548 ?

i'm seeing at least 3 forms of device mapper failures:
```
Error running deviceResume dm_task_run failed
```

```
Driver devicemapper failed to remove root filesystem
```

```
error: build error: open /dev/mapper/docker
```

would be nice if they were all one docker bug.

**Comment by miminar** [comment]
Another failing job: https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/7632/

**Comment by jwhonce** [comment]
@miminar I don't see any failures in the docker journald entries for this run. Can you point me to where you see the docker issue in the logs?  Thanks.

**Comment by miminar** [comment]
@jwhonce I see it 97 lines above [the indication](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/4822/consoleFull#-125671511456cbb9a5e4b02b88ae8c2f77) in the console output of the job.

**Comment by mfojtik** [comment]
bumping prio of this as this is no. 1 flake :-)

**Comment by bparees** [comment]
@mfojtik it's number one only because it's been around so long, if you look at the actual frequency with which it's hit, it's not very frequent (hasn't been seen in 15 days for instance).

Need to divide number of occurences by the age of the flake, to get at least a simplistic metric.

**Comment by mfojtik** [comment]
@bparees good idea :-) i will add that tonight to my flake reporter.

**Comment by jwhonce** [comment]
@mfojtik @bparees Given your discussion should this really be restored to a P2?

**Comment by bparees** [comment]
@jwhonce given that it's been 25+ days since anyone referenced it, i'd even be willing to consider closing it and reopen if we recreate, unless you guys have reason to think it's still a problem.

**Comment by jwhonce** [comment]
Please re-open issue if it resurfaces.

**Comment by stevekuznetsov** [comment]
Rats. We've not been referencing this but we hit it in `base_ami` job quite often: https://ci.openshift.redhat.com/jenkins/job/base_ami/2571/consoleFull#1518085191577f0ce7e4b0b14b5836ce6d

 That being said this feels like a weird conglomerate of lots of issues, but @runcom should be able to better understand it.

**Comment by runcom** [comment]
Pretty sure there's an active bugzilla about this "mount still active" on Docker build (https://bugzilla.redhat.com/show_bug.cgi?id=1403027)
