### ISSUE TITLE
oc cluster up should queue temporary container deletes and process them in the background

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9499]
They are very slow and we don't need to wait for them.  Create a delete queue, shuttle them off and dispatch deletes for each.  May need to test whether this blows up docker.

**Comment by csrwng** [comment]
I tried this and it did very little to improve performance. I think we can gain a lot more by minimizing the number of containers we launch. Of course we can do this as well when we optimize the containers. Will use this issue to track that pending performance work.

**Comment by bparees** [comment]
@mfojtik this should be factored into whatever rearchitecture of oc cluster up the master team ends up doing.

**Comment by mfojtik** [comment]
We are going to increase the # of containers ;-) Wonder if delete queue will make a difference right now with the amount of containers we run (@deads2k ?)
