### ISSUE TITLE
oadm prune --namespace=myns does not limit to specified namespace

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#9502]
While working on my pruning image card, I wanted to test the pruning only within my test namespace, but invoking `oadm prune images -n test --loglevel=4` showed me that all namespaces were taken into consideration. Looking at the pruning source code ([builds.go](https://github.com/openshift/origin/blob/16bcdd0e49490976c2c942ed90b0de7db757a8cf/pkg/cmd/admin/prune/builds.go#L70), [deployments.go](https://github.com/openshift/origin/blob/16bcdd0e49490976c2c942ed90b0de7db757a8cf/pkg/cmd/admin/prune/deployments.go#L70), [images.go](https://github.com/openshift/origin/blob/16bcdd0e49490976c2c942ed90b0de7db757a8cf/pkg/cmd/admin/prune/images.go#L127)) we always use `kapi.NamespaceAll`. The question is should we take namespace into consideration? 

In my opinion, and from talking to @miminar for builds and deployments it's quite straightforward, so yes. Unfortunately for images, it's not that simple, since Images are non-namespaced objects, but others using them (ImageStreams, Pods, ReplicationControllerss, BuildConfigs, Builds, DeploymentConfigs) are. The only problem here is, that we can't be sure if an Image which might be a candidate for pruning in one namespace, might be still used in others. In other words, we would have to look through all namespaces still but remove only from those specified. 

@miminar @smarterclayton @derekwaynecarr @deads2k thoughts?

**Comment by mfojtik** [comment]
@soltysh I agree. If we support `-n` on prune we should take it into account when pruning.

**Comment by deads2k** [comment]
> In other words, we would have to look through all namespaces still but remove only from those specified.

I don't understand.  Given an image that isn't used in a particular namespace, what would you do?  You can't remove it unless other namespaces aren't using it, but if you're checking other namespaces, it's no longer contained to a namespace.

How about you simply detect if they specified `-n` and then fail?

**Comment by smarterclayton** [comment]
It's likely that prune could prune just the image streams for -n.  But it
definitely can't remove images.

**Comment by soltysh** [comment]
I like @smarterclayton idea. I'll go with that, esp. it's reasonable to reason about, with images being non-namespaced resources.
