### ISSUE TITLE
Environment variables passed to oc new-app are ignored by template

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#9508]
`oc new-app` has a flag `--env` that is documented as:

```
  -e, --env=[]: Specify key value pairs of environment variables to set into each container.
```

And one of the multiple uses of `new-app` is to instantiate a template with `-f`:

```
  -f, --file=[]: Path to a template file to use for the app.
```

One could then assume that both options would work together:

```
oc new-app -f template.json --env FOO=BAR
```

However the environment variables are effectively ignored.

##### Version

```
$ oc version
oc v1.3.0-alpha.1-379-g662753c-dirty
kubernetes v1.3.0-alpha.3-599-g2746284
```

##### Steps To Reproduce
1. `oc new-app -f https://raw.githubusercontent.com/openshift/origin/master/examples/sample-app/application-template-stibuild.json -e NEWAPP=ok`
2. `oc env dc/frontend --list`

##### Current Result

```
$ oc env dc/frontend --list
# deploymentconfigs frontend, container ruby-helloworld
ADMIN_USERNAME=admin67Q
ADMIN_PASSWORD=DjEGRibg
MYSQL_USER=userBFI
MYSQL_PASSWORD=KIiNJnft
MYSQL_DATABASE=root
```

##### Expected Result

Should include the NEWAPP=ok variable, or it should be documented that both `-f` and `-e` don't work together, or a warning/error message.

```
$ oc env dc/frontend --list
# deploymentconfigs frontend, container ruby-helloworld
ADMIN_USERNAME=admin67Q
ADMIN_PASSWORD=DjEGRibg
MYSQL_USER=userBFI
MYSQL_PASSWORD=KIiNJnft
MYSQL_DATABASE=root
NEWAPP=ok
```

##### Additional Information

Pointing `new-app` to a Git repository and setting envs work as expected:

```
$ oc new-app https://github.com/openshift/ruby-hello-world -e NEWAPP=ok
--> Found Docker image 09345a0 (41 hours old) from Docker Hub for "centos/ruby-22-centos7"
...
--> Creating resources with label app=ruby-hello-world ...
    imagestream "ruby-22-centos7" created
    imagestream "ruby-hello-world" created
    buildconfig "ruby-hello-world" created
    deploymentconfig "ruby-hello-world" created
    service "ruby-hello-world" created
--> Success
    Build scheduled, use 'oc logs -f bc/ruby-hello-world' to track its progress.
    Run 'oc status' to view your app.
$ oc env dc/ruby-hello-world --list
# deploymentconfigs ruby-hello-world, container ruby-hello-world
NEWAPP=ok
```

**Comment by rhcarvalho** [comment]
Thanks to @mikenairn for spotting the problem.

@bparees what's your take here? Documentation omission, lacking validation or bug?

**Comment by bparees** [comment]
@rhcarvalho for now it's a documentation omission, we've discussed this problem before, the challenge is we aren't sure where we should add the env variables (just add them to the DCs in the template?  just the BCs?  both?).  And we tend to assume the template should be defining env vars that are needed (potentially as parameters).

**Comment by rhcarvalho** [comment]
> we've discussed this problem before, the challenge is we aren't sure where we should add the env variables (just add them to the DCs in the template? just the BCs? both?).

Correct, now I remember that discussion.

What we could do here is note on the help for `--env` that is doesn't apply to objects created from a template.

**Comment by bparees** [comment]
> What we could do here is note on the help for --env that is doesn't apply to objects created from a template.

yeah, i think that'd be sufficient for now.
