### ISSUE TITLE
Set initial user for 'cluster up'?

### ISSUE THREAD

**Issue by inlandsee** [openshift/origin#9515]
Make it possible to set initial user and password for 'cluster up"

##### Version
oc v1.3.0-alpha.2-171-g16bcdd0-dirty

##### Steps To Reproduce
1. modify master-config.yaml to perform htpasswd_auth with certs
2. oc cluster up 

##### Current Result

oc cluster up reports 'Login to server ... FAIL' because initial user/pw is no longer valid

##### Expected Result

valid login if allowed to specify a different initial user

##### Additional Information

ERROR: [DCli0014 from diagnostic ConfigContexts@openshift/origin/pkg/diagnostics/client/config_contexts.go:285]
       For client config context '/192-168-1-118:8443/developer':
       The server URL is 'https://192.168.1.118:8443'
       The user authentication is 'developer/192-168-1-118:8443'
       The current project is 'default'
       (*errors.StatusError) the server has asked for the client to provide credentials
       
       This means that when we tried to make a request to the master API
       server, the request required credentials that were not presented. This
       can happen with an expired or invalid authentication token. Try logging
       in with this user again.

**Comment by csrwng** [comment]
should be addressed by https://github.com/openshift/origin/pull/11146

**Comment by csrwng** [comment]
#11146 merged. cluster up should no longer try to login if the provider has been changed or user has already been created.
