### ISSUE TITLE
Unclear message when oadm create-node-config is missing --node-client-certificate-authority

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#9519]
Hello,

When configuring Origin on Fedora 24 (using the RPM packages) according to the [installation guide](https://docs.openshift.com/enterprise/3.0/admin_guide/master_node_configuration.html), detailed error messages are returned for various flags (--signer-cert, --signer-key) but not for --node-client-certificate-authority.

Additionally, the paths default to /openshift.local.config rather than /etc/origin where everything has been installed. It would be nice if the Fedora packages overrode paths (through a patch or configuration file) to default to the correct location.
##### Version
# oc version

oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5
# openshift version

openshift v1.1.6
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5
##### Steps To Reproduce

For most commands, the error message describes which flag warnings pertain 

> # oadm create-node-config --node-dir=/etc/origin/node --node=jawnsy-dev --hostnames=10.0.0.1 --certificate-authority=/etc/origin/master/ca.crt
> Generating node credentials ...
> error: --signer-cert, "/etc/origin/master/openshift.local.config/master/ca.crt" must be a valid certificate file
> # oadm create-node-config --node-dir=/etc/origin/node --node=jawnsy-dev --hostnames=10.0.0.1 --certificate-authority=/etc/origin/master/ca.crt --signer-cert=/etc/origin/master/ca.crt --signer-key=/etc/origin/ca.key
> Generating node credentials ...
> error: --signer-key, "/etc/origin/ca.key" must be a valid key file
> # oadm create-node-config --node-dir=/etc/origin/node --node=jawnsy-dev --hostnames=10.0.0.1 --certificate-authority=/etc/origin/master/ca.crt --signer-cert=/etc/origin/master/ca.crt --signer-key=/etc/origin/master/ca.key
> Generating node credentials ...
> error: --signer-serial, "/etc/origin/master/openshift.local.config/master/ca.serial.txt" must be a valid file

However, if `--node-client-certificate-authority` is missing, the error message only shows the path that could not be opened, not the flag that referred to it. It is thus necessary to look at the `oadm create-node-config -h` output to understand which other flags default to this path.

> # oadm create-node-config --node-dir=/etc/origin/node --node=jawnsy-dev --hostnames=10.0.0.1 --certificate-authority=/etc/origin/master/ca.crt --signer-cert=/etc/origin/master/ca.crt --signer-key=/etc/origin/master/ca.key --signer-serial=/etc/origin/master/ca.serial.txt
> Generating node credentials ...
> error: open openshift.local.config/master/ca.crt: no such file or directory

Once this is done, everything works nicely (yay!).

> # oadm create-node-config --node-dir=/etc/origin/node --node=jawnsy-dev --hostnames=10.0.0.1 --certificate-authority=/etc/origin/master/ca.crt --signer-cert=/etc/origin/master/ca.crt --signer-key=/etc/origin/master/ca.key --signer-serial=/etc/origin/master/ca.serial.txt --node-client-certificate-authority=/etc/origin/master/ca.crt
> Generating node credentials ...
> Created node config for jawnsy-dev in /etc/origin/node
##### Current Result

An error message that states simply:

> error: open openshift.local.config/master/ca.crt: no such file or directory
##### Expected Result

> error: --node-client-certificate-authority, "/etc/origin/master/openshift.local.config/master/ca.serial.txt" must be a valid file

(It would also be nice if it defaulted to the value of `--certificate-authority`)

**Comment by PI-Victor** [comment]
partly a dupe of https://github.com/openshift/origin/issues/8312

**Comment by PI-Victor** [comment]
closed the other issue in favor of this because it's a bit more comprehensive, just wanted to highlight the fact that this is an old issue:
https://github.com/openshift/origin/issues/8312#issuecomment-228866330 
https://bugzilla.redhat.com/show_bug.cgi?id=1259913

**Comment by soltysh** [comment]
The flag is currently defaulted to `master/ca.crt` when not specified so I'm guessing this implies all the problems in this issue solved. If not feel free to reopen.
/close
