### ISSUE TITLE
build extended test "should allow to change build log level" fails consistently

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#9524]
@bparees FYI: this fails both locally for me and on ci.openshift.

Logs contain a message that the test does not think should be there.

I have not looked in detail, but I wonder if the recent work from @jupierce either lead to this, or if not, if he could look into fixing this as part of what he is doing.

file is test/extended/builds/start.go

**Comment by jupierce** [comment]
@gabemontero This would have definitely been broken by my changes but should subsequently be fixed by #9428

**Comment by gabemontero** [comment]
cool - thanks for the confirm @jupierce

**Comment by bparees** [comment]
let's leave this open until the PR merges.
