### ISSUE TITLE
build extended test "should accept --from-repo with --commit as input" fails consistently

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#9525]
@bparees FYI: this fails both locally for me and on ci.openshift.

The start-build fails with this flavor (again, both locally and on ci.openshift):
```
Unable to connect to the server: unable to create Git archive of "/home/gmontero/go/src/github.com/openshift/origin/test/extended/testdata/test-build-app" for build: fatal: current working directory is untracked
```

file is test/extended/builds/start.go

**Comment by bparees** [comment]
i'm not sure how that ever worked since the directory in question is not a git repo.

**Comment by bparees** [comment]
@gabemontero ptal, the test in question passed, the remaining failure is the one to be addressed by @jupierce's logging changes.
