### ISSUE TITLE
build extended test "should create a image via new-build" fails consistently

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#9526]
@bparees FYI: fails consistently both locally and on ci.openshift

We've discussed this previously, and there is a long term plan, so this is more for tracking purposes.  It uses the origin-base image, which has not been re-published since the docker v1.10 debacle.  The build fails with 

```
Trying to pull repository docker.io/openshift/origin-base ... 
manifest unknown: manifest unknown
F0623 20:51:40.362871       1 helpers.go:107] error: build error: manifest unknown: manifest unknown
```

file is test/extended/builds/dockerfile.go

**Comment by bparees** [comment]
yeah this will be fixed when the docker1.10 issues are addressed.

**Comment by bparees** [comment]
assigning to @danmcp since he's tracking when we get the docker1.10 rhel patches in our infrastructure.

**Comment by danmcp** [comment]
Do we want to dup this on: https://github.com/openshift/origin/issues/9122

**Comment by bparees** [comment]
I'm inclined to say no.  there are really two issues/fixes:
1) openshift tolerating images pushed w/ "bad' manifest data (9122)
2) us pushing our infrastructure images with correct manifest data (this issue)

if we got (1) then we wouldn't need (2) of course.  but i'm not clear what path we're on for resolution, i thought we were more on path (2) (updating the rhel docker1.10 distribution to push v1 metadata)

**Comment by danmcp** [comment]
@bparees Okay I get the distinction now.  Assigning to jwhonce as this is a tracker for: https://github.com/projectatomic/docker/pull/169

**Comment by stevekuznetsov** [comment]
Has been fixed.
