### ISSUE TITLE
Rework the deploymentconfig reaper

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9532]
The way the dc reaper currently works:
```
$ oc delete dc/foo
- Delete foo
- Delete all deployments (rcs) of foo
```

Now that we have pausing, we should move the deletion of the config in the end and delete rcs first.
```
$ oc delete dc/foo
- Pause foo
- Delete all deployments (rcs) of foo
- Delete foo
```

cc: @mfojtik @bparees 

@mfojtik assigning to you since you are working on the reaper already

**Comment by mfojtik** [comment]
@kargakis we have pausing?

**Comment by kargakis** [comment]
@mfojtik ever since https://github.com/openshift/origin/pull/9086

**Comment by kargakis** [comment]
@mfojtik for a reference have a look at the upstream reaper for Deployments: https://github.com/kubernetes/kubernetes/blob/c0c2e9d9fd928b7deaaf09ea40b1a9a4e3488845/pkg/kubectl/stop.go#L362

**Comment by mfojtik** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lAJPH0jU&#x2F;747-5-fix-origin-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (5) Fix origin issues</a>
