### ISSUE TITLE
Docker-compose with sti build

### ISSUE THREAD

**Issue by charliemaiors** [openshift/origin#9538]
Hi,

this is a generic question, not really an issue. I would know if is possible to define a docker-compose build with one image which came from a build process with s2i build procedure. Thanks in advance.

Best Regards

**Comment by bparees** [comment]
sure, images that come from s2i are just like any other docker image, so you can use them in the same way you'd use any other image.

**Comment by charliemaiors** [comment]
In order to enable this I've to define a build config with standard s2i build process, but which image name I've to put inside the compose file? The whole name generated by the build process? Thanks in advance.

**Comment by bparees** [comment]
yes, the full name.  or you can re-tag the image after it's built to something else, particularly if your buildconfig is including the openshift registry ip in the name.
