### ISSUE TITLE
Godeps kubernetes hash does not match any commit

### ISSUE THREAD

**Issue by lpabon** [openshift/origin#9546]
Question:
Why do the Godeps kubernetes hashes never match any commit hash from Kubernetes?  Where do they come from?

**Comment by liggitt** [comment]
they come from the https://github.com/openshift/kubernetes repo, which includes the base kubernetes repo and various carries we have for maintaining compatibility with previous releases

**Comment by lpabon** [comment]
Awesome! Thanks!
