### ISSUE TITLE
devmapper driver flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9548]
```
failed to register layer: devicemapper: Error running deviceResume dm_task_run failed
F0624 14:23:42.011832       1 helpers.go:107] error: build error: failed to register layer: devicemapper: Error running deviceResume dm_task_run failed
error: The build extended-test-build-no-outputname-moynj-m22ea/test-docker-1 status is "Failed"
```

as seen in:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2563/consoleFull

Not sure what component label to use for this, @danmcp.

**Comment by jwhonce** [comment]
@rhvgoyal Do you have any insight here?

**Comment by rhvgoyal** [comment]
cc @shishir-a412ed

**Comment by shishir-a412ed** [comment]
@jwhonce I agree this looks like the race condition issue.
https://github.com/docker/docker/issues/23418

A fix is already proposed upstream and internally (projectatomic/docker)

Upstream: https://github.com/docker/docker/pull/23497
Projectatomic/docker: https://github.com/projectatomic/docker/pull/171

**Comment by bparees** [comment]
recurred here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2798/consoleFull

**Comment by jwhonce** [comment]
The current plan is to get a build by @runcom  for testing https://github.com/projectatomic/docker/pull/171#issuecomment-225977662

**Comment by runcom** [comment]
@jwhonce is that for RHEL? if it is @lsm5 might give you that because I don't have any RHEL build machine (I never had, fedora only)

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3199/consoleFull

**Comment by smarterclayton** [comment]
Do we have a plan to get a fix tested?

**Comment by jwhonce** [comment]
@bparees Which OS and Docker version are the jenkins tests using?

**Comment by bparees** [comment]
@jwhonce 
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

$ uname -a
Linux ip-172-18-10-184.ec2.internal 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 9 10:09:10 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.3.x86_64
 Go version:      go1.6.2
 Git commit:      969e2ce-unsupported
 Built:           Tue Jul  5 17:10:57 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.3.x86_64
 Go version:      go1.6.2
 Git commit:      969e2ce-unsupported
 Built:           Tue Jul  5 17:10:57 2016
 OS/Arch:         linux/amd64
```

**Comment by jwhonce** [comment]
@shishir-a412ed @rhvgoyal Looking at the git logs @shishir-a412ed 's patch should be included in the version of docker being run here. Any other ideas?

**Comment by bparees** [comment]
@jwhonce @shishir-a412ed @rhvgoyal is this another form of the same bug?
```
F0730 11:25:29.985953       1 helpers.go:108] error: build error: open /dev/mapper/docker-202:2-50512749-36414ad9688ecd4e76f41c686c014523ab0f06bdc075ed2e3381c5b58ed858ce: no such file or directory
```

as seen here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/4391/consoleFull

**Comment by shishir-a412ed** [comment]
@bparees Which docker operation is throwing this error ? docker build ?
Is this also on docker 1.10.3  on Red Hat Enterprise Linux Server release 7.2 (Maipo) ?

Do you have some steps which I can use to reproduce this error ?

Shishir

**Comment by bparees** [comment]
@shishir-a412ed it's the same infrastructure, yes.  it occurred during a docker build operation as you can see from the logs i linked, it's just a standard docker build operation against a dockerfile.  Looks like it was performing a COPY operation at the time.

**Comment by mdshuai** [comment]
When test this error in our env, "Error response from daemon: devicemapper: Error running deviceCreate (createSnapDevice) dm_task_run failed"
https://bugzilla.redhat.com/show_bug.cgi?id=1362131

**Comment by jwhonce** [comment]
@bparees Has this issue been seen since https://bugzilla.redhat.com/show_bug.cgi?id=1362109#c43 ?

**Comment by bparees** [comment]
@jwhonce 
The FCM in jenkins, which matches on:
.*Error running deviceResume dm_task_run failed.*
and
.*Driver devicemapper failed to remove root filesystem.*

shows it last occurred on 9/2/16:
https://github.com/openshift/origin/pull/10708#issuecomment-244079722

**Comment by runcom** [comment]
@jwhonce @bparees we added a backport to 1.12.1 and 1.10.3 (Fedora and RHEL) which I think addresses this flake (and race):

1.12: https://github.com/projectatomic/docker/commit/4ad9a6417b1b86702d330edffb33aaf4a88c76f3
1.10.3: https://github.com/projectatomic/docker/commit/a612434f4fa5da18833706885c24a1786dfac8e2

I built just this morning both versions in Fedora FWIW.
