### ISSUE TITLE
Docker registry should handle a case of upload without a tag

### ISSUE THREAD

**Issue by miminar** [openshift/origin#9550]
The new registry 2.4 is [structured in a way](https://github.com/docker/distribution/blob/release/2.4/registry/storage/manifeststore.go#L113) that allows for a separated push of a manifest without a tag and a later assignment of tag. Right now tag is passed as an option to a `manifestStore.Put()` which we handle. In the future, it's possible that tag won't be even passed and that docker client will allow for a manifest push without tagging it.

We need to handle above cases.

Proposed solution:
- on `manifestStore.Put()` lacking any tag, just create an image in etcd (currently we just fail)
- on `tagStore.Tag()`, tag the image into image stream
##### Version

once #8938 lands

**Comment by dmage** [comment]
```
2017/04/20 15:12:30 > PUT http://172.30.1.1:5000/v2/myproject/foo/manifests/sha256:bceb34367da85d2b9d4772107e84694cef4b4aab265acbdde0eb0135ade54083 HTTP/1.1
2017/04/20 15:12:30 > Authorization: Bearer ahq_x3yUIGuTajXnsz_hWoJpce5GUVXSwOFRJCAamHk
2017/04/20 15:12:30 > Content-Type: application/vnd.docker.distribution.manifest.v1+json
2017/04/20 15:12:30 > ...
2017/04/20 15:12:30 < HTTP/1.1 500 Internal Server Error
2017/04/20 15:12:30 < Content-Length: 402
2017/04/20 15:12:30 < Content-Type: application/json; charset=utf-8
2017/04/20 15:12:30 < Date: Thu, 20 Apr 2017 13:12:30 GMT
2017/04/20 15:12:30 < Docker-Distribution-Api-Version: registry/2.0
2017/04/20 15:12:30 < X-Registry-Supports-Signatures: 1
2017/04/20 15:12:30 < ...
2017/04/20 15:12:30 {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"ErrStatus":{"metadata":{},"status":"Failure","message":"ImageStreamMapping.image.openshift.io \"foo\" is invalid: tag: Required value","reason":"Invalid","details":{"name":"foo","group":"image.openshift.io","kind":"ImageStreamMapping","causes":[{"reason":"FieldValueRequired","message":"Required value","field":"tag"}]},"code":422}}}]}
```

**Comment by dmage** [comment]
> on manifestStore.Put() lacking any tag, just create an image in etcd

This really conflicts with our desire to prune images that are not assigned to image steams.

**Comment by bparees** [comment]
trello'd: https://trello.com/c/RgCp1ddh
