### ISSUE TITLE
Build controllers should use a shared cache for builds/buildconfigs/imagestreams/pods

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9551]
Similiar to the work done in https://github.com/openshift/origin/pull/9485 for deployments

cc: @bparees @deads2k @smarterclayton

**Comment by deads2k** [comment]
This change would also standardize this controller on the same infrastructure as all the other ones, to avoid one-off problems like https://github.com/openshift/origin/issues/9861

**Comment by bparees** [comment]
@deads2k's best practices for controller authoring: https://github.com/kubernetes/kubernetes/pull/32778

will try to follow this when i update our controllers :)

**Comment by bparees** [comment]
opened in trello, closing here: https://trello.com/c/LlC0nHkT
