### ISSUE TITLE
Add Patch in our clients

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9562]
Currently added upstream in various pulls, this issue is for the work that needs to be done for our namespacers.

@deads2k @smarterclayton @mfojtik

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/27600 adds to clientset

**Comment by mfojtik** [comment]
@kargakis dunno if this will be picked up with @smarterclayton rebase, but we just need to rerun the update-clientset script.

**Comment by mfojtik** [comment]
(I will add `Patch()` to `pkg/client/*` as there are people using that package and we use it on many places already, but the long-term plan is to migrate to clientset)

**Comment by deads2k** [comment]
> I will add Patch() to pkg/client/*

I don't see a strong need, places that need it can lead the transition to clientsets.

Are you going to update for the rest of our objects and pull over the one-offs?

**Comment by mfojtik** [comment]
@deads2k yeah, more I'm digging into what everything will need update, more I'm inclined to simple transition to clientsets. Is the plan to switch `pkg/client` to use clientset entirely? (so in theory, I can just import `github.com/openshift/origin/pkg/client` and I have access to all resources. Or is this the uber-client scenario, we want to avoid?

**Comment by deads2k** [comment]
> Is the plan to switch pkg/client to use clientset entirely? (so in theory, I can just import github.com/openshift/origin/pkg/client and I have access to all resources. Or is this the uber-client scenario, we want to avoid?

We want to try, but we'll probably have to fix up the generator on our way through.  Right now, "unusual" resources have to have hand-coded extension points wired in and if you're really unusual you have to write the entire thing yourself.

We've been enforcing the "use a namespacer" rule during reviews, so we've started subdividing already

**Comment by mfojtik** [comment]
@kargakis we will start transition to cliensets for selected controllers after 3.3

**Comment by kargakis** [comment]
@mfojtik fixed?
