### ISSUE TITLE
don't split string args on commas by default

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9565]
pflag automatically splits any StringSlice arguments on commas:
https://github.com/spf13/pflag/blob/master/string_slice.go#L52

This means arguments like -v and -p that take env variables and parameter values, can't contain commas in the value.  Instead of using this default behavior, so we need our own String arg implementation in our cli tools.

@smarterclayton 

assigning to @fabianofranz for now but it may make more sense to divide this among people who own different cli tools.

**Comment by smarterclayton** [comment]
This is really an upstream issue too - it affects anything naively using
stringslice and expecting it to not mangle inputs.

On Jun 25, 2016, at 8:21 PM, Ben Parees <notifications@github.com> wrote:

pflag automatically splits any StringSlice arguments:
https://github.com/spf13/pflag/blob/master/string_slice.go#L52

This means arguments like -v and -p that take env variables and parameter
values, can't contain commas in the value. Instead of using this default
behavior, so we need our own String arg implementation in our cli tools.

@smarterclayton <https://github.com/smarterclayton>

assigning to @fabianofranz <https://github.com/fabianofranz> for now but it
may make more sense to divide this among people who own different cli tools.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9565>, or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p28G47SEGqyOgCzoUoSzmEgt7MOmks5qPcYegaJpZM4I-dQk>
.

**Comment by bparees** [comment]
> Having different rules for delimiters for some multi-specified flags seems like a difficult thing to explain to people.

having an arbitrary universal delimeter seems like a difficult thing to justify to people.

in any case it's easy enough for the flag description in the help to indicate whether/what delimeter it uses.

**Comment by liggitt** [comment]
Is applying CSV escaping from the CLI easy for arbitrary values?

**Comment by deads2k** [comment]
> in any case it's easy enough for the flag description in the help to indicate whether/what delimeter it uses.

I think that people will get used to "arrays a parsed like this" and never read the delimiter details inside of help.  



> having an arbitrary universal delimeter seems like a difficult thing to justify to people.

Choosing a "normal" one being consistent in its usage seems very justifiable.  I shouldn't have to read help pages to format my flag args.

**Comment by deads2k** [comment]
> Is applying CSV escaping from the CLI easy for arbitrary values?

It's pretty normal thing to do and follows the normal rules
`--flag='"foo,bar"'` is `{"foo,bar"}`
`--flag="foo,bar"` is `{"foo","bar"}`

**Comment by bparees** [comment]
> Choosing a "normal" one being consistent in its usage seems very justifiable. I shouldn't have to read help pages to format my flag args.

right up until someone says "why would you make comma the delimeter for this arg, when commas appear in those values naturally all the time"

anyway imho comma separation for arg values is a poor way to go for precisely this reason.  repeating the flag makes more sense, then there is *never* a question of what the delimeter is, whether it can be escaped, etc.

**Comment by bparees** [comment]
> It's pretty normal thing to do and follows the normal rules
--flag='"foo,bar"' is {"foo,bar"}
--flag="foo,bar" is {"foo","bar"}

lol.

**Comment by liggitt** [comment]
…

Yeah, I vastly prefer repeating flags only for multi-value fields. Not sure whether it's worth the compatibility hit, but I don't think CSV escaping is a very usable solution

**Comment by smarterclayton** [comment]
It's not.

**Comment by liggitt** [comment]
it's not worth it? or it's not usable?

**Comment by smarterclayton** [comment]
It's not usable.  We have multiple flag values to convey multiple things.  Don't have two ways to do the same thing, especially when it is so fundamental.

**Comment by smarterclayton** [comment]
We need to rename StringSlice upstream to SplittingStringSplice and create a new non splitting one called StringSlice.  People need to opt into broken behavior.  We need to sweep each command and determine whether it is broken by splitting.  And we need to stop the bleeding.

**Comment by smarterclayton** [comment]
I'm 99% sure this was introduced for the etcd servers list (which was comma delimited) and leaked out into the rest of the code

**Comment by deads2k** [comment]
> I'm 99% sure this was introduced for the etcd servers list (which was comma delimited) and leaked out into the rest of the code

https://github.com/kubernetes/kubernetes/pull/789 and got brought into our code for cors: https://github.com/openshift/origin/pull/154

**Comment by bparees** [comment]
@juanvallejo this can probably be closed at this point (at a minimum i think we've fixed all our flags that used to use comma separated multivalue args) but will let you guys make the call.

**Comment by juanvallejo** [comment]
@bparees thanks, closing.
@soltysh fyi
