### ISSUE TITLE
Adding certificates fails on creating new advanced origin installation (Centos7 or Fedora24)

### ISSUE THREAD

**Issue by kaspro** [openshift/origin#9569]
Advanced installation (1 master 2 nodes) fails on "TASK [Unarchive the tarball on the node]" after "TASK [Ensure certificate directory exists]"
##### Steps To Reproduce
1. Use the example config from the advanced installation, uncomment the htaccess config
2. Run the ansible on Centos7 or Fedora24
##### Current Result

fatal: [node-i01.oc.example.loc]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/etc/origin/node/./system:node:node-i01.oc.example.loc.crt'"}
fatal: [node-i02.oc.example.loc]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/etc/origin/node/./system:node:node-i02.oc.example.loc.crt'"}
fatal: [master.oc.example.loc]: FAILED! => {"changed": false, "failed": true, "msg": "path /etc/origin/node/./system:node:master.oc.example.loc.crt does not exist", "path": "/etc/origin/node/./system:node:master.oc.example.loc.crt", "state": "absent"}
##### Expected Result

Successful installation

I also tried with submitting my own certificates, which fails with the same result.

Thanks in advance for any hints,
Cheers Chris

**Comment by tj13** [comment]
also met the same issue both with latest master or enterprise-3.2 branch code. anyone knows how to fix it?

**Comment by detiber** [comment]
@abutcher can you take a closer look?

**Comment by abutcher** [comment]
This looks like it could be an issue with the unarchive module.

Which version of ansible are you using and could you provide verbose output for the failing task (run ansible with `-vvv`)?

**Comment by tj13** [comment]
@abutcher info is as below.  

`$ ansible-playbook --version`
`ansible-playbook 2.1.0.0`
  `config file = /etc/ansible/ansible.cfg`
  `configured module search path = Default w/o overrides`

`TASK [Unarchive the tarball on the etcd host] **********************************
task path: /home/tanjun/openshift-ansible/playbooks/common/openshift-etcd/config.yml:81
<cjjoc01e01.sit.caijj.net> ESTABLISH SSH CONNECTION FOR USER: tanjun
<cjjoc01e01.sit.caijj.net> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=tanjun -o ConnectTimeout=10 -o ControlPath=/home/tanjun/.ansible/cp/ansible-ssh-%h-%p-%r cjjoc01e01.sit.caijj.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467876143.65-235398810422519 `" && echo ansible-tmp-1467876143.65-235398810422519="` echo $HOME/.ansible/tmp/ansible-tmp-1467876143.65-235398810422519 `" ) && sleep 0'"'"''
<cjjoc01e01.sit.caijj.net> ESTABLISH SSH CONNECTION FOR USER: tanjun
<cjjoc01e01.sit.caijj.net> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=tanjun -o ConnectTimeout=10 -o ControlPath=/home/tanjun/.ansible/cp/ansible-ssh-%h-%p-%r cjjoc01e01.sit.caijj.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467876143.67-78785187265330 `" && echo ansible-tmp-1467876143.67-78785187265330="` echo $HOME/.ansible/tmp/ansible-tmp-1467876143.67-78785187265330 `" ) && sleep 0'"'"''
<cjjoc01e01.sit.caijj.net> PUT /tmp/tmpfAbNyX TO /home/tanjun/.ansible/tmp/ansible-tmp-1467876143.67-78785187265330/stat
<cjjoc01e01.sit.caijj.net> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=tanjun -o ConnectTimeout=10 -o ControlPath=/home/tanjun/.ansible/cp/ansible-ssh-%h-%p-%r '[cjjoc01e01.sit.caijj.net]'
<cjjoc01e01.sit.caijj.net> ESTABLISH SSH CONNECTION FOR USER: tanjun
<cjjoc01e01.sit.caijj.net> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=tanjun -o ConnectTimeout=10 -o ControlPath=/home/tanjun/.ansible/cp/ansible-ssh-%h-%p-%r -tt cjjoc01e01.sit.caijj.net '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-lgdggzlvlskkxbgpnzixpuymitzwvsxs; LANG=zh_CN.UTF-8 LC_ALL=zh_CN.UTF-8 LC_MESSAGES=zh_CN.UTF-8 /usr/bin/python /home/tanjun/.ansible/tmp/ansible-tmp-1467876143.67-78785187265330/stat; rm -rf "/home/tanjun/.ansible/tmp/ansible-tmp-1467876143.67-78785187265330/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<cjjoc01e01.sit.caijj.net> PUT /tmp/openshift-ansible-TRjPkU4/etcd-cjjoc01e01.sit.caijj.net.tgz TO /home/tanjun/.ansible/tmp/ansible-tmp-1467876143.65-235398810422519/source
<cjjoc01e01.sit.caijj.net> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=tanjun -o ConnectTimeout=10 -o ControlPath=/home/tanjun/.ansible/cp/ansible-ssh-%h-%p-%r '[cjjoc01e01.sit.caijj.net]'
<cjjoc01e01.sit.caijj.net> ESTABLISH SSH CONNECTION FOR USER: tanjun
<cjjoc01e01.sit.caijj.net> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=tanjun -o ConnectTimeout=10 -o ControlPath=/home/tanjun/.ansible/cp/ansible-ssh-%h-%p-%r cjjoc01e01.sit.caijj.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467876144.18-188939129623000 `" && echo ansible-tmp-1467876144.18-188939129623000="` echo $HOME/.ansible/tmp/ansible-tmp-1467876144.18-188939129623000 `" ) && sleep 0'"'"''
<cjjoc01e01.sit.caijj.net> PUT /tmp/tmpxnx2pN TO /home/tanjun/.ansible/tmp/ansible-tmp-1467876144.18-188939129623000/unarchive
<cjjoc01e01.sit.caijj.net> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=tanjun -o ConnectTimeout=10 -o ControlPath=/home/tanjun/.ansible/cp/ansible-ssh-%h-%p-%r '[cjjoc01e01.sit.caijj.net]'
<cjjoc01e01.sit.caijj.net> ESTABLISH SSH CONNECTION FOR USER: tanjun
<cjjoc01e01.sit.caijj.net> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=tanjun -o ConnectTimeout=10 -o ControlPath=/home/tanjun/.ansible/cp/ansible-ssh-%h-%p-%r -tt cjjoc01e01.sit.caijj.net '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-kyuwijfxirpzlagomqzppiyhimdbfoxk; LANG=zh_CN.UTF-8 LC_ALL=zh_CN.UTF-8 LC_MESSAGES=zh_CN.UTF-8 /usr/bin/python /home/tanjun/.ansible/tmp/ansible-tmp-1467876144.18-188939129623000/unarchive; rm -rf "/home/tanjun/.ansible/tmp/ansible-tmp-1467876144.18-188939129623000/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<cjjoc01e01.sit.caijj.net> ESTABLISH SSH CONNECTION FOR USER: tanjun
<cjjoc01e01.sit.caijj.net> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=tanjun -o ConnectTimeout=10 -o ControlPath=/home/tanjun/.ansible/cp/ansible-ssh-%h-%p-%r cjjoc01e01.sit.caijj.net '/bin/sh -c '"'"'rm -f -r /home/tanjun/.ansible/tmp/ansible-tmp-1467876143.65-235398810422519/ > /dev/null 2>&1 && sleep 0'"'"''
fatal: [cjjoc01e01.sit.caijj.net]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"backup": null, "content": null, "copy": true, "creates": null, "delimiter": null, "dest": "/etc/etcd", "directory_mode": null, "exclude": [], "extra_opts": [], "follow": false, "force": null, "group": null, "keep_newer": false, "list_files": false, "mode": null, "original_basename": "etcd-cjjoc01e01.sit.caijj.net.tgz", "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/home/tanjun/.ansible/tmp/ansible-tmp-1467876143.65-235398810422519/source"}}, "msg": "Unexpected error when accessing exploded file: [Errno 2] 没有那个文件或目录: '/etc/etcd/./server.key'"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/home/tanjun/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
cjjoc01e01.sit.caijj.net   : ok=63   changed=5    unreachable=0    failed=1   
cjjoc01e02.sit.caijj.net   : ok=32   changed=0    unreachable=0    failed=0   
cjjoc01e03.sit.caijj.net   : ok=32   changed=0    unreachable=0    failed=0   
cjjoc01m01.sit.caijj.net   : ok=22   changed=0    unreachable=0    failed=0   
localhost                  : ok=10   changed=8    unreachable=0    failed=0   

`

**Comment by tj13** [comment]
installation with ansible 1.9.6 successfully.

**Comment by abutcher** [comment]
@tj13 Could you try with ansible's `stable-2.1` branch? I believe this may have been fixed in [ansible-modules-core#3767](https://github.com/ansible/ansible-modules-core/pull/3767)

To test using an ansible checkout:
```
$ git clone git@github.com:ansible/ansible.git
$ cd ansible
$ git checkout stable-2.1
$ git submodule update --init --recursive
$ . ./hacking/env-setup
```

Now we're running latest `stable-2.1`:
```
$ ansible --version
ansible 2.1.1.0 (stable-2.1 9eb32357de) last updated 2016/07/07 14:49:45 (GMT -400)
  lib/ansible/modules/core: (detached HEAD c8d6886007) last updated 2016/07/07 14:51:49 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 4d6afbcb62) last updated 2016/07/07 14:51:51 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by tj13** [comment]
@abutcher ansible's stable-2.1 is also fine. 

PLAY RECAP *********************************************************************
cjjoc01e01.sit.caijj.net   : ok=185  changed=48   unreachable=0    failed=0   
cjjoc01e02.sit.caijj.net   : ok=131  changed=28   unreachable=0    failed=0   
cjjoc01e03.sit.caijj.net   : ok=131  changed=29   unreachable=0    failed=0   
cjjoc01m01.sit.caijj.net   : ok=321  changed=63   unreachable=0    failed=0   
localhost                  : ok=17   changed=8    unreachable=0    failed=0

**Comment by abutcher** [comment]
Thanks for confirming @tj13
