### ISSUE TITLE
Many commands do poorly when pods take ~30s to go to pending

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9572]
```
oc logs bc,dc
oc start-build --from-dir
```

all behaved badly (user was effectively broken).  Need to evaluate timeouts and wait periods.  Taking upwards of a minute for a pod to transition to running is reasonable, and the CLI needs to do a better job of dealing with .

**Comment by smarterclayton** [comment]
@fabianofranz @kargakis

**Comment by smarterclayton** [comment]
@bparees

**Comment by kargakis** [comment]
Regarding build and deployment logs, both use podLogOptions and that one should have a timeout param wired to the server.

**Comment by smarterclayton** [comment]
We may need to fix the timeout behavior for those commands, either through
a longer default or via a better mechanism.

On Jun 27, 2016, at 2:31 AM, Michail Kargakis <notifications@github.com>
wrote:

Regarding build and deployment logs, both use podLogOptions and that one
should have a timeout param wired to the server.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9572#issuecomment-228697062>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p9k0vFdvWyGqhA-v-9bV9izFW43-ks5qP5iIgaJpZM4I-qjQ>
.

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/41813 adds a flag for setting a timeout for logs and attach. We need to make sure we set a reasonable default.
