### ISSUE TITLE
[oc client] [mac os x] No such host on pingable server.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#9585]
**Problem**

 On mac os x oc clients, im finding that a pingable server is reported  (via the oc client)  as  message "no such host".   the clients in this case are downloaded from the openshift downloads (iirc https://docs.openshift.com/enterprise/3.0/cli_reference/get_started_cli.html#installing-the-cli).

**Example**

ping works... 
```
➜  ~  ping ce-os-rhel-master.usersys.redhat.com
PING ce-os-rhel-master.usersys.redhat.com (10.34.75.159): 56 data bytes
64 bytes from 10.34.75.159: icmp_seq=0 ttl=57 time=179.213 ms
--- ce-os-rhel-master.usersys.redhat.com ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 179.213/179.213/179.213/0.000 ms
```

but.. any attempts at trying to get the `oc client` to see this host fails,   All result in `no such host`, which is innaccurate, since the host is pingable from the same terminal... 

```
➜  ~  oc login https://ce-os-rhel-master.usersys.redhat.com
Unable to connect to the server: dial tcp: lookup ce-os-rhel-master.usersys.redhat.com: no such host
```

```
➜  ~  oc login ce-os-rhel-master.usersys.redhat.com
Unable to connect to the server: dial tcp: lookup ce-os-rhel-master.usersys.redhat.com: no such host
```

```
➜  ~  oc login http://ce-os-rhel-master.usersys.redhat.com
Unable to connect to the server: dial tcp: lookup ce-os-rhel-master.usersys.redhat.com: no such host
```

```
➜  ~  oc login http://ce-os-rhel-master.usersys.redhat.com:8443
Unable to connect to the server: dial tcp: lookup ce-os-rhel-master.usersys.redhat.com: no such host
```

**Solution**

The oc client maybe needs to correct its interpretation regarding wether a host is available or not

**Version**

```
oc3116 v3.1.1.6-64-g80b61da
kubernetes v1.1.0-origin-1107-g4c8e6f4
```

**Comment by jayunit100** [comment]
This may be b/c the client can get stale or something ?

**Comment by fabianofranz** [comment]
@jayunit100 Can you add the output of running the login command with `--loglevel=10`, please?
