### ISSUE TITLE
No Package matching 'origin' found available, installed or updated

### ISSUE THREAD

**Issue by enlinxu** [openshift/origin#9589]
When using the latest openshift-ansible to deploy a non-HA cluster, after following the steps here (https://docs.openshift.org/latest/install_config/install/advanced_install.html), I am getting:
TASK [openshift_common : Install the base package for versioning] **************
fatal: [10.10.174.90]: FAILED! => {"changed": false, "failed": true, "msg": "No Package matching 'origin' found available, installed or updated", "rc": 0, "results": []}

Here is my /etc/ansible/hosts :
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]

# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

deployment_type=origin
# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
# host group for masters
[masters]
10.10.174.90

# host group for nodes, includes region info
[nodes]
10.10.174.90 openshift_node_labels="{'env': 'dev'}"
10.10.174.88 openshift_node_labels="{'env': 'prod'}"
10.10.174.89 openshift_node_labels="{'env': 'dev'}"

Any help is appreciate.

**Comment by sdodson** [comment]
@enlinxu your OS is RHEL, correct? We don't currently have a good method to install centos paas repos on rhel. I can hack something up for that scenario.

**Comment by enlinxu** [comment]
@sdodson , yes, we are using RHEL 7, and I followed the online tutorial ( https://docs.openshift.org/latest/install_config/install/advanced_install.html ), so the tutorial needs to be updated?
Appreciate any help!

**Comment by sdodson** [comment]
@enlinxu You can try my PR, `git pull https://github.com/sdodson/openshift-ansible rhel-origin`  should apply the changes to your checkout.

**Comment by enlinxu** [comment]
@sdodson Thanks. But after I shift to your branch, I started to have this issue.
https://github.com/ansible/ansible/issues/14665

TASK [nuage_node : include] ****************************************************
skipping: [10.10.174.90]

TASK [nuage_node : Set the vsp-openshift.yaml] *********************************
skipping: [10.10.174.90]

TASK [nickhammond.logrotate : nickhammond.logrotate | Install logrotate] *******
ok: [10.10.174.90]

TASK [nickhammond.logrotate : nickhammond.logrotate | Setup logrotate.d scripts] ***
skipping: [10.10.174.90] => (item=logrotate_scripts) 

TASK [Create group for deployment type] ****************************************
ok: [10.10.174.90]

NO MORE HOSTS LEFT *************************************************************

PLAY [Delete temporary directory on localhost] *********************************
**ERROR! invalid host (10.10.174.88) specified for playbook iteration**

**Comment by enlinxu** [comment]
hi @sdodson . I am having this issue again recently. Same set up, but complains about origin package not matching. It is looking for origin-1.4+c1e84da

TASK [openshift_common : Install the base package for versioning] **************
fatal: [10.10.174.88]: FAILED! => {"changed": false, "failed": true, "msg": "No Package matching 'origin-1.4+c1e84da' found available, installed or updated", "rc": 0, "results": []}
