### ISSUE TITLE
[Question] Security Context Constraints (SCC) association

### ISSUE THREAD

**Issue by ltagliamonte** [openshift/origin#9591]
Instead of modify the restricted SCC as described: [`here`](https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html#modify-cluster-default-behavior) can i associate a SCC to a project or to a namespace?
If yes how to do it?
Thanks in advance for any reply.

**Comment by pweil-** [comment]
Not directly to a project or namespace but you may create new SCCs and use the `users` and `groups` to grant access to the SCC.  https://docs.openshift.org/latest/admin_guide/manage_scc.html#grant-access-to-the-privileged-scc

If you would like to ensure your new SCC is used to validate before any of the other SCCs you may set the priority https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#scc-prioritization.

Let me know if that doesn't answer your question.  Thanks!
