### ISSUE TITLE
Make LegacyPrefix configurable for generated clients

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#9594]
The prefix is currently hardcoded to `/api` where OpenShift API use `/oapi`. See: https://github.com/kubernetes/kubernetes/blob/cbab337b9967663f581165da18126f660b7fa7a8/pkg/client/typed/discovery/discovery_client.go#L291

Follow up for: https://github.com/openshift/origin/pull/9372

**Comment by mfojtik** [comment]
@deads2k @smarterclayton follow up created :-)

**Comment by mfojtik** [comment]
@deads2k @smarterclayton I found that this might not actually be needed as the `DiscoveryClient` already have exported `LegacyPrefix`, so we can just override it to `/oapi` after we initialize the client.

**Comment by kargakis** [comment]
@mfojtik still an issue?
