### ISSUE TITLE
Limit the amount of events displayed in deployment config describer

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#9604]
Follow up for: https://github.com/openshift/origin/pull/9456

We need a way to limit the amount of events displayed in `oc describe`. The upstream now has DescribeConfig field that is passed to every describer. We should use it and see if we can also specify the number of events to be displayed.

@kargakis @smarterclayton FYI

**Comment by kargakis** [comment]
In `oc status` we trim the output down to three deployments, upstream we are talking about defaulting cleanup policy to 2 (which means last three replica sets) so this should be similar (keep events for the last three deployments or maybe less).
