### ISSUE TITLE
Router: fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by mignev** [openshift/origin#9611]
fatal error: concurrent map read and map write

goroutine 74 [running]:
runtime.throw(0x38e0840, 0x21)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8207d3248 sp=0xc8207d3230
runtime.mapaccess2(0x2821460, 0xc820586210, 0xc820cc6dc0, 0x317cc20, 0xc820747740)
	/usr/local/go/src/runtime/hashmap.go:343 +0x5a fp=0xc8207d3290 sp=0xc8207d3248
reflect.mapaccess(0x2821460, 0xc820586210, 0xc820cc6dc0, 0xc820586210)
	/usr/local/go/src/runtime/hashmap.go:993 +0x35 fp=0xc8207d32c0 sp=0xc8207d3290
reflect.Value.MapIndex(0x2821460, 0xc8200eb820, 0x95, 0x2829460, 0xc820cc6dc0, 0x98, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:1041 +0x14a fp=0xc8207d3348 sp=0xc8207d32c0
text/template.(*state).walkRange(0xc8207d38d0, 0x329f620, 0xc8200eb810, 0x99, 0xc820300b00)
	/usr/local/go/src/text/template/exec.go:327 +0x885 fp=0xc8207d3548 sp=0xc8207d3348
text/template.(*state).walk(0xc8207d38d0, 0x329f620, 0xc8200eb810, 0x99, 0x7ff9c96fe048, 0xc820300b00)
	/usr/local/go/src/text/template/exec.go:226 +0x264 fp=0xc8207d3690 sp=0xc8207d3548
text/template.(*state).walk(0xc8207d38d0, 0x329f620, 0xc8200eb810, 0x99, 0x7ff9c9752758, 0xc8202c2990)
	/usr/local/go/src/text/template/exec.go:223 +0x6a1 fp=0xc8207d37d8 sp=0xc8207d3690
text/template.(*Template).Execute(0xc820017940, 0x7ff9c9742398, 0xc8200e6aa8, 0x329f620, 0xc8200eb810, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:178 +0x2a7 fp=0xc8207d3918 sp=0xc8207d37d8
github.com/openshift/origin/pkg/router/template.(*templateRouter).writeConfig(0xc8201685b0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/template/router.go:283 +0x892 fp=0xc8207d3d58 sp=0xc8207d3918
github.com/openshift/origin/pkg/router/template.(*templateRouter).commitAndReload(0xc8201685b0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/template/router.go:231 +0x14d fp=0xc8207d3dc0 sp=0xc8207d3d58
github.com/openshift/origin/pkg/router/template.(*templateRouter).(github.com/openshift/origin/pkg/router/template.commitAndReload)-fm(0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/template/router.go:157 +0x2e fp=0xc8207d3de0 sp=0xc8207d3dc0
github.com/openshift/origin/pkg/util/ratelimiter.(*RateLimitedFunction).handleOne(0xc820586120, 0x33272a0, 0xc820586120)
	/go/src/github.com/openshift/origin/pkg/util/ratelimiter/ratelimiter.go:49 +0x48 fp=0xc8207d3e18 sp=0xc8207d3de0
github.com/openshift/origin/pkg/util/ratelimiter.(*RateLimitedFunction).RunUntil.func1()
	/go/src/github.com/openshift/origin/pkg/util/ratelimiter/ratelimiter.go:42 +0x6a fp=0xc8207d3e60 sp=0xc8207d3e18
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820418bf0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b fp=0xc8207d3e90 sp=0xc8207d3e60
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820418bf0, 0x0, 0x0, 0xc8200e0060)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68 fp=0xc8207d3f50 sp=0xc8207d3e90
k8s.io/kubernetes/pkg/util/wait.Until(0xc820418bf0, 0x0, 0xc8200e0060)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e fp=0xc8207d3f78 sp=0xc8207d3f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8207d3f80 sp=0xc8207d3f78
created by github.com/openshift/origin/pkg/util/ratelimiter.(*RateLimitedFunction).RunUntil
	/go/src/github.com/openshift/origin/pkg/util/ratelimiter/ratelimiter.go:42 +0x7d

goroutine 1 [select (no cases), 5 minutes]:
github.com/openshift/origin/pkg/cmd/infra/router.(*TemplateRouterOptions).Run(0xc8202e8c00, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/cmd/infra/router/template.go:203 +0x85e
github.com/openshift/origin/pkg/cmd/infra/router.NewCommandTemplateRouter.func1(0xc820148200, 0x5ba9638, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/cmd/infra/router/template.go:111 +0x1ad
github.com/spf13/cobra.(*Command).execute(0xc820148200, 0xc82000a1e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x85a
github.com/spf13/cobra.(*Command).ExecuteC(0xc820148200, 0xc820148200, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x53f
github.com/spf13/cobra.(*Command).Execute(0xc820148200, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x2d
main.main()
	/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:27 +0x180

goroutine 17 [syscall, 5 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive, 2 minutes]:
github.com/golang/glog.(*loggingT).flushDaemon(0x5b81500)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 24 [syscall, 4 minutes]:
os/signal.signal_recv(0x7ff9c973e078)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 76 [select]:
k8s.io/kubernetes/pkg/client/cache.(*Reflector).watchHandler(0xc820536d20, 0x7ff9c975ae70, 0xc820d7ac60, 0xc820215c00, 0xc820549800, 0xc82005ae40, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:320 +0x13f7
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc820536d20, 0xc82005ae40, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:287 +0x125f
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x2c
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820292060)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820292060, 0x3b9aca00, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc820292060, 0x3b9aca00, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x84

goroutine 75 [select]:
k8s.io/kubernetes/pkg/client/cache.(*Reflector).watchHandler(0xc820536c80, 0x7ff9c975ae70, 0xc820b0c270, 0xc8207cfbf0, 0xc82080cfc0, 0xc82005ae40, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:320 +0x13f7
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc820536c80, 0xc82005ae40, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:287 +0x125f
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x2c
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820292010)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820292010, 0x3b9aca00, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc820292010, 0x3b9aca00, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x84

goroutine 92 [select]:
net/http.(*persistConn).writeLoop(0xc8208380d0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 77 [runnable]:
github.com/openshift/origin/pkg/router/template.(*templateRouter).cleanUpdates(0xc8201685b0, 0xc8207a1ac0, 0x33, 0xc8207a1b00, 0x31)
	/go/src/github.com/openshift/origin/pkg/router/template/router.go:471 +0x27c
github.com/openshift/origin/pkg/router/template.(*templateRouter).AddRoute(0xc8201685b0, 0xc8207a1ac0, 0x33, 0xc820d963a8, 0xc820ccd640, 0x33, 0x1)
	/go/src/github.com/openshift/origin/pkg/router/template/router.go:456 +0x4fe
github.com/openshift/origin/pkg/router/template.(*TemplatePlugin).HandleRoute(0xc82044b120, 0x3593950, 0x8, 0xc820d963a8, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/template/plugin.go:174 +0x421
github.com/openshift/origin/pkg/router/controller.(*StatusAdmitter).HandleRoute(0xc8205506c0, 0x3593950, 0x8, 0xc820d963a8, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/controller/status.go:295 +0x2e3
github.com/openshift/origin/pkg/router/controller.(*UniqueHost).HandleRoute(0xc820550700, 0x3593950, 0x8, 0xc820d963a8, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/controller/unique_host.go:170 +0x11ee
github.com/openshift/origin/pkg/router/controller.(*RouterController).HandleRoute(0xc820552230)
	/go/src/github.com/openshift/origin/pkg/router/controller/controller.go:84 +0x5ea
github.com/openshift/origin/pkg/router/controller.(*RouterController).HandleRoute-fm()
	/go/src/github.com/openshift/origin/pkg/router/controller/controller.go:46 +0x20
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc8202920c0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8202920c0, 0x0, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc8202920c0, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
k8s.io/kubernetes/pkg/util/wait.Forever(0xc8202920c0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:41 +0x37
created by github.com/openshift/origin/pkg/router/controller.(*RouterController).Run
	/go/src/github.com/openshift/origin/pkg/router/controller/controller.go:46 +0x1da

goroutine 78 [semacquire, 5 minutes]:
sync.runtime_Syncsemacquire(0xc82021a148)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc82021a138)
	/usr/local/go/src/sync/cond.go:63 +0x9b
github.com/openshift/origin/pkg/client/cache.(*EventQueue).Pop(0xc82021a120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/client/cache/eventqueue.go:273 +0xd9
github.com/openshift/origin/pkg/router/controller/factory.(*RouterControllerFactory).Create.func1(0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/pkg/router/controller/factory/factory.go:71 +0x42
github.com/openshift/origin/pkg/router/controller.(*RouterController).HandleEndpoints(0xc820552230)
	/go/src/github.com/openshift/origin/pkg/router/controller/controller.go:91 +0x30
github.com/openshift/origin/pkg/router/controller.(*RouterController).HandleEndpoints-fm()
	/go/src/github.com/openshift/origin/pkg/router/controller/controller.go:47 +0x20
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc8202920d0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8202920d0, 0x0, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc8202920d0, 0x0, 0xc82005ae40)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
k8s.io/kubernetes/pkg/util/wait.Forever(0xc8202920d0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go:41 +0x37
created by github.com/openshift/origin/pkg/router/controller.(*RouterController).Run
	/go/src/github.com/openshift/origin/pkg/router/controller/controller.go:47 +0x239

goroutine 79 [chan receive, 4 minutes]:
github.com/openshift/origin/pkg/util/proc.StartReaper.func1()
	/go/src/github.com/openshift/origin/pkg/util/proc/reaper.go:23 +0x193
created by github.com/openshift/origin/pkg/util/proc.StartReaper
	/go/src/github.com/openshift/origin/pkg/util/proc/reaper.go:35 +0x79

goroutine 80 [select, 5 minutes, locked to thread]:
runtime.gopark(0x3e690f0, 0xc82001ef28, 0x3573f30, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc82001ef28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc82001ef28)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 94 [IO wait]:
net.runtime_pollWait(0x7ff9c970ed70, 0x72, 0xc820c8c000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82052e8b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82052e8b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82052e850, 0xc820c8c000, 0x8000, 0x8000, 0x0, 0x7ff9c973e050, 0xc82000a120)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820024bd8, 0xc820c8c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820d7b4d0, 0x7ff9c970f2c0, 0xc820024bd8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8205b4600, 0x3e69217, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8205b4600, 0xc820881000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x7ff9c97133c8, 0xc8205b4600, 0xc8208383a8, 0xc820881000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc820b7ed00, 0xc820881000, 0x1000, 0x1000, 0xc820d7b020, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc82080ce40)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82080ce40, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
net/http/internal.readChunkLine(0xc82080ce40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/internal/chunked.go:110 +0x53
net/http/internal.(*chunkedReader).beginChunk(0xc820b0c150)
	/usr/local/go/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0xc820b0c150, 0xc82019e200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0xc820c98000, 0xc82019e200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:651 +0xa1
net/http.(*body).Read(0xc820c98000, 0xc82019e200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:643 +0x110
net/http.(*bodyEOFSignal).Read(0xc820c98040, 0xc82019e200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1609 +0x26a
encoding/json.(*Decoder).refill(0xc82005e1a0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc82005e1a0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:128 +0x413
encoding/json.(*Decoder).Decode(0xc82005e1a0, 0x275d780, 0xc820c980c0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:57 +0x159
k8s.io/kubernetes/pkg/watch/json.(*Decoder).Decode(0xc820b0c1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/json/decoder.go:50 +0xa5
k8s.io/kubernetes/pkg/watch.(*StreamWatcher).receive(0xc820b0c270)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:93 +0x104
created by k8s.io/kubernetes/pkg/watch.NewStreamWatcher
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:60 +0xbf

goroutine 91 [select]:
net/http.(*persistConn).readLoop(0xc8208380d0)
	/usr/local/go/src/net/http/transport.go:1178 +0xd52
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 103 [IO wait]:
net.runtime_pollWait(0x7ff9c970eef0, 0x72, 0xc820d82c00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82052e450, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82052e450, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82052e3f0, 0xc820d82c00, 0x400, 0x400, 0x0, 0x7ff9c973e050, 0xc82000a120)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200248d8, 0xc820d82c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820d538c0, 0x7ff9c970f2c0, 0xc8200248d8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8205b4300, 0x3e69217, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8205b4300, 0xc820b26000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x7ff9c97133c8, 0xc8205b4300, 0xc820838138, 0xc820b26000, 0x1000, 0x1000, 0xc82055e000, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc820bfc400, 0xc820b26000, 0x1000, 0x1000, 0xfc4ec4, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820bd1aa0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820bd1aa0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
net/http/internal.readChunkLine(0xc820bd1aa0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/internal/chunked.go:110 +0x53
net/http/internal.(*chunkedReader).beginChunk(0xc820d7ac00)
	/usr/local/go/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0xc820d7ac00, 0xc8200ec600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0xc820be81c0, 0xc8200ec600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:651 +0xa1
net/http.(*body).Read(0xc820be81c0, 0xc8200ec600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:643 +0x110
net/http.(*bodyEOFSignal).Read(0xc820be8200, 0xc8200ec600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1609 +0x26a
encoding/json.(*Decoder).refill(0xc8201bd380, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc8201bd380, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:128 +0x413
encoding/json.(*Decoder).Decode(0xc8201bd380, 0x275d780, 0xc820be8240, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:57 +0x159
k8s.io/kubernetes/pkg/watch/json.(*Decoder).Decode(0xc820d7ac30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/json/decoder.go:50 +0xa5
k8s.io/kubernetes/pkg/watch.(*StreamWatcher).receive(0xc820d7ac60)
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:93 +0x104
created by k8s.io/kubernetes/pkg/watch.NewStreamWatcher
	/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:60 +0xbf

goroutine 109 [select]:
net/http.(*persistConn).readLoop(0xc820838340)
	/usr/local/go/src/net/http/transport.go:1178 +0xd52
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 110 [select]:
net/http.(*persistConn).writeLoop(0xc820838340)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

**Comment by liggitt** [comment]
what version of openshift (and the router) is this running?

**Comment by mignev** [comment]
Hey @liggitt ,

openshift version
openshift v1.2.0-rc1
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

docker.io/openshift/origin-haproxy-router v1.2.0-rc1

**Comment by liggitt** [comment]
yeah, this was fixed in https://github.com/openshift/origin/pull/8893 on 5/17, and is in the release-1.2 tag
