### ISSUE TITLE
S2I image should allow specification of minimum compute resources

### ISSUE THREAD

**Issue by double16** [openshift/origin#9628]
There is no way for an S2I image to specify minimum compute resources, CPU or memory. For example, Java builds can take 1-2Gi of memory to build.

Either an image LABEL or something in an ImageStream document.
##### Version

oc v1.3.0-alpha.2

**Comment by bparees** [comment]
I feel like we've discussed this before, so there may be a trello card or github issue that covers this, but we can leave this open for now pending rediscovery of that.

**Comment by bparees** [comment]
@smarterclayton this seems like something we'd want for more than just builds, it seems like any image we're going to potentially run would want to be able to indicate minimum requirements, if we're going to do it at all.  What's your take?

1) is this something we'd want to spec out?
2) would it be better as an image label, or imagestream metadata?

**Comment by bparees** [comment]
@smarterclayton bump

**Comment by smarterclayton** [comment]
Probably image labels, and extract during new-app.  Challenge is that build time is special, so a separate set of labels for build time would be useful for those images.  I don't think they are s2i specific, and we should think about request vs limit (probably request is what the image should be setting).

**Comment by bparees** [comment]
i'd think the image could provide both requests and limits, or just one of them.  and they should all be treated as defaults (which of course in the case of new-app means use them, but for builds might not).

In other words, 8 new labels on the following axis:
[build/runtime][request/limit][cpu/memory]

new-app will use them to configure deploymentconfig/buildconfig request/limit values on the resources it creates (for whatever labels are provided).

and builds will use those values to set resource limits on the build pod if the buildconfig did not provide any resource constraints itself (but that would also preempt project defaults, so are we sure we'd want to do that?)

**Comment by smarterclayton** [comment]
I don't see much value in setting limits (usually) for builds, but for runtime it might be ok.

In the long run the real solution is going to be the vertical autosizer (which basically is going to say "you are running java/foo and the last time I saw that it took 500M of memory"), so it's hard to say whether this is with the complexity.  I don't want image defaults overriding project defaults or user settings, so this gets complicated.

**Comment by bparees** [comment]
sounds like a close to me.

**Comment by coreydaley** [comment]
closing due to age and inactivity, along with the comment above from @bparees
