### ISSUE TITLE
integration test doesn't build unless you have aws-sdk-go in $GOROOT

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#9630]
danw@w541:origin (master)> make test-integration 
    KUBE_COVER=" " KUBE_RACE=" " hack/test-integration.sh
    
    Test test/integration -tags='integration docker' ...
    
    Building test executable...
    # github.com/openshift/origin/test/integration
    package github.com/openshift/origin/test/integration (test)
    	imports github.com/openshift/origin/pkg/cmd/dockerregistry
    	imports github.com/docker/distribution/registry/storage/driver/middleware/cloudfront
    	imports github.com/aws/aws-sdk-go/service/cloudfront/sign: cannot find package "github.com/aws/aws-sdk-go/service/cloudfront/sign" in any of:
    	/usr/lib/golang/src/github.com/aws/aws-sdk-go/service/cloudfront/sign (from $GOROOT)
    	/home/danw/rh/go/src/github.com/openshift/origin/_output/local/go/src/github.com/aws/aws-sdk-go/service/cloudfront/sign (from $GOPATH)
    	/home/danw/rh/go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/cloudfront/sign
    FAIL	github.com/openshift/origin/test/integration [setup failed]

(The "missing" package is under Godeps/_workspace/src/github.com/docker/distribution/vendor/, but we aren't adding that directory to GOPATH.)

**Comment by liggitt** [comment]
are you sure? the CI machines $GOPATH only contain openshift, but integration tests still build

**Comment by danwinship** [comment]
The CI machines are on AWS so maybe the SDK is installed in $GOROOT (not $GOPATH) by default there?

(I don't know for sure why it *does* work in CI, I just know that it doesn't work on my laptop.)

**Comment by liggitt** [comment]
nope, not in GOROOT on the CI machines. aws-sdk-go is in our Godeps, just not that package. what version of go are you building with? I think @smarterclayton's change to use the vendor stuff for distribution relied on go 1.6

**Comment by danwinship** [comment]
ah, go 1.5.4, so maybe that's the problem.

I kept running into problems recently with the fact that verify-govet.sh doesn't work with go 1.5 either (so I kept pushing code that failed verification in CI)... I guess I need to upgrade. (Do we have a supported go 1.6 for F23? `yum --releasever=24 upgrade golang` doesn't seem to work; I get linker errors trying to build.)

**Comment by liggitt** [comment]
yeah, origin build only ever supported go1.4 and go1.6, and go1.4 support was dropped after origin 1.2 was cut:
http://lists.openshift.redhat.com/openshift-archives/dev/2016-March/msg00071.html

not sure about a yum-installable golang for fedora 23, I've always installed from source
