### ISSUE TITLE
osc skip tls verify

### ISSUE THREAD

**Issue by roberto-gomez** [openshift/origin#964]
Hello.

When I execute a command like `osc get pods` osc return a error like this

    F0210 16:07:04.021613     148 get.go:158] Get https://localhost:8443/api/v1beta1/pods?namespace=default: x509: certificate signed by unknown authority

If I use the option --insecure-skip-tls-verify=true when execute the command the error disapears, but I don't want to use the option in all commands. 

There is a method to avoid to use the option? Maybe editing some config file...

**Comment by smarterclayton** [comment]
Yes, you need to set up the KUBECONFIG file to point to the certs generated by the OpenShift server.  See http://lists.openshift.redhat.com/openshift-archives/dev/2015-January/msg00057.html for more on how to configure this.

@liggitt we may need to call this out in our README / contributing guide more.

**Comment by liggitt** [comment]
osc login prompts you to accept an insecure connection now
