### ISSUE TITLE
openshift_manageiq : Configure role/user permissions problem during installing

### ISSUE THREAD

**Issue by jeffchanjunwei** [openshift/origin#9641]
**when i install the openshift origin using openshift-ansible, there is always a "openshift_manageiq configure permissions" problem, showed below** 

TASK [openshift_manageiq : Configure role/user permissions] ********************
changed: [10.134.29.108] => (item=policy add-role-to-user -n management-infra admin -z management-admin)
changed: [10.134.29.108] => (item=policy add-role-to-user -n management-infra management-infra-admin -z management-admin)
changed: [10.134.29.108] => (item=policy add-cluster-role-to-user cluster-reader system:serviceaccount:management-infra:management-admin)
changed: [10.134.29.108] => (item=policy add-scc-to-user privileged system:serviceaccount:management-infra:management-admin)
changed: [10.134.29.108] => (item=policy add-cluster-role-to-user system:image-puller system:serviceaccount:management-infra:inspector-admin)
changed: [10.134.29.108] => (item=policy add-scc-to-user privileged system:serviceaccount:management-infra:inspector-admin)

TASK [openshift_manageiq : Configure 3_2 role/user permissions] ****************
failed: [10.134.29.108] (item=policy add-cluster-role-to-user system:image-auditor system:serviceaccount:management-infra:management-admin) => {"changed": false, "cmd": ["oadm", "policy", "addent-infra:management-admin", "--config=/tmp/manageiq_admin.kubeconfig"], "delta": "0:00:00.330130", "end": "2016-06-29 12:30:40.124611", "failed": true, "failed_when_result": true, "item": "poement-infra:management-admin", "rc": 1, "start": "2016-06-29 12:30:39.794481", "stderr": "Error from server: role \"system:image-auditor\" not found", "stdout": "", "stdout_lines": [], "warnin

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @./openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
10.134.29.108              : ok=198  changed=9    unreachable=0    failed=1   
10.134.29.144              : ok=24   changed=0    unreachable=0    failed=0   
10.134.29.148              : ok=24   changed=0    unreachable=0    failed=0   
localhost                  : ok=12   changed=6    unreachable=0    failed=0 

**Version**
openshift-ansible branch master tag 3.3.0-1
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
openshift v1.2.0
etcd 2.2.5

**Additional Information**
archtecture of my openshfit
Host Name	                   Infrastructure Component to Install
master.example.com          Master and node
node1.example.com           Node
node2.example.com           Node

**Comment by liggitt** [comment]
you are trying to use ansible 3.3 scripts with origin 1.2... that role was added to origin master after 1.2.0 branched: https://github.com/openshift/origin/pull/8455

@sdodson what origin version is appropriate to use with ansible 3.3.0?

**Comment by sdodson** [comment]
Hmm, that's in the v1.2.0 tag as far as I can tell.

```
sdodson@sdodson: ~/origin (master)$ git tag --contains ee377dc                                                                                                                                                                                                                  
v1.2.0
v1.2.0-rc1
v1.2.0-rc2
v1.3.0-alpha.0
v1.3.0-alpha.1
v1.3.0-alpha.2
```

**Comment by sdodson** [comment]
I don't believe we've added anything to the master branch of openshift-ansible or the 3.3 tags that shouldn't work with origin 1.2 but you can also use the latest from the enterprise-3.2 branch, we're more conservative with the changes that are going into that branch right now.

**Comment by liggitt** [comment]
@jeffchanjunwei is this a new install (with a new etcd instance), or is it using an etcd with data from a previous version?

**Comment by jeffchanjunwei** [comment]
thx @liggitt @sdodson . I have tried new install  with another branch, the problem fixd.
