### ISSUE TITLE
Importing 3 images at the same time, not all processed

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9650]
I think we're dropping items out of the import image queue somehow.  Ran 3 streams created at the same time, only 2 got imported.

**Comment by smarterclayton** [comment]
```
git clone https://github.com/docker/example-voting-app.git
oc import docker-compose -f example-voting-app/docker-compose.yaml
```

Half the time one of the images doesn't get imported.

**Comment by soltysh** [comment]
@smarterclayton I've tried several times, the images were imported in the worst case within 10s, but always all. Nothing got lost. Can you provide some logs from the times you're getting drops?

**Comment by mfojtik** [comment]
@smarterclayton bump

**Comment by smarterclayton** [comment]
This *could* be the requeueing on retry problem.

**Comment by soltysh** [comment]
I haven't this error, additionally the import controller was refactored to use shared informers. If you hit this problem once more feel free to reopen. The provided steps to reproduce don't work either, anymore.
