### ISSUE TITLE
oc cluster up fails with Finding server IP ... FAIL

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#9664]
##### Version
oc v1.3.0-alpha.2
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Steps To Reproduce
oc cluster up

##### Current Result
-- Finding server IP ... FAIL
   Error: cannot determine a server IP to use
   Caused By:
     Error: cannot determine an IP to use for your server.

##### Expected Result
cluster should be up 

##### Additional Information
No oadm involced

**Comment by debianmaster** [comment]
FYI.   i'am using Docker for MAC

**Comment by csrwng** [comment]
dup of #915

**Comment by debianmaster** [comment]
this issue may be specific to Docker for MAC

**Comment by csrwng** [comment]
Sorry, included wrong issue. This is a dup of https://github.com/openshift/origin/issues/9487

**Comment by csrwng** [comment]
@debianmaster - I will close this issue to keep track of a single issue at https://github.com/openshift/origin/issues/9487  Please reopen if you think this is something else.
