### ISSUE TITLE
service account token flake

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9672]
```
Running test/end-to-end/core.sh:181: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default'...
FAILURE after 0.020s: test/end-to-end/core.sh:181: executing 'cat '/tmp/openshift/test-end-to-end-docker//logs/cli-with-token2.log'' expecting success and text 'system:serviceaccount:test:default': the output content test failed
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2734/console

unclear if this is related to:
https://github.com/openshift/origin/issues/9480

which was closed as a dupe of:
https://github.com/openshift/origin/issues/9309

**Comment by liggitt** [comment]
yeah, looks like the same issue as https://github.com/openshift/origin/issues/9309... output from an attach command sometimes not including the last line
