### ISSUE TITLE
TestTriggers_imageChange_nonAutomatic flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9683]
```
--- FAIL: TestTriggers_imageChange_nonAutomatic (125.80s)
	deploy_trigger_test.go:251: Waiting for image stream mapping to be reflected in the image stream status...
	deploy_trigger_test.go:264: Still waiting for latest tag status update on imagestream "test-image-stream"
	deploy_trigger_test.go:286: Waiting for the initial deploymentconfig update in response to the imagestream update
	deploy_trigger_test.go:309: timed out waiting for the image update to happen
FAIL
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2809/consoleFull

**Comment by bparees** [comment]
recurred:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/2866/console

**Comment by kargakis** [comment]
The config seems to be reconciled correctly by the image change controller
```
I0705 11:49:27.328761   14738 controller.go:42] Detecting image changes for deployment config "integration/config"
```
but it fails to update. The controller doesn't retry failed updates. At this point, I prefer to proceed with https://github.com/openshift/origin/pull/9349 which collapses the image change controller under the endpoint rather than fixing the controller.

**Comment by kargakis** [comment]
Should be fixed in https://github.com/openshift/origin/pull/9774, reopen if it occurs again

**Comment by miminar** [comment]
Reopenning thanks to https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/4514/consoleFull
