### ISSUE TITLE
  An error occurred while building 1.2(openshift_node_dnsmasq)

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#9684]
Version: oepnshift-origin-1.2.0
Environment: The new system did not install anything(Centos cloud images)
build: 3master+3etcd+3node+1lb[1]+DNS / 1master+2node
command: ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
Hi,
There is a problem when I build openshift 1.2
{"changed": false, "failed": true, "msg": "Currently, NetworkManager must be installed and enabled prior to installation."}
![error-1](https://cloud.githubusercontent.com/assets/12937669/16540952/46aaf98e-40a9-11e6-822b-4ca5212418ab.jpg)
![error-2](https://cloud.githubusercontent.com/assets/12937669/16540977/f692bf80-40a9-11e6-8292-f455f69da7e7.jpg)
when i use `ansible-playbook ~/openshift-ansible/playbooks/adhoc/uninstall.yml` and build again,it is ok.but if i want to add a new node,also error,how can i do for this?
thanks.

**Comment by wenskys** [comment]
I think it is a bug for cloud system images or ansible(Physical machines and virtual machine haven't this bug)
At last ，i use `systemctl restart NetworkManager`command can solve this bug(At node).

**Comment by wenskys** [comment]
now,i use `systemctl restart NetworkManager` before i runing `ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml`,and it's ok.
uninstall command have restart NetworkManager,so when i build again,it is ok.

**Comment by sdodson** [comment]
Yes, NetworkManager is a requirement to use openshift-ansible installer and we didn't think it was safe to install and enable it without admin intervention so we halt the install. https://github.com/openshift/openshift-ansible/issues/1807 tracks implementing without NetworkManager but unless the community contributes that we're not focusing on it.
