### ISSUE TITLE
[RFE] Build pods should have openshift.io/build-config.name annotation set

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#9698]
@bparees I'm gonna need this for #9587 and it'll work similarly to how deployments do. I'd like the build pods to be associated with specific `BuildConfig` using `openshift.io/build-config.name`.

For example annotations you can find on any pod created by deployment are:
- `openshift.io/deployment-config.name` 
- `openshift.io/deployment.name` 
- `openshift.io/scc:restricted` 
- `kubernetes.io/created-by`

I'll do it by myself, I just need your OK on that.

**Comment by bparees** [comment]
Pods already have openshift.io/build.name which associated a pod to a build, from which you can get the buildconfig.  Is this absolutely necessary?

**Comment by bparees** [comment]
especially since not all builds have a buildconfig, so now you'll have some build pods for which the buildconfig annotation does not exist or is emptystring.

**Comment by soltysh** [comment]
Yeah, but with that I'll have a clear indication that this build wasn't created from any specific BuildConfig. Without it, I'd have to search for a specific Build to get just the information about the BuildConfig. Is that a big problem for you to have it there?

**Comment by bparees** [comment]
> Yeah, but with that I'll have a clear indication that this build wasn't created from any specific BuildConfig. 

or that it was created before we introduced this logic....

>  Is that a big problem for you to have it there?

not a big problem, just want to make sure we *really* want to add it.  it's really up to @openshift/api-review

**Comment by soltysh** [comment]
>not a big problem, just want to make sure we really want to add it. it's really up to @openshift/api-review

Leave them to me, I'll buy their approval with krowkas ;)

**Comment by smarterclayton** [comment]
Build pods should have the created by annotation that correlates to the controller that created it (the build).  I'm not averse to the extra annotations, but it would be better if this followed new and emerging patterns.

**Comment by soltysh** [comment]
I've discussed this with @deads2k on IRC, for now I'm closing this without any further actions.

**Comment by smarterclayton** [comment]
Within reason, neither the explosion nor the "out-datedness" is the real problem.  I agree we want to be judicious about its use, but on the other hand performing extensive inferencing is not a real solution (for anyone except someone with lots of spare time to build a graph library).  Our users and clients don't really fit into that space.
