### ISSUE TITLE
Extended.deploymentconfigs when run iteratively should immediately start a new deployment [Conformance]

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#9701]
```
Stacktrace

/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:181
Expected error:
    <*errors.errorString | 0xc820067f50>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2970/testReport/junit/(root)/Extended/deploymentconfigs_when_run_iteratively_should_immediately_start_a_new_deployment__Conformance_/

**Comment by bparees** [comment]
recurred: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2987/consoleFull

**Comment by kargakis** [comment]
Dupe of https://github.com/openshift/origin/issues/9681
