### ISSUE TITLE
Image pruning works against schema 1 only

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#9702]
Currently our pruning code works only with schema 1 images only. See [these lines](https://github.com/openshift/origin/blob/8f01725bdffd24233bd256484c1835cc7ea9e322/pkg/image/prune/imagepruner.go#L302-L306) which handle only v1 layers.

@miminar @legionus fyi

**Comment by legionus** [comment]
If the problem is only in this piece of code, it's easy to fix.

**Comment by soltysh** [comment]
Not sure about the actual removal part.

**Comment by legionus** [comment]
I didn't mean to remove this piece of code, I mean adding support v2 scheme.

**Comment by soltysh** [comment]
I meant I'm not sure about the actual remove that is being called on a layer. Iow. where you say the registry that it should remove specific layer. Not the removal of this code ;)

**Comment by legionus** [comment]
You was faster :)
