### ISSUE TITLE
Create an extended test veryfing image pruning

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#9712]
Currently the only image pruning tests are unit tests. We should consider writing extended tests. @miminar @legionus any objections?

**Comment by soltysh** [comment]
This came out when I was working on https://github.com/openshift/origin/issues/9702 and https://github.com/openshift/origin/pull/9481

**Comment by mfojtik** [comment]
@miminar @soltysh i thought we have test for pruning already?

**Comment by soltysh** [comment]
Yup, it's in https://github.com/openshift/origin/blob/master/test/extended/images/prune.go. I'll close @miminar feel free to reopen if you feel more is needed.
