### ISSUE TITLE
Man pages display flags from base Golang flags package that are not included in our CLI tools

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#9717]
Man pages are generated with flags that come from the base Golang flags package, but are not present in actual openshift commands.

Related issue: https://github.com/openshift/origin/issues/9348#issuecomment-230834896
Related PR: https://github.com/openshift/origin/pull/9448#issuecomment-230135780

##### Version
oc v1.3.0-alpha.0-1394-g03981d1-dirty
kubernetes v1.3.0-alpha.3-599-g2746284

##### Steps To Reproduce
`./hack/update-generated-docs.sh`

##### Current Result
```
-\fB\-\-docker\fP="unix:///var/run/docker.sock"
-    docker endpoint
-
-.PP
-\fB\-\-docker\-env\-metadata\-whitelist\fP=""
-    a comma\-separated list of environment variable keys that needs to be collected for docker containers
-
-.PP
-\fB\-\-docker\-only\fP=false
-    Only report docker containers in addition to root stats
-
-.PP
-\fB\-\-docker\-root\fP="/var/lib/docker"
-    Absolute path to the Docker state root directory (default: /var/lib/docker)
-
-.PP
-\fB\-\-docker\-run\fP="/var/run/docker"
-    Absolute path to the Docker run directory (default: /var/run/docker)
-
-.PP
-\fB\-\-enable\-load\-reader\fP=false
-    Whether to enable cpu load reader
-
-.PP
-\fB\-\-event\-storage\-age\-limit\fP="default=24h"
-    Max length of time for which to store events (per type). Value is a comma separated list of key values, where the keys are event types (e.g.: creation, oom) or "default" and the value is a duration. Default is applied to all non\-specified event types
-
-.PP
-\fB\-\-event\-storage\-event\-limit\fP="default=100000"
-    Max number of events to store (per type). Value is a comma separated list of key values, where the keys are event types (e.g.: creation, oom) or "default" and the value is an integer. Default is applied to all non\-specified event types
-
-.PP
-\fB\-\-global\-housekeeping\-interval\fP=0
-    Interval between global housekeepings
-
-.PP

-\fB\-\-storage\-driver\-buffer\-duration\fP=0
-    Writes in the storage driver will be buffered for this duration, and committed to the non memory backends as a single transaction
-
-.PP
-\fB\-\-storage\-driver\-db\fP="cadvisor"
-    database name
-
-.PP
-\fB\-\-storage\-driver\-host\fP="localhost:8086"
-    database host:port
-
-.PP
-\fB\-\-storage\-driver\-password\fP="root"
-    database password
-
-.PP
-\fB\-\-storage\-driver\-secure\fP=false
-    use secure connection with database
-
-.PP
-\fB\-\-storage\-driver\-table\fP="stats"
-    table name
-
-.PP
-\fB\-\-storage\-driver\-user\fP="root"
-    database username
-
-.PP
```

##### Expected Result
Flags that are not part of our CLI tools not included

##### Additional Information
If you compile on a Mac or Windows these flags are excluded

**Comment by juanvallejo** [comment]
@smarterclayton @fabianofranz Created issue based on https://github.com/openshift/origin/pull/9448#issuecomment-230135780

**Comment by fabianofranz** [comment]
@juanvallejo as far as I remember we had (and fixed) the same issue in our previous version of the generated completions. That might give a clue about how to exclude these flags.

**Comment by juanvallejo** [comment]
Relevant PR: https://github.com/openshift/origin/pull/7482/files

**Comment by fabianofranz** [comment]
@smarterclayton @juanvallejo interestingly I *don't* see the issue building completions in `go1.6.2 linux/amd64` (Fedora 24), so it's not only Mac/Windows.

**Comment by fabianofranz** [comment]
@smarterclayton Wondering if the *completions* issue is something else related to the Kube rebase - I'm really not seeing invalid global flags in completion, not even in the `openshift` command. Taking a look at the rebase to make sure it wasn't changed (unexpected call to `BindExternalFlags()` or something similar).

**Comment by smarterclayton** [comment]
On Master with Mac I definitely see those completions removed from what is
checked i
