### ISSUE TITLE
OpenShift V3 beta step by step document tation

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#973]
Hi all, is there any updated step by step documententation? I would like to try OpenShift V3 beta docker image (from docker hub) and samples.

Many thanks for you help.

**Comment by soltysh** [comment]
The docs, although still under heavy development are [here](http://docs.openshift.org/latest/welcome/index.html), the repo of it is available [here](https://github.com/openshift/openshift-docs/). Besides that there's always up to date [sample-app](https://github.com/openshift/origin/tree/master/examples/sample-app). If you still have questions/problems feel free to reach out us at *#openshift-dev@freenode* or *#openshift@freenode*.

**Comment by soltysh** [comment]
There are also some training materials [here](https://github.com/openshift/training/blob/master/beta-1-setup.md)

**Comment by smarterclayton** [comment]
Closing with the links
