### ISSUE TITLE
deploy fails due to no tmp token directory

### ISSUE THREAD

**Issue by vbatts** [openshift/origin#9733]
##### Version

openshift v1.3.0-alpha.2-1057-g1cb1dac
kubernetes v1.3.0-alpha.3-599-g2746284
etcd 2.3.0+git
##### Steps To Reproduce
1. `make` build of 1cb1dacd3ea6549da83a66455f97dd79bc46add2
2. sudo ./_output/local/bin/linux/amd64/openshift start 
3. oc login https://xx.xx.xx.33:8443
4. oc new-project demo
5. oc new-app openshift/deployment-example
##### Current Result

The deploy log shows failure of:
`error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`
##### Expected Result

Deployed example
##### Additional

I `mkdir -p /var/run/secrets/kubernetes.io/serviceaccount/` and then `mkdir -p /var/run/secrets/kubernetes.io/serviceaccount/token` on the host, but this did not suffice. So I presume it's a /var/run tmpfs in some child mount namespace.

**Comment by liggitt** [comment]
what does the pod spec for the failing pod look like? does it include a volume mount for the secret? if so, it's like an issue with the volume mount, either docker mount propagation or selinux permissions on the volumes dir. what docker version do you have? selinux enforcing or not? @pmorie / @ncdc, do you have any troubleshooting tips for debugging tmpfs mount issues?

**Comment by ncdc** [comment]
I'd start with what you asked and go from there

**Comment by vbatts** [comment]
This host does not have selinux.
Docker version is: 
```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Tue Mar 29 15:46:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Tue Mar 29 15:46:59 2016
 OS/Arch:      linux/amd64
```

**Comment by ncdc** [comment]
Will need the log from `openshift start`, preferably at `--loglevel 5`

**Comment by vbatts** [comment]
http://pastebin.com/85xN2GQy is a failing pod yaml, with the host-ip scrubbed

**Comment by vbatts** [comment]
@ncdc here is the log (1month expiration) http://pastebin.com/SdbrAz8t

**Comment by ncdc** [comment]
@vbatts can you `ls -lR /home/vbatts/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift.local.volumes`?

**Comment by vbatts** [comment]
@ncdc 
```bash
vbatts@bananaboat ~ (master) $ ls -lR /home/vbatts/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift.local.volumes
/home/vbatts/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift.local.volumes:
total 8
drwxr-x--- 2 root root 4096 Jul  7 11:17 plugins/
drwxr-x--- 3 root root 4096 Jul  7 11:46 pods/
/bin/ls: cannot open directory '/home/vbatts/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift.local.volumes/plugins': Permission denied
/bin/ls: cannot open directory '/home/vbatts/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift.local.volumes/pods': Permission denied
vbatts@bananaboat ~ (master) $ stat /home/vbatts/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift.local.volumes/plugins /home/vbatts/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift.local.volumes/pods
  File: '/home/vbatts/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift.local.volumes/plugins'
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d    Inode: 9177851     Links: 2
Access: (0750/drwxr-x---)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-07-07 11:17:26.115925812 -0400
Modify: 2016-07-07 11:17:26.115925812 -0400
Change: 2016-07-07 11:17:26.115925812 -0400
 Birth: -
  File: '/home/vbatts/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift.local.volumes/pods'
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d    Inode: 9177850     Links: 3
Access: (0750/drwxr-x---)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-07-07 11:46:04.483339517 -0400
Modify: 2016-07-07 11:46:04.351338399 -0400
Change: 2016-07-07 11:46:04.351338399 -0400
 Birth: -
```

**Comment by vbatts** [comment]
@ncdc rather, `sudo ls -lR ...` http://pastebin.com/VNB16knC

**Comment by ncdc** [comment]
@vbatts can you test with the latest origin master and see if this is still an issue?

**Comment by ncdc** [comment]
Closing due to age + inactivity. Please reopen if necessary.
