### ISSUE TITLE
When oc edit re-opens with a failure, get unfriendly protobuf message in the comments

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#9739]
When using oc edit and causing a failure I got back this message in the comments:

```
The edited file had a syntax error: unable to decode "edited-file": provided data does not appear to be a protobuf message, expected prefix [107 56 115 0]
```

This issue may affect upstream, need to test against kube as well.

I was able to recreate it when editing a quota when I put GiB instead of Gi

**Comment by jwforres** [comment]
cc @smarterclayton

**Comment by deads2k** [comment]
Well did you try prefix `[07 10 10 04]`?

**Comment by smarterclayton** [comment]
lol

Probably someone using codec blindly.

**Comment by mfojtik** [comment]
just got this when editing project ;-)

**Comment by pweil-** [comment]
it looks like the interface for `RecognizingDecoder` changed so the protobuf decoder was being added as a skipped decoder and replacing the good error message from the json decoder with what is described above.  

After adding the `unknown` parameter the error message of 
```
The edited file had a syntax error: unable to decode "edited-file": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```
shows as I'd expect.  Here is the change.  If this looks ok then I will submit upstream: https://github.com/openshift/origin/pull/10191

**Comment by smarterclayton** [comment]
Yikes.  Ok, we need to assert that all the protobuf methods implement recognizing decoder, for sure.
