### ISSUE TITLE
initial deployment doesn't wait for readiness?

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9752]
Based on the failures seen in the nodejs test here:

```
• Failure [142.890 seconds]
[images][Slow] openshift sample application repositories
/data/src/github.com/openshift/origin/test/extended/images/sample_repos.go:205
  [images][nodejs] test nodejs images with nodejs-ex db repo
  /data/src/github.com/openshift/origin/test/extended/images/sample_repos.go:124
    Building nodejs-mongodb app from new-app
    /data/src/github.com/openshift/origin/test/extended/images/sample_repos.go:81
      should build a nodejs-mongodb image and run it in a pod [It]
      /data/src/github.com/openshift/origin/test/extended/images/sample_repos.go:80
```

https://ci.openshift.redhat.com/jenkins/job/origin_extended_image_tests/299/consoleFull

it looks like maybe the DB deployment is being reported as "complete" even though the DB service has no available endpoints.  (The app test then fails because it hits the app before the DB is available, and the app response does not include the expected DB-related string, which implies the app was unable to connect to the DB).

Note that i've since changed the test to explicitly wait for a DB endpoint after the DB deploy completes, before hitting the app, so we (hopefully) won't see this issue anymore, but it still seems like a flaw in deployments if my theory is correct.

**Comment by kargakis** [comment]
@smarterclayton we don't look into readiness at all on initial deployments (because we are just scaling up). This is most probably the issue but I need to look deeper into the deployer. We expose AvailableReplicas in the deployment config, we could poll that field until dc.spec.replicas-maxUnavailable=AvailableReplicas. Thoughts?

**Comment by smarterclayton** [comment]
Making readiness apply to initial deployments as well as subsequent deployments is the right thing to do.  Even if we scale up, we should still fail the deployment if readiness isn't reached within window.

**Comment by kargakis** [comment]
@smarterclayton AvailableReplicas is not available on older servers. Is there another way to determine that the deployer is talking to an older server?

**Comment by smarterclayton** [comment]
Other than by observing other missing fields, no.

**Comment by kargakis** [comment]
It turns out we are waiting for initial deployment to become ready - it's just that our examples don't have any requirement for availability. I will add an extended test proving that this is not a bug.

**Comment by kargakis** [comment]
> it's just that our examples don't have any requirement for availability

Nevermind this, I am not sure why that test failed (maybe related to another deployment flake?). We are waiting for initial deployments to become ready though: https://github.com/openshift/origin/pull/10736
