### ISSUE TITLE
RFE: be able to specify multiple secrets for an image import

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#9758]
This was discovered during adding tests from https://github.com/openshift/origin/issues/9730#issuecomment-231109469. We're trying to access internal docker registry, by default we generate secrets to access that registry for every project we create (you can't even remove them, they will be recreated). I'm creating additional secret using my user data, since it has access to both projects. Now I have two secrets, which will be considered appropriate for that registry. With current [credentials](https://github.com/openshift/origin/blob/7df6638740d3f992860f2833a3c4e529be97c123/pkg/image/importer/credentials.go#L152-L182) implementation one will be picked randomly.

The proposed solution is:
1. add retry mechanism for that cases
2. allow users specify which secret to use at IS level

First is required, the latter would be a nice to have.

@smarterclayton fyi

**Comment by smarterclayton** [comment]
On the node, we walk all applicable secrets until one works (Docker does
this as well).  Importer and registry pull through ultimately have to do
the same.  We may need a cache in pull through to identify likely candidate
secret names (so we can prefer them).

**Comment by mfojtik** [comment]
@bparees another trello card candidate, @soltysh can brief you in details.

**Comment by bparees** [comment]
trello'd https://trello.com/c/sSj0DAlK
