### ISSUE TITLE
TestConcurrentBuildPodControllers flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9765]
```
--- FAIL: TestConcurrentBuildPodControllers (7.46s)
    buildcontroller_test.go:325: unexpected error: Operation cannot be fulfilled on pods "mock-build7o9lj-build": the object has been modified; please apply your changes to the latest version and try again
FAIL
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3084/consoleFull
@smarterclayton said he's looking at all the new post-rebase races in integration

@bparees fyi

**Comment by bparees** [comment]
adding @csrwng since he was heavily involved in us convincing ourselves we were concurrent-safe :)

**Comment by smarterclayton** [comment]
Merged fix in #9770, but that doesn't answer who was mutating the pod under us.

**Comment by smarterclayton** [comment]
I think that fixes the flake, but we need to dig into the why.

**Comment by mfojtik** [comment]
closing due to age.
