### ISSUE TITLE
Route to MySQL is not working

### ISSUE THREAD

**Issue by bkmagnetron** [openshift/origin#9769]
I have followed [this](https://github.com/openshift/origin/tree/master/examples/wordpress) and deployed wordpress.
Then I created a route for MySQL service from web console.
Then I configured my client(HeidiSQL) with the route url and port 80.
Then I get this error
```
Lost connetion to MySQL server at 'reading initial communication packet', system error: 0
```
![route-mysql-error](https://cloud.githubusercontent.com/assets/4893873/16733607/d09d75b6-479f-11e6-888f-8f42453f3c8e.png)

**Comment by danmcp** [comment]
Routing is for HTTPS/HTTP/SNI for now.  We are working for a feature to be about to route TCP externally (https://trello.com/c/9TXvMeS2/).  But for now, you should be able to run HeidiSQL on the cluster and be able to access MySQL through its pod_ip:port.
