### ISSUE TITLE
Incomplete document docs/openshift_model.md

### ISSUE THREAD

**Issue by oatmealraisin** [openshift/origin#9772]
[This document](https://github.com/openshift/origin/blob/master/docs/openshift_model.md) seems to be a bit incomplete.  What is the purpose of this document?  Would it be worth working on, or should we do away with it?

**Comment by sosiouxme** [comment]
Looks like cruft to me. I don't even remember why I started it. Probably trying to get others to chime in on how OpenShift added to Kubernetes from an API standpoint, but it doesn't seem to have attracted much interest, so I'll just get rid of it.
