### ISSUE TITLE
Unable to deploy database in e2e test: secret never got mounted

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9775]
Post Rebase (kube 1.3.0) on our RHEL 7.2 CI machines some deployments are failing because they are unable to mount a secret occasionally.

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3091/
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3091/s3/download/test-end-to-end-docker/logs/container-origin.log

Opened kubernetes/kubernetes#28750

**Comment by deads2k** [comment]
test/end-to-end/core.sh:21: executing 'oc get -n test pods -l name=database' expecting any result and text 'Running'

The linked issue was closed, so I'm adding this so people can find it.  Hit it again.

**Comment by smarterclayton** [comment]
This is because identical volumes are mounted in serial per node, and since the same secret is used multiple times on the same node for different pods all of those pod starts are serialized.  There appears to be a detach issues as well potentially (which may exacerbate the problem here).

**Comment by smarterclayton** [comment]
Issue is being worked and slated for 1.3 backport.

**Comment by bparees** [comment]
think i hit what @deads2k referenced again here:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3342/consoleFull

**Comment by smarterclayton** [comment]
Now resolved
