### ISSUE TITLE
openshift-infra can not access kubernetes.default.svc when i build metrics

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#9794]
Hi,
I want to build metrics for openshift,but something is error.
```
#create ServiceAccount
oc create -f - <<API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-deployer
secrets:
- name: metrics-deployer
API

oadm policy add-role-to-user edit system:serviceaccount:openshift-infra:metrics-deployer
oadm policy add-cluster-role-to-user cluster-reader system:serviceaccount:openshift-infra:heapster

#create secrets
oc secrets new metrics-deployer nothing=/dev/null

#create metrics pod
oc process metrics-deployer-template -n openshift \
 -v IMAGE_PREFIX=172.30.159.16:5000/openshift-infra/,\
HAWKULAR_METRICS_HOSTNAME=hawkular-metrics.goshift.com,\
USE_PERSISTENT_STORAGE=false | oc create -f -
```
it is error.
![openshift-3](https://cloud.githubusercontent.com/assets/12937669/16754620/c956fc1e-4826-11e6-8320-325506ff0746.png)
the default project can access the kubernetes.default.svc.

How to access across the namespace，such as default and openshift-infra/logging?
thanks.

**Comment by liggitt** [comment]
Seems like cluster DNS is not working in your setup. What does /etc/resolv.conf look like inside one of your pods?

**Comment by wenskys** [comment]
@liggitt 
i use this to start openshift
```
nohup openshift start --public-master='https://oc.goshift.com:8443' \
--master='https://oc.goshift.com:8443' --hostname='oc.goshift.com' \
--portal-net='10.30.0.0/16' \
--volume-dir=/var/lib/openshift/openshift.local.volumes \
--etcd-dir=/var/lib/openshift/openshift.local.etcd >> /var/log/openshift/openshift.log 2>&1  &
```
but the pod /etc/resolv.conf haven't the dns 10.30.0.1.

**Comment by wenskys** [comment]
use `--dns='tcp://0.0.0.0:8053'`,the /etc/resolv.conf have 10.30.0.1,but the 53 port can't up in openshift.

**Comment by liggitt** [comment]
if you start with dns on port 8053, the kubernetes service will map port 53 inside a pod to port 8053 on the master. can you show the output of the following:
```
oc get service kubernetes -n default -o yaml
```

**Comment by wenskys** [comment]
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-07-12T05:07:39Z
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "7"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: 8e6e6cba-47ee-11e6-91ad-080027729a62
spec:
  clusterIP: 10.30.0.1
  portalIP: 10.30.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 8053
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 8053
  sessionAffinity: ClientIP
  type: ClusterIP
status:
  loadBalancer: {}
```
I use openshift start to start my openshift origin(use Binary to start openshift).
if i haven't use  `--dns='tcp://0.0.0.0:8053'`,the 53 and 8053 port is ok,but /etc/resolv.conf haven't inside all of my pods.
![openshift-error-1](https://cloud.githubusercontent.com/assets/12937669/16771318/a07ea524-4882-11e6-9ac2-246f2e406e43.png)
not use `--dns='tcp://0.0.0.0:8053'`  
![openshift-error-2](https://cloud.githubusercontent.com/assets/12937669/16771430/0eb1a23a-4883-11e6-92e2-d1268e5a62ac.png)


I'm not sure whether my startup mode error or parameter errors

**Comment by wenskys** [comment]
The new release of openshift need  dnsmsmq,but the all in one for openshift have start dns again，so i use --dns="tcp://0.0.0.0:8053" to avoid running openshift dns,but the pod have use /etc/resolv.conf for 10.30.0.1,and when i ping kubernetes.default.svc,response of the IP is the host machine ,so it look like haven't good method
