### ISSUE TITLE
Policy check on a nonexistent namespace returns the wrong error to the client

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9831]
Policy on a nonexistent namespace returns the wrong error to the client:

```
FAILURE after 0.106s: test/cmd/authentication.sh:22: executing 'oc policy can-i --list -n cmd-authentication --as=scoped-user' expecting success and text 'get.*pods': the command returned the wrong error code; the output content test failed
There was no output from the command.
Standard error from the command:
Error from server: Internal error occurred: [namespace cmd-authentication does not exist, object does not implement the Object interfaces]
```

It looks like this is an aggregate error, but not sure if it's client or server (because SelfSubjectReview).  Suspect something in rest handler is trying to write error information but instead lumping it into a NewAggregate when it can't get info about a SelfSAR.

**Comment by php-coder** [comment]
Test is passing now.

@smarterclayton Is it still an issue or we can close it?

**Comment by php-coder** [comment]
@smarterclayton ping. Could you close this issue, please?
