### ISSUE TITLE
TestRouterPathSpecificity

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9845]
```
--- FAIL: TestRouterPathSpecificity (3.19s)
    router_test.go:478: unexpected response with protocol http (port 80): "Get http://0.0.0.0/test: dial tcp 0.0.0.0:80: getsockopt: connection reset by peer"
FAIL
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3343/consoleFull

**Comment by knobunc** [comment]
@weliang1 Can you please take a look at this and try to reproduce it.  I have no idea why the test would be trying the URL http://0.0.0.0:80/.  Where are we getting the address for that test from?  Thanks.

**Comment by weliang1** [comment]
@knobunc TestRouterPathSpecificity test case failed on:
--- FAIL: TestRouterPathSpecificity (3.19s)
	router_test.go:478: unexpected response with protocol http (port 80): "Get http://0.0.0.0/test: dial tcp 0.0.0.0:80: getsockopt: connection reset by peer"

Could you tell me how to just run TestRouterPathSpecificity test case from router_test.go and skip any other test cases?

**Comment by kargakis** [comment]
@weliang1 `./hack/test-integration TestRouterPathSpecificity`

**Comment by weliang1** [comment]
Try run both ./hack/test-integration.sh TestRouterPathSpecificity and
./hack/test-integration.sh
three times, both test passed, can not easily reproduce it

++ /home/fedora/go/src/
github.com/openshift/origin/_output/testbin/test/integration/integration.test
-test.timeout=4m '-test.run=^TestRouterPathSpecificity$'
+ out='I0714 19:41:26.067134   16547 plugins.go:46] Registered cloud
provider "aws"
I0714 19:41:26.067291   16547 plugins.go:46] Registered cloud provider "gce"
I0714 19:41:26.067426   16547 plugins.go:46] Registered cloud provider
"mesos"
I0714 19:41:26.067479   16547 plugins.go:46] Registered cloud provider
"openstack"
I0714 19:41:26.067490   16547 plugins.go:46] Registered cloud provider
"ovirt"
I0714 19:41:26.067501   16547 plugins.go:46] Registered cloud provider
"rackspace"
I0714 19:41:26.069967   16547 plugins.go:46] Registered cloud provider
"vsphere"
I0714 19:41:26.071349   16547 plugins.go:41] Registered credential provider
"google-jwt-key"
I0714 19:41:26.071366   16547 plugins.go:41] Registered credential provider
"google-dockercfg"
I0714 19:41:26.071372   16547 plugins.go:41] Registered credential provider
"google-dockercfg-url"
I0714 19:41:26.071376   16547 plugins.go:41] Registered credential provider
"google-container-registry"
I0714 19:41:26.072272   16547 plugins.go:74] Registered admission plugin
"BuildDefaults"
I0714 19:41:26.072296   16547 plugins.go:74] Registered admission plugin
"JenkinsBootstrapper"
I0714 19:41:26.072308   16547 plugins.go:74] Registered admission plugin
"BuildOverrides"
I0714 19:41:26.072321   16547 plugins.go:74] Registered admission plugin
"BuildByStrategy"
I0714 19:41:26.072335   16547 plugins.go:74] Registered admission plugin
"LimitRanger"
I0714 19:41:26.072343   16547 plugins.go:74] Registered admission plugin
"ImageLimitRange"
I0714 19:41:26.072361   16547 plugins.go:74] Registered admission plugin
"OriginNamespaceLifecycle"
I0714 19:41:26.072370   16547 plugins.go:74] Registered admission plugin
"OriginPodNodeEnvironment"
I0714 19:41:26.072378   16547 plugins.go:74] Registered admission plugin
"ProjectRequestLimit"
I0714 19:41:26.072391   16547 plugins.go:74] Registered admission plugin
"ClusterResourceOverride"
I0714 19:41:26.072403   16547 plugins.go:74] Registered admission plugin
"ResourceQuota"
I0714 19:41:26.072411   16547 plugins.go:74] Registered admission plugin
"ClusterResourceQuota"
I0714 19:41:26.072419   16547 plugins.go:74] Registered admission plugin
"OriginResourceQuota"
I0714 19:41:26.072427   16547 plugins.go:74] Registered admission plugin
"RunOnceDuration"
I0714 19:41:26.072457   16547 plugins.go:74] Registered admission plugin
"PodNodeConstraints"
I0714 19:41:26.072472   16547 plugins.go:74] Registered admission plugin
"SecurityContextConstraint"
I0714 19:41:26.072480   16547 plugins.go:74] Registered admission plugin
"SCCExecRestrictions"
I0714 19:41:26.072488   16547 plugins.go:74] Registered admission plugin
"AlwaysAdmit"
I0714 19:41:26.072498   16547 plugins.go:74] Registered admission plugin
"AlwaysPullImages"
I0714 19:41:26.072506   16547 plugins.go:74] Registered admission plugin
"DenyEscalatingExec"
I0714 19:41:26.072513   16547 plugins.go:74] Registered admission plugin
"DenyExecOnPrivileged"
I0714 19:41:26.072521   16547 plugins.go:74] Registered admission plugin
"NamespaceExists"
I0714 19:41:26.072531   16547 plugins.go:74] Registered admission plugin
"NamespaceLifecycle"
I0714 19:41:26.072539   16547 plugins.go:74] Registered admission plugin
"ServiceAccount"
I0714 19:41:26.072549   16547 plugins.go:74] Registered admission plugin
"LimitPodHardAntiAffinityTopology"
I0714 19:41:26.072557   16547 plugins.go:74] Registered admission plugin
"AlwaysDeny"
I0714 19:41:26.072836   16547 plugins.go:74] Registered admission plugin
"InitialResources"
I0714 19:41:26.072855   16547 plugins.go:74] Registered admission plugin
"NamespaceAutoProvision"
I0714 19:41:26.072866   16547 plugins.go:74] Registered admission plugin
"PersistentVolumeLabel"
I0714 19:41:26.072877   16547 plugins.go:74] Registered admission plugin
"PodSecurityPolicy"
I0714 19:41:26.072884   16547 plugins.go:74] Registered admission plugin
"SecurityContextDeny"
I0714 19:41:26.079766   16547 plugins.go:74] Registered admission plugin
"RestrictedEndpointsAdmission"
I0714 19:41:26.079784   16547 plugins.go:74] Registered admission plugin
"ExternalIPRanger"
I0714 19:41:26.082580   16547 router_http_server.go:265] Started, serving
at 172.18.13.242:8080
I0714 19:41:26.082659   16547 router_http_server.go:265] Started, serving
at 172.18.13.242:8888
I0714 19:41:26.082691   16547 router_http_server.go:265] Started, serving
at 172.18.13.242:8889
I0714 19:41:26.083211   16547 router_http_server.go:297] Started, serving
TLS at 172.18.13.242:8443
I0714 19:41:35.282230   16547 router_http_server.go:174] Stopping listener
at 172.18.13.242:8080
I0714 19:41:35.282252   16547 router_http_server.go:174] Stopping listener
at 172.18.13.242:8888
I0714 19:41:35.282256   16547 router_http_server.go:174] Stopping listener
at 172.18.13.242:8889
I0714 19:41:35.282260   16547 router_http_server.go:174] Stopping listener
at 172.18.13.242:8443
PASS'


On Thu, Jul 14, 2016 at 11:25 AM, Michail Kargakis <notifications@github.com

**Comment by kargakis** [comment]
Occured once again in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3680/consoleFull

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration_future/302/consoleFull#-212598301056bf4006e4b05b79524e5923

**Comment by smarterclayton** [comment]
Worried that more router issues are cropping up.

**Comment by knobunc** [comment]
I don't see this happening on http://snowstorm-dev.app.mfojtik.io/
