### ISSUE TITLE
Use image.DockerImageLayers instead of image.DockerImageManifest.(Layers|FSLayers)

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#9846]
I discovered that during working on #9587. We have `image.DockerImageLayers` which is reversed order table of layers (pupulated [v1 here](https://github.com/openshift/origin/blob/master/pkg/image/api/helper.go#L491-L494) and [v2 here](https://github.com/openshift/origin/blob/master/pkg/image/api/helper.go#L532-L535)). With that in mind, shouldn't we stop manually encoding `image.DockerImageManifest.(Layers|FSLayers)` and start using the former? Specifically I mean the [pruning code](https://github.com/openshift/origin/blob/d4c3349faeba77216d1d5a234997a138cc09209b/pkg/image/prune/prune.go#L316-L329)? Additionally this applies to the PR I've mentioned in the beginning that I'm currently working on.

@miminar @smarterclayton @legionus opinions?
@ncdc any backwards compatibility issues you can think of?

**Comment by legionus** [comment]
`imageapi.DockerImageManifest.(Layers|FSLayers)` is used for `image.DockerImageLayers` construction. No one should use them except `docker-registry` and `importer` because they are doing non-trivial work to fill in `image.DockerImageLayers` with the correct values.
