### ISSUE TITLE
Can't substitute new-app parameter with value containing newlines

### ISSUE THREAD

**Issue by ironcladlou** [openshift/origin#9863]
Passing a parameter value to `oc new-app` containing newlines results in only the first line of the file being preserved in the resulting processed template data.

##### Version

oc v1.3.0-alpha.2+7fad2e0

##### Steps To Reproduce

Use the test case in [this gist] (https://gist.github.com/ironcladlou/37f9a4ef92cb0f166143de951db96260) which includes a sample template, data, command line execution and output.

##### Current Result

See the gist- only the first line of the parameter value is preserved.

##### Expected Result

The entire file contents passed to the parameter should be preserved.

##### Additional Information

GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)

**Comment by Miciah** [comment]
I believe the culprit is [our use of](https://github.com/openshift/origin/blob/60c7d7bc93e463e3f68d3e9c9043b36bd938fd70/pkg/cmd/cli/cmd/newapp.go#L165) Cobra's `StringSliceVarP`:

```go
package main

import (
	"fmt"
	"github.com/spf13/cobra"
)

func main() {
	var templateParameters []string

	cmd := &cobra.Command{
		Run: func(c *cobra.Command, args []string) {
			fmt.Printf("%#v\n", templateParameters)
		},
	}

	cmd.Flags().StringSliceVarP(&templateParameters, "param", "p", nil, "Specify a list of key value pairs (e.g., -p FOO=BAR,BAR=FOO) to set/override parameter values in the template.")
	cmd.Execute()
}
```

```console
% go run example.go -p='x=yz'
[]string{"x=yz"}
% go run example.go -p=$'x=y\nz'
[]string{"x=y"}
%
```

**Comment by Miciah** [comment]
@ironcladlou, `StringSliceVarP` uses the encoding/csv library, so you should be able to use newlines if you quote the string as follows:

```console
$ oc new-app -f template.yaml -p="\"DATA=$(<test.crt)\"" -o json
```

Using that gets us a little further, but with that command, I get the following: "error: environment variables must be of the form key=value".
