### ISSUE TITLE
Multi-line environment variables with 'oc set env'

### ISSUE THREAD

**Issue by AlbertoPeon** [openshift/origin#9877]
Is it possible to define multiline environment variables using 'oc set env'? 

We want to store a config file into an environment variable using 'oc set env' but it doesn't seem possible as only the first line is saved.

e.g.
```bash
$ cat apache.conf
# Apache example

<VirtualHost *:*>
  <Location "/">
    More stuff here
  </Location>
</VirtualHost>
$ oc set env dc/apache -e MAIN_CONF="`cat apache.conf`"
deploymentconfig "apache" updated
$ oc set env dc/apache --list
# deploymentconfigs apache, container http
MAIN_CONF=# Apache example

```
If I try without the -e variable the parsing fails
```bash
$ oc set env dc/apache MAIN_CONF="`cat apache.conf`"
arguments in resource/name form may not have more than one slash
```

Please note that it's possible to set multi-line env variables directly in the DeploymentConfig using the '|-' operator and copying the contents of the file there, but it's a bit annoying (need to copy and paste, escaping quotes... etc.)

Is there a better way to do this?

**Comment by juanvallejo** [comment]
I am currently able to successfully set a multi-line value with `oc set env`. Maybe this has been fixed since this bug was posted?

```
$ cat apache.conf
# Apache example

<VirtualHost *:*>
  <Location "/" >
    More stuff here
  </Location>
</VirtualHost>
```
```
$ oc set env dc/node MAIN_CONF="`cat apache.conf`"
deploymentconfig "node" updated
```
```
$ oc describe dc/node
...
  Containers:
   node:
    Image:              node@sha256:db245bde5445eb122d8dc090ba98539a9ef7f56c0ea981ade643695af0d8eaf0
    Port:
    Volume Mounts:      <none>
    Environment Variables:
      MAIN_CONF:        # Apache example

<VirtualHost *:*>
  <Location "/" >
    More stuff here
  </Location>
</VirtualHost>
  No volumes.

Deployment #9 (latest):
...
```

**oc version**
```
oc v1.3.0-rc1+ffdeb1b-dirty
kubernetes v1.4.0-beta.3+d19513f
features: Basic-Auth

Server https://10.13.137.149:8443
openshift v1.3.0-rc1
kubernetes v1.3.0+52492b4
```

cc @fabianofranz

**Comment by juanvallejo** [comment]
@AlbertoPeon Closing this issue for now, but please re-open if you're still experiencing it

**Comment by raffian** [comment]
nice one -> `oc set env dc/node MAIN_CONF="`cat apache.conf`"`
