### ISSUE TITLE
'oc rsync' with --strategy=rsync-daemon leaves zombie processes in container 

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#9882]
When running with the rsync-daemon strategy, a zombie process is created in the container, taking up space in the process table. 

The rsync --daemon process is started and later killed by the rsync command, but because it has no parent, the zombie entry remains in the process table.

##### Version
oc v1.3.0-alpha.2

##### Steps To Reproduce
1. Run oc rsync with --strategy=rsync-daemon to sync files to a container
2. 'oc rsh' into container and display processes ('ps ax')

##### Current Result
A zombie process is listed for each 'oc rsync' invocation

##### Expected Result
No zombie processes are present

##### Additional Information
A possible fix is to not start the daemon process in the background, but rather do it through an 'exec' invocation and hold it running in the foreground until the copy process is completed.

**Comment by csrwng** [comment]
@bparees fyi

**Comment by bparees** [comment]
@csrwng thx
