### ISSUE TITLE
flake: oc adm diagnostics doesn't run PodCheckDns

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9888]
```
FAILURE after 6.889s: test/end-to-end/core.sh:266: executing 'oadm diagnostics DiagnosticPod --images='openshift/origin-${component}:dbd64bb'' expecting success and text 'Running diagnostic: PodCheckDns': the output content test failed
Standard output from the command:
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/tmp/openshift/test-end-to-end-docker//openshift.local.config/master/admin.kubeconfig'

[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint

Info:  Output from the diagnostic pod (image openshift/origin-deployer:dbd64bb):
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected

[Note] Summary of diagnostics execution (version v1.3.0-alpha.2+dbd64bb):
[Note] Completed with no errors or warnings seen.

There was no error output from the command.
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3433/console

**Comment by sosiouxme** [comment]
The failure is because the diagnostic pod is supposed to run two diagnostics at this time, and only one ran. I can't see why that would happen - the missing diagnostic isn't conditional on anything. It's as if the name were left out of the list somehow.

**Comment by sosiouxme** [comment]
I don't see how this could flake or anything that would help diagnose it. The job is gone now; tag this issue if it ever happens again, otherwise I don't really have anything to add here :(

**Comment by sosiouxme** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/4140/consoleFull#-720211075762928fe4b031e1b25ced2a

**Comment by sosiouxme** [comment]
The flake shouldn't be happening anymore but I'm leaving this here to figure out why it happened, fix, and reinstate the test.

**Comment by sosiouxme** [comment]
My fix for this flake was [reverted](https://github.com/openshift/origin/pull/12890/files) in an attempt to fix another flake (which I honestly don't think was affected), so it may be back occasionally. I'll take a look when I can.
