### ISSUE TITLE
Support obtaining registry token via basic auth

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#9895]
https://github.com/openshift/origin/pull/9887 adds support for a token challenge, but is limited to issuing a token to anonymous users, or validating/echoing an existing API token provided as a "password".

If a password is not a valid token, the registry token issuing endpoint could attempt to obtain an API token using the provided credentials. Note that this will only succeed if a basic-auth method is configured.

**Comment by mfojtik** [comment]
@liggitt should this become a card?

**Comment by liggitt** [comment]
it already was: https://trello.com/c/XWtly5p1/621-spike-support-integrating-docker-registry-login-with-openshift-credentials
