### ISSUE TITLE
Unable to delete pod by ID

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#9897]
Per one of the examples in `oc delete -h`, I should be able to  delete a pod using its ID:
`oc delete pod <pod_id>`. This however fails with error `Error from server: pods "`\<pod_id\>`" not found`.

##### Version
oc v1.3.0-alpha.0+d26c9ce-dirty
kubernetes v1.3.0+57fb9ac
features: Basic-Auth

##### Steps To Reproduce
1. Create new pod with `oc new-app node`
2. Obtain pod's ID with `oc get pod <pod_name> -o yaml`
3. Attempt to delete pod with `oc delete pod <pod_id>`

##### Current Result
Error from server: pods "`<pod_id>`" not found.

##### Expected Result
Pod should be removed.

##### Additional Information
Related BugZilla: https://bugzilla.redhat.com/show_bug.cgi?id=1342914

**Comment by liggitt** [comment]
are you referring to the uid?

**Comment by liggitt** [comment]
I think the help message just needs tweaking to say "pod name". Delete by UID has never been supported
