### ISSUE TITLE
Testdata and external repositories

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#9899]
I've found that some of our test data use personal GitHub repositories. It's not a problem and work so far but IMHO this fact makes our extended tests weaker because of these dependencies.

If one of the repository owners decide to clean up his repositories and forgot that our tests uses one of his repo, our tests will fail. If we change something that requires update of the source repositories then we should create a couple of PRs to a different repos and waiting while their owner merge them.

It just and idea for tests improvement.

Here are some examples:

```
test/extended/testdata/forcepull-setup.json:                    "uri": "https://github.com/gabemontero/forcepull-extended-test-builder.git"
test/extended/testdata/incremental-auth-build.json:            "uri": "https://github.com/bparees/incremental-app.git"
test/extended/testdata/incremental-auth-build.json:            "uri": "https://github.com/bparees/incremental-app.git"
test/testdata/app-scenarios/new-project-no-build.yaml:        uri: git://github.com/mfojtik/sinatra-example-2
test/testdata/app-scenarios/new-project-one-build.yaml:        uri: git://github.com/mfojtik/sinatra-example-1
test/testdata/app-scenarios/new-project-one-build.yaml:        uri: git://github.com/mfojtik/sinatra-example-1
test/testdata/app-scenarios/new-project-two-deployment-configs.yaml:        uri: git://github.com/mfojtik/sinatra-app-example
test/testdata/app-scenarios/new-project-two-deployment-configs.yaml:        uri: git://github.com/mfojtik/sinatra-app-example
```

**Comment by php-coder** [comment]
As part of https://github.com/openshift/origin/pull/9813 I've added dependence on the https://github.com/php-coder/java-maven-hello-world repository.

**Comment by bparees** [comment]
for  https://github.com/bparees/openshift-jee-sample we now have https://github.com/openshift/jee-ex that we can use instead.

**Comment by rhcarvalho** [comment]
@php-coder @bparees is this still something we'd like done?

**Comment by bparees** [comment]
@rhcarvalho yes though it's not very high priority.

**Comment by php-coder** [comment]
>As part of #9813 I've added dependency on the https://github.com/php-coder/java-maven-hello-world repository.

This will be resolved in https://github.com/openshift/origin/pull/12312

**Comment by bparees** [comment]
doing some work on this here:
https://github.com/openshift/origin/pull/14178

the remaining obvious issues are @gabemontero's force pull repo and @mfojtik has some some references to github.com/mfojtik/sinatra-example-1, github.com/mfojtik/sinatra-example-2 and github.com/mfojtik/sinatra-example

**Comment by gabemontero** [comment]
I already removed `test/extended/testdata/forcepull-setup.json` in late 2016.  It no longer exists in the origin repo.

**Comment by bparees** [comment]
@gabemontero it's still referenced from `origin/test/extended/testdata/jenkins-plugin/create-job.xml` and `origin/test/extended/testdata/jenkins-plugin/delete-job.xml`

**Comment by bparees** [comment]
(look for your name in those files)

**Comment by gabemontero** [comment]
my bad .... submitted https://github.com/openshift/origin/pull/14247
