### ISSUE TITLE
oc annotate fails when used with --resource-version

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#9908]
When using annotate with a `--resource-version` on a resource, such as `oc annotate pod <pod_name> --resource-version=1820 description='myannotation'`, the command fails with the error: `error: --resource-version may only be used with a single resource`.

Upon printing the output of `resources` that the annotate command receives, it prints: `Resources:[pod <pod_name>]`. In other words, it treats the name of the resource as a second resource.

##### Version
oc v1.3.0-alpha.0+ae234a2-dirty
kubernetes v1.3.0+57fb9ac
features: Basic-Auth

##### Steps To Reproduce
1. `oc annotate pod <pod_name> --resource-version=1820 description='myannotation'`

##### Current Result
`error: --resource-version may only be used with a single resource`.

##### Expected Result
Resource should be updated with annotation info.

##### Additional Information
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1257853

**Comment by juanvallejo** [comment]
This function in `vendor/k8s.io/pkg/kubectl/cmd/util/helpers.go` parses resources from cli arguments, but does not seem to distinguish between resource kinds from resource names, thus returning "more than one resource" [here](https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/annotate.go#L151) even when only one is passed through cli args.
```
func GetResourcesAndPairs(args []string, pairType string) (resources []string, pairArgs []string, err error) {
	foundPair := false
	for _, s := range args {
		nonResource := strings.Contains(s, "=") || strings.HasSuffix(s, "-")
		switch {
		case !foundPair && nonResource:
			foundPair = true
			fallthrough
		case foundPair && nonResource:
			pairArgs = append(pairArgs, s)
		case !foundPair && !nonResource:
			resources = append(resources, s)
		case foundPair && !nonResource:
			err = fmt.Errorf("all resources must be specified before %s changes: %s", pairType, s)
			return
		}
	}
	return
}
```

**Comment by juanvallejo** [comment]
@liggitt or @fabianofranz could you take a look please?

**Comment by liggitt** [comment]
what does `oc annotate pod <podname>` do?

**Comment by juanvallejo** [comment]
@liggitt 
It returns an error `error: at least one annotation update is required`
Printing out the "annotation updates" it receives from the cli, and resources, I get:
```
AnnotationUpdates []
resources [pod <podname>]
```

**Comment by juanvallejo** [comment]
Changing the resource to include `kind/resource` seems to work: `oc annotate po/<pod_name> --resource-version=1820 description='myannotation'`.

However the help for `oc annotate` states I should still be able to use `oc annotate pod <pod_name>`

**Comment by liggitt** [comment]
should probably just move the check after we do Builder.Do(), and check if the result was singular. If it wasn't, and resourceVersion was set, error at that point

**Comment by juanvallejo** [comment]
@liggitt Sounds good, submitting PR for this. Thanks for your help
