### ISSUE TITLE
Importing Docker Images Images From The Public Registry

### ISSUE THREAD

**Issue by kamikazechaser** [openshift/origin#9910]
Importing Docker Images Images From The [Public](https://hub.docker.com/) Registry
##### Version

oc v3.2.1.3-1-gcbaf600
##### Additional Information

There isn't a proper example on how to import images from [here](https://hub.docker.com/). All the documentation says its [possible](https://docs.openshift.com/online/using_images/docker_images/index.html)

Any example of how to do it would be great.

**Comment by soltysh** [comment]
It looks like you're hitting the problem described in #9834.

**Comment by kamikazechaser** [comment]
A Ubuntu example would suffice, like [this one](https://hub.docker.com/r/phusion/baseimage/)

**Comment by kamikazechaser** [comment]
![image 1](https://cloud.githubusercontent.com/assets/18488025/16947770/88f596c4-4db9-11e6-942d-431721d49282.png)

**Comment by kamikazechaser** [comment]
Any suggestions?

**Comment by miminar** [comment]
> Any suggestions?

@kamikazechaser with the current version of OpenShift. You can do:

1. using Docker < 1.10 pull the image
2. tag it either as
  - `docker.io/<yourname>/imagename`
  - `${INTERNAL_DOCKER_REGISTRY_IP}/openshift/imagename`
3. push it using the same tag
4. deploy from that

Using docker < 1.10, you may be sure that the pushed image will be of schema v1 which is importable both by current registry version and docker 1.9.

**Comment by kamikazechaser** [comment]
Ok I will give it a shot.

**Comment by kamikazechaser** [comment]
@miminar Actually OpenShift pulls the image successfully from the Hub
![image 3](https://cloud.githubusercontent.com/assets/18488025/16990903/71fe3df6-4ea2-11e6-9bb6-dc46a797fcdf.png)

**Comment by kamikazechaser** [comment]
**Update:**

When attempting to deploy, I get an error 
`
This pod has been stuck in the pending state for more than 5 minutes`

**Some more Logs:**
```

I0720 10:48:42.436806       1 deployer.go:200] Deploying kamikazetech/ubuntu-4 for the first time (replicas: 1)
I0720 10:48:42.441709       1 recreate.go:126] Scaling kamikazetech/ubuntu-4 to 1 before performing acceptance check
I0720 10:48:44.468651       1 recreate.go:131] Performing acceptance check of kamikazetech/ubuntu-4
I0720 10:48:44.468744       1 lifecycle.go:445] Waiting 600 seconds for pods owned by deployment "kamikazetech/ubuntu-4" to become ready (checking every 1 seconds; 0 pods previously accepted)
F0720 10:58:44.469095 1 deployer.go:70] update acceptor rejected kamikazetech/ubuntu-4: pods for deployment "kamikazetech/ubuntu-4" took longer than 600 seconds to become ready

```

**Could This be The Problem:**
![image 019](https://cloud.githubusercontent.com/assets/18488025/16991370/fc59f8fe-4ea3-11e6-9d92-38261adb6117.png)

**Comment by miminar** [comment]
> Actually OpenShift pulls the image successfully from the Hub

@kamikazechaser That's expected. Pulling it is no problem, because Docker hub converts it on the fly to schema v1 which has a different digest than the one on the hub. So if you try to pull using this digest you will fail because it isn't stored on the hub. Thus the deployer will fail because docker fails to pull given digest.

**Comment by kamikazechaser** [comment]
@miminar So I have to use Docker to pull first. Then tag it and push back to OpenShift Online?

**Comment by miminar** [comment]
> So I have to use Docker to pull first. Then tag it and push back to OpenShift Online?

Pushing it **back** to OpenShift Online suggests that OpenShift is a source of the image that's causing you trouble. And I doubt that's the case.

Basically, you can push it anywhere as long as you use docker < 1.10 so you can be sure that the resulting image manifest will be of schema v1 - such a manifest can be safely consumed by the OpenShift and docker of any version.

You can also push it to OpenShift Online with any docker version you want. Because OpenShift's registry stores only v1 schema. Then refer to the pushed image instead of original source on the Docker Hub.

**Comment by metmajer** [comment]
+1

```
oc v1.2.0-rc2
kubernetes v1.2.0-36-g4a3f9c5
openshift-ansible v3.2.14-1
```

**Comment by metmajer** [comment]
Interesting finding: seems like images from the Docker Hub run successfully if they make proper use of USER. The problem persists for all images who don't.

**Comment by kamikazechaser** [comment]
@metmajer Thats interesting. How did you do it?

**Comment by metmajer** [comment]
I don't have an explanation for this, but all images I had designed to comply with OpenShift Docker image best practices are running successfully, while their non-compliant equivalents do not work. They produce exactly the same error you have documented further above and the same applies to official images such as 'tomcat' and all others I have tested.

Here's a project with OpenShift compliant Dockerfiles: https://github.com/dynatrace-innovationlab/easyTravel-OpenShift/tree/master/build and here are the non-compliant equivalents: https://github.com/dynatrace-innovationlab/easyTravel-Docker/tree/master/build. These images are available on the Docker Hub as `dynatrace/easytravel-$component` and `dynatrace/easytravel-$component:openshift`, respectively.

@kamikazechaser You could verify that the non-compliant images fail with said error by issuing an `oc new-app dynatrace/easytravel-mongodb` whereas `oc new-app dynatrace/easytravel-mongodb:openshift` should not.

**Comment by benhosmer** [comment]
@metmajer I was hoping to confirm the container running as root answer, but your repo `dynatrace/easytravel-mongodb` doesn't have an `:openshift` tag.

I did however try this `$ oc new-app --docker-image="docker.io/openshift/hello-openshift"`

And saw the similar error:

```

TimeSeverity	Reason	Message
8:08:35 PM	Warning	Failed sync 	Error syncing pod, skipping: failed to "StartContainer" for "hello-openshift" with ImagePullBackOff: "Back-off pulling image \"docker.io/openshift/hello-openshift@sha256:0b42d06db9dafdb6d0337936b52fb5ecd7584a17da1afafcec6b62d37d8f53c2\""
32 times in the last 7 minutes
8:08:24 PM	Normal	Back off 	Back-off pulling image "docker.io/openshift/hello-openshift@sha256:0b42d06db9dafdb6d0337936b52fb5ecd7584a17da1afafcec6b62d37d8f53c2"
31 times in the last 7 minutes
8:06:29 PM	Warning	Failed 	Failed to pull image "docker.io/openshift/hello-openshift@sha256:0b42d06db9dafdb6d0337936b52fb5ecd7584a17da1afafcec6b62d37d8f53c2": image pull failed for docker.io/openshift/hello-openshift@sha256:0b42d06db9dafdb6d0337936b52fb5ecd7584a17da1afafcec6b62d37d8f53c2, this may be because there are no credentials on this request. details: (manifest unknown: manifest unknown)
6 times in the last 7 minutes
8:06:29 PM	Warning	Failed sync 	Error syncing pod, skipping: failed to "StartContainer" for "hello-openshift" with ErrImagePull: "image pull failed for docker.io/openshift/hello-openshift@sha256:0b42d06db9dafdb6d0337936b52fb5ecd7584a17da1afafcec6b62d37d8f53c2, this may be because there are no credentials on this request. details: (manifest unknown: manifest unknown)"
6 times in the last 7 minutes
8:06:28 PM	Normal	Pulling 	pulling image "docker.io/openshift/hello-openshift@sha256:0b42d06db9dafdb6d0337936b52fb5ecd7584a17da1afafcec6b62d37d8f53c2"
6 times in the last 7 minutes
8:00:50 PM	Normal	Scheduled 	Successfully assigned hello-openshift-1-66p61 to origin
````

This is using the vagrant install of openshift origin.
```
[vagrant@localhost ~]$ oc version
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
[vagrant@localhost ~]$ docker --version
Docker version 1.9.1, build ee06d03/1.9.1
```

**Comment by bparees** [comment]
pretty sure everything related to this is resolved(manifest import issues) or working as expected(can't run images that run as root, by default).  The hello-openshift image actually did run as root, but that has been fixed recently.

/close
