### ISSUE TITLE
multiple extended test execution is broken

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9922]
I requested two sets of extended test runs via two separate comments (that you can't put both in a single comment is a separate issue):

```
[testextended][extended:core(builds)]
[testextended][extended:core(images)]
```

to which the bot correctly responded:
```
continuous-integration/openshift-jenkins/testextended Running (https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/345/) (Extended Tests: core(images), core(builds))
```

but if you look at what it ran, it failed on one of the image tests and then never ran the build tests:

https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/324/consoleFull

**Comment by stevekuznetsov** [comment]
So the extended test regex that we're running is `\[extended *:( *[^,\[\]]+ *(, *[^,\[\]]+ *)*)\]`, so you should be able to trigger multiple extended focuses with a comma-delimited list: `[extended:core(builds),core(images)]` currently parsing `[extended:core(builds)]` into `core(builds)` happens in the bot, then parsing that into `test/extended/core.sh --ginkgo.focus='builds'` happens in the `vagrant-openshift` plugin. We can see that both of your requests go through by looking at the [parameters](https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/324/parameters/), however what `vagrant-openshift` ends up doing is running:
```sh
test/extended/core.sh --ginkgo.focus='builds'
test/extended/core.sh --ginkgo.focus='images'
```

Whereas what we *want* is:
```sh
test/extended/core.sh --ginkgo.focus='builds|images'
```

So what you should tag with is:
````
[testextended][extended:core(builds|images)]
```

**Comment by bparees** [comment]
The bot is supposed to correctly combine multiple test tags.  so while you've given me a workaround (delete all my existing comments and make a new comment), the bot's behavior is still wrong in my scenario.

**Comment by stevekuznetsov** [comment]
I mean, it has combined your queries ... just not exactly how you wanted. From a cursory glance, determining how to combine them and obey the `--ginkgo.focus` syntax seems needlessly complicated / nontrivial. @danmcp could weigh in but I'm not really sure the time is better spent implementing that versus having the user provide a fully-formed focus string.

**Comment by danmcp** [comment]
@bparees @stevekuznetsov Yeah I don't want to put that sort of logic in the bot.  It's just doing a join(',').  You can parse it out in vagrant openshift or in the test command maybe.  But the contract for the bot is it will send to jenkins a comma separated list of what was requested.
