### ISSUE TITLE
Allow to specify an args (for entrypoint) to a ExecNewPodHook

### ISSUE THREAD

**Issue by xavfernandez** [openshift/origin#9924]
Just like for `v1.Container` which allows either a `command` or an `args` entry, it would be nice (and more consistent) if `v1.ExecNewPodHook` also supported the `args` entry.

**Comment by mfojtik** [comment]
@bparees @rhcarvalho I know we had an extensive discussion over this for post-build hooks, maybe it is time to make it consistent with deployments. My only worry here is to not break the backward compatibility.

**Comment by rhcarvalho** [comment]
@mfojtik the request seems to be backwards compatible. Haven't checked, but from what is said above, `command` and `args` cannot be used together in deployment hooks. The request is to allow using the two things together.

The Docker API and build hooks both support using those together.

The change affects only deployments. Depending on the timeline for phasing out the current deployment objects, that might be something we can support for consistency.

**Comment by mfojtik** [comment]
@smarterclayton do you think this is something that upstream will want once we start upstreaming the hooks?

**Comment by xavfernandez** [comment]
@rhcarvalho Currently `v1.ExecNewPodHook` does not seem to support entrypoint at all: https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-execnewpodhook
while `v1.Container` supports both
https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-container

It should not imply any backward incompatibility.
