### ISSUE TITLE
Git clone timouts- DNS issue

### ISSUE THREAD

**Issue by mjudeikis** [openshift/origin#9927]
Git clone timeouts from private repos

```
##### Version
-bash-4.2$ oc version
oc v3.2.0.44
kubernetes v1.2.0-36-g4a3f9c5

```
##### Steps To Reproduce
1. Create new BC with access to private git
2. try to build it

```
##### Current Result
uilder.go:204] Error: build error: timeout while waiting for remote repository
##### Expected Result
success
##### Additional Information
ERROR: [DCli2012 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:155]
       See the errors below in the output from the diagnostic pod:
       [Note] Running diagnostic: PodCheckAuth
              Description: Check that service account credentials authenticate as expected

       WARN:  [DP1005 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:85]
              A request to the master timed out.
              This could be temporary but could also indicate network or DNS problems.

       ERROR: [DP1006 from diagnostic PodCheckAuth@openshift/origin/pkg/diagnostics/pod/auth.go:110]
              DNS resolution for registry address docker-registry.default.svc.cluster.local timed out; this could indicate problems with DNS resolution or networking

       [Note] Running diagnostic: PodCheckDns
              Description: Check that DNS within a pod works as expected

       WARN:  [DP2009 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:64]
              A request to the master (SkyDNS) nameserver 172.30.0.1 timed out.
              This could be temporary but could also indicate network or DNS problems.
              This nameserver is critical for resolving cluster DNS names.

       WARN:  [DP2014 from diagnostic PodCheckDns@openshift/origin/pkg/diagnostics/pod/dns.go:119]
              A request to the nameserver 172.30.0.1 timed out.
              This could be temporary but could also indicate network or DNS problems.

       [Note] Summary of diagnostics execution (version v3.2.0.44):
       [Note] Warnings seen: 3
```

53 Ports is there:

```
sudo nmap -sT -O localhost
Starting Nmap 6.40 ( http://nmap.org ) at 2016-07-19 11:58 BST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000089s latency).
Not shown: 994 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
25/tcp   open  smtp
53/tcp   open  domain
111/tcp  open  rpcbind
443/tcp  open  https
9090/tcp open  zeus-admin
```

from container:

```
curl -v docker-registry.default.svc.cluster.local:5000/healthz
curl: (6) Could not resolve host: docker-registry.default.svc.cluster.local; Name or service not known
```

and resolv.conf file:

```
sh-4.2$ cat /etc/resolv.conf
search mj.svc.cluster.local svc.cluster.local cluster.local uk.mycompany.com srv.mycompany.sub.com
nameserver 172.30.0.1
nameserver 10.232.1.2
nameserver 10.xxx.96.20
nameserver 10.xxx.128.20
options attempts:3
options ndots:5

```

How I can check other details?

**Comment by Mangirdaz** [comment]
@danmcp let me know if you need more details, or more logs. And want is recommended Networkmanager state on estate? previously we had to remove it, not looks like now. can it be a case?

**Comment by Mangirdaz** [comment]
I can see DNS is running on masters:
dnsmasq[32489]: using nameserver 172.30.0.1#53 for domain cluster.local
with bunch of limit errors
Maximum number of concurrent DNS queries reached (max: 150)

**Comment by knobunc** [comment]
Can you please run 'oc get endpoints -n default kubernetes'  It should list the IP addresses of the masters.

Then try:
 > dig docker-registry.default.svc.cluster.local @172.30.0.1 
 > dig docker-registry.default.svc.cluster.local @...

(replace ... above with one of the endpoints from the oc get endpoints command)

**Comment by PI-Victor** [comment]
this related to: https://github.com/openshift/origin/issues/9789

**Comment by Mangirdaz** [comment]
k, tooks me a while to get dig to container (sad story :/ )

```
-bash-4.2$ oc get endpoints -n default kubernetes
NAME         ENDPOINTS                                                           AGE
kubernetes   10.236.111.114:53,10.236.111.99:53,10.236.111.114:443 + 3 more...   22h
```

```
sh-4.2# dig docker-registry.default.svc.cluster.local @172.30.0.1
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> docker-registry.default.svc.cluster.local @172.30.0.1
;; global options: +cmd
;; connection timed out; no servers could be reached
```

```
sh-4.2# dig docker-registry.default.svc.cluster.local @10.236.111.114
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> docker-registry.default.svc.cluster.local @10.236.111.114
;; global options: +cmd
;; connection timed out; no servers could be reached
```

output from: https://raw.githubusercontent.com/openshift/openshift-sdn/master/hack/debug.sh
CASE 01670960 on access portal (sorry, cant upload here)

**Comment by Mangirdaz** [comment]
Can it be SND plugin??

**Comment by knobunc** [comment]
I don't suppose this is the same as https://github.com/openshift/openshift-ansible/issues/2163 ?

**Comment by Mangirdaz** [comment]
Does not looks like this. I cant get to dig docker-registry.default.svc.cluster.local @172.30.0.1
so looks like internal DNS is not serving me at all, can it be a case? (Registry is running just fine)

**Comment by knobunc** [comment]
Can you try restarting the openshift processes and see if that makes DNS start working?

**Comment by Mangirdaz** [comment]
no luck. Any other way to check skyDNS state?

**Comment by Mangirdaz** [comment]
Ok, so looks like SKYDNS was not able to start because dnsmasq was running (no idea where it came from on my boxes (going to central configuration management team. )).

Just to be sure, dnsmasq is not part of openshift deployment???

**Comment by bparees** [comment]
correct, you need to disable it prior to starting openshift so openshift can grab the port.

**Comment by Mangirdaz** [comment]
but as there fresh VMs and i only ran Openshift ansible on those, whats the chance it was one of the deployment dependency of openshift? 

*going to crash and burn all my boxes and rebuild stuff to check* 

but thanks guys, i learned more on DNS in OSE than i expected!

**Comment by roshan-mr** [comment]
Hi Mangirdaz,

Disabling the dnsmasq service fixed the issue for you? I am also experiencing the same issue.

Regards,
Muhammed Roshan

**Comment by scheng1** [comment]
@scheng1

**Comment by bzon** [comment]
Do we have the same issue? https://github.com/openshift/origin/issues/15207#issuecomment-315522917

**Comment by coreydaley** [comment]
This seems to be a much older version of OSO and potentially the OS it was running on, along with the linked issue (#15207) having been closed.  Please re-open this issue, or create a new one, if you are still experiencing this issue.
