### ISSUE TITLE
Test flake in cmd/quota.sh: secrets not showing up

### ISSUE THREAD

**Issue by miminar** [openshift/origin#9929]
```
FAILURE after 60.119s: test/cmd/quota.sh:25: executing 'oc describe appliedclusterresourcequota/for-deads-by-annotation -n bar --as deads' expecting any result and text 'secrets.*18'; re-trying every 0.2s until completion or 60.000s: the command timed out
Standard output from the command:
Name:		for-deads-by-annotation
Namespace:	<none>
Created:	2 seconds ago
Labels:		<none>
Annotations:	<none>
Label Selector: <null>
AnnotationSelector: map[openshift.io/requester:deads]
...

... repeated 2 times
Name:		for-deads-by-annotation
Namespace:	<none>
Created:	About a minute ago
Labels:		<none>
Annotations:	<none>
Label Selector: <null>
AnnotationSelector: map[openshift.io/requester:deads]
Resource	Used	Hard
--------	----	----
secrets		17	50
... repeated 3 times
There was no error output from the command.
[ERROR] jUnit test marker could not be placed, expected one test in flight, got 0
[ERROR] PID 2608: hack/lib/cmd.sh:95: `return 1` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/cmd.sh:95: `return 1`
[INFO] 		  2: hack/lib/cmd.sh:139: os::cmd::internal::run_until_text
[INFO] 		  3: test/cmd/quota.sh:25: os::cmd::try_until_text
[INFO]   Exiting with code 1.
```

See [job 3506](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/3506/console) for details.

**Comment by deads2k** [comment]
@stevekuznetsov The etcd dump for the linked build doesn't have any data in it.  Any idea where it went?

**Comment by stevekuznetsov** [comment]
Looking ... the jUnit stuff failed as well. Weird.

**Comment by deads2k** [comment]
> Looking ... the jUnit stuff failed as well. Weird.

Thanks.  I'd like to know why my secrets aren't getting created.  Getting less than 18 secrets means that something won't work.

**Comment by stevekuznetsov** [comment]
I mean let's be honest here, 18 is a lot of secrets. Can't we just live with, 15 or so?

**Comment by stevekuznetsov** [comment]
As an aside, can you do a `jsonpath` into the object instead of a `grep` on the output of `describe`?

**Comment by stevekuznetsov** [comment]
Fixed the jUnit bug. but since the cleanup for `test-cmd` is still a) special and b) inside `set +o errexit` we really can't tell if that `curl` succeeded or not, sorry. There's no logs and I guess it just failed silently?

**Comment by deads2k** [comment]
This is the "off by one" (off by X since we started batching the updates) that is caused by a reconciliation check that doesn't get a complete list that includes secrets about to be created.  The design here: https://github.com/kubernetes/kubernetes/pull/20113 ought to resolve it.

I'll address this by loosening the regex to eliminate the flake.
