### ISSUE TITLE
out of quota or nearly out of quota should show as warning on oc status

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#9930]
We don't need it in a normal case, but if you're out of quota or almost out of quota (or appliedclusterquota), a warning seems to be in order.

@fabianofranz maybe @juanvallejo ?

**Comment by juanvallejo** [comment]
I think it would be useful, it would benefit from being the last thing (or something towards the bottom) that the user sees in case they have a pretty big output for `oc status`. @oatmealraisin mentioned having it as part of the message a user sees when they ssh into a container as well.

**Comment by oatmealraisin** [comment]
@juanvallejo I was just using an ssh login message as an example, we could display the information on `oc login`

**Comment by deads2k** [comment]
@juanvallejo we have warning markers that can appear at the end.  This is warning marker worthy.
