### ISSUE TITLE
'service network restart' silently disables IP forwarding until Openshift node is restarted

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#9931]
AFAICS, it is the Openshift node process (sdn plugin) that is currently responsible for enabling the net.ipv4.ip_forward sysctl as a one-shot when it starts up.

As things stand, if an unfortunate admin runs 'service network restart' on a machine while the openshift node process is running, the stop() part of /etc/init.d/network will disable net.ipv4.ip_forward, however the start() part will not re-enable it.  I think the usual means by which this is achieved is adding line reading 'net.ipv4.ip_forward=1' in /etc/sysctl.conf (this is actually applied by /etc/init.d/network!), but this is not laid down by the ansible installer by default.

It's a gotcha that 'service network restart' will silently break IP forwarding, and it's easy enough for novice admins to run into this problem while trying to debug network issues.

It would be nice to get to a point where 'service network restart' would not break openshift IP forwarding, and make this were provable via automated testing.

**Comment by tosmi** [comment]
we got hit by this when upgrading from 3.2.1.15 to 3.2.1.21. after running the ansible playbook ip_forward was set to 0 and it took us some time to figure out what had happend. restarting the atomic-openshift-node service did _not_ fix this, only a reboot of affected nodes (== all nodes in this cluster).

**Comment by knobunc** [comment]
@sdodson any idea why we don't set that in the installer?  If it is not deliberate I can look at trying to set it.

**Comment by tosmi** [comment]
just did the upgrade from 3.2.1.21 to 3.3.1.7, it happend again on two nodes, the masters were unaffected this time.

**Comment by sdodson** [comment]
We do that in the installer here https://github.com/openshift/openshift-ansible/commit/2ce9018ece4dffe10ecc355adffa6fd2782619d7 but that code wouldn't be executed during an upgrade. So only if one installed using 3.4 installer or 3.3 installer newer than 3.3.30 that should be set.
