### ISSUE TITLE
Redundant labels in Prometheus metrics (upstreamed PR)

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#9958]
Previous versions of Kubernetes/OpenShift didn't properly expose Docker labels as Prometheus labels so pod name, namespace name, etc were derived from container name. Kubernetes now properly sets the Docker labels & cadvisor properly exposes these (e.g. io.kubernetes.pod.name as io_kubernetes_pod_name, etc) so this is no longer required & actually results in unnecessary duplicate Prometheus labels.

Upstreamed PR (kubernetes/kubernetes#29291) already submitted - shall I submit a PR with the same patch to vendored deps?

**Comment by mwringe** [comment]
I don't know why this is assigned to me. The Prometheus endpoint falls outside of what we are currently doing with Origin Metrics.

I think all that @jimmidyson is asking is if he should submit this PR to the origin code or wait until upstream accepts it and then pull it in with a rebase. Of which I don't know what the proper procedure is.

@danmcp do you know what the acceptable procedure is here? Should we wait for upstream and a rebase or submit a PR directly to origin? As far as I can tell it just means a duplication of labels, so while its something which needs to be fixed, I don't know of its urgency.

**Comment by danmcp** [comment]
@jimmidyson There is still one more rebase planned for 3.3.  But if your change isn't in the kube 1.3 stream and it needs to get into 3.3, you will need to cherry-pick it.

**Comment by jimmidyson** [comment]
@danmcp OK thanks - hopefully it will be in 1.3 stream soon.
