### ISSUE TITLE
Pods stay in ContainerCreating forever

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9959]
test failure is
```
FAILURE after 120.068s: test/end-to-end/core.sh:29: executing 'oc get -n test pods' expecting any result and text 'frontend.+Running'; re-trying every 0.2s until completion or 120.000s: the command timed out
```
but the logs show the deployment pod (frontend-1-deploy) is in "ContainerCreating" and stays that way for the full 2 minute timeout.

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3654/consoleFull

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/3672/console

**Comment by stevekuznetsov** [comment]
Upgrading this to a P1 -- @bparees why did you label this a Docker issue?

**Comment by bparees** [comment]
@stevekuznetsov because "ContainerCreate" means k8s requested docker to create the container and docker hasn't successfully done so.

**Comment by stevekuznetsov** [comment]
FYI @runcom @rhatdan help appreciated here

**Comment by rhatdan** [comment]
Anything from the docker logs?

**Comment by stevekuznetsov** [comment]
I don't think they're plumbed through quite yet ... hopefully soon.

**Comment by jwhonce** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1360921 Covers logging enhancement during buids

**Comment by stevekuznetsov** [comment]
Seeing this quite a lot on my open PRs, bumping priority

**Comment by liggitt** [comment]
possibly resolved in https://github.com/openshift/origin/pull/10111

**Comment by liggitt** [comment]
hasn't been referenced since the day after the storage fixes went in, closing hopefully.
