### ISSUE TITLE
Visceral Infrastructure Failures Causing Conformance to Timeout

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9965]
Something is going wrong in our extended conformance tests and it looks like no pods ever get deployed. See:
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3765/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3760/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3755/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3754/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3751/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3742/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3741/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3738/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3737/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3728/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3666/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3663/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3651/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3643/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3623/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3614/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3611/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3605/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3602/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3598/
 - https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3593/

Might be a Docker daemon issue.

@smarterclayton @deads2k @liggitt @ncdc @rhatdan @runcom @bparees @pweil- @danmcp

**Comment by runcom** [comment]
Is this running docker 1.10.3?

**Comment by runcom** [comment]
Today @ncdc found a patch to be backported to prevent a race which caused the daemon to panic (I'm not saying this is the issue here but if docker is casing this somehow that can be an issue)

**Comment by stevekuznetsov** [comment]
@runcom 
```
$ yum list installed
....
docker.x86_64                1.10.3-46.el7.3      @dockerextra                  
docker-common.x86_64         1.10.3-46.el7.3      @dockerextra                  
docker-forward-journald.x86_64
                             1.10.3-46.el7.3      @dockerextra                  
docker-rhel-push-plugin.x86_64
                             1.10.3-46.el7.3      @dockerextra                  
docker-selinux.x86_64        1.10.3-46.el7.3      @dockerextra 
...
```

**Comment by runcom** [comment]
We could build docker from the latest patches we have (which didn't make the release) in docker rhel branch and test everything again. Is this doable? /cc @lsm5

**Comment by runcom** [comment]
Steve do you have docker logs about those failures?

**Comment by stevekuznetsov** [comment]
> We could build docker from the latest patches we have 

For a while the `dockerextra` repo on the OpenShift mirror list wasn't getting updated with 1.10.3 builds that did end up in RHEL -- @tdawson would know about the state of this today.

> Steve do you have docker logs about those failures? 

No.

**Comment by ncdc** [comment]
@stevekuznetsov if we aren't currently doing it, it would be nice if we could get journalctl output for docker.

**Comment by stevekuznetsov** [comment]
@ncdc currently the jobs were being killed by Jenkins and the post-build download step wasn't occurring for artifacts. If the test script correctly fails and cleanup occurs, we [log the last fifteen minutes from `journalctl`](https://github.com/openshift/origin/blob/master/hack/util.sh#L601) for the Docker daemon and the artifacts can be found at `openshift/test-extended/core/logs/docker.log` [ex. here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3787/s3/download/openshift/test-extended/core/logs/docker.log)

I've reconfigured the Jenkins master to not abort the jobs, so instead, the host Vagrant connection should terminate running processes after 4h. However, I'm not certain that the termination will result in the `journalctl` logs being dumped, although it will net us all the other artifacts that existed at the time of termination. We'd need someone to implement a logging mechanism by which we can grab stuff even if something times out and the job gets killed without running cleanup correctly to get logs always. I don't have the bandwidth to do that.

**Comment by stevekuznetsov** [comment]
@ncdc @runcom another possible strategy to harvest logs would be to `ssh` into the EC2 instances running the failing tests while they're failing but not yet timed out. For instance, [this job](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3781/) right now looks to be such a candidate. Candidates can be identified by looking at the [job trend](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/buildTimeTrend) and looking for live jobs that have been running for two hours or more.

**Comment by ncdc** [comment]
```
goroutine 18115 [running]:
runtime.throw(0x17f6820, 0x15)
/usr/lib/golang/src/runtime/panic.go:547 +0x90 fp=0xc821588ef8 sp=0xc821588ee0
runtime.mapassign1(0x120b100, 0xc8212bc240, 0xc821588fe8, 0xc821588fc0)
/usr/lib/golang/src/runtime/hashmap.go:540 +0x54b fp=0xc821588fa0 sp=0xc821588ef8
github.com/docker/docker/layer.(*layerStore).Get(0xc8205e4ac0, 0xc82339c1e0, 0x47, 0x0, 0x0, 0x0, 0x0)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/layer/layer_store.go:342 +0x141 fp=0xc821589000 sp=0xc821588fa0
github.com/docker/docker/daemon.(*Daemon).LookupImage(0xc820001b00, 0xc82152c1cc, 0x1c, 0x0, 0x0, 0x0)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/daemon/daemon.go:1104 +0x525 fp=0xc821589298 sp=0xc821589000
github.com/docker/docker/api/server/router/local.(*router).getImagesByName(0xc820a2ce00, 0x7fd2d22d6c48, 0xc82298bbf0, 0x7fd2d22d6c10, 0xc82104df40, 0xc821595420, 0xc82298b7d0, 0x0, 0x0)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/api/server/router/local/image.go:286 +0xa6 fp=0xc821589318 sp=0xc821589298
github.com/docker/docker/api/server/router/local.(*router).(github.com/docker/docker/api/server/router/local.getImagesByName)-fm(0x7fd2d22d6c48, 0xc82298bbf0, 0x7fd2d22d6c10, 0xc82104df40,
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/api/server/router/local/local.go:97 +0x74 fp=0xc821589368 sp=0xc821589318
github.com/docker/docker/api/server.(*Server).auditMiddleware.func1(0x7fd2d22d6c48, 0xc82298bbf0, 0x7fd2d22d6c10, 0xc82104df40, 0xc821595420, 0xc82298b7d0, 0x0, 0x0)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/api/server/middleware.go:163 +0xa2 fp=0xc8215893b8 sp=0xc821589368
github.com/docker/docker/api/server.versionMiddleware.func1(0x7fd2d22d6c48, 0xc82298bbf0, 0x7fd2d22d6c10, 0xc82104df40, 0xc821595420, 0xc82298b7d0, 0x0, 0x0)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a fp=0xc821589538 sp=0xc8215893b8
github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7fd2d22be538, 0xc820013340, 0x7fd2d22d6c10, 0xc82104df40, 0xc821595420, 0xc82298b7d0, 0x0, 0x0)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa fp=0xc821589598 sp=0xc821589538
github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7fd2d22be538, 0xc820013340, 0x7fd2d22d6c10, 0xc82104df40, 0xc821595420, 0xc82298b7d0, 0x0, 0x0)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/api/server/middleware.go:117 +0x4af fp=0xc8215896a8 sp=0xc821589598
github.com/docker/docker/api/server.(*Server).authorizationMiddleware.func1(0x7fd2d22be538, 0xc820013340, 0x7fd2d2231400, 0xc822575e10, 0xc821595420, 0xc82298b7d0, 0x0, 0x0)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/api/server/middleware.go:86 +0x5ba fp=0xc8215898d0 sp=0xc8215896a8
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fd2d2231400, 0xc822575e10, 0xc821595420)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/api/server/server.go:175 +0x2ad fp=0xc8215899f8 sp=0xc8215898d0
net/http.HandlerFunc.ServeHTTP(0xc820b1c940, 0x7fd2d2231400, 0xc822575e10, 0xc821595420)
/usr/lib/golang/src/net/http/server.go:1618 +0x3a fp=0xc821589a18 sp=0xc8215899f8
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820928050, 0x7fd2d2231400, 0xc822575e10, 0xc821595420)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e fp=0xc821589b30 sp=0xc821589a18
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820bab5c0, 0x7fd2d2231400, 0xc822575e10, 0xc821595420)
/builddir/build/BUILD/docker-a46c31af70ca8d15521e312ad9ef7085cfe2fd3f/_build/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72 fp=0xc821589b60 sp=0xc821589b30
net/http.serverHandler.ServeHTTP(0xc82007ce80, 0x7fd2d2231400, 0xc822575e10, 0xc821595420)
/usr/lib/golang/src/net/http/server.go:2081 +0x19e fp=0xc821589bc0 sp=0xc821589b60
net/http.(*conn).serve(0xc821658280)
/usr/lib/golang/src/net/http/server.go:1472 +0xf2e fp=0xc821589f88 sp=0xc821589bc0
runtime.goexit()
/usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc821589f90 sp=0xc821589f88
created by net/http.(*Server).Serve
/usr/lib/golang/src/net/http/server.go:2137 +0x44e
```

Should be fixed by https://github.com/projectatomic/docker/commit/a3eb7caa142094e01a452cea7faa9885f1dbbbc8.

I have confirmed that docker-1.10.3-46.el7.3.x86_64, which looks like it corresponds to commit a46c31af70ca8d15521e312ad9ef7085cfe2fd3f, does not contain the fix referenced above.

**Comment by ncdc** [comment]
So a new build of 1.10.3 should fix this

**Comment by runcom** [comment]
@ncdc great

**Comment by smarterclayton** [comment]
Conformance should be running a health check on the apiservers periodically
and bailing out if they go down.  Waiting 300s each test is ridiculous.

**Comment by ncdc** [comment]
According to @stevekuznetsov the test isn't origin containerized, so the apiserver stays up in this case even if docker goes down.

**Comment by lsm5** [comment]
The updated docker will be released in 7.2.6

**Comment by stevekuznetsov** [comment]
@lsm5 @runcom do we know which patch on `docker-1.10.3` has this fix?

**Comment by smarterclayton** [comment]
We need this fix in an RPM we can tag into our builds for testing.
Waiting for 7.2.6 isn't an option, because this is a blocker build for
a hundred developers.

**Comment by runcom** [comment]
> @lsm5 @runcom do we know which patch on docker-1.10.3 has this fix?

@stevekuznetsov https://github.com/projectatomic/docker/commit/a3eb7caa142094e01a452cea7faa9885f1dbbbc8

**Comment by stevekuznetsov** [comment]
@runcom sorry, by patch I meant the patch number in the resultant `docker-1.10.3-XX` RPM name. AFAIK @tdawson is mirroring Docker builds, not building himself, so unless it's simple to determine which commit is in which patch we need the patch number to mirror

**Comment by ncdc** [comment]
@stevekuznetsov the mirror has been updated to docker-1.10.3-46.el7.10, which contains the fixes we need.

**Comment by stevekuznetsov** [comment]
Ok. Let's keep an eye out and open this if we see any more failures.
