### ISSUE TITLE
Apache errors with node.js

### ISSUE THREAD

**Issue by elprogrammer** [openshift/origin#9974]
I made a node.js script that end the request without any body if something wrong happened. When I tested it I got error say that apache2 cannot accept empty body, I think it's the proxy you're using it said that too. Sorry I don't remember everything because that was a while ago but I think that's all

**Comment by danmcp** [comment]
Can you give any more details about what you tried (which image you were using, what commands you ran to launch it, what version of OpenShift, etc)?  It isn't clear how to recreate this.

**Comment by danmcp** [comment]
Based on the other issue you opened: https://github.com/openshift/origin/issues/9975

I am assuming this is also a 2.x bug.  Please go ahead and open a bugzilla for this as well.

Sorry for the inconvenience,

Dan
