### ISSUE TITLE
node.js dependencies errors

### ISSUE THREAD

**Issue by elprogrammer** [openshift/origin#9975]
I develop my node.js apps using the recommended version 4.4.7
When I push my repository to openshift it doesn't rebuild dependencies and everytime I have to open ssh and go to app-root/repo and rebuild them manually, that was really annoying.

**Comment by danmcp** [comment]
This is the wrong repo to open this issue against.  The correct place would be to open a bug against version 2.x here:

https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Online
