### ISSUE TITLE
oc new-project becomes very slow with hundreds of projects

### ISSUE THREAD

**Issue by a13m** [openshift/origin#9979]
I was trying to load-test a cluster yesterday, and ran this simple loop:

```sh
for x in $( seq 1 1500 ); do time oc new-project ops-loadtest$x; done
```
I expected this to take less than an hour, but after several hours, only about 550 projects had been created.

##### Version
oc v3.2.1.10-1-g668ed0a
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
```sh
for x in $( seq 1 1500 ); do time oc new-project ops-loadtest$x; done
```

I wasn't paying close attention the whole time, but the slowness was obvious by the 500th project.

##### Current Result

The project creation was quick at first (less than a second), but gradually slowed to more than a minute per command, and it seems that this is all due to rewriting ~/.kube/config ; I have confirmed that if I remove all of the test project contexts from the config file, the next project is created in about a second.

##### Expected Result

I would expect the CLI to be faster, and in my case I don't really care about it rewriting the kube config.

##### Additional Information

I discussed this with @jwforres , and she said that having an oc CLI parameter to simply skip rewriting the config would be reasonable.

**Comment by fabianofranz** [comment]
cc @deads2k

**Comment by deads2k** [comment]
Sounds reasonable to me too.  Also, `cp ` to a tmp file and `--config=tmpfile` works too.

We hit this in 1.1 while testing the project cache.
