### ISSUE TITLE
conformance flake: Extended.deploymentconfigs with minimum ready seconds set should include various info in status

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9987]
Extended.deploymentconfigs with minimum ready seconds set should include various info in status [Conformance]

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3870/

```
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:601
Expected error:
    <*errors.errorString | 0xc821085a30>: {
        s: "expected deployment \"minreadytest-1\" not to have terminated",
    }
    expected deployment "minreadytest-1" not to have terminated
not to have occurred
```

**Comment by kargakis** [comment]
What happens to a pod if docker is down? Will it be transitioned to Failed by kubelet or the api server? Smells like https://github.com/openshift/origin/issues/9965 but a failure trap should clear this out.

**Comment by mfojtik** [comment]
I will try to look at this while @kargakis will be out.

**Comment by kargakis** [comment]
> What happens to a pod if docker is down? Will it be transitioned to Failed by kubelet or the api server? Smells like #9965 but a failure trap should clear this out.

Seems like it. Docker is down, the deployer transitions to Failed, the deployment is marked as Failed.

**Comment by mfojtik** [comment]
@kargakis @smarterclayton will leave this open for another week if somebody hit this. If it is a Docker issue, there is not too much we can do.

**Comment by smarterclayton** [comment]
The two known issues are the crash (docker) and the secret mount / unmount
issue.  I have also not seen this, but not ruling it out yet.
