### ISSUE TITLE
Add --no-cache flag to `oc start-build`

### ISSUE THREAD

**Issue by danni** [openshift/origin#9988]
It would be extremely useful to have a `--no-cache` flag in `oc start-build` that is equivalent to the `noCache: true` setting in the build strategy.

**Comment by bparees** [comment]
would this flag only apply to docker type builds?  or would you also want it to set incremental to false for s2i builds?

**Comment by bparees** [comment]
also can you elaborate on when this is needed as opposed to setting the field in the buildconfig?

**Comment by danni** [comment]
Typical use case is when something is cloning a branch as part of a Docker build and the branch gets updated. This won't cause anything in the build to change and instead rebuild from cache.

**Comment by bparees** [comment]
if you're doing something like that it seems like you'd want the buildconfig to be defined with nocache in the first place.  otherwise all your triggered builds are also going to be stale.

**Comment by danni** [comment]
I suppose it depends how often the branch gets updated (ideally I could pin this to actual hashes and avoid the problem completely, but alas).

**Comment by bparees** [comment]
@danni well if instead of cloning within the dockerfile, you let openshift do the clone and did an ADD in your dockerfile, you wouldn't have this problem, right?

**Comment by bparees** [comment]
trello https://trello.com/c/QDZ4fSCo
