### ISSUE TITLE
[Conformance] flake: Extended.deploymentconfigs reaper should delete all failed deployer pods and hook pods

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#9999]
Test flake:

```
deploymentconfigs reaper 
  should delete all failed deployer pods and hook pods [Conformance]
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:517

STEP: Creating a kubernetes client
Jul 22 14:46:17.851: INFO: >>> kubeConfig: /tmp/openshift/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig

STEP: Building a namespace api object
Jul 22 14:46:17.883: INFO: configPath is now "/tmp/openshift/extended-test-cli-deployment-39jil-hjdut-user.kubeconfig"
Jul 22 14:46:17.883: INFO: The user is now "extended-test-cli-deployment-39jil-hjdut-user"
Jul 22 14:46:17.883: INFO: Creating project "extended-test-cli-deployment-39jil-hjdut"
STEP: Waiting for a default service account to be provisioned in namespace
Jul 22 14:46:18.051: INFO: Running 'oc create --namespace=extended-test-cli-deployment-39jil-hjdut --config=/tmp/openshift/extended-test-cli-deployment-39jil-hjdut-user.kubeconfig -f /data/src/github.com/openshift/origin/test/extended/testdata/test-deployment-broken.yaml -o name'
STEP: waiting for the deployment to complete
STEP: fetching the deployer pod
Jul 22 14:51:18.263: INFO: Running 'oc get --namespace=extended-test-cli-deployment-39jil-hjdut --config=/tmp/openshift/extended-test-cli-deployment-39jil-hjdut-user.kubeconfig pod brokendeployment-1-deploy'
STEP: Collecting resource usage data
Jul 22 14:51:18.419: INFO: Closed stop channel. Waiting for 1 workers
Jul 22 14:51:18.419: INFO: Closing worker for 172.18.14.82
Jul 22 14:51:18.419: INFO: Waitgroup finished.
Jul 22 14:51:18.420: INFO: Unknown output type: . Skipping.
Jul 22 14:51:18.420: INFO: Waiting up to 1m0s for all nodes to be ready
STEP: Destroying namespace "extended-test-cli-deployment-39jil-hjdut" for this suite.


• Failure [310.596 seconds]
deploymentconfigs
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:603
  reaper
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:518
    should delete all failed deployer pods and hook pods [Conformance] [It]
    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:517

    Expected
        <string>: NAME                        READY     STATUS    RESTARTS   AGE
        brokendeployment-1-deploy   1/1       Running   0          5m
    to contain substring
        <string>: Error

    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:49
```
##### Additional Information

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/3922/

**Comment by mfojtik** [comment]
@csrwng have you seen this recently? I'm looking at the test and I don't see how this can happen (we are waiting for deployment to reach the complete).

**Comment by csrwng** [comment]
@mfojtik no I only saw it in the test I linked above.

**Comment by bparees** [comment]
closing a flake is a surefire way to cause it to show up again.
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/10777/testReport/junit/(root)/Extended/deploymentconfigs_reaper__Conformance__should_delete_all_failed_deployer_pods_and_hook_pods/

**Comment by smarterclayton** [comment]
Mission accomplished.

**Comment by smarterclayton** [comment]
Looks like #11016.  Needs a bit more triage.

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/742/testReport/junit/(root)/Extended/deploymentconfigs_reaper__Conformance__should_delete_all_failed_deployer_pods_and_hook_pods/

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/815

**Comment by mfojtik** [comment]
@bparees setting this back to P2 as the last time this occurred was a month ago. Feel free to rebump, but I guess this is happening when the node is "slow" or the docker is busy.

**Comment by danwinship** [comment]
same test, different error, not sure if it's the same issue?

    Expected
        <string>: Unable to connect to the server: dial tcp 35.192.11.36:8443: i/o timeout
    to contain substring
        <string>: not found
    ...
    [Fail] deploymentconfigs reaper [Conformance] [It] should delete all failed deployer pods and hook pods

**Comment by mfojtik** [comment]
@danwinship that seems infrastructure flake. can you please open a separate issue?

I believe the original issue here is already solved by garbage collection and I haven't see this reccuring till Apr/20, so closing this.

**Comment by danwinship** [comment]
> @danwinship that seems infrastructure flake. can you please open a separate issue?

at this point, with the logs from the failed test run having been GCed, I don't think it's worth filing. If it shows up again someone can file a flake with more details then.
